### ISSUE TITLE
Taekwondo Sweep throws error

### ISSUE THREAD

**Issue by aMegaSloth** [CleverRaven/Cataclysm-DDA#57779]
### Describe the bug

Using Taekwondo, whenever tec_taekwondo_sweep is performed it will throw the following error:

```
DEBUG    : invalid body part id "leg_lower_l"

FUNCTION : convert
FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
LINE     : 477
VERSION  : 77955ca
```

### Steps to reproduce

1. Use taekwondo fighting style.
2. Start swinging.
3. Will get the debug error when you perform leg sweep. I was doing it against zombies.

### Expected behavior

I expected to not get the error. Looks like there is something happening in randomizing the strike at sub body part?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 77955ca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    No Triffids [no_triffids]
]

**Comment by GuardianDll** [comment]
cannot reproduce it
- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 6779b81 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by aMegaSloth** [comment]
debug.log

```
-----------------------------------------
14:27:17.707 : Starting log.
14:27:17.707 INFO : Cataclysm DDA version 962ad68
14:27:17.707 INFO : [main] C locale set to English_United States.utf8
14:27:17.707 INFO : [main] C++ locale set to 
14:27:17.707 INFO : SDL version used during compile is 2.0.20
14:27:17.707 INFO : SDL version used during linking and in runtime is 2.0.20
14:27:17.756 INFO : Number of render drivers on your system: 5
14:27:17.756 INFO : Render driver: 0/direct3d
14:27:17.756 INFO : Render driver: 1/direct3d11
14:27:17.756 INFO : Render driver: 2/opengl
14:27:17.756 INFO : Render driver: 3/opengles2
14:27:17.756 INFO : Render driver: 4/software
14:27:17.761 INFO : [options] C locale set to English_United States.utf8
14:27:17.761 INFO : [options] C++ locale set to 
14:27:17.761 INFO : Setting language to: 'en'
14:27:17.761 INFO : [i18n] Scanning core translations from lang/mo/
14:27:17.761 INFO : [i18n] Scanning mod translations from D:/Games/Cataclysm/dda/userdata/mods/
14:27:17.911 INFO : Active renderer: 1/direct3d11
14:27:18.001 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
14:27:18.001 INFO : ColorModulatedGeometryRenderer constructor() = FAIL. tex_enable = 1
14:27:18.202 INFO : Setting language to: 'en'
14:28:00.867 WARNING : opendir [D:/Games/Cataclysm/dda/userdata/save/DEBUG/mods] failed with "The system cannot find the path specified.".
14:28:01.272 INFO : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:64: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'class overmap_special' does not track object sources
14:28:38.868 INFO : Loaded tileset: Chibi_Ultica
14:28:38.868 INFO : Loaded tileset: Chibi_Ultica
14:30:49.880 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h:477 [convert] invalid body part id "leg_lower_l"
14:30:50.811 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h:477 [convert] invalid body part id "leg_lower_l"
14:30:51.343 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h:477 [convert] invalid body part id "leg_lower_l"
14:31:37.930 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h:477 [convert] invalid body part id "leg_lower_l"
14:31:40.624 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h:477 [convert] invalid body part id "leg_lower_l"
14:31:41.807 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h:477 [convert] invalid body part id "leg_lower_l"
14:31:58.009 : Log shutdown.
-----------------------------------------
```

Game info:

```
- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 962ad68 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]

]

```

Attached save where I Started a clean world and attacked two zombies. Happens when the sweep kick triggers.
[DEBUG.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8721020/DEBUG.zip)

**Comment by aMegaSloth** [comment]
> cannot reproduce it
> 
>     * OS: Windows
>       
>       * OS Version: 10.0.19044.1645 (21H2)
> 
>     * Game Version: [6779b81](https://github.com/CleverRaven/Cataclysm-DDA/commit/6779b815aaf6f4d096cd08cce00a6eec999666ce) [64-bit]
> 
>     * Graphics Version: Tiles
> 
>     * Game Language: English [en]
> 
>     * Mods loaded: [
>       Dark Days Ahead [dda],
>       Disable NPC Needs [no_npc_food],
>       No Fungal Growth [no_fungal_growth],
>       Bionic Professions [package_bionic_professions]
>       ]

Your game version is older. For what it's worth I think a change within the last 3 days of the build I use broke it. A took about a week before making the last update to the one I posted, and I didnt have issues.

 will attempt top track down which one

**Comment by GuardianDll** [comment]
oookay, i update the game, and now can reproduce it, you were right
/confirmed

**Comment by GuardianDll** [comment]
/confirmed
oookay, i update the game, and now can reproduce it, you were right

**Comment by aMegaSloth** [comment]
Great, turns out I just happened to update to the exact build where things broke.

This is the last 'good' build the error doesn't happen on.
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-05-17-2254

**Comment by arkusix** [comment]
I can confirm this, Muay Thai techniques with sub body parts also throw similar errors.

**Comment by jeffplata** [comment]
Can confirm. Taekwondo attacks triggers it for me.

**Comment by ProfessorRich** [comment]
Confirmed for me on latest build 93a5ad9.

Taekwondo does it - seems to happen when doing lower sweep on Zombies - possibly related to blocking? Just guessing.

It was also reported here #58239

----

12:42:17.792 ERROR : src/generic_factory.h:477 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]] invalid body part id "leg_lower_l"
12:42:17.792 ERROR : src/generic_factory.h:477 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]] invalid body part id "leg_lower_l"
12:42:23.647 ERROR : src/generic_factory.h:477 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]] invalid body part id "leg_lower_l"
[ Previous repeated 1 times ]
12:42:23.647 ERROR : src/generic_factory.h:477 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]] invalid body part id "leg_lower_l"

**Comment by TadhgEomonn** [comment]
I am also experiencing this error:

 DEBUG    : invalid body part id "leg_lower_l"

 FUNCTION : convert
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 477
 VERSION  : 2b29aca

As others have reported, I am getting this on Taekwondo unarmed attacks.

**Comment by TadhgEomonn** [comment]
Has this bug met the requirements for confirmation. If not, what more is required?

**Comment by anothersimulacrum** [comment]
It has.

**Comment by TadhgEomonn** [comment]
Thank you anothersimulacrum. Will patiently await a resolution.

**Comment by TheShadowFerret** [comment]
Can no longer reproduce
![image](https://user-images.githubusercontent.com/99621099/184524021-bd0331ef-6f90-478b-bb9a-f8799f0fc32f.png)

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: bd5813a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA]
]
