### ISSUE TITLE
Modders have lack of way to change the regional map settings

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57788]
### Is your feature request related to a problem? Please describe.

Right now the only way to change the region_settings is copypaste it with your changes, which is fine if your mod is total conversion, but not so much, if you just want to add a few flowers. in second case it is really bad for mod maintenance (you need to update the mod regional settings each time the original file was changed) and also looks ugly.

### Solution you would like.

Add some way to modificate the existed region_settings.
The best would be to insert or overwrite the fields to new value using construction similar to `MIGRATION` type
for example:
```json
[
  {
    "type": "region_change",
    "id": "magiclysm_f_moonflower",
    "target_id": "default",
    "extend": { "region_terrain_and_furniture": { "terrain": { "t_region_shrub": { "f_moonflower": 2 } } } }
  }
]
```

### Describe alternatives you have considered.

Make it using inheritance, so modder can copy-from the default region_settings, and add his own parts. Not the best solution, because few mods with construction will overwrite each other

### Additional context

#55164 is a bit dead (guess ill do it using map extras)

**Comment by Maleclypse** [comment]
I’ve marked it as a bug to keep stalebot from eating it since Kevin commented in discord this is a solid feature request.

**Comment by ZhilkinSerg** [comment]
regional_overlay?

**Comment by GuardianDll** [comment]
it can work, but there is 0 info about how it works
if you can point me ill close the request

**Comment by GuardianDll** [comment]
oh god, im so dumb
im sorry
