### ISSUE TITLE
Player should know when a soft container cannot accommodate an item because its parent container is too small to contain the expanded container 

### ISSUE THREAD

**Issue by VoidForge** [CleverRaven/Cataclysm-DDA#57783]
### Is your feature request related to a problem? Please describe.

As title. There is currently no clear message to the player why a soft container that could hold a lot of things cannot because it has already expanded to the maximum volume/weight allowed by its parent container. In the 'i'nsert menu, items that cannot be inserted due to the aforementioned reason are not listed at all, creating frustration and misunderstanding. 

### Solution you would like.

Instead of not listing the items that the soft container itself can hold but the parent container cannot, list them in the menus but grey/red them out and display messages like "The container cannot hold this item because the pocket in which the container is held is too small". 

### Describe alternatives you have considered.

- Keep it the way it is, not making any change
- Find some other way to notify the player of this issue

### Additional context

explanation and screenshots on request

**Comment by mqrause** [comment]
Back when I implemented this, I was asked to omit those entries: https://github.com/CleverRaven/Cataclysm-DDA/pull/42320#issuecomment-662188805
Switching it around to denial messages should be easy, though, if that's preferred.

**Comment by VoidForge** [comment]
> Back when I implemented this, I was asked to omit those entries: [#42320 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/42320#issuecomment-662188805) Switching it around to denial messages should be easy, though, if that's preferred.

That would be much (personally) prefered, although I feel there should be a survey/discussion to assess public opinion.
