### ISSUE TITLE
 DEBUG    : In nested mapgen garden_3x3_1 in mapgen...

### ISSUE THREAD

**Issue by tim110011** [CleverRaven/Cataclysm-DDA#57797]
### Describe the bug

Bug happen when start a new game, debug screen  can be skipped and enter game.

DEBUG    : In nested mapgen garden_3x3_1 in mapgen house_inner_garden on house_inner_garden_south, setting terrain to t_dirtmound (from t_grass) at (16,14) when item seed_sugar_beet existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

 FUNCTION : virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const
 FILE     : src/mapgen.cpp
 LINE     : 2616
 VERSION  : 0.F

### Steps to reproduce

Start a new game then the bug appear randomly.

### Expected behavior

No bug.

### Versions and configuration

- OS: Linux fedora 5.17.7-200.fc35.x86_64
- Game Version: commit: b0d36241dbc47ebed6ab63ff22bca77f0cf7402f
- Graphics version: Tiles
- Ingame language: Chinese (Simplified)
- Mods loaded: dda no_hope blazeindustries no_fungal_growth speedydex StatsThroghSkills
- Game build with Make flags: CLANG=0 CCACHE=1 RELEASE=1 LTO=1 TILES=1 SOUND=1 LOCALIZE=1 LANGUAGES="zh_CN" RUNTESTS=0

### Additional context

debug.log
-----------------------------------------
09:59:55.259 : Starting log.
09:59:55.259 INFO : Cataclysm DDA version 0.F
09:59:55.259 INFO : [main] C locale set to zh_CN.utf8
09:59:55.259 INFO : [main] C++ locale set to zh_CN.utf8
09:59:55.259 INFO : SDL version used during compile is 2.0.22
09:59:55.259 INFO : SDL version used during linking and in runtime is 2.0.22
09:59:55.298 INFO : Number of render drivers on your system: 4
09:59:55.298 INFO : Render driver: 0/opengl
09:59:55.298 INFO : Render driver: 1/opengles2
09:59:55.298 INFO : Render driver: 2/opengles
09:59:55.298 INFO : Render driver: 3/software
09:59:55.300 INFO : [options] C locale set to zh_CN.utf8
09:59:55.300 INFO : [options] C++ locale set to zh_CN.utf8
09:59:55.300 INFO : Setting language to: 'zh_CN'
09:59:55.300 INFO : [i18n] Scanning core translations from lang/mo/
09:59:55.300 INFO : [i18n] Scanning mod translations from ./mods/
09:59:55.300 WARNING : opendir [./mods/] failed with "没有那个文件或目录".
09:59:55.563 INFO : Active renderer: 0/opengl
09:59:56.100 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
09:59:57.571 INFO : Setting language to: 'zh_CN'
09:59:57.592 WARNING : opendir [./mods/] failed with "没有那个文件或目录".
10:00:11.455 INFO : src/mod_tracker.h:64: Tried check if 'LMOE Shelter' had a duplicate, but type 'overmap_special' does not track object sources
10:00:11.738 WARNING : opendir [./save/圣安东尼奥/mods] failed with "没有那个文件或目录".
10:00:21.212 INFO : Loaded tileset: UltimateCataclysm
10:00:21.213 INFO : Loaded tileset: UltimateCataclysm
10:00:28.747 ERROR : (error message will follow backtrace)
    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x26) [0x990dc2]
    ./cataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x1e2) [0x991f74]
    ./cataclysm-tiles(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x14b) [0x9923ee]
    ./cataclysm-tiles() [0xcbd40f]
    ./cataclysm-tiles(jmapgen_objects::apply(mapgendata const&, mapgen_phase, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x26b) [0xcbb5d3]
    ./cataclysm-tiles() [0xcc7a4c]
    ./cataclysm-tiles(mapgen_function_json_nested::nest(mapgendata const&, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0xa4) [0xcc7b60]
    ./cataclysm-tiles() [0xcc7caf]
    ./cataclysm-tiles(jmapgen_objects::apply(mapgendata const&, mapgen_phase, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x26b) [0xcbb5d3]
    ./cataclysm-tiles() [0xcc7a4c]
    ./cataclysm-tiles(mapgen_function_json::generate(mapgendata&)+0x198) [0xcc7e56]
    ./cataclysm-tiles() [0x11804a8]
    ./cataclysm-tiles(map::draw_map(mapgendata&)+0x30) [0xcd1706]
    ./cataclysm-tiles(map::generate(tripoint const&, time_point const&)+0x2a2) [0xcb5f18]
    ./cataclysm-tiles(map::loadn(tripoint const&, bool, bool)+0x2c5) [0xc84847]
    ./cataclysm-tiles(map::load(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&, bool, bool)+0x191) [0xc84d53]
    ./cataclysm-tiles(start_location::prepare_map(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&) const+0x39) [0xfca6e1]
    ./cataclysm-tiles(game::start_game()+0x342) [0xa58d8e]
    ./cataclysm-tiles(main_menu::new_character_tab()+0xdbd) [0xc66eb9]
    ./cataclysm-tiles(main_menu::opening_screen()+0xa59) [0xc67bc7]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    DebugLog(DebugLevel, DebugClass)
    ??:?
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    ??:?
    jmapgen_terrain::apply(mapgendata const&, jmapgen_int const&, jmapgen_int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    <artificial>:?
    jmapgen_objects::apply(mapgendata const&, mapgen_phase, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    ??:?
    apply_mapgen_in_phases(mapgendata const&, std::vector<jmapgen_setmap, std::allocator<jmapgen_setmap> > const&, jmapgen_objects const&, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) [clone .lto_priv.0]
    <artificial>:?
    mapgen_function_json_nested::nest(mapgendata const&, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    ??:?
    jmapgen_nested::apply(mapgendata const&, jmapgen_int const&, jmapgen_int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    <artificial>:?
    jmapgen_objects::apply(mapgendata const&, mapgen_phase, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
    ??:?
    apply_mapgen_in_phases(mapgendata const&, std::vector<jmapgen_setmap, std::allocator<jmapgen_setmap> > const&, jmapgen_objects const&, point const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) [clone .lto_priv.0]
    <artificial>:?
    .LTHUNK8.lto_priv.1
    <artificial>:?
    mapgen_factory::generate(mapgendata&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const [clone .constprop.0]
    <artificial>:?
    map::draw_map(mapgendata&)
    ??:?
    map::generate(tripoint const&, time_point const&)
    ??:?
    map::loadn(tripoint const&, bool, bool)
    ??:?
    map::load(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&, bool, bool)
    ??:?
    start_location::prepare_map(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&) const
    ??:?
    game::start_game()
    ??:?
    main_menu::new_character_tab()
    ??:?
    main_menu::opening_screen()
    ??:?
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/mapgen.cpp:2616 [virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const] In nested mapgen garden_3x3_1 in mapgen house_inner_garden on house_inner_garden_south, setting terrain to t_dirtmound (from t_grass) at (16,14) when item seed_sugar_beet existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

More additional context:
  find ./Cataclysm-DDA/ -mindepth 1 -maxdepth 1 -iname '*'
./Cataclysm-DDA/cataclysm-tiles
./Cataclysm-DDA/lang
./Cataclysm-DDA/config
./Cataclysm-DDA/LICENSE.txt
./Cataclysm-DDA/data
./Cataclysm-DDA/font
./Cataclysm-DDA/gfx
./Cataclysm-DDA/sound
./Cataclysm-DDA/LICENSE-OFL-Terminus-Font.txt
./Cataclysm-DDA/save
./Cataclysm-DDA/templates
./Cataclysm-DDA/version.txt

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12274.
