### ISSUE TITLE
<Bug> Power Armor Hauling Frame Definitions not found along with other PA

### ISSUE THREAD

**Issue by GexitheHundredth** [CleverRaven/Cataclysm-DDA#57815]
### Describe the bug

When I select Power Armor Hauling Frame it gives me the following error message:

`DEBUG    : Missing item definition: power_armor_frame_on

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 2321
 VERSION  : f5861b7`

It also prevents me from equipping it with or without Power Armor

### Steps to reproduce

1. select power armor hauling frame
2. see error message
3. try to equip said equipment
4. can't

### Expected behavior

I expected the Power Armor Hauling to be able to be equipped with power armor

### Versions and configuration

OS: Windows 11
Branch: Experimental
Platform: Windows x64 (64-bit)
Version: f5861b7 (tiles)
Build: 2022-05-20-0847

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12274.
