### ISSUE TITLE
Crash on latest stable while searching through items

### ISSUE THREAD

**Issue by Yittri** [CleverRaven/Cataclysm-DDA#57812]
### Describe the bug

I'm trying to find an item on the ground by searching for "ga" but this crashes the game consistently. I'm using a linux machine with endeavour os if that makes any difference. Also not using a launcher.

### Steps to reproduce

1. Pickup items at players feet (I have this set to <kbd>,</kbd>)
2. Press <kbd>/</kbd> to search.
3.  Enter `ga` and press enter.
4. Crash.

### Expected behavior

The game should not crash and should show relevant items.

### Versions and configuration

- OS: Endeavouros
- Game Version: 0.F-3
- Graphics: Tiles
- Ingame language: English
- Mods loaded: None

### Additional context

I could not locate a crash log but here are the debug log and save file.
- debug.log file:
[debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8738771/debug.log.zip)
 - save file:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8738779/save.zip)

**Comment by ZhilkinSerg** [comment]
See whether it is reproducible on latest experimental version. We won't release 0.F-4.

**Comment by Yittri** [comment]
This does not seem to happen on latest experimental. 
So as I gather, before making a bug report I should check with the latest experimental release. Also where are the crash logs located? I couldn't find any.

**Comment by BrettDong** [comment]
> Also where are the crash logs located? I couldn't find any.

`config/crash.log`

**Comment by ssdaniel24** [comment]
Same problem on version 0.F ([0.F.3-2](https://archlinux.org/packages/community/x86_64/cataclysm-dda-tiles/)), noticed that the game crashes if no items matching the search (filter) criteria are found.
