### ISSUE TITLE
Make stored books show up in the read menu

### ISSUE THREAD

**Issue by FIM43-Redeye** [CleverRaven/Cataclysm-DDA#57817]
### Is your feature request related to a problem? Please describe.

When books are stored in a carried device (smartphone, e-ink tablet PC) and the read menu is used, stored books don't show up. This requires manually activating the device, which can be a little clumsy.

### Solution you would like.

Read menu views all books available to the player, including stored books.

**Comment by fairyarmadillo** [comment]
If this gets added I hope there would be some indicator in the book list that a given book was a digital and not a physical copy. I scan all my books for recipes but keep hard copies so I can study without wasting batteries.
