### ISSUE TITLE
Rubik has bad bedside manners

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#57827]
### Is your feature request related to a problem? Please describe.

A discussion on the discord led us to the conclusion that Rubik is kind of an asshole surgeon.  I mean which world did this guy even get his medical license from?
From what I understand the Exodil want to continue trading with Humans and therefore should try to follow some medical practices, or that might not be too good for their reputation.

1. If its winter you can get frostbite and I assume freeze to death while under surgery. Please Rubik give me a blanket I'm freezing.

2. Rubik will let you die of dehydration while under the knife, it's kind of rude honestly. Surgeons usually try to avoid their patients dying even if they didn't cause it.

3. There's no compensation for failed installations, just whoops you lose your priceless CBM and I still get paid lmao. 

4. In that same vein I'm not sure the intended fail chance but 9% fail rate was mentioned as something a user had seen. Personally I wouldn't want a surgeon with a 9% fail rate touching me.

5. Some flavor text upon waking up from surgery with a success or a failure, instead of the current implementation of waking up, looking at Rubik and he shouts at you "I think I just heard some loud thuds."

### Solution you would like.

1. For this options discussed were central cooling in the entire building, or just the office Rubik lives in. Or using the sleep with a blanket stuff to maintain comfortable.

2. IV fluids/banana bag of some sort maybe like a real surgeon.  Some "hacky" stuff to reset hunger/thirst if below a certain level near death while under the knife I suppose would be alright. This could also be used as an easy quest for Rubik, collecting blankets and IV fluids, I don't think that would be something they carry with them through jumps.

3. Increase of faction trust or some kind of payment upon CBM failure.

4. Make the cyborg better at his job if the failure rate is not intended.

5. Immersion and lore and all that "junk".

### Additional context

Any discussion on additional issues with Rubik or other ways to solve the issues outlined would be appreciated.

**Comment by PatrikLundell** [comment]
I'm not sure the Exodii have any use for A/C or heating. They presumably have all the temperature control they need installed (although the CBM available to the player is somewhat weak in its performance).

Surgeons tend not to operate on patients that are not in shape for operation (see South Africa's former(?) health minister who had a liver transplant cancelled due to being too intoxicated). If the character is thirstier than "thirsty" he ought to refuse and say the player would need to be sufficiently hydrated (in his weird dialect, of course). For hunger I guess starvation level of hunger would be needed to reject an operation.

Blanket magic (using player supplied blanket) would make sense, but currently walking to the operating theater, operation, and the trip back is abstracted away, so implementing it might be tricky.
However, a quest to fetch blankets and IV fluid that then would be used as needed during operation if available would be nice, but it might be hard to implement.

**Comment by Benny-Bear** [comment]
> I'm not sure the Exodii have any use for A/C or heating. They presumably have all the temperature control they need installed (although the CBM available to the player is somewhat weak in its performance).

My thought would be less the Exodil need temperature control but possibly their supplies. I'm not sure what building material they use but its probably fairly hot in there in the summer. Maybe their fuels or any gasses they have wouldn't be able to handle the cold and or hot temperatures. 
That's the only line of thought I can think of to support that way of solving the problem.

**Comment by PatrikLundell** [comment]
Temperature sensitive things can be stored in the subterranean level(s?).

It looks like the building is made out of metal, so it ought to get rather hot in summer, but the game's temperature logic seems to be that the above ground temperature is the same regardless of whether you're inside or outside (and, of course, of building materials).

**Comment by estebandellasilva** [comment]
Regarding the failure chance ... maybe he can offer you a better chance at a higher price?
Pay More, get better Treatment and better chances of sucess

**Comment by PatrikLundell** [comment]
That's a horrible suggestion. "Pay more, and I'll try to be sober and clean the equipment" level of horrible.

**Comment by estebandellasilva** [comment]
> That's a horrible suggestion. "Pay more, and I'll try to be sober and clean the equipment" level of horrible.

But its a reality thats happening kind of in the real world. If you can afford it to go to a better doctor you would do it.
If you can afford the better medication you would proably do it, and so on.

**Comment by PatrikLundell** [comment]
Rubik probably doesn't have many people to trade with, so it would be in his interest to keep you alive.

**Comment by estebandellasilva** [comment]
> Rubik probably doesn't have many people to trade with, so it would be in his interest to keep you alive.

I agree with you on that ... but its an apocalypse so the resources are kinda limited ... and last time i was at this place he asked only for 20$(of stuff) to install a cbm ... sooooo if i pay him more he could justify using the better stuff which increase the chances not to fail? I mean i dont think he is intentionally trying to kill you but accidents happen if you dont have enough of the good stuff to not fail (i know that when you do it via autodoc that you only need anesthetic, but if he does it he might need other resources)

**Comment by PatrikLundell** [comment]
If he had that option he should have offered that one first, and the cheap one only if you wouldn't be willing to pay to maximize the profits.
Note, however, that the failure rates are low enough that catastrophic failures can't happen, so it's a matter of minor damage healed in a few days and a lost CBM. I wouldn't be surprised if that's what they do with themselves.

**Comment by Benny-Bear** [comment]
Maybe being able to buy some sort of insurance for a rare CBM during install, pay some portion of the CBM's cost possibly exceeding the cost of said CBM. If the install fails he will give you a replacement or say one will be made and you can pick it up in a few days.

**Comment by toweroglass** [comment]
I decided to install a CBM because a portal storm started and hey why not. the quadrupeds killed the shit out of me while i slept.
I know it's not rubik but still not an ideal situation.

**Comment by PatrikLundell** [comment]
I believe that should be a completely separate bug report. What I suspect happens is that the quads get hostile towards something spawning, and the hostility logic is lacking in that hostile critters are hostile towards everything except their own faction (dogs, for instance, attack everyone when going hostile).

If my suspicion is correct, it will also lead to nearby wildlife to both go hostile and to move around chasing hostiles, and so get drawn into your camp if you're unlucky. Being indoors may help against portal enemies, but not moose and bears.

I apparently was lucky with my installation spree (forgot to disable the blasted storms when upgrading to a newer experimental)...

**Comment by BaumgeistOne** [comment]
> I believe that should be a completely separate bug report. What I suspect happens is that the quads get hostile towards something spawning, and the hostility logic is lacking in that hostile critters are hostile towards everything except their own faction (dogs, for instance, attack everyone when going hostile).

Yes, I have seen this happen too. To be honest I tried to do the Hub 01 quest of staying outside in a portal storm, and figured the quads would kill all the enemies... which they did, but... yeah, after that they started shooting at me, which took me by surprise.
