### ISSUE TITLE
Vehicles skill shouldn't use focus

### ISSUE THREAD

**Issue by Nerezza** [CleverRaven/Cataclysm-DDA#57844]
### Is your feature request related to a problem? Please describe.

I find it strange that driving with skill training toggled on makes your character drive with intense focus that leaves you mentally drained within minutes of getting behind the wheel.

As someone that drives everywhere irl, I can say from experience (as can many other people) that driving around is rather calm or boring most of the time.

### Solution you would like.

I'd like to see the Vehicles skill disconnected from focus for behind-the-wheel training. Your skill in vehicle control is something that passively increases irl the more you drive irl, unless you're a race car driver that has to intensely learn a track layout and the safe maximum speeds for corners and straights.

**Comment by PatrikLundell** [comment]
If it's of any help, the drain stops once you get the skill up to 10.0, as does skill rust, so just hang in there, as it doesn't take that long to reach this point (I think it took me less than a season).

**Comment by fairyarmadillo** [comment]
It'd be neat if activities had mental activity levels similar to physical ones.

**Comment by Inglonias** [comment]
From a game design standpoint, that's a really elegant solution. I like it. In terms of the effort required, yeesh... You're basically talking about overhauling the focus system and adding mental activity levels for every activity in the game. Worse, driving a vehicle and learning a skill through experience aren't activities themselves, so that's at least one special case.

**Comment by Zireael07** [comment]
@fairyarmadillo At this point, I really suspect this "focus rework" is one of the mythical features that will never materialize (there are quite some)

**Comment by fairyarmadillo** [comment]
We've seen bigger and more unexpected changes come out of nowhere! It's mecessary for drugs to make sense again, so it has to happen at some point.
