### ISSUE TITLE
Make microwaves installable and function as cooking appliances

### ISSUE THREAD

**Issue by Secret-Cisco** [CleverRaven/Cataclysm-DDA#57847]
### Is your feature request related to a problem? Please describe.

Microwaves exist but cannot be used for their original purpose, only scrapped for parts.

### Solution you would like.

Allow microwave ovens to be installed on power grids and used to cook food. Realistically, microwaves don't cook food the same way as a regular oven and are usually much faster (and in many cases create less appealing food) so they could have separate, faster, recipes with possibly different results.

### Describe alternatives you have considered.

Alternatively, microwaves could function the same as any other heated cooking tool and use all the same recipes. Microwaves could also be modified to mount on vehicles.

**Comment by PatrikLundell** [comment]
As you pointed out, microwaves would require different recipes, and it would be a lot of work to make them (and it would clutter the list of recipes even further).
It certainly would make logical sense to have them as appliances and vehicle parts, but the implementation of the recipes would be a massive task.

An alternative to separate recipes would be refined tool qualities such that a regular oven has a "food heating" food quality in addition to some other qualities ("frying", "grilling", ...?), while a micro has only that one at a higher level. It would still be a massive task to go through all recipes that actually performs cooking (as opposed to just "mixing" cold ingredients, like e.g. making a sandwich) to assign the appropriate qualities to them.
I don't think higher tool quality than the minimum required does anything currently, but when such support was added it might allow micros to actually be faster, but until then you'd probably have equipment that takes the same time as a regular oven for heating, but isn't useful for anything else, unless specific higher heating quality requiring recipes are added.
I think a more granular tool/equipment functionality is there the game is heading, but it's likely to take time to get there.
