### ISSUE TITLE
(e)xamining a creature allows bypassing "Inattentive" trait

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#57842]
### Describe the bug

(e)xamining a creature allows you to see the intent of said creature, bypassing the "Inattentive" trait, which normally overrides it to be "Unknown".

### Steps to reproduce

1. Create a character with the "Inattentive" trait
2. Look at a creature (x, move cursor over)
3. Notice the intent being "Unknown"
4. (e)xamine that same creature.
5. Notice the intent not being "Unknown"

### Expected behavior

The "Unknown" intent would apply while (e)xamining creatures.

### Screenshots

![ddia1](https://user-images.githubusercontent.com/32048635/169671943-1031d00b-833f-471e-b75d-3a6ec3047b24.png)
![ddia](https://user-images.githubusercontent.com/32048635/169671945-b05b66b2-ca66-4204-8cf5-cfbf5f777b62.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 77955ca [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Can reproduce. TIL of that menu, I quite literally never saw that before. The dev who implemented (@mkrutov) this probably missed this one just like I did. Good catch!
