### ISSUE TITLE
Crafting Woods Meat Soup Output to low (probably the case with most soups)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#57848]
### Describe the bug

Most Soup Recipes are weird that the Volumes dont really match up correctly.

For Example the Woods Meat Soup 3L Version (the Version i cooked)
Requires
3L of Bone Broth/Broth/Pine Needle Tea
1,5l Of Meat (Salted Meat Slices in my Point)
3l Of Veg (canned or cooked Beans)
2,5l of Water (which will be discarded as a byproduct)

And it Makes 3L of Soup

### Steps to reproduce

Craft the Woods Meat Soup 3l Version

### Expected behavior

The Recipe Should Require 2 x 3l Jars and Create Double the Amount
This is probably a case with most Soups kinda.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1706 (20H2)
- Game Version: 01f7b57 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by arthurmmaia** [comment]
Hey, me and @yanpisani would like to work on this issue.

**Comment by Maleclypse** [comment]
Go for it.
