### ISSUE TITLE
Summoned vehicles can spawn locked

### ISSUE THREAD

**Issue by shacknetisp** [CleverRaven/Cataclysm-DDA#57859]
### Describe the bug

Due to the changes in #57601 undamaged vehicles can spawn locked; this means that even summoned vehicles like the Mojocycle from Magiclysm can spawn locked from their summoner.

### Steps to reproduce

1. Make a new character.
2. Learn the Summon Mojocycle spell.
3. Cast the spell until you hit the 33% chance for a locked magic motorcycle.

### Expected behavior

Seeing as the Mojocycle is a magic vehicle summoned by your mind out of thin air, you should have the magic keys to go with it.

### Screenshots

![Screenshot of locked vehicle message](https://user-images.githubusercontent.com/2333388/169712702-0d54d9a8-2da6-4c64-a001-f4959fe37e08.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-8601-g051a3c7256 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

AND

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-8594-gbfeb9fd031 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    DinoMod [DinoMod],
    Blaze Industries [blazeindustries],
    Tankmod: Revived [Tankmod_Revived],
    Bionic Slots [cbm_slots],
    Magiclysm [magiclysm],
    Arcana and Magic Items [Arcana],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    No Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Dorf Life [Dorf_Life],
    Caches [P_Caches],
    Beha [beha],
    MST Extra [MST_Extra],
    Medieval Mod Reborn [Medieval_Mod_Reborn]
]

**Comment by GuardianDll** [comment]
cannot reproduce it on the latest version
- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 051a3c7 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
]

**Comment by shacknetisp** [comment]
It's a`one_in(3)` chance, so you might have to try a few times.

**Comment by GuardianDll** [comment]
🤨 
![image](https://user-images.githubusercontent.com/67688115/169710800-492ae8a4-30bc-4163-8d72-f29c4333796a.png)

**Comment by shacknetisp** [comment]
I reproduced it again with:

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-8601-g051a3c7256 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

![2022-05-22-153009_346x34_scrot](https://user-images.githubusercontent.com/2333388/169712702-0d54d9a8-2da6-4c64-a001-f4959fe37e08.png)

**Comment by shacknetisp** [comment]
So I'm stumped, either you had astronomically bad luck or I've messed up some cache or something somewhere :shrug:
