### ISSUE TITLE
The milspec spotlight is dangerously close to your location - Stop smashing?

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#57865]
### Describe the bug

The game is warning me about the impending approach of the immobile milspec spotlight when I start smashing corpses.

### Steps to reproduce

1. Kill a zombie near a spotlight
2. Try to smash it
3. Dialog

### Expected behavior

Immobile enemies should not produce "dangerously close" warnings. Or maybe this is intended. Some immobile enemies are dangerous

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/169725123-4759d510-bb8f-4a77-a963-2f2990a423cb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 051a3c7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by Night-Pryanik** [comment]
> maybe this is intended. Some immobile enemies are dangerous

This. Better safe than sorry.

**Comment by PatrikLundell** [comment]
There is a functionality to block "creatures" from resulting in warnings, on a per "creature" basis.
Sure, it's annoying, but you can do something about the ones you think are no danger to you.

**Comment by NetSysFire** [comment]
I wonder if it would make sense to add this one to the default safe mode exceptions. Not 100% sure if it would help against the warning but it is a start. I would hope this does not exempt the actual searchlight which would alert the turrets.

**Comment by PatrikLundell** [comment]
You shouldn't automatically know whether there are any turrets (left) nearby. On the other hand, I don't think I've seen the searchlights before the turrets (when there are any present) at any time, but I guess you can get unlucky.

**Comment by PatrikLundell** [comment]
Yes, but how would the game know the difference between those searchlights and the same type in road blocks, where the riot control turrets accompany them?

**Comment by Inglonias** [comment]
Alright. Sounds to me that this is intended behavior. Though it may be silly in my current situation, it has a purpose.
