### ISSUE TITLE
Used Car Salesman has two wrist watches on the same hand

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#57866]
### Describe the bug

The Used Car Salesman has both a wrist watch and a gold watch in their starting kit.

### Steps to reproduce

Start a new character as a Used Car Salesman

### Expected behavior

Gold watch OR wrist watch. Not both.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 051a3c7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by Termineitor244** [comment]
/confirmed

And sorry... It was my fault when I did #53034, I will correct it in short.
