### ISSUE TITLE
`PERCENTAGE_DAMAGE` spell flag works incorrect for player

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57875]
### Describe the bug

dealing damage for player with `PERCENTAGE_DAMAGE` flag works incorrect - it picks the max limb hp instead of current one

### Steps to reproduce

1. Make some self harming spell with `PERCENTAGE_DAMAGE` flag (for example, change the `disruption_bolt` to `"valid_targets": [ "self" ]`)
2. Give the character this spell
3. Cast the spell
4. Find it kills you way faster than it must

### Expected behavior

Dealing a correct amount of damage

### Screenshots

Self harm spell with 50% damage
The character
![image](https://user-images.githubusercontent.com/67688115/169888609-d2b6ecdf-da38-48aa-94ed-007dc26182e3.png)
The character after the first cast
![image](https://user-images.githubusercontent.com/67688115/169888555-595379c5-0922-472c-b390-ecb9f3166747.png)
The character after the second cast
![image](https://user-images.githubusercontent.com/67688115/169888459-e03231a6-2282-4181-9ee6-bc4d8208e835.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 714cafd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

### Additional context

PvE effect works fine
![image](https://user-images.githubusercontent.com/67688115/169889163-9c0ef6a9-5ff4-4e39-90e4-115259355fdb.png)

**Comment by Procyonae** [comment]
Would it be better if it hit all bodyparts rather than just the torso too?

**Comment by Procyonae** [comment]
So the issue is it's getting the current hp of the root body part which for the player and NPCs at least is the head but then it's damaging the torso by that amount so if you're at full hp on your head it will always do 50% of your head's max hp while in this image I've set my head hp to 1 and no longer take any damage
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/5b59454f-3528-4c65-afdc-ac55b34e3c7b)
