### ISSUE TITLE
Add another type of hazardous waste storage facility based on the WIPP

### ISSUE THREAD

**Issue by AlbertNewton** [CleverRaven/Cataclysm-DDA#57877]
### Is your feature request related to a problem? Please describe.

Not really. I just think this is a cool idea, cool enough that it might make me figure out how to write json maps.

### Solution you would like.

The Waste Isolation Pilot Plant is something that's been in the works for a while in reality. It's a nuclear waste storage facility built under a salt flat and designed to store the kind of waste that stays hazardous for tens of millennia.
https://en.wikipedia.org/wiki/Waste_Isolation_Pilot_Plant
Of course, in that time, civilisation might collapse, or change beyond recognition. Waste storage facilities might be forgotten, and far future people coming across a mysterious storage bunker from the Before Times might well treat it like CDDA survivors treat pretty much anything that's obviously a deathtrap - grab their best weapons and a shopping cart and dive right in. Only to bring nuclear waste to their encampment and kill hundreds or more people.

Here comes the interesting bit. The WIPP is being designed to actively deter people, with fields of giant protruding spikes, enormous not-quite-even concrete blocks, slabs of concrete hundreds of meters across making the land unusable, highly durable replicas of human bones (or even the real thing).

The general message is:

> This place is a message... and part of a system of messages... pay attention to it!
> 
> Sending this message was important to us. We considered ourselves to be a powerful culture.
> 
> This place is not a place of honor... no highly esteemed deed is commemorated here... nothing valued is here.
> 
> What is here was dangerous and repulsive to us. This message is a warning about danger.
> 
> The danger is in a particular location... it increases towards a center... the center of danger is here... of a particular size and shape, and below us.
> 
> The danger is still present, in your time, as it was in ours.
> 
> The danger is to the body, and it can kill.
> 
> The form of the danger is an emanation of energy.
> 
> The danger is unleashed only if you substantially disturb this place physically. This place is best shunned and left uninhabited.

Maybe even have iridescent cats spawn there as a reference to the Raycat Solution, I don't know.

Lots of things in Cataclysm are designed to be unsettling, so why not another drawn from reality?

### Describe alternatives you have considered.

Not doing it

**Comment by GuardianDll** [comment]
Its in New Mexico, and we are in the New England

**Comment by AlbertNewton** [comment]
I didn't mean literally the WIPP, but facilities inspired by them. We don't have any true hostile architecture in CDDA at the moment, and I think that's a missed opportunity. I mean, imagine it:
Wandering through the ruins of a world that was, you come across a square three overmap tiles across of black concrete, with huge view-blocking granite cuboids scattered densely across it with only a winding labyrinth between them, spikes of rock protruding from the ground, and at the centre a message carved into granite pillars in dozens of languages and styles of pictogram.
"There is nothing useful here, nothing of material, artistic or cultural value. This place was designed to scare people away, because here there is only suffering and death beyond your imagination. Leave, and never return, and if you tell others of this place ward them away."
