### ISSUE TITLE
Large worm blood, and likely others, are counted as human blood.

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#57876]
### Describe the bug

When you draw blood from a large worm, you will be given blood whose material is human blood, instead of blood or mutant blood.
![image](https://user-images.githubusercontent.com/43324177/169903723-84e7db89-38d0-4de5-9513-9b393045c43c.png)

### Steps to reproduce

1: KIll worm
2:Draw blood from worm
3:Notice you have human worm blood

### Expected behavior

You'd expect mutant blood, or animal blood.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: e87eb80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Combat Robotics [combat_robotics]
]

### Additional context

Combat robotics is a mod of my own that shouldn't cause this

**Comment by catdach** [comment]
dup of #52160
