### ISSUE TITLE
Please add a toggle to the "You are at risk of starving!" prompt. It is really a pain in the arse

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#57889]
### Is your feature request related to a problem? Please describe.

The "You are at risk of starving!" prompt gets in the way of doing EVERYTHING. 

I can't pick/drop/move items without a prompt.

I can't drag items without a prompt.

Heck I can't even cook my food without it telling me I'm at risking of starving, like heck man I'm working on it.

### Solution you would like.

Add toggle in the options menu to disable this, or provide keybinding to turn it off like Safe Mode

### Describe alternatives you have considered.

I'd consider eating, if it would let me cook the damn food in peace

**Comment by BaumgeistOne** [comment]
Yeah, that message is a bit too much. Would be better if hitting "ignore" would suppress that message for half an (ingame) hour or so (considering that starving probably takes a lot more time than half an hour). :)

**Comment by RoyBerube** [comment]
Currently it triggers at about 27kCal; for reference 55kCal is normal weight.

I'm thinking of just changing the trigger point to something a lot lower - around 5kCal or so. At that point you would still have maybe a day to find food.

**Comment by DamienRoyan** [comment]
Thank you @RoyBerube
