### ISSUE TITLE
Layering issue with heavy load bearing vest and ballistic vest

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#57888]
### Describe the bug

Wearing a heavy load bearing vest with added pockets (layer "strapped") seems to conflict with ballistic vest (layer "outer").

Message while selecting ballistic vest says "wearing multiple items on your outer clothing on your  is adding encumbrance there."

Message while selecting load bearing vest says "wearing multiple items on your strapped clothing on your  is adding encumbrance there."

18 additional encumbrance is added.

### Steps to reproduce

1. Load attached save.
2. Get rid of worn stuff as needed, keeping both vests.
3. Use armor menu to check layering issue and encumbrance.

### Expected behavior

Either this is a bug, and there should be no additional encumbrance (and the messages should be fixed), or this is expected behavior, then the messages should be clearer as to what the problem is. As it stands, I do not know why there should be a layering issue.

### Screenshots

![Screenshot from 2022-05-24 11-33-05](https://user-images.githubusercontent.com/53833479/170001378-04c460e4-8098-409a-be6d-5aa9cf4a9128.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-8435-g681c2a46f4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Savegame: [Cyberworld.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/8761236/Cyberworld.tar.gz)

**Comment by OtpalTS** [comment]
That's because the US ballistic vest has a bunch of MOLLE pocekts attached to it. Take those off if you plan on using the LBV with it.

**Comment by BaumgeistOne** [comment]
Thanks for the answer. :)

Would be cool if the game UI could tell me that.
(Really like that new pocket system, by the way!)

**Comment by bombasticSlacks** [comment]
This is more of a general bug with the layer conflicts screen which needs to be touched up it happens with other items as well.

I'll leave this since I'm not sure it has been reported though.
