### ISSUE TITLE
Give all creatures, monsters, animals, etc a very slow passive health regen

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#57899]
### Is your feature request related to a problem? Please describe.

at first i wanted some way to heal a horse, but thinking about it itd be complex to implement. Should they heal like the player? but the player mostly heals by sleeping, and animals dont sleep. And they dont have limbs so would you just need to bandage and antiseptic their whole body then wait? it just feels like itd be a can of worms.

### Solution you would like.

so, i think a simple way of modelling it would just be very slow passive regen, IE unnoticeable in combat but noticeable in long term. Like each day a creature heals a 1/3rd of its missing HP. so if you have a pet animal thats at very low HP Its not permanently at risk of dying to any small injury and instead you can just leave it out of combat in safety for a couple days and it heals. Maybe robots (atleast the simpler ones) should be exempt from this since they have no natural methods of repairing damage AFAIK.

### Describe alternatives you have considered.

adding in proper handling of medical items, sleep, etc for animals.

**Comment by Entity-y** [comment]
If animals could heal over time I'd be more inclined to bring a dog with me during raids. 1/3rd of it's HP over night might be too generous though. Perhaps another way to heal would be to feed it the food that you tame them with.

**Comment by LyleSY** [comment]
I believe this has been in for years and was added by #13902
