### ISSUE TITLE
Possibility to randomize traits on character generation menu

### ISSUE THREAD

**Issue by ClockworkCryptid** [CleverRaven/Cataclysm-DDA#57908]
### Is your feature request related to a problem? Please describe.

I would like to be able to randomize a specific page of traits in a similar way to when a random character is generated

### Solution you would like.

a keybind, off by deafult, which is only active when point limit is on

### Describe alternatives you have considered.

last bit is not neccesary

**Comment by Maleclypse** [comment]
I’m trying to label this and I don’t understand what you are requesting.
