### ISSUE TITLE
Exodii Stone Barns ought to be more common

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#57910]
### Is your feature request related to a problem? Please describe.

Exodii outposts should be more common
Reasoning:

From what I can see, they have the same weight as the exodii base, and as such are extremely rare, so rare that it could take easily take months in-game to find one - averaging one per overmap.

As they are one of the only methods of finding an exodii base, it would make sense for them to be more common, especially as these are only outposts. As it stands, it's very hard to find the exodii.

Although it is only an anecdote, I have found 4+ TCLs, 3+ Research labs, 3+ Hub01s, the Exodii base, 2 malls, 2 mil bunkers, a military base, 2 missile silos etc etc, before finding even one of these barns. If you'd like, I can provide proof in discord where I posted my merged explored map, but posting it here in github isn't wise due to the sheer size of the image.

### Solution you would like.

Solution: They should be roughly 3x-5x as common as they are. They are small locations, and offer little to the player outside of directions, as such there is little to go wrong if they are made more common - and yet the benefits would be great.

### Describe alternatives you have considered.

Additional exodii locations that offer directions would also be welcome, then the barns wouldn't need to be more common as overall directions would be more common

**Comment by PatrikLundell** [comment]
There are two refugee center missions directing you to the Exodii base as well.

Also. as far as I understand there are resources inside the storage facilities (I've never entered one), which might be unbalancing if the spawns are too common. However, the same rate as the base itself seems a bit low.

**Comment by DamienRoyan** [comment]
Me who found one near spawn in one playthrough and have not seen one since:

0____0

I think this is a good idea. Although as PatrickLundell said, it shouldn't be **_too_** common.

**Comment by Gotdamnmiracle** [comment]
Alternatively, would it be worththile to maybe have this info on the droppods that pop up with all the cyborgs? It seems sensible they'd have some "return to sender" info for after they jump.
