### ISSUE TITLE
The construction menu could use to have more info

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#57927]
### Is your feature request related to a problem? Please describe.

I think that this screen isn't very clear for people who aren't familiar with the items in the game.
![image](https://user-images.githubusercontent.com/24830358/170354591-458feaa9-6359-48c0-91a3-564e0cffa15d.png)

Some items have more information, but it seems pretty inconsistent, and especially appliances seem to be lacking. 

### Solution you would like.

A line of description, perhaps pulled straight from the item.
For electrical things, they should also tell you how much electricity they will use.

**Comment by ERRORCODE509** [comment]
Personally I think the entire construction menu needs an overhaul. It's pretty outdated.
