### ISSUE TITLE
Vehicle ramming should be able to inflict bleeding

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#57921]
### Is your feature request related to a problem? Please describe.

I think that bleeding is a fantastic feature to combat, however, it doesn't affect vehicles, which a lot of the player base uses to fight large groups of zeds.

I think that those things could be merged, as car accidents frequently inflict bad wounds. 
On top of that, it could give a stronger reason to actually use the blade vehicle part over spikes & rams. 

### Solution you would like.

I would like that every ram has a chance to inflict some bleeding, with severity varying on speed and the part that hits, with spikes and blades inflicting the most, and a mattress the least.

**Comment by DamienRoyan** [comment]
This is a good realism suggestion. I feel that the risk of such injury should also skyrocket if there is no seatbelt.
