### ISSUE TITLE
Connecting solar panel appliance serially causes massive slowdown

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#57977]
### Describe the bug

When solar panel appliances are connect serially, in a chain one to another that is, and then to a batter that is then connect to a wall wiring and used to power appliances it causes the game to slow down massively. However, if they are connected in parallel, that is each to their own wall wiring and have the wall wiring connect together and to the battery and a appliances does not cause this slowdown. I imagine their some kind of calculation that grows exponentially every time I connect a solar panel serially. 

### Steps to reproduce

1. Daisy chain solar panel appliances 
2. Game runs slower

Note, I  put down a pair of coffee cups north and south that indicates where the edge of the issue is. The cup closer to the base will be where the slowdown start, the farther cup on each side just outside the slowdown if anyone wants to test the effect.

### Expected behavior

1. Daisy chain solar panel appliances 
2. Game does not run slower

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 9ab7cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    Gun Cotton [guncotton],
    More Survivor Stuff [more_survivor_stuff],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[Everetts.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8790804/Everetts.zip)

At first I thought I was the loot amount, but moving all my stuff changed nothing. I tried removing all my zones, move my companions out of the reality bubble etc. Only disconnecting the solar panels removed the slowdown.

 I  put down a pair of coffee cups north and south that indicates where the edge of the issue is. The cup closer to the base will be where the slowdown start, the farther cup on each side just outside the slowdown. What is interesting is that I also put down plastic supplement bottles  of where the reality bubble should end relative to the coffee cups (each on the opposite side of the base). What tipped me off that it wasn't an item slowdown was the fact that it did not correlate with reality bubble as I know it (120 tiles).

**Comment by Wyrdean** [comment]
Can confirm this, didn't realize it at the time, but I lost a base to this.
