### ISSUE TITLE
Armor and other Recipes causing slowdowns (possibly some recursive recipes)

### ISSUE THREAD

**Issue by hostergaard** [CleverRaven/Cataclysm-DDA#57975]
### Describe the bug

For the last few updates going into recipes, particularly selecting "armor" and to a lesser degree "other" takes a very long time to load.

I believe its because of some recursive recipe because I also happen to note that the hitchiker guide to the cataclysm fails to load any recipe for the latest few updates complaining about recursion, I believe it might be related. Take fx vacuum pump:

https://nornagon.github.io/cdda-guide/#/item/vac_pump

But if you select an earlier verision there is less than issue. Say the verision from 05/15 2022

https://nornagon.github.io/cdda-guide/?v=cdda-experimental-2022-05-15-1852#/item/vac_pump

What more is, my main base is massively slowed down, it takes a long time to sleep and craft. I figure its because of the massive amount of loot I have there, but even getting rid of the usual sinners of glass shards don't do anything to help, so I am wondering if there is some other sinner.

### Steps to reproduce

1. Open crafting menu
2. Try to tab into Armor 
3. Wait for a while while it loads

### Expected behavior

1. Open crafting menu
2. Try to tab into Armor 
3. Open tab quickly

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 9ab7cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    Gun Cotton [guncotton],
    More Survivor Stuff [more_survivor_stuff],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[Everetts.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8790632/Everetts.zip)

There is another bug also in there where my character save gets duplicated for some reason, although they both refer to the exact same save. 
Oh, and I am currently on a older computer, so these slowdowns are probably a bit more noticeable because of it.

**Comment by mqrause** [comment]
/confirmed

![grafik](https://user-images.githubusercontent.com/38702195/170824501-6c3c02b9-0fa2-4648-ad13-7d6b89ebd3c9.png)
Every peak in this is one of the crafting menu tabs, tabbing through from left to right. Most of the cpu time is spent going through the crafting inventory, the relative values are pretty much the same for all tabs.
So it's an issue with calculating available crafting requirements. So basically too many (nested) items are expensive to calculate for too many recipes.
I assume recipe complexity also plays a role there. The weapon category (1st plateau) has 265 recipes, food (3rd plateau) has 739 with pretty much the same length, and armor (the massive 6th plateau) has 1142 recipes, so it's definitely more than just numbers.
