### ISSUE TITLE
Killing leeches/leech cluster when doing hub mission consistently crashes the game (also broke my launcher)

### ISSUE THREAD

**Issue by KingApep** [CleverRaven/Cataclysm-DDA#57979]
### Describe the bug

Killing leeches/leech cluster when doing hub mission consistently crashes the game and it also broke my launcher.

(after reviewing other bugs, something I noticed was the npc hulk crash bug listed eight hours prior to this. This save also has an npc with a firearm whilst my character is melee focused. This may be a correlation without any linked causation however).

(update) I have attempted multiple runs of the same situation and finally seemed to have killed it without crashing. I can't recall which npc commands I ordered or which moves I made, but I feel that perhaps this issue may be the underlying cause: https://github.com/CleverRaven/Cataclysm-DDA/issues/57925

### Steps to reproduce

1. Kill leeches with my character.
2. 2. If it doesnt crash when killing the root leeches (its inconsistent), then approach and kill the leech cluster
3. this will consistently crash the game following a 'waiting turns' brief dialog box

### Expected behavior

That game doesn't crash when enemies are killed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 6027e66 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Launcher log from when I attmept to run it :
CDDA Game Launcher version: 1.5.6
OS: Windows-10-10.0.19041-SP0 (64-bit)
Type: <class 'IndexError'>
Value: list index out of range
Traceback:
File "cddagl\ui\views\main.py", line 1368, in showEvent

File "cddagl\ui\views\main.py", line 3129, in refresh_builds
File "cddagl\ui\views\main.py", line 3168, in refresh_changelog

Since tried catapult and it still crashes the game when killing leeches.
[Hope - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8790995/Hope.-.Copy.zip)

**Comment by animation303** [comment]
that launcher error is unrelated, there is a fix on the github page for it, something about how the changelogs are updated
