### ISSUE TITLE
Completing Missions at Multiple Hub 01s gets "Retrieve Field Data" Stuck and Prevents Interacting with Intercom.

### ISSUE THREAD

**Issue by IncoherentOrange** [CleverRaven/Cataclysm-DDA#57987]
### Describe the bug

Somewhere along the way as I sporadically worked on the Hub 01 mission chain, I found myself unable to interact with the Intercoms at any new Hub 01s I encountered. Only my most-progressed Hub 01 was working as normal, providing trade and quest options after pushing the intercom button. 
Instead, I get the dialog prompt shown in screenshot 1 whenever I talk to any other intercom. Presenting a Prototype I/O Recorder will allow interaction with the Hub as normal, but leaving dialog and coming back will result in the same request. The mission Return Field Data does not mark as completed after presenting the item at the Hub 01 that initiated that instance of the quest and all other Intercoms also request the item, rendering all but the first Hub 01 nonfunctional. For reproduction steps I provide the approximate order I did the Hub 01 quests, in case it had something to do with causing this issue.

### Steps to reproduce

1. Complete Hub 01 Missions Return Field Data, Iron Safari and Hazard Meteorology, then start Steal a Dead Man's Last Words. all at a single Hub 01 [Hub 1].
2. Visit another Hub 01 and undertake mission Return Field Data. Obtain and turn in the Prototype I/O Recorder.
3. Complete Steal a Dead Man's Last Words, Active Noise Control, and then Light Retrieval at Hub 1. Wait one day and obtain Hub 01 Military armor pieces.
5. Attempt to interact with any Hub 01 instance except Hub 1.

### Expected behavior

Approach any previously not interacted Hub 01 instance and be provided with quest Return Field Data. Return Prototype I/O Recorder to Intercom to enable trading and other unlocked dialog options like asking for HWP magazines.

### Screenshots

![image](https://user-images.githubusercontent.com/106454658/170846523-b9730235-5da2-49d1-b18e-f40e28faf843.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 218edd5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

Debug menu cannot complete the Return Field Data mission. Deleting or failing the mission through debug results in its reissuing at any Hub 01 as normal, but the new Return Field Data mission likewise will not be completed when the recorder is turned in and the problem will persist.

**Comment by denistest18** [comment]
he wants the registrar of the robot prototype constantly after the dialogue to talk to him, the registrar and the task of returning the field data is not fulfilled

**Comment by Fosheze** [comment]
/confirmed

Same thing happens to me. I can no longer interact with any hub except the original one and the original one no longer offers any missions. No amount of debug fenagling seems to fix the problem.

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 9c88952 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by User-Happy** [comment]
This is my first post so I apologize for not knowing the etiquette here.
This bug can be resolved by adding the following Var to the, "the intercom" NPC, via the console.

Var: dialogue_intercom_npc_intercom_trade
Value: yes

Because this Var is missing, robofac_intercom.json "id": "TALK_ROBOFAC_INTERCOM", always fails causing
"topic": "TALK_ROBOFAC_INTERCOM_INTRO",  and "topic": "MISSION_ROBOFAC_INTERCOM_1_INQUIRE", to loop.

I have been unable to determine why this Var is not written to the NPC upon completion of 
"id": "TALK_ROBOFAC_INTERCOM_1_JOBS_2", and MISSION_ROBOFAC_INTERCOM_1 is not flagged as finished.

OS: Windows 10
Game Version: cdda-windows-tiles-sounds-x64-2022-12-02-0444

**Comment by TripleSixPeasant** [comment]
I have the same issue on MacOS build, latest experimental.

@User-Happy Could you please let me know how to fix the issue by editing the save/game files directly? I'm not sure how to access the console.

**Comment by User-Happy** [comment]
Sorry I dont know about the Mac version, but the console on windows is
accessed via the  `   key.  (no shift ~)

Full steps are:
` (console)
p (Player)
p (edit Player/NPC)
select the NPC "the intercom"
v (Edit Vars)
enter the Var Key:  dialogue_intercom_npc_intercom_trade
Value:  yes

The intercom can now be accessed normally.
Hope that helps.

**Comment by TripleSixPeasant** [comment]
@User-Happy Ah, you mean the dubug menu. Yes, that fixes it, thanks!

**Comment by Raikiri** [comment]
Encountered the same problem. Broke my progress.

**Comment by mlgproftw** [comment]
Also had the same problem. Except I can't even fix it with debug menu because my intercom despawned for some reason
