### ISSUE TITLE
Unable to Dig up graves

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#57995]
### Describe the bug

Found a grave - was not able to dig it up - thought it was maybe problem with that one grave
Found 2 grave next to each other - still unable to dig them up

Tested with shovel and entrenching tool

### Steps to reproduce

Find grave
Try to dig it up

### Expected behavior

Being able to dig up graves

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/170863584-d06aa441-06ce-42dc-ab46-0efe2858fd02.png)
![image](https://user-images.githubusercontent.com/89189872/170863597-54f233ae-5a8a-4008-b4c6-7ff8c58dad98.png)
![image](https://user-images.githubusercontent.com/89189872/170863610-67a65f1c-e5a1-4200-b02d-cffc6b903d26.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1706 (20H2)
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by andrei8l** [comment]
Works for me:
![Screenshot from 2022-05-29 13-35-18](https://user-images.githubusercontent.com/68240139/170863698-b46dbbed-cd5f-4ae1-87b9-93f79c2eb661.png)

![Screenshot from 2022-05-29 13-35-22](https://user-images.githubusercontent.com/68240139/170863706-e6c4d18e-cab0-40a2-869f-5907cbed52e8.png)

Can you upload your save file please? Maybe those graves have different terrain IDs.

**Comment by estebandellasilva** [comment]
[Wilderness.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8793266/Wilderness.zip)
Had to cut it down a little and move to the graves

**Comment by estebandellasilva** [comment]
Weirdly the graves in the cementary up north a digable
