### ISSUE TITLE
Unknown segfault. May be related to NPC with aftershock laser gun.

### ISSUE THREAD

**Issue by NightPulsar** [CleverRaven/Cataclysm-DDA#57991]
### Describe the bug

Segmentation fault and game crash. Probably related to the NPC firing or reloading an aftershock laser weapon in some manner.

### Steps to reproduce

1. Load attached save.
2. Turn off safe mode
3. Keep hitting tab until game segfaults.
4. If all aggro'd zombies in the area die without a segfault, you got different results.

Has happened at least six times for me.

### Expected behavior

No segfault.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1586 (20H2)
- Game Version: d5502cf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crashlogs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8792561/crashlogs.zip)

Save:
https://www.dropbox.com/s/kfedkha909zqxvy/MarinCityLowCompression.zip?dl=0

Also replicated on latest experimental.

**Comment by RoyBerube** [comment]
Could be same problem as #57925. That crashlog shows it happens on npc::do_reload() same as this one.

**Comment by RoyBerube** [comment]
Can confirm the problem is caused by the npc trying to reload with no ammo. It will take more than just a check for lack of ammo - the npc still tries to reload endlessly.
