### ISSUE TITLE
Outside temperature too low for Autumn

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#57996]
### Describe the bug

I just woke up to Autumn day 66 and figured the items in my fridge are frozen and the thermometer shows -6C.

 I feel like there are multiple issues with this. 

1.  It's too low generally, if I say day 66 is like beginning of November, based on New England avg temp, it should maybe drop to like +4C at most. 
2.  Items in the fridge should not freeze at merely  -6C outside temp during one night. 
3.  Living in closed house with 2 companions, cooking food and working in a workshop with forge etc. should make the house a bit warmer inside than it is outside. The inside temp should not drop to the same -6C as outside just during one night. 

### Steps to reproduce

Change time to autumn and see the temperature. 

### Expected behavior

Having the temperature drop down as the winter gets closer but only about +2 to +5 at the end autumn. 
The temperature in a closed house should stay few degrees above outside temperature. 
Items in fridge should not freeze over night.
(possibly have cooking and crafting recipes that use heat source generate some hot air....)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 9129922 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

So the actual question might be:  Is this working as intended or did the cataclysm changed the weather pattern?

**Comment by Zireael07** [comment]
1) Average temperatures are just that, averages. I can tell you here in Poland, average for November is something similar to what you cite, but that doesn't mean you can't get -5 or so.
2) Cataclysm means no power, so in an unpowered fridge items can and will freeze overnight if temperature drops in the negative. Same thing as plants dying because they spent a night in the negatives due to whatever reason.

**Comment by tinukedaya** [comment]
1. Sure it can get cold, but would be exception. not a continuous thing. 
![image](https://user-images.githubusercontent.com/19891532/170866606-51f2b985-54da-4207-ad63-861dfb3d3d53.png)

In this chart you can see the minimums for November dropping to +3C. And in my play thru I'm still at the beginning of November so i would expect it to be closer to the October minimums... 

2. Well sure, eventually it'll freeze in unpowered fridge. But not over one autumn night. The insulation will hold that for sure. Not to mention, that this fridge in question is actually powered in a house (well a fire lookout tower) that I live in, so all the heat generated by me and my companions an all the crafting/cooking occasional usage of a large heater >>> which leads to point 3. that the temperature inside a house should be different than outside if it's being used...

**Comment by Zireael07** [comment]
aaah if the fridge IS powered (you didn't mention that in OP) it's definitely a bug/oversight

**Comment by tinukedaya** [comment]
I didn't mention it, because I didn't think it was relevant. It shouldn't have had frozen in powerless fridge either over the period of one night. After all, if the temperature inside the fridge is less then set, it will not start heating up, it just stops cooling, So technically, if outside temperature is low enough, it would behave as powerless just insulating it from the outside. 

And that insulation part is what I think ain't working that well.
