### ISSUE TITLE
Regression-cannot extinguish fire lit in an oven by examining the object, another menu pops-up

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58006]
### Describe the bug

cannot extinguish fire lit in an oven by examining the object, another menu pops-up

### Steps to reproduce

Light a fire in an oven
Try to extinghuish it by examining the oven, you cannot

### Expected behavior

IIRC it used to be possible to examine an oven and if there was a fire inside, you could extinguish it. Please bring back this capability.

### Versions and configuration

build type: linux-tiles-x64
build number: 2022-05-28-1015
commit sha: 91299226f02ee9c035ef832dfcc693aee8502a1b
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/91299226f02ee9c035ef832dfcc693aee8502a1b

### Additional context
It is even more a problem when you setup a firewood source, if you cannot extinguish the fire it will burn all your stockpile

**Comment by GuardianDll** [comment]
How do you imagine this? The oven has some extinguisher inside, that extinguish flame by pressing the button?
That was removed with a reason

**Comment by ZeroInternalReflection** [comment]
For the record, tested in "cdda-linux-tiles-sounds-x64-2022-05-29-0616":
Disconnected oven (e.g. as generated in a random house)
- Can start a fire 'in the oven'
- Treated as a 'nearby fire' for crafting
- No option to extinguish a fire when `e`xamining
- Fire can be put out by dropping water on it/`a`ctivating a fire extinguisher
- A firewood source next to the oven will automatically be used to maintain the fire
Oven appliance (after 'connecting to grid')
- Cannot start a fire on this tile

Given that an oven worked as a fireplace in previous versions (it still kind of works now, right up until you want to extinguish it) and we still abstract away putting out a fire in a fire pit, I think the UX here still needs work.  Options include:
1. When examining any tile that's on fire, have the first check be a "This is on fire!  Do you want to extinguish with water/sand/fire extinguisher" menu
2. Prevent the player from starting a fire on a 'disconnected oven'.  While, as I understand it, you _can_ keep a wood fire going inside of a typical oven in real life, I'm betting that it wouldn't do what you need for many of the 'nearby fire' crafting recipes
3. Prevent non-approved fire locations from pulling from firewood sources

**Comment by Qrox** [comment]
Caused by #56807.
