### ISSUE TITLE
Mutating Protective Bark and Shifting Bark doesn't remove worn rigid gear that conflicts.

### ISSUE THREAD

**Issue by LosingHope** [CleverRaven/Cataclysm-DDA#58005]
### Describe the bug

Mutating these two won't immediately remove conflicting armor or clothing, but doesn't allow it to be put back on if it is taken off. 

### Steps to reproduce

1. Wear rigid gear, such as a helmet on the head.
2. Mutate protective bark or shifting bark via any methods.
3. Conflicting rigid gear will not be removed.

### Expected behavior

Rigid gear immediately removed upon mutating.

### Screenshots

![image](https://user-images.githubusercontent.com/106485795/170882994-798bca87-a0e4-4d17-8082-b01e8e519583.png)
Debug used to mutate quickly.

### Versions and configuration

MacOS 12.3.1
Experimental Version cd180bf
Tiles
English Language

**Comment by Demivan** [comment]
This can be combined with #60653 as a way to temporary remove bark.
