### ISSUE TITLE
The 'Unload containers' zone should have its own button.

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#58019]
### Is your feature request related to a problem? Please describe.

I think that this zone is very unclear in how it works. 
From what i understand, this zone only works if you don't have any other 'loot' zones, such as Loot: Guns under it.

### Solution you would like.

I think it should instead work like a normal work zone with its own button.
Something like this : 
![image](https://user-images.githubusercontent.com/24830358/170895199-5d9fc171-1230-4385-a501-55f2b53415ab.png)

**Comment by bombasticSlacks** [comment]
It is an optional part of sorting normally and very useful for most workflows. 

If you have a field of corpses with bags and junk on them. Unload containers + a guns zone will unload all the corpses, unload their bags and drop the still loaded guns in the guns zone. The idea being you don't want to unload something you are manually sorting. 

I have no idea what use case their would be for just unload that would require it being a seperate button.

**Comment by BaumgeistOne** [comment]
Well, the trouble start when you have defined a "corpse" or a "other" zone. Because then, the corpses will be sorted there, and no unloading will take place. Because you wanted to sort them there, yes. But if I want them sorted there, but also want to strip them - well, gotta do some zone disabling and afterwards reenabling. It is a tiny bit annoying. Having some kind of method of telling the game "Unload what is in that zone, no matter what other zones are there" would be very helpful, I think.

**Comment by mkrutov** [comment]
yes please, exactly for reasons in previous comment. +1

Another example: 
you have a field of corpses covered by unsorted loot and unload containers zone, plus a "container" storage and "food" storage.

you do the sorting stuff, then what happens is MRE containers are taken off the corpses and are sent to.. container storage, despite having food inside of the container. It has lead to some confusion as to "where did all my food go?"

**Comment by bombasticSlacks** [comment]
It sounds like the not super complicated solution for this that isn't incredibly complex and bloated is to add a configure option for unload so that it can have filters (and remove the corpse zone all together) and an option to "always unload" vs "unload if unsorted"

**Comment by bombasticSlacks** [comment]
This was implemented so I'm gonna reopen and close as done
