### ISSUE TITLE
Full brightness outside in the middle of night

### ISSUE THREAD

**Issue by petermorck** [CleverRaven/Cataclysm-DDA#58010]
### Describe the bug

I had been trying to sleep in a lean-to while there was a fire 2 tiles next to it.
After failing to fall asleep due to shivering I noticed the fire had died, so I stepped out and lit the fire again but it didn't seem to light the area up, so I started walking around and noticed everything became lit and it says "Light: bright" even though it's the dead of night and I'm well away from the fire.
I see there was a similar issue (#30732) a long time ago which was closed (in 2019).

### Steps to reproduce

Not sure... I don't have a save before the situation occured, but I did something like this:
Start a fire in a fire ring outdoors during night time (in darkness).
Go to a lean-to 2 tiles west of the fire and try to sleep.
Fail to sleep a few times due to shivering.
Realize fire has died.
Move 1 tile east and re-light it.
The fire ring tile does NOT seem to light up.
Walk around a bit to see what it looks like.
Notice the entire outdoors are suddenly fully lit as if it's day.

### Expected behavior

I'm expecting it to be dark outside in the middle of the night.

### Screenshots

![image](https://user-images.githubusercontent.com/20305709/170887747-37b8b9b2-b2f0-4e94-aab8-e097a403679b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 9ab7cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

[The Undiscovered Land during bright night.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8794194/The.Undiscovered.Land.during.bright.night.zip)

**Comment by Hirmuolio** [comment]
Spring 62 is approximately April 20th. 
Dead of night is a bit vague time. It is somewhere between 00:00-04:00.
Sunrise occurs at 04:42 (irl. About same ingame). You get very little or darkness at that time of year on boston latitude.

Loaded the save and the time is 04:35 so just few minutes until sun rises above horizon.

Maybe the time strings should be scaled to sun position to avoid confusion.

**Comment by petermorck** [comment]
> Spring 62 is approximately April 20th. Dead of night is a bit vague time. It is somewhere between 02:00-05:00. Sunrise occurs at 04:42 (irl. About same ingame). You don't get much darkness at that time of year on boston latitude.
> 
> Loaded the save and the time is 04:35 so just few minutes until sun rises above horizon.
> 
> Maybe the time strings should be scaled to sun position to avoid confusion.

But is it really "bright" in all tiles at that time? I just came from stable 0.F-3 and I'm pretty sure I didn't have this much brightness until like 5:30, but perhaps it's changed since then?

**Comment by Hirmuolio** [comment]
Yes the lighting is bright when sun is about to rise.
The sunlight thing change it is not on the 0.F.

**Comment by petermorck** [comment]
> Yes the lighting is bright when sun is about to rise. The sunlight thing change it is not on the 0.F.

Ok that's fine. But then maybe as you said earlier the time for that message should change as "dead of night" would imply that it's basically as dark as it gets, right? It would make more sense to have "Early morning" before dawn.
Should I change the title of this issue (Can I?) or submit a new one?

**Comment by Hirmuolio** [comment]
Already did a pull to change the times #58030
