### ISSUE TITLE
Zombies might be able to grab two people at once.

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#58011]
### Describe the bug

Here is a screenshot that explains the main source of my suspicions :
![image](https://user-images.githubusercontent.com/24830358/170889790-ba3da90b-18ed-4599-8791-c18336296076.png)

I am not sure if the zombie is actually grabbing, or the game is just spazzing out with the status.

### Steps to reproduce

1. Get close to a zombie with a NPC
2. Get grabbed.
3. Watch as it looks like both you and the NPC are grabbed.

### Expected behavior

I am not sure if this IS expected behavior!
If it is, i guess we only need it to be clearer.
If it is not, i suppose the status icon should be removed, or zombies should have more expansion in their grabbing ability.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Termineitor244** [comment]
/confirmed

It has happened to me too.

**Comment by gtim** [comment]
Seems a duplicate of #54608

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
