### ISSUE TITLE
Pushing grabbed vehicle makes you move on tile with that vehicle

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#58027]
### Describe the bug

Pushing grabbed vehicle makes you move on tile with that vehicle instead of actual pushing.

### Steps to reproduce

1. Grab some vehicle.
2. Move in the direction of this vehicle, i.e. try to push it.
3. Observe you're walked on tile of this vehicle.

### Expected behavior

Pushing vehicle works.

### Screenshots

https://user-images.githubusercontent.com/11132525/171002378-74bf9ed1-c718-4109-a1c5-d7004a736a0f.mp4

### Versions and configuration

Windows 10 x64, 0.F-8656.

**Comment by PatrikLundell** [comment]
/confirmed

Although I'm not sure it's a bug as such, but rather a feature to simplify handling bikes and the like in tight spaces.

A little bit of testing:
- Welding cart (single tile): Gets pushed normally
- Shopping cart (single tile): Gets pushed normally according to memory (didn't test it now).
- MC: Flips if you push the front, pushed if you grabbed the back.
- Generator (two tiles): Pushed when you push the back (the wheel tile), flips when the front is grabbed.
- Bicycle: same as MC, according to memory.
- MC with side carriage: Gets pushed normally when the back is grabbed, but flips when you then pull it.

Based on testing the MC, it seems like grabbing a central tile results in grabbing the front one (I couldn't push it sideways).

Thus, if you were to grab the basket end of the bike you ought to succeed in pushing it.

**Comment by PatrikLundell** [comment]
Well, real life vehicles don't swivel around the center when turning either, etc. so we're definitely in game mechanics territory.

**Comment by Night-Pryanik** [comment]
Ok, based on feedback, consider it a feature rather than a bug. Closing.
