### ISSUE TITLE
New industrial professions and items

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#58025]
### Is your feature request related to a problem? Please describe.

There is a lack of proper PPE in the game, even though this kind of equipment would be items that are very useful to have in an apocalypse... In the same vein, there is a lack of professions with proper personal protection equipment.

### Solution you would like.

More hard hats! Maybe, the hard hats used in industrial environments come in many varieties, not just in color but in protection too.

Hard hats add-ons: Hard hats are often used in conjunction with certain items to better protect the user, why not use them in CDDA too?

Coverall/overall/boiler suit: These suits cover the whole body (excluding the head/hands and feet), commonly used to protect the user (and the user clothes) from chemical splatter and to proportionate a comfortable protective garment, they come in many varieties in color but in use too, most are fire-resistant and others have certain properties that make them very useful in dangerous situations. This item could be improved with some kevlar (like 50 / 75 % of kevlar coverage if you want to mantain the mobility of the suit) for better protection, it certainly works as a good alternative to a survivor duster or whatever, since this is an item designed to cover all your body comfortably, and has some thickness by itself.

New professions: Industrial engineers/workers, with all kinds of PPE and related proficiencies.

And even more...

### Describe alternatives you have considered.

To only add the hard hats related changes, like in #58020

**Comment by anothersimulacrum** [comment]
The bionic starts are already a mod for this reason.

**Comment by Inglonias** [comment]
I forgot that had been moved to a mod.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
