### ISSUE TITLE
Important Faction NPCs not immune to portal storms

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#58023]
### Describe the bug

Labeling this as a bug, as it isn't intended behavior. 
Important npcs such as rubrik or refuge camp npcs are not immune to, or have any methods of dealing with portal storms.

### Steps to reproduce

1. Visit faction base
2. Wait until portal storm
3. Notice how they get killed, kill themselves or eachother by accident due to the portal storm

### Expected behavior

Npcs should have some way of dealing with storms, even if it's just them being flat immune to the effects

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: e87eb80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Combat Robotics [combat_robotics],
    SpeedyDex [speedydex],
    Customizable Guns [customizable_guns],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

It's quite annoying when the npcs you spent weeks traveling to meet die due to a portal storm just because you camped nearby.

**Comment by jokermatt999** [comment]
Looks like this is still an issue. Frustratingly, it seems to have gotten my ranch foreman. Portal storms are a cool idea (reminds me of the blowouts from STALKER), but incredibly annoying to protect NPCs from. You can send out followers on a camp mission, but non-followers seem to leave shelter to kill monsters.
I think flat out immunity is a decent stop gap fix, because this can completely ruin an otherwise safe NPC hub.

**Comment by I-am-Erk** [comment]
This remains a pretty core issue. We need better long term solutions, but for stable, we should add some kind of jank fix that we can put into stable, but revert for H-experimental. I do not know enough about how portal storms work to suggest a jank fix though, open to suggestions. I suspect we could do something like check your location against a list of "protected maps" and turn off storm-related counters and checks if any of those maps are loaded into the reality bubble.
