### ISSUE TITLE
New scenario: Horror Cabin

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#58024]
### Is your feature request related to a problem? Please describe.

I thought it would be cool to have an scenario in a typical horror movie environment, like a cabin in the middle of a lake, with killer ferals based around typical antagonist of these kind of movies (Like Jason or Freedy Kruger).

### Solution you would like.

A new scenario: Horror Cabin

Where you start on an island cabin on the middle of a lake,  the island being quite big, with forests and a small ship dock too, maybe even some hidden places where something interesting could happen...

New enemies:

Feral killers: These enemies are varied, but most would be masked in some way and be equiped with some kind of weapon typical of a horror movie, like a certain feral killer using a machete...

Feral killers (shadows): The same as the normal versions, but these versions spawn randomly when you are outside of the cabin with an EOC, they vanish when killed and are practically endless, if you want to stop them from spawning, you will need to search on the island for the real version of the killer, and kill it for good.

Horror monster: Some otherworldly monster typical of some horror movies.

Scenario professions:

Some of the new swimming ones, as well as some basic new professions based around typical characters in horror movies.

### Describe alternatives you have considered.

To just add some feral killers and call it a day haha.

### Additional context

I will probably take a good time to finish this, I still have to finish or edit some other scenarios.

**Comment by Inglonias** [comment]
We already have an overmap special representing cabins on a lake. It's possible you know about it already, but if you don't want to make a whole new overmap special, use the cabin_lake start point.

**Comment by Termineitor244** [comment]
> We already have an overmap special representing cabins on a lake. It's possible you know about it already, but if you don't want to make a whole new overmap special, use the cabin_lake start point.

I have seen the cabins, they do serve as a good start point to start, thanks for the reminder!
