### ISSUE TITLE
Crash when pressing enter in "sort armor" window when wearing nothing

### ISSUE THREAD

**Issue by petermorck** [CleverRaven/Cataclysm-DDA#58036]
### Describe the bug

Pressing enter while the "sort armor" window is open causes the game to crash if you're not wearing anything.

### Steps to reproduce

1. Wear nothing (wielding item or not doesn't seem to matter, but be completely naked).
2. Go to "sort armor" window (default '+')
3. Press enter
Game crashes

### Expected behavior

Not sure, but I guess nothing should happen, at least not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 9ab7cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

[crash_config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8800798/crash_config.zip)

**Comment by Inglonias** [comment]
/confirmed

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by ZeroInternalReflection** [comment]
I can confirm this crash on:
<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

It looks like several other actions in this screen check to see whether the list of armor is empty before doing anything:
https://github.com/CleverRaven/Cataclysm-DDA/blob/e4795ccaeb7b2d8f9c912872e5043301e69bfc5a/src/armor_layers.cpp#L864
But the MOVE_ARMOR action (`s`/`ENTER`/`RETURN`) does not:
https://github.com/CleverRaven/Cataclysm-DDA/blob/e4795ccaeb7b2d8f9c912872e5043301e69bfc5a/src/armor_layers.cpp#L900
