### ISSUE TITLE
Design document mentions non-existent factions

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#58043]
### Describe the bug

I got really confused seeing names like "~~God’s Chosen~~, the Great Library, the Campus, the Brotherhood of the Tentacle, Strongarm Survivalists, and Fence Men" in https://cataclysmdda.org/lore-factions.html and not seeing them anywhere else.

Git blame says Erk added those, so I assigned them to this issue.

### Steps to reproduce

-

### Expected behavior

Are those factions that are officially okay to implement but no one has implemented them yet?
I found them discussed in #27479 but nowhere else.

Would be great if there could be at least a little blurb about them that this faction is still WIP and contributions are welcome. Potentially also copy the comment with the idea for the faction into the document and credit the one suggesting it so there is some information about the faction.

### Versions and configuration

-

### Additional context

If you are reading this Erk, would you also take a look at https://github.com/CleverRaven/Cataclysm-DDA/pull/57869#issuecomment-1134589041 please? This also looks like an undocumented faction.

**Comment by Maleclypse** [comment]
Is everything in the godco folder not God's Chosen?

**Comment by NetSysFire** [comment]
I looked into the files and I am not sure. Nothing specifically mentions "God's Chosen"

**Comment by tenmillimaster** [comment]
Shouldn't the design document be allowed to speak not only on the design of the existing game, but also the game that is being made? Not everything in there has to exist yet.

**Comment by NetSysFire** [comment]
Yes, but my point is that it is unclear and confusing when non-existent factions are mentioned in this way. It would be awesome if these loose ends could be tied up, so if they are getting implemented by someone, there are already some guidelines on what the faction does and does not.

**Comment by MNG-cataclysm** [comment]
God's Chosen was added in PR #62061, so that's one down.

**Comment by I-am-Erk** [comment]
It would be good to have a bit more design sketch in there, but also we don't want to overfill the design doc with expected information... factions that are loosely designed but not implemented can be left very vague so that someone can pick them up and design them themselves.
