### ISSUE TITLE
Combat overhaul. Hitboxes, for the love of wasps.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#58054]
### Is your feature request related to a problem? Please describe.

Wasp frustrations. I understand the wasp hate but simply nerfing them doesn't seem right. IRL they as well as other creatures can be quite difficult to hit. Some weapons should be far more effective with hard to hit enemies.

I have an extensive solution that may seem excessive but i believe will address this irritation as well as completely overhaul combat in a way that is more realistic, difficult, and rewarding. 

### Solution you would like.

Weapon and enemy "hitboxes" for hit/miss calculations. A tennis racket is more effective for a wasp than a baseball bat.

The "small" changes:
-Creatures like wasps are not ALWAYS flying. They will periodically return to the ground for a (generally) short time. They are much easier to hit when on the ground but will take flight upon spotting the player, so sneaking up is key. Their hitbox is still small so a weapon with a good hitbox is recommended to stun them.
-Certain creatures like wasps are easily stunned when hit, causing them to become grounded for a turn and much easier to hit. This makes the first hit the most difficult.
-Other enemies can be downed (knocked to the ground and usually stunned for a turn or more).
-(B)ashing can attack enemies who are downed with good accuracy.
-OPTIONAL: Make stomping an action (similar to bashing) the player can take at any time. Stomp damage will vary and can injure the player depending on footwear (and maybe weight).  This action is (generally) faster and more accurate than bashing but less damaging compared to a bash with something like a baseball bat or pipe.
-Nets that can be used to capture flying enemies and restrain them for a time for easy bashing.

The big changes (combat overhaul):
-Give weapons and enemies hitboxes for hit/miss calculations.
-Items (that can be used for weapons) will have standard stats, combat stats, and damage stats.
   Item stats: volume, weight, length, material, etc
   Combat stats: Range, Speed, Hitbox (OPTIONAL: min/max)
   Damage stats: Bash/Cut/Pierce damage, Moves per attack, to hit bonus, damage per move
-OPTIONAL: Hitbox min/max values are like the effective surface area for combat. In melee the max hitbox is used but when an item is thrown this value will oscillate between max and min (throwing skill could affect min threshold?). A rock will have min values near identical to its max while a tennis racket will have a much lower minimum value.

Details: Unsure how arbitrary the hitbox system numbers should be. One idea is general surface area for weapons and creatures. A better system may just a simple ranking or a bonus certain items have. Regarding calculations- possibly an initial check with weapon hitbox vs enemy hitbox for a hit-chance variable used in a subsequent calculation with dexterity, weapon skills, and enemy dodge skills to see if the attack actually lands. This is long enough for now and the mechanics and details can be further fleshed out if this appeals to people.

Core idea:
Accuracy is not only determined by dexterity and weapon skills. weapon and enemy hitboxes should play a huge role in how easy they are to hit. Hitting a large enemy with most any weapon should be easy. Something like a wasp is very difficult to hit unless it is stunned or hit with a weapon with a larger hitbox (tennis racket, frying pan, etc) Weapon skills should play a bigger role in how effective the hit is. 

### Describe alternatives you have considered.

Reworking dodge speed stat in favor of Internal clock speed/reaction time stat that can affect multiple actions but be separate from movement speed. Make dodge speed differences a finer gradient vs the current sharp steps that exist.

Simplifying or leaving out some of these ideas.

### Additional context

There are many ideas here, not everything would need implemented but i want it all accessible in 1 place to read for now.

To-hit bonus is a bit of an odd term, possibly renaming to something like "weapon tier "effectiveness", or something for new players?

Much discussion should be had on how this could be implemented and what current stats need changed if there is any desire for some of these concepts. thanks.

**Comment by liminalRoar** [comment]
Some simple tags would be the easiest implementation by far for now. a "WIDEHIT" tag or something similar for Tennis racket, frying pan, and maybe shovel along with some other weapons and items.

I do think flying creatures getting stunned and falling down for a turn or so would be a great addition as well, but might take some work.

**Comment by liminalRoar** [comment]
Those are all pretty valid points. I was forgetting quite how large they were. It says giant wasps are human sized?

I do still think the implementation of flying creatures becoming stunned and downed when hit could make a huge difference. The larger the creature the more difficult that could be.

Also finding them returning to the ground occasionally for a time and taking flight when seeing the player could be good but likely would require a lot of new code.

**Comment by liminalRoar** [comment]
I love that idea! Is there anything that exists like that currently? Wondering if there is architecture to support multiple states for Enemies and maybe NPCs. For example, a hulk that goes from a berserk state of increased speed and damage to a defensive state of increasing armor and readying another berserk state. Or possibly even shock zombies entering an electrified state before releasing an attack and recharging.

Adding the ability for unique sprites for each state would be icing on the cake! Visually seeing the difference between a crawling and flying wasp would be useful.

**Comment by LucasBurrns** [comment]
How about splitting the attack event into few states. For example: wind-up, strike, recover. It could take the same in action points, but weapons weapons will have different proportions of those states. States could be processed dynamically based on monster type and weapon(plus states, perks etc). A sledgehammer will have long windup, but will have easier time of hitting slow targets, also will require more AP to recover if missed. Quick strike weapons will have chance to reduce a windup and strike time slightly, though, will have less damage of shortened range of motion. Fencing perks will affect recovery time. This system could also provide lots of benefits for martial arts too.
