### ISSUE TITLE
Traits or proficiencies that impact NPC Faction relations

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#58057]
### Is your feature request related to a problem? Please describe.

I'd like to be able to create professions, missions and scenarios that impact the players relations with other factions.   An example would be in Xedra Evolved I'd like to have some professions that start with CBMs but as a cost of that start are incapable of ever interacting peacefully with the Exodii.  Or as is currently planned having missions that for the Hub01 and Exodii that make the PC hostile to the opposite faction.

### Solution you would like.

I'd like for this system to tie into the traits or proficiencies so that it can be used for aspects of character generation as well as in normal play.

**Comment by Zireael07** [comment]
Could also be used for planned mycus/fungi factions? (At least I dimly recall such plans, although it's possible they went the way of God's Chosen...)
