### ISSUE TITLE
Make graffiti support sprite variety and possibly multitile

### ISSUE THREAD

**Issue by AlbertTheTerrible** [CleverRaven/Cataclysm-DDA#58067]
### Is your feature request related to a problem? Please describe.

Graffiti's currently can only be a single sprite. Although i'm not the biggest fan of graffiti myself, visually, it can add a lot of different elements that can make zones feel more varied and add life to them.

### Solution you would like.

Add support for sprite variety. I'm not sure how it works on the programing side, but making it multitile would be great. so that bigger sprites could also be used, or even using a different type of sprite for vertical walls.

We could even have special types of graffiti for specific zones, like different graffiti for the different factions of the game.

### Additional context

Some concepts I made

![image](https://user-images.githubusercontent.com/80914993/171306063-7c68bd38-e38e-482e-ba1c-cd9b436e759b.png)
![image](https://user-images.githubusercontent.com/80914993/171306083-ecf90dcb-8923-4112-87a4-105b3920ffcd.png)

**Comment by mlange-42** [comment]
Variants were implemented in #61427.

Not sure if multitile in combination with variants really make sense here.
