### ISSUE TITLE
Excessive portal spawns rendering game unplayable

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58065]
### Describe the bug

In situations where a portal is inaccessible to immediate play, such as being on a different Z-layer from the player, it's possible for the game to silently populate several hundred nether creatures into every possible tile for a large region around portals. In addition to making the game nearly unwinnable in some cases, the extreme number of spawns create a bevy of errors and severely degraded performance.

![cddaslimecrowd](https://user-images.githubusercontent.com/104868222/171300342-34572028-058c-4526-9771-3ff95f8ab384.png)
.

### Steps to reproduce

1) Create a situation where a portal is within the player's reality bubble but undetected
2) Allow the game to progress as normal for a moderate time period

### Expected behavior

Some natural limits on portal spawns should be in place to prevent game overpopulation

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Jan-Blasiak** [comment]
While it's not a bug, I can definitely /confirm that I've experienced such thing multiple times in the past.

**Comment by BaumgeistOne** [comment]
I am not sure this issue is directly related to the portals. Notice that most of the enemies in that picture are blobs.

I recently raided a lab, and some rooms (without portals) were filled to the brim with big blobs. So I guess there is something wrong with them.
