### ISSUE TITLE
Reversing while towing a vehicle does not pull

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#58068]
### Describe the bug

If you reverse while towing a vehicle, it will not pull said vehicle. Reversing too far will snap the cable.

### Steps to reproduce

1. Setup a normally functioning towing operation
2. Reverse the head vehicle 
3. Notice your snapped tow cable

### Expected behavior

The towed vehicle will still be towed (following the point in which the connection is made).

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 77955ca [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by xrogaan** [comment]
I just experienced this behavior in my game. Reversing will snap the cable.
