### ISSUE TITLE
Malfunctioning 5-point anchors always spawn without batteries 

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#58071]
### Describe the bug

As this is likely unintended, I'm labeling this as a bug. 
Broken 5-point anchors off of phase shulkers and other similar entities never spawn with batteries

### Steps to reproduce

1. Find new lab
2. Explore until finding a phased enemy
3. Kill
4. Notice lack of battery

### Expected behavior

You would expect them to have batteries, even if they are empty or very low charge, as the harness need batteries to function, and it's only as a result of the harness that they are as corporal as they are

### Screenshots

![image](https://user-images.githubusercontent.com/43324177/171355515-c9e3ecfb-0bcd-4303-8e06-6299dacbd710.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: e87eb80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Combat Robotics [combat_robotics],
    SpeedyDex [speedydex],
    Customizable Guns [customizable_guns],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by bombasticSlacks** [comment]
this is an easy fix for someone, just adding a battery with some charge to the malfunctioning harness should work in the item group for the phase enemies.
