### ISSUE TITLE
I am allowed to attatch a suppressor to a USP .45 whilst it is in a holster that normally wouldn't fit a suppressed USP .45

### ISSUE THREAD

**Issue by TheKittieMuffin** [CleverRaven/Cataclysm-DDA#58078]
### Describe the bug

if I attach a suppressor to a USP .45, it won't fit in the holster. however if I remove the suppressor and then place the USP .45 in the holster, I can reattach the suppressor and the gun stays in the holster. this causes an error to appear when loading a save;

" DEBUG    : error: item usp_45 cannot fit into pocket while loading: item is too long

 FUNCTION : void item_contents::combine(const item_contents&, bool)
 FILE     : src/item_contents.cpp
 LINE     : 384
 VERSION  : 0.F-2
"

### Steps to reproduce

see above

### Expected behavior

when loading the save, my suppressed usp will drop to the floor rather than stay in the holster.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Stone94** [comment]
I can confirm this, I spawned the items, holstered the USP .45 and attached the suppressor, which allowed me to go beyond the bags length limit. removing the pistol wouldn't allow me to put it back in the holster. using an experimental from last week.

**Comment by bombasticSlacks** [comment]
in some cases a weapon needs to be wielded to add a mod that should probably be standardized.
