### ISSUE TITLE
Can disassemble sporks from the sealed MREs without unsealing them 

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58074]
### Describe the bug

Magic!

### Steps to reproduce

Spawn some MREs, `(`disassemble some sporks, look around with `/` to see that all the MREs are still sealed.

### Expected behavior

No magic, also there should be prompts when something must be unsealed to complete the action.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-8743-g3df7dc7fcb-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ZeroInternalReflection** [comment]
I can confirm this on:
<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-9043-gfdf38c42583 [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

Though I did need to `a`ctivate the MRE first.
