### ISSUE TITLE
Disassembly of the freezer and its recipe

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#58083]
### Is your feature request related to a problem? Please describe.

My first issue, sorry, if something is wrong
Previously, large freezers were added https://github.com/CleverRaven/Cataclysm-DDA/pull/56293
But they can only be found in small, city dumps and a couple of other locations, while they cannot be dismantled for parts or crafted, unlike the same large refrigerators
We have fridge, minifridge and mini frezeer recipe, but not frezeer

### Solution you would like.

1) The ability to dismantle freezers for parts and craft them
2) Need a freezer recipe

### Describe alternatives you have considered.

1) I don't remember which book the fridge recipe is in, but the freezer recipe can be placed in it too
2) Freezer disassembly. But I do not know how much the number of parts will differ from the refrigerator

### Additional context

the inability to disassemble the freezer:
![3](https://user-images.githubusercontent.com/102726167/171616691-d303359a-23d9-4bf5-96e5-81935b88588b.png)

lack of freezer recipe when learning all recipes through the debug menu and serching for the word "freezer"
![2](https://user-images.githubusercontent.com/102726167/171616811-22d94efc-6d7c-4999-9305-5eb148732c91.png)

However, the fridge is fine
![1](https://user-images.githubusercontent.com/102726167/171617105-2f00ed9e-d738-42fa-9966-e1a82cb45556.png)

**Comment by Ezrashaw** [comment]
I think that a freezer recipe could be added basically as an advanced fridge, potentially with all the same types of ingredients just more quantity.

**Comment by KHeket** [comment]
> I think that a freezer recipe could be added basically as an advanced fridge, potentially with all the same types of ingredients just more quantity. This wouldn't be that hard a change, could be a 'good first issue'.

What should I do now? Just wait or somehow attach labels? I did not find any button for this, and in order to edit the game files I don't have the skills. And I would like someone to make this change

**Comment by KHeket** [comment]
Can I somehow bump this issue? Becouse big frezeers very usefull for bases and its easy to make change

**Comment by KHeket** [comment]
@Ezrashaw 
What should I do now? Just wait or somehow attach labels? I did not find any button for this, and in order to edit the game files I don't have the skills. And I would like someone to make this change
Can I somehow bump this issue? Becouse big frezeers very usefull for bases and its easy to make change

**Comment by KHeket** [comment]
Copy post from https://github.com/CleverRaven/Cataclysm-DDA/pull/62429 may be someone will do this change

We have mini-freezer and mini-fridge recipe difference in 2 plastic chunks, so we can use it as simular example. We also have standart fridge resipe with plastic chunks as ingridient
I am not fredge and freezers expert too, but when I googled "difference between freezer and fridge" I found next valuable information.(I will also attach links)

<details>
  <summary>First piece of information</summary>

https://home.howstuffworks.com/freezer3.htm#:~:text=The%20only%20difference%20between%20a,Fahrenehit%20(%2D18%20degrees%20Celsius).

![image](https://user-images.githubusercontent.com/102726167/204558721-f8a20a01-0298-45dd-83fc-e591fa54f963.png)


</details>

<details>
  <summary>Second piece of information</summary>

https://reductionrevolution.com.au/blogs/how-to/convert-freezer-to-fridge
![image](https://user-images.githubusercontent.com/102726167/204559107-2bd29786-202a-4e66-83ff-a99d1d1d32f1.png)

</details>

So there is already more power cost for freezers, and all we need is to encrease by half or two plastic chunks for freezer recipe

**Comment by KHeket** [comment]
All is needed - is copy/past code of fridge recipe, rename it and add some plastic to recipe, and copy/past disassemble function from fridge to freezer with platic correction. As mentioned and showed on screensshots above, difference between minifridge and minifreezer is in 2 plascit chunks. Minifridge is 8 plastic chunks, fridge is 16 (they are doubled). So for regular freezer there must be 20 plastic chunks

**Comment by KHeket** [comment]
Dont touch this issues, I want to make it by myself
