### ISSUE TITLE
Moonshine Destilation produces Methanol in the same Volume as Moonshine

### ISSUE THREAD

**Issue by SamGondra** [CleverRaven/Cataclysm-DDA#58085]
### Describe the bug

Currently Distilling Moonshine produces the same volume of Moonshine (0,25l) as Methanol (0,25l).

### Steps to reproduce

1. Distill a single batch of Moonshine.
2. Realize that you just got 0,25l Moonshine and 0,25l Methanol
3. You know have enough Methanol to easily kill 2 People by toxicity (1-2ml per kg bodyweight) or permanently blind 20+ People

### Expected behavior

As per #53836 it should only be 12-15% of the rest of the product?

### Screenshots

![MethanolMoonshine](https://user-images.githubusercontent.com/101570967/171642576-7a52bfd6-ebe5-4e2f-9c24-a1f9347d5aa2.png)
![Moonshine](https://user-images.githubusercontent.com/101570967/171642578-b5e5aa79-fbf9-4446-a558-c433b6c794cb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 000bdd9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots]
]

### Additional context

I tried to figure out how to fix this, but could not figure out how to.

**Comment by PatrikLundell** [comment]
The screenshots show 1 unit of methanol and 7 units of moonshine, which is about the correct proportions (one standard unit is 250 ml, and booze uses standard units while chemicals typically use ml).

**Comment by SamGondra** [comment]
> The screenshots show 1 unit of methanol and 7 units of moonshine, which is about the correct proportions (one standard unit is 250 ml, and booze uses standard units while chemicals typically use ml).

that might be the case but according to what I have read, and what some people in discord say, even 12% Volume of the product (the moonshine) would be far too much.

**Comment by PatrikLundell** [comment]
You're changing the goalpost when you claim that "Expected behavior" isn't good enough for you.

If you want to change this report to be about what the amount ought to be, rather than it not being what it's defined to be when it is, you're free to do so, and I will have no opinion on the matter as I don't have any expertise. If you do, please remember to change the heading as well as the body of the report.
