### ISSUE TITLE
Narrow zombie spawns and evolution "families" to create more varied experiences

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#58087]
### Is your feature request related to a problem? Please describe.

Currently, most of the basic zombie types can evolve into almost any kind of zombie, and most locations spawn lots of basic zombies. This means that after a while, most places end up with a pretty even mix of advanced zombie type.

This is a bit boring, because it means the combat threat is more or less the same everywhere. I particularly dislike that it robs the player of the ability to strategize and make meaningful choices by rendering many specialized items either useless or mandatory. I wish I could break out my shotgun when it's time for close-quarters combat, but I have to be prepared to gun down a Skeletal Juggernaut at any time. I wish the faraday suit was a tool I could use to solve specific problems, not something I have to live in 24/7 because a Shocker could pop up at any time.

### Solution you would like.

Prune the evolution trees of the basic zombie types to only a few thematically relevant options, and audit their placement. For example, regular "zombie" enemies might only evolve into the "physical" types (grabber, hunter, shrieker, etc.) while zombie scientists evolve into shockers and acid zombies. This would instantly create a noticeable difference between raiding a city and raiding a lab.

It might also be good to create more basic zombie types and place them in certain locations. This could be accomplished through entirely new types, or through hidden variants, like a "zombie_garbage" that looks exactly like a normal "zombie" to the player but only spawns in dump and hazardous waste sarcophagi and evolves into rad or acid zombies.

I think just doing the first thing would create a more varied experience, but for the full effect there would need to be some re-evaluation of spawns. There's not much point in splitting the "families" between three different base types if you end up spawning all three types in most places anyway.

### Describe alternatives you have considered.

Increase the amount of non-zombie enemies. This is a promising idea, and there have been some great strides in adding interesting new enemy types, but it's hard to get away from the zombies. Most places the player wants to go used to be places of human activity, so whatever else is going on it usually wouldn't make sense for there not to be zombies there. Plus, we've already got a bunch of different kinds of zombie providing unique combat challenges, they could just be put to better use.

### Additional context

I haven't actually played the game in months and I'm too busy to get sucked back in right now, but I remembered that I never got around to posting this suggestion so I had to exorcise the demon before it consumed me.

e: when planning a system like this, I think it's more important to consider what you WON'T encounter in a particular location. Me wanting to bring my shotgun is more contingent on being reasonably sure there _won't_ be (m)any high-armor enemies than on any particular enemy type that _will_ be there. And while it's important that there are places that will almost certainly have shockers for my faraday suit to come into play, if there aren't places where I can be reasonably sure there won't be any shockers I'll still have to wear it all the time.

**Comment by Terrorforge** [comment]
Zombie scientists already evolve, that's not a change I'm proposing. Also, if I'm understanding it correctly, #57468 should mean the evolved forms retain the zombie scientist drops.

**Comment by liminalRoar** [comment]
Personally i really hope the possibility for unique evolutions emerges, though i think you would need a pretty hefty database to store all the info for enemies..

 Essentially, Zombies make small evolutionary jumps, with jumps to a new enemy type becoming more rare (either taking more time, or after a certain amount of smaller evolutions happen). Certain events could speed evolution too, like radiation, portal storms even?

There would be a number of "upgrades" zombies could receive from small evolutions. Gaining a stat, a new skill, or a random mutation, with each enemy possessing unique traits. It could make combat much more difficult...regardless, zombies would start with few or none of these unique traits. The player shouldn't be able to see these hidden stats, but perhaps with perception increasing or a certain skill they could better access the enemies capabilities.

It could even allow for all creatures to possess unique stats. with a standard stat and skill set for everthing but some randomization thrown in. Perhaps you stumble across a bear that is a little slower than normal but more of a tank or is more powerful.

Procedural artwork/animation would be amazing if not impossible.
