### ISSUE TITLE
Unable to open windows while standing on Metal Floor

### ISSUE THREAD

**Issue by blacktarheroin** [CleverRaven/Cataclysm-DDA#58098]
### Describe the bug

 Version 2022-05-28-1015
This is more or less self-explanatory. I cannot open/close windows (or reinforced window shutters) while standing on Metal Floor. I was making a home out of a radio tower when I discovered this, if that helps. I was still able to pry open normal windows with a crowbar, but not close them.

I was able to fix this by replacing the floor with carpet, at which point I could open/close windows.

### Steps to reproduce

1. Download version 2022-05-28-1015
2. Stand on Metal Floor with a nearby window with curtains
3. Try to open them

### Expected behavior

Read above.

### Versions and configuration

Version 2022-05-28-1015
Mods: Bionic Professions

**Comment by ZeroInternalReflection** [comment]
I've managed to reproduce in this test world (compare the north "wall" and the east "wall.  I didn't bother actually moving to the second level of the tower)
[Metal_Floor_Testing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8829326/Metal_Floor_Testing.zip)

<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

With a bit of testing, the key looks to be that the radio tower uses t_metal_floor_no_roof, not t_metal_floor.  Unlike t_metal_floor and carpet, t_metal_floor_no_roof does not have the "INDOORS" flag,  So, when you're on the existing floor of the radio tower and try to open/close the curtains, the game thinks you're outside.  Adding the "INDOORS" flag allows you to open the curtains, but probably breaks a bunch of other stuff.

I have not yet tracked down exactly where in the code it fails to figure out if you're in an enclosed space, but I think it's somewhere upstream of here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/01f7b57b86342fbfb3f269fa3e43bd90b9b52ddb/src/map.cpp#L4014

Theoretically this is a quirk that could impact any in-game exterior structure that the player tries to enclose.
