### ISSUE TITLE
Denatured Alcohol required for Magiclysm recipe cannot be crafted

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#58090]
### Describe the bug

To make Alumentum the component Denatured Alcohol is needed, but cannot be crafted. 
Used to be a recipe found in chemistry textbook and one other book. 

According to terrorforge: 
The denatured alcohol recipes [was removed](https://github.com/CleverRaven/Cataclysm-DDA/pull/53716) and replaced with methylated spirits, on account of denaturing alcohol would require denaturing agents. The fact that it makes this Magiclysm recipes very hard was probably an oversight, which is only a problem because of the original oversight that this recipe specifically calls for denatured alcohol rather than "OR ethanol".

### Steps to reproduce

Attempt to make alumentum, precursor to superior potion starter 
Note requirement for 'denatured alcohol' 
Find that there are no recipes for denatured alcohol in chemistry textbook or Out of the Holler etc. 

### Expected behavior

Recipe should allow ethanol or methylated spirits

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.239 (1903)
- Game Version: 57d911c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by Heaper327** [comment]
The Stirling engine toy kit in vanilla game also requires denatured alcohol to be used, which should probably be fixed too

**Comment by Shados** [comment]
Not sure if it was changed since your comment, but the Stirling engine kit uses _any_ concentrated alcohol, which also includes ethanol, methanol, and methylated spirits.

**Comment by Night-Pryanik** [comment]
I think this is resolved by #60857.
