### ISSUE TITLE
Some vehicle parts can still be folded when placed down as appliances.

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#58095]
### Describe the bug

I think the title clarify most of the issue.
It happens particularly with the storage batteries. 

### Steps to reproduce

1. Take a medium storage battery
2. Place it down as an appliance
3. Watch as you can fold it, for some reason.

### Expected behavior

I think we shouldn't be able to fold anything that has been placed down. 
I suppose there should be a simple check in the c++ file for it.

### Screenshots

![image](https://user-images.githubusercontent.com/24830358/171742925-88e48836-592f-4240-b900-354c628c965d.png)
![image](https://user-images.githubusercontent.com/24830358/171742941-84d4769d-0454-4784-b367-59541e9873a3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 0.F-8780-g18d1da2cd1-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
The simple check should probably be that appliances shouldn't check for foldability.

The reason the battery can be "folded" is to allow (custom) electric bikes to be foldable. A vehicle can only be folded if all parts it's made of are marked as being foldable, so it's a sort of work around.
