### ISSUE TITLE
Dinomod with NoMonsters

### ISSUE THREAD

**Issue by KAmaia** [CleverRaven/Cataclysm-DDA#58100]
### Is your feature request related to a problem? Please describe.

I wanted to start a world tonight with no zombies, just dinosaurs.  

I enabled NoMonsters first, then added dinomod below that in the load order.  

I went into my debug menu to see if dinos could be spawned, and unfortunately it appears that they are not considered wildlife, but are instead considered monsters.  

### Solution you would like.

I would like to see dinosaurs in dinomod treated as wildlife, instead of monsters, as this would enable the gameplay style I am looking for.

### Describe alternatives you have considered.

Another workaround would be allowing players to customize the types of monsters that they want to be spawnable.

**Comment by LyleSY** [comment]
Makes sense to me. I don't know why anyone would run DinoMod and NoMonsters together otherwise

**Comment by estebandellasilva** [comment]
> Makes sense to me. I don't know why anyone would run DinoMod and NoMonsters together otherwise

Cataclysm dark dinos ahead?

**Comment by KAmaia** [comment]
> > Makes sense to me. I don't know why anyone would run DinoMod and NoMonsters together otherwise
> 
> Cataclysm dark dinos ahead?

Tbh it was either submit this bug and related PR, or start my own game from scratch.
