### ISSUE TITLE
Display number of pouch slots on MOLLE equipment

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#58103]
### Is your feature request related to a problem? Please describe.

Currently, the number of pouches can only be found out by somewhat tediously filling a piece of equipment full of pouches to find the max, or going through the files looking for each item that can accept pouches

### Solution you would like.

The max number of pouches should be displayed in the ui, ideally, the volume encumbrance modifier would be displayed as well; as it's a fairly important stat to know when picking a backpack

### Describe alternatives you have considered.

1. Not having the max number of pouches be displayed
2. Not displaying the volume/encumberance modifier directly, instead perhaps through a layer of obfuscation such as "it has good lower back support"

**Comment by bombasticSlacks** [comment]
> Not displaying the volume/encumberance modifier directly, instead perhaps through a layer of obfuscation such as "it has good lower back support"

This could be handled with flags but would need to be inputted manually. 


As for pouch limits it is displayed in the UI for attaching:
![image](https://user-images.githubusercontent.com/4514073/172003516-1bf887f2-6f62-48c1-975f-a29c8a866648.png)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
