### ISSUE TITLE
No overmap path indicators for autotravel with Surveyor's Map tileset

### ISSUE THREAD

**Issue by mlange-42** [CleverRaven/Cataclysm-DDA#58111]
### Describe the bug

When auto-travelling while using the Surveyor's Map tileset for the overmap, the path of travel is not visible.

### Steps to reproduce

1. Set overmap tileset to SurveyorsMap
2. Open the overmap (`m`)
3. Try to auto-travel somewhere (`W`)
4. See that you see no path indicators

### Expected behavior

After pressing `W` the first time, the path to travel should be indicated

### Screenshots

![grafik](https://user-images.githubusercontent.com/44003176/171853574-aea81491-cd72-4690-a313-cd57f8fa7514.png)

### Versions and configuration

- OS: MS Windows 10
- Game version: Build 2022-05-25-0655
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda

**Comment by mlange-42** [comment]
The issue is caused by missing `"id": "highlight"` entry in `tile_config.json`. The tileset does not contain an appropriate tile, but maybe the tile for `"id": "cursor"` (1983) could be used.

**Comment by Inglonias** [comment]
This issue would need to be fixed in the [CDDA-Tilesets repository](https://github.com/I-am-Erk/CDDA-Tilesets)

**Comment by mlange-42** [comment]
> This issue would need to be fixed in the [CDDA-Tilesets repository](https://github.com/I-am-Erk/CDDA-Tilesets)

Thanks @Inglonias! Opened an issue over there: https://github.com/I-am-Erk/CDDA-Tilesets/issues/1373

**Comment by Fris0uman** [comment]
This was added in https://github.com/I-am-Erk/CDDA-Tilesets/pull/1327 and I just tried in game and it works
