### ISSUE TITLE
Venom Mob Protege can still spawn on NPCs

### ISSUE THREAD

**Issue by CuriousTrout** [CleverRaven/Cataclysm-DDA#58125]
### Describe the bug

The trait Venom Mob Protege is supposed to be locked behind Mythical Martial Arts, but it can still spawn on NPCs without the mod enabled. 

### Steps to reproduce

Rerolling my Evac NPC repeatedly is how I did it, but I'm not sure this is something you "reproduce."

### Expected behavior

Venom Mob Protege to be locked behind MMA.

### Screenshots

<img width="960" alt="venom mob" src="https://user-images.githubusercontent.com/36283764/171945815-c69cdede-49ac-452a-a083-87dc5a084533.png">

### Versions and configuration

0.F-3

-Dark Days Ahead
-Alternative Map Key
-Disable NPC Needs

**Comment by Maleclypse** [comment]
Venom Mob styles are fictional martial arts that are not in the Mythical Martial Arts mod but rather are in the base game.   It's possible they should be moved their but this by itself right now isn't a bug.

**Comment by Maleclypse** [comment]
@Hymore246 Should the Venom Mob styles be moved out of vanilla? And if so they should be obsoleted now so that the trait can't be chosen in the upcoming stable.

**Comment by CuriousTrout** [comment]
Venom Mob styles have been removed from Vanilla already, you can't gain the styles at all anymore. The NPC has the trait to pick one, but it can't actually use the trait, so it's a dummy trait.

**Comment by Hymore246** [comment]
Venom Mob Protege trait still exists in vanilla in `data/fictional_martialarts.json` It is marked as `"starting_trait": false` which prevents it from being selectable by players. `data\mods\MMA\mutations.json` redefines the trait with `"starting_trait": true` which makes it selectable. What is probably happening here is the code that assigns martial art styles to NPCs is not obeying `"starting_trait": false`. That should be changed and I think `fictional_martiarts.json` exists for backwards compatibility.
