### ISSUE TITLE
Dopamine Stimulators power hog

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#58137]
### Describe the bug

This CBM seems to run pretty hot, 5kJ/200 turns or 25j/turn. 

### Steps to reproduce

Install Dopamine Stimulator CBM
Turn it on
Observe power draw

### Expected behavior

Compared to Repair Nanobots at 40j/turn or the Dielectric Capacitance System at 5j/turn. 
According to [this](https://www.thehealthboard.com/how-much-energy-does-the-brain-use.htm) the human brain only uses 10-25 watts, or joules per second.

A brain tickler seems like it would need to be low power to avoid cooking the squishy bits. 

Maybe no more than 5j/turn? 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.239 (1903)
- Game Version: 57d911c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by Wyrdean** [comment]
The Dopamine Stimulators and its sister the Linguistic Coprocessor CBM both sound to me like they'd make good vanilla cdda additions
