### ISSUE TITLE
Please increase message interval for "Your [LIMB] will be frostbitten in [time span]" and addiction related texts

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#58139]
### Is your feature request related to a problem? Please describe.

At the current rates, the message log gets spammed with these messages. The bright yellow text is easy to detect, so it is unnecessary if the goal is to make sure the player does not miss them. They are distracting and annoying when doing things like crafting or waiting

### Solution you would like.

Increase interval at which these messages get printed out.

**Comment by PatrikLundell** [comment]
I assume you actually want to INCREASE the interval in order to decrease the frequency. It might be useful to rephrase both the title and the body of the request to indicate that.

**Comment by DamienRoyan** [comment]
> I assume you actually want to INCREASE the interval in order to decrease the frequency. It might be useful to rephrase both the title and the body of the request to indicate that.

Noted and done, thanks

**Comment by Ezrashaw** [comment]
This feels very subjective, maybe it should be longer by default but I think this should be a customizable thing.

**Comment by DamienRoyan** [comment]
I agree. This is a subjective thing, and a customizable setting would be
much appreciated.

**Comment by DamienRoyan** [comment]
> This feels very subjective, maybe it should be longer by default but I think this should be a customizable thing.

Agreed. It is a subjective problem, and a customizable option would be much appreciated

**Comment by fungamer2-2** [comment]
Looking at the code, it seems like the interval for frostbite messages is probabilistic
https://github.com/CleverRaven/Cataclysm-DDA/blob/568683befe9c091e132f8d5a53e1b78da739419b/src/character_body.cpp#L793-L825

**Comment by anothersimulacrum** [comment]
This should not be an option. Currently it'll appear roughly once every 100 turns, to change that, simply change the number `100` in the `one_in( 100 )` in the code posted above to a different number. Now, the hard part is choosing that new number. I'd suggest increasing by at least 6x, because this likely predates the turn-time change.

**Comment by Ezrashaw** [comment]
> This should not be an option. Currently it'll appear roughly once every 100 turns, to change that, simply change the number `100` in the `one_in( 100 )` in the code posted above to a different number. Now, the hard part is choosing that new number. I'd suggest increasing by at least 6x, because this likely predates the turn-time change.

There should be some option to change the frequency of these kind of messages. Something like 'low', 'normal', 'high' so that new players don't miss it but more experienced players can decrease the log spam. Although I do agree the default should be less frequent.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
