### ISSUE TITLE
Monster behavior flag to drag grabbed enemies into deep water and drown them

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#58136]
### Is your feature request related to a problem? Please describe.

I have made aquatic enemies that grab their enemies.  But many of the times they pull their enemy into shallow water.  

### Solution you would like.

 I want them to pull until their target is in deep water too.  So if they pull the target into shallow water they attempt to move until they can pull the target into deep water.

### Describe alternatives you have considered.

Making monsters that can only live in deep water but they would still often pull monsters into the shallow water that is next to deep water.

### Additional context

I could make a horse that when you try to mount it, runs straight into deep water and forcibly dismounts the PC.

**Comment by Maleclypse** [comment]
@John-Candlebury I know you've made behavior flags before. Is this feasible?

**Comment by John-Candlebury** [comment]
Should be possible, although its more complex than any of the behaviors currently ingame. Might need to wait until the behavior tree system implementation

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
