### ISSUE TITLE
Mutation line: Return to Monke

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#58146]
### Is your feature request related to a problem? Please describe.

I'd like to have a yet another mutation category that allows for wearing human-shaped clothing. Good candidates from the animal kingdom are great apes. Gorilla, in particular, seems to be the best candidate for this. I'm open to suggestions (neanderthal? Homo erectus?). Where we can have anthropomorphic squids, we can have hominids.

### Solution you would like.

Create a mutation line for a monkey.

The definitive traits should be:
- Strength, Dexterity ++
- Intelligence -- 
- Large and large_ok
- Difficulty walking upright (add a walking category - "on all four")
- Shouter
- Food intolerance aside from plants
- Shaggy Fur
- TAAANK or resilient.

I feel like I should be adding more negatives. Please make suggestions here.

### Describe alternatives you have considered.

Add some other hominid instead. Open to suggestions.

### Additional context

![image](https://user-images.githubusercontent.com/56438982/171996259-d0c2b223-6966-4212-b695-95b81b9ae8ad.png)

**Comment by fairyarmadillo** [comment]
Apes mostly have fangs and a fairly dangerous bite. They should also be great at climbing.

Shaggy Fur is super dense bear fur that soaks bullets. Ape fur is not like that. Their fur would probably be closer to Lightly Furred.

Feet hands and knuckle walking will probably have to wait on limb code. The latter will be a good drawback though, especially if it's not slower but rather less stamina efficient for them to run. Apes are very physically able but they can't go long distances as well as humans.

**Comment by Atomikkrab** [comment]
Bad back, posture would not be as good for carrying things

**Comment by fairyarmadillo** [comment]
> Bad back, posture would not be as good for carrying things

Gonna need a source on that. Apes are many times stronger than humans and our upright posture makes us especially vulnerable to back problems.

**Comment by Atomikkrab** [comment]
> > Bad back, posture would not be as good for carrying things
> 
> Gonna need a source on that. Apes are much stronger than humans and our upright posture makes us especially vulnerable to back problems.

I'm just trying to think of negatives, and this is not a real gorilla this is a horrific mutated human with gorilla features.


Also ponderous might be an option, Gorilla apparently have less muscle in their legs which is part of the reason for the quadruped movement (and far more muscle in their arms)

**Comment by fairyarmadillo** [comment]
The animal mutation lines are a straight mix of human and animal features and shouldn't feature anything for video game reasons. It should all be drawn from real facts about the animals and backed up by outside sources if necessary.

Ponderous is no good, gorillas are very fast over short distances. Their mobility disadvantages compared to humans are that their walking style limits their hand usage (which we can't do yet) and they get tired faster over long distances (which we can).

Smelly works.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
