### ISSUE TITLE
Disassembling anything while it's in-progress crashes the game

### ISSUE THREAD

**Issue by Crudbone** [CleverRaven/Cataclysm-DDA#58143]
### Describe the bug

Disassembling an in-progress item crashes the game.

### Steps to reproduce

1. Get any disassemblable item
2. Disassemble it with the required tools
3. Interrupt the disassembly manually at any time (obviously it's much easier to do with an item that takes at least 30 minutes to disassemble such as a hotplate)
5. Activate the in-progress item in your inventory to work on it again.

### Expected behavior

The game should crash immediately after attempting to disassemble the in-progress item. 

What's strange is that this seems like a bug that would be widely reported by now since it's so easy to replicate in a normal game. So maybe it's actually triggered by my character's specific circumstances and not the action by itself. But I have no clue as to what that trigger could be.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 80a0da6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8837260/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8837262/debug.log)

I included my character's save file so someone can look into it further, assuming it has something to do with my own circumstances. There's a lone minifridge next to my character and you can disassemble it right on the spot to test it for yourself.
[Yeoman.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8837265/Yeoman.zip)

**Comment by andrei8l** [comment]
This is embarrassing...

**Comment by Crudbone** [comment]
> This is embarrassing...

No need to feel embarrassed! Thanks for fixing it so quickly!
