### ISSUE TITLE
Freshwater Research Station is selectable as starting location despite it was removed by Dark Days of the Dead mod

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58155]
### Describe the bug

After character generation, I hit TAB to begin and got this opoup window "Unable to generate a valid starting location Freshwater Research Station in a radius of 3 overmaps, please report this failure" here is the report.
The program then offers to try again, I tried again 10 times, same message each time.

### Steps to reproduce

see above

### Expected behavior

no error

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: ac85e55 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
/confirmed
Thats mean the map doesn't have any lakes, you need to generate a new world and try again

**Comment by Terrorforge** [comment]
I believe Dark Days of the Dead removes the Freshwater Research Station from the game.

But apparently, it doesn't remove it from being selected as a starting point, which is definitely an oversight.

**Comment by NealsSec** [comment]
I've been looking into this issue and have discovered a couple of map that are spawning in Classic that should not be and a couple that are potentially missing. 

I believe the Freshwater Research Station is missing a classic tag and should actually be spawning in Classic Zombies in addition to some other water features (lake_shore_dock_small). 

I have read through the design document for classic zombies but can't really make a determination if I'm right in thinking that the Freshwater Research Station would fit. @I-am-Erk do you mind clarifying?
