### ISSUE TITLE
Antiseptic freeze point?

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58151]
### Is your feature request related to a problem? Please describe.

I think that most antiseptic contain a fair amount of alcohol. Alcohol has a freeze point of -100°C so I am not sure if antispetic should freeze in winter.  Does anyone know the IRL freeze point of the various antiseptics in the game?

### Solution you would like.

Adjust the freeze points of antispetic drugs to IRL values.

### Additional context

Non US here so I am not sure what the standard antispetic in the game is made of.

**Comment by Gotdamnmiracle** [comment]
I had assumed it was 70% isopropyl alcohol. A pretty common wound cleaning agent found in the US  that isn't a bacteriostatic like triple antibiotic ointment or neosporin (both of which don't actively clean deep wounds but prevent infection by providing a barrier to germs and dirt). Isopropyl alcohol can be used to clean out deeper wounds alongside soap and water and active scrubbing. It generally doesn't feel very pleasant though. 

source: work in healthcare. Clean wounds frequently.

**Comment by matt32106** [comment]
Ok, if this is indeed 70% isopropyl then the freezing point should be set at −89 °C according to wikipedia. So in the game you would be dead from cold before it freezes I think.

**Comment by Gotdamnmiracle** [comment]
Not exactly a scientific journal for a source, but this suggests 70% will freeze at much higher temps, but still unlikely to be encountered in most weather (or freezers) in New England.

https://www.rubbing-alcohol.com/does-rubbing-alcohol-freeze/

"Will 70% isopropyl alcohol freeze? Yes, 70% isopropyl alcohol freeze at around -2.5 degrees F, or -19 degrees C."

**Comment by leemuar** [comment]
It is pretty easy to fix, I'd suggest -19C as a good guestimate

**Comment by matt32106** [comment]
> It is pretty easy to fix, I'd suggest -19C as a good guestimate

I would have but can't find "antiseptic" in the code with github. Strange...

**Comment by matt32106** [comment]
If the disinfectant is made from denatured alcohol (a mix of ethanol and methanol) the same rule can be applied as for isopropyl as ethanol freeze point is -114°C and methanol's is -97°C so a 70-ish% watered mix would probably also have something close to the diluted isopropyl freeze point. Please note that hydrogen peroxyde type of disinfectant is another object in cdda -adequately- named "hydrogen peroxyde". The much lower freeze point of alcohol based disinfectant does not apply here (please check this article https://rescuedisinfectants.com/wp-content/uploads/2019/01/Cleaning-and-Disinfection-Procedure_Cold-Weather_US_Nov2016.pdf mentioned by @Maleclypse in the PR).

**Comment by leemuar** [comment]
should not be closed
