### ISSUE TITLE
Crash when attempting to continue disassemble

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#58169]
### Describe the bug

Found a reproduceable crash bug when attempting to continue disassembly of cargo carrier via butcher menu.

### Steps to reproduce

1. Load attached save
2. Use "butcher"-key
3. select damaged cargo carrier
4. abort with esc-key when asked what to do with toolbox
5. drop toolbox
6. use "butcher"-key
7. select "in progess" item
8. crash

### Expected behavior

No crash, obviously. :)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-8810-g98ec1bd1d2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

logs: [config.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/8839485/config.tar.gz)
save: [Cyberworld.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/8839488/Cyberworld.tar.gz)

**Comment by andrei8l** [comment]
This should be fixed now. Please try again with a newer build

**Comment by BaumgeistOne** [comment]
You are right, bug is gone in newest build. :)

I assume https://github.com/CleverRaven/Cataclysm-DDA/pull/58144 fixed it.
