### ISSUE TITLE
Appliances have irrelevant options when you interact with them.

### ISSUE THREAD

**Issue by lbnesquik** [CleverRaven/Cataclysm-DDA#58165]
### Describe the bug

I think the screenshot will clarify what I am talking about the most.

Siphon from tank? Refill tank? Those things should be tied to the flags of the appliances, rather than be given to all appliances.
I didn't manage to modify the code to take it into account on my own, but it shouldn't be 'TOO' hard. 'Simply' check for the FLUIDTANK flag, for example.

### Steps to reproduce

1. Spawn an appliance without a battery or a tank.
2. Interact with it.
3. See irrelevant buttons.

### Expected behavior

I expected those to be tied to appliance flags.

### Screenshots

![image](https://user-images.githubusercontent.com/24830358/172030844-34f67c0f-6efe-42ba-b94d-fcf07db1db6a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 0.F-8780-g18d1da2cd1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
As far as I can see from the screenshots the irrelevant options are greyed out, so whoever implemented this seems to have settled for that approach. Changing the UI to not display irrelevant options would presumably use the logic that's currently used to grey the alternative out to instead refrain from adding them at all.
