### ISSUE TITLE
Apartment tower kitchen cupboard has dirt/gravel as floor terrain

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#58161]
### Describe the bug

In the apartment tower is a kitchen with a cupboard. Under the cupboard is t_region_groundcover_barren where it shouldn't be.

### Steps to reproduce

1. Go to apartment tower
2. Observe the different kitchens, there's probably one with a cupboard that has dirt/gravel

### Expected behavior

Have a floor under the cupboard

### Screenshots

![image](https://user-images.githubusercontent.com/50166150/172026059-0b777732-aa21-4f76-a09b-b421dea5a8c3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 0.F-8491-gcc1a147891 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The apartment tower mapgen uses nested maps, including `kitchen_5x5_N_1`
The nested mapgen `kitchen_5x5_N_1` uses the `house_w_nest_palette` palette and doesn't set any terrain definition for symbol `2`, where the cupboard is.
If you look at the house_w_nest_palette, it sets `t_region_groundcover_barren` for symbol `2`. 

So the easiest fix is probably to change the symbol in house_nested.json:
![image](https://user-images.githubusercontent.com/50166150/172026161-3fb11c39-7ee1-4625-a71b-fd500a306e7a.png)

**Comment by NetSysFire** [comment]
Can reproduce. This is a nested mapgen error that should be easy to fix.
