### ISSUE TITLE
NPC Stuck Overburdened

### ISSUE THREAD

**Issue by YankelMyWankel88** [CleverRaven/Cataclysm-DDA#58163]
### Describe the bug

Starting NPC was allowed to pickup items with no rules set and has since picked up so many items he is over the weight limit, it will not let me take any items through the trade menu off of him to remove his burden, it constantly says "they can't carry all that" he is now stuck 11.9 L over the limit and no way to correct this.

### Steps to reproduce

Try to take individual items
try to take all items of weight
try to give him a container to hold more items

### Expected behavior

To take enough items to reduce his weight to the proper limit or below

### Screenshots

![bugcdda](https://user-images.githubusercontent.com/106891008/172027966-67c00dc9-dfa6-4c77-a885-680ccc4d2f5d.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
I think you'd be able to remove the junk from the companion if you select enough junk for "trade" for the companion to end up below its weight limit. Thus, drop everything except containers and trade for as much of the junk as you can, dump it somewhere and repeat until the companion only carries useful stuff. Obviously, this is a work around, not a fix.

The correction ought to be for the trade menu to not just check if the companion is overburdened after the trade, but to also check whether the load after the trade would be higher than before (or equal), and reject the trade only if both conditions are fulfilled.

**Comment by YankelMyWankel88** [comment]
Tried taking every item except what he was wearing and it would still tell me he can't carry it. .I had to debug to increase his strength then it would let me trade the items out

**Comment by PatrikLundell** [comment]
That's definitely annoying. I think there is a command to drop everything that's not needed, or something like that. This might work.
