### ISSUE TITLE
Single-tile apartment towers can spawn with a door or window blocked by adjacent buildings due to being too big

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#58175]
### Describe the bug

Single-tile apartment towers fill in too much of their space, which means the doors or windows can spawn blocked by adjacent buildings.

### Steps to reproduce

1. Teleport to various single-tile apartment towers(multi-tile have a gap before the boundary into the next OMT)
2. See ridiculous designs, such as windows or doors opening into privacy fences or walls.

### Expected behavior

Usable doors & windows on apartment towers.

### Screenshots

![image](https://user-images.githubusercontent.com/99621099/172052275-dc1cfcae-5bd4-4ab1-97d8-4f541744f5b2.png)
![image](https://user-images.githubusercontent.com/99621099/172052298-9ce4e831-e446-4f55-bc18-70e7d13b1828.png)
House <-> Dive Shop
Apartment Tower <-> Pharmacy

![image](https://user-images.githubusercontent.com/99621099/172052711-c23fbca9-8880-4960-aa3c-da7198ff727e.png)
![image](https://user-images.githubusercontent.com/99621099/172052723-841f6b92-807e-488e-b514-aececc8cc678.png)
Hardware store bottom-left, apartment tower top-right, houses on other two

![image](https://user-images.githubusercontent.com/99621099/172052948-b8e74900-e9cb-41fe-999b-c7385ed3b959.png)
House under Apartment Tower

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.675 (21H2)
- Game Version: 5f229e6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by toweroglass** [comment]
the window adjacent a fence is reasonable and makes sense, the windows creating mini courtyard next to the house also makes sense. it get's a little cramped in urban areas. The door opening into a wall however does not.

I think making it so they have to spawn with a street adjacent the door(s) would make sense. But I don't think redesigning the tile altogether is necessary.

**Comment by hexagonrecursion** [comment]
> The door opening into a wall however does not.

Depends on the order the buildings were built (as long as there is at least one unblocked door)
