### ISSUE TITLE
Sidebar map resets after minimizing and maximizing the game window.

### ISSUE THREAD

**Issue by SandNoodle** [CleverRaven/Cataclysm-DDA#58176]
### Describe the bug

Sidebar map loses track of currently visible tiles after minimizing and then maximizing application window (by, for example, alt-tabbing).
When moving only the previous invisible tiles are recalculated. "Visible" tiles stay black.

### Steps to reproduce

1. Load any save
2. Minimize the window to background
3. Maximize the window
4. Sidebar map goes black until any movement

### Expected behavior

Sidebar map would stay the same, i. e. loaded with currently seen tiles.

### Screenshots

Before minimizing:
![image](https://user-images.githubusercontent.com/34868657/172052721-70413439-487a-4aad-b672-96de5cb27b0b.png)
After minimizing and maximizing:
![image](https://user-images.githubusercontent.com/34868657/172052750-44cd160c-ad1b-4b6c-a964-1046481a1d69.png)
After moving once:
![image](https://user-images.githubusercontent.com/34868657/172053017-8fea5b0c-36e6-49b1-906f-328b6da01016.png)

### Versions and configuration

- OS: Windows 7
- Game Version: ca05dd4
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, Stats Through Skills

### Additional context

EDIT:
After testing different graphics settings (by changing map styles (solid, dots, squares), selecting different renderers, etc.) I've come to these conclusions:
- both direct3d and opengles2 have this problem (DX11 works fine).
- it does not matter what map style is used.
- it does not matter if the game is in windowed, fullscreen, or in borderless mode.

**Comment by Ezrashaw** [comment]
Seems fine on Ubuntu 22.04 (probably fine for linux in general).

**Comment by PatrikLundell** [comment]
I don't see the issue on Windows 10.1. Tried both alt-tab and minimize/maximize.

**Comment by SandNoodle** [comment]
After testing different graphics settings (by changing map styles (solid, dots, squares), selecting different renderers, etc.) I've come to these conclusions:
- both direct3d and opengles2 have this problem
- it does not matter what map style is used
- it does not matter if the game is in windowed, fullscreen, or borderless mode

**Comment by Zireael07** [comment]
What is your GPU, because that looks suspiciously like a driver problem.

**Comment by SandNoodle** [comment]
NVidia GTX970. Problem still persists on 472.12 and (up-to-date) 473.62 driver versions.
