### ISSUE TITLE
Random partial vehicle spawns on Military Base map

### ISSUE THREAD

**Issue by notbugsno** [CleverRaven/Cataclysm-DDA#58185]
### Describe the bug

Front ends of Humvees spawning on military base at random locations possibly after reloading a save. Not sure if it happens on natural bases or just on Overrun scenario. Screenshots are from 2 different saves, there is usually at least one of these somewhere on the base. 

### Steps to reproduce

1. Start Overrun scenario
2. Check base for abnormal vehicle spawns
3. If there are no abnormal spawns, save and quit
4. Load save
5. Check base for abnormal vehicle spawns

### Expected behavior

These should not spawn at all.

### Screenshots

![Screenshot from 2022-06-05 14-12-57](https://user-images.githubusercontent.com/106927596/172066300-1a53378c-b914-402a-94e0-29a92630493e.png)
![Screenshot from 2022-06-05 16-05-58](https://user-images.githubusercontent.com/106927596/172068546-4bec85fd-f109-488a-8b1e-efaf3d2d6249.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 5f229e6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
That's rampant, with partial vehicles, often with a number of strings on the tiles where the seats would have been, and it's not specific to any kind of location. I've seen these weird spawns partially inside a shop (with the rest outside), in towns, and on the tiles adjacent to habitation, but still on field/wood tiles.
My guess is that something was broken a bit when wreckages were converted into piles of vehicles, so these weirdo things spawn in odd places. Could it be that they're spawned on the wrong tile?

**Comment by Inglonias** [comment]
Yes, this is not specific to military bases. Partial vehicles can spawn anywhere. I suppose it can be explained by the story (big scary monster sliced a car in half or something), but this is a bug.

**Comment by notbugsno** [comment]
This bug wouldn't be as jarring if they didn't appear after coming back to explored areas. The first example is one I know for a fact wasn't there after starting the game since I moved all of the consumables downstairs before going to the armory, you can see the shelf where the meat slices and water would be are empty. The rest are just containers.

That's really all I did though, move some stuff, go to armory, save & quit, reload next day, go back to warehouse, go to roof to do some experimental Z-level enabled fighting, take dart to torso but forgot to wear vest, go back down and see this.

I know this report isn't exactly helpful but I honestly have no idea what triggers it, the second example is the only one I've seen consistently.
