### ISSUE TITLE
Pride Flags as potential house loot

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#58182]
### Is your feature request related to a problem? Please describe.

Since it’s pride month, I think pride flags as potential loot would be a nice and inclusive addition to the apocalyptic world of cataclysm.

### Solution you would like.

Spawn Location:
Pride Flags could spawn in houses in containers such as dressers and closets. 

Description Example:
“Pride Flag”

“This is the progress pride flag. It has six rainbow colored stripes with a multicolored arrow consisting of five lines to it’s left side. happy pride!”

**Comment by liminalRoar** [comment]
Doesn't this open the door to a whole bunch of "why is this flag/idea added but not this one?". Leading to perhaps too much focus on representing current trends in game and less on creating a rather neutral game to be enjoyed by all regardless?

What about the BLM flag? Aromantic flag? Transgender pride flag? Ukraine flag? Graysexual flag? 

I feel like taking a neutral stance on politics and ideology is much safer in general. No reason we can't fill in the blanks in our minds about what various homes and places in CDDA would have been like or believed.

Just my 2 cents.

**Comment by Termineitor244** [comment]
Pride flags and pride related items could make use of the holiday special spawns if someone decided to add the pride month to the list of cata holidays.

The (US) flag items for example (flag bikinis, flag pants, flag shirts, flag everything) can spawn normally all year, but on independence day they have increased spawns for the people that like these kind of holiday items!

I personally added Christmas and Halloween items in #53159 and #56517.

My recommendation is to add any new pride item (Or any new cosmetic only new item) as a variant to already existing items (See t-shirt variants, bikini variants, apron variants, among others), to avoid clutter of items for something that is only flavor.

**Comment by AtomicFox556** [comment]
Could we just make a single "flag" item with many description variants instead, including mentioned flags as well as any other ones people could think of? I'm opposed to representing just one kind of political ideas while ignoring others.

**Comment by Maleclypse** [comment]
This is an excellent use of the variants json and in fact would allow a basically unlimited number of flags without increasing the number of actual items.

**Comment by liminalRoar** [comment]
That would be neat to have variants on flags! I wonder if posters could be a thing too? Would be kinda cool to find a poster in some house or building and decide to take it for decoration in your house.

**Comment by Maleclypse** [comment]
> That would be neat to have variants on flags! I wonder if posters could be a thing too? Would be kinda cool to find a poster in some house or building and decide to take it for decoration in your house.

We could create variant posters but we currently have no way to display them on walls.

**Comment by liminalRoar** [comment]
I wonder if with #58067 and the graffiti variants and multi-tile support ideas. If that would go some way for supporting "posters" as well. Almost like graffiti tied to an object that can be removed and placed..

Theoretically flags can be attached to walls like posters irl too, or on a flagpole obviously.

**Comment by NetSysFire** [comment]
Variants for a generic flag item would be epic. I'd love to see a cdda logo flag, too. In general this can be used to impart much flavor into the world. Imagine having flags for all the factions.

**Comment by liminalRoar** [comment]
ooh yes. Some factions could have dedicated flags, other factions like small groups of NPCs could have randomly generated flags with one of many designs or themes and random colors picked. Then maybe the designs and colors are used on flags in their camp or on vehicles even.

**Comment by NetSysFire** [comment]
Speaking about the realism: If you just managed to find an unoccupied cabin or other small structure and are trying to survive as a small group of NPCs, a fitting flag would be the least of your worries.

**Comment by Termineitor244** [comment]
> could have randomly generated flags with one of many designs or themes and random colors picked. Then maybe the designs and colors are used on flags in their camp or on vehicles even.

I don't think we have functionality for that, the variants we have are just a different item color/description/name/symbol, and are defined with an specific ID, not by using a range of colors/patterns generated at random (Each sprite for each variant has to be defined by hand). I know some games that a similar functionality, but CDDA does not at the moment.

**Comment by Zireael07** [comment]
I know it's tangent to the original request, but yes, +100 to using flag variants to provide the factions with their own flags

**Comment by Zireael07** [comment]
@PatrikLundell: I lurk on vexillology subreddit, and there are a ton of various flags being flown in the USA (many of them slight variations of modern/past US flags). Yes, the US of A flag is by far the most common, but people many townships fly their own flags as a matter of local pride (also, same deal with specific state flags, e.g. Cali or Texas or Florida or w/e), and/or a flag of an association/political group they identify with.

I believe we could add rarity to variants, and e.g. have some T-shirts appear more commonly than others, and same for the flags.

**Comment by fairyarmadillo** [comment]
> It detracts from realism if the US flag just becomes one out of 5000 different flags, without means to ensure it still makes up 90+ percent of the flag items found, as I believe to be the case in reality. Sure, if you somehow designed a Little Italy section of a town it could have a lot of Italian flags locally, and a zombiefied Pride parade would probably drop a lot of Pride flags (which would assume the Cataclysm happened during a parade performed during the riots), and so on.

I see pride flags year round far more often than American flags. It's trendy for businesses to display them to show that they're welcoming places. People also stick them on their houses or apartments. They're probably a bit less common in rural and suburban areas where a lot of Cataclysm takes place, but they wouldn't be super rare.

Also good would be Gadsden flags, jolly rogers, Canadian flags, Mexican flags, and maybe some New England state flags. Milsurp shops could have various armed forces flags. I see all of those often enough in the United States IRL.

**Comment by MNG-cataclysm** [comment]
I've started work on this using the variant descriptions. I'm thinking about making a single "base" flag with different types as variants; like the flags of nations, pride movements, and activist groups.
Should we add any hate flags, such as the Swastika? Is that going too far for the sake of realism?

**Comment by anothersimulacrum** [comment]
No.

**Comment by AtomicFox556** [comment]
> No, do not add hate flags.

I strongly disagree (and yes, I'm not afraid to say that). If you disagree with the idea that is represented by the flag, burning it in-game is always an option. Otherwise that's on the same level as more recently released WWII-themed video games censoring German flags and symbols by replacing them with something else entirely, even if those symbols belong to in-game enemies.

However, flags descriptions definitely should not promote anything at all, and should be limited to describing what one could see while looking at the flag, and the relative rarity of variants should at least loosely reflect the popularity of those ideas among the population.

**Comment by liminalRoar** [comment]
There is a difference between a historical game focused on accuracy, and a game adding something that at face value seems unnecessary, controversial, out of context, and does not add to realism in game any (how many house in the US have a nazi flag, like 10?)

To be clear, i don't have a strong opinion either way. I don't think having an item in the game supports it. We dont support using meth but you can in game. I don't support suicide, or cannibalism, but those are in game. But i also think adding ideologies contributes nothing of importance to the game and instead adds conflict.

**Comment by Maleclypse** [comment]
This isn't getting too heated or anything but I don't think much else can be added on this topic as an issue so I've locked the issue. If someone creates PRs revolving around this topic it can be discussed there.
