### ISSUE TITLE
Starting as "Lost Submissive" with "Near-Sighted" causes you to start without glasses

### ISSUE THREAD

**Issue by pacrahna** [CleverRaven/Cataclysm-DDA#58198]
### Describe the bug

Starting a scenario with the profession of "Lost Submissive" and taking the negative trait "Near-Sighted" causes you to start without glasses, even though the trait specifies that, "you are guaranteed to start with a pair of glasses". This also renders you completely blind in any start that start in darkness.

### Steps to reproduce

1. Create a character
2. Select the "Lost Submissive" profession
3. Select the negative trait "Near-Sighted"
4. Load in, without glasses

### Expected behavior

I'd expect the start to start with glasses either being worn or on the person, as is how it works with other starts, and as is what is specified in the trait description.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 82afe21 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by SariusSkelrets** [comment]
Some scenarios and professions can override items spawned by traits like for example shower victim that will only let you spawn with a towel

Lost submissive got the no_bonus_items flag so it’s intended that they don’t get their glasses. The fact that they fled to safety still in bondage gear means that their glasses are probably still at home

**Comment by ZhilkinSerg** [comment]
That's an intended behavior.
