### ISSUE TITLE
Crash on load if saved while unloading vehicle from bike rack

### ISSUE THREAD

**Issue by Jordanb716** [CleverRaven/Cataclysm-DDA#58217]
### Describe the bug

Loading a save that took place in the middle of taking a vehicle off of a bike rack causes the game to freeze for a second and then crash. Seems to load fully, and shows the game loaded as normal, but presumably crashes when it tries to resume the activity.

I was able to recover the save by opening up the .sav file, going to the "activity" section that seemed to be describing the PC's current action and replacing it with.
```
"activity": {
      "type": "ACT_NULL"
    },
```
(If anyone needs to do this, use something to format the file as readable json, it makes it much easier and seems to load fine.)

### Steps to reproduce

- Enable autosaves.
- Attach two vehicles together.
- Remove the vehicle from the bike rack timed so the game saves in the middle of it.
- Quit and load that save.

### Expected behavior

Either:
A) Game should load that save correctly and resume unloading the vehicle.
B) Game should wait for the current activity to complete before autosaving to avoid making a corrupted save

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 4f1c3fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8846034/debug.log)
There was no crash.log in the folder.
[save](https://github.com/CleverRaven/Cataclysm-DDA/files/8846040/Granton.zip)

**Comment by RoyBerube** [comment]
It crashes when trying to access the vehicle parts. The `vehicle &` stored in the activity is no longer valid after deserializing.

My guess is that saving a tripoint would be safer than saving the vehicle reference.
