### ISSUE TITLE
Ledge eats grappling hooks

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58216]
### Describe the bug

After using a grappling hook it's impossible to recover it. Also there's an error:
```
(continued from above) ERROR : src/game.cpp:11147 [void game::vertical_move(int, bool, bool)] Failed to find a spot to displace into.
```

### Steps to reproduce

Load the attached save, climb down, take down the rope, notice you don't have it anymore anywhere.

### Expected behavior

Rope conservation.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-8827-g293c808cb2-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[2022.05.21.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8845619/2022.05.21.zip)

**Comment by hexagonrecursion** [comment]
Which ledge did you climb? In the save you have attached there are multiple ledges nearby. I tried one, but was **able** to recover the hook.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cb051eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by l29ah** [comment]
The one directly next to the player. Also mind that the player has two hooks initially.

**Comment by EvanBalster** [comment]
I've been working with grappling hooks in #68265 and related contributions, and if this was ever a bug it isn't anymore.

Note:  taking down a grappling hook doesn't currently put it in your inventory; the item is left sitting on the ground.  Could use QoL/UX improvement.
