### ISSUE TITLE
Wasp nests can generate in the air

### ISSUE THREAD

**Issue by qazW12345** [CleverRaven/Cataclysm-DDA#58219]
### Describe the bug

Wasp nest can generate in the air (Z-level 1) with nothing to support it.

First 2 screenshots show a nest that has generated in the air, and the next 3 a effects of breaking a such nest. Notably, there is dirt below the walls, but it doesn't appear after going one Z-level down (to Z-level 0)

### Steps to reproduce

1. Find a structure with wasp nest - here motel
2. Use stairs to reach Z-level 1 where the nest is
3. Part of the nest might generate in the air

### Expected behavior

I expected the wasp nest blocks to generate only if the block below is not air. A possible exception could be a nest which has a part that is not directly supported by blocks below, but the structure as a whole has contact with wall/floor or other otherwise solid material at some point.

### Screenshots

![obraz](https://user-images.githubusercontent.com/44544794/172212446-0866ba20-1165-424b-be22-87ada054b585.png)
![obraz](https://user-images.githubusercontent.com/44544794/172212468-95499566-8405-46e3-b8ea-cb6a4024b8ea.png)

![obraz](https://user-images.githubusercontent.com/44544794/172213531-d3bdd6b4-bd00-42e9-b3e9-af14e3d18b1d.png)
![obraz](https://user-images.githubusercontent.com/44544794/172213557-1631104c-6ee4-47b8-b9f7-eac470b2f2e5.png)
![obraz](https://user-images.githubusercontent.com/44544794/172213565-a142e64b-88fa-4ac1-8b0d-2be0225070e1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 82afe21 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Night-Pryanik** [comment]
Duplicate of #56682.
