### ISSUE TITLE
Kord did not spawn (Guaranteed items not guaranteed on lower item spawn scaling factor?)

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#58225]
### Describe the bug

Tried doing Cody's quest to get the Kord 6P67 from the gunshow, but it's not there. This is likely due to me running a world with "Item spawn scaling factor" set to 0.50, as I've experienced this with other supposedly guaranteed spawns like the hazardous waste sarcophagus code and the TCL keycards.

However, it becomes a much bigger problem here, because you absolutely 100% unavoidably _need_ this item in order to progress the quest line.

### Steps to reproduce

1. Generate a world with low Item spawn scaling factor.
2. Find Cody and accept her quest.
3. Proceed to gun show
4. Do not find Kord 6P67
5. Repeat a few times if necessary

### Expected behavior

Quest items should always spawn. Probably there needs to be some kind of override that tells the game "always generate this regardless of world settings."

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 90e1eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

[New New New Caledonia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8848803/New.New.New.Caledonia.zip)
Including save file so you can see it just ain't there if you want.

**Comment by PatrikLundell** [comment]
In my world I've seen a second gun show, although I haven't visited it. Thus, there should still be some hope for you to be able to fulfill the quest (this does not in any way try to say missing quest items isn't a bug).

**Comment by Terrorforge** [comment]
Oh that's good to know, but I just debugged one in.
