### ISSUE TITLE
Bandits will landmine own base, including walls

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#58221]
### Describe the bug

Bandits will place landmines in their base, along commonly used and or required paths

### Steps to reproduce

1. Find bandit base
2. Roam around in base, step on landmine while following path
3. Find landmine in a wall, may require several attempts

### Expected behavior

Bandits shouldn't landmine their walkways, and shouldn't be able to landmine their walls

### Screenshots

![image](https://user-images.githubusercontent.com/43324177/172256885-f9525f0f-6069-4dec-9e5a-4aa8cc77b4b6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: e87eb80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Combat Robotics [combat_robotics],
    SpeedyDex [speedydex],
    Customizable Guns [customizable_guns],
    Tamable Wildlife [Tamable_Wildlife],
    Custom Garbagetruck [custom_garbagetruck]
]

**Comment by PatrikLundell** [comment]
/confirmed

I've seen this as well. It was present in 0.E-2, and was still present in Experimental as of maybe a month or two ago (when I did the quest to rid a fort of bandits).
Land mines were both outside of the fort (which is reasonable) and inside in various places, including bike shed walls (and possibly other walls as well), plus on various highly unsafe locations inside the outer perimeter.
