### ISSUE TITLE
Attempts to pry a crate don't consume time

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58229]
### Describe the bug

You attempt to pry open the crate using your time machine

### Steps to reproduce

Pry a crate noting the time on your clock.

### Expected behavior

Seconds increasing.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-8827-g293c808cb2-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 82afe21 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
