### ISSUE TITLE
invalid body part id "leg_lower_l"

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#58239]
### Describe the bug

Sometimes I get the below error message when fighting monsters.

 DEBUG    : invalid body part id "leg_lower_l"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 477
 VERSION  : c355923

### Steps to reproduce

Go fight zeds.

### Expected behavior

No errors.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/172337479-846bba20-a415-4b7a-97d6-0dff1e6d9bce.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: c355923 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by aMegaSloth** [comment]
Duplicate of the bug I reported. #57779
