### ISSUE TITLE
Can't place carpet on any floor except t_floor

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#58245]
### Describe the bug

While I was doing some renovation in the evac shelter's basement, I noticed that I can't place the carpets on the linoleum floor. I removed the linoleum floor and tried to place it on the concrete floor, it didn't work. Even the wooden floor I recently built didn't worked at all.

### Steps to reproduce

1. Get yourself a carpet and nails
2. Go to an indoor floor that aren't "floor" (i.e. concrete floor, wooden floor)
3. Open the construction menu
4. Notice that you can't construct "place carpet"

### Expected behavior

I should have the ability to carpet the place regardless of the floor.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 7ffd17f [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Crow's Hairstles 2: Bright [hairmod2_bright],
    Crow's Hairstles 2: Ears and Tails [hairmod2_earsAndTails],
    Crow's Hairstles 2: Natural [hairmod2_natural],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Recipe Fix [recipe_fix],
    Blaze Industries [blazeindustries]
]

### Additional context

I don't know if this is intentional or not since I saw the basement carpet has "floor" under it, but it feels like an oversight.

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 74ad8be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
