### ISSUE TITLE
'Hunted' scenario segfault

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#58242]
### Describe the bug

Starting a new game with the Hunted scenario crashes the game. Happens often but not every time.

### Steps to reproduce

1. Start a new game with the hunted scenario
2. repeat until crash

### Expected behavior

no segfaults

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 7ffd17f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8852547/config.zip)

**Comment by taatu** [comment]
Confirmed, stack trace: [https://pastebin.com/raw/2VUrkn2w](https://pastebin.com/raw/2VUrkn2w)

(linux 5.4.0-113-generic)
(version gb3374d)

**Comment by Farseer2** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/58382 fixes it :)
