### ISSUE TITLE
Giant Wasps become sludged

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58253]
### Describe the bug

Giant Wasps, when crossing over sludge patches, become afflicted by the "sludged" effect despite being flying insects.

### Steps to reproduce

1. ) Lure wasps onto sludge patch
2. ) Marvel as they still move ten times faster than you even with the speed debuff
3. ) Wonder why they keep landing in the goo. Does it taste good? Should you eat it?
4. ) Decide not to eat the goo

### Expected behavior

Wasps should be able to resist the temptation to play with sludge. They have responsibilities.

### Screenshots

![image](https://user-images.githubusercontent.com/104868222/172473860-bd775dfe-fd47-41c7-a103-cb1221df8817.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: a62e76c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 74ad8be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
