### ISSUE TITLE
Rubik can be fooled to take 0 anesthetic with an anesthesia kit

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58252]
### Describe the bug

Apparently, Rubik can only pick it up from a proper container.

### Steps to reproduce

Load the attached game, note you have 6L of anesthetic, talk with Rubik, agree, `You don't have a anesthetic!`, look at his happy face, check your inventory to see that no anesthetic was given.

### Expected behavior

Taken anus fetick.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-8927-g7e8b40a989-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[2022.05.28.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8856270/2022.05.28.zip)

**Comment by Cimanyd0** [comment]
Just saw this myself.

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 49b8098 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by l29ah** [comment]
Related: https://github.com/CleverRaven/Cataclysm-DDA/issues/56542

**Comment by RenechCDDA** [comment]
I experienced the same issue in b9c5366 despite the anesthesia being present in an anesthetic kit. It gave me notice that I didn't have any (incorrect), then went ahead with the surgery and did not remove any anesthetic.

Subsequent installs are also not taking anesthetic but I'm unsure if that is intended.

**Comment by RenechCDDA** [comment]
This appears to have been resolved at some point. Can no longer reproduce on 08a7eee6413e86e9d69db3e27dcb535e87436d74
