### ISSUE TITLE
Vehicles and appliances temporarily disappear and reappear

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#58267]
### Describe the bug

Multiple times, I have observed all the vehicles and appliances in my world to just vanish.  They eventually reappear after walking around a bit, and reappear if I save and load my game.  I have no idea what triggers this and have not been able to reproduce it, but this time I saw it happen _while_ disassembling a vehicle - I just saw it (and every other vehicle on the screen) disappear, and then got a debug message.

```
 DEBUG    : Activity ACT_VEHICLE: vehicle not found

 FUNCTION : complete_vehicle
 FILE     : C:\git\Cataclysm-DDA\src\veh_interact.cpp
 LINE     : 3236
 VERSION  : 0.F-8931-gf316f36718-dirty
```

### Steps to reproduce

Unknown.  I have seen this at least four times but have been unable to reproduce it intentionally.

### Expected behavior

I expect vehicles and appliances to not disappear.

### Screenshots

After my vehicles disappeared:
![image](https://user-images.githubusercontent.com/3675402/172543757-c755c2c8-ee9a-4b42-9f69-4f9948a87c2d.png)

They then reappeared after I walked a couple tiles away and back:
![image](https://user-images.githubusercontent.com/3675402/172543809-5504f8ea-7159-42ec-bb15-f746ae569315.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1348 (20H2)
- Game Version: 0.F-8931-gf316f36718-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ilurker** [comment]
I've been encountering this. While it's not consistent, the most reliable trigger appears to be sleeping or utilizing the optical dampener CBM while within the vehicle itself. As with the reporter's experience, moving appears to correct the issue.

The following error log in consistently generated:

16:19:43.100 : Starting log.
16:19:43.100 INFO : Cataclysm DDA version fdf38c4
16:19:43.100 INFO : [main] C locale set to English_United States.utf8
16:19:43.100 INFO : [main] C++ locale set to 
16:19:43.100 INFO : SDL version used during compile is 2.0.20
16:19:43.100 INFO : SDL version used during linking and in runtime is 2.0.20
16:19:43.140 INFO : Number of render drivers on your system: 5
16:19:43.140 INFO : Render driver: 0/direct3d
16:19:43.140 INFO : Render driver: 1/direct3d11
16:19:43.140 INFO : Render driver: 2/opengl
16:19:43.140 INFO : Render driver: 3/opengles2
16:19:43.140 INFO : Render driver: 4/software
16:19:43.144 INFO : [options] C locale set to English_United States.utf8
16:19:43.144 INFO : [options] C++ locale set to 
16:19:43.144 INFO : Setting language to: 'en'
16:19:43.144 INFO : [i18n] Scanning core translations from lang/mo/
16:19:43.144 INFO : [i18n] Scanning mod translations from F:/games/dda/userdata/mods/
16:19:43.144 WARNING : opendir [F:/games/dda/userdata/mods/] failed with "The system cannot find the path specified.".
16:19:43.473 INFO : Active renderer: 1/direct3d11
16:19:43.675 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
16:19:45.442 INFO : Setting language to: 'en'
16:19:45.630 WARNING : opendir [F:/games/dda/userdata/mods/] failed with "The system cannot find the path specified.".
16:19:50.448 WARNING : opendir [F:/games/dda/userdata/save/Elk Springs/mods] failed with "The system cannot find the path specified.".
16:19:50.985 INFO : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:64: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'class overmap_special' does not track object sources
16:20:01.186 INFO : Loaded tileset: UltimateCataclysm
16:20:01.186 INFO : Loaded tileset: UltimateCataclysm
16:34:55.300 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1110 [unboard_vehicle] map::unboard_vehicle: vehicle not found
16:34:57.454 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1069 [board_vehicle] map::board_vehicle: passenger (Alan Givens) is already there
17:37:09.019 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1110 [unboard_vehicle] map::unboard_vehicle: vehicle not found
17:37:11.463 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1069 [board_vehicle] map::board_vehicle: passenger (Alan Givens) is already there
18:07:15.367 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1110 [unboard_vehicle] map::unboard_vehicle: vehicle not found
18:07:17.207 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp:1069 [board_vehicle] map::board_vehicle: passenger (Alan Givens) is already there

**Comment by Ilurker** [comment]
I had this happen again today and couldn't resolve it via the normal methods, but I did notice that my window curtains were still blocking light, which might provide some clues? I checked and any roundabout ways to interact with items in the vehicle didn't work (action menu, consume menu, smashing, etc).

![image](https://user-images.githubusercontent.com/104868222/174319316-8c920a19-209d-4e8b-9e94-a4aafcb48b6a.png)

**Comment by mkrutov** [comment]
Please check if patch by @andrei8l fixes this issue as well

**Comment by dholmes215** [comment]
I played with that patch for hours yesterday and the bug never happened.  I never had a reliable recipe to reproduce the bug, but it happened often enough that it seems likely that the patch fixed it.  I'll continue playing with it today.
