### ISSUE TITLE
Eating vegetables gives character "Ate meat" morale debuff

### ISSUE THREAD

**Issue by leifgiering** [CleverRaven/Cataclysm-DDA#58264]
### Describe the bug

If your character eats a vegetable while having the 'hates vegetables' trait, they will suffer a morale penalty for eating meat.

### Steps to reproduce

1. Create character with 'hates vegetables' trait
2. Eat any vegetable
3. Check morale status

### Expected behavior

Character should receive 'ate vegetable' morale debuff instead of 'ate meat' debuff.

### Screenshots

![cdda_meat_bug_1](https://user-images.githubusercontent.com/8811860/172509728-53c9327c-b463-4b2e-8980-1796b699330a.png)
![cdda_meat_bug_2](https://user-images.githubusercontent.com/8811860/172509733-a1009348-3778-4a94-baeb-97aa4866a1c4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: dbe28af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZeroInternalReflection** [comment]
I can confirm this behaviour in:
<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 90e1eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

In fact, the reverse is also true.  A vegetarian character eating meat will get a morale debuff for "Ate vegetables".
It looks like the code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0d4107d70631e4700869b972d561bb4f493b638a/src/consumption.cpp#L632-L648
Expects  "morale_x" to be a debuff message, while the json:
https://github.com/CleverRaven/Cataclysm-DDA/blob/0d4107d70631e4700869b972d561bb4f493b638a/data/json/morale_types.json#L132-L141
Provides a positive message for those traits.

They should probably be pulling new "morale_antimeat" and "morale_antivegetable" strings.

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 74ad8be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
