### ISSUE TITLE
Optionally shrink or remove ASCII coverage art

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#58273]
### Is your feature request related to a problem? Please describe.

I usually play my game at 2x scale as I find the 1x UI harder to read, especially when streaming or recording, and the new coverage ASCII art in the examine panel for armor is much too big at this scale. 

### Solution you would like.

It would be great if the game detected UI scale and swapped out the ASCII art for something that fit better on my screen, or if it could optionally be disabled entirely. The information presented by the graphic is redundant, so removing it wouldn't hurt anything.

### Describe alternatives you have considered.

Move the coverage graphic to the very bottom so that people don't have to scroll more than an entire screen length just to find the protection, encumberance, and numerical coverage values.

### Additional context

![2xbad](https://user-images.githubusercontent.com/94415528/172601113-717dd685-b1b9-4569-9cdc-38815e69699a.png)

**Comment by GuardianDll** [comment]
I think it can be turned off somewhere in the settings

**Comment by fairyarmadillo** [comment]
You're right! Closing this then.

**Comment by anyamartin** [comment]
Is the option you mention here "Enable ASCII art in item and monster descriptions?" Because I have tried to disable the art through that and it doesn't appear to work, even after a reload.
