### ISSUE TITLE
Bone broth recipe is way too expensive

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58276]
### Describe the bug

Crafting 3L of bone broth requires 120 bones, which at 225g per unit of bone means 27kg of bones.

### Steps to reproduce

Look at the recipe of the bone broth

### Expected behavior

According to first result from google search on the topic (https://theforkedspoon.com/bone-broth-recipe/) 5.5L (24 cups) of bone broth requires only 4.5kg (10 pounds) of bones

### Screenshots

![expensive_bone_broth](https://user-images.githubusercontent.com/55463047/172620104-87169000-ddef-461e-b763-3ac34e643e41.png)

### Versions and configuration

- Game Version: 0.F-3-3 from cataclysm-dda-sdl official Debian package

**Comment by chrispikula** [comment]
I think that the rational there is that it's more of a marrow broth, rather than a bone broth.  When I cook bone broth, it usually takes 12-20 hours on the stove, rather than 4, but I can use bones that don't have much marrow in them, such as turkey or chicken bones.

**Comment by TheShadowFerret** [comment]
> I think that the rational there is that it's more of a marrow broth, rather than a bone broth

As we have bone marrow as an explicit item now, the recipe needs to be updated then.

**Comment by Inglonias** [comment]
Given the choice between needing too many ingredients and not taking enough time, I would prefer the latter as the lesser of two evils.

**Comment by x-qq** [comment]
I think adding bone marrow as an alternative ingredient to the recipe and increasing the recipe output from 0.25L to 1L per 10 bones (2.25kg of bone) would be a reasonable fix.

**Comment by Grubleafeater** [comment]
I would like to add that bone broth, with the advent of vitamins, has COMPLETELY INSANE VITAMINS. As in, the broth has none, and the gelatin has a smattering of all 3 vitamins.

The bones themselves have 96% daily calcium! That's it, that's all they have!
