### ISSUE TITLE
Innawood bronze nails creation path

### ISSUE THREAD

**Issue by ZenithStoneoath** [CleverRaven/Cataclysm-DDA#58279]
### Describe the bug

Recently added bronze nails for innawood require a hotcut, which is only craftable with level 3 anvil. 
Moreover, the clay crucible is required twice in the recipe.

### Steps to reproduce

Load Innawood mod, spawn bronze tools and materials, try to make bronze nails.

### Expected behavior

The required tool should be acquirable with anvil 2 and hammering 2. For example pair of flatjaw tongs. The crucible should be only needed once in the recipe.

The point in making bronze nails is to be able to produce nail dependent crafts earlier with lower tool qualities (anvil, hammering level 2) and material (bronze).

### Versions and configuration

latest experimental of 08.06.2022

**Comment by Jetshelby** [comment]
Bronze Hotcuts are also currently uncraftable. This would resolve the issue I think, were this were fixed.
