### ISSUE TITLE
Touching c_unset in the color manager prevents the game from loading

### ISSUE THREAD

**Issue by ZeroInternalReflection** [CleverRaven/Cataclysm-DDA#58286]
### Describe the bug

This testing came about from a conversation with @vetall812 (I hope I got their GitHub account correct) on Discord.  They were trying to change a large number of colour definitions for alternative themes, and were getting error messages.  I'm pretty sure there are other bugs hiding in there, but this is the only one I've been able to pin down in further testing:

1] Setting "c_unset" to a colour that's in use will cause errors loading that colour
c_unset = c_blue results in:
<details><summary>Error message</summary>
 DEBUG    : Error: Json error: data/json/move_modes.json:63:20: invalid color name

    "name": "prone",
    "panel_color": "green",
    "symbol_color":
                   ^
                    "blue",
    "exertion_level": "NO_EXERCISE",
    "change_good_none": "You lie down.",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 949
 VERSION  : 90e1eb2
</details>
c_unset = c_magenta results in:
<details><summary>Error message</summary>
 DEBUG    : Error: Json error: data/core/weather.json:24:13: invalid color name

    "type": "weather_type",
    "name": "NULL Weather - BUG",
    "color":
            ^
             "magenta",
    "map_color": "magenta_red",
    "sym": "0",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 949
 VERSION  : 90e1eb2

</details>
c_unset = c_light_red_magenta loads properly

2] Setting a colour that's in use to c_unset will similarly result in being unable to load JSON with that colour:
c_light_gray = c_unset results in:
<details><summary>Error message</summary>
 DEBUG    : Error: Json error: data/json/move_modes.json:46:20: invalid color name

    "name": "crouch",
    "panel_color": "light_blue",
    "symbol_color":
                   ^
                    "light_gray",
    "exertion_level": "MODERATE_EXERCISE",
    "change_good_none": "You start crouching.",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 949
 VERSION  : 90e1eb2

</details>

### Steps to reproduce

1. 'Main menu'
2. 'Settings'
3. 'Colors'
4. Set colours as specified
5. Attempt to load a game or create a character
6. See an error message about failing to load colour-related data from JSON
7. Get kicked back to the main menu 

### Expected behavior

Custom colour settings should not result in error messages or crashes.

c_unset should probably not be customizable/usable as a custom colour.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 90e1eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Similar behaviour has also been observed in equivalent Linux curses builds, and by vetall812 in Windows.

**Comment by ZeroInternalReflection** [comment]
Right, that was the other one I was planning on mentioning.  However, I've only been able to replicate it with the same root cause.  In this example, both c_unset and c_light_gray are set to i_light_gray:
![i_light_gray_tags_1](https://user-images.githubusercontent.com/89038572/172975689-f4fd5ead-cc22-4900-b8c4-669aae473684.png)
![i_light_gray_tags_2](https://user-images.githubusercontent.com/89038572/172975694-f68d8788-c768-48f1-bb9b-63245eccb6cc.png)
Resulting in the submenu being unable to figure out tags for c_light_gray.  Removing the ability to set a custom colour for c_unset should fix this as well.

**Comment by leemuar** [comment]
Where does this color definition changes happen? In c++ code or somewhere else?
