### ISSUE TITLE
Cannot disassemble a large item, even with a workbench

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#58288]
### Describe the bug

Trying to crack open this mech lifter. it would disassemble in my car. so i drag it in this house and set it on a workbench. no matter what it won't disassemble. 

![image](https://user-images.githubusercontent.com/81603517/172734375-17b6cbac-8c79-40ad-bf36-93cd4e7343a5.png)

### Steps to reproduce

So I made a fresh character and spawned everything I needed and found that with high enough morale they will start to deconstruct but as soon as they hit negative they will stop and say the item is too big and stop. each time i debugged positive morale they will start again then stop.

If this is intended behavior it should be giving me a message that says my morale isn't high enough to handle a heavy object.

### Expected behavior

I would expect that with a workbench that holds 1000L i should be able to deconstruct a 250L item.

### Versions and configuration

**- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: dbe28af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth]
]
**

**Comment by hexagonrecursion** [comment]
I am sorry, but I could not reproduce the issue. Could you please share your save file?

![Screenshot from 2022-06-09 08-52-33](https://user-images.githubusercontent.com/52621858/172775137-a9d6ac31-6103-4290-a6ed-9303a3ff0c9b.png)

- OS: Linux
    - OS Version: <unknown>
- Game Version: befb7ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
What's the STR of the OP's character?
It's been an issue for a long time that any in-progress crafting won't be worked on while on the work bench, but actually has to be picked up and wielded to be worked on. The initial crafting can be done on the work bench, but no continuation will (if you e.g. make a break to drink something). It may be the same issue with deconstruction.
The issues about size/weight in @hexagonrecursion's reproduction attempt seems to indicate that character struggles with the wielding of the in-progress item.

**Comment by toweroglass** [comment]
> What's the STR of the OP's character?
It's been an issue for a long time that any in-progress crafting won't be worked on while on the work bench, but actually has to be picked up and wielded to be worked on. The initial crafting can be done on the work bench, but no continuation will (if you e.g. make a break to drink something). It may be the same issue with deconstruction.
The issues about size/weight in @hexagonrecursion's reproduction attempt seems to indicate that character struggles with the wielding of the in-progress item.

I'm aware of that issue and have always dealt with it. My character has at least 10 str. Always. I'm not a masochist lol. This is the first time I've ever seen this message and didn't notice the improvement from morale until i actually made a test character.

When I get home I'll zip my test character save file and post it. My current run has one non-repo mod and I didn't want my issue to be ignored over that. If I'm feeling productive i'll even make a new test character and try again. I'll backup my save on my current run and update too in case it was fixed in the last 3 days.

**Comment by Qrox** [comment]
Workbenches have speed penalties for exceedingly large or heavy crafts and disassemblies, so I think you can disassemble the mech lifter with a workbench that has a higher weight limit (for example, "ground crafting spot"). The messsage could definitely be improved though.

**Comment by toweroglass** [comment]
> Workbenches have speed penalties for exceedingly large or heavy crafts and disassemblies, so I think you can disassemble the mech lifter with a workbench that has a higher weight limit (for example, "ground crafting spot"). The messsage could definitely be improved though.

Ground crafting spot was the first thing i tried. I then went into a house and tried a workbench since the message seemed so insistent. I thought it was something new.
I forgot to test last night, but I should be able to try it again today.

**Comment by Qrox** [comment]
Ground crafting spot has the highest weight limit. If it didn't work we should probably increase that limit or add another type of workbench specialized for large object disassembly.

**Comment by hexagonrecursion** [comment]
I have done a bit more testing:

- Ground crafting spot - can **not** disassemble. (Same message as the original bug report)
- A workbench (Construction -> Build a work bench ) - **can** disassemble

[test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8884135/test.zip)
