### ISSUE TITLE
Boat sinking at random. Edit: vehicle disappears at random, even when I moved it ashore. 

### ISSUE THREAD

**Issue by Rayeneth** [CleverRaven/Cataclysm-DDA#58285]
### Describe the bug

With enough height above the water my boat is sinking. It sinks no matter what action I take, including dumping the contents of the boat. 

### Steps to reproduce

1. download my save
2. do nothing for an hour
3. watch boat sink
4. scratch head
[Magic Falls.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8865450/Magic.Falls.zip)
.

### Expected behavior

Boat not sinking randomly. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 4231084 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm]
]

**Comment by mkrutov** [comment]
I've had this happen to me as well, however I'm not able to make it reproducible. Just was repairing my car's damages and replacing bits and bobs, bam it disappeared.

**Comment by mkrutov** [comment]
In fact, not only *my* vehicle disappeared. All wrecks in the loaded area did.

**Comment by mkrutov** [comment]
![Screenshot_20220617_213144](https://user-images.githubusercontent.com/48674477/174390383-1da3942d-8754-4ede-9422-bc405181ccd2.png)
It happened again after auto-driving for a little bit - I was asked "you see monsters, continue driving?", answered yes, and next game tick vehicle was gone. I've tried to repeat the same route again, doesn't happen. Might be tied somehow to the vehicle skidding as seen in screenshot?

**Comment by mkrutov** [comment]
Tried various combination of zombies and other monsters and autodriving, wasnt' able to reproduce it on purpose.

**Comment by mkrutov** [comment]
[Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8931043/Debug.zip)
In this file problem is pinned to exact second it happens. When you load it you press "." one time and vehicle disappears. Moreso, if you add more vehicles by debug-spawning them, ALL loaded vehicles disappear. This doesn't affect vehicles spawned after the fact, just something happens this exact tick which makes all vehicles in your immediate surroundings go poof.

I think that this should be a release blocker as this has very severe gameplay implications.

**Comment by Rayeneth** [comment]
That explains why I was able to prevent it by running until it unloaded,
waiting, and running back after the tick in question.  Thank you for your
thoroughness.

**Comment by mkrutov** [comment]
Oh yeah, teleporting away, skipping 1 tick and teleporting back also makes the vehicle not disappear. However, all loaded vehicles in spot you'd teleport to do indeed disappear.

**Comment by andrei8l** [comment]
/confirmed Caused by `"remove_vehicle"` in the mapgen update called by `EOC_RandEnc_Roadstop_remove`.

Possible patch:
```diff
diff --git a/src/mapgen.cpp b/src/mapgen.cpp
index 7500031d57..e59440a3d6 100644
--- a/src/mapgen.cpp
+++ b/src/mapgen.cpp
@@ -3018,7 +3018,7 @@ class jmapgen_remove_vehicles : public jmapgen_piece
                     }
                     if( remove ) {
                         dat.m.destroy_vehicle( &vp->vehicle() );
-                        get_map().clear_vehicle_level_caches();
+                        dat.m.rebuild_vehicle_level_caches();
                     }
                 }
             } else {
@@ -3033,7 +3033,7 @@ class jmapgen_remove_vehicles : public jmapgen_piece
                         }
                         if( remove ) {
                             dat.m.destroy_vehicle( &vp->vehicle() );
-                            get_map().clear_vehicle_level_caches();
+                            dat.m.rebuild_vehicle_level_caches();
                         }
                     }
                 }
```

**Comment by mkrutov** [comment]
This holds water as I've had a caravan with Merchant NPC stationed in a few tiles away from me when this happened. 

Also, I've just tested this patch and it fixes issue on my side. Thanks @andrei8l !

P.s. however imo function named "clear vehicle level caches" should not *remove* actual vehicles from the map. So may be there's a point in revising that function?

**Comment by Zireael07** [comment]
#58267 is likely related given your findings
