### ISSUE TITLE
X Transcending without any mutations, do not give any mutations

### ISSUE THREAD

**Issue by OldFriendEr** [CleverRaven/Cataclysm-DDA#58301]
### Describe the bug

If a player does not have enough mutations to cross the threshold then X Transcending will not grant any mutations until, the player looses X Transcending status. I would guess that is because the transcending stage only tries to cross the threshold instead of mutating.

### Steps to reproduce

1. Create a new player without any mutations or trains
2. Inject Alpha primers until Alpha Transcending
3. Inject Catalyst or two to get Warping.
4. Spend 2 days

### Expected behavior

In case the player is not ready to transcend, I would expect transcending status to work just like the transforming status, and keep on getting the regular mutations, until it is possible to transcend If the mutations did not reduce the transcending status.

### Versions and configuration

- version 93cf075 (tiles)
- build 2022-06-08-1832

**Comment by hexagonrecursion** [comment]
> Alpha Transcending

I assume you mean Alpha Metamorphosis

I am sorry, but I could not replicate the bug:
![image](https://user-images.githubusercontent.com/52621858/177045949-f4f5f6e6-4460-468e-9385-9d804f72e7bc.png)

The effects screen *after* taking the above screenshot:
![image](https://user-images.githubusercontent.com/52621858/177045935-8e5bf1f7-8c29-4b08-984c-4f2220d62cde.png)


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
