### ISSUE TITLE
Jay killed by his own turret

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#58313]
### Describe the bug

Came a little close to a nearby mass grave while driving over to the isolated merchants, and after I bought membership in the co-op from Cody, I came back to find Jay dead in his own house with a lot of bullet casings around one of his turrets.

### Steps to reproduce

1. Pull lots of enemies to the west side of the compound
2. Probably Jay will die

### Expected behavior

People should generally not be killed by their own turrets.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/172942572-1c418e58-c646-41fb-a5a8-4ac023b04e77.png)
Alas, I hardly knew ye.

![image](https://user-images.githubusercontent.com/5107449/172942794-6762fc29-f526-41c3-ad85-516b45d56828.png)
This sightline seems to be the culprit. The turret saw zombies approaching the west side of the compound and started shooting, and Jay got in the way.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: f689b47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

I guess this is technically not a bug, but it shouldn't be _too_ much of a problem so shift things around so the interior turrets can't see outside, which should prevent this from happening. Probably do the same for Cody's interior turret as well, just in case.

**Comment by RoyBerube** [comment]
/confirmed I've seen it happen with friendly npcs and vehicle turrets.

https://github.com/CleverRaven/Cataclysm-DDA/blob/fc2371d1f4924093e6e566b30f63ea5b1af619c7/src/turret.cpp#L588

This is used by turrets, and the method only checks for the player character being in the line of fire. Any other npc is not factored in to the avoidance.

**Comment by Terrorforge** [comment]
That's probably worth adjusting, but that function is absolutely no foolproof. I've been shot by my own turrets on many occasions, so you'd probably still want to adjust the map to make absolutely sure it can't happen.

**Comment by NetSysFire** [comment]
Semi-relevant: #54752

**Comment by MNG-cataclysm** [comment]
I tested this on version windows-tiles-sounds-x64 2022-10-08-0525, and Jay remained unscathed. I think this issue has been resolved somewhere along the line.

**Comment by NetSysFire** [comment]
Probably resolved by #59795, but not sure if this is the specific PR that fixed this
