### ISSUE TITLE
Make it worth it to take off uncomfortable clothing and gear sometimes

### ISSUE THREAD

**Issue by AtomicFox556** [CleverRaven/Cataclysm-DDA#58312]
### Is your feature request related to a problem? Please describe.

Currently the characters have no issues constantly wearing plate armor, footwear and other gear that wouldn't be desirable to wear constantly: most people wouldn't want to wear plate armor while sleeping, and people generally prefer to take off rigid footwear whenever they don't have to be wearing it.

### Solution you would like.

Wearing certain clothing items while sleeping could make it harder to fall asleep and/or provide negative morale after waking up. This would affect primarily rigid items like plate armor, and to a much lesser extent, any items with high thickness such as leather armor or Kevlar vests. Obviously is this is implemented, there would need to be an option to automatically take off all gear that would be uncomfortable to sleep in before going to sleep, and then to put it all back on once the character wakes up.

Body parts that have been wet for very long could be affected by skin maceration, causing morale penalty at most. This is generally much more of an issue for feet due to poor breathability of most footwear if compared to normal clothing, and the condition can progress much further for the feet: trench foot could cause pain, actual damage and even infection at some point if not taken care of. Certain skin mutations related to aquatic creatures could probably prevent this from happening completely, as they're used to being immersed in water.

Crafting and similar tasks (such as lockpicking) could be negatively affected by hand encumbrance by taking more time and/or reducing success chance: one possible scenario where it'd matter is the character trying to craft something outside in winter while wearing mittens to prevent their fingers from freezing off. If this is implemented, there would need to be a way to automatically take off everything that gets in the way before starting the task, and then replacing it once the task is finished.

Weariness accumulation could be increased by encumbrance over all the body, to make it desirable to wear light clothing while doing anything physically exerting, unless you're deliberately trying to exert yourself more by digging pits while wearing heavy armor.

### Describe alternatives you have considered.

None; can't think of anything else right now.

### Additional context

None.

**Comment by PatrikLundell** [comment]
Any such implementation would have to take great care not to cause it to devolve into a micro management dressing game. Automatically take on/off clothing works in some cases, but can be lethal in others, for instance.

**Comment by fairyarmadillo** [comment]
We have a comfort system that looks for soft chairs/bedding, the least we could do is deny the bonus if the character is wearing rigid gear. That would provide a positive incentive to remove armor without making the micromanagement mandatory.

**Comment by PatrikLundell** [comment]
You'd still be penalized for not subjecting yourself to micro management hell in that case, even if this penalty would come in the form of withholding a benefit you reaped previously.

**Comment by Zireael07** [comment]
I think micromanagement issue could be avoided with something like auto-drinking that already exists. Similarly, IIRC the character takes off armor to sleep.

**Comment by fairyarmadillo** [comment]
> You'd still be penalized for not subjecting yourself to micro management hell in that case, even if this penalty would come in the form of withholding a benefit you reaped previously.

Comfort is a small enough benefit that I'd happily take the hit. I cram tallow down my character's throat when I don't feel like micromanaging a balanced meal. It's not good for them but I don't always care.

**Comment by toweroglass** [comment]
I like the "auto strip and auto dress" method. Could add it to the sleep menu before or after setting an alarm. This way you have pros and cons to measure. Am I safe enough to take the time to get dressed in the morning? Am i sleeping rough in a city and might get woken up by some mobs? 
This way you aren't just abstracting actual activities but canceling getting dressed in the morning might be necessary if you have to fight.

This would have the added pro of not overheating at night, seeing as blankets are no longer magic temperature maintainers. I always had it in my head that having a blanket in my bed meant i was regulating my own temperature, by taking clothes off if need be, but now i accept that i need to dump my hot clothes somewhere before bed.

**Comment by PatrikLundell** [comment]
If taking off your clothes and putting the same set you took off back in in the morning would be enabled by a persistent setting (that can be toggled from the sleep menu if you need to use it in the "other" way I'm perfectly OK with it. It's the additional manual chore I'm against, not the risks of being caught without you pants on (literally) and the time taken.

**Comment by matt32106** [comment]
Brainstorming here: could also be a negative trait "can't fall asleep when encumbered" that would say that you cannot sleep if any body part has encumbrance > 5 or 3 or whatever. Or a positive trait, "can sleep fully armored and packed" if there was some falling asleep penalty if encumbrance > x.

**Comment by fairyarmadillo** [comment]
There's also an existing sleep mode bionic that could allow you to ignore any discomfort, and I can picture post-threah slime mutants not caring since they're basically goop.

**Comment by Zireael07** [comment]
@HenicTheSodgehog Those blisters can get infected in survivor situations, so yep, a good idea for a realistic downside

**Comment by Zireael07** [comment]
Gas mask is also an egregious case of this.

**Comment by anothersimulacrum** [comment]
AFAIK this would only be waiting on automation features as are partially discussed above.
