### ISSUE TITLE
Every item becomes an "item worn" after picking up too many

### ISSUE THREAD

**Issue by ThePainkiller** [CleverRaven/Cataclysm-DDA#58338]
### Describe the bug

When looting a bunch of ammo from a gun store, ammo that no longer fit inside the backpack flowed into the pockets of army pants/leather jacket ~~(not present in the screenshot, I broke it trying to refit it by being hasty)~~ and destroyed my inventory window. Now every item both worn and nested inside a container is unified into just one "items worn" category.

This happened before, on another earlier experimental version of the game (didn't decide to do a bug report back then), but it was easily fixed by dropping and unequipping everything, then (W)earing everything again and picking up other items so that they get properly assigned to my inventory. This time, however, it does not work for me and I'm perpetually stuck with the "items worn" category forever with no apparent way to fix it.

Basically a reproduction of an ages old issue, exact same as #40122 .

### Steps to reproduce

1. Attempt to loot a high amount of ammo/casings/primer or quantitative items (like charcoal) with an almost-full backpack
2. Have the item stacks divided by pockets by virtue of pickup rules
3. Inventory window is now broken and every item shows on a single, unified tab as "Items worn"

### Expected behavior

Items should nest properly inside a container and not unify all of the inventory into just "items worn". I want my inventory separated left and right back to how it always was.

### Screenshots

![image](https://user-images.githubusercontent.com/1294508/173160819-10a936d5-57b9-4099-bfc4-7f64fa95eefc.png)

### Versions and configuration

- **OS:** Windows 10
- **Game Version:** Experimental, build fdf38c4
- **Graphics version:** Tiles (UndeadPeople)
- **Ingame language:** English
- **Mods loaded:** Disable NPC needs, Alternative Map Key, Mythical Martial Arts

**Comment by Terrorforge** [comment]
I'm think you've just accidentally hit ; and toggled inventory categories off. Press it again to fix.

**Comment by ThePainkiller** [comment]
> I'm think you've just accidentally hit ; and toggled inventory categories off. Press it again to fix.

...Turns out this I am really dumb, and for some reason **this** was **exactly** what caused the issue despite me never really pressing the key in the inventory window (This happened right after looting and pressing `i`, I'm sure I didn't touch it, else I'd notice the immediate shift between "items worn" and normal inventory)
...Unless advanced inventory counts since I'm still confusing `;` as a "transfer all" key despite it being `,` whenever I try to rearrange stuff, that's the only time I've ever used `;` as a hotkey. Thank you so much for the quick response!
