### ISSUE TITLE
Animal combat text is bugged.

### ISSUE THREAD

**Issue by Bracket-H** [CleverRaven/Cataclysm-DDA#58340]
### Describe the bug

Animals seem to use a plural to describe actions done to them.

The blabla attacks the animal, they dodge.

### Steps to reproduce

Witness combat among animals.

### Expected behavior

Blabla attacks the animal, it dodges.

### Versions and configuration

game version: 6027e6611d79b2d1cfba3ed5500988e6c5288936

**Comment by Maleclypse** [comment]
Are you suggesting that `attacks` is a pluralized word and not the verb form of attack?  Or am I misunderstanding?

**Comment by Maleclypse** [comment]
Dodges is also in 3rd person present.

**Comment by Qrox** [comment]
The OP probably meant that "they dodge" should be changed to "it dodges".

The "they dodge" text appears in `"miss_msg_npc"` text, so it appears "they" is used as a gender-neutral pronoun which is also incorrectly used for animals. To fix it however would require either adding animal-specific text for each npc text or to rewrite the messages to avoid the pronoun.

**Comment by Maleclypse** [comment]
I completely missed their change. That makes more sense.

**Comment by Bracket-H** [comment]
> The OP probably meant that "they dodge" should be changed to "it dodges".
> 
> The "they dodge" text appears in `"miss_msg_npc"` text, so it appears "they" is used as a gender-neutral pronoun which is also incorrectly used for animals. To fix it however would require either adding animal-specific text for each npc text or to rewrite the messages to avoid the pronoun.

Yeah, that's what I mean, I figured it just used a wrong plural, though.

**Comment by fairyarmadillo** [comment]
The game uses singular they all over the place. It's not an error.

**Comment by Bracket-H** [comment]
> The game uses singular they all over the place. It's not an error. Animals can be tamed and named so it makes sense that they're getting a personal pronoun and not an object pronoun.

That's pretty damn stupid, but okay. I'm just gonna leave this retard shit alone and change this for myself. Cheers.

**Comment by fairyarmadillo** [comment]
I have never seen someone go mask off that fast.

**Comment by Bracket-H** [comment]
> > That's pretty damn stupid, but okay. I'm just gonna leave this retard shit alone and change this for myself. Cheers.
> 
> I have never seen someone go mask off that fast.

The blazes are you talking about now?

**Comment by Zireael07** [comment]
@Bracket-H: The only edit they did is adding a quote.

"They dodge" is not a plural, it's a pronoun. Actually, if I (an English major) would be talking about a dog, if I didn't know the actual physical sex, I'd use 'they' too (to avoid automatically assuming it's male and getting corrected - happened to me many times with not just dogs but also other animals, sometimes it's really hard to tell!)

**Comment by Bracket-H** [comment]
You're trolling me, aren't you?

"I threw the ball at the dog but it dodged my throw."
Is this not English? I'm pretty sure this is perfectly normal valid English and English isn't even my native language.

**Comment by fairyarmadillo** [comment]
OP has a history of bad faith arguments and rudeness in other projects and if it's not clear to anyone reading now, they're currently engaging in some culture war trolling. 

The singular use of they is broadly accepted by most authoritative English references ([Merriam-Webster](https://www.merriam-webster.com/dictionary/they), [OED](https://public.oed.com/blog/a-brief-history-of-singular-they/) but in the last six or so years has been a topic of contention for some on the far right of the American political spectrum who insist it's never existed.

**Comment by Bracket-H** [comment]
> OP has a documented history of bad faith arguments and rudeness in other projects and if it's not clear to anyone reading now, they seem to be engaging in some culture war trolling.
> 
> The singular use of they is broadly accepted by most authoritative English references ([Merriam-Webster](https://www.merriam-webster.com/dictionary/they), [OED](https://public.oed.com/blog/a-brief-history-of-singular-they/) ) but in the last six or so years has been a topic of contention for some far right activists who insist it's never existed.
> 
> Since this isn't really a space for political debate, I suggest we defer to the dictionary.

I'm singular, dude. I came here with a bug report about bad English and was faced with some really dumb shit about gender, masks, and now you bring up politics.

Are you literally, sincerely retarded, or what? What in the truest of all fucks is wrong with you here, delivering such asinine shit?
You talk about bad faith?

I think it's extremely malignant faith to troll people with stupid shit like this.

Actual human English:
"The insect, it is skittering across the flor."
"The insect is small."
See? See how it's consistent and not retarded?

Retard English:
"The insect, they are dodging."
"The insect are small."
See, retarded. 

Now you have to go: "Yeah well, we use they with an action verb like they dodge, which sounds like a plural but really is just some gender thing, but when you are referring to an attribute of it without the pronoun then you use a singular article or whatever it's called, and don't even think about going "The insect, they is dodging' even though it's really a singular insect in this case and well you know, we're just being retards/trolls here while pretending we're a vanguard against ....masked political villains! (or whatever is going on in your heads)"

Anyway, I have long fixed this for myself, hence the issue being closed. You bloody bumboclaats.
