### ISSUE TITLE
Pocket autopickup settings menu exits after setting pocket priority

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#58347]
### Describe the bug

When you put in a number for the priority in the pocket autopickup settings menu, the game quits out of the menu back to standard gameplay.

This started happening when I updated this morning from a version from yesterday. It's presumably related to the implementation of #58116

### Steps to reproduce

1. Assign a priority to a pocket

### Expected behavior

I can adjust multiple pocket parameters of an item without having to enter and leave the menu over and over.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 74ad8be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

### Additional context

e: this happens when you update the priority from the i->i "Organize contents" menu as well

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 74ad8be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mlange-42** [comment]
Can't confirm this. Changing pocket priority does not close the view for me.

Tested in the context of #59514, which fixes a similar issue for the context menu.

* OS: Windows 10
* Game Version: d291072 [64-bit]
* Graphics Version: Tiles
* Game Language: English [en]
* Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
  ]

**Comment by rgehlen** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/58564 probably fixed this

**Comment by dseguin** [comment]
Seems to be resolved :+1:
