### ISSUE TITLE
Error report: Unable to find and assign mission target roadstop_a.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#58349]
### Describe the bug

Returning to a town that's been cleared a long time ago (and possibly not visited with the current experimental) the following error report was received: 
DEBUG    : Unable to find and assign mission target roadstop_a.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 251
 VERSION  : 218edd5

### Steps to reproduce

?

### Expected behavior

No report

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 218edd5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON hack "mod" to disable portal storms as the PR for such a mod was rejected.
+ Manual addition of corn cob -> kernel kitchen expansion recipe addition.
+ possibly workshop recipe addition of welding consumables recipes.

### Additional context

Doesn't seem to have any harmful effect on the game (so far?).

**Comment by andrei8l** [comment]
I'm fairly certain I've fixed this definitively in https://github.com/CleverRaven/Cataclysm-DDA/pull/58112 which was merged after the commit in your build.

Can you provide the save file though?

**Comment by PatrikLundell** [comment]
[](https://www.dropbox.com/s/3h656b47govm2cz/Weippe%20-%20Copy.zip?dl=0)

It seems like this should be a fairly good test case. I copied the save and removed the mm1 folder in it, and when I loaded the original save and tried to move through the door of the vehicle (i.e. south) I received the message again. Repeating the same thing with the copied save gave the same result, so if it doesn't happen with a recent experimental at least this instance ought to be handled.

**Comment by andrei8l** [comment]
Thanks for the save file. I can reproduce it with [this build](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-06-2018) but not with [this build](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-06-2119) (or newer) that includes the patch above

**Comment by PatrikLundell** [comment]
Has been fixed by #58112.
