### ISSUE TITLE
Rebalance bullets per stack of ammo.

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#5834]
Is there are particular reason why, for example, 7.62x39mm rounds are four times more numerous per-stack than 7.62x51mm/.308 Winchester, and twice more per-stack than 5.56 NATO/.223 Remington? Or why .50 BMG comes in stacks of 30?

I really feel like 7.62 Russian is overpowered simply because there's *so much* of it. While mechanically 7.62 NATO and 5.56 have better performance, damage/range performance isn't what makes bullets good in CDDA - it's how much you have, and how much you can afford to waste on things. And you can afford to waste four times as much 7.62 Russian than 7.62 NATO, or twice more than 5.56.

In my experience, 7.62 Russian kills things dead just as good as the other two; you have a hard floor on just how good a bullet is, and that floor is "kills thing in 1 shot". In fact, in this specific example, 7.62 Russian could be four times worse at killing compared to 7.62 NATO, and you'd still break even.

And yes, 7.62 and 5.56 NATO have better range, but again, in my experience, most engagements are happening at <30 tiles.

Hell, if someone ever decides to implement an LMG that fires 7.62 Russian (e.g the RPK), and can be mounted as a turret, expect to never see M249s used ever again.

If only there were a way to vary the number of bullets (in a stack) per spawn - then you could have things like a box of bullets (so there's your 80 7.62 Russian, although judging from a quick look at Google, 7.62 Russian is more likely to spawn in boxes of 1000 than it is in boxes of 80), a belt (200 5.56 NATO for that M249!) plus different "magazine"-sized spawns (e.g. a 30-round spawn of 7.62 Russian for AK-47s, a 10-round "stripper clip" spawn of it for the SKS), and even loose single cartridges.

**Comment by illi-kun** [comment]
@mugling I'm not sure but maybe your latest changes of ammo related code & json definitions of ammo somehow affect this issue? Is this issue outdated?

**Comment by mugling** [comment]
Yes, it can be closed now
