### ISSUE TITLE
Speedloaders doesn't work correctly with magazines

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#58359]
### Is your feature request related to a problem? Please describe.

Right now speedloader designed to work with mags, that has the same amount of ammo as speedloader itself (ie 6 round .44 revolver speedloader can be used only on empty .44 revlolver with 6 rounds (for example, Ruger Redhawk)).
The #58016 will introduce the ar-15 compatible stripper clips, that works different - instead of loading the whole mag, they designed to load only 10 rounds at once, and this is where the problem occur - the game dont allow to load the gun, if its not empty, it just says "you don't have any ammo!"

### Solution you would like.

I think about the flag, that will allow to reload things even if the mag is not emply - lack of this flag would be used for something like revolver speedloaders, when using allow to use shotgun speedloaders and stripper clips

### Additional context

This issue block the release of #58016

in some reason i was not able to use shotgun speedloader at all. Not sure is it the issue or im just doing something wrong

**Comment by catdach** [comment]
Shotgun speedloaders, and specifically the shotgun speedloader chute, have been broken for a while. #52595
