### ISSUE TITLE
Doing next to no damage when attacking

### ISSUE THREAD

**Issue by LordKaaven** [CleverRaven/Cataclysm-DDA#58366]
### Describe the bug

After an experimental update between yesterday and today, my characters started doing next to no damage.

Saved game yesterday, with a character with combat skills at around 2-3 (see screenshots), being able to fight single basic zombies relatively easy. After updating today (several times throughout the day) my char does next to no damage. Tried 2 different weapons (machete and naginata) both direct attack and reach attack and the damage is so low it most of the time fails to hurt even most basic enemies.

### Steps to reproduce

Loaded earlier save
Tried to play like before
Attacked a zed
Died, due to not doing damage

### Expected behavior

Should be able to reliably damage a single zombie with machete and combat skills of 2-3.

### Screenshots

![NoDamage](https://user-images.githubusercontent.com/66031499/173211519-9a16b50a-48ee-4278-9f22-c0adac8b78f9.png)

![NoDamage2](https://user-images.githubusercontent.com/66031499/173211524-a794d273-4a9c-40d2-ba42-70099b32ad5b.png)

### Versions and configuration

- Win 7
- Version: cf8caa8 (and few earlier)
- Mods: No Fungal Growth, Disable NPC needs, No rail stations, Blaze Industries

**Comment by sonphantrung** [comment]
Hence why I died fighting vs. cunning feral while wielding a fire axe in the Aircraft Carrier!

**Comment by sonphantrung** [comment]
Based on what I can tell, It seem to be cutting-specific

**Comment by dseguin** [comment]
> Based on what I can tell, It seem to be cutting-specific

Doesn't seem to be specific to cutting damage, it's actually related to #57972.

Thankfully it looks like a one line fix:

```diff
diff --git a/src/melee.cpp b/src/melee.cpp
index cbc44da1ec..71d51e17e4 100644
--- a/src/melee.cpp
+++ b/src/melee.cpp
@@ -711,7 +711,7 @@ bool Character::melee_attack_abstract( Creature &t, bool allow_special,
 
         // Failsafe for tec_none
         if( technique_id == tec_none ) {
-            attack_vector = "HANDS";
+            attack_vector = cur_weapon->is_null() ? "HANDS" : "WEAPON";
         } else {
             attack_vector = martial_arts_data->get_valid_attack_vector( *this,
                             technique_id.obj().attack_vectors );
```

**Comment by sonphantrung** [comment]
Oh, so the player actually punched at the zombie instead of swinging!

**Comment by hexagonrecursion** [comment]
/confirmed by using machete on a fat zombie

- OS: Linux
    - OS Version: <unknown>
- Game Version: c15589a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
