### ISSUE TITLE
Recharging station and battery charger appliances aren't working

### ISSUE THREAD

**Issue by Endertron51** [CleverRaven/Cataclysm-DDA#58365]
### Describe the bug

The appliances recharging station and battery charger aren't receiving energy from storage batteries connected, when turned on they don't recharge the batteries inside them. They only seem to work when receiving direct power from a energy generator like a solar panel

### Steps to reproduce

1. Place any sized storage battery with energy
2. Place the recharging station or the battery charger nearby
3. Plug the recharging station/battery charger to the battery
4. Place empty batteries inside the appliance
5. Turn the appliance on

### Expected behavior

These appliances should constantly pull energy from the storage batteries connected to them, other possible solution is pulling energy only when turned on, I'm no programmer so I can't imagine what is easier/possible/less laggy

### Versions and configuration

- OS: Windows 7
- Game Version: d69f563 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I tried to connect with jumper cables and cords, didn't work too

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: c15589a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
