### ISSUE TITLE
zh_CN lang is broken in 58343

### ISSUE THREAD

**Issue by tim110011** [CleverRaven/Cataclysm-DDA#58360]
### Describe the bug

Translate  is broken.

### Steps to reproduce

Run the game.

### Expected behavior

Translate is not broken.

### Versions and configuration

https://github.com/CleverRaven/Cataclysm-DDA/pull/58343

**Comment by NetSysFire** [comment]
"Broken" in what way? We need more info than that.

**Comment by yetaGitacc** [comment]
> "Broken" in what way? We need more info than that.

Most texts fallback to english, very few places indicate it's in zh_CN ( including tips and logo ASCII art )
Occurs in zh_CN only, though zh_TW works normally.

**Comment by NetSysFire** [comment]
@BrettDong, could you take a look at that please?

**Comment by ZeroInternalReflection** [comment]
I can confirm that something's gone wrong.  A significant amount of text that was previously translated is now in English.

Images from a build 2022-06-04:
<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 5f229e6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

![Screenshot from 2022-06-11 18-17-43](https://user-images.githubusercontent.com/89038572/173206721-c870b6bc-f8ee-48fc-9e07-a3f83f1e83a0.png)
![Screenshot from 2022-06-11 18-18-08](https://user-images.githubusercontent.com/89038572/173206741-b6acf94f-b486-45b0-921f-7c947061449b.png)

Compared to images from a build downloaded just now:
<details><summary>Version</summary>

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 51e8603 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
</details>

![Screenshot from 2022-06-11 18-17-46](https://user-images.githubusercontent.com/89038572/173206732-9d146688-3f64-4cbd-861a-a0c6476c9e22.png)
![Screenshot from 2022-06-11 18-18-09](https://user-images.githubusercontent.com/89038572/173206743-e3b163cf-c636-46c4-9682-229b8f51d9ff.png)

**Comment by ZhilkinSerg** [comment]
Yeah, -77k lines diff is rather strange for translations:

![image](https://user-images.githubusercontent.com/16213433/173216847-c78fe7e7-e0f0-496f-8c62-61e16c7e8698.png)

**Comment by BrettDong** [comment]
This is probably a bug in Transifex's CLI or API. The content of `lang/po/zh_CN.po` is incomplete, but Transifex CLI reported that the download was successful (https://github.com/CleverRaven/Cataclysm-DDA/runs/6840324270):

>  SUCCESS Translation file 'lang/po/zh_CN.po' downloaded

**Comment by H4M5TER** [comment]
build 0615 reproduced
anybody knows the latest build without this issue?
