### ISSUE TITLE
Wrong graphics on motor boats

### ISSUE THREAD

**Issue by cherdaq** [CleverRaven/Cataclysm-DDA#58389]
### Describe the bug

Motor boats show graphics of log wall for their frame/hull on Ultica tileset.

### Steps to reproduce

Find yourself a motor boat in a island prison-B scenario, for example, or just spawn it.

### Expected behavior

Motor boats don't look like they're made of logs.

### Screenshots

Encountered on a regular playthrough, with a few balancing mods.
![image](https://user-images.githubusercontent.com/93034036/173258648-006f1344-ea69-45ed-aa1c-2efea62814e9.png)

Same problem on a mod-clean world.
![image](https://user-images.githubusercontent.com/93034036/173258659-f70bb24e-e519-4008-9e41-42a7aaf59c33.png)
Also if spawned.
![image](https://user-images.githubusercontent.com/93034036/173258663-72dc982f-69ef-4734-a574-e9aadaeeb1e3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: ab8c2ff [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык [] (Russian)
- Mods loaded: [
    Тёмные Дни Впереди [dda]
]

**Comment by mkrutov** [comment]
Can confirm, crafted a boat today and had same thing.

**Comment by Rygalenko** [comment]
Yup, it seems to happen with **all** the boats, now that I've looked more into it.

**Comment by mkrutov** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/e1880370d3744fa4236945a5e1ecfe996e80e267/data/json/vehicleparts/vehicle_parts.json#L1052

yeah, someone with graphics skills might want to draw something which would resemble a boat hull instead of a log wall. ;)

**Comment by Rygalenko** [comment]
Lmao
There was a different tile used for it before, I can clearly remember that

**Comment by Calavera20012** [comment]
noted, will work on graphics for them in Ultica (and Chibi) throughout this week
