### ISSUE TITLE
Big fuel loss after "fake parts update"

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#58385]
### Describe the bug

After this update https://github.com/CleverRaven/Cataclysm-DDA/pull/56143
[Cataclysm-DDA experimental build 2022-06-08-2059](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-2059)
The fuel consumption of cars has been greatly increased

### Steps to reproduce

I tested it on grass, not on the road, but situation is the same
1) Load update which comes before "Fake parts for filling vehicle gaps"
[Cataclysm-DDA experimental build 2022-06-08-1950](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-1950)
2) Spawn car. I tested it on "Flatbed truck" and "Cargo van"
3) Speed up to 25 km/h
4) Check fuel consumption
5) Load "Fake parts for filling vehicle gaps" update 
[Cataclysm-DDA experimental build 2022-06-08-2059](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-2059)
6) Spawn "Flatbed truck" and "Cargo van"
7) Speed up to 25 km/h
8) Check fuel consumption

### Expected behavior

Normal fuel comsuption. I think, fake part logick doubles weight or something like this, but on screenshots you can see, weight stays the same before and after "fake part" update

### Screenshots

Check fuel consumption on the screenshots

<details>

![11](https://user-images.githubusercontent.com/102726167/173247875-770a21bd-589e-408c-84b9-89103bc3224b.png)
![33](https://user-images.githubusercontent.com/102726167/173247876-173cb78e-6a91-4b07-90fd-fab8b088bf19.png)

<summary> "Flatbed truck" before and after "fake part update" </summary>
</details>

<details>

![22](https://user-images.githubusercontent.com/102726167/173248035-9e744890-c882-4c93-9551-7222b7cb4148.png)
![44](https://user-images.githubusercontent.com/102726167/173248041-42d7d593-bae5-48c5-86e3-fbb4317a31e7.png)

<summary> "Cargo van" before and after "fake part update" </summary>
</details>

<details>

![55](https://user-images.githubusercontent.com/102726167/173248109-f61d6d3d-8c7a-4c36-988b-579010f484e3.png)

<summary> Tested place </summary>
</details>

### Versions and configuration

<details>

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 2ec0e5e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

<summary> Cataclysm-DDA experimental build 2022-06-08-1950 version and configuration </summary>
</details>

<details>

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: befb7ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

<summary> Cataclysm-DDA experimental build 2022-06-08-2059 version and configuration </summary>
</details>

**Comment by KHeket** [comment]
I have also tested it on the last update [Cataclysm-DDA experimental build 2022-06-12-1440](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-12-1440), and the problem stays the same

**Comment by ZhilkinSerg** [comment]
There are vehicle efficiency tests in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tests/vehicle_efficiency_test.cpp, they haven't been changed in https://github.com/CleverRaven/Cataclysm-DDA/pull/56143, but are still passing.

**Comment by Inglonias** [comment]
The "estimated time until empty" display is not a very good predictor, and can change depending on how long you've been driving on grass. It's possible something is off about the display, rather than actual efficiency.

**Comment by Terrorforge** [comment]
Yeah, in my experience that fuel consumption number is just utter nonsense. I mean, at 0.2%, that van would be consuming about 0.25L of gas per hour, and I don't think even motorcycles get that kind of efficiency in practice.

**Comment by KHeket** [comment]
> Yeah, in my experience that fuel consumption number is just utter nonsense. I mean, at 0.2%, that van would be consuming about 0.25L of gas per hour, and I don't think even motorcycles get that kind of efficiency in practice.

I think it is +- normal gas consumption on 25 km/h, if you look at the analogue in reality

**Comment by Terrorforge** [comment]
If you say so, but I'm not talking about reality. I'm saying that the number displayed in the vehicle UI doesn't match how much fuel that vehicle actually consumes when you're driving it in the game.
