### ISSUE TITLE
Improve "sort out my loot"-messages

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#58384]
### Is your feature request related to a problem? Please describe.

<s>I just found out that the "sort out my loot"-function now (?) works across levels, which is fantastic of course, especially for looting labs. I noticed this because the stuff was not sorted into the nearby zone, so seemingly "disappeared", and only when I disabled all other zones on higher levels, the stuff got sorted into the zone I expected it to.</s>

The messages in the log did not help with figuring out where the stuff was moved to at all:
**"You drop your (item name) on the (tile name)"**

### Solution you would like.

Change the messages for stuff moved by the "sort out my loot"-function to **"You move (item name) to (zone name)"**. Provided the zones are properly named, it should be much easier to figure out from the log where the stuff was moved to.

**Comment by BaumgeistOne** [comment]
Well, it turns out I should have checked where the stuff was sorted to, because I missed a zone on the same level. So maybe sorting does not work across levels? I do not know.

This only works to reinforce my point though - the messages should tell the player to which zone the stuff is sorted to.

**Comment by PatrikLundell** [comment]
Sorting does not support multiple levels.

**Comment by BaumgeistOne** [comment]
Good to know. :)

Would be a cool feature though.
