### ISSUE TITLE
Wearing Armors which are able to block then wielding a weapon which could also do so results in never being able to block anything

### ISSUE THREAD

**Issue by WreckingAbandon** [CleverRaven/Cataclysm-DDA#58383]
### Describe the bug

I'm wearing a pair of scrap arm guards and wielding a wooden tonfa when I noticed that I am never blocking anything anymore. I'm currently playing an OP character at the moment, so blocking triggers a lot of the time when I was only wielding a tonfa, but when I wore the scrap guards somehow I never block anything anymore. I then remove the said armor which returned my ability to block.

However, when fighting unarmed with the scrap guards on, I could block with them just fine.

### Steps to reproduce

1. Play a character, an OP one in my case.
2. Debug in any armor that has the ability to block attacks, along with a weapon that can also do so, and use them both.
3. Look for a fight, the ones not involving guns or some such.
4. Stand around and notice you could never block anything with the scrap guards on.
5. Remove them, then notice you can block again.
6. EDIT: Another thing, martial arts with no limb blocking capacity are the only thing affected.

### Expected behavior

I expect any armor with the ability to block attacks to do so, with or without a weapon.

### Versions and configuration
-----------------------------------------
19:32:54.336 : Starting log.
19:32:54.336 INFO : Cataclysm DDA version 5f229e6
19:32:54.338 INFO : [main] C locale set to C.UTF-8
19:32:54.338 INFO : [main] C++ locale set to 
19:32:54.338 INFO : SDL version used during compile is 2.0.12
19:32:54.338 INFO : SDL version used during linking and in runtime is 2.0.12
19:32:54.579 INFO : [options] C locale set to C.UTF-8
19:32:54.579 INFO : [options] C++ locale set to 
19:32:54.579 INFO : Read Android system language: 'en_GB'
19:32:54.579 INFO : Setting language to: 'en'
19:32:54.579 INFO : [i18n] Scanning core translations from /storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/lang/mo/
19:32:54.579 INFO : [i18n] Scanning mod translations from /storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/
19:32:54.579 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/] failed with "No such file or directory".
19:32:54.584 INFO : Read Android system language: 'en_GB'
19:32:55.165 ERROR SDL : (error message will follow backtrace)#01: 0x71ae8f4dec DebugLog(DebugLevel, DebugClass)
#02: 0x71af3ccb18 printErrorIf(bool, char const*)
#03: 0x71af3ca4c8 gamepad::init()
#04: 0x71af3dddb0 catacurses::init_interface()
#05: 0x71aedce1f8 SDL_main
#06: 0x71b08cd5f0 Java_org_libsdl_app_SDLActivity_nativeRunMain
Backtrace emission took 0 seconds.
(continued from above) ERROR : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/sdl_wrappers.cpp:26: SDL_GameControllerOpen failed: Couldn't find mapping for device (0)
19:32:55.241 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
19:32:59.990 INFO : Read Android system language: 'en_GB'
19:32:59.990 INFO : Setting language to: 'en'
19:32:59.990 INFO : Read Android system language: 'en_GB'
19:33:00.692 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/] failed with "No such file or directory".
19:33:01.061 INFO : Read Android system language: 'en_GB'
19:33:01.099 INFO : Read Android system language: 'en_GB'
19:33:01.100 INFO : Read Android system language: 'en_GB'
19:33:01.101 INFO : Read Android system language: 'en_GB'
19:33:16.799 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/save/Test World/mods] failed with "No such file or directory".
19:33:17.872 INFO : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/mod_tracker.h:64: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'overmap_special' does not track object sources
19:33:41.064 ERROR SDL : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/cata_tiles.cpp:734: tile overlay_wielded_mosin91_30_ebr has no (valid) foreground nor background
19:33:41.068 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
19:33:41.068 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE

### Additional context

This doesn't throw off an error, so I couldn't paste anything in the Versions and Configurations. 

EDIT: Also, after trying out other martial arts it seems that this only affects martial arts that doesn't have any limb blocking capacity.

**Comment by WreckingAbandon** [comment]
I pasted the one I have in the debug.log, though I used a new game which only has the basic mods enabled to see if it is somehow caused by other mods. I edited the description based on what I found, but it seems like this only happens when the martial art doesn't have limb blocking abilities.

Also, does it mean that I will always block when a dodge doesn't happen regardless of anything?

**Comment by Broken27** [comment]
>Also, does it mean that I will always block when a dodge doesn't happen regardless of anything?

Yes, unless you have used all your block attempts of the turn.

**Comment by Terrorforge** [comment]
Yep. Basically, you add together your Strength, Melee (or Unarmed if applicable) and a bonus for your blocking tool. Iirc it's 2 for bracers, 4 for weapons with the "Block" technique and 6 for weapons with "Parry". If that number is 40 or higher, you just flat out do not take damage. Below that it's a percentage reduction determined by a logarithmic curve, so it's not as simple as taking 50% damage when the total is 20, but it's something like that.

I'd honestly kind of forgot about blocking. I've been a little concerned about the fact that it's kind of hard to get reliable bash armor now, but if your block total is in like the 20-30 range it should reduce most attacks enough for even quite light armor to soak the rest, and thus my love of the trench knife is once again vindicated.

**Comment by WreckingAbandon** [comment]
So what is the difference between the block and block-effectiveness stat in martial arts? I tried to search it in the forums, even asked about it there, but no provided me with an answer.

**Comment by Terrorforge** [comment]
Block Effectiveness adds to the Strength + Melee number I was talking about
Block: +X% of [stat] is a flat damage reduction added on top of that. I believe it applies before the percentage reduction.

**Comment by Terrorforge** [comment]
/confirmed on current experimental. If I put on steel arm guards or scrap arm guards while wielding a quarterstaff, I stop blocking. I thought it might be strictly a visual bug where the messages don't show up, but after debugging my Strength to 50 so I would block all damage, I did block all damage with the staff, but started taking damage when I put on the arm guards.

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: f6be61e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by WreckingAbandon** [comment]
Is it intended to not be able to block while wielding a firearm? I understand if the gun itself is used to block, but an armour part should be allowed to block an attack. Maybe its unrelated to this one, or its just intended.
