### ISSUE TITLE
Construction-menu buildable "Control panel"/"switch"

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#58388]
### Is your feature request related to a problem? Please describe.

I wanted to create a lightswitch to control floodlights outside of my compound, and I couldn't.

### Solution you would like.

Being able to construct a control panel of some kind, which can control other constructed devices connected over wires.

### Describe alternatives you have considered.

This isn't so much alternatives as it is various implementations:

- Either needing a specific type of item/wire for controlling objects, or else allowing control just through the normal power cords that connect constructions. The latter might make sense for simple electric devices like lights, but sending actual commands might need more complicated circuitry and/or electrical/computer skill in construction.
- Either controlling anything connected to the network, or requiring the control panel/switches to be connected directly to a specific object that it controls. If the latter, I would suggest allowing one control panel to be connected to multiple different objects (maybe up to a limit), as taking up an entire second worldtile for allowing remote control of a single object (which could be as simple as a lamp) seems a bit much.
- If there is such a limit, perhaps allow "complicated control panel" item/construction, to represent something more like a pilots cockpit control panel instead of a simple control board.
- Perhaps such a control panel or switch can be built into (some types of) walls, rather than need to be built free-standing.

### Additional context

It's currently possible to construct a Vehicle floodlight (not the Standing Floodlight) and use a remote control device, drive-by-wire, and electronic control units to remotely activate the light. That seems a bit above-and-beyond what should be required for actually activating other objects that are connected by wires.

**Comment by PatrikLundell** [comment]
I think there's a need for a dedicated control appliance, because the vehicle functionality requires both a control panel AND a dashboard to work, and we'd need something that provides both control and feedback in a single tile. Such a control ought to allow control over everything connected to the same appliance network, but may have to rely on the player naming appliances for them to be distinguished by the control. Allowing wall fitting of the control would be useful.
