### ISSUE TITLE
tried to collet acid on the spitter zombie corpse but instead have tainted blood.

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#58395]
### Describe the bug

I tried to dry out the corpse on the spitter zombie for the acid in order to recharge my batterys, only to found out there's only tainted blood instead of Acid Blood...

### Steps to reproduce

1. Spawn spitter zombie
2.Use debug kill the spitter
3.Wait till the Acid on the floor are gone
4.Opening butcher menu, select bleed corpse
5.Getting 25 Units tainted blood from the corpse

### Expected behavior

Since the spitter already mutate the acid all over the body, the tainted blood are not suppose to collected,
mabye same thing also happen to other acid zombies too?

### Versions and configuration

tiles, 0.F-3

**Comment by PatrikLundell** [comment]
It's beside the point of the issue, but you can use the '/' menu to move the corpse to a tile without acid so you can dismember it safely (or "butcher" it in other ways).
