### ISSUE TITLE
Melee weapon seems to do too much damage

### ISSUE THREAD

**Issue by Tr-T** [CleverRaven/Cataclysm-DDA#58399]
### Describe the bug

After updating to the most recent experimental my pipe spear does more damage than it ever did before, or should be doing. Havent tested other melee weapons.

### Steps to reproduce

1. Equip pipe spear.
2. Hit a zombie
3. Do damage that goes beyond the average melee damage predicted by the game. I did up to 44 on regular hits and 67 on crit. The highest crit is visible in screenshot's feed, along with a 43 regular hit. My melee skill was 4, piercing 4, bashing 3

### Expected behavior

Not one tapping zombies with a pipe spear.

### Screenshots

![CDD](https://user-images.githubusercontent.com/52385475/173369390-9cade7f1-1389-4f39-af9c-c42a95fe5a8d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 3396a32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key]
]

**Comment by Inglonias** [comment]
#58373 fixed a bug relating to melee attacks recently. If you started playing while that bug was still open, that would explain the damage boost.

The numbers you gave seem reasonable for the weapon you're using at the skill levels you have.

**Comment by Tr-T** [comment]
My save predated the bug, but I did experience it and subsequently waited for a patch. Started again today and the damage numbers seemed higher than before the bug. Then again, maybe it's pure psychology on my part. Out of curiosity, how do the damage calculations come up with the final number, exactly?

**Comment by toweroglass** [comment]
29 pierce and 6 bash = 35 damage and your melee skills are decent I think the damage you are doing is reasonable.

**Comment by Inglonias** [comment]
Thing is that we have [automated DPS tests](https://github.com/CleverRaven/Cataclysm-DDA/blob/f97c81efdae5bfae202d93e24bd77525552df3e3/tests/effective_dps_test.cpp) that should catch something like this. If this were a problem, I would expect those tests to start failing.

**Comment by TheShadowFerret** [comment]
![image](https://user-images.githubusercontent.com/99621099/173404887-123fd5b8-6422-4d98-92f8-f80733b9e9d6.png)
Average melee damage of 42 and on crit of 59 + that hit was in the head(x1.1 crit multiplier = 64.9)

I don't see a bug here. Enjoy your powa 🎉

**Comment by Tr-T** [comment]
That makes sense. I guess I've gotten too used to games providing minimum to maximum damage values rather than giving the average.
