### ISSUE TITLE
Implement Battery Charger appliance

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#58390]
### Is your feature request related to a problem? Please describe.

After coming back from a hiatus, I've found it's suddenly much easier to set up a small, stationary electrical grid than constructing a monstrous Deathmobile. Which is a positive change, but there's a notable exception: charging batteries.

There exists a foot locker recharging station, but it needs to be crafted with a recharging station at a component, at which point it's easier to just install it in a vehicle. You almost certainly had to pull it out of one, anyway.

### Solution you would like.

Let us place the "battery charger" item as an appliance. The item description suggests it is in fact a regular wall-socket battery charger that has to be modified and "wired into" a vehicle to work that way, as does the fact it's usually just sitting in someone's kitchen drawer. We should be able to just plug it into the electrical network. Give it a small storage capacity if the slow charge speed isn't enough.

**Comment by Rygalenko** [comment]
Isn't it an appliance already? I mean, not the same as the vehicle-mounted version but still...
![image](https://user-images.githubusercontent.com/93034036/173259068-2328f2b5-bbf0-4e51-bb6f-63f9a15f6170.png)

**Comment by descan** [comment]
The battery charger can be turned into a "box battery charger," which can be constructed as you are suggesting here.
![image](https://user-images.githubusercontent.com/4212389/173259233-9fb5e83e-305f-4bb4-9109-6069163d047e.png)
![image](https://user-images.githubusercontent.com/4212389/173259243-e27e54d2-1424-4dbd-a88f-1b716c69ecf3.png)

**Comment by Rygalenko** [comment]
> The battery charger can be turned into a "box battery charger," which can be constructed as you are suggesting here.

> There exists a foot locker recharging station, but it needs to be crafted with a recharging station at a component, at which point it's easier to just install it in a vehicle.
Well, he did mentioned it...

**Comment by descan** [comment]
That's a different object, which (as he said) requires a "recharging station," not the "battery charger" that the recipe I showed here indicates.

**Comment by Rygalenko** [comment]
Oh, my bad, must've missed this line.

**Comment by Terrorforge** [comment]
Oh, I thought that was a different thing for regular vehicles. The shared code is making it a bit hard to part which is which.

It also doesn't quite do what I want, because this is something you need to craft. Like, you have to solder. You don't need Electronics skill to plug in a fridge, so why on earth do you need it for the battery charger?

Which I guess means the real question is: what the hell is the "battery charger" item supposed to be, anyway? I always assumed it was a normal charger you stuck in an outlet and the "needs a box" thing was just a technical limitation because the batteries have to go somewhere in the car, but this recipe implies you have to... wire it into the box, somehow? And it just like wirelessly transfers power into batteries that happen to be in the box? Feels like it was implemented purely on the basis of matching the way it works in vehicles without considering what this object is actually supposed to be and do.

**Comment by dfrison01** [comment]
Just like @Terrorforge said, I also thought the "battery charger" was a wall-socket-thingy, a "charging brick" used on cellphones or rechargeable batteries, or something like that (as the name implies).
Is this intended to represent a battery charger's CIRCUIT? If that's the case, then maybe the word "circuit" should be added to the end of the item's name, and let be created a proper "phone/wall charger" of sorts.
Makes sense?
