### ISSUE TITLE
Should the extended toolset receive some of the newer qualities? 

### ISSUE THREAD

**Issue by Wyrdean** [CleverRaven/Cataclysm-DDA#58397]
### Is your feature request related to a problem? Please describe.

Should the extended toolset receive some of the newer qualities? 
As an example, should it receive fabric cutting? Filing? Drilling? Wood chiseling? 

List of qualities it has for reference: 
Has level 1 [wood sawing](https://nornagon.github.io/cdda-guide/#/tool_quality/SAW_W) quality.
Has level 1 [metal sawing](https://nornagon.github.io/cdda-guide/#/tool_quality/SAW_M) quality.
Has level 1 [fine metal sawing](https://nornagon.github.io/cdda-guide/#/tool_quality/SAW_M_FINE) quality.
Has level 1 [bolt turning](https://nornagon.github.io/cdda-guide/#/tool_quality/WRENCH) quality.
Has level 1 [fine bolt turning](https://nornagon.github.io/cdda-guide/#/tool_quality/WRENCH_FINE) quality.
Has level 1 [screw driving](https://nornagon.github.io/cdda-guide/#/tool_quality/SCREW) quality.
Has level 1 [fine screw driving](https://nornagon.github.io/cdda-guide/#/tool_quality/SCREW_FINE) quality.
Has level 2 [cutting](https://nornagon.github.io/cdda-guide/#/tool_quality/CUT) quality.
Has level 1 [prying](https://nornagon.github.io/cdda-guide/#/tool_quality/PRY) quality.
Has level 1 [nail prying](https://nornagon.github.io/cdda-guide/#/tool_quality/PRYING_NAIL) quality.
Has level -55 [butchering](https://nornagon.github.io/cdda-guide/#/tool_quality/BUTCHER) quality.

List of qualites present in the game for reference (Minus ones that make no sense or that it already has):
[awl](https://nornagon.github.io/cdda-guide/#/tool_quality/LEATHER_AWL)
[bullet pulling](https://nornagon.github.io/cdda-guide/#/tool_quality/PULL)
[chiseling](https://nornagon.github.io/cdda-guide/#/tool_quality/CHISEL)
[curved needle](https://nornagon.github.io/cdda-guide/#/tool_quality/SEW_CURVED)
[digging](https://nornagon.github.io/cdda-guide/#/tool_quality/DIG)
[drilling](https://nornagon.github.io/cdda-guide/#/tool_quality/DRILL)
[fabric cutting](https://nornagon.github.io/cdda-guide/#/tool_quality/FABRIC_CUT)
[filing](https://nornagon.github.io/cdda-guide/#/tool_quality/FILE)
[fine cutting](https://nornagon.github.io/cdda-guide/#/tool_quality/CUT_FINE)
[fine grinding](https://nornagon.github.io/cdda-guide/#/tool_quality/FINE_GRIND)
[fine hammering](https://nornagon.github.io/cdda-guide/#/tool_quality/HAMMER_FINE)
[grass cutting](https://nornagon.github.io/cdda-guide/#/tool_quality/GRASS_CUT)
[grinding](https://nornagon.github.io/cdda-guide/#/tool_quality/GRIND)
[hammering](https://nornagon.github.io/cdda-guide/#/tool_quality/HAMMER)
[knitting](https://nornagon.github.io/cdda-guide/#/tool_quality/KNIT)
[pencil](https://nornagon.github.io/cdda-guide/#/tool_quality/WRITE)
[punch](https://nornagon.github.io/cdda-guide/#/tool_quality/PUNCH)
[reaming](https://nornagon.github.io/cdda-guide/#/tool_quality/REAM)
[rock drilling](https://nornagon.github.io/cdda-guide/#/tool_quality/DRILL_ROCK)
[sewing](https://nornagon.github.io/cdda-guide/#/tool_quality/SEW)
[shearing](https://nornagon.github.io/cdda-guide/#/tool_quality/SHEAR)
[smoothing](https://nornagon.github.io/cdda-guide/#/tool_quality/SMOOTH)
[soft hammering](https://nornagon.github.io/cdda-guide/#/tool_quality/HAMMER_SOFT)
[welding](https://nornagon.github.io/cdda-guide/#/tool_quality/WELD)
[wood chiseling](https://nornagon.github.io/cdda-guide/#/tool_quality/CHISEL_WOOD)

### Solution you would like.

I believe the toolset could fit several of the newer qualities without stretching the imagination.

**Comment by Wyrdean** [comment]
I wasn't too harsh when removing ones that wouldn't make sense, as for some of them I could see arguments that'd allow them, but the ones in particular I was thinking of were the ones I mentioned, namely: fabric cutting, filing, drilling and wood chiseling which I personally think have reasonable possibility of being kept in a bionic multitool. Fabric cutting is an easy explanation, a pair of scissors kept in a finger or the forearm. Files are small and can easily be on the side of another tool. Drilling would be limited, but a small power drill could definitely be hidden within the tip of ones finger. Wood chiseling is probably the farthest stretch, but a chisel isn't a complex tool and could reasonably fit within ones hand if you take off the handle.

**Comment by toweroglass** [comment]
i think drilling 1 is the only thing I would agree with adding. if your finger/hand can do some simple screw driving some simple drilling doesn't seem like a stretch.

**Comment by Griffinhart** [comment]
`filing` might make sense; my IRL [Leatherman Wave+](https://www.leatherman.com/wave-10.html) multitool (which is small enough to fit in a pocket) has two different filing faces (one for wood/metal and one that's diamond-coated).

**Comment by a-chancey** [comment]
Fabric Cutting 1 makes sense, as it's more implied to be something like scissors. Fabric Cutting 2 is more a specialized cutting tool - shears, rotary cutters, things of that nature for specialized fabrics

**Comment by Xpyder** [comment]
I've always felt like the Extended Toolset was too much of an omni tool, I've thought it might be better if there were versions specialized for specific crafting like a Mechanics toolset, Carpenter's toolset, Welder's toolset, Electronics toolset, etc.  This would indirectly increase your chances of finding one by adding more to the loot tables (and possibly allowing us to add custom versions as rare drops in appropriate places like mechanic's shops) while making it less overpowering as the Ultimate Omni Tool.

That would probably be a larger project though
