### ISSUE TITLE
Crafting `Heated Tank` with a 60L metal tank filled with water consumes the component but cannot proceed

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#58408]
### Describe the bug

Attempting to craft a `heated tank` and using a `metal tank (60L)` that is (partially) filled with `water (frozen)` goes through all the normal crafting steps (selecting components, etc.) including the "metal tank (60L) > water (frozen)  is not empty. Continue anyway?" dialog and creates the in-progress crafting item, but the craft is immediately interrupted (progress 0%) due to missing component.

Attempting to `a`ctivate the component gives the message `You don't have the required components to continue crafting! These components are missing:  metal tank (60L)`.

NB: crafting was attempted while standing inside a vehicle, adjacent to a workbench. Tank was pulled off of the vehicle.

### Steps to reproduce

1. Fill a `metal tank (60L)` with water (unsure if a specific amount is required - bug occurred with 95 units). Make sure this is the only `metal tank (60L)` in the area.
2. Freeze the water in the tank.
3. (Optional) Install tank into vehicle.
4. (Optional, only if 3 was done) Uninstall tank from vehicle.
5. Craft a `heated tank`.

### Expected behavior

Either a `heated tank` object is created, or the crafting is blocked (e.g. until an empty `metal tank (60L)` is provided).

### Versions and configuration

- OS: Windows 10 Pro x64
- Game Version: `781a1fc`, `cdda-windows-tiles-x64-2022-06-12-1440`
- Tiles, but not using any tiles
- Ingame language: English
- Mods loaded: [
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "package_bionic_professions",
  "blazeindustries",
  "magiclysm",
  "alt_map_key",
  "MMA",
  "crazy_cataclysm"
]

**Comment by Nagyonkrisztina** [comment]
> ### Describe the bug
> 
> Attempting to craft a `heated tank` and using a `metal tank (60L)` that is (partially) filled with `water (frozen)` goes through all the normal crafting steps (selecting components, etc.) including the "metal tank (60L) > water (frozen)  is not empty. Continue anyway?" dialog and creates the in-progress crafting item, but the craft is immediately interrupted (progress 0%) due to missing component.
> 
> Attempting to `a`ctivate the component gives the message `You don't have the required components to continue crafting! These components are missing:  metal tank (60L)`.
> 
> NB: crafting was attempted while standing inside a vehicle, adjacent to a workbench. Tank was pulled off of the vehicle.
> 
> ### Steps to reproduce
> 
> 1. Fill a `metal tank (60L)` with water (unsure if a specific amount is required - bug occurred with 95 units). Make sure this is the only `metal tank (60L)` in the area.
> 2. Freeze the water in the tank.
> 3. (Optional) Install tank into vehicle.
> 4. (Optional, only if 3 was done) Uninstall tank from vehicle.
> 5. Craft a `heated tank`.
> 
> ### Expected behavior
> 
> Either a `heated tank` object is created, or the crafting is blocked (e.g. until an empty `metal tank (60L)` is provided).
> 
> ### Screenshots
> 
> _No response_
> 
> ### Versions and configuration
> 
> - OS: Windows 10 Pro x64
> - Game Version: `781a1fc`, `cdda-windows-tiles-x64-2022-06-12-1440`
> - Tiles, but not using any tiles
> - Ingame language: English
> - Mods loaded: [
>   "dda",
>   "no_npc_food",
>   "no_fungal_growth",
>   "package_bionic_professions",
>   "blazeindustries",
>   "magiclysm",
>   "alt_map_key",
>   "MMA",
>   "crazy_cataclysm"
> ]
> 
> ### Additional context
> 
> _No response_

![shareshare__2022-06-12_21:17:272022-06-12_21:17:27|683.jpeg](https://user-images.githubusercontent.com/104958921/173463832-16926dc1-79b4-4dcf-9b2b-573752a7a90d.jpeg)

**Comment by Griffinhart** [comment]
Tested with unfrozen water (`water (cold)`) in the component tank; bug still occurs as stated originally.

**Comment by Griffinhart** [comment]
I think the `heated tank` recipe actually requires 2 `metal tank (60L)` for some reason? I crafted a second, empty `metal tank (60L)` and used that as the component for the `heated tank` craft, which succeeded (and did not prompt me about the non-empty `metal tank (60L)`), but afterwards I was missing *both* `metal tank (60L)`s, and had a block of `water (frozen) (95)` sitting on the ground, not inside the tank it was in previously.

**Comment by hexagonrecursion** [comment]
@Griffinhart  I am sorry, but I could not reproduce the issue. Are you able to reproduce is reliably?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
