### ISSUE TITLE
Cars stop in 1 second

### ISSUE THREAD

**Issue by mora145** [CleverRaven/Cataclysm-DDA#58410]
### Describe the bug

It could not be classified as a crash, but as a failure in the logic of the game. It is supposed that after the vehicles start they start to have 'momentum' that makes them continue in the direction they are going even if they are not accelerating, or if they brake it takes a few seconds to brake and reach a speed of 0. This does not happen, but the vehicles brake in 1 second, regardless of the speed at which they are moving.

### Steps to reproduce

1. Accelerate the vehicle, let's say to more than 20
2. Reduce speed to 0.

### Expected behavior

The car should move a few squares (depending on the speed at which it is slowing down) before stopping, assuming that bringing the speed to 0 also involves applying the brakes.

### Versions and configuration

- All OS
- All versions

**Comment by PatrikLundell** [comment]
You're not going fast enough. With a speed of 51 km/h and changing the speed to 0 my vehicle will typically change to 8 for one turn before stopping on the next turn. I've seen other residual speeds, and it may be dependent on the vehicle and vehicle load.
I agree that speed changes happen much faster than it does in reality, but on the other hand you've got more control of the vehicle in reality than in the game.

**Comment by mora145** [comment]
@PatrikLundell I believe that the braking speed should be about the same as the vehicle's starting time. And if it is true that they are not quite ready, but from 50 to 0 in 1 second or 2? I guess you will hit the steering wheel with your head if this happens.

**Comment by PatrikLundell** [comment]
I'm not claiming the braking speed is realistic. I'm just saying that a braking effect exists, and that slowing it all the way to realistic levels with the steering and one second steps may make vehicle travel in the game too hard.
Acceleration time probably isn't a good model for deceleration, as a weak engine doesn't have any correlation with the brake efficiency (momentum does, wheel contact area does, so maximum possible acceleration for an infinitely strong engine is probably close to the maximum possible deceleration speed).

**Comment by mora145** [comment]
Very true what you say, it has nothing to do with it. I am referring a little bit to that time lapse that can be noticed when starting the vehicle; I mean that the acceleration curve makes you really feel that the car needs some time to start and reach the target. What I think is that on the other hand the deceleration curve is a bit abrupt although in the game the brakes have not been implemented as part of the vehicle. From 51km/h to 8 in one turn is a bit extreme, and if we take the time in seconds as a reference then it is even more extreme. On the other hand, I don't know if the mass of the vehicle is included in the braking calculations. 
Do you have any idea which is the file that controls all this?
