### ISSUE TITLE
If a comestible is missing the comestible_type property, consuming fails without error

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#58412]
### Describe the bug

See title. Added some new items, forgot to set `"material": [ "veggy" ],`.

### Steps to reproduce

1. Add a comestible, which is missing `comestible_type`, like this

```json
  {
    "type": "COMESTIBLE",
    "id": "wild_garlic",
    "name": { "str_sp": "wild garlic" },
    "weight": "30 g",
    "price": 100,
    "price_postapoc": 50,
    "volume": "70 ml",
    "color": "light_green",
    "calories": 12,
    "spoils_in": "3 days",
    "healthy": 1,
    "description": "Also called ramps, this delicate leafy vegetable is healthy and a tasty ingredient for many dishes.",
    "symbol": ",",
    "flags": [ "RAW" ],
    "vitamins": [ [ "vitC", 10 ], [ "iron", 2 ] ],
    "fun": -2
  }
```

2. It shows up in the eating menu.
3. If you consume it, there will be a little progress icon but you will not gain any nutrition and the item will persist.

### Expected behavior

There is a debug message that a comestible is missing `comestible_type`, or at least upon trying to consume it. It drove me insane trying to find out why this it was behaving like this.

Also perhaps do the same if the comestible is missing `material`.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-9043-gfdf38c42583 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Ugh. It was `comestible_type`, not material.

**Comment by RenechCDDA** [comment]
comestible_type is mandatory as of #59305, closing as resolved.
