### ISSUE TITLE
Large worm got into my car and is untoucheable

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58419]
### Describe the bug

I can't hit it or push it or anything!

### Steps to reproduce

Load the game and deal with the worm in your car.

### Expected behavior

No invulnerable worms in my car.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-9089-g084538712a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

https://tinystash.undef.im/il/45TjQWoZ1UqzkWH2vR9zyEosxJ8vpkeBfmKc1CDV3abHeRgYBhFaRbhDtwAHXqxowdZ1hRxeNva7CJKCPANmXfdb.zip

**Comment by PatrikLundell** [comment]
Like the case I reported in #57580, this worm doesn't attack, and so remains harmless while it's invulnerable. Moving your character out of the vehicle allows it to hit and kill the worm as it moves onto the door.
Still a bug of course (the same one as the one previously reported), but there's a work around that allows you to get rid of it at least.
So, this is a confirmed duplicate.
