### ISSUE TITLE
Segmentation fault when inserting items into container

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58426]
### Describe the bug

The game reliably segfaults when trying to insert all items into makeshift sling.

### Steps to reproduce

1. Load attached save [crashsave.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8904903/crashsave.zip)
2. Open inventory and navigate to the worn makeshift sling
3. Press Enter, then (i) to insert
4. Press , to select all
5. Press Enter
6. Segmentation Fault

### Expected behavior

I expected no crash

### Versions and configuration

- Game version: cdda-linux-tiles-x64-2022-06-12-1440

**Comment by RoyBerube** [comment]
It makes sense to not show it if already in the sling. If you really want to take it out of the box, unload the box.

Pockets.. the problems never end.
