### ISSUE TITLE
Vehicles still have gaps

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#58427]
### Describe the bug

At least one case of a vehicle having a (LOS) gap still exists after #56143 was merged. See screenshots.

### Steps to reproduce

1. Build 5-wide, 10-long vehicle (see screenshots.)
2. turn it to face southeast.
3. Observe gap.

Text description of vehicle construction spec:
1. Coordinates are given as (row, column), zero-indexed. (0,0) is the northwestern-most tile; (0,4) is the northeastern-most tile; (9,0) is the southwestern-most tile; (9,4) is the southeastern-most tile.
2. (0,0) -> (0,4) are exterior tiles (rams)
3. (1,0) -> (1,4) are reinforced windshields
4. (2,0), (2,4), (6,0), (6,4), and (8,2) are heavy opaque hatches
5. (2,2) is the driver's seat and controls
6. (1,3), (3,3), (1,4), (3,4), (1,5), (3,5) are Steel Drum (200L)
7. (2,3) is an internal door (open in this scenario)
8. (8,0) -> (8,4), except for (8,2), are heavy stow boards
9. (3,0) -> (5,0), (3,4) -> (5,4), (7,0), and (7,4) are heavy stow boards
10. (2,1) -> (7,3) are interior tiles (heavy roof)
11. (9,0) -> (9,4) are exterior tiles
12. Wheels are at (1,0), (1,4), (8,0), and (8,4).

### Expected behavior

I believe the expectation is that vehicles should not have gaps per #56143.

### Screenshots

Gap when vehicle is turned to face southeast:
![image](https://user-images.githubusercontent.com/3744055/173715167-4a093f29-0bcb-4a36-a8cf-fe23290a4275.png)

Vehicle construction:
![image](https://user-images.githubusercontent.com/3744055/173717485-64be84cd-45cf-4fb0-9cfb-4aff1ecbd088.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 781a1fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by Griffinhart** [comment]
Gap also occurs when facing southwest:

![image](https://user-images.githubusercontent.com/3744055/173718457-92fd9d7d-e853-4067-8d5e-9d02ed97b22d.png)

**Comment by Griffinhart** [comment]
Gap also occurs when facing northwest and northeast.

![image](https://user-images.githubusercontent.com/3744055/173719587-1cedbc17-402a-4c02-a89c-a0826635ff55.png)

![image](https://user-images.githubusercontent.com/3744055/173719553-61bb3c65-be4e-46d1-b87d-8ff5699eb05c.png)

**Comment by Inglonias** [comment]
Can you provide a save file with this vehicle? I would like to try testing this, but unfortunately I'm dumb and cannot read ASCII.
