### ISSUE TITLE
Folded/missing stock should affect maximum long-range accuracy

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#58437]
### Is your feature request related to a problem? Please describe.

Was messing around with the Sig 553 and Breacher LBV and noticed that I could whip out the folded 553 and make perfectly accurate shots at max range. The only effect of not having a stock is reduced Handling, which as far as I can tell only reduces effective recoil, which in turn translates to longer time between shots of the same accuracy - or lower accuracy for the same time aiming, if you prefer.

I'm no expert, but it's my understanding that guns without a stock are harder to aim accurately because they're less stable, limiting your ability to hit distant targets. In CDDA terms, this should affect maximum possible accuracy.

### Solution you would like.

Would it be crazy if Handling simply improved your accuracy? Or perhaps rather, if low Handling impeded accuracy. Handling bonuses mostly come from stuff like stocks and bipods that provide stability. In my (again, very much non-expert) opinion, such things would improve your practical accuracy, no?

Any such bonus should probably be more noticeable at long range and not matter so much at close range.

### Describe alternatives you have considered.

- A binary check for if a gun that's supposed to have a stock doesn't have one and apply a penalty based on that. Seems a bit brute force, and perhaps arbitrary. E.g. do all those machine pistols with collapsing stocks get the penalty?
- Reduce folded stock handling to 0 instead of 10 to make that recoil _really_ noticeable. This makes some sense, as a folded Sig 553 would be much more unwieldy that a regular pistol. This might be part of the solution, but by itself it doesn't adress the core problem that you can float an 8lb assault rifle pistol in front of your eyes and snipe enemies at maximum range.

### Additional context

I've mainly talked about folding stocks here, but this would also apply to sawed-off stocks if/when that goes in, and some of it to pistols as well. If stocks and other handling upgrades provided an accuracy boost on top of managing the already manageable recoil, stocked pistols might be a serious consideration.

**Comment by Griffinhart** [comment]
>I'm no expert, but it's my understanding that guns without a stock are harder to aim accurately because they're less stable, limiting your ability to hit distant targets

Yes, but no. They don't affect the mechanical accuracy of the firearm, they relieve the shooter from having to exert themselves more to achieve stability (which I suppose is represented in CDDA by handling/time to aim), and help to mitigate recoil. This, however, doesn't affect ability to hit distant targets - that's a function of the mechanical accuracy of a gun. (I.e. unfolding the stock of a SCAR-H doesn't magically extend its range from 600 yards to 800 yards.)

It's entirely possible to achieve extremely long range shots with a handgun (no stock/bipod/foregrip, and strictly worse ballistics than a rifle), it just takes more time to aim. The same can be said of a stockless/folded stock rifle.

If anything, shooting in CDDA should have a stamina cost (not sure if it does already) and having a stock/grip/bipod/shooting from prone should reduce that stamina cost. (I, for one, certainly do get briefly tired after dumping several magazines of .308 in quick succession from a standing/offhand shooting position.)

**Comment by descan** [comment]
If blasting 200 rounds at the local zombarty convention in quick succession doesn't tucker you out to the point where you can't run away in game, and firing off such a string in real life *would*, then I would say that it probably should behave that way in the game, and then you would factor that in to your gameplay and not fire off so many rounds in one sitting.

**Comment by bombasticSlacks** [comment]
> I'm no expert, but it's my understanding that guns without a stock are harder to aim accurately because they're less stable, limiting your ability to hit distant targets. In CDDA terms, this should affect maximum possible accuracy.

My understanding is that handling does improve your target acquisition at range.

**Comment by Terrorforge** [comment]
It does, in the sense that it lets you reach a given aim level faster. If you're steadying manually that presumably translates to worse aim for the same aiming time, but I didn't really test that.

What it doesn't seem to have any effect on is maximum accuracy. I'm just some guy who watches too much Forgotten Weapons so maybe I'm just talking out my ass, but that seems wrong to me. There's an upper limit to how steady you can hold a weapon without a stock, no?

**Comment by bombasticSlacks** [comment]
To get back on track I think the actual solution should just be that steadying and holding at ready a weapon costs stamina. This has been discussed as desired before in other circumstances as well. There could be a reduction to stamina cost for each point of contact (each hand, shoulder, cheek and *if implemented better in the future* sling) and weight would increase how tiring it was.

**Comment by Terrorforge** [comment]
I did see those videos, and what struck me about them is that those techniques require specialized training and a lot of practice, which would be really cool to implement. Pie-in-the-sky version would be having proficiencies or something that let you learn those specific techniques, but a good general implementation might be that the relative penalty for suboptimal shooting is heavily reduced by high skill. E.g. a character with Shotguns 0 might actively hurt themselves trying to shoot a breacher grip gun, but for a shotgun 8 expert it's barely any worse than one with a stock.

And yeah, range (and scale in general) is pretty skewed, which is why we exaggerate a lot of stuff, like the pitiful range of pistols and shotguns. So when deciding how a gun in CDDA should perform at a certain range, we have to map that onto what it represents in real life. In the case of my 553, its 36 tile range would correspond roughly to the maximum effective range of 5.56 so (quick googling) like 500-600 yards? 

> To get back on track I think the actual solution should just be that steadying and holding at ready a weapon costs stamina. This has been discussed as desired before in other circumstances as well. There could be a reduction to stamina cost for each point of contact (each hand, shoulder, cheek and _if implemented better in the future_ sling) and weight would increase how tiring it was.

One thing that bothers me a bit about this implementation is that while I get that shooting and aiming is exhausting, is it ever going to be the kind of gasping for air, can't move my legs exhausting that's represented by running out of stamina? I guess it's probably fine since running down one street is also not quite that exhausting in real life, but it does feel a bit weird.

Oh and idk if we you he'd on this already, but in this implementation stamina should probably influence your aim somehow, either accuracy directly or just speed of aiming.

And like with the special techniques, it might be interesting if it was mitigated by skill, e g. stamina cost goes down as you develop strength and muscle memory. This might also help fix the long-standing issue that you become a god the second you acquire a gun and enough ammo to run it. It would be neat if the ability to mow down 100 zombies without breaking a sweat was actually contingent on knowing which end the bullets come out of.
