### ISSUE TITLE
Auto-Pickup/Auto-Deposit option for foraged underbrush

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#58445]
### Is your feature request related to a problem? Please describe.

There is currently an auto-pickup of sorts for harvested bushes and trees - the items deposit directly into your inventory. There is also an auto-forage feature, allowing the character to automatically check nearby underbrush, crops, and trees. But when autoforaging underbrush, the items drop directly to the ground rather than into the characters inventory, unlike with tree and flower interactions.

### Solution you would like.

Provide an option, similar to the behavior around dropping containers (All, Watertight, None), to auto-pickup foraged items of certain qualities. Food is the obvious one, but other items might want to always be picked up, like piles of straw and other crafting materials, or manufactured items like watertight containers (bottles and the like.) Having a series of auto-pickup/deposit choices would be helpful in foraging for items without needless keypresses and constant vigilance for "You Found Something!" amongst all the "Climbing onto this Long Grass is difficult!" spam. 

### Describe alternatives you have considered.

Auto-foraging depositing everything into the characters inventory without regard, such as is done with flowers and trees. 
Adding a quick-option to the Auto-Pickup Rules menu for foraged goods.

### Additional context

I assume, based on the inclusion of an auto-forage option, that there is a consensus or at least undercurrent that running around in a forest to gather needed innawoods materials, without needing to stop every 2 seconds and enter a series of keypresses and directionality, is desirable. I'm seeking to indicate one area where that QoL idea is lacking. If underbrush items dropping onto the ground, instead of into the inventory like other forages, is WAD then fair enough, although I would disagree with it. Or maybe it's harder to program for underbrush foraging than for flower/tree harvesting, I don't know the code.

Also, I understand crops also behave this way - dropping rather than being put into the inventory. I would also suggest that that be changed to prefer inventory rather than dropping, although the differences (a decent-sized crop yield can quickly fill up a characters inventory for one, and for two a crop dropping to the ground in a cleared area isn't as much of a hindrance as, say, wild vegetables dropping into a bush and disappearing from view as soon as you step 2 tiles away) so I'm not as bothered by the crop behaviour as I am by the underbrush behaviour, despite their similarities.

**Comment by liminalRoar** [comment]
Yes! this has plagued me for too long! We could really use an option to auto-pickup any foraged goods.

**Comment by PatrikLundell** [comment]
For the crops aside: I've found that the most efficient way to harvest crops is to leave the items on the ground, paint an Unsorted zone over the area, and then use auto sorting to load the harvest into a vehicle with unspecified custom zones.

**Comment by Night-Pryanik** [comment]
Essentially the same as  #41424.
