### ISSUE TITLE
Blaze Industries: Unable to install either of the Blaze Industry Buddies on any vehicle after update

### ISSUE THREAD

**Issue by SauperMagiuse** [CleverRaven/Cataclysm-DDA#58452]
### Describe the bug

A few days ago, I was on the most recent experimental and installed a MetalMaster Forge Buddy on a cart. A few days later, I removed it and went to reinstall it after moving the vehicle, but it's not listed as a vehicle part for installation. The foodco buddy is still there- I suspect this is due to the metalmaster being Blaze Industries, possibly collateral from the appliance update?

### Steps to reproduce

1. create a world with Blaze Industries mod enabled
2. Find/Spawn any vehicle with a valid spot for a MetalMaster Forge Buddy or a KitchenMaster cooking buddy.
3. (e)xamine, (i)nstall, and search for the buddy.
4. It will not be listed.

### Expected behavior

I expected the buddy to be installable on a vehicle; it was previous installed in the exact space I wanted to install it. The item is meant to be a vehicle mounted forge/welding kit, so I expected it would still be that. Same for the kitchen.

### Screenshots

![2022-06-15](https://user-images.githubusercontent.com/8670884/173973673-87d1b485-748b-40a7-8540-b2d7447759cf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: e26fd43 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries]
]

**Comment by sonphantrung** [comment]
Oh, that's my PR (#58345), which added vehicle parts as appliances. It's quite weird though, that it conflicts w/ vehicle parts

**Comment by sonphantrung** [comment]
Also, only Blaze Industries is affected by this, vanilla still works as intended
