### ISSUE TITLE
[Project] Mouse drag-and-drop in UI windows

### ISSUE THREAD

**Issue by leemuar** [CleverRaven/Cataclysm-DDA#58454]
### Is your feature request related to a problem? Please describe.

Mouse drag-and-drop is a powerful and natural way to interact with the UI. Having it implemented in different UI windows can improve UX and general usability.

This issue is a project to track all related issues and to gather suggestion on where to add drag-and-drop.

### Solution you would like.

Add drag-n-drop support to UI windows where appropriate

### Additional context

Made possible by changes in https://github.com/CleverRaven/Cataclysm-DDA/issues/58214

**Comment by PatrikLundell** [comment]
As long as it is in addition to keyboard support I have no objection. When it becomes a replacement I'm violently against it.

**Comment by Night-Pryanik** [comment]
I think moving items from one container to another using drag-and-drop would be very cool addition.

**Comment by leemuar** [comment]
> As long as it is in addition to keyboard support I have no objection. When it becomes a replacement I'm violently against it.

Addition only. Mouse support should break nothing for people without mouse, that's my core principle in expanding mouse support

**Comment by leemuar** [comment]
> I think moving items from one container to another using drag-and-drop would be very cool addition.

What UI window is this? ```i``` Inventory? ```/```Extended Inventory?

**Comment by leemuar** [comment]
Closing, will continue the work on grag-and-drop in [#58106](https://github.com/CleverRaven/Cataclysm-DDA/issues/58106)

**Comment by anothersimulacrum** [comment]
@PatrikLundell 

> As long as it is in addition to keyboard support I have no objection. When it becomes a replacement I'm violently against it.

Mouse support is not an option for the curses build, so I would not be worried.

**Comment by PatrikLundell** [comment]
Based on events I've recently seen elsewhere, I wouldn't be surprised if a "modern" crowd would consider that to be a reason to drop curses... Keyboard support is something that has to be defended constantly or it will eventually be dropped by someone who think keyboards are useless relics because they don't use them themselves.

**Comment by leemuar** [comment]
> keyboards are useless relics

I think like that too :) But I value backward compatibility and hate breaking things for people
