### ISSUE TITLE
Can't place Fridge, construction recipe calls for 'minifridge' 

### ISSUE THREAD

**Issue by vlad1492** [CleverRaven/Cataclysm-DDA#58458]
### Describe the bug

Both the 'Place Fridge' and the 'Place Minifridge' call for the same item, the minifridge. 
You can take down a fridge, resulting in a 800L 70kg object you can drag around but not place. 

### Steps to reproduce

Find a Fridge (Mine came from a Survivor Encampment)
Take it down
Try to put it up via the construction menu

### Expected behavior

Anything you can take down should be able to be put back up

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.239 (1903)
- Game Version: 3fc0f90 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Cataclysm++ [Cata++],
    Xedra Evolved [xedra_evolved],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by sonphantrung** [comment]
Can you update the game to the newest version?

**Comment by vlad1492** [comment]
Updated to 2022-06-16-0301

My fridge, undeployed, turned itself into a minifridge. 
And the construction menu remains unchanged. 
'Place Fridge' calls for a minifridge. 

Spawning in a full-sized fridge, still unable to deploy.

**Comment by sonphantrung** [comment]
Have you double-checked? I can still install fridges properly (only w/ Blaze Industries). Next time, test it with vanilla modlist

**Comment by underwillowtree** [comment]
There is a old MIGRATION in the setting of Cata++

nocts_cata_mod_DDA/legacy.json Line 82
  {
    "id": "fridge",
    "type": "MIGRATION",
    "replace": "minifridge"
  },

**Comment by vlad1492** [comment]
Thank you, looks like something I should take up with that author.

**Comment by sonphantrung** [comment]
You can now close this issue
