### ISSUE TITLE
[DinoMod] regular dino eggs can't be dehydrated

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#58464]
### Describe the bug

Large and small dino eggs can be made into powdered eggs. The same recipe structure was applied to regular size dino eggs (the majority of dino eggs), but it appears to be bugged. A quick look wasn't very revealing. The recipe is there, it should work, but it doesn't. Other recipes for regular size dino eggs using the same requirements list work fine. Thanks to Critsy Bear for catching this issue

### Steps to reproduce

1. Start a world with DinoMod enabled and give yourself every recipe. 
2. Note that you have many recipes for powdered eggs, but only large and small dino eggs can be used. For example, no ceratopsian egg like triceratops can be used.

### Expected behavior

Regular dino eggs appear as options for powdered eggs as intended

### Versions and configuration

Latest experimental with DinoMod enabled

**Comment by mqrause** [comment]
The recipes for normal and large eggs use the same `id_suffix`, so the latter overwrite the former.
