### ISSUE TITLE
New main menu issues, part II

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#58462]
### Describe the bug

- [x] When there are no worlds created, pressing Enter on the `Load` menu crashes the game.
- [x] Now there is no way to delete created presets. Previously pressing `d` on the selected preset deleted it.
- [ ] Selecting world with no save games (through `Load` menu) creates a `Foo has no characters to load!` popup which you cannot close by pressing RMB.
- [ ] In the `Setting` menu, only `Options` submenu is right-click-closable. Other submenus (`Colors`, `Autopickup`, `Safemode`, `Keybindings`) are not right-click closable.
- [ ] Minor: in the `Options` submenu sound is played when you're hovering over tabs names. I.e. it will play sound on every mouse move over World Defaults tab name, not only when you're changing highlighted tabs.

### Steps to reproduce

See above.

### Expected behavior

See above.

### Versions and configuration

Windows 10 x64, 0.F-9162.

**Comment by SandNoodle** [comment]
> * [ ]  When there are no worlds created, pressing Enter on the `Load` menu crashes the game.

was fixed in 5ac426d by @BrettDong

**Comment by SandNoodle** [comment]
> Selecting world with no save games (through Load menu) creates a Foo has no characters to load! popup which you cannot close by pressing RMB.

Also, LMB should bring up the popup (it should mimic [HELP] behavior in that case)
