### ISSUE TITLE
smashing zombie corpse doesn't reset FoV after shooting

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#58478]
### Describe the bug

FoV is not reset after smashing zombie corpse

### Steps to reproduce

1. shoot gun precisely (f -> precise)
2. smash zobmie corpse

### Expected behavior

any action which takes time should reset FoV

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: e26fd43 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod]
]

### Additional context

I've tried to find more actions which dont' reset FoV but only one so far seems to be `s`mashing zombie corspe

**Comment by NetSysFire** [comment]
@Night-Pryanik, since you did #58073, mind taking a look at this?

**Comment by Night-Pryanik** [comment]
Ok, I'll look into this, though I'm unfamiliar with FOV stuff.
