### ISSUE TITLE
Fake parts block floodlights.

### ISSUE THREAD

**Issue by LetMeGitDat** [CleverRaven/Cataclysm-DDA#58470]
### Describe the bug

Fake parts generated by deforming vehicles block vehicle light sources.

### Steps to reproduce

1. Make a vehicle.
2. Install cameras+floodlights/directed floodlights facing left/right/rear.
3. Drive at night, turn until the vehicle deforms, and generates fake parts.

### Expected behavior

The light should propagate as it would without fake parts.

### Screenshots

[https://ibb.co/dPMS2wK](url)
[https://ibb.co/c6zSsNk](url)
[https://ibb.co/vhTDxJz](url)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 6dc7309 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
I believe I've been annoyed to see that the view from (internal) rear mirrors get more restricted than before when moving at an angle. That's not strong enough to be considered a confirmation, though.
