### ISSUE TITLE
Adding metal bars to empty window frames

### ISSUE THREAD

**Issue by Mravv1** [CleverRaven/Cataclysm-DDA#58471]
### Is your feature request related to a problem? Please describe.

Currently if you want to add metal bars to an empty window frame, you have to install a sheet of glass first, then add bars.

### Solution you would like.

I would like to be able to install bars onto empty window frames the same way as with regular windows.

**Comment by swatiaggrawal** [comment]
hello @Mravv1 
Can you please assign this issue to me and elaborate more about the issue. I am a first-time contributor.
Looking forward to your reply.
Thanks.

**Comment by Mravv1** [comment]
Hi @swatiaggrawal 
After reading Github's guide on assigning issues I can say with a high degree of certainty that I can't do that.
I'm not sure what you mean by elaborating on the issue, it will be easier if I just tell you how I'd solve it.
The file you'll need to change is construction.json and the construction group you'll need to add to is "install_bars_onto_window" found here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/construction.json#L2680
The code you'd need to add should be roughly a copy of lines 2680 to 2692 with id changed to something like "constr_window_bars_frame", pre_terrain to "t_window_empty" and post_terrain to "t_window_bars_noglass".
And before you ask, I didn't do that myself because I can't wrap my head around how Github works.

**Comment by NetSysFire** [comment]
We do not assign issues to first time contributors. Just file a PR and link it to this issue.
