### ISSUE TITLE
Alternative color overlay when seeing down a z-level

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#58479]
### Is your feature request related to a problem? Please describe.

Currently, when viewing different z-levels in-game, the game will render corresponding colored dots for whatever tile is one level below, with a sky blue background, and black for tiles that go even further down. This is a fairly basic method of handling the situation and could be improved upon.

### Solution you would like.

As an (optional) alternative, instead allow for these tiles to be rendered with a specified overlay color, just as map memory is handled, but with a different default color choice (e.g., darkened for memory, sepia for depth). It could also handle multiple z-levels by stacking the effect (with a potential cap if need be) or with additional colors.

### Describe alternatives you have considered.

A miniature rendering of the sprites instead of just the dots, and possibly tiled to fill the space for terrain (this could be done alongside the main suggestion, although it would likely be more complicated and less effective).
Or just staying with the current method.

### Additional context

Rough concept pictures:
![zlvlcon2](https://user-images.githubusercontent.com/32048635/174202918-89c924e5-8ad0-4328-871a-569bba44e85d.png)
![zlvlcon1](https://user-images.githubusercontent.com/32048635/174202923-fceaddd9-baa4-4c7a-94f4-3c54aae94096.png)

**Comment by RAldrich** [comment]
This should actually be pretty straightforward to implement, as it's already being done for vehicle rendering: you'll see either the vehicle roof, or a grayscale version of the tile graphics.

The rest of the cata_tiles::draw_terrain_below is actually just sampling the underlying tile graphic, extracting the dominant curses tile color and converting it a rectangular SDL tile.

I'm not totally clear why the conversion to SDL tiles was chosen in the first place, but I might take a stab at this.

**Comment by RAldrich** [comment]
Ok after poking at this for a bit getting the tiles below to render is trivial, but getting them render and play nice with rendering vehicles, creatures, etc. will take some fiddling (I'm still reading through the huge file that is the rendering code). Other issues include:

- The existing light levels aren't very good for this, it's hard to tell where the edge of the roof is if using light_level::LOW and light_level::MEMORIZED just doesn't look good. Will need a new type of light level.
- The light level filter approach may not look good on creatures (but could still be better than the existing red squares)
- Additional work will be needed to support z-layers more than one layer below. Dwarf fortress handles this with an increasingly dark fade, which I think would work here, but might require a re-work instead of just slapping a light level on top of things.

**Comment by anothersimulacrum** [comment]
> The existing light levels aren't very good for this, it's hard to tell where the edge of the roof is if using light_level::LOW and light_level::MEMORIZED just doesn't look good. Will need a new type of light level.

Be aware that adding a new light level will increase the memory footprint of tiles by 20%, because every tile is duplicated for each light level.

**Comment by RAldrich** [comment]
>Be aware that adding a new light level will increase the memory footprint of tiles by 20%, because every tile is duplicated for each light level.

Good to know! I will not do that. Maybe some combination of an existing light level and the SDL squares could look ok (as is currently done for the vehicles).

**Comment by RAldrich** [comment]
Ok, I've got the draw layering sorted out. Newest problem is that various terrain tiles were not designed to be visible from above and look bad (downspouts stand out as an example of this).

Simply leaving the existing SDL boxes on top of the tiles helps with visual separation, but I'm not convinced this actually looks better yet.

**Comment by RAldrich** [comment]
After some conversations over on Reddit, it's looking like getting the rough edges into an acceptable level of polish is going to require a pretty significant overhaul of the rendering engine. That is something I'm capable of and interested in doing, but it will not be a fast fix (and certainly will not be accepted during a release freeze). I'm going to think on this and determine if there is a way to get some of the functionality released iteratively.

**Comment by sonphantrung** [comment]
Undergoing process with #61074

**Comment by joonazan** [comment]
@RAldrich can you share the reddit conversations and your code? It sounds like even your rough version could be an improvement over not seeing down.

I might help with the graphics overhaul, depending on how much I enjoy the game. (Only started playing recently.) I know modern C++ (though more proficient in Rust) and have computer graphics experience and a degree.

**Comment by RAldrich** [comment]
I don't mind sharing, but it's 100% not a production approach: it wastes a lot of cycles on drawing blended overlays. And there's the obvious visual problems with all sprites that extend outside their cell.

I also don't think I have a remote branch with the changes, and I'm traveling for the Thanksgiving holiday, so I won't be back at my dev machine for about two weeks.

**Comment by joonazan** [comment]
No problem, I'm not going to work on it right now anyway.

ma 21. marrask. 2022 klo 21.34 Ryan Aldrich ***@***.***)
kirjoitti:
