### ISSUE TITLE
"There is nothing to pick up." popup should not be shown when character (w)ields the only item in the (g)et menu

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58473]
### Is your feature request related to a problem? Please describe.

"There is nothing to pick up." popup is shown when you (w)ield an item from the (g)et menu and the wielded item was the only one in the menu. This information is already obvious and the popup is repetitive and distracting because it blocks all other input for one keypress.

### Solution you would like.

Do not show the popup if the last item got wielded.

### Describe alternatives you have considered.

Alternatively a log message along the lines of "There are no more items" could be shown. But I do not think it's needed either.

**Comment by NetSysFire** [comment]
Might be the same underlying issue as #53526

**Comment by mqrause** [comment]
Wield/wear closes and reopens the pickup menu. The reopening is where the popup is shown. To avoid this, it needs a method to check the number of items the menu has and only reopen it when that number minus what you're wielding is >0 (careful with partial wielding of charges). It's probably a fairly easy change.

It's unrelated to the other issue.
