### ISSUE TITLE
Zombies that used to be NPCs should have their names displayed

### ISSUE THREAD

**Issue by leifgiering** [CleverRaven/Cataclysm-DDA#58481]
### Is your feature request related to a problem? Please describe.

If an NPC dies and reanimates, you don't necessarily know it was them, unless you either saw their corpse rise or know based on where you found them.

### Solution you would like.

Zombies that used to be NPCs should have their living name next to their monster name.  Example:

Zombie: Taylor Jones

This feature already exists for scripted zombies, such as the "Tough Zombie: Andy" easter egg.

**Comment by descan** [comment]
Semi-related, but it might be fun if some zombies that spawned in retail locations could spawn with a name-tag item and if you get close enough to read it, the zombie gets labelled with their living name.
