### ISSUE TITLE
Should be a bug: craft Steel sewing awl

### ISSUE THREAD

**Issue by XchiTea** [CleverRaven/Cataclysm-DDA#58488]
### Describe the bug

There are 2 formula to craft steel sewing awl. 
One need lv.4 fabrication, and a lot of forging tools, such as anvil, metal tongs, torch...
Another formula only need lv.1 fabrication and a screwdriver.

### Steps to reproduce

press '&'

### Expected behavior

It looks like the easy formula should be a bug. Because you can't use only One screwdriver to make a steel sewing awl!

### Versions and configuration

- os: windows 11
- game version: cdda-windows-tiles-x64-2022-06-17-1020

**Comment by a-chancey** [comment]
The screwdriver version also requires a tool with filing 1. 

Which, to be fair, seems a bit unrealistic. Filing 1 is sandpaper/sand leather, which may *eventually* work, but I think 50 minutes is too short for sandpaper to do the job. That being said, I've not taken the time to test this IRL, I'm just thinking you're going to burn through a LOT of sandpaper. 

Filing 2 would be more sensible to me, as the filing 2 tool is a metal file set.

**Comment by chrispikula** [comment]
A stone to scrape the screwdriver against till it's roughly the right shape, then sandpaper would work.  This would also mangle the sandpaper, but that's a story for another time.

**Comment by descan** [comment]
If it would break sandpaper/sandleather, then maybe the recipe could involve a tool to scrape the screwdriver against (hammering? clean surface? anvil?, and then use the sandpaper/leather as an ingredient? Using a tool as an ingredient like that is... unorthodox, to be sure. 

The current recipe with filing 2 and no destruction of the sandpaper/leather could stand alongside - there are other items that have three recipes too, such as all the thread, string, yarn, and rope recipes (involving hand spinning, distaff spinning, and using a spinwheel)
