### ISSUE TITLE
 DEBUG    : invalid recipe id "rag_from_sheet"   FUNCTION : const T& string_id<T>::obj() const [with T = recipe]  FILE     : src/recipe_dictionary.cpp  LINE     : 67  VERSION  : ab49000

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58497]
### Describe the bug

Error opening save

### Steps to reproduce

Open save

### Expected behavior

no error

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: ab49000 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by descan** [comment]
This is a result of the recent tailoring changes - the rags have been deprecated in favour of cotton patches. Saves older than those changes, which retain hooks to recipes for and involving rags that are now gone, produce the error.

I don't *believe* it'll cause any issues - it hasn't crashed my game yet, all my rags were properly transformed into patches, and I can use other recipes correctly.

**Comment by BevapDin** [comment]
About that: what is actually stored in a "in progress" item? If it stores the recipe id, it will now contain an invalid id. Does it still spawn the correct resulting item?

**Comment by descan** [comment]
> About that: what is actually stored in a "in progress" item? If it stores the recipe id, it will now contain an invalid id. Does it still spawn the correct resulting item?

Actually, now that you say that, I did have some in-progress disassembly of combat boots that behaved weirdly. They immediately finished and said it produced only a single item (a rubber sole)

Although there seemed to be the correct quantity of items on the workbench, I can't be sure as I didn't check immediately. The fact that it finished immediately is concerning though, even if it spawned correct items.

**Comment by Max17U** [comment]
> This is a result of the recent tailoring changes - the rags have been deprecated in favour of cotton patches. Saves older than those changes, which retain hooks to recipes for and involving rags that are now gone, produce the error.

I received a similar error `invalid recipe id "ammo_satchel_from leather`, while loading an older savefile [older version: 2022-05-19-0557, newer version:2022-06-18-0247]. 
So i guess it could depend, as you said, from the new tailoring changes. I hope my save won't break, lol.

**Comment by descan** [comment]
re: the combat boots, I later had another pair of boots that I disassembled post-changes, and they also took very little time and only provided one rubber sole. I think that's a different bug than a recipe being called that doesn't exist. I'll report the bug if it persists if/when I die and make a new character in a new world.

**Comment by andrei8l** [comment]
> re: the combat boots, I later had another pair of combat boots that I disassembled post-changes, and they also took very little time and only provided one rubber sole. I think that's a different bug than a recipe being called that doesn't exist. I'll report the bug if it persists if/when I die and make a new character in a new world.

This is just an error in the JSON recipe
```diff
diff --git a/data/json/recipes/recipe_deconstruction.json b/data/json/recipes/recipe_deconstruction.json
index 158e9d4889..babf613793 100644
--- a/data/json/recipes/recipe_deconstruction.json
+++ b/data/json/recipes/recipe_deconstruction.json
@@ -6248,7 +6248,7 @@
     "type": "uncraft",
     "activity_level": "LIGHT_EXERCISE",
     "time": "24 s",
-    "components": [ [ [ "sole_rubber", 1 ], [ "leather", 4 ], [ "scrap_kevlar", 4 ] ] ],
+    "components": [ [ [ "sole_rubber", 1 ] ], [ [ "leather", 4 ] ], [ [ "scrap_kevlar", 4 ] ] ],
     "qualities": [ { "id": "CUT", "level": 1 } ]
   },
   {
```
