### ISSUE TITLE
Impossible to fly the Apache Helicopter at the Aircraft Carrier.

### ISSUE THREAD

**Issue by vicbrandao92** [CleverRaven/Cataclysm-DDA#58491]
### Describe the bug

Getting the message "It would be unsafe to try and ascend when there are obstacles above you" while trying to fly the carrier's Apache.

### Steps to reproduce

1. Make a player with the helicopter flying proficiency.
2. Spawn at the Aircraft Carrier
3. Find and try to fly the "like new" Apache.

### Expected behavior

Expected the Apache to take off.

### Screenshots

![image](https://user-images.githubusercontent.com/64813207/174346066-2aece9e0-85e5-4a37-bcbc-4de26a730e2f.png)

### Versions and configuration

Windows 10.
Version windows-tiles-x64-2022-06-15-1529.
English Language.
Standard mod array.

**Comment by GuardianDll** [comment]
/confirmed.
thats odd, because there is nothing above the heli
![image](https://user-images.githubusercontent.com/67688115/174348174-ef634190-4587-473b-b1c7-592c97b2a858.png)

**Comment by vicbrandao92** [comment]
Seems like it's the elevator floor. Game treats it as a box elevator I guess. Edited sidewalk all around it and it flew. Well, would have flown, if the rotors hadn't collided with the nearby railing, making the whole helicopter explode.
