### ISSUE TITLE
mon_science_bot's "SCIENCE" should not mutate the player

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#58492]
### Is your feature request related to a problem? Please describe.

Currently experimental lab bots can mutate the player with their magic laser beam. This mutation occurs instantaneously unlike any other mutations which were changed to be gradual. Aside from arguably being pretty lore-breaking this has an effect of making experimental lab bots capable of randomly fucking up your character irreversibly through mutations as it is no longer possible to purify mutations without cleaving through your starting traits because of how purifier works nowadays.

Yuggs probably have the same issue, but it's especially egregious that a manmade device can remotely mutate people instantly.

### Solution you would like.

Beam should just irradiate the player if anything, it should not cause mutations.

### Describe alternatives you have considered.

Arguably the radiation it inflicts could be what's mutating you, but this has always been a very silly mechanic leftover from the Fallout era of CDDA.

**Comment by anothersimulacrum** [comment]
Located here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/ab490003680fda0330ad643f4753722980cb7fa0/src/monattack.cpp#L1453
