### ISSUE TITLE
Grabs persisting longer than they should

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#58501]
### Describe the bug

Grabs no longer break immediately when broken. The chatlog displays a message about breaking out of the grab but you remain grabbed and have the grabbed debuff until the next turn when the chat log tells you "you find yourself no longer grabbed".

### Steps to reproduce

1. Get grabbed.
2. Break the grab.

### Expected behavior

Breaking the grab should break the grab.

### Screenshots

![bug1](https://user-images.githubusercontent.com/56016372/174416203-97d70a16-a151-4937-bf6e-2cfdfb7363b4.png)
![bug2](https://user-images.githubusercontent.com/56016372/174416204-33b4662c-dc58-41d6-9923-fb3840e8ee29.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: ab49000 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by andrei8l** [comment]
/confirmed Caused by #58400. It looks like the order of operations is still not quite right.

Somewhat related issue: fleeing & grabbing monsters still keep you grabbed after moving away. This existed before the PR above and can be tested with `mon_shadow`s.
