### ISSUE TITLE
 DEBUG    : Attempted a recipe with no available components!   FUNCTION : comp_selection<item_comp> Character::select_item_component(const std::vector<item_comp>&, int, read_only_visitable&, bool, const std::function<bool(const item&)>&, bool, const recipe*)  FILE     : src/crafting.cpp  LINE     : 1798  VERSION  : ab49000

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58517]
### Describe the bug

Error while crafting a makeshift funnel

### Steps to reproduce

Craft makeshift funnel

### Expected behavior

no error

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: ab49000 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by SandNoodle** [comment]
Can you provide a save file?

**Comment by matt32106** [comment]
No save file sorry, a pity that crashing won't generate a save file on its own...

**Comment by Timoffey** [comment]
The same
Mac OS 12.4
Apple Silicon M1 Pro
ERROR : src/crafting.cpp:1617 [comp_selection<item_comp> Character::select_item_component(const std::vector<item_comp> &, int, read_only_visitable &, bool, const std::function<bool (const item &)> &, bool)] Attempted a recipe with no available components!% []
Here files log + save: https://drive.google.com/drive/folders/1iX1oAjGgCjLhvT36H0YWrDIbyc8uaqrF?usp=sharing
