### ISSUE TITLE
Some eggs spawn outside of egg cartons

### ISSUE THREAD

**Issue by Cimanyd0** [CleverRaven/Cataclysm-DDA#58536]
### Describe the bug

Refrigerators in houses can have egg cartons with some eggs in them, but they also contain standalone eggs.

### Steps to reproduce

1. Go to a fridge. (You can start in a house by selecting an In Town scenario like Missed, then going to the last screen on character creation and pressing `/`.)
2. Look at what's in the fridge (such as with `g`) and see what the eggs look like.

### Expected behavior

Eggs should be in egg cartons, because that's why egg cartons were added to the game (source: #47020), and it seems odd to have half of them rolling around on their own inside fridges.

### Screenshots

![CDDA escaped eggs](https://user-images.githubusercontent.com/74877667/174458473-04b4d282-b0a9-464b-80c5-1981f788fb37.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: d422ab7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Sometimes the total number of eggs is more than 12, so it's possible there are also twice as many eggs than there should be—one set in a carton, one set out. Of course, there's no reason a fridge couldn't have more than 12 eggs or 1 carton.

**Comment by estebandellasilva** [comment]
... i am not sure this is a bug ... as some refrigerators can have egg holders ... or maybe you got one of those insane freaks that keep their eggs just in the refrigerator
![image](https://user-images.githubusercontent.com/89189872/174467196-595e68f3-421e-41b8-8e40-04ac8f71ec8b.png)

**Comment by hexagonrecursion** [comment]
/confirmed eggs **do** spawn by themselves
![image](https://user-images.githubusercontent.com/52621858/177046469-c7f6d874-99ae-4f92-9caf-0b852351ddfc.png)


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
