### ISSUE TITLE
Innawood naked Impossible

### ISSUE THREAD

**Issue by VagaB00m** [CleverRaven/Cataclysm-DDA#58535]
### Is your feature request related to a problem? Please describe.

The tailoring update made impossible surviving a innawood naked run. Since you aren't able to make any piece of clothing until you get to bronze or iron due that all clothing recipes need "fabric cutting" quality and you can't have any until you get bronze shears or scissors, you can't even make anything made of grass besides grass skirt and grass shirt that give almost nothing of warm making it impossible to get away from fire. 

Besides that the other issue is that you now need a lot of fibercloth sheets to make clothing.

### Solution you would like.

Maybe add a stone tool with fabric cutting. And add another way to get plant fiber or increase the output of the actual recipes.

### Describe alternatives you have considered.

Make cotton plants more common, I haven't seen any in my innawood runs.

**Comment by mqrause** [comment]
Yeah, the grass recipes at least need an overhaul. Making (enough) fibercloth isn't feasible without a spinning wheel anyway, so that's for a later tech level. Considering the amounts you need to make, a more "automated" way to produce them with less repeated keypresses would be nice, though.

But all in all it's still very much possible to reach summer without clothes and at that point you have enough time and resources to make all the tools you need. But getting there is meant to be hard.

**Comment by NetSysFire** [comment]
CC @Light-Wave

**Comment by Sathra225** [comment]
The Innawoods wild cotton plants won't help, as they're only harvestable in Autumn and cannabis is Summer onwards. There's not alot of granularity in tool qualities either.

**Comment by Light-Wave** [comment]
I feel like the following items should be craftable without fabric cutting, as they are relatively crude shapes. They should require normal cutting if anything.

- All grass yarn items
- All cloaks
- All types of hand wraps
- All types of foot wraps
- All types of scarfs
- Bandana
- Turban
- XL and XS versions of mentioned items

I think it would be reasonable to have these changes in mainline.

Thoughts?

**Comment by Sathra225** [comment]
Sounds reasonable to me. They've all got fabric cutting reqs due to sewing_standard being updated to include fabric_cut. So those items would need a new simple_sewing_standard or something.

**Comment by Light-Wave** [comment]
Sounds like a good fix. I'll look into implementing that tomorrow. In the meanwhile, are there any other items you think should be craftable without metal cutting tools? If so, feel free to list them below.

**Comment by VagaB00m** [comment]
I would think about planks, you can't either get them until you have something with tree cutting or wood sawing 2 which are only metal tools. Maybe buff the adze or stone axe as it's more easy crafting a stone axe head instead of the full since you need less tools, that would be a reason to craft the full stone axe.

**Comment by MegaGlub** [comment]
> Sounds like a good fix. I'll look into implementing that tomorrow. In the meanwhile, are there any other items you think should be craftable without metal cutting tools? If so, feel free to list them below.

Probably some form of blanket or sheet. iirc, there's grass sheets and blankets that require fabric cutting currently that probably should not.

**Comment by Light-Wave** [comment]
Good catch. Added blankets to the list and made a pull request. PR #58565

**Comment by a-chancey** [comment]
All the changes seem reasonable to me with the justification given. There's probably more that could use regular cutting, but this is a solid start.

**Comment by RAldrich** [comment]
Just to look at this from the other angle, is the problem possibly that exposure mechanics are overtuned? Would a naked, healthy, adult human die of exposure during the spring in New England?
