### ISSUE TITLE
Long hang while reading book

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#58533]
### Describe the bug

While reading a book as the sun was setting, the game hung for a very long time, and showed as "not responsive", before eventually showing me the "stop reading?" prompt.

### Steps to reproduce

I'm not sure how to reproduce this precisely, but I've attached a dump file created with Task Manager, which hopefully will show where the problem is.

### Expected behavior

The game shouldn't take 60+ seconds to do anything!

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 781a1fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

Here's a link to the memory dump taken while the game was hung: https://drive.google.com/file/d/1papImzrLN-a2oNqxeZV4vCsVNkR0mTud/view?usp=sharing

**Comment by descan** [comment]
I've had similar hangs on other tasks - actually, right as I'm writing this, it's hanging on dissecting a Skeletal Brute in the back of the refugee center.
