### ISSUE TITLE
Incorrect Responses when asking for training from NPC

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#58537]
### Describe the bug

When asking an NPC to train, if they are willing to, they say "Sorry, can't do that." If isn't, he says "Sure, happy to trade." The player responses are the only indicator that he is actually willing, or that he isn't.

### Steps to reproduce

1. Load save
2. Talk to John Bailey, navigate to asking to trade for learning a trade.
3. Note his response indicates affirmative, but that the player cannot negotiate for training.

### Expected behavior

I expect that an NPC willing to trade will say as such, while unwilling NPCs will say "Sorry, no."

### Screenshots

![image](https://user-images.githubusercontent.com/4212389/174459698-f615782a-e85c-4608-8111-574b458b2ea8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: 08c16e6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Generic Guns [generic_guns],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

This might be specific to this NPC and situation, I'm not sure.

**Comment by descan** [comment]
[Cawood.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8934490/Cawood.zip)

**Comment by hexagonrecursion** [comment]
/confirmed in a fresh world (I have forced John Bailey to spawn by editing the data files)

I think yes and no got swapped.

https://github.com/CleverRaven/Cataclysm-DDA/blob/9e85e6e00a11b042ec248435f7bf2a97a6b3bfed/data/json/npcs/random_encounters/john_bailey.json#L520-L526

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
