### ISSUE TITLE
Guaranteed crash in an extremely specific set of Random NPC circumstances

### ISSUE THREAD

**Issue by digitCruncher** [CleverRaven/Cataclysm-DDA#58534]
### Describe the bug

Some random shelter NPCs have missions that appear when you first talk to them (e.g. 'Infected NPC needs antibiotics mission'). However, the NPC dialogue pathways aren't set correctly when you accept the mission, allowing you to accept it a second time, which causes the game to crash.

To do this you need to:

- A random starting shelter NPC with one of the 4(?) missions that change the initial dialogue (eater of the dead, infected NPC, asthmatic NPC, or dead mother)
- Accept that mission
- Don't end the conversation yet, but instead start a trade
- Cancel the trade without doing anything (*very* common behaviour, as often the NPCs have nothing of value)
- Accept the mission a second time.

(This is a low priority as the bug seems to be extremely specific, and the workaround is just to not accept it a second time. I mostly wrote it because I only realised it was extremely specific while I was trying to reproduce it)

### Steps to reproduce

1) Start a 'Missed' scenario (or any scenario which starts with a random NPC)
2) Save the game
3) Talk to the NPC
4) If the NPC starts talking with "At least we have shelter", they don't have an initial mission, and this bug can't be reproduced. Delete the world and start again
5) If the NPC says anything else (eg. "The eater of the dead... something was ripping zombies to shreds and only leaving a few scattered limbs") continue talking along the path that makes you accept the mission
6) After accepting the mission select "Not a problem", then start trading
7) Cancel trading, and the NPC will start the conversation from the top [I have not tested accepting trading, but from memory, a successful trade ends the conversation, and thus this bug won't happen if you perform an actual trade]
![image](https://user-images.githubusercontent.com/48256023/174456932-d3aeedce-f01e-4bdc-9b16-99581663a814.png)
8) Continue talking along the path that makes you accept the mission again
9) An error message appears: 'DEBUG: strange: player is already assigned to mission 1' ... line 281 of src/mission.cpp, version d422ab7
![image](https://user-images.githubusercontent.com/48256023/174456914-1325e436-1acf-4a5d-bc64-3d928cc7c94b.png)
10) The game crashes

### Expected behavior

After cancelling trading, the NPC should go to the 'Well, I guess it's just us.' page, and not the special mission start page.

Accepting the mission after already accepting it should stop more gracefully (possibly with an error)

### Versions and configuration

09:01:51.856 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: d422ab7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8934342/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8934346/debug.log)

**Comment by Cimanyd0** [comment]
This has previously been reported at #52220 and #54648, but is still happening (I only know about those since I ran into the bug a few days ago).
