### ISSUE TITLE
Bug on death of the mission dog

### ISSUE THREAD

**Issue by mora145** [CleverRaven/Cataclysm-DDA#58556]
### Describe the bug

In the first survivor mission, the NPC that appears next to me sends me to look for a dog, and gives me a whistle to call it when it is near. I then return with the dog and talk to the NPC who gave me the mission, it is marked as completed but the dog continues to follow me. 
After some other monster kills it I get the crash. 
Even if I give the sibate back to the NPC the dog continues to follow me.

### Steps to reproduce

1. Obtain the mission 'Find Lost Dog'.
2. Search for the dog and blow the whistle when it is near.
3. Complete the mission by talking to the NPC
4. Go to fight some monster and get the dog killed.

### Expected behavior

When the mission is completed the ownership of the dog should pass to the NPC.

### Screenshots

![Screenshot_51](https://user-images.githubusercontent.com/25883820/174498459-2a8de23b-7d53-49ed-9d45-3c4c42ce24f4.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 060b19e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Deadly Zombie Virus [deadly_bites],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8936209/debug.log)
Save: https://drive.google.com/file/d/1wbFHx34s3mTNB5bj9b-ioXOgwt0w0DaR/view?usp=sharing

**Comment by hexagonrecursion** [comment]
/confirmed (partially)

1. The dog does follow me after the mission is done (it should not)
2. When the dog dies I get the same debug assertion I see in your log (see below)
3. I did not get a crash. I have tried this in a fresh save 2 times and once using your save file

```
 DEBUG    : completed mission 1 was not in the active_missions list

 FUNCTION : void avatar::on_mission_finished(mission&)
 FILE     : src/avatar.cpp
 LINE     : 349
 VERSION  : 765f442
```

- OS: Linux
    - OS Version: <unknown>
- Game Version: 765f442 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mora145** [comment]
@hexagonrecursion Thank you for trying it out. 
Yes, although I don't have a complete crash, getting rid of the dog without making too much of a mess is a sad thing. I wouldn't want to lead the dog to certain death.
