### ISSUE TITLE
M26-MASS standalone shotgun: Magazines Are Unobtainable

### ISSUE THREAD

**Issue by Silencer9941** [CleverRaven/Cataclysm-DDA#58563]
### Describe the bug

The "M26-MASS standalone shotgun" seems to be a new shotgun and it doesn't seem to spawn with the magazines intended for them. I checked on "https://nornagon.github.io/cdda-guide/#/item/m26_mass_mag_3" and they don't seem to be obtainable via crafting or looting a location. Shotgun cannot be loaded by any other means.

### Steps to reproduce

1. Find military body site containing the M26-MASS standalone shotgun
2. Pickup gun and examine
3. Gun does not contain either the 3-round or the 5-round magazine
4. Magazines do not spawn anywhere

### Expected behavior

The shotgun should spawn with the 3-round magazine or the 5-round magazine. Or, they should be obtainable from body sites or military related locations.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: cc694a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

I found the military body site in a Hub-01 railroad system and the gun itself was next to a dead feral soldier with a couple spiders wandering about.

**Comment by GuardianDll** [comment]
Thats odd, i thought they spawn with empty mags inside 🤔
Anyway it was fixed already in #58016
