### ISSUE TITLE
Military bases are very easy to clear thanks to infinite grenades

### ISSUE THREAD

**Issue by actually-a-cat** [CleverRaven/Cataclysm-DDA#58577]
### Is your feature request related to a problem? Please describe.

Military bases don't provide an appropriate level of challenge relative to their size, menacing appearance, and the obscene amounts of loot inside. The threat inside is a horde of soldier zombies, but on its own, that is a somewhat self-defeating enemy because of the generous grenade drops. All you need to do is loot a few zombies that have leaked outside (the base conveniently provides a minefield for them to die on) to gather an armful of grenades, then with those you can kill a small crowd, which in turn will provide you with more grenades than you could possibly need. All before you've even entered one building in the base.

Even if it's late and there are kevlar hulks everywhere that doesn't matter much when you have more grenades than you can carry and every wave of them brings you more.

### Solution you would like.

Fewer zombies, more and better ferals instead. Ferals manning machine gun nests. Sniper ferals. Grenade launcher ferals. ~~Missile launcher ferals.~~ I'm imagining military bases as an extreme ranged combat challenge that actually warrants an armored deathmobile or power armor.

**Comment by RAldrich** [comment]
Adding damaged variations of the base would also help a lot. Right now it is pristine, as if everyone zombified all at once, suddenly, with no chance for resistance. This makes no sense, I would expect all of that delicious military ordinance to have been *used* in a last stand defense of the facility.

There should also be holdout emplacements on rooftops. The former inhabitants are just as intelligent as the player avatar and follow similar strategies.

I get that the cataclysm is modeled as a sudden recent event, but if anyone had a chance to react with extreme violence I would expect it to be the military base inhabitants.

Hell, we should probably go all out and add a new survivor faction for a successfully held base.
