### ISSUE TITLE
Exodii pods spawning very large numbers of firearms and ammunition

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58575]
### Describe the bug

When opening crashed exodii pods, there appear to be unusual numbers of weapons and ammunition being spawned alongside the other materials found within. For example, one pod spawned with 3000 rounds of 12.3 ln ammunition and 52 magazines, while another had 60 guns. This represents levels of firepower and bartering content exceeding the finales of some major locations at the cost of the fuel required to torch 1-2 layers of metal. When taken in concert with the CBMs found in zomborgs, this makes exodii pods perhaps the most lucrative map extra in the game by an enormous degree.

![image](https://user-images.githubusercontent.com/104868222/174630521-f32f09ba-ad74-4b4e-a886-8bb46af96507.png)

![image](https://user-images.githubusercontent.com/104868222/174630990-1a6ecd55-4d54-4264-bce4-93fe8aae44bb.png)

### Steps to reproduce

* Spawn crashed pod map extra

* Cut into the metal portion with a torch or via other methods

### Expected behavior

More reasonable spawn rates should exist to reflect the relative ease with which the pods can be looted.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: cc694a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by a-chancey** [comment]
Yeah looking at the spawn groups, they can spawn 15-20 of one of the guns and 10-15 of the other if RNG plays nice. The odds aren't that great to get the high value loot variety, but sometimes you just get lucky

**Comment by Ilurker** [comment]
If you check, the screenshot, it's actually much higher than that - there are literally 60 guns (35 of one and 25 of the other) spawned in the one pod. Perhaps I was very lucky this game, but it's somewhat suspicious for both pods to be an extraordinary outlier like that!

**Comment by a-chancey** [comment]
Some of them have multiple loot locations, each with a 100% chance to spawn stuff from the item group, and some of them have a chance to repeat the item placement. They’re loaded with items by design apparently

**Comment by Broken27** [comment]
You are thinking that there must be a relation between the difficulty of a location and it's rewards, but that's not a design goal.

Extremely hard locations having no loot, and easy locations having great loot is perfectly fine.

**Comment by Ilurker** [comment]
> You are thinking that there must be a relation between the difficulty of a location and it's rewards, but that's not a design goal.
> 
> Extremely hard locations having no loot, and easy locations having great loot is perfectly fine.

Yes, it's fine if it's in spec, my concern was that it might be producing large numbers of arms unintentionally since it represents such a drastic departure from the normal availability of high damage guns and ammunition - those two screenshots represent a cumulative damage potential of 186000, on par around 1420 rounds of .50 calibre ammunition. Given that outdoor turrets were drastically scaled back (eliminated?) to curtail the availability of high powered ammunition available on the world map, it stood to reason that this might be an oversight.

It's not intended to be a commentary on the design itself - I certainly didn't mind - just a clue that it might have been an unintended outlier.
