### ISSUE TITLE
Some relevant animals don't dissect into their respective samples

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#58587]
### Some of animals don't dissect into their respective samples

Ones I've found:

- Cerbearus - this one should dissect into ursine samples
- Mouse of NEMA (? I never seen this, only seen this in hitchhikers guide) should dissect into either rat or mouse sample
- DinoMod's dinos should probably dissect into raptor or lizard serums, although this would be greatly unbalanced due to sheer number of Dinos
- Owlbears should also probably dissect into Ursine samples
- Demon spiders should may be also dissect into Spider samples
I'll go through the creature list again in close future to compile a more complete list of those. 

### Solution you would like.

--

### Describe alternatives you have considered.

--

### Additional context

Some mutagens are significantly more annoying to obtain compared to the others based on rareness of creatures in question. While this might be an actual conscious decision for balance reasons, I still think that relevant mutants from every animal category should indeed drop the proper samples, may be with adjusted chances for balancing between relative "power" of various mutant categories.

**Comment by Maleclypse** [comment]
Dinomods dinos should dissect into the dinomod mutation (stego and Tyrant) lines plus raptor and lizard as makes sense.    You can set dissections to have multiple sample types so I would suggest Owlbear dissecting into both Ursine and Bear.   Nema should be like all the other ratkin and dissect into a chance at either mouse/rat sample.   Demonspiders would be good for both spider and manatouched.

**Comment by mkrutov** [comment]
(Ursine *is* Bear)

**Comment by PatrikLundell** [comment]
@mkrutov is correct, but I wonder if it was intended to say "Ursine and Bird"?

**Comment by mkrutov** [comment]
Going through jsons, on top of whats in issue description there're no samples currently for:

beaver, dambreaker, feaver

beaver - unsure
dambreaker - beast + what beaver got
feaver - bird + what beaver got


iridescent cat, iridescent kitten - Feline

grinning coyote, slavering coyote, dire wolf - lupine, beast(?)

spideer - ? spider, but its not a spider technically

mongrel - lupine

pig, boar - ? no idea

**Comment by LyleSY** [comment]
I thought about it for DinoMod, but the eggs are already usable as ingredients. I don't know about all dinos giving samples, but having the same dinos give samples as eggs makes sense. Also I'm now noticing that the tyrant list needs to updated, there's a lot more tyrannosaurids in the mod now.

**Comment by Maleclypse** [comment]
> @mkrutov is correct, but I wonder if it was intended to say "Ursine and Bird"?

Yes. Sorry Ursine and Bird.

**Comment by Maleclypse** [comment]
Spideer could do spider and cattle  because deer are related to cattle if I recall?

**Comment by LyleSY** [comment]
Thinking about this some more, I'm good with mosasaurus and the three pterosaurs dissecting to lizard samples, and the other dinos whose eggs now can be used for mutagen dissecting to their respective mutagen types. I don't think every dino/pterosaur/mosasaurus should dissect to every dino mutagen and lizard. If someone wants to make this PR. Also a sauropod mutation line would make a lot of sense if someone wants to do that.

**Comment by LyleSY** [comment]
The most important chunk of this for DinoMod should be complete at this point. The only remaining items at this time is to dissect mosasaurus and the pterosaurus into lizard samples. I may do that later but there are a lot of conflicting content priorities in DinoMod right now

**Comment by LyleSY** [comment]
I believe the DinoMod pieces of this are now complete
