### ISSUE TITLE
 DEBUG    : Missing item definition: ammonia   FUNCTION : const itype* Item_factory::find_template(const itype_id&) const  FILE     : src/item_factory.cpp  LINE     : 2327  VERSION  : eeef80f

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58586]
### Describe the bug

 DEBUG    : Missing item definition: ammonia

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 2327
 VERSION  : eeef80f

### Steps to reproduce

open saved game

### Expected behavior

no error

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: eeef80f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
@matt32106 Are you able to reproduce the issue?

I have created a new world, saved and loaded without issues. Please attach your save file.

- OS: Linux
    - OS Version: <unknown>
- Game Version: 765f442 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by matt32106** [comment]
> Please attach your save file.
Sorry did not generate save. If only the error routine generated it each time...

**Comment by estebandellasilva** [comment]
[Fentress.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8949788/Fentress.zip)
Error on load
Cannot siphon ammonia from vehicle tank
Crash if i select the tile in the car window where to tank with ammonia is placed -> unable to remove said tank

**Comment by TadhgEomonn** [comment]
I have seen these four different Debug messages while loading (mostly) or running the game.

 DEBUG    : Item ammonia was loaded with charges, but can not have any!

 FUNCTION : io
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\savegame_json.cpp
 LINE     : 2940
 VERSION  : 765f442

 DEBUG    : ammonia in inline_recipe_acidchitin_piece_wyrm is not a valid item template

 FUNCTION : check_consistency
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\requirements.cpp
 LINE     : 597
 VERSION  : 765f442

 DEBUG    : Missing item definition: ammonia

 FUNCTION : find_template
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 2327
 VERSION  : 765f442

 DEBUG    : ammonia in inline_recipe_acidchitin_piece_wyrm is not a valid item template

 FUNCTION : check_consistency
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\requirements.cpp
 LINE     : 597
 VERSION  : 765f442

**Comment by RoyBerube** [comment]
Ammonia has been replaced with two new chemicals in #57284. Unfortunately it did not migrate the old chemical in saves to the new chemical.

Here is a bash one-liner to update all the existing ammonia in a save to ammonia hydroxide. Sadly the amount has already been lost in the save file so this just gives 2 per container. The stuff is not all that useful anyway now, so not a big deal.

`grep -lr --exclude=*.{json,log} "ammonia" | xargs sed -i 's/"ammonia"/"ammonia_hydroxide"/g'`

Backup your save before running this. Run it in a bash shell in the save folder. Give it some time to complete. Loading errors no more.

**Comment by hexagonrecursion** [comment]
> [Fentress.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8949788/Fentress.zip) Error on load Cannot siphon ammonia from vehicle tank Crash if i select the tile in the car window where to tank with ammonia is placed -> unable to remove said tank

Huge thanks to @estebandellasilva for sharing the save file.

I was successfully able to reproduce the bug.


 DEBUG    : Missing item definition: ammonia

 FUNCTION : `const itype* Item_factory::find_template(const itype_id&) const`
 FILE     : src/item_factory.cpp
 LINE     : 2327
 VERSION  : f16a8c2
