### ISSUE TITLE
Object creator, but for loot groups

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#58597]
### Is your feature request related to a problem? Please describe.

I feel making loot groups as most boring part of mapmaking - you need to manually search almost each item or loot group to put it on exact group

### Solution you would like.

Making a tool, similar to "Object creator", but for loot groups, which can not only make a ready to use json blocks, but also work as useful tool for experienced creator
So, it need to parse the /json/items and /json/itemgroups. For items it will contain the item's id, name, type and, maybe, some additional info - the description, weight, volume, price, comments etc. For groups it will parse the id, list of entities with weights and the comment. The search menu allow to hide/sort entities by some rules. Picking the item or group will add it to batch menu, where you can tweak it weight.

Mostly its tool not for making json, but to make mapper work easier, allowing him to not search each item manually for each time

### Describe alternatives you have considered.

Not making it
Ask some mappers what they want to see in such tool

### Additional context

kinda idea
![image](https://user-images.githubusercontent.com/67688115/174797469-92072c9b-fcd1-4a41-be8b-5deac0d7b014.png)

**Comment by snipercup** [comment]
I'm going to work on this. It will take time though.
