### ISSUE TITLE
Sclrerotin plate: wearing any clothing causes uncomfortable status effect forever

### ISSUE THREAD

**Issue by irisanuwu** [CleverRaven/Cataclysm-DDA#58596]
### Describe the bug

What it says in the title. What's interesting is that it causes uncomfortable across your entire body (including your head), even if you put clothing that only affects a select bodypart, like a jacket for example. This is related to mutation Epiticule, since having it doesn't cause this issue. The fact that you can find yourself in a situation without epiticule but with sclerotin plate is strange.

### Steps to reproduce

1. Make your character mutate sclernonin plate while not wearing any clothing
2. Open character menu to see that they are comfortable
3. Wear any article of clothing
4. Take it off
5. Open character menu again to see that every body part is now uncomfortable forever

### Expected behavior

I expected that soft clothing wouldnt make me uncomfortable and when it did, I expected that taking it off will remove the status effect

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.348 (21H2)
- Game Version: f80cdc8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by fairyarmadillo** [comment]
![image](https://user-images.githubusercontent.com/94415528/174896327-58603ab7-4be5-4fc0-a787-5dbfe0089ad8.png)

Mutant here shown with Epicuticle (mandatory for Sclerotin Plate) and a full set of clothing, zero discomfort. Since there's no way to get Sclerotin Plate without Epicuticle I think we're good.

**Comment by descan** [comment]
I think that they said "The fact that you can find yourself in a situation without epiticule but with scleronin plate is strange," implies that they didn't debug it in and did, somehow, manage to get the plate without the epic cuticle. Which would be the bug here, assuming that's correct, because as you said it shouldn't be possible.

**Comment by irisanuwu** [comment]
i guess this is an overlapping issue with the current mutation system. i used a purifier in my playthrough several times so my only guess is that it chose to purify the tier 1 spider skin mutation and keeping the tier 2 and tier 3 instead of going back in order they were mutated. i guess this bug report has strayed in a different direction than the issue i had originally but here you go

**Comment by irisanuwu** [comment]
![image](https://user-images.githubusercontent.com/106341934/174914772-eb738a94-6b00-4fbd-ba64-c6f7b0017c32.png)
sure enough, i reproduced it. eyes on the log. does this constitute opening a new bug report?

**Comment by fairyarmadillo** [comment]
> ![image](https://user-images.githubusercontent.com/106341934/174914772-eb738a94-6b00-4fbd-ba64-c6f7b0017c32.png) sure enough, i reproduced it. eyes on the log. does this constitute opening a new bug report better representative of the issue?

Yeah, you shouldn't be able to purify off prerequisite mutations without losing the later ones first. That is definitely a bug and something I'd open a new report for.
