### ISSUE TITLE
Merchants can only use shelves/storage space for sale, not buying

### ISSUE THREAD

**Issue by Delightful-Beet** [CleverRaven/Cataclysm-DDA#58604]
### Describe the bug

Smokes will only accept items that either fit in his pockets or are themselves wearable. While he
will happily trade items _from_ his shelves, any free space there is unavailable for items the
player wishes to give him. 

Unaccepted items trigger the message "Smokes, Merchant doesn't have the appropriate pockets to
accept that.". This is frustrating because the trade screen shows him selling from his shelves,
chair and floor, but no explanation is given for why incoming stuff can't go there as well.
Absurdly, the player can buy items, immediately try to give them back and be told there's no space.

As a side note, the "available weight/volume" stat in the trade screen only changes if the player
buys items Smokes carries on himself, or gives him something he chooses to carry. Storage is ignored
entirely.

Presumably this applies to all merchants with storage.

### Steps to reproduce

Using the provided save:

1. Talk to Smokes and initiate trade.
2. Attempt to trade your golf bag for nothing. Decline the deal, but note that Smokes has space for
   it ("Looks like a deal!").
3. Unmark the bag and offer the (much smaller) grenade inside it instead. Smokes now "has no
   appropriate pockets".
4. Unmark grenade, trade your Kevlar vest for the stack of 38 planks (then spam "drop item" a lot.
   Sorry). 
5. Initiate a new trade.
6. Attempt to trade your grenade for nothing again. Even with all the space you just freed, Smokes
   still complains about pockets.
7. Attempt to trade just one of the planks you bought back to Smokes for nothing (easiest way is to
   use the one you should be wielding). Smokes can't put it back where it came from.

Any non-wearable item larger than what the free volume/weight stats state triggers the pockets
message.

### Expected behavior

Smokes should accept as many goods as his store will fit, or at least his shelves. He should not
effectively "lose" space when he trades large items for smaller ones. 

The free weight/volume display should include storage space if the merchant has any.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: d69f563 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Save file: [Colgate.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8952240/Colgate.zip)

**Comment by andrei8l** [comment]
There's a specific check for this but the Smokes in your save lost his `NPC_MISSION_SHOPKEEP` mission for some reason (he's doing `NPC_MISSION_GUARD` now).

Probably can't do anything here before #56990 is addressed.
