### ISSUE TITLE
Wasps able to hit player while player cannot hit them back due to XY mismatch

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#58601]
### Describe the bug

Giant wasps very often fly on the higher Z-level and attack the player from above. However when they do this they are misalligned, as they can hit the player from 1 tile diagonally or horizontally while the player can only hit from directly below a target. I assume this affects more than just wasps but they are the most common example.

in addition, the player cannot see wasps that are on a higher z-level, unlike with lower z-levels. This allows wasps to "sneak up" on the player if you're not constantly changing to the higher z-view when wasps are around since you can't normally see where they are.

Note in the screenshots how the wasp is a tile away from me in addition to above and can hit me while when I press TAB the game simply tells me no enemies are nearby. The solution is to step underneath the wasp obviously but it's very annoying that this has to happen at all.

### Steps to reproduce

1. Find wasps in the city.
2. Get attacked by wasps.
3. Observe wasps attacking from the wrong coordinate.

### Expected behavior

Wasps should only be able to attack from directly above the player since they do not have reach. 

### Screenshots

![wasp1](https://user-images.githubusercontent.com/56016372/174830919-4399035e-d624-477f-b947-fbe60bf53d5d.PNG)
![wasp2](https://user-images.githubusercontent.com/56016372/174830933-410d3016-aecd-4b9b-b82c-86092d6572c6.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 7ff3302 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by hexagonrecursion** [comment]
/confirmed I was unable to attack a wasp guard with a katana from 1 z level below and diagonally, but the guard was able to attack me.

I was **able** to hit the guard from 1 z level below from a vertically or horizontally adjacent tile.

/confirmed There is no indication that a wasp is near on the main screen or minimap in the tiles version.

The wasp guard does show up in the list of monsters above the minimap, but the monster direction indicator (NW, North, NE, ...) does not show where it is.

The wasp guard does trigger safe mode.

You should have mentioned that reproducing this requires enabling experimental 3d field of vision.


- OS: Linux
    - OS Version: <unknown>
- Game Version: f16a8c2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
