### ISSUE TITLE
Vehicle in attached save is unable to be refilled - vehicle not found

### ISSUE THREAD

**Issue by MoocowTG** [CleverRaven/Cataclysm-DDA#58616]
### Describe the bug

Any attempt to siphon from another vehicle or refill from a gas station of the police car in the save will fail with a vehicle not found error message.

### Steps to reproduce

Attempt to refill the vehicle through any means

### Expected behavior

Vehicle gets refilled

### Versions and configuration

Win 10

Using build from June 20, 2022

Running Aftershock

### Additional context

[Vinita_tankfill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8955311/Vinita_tankfill.zip)

**Comment by PatrikLundell** [comment]
/confirmed

It can be noted that the mod list is incomplete, which may or may not be relevant.
