### ISSUE TITLE
Crash while attaching modified forward grip

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58638]
### Describe the bug

When attaching a modified forward grip to the RM232, while the grip is wielded, a crash to desktop can be consistently triggered by selecting the option "store in inventory" went prompted to do so. The crash is not evident when attaching the grip while it is not being held.

This action is being undertaken with the following inventory items with available pockets:

* Breacher Load Bearing Vest
* Military heavy rucksack
* Army pants
* US ballistic vest

No unusual circumstances, such as overfull pockets or modified storage items, exists.

### Steps to reproduce

1) Hold the modified forward grip
2) Use the activate function to attach it to a pistol (perhaps other weapons as well)
3) The game will then attempt the wield the weapon being modified and query what to do with the wielded modified forward grip. When prompted, select the option to store the forward grip in the inventory. Do not use more specific options such as choosing to store the grip in a specific bag, holster, or pocket.

### Expected behavior

The game should successfully store the item and proceed with the modification.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: cc694a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed Segmentation fault (core dumped)

unfortunately there was no config/debug.log or config/crash.log

- OS: Linux
    - OS Version: <unknown>
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ilurker** [comment]
Solved via #58915
