### ISSUE TITLE
Way Too Many Dermatik Nests

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#58634]
### Describe the bug

I've been doing random today and it at least too me feels that the "Mound Of Dirt" overmap is way too abundant.

### Steps to reproduce

Check some overworlds and see how over represented it is

### Expected behavior

I would expect there to be less already formed giant bug nests on day 1 of the cataclysm

### Screenshots

![image](https://user-images.githubusercontent.com/4514073/175113739-5b1b570d-1f78-4fd6-a27d-d41bd0721b30.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: d046929 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Venera3** [comment]
They're 0 - 3 per OM, the same as the other "minor" mob lairs - scout towers and shipwrecks. Not that I wouldn't adore a way to spawn them dynamically as time goes by, mind.

How common they get will also depend on world settings slightly: they have a 20 OMT min city distance and unrestricted max distance, so they'll fill large stretches of wilderness (not a lot of locations competing for the 40+ city distance parts of the map).
