### ISSUE TITLE
Disassembly of stacks (bullets) no longer checks the actual amount

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#58632]
### Describe the bug

If you disassemble ammo (maybe other items which can be disassembled in stacks) you can type in the amount of items higher that you have (which you could always)

The game currently does not check if you actually have that amount.
[Fentress.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8960173/Fentress.zip)

### Steps to reproduce

Get some ammo
Disassemble that ammo 
Type an amount far greater than what you have in
Get resources for the amount you typed in not for the amount you had

### Expected behavior

Disassembly checked the actual amount before - this was changed recently

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/175102257-fc4543e1-bd5c-4bc9-8f9f-c76ac375ad53.png)
![image](https://user-images.githubusercontent.com/89189872/175102317-404801a3-6cfa-405f-9f2f-fbb0c9306d39.png)
![image](https://user-images.githubusercontent.com/89189872/175102371-1ef4748e-fca4-413c-bc09-1c9796e94dce.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1766 (20H2)
- Game Version: 92acd0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by andrei8l** [comment]
/confirmed
```diff
diff --git a/src/crafting.cpp b/src/crafting.cpp
index dbc380503f..27be067e09 100644
--- a/src/crafting.cpp
+++ b/src/crafting.cpp
@@ -2403,6 +2403,7 @@ bool Character::disassemble( item_location target, bool interactive, bool disass
                     add_msg( _( "Never mind." ) );
                     return false;
                 }
+                num_dis = std::min( num_dis, obj.charges );
             } else {
                 num_dis = obj.charges;
             }
@@ -2519,6 +2520,7 @@ void Character::complete_disassemble( item_location target )
                 activity.set_to_null();
                 return;
             }
+            num_dis = std::min( num_dis, obj.charges );
         } else {
             num_dis = obj.charges;
         }
```
