### ISSUE TITLE
Eyebots

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#58631]
### Is your feature request related to a problem? Please describe.

Eyebots are super problematic. They materialize out of thin air whenever an alarm sounds and then materialize police bots out of thin air whenever the player steps nearby. Not the zombies though! An eyebot can be surrounded on all sides by zombies trying to kill it and it will do absolutely nothing about it, but if you step nearby while this is happening it will take your picture and call the popos. 

All these things combined with the fact that their perpetual operation is entirely handwaved by "charging ports must exist somewhere" yet no matter how hard the player looks they cannot find these charging ports which apparently exist. They also continue to spawn as the cataclysm progresses despite the fact that no one is making more, and their collective supply of police bots is similarly infinite.  

Even worse is that they only start spawning in response to your interaction in the world - there are no pre existing eyebots floating around from doors that got busted open and windows that got smashed either. There are times in cataclysm where it's obvious the world didn't exist until you were there to see it and eyebots are one of those.

### Solution you would like.

There are so many. 

Stop spawning eyebots in response to alarms, they almost certainly all got deployed already. Have eyebots floating around as rare spawns in cities or as broken corpses from ones that were already destroyed.

Eyebots call the police on zombies too, not just the player - or they don't call the police at all and just take pictures and make noise. Either way the fact that they differentiate zombies, ferals and the player character is absolute nonsense.

Make eyebots not immune to zombies. They don't take damage from almost anything other than an axe feral. They're supposed to just be a quadcopter, that level of armor plating is preposterous and they should be taken out as soon as something takes a swipe at them or throws a rock at them - anyone who has flown a quadcopter can attest to how ridiculously fragile those things are. Presently you can use eyebots as a distraction to attract swarms of zombies who crowd around it unable to damage it. This problem also affects riot turrets and grocery bots but that's a tangential issue.

### Describe alternatives you have considered.

Remove eyebots entirely. Alarms attracting zombies is already *fine* as a penalty to encourage lockpicking and eyebots themselves are another leftover Fallout reference that doesn't really need to be here.

**Comment by PatrikLundell** [comment]
I fully agree eyebots should act the same towards zombies and ferals as toward the player, and also that they should be depleted and actually have recharging centers that can be taken out (with some useful loot in them). It's not completely true that the player is the only thing summoning them, though, as I've had these nuisances show up in response to zombie triggered alarms (and they'll still "arrest" you when you get close to them, despite you not having had anything to do with any "crime" anywhere in the vicinity as you haven't yet reached the looting phase).

Lock picking is actually discouraged as alarms are frequently triggered by successful lock picking... It's better to look for an open window and open the front door from the inside when possible.

I won't shed a tear if eyebots are removed completely, however.

**Comment by RAldrich** [comment]
Another option that could help and keeps technology in line with "current day" - replace eyebots with wheeled version, and limit their spawn to labs or other similar high tech / corporate facilities. Maybe have a civilian version that just follows you and makes a shit ton of noise, and a military / lab version that can summon reinforcement.

Existing riot and police bots could be re-purposed for use in police and roadblock map locations (or just removed, given the current trend towards more real world tech and the way cybernetics are being moved to the Exodii)
