### ISSUE TITLE
Research in Innawood

### ISSUE THREAD

**Issue by Light-Wave** [CleverRaven/Cataclysm-DDA#58633]
### Is your feature request related to a problem? Please describe.

It has been suggested that instead of using autolearn to get recipes in Innawood, it would make sense to gain recipes through research projects instead. Here, I will try to structure and organize how that might be done. I might have accidentally put an item that is autolearned in mainline under a research project here. If so that is a mistake and it should stay autolearned.

Feedback is welcome.

### Solution you would like.

The recipes that are in Innawood, and what research project we could put them under are below. Note that tech tree structure and research project names are WIP.

- **Stay autolearned**
  - Bronze nails
  - prac_mechanics
  - prac_cutting_beg
  - prac_bashing_beg
  - prac_stabbing_beg
  - prac_knitting
  - sword_wood
  - 2byarm_guard
  - honeydew
  - chemistry_set_basic
  - chemistry_set
  - duct_tape
  - tailors_kit
  - training_dummy_light
  - sewing_kit
  - metalworking_tongs (alternative recipe takes steel lumps instead of nail)
  - metal_file (alternative recipe takes steel lump instead of scrap metal)
  - blacksmith_kit
- **earth-related chemistry**
  - material_quicklime
  - material_cement
  - mortar_build
- **Glassworking**
  - glass_shard
  - glass_tinted
  - goggles_welding
  - jar_3l_glass_sealed
  - bottle_glass
  - jar_glass_sealed
  - flask_glass
  - test_tube
- **Laboratory glassware** (require glassworking and perhaps some chemistry skill)
  - funnel_separation
  - still_lab
  - thermometer
- **Basic tailoring**
  - sheet_fibercloth
  - sheet_fibercloth (from spinningwheel)
- **Chemical study on chitin**
  - plastic_chunk (from chitin)
- **utility smithing**
  - pilot_light
  - water_faucet
  - well_pump
  - pipe_cleaner (also in utility gunsmithing)
- **makeshift electronics**
  - makeshift_transformer
  - vehicle_controls
  - electronics_controls
  - battery_charger
  - light_minus_disposable_cell
  - light_disposable_cell
  - medium_disposable_cell
  - heavy_disposable_cell
  - battery_car_clay
  - light_bulb
  - welder_crude (required to progress, so should be available early)
  - soldering_iron (required to progress, so should be available early)
  - hotplate
  - reading_light
- **Electrical appliances** (Requires utility smithing and makeshift electronics)
  - motor_micro
  - motor_tiny
  - motor_small
  - vac_pump
  - drivebelt_makeshift (for vac_pump)
  - kitchen_unit
  - condensor_coil
  - evaporator_coil
  - filter_air_makeshift
  - water_purifier
  - coffeemaker
  - dehydrator
  - makeshift_sealer
  - makeshift_vacuum_mold
  - food_processor
  - electric_lantern
  - flashlight
  - floodlight
  - directed_floodlight
  - car_headlight
  - car_wide_headlight
  - wearable_light
  - survivor_light
- **Bronzesmithing** (Or perhaps keep these autolearend to stay in tune with mainline?)
    - sword_xiphos
    - brush_axe
    - spear_dory
    - button_bronze
    - bronze_axe
    - bronze_hoe
    - bronze_sickle
    - bronze_pickaxe
    - bronze_shears
    - bronze_knife
- **Weaponsmithing**
  - pike
  - xacto (X-Acto knife)
- **Metal machinery**
  - steam_watts_small
  - jack
  - jack_makeshift
  - jack_small
- **Gunsmithing** (requires utility smithing and Metal machinery)
  - rifle_flintlock
  - longrifle_flintlock
  - carbine_flintlock
  - pistol_flintlock
  - carbine_flintlock_double
  - cannon_3in_ordnance
  - pipe_cleaner (also in utility smithing)
- **Fletching** 
  - hand_crossbow
  - crossbow
  - compositecrossbow
  - bullet_crossbow
- **Cooking with milk**
  - brew_milk_curdled
  - raw_butter
  - raw_butter (shake)
  - cheese_hard
- **Brewing**
  - brew_whiskey
  - brew_gin
  - brew_rum
  - brew_moonshine
  - brew_hb_seltzer
  - brew_moonshine (pumpkin)
  - brew_moonshine (forage)
  - brew_fruit_wine
  - brew_hb_beer
  - brew_mead
  - brew_dandelion_wine
  - brew_burdock_wine
  - brew_pine_wine
  - malting_grain
  - soaking_dandelion
  - brew_vinegar
  - gin
  - vodka
  - rum
  - whiskey
  - moonshine
- **Organic chemistry**
  - chem_ethanol
  - chem_ethanol (slow distill)
  - methed_alcohol
  - biodiesel
  - primitive lamp oil (should probably be added)
  - rubber_cement
  - rubber_cement (by hand)
- **Survival herb use** (or keep autolearn)
  - tea_willowbark
  - cattail_jelly
  - bandages_birchbark
  - bandages_birchbark_adv
  - dahlia_baked
  - burdock_cooked
  - burdock_fried
  - dandelionburdock_fried
  - pine_tea
  - dandelion_tea
  - dandelionburdock_tea
  - chicory_coffee
  - chamomile_tea
  - lotus_tea
  - spurge_tea
  - coffee_raw_kentucky
  - tea_bark
- **Simple chemistry**
  - ammonia_hydroxide
  - oxy_powder
  - chem_muriatic_acid
  - chem_muriatic_acid (by electrolysis)
  - chem_black_powder
  - chem_black_powder (generic)
  - bleach
  - (remove oxy_powder duplicate recipe)
  - latex
  - chunk_rubber
  - formic_acid
- **Simple cooking**
  - blood_pancakes
  - blood_pancakes_wheat_free
  - soup_blood
  - soup_blood_wheat_free
  - blutwurst_sausage
  - hardtack
  - sausage_casings
  - sausage
  - sausage_raw
  - sweet_sausage
  - ghee
  - offal_pickled
  - offal_pickled (jared 3l)
  - fried_brain
  - grilled_sweetbread
  - seasoning_italian
  - pie
  - pie_veggy
  - pie_meat
  - humble_pie
  - veggy_pickled
  - sauerkraut_ferment
  - pickles_ferment
  - eggs_ferment
  - meat_pickled
  - fish_pickled
  - jam_fruit
  - fish_pickled
  - meat_pickled
  - veggy_pickled
  - meatball_raw
  - bread
- Basic carpentry
  - yoke_harness
  - still

### Describe alternatives you have considered.

- Keep things autolearned
- Put the research system into mainline instead of this mod.

**Comment by Light-Wave** [comment]
Tagging @Maleclypse since they did some thinking regarding this in PR #58614 and might want to weigh in on this more.

**Comment by PatrikLundell** [comment]
I think it would make sense for the core to make use of an experiment/research system rather than auto learn for most items if a robust system is implemented. Innawoods would then "just" tweak things such that some things that core would require a book for would be reachable via experiments in Innawoods (and many current book only recipes in core ought to be reachable via experimentation in addition to the book approach).

**Comment by RenechCDDA** [comment]
@Light-Wave Do you want this un-staled and kept open? I can slap a label on it.

**Comment by Light-Wave** [comment]
Nah, it can stay closed.
