### ISSUE TITLE
`npc::starting_weapon` doesn't spawn a weapon if the npc has the wrong skillset

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#58648]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/e34eeaacc7a51fe8bb1798d662bee648749a70c1/src/npc.cpp#L1190-L1211

The best skill here can be any skill with the the `combat_skill` tag, but this doesn't check for `melee`, `marksmanship`, `launchers`, `dodging` or `unarmed` and thus will spawn no weapon. Moving the check for `stabbing` to a default else case as the comment suggests was intended would mostly solve it but feel wrong for some of these skills.

### Steps to reproduce

Spawn some random npcs and look at skills and weapons I guess.

### Expected behavior

The method should probably always create a weapon, maybe excluding `unarmed` as the best skill. If npcs without a weapon are intended, it should probably be handled before calling this method (in `npc::randomize`).

### Versions and configuration

9d30272dfe8c326d228782e4670dd2684cafd41e

**Comment by I-am-Erk** [comment]
It should be pretty straightforward to just have the marksman/melee/dodge/launcher/unarmed skills excluded from checking which is `best`, and then also give a default as an error trap if it all falls apart.
