### ISSUE TITLE
Military Bunkers spawning with enormous volumes of low-capacity magazines

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58657]
### Describe the bug

Military bunkers currently spawn with literally thousands of low-volume magazine types, especially 10 round 5.56 clips, each packed in mini containers. This poses a significant usability problem as the time associated with unpacking each of these thousands of clips individually represents tens of hours of game time, several hours of human time, and perhaps over 20,000 keystrokes (assuming 3-4 keystrokes per unload command). The sheer volume of magazines, when combined with the boxes and other items such as loose ammunition and MREs, also poses a major performance issue, as the cumulative impact of the ~0.5-1 second delay while the list of thousands of candidates to unload sum to an hour or more over thousands of unload actions, as well as a moderate engine issue, as tiles easily exceed the 4096 maximum item limit due to the combination of thousands of clips and thousands of small boxes.

### Steps to reproduce

1) Spawn a military bunker
2) Loot it

### Expected behavior

A more realistic mix of clip sizes and storage methods should be utilized, with a good mix of loose ammunition, empty clips, stocked clips and magazines of various sizes instead of the current domination of 10-round clips. A bit of research shows that most military ammunition is stored in larger ammunition cans, not in thousands of pre-loaded clips. Reworking the spawn table to replace the majority of 10 round clips with nested small ammunition boxes within larger cans would improve the problem from both a usability and realism perspective.

Clips should be coded to load properly - testing on magazines shows that only a single 10-round clip can be loaded into a magazine before they cease to be recognized as a valid source of ammunition for reloading. This fix would cut down on the need to unload each clip as they would serve a valid function in their loaded state.

Alternately, the ability, via zones or a multi-select capability, to unload multiple items at once would go a long way to rendering situations like this usable.

### Screenshots

![image](https://user-images.githubusercontent.com/104868222/175389312-4e53782e-b11e-4f0f-8615-df054e162096.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ilurker** [comment]
@GuardianDll I believe the reworking the spawns of military ammo was your baby, so I'm tagging you in here.

**Comment by Inglonias** [comment]
I visited both military outposts and both flavors of military bunker. I did not see the thousands of magazines you mentioned. Can you tell us what the ID of the location you found this is? Or just give us a screenshot of it so we can identify it?

**Comment by Ilurker** [comment]
I'm not entirely sure how to find the proper ID of the location 

> I visited a military outpost and both flavors of military bunker. I did not see the thousands of magazines you mentioned. Can you tell us what the ID of the location you found this is? Or just give us a screenshot of it so we can identify it?

The id is military_bunker (ie the one with six rooms containing nothing but shelving). I would check that we're using the same version of the game as I understand the PR behind this was merged fairly recently.

The screenshot attached shows the magazine balance post-unloading of all the boxes, here's another pair to give you an idea of the sheer mass of 10-round clips (each packaged three to a box) and containers. I had unloaded several hundred magazines and a few dozen partial ammo belts at the time of the screenshot.

![image](https://user-images.githubusercontent.com/104868222/175395131-838884db-f249-431a-bf90-4bc6c87e3b67.png)

![image](https://user-images.githubusercontent.com/104868222/175395353-c77c2457-16fe-434c-a8c0-51decfabc10d.png)

**Comment by GuardianDll** [comment]
@Ilurker yes, i did it, and its based on real military supplies with ammo ([Here is an example](https://youtu.be/XPahdicCr4w)
And its not magazines, its stripper clips, they are similar to speedloaders, so the idea was "you can load 10 round in mag at once" (it can be not so useful now, but i believe it cool enough even now, and will be useful in the future"
But ammo clips doesn't work right, thats true, and i write about this already (#58359) (i also write to not merge the pr before it will be fixed but, well, i guess kevin oversight it 🤷)

**Comment by mkrutov** [comment]
So several things.

1) I'd confirm this bug if I'd have privileges to do so: visit to single military outpost with 1x loot results in >300 10-round clips

2) however, those 10-round clips could be used directly to reload STANAG magazines

3) however, that is somewhat bugged, see #58658

**Comment by Ilurker** [comment]
10 round stripper clips are definitely in use, but I don't believe that ammunition is stored in that state - rather it's stored and distributed in boxes and loaded by soldiers as needed, since you don't need the extra weight and expense of thousands upon thousands of reusable stripper clips.

**Comment by GuardianDll** [comment]
> extra weight

Few grams for each clip, like 150 gram of additional weight, enough price for soldier that can spend more time to rest than for reloading a gun

> reusable

Well, they can be reused, but in army they are one-off

**Comment by GuardianDll** [comment]
Oh, btw
/confirmed.

**Comment by GuardianDll** [comment]
And btw, there is a fat-50 ammo cans with bare ammo, without clips, so we can tweak it for a bit
And also remember, its a **military bunker**, its like designed to store a lot of reserves

**Comment by Ilurker** [comment]
This is what I was referring to:

https://www.midwayusa.com/product/1002002047
https://www.midwayusa.com/product/100188288
https://www.sportsmansguide.com/product/index/pmc-x-tac-m855-green-tip-556x45mm-nato-fmj-62-grain-120-rounds-in-a-battle-pack?a=1724854
https://www.reddit.com/r/gundeals/comments/pvv0pk/ammo_50cpr_swiss_556x45_62_gr_ss109_penetrator_on/

Apparently I was quite mistaken and the US is a bit of an outlier among NATO countries in how they handle ammunition (I grew up on a non-US military base so there was a bit of misplaced confidence there).

That said, this still represents a huge performance/usability problem right now due to how the game handles ammunition vs discreet magazines (I know they're clips, but from a code perspective they're magazines).

**Comment by GuardianDll** [comment]
Well thats true, i understand it, but i guess we need to summon someone that can describe the best way here

**Comment by Inglonias** [comment]
I spawned three more military bunkers and was still not able to find the thousands of magazines mentioned here. I am using the same version of the game as Ilurker.

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

![image](https://user-images.githubusercontent.com/2125926/175400272-d533e32f-3024-4eac-9d01-a951d89931a7.png)
![image](https://user-images.githubusercontent.com/2125926/175400299-0632403b-fe11-453d-a6bf-604d20c0af4e.png)

**Comment by Ilurker** [comment]
@Inglonias Are you taking the time to open up the nested containers? The strippers are nested, 3 to a box, within a few thousand small boxes, which I believe are themselves within a much smaller number of large boxes.

**Comment by Inglonias** [comment]
I did. I'm not finding the stripper clips you are. I am finding dozens of mini ammo boxes, which, yes, would be a pain to unload without keyboard macros, but I didn't find any blackout stripper clips.

It's not that I don't believe you. I'm probably doing something wrong.

My suggestion would be to stop storing the ammo inside the nested containers, and just keep the ammo stored separately, even if it's not realistic, just to keep the number of keystrokes down.

**Comment by Ilurker** [comment]
The box unloading itself wasn't too bad, since as you said, it can be automated (though huge numbers of items highlights some weirdness with the way the game handles these actions as it did take ~16 hours). The real issue arises with the 20,000+ keystrokes to unload all the clips those boxes were containing, since you can't automate or batch-process them at all.

That's why I gave three possible routes to resolve the issue this poses - remove the clips until they work, get the clips working as intended, or allow some sort of batch unload functionality to render it moot. It's completely realistic that my character would have to spend a day or even longer unloading all of that, it's just not very good that I've been running a keyboard macro automating the unloading process since about 10 minutes before I made this bug report and it's still going!

**Comment by Inglonias** [comment]
Yep. Ok. Fair enough.

**Comment by RAldrich** [comment]
I don't want to derail this issue, but nested containers are currently a pretty janky UX in general. Similar problems arise with MREs. I don't have profiler data, but I suspect they're not great for performance either.

The closest we have to a batch operation right now seems to be use of an "unload containers" zone. That will at least let you pile up everything and unload one layer of nesting per "sort" operation. But some sort of recursive unload command might be helpful.

I've been writing up an issue having to do with MREs and (sealed) nested containers - I'll save the rest of this diversion and post it there.

**Comment by chrispikula** [comment]
> The real issue arises with the 20,000+ keystrokes to unload all the clips those boxes were containing, since you can't automate or batch-process them at all.

If you've got the clips in inventory, you can filter '/' for just the ammo, and then dump it on the ground or into a storage.  

Or, alternatively, if you've got a 100L drum, hold it, and 'insert' (or maybe refill? I forget) into it while standing above a pile of stuff, and then just filter away the bullet holding things.

**Comment by Ilurker** [comment]
That method actually doesn't work in experimental - it was suggested by a few people. I tried several different variations just to be sure.

A PR's in the works to extend unloading to magazines, which should resolve the issue.

**Comment by chrispikula** [comment]
Huh, yeah, wasn't expecting that update from experimental.  C'est la vie, I guess.  At least they still work for MRE's, and unload still works on mags, but, yeah, that's s silly number of key presses.  :-/

**Comment by Inglonias** [comment]
Is #58661 sufficient to close this one?

**Comment by Ilurker** [comment]
I think it's a fair enough solution!
