### ISSUE TITLE
Basement Bugs

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#58660]
### Is your feature request related to a problem? Please describe.

Cockroaches are currently flagged to be neutral with zombies. This has been explained by the cockroaches not seeing live zombies as worthwhile food sources and the zombies considering them to be too low priority to bother with as they're small, ubiquitous, and hard to catch.

### Solution you would like.

I think it would be best if they switched to by_mood and could sometimes provoke attack:

Cockroaches should avoid zombies unless the zombie is very injured.

Cockroaches should eat corpses (zombie or human) in the same way that deer eat crops. Each "bite" would damage the corpse, eventually pulping and even destroying it. 

Cockroaches should be able to hide under furniture. They're big, but they have relatively flat bodies and can squash themselves quite a bit.

This way, a roach basement with a few zombies in it might seem OK until you killed the zombies, then a swarm of roaches would come out from under all the couches to feast on you and the dead zeds.

### Describe alternatives you have considered.

Leaving them as is. They make enough sense as is, but more granular interactions with their surroundings would be cool.

### Additional context

Some of this could also be applied to other animals. Spiders, flies, crows, coyotes, and rats could all use some of these mechanics. Anything that opportunistically eats zombie meat or skitters underfoot, really.

**Comment by anoobindisguise** [comment]
Also, generic cockroaches are mindlessly aggressive against the player, while skittering plagues (the more mutated ones?) seemingly refuse to attack the player and flee on sight, not sure what's up with that inconsistency.

**Comment by anothersimulacrum** [comment]
No longer the case, see https://github.com/CleverRaven/Cataclysm-DDA/pull/60605
