### ISSUE TITLE
JSON Sidebar regression - Allow widgets to change their widget_var through clauses and conditions

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#58684]
### Is your feature request related to a problem? Please describe.

There is one remaining known regression relating to the replacement of hardcoded sidebars with their JSON counterparts, and it's that widgets cannot be set up to conditionally display more than one widget_var based on conditions.

### Solution you would like.

A new field for `widget_clause` that allows it to override the `var` field of its parent `widget` when certain conditions are met.

### Describe alternatives you have considered.

This is only used in two places in the hard-coded sidebars that I know of. The first is in the case of broken limbs, as stated previously. The second is probably not something we should reintroduce, and it's the fact that the classic sidebar replaced certain widgets in the health section with vehicle widgets when you were inside of a vehicle.

**Comment by vetall812** [comment]
I think this is unnecessary now. As we can just swap out whole widgets
