### ISSUE TITLE
Infrared vision does not obey FoV restrictions

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58682]
### Describe the bug

Infrared goggles, when worn, ignore the FoV restrictions associated with the use of weapon scopes. This allows players unrestricted 360 vision even while at maximum aim level and negates a large portion of the penalty associated with high powered scopes.

### Steps to reproduce

1) Equip and activate infrared goggles
2) Apply a high-FoV restriction attachment to a firearm, such as a rifle scope
3) Aim away from an otherwise visible creature, such that the FoV cone does not cover them, while positioned far enough away from the creature that they would not otherwise be visible by the limited peripheral vision available.

### Expected behavior

The FoV cone would apply to the infrared goggles as well.

### Screenshots

![image](https://user-images.githubusercontent.com/104868222/175576146-70bb7773-c25d-4f1e-b4a5-ae7900b4b00f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I am sorry, but I could not reproduce the bug: there are **no** field of view restrictions **regardless** of whether I am wearing the goggles or not. I have tested this with AR-15 (id: ar15) and rifle scope (id: rifle_scope)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ilurker** [comment]
FoV restrictions are a limitation of certain sights, like scopes, which trigger during the aiming process in experimental. I believe #53180 and #53106 is what implemented it, but I could be incorrect.

**Comment by hexagonrecursion** [comment]
/confirmed

It turns out that the field of view restriction only applies after I spend some time aiming.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
