### ISSUE TITLE
Food spawns (hot) for no apparent reason

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#58699]
### Describe the bug

Food is spawning in the (hot) state when newly formed in odd situations.

### Steps to reproduce
Go to a microlab. Look at most food items and some chemicals.

### Expected behavior

My food does not get hot for no reason

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/175753759-456e0582-19e9-4226-bc57-15b0ea860943.png)
![image](https://user-images.githubusercontent.com/2125926/175779218-7c0e7bc3-6678-4de6-b1a0-a7477f6c2249.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 0.F-9359-g7139f9caf5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

I have seen some food in other places also heat up for no reason recently. Not sure what's happening here.

**Comment by BrettDong** [comment]
Could you attach your save?

**Comment by Inglonias** [comment]
Well, I would, but unfortunately the bug seems to have vanished. I'll close this until it reoccurs.

**Comment by Inglonias** [comment]
@BrettDong It looks like food in this microlab spawned in the (hot) state.
[Apollo.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8984967/Apollo.zip)

**Comment by descan** [comment]
I've been noticing this when spawning as a Squatter - all the protein rations have been (hot), and more importantly, all the water in the basement toilets were (hot) enough to be turned into clean water.

It also happened in a megacity I was trying out yesterday as well, quite a lot of foods were spawning as (hot) as well as some chemicals (bleach, I think?) although I'm less sure of my memory regarding non-food spawns.

**Comment by estebandellasilva** [comment]
That could explain why all the drinks i found in the bottom level of the collapsed tower were hot

**Comment by Hirmuolio** [comment]
I found and fixed the bug with underground areas. Are bugged temperature items spawning in above groun areas too?

**Comment by Inglonias** [comment]
I saw it in an evac shelter so yes

**Comment by descan** [comment]
Yes, above ground - but not all of them?
![image](https://user-images.githubusercontent.com/4212389/175792587-5ab9df3d-1e5f-4e83-a63c-eb373731eeba.png)
This is a character I just made and then moved onto the nearest counter, which had this on it. It's an above-ground ransacked evac shelter.

**Comment by descan** [comment]
Same character, underground - the bleach I mentioned being hot, meaning it's not just food but other things (within containers? I haven't found free-floating items that are hot.)
![image](https://user-images.githubusercontent.com/4212389/175792662-ceceea57-cd00-4a81-a6ee-b31d83a20f77.png)
The toilet water that is clean water (hot).
![image](https://user-images.githubusercontent.com/4212389/175792665-8f4ea785-b864-43d8-af14-8aa8eaad1437.png)

**Comment by Inglonias** [comment]
> Same character, underground - the bleach I mentioned being hot, meaning it's not just food but other things (within containers? I haven't found free-floating items that are hot.)

I have seen hot things spawn outside containers, though this is also underground. 
![image](https://user-images.githubusercontent.com/2125926/175792825-1913f9bd-6fcc-41a5-8434-344c229d8dc5.png)

**Comment by Hirmuolio** [comment]
Something weird is going on.

I can't think of any valid reason why items that spawn on same tile would have different temperatures. That makes no sense. Something is very broken there.

On the release version one part of the stack has correct temperature and one part of the stack has bad temperature.

For some bizzare reason the fix I made for underground items seems to fix the above ground items spawning too. That doesn't make sense at all.

So I guess there is bug somewhere that causes items to get processed as if they were underground when the item is spawned above ground.
