### ISSUE TITLE
new sidebar thirst seem to be not updating (or showing some differing info)

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#58705]
### Describe the bug

i was "very thirsty", i drank a huge volume of water until i was full and the consume item screen told me that i have no thirst anymore (blank status). The sidebar showed me that im still "very thirsty"

before the sidebar update the consume item screen and the sidebar always showed the same status

### Steps to reproduce

get thirsty (easy, since its summer)
drink something
compare consume item screen with sidebar
wait a bit to further observe the difference

### Expected behavior

the sidebar and the consume item screen should show the same status.
after drinking a huge amount of water, one is not thirsty anymore. I even waited several minutes until the "full" changed to "satisfied", but the thirst display hadnt updated.

### Screenshots

![thirst sidebar bug](https://user-images.githubusercontent.com/76821083/175768312-ac878aea-bf27-450d-a0f8-295f1a492b20.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 06f4f6f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]
]

using the classic sidebar , and i edited the sidebar-legacy-classic.json to not contain the health bars by omitting "lcla_health_left_layout" from "lcla_health_layout" and changing the overlay map size a bit... this should not have an influence, since the hunger display still works fine...

### Additional context

[Polebridge.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8984443/Polebridge.zip)

**Comment by Inglonias** [comment]
/confirmed

What's happening here is that the consume menu takes the stuff in your stomach into account to allow for instant feedback, and because the sidebar is just reading your character's raw thirst value, it doesn't do that.

You could argue that the sidebar is more technically correct than the consume menu, but I can certainly see why this would not be desirable.
