### ISSUE TITLE
Item charges spawning via allowed charges rather than predefined

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#58709]
### Is your feature request related to a problem? Please describe.

I think it would be nice if the spawn lists for items with charges could also include an non-explicit distribution for their contents.
  

### Solution you would like.

Say, take pens.  They can have red/blue/green/black ink.  Instead of spawning each type, like so:
```
{
    "id": "writing_utensils",
    "type": "item_group",
    "items": [
      { "item": "permanent_marker", "prob": 10, "charges": [ 0, 500 ] },
      { "item": "pen", "prob": 15, "charges": [ 0, 100 ] },
      { "item": "pencil", "prob": 35, "charges": [ 0, 100 ] },
      { "item": "black_pen", "prob": 35, "charges": [ 0, 100 ] },
      { "item": "blue_pen", "prob": 20, "charges": [ 0, 100 ] },
      { "item": "red_pen", "prob": 10, "charges": [ 0, 100 ] },
      { "item": "green_pen", "prob": 5, "charges": [ 0, 100 ] }
    ]
  },
  ```
Instead you could set up an office distribution line that would imply:
```
{
    "id": "writing_utensils",
    "type": "item_group",
    "items": [
      { "item": "permanent_marker", "prob": 10, "charges": [ 0, 500 ] },
      { "item": "pen", "prob": 85, "valid_charges": ["Any"], "distribution_rarity":["Value"], "charges": [ 0, 100 ] },
      { "item": "pencil", "prob": 35, "charges": [ 0, 100 ] },
    ]
  },
  ```
Which would randomize the color of ink that could go into the pens.  (This would bypass the refillable:false part of reloading items, btw.) *
    
So the first of two new json tags would be something like "valid_charges", which would either take 'Any', or would take an array of inputs.  The second would be "distribution_rarity", which would take options like "Flat", "Value" **, "Value_squared", "post_apoc_value", "weight", or an array of values.  The items generated would, ideally, be generated with random charges upon spawn, rather than once dice-roll per cell.  

Now, this doesn't solve doubly or triply nested items, without becoming a mess.  My only thoughts there would be to either include default distributions with them (such as for magazines or ammo belts), or to have another tag like "recursive_random_charges":"True".

\* (Yes, I do realize that pen inks don't have different values, so that's a bad weight scheme, and to be more identical the line should have been 
```{ "item": "pen", "prob": 85, "valid_charges": ["ink_black", "ink_blue", "ink_red", "ink_green"], "distribution_rarity":[50,20,10,5], "charges": [ 0, 100 ] },``` 
but I was going with the simplest toy example.)

\*\* In the case of a distribution such as "Value", I am implying that more expensive items be given a weight something like 
flat_chance_% / ((specific item distribution value)/total distribution set value sum) or, as a computationally cheap alternative, flat_chance_% * (total distribution set value sum - specific item distribution value).  Value_squared would be a more exaggerated version, in the cases where such are reflected IRL.  (Canola oil vs, say, sunflower oil.)

### Describe alternatives you have considered.

Keeping as is, and hoping that out there, one day, a zombie might have a gun with an uncommonly loaded ammo in it without yet another distribution PR fix.

### Additional context

[There are 3 competing standards!
](https://xkcd.com/927/)

**Comment by GuardianDll** [comment]
Im not entirely understand it
why not just pre made another item_group for pens, like:
```json
{
    "id": "pens",
    "type": "item_group",
    "items": [
      { "item": "pen", "prob": 15, "charges": [ 0, 100 ] },
      { "item": "black_pen", "prob": 35, "charges": [ 0, 100 ] },
      { "item": "blue_pen", "prob": 20, "charges": [ 0, 100 ] },
      { "item": "red_pen", "prob": 10, "charges": [ 0, 100 ] },
      { "item": "green_pen", "prob": 5, "charges": [ 0, 100 ] }
    ]
  },
```

and then just put this group in the original group:
```json
{
    "id": "writing_utensils",
    "type": "item_group",
    "items": [
      { "item": "permanent_marker", "prob": 10, "charges": [ 0, 500 ] },
      { "group": "pens", "prob": 15, "charges": [ 0, 100 ] },
      { "item": "pencil", "prob": 35, "charges": [ 0, 100 ] },
    ]
  },
  ```
  ?

**Comment by chrispikula** [comment]
The issue with that is that you need to change all the item groups if someone extends the types of, say, 9mm ammo.  Or adds a new type of magazine for 5.56.  And what about if you have two mods that add more items to the same item_group?  Then one will overwrite the other, unless you get a third compatibility between the two.  

This would be a way, if used in the broad value methods, of possibly sidestepping the issue of re-writing the distribution lists when new items are added.

Maybe add an "Else" with a low probability if using the multi-value array method?
