### ISSUE TITLE
Please allow players to achieve the old Custom right panel layout they had before the recent changes

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#58704]
### Is your feature request related to a problem? Please describe.

The first screenshot given in Additional Context is the UI I used. It was compact, concise with a mini-map of the overmap and text aligned to the left. I have grown accustomed to this layout and was able to gather information from it without much thought.

Now the second screenshot is the closest I could get it to the old UI. However some key differences is the missing overmap widget I would have to the right of place and environment. Additionally, Temperature has been moved to be with wind. Also a slight aesthetic disatisfaction in the fact that the Blue Bionic power text does not full fit so "3005 kJ" now shows as "3005..."

Now this may seem like a personal issue, but do bear in mind that I cannot be the only Player who cares deeply about their UI which they rely on for information. Those who upgraded to the latest experimental with this UI change would also be annoyed that their UI cannot be customized to exactly how it was 1 build ago. Habits of looking at certain places for information would become frustrating.
It would defeat the purpose of a customizable UI, if the preferred layout is discarded for the new UI that may not be to everyones satisfaction.

### Solution you would like.

Make it so that players can toggle whether they want the old or new UI. The same was done in the case of the armor coverage map.

### Describe alternatives you have considered.

Make the old UI as (alt) widgets, like "Body Part Status Alt" which is already available.

### Additional context

Beautiful old UI
![image](https://user-images.githubusercontent.com/88375697/175759719-04ae3696-589d-401e-9939-028a133bcc11.png)

Current UI
![image](https://user-images.githubusercontent.com/88375697/175759814-c7a7d90d-da30-4388-aa5b-4b14da6ce39d.png)

**Comment by KHeket** [comment]
And now, if you want to see, which of your part of body are broken, bitten or bleeding - you need to add big widjet, but in previous version you can see all that information in one body part health widjet

**Comment by descan** [comment]
> And now, if you want to see, which of your part of body are broken, bitten or bleeding - you need to add big widjet, but in previous version you can see all that information in one body part health widjet

That much is just a bug that's being worked on and has a PR running for it. The added widget is just a stop-gap.

**Comment by Ilurker** [comment]
It might be appropriate to add a "classic sidebar" mod to the repo until the (much upgraded) sidebar rework is finished? As someone who's very picky about his UI, I sympathize and I've been holding off because of it, but it's not reasonable to expect experimental to revert changes for in-progress features just because they're rough around the edges - this is experimental for a reason, and the sidebar rework is long overdue.

**Comment by Inglonias** [comment]
I made some changes to the label sidebar. Update to the latest experimental and let me know if your issues with it have been resolved.

**Comment by Sathra225** [comment]
I would like there to be a Weather widget option for the custom sidebar as well. Its not available for some reason.

**Comment by DamienRoyan** [comment]
> I made some changes to the label sidebar. Update to the latest experimental and let me know if your issues with it have been resolved.

Yes it is very much satisfactory. Thank you so much :)

**Comment by Maleclypse** [comment]
OP says update is satisfactory
