### ISSUE TITLE
All appliances should be removable via simple deconstruction

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#58710]
### Is your feature request related to a problem? Please describe.

Bug or feature request?

So far I've encountered two appliances "in the wild" that are described as being possible to disconnect and move, but can't be removed in a reasonable manner, namely the hydraulic press and the water purifier. Using the "full" deconstruction on either of these results in a pile of parts, which is reasonable for that command, but not what you want when you want to actually just move it.

I just found out that there is a convoluted way to actually get a hydraulic press found in e.g. a garage as an item, and that is to first "plug it in" when examining it, and then disconnect it (again when examining it).

### Solution you would like.

All appliance furniture should be removable either via simple deconstruction, or, even better, a general "disconnect appliance furniture" command that's applicable to appliances that are placed as furniture by map generation.

### Additional context

I assume the two cases I've found somehow didn't get the appropriate JSON descriptions for disconnection when they were supported as appliances. I consider it unlikely those two are the only ones that have some aspects of their appliancification missed, so appliance reviews might be useful (even better if there's a checklist for what's needed for all appliances, e.g. in the form of an example listing all the locations of example JSON parts, plus one or more optional sections for mapgen furniture support and other special cases, if any).

**Comment by deafmole** [comment]
I would like to add, that (simple) deconstruction of Appliances should add up with the respective object in the wild.
e.g.: solar panels on a roof take 1(one) screw driving & 1(one) prying to deconstruct. If you add them to the grid, they need 2(two) bolt turning instead.

**Comment by PatrikLundell** [comment]
That makes sense. I haven't checked the ones I've introduced in the PR referencing this.
