### ISSUE TITLE
Tin can of curry with meat spoils

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#5873]
Like terrible person said when I complained about it on IRC: 

\<terribleperson> Soyweiser: That still happens? I complained about it a while ago... realistically speaking, properly canned food never goes bad (not in a lifetime, anyways). Tastiness might deteriorate, but you should never have spoilage.

I agree. As long as you do not throw with the cans it should be allright

Edit:
http://smf.cataclysmdda.com/index.php?topic=5747.0 seems to be still around.

**Comment by KA101** [comment]
Think we nailed this one.
