### ISSUE TITLE
New vehicle part: radio

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#58736]
### Is your feature request related to a problem? Please describe.

It would make sense have a radio vehicle part that allows two way communication. It would work akin to the existing two-way radios, but installed into vehicles, freeing up some space/weight for the player's inventory.

In the longer term, it ought to allow for the player being contacted via radio when moving sufficiently close to a location where a caller is located, either because the caller is trying to get in contact with anyone within range, or because the caller actually saw the player's vehicle and decided to try to make contact.
Note that this behavior shouldn't be exclusive to vehicles, as a carried radio ought to work as well, but vehicles are easier to spot, and the antennas are clear indications that the vehicle at least has had communications abilities.

### Solution you would like.

A comms radio part that may occasionally be found in 4x4 cars, all police cars, military vehicles, and probably security vans and prison transports as well. Buses and fire trucks ought to have them too.
This also means police and fire stations ought to have communications desks fitted with a furniture version of this item.

The radio would turn on and scan frequencies when the engine is turned on, but should also be possible to turn on manually. Apart from that, there should be an interaction to allow you to perform the same actions as you can with a two-way radio.

**Comment by kevingranade** [comment]
Feel free to add a vehicle radio, but we don't need an issue tracking it.
