### ISSUE TITLE
Way too many gasoline zombies

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#58733]
### Describe the bug

Gas stations as of #58649 now spawn comically large numbers of gasoline zombies, and they do this on day one. I ran around a city and each gas station I found had something like ten gasoline zombies, and again this is happening immediately instead of after 7 days like the PR claims.

### Steps to reproduce

1. Find a gas station.
2. Observe the absurd numbers of gasoline zombies.

### Expected behavior

I was expecting 0-1 gasoline zombies per gas station and only later into the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 5ea8d0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by sonphantrung** [comment]
Hmm, how many gas zeds do you have? I’ve checked the files and I can assure that it starts at 7 days. Perhaps the repeat field may do something weird

**Comment by sonphantrung** [comment]
Currently working on this! Also, after some testing, the `starts` field seem to not work
