### ISSUE TITLE
Inconsistent in-game reference material for rubber cement

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#58732]
### Describe the bug

The rubber cement is written in 4 reference materials, according to JSON files, according to the HHGC. The in-game crafting menu on the other hand list only 3.
PC read the Sewing book which happens to be not in the crafting menu since it is a faster read, and saved it in the e-ink tablet. The recipe was learned but needs to have the actual Sewing book for reference, the e-ink copy won't work.

### Steps to reproduce

Debug please

### Expected behavior

I expect consistency.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/175800441-bfa56e4e-5c5a-48b2-af06-096003fe4b37.png)
![image](https://user-images.githubusercontent.com/29348635/175800444-80de02bb-e05a-4cf5-93f5-f3948900dab9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 0576312 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
Hello. You choice of wording makes it hard to figure out what you mean, but I think I got it: the recipe can be learned from 4 different books, but you only see 3 in the crafting menu. This is **not a bug**. Either you do not have a copy of "Sewing Techniques for designers" or your applied science level is not high enough.

Here is proof that everything works as intended:

![image](https://user-images.githubusercontent.com/52621858/176006158-b216c161-a652-41a4-87f0-2e40aa9901bb.png)

- OS: Linux
    - OS Version: <unknown>
- Game Version: cb051eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by kevingranade** [comment]
Not an issue as outlined in above comment.
