### ISSUE TITLE
Mycus mutation broken

### ISSUE THREAD

**Issue by Afavertov** [CleverRaven/Cataclysm-DDA#58747]
### Describe the bug

It is not possible to get mycus traitsfeeder, identity, etc.), except for the just "mycus" (. Sleep, eating an incredible amount of mycus fruits and wine do not help either.

### Steps to reproduce

1. Eat marloss berries and seeds.
2. Go to fungus tower and let it give you "marloss gate" trait.
3. Eat mycus fruit, get "mycus" trait
4. Eat more mycus fruits, drink mycus wine and sleep, to mutate further.
5. Wait eternity and die without getting any other trait.

### Expected behavior

After eating mycus fruits and sleeping for a week character should get some new traits, like mycus identity, feeder, mycus flesh, defender and other.

### Versions and configuration

- OS: Win 10
- Game version: experimental 2022-06-26-1548
- Graphic version: tiles
- Ingame language: rus
- Mods loaded: [
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "StatsThroughSkills",
  "stats_through_kills"
]

**Comment by Stadler76** [comment]
/confirmed

In aiddtion to that I didn't have any dreams at all. I've only tested this for like 4 nights, but I doubt it's caused by the RNGsus.

**Comment by Stadler76** [comment]
/confirmed again

Found the cause of it (I think):
![grafik](https://user-images.githubusercontent.com/13157984/183308798-603e400a-ebf3-456a-af05-1f316b3893cc.png)
