### ISSUE TITLE
Appliance Stereo

### ISSUE THREAD

**Issue by deafmole** [CleverRaven/Cataclysm-DDA#58744]
### Is your feature request related to a problem? Please describe.

It was probably just an oversight, but we are still missing an appliance similar to the stereo in a vehicle to play music with. 

### Solution you would like.

Add the appliance 'stereo system'.

### Describe alternatives you have considered.

Not adding it, which would result in either more keypresses to switch out batteries of your mp3-player, or a one tile vehicle in your base.

**Comment by liminalRoar** [comment]
how does this differ from the suggestion just made a few hours before? #58736
