### ISSUE TITLE
20.16kg of kevlar for a 7.5kg suit.

### ISSUE THREAD

**Issue by keampe** [CleverRaven/Cataclysm-DDA#58758]
### Describe the bug

the Kevlar Jumpsuit uses 672 sheets of Kevlar at .03 kg per - or 20.16 kg of Kevlar on an item that weighs 7.5 kg total. To top it off, it's only 50% Kevlar. The other 50% is Lycra. It uses 20 Lycra sheets at .03kg a pop or 0.6 kg. and a Raincoat weighing 0.96 kg and of course 300 duct tape for another 1.2 kg.

### Steps to reproduce

Try making a Kevlar Jumpsuit, notice the huge amount of Kevlar needed.

### Expected behavior

I would expect the Kevlar Jumpsuit to use less material - something like 120 of each Kevlar and Lycra plus the rain coat and duct tape. This still adds up to 9.36 kg, so maybe less is in order, but you would have some wastage of material. Maybe 100 of each would have enough wastage - a whole 0.66 kg worth.

### Versions and configuration

I believe this issue would be standard through all versions of the current experimental.

### Additional context

The Light Kevlar Jumpsuit likewise uses way too much material - 11.52 kg or Kevlar for a 5.2 kg suit. You'll note in both cases it's more than twice as much as the total suit weighs.

   - Shane

**Comment by chrispikula** [comment]
I think this arises out of mishaps with Kevlar sheets to layered kevlar plates, and abandoned tailoring overhauls?  Maybe the fabric charge rework, as well?

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: cb051eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
These were not touched during the recent tailoring overhaul. The extremely large values of sheets arose from ye olden times when sheets were something like 1/22th of a patch and used charges rather than being stacks of individual items.

**Comment by anoobindisguise** [comment]
By the way, if this changes this would be a good time to implement #57809.

**Comment by Marcos6226** [comment]
Fixed by #59434 @bombasticSlacks

**Comment by bombasticSlacks** [comment]
Alright it is closed 🔐
