### ISSUE TITLE
Vehicle belongs to: your followers spam/npc agro.

### ISSUE THREAD

**Issue by viljar290** [CleverRaven/Cataclysm-DDA#58752]
### Describe the bug

npc's seeing me use my own vehicle get angry and attack me along with the spam of This vehicle belongs to: your followers. there may be consequences if you are observed interacting with it, continue?

### Steps to reproduce

attempt to use your vehicle with npc there.  Get spammed with warning about it and if you do use it the npc attacks you. 

Added link containing savefile: https://1drv.ms/u/s!AqStS6i9yEofgpJ1zcpzzrQ2QJ1bug?e=l8v7Lm

### Expected behavior

its my vehicle the npc should not be having issues with it.

### Screenshots

![image](https://user-images.githubusercontent.com/41335390/175831791-daf29841-c08b-4b4c-8e53-1a2a4e25fd87.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 0dbe8ac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by hexagonrecursion** [comment]
Did you die and continue the game as a follower?

/confirmed by loading the save file you provided

- OS: Linux
    - OS Version: <unknown>
- Game Version: cb051eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
