### ISSUE TITLE
region_overlay can not deal with weather

### ISSUE THREAD

**Issue by Light-Wave** [CleverRaven/Cataclysm-DDA#58757]
### Describe the bug

region_settings contains data for weather, and region_overlay can overwrite most things, but not the weather field.

### Steps to reproduce

Create a mod with a region_overlay, try to add a "weather" field, get an error when you try to load the world.

### Expected behavior

If a weather field exists, it should allow one to overwrite the values given in the weather field in the region_overlay, without altering values not given.

### Screenshots

![image](https://user-images.githubusercontent.com/66904273/175797005-a6f60323-7356-41ac-8b7f-b5f57c064596.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: d422ab7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    DinoMod [DinoMod],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Blocks PR #58727

region_overlay is dealt with in [regional_settings.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/regional_settings.cpp). Dealing with weather would fitt near the end of apply_region_overlay(), near line 805.
Weather is loaded in [weather_gen.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/weather_gen.cpp), in load() near line 314.

One solution would be to add a function in weather_gen.cpp like `weather_generator weather_generator::load_with_overlay( const JsonObject &jo,  weather_generator  old_weather)` that loads given values if they are given, and otherwise uses the old weather given. The function would be called from apply_region_overlay() near line 805.

**Comment by anothersimulacrum** [comment]
CC @Ramza13 
You've been touching weather.
