### ISSUE TITLE
How do you build and package efficiently

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#58765]
### Is your feature request related to a problem? Please describe.

Currently you need to build at least twice and sometimes even thrice which is super frustrating and consumes unnecessary cpu time.

### Solution you would like.

Arch Linux compiles *thrice*:

https://github.com/archlinux/svntogit-community/blob/packages/cataclysm-dda/trunk/PKGBUILD#L33-L34

```
ODIR = $(BUILD_PREFIX)obj
```

once for curses, once for tiles and then once again because the build prefix changes. This takes super long and is frustrating. Is there a better way to build? Is it possible to build curses and tiles in one go via the same compiled objects?

Edit: the -git version from the AUR might even compile four times:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cataclysm-dda-git#n50

**Comment by BrettDong** [comment]
> Is it possible to build curses and tiles in one go via the same compiled objects?

It is not possible. Curses and Tiles define different set of macros and link against different external libraries. They should be built separately.

In my opinion, Curses and Tiles should be distributed in separate packages. It does not make much sense to me to bundle Curses and Tiles in a single package.

As an example this is how NetHack gets packaged in Debian:

* [nethack-console](https://packages.debian.org/stable/games/nethack-console) (3.6.6-2+b1 [amd64], 3.6.6-2 [arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x])
dungeon crawl game - text-based interface

* [nethack-qt](https://packages.debian.org/stable/games/nethack-qt) (3.6.6-2+b1 [amd64], 3.6.6-2 [arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x])
dungeon crawl game - Qt interface

* [nethack-x11](https://packages.debian.org/stable/games/nethack-x11) (3.6.6-2+b1 [amd64], 3.6.6-2 [arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x])
dungeon crawl game - X11 interface

**Comment by NetSysFire** [comment]
It actually gets packaged separately but the -git package does not do that and ships both (see https://archlinux.org/packages/?q=cataclysm for the "official" versions). Could you think of any reason why the third pass in `package()` where make install is run needs to compile yet again? I really think it might be because of the `PREFIX` but I am really not sure.
