### ISSUE TITLE
Sand mound extraction missing from menu

### ISSUE THREAD

**Issue by nukularpower** [CleverRaven/Cataclysm-DDA#58767]
### Describe the bug

In current experimental, when using the construction menu, the entry for Extract Clay correctly has two options for sources, naked clay and "mound of Clay."  However, the similar project Extract Sand only has naked sand, so it is impossible to extract from placed Mounds of Sand.

### Steps to reproduce

1.  Open Contruction Menu
2.  View options for Extract

### Expected behavior

Should be able to get sand from mounds

### Screenshots

![image](https://user-images.githubusercontent.com/5522233/175863978-795ca072-8b14-4086-9443-d2bf8b8325f3.png)

![image](https://user-images.githubusercontent.com/5522233/175864041-0f774501-4c5c-4113-a1fb-4644370f8154.png)

### Versions and configuration

Experimental

**Comment by hexagonrecursion** [comment]
/confirmed being able to extract sand mounds the same way as clay mounds would be consistent.

Note: both sand bounds and clay mounds can be smashed
Note: there are not many place, where sand mounds naturally spawn. exodii pods is one such place

- OS: Linux
    - OS Version: <unknown>
- Game Version: cb051eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
This is just a small matter of adding the definition to `construction.json`. Should be a good first issue for hopeful contributors.

**Comment by Devengel** [comment]
Annoying issue, ran into it, i'll fix it myself i guess.
