### ISSUE TITLE
Refugee Merchant Smokes does not trust me enough to do trade with me even after doing 3 or 4 missions for him.

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#58772]
### Describe the bug

Done around 3 or 4 missions for Smokes at the Refugee Center. The next mission is to collect jars for him. He still does not want to trade with me the important materials.

### Steps to reproduce

Find the Refugee Center and trade with Smokes. Do missions as necessary. 

### Expected behavior

**Goals (of the Free Merchants)**

_Survive through trade. Form friendly mutually beneficial relationships with other survivor factions. Gain control over valuable resources and get other people to pay for them.

In the early to mid-game, a key priority of the Merchants should be to build a self-sufficient defensible base. While they don’t require the player’s aid for that, they may value the player as an experienced consultant._

The Lore does not mention trust issues or doing errands first before the Merchants open up to trade. (Smokes is not his usual self)

### Screenshots

![Uploading image.png…]()

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 31319f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bombasticSlacks** [comment]
I can't compile right now but I think something in wants_to_sell is backwards. That or the default condition / group is ill-defined I need to dig in more with the ability to compile.

**Comment by jeffplata** [comment]
> 

Is the save file the whole world folder?

**Comment by andrei8l** [comment]
Yes. If it's too big for github, you can use a third-party website like https://send.vis.ee/

**Comment by andrei8l** [comment]
Ok, I reproduced it by completing one mission, which set trust to `-97`. I'll look into it.

**Comment by jeffplata** [comment]
I'll hold uploading the save file then.

**Comment by hexagonrecursion** [comment]
@jeffplata 

> I'll hold uploading the save file then.

> EDIT: maybe not. I can't reproduce anymore.

Please upload the file.

**Comment by andrei8l** [comment]
Thanks for the save file. Your trust with `free_merchants` is negative so the trade part is working correctly.

Now to figure out why trust is negative. Did you (try to) steal any items from them?

**Comment by jeffplata** [comment]
Ah, confession time. Now I remember.
Took water from their toilet (I thought it was free). Got caught and confronted when I tried to purify it. Got killed doing the spy mission. Savescummed. Ah, even in the afterlife they don't forget trespasses. So that explains why after completing the jars mission he wants to trade again.

**Comment by Zireael07** [comment]
FTFY: Savescumming nearly always leads to weird stuff

**Comment by anothersimulacrum** [comment]
Bugs due to savescumming aren't valid. If anyone has reason to keep this issue open, just comment and I can reopen it.

**Comment by jeffplata** [comment]
I hope this gets revisited. On other games this bug still persists with even when playing immaculately.

**Comment by andrei8l** [comment]
Sorry, I still can't reproduce it. I've tried going to several evac centers, completing missions, saving and reloading. Please upload the new save file and/or provide exact reproduction steps.

**Comment by anothersimulacrum** [comment]
@andrei8l Would you like me to reopen this issue?

**Comment by jeffplata** [comment]
I can confirm that I did the `Deal with the Informant` mission (with several attempts) when I started noticing Smokes not wanting to trade. It is not triggered when testing on a new game and going straight to Smokes and doing missions.

**Comment by jeffplata** [comment]
Any work around while awaiting fix?

**Comment by bombasticSlacks** [comment]
I mean the bandit informant quest would need to be redesigned. I don't think there really is another solution, the code for trust is working as expected it's just that quest is malformed.

**Comment by pjf** [comment]
I just had the same thing happen to me. Thank you *so much* for the spot with the deal with informant mission, @andrei8l.

The informant mission sticks out like a sore thumb compared to a lot of the other missions. I was expecting some cool "Professor Alonso in the bathroom with a candlestick" detective work, but instead it's "talk to all the guards until you find one with different dialogue".

**Comment by BHat0451** [comment]
I've had this happen to me, as well; complete every mission for Smokes, then move on to doing Old Guard missions, get to the informant mission, flub the dialogue a few times... Time passes, finish every Old Guard mission there is, but now Smokes doesn't want to trade because of the earlier dialogue flubbing. Didn't even know that could happen until finding this

Don't know how to fix this with save-editing, and being unable to trade with the Free Merchants is a major downside; don't know how to fix with the in-game debug menu, either (or if it's even possible to fix there, since you don't seem to be able to edit faction values like trust/reputation using the menu).

**Comment by jhamilton0** [comment]
To fix this in an existing save, you can open the file "master.gsav" in a text editor, search for the string "The Free Merchants", then change the "trusts_u" property that appears immediately after to something positive.

**Comment by matt32106** [comment]
me too :) "The Free Merchants", "likes_u": 27, "respects_u": 27, "trusts_u": -3,
