### ISSUE TITLE
sidebar UI, vertical graph

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#58770]
### Is your feature request related to a problem? Please describe.

It will be great to have a multiline 1 symbol widht graph widget.

### Solution you would like.

Something with behavior similar to overmap widget.

**Comment by bombasticSlacks** [comment]
I don't understand exactly what you mean by this.

**Comment by Inglonias** [comment]
I think they're asking for a graph that, instead of putting symbols into a single row, adjacent to each other, a graph that will place one symbol per row. Not sure how this would work, exactly. Maybe something like this?

```   |   
   |   
   |   
   |   
   |   
Text```

**Comment by vetall812** [comment]
> I think they're asking for a graph that, instead of putting symbols into a single row, adjacent to each other, a graph that will place one symbol per row. Not sure how this would work, exactly. Maybe something like this?
> 
> ```
>    |   
>    |   
>    |   
>    |   
>   Text
> ```

Exactly, but i thought about no labels... probably.
