### ISSUE TITLE
Mine Water Dispensers Have Infinite Water

### ISSUE THREAD

**Issue by Fumarii** [CleverRaven/Cataclysm-DDA#58791]
### Describe the bug

As the title states. The capacity of water dispensers found in mine locations is bugged, and they are able to dispense hundreds of liters of clean water without running dry.

### Steps to reproduce

Get 200L drum(s).
Fill drum(s) with clean water from dispenser.
Dispenser continues producing clean water.

### Expected behavior

I am thinking these are supposed to be like office water dispensers? If so they should have a maximum capacity of 3/5 gallons of water, but even that might be too much for the setting.

### Versions and configuration

Windows 10
Cataclysm-BN Experimental Build 06/21/2022-2053

**Comment by estebandellasilva** [comment]
Bright Night?
