### ISSUE TITLE
Mounted lasers not using car battery.

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#58798]
### Describe the bug

I've been using a mounted A7 laser rifle, but in a more recent update it seems to have stopped being able to draw power from my vehicle despite still being mountable.

### Steps to reproduce

Spawn a vehicle and some tools
Spawn a laser gun and a turret mount
Mount the laser gun on the vehicle
Be unable to fire the gun

### Expected behavior

The gun should draw power from the vehicle's batteries

### Screenshots

![image](https://user-images.githubusercontent.com/94415528/176264955-7f3744ab-b7db-4f58-8d9f-4ef7b0ca9072.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: d046929 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'm using Magiclysm in the screenshot, but I tested this without it and it's still a problem.

**Comment by actually-a-cat** [comment]
Could not reproduce on 80d1bee. Spawned a wheelchair, put a charged car battery, a turret mount, and a laser rifle on it, successfully fired the rifle.

**Comment by fairyarmadillo** [comment]
Ack! I'll close this for now, update, and reopen if I am still having the issue. Thanks for checking.
