### ISSUE TITLE
Split wood smoke and engine exhaust into their own field types

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#58802]
### Is your feature request related to a problem? Please describe.

Kevin and I have spent a lot of time brainstorming ways to make cheap smoke dispersion algorithms so that campfire smoke and things don't mess with line of sight calculations so much. If we had better systems here we could cache line of sight fields in places like faction camps, which would open up some cool new optimization avenues, and allow more things to be cached and run in the background outside the reality bubble.

### Solution you would like.

I realized today that, while we do still want ways to model plumes of smoke and wind effects, we were getting pretty far into the weeds. Most of the smoke we care about for caching reasons is not dense enough to block line of sight in the context we mean!

I propose making two new smoke effect fields.
- wood smoke is essentially the same as the current smoke field, but transparent until very high levels.
- exhaust is always transparent and doesn't cause coughing effects

TThe  existing smoke field should still be kept around, for use with other sources of smoke so that we don't accidentally nerf smoker zombies or smoke grenades

### Describe alternatives you have considered.

Complex smoke modeling...

### Additional context

This will still need some changes and adjustments and a better smoke system in the future.

**Comment by AtomicFox556** [comment]
> * exhaust is always transparent and doesn't cause coughing effects

That doesn't mean it's not dangerous, though. It is indeed possible to suffer carbon monoxide poisoning (potentially even a lethal one) if you let your vehicle engine run in a closed garage while you're inside.

**Comment by I-am-Erk** [comment]
Yes, that's not really a directly related issue. Separating exhaust would eventually allow us to have CO effects though.
