### ISSUE TITLE
Collapsed baton disappears from inventory after loading save

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [CleverRaven/Cataclysm-DDA#58808]
### Describe the bug

I was wielding a baton (extended) when I decided to wield another weapon. When prompted, I opted to place the baton (extended) into my inventory. I then activated the baton to collapse it. Later, I saved and reloaded the game and was shown the following error:

> DEBUG    : error: item baton cannot fit into pocket while loading: item is too short
>
> FUNCTION : void item_contents::combine(const item_contents&, bool)
> FILE     : src/item_contents.cpp
> LINE     : 599
> VERSION  : 80d1bee

After dismissing the error, the baton had disappeared from my inventory.

### Steps to reproduce

Load the attached save for Glinda 'Sixes' Moody.

More generally, it seems the error occurs when an item changes length after being inserted into a pocket.

### Expected behavior

Baton does not disappear from inventory.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9006925/debug.log)
[Pendleton Center.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9006933/Pendleton.Center.zip)

**Comment by PatrikLundell** [comment]
/confirmed

I believe similar issues have been reported for modding holstered weapons.

Move your character one step and the baton falls to the ground, so at least it isn't lost.

**Comment by I-am-Erk** [comment]
as long as the items are falling to the ground and not being lost entirely, I think this can be deferred as a blocker. As with all deferred blockers, I still hope it gets fixed before stable, but I think there are some complex UI questions there. At the very least, it would be nice to have a warning prompt or an alert, as mentioned in #51457.

**Comment by jeanpaulrsoucy** [comment]
This is a super old save, so the characteristics of the items in question have greatly changed, but I can confirm that the overflow functionality seems to be working as intended.

![overflow](https://github.com/CleverRaven/Cataclysm-DDA/assets/31170087/c6566b21-a103-426a-87b9-cc810cb51858)

The specific bug raised in this issue also seems to have been tested here: https://github.com/CleverRaven/Cataclysm-DDA/pull/65518#issue-1698901501.
