### ISSUE TITLE
Blacksmith Cody Miller & Gunsmith Jay Ruckers non-unique

### ISSUE THREAD

**Issue by deafmole** [CleverRaven/Cataclysm-DDA#58813]
### Describe the bug

The 'unique' NPC-Location is not unique. While it is understandable that we should encounter that location, it leads to silly mapgeneration like you can see below.

### Steps to reproduce

1. Start a new run
2. Explore

### Expected behavior

- The Location gets only generated once.
- Alternatively, add a set of the NPCs & their different quests
- No call_by_reference for (unique) NPCs. 

### Screenshots

![twins](https://user-images.githubusercontent.com/108176226/176390357-8db047b4-27cd-4bae-9ffb-8cff005086d1.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 27817a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by andrei8l** [comment]
This is a known issue with no good solution at the moment. You can read through previous discussion in #49322 and #57127.

**Comment by deafmole** [comment]
Oh, sorry I just checked for the Blacksmith location in issues. Never encountered them before, so I thought that might be an issue with the definition of that single location. And I have never found more than one Hub, one Refugeecenter, etc.. - however, I am not a mobile-base-player.
If a globally unique flag, like mentioned in #49322 is used, adding NPCs to it shouldn't be too hard.

**Comment by kevingranade** [comment]
Duplicate of more general issue.
