### ISSUE TITLE
Making units::temperature safer

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#58820]
### Is your feature request related to a problem? Please describe.

The new units::temperature is nice. But it is too easy to do wrong math with it.

For example:
units::temperature temperature_delta = units::from_celcius( 20 )
units::temperature temperature = units::from_celcius( 15 )

One could without thinking do `temperature_delta * 2` and expect it to result in 40 °C but it actually results in 313.15 °C.
One could without thinking do `temperature + temperature_delta ` and expect it to result in 35 °C but it actually results in 307.85 °C.

The main problem is that the three different temperature scales (kelvin, celcius and fahrenheit) have their zero in different places. So 20 C + 15 C is different from 293.15 K + 288.15 K even though the temperatures in both are same. Operations on units::temperature always operate with kelvins.

### Solution you would like.

* Do not allow multiplying units::temperature with scalars.
* Do not allow adding units::temperature with units::temperature.

These two are technically ok operations to do. But it is too easy to make errors when doing so. So it is best to not even allow trying to do them.

Create new units::temperature_delta.

* units::temperature_delta could be summed with itself or multiplied with scalar. 
* It could be summed with units::temperature and that would result in units::temperature.
* Units::temperature - units::temperature would result in units::temperature_delta.

Now:

units::temperature_delta temperature_delta = units::from_celcius( 20 )
units::temperature temperature = units::from_celcius( 15 )

Now `temperature_delta * 2` results in 40 °C.
Now `temperature + temperature_delta ` results in 35 °C.

### Describe alternatives you have considered.

Be very very careful when writing temperature math.

**Comment by jbytheway** [comment]
I agree that separating temperature and delta_temperature is a good idea.  We have similar protections in the type-safe points.

However, I think you won't be able to achieve this using the existing `units` infrastructure.  You'll need to either add something new or significantly rework it.

My gut says that the easiest approach would be to have a `units::`-based value to represent delta-temperature, and a new type to represent absolute temperatures.
