### ISSUE TITLE
Smoking rack teleports food out of sealed containers

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58822]
### Describe the bug

If you put foodstuffs inside a sealed container into a smoking rack, they get moved but the container remains sealed.

### Steps to reproduce

1. Craft "3L glass jar (sealed) > pickled veggies (fresh) (12)"
2. Build a smoking rack
3. Open the smoking rack UI -> "Insert food for smoking..." and add the veggies
4. The veggies are now in the rack but you have an empty _sealed_ 3L jar.

### Expected behavior

1. The jar should get unsealed before its contents get used
2. It would be much nicer if the game asked for a confirmation before unsealing containers (#58821)

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-06-12-1440

**Comment by hexagonrecursion** [comment]
/confirmed

![image](https://user-images.githubusercontent.com/52621858/176594522-c500a7f8-f6d2-4af4-80e3-284c6388a130.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 22 October 2024.

I crafted picked veggies and got a sealed glass jar with them.
![изображение](https://github.com/user-attachments/assets/9f1021e9-5626-4db7-b21a-450c8b621086)

I'm putting veggies into the smoking rack.
![изображение](https://github.com/user-attachments/assets/c6d264b5-e9e5-4f08-8423-b8f116b30045)
![изображение](https://github.com/user-attachments/assets/48e3f20e-e314-41b2-8171-8a617aa68fcc)

My jar is unsealed.
![изображение](https://github.com/user-attachments/assets/59071c57-f1f3-420a-8a52-1ae655807dd6)

Closing until reconfirmed.
