### ISSUE TITLE
Cauterization don't heal bitten body parts and don't stop bleeding

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#58823]
### Describe the bug

Currently attempting to cauterize a bite wound or at least used to a few months back, used to give you a 50/50 chance of cleaning the wound, in exchange for bodypart damage and pain, it was a method of saving on some disinfectant, if you were in a position to do so or if you had no disinfectant and wanted to take a chance.

After doing some equieries in discord chat with the help of Harakka, and Venera3, it was concluded that the iuse_actor.cpp doesn't actually give you any chance to clean the wound via cauterization. So this bug report is over whether or not that the UI is giving out misinformation or it's not displaying the correct information as i've attempted multiple times on a new character and it never once cleaned the infection via cauterization. 

### Steps to reproduce

Get bitten by a zombie, attempt to clean it with cauterization, with some metal object and a fire source.

### Expected behavior

Have the UI not inform the player of giving them a 50/50 chance of cleaning bite wounds, when it no longer does.

### Screenshots

![image](https://user-images.githubusercontent.com/5264667/176490334-d0f4c363-78e8-4cb4-bd48-8955beabde74.png)
![image](https://user-images.githubusercontent.com/5264667/176491235-78a9fabe-2e1f-4733-a382-3c91ecfd6e9e.png)
![image](https://user-images.githubusercontent.com/5264667/176491287-465b8a34-73bd-47c4-a2e7-4bd19a5ccb4c.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: cc52f60 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Mythical Martial Arts [MMA],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Blaze Industries [blazeindustries],
    Useful Helicopters Experimental [useful_helicopters],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    Aftershock [aftershock],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch]
]

**Comment by hexagonrecursion** [comment]
/confirmed it says 50%, but I have made 10+ attempts with 0 successes.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
