### ISSUE TITLE
Game very slow when returning to NPCs doing deconstruction work without necessary items

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#58838]
### Describe the bug

I set three NPC followers deconstructing everything at a house and when off to have some fun.  After coming back a day or two later, the game became unplayably slow as I approached their location. Each step I take, takes 7-8 seconds.  It appears the game is getting stuck in a loop where an NPC is trying to find a tool he needs.

I am running a fairly recent Windows MSVC build I built myself (2f9a6353c7, no code changes)

### Steps to reproduce

1. Load the save file: https://drive.google.com/file/d/1jje22dRnpvooaYQ5VAS8lPUvGMRuzjW3/view?usp=sharing
2. Try to walk north towards the house with the NPCs working.
3. When you get close enough to see the NPC "Lester 'Music' Matlock" you'll see he is "trying to find necessary items to do the job x 100" every turn.
4. If you tell Lester to stop constructing, the issue goes away.

### Expected behavior

I expect the game not to be extremely slow.

### Screenshots

![image](https://user-images.githubusercontent.com/3675402/176598364-f033df3f-9ad8-4013-81eb-1db120af5402.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1348 (20H2)
- Game Version: 0.F-9412-g2f9a6353c7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
IIRC this was already reported sometime ago.

**Comment by dholmes215** [comment]
I might not have searched thoroughly enough when I wrote it. It looks like it could be the same as #52283, if that's what you mean.

**Comment by andrei8l** [comment]
The code block responsible for this *desperately* needs to be rewritten. From scratch. After nuking the existing code. And burning the remains for 24 hours minimum. Can you please try this stopgap patch?
```diff
diff --git a/src/activity_item_handling.cpp b/src/activity_item_handling.cpp
index 147276214a..e27103542f 100644
--- a/src/activity_item_handling.cpp
+++ b/src/activity_item_handling.cpp
@@ -2515,6 +2515,7 @@ static std::unordered_set<tripoint_abs_ms> generic_multi_activity_locations(
             }
         }
     } else if( act_id != ACT_FETCH_REQUIRED ) {
+        dark_capable = true;
         zone_type_id zone_type = get_zone_for_act( tripoint_zero, mgr, act_id, _fac_id( you ) );
         src_set = mgr.get_near( zone_type, abspos, ACTIVITY_SEARCH_DISTANCE, nullptr, _fac_id( you ) );
         // multiple construction will form a list of targets based on blueprint zones and unfinished constructions
@@ -2525,9 +2526,6 @@ static std::unordered_set<tripoint_abs_ms> generic_multi_activity_locations(
                     src_set.insert( here.getglobal( elem ) );
                 }
             }
-            // farming activities encompass tilling, planting, harvesting.
-        } else if( act_id == ACT_MULTIPLE_FARM ) {
-            dark_capable = true;
         }
     } else {
         dark_capable = true;
```

**Comment by AndyHugwell1984** [comment]
This is happening to me on the latest experimental (10/11/2023). NPC has the the necessary tools in his inventory, as well as another set of the same tools right beside him, and has access to the required materials, but it slows the game down hugely with the "trying to find necessary items" line.
