### ISSUE TITLE
Battery charges being unloaded by unload zone

### ISSUE THREAD

**Issue by Ilurker** [CleverRaven/Cataclysm-DDA#58833]
### Describe the bug

The unload zone appears to have achieved the unique ability to unload the electrons from batteries, much to the consternation of battery lickers the world over.

### Steps to reproduce

1. Gather bare batteries into a pile
2. Zone the tile they are in as unsorted and unload. Make sure no other zones but unload and unsort zones cover the title.
3. Trigger the sort command

### Expected behavior

Battery charge should remain within batteries until such time as they are applied to a proper device, such as a tongue.

### Screenshots

![image](https://user-images.githubusercontent.com/104868222/176580789-5c88a026-0a9a-4e56-a2ac-fe7a5c087538.png)
![image](https://user-images.githubusercontent.com/104868222/176580821-e3f6482f-d914-433e-afcb-10fea677a2df.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: edc1469 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ilurker** [comment]
@bombasticSlacks @mqrause I believe you were the two most recent contributors to the unload zone code - any insight?

**Comment by mqrause** [comment]
I can't remember touching that, but magazine unloading is new and batteries are magazines, so I guess it just misses a check for that.

**Comment by hexagonrecursion** [comment]
/confirmed Sort full batteries -> get empty batteries (the charge evaporates)

Note: this does **not** produce free floating charge

Workaround: designate a "loot: spare parts" zone

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by delarifert** [comment]
i've seen this too, should i post evidence or is it enough to say it?

**Comment by mkrutov** [comment]
oh god its https://github.com/CleverRaven/Cataclysm-DDA/issues/57742 all over again!

**Comment by bombasticSlacks** [comment]
I'll fix this when it isn't 5am here

**Comment by Ilurker** [comment]
> /confirmed Sort full batteries -> get empty batteries (the charge evaporates)
> 
> Note: this does **not** produce free floating charge
> 
> Workaround: designate a "loot: spare parts" zone

Interestingly, I can't get it to consistently produce free-floating charge either - it just pops occasionally. I wonder if there's some sort of code to clean up the charge items that occasionally isn't firing or something? It's really weird.

**Comment by bombasticSlacks** [comment]
Compiling the fix rn its as simple as actually using the code infrastructure the game already has
