### ISSUE TITLE
Peeking up the stairs in a lab displays a location different from where you go with them

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58839]
### Describe the bug

In a lab, peeking upstairs shows one location, but actually going up the stairs land you in a different area.

### Steps to reproduce

1. Load the attached save [weird_peeking_stairs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9016751/weird_peeking_stairs.zip)
2. Peek up the staircase the character is standing on
![peek](https://user-images.githubusercontent.com/55463047/176602223-0a13a454-d137-4596-9683-394006b92644.png)

3. Now actually go up the staircase and see where you end up 
![go](https://user-images.githubusercontent.com/55463047/176602245-a774553e-dd60-48cd-8442-bd77983b8359.png)

### Expected behavior

I expect peeking and going via a staircase to interact with the same area.

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-06-12-1440
Mod list: default

**Comment by mkrutov** [comment]
Oh yeah, constantly see this in labs and subways. I was under impression that this has already been reported, but can not find the issue(s).

**Comment by mkrutov** [comment]
nvm https://github.com/CleverRaven/Cataclysm-DDA/issues/49162, this was fixed a little bit ago, try with new experimental version i suppose

**Comment by x-qq** [comment]
Thanks.
