### ISSUE TITLE
Add a boiled potato recipe/item

### ISSUE THREAD

**Issue by Crudbone** [CleverRaven/Cataclysm-DDA#58843]
### Is your feature request related to a problem? Please describe.

Looking at Hitchhiker's Guide to The Cataclysm, there seems to be an unrealistic lack of cooking recipes that involve raw potatoes being the main ingredient; the only ones being baked potatoes, french fries, and potato chips.

In the early game, you can't do much with a raw potato unless you have cooking oil for french fries. You might think that baked potatoes are the easiest to make in the early game, but they require a functioning oven. Of all the basic foodstuffs that exist in CDDA, why aren't boiled potatoes a thing yet?

### Solution you would like.

Make a boiled potato recipe and food item.

### Additional context

P.S. If someone would like to turn this suggestion into a reality, could they also make a recipe for mashed potatoes while they're at it? Thanks in advance.

**Comment by Zireael07** [comment]
Boiled as in boiled in a container of some sort on a stove/over a fire?

For baked, well, you can bake potatoes in a fire (I used to do this as a teen) so that should be changed too.

**Comment by Zireael07** [comment]
Yep, I did it with the aluminium foil method in fire

**Comment by NetSysFire** [comment]
Labeling as good first issue. I wonder if you can re-use the aluminium foil (can be used as a tool rather than an ingrdient). I would also add another recipe that works without using foil but takes longer. I am thinking of skewering the potatoes and putting them over the fire. All three recipes should have good batch time savings.

**Comment by chrispikula** [comment]
It's too bad things can't gain the tag 'dirty' via cooking ala json.  This would be an acceptable spot for re-used baked-potato aluminum.

**Comment by Crudbone** [comment]
#58930

**Comment by NetSysFire** [comment]
You should reopen this and add a closing keyword to your PR, so this issue is automagically closed when the PR gets merged.

**Comment by Crudbone** [comment]
Ah, so that's how it works.
