### ISSUE TITLE
Keybinding display consistency

### ISSUE THREAD

**Issue by ZeroInternalReflection** [CleverRaven/Cataclysm-DDA#58846]
### Is your feature request related to a problem? Please describe.

Many of the UI screens in CDDA show keybindings for common actions, which is great.  However, there is very little consistency in how those keybindings are shown, meaning it's not always clear if something is a keybinding, or if that keybinding works in the current context.  For example...
Sometimes the keybindings are described with words rather than the actual key name:
![Crafting - Filter screen -- 103x34](https://user-images.githubusercontent.com/89038572/167521440-57208844-5756-4832-87fe-9ec5ae80cf9c.png)

(In this case, if the user changes the keybinding for this action, the hint is now incorrect.  It also means that the keybinding needs to be translated)

Sometimes the keybindings are flagged by being in a different colour, such as:
Green
![Actions - Combat -- 80x24](https://user-images.githubusercontent.com/89038572/167330265-48639872-96d2-4fe5-8a9b-c2b830f719f8.png) 

Yellow:
![Base camp - Inspect NPC -- 80x24](https://user-images.githubusercontent.com/89038572/169736605-09f3cb07-30d9-4745-8af1-4a466bedd82c.png)

Blue:
![Main menu - Help - Details -- 80x24](https://user-images.githubusercontent.com/89038572/166125099-c20d3392-5708-4d26-8c82-d4a3aa6c86d6.png)

White:
![Debug error prompt -- 80x24](https://user-images.githubusercontent.com/89038572/167521441-fda560e6-2e53-4ace-a216-bedc873e618d.png)

Sometimes the keybindings are left to match the adjacent text, in:
White: 
![Activate (a) -- 80x24](https://user-images.githubusercontent.com/89038572/166401118-34114026-4ca3-47a9-9f4a-9c32f32e8613.png)

Dark Gray (shows as magenta in my configuration):
![Activate - Gun modification - Risk damage -- 80x24](https://user-images.githubusercontent.com/89038572/170834473-dab1fcbc-2de8-4044-803a-c3def9681c2a.png)

Yellow:
![Examine vehicle - Crew -- 80x24](https://user-images.githubusercontent.com/89038572/169736589-d183c1c3-ef8d-49da-88a2-81ded29d0326.png)

Green:
![Look around (x) -- 80x24](https://user-images.githubusercontent.com/89038572/166250088-c351c1ed-286a-467b-a811-d9600f5c6195.png)

Red:
![Defense mode - Caravan -- 80x24](https://user-images.githubusercontent.com/89038572/169736568-4b22e63b-3e82-43b4-8604-7592e470a819.png) 

Red and green:
![Look around -- 80x27](https://user-images.githubusercontent.com/89038572/176701643-c2114afe-3001-48a0-94ff-1c65fe146bdd.png)

Red and green and light blue:
![Mutations ( ) -- 80x24](https://user-images.githubusercontent.com/89038572/166156885-c5764992-6791-41a1-a9d3-cbd43701cae5.png)

Sometimes the keybindings are the same colour, but **bold**:
![Pickup (g) -- 80x24](https://user-images.githubusercontent.com/89038572/166157221-bae733eb-7427-44ed-ac46-0af7bb700f5c.png)

Sometimes the keybindings are in (parentheses):
![Workout -- 80x24](https://user-images.githubusercontent.com/89038572/168921872-7b5b3139-8b0d-4205-abe8-f8df221c6f86.png)

Sometimes the keybindings are in [brackets]:
![Proficiencies (@p) -- 80x24](https://user-images.githubusercontent.com/89038572/166158097-d043c93d-cd1d-4931-baf5-63a432957e30.png)

Sometimes the keybindings are in _both_ (parentheses) and [brackets]:
![Diary - Edit text -- 80x24](https://user-images.githubusercontent.com/89038572/167521444-2f98ee1e-c49e-44d2-b145-2fc414ac9744.png)

Sometimes the keybindings are in angle brackets:
![View items (V) -- 80x24](https://user-images.githubusercontent.com/89038572/166167087-573f1091-2b39-4c0e-a343-d2b370a737fa.png)

Sometimes the keybindings are in  **double** angle brackets:
![Keybindings -- 80x24 -- Russian](https://user-images.githubusercontent.com/89038572/173203132-98cb8c85-a9cf-43a1-8c5f-e363a8dda8ad.png)

Sometimes the keybindings are in 'quotes':
![Software - Snake - Game over -- 80x24](https://user-images.githubusercontent.com/89038572/170140775-1d34e739-fc1a-4035-befb-049eda0b220c.png) 

Sometimes the keybindings have their own column to separate them from the corresponding action:
![Bionics -- 80x24 -- With scrollbar](https://user-images.githubusercontent.com/89038572/168948606-687baf4c-ddfc-4fdb-a598-46ebe4c3c416.png)

Sometimes the keybindings have their own rows to separate them from the corresponding action:
![Sidebar options (}) -- 80x24](https://user-images.githubusercontent.com/89038572/166165776-a6781656-150b-4436-807c-adba3ac7faf8.png)

Sometimes the keybindings use a colon to separate them from the action:
![Main menu - Help -- 80x24](https://user-images.githubusercontent.com/89038572/166125088-b509bce4-7b91-4f2e-8b85-372566ea6230.png)

Sometimes an effort is made to display the keybinding within the description of the action:
![Zones manager – 80x24](https://user-images.githubusercontent.com/89038572/168921878-4158fd24-84bb-481b-9790-3e3ae4838b85.png)

Sometimes the keybinding is displayed outside of the action description even when it would fit:
![Look around - Extended description -- 80x24](https://user-images.githubusercontent.com/89038572/167272907-538111da-66cd-4117-8754-bb92db0182a1.png) 

This is anarchy.

### Solution you would like.

1] Avoid the use of text descriptions of keybindings, since those can't be updated if the keybinding changes
2] When a keybinding is being listed, it should stand out from the surrounding text, both by colour and by formatting
3] Standardize on a single colour for keybinding display.  One colour for an active keybinding and a different colour for an inactive keybinding (e.g. the gun modification UI above where the character didn't have a firearm repair kit to use) would also make sense.
For reference, in a survey of 361 different UI screens in the game (not comprehensive, but eh), I noted the following:
Keybninding colour|Count|Percentage
--|--|--
No keybindings shown|65|18%
Blue/Light blue|4|1%
Dark Gray|10|3%
Green|206|57%
Red|6|2%
White|69|19%
Yellow|25|7%

And yes those numbers do add up to more than 100%. 
Green for active, dark gray or red for inactive seems fairly natural, but green, red and dark gray are commonly used to flag certain types of text, so it wouldn't necessarily stand out.

4] The keybinding colour should not be used for other text highlighting (see the crafting filter screen above, where yellow is used to flag both keybindings and filter prefixes).

5] Formatting to draw attention to keybindings should be consistent (e.g. the use of brackets vs. parentheses vs. angle brackets vs. columns vs. rows vs. double angle brackets vs. quotes)

6] Whether the game tries to fit keybindings into the description of the action should be consistent.
I think trying to highlight the keybinding within the action looks good, and there are benefits for screen real estate, but it means that anyone who doesn't notice the colour difference (e.g. colour blindness/use of screen readers) won't be told what the keybinding is.  Of course, a screen reader giving a constant refrain of "left bracket a right bracket left bracket b right bracket left bracket c right bracket" probably isn't fantastic either.

### Describe alternatives you have considered.

- Ignore the inconsistencies and resulting player confusion and aesthetic annoyance
- Standardize the appearance of keybindings in some other way I haven't thought of

### Additional context

I'm not differentiating here between keybindings defined in keybindings.json and invlets (I think that's the term used in most places in the code) that are generated when managing inventory or creating uilists.  At the end of the day, both are "press listed key, action happens"
Yes, each individual inconsistency is a minor issue.  In aggregate I find it surprisingly annoying.

**Comment by descan** [comment]
The screen-reader issue would be fixed by having them separated by a short word (vocalized, that is). Like "a: accept" would come out as "a colon accept." My preference would be a colon.

Of course, other languages using screen readers might have translations for those symbols that are not quite so short, but retaining the "nothing on the left side" aspect would at least standardize the "First letter is the key binding, word after the colon is what the key bind does" aspect.

**Comment by descan** [comment]
As for the colours - some of the ones you highlighted, are different because they stand out on that screen. The white on the red error screen, for example - a red "Bad/Important Keybind" colour wouldn't stand out on that screen, while otherwise it would. Some of them, of course, aren't so clear-cut on *why* they're a certain colour, or why there are multiple different colours used on the same screen.

**Comment by ZeroInternalReflection** [comment]
> The benefits of screen real-estate might be served by having an option for "Keybindings: Inset, Separated." People who have difficulty differentiating the inserted keybinds would use one option, while people who value screen real estate could use the other.

I do like the idea of an option for that, though I'm not sure what the general dev team preference is on UI options like that.  I think the main trick would be ensuring the option is linked everywhere.  Part of why this is a bit of a mess right now is because there are a _lot_ of locations that display keybindings.

> As for the colours - some of the ones you highlighted, are different because they stand out on that screen

I'd be perfectly happy with a home jersey/away jersey style, where in context 1, it's colour 2, and in context 2, it's colour 1.  I think that's just as much work as standardizing on one distinct colour though.

> The screen-reader issue would be fixed by having them separated by a short word (vocalized, that is). Like "a: accept" would come out as "a colon accept." My preference would be a colon, although a dash is quicker vocalized - the colon takes up less screen space.

I had not thought about how much faster some punctuation is for a screen reader to say.  That's definitely a factor to consider, particularly for an inset vs. separated option.
Interestingly, the help menu already uses "a: action" while the trade menu uses "a - item".  I'll need to check them out with a screen reader on for comparison.
I'm also curious whether that format would still work out for more complicated keybindings.  e.g. "ESC, q, Q, or SPACE: close".
