### ISSUE TITLE
Water is nonconductive

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#58849]
### Describe the bug

Under materials.json, water is considered conductive, yet when you examine water or clean water in game, it is described, "this item does not conduct electricity."

Materials.json entry below: 
 {
    "type": "material",
    "id": "water",
    "name": "Water",
    "density": 1.0,
    "specific_heat_liquid": 4.186,
    "specific_heat_solid": 2.108,
    "latent_heat": 333,
    "edible": true,
    "bash_resist": 0,
    "cut_resist": 0,
    "bullet_resist": 0,
    "acid_resist": 0,
    "fire_resist": 1,
    "conductive": true,
    "chip_resist": 0,
    "dmg_adj": [ "lightly damaged", "damaged", "very damaged", "thoroughly damaged" ],
    "bash_dmg_verb": "damaged",
    "cut_dmg_verb": "damaged",
    "burn_data": [
      { "fuel": -100, "smoke": 1, "burn": 1 },
      { "fuel": -50, "smoke": 2, "burn": 1 },
      { "fuel": -10, "smoke": 2, "burn": 2 }
    ]
  },

### Steps to reproduce

Start up a game, make a makeshift pot, scoop some water out of a toilet, and then examine the water in inventory. 

### Expected behavior

Water from a toilet bowl (any water that is not distilled water) should conduct electricity. 

### Screenshots

![unknown](https://user-images.githubusercontent.com/108444328/176737526-cecd6a81-b349-4fe2-b69a-7d6e3705487a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Theawesomeboophis** [comment]
Pure water is non-conductive, the minerals are what make water conductive, not sure if clean water in-game is pure or if clean refers to the actual cleanliness of the water, it seems to indicate the actual cleanliness, but lake and river water should definitely be conductive as it's unpure.

**Comment by descan** [comment]
I think the concern here is that "water" is "conductive:true" in the JSON, but "water" in-game is not. So either the in-game water is using a different JSON file for its properties, or for some reason the file isn't bearing true in the game. 

Whether or not "water" is conductive in real-life is secondary to a material not retaining its JSONized properties - then realism doesn't really matter, the game'll just do whatever, no matter how realistic the files are coded to be. :P

**Comment by Qrox** [comment]
The item definition of water does not specify its material (neither do clean water, mineral water, salt water, sewage water, and soapy water), so the game doesn't know water is actually, well, water.

**Comment by kevingranade** [comment]
Considering that the purpose of this message is using items in melee,  liquids could simply not display it.
