### ISSUE TITLE
Appliance battery or Standing lamp either or are not draining charge from Large storage battery (May extend to others)

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#58850]
### Describe the bug

The charge is not being drained from a large storage battery, when either using the oven and or standing light.

### Steps to reproduce

Place down a large battery with charge.
Connect it up to a device that uses charge.
Use said device.

### Expected behavior

For it to drain charge out of the large storage battery. 

### Screenshots

![image](https://user-images.githubusercontent.com/5264667/176746641-bca820bb-aea2-4a9c-97c5-a3b4ea499ca7.png)
![image](https://user-images.githubusercontent.com/5264667/176746656-f9b9a42b-a1b3-4d59-9d56-aa2972f2d222.png)
![image](https://user-images.githubusercontent.com/5264667/176746665-d7242ab5-281b-4ecf-b6c2-2ffdad374042.png)
![image](https://user-images.githubusercontent.com/5264667/176746675-4f7c1626-4d07-4331-8daf-bf425952998d.png)
![image](https://user-images.githubusercontent.com/5264667/176746689-83845c10-94e0-412a-a5c5-70398ab72634.png)
![image](https://user-images.githubusercontent.com/5264667/176748051-f7747d62-208a-4e74-93de-079cfcb05e21.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 873f768 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Mythical Martial Arts [MMA],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Blaze Industries [blazeindustries],
    Useful Helicopters Experimental [useful_helicopters],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    Aftershock [aftershock],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch]
]

**Comment by epsimpson** [comment]
This MAYBE sounds related to what I just saw?  My large battery does drain, but too slow (the box battery charger by itself adds more charge than it draws from the large battery), but my large battery spontaneously fully recharged itself overnight.  Unfortunately my setup is maybe too complicate to help debug.

I thought it was a CASR generator issue.  I have a large battery being charged by a CASR generator.  When I noticed the battery full I turned OFF the generator, and have been watching the battery steadily drain, checking it every morning, thinking I'll just click on the generator when it emptied.  This morning the battery is 49999/50000.  Checked the generator and it is indeed off and showing zero power.

I just did several hours with the lamp on and the battery is still draining.

Unfortunately my setup is maybe too complicate to help debug.   I will create a save file before sleeping from now on in case it happens again (my save file right now is 3.8MB as a tar.gz, what is the file size limit again?)

I have a turned off CASR generator inside the first floor feeding a large battery on the balcony above it.

First floor CASR -> wall wire -> outside extension -> second floor large battery -> outside extension -> wall wire -> oven/freezer/fridge -> inside extension -> standing lamp -> box battery charger (1 tile space between lamp and charger).

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-11363-gfd463d4697 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
