### ISSUE TITLE
Add ThemeManager to control UI colors

### ISSUE THREAD

**Issue by leemuar** [CleverRaven/Cataclysm-DDA#58865]
### Is your feature request related to a problem? Please describe.

Continue great work of https://github.com/CleverRaven/Cataclysm-DDA/pull/58646 and [58646](https://github.com/CleverRaven/Cataclysm-DDA/pull/58856) and instead of redefining color "constant" implement a UI ThemeManager.

### Solution you would like.

Currently color switching is implemented by changing color constants: c_black = (255, 255, 255). This works, but it is hacky.
Instead of changing color "constants" I would like to have a distinct color theme manager, and refactor all UI to get colors from it

instead of

```
c_black_white
```

use

```
ThemeManager.set( "border_color", (255, 255, 255) )

ThemeManager.get( "unread_book_text_color" )
ThemeManager.get( "low_skill_text_color" )
ThemeManager.get( "border_color" )
ThemeManager.get( "window_background_color" )
ThemeManager.get( "damaged_limb_color" )
```

This will allow us to encapsulate all UI color management in a single object, switch colors on-the-fly, save and load themes from JSON etc

**Comment by leemuar** [comment]
[vetall812](https://github.com/vetall812) pinging you so you know about this issue continuing great work of yours

**Comment by vetall812** [comment]
> @vetall812 pinging you so you know about this issue continuing great work of yours

Thank you!

**Comment by kevingranade** [comment]
Overdue closure for stale issue,  this is less an issue and more a personal TODO. 
If someone wants to work on this,  great,  but we can't afford to keep around thousands of,  "it would be nice if we..." type issues.
