### ISSUE TITLE
Cooked liver is considered raw food

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#58877]
### Describe the bug

Cooked liver is considered as raw food and as such has decreased nutritional value.

### Steps to reproduce

1. Spawn _raw liver_ food item.
2. Cook _cooked liver_ item from _raw liver_.
3. Observe that item information says it is considered **raw**.

### Expected behavior

Cooked liver should not be considered raw item because it's already cooked.

### Screenshots

![cataclysm-tiles_IMCenZSWfs](https://user-images.githubusercontent.com/16436920/176963995-f0651791-7a4e-49b0-9c4b-e49875926365.png)

### Versions and configuration

Game Version: 55adc9a

**Comment by natsirt721** [comment]
The same thing appears for cooked brains, kidney, and lung. 

Looks like this was done intentionally under #50221

**Comment by matshou** [comment]
> Apparrently the recipes are supposed to handle the removal of the flags.

This seems to be handled here but like you mention apparently doesn't work: 
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/crafting.cpp#L1747-L1755
