### ISSUE TITLE
Highlight nearby hostile creatures

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#58880]
### Is your feature request related to a problem? Please describe.

In some tilesets, particularly NeoDays/RetroDays, it can be really difficult to pick out monsters from the background, especially in low light conditions.

![Screenshot of the character and a nearby zombie dog, barely visible, using the NeoDays tileset](https://user-images.githubusercontent.com/172800/176969162-709aaa52-e6ac-4897-ad62-4dc0b3124b5f.png)

Spot the zombie here! Safe mode is on and was triggered, so it's definitely _somewhere_
![A zombie hiding outside the window, barely visible](https://user-images.githubusercontent.com/172800/176969755-2553c0a4-1b54-43b2-bf3e-3c8fc4b06065.png)

### Solution you would like.

There should be a way to visually highlight nearby hostile creatures. I can imagine a variety of different ways to make them stand out more clearly:

1. render monsters at "full lighting" conditions, rather than in sepia/grayscale, and keep terrain dark.
2. draw a border/indicator over the creature, either an outline or an overlay
3. use some other highlighting effect, e.g. a glow, slow flash, some kind of animation, a procedurally-rendered green outline, etc.
4. do one of the above, but only in (V) mode

### Describe alternatives you have considered.

I can see an argument that it's atmospherically appropriate for zombies to be hard to spot, but given Safe Mode already halts the game whenever you see a zombie, I'm not sure the rest of the game's mechanics support that.

Perhaps this highlighting mode could be enabled only when Safe Mode is on, or possibly controlled by a menu option so it's toggleable for those that like being unable to see a zombie in the night :)

**Comment by PatrikLundell** [comment]
Related, but not the same, is when creatures are "hidden" behind a tree or other object that obscures the tile above it from the player, but clearly visible to the PC (move the "something, somewhere" two tiles to the NE for a partial case, and to the tile N of the tree for a full one).

**Comment by nornagon** [comment]
Tested this out locally, here's what it looks like to always render monsters at lit_level::LIT regardless of lighting:

<img width="554" alt="Screen Shot 2022-07-03 at 1 53 15 PM" src="https://user-images.githubusercontent.com/172800/177056944-d8d5c9e3-1535-4c30-bc01-de39b0fc9d95.png">

or with UltiCa:
<img width="789" alt="Screen Shot 2022-07-03 at 1 54 29 PM" src="https://user-images.githubusercontent.com/172800/177056971-35a0540c-b3a9-4bd7-871c-ace94e544240.png">

I'm not sure I love this thematically, but it does make monsters MUCH easier to see!

**Comment by nornagon** [comment]
Hm, I think the problem isn't just at night time. See this screenshot from full day, with three ants in the field:

![image](https://user-images.githubusercontent.com/172800/178072311-ce9d03d4-cf9a-4073-baf6-0a6ef157c2f1.png)

So perhaps a border/highlight/overlay is the way to go

**Comment by nornagon** [comment]
Bump--

j
