### ISSUE TITLE
Using GCC 12 for the CI

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#58884]
### Is your feature request related to a problem? Please describe.

GCC 12 was released a while ago and it exposed some errors, see #58123

### Solution you would like.

Testing and eventually using GCC 12 for the CI. Afaik it also includes new linting methods, catching errors like the one mentioned above.
I can successfully build with GCC 12 locally, so it hopefully should not be too much work.

**Comment by kevingranade** [comment]
One of the ci targets bumped to gcc 12 as of #63672
