### ISSUE TITLE
Reliable segfault when attaching a wielded gunmod to a gun

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58899]
### Describe the bug

The game reliably segfaults upon the following reproduction steps

### Steps to reproduce

1. Get a handgun (tested with M17)
2. Get a handgun mod (tested with red dot sight)
3. Ensure that your handguns and marksmanship skills are at least 2 to be able to proceed
4. 'w'ield the red dot sight
5. 'A' to attach the gunmod -> select M17 from the menu -> confirm modification -> "Store in inventory" (**it is unclear what this step means or what it does**) -> crash

### Expected behavior

I expect to be able to attach a gunmod without a crash

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-06-30-0619
Mod list: default

**Comment by PatrikLundell** [comment]
The step about storing in inventory is there to free up the hands for the crafting. You can also drop the item to the ground to free up the hands.
