### ISSUE TITLE
Can you make foldable big electric dehydrator?

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#58892]
### Is your feature request related to a problem? Please describe.

We have a foldable "metal smoking rack" but we don't have an electric analog, although we do have a food dehydrator. This will also make the game easier for the players, as there will be no need to farm coal

### Solution you would like.

Add big foldable dehydrator recipe, and also add ability to connect it to vehicle to use its power
Add ability to use big foldable dehydrator as analog of smoking rack, make it dehydrate food by itself, to prevent the player from manually drying food, and make it like analog of dehydrating instrument in crafting recipes
Unfold big dehydrator > connect to vehicle > load food in it > turn on > wait for same time > take dried food > fold big dehydrator if needed
Or you can make it like appliance, buildable from "build menu"
And mountable on vehicle too

### Describe alternatives you have considered.

No alternatives, we need this renewable source of preservation

### Additional context

I dont have magick power of programming and asking you, programm magician, to help me and other mortals in this hard quest

**Comment by PatrikLundell** [comment]
I don't think foldable is a good idea. Do you have any real world examples of any?

Appliances can generally be taken down into items and set up again, which provides the functionality you're (probably) really after. Foldable vehicles, in contrast, are typically used to move vehicles between places where you can't drive or drag them (e.g. up/down stairs).

I do, however, think that an electrically powered passive dehydrator appliance is a good idea. I don't think it would hurt to support it as a vehicle part as well.

**Comment by KHeket** [comment]
> Do you have any real world examples of any?

https://www.youtube.com/watch?v=0Vhf-EG0Iq8&ab_channel=AromaHousewares
or you can find it in youtube by "Aroma Collapsible Dehydrator [AFD-1000SD]"
I think, in post-apocalypse the character can craft such simple foldable construction
And I think it will be good idea to make 2 types of dehydrators:
1) Big foldable dehydrator, which will have little size in folded status. It will be very usefull for lond rides or players, who like to live in car
Similar to foldable metal smocking rack
2) And big dehydratorm which cannot be folded, which can store more food and can be only dismanteled as appliance, and will have size 90-150 liters like washing machine or something like that. It will be very usefull for bases and base players
Similar to only buildable smocking rack

**Comment by robob27** [comment]
They call that dehydrator collapsible but I think that's maybe a little of a stretch. I would argue it's more "easily assembled and disassembled". I don't think this is a good case for a "foldable" dehydrator. When I think foldable I think something that is 1 object before folding and still 1 object after folding, like a folding chair or foldable drying rack. I think the collapsible/easily assembled/disassembled dehydrator is fine, I just think it should still be treated as disassembly rather than folding.

I imagine it would have 2 recipes:

- one where the fan assembly isn't complete yet and all of that needs to be built (some electrical required)
- one where the fan is complete and it has been disassembled/collapsed after construction (maybe it could be found this way in electronic stores and assembled without any knowledge)

**Comment by KHeket** [comment]
> When I think foldable I think something that is 1 object before folding and still 1 object after folding, like a folding chair or foldable drying rack
But foldable smocking rack made from different parts too, and I think at least soo from pictures from internet. Box, cap, food drying rack, maybe legs. And we can make similar foldable dehydrator to prevent creating uselles crafting parts and make its easy to realise, becouse as you can see in video - this dehydrator made from 5 special metal sheets with fasteners, 1 metal sheet with holes and 1 part with fan and heat parts. And it will also solve the problem with loosing parts after dismantling

**Comment by kevingranade** [comment]
Overdue stale closure,  a big portable dehydrator is fine to add, but we need to clear out wish list issues.
