### ISSUE TITLE
Lumbering requirements inconsistent

### ISSUE THREAD

**Issue by robob27** [CleverRaven/Cataclysm-DDA#58895]
### Describe the bug

With an axe with 1 tree cutting, you cannot produce planks by activating the axe. The option doesn't appear because the tool quality isn't high enough.

However, if you have created a wood zone and use Shift+O/Organize Loot you are presented with an option to chop wood into planks and can produce planks that way.

I think it is related to these two bits of code here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/tool_qualities.json#L130

vs

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/activity_item_handling.cpp#L2710

### Steps to reproduce

1. Get a stone axe
2. Cut down a tree
3. Chop a trunk into logs
4. Observe that you cannot activate the axe to chop the log into planks
5. Create a Wood zone
6. Open the sort loot UI
7. Observe the chopping planks action is available
8. Chop some planks

### Expected behavior

Playing Innawood right now (reproduced in vanilla though) and feel like I was supposed to have progressed to bronze axe (with 2 tree cutting) to be able to make planks. If not, then I should probably be able to chop planks by activating the stone axe instead of only through sort loot UI.

### Screenshots

![image](https://user-images.githubusercontent.com/2104555/176994024-706a2d82-30db-4da5-86f8-1bd62cac8429.png)

![image](https://user-images.githubusercontent.com/2104555/176994029-e17aceb6-4dd1-44d0-a578-5dd4831fa76a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.160 (22H2)
- Game Version: 0.F-9540-g14471ad4d5-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by natsirt721** [comment]
Its always seemed weird to me that you can make planks using an axe at all. Planks are effectively a stand-in for dimensional lumber - it doesn't seem like an axe would have the precision needed to make even a rough simlarcium of that from a log. Use an adze or a plane to hew boards? Sure. Use a saw to cut them? No problem. But an axe just seems too coarse of a tool. 

Its also weird that you can (a)ctivate an axe to turn a log (item) into planks (item). There is already have a system for using tools to turn items into different items: crafting. Why is this even available in the axe use menu at all?
