### ISSUE TITLE
Game fails to load with: "ERROR : src/main_menu.cpp:1027 [bool main_menu::load_character_tab(const string&)] Error: MISSION_OLD_GUARD_NEC_1 (mission_type) has two definitions from the same source (dda)!"

### ISSUE THREAD

**Issue by zer0Entropy** [CleverRaven/Cataclysm-DDA#58905]
### Describe the bug

I just updated to the latest experimental release, and attempted to load a character that I'd been playing before updating (previous version was 06-27-1859, and the character definitely loaded and played fine in that one).  Also, I just checked, and it turns out I cannot create a new character either!  The loading process fails with the same error message, either way.

The game starts up fine, and shows my previously-created world under "Load" on the Main Menu.  When I select that world and press Enter, my character dutifully pops up and I am offered the opportunity to load it, as usual.

...and that's as far as I can get.  During the loading process, the game encounters an error that it presents as follows:
`ERROR : src/main_menu.cpp:1027 [bool main_menu::load_character_tab(const string&)] Error: MISSION_OLD_GUARD_NEC_1 (mission_type) has two definitions from the same source (dda)!`

Then, whether I press 'c' or 'i', the game immediately returns me to the Main Menu.
debug.log doesn't seem to include any other helpful information.  The line I copy-pasted above is immediately followed by "Log shutdown".

### Steps to reproduce

1.  Attempt to load the attached save file in the (as-of-writing) most recent experiment build (2022-07-02-0830).
2.  Observe its failure to load

### Expected behavior

I expected that my save file would successfully load, as it had merely minutes prior using an older experimental build.

### Versions and configuration

[please bear with me, I cannot access the game to do a proper "Generate game report"]
OS:  Pop! OS 22.04 LTS
Game Version:  bcf34db [build number 2022-07-02-0830] linux-tiles-x64
Graphics version: Tiles
Ingame language: English
Mods loaded: dda, no_npc_food, no_fungal_growth, package_bionic_professions

### Additional context

[Jeremy Watkins.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/9033247/Jeremy.Watkins.tar.gz)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9033249/debug.log)

**Comment by zer0Entropy** [comment]
Just tried loading the game in the previous build (2022-07-02-0705) -- success!  This bug definitely emerged from changes in the most recent commit.

**Comment by AlecVoid** [comment]
Yeah. Same here. 

Old savegame with version cdda-linux-tiles-x64-2022-06-16-0508 and new version cdda-linux-tiles-x64-2022-06-16-0508 won't load but shows error: MISSION_OLD_GUARD_NEC_1 (mission_type) has two definitions from the same source

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/59578
