### ISSUE TITLE
Fatally cold temperatures don't interrupt crafting

### ISSUE THREAD

**Issue by robob27** [CleverRaven/Cataclysm-DDA#58921]
### Describe the bug

If you are crafting something that takes a long time outside and it starts getting really cold, you can suffer fatal damage without any sort of interruption. This can lead to a very quick death as it is then on the player to notice and quickly press `.` to stop, with the window to do so varying based on how fast their computer is.

### Steps to reproduce

1. Make a player with the necessary skills/components to craft something that takes a decent amount of time (I used anvil) and a light source that doesn't produce heat (I used atomic lamp)
2. Change the time to hour 0, day 61 spring and change the weather to raining
3. Start crafting the item
4. Observe your health rapidly (depending on your computer) decreasing with messages that say "Your x hurts!" (x = all the limbs). Observe that you have no pain and the crafting is not interrupted.

### Expected behavior

I expect that if something is killing me while I'm crafting, I should be notified at least once and given the opportunity the stop the crafting. Contrasting this to when I had early scurvy, I had to constantly spam N to continue activities because of the pain even though that was not causing massive damage on my limbs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.160 (22H2)
- Game Version: 0.F-9575-g35ac51b95f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This happened while I was crafting some nails outside. It was night time when I started, but I had a fire going nearby to stay comfortable. It started raining and I just lost half the health on all of my limbs almost instantly. I have nothing going on in my reality bubble so things happen very very fast.

I think if this damage caused pain, it would probably work as expected. So the bug might just be that this damage from extreme temperatures isn't causing pain?

![image](https://user-images.githubusercontent.com/2104555/177020250-f258588c-5de2-43b4-a1f7-8df4f180ed17.png)

Additional screenshot just showing that my custom sidebar does show pain properly when there (caused this pain through debug menu);

![image](https://user-images.githubusercontent.com/2104555/177020261-d807d670-bb8e-4a7d-832c-8406dc565a10.png)

**Comment by robob27** [comment]
I noticed in another playthrough that this also applies to lockpicking. Basically seems like any activity is not interrupted.

**Comment by robob27** [comment]
I looked into this a bit more. The reason the cold doesn't cause pain is because the cold effect adds a painkiller effect to the player to simulate numbness from the cold. The painkiller intensity always outpaces the damage from the cold (1 at a time) so no pain is caused and `on_hurt` is not called.

So this seems intentional.. albeit a little strangely implemented (being cold should probably not cause the exact same status effect as taking aspirin). Maybe it's just a little too aggressive? In my test, it's 11 degrees celsius, spring, with a gentle breeze. I don't think this would cause numbness to the point where I die from exposure without noticing something isn't right (disclaimer: am Canadian lol). Maybe the painkiller effect should be moved to the frostbite/frostnip effect for now?

**Comment by Zireael07** [comment]
I would keep the painkiller effect as is, but make temp itself interrupt activities (i.e. more things than pain/wounds should interrupt)
