### ISSUE TITLE
When in the new portal storm maze/dungeon, sometimes the entire structure disappears

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#58925]
### Describe the bug

I ventured into the new dungeon like structure recently introduced for portal storms. As I was moving through it, the structure while doing its usual shifting, had suddenly disappeared, leaving me high in the sky.

But oddly enough, waiting turns does not make me fall. But if I try to move, it asks me if I really want to move to this ledge.

Also for context of how long it took before this happened, I was able to reach the portals at the end of the level, although I picked one which sent me to the start. The structure disappeared as I was halfway from reaching those portals again.

### Steps to reproduce

1. Trigger Portal Storm
2. Enter dungeon
3. Move around or wait
4. The entire structure will disappear.

### Expected behavior

It shouldn't disappear. Unless it is supposed to... It's not very clear what one might do after this though.

### Screenshots

Here my character is stuck in the air. The shifting masses that were also in the maze are here with me.
![image](https://user-images.githubusercontent.com/88375697/177025552-344ae705-1210-4e97-b8cd-0ee6b58b676c.png)
Also notice in my tiny overmap above the temperature reading, my memorized vehicles are shown to be below me, not far from where I entered the structure that spawned near my base

I wasn't gonna lose this character to a bug, so I teleported to the ground. Here is the ground level entrance, however the portal has despawned
![image](https://user-images.githubusercontent.com/88375697/177025958-d9d72155-1857-45d5-ae3f-5266ca9ea8af.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 26b4c80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Ramza13** [comment]
Hmmm weird. I'll try to take a look at this tomorrow, thanks for the report
