### ISSUE TITLE
The game did not quit properly last time

### ISSUE THREAD

**Issue by Mob6092** [CleverRaven/Cataclysm-DDA#58927]
### Describe the bug

I would like to seek you assistance on resolving my concern. I accidentally uninstalled the game and by the time I've reinstalled the game again, this error message always show up. Please, I've missed playing the gane for months now and I really dont know what to do Ive already reported through google playstore and through reddit but still no updates yet. Please see the attached file for the error message. []() 
![Screenshot_20220518_165500_com cleverraven cataclysmdda](https://user-images.githubusercontent.com/108603571/177026515-925f4d2a-4c93-4e15-8042-e7942adf1e81.jpg)

### Steps to reproduce

N/A

### Expected behavior

I want to played this awesome game again

### Screenshots

Please see screenshot below
![Screenshot_20220518_165500_com cleverraven cataclysmdda](https://user-images.githubusercontent.com/108603571/177026547-44d9d7cc-0b15-4b1e-be91-0b903d46b0f5.jpg)

### Versions and configuration

N/A

**Comment by robob27** [comment]
Is this on android?

If so, try uninstalling the app again, and then use a file manager to move the folder /Android/data/com.cleverraven.cataclysmdda (or whatever your folder in there is called) to another location to back it up (in case you have anything you care about, maybe you can restore save/config data after, otherwise just delete it). After that, try reinstalling the app again and see if you have the same issue.

**Comment by BrettDong** [comment]
Try changing the Software Renderer setting.

**Comment by Mob6092** [comment]
> Is this on android?
> 
> If so, try uninstalling the app again, and then use a file manager to move the folder /Android/data/com.cleverraven.cataclysmdda (or whatever your folder in there is called) to another location to back it up (in case you have anything you care about, maybe you can restore save/config data after, otherwise just delete it). After that, try reinstalling the app again and see if you have the same issue.
> 
> If you do have the same issue, maybe the app is having trouble with some setting/other app on your phone. In that case maybe you could try a [recent experimental build](https://github.com/CleverRaven/Cataclysm-DDA/releases) to see if the issue if fixed there.

I downloaded the experimental build but still have the same issue but let me try the deleting the folder first if that works. Thanks for the help. I appreciated.

**Comment by Mob6092** [comment]
> Try changing the Software Renderer setting.

How can I change the software rendering setting?

**Comment by Mob6092** [comment]
> When you launch the app for the first time, there is a dialog of three to four checkboxes. The middle one is a setting called Software Rendering. Try a different setting and see if the crash can be solved.

I tried doing that but still got the same issues. However I tried downloading the link robob27 recommended and I was able to play the game now but I cannot select what type of point system to choose. It will give me the same error but so far so good that I am able to play the game now😁

**Comment by kevingranade** [comment]
Catching up stale issue closures.
