### ISSUE TITLE
item description error on experimental version 26b4c80

### ISSUE THREAD

**Issue by mhare323432** [CleverRaven/Cataclysm-DDA#58923]
### Describe the bug

world generation failure due to duplicated item description

### Steps to reproduce

starting game

### Expected behavior

world generation 

### Screenshots

![Screenshot 2022-07-02 213510](https://user-images.githubusercontent.com/57967900/177021069-95a7ca78-9daf-4082-ad68-28c5a62435ab.png)

### Versions and configuration

experimental ver. 26b4c80
mod: [for world] (no new ones besides those that come with install)
 
![Screenshot 2022-07-02 214234](https://user-images.githubusercontent.com/57967900/177021174-4921e859-dbd2-4f6b-9f1f-aed9cbdc1391.png)

### Additional context

this is a fresh install with only addition being the Utica tile pack

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-12380.
