### ISSUE TITLE
Monsters can't see you if you don't see them

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#58938]
### Describe the bug

Monsters can't see you if you don't see them.

### Steps to reproduce

1. Get blindfold.
2. Find or spawn a monster with ranged attack, turret is a perfect example since it's immobile, and get into its attack range.
3. Wear blindfold.
4. Notice that turret won't attack you.
5. Take off blindfold.
6. Notice that turret starts attacking you immediately.
7. Optional: get debug clairvoyance mutation and notice that turret indeed can't see you if you don't see it.

### Expected behavior

Monsters should see you no matter what state your vision in.

### Screenshots

I'm wearing my blindfold, the turret is several tiles to the right of me, but isn't seen
![изображение](https://user-images.githubusercontent.com/11132525/177045932-51310e9b-82a5-49ef-b73f-13f390dba4ac.png)

I'm still wearing my blindfold, but now I have debug clairvoyance mutation
![изображение](https://user-images.githubusercontent.com/11132525/177046016-295f3632-21d7-4d3d-b067-458e99e8a471.png)

### Versions and configuration

0.F-9595, Windows 10 x64.

### Additional context

There is also another bug with vision: after taking off blindfold, my sight isn't returning if I'm just waiting in place (by pressing `.`). It returns immediately if I make a move or make any other activity.

**Comment by andrei8l** [comment]
Another bug introduced by #56231, specifically [this line](https://github.com/MylieDaniels/Cataclysm-DDA/blob/63ff14af028afcbe30f4f81be6a2b13e136a4900/src/lightmap.cpp#L995). Reverting it to `0` fixes this issue
