### ISSUE TITLE
Where are all the ferals that appear hiding out initially?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#58934]
### Describe the bug

As time goes by, the proportion of ferals in the "zombie" population seems to increase, which doesn't make sense from a lore perspective.

Initially you may very occasionally encounter a feral when visiting a city, but over time the proportion has increased rather substantially, with something like a quarter of the "zombies" in a park cluster being ferals toward the middle of the autumn (standard starting time and zombie progression rate, but significantly lowered number of zombies).

### Steps to reproduce

1. Start a normal game on 0.F-0
2. Play your way to the autumn while upgrading to newer experimental versions at uneven interval.
3. Find that the feral proportion of the "zombie" population increase gradually.

### Expected behavior

One of a few alternatives:
- A fairly constant proportion of the "zombie" population being feral.
- An initial, almost feral free, grace period followed by rapid increase of the feral proportion to a new proportion with a hand wavey explanation that the ferals somehow were in hiding or hibernation and haven't joined the zombie population until now.
- A lore explanation for why the ferals population just seems to keep increasing.

### Versions and configuration

- Windows 10.1
- 0.F-0 and various experimental version up until a couple of weeks ago.
- Default set of "mods".
- Default start time.
- Default zombie evolution rate.
- Heavily reduced zombie spawn rate (0.2) so you don't open a barn gate and is greeted with the whole population of the surrounding 5 farms holed up in there, packed three lines deep (plus additional ones pouring out of the door they break down. I don't even know how they'd be able to pack 150 zombies into an infested gun store, as opposed to the 30 I've seen).

### Additional context

It's possible the increase is caused by changes in the experimental versions so the effect seen is caused by later encounters being generated using much higher feral proportions than the earlier versions, and thus that new games with the later version would get these high feral populations immediately. That would be a rather sharp spike in difficulty, however, given how deadly ferals with 100% ranged accuracy would be against unarmored PCs.

**Comment by DamienRoyan** [comment]
The initial riots were a mix of the zombies + people turned feral.
Some NPC backstories say that they were ferals turned to normal.

It would be possible that extreme stress turns people feral, so as time goes on and resources become scarce, survivors with low willpower finally start turning feral.
I'm not sure if this is the intended lore, but it's always how I thought of it.

**Comment by PatrikLundell** [comment]
My understanding of the lore is that blob psychosis turned people violent but not into ferals. From there, some progressed into ferals, with the included unrecoverable brain damage, while the rest recovered from the psychosis to a new state ranging from highly aggressive (I guess that's where the Psychos you can encounter are), to enhanced risk taking, and back to normal, over a spectrum.

I haven't seen any lore indication of new ferals being generated, and even if they would be, how could these unstable persons have survived surrounded by zombies without being protected by the feral zombie affiliation?
The number of survivors is very low, so the pool of bodies available to produce new ferals (or zombies, for that matter) even if it would happen is far too low to account for all the ferals popping up.
