### ISSUE TITLE
Iso Tileset don't display properly when loading the game

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#58945]
### Describe the bug

Iso Tileset don't display properly when loading the game

### Steps to reproduce

 - Set tileset to an iso tileset
 - close the game
 - reload > the display is messed up as the tileset is displayed like regular tileset
 - change to a regular tileset
 - change back to iso > the display is fixed

### Expected behavior

Iso tileset should display properly directly when loading the game

### Screenshots

Normal display 
![image](https://user-images.githubusercontent.com/41293484/177051831-9b590f0b-ca5f-45aa-b0e4-87e1968fb9e6.png)

Display after closing the game and reloading
![image](https://user-images.githubusercontent.com/41293484/177051851-91d6846b-3036-4647-acc6-e895d143e5e0.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 0.F-9606-gf47e9ad1c1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by Qrox** [comment]
#57123

**Comment by esotericist** [comment]
closing as duplicate (and raising the status of the older issue)
