### ISSUE TITLE
Implement an ability to put items into a container outside of inventory

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58943]
### Is your feature request related to a problem? Please describe.

Currently it is impossible to insert items into a container (backpack, etc) that is located outside of your inventory. This could be useful in a situation where you drop a bag with some items to collect it later, then come back to it and want to add some more items inside.

### Solution you would like.

It would be nice to be able to perform and 'i'nsert command on a container outside your inventory

### Describe alternatives you have considered.

Cannot think of any

**Comment by Cimanyd0** [comment]
I drag a shopping cart everywhere, with a toolbox in it with tools I want to drag everywhere. To insert any new item into the toolbox, I must drop enough stuff that I can hold the toolbox's weight, pick it up, insert the item, and put it back in the cart.
