### ISSUE TITLE
Sidebar UI, W_NO_PADDING behavior

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#58959]
### Describe the bug

Using W_NO_PADDING flag breaks columns width calculation and removing necessary padding for column arrangement.

Removed padding still used in calculation for elements width:
" DEBUG    : widget layout is wider than sidebar allows."
But all sizes are calculated manually and should fit.

### Steps to reproduce

Use attached sidebar.

### Expected behavior

![image](https://user-images.githubusercontent.com/6676374/177123619-3b72992a-cac2-4884-84eb-960dd57554fa.png)

### Screenshots

![image](https://user-images.githubusercontent.com/6676374/177124118-69fe0359-6e09-4d83-9b77-e81bc24c94cf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[!_sidebar.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9038119/_sidebar.zip)

**Comment by Inglonias** [comment]
Sidebar padding is now configurable thanks to #58792. Does setting `"padding": 0` result in more desirable behavior?

**Comment by vetall812** [comment]
> Sidebar padding is now configurable thanks to #58792. Does setting `"padding": 0` result in more desirable behavior?

Nope. Doesn't work at all.
![image](https://user-images.githubusercontent.com/6676374/177300579-7175a856-ed45-4c36-93c2-f0e598ddab6f.png)

**Comment by vetall812** [comment]
It seems that my sidebar have a deep structure, and it breaks somewhere.

**Comment by vetall812** [comment]
> Sidebar padding is now configurable thanks to #58792. Does setting `"padding": 0` result in more desirable behavior?

it looks like flag W_NO_PADDING, and "padding": 0 should yield the same result, but yet both fails )

**Comment by Inglonias** [comment]
They are slightly different, and someone should probably look at that.

It sounds like what you're after is absolute positional control of sidebar widgets, which would probably have to be added explicitly as a feature.

**Comment by Inglonias** [comment]
My proposal to deal with this is to remove the NO_PADDING flag, and instead replace it with something like MANUAL_ALIGNMENT, that, when true, guarantees that what you type is what gets printed on each line, assuming the line is long enough. Whitespace and all.
