### ISSUE TITLE
Project Management Wishlist 

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#58955]
### Is your feature request related to a problem? Please describe.

I'm adding this wishlist to follow up on further improvements that can be achieved in github/project management.  

The issue and PR auto labelers are performing hours worth of sorting each week and have vastly improved the workflow.  There may be other organizational improvements / bots that we can make use of from other projects or things we've come up with on our own.  
@casswedson has been instrumental in helping us move forward in this direction and I'd like to thank them here as well.   

### Solution you would like.

As people add suggestions or PRs related to this I will be happy to add them here.  Please feel free to make suggestions 

- [ ] auto astyle-json corrections as reviews #58916
- [ ] additional labeling improvements if possible for issues, potentially a keyword matching bot? 
- [ ] text style and clang-tidy checks auto output diff 

### Describe alternatives you have considered.

I wanted to organize thoughts around this topic.

**Comment by Qrox** [comment]
> auto astyle-json corrections as reviews

We could extend this to the text style and clang-tidy checks, but they should be made to output diff first, or we could write our custom comment code.

**Comment by Maleclypse** [comment]
@casswedson I think you've completed everything on this list now?

**Comment by casswedson** [comment]
I am the type that always finds something to tweak, specially in my implementations; tho I am satisfied with the completeness of the list as it is
