### ISSUE TITLE
Overmap has shifted it's display when the tileset is isometric

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#58951]
### Describe the bug

When playing with an isometric tileset, the overmap is also isometric. This isn't an issue by itself, but the overmap viewpoint has shifted and vision is limited. It doesn't matter if you have selected an isometric overmap tileset or a non-isometric overmap tileset.

The workaround is to turn overmap tileset off. Then it will display the overmap non-isometric but without graphics.

### Steps to reproduce

1. Load an isometric tileset, I used smasbutton iso
2. Look at the overmap

### Expected behavior

The overmap display should depend on the selected overmap tileset. I can set the overmap tileset to smashbutton iso but the result is shown in the screenshot below.

### Screenshots

![image](https://user-images.githubusercontent.com/50166150/177059899-74ead448-3bb8-41d2-9e37-25c29685e1e4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: e68b884 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by esotericist** [comment]
just confirmed on a recent build:

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: f85703b [64-bit]
