### ISSUE TITLE
'Fallout' Vaults no longer fit

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#58958]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/13670135/177089972-759082d6-0586-494c-a5f0-6d205fcfa929.png)
These Vaults are apparently very old and haven't been updated properly.  The only thing remaining in them are Irridated wanderers.  The other problems are as follows.

1. There are no updated loot tables, and zero enemy variety aside from the Irridiated wanderers and an occasional variation of them.
2. They are big, obvious and easily spotted since they always create a square town on the top with Irridiated wanderers.
3. They have no lore associated with them, where did they come from? Why are they here? Do they still fit?
4. There's no gameplay challenge, just dozens of Irridiated wanderers in hallways.  Irridiated wanderers are zombies, yet don't revivify.

### Solution you would like.

Remove them or prevent them from spawning.  They are an obvious Fallout reference and have little point in the game.

### Describe alternatives you have considered.

They could be retooled into proper 'dungeons' to be explored but it would require a significant amount of work.  Issue 1 could be solved by just fixing the loot tables, but balancing the rewards could be difficult.  
To fix 2 they could be placed underneath a typical city instead of spawning on their own or in a forest spawn.  It doesn't seem to make much sense to put that kind of bunker in the middle of a city that's going to presumably get nuked.
3 is something I don't know about.  I'm no loremaster of the game.
The last point is something that is up for debate.  Considering the irridiated wanderers radiation could be an issue, survivors only being able to explore the vaults with proper rad gear.  Though just making the monster have more variety might be enough.  But it would risk just being another underground Lab-esque area to explore for various loot.

**Comment by Venera3** [comment]
Three days too late -  #58842 obsoleted the location and the barebones lore scattered in the old guard questline.
