### ISSUE TITLE
Merchant Inventory Spawning Improperly

### ISSUE THREAD

**Issue by Uplinkedxd** [CleverRaven/Cataclysm-DDA#58957]
### Describe the bug

The trader in the Refugee Center trade inventory is spawning in the wrong location, making it so he doesn't have access to it, meaning he can't trade any of those items. I've seen this occur on a couple saves, but what causes it to occur is beyond me.

### Steps to reproduce

1. Create a new character.
2. Walk/Teleport near _then_ walk to the refugee center
3. Occasionally Smoke's inventory will be in a random spot outside of his trading room. (When this occurs, it's usually in the lobby or the stockpile room behind him.

### Expected behavior

Smoke's inventory spawns in the proper location, so you can trade with him normally.

### Screenshots

![Smokes Better](https://user-images.githubusercontent.com/32650533/177079519-37fe1a98-6354-4416-8f3f-528c7555b6ca.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 437c1db [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

https://www.dropbox.com/s/jdabpd4qtiotb08/Tekonsha.rar?dl=0 download save here

**Comment by andrei8l** [comment]
Really odd. The trade zones are in the right place and the shop restocks properly if you advance time by 6 days.

From which direction did you approach the center?

**Comment by Uplinkedxd** [comment]
Yeah, from the south to my knowledge. I've had this happen a handful of times, both walking in with zero teleporting whatsoever, and by teleporting into the middle of the center at game start.

**Comment by andrei8l** [comment]
/confirmed projected coordinates are off by a nonant
