### ISSUE TITLE
vehicle inventory does not notify of 4096 item limit

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#58966]
### Describe the bug

Moving items onto a cargo shelving with plenty of free space (961L out of 2000) nevertheless generates a message indicating "the cargo shelving is full, so it fell to the grass". The game doesn't even prompt you with the typical "there isn't enough room" warning you would otherwise get.

### Steps to reproduce

1. Move items onto cargo shelving
2. At some indeterminate point the items will fall onto the grass

### Expected behavior

You'd expect the inventory volume indicator to be accurate. If volume is not maxed out, there's no reason items should fall to the ground.

### Screenshots

![image](https://user-images.githubusercontent.com/19356629/177158138-69605090-e961-47b8-9635-6275865b0459.png)
![image](https://user-images.githubusercontent.com/19356629/177158187-955a504d-58bb-452f-b85a-e70e57beba13.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1806 (21H2)
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by anothersimulacrum** [comment]
Only 4096 items can be stored in a tile.

**Comment by bouchacha** [comment]
That's good to know, the game does not tell you at all. What counts as an "item"? I notice that some items have the quantity described inline (e.g. "flour (130)"), while others have the quantity in a separate column (e.g. "solar panel      4"). I never understood why there were two ways of counting but I guess that's a separate question.

**Comment by anothersimulacrum** [comment]
The first type of items are called `count by charges` items, and they represent multiple items with a single item and it's "charges", whereas other items represent multiple items with multiple literal items. We want to gradually remove `count by charges` items for technical reasons.

**Comment by PatrikLundell** [comment]
Isn't cargo shelving a game mod vehicle part? If so, this post should probably be tagged with the appropriate mod?

**Comment by Zireael07** [comment]
Not sure, but either way the crux of the issue is in core game code.

**Comment by bouchacha** [comment]
I just tested this without any mods at all. I spawned 10,000 ear plugs (0.1 L volume) and there's no issue if you're just moving items between ground tiles. The max number of items is indeed 4096, but if you try to move more onto that tile using AIM it will stop you and give this message:

![image](https://user-images.githubusercontent.com/19356629/177310958-573b40c4-429e-497a-b867-0bcde585dfff.png)

The problem is that it doesn't give you this message when you're moving items onto vehicles, it just drops them to the ground without any explanation:

![image](https://user-images.githubusercontent.com/19356629/177310718-ba3c48ec-4039-4685-b108-757490179eda.png)

I've been playing this game for years and had no idea there was any item limit whatsoever. 4096 cotton patches is not completely unfathomable and is only 25L of volume, and vehicle inventory management is a core feature of the game, so this issue is bound to come up many times and cause countless confusion due to the lack of any message.
![image](https://user-images.githubusercontent.com/19356629/177312150-aad96bef-131c-4139-a52b-507f4fa1d5cf.png)


1. There should _at least_ be a message. "X is full" without a reference to the hardcoded item limit is extremely ambiguous and confusing.
2. Why does the 4096 limit even exist? If we're moving away from `count by charges` items, we'd only be accelerating how often this limit becomes an issue.

**Comment by Qrox** [comment]
According to this comment https://github.com/CleverRaven/Cataclysm-DDA/issues/20483#issuecomment-284949006 the 4096 limit was to work around the performance issue of iterating through a `std::list` to find map items. However we already switched to using `cata::colony` to store map items and `cata:colony` should have a average random-access complexity of [approximately O(logN)](https://plflib.org/colony.htm), so it may be possible to remove or relax this limit. (Although it seems `item_location` still unpacks by iterating through the item stack which results in O(N) random access complexity, so that need to be updated first).

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/35411#issuecomment-580445996

**Comment by Qrox** [comment]
Well, we can at least tune the limit up if removing it is not an option. I'm not sure what overflow problem the comments in that issue are referring to. Considering that volume is always limited in a tile and should not overflow in any case, maybe they are refering to the weight? Although in that case you can still cause an overflow by having a stack of very many items counted by charge, nested containers, or a misbehaving mod that adds mini-blackholes to the game, so we probably want to add weight limit to a tile to prevent weight overflow.

> gradually remove count by charges items for technical reasons.

In addition to causing the item limit to be hit more often as @bouchacha pointed out, this might also cause higher memory consumption if the items are not stored with an RLE-like data structure (especially with items such as thread which the player usually has thousands after some reasonable time). But that is more or less equivalent to keeping the items counted by charge but displaying them the same as a stack of items in UIs.
