### ISSUE TITLE
Body temperature calculations are weird and probably a bit broken

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#58961]
### Is your feature request related to a problem? Please describe.

Body temperature calculations uses three different temperature units:
* C (usually 0.01 C).
* F (usually 0.01 F).
* u (weird custom temperature unit. May be fahrenheit/50 or arbitrary values).

The math for body temperature mixes these three units seemingly without unit conversions.

For example on this line: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character_body.cpp#L500

`set_part_temp_conv( bp, BODYTEMP_NORM + adjusted_temp + windchill * 100 + clothing_warmth_adjustment + bp_temp_min );`

where:
* `BODYTEMP_NORM` is 5000 (u)
* `adjusted_temp` is 100 * ( environment temperature (C) - 31 (C) )
* windchill is in fahrenheit.
* clothing_warmth_adjustment is in u.
* bp_temp_min is always zero (only used by "debug tail" mutation).

Summing temperatures of different units together like this is nonsense. It can't be right.

Also variables are all done with integers for some reason. Extra effort is made to keep everything in integers. For example divisions will do cast to float and then cast back to integers. Occasionally doubles are used because we really need full 64 bit precision for this number that will be rounded to integer.

For example this beuty is in the code:
```
double total_windpower = get_local_windpower(...
int bp_windpower = total_windpower;
bp_windpower = static_cast<int>( static_cast<float>( bp_windpower ) * ... );
```
The for loop also has math in it that does not depend on looped variable (ie. same for all body parts). They could be just moved out of the for loop.

### Solution you would like.

All the temperature should be in same units (preferably units::temperature).
Refactoring is very hard since it is not clear what units are wrong and how wrong they are.
Refactor to more consistently use float when appropriate.
Refactor some more.

### Describe alternatives you have considered.

Nuke it and rewrite from scratch.

**Comment by Venera3** [comment]
For context, the `bp_min` bit is in preparation for Limb Stuff with different limbs having different levels of base warmth and warmth compensation, but that Project won't happen this cycle.

**Comment by bombasticSlacks** [comment]
u is defined in weather.h 

```c++
/**
 * @name BODYTEMP
 * Body temperature.
 * Body temperature is measured on a scale of 0u to 10000u, where 10u = 0.02C and 5000u is 37C
 * Outdoor temperature uses similar numbers, but on a different scale: 2200u = 22C, where 10u = 0.1C.
 * Most values can be changed with no impact on calculations.
 * Maximum heat cannot pass 15000u, otherwise the player will vomit to death.
 */
///@{
//!< More aggressive cold effects.
static constexpr int BODYTEMP_FREEZING = 500;
//!< This value means frostbite occurs at the warmest temperature of 1C. If changed, the temp_conv calculation should be reexamined.
static constexpr int BODYTEMP_VERY_COLD = 2000;
//!< Frostbite timer will not improve while below this point.
static constexpr int BODYTEMP_COLD = 3500;
//!< Do not change this value, it is an arbitrary anchor on which other calculations are made.
static constexpr int BODYTEMP_NORM = 5000;
//!< Level 1 hotness.
static constexpr int BODYTEMP_HOT = 6500;
//!< Level 2 hotness.
static constexpr int BODYTEMP_VERY_HOT = 8000;
//!< Level 3 hotness.
static constexpr int BODYTEMP_SCORCHING = 9500;

//!< Additional Threshold before speed is impacted by heat.
static constexpr int BODYTEMP_THRESHOLD = 500;
```
for whoever ends up working on this

**Comment by peter4370** [comment]
In my understanding is you want to change those to body temperature unit it should be like this
`int temp = BODYTEMP_NORM + adjusted_temp * 5 + clothing_warmth_adjustment + bp_temp_min + units::to_kelvin( windchill ) * 5 * 100;`
Because 0.01c is 5u body temerature so times 5
But other part of the code might not works correctly with it
