### ISSUE TITLE
sidebar UI, basic stats colors

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#58988]
### Describe the bug

Basic stats widget calculate wrong colors for the basic stats.

### Steps to reproduce

use any modern sidebar,
create naked person, wait for a while.
low temperature will decrease stats at night and then they slightly grow back
at this point low values will became green. as they are over basic stat.

### Expected behavior

Any stat lower than basic should go to the first colors in list and vice versa.

### Screenshots
compare: left panel and top right numbers
![image](https://user-images.githubusercontent.com/6676374/177294388-843aa516-0f27-4506-a40a-ea61189ba0de.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: cccb059 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed

![image](https://user-images.githubusercontent.com/52621858/177699709-d7ea8361-fa74-4fed-8782-39e56befce71.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
