### ISSUE TITLE
Are gasoline zombies intended to be unable to climb out through windows?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#58993]
### Describe the bug

I've had a couple of cases where gasoline zombies happily smash out windows in the house they're in, but then seem unable to actually climb out through the empty window frames. That's rather annoying, since you typically don't want to set off fires that will rage for months and burn down an unknown portion of the neighborhood by killing them while still inside.

### Steps to reproduce

1. Find a gasoline zombie inside a house
2. Make your presence known and make faces at it.
3. See it smash the windows and clear the window frames.
4. Wait until you get bored.

### Expected behavior

These buggers ought to be able to get through places where other zombies are able to get through. Even the crawling zombies are able to get through smashed out and cleared windows.

### Screenshots

![Screenshot (247)](https://user-images.githubusercontent.com/22739822/177377790-9bfb1432-9f6e-4867-932b-1073c8bcad17.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: be2fdc3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms
+ Workshop recipes for welding consumables.

**Comment by PatrikLundell** [comment]
"Large" PCs would have to be mutated. as my maximum sized characters haven't had any problems, and I believe I've cleared window frames and passed through while morbidly obese.

The problem isn't really that huge (and not extremely strong) zombies can't get through, but that this particularly nasty one can't. Not having any way to "disarm" is quite annoying.

Regular zombies smashing up vehicles is double edged. On the one hand you might have wanted to claim those vehicles, but on the other hand being able to wait for them to smash their way through rather than having to open the doors for them and end up in melee tends to be useful. I've seen some zombie children being too weak to smash their way out of vehicles, though.

**Comment by fairyarmadillo** [comment]
The fact that they get stuck in windows is intended and winds up being pretty useful for corralling them, which is presently the only way to deal with them other than leaving or kiting them somewhere that you don't mind burning.

**Comment by PatrikLundell** [comment]
Leaving gasoline zombies in nearby buildings means there's a constant danger that they might get out and kill you when performing some uninterruptible activity (like bandaging wounds) due to passing foxes and whatnot.
Trying to lure them out through the door seems extremely dangerous, as I assume they explode and kill you in a ball of fire (haven't dared approach to melee range to find out if they only explode when taking fatal damage).

**Comment by fairyarmadillo** [comment]
They only explode when killed, and they're so incredibly slow that they'll never catch you anyway.

You can also bash out the window frame if you have a decent weapon. Also iirc they were recently changed so that they only really spawn near gas stations, they should be much rarer than they were unless they're still popping up elsewhere due to evolution.

**Comment by PatrikLundell** [comment]
It's a consolation that it should be possible to clear a way for them without getting killed by a fireball.

**Comment by fairyarmadillo** [comment]
I agree that they shouldn't always explode. Really they shouldn't explode at all unless they take fire damage.

Also it's weird how lethal fire is in this game. Taking even one fire damage can set you on fire, and that hurts so bad so fast that it's almost impossible to extinguish in time even if you're not getting chewed on by zombies.
