### ISSUE TITLE
Expandable Batons are really cumbersome to use

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#58996]
### Is your feature request related to a problem? Please describe.

Wielding a baton isn't sufficient, since you have to then (a)ctivate it before it becomes a viable weapon. If you want to put it away, you have to (a)ctivate it again to retract it, then (w)ield it to put it away. This, on its own, would not necessarily be that big of a problem. The added issue is that because the item "transforms" between expansion/retraction, it loses its inventory letter, including any that you would have specified to use as a shortcut key.

### Solution you would like.

1. If someone is (w)ielding a baton, it's perfectly reasonable to assume they're about to use it as a weapon, so they should automatically (a)ctivate upon wielding. Why else are you wielding it?
2. Is it possible for the game to keep track of assigned inventory letters across item transformations?

### Describe alternatives you have considered.

Not use one of the best melee weapons in the game

**Comment by bouchacha** [comment]
> Adding the NEEDS_UNFOLD/SLOW_WIELD flags in place of activation might help with this.

That's quite an elegant solution! It would be an improvement over the current status quo for sure. I've used batons in real life and they're built to expand _very_ easily with just a flick of the wrist. If you practice well enough, you could theoretically expand a baton mid-swing. This seems to track well with the SLOW_WIELD flag feature that lets you reduce this delay with higher skill. Perfect.

The only issue is that the player technically should be able to choose to keep a baton expanded (despite it taking up larger volume) in order to avoid the expand/retract wielding delay. This is similar to the current system in place for folding stocks on firearms. Not sure how that can be applied to melee weapons.

**Comment by Marrim** [comment]
I found it useful to have "[a]ctivate" and "[A]ctivate wielded item" keybindings for this.

**Comment by Zireael07** [comment]
Someone recently hadn't realized they could extend the baton, starting as a sec guard
