### ISSUE TITLE
Marshal Rep gives you a holster and a revolver that can't fit inside it

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#58994]
### Describe the bug

At one point in the representative questline, you are given a marshal badge, a holster, and a Ruger Redhawk. The Ruger Redhawk has an item length of 31cm, but the holster's max item length is 30cm.

It doesn't make sense for you to be gifted a holster and a gun that can't fit inside that holster. But also, the holster's max item length seems too restrictive. The longest part of the Redhawk revolver is the barrel, and it would be trivial to just cut off the end of the holster and let the barrel poke through. In fact, holsters intended to be "universal" [tend to leave the barrel end open](https://diamonddoutdoors.com/products/denali-chest-holster) to accommodate different firearm sizes:
![image](https://user-images.githubusercontent.com/19356629/177382245-c378755b-1e98-45eb-92c9-bb57a2a28dc6.png)

And this is especially common for Redhawks because they're made in different sizes:
![image](https://user-images.githubusercontent.com/19356629/177382398-fd86093b-6bb0-4eeb-a580-7b84ecd2f0b2.png)
![image](https://user-images.githubusercontent.com/19356629/177382521-91beb2a0-acbe-4040-bc73-47730cb0831d.png)
![image](https://user-images.githubusercontent.com/19356629/177382715-c07565cd-1145-4b07-85b1-4aa6c7e85a58.png)

### Steps to reproduce

See above

### Expected behavior

If you're gifted a gun and a holster as a reward, they should be able to be used together.

There are two solutions here:
1. The rep should gift you a 'western holster' instead of a regular holster, since that will fit the Ruger and also be thematically consistent with the Marshal aesthetic.
2. The 'holster' max item length should be increased, but this might cause game balance issues given that the western holster is more difficult to wear comfortably because it overlaps between 'torso (lower torso)' and 'legs (hips)' instead of just 'legs (hips)'. 'western holster' also already has the added bonus of holding bullets in another pocket, maybe it can also get the FANCY tag?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1806 (21H2)
- Game Version: db8eb88 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
/confirmed

![image](https://user-images.githubusercontent.com/52621858/177697998-92952564-c58f-42a3-9179-ce7cf5a27ca9.png)
![image](https://user-images.githubusercontent.com/52621858/177698055-079bf34b-7ded-4e5a-975d-593d0845953d.png)


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
The OP is talking about this mission:

https://github.com/CleverRaven/Cataclysm-DDA/blob/679fd9f3569f751cc4af0ee54576b82011ea13b9/data/json/npcs/refugee_center/surface_visitors/NPC_old_guard_representative.json#L300-L337
