### ISSUE TITLE
Split hand- and footwear into two separate entities for your left and right limb

### ISSUE THREAD

**Issue by L-3-on** [CleverRaven/Cataclysm-DDA#59003]
### Is your feature request related to a problem? Please describe.

A lot of things in this game evolve in unique ways for the sake of realism, while such a simple thing like loosing only your left glove because a zombie attacked your left arm and hand isn't possible.

### Solution you would like.

Including flags like "left_limb" and "right_limb", splitting hand- and footwear into to entities, give one the flag "left_limb", the other "right_limb" and give the player an encumberance malus when using e.g. a soft glove for the left hand on the right one or make it rightout impossible if it is a hard one like a gauntlet.

**Comment by Drew4484** [comment]
We currently have "sided" as an option, see https://nornagon.github.io/cdda-guide/#/item/armor_lc_armguard.
A sided object can be worn on the left or right and swapped in the clothing menu (default '+'). 

What could be helpful is to audit items that should be sided, reduce the weight/volume in half, and then adjust spawns so they're more likely to spawn in pairs.

**Comment by liminalRoar** [comment]
Would be neat but i am sure there are relatively few reasons you would ever want different shoes or gloves on. Though, would maybe be a stepping stone towards my most wanted feature - the ability to hold items in each hand! I would love nothing more than that. Carrying a flashlight in one and a combat knife in the other, or needing both hands free for two handed items. So many situations, really.

**Comment by Drew4484** [comment]
> Would be neat but i am sure there are relatively few reasons you would ever want different shoes or gloves on. Though, would maybe be a stepping stone towards my most wanted feature - the ability to hold items in each hand! I would love nothing more than that. Carrying a flashlight in one and a combat knife in the other, or needing both hands free for two handed items. So many situations, really.

Multiwield is a whole different problem that we'd like to fix soon, but the only downside to splitting gloves/socks/shoes/etc. is the extra inventory management. From a simulation point of view it's more accurate to have one boot damaged by an attack and need repair or replacement than to have both destroyed at once.

**Comment by L-3-on** [comment]
A technically simple "interim solution" would be to...
1) ...duplicate all entries for items that come in pairs atm. and are worn on arms, legs, hands or feet,...
2) ...halve their weight, value and volume,...
3) ...change the ID / rename one of those duplicants to "ItemName_left" and the other one to "ItemName_right" and...
4) ...remove body coverage for all bodyparts on the right side from "ItemName_left" and vice versa.
5) Finally define "item_groups" that only contain "ItemName_left" and "ItemName_right" and...
6) ...replace all previous spawns of the old pairs with that "item_group".

**Comment by L-3-on** [comment]
This interim solution would make it impossible to wear a left shoe on the right foot and therefor there won't be any encumberance penalties.

**Comment by kevingranade** [comment]
Closing discussion that played out a year ago.
