### ISSUE TITLE
Allow other NPCs to give directions to the player if the regular direction-giver dies

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#59019]
### Is your feature request related to a problem? Please describe.

After accepting smokes' first mission in a double spawn world, I instantly got the success message. Looking at the backbay revealed that 4 NPCs including the teamster died to kill all the zombies

The teamster death meant that it suddently became way harder to find the Hub 01, the Exodii and the two artisans as getting directions was now impossible unless I found a new refugee center

### Solution you would like.

That  another nearby NPC could at least tell the directions to the player if the main direction giver is dead

### Additional context

It probalby wouldn't happen at regular spawns but the fact that some locations can become way harder to find is something that needds to be adressed

**Comment by PatrikLundell** [comment]
I agree that it's desirable to have other NPCs take the place of dead ones in "large" factions, in particular going forward toward truly unique factions.
