### ISSUE TITLE
avatar attempts to butcher when stepping on an item

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#59014]
### Describe the bug

My character automatically attempts to butcher, but quickly canceled because there's no corpses. It also happened on a newly created world.

### Steps to reproduce

1. Find an item on the ground or drop one
2. Walk into it
3. Butcher automatically happened

### Expected behavior

Walking on it as usual

### Screenshots

![Screenshot_20220706-221504](https://user-images.githubusercontent.com/78019001/177585248-e620a315-cf77-4848-9854-4a81b63ec3d2.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 709099b [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
Check your keybinds for "Toggle auto pulp or butcher".

**Comment by gettingusedto** [comment]
I didn't noticed that I accidentally press the button. Thank you and sorry for inconveniencing you
