### ISSUE TITLE
Stock accessories can be attached to guns with stock sawn off

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#59026]
### Describe the bug

I was about to write a PR to convert wooden stocked guns to mounts, as many of them shouldn't be easily convertible w/o modification + so people can use the new sawn-off stock mod on them, and realized stock accessories are not blocked by sawing the stock off.

### Steps to reproduce

1. Spawn a shotgun with both stock accessories and stock mount/a wooden stock.
2. Saw off the stock with a bow saw or wood saw.
3. Attach butt hook to air.

*Steps 2 & 3 cannot be swapped in order as there is a check on the saw down stock action.

### Expected behavior

Not being able to add stock accessories to the air, or gunmods deleting gunmod slots like they can add them & this being applied to the sawn-off stock mod deleting the two stock accessory slots.

### Screenshots

![image](https://user-images.githubusercontent.com/99621099/177665944-0976701b-7ee1-4805-8308-3ec7283951e8.png)

### Versions and configuration

*Applies to all versions after #58936 was merged

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: 1348046 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This also applies to the cheek pad for rifles/the only other stock accessory.

**Comment by hexagonrecursion** [comment]
/confirmed

![image](https://user-images.githubusercontent.com/52621858/177696878-b54e3dc4-3e2b-4035-9ff1-91e082af105b.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
