### ISSUE TITLE
Add some way to be able to get a prompt if the player would attack a non-hostile creature from a non-hostile faction

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#59021]
### Is your feature request related to a problem? Please describe.

While I was walking around in the Exodii castle, I noticed that it was quite tedious and stressful to avoid walking into (and thus attaacking) the workers and quadrupeds

A single misshap could result in being blasted by a quadruped

### Solution you would like.

A way to get prompted if the player would accidentally attack a non-hostile to prevent being hurt by a now-hostile creature

### Describe alternatives you have considered.

Allowing to swap place with neutral creatures by walking in them and attacking by examining

**Comment by Zireael07** [comment]
I think it was already proposed (in a comment somewhere????), but definitely worthwhile having a separate issue.
