### ISSUE TITLE
Game crash on world load at items

### ISSUE THREAD

**Issue by cresttoothpaste** [CleverRaven/Cataclysm-DDA#59041]
### Describe the bug

As of 7/7/22 10:56 am EST, the game will fail to load into the world every time it gets to the items portion.  I've even tried removing every single mod, leaving only the base game.

### Steps to reproduce

1. start game
2. create new world with no mods
3. try to load into the map
4. load order gets to items
5. crash to title screen without error log prompt

### Expected behavior

I expect to get into the game proper at the very least with the base game.

### Versions and configuration

game version 2022-07-07-0606

**Comment by BrettDong** [comment]
I have no problem getting into the game. 3d81d31

**Comment by cresttoothpaste** [comment]
I'm not sure what fixed it, but the latest update seemed to have corrected whatever the issue was.
