### ISSUE TITLE
NPC activity - cannot mine terrain if its dark, but no meaningful error

### ISSUE THREAD

**Issue by Ivan-Shestakov** [CleverRaven/Cataclysm-DDA#59051]
### Describe the bug

Can't make NPCs mine terrain for the player. The NPC says to have completed assigned task, no error is given, but they don't move at all.
Edit: the reason for failure is too dark, dropping a lit candle near the mining area - allowed NPC to start mining.

### Steps to reproduce

1. Start new game in shelter
2. Spawn in NPC, make them friendly (for example by spawning their required item - inhaler in my case).
3. Go  down to shelter basement
5. Go to Zones manager and create new "Mine Terrain" zone on top of concrete walls, and Unsorted loot zone nearby.
6. Spawn item "pickaxe" and drop it in unsorted loot tile.
7. Talk to NPC, ask them (d) "something to do", then talk (j) "current activity", and  (e) "do any mining work that you can".

### Expected behavior

The NPC should collect required tools (pickaxe) and start mining the concrete walls according to designation.
If tools/qualities are missing the game should let the player know.

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin M-C02FD2YGMD6R 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
- Game Version: 0.F-9746-g3d81d31cdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
I believe there are candles, oil lamps, and torches in Innawoods, and probably other lighting options as well.

Companions just "complete" sorting when out of space or someone blocks their path to the tile they've decided they want to use, and, similarly, companions "complete" vehicle dismantling when their skills are insufficient.
