### ISSUE TITLE
Dissecting a Skeletal Dog doesn't improve proficiency for Natural Exoskeletons

### ISSUE THREAD

**Issue by SolventMercury** [CleverRaven/Cataclysm-DDA#59053]
### Describe the bug

Skeletal Dogs, despite having a natural bone exoskeleton, do not provide any experience towards the Natural Exoskeletons proficiency.

### Steps to reproduce

Perform a dissection on a Skeletal Dog with the appropriate prerequisites already completed.

### Expected behavior

Increase to progress towards proficiency in Natural Exoskeleton

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 873f768 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key]
]

**Comment by chrispikula** [comment]
Would they be considered 'natural'?  

Do we have blob-specific dissection proficiencies?

**Comment by Cimanyd0** [comment]
#56487 added weakpoint proficiencies "to monsters with existing weakpoints only". Zombie dogs don't have weakpoints yet, so they didn't get any proficiencies.

I also think it would be better to get proficiencies from monsters that make sense, even if they don't have the weakpoints added yet. `prof_wp_skeleton` (Natural Exoskeletons) on any skeletal zombies including animals, `prof_wp_zombie` (Principles of Zombie Biology) on all zombies including animals, `prof_intro_biology` (Principles of Biology) even on non-zombie animals, and so on.

That would turn the line "You carefully record the creature's vulnerabilities." into a lie if the creature has no vulnerabilities yet.

> Would they be considered 'natural'?
> 
> Do we have blob-specific dissection proficiencies?

`prof_wp_skeleton` might need a name change from Natural Exoskeletons. Currently it's only on skeletal human zombies, and different kinds of insects were given their own proficiencies in #58751.
