### ISSUE TITLE
How to build Cataclysm-DDA on windows arm64 using MSVC

### ISSUE THREAD

**Issue by spacelg** [CleverRaven/Cataclysm-DDA#59059]
### Is your feature request related to a problem? Please describe.

Hi all,

We try MSVC to build Cataclysm-vcpkg-static.sln on x64, it works.  But when we tried to build for target arm64, I found that Cataclysm-vcpkg-static.sln did not have arm64 configuration. 

### Solution you would like.

Is it possible to provide a sln with arm64 configuration? Or another way to build on windows arm64? 

Could someone please help look at this issue? Thanks in advance.

Thanks,
Lin

**Comment by BrettDong** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/62594#issuecomment-1341177596
