### ISSUE TITLE
Boats 'Submerged' on Flowing Deep Water Tiles

### ISSUE THREAD

**Issue by indigorain** [CleverRaven/Cataclysm-DDA#59060]
### Describe the bug

When a boat-vehicle tile is over flowing water, the player does not have the option to step onto the tile, but instead is asked whether he or she would like to dive. The player is sent under water with the vehicle tiles fully accessible. Should a player 'dive' into the seat and start driving, the player will start drowning. This bug occurs regardless of the integrity or weight of the vehicle.

### Steps to reproduce

1. Make fresh, undamaged vehicle.
2. Drag some tiles of it into deep water
3. Try to step onto tiles that are over deep water
4. Be given prompt to dive
5. Sink like a rock, with the vehicle tile fully accessible

Bug does not occur when walking from deep water to deep water. Seems to only occur when walking from shallow to deep.

### Expected behavior

Player should be able to walk freely from shallow to deep water tiles provided they are in a sea-worthy vehicle. The option to dive should not be given, nor should vehicle tiles be available once submerged, suggested that the vehicle is both in and out of water.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-9746.

I'm standing on a canoe, on a tile over flowing shallow water.
![изображение](https://user-images.githubusercontent.com/11132525/177954749-9ac98804-cbe9-42cc-b52c-18eca266e24f.png)

The tile north of me is a flowing deep water.
![изображение](https://user-images.githubusercontent.com/11132525/177954838-45e7fe43-bee8-427f-a641-b9f3074fa69a.png)

I made a step from shallow water to deep water, and got no prompt to dive.

Could you provide a savefile with this bug?

**Comment by indigorain** [comment]
Yes, here it is.

It's possible that this is an old bug that has gotten fixed. I know 0.F-3 has the problem where you cannot reload magazines that are slotted inside weapons and that got fixed.

[boat-bug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9070635/boat-bug.zip)

**Comment by Night-Pryanik** [comment]
I tested your save, and the bug still didn't occur. I suppose that's 0.F-3 stable bug that was fixed in latest experimentals. I'm closing this right now. If someone encounter this bug in latest experimentals, ping me, and I'll reopen this issue.
