### ISSUE TITLE
Mutant Molluscs can be butchered for regular fat

### ISSUE THREAD

**Issue by Saeveo** [CleverRaven/Cataclysm-DDA#59069]
### Describe the bug

Creatures with the mutant_mollusk harvest type produce mutant meat (as one would expect), but regular, toxin-free fat.

### Steps to reproduce

1. Butcher a creature with the mutant_mollusk harvest type, e.g. Giant Snail, Colossal Slug, 
2. Observe that the meat produced contains toxin, but the fat is toxin-free.

### Expected behavior

I would expect meat and fat from mutant_mollusk creatures to consistently have toxins.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 57db2bc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]


![image](https://user-images.githubusercontent.com/52621858/178042277-39c3b4da-c85d-4857-893e-870aa396dbe1.png)
