### ISSUE TITLE
 new bionic profession "Bionic Mechanic"

### ISSUE THREAD

**Issue by yam1917** [CleverRaven/Cataclysm-DDA#59064]
### Is your feature request related to a problem? Please describe.

well, lets just say that there isnt a character like this

### Solution you would like.

add my character into the game (i wanted to create a pull request, but couldnt quite figure it out, i rarely ever use github you know... i will put profession code in the "additional context" section), character could use some rebalancing though.

oh, also, there is an error, claiming that "bio_blindfold" is already installed during spawning, i didnt figure out how to get rid of it, but it doesnt have an effect on the game

i also edited code a bit, to look prettier and didnt check if it still works after, hopefully i didnt mess something up

### Additional context

{
	  "type": "profession",
	  "id": "biomechanic",
	  "name": "Bionic Mechanic",
	  "description": "With a set of bionic implants, you are ready for every vehicle repair",
	  "points": 4,
	  "CBMs":["bio_cable","bio_tools", "bio_tools_extend","bio_hydraulics","bio_power_storage_mkII","bio_power_storage_mkII","bio_stiff", "bio_blindfold", "bio_sunglasses","bio_ankles","bio_thumbs", "bio_deformity", "bio_earplugs", "bio_glowy",  "bio_itchy", "bio_nostril", "bio_voice", "bio_pokedeye" ],
	  "skills":[{"level":2, "name": "mechanics"}],
	  "items":{
		  "both":{
			  "items":["slingpack", "tank_top", "jeans", "socks", "boots_steel", "duct_tape", "wristwatch", "jumper_cable"]
		  },
			  "male": [ "boxer_shorts" ],
      "female": [ "bra", "boy_shorts" ] 
	  }
}

**Comment by NetSysFire** [comment]
Although bionic professions are super cool I am unsure how they are going to be handled with the new lore that you can only get bionics from a specific faction which only spawned through the Cataclysm.

**Comment by yam1917** [comment]
maybe we can have exodii themed scenario, just like we have "experiment" scenario where you can pick mutations

**Comment by yam1917** [comment]
btw, about balance, i think itchy bionic should be removed

**Comment by kevingranade** [comment]
Stale speedup.
