### ISSUE TITLE
Free leather patches by crafting tanned hide

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#59068]
### Describe the bug

I noticed that you can craft tanned hide from 6 leather patches and some thread, but the crafted tanned hide can be disassembled into 8 patches.

### Steps to reproduce

1. Get some leather patches and some thread
2. Craft tanned hide
3. Disassemble the tanned hide
4. Profit

### Expected behavior

It should require 8 leather patches to craft. Alternatively, since we already have patchwork leather sheet, maybe we should audit any crafting recipe that requires tanned hide to also accept patchwork leather sheet, and obsolete the tanned hide from leather patch recipe.

### Versions and configuration

350a2ead748027fac358bd8649af95c9ee33572b

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
