### ISSUE TITLE
Water does not put out fire

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#59066]
### Describe the bug

As fire burners began to explode, I tryed to figure out how to save their valuable loot and dont die in process
And I make some experiments with fire and water
I will also attach a video with my little experiment
If you pour water on fire - it will be extinguished
If you start fire in water no matter shallow or deep - it will burn and cannot be extinguished, pouring water on it cause nothing

### Steps to reproduce

1) Teleport to the river or any place with deep and shallow water
2) Spawn with debug menu next list of items: 
Lighter
Some splintered wood or somehing good burning, I spawned 500 splintered wood and split them in 5 piles wich 100 splintered wood in each
Bottle for water
3) Put 1 pile of wood into shallow water, 1 pile in deep water, and 3 piles on ground
4) Pour water on 1 pile on ground
5) Start fire on all of 5 piles
6) Watch how pile of wood on the ground with poured water on it will be extinguished fast, and piles in shallow and deep water will burn for long. You can also pour water on two others piles of wood after the flame is lit to see, how fast water will extinguish it, or dont touch it to see, how they will burn for the same amount of time with piles in shallow and deep water. You can also try to extinguish piles in shallow and deep water with pouring water on them, but it will cause nothing

### Expected behavior

I expected not to see burning wood and other items (like loot from fire burners) in water

### Screenshots

Sorry for video quality, there is 10 mb limit and I dont know, how to upload big and high quality videos

https://user-images.githubusercontent.com/102726167/178003513-4f1f5c98-41b8-4c9d-8582-174a284cb172.mov

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 350a2ea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed a puddle is **enough** to put out a fire, but a river is **not** enough

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6502158 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by kurtisvetter** [comment]
Also can confirm, as I found out while trying to fight a burner zombie in a pool of water. However someone else pointed out the napalm (which is mostly just gasoline) floats on water and could still burn on the surface. So maybe in that specific case it does make sense for water not to put out fire. 
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 0.F-11471-ga3c6a291d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved]
]
