### ISSUE TITLE
Add a Translation Notes box in the main menu

### ISSUE THREAD

**Issue by Sniper27IT** [CleverRaven/Cataclysm-DDA#59070]
### Is your feature request related to a problem? Please describe.

As main Italian translator, i'd like to have a box, or any other sort of information menu accessible in the main menu of the game (like some sort of patch notes) where translators can report the state of the translation, such as: problems, notes, contact info to report errors and/or join the team and other translation-related infos. I really care for this as the state of italian translation is very much a mess at the moment and i wish to warn new players about this, even tho C:DDA, being a niche game, will probably be played by italians who can understand english quite well. Still, for completion's sake, i push myself to give access to the game for those who don't understand english.
This would also benefit any other translation project with similar issues.

### Solution you would like.

Adding an infobox or any other similar structure to the main menu. Or a selection in the option menu which brings this up as a pop-up window.
Either way, the translation box should be edited in a file placed into the game's Transifex directory called "Translation Notes". This way, languages which don't need this can just leave it empty.

### Describe alternatives you have considered.

Anything else that would allow a similar result. I feel bad for not having a way to explain new players why they have messed-up translations.

### Additional context

None

**Comment by BrettDong** [comment]
You may put the information in MOTD

**Comment by Sniper27IT** [comment]
> You may put the information in MOTD

I don't think it would be enough space tho. Also MOTDs are random if i recall correctly so it is not guaranteed to be shown. Something that can be brought up like a prompt on-demand would be far better

**Comment by BrettDong** [comment]
The content of MOTD is not random and it can be multi-page long: https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/motd

**Comment by Sniper27IT** [comment]
Sorry, i mistook MOTD with the bottom screen tips. That's one way to deal with this. The only thing is that it must be edited and then uploaded back to git, am i right? That's why i suggested a separated file for Transifex directory

**Comment by BrettDong** [comment]
MOTD is translated on Transifex: https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/motd-master/

**Comment by Sniper27IT** [comment]
Yeah, but for some reason i still have an older MOTD which doesn't match the current translation, are they pulled along the other Transifex files in the weekly update? Because even tho i update the game daily, my MOTD still shows something about version 0.C

**Comment by BrettDong** [comment]
Yes, currently MOTD is not automatically synchronised between Transifex and GitHub.
