### ISSUE TITLE
lamp oil (based on rendered fat) for oil lamps

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#59076]
### Is your feature request related to a problem? Please describe.

the requirement to synthesize kerosene is ridiculous (extraction 3 tool, which is apparently only available in labs) and camphene cannot be made from rendered fat.

### Solution you would like.

reintroducing lamp oil for oil lamps. The only reason why this was taken out was the side-usage as diesel replacement. There was no reason to remove it for the main usage in oil and tallow lamps. 

### Additional context

Historically tallow and oil lamps with fuel from rendered creature fats were wide-spread. Example here: https://www.bbc.co.uk/ahistoryoftheworld/objects/j5Ciq9YBT56GBH1TtPagxA

One does not need the high-tech to crack or refine oils to fuel a simple lamp. And my lamps dont have to be vegan either

**Comment by TheLyca0n** [comment]
Think that the lamp oil cooker/surv mess kit should be reintroduced ?. Or was that that be OP

https://m.youtube.com/watch?v=hKVMf0IxdZA

Exists IRL just seems really slow to cook with, design could probably be improved just with just some more wicks and or candles to improve speed at cost of efficiency

Though in a world filled with mutant/zombie fat don't think a little excess tallow burned should be a concern.
