### ISSUE TITLE
scenario description got cut in half

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#59080]
### Describe the bug

the description on the scenario tab got cut in half. Oddly enough the descriptions in other tabs worked fine

### Steps to reproduce

1. Make a world
2. Enter character creation 
3. Go to the scenario tab
4. Look at the glitched up description 

### Expected behavior

The scenario description wasn't cut in half.

### Screenshots

Disregard the fact that it's in portrait orientation, it's still get cut in half regardless. 
![Screenshot_20220709-031749](https://user-images.githubusercontent.com/78019001/178067135-b7f61208-7f20-40c6-a7f9-175a82ff05cc.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 350a2ea [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sanguinea  [sanguinea]
]

**Comment by ZeroInternalReflection** [comment]
The details section printing over the narrative description isn't entirely new (Screenshot from #58226):

![Existing cut off scenario description](https://user-images.githubusercontent.com/89038572/166401417-2aa18b77-dbf5-49cc-bf8a-6572e1964777.png)

It looks like there's a check to ensure the details section doesn't get too tall:
https://github.com/CleverRaven/Cataclysm-DDA/blob/414c57e47c7ecc85799dceeb4a2aae5763ae9c6f/src/newcharacter.cpp#L3021-L3024

But:
1. This check fails if the other windows are already too tall (e.g. on a 24-high terminal), and
2. This check doesn't factor in w_requirement_h (added in #58804)
