### ISSUE TITLE
Portal Dungeon Kills Player Without Warning

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#59087]
### Describe the bug

In debug testing the new portal storm dungeons I have repeatedly been instant-killed for no obvious reason.  

The first instance is that it will spit you out randomly into the sky and you cannot do anything, if you move at all you instantly fall to your death.  I was not able to get footage of this but I have a screenshot.

The second instance is that when walking into a swirling portal you are just instantly killed.  All bodypart HP is set to 0, you are dropped to the ground, and that's it, you're dead.  It seems unlikely that a bug is setting all bodypart hp to 0, which made me wonder if this was an intentional thing.  But there's no message printed in the log (or at least I cannot see one, though my sidebar is messed up in the footage).  Figure I probably should ping @Ramza13 

### Steps to reproduce

I was using the debug EOC to spawn the dungeon.  So do that.

Proceed through the swirling vortex to the next level.

Repeat until you are spat out into the sky or instantly murdered.

### Expected behavior

I don't understand the sky part, that's probably a bug.

The instant-kill that reduces all bodypart hp to 0 is confusing.  I don't think this should happen.  Even if this was the intentional design that's frankly, really really really terrible because the player has no agency in that moment, their life is just over.

I expect the vortex to continually move you to the next tier of the dungeon, and if there are no more tiers, no more vortex should be generated, there should only be the exit.

### Screenshots

Screenshot of being dumped into open sky -
![image](https://user-images.githubusercontent.com/41651793/178081082-ea2433e1-62b4-473a-9395-30f04cf75ecf.png)

And then here's a short video of my debug testing the dungeon where I suddenly get my HP set to zero.  Apologies for the sidebar, it is still messed up due to the jsonizing of sidebar elements, this means I did not see precisely what was said in the log.  

This video may be blurry or unavailable for a short time after this post as I just uploaded it.
https://youtu.be/JnT0DRP-jrs

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 414c57e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

As I said, all of this was done through debug testing.  I was starting the dungeon using the EOC.  It's unclear to me if this would cause problems leading to the issues I've mentioned.  I do not know if they would also happen in casual play or if this is one of those situations where debugging it has caused things not to work properly.

**Comment by TheMurderUnicorn** [comment]
Also apologies if the wrong ping went out, despite clearly saying ramza13 in the preview it pinged a random other person I don't know.  So . . . don't hate me if you got ghost pinged, sorry about that x_x

**Comment by Ramza13** [comment]
So was this using a version containing #58992?  If so then I must not have solved the issue completely.  In that case I have a guess for what might have caused it and will investigate.

**Comment by TheMurderUnicorn** [comment]
The dumping me out into the sky was something I encountered previously, using a version from monday (before the change you posted).  But the insta-death with my bodypart hp being set to 0 was on a version from earlier today, which is after that change was merged.

**Comment by zakhad** [comment]
/confirmed 

At first i thought i was just walking out of boundaries, but then even standing still just causes you to be ejected i don't know the technicalities of this though. 

![image](https://user-images.githubusercontent.com/5264667/178097410-7f30a394-2ef2-4e69-86c9-36552068c652.png)
![image](https://user-images.githubusercontent.com/5264667/178097423-d54a15ab-48f2-4092-a037-2fa7e2eab32c.png)
