### ISSUE TITLE
Going crouch/prone should help you avoid grenade shrapnel

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#59081]
### Is your feature request related to a problem? Please describe.

Crouching/Prone doesn't seem to have any noticeable effect on the amount of fragments that hit you when a grenade explodes.

### Solution you would like.

Based on PR [#49993](https://github.com/CleverRaven/Cataclysm-DDA/pull/49993), bomb fragments are already size aware.
My best guess is that the simple solution would be to change the player size based on crouch/prone position when doing bomb fragment calculations.

A prone person (especially with an army issue helmet) is extremely likely to avoid most lethal shrapnel from a grenade at any distance past 5 meters. 
Here's an image to help visualize a bit how much safer you are while prone.
![image](https://user-images.githubusercontent.com/22645231/178069499-9d1e952d-c2c5-46b5-8e11-49063b2fbc58.png)

While crouching would only reduce the damage, being prone should most certainly help avoid most if not all of the damage even at fairly close ranges.

### Describe alternatives you have considered.

A flat % dodge chance added to the shrapnel calculations thats cranked WAY up for prone people and slightly for crouched.

### Additional context

In hindsight this might actually be considered a bug so I may have mislabeled this submission

A lot of this may also be a result of my perception of distance in CDDA, but it "feels" like going prone doesn't have nearly enough effect against shrapnel as it should.

**Comment by Gotdamnmiracle** [comment]
I can confirm this does not happen in game and absolutely should happen. It is the method by which marines teach rifleman to avoid fragmentation shrapnel and is also the method illustrated in several military field manuals. 

I honestly thought this was already in the game before trying it and being cut to ribbons. It's pretty basic explosive knowledge. This doesn't necessarily hold for things IEDs and shapecharges, but it's a good rule of thumb.

**Comment by KHeket** [comment]
And also need to add check, is charecter crouching/prone in pit, deep peet, pile of stone trash, shallow/deep water, bushes, furniture water and etc, becouse all of this tiles and objects can partially or completely protect against fragments or/and blast
Ability to protect youself by using enemy dead body will be good too
If you are lying behind dead body of giant ant, hulk, juggernaut or anather big creature, I whink they will absob all of fragments
