### ISSUE TITLE
You need a bow fire drill to craft one

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#59093]
### Describe the bug

The recipe of the bow fire drill requires as components a plank or a stick and a bow fire drill.
So we have to imagine you already have one and toss the stick away or something?
: )

### Steps to reproduce

check out recipe

### Expected behavior

we expect the bow fire drill to be made from other stuff than an already existing bow fire drill

### Versions and configuration

win7, experimental from early june 2022

**Comment by anothersimulacrum** [comment]
There are two recipes:
![image](https://user-images.githubusercontent.com/42699974/178087219-d59fec3b-7464-4254-bec4-0ff7e36b044d.png)

**Comment by TheShadowFerret** [comment]
As @anothersimulacrum said, that is the reload recipe when your current fire drill is used up. The other one is the one you craft a new one with. There is no bug.

*Pokes close issue button*

**Comment by Cimanyd0** [comment]
![three different people in Discord, confused by this issue](https://user-images.githubusercontent.com/74877667/178090686-742916a7-50ba-4810-b849-14bfd5499b4a.png)

I think the issue is it keeps confusing players.

The recipe to actually craft a bow fire drill is autolearned at survival 2 and not visible before then. The recipe to use a new plank with it is autolearned "at birth", [as the Hitchhiker's Guide puts it](https://nornagon.github.io/cdda-guide/#/item/fire_drill), so everyone sees it immediately. The same goes for the pump fire drill.

**Comment by hexagonrecursion** [comment]
/confirmed

Unfortunately the ability to change the recipe name is currently only implemented for practice recipes. Fixing this would require a bit of C++

**Comment by mqrause** [comment]
To reduce the confusion, one option would be to give both recipes the same skill requirements so you see both at the same time.

**Comment by liminalRoar** [comment]
Is there now way we can add something to action or reload with the fire drill bow to allow us to reload manual if the materials are around? I really don't like that being a recipe. It doesn't seem like a good long term solution as it is rather confusing. i never realized what it was anyway.

**Comment by LyranRenegade** [comment]
right, I should've checked better.. Still indeed I agree it's confusing..

**Comment by descan** [comment]
It would be difficult to make the drill use planks as ammo, right? Because each use would use up the plank entirely, rather than a little bit at a time? Unless planks were changed to be more granular, which would have a lot of knock-on effects elsewhere I'm sure.

**Comment by mqrause** [comment]
Reloading with a plank is not really an option. However changing the drills to accept a fireboard as ammo and adding a recipe for fireboards might be a possibility.

**Comment by estebandellasilva** [comment]
... maybe you could make it so the bow fire drill once it has no charges to be used, become a different item

**Comment by descan** [comment]
It wouldn't fix the issue of two recipes with the same name, but it would at least lead to less confusion from people who read the ingredients list.

**Comment by estebandellasilva** [comment]
> It wouldn't fix the issue of two recipes with the same name, but it would at least lead to less confusion from people who read the ingredients list.

which is not really an issue as you can have multiple recipes with the same name ... looking at salt or sugar
