### ISSUE TITLE
Consistent crash from attacking zombies at a mine

### ISSUE THREAD

**Issue by BlueManedHawk** [CleverRaven/Cataclysm-DDA#59105]
### Describe the bug

I'm currently at a mine⁽⁰⁾, and whenever i attack the zombies there , the game crashes.

<sup style="line-height: 0.5">⁽⁰⁾I'm new to the game and had accidentally smashed all the lockers in the evac shelter instead of disassemling one, so i didn't have a metal sheet to make a brazier and get some food.  This was just the nearest location, so i decided to check.</sup>

### Steps to reproduce

1. Load the save that i've attached.
2. Try to attack one of the zombies that's just broken through.
3. After between 1 and a dozen attacks, the game will crash.

### Expected behavior

The game wouldn't crash.
<sup>Also, i'd probably be killed by all the zombies.</sup>

### Versions and configuration

OS is GalliumOS 3.1.  Game version is experimental 2022-07-09-0705 with tiles in English.  Mods loaded are: dda, no_npc_food, no_fungal_growth, package_bionic_professions, blazeindustries, magiclysm, generic_guns, DinoMod, alt_map_key, CrazyCataclysm, extra_mut_scens, MMA, translate_dialog, speedydex, stats_through_kills, StatsThroughSkills, Tamable_Wildlife.  Also, those two graphical mods.

### Additional context

There does not appear to be any such `crash.log` file.  I did hook up LLDB 13 to the process and could determine that it was a segfault from address 0xd0, but my computer doesn't have enough space for me to build a copy with debug symbols, so i don't know where it happened.  (I'm not sure how useful this information is.)

[Here's the save.](https://github.com/CleverRaven/Cataclysm-DDA/files/9076455/ConsistentAttackCrash.zip)

**Comment by mqrause** [comment]
Very likely fallout from #58666. I'll take a look at it in a bit, but if you wanna continue your game, try the version right before that.

**Comment by mqrause** [comment]
Yeah, happens on block, slight oversight and easy fix.

**Comment by BlueManedHawk** [comment]
Thank you!
