### ISSUE TITLE
World creation mode/variant selection (mod packages)

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59102]
### Is your feature request related to a problem? Please describe.

CDDA offers a vast world with many playstyles and features to enjoy. There are many visions for the future of this game. I think giving more power for the various mod communities and streamlining world creation is a win for everyone.

Started as a thought in #59074 comments; wanted to expand it out here.

### Solution you would like.

Allow game variant selection at world creation. A list of modes including Default CDDA for players to quickly select. Selecting a game mode with automatically load desired dependencies. Being able to load standard mod packages with larger CDDA overhauls would streamline and make more accessible those options. An explanation for the game mode and it's changes can be added underneath.

![CDDA-world-mods](https://user-images.githubusercontent.com/92204064/178104541-de89cce2-89ce-4225-8845-697ceef74966.jpg)

(Picture is just a rough idea of what i have in mind, but something along these lines.)

Legitimizing alternative ways of playing CDDA more while keeping the default experience might encourage experimenting more. This could especially be helpful for new players to see what the game offers while still allowing control over custom mod changes and making the standard CDDA experience clear.

### Additional context

Why do i want this? Partly, i'd love a more hardcore horror experience to be an option in CDDA which is not for everyone.

Will be adding more to this soon.

**Comment by chrispikula** [comment]
Do people _not_ play with the settings at worldgen?

The biggest thing that I find that new players aren't aware of is that world settings can be changed after world gen.  Item frequency, town frequency, evo factor, etc.

**Comment by liminalRoar** [comment]
Many people do, but i do think its an easily implemented, useful feature regardless. Maybe im wrong

**Comment by PatrikLundell** [comment]
I like the suggestion of mod packages and mod affinities.

I'd probably state that the selections are starting points for mod selection to inform players that they're not forced into taking these packages as is, but the selections can be modified, including by usage of third party mods (that have to be supported by third parties that are responsible for compatibility).

**Comment by liminalRoar** [comment]
Each selection would be a starting point of course. The way i see it is right now a new player creating a world might be unaware of how much the game can change with mods. The mod manager would still be there just like now.

We could add a small tip about customizing the world more with the mod manager. Possibly a future tutorial may have an early section on world creation and mod packages?

Debating if the player should be able to create custom mod affinities, name them, getting added for quick selection here as well. Probably, but maybe it is not needed and having that quick starting point is better.
