### ISSUE TITLE
Crash in advanced inventory

### ISSUE THREAD

**Issue by nik-ovchin** [CleverRaven/Cataclysm-DDA#59106]
### Describe the bug

Game crashed then trying open player inventory in advanced inventory (Shift+i)
Also with with ablosutly naked character

### Steps to reproduce

1. Start default scenario in default world
2. Open advanced inventory
3. Press Shift+i

### Expected behavior

I expected game not crash

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 979718d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9076550/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9076551/debug.log)

**Comment by BrettDong** [comment]
Might be related to #58666

**Comment by liminalRoar** [comment]
Shift + i ("I") is item comparison not AIM, right? a bit confused what the sequence of events was here.

**Comment by nik-ovchin** [comment]
> 

in AIM Shift+i will open player inventory on panel

**Comment by nik-ovchin** [comment]
to be clear
1. start new game
2. press /
3. press Shift+i

PS I think its default keybindings

**Comment by nik-ovchin** [comment]
> Might be related to #58666

Yep, Previuos version https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-07-09-0558/cdda-windows-tiles-sounds-x64-2022-07-09-0558.zip working fine

**Comment by mqrause** [comment]
I'll fix it with the other crash.
