### ISSUE TITLE
Too many aircraft carriers in lakes

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#59115]
### Describe the bug

I found four aircraft carriers in the same lake.

The US navy only has [11 aircraft carriers and 9 helicopter carriers](https://worldpopulationreview.com/country-rankings/aircraft-carriers-by-country). This is a sizable portion of their fleet sitting in a lake for no reason.

### Steps to reproduce

1. Find a big ol' lake
2. Explore it
3. Look at all these carriers!

### Expected behavior

I expect aircraft carriers to be much more rare.

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/178121196-9d2f4a9e-8f38-4492-9971-60892f586eef.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 4718292 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by hexagonrecursion** [comment]
I agree. The quantity of aircraft carriers is wrong. 1 out of 20 basements in C:DDA has a secret government lab under it. The ratio of secret labs to aircraft carriers in the real world is about 14 to 11. It is therefore unrealistic to see so few carriers. We need much more. :)

**Comment by Maleclypse** [comment]
Does carrier have the unique flag or was it not set til you’ve gotten it’s spawns tested? @GuardianDll

**Comment by Inglonias** [comment]
I should clarify that each of those carriers is in a different overmap sector.

**Comment by Inglonias** [comment]
The thought occurs to me that this special might be a good first candidate for the ability to make an overmap special globally unique introduced in #57127. It's on the lake, so there's zero chance of an anthill or fungal colony making it inaccessible, and it's rare enough.

**Comment by anothersimulacrum** [comment]
I think it's a good fit for that. It should be astonishingly rare, the only reason it can't be is for the starting location.

**Comment by GuardianDll** [comment]
/portal storm did it/

I think to add something that can say it was teleported here, but in the future it can be moved to the ocean, of course

**Comment by OpacareAngelus** [comment]
How many secret labs in the USA?
It really bothers me that there are so many secret labs in the game, it's not realistic :)

**Comment by GuardianDll** [comment]
#59975
