### ISSUE TITLE
Weapons spontaneously transform when fighting, probably triggered by a Krav Maga move

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59118]
### Describe the bug

My character wielded a combat knife, and after fighting a zombie I found that he was wielding a pair of cut resistant gloves. As that's the hand protection used, I scratched my head, put them on, and found that the combat knife was nowhere to be seen.
I then wielded a kukri instead, and also found that I somehow had two pairs of cut resistant gloves, so I took one pair off.
I then engaged a zombie brute, and eventually was sent flying. I then found that I was, again, wielding a pair of cut resistant gloves, ran off to pick up an aluminum bat, and finally managed to kill the brute.

### Steps to reproduce

1. Wear cut resistant gloves and wield a combat knife.
2. Engage a zombie.
3. Find that you're slapping it to death with cut resistant gloves.
4. Wield a backup kukri.
5. Engage a zombie.
6. Eventually find that you're again wielding cut resistant gloves.
7. Verify that you're now in possession of three pairs of cut resistant gloves and neither a combat knife of a kukri.

### Expected behavior

Weapons shouldn't spontaneously turn into other items.

### Screenshots

![Screenshot (249)](https://user-images.githubusercontent.com/22739822/178123866-ed761b70-12c1-4ef6-a3ba-328cb7426f22.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 979718d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms
+ JSON addition of welding supplies to workshop recipes

### Additional context

Continuing from the above, I replaced my weapon with a hunting knife. I then engaged a zombie, checking the inventory after each attack, and found the weapon intact after jabbing at the zombie, but replaced with a fourth pair of cut resistant gloves as soon as the message "You force the fat zombie to the ground for 9 damage, and hit it in the leg." as a result of a Krav Maga attack.

Killed the game and drove to the same town again. Saved.
Changed to Brawling and killed two zombies with the combat knife. Switched to Krav Maga and attacked a tough zombie. Suddenly was wearing two pairs of cut resistant gloves and wielding nothing again.

Killed the game again and this time used Ninjutsu. Killed about 10 zombies without losing the weapon.

**Comment by Sniper27IT** [comment]
Confirming, i have this too. I was fighting with Kukri and Krav Maga, my kukri turned into the gloves i was wearing (light survival), then again with a hunting knife. It seems that Krav Maga or other martial arts turn valid weapons into the glove you are wearing, duping them. I have also a Fireman Axe, that went unaffected.

**Comment by mqrause** [comment]
I'm assuming this is also caused by #58666. I'll look into it in a bit.
