### ISSUE TITLE
Wielded item is displayed as worn, if wearing an identical item.

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#59124]
### Describe the bug

The inventory menu will display your wielded item as being worn, if you are wearing an identical item. This will result in the inventory menu saying that you are wearing 2 of that item, even though you are actually wielding one of them. This bug does not occur if the items are different in any way (such as different damage states).

### Steps to reproduce

1. Spawn 2 identical, wearable items
2. Wear one of the items, wield the other. (which order you do this doesn't matter).
3. Open the 'i' inventory menu. It will show that you are wearing both of the items.

### Expected behavior

The inventory menu will display the wielded item as being wielded, not worn.

### Screenshots

Here's a test with leather belts. Notice the sidebar properly shows that I am wielding one of them, while the inventory menu says I am wearing 2 of them when I am actually only wearing one and wielding the other.
![Screenshot (176)](https://user-images.githubusercontent.com/38295275/178128761-49165a58-d738-489b-955a-2c0c2e25ef1c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: cf23f01 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by PatrikLundell** [comment]
Might be related to #59118 where a wielded weapon was transformed into a copy of the protection worn on the hands and reported to be worn in the inventory but wielded in the side bar (but still as the armor item, not the weapon).

**Comment by mqrause** [comment]
I don't think those are related. #58917 is a more likely cause of this.

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
