### ISSUE TITLE
Changing eye color or skin color using the standing mirror gives a boost in stats momentarily, and it stacks

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#59123]
### Describe the bug

as title says, was changing my eye color in the mirror, and i noticed i had massive boosted up stats after changing my eye color a bunch of times, check screenshot

### Steps to reproduce

1. open game
2. go to a house with a standing mirror
3. change your eye color or skin color using the standing mirror
4. open @ menu and notice the boosted stats.

### Expected behavior

To not become God's Avatar after changing your eye color

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/178127934-481b1afa-0d06-4296-afa7-27879f178f16.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 1d30382 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
/confirmed

1. Make a world with Stats Through Skills
2. Set your dodging skill to 5
3. Change your skin color using a standing mirror
4. Notice the stat boost

Note: the stat boost goes away after 1 turn

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cf23f01 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Qrox** [comment]
Imagine dragging a standing mirror behind you and changing your makeup before bashing a hulk into oblivion.
