### ISSUE TITLE
Idea - Some improvements the rechargeable battery mod

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#5912]
The rechargeable battery mod is really cool, but it occurred to me some parts of it are a little odd.
For one thing, it's built from the small storage battery (which holds 1000 power), but when you add it to a tool, the tool still only holds the same amount of power as default.  This doesn't really make sense, it should just set the capacity to 1000.

In addition, it would be cool if the battery mod could be charged while not attached to something, and remembered how much power it had in it, like uninstalled vehicle batteries do.  That way, you could charge the batteries and swap them in the field.

Does anyone think they could code this?  Is it a good idea?
##

**Comment by illi-kun** [comment]
Battery mod related stuff was updated recently.
