### ISSUE TITLE
Chitin suit is incompatible

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#59125]
### Describe the bug

When I am wearing chitinous armor, I can't wear chitin leg guards.
![image](https://user-images.githubusercontent.com/22638873/178130909-e332f8c8-b9eb-4f4a-8e5c-bb6f5336fe93.png)
![image](https://user-images.githubusercontent.com/22638873/178130914-d783ff54-a0a9-4a9d-9cc6-ee1567904d16.png)

### Steps to reproduce

1. Wear chitinous armor
2. Try to wear chitin leg guards

### Expected behavior

I can wear all the chitinous armors, just like other suits, such as steel suits, or scrap suits.
![image](https://user-images.githubusercontent.com/22638873/178130948-e630e3f1-0fed-4114-8303-d59726776239.png)
![image](https://user-images.githubusercontent.com/22638873/178131011-7b719575-9144-4ab2-8785-c068d404f14d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1806 (21H2)
- Game Version: 979718d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA]
]

**Comment by NetSysFire** [comment]
Can confirm. Since this covers the (upper) legs and is rigid, this is probably the problem. I would say this can be fixed in JSON.
