### ISSUE TITLE
[XEDRA Evolved] Fae meat disappears when loaded into smoking rack

### ISSUE THREAD

**Issue by LilimDiam** [CleverRaven/Cataclysm-DDA#59128]
### Describe the bug

You are able to load fae meat into smoking rack, however when you do so, the rack stays empty and you lose the meat that you've loaded.

### Steps to reproduce

Get Fae meat.
Try loading it into smoking rack.
Enjoy watching it disappear.

### Expected behavior

Meat *not* disappearing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 4d34ea0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Tamable Wildlife [Tamable_Wildlife]
    ]

**Comment by Maleclypse** [comment]
Suggestions welcome as my first attempt has not resolved the insert fae_meat into black hole effect the smoking rack is having on that item only.

**Comment by Maleclypse** [comment]
@anothersimulacrum I've checked that it has both the SMOKABLE flag and "smokes_into" and it doesn't even require you to turn on the smoking rack.  Just inserting a chunk of fae_meat causes it to vanish without filling the smoking rack.

**Comment by anothersimulacrum** [comment]
`fae_meat` is not considered food by `item::is_food()` - it lacks a comestible type.
