### ISSUE TITLE
Fabrics have too high barter value

### ISSUE THREAD

**Issue by taivo-tobreluts** [CleverRaven/Cataclysm-DDA#59129]
### Describe the bug

One cotton patch has a barter value 0.50$. Armed with a humble pair of scissors every single house in the game is a potential source for thousands of cotton patches. Once realized, that kinda breaks the economy.

### Steps to reproduce

Get a several sheets, cut them up, get to a merchant, buy entire stock.

### Expected behavior

Cotton, felt, leather, faux fur and synthetic fabric are very common items and not very useful to merchants so the buy price should be minimal (or better yet, zero).
I would expect merchants to only deal with large intact pieces of fabric and not bother with small patches at all.

### Screenshots

![image](https://user-images.githubusercontent.com/90152901/178139050-39de8844-368e-4de0-909b-ec24b52588ce.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.17763.3046 (1809)
- Game Version: 1d30382 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Crow's Hairstles 2: Bright [hairmod2_bright],
    Crow's Hairstles 2: Ears and Tails [hairmod2_earsAndTails],
    Crow's Hairstles 2: Natural [hairmod2_natural],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by pjf** [comment]
Looks like this can be closed now that #59389 has been merged. :tada:
