### ISSUE TITLE
Crash on martial art description

### ISSUE THREAD

**Issue by nik-ovchin** [CleverRaven/Cataclysm-DDA#59122]
### Describe the bug

Game crash if press F1 in martial art chosing window

Possible again https://github.com/CleverRaven/Cataclysm-DDA/pull/58666

### Steps to reproduce

1. Press "_"
2. Press F1

### Expected behavior

Game not crash

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: cf23f01 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9078201/crash.log)

**Comment by eturner** [comment]
Happens to me as well. Crashes immediately on F1.
