### ISSUE TITLE
NPC wielding null

### ISSUE THREAD

**Issue by nik-ovchin** [CleverRaven/Cataclysm-DDA#59136]
### Describe the bug

NPC faints and go into debug mode with log message "wielding null at value 0,7"
Again #58666 ?

### Steps to reproduce

After some time from begining starting NPC faints

### Expected behavior

Usual NPC behavior

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: cf23f01 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9078953/debug.log)

**Comment by mqrause** [comment]
/confirmed

This consistently happens when the starting NPC spawns without a weapon.
![grafik](https://user-images.githubusercontent.com/38702195/178144088-d7720473-b9b8-4bff-bab8-d8668f2eee24.png)

I can't tell the cause at this point, needs more investigation.

**Comment by PatrikLundell** [comment]
My characters have started to faint all over the place (#59143)), so it may be a common cause.
