### ISSUE TITLE
Companion entering infinite loop report

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59143]
### Describe the bug

While my character goes to sleep this message crops up (has happened twice, on this experimental):
 DEBUG    : NPC Eleanor Shank, meteorologist entered infinite loop.  Turning on debug mode

 FUNCTION : monmove
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\do_turn.cpp
 LINE     : 515
 VERSION  : 979718d

### Steps to reproduce

1. Set your companions to stay awake (the default setting).
2.  Set a companion to disassemble a large pile of things in an illuminated disassembly zone (so the task isn't interrupted by darkness).
3. Go to sleep.
4. After a number of hours this message crops up. This is approximately when the companion used to report the task "completed" and go to sleep.

### Expected behavior

Either the behavior in earlier versions (the companion decides to go to sleep in a bed, gradually accumulating unfinished disassembly items in the inventory for some reason), or the companion would just continue on without stop.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 979718d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms
+ JSON addition of welding supply crafting to the Workshop expansion.

### Additional context

It's now happened twice, which is the number of times my character has slept with this experimental version.

Waking the companion from the debug induced stasis in the morning doesn't seem to cause any issues. There's a message about believing the issue to be resolved when doing so.

Edit:
When I order companions to sort out loot they now run into a somewhat recently built wall of the base camp and shut down. I can't order the moron to stop the activity, as he claims not to have any, and then he shuts down again rather than following. I was able to get the companion to follow by giving a different order (construction) and then cancel it, lead the bugger away, and order him to sort out things elsewhere. He eventually shut down sorting out vehicle parts, however (because the PC also sorted out parts and took the last one?).
Whatever orders I give him, he just shuts down, quite possibly actually trying to perform the previous order and then failing again. I eventually gave up and sent him off on a base camp mission, as those companions are in stasis anyway.

**Comment by TiuTalk** [comment]
The same happened with me when I asked the companion to guard a position and come back a couple of days later.

**Comment by Ilurker** [comment]
This has happened to me and is popping up all over the discord lately. Seems to be fairly random. I fixed it by rolling back to 2022-07-08-0934 from 2022-07-09-1715, but I coudn't find any readily apparently PRs in that time that might have caused it.
