### ISSUE TITLE
misson_meteorologist_5 spawning too much copper wire

### ISSUE THREAD

**Issue by godhaj** [CleverRaven/Cataclysm-DDA#59144]
### Describe the bug

During misson_meteorologist_5 you find what is supposed to be wreck of a drone, wreckage consist of ,among other things, copper wire in quantities in thousands

### Steps to reproduce

Accept misson_meteorologist_5
Find objective (crashed drone)
Check amounts of copper wire in wreckage

### Expected behavior

Copper wire in single units, not thousands

### Screenshots

![image](https://user-images.githubusercontent.com/109033009/178150944-53ccaf9c-eb79-4550-b936-2b8cb729c221.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 8b7e574 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]

**Comment by Vaskritaya** [comment]
can confirm this happened in my game on the latest experimental as well, only using whatever the default mods are (like npc needs off, no fungal spread, etc). 18000 copper wire total
