### ISSUE TITLE
Cannot unload 1 tile vehicle from bike rack

### ISSUE THREAD

**Issue by TiuTalk** [CleverRaven/Cataclysm-DDA#59152]
### Describe the bug

When I try to unload my 1 tile vehicle from my bike rack I select the option "Load or unload vehicle" and nothing happens, the vehicle is still attached to the main one.

There are no message on the log, no errors, no crashes.

### Steps to reproduce

1. Make a vehicle with a bike rack
2. Load a one tile vehicle to the bike rack
3. Try to unload the vehicle

### Expected behavior

The vehicle to be unloaded

### Screenshots

[Screencast from 10-07-2022 19:59:53.webm](https://user-images.githubusercontent.com/145339/178165344-2f2ef873-0023-49da-8b21-dc5917843e54.webm)

![image](https://user-images.githubusercontent.com/145339/178165383-1260449a-9de2-47e6-93ac-8e13dec6590e.png)

![image](https://user-images.githubusercontent.com/145339/178165436-def2ebd5-83ce-4cf6-be38-3800138c1bd2.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: de006e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Generic Guns [generic_guns],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by delarifert** [comment]
just tested this, a single tile vehicle wont load onto the racks properly. but my 3-tile motorcycle works fine

![](https://i.imgur.com/Fp0EX5i.png)

**Comment by Devengel** [comment]
/confirmed

cannot load my 1 tile vehicle onto the bike rack as well

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 1d30382 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
/confirmed

Hello, @Devengel. Welcome to the bug verification squad. In order to use the /confirmed command, you should add yourself to the allowlist like this: https://github.com/CleverRaven/Cataclysm-DDA/compare/master...hexagonrecursion:Devengel-allowlist

**Comment by Devengel** [comment]
> /confirmed
> 
> Hello, @Devengel. Welcome to the bug verification squad. In order to use the /confirmed command, you should add yourself to the allowlist like this: [master...hexagonrecursion:Devengel-allowlist](https://github.com/CleverRaven/Cataclysm-DDA/compare/master...hexagonrecursion:Devengel-allowlist)

haha thank you, but i am mainly into adding PRs and such, Came here because i kept experiencing the same bug, along with a crash that i can't replicate.

**Comment by Devengel** [comment]
hmm, it seems to have something to deal with steel booms and solar panels? if i install those it doesn't load the vehicle, does if i remove them.

**Comment by TiuTalk** [comment]
> hmm, it seems to have something to deal with steel booms and solar panels? if i install those it doesn't load the vehicle, does if i remove them.

This is what my 1-tile vehicle looks like, should be the solar panel then 

![image](https://user-images.githubusercontent.com/145339/179229334-356c468c-bbfb-433f-ae08-0ed929b25d88.png)
