### ISSUE TITLE
Can't defend myself after activating an inflatable boat

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#59157]
### Describe the bug

Attempted to place an inflatable boat. Grinning coyote approached me and attacked me hundreds of times while I couldn't do anything.

### Steps to reproduce

1. debug spawn enemy nearby.
2. Attempt to place an inflatable boat with a hand pump.

### Expected behavior

Convert to an activity so it can be canceled.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: de006e8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by irwiss** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/60266
