### ISSUE TITLE
Karate roundhouse kick replaces wielded weapon with a copy of outermost item on feet.

### ISSUE THREAD

**Issue by delarifert** [CleverRaven/Cataclysm-DDA#59153]
### Describe the bug

When attacking with Karate, the roundhouse kick attack is replacing my weapon with a copy of my boots/whatever is outermost on the foot slot. I noticed this on my own character, confirmed it a couple times in that save and then found it also happens in a fresh world with a fresh character.

### Steps to reproduce

1. Create a world and a character, give them Karate and a compatible weapon, and enough stats to activate roundhouse kick
2. Hit something until roundhouse kick happens.
3. Weapon will disappear. If you try to equip something else, the game will ask what to do with your current weapon, a copy of your boots/whatever.

### Expected behavior

I would expect to kick the enemy I am fighting, vs the current kick my weapon into the shadow realm.

### Screenshots

here in my fresh default world with a random character, I gave them Karate, 5 in all skills to activate the abilities, and a staff.
![](https://i.imgur.com/WO7wIys.png)

ran around attacking things until a roundhouse kick went off. on the very first one,
![](https://i.imgur.com/UsUwId2.png)

my weapon vanished.
![](https://i.imgur.com/TT5DMFN.png)

nothing shown in inventory now
![](https://i.imgur.com/kBYMoNm.png)

when i wield anything else,
![](https://i.imgur.com/xqRnT9F.png)

i'm wielding a copy of my shoes
![](https://i.imgur.com/xMCdDGw.png)

same behavior seen on my older magiclysm character
![](https://i.imgur.com/h6dOtx9.png)
![](https://i.imgur.com/IjPjd2o.png)
![](https://i.imgur.com/4WALFrx.png)

### Versions and configuration

 - OS: Windows 10
 - Version Experimental 2022-07-10-0511
 - Graphics: Tiles
 - Language: English
 - Mods: Magiclysm+Mythical Martial Arts initially, same behavior on fresh default world

### Additional context

Rolled back to the previous version I had, 2022-07-09-0429 and the issue is gone.
![](https://i.imgur.com/e5pqm2T.png)

**Comment by delarifert** [comment]
i just found #58666 and built and tested those changes locally, that fixes this for me

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by delarifert** [comment]
just tested, this is fixed in experimental 2022-07-11-0524
