### ISSUE TITLE
Can't escape locked shed in the hunting lodge in various scenarios .

### ISSUE THREAD

**Issue by Beans142** [CleverRaven/Cataclysm-DDA#59150]
### Describe the bug

In various scenarios like (for example) a safe place you can choose the hunting lodge as a spawn location ,this has a chance to spawn you inside of a locked shed , this shed is made out of stone walls, has a closed metal door (non lockpickable) and has "window frame with high metal bars" for windows , i believe the only way to escape this shed is to use a hacksaw and saw the bars off .
The problem is this is not a garanted spawn , making this scenario impossible if you spawn in a locked shed without a hacksaw.

### Steps to reproduce

1.Make a character and pick the safe place scenario 
2.Pick hunting lodge as your starting location
3.Hope(not) to spawn inside the locked shed 
4.Look around the shed for a hacksaw
5.Possibly not find one.

### Expected behavior

I expect that i would find a hacksaw or some other method of exiting the shed.

### Screenshots
Every item in the shed:
![Captura de Ecrã (143)](https://user-images.githubusercontent.com/109043884/178162509-b6c17603-cb45-4883-9a2c-dfd2a5bc24b7.png)
![Captura de Ecrã (142)](https://user-images.githubusercontent.com/109043884/178162512-f073d0fb-1f5c-4051-b6f7-a67da2ef4eaf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 1d30382 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    My Sweet Cataclysm [my_sweet_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills]
]

**Comment by Maleclypse** [comment]
Can you share a screenshot of the “shed” you are spawning inside?

**Comment by Beans142** [comment]
![Captura de Ecrã (144)](https://user-images.githubusercontent.com/109043884/178338974-06699f42-3411-4320-970c-13db2732c8f9.png)

**Comment by hexagonrecursion** [comment]
/confirmed

![image](https://user-images.githubusercontent.com/52621858/178396024-3acf5f88-02ca-4d8f-9a9e-e83b0ddf2072.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Starting in a locked shed is silly in the first place, it shouldn't be a normal situation, no need to put items that would help with getting out. We need to either remove the hunting lodge from the list if possible starting locations, or leave it as is, saying "bad luck" and suggesting to restart the game.

**Comment by Maleclypse** [comment]
I’m for removing it from starting locations.

**Comment by Amoebka** [comment]
The issue might affect more than just this particular location. Anything that has locked doors is a future risk. Maybe some kind of on-spawn EoC that unlock all doors in the starting location for the non-challenge scenarios? The player had to get in there in the first place, after all.

**Comment by Zireael07** [comment]
I seem to recall similar problems in hospitals and firestation and police station starts, so I think a "starting_zone" is necessary

**Comment by hexagonrecursion** [comment]
> I seem to recall similar problems in hospitals and firestation and police station starts, so I think a "starting_zone" is necessary

Could we use the same mechanism as the lab challenge (it always spawns the player in the prison cell)?

**Comment by Zireael07** [comment]
IIRC lab challenge cheats around the problem by having prison cell be a separate OMT. IIRC police station is a single OMT though...
