### ISSUE TITLE
Extension cord disappears when taking down appliance

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#59168]
### Describe the bug

When taking down appliance with extension cord plugged in, the extension cord is not returned.

### Steps to reproduce

1. Put up appliance
2. Connect the appliance to the grid using an extension cord
3. Take down the appliance
4. Extension cord nowhere to be found

### Expected behavior

The extension cord should drop along with the appliance.

### Versions and configuration

350a2ead748027fac358bd8649af95c9ee33572b

**Comment by deafmole** [comment]
Can confirm, happened to me yesterday aswell.

**Comment by TheShadowFerret** [comment]
/confirmed

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: 20872a7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]
