### ISSUE TITLE
Allow unplugging appliance

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#59166]
### Is your feature request related to a problem? Please describe.

Sometimes you may want to disconnect an appliance and connect it to a different grid, or may want to recover an extension cord and use it elsewhere, but currently you can only unplug an appliance by dragging it around which sometimes you cannot do because the appliance is blocked by other appliances/vehicles.

### Solution you would like.

An option to remove a particular connection from an appliance, like how jumper cable is removed from a vehicle

### Describe alternatives you have considered.

None

**Comment by esotericist** [comment]
note that you currently also cannot disconnect jumper cables from appliances that you attached from a vehicle. of course directly connecting jumper cables to arbitrary appliances might not be appropriate, see #59169
