### ISSUE TITLE
Extension cord cannot be plugged into vehicle

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#59169]
### Describe the bug

You can connect an appliance with a nearby vehicle, but cannot connect an appliance with a vehicle using extension cord. You can do so using a jumper cable or heavy-duty cable though.

### Steps to reproduce

1. Put up appliance
2. Construct vehicle
3. Plug extension cord into the appliance
4. Cannot plug the extension cord into the vehicle

### Expected behavior

Being able to plug extension cord into a vehicle. Alternatively, disallow connecting an appliance to a vehicle without using a jumper cable or heavy-duty cable, and make it clear in the item description and show a warning message when the player tries to do so.

### Versions and configuration

350a2ead748027fac358bd8649af95c9ee33572b

**Comment by hexagonrecursion** [comment]
/confirmed

Note: most extension cords I have seen are designed to plug into an outlet and most cars do not have an outlet.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by esotericist** [comment]
what we probably want here is some kind of appliance specifically designed for connecting vehicles to the appliance network.

**Comment by bombasticSlacks** [comment]
Yeah so this was requested and intended (as can be seen in the original PR), but you are right that the connection otherwise shouldn't be free.
