### ISSUE TITLE
Scythe blade disassembly is instantaneous

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#59161]
### Describe the bug

Seems like an oversight to make it possible to instantaneously disassemble a scythe blade into 1 lump of steel. 

### Steps to reproduce

Make a character with 5 fabrication level. Forge a scythe blade. Disassemble it via the ( key to get a lump of steel. 

### Expected behavior

It doesn't make sense to be able to instantaneously to disassemble a scythe blade. For comparison, a spike takes 30 minutes to disassemble and produces 1 chunk of steel. 

### Screenshots

![image](https://user-images.githubusercontent.com/108444328/178181020-47a1fe3b-3060-4686-9ca1-354b4b1d5256.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: fa6f25b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
I don't think this is a bug. Scythe blade is in fact a lump of steel, so you're not actually _disassembling_ it, but rather _converting_ it into a lump of steel to make it accessible for other recipes. It shouldn't require any time to convert blade into lump of steel.

The actual bug here is time required to disassemble spike being so big.

**Comment by Night-Pryanik** [comment]
Closing as not-a-bug. Spike disassembly time fixed in #59763.
