### ISSUE TITLE
Extension cord dropped when dragging appliance around

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#59167]
### Describe the bug

When you connect two appliances using an extension cord, the extension cord is dropped when you drag one of the appliances around, even if the distance between the two appliances is less than the maximum length of the extension cord.

### Steps to reproduce

1. Put up twp appliances
2. Connect the appliances using an extension cord
3. Drag one of the appliances
4. See that the extension cord is dropped to the ground

### Expected behavior

Extension cord not dropped to the ground unless the distance between appliances exceeds the maximum length of the extension cord. And a message indicating the extension cord is dropped in the latter case.

### Versions and configuration

350a2ead748027fac358bd8649af95c9ee33572b

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
