### ISSUE TITLE
Intercom bugged after some time and became unable to trade

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#59170]
### Describe the bug

After some time intercome intering debug mode with next crash text

DEBUG    : NPC the intercom entered infinite loop.  Turning on debug mode

 FUNCTION : monmove
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\do_turn.cpp
 LINE     : 515
 VERSION  : ca79ddd

And afer it you cant trade with him becouse of "the intercome doesn't have the appropriate pockets to accept that", which making him unable to trade

### Steps to reproduce

1. Teleport to intercome
2. Take first quest for killing robot and complete it
3. wait for some time near the intercome 1 or more hour is enough, may be it will need more time
4. See crash text
5. try to trade with intercome and see, how it cant buy anything becouse of the lack of pockets
6. Cry, becouse you cant buy good armor

You can also close game, than start it again ater crash and see this crash again after a few seconds

### Expected behavior

I expected to trade with intercome and have no crashes

### Screenshots

![image](https://user-images.githubusercontent.com/102726167/178215959-76a8682b-a30e-493e-8598-73363dce9147.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: ca79ddd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9081949/debug.log)

here is my save file \/
But you can easyly make this crash by yourself

[Мед.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9081982/default.zip)

**Comment by PatrikLundell** [comment]
I believe it's yet another manifestation of what causes of #59143, although  I would guess this case might be even worse as there probably isn't any way to recover from it.
When the underlying problem is fixed, there should probably be something that also removes companions and NPCs from this state when a save is loaded as a way to to recover (if whatever is the problem remains, the communications partner would fall into coma again when talked to, so it would be one recovery attempt per save load).

**Comment by KHeket** [comment]
@mqrause need your help

**Comment by mqrause** [comment]
Yeah, I figured out I caused this, too. But I have no idea what the issue is or how to fix it.

**Comment by KHeket** [comment]
> Yeah, I figured out I caused this, too. But I have no idea what the issue is or how to fix it.

I figure out that this problem happen at refuge center too, and a lot of npc caused this. And I also checked all of them, and npc which dont wielding weapons in hands - caused this crash, and npc without weapons in had - do not cause this crash. I also gave to intercome from debug meny m4a1 - and crashes dissappeared

It looks like friendly or neutral npc without weapon in hands trying to pick it and cousing this crash and bug

You can reproduce this by spawning with debug menu a lot of npc, than wait for some time and check names of npcs, whick causing this crash - all of them will not have weps

**Comment by mqrause** [comment]
That's also as far as I got. NPCs not wielding anything that don't find anything better to wield cause this issue, I just don't see what changes I made that cause this.
