### ISSUE TITLE
Bike rack + welding rig = segmentation fault

### ISSUE THREAD

**Issue by Bark0805** [CleverRaven/Cataclysm-DDA#59173]
### Describe the bug

Welding rig attached to car using bike rack, when i try to use welding rig game crash.

### Steps to reproduce

1. Load my save
2. 'e' on welding rig
3. 'w' Use arc welder
4. Game crash

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Бионические профессии [package_bionic_professions],
    Без ж/д станций [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Скорость от ловкости [speedydex],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9083343/crash.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9083355/Save.zip)

**Comment by irwiss** [comment]
Wasn't able to reproduce the crash on current master (63257f7b147a4c90044a5555afe710e04361ac1e)
Tried:
With or without the Tankmod_Revived
With english or russian language selected
Detached/attached the cart
Tried arc welder and solder iron
