### ISSUE TITLE
lantern for candle

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#59172]
### Is your feature request related to a problem? Please describe.

candles blow out in the wind outside. I feel like there are many very easy crafting options to protect candles from wind

### Solution you would like.

a lantern made from paper or glass would be nice

### Describe alternatives you have considered.

well there are jack o lanterns, but they need pumpkins. There are also oil lamps, but right now they dont run with Z fat. And there are other lighting options, too, but its the same with them.

### Additional context

i feel like i dont need to deliver proof that lanterns protect open small lighting fires from wind since the time paper or glass is used. Those options are cheap, low-tech and very common

**Comment by kevingranade** [comment]
Helping stale bot catch up with mega stale issues.
This would be fine to add but doesn't need an issue.
