### ISSUE TITLE
Let's setup a folder structure for the source code.

### ISSUE THREAD

**Issue by Nyghtrid3r** [CleverRaven/Cataclysm-DDA#59181]
### Is your feature request related to a problem? Please describe.

Currently, almost all the source code is located in the /src directory. The amount of files might not have reached critical mass yet, but it's likely they will at some point. This makes it difficult to navigate, especially for new contributors.

### Solution you would like.

I suggest grouping the files by their areas of concern (i.e. GUI, creatures, map, attacks, utilities, etc.) and placing them in a respective subdirectory. Naturally, this requires adjustment of the `#include` commands and the CMake script. Jenkins might also get upset and require tinkering.

The change itself will be relatively easy to make, of course, but this will come with caveats. Any currently open branches will have merge issues. We also need to make sure that future contributions are added to the correct folder.

I suggest making this change after the 0.G release. Or making this a long term goal. Perhaps we could also refactor the code incrementally.

### Describe alternatives you have considered.

We could leave it as it is. This change would of course slow down progress, but I strongly recommend against putting this off to prevent the technical debt from continuing to pile on. It will only get worse and harder to make this change as the game gets bigger.

**Comment by andrei8l** [comment]
There are no distinct or independent subprojects in `src` so there is nothing to gain from an arbitrary folder structure. Symbol navigation through ctags/clangd/intellisense/whatever-your-IDE-uses and regex searching with `git grep` (or otherwise) already let you navigate the code easily.

**Comment by Nyghtrid3r** [comment]
> There are no distinct or independent subprojects in `src` so there is nothing to gain from an arbitrary folder structure.

Well yeah there is. Ther

**Comment by Nyghtrid3r** [comment]
Fat fingers.

Well yeah there is a benefit. The code has better structure and it's easier to see which files belong to what. It's not necessarily tied to submodules either. And while there are ways to navigate the code, it still requires a general idea of the content.

**Comment by natsirt721** [comment]
NPC and the vehicle stuff could use a subfolder sure. I'm not sure that much else needs it tbh.

I'll admit, when I first saw that `src` had _everything_ in it I too was disgusted. But at this point I don't think there is much to gain from a major reorg, and there is a simple beauty to not having to deal with nested folders. 

"Where is that file again?"
"Of course, its in src"

**Comment by anothersimulacrum** [comment]
1. This makes tracking history messy
2. You make merge conflicts for literally everyone doing C++ work
3. You simultaneously make every build system more complicated and have to fix all of them
4. The benefits are pretty negligible

akrieger: (https://discord.com/channels/598523535169945603/598535827169083403/982716226855907358)

> i'm going to pile into this thread cause i actually did a little bit of 'just add a folder for organization' for src/third-party. This was easy enough when it was just headers (add a few new include paths in a few places), but i have an in progress pr which actually adds sources and it was a much bigger headache then. part of the issue is, yes the variety of build systems we're using, and each of them have their own quirks and ways of doing things (and are not all super well structured like more modern build systems). fixing cmake was probably the easiest one to fix once i had a repro command, and i hate cmake. it was a big hurdle to overcome just to slot some third party library code into a separate location to keep it physically sorted off from the other sources. if it wasn't because i was introducing a new paradigm (interned third party code into the repo) i wouldn't have done it.
>
> cata has one folder per each logzical unit of code. there's src for 'all of cata', there's tests for the tests, there's object_creator, src/chkjson for the... chkjson util. but it doesn't really make sense to slice cata any finer than it already is. you need all of it for any of it to work, you can see just from all the #include directives in the files how interconnected all the code is.

Kevin: (https://discord.com/channels/598523535169945603/598535827169083403/982720274535415868)

> The most I could ever see would be sequestering some of the mega objects like vehicle, item, creature and map, maybe the serialization code.
That's not going to "make it easier to find things", it would be to enforce seperation between class namespaces to help with build times

Something like this could happen, as Kevin mentions, but it would be a concerted effort in specific areas. Having an issue this broad in scope won't do anything towards achieving that goal.
