### ISSUE TITLE
shifting masses in the sky

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#59197]
### Describe the bug

There's lingering shuffling masses in the sky despite the last portal storm is 2-3 days ago. I assume it came from the portal storm dungeon since I don't think portal storm can spawn 17 shuffling masses at the same time   

### Steps to reproduce

Not sure how did it happen, but I suspect that the portal storm dungeon I have visited might have to do with it

### Expected behavior

There shouldn't be any shuffling masses in the sky outside of the portal storm

### Screenshots

![Screenshot_20220712-170537](https://user-images.githubusercontent.com/78019001/178469051-6e10c85e-f4f6-4b8b-bace-a9590e5758a0.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 41b1786 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Crow's Hairstles 2: Bright [hairmod2_bright],
    Crow's Hairstles 2: Ears and Tails [hairmod2_earsAndTails],
    Crow's Hairstles 2: Natural [hairmod2_natural],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Recipe Fix [recipe_fix],
    Blu [blu],
    Structured Sidebar [Structured_Sidebar],
    Blaze Industries [blazeindustries]
]

**Comment by PatrikLundell** [comment]
This looks like the same issue as #58967

**Comment by Ramza13** [comment]
Ahh yea I know what causes this and have the solution in a PR I'm working on.
