### ISSUE TITLE
Flashlight app on smartphones does not light up anything

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#59196]
### Describe the bug

When activating flashlight on a smartphone, no light appears.

### Steps to reproduce

1. Have a charged smartphone
2. Activate flashlight on it

### Expected behavior

I expected a smartphone flashlight to lighten up at least in one tile radius.

### Screenshots

![cataclysm-tiles_zk17qOmk7A](https://user-images.githubusercontent.com/30211338/178468900-754cd110-3c1a-43b9-91f4-457630ac6d00.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: ec37cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Have you moved one step?
There was a change a month or more ago that caused effects to be delayed one turn (lots and lots of effects...). This wasn't the intended effect, but only a small number of individual cases have been fixed since.

**Comment by Joanakor** [comment]
> Have you moved one step? There was a change a month or more ago that caused effects to be delayed one turn (lots and lots of effects...). This wasn't the intended effect, but only a small number of individual cases have been fixed since.

I know about this and it is definitely not the case. The regular flashlight works just fine.

**Comment by descan** [comment]
Can confirm that moving one step with a smartphone flashlight (fully charged, too) does not activate the light.

**Comment by natsirt721** [comment]
Possibly related #59117? But I can't quite tell how...

**Comment by Aerin-of-the-Toast** [comment]
I can confirm too, same issue. Smartphone is providing no light when activated.

**Comment by Inglonias** [comment]
> Possibly related #59117? But I can't quite tell how...
> 
> Edit: I think the in the "extend" in the linked PR should be extending "flags" instead of "effects". I'd wager that the music function doesn't actually boost morale either.

This is correct. I'm submitting a PR to fix this.
