### ISSUE TITLE
add schedule to basecamp

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#59207]
### Is your feature request related to a problem? Please describe.

going frequently to the basecamp to assign activities to the NPCs and having to keep track of activities status

### Solution you would like.

adding a camp schedule

### Additional context

lines being hours of the day and columns the existing NPCs, when adding an activity you would be bring back to the main menu

**Comment by descan** [comment]
... Do you mean a camp schedule?

**Comment by jfferson** [comment]
> ... Do you mean a camp schedule? A chronogram is a different thing entirely.

yes
