### ISSUE TITLE
chainmail faraday suit is missing Rubber boots environmental protections, despite using rubber boots as an ingredient

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59200]
### Describe the bug

as title says, it is missing rubber boot's environmental protection values

### Steps to reproduce

debug spawn both rubber boots and chainmail faraday suit, see that the suit is missing the enviromental protection values the rubber boots has

debug learn all recipes to see that it indeed requires rubber boots as an ingredient, and that it blocks other footwear

### Expected behavior

For chainmail faraday suit to adopt the values of the ingredients it uses

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/178478094-2c498fd7-7e7f-461d-b627-48c540fce930.png)
![image](https://user-images.githubusercontent.com/71761521/178478102-4eb28470-bb24-43cc-8952-593cf979c95a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 1d30382 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 8f770f0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Can confirm too on 0.F-12380.
Even adding `"environmental_protection": 12` (like on rubber boots) to legs armor portion of faraday suit doesn't work for some reason, though it's supposed to be supported in the code.

**Comment by GuardianDll** [comment]
resolved by #61066
