### ISSUE TITLE
Suggested Item: Long sticks for mobility of rafts and boats

### ISSUE THREAD

**Issue by LightCaptain** [CleverRaven/Cataclysm-DDA#59206]
### Is your feature request related to a problem? Please describe.

(Stable Frank-3) When building boats from scratch, nails are required to make oars and sails. When surviving in the wilderness or playing in a world without man-made items nails are difficult to get everything needed to make them for using in these two recipes. Without the oar or sail this leaves a raft without any way to move for driving on water.

### Solution you would like.

Something similar to a paddle or sail that can be crafted in the wilds without any forged metal.

### Describe alternatives you have considered.

Any kind of long stick, staff or pole for use as a paddle while the driver stands on their raft or on the edge of their boat. Much like the river rafts used in the 19th century.

### Additional context

I assume that using sticks without wide flat ends would be less effective than oars for controlled movement (unless they can push off the ground under shallow water). So it would be a lot slower or useless for moving large heavy boats and would take more human effort to get up to the same speed as rafts/boats with oars.

I think there's two ways it can be used to move a boat:
*Poke the bottom end of the stick into the water that's out in the direction you want to go then pull the end down back past behind you.
*Poke the stick in the water close to the raft/boat and quickly stir in tight circles to create small whirl pools which'll draw the boat in the direction you want to go.

**Comment by natsirt721** [comment]
There's [this recipe](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/tools/tools_primitive.json#L410) which does not require nails.

**Comment by LightCaptain** [comment]
> There's [this recipe](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/tools/tools_primitive.json#L410) for oars which does not require nails.

Ok good to know. I had been playing frank 3 for a while. I'll consider playing the experimental version to use this recipe.
