### ISSUE TITLE
Peasant flail damage showing higher when weapon is damaged

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#59210]
### Describe the bug

A peasant flail shows higher damage when the weapon's condition worsens.

NOTE: the base melee damage seems to be reflected ok, but the DPS and damage per stamina are off. Unsure if this reflects the true damage, or if it is a bug in the stats displayed.

### Steps to reproduce

view damage values of a new or repaired peasant flail and compare after it becomes damaged.

check other weapons?

### Expected behavior

These values should be reversed?

### Screenshots

![undamaged-damage](https://user-images.githubusercontent.com/92204064/178550145-7d319407-eb94-4415-95a3-c01b126d2171.jpg)
![damaged-damage](https://user-images.githubusercontent.com/92204064/178550153-c2de73e1-4558-42cb-a468-315fc1493888.jpg)
![stats](https://user-images.githubusercontent.com/92204064/178550161-819be2a2-d6c7-4f63-8b72-f1236b637f15.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-S205DL; Release: 10; Incremental: S205DLUDU5BTE7; 
- Game Version: ca79ddd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

As a side note, when comparing two items, the highlighted green and red values for which is better need reversed for many functions. (the colors, not values)

**Comment by liminalRoar** [comment]
item description is showing different adjusted moves per attack

154 - Undamaged
124 - Damaged    -    |\

**Comment by hexagonrecursion** [comment]
Please upload your save file. I am sorry, but I could not reproduce this bug. What is adjusted moves per attack? Where can I see this statistic? Were you able to reliably reproduce the bug? How?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 9be17db [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by liminalRoar** [comment]
Well, oddly enough, i just repaired two worn down peasant flails so that one is fully repaired and the other is damaged ( |\ ) and compared with "I". The stats look as they should.

However, i will try using the fully repaired flail until it is damaged again and make sure it looks the same as the other. If not i will include the save with the item discrepancies.,

**Comment by liminalRoar** [comment]
It appears it was in fact the repaired flail that was displaying wrong as the |\ damage was correct. I am unsure what caused this..

The previous time i repaired the peasant flail the damage was nearly halved. And restored its regular damage after it was damaged.

This time when i fully repaired the flail it displayed correctly.
