### ISSUE TITLE
Craftability of footcranks

### ISSUE THREAD

**Issue by n0pen** [CleverRaven/Cataclysm-DDA#59213]
### Is your feature request related to a problem? Please describe.

At the time, there is no access to foot cranks other than disassembly of cranked machines, which is limiting in wilderness scenarios (Innawoods for example)
Access to foot cranks open some  very useful crafting recipes:

- Can sealers
- Manual oil press
- Pedal powered grindstone

It would also give us more options for light vehicle crafting

### Solution you would like.

Adding a crafting recipe for foot cranks

### Describe alternatives you have considered.

Add the recipe for Innawoods only (where you can't find them in the wild)

### Additional context

"Modern" pedal powered machines were created during the 1800's
https://www.lowtechmagazine.com/2011/05/history-of-pedal-powered-machines.html
there is a short summary of different types of machines using pedals.

The first pedal powered bicycle was created in the 1850's according to wikipedia
https://en.wikipedia.org/wiki/History_of_the_bicycle

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/42497

**Comment by n0pen** [comment]
#59138 seems to have solved this problem in a better way
