### ISSUE TITLE
Advanced solar panels use solar cells as ingredients for repair, Not advanced solar cells

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#59221]
### Describe the bug

as title says, solar cells is for normal panels, advanced cells is for advanced solar cells

### Steps to reproduce

1.try to repair advanced solar panel either on a vehicle or as an item
2.see that it requires normal cells

### Expected behavior

to use advanced solar cells as repair ingredient instead of normal cells

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/178701741-0eb09561-9e71-4e9b-adef-90402984b7a7.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: ec37cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
Failed to repeat with the default mods, so it's presumably something added in a mod.
The standard game doesn't allow solar panels to be repaired, and the recipe for the advanced panel calls for advanced cells (checked by loading a save and spawning a panel to check for repair options, as well as checking the construction recipe).

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 0.F-9864-g704a963e39 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by molkero** [comment]
> The standard game doesn't allow solar panels to be repaired

Both panels can be repaired if installed in a vehicle, not as items. Repairing installed advanced panel doesn't take advanced cells.

![Screenshot_20220713_222335](https://user-images.githubusercontent.com/49575273/178815536-14751030-5a49-444c-96dd-2653c36178f9.png)

![Screenshot_20220713_222826](https://user-images.githubusercontent.com/49575273/178816070-e9bbf95b-22ed-4876-9480-d43c5178fac5.png)

![Screenshot_20220713_223308](https://user-images.githubusercontent.com/49575273/178816959-a838e787-e003-4759-b210-2789f575704c.png)

![Screenshot_20220713_223333](https://user-images.githubusercontent.com/49575273/178816967-dca24212-b814-4f18-be39-97e68e090709.png)

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 21.3.3; Codename: Ruah; 
- Game Version: 0.F-9864-g704a963e39 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots]
]

**Comment by PatrikLundell** [comment]
/confirmed

I'm sorry. I was wrong. I didn't know you could repair solar panels when installed.

I did get hold of a damaged advanced solar panel, installed in in a vehicle, and verified that trying to repair it required regular cells, not the advanced version.
