### ISSUE TITLE
sidebar UI, "var": "place_text", do not change color. always c_light_gray

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59228]
### Describe the bug

following widget should add place description colored white, but it stays c_light_gray. 

`  { "id": "i_place_text",       "width": 23,
    "style": "text",
    "var": "place_text",
    "colors": [ "c_white" ],
    "type": "widget"
  },`

### Steps to reproduce

add my snippet to the sidebar

### Expected behavior

text should change color

### Screenshots

![image](https://user-images.githubusercontent.com/6676374/178765086-b74ea942-eda6-4e26-957c-1385d82b95ea.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: ec37cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Inglonias** [comment]
I believe that text widgets are expected to define a color in the string coming back. This is why, for instance, the safe mode widget doesn't need to have a color set. The location widget currently does not seem to do this.

**Comment by vetall812** [comment]
> I believe that text widgets are expected to define a color in the string coming back. This is why, for instance, the safe mode widget doesn't need to have a color set. The location widget currently does not seem to do this.

So it's not a bug, it's a feature. )
Can we override color in widget?

**Comment by Inglonias** [comment]
The game should probably allow some sort of color override, yes.

**Comment by vetall812** [comment]
> The game should probably allow some sort of color override, yes. 
> 
> To clarify, right now we do not

Is there any way way to transform "bug" into "feature request"?

**Comment by anothersimulacrum** [comment]
That good?
