### ISSUE TITLE
"Iron Safari" mission is ambiguously worded

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#59233]
### Is your feature request related to a problem? Please describe.

The "Iron Safari" mission given by Hub 01 doesn't sufficiently specify that you're supposed to disable the robot without destroying it.

### Solution you would like.

The description can be simply changed from "Disable and retrieve the unusual robot." to "Disable and retrieve the unusual robot without destroying it."

### Describe alternatives you have considered.

You can leave it as is, but I doubt I was the only one confused by this

**Comment by a-chancey** [comment]
I agree that this is a bit ambiguous. Maybe an extra bit of dialog just explaining "get a hit on the sensors with the dazzle rifle to scramble it, then you have to physically deactivate it before it recovers, but remember: we need it intact."

**Comment by bouchacha** [comment]
Do you have to damage it first before using the dazzle rifle? Or do you have to use the dazzle rifle and then run up to it to manually shut it down? So many questions
