### ISSUE TITLE
"Suit" should not be a single piece of equipment

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#59234]
### Is your feature request related to a problem? Please describe.

"Suit" is described as a "full-body cotton suit", and presumably includes both a blazer and some dress pants. It's not clear why this would need to be a single and inseparable piece of equipment. Further, the entire thing is uniformly on the 'Outer' layer, which means you can wear a suit with cargo pants and have no encumbrance penalties. Also, the lawyer profession starts with a suit, but apparently no dress shirt (or maybe a dress shirt is implicitly included in the suit item?) which is a bit weird.

### Solution you would like.

Instead of a single equipment, suit should be made obsolete and replaced by different bits of equipment. We already have 'blazer' and 'dress shirt', both of which are FANCY. The only thing missing would be a new item called 'dress pants' or 'suit pants' which is also made of wool and also FANCY. After that, every mention of 'suit' can just be replaced by these three separate items or put in the same loot table.

### Describe alternatives you have considered.

I can't get the picture out of my head of a lawyer wearing a suit and tie, but without a dress shirt on.

**Comment by pjf** [comment]
Wait, isn't this how suits normally work?

![suit](https://user-images.githubusercontent.com/12072/178850671-8e67c56c-abd2-4e5d-a8be-aabfb2f71262.png)

**Comment by RelMayers** [comment]
It could be kept in suit protection thingy (do not know this name) and just nested inside
