### ISSUE TITLE
Excessive calcium chloride byproduct from washing soda recipe

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#59230]
### Describe the bug

You could create 12750 (25.5 kg) calcium chloride by crafting 41 washing soda, using 3 (780 g) salt water, 8 (112 g) limestone, and 4 (496 g) liquid ammonia.

### Steps to reproduce

1. Learn washing soda recipe
2. Get all the ingredients
3. ???
4. Profit!!!

### Expected behavior

Producing 51 charges of calcium chloride is probably what the recipe has intended, but somehow the byproduct number is treated as number of default stacks instead of charges. I suspect other recipes with byproducts may also have similar problems.

### Versions and configuration

350a2ead748027fac358bd8649af95c9ee33572b

**Comment by Maleclypse** [comment]
/confirmed


I made a batch of 41 and received 1 ton of calcium chloride .

**Comment by RenechCDDA** [comment]
Resolved by #63137
