### ISSUE TITLE
Military outpost is on fire

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#59248]
### Is your feature request related to a problem? Please describe.

Everytime I am trying to loot military outpost - turrets killing zombie burners, they expoding and burn a lot of valuable loot to ash. And zombie burner explosion probability must be 10%, but they are exploding every time

### Solution you would like.

I have at least two solutinons to this problem
1) Split spawn points to make robots and zombies spawn in different rooms, to prevent them spawn in one room. In one room must be robots or zombies, not both. And replace wooden doors with metal to prevent zombies from breaking them and duying from robots. There is some logick. Solders before dead have no need to protect rooms, wich are already protected by robots, and there is no need of robots in dorminotory
2) Place military zombie spawn outside of outpost, and robot spawn inside. Simular to new bunkers with lots of zeds outside and 1 turret inside

### Describe alternatives you have considered.

Leave all as it is and contine to loose lots of stuff

**Comment by a-chancey** [comment]
Yeah it's a bug with the fireball death spell, I've been trying to pin it down in debug but haven't been able to yet, like it just ignores the fake deathspell completely. 

Zomborgs are exploding into fireballs 100% of the time now, as well

**Comment by KHeket** [comment]
Solved in https://github.com/CleverRaven/Cataclysm-DDA/pull/59354
