### ISSUE TITLE
NPC asking for food with "Disable NPC Needs"

### ISSUE THREAD

**Issue by nik-ovchin** [CleverRaven/Cataclysm-DDA#59243]
### Describe the bug

Today my companion started asking for food and water despite I have enabled "Disable NPC Needs" mod.
I'm pretty sure I didn't see this complain previous in log.

### Steps to reproduce

Don't know what triggering it.

### Expected behavior

I expected with "Disabled NPC Needs" NPC don't ask for food and drink.

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 704a963 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
Please upload your save file

**Comment by nik-ovchin** [comment]
Companion was ordered to cut grass.
But he can't do it while main character on different z-level.
Maybe this two bugs related.
I will post save as soon as I was near comp.

**Comment by nik-ovchin** [comment]
Is it supposed with "Disable NPC needs" NPC have hunger and thirst status when I examine their stats through talking.

![image](https://user-images.githubusercontent.com/108984618/178980436-022fb1c9-c882-444d-a993-4c2639ededa8.png)

**Comment by nik-ovchin** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9111676/save.zip)

**Comment by RelMayers** [comment]
NPC will complain about lack of food with disable NPC needs mods if you have base amp with low fppd

**Comment by nik-ovchin** [comment]
Can you please decrypt "base amp with low fppd"?

**Comment by PatrikLundell** [comment]
My guess is that it's supposed to say "camp" and "food", and would to be interpreted as having a base camp food storage that's low.

However, while companions will complain when sent off on base camp missions and there is insufficient food in the base camp storage, I'm not aware of this interacting with direct companion interaction complaints about food (and I didn't have any base camp food shortage when I had these problems either).

**Comment by nik-ovchin** [comment]
There is no camp in innawood. And I don't see such complain before.
Must be some related to experimental changes in last couple days.
