### ISSUE TITLE
legend type widget

### ISSUE THREAD

**Issue by dikiy4eburator** [CleverRaven/Cataclysm-DDA#59258]
### Describe the bug

the legend type widget messes up other widgets thet are on the right side of it,
when used in columns mode with other widgets.
but it does it only when it has to show something. here some examples:

![legend_normal](https://user-images.githubusercontent.com/30246258/178960475-c18a4d4b-e2a7-45ad-b06a-78598d2af08b.png)
when it is empty, everything is OK.
but when it has something to show it looks like this.

![messed_up_legend](https://user-images.githubusercontent.com/30246258/178960836-604af029-4dce-482a-bb1d-c237a65c9778.png)

and this applays to all legend widgets i tested so far.
"bp_status_legend_text",  "compass_legend_text" and "ma_buff_legend"

### Steps to reproduce

- make a layout widget with columns arrangement.
- combine any legend widget with any other widget
  so that the legend widget is on the left side.
- give the legend widget to show something

### Expected behavior

the widget should not affect the layout and other widgets, and consider
the width parameter given to it.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 4484667 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Wlad's Modifications [wlads_modicikations],
    No Rail Stations [No_Rail_Stations],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by vetall812** [comment]
This is currently expected behavior, "width" property doesn't work like "i want this widget be X width no matter what". Some widgets ignore this property, some consider it as "not less than"...
Probably #58684 relates to it.
