### ISSUE TITLE
Being able to repair many materials disrupts UI

### ISSUE THREAD

**Issue by SolventMercury** [CleverRaven/Cataclysm-DDA#59253]
### Describe the bug

In menus listing the option to repair materials, being able to repair a large number of different materials causes the window to be needlessly large. This can also cause certain pieces of the UI to be obscured, because there is insufficient room for them.

### Steps to reproduce

1. Add arc welder to inventory
2. Open actions menu (% by default)

### Expected behavior

This is technically correct behavior, but there should really be some kind of maximum length, and anything after that should be replaced by ellipses.

### Screenshots

![image](https://user-images.githubusercontent.com/87032239/178888575-6a638698-866d-4a7a-8c3c-375311d9afaa.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 10a4412 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 1159e88 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Qrox** [comment]
The material list can be moved to `uilist` description to reduce UI size.
