### ISSUE TITLE
My game can't stop crashing when i try to sleep.

### ISSUE THREAD

**Issue by Brazilsurvivor** [CleverRaven/Cataclysm-DDA#59255]
### Describe the bug

When i try to sleep, after some time, my game crashes.

### Steps to reproduce

1 - Try to sleep.

### Expected behavior

My game doesn't crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 1d66199 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Generic Guns [generic_guns],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9108599/config.zip)
[Belmont_no deadly.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9108607/Belmont_no.deadly.zip)

**Comment by andrei8l** [comment]
/confirmed more unsafe derefrencing of `get_wielded_item()` https://github.com/CleverRaven/Cataclysm-DDA/blob/e13f28271cb6b3889ad94f425bf6712eb1c1455f/src/suffer.cpp#L1343

**Comment by mqrause** [comment]
Damn, that's such an obvious case I don't even know how I missed it.
