### ISSUE TITLE
Obscure enemies depending on light level/distance

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59266]
### Is your feature request related to a problem? Please describe.

I believe detection of hostiles/people at night is currently a bit rough and can be improved upon.

### Solution you would like.

Add state/sprites for creatures at night that are indiscernible.  This provides an intermediate state between seen and unseen. 3 forms of shadowy visage.

- A _small figure_ (for small creatures)
- A _figure_ (for dog - human sized creatures)
- A _large figure_ (for hulks and other monstrosities)

Simplest solution could involve 2 radiuses around the PC and running a check when at night or in a basement. If outside the first distance, an enemy will be seen as the appropriate _figure_. If outside the second distance, enemy will remain unseen.

A better solution could include calculating a visibility score for enemies within general sight radius and line of sight. This score would consider distance, light, and possibly other factors. It will determine if the creature is fully visible, obscured, or unseen.

Visibility can be affected by the perception stat. Possibly other factors like focus or pain.

This could also be used as an effect from certain conditions or drugs. Instead of just hallucination, we add an effect obscuring creatures identities for a time, making them indistinguishable.

 It could even be a (very) dangerous trait - Prosopagnosia. Inability to recognize faces. this could apply to all creatures or just to human/zombie creatures with a stronger version of the trait applying to all creatures.

### Describe alternatives you have considered.

A figure that becomes recognized should probably remain identifiable for an amount of time if it gets far enough to be obscured. However, if it loses line of sight and returns it would be obscured again.

Plenty of other more advanced situations and calculations can be considered if this is implemented someday.

### Additional context

Not sure how feasible this is on the programming/code side or if it would be worth adding before 0.G if desired.

**Comment by ANickelN** [comment]
Why is this not planned?  This seems like an interesting feature.

**Comment by Cimanyd0** [comment]
@kevingranade did you intend to close 4 different issues by deleted user(s) as not planned? #59074 #59102 #59288

**Comment by kevingranade** [comment]
Yes, these are all fairly poorly supported with details, and as the original author is gone now, that's not going to improve, so it's better to start from scratch than use these as a base for a feature.
