### ISSUE TITLE
Add reading lamp

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#59265]
### Is your feature request related to a problem? Please describe.

Reading is only optimal in daytime, or if a flashlight is activated. A light source dedicated to this purpose is a very real thing and would be useful in game.

### Solution you would like.

Add a battery operated reading lamp. Preferably this would come in two options. I'm not sure amazon links are a good idea here but the lamps are widely available and easily referenced.

1. A desk suitable reading lamp. Useful to have sitting at your base near a stack of books.
- Regular batteries, lasts a decent amount.
- Lightweight but takes up some space.
- Illuminates small amount of space.
- Lasts maybe 6-8 hrs.

2. A clip-on reading lamp. Useful to carry with you for reading on the go.
- Very portable. maybe an oz or two. .3 L or less likely.
- Provides minimal light (like 1 tile maybe)
- Likely use light batteries. R longer than a flashlight. (one example provides 70 hours at minimum brightness; 7 hrs at max) 
- Would not alert enemies in most cases.

### Describe alternatives you have considered.

Allow switching between brightness levels (on desk reading lamp at least) to go between solely reading usage to lighting up the room. Could be included in the activate function on the item. Would affect brightness as well as battery consumption. This would be highly useful with regular flashlights as well, perhaps ill start a suggestion eventually. Would allow us to have multiple flashlights with different capabilities. 

### Additional context

thoughts?

**Comment by Hirmuolio** [comment]
It already exists: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/tool/lighting.json#L605

It consumes 1/10 of normal flashlight power.
