### ISSUE TITLE
Green/Red colors for item comparison display wrong

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#59264]
### Describe the bug

When comparing two similar items with different stats green should indicate a superior value and converse for red. This is not the case with all stats, however. 

This appears to apply to damage per stamina, price, and warmth in the case of clothes.

### Steps to reproduce

Compare two items and see the colors displayed incorrectly. See attached photos.

### Expected behavior

The same rule should apply to all elements for the items compared.

### Screenshots

![Screenshot_20220714-115835_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/92204064/179026304-8bfa4f78-8d63-4f0b-8994-25f1187f0b51.jpg)
![Screenshot_20220714-120344_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/92204064/179026731-29a7a401-1cc1-4102-aba9-b56085055f26.jpg)
![Screenshot_20220714-120359_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/92204064/179026739-e3b6dca8-92d5-4b6b-8825-450759eb83ee.jpg)

### Versions and configuration
- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-S205DL; Release: 10; Incremental: S205DLUDU5BTE7; 
- Game Version: ca79ddd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by ZeroInternalReflection** [comment]
For anyone looking to fix this, #50288 is largely the same issue, but with a different collection of comparison examples.

**Comment by hexagonrecursion** [comment]
/confirmed

+ damage per stamina is colored **correctly** (I compared cudgel vs quarterstaff)
+ price is colored **incorrecty** - higher is red, lower is green
+ warmth is colored incorrectly (I compared fur gloves vs leather gloves and both sides were red)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: d06b4a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
