### ISSUE TITLE
Guns have two shoulder straps attached

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#59262]
### Describe the bug

Guns found in the world, which would ordinarily have a single shoulder strap attached to them, now have two attached.

### Steps to reproduce

1. Spawn a large amount of zombie soldiers.
2. Kill them all.
3. Sift through the loot and observe that some guns have double shoulder straps.

### Expected behavior

Guns have only one shoulder strap.

### Screenshots

![ar](https://user-images.githubusercontent.com/45204409/179016336-17652219-f6e5-416b-a82d-3739219556a2.JPG)
![strap](https://user-images.githubusercontent.com/45204409/179016350-290c2261-b196-4178-ab84-5ecb03c39ac3.JPG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 4484667 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

No additional context, it's a fairly minor bug.

**Comment by anoobindisguise** [comment]
I've seen the same thing. Haven't checked if it's 100% of guns with shoulder straps though.

**Comment by Bulletfang** [comment]
It's not 100%, but I can't tell if there's a condition or if it's random.
