### ISSUE TITLE
Monster groups in monster groups are not evaluated correctly

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#59276]
### Describe the bug

See #59215. Copying my comment in here:

I am understanding it currently works like this:

```json
{ "monster": "mon_cat", "weight": 5 },
{ "monster": "mon_something else", "weight": 5 },
```

The above works as expected but however this does not:

```json
{ "group": "GROUP_STRAY_CATS", "weight": 5 },
{ "monster": "mon_something_else", "weight": 5 },
```

Because it basically turns into:

```json
{ "monster": "mon_cat", "weight": 50 },
{ "monster": "mon_cat_kitten", "weight": 5 },
{ "monster": "mon_cat_calico", "weight": 50 },
{ "monster": "mon_cat_calico_kitten", "weight": 5 },
...
{ "monster": "mon_something else", "weight": 5 },
```

This is my guess at least, seeing at how the spawns reacted to me fiddling with the `GROUP_FOREST` spawn locally to resolve the feline world domination problem. Currently it looks like it includes the group as is, inserting all the entries of the group with their original weights intact instead of considering the group as a whole. So in our example, there is a 50/50 chance of the monster being a cat (like intended), but with the `group` being used, the chance of a monster being any cat is nigh 99% since all the entries are inserted into the array.

The intended behavior is that the chance the monster is any cat is still 50/50 and the chance of said cat being e.g a calico kitten is a different, irrelevant chance which is internal to said monstergroup. The monstergroups weights should affect only itself.

I hope I explained that right since I am a total noob.

### Steps to reproduce

See above.

### Expected behavior

The weights inside of a monster group stay inside of it and entries do not get inserted into the parent group.

### Versions and configuration

git

**Comment by Venera3** [comment]
See #59174 for a related problem. Another slight problem with nested mongroups is that default monsters are ignored (so a monstergroup needs at least one proper entry to spawn anything).

I'm sorry about pointing you at something I didn't try myself causing a slight catocalypse, by the way.

**Comment by NetSysFire** [comment]
>I'm sorry about pointing you at something I didn't try myself causing a slight catocalypse, by the way.

No worries. It turned out to be a quite amusing dwarffortress-style bug.
