### ISSUE TITLE
Unify color scale for HP bars and body graphs

### ISSUE THREAD

**Issue by mlange-42** [CleverRaven/Cataclysm-DDA#59274]
### Is your feature request related to a problem? Please describe.

Currently, HP bars in the sidebar use a different color scale than body_graph HP widgets. Makes the UI unintuitive.

### Solution you would like.

Use the same color scale for HP bars and body graphs.

A problem could be that the dark green for full HP might be too dark for the body graph.

### Describe alternatives you have considered.

Do not unify.

### Additional context

Example:

![grafik](https://user-images.githubusercontent.com/44003176/179100312-d414840d-a658-4573-bdc6-f5cdc0dc16da.png)

Would be much clearer with unified color scale.

**Comment by Inglonias** [comment]
Changing the color scale for the HP graphs is easy - It should be a single line of JSON. Specifically, line ```
9 of data/json/ui/hp.json.

This is the code that tells the body graph what color to be:

```
if( cur_hp_pcnt < 0.25f ) {
        return { bgp.sym, c_red };
    } else if( cur_hp_pcnt < 0.5f ) {
        return { bgp.sym, c_light_red };
    } else if( cur_hp_pcnt < 0.75f ) {
        return { bgp.sym, c_yellow };
    }
    return { bgp.sym, c_light_green };
