### ISSUE TITLE
Bronze Horse Armor duplicate fabrication requirement

### ISSUE THREAD

**Issue by Travia21** [CleverRaven/Cataclysm-DDA#59289]
### Describe the bug

The Bronze Horse Armor craft's primary _and_ secondary skill requirements are Fabrication 5.

### Steps to reproduce

1. Look at the Bronze Horse Armor crafting recipe.

### Expected behavior

The secondary skill should be tailoring 3, in line with Iron Horse Armor

### Screenshots

![image](https://user-images.githubusercontent.com/3219079/179242974-533e187c-9a2f-4c9c-8027-ed1c514ec65e.png)

### Versions and configuration

 - OS: Windows 10
 - Game version: O.F-93a5ad9
 - Graphics version: Tiles & Sound
 - Ingame language: English
 - Mods loaded: DDA, No Fungal Growth, No NPC Needs, Bionic Professions

### Additional context

My fab skill is currently 4, but I have the recipe from "Sewing Techniques for Designers" and "Clothing Designer's Portfolio"

**Comment by merrygin** [comment]
Yeah, can confirm. The horse armor copys from the bronze cuirass which is already fab difficulty 5 and then adds the "skills_required" fab 5.

**Comment by merrygin** [comment]
Seems like a number of horse armors have a bit inconsistent req's. possibly someone could have look over all of them and make them consistent.
