### ISSUE TITLE
Can't create character.

### ISSUE THREAD

**Issue by NetKg** [CleverRaven/Cataclysm-DDA#59286]
### Describe the bug

This is on the latest experimental version for android. Whenever i try to make a character, the games throws me back to main menu. I tried this with a few mods, multiple mods, and with no mods at all and it still had the same results.

### Steps to reproduce

.

### Expected behavior

.

### Versions and configuration

.

**Comment by H4M5TER** [comment]
confirmed on windows 2022-07-16-0737

**Comment by NetSysFire** [comment]
First of all, the "Steps to reproduce" and "Version and configuration" input fields are mandatory for a reason.

Launchers are also unsupported and you need to report the bug to the catapult authors instead.

**Comment by kevingranade** [comment]
Closing as unreproduceable.
