### ISSUE TITLE
Arithmetical error crash when siphoning fuel

### ISSUE THREAD

**Issue by Basher6079** [CleverRaven/Cataclysm-DDA#59282]
### Describe the bug

I have a 200L barrel at my feet and I'm siphoning fuel from helicopters. When I siphon the last tank then return to the vehicle menu the game crashes. It is possible to get around this bug by saving after the final siphon then restarting the game.

### Steps to reproduce

My save, next to the helicopter I am trying to drain.
[Hunts Point.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9117752/Hunts.Point.zip)

Siphon fuel into the barrel until the helicopter is empty.
Return to the helicopter's menu.
The game then crashes (unless it decides not to; I've had it crash 6/8 times).

### Expected behavior

I expect that the vehicle's fuel tanks would drain, my tank would fill, and the game wouldn't crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 20872a7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries]
]

### Additional context

Here is the crash report:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 20872a7
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

  #0
    (dbghelp: @0x7ff724330748[cataclysm-tiles.exe+0x220748]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x140220748),
    (libbacktrace: 0x140220748    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff72431a091[cataclysm-tiles.exe+0x20a091]), 
    (libbacktrace: log_crash+0x1d2@0x14020a091),
    (libbacktrace: 0x14020a091    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff72431a2bf[cataclysm-tiles.exe+0x20a2bf]), 
    (libbacktrace: signal_handler+0x52@0x14020a2bf),
    (libbacktrace: 0x14020a2bf    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff724c13082[cataclysm-tiles.exe+0xb03082]), 
    (libbacktrace: gnu_exception_handler+0x122@0x140b03082),
    (libbacktrace: 0x140b03082    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:270    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffa54347ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffa562b209f[ntdll.dll+0xa209f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ffa56261454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffa562b0bce[ntdll.dll+0xa0bce]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff724b081f9[cataclysm-tiles.exe+0x9f81f9]), 
    (libbacktrace: vehicle::print_fuel_indicator(catacurses::window const&, point const&, string_id<itype> const&, std::map<string_id<itype>, float, std::less<string_id<itype> >, std::allocator<std::pair<string_id<itype> const, float> > >, bool, bool)+0x1c5@0x1409f81f9),
    (libbacktrace: 0x1409f81f9    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff724b08add[cataclysm-tiles.exe+0x9f8add]), 
    (libbacktrace: vehicle::print_fuel_indicators(catacurses::window const&, point const&, int, bool, bool, bool, bool)+0x1f3@0x1409f8add),
    (libbacktrace: 0x1409f8add    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff724ab86f8[cataclysm-tiles.exe+0x9a86f8]), 
    (libbacktrace: veh_interact::display_stats() const+0x1d9c@0x1409a86f8),
    (libbacktrace: 0x1409a86f8    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff724ac520f[cataclysm-tiles.exe+0x9b520f]), 
    (libbacktrace: veh_interact::create_or_get_ui_adaptor()::{lambda(ui_adaptor const&)#2}::operator()(ui_adaptor const&) const [clone .constprop.0]+0x3b@0x1409b520f),
    (libbacktrace: 0x1409b520f    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff724a9fdea[cataclysm-tiles.exe+0x98fdea]), 
    (libbacktrace: ui_adaptor::redraw_invalidated()+0x1e8@0x14098fdea),
    (libbacktrace: 0x14098fdea    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff724ac8504[cataclysm-tiles.exe+0x9b8504]), 
    (libbacktrace: veh_interact::do_main_loop()+0xb0@0x1409b8504),
    (libbacktrace: 0x1409b8504    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff724ac8ce1[cataclysm-tiles.exe+0x9b8ce1]), 
    (libbacktrace: veh_interact::run(vehicle&, point const&)+0x29@0x1409b8ce1),
    (libbacktrace: 0x1409b8ce1    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff724423b13[cataclysm-tiles.exe+0x313b13]), 
    (libbacktrace: game::exam_vehicle(vehicle&, point const&)+0xa3@0x140313b13),
    (libbacktrace: 0x140313b13    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff724b332a3[cataclysm-tiles.exe+0xa232a3]), 
    (libbacktrace: vehicle::interact_with(vpart_position const&, bool)+0x22a1@0x140a232a3),
    (libbacktrace: 0x140a232a3    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x7ff72444bf2e[cataclysm-tiles.exe+0x33bf2e]), 
    (libbacktrace: game::examine(tripoint const&, bool)+0x414@0x14033bf2e),
    (libbacktrace: 0x14033bf2e    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x7ff72444c862[cataclysm-tiles.exe+0x33c862]), 
    (libbacktrace: game::examine(bool)+0x2f4@0x14033c862),
    (libbacktrace: 0x14033c862    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x7ff72447c90e[cataclysm-tiles.exe+0x36c90e]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x1128@0x14036c90e),
    (libbacktrace: 0x14036c90e    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x7ff724481972[cataclysm-tiles.exe+0x371972]), 
    (libbacktrace: game::handle_action()+0xafa@0x140371972),
    (libbacktrace: 0x140371972    [unknown src]:0    [unknown func]),
  #21
    (dbghelp: @0x7ff72437b568[cataclysm-tiles.exe+0x26b568]), 
    (libbacktrace: do_turn()+0x540@0x14026b568),
    (libbacktrace: 0x14026b568    [unknown src]:0    [unknown func]),
  #22
    (dbghelp: @0x7ff72565d9bd[cataclysm-tiles.exe+0x154d9bd]), 
    (libbacktrace: main+0x16e8@0x14154d9bd),
    (libbacktrace: 0x14154d9bd    [unknown src]:0    [unknown func]),
  #23
    (dbghelp: @0x7ff7241113c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    (libbacktrace: 0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup),
  #24
    (dbghelp: @0x7ff7241114d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    (libbacktrace: 0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup),
  #25
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffa55707034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #26
    (dbghelp: RtlUserThreadStart+0x21@0x7ffa56262651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by natsirt721** [comment]
[This line](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle_display.cpp#L438) is the culprit. Somehow its trying to print the fuel gauge for JP8 eve though there is none remaining and no capacity, and its trying to divide by zero. I tested this on the same build with a different vehicle (luxury RV) and it did not crash. You can see this by turning on debug mode; it prints the fraction unresolved (ie 0/0 JP8) instead of dividing and you don't get the crash.

**Comment by Basher6079** [comment]
The issue seems to be isolated to existing Apaches. Spawning in new Apaches doesn't trigger the crash but draining the ones on the flight deck also causes the problem. Also, the Ospreys aren't giving me trouble.

**Comment by natsirt721** [comment]
It looks like there is a fake part somewhere that can hold JP8 that is causing the issue. The `get_printable_fuel_types` method is iterating over the `parts` master list and including the fake part, and includes JP8 as a fuel. However, the `get_capacity` method uses `get_all_parts()` which presumably filters out fake parts - hence why that can get a capacity of 0.

The fix is either to change the `get_printable_fuel_types` loop to check for fake parts, or change the loop to use `get_all_parts()` instead of `parts`. I'm not sure what the preferred solution is; I'd assume the latter?
