### ISSUE TITLE
Obsolete the consistency check for 'leads_to' mutations.

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#59299]
### Is your feature request related to a problem? Please describe.

I made a PR that removes the prereq `EYEBULGE` from the `MEMBRANE`-mutation, but I intended to leave the `"leads_to": [ "MEMBRANE" ],` since I think, it's a good thing, that `leads_to` is a means to modify the weight of the roll towards the next mutation.

However: After removing `EYEBULGE` from lizard mutation it gave me this error:
```
 DEBUG    : mutation EYEBULGE lacks category LIZARD present in additive mutation MEMBRANE

 FUNCTION : check_consistency
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mutation_data.cpp
 LINE     : 731
 VERSION  : 8157ece
```

### Solution you would like.

I suggest to obsolete the consistency check for `leads_to` as it adds more flexibilty upon designing new mutations and modifying existing ones.

**Comment by actually-a-cat** [comment]
Additional context: since #58803, it's not a problem if there is an upgrade that is not in the same category, because it won't be picked anyway. It should be sufficient to check if at least one category matches, instead of requiring that all match.

Disclaimer: haven't had a chance to test the above yet.

**Comment by Stadler76** [comment]
Untested, but would this fix it:
```diff
diff --git a/src/mutation_data.cpp b/src/mutation_data.cpp
index 526a8aacf9..c66217291c 100644
--- a/src/mutation_data.cpp
+++ b/src/mutation_data.cpp
@@ -725,11 +725,13 @@ void mutation_branch::check_consistency()
         }
         for( const trait_id &addition : mdata.additions ) {
             const mutation_branch &adata = addition.obj();
+            bool found = false;
             for( const mutation_category_id &cat : adata.category ) {
-                if( std::find( mdata.category.begin(), mdata.category.end(), cat ) == mdata.category.end() ) {
-                    debugmsg( "mutation %s lacks category %s present in additive mutation %s", mid.c_str(), cat.c_str(),
-                              addition.c_str() );
-                }
+                found = found ||
+                        std::find( mdata.category.begin(), mdata.category.end(), cat ) != mdata.category.end();
+            }
+            if ( !found ) {
+                debugmsg( "categories in mutation %s don't match any category present in additive mutation %s", mid.c_str(), addition.c_str() );
             }
         }
 
```

**Comment by Stadler76** [comment]
I just got another idea that might help with designing mutations:
The field "comes_from" as a 'soft prereq'.
For example: If you have two mutations of the same category that aren't linked and you want to make sure, that a player or NPC mutated in the intended order without making it a prereq for other categories.
To give one example:
You want to make sure for the lizard category that the player/NPC gains `FANGS` after gaining `MUZZLE_LONG` you could simply add
```json
    "comes_from": [ "MUZZLE_LONG" ],
```
to the `FANGS`-mutation without making it a prereq for other categories.
