### ISSUE TITLE
Blood Analysis ability to check vitamin and health level

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#59291]
### Is your feature request related to a problem? Please describe.

There is no way without debug menu to check you vitamin and health lvl (health mean not your bodyparts, I mean health of your organism, which decreasing from junk food and other things) 
In reality we can check all your vitamins in a laboratory way, but in game you cannot do it. No matter, will you use autodock, stationary blood analyzer or cbm variant
And also in realyty by blood analysis we can understand, how good is health of organizm

### Solution you would like.

Can you add to autodock, stationary blood analyzer and cbm Blood Analysis ability to check character health level, his vitamins, toxins and etc?

**Comment by kevingranade** [comment]
Helping stalebot catch up.
Checking vitamin levels would be fine but overall health is not something that's readily apparent from a couple of lab tests.
Feel free to implement this but I'm closing the issue.
