### ISSUE TITLE
Leaves and Twigs do not sort into Fire/Wood Zones from Unsorted

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#59294]
### Describe the bug

Minor issue. Pile of Leaves and Twigs found in scavenging do not sort from Unsorted zones into Firewood nor Wood zones when using Zone Manager and Sort features. 

Guessing that these items are not flagged as either material esp if they are not flagged to be used in crafting at all. 

### Steps to reproduce

1. Create zones via Zone Manager for Firewood, Wood and Unsorted. 
2. Place problem items in Unsorted Zone.
3. Use the s(O)rt menu to move items into the (Fire)Wood zones. 
4. Items do not move.

### Expected behavior

Items would move to either zone for auto-usage in burning/fireplaces.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 1d66199 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by NetSysFire** [comment]
Not specific to Innawood. I'll look into this since I am the one who added these items.
