### ISSUE TITLE
Screen Flickering In-Game

### ISSUE THREAD

**Issue by Verticalphase** [CleverRaven/Cataclysm-DDA#59306]
### Describe the bug

When I am loaded into a world the screen flickers (but the menus don't seem to flicker), when I move my mouse around it stops until I hold my mouse still again. This only happens sometimes, but when it does happen it persists through multiple reloading and quitting the whole game. It decides to stop randomly it seems, but never during the game, it always stops after a random amount of quitting and reloading. 

### Steps to reproduce

1. Start a new game
2. It should flicker as soon as you load in (easier to tell if you go outside and have a wide view.)
3. Not sure how to accurately reproduce this, it seems to happen randomly. 

### Expected behavior

I expected that my game hold a steady image. 

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental 2022-07-15-1818 [link](https://github.com/CleverRaven/Cataclysm-DDA/commit/8157ece0f94417c2454e31dcf80b56be5b417a42)
- Graphics Version: Tiles (Ultica from base game selections)
- Ingame language: English
- Mods Loaded: Dark Days Ahead, Disable NPC Needs, No Fungal Growth, Alternative Map Key

### Additional context

I tried recording the bug while it was happening but you can't see it on the video, you're only able to see it in the game. 
[Save File](https://www.dropbox.com/sh/s9uxkfgsc8iaisx/AADUJP0fu2zFI0FrcO3E1Pf2a?dl=0)

**Comment by Qrox** [comment]
> I tried recording the bug while it was happening but you can't see it on the video, you're only able to see it in the game.

Sounds like some problem with the driver or hardware to me. Could you switch the renderer in the settings and see if still flickers?

**Comment by ANickelN** [comment]
I have this happen when playing in Maximized mode, switching to Borderless fixes it.

**Comment by Verticalphase** [comment]
Thank you guys for the support! So I switched my renderer from “direct3d11” to “direct3d” and I’ve been playing for a couple hours without any flickering. And I was already on Windowed Borderless when the flickering began sadly. I am currently playing on a widescreen (3440x1440, 120hz) monitor, could that have had something to do with the renderer being the cause?
