### ISSUE TITLE
Trailer Parks doesn't have Roofs

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#59314]
### Describe the bug

Trailer parks does not have roofs on them.

### Steps to reproduce

1. Go to a trailer park
2. Look at the roofless trailers

### Expected behavior

It has roofs

### Screenshots

![Screenshot_20220716-191425](https://user-images.githubusercontent.com/78019001/179354566-39e2905d-9bb9-405b-95e3-f3cea2482274.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 93a5ad9 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blu [blu],
    No Rail Stations [No_Rail_Stations],
    Crow's Hairstles 2: Natural [hairmod2_natural],
    Crow's Hairstles 2: Ears and Tails [hairmod2_earsAndTails],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

### Additional context

I noticed trailer parks loots are sparse. Not sure if that's the intention or not.

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/179357182-a6b306d0-3f3c-4119-be2e-0b522ee3b2b8.png)

Can not reproduce. Make sure none of the mods you are using causes this.

**Comment by gettingusedto** [comment]
Made a new world with the default modlist and it does have roofs. Time to find out which mod that does it.

Thank you and sorry for the inconvenience.
