### ISSUE TITLE
More meta-progression and achievement enhancements

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#59326]
### Is your feature request related to a problem? Please describe.

Right now, the meta-progression system is used for four scenarios in the base game, which makes it more annoying than useful. If we have this system available to us, we may as well put it to good use.

### Solution you would like.

In my perfect vision of the future, Evacuee would be the only scenario available to a brand-new player. Many of the other scenarios would be fairly easy to unlock, but not necessarily all of them. Most of the more mundane starts would be unlocked by the achievement you get for surviving 24 hours. Some of the harder starts would be unlocked by surviving for a week. Finally, specialized starts would be unlocked when you visited their associated locations.

We would also need to add more achievement infrastructure. From the list I have generated below, we would need the following:
* An achievement for surviving a portal storm
* The ability to trigger an achievement with any member of a list of overmap types. For instance, if we wanted the aircraft carrier start to be gated behind the player visiting a carrier first, we need to be able to check if they boarded from any tile, not just one. Ditto for military bases. We can probably get away without this for the TCL achievement, since that special only has one normal entrance, but that's about it.

### Additional context

I've drawn up a hypothetical list of how I would lock off various starting scenarios. Anything in parentheses is the achievement that, when achieved, unlocks the scenario. Any achievement that begins with `!!` does not yet exist in the game. Many of those achievements are currently either prohibitively difficult to implement, or flat-out impossible without more C++ support.

```
Evacuee                         (Unlocked at the start. No achievements)
Challenge - Fungal Infection    (Fungicide)
Challenge - Really Bad Day      (Thank god it's Friday)
Challenge - Medieval Peasant    (Thank god it's Friday)
Challenge - Abandoned           (!!Visited a hospital)
Challenge - Mi-Go Camp          (Silence your Nightmares)
Challenge - Portal Dependent    (!!Survived a storm)
Challenge - TCL Concourse       (!!Visited TCL)
Challenge - Island Prison       (!!Visited an island prison)
Helicopter Crash                (Thank god it's Friday)
Infected                        (Thank god it's Friday)
Prison                          (Thank god it's Friday)
Stronger Portal Storms          (!!Survived a portal storm)
Frequent Portal Storms          (!!Survived a portal storm)
Sheltered                       (A time to every purpose under heaven)
Splintering Reality             (!!Survived a portal storm)
Surrounded                      (Centinel)
Challenge - Hunted              (Thank god it's Friday)
Burning Building                (Thank god it's Friday)
(un)living History              (!!Visited a bastion fort)
Challenge - Bordered            (Thank god it's Friday)
Crazy Party                     (The first day of the rest of their unlives)
Car Crash                       (The first day of the rest of their unlives)
Squatter                        (The first day of the rest of their unlives)
Large Building                  (Centinel)
Mansion Escape                  (Centinel)
Missed                          (The first day of the rest of their unlives)
The Mascot Rises                (The first day of the rest of their unlives)
Wilderness                      (The first day of the rest of their unlives)
Safe Place                      (The last homely house)
Bottom of a Mine                (!!Got to the bottom of a mine)
Experiment                      (Homo Evolutis)
The Last Delivery               (The first day of the rest of their unlives)
Last Flight                     (The first day of the rest of their unlives)
High Tech, Low Life             (Spiritus quidem promptus; caro vero infirma.)
Overrun                         (!!Visited a military base)
CVN Sailor                      (!!Visited an aircraft carrier)
```

**Comment by jbytheway** [comment]
I think three new features in the achievements infrastructure would suffice for these achievements:
* A `value_constraint` that's "is one of" rather than just "equals".  That would allow for e.g. checking for multiple `oter_type_id`s.
* A way to get the overmap special id for the special that the player is currently in.  That isn't strictly necessary given the above feature, but it would simplify a lot of cases.
* A new event for surviving a portal storm.

Each of these should be pretty easy to add.

**Comment by Inglonias** [comment]
Another possible approach I thought of is hooking the EOC system to the event system - Basically, a new type of event that can be directly messed with by EOCs.

**Comment by Zireael07** [comment]
I think this sorta ties into the new player experience issue/planned overhaul thingy?

**Comment by jbytheway** [comment]
#59356 and #59363 will allow for all of these except the portal storm one.

**Comment by Inglonias** [comment]
#59423 allows for the portal storm one, and more. Any dialogue variable change can be watched for.

**Comment by Inglonias** [comment]
@I-am-Erk linked me to this document where they have been brainstorming ideas in this space: https://docs.google.com/spreadsheets/d/1hRlquzrOVVg3cPHlx1KJAXYGf1CVeOZ-NwtF7-9oWKU/edit#gid=0

**Comment by I-am-Erk** [comment]
So carrying over a summary of what I said on discord
- We should make sure there are a few different options out of the gate for new players beyond evacuee/survivor. I think Squatter and Safe Place are good possibilities.
- Be careful about tying too many things to "visit this place". Generally I think that should be for places that are plot critical - factions and labs, mainly. After that, the different start scenarios represent ways of trying things you might not have had a chance to find randomly, so we should avoid triggering them by having actually done that thing yourself.
- A majority of unlocks should still be unlocked by TGIF, First Day, Decamate, and Centinel. Probably about 75% of stuff should be unlocked if you've done that stuff and demonstrated a basic proficiency with the game

**Comment by Inglonias** [comment]
> A majority of unlocks should still be unlocked by TGIF, First Day, Decamate, and Centinel. Probably about 75% of stuff should be unlocked if you've done that stuff and demonstrated a basic proficiency with the game

This is the only point I disagree with, but not because I think these unlocks should be more difficult. I just want more variety. The greater variety of activities we can use, the better. The rule of thumb I want to use is that if a player is capable of getting the four achievements you mentioned, they should have picked up most of the unlocks you're talking about, but not necessarily all of them, and finding the rest shouldn't be prohibitively difficult.

For example, if we locked the police professions behind killing a zombie cop instead of getting 10 kills or surviving a day, I don't think that's too big an ask. Zombie cops are not especially difficult to kill and are fairly common. Other professions would be a bit trickier. Locking the fancy military starts behind killing a zombie specops or bio-operator might be a bad idea.

**Comment by I-am-Erk** [comment]
I don't mind having other flavourful easy unlocks, so long as a majority of stuff is going to be available quickly and easily through regular play, and also a small amount of stuff is tricky or even extremely hard to unlock. Later on we should look at adding some really weird or powerful starts that have even tougher unlock options, but that should be after stable.

**Comment by I-am-Erk** [comment]
Oh hey food for thought. We should have an achievement unlocked for completing the tutorial, and it could unlock some fairly trivial variant profession or something. Or if we have the option to have multiple unlock options (ie achievement a *or* b can unlock this scenario), completion of tutorial could be counted as equivalent to surviving one day

**Comment by Inglonias** [comment]
The ability to have a boolean "or" for achievement unlock requirements is not something we support right now. Ditto for unlocking scenarios and professions. That said, this can be accomplished by making sleep the last part of the tutorial.

**Comment by kevingranade** [comment]
The requested infrastructure has been added. 
Feed free to add the achievements as outlined,  but no need to track them here.
