### ISSUE TITLE
Introduce non collision "vehicle parts"

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59322]
### Is your feature request related to a problem? Please describe.

I'd like to see a way to construct appliances that don't impede either character movement or vehicle movement. The logic behind it would be that they'd either be mounted from a ceiling, or mounted in/on the floor, or the wall.

Some potential use cases:
- "Normal" lamps (as opposed to the current standing ones).
- Explicit electric cabling (I think there's a PR for that currently. May be in draft mode)
- Cooling systems that dump cool air from above (that may or may not be "reversible" to provide some heating in winter).

### Solution you would like.

The introduction of a new flag, e.g. "NO_COLLISION". I would guess it would need to have support in the code in the form of a way to allow for and display multiple vehicles in the same tile.

### Describe alternatives you have considered.

A flag might not turn out to be the best option...

### Additional context

This might actually allow for rugs that won't replace what's underneath for any terrain, as well as posters/paintings/paint on any walls (but that really ought to include support for which side of the wall it's mounted at).

**Comment by chrispikula** [comment]
Just to be clear, this is for things outside of a vehicle, yes?

**Comment by PatrikLundell** [comment]
My intention for this is for use by appliances, not actual vehicles.

I guess you could have non collision wing mirrors to sort of simulate that they don't actually take up the whole tile, but then those would be invulnerable to direct damage and you could end up with more cases of vehicles split into multiple parts, which is bad. Any further work in this direction for actual vehicles would need to consider all such resulting messiness before it would be implemented (or at least before it was merged...).

I could think of an extension of it (i.e. a new flag) being used internally in/on a vehicle for storage space for carried vehicles, but that would require a whole other level of support, as you'd need a way to first drive it onto the carrying vehicle lowering (extending the vehicle: fail on obstacles) non ramp collision tiles that would be exempt from collision only when activated and that would activate the non collision property of the carrying tiles with it, and then fasten the carried vehicle to merge it which would also automatically disable (raise) the ramp (which ought to fail if any vehicle is occupying any ramp tile). I think that would be a fair bit of work to implement and a lot of testing to deal with corner cases (like driving around with the ramp down shouldn't allow you to back up through things).

In the suggested form, the flag would probably do nothing inside of a vehicle as it would exempt that part from collision detection, not the rest of the parts on that tile. In an interior tile it wouldn't protect the part from force transfer, for instance, and it probably shouldn't exempt it from direct damage if some other part on that tile triggers collision calculations either.

**Comment by chrispikula** [comment]
I was wondering how this would be different from BOARDABLE (for larger stuff), or AISLE (for smaller stuff), or just not having the OBSTACLE tag when the location is "center".

**Comment by PatrikLundell** [comment]
"AISLE" allows unimpeded passage through the tile on foot, but vehicles collide with it. For normal indoors cases you'll want to be able to pull things like shopping trolleys and welding carts with you, while a garage usage would allow you to mount lamps in the ceiling and still drive vehicles for repair or dismantling in underneath them (in particular nuisance parts such as wing mirrors).

"BOARDABLE" allows the passage on foot through the tile, but at an additional movement cost. Again, it doesn't let vehicles through.

"OBSTACLE", blocks creature traffic, but like the other two, it also causes vehicle collision.

**Comment by chrispikula** [comment]
Is there a differing location for home appliances, maybe that in conjunction with the existing tags?

**Comment by PatrikLundell** [comment]
Sorry, I'm not completely sure I understand your question. If you ask whether appliances have their own set of tags, I don't believe that's the case. All the tags I've seen have been shared with vehicles except for the "APPLIANCE" tag itself.

**Comment by chrispikula** [comment]
Ah, it looks like they have `"location": "structure",`, so what about just adding logic to the AISLE/BOARDABLE tags if location = structure is found?  (Or vice-versa, I'm not sure how the c++ for vehicles is provisioned.)

**Comment by PatrikLundell** [comment]
I don't think it's a good idea to piggy-back side effects onto existing tags so the same tag behaves differently depending on the target.

**Comment by chrispikula** [comment]
Fair.
