### ISSUE TITLE
Modable hordes - e.g. for innawood herds

### ISSUE THREAD

**Issue by mlange-42** [CleverRaven/Cataclysm-DDA#59338]
### Is your feature request related to a problem? Please describe.

How about herds of animals roaming in Innawood?

### Solution you would like.

Ability to use groups other than `GROUP_ZOMBIE` for wandering hordes. Potentially, allow for multiple types of hordes for different species. Hordes of dangerous species could move towards noise, while prey species could avoid it.

**Comment by kevingranade** [comment]
A future functioning horde system would have this.
