### ISSUE TITLE
Folding a vehicle causes you to forget its position

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#59334]
### Describe the bug

Whether or not this is a "bug" is debatable. An unfolded vehicle can have its position remembered so that its position can be shown on the map screen. Folding the vehicle and then unfolding it again makes your character forget they were supposed to remember it.

### Steps to reproduce

1. Take any folding vehicle and unfold it.
2. Remember this vehicle
3. It should show up on the map
4. Fold the vehicle, then unfold it again
5. It won't show up on the map anymore

### Expected behavior

When the vehicle is folded into an item, I don't think it should be expected that your character can remember the _item's_ position. But when it's unfolded, seems reasonable for your character to start remembering the _vehicle's_ position again. This is especially useful for small vehicles like folding carts that are easy to lose track of.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 554df77 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mlange-42** [comment]
Confirmed. Annoys me too sometimes.
