### ISSUE TITLE
Damaged steel ballistic plates can be repaired with needle & thread

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#59333]
### Describe the bug

Damaged steel ballistic plates show up on the tailoring repair menu. When you select them you are able to use needle & thread to sew them back together. You can even reinforce them in this way.

This seems to be because the item is considered 50% tempered carbon steel and 50% synthetic fabric. No idea why that would be the case.

### Steps to reproduce

Take a damaged steel ballistic plate and try to repair it with a needle.

### Expected behavior

I definitely never expected my tailoring skills to get so high that it can sew steel back together.

### Screenshots

![image](https://user-images.githubusercontent.com/19356629/179372863-6e7afaaf-4253-4f66-a7a6-c5da69c0d006.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 554df77 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: d06b4a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
