### ISSUE TITLE
Odd vehicle colliding thingy

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#59331]
### Describe the bug

Being in exact position while driving around the obstacle make vehicle collide without visual touching the car

### Steps to reproduce

1. spawn transport, position it exactly like in the screenshot - being diagonal, and making an attempt to turn the car once
![image](https://user-images.githubusercontent.com/67688115/179371641-2459e77a-4b47-43d9-aa2e-011408e9c250.png)
2. drive
3. see the vehicle refuse to drive, even when visually there is no colliding

### Expected behavior

🤷‍♂️ 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: d6a1777 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Massachusetts [MA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

the reason, i think, in this fake part, that will be created in the next move, when the car will turn, but also will spawn inside the obstacle, which is impossible, therefore the game show it collide
![image](https://user-images.githubusercontent.com/67688115/179371735-a966e1b6-5d46-4d76-9b55-366ef56f5cdd.png)

**Comment by KrunkySmokin** [comment]
I did some reverting builds to try and figure out what the issue is, finding every experimental after [2022-06-08-2059](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-2059) is affected by it. This is related to issue #56143 ([Fake parts for filling vehicle gaps](https://github.com/CleverRaven/Cataclysm-DDA/pull/56143)).
