### ISSUE TITLE
Item reinforcement through repair is inconsistent & incoherent

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#59342]
### Is your feature request related to a problem? Please describe.

Tailoring modification (the practice of stuffing kevlar patches onto existing clothing) was previously jettisoned, because it was gamey and didn't really make sense within the context of a complex equipment layering system. So what's the justification for item reinforcement?

It's not coherent within the game logic. Besides a nominal material cost, it's a "free" way to add more durability to your equipment _without_ any additional encumbrance or weight. It's difficult to contemplate how this is even physically possible.

Moreover, which items can be reinforced is inconsistent. It seems like almost all clothing is reinforceable, but only _some_ welding/soldering items are reinforceable. Apparently a marshal badge is reinforceable (provided you have the required silver) but greaves aren't. What distinguishes which one?

The last issue is magnified by the fact that when you select a soldering iron or welder to repair an item, it shows you even items that are already fully-repaired. If you want to reinforce your equipment, you can only do so by trial and error, by selecting each item candidate and seeing if you'll get the error message "You cannot improve your %s any more this way."

### Solution you would like.

Get rid of reinforcement. It's gamey, doesn't make sense, and waste the player's time trying to find out which items are not reinforced.

### Describe alternatives you have considered.

Keeping reinforcement? But as mentioned above, why does it even exist?

**Comment by Drew4484** [comment]
Most common clothing IRL could easily be reinforced but not gain much other than resisting wear and tear better. Restitching a pair of jeans won't make them any more resistant to a knife.  Like with the tailoring modifications, a better solution would be to add a new recipe to reinforce an item.

**Comment by RelMayers** [comment]
It works fine right now.
