### ISSUE TITLE
Revamped fire lookout towers broken at the top if discovered before the change but visited after

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59357]
### Describe the bug

I've been to two fire lookout towers generated according to the revamped layout. Both of them seem to have the staircase broken at the top.
The images attached shows the latter one, while I believe the previous one looked the same but rotated 180 degrees.

Both of them had this weird staircase upward outside of the footprint of the tower rather than inside it, so I suspect it's a matter of it not being rotated correctly to line up with stairs on the level above that probably are aligned like the stairs further down.

Edit: The discussion below identifies the cause as something that can't easily be fixed.
The cause of the issue is that the revamped tower is one level higher than the previous one, but when you see something in the distance the game generates all the visible levels of that tile at that time, including empty air tiles above the tower. When you gets close to the tower (getting it into the reality bubble) the tower tiles get generated according to the new layout, but as the new top level is saved as an empty air tile, nothing will be generated there.

### Steps to reproduce

1. Find a new layout fire loookout tower.
2. Climb it.
3. Find that you can't climb up to the top (I saved on the previous tower and made about 5 attempts, all resulting in falling down before killing the game and restoring, expecting it never to work).
4. Note that there is probably at least one orientation that works correctly, or the problem would probably have been discovered when the PR was tested.

### Expected behavior

You can climb to the top without problems.

### Screenshots

![Screenshot (250)](https://user-images.githubusercontent.com/22739822/179403324-56d4f573-0215-49f2-99d5-62e8fc10b30d.png)
![Screenshot (251)](https://user-images.githubusercontent.com/22739822/179403413-a47a4ef7-3988-4cc5-82e8-8e0b68e896c1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: d6a1777 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms
+ JSON addition of recipes for welding consumables to workshop expansion
+ JSON addition of tallow recipe to canteen expansion (I don't want cracklins and less fat for further cooking).

### Additional context

Edit:
A lesson from this is that when reworking existing features into a new layout that includes a different number of layers than the previous version, it should probably be given a new identifier that replaces the old one everywhere, while the old one ought to be moved to a deprecated feature file so it can still be generated in existing game if discovered, but new versions of the old version won't be generated.

**Comment by a-chancey** [comment]
Hm a build from about 3 days ago had them broken, but one I built from source two days ago had newly generated ones fixed (the old ones were still broken). I'll try to confirm this today

**Comment by PatrikLundell** [comment]
I can't make sense of the game version hex number in terms of time of release, but my game version is fairly recent (yesterday?). I can return to the tower and save if you want, as it's less than 5 minutes game time from where I am currently.

Thanks for looking into it.

**Comment by anothersimulacrum** [comment]
The special was generated before the overhaul, and the overhaul added another+ z-level to the tower. So when you actually generated the mapgen for this tower, it's missing those z-levels the overhaul added.

**Comment by a-chancey** [comment]
That’s what I was assuming happened. I was trying to find the mapgen file for it though, as I want to know if the the survivor RV can still spawn there

**Comment by PatrikLundell** [comment]
Thanks for the investigation and explanation. I hadn't realized generating something seen in a distance had to generate the levels above ground as well, but upon explanation it's obvious, as those levels are seen as well.

This means there is a transition issue I don't think is going to be fixed. Should we retain this and have me change the title (and description) to indicate this, as I'd suspect it will be reported again?

The lower levels seem to generate as intended, and both towers I've visited had a pickup.

**Comment by Maleclypse** [comment]
> This means there is a transition issue I don't think is going to be fixed. Should we retain this and have me change the title (and description) to indicate this, as I'd suspect it will be reported again?

Please do.  We'll close it after next stable.

**Comment by PatrikLundell** [comment]
I've changed the title and added bits to the description and additional content parts. I'm prepared to change it further if it need improvements.

**Comment by RenechCDDA** [comment]
> Please do. We'll close it after next stable.

0.G released in March 2023, so closing it as done. 👍
