### ISSUE TITLE
[Innawoods] New missions can't be completed

### ISSUE THREAD

**Issue by n0pen** [CleverRaven/Cataclysm-DDA#59367]
### Describe the bug

Modded missions for Innawoods won't spawn labeled item

### Steps to reproduce

1. Get into Innawoods world
2. Spawn NPCs and acquire MGOAL_FIND_ANY_ITEM mission (relic, stick, etc)
3.  There is no way to get the required item

### Expected behavior

Spawn the tagged item at the start of the mission, making it completable

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-9961-gb96015a73a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

Currently, all MGOAL_FIND_ANY_ITEM are related to terminals and I couldn't find any code related  to automatically spawn items with the mission_id value.
Changes were merged in #59263

**Comment by pjf** [comment]
/confirmed

I've just hit the same on my innawood playthrough.

`MGOAL_FIND_ANY_ITEM` requires the item be tagged with the specific mission ID, which I don't believe we do.

`MGOAL_FIND_ITEM` is likely what was intended

**Comment by Light-Wave** [comment]
Right, completely forgot about this. #60077 should fix this.
