### ISSUE TITLE
"Custom" sidebar no longer has self-aware HP numbers available

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59361]
### Describe the bug

You can't get numerical HP using the "custom" sidebar. This is because #59319 removed those from the vital_numbers_layout widget and added optional self-aware versions of each sidebar's HP display to every sidebar EXCEPT the "Custom" (sidebar.json) one.

### Steps to reproduce

Load "Custom" and confirm there is no self-aware HP.

### Expected behavior

Numerical display should be an option for very sidebar.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: d06b4a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by descan** [comment]
The new "Structured" sidebar also lacks the new Self-Aware widgets.

**Comment by Inglonias** [comment]
The custom sidebar was mostly a tech demo and example on how to do custom sidebar things. I feel that it can now be safely removed, unless someone really objects to it going away.

The structured sidebar, I can definitely fix.

**Comment by Terrorforge** [comment]
I think it would be good to keep "Custom" as a sort of template sidebar that invites the player create their own, not least because it gives us a dedicated "user setting" file that you can transfer when updating. Maybe you even store it in config instead of json/ui. However, the default state of that file should probably be mostly empty, and it should probably be located in a file that matches the name of the sidebar.

Also I personally would like to see the rest of the "vital numbers" as an option in the other sidebars, but I suspect that's more of a me thing than an actual good idea.
