### ISSUE TITLE
Flammable arrows can't be stored inside quivers and are much more lighter than the components used to craft them.

### ISSUE THREAD

**Issue by Nihad2004** [CleverRaven/Cataclysm-DDA#59365]
### Describe the bug

You can't store flammable arrows made of bodkin arrows inside quivers and flammable arrows are 10 times lighter than bodkin arrows even though you use bodkin arrows and few other components to craft flammable ones.

### Steps to reproduce

1. Make a character and spawn a few flammable arrows and a quiver. Equip the quiver.
2. Try to pick up flammable arrows. 
3. They can't be stored inside quiver.

### Expected behavior

Title says it all but for context, I wanted to upgrade my standart bodkin arrows into flammable ones as they're stronger but when I did craft them, I found out you can't store them inside your quiver (I have the large quiver by the way) which makes no sense. Also, I don't know how but flammable arrows are somewhat lighter than the components used to make them but I don't know if this is a bug at all. My main complaint is it's incompatibility with quivers. 

### Screenshots

1. I only have quiver on my character so arrows cannot be stored in another clothing such as duffel backbag.
![image](https://user-images.githubusercontent.com/75498935/179419118-b92bdf6a-9ced-4aca-82b9-e183978b951c.png)
2. Flammable arrows cannot be picked up.
![image](https://user-images.githubusercontent.com/75498935/179419144-8a6030aa-649e-4f7c-9524-b2d121edff36.png)
3. Wooden bodkin arrows can be picked up and they're stored in quiver as it should be.
![image](https://user-images.githubusercontent.com/75498935/179419152-c3da8dc8-f9cb-41ae-84ef-b74462cb8314.png)
![image](https://user-images.githubusercontent.com/75498935/179419231-3e8dd8e2-70df-491e-8d3f-de1795342453.png)
4. Wooden bodkin arrows are heavier and have more volume than flammable arrows even though flammable arrows are made of wooden bodkin arrows and rags soaked with flammable liquid such as gasoline.
![image](https://user-images.githubusercontent.com/75498935/179419326-961acaa4-154b-4118-b381-ff1091ffd29f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1348 (20H2)
- Game Version: d6a1777 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Seems like related to #56595.

**Comment by hexagonrecursion** [comment]
/confirmed : I can not store flammable arrows in a quiver

Flammable arrows actually have the same weight as bodkin arrows:
![image](https://user-images.githubusercontent.com/52621858/179665444-65bc72a6-5377-4a04-99ce-26f76887f92b.png)

You got confused because you compared one flammable arrow to a stack of bodkin arrows.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6ebdac2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Nihad2004** [comment]
> You got confused because you compared one flammable arrow to a stack of bodkin arrows.

Weird it doesn't take all the flammable arrows into account like it does with other arrows types when comparing items. Because I remember I chose the flammable arrows from a stack of 10 like I did with bodkin arrows. Thanks for explanation.

**Comment by GuardianDll** [comment]
To fix this someone need:
go to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/tool/misc.json, replace flamable_arrow tool from TOOL to AMMO, add `"ammo_type": "arrow",`, and somehow fix the bug when, if you try to active pile of 10 arrows, you transform it into only 1 ignited arrow instead

**Comment by cake-pie** [comment]
was already working on it :wink:
