### ISSUE TITLE
Folding a takedown recurve bow that has mods installed sends mods to a parallel dimension

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59364]
### Describe the bug

After the following reproduce steps, the mod is nowhere to be found. You can get them back (see the last step).

### Steps to reproduce

1. Obtain 'takedown recurve bow'
2. Obtain 'arrow rest'
3. Ensure that your marksmanship is at least 1
4. Wield the bow
5. Attach the arrow rest to the bow
6. 'A'ctivate the bow -> "Disassemble it"
7. Observe multiple exceptions:

 ```
 DEBUG    : tried to put an item (arrowrest) count (1) in a container (takedown_recurbow_folded) that cannot contain it: pocket with type (MOD) not found

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1480
 VERSION  : 81f140e
```

```
 DEBUG    : failed to insert mod
 FUNCTION : item& item::convert(const itype_id&)
 FILE     : src/item.cpp
 LINE     : 561
 VERSION  : 81f140e
```
8. Notice that now the arrow rest is nowhere to be found
9. **Workaround**, or how to obtain your arrow rest back: drop the bow, pick it up, and the arrow rest will spawn on the ground.

### Expected behavior

I expect reality to be consistent.

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-07-05-2300
Mod list: default

**Comment by PatrikLundell** [comment]
There have been a number of cases where things that can't be placed end up in limbo for a turn and then dropping to the ground during the next turn. Thus, it might be that the dropping/picking up of the bow steps are redundant and any passing of time might do (in particular movement, as there is a whole slew of things that don't happen as they should have until you move).
