### ISSUE TITLE
sidebar UI, widget request (u_bionic_balance)

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59368]
### Is your feature request related to a problem? Please describe.

I think that widget (or at least variable that can be accessed by widgets) that shows last turn bionic power balance would be great. So player can see if the power providing CBMs produce enough power to keep all active bionics running.

### Solution you would like.

i think that u_bionic_balance variable will be great.

### Describe alternatives you have considered.

May be predictable variable would be better, but it should take into account all this autostarted power providers and such...

**Comment by descan** [comment]
Something like "Power: 100kJ +/- XXkJ" or "Power: 100kJ +/- XX%" seems like it'd function, if the data can be ripped and displayed like that - with the XX being either predictive for next turn or at least last turns usage/percantage if the predictive one isn't possible to code.

**Comment by vetall812** [comment]
I think as torsion ratchet may or may not produce power predictions will be inaccurate. So i think that last change would be enough. As we have movement indicator that tells last action movement points cost.
