### ISSUE TITLE
Make the breach power test less restrictive

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#59362]
### Is your feature request related to a problem? Please describe.

After first pushing PR #59292 where I've unlinked Bulging Eyes (`EYEBULGE`) and Nictitating Membrane (`MEMBRANE`) the [breach power test failed](https://github.com/CleverRaven/Cataclysm-DDA/runs/7362911241?check_suite_focus=true#step:16:397) on the batrachian mutation because of the breach power being above the upper limit.
This lead to quite a [lengthy discussion on the CDDA Discord](https://discord.com/channels/598523535169945603/598535827169083403/997569151130406953) and resulted in me 'fixing' batrachian by moving two mutations from pre-thresh to post-thresh, which is undesirable. Hence the request.

This has happened before in a bigger scale and is quite undesirable, now that the test is concluded more or less obsolete. At least on the `BREACH_POWER_MAX`-end. Quoting @Maleclypse ([link to Discord post](https://discord.com/channels/598523535169945603/598535827169083403/997700429506940958)) here:
> Tests are broken because they were created before it was realized a consequence of the new system was that all mutations in the path to an intended mutation had to be listed in the category the ultimate mutation is in.  #57611 is recent and and I'm fairly positive there are several other PRs performing these kinds of fixes since the tests were set as correctly numbered, before every category exploded in size.

### Solution you would like.

Raise the upper limit or obsolete the check for `BREACH_POWER_MAX` altogether.

### Describe alternatives you have considered.

Leaving the breach power test untouched and *hope* that #59299 fixes it.

**Comment by actually-a-cat** [comment]
Closed by #61394
