### ISSUE TITLE
Smartphone flashlight does nothing

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#59373]
### Describe the bug

Smartphone flashlights do not produce any light

### Steps to reproduce

1. Make a default survivor with a default Evacuee start.
2. Activate your smartphone's flashlight.
3. No light

### Expected behavior

The smartphone flashlight is at least as effective as the cell phone flashlight

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/179423690-a5a5661a-581b-4efe-aced-21acc3e8e7c4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: d6a1777 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

Found this while investigating another smartphone issue at #56127. Smartphones are kind of broken. Someone please fix them.

**Comment by Golfavel** [comment]
Did you move after activating it?

**Comment by Inglonias** [comment]
Yes I did, but to prove it, here's another screenshot.
![image](https://user-images.githubusercontent.com/2125926/179424432-564c3c60-8331-4787-8c24-9efd375a32b5.png)

**Comment by descan** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/59196 This was a known issue (glad someone fixed it here) and as noted then, moving didn't help.

Later I also noticed that other smartphone apps didn't actually work anymore either - I think music was the one I tried that didn't work.

**Comment by Inglonias** [comment]
Closing because this is a duplicate
