### ISSUE TITLE
Deleted/Edited Map Extra Autonotes Reverted When Tile Currently Seen or Re-Seen

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#59393]
### Describe the bug

As I'm playing, I delete or edit map extra autonotes to help keep track of what I've done (delete "Corpses" autonote after I've looted it, change "Derelict Shed" icon to an "x" to indicate I've checked it out, etc.).  A recent experimental update (I'm guessing aec824dd503cd20dd25014101f298dc311a75474 but cf6c27e1b4e71cab92861ac496e41dede60d4b55 might also be relevant) has now made it so that:
1. after deleting or edit the map extra autonote, the deletion/edit is immediately reverted:  that is, the autonote is re-added if it was deleted (i.e., deleted "Corpses" autonote shows up again) or is reverted to its original state if it was previously edited (i.e., "Derelict Shed" icon reverts from "x" to its original icon); and
2. if an autonote is deleted or edited while the player is far away (presumably so that the map tile is no longer currently seen) and the player later returns to the area, the autonote deletion/edit is then also reverted.
3. (Note that these reversions are repeatable -- for example, deleting an autonote while close to the tile results in immediate reversion, deleting the now-reverted autonote also results in immediate reversion, and so on.)

### Steps to reproduce

When close to map tile (so it's seen?):
1. Move near to a map tile with a map extra that results in an autonote being created.
2. Open map and delete or edit autonote.
3. Close map.
4. Open map and observe re-added or reverted-to-unedited-state autonote.

When far from map tile (so it's not seen?):
1. Find a map tile with a map extra that results in an autonote being created and that is far from the player's current location.
2. Open map and delete or edit that autonote.
3. Close map.
4. Open map and observe the autonote deletion/edit has persisted.
5. Move player close enough to map tile (so that the tile is seen?).
6. Open map and observe re-added or reverted-to-unedited-state autonote.

### Expected behavior

Deletions of or edits to map extra autonotes should persist instead of being reverted.

### Screenshots

1. Before attempting deletion or edit: 
![1](https://user-images.githubusercontent.com/109529281/179527869-097f68b3-be6c-4bc8-b951-b973b33192e2.jpg)

2. After deletion or edit:  
![2](https://user-images.githubusercontent.com/109529281/179527947-074db85a-c2bd-4fca-b1b4-c8656cbd65e2.jpg)

3. After closing and reopening map screen:  
![3](https://user-images.githubusercontent.com/109529281/179528031-46cee1bb-8f27-4695-b0bb-6d04744a9977.jpg)

 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 85de01c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots]
]

**Comment by anothersimulacrum** [comment]
Definitely https://github.com/CleverRaven/Cataclysm-DDA/commit/aec824dd503cd20dd25014101f298dc311a75474

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 6ebdac2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
