### ISSUE TITLE
Request: Sort Willowbark Tea into DRUGS category instead of WATER to prevent ODing into Nausea (85de01c)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#59394]
### Is your feature request related to a problem? Please describe.

Issue is due to experiences of Willowbark Tea being classed into WATER so player auto-drinks it when item-container is sorted into Auto Drink location.

### Solution you would like.

Issue is mitigated when player has Strong Stomach trait but I believe a better sorting should be done to prevent automatic vomiting and overdose. Tea causes nausea so sometimes when automated: player throws up at random and wastes Satiety. 

I believe it's better to have the item sorted as DRUG so even if player has Painkiller Dependency that doses can be mitigated to allow weaning off of the trait as well. (Possible?)

### Describe alternatives you have considered.

If item has a specific reasoning to remain in WATER class: is there a way to lower the priority of the item for consumption as opposed to Clean Water? 

Reason being is that via Auto Drink-player will consume it alongside Clean Water, leading to excessive Nausea and vomiting sans Strong Stomach **even if there is** and abundance of Clean Water in same pile. 

### Additional context

![image](https://user-images.githubusercontent.com/43046067/179533790-022be058-bb05-4ddf-8c80-94a74aee1286.png)

**Comment by NetSysFire** [comment]
Or alternatively add `NO_AUTO_CONSUME` to the flags. DRUGS definitely looks more appropriate though.

**Comment by NetSysFire** [comment]
No, unfortunately not. @Light-Wave can probably help out with the Innawoods stuff though.
You would need to manually go through all the items. I already tackled alcohol and gross stuff like spider eggs in #58227.

But however, looking at the git blame, it revealed to me that #57305 caused that, so I'll CC @Sathra225 here.

**Comment by Light-Wave** [comment]
Innawood doesn't really have any item data for tea. The only thing I can think of that is Innawood-specific that could cause issues is fresh_honeydew in mods/innawood/items/food_other.json. It has a little bit of toxins. But you should probably still auto consume it if it is in the auto consume pile. So no changes to Innawood should be needed as far as I can tell.

Anyways, it looks to me like willowbark tea already have the NO_AUTO_CONSUME tag. Shouldn't that solve this issue? Or do you still auto drink it even with that tag? If so, that sounds like a bug in the C++ code.

**Comment by NetSysFire** [comment]
>Anyways, it looks to me like willowbark tea already have the NO_AUTO_CONSUME tag

No. It specifically deleted this flag:

https://github.com/CleverRaven/Cataclysm-DDA/blob/054348b1ce374bbc9e9920319480e5fbd5ba89f0/data/json/items/comestibles/drink.json#L1276

See the mentioned PR.

**Comment by Sathra225** [comment]
Ah, I see what happened. Failure to read on my part as willowbark tea is a copy-from tea so the NO_AUTO_CONSUME there doesn't do anything.
