### ISSUE TITLE
Chitin carapace is uncomfortable

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#59392]
### Describe the bug

The mutation chitin carapace makes the survivor permanently uncomfortable in every limb except eyes (-20% speed) and there is no way to wear something soft below the "integrated armor" layer to mitigate this effect, i was told to make a bug report about it

### Steps to reproduce

1. mutate  chitin carapace
2. observe @ screen
3. try to wear any soft item
4. enjoy the -20% speed

### Expected behavior

don't think we should be able to wear something soft underneath, i think rather it shouldn't be that hampering

### Screenshots

![image](https://user-images.githubusercontent.com/42104923/179524063-7ce188cf-5979-4613-bbd5-534084f7b42d.png)
![image](https://user-images.githubusercontent.com/42104923/179524188-9ac68ccd-55b5-469b-bb49-6dc07263bb92.png)
![image](https://user-images.githubusercontent.com/42104923/179524247-8031ff12-9a00-4e41-95ce-e7893f8fbbfd.png)

### Versions and configuration

Windows 10
build 2022-07-18-0605
tiles
english
[
  "dda",
  "no_hope",
  "blazeindustries",
  "no_npc_food",
  "no_fungal_growth",
  "speedydex",
  "stats_through_kills",
  "translate_dialogue",
  "MMA",
  "No_Rail_Stations"
]

**Comment by Terrorforge** [comment]
I think the real problem here is that you seem to have mutated Chitin Carapace without first having Epicuticle, which should not be possible. Did you notice anything weird while mutating? Is it possible that you somehow managed to purge Epicuticle but keep Chitin Carapace?

**Comment by anothersimulacrum** [comment]
Looks like a dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/58596

**Comment by Terrorforge** [comment]
That might be a separate (but related?) issue, then. NPCs shouldn't have mutations they lack the prerequisites for.

**Comment by RHSvenson** [comment]
In the experimental from last week I managed to get this through normal mutation by loosing epicuticle to fur during rabbit mutation. I kept carapace.

**Comment by MochaModifier** [comment]
Had this happen on experimental v.2ed6865

To preface, I started an experiment run with Genetic Chaos and a few immutable taits (masochist, outdoorsman, tough feet). I use the journal to track my mutations over time

I grew the epicuticle mutation first, then developed chitin carapace shortly after. 

The next night, I lost the _epicutical_ mutation, it had turned into rough skin; and then into feathers. (within the same hour according to the log)

**Comment by MochaModifier** [comment]
This keeps happening, and it's fairly easy to get in a mutant start - pick epicuticle and genetic chaos as starting traits, and you'll likely grow chitin.
Also seems a bit odd that most mutations then become a back and forth of gaining chitin and hairy chitin; I spent several days of just mutating into one or the other.

Perhaps an unintended thing, but if you lose epicuticle, you might mutate something else like scales - this stops the chafing again (until you once again lose the skin mutation)

Seems like it'd be unintentional for you to have both chitin and scales - a pretty potent pair of defensive mutations.
Epicuticle to me seems like the epidermis that chitin grows out of - so to lose epicuticle, it seems odd that you could keep the chitin. Perhaps you'd lose the chitin mutation if this happens?
