### ISSUE TITLE
Digging Shallow Pit on Bog Iron destroys deposit. Intended? (85de01c)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#59401]
### Describe the bug

Digging a Shallow Pit on a Bog Iron deposit instead of Extract Bog Iron destroys the entire deposit.

### Steps to reproduce

Same as above.

### Expected behavior

Bug? Feature? (Un)Intended? I'd expect that at least you'd get a "You cannot build that here" or a prewarning. Strange that the Deposit is considered diggable terrain despite requiring a Shovel to process/Extract Iron?

Will test Clay/Sand deposits for same issue.  

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 85de01c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by kevingranade** [comment]
That's how it works yes,  bog iron deposits are coded as a terrain type and digging a shallow pit changes the terrain type.
