### ISSUE TITLE
Implement batch time savings for moving multiple items at once

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59417]
### Is your feature request related to a problem? Please describe.

Currently dropping 87 cudgels from a hiking backpack to the ground takes 6 minutes.
Meanwhile moving the same amount of items via AIM from a shopping cart to the ground next tile takes 40 seconds.

This is unreasonably punishing on the backpack users.

### Solution you would like.

Moving batches of items should have batch time savings, similar to existing batch time savings on cooking recipes. You would not spend 2x time moving 2 cudgels out of a backpack compared to one - you put it on the ground (once), open it (once), take items (one action per item), and close it (once).

**EDIT:** a solution that I think works very well has been proposed in https://github.com/CleverRaven/Cataclysm-DDA/issues/58793#issuecomment-1169630254

```
The activity just has to remember which containers were accessed already
and only count that for the first item taken from or put there.
```

### Describe alternatives you have considered.

Keeping things as is and enjoying multi-minute transfer times does not sound like a fun alternative.

### Additional context

Game version: cdda-linux-tiles-x64-2022-07-05-2300
Mod list: default

**Comment by rgehlen** [comment]
Duplicate of  #58793?

**Comment by Zireael07** [comment]
Related but not dupe. This is afaict about a discrepancy between inventory and AIM (which IIRC has been mentioned a couple times in the past)
