### ISSUE TITLE
Add enemy - Zoomer

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59413]
### Is your feature request related to a problem? Please describe.

We have boomers, but no zoomers.

### Solution you would like.

add Zoomers.

Essentially a better zombie runner. Give it a lesser spawn weight. Can just spawn into hunters like the runner does for now. Basically halfway between runners and hunters for difficulty. Proposed stats:

 {
    "id": "mon_zoomer",
    "type": "MONSTER",
    "name": { "str": "Zoomer" },
    "description": "This undead races toward you with both arms outstretched behind.  Darkness spills from its dead eyes; a roiled scream from its dislocated jaw.",
    "copy-from": "mon_zombie", 
    "hp": 70,
    "speed": 110,
    "color": "light_cyan",
    "special_attacks": [
      [ "scratch", 15 ],
      {
        "type": "bite",
        "cooldown": 5,
        "damage_max_instance": [ { "damage_type": "stab", "amount": 10, "armor_multiplier": 0.7 } ]
      },
      {
        "type": "leap",
        "cooldown": 10,
        "max_range": 2 
      }
],
    "fungalize_into": "mon_zombie_fungus",
}

### Describe alternatives you have considered.

Not doing this because its too silly or unneeded.

make it a faster boomer. Add to boomer upgrade group and/or add as a rare variant spawn.

leap range could be more, 2 might be useless. Or give it a different attack instead.

### Additional context

Not sure why fungalize is missing for zombie runner, or if that is standard on some enemies?

**Comment by Gotdamnmiracle** [comment]
Can we, uh, name it something like a sprinter or something?

Zoomer has as second meaning more common in the US. While boomer does as well it is also the name of the exact same enemy from left 4 dead, so it makes a shred more sense.

I'd prefer to not have a zombie millennial.

**Comment by liminalRoar** [comment]
I am not unaware. Personally if i was in a zombie apocalypse i would name creatures descriptive but slightly amusing names. I understand boomer is a more established name in the zombie world Boomer's secondary association is funny happenstance, but adds to their charm in my view and i think most people would find the humor in making a "zoomer" enemy.

If it's too dumb or unnecessary i can understand that, it was just a fun thought. If you think it's inappropriate or offensive i am surprised, i don't see it that way.

**Comment by Gotdamnmiracle** [comment]
Not offensive. I just don't think it matches the tone of the game, necessarily.

**Comment by liminalRoar** [comment]
well shucks. We got the shia labeouf stuff and all, i figured it wasn't too far out of character. and like i said, and actual descriptive name anyways.

There's always adding an early game "Leaper" or something, being more or less what i proposed as an easier, early game Zombie Hunter variant. In general adding more early game enemies isn't as exciting as adding new more difficult versions. But it's nice to add some more variety i think.

**Comment by sonphantrung** [comment]
And ShiaLabeouf is now Crazy Cataclysm exclusive (he appears in the base game but doesn’t spawn anywhere at all unless the mod is enabled)
