### ISSUE TITLE
Bike racks do not work

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#59425]
### Describe the bug

I can't secure my bike to my vehicle. I have 3 tiles on my car with bike racks, next to my bike, which also has 3 tiles. I 'e'xamine the car and select to load the bike. Nothing happens. No text feedback, and driving away leaves the bike in place. Trying to select to load the bike on all 3 bike racks before driving away ends the same way. 

### Steps to reproduce

Find a bike at a nearby dairy farm. Ride it back home. Create 3 bike racks on vehicle at the rear. Grab bike and place it next to the vehicle when done. Examine the vehicle in a tile with a bike rack. Select to load vehicle. Drive away. 

### Expected behavior

The bike should move with the car when I drive. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: fac3512 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
[Aventura.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9144852/Aventura.zip)

    Bionic Professions [package_bionic_professions]
]

**Comment by Merikona** [comment]
I remade the bike into 2 tiles and reinstalled the bike racks, and they still do not work.

**Comment by jagoly** [comment]
seem to be having the same issue, I have a shopping cart and car with bike racks but it ain't working
