### ISSUE TITLE
exchanging bundles of cash gives 10X more money than it should, suddenly im rich from 2 safes

### ISSUE THREAD

**Issue by yamil-90** [CleverRaven/Cataclysm-DDA#59427]
### Describe the bug

i love being able to exchange the whole stack of cash into e-cash at once but i noticed that im getting way more money that what i should
one bundle of 100 20 dollar bills gave me 19800.00 instead of 1900.00 

### Steps to reproduce

1 get a bundle of cash (any bundle) 
2 get a cash card
3 exchange the bundle at the banks ATM for e-cash (without disassembly)
4 notice you are getting 10 times what you should inside the cash card

### Expected behavior

i should get 1900.00  for a bundle of 20 dollar bills

### Versions and configuration

- game version d6a1777, is one of the latest experimental versions
- OS ubuntu 20.04.4 LTS

**Comment by hexagonrecursion** [comment]
A twenty-dollar currency bundle (id: money_bundle_twenty) is **1000** twenty-dollar bills rather than 100.

It was converted to $19800.00 e-cash i.e. the ATM actually charged me 2% instead of the advertised 1%. :angry: I want to speak to the manager!

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 8f770f0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by GuardianDll** [comment]
yeah, as said before, bundle is 1000 units
`A thousand hundred-dollar bills, divided evenly between ten mustard currency straps`
dont confuse it with strap, which is 100 units

**Comment by Cimanyd0** [comment]
> A twenty-dollar currency bundle (id: money_bundle_twenty) is **1000** twenty-dollar bills rather than 100.
> 
> It was converted to $19800.00 e-cash i.e. the ATM actually charged me 2% instead of the advertised 1%. 😠 I want to speak to the manager!

That looks right to me. 1% of $20,000 is $200.
