### ISSUE TITLE
Bare bones base camp

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59439]
### Is your feature request related to a problem? Please describe.

The current set of base camps allows you to set up camp only in a few select places, where it mandates constructions and order of construction which may be undesirable for some players. At the same time, base camps provide some functionality that isn't available through other means (sending off companions on tasks and companion crafting in particular), and so might be wanted without the burden of a "proper" camp in an "approved" location.

### Solution you would like.

Introduce a bare bones base camp that just declares the tile as a base camp, but doesn't provide any construction, not even of a bulletin board, but which can be set up almost anywhere.

Once a player builds a bulletin board anywhere within the tile, the "full" set of camp functionality should become available (because the interface through which it's reached has been constructed), with the set being:
- The companion tasks base camps currently provide gated behind construction (remote logging, foraging, etc.)
- The ability to construct expansions in all surrounding tiles (the expansions would still have to satisfy the restrictions they have).
- The ability to order companions to do crafting of a (hopefully well selected) set of items. The crafting would still rely on resources being available within the base camp, but provided the resources have had the Basecamp: Storage zone painted over them they should work when constructed or placed by the player.

### Describe alternatives you have considered.

Changing the companion interaction dialog to include crafting and "base camp" mission orders (although I don't know how you'd handle abstracted calories in that case), somehow handling return to wherever the order was given and item delivery to the same location.

### Additional context

Not placing a bulletin board but requiring the player to make it allows this base camp to be set up anywhere, without issues with walls potentially being in the way, such as caves roof tops, or even down in mines.

It should be noted that this "base camp" wouldn't automatically be available anywhere, as you'd still have to manually list every type of terrain for which it should be legal. Thus, I'd expect only some roofs and building interiors would be included in the list.

I think this could be made to work in e.g. Innawoods if that mod overrode the bulletin board construction/deconstruction with something reasonably easily available (I think nails are hard to come by there, and planks require some progress along the technology ladder).

Companion crafting list bloat is a significant UI issue (look at the bloated workshop lists). In the longer term the UI ought to be changed to be very similar to the player crafting one (categories etc., but omitting fluid recipes that can't be crafted by companions until a solution to that has been found).
In the mean time a comparably "short" list of things ought to be provided, with a recommendation for players to (unfortunately) mod their lists to include the things they want their companions to be able to craft.
It would be better to allow the players to add/remove items to the crafting list, but that would require the construction of a UI for that, something I think the uilist currently used isn't up to. A bare bones UI would just list every known recipe that doesn't produce fluids and provide a search function to allow players to find the items they want in that very long list.

**Comment by liminalRoar** [comment]
I would love to be able to set up a base camp anywhere. Is there possibility to add a section of the zone manager for declaring "zones" for base camp usage?

**Comment by PatrikLundell** [comment]
You mean have the zone manager do the same job the companion request does, but without the tie to the world tile ID?
If the code was added to do that, you'd end up with a base camp with almost no functionality, as there'd be no JSON definition of its functionality. Construction of a bulletin board would allow you to interact with it to store calories and the very small set of hard coded actions you get immediately when you start a camp (no crafting, as that's defined by JSON).

A better way to actually allow camps anywhere would be allow you to define the set of terrains to somehow say "any terrain whatsoever" (e.g. by an empty list or listing t_null or t_clear, or by having an alternative token for that section instead of a list). That would lead to some silly things like flying and then declare the air a camp, or declaring a camp on water, but so what? It'd be stupid and useless, but also harmless, as far as I can tell.
