### ISSUE TITLE
"You can't do anything interesting with your none"

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#59432]
### Describe the bug

Found in #59431.

### Steps to reproduce

1. Wield nothing, just have empty hands.
2. Press the keybind for "Use wielded item".
3. "You can't do anything interesting with your none."

### Expected behavior

A more sensible message when you have nothing in your hands. E.g "You are not wielding anything you could use."

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-10021-g2f227d4490d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by WIsaacOH** [comment]
I would be happy to take care of this.

**Comment by NetSysFire** [comment]
Great! Please just file a PR and link the issue in it because we usually do not assign issues to people.
