### ISSUE TITLE
Log says my Psychopath character feels bad when NPC kills a zombie child

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#59444]
### Describe the bug

The title sums it up.

I was in a homeless camp and a bunch of zombies had already spawned there (idk if this is a bug as well)

At some point while I was walking back to my vehicle and I got the message in the log. This makes no sense as I was not in combat, and my character has the psychopath trait.

No mood debuff though

It seems the homeless NPCs (who are **not** my followers) killing a zombie child made the log say I felt guilty, although it's actually them getting that mood effect

### Steps to reproduce

[Optional] Make player character have psychopath trait
1. Any NPC should do, but if its a specific case, then one of the homeless camp NPCs will do
2. Spawn zombie child and let them kill it
3. Message will show as in screenshot

### Expected behavior

It shouldn't print that

### Screenshots

![image](https://user-images.githubusercontent.com/88375697/179972112-5128aeec-7e4a-4922-8725-3edce19429db.png)

This despite my character being a psychopath too
![image](https://user-images.githubusercontent.com/88375697/179972739-3a8d8cc3-7c8c-4365-b05b-2ddcaaa8f2ba.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: ae2ff5c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 75e3982 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by GoLoT** [comment]
Related to: https://github.com/CleverRaven/Cataclysm-DDA/issues/54077#issuecomment-1006072327
