### ISSUE TITLE
Unload Zones behave oddly

### ISSUE THREAD

**Issue by TaiGambol** [CleverRaven/Cataclysm-DDA#59448]
### Describe the bug

When using static zones for organization, an 'Unload Everything' zone fails to unload any containers inside it, unless the container is also in an 'Unsorted' zone **and** there is nowhere the container can be sorted to.

### Steps to reproduce

1. Make a character, with a duffel bag filled with random objects.
2. Put down an 'Unload Everything' zone and place the duffel bag in it.
3. Sort loot. Duffel bag does not unload.
4. Place down an 'Unsorted' zone on top of the 'Unload Everything' zone, then place a 'Clothing' zone nearby.
5. Sort loot. Duffel bag is moved to the Clothing zone without being emptied.
6. Move duffel bag back to 'Unload/Unsorted' zone, disable Clothing zone.
7. Sort loot. Duffel bag correctly unloads.

### Expected behavior

I expected the duffel bag to be unloaded without also needing an Unsorted zone; failing that, I expected it to unload _before_ being moved to the Clothing zone. As it currently stands, static Unload (and by extension Strip Corpses) zones are effectively non-functional unless you don't otherwise use zones - and if you don't otherwise use zones, you're unlikely to use Unload zones, making it a moot point.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: ae2ff5c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Culinary Days Ahead [culinary_days_ahead],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Magiclysm Revamp and Additions [magicrevamp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    <color_cyan>Muse Professions</color> [Muse_Professions_Mod]
]

**Comment by Inglonias** [comment]
Tagging @bombasticSlacks in case I'm wrong about this, but I think this is how the zones are intended to work. Unload zones are lower priority than other types of zone.

**Comment by bombasticSlacks** [comment]
This is how they are supposed to work yeah. If someone wanted to implement a toggle for "always unload before sorting" that would be fine but everyone has a different way they want zones to work that would be easiest for them if this was just changed I would get similar complaints the other way (and have in the past).

**Comment by TaiGambol** [comment]
Can I ask how the 'expected use' for them right now is, in that case? Because it makes no sense to me the way it's currently implemented.

**Comment by bombasticSlacks** [comment]
Lots of people like keeping specific containers intact. So for example filtering for first aid kits, or filtering for prescription bottles.  Though I realize that now that normal zombies have stuff in clothing there is an issue of grabbing still fully loaded back packs, pants etc. a bunch of the time. As I said I think this does need to be either a toggle or two separate zones. Neither would be too much work however.

**Comment by chrispikula** [comment]
What about the use case of unloading all the containers on corpses via personal zones?  

Do I need to have a set of personal zones that I toggle on & off for unload then sort?

**Comment by bombasticSlacks** [comment]
alright I've fixed this, since it was a problem overall. You can now configure if you want containers to unload even if they will be sorted.

**Comment by Je55eah** [comment]
Is that what this means?
![always unload](https://user-images.githubusercontent.com/12481255/203429218-7d93021e-a9b8-4af5-9e92-84d1d0458134.png)
