### ISSUE TITLE
Loaded "5.56x45mm/.300BLK 10-round clip" considers every item with charges to be its ammo

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59441]
### Describe the bug

Having a loaded "5.56x45mm/.300BLK 10-round clip" in inventory suddenly recolors all items with charges in inventory to light-red color.

This is very disturbing.

### Steps to reproduce

1. Spawn a new character.
2. Spawn "candle", "smartphone (UPS)", "lighter", "oil lamp", "cash card".
3. Look in inventory and see that everything is properly colored.
![normal](https://user-images.githubusercontent.com/55463047/179960042-b5430ec5-f261-4522-9c5c-31c99b7b6a5b.png)
4. Spawn "5.56x45mm/.300BLK 10-round clip"
5. Look in inventory and see that items with charges have suddenly been recolored light-red.
![red](https://user-images.githubusercontent.com/55463047/179960321-c059510e-6b8a-4483-97f1-611d142cc65c.png)

### Expected behavior

1. Magazines/speedloaders should not recolor random unrelated items in inventory
2. If items ARE recolored due to being considered proper ammo (or any other reason like being stale food etc), **there should be a plain-text explanation available to the player** as to WHY the item has a different color, because what right now various colors mean is a mystery.

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-07-05-2300
Mod list: default

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 75e3982 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
