### ISSUE TITLE
Some symbols are absent in Terminus font (default font shipped with game) lets change them

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59451]
### Describe the bug

As far as game would work on a terminal it will use local terminal font. And I understood it, but the game shipped with Terminus font, and I think that we should be sure that every symbol appears at least with this font.

Issue #58991 contains some screenshots with wind direction. The gray screenshots display rectangle instead of arrow. And those arrows are diagonal ones.

I think that we can use more common symbols like table corners. They usually exist in fonts.

### Steps to reproduce

Change your font setting to use Terminus font, set wind direction to NW, NE, SW or SE.

### Expected behavior

I think that symbols "┌,┐,└,┘" would be better.

### Versions and configuration

any

**Comment by ZhilkinSerg** [comment]
unifont fallback should be working in that case and it works fine to me:

![Uploading image.png…]()

**Comment by vetall812** [comment]
> unifont fallback should be working in that case and it works fine to me:

Unfortunately game use just one font at the time, so you can't use Terminus for everything but diagonal arrows.

Terminus looks better on mobile. 

So as alternative we can either change wind widget to tell directions by letters (NW), or add two variables wind speed (text: data+units) and wind directions (number 0-8, where 0 is still and 1-8 represent directions)

**Comment by anothersimulacrum** [comment]
> > unifont fallback should be working in that case and it works fine to me:
> 
> Unfortunately game use just one font at the time, so you can't use Terminus for everything but diagonal arrows.

You misunderstand, the game can and does (fallback to unifont for missing glyphs in primary font(s)), if it's not working it's a bug.

**Comment by Qrox** [comment]
> the game fall back to next font in setting only if it can't use current font at all

It falls back to the next font if the currently rendered glyph is not provided by the font.

**Comment by vetall812** [comment]
Well then this is a bug.
![image](https://user-images.githubusercontent.com/6676374/180238406-c65582ba-96d2-487e-89f5-03f01172afcc.png)
