### ISSUE TITLE
Make Hordes mandatory

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59466]
### Is your feature request related to a problem? Please describe.

The game can get a bit static because it doesn't have many ways of forcing the player out of their comfort zone. Base building in particular feels a bit anemic because you don't really have to worry about defenses.

Wandering hordes are an interesting and mostly functional feature that could alleviate this, but they're still kind of wonky and underdeveloped because they haven't gotten any serious attention in... years, I think? Not only do they have problems in and of themselves, new features are never implemented with hordes in mind.

### Solution you would like.

In discussions of portal storms, it was mentioned that it is now policy to not allow users to opt out of major features, specifically citing the lack of development on hordes as an example of how this leads both players and devs to ignore the feature instead of putting in the work needed to fix it.

The solution seems simple: do not allow players to opt out of hordes. This will create incentive to fix what's broken, balance what's annoying and build more systems on top of and around this promising but incomplete feature.

### Additional context

This should probably wait until after 0.G, tho.

**Comment by I-am-Erk** [comment]
This is planned, but [infrastructure is necessary first](https://github.com/CleverRaven/Cataclysm-DDA/projects/3). The current hordes framework doesn't respect things like walls and player based.

**Comment by Terrorforge** [comment]
That's kind of my point, though. A new implementation has been planned since 2015, but it doesn't look like there's been any progress since 2018. I don't think that would be the case if zombies had been teleporting into every player base built in the last seven years.

**Comment by Zireael07** [comment]
@Terrorforge: From my couple attempts at hordes, yes, they teleport into player bases.

The reason people aren't up in arms is simple: hordes are known to be broken, so very few people actually play hordes.

**Comment by Terrorforge** [comment]
My point exactly. I'm not saying that bug doesn't exist, I'm saying that it's being ignored because hordes are opt-in. If they were mandatory, people _would_ have been up in arms, and it would've gotten fixed years ago.

**Comment by WreckingAbandon** [comment]
They certainly would be up in arms if you enforce them to play a feature that everybody knows is currently broken. I hope if this ever comes to pass they have at least some part of a general fix already planned out.
