### ISSUE TITLE
Invalid or misplaced field name "playlists" in JSON data

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59464]
### Describe the bug

For the last while, I've been seeing this error whenever I boot up the version without sound included on windows.
![image](https://user-images.githubusercontent.com/45136638/180100791-fce5a298-1f40-40fb-af4a-bd0b31f89f19.png)

And on and on
![image](https://user-images.githubusercontent.com/45136638/180100857-5088da94-0f4d-4919-9721-08ee6fe43e98.png)
![image](https://user-images.githubusercontent.com/45136638/180100876-6ca00331-4423-49de-aabc-b1a5294a5d78.png)

Tested on 64b msvc and non-msvc without sound so far.
Edit: Tested on 64b msvc with sound, and got it too.  It seems some people aren't getting this which makes it more curious.

### Steps to reproduce

1. Download cdda-windows-tiles-x64 version without sound - eg [cdda-windows-tiles-x64-2022-07-20-1912.zip](https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-07-20-1912/cdda-windows-tiles-x64-2022-07-20-1912.zip)
2. start the game
3. get these errors

### Expected behavior

Shouldn't be getting json errors on a fresh download of the game.

### Screenshots

see above

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 57b062c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I've had this for several weeks on multiple computers in different locations. Doubtful it's just my system.

**Comment by GeekDuanLian** [comment]
I just encountered this error too, I found out that I disabled all audio outputs, after re-enabling any one, the error disappeared.

**Comment by I-am-Erk** [comment]
It eventually vanished for me too. It's a very strange bug.

**Comment by I-am-Erk** [comment]
I haven't been able to reproduce this since, so I am cautiously closing this but I suspect it's still out there somewhere.
