### ISSUE TITLE
"tracked" per JSON_FLAGS.md causes error on loading.

### ISSUE THREAD

**Issue by YehnBeep** [CleverRaven/Cataclysm-DDA#59478]
### Describe the bug

JSON_FLAGS.md listed a "TRACKED" flag, however, trying to create a vehicle part with it yields the following error when attempting to load:

 DEBUG    : vehicle part yc_tread has unknown flag TRACKED

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 692
 VERSION  : ae2ff5c

### Steps to reproduce

Create a vehicle part and include the flag "TRACKED"

### Expected behavior

Expected to load without an unknown flag error.

### Versions and configuration

win 10
tiles x64
ae2ff5c

**Comment by PatrikLundell** [comment]
I thought the player action of marking a vehicle as tracked would be using this variable, in which case it isn't intended to be used as a vehicle part property, but rather something that's attached to a vehicle (and probably a vehicle part, technically) while the vehicle is being tracked.

**Comment by YehnBeep** [comment]
> AFAIK it's intended that users of this flag add a definition for it.

Hmm. Well, I can only say that I did not expect using a documented flag to throw an error, and the documentation makes no mention of extra steps needed.

> I thought the player action of marking a vehicle as tracked would be using this variable, in which case it isn't intended to be used as a vehicle part property, but rather something that's attached to a vehicle (and probably a vehicle part, technically) while the vehicle is being tracked.

It sounds like you are thinking of the "TRACK" flag, which is distinct from the "TRACKED" flag; the latter is a matter of locomotion (At least, according to the documentation... which already seems suspect).

**Comment by PatrikLundell** [comment]
The "TRACK" flag is listed in the vp_flags.json file and it is used on a vehicle part called "tracker", which is indicated to be used for the usage I suggested.

I find no use of any "TRACKED" flag anywhere in the JSON files of the game.

There are vehicles intended for use on railway tracks (draisines), but neither they nor their parts have any "TRACKED" flag.

The description of the "TRACKED" flag in the documentation suggests that it ought to be used for rail using vehicles, but the fact that it doesn't seem to be used indicates that it may have been replaced by "RAIL" which isn't in the documentation file, but is a flag on "rail_wheel".

Thus, I suspect the documentation is obsolete.

**Comment by Night-Pryanik** [comment]
The documentation isn't obsolete, it reliably depicts what the game is doing with this flag. The thing is that no vehicle part in the game actually uses this flag, and we need either make some part use this flag or remove the dead code related to this flag.
