### ISSUE TITLE
sidebar UI, widget request (u_bionic_percentage)

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59475]
### Is your feature request related to a problem? Please describe.

I want to draw a sidebar widget with graph that represents power reserves.
But currently we have only text variable.

### Solution you would like.

Please add variable that represent power percentage.

### Describe alternatives you have considered.

add ability to reach "u_val": "power_percentage" from the sidebar

**Comment by mlange-42** [comment]
@vetall812 `u_val` for `power_percentage` (for use in conditions) is already there:

https://github.com/CleverRaven/Cataclysm-DDA/blob/8b678c8fbc51a9d6c762565fc8fbf9a64a90efb8/src/condition.cpp#L1546

Widget var `power_percentage` for direct use in widgets is in the works...

**Comment by vetall812** [comment]
> @vetall812 `u_val` for `power_percentage` (for use in conditions) is already there:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/8b678c8fbc51a9d6c762565fc8fbf9a64a90efb8/src/condition.cpp#L1546
> 
> Widget var `power_percentage` for direct use in widgets is in the works...

Yeah, i want to use it in widgets. As i can't code )
