### ISSUE TITLE
Add hint for mouse over sidebar widgets

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59472]
### Is your feature request related to a problem? Please describe.

Some sidebars looks great, but lack of labels (in case of limited width for example) make it difficult to read or graphs that represent numerical value can be not obvious.
On the other hand if following solution will be implemented some sidebar can reduce or remove unnecessary labels.

### Solution you would like.

It would be great if when mouse cursor positioned over some sidebar widget to show some hint.
Appearance can be similar to the labels of sidebar rows (red text on the left of sidebar)
Info that I'd like to see is:
- label for current widget (even, or especially if NO_LABEL flag used)
- numerical value of current widget (value of variable used in widget in fact), if it text variable - so let it be text. But in cases when numerical variable presented as graph or text, show the number.

### Describe alternatives you have considered.

Probably some numbers shouldn't be visible. Bodypart HP value without a self awareness for example.

### Additional context

Very nice sidebar #59182 would benefit from it.

**Comment by liminalRoar** [comment]
I like this idea, goes along with my recent suggestion some.  #59288 in brief:

- Right click anywhere on sidebar opens sidebar options ("}")

Left click on the following sections opens the corresponding menu:

- Stats opens player info ("@")
- Limbs opens Body status ("s" under the "@" player info screen)
- Compass opens map ("m")
- Log opens the message log ("P")

**Comment by PatrikLundell** [comment]
I don't have any problems with adding mouse over hints, but I strongly dislike using that as an excuse for making a mouse required to be able to understand a widget, both because I don't like to be forced to use a mouse, and because a UI designed for general use should be legible (if you're a power user who knows the fields by heart, it would make sense for you to use a compact design with no indicators, but then you don't need any mouse overs either).

**Comment by vetall812** [comment]
> I don't have any problems with adding mouse over hints, but I strongly dislike using that as an excuse for making a mouse required to be able to understand a widget, both because I don't like to be forced to use a mouse, and because a UI designed for general use should be legible (if you're a power user who knows the fields by heart, it would make sense for you to use a compact design with no indicators, but then you don't need any mouse overs either).

Agreed. And after some thoughts I cannot see actual using this feature by players. But i requested it because i need some debug tools for mobile sidebar. 
Right now this area is under rapid development and sometimes one cannot be sure if it's problem with incorrectly defined widget, or the game return weird data.

An example - right after loading game and some turns after atmospheric relative humidity is zero (later it turns to real numbers). Also i have some doubts about current body part wetness.

**Comment by PatrikLundell** [comment]
More debug support is great, as long as it doesn't impact game play.

However, for that use you'd probably want to be able to hook up the debug support to whatever info you want to examine at the moment, which suggests to me that it would be a hook to something that's easily modified into what you want to get hold of (more or less "send the whole set of widget and screen info into this function for display of what you want to see").

**Comment by vetall812** [comment]
> More debug support is great, as long as it doesn't impact game play.
> 
> However, for that use you'd probably want to be able to hook up the debug support to whatever info you want to examine at the moment, which suggests to me that it would be a hook to something that's easily modified into what you want to get hold of (more or less "send the whole set of widget and screen info into this function for display of what you want to see").

Probably this.

**Comment by mlange-42** [comment]
With the upcoming variety of sidebars, even experienced players should be able to somehow get information about what a widget or indicator represents when trying a new sidebar. Things can look quite unfamiliar at first, check the new sidebar "mobile" by the OP for an innovative example.

Top-level widgets can now be explained to the player using the widget property `description`. However, a top-level widget can contain a dozen or more indicators. So mouse-over hints are still useful.

Regarding the mouse requirement, the sidebar settings menu could have an option to tab through widgets to view the hints.

**Comment by kevingranade** [comment]
Closing long stale discussion.
