### ISSUE TITLE
Basecamp crafting results excessive

### ISSUE THREAD

**Issue by Sathra225** [CleverRaven/Cataclysm-DDA#59484]
### Describe the bug

Had a NPC craft wooden panels from heavy wooden beams (also crafted via basecamp menu and these turned out fine).
It took about 2 days and at the end I had 24 tiles containing 48 splintered wood and 52 wooden panels. Which is far in excess of the expected 80 panels

### Steps to reproduce

Have 20 Heavy Wooden Beams and use 'Wooden panels from Heavy wooden beams' camp recipe to craft them into panels.

### Expected behavior

Only getting 80 panels and 140 splintered wood.

### Screenshots

<img width="602" alt="UhhWhat" src="https://user-images.githubusercontent.com/100510526/180309803-cabb576e-5ec0-42a0-8a8f-e904cc7d83ae.png">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: 072a7a3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Save file:
https://www.dropbox.com/sh/wo8kq3cu2zfvzw3/AABQshYHjThpIq86a2wkEpTva?dl=0

**Comment by Sathra225** [comment]
I think what may have happened is that for some reason it multiplied the byproducts (7 splintered wood and 3 panels) by 20, then that by 20 **again**

**Comment by PatrikLundell** [comment]
"Latest experimental" is a useless description. At best it was valid when the issue was written, and it may well have been outdated by the time it was posted. The game provides a functionality to capture the information into the clipboard so it can be posted into reports.

**Comment by Sathra225** [comment]
It does? Time for some digging.

**Comment by PatrikLundell** [comment]
No need for digging. I didn't spell it out since I though it was widely known (and might be included in the template text):
- <ESC>
- Debug menu (this step might be because I've enabled the menu, but it's available without that step)
- Info
- Generate game report

Produces:
- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: d6a1777 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Sathra225** [comment]
You are correct and I can't read apparently.

But updated that part now and double-checked after updating. Spawned in 20 heavy wooden beams and had an NPC start crafting 20 'wooden panels from wooden beams'. Same result.
It also takes around 4 days for some reason instead of the expected 40 hours (1.66r days).

**Comment by DamienRoyan** [comment]
>It also takes around 4 days for some reason instead of the expected 40 hours (1.66r days).

Sounds like the time is based on an outdated hardcoded value, instead of pulling the time from existing recipes

**Comment by Sathra225** [comment]
Still current.
- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: 60f648c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]
<img width="242" alt="2beamstopanels" src="https://user-images.githubusercontent.com/100510526/185545757-89ae530e-fded-4ff0-a3b4-e8e16d2548bc.png">
This was from ordering 2 beams cut into panels. It should have been 14 splintered wood and 12 panels, not 28 splintered wood and 14 panels.
Best guess is that it's applying the unit multiplier to byproducts twice.

**Comment by PatrikLundell** [comment]
The logic for the time taken accounts for the companion sleeping if the crafting takes too long. The logic operates with 10 hour work days, so 4 days for a 40 hour crafting job sounds correct.

**Comment by PatrikLundell** [comment]
The logic for the time taken accounts for the companion sleeping if the crafting takes too long. The logic operates with 10 hour work days, so 4 days for a 40 hour crafting job sounds correct.
