### ISSUE TITLE
Aim FOV obscuring monsters changes how electroreceptors work

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#59486]
### Describe the bug

Messing with #59477 I noticed electro receptors have weird interaction with aiming FOV code that's likely coincidental although I'm not sure about the correct behavior:
With electroreceptors you always see the electric monsters with the graphics, except for the case when you start aiming and the aiming FOV blocks them, then they turn into "sense a creature" blobs.

It seems aiming returns apparent_light_info that specifies 'obscured' and this trips the mutation from working.

cata_tiles::draw_critter_at seems to have collected a lot of cruft over time and has mutating variables in multiple branches just to draw _sees_player overlay before exiting, this can probably be rewritten to be much simpler so it can be reasoned about and each case handled separately, specifically the case where lightmap says creature is obscured but player has electroreceptors mutation, one way or another (always "sense a creature" blobs, never blobs or how it is now but by design rather than coincidence)

### Steps to reproduce

1. Spawn player + gun(attach a scope) + mutate electroreceptors.
2. Spawn a few `zapper zombie`s in circular pattern 15-20 tiles away from the player .
3. Set to night time, or otherwise hide zappers from normal view.
4. You should see zappers as a tile because of the mutation.
5. Start aiming at a monster, observe how zappers at edge of aiming FOV cone turn into generic "sense a creature" blobs.

### Expected behavior

Judging by sentiment from others electroreceptors should work independent of aiming FOV.

Alternatively dependent on aiming FOV but by-design, not by coincidence.

### Screenshots

Demonstration video, see how zappers in lower right turn into blobs as aiming FOV narrowing blocks them out

https://user-images.githubusercontent.com/6560075/180326504-569ae5b7-3ce6-4c16-981c-d27c403f85b5.mp4

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 0.F-10043-g2b29aca4b8-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
I'd argue that the concentration involved in aiming should filter out detailed sensory input from outside of that area, unless the functionality comes with an expanded brain functionality allowing it to process more information concurrently than a normal brain.
I agree this should be by design rather than accident, though.

**Comment by RelMayers** [comment]
Can you check if its issue with how tileset works or if its general issue affecting ASCII as well?
