### ISSUE TITLE
Removing vehicle parts from wrecks can return items from another vehicle

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#59489]
### Describe the bug

I've encountered a wreck with two (or more) vehicles joined together.

When trying to disassemble parts from one (the luxury RV), components from the other (Armoured Car) are returned.

### Steps to reproduce

1. Load the attached save.
2. Take note of the items at your feet
3. `e`xamine the wrecked to the NW
4. Remove the washing machine (about half-way down on the left hand side)
5. Observe that after removal the vehicle screen for the Armoured Car is shown
6. Observe the new item at your feet is not the remains of a washing machine, but something like a steel plating or other item from the Armoured Car.

### Expected behavior

Removing parts from a vehicle gives you the part you removed, not something from a different vehicle.

### Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-10057-ga480687c68 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    No Hope [no_hope],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]
```

Game version is `cdda-experimental-2022-07-21-0520`, with my pending PRs applied, and a few JSON edits that have nothing to do with vehicles.

### Additional context

I'm using 'No Hope', but don't believe this is a No Hope bug.

Probably related: #53862

- [Download save file](https://github.com/CleverRaven/Cataclysm-DDA/files/9164237/CarBugSave.zip)

**Comment by Terrorforge** [comment]
Can confirm. I noticed this a month or two ago, but I forgot to make a report. Was trying to removed the intact battery from one of the wrecked cars, but I just kept getting scrap and various bits of the other car.

**Comment by irwiss** [comment]
I couldn't find the washing machine NW of saved spot in the attached save

The only washing machine i found grapping save files was at overmap coords 9.95.0, no armored car anywhere near it

If someone has a save that replicates this do attach as it'll make finding the bug much easier
