### ISSUE TITLE
Aiming is broken

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#59492]
### Describe the bug

Before [Cataclysm-DDA experimental build 2022-07-22-0211](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-22-0211) I can see my current hit chance, which are increasing when I am pressing "."
After this update I cannot. And it VERY uncomfortable, becouse I dont know, can I shoot enemy or not

I have also two videos, but I dont know, how to upload it becouse of 10 mb of file limit, if you show me, how to do it - I will do it

### Steps to reproduce

1. Load [Cataclysm-DDA experimental build 2022-07-22-0050](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-22-0050)
2. Make with debud meny any gun, find enemy, press f (fire wielded weapon), than press "." ("to steady tour aim")
3. See your current hit chance
4. Load [Cataclysm-DDA experimental build 2022-07-22-0211](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-22-0211)
5. Make the same steps
6. See only default hit chances, not current
7. Pray to the god of aim and cry

### Expected behavior

I want to know, can I shoot this dead punks or not

### Screenshots

On the screenshots below I pressed steady aim button "." about ~ 16 time on bouth screens, but the difference in hit chance is big
And you can see on first screen "curent aim", which are VERY usefull in game
Before [Cataclysm-DDA experimental build 2022-07-22-0211](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-22-0211)
![image](https://user-images.githubusercontent.com/102726167/180369383-e866d5b6-0219-4708-a8f4-19421579cbca.png)
After
![image](https://user-images.githubusercontent.com/102726167/180369772-821fc9a9-e22d-4045-af86-dc009bf970ea.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 7fe8d5b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by KHeket** [comment]
I think problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/59408
@irwiss 
Is the removing "current aim" a bug or a new feature? Becouse if it is new feature - it is a worsening of aiming and game process, becouse now its began very hard to shoot in close range combat

**Comment by irwiss** [comment]
No, aiming is still broken, but now in a different way 🤦‍♂️

I think i skipped the . spamming in my playtesting, usually not how i use guns, but I can see why you'd want it 

I'll work on it soon, unless someone gets to it faster

**Comment by Terrorforge** [comment]
I don't think the videos will be necessary this time, but the best way to upload them is probably to put them on YouTube or a similar site. You can make them unlisted so they don't show up in searches or on your channel

**Comment by pjf** [comment]
Oh yay! . spamming is the majority of my gun usage, and I am *so glad* to hear it has changed.
