### ISSUE TITLE
Cataclysm-DDA failed to build with "error C3861: 'ReadAcquire8': identifier not found" with MSVC on Windows arm64

### ISSUE THREAD

**Issue by YangYang129** [CleverRaven/Cataclysm-DDA#59493]
### Describe the bug

Cataclysm-DDA failed to build with "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8078,19): error C3861: 'ReadAcquire8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]" with MSVC on Windows arm64. It can reproduce on latest version on master branch. Could you please help look at this issue?
**Error info:**
```
8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8078,19): error C3861: 'ReadAcquire8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8089,19): error C3861: 'ReadNoFence8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8100,21): error C3861: 'ReadAcquire8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8111,21): error C3861: 'ReadNoFence8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8134,5): error C3861: 'WriteRelease8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8147,5): error C3861: 'WriteNoFence8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8160,5): error C3861: 'WriteRelease8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8173,5): error C3861: 'WriteNoFence8': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
     8>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(8198,20): error C3861: 'ReadAcquire16': identifier not found [F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64\src\cataclysm-tiles-common.vcxproj]
```
**Error log:**
[Cataclysm-DDA_build_error.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9165246/Cataclysm-DDA_build_error.log)
patch log:
[Cataclysm_DDA_bug1558519.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9165279/Cataclysm_DDA_bug1558519.log)
[Cataclysm_DDA_arm64_C3861_C2065.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9165280/Cataclysm_DDA_arm64_C3861_C2065.log)
[Cataclysm_DDA_runtest.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9165281/Cataclysm_DDA_runtest.log)
[Cataclysm_DDA_overmap_test.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9165282/Cataclysm_DDA_overmap_test.log)

### Steps to reproduce

1. open x64 native tools command prompt for VS 2019
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
4. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent\_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_arm64_c3861_c2065.patch
5. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent\_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_bug1558519.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
6. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent\_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_overmap_test.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
7. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent\_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_runtest.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
8. cd F:\gitP\Microsoft\vcpkg
9. bootstrap-vcpkg.bat 2>&1
10. vcpkg.exe install --recurse zlib sdl2 sdl2-ttf sdl2-image --triplet arm64-windows --clean-after-build 2>&1
11. F:\gitP\CleverRaven\Cataclysm-DDA
12. mkdir build_arm64 & cd build_arm64
13. cmake -G "Visual Studio 16 2019" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows -DCMAKE_BUILD_TYPE=Release -DCURSES=OFF -DLOCALIZE=OFF -DTILES=1 -DBUILD_TESTING=OFF .. 2>&1
14. set PATH=C:\tools\msys64\usr\bin;%PATH%
15. set _CL_=/permissive-
16. msbuild /m /p:Platform=arm64 /p:Configuration=Release CataclysmDDA.sln /t:Rebuild

### Expected behavior

I expected build fine and does not error

### Versions and configuration

OS: win10
VS: Visual Studio 2019(16.11.11)

**Comment by ZhilkinSerg** [comment]
Did you try to use solution file instead of using cmake? Is it working for you?

**Comment by YangYang129** [comment]
@ZhilkinSerg display "EXEC : error : yasm:arm64-windows-static@1.3.0#3 is only supported on 'windows & !uwp & !arm' [F:\gitP\CleverRaven\Cataclysm-DDA\msvc-full-features\Cataclysm-lib-vcpkg-static.vcxproj]" with using solution.
**step:**
1. open x64 native tools command prompt for VS 2019
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
4. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent\_work\12\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_add_arm64_sln_vcxproj.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
5. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_bug1558519.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
6. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_overmap_test.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
7. git -C "F:\gitP\CleverRaven\Cataclysm-DDA" apply f:\agent_work\21\s\src\qa\suites\oss\patch\cataclysm_dda\cataclysm_dda_runtest.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
8. cd F:\gitP\CleverRaven\vcpkg
9. git rev-parse --git-dir 2>&1
10. git clean -xdf 2>&1
11. git fetch --recurse-submodules=no --force 2>&1
12. git reset --hard 61a704c 2>&1
13. .\bootstrap-vcpkg.bat -disableMetrics
14. .\vcpkg integrate install
15. cd F:\gitP\CleverRaven\Cataclysm-DDA
16. mkdir build_arm64 & cd build_arm64
17. msbuild /m /p:Platform=arm64 /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64 /t:Rebuild 
Error log:
[Cataclysm_DDA_sln_error.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9177167/Cataclysm_DDA_sln_error.log)
**patch log:**
[Cataclysm_DDA_add_arm64_sln_vcxproj.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9177169/Cataclysm_DDA_add_arm64_sln_vcxproj.log)

**Comment by akrieger** [comment]
The problem is that the dependencies of the project rely on `yasm`, which is a third party assembler, which does *not* support emitting `aarch64` assembly. It might be possible to have a stripped down version of the game that'll run on windows arm64, but I don't know exactly what would have to get cut to allow that to happen.
