### ISSUE TITLE
Please add better visualization for running/crouching/prone state in RetroDays tileset

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59494]
### Is your feature request related to a problem? Please describe.

Currently if you use UltiCa tileset, you get a visual indicator when the character is running/crouching/prone directly on the character icon (arrows in bottom right corner of the sprite).

However there is no such indicator in RetroDays tileset, and as a result it is very easy to forget that you are running, run out of stamina and receive 3 hours worth of pain (and die if it happened at a bad time).

### Solution you would like.

Arrow indicators that are used in UltiCa would be an ideal solution, but if that's not possible any improvement at all is welcome.

### Describe alternatives you have considered.

If the UltiCa-like arrow indicator is not possible, maybe character sprite could change its color.
Or have a couple of differently-colored pixels on the character sprite.

### Additional context

Game version: cdda-linux-tiles-x64-2022-07-05-2300
Mod list: default

**Comment by Fris0uman** [comment]
Should probably open this issue in the tileset repo instead https://github.com/I-am-Erk/CDDA-Tilesets

**Comment by x-qq** [comment]
Done https://github.com/I-am-Erk/CDDA-Tilesets/issues/1456

**Comment by anothersimulacrum** [comment]
Issue opened in relevant repo.
