### ISSUE TITLE
Vehicle Deconstruciton Zone work stops when one of multiple vehicles is finished

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59497]
### Describe the bug

If you've got 4 1x3 bicycles in a 4x3 vehicle deconstruction zone, the player, (and likely NPC's), will stop deconstructing once every bicycle finishes.

### Steps to reproduce

Align multiple bicycles in zone, deconstruct.

### Expected behavior

Keeping on, keeping on.

### Versions and configuration

Win 10, Tiles, 42a7fde 

### Additional context

Does this also happen with multi-vehicle wreaks?  Not sure.

**Comment by PatrikLundell** [comment]
Duplicate of #57961.

I don't think it's a bug as such, but rather a missing feature (hence my feature request). And yes, I'd expect the modified wrecks to deal with it as a set of individual vehicles. I've never bothered with dismantling of those, however, as I've thought it to be a waste of time (smashing or towing being more time cost effective if you want their resources or get them out of the way).

**Comment by chrispikula** [comment]
Bicycles have extra light frames, and for boats, that's useful.  Bicycles are also easy to pick up, what with bike racks, and foldable variants.

**Comment by PatrikLundell** [comment]
Oh, I'm not saying dismantling is of little use: I build my base out of steel plating from vehicles towed back to my base... I'm saying dismantling wrecks is fairly useless. Sorry if I was unclear.
