### ISSUE TITLE
Health debug tools are outdated and insufficient

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59499]
### Describe the bug

The "Set health" command (debug->player->edit player/NPC->set health) only has two health values listed: Health and Health modifier. These do not match the new terminology as of #57331. Further, while I was able to figure out through much trial and error that "Health" corresponds to lifestyle and "Health modifier" to health_tally, there seems to be no way to view or modify daily_health.

It's possibly to view daily_health in debug mode, and this option does use the correct terminology. However, it only include lifestyle and daily_health, not health_tally. And as far as I've been able to figure out, you can only see it by activating debug mode and waiting until midnight for the health values to tick over.

e: I think I was wrong and "Health modifier" is actually daily_health. It's hard to tell

### Steps to reproduce

Open "set health" in debug.

Activate debug mode and wait until midnight.

### Expected behavior

Debug options use the correct terminology and allow the relevant values to be viewed and edited.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/180462973-6fe2128a-db28-4a3d-93d7-079799e78fe6.png)
![image](https://user-images.githubusercontent.com/5107449/180463907-83c91029-50a8-415d-97a8-085de983701c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 5301287 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by anothersimulacrum** [comment]
I don't think it's really worth tracking issues for debug features.

**Comment by Golfavel** [comment]
Being able to properly debug without having to invest a considerable amount of time just setting up I'd consider fairly important.

**Comment by anothersimulacrum** [comment]
Feature requests for the debug menu without an actual use case for development don't help with that.

**Comment by Terrorforge** [comment]
No use case..? It's basically impossible to test any aspect of the health system without being able to see and manipulate all three of these values.

If you want a specific example, what brought this to my attention was my health behaving bizarrely, first going up by 20+ points per day and then tanking mysteriously and seemingly irreversibly, and it took me hours to even begin to figure out that this is because daily_health decays too slowly when that would have been immediately obvious if there was an easy way to see that value

**Comment by anothersimulacrum** [comment]
The issue just states that you cannot see values and they have different names. That's not a use case. I understand it may seem a bit contrived, but for something like a feature request for debug features, without a specific use case (like the one just provided), there's really no reason to have an issue tracking it.

**Comment by kevingranade** [comment]
We don't track feature requests for debug functionality.
