### ISSUE TITLE
Exodii Quadruped becomes hostile against player if it self-damages with its electricity weapon

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#59495]
### Describe the bug

Was watching a Quadruped go to town on some zombies. The noise was attracting more and more of them.

By the time it used all the bullets and started using the arc weapon, some zombies got really close. The arcs of electricity damaged the quadruped and it got aggro against me.

### Steps to reproduce

1. Find/Spawn quadruped
2. Find/Spawn zombies. Keep on until it runs out of bullets
3. Spawn a zombie really close to it so it fires the weapon point blank. If it self-damages then-
4. RUN!

### Expected behavior

It should not become aggro against me when it self-damages. It's anger against the player should only occur if I actually did it.

I checked it's Anger Trigger flags in the Nornagon guide https://nornagon.github.io/cdda-guide/#/monster/mon_exodii_quad and I suspect the HURT flag indiscriminately makes the creature hostile against the player regardless of true guilty party.

I think dogs are also affected by this. I used to think it was because they associated zombies with the players and so got aggro by association (which is a neat simulation of animal behavior to me), but looking at the tags in:
https://nornagon.github.io/cdda-guide/#/monster/mon_dog
https://nornagon.github.io/cdda-guide/#/monster/mon_dog_bull        it seems they are also attacking the player due to this bug

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 072a7a3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

**Comment by PatrikLundell** [comment]
Creatures in a fight seem to attack everything that isn't friendly to them, and so you'd have to wait until they calm down after a fight before approaching them. Thus, I suspect you'd be attacked if you approached even if the quads hadn't been damaged.
As far as I understand it's a limit of the faction system.

**Comment by DamienRoyan** [comment]
> Thus, I suspect you'd be attacked if you approached even if the quads hadn't been damaged. 

No I've walked right up to one to smash the corpses as it walked towards them to "inspect" it's work

**Comment by PatrikLundell** [comment]
Interesting. Thanks for correcting my impression.
