### ISSUE TITLE
fake_char_kiln related error during character creation

### ISSUE THREAD

**Issue by LlubNek** [CleverRaven/Cataclysm-DDA#59508]
### Describe the bug

If character creation fails and you try again, the following message appears during character creation:
```
DEBUG    : Error: fake_char_kiln (struct itype) has two definitions from the same source (dda)!

FUNCTION : new_character_tab
FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
LINE     : 916
VERSION  : 072a7a3
```

Seems like things aren't being unloaded properly after erroring out.

### Steps to reproduce

1. Get the  latest experimental build (I'm using [cdda-windows-tiles-sounds-x64-msvc-2022-07-22-0807.zip](https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-07-22-0807/cdda-windows-tiles-sounds-x64-msvc-2022-07-22-0807.zip))
2. Create a world with some mod that errors out during character creation (anything old really, try BioCo from [Kenan's mod pack](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack))
3. Attempt to create a character and fail, returning to main menu
4. Create a world with default settings and mods
5. Attempt to create a character in this newly created world

### Expected behavior

no error

### Versions and configuration

Windows 10
[cdda-windows-tiles-sounds-x64-msvc-2022-07-22-0807.zip](https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-07-22-0807/cdda-windows-tiles-sounds-x64-msvc-2022-07-22-0807.zip)

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9171558/debug.log)

**Comment by PatrikLundell** [comment]
I get these kinds of spurious errors, usually after having edited some JSON file, where no issues were present prior to the editing (and the edits were completely unrelated to the complaint).
After it happens, you won't get rid of it by exiting the save and reloading it, but restarting the game usually gets rid of it.

I too suspect it's caused by caches that aren't cleared out properly.

**Comment by Drew4484** [comment]
> I get these kinds of spurious errors, usually after having edited some JSON file, where no issues were present prior to the editing (and the edits were completely unrelated to the complaint).
> After it happens, you won't get rid of it by exiting the save and reloading it, but restarting the game usually gets rid of it.
> 
> I too suspect it's caused by caches that aren't cleared out properly.

Same, I can reliably recreate this issue if needed.

**Comment by AmarinReyny** [comment]
> I get these kinds of spurious errors, usually after having edited some JSON file, where no issues were present prior to the editing (and the edits were completely unrelated to the complaint). After it happens, you won't get rid of it by exiting the save and reloading it, but restarting the game usually gets rid of it.
> 
> I too suspect it's caused by caches that aren't cleared out properly.

Where would these caches be? I had the same error after reinstalling everything in a new folder after stepping away from CDDA for a couple of months.

**Comment by PatrikLundell** [comment]
I'd expect them to be inside the game's memory, i.e. not a rogue file that could be deleted. My expectations are not always met, though...

**Comment by anothersimulacrum** [comment]
The game loads JSON objects into what it calls "factories" (generalisation). These are cleared in `DynamicDataLoader::unload_data()`, which is called before loading begins. When an object is loaded, before it is inserted into one of these factories, it checks if there is already an object with this id. If there is, it checks the mod that object was loaded from. If both objects are from the same mod, it throws the error shown here.

For some reason, if an error is thrown during loading (this is not a `debugmsg`, this is an error that halts loading), something goes wrong and the game gets confused, and it throws this error.

Note the generalisation - most objects use a class called `generic_factory` to do this, but certain ones, like items (itypes) and monsters, do not, they use their own equivalents. This may be the source of the issue.

**Comment by EIIKaO** [comment]
> I get these kinds of spurious errors, usually after having edited some JSON file, where no issues were present prior to the editing (and the edits were completely unrelated to the complaint). After it happens, you won't get rid of it by exiting the save and reloading it, but restarting the game usually gets rid of it.

I was annoyed this error too(when creating my crappy mod), came up with a solution (inspired by othersimulacrum's comment).
It has a simple PR(poor code changing)https://github.com/CleverRaven/Cataclysm-DDA/pull/59578 but it may needs to be reviewed by c++ experts and veteran C:DDA developers.

> I had the same error after reinstalling everything in a new folder after stepping away from CDDA for a couple of months.

Does it happen after a clean install of other recent builds?
