### ISSUE TITLE
Allow character starting age to be restricted by profession

### ISSUE THREAD

**Issue by pshepjr** [CleverRaven/Cataclysm-DDA#59511]
### Is your feature request related to a problem? Please describe.

Currently, the character's starting age is hardcoded to be between 16 and 55 as determined by the player upon creation. This leads to some oddities in some professions (the 'senior citizen' for example, that can start as a 16 year old). 

### Solution you would like.

If professions (and/or scenarios?) could restrict the selectable age, there could be more variety/flavor in character creation. 

This isn't exactly a huge problem, as obviously the vast majority of professions can feasibly be any age. However, I don't think there is ever anything wrong with more options for content creators.

Thanks!

### Describe alternatives you have considered.

Leaving it the way it is.

### Additional context

I do not know code so I am not sure how easy this is to do.

**Comment by ANickelN** [comment]
Does age even do anything?  If it doesn't, I don't see why not leave it how it is.

**Comment by pshepjr** [comment]
It affects character stamina, to my knowledge not anything else. I made a character at age 55 - they had a max stamina of 8273. I made another character at age 16 and they had 8858. I believe they both had indefatigable and athletics 1.

**Comment by TheShadowFerret** [comment]
~~What do you mean you can't be a Special Operator or Police Sniper at 16~~
