### ISSUE TITLE
Error on refill vehicle tank from water

### ISSUE THREAD

**Issue by CaseMonster** [CleverRaven/Cataclysm-DDA#59510]
### Describe the bug

 DEBUG    : error in activity data: "could not find target vehicle for liquid transfer"

 FUNCTION : void activity_handlers::fill_liquid_do_turn(player_activity*, Character*)
 FILE     : src/activity_handlers.cpp
 LINE     : 1480
 VERSION  : d291072

### Steps to reproduce

1. Park vehicle one tile from puddle
2. Have hose in inv
3. 'e' on water
4. 'fill vehicle'
5. Select tank to fill

### Expected behavior

Tank filled with water

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.25163.1000 (22H2)
- Game Version: d291072 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

**Comment by CaseMonster** [comment]
Bug was present in the exp build i was using from a few days ago.  Updated to current to check to see if bug was still present.

**Comment by hexagonrecursion** [comment]
Please post your save file. I have tried to replicate this bug, but could not. I did get a different debug message while trying to fill a humvee with salt water from a swamp:

```
 DEBUG    : tried to put an item (salt_water, amount 1) in a container (metal_tank) that cannot contain it

 FUNCTION : int item::fill_with(const item&, int, bool, bool, bool)
 FILE     : src/item.cpp
 LINE     : 11866
 VERSION  : 4abdbc8
```

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 4abdbc8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by CaseMonster** [comment]
Sorry for the delay.  I tried to replicate this several dozen times the last couple of days.  No luck...
