### ISSUE TITLE
Logging Camp manager does not take quest items

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#59526]
### Describe the bug

I did the first quest for the logging camp manager NPC, which is to bring him three drive belts. After bringing him these items and collecting my reward, I noticed that all three drive belts were still in my inventory. The quest was finished but the requested items were not taken.

### Steps to reproduce

1. Do the first quest for the logging camp manager.
2. See that he does not take the items he wants from you.

### Expected behavior

Quest items are handed over to the NPC.

### Screenshots

None.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 6a0d865 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

As quest reward, I chose to take some items, which was pretty much just wood in various forms. The stuff he trades is pretty voluminous, he possibly doesn't have the space to accept the items. (This is pure conjecture, I have no clue how this stuff works.)

**Comment by MNG-cataclysm** [comment]
Confirmed. I will fix this shortly.
