### ISSUE TITLE
Scenario monologue repeats on Loading a Save

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#59522]
### Describe the bug

The scenario monologue repeats itself on loading a Save.

On noticing this, I save-quit 2 times and loaded the save again. The message stacked up x3, and I assume it would keep doing this. Nothing else seems out of the ordinary

Possible fallout of #59490

### Steps to reproduce

1. Load an old save, or start a new save, quit from it and load it again. That's it

### Expected behavior

Should not appear at any time other than when you start the character

### Screenshots

![image](https://user-images.githubusercontent.com/88375697/180589945-5d851365-9a90-4fbd-a2cd-18b49936b30c.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: d291072 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Zireael07** [comment]
Actually I wouldn't mind it staying... the way it was currently means players quickly forget their character's backstory.

**Comment by DamienRoyan** [comment]
But it would

1. It does not make sense with certain backstories. Why would my character monologue about the shelter I had already left last season. And what about backstories like Last Delivery. I've already made the delivery. What's it talking about.

2. It looks bugged to those who don't know it's "supposed to be like that"

3. You're either doing survivor, trying out other backstories to get a feel of them, or doing specific roleplay which isn't easy to forget.

**Comment by RelMayers** [comment]
IMO it's not a big issue, maybe different message for loading rather than starting one might be nice.

**Comment by EIIKaO** [comment]
I made this bug.

My bad I tested only with new game and did not try with load game. 
It seems like an easy fix. I'm Testing now and I will PR the fix if possible.

**Comment by DamienRoyan** [comment]
Oh that would be wonderful

After a season it would say something like "The seasons have changed, but the world isn't much different. Still doomed"

After a year it would say "It's been a year since I was forced into this chaos. I feel changed by it. And I'm not sure how to feel about it"

**Comment by DamienRoyan** [comment]
> I made this bug.
> 
> My bad I tested only with new game and did not try with load game. It seems like an easy fix. I'm Testing now and I will PR the fix if possible.

It's alright. Bugs always appear when you least expect them. And also when you most expect them.... They appear.

**Comment by RelMayers** [comment]
Well IMO this thing could be considered a feature, I think for some scenarios a text on start is fitting for a text for load.

**Comment by ANickelN** [comment]
Fixed by #59525
