### ISSUE TITLE
(Occasional) Batch Crafting of Rubber Cement destroys Liquid Ammonia despite adequate skill and no crafting-mistake message

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59539]
### Describe the bug

Sometimes, usually when doing a batch, Rubber Cement will destroy the Liquid Ammonia in the same way as with messing up a recipe. However, my characters skills are not so inadequate that this would actually be from a mess-up, and there is no log indication of messing up.

As said, this usually happens with a batch. I noticed this the first time with 20 Rubber Cement, the second time with 2, and right after I did the 2, trying single batches also destroyed the ammonia. Other times it did not in single batches. I am not sure if I have successfully done a multiple batch of Rubber Cement without destroying the liquid ammonia.

### Steps to reproduce

I'm not entirely sure, as it doesn't reproduce all the time in my own game world, and debugged-in liquid ammonia tanks worked. 

But, uh...

1. Get a UPS Food Processor and UPS Chemistry Set, put outside of inventory.
2. Put UPS in inventory.
3. Put liquid ammonia (and other ingredients) outside of inventory.
4. Try to do a batch craft of at least 2 Rubber Cement.
5. Hopefully fuck up?

### Expected behavior

I expect that if there is a skill issue, that it would display. Otherwise, I expect my character to be able to create rubber cement without destroying the item, as with every other crafting of similar skill requirements met.

### Screenshots

First image is the crafting display, showing no skill notices. 
Second image is the log, showing no "You made a mistake!" message.
Third image is the location of the liquid ammonia tanks.
![image](https://user-images.githubusercontent.com/4212389/180622337-1e1ee543-d35f-412c-8f6e-37229a990320.png)
![image](https://user-images.githubusercontent.com/4212389/180622353-afc3dca2-de63-4c7e-8314-ff66c113841a.png)
![image](https://user-images.githubusercontent.com/4212389/180622404-749316af-ef91-49e3-9f89-ee43dd6ca15f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: b86bfea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

Other potential caveats:
The crafting takes place on a placed furniture workbench in a Light Industry structure that is just 1 OMT north of a player-faction Basecamp.
The liquid ammonia are in tanks found from a hidden lab, and they are not on my character - they're on a display rack 4-5 tiles to my east.
The chemistry set and food processor are to my north, are UPS modded, and are running off a UPS in my inventory.
I debugged in some liquid ammonia to replace this, and both the batch and single-craft In Progress items then would work. I am not sure why this is.

**Comment by descan** [comment]
I believe this might be related either to the recent ammonia changes, and/or to something about the liquid ammonia not being allowed to exist outside of the tank. I'm not sure though, because this isn't consistent, and sometimes it works and sometimes it doesn't.

**Comment by Bulletfang** [comment]
Also happens with batch crafting mutagen, just eats your liquid ammonia, very annoying bug, considering that stuff is a lot more rare now.

**Comment by RenechCDDA** [comment]
I can reproduce this reliably - it only ever destroys ammonia at the start. Continuing an in progress craft, even from 0%, does not destroy the ammonia.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/liquid-ammonia-evaporating-while-cooking-mutagen/28503/2
