### ISSUE TITLE
New nitric acid recipe 

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#59531]
### Is your feature request related to a problem? Please describe.

there are a lot of uses for nitric acid (and some acids you can make from it) but all the recipes to make it require a fair amount of precursors, whereas nitric acid can be made IRL with high voltage electricity, air, and water  

### Solution you would like.

a new recipe for dilute nitric acid using a makeshift nitric acid machine, similar to the ones added for ammonia recently, and potentially the ability to distill into fuming nitric acid if that's required

### Describe alternatives you have considered.

Continuing having to always hunt for chemical precursors and pray to RNG

### Additional context

[Video showing a makshift machine that outputs nitric acid from air and water](https://youtu.be/HN6tv7NKtPk)

**Comment by kevingranade** [comment]
If you do the math on this the yield are incredibly poor and really not worthy pursuing in the context of dda.
