### ISSUE TITLE
Container insert interface issue and suggestion.

### ISSUE THREAD

**Issue by tim110011** [CleverRaven/Cataclysm-DDA#59549]
### Describe the bug

The auto-assign number shortcut in the container insert interface conflicts with picking up x items.

### Steps to reproduce

1. Try use a container to insert x items.
2. The auto-assign number shortcut conflicts with picking up x items, even "Options->Interface->Auto inventory letters" is Disable.

### Expected behavior

Suggestion:
1. Do not auto-assign any type shortcut.
2. Or do not use number keys for item shortcut.
3. Add option: [disable in any interface] in "Options->Interface->Auto inventory letters"
4. "Container insert interface" and "Pickup interface" should consistent: prompt keybinding, length, weight, volume.
5. Shortcut keys, key bindings and display should be clear and unified. see https://github.com/CleverRaven/Cataclysm-DDA/issues/58846

### Screenshots

![cdda_container_insert_issue](https://user-images.githubusercontent.com/8690917/180629080-ebc56208-fd3b-459c-a9d7-7835c6cf585d.jpg)

### Versions and configuration

OS: Fedora Linux 36
Game Version: eb4bede0355d78f5a6595986115de11c6c135cc5
Graphics version: Tiles
Ingame language: Chinese (Simplified)
Mods loaded: dda, no_hope, no_fungal_growth, speedydex, translate_dialogue

**Comment by rgehlen** [comment]
It's possible to bind `Mark a specific amount of selected item (标记所选物品特定数量) `in that menu to a key in case you didn't know.

**Comment by tim110011** [comment]
> 

There is no prompt "[?]", how possible could i known?

**Comment by anothersimulacrum** [comment]
It should be safe to assume `?` works in every single menu, but it's a bug regardless that the keys conflict.
