### ISSUE TITLE
mi-go guardian should not move away from his tower.

### ISSUE THREAD

**Issue by mora145** [CleverRaven/Cataclysm-DDA#59545]
### Is your feature request related to a problem? Please describe.

The guardian mi-gos tend to run behind the player and move too far away from their tower, which makes them easily distractible and usable to attack other monsters by directing them at them.

### Solution you would like.

The mi-go guards should not go more than 30 - 50 meters away from your tower. This will allow you to do your job of guarding the tower.

### Additional context

![Screenshot_18](https://user-images.githubusercontent.com/25883820/180629002-bc6d1ccc-f98a-4861-abb8-45d0b97d20f1.jpg)

![Screenshot_19](https://user-images.githubusercontent.com/25883820/180629010-753eb168-52d0-4a8e-84ff-adcddf8c1c5e.jpg)

**Comment by anothersimulacrum** [comment]
Could probably add a patrol like https://github.com/CleverRaven/Cataclysm-DDA/pull/59067

**Comment by mora145** [comment]
> Could probably add a patrol like #59067
Yes, I think that would solve it.
