### ISSUE TITLE
Health Stat maxes out and only tends towards -200, regardless of healthy habits and Health Modifier.

### ISSUE THREAD

**Issue by HatRat** [CleverRaven/Cataclysm-DDA#59547]
### Describe the bug

After seriously decreasing the health of a character due to faulty bionics, radiation and addictions, the health does not improve in any way, only staying at the maxed out -200 or further decreasing regardless of the healthy habits to improve it.
Even after using the debug menu to check the stats, and manually set the health stat to 0, while having a positive health modifier, no radiation, leaky bionics, diseases (besides a broken leg), mutations, addictions, or unhealthy food, the health itself would still only decrease, and drastically so. 
After about two-three days starting with 0 Health and -55 Health, doing nothing but reading, eating apples and clean water, exercising and sleeping, the stats would become -84 Health and +17 Health modifier. After spending one more day with the same routine, the new stats became -153 Health and +21 Health modifier, indicating that even within 24 hours, the Health drastically decreases despite the positive Health modifier increasing, without any radiation. (In relation to the save file, this happened to the character named "Tuque".
[manual_backup.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9174905/manual_backup.zip)

### Steps to reproduce

(Note, I only passively noticed the problem with my stats, and used the debug menu to change and test them out. I can't determine what were the actions that precisely caused it, so the following steps are just a general description of all the things I did up to that point and the testing process, and might not be able to be reproduced with the same effects.)

1. Make Prototype Cyborg in Lab start with Alcohol, Opiate and Nicotine addiction.
2. Spend some time (about 20-25 days) trying to extract various faulty bionics and overall survive. (taking rests to recover from failed attempts).
3. Get exposed to radiation from the Radiation leak bionic (and some slight outside sources), but keep it in check with the Autodoc administered Prussian Blue (never surpassing 120 mSv).
4. Get a leg broken in the process of removing bionics, and get it patched by the Autodoc.
5. Catch the common cold in the meantime.
6. After Finishing the removal of all bionics, spend around 5 days doing nothing but light activity like reading, crafting, resting, Exercise daily on a training machine, and eat relatively healthy (forest honey, candied honey, meat confit and other stuff, but nothing that had a - to health). Recover from the cold and radiation, but notice no improvement at all in the leg during this time.
7. After those 5 days with no sight of improvement, check the debug menu for the health stat.
8. Notice -200 in health, -55 in health modifier and 0 radiation.
9. Change the stats so that it has 0 health.
10. Spawn in apples.
11. Continue spending the next 2-3 days with the same healthy routine of eating healthy apples, exercising and resting.
12. After those days have passed, check the debug menu again and notice -84 health and +17 health modifier.
13. Spend one more day with the same routine.
14. Check the debug menu again and notice -151 health and +21 health modifier.

### Expected behavior

I expected the Health to slowly tend towards an equilibrium with the Health modifier once there were no more factors to decrease it, or at least not to decrease drastically even after the health modifier reached positive values.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: b86bfea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
This is essentially the same as #59505. It appears the debug info is out of date as well (#59499).

**Comment by Terrorforge** [comment]
To reiterate what I said in those threads: daily_health, the value that changes health_tally, does not reset at the end of the day, it only decays slowly. I'm pretty sure "Health modifier" in the debug menu is health_tally. This can lead to a surd results, particularly in testing, because even if you set health_tally to 0, you may still have like a -79 daily_health, which will make health_tally negative again and cause you to keep losing health.
