### ISSUE TITLE
thick and thin skinned doesnt work correctly

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#59554]
### Describe the bug

thick skinned and thin skinned armor doesnt work correctly

### Steps to reproduce

tested by adding bullet protection 999 to thick skinned and got shot from corws and died

### Expected behavior

instead of     "armor": [ { "part_types": [ "torso", "head", "arm", "hand", "leg", "foot", "mouth", "tail" ], "cut": 1, "bash": 1 } ]

it needs to be "armor": [ { "part_types": [ "torso", "head", "arm_l", "arm_r", "hand_l", "hand_r", "leg_l", "leg_r", "foot_l", "foot_r", "mouth", "tail" ], "cut": 1, "bash": 1 } ]

excluded eyes didnt tested with tail so i dont know if it works correctly

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 85de01c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by sonphantrung** [comment]
Wait, I thought Thick/Thin skinned got removed?
