### ISSUE TITLE
you cannot place workbench with battery charger

### ISSUE THREAD

**Issue by SSDar** [CleverRaven/Cataclysm-DDA#59551]
### Describe the bug

you can place a workbench in the construction menu, but if you craft a workbench with a battery charger there is no option to place it in the construction menu

### Steps to reproduce

1. craft workbench with battery charger
2. try to place it

### Expected behavior

that i can place the workbench with a battery charger

### Versions and configuration

none

### Additional context

none

**Comment by chrispikula** [comment]
Are you attempting to place it in a vehicle, on a frame?  What version?

I used it today, in 42a7fde , in my vehicle.

**Comment by SSDar** [comment]
> Are you attempting to place it in a vehicle, on a frame? What version?
> 
> I used it today, in [42a7fde](https://github.com/CleverRaven/Cataclysm-DDA/commit/42a7fded3aaa2d7bda48f2b3cab3b947b8229187) , in my vehicle.

i am attempting to place it on the ground like the normal workshop does, so i can use it in my evac shelter base
yes i am aware it works as a vehicle part

**Comment by Zourin2** [comment]
can confirm the lack of a construction menu option for this peice. It may be vehicle only.

**Comment by magnoliadhole** [comment]
I just ran into this issue. Workbench has a construction menu item, but workbench with charger does not.

**Comment by PortlyAssassin** [comment]
Same issue, current experimental.
