### ISSUE TITLE
"Transform item when charges = 0" flag

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#59552]
### Is your feature request related to a problem? Please describe.

Somehow i found the game has lack of way to transform item to another item, when it has no charges (or just after some activity)
Lest see an example:
A `TOOL`, that `use_action` `cast_spell`, and then must be deleted
first attempt: using `max_charges` 1 and `initial_charges` 1
result: item has 0 charges, but do not transform
![image](https://user-images.githubusercontent.com/67688115/180641722-40e24a27-5488-4fd3-8250-80ee71e1a587.png)
second attempt: adding `use_action` `transform`
result: the item got shiny new "turn on" button. It doesnt activates when charges are 0 tho, so player need manually delete it, which is, you know, weird
![image](https://user-images.githubusercontent.com/67688115/180641932-a9176713-32f9-47d1-939f-9a7c937c9208.png)
third attempt was with using the `ammo` field, and another stuff for this like `pocket_data`
it also doesnt work, but i lost my screenshot

Upd: i found this json combination:
```json
    "use_action": { "type": "countdown", "name": "Unroll", "message": "You unroll the dragon scroll…" },
    "countdown_interval": 1,
    "countdown_destroy": true,
    "countdown_action": { "type": "cast_spell", "spell_id": "learn_ki_strike", "no_fail": true, "level": 0 }
```
It kinda works, it allows me to delete the item after casting the spell, but  it has 1 second delay between using and casting when uses it in hands, and it aslo do not support another actions

### Solution you would like.

A flag `TRANSFORM_AFTER_DISCHARGE`, that will use `revert_to` when initial item has no charges
maybe also flag `DELETE_AFTER_DISCHARGE`, to prevent dirty tricks with transforming to gas to delete an item

### Describe alternatives you have considered.

🤷 
Maybe `use_action` boolean to not show the picked action, so it will be possible to use `"ammo_scale": 0` with different actions. Maybe its even better comparing to flag
### Additional context

I was surprised the game has no flag for such small things already

**Comment by Sathra225** [comment]
Related to this, the torches don't change into the burnt out version either.

**Comment by catdach** [comment]
JSON_INFO.md has this field under use_actions:
```
    "ammo_scale": 0,    // For use when an item automatically transforms into another when its ammo drops to 0, or to allow guns to transform with 0 ammo.
```
Which sounds like it's what you're looking for. This is used by things like flashlights and candles.

**Comment by GuardianDll** [comment]
I was not able to use it without making a new action button, the result described on "second attempt"
