### ISSUE TITLE
HELMET_COMPAT flag doesn't seem to do anything

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#59566]
### Describe the bug

I'm not exactly clear how the [HELMET_COMPAT](https://github.com/CleverRaven/Cataclysm-DDA/blob/eb4bede0355d78f5a6595986115de11c6c135cc5/doc/JSON_FLAGS.md) flag is supposed to work, but the documentation indicates it's supposed to allow the flagged item to be worn with a helmet. However, this flag appears to get overridden by the material rigidity system.

Out of the [flagged items](https://nornagon.github.io/cdda-guide/#/json_flag/HELMET_COMPAT), this issue is most common with chainmail. Despite the text description and the flag, you can't wear a chainmail coif with a helmet (tested with "chainmail coif + army helmet", "shark suit + tactical helmet", etc.). This is related to [#53259](https://github.com/CleverRaven/Cataclysm-DDA/issues/59259).

The flag also causes some oddities that don't fully make sense with the new encumbrance/rigidity system, like how great helms can be worn with other helmets ([#28554](https://github.com/CleverRaven/Cataclysm-DDA/pull/28554))

### Steps to reproduce

1. Wear any "rigid" HELMET_COMPAT item
2. Try to wear a helmet
3. Fail

### Expected behavior

With the new material rigidity system, I'm not sure what the purpose of the HELMET_COMPAT flag is supposed to be now. It might be obsolete.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: fc73b64 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by descan** [comment]
Relatedly, non-rigid items that *say* they can be worn with a helmet (like the Hub01 Env. Suit) will still interfere with helmets - like the Tactical Helmet. Considering most helmets are Normal layer, and additional encumbrance from interfering on the same layer with non-rigid items seems to be the only real issue with wearing two items on the same layer, then the fact that HELMET_COMPAT doesn't actually do away with that interference makes me question what the whole point of it is, as it doesn't seem to be doing anything else.

**Comment by bouchacha** [comment]
Thank you for pointing that out, it's not clear that the flag does anything at this point. I'm going to edit the title as the issue seems bigger than just rigidity
