### ISSUE TITLE
Starting Professions should list if they start with Missions

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59567]
### Is your feature request related to a problem? Please describe.

I had no idea that some starting professions start with missions, and I've been playing for *years.* 

### Solution you would like.

On the Professions tab, where it lists all your starting guff, it should at least say "Starts with a mission," if not explicitly saying what the mission is.

### Describe alternatives you have considered.

Not do this? It seems a bit of waste to not notify people that there's more to the choices they're making than what's on the box.

### Additional context

![image](https://user-images.githubusercontent.com/4212389/180662287-64a82674-2cd8-4f2b-b314-8b2747a12a4e.png)
![image](https://user-images.githubusercontent.com/4212389/180662320-61e0a630-326e-4b9d-92b7-afd15aae3c2f.png)

**Comment by ZeroInternalReflection** [comment]
It looks like this is a pretty simple code change:

![Profession_missions_test--English](https://user-images.githubusercontent.com/89038572/180681408-8d0baf5a-a6af-4069-b35e-d5da7e000f84.png)

![Profession_missions_test--Japanese](https://user-images.githubusercontent.com/89038572/180681414-a3affa16-53b1-40b9-a123-33fe4dcf2c5d.png)

I'm in the middle of trying to tidy that entire UI screen right now, so I'd prefer to include this change there or to PR it afterwards.  If 
my rework drags on much longer I'll split it off.

**Comment by Termineitor244** [comment]
You haven't seen the starting missions because most of them were added in #57600, just 3 months ago, but I hope you like them!

**Comment by descan** [comment]
> You haven't seen the starting missions because most of them were added in #57600, just 3 months ago, but I hope you like them!

Aha, that would explain it! It's a neat thing, it adds some interest in taking other classes you wouldn't otherwise, just thought they should be noted on the char gen screen! Thanks for adding them!
