### ISSUE TITLE
Immediate aiming mode displays incorrect values

### ISSUE THREAD

**Issue by in-F** [CleverRaven/Cataclysm-DDA#59564]
### Describe the bug

Increasing steadiness doesn't affect the percentage display of immediate aim. Only a visual issue, the action will complete with the expected accuracy.

### Steps to reproduce

1. Target an enemy
2. Increase steadiness
3. Displayed values are not impacted by steadiness.

### Expected behavior

Percentage values should adjust based upon steadiness.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1766 (20H2)
- Game Version: c2b61d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key]
]

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/59492

Likely fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/59512 (please playtest if you're able to compile ☺ )
