### ISSUE TITLE
[No Hope] Mine is overflowing with loot

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#59579]
### Describe the bug

I'm playing the excellent *No Hope* mod by @Night-Pryanik, and while everywhere has been broken down cars and ramshackle houses, the mining site (`mine entrance`) and associated carpark I've found have been absolutely overflowing with loot.

Two heavy vehicles in near-working condition, fully stocked offices with an endless supply of pens, quarters with folks who have been collecting permanent markers and friendship bracelets by the dozen. I didn't just find my first pair of scissors after weeks of in-game looking, I found multiple scissors and *sewing kits*. It's a *lot* of loot.

I'm happy if this is as-intended. The mine has a big fence and maybe hasn't been looted like everything else, but it is a bit of a change of pace from the rest of the mod.

### Steps to reproduce

1. Start a game with the No Hope mod
2. Find a `mine entrance`
3. Check out that loot!

I've attached a save file of my current game, with my character standing in the mine site.

### Expected behavior

Mining sites are just as ruined as everything else.

### Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-10147-gc0a38cdce7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    No Hope [no_hope],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]
```

### Additional context

- <s>Save file: [NoHopeMiningSite.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9177778/NoHopeMiningSite.zip)</s>
- Actual save file: [NoHopeMineLootForReal.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9186139/NoHopeMineLootForReal.zip)

**Comment by Night-Pryanik** [comment]
First of all, thanks for kind words.

https://github.com/CleverRaven/Cataclysm-DDA/blob/4abdbc8eec0c78c111aa6c37bda485c4d8a81051/data/mods/No_Hope/Mapgen/mine_entrance.json#L111-L142

As you can see in code snippet above, the chances to spawn most stuff is only 20%. Only a handful of items have 50% chance to spawn (trash) and 80% (silverware, knives and dishes). So this might just be RNG messing with item spawn. What's your world item spawn modifier, btw?

Mine uses SUS-style item groups, which, as claimed, are trying to represent "realistic" item distribution. I didn't create them, so I can't say why are there so many items in item group definition.

ALL cars in the mod are guaranteed to spawn in "disabled" condition. But sometimes they spawn in more "working" condition than others. Near-working car is just RNG. Sometimes you're just lucky to find a car in this condition.

Finally, mines ain't supposed to be locations which looters would be interested in. So it shouldn't be a surprise that offices are full of pens, permanent markers, or scissors.

**Comment by pjf** [comment]
> First of all, thanks for kind words.

♥

> What's your world item spawn modifier, btw?

It's set to 1, which I believe is the default.

Looking at the JSON for the No Hope mapgen, I see:

`      "gaspumps": { "@": { "fuel": "gasoline", "amount": [ 0, 5000 ] }, "$": { "fuel": "diesel", "amount": [ 0, 5000 ] } },`

If I recall correctly, there's 1000 fuel to a litre, so I'm guessing this line gives each pump anywhere up to 5L of fuel.

However in the save attached there's almost 42 litres of diesel (I might have moved some to a jerry-can next to the pump), and there's a similar amount of gas in the other pump. Am I reading things wrong, or are at least the gas pumps clearly out here?

**Comment by Night-Pryanik** [comment]
If this your _old_ world? I teleported underground of this particular mine, and there is some weird stuff happening on.
![изображение](https://user-images.githubusercontent.com/11132525/180700073-4c4b85f8-5593-48a1-a2f3-b0c5b4ed5bab.png)

This big-empty-rooms mapgen are feature of old hardcoded mines. They were removed from the game in April, in #56555.

**Comment by pjf** [comment]
OH SHOot! I included the wrong save!! I am *so sorry*!

Here's the actual save:

[NoHopeMineLootForReal.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9186135/NoHopeMineLootForReal.zip)

**Comment by Night-Pryanik** [comment]
Well, the situation is the same: the amount of loot might be huge, but mostly it's low-level loot you _expect_ to find in this location even after the apocalypse since it has low interest for marauders.

**Comment by pjf** [comment]
I'm happy to close this if it's working as intended with the actual correct save, but the amount of loot (and 40+ litres of fuel in each pump!) felt like it was using the default loot gen rather than the No Hope loot gen.

**Comment by Night-Pryanik** [comment]
I'm not sure what's causing pumps to generate much more fuel than intended. Is this the first mine with this amount of fuel you encountered?

I debug-spawned the very same type of mine that's in your save (`spirals`), and both pumps have correct 0..5000 units of fuel in them. In fact, I debug-spawned dozens of these mines in your world, and all of them have the correct amount of fuel in pumps.

As for amount of loot, I'd say it's ok. I have a friendly advice, though, and I even put it into a mod's description: I suggest lowering item spawn modifier from 1.0 to 0.5 or even lower to get a true "no hope" feeling.

**Comment by pjf** [comment]
Thank you so much for your time and patience! I'm not sure about the pumps either, but the SUS-style loot lists make sense as to why there's so much *stuff* in the mining site.

Closing this as it doesn't look like I've encountered a bug after all.

Thank you so much again for No Hope, I'm having a blast with it!
