### ISSUE TITLE
[XEDRA Evolved] Dreamsmith and Mad Genius give player character spells that don't exist

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#59588]
### Describe the bug

So, after messing around with various things to see what's changed after reinstalling CDDA, I've run into a bug with the XEDRA Evolved mod, in that both the Dreamsmith and Mad Genius mutations give the player character spells that don't exist - the IDs for the spells are listed in the mutations' data as "forge_dreamdross" and "spark_of_inspiration," respectively, but no spells with those IDs are actually defined anywhere. Adding these mutations via debug gave my character two spells with no name listed, and trying to cast the spells (which I've selected by accident multiple times) causes the game to crash. The same crash also occurs when I try to use debug to change what spells my character has; I believe this is due to the presence of these undefined spells in the list of spells accessible via the debug menu.

### Steps to reproduce

1. Make and play in a world with the XEDRA Evolved mod
2. Add the "Dreamsmith" and "Mad Genius" mutations to your character
3. Look at your spell list
4. Try to cast the unnamed spells

Also:

1. Make and play in a world with the XEDRA Evolved mod
2. Try to edit your character's spells via the debug menu

### Expected behavior

I expect the mutations to not add undefined spells that make my game crash.

### Screenshots

![Dream spells not defined](https://user-images.githubusercontent.com/60671985/180798720-e1cdea83-259c-406f-a086-4cee8b815a2b.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 8c56f13 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Aftershock [aftershock],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by Maleclypse** [comment]
You can't have a bug from debugging in incomplete content.  Once it's content that is achievable in game you can bring me bugs for it.

**Comment by AmarinReyny** [comment]
> You can't have a bug from debugging in incomplete content. Once it's content that is achievable in game you can bring me bugs for it.

Ah, sorry. I didn't realize it was incomplete.

**Comment by Maleclypse** [comment]
No stress.  I appreciate you trying out the content.  And hopefully if life is kind to me this week I'll have some stuff to make both of those live in game by friday.

**Comment by EIIKaO** [comment]
Hi, folks.
I have a idea that avoiding the game crush when learn to invalid spell although keep room for the evolving mod development.

### The best scenario

AmarinReyny
Without crashing, you can continue playing with the player char who got that mutation (but you will get a debug message every load). You still cannot learn that incomplete spells yet.

Maleclypse
Keep developing the mod to your own plan. Then, you will continue to develop the mod and implement the spells and they will be merge. 

AmarinReyny
If you load the save with the build which merged complete spells, it will allow you to automatically(?) learn spells. 
All's well that ends well.


If anyone is interested, I would try to PR it later.
