### ISSUE TITLE
Add Templating for Pockets

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#59580]
### Is your feature request related to a problem? Please describe.

As someone who blows through characters pretty quickly, having a way to "save" a white/blacklist for an article of clothing or a pocket would be an amazing feature.  The first thing I do when I start is shuffle over to my pants, add priority for one of the pockets and whitelist lighter, pocket knife and smartphone.  

Being able to do this using a template would drastically decrease the amount of keypresses and would incentivize setting up more comprehensive pocket loadouts as they wouldn't disappear when you lose that character.

### Solution you would like.

Add templating system to articles of clothing.
"Save Settings for [Jeans]" -> Name Template [Raiding Jeans] 
Die with that character -> Start new character -> Load Template [Raiding Jeans]

### Describe alternatives you have considered.

Adding templating for pockets instead of articles of clothing, although either would be useful I think clothing might be initially easier to do.

### Additional context

**Comment by DIBAOS** [comment]
I think the favorite menu of crafting items needs such a template too, because favorite menu will disappear after you lose characters and restart the game.exe.

**Comment by chrispikula** [comment]
Both of these will need a try-catch exception, item by item for the use-case where mods are added and removed, or the game is updated, and thus items or recipes no longer exist.

**Comment by anothersimulacrum** [comment]
Added in https://github.com/CleverRaven/Cataclysm-DDA/pull/63390
