### ISSUE TITLE
Martial arts compatible with long weapons do not trigger techniques on reach attacks

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59585]
### Describe the bug

Techniques do not trigger when reach attacks are used.

This reduces the usefulness of relevant martial arts considerably.

Especially due to the fact that a large percentage of reach weapons have 30% damage penalty when used for non-reach (adjacent) attacks.

So, for example using a halberd, naginata, or pike, you are currently stuck either with 30% damage penalty or non-working techniques.

### Steps to reproduce

1. Make a new character with "Melee Training" background and select Pencak Silat
2. Level up Melee to 5, switch to Silat in the "_" menu
3. Spawn a pike and some zombies
4. Attack with reach and long reach attacks, either with f key or Tab key.
5. Notice that no matter how much you attack, none of the techniques trigger.

### Expected behavior

I expect martial arts techniques to trigger on reach attacks.

### Screenshots

![not_very_silat](https://user-images.githubusercontent.com/55463047/180767316-aa24ad06-c944-497d-bbc1-a6e6ba45c936.png)

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-07-22-0050
Mods: default

**Comment by bombasticSlacks** [comment]
#56116 fixes this but is gonna be a project for next release.

Basically we need to re-balance reach attacks for specific techniques since not all should trigger for any weapon.

**Comment by Night-Pryanik** [comment]
Should be fixed by #69103.
