### ISSUE TITLE
Auto-MOLLE pockets removing zone?

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#59593]
### Is your feature request related to a problem? Please describe.

Similar to how we have Unload Everything loot zone, I just wish we have the same, but for detaching the MOLLE pockets from the MOLLE packs you get from zombie soldiers. Sometimes you get a LOT of those, yet have to go through them one by one to remove the pockets if you'd want to keep everything.

### Solution you would like.

Just a loot zone for removing MOLLE pockets from MOLLE-compatible stuffs within the zone. I don't know anything about code so that's why I'm making a request instead of trying to add it myself.

**Comment by descan** [comment]
Expanding this to a "remove mods" zone, from all objects placed in it (guns, armour, packs, tools) seems like it would be in order, yes?

**Comment by bombasticSlacks** [comment]
Well I fixed this (I was already overhauling some stuff to fix a bigger issue), and added the remove mods for guns option, oddly enough without reading this suggestion from you descan. Great minds think alike I guess.
