### ISSUE TITLE
sidebar UI, conditional swap doesn't work for bodypart

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59598]
### Describe the bug

It seems that swapping work only for casual widgets but boduparts
related to #59442

### Steps to reproduce

Use attached sidebar, remove hp of arm_l to 0
Now you can see that hp bar completely blue and red X on the line below.

### Expected behavior

for arm_l 

"i_bp_LA_hp_graph" should change to "i_bp_LA_broken_sym" when

 "condition": { "compare_int": [ { "u_val": "hp" }, "==", { "const": 0 } ] }

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 7fe8d5b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context
[sidebar-mobile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9183438/sidebar-mobile.zip)

this sidebar shows two warnings
they can be ignored for now as they are unrelated to the bug

**Comment by vetall812** [comment]
@mlange-42 , could you please take a look?

**Comment by mlange-42** [comment]
@vetall812 Could you post the complete JSON entry?

Not sure what you are trying to do, but to swap out entire widgets, you need a `layout` widget as wrapper that does the logic.

E.g. from the "structured" sidebar:

```json
  {
    "id": "structured_speed_vehicle_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "columns",
    "clauses": [
      { "id": "driving", "widgets": [ "vehicle_cruise_desc_no_label" ], "condition": "u_driving" },
      {
        "id": "not_driving",
        "widgets": [ "structured_speed_num_layout", "structured_move_count_mode_layout" ],
        "condition": { "not": "u_driving" }
      }
    ]
  }
```

BTW... When posting code, putting it between triple back-quotes formats it as such, like so:

````
```json
{
  "key": "value"
}
```
````

gives:

```json
{
  "key": "value"
}
```

**Comment by vetall812** [comment]
the second i've read 'complete JSON' I've figured out what is my problem. I have to define exact bodypart for this clause. Thank you!
