### ISSUE TITLE
Sidebar widgets with `rows` layout are mis-aligned

### ISSUE THREAD

**Issue by mlange-42** [CleverRaven/Cataclysm-DDA#59611]
### Describe the bug

Sidebar widgets that stack `columns` layouts in `rows` are mis-aligned, if cells have defined width.

### Steps to reproduce

Not really sure. Make a sidebar widget using a `rows` layout, which contains `columns` layouts, which contain elements with a defined width.

Added code for a sidebar that reproduces the behaviour under "Additional context". The important points are the layouts with `width` defined, and stacking multiple `column` layouts.

### Expected behavior

Alignment/cell width should not change when stacking rows.

### Screenshots

Top: Tree separate widgets with `columns` layout.  
Bottom: the same three widgets, but into a `rows` layout widget.  
Both should look the same.

![grafik](https://user-images.githubusercontent.com/44003176/180883152-dfb09ad5-3d17-4874-981a-48166e638553.png)

Note the indent, already in the first!

### Versions and configuration

- OS: Windows 10
- Game version: [cdda-experimental-2022-07-25-0625](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-25-0625) (32ee0b1)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [ dda, no_npc_food, no_fungal_growth ]

### Additional context

Sidebar code reproducing the issue. Put into `data/json/ui`, e.g. as `sidebar-test.json`.

```json
[
  {
    "id": "test_environment_layout",
    "type": "widget",
    "label": "Environment",
    "description": "Shows environment and place information, like time, weather, light, etc.",
    "style": "layout",
    "arrange": "rows",
    "widgets": [ "test_time_moon_layout", "test_weather_layout", "test_place_sound_layout" ]
  },
  {
    "id": "test_time_moon_layout",
    "type": "widget",
    "label": "Date/Time/Moon",
    "description": "Shows date, time and moon phase.",
    "style": "layout",
    "arrange": "columns",
    "widgets": [ "date_desc_no_label", "test_time_layout", "moon_phase_graph" ]
  },
  {
    "id": "test_weather_layout",
    "type": "widget",
    "style": "layout",
    "label": "Weather",
    "description": "Shows weather, light and wind.",
    "arrange": "columns",
    "widgets": [ "weather_desc_no_label", "test_lighting_layout", "test_wind_layout" ]
  },
  {
    "id": "test_place_sound_layout",
    "type": "widget",
    "style": "layout",
    "label": "Place/Sound",
    "description": "Shows the current location and sound emitted.",
    "arrange": "columns",
    "widgets": [ "test_place_layout", "test_sound_layout" ]
  },
  {
    "id": "test_time_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 10,
    "widgets": [ "sundial_time_desc_no_label" ]
  },
  {
    "id": "test_lighting_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 10,
    "widgets": [ "lighting_desc_no_label" ]
  },
  {
    "id": "test_wind_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 18,
    "widgets": [ "wind_desc_no_label" ]
  },
  {
    "id": "test_place_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 26,
    "widgets": [ "test_place_desc" ]
  },
  {
    "id": "test_sound_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 10,
    "widgets": [ "sound_num" ]
  },
  {
    "id": "test_place_desc",
    "type": "widget",
    "copy-from": "place_desc",
    "flags": [ "W_LABEL_NONE" ]
  },
  {
    "id": "test_sidebar",
    "type": "widget",
    "style": "sidebar",
    "label": "test",
    "description": "Test sidebar",
    "separator": ": ",
    "width": 48,
    "padding": 1,
    "widgets": [
      "separator",
      "test_environment_layout",
      "separator",
      "test_time_moon_layout",
      "test_weather_layout",
      "test_place_sound_layout",
      "separator"
    ]
  }
]
```

**Comment by vetall812** [comment]
/confirmed
and related to #58991

**Comment by mlange-42** [comment]
Looks like it is caused by the difference in code usef for top-level vs. nested widgets. If you put the row-layout widget into another single-element layout widget, everything looks good.
