### ISSUE TITLE
Zone profiles

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59619]
### Is your feature request related to a problem? Please describe.

Having to remake zones all the time gets tedious, and i think we can make them even more useful.

### Solution you would like.

Add multiple zone "profiles". We should be able to make and switch between multiple zone set ups easily in a single character save and name them. We should also have the ability to save them globally with a name, then load and access from any character.

Another thing this can be useful for. Allow entire zone profiles to be toggled between personal and regular zones. 

I think this can save players a lot of time. I realize zones can be enabled and disabled, but i think a stronger feature like this is needed at this point with how much zones have grown and how useful they are.

Also, zone keybindings should really be simplified. We don't need separate keys to Enable/Disable zones or personal - they should just toggle. That cuts 4 keybindings down to 2.

**Comment by ANickelN** [comment]
Love this idea, I would be a lot more encouraged to use both personal and general sorting zones if I didn't think I would have to redo all the work into getting them set up when I inevitably lose all my limbs and explode.
