### ISSUE TITLE
Filter memory

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59625]
### Is your feature request related to a problem? Please describe.

So, I'm often using the same filters, over and over again, when I'm trying to loot a pile of corpses.  m:gold, m:gemstone, card, m:platinum, c:ammo, c:gun, c:mag, m:synthetic, etc.

This is a pain to re-type.  Recipes and 'v'iew items have a memory, why not filters?  It could even be globally shared across AIM/pickup nearby/pickup all/drop, etc.  

### Solution you would like.

Pressing the up arrow when filtering these things would bring back historical choices.

### Describe alternatives you have considered.

idk, auto-hotkey and a macro?  No idea what keybind I should use.

**Comment by PatrikLundell** [comment]
A work around in the mean time would be to have it stored in a text file outside of the game and copy/paste it.

**Comment by liminalRoar** [comment]
With the construction menu we have an entire page for << Filter >> I always wondered why this wasn't implemented for crafting. 
Granted it doesn't exactly solve the problem because a history or ability to store multiple filters and switch back easily would be useful.
