### ISSUE TITLE
Make "Container view" inventory display items by pocket

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59637]
### Is your feature request related to a problem? Please describe.

I just now fell in love with the "container view" mode for the basic inventory, as it allows me to indulge all my sick organizing fantasies. However, I'm noticing that it hasn't really kept up with all the lovely updates to pockets. With carabiners/straps, MOLLE and the Inventory Organizer, it is now both possible and practical to have a single item with dozens of specialized pockets, but no way to keep those pockets separate in your actual inventory. It's all considered a single container.

### Solution you would like.

Show pockets as indented sub-containers, basically like nested containers currently are. Ideally with their descriptions as labels, but just the size values would work.

e: and the ability to show/hide pockets like you can whole containers would also be splendid, but that may be A Whole Thing in itself

e2: and while I'm dreaming, it would be great of you could directly select the pockets as if they were containers in the inventory, to manage autopickup settings, (i)nsert items etc.

**Comment by Je55eah** [comment]
Did the OP get their wish fulfilled? I think it works that way.

When I press i twice I get a menu with all the containers and all the things in them. I use it a lot and I think it would be great if I could also examine and take actions on the items from that screen. If items were selectable then I could highlight them and move them directly too. highlight item-m-target container-m would be better than highlight container-m-highlight item-enter-target container-m.

**Comment by Terrorforge** [comment]
That's the Inventory Organizer. I'm talking about the "container view" you can switch to, which does let you use/examine/etc. items, but doesn't display by pocket or let you move things between pockets.

But your comment does make me think that the ideal solution would be to combine those two things into one menu. I know it was a lot of work just to get the inventory organizer working in the first place, so I imagine this would be even more so, but we can hope.
