### ISSUE TITLE
game crash on android

### ISSUE THREAD

**Issue by zhou77521** [CleverRaven/Cataclysm-DDA#59635]
### Describe the bug

game crash

### Steps to reproduce

game crash

### Expected behavior

i  donot know

### Versions and configuration

 DEBUG    : Tried to use non-existent scenario '(null)'. Setting to generic 'evacuee'.

 FUNCTION : void avatar::load(const JsonObject &)
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/savegame_json.cpp
 LINE     : 1616
 VERSION  : 8105c2c

**Comment by DamienRoyan** [comment]
#59632

**Comment by irwiss** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/59648
