### ISSUE TITLE
Crash while saving the game

### ISSUE THREAD

**Issue by jiornojiovanni** [CleverRaven/Cataclysm-DDA#59632]
### Describe the bug

When I save the game it crashes, but not always.

### Steps to reproduce

1. Play for some time
2. Save
3. Crash

### Expected behavior

No crash

### Versions and configuration

-OS: Windows 11
-Game Version: 8105c2c (latest experimental)
-Graphics: tile (with UDP tileset)
-Ingame language: english
-mods: "dda", "package_bionic_professions" ,  "no_npc_food",  "no_fungal_growth",  "cbm_slots",  "No_Rail_Stations", 
"translate_dialogue"

### Additional context

There is no crash log for some reason
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9188349/debug.log)

**Comment by jiornojiovanni** [comment]
The game gets saved tho

**Comment by jonokrukov** [comment]
I'm getting a crash whenever I save the game as well on the latest experimental.  It does still actually save the game like @jiornojiovanni says.  My debug errors are a bit different than yours though:
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9188592/debug.log)

**Comment by DamienRoyan** [comment]
/confirmed
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9188655/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9188657/debug.log)


![image](https://user-images.githubusercontent.com/88375697/180978091-3042d5a6-af2f-48ec-a026-aad90bfa841b.png)

**Comment by KHeket** [comment]
Same problem. Game autosaved = crash. But Game is actually saved. I tryed to quicksave - same problem
- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 8105c2c [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by in-F** [comment]
Same issue. 

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9191208/debug.log)

- OS: Windows
    - OS Version: 10.0.19042.1766 (20H2)
- Game Version: 8105c2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key]
]

**Comment by eturner** [comment]
Came here for this. Happens on linux too.

**Comment by denistest18** [comment]
same with the save drop and the first hub 01 quest not completed due to a bug

**Comment by Kribylet** [comment]
Tested reverting 54989b8347f429c008eccce9900e5ede39390ec4 (#59488), quicksaving works after revert.

**Comment by jiornojiovanni** [comment]
I also reverted to the previous build to temporarily fix this issue

**Comment by Boonlike** [comment]
Chiming in that I've got the same issue. Game saves on crash. Just quits, doesn't throw any errors. Currently reverting to an older build.

**Comment by DamienRoyan** [comment]
> Chiming in that I've got the same issue. Game saves on crash. Just quits, doesn't throw any errors. Currently reverting to an older build.

We now know what stable release users feel like

**Comment by SStelioss** [comment]
Exact same crash here
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9200697/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9200698/debug.log)
.
