### ISSUE TITLE
Companions mining appears to dig down when selecting the same tile

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59634]
### Describe the bug

I'm trying to use two companions to dig out a basement under my base. The latest session resulted in a hole rather than two dug out tiles. I believe I left both of them adjacent to the rock wall that's now a hole when I ordered them to mine.

### Steps to reproduce

1. Paint mining zones.
2. Equip two companions with mining equipment and ensure there's sufficient lighting.
3. Order two companions standing next to a painted tile to mine.
4. "Hope" they'll try to mine out the same tile. This might be possible to be helped along by clever zone placement so the only legal tile within reach (i.e. without moving) is that particular tile.

### Expected behavior

Companions should not try to mine out the same tile someone else is working on, and definitely shouldn't dig a hole under it (nothing resulting from the second companion's effort would be a better option than a hole).

### Screenshots

![image](https://user-images.githubusercontent.com/22739822/180979004-42edfa97-e357-4339-a967-acf737d32e8b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: d6a1777 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms.
+ JSON recipe additions of welding supplies to workshop and tallow to canteen expansions respectively.

### Additional context

My current work around to try to avoid it from happening again is to lead the companions to locations where they can mine without moving and can't target the same tile.

**Comment by rgehlen** [comment]
I had this happen a few weeks ago. I think the way it happened was that my tunnel was 1 tile wide and the NPC was working with a pick axe.  Then I did swap position and jackhammered the tile the NPC was working on fell down a z-level.

**Comment by descan** [comment]
Just in general, multiple entities working the same zone should not work the same tile. I've had plenty of stop-starts when deconstructing a building with a follower because of working the same (de)construction zone tile.

Nothing so bad as this, it's just annoying in my case :P
