### ISSUE TITLE
Soaked Dandelion

### ISSUE THREAD

**Issue by Coaxy** [CleverRaven/Cataclysm-DDA#59639]
### Describe the bug

Dandelion Wine should get another look over - five books give you the recipe to make the must, but only one of those books gives you the recipe to make Soaking Dandelion, the required component for the must.

### Steps to reproduce

1. Gain Access to the 'Dandelion Wine Must' recipe from any non-Homebrewer's Bible source (e.g. any book like pitching a tent, etc)
2. See that it includes an ingredient "Soaked Dandelion" that you cannot craft
3. Research this on Hitchhiker's Guide to the Cataclysm
4. See that there is no recipe for "Soaked Dandelion" but that there is a recipe for "Soaking Dandelions"
5. Realize that "Soaking Dandelions" is a recipe learned only from the book Homebrewer's Bible

### Expected behavior

I expected there to be some way of creating Soaking/Soaked Dandelion in the book that gives you the recipe for the must. 

Especially since the process of creating "Soaked Dandelions" is just the process of making a tea - you are covering the flowers in hot water and letting it steep. There's no unique knowledge or cooking skill involved (the most intensive part would be processing the dandelions since you don't want the "milk" from the stems, but that is just mechanically separating the stem from the flower, which would normally be done with your hands), and it would without a doubt be covered as a step in the recipe for making dandelion wine.

### Versions and configuration

Playing on 0.F-3, although according to Hitchiker's Guide to the Cataclysm, this discrepancy is still there on the latest experimental builds.

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 4abdbc8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
