### ISSUE TITLE
Allow map_gen_updates for larger areas

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#59641]
### Is your feature request related to a problem? Please describe.

currently it's only taking a max mapgen of 24x24, but it would be great if you could toss in an array like so: 
"mapgen_update": "realbig_map_update", "om_terrain": [ level0_nw, level_0_ne, level0_sw, level0_se ]

This because i made some big maps and want to change them all into a potential map-update so i can have them spawn once only.
If i need to cut it all in 24x24 pieces that's a lot of work because i placed a lot of things there with coordinates which all would have to change [if not in the nw quadrant.]

It's doable ofc but i'd assume it's a fairly easy fix as mapgens already can take in an array of ids and figure out what goes where.

### Solution you would like.

mapgen_update take in arrays of om_terrains, and the order will tell it what goes where like in default mapgens, so.

om_terrain: [ [ "terrain_at_0_0",  "terrain_a_1_0" ], [ "terrain_at_0_1", "terrain_at1_1" ]  ]

with the sensible restriction being that they're all the same size 

### Additional context

the context is the mod i'm working on, it's going to be pretty awesome

**Comment by LyranRenegade** [comment]
ok, i chopped it up in pieces and it seems to work, but maybe for the future it would be a nice thing to have..

**Comment by pshepjr** [comment]
I agree it would be really nice to have, I am also working on something and quickly became frustrated when I realized I cannot do nested chunks because they "cross the border." I can only assume this is still an issue because it isn't easy/possible to fix but I am certainly not a code expert.

**Comment by kevingranade** [comment]
It's not simple and this issue doesn't address anything about the complexity.
