### ISSUE TITLE
Auto-sort inventory button

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59640]
### Is your feature request related to a problem? Please describe.

I like using pocket autopickup settings for organizing, but it's easy for things to become disorganized.

Let's say I put the IFAK in my LBV aside for medical supplies. I put all my newly acquired bandages in there, but it gets full and bandages start going in my backpack instead. Then I use some of the bandages in the IFAK. Now I have a slightly annoying situation where I could fit all my bandages in the IFAK pocket, but to put them there I would have to move them manually.

Another common scenario is I've dropped my backpack somewhere, but I find something too tasty not to grab immediately, so it goes in my pants pocket, and I wish when I got back I could just shove all stuff in the backpack where it belongs.

### Solution you would like.

A button that shuffles your inventory around essentially as if you had dropped everything you aren't wearing on the ground and picked it back up.

Holsters and magazine pockets should probably be exempted, maybe as a toggleable option. And there should be some way to mark a pocket as "don't sort". An alternative/supplemental option might be to not sort favorited items.

**Comment by andrei8l** [comment]
> A button that shuffles your inventory around essentially as if you had dropped everything you aren't wearing on the ground and picked it back up.

In what order should it pick them up? If in arbitrary order, then you probably will get the same result or something similarly bad. If you want the optimal shuffle, you're looking at a 2-dimensional (volume, weight) variable bin packing problem with at least 2 extra constraints (length and pocket restrictions). And good luck with that one!

**Comment by Terrorforge** [comment]
Probably in some fixed order. Alphabetically, or by volume maybe. I'm not looking for something that will optimize use of pocket space, I'm looking for something that will organize my inventory according to my pocket autopickup settings.

**Comment by rgehlen** [comment]
there is a new unbound (by default) "unload container" (to a tile) which also allows multiple worn items to be unloaded at the same time. not the same thing but this should be helpful.

**Comment by keampe** [comment]
I have a work around, but it's a little clumsy. I make use of small bottles/cigarette packs. So, I'll have a cigarette pack whitelisted for adhesive bandages (it'll hold 45) and I label it *edc - Adhesive Bandages and it goes in a specific pocket. Rinse and repeat with everything else you want to every day carry. Basically using containers as sub - pockets.

What would be nice is if you could define a "Kit" as an array of items, assign it to a pocket and have your pick up try to top the Kit up first. Maybe you flag the pocket as "Kit" and whatever is in there when you do that becomes the inventory of that kit.

   - Shane

**Comment by Terrorforge** [comment]
Thanks, but that's a workaround for a different problem than the one I have. My problem is a situation where I have 38 adhesive bandages in the cigarette pack and 5 in my inventory and I'd like all of them to go in the pack

Which, again, not a huge problem if it's literally just that, but if I've got several containers like tht, it starts to get annoying

**Comment by keampe** [comment]
I Whitelist the cigarette pack at priority 5, so the adhesive bandages go there first, but I see your point - I have to drop and pick them up for them to go there. The other problem is if you have 38 in the pack (which holds 45, max) and the stack you're picking up is 8 or more it'll go into your inventory, not 7 into the pack and 1 into your inventory.

I do spend quite a bit of time on inventory management - it'd be nice to automate it more.

   - Shane

**Comment by Terrorforge** [comment]
Even worse if you drop all of it and now your 46 bandages go in the backpack. But that's a separate issue I've already reported in #58306

**Comment by Je55eah** [comment]
A repack button to drop everything (except liquids) in a container as individual, un-nested, items and then immediately pick everything back up according to the players settings would be handy. If the drop function crawls through and drops the most nested items first and repeats until there are no nested items and then it picks the items up in the reverse order that the items were dropped then the nested items should all find their way back into a container that existed.
