### ISSUE TITLE
"You have no room for X" item error should state whether the problem is volume or length.

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59642]
### Is your feature request related to a problem? Please describe.

Sometimes, when picking up an item that I *technically* have the volume for (and occasionally when I have the length for it, although this doesn't come up as often) I'll get an error that I have no room for it. Can sometimes take a moment to figure out what the issue is and fix it. 

### Solution you would like.

Have the error provide some more information about what's causing it.

**Comment by liminalRoar** [comment]
Are you referring to attempting to move items with Advanced inventory management?

**Comment by descan** [comment]
> Are you referring to attempting to move items with Advanced inventory management?

That too, but I thought of it specifically when trying to pick up an item that you technically have the volume for, but none of your pockets are long enough.

**Comment by liminalRoar** [comment]
With AIM it will tell you "You have no space for _x_"

With regular "g"rab, it simply has the red "Does not fit in any pocket!" text now.

So you want it to specify on the grab menu how it does not fit? It used to give you the option to wield there at least, but doesn't do that anymore either.

**Comment by descan** [comment]
I hadn't even thought about the weight one, because it's not as much of a hard limit in my game (I can suffer a couple turns of pain, it's all good). I think there's a message about being overburdened when you do pick it up, but I have that option of prevent item pick-up turned off, so I'm not sure what it says elsewhere. In either case, with the three barriers to item pick-up in play, it should probably be more specific on the error prompt - especially for new players who might not yet grok the whole idea of length vs. volume vs. weight.

**Comment by mlange-42** [comment]
> It used to give you the option to wield there at least, but doesn't do that anymore either.

You can still wield it. The shortkey is listed in the header.

> Perhaps it could say "Too heavy to carry", "Too long to fit in any pocket" and "Too large to fit in any pocket"

:+1:

> I think there's a message about being overburdened when you do pick it up

It's a bit weird. As long as you can pick up one item of a type without being overburdened, you can pick up as many as you want and become overburdended. If a single item would make you overburdened, you can't pick up any. But you can wield it. (this should probably go to a separate issue...)

**Comment by mlange-42** [comment]
Mh, it is probably not as simple as one might think when having only a single pocket in mind. You get a certain rejection reason for each pocket, so how to combine pockets that deny one due to length, some for volume, and another for blacklisting? Ah, and one for mass, which is also limited per pocket.

**Comment by descan** [comment]
Length is usually the biggest obstacle in my experience. Find a pocket with the right minimum length, and list the problems with placing it in that pocket - too heavy, too big, it's been blacklisted. Multiple pockets can be that same minimum, so prioritize the... priority pockets, assuming the player has set that up on their character. If there are no priorities, then I'd say just the biggest pocket of eligible length should be listed as its problems.
