### ISSUE TITLE
Game crashes after interacting with vehicle

### ISSUE THREAD

**Issue by TokyoJedi** [CleverRaven/Cataclysm-DDA#59647]
### Describe the bug

When trying to examine my vehicle, the game crashes to desktop.

### Steps to reproduce

1. Load my save after update 8105c2c.
2. Examine my vehicle to modify it.
3. Crash to desktop.

### Expected behavior

I should be able to enter the vehicle modification screen.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 8105c2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9193273/debug.zip)
[debug (after running generate game report).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9193288/debug.after.running.generate.game.report.zip)

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/59648
