### ISSUE TITLE
"Invalid Location" Save bug

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#59659]
### Describe the bug

Quick/auto saving procs an "Invalid Location" Error. Dismissing the error causes the game to crash. 

### Steps to reproduce

Save the game.
Press 'I' when the "invalid location" error comes up.
Press any key.
>crash

### Expected behavior

No crash, no error

### Screenshots

![image](https://user-images.githubusercontent.com/107653330/181166946-54ee3d01-7263-4b7e-aa13-cd497a1255cf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 2fbf47c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

 DEBUG    : invalid terrain id "1822023696"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 432
 VERSION  : 8105c2c

I have tried reverting to earlier versions of the game but this doesn't seem to help. The  version i started getting this error in was:
2022-07-26-2249

**Comment by Resok** [comment]
I'm seeing the same behavior with the latest few builds. Brand new game, similar mod set as above.

- OS: Windows
    - OS Version: 10.0.19044.1862 (21H2)
- Game Version: 8105c2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
]

I was able to used save and quit reliably though without any error.  The issue appears isolated to either quicksave or autosave.

**Comment by Kribylet** [comment]
#59648?

**Comment by foxymacko-real** [comment]
happend to me too

**Comment by kevingranade** [comment]
Presumably closed by #59648
