### ISSUE TITLE
Allow player to track horse location

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#59655]
### Is your feature request related to a problem? Please describe.

I lost my freaking horse. It had all my stuff.

### Solution you would like.

Similar to how vehicles are tracked, add a tracking feature for the horse

### Describe alternatives you have considered.

Have something to blind the horse, so it only runs if it takes damage, not just because something spooky walked nearby.

Tying the horse down only make it vulnerable to get killed. At least this way it'll run away if danger befalls it

**Comment by Mo-rang** [comment]
i want something like gps trackers for animals too.

**Comment by liminalRoar** [comment]
i need this for my backpack sometimes... xD

**Comment by kevingranade** [comment]
Vehicle tracking isn't really tracking,  it's just remembering where the thing is. With a horse the feature would be "remember where i dismounted my horse".

Someone can feel free to add that,  but we can't keep feature requests around forever.
