### ISSUE TITLE
Player-created destination "missions."

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59652]
### Is your feature request related to a problem? Please describe.

I sometimes need to re-orient myself and find my destination again, especially if it's in a city.

### Solution you would like.

Similarly to how missions can place a red * on the map and show you how far away it is, allowing a player-placed Destination marker would be welcomed by me.

**Comment by PatrikLundell** [comment]
Yes, it can be tricky to orient yourself over large distances.

Like "Hm, I've been away from the game for a week, and I'm continuing with zombie clearing/looting in a city far from my base. How do I get back?". A mission marker would definitely be helpful.
