### ISSUE TITLE
Exosuit features no longer work

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#59657]
### Describe the bug

Something in the last few weeks broke most of the exosuit functionality. Flags and relic passive effects no longer work when activated. Transforms still work. 

### Steps to reproduce

1. Spawn an exosuit frame and power supply.
2. Activate exosuit.
3. Note that exosuit is active as vision is no longer obstructed.
4. Check player stats, +10 strength bonus is not visible. 
5. Notice you are freezing to death as the climate control is not functioning.

Also impacts modules like the small and large load support modules, which can be reproduced easily.

### Expected behavior

Activating a module or the frame itself should provide passive bonus effects.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 2fbf47c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

### Additional context

Also happens on non-exoplanet worlds, see below
- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 2fbf47c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Aftershock [aftershock]
]

**Comment by Drew4484** [comment]
Confirmed by @irwiss and @Merikona

**Comment by Drew4484** [comment]
First noticed the issue while working on #58670, so approximately 06/24/2022 for a start date.

**Comment by Maleclypse** [comment]
I can't make it work on [Cataclysm-DDA experimental build 2022-05-02-2346](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-05-02-2346) and I tested with saving and reloading to see if it required a reload like some errors do occasionally.

**Comment by Maleclypse** [comment]
irwiss — Today at 6:19 AM
think there's already inherit: false for flags... btw flags is also at least part of the reason for the missing STR bonus that's tracked in the 0.G stable tracker - IS_UPS makes item processing branch into process_UPS where it's trying to look up a CABLE_SPOOL and when it doesn't find one it sets active=false on exosuit (silently, and not calling deactivate() so  exosuit doesn't revert to non-powered in inventory) so the enchantment doesn't work

From the discord this morning

**Comment by I-am-Erk** [comment]
What is the status on this one? I see some related PRs, are these still broken?

**Comment by Drew4484** [comment]
> What is the status on this one? I see some related PRs, are these still broken?

I need to sit down and do an item by item check tonight, I'll update or close this as appropriate.

**Comment by Jordanb716** [comment]
Part of this reported in #58836, so if fixed that can be closed as well.

**Comment by GuardianDll** [comment]
and also #61701

**Comment by LyleSY** [comment]
I can't replicate this in vanilla, I see no monster or item called "exosuit"

**Comment by Drew4484** [comment]
> I can't replicate this in vanilla, I see no monster or item called "exosuit"

These are Aftershock items.

**Comment by LyleSY** [comment]
I tried this with an X-02: 'Grunt' Combat Mech in vanilla. There I saw no strength boost and no protection from cold.

**Comment by I-am-Erk** [comment]
Ok. This one probably does need fixing for stable unfortunately. I'll see if I can find some time to pin it down  tonight somehow

**Comment by andrei8l** [comment]
Isn't this working correctly? I'm getting the strength bonus and some warmth after activating the frame

[Screencast from 2022-11-28 07-45-55.webm](https://user-images.githubusercontent.com/68240139/204203144-02f1a63f-b359-4a48-beda-b94003984b2e.webm)

**Comment by andrei8l** [comment]
> I tried this with an X-02: 'Grunt' Combat Mech in vanilla. There I saw no strength boost and no protection from cold.

From looking briefly at the code, the vanilla `mech_str_bonus` only improves carry weight and throw ability rather than add raw stat and I can verify that it still works.

**Comment by Drew4484** [comment]
The majority of the features seem to be working now. 

Tested successfully:
- Frame powers on.
- Pilot can see and receives strength bonus while frame is active.
- Underlayer provides insulation (when worn, will remove underlayer slot from frame).
- Power supply unit powers frame.
- Jetpack allows movement laterally, horizontally, and in combination.
- Structural imager provides clairvoyance cone.
- Oxygen supply provides air as necessary while submerged.

Tested but not functioning:
- Climbing module (does not allow climbing a single wall tile without assistance from furniture).
- Load support modules (large and small) do not provide weight bonus.
- AR module (error with power).

Not yet tested:
- ICE generator
- Turbine generator
- ASRG
- Quickdraw holster/sheath
- Forcefields
- Cartridge charger
- Medical injector

**Comment by andrei8l** [comment]
These all appear to be different and unrelated issues:
> * Load support modules (large and small) do not provide weight bonus.

`"has": "WORN"` fails here. 
<details>
<summary>Quick and dirty patch; it would be prettier if relic code used item_location
</summary>

```diff
diff --git a/src/character.h b/src/character.h
index f21a1a2189..a20c4c6759 100644
--- a/src/character.h
+++ b/src/character.h
@@ -1676,6 +1676,10 @@ class Character : public Creature, public visitable
             return worn.is_worn( thing );
         }
 
+        bool is_worn_module( const item &thing ) const {
+            return worn.is_worn_module( thing );
+        }
+
         /**
          * Asks how to use the item (if it has more than one use_method) and uses it.
          * Returns true if it destroys the item. Consumes charges from the item.
diff --git a/src/character_attire.cpp b/src/character_attire.cpp
index 6156574d35..5daef15bfc 100644
--- a/src/character_attire.cpp
+++ b/src/character_attire.cpp
@@ -869,6 +869,15 @@ bool outfit::is_worn( const itype_id &clothing ) const
     return false;
 }
 
+bool outfit::is_worn_module( const item &thing ) const
+{
+    return thing.has_flag( flag_CANT_WEAR ) &&
+    std::any_of( worn.cbegin(), worn.cend(), [&thing]( item const & elem ) {
+        return elem.contained_where( thing ) != nullptr;
+    } );
+}
+
+
 bool outfit::is_wearing_on_bp( const itype_id &clothing, const bodypart_id &bp ) const
 {
     for( const item &i : worn ) {
diff --git a/src/character_attire.h b/src/character_attire.h
index 995ac105fc..e4b6db3d00 100644
--- a/src/character_attire.h
+++ b/src/character_attire.h
@@ -66,6 +66,7 @@ class outfit
         explicit outfit( const std::list<item> &items ) : worn( items ) {}
         bool is_worn( const item &clothing ) const;
         bool is_worn( const itype_id &clothing ) const;
+        bool is_worn_module( const item &thing ) const;
         bool is_wearing_on_bp( const itype_id &clothing, const bodypart_id &bp ) const;
         bool covered_with_flag( const flag_id &f, const body_part_set &parts ) const;
         bool wearing_something_on( const bodypart_id &bp ) const;
diff --git a/src/magic_enchantment.cpp b/src/magic_enchantment.cpp
index 78de807b4a..1673c102a9 100644
--- a/src/magic_enchantment.cpp
+++ b/src/magic_enchantment.cpp
@@ -216,7 +216,8 @@ bool enchantment::is_active( const Character &guy, const item &parent ) const
 
     if( !( active_conditions.first == has::HELD ||
            ( active_conditions.first == has::WIELD && guy.is_wielding( parent ) ) ||
-           ( active_conditions.first == has::WORN && guy.is_worn( parent ) ) ) ) {
+           ( active_conditions.first == has::WORN &&
+             ( guy.is_worn( parent ) || guy.is_worn_module( parent ) ) ) ) ) {
         return false;
     }
 
```
</details>

> * Climbing module (does not allow climbing a single wall tile without assistance from furniture).

<details>
<summary>The mutation flag should be in uppercase</summary>

```diff
diff --git a/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json b/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json
index 57a7aae2f3..9fec47e813 100644
--- a/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json
+++ b/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json
@@ -8,6 +8,6 @@
     "valid": false,
     "purifiable": false,
     "types": [ "Equipment" ],
-    "flags": "wall_cling"
+    "flags": "WALL_CLING"
   }
 ]
```
</details>

But the activation conditions aren't loaded properly for some reason

> 
> * AR module (error with power).
<details>
<summary>This lets it turn on</summary>

```diff
diff --git a/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json b/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json
index c89f0f55df..b64eda056c 100644
--- a/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json
+++ b/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json
@@ -665,7 +665,7 @@
     "material": [ "lvl4ballisticglass", "qt_steel" ],
     "symbol": "(",
     "color": "yellow",
-    "flags": [ "CANT_WEAR", "EXO_HELMET_GADGET" ],
+    "flags": [ "CANT_WEAR", "EXO_HELMET_GADGET", "USE_UPS" ],
     "relic_data": {
       "passive_effects": [ { "has": "WORN", "condition": "ACTIVE", "values": [ { "value": "LEARNING_FOCUS", "add": 15 } ] } ]
     },
```
</details>

**Comment by Drew4484** [comment]
> These all appear to be different and unrelated issues:
> > * Load support modules (large and small) do not provide weight bonus.
> 
> `"has": "WORN"` fails here. 
> <details>
> <summary>Quick and dirty patch; it would be prettier if relic code used item_location
> </summary>
> 
> ```diff
> diff --git a/src/character.h b/src/character.h
> index f21a1a2189..a20c4c6759 100644
> --- a/src/character.h
> +++ b/src/character.h
> @@ -1676,6 +1676,10 @@ class Character : public Creature, public visitable
>              return worn.is_worn( thing );
>          }
>  
> +        bool is_worn_module( const item &thing ) const {
> +            return worn.is_worn_module( thing );
> +        }
> +
>          /**
>           * Asks how to use the item (if it has more than one use_method) and uses it.
>           * Returns true if it destroys the item. Consumes charges from the item.
> diff --git a/src/character_attire.cpp b/src/character_attire.cpp
> index 6156574d35..5daef15bfc 100644
> --- a/src/character_attire.cpp
> +++ b/src/character_attire.cpp
> @@ -869,6 +869,15 @@ bool outfit::is_worn( const itype_id &clothing ) const
>      return false;
>  }
>  
> +bool outfit::is_worn_module( const item &thing ) const
> +{
> +    return thing.has_flag( flag_CANT_WEAR ) &&
> +    std::any_of( worn.cbegin(), worn.cend(), [&thing]( item const & elem ) {
> +        return elem.contained_where( thing ) != nullptr;
> +    } );
> +}
> +
> +
>  bool outfit::is_wearing_on_bp( const itype_id &clothing, const bodypart_id &bp ) const
>  {
>      for( const item &i : worn ) {
> diff --git a/src/character_attire.h b/src/character_attire.h
> index 995ac105fc..e4b6db3d00 100644
> --- a/src/character_attire.h
> +++ b/src/character_attire.h
> @@ -66,6 +66,7 @@ class outfit
>          explicit outfit( const std::list<item> &items ) : worn( items ) {}
>          bool is_worn( const item &clothing ) const;
>          bool is_worn( const itype_id &clothing ) const;
> +        bool is_worn_module( const item &thing ) const;
>          bool is_wearing_on_bp( const itype_id &clothing, const bodypart_id &bp ) const;
>          bool covered_with_flag( const flag_id &f, const body_part_set &parts ) const;
>          bool wearing_something_on( const bodypart_id &bp ) const;
> diff --git a/src/magic_enchantment.cpp b/src/magic_enchantment.cpp
> index 78de807b4a..1673c102a9 100644
> --- a/src/magic_enchantment.cpp
> +++ b/src/magic_enchantment.cpp
> @@ -216,7 +216,8 @@ bool enchantment::is_active( const Character &guy, const item &parent ) const
>  
>      if( !( active_conditions.first == has::HELD ||
>             ( active_conditions.first == has::WIELD && guy.is_wielding( parent ) ) ||
> -           ( active_conditions.first == has::WORN && guy.is_worn( parent ) ) ) ) {
> +           ( active_conditions.first == has::WORN &&
> +             ( guy.is_worn( parent ) || guy.is_worn_module( parent ) ) ) ) ) {
>          return false;
>      }
>  
> ```
> </details>
> 
> > * Climbing module (does not allow climbing a single wall tile without assistance from furniture).
> 
> <details>
> <summary>The mutation flag should be in uppercase</summary>
> 
> ```diff
> diff --git a/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json b/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json
> index 57a7aae2f3..9fec47e813 100644
> --- a/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json
> +++ b/data/mods/Aftershock/items/armor/exosuit/exosuit_mutations.json
> @@ -8,6 +8,6 @@
>      "valid": false,
>      "purifiable": false,
>      "types": [ "Equipment" ],
> -    "flags": "wall_cling"
> +    "flags": "WALL_CLING"
>    }
>  ]
> ```
> </details>
> 
> But the activation conditions aren't loaded properly for some reason
> 
> > 
> > * AR module (error with power).
> <details>
> <summary>This lets it turn on (and it also needs the worn patch from above)</summary>
> 
> ```diff
> diff --git a/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json b/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json
> index c89f0f55df..b64eda056c 100644
> --- a/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json
> +++ b/data/mods/Aftershock/items/armor/exosuit/exosuit_modules.json
> @@ -665,7 +665,7 @@
>      "material": [ "lvl4ballisticglass", "qt_steel" ],
>      "symbol": "(",
>      "color": "yellow",
> -    "flags": [ "CANT_WEAR", "EXO_HELMET_GADGET" ],
> +    "flags": [ "CANT_WEAR", "EXO_HELMET_GADGET", "USE_UPS" ],
>      "relic_data": {
>        "passive_effects": [ { "has": "WORN", "condition": "ACTIVE", "values": [ { "value": "LEARNING_FOCUS", "add": 15 } ] } ]
>      },
> ```
> </details>
> 
> 
> > * ICE generator
> > * Turbine generator
> > * ASRG
> > * Medical injector
> 
> These work fine. Not sure how to test the other ones.
> 

This is what I expected, I think the core issue can be closed at this point. Thanks for taking a look.

**Comment by Drew4484** [comment]
Issue appears to be resolved, remaining exosuit modules to test or debug appear to be item based, not an issue with the core mechanic of worn items.
