### ISSUE TITLE
revert examine-action

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#59667]
### Is your feature request related to a problem? Please describe.

why do we need the game to figure out for us which tile we want to examine and figure out for us what the appropriate action would be?

The new feature also makes it so that we can't examine tiles that haven't got a specific examine_action if you're standing next to one tile that has. {because you now are limited to either doing the 'defined' examine action or not, like picking up a mutated poppy flower or whatever while in reality you want to look at a piano next to it, for arguments sake.]

I use the examine_action a lot in my mod, it's one of the most powerful json-tools we have as we can run eocs directly from there.

I'd like there to be a conscious action from the player instead of it automatically picking a direction.
I understand the argument that it will only automatically do stuff if there's no other option but my arguments against that are:
1. that's not entirely true, examine also prints the description on screen, which in some cases is now impossible to achieve.
2. It doesnt make sense, you walk up to an interesting object and think, let's examine this, you press e and you pry open the door next to it. In the old system you at least could see that the object didnt get a highlight, still you could examine it for the description.
3. It's no longer 'examining' in the strict sense of the word, maybe make another key for the new feature and call it 'AUTO-ACT' or whatever.
4. why? It's dumb
5. I want it out.
6. God is on my side.
7. Bob marley wrote a song about it.
8. Just because.
and i got many more arguments like that, as i'm sure y'all understand

### Solution you would like.

revert examine-action 

### Additional context

json-modding options.

in my upcoming mod i use examine extensively, don't want the player to just press e and automatically look under the carpet, he/she at least should pick the direction [that's highlighted, sure], still it seems like a conscious action that way.. there's a pause there.. A moment of realization that you selected the carpet instead of the game doing that for you.

**Comment by mqrause** [comment]
You can turn off the option "Autoselect if exactly one valid target".

**Comment by LyranRenegade** [comment]
right, that's what i wanted to hear :P

**Comment by LyranRenegade** [comment]
i suggest turning that option off by default then

**Comment by mqrause** [comment]
Unless you provide some evidence that most people would prefer it that way, chances are low for that happening.

**Comment by ZhilkinSerg** [comment]
> i suggest turning that option off by default then

No, we don't want that.

**Comment by kevingranade** [comment]
Not planned.
