### ISSUE TITLE
Faction camp building doesn't appear when built.

### ISSUE THREAD

**Issue by JackReport** [CleverRaven/Cataclysm-DDA#59660]
### Describe the bug

Using the faction bulletin bord to reclaim my NPC's after building gives an error.

 DEBUG    : In nested mapgen fbmc_shelter_bedroom_SE_rock in update mapgen fbmc_shelter_bedroom_se_rock on faction_base_camp_new_0_north, setting terrain to t_door_c (from t_floor) at (15,21) when furniture was f_cupboard.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

 FUNCTION : virtual void jmapgen_terrain::apply(const mapgendata&, const jmapgen_int&, const jmapgen_int&, const string&) const
 FILE     : src/mapgen.cpp
 LINE     : 2780
 VERSION  : 14c36f5

It doesn't crash the game, but the buildings never appear. There are upgrade paths for the non existent building. 
Let me know If further Information is required.

### Steps to reproduce

1. Spawn NPC
2. Start faction Camp at Evacuation Shelter
3. Build any one of the bedroom options

### Expected behavior

I expected building to appear because I built it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 14c36f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Gun Cotton [guncotton],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Useful Helicopters Experimental [useful_helicopters],
    Tamable Wildlife [Tamable_Wildlife],
    Safe Portable Autodoc [safe_portable_autodoc],
    Clean CBMs [clean_cbm]
]

**Comment by PatrikLundell** [comment]
That report appears when there is "furniture" in the way of something "constructed" and there is no flag to indicate how to handle the situation. Just proceeding with space or Ignore should effectively use the ALLOW... option suggested, with the construction appearing where specified and the "furniture" appearing in the (possibly) inappropriate location. This is essentially a message to say that the map designer should update the design to take the flags introduced after the map was created into consideration. For faction camps this should always be the ALLOW_... flag.

I'm not aware of this having failed previously.

I don't know where "faction_base_camp_new_0_north" comes from, though, as that's not something I can find in any of the base game's JSON files. It could be something from a mod, or it could be unrelated to the problem.

**Comment by JackReport** [comment]
> That report appears when there is "furniture" in the way of something "constructed" and there is no flag to indicate how to handle the situation. Just proceeding with space or Ignore should effectively use the ALLOW... option suggested, with the construction appearing where specified and the "furniture" appearing in the (possibly) inappropriate location. This is essentially a message to say that the map designer should update the design to take the flags introduced after the map was created into consideration. For faction camps this should always be the ALLOW_... flag.
> 
> I'm not aware of this having failed previously.
> 
> I don't know where "faction_base_camp_new_0_north" comes from, though, as that's not something I can find in any of the base game's JSON files. It could be something from a mod, or it could be unrelated to the problem.

Is there a work around using the map editor to spawn the buildings in question? Not sure if the recent changes to faction camps has anything to do with this.

**Comment by PatrikLundell** [comment]
Using the map editor it should be possible to generate the same things the construction does, one tile at a time, but it would require looking at the blueprint to see what exactly is spawned on each tile, and do the calculations required to find what these tiles are.

**Comment by JackReport** [comment]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9205008/debug.log)
Additional Info from the debuglog

**Comment by JackReport** [comment]
> Using the map editor it should be possible to generate the same things the construction does, one tile at a time, but it would require looking at the blueprint to see what exactly is spawned on each tile, and do the calculations required to find what these tiles are.
> 
> Edit: I'm failing to repeat the problem. I've downloaded whatever is the latest master as of an hour ago or so, compiled it, and teleported to an evac center of type A with an orientation of east rather than north (I couldn't find any north oriented shelter of type A). I get the same error report, but the walls and the door show up as they should. The cupboard is gone, but the things in it remain.
> 
> By the way, "faction_base_camp_new_0_north" is the name of shelter type A, with the suffix being the orientation.

**Comment by JackReport** [comment]
whoops accidently closed it, my bad.

**Comment by PatrikLundell** [comment]
The trace in the debug log seems to just show that the debug function has been called and from where, which just confirms that the message is produced, but I fail to find anything that would indicate a subsequent failure to actually update the terrain. The code should issue the message and then continue, when working properly.

I managed to spawn the shelter with the correct orientation and build the bedroom, and it still works (after dismissing the error message).

It can be noted that in some of my tests it's been too dark to actually see what was constructed so I had to go to the location to see that things actually had changed, but that isn't the case in this version (although it would be if the time was during the night).

This is what the result of constructing the room in that shelter looks like (in case you want to debug the walls and door in):
![Screenshot (255)](https://user-images.githubusercontent.com/22739822/181445619-89b0625c-36ba-44d4-a5e4-2ef99d370b4a.png)

If you can provide your save at the point prior to the construction I can try it to see what happens, but otherwise I have no clue as to why it wouldn't work for you, unless some of the mods you use has done something weird with the shelter.

**Comment by JackReport** [comment]
> 
I think I figured out what was happening, I hadn't destroyed 1 cupboard that was right where a wall was supposed to go. 
After I did so, completing the build job built the room no trouble.
Haha, I just imagine them working for 3 days, and then seeing that cupboard and being like "Shit, Alright boys, break everything down we can't do the job, something was in the way.".

Thanks for helping me out, hopefully this can help others who encounter the same problem as me!

**Comment by PatrikLundell** [comment]
It's still odd, because the cupboards where the walls are built are always removed (that's hard coded for walls), which is why it complains about the one in the way of the door only. However, it's good to hear you've gotten past that problem, even though it's still somewhat worrying that you encountered it at all.
