### ISSUE TITLE
UI suggestion for incompatible armor

### ISSUE THREAD

**Issue by YehnBeep** [CleverRaven/Cataclysm-DDA#59664]
### Is your feature request related to a problem? Please describe.

I spent a long time trying to figure out why I couldn't wear a certain piece of armor. The error message gave no hints, and since it had an 'examine' screen several pages long, I also didn't notice the problem there for a while.

But I did eventually see it at the very very bottom - "You cannot wear this because of your mutation"

It would be nice if this message was moved to near the top. For example, just under the description?

### Solution you would like.

It would be nice if this message was moved to near the top.

### Describe alternatives you have considered.

A more descriptive error message could maybe help as well...

**Comment by kevingranade** [comment]
Not planned.
