### ISSUE TITLE
Sidebar UI, Some multiline widgets still produce unnecessary empty row

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59669]
### Describe the bug

mutilline widgets still produce additional line

1) without multiline widget
![image](https://user-images.githubusercontent.com/6676374/181318078-06269d35-097a-4cdb-b614-a02dc65e2de8.png)

2) with such widget
![image](https://user-images.githubusercontent.com/6676374/181320449-3ecabb83-9fa3-4632-bf52-be4d915366cb.png)
![image](https://user-images.githubusercontent.com/6676374/181334978-34416085-9040-4856-8753-2fc2a934c921.png)

### Steps to reproduce

you can see it on the sidebars:
- classic
- one padding
- compact
- thick
- structured

### Expected behavior

its unwanted line

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 776aa63 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context
Probably related to #59571 
_No response_

**Comment by descan** [comment]
Which widget specifically are you talking about? The "Separator" widgets are *designed* to add empty rows, and that widget/empty row is the only one I see that is adding empty rows.

**Comment by vetall812** [comment]
> Which widget specifically are you talking about? The "Separator" widgets are _designed_ to add empty rows, and that widget/empty row is the only one I see that is adding empty rows.

In the examples I've provided it is a widget with "var": "overmap_text".
Probably there are some other multiline widgets with same behavior.

**Comment by mlange-42** [comment]
Seems like Overmap has the problem, and the Log too (gets fixed with #59646). Will also try to fix it for Overmap. Thanks for reporting!

**Comment by mlange-42** [comment]
Looks like I already found the problem. Easy to fix...

**Comment by mlange-42** [comment]
Added the fix to the existing PR for the Log fix.

**Comment by mlange-42** [comment]
Ok, it is more complicated... The newlines at the end of the multiline widgets, which cause these empty lines, have a meaning for column alignment. I think their purpuse it to make multiline widgets only take as much space as needed, not the entire automatic column width. The problem with this solution, however, is that widgets in columns further to the right, and below the lower end of the multiline widgets, "flow" to the left.

**Comment by vetall812** [comment]
> Ok, it is more complicated... The newlines at the end of the multiline widgets, which cause these empty lines, have a meaning for column alignment. I think their purpuse it to make multiline widgets only take as much space as needed, not the entire automatic column width. The problem with this solution, however, is that widgets in columns further to the right, and below the lower end of the multiline widgets, "flow" to the left.

If there is a workaround like wrap mutiline widget into simple row arrangement widget i can live with it.

**Comment by mlange-42** [comment]
> If there is a workaround like wrap mutiline widget into simple row arrangement widget i can live with it.

Something like that might help. But I think I have a solution, although not an optimal one. Will push it to #59646 soon. I think, however, it will require some discussion with the original author of the respective code parts.

**Comment by mlange-42** [comment]
Should be fixed by #59676.

**Comment by vetall812** [comment]
YES!
