### ISSUE TITLE
Finally implement RC cameras.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59673]
### Is your feature request related to a problem? Please describe.

I want to be able to attach a remote camera to RC cars. This has been mentioned before, but i want to add some more thoughts and compile where we are at. So far, related we have had:

- #36965 - (first?) Request to view camera feed for RC cars
- #37200 - Would add some functionality but needed limited to RC cars _with_ cameras. And the lighting/view from RC car should be limited/directional.
- #42281 - Jul 28, 2020 : Not exactly the same but related.

### Solution you would like.

Implement remote cameras for RC cars. Ideally, RC cars with a camera and controller that has a screen/video feed will "illuminate" tiles in a limited, directions view in front of the car. Subsequently, add the ability to have the camera follow the car, either with an option on the controller, or some manner of toggle when a remote camera is in use.  What we need that is not implemented (i think) :

- Remote camera mod that can be installed on RC cars or included on some.
- Advanced remote controller with screen (the basic one should just be knobs and buttons with no ability for camera feed).
- Directional illumination with the remote camera.
- Camera toggle to follow RC car.

Other mod ideas for RC cars.
- Speakers that can be attached and turned on/off for distraction purposes.
- Gas powered variant vs Electric
- RC dump bed variant where small items can be loaded manually and dropped off remotely.
- Various components to modify/customize RC car (change max speed, distance from receiver before losing connection, turning ability, etc)

### Describe alternatives you have considered.

Plenty of other ideas but this gets the conversation out there again for now.

### Additional context

I will look through this more deeply when i am back home.

**Comment by x-qq** [comment]
Another possibility for this: some existing RC cars with cameras [0] are controlled using a smartphone application, and send the video feed to it as well.

[0] https://www.amazon.com/DEERC-Remote-Control-Off-Road-Monster/dp/B07VCCL9VC

**Comment by liminalRoar** [comment]
Yes, i brought that up on discord today as well. One issue is we don't have phone service or internet. So the only way i can think the smartphone communicates is through Bluetooth, which wouldn't have much of a range, and also isn't implemented in anything else yet.

**Comment by x-qq** [comment]
I think the IRL thing uses wifi (the car has an access point, the phone connects to it).
