### ISSUE TITLE
Move the "morale" menu away from root level keybindings

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59677]
### Is your feature request related to a problem? Please describe.

This is part of a larger effort to identify places where our "top level" keybindings have been mapped to things that players do not need rapid, single-keypress access for. This is a discussion: all these issues are valid places to raise concerns about reasons a player should have immediate single-key access to this function.

The Morale menu is currently mapped to `V` by default, but I argue this probably makes it harder for new players to find, as it doesn't even appear to make sense as a menu in its own right.

### Solution you would like.

Move morale to the `@` menu. In the future it probably makes sense to bundle it with the same pane as effects, but prior to any full revamps of the layout of the `@` menu we could simply put a line somewhere obvious reading "press V to morale effects"

### Describe alternatives you have considered.

We could instead make the `V` menu more worthwhile, eg by moving active effects and things in there, but I would still argue that that stuff should be in the @ menu where players expect to find it.

In the more distant future, we should rework the entire @ menu to have a customizable tabbed layout, with morale and effects in a tab.

**Comment by PatrikLundell** [comment]
Makes sense to me. The only time I "use" that menu is when I press the wrong key or caps lock has been toggled...
The logic of tying this to the character screen instead sounds good.

Is there a use case where you'd want to frequently check morale (not counting debugging/testing)?

**Comment by Zireael07** [comment]
@PatrikLundell Not really... I usually check morale only when I want to craft something long-taking or chug multiple mutagens (or other morale-debuffing food-ish stuff)

**Comment by chrispikula** [comment]
New players need it a bit more frequently, especially if they don't know why their ability to learn skills is tanking.

**Comment by I-am-Erk** [comment]
I would argue that it is easier for new players to find it if it's in another common area like the @ window than if it is bound to another keypress they need to memorize

**Comment by chrispikula** [comment]
Oh, I agree, I was just commenting that it's only older players who _don't_ use it as often.

**Comment by pjf** [comment]
I'm an older player who uses it frequently. I'll be sad to see the root-level morale keybinding go, but understand the need to make it more discoverable.
