### ISSUE TITLE
Remove top-level keybinding for kill count

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59685]
### Is your feature request related to a problem? Please describe.

This is part of a larger effort to identify places where our "top level" keybindings have been mapped to things that players do not need rapid, single-keypress access for. This is a discussion: all these issues are valid places to raise concerns about reasons a player should have immediate single-key access to this function.

"Kill count" is a purely for-interest feature, and not one that needs to be accessed rapidly as a single keypress.

### Solution you would like.

I suggest moving Kill Count into the Diary - `K: view kill count` for example. 

Then, let's bind the Diary to `(` because it's a very nice feature that is currently not accessible through default keybindings and many people don't know about it.

### Describe alternatives you have considered.

The kill count could go in the `@` menu instead but I like the conceptual idea of keeping the diary to "fluff" stuff and the @ menu for "affects the game directly" stuff.

### Additional context

Ideally we'd also revamp the appearance of the Kill Count screen to match the diary page display but in the short term, it could just pop up overtop of the diary looking like it currently does.

**Comment by Zireael07** [comment]
Achievements and kill count kinda sorta might be in the same place/menu, methinks?

**Comment by PatrikLundell** [comment]
I agree with the reasoning of having the character menu contain "real" things and somewhere else for fluff like achievements, kill counts, and diary. The fluff section ought to have a default key binding, but there should be little reason for its sub sections to have default bindings (but still support player binding directly to sub sections).

**Comment by chrispikula** [comment]
I've been using ctrl-D for diary, myself.  The ctrl-keys are much nicer than the shift-number keys.  Ctrl-V, vehicle, Ctrl-C, craft, Ctrl-X, construct, etc, ctrl-S, Sky(weather), ctrl-F, Forage options, ctrl-A, all the item use options such as star a fire & cut bars, etc.

**Comment by Zireael07** [comment]
@chrispikula: I think your comment belongs in https://github.com/CleverRaven/Cataclysm-DDA/discussions/59678, not here ?
