### ISSUE TITLE
Post-59648 merge crash on savegame.

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59680]
### Describe the bug

The PR supposed to fix the mapbuffer crash ( https://github.com/CleverRaven/Cataclysm-DDA/pull/59648 ) does not seem to have fixed the crashes on savegames. Either that, or a different crash has been introduced.
@Kribylet 

### Steps to reproduce

1. Load a game on the latest experimental
2. Craaaaash?

### Expected behavior

Not craaaaaaash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: 037ed1f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9203731/debug.log)
There does not seem to be a crash.log file in my config folder. Worrisome.

**Comment by descan** [comment]
Save is too large for a single upload, so the root folder is zipped, and the maps folder has been split into two zips: 
[maps root.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9203757/maps.root.zip)
[maps 2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9203760/maps.2.zip)
[maps 1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9203761/maps.1.zip)

**Comment by LyleSY** [comment]
I'm pleasantly surprised to report that I couldn't reproduce with my crashed save.

**Comment by Kribylet** [comment]
Hm! I downloaded your save and the latest experimental 05ebec592d2c8123cd636c6add4bcc13ef62b191. I could load your save, save and quit out of it as well as quicksave.

**Comment by descan** [comment]
> Hm! I downloaded your save and the latest experimental [05ebec5](https://github.com/CleverRaven/Cataclysm-DDA/commit/05ebec592d2c8123cd636c6add4bcc13ef62b191). I could load your save, save and quit out of it as well as quicksave.

Hm. Interesting. I had used that save a couple times to make sure, at least three launches, and all three of them crashed. But I updated my game just now and opened the same game (a later save though) and it seems to be functioning fairly fine? 

Weird.
