### ISSUE TITLE
Remove Wooden Wall should also work on Chipped Wooden Walls

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59681]
### Is your feature request related to a problem? Please describe.

why the hell do i have to repair a tiny chip in order to tear down this wall?

### Solution you would like.

not need to repair the entire wall in order to tear it down

### Describe alternatives you have considered.

literally none ever, why is this not already a thing?

### Additional context

someone goofed

**Comment by PatrikLundell** [comment]
I don't think anyone goofed. Instead, nobody has added the functionality to tear down a chipped wall, leaving a work around as the way to do it (apart from smashing it). Thus, it's a missing feature rather than a bug (and it's appropriately labeled as a suggestion).
