### ISSUE TITLE
Move 'customize sidebar' out of root keybindings

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59684]
### Is your feature request related to a problem? Please describe.

This is part of a larger effort to identify places where our "top level" keybindings have been mapped to things that players do not need rapid, single-keypress access for. This is a discussion: all these issues are valid places to raise concerns about reasons a player should have immediate single-key access to this function.

The customize sidebar key, `{`, was a necessary feature when the customizable sidebar first launched, especially because the sudden change in layout was shocking to people.

Changes to sidebar layout are no longer so shocking, and the feature is quite stable.

### Solution you would like.

Remove the default "hint" from the sidebar, and move the 'customize sidebar' feature either into the ESC menu or into the Settings menu. I would suggest we put it in ESC for now, and then when we revamp the settings menu to be less of a dog's breakfast, we fit it into the new setup.

### Describe alternatives you have considered.

If we really want we could keep the Hint in there and have it direct people to the esc menu, but I don't think it's that vital that new players know they can adjust their sidebars, it was really there to help the old school folks who were upset at the change.

**Comment by Termineitor244** [comment]
Leaving the feature into the ESC menu sounds good to me, most inexperienced players (myself included) would expect that functionality to be there, so I was pretty surprised after **not** finding it there, I then read the hint and found myself pretty bewildered for it.
