### ISSUE TITLE
New sidebar and seasons longer than 99 days

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59699]
### Describe the bug

![image](https://user-images.githubusercontent.com/22281606/181458741-0ad832c0-7034-4633-8965-9d71ad655410.png)

What day is it?  How can I find out?

### Steps to reproduce

Set your season length to 100 or more days.  127 and you won't miss it.
Wait.

### Expected behavior

123rd of Spring, or 123rd of Spri... would be more useful.

### Screenshots

![image](https://user-images.githubusercontent.com/22281606/181459430-3b182e29-56da-47aa-b84a-08fded4e2b01.png)

### Versions and configuration

Win 10 Tiles, 42a7fde

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 4abdbc8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Inglonias** [comment]
This can be fixed pretty easily by making the widgets a character or two wider, but I admit that it didn't occur to me that people would make seasons longer than 91 days, since... that's sort of Earth standard.

Alternatively, we can limit season length to 91 days. I could see that happening as well, though I admit that might be a cowardly way out of this.

**Comment by mlange-42** [comment]
> 123rd of Spring, or 123rd of Spri... would be more useful.

(from original comment)

I think this is a good idea. The string is quite important, and takes a lot of space. Alternatively, add a place text variant that uses symbols or abbreviations for seasons?

Fixed it for now in #59868 by changing column widths.
