### ISSUE TITLE
New Arrow key modifier option for Ascend/Descend and movement speed

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#59692]
### Is your feature request related to a problem? Please describe.

Some actions would be nice to have easier access to. I think this in particular could speed up gameplay.

### Solution you would like.

Current L/R tilt option allows for Diagonal movement. SHIFT + L/R arrow keys moves character upwards diagonally while CTRL + L/R arrow keys moves downward diagonally.

Add following options:
- SHIFT + Up/down arrow keys to Ascend/Descend
- CTRL + Up/down arrow keys will increase/decrease movement mode (aka crouch/walk/run). 

### Describe alternatives you have considered.

similar concept but implemented slightly different.

Allow keybinding for compound strokes

### Additional context

Almost have it i think, just having a bit of trouble with the movement mode cycling since i want to add an opposing cycle direction.

**Comment by vetall812** [comment]
what about not only change speed in vehicle, but also change movement prone <-> crouch <-> walk <-> run ?

**Comment by liminalRoar** [comment]
hm perhaps i should have clarified things some. That is exactly what i mean :)

Because by default Up and down arrow keys control vehicle speed. This hopefully will indroduce a quick way to cycle back and forth through Prone/crouch/walk/run!

I'll be working on it more today and see if i can get it all running, was having issues last night lol

**Comment by chrispikula** [comment]
So, when you say vertical, do you mean North/South, or do you mean +z level, -z level?  Because it is not clear to me, nor in the description of your PR.

**Comment by liminalRoar** [comment]
I do mean Z level. thats why i mention it as Ascend/Descend. im trying to remember where i had vertical written.

**Comment by chrispikula** [comment]
I think you caught them, I can't find any via a quick history re-check.  I found this via some of the keybindings talk.  There's a _minor_ bit of confusion with:

> Current L/R tilt option allows for Diagonal movement. SHIFT + L/R arrow keys moves character upwards diagonally while CTRL + L/R arrow keys moves downward diagonally.

But with context it's fine.

Isn't the impreciseness of language great?  :-p

**Comment by liminalRoar** [comment]
Yeah sorry that was just to state the option we already have and how this is a similar addition.

I really think making movement mode (crouch, run, etc) and Ascending/descending makes gameplay more smooth. We could always implement the same kind of system with the Numpad + Shift/Ctrl as well if this idea catches on. Keeping your hand on the movement keys and just being able to press Ctrl or Shift is a lot quicker than switching to `Shift + ,` , `Shift + .` , and using the current movement mode menu (which we should keep of course)

BTW fantastic thoughts on the "Let's devise a brand new, optimized keymap" by Erk.
