### ISSUE TITLE
Allow companions to perform milking

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59706]
### Is your feature request related to a problem? Please describe.

Currently milking is a player only task. It's something that you'd want to be able to let companions deal with.

### Solution you would like.

Introduce milking zones, milk target zones, and a companion activity to milk animals within the milking zone.
The milk target zones would contain empty containers that could be fixed ("terrain", "furniture", and/or "appliance"), or items (flasks, gallon jugs, drums, etc.) into which the milk would be stored, filling the largest containers first.

A usage of overlapping zones ought to make it possible to "sort out items" to move filled containers away and replace them with empty ones, if desired, using existing zone functionality.

It can also be noted that an obvious appliance candidate for a target would be a temperature controlled container (essentially a working version of the non functional things found at dairy farms).

### Describe alternatives you have considered.

Introduce a faction camp parallel implementation of the functionality (and thus more of an addition than an alternative) that would differ from the companion task in that the companion would disappear into the void from the bulletin board and be recalled from the void when done via the board. The advantage of this is that the player can send of the companion and then leave the camp, rather than having to ensure he's not moving so the milking companion (and/or their targets) exit the reality bubble.

### Additional context

Tangentially related to #59643, as something that produced an increased incentive to keep animals to offset the increased effort #59643.

**Comment by anothersimulacrum** [comment]
Closing stale feature issue as per https://github.com/CleverRaven/Cataclysm-DDA/issues/59655#issuecomment-1475406441
