### ISSUE TITLE
Animal husbandry: Introduce breeding

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59702]
### Is your feature request related to a problem? Please describe.

Currently animals breed (or not) randomly. To breed animals for food there's a need to provide some control over the breeding and make it more consistent with the real world.

This is loosely related to #59643 that wants to increase the effort of keeping animals.

### Solution you would like.

- Introduce animal genders. As a result, only females should give birth and produce milk.
- Large animals should only (have a chance to) produce offspring during the spring.
- Animals kept by the player should only have a chance to produce offspring if they have been kept with a male in a breeding zone during the autumn. Ideally, they should also have been able to actually meet each other (no impregnation via spores). Untamed animals shouldn't breed in breeding zones (so you need to tame the offspring).
- Females should produce milk only after giving birth. Animals collected in the "wild" should ideally be identified as milk producing or not when first encountered (which would require either storing a state in the animals or having that as part of the animal identifier e.g. "bull", "cow", "heifer" for cows, in which case there should be support for transformation from non milk producing to milk producing when giving birth).
- Optionally milk producing species could require yearly births to not dry up. However, that does not have to be applied to untamed animals, although they could automatically be dry if tamed after summer.
- Medium/small sized animals should be capable of producing several litters per year, from mid spring to the end of summer. For breeding, they'd need to be kept in breeding zones during spring to early summer (I doubt players would want to keep moving them about anyway).
- Tame animals should keep a gestation state, i.e. they'd actually have some time of impregnation stored within them, so they might contain more state than untamed ones.
- Untamed animals could continue using logic similar to the current one.
- Egg laying species should be dealt with separately.

### Additional context

Edit: Modifying drying up based on @mlange-42's feedback.

**Comment by mlange-42** [comment]
> I think cows are bred to require only a single birth for life long production

No, cows lactate for around 300 days after calving. I.e. a calf is required each year. Or rather, for "high performance breeds" it is often a bit more than a year between two calves, due to reduced fertility.

**Comment by anothersimulacrum** [comment]
Closing stale feature issue as per https://github.com/CleverRaven/Cataclysm-DDA/issues/59655#issuecomment-1475406441
