### ISSUE TITLE
Allow companions to collect and process eggs

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59709]
### Is your feature request related to a problem? Please describe.

Currently you can probably set up egg collection from your chicken (or other birds, including wild ones) by a clever setup of custom zones (Fresh eggs here, ignore "rotten" eggs, and either ignore or move litter to either a garbage zone or a manure zone).
However, there isn't much companions can actually do with the eggs (only boil them, I think, and then only in faction camps with sufficient cooking facilities).

### Solution you would like.

- Introduce predefined zone support for egg collection. While I believe the zone system can be used to set it up, I'd expect most people trying to do that will end up with various undesirable results (litter in the Others zone and "rotten" eggs moved away to some zone) until they've fiddled their way to an understanding of how to wring zones. While an understanding of how zones work is good, it probably shouldn't be mandatory to perform reasonably standard activities.
- Introduce a well curated selection of egg based recipes for processing of collected eggs to faction camp recipe banks, keeping in mind that the UI quickly becomes hard to use with recipe bloat.

### Describe alternatives you have considered.

In addition to the above, introduce a way to instruct companions to craft without involving the faction camp system. That's a much larger task than the ones above (but a desirable one in the longer term).

### Additional context

Tangentially related to #59643 as a way to offset that suggestion's increased effort to maintain animals with an increased benefit from it.

**Comment by Zireael07** [comment]
Kinda sorta this and the other suggestions could be put in a single tracker issue or something (there's like 5 or 6 of them...)

**Comment by anothersimulacrum** [comment]
Closing stale feature issue as per https://github.com/CleverRaven/Cataclysm-DDA/issues/59655#issuecomment-1475406441
