### ISSUE TITLE
Allow the player and companions to slaughter tame animals

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59708]
### Is your feature request related to a problem? Please describe.

Currently the way to "slaughter" animals is to attack them. However, that can result in the corpse getting sufficiently damaged that you get a reduced product yield out of it. This is particularly noticeable with birds (such as chicken), as they yield little to begin with. Loss of chucks of meat for scraps of meat is bad because scraps have far fewer uses than chunks do.

### Solution you would like.

Introduce a tame animal interaction of "slaughter" that kills the animal and leaves an undamaged corpse. It may require a suitable knife for larger animals (wringing the neck of birds presumably is done without any tools).

For companions you'd probably want a combined "slaughter and butcher" activity where you designate one or more targets (several may be appropriate for smaller animals such as birds). After that, the companion would kill and process one animal at a time until they've all been processed. Ideally, the activity should allow the designation of target locations (zones?) for the products into which they'd be stored one animal at a time. Further, an option to collect blood would be useful (although that requires that the issue of selecting containers for it is supported).

### Describe alternatives you have considered.

Ideally I'd complement the companion activity with a faction camp order where you'd order the same activity to be performed, but the companion goes off into the void with the animals and returns with the products when recalled from the board. This wouldn't require any storage designation as all the products would be delivered at once, but it does have the blood collection option issue.
The advantage of this version is that it wouldn't require the player to stay at the base while the potentially several hours long sequence of actions is performed.

### Additional context

Tangentially related to #59643, as this is a way to make slaughter and butchery less of a hassle for the player, to offset that suggestion's increase in effort to maintain the animals.

**Comment by Zireael07** [comment]
Hm, slaughterhouse camp building coming when? (I imagine slaughtering things like horses or cows would require them being tied down or placed in such a building)

**Comment by PatrikLundell** [comment]
In the real world slaughter houses are currently used for industrial scale slaughtering, but I don't think people who slaughter animals for their own use have/had dedicated buildings on their farms for it. In the richer parts of the world there are health (and [anti] animal cruelty) authorities that mandate slaughter conditions for commercial and sometimes private use (don't think it's legal where I live, with hunting being an obvious exception), but those authorities are somewhat impotent in the post apocalyptic world...

Also, to justify a building you'd need to get a fair bit of functionality out of it, and I'm currently leaning towards moving away from camp building plans to free form building anyway. It doesn't mean I'd have anything against a system for handling building blueprints, but I don't think such a system exists currently.

**Comment by anothersimulacrum** [comment]
Closing stale feature issue as per https://github.com/CleverRaven/Cataclysm-DDA/issues/59655#issuecomment-1475406441
