### ISSUE TITLE
Support companion crafting of liquids

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59704]
### Is your feature request related to a problem? Please describe.

Currently any crafting recipe producing liquids is useless for base camp companion crafting, as the results of crafting is dumped on the ground when the companion returns.

### Solution you would like.

There are several changes that are possible, not all of them mutually exclusive.
- When companion crafting produces a liquid, add functionality similar to player crafting to ask for containers in which to store the product until all of it has been stored. Ideally, the selection of containers should include fixed ones, such as "terrain", "furniture", and/or "appliance" containers within the camp and its expansions.
- Allow the dedication of fixed containers as targets for specific liquid products. This can be tricky for liquids that spoil as you can't mix those. However, it would be convenient to check that designated targets exists as a recipe pre condition.
- Modify crafting to allow the up front selection of containers for the product and dynamically generate the appropriate crafting results (i.e. the liquid stored within the selected containers). The "primitive" version of this would require all the liquid to be stored in the same kind of container, such as all glass bottles, or all gallon jugs, etc., while the more advanced version would essentially use the current player crafting process of selecting from available containers until all the result has been accounted for, but done at the start of crafting rather than at the end. It can be noted that this crafting method can get into trouble with fixed containers ("furniture" etc.), as you can't remove them from the game and thus claim them for that particular crafting task, and thus would allow you to claim the same fixed container for multiple concurrent crafting missions (or even manual storage), with the need to handle any issues with conflict or insufficient volume at the end of crafting.

### Additional context

Tangentially related to #59643, at least when it comes to allowing companions to process milk (and blood?).

**Comment by PatrikLundell** [comment]
I made an attempt to implement this, and it sort of works, but not well enough.

I essentially copied the logic from regular crafting and added a check for liquids on companion crafting delivery and then called the regular crafting logic for that case with a radius of 60. That sort of works, as I could get a companion to craft milk out of raw milk and get the result delivered back into the canning pot I'd put the milked raw milk into. However, it doesn't find most of the containers in the camp. In a follow up test I'd sprinkled a few containers of different types (so I could distinguish them) within line of sight, plus one "hidden" behind a nearby wall, and one beneath the closest tile of a nearby vehicle. The container out of sight wasn't found, despite being the closest one, but all the visible ones were, including the one under the vehicle.

What I'd want is for the set of containers considered to be taken from the items stored in Base;Storage zones and to get the selected containers delivered at the delivery spot, rather than filled up while remaining in whatever location they are currently in. In addition to that, I'd like to see fixed containers (furniture tanks, vehicle tanks, appliance tanks) in a new Liquids container Infrastructure zones to be valid targets (optionally tagged with valid fluids), in which case they'd be filled up in place (obviously).
However, that looks like it would require merging zone logic into inventory_ui.cpp and game_inventory.cpp (the files containing the logic for liquid storage), which could get rather messy.

**Comment by anothersimulacrum** [comment]
Closing stale feature issue as per https://github.com/CleverRaven/Cataclysm-DDA/issues/59655#issuecomment-1475406441
