### ISSUE TITLE
Game crashes when saving after using helicopter and change Z levels with it

### ISSUE THREAD

**Issue by PunishedHideo** [CleverRaven/Cataclysm-DDA#59701]
### Describe the bug

Game crashes after using helicopter to change Z levels

### Steps to reproduce

1. Create character with piloting skill
2. Spawn a helicopter
3. Use < > to change z levels when piloting it
4. Save afterwards

### Expected behavior

It shouldn't crash when saving

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 14c36f5 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык [Russian]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Бионические профессии [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Перевод сложных диалогов [translate_dialogue]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9207427/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9207428/debug.log)

**Comment by Kribylet** [comment]
Have you tried a newer experimental build? This could be related to the issues fixed by #59648 which has been merged

**Comment by irwiss** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/59648 or https://github.com/CleverRaven/Cataclysm-DDA/pull/60018
