### ISSUE TITLE
XEDRA Evolved, missing proficiency

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59715]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/eb4bede0355d78f5a6595986115de11c6c135cc5/data/mods/Xedra_Evolved/monsters/changeling.json#L31

>     "families": [ "prof_physiology_demihuman" ],

prof_physiology_demihuman doesn't exist, and causes an ignorable error when monster with such is killed.

### Steps to reproduce

Kill said fey creatures after XEDRA evolved mod is used in world-gen.

### Expected behavior

Working proficiency.  

### Versions and configuration

Win 10, tiles, 42a7fde, use XEDRA evolved mod in world-gen.

### Additional context

It's an in-repository mod.  Not sure what else

**Comment by Maleclypse** [comment]
Closed by #60499
