### ISSUE TITLE
Expand the 'run to' function to allow unseen destinations

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59716]
### Is your feature request related to a problem? Please describe.

Currently you can enter look mode (;), aim at a tile and press T to auto-run to it.

However it only works for tiles that can be immediately seen. This severely limits the usefulness of this function.

### Solution you would like.

1. Enter look mode (;)
2. Aim at any explored tile, visible or not
3. Press T or double-click with mouse to run to it

### Describe alternatives you have considered.

The alternative of leaving things as is does not seem good.

### Additional context

Game version: cdda-linux-tiles-x64-2022-07-22-0050
Mod list: default

**Comment by anothersimulacrum** [comment]
Closing as per https://github.com/CleverRaven/Cataclysm-DDA/issues/59655#issuecomment-1475406441
