### ISSUE TITLE
MOLLE webbing belts never spawn with any pouches attached

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59713]
### Describe the bug

Various MOLLE equipment pieces usually spawn with some pouches attached, but I have not seen a single MOLLE webbing belt spawn with any sort of pouch on it. This seems inconsistent.

### Steps to reproduce

1. Kill hundreds of zombie soldiers
2. Collect hundreds of MOLLE webbing belts
3. Observe that not a single one has any pouches attached, ever

### Expected behavior

Would be nice if pouches could spawn on belts, optionally with some appropriate contents

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-07-22-0050
Mod list: default

**Comment by descan** [comment]
I have seen one (1) belt spawn with a pouch attached, ever. I believe it was a grenade pouch.

**Comment by mlange-42** [comment]
Never seen one with pouches, too.

**Comment by kholat** [comment]
same
