### ISSUE TITLE
Electric zombies are breaking equipment really fast

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#59727]
### Describe the bug

Melee attacks of electric zombies - shockers, zappers, are breaking equipment extremely quickly. I've noticed this from time to time, but they damage my gear really really fast, nearly on every single hit. 

If I had to guess electric damage started damaging armor for some reason? And since all armor has 0 electric resist, it breaks everything instantly? I even have electric immunity from my activity suit. 

### Steps to reproduce

1. Wear gear, optionally with electric resistance
2. be attacked in melee by an electric zed
3. notice even sturdy stuff degrading extremely rapidly

### Expected behavior

Electric zeds shouldn't be shredding my equipment into nothingness

### Screenshots

![image](https://user-images.githubusercontent.com/56016372/181690214-95306161-721d-45ae-b50e-3580c7f215bb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 536808e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Kribylet** [comment]
After some sleuthing I found that electric damage, along with cold and biological damage was allowed to damage items as of 4721e1ba978ddd5c8bce49d4bf186eba8e2e5716. I do not know the reasoning, though. From skimming the JSON entries for materials, resistances to these types seem absent in general, so they will substitute a 0.0f resistance, presumably getting wrecked.

**Comment by bombasticSlacks** [comment]
Yeah that's an oversight I can fix.
