### ISSUE TITLE
Chop Trees zone generating less trunks than manually chopping down trees

### ISSUE THREAD

**Issue by TaiGambol** [CleverRaven/Cataclysm-DDA#59725]
### Describe the bug

When using zones to chop trees, the trees seem to generate less trunks than when chopped manually.

### Steps to reproduce

1. Make a player with a woodcutting tool.
2. Find a forest. Designate a 'Chop Trees' zone covering some of the trees.
3. Using the 'Zone Activities' menu, begin chopping trees.
4. Each tree fells and produces its base trunk and one extra.
5. Cancel chopping. 
6. Approach a tree and 'a'ctivate your woodcutting tool, choosing to cut it down. Select a direction for it to fall.
7. Tree falls and produces its base trunk and three or four extra.

### Expected behavior

Trees cut down with the zone should generate the same trunks as if chopped down by hand.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 6447b56 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Culinary Days Ahead [culinary_days_ahead],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    DinoMod [DinoMod]
]

**Comment by PatrikLundell** [comment]
Manual tree chopping produces 3 +/- 1 trunk, i.e. 2-4 trunks. It seems that multi tree chopping produces 1 trunk 8/9 times and 0 trunks the nineth time.
Actually, it works as usual when a companion does the chopping, but not when the PC does it.
