### ISSUE TITLE
CTD with no error when picking up rotten cow pies from the ground

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#59734]
### Describe the bug

crashing when picking up cow pies.

### Steps to reproduce

1. Download the save and put it in your save folder https://mega.nz/folder/5rQFVaxA#Y8aoyGxirdDPNf5HRSSZDg
2. Run the save
3. when in the game, there are some cow pies at the friendly cow, if you wield a body bag thats in the car, and then walk to the cow pies and insert them into the body bag, the game crashes

### Expected behavior

No crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 3a934ca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

N/A

**Comment by PatrikLundell** [comment]
I failed to download the save, as the download speed was down to 2 kbps at 69% after two hours or so.

**Comment by kholat** [comment]
hmm after loading multiple times after restarting CDDA, sometimes it does not crash, interesting. 
Also ill try uploading somewhere else, cant on github because its >200MB

**Comment by kholat** [comment]
https://mega.nz/folder/5rQFVaxA#Y8aoyGxirdDPNf5HRSSZDg same thing with bird litter

**Comment by PatrikLundell** [comment]
Just as useless as the previous usage of the same storage. Down to 3 kbps at 57% and a number of hours. Cancelled.

**Comment by Zireael07** [comment]
@PatrikLundell: Something with your ISP likely - I've used mega to send as well as download files with no trouble.

@kholat Try dropbox? IIRC it has a cap of 2 or 3 GB space for free.

**Comment by PatrikLundell** [comment]
I doubt it's my ISP. I suspect it's mega throttling those not registered with them (as if that wouldn't get me to absolutely NOT register). The thing starts out at 150 kbps and then gradually drops off to an early modem rate trickle.

However, if @Zireael07 can download without issues I guess I can just offload verification there.

**Comment by kholat** [comment]
Well I refuse to use dropbox because its an absolute gutter tier company. Tell me which site you would like me to upload to at least instead of just complaining it doesnt work for you and ill upload it there.

**Comment by PatrikLundell** [comment]
Any that doesn't require membership to realistically download from.
