### ISSUE TITLE
Allow separate tilesets for characters and terrain. Granular tilesets.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59735]
### Is your feature request related to a problem? Please describe.

Some assets are used in multiple tilesets. Ultica, Altica, and Chibi ultica share the same terrain (i believe). Neodays and retrodays share many similarities too i think. I think we can have a way to cut down on disk spaced used as well as give more flexibility for tileset customization.

### Solution you would like.

A couple ways we can do this

1. Allow tilesets to have alternative character/monster sheets. You can choose a tileset and it may have multiple options for character art. example:
- Tileset: **Ultica**
- Character art: **Default,** **Altica,** **Chibi**

2. Granulate tilesets and allow for full mixing and matching. We can choose terrain, character, and maybe monster art all separately. Want Brownlikebears terrain with Hollow Moon characters? Why not.

The other feature that would go along with this nicely is nested settings. For example when `Use Tiles` is turned off, none of the other tile settings display. This makes settings much easier to navigate imo. For example custom overlay colors takes up a solid 8 lines that most people are not going to touch, a simple switch to turn those all on would be useful. Here is an image of how the tileset settings might look. The indenting for settings shows what the collapse tree.

![tilesets](https://user-images.githubusercontent.com/92204064/181770423-91d1439f-ad5b-4707-baa9-61eeaff46b0d.PNG)

I think we should go with the second option, but the first can actually be incorporated. We just need to allow Tilesets to specify that they use the terrain set of another. For example by default Altica could use Ultica for terrain and have a unique character/monster sprite sheet. Other unique sprites could be specified individually perhaps.

Either way, there's probably going to need to be some more code for tilesets to get any of the features to work, maybe just some .json files other than the new tileset options?

### Additional context

There is the issue of separate tilesets for far. Would it use that tileset for terrain and characters? I say yes for now, no need to make it more complex rn.

**Comment by bombasticSlacks** [comment]
I don't think this is a bad idea, but it would be a lot of work.

It would need to be done almost entirely at the renderer level since sprite sheets don't differentiate type of sprite. So even the PR I just did #59666 that basically doesn't touch the renderer just changes what data the renderer is using. The above would require each function for each thing you draw to be able to interact with each loaded tileset.

in some cases it would also be impossible. Different tilesets have different scales so for example a retrodays tile is a different scale than ultica. Checking scales lineup or rescaling stuff would be very complicated.

**Comment by liminalRoar** [comment]
Ah, i see. idk why i was thinking tilesheets were already divided in their own folders by name. For example a terrain file, character file, tall file, etc. And that makes sense with the scale. I was imagining it wouldn't be too hard to implement. But yeah it would need a rework of how tiles are handled i guess. and the scales would be quite an issue.

I do wonder if my first suggestion is at all possible then, of combining similar elements of like-tilesets together and being able to switch out the changed components. But i guess that is probably not worth the work.
