### ISSUE TITLE
Unfolding my bicycle results in a phantom piece remaining in one spot forever

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#59731]
### Describe the bug

I made myself a little folding electric bicycle to ride around on. After getting back to base and unfolding it, there's a tile that just sits there, even if I move the rest of the bicycle.

The bicycle doesn't lose any parts, it just has this one extra part that's a clone of an existing part.

Maybe related to #59429 or #59470, but honestly could be anything #56143 related.

### Steps to reproduce

1. Load the attached save
2. Look at the bicycle with a phantom wheel hanging off by itself
3. Fold the bicycle, the part goes away. Unfold it, and it comes back.
4. `e`xamine the bicycle, notice both parts give you the same bicycle.
5. Look at the tiles with the phantom part, and the front of the bicycle. They're the same!

### Expected behavior

Folded vehicles don't cause reality to shatter.

### Screenshots

Here's my bicycle, notice the extra wheel piece:

![bike1](https://user-images.githubusercontent.com/12072/181718302-4b674b45-785e-481e-9c26-a56027ce8b9b.png)

Move the bike, wheel still stays there:

![bike2](https://user-images.githubusercontent.com/12072/181718355-597b7d65-4f14-48a0-8c6a-5ba80bd51145.png)

### Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-10286-g919fd54ca2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    No Hope [no_hope],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]
```

Version is `cdda-experimental-2022-07-29-0223` with some of my local patches applied (none to do with vehicles).

### Additional context

- Save: [PhantomBikePart.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9218245/PhantomBikePart.zip)

**Comment by irwiss** [comment]
Loading the save I see a json error about kitchen unit but I'm guess it's your experiments at #59705 and doesn't look like it can affect it.

After loading I see no phantom parts:
![image](https://user-images.githubusercontent.com/6560075/181721900-8af3f3c6-cfe3-41bb-9c8f-bfb04ecec59a.png)

Tried driving, dragging it around and fold/unfold cycles but can't get the part to appear anything else I can try?

**Comment by pjf** [comment]
Well heck, it doesn't persist across save/load cycles for me either.

On the upside, my bicycle is now without phantom parts!

**Comment by PatrikLundell** [comment]
I frequently get that when unloading my motorcycle from my main vehicle, i.e. when I drag it away a shadow part remains, in particular if I grab it by the rear end an pull it (so it reverses direction). Haven't reported it as it seems to be visual only, i.e. it doesn't cause any obstruction. It's been that way for quite some time, so it's not new.

**Comment by chrispikula** [comment]
Any chance you copied this vehicle from a different world?

I've noticed similar things with bike-shop bikes, when I grab and drag them before riding them.  Might have something to do with interacting with it before it's treated, by the player, as a vehicle.  That means no examining it, no riding, just see and grab after creation.

**Comment by PatrikLundell** [comment]
No, it's one I've found (it might have been from a regular house garage, but anyway, it was in pristine condition before I laid my hands on it) and used for a fair while. I've loaded and unloaded it from my vehicle a fair number of times. I won't claim a bike before I examine it to verify that it is in better condition than my current bike.

**Comment by chrispikula** [comment]
Ah, whereas I just tend to grab them for their light frames or the aluminum ingots before I line them up in a veh.decon zone.

**Comment by PatrikLundell** [comment]
I've got a line of 15 or so electric cars to strip of their solar panels, and before that I've dedicated most of the stripping power to armored vehicles for metal building construction materials...
