### ISSUE TITLE
Unarmed weapons can't be used until unarmed 4 or learning a real martial art, due to lack of default attack vector

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#59741]
### Describe the bug

The various knuckle weapons(and other clothing with melee damage 😛) do not offer any damage to players if they lack a non-Brawling martial art until unarmed 4/5/6, for access to Power Hit/Trip/Disarm which have the HAND attack vector.

### Steps to reproduce

1. Spawn a debug monster & skewer knuckles(so the added damage shows as bleeding)
2. Attack it without skewer knuckles to see damage & no bleed as expected
3. Attack it wearing skewer knuckles & see no increased damage or bleed
4. Increase your unarmed skill to 4+ so you have access to Brawling's Power Hit/Trip/Disarm, which have the HAND attack vector.
5. Attack it until one of the techniques trigger, see increased damage & bleed.
6. Learn a martial art that has a default attack using the hands(I used Karate for Backhand Strike & Wing Chun for Chain Punch)
7. See every hit apply damage+bleed.

### Expected behavior

A default attack vector(probably easiest to just assume ``HAND`` rather than trying to work possibilities of kicks) so unarmed weapons aren't useless until unarmed 4.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: 96807af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by IrfanxHafiz** [comment]
Can confirm this is happening. Even with level 4 in unarmed, brawling will only proc damage with worn weapon when using power hit and not normal attack.
