### ISSUE TITLE
Selling things to traders and the Hub, what do they do with it?

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59744]
### Is your feature request related to a problem? Please describe.

So, it'd be nifty if the trading hubs tracked how much they received from you, either by value/category, or m:material, etc, and got improvements or quests as a result of that.

### Solution you would like.

Say you've dropped 50 lbs of electronics on them, maybe some people there would get better gear.

Or if you sell them 500 lbs of steel, they start improving some of the fences.

Probably shouldn't do it based _only_ on the player, and to not track every individual item sold, but cluster it a bit.  

Maybe specific item filters?  Could be used to set up 'we need this stuff and will pay more' economy stuff?  
They'd want steel first to make fences, then electronics stuff after, to make cameras, maybe wire and explosives after that to electrify things and setup mines, etc.

### Additional context

Why do they buy it, if they don't use it?

**Comment by Marcos6226** [comment]
I Support this idea, principally the fact that they don't need to depend only on you. But I don't see this being a reality as soon as we would like.

**Comment by chrispikula** [comment]
It doesn't need to start off with actual results from selling things, but maybe a 'we need are buying these sorts of things', to get traders that give better prices for a filter, say, m:steel, m:aluminum, scrap_copper, wire, and rock-bottom prices for other things, etc.  Just to get the indication that they've got needs that change over time, rather than my cubic meter of cracklins.

**Comment by andrei8l** [comment]
> It doesn't need to start off with actual results from selling things, but maybe a 'we need are buying these sorts of things', to get traders that give better prices for a filter, say, m:steel, m:aluminum, scrap_copper, wire, and rock-bottom prices for other things, etc. Just to get the indication that they've got needs that change over time, rather than my cubic meter of cracklins.

You can do this entirely from JSON side with [faction price rules](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FACTIONS.md#npc-factions). You might need a new rule type (`premium` to complement `markup` maybe), but the infrastructure is mostly there.

**Comment by chrispikula** [comment]
It also appears to be static, and doesn't change?

**Comment by andrei8l** [comment]
> It also appears to be static, and doesn't change?

You can use conditions to vary the price rules with time or whatever else you want (as long as it's exposed to the EOC engine).

**Comment by Amoebka** [comment]
Unless it's some unique rare items, player's contribution to the overall faction trade is likely insignificant and doesn't affect the rates of gearing/building up that much.

**Comment by chrispikula** [comment]
> You can use conditions to vary the price rules with time or whatever else you want (as long as it's exposed to the EOC engine).
That's going to be, effectively, a huge if-then-else tree, yeah?  No unpredictability?  Also, the engine tallying the player contribution isn't possible.

> Unless it's some unique rare items, player's contribution to the overall faction trade is likely insignificant and doesn't affect the rates of gearing/building up that much.

Yes?  But if there's quite a number of similar traders, then we can postulate vaguely similar rates of trading, roughly.  ~OoM.  So if the player has traded 1% of their needed x things in y time, then, with the rest of the traders, they've reached that 100% in roughly the same time.  +- some number of days.

Ideally there'd be some fuzziness to hide the breakpoints as well.  Right now I'm imagining it as something like reward-less, hidden missions with a countdown timer*.  The 'reward' is higher prices for the stuff they are looking for, and far lower for all the rest of the junk you want to offload.  

*I'm not saying use the mission system code, but bringing it up here as thought example.
