### ISSUE TITLE
Giving NPCs armor to wear does not reduce weight from own inventory when the item is gone.

### ISSUE THREAD

**Issue by YehnBeep** [CleverRaven/Cataclysm-DDA#59767]
### Describe the bug

When giving armor to a friendly NPC to wear (d->e on the dialogue screen), your inventory still displays weight as if the traded armor is still present.

### Steps to reproduce

1. Pick up a piece of armor to give to an NPC. (In my case, I used the "Hub 01 modular defense system" with an attached mantle and skirt).
2. Take note of your inventory's weight from the 'i' screen.
3. Talk to the NPC. Give them the armor via "I want you to use this item" ('d', then 'e').
4. Verify that the given armor is no longer in your inventory.
5. Notice that your inventory's weight display in the top right has not changed, despite the removal of the given armor.

### Expected behavior

Inventory capacity should reflect the currently present items.

### Versions and configuration

win 10
96807af
tiles x64

**Comment by PatrikLundell** [comment]
Is this another case of delayed updates? Filling smokers with food the weight isn't updated until you've moved (I haven't tried waiting a tick to see if it's just time and not movement related). It would still be a bug, but a less annoying one if it's temporary.

**Comment by YehnBeep** [comment]
I'm not sure. I was just trying to figure out why I was overburdened when nothing I was holding/wearing seemed to add up, and then I dropped stuff and picked it up again to fix it.

**Comment by YehnBeep** [comment]
Ok, I encountered it again.

1. The trade screen ('b' from the top level NPC interaction menu) with the NPC also causes this.
2. You're right, it's resolved when you move.
