### ISSUE TITLE
Smoke alarms (enhancement)

### ISSUE THREAD

**Issue by jjs2** [CleverRaven/Cataclysm-DDA#5976]
Buildings and houses should contain smoke alarms (which, since they use radioactive batteries, should still be operational even after the lights go out for good).  Smoking or using a brazier or otherwise creating smoke in an area with working smoke alarms should set off a loud alarm noise, alerting any zombies in the vicinity, and persisting until the smoke has dissipated or the alarm has been otherwise disabled.

**Comment by illi-kun** [comment]
My attempts to implement this were ugly hacks in gas spreading system, and I see no interest from other contributors, so closing this for reduction of number of issues.

**Comment by mugling** [comment]
> so closing this for reduction of number of issues

Especially this.

You may have seen I wrote a template message for such issue closures - the idea being to limit the inevitable necros that occur when inactive issues are closed.

**Comment by illi-kun** [comment]
I saw your template and I think it's a good idea. We don't need 1300 issues most of which are obsolete.
