### ISSUE TITLE
Ties and stylish wallet have too high damage chance when repairing compared to other more complex clothing

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#59769]
### Describe the bug

When using a tailoring kit to repair neck ties, skinny ties and other ties and also stylish wallets, the damage chance is too high compared to other more complex clothing

### Steps to reproduce

1. Carry charged tailoring kit and required patches
2. find damaged ties and/or stylish wallet and attempt to repair them
3. Observe high damage chance (see screenshot)

### Expected behavior

I've never repaired ties or stylish wallets IRL, but it's only logical that they are easier to repair then steel ballistic plates or turnout coats or military rucksacks

### Screenshots

Necktie (damage chance 6.4%):
![image](https://user-images.githubusercontent.com/50166150/181995712-1b46aae3-3414-48ce-9fe4-df993b224b1a.png)

Stylish wallet (damage chance 7.4%):
![image](https://user-images.githubusercontent.com/50166150/181995721-0aae08ca-6e67-4aba-8673-3d848ab3fecb.png)

Here is the firefighter PBA mask for comparison (damage chance 0.4%):
![image](https://user-images.githubusercontent.com/50166150/181995742-6e7cb386-66f3-4393-9bc6-72e48635fcc5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 3b41d64 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Looked for similar issues on github and discord but found none.

**Comment by anothersimulacrum** [comment]
They need a `repairs_like`, because you can't craft them.
