### ISSUE TITLE
Box battery recharger cannot be moved

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#59774]
### Describe the bug

Honestly, repeat of #57364 but with box battery charger instead. When placed down you can't drag it.

### Steps to reproduce

1. Make a Box Battery Charger
2. "G"rab it
3. Try to drag it.
4. 
![image](https://user-images.githubusercontent.com/71143790/182007880-1db2a4a4-d2d0-4d52-907a-b28941f7214b.png)

### Expected behavior

Yknow. Dragging it around like a cart should've been possible.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: b86bfea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by ANickelN** [comment]
Don't think I'm able to, but yes /confirmed as of the latest version.
