### ISSUE TITLE
Add possibility to inspect/compare location variable in JSON

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#59782]
### Is your feature request related to a problem? Please describe.

I did some research and asked a few times but afaik it is not possible to check whether a player is at a certain (specific, not generic) location / om_location.

Best you can do is have a unique type of terrain and know the player is at the location once he interacted with it [because it is needed to gain access] or walked over it, with a trap.

But it would be very handy if you could actually just compare the location var like so:
```
                            "u_location_variable": { "global_val": "cyrus_cellar_loc" },
                            "target_params": { "om_terrain": "ha_squat_cellar" }        
```

and later check that specific location, for instance like so
```
 u_at_om_location( "cyrus_cellar_loc" )
 ```
But any way will do.

It might already be possible but there's no documentation on how a location_var (target_var?) is made, what its fields are, how to compare them, etc. In either way it seems like it would only be a small change.

### Solution you would like.

being able to read a target_var set by u_location_variable [If that does what I think it does, keep track of the current location, with the second parameter possibly pointing to the nearest specific om_terrain id)

### Additional context

This way we can make unique location more easily.
And write more consistent quest-lines, keep track of the state of the world in a less generic way.

**Comment by ZhilkinSerg** [comment]
`u_at_om_location` should return id of an overmap terrain player is located on.

**Comment by LyranRenegade** [comment]
> `u_at_om_location` should return id of an overmap terrain player is located on.

eh.,. it takes an argument and checks whether you are there.. and returns a boolean.
```
    } else if( jo.has_string( "u_at_om_location" ) ) {
        set_at_om_location( jo, "u_at_om_location" );
        ```
-->        
```
void conditional_t<T>::set_at_om_location( const JsonObject &jo, const std::string &member,
        bool is_npc )
        ```
relevant part of the function:
```
const std::string &location = jo.get_string( member ); //gets the string put in the json?
        const tripoint_abs_omt omt_pos = d.actor( is_npc )->global_omt_location(); //gets the current tripoint location from the player in this case [as is_npc isn't set = false]
        const oter_id &omt_ter = overmap_buffer.ter( omt_pos ); //gets the overmap id from that tripoint
        return oter_no_dir( omt_ter ) == location; //compares the found id with the one given in the json
        ```
        
I just want to compare 2 variables how hard can that be?                
I don't want to check for an id of an overmap as that is generic and could be anywhere it spawned, I want to check for a specific target_var location as been set by 'u_location_variable'

Maybe I could use u_compare_var and then put in the saved location_variable and compare it with another [a new one I just make whenever i want to check if current location is the same],
but digging in the c++ code for u_compare_var:
```
    } else if( jo.has_string( "u_compare_var" ) ) {
        set_compare_var( jo, "u_compare_var" );
        ```
set_compare_var:
```
   void conditional_t<T>::set_compare_var( const JsonObject &jo, const std::string &member,
                                        bool is_npc )
                                        ```
so that would read set_compare_var ( JSON-data, "u_compare_var", false )
relevant part o/t function:
```
                         int_or_var<T> iov = get_int_or_var<T>( jo, "value" );
                         ```
but then it gets too convoluted for me.. 
get_int_or_var probably calls on read_var_info for complex variables

In the json I see for the "value": part of a comparison only parsed values, like a string or an integer, never another variable.
Also it is unclear whether I can stuff a target_var created with "u_location_variable" in a "u_compare_var"

It might be the functionality is already there I just can't figure out how to formulate the u_compare_var
There's no precedent in the json code and it could also be it isn't possible at all, 
Hence the issue i posted here. 
Here's hoping I get some useful response!
:)

**Comment by LyranRenegade** [comment]
awesome, thanks a lot, been trying to get this to work for a week now

**Comment by LyranRenegade** [comment]
> So you can use arithmetic and the distance function in it to compare location vars and the player/npc location.
> 
> "condition": { "compare_int": [ { "distance": [ "u",{ "u_val": "stuck", "type": "ps", "context": "teleport" } ] },

where did you get that piece of code from? Can't find it in the json or mods..

mainly so I know how to put the u_location_variable in there.

i didn't succeed in "u_add_var"-ing a location variable as well.. but i suppose that could be done as well (?)
