### ISSUE TITLE
Proportional price in item JSON does not imply proportional price_postapoc (but should!)

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#59783]
### Describe the bug

A number of items have proportional values of a base item, such as the scrap of meat, which tries to be 1/10th of a regular chunk of meat:

`    "proportional": { "weight": 0.1, "volume": 0.1, "price": 0.1, "calories": 0.1 },`

However since our scrap of meat doesn't have `price_postapoc`, only the pre-apoc price is proportional, and the post-apoc barter value of a scrap of meat ends up being the same as a chunk of meat:

<details>
<summary><b>Click to expand screenshot of meat scrap vs meat chunk</b></summary>

![meat-scrap](https://user-images.githubusercontent.com/12072/182024785-bdfef977-b1af-4441-8948-52b554f20c8a.png)

![meat-chunk](https://user-images.githubusercontent.com/12072/182024793-e7cb88aa-fc51-4f57-9ebe-f338d81ad205.png)
</details>

The solution for this specific instance is easy enough, adding `price_postapoc` gives us scraps of meat with the correct barter value:

`    "proportional": { "weight": 0.1, "volume": 0.1, "price": 0.1, "price_postapoc": 0.1, "calories": 0.1 },`

However there are a *lot* of items that just define a proportional `price`, and not a proportional `price_postapoc`, so even if we fix the current instances, this looks like a mistake which is easy to continue making.

### Steps to reproduce

1. Grab an item which defines a proportional `price`, but not a proportional `price_postapoc` (eg, the scrap of meat)
2. Notice the barter price is wrong, because proportional `price` does not imply proportional `price_postapoc`

### Expected behavior

I suggest that if a proportional `price` exists, it should *imply* the same proportional `price_postapoc` unless that's also explicitly specified.

Failing that, tests/validation to make sure we don't have proportional `price` without `price_postapoc`.

I would do this myself but I'm still grinding proficiency in our C++ item creation code.

### Versions and configuration

`cdda-experimental-2022-07-31-0201`

**Comment by chrispikula** [comment]
I'm going to suggest an alternative solution, that reframes the problem.

If an item doesn't have a price, maybe we should default back to a price of for the material, probably per weight.  That way we won't chase down endless not-the-right prices of items.

So [FLESH] would have a base price, and anything made of flesh without a value would just default to that.
