### ISSUE TITLE
Incorrect crater map extra generation

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#59781]
### Describe the bug

Sometimes the game spawn bomb on the edge of the overmap tile, and it cant interact with not loaded adjacent overmap tile correctly 
(#59717 may be related for this)

### Steps to reproduce

Walk on the map
find sometimes craters spawns incorrectly

### Expected behavior

Correct crater spawn

### Screenshots

![image](https://user-images.githubusercontent.com/67688115/182021542-8abbf51b-f34c-4a63-8bf2-4e7d43360199.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 3b41d64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Massachusetts [MA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Xedra Evolved [xedra_evolved]
]

**Comment by Night-Pryanik** [comment]
The most easiest solution is to place bomb in the center of OMT. This will work for medium-power bombs (such as on crater map extra), with explosion radius not crossing the boundaries of OMT. Consequently, this solution won't work for high-power bombs, as even one bomb with enough destructive power can have very big explosion radius which will cross the boundaries of OMT.

The proper solution would be to rework explosion mechanic so it can handle crossing the boundaries of OMT.

**Comment by Procyonae** [comment]
I don't think this is anything to do with the explosion mechanic as such it's just that the crater bomb goes off at the edge of your reality bubble so the other OMT isn't loaded, if you just spawn bombs in they work fine over OMT and even 180x180 OM tile borders.

**Comment by Procyonae** [comment]
Ok scrap that there's something weirder going on I'm getting square edges consistently without them even crossing any OM boundary
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/eb9d2596-555d-4978-85dd-a6ebdcb413cc)

**Comment by Brambor** [comment]
Solved by
 - #75567
