### ISSUE TITLE
NPC is claiming to hear my hallucinations somehow

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#59791]
### Describe the bug

I have a nyctophobic character with an evacuee start. They're hallucinating because they're in a dark evac shelter.

But the nearby NPC is claiming to be hearing my hallucinations

### Steps to reproduce

1. Make a character with nyctophobia in the evacuee start.
2. Wait for hallucinations.
3. The NPC will react as though something is there.

### Expected behavior

I expect that the NPC won't be able to read my mind?

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/182040441-87129416-6d4a-48f4-aac8-afc4322afb6a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 57fe6ea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by Inglonias** [comment]
It looks like this mainly occurs when I hallucinate robots.

**Comment by NetSysFire** [comment]
CC @Night-Pryanik.

Also @perryprog since you did #52416, it occurs the "footsteps.!" issue is present here, too.

**Comment by TiberianErin** [comment]
you could think of it as your character hallucinating the npc hearing your hallucinations

**Comment by Night-Pryanik** [comment]
I don't think it has something to do with nyctophobia trait itself. I think it's a bug in sound handling mechanics.

**Comment by Inglonias** [comment]
I agree there. Nyctophobia is just a convenient way to expose the bug.

**Comment by esotericist** [comment]
i confirmed this through a different means: in my current debug world, dino dave randomly generated with kaluptic psychosis, and his hallucinations are audible to me and, more pressingly, the guards in the refugee center.

tangentially, this results in this hilarity as the guards all collide with each other trying to get to the auditory hallucination:
![image](https://user-images.githubusercontent.com/1569754/183264579-82d65b62-ed00-4b3f-a471-1d79e0ac421d.png)
