### ISSUE TITLE
instant failure when crafting higher lever recipes at skill zero

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#59807]
### Describe the bug

When crafting items with a skill requirement greater than zero, if your skill is zero the failure seems to be instantaneous. Not just a very high chance, but INSTANT. Trying to go from from lv0 with 99% xp (due to skill rust) by continuing a lv1 craft seems to be impossible, as the craft will fail and void the ingredients before any XP is gained.

### Steps to reproduce

- level up to lv1 of a skill (such as electronics)
- start crafting a lv1 item, don't finish it
- let practical skill rust back to lv0
- note that continuing the craft fails instantly

### Expected behavior

Skill lv0 should behave like every other level. Even if the failure rate is meant to be very high, it should not be impossible. 

### Screenshots

![Screenshot from 2022-08-01 19-03-36](https://user-images.githubusercontent.com/4125929/182113551-07a71859-fd50-4ffb-b80f-6d048c39511d.png)

### Versions and configuration

latest experimental

### Additional context

Attached is a [save file](https://github.com/CleverRaven/Cataclysm-DDA/files/9232482/Dean.zip) with this issue present. Attempt to continue crafting the firestarters on the table, and note that you can destroy hundreds of wires and bits of scrap metal in seconds.

I'm not certain if this issue occurs with skills other than electronics, but I would assume it does. Will do more testing.

**Comment by PatrikLundell** [comment]
It's not tied to lvl 0, but happens at any level when you try something that's "too difficult". I don't know exactly when "too difficult" kicks in, and there's no info on it apart from it being above your skill level.

**Comment by jagoly** [comment]
I see, so are you saying there is some kind of hard cuttoff point where it goes from "difficult" to impossible? Just now, trying to craft a longbow (fab 5, archery 3) with fab skill 4 and archery 0 doesn't have the issue. It gets quite some way through the craft before failing (which is how I expect thing to work). So unless the insta-fail kicks in with something like a fab 9 recipe at skill 4 it does seem to be tied to lvl 0.

**Comment by jagoly** [comment]
Just for testing I used debug mode to unlock all recipes, and tried to craft a land mind (devices 5) at skill 1, and there's no issue there either. So I am pretty certain it's tied to lvl 0. 

Wild guess, but maybe there's some multiplication by the skill level somewhere in the formula, which would cause an instant failure at lvl 0. Guess I'll have to try and look at the code.

**Comment by jagoly** [comment]
Ah, right, this is indeed a duplicate. I did try to find an existing issue, guess I used the wrong search terms. Looks like my guess about a multiplication by skill level was correct anyway.
