### ISSUE TITLE
Coverage and protection info is incomprehensible and no documentation is available

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59820]
### Describe the bug

The coverage and protection information on various clothing and armor pieces is currently not possible to understand, creating significant difficutly in evaluating armor, compraring items and as such, making educated decisions about character equipment.

Based on an example item "heavy ballistic vest" with 2 ESAPI and 2 ESBI plates, here are the specific problems with its description:

![armor1](https://user-images.githubusercontent.com/55463047/182266003-0d2cf379-090e-4f4e-b5b3-b6f9706141ed.png)

1. The coverage percentages (100%, 48%, 15% on the screenshot) - what is their practical meaning? Does 15% mean that armor will mitigate the damage done to this bodypart only in 15 attacks on average out of 100, and always for 100%, or does it mean something else?
2. The breathability (50%, 51% on the screenshot) is expressed as a percentage.
 2.1. As a percentage of what?
 2.2. Is a higher or lower value better in hot temperature? Cold temperature? Does it affect windchill?
 2.3. What breathability percentage would a body part without any item worn on it have?
 2.4. What does breathability over 100% present on some items represent, and how does it compare to wearing nothing at all?
3. What do multiple protection values represent
 3.1. The percentages (5%, 95% on the screenshot): what are they percentages **of**? 5% of what? 95% of what?
 3.1.1 What do the colors represent?
 3.2. The absolute values for damage types  (1.00, 9.80 on the screenshot): why are there two of them?
 3.2.1 What do the colors represent?
 3.2.2 Why are there two of them only on some parts of the armor, but not others (on screenshot: on torso, but not on the hips)
 3.3 What is the practical meaning of the protection value? Is it a flat reduction to the incoming damage type, or something else?
4. What do multiple coverage values (Default: 80 Ranged: 95 Vitals: 100 on the screenshot) represent
 4.1. What are the units of these numbers? 80 of what, bananas? 100 of what? Volts per kilogram squared?
 4.2. Default, Ranged, Vitals - what is the practical meaning (functionality) of each of these categories?
 4.2.1. How do these values interoperate with the coverage values for the armor itself, listed earlier? For example, 48% coverage of arms with Default: 80 listed in this section - how does this work? 

![armor2](https://user-images.githubusercontent.com/55463047/182266016-1006424f-25e7-40b0-8057-73ad74f2ff30.png)

5. Coverage of the inserted armor plates:
 5.1. What do (R) (M) (V) labels mean?
 5.2. What units are the (R) (M) (V) values (27 27 0 on the screenshot) in?
 5.3. What is the practical functionality of these values?
 5.4. How do the protection and (R) (M) (V) values of the plates interoperate (stack? addup/augment in some other way?) with the protection and coverage values of the armor itself?

### Steps to reproduce

1. Make a new character
2. Obtain a heavy armor vest with plates
3. Look at the item description
4. Understand nothing
5. Read the game documentation
6. Complete the game tutorial
7. Look at the item description again
8. Still understand nothing

### Expected behavior

1. Read the game documentation and/or complete the tutorial
2. Make a new character
3. Obtain a heavy armor vest with plates
4. Look at the item description
5. Understand everything in it

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-08-01-0625
Mod list: default

**Comment by kholat** [comment]
>literally me as well
THE NUMBERS MASON, WHAT DO THEY MEAN!?

**Comment by Lamandus** [comment]
A simplified view would help a lot. Rather than giving values, it should say "somewhat breathable" etc.. those who really want to check, should refer to external sources. A lot of games handle it that way.
Noone will say that they prefer one piece of clothing because it got 5 percent more breathability.

**Comment by Raikiri** [comment]
I feel like I can answer every mechanical question from the OP about how it works, but I can't answer why it needs to be so complicated.

**Comment by Cenness** [comment]
re third point:
if player thought that they may have a workable hypothesis of what it may mean, it will be shattered to nothing when they'll encounter nomad bodymesh or tempered plate armor with this:
![image](https://user-images.githubusercontent.com/9906246/224506653-b5e88728-3efd-4ef7-acdf-060c792ef61c.png)
