### ISSUE TITLE
Radio Tower (North Road Entrance) Basecamp - Fourth Wooden Panel Structure does not place with a roof.

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59836]
### Describe the bug

It's cold in that building - some dingleberry NPC forgot to build a roof! We'll have him flogged.

(I've only built 4 all-wood buildings so far, so it might be only a one-off, or maybe other structures/materials are also missing rooves?)

### Steps to reproduce

1. Spawn a north-facing radio tower (direction may or may not be relevant?)
2. Spawn an NPC, give him huggles, set up basecamp
3. Get him to build 4 (or more!) wooden structures with spawned materials (material is probably relevant, considering how these are coded, but maybe check the other ones just in case?)
4. King Kong yourself up the stairs and check out the nice hole to the south

Alternatively!
1. Look at code
2. Note whether the fourth (or others) basecamp wooden panel structure for north-facing radio towers has a roof
3. fix if not?

### Expected behavior

Rooves! I expect roofing.

### Screenshots

![image](https://user-images.githubusercontent.com/4212389/182484319-ce0a1520-3903-4c73-b4f2-1462622879a8.png)
![image](https://user-images.githubusercontent.com/4212389/182484346-9834302f-dae0-4e15-a4f3-c26cfcb9fe5b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: 47d49b1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

and i thought my last bug report was weirdly specific...

**Comment by descan** [comment]
Having subsequently built the remaining 2 wooden panel buildings, they also spawn without roofs.

**Comment by PatrikLundell** [comment]
Looks like this is related to #59833, possibly because the building rotation is different.

**Comment by descan** [comment]
> Looks like this is related to #59833, possibly because the building rotation is different.

Curious, because the first three built their roofs fine. If it was an issue with the footprint itself... Unless it was a new bug introduced between when I built the third and when I built the fourth.

**Comment by PatrikLundell** [comment]
Hm, didn't someone make a change recently to adjust what the roofs looked like, because they all looked alike? It might be worth to see if that could have caused it (in which case it could be something that's changed between your last two buildings).
