### ISSUE TITLE
[Interface/Tilesets] Add ability to specify different 'unknown' tiles for different z-levels

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#59851]
### Is your feature request related to a problem? Please describe.

Right now 'unknown' tile is the same for every z-level.
For z-level <0 it became too eyestraining as is covers all field of view.

### Solution you would like.

It would be great if one can define separate tiles for different z-levels.

Adding multitile for 'unknown' tile is a nice bonus!

### Describe alternatives you have considered.

Leave it as is

### Additional context

@Night-Pryanik , could you please take a look?

**Comment by Night-Pryanik** [comment]
Well, I guess it's possible to add simple checks for different z-levels and add separate OMTs for them. I'll try to look into this tomorrow.

However, I know nothing about multitiles, so I doubt I can do something on this matter.

**Comment by vetall812** [comment]
> Well, I guess it's possible to add simple checks for different z-levels and add separate OMTs for them. I'll try to look into this tomorrow.
> 
> However, I know nothing about multitiles, so I doubt I can do something on this matter.

If you'll see something like 'allow_multitile' - just set it 'true' then. 
Oh and thank you!
