### ISSUE TITLE
Rework of Trapdoor Spiders attack pattern.

### ISSUE THREAD

**Issue by Marcos6226** [CleverRaven/Cataclysm-DDA#59863]
### Is your feature request related to a problem? Please describe.

Right now Trapdoor Spiders attack pattern and behavior are unrealistic and unbalanced. They are generally in great numbers and gives little to no visual indication of its presence.

As Labsenjoyer said on the discussion topic:
`They’re basically giant worms who are faster than anyone without the quick trait or bionics/mutations, poison you, and have a grab. By itself this isn’t too bad, the real issue is the numbers they come in. I’ve seen/killed 18 in about a day, including two of the giant ones which have higher HP than hulks. If you have guns then it’s not too hard to dispose of them, but getting a clown car’s worth of spiders on you with no warning and no indication of their presence on the map seems a little unfair. One spider? go for it. Two? sure. Five, even? still reasonable. But more than that is a bit excessive.`

Additionally it's giant counterpart have way too much HP, making it a pain to deal with.

### Solution you would like.

One solution suggested by DCHY is to create a visual indication of its presence, as well as changing its behavior from direct pursuing its pray to being a opportunity hunter, making traps and waiting for its pray to trigger it and only then attacking. One way to do that is to make them surround itself in cobwebs, only getting out if necessary or if provoked.

Below is a direct quote of DCHY suggestion, taken from the forum.
`All problems will be solved if we recycle these spiders to become MORE realistic analogues.
Funnel spiders don’t dig incredible underground passages, they shouldn’t be able to do it. the most logical method would be to recode the spiders so that they could be buried only after a while without the task of “killing someone”. at this moment, their vision, sense of smell and so on should be greatly weakened, up to 1 cell in all directions. and, like the original spiders, he must create a web around his burrow. as a result, we get the fact that the spider is sitting in a hole, which we can see because of the web in the neighborhood, and if someone steps on it, he will be directly in the vicinity of the spider, because of which he will “get out” of the hole and start attacking. it will be quite realistic, and will not spoil the gameplay. (Like in pic)`

### Describe alternatives you have considered.

We are open to any other suggestions and ideas.

### Additional context

![548fd2a2d7fd10b7debdfff068c2fd8c6411283b](https://user-images.githubusercontent.com/49823690/182699122-f44cda4e-f3a1-48d9-b958-3700904447d8.jpeg)
Picture representing the way Trapdoor Spiders could visually indicate its position and how players could be attacked. Made by DCHY.

This issue is opened based on a topic in the Cataclysm official discussion forum. Post link for reference [Here](https://discourse.cataclysmdda.org/t/giant-trapdoor-spiders/28047)

idealizers of this suggestion.
[DCHY Profile](https://discourse.cataclysmdda.org/u/DCHY)
[Labsenjoyer profile](https://discourse.cataclysmdda.org/u/Labsenjoyer)

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/giant-trapdoor-spiders/28047/9

**Comment by Marcos6226** [comment]
> This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:
> 
> https://discourse.cataclysmdda.org/t/giant-trapdoor-spiders/28047/9

Thank you, I will check it and maybe expand this suggestion, of course I'm open to any ideas.

**Comment by Night-Pryanik** [comment]
Related: #56133.

**Comment by Marcos6226** [comment]
> Related: #56133.

Thanks, I'm going to check it.

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/63853
