### ISSUE TITLE
Floor type under existing Fence structure will vary depending on how fence is removed.

### ISSUE THREAD

**Issue by TripleBakedZiti** [CleverRaven/Cataclysm-DDA#59867]
### Describe the bug

If you deconstruct an existing fence (it was there on world creation) on a dirt floor tile it will remain a dirt tile.
If you hit the fence with a vehicle and destroy it, the floor tile will be a rock floor tile instead of a dirt tile.

### Steps to reproduce

1. Find a Fence structure built on dirt that was generated on world creation.
2. Drive a vehicle into it and destroy it.
3. Observe floor tile.

### Expected behavior

Floor tile should remain the floor type that the fence was originally built on. I.E. dirt, grass, etc.

### Screenshots

![rock floor](https://user-images.githubusercontent.com/110523573/182715349-57cb7726-64d1-46f8-8d87-1dae3b0476c2.png)
![rock floor 1](https://user-images.githubusercontent.com/110523573/182715355-29219900-810f-4766-bd35-9c7d996b5609.png)
![rock floor 2](https://user-images.githubusercontent.com/110523573/182715358-3ab5e55c-eca5-40ff-900c-7c6b0935618a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Just to be clear - technically fences aren't built on anything. Fence is a "terrain" in game terms, much like dirt, grass, or rock floor, so there's nothing underneath the fence, since there could be only one terrain on a given tile.

Could you please tell exactly what type of fence demonstrated this behavior?

**Comment by TripleBakedZiti** [comment]
Okay, that's fine. You get the idea though.

This particular fence is a split rail fence. I didn't test it on any other types.
