### ISSUE TITLE
Moonshine Mash can only be made from Pumpkins

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#59877]
### Describe the bug

Moonshine mash can only be made from pumpkins for some reason, weird considering you can make moonshine from pretty much anything with any sugar in it, or just direct sugar if you want a shitty moonshine.

### Steps to reproduce

Open the game and look at the recipe.

### Expected behavior

Moonshine should be the catch-all booze you can make if you just want to throw stuff together, not the pumpkin brew of choice for some reason.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: d4be690 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungus [No_Fungus]
]

**Comment by Cimanyd0** [comment]
[From the Hitchhiker's Guide, there are two recipes for moonshine mash](https://nornagon.github.io/cdda-guide/#/item/brew_moonshine):
1. made from corn (and water, sugar and yeast): written in "The Homebrewer's Bible" and "family cookbook"
2. made from pumpkins (and water, sugar and yeast): written in "Out of the Holler and into the Home: A guide to home distillation" (which I will refer to as `distilling_cookbook`) and "family cookbook"

Moonshine mash ferments into [moonshine wash](https://nornagon.github.io/cdda-guide/#/item/wash_moonshine), which isn't useful on its own. It can be distilled into:
1. [moonshine](https://nornagon.github.io/cdda-guide/#/item/moonshine): written in `distilling_cookbook`
2. [ethanol](https://nornagon.github.io/cdda-guide/#/item/chem_ethanol): written in "chemistry textbook" and `distilling_cookbook`
Ethanol cannot be drunk on its own but can be mixed with water to make [vodka](https://nornagon.github.io/cdda-guide/#/item/vodka) or used for some other purposes.

There are several issues here:
1. you can't make moonshine out of corn with `distilling_cookbook`, just pumpkins
2. you can make moonshine wash (out of corn) without `distilling_cookbook`, but you can't turn it into moonshine without that specific book, leaving you with useless moonshine wash (or, at best, ethanol with a chemistry textbook)
3. [`distilling_cookbook` is pretty rare, outside of regional schools](https://nornagon.github.io/cdda-guide/#/item/distilling_cookbook)

You can make alcohol directly out of sugar with [vodka wort](https://nornagon.github.io/cdda-guide/#/item/brew_vodka).

**Comment by ANickelN** [comment]
I think that is exactly what got to me.  I had the option in the crafting menu to create moonshine mash from pumpkins, but not from corn so I didn't even think to check HHG.  Seems that the books need to be fixed.
