### ISSUE TITLE
`professional_zombie_gear` item group can cause errors on monster death

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#59873]
### Describe the bug

It is possible a monster death can create an error message leading to CI test fails.
https://github.com/CleverRaven/Cataclysm-DDA/runs/7653184359?check_suite_focus=true#step:16:430

### Steps to reproduce

I have not been able to reproduce the issue with the seed from the failed test and in another 60 random test runs locally.

However digging into the test code I can fairly safely conclude the cause is the chance for `professional_zombie_gear` in the `default_zombie_death_drops` item group.
`professional_zombie_gear` contains the group `hardware_plumbing`, which in turn contains `plumbing_clothing` which has the explicit comment `"//2": "Not intended to be a set of clothing for NPCs or monsters"`, most likely because it does not guarantee in any way that proper container items are spawned for any additional loot to be put in, since it seems to only spawn one item from the list and not a set of gear the zombie would be wearing.

### Expected behavior

Items spawn without issues. However in this case it might be unlikely enough to not be a problem.

### Versions and configuration

bc8d87c8203708c2580c89370a253e190f1ef7e4

**Comment by Stadler76** [comment]
I assume, that this one is related: https://github.com/CleverRaven/Cataclysm-DDA/runs/7708088941?check_suite_focus=true#step:16:259

**Comment by mqrause** [comment]
Presumably another case: https://github.com/CleverRaven/Cataclysm-DDA/runs/7868235039?check_suite_focus=true#step:16:568
