### ISSUE TITLE
Polishing Stone (item) takes a lot of time to craft

### ISSUE THREAD

**Issue by MatesWithoutBorders** [CleverRaven/Cataclysm-DDA#59879]
### Is your feature request related to a problem? Please describe.

The recipe for the 'polishing stone' item is very heavily influenced by the proficiencies Knapping and Speed Knapping. Having neither Knppg or SpdKnppg multiplies the time to craft by 7.5, and not having SpdKnppg multiplies the time by 4.5. With both proficiencies, the recipe takes 20 hours to complete, which, combined with the time requirements, means the item is quite inefficient to craft.

### Solution you would like.

Reducing how much Knapping/Speed Knapping impact time, changing the recipe to better reflect how long a process it'd be, or reducing the base time in the recipe from around 20 hours to 4. Alternatively, adding another recipe utilizing another tool with above 2 q:hammering instead of a rock, which was a quality of 1.

### Describe alternatives you have considered.

Looting an item with q:grinding elsewhere.

### Additional context

The recipe itself uses a rock as a tool and not an item with hammering quality, and the 'main' component is a large rock, reduced from 6 liters to 3, and from 15.77 kg to 8 kg.

**Comment by liminalRoar** [comment]
Could be a great recipe for #59839 if implemented

**Comment by anothersimulacrum** [comment]
Why should it take less time? I don't see the problem here.

**Comment by FeelsBadMatey** [comment]
> Why should it take less time? I don't see the problem here.

For an item that's essentially just a rock, it doesn't seem like it should take more time to craft than an anvil without any proficiencies in blacksmithing or whatnot.

**Comment by anothersimulacrum** [comment]
It's not essentially just a rock, it's a rock that's been ground down to have a surface suitable for working. Grinding rocks takes a long time.

**Comment by FeelsBadMatey** [comment]
> It's not essentially just a rock, it's a rock that's been ground down to have a surface suitable for working. Grinding rocks down like that takes a long time.

I apologize if I seemed dismissive - I've realized my issue is that the recipe's utilization of just a rock as the tool seems inefficient, but I didn't realize that while making the original post.

**Comment by liminalRoar** [comment]
anothersimulacrum, do you disagree that the time to craft such a thing could be diminished with the right tools?

**Comment by pjf** [comment]
I would like to argue that at the very least, speed knapping (and possibly all knapping) should be removed as a requirement. One doesn't make polishing stones by flaking flint or chert (which knapping relates to), instead they're ground flat surfaces, which while labour intensive, requires more elbow grease than skill.

**Comment by Vzor-** [comment]
This is the only pre-metal item with grinding 2 or more. The metal chisel crafting requires grinding 2 to make, and the metal fileset requires the metal chisel. Meaning nearly all forged items are locked behind the 6-day craft time of the grinding stone. 

I think knapping should be removed from this, and the crafting time should be much shorter. In the real world it is trivial to sharpen metal on unfinished stone*. 

* source https://www.youtube.com/watch?v=5LsvsFHD5Jw
he also has sharpened a knife on a brick, and on a brick wall.

**Comment by Brambor** [comment]
@Vzor-
> (...) nearly all forged items are locked behind the 6-day craft time of the grinding stone.

Obtaining a grinding stone doesn't have to take 6 days as it is faster to just:

1. practice the knapping proficiency to 100%
2. practice speed knapping proficiency to 100%
3. craft grinding stone

I don't remember how much time this approach takes tho.
