### ISSUE TITLE
Item examination page: Add compare hotkey and item scrolling.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59890]
### Is your feature request related to a problem? Please describe.

Item compare is a useful feature and i am always bummed that there is no way to do this when using regular inventory or when examining an item. I think we can make the item examination page more useful with some additions.

### Solution you would like.

Add a hotkey when examining an item to compare it with another. This should open the compare screen with that item selected and the ability to select a second item for compare. Closing that window should return and allow another item to be compared to the first, and closing the compare screen altogether should probably return to the item examination window.

Adding _compare_ to the item examination screen, i suggest we can alter `c` _"change side"_ to `s` _"switch side"_ and then add `c` as _"compare"_.

Additionally i would like to add the ability when examining an item to quickly switch to the next and previous item from the list you are examining from. For example, `e` examining from `i` inventory will allow you to cycle through items however they are sorted in inventory currently, while examining from the `V` view menu will allow scrolling through the items listed there. I think this could be set to left/right arrow keys quite well, since up/down arrow keys are used for scrolling through options.

### Additional context

#59891 is related and will discuss general inventory ideas more. The item examination additions here would be an easy prerequisite for anything discussed there, which will involve much larger changes.

**Comment by Zireael07** [comment]
Compare should definitely be accessible from inventory/examine.
