### ISSUE TITLE
Pictures of an impossible shape should cause their attack

### ISSUE THREAD

**Issue by Chrisbehk** [CleverRaven/Cataclysm-DDA#59894]
### Is your feature request related to a problem? Please describe.

When you look at a picture of the impossible shape you don't experience the negative effects that seeing it in reality causes. 

### Solution you would like.

When looking at a picture of the impossible shape, you should experience the negative effects of looking at it all over again, given that it is a memory based attack and you are refreshing your memory of it.

### Describe alternatives you have considered.

I have considered that a photo of the impossible shape is just a 2d image of it rather than the 3d moving version your character sees in real life, and that perhaps this wouldn't cause the debuff to trigger all over again.

But i am of the opinion that given the debuff is you saw something it hurts to remember, seeing it all over again in picture form will refresh the memory and cause the hurt all over again.

**Comment by liminalRoar** [comment]
perhaps the picture does not capture the true essence? So the description for the picture includes something about that. Or a message appears in the log about "the photo unsettles you so you look away". Something where there isn't an actual debuff from just looking at the picture, but the ghastly nature is acknowledged at least?

**Comment by Chrisbehk** [comment]
I believe mechanically, the creature does an attack on you when you are able to see it, and it doesn't have a 100% success rate, but the message you get when the attack lands is "You get a very clear view of the impossible shape" or something to that effect. then you get the morale debuff, the morale debuff itself says "you saw something that hurts to remember" my interpretation is that over time, your brain does a good job at jettisoning or otherwise suppressing the memory to allow you to continue to function, and taking a picture and looking at it are just stupid ideas. 

Stupid ideas I think should be implemented for flavour, if this does get merged i may also suggest being blackout drunk or otherwise having an impaired memory could protect you from the attack.

**Comment by liminalRoar** [comment]
I guess i wasn't sure if it is technically something the monster has imposes on you mentally. Where you have to be withing physical range of him. It is a nether creature so. I felt like the reason it causes the effect is more supernatural than just something so actual ugly it hurts our brain. But maybe that is the case.
