### ISSUE TITLE
Formatting error in `game_balance.json` leads to silent CTD when starting game

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#59892]
### Describe the bug

Basically, what's in the title. Miss a comma somewhere in this file, or add an excessive one, and you won't be able to start a game. No messages at all, no meaningful explanation in `debug.log`.

### Steps to reproduce

1. Open `game_balance.json`.
2. Remove comma somewhere, save changes.
3. Try to start the game.
4. CTD.

### Expected behavior

No silent CTDs and some type of error message telling me what's wrong.

### Screenshots

None.

### Versions and configuration

0.F-10407, Windows 10 x64.

### Additional context

20:31:19.740 : Starting log.
20:31:19.740 INFO : Cataclysm DDA version 0.F-10407-g8f8b8d9550
20:31:19.740 INFO : [main] C locale set to Russian_Russia.utf8
20:31:19.740 INFO : [main] C++ locale set to 
20:31:19.740 INFO : SDL version used during compile is 2.0.10
20:31:19.740 INFO : SDL version used during linking and in runtime is 2.0.10
20:31:19.762 INFO : Number of render drivers on your system: 5
20:31:19.762 INFO : Render driver: 0/direct3d
20:31:19.762 INFO : Render driver: 1/direct3d11
20:31:19.762 INFO : Render driver: 2/opengl
20:31:19.762 INFO : Render driver: 3/opengles2
20:31:19.762 INFO : Render driver: 4/software
20:31:19.776 INFO : [options] C locale set to en_US.UTF-8
20:31:19.776 INFO : [options] C++ locale set to en_US.UTF-8
20:31:19.776 INFO : Setting language to: 'en'
20:31:19.776 INFO : [i18n] Scanning core translations from lang/mo/
20:31:19.776 INFO : [i18n] Scanning mod translations from ./mods/
20:31:19.776 WARNING : opendir [./mods/] failed with "Системе не удается найти указанный путь.".
20:31:19.867 INFO : Active renderer: 3/opengles2
20:31:20.153 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
20:31:20.153 INFO : ColorModulatedGeometryRenderer constructor() = FAIL. tex_enable = 1
20:31:20.204 INFO : Setting language to: 'en'
20:31:20.299 WARNING : opendir [./mods/] failed with "Системе не удается найти указанный путь.".
20:32:19.373 : Log shutdown.

**Comment by chrispikula** [comment]
You mean `game_balance.json` , yeah?
/confirmed.

**Comment by Night-Pryanik** [comment]
Yeah, exactly.
