### ISSUE TITLE
Inventory screen rework: Views, Sorting, mouse support, compare, other features

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59891]
### Is your feature request related to a problem? Please describe.

Inventory management is one of the most crucial aspects of CDDA and anything we can do to increase accessibility, efficiency, and function will make a vast difference in user experience. I have some thoughts on how we might improve this feature.

### Solution you would like.

Add the following features to `i` inventory screen:

- [ ] View "buttons" above inventory (Category, Pocket, Detailed)
- [ ] Add detailed view with description bar and columns
- [ ] Quick menu access for items
- [ ] Integrate compare function into standard inventory screen
- [ ] Additional mouse support for new features
- [ ] Add colors to inventory items (revive #46329)

---

**View buttons.**
New options up top for changing inventory view, selectable with mouse click or hotkeys. Can be added near inv info (weight, free volume, etc) or added below as a separate bar. Inventory should save which view is used upon exit and reopen in that view. 3 views that i can think of for now.
- Category (default) 
- Pocket view (`;` currently in inventory screen)
- Detailed view (details discussed in detail in next section about detail view. details.)
- No category/group view (especially useful if the previous becomes a toggle instead of its own view. discussed further down)

I would recommend that in addition to or instead of hotkeys, we let `TAB` and `BACKTAB` cycle through the views.

---

**Detailed View**
This adds some of the usefulness of AIM into regular inventory. This view will allow item details to be listed in sortable columns. Sorted with corresponding hotkeys. Mouse support should be added to click on the top of columns for sorting. How items are sorted with the categories could be an issue. I would say it should sort items, but not mix around any categories. Example for how this can look (sorry, just a quick excel sheet):

![inv-preview](https://user-images.githubusercontent.com/92204064/182897536-c53beab0-35c4-424e-a670-43e1483921da.PNG)

Another option is to make the detailed view a toggle option up top instead of a separate view. This allows the detail columns to be shown on the selected "view" mode discussed previously which can now include _Category, Pocket view,_ and _No grouping_ (for easy sorting by detail columns instead.

Most powerful yet would be a way to customize the detailed view and add/remove columns of information. For example be able to display item damage, price, etc.

---

**Quick access menu**
This one will require some work.  The idea is a small pop up window that can be activated for any item while on the inventory page. This window can contain the following and more: **activate, wield, wear, drop, and close(menu).**. Ideally this menu would pop up right below the item highlighted - above in the case of the item being towards the bottom of the screen. Alternatively it could pop up in the center of the screen, but should have the item name in a top bar of the quick access window. We could even allow customization for what options are available on the quick menu.

My thoughts with inventory are `e` can open the item for examination while `ENTER` or another key will open the quick access menu. You will be able to arrow key through the quick access menu and select an option with `ENTER`. Hotkeys could also be used. `ESC` will close the quick access menu.

With mouse controls, left clicking an item will open it for examination, right click will open the quick access menu, and middle click can select the item for comparison. Mouse can also be used with the quick access menu.

---

**Add compare to inventory**
I suggest adding `c` as the hotkey to select a highlighted item for comparison. This will pop up the check column to the left of items to select another (viewed as - and + ) This is not as simple as just bringing up the compare screen. I would like the comparison to be a function that can be opened on the various inventory view modes without losing place in the item list.

`c` would interfere with potential hotkeys for items, however, so this could be changed to another alternative.

---

**Mouse Support**
Allow the mouse to select view options, hit sort buttons in detailed view, add items for comparison, and open the quick access menu. Some of my ideas include using the right mouse click for specific functions, but if we use that for `ESC` to close out of menus it could conflict. One option is that since inv is not a full screen window, mouse clicking anywhere outside of the inventory screen can close the menu. The same can be applied with the quick access menu.

---

**Colored inventory items** Features from the closed #46329 which was abandoned but desired. Can possibly be a toggle on the top bar to turn extra colors on/off.

---

### Describe alternatives you have considered.

- Add `i + i` pocket management to the inventory view list, integrating it into inventory more.
- Add more columns for the detailed view to list other aspects of the items.
- Complete rework to UI, but that is another issue.
- Not implementing all features but only some.
- Ability to compare more than 2 items and scroll horizontally across them could be useful, but that is for another issue

### Additional context

Probably some relevant suggestions and PRs i am not aware of. I'd be happy for anyone to link related issues and add any suggestions!

I will try to update this more and clarify if needed, but for now i think this is enough.

**Comment by PatrikLundell** [comment]
I probably miss something, because I can't see what the quick access view would add. To me it just looks like a stripped down examine menu that contains none of the info and a subset of the actions.

**Comment by liminalRoar** [comment]
I was thinking of this feature as helping mostly with mouse controls. Imagine using just a mouse, scrolling through your inventory, right clicking an item and quickly dropping it. You could potentially have the action execute but stay in the inventory menu.

For keyboard play, it is less useful, but i think still worth considering. It allows you to do more actions quickly from the inventory, Especially if the feature could be used anywhere you are scrolling through items. For items outside your personal inventory the drop action would be replaced with pick up, so say you have a pile of loot to look through. You scroll through the items, find a item you want to wield and quickly do so, staying on the page, arrow down a little and decide to wear a new vest, then pick up a couple items.

My main thoughts are adding efficient ways to perform actions and lessening the need to open 5 different menus to do things. Especially with your inventory, i think we can integrate more QoL features. Someone pointed me to #50015 which shares some sentiments.

**Comment by PatrikLundell** [comment]
Staying in the inventory is definitely a useful option, and from the different locations you mentioned, but I still don't see much point in a stunted menu that can only be used for some things, and thus only some of the time. I'd rather see the examine menu opened with and without return to whatever menu you came from, than one you can return from and perform some actions but not see anything, and a full functionality one you can't return from.

The stunted menu looks like a work around to emulate a press to get menu, scroll down, release on (hopefully) the intended option type mouse interfaces that are all over the place nowadays.

**Comment by liminalRoar** [comment]
Well that is a decent point. I guess i still think it could be useful, at least for mouse. Hopefully someday if/when there is a big UI rework an inventory (and character page) can be implemented that is designed to work easily with any input/os. So perhaps an inventory screen with multiple tabs that can be switched through. For example:

**INVENTORY**
View      Compare      Drop      Nearby      Details

Or something like that, idk. Something that can be switched quickly on keyboard as well as mouse, and touchscreen.

**Comment by PatrikLundell** [comment]
Better UIs is always welcome (except by those who have hard coded themselves into the current ones, I guess).

However, I don't think the example makes that much sense, as it matches content selection with actions and display. Regardless, it's useful to explore ideas and hopefully narrow down on ones that most people think are good before wasting time on implementing ones that would be rejected.
- Being able to select what level of details you want to see may be useful, although it could turn out to be more hassle than it's worth in practice. Regardless, the default level should be usable by everyone, in particular newbies. A tailoring screen with quick presets might be useful, in particular for users with tiny screens who may want to see as many items as possible most of the time.
- Selection of what items to view (inventory/nearby/two locations(basically AIM)/... is another set of settings that would be useful to be able to change without leaving the screen.
- Changing the mode to multi drop/pickup/move/compare/... would likewise be useful.
The settings of the latter two sets ought to depend on how you got to the screen, i.e. a "go to this screen" command would use the parameters last used, a "go to pickup menu" one would have the pickup mode pre selected, and either use a standard view selection or the last one with pickup mode (if so, would it matter if the pickup mode was selected within the menu or you got there via a dedicated pickup command? probably the former).

Complicated, and with lots of room for opinions...
