### ISSUE TITLE
Exodii Mission 2: Find the Lost Warehouse

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59905]
### Is your feature request related to a problem? Please describe.

See https://github.com/CleverRaven/Cataclysm-DDA/issues/59900

The Exodii missions haven't yet been implemented, and I am worried that my life commitments will keep them out of my reach for a long time. I am posting my plan for their missions in the hopes that someone will help me implement parts of them. If that happens, I would be more than happy to contribute with dialogue and editing and some of the components as I have time.

Of course I may get to this myself, in which case having it written up will keep me from forgetting what I wanted.

### Solution you would like.

Preceding mission: [Investigate the Hub](https://github.com/CleverRaven/Cataclysm-DDA/issues/59901)
- [Refining mission 1](https://github.com/CleverRaven/Cataclysm-DDA/issues/59904) is not necessary to add Mission 2.

#### Mission 2: Find the Lost Warehouse

This mission can proceed regardless of the specific outcomes of mission 1. However, we might change around dialogue depending on how that mission went.

- Rubik wants you to track down a warehouse with a missing transponder and place a booster to help them locate it.
- They give you a clear description of the warehouse, which we can write after the warehouse has been mapped.
- On this first pass, to complete the mission you'll just have to hunt around for it. The next improvement to the mission will add more complexity.

**Dialogue**

I have begun writing the dialogue [in this git gist](https://gist.github.com/I-am-Erk/2ec281eee9dd52032e77b9fbc729d49d). It's not quite done.

**Mapping**
- The warehouse should be fairly small and is sealed. A few zomborg are scattered outside.
- The exodii are storing a lot of basic scrap here, but the value of the place is that it contains 3 nearly functional autodocs (stored as items in crates). These will not be added on a first pass of this mission: initially, just add scrap metal and stuff like in any other exodii storage pod.
- The map will need to have an exodii antenna on top of the base, this is the mission target. You'll need to use the comm rebooter there.

**New game items**
- We also need an "exodii comm rebooter" device that can be used in the new map to boost the antenna. Interact with the antenna, get the option to use the booster, remove the booster from inventory and set a variable to true.

**Paths to completion**
- Option 1: Find the warehouse on your own, activate the antenna using the comm rebooter, return to Rubik. This increases Rubik's trust in you quite a lot.
- Option 2: Find the warehouse on your own, return to Rubik without using the comm rebooter, explain how to get there with directions. This will make no major difference on the quest outcome but will produce some funny dialogue from Rubik about your inability to use the tools they gave you (and it offers players an 'out' if they lose the rebooter somehow).

### Describe alternatives you have considered.

We could potentially switch the order of missions 2 and 3, but I think two "contact a faction" quests in a row gets a bit old.

### Additional context

This is a very perfunctory version of this mission but I would like it kept separate from all the nuanced interactions, to be added later, because adding and debugging the map itself is already enough work.

**Comment by PatrikLundell** [comment]
I believe this mission is a good place to add dialog about Exodii warehouses, the difference between the variants with the two "guard forces", and how the Exodii feels about you looting each version (I still don't know, although I have guesses).

**Comment by Termineitor244** [comment]
I think this could be considered as completed since #67695 was merged, right? There are already other issues for the improvements of this specific mission.

**Comment by I-am-Erk** [comment]
Sure
