### ISSUE TITLE
FR: When low on health, overlay a "low HP blood splatter" on the edges of game screen.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#59902]
### Is your feature request related to a problem? Please describe.

I just died to an electric zombie. I forgot it deals damage even if you have sensory dulling, and since I walked and fought normally I didn't realize my torso was at 10% before engaging.

### Solution you would like.

When low on health, overlay a "low HP blood splatter" on the edges of game screen.

I've been thinking of something like this but less of an eyesore, something to indicate that "shit's fucked" even if you're as tunnel visioned as me.

![Blood_Splatter_CoD2](https://user-images.githubusercontent.com/61629226/182939163-f94832a9-f4a8-4354-8212-1e9e43b30a20.jpeg)

**Comment by liminalRoar** [comment]
CODDA
