### ISSUE TITLE
Exodii Mission 1: Hub Contact

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59901]
### Is your feature request related to a problem? Please describe.

See https://github.com/CleverRaven/Cataclysm-DDA/issues/59900

The Exodii missions haven't yet been implemented, and I am worried that my life commitments will keep them out of my reach for a long time. I am posting my plan for their missions in the hopes that someone will help me implement parts of them. If that happens, I would be more than happy to contribute with dialogue and editing and some of the components as I have time.

Of course I may get to this myself, in which case having it written up will keep me from forgetting what I wanted.

#### Mission 1: Investigate the Hub 

Scouts have reported another high tech faction in the area, and initial reports have the Exodii concerned that it will be hostile to cyborgs. They would like you to get a cursory examination of them but not engage. This is Hub01. If you make direct contact, you'll have to try to lie to Rubik about why you did so, and the outcome will have minor influence on their trust.

- Available until 2 weeks after the start of cataclysm at which point we assume the Exodii have met the Hub already, and likely you have too. At that point, we move straight on to offering Mission 2.
- Does not require any trust, available on your first meeting if you ask about work and haven't somehow annoyed Rubik: They see this as a way to test your trustworthiness.

Exodii scouts have noticed areas of high tech drones patrolling a central base. The level of technology suggests that it would be appropriate to scout closer, but Exodii tactitians do not recommend a direct approach. Hiring a mercenary to scout it out allows them to remain unidentified. Would you be that mercenary?
- Rubik is willing to pay you with a free exodization, skipping the anus fetik mission, if you have not already been exodized
- If you have already been exodized, Rubik is willing to pay you with store credit, or with a CBM of your choice chosen from a short list of desirable early game CBMs.

If you have already encountered Hub01, you may just recognize the faction and tell Rubik about them.
- You can do this for free before accepting the mission. This will not get a reward and lets you move directly to mission 2.
- You can accept the mission first, haggle a price, and then confess you've already met the hub and can tell Rubik about them right away. Rubik will find this hilarious, and is impressed with your cunning. It has neither a negative nor positive impact on your trust unless you choose some really unflattering dialogue options.

In order to complete the mission you have to travel to Hub01, then return to Rubik and tell them about it. Rubik will be concerned about this new faction and warn you to stay away from them, with some persuasion you can get them to admit that similar groups in other dimensions are pretty common and tend to be extremely dangerous. They are concerned that this may cut their time in this dimension short.

In this first pass, that's all there is to it. Further implementation will allow shadier things to happen.

#### Rubik's dialogue

https://gist.github.com/I-am-Erk/a1aea11ed644db4e907836ce60db38bc#file-exodii_mission_1_dialogue-md

I've written a large chunk of the dialogue for this already. Woo!

### Describe alternatives you have considered.

It might be possible before accepting the mission to lie and claim you've already met hub01, or lie and claim you haven't. However I'm not sure how we would work the first one out, and the second one wouldn't play any differently than just letting you lie by omission except that it carries more risk, so I am not sure it's worth adding.

It may be worth having Rubik ask for photos of the area.

### Additional context

BEHIND THE SCENES:

This mission's primary role is to try to make sure that the player can be involved with all the major factions that interact with ongoing exodii quests. Almost all the quests in their main line can potentially invoke interplay between the hub and the free merchants, especially the hub. It is quite plausible they'd want you to check out the hub early anyway, for the reasons listed, and this also gives an interesting teaser into lore about Melchior in other dimensions, without revealing too much. Bringing this relationship online fast is a good way to get the ball rolling.

**Comment by Jan-Blasiak** [comment]
I would extend the time for offering mission 1 to 1 season, it will be a shame to miss it just because you were locked in a lab for a week.

**Comment by a-chancey** [comment]
> I would extend the time for offering mission 1 to 1 season, it will be a shame to miss it just because you were locked in a lab for a week.

Eh, I’m torn. The world isn’t waiting around because you chose a lab start scenario 🤷🏻‍♂️ the Exodii are going to want the recon info sooner rather than later, whether it comes from you or “another survivor” who took the job before you.

I think we should do something similar with the free merchant’s back bay mission. Those zombies aren’t staying in the back room forever.

**Comment by I-am-Erk** [comment]
Two weeks might be a little fast, but I think a season makes them seem a bit static.

**Comment by PatrikLundell** [comment]
I like the mission direction. However, the part I have problems with is that there is no way to do any meaningful scouting out of hub 01 without entering the building, and if you enter an unknown, supposedly/potentially inhabited building you're likely to get in contact with the inhabitants (we know there's nobody inside the accessible top level, but the player character doesn't).

The problem with just scouting from the outside is that there's a wall with some building inside, and you don't really get any useful info out of that. If there was a hub 01 drone by the facility it would provide some indication of something actually going on, though, but that would require some hub 01 modifications.

The mission wording would have to be chosen carefully so they reflect what the PC would be requested to do so the player understands it correctly.

**Comment by I-am-Erk** [comment]
It might be worth adding an expansion that uses update_mapgen to have something minor going on at the hub when you arrive to scout, but the exodii can make do with your description. It'd also be worth considering asking for photos.

**Comment by PatrikLundell** [comment]
Requiring photos during the very early phase of the post cataclysmic world is a rather steep requirement. A camera is not something I consider to be important (ever, really), and certainly not in the phase where you may still be limited both in what you can loot because of the lack of a vehicle and because you may be rather limited in the locations you can visit.
It would be OK if it was a bonus, though.

**Comment by I-am-Erk** [comment]
Most characters start the game with a smartphone.

**Comment by PatrikLundell** [comment]
Didn't know you could take photos with them... That definitely solves the issue (after all, challenge starts are supposed to be challenging, and smartphones are common loot anyway).

**Comment by MNG-cataclysm** [comment]
Should this be closed now that the first mission has been added, and that there's a separate issue post for expanding it?

**Comment by I-am-Erk** [comment]
Yep we're on to https://github.com/CleverRaven/Cataclysm-DDA/issues/59904 now
