### ISSUE TITLE
Non-permadeath mode (hear me out)

### ISSUE THREAD

**Issue by liminalRoar** [CleverRaven/Cataclysm-DDA#59903]
### Is your feature request related to a problem? Please describe.

Permadeath is great but there are legitimate reasons why an easier mode can exist.
- For beginners and practice/experimentation purposes.
- There are other options at world gen which can make the game much easier, as well no limit points for character creation, so a save/load feature at least is no less antithetical to the gameplay.
- An easier mode can disincentivize save-scumming as it allows players to choose if they want the real experience or have more leeway.
- There are good methods for rewarding hardcore gameplay and limiting the experience with an easy mode.

### Solution you would like.

We could either add a new option during character creation, _Practice mode_, which can be checked if the players want a way to continue after death. Ideally on the first page where you select the point pools. It will include a clear description of what features will be lacking in this mode, and how the save mechanic will work. A world and game setting can disable this altogether.

The other option is to actually implement (at least) two difficulty modes. An easy/beginner mode and a Hardcore/Cataclysm mode. We have difficulty settings for world gen; this is essentially a difficulty setting tied to characters, not the world.

The actual save mechanic could have multiple options. But my recommendation would be the option to save when sleeping (like currently) but if your character dies, you have the option to reload to the last save point at a bed. This offers a drawback for reloading, being losing whatever progress you made that day. This would involve "save and quit" or the usual save while playing being differentiated from saving in a bed.

Now for the other penalties while playing on practice mode. Achievements will be disabled. As the achievement system grows, this gives some incentive to play the permadeath mode. Also, i really do want to eventually add a Hall of Remembrance like #52182 (my first suggestion ever!). A menu option to view diseased characters and their stats and achievements, and scores. This feature would be disabled for characters that were practice runs.

If this was implemented, then making save scumming more difficult could be warranted, but that is another issue.

### Describe alternatives you have considered.
Have a giant "PRACTICE MODE"  flash across the screen while playing to remind players their choice.

Add some relatively humiliating messages from portal storm voices and NPC responses if playing on practice mode.
_No response_

### Additional context

Open to any suggestions. I understand why this would not be desired at all, but i do believe if done right, it would not change the CDDA experience negatively at all.

**Comment by AtomicFox556** [comment]
I think this could only be reasonably implemented by saving multiple "states" of the world and the character at various time points, which is pretty much just assisting savescumming.

**Comment by liminalRoar** [comment]
Well the way i envision it, two states of a save would need saved at 1 time. The last legal save to reload upon death, and the most recent save. The other option is to simply have only 1 save state that can be reloaded whenever but i think it is a worse way to do it. I guess i don't see what would be wrong with the 2 save states. Takes a bit more space, but otherwise not really an issue. 

I think the whole premise is more than simple save scumming or assisted save scumming and that it has its place, but i've probably laid out my thoughts well enough in the initial suggestion for now at least.

**Comment by anothersimulacrum** [comment]
This discussion was had 8 years ago:
>  permadeath is simply a play style, it’s not, it’s a rule of the game, it’s one of the things that defines the game.

https://discourse.cataclysmdda.org/t/the-complexity-of-this-game-has-surpassed-non-optional-permadeath/5464/102

There are various ways (graveyard folder, save backups) that you can do this if you want, but the game will not enable it.
See also https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#Rogue_Like

**Comment by liminalRoar** [comment]
8 years of an ever-evolving game and not even room to discuss some additional features for those looking for some easier avenues to get into the game? all i can say is wow. lost a bunch of respect here.

This isn't even for me, its for opening up conversation to allow a way for those who wish for a different experience while still respecting and rewarding the true thing. I wouldn't even be playing the practice mode. Anyway, that's all for me. tired of getting shut down and ignored when i am doing my best to brainstorm how to improve this game and still stay true to its core.

**Comment by I-am-Erk** [comment]
On the off chance you check back in here, I think it's a shame you feel that way. I've listened to your feedback extensively on stuff like UI changes and thought you had good commentary. This is a project where not all things everyone wants can happen simultaneously, someone can have good ideas and also get their issues closed.

**Comment by Rimplestilt** [comment]
I am sorry. and it was never anything personal (towards the community). there were, many factors, tbh, in me taking a break from things. A lot of changes in life, personal/work related/and other wise, combined with many tiny aspects i was annoyed with in CDDA development, but which ultimately matter little. (but...admittingly, i have paid careful attention to nearly every new Issue and pull request with this project...i just needed some personal space)

So, apologies for the petty and abrupt leaving, looking back it was uncalled for, but i also did need time to focus on other things in life more.

Other than that annoying rant... Absolutely astounding work to everyone on how much this cycle of CDDA has managed to accomplish! i am glad to have been even the slightest involved in it.

**Comment by I-am-Erk** [comment]
Hey, I'm really glad you remembered to come back and saw the reply. I was quite sad to think you'd left on unhappy terms and I'm glad you're in a better spot.
