### ISSUE TITLE
Freezing when crafting with very low NPC spawn delay

### ISSUE THREAD

**Issue by Sunshine-Lolipop** [CleverRaven/Cataclysm-DDA#59912]
### Describe the bug

Upon crafting I experience a freeze when NPC spawn delay is low enough

requirements for freeze:
NPC spawn delay need to be low (less than 0.1)

[Xedra-max-npc.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9264246/Xedra-max-npc.zip)
### Steps to reproduce

1. Use the save file sent above
2. Start a long craft (enough resources are around to start crafting a short bow)
3. The game will freeze, usually around 4% completion of the shortbow for me

### Expected behavior

The game does not freeze, or the game prevents me from setting a NPC spawn delay low enough to crash the game

### Versions and configuration

OS: Windows 10
Game Version: 8f8b8d9 (although I have experienced this bug on all the version of the experimental I have tried in the last 2 weeks)
Tiles: Yes
Mods: cdda, NPC_NO_NEEDs, Xedra_Evolved

### Additional context

My kneejerk reaction is the solution should be to create a minimum NPC spawn delay, but I think that might just mask the actual issue

**Comment by Maleclypse** [comment]
BlazeMod doesn't have NPCs though, which invalidated my first theory.

**Comment by bananaedmonkey** [comment]
Well I am a moron,
The issue has nothing to do with mods
here is the same issue on a save file with no mods:
[max_npc.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9267142/max_npc.zip)
same deal as last time, to replicate the freeze just attempt to craft the bow

**Comment by bananaedmonkey** [comment]
so the bug is based heavily on NPC spawn delay

0.01 NPC spawn delay causes long-bow to crash around 2%
0.05 NPC spawn delay causes crash around 5%
0.1 NPC spawn delay causes crash around 12%
0.5 NPC spawn delay does not crash
