### ISSUE TITLE
Zombies somehow having reduced sight radius?

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#59913]
### Describe the bug

I encountered a case in TCL where I'm walking towards the zombies and the GM security drones, but they don't see me despite bright lighting. 

Disclaimer: I have still not updated to latest experimental so I don't know if this is fixed (version current as of 07-19-22)

### Steps to reproduce

Just load up the save file I have uploaded and walk around. 

### Expected behavior

The zombies should have seen me approaching from the right many tiles ago. 

### Screenshots

![image](https://user-images.githubusercontent.com/108444328/182979617-6f00fd04-bf01-4002-8127-80a2408a3878.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: fac3512 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
[Silica.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9264378/Silica.zip)

**Comment by andrei8l** [comment]
This appears to be working correctly. Your player is in a dark spot (light_level = 16) so the zombies have an effective sight range of 8 (for that spot). If you teleport to of one of the ceiling lights to the right, the zombies will spot you.

**Comment by Merikona** [comment]
> This appears to be working correctly. Your player is in a dark spot (light_level = 16) so the zombies have an effective sight range of 8 (for that spot). If you teleport to of one of the ceiling lights to the right, the zombies will spot you.

Hey andrei, when I use 'x' to examine the tiles from my character to the zombies to my left, and even the tiles I came from, they all show up as "bright." So if I was in a dark spot, the interface wasn't reflecting it.
