### ISSUE TITLE
Tempered Combat Machete in Armor section of Crafting Menu

### ISSUE THREAD

**Issue by SauperMagiuse** [CleverRaven/Cataclysm-DDA#59915]
### Describe the bug

The Tempered Combat Machete, which is a weapon that cannot be worn, is located in the Arms subsection of the Armor section of the crafting menu.

### Steps to reproduce

1. Make a character with enough fabrication (7 is def enough)
2. Spawn or find the "Welding and Metallurgy" book
3. look in the Crafting menu arms section in the armor section
4. The Tempered Combat Machete will be listed.

### Expected behavior

I expected a combat machete that cannot be worn would be in the Cutting Weapons Section 

### Screenshots

![2022-08-04](https://user-images.githubusercontent.com/8670884/182984768-39a103b9-467c-454d-91b6-0d145904ba42.png)
![2022-08-04 (1)](https://user-images.githubusercontent.com/8670884/182984917-049477e2-0e52-4066-8854-b8658c05d9d6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: c32d23c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: c32d23c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
