### ISSUE TITLE
Mac Version of CDDA not opening since 7/21

### ISSUE THREAD

**Issue by ZionRoL** [CleverRaven/Cataclysm-DDA#59926]
### Describe the bug

The game will not start after updating past "cdda-osx-tiles-x64-2022-07-21-0520" 

This version and versions before this one are able to start. 

Upon clicking or opening the application, it will "activate" or have the little notification that it opens, then it immediately closes.

### Steps to reproduce

1. Install the update
2. Install sound packs (if needed)
3. run the game
4. allow security permissions
5. start the game again with permissions updated
6. game should start after step 5, but will fail to start with no more indicators.

### Expected behavior

I expected the game to start normally and move me to the title screen.

### Screenshots

N/A

### Versions and configuration

N/A

### Additional context

N/A

**Comment by sonphantrung** [comment]
Launch the game using the terminal?

**Comment by sonphantrung** [comment]
@ZionRoL maybe #60018 has fixed the crash, you may want to update the game to the newest version

**Comment by animation303** [comment]
I had the same problem, downloading the dmg file and just dragging it to Applications

the dmg versions seem to be missing some libraries, the problem went away when I installed the homebrew version

**Comment by BrettDong** [comment]
Cannot reproduce on latest macOS Tiles experimental.

**Comment by BrettDong** [comment]
> I have this same problem on the latest experimental, Running MacOS 10.11 El Capitan
> 
> When i launch it, it opens for a millisecond in the dock, then closes.
> 
> Macbook pro late 2008

Latest experimental requires macOS 10.13 or newer.
