### ISSUE TITLE
Marking items as "Sleeping gear," and the reverse of this as well

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59928]
### Is your feature request related to a problem? Please describe.

I sometimes forget to take off my gear when I go to sleep, get really hot, and wake up dehydrated.

### Solution you would like.

Marking certain items as "stuff to take off when sleeping," and marking other items as "stuff to put on when sleeping." The latter isn't as important because the character will try to keep warm in The Pile, but the character will not take off clothing automatically when they sleep if they're too hot. Players would not want characters taking off items willy-nilly because some stuff is important to keep by in case of random attacks at night, like a sword or armor, of course. That being the case, allowing the player to mark certain items as "Take this off automatically when you sleep" would save on key-presses every sleep-cycle, as well as the occasional "oh whoops forgot to take off my heavy hot armour!" issues.

### Describe alternatives you have considered.

Taking it off manually every. single. time.

### Additional context

i wonder how comfortable sleeping in full cataphract armor would actually be - you'd think it'd prevent getting to sleep because of discomfort, same as sleeping on a concrete floor or similar.

**Comment by pshepjr** [comment]
As an extension to this, it might be nice to have an "outfit" system where you can pre-set worn equipment and toggle between them. This would let you 'quick-swap' [it still takes in-game time] between your outfits before and after sleeping. This also ensures that you're still stuck outside of your preferred combat gear if you're woken up in the middle of the night by a biter.

I don't know how easy it is to implement something like this though.

**Comment by descan** [comment]
> As an extension to this, it might be nice to have an "outfit" system where you can pre-set worn equipment and toggle between them. This would let you 'quick-swap' [it still takes in-game time] between your outfits before and after sleeping. This also ensures that you're still stuck outside of your preferred combat gear if you're woken up in the middle of the night by a biter.
> 
> I don't know how easy it is to implement something like this though.

I *have* heard people talking about an outfit system, although I don't recall if it was a concrete plan someone had been coding, a future plan, or just whimsical musing...

**Comment by yoopgim** [comment]
additional (related) idea: bed varients, and maybe a advanced bed in the aftershock mod?
