### ISSUE TITLE
Changing bindings behaves inconsistently

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#59922]
### Describe the bug

I added a bind to ascend stairs and descend stairs action default are >,< i added pageup and pagedown as well.
Throwing an item to a different z level does not work with the new bind, the old one works; however ascending and descending stairs can be done with both default and new binds.

### Steps to reproduce

1. add new keybinds to Descend Stairs and Ascend Stairs actions [https://puu.sh/JeGz2/994c43405a.png](url)
2. equip something you can throw a few tiles, throw it
3. move up or down a z level while in throwing mode
4. observe that using default keybinds works, using custom ones does not, here is a video with key presses https://puu.sh/JeGvv/504be065c7.mp4
5. bonus: if you remove all the keys, adding new ones behaves the same (wont work for throwing if custom) however if you re-add the default ones <> those will work as before.

### Expected behavior

Should be consistent..

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: e9808ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations]
]

**Comment by liminalRoar** [comment]
removing and adding keybindings can get very weird. especially when there are multiple bindings or gamepad bindings. Sometimes it doesnt show bindings when there are some. Sometimes it messes up even the name of the keybinding, some actions dont work, the global, local thing has some quirks.

I noticed this recently when adding a keybinding option.
