### ISSUE TITLE
Add Blowguns: better than no guns!

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#59923]
### Is your feature request related to a problem? Please describe.

This is something i would like to (re)implement personally. Blowguns became obsolete in #16541 but were never much to begin with. As someone who has some experience with them, I believe they have their place and fill a unique role.

Pros:
- Lightweight and fits in a spear strap.
- Some can be disassembled for easier storage.
- Quick to aim and shoot; accurate.
- Ammo can usually be reused (like a bow).
- Very quiet (more than a bow). Stealthy.
- Should use very little stamina (and no body strain, for the future)
- Can be used while prone or crouched ( a bow cannot... should not)
- Make a "decent" melee weapon
- ~~Make a decent snorkel~~

Cons:
- Not very powerful
- Not a lot of range

### Solution you would like.

- Add blowguns in multiple lengths, caliber, and material, as well as .
- Add multiple types/grades of dart for each bore size (.40 and .625 caliber for sure).
- Add recipes for some makeshift/simple blowguns and darts

A blowgun's caliber, length, and material will affect it's ranged damage, accuracy, effective range, melee strength and speed (and possibly range!) and more. Longer blowguns should have reach attack capabilities for melee (5 and 6 foot models for sure).

Blowguns will best for hunting, especially small game, but can help take down lesser targets and help in a pinch. Again, they fill a unique role in the game and deserve a place! 

### Describe alternatives you have considered.

not having a separate json for them , but i think it is warranted.

ideally i'd love poison to be a thing. For darts and arrows. Only really useful on wildlife, which most wouldn't need to kill anyways but. Could be a cool addition.

Letting darts take a special place between ranged and throwing, having a separate range compression to even things out. For example: 12x reduction from real life for guns, 10x for bows, and 8x for blowguns and darts. Or 12x, 9x, and 6x. Personally i think this can be justified in that the range issue is most apparent for guns and longer range, and diminishes as range does. So its kind of  like a log scale adjustment. I think it could balance things more not les, but it's probably a hot take. 

### Additional context

I'd probably like to know sooner than later if devs are completely against this, because it will take me some time and work to implement right and balance.

**Comment by snipercup** [comment]
I'd like to see them in-game but everything about them has to be realistic. I see they are illegal in Massachusetts, how can we represent that in-game? For item spawns, how many even own a blowpipe? Where would you find a recipe for a blowgun?

I'm not even talking about damage or range but just their prevalence in New England requires good sources and a lot of research.

**Comment by ggttttggggtt** [comment]
> I'd like to see them in-game but everything about them has to be realistic. I see they are illegal in Massachusetts, how can we represent that in-game? For item spawns, how many even own a blowpipe? Where would you find a recipe for a blowgun?
> 
> I'm not even talking about damage or range but just their prevalence in New England requires good sources and a lot of research.

Although I don't know anything about blowguns, they seem like something the player could craft. Given that they're illegal, they probably wouldn't spawn in the world or at least would be extremely rare, but maybe there could be a book that provides recipes for them. If not, maybe an NPC that could teach you how to make/use them.

**Comment by AtomicFox556** [comment]
One more notable thing to worry about would be that it'd need to be impossible to use while the user's mouth is covered.

The skill needed to use one would likely be throwing. I can't think of anything else that'd make more sense, and that way it's (intentionally) at least not usable for improving your skill at using bows or any of the firearms.

Less sure about this one, but in the absence of actual usable poison, one could try to make low-explosive darts that could actually do some damage. Those specifically use too little explosive material, but I guess one could add more. https://www.youtube.com/watch?v=t6748EuVEJg

**Comment by GuardianDll** [comment]
We know about blowguns, we want to see them, but we can't accept them before there will be multimag system, that will allow us to check both compressed air and rounds to use such weapon (we also want to use it in a bunch of different stuff, but thats a different story)
