### ISSUE TITLE
log font in blue is almost unreadable

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#59936]
### Is your feature request related to a problem? Please describe.

the blue font in the log is barely readable, and only when my eyes are very close to the screen. Every other text in all colors are readable, but the blue contrasted with black background is not.

### Solution you would like.

Change the blue to a brighter blue... maybe cyan or something like that and it would be readable again

**Comment by ZhilkinSerg** [comment]
In Tiles version you can change RGB values used for specific Curses colors in `config\base_colors.json` (default values are in `data\raw\colors.json`).

In Curses versions you can change RGB values used for specific Curses colors in your Terminal software.

**Comment by vetall812** [comment]
There are color schemes already that fix that issue.
Try `dark` scheme or more classic `vintage`

**Comment by Zireael07** [comment]
This is an accessibility issue that should be fixed instead of workarounds being suggested
