### ISSUE TITLE
More Variants for the Multi-Unit Housing

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#59930]
### Is your feature request related to a problem? Please describe.

I recently added multi-unit houses in the last few weeks to get them into the game.  However, I did not add any variations to how each apartment would be set up.  I'm putting out a request for people who would like to to learn mapgen or are looking for an easy project to please increase the variations between apartments in this.  For the love of everything holy every single apartment contains a pool table, currently.   Additions welcome.

### Solution you would like.

I'd love for people to do different variants that have different nested mapgen solutions but even full new maps for each floor are welcome.   These types of houses should be a significant portion of the types of homes in New England but they are currently limited by the fact that we only have a single floor design.

### Describe alternatives you have considered.

Not asking for help and waiting for people to complain enough for someone else to do it.   

I've completed the part of this project I'm likely to complete, I did it because someone else was asking for help getting them into the game.

**Comment by LyranRenegade** [comment]
I've been making a few highly modular random buildings and like to make many more but it seems chunk-rotation doesn't work #59921. If somebody fixes that I'll make some nests.

**Comment by yoopgim** [comment]
bunched loot tables and sectional randomness in general would be cool in my opinion
