### ISSUE TITLE
button for parts panel and parts information

### ISSUE THREAD

**Issue by Frozefront** [CleverRaven/Cataclysm-DDA#59944]
### Describe the bug

(Use of translator [because I'm from another language], it may not translate well, in that case, burn your brain cells to decipher this...)
Although, not all of us are PC gamers... there is a big problem when checking the information panel and parts list, since we mobile gamers do not have such large screens. When checking part information, there is no button to scroll down the panel or parts list any further (because the screens are not big), it's really annoying trying to figure it out. What do you think is needed to repair or what tool is needed to remove, for example a solar panel, it is impossible to know what tools I use to be able to remove the piece, the same for Repair, it's hell trying to figure out what it takes, and not all of us have the resources to get a pc...

### Steps to reproduce

1.Examine the vehicle (play it from mobile)
2. Look for a button to scroll the part information panel or list (which you will never find)

### Expected behavior

I was looking for the button Hoping I could scroll to read the information or tools needed to remove the part, I never found it 

### Versions and configuration

-SO: [redmi 9C] game version: [93a5ad9] Game language: [Argentine Spanish]

**Comment by descan** [comment]
On PC there is a common problem where a lot of the scrolling buttons are different on other pages. PgDn [Page Down], > (Shift + Period), [, and the down arrow are all keys that I have seen used for it. Some of the time, multiples of these are used on the same page (Crafting, for example, uses > and [ to scroll crafting requirements and item description.)

On PC, for item descriptions, PgDn is the key used. That key is bound to "Desplazar abajo rápido." Does your options screen on mobile for keybindings have something like that? If not, then that would definitely be an issue.

**Comment by Zireael07** [comment]
@descan: There has been some movement towards unifying those, also see the discussion on creating a new keybinding.

**Comment by descan** [comment]
Yes, I've been watching those discussions with eagerness. I was using it as background for why it might be difficult to know which button to use where in this case - that the functionality the OP is looking for might already be in the game (I'm not sure, I don't play on Mobile) but hidden behind the keybinding obtuseness that currently exists.
