### ISSUE TITLE
Night raider mutation increases noise at night 

### ISSUE THREAD

**Issue by Sjb4243** [CleverRaven/Cataclysm-DDA#59942]
### Describe the bug

The night raider mutation increases the noise the player makes at night time rather than decreases it. 

### Steps to reproduce

Make a character
Use debug to mutate night raider
Walk around to observe noise
Wait until night time
Walk around to observe increased noise
Wait until day
Walk around and observe decreased noise

### Expected behavior

I expected noise to go down to 3, rather than up to 8. I have checked the json which states that noise should be getting multiplied by 0.5. Increasing the value in the json affects noise correspondingly. Interestingly changing the value to 2 increases the value to 17 rather than the expected 10.

### Versions and configuration

OS : Windows 21H2
CDDA version: 8f8b8d9
Graphics Version: Tiles
Game Language: System language
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Bionic Professions [package_bionic_professions],
No Fungus [No_Fungus]

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/0c6d3025a572972e41b3891a93c9e9bbdeeedea9/src/character.cpp#L7056-L7057

Json value likely should be negative to decrease noise as in a bunch of similar mutations

**Comment by Sjb4243** [comment]
Changing the value to negative does reduce the noise to a more expected value!
