### ISSUE TITLE
missing qualities for use with aim game practice kit

### ISSUE THREAD

**Issue by jagoly** [CleverRaven/Cataclysm-DDA#59956]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/pull/59520 added a way to easily practice with ranged weapons. Part of this was adding "gun", "rifle", etc qualities to all firearms. This was done by adding the qualities to various base items in gun.json. Unfortunately, there are a large number of guns that don't copy-from these, so many guns are not usable with the new practice recipes.

### Steps to reproduce

Try to use a crossbow, ruger 10/22, pipe rifle, or many other guns for laser target practice.

### Expected behavior

All vaguely gun-like ranged weapons should be usable for practice.

I can think of three ways to fix this:
- add the qualities to all the other guns individually
  - easy, but inconsistent and seems like a band-aid
- go through guns and make sure that they all copy-from one of the bases
  - might have other benefits and seems like a good long term solution
- do something in c++ so that we don't need the extra qualities
  - would need a way to expose the "skill" field to recipes
  - means all ranged weapons should just work and reduces work long term

I'm not well versed in the crafting system, so unsure if option 3 would be feasible or desirable. But imo it seems like the best solution since then there's no chance of people forgetting the tags, and we wouldn't need to change any of the guns, just the practice recipe.

One other option would be to make the target practice more immersive, rather than just a crafting job. We could allow placing the target kit like you would when marking a regular practice target. Then, in c++ we would add a special case for when targeting it to not consume any ammo or make any noise, and to display a message, like "pew pew!" (or something less fun).

### Versions and configuration

latest experimental

**Comment by hexagonrecursion** [comment]
/confirmed I can not use a pipe rifle 9x19 (id: rifle_9mm) to train rifles (beginner)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: df06cbf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
