### ISSUE TITLE
ODR violation in widget tests

### ISSUE THREAD

**Issue by jbytheway** [CleverRaven/Cataclysm-DDA#59951]
### Describe the bug

When compiling with LTO (and a sufficiently recent compiler/linker) the widget tests trigger an ODR violation.

### Steps to reproduce

Compile with these options (mimicking the "GCC 9, Curses, LTO" CI job, except with newer gcc):
```
make -j $(nproc) NATIVE=linux64 RELEASE=1 CCACHE=1 CROSS= LINTJSON=0 LTO=1 LIBBACKTRACE=1
```
Yields the following linking error (when linking `cata_test`):
```
/usr/include/ncursesw/curses.h:670: error: ‘initscr’ violates the C++ One Definition Rule [-Werror=odr]
  670 | extern NCURSES_EXPORT(WINDOW *) initscr (void);                         /* implemented */
      | 
/usr/include/ncursesw/curses.h:670: note: return value type mismatch
  670 | extern NCURSES_EXPORT(WINDOW *) initscr (void);                         /* implemented */
      | 
/usr/include/ncursesw/curses.h:670: note: type name ‘cata_curses_test::_win_st’ should match type name ‘_win_st’
/usr/include/ncursesw/curses.h:670: note: ‘initscr’ was previously declared here
/usr/include/ncursesw/curses.h:670: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
```

This is because the curses headers are being included in `widget_test.cpp` inside `namespace cata_curses_test`.  So the types defined in these headers get placed in that namespace.  But the functions are `extern "C"`, so they don't get mangled names, and they collide with the 'real' curses functions.

### Versions and configuration

On Linux, with the following toolchain:
```
$ c++ --version
c++ (Gentoo 11.3.0 p5) 11.3.0
$ ld.gold --version
GNU gold (Gentoo 2.37_p1 p2 2.37) 1.16
```

### Additional context

This results from the changes by @dseguin in #54050.  I haven't taken the time to fully understand what the objective here is.  I'm hoping we can work together to figure out a different way to implement these tests that doesn't cause an ODR violation.  The boring option is just to remove these tests on curses builds, and run them only for TILES builds.  But perhaps someone has an alternate idea?

**Comment by dseguin** [comment]
Looks like this bit of the widget tests has been causing more issues than it's worth. Originally I just wanted something to read back text that would be printed on screen, but that part of the test doesn't even run for curses builds at the moment:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3c5939e35be2d7db8341191290498a74133cd76f/tests/widget_test.cpp#L2059-L2067

Since `$TERM` is "unknown" in the CI that part is skipped

**Comment by jbytheway** [comment]
So probably best just to cut it out of curses builds, then?  Can I leave that to you? If you are busy then I can try.

**Comment by dseguin** [comment]
Cheers, I can take care of it :)
