### ISSUE TITLE
Controversial: Labs should be much more rare (and general underground stuff)

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#59975]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/59517351/183263158-95afcead-4cd7-4375-a1e7-303524eef8d6.png)

Whereever you go, labs are *everywhere*. I mean sure, the lore said there was *some* secret government-backed research, but there are more labs than grocery stores it feels like.

### Solution you would like.

Less labs. The density of them should be drastically decreased, same for transcoast logistics.

### Describe alternatives you have considered.

However, this makes the underground much less interesting, so there need to be some alternatives.

The government nuked many labs, so there being a nuked lab equivalent would make sense. Basically a giant crater with remnants of a lab. The horrors are mostly dead and if not weakened or twisted by the radiation.

Of what else could be down there:

- Old cold war era bunkers (only for bigger cities)
- Subway technical rooms
- Abandoned or collapsed subway tunnels
- Complex: otherworldly ores/minerals brought there by portal storms
- CHUD nests
- Trainwrecks?
- Molerat tunnels
- Perhaps even metro-style subway station survivor bastions?

**Comment by Gotdamnmiracle** [comment]
For labs to be rarer I think it is fair to say they should be more lucrative. That is to say, things like the CVD machine or the nanofab machine are already very rare compared to mutagens. Reducing the amount of labs means most players won't have an opportunity to see these things, likely.

I don't see why a lab can't have multiple departments each with their own projects.

**Comment by NetSysFire** [comment]
I did some research on animals existing in actual subway tunnels. It is mosty rats, racoons and pigeons (read: rats of the sky). I live in a city with a subway system and I can frequently see pigeons underground. Most subway systems also have a surface part, where other animals can get in. According to my research this is apparently geese, kittens and goats but this would not really fit so I am omitting this one for simplicity's sake. However it would make sense for pigeons to get into ingame subway stations. These critters get there because there is an abundance of trash and the temperature is relatively constant, ideal if it is icy cold outside.

Moving away from animal inhabitants, homeless also appear to make use of tunnels and subway stations. People vandalizing the tunnels and especially subway stations are also a thing. Right now, the tunnels are literally mostly cellar spiders. In real life there are no spiders in subway tunnels because their prey, which are insects, are not there.
I could imagine there being mutated racoons and swarms of rats, while some pigeons could potentially use the subway station as their nest. Unsure about the pigeons, I could maybe imagine them to live off zombie corpses or something but this still does not sound right.
Mutated racoons and a horde of rats sounds nice so far though.

**Comment by kholat** [comment]
you should try the mod Dorf Life by chaosvolt, has rly good additions for underground stuff

**Comment by a-chancey** [comment]
> For labs to be rarer I think it is fair to say they should be more lucrative. That is to say, things like the CVD machine or the nanofab machine are already very rare compared to mutagens. Reducing the amount of labs means most players won't have an opportunity to see these things, likely.

The labs in the screenshot are microlabs, not science labs. reducing the number of microlabs wouldn't have any impact on the availability of the CVD or nanofabricator. I've made the suggestion that the Hub should eventually sell you access to their nanofabricator when you've done enough for them, and it was well received, I just need to get around to doing it. We do need new locations for the science lab finale specific loot - mostly the CVD and Nanofabricator, but a few other pieces of loot are also exclusive to the finales. Science labs (the old ones) will eventually be on the chopping block.

> I don't see why a lab can't have multiple departments each with their own projects. The trans-coastal logistics special has this and it works great for storytelling and the heist aspect of breaking onto a tightly controlled complex against multiple unique challenges.

nobody has made additional locations yet like the TCL, that's why we haven't seen a different TCL style lab yet.
