### ISSUE TITLE
The MD trait should allow butching of humans without morale penalty

### ISSUE THREAD

**Issue by Nickboom21** [CleverRaven/Cataclysm-DDA#59971]
### Is your feature request related to a problem? Please describe.

While playing I noticed that unless you have psychopath or a similar empathy lacking trait you suffer a morale penalty for butchering a human being. However, physicians are trained in anatomy largely by dissecting and studying the human body. As a result I think they shouldn't suffer such a penalty as they've been exposed and used to doing such a thing, granted under different circumstances.

### Solution you would like.

Characters with the MD trait shouldn't suffer morale penalties for butchering human beings.

### Describe alternatives you have considered.

Leave the system as is or only reduce the morale penalty to reflect familiarity/experience with dissection of humans but still the ethical complications.

### Additional context

Tested MD trait in game.

**Comment by descan** [comment]
The context being completely different (medical training/necessary surgery vs. a dead body lying in the street that was moments ago, trying to murder you. At best. Or it's some dude you found randomly. Or a friendly NPC, even!), I would definitely not remove the penalty entirely. I can see modulating it for at least having experience with the grossness factor... But then, dissecting/butchering actual zombies doesn't provide *any* morale penalty - and I'd think a decaying shambling twitching corpse would be more gross than an otherwise normal human body. 

If butchering bodies/zombies in general had a morale penalty for the squick factor that got lessened over time (similar to zombie-children-murder) then I could definitely see the MD trait getting rid of *that.*

**Comment by Aerin-of-the-Toast** [comment]
This is a complicated issue. Dissecting, sure, for whatever reason you have to dissect recently-living people/ferals, I can see it getting rid of the penalty. But butchering is different from dissection, it's not just anatomy and physiology, it's cutting apart the body for *meat,* and someone with medical experience isn't necessarily going to be more okay with going down the cannibal route than anyone else.

Descan's point makes sense though; if butchering *in general* had a morale penalty (let's face it, most people would probably be at least somewhat bothered butchering an animal for the first time, especially if it's a pet animal like a dog) I could see MD lowering/removing the penalty.

**Comment by Nickboom21** [comment]
> This is a complicated issue. Dissecting, sure, for whatever reason you have to dissect recently-living people/ferals, I can see it getting rid of the penalty. But butchering is different from dissection, it's not just anatomy and physiology, it's cutting apart the body for _meat,_ and someone with medical experience isn't necessarily going to be more okay with going down the cannibal route than anyone else.
> 
> Descan's point makes sense though; if butchering _in general_ had a morale penalty (let's face it, most people would probably be at least somewhat bothered butchering an animal for the first time, especially if it's a pet animal like a dog) I could see MD lowering/removing the penalty.

I am actually interested in a general morale penalty until the character get adjusted to butchery, however I'd argue that the cannibalism penalty is already baked in for generic butchery since you get a big penalty for eating anything human flesh. I believe that aspect would be left alone because the act of butchery doesn't imply cannibalism, for instance if you use the bones or skin for certain project (how ever morbid that might be).

**Comment by descan** [comment]
In that case, a non-cannibal non-psychopath non-MD (or other profession backgrounds) would get three penalties for butchering and eating a human corpse. The penalty for butchering something for the first time - the grossness factor. This would apply on a decaying rate for any butchering you do - you're not used to all the blood and guts and so you're not having a good time. Having an MD background (even not surgical - you still had to go through training, dissections, at the very least a lot of *images* of the insides of people) would mitigate or remove that penalty. Other professional backgrounds would also help - a butcher would obviously be used to the experience, after all. So would a vet, or a scientist. 

*THEN* you'd have the penalty from butchering a human body - that's the penalty currently in the game. This is less the grossness factor of "ew blood and guts" and more the morbidity of "this was a living, breathing, thinking member of my own species that is now just so much more meat on the table." Spiritual should probably increase this penalty, while psychopath and cannibal decrease it. (Other traits/backgrounds might modulate it too.)  

After that is the morale penalty from eating human flesh. Cannibal inverts this into a morale boost, and psychopath just removes it. Other traits might should also influence this - as far as I know, there are no other traits that fiddle with this activity. There might should also be an issue from, as you say, the fact that you can use the other parts of human bodies for non-eating aspects. Same as wearing filthy clothing can lower your morale, maybe wearing a coat made from tanned human skin could too, unless you're a cannibal. In which case, it's high fashion and you're stylin' on them zombies, son!

So to sum - to make MD do something in regards to butchering, it'd have to add a morale penalty to the butchering process itself, not necessarily the target of that process. 

If you were a non-MD cannibal/psychopath, I'm not sure if you should get a penalty for butchering in general. On the one hand, psychopaths don't care about the ethical question. On the other hand, we're not talking about an ethical morale-penalty, it's just basic "ew blood" nausea/squickiness. Psychopaths can still (as far as I know?) get grossed out by something.
