### ISSUE TITLE
Reach attacks through metal bars do not work

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59979]
### Describe the bug

It does not seem to be possible to reach attacks through various metal bars and barred windows.

### Steps to reproduce

1. Create a new character
2. Spawn yourself a steel spear
3. Teleport to a gun store or a prison
4. Try to perform reach attacks with a spear through metal bars (prison) or windows with metal bars (gun store)
5. It does not work, you seem to be attacking the bars themselves

### Expected behavior

Reach attacks should work through metal bars, windows with metal bars, and similar terrain.

### Screenshots

![clang](https://user-images.githubusercontent.com/55463047/183267206-02ee8d16-0062-41b8-915e-23db8af383ed.png)

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-08-04-1310
Mod list: default

### Additional context

Trying to 't'hrow rocks through these obstacles does not seem to work either.

**Comment by ANickelN** [comment]
![image](https://user-images.githubusercontent.com/52714184/183274601-385d7ea1-1e33-4df5-860a-852b139495ca.png)

/confirmed

The bars just get "hit" instead of the zombie through the bars.  Throwing items through bars does not work either.  I tried throwing a grenade through the bars, but it bounced off and turned me into a pile of spaghetti.

**Comment by KHeket** [comment]
Guys you are wrong. I was very annoyed by this bug, and I tested lots of versions to find out, when this mechanic was broken. On your versions 1-7 august your mistake was that you tryed to hit through bars with zero skill charcter. I repeat that and yes, I didnt hit zombies through bars anyway. But when I add 1-10 point to skills (melee and piercing) - I started to hit them
Probles is in https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-08-18-1044 version
Load [Cataclysm-DDA experimental build 2022-08-18-0942](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-08-18-0942) , set up skills to 10. Teleport to nearby gun store or prison, spawn steel spear and spawn some zombies on other side of window with steel bars - you will hit monsters and kill them. I hitting them by TAB
Load [Cataclysm-DDA experimental build 2022-08-18-1044](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-08-18-1044) and repeat this steps - there will be message "no hostile creature in reach. Waiting a turn". Trying to hit them manually by "f" - will cause nothing.


<details>
  <summary>Screenshot</summary>

 ![image](https://user-images.githubusercontent.com/102726167/192833352-09a98dc6-45db-4830-bc87-463181dcb795.png)

</details>

Obviosly, problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/59857 or https://github.com/CleverRaven/Cataclysm-DDA/pull/59849 becouse both of this pr is about windows

@CalamityKing can you fix that?
And I didnt see prs from CalamutyKing from the august, so @ANickelN or someone else can help and use programming magic to cure this problem? Becouse hitting through metal bars is very usefull ability

**Comment by KHeket** [comment]
Problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/59849 because of deleting "THIN_OBSTACLE" flag from data\json\furniture_and_terrain\terrain-windows 
I edited text files and added this flag to metal bars - all work fine as before. But I can make it at github becouse dont know programming magick and need help
