### ISSUE TITLE
using a non-iso graphical overmap tileset with an iso main map misbehaves

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#59974]
### Describe the bug

using a non-isometric overmap tileset with an isometric main map results in attempting to render the overmap with an iso perspective. this is fairly non-productive.

### Steps to reproduce

1. set main map to an isometric tileset (such as smashbutton iso)
2. set overmap to a non-isometric tileset (such as larwick)
3. open overmap
4. observe lack of usability

### Expected behavior

i would expect a non-iso tileset to get rendered normally instead of as an isometric tileset

### Screenshots

larwick, with incorrect isometric rendering
![image](https://user-images.githubusercontent.com/1569754/183261820-cc659b71-901a-41a7-b9fe-fd8a85dcadb7.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: f85703b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

#58951 is also in play in the above screenshots.

i suspect that this issue might be related to #57123 given that there's clearly a state issue with regards to iso-ness of the currently loaded tileset(s).

**Comment by mlange-42** [comment]
The problem here is that there is only a global variable that says ISO yes or no. It is overwritten when loading the non-iso overmap.

Working on the fix currently...

**Comment by mlange-42** [comment]
Fixed by #60283. Can be closed.
