### ISSUE TITLE
Cannot move items between containers on the ground using AIM

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#59982]
### Describe the bug

The AIM user interface does not seem to allow opening two containers at once (one on each side) for moving items between them.

### Steps to reproduce

1. Make a new character.
2. Spawn a messenger bag, pair of combat boots, pair of sneakers.
3. Insert boots and sneakers into the bag, then drop the bag on the tile East of you.
4. Spawn another empty messenger bag, drop it West of you.
5. Now, attempt to move any items inside the bag on East to the empty bag on the West:
6. Open AIM, navigate to the left pane
7. Press 4 to show items on West, the empty messenger bag should be a selected item as it's the only one on that tile
![aim1](https://user-images.githubusercontent.com/55463047/183269603-9d7f073d-5ed3-41b0-9544-0399c56c8a9a.png)
8. Press C to open the bag
9. Now navigate to the right pane
10. Press 6 to show items on East, the messenger bag with 2 items should be a selected item as it's the only one on that tile
![aim2](https://user-images.githubusercontent.com/55463047/183269609-79c963b7-9238-44da-b1a5-d275869a9ef4.png)
11. Press C to open the bag on East with items in the right pane
12. Notice that AIM did something entirely different (has swapped the pane contents)
![aim3](https://user-images.githubusercontent.com/55463047/183269634-fe0ace3b-234a-4edd-a3d8-2b2b2f7879ac.png)

### Expected behavior

AIM should be able to open an item container in each pane and allow moving items between them.

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-08-06-2052
Mod list: default

**Comment by ANickelN** [comment]
/confirmed

Panels are just moving across instead of opening both of the containers.

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: e46c679 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungus [No_Fungus]
]

**Comment by Maleclypse** [comment]
Closed by #65560
