### ISSUE TITLE
hit_me_effect leaves no message in the log

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#59989]
### Describe the bug

Hit_me_effects should leave a message in the message log explaining what happens.  Currently these spells are basically invisible to the message log unless they cause an effect like blindness.

### Steps to reproduce

Debug trait SUN_MAGE
Fight zombies in hand to hand.  
See that they are blinded in the log and by examining the monster.
Ponder why there is no message in the log explaining what happened to blind the monster.

### Expected behavior

I'd expect a log to say what the spell is and who it hits.

### Versions and configuration

08/05/22 download.  I'll put this in tomorrow. Shutting down for the night.

**Comment by Maleclypse** [comment]
Not positive but I believe that hit_me_effects don't work on ranged attacks or spells but again I can't confirm that easily when there is no message in the log either way.

**Comment by GuardianDll** [comment]
> hit_me_effect leaves no message

Magic.md mention `message` and `npc_message`, do they work?

**Comment by Maleclypse** [comment]
> > hit_me_effect leaves no message
> 
> Magic.md mention `message` and `npc_message`, do they work?

They do elsewhere.  They'd be good ways to try a fix for this.
