### ISSUE TITLE
The game segfaults when triggering the microlab shifting hall trap

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#60001]
### Describe the bug

The game crashes whenever I walk onto the end of the microlab shifting hall.

### Steps to reproduce

1. Create a world and find a microlab shifting hall (or use my save)
2. Walk to the end of hallway and trigger the shifting hall trap
3. Crash

### Expected behavior

Not crashing.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: e46c679 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Yorkshire_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9277091/Yorkshire_copy.zip)
[debug and crash log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9277094/debug.and.crash.log.zip)

**Comment by andrei8l** [comment]
/confirmed Collateral damage from a bug fix in #58546

AFAIK, candlebury is already working on a map fix.

**Comment by anothersimulacrum** [comment]
CC @John-Candlebury
