### ISSUE TITLE
Can't load my save after updating to dc9ff8f

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60008]
### Describe the bug

After attempting to load my save file in the recent version dc9ff8f I can no longer load the file. It crashes with no crash log after hanging on the "Please wait... loading save..." that appears after loading all the DDA data.

13:38:01.475 : Starting log.
13:38:01.475 INFO : Cataclysm DDA version dc9ff8f
13:38:01.475 INFO : [main] C locale set to English_United States.utf8
13:38:01.475 INFO : [main] C++ locale set to 
13:38:01.475 INFO : SDL version used during compile is 2.0.20
13:38:01.475 INFO : SDL version used during linking and in runtime is 2.0.20
13:38:01.503 INFO : Number of render drivers on your system: 5
13:38:01.503 INFO : Render driver: 0/direct3d
13:38:01.503 INFO : Render driver: 1/direct3d11
13:38:01.503 INFO : Render driver: 2/opengl
13:38:01.503 INFO : Render driver: 3/opengles2
13:38:01.503 INFO : Render driver: 4/software
13:38:01.515 INFO : [options] C locale set to en_US.UTF-8
13:38:01.515 INFO : [options] C++ locale set to en_US.UTF-8
13:38:01.515 INFO : Setting language to: 'en'
13:38:01.515 INFO : [i18n] Scanning core translations from lang/mo/
13:38:01.515 INFO : [i18n] Scanning mod translations from ./mods/
13:38:01.515 WARNING : opendir [./mods/] failed with "The system cannot find the path specified.".
13:38:01.609 INFO : Active renderer: 0/direct3d
13:38:01.738 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:38:01.876 INFO : Setting language to: 'en'
13:38:01.976 WARNING : opendir [./mods/] failed with "The system cannot find the path specified.".
13:38:18.237 INFO : Loaded tileset: MshockXottoplus
13:38:18.237 INFO : Loaded tileset: MshockXottoplus
13:38:25.822 WARNING : opendir [./save/Piney Green/mods] failed with "The system cannot find the path specified.".

mods.json is still there. did the file structure change somehow?
This save was functional on 2022-08-05-1816.

### Steps to reproduce

[Piney Green.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9277535/Piney.Green.zip)

### Expected behavior

I should be able to load my save file.

### Versions and configuration

dc9ff8f

**Comment by Consoleable** [comment]
I have been having the same issue.

**Comment by irwiss** [comment]
It's likely you need to roll back to experimental from 2022-08-07-1542 or earlier until it gets fixed
