### ISSUE TITLE
Game crushes after trying to add a waypoint trough evac shelter computer

### ISSUE THREAD

**Issue by Denchik050** [CleverRaven/Cataclysm-DDA#60005]
### Describe the bug

After pressing "Contact us" on a evac shelter computer game freezes, then crushes without any error messages.

### Steps to reproduce

1. Interact evac shelter computer.
2. Chose "b. Contact us"
3. Press Esc or enter.

### Expected behavior

Expected a survivor center quest.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: df06cbf [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Бионические профессии [package_bionic_professions],
    [WIP] Мифос Мод - Без зомби [Mythos],
    иконки видит-игрока, бег, приседание, кровотечение для retrodays [sees_player_retro]
]

### Additional context

[bugreport.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9277215/bugreport.zip)
Also, "crush.log" looks like its not changes for a long time

**Comment by SariusSkelrets** [comment]
I encountered the same issue today. It didn't crashed in worlds without mythos so it seems that the error is related to the mythos mod 

- OS: Windows
    - OS Version: 10.0.22000.1455 (21H2)
- Game Version: a72dc5d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    [WIP] Mythos Mod - No Zombies [Mythos]
