### ISSUE TITLE
Unused things in item use actions that should probably be removed.

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#60012]
### Is your feature request related to a problem? Please describe.

* On `cauterize` item use action "cost" and "flame" parameters are never used. "flame" is false on all items and "cost" is never set.
* `salvage` item use action does not seem to be used by any item.
* On `inscribe` use action the "cost", "on_items", "material_restricted" and "material_whitelist" are never used. ("material_restricted" is always false)

### Solution you would like.

Remove them.

### Describe alternatives you have considered.

Use them.

**Comment by chrispikula** [comment]
`cauterize` : Magiclysm\items\enchanted_misc.json, line 34.  Heat cube.

`salvage` : data\json\tool_qualities.json, line 6, part of the tool quality 'CUT'.

As to the last, that's true, but it's also a little silly than pens can write on dirt.  :-p

**Comment by Hirmuolio** [comment]
> cauterize : Magiclysm\items\enchanted_misc.json, line 34. Heat cube.

It is set to false. It is always set to false on every single item. So it is "used" not in a meaningful way as it is always same.

I hadn't noticed that tool quality can define use action independent from the item. The variables in salvage ("cost", "moves_per_part" and "material_whitelist") are all still unused though.

**Comment by chrispikula** [comment]
There's a few in tool_quality.json for cauterize as well, but they are all, likewise, flame:false, 

What would flame being true do for cauterize?  Require an external flame nearby, I'm guessing?

**Comment by Hirmuolio** [comment]
Yeah. It was for the old system where you could use knife+fire to cauterize wounds. That seems to have been removed at some point.

**Comment by chrispikula** [comment]
I think I remember that discussion, something about cauterizing being a terrible idea vs just putting pressure on the wound.  Side note, not sure how the character would _know_ that, but we've moved away from adding 'bad idea'* recipes and actions at lower skill levels in general.

*Not sure of the right term here.
