### ISSUE TITLE
Damaging turret with empty hands causes crash

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#60027]
### Describe the bug

The game crashes, if you attack turret with `RETURN_FIRE` attack, while your hands is empty
### Steps to reproduce

1. Give yourself a 10 throwing skill
2. Spawn any item (but only 1 unit, like a gun, and not rocks that are charges)
3. Spawn a turret (m240/249)
4. Throw an item to them, dealing damage
5. Segfault

### Expected behavior

Do not crash the game

### Screenshots

![image](https://user-images.githubusercontent.com/67688115/183472453-3b6ac484-5f1f-4f42-ab5e-c23f5b8fb1e5.png)
![image](https://user-images.githubusercontent.com/67688115/183472486-45013d2c-2537-44ff-a3ac-afe4e047f41e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 0a3bbdd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Massachusetts [MA],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9283412/crash.log)

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/44d9a6e4561294e80ae95dad018e6b3343e2f2b3/src/mondefense.cpp#L159

Looks to be at blame - it assumes the attacker is wielding a gun that it just shot with.

**Comment by mqrause** [comment]
Oops, more fallout from #58666. I'll fix it in a bit if nobody beats me to it.
