### ISSUE TITLE
Attaching a shoulder strap to a gun while the strap is wielded results in a hard crash.

### ISSUE THREAD

**Issue by Psiclops** [CleverRaven/Cataclysm-DDA#60048]
### Describe the bug

If you are wielding the shoulder strap while attempting to attach it to a gun, after the attachment is complete the game asks you what to do with the strap and selecting "drop it" causes the entire client to crash to desktop.

### Steps to reproduce

1. wield a shoulder strap
2. choose to attach the strap as a gun mod
3. complete the attachment process
4. When the game subsequently asks "Stop wielding shoulder strap?" and offers choices what to do with it choosing any option results in a full crash to desktop. 
5. 100% repro rate.

### Expected behavior

I expect to be able to attach a wielded shoulder strap to a gun without a crash, or to not be offered the ability to do so. The fact that the item "shoulder strap" is being destroyed when it is attached to the gun is not being handled correctly by the client, leading it to believe it is still wielded after the successful gunmod action. 

Performing the same action with the same shoulder strap while not wielded succeeds without asking any questions about what to do with the strap afterwards. I believe the fact that the gun was not wielded during the gunmod action, but is being wielded afterward is the reason the question about the strap is being asked.  The order of events should be examined, as the destruction of the strap should occur before the gun is wielded, or using gunmod actions on wielded items should be disallowed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 1348046 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9293797/crash.log)

**Comment by Trioct** [comment]
Try updating. It should've been fixed by #58915.

**Comment by Night-Pryanik** [comment]
Fixed by #58915.
