### ISSUE TITLE
Phelloderm Mutation Bug

### ISSUE THREAD

**Issue by Mulanti** [CleverRaven/Cataclysm-DDA#60054]
### Describe the bug

Phelloderm will not mutate with Alloy Plating CBMs installed.

### Steps to reproduce

1. Created new character.
2. Debug spawned and installed all Alloy Plating CBMs.
3. Attempted to Debug mutate Phelloderm.

The reverse is not true, you can mutate Phelloderm then install the CBMs, but if you remove Phelloderm it will no longer let you debug it back on.

### Expected behavior

I expected to be able to mutate Phelloderm in the plant line mutation tree, as it is tied to most of the rest of the mutation line.
I am unable to test if other parts of the mutation line are bugged with the CBMs that require Phelloderm.

### Screenshots

Screenshot with CBMs:
![image](https://user-images.githubusercontent.com/100085848/183794146-bd69dc0c-00f8-4798-8c96-5328584b8ffa.png)

Screenshot of being unable to activate Phelloderm mutation:
![image](https://user-images.githubusercontent.com/100085848/183794400-f8f56546-c2b3-40af-80b3-3ab6ee0b42f7.png)
![image](https://user-images.githubusercontent.com/100085848/183794443-00c1c6f1-35d4-4e82-b376-066eae8283e1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: f80d2ee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
I think the Alloy Plating CBM has gone through various thought about how it works, from replacing the skin (in which case you can't replace the removed skin with a new type of "skin", to subdermal, back and forth. I think it's currently considered subdermal, in which case you ought to be able to replace the skin layer, but I'm not sure.
Given that the Exodii seem to replace as much of their meat bodies as possible with metal, the skin replacement model seems to me to be the way things are headed, though.
