### ISSUE TITLE
Marginal skill gains affect failure rate

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#60064]
### Is your feature request related to a problem? Please describe.

This is part of a [project for after 0.G stable](https://github.com/orgs/CleverRaven/projects/4/), to make skill gain take much longer.

When it takes weeks to gain a level in a skill, it will become disheartening and unrealistic to see no changes from day to day practice. There's no reason it has to be that way, since skill level isn't a real thing and skill changes should be incremental.

### Solution you would like.

We can make skill levels less relevant - more of a general marker of skill - by having success/fail rates take into account your progress towards the next skill level. Proficiencies already work this way.

I once [sketched up a way to use a normal roll instead of dice](https://github.com/CleverRaven/Cataclysm-DDA/pull/46153) to determine skill success, and that would be one option here. We could ditch the current system using dice, and instead have your chance of success fall on a normal curve based on comparing your skill to the target difficulty. This remains an option, one that has some potential major long term benefits. I still believe it is the best choice, and the linked pull request is something that could likely be re-adapted pretty easily.
- If doing it this way we'd need to change `weighted_skill_average` to also include the percentage to next skill level of all involved skills.

Another option is just to keep the current rolling system but make it better.
- The current formula is: `skill_dice = get_skill_level( making.skill_used ) * 4;`
- This could be easily changed to a float and use `std::max(skill_used + fraction_to_next_skill_level * 4, 1)`
- Changing it to have a floor of 1 means that the first 0-25% of skill level 0 will be consistently the same but also means that we fix the existing bug where crafting always fails at skill level 0.

I do not like the current skill rolling system at all and I highly favour rewriting it, even if it is rewritten to use dice in some other way. The current system inexplicably rolls both success and difficulty, for example. It is just a mess.

### Describe alternatives you have considered.

it's debatable if we should have fractional skills increase linearly as above - where 99% is nearly as good as the whole skill level - or on a bellcurve, where the first 50% don't count as much as the second. I am inclined to make it linear both because the math is easier, and because with rust this means that rusting your skill to 1(99%) doesn't actually reflect into any significant difference in fail rates compared to being at 2(0%).

### Additional context

I also think we should seriously revisit the 'skill requirements' system and make very few things have a hard-and-fast skill requirement, as it is done in crafting. That would further remove the frustration of slow skill gain by allowing players to attempt eg. mechanics operations requiring skill 5 when they have skill 4(90%).

**Comment by PatrikLundell** [comment]
I'm definitely in favor of taking partial levels into consideration, and skill rust means that it probably has to be more or less linear, or you get weird penalties such as having your plans derailed by e.g. having to butcher an animal (road kill or defense) delays some work by a day, and by that time you've rusted through the floor. The game shouldn't have a skill rust system that penalizes the player for not meta gaming the system.

**Comment by I-am-Erk** [comment]
We now have the stuff for this with #63886 and it should be pretty easy. I'm going to give this a priority level because it could potentially allow some other steps, and it should only be a few lines of code.

**Comment by RenechCDDA** [comment]
I believe this has been partially or fully resolved by #65004?
