### ISSUE TITLE
Make construction operations smoothly gated to skill

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#60066]
### Is your feature request related to a problem? Please describe.

Currently, having insufficient skill for a construction command makes it impossible, largely because as far as I know there is no skill check for success/fail on construction.

This is part of a [project for after 0.G stable](https://github.com/orgs/CleverRaven/projects/4/), to make skill gain take much longer.

### Solution you would like.

Construction needs a skill check, probably using the same checks and methods used for crafting.
- In a first pass implementation it would be all right if this meant that at 50% progress we make a skill roll and if it fails, cancel and end the construction, dropping all the components on the ground and forcing you to restart with no cost but time.
- A second pass could add a chance to destroy a component on fail, and allow failure to occur at a random time throughout the progress - although I don't know how necessary the latter is, the 50% progress thing is not actually a bad simulation and prevents us from having to cache and remember if the skill check has been attempted or not.

Once this is added, we can also look into adding proficiencies fully to construction like they work with crafting, at least for pass/fail.

### Describe alternatives you have considered.

Since as far as I know it is harder to cache data on constructions like we do on items, it's hard to make it work the same as crafting. However I could envision a system where every 10% progress we call for a skill roll, and either increase or decrease progress based on the magnitude of the result. That would allow highly skilled builders to work faster. If the progress drops to 0%, eg. on a severe failure, the construction fails, losing components and requiring a restart. In this way the progress bar becomes a surrogate way to store a record of pass/fail. This system would also mean that, if NPC helpers and proficiencies boost chance of successful roll, then having the right proficiencies and other things to improve success would speed it up organically.

### Additional context

The reasoning here is that if we make skill levels take longer to gain, suddenly it will be a very major issue that it takes fabrication 2 to make a needed terrain piece. There is no way around that requirement, you cannot attempt the action and fail. That's bad simulation, and will go from annoying to play-blocking if it is going to take two weeks to gain that skill level.

**Comment by Zireael07** [comment]
I guess related to #60065?

**Comment by Zireael07** [comment]
> There is no way around that requirement, you cannot attempt the action and fail. 

IIRC crafting still works that way with attempting and failing... why should construction be any different?

>  I could envision a system where every 10% progress we call for a skill roll, and either increase or decrease progress based on the magnitude of the result. That would allow highly skilled builders to work faster. 

On one hand, I like it, on the other, you kind of run into the problem that some tabletop games had. The more rolls you make, the more likely you're to get a fail result (it's easier to get one '1' in 10 rolls than 5)

**Comment by andrei8l** [comment]
> Since as far as I know it is harder to cache data on constructions like we do on items, it's hard to make it work the same as crafting.

The partial construction is a meta item that can store arbitrary data/state better than the in-progress crafting pseudoitem.

**Comment by PatrikLundell** [comment]
I would like to see construction and crafting to essentially use the same basic system eventually. If I understand crafting correctly, a critical failure results in a loss of progress and materials, but typically not a total loss, while a failure results in no progress.

Ideally a failure should also result in loss of consumables you tried to use for that segment, but it might be hard to implement before crafting/construction gets divided into phases with their own requirements (of you screw up the concrete pouring phase of concrete construction, you shouldn't lose welding consumables that were needed for the cage construction phase).
