### ISSUE TITLE
Input fields don’t show/handle non-ASCII correctly

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#6008]
This is an issue regarding the ncurses version of C:DDA.

Input fields still have problems with non-ASCII characters. Well, at least that’s what I _suspect_.

Here’s an example of the problem:
Create a note on a map with the text “gefährlich” and save it. The input field fails to render the character “ä” correctly, instead, two garbage characters are visible. To me, they are black, bold on a white background and blink. But create this note anyways. On the map itself, the “ä” renders correctly. Now the real fun begins: Edit the same note again, now you will see the word “gefährlich” but it still has a problem. The cursor is on the “h” and not on the field behind it (as usual). And the “ä” is black, block, on a white background and blinks. And if you try to move the cursor or type something, the text field behaves really weird, charcters get overwritten, etc.

The “window” for entering the character template name seems to behave the same way.

A similar but not identical problem exists for the input field of the character name and the world name. If you input a non-ASCII character (I suspect), all you get is some garbage characters instead.

I _expect_ the input fields to either ignore any characters they can’t handle or to properly handle UTF-8 (for example). In any case, there should be no garbage characters. ;-)

C:DDA version: f64ce220e6fbbd4e6582a75d318f31cb2d1b5d1e
Tested on GNU/Linux with ncurses
##

**Comment by BevapDin** [comment]
Can anyone still reproduce this? Or similar problems at other places?
