### ISSUE TITLE
Method to know that HELMET_MANDIBLE_GUARD_STRAPPED and HELMET_MANDIBLE_GUARD are different in game

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60086]
### Is your feature request related to a problem? Please describe.

For the helmet attachments, specifically, mandible guards, there are two types.

As it stands, other than the item itself saying it fits in hard hats and helmets, there is no indication that it doesn't fit in helmets (military).
![image](https://user-images.githubusercontent.com/22281606/184223680-f49e7c12-02af-4241-a1e5-05c78e3345dd.png)

### Solution you would like.

They weren't merged into one in the original PRs, but I couldn't find a reason why?
#58749
#58020

If there's a reason not to, could there be a way to say that they aren't compatible, rather than having to search *.json?

### Additional context

Example of two incompatible mandible items:

Plastic Chin Guard:
![image](https://user-images.githubusercontent.com/22281606/184223007-ba30b9b9-1eeb-46a1-b502-3e6040a7a7b0.png)
Tactical Helmet:
![image](https://user-images.githubusercontent.com/22281606/184223069-0a07ad17-fad4-4c4f-b87c-886a2b228a82.png)

**Comment by Termineitor244** [comment]
So, here is the thing, the reason there are 2 different flags for the mandible guards is that they are supposed to represent 2 different kinds of mandible guards, one being the military rail mounted kind and the other just an attachment made with straps for any common hard hat or helmet.

I should had probably done a change so this was more clear in-game, but I had too much work after my last PR in which I added these new items so it slipped me by, sorry!
