### ISSUE TITLE
Allow players to remove alien grass

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#60092]
### Is your feature request related to a problem? Please describe.

Sometimes it does not disappear, causing this
![image](https://user-images.githubusercontent.com/88375697/184275951-2ce7e8bf-6687-4c10-8fc6-b85b2094a20f.png)

And this
![image](https://user-images.githubusercontent.com/88375697/184276023-a0c9f8a5-08ec-4cee-8de6-74a7ea109714.png)

### Solution you would like.

Allow players to cut the alien grass rather than having to go through the laborious process of upturning the ground and tamping it back down 

### Describe alternatives you have considered.

Have any alien grass tile after portal storms be replaced by grass/dirt

This check and change would be done when weather changes from Portal Storm to anything else

**Comment by Ramza13** [comment]
So alien grass not disappearing is a bug that needs to be fixed.  It should possibly be made destroyable also but I want to stop it sticking around first.

**Comment by Zireael07** [comment]
I think this PR is kinda a fix? https://github.com/CleverRaven/Cataclysm-DDA/pull/59934

**Comment by Fris0uman** [comment]
I think we need an issue to track alien grass not desapearing, as it's not the intended behaviour an allowing to cut it down does not fix that
