### ISSUE TITLE
epicuticle causes hands to be "too encumbered" to apply pressure to bleeding wounds

### ISSUE THREAD

**Issue by yam1917** [CleverRaven/Cataclysm-DDA#60100]
### Describe the bug

epicuticle causes hands to be "too encumbered" to apply pressure to bleeding wounds

### Steps to reproduce

just spawn a character with epicuticle trait, get scratched by a zombie or something and then wait while bleeding (yes, i did make sure my hands are free)

### Expected behavior

pressure should be applied to bleeding wound

### Versions and configuration

-windows 10
- version: x64-2022-08-01-0506

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 13fbcc2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by yam1917** [comment]
i also think that epicuticle negates spines mutation, but im not sure if i was just really unlucky
