### ISSUE TITLE
Shooter's Earplugs use 40x as much charge as shooter's earmuffs

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60106]
### Is your feature request related to a problem? Please describe.

Shooter's earmuffs use 0.1w. Earplugs use 4w.

### Solution you would like.

Either one is way to expensive or one is way too cheap. I don't know which is which because I have no knowledge about this technology.

**Comment by chrispikula** [comment]
4W would make your ears very, _very_ warm.

**Comment by catdach** [comment]
I don't know how accurate these numbers are, but there are some relevant comments in the JSON definitions of these items.

ear**muffs**:
https://github.com/CleverRaven/Cataclysm-DDA/blob/d6a17775bdb37b72d5703ebc296a696c15f34ca9/data/json/items/tool_armor.json#L2662-L2663
ear**plugs**:
https://github.com/CleverRaven/Cataclysm-DDA/blob/d6a17775bdb37b72d5703ebc296a696c15f34ca9/data/json/items/tool_armor.json#L2724-L2725

**Comment by chrispikula** [comment]
So, looking at the pocket for the earplugs, they've got a 100 rating battery.  Probably a holdover.

I'm thinking it should be changed to a smaller battery, and a lower power_draw.

I don't know the power_draw math, but something closer to a 1 rating and a 40 Power draw would make sense, yeah?

**Comment by Maleclypse** [comment]
Earplugs should have the same power draw but a built in rechargeable battery that is less than 100 charge is how I'd fix it.

**Comment by chrispikula** [comment]
The reason I was thinking a lower power draw was that, possibly, the noise-canceling speaker would be smaller.  Less air volume inside the ear to propagate through, vs the entire ear-muff covering.

But it's probably easier to keep them the same, so inheritance could be used and people in the future don't need to think about it.
