### ISSUE TITLE
items dissapear upon using "organize contents" menu and putting them where they shouldnt fit

### ISSUE THREAD

**Issue by yam1917** [CleverRaven/Cataclysm-DDA#60108]
### Describe the bug

when using "organize contents" menu and one selects item and tries to move it elsewhere (destination must not fit the item), it will dissapear

### Steps to reproduce

1. open inventory
2. open "organize contents" menu (i) by default
3. select an item to move
4. select destination, but destination must be too small / too full to fit the item
5. item dissapears

### Expected behavior

item should not be moved

### Versions and configuration

-OS: windows 10
-game version: x64-2022-08-01-0506

**Comment by ZeroInternalReflection** [comment]
The specific case I'm aware of, having looked into the similar #59853, is if an item is already in the only pocket where it will fit, then it will let you _try_ to move it, destroying the item.  This should be fixed by #60057.

Is that the issue you're having?

**Comment by yam1917** [comment]
yes, thank you
