### ISSUE TITLE
Ammonia appliance parts are catastrophically rare

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60105]
### Is your feature request related to a problem? Please describe.

In order to craft the full ammonia machine you need:
- 1 large pressure vessel
- 3 pressure gauges
- 4 heavy duty valves
- 1 pyrometer
- 6 heavy duty pipe fittings
- 20 heavy duty pipes
- 4 industrial compressors
- 1 small pressure vessel
- 1 nitrogen membrane filter
- an assortment of other readily available supplies

However, I've explored like 1.5 gigs of terrain on the current character and looking everywhere I've only found a single heavy duty pipe and nothing else. These parts are also not craftable, which is probably for the best. In any case they seem to be much too rare, they straight up don't appear in hardware stores and barely appear in megastores, and extremely infrequently in some select other locations. 

### Solution you would like.

I have no reference or data as to how rare industrial equipment like this is. But my gut says it should be more common.

### Describe alternatives you have considered.

I don't really need to manufacture ammonia for 200000kJ that badly. But it was disappointing to find out I basically couldn't even if I wanted to.

**Comment by Maleclypse** [comment]
Mostly I would guess it's uncommon because we lack the locations you could loot it.  Heavy industrial locations etc

**Comment by chrispikula** [comment]
What are the spawn rates of the parts in places like mines or light industry?  Are they even part of either's loot distributions?
