### ISSUE TITLE
[Magiclysm} Request to Add Damage to Self/Allies Notification when casting AOE Spells such as Fireball

### ISSUE THREAD

**Issue by ScarPan** [CleverRaven/Cataclysm-DDA#60118]
### Is your feature request related to a problem? Please describe.

This request is brought up due to numerous self-inflicted death by casting fireball in my current Kelvinist run.

### Solution you would like.

Granted, the AOE spells in Magiclysm should have friendly-fire damage. Though a prompt notice to the Player asking if they are aware/sure that the to be casted spell will damage self/allies would be a god-sent.

Maybe something saying " This spell will damage your character and/or your allies, proceed?" "Y/N".

### Describe alternatives you have considered.

Casting all spells cautiously like a true wizard should. Though that is expecting too much of me/s

**Comment by GuardianDll** [comment]
![image](https://user-images.githubusercontent.com/67688115/184497740-69794b0d-1e47-4575-a87c-04b4e6f44830.png)

**Comment by ScarPan** [comment]
> 

Thanks for the kind reply. Yes, I am aware a WARNING such as the one shown in the screenshot if available.

However, I am referring to the kind of notice/warning that functions like how the game warns you that you are about to walk into Dangerous Terrain (acid splatter etc.).

I rely on Snap to target to cast my spells and if the zombie horde is one tile away from max range of fireball, there is a high chance my finger will be to fast for my brain to stop. 

That's why I think a  Y/N prompt would be much safer.
