### ISSUE TITLE
Vacuum Pump lacks Apoc Price, is worth WAY too much

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#60110]
### Describe the bug

The Vacuum Pump is using the pre-Cataclysm price for bartering, meaning one can purchase an entire merchants stock 3 times over with one pump worth... 3000 bucks.

### Steps to reproduce

1. Spawn a vacuum pump
2. Notice the lack of barter value
3. Talk to the hub, haggle, wager, beg
4. Buy literally the entire building, you own it now, it's yours

### Expected behavior

That this item, whose only purpose is to make a makeshift molder for plastic working or an oven for making distilled The Shweeds, should not be worth 10 bleeding edge defensive systems.

### Screenshots

![image](https://user-images.githubusercontent.com/4212389/184447631-4e018871-9e31-498c-9459-fa7b4f030e8e.png)
![image](https://user-images.githubusercontent.com/4212389/184447701-6e890c35-abfd-40e7-8713-9db610097127.png)
(Just spawned one in to trade it with one of my shitty-social NPC followers to note the actual-practical barter price is absurd.)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: 750edd4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
Either you don't know that "literally" literally means literally rather than virtually, or there are some rather weird bartering options in the hub.

**Comment by Marcos6226** [comment]
> Either you don't know that "literally" literally means literally rather than virtually, or there are some rather weird bartering options in the hub.

He was talking in a hyperbolic manner so his use of "literally" is acceptable.

**Comment by PatrikLundell** [comment]
No. Talking in a hyperbolic manner using anything except the hyperbole override "literally" is fine (including, but not limited to, using the clear word "virtually" or using nothing except the improbability of the literal interpretation as the indication of hyperbole). Trying to abuse the override as the highest level of hyperbole is not. Literally expressly means what's said is NOT to be interpreted, but taken at face value so you can tell someone that you e.g. actually fell off a chair rather than did so only metaphorically.

**Comment by Marcos6226** [comment]
> No. Talking in a hyperbolic manner using anything except the hyperbole override "literally" is fine (including, but not limited to, using the clear word "virtually" or using nothing except the improbability of the literal interpretation as the indication of hyperbole). Trying to abuse the override as the highest level of hyperbole is not. Literally expressly means what's said is NOT to be interpreted, but taken at face value so you can tell someone that you e.g. actually fell off a chair rather than did so only metaphorically.

That's a good explanation so I'm going to admit that you are right, it's just a (bad) costume (AFAIK) on the English language to use the word "literally" on hyperbolic speeches.

**Comment by chrispikula** [comment]
So, un-literally speaking, is Bruce wearing the skull dusk mask over, or under the Corinthian helm.  Over looks more intimidating, but it'd be hella useless given you'd just breath in through the eye-holes.

**Comment by descan** [comment]
> So, un-literally speaking, is Bruce wearing the skull dusk mask over, or under the Corinthian helm. Over looks more intimidating, but it'd be hella useless given you'd just breath in through the eye-holes.

It's actually under the survivor mask AND under the helmet. Double whammy of useless!

Just like he is, tbh.
