### ISSUE TITLE
Selecting "Random Character" when there's only one scenario with `CHALLENGE` flag silently CTD

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#60119]
### Describe the bug

Basically, what's in the title.

`Random Character` game mode excludes any scenario with `CHALLENGE` flag from being available to select. So when there's only one scenario available with this flag (for example, mod uses a sole white-listed scenario), the game can't select anything and CTD.

### Steps to reproduce

1. Create a mod which adds a single scenario.
2. Add `CHALLENGE` flag to this scenario.
3. Add this scenario to whitelist, like this:

```
{
  "type": "scenario",
  "id": "foo_scenario",
  "name": "Foo",
  "points": 0,
  "description": "Foo.",
  "allowed_locs": [ "sloc_foo" ],
  "start_name": "Foo",
  "flags": [ "CHALLENGE" ]
},
{
  "type": "SCENARIO_BLACKLIST",
  "subtype": "whitelist",
  "scenarios": [ "foo_scenario" ]
}
```

4. Select `Random Character` game mode.
5. CTD.

### Expected behavior

No silent CTDs and some type of error message telling me what's wrong.

### Screenshots

None.

### Versions and configuration

0.F-10653, Windows 10 x64.

### Additional context

Nothing interesting in debug.log.

**Comment by RelMayers** [comment]
It is caused by you not issue on its own.

**Comment by Night-Pryanik** [comment]
The game should not _silently_ crash to desktop in _any_ case.

**Comment by ZhilkinSerg** [comment]
It crashes here:

![image](https://user-images.githubusercontent.com/16213433/185904901-27a393da-3a34-4723-a85a-03148db97301.png)
