### ISSUE TITLE
beak mutation should provide mouth/head protection

### ISSUE THREAD

**Issue by yam1917** [CleverRaven/Cataclysm-DDA#60125]
### Is your feature request related to a problem? Please describe.

wearing a helmet that covers whole face is impossible with a beak, but when you think about it, beak should be solid and for that offer some protection by itself, in combo with helmet that covers everything but mouth, we should be able to get full head protection

### Solution you would like.

make beak mutation also give some head protection

### Describe alternatives you have considered.

special survivor-made mouthgear that could be put over beak

**Comment by PatrikLundell** [comment]
A beak can break (and you probably won't fix it with duct tape and a welder), and it's attacked to the skull in some way that probably transfers forces more than a helmet with proper padding.

However, I agree a beak would probably provide some protection for the mouth (and nose) part of the head: it certainly should be less squishy than lips, for example.

**Comment by Venera3** [comment]
Beaks will get limbed when that stuff gets going again, so they'll probably be brittle-but-hard things that don't heal for squat. In the meantime I suppose they could use some cut armor on the mouth at least.
