### ISSUE TITLE
Mutation trees should not be mutually exclusive

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60126]
### Is your feature request related to a problem? Please describe.

Currently, if you cross mutation trees and take mutations from different trees, the mutations from the new tree will remove mutations from the first tree. I don't think this should happen. There are already several barriers in place to stop you from doing this:
1 - mutations are costlier and harder to manufacture and apply now. It's much more expensive to get a ton of mutations.
2 - mutations already have a mechanic for this - conflicting mutations. If you get some awesome chitin armor from Insect, you might turn it into less good fur if you start taking Feline mutagen for example.
3 - mutations have an innate mechanic which makes mutating a worse prospect the more you mutate, instability. Unless you specifically have Robust Genetics and wait a very long time between each mutation (roughly a month per mutagenic primer) continually mutating will cause you to start getting more and more "bad" mutations.
4 - there is a specific malus which causes mutations to be more likely to be bad if you currently have a lot of mutagen vitamins from other trees.
5 - enemy mutants are often hybrids of multiple mutation trees. Shelled mutants are a mix of cephalopod, gastropod and possibly even more. These enemies *are* homicidally insane which definitely implies mutating like that has some serious cognitive side effects but it at least implies mixing trees is possible. This is probably the weakest of my arguments but I figured it bore mentioning

### Solution you would like.

Allow cross contamination of mutation trees without auto-pruning mutations from other trees.

**Comment by anoobindisguise** [comment]
> Either there is bigger issue at hand or you misunderstood how mutation system works

What do you mean by this. There is an explicit function in code that causes out of category mutations to be removed some of the time when you gain mutations.

**Comment by RelMayers** [comment]
>... There is an explicit function in code that causes out of category mutations (not starting traits) to be removed some of the time when you gain mutations.

Which part? Is it due to conflicting traits?
Was that another BS by mutation changes?

**Comment by anoobindisguise** [comment]
> > ... There is an explicit function in code that causes out of category mutations (not starting traits) to be removed some of the time when you gain mutations.
> 
> Which part? Is it due to conflicting traits? Was that another BS by mutation changes?

Every time you mutate, there is a 1/4 chance per mutation you gained from another tree to be removed.

**Comment by RelMayers** [comment]
What file code sits in?

**Comment by actually-a-cat** [comment]
> 4 - there is a specific malus which causes mutations to be more likely to be bad if you currently have a lot of mutagen vitamins from other trees.

That I took out in #58832. (It was just because I didn't find documentation about it, and the math wasn't working out, so this doesn't mean I think it shouldn't exist - just saying that it currently doesn't)
