### ISSUE TITLE
Chemical spills in labs

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60127]
### Is your feature request related to a problem? Please describe.

Because zombies smash up glass bottles with gusto, there are often a lot of really dangerous chemicals spilt around subway microlabs. I would be really uncomfortable walking around a laboratory filled with spilt formaldehyde, mercury, phenol, toluene, and other awful stuff. Currently you can do so without a gas mask and be fine though.

### Solution you would like.

It's possible these spilt chemicals should have a similar effect to plutonium slurry. These shouldn't spawn full on toxic gasses, but these are really dangerous on very low concentrations that are better represented by an "aura" of badness that would need to be protected against with a gas mask + other PPE. 

### Describe alternatives you have considered.

Continue to leave it abstract.
Make them spawn in non breakable bottles.

**Comment by NetSysFire** [comment]
I'd love that. Currently I use a workaround for the toxic waste dump (#59618) by spawning a toxic gas vent, perhaps there could be a "destroyed chem lab" in the microlab with such hardcoded gas vents. About plutonium slurry, I think it only irradiates you when in your inventory?

**Comment by PatrikLundell** [comment]
As far as I've seen, you get irradiated by plutonium slurry just by quickly passing by at a distance of several tiles. It could be that some slurry spills have fields associated with them while others do not, however. My case was in a lab: I haven't had any reason to visit toxic waste dumps with my current character.
