### ISSUE TITLE
"Stinger Kick" in Scorpion Kung Fu not working

### ISSUE THREAD

**Issue by Riptor90** [CleverRaven/Cataclysm-DDA#60122]
### Describe the bug

Stinger Kick does not activate with the required 5/5 of unarmed.  

### Steps to reproduce

1.  Have a character with 5/5 melee and Scorpion Kung Fu
2. Attack zombie, scoring critical hits
3. No Stinger Kick activation, knockback, or big crits

### Expected behavior

I was expecting there to be a large, 3 tile knockback with collision and a large crit

### Screenshots

![image](https://user-images.githubusercontent.com/111188203/184498742-55abb53f-afc2-463f-861b-b14e8295a9a4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: c32d23c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by GuardianDll** [comment]
I was not able to use the technique with max skill, and not only this, but any technique from Skorpion Kung Fu
/confirmed

**Comment by TheShadowFerret** [comment]
*Notices there isn't an attack vector on any of its techniques*
🤔
