### ISSUE TITLE
We lose the ability to use vehicle-mounted water purifier

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#60144]
### Describe the bug

The ability to use a vehicle-mounted water purifier was gone. There is no "Use water purifier" or similar entry in the menu.

### Steps to reproduce

Install a water purifier onto a vehicle. 'e'xamine the tile. No menu to use purifier.

### Expected behavior

Should be able to use vehicle-mounted purifier.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/184539911-23547479-d828-433d-bb44-4dfecca3160f.png)
![image](https://user-images.githubusercontent.com/29348635/184539937-f29d4612-503a-4d13-afab-e4f41ed8e411.png)
![image](https://user-images.githubusercontent.com/29348635/184539949-ce2794d6-6911-4517-a39c-0a8901385184.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: bd5813a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This same purifier worked before. Tried re-installing. Nope. Tried installing on a different tile. Nope.
There is a tank with water installed in the vehicle.

**Comment by ampersand55** [comment]
Can confirm. Doesn't work for me either.

**Comment by EIIKaO** [comment]
/confirmed
This changes seems caused by #56991, because revert #56991 then a vehicle-mounted water purifier is working again.
But I'm not sure whether it is a specification change or a bug.
See also #60150, related discussion has started.

**Comment by descan** [comment]
Can you still use it with the crafting menu? Crafting clean water via purifier, rather than boiling?

**Comment by EIIKaO** [comment]
`Can you still use it with the crafting menu?`
In my case, YES.
I can still make clean water with crafting menu using mounted water purifier per 9 sec.

No longer can make it via "Select an action" (didn't appear "Purify water in vehicle tank" item) as shown in the issue authors third screenshot.

Then it may be a similar but different problem from #60150.

**Comment by ZeroInternalReflection** [comment]
Both this and #60150 are indeed a regression due to changes in #56991.
It looks like certain crafting capabilities work correctly when the "sub" json entry is linked to the original item, but qualities and examine actions don't, and I missed it during testing.

Based on some quick testing, the following entry in fake.json results in a water purifier that can a) be used via `e`xamining, and b) can use the vehicle's full battery capacity in crafting:

```
  {
    "id": "pseudo_veh_water_purifier",
    "copy-from": "water_purifier",
    "sub": "water_purifier",
    "type": "TOOL",
    "name": { "str": "mounted water purifier" },
    "flags": [ "ALLOWS_REMOTE_USE", "PSEUDO" ],
    "pocket_data": [ { "pocket_type": "MAGAZINE_WELL", "default_magazine": "pseudo_battery" } ]
  },
```

If I don't spot any new wrinkles in testing, I should have a PR ready in the next couple of days.

**Comment by descan** [comment]
> `Can you still use it with the crafting menu?` In my case, YES. I can still make clean water with crafting menu using mounted water purifier per 9 sec.
> 
> No longer can make it via "Select an action" (didn't appear "Purify water in vehicle tank" item) as shown in the issue authors third screenshot.
> 
> Then it may be a similar but different problem from #60150.

Alright so it's not an issue of the vehicle part losing the ability to water purify entirely. Looks like other people are on the case and are figured/have figured it out though, so we're good :B

**Comment by hexagonrecursion** [comment]
/confirmed

@EIIKaO, welcome to the bug triage squad, comrade. In order to get your badge please [submit the required paperwork](https://github.com/CleverRaven/Cataclysm-DDA/compare/master...hexagonrecursion:Cataclysm-DDA:EIIKaO-comment-commands)

> /confirmed This changes seems caused by #56991, because revert #56991 then a vehicle-mounted water purifier is working again. But I'm not sure whether it is a specification change or a bug. See also #60150, related discussion has started.

**Comment by EIIKaO** [comment]
@hexagonrecursion
I'm embarrassed, I just tried to imitate your behavior.

Of course, I'm interested in discovering, inspecting and fixing the bugs, hopefully in cooperation with you all.
I'll try later if possible. Thank you.

**Comment by jeffplata** [comment]
The FoodCo kitchen buddy seems to be affected as well. I just installed one and examining the tile gives no special menu, just "examine vehicle' and 'forget vehicle position'.

**Comment by ZeroInternalReflection** [comment]
> Edit: And it's not even providing a hotplate?

Fun fact: The FoodCo never had a hotplate.  It's everything _else_ you might want in the kitchen, apparently

I'm still assembling my test world of every appliance and vehicle part that needs to be fully retested.  Some of the following only have the basic crafting charge usage, and are thus still working correctly.  If they had any special crafting qualities or examine actions though, those are currently broken.

Appliances: Oven, water purifier, forge, kiln, FoodCo, Chemistry lab
Vehicle parts: Water purifier, forge, oil press, kiln, kitchen unit, FoodCo, Chemistry lab

**Comment by FayFlightee** [comment]
Really looking forward to this getting fixed. Along with all vp issues really.

**Comment by descan** [comment]
> Really looking forward to this getting fixed. Along with all vp issues really.

Actually, I thought this had been fixed. Last night I was playing and was able to purify all the water in my vehicle tank by interacting with a FoodCo vehicle part...? (I updated every day, so it's an old save, but...?)

**Comment by ZeroInternalReflection** [comment]
> Actually, I thought this had been fixed. Last night I was playing and was able to purify all the water in my vehicle tank by interacting with a FoodCo vehicle part...? (I updated every day, so it's an old save, but up-to-date version?)

It's still broken for me as of a fresh experimental download today.  I've got a mostly-complete fix, but purifying water in a vehicle tank needs a minor code change that I'm still testing.

**Comment by hexagonrecursion** [comment]
@EIIKaO

> @hexagonrecursion I'm embarrassed, I just tried to imitate your behavior.

I am sorry. I did not mean to embarrass you. Do you think a less flavored (more boring) way to introduce newcomers would be more appropriate?
