### ISSUE TITLE
Can't seem to level unarmed beyond 6

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60157]
### Describe the bug

I've punched a *lot* of stuff, from regular zombies to wasps to experimental mutants to bio-ops, and I've done the punching with a variety of setups - armored gauntlets, brass knuckles, bare fists for example. Yet I can't seem to level unarmed beyond 6 no matter what I do, everything is deemed too trivial to train the skill beyond 6.

### Steps to reproduce

1. Set skill to 6.
2. Punch various baddies.
3. Observe skill not increasing.

### Expected behavior

Skill should increase beyond 6.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0471811 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by buffog** [comment]
I have the same problem.
