### ISSUE TITLE
Chemistry lab fails to provide chemical making quality

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#60150]
### Describe the bug

Currently, chemistry lab, both vehicle part version and appliance version do NOT provide chemical making quality 3 it should be doing.

### Steps to reproduce

1. Summon an undamaged mobile meth lab.
2. Stand near the onboard chemistry lab.
3. Go into crafting menu and search with the filter Q:making for chemical making
4. You can see it doesn't even provide chemical making 2 quality.

### Expected behavior

I should be able to make science stuff with this. Like Dynamites.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0471811 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by harakka** [comment]
Might be regression from https://github.com/CleverRaven/Cataclysm-DDA/pull/56991, due to copy-from usage?

**Comment by irwiss** [comment]
Likely it's not the copy-from that's the problem - the fake parts/appliances have `"copy-from": "fake_power_tool_with_pseudo_battery"`, that by itself has no qualities just a magwell, and none of the tools specify qualities themselves, so the quality isn't part of the new items

**Comment by ZeroInternalReflection** [comment]
This is indeed a regression from #56991.  Based on initial testing, I mistakenly thought the relevant crafting qualities would get pulled over through the "sub" entry.  It looks like for everything to work it needs both "copy-from" and "sub" from the original tool.
The following in fake.json appears to work correctly, though I will be doing some further testing for a formal PR:

```
  {
    "id": "pseudo_veh_chemlab_chemset",
    "copy-from": "chemistry_set",
    "sub": "chemistry_set",
    "type": "TOOL",
    "name": { "str": "onboard chemistry set" },
    "flags": [ "ALLOWS_REMOTE_USE", "PSEUDO" ],
    "pocket_data": [ { "pocket_type": "MAGAZINE_WELL", "default_magazine": "pseudo_battery" } ]
  },
  {
    "id": "pseudo_veh_chemlab_electrolysis_kit",
    "copy-from": "electrolysis_kit",
    "sub": "electrolysis_kit",
    "type": "TOOL",
    "name": { "str": "onboard electrolysis kit" },
    "flags": [ "ALLOWS_REMOTE_USE", "PSEUDO" ],
    "pocket_data": [ { "pocket_type": "MAGAZINE_WELL", "default_magazine": "pseudo_battery" } ]
  },
  {
    "id": "pseudo_veh_chemlab_hotplate",
    "copy-from": "hotplate",
    "sub": "hotplate",
    "type": "TOOL",
    "name": { "str": "onboard hotplate" },
    "flags": [ "ALLOWS_REMOTE_USE", "PSEUDO" ],
    "pocket_data": [ { "pocket_type": "MAGAZINE_WELL", "default_magazine": "pseudo_battery" } ]
  },
```
