### ISSUE TITLE
Butchering with Ceramic Shards not working.

### ISSUE THREAD

**Issue by Lavoroxan** [CleverRaven/Cataclysm-DDA#60153]
### Describe the bug

If only having a ceramic shard, which has -66 butchering quality, the butchering menu will say you have an item with 0 butchering quality. 

### Steps to reproduce

1. Have a empty inventory character.
2. Spawn 1 ceramic shard and wield.
3. Approach zombie corpse and try to butcher.

### Expected behavior

I expected the Ceramic shard to be able to butcher, even if incredibly poorly.

### Screenshots

![image](https://user-images.githubusercontent.com/111240239/184546087-b40d9c35-3a7b-449b-bc42-fbfaae17ded9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: e0b9547 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    MST Extra [MST_Extra],
    Alternative Map Key [alt_map_key],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

The screenshot is from another user who tested the same thing. But my screenshot would be identical anyways.

**Comment by pjf** [comment]
Butchering confuses me as well. I seem to recall butchery requires at least `cutting` 2, but lots of items with `cutting` 1 have butchery qualities on them, and I've no idea how they're supposed to fit into the butchery system.
