### ISSUE TITLE
Can't use my rope to escape collapsed tower

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60164]
### Describe the bug

I can use a rope to descend the halfway staircase, but if I try to return up that rope I simply get told the message about "you need furniture to brace against". However thankfully if I take the rope down I can then climb up the walls to escape.

### Steps to reproduce

1. Descend collapsed tower with rope.
2. attempt to return.
3. take the rope down and observe being able to climb.

### Expected behavior

Rope should work.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0471811 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by hexagonrecursion** [comment]
I assume by "rope" you mean a grappling hook. Or is there a different way to climb down using a rope?

/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: e519404 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
> I assume by "rope" you mean a grappling hook. Or is there a different way to climb down using a rope?
> 
> /confirmed
> 
> * OS: Linux
>   
>   * OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix;
> * Game Version: [e519404](https://github.com/CleverRaven/Cataclysm-DDA/commit/e519404459e0583dab688132a37dfbf6e36c3c50) [64-bit]
> * Graphics Version: Tiles
> * Game Language: English [en]
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   No Fungal Growth [no_fungal_growth],
>   Bionic Professions [package_bionic_professions]
>   ]

I can use a long rope to descend. but there is a specific separate bug I ought to have mentioned, that the long rope transmutes into a grappling hook when I do this.

**Comment by PatrikLundell** [comment]
Probably the same as #58717.

**Comment by hexagonrecursion** [comment]
I am sorry. I am unfamiliar with this feature. How to use a long rope to descend? Do I need any traits or skills? Which keys do I press? Can I do this anywhere or only in specific circumstances?

**Comment by fairyarmadillo** [comment]
In situations where a downward staircase exists on the upper level but an upward staircase does not exist on the lower level, a player with a long rope is prompted to tie the rope to the top of the stairs and safely descend with it. No special skills are needed. This works everywhere and requires no skills ot grappling hook.

For some reason, in the collapsed tower, this behaves incorrectly.

**Comment by hexagonrecursion** [comment]
I can confirm that this happens with a rope too. There is nothing special about the collapsed tower: I was able to reproduce this in the evac shelter by using the map editor

1. Go to the basement
2. Replace the upward staircases with grass
3. Teleport to the surface
4. Go down using a rope
5. **Add** walls around the "rope leading up" tile until the game decides there are **not enough walls**

![image](https://user-images.githubusercontent.com/52621858/186073978-594b0e87-43bf-464d-b773-0040e70c5391.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cee383c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
