### ISSUE TITLE
Mutating your followers

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60163]
### Is your feature request related to a problem? Please describe.

Currently as I understand it, followers will passively accept you dosing them with mutagens if they trust you enough, otherwise they won't let you mutate them. It would be more interesting if NPCs were "active" in this decision process since mutating is an extremely life-changing process and the NPC should have some say in it.
This came up because I was thinking of turning my NPC followers into mutants with all my mutagen supplies but I realized, roleplay wise, it would be really cool to actually ask them what they want out of it, if anything.

### Solution you would like.

The way I see it, the player should broach the subject with one of their follows (something like "how do you feel about mutations? I might be able to provide them for you.") and there should be multiple types of "opinions" regarding mutations.

- Does not want to become a mutant, period.

- Does not want to become a mutant right now but might change their mind at some point in the future.

- Does want to become a mutant, and has an idea in mind of what sort of mutant they want to become, asking for a specific type of mutagen.

- Is willing to become a mutant, but leaves the decision to you as they believe you can make the best judgement for what will be "best" for them.

### Describe alternatives you have considered.

Have followers directly abandon you for mutating them without their consent or with a type of mutagen that they don't want to receive.
This is assuming everyone has a passing understanding of the existence of mutations, like they see some guy with a cat tail or something weird. There are some NPCs who specifically ask you to give them mutagens via quest but they're very rare and I'd like to as the player have a way to talk to my followers about it. There are also NPCs like Makayla Sanchez and the lady in the refugee center lobby who spontaneously developed mutations, so many people would likely be at least aware it can happen.

**Comment by Amoebka** [comment]
If a NPC trusts you enough to eat your food, you should be able to mutate them without asking by putting it in their food. Mutations are a very poorly understood thing, people shouldn't be able to guess what's happening or why.
