### ISSUE TITLE
High hand encumbrance causes gun aim speed to be zero, and attempting to use a gun locks up the game 

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60171]
### Describe the bug

When your limb scores on your relevant parts are low enough that you have 0.00x gun aim speed, attempting to either view the description of a gun or use it in combat will cause the game to lock up and behave very weirdly.

### Steps to reproduce

1. Wear two+ blankets to max out your encumbrance.
2. Attempt to view or otherwise use a gun.

### Expected behavior

The game shouldn't lock up when trying to view the gun, and you should get a special cased message stating that you don't have a free hand to use a gun, or some other equivalent.

### Screenshots

![image](https://user-images.githubusercontent.com/56016372/184598703-bd8043d0-13e3-4abc-95ad-4101bbe00f32.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: e519404 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Venera3** [comment]
I'll poke at it sometime before Stable, there are a few rough edges around base limbs like that.

**Comment by ANickelN** [comment]
- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 0df7d8f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungus [No_Fungus],
    Translate Complex Dialogue [translate_dialogue]
]

/confirmed
