### ISSUE TITLE
Modded json requirements revert to base game values on destroyed vehicle components

### ISSUE THREAD

**Issue by neonspectra** [CleverRaven/Cataclysm-DDA#60175]
### Describe the bug

There is some quirky behaviour that occurs if you create a mod that overrides an `id` of type `requirement` for recipes regarding vehicle parts.

Specifically, the game will display the original recipe for installation (NOT the mod-overwritten one) if a vehicle component is in the `XX` condition. 

Override of `requirement` values otherwise works as expected for repair of vehicle components at any other condition and for installation of new vehicle components from scratch.

### Steps to reproduce

1. Create a mod that overwrites and existing `requirement` ID for a vehicle part. For example, let's create a mod that removes the welding rod `component` from the `repair_welding_standard` requirement:
```json
[
  {
    "id": "repair_welding_standard",
    "type": "requirement",
    "//": "Repair of steel/iron items",
    "qualities": [ { "id": "GLARE", "level": 1 }, { "id": "HAMMER", "level": 2 } ],
    "tools": [ [ [ "welder", 20 ], [ "welder_crude", 30 ], [ "toolset", 30 ], [ "oxy_torch", 4 ] ] ],
    "components": [
      [ [ "steel_tiny", 1, "LIST" ] ]
    ]
  }
]
```
2. Create a brand new character in a brand new world with only `dda` and your test mod created in step 1 loaded.
    - For ease of recreation, I find it easiest to use the Helicopter Crash start, since it spawns you right onto a vehicle with destroyed components on it.
3. (e)xamine a vehicle and attempt to (r)epair components. You will notice that your modded `requirement` displays properly on most components, but that any destroyed components (`XX` condition) will still show the original requirement as loaded from the base game.

### Expected behavior

Overridden requirements should remain consistent no matter the condition of the vehicle part that they have been overridden for.

I double checked and verified the `vehicleparts.json`... the `requirement`  values do not appear to have a unique value for destroyed components vs installation of new components.

I imagine that there's some kind of weird hardcoded shorthand to replace components and use the base game `requirement` value.

### Versions and configuration

- **OS:** Windows 11
- **Game Version:** Experimental 2022-08-14-1749
- **Graphics Version:** Tiles
- **In-Game Language:** English
- **Mods Loaded:**
    - `dda`
    - The test mod we created in order to produce this bug

### Additional context

Please feel free to create your own mod to test, but for your convenience I've attached a test demonstration mod that does what I described in the steps to reproduce.

[test-mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9337604/test-mod.zip)

**Comment by neonspectra** [comment]
Oh, whoops, I left a part out of my demonstation for this that you might think to yourself is the cause here (but isn't).

For the creation of new vehicle parts (such as frames for example), as per `vehicleplarts.json`, it actually makes use of `welding_standard` for the requirement, not `repair_welding_standard`. I've tried overwriting both `welding_standard` AND `repair_welding_standard`, and the quirky behaviour still occurs. 

This indicates to me that the unexpected behaviour is linked to a quirk in the game itself, as opposed to a requirement that I've missed here.

**Comment by sonphantrung** [comment]
Can confirm

**Comment by sonphantrung** [comment]
Hey @neonspectra are you still around?

**Comment by sonphantrung** [comment]
Alright, @neonspectra requirements still work properly, the main culprit of your problem is that you didn't override `welding_alloys` and `repair_welding_alloys` (repaired using aluminum welding wires)
