### ISSUE TITLE
(e519404) Bandaging (Basic) item usage converts Fibercloth > Cotton 

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#60181]
### Describe the bug

Using Bandaging Basic with Fibercloth Patch > Makeshift Bandages > Boiled Makeshift Bandage option usage to practice will turn the end (return?) cloth from Fibercloth Patch into Cotton Patch. 

### Steps to reproduce

1. Make Fibercloth Sheet > cut into Fibercloth Patch
2. Make 6x Makeshift Bandage w/ Fibercloth Patch
3. Make Boiled Makeshift Bandage with 6x MSB
4. Attempt Bandaging (Basic)
5. End product after 100% progression returns Cotton Patches.

### Expected behavior

Return item should be originally crafted material I'm guessing? 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: e519404 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna]
]

**Comment by mqrause** [comment]
This is an issue with any kind of chainable recipe. Because components of a crafted item are stored as itypes, which can't have any components themselves, they are lost and set to the default if you use a crafted item as a component.

**Comment by evankimori** [comment]
> This is an issue with any kind of chainable recipe. Because components of a crafted item are stored as itypes, which can't have any components themselves, they are lost and set to the default if you use a crafted item as a component.

Ah so it's a limitation of current system and classing? That's disappointing. Issue closed for now then until this limitation can be bypassed?

**Comment by mqrause** [comment]
The only currently possible way to solve this specific case without diving into C++ is to make fibercloth bandages their own item separate from cotton bandages. But I'm not sure it that's a desired change.

It's still a valid issue, so I don't think you need to close it. Although there might be other ones describing the same underlying problem.

**Comment by evankimori** [comment]
> The only currently possible way to solve this specific case without diving into C++ is to make fibercloth bandages their own item separate from cotton bandages. But I'm not sure it that's a desired change.
> 
> It's still a valid issue, so I don't think you need to close it. Although there might be other ones describing the same underlying problem.

Of course, noted. I checked the Issue list and couldn't really see anything matching the desc but I'll leave that up to the more skilled persons than I to do an issue merge if needed. I'm just a testing public after all. :)

Thanks for your input!

**Comment by descan** [comment]
To clarify, I don't think you'd have to turn the bandages into boiled ones, would you? Or do you need that extra step to erase the information about them being made from fibrecloth?

**Comment by mqrause** [comment]
Ah, yeah, you're right. I misinterpreted the issue. It's actually the practice recipe at fault here, because it always produces cotton. Still the only way to solve this currently is splitting up the items and then also the practice recipe. (Or removing fibrecloth from the bandage recipe if you wanna be evil.)

**Comment by evankimori** [comment]
> Ah, yeah, you're right. I misinterpreted the issue. It's actually the practice recipe at fault here, because it always produces cotton. Still the only way to solve this currently is splitting up the items and then also the practice recipe. (Or removing fibrecloth from the bandage recipe if you wanna be evil.)

Here's a question. I'm seeing the Nested listings for the Steel armor in Innawoods with recent experimental (14 Aug 2022) - would a Nest system be able to be used for this issue?
