### ISSUE TITLE
Continue adding generic functional names for guns

### ISSUE THREAD

**Issue by Cimanyd0** [CleverRaven/Cataclysm-DDA#60184]
### Is your feature request related to a problem? Please describe.

This interface option exists:

> Show gun brand names
> If true, show brand names for guns, instead of generic functional names - 'm4a1' or 'h&k416a5' instead of 'NATO assault rifle'.

However, with the option off (default), many guns still show only brand names.

### Solution you would like.

As @I-am-Erk said in #50137, gun names should answer the question "Is this a gun, or an automatically generated password?"

Each gun should (by default) have a name that fits the system Erk describes there, or at least a name that's more useful than its brand name and nothing else.

This can be done by changing the name of the gun. If you want the old name to stay when the show-brand-names option is on, add it as a gun variant.

### Describe alternatives you have considered.

Turn on Generic Guns.

### Additional context

#46814 added the option. It was part of a larger feature to combine similar guns into identical variants, which is fine but not what this issue is about.

[The Hitchhiker's Guide has a list of "guns"](https://nornagon.github.io/cdda-guide/#/item) (scroll down to "GUN (GUNS)"). Variants are only visible in the individual item pages, or by searching for their names. Here you can see:
- Some guns have already been variantized: M16 auto rifle (M16A3, Remington ACR); M1911 pistol (M1911, M45A1)
- Some have only a brand name: M11; M1911A1
- Some already have a description in their name, with no variants: M1 carbine; M79 launcher
- Some are two different items that have the same generic name: Glock pistol (Glock 20, Glock 40 MOS); Glock pistol (Glock 21)
- Some are fictional guns that have a description in their name: A7 laser rifle; RM2000 submachine gun
- Some are fictional guns that are trying to be passwords: RM216 SPIW; RM614 LMG
- Some are irrelevant items like bows and crossbows, homemade guns, and pseudo items for bionics or monster special attacks.

[This documentation](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#generic-items) describes how variants work, in the part that starts with this:
>`"variant_type": "gun"`
>`"variants": [        `

#50203 split the "NATO assault rifle" into three items, so the example in the option description isn't real anymore.

**Comment by Marcos6226** [comment]
What is the purpose of generic names anyway? I know what these guns are just by they designation name (brand name). And I personally like they password like names to be honest.

P.S. I'm not criticizing the efforts to create generic names, I'm curious about it's purpose.

**Comment by anothersimulacrum** [comment]
> I know what these guns are just by they designation name (brand name). And I personally like they password like names to be honest. 

That's why the option's there. If you don't know guns, it's a bunch of meaningless noise and it makes guns really hostile to interact with.

As to the broader issue: I need/want to write up some guidelines/documentation on how exactly this should be done (or rather, how I did it and I think it should be extended), and then continue to work on it.
