### ISSUE TITLE
Zombie Children aren't also human.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60197]
### Describe the bug

![image](https://user-images.githubusercontent.com/22281606/184792080-cd7c3e01-fa22-4074-aebd-aaf633a2b9bc.png)
![image](https://user-images.githubusercontent.com/22281606/184792089-8c0539f2-db83-41b8-a572-0d2c021b3e88.png)

### Steps to reproduce

Take photos of zombies, discover children aren't human.

### Expected behavior

Children are human

### Versions and configuration

Win 10, 013e053, tiles

**Comment by hexagonrecursion** [comment]
/confirmed

It took me some time to figure out **what** this is a screenshot of.

To reproduce:

1. Take a photo
2. Open the "creatures" tab of the "view factions" dialogue

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cee383c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Marcos6226** [comment]
I'm going to check it.

**Comment by chrispikula** [comment]
@hexagonrecursion , my apologies, I forget that not everyone is as much of a shutter hound as I am.  :-p
