### ISSUE TITLE
Variant T-Shirts do not disassemble, while the generic item version does

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#60190]
### Describe the bug

Just a mismatch in un-crafting, I guess? T-Shirts with logos (like the Cthulhu one) do not have disassembly code, while the generic T-Shirt does.

### Steps to reproduce

1. Spawn all the shirt
2. Disassemble not!all the shirts.

### Expected behavior

They should all disassemble in the same manner, since they're materially the same item.

### Screenshots

Generic Shirt:
![image](https://user-images.githubusercontent.com/4212389/184757397-62daa634-4012-4f30-a5e3-98af433feffd.png)
![image](https://user-images.githubusercontent.com/4212389/184757416-820e6802-36fa-4966-bca5-cc4c4c370ee6.png)

Variable Shirt:
![image](https://user-images.githubusercontent.com/4212389/184757441-9e3b78d0-a458-4a24-bf14-3c67b6183a46.png)
![image](https://user-images.githubusercontent.com/4212389/184757453-eeb4034d-9ab2-4847-97f1-c1d14db0a101.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: a0c8184 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Marcos6226** [comment]
I'm going to try to check it.


P.S. You're a great bug hunter.

**Comment by descan** [comment]
> I'm going to try to check it.
> 
> P.S. You're a great bug hunter.

I may not know how to *fix* them (even when I know they're actually dead simple easy to fix, it just doesn't work for me? I've tried, I swear.) but I *DO* know how to break games. Or, in this case, notice weird and (usually, though not always) minor things going on, like having a bunch of t-shirts in my pile that only some of which can be disassembled. Thanks for the compliment!

**Comment by Marcos6226** [comment]
> I may not know how to _fix_ them (even when I know they're actually dead simple easy to fix, it just doesn't work for me? I've tried, I swear.) but I _DO_ know how to break games. Or, in this case, notice weird and (usually, though not always) minor things going on, like having a bunch of t-shirts in my pile that only some of which can be disassembled. Thanks for the compliment!

You're welcome.

I may also have found the issue, but I'll have to wait until tomorrow (it's 23:00 pm where I'm now) to try to fix it (too tired to think straight).
See you later. =)

**Comment by Marcos6226** [comment]
I'm sorry, but I wasn't able to find where the disassembly data is located. That means I can't fix this issue until I find out where it is.

If someone knows where it is or how I can do it, I'll be very grateful. Thanks

**Comment by descan** [comment]
> I'm sorry, but I wasn't able to find where the disassembly data is located. That means I can't fix this issue until I find out where it is.
> 
> If someone knows where it is or how I can do it, I'll be very grateful. Thanks

I believe there is a json file name "uncraft"? That might be where it is.

**Comment by Marcos6226** [comment]
> I believe there is a json file name "uncraft"? That might be where it is.

It took me some time, but I have finally found where that data was stored. Well, thanks for the suggestion anyway. I really appreciate it. =)
