### ISSUE TITLE
Crash when accepting mission "Kill Horde Master" from NPC

### ISSUE THREAD

**Issue by ZyonGui** [CleverRaven/Cataclysm-DDA#60210]
### Describe the bug

On ground surface, when trying to accept the quest "Kill Horde Master" from the following NPC, the moment player choose the "I'll do it!" accept option, the whole game freezes, stop responding and crash, without any bug report.

### Steps to reproduce

1. find a follower with the "Kill Jabberwock" questline
2. proceed to complete all the quests till "kill 100 zombies"
3. try to accept the next quest
4. Crash

### Expected behavior

A horde is supposed to spawn with a horde master within, giving the quest a target, the player then proceeds to kill said horde master and finish the quest with the NPC

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ZhilkinSerg** [comment]
Please provide savegame.

**Comment by TealcOneill** [comment]
@GuardianDll Can't replicate, I've tried it twice.
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-0120 731bdaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
