### ISSUE TITLE
Add the emergency blanket as a component for the makeshift sling

### ISSUE THREAD

**Issue by Crudbone** [CleverRaven/Cataclysm-DDA#60215]
### Is your feature request related to a problem? Please describe.

It doesn't make sense to me why an emergency blanket can't be used to make a makeshift sling when all the other blanket variants can. 

The description for the emergency blanket reads: "A blanket made of space-age material that covers your most important body parts. It folds into a very compact form when not in use." 

"Space-age material" is a bit vague but nothing about its description seems like it would prevent someone from tying it into a sling.

### Solution you would like.

Add the emergency blanket as a component for a makeshift sling.

### Additional context

I'll make the PR for this but first I need to know if there are any objections before I start.

**Comment by ANickelN** [comment]
Makes sense that you can, especially considering all other blankets are able to.  Probably just an oversight.
