### ISSUE TITLE
Kevlar Nape Protector Can't Spawn

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#60220]
### Is your feature request related to a problem? Please describe.

Kevlar Nape Protector doesn't have a spawn location set, unlike its nomal cotton counterparts.

### Solution you would like.

Add it to the same group for military/tactical gear, to give it a reasonable chance to be found.

**Comment by Kantonine** [comment]
Also can Counterweight Pouches be added as well?

**Comment by Marcos6226** [comment]
I think this can be done. I'll check it out.
