### ISSUE TITLE
ExperARMental - Crash On 'Save and Quit'

### ISSUE THREAD

**Issue by indigorain** [CleverRaven/Cataclysm-DDA#60222]
### Describe the bug

Game crashes (segfault?) on ARM when the player chooses to 'save and quit'

Crash has also occurred with 'quicksave' and also loading up a world that had crashed previously.

### Steps to reproduce

Make world
Play
'S'ave and quit. 'Y'es. 
Good bye cruel world

### Expected behavior

I should be able to save the game.

### Versions and configuration

Raspberry Pi OS, 64bit
04:32:55.013 INFO : Cataclysm DDA version aba7fd9
04:32:55.013 INFO : [main] C locale set to en_US.UTF-8
04:32:55.014 INFO : [main] C++ locale set to en_US.UTF-8
04:32:55.027 INFO : [options] C locale set to en_US.UTF-8
04:32:55.027 INFO : [options] C++ locale set to en_US.UTF-8
04:32:55.029 INFO : Setting language to: 'en'
04:32:55.030 INFO : [i18n] Scanning core translations from lang/mo/
04:32:55.030 INFO : [i18n] Scanning mod translations from ./mods/
04:32:55.030 WARNING : opendir [./mods/] failed with "No such file or directory".
04:32:55.415 WARNING : opendir [./mods/] failed with "No such file or directory".
04:33:34.593 WARNING : opendir [./save/Peterborough/mods] failed with "No such file or directory".
04:33:35.537 INFO : src/mod_tracker.h:70: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'overmap_special' does not track object sources
04:34:01.909 WARNING : opendir [./memorial/] failed with "No such file or directory".

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9354831/crash.log)

**Comment by NetSysFire** [comment]
You need to update because there have been fixes in the meantime, see #60015 and also potentially #60008.

**Comment by indigorain** [comment]
Well, it took three hours to compile last time, after many failed attempts. And it has aborted a few times with a more recent experimental, and I've yet to compile.

I'm closing this, as I don't have the time to make further attempts and see if it's unique to ARM or if it's a different bug.
