### ISSUE TITLE
Not being able to disassemble too heavy/big object on a workbench

### ISSUE THREAD

**Issue by DekerVke** [CleverRaven/Cataclysm-DDA#60221]
### Describe the bug

I was trying to disassemble a combat mech. I couldn't do it and the game prompted me to use a workbench. I put it on one yet the problem persisted. Then some fine lads over at discord suggested I could need a lifting device or maybe do it on a crafting spot rather than a workbench. Nothing worked.

### Steps to reproduce

1. Have a combat mech, or something as big/heavy as one.
2. Put it over a workbench
3. Try to disassemble it.

### Expected behavior

I expected the mech to get disassembled after putting it on a workbench to get that sweet cannon.

### Screenshots

![image](https://user-images.githubusercontent.com/111388850/184972080-ff1804ef-6886-4050-a89f-b61e2a970c20.png)
![image](https://user-images.githubusercontent.com/111388850/184972142-890d9370-c975-48bc-89ee-0661612c6d10.png)
![image](https://user-images.githubusercontent.com/111388850/184972191-931e16bf-925b-4028-839f-e27bba0a05b3.png)
![image](https://user-images.githubusercontent.com/111388850/184972218-31047c09-5929-48b6-a6a6-48bb14652068.png)
![image](https://user-images.githubusercontent.com/111388850/184972579-39a313b5-f69b-4f55-8964-47a6d264307a.png)
![image](https://user-images.githubusercontent.com/111388850/184972623-81975d31-ebdc-4667-b05d-8510afa81b45.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 07d8e66 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries]
]

**Comment by esotericist** [comment]
for anyone looking to do something about this, the fundamental problem is that the upper cap on mass for crafting appears to be about 1,000 kg (see: crafting spot fake workbench), while the broken combat mech is almost half again that.

simple solution would be increase mass allowance of the fake workbench for ground crafting, but we also need to ask "should mechs have this much mass". i personally have trouble reasoning about these numbers, so i have no idea if they're "right" or not.

a more involved solution that could be neat would be an engineering workbench with an integrated crane and a very large mass capacity. the exodii should definitely have something like this, and the player could conceivably build something themselves to that effect.

if someone is really feeling ambitious, adding nearby lifting devices to the capacity of the workbench would be nice.
