### ISSUE TITLE
Picking red hornmoss destroys tile, leaving Nothing behind.

### ISSUE THREAD

**Issue by rGhede** [CleverRaven/Cataclysm-DDA#60227]
### Describe the bug

Picking horn moss for horn moss capsules destroys the terrain, leaving an impassable nothing, that cannot be interacted with.

### Steps to reproduce

0. Wilderness start, Magiclysm world.
1. Spawn on in a wilderness location near red hornmoss in the spring, possibly swamps or island swamps or lakeshore locations?
2. Press e and harvest the red hornmoss
3. Stare into the void

### Expected behavior

That it would leave behind a harvested horn moss, or bare dirt tile.

### Screenshots

![image](https://user-images.githubusercontent.com/66904466/185006225-a40ae5dc-635a-424b-880a-edec05c59694.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 07d8e66 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]
]

**Comment by Marcos6226** [comment]
#60204 fix it, but you will have to wait until it gets merged.
