### ISSUE TITLE
Quadrupeds Still Hate Players

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#60231]
### Describe the bug

After the recent changes to monster triggers from @venera3 creatures are not supposed to become hostile to the player unless the player is the attacker.  However, if, for example, one Exodii Quadruped shoots another Quadruped by accident, they become hostile to the player.  I don't know the ins and outs of this, I just know it shouldn't be that way.

### Steps to reproduce

Spawn several Exodii Quadrupeds close together
Spawn a gaggle of enemies
Enemies and quadrupeds will fight, and the quadrupeds may accidentally damage each other.
Observe that some of the offending quadrupeds are hostile to you as the player.
Promptly be murdered by the Exodii despite being innocent.

I've been able to get this to happen pretty reliably. There's a video below.

### Expected behavior

After the recent changes to triggers, I expect the Quadrupeds to be hostile to whatever damages them/triggers their aggression but they should not attack the innocent player character.

### Screenshots

Here's a video of my doing some routine testing when this first popped up. You'll notice the exodii on the left becomes hostile.  It then shoots the other quadruped.  When that quadruped flees and the player is now the closest target, it shot the player.  Sorry for the long pauses, I should have edited this down a little.  

https://youtu.be/lm5d33djrPY

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: a0c8184 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

None, really.  This is still better than it used to be, where they became hostile at the drop of a hat. It seems this is tied to them hitting each other, specifically.  It's also unlikely that other enemies would have this happen, since most enemies don't have ranged attacks and would never melee their own 'species' or whatever it's called.  So this is probably only an issue for ranged attackers, like the quadrupeds.

Also in the video I get an error popup about a damage type of 'NONE'.  Seems unlikely that's connected but it's worth pointing out.

**Comment by Venera3** [comment]
Oh, right, that will be a problem - monster spells route through a fake NPC when casting unless I'm mistaken. 

I'll try digging into it if there's a low-hanging solution but it might be tricky.

**Comment by TheMurderUnicorn** [comment]
I would not have guessed it worked that way but it makes a lot of sense, you said NPCs count as players for the purposes of determining hostility, right?  Well, the vast majority of monsters with spell based attacks are already hostile, the quadrupeds may be the most noteworthy issue with this, then.

**Comment by Venera3** [comment]
It's actually their gun attack, not the spells that are the problem. I'll see what I can do.
