### ISSUE TITLE
Condition-based names for overmap locations

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#60246]
### Is your feature request related to a problem? Please describe.

It always bugged me out that even a medieval peasant can tell that this location is `hazardous waste sarcophagus`, that location is `FEMA camp`, this one is `electrical substation`, and that one is `gas station`, more over from the distance.

The same for situation when one can easily tell that this weird structure is not only a scout tower, but a _mi-go_ scout tower, even if player hasn't ever seen mi-gos or heard about them.

### Solution you would like.

The easiest solution would be to add a proximity condition. One (vague) name for location is shown when it's unvisited, and another one (accurate) is shown when player came close to the location. E.g. for unvisited location - something like `strange structure`, for visited location - `mi-go scout tower`.

More complex solution would be to add a check for specific conditions. E.g. if player has `Churl` trait, then print something like `stone building` for banks, gun stores, pharmacies and the like. The check for proximity might apply here too.

### Describe alternatives you have considered.

None.

### Additional context

None.

**Comment by GuardianDll** [comment]
partially related to #60196, because items also has such issue - we can detect the cough syrup, m16a4 and 5-point anchor even when character is dumb clerk that dont know how to use a sword

**Comment by NetSysFire** [comment]
I think another potential use case would be at least some of the magiclysm locations, e.g the black dragon lair which is marked as "swamp?" and also the wizard lake tower stuff since you will recognize once you have been there.

**Comment by PatrikLundell** [comment]
It makes logical sense that you don't automatically know what a building is used for at a distance, but it adds game play tedium to have to visit every building in every town to find the buildings you're interested in.

Technically you'd also have to take the various maps with marked points of interest into consideration if you were to implement it. A gun shop identified as such by a map should be identified on the overmap without requiring a visit in person.

**Comment by GuardianDll** [comment]
Well, it can depend on map itself and on some player's stats - small gun shop is really hard to miss between another buildings, but small shop with giant "WEAPON" billboard is hard to miss.
I guess we can make an additional fields to overmap terrain jsons, so it will looks like this:
`name`, that describe a map from average distance (like our gun shop with huge table) (i guess almost every shop shop has such)
`name_afar`, that describe a map, that you spot from really huge distance, and not sure what it can be (like "huge building" in the middle of the road like tcl, or exodii mountain) (i guess gas stations and hotels has pretty easy to spot tables, so they must have identical name and name_afar)
`name_inside`, when the only way to find what is this location you need to be really close, even inside of it (like lab entrance)
