### ISSUE TITLE
Bleeding should make you smell more.

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#60242]
### Is your feature request related to a problem? Please describe.

It is a common theme in media that predatory monsters will pick up the scent of blood and track their targets more easily. Research has shown that bears and wolves are attracted to the scent of blood, so it makes sense that zombies would be too - a bleeding victim probably means one that's almost dead and that's a good target to prioritize, and even if zombies aren't using that kind of logic, there are still more proteins in the air for them to detect.

### Solution you would like.

A bleeding character (maybe above a certain amount of bleeding) could be slightly smellier. This could create more tension and encourage players to fix themselves up rather than walking around bleeding everywhere, and create risk/reward decisions about patching up injuries on the spot or trying to run for shelter first.

### Describe alternatives you have considered.

This could also apply to sweaty and sleep-deprived characters, unless they are some kind of non-swesting mutant.

It may be necessary to slightly reduce the default scent range if this is implemented, as the player being smellier on average may add unintentional difficulty.

It would be REALLY cool if fresh human blood also emitted a small amount of scent, but I understand that may lead to performance issues. Still, imagine frantically mopping your driveway to try to keep the horde from noticing you, or shooting an NPC to distract the zombies, or using some kind of human chum bucket to lure them somewhere.

**Comment by PatrikLundell** [comment]
The current implementation of bandaging means that it's lethal to try to patch up bleeding unless you're in a very safe location, as your attempt to bandage a wound isn't interrupted by your limbs being ripped off by zombies that happen to close in on you during the attempt. Add a blood smell homing signal, and it's certain death.

**Comment by vetall812** [comment]
Probably add smell correlation with breathing (stamina). Or sweating.

**Comment by anothersimulacrum** [comment]
> This isn't actually true. You can easily just drop your weapon and press . to close up most wounds in a matter of seconds

To be clear, this is definitely a bug.

**Comment by fairyarmadillo** [comment]
> > This isn't actually true. You can easily just drop your weapon and press . to close up most wounds in a matter of seconds
> 
> To be clear, this is definitely a bug.

I'm not sure how this could be a bug. Applying pressure to a minor bleeding wound IRL will help the body clot.it quickly even if you don't dress it. To be clear I'm not talking about major injuries, just the standard nicks and scrapes.

Has this been discussed anywhere, or do you have more specifics?

**Comment by anothersimulacrum** [comment]
I meant more non-minor injuries, though I am unsure if even then the timescales are correct (but I don't know, so there's nothing to go on there).

**Comment by fairyarmadillo** [comment]
Oh for sure. I don't think applying pressure to major injuries effectively staunches them before blood loss becomes a problem. If it does that should probably be looked at.

Those sorts of injuries are fairly rare and often you want to get away from enemies and torniquet/powder the wound or bandage it.

I think adding a tile or two to the player's scent radius while bleeding would only significantly worsen their situation if they refused to stop and address the issue, or if they attempted to do first aid without pulling back out of the hot zone. These actions probably should be punished IMO, and for players who want to barrel ahead, there's still hemostatic powder, which is very quick.
