### ISSUE TITLE
The proficiency list should have in-progress proficiencies at the top, and completed ones at the bottom

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60252]
### Is your feature request related to a problem? Please describe.

When I am training proficiency in anything, I check it repeatedly, which isn't too bad early game.  Late game, however, I need multiple key-presses to find my progress, @\->p\->/->name or @\->shift-tab->↑

### Solution you would like.

If the in-progress ones were at the top, this gets reduced to @

### Describe alternatives you have considered.

A method to hide known proficiency in the @ menu, either with child ones auto-hiding their parents, or something like hiding recipes in the crafting menu.

You don't really care about 'Electronic Circuits' when you're training 'Semiconductors', yet once you've got too many proficiencies, guess which one is still visible w/o scrolling.

**Comment by PatrikLundell** [comment]
I'm not sure that's the only use case for a particular sorting order. What I'm trying to say is that there should be some care taken when considering any fixed sorting order to ensure all other use cases aren't screwed over by my favorite (at the moment) case.
Allowing player control over the sort order (remembered between invocations) might be a better solution (and more work to implement).
