### ISSUE TITLE
large amount of stackable items in inventory causing lag when using(a) or picking up(g) items

### ISSUE THREAD

**Issue by Citizen-of-Arcadia** [CleverRaven/Cataclysm-DDA#60277]
### Describe the bug

A save folder has been provided(.zip), this happened on Experimental(2022-08-18-1622).
We tried to search for similar issues with a generic "lag" word and looked through a dozen but none seemed too similar.

In more detail, the character has a daypack with 448 cotton patches inside(amongst various other items) and a large amount of items in the top left corner from them(numpad 7), when trying to pick up items(with "g") from that top left corner or trying to open the "use item" menu(with "a") the game loads for ~14s(slightly less when opening the "use item" menu) before opening the requested menu.
When either the whole daypack, or at least all 448 cotton patches are dropped from the daypack, the game only loads for  ~1s before opening the requested menu.

### Steps to reproduce

1. Load the save.
2. Try opening the "use item" or "pick up item" menus, the latter from that specific tile.

### Expected behavior

Expected the game to load the requested menus much quicker.

### Screenshots

![image](https://user-images.githubusercontent.com/49358371/185459933-2435a1e0-74a6-40f3-85df-cc48c2d07314.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.2; Release: 20.2; Codename: uma; 
- Game Version: f54229a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[2035.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9376276/2035.zip)

**Comment by andrei8l** [comment]
/confirmed

![Screenshot from 2022-08-18 21-31-51](https://user-images.githubusercontent.com/68240139/185468656-36e69bd0-0d19-472f-a4ba-600a74d70cd8.png)

It was introduced by https://github.com/CleverRaven/Cataclysm-DDA/pull/60151 and reverting 935e3dfa43c350214c5b1d664ae6d717cf42581f restores old performance.
