### ISSUE TITLE
Bollards are too resistant to damage.

### ISSUE THREAD

**Issue by DekerVke** [CleverRaven/Cataclysm-DDA#60276]
### Describe the bug

I wanted to remove some bollards to push my vehicle through. I couldn't deconstruct them, so I decided to bash it. Didn't work.
I tried dynamite yet they still were standing. Resorted to a C4, fixed my issue as the walls disappeared but the bollards are still there, mocking me.

### Steps to reproduce

1. Find a bollard.
2. Tried to deal with it.
3. Fail.

### Expected behavior

They should stop vehicles (depending on the speed and mass) but in no way should they be able to stand after a C4 explosion.

### Screenshots

![unknown](https://user-images.githubusercontent.com/111388850/185431793-3158b7be-37aa-4474-9c1d-07fef16e860f.png)
![unknown](https://user-images.githubusercontent.com/111388850/185431929-2b7739ac-5f03-44a2-a0d8-28255cb114b8.png)
![unknown](https://user-images.githubusercontent.com/111388850/185431987-0090b673-d9d0-4e17-ab30-0b07cf44bf42.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 07d8e66 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries]
]

**Comment by Night-Pryanik** [comment]
> in no way should they be able to stand after a C4 explosion.

Are you sure on this? This is a solid piece of sturdy metal, after all.

**Comment by DekerVke** [comment]
A valid point and I'm unsure how to prove if they would or wouldn't stand after a 1 kg of C4 IRL. But what about creating an option to remove them, like sawing them with a hacksaw?

**Comment by Maleclypse** [comment]
`[K-rated bollards](https://www.reliance-foundry.com/bollard/crash-rated-bollards), as well as fences, medians, and other forms of perimeter security installation, are tested barriers proven to stop a 15,000-pound diesel truck impacting at 30, 40, or 50 mph. The Department of State was particularly interested in preventing bombs or other explosive payloads from being delivered to structures, so by 2003, DoS K-ratings came to focus on devices that would prevent a truck’s flatbed from penetrating [farther than 3.3 feet](https://www.fema.gov/media-library-data/20130726-1624-20490-9648/fema430.pdf) through a structure. If bollards or other perimeter obstacles are shown to stop a concerted attack within a meter, they are useful in the site planning of safe zones around targeted installations.`

<https://www.reliance-foundry.com/blog/k-rated-bollards>

Video of a semi truck hitting a bollard and not moving it.
<https://www.reddit.com/r/CatastrophicFailure/comments/4sm7u9/truck_vs_safety_bollard/>


A hacksaw isn't going to cut it.
