### ISSUE TITLE
Granular height should be replaced with categorical height (short/medium/tall)

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60278]
### Is your feature request related to a problem? Please describe.

Currently height should have a reasonably big impact on how your character manages in-game survival but the height number in cm (145-200) is basically just flavor text. This is partially because granularizing the system to such a degree makes exploring its effects pretty difficult so it may actually be better to split it into categories that you pick on character creation.

### Solution you would like.

Split size into 3 human sizes, and 2-4 mutant sizes. 
Medium sized humans should have no effects, they should be the standard as things are now.
Short humans should have various penalties and advantages, such as easier stealth/dodge, less food consumption, less carry weight, slower movement speed, difficulty climbing, less threatening to NPCs, and so on.
Tall humans should have various penalties and advantages, largely the inverse of short humans - can carry more, run a bit faster, can climb more easily, are scarier to NPCs, and so on, but they have a harder time staying hidden (noisier footsteps), can't dodge as easily due to their height, need to eat more food, and so on.
Mutant sizes could be "Large = Tall+" and "Small = Short+" with minor differences from those sizes, but otherwise treated as those sizes, while Tiny and Huge can be treated as extreme special variants which are separate size categories.

This could be an opportunity to adjust the way clothing was fitted or unfitted, as clothing could be defined a specific height category it was intended for, rather than simply being fitted, or unfitted. It would also solve "fitted" clothing being "fitted" for all NPCs, so instead if you and your buddy are both tall, you can share clothing, but you can't fit in medium sized clothing as well but medium sized clothing would fit a different NPC. It could also allow for separate penalties, such as less coverage on tall people wearing short people clothes. Medium-sized clothes would probably be the most common, and zombie children could specifically drop Short-category clothes. For HUGE and TINY mutants, specific XL and XS gear would no longer need to be defined but instead simply another size, and using nested crafting you could be given the option to craft "Very Short, Short, Medium, Tall, Very Tall" gear depending on circumstance although this would probably be an obscene amount of JSON churn.  

### Describe alternatives you have considered.

Height absolutely should affect your character and it currently basically doesn't except for people using it to cheese specific game systems. But using a granular height model will make it really difficult to actually implement benefits and drawbacks. 

I have no idea how difficult this would be to implement (in any case it's way beyond me) but I assume it would require an very large amount of code. However I figured I'd share my ideas in case anyone else ends up agreeing with them.

Age could also be replaced with "Young, Middle-aged, Old" with similar consequences but that's out of scope for the discussion most likely.

**Comment by PatrikLundell** [comment]
I'm not sure about climbing. A tall person has a longer reach, and can thus use support that's out of reach of a shorter person, but a lighter person can use support that's too weak to bear the weight of a heavy person. Obviously, height and weight isn't directly correlated, but if you constrain the comparison to people of similar build it is.
