### ISSUE TITLE
Dissecting zombie runner does not give biology proficiency 

### ISSUE THREAD

**Issue by Tr1p0re** [CleverRaven/Cataclysm-DDA#60294]
### Describe the bug

Dissecting zombie runner's corpse won't increase your Principles of Biology progress, while dissectiing other zombies would.

### Steps to reproduce

1. Spawn a character with melee skills, X-acto and a weapon
2. Spawn a normal zombie, a zombie runner and a tough zombie
3. Beat them up
4. Dissect their bodies
5. Zombie runner will not increase your proficiency, while others would

### Expected behavior

Dissecting zombie runner should increase your Principles of BIology poficiency

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Google; Model: Mediatek MT8173 Chromebook; Release: 9; Incremental: 8843055; 
- Game Version: 93a5ad9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

First issue, sorry for bad English

**Comment by Marcos6226** [comment]
I can confirm it. The bug is exactly as described.

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: d060cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]
