### ISSUE TITLE
Joint Servo CBM works without power

### ISSUE THREAD

**Issue by actually-a-cat** [CleverRaven/Cataclysm-DDA#60293]
### Describe the bug

~~Joint Servo CBM consumes bionic power, but it works fine without any. It can be activated with no power and will remain on and provide its effect.~~ (This part fixed by #60331) It will also continue to work if power runs out when it is active.

### Steps to reproduce

~~Install the CBM, activate it with 0 power.~~

Install the CBM and some power storage, get some power, activate Joint Servo, use up all power. Observe it continue to be active and provide the effect.

### Expected behavior

It shouldn't.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: f987858 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

_I don't know why it says that, it's on Windows 8.1_

**Comment by Marcos6226** [comment]
I may have found the issue but I'm not certain of how to fix it...

**Comment by bombasticSlacks** [comment]
Apparently this was only a partial fix so I'm reopening.
