### ISSUE TITLE
Allow some things to cut reinforced windows

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#60290]
### Is your feature request related to a problem? Please describe.

I am always frustrated when there is a reinforced window blocking my path to someplace I want to be and I can't use my acetylene torch or angle grinder to cut it open.

### Solution you would like.

The ability to use the acetylene torch or angle grinder to take down reinforced windows.

**Comment by Marcos6226** [comment]
Could you please specify (if possible, including their IDs; you can do this by using [this](https://nornagon.github.io/cdda-guide/#/search/) tool) which windows you want to be able to get cut down?

**Comment by pantherpusher** [comment]
https://nornagon.github.io/cdda-guide/#/terrain/t_ballistic_glass
https://nornagon.github.io/cdda-guide/#/terrain/t_laminated_glass
https://nornagon.github.io/cdda-guide/#/terrain/t_reinforced_glass
