### ISSUE TITLE
NPC medical menu ui crash

### ISSUE THREAD

**Issue by harperers** [CleverRaven/Cataclysm-DDA#60308]
### Describe the bug

trying to check an npc followers medical menu with @ causes a segmentation fault.

### Steps to reproduce

1. Talk to an npc follower and say "I'd like to know a bit more about your abilities"
2. Press @ in the info screen that pops up
3. Crash

### Expected behavior

It should at the very least do nothing, if not open the npcs medical menu

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: dd59e08 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Xaleth** [comment]
confirmed on latest experimental

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/185901915-49fac1c2-26c5-44ed-a034-b428665895f4.png)

**Comment by ZhilkinSerg** [comment]
```DIFF
diff --git a/src/player_display.cpp b/src/player_display.cpp
index 68c753c2ee9..89f41c0d8c7 100644
--- a/src/player_display.cpp
+++ b/src/player_display.cpp
@@ -1265,7 +1265,9 @@ static bool handle_player_display_action( Character &you, unsigned int &line,
         ++info_line;
         ui_info.invalidate_ui();
     } else if( action == "MEDICAL_MENU" ) {
-        you.as_avatar()->disp_medical();
+        if( you.is_avatar() ) {
+            you.as_avatar()->disp_medical();
+        }
     }
     return done;
 }
```
