### ISSUE TITLE
Taking Down Aluminum Stepladder Gives Wooden Stepladder

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#60304]
### Describe the bug

When an aluminum stepladder is placed, a material-less "stepladder" object is created.  When that stepladder object is taken down, a wooden stepladder item is created (rather than an aluminum stepladder).

### Steps to reproduce

1. Spawn aluminum stepladder item.
2. Place aluminum stepladder object.
3. Take down aluminum stepladder object.
4. Observe the wonders of alchemy as a wooden stepladder item is created!

### Expected behavior

Taking down a placed aluminum stepladder should result in the creation of an aluminum stepladder item.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: d060cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots]
]

**Comment by Marcos6226** [comment]
The issue is that, right now, we only have one terrain and furniture ladder, and as you can already guess, it's the wood one.
Fixing this will take some time but it's possible if someone adds a aluminum variant of the terrain and furniture wood ladder.

**Comment by Karol1223** [comment]
> The issue is that, right now, we only have one terrain and furniture ladder, and as you can already guess, it's the wood one. Fixing this will take some time but it's possible if someone adds a aluminum variant of the terrain and furniture wood ladder.

That's not the issue whatsoever, that's a 5 min fix. The problem is the activity to set up a ladder automatically defaults to the wooden variant and I don't see an easy way to change that, even if a new furniture is made. Having said that I'll try my best to fix this mess I caused, honestly should have predicted this would happen with a new ladder.

**Comment by Night-Pryanik** [comment]
I made a PR to fix this issue: #60330.

**Comment by ChromePoptart** [comment]
Thanks, @Night-Pryanik!
