### ISSUE TITLE
No way to get gun crossbow mod

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#60309]
### Describe the bug

There is no way to get this item in game

can be seen on https://nornagon.github.io/cdda-guide/#/item/gun_crossbow_mod

### Steps to reproduce

Found this when doing some other testing.

### Expected behavior

Should exist or be removed

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0.F-10713-gd65b67088a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed fgrep -r gun_crossbow_mod data/json/ src/ finds only the item definition, but no spawns or recipes

9d29e9359f7eb52b23f1bd3f5d8fc979bbdaac99

**Comment by RenechCDDA** [comment]
Unavailable item was removed in #68108, closing as resolved.
