### ISSUE TITLE
No longer able to heat food with an oven appliance

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#60318]
### Describe the bug

Sometime between August 8 and August 18 oven appliances have lost their hotplates.

Examine menu, build cdda-linux-tiles-x64-2022-08-08-0746

![exa_08](https://user-images.githubusercontent.com/55463047/185725184-cf3c99e5-3b91-43d2-91be-7cbf84e1a9d0.png)

Examine menu, same exact oven, build cdda-linux-tiles-x64-2022-08-18-0523

![exa_18](https://user-images.githubusercontent.com/55463047/185725199-3673a726-522e-4f69-aae7-a2eb552bc3a2.png)

### Steps to reproduce

1. Examine an oven
2. See that there is no Use Hotplate action anymore

### Expected behavior

I expect to be able to heat food using an oven appliance.

### Versions and configuration

Game version: cdda-linux-tiles-x64-2022-08-18-0523
Mod list: default

**Comment by ZeroInternalReflection** [comment]
This, along with a couple of similar examine-actions, was broken in #56991.  #60232 should fix it (due to some of the changes involved, it will show up as "use oven" rather than "use hotplate").
