### ISSUE TITLE
Wing/Inboard Mirrors Allow Seeing Through Blindfold

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#60317]
### Describe the bug

When onboard a vehicle and in view of an installed wing mirror or inboard mirror, the mirror seems to grant vision of tiles to the player even if player is wearing a blindfold.

Other things of note:
1. Behavior is the same whether wearing blindfold, makeshift blindfold, or duct tape blindfold.
2. Seems like the issue might only be in code that calculates which tiles the player has vision of -- for example, even if tiles are being shown when wearing a blindfold, trying to craft still results in "You can't see to craft!"

### Steps to reproduce

1. Find a vehicle with either an inboard mirror or a wing mirror installed.
2. Go onboard vehicle and enter a tile where the mirror can be seen.
3. Check vision radius without blindfold on.
4. Wear blindfold, and check vision radius again.
5. Verify vision radius is normal when mirror is out of view or after exiting vehicle.

### Expected behavior

The player should still not be able to see when wearing a blindfold even if in a vehicle within view of a wing mirror or inboard mirror.

### Screenshots

No mirrors installed in vehicle, not blindfolded:
![no mirrors, not blindfolded](https://user-images.githubusercontent.com/109529281/185724479-042ffbff-dd88-45c8-9a63-8eb4406a3dea.jpg)

No mirrors installed in vehicle, wearing blindfold:
![no mirrors, blindfolded](https://user-images.githubusercontent.com/109529281/185724491-6c5cf41c-e87e-4cfe-a964-7f89ffd11fa6.jpg)

==================================

Wing mirrors installed in vehicle but NOT in view, not blindfolded:
![Mirrors not visible, no blindfold](https://user-images.githubusercontent.com/109529281/185724506-4a4cd9f5-6dc5-47c6-9c15-199bc09b69fc.jpg)

Wing mirrors installed in vehicle but NOT in view, wearing blindfold:
![Mirrors not visible, blindfold](https://user-images.githubusercontent.com/109529281/185724529-82b7c846-b21e-4883-aac3-e0ac0a2651ca.jpg)

==================================

Wing mirrors installed in vehicle and ARE in view, not blindfolded:
![Mirrors visible, not blindfolded](https://user-images.githubusercontent.com/109529281/185724539-39cd4e4d-348f-4dd8-a7dc-f9e4598b8bc0.jpg)

Wing mirrors installed in vehicle and ARE in view, wearing blindfold:
![Mirrors visible, blindfolded](https://user-images.githubusercontent.com/109529281/185724544-255abe47-bfbe-4b4e-b0bc-08da496c4fb3.jpg)

==================================

Inboard mirror installed in vehicle (1 tile south of seat) and IS visible, not blindfolded:
![inboard mirror, not blindfolded](https://user-images.githubusercontent.com/109529281/185724569-8d8dd7fc-84be-4789-9e2f-566b266a89e8.jpg)

Inboard mirror installed in vehicle (1 tile south of seat) and IS visible, wearing blindfold:
![inboard mirror, blindfolded](https://user-images.githubusercontent.com/109529281/185724583-75e7acce-90d7-4aba-859e-689ad4c011ac.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: d060cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots]
]

**Comment by descan** [comment]
The same behavior occurs if you wear a blindfold on a security camera display tile.
