### ISSUE TITLE
Using the unload zone on ammo belts destroys the linkages.

### ISSUE THREAD

**Issue by Kiael** [CleverRaven/Cataclysm-DDA#60310]
### Describe the bug

If you create an unload zone on a tile within a vehicle and place an ammo belt onto it and then unload them using the zone interface, the linkages disappear but the ammunition is correctly removed from the belt and sorted.

### Steps to reproduce

1. Create a loot zone on a cargo space or other vehicle container for unloading.
2. Place an ammo belt onto the space.
3. Unload the ammunition.
4. The linkages dissapear.

### Expected behavior

The linkages should still exist.

### Screenshots

N/A

### Versions and configuration

07d8e66

### Additional context

none

**Comment by GuardianDll** [comment]
/confirmed, but its not related to vehicle, you can't get a linkage even if you unload on the ground
![image](https://user-images.githubusercontent.com/67688115/185707277-33ccbff2-78f6-4d41-a071-551284fb18fb.png)
also the player left with perfect `0/500` `0` g `0` ml ammo belt, which is also wrong

**Comment by Kiael** [comment]
> /confirmed, but its not related to vehicle, you can't get a linkage even if you unload on the ground ![image](https://user-images.githubusercontent.com/67688115/185707277-33ccbff2-78f6-4d41-a071-551284fb18fb.png) also the player left with perfect `0/500` `0` g `0` ml ammo belt, which is also wrong

My bad, I should have tested it more before making an issue. If it helps with sorting the issue in the tracker I edited the name to more accurately reflect the problem.

**Comment by I-am-Erk** [comment]
Ugh we probably should get a diagnosis on this and see if we can fix it in time

**Comment by RenechCDDA** [comment]
My diagnosis is that this *should* be straightforward, provided you can unravel the mess of pointers that lies in the unloading zone code.

Basically, we take the linkage check from `unload_activity_actor::unload` (the player manually unloading)

https://github.com/CleverRaven/Cataclysm-DDA/blob/57c865ece207986decd6db4ccb403e14a15fad5a/src/activity_actor.cpp#L2929-L2936

...and slap it into `activity_on_turn_move_loot` (zone unloading), somewhere below line 2276 or so.

https://github.com/CleverRaven/Cataclysm-DDA/blob/695709056140a0aad40689dd52d244627fe8687c/src/activity_item_handling.cpp#L2276-L2282

They're both performing the same action, we just need to make the operations consistent between them.

**Comment by mqrause** [comment]
That's an appropriate fix for stable, but a real fix would be to make unload zones actually unload items using unload activities and then move, and not just move the contents somewhere else. These zone activities need a major refactor anyway.
