### ISSUE TITLE
Vehicles with charge between 2164704 kJ and 2162516 kJ in batteries cannot fire energy weapons

### ISSUE THREAD

**Issue by DPavonis** [CleverRaven/Cataclysm-DDA#60315]
### Describe the bug

Attempting to fire mounted weapons that take battery as their ammo type on a vehicle with more than 2,162,516 kJ, but less than 2,164,704 kJ in its batteries results in being unable to fire.

### Steps to reproduce

1.) Have a vehicle with sufficient battery capacity, 22 very large storage batteries will suffice, alongside a mounted energy weapon.
2.) Have more than 2,162,516 kJ, but less than 2,164,704 kJ in the vehicle's batteries.
3.) Attempt to fire.
4.) Receive error message: "Can't aim turrets: all turrets are offline or set to manual targeting mode."

### Expected behavior

Vehicle-mounted energy weapons should be able to fire when charge level is between 2164704 kJ and 2162516 kJ in their batteries.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 326fae6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Attached is a save with a demonstrator vehicle already built
[2162516kJ_bug_test_rig_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9387926/2162516kJ_bug_test_rig_2.zip)

**Comment by irwiss** [comment]
Can't replicate this, I loaded your save - the vehicle has no battery charge so the turrets can't fire
Debug menu charge to 2000kJ - turret can now fire
Debug menu charge to ~2170000kJ - turret can still fire
Debug menu charge to 2200000kJ - turret can still fire

**Comment by DPavonis** [comment]
> Can't replicate this, I loaded your save - the vehicle has no battery charge so the turrets can't fire Debug menu charge to 2000kJ - turret can now fire Debug menu charge to ~2170000kJ - turret can still fire Debug menu charge to 2200000kJ - turret can still fire

After further testing, it turns out the bug only manifests itself in the range { x | 2164704 > x > 2162516 }

Will be amending reproduction instructions accordingly. Save attached actually demonstrates the bug. 

[2162516kJ_bug_test_rig_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9387926/2162516kJ_bug_test_rig_2.zip)
