### ISSUE TITLE
[Magiclysm] Harvesting horn moss leaves behind invalid terrain

### ISSUE THREAD

**Issue by Ambrux** [CleverRaven/Cataclysm-DDA#60339]
### Describe the bug

Swamps have a horn moss terrain that can be harvested for horn moss capsules. Once harvested, it leaves behind a "nothing" terrain that is impassible.

I believe the bug is due to:
`mods\Magiclysm\furniture_and_terrain\furniture_plants.json`
```json
  {
    "type": "terrain",
    "id": "t_horn_moss",
    "name": "horn moss",
    "looks_like": "t_grass",
    "description": "A cluster of red moss, so called for the white capsules that it will grow during spring.",
    "symbol": ".",
    "color": "light_red",
    "move_cost": 2,
    "examine_action": "harvest_ter_nectar",
    "flags": [ "TRANSPARENT", "DIGGABLE", "FLAT" ],
    "harvest_by_season": [ { "seasons": [ "spring" ], "id": "horn_moss_harv" } ]
  },
```
missing a transforms_into field as seen in:
`json\furniture_and_terrain\terrain-flora.json`
```json
{
    "type": "terrain",
    "id": "t_tree_basswood",
    "name": "basswood tree",
    "looks_like": "t_tree",
    "description": "The American linden.  It has pretty and sweet-smelling flowers in the Summer and you might be able to eat its young leaves in Spring.",
    "symbol": "7",
    "color": [ "green", "green", "green", "brown" ],
    "move_cost": 0,
    "coverage": 80,
    "examine_action": "harvest_ter_nectar",
    "transforms_into": "t_tree_basswood_harvested",
    "harvest_by_season": [ { "seasons": [ "spring" ], "id": "young_leaves_harv" } ],
    "flags": [ "FLAMMABLE_ASH", "NOITEM", "SUPPORTS_ROOF", "TREE", "REDUCE_SCENT" ],
    "bash": {
      "str_min": 80,
      "str_max": 180,
      "sound": "crunch!",
      "sound_fail": "whack!",
      "ter_set": "t_dirt",
      "items": [
        { "item": "stick_long", "count": [ 3, 10 ] },
        { "item": "splinter", "count": [ 10, 25 ] },
        { "item": "leaves", "count": [ 50, 150 ] }
      ]
    }
  },
```

### Steps to reproduce

1. Approach horn moss, e.g. in a swamp.
2. Harvest via interaction.
3. Observe that a nothing tile is left behind.

### Expected behavior

Once harvested, horn moss would transform into some other terrain. Perhaps dirt, or some intermediary (like trees) that eventually regenerate the plant.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0.F-10776-g630e438b9b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Miscellaneous Additions [ext_misc],
    Magiclysm [magiclysm],
    Arcana and Magic Items [Arcana],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Marcos6226** [comment]
#60204 is going to fix it, but we will have to wait until it gets merged.

**Comment by Ambrux** [comment]
Understood. Thanks for your reply, I missed the PR that addressed it.

**Comment by NetSysFire** [comment]
For the record, those PRs usually include a closing keyword, so the issue will be automagically closed when said PR is merged
