### ISSUE TITLE
We have alerts for being spotted or interrupted.  What about an alert for making too much noise?

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60348]
### Is your feature request related to a problem? Please describe.

So, currently, it's very easy to screw up playing a stealth character in C:DDA.  Cleaning a broken window, prying a door, talking to an npc, shooting a gun, disassembling a glass jar, what noise level will you make next?

### Solution you would like.

Wouldn't it be nice to get a popup saying 'You are about to make noise higher than '%x', do you want to continue?  Where %x is some user-settable value.

### Describe alternatives you have considered.

It doesn't necessarily need to track all noises, maybe have it happen only in 'crouch'/'prone' stance, or a stealth toggle.

**Comment by brassmaster2357** [comment]
This is a good idea, although I think it would be more fitting to be added once a larger update/change to stealth and sneaking is added, like non-360 degree vision.
