### ISSUE TITLE
New portal storm monster inflicts 3 months of deafen.

### ISSUE THREAD

**Issue by Pyramidekopf** [CleverRaven/Cataclysm-DDA#60340]
### Describe the bug

New portal storm monster's attack seems to have deafened me for ~3 months.
![notepad_2RUj16WbPz](https://user-images.githubusercontent.com/111657777/185764475-1f30bff8-2e50-42e6-ab66-7edda2d12f65.png)

There are 13 different "deaf" effects in there that look like this:
![notepad_cFWzVaH3ZP](https://user-images.githubusercontent.com/111657777/185764579-092004c0-376e-4b84-a43a-36389c89632f.png)

Not entirely sure if something else around was also trying to deafen me or not, there was a prison fire close by.

### Steps to reproduce

Get attacked by the "A Person" portal storm creature.

### Expected behavior

I'm not entirely sure, I didn't write the creature but it seems like it unintentionally stacked or something.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0ba9a3a [64-bit]
- Graphics Version: Tiles
- Game Language: System language 
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Original Drug Names [OG_Drugs],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills]

### Additional context

[South NorthHaven.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9387876/South.NorthHaven.zip)
Just gonna throw the whole save file in here just in case.

**Comment by Pieman492** [comment]
This should have been fixed by #60270, a few versions after the one in the report.
