### ISSUE TITLE
Destroying an automatically-deployed long rope that was used to safely climb down wooden stairs with a destroyed lower section creates 4 grip hooks

### ISSUE THREAD

**Issue by HardcastFlare** [CleverRaven/Cataclysm-DDA#60366]
### Describe the bug

When descending a wooden staircase to a tile with no staircase on the lower z-level (e.g. because the lower staircase was destroyed by monsters), the game will automatically prompt you to use a rope-type item from your inventory to safely descend. If you have a long rope, this will result in a climbable rope tile being deployed where the lower staircase should be.

Destroying this climbable rope tile (by smashing or otherwise) results in the rope being dropped, along with 4 grip hooks.

### Steps to reproduce

Obtain a long rope.
Find or create a location where z-levels can be crossed using a pair of linked wooden staircases.
Destroy the lower staircase.
Return to the upper staircase.
Attempt to descend the upper staircase. The game should prompt you to deploy the long rope to safely descend.
Descend the staircase using the rope.
Destroy the resulting rope tile created on the lower z-level.

### Expected behavior

When destroyed, the rope tile should, at best, return only the items used to deploy it.

### Versions and configuration

Game version: 0.F-630e438-Tiles, build 2022-08-20-1255
Only default mods loaded

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: cee383c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Destroying the `grappling hook` furniture (called `rope leading up` in 2020) dismantles it into what it was created from: 4 grip hooks and a rope: https://github.com/CleverRaven/Cataclysm-DDA/blob/5762e894932f7cde1212de1db7102bcedaa00591/data/json/recipes/recipe_others.json#L1686
That's not 4 grappling hooks, that's 4 grip hooks. So it's working as intended.
