### ISSUE TITLE
"Focused Beam Death" Death effect for milspec searchlight doesn't work

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#60376]
### Describe the bug

according to the monster_death.json and what some people on discord has said, the milspec searchlight should have blind the player on death, but it didn't happen. 

### Steps to reproduce

1. Make a new world
2. Spawn a milspec searchlight
3. Kill it
4. Not get blinded

### Expected behavior

The death function to work properly

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: a2991c7 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Dynamitesound [dynamite_sound],
    Stats Through Kills [stats_through_kills]
]

**Comment by Venera3** [comment]
Their death spell uses a `line` shape to spawn dazzling fields, but targets its own position. Either changing it to a blast or adding a range and `RANDOM_TARGET` to it should fix it.

**Comment by Marcos6226** [comment]
> Their death spell uses a `line` shape to spawn dazzling fields, but targets its own position. Either changing it to a blast or adding a range and `RANDOM_TARGET` to it should fix it.

What if I changed it to `blast` and added the `"min_range": 48` and `"max_range": 48` lines? because I did it and it worked perfectly.
Now the question is, what value should the range be?

**Comment by Venera3** [comment]
I'd say a 2-tile AoE blast sounds reasonable. You're not blinding anybody at range, but it should affect melee enemies.
