### ISSUE TITLE
Blacklist/de-prioritize map tiles for auto-travel

### ISSUE THREAD

**Issue by SamuelFoster** [CleverRaven/Cataclysm-DDA#60374]
### Is your feature request related to a problem? Please describe.

Auto-travel often takes paths that are inconvenient or dangerous. For example, auto-drive likes to stick to roads, which often means driving straight through a zombie-filled town. It also can choose paths that go right next to dangers like wasp nests, or straight into craters.

### Solution you would like.

I think an option to blacklist or de-prioritize map tiles for auto-travel pathing would allow the player to easily avoid known hazards and streamline long trips. [Edit] Ideally something as convenient as 'E' to mark a tile as explored, which would allow drawing a border around an area to avoid.

### Describe alternatives you have considered.

[Edit] Being able to mark a note as dangerous from the overmap (similarly to 'N' or 'D' to edit or delete a note) would make the existing functionality for avoiding a location while auto-traveling more obvious and accessible to newer players.

**Comment by descan** [comment]
Part of this is something you can do in the game - you can set a note as Dangerous in the Notes List on the overmap, which comes with a chosen radius of avoidance for auto-move. I've put in a suggestion about exposing this system to the player some more, and it doesn't quite do everything I think you're asking (it would be difficult, time consuming, and annoying to use the Dangerous Note system to make your auto-move de-prioritize roads, for example), but you can use it to mark certain areas as hazardous and to avoid driving through them.

That being said, having a list of things you could tell Auto-Move to prioritize/de-prioritize would still be welcome. "Use Roads/Don't care about Roads/Avoid Roads," "Don't go near X Y Z buildings/cities in general," "maximize gas and power efficiency/minimize time/minimize distance traveled" etc, etc.

**Comment by SamuelFoster** [comment]
I wasn't aware of the "mark as dangerous" feature in the notes list. I think marking as dangerous lets me accomplish avoiding dangerous areas with auto travel, but it wasn't obvious that this feature existed. Being able to mark a note as dangerous from the overmap (similar to deleting or editing a note) would make this more visible, as well as more convenient, in my opinion.

In my suggestion, I was envisioning a feature as convenient as "Toggle explored", which would make it easy to draw a border around a dangerous area, but this could be redundant with existing functionality.

**Comment by descan** [comment]
Yeah, it's the lack of obviousness that the feature existed that was what my suggestion was about, when I posted it.
