### ISSUE TITLE
Hang while sleeping

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#60371]
### Describe the bug

This save consistently hangs if you sleep immediately after loading.

[Bear Creek.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9391499/Bear.Creek.zip)

### Steps to reproduce

1. Load save
2. Immediately sleep

The game will hang after a few seconds, becoming nonresponsive.

### Expected behavior

The game shouldn't hang.

### Versions and configuration

Experimental - 630e438

**Comment by Golfavel** [comment]
Cannot reproduce with build 0cfdc59 Linux tiles, software rendering.

**Comment by nornagon** [comment]
Hm, this reproduced for me three times over on Windows tiles.

**Comment by Farseer2** [comment]
Cannot reproduce on Windows tiles 8abc45f7529939ca102988c770f6f4a872446524
