### ISSUE TITLE
Can't make peanut butter sandwich in tutorial because of freezing

### ISSUE THREAD

**Issue by pali6** [CleverRaven/Cataclysm-DDA#60383]
### Describe the bug

One step of the in-game tutorial tells you to make a peanut butter sandwich. However, by the time you get to that step the peanut butter freezes and as such is unsuitable for peanut butter sandwich purposes.

### Steps to reproduce

1. Start the tutorial and proceed until the food/hunger part
2. Open crafting menu
3. Observe how peanut butter sandwich is not craftable and the peanut butter on the counter is frozen

### Expected behavior

Either the tutorial should give you means to unfreeze the peanut butter and tell you to do that, or the peanut butter should be resistant to freezing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: f0d7703 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I am sorry. I have tried to replicate this situation, but failed. Could you please upload a save file of the tutorial world, where this occurred?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: f0d7703 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by pali6** [comment]
I haven't thought of saving the tutorial world when it originally occurred. When trying to replicate the issue I am also failing at the moment. Could be that it depends on some rare particulars of the tutorial world generation (such as cold weather).

**Comment by Night-Pryanik** [comment]
I can confirm this on 0.F-10912.
![изображение](https://user-images.githubusercontent.com/11132525/187072413-74d1dd02-ee3f-4918-9bb3-e6a853ee6571.png)
That's really strange because temperature is 11C, which shouldn't make things freeze.

**Comment by StalwartTirith** [comment]
Happened to me as well.

**Comment by Brodacious** [comment]
Can confirm, happened to me as well. Thought I had to disassemble the jar and ended up with glass shards and dirty peanut butter lol

**Comment by Brodacious** [comment]
[TUTORIAL.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9843615/TUTORIAL.zip)

**Comment by Brodacious** [comment]
Here's my saved version, the drugs for pain relief were also frozen, and the peanut butter was over by the glass shards on the ground.
[TUTORIAL.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9843624/TUTORIAL.zip)
