### ISSUE TITLE
Teamster should have a rumour for finding the Aircraft Carrier

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#60384]
### Is your feature request related to a problem? Please describe.

With the recent changes to make the Aircraft Carrier globally unique, they've become extremely difficult to find. 

### Solution you would like.

Asking the Teamster for rumours should have a chance of giving a rumour-mission towards the aircraft carrier. Given the... oddness of an aircraft carrier just suddenly being dumped into a lake in the middle of New England, I feel like there likely *would* be rumours about such a weird event, even in the middle of the weirdness of the cataclysm (if only because "hey there might be FOOD and GUNS on board!").

### Describe alternatives you have considered.

I wouldn't want to bloat the Teamster rumours so that there's a dozen and a hundred different rumours you could get from them, so maybe multiple different rumour-types might work? One set of "Heard of anything just... plain weird?" for locations, and another set of "Hey, have you heard of any possible survivors?" for NPC bases, so that one could ask about Interesting Locations without losing out for a week+ on potential NPC locations, if you haven't managed to find the Exodii, Hub, Isherwoods, or Artisans yet.

### Additional context

Unless and until there are actual missions tied into the aircraft carrier which could guide a player to the location, a rumour-based mission might be the best way to make sure it's not lost in the shuffle for players who want to delve into it, now that it's become a unique location.

**Comment by Michael1993** [comment]
It would make a lot more sense for the Old Guard Representative to guide the player to the aircraft carrier, in my opinion. Could be a "check that place out" like with the "find the source of robots" quest.

**Comment by descan** [comment]
Either would work IMHO, I'm not married to the Teamster (even if they are kinda cute).

**Comment by vicbrandao92** [comment]
Agreed. Are you working on something to implement this? If not, where should I first look to start doing it? Considering I have very limited experience in coding that is.

**Comment by descan** [comment]
> Agreed. Are you working on something to implement this? If not, where should I first look to start doing it? Considering I have very limited experience in coding that is.

I have 0 coding experience, and would have no idea how to implement it. I guess that answers both your questions, at least from me. :P 

I guess looking at how the other Teamster/Old Guard missions for finding a location work, and trying to emulate them? That's all I got.

**Comment by vicbrandao92** [comment]
Do you know who would be responsible for accepting or refusing the merge? I might take a shot at it, always good to learn something new.

**Comment by descan** [comment]
> Do you know who would be responsible for accepting or refusing the merge? I might take a shot

The automated bots (with oversight) would be responsible for making sure the code doesn't break. A couple of the moderators would be responsible for making sure it doesn't break lore. Beyond that, the project tends to have a very permissive attitude towards merging - as long as it doesn't break something or go (directly) against established lore/norms or the lore design doc, it would most likely get merged.

**Comment by anothersimulacrum** [comment]
To put it another way, the project is such that an awful lot of things fit. It is very reasonable there is some form of knowledge in the world about this anomalous aircraft carrier being here, and changes reflecting that are welcome, though I am not in a position to tell you this specific change has no problems.
