### ISSUE TITLE
Monster 'Person' (mon_hallucinator), interactions with NPCs, and lag.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60389]
### Is your feature request related to a problem? Please describe.

Currently, the clairvoyance of 'Person' is visible to NPCs, which, if you don't instantly remember to change their state, will cause them to react poorly to portal storms.  

This, in addition to the player having interruptions (even if they are ignored), this much more frequently has lead to portal storms taking quite a bit longer to wait out.  Guesstimating five times longer or so?  (I'm mid-late game, about 150 days in.)

My latest portal storm I had 9 Person monsters walking around, so I ended up with a log full of an NPC shouting causing the portal storm to lag me out even more than it usually does.  I ended up disabling their ability to go through doors as otherwise it'd have been an end of run for me, as my vehicle has more than two entry doors, that they kept on opening.  Add to this the clairvoyance bubbles, which highlight 20 tiles around them, and the player themselves has to do dangerous things with 'ignore all x' stuff that's easy to forget you've disabled.

### Solution you would like.

There's a few issues here.

No re-enabling of 'ignore x', similar as to safe mode.  Forgetting to re-enable the distractions manager 'Hostile Spotted' or 'Noise' is a quick way to have YASD, but it's super easy to forget to re-enable it.

NPC vs non NPC mechanics.  Them yelling about your hallucinations is odd, perhaps they should have their own?

NPC portal state rules automatic switch?  Make it based on actually having good social skills?

I've got no idea.  This isn't really a bug, it feels very intended, but it's kind of means I've got no idea how to keep up basecamps, or mobile bases anymore.  Are we moving away from both of those?  Even trying to drive away from portal storms, you take damage from running into monsters which doesn't do good things to them.

### Additional context

![image](https://user-images.githubusercontent.com/22281606/186066218-323dd300-0878-45c1-bae2-bf67bc7dea04.png)

**Comment by GuardianDll** [comment]
Okay, the fact it spawns nine times while the storm is not really good, it was designed as rare monster. To fix this part someone need to add variable, when monster spawns, and check this variable for the next attempts - so only one per storm can be spawned (or drastically increace probabilities to spawn another monsters, dunno which is better)
NPC interaction is... tricky. 
The original method to deal with them is board up doors and windows in room, so they can't open them, but its kinda hard to do with vehicle
