### ISSUE TITLE
Game overrides some modded json objects?

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#60381]
### Describe the bug

The game seems to override some modded objects with vanilla values: for example, I can mod "suppressor" fine, but changes to "riv_suppressor" don't show up in game.

### Steps to reproduce

1. Create an empty mod.
2. Copy data\json\items\gunmod\muzzle.json into new mod.
3. Edit some values of "suppressor" and "riv_suppressor" in a mod file.
4. Ceate a world with the new mod at the end of the load order list, create a character.
5. Search for suppressors in debug spawn menu, look at the values.

### Expected behavior

Modded values for both objects should show up. If there was a load order problem, both objects would be overriden with vanilla values.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.30 (1903)
- Game Version: 593e21a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    zPersonal Mod [zPersonal]
]

**Comment by ZhilkinSerg** [comment]
If you already have the mod that fails to work properly - upload it here.

**Comment by Nandorianen** [comment]
[Test Mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9397045/Test.Mod.zip)
Here's an example. Suppressor should have -111 loudness and riv_suppressor -333. However, in my game riv_suppressor shows -222, which is vanilla x2 of the modded version of copied-from suppressor.

**Comment by ZhilkinSerg** [comment]
You need to copy-from original item `riv_suppressor` in your mod:

```JSON
  {
    "id": "riv_suppressor",
    "copy-from": "riv_suppressor",
    "type": "GUNMOD",
    "name": { "str": "RK6S34 suppressor" },
    "description": "A suppressor reduces the amount of noise and muzzle flash generated by the report of a firearm.  This RK6S34 Mustela is a rather advanced version integral to the RM11B rifle system.",
    "weight": "0 g",
    "volume": "0 ml",
    "price": 0,
    "price_postapoc": 1500,
    "install_time": "0 s",
    "material": [ "superalloy", "ceramic" ],
    "mod_targets": [ "rifle" ],
    "handling_modifier": 0,
    "loudness_modifier": -333,
    "flags": [ "IRREMOVABLE" ]
  }
```

Then it should be inherited properly:

![image](https://user-images.githubusercontent.com/16213433/186008401-9ffc7f43-5cbf-4d5d-bac4-ad3bbbb295c1.png)

**Comment by Nandorianen** [comment]
Hmm. That works, thanks. However, I do not think it works entirely as designed.
1. I can mod "suppressor" fine straight out of the box, no copy-from needed.
2. I can insert copy-from line to "suppressor" and it will target vanilla data, but it will work.
3. I can't mod "riv_suppressor" at all unless I use copy-from itself.
So the game handles items that had "copy-from" line in vanilla differently from those that didn't. Why?

Also it was working universally fine (with any object) last time I played (0.E b11128). Was this part of code intentionally changed to work like this?

**Comment by ZhilkinSerg** [comment]
If you mod some item, you need to copy-from this item.

**Comment by Nandorianen** [comment]
I don't need any copy-from to mod "suppressor". But I need it to mod "riv_suppressor".
That's inconsistency. Which one is the desired behavior? Based on how it previously worked, based on how this is not covered by documentation at all, I would say that "suppressor" behaviour is the intended one, while "riv_suppressor" is a bug.

**Comment by ZhilkinSerg** [comment]
If you mod some item, you need to copy-from this item.

**Comment by Nandorianen** [comment]
If it is intended to work like that, maybe it should be documented? I wouldn't have guessed how to make it work myself, and I don't think I'm the only one.
Actually, there isn't _any_ info on editing existing objects in MODDING.md.
