### ISSUE TITLE
Port changes from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1610

### ISSUE THREAD

**Issue by sonphantrung** [CleverRaven/Cataclysm-DDA#60399]
### Is your feature request related to a problem? Please describe.

The solution to vehicle gaps presented in [BN](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1610), apparently doesn't use fake parts, which is an advantage compared to DDA's fake parts implementation.

### Solution you would like.

Port the change, we have done ports from BN to DDA before (Unlimited map memory for example)

### Describe alternatives you have considered.

Not porting this, and receiving complains from players, and eventually receiving "dev man bad" accusations (That would sucks)

### Additional context

This [Reddit post](https://www.reddit.com/r/cataclysmdda/comments/wvmgf7/is_there_a_way_to_disable_fake_vehicle_parts/) brought me up about this feature request

**Comment by Fris0uman** [comment]
Pretty sure that if you read the history behind that issue you'll find that this solution has already been rejected  https://github.com/CleverRaven/Cataclysm-DDA/issues/5684

**Comment by ZhilkinSerg** [comment]
No.
