### ISSUE TITLE
offset iron sights don't do anything

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#60398]
### Describe the bug

Offset iron sights have no effect

They need to be moved from faux irons to the new sight system with FOV

### Steps to reproduce

Spawn M4
Spawn Offset Irons
Spawn ACOG
Add ACOG
Add Irons
Note the stats don't change

### Expected behavior

Should so something. 

### Versions and configuration

Build as of Tuesday August 22nd

**Comment by GuardianDll** [comment]
my stats has changes
![image](https://user-images.githubusercontent.com/67688115/186219064-cc93615d-cf17-4b05-984f-8752ca947deb.png)

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 262a6eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA]
]

**Comment by catdach** [comment]
> They need to be moved from faux irons to the new sight system with FOV

the "offset iron sights" inherits most of its stats from the base "iron sights" gunmod. Including FOV: 
<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/93795131/186263149-0afbaa01-0870-49c0-baad-5bff89b76d14.png)
</details>
adding "offset iron sights" will slightly change the aim speeds of the gun, unless you have pretty high levels in marksmanship  and the relevant gun skill. 
 
<details><summary>for example here's with rifle 5 and markmanship 5:</summary>

![image](https://user-images.githubusercontent.com/93795131/186263987-3284aed5-1d3b-4b76-81f9-2e33ba992a17.png)
</details>
<details><summary>and here's with rifle 6 and markmanship 5:</summary>

![image](https://user-images.githubusercontent.com/93795131/186264272-67c76b34-42b9-4a20-a53f-c334dfd06146.png)
</details>

**Comment by bombasticSlacks** [comment]
ahhh I checked it on my non debug character, I'm closing this.
