### ISSUE TITLE
mutant armors cause unconfortable gear morale penalty

### ISSUE THREAD

**Issue by n0pen** [CleverRaven/Cataclysm-DDA#60409]
### Describe the bug

If you get an aura armor (mutant skin armor) it will count as covering body parts when calculating "uncomfortable gear" penalty

### Steps to reproduce

1. Get nude and mutate into plant and verdant leaves or flowering
2. The game will give you phelloderm
3. Check morale to see -10 uncomfortable gear penalty
4. Remove mutation phelloderm and see the penalty vanish
5. Repeat for other armors (carapace)

### Expected behavior

Mutated skin/aura armors shouldn't constraint other mutations, even less when they are on the same mutation tree

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-10826-g01204a9016-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The morale penalty from this issue is result of having specific mutations that want to be exposed to the air/environment and it's not related to aura penalties

**Comment by Maleclypse** [comment]
To clarify from discord auras shouldn't interfere with other armors/skins but skins should definitely be able to interfere with other armors, in my opinion. I think you are saying the same thing but I wanted to confirm.

**Comment by n0pen** [comment]
This issue is not related to the armor item itself, but the fact that having an aura armor interferes with other non-armor mutations that want to be exposed. The aura armor has its armor properties as it should, but why having phelloderm skin counts as obstructing Flowering (flowers in your head). It's only related to morale calculations for this issue in particular
