### ISSUE TITLE
Hang your flag upon the wall

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#60405]
### Is your feature request related to a problem? Please describe.

We have a lot of interesting flags that can be worn or dropped on the ground but not hung on walls and windows. That is because it ranges from impossible to incredibly annoying to make a different furniture item for every variant flag.

### Solution you would like.

Our sprite system allows contextual changes to sprites, showing a different sprite for an item if it's on a certain tile. However, we can't place items on walls and windows because they have the NOITEM flag.

To my knowledge last I checked, terrain with the NOITEM flag can still have an item on it if we place it there by other means though!

I suggest an iuse action for flags, and for other things that might hang on a wall, that basically just lets you drop the item on a terrain with the WALL, WINDOW, or DOOR flag.

This gives us the workflow:
1. Get flag/poster/whatever
2. Activate item - "Hang up poster" or "hang up flag"
3. Select nearby terrain with flag WALL
4. Item is dropped there
5. Tileset's contextual item sprite shows a flag or poster hanging on said wall.

Ideally, there might also be some error checking here that only allows you to do this on horizontal walls, in the North direction, since the sprite won't work easily on vertical walls and if you place it on a wall to your South it will appear you passed it through the wall. As it stands this will also let you pick the item up from the other side of the wall, but that seems like a minor bug. Potentially we could work around that if it bothers people, by not letting you pick up items from wall tiles except from the south side.

### Describe alternatives you have considered.

We could have a whole new way of deploying items to create a new type of furniture that supports variants.

### Additional context

This is not something we need but it would be real fun.

**Comment by rty275** [comment]
If you were to hang a flag up over a window, should it block sight? I dunno how possible that is with plain items on a spot, it'd probably be getting into more complex waters, but I imagine you could use a flag like an impromptu curtain for windows or other privacy curtain related needs.

Granted, maybe that's just a reason to add flags to the possible construction components for those things, but if it could then somehow inherit the image of the flag when the curtains are drawn, that would be incredibly cool. Also probably *far* more complicated than your proposed solution, but it'd be a nice added feature and potentially groundwork for other future things?
