### ISSUE TITLE
Vegetable cleaver is slightly better than the meat cleaver, despite it’s description saying the contrary.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#60404]
### Describe the bug

As may be seen within these two screenshots, the vegetable cleaver is not worse in any personally noticeable way than the meat cleaver, despite the former’s description stating that it makes for an inferior weapon. Indeed, as far as I can tell the humble veg cleaver is actually better than the meat cleaver, as its more compact, lighter, and is quicker.
![Screenshot at 2022-08-23 19-19-09](https://user-images.githubusercontent.com/102766473/186226995-2d718ed5-356f-46aa-aec1-36a6e746b63c.png)
![Screenshot at 2022-08-23 19-19-52](https://user-images.githubusercontent.com/102766473/186227003-d81be116-1e22-475e-947c-fdd1cc7c02ea.png)

### Steps to reproduce

1. create a character that starts in a city.
2. hunt around for a meat and vegetable cleaver.
3. directly compare the two and see that, indeed, the vegetable cleaver is not worse than it's meat oriented big brother.

### Expected behavior

I expected that the vegetable cleaver is worse than the meat cleaver, and that it’s description isn’t lying to me.

### Versions and configuration

OS: Ubuntu 18.04
- Game Version: 8372ed1
- Graphics version: curses
- Ingame language: English
- Mods loaded: dda, no_npc_food, no_fungal_growth, aftershock, blazeindustries, secronom, secronom_lore_expansion, xedra_evolved, alt_map_key, MMA, Tamable_Wildlife, speedydex, StatsThroughSkills

**Comment by ANickelN** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/59599
It was lowered here on request from AnotherSimulacrum.  The damage could either be very slight increased, the damage of the vegetable cleaver lowered, or the description changed.

**Comment by Marcos6226** [comment]
> The damage could either be very slight increased...

I vote for the damage to be slightly increased, based on the fact that it's is bigger and heavier than the vegetable one.

**Comment by anoobindisguise** [comment]
> > The damage could either be very slight increased...
> 
> I vote for the damage to be slightly increased, based on the fact that it's is bigger and heavier than the vegetable one.

Likewise, meat cleavers can chop through bone pretty easily. It's easy to lose a finger by accident.

**Comment by Marcos6226** [comment]
> It's easy to lose a finger by accident, much more so than other knives which might be more likely to just mangle your finger rather than chop it clean off.

Exactly! All arguments lead to the same conclusion: the meat cleaver is more dangerous than the vegetable one.

**Comment by DoctorBoomstick** [comment]
Well folks, it looks like we’re all reaching the same conclusion here, and personally it would make more sense to buff the meat cleaver than nerf the vegetable cleaver. The only question is, if it was originally debuffed cause it was too strong, how much added damage makes sense to bring it up? Personally I think it’d be a fine middle ground to drop the vegetable cleaver by a couple cutting points, and buff the meat version by two or three points of damage, though I’m relatively crap at balancing stuff, so really, idk on this one.

**Comment by Marcos6226** [comment]
I would balance this way
```
Vegetable Cleaver
bash: 3  cut: 14 

Meat Cleaver
bash: 5 cut: 16
```
This way we have noticeable difference between them, and you get slightly more damage at the cost of needing more time to swing.

**Comment by anoobindisguise** [comment]
Those numbers are probably too low, use the following for reference:
carving knife: 1 bash, 18 pierce
butcher knife: 2 bash, 14 pierce
chef knife: 2 bash, 16 pierce

**Comment by Marcos6226** [comment]
>Those numbers are probably a little on the low side[...]

I think you are right. And after reading this [article](https://knivesacademy.com/meat-cleavers-vs-vegetable-cleavers) I have noticed that the vegetable one should have more cut and less bash, and the meat one more bash and less cut. So I decided to edit my suggestion.
