### ISSUE TITLE
None of the courtyard wall descriptions have end periods

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#60427]
### Is your feature request related to a problem? Please describe.

While translating I realized none of the courtyard wall upgrade descriptions for modular field camps have periods at the end of them, which is against the trend of camp upgrades having periods at the end of their descriptions (periods are important, that's why every sentence in my issue has one to finish it).

### Solution you would like.

Adding periods to every single upgrade description, if others I've not seen get fixed too, all will be good.

### Describe alternatives you have considered.

Keep this absolutely unplayable grammatical/syntaxial typo in the game, I mean this isn't content that absolutely every player sees, notices, or even cares about, but still.

**Comment by PatrikLundell** [comment]
Acshually, it's "syntactical".

(Sorry, couldn't resist)
