### ISSUE TITLE
submit to flathub 

### ISSUE THREAD

**Issue by trkgopher** [CleverRaven/Cataclysm-DDA#60429]
### Is your feature request related to a problem? Please describe.

I can't install the raw code without disabling the immutable file system built into my iOS, which means the code gets wiped every time I update the OS. 

### Solution you would like.

Would dearly like to be able to download as a flat pack but needs to be submitted to flat hub. 

### Additional context

Some Linux OS with immutable file systems don't like non-flat pack installations. Specifically in my case the Steam OS factory installed on the steam deck.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/33682

**Comment by ZhilkinSerg** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/33682
