### ISSUE TITLE
Oven appliance doesn't provide oven quality

### ISSUE THREAD

**Issue by jiornojiovanni** [CleverRaven/Cataclysm-DDA#60434]
### Describe the bug

I have an oven appliance installed, but when I try to cook something requiring an oven I don't have the quality.

### Steps to reproduce

1. Install oven
2. Try to craft something requiring oven quality

### Expected behavior

I should be able to use the oven. In the screenshot attached you can see that is it correctly connected as I can use it for cooking.

### Screenshots

![immagine](https://user-images.githubusercontent.com/31773561/186655257-71d0874b-161d-4de8-a942-4b074de15d1c.png)

![immagine](https://user-images.githubusercontent.com/31773561/186656395-a3eee708-240f-44ce-896e-3747c0fc5265.png)
_I just want to grill for god's sake_

### Versions and configuration

-OS Windows 11
-build 2022-08-25-1016
-mods : "dda",
  "package_bionic_professions",
  "no_npc_food",
  "no_fungal_growth",
  "No_Rail_Stations",
  "translate_dialogue"

**Comment by sonphantrung** [comment]
#60232 has fixed the issue you've listed, please update the game to the newest version

**Comment by ZeroInternalReflection** [comment]
> #60232 has fixed the issue you've listed, please update the game to the newest version

Unfortunately, it would appear that it did not.  I had specifically checked whether it provided hotplate charges, but missed checking the oven quality.

Replacing the "pseudo_app_oven_hotplate" entry in data/json/items/fake.json with this:
```
  {
    "copy-from": "pseudo_hotplate_abstract",
    "id": "pseudo_app_oven_hotplate",
    "type": "TOOL",
    "qualities": [ [ "OVEN", 2 ] ],
    "name": { "str": "oven" }
  },
```

Will add the quality back.  I'll be doing a bit more testing, then submitting a PR.

I believe that the oven appliance will be the only one affected by this, since the RV kitchen unit has a hotplate and pot rather than an oven.

**Comment by jiornojiovanni** [comment]
> > #60232 has fixed the issue you've listed, please update the game to the newest version
> 
> Unfortunately, it would appear that it did not. I had specifically checked whether it provided hotplate charges, but missed checking the oven quality.
> 
> Replacing the "pseudo_app_oven_hotplate" entry in data/json/items/fake.json with this:
> 
> ```
>   {
>     "copy-from": "pseudo_hotplate_abstract",
>     "id": "pseudo_app_oven_hotplate",
>     "type": "TOOL",
>     "qualities": [ [ "OVEN", 2 ] ],
>     "name": { "str": "oven" }
>   },
> ```
> 
> Will add the quality back. I'll be doing a bit more testing, then submitting a PR.
> 
> I believe that the oven appliance will be the only one affected by this, since the RV kitchen unit has a hotplate and pot rather than an oven.

Tbh I think other appliances also doesn't work, like the router and the drill. I might check later.

**Comment by ZeroInternalReflection** [comment]
> Tbh I think other appliances also doesn't work, like the router and the drill. I might check later.

I was referring specifically to appliances/vehicle parts broken by #56991.  I believe the woodworking appliances have never actually provided qualities (see #56628).  IIRC, there was discussion about wanting to differentiate between fixed and mobile crafting tools.  A drill press is very good at drilling, but if you need to drill a hole in a wall, it doesn't do you much good.
