### ISSUE TITLE
Website link to "Linux Graphical" download is incorrect

### ISSUE THREAD

**Issue by ScottMaclure** [CleverRaven/Cataclysm-DDA#6043]
Current link:
http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/Graphics=Curses,Platform=Linux/lastSuccessfulBuild/

Should be:
http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/Graphics=Tiles,Platform=Linux/

Up and running on my Laptop now :)

**Comment by OzoneH3** [comment]
All links are ok atm on en.cataclysmdda.com
