### ISSUE TITLE
Being blinded with glare protection by milspec searchlight

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60442]
### Describe the bug

The blinding flare of the milspec searchlight doesn't check glare protection. I have both a firefighter PBA mask and the glare protection CBM and still get blinded.

### Steps to reproduce

1. Wear glare protection.
2. Punch milspec searchlight until it dies.
3. go blind.

### Expected behavior

Glare protection should protect from glare. Flashbangs respect it so the milspec should too.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: d2a84e3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Marcos6226** [comment]
The problem may be linked to the fact that their **death spell** spawn **dazzling fields** to blind the player.

**Comment by Marcos6226** [comment]
@Venera3 Sorry for bothering you, but I noticed you were one of the contributors to this file. So I'm wondering if you have any thoughts on this one. Is it a simple fix or it's needed to mess with hard code?

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: e6d3244-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Venera3** [comment]
Whoops, right. The dazzling field will only check for the environmental protection to affect a bp, not any flags. I'll see what I can do, this whole thing could use some more limb-proofing anyway.
