### ISSUE TITLE
Character height doesn't always respect metric/imperial setting

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#60443]
### Describe the bug

On the final screen of the character creation wizard, it's hardcoded to show your height in centimeters.

### Steps to reproduce

1) Configure `Settings->Interface->Distance units' to imperial.
2) Create a new character
3) On the final character creation screen, note that the character's height is 175 (or whatever) cm.
4) After the game starts, press `@' and see that the height is displayed as 5'9".

### Expected behavior

If the distance units are imperial, the height should be displayed as 66 inches or 5'9"

### Versions and configuration

Linux, last commit is 60820c9a4a82778b481ab277020e9d12fd0ea501. Version 0.F-10847-g60820c9a4a.

### Additional context

In-game, the character information screen ('@' menu) shows the character's height correctly- 5'9" or 175cm depending on the metric/imperial setting. But in `newcharacter.cpp:draw_height()', it's hardcoded to say it in centimeters. I would consider fixing this by centralizing the code in something along the lines of Character::height_to_str().

**Comment by ZhilkinSerg** [comment]
```PATCH
diff --git a/src/newcharacter.cpp b/src/newcharacter.cpp
index 35bc3b6bf97..9f56f031846 100644
--- a/src/newcharacter.cpp
+++ b/src/newcharacter.cpp
@@ -3357,8 +3357,7 @@ static void draw_height( const catacurses::window &w_height, const avatar &you,
     werase( w_height );
     mvwprintz( w_height, point_zero, highlight ? COL_SELECT : c_light_gray, _( "Height:" ) );
     unsigned height_pos = 1 + utf8_width( _( "Height:" ) );
-    mvwprintz( w_height, point( height_pos, 0 ), c_white, string_format( "%d cm",
-               you.base_height() ) );
+    mvwprintz( w_height, point( height_pos, 0 ), c_white, you.height_string() );
     wnoutrefresh( w_height );
 }

```

**Comment by sethsimon** [comment]
Good catch- that age display is also a bug when the scenario starts 1 year or more after the cataclysm because the base age refers to the beginning of the cataclysm, which isn't necessarily the same as the beginning of the gameplay. A quick test with a scenario that starts 12 years after the cataclysm shows that the character is 25 in the character creation screen, but upon starting the game they'll be 36 (no, not 37 for some reason). Just from reading the code, I don't think your change would fix that because `age_string` uses `calendar::turn` which is initialized by `game::start_calendar` which is called by `game::start_game` which is called in main_menu.cpp AFTER calling `avatar::create` (Update: Yeah, I tested that change and it still shows up as 25[1]).

A proper fix is further complicated by the ability for scenarios to have a random start year, so we can't just peek at the scenario info to calculate it. I guess `scenario::set _scenario` (which is in game.cpp) should be responsible for setting `calendar::turn`.

[1]Compiling just that change results in a 1.6GB executable (no wonder linking hung my PC and took all night) and ld warns:
```
/usr/bin/ld: error: cata_test(.debug_info) is too large (0x4e6fe468 bytes)
/usr/bin/ld: error: cata_test(.debug_line) is too large (0x6279cd4 bytes)
/usr/bin/ld: error: cata_test(.debug_str) is too large (0x53841dd bytes)
/usr/bin/ld: error: cata_test(.debug_loc) is too large (0x23abd1ca bytes)
```
Even though it says it's an error, it still succeeded. It looks like the Makefile has lots of options, so I'll have to see what I can do about that.

**Comment by ZhilkinSerg** [comment]
RELEASE=1
