### ISSUE TITLE
Mutation needs an option (instant mutations without waiting)

### ISSUE THREAD

**Issue by Altogolik** [CleverRaven/Cataclysm-DDA#60444]
### Is your feature request related to a problem? Please describe.

I liked the old system of mutations - they happened instantly, I knew immediately what the result and could replay this moment.
Now it's impossible to control the mutations, which really ruined the game for me.

### Solution you would like.

Need to add an option to the debug menu (instant mutations without waiting)
There is already an option to turn off the degradation of skills think the right place for it

### Describe alternatives you have considered.

If there was an option without negative mutations, the wait wouldn't be so scary.  (I used to be able to just restart the game and get the same positive results, wasting my time)

**Comment by Fris0uman** [comment]
We don't track feature request for the debug menu, debug menu is meant for debuging and not for players.

**Comment by Altogolik** [comment]
Why wrong? I changed the description

**Comment by esotericist** [comment]
locking this one as well (submitter opened multiple issues)
