### ISSUE TITLE
Mutation needs an option (instant mutations without waiting)

### ISSUE THREAD

**Issue by Altogolik** [CleverRaven/Cataclysm-DDA#60447]
### Is your feature request related to a problem? Please describe.

I liked the old system of mutations - they happened instantly, I knew the result immediately and could replay that moment.
Now it's impossible to control the mutations, which really ruined the game for me.

### Solution you would like.

Need to add an option in the world settings menu (there is 1 option mutations from radiation, you can add 1 more setting)
- Instant mutations yes\no.

### Describe alternatives you have considered.

If there was an option without negative mutations, the wait wouldn't be so scary. (I used to be able to just restart the game and get the same positive results, wasting time).

**Comment by fungamer2-2** [comment]
This is the same as an issue you opened that was already closed (#60444)

**Comment by mqrause** [comment]
For that use case you can just edit your mutations in the debug menu.

**Comment by Altogolik** [comment]
This is inconvenient, and this proposal is not a copy, in that I wrote about debug to which I was told that in debug do not add options, here I suggested a setting in the world menu

**Comment by mqrause** [comment]
How is that inconvenient compared to "I don't like that mutation result so I'll reload"?

Another option is making a mod without negative mutations, though I don't know if you can actually remove mutations in a mod.

**Comment by esotericist** [comment]
we don't provide options like this for changes in gameplay as a matter of policy. it's all data-driven in json, so if someone wants to make a mod changing how mutation behaves, they can feel free to do that, but it's not going to be in a menu like is being requested here.

please don't open a third issue for this, you're not going to get the result you're after.
