### ISSUE TITLE
Bike racks causing vehicle tiles to merge

### ISSUE THREAD

**Issue by DPavonis** [CleverRaven/Cataclysm-DDA#60453]
### Describe the bug

On a two tile vehicle, with bike racks on both tiles and identically-named sub-vehicles loaded on both racks, attempting to unload one of the sub-vehicles will cause it to merge with the other

### Steps to reproduce

1.) Have a two tile vehicle with bike racks on each tile
2.) Create two sub-vehicles and name them identically
3.) Load both sub-vehicles onto a rack
4.) Attempt to unload a vehicle from the rack

### Expected behavior

That the sub-vehicles not re-enact Jeff Goldblum's role in The Fly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 3d2829c-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Here is a video demonstrating the bug in action:
https://www.youtube.com/watch?v=Toim8dtdvWU

Attached save has a vehicle ready to demonstrate the bug; simply attempt to unload a vehicle from either rack:

[two_tile_vehicle_bike_rack_bug_demonstrator.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9429904/two_tile_vehicle_bike_rack_bug_demonstrator.zip)

**Comment by anothersimulacrum** [comment]
CC @irwiss - I don't know if something you've done recently fixes this.

**Comment by DPavonis** [comment]
Bug is still present as of build 3d2829c-dirty [64-bit], will update the ticket with a link to a video demonstrating the bug once it's finished processing.

**Comment by irwiss** [comment]
I didn't dig too deep yet, but it looks to me like vehicle name is the only separator between vehicles if you rack a few of them side by side on the same rack
https://github.com/CleverRaven/Cataclysm-DDA/blob/3d2829c8230ede7b009033ee50c1c32d13674465/src/vehicle_use.cpp#L2024
