### ISSUE TITLE
New "Person" portal storm monster does not despawn

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#60455]
### Describe the bug

The Person monster which spawns during a portal storm, persists even after the weather clears.

Because of this, facing them would eventually become inevitable

### Steps to reproduce

1. Let them spawn during a portal storm, while staying in an unreachable place
2. Wait till the storm ends
3. They will persist and continue "hunting" the player

### Expected behavior

Despawn

### Screenshots

![image](https://user-images.githubusercontent.com/88375697/186832602-03dc8b7a-ecfd-4830-904e-ba40aadbd8ae.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: e6d3244-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Vampiric Stuff [vamp_stuff],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Ramza13** [comment]
So right now it should die 40-60 minutes after being spawned.  Technically this is how all portal storm monsters work, they don't all die when the storm ends, but most of them have life spans of like 5 minutes max so you don't notice it.  Its possible I will get around to killing them at storm end but its low on the priority list.

I didn't actually make that monster and haven't really looked at it, its possible 40-60 minutes is way too long and I'll try to remember to take a look when I eventually rebalance all of portal storms someday but no promises.

**Comment by chrispikula** [comment]
I don't have that save-state anymore, but I had a similar issue that I think was tied to a reload, or possibly them standing on an external boardable part of a vehicle.

**Comment by RDru** [comment]
I can confirm the problem. Even slept 7h and they are still around.
![1](https://user-images.githubusercontent.com/26722636/188265978-4e034755-f24d-488b-bb6e-82e2997d94aa.png)
