### ISSUE TITLE
Odd food type assignments

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#6045]
Okay, so I just downloaded the latest build and decided to do a diet-restrictive character build. I chose Hates Vegetables, Junkfood Intolerant, and Lactose Intolerant. However, it quickly became apparent that things were screwy, namely that fruits seem to be treated as vegetables (so far: oranges, grapefruits, and lemons) and certain other foods seem to fall under the restricted foods umbrella. Lemonade, for instance, is one I can think of off the top of my head. Probably not a bug (can't imagine how it could be), but darned weird all the same. If it gets aggravating enough, I'll probably do a file crawl of the relevant jsons myself, but I just thought I'd just raise the issue in the meantime.

EDIT: Took a look at the in-game recipes list, and no wonder I'm having issues. Fruit recipes are lumped under VEGGI, making them nonsensically off-limits to one who hates vegetables.
##

**Comment by mightyagrippa** [comment]
I'm looking at this, seems there's still room to improve. Some food (french toast, boozeberry, etc) has three ingredients as opposed to the normal two. Is this fine? For some reason the diamond kukri has a third ingredient too.

**Comment by Rivet-the-Zombie** [comment]
>Some food (french toast, boozeberry, etc) has three ingredients as opposed to the normal two. Is this fine?

Yeah, it can handle more than two materials.
