### ISSUE TITLE
Allow spells to be casted not from critter's body

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#60461]
### Is your feature request related to a problem? Please describe.

Right now all spells move from the caster's body, which looks wonky if you try to use extra_effects

### Solution you would like.

flag (or maybe boolean field for extra effect?), that allow player to use a different point, where spell is created.

### Additional context

| Current mechanic  | This feature |
| ------------- | ------------- |
| ![1](https://user-images.githubusercontent.com/67688115/186895710-18c57dc3-9aa4-4954-9171-1cf4e611a005.png)  | ![2](https://user-images.githubusercontent.com/67688115/186895743-41c2cfc6-6834-4b77-9529-5a2d9709fff9.png)  |

**Comment by KorGgenT** [comment]
how would you imagine this would work? how would you know where the "inflection point" would be?

**Comment by GuardianDll** [comment]
I think we can use a dummy spell at first, picking a first point, and then use the spell itself, that cause stuff

**Comment by KorGgenT** [comment]
oh, i see, you're suggesting that the player chooses where the inflection point is? how would this work for npcs/monsters?

**Comment by GuardianDll** [comment]
hmm. thats a good question, that i did not thought about

**Comment by GuardianDll** [comment]
I don't really think it would be possible to make monsters use this system, except with the "random_target" flag. the only way for monster's to make it targetable is "first spell aim the target, second spell pick a random spot near the target, and then the third spell can cast something dangerous"

The reason i stick to this idea is, at first, make the proper way for character to cast "walls", that do not bonded to his position (like the `+` or `x` shape spell will work), and also to use spells in places, where connection to player would be bad - the original idea was to make a series of "reality rifts", dropping clairvoyance field of random line shapes on a whole map
![unknown-98](https://user-images.githubusercontent.com/67688115/196354550-c35c43e0-4866-4da1-a229-1f912571cbfe.png)
But instead, i found the game do not handle it properly, casting all rays out of player's body
![unknown-64](https://user-images.githubusercontent.com/67688115/196354660-b43e680d-2c42-4093-9b65-0e1b8df8d544.png)
