### ISSUE TITLE
Manhole covers disappear when lifted 

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#60468]
### Describe the bug

Manhole covers do not appear next to the manhole when lifted using a hammer.

### Steps to reproduce

Find a covered manhole.
Find a prying tool.
Lift the manhole cover using the tool.

### Expected behavior

Expected a manhole cover.

### Versions and configuration

Game version 0a3bbdd
Mods: DDA

### Additional context

When climbing up through a covered manhole a manhole cover appears next to the now open manhole.

**Comment by Rygalenko** [comment]
Confirmed.
