### ISSUE TITLE
Settings weather/real cataclysm

### ISSUE THREAD

**Issue by 01010UA** [CleverRaven/Cataclysm-DDA#60479]
### Is your feature request related to a problem? Please describe.

There is not enough function to be able to change weather conditions like: acid rain > portal storm > thunderstorm.  Every day a new disaster.

### Solution you would like.

Weather control option when creating the world

### Describe alternatives you have considered.

Mod

### Additional context

Add new disaster

**Comment by ZhilkinSerg** [comment]
Weather is mostly not hardcoded. New weather types and effects can be easily added in JSON and controlled through regional settings, EOC and debug menu. There is no need to expose any settings to UI.

**Comment by 01010UA** [comment]
Ok
