### ISSUE TITLE
Stratoscomm relay station has an abnormal roof

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#60470]
### Describe the bug

There's a huge chunk of grass and dead grass on the roof of the Stratoscomm relay station, where one would expect open air, especially considering the solar panels on the ground floor.

### Steps to reproduce

Find a Stratoscomm relay station.
Find a way to the roof.

### Expected behavior

Expected open air to be present.

### Versions and configuration

Game version: 0a3bbdd
Mods: DDA, Aftershock

**Comment by hexagonrecursion** [comment]
/confirmed

![image](https://user-images.githubusercontent.com/52621858/189584021-3725d950-7cfc-4c58-b6b0-ca26c866ee12.png)


- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: b9c5366 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]
