### ISSUE TITLE
Faction epilogues are displayed incorrectly in death ending screens

### ISSUE THREAD

**Issue by Extension-Driver** [CleverRaven/Cataclysm-DDA#60480]
### Describe the bug

Upon death, faction epilogues are displayed incorrectly if the player has met any faction. 

### Steps to reproduce

1. Find the site of any faction (I used the refugee center and Hub 01)
2. Speak to any NPC of that faction, OR do 1 mission for them (or complete mission in debug menu)
3. Abandon your character with Shift-Q
4. See that the "bad" epilogue and "good" epilogue ending is displayed twice.

### Expected behavior

Only 1 faction epilogue is shown. I expect that, depending on the player's choice, only one set of events will play out for every in-game faction.

### Screenshots

_**Endings for the Free Merchants:**_
![FreeMerchantEndings](https://user-images.githubusercontent.com/85973915/187020512-7ee77f09-5170-45c7-b528-ae77844f13ac.png)

_**Endings for Hub 01:**_
![Hub01Endings](https://user-images.githubusercontent.com/85973915/187020527-c52bb646-b6f2-4295-b0d0-02ab666fd4c2.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 725e825 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I think the endings are due a rewrite anyway: they're quite old.

**Comment by ZhilkinSerg** [comment]
Faction epilogues are displayed based on faction power. One needs to define `power_min` and `power_max` for each epilogue entry to control whether epilogue entry is displayed or not. For Hub 01 there is no `power_min` for one epilogue entry and no `power_max` for another epilogue entry, thus both would appear simultaneously.

https://github.com/CleverRaven/Cataclysm-DDA/blob/aa80ff7838c77ecbaae42d18a74bc207e3bd90cd/data/json/npcs/factions.json#L79
