### ISSUE TITLE
Infinite stepladders!

### ISSUE THREAD

**Issue by OnTheDouble** [CleverRaven/Cataclysm-DDA#60487]
### Describe the bug

I attached a savegame with me holding the ladder. See for yourselves.

### Steps to reproduce

1. Pl[a]ce the ladder you are holding
2. One ladder will be placed and one will still be in your hands

### Expected behavior

Ladders should be finite. I play this game for its realism!

Here's my savegame.
[Wetmore.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9438084/Wetmore.zip)

### Screenshots

![2022-08-27_16-44-06](https://user-images.githubusercontent.com/82908191/187032959-cb58486b-7a87-488f-b6f6-10b5022b9807.png)

### Versions and configuration

 cdda-windows-tiles-x64-msvc-2022-08-27-0708.zip

### Additional context

Turning it off and on again didn't fix the bug.

**Comment by Marcos6226** [comment]
Lol, funny way to do a report.
Poking @Night-Pryanik

**Comment by Night-Pryanik** [comment]
My recent work on stepladders has nothing to do with this bug, but I fixed it anyway.

**Comment by OnTheDouble** [comment]
Thanks a lot!

**Comment by Marcos6226** [comment]
> My recent work on stepladders has nothing to do with this bug, but I fixed it anyway.

Of course, I knew that. I just assumed that since you've worked with ladders before, you'd know how to fix this one as well. Anyway, thank you very much.
