### ISSUE TITLE
Add a Raw Carcass item for cooking

### ISSUE THREAD

**Issue by Xaritscin** [CleverRaven/Cataclysm-DDA#60501]
### Is your feature request related to a problem? Please describe.

A feature i was talking about the other day. right now players butcher all kinds of animals for meat but stuff like chicken or rabbit end being a waste of time most of the time because you only get scraps of meat instead of a good chunk of rabbit/chicken

This request is based around the idea of giving a way for players to make use of the butchering system to generate a raw food item that could be used for cooking the whole animal after skinning and field dressing it.

### Solution you would like.

After some talking in discord im not sure if the current code allows to make a carcass directly out of a corpse after taking out the skin and field dressing it.

So right now it appears the only option is to add a "prepare carcass" option in the butchering menu. this option should get rid of all organs and would skin the corpse to prepare it for cooking on a grill or smoker.

This would be like butchering the corpse in full but the end result would be the full carcass, the hide/furs and the organs + a lot of blood. with a significant time consumption because you are doing triple the work of skinning the corpse and then taking out the organs so you can use the full headless body for cooking rather than just for skin/preservation purposes.

### Describe alternatives you have considered.

produce the carcass when doing full butchery but it may conflict with the purpose of doing a full pull out of the corpse(?), otherwise we could move the separate butchery produce from a full butchery to disecction instead.

### Additional context

This proposal is basically to give more of an option for players when they find small game. instead of getting a few scraps just get a full carcass that is consequent with the amount of meat that should be obtained from the animal.

Then the carcass could be used for different cooking recipes. like, for real, how come we dont have the option to make a full coocked chicken/fish/rabbit or other. it kind of breaks realism to just cut out the meat from the animal rather than cook it in full.

**Comment by PatrikLundell** [comment]
The problem is that the eating system probably doesn't support byproducts (cooked bones mainly, not usable for bone crafting). Instead is uses the rather inflexible system of 250 ml "portions".

Thus, the cooking of a plucked and gutted chicken carcass would have to result in a multiple of "whole chicken" portions plus a stack of bones too small to be usable (although I think they could still be used for broth in real life).

**Comment by anothersimulacrum** [comment]
> the rather inflexible system of ~~250 ml~~ **$ITEM_VOLUME** "portions".
