### ISSUE TITLE
Sidebar Map artifacting with OpenGL/OpenGLES

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#60508]
### Describe the bug

The sidebar's minimap artifacts in newly discovered but unseen regions.

### Steps to reproduce

1. Switch graphics renderer to OpenGL or OpenGLES
2. Reload CDDA
3. Enter a world from the menu
5. Notice the artifacts

### Expected behavior

No artifacts.

### Screenshots

![mmogl](https://user-images.githubusercontent.com/32048635/187050915-63c6e7ac-e151-4beb-a26b-27bf4a75b4bf.png)
OpenGL renderer teleporting from a field
![mmogles](https://user-images.githubusercontent.com/32048635/187050914-e4540d18-0afa-4543-bc5c-3188bc13db0e.png)
Reloaded into OpenGLES renderer
![mmoglreloaded](https://user-images.githubusercontent.com/32048635/187050913-885caaf9-daa7-47d4-8f43-167e785932bd.png)
Reloaded into OpenGL renderer

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 3d2829c-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Mesa drivers are up-to-date, this does/did not happen in my previous testing release, ```bb34fdb```. I have not changed the sidebar. I'm under the assumption it is due to #60412.

**Comment by ANickelN** [comment]
/confirmed although this is presenting differently to me, as distinct squares of corruption instead of just blobs

**Comment by EIIKaO** [comment]
This also happens often with using sloping stairs (e.g., back stairs at a winery).

It seems to happen similarly with software and direct3d too.
In my case with software rendering, the lights? on the minimap were animating like searchlights.

For people who can't tolerate Abstract expressionism:
The simplest quick and harmless fix as a users is change `Options-Interface-Graphics-Background color` to `theme`.
Maybe dissapear artifacting and will not affect on your game-experience, unless you are using a custom theme.
