### ISSUE TITLE
Using search bypasses scenario starting requirements.

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#60519]
### Describe the bug

If you use search in the scenario selection you can choose challenge scenario that you do not have the requirements for.

### Steps to reproduce

1. Start new character.
2. Scenario tab.
3. Search `/` for name of challenge scenario (for example "lab").
4. The top result gets turned on even if you do not have requirements for it.

### Expected behavior

Search should not move the selection.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 0.F-10912-g28a5100a36 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 21 October 2024.
In scenario tab pressed `/` to search for `The Next Summer` scenario. The result of the search is still unavailable.
![изображение](https://github.com/user-attachments/assets/abe161d5-28e4-4a94-b485-3e1fb482305a)
