### ISSUE TITLE
Folding vehicles duplication

### ISSUE THREAD

**Issue by buffog** [CleverRaven/Cataclysm-DDA#60536]
### Describe the bug

Activating folded vehicle no longer removes it from inventory.

### Steps to reproduce

1. Spawn or otherwise acquire any folding frame
2. Construct a folding vehicle 
3. Activate the vehicle to unfold it
4. Vehicle deploys, while its copy stays in inventory/wielded, allowing any number of additional activations. 

### Expected behavior

Expected not being able to spawn infinite copies of a folding vehicle

### Versions and configuration

Version: 70905b5, Android x64, Tiles, English language. 
Reproducible with default mods.

**Comment by irwiss** [comment]
Likely needs same treatment as #60512

**Comment by buffog** [comment]
Tents also duplicate.

**Comment by irwiss** [comment]
> Not sure if it uses same mechanics as folding vehicles

It is, all folding vehicles now use the same code paths after 646fa4d

Tents have separate iuse
