### ISSUE TITLE
Second level staicase not breaks after 1st lvl destroyed

### ISSUE THREAD

**Issue by valerij-makogonenko-idf** [CleverRaven/Cataclysm-DDA#60540]
### Describe the bug

When lower level staircase destroyed upper level part stays undamaged, you can stay on it and hit zonbies at beneath with now fight back

### Steps to reproduce

Load save game 
or
1)destroy 1st lvl staicase 
2)attract zobies
3)get to upper floor
4)stay on upper floor staircase icon
4)stay with pass turn button on

### Expected behavior

Zombies can hit back 
Upper ladder icon destroyed

### Screenshots

![image](https://user-images.githubusercontent.com/102046697/187094160-6b8db0ef-2d75-4c67-b8f8-0858c7cea7d2.png)
first floor
![image](https://user-images.githubusercontent.com/102046697/187094171-1adf84f3-a169-4715-9a00-c4473a653306.png)

### Versions and configuration

Win 10 64 
CDDA ver:
 70905b5 tiles
 2022-08-28-0848
Experimental 3d field view - on 

### Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9440458/save.zip)

**Comment by PatrikLundell** [comment]
A staircase whose bottom part is destroyed is working as intended. You get a warning trying to descent saying there's a drop and you'd have trouble getting back up, etc. It can be noted that it's not uncommon for zombies in basements to smash up the stairs.

As far as I understand, it's intended that you should be able to fight zombies below the stairs if you have a reach or missile weapon and experimental 3D view is enabled. Only zombies with a reach or missile attack ought to be able to fight back (I don't know if a grabber zombie is able to grab you currently, but they should be able to do so).
If you're able to fight zombies beneath the stairs with a normal melee weapon that's probably not intended.

**Comment by valerij-makogonenko-idf** [comment]
If you're able to fight zombies beneath the stairs with a normal melee weapon that's probably not intended.
 
 yes i can bash them with wood plank

**Comment by valerij-makogonenko-idf** [comment]
> If you're able to fight zombies beneath the stairs with a normal melee weapon that's probably not intended.

Yes i can bash them with bare hands and get no fight back
