### ISSUE TITLE
Make character sit/lie while doing some activities

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#60542]
### Is your feature request related to a problem? Please describe.

Character still stay on his legs while reading books (abd i believe its pretty hard to stay in one place for hours without movenents) or crafting

### Solution you would like.

Make character crouch while reading books (at least) 

### Describe alternatives you have considered.

Better would be a way to make a separate json for activities, that describe in what position character can do them, and pick the most "lazy" of them (i believe it could be useful in future, when #42556 would work, but we're pretty far from it) 

### Additional context

Am i the only who sit on the sofa/chair while reading books?

**Comment by Marcos6226** [comment]
> Am i the only who sit on the sofa/chair while reading books?

I normally lie down so the blood goes to the brain more easily and I absorb more information.
<sub>~~It's a lie, I'm just lazy~~</sub>

**Comment by PatrikLundell** [comment]
I role play it by having my character move onto a chair (beside the workbench) when reading or crafting (I'm not saying automatic stance changes aren't useful, only that there's a work around available currently).

**Comment by 1FSTCAT** [comment]
Perhaps a lack of comfort for some activities could effect focus and how quickly the character becomes weary? That would give furniture a purpose!
