### ISSUE TITLE
Mutagen Chelator doesn't spawn anywhere

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#60548]
### Is your feature request related to a problem? Please describe.

When mutations were reworked to use vitamins, a new item - mutagen chelator - was added into the game. Its purpose is to remove mutant vitamins from blood without having to wait in-game years or mutating. As far as I can tell, it works perfectly and isn't bugged in any way. However, it wasn't added to any of the spawn groups and never appears in the game world. Why? It's a useful item, and the original PR mentions it should be common in labs, more common than purifier.

### Solution you would like.

Add mutagen chelator to lab spawn groups.

### Describe alternatives you have considered.

Perhaps it was internally decided the item shouldn't exist for whatever reason? If yes, it should be removed from the files.

**Comment by Marcos6226** [comment]
I'm going to check this. See what can be done.
