### ISSUE TITLE
Debug message when trying to wield things with activated unwieldable bionics

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#60550]
### Describe the bug

Debug message when trying to wield things with activated unwieldable bionics, such as monomolecular blade.

### Steps to reproduce

1. Got monomolecular blade, install and activate it.
2. Try to wield something else.
3. Debug message.
4. If you continue the game, the bionic will be deactivated and you will be wielding thing you was trying to wield.

### Expected behavior

You shouldn't be able to try to wield anything with activated unwieldable bionics
OR
No debug message, unwieldable bionics should be automatically deactivated (with a check for power required for deactivation, where applicable), you successfully wield thing you was trying to wield.

### Versions and configuration

Windows 10 x64, 0.F-10914.

### Additional context

 DEBUG    : Wielded weapon doesn't match the expected weapon equipped from Monomolecular Blade

 FUNCTION : process_bionic
 FILE     : E:\Cataclysm-DDA\src\bionics.cpp
 LINE     : 1770
 VERSION  : 0.F-10914-g70905b58ae-dirty

**Comment by Raikiri** [comment]
There's also weird errors when you're wielding something and then activating the claws. These errors include fusing claws with the wielded item, being unable to retract the claws/unequip the item, etc. Happened on vormithrax's stream too.

**Comment by Night-Pryanik** [comment]
Don't know when this was fixed, but it's no longer an issue. Game automatically deactivate and withdraw unwieldable bionic when you're trying to wield something else.
