### ISSUE TITLE
Allow for the use of captured monsters in crafting recipes

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#60559]
### Is your feature request related to a problem? Please describe.

Not necessarily a problem but while discussing the possibility of craftable aquariums it came to light that the ideal solution would be to be able to use captured fish in the crafting recipe itself, which at the moment is not possible. This is certainly not any sort of priority issue, just for the sake of more possibilities in the long run (could also allow for the crafting of items such as the Firefly Lantern). 

### Solution you would like.

As stated in the title, the ideal solution would be to be able to use monsters captured in 'animal containers' such as pet carriers as ingredients in crafting recipes.

### Describe alternatives you have considered.

Sure, you could use eggs instead of a living monster/animal/whatever in the recipe for aquariums or firefly lanterns, and it's certainly an option, but this alternative feels more in line with what it should be.

**Comment by Amoebka** [comment]
I believe reducing instability was deemed a powerful effect that should only be found in a special rare item for it, comparable to smart purifier or alpha serums in rarity. Common chelators shouldn't be able to do that, probably, you need a new item with lower spawn chance.
