### ISSUE TITLE
Debug message after collapsing roof

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#60551]
### Describe the bug

When the roof (or second floor) has collapsed, there is a debug message popping up.

### Steps to reproduce

1. Set some intact building (for example, starting evac shelter) on fire.
2. Wait for building's roof to start collapsing.
3. Debug message.

### Expected behavior

No debug message.

### Versions and configuration

Windows 10 x64, 0.F-10914.

### Additional context

 DEBUG    : Setting terrain t_open_air at (55,62,0) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : ter_set
 FILE     : E:\Cataclysm-DDA\src\map.cpp
 LINE     : 1964
 VERSION  : 0.F-10914-g70905b58ae-dirty

**Comment by PatrikLundell** [comment]
Previously reported as #54092 and #56242.
