### ISSUE TITLE
Flag blacklisting for 'animal containers'

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#60557]
### Is your feature request related to a problem? Please describe.

At present, all 'animal container' type items can pick up all monsters that fit the size limit. This poses several problems such as aquatic animals being able to be carried around in stuff like chicken cages. The flag limiting could also be useful for any enemies that are supposed to be liquid/liquid-esque such as slimes, any future (or present if those exist) enemies that can teleport and very likely several other alternatives that I am not aware of at the moment.

### Solution you would like.

Ideally a way to blacklist flags in the json of the item itself, so you can have a transporter than can pick up everything BUT stuff with the AQUATIC flag for example. I'm saying ideally in json because I feel like having it be hardcoded wouldn't end up helping a lot of contributors in the long run.

### Describe alternatives you have considered.

None, really, as any alternatives would be single-solution hardcoded items. Not really ideal, in my opinion.

### Additional context

I would like some confirmation on whether the current system also allows the player to capture portal storm monsters and/or hallucinations as I think it may. If it does that's more reason for the flag blacklisting to become a thing.

**Comment by chrispikula** [comment]
Perhaps tie it to the dissection proficiency associated with that class of creature?

**Comment by Karol1223** [comment]
> Perhaps tie it to the dissection proficiency associated with that class of creature?

I guess that could be an additional nice way to blacklist things, flags still would be the most versatile and easiest to manage but having both of those as options would make this even nicer.
