### ISSUE TITLE
[XEDRA Evolved] Brass Cylinders adds an undefined spell to character which causes a CTD when used

### ISSUE THREAD

**Issue by Ladikn** [CleverRaven/Cataclysm-DDA#60563]
### Describe the bug

Was looting a mine entrance and found "a set of brass cylinders", which would teach the spell "Call Oneiric Hammer".  When used added Dreamsmith which upon accepting caused a string of errors and added a blank spell to the spell list.  Using that spell caused a CTD.  

While researching a possible solution, this seems to be the same error that was reported in the closed bug report #59588; however, while that bug was closed due to being strictly caused by messing with debug, this was encountered normally in game.  I did reproduce it using debug (as described below), but I avoided messing with the character to keep it as clean as possible.

I couldn't reload that save (it was a new character so the CTD lost that world), so to double check it I made a fresh character, used the overmap editor to spawn a bunch of mine entrances, and looked through them.  At the third one I found a fresh set of brass cylinders in a junk drawer, which caused the same issue.

### Steps to reproduce

1) Make a character
2) Give the character "a set of brass cylinders", either through spawning the item or looting a mine entrance as described above
3) Learn the spell "Call Oneiric Hammer"
4) Become a Dreamsmith
5) Cast the blank spell

### Expected behavior

Normally I'd say that the blank spell wouldn't be added and instead the intended spell would be added.  However, from bug report #59588 that this is unfinished content and shouldn't be player accessible, so I'd say the expected behavior would be that the set of brass cylinders should not be lootable from the mine entrance until it's ready for release.

### Screenshots

![image](https://user-images.githubusercontent.com/8979197/187242807-b52d61f7-7897-4a71-a2d7-9780c38b64c3.png)
![image](https://user-images.githubusercontent.com/8979197/187242921-f2d1ec09-1787-48ed-aea6-df92b1b041e2.png)
![image](https://user-images.githubusercontent.com/8979197/187242996-705c255a-db6c-4ede-baf0-f6f2db831b3f.png)
![image](https://user-images.githubusercontent.com/8979197/187243014-e0249d39-5c17-420c-9af7-854e667c6591.png)
![image](https://user-images.githubusercontent.com/8979197/187243036-f9e610ea-ffac-4719-b8e5-17d29385a56f.png)
![image](https://user-images.githubusercontent.com/8979197/187243141-ec85335b-023a-4dd7-8b2c-241297f0c746.png)
![image](https://user-images.githubusercontent.com/8979197/187245456-efe1b36a-36b7-40eb-a612-a63e46d05318.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: c375f1d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by Maleclypse** [comment]
Thanks for reporting this.  I shouldn't have added this in the spawn lists yet.  I'll see if I can get a fix out tonight.
