### ISSUE TITLE
Can't place mattress on floor

### ISSUE THREAD

**Issue by Constellati** [CleverRaven/Cataclysm-DDA#60570]
### Describe the bug

When trying to deploy a mattress on the floor, the game encountered the following bug and simply moved the mattress item to the tile I was standing on, without deploying it.

### Steps to reproduce

Disassemble a bunk bed, move the mattress onto the floor, hit a to activate the mattress, the bug comes up and the mattress moves to the tile, undeployed.

### Expected behavior

I was expecting that the mattress be placed down as furniture for me to sleep on.

### Screenshots

![image](https://user-images.githubusercontent.com/101519321/187277010-c61d86d5-c634-4edf-8693-f04b2f7ed954.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: d2a84e3-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp]
]

### Additional context

 DEBUG    : Failed to obtain target item

 FUNCTION : use_item
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\avatar_action.cpp
 LINE     : 1165
 VERSION  : d2a84e3-dirty

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 21 October 2024. 
Activating mattress lying on the ground with broken arm gives you the `You couldn't pickup the mattress.` message and stopping the activation activity without any debug messages.
