### ISSUE TITLE
error message when plugging an appliance's power cord to other appliance

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#60589]
### Describe the bug

This error message pops up whenever I plug in an appliance's power cord to another appliance.
 
 DEBUG    : did not found item power cord (active) to remove it!

 FUNCTION : item Character::i_rem(const item *)
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/character_inventory.cpp
 LINE     : 251
 VERSION  : b5e0cb5

Beyond that, said power cord is connected and working. 

### Steps to reproduce

1. Make a new world.
2. Get yourself 2 appliances.
3. Plug one of the appliance to another.
4. Error message.

### Expected behavior

Error message not popping up whenever I daisy chain my appliances.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: b5e0cb5 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Might be related to #60516

**Comment by Hirmuolio** [comment]
The problem seems to be that `iuse::cable_attach` is used for both extension cords (which needs to be removed after use) and plugging appliances on their own (so no cord is involved).
