### ISSUE TITLE
Nested recipes make it hard to quickly scan your recipes

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#60588]
### Is your feature request related to a problem? Please describe.

- 1 Nested recipes appear in your list in a nice interactable blue that always make me think I can craft a thing when in fact I can't
- 2 There's no way to know what is in the nest whithout opening it
- 3 Once you get inside the nested recipe you can't go back to where you were without tabbing back to the category and scrolling down again

### Solution you would like.

1 and 2 could be solved by listing the recipes in the category in the right panel, right now that panel is pretty much empty it could instead list all the recipes listed in the category in white if craftable and grey if not

3 was partially adressed in #60378 but when you back out to NESTED you're still not where you were when you opened the list of nested recipes

### Additional context

Nested recipes are a great idea but personally right now I'm more annoyed at navigating through them than I was at scrolling through thousands of recipes.

**Comment by bombasticSlacks** [comment]
These are all on my list fwiw I've just been on vacation. 

If someone else wanted to tackle 1/2 with your suggestion it is quite easy to do.

**Comment by irwiss** [comment]
Perhaps consider tree-like nesting? it keeps visually consistent context without jumping around in the UI while providing the means to drill down nested items, for example:

```
flyswatter
maces
  great pipe mace
  pipe mace
  simple mace
nail bat
sling-ready explosives
  sling-ready grenade
  ...
```

Could also help mitigate the fact crafting menu is turning into 4 dimensional monstrosity:
* categories on top ( switch with tab / backtab )
* categories below them ( switch left/right arrow ), which default to "all" anyway, i doubt most players even notice them
* nested categories which are kinda-items ( switch with enter and pretty sure you can't go back )
* finally the actual items which you wanted to actually see

Tree view would make navigation super consistent; up/down to select, right arrow to expand and left to collapse, filters/search could also show you which categor you're in

**Comment by bombasticSlacks** [comment]
If you wanna scrap what I've got and redo it as a tree while also doing the entire crafting menu rework required to make your control scheme work feel free 🤷

Let me know if you are and I won't bother with these last two bits of cleanup.

**Comment by ANickelN** [comment]
To your point #2 @Fris0uman , which nests are unclear as to what is inside?  I've tried to label them all as obviously as possible, but if there is any that seem too ambiguous let me know and I can go back and change them.

**Comment by Fris0uman** [comment]
No but the names are fine they still don't give me the list of all recipes inside

**Comment by ANickelN** [comment]
That's kind of the point of the system though, isn't it?  To not show the recipes until you click on the broader group in order to de-clutter the crafting menu.  Maybe I'm not understanding what you mean.

**Comment by Fris0uman** [comment]
![image](https://user-images.githubusercontent.com/41293484/187530987-3b84ef90-2f64-441f-a4ad-d84d2a2b6a5b.png)
Here's some quick mock up, there's tons of empty space on the right, we could put the list of recipes that are nested within the recipe on the left in there

There's almost enough room to put the recipe themselves there
![image](https://user-images.githubusercontent.com/41293484/187531422-4b971661-fa8d-4246-a1fa-8fc728969dd2.png)

**Comment by Zireael07** [comment]
@Fris0uman is that the default window size though?

**Comment by Fris0uman** [comment]
The window is organised in thre column, the two column on the right are empty, in a smaller window there would be less space bt still two mostly empty column on the right

**Comment by showerv** [comment]
> Here's some quick mock up, there's tons of empty space on the right, we could put the list of recipes that are nested within the recipe on the left in there ![image](https://user-images.githubusercontent.com/41293484/187530987-3b84ef90-2f64-441f-a4ad-d84d2a2b6a5b.png)
> 
> There's almost enough room to put the recipe themselves there ![image](https://user-images.githubusercontent.com/41293484/187531422-4b971661-fa8d-4246-a1fa-8fc728969dd2.png)

A lot of unused empty space in 2nd column.
Not applicable to show all nested recipes expanded.
Not adaptable for smaller screens.
