### ISSUE TITLE
Simple deconstruct oven

### ISSUE THREAD

**Issue by Rasengetsu** [CleverRaven/Cataclysm-DDA#60619]
### Describe the bug

Simple deconstruct turned "gas oven and microwave combo" into just a microwave object and no oven or components.
https://cdn.discordapp.com/attachments/598523535169945607/1014385689246302238/unknown.png

### Steps to reproduce

1. Find gas oven and microwave combo
2. Use simple deconstruct
3. Problem

### Expected behavior

A gas oven and microwave should be created, or at the very least the components of a gas oven along with the microwave.

### Screenshots

https://cdn.discordapp.com/attachments/598523535169945607/1014385689246302238/unknown.png

### Versions and configuration

Windows 10
Experimental
Version 9bd27c3
Build 2022-08-30-1852

**Comment by misterprimus** [comment]
I can confirm. Looks like you can still get the oven by disconnecting it first. This seems to be the culprit:
![image](https://user-images.githubusercontent.com/45959491/188255872-2fb0c54d-b332-4947-b3d4-df03d397e19d.png)

**Comment by misterprimus** [comment]
> ### Describe the bug
> Simple deconstruct turned "gas oven and microwave combo" into just a microwave object and no oven or components. https://cdn.discordapp.com/attachments/598523535169945607/1014385689246302238/unknown.png
> 
> ### Steps to reproduce
> 1. Find gas oven and microwave combo
> 2. Use simple deconstruct
> 3. Problem
> 
> ### Expected behavior
> A gas oven and microwave should be created, or at the very least the components of a gas oven along with the microwave.
> 
> ### Screenshots
> https://cdn.discordapp.com/attachments/598523535169945607/1014385689246302238/unknown.png
> 
> ### Versions and configuration
> Windows 10 Experimental Version [9bd27c3](https://github.com/CleverRaven/Cataclysm-DDA/commit/9bd27c3bd250c88ccf42c2b2d26c47c0fe3819cd) Build 2022-08-30-1852
> 
> ### Additional context
> _No response_

Can you send me a saved game just before deconstruct? I want to test but I lost my savegame.

**Comment by Rasengetsu** [comment]
You could just debug menu map edit the furniture into existence, I don't have a save right now because I just deleted my world.

**Comment by misterprimus** [comment]
> 

I did but it seems to be working now for some reason.
