### ISSUE TITLE
More canning recipes, for all sizes and needs

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#60625]
### Is your feature request related to a problem? Please describe.

Right now, canning is a mess. Some recipes use small tin cans, some use medium, everything can use 3L glass jars, and *none* of them use large tin cans! My character needs to save food for winter but dangit, they only have medium tin cans and no glass jars... My character could can these fish, if only the tin cans were smaller!

### Solution you would like.

Add new recipes to ensure any canning recipe that uses tin cans has a small, medium, and large recipe.

Nest all the resulting recipes to reduce bloat. (Double nest to distinguish between the set using tin cans+can sealer and the canning pot+glass jars?)

### Describe alternatives you have considered.

A sharp object, three new recipes, and an abjectly poor idea to saw larger tins down to size by reducing their height...

### Additional context

Because of the way canning works IRL, processing time is non-linear. Adding small recipes to all existing recipes that use mediums should be straightforward (if nothing else just copy the medium recipe and substitute small), but 'sizing up' may require much more processing time.

There is a partly government-funded resource available with a wide range of recommended times and sizes ( https://nchfp.uga.edu/how/can_home.html ) but very few items are listed for the half-gallon (roughly equal to 3L glass jar/large tin can) size. Some estimations will have to be made.

**Comment by Zireael07** [comment]
Example why #56326 needs a dev-side fix ;)

**Comment by RenechCDDA** [comment]
Some additional hurdles I've run into:

Offal consumes 2 raw offals (0.5L) but only cans 1 unit (0.25L), despite using a medium sized container (0.5L). Presumably the rest is taken up by the water component (0.25L)?† But half of it disappearing is uh, not desirable. (On further examination this might just be a bug with offal since canned beans, the other medium size tin can craft, seems to properly store 2 units.)

†Assuming that the intention is that the canned food is 50% water by volume, this means that offal can't fit into a small tin can since one unit takes up the entire can.

Canning liver via jars consumes *all* the water - the rest of of the jar-canning crafts return a portion of the water used as clean water. Because you did just boil it.

The portion of returned water is not uniform across crafts that do return it. Canned meat (2 units) uses 11, returns 10. Canned meat (12 units) uses 16, returns... 10. Some boil-off is to a given but this difference is unexpected.

**Comment by RenechCDDA** [comment]
Really, this is done. I implemented the canning recipes shortly after making this issue, and while the nesting was never done I don't think it's a huge issue.
