### ISSUE TITLE
NPC doesn't know what to say for BGSS_RADIATION_2_STORY3 when asked about their story before the cataclysm

### ISSUE THREAD

**Issue by Spacer-1970** [CleverRaven/Cataclysm-DDA#60626]
### Describe the bug

When you talk to a specific npc about their backstory before the cataclysm, they get an error whereby they don't know what to say for their story and just leaves a blank space instead of the story.

### Steps to reproduce

1. Make the npc become friendly whereby you can ask them about their history.
2. Ask the npc about their history before the cataclysm.
3. The error should appear whereby they don't know how to continue their story and it just leaves a blank space.

### Expected behavior

I expected that the npc's story would continue and the error would not appear.

### Screenshots

![Screenshot (270)](https://user-images.githubusercontent.com/92626947/187671136-b3f8370b-1935-470f-be19-9682bc9ec71b.png)
![Screenshot (271)](https://user-images.githubusercontent.com/92626947/187671177-041d5cfa-3e95-4557-9c3e-454f098a11be.png)
![Screenshot (272)](https://user-images.githubusercontent.com/92626947/187671196-8c70e58e-2641-4846-b030-2204bea84739.png)
![Screenshot (273)](https://user-images.githubusercontent.com/92626947/187671205-3c7363a0-0413-43df-9f0c-c4f21d3a938f.png)

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9461192/debug.log)

### Additional context

[user-default-mods.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/9461199/user-default-mods.txt)

**Comment by EIIKaO** [comment]
This BGSS is the Aftershock's and the typos seems to be the cause of the error.
Also, even if there were no typos, the conversation looks still incomplete.
Therefore, simply correcting typos may not be enough to have a satisfactory conversation.
