### ISSUE TITLE
Appliance fridge needs different tools to deconstruct than a normally occuring one

### ISSUE THREAD

**Issue by AzTheProtoGoat** [CleverRaven/Cataclysm-DDA#60624]
### Describe the bug

As title suggests, Appliance fridge reguires a tool with bolt turning 2 to take down, whilst the one you find normally you can take down with the : deconstruct furniture order which does not reguire bolt turning 2

### Steps to reproduce

Go to the appliance, examine, press take down fridge.
Prompts that you're missing a tool with bolt turning 2

### Expected behavior

Expected the appliance fridge to make use of deconstruct furniture tools

### Screenshots

![image](https://user-images.githubusercontent.com/112546133/187636519-23e300a2-ee87-460c-b060-402a88a7c863.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: be8d4ed [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    <color_light_blue>Lighter Weariness</color> [light_weariness]
]

**Comment by a-chancey** [comment]
/confirmed

Honestly, a fridge shouldn't take a wrench to install/uninstall at all. All you do is plug it in.
