### ISSUE TITLE
"Angel Carlisle, scrappe doesn't the appropriate pockets to accept that"

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60637]
### Describe the bug

Can't sell long guns to Angel because she can't fit them in her pockets, which seems weird because she has an entire scrapyard's worth of space.

### Steps to reproduce

Attempt to sell an AR-15 to Angel.

### Expected behavior

Merchants don't base their buying decision on whether they can fit the merchandise in their pants or not.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/187788564-a98f320a-d72e-45ca-bb6f-1aa00ced6086.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: d9451f8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by andrei8l** [comment]
Both scrap traders are defined with `NPC_MISSION_GUARD` instead of `NPC_MISSION_SHOPKEEP` and no shopkeeper item groups or zones so they're not very good merchants.

There was a PR to fix this, but it appears to have stalled: #59805

**Comment by Merikona** [comment]
Should get a chance to work on that PR later this week, which will fix this issue.

**Comment by MNG-cataclysm** [comment]
PR #59805 has been merged, fixing this issue. @Maleclypse I recommend closing this.
