### ISSUE TITLE
DDA needs a tiny pinball game for a pinball machine appliance

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#60644]
### Is your feature request related to a problem? Please describe.

I believe that there is probably an open source 8bit or so virtual pinball game out there somewhere that could be loaded up into Cataclysm and tied to use of a pinball machine appliance.

### Solution you would like.

Exactly what I described above.

### Describe alternatives you have considered.

Pinball Machine appliance that doesn't include a real playable game but does have in game morale effects.

**Comment by sonphantrung** [comment]
I've recently got my hands on Copilot, not sure how well it can handle coding the whole pinball game :D
