### ISSUE TITLE
Distributed Bark can be cut up

### ISSUE THREAD

**Issue by Demivan** [CleverRaven/Cataclysm-DDA#60653]
### Describe the bug

Distributed Bark can cut up and re-generated again giving the player infinite splintered wood :)

### Steps to reproduce

1. Mutate Shifting Bark
2. Cut up bark you are wearing
3. Get 80 splintered wood :) 
4. Activate shifting bark mutation to get a new armor

### Expected behavior

Cutting up own body should damage the player or cutting up should be disabled

### Screenshots

![image](https://user-images.githubusercontent.com/2339406/187925908-394751e4-54bf-4734-b3b1-12a3b19cf401.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 04606aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/64449/files
