### ISSUE TITLE
Removal of gamma globulin shot leaves me with an active syringe I can't turn off

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#60663]
### Describe the bug

I've loaded a save where the PC still has some gamma globulin shots in the inventory.
When I try to sleep, the game prompts me to turn off the `syringe (active)`.
However: There's no way to turn a syringe off (or turn it on to begin with). Or am I missing the big red 'Do **not** push this button' button on it?

#60602 is the PR that removed that item from the game.

### Steps to reproduce

1. Have a save with some gamma globulin shots in your inventory.
2. Update your game to at least `cdda-experimental-2022-09-01-0523`.
3. Load your save.
4. Try to sleep or open your inventory.

### Expected behavior

The game lets me sleep without prompting me to turn off a syringe.

### Screenshots

![Turn off syringe prompt](https://user-images.githubusercontent.com/13157984/188001273-1a644d66-4151-4c93-8c9d-1d0979cc9ad5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 0.F-11019-g9da5d55a2b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Stadler76** [comment]
Trying to load the save also gives me this error:
```
 DEBUG    : Item syringe was loaded with charges, but can not have any!

 FUNCTION : io
 FILE     : D:\Spiele\Git\Cataclysm-DDA\src\savegame_json.cpp
 LINE     : 3040
 VERSION  : 0.F-11028-g3869e2b669
```
Additionally I only get a single syringe.
Additional steps to reproduce (because downgrading/switching the version with the [CDDA Game Launcher](https://github.com/DazedNConfused-/CDDA-Game-Launcher/releases) is also an option):
1. Create a character in a version before `cdda-experimental-2022-09-01-0523`.
2. Add 20 gamma globulin shots to your inventory. e. g. through the debug menu.
3. Save and close the game.
4. Upgrade to `cdda-experimental-2022-09-01-0523` or later.
5. Load the save.

So maybe the migration code just needs a way to 'ignore charges' when migrating?

**Comment by irwiss** [comment]
Most likely was fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/63079 in case anyone has the opportunity to test
