### ISSUE TITLE
Nerf the Combat Knife

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60684]
### Is your feature request related to a problem? Please describe.

We all know the [combat knife](https://nornagon.github.io/cdda-guide/#/item/knife_combat) is really good, but there seems to be less consensus on whether it's too good. Here's why I think it is, in fact, too good:

To start with, the US army [doesn't actually seem to issue soldiers with combat knives](https://www.quora.com/What-is-the-standard-issue-US-Army-knife) these days, so they're probably too common. In as far as they do get knives, it's mostly the [M9 bayonet](https://en.wikipedia.org/wiki/M9_bayonet). The "combat knife" item seems to be loosely based on this knife, as it's the same length and can be attached as a bayonet.

The thing is that the M9 isn't a dedicated fighting knife. It's a multipurpose utility knife, complete with wirecutting functionality and a sawblade. It's a compromise design, which is why it seems weird to me that it deals noticeably more damage than dedicated fighting knives like the [kukri](https://nornagon.github.io/cdda-guide/#/item/kukri), [tanto](https://nornagon.github.io/cdda-guide/#/item/tanto) and [trench knife](https://nornagon.github.io/cdda-guide/#/item/knife_trench). In fact, its damage is closer to certain swords, like the [rapier](https://nornagon.github.io/cdda-guide/#/item/rapier), than it is to most knives.

Those weapons have their own pros and cons, of course, but I just cannot get over the fact that this tertiary utility sidearm is up there competing with actual weapons.

### Solution you would like.

Just drop its pierce damage a few points. I think you could go down all the way to 20, tbh. Maybe do like 22 and make it a bit slower to represent that it's not designed for maximum agility.

### Additional context

Part of the problem here is that the damage range for melee weapons is heavily compressed into the 20-40 range. There's just not a lot of room to make a particularly good knife, because just one or two points of damage too many and it's competing with swords. But that's a problem that would require a much more radical intervention to solve.

**Comment by Terrorforge** [comment]
I just learned you can PR changes like this very easily, so I did.

**Comment by kevingranade** [comment]
Your argument that "dedicated weapons deal more damage than purpose built weapons" does not actually hold up, you need to describe why those other weapons are better.
Given that we discussed this on discord and you were told you needed sourcing for your argument I'm going to close it. If you come up with some sourcing as requested you can open a new issue

**Comment by Terrorforge** [comment]
We have not discussed this on Discord, you must be thinking of someone else. I _was_  reminded to do this by discussion in the Discord, but you and I never talked about it.

Also, I know this is your call so I'm not gonna press the issue, but I have to ask: are there any sources backing up the idea that the combat knife should be doing ~25% more damage than every other fighting knife? Because I feel like the null hypothesis should be that most knives of this size and purpose deal about the same damage, and it's this outlier that needs to be justified with facts and data, not the other way around.

**Comment by Terrorforge** [comment]
Wrote it up as #60766
