### ISSUE TITLE
There aren't enough positive Alpha mutations to breach threshold

### ISSUE THREAD

**Issue by Piddagoras** [CleverRaven/Cataclysm-DDA#60685]
### Describe the bug

During normal play, seeking a safe Alpha threshold crossing, one might use Robust Genetics to only mutate with no genetic damage, and only obtain positive mutations.  There are currently not enough positive mutations to obtain tier 3 dreams nor cross the threshold, however.  

The only workaround (to breach the threshold) once the player has obtained all positive alpha mutations is to intentionally take genetic damage by mutating in a different direction in order to force negative Alpha category mutations.  This is counterintuitive and requires meta-knowledge of how the dreams and threshold system works in order to even recognize that you can no longer gain anything from using Alpha mutagens.

### Steps to reproduce

1. Make a new character with no traits.
2. Debug add all of the positive alpha mutations (to avoid genetic damage)
3. Consume enough alpha primer to activate metamorphosis effect
4. Consume enough mutagenic catalyst to activate warping effect
5. Wait a long time, in which you will neither obtain any mutations from Alpha nor cross the threshold.

### Expected behavior

There should be progress towards the threshold whenever the mutagen is consumed, independently of any genetic damage.  If the player is unable to gain any more mutations from the category, threshold breaching should be possible, regardless of the number of category points.

### Screenshots

![alpha1](https://user-images.githubusercontent.com/5413987/188155679-8cd4e023-17d7-4bda-a684-230921081b87.png)
![alpha2](https://user-images.githubusercontent.com/5413987/188155681-d74e1f57-f785-4305-a51d-78e744f49a8d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: d8ef623 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by vicbrandao92** [comment]
Wouldn't you need very smart/very dextrous too?

**Comment by Piddagoras** [comment]
> Wouldn't you need very smart/very dextrous too?

Those aren't Alpha category mutations.  You can see this in the debug menu, the .json files, or the fact that in the screenshots I'm churning instead of gaining those mutations.

**Comment by vicbrandao92** [comment]
Damn... just as I am trying to get past through alpha threshold.

**Comment by Piddagoras** [comment]
> Damn... just as I am trying to get past through alpha threshold.

Hilariously, I was curious whether two extra mutations would be enough, and so I just added them to the Alpha category in the .json files and it was enough to breach the threshold.  If you were to do this, you'd probably would want to change the pre-reqs on the Prime mutations to use very smart and very dextrous instead of smart and dextrous for consistency, but this isn't a bad workaround (although it requires you to edit your files by hand for now).

**Comment by anoobindisguise** [comment]
Not true, fast metabolism is a beneficial mutation in practice and starting traits do count towards threshold. I've minmaxed a shitton of alpha mutants and gotten pretty consistent at just barely being able to threshold under current rules. With fast metabolism you can breach just fine. (Alpha needs 30 power to breach and each mutation/trait adds 3 + its level, so very strong and perceptive each add 4 instead).
Alpha does need to be fleshed out more and treated more like a regular tree though.

**Comment by Piddagoras** [comment]
> Not true, fast metabolism is a beneficial mutation in practice and starting traits do count towards threshold. I've minmaxed a shitton of alpha mutants and gotten pretty consistent at just barely being able to threshold under current rules. With fast metabolism you can breach just fine. (Alpha needs 30 power to breach and each mutation/trait adds 3 + its level, so very strong and perceptive each add 4 instead). Alpha does need to be fleshed out more and treated more like a regular tree though.

I believe all mutation categories need 30 power to breach, Alpha just has very few positive pre-threshold mutations.

Fast metabolism is a negative trait.  It gives you more stamina, true, but you still can't gain it during mutation without exposing yourself to other significantly worse traits with genetic damage (you can't get genetic damage even if you wanted to if you already have all positive traits for a category, and are forced to use another mutagen type)

If you knew you wanted to go Alpha at creation _**and**_ you knew that Alpha has threshold problems _**and**_ you knew that Fast Metabolism or Junkfood intolerance are manageable traits that will count towards the threshold, then sure, you can minmax. I personally don't think that this is very natural gameplay though.

**Comment by Sevaaas1** [comment]
> Not true, fast metabolism is a beneficial mutation in practice and starting traits do count towards threshold. I've minmaxed a shitton of alpha mutants and gotten pretty consistent at just barely being able to threshold under current rules. With fast metabolism you can breach just fine. (Alpha needs 30 power to breach and each mutation/trait adds 3 + its level, so very strong and perceptive each add 4 instead). Alpha does need to be fleshed out more and treated more like a regular tree though.

I think that an easy and good solution solution would be to shift fast metabolism to either cost 0 points, or to cost 1 point, making it a positive mutation so that its affected by Robust Genetics, because while it does have the trade off of needing more food to survive, it makes combat easier, specially drawn out fights with the stamina regen it provides, food is already plenty specially in cities. Unless you do a innawoods run where food is a bit harder to obtain, which most players wont be doing that, and those who do are likely to already be experienced with the game, and will be able to find different sources of food to not starve

Therefore, if its shifted to positive mutation, there might be enough power to breach into alpha, since it should give a +4 breach strength

**Comment by descan** [comment]
Just an off the cuff idea that probably should be shot full of holes, but what about a third tier of "Neutral" mutations, that you could stick stuff like Fast Metabolism in (that is, traits that could be seen as good or bad depending on circumstance, or that have no gameplay effect) and have those proc on a lower chance*, but not 0 like negative mutations are when genetically stable?

*I started by thinking they should proc only if there are no good mutations left, but most other categories have plenty enough good mutations that they likely don't have this issue - and besides, neutral doesn't mean bad (that's the point, after all) so making them impossible to get until you've used up your Good ones or accrued enough damage would be gimping them rather harshly.

**Comment by Maleclypse** [comment]
Ideally every tree would require negative mutations and positive mutations to cross the threshold.

**Comment by Piddagoras** [comment]
> Ideally every tree would require negative mutations and positive mutations to cross the threshold.

This makes sense and I agree that thematically, you should probably have to have tentacles to cross the squid threshold, for example.  I still think that with the way genetic damage works right now, it wouldn't be unusual for players pursuing mutation categories with Robust Genetics to end up trapped, unable to gain any negative mutations without first using other mutagens to obtain enough genetic damage to proceed (particularly if unfamiliar with the systems, and anxious about trying to mutate with the ominous "genetic damage" effect on their character).  There is no in-game indication that to progress fully into a category and cross a threshold, the player should avoid fully-safe mutation or use another mutagen type so that they can gain negative mutations.

A potential solution would be for genetic damage to occur on the failed mutations where you just churn a little bit, that way a player, even one unfamiliar with how mutation works behind the scenes, may eventually find their way out of the trap by desperately consuming larger quantities of mutagen (in response to the yearning to be free messages) to get a negative mutation or two and then actually cross the threshold.

**Comment by Terrorforge** [comment]
>  it makes combat easier, specially drawn out fights with the stamina regen it provides

The stamina regen portion of Fast Metabolism is completely inconsequential. Regen is such an small part of long-term stamina that a 10% increase is very close to literally nothing. The reason Fast Metabolism has a profound effect on stamina right now is that the increased food consumption effect increases your Base Metabolic Rate, which is tied directly to cardio, and thus stamina. This is (arguably) a bug. If/when #60202 merges, Fast Metabolism will go back to effectively being pure downside.

> Just an off the cuff idea that probably should be shot full of holes, but what about a third tier of "Neutral" mutations

These already exist. Any mutation with a cost of exactly 0 is considered neutral, and you always have a 10% chance of getting a neutral mutation, regardless of genetic damage.
