### ISSUE TITLE
"Active world mods" window isn't wide enough

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#60695]
### Describe the bug

In the window that shows the active world mods, the window isn't wide enough to fit everything. Normally that wouldn't be a problem, but there's also no way to scroll the window horizontally.

### Steps to reproduce

1. Start a new world or load an existing world that has the Bionic Professions mod (`package_bionic_professions`).
2. Press `ESC` then `8` to get to the active world mods window.
3. Note that the Bionic Professions line says `Bionic Professions [package_bionic_...]`
4. Press `?` to see the keybindings menu and note that nothing describes scrolling horizontally.

### Expected behavior

The window should probably be wider or even full screen; there's no reason to use a tiny window on a large screen. However, horizontal scrolling should probably also be added to account for mobile users.

### Screenshots

![cata-mods0](https://user-images.githubusercontent.com/16765166/188225206-a9a9a98c-7f5f-4998-976f-14ffe1eda415.png)
![cata-mods1](https://user-images.githubusercontent.com/16765166/188225248-6b7819a5-3f1e-4854-b20b-caef528a9edd.png)

### Versions and configuration

Linux, last commit is cb944bfe7b5bfbf08296133b7014f412d43d3bbf.

**Comment by Ezrashaw** [comment]
IMHO, horizontal scrolling is not ideal. AFAIK, it doesn't exist anywhere else in the game and could be quite unintuitive. Maybe we could widen that window and hide the `[mod_id]` if it would be offscreen? Also, word wrapping?
