### ISSUE TITLE
Make ponds riskier ( Possibly more aquatic enemies? )

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#60698]
### Is your feature request related to a problem? Please describe.

I think ponds, in any run, are amazing and incredibly convenient to live next to, its basically free source of infinite water (and maybe food) for a survivor, and it also makes a great location for washing clothes. This can be somewhat of a problem in my opinion.  as there's never really any risk in living next to a pond other than giant dragonfly naiads, which can be taken care of quite easily.  I think ponds should be a little more riskier to visit. 

### Solution you would like.

Id consider adding mutant insects, like mosquitoes or wasps, or even amphibians such as mutant frogs near ponds to enhance the risk of heading to a pond for the first time, the fish could even be made into a threat as well. 

I brainstormed some aquatic life that could serve as potential threats to an unsuspecting fishermen.

Pike Charger: What was once an ordinary, somewhat aggressive Northern Pike has transformed into a massive, elongated monster of a fish with rows of serrated teeth.  It seems more than eager to pull you into the water and tear you to shreds.

Snapping Turtle: a regular snapping turtle native to the New England region of the United States. Won't bite at you as long as you leave it alone.

Mutant Snapping Turtle: Clearly has no taste in pizza, but has one for human flesh. This once territorial snapping turtle has become significantly larger, about the size of a large dog. its shell warped and discolored, with dilated pupils that stare at you with malice.

**Comment by Xaritscin** [comment]
I think the deal with ponds is that they are supposed to be more tame aquatic spots compared to rivers/lakes. at best you have a chance to find an aquatic bug.

I think the condition here should be to up the chance to find toads/frogs/naiads or other aquatics that will grow into mutant variations.

as for the Snapping Turtle thing. TropiCataclysm has them on mod as a generic nondescript species. it could be mainlined in a PR seeing that according to Discord there's at least 1 species of them living in New England. there's no baby variation or mutant variant though.

**Comment by Karol1223** [comment]
I fully agree that ponds should be far tamer as the fish that'd grow into dangerous predatory mutants wouldn't really live there 9/10 times. Dragonfly naiads, toads, frogs, possibly the snapping turtle if it passes the mainlining process and _maybe_ some sort of salamander? Mutant pike works perfectly fine for rivers and larger lakes, alongside the (ones mentioned on Discord a few times during brainstorming) mutant eels or catfish but that's beyond this issue's scope.
