### ISSUE TITLE
Recent Windows builds are failing

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#60712]
### Describe the bug

Recent windows builds with Visual Studio are failing. The most likely cause is #60191.

### Steps to reproduce

1. Checkout the latest version, being 66746d1e9c84d522739c3acdbf9332e740f7c5e7 at the time of writing.
2. Fire up Visual Studio and hit 'Build solution'

### Expected behavior

It compiles without issues.

### Versions and configuration

- OS: Windows 10

### Additional context

Examples of failed builds:
- https://github.com/CleverRaven/Cataclysm-DDA/runs/8165732777#step:13:812
- https://github.com/CleverRaven/Cataclysm-DDA/runs/8166106202#step:13:814
- https://github.com/CleverRaven/Cataclysm-DDA/runs/8166520616#step:13:812

**Comment by mqrause** [comment]
It compiles fine for me. But looking at the error `error C2079: 'TranslationPluralRulesEvaluator::ExprNode::children' uses undefined class 'std::array<TranslationPluralRulesEvaluator::ExprNode *,3>'` I guess `translation_plural_evaluator.h` is missing `#include <array>`.

**Comment by DPavonis** [comment]
Tiles builds compile fine, but NoTiles builds are consistently failing on my end.
