### ISSUE TITLE
Tile for ap_foodco won't apply

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#60722]
### Describe the bug

The appliance version of FOODCO kitchen buddy's tile basically won't apply even when the tileset has a config for `ap_foodco`. It uses `f_sink` or `&` instead.

### Steps to reproduce

1. Make a world.
2. Spawn a FOODCO kitchen buddy.
3. Place a FOODCO kitchen buddy as an appliance.

### Expected behavior

The tile for appliance version of FOODCO kitchen buddy won't fallback.

### Screenshots

![20220903_205808](https://user-images.githubusercontent.com/52661206/188269459-7a643997-12b1-4651-952f-10c78509d3b5.jpg)
(used Undeadpeople Tileset.)
(Note that the left one is on vehicle, and the right one is the appliance version)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G950N; Release: 9; Incremental: G950NKSU5DVG2; 
- Game Version: 0cf3d9f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I tried using `looks_like` for the `ap_foodco` and it somehow worked.
Anything else would just fallback to `f_sink` or `&`.

It's driving me insane.

**Comment by FayFlightee** [comment]
confirmed. What the hell happened?
