### ISSUE TITLE
Pupating brute healing level makes him undefeatable 

### ISSUE THREAD

**Issue by Farmabear** [CleverRaven/Cataclysm-DDA#60720]
### Describe the bug

each turn pupating brute healh himsef for about 40 HP per turn 

### Steps to reproduce

1. make steel tube spear
2. steay behind prison bars
3. hit pupating brute 

or load save 

### Expected behavior

pupating brute shoud be dead after 1000 dmg in 30m 

### Screenshots

![image](https://user-images.githubusercontent.com/51384409/188267440-a05fe6aa-ead0-4be2-9eaa-d9fbb27b70fa.png)

### Versions and configuration

build type: windows-tiles-x64
build number: 2022-09-02-2035

### Additional context

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9482426/save.zip)

**Comment by a-chancey** [comment]
That image didn't give any real details as to your stats, but here's my take:

A pupating brute regenerates 10hp per turn, and has 120 hp and 4 stab/4 bash armor. 

I'm assuming the weapon is either a basic or regular pipe spear. Assuming best case is regular pipe spear, that's 8 bash/29 pierce (~4 and 25 after pupating brute's armor) and a -1 to hit. It takes 147 moves to attack. The average survivor has 100 speed, so this means they will get 2 attacks every three turns - for a few swings. When your stamina drops, so does your speed, and this quickly becomes 2 attacks per 4 turns. 

-1 to hit means you're going to miss a considerable amount. That means you might only be hitting the monster 0-1 times of every 4 turns, at which point it would have healed 40hp. 

Pupating brutes are later game monsters and a pipe spear is an early game weapon. I'd say it's working as intended

**Comment by Farmabear** [comment]
> That image didn't give any real details as to your stats, but here's my take:
> 
> A pupating brute regenerates 10hp per turn, and has 120 hp and 4 stab/4 bash armor.
> 
> I'm assuming the weapon is either a basic or regular pipe spear. Assuming best case is regular pipe spear, that's 8 bash/29 pierce (~4 and 25 after pupating brute's armor) and a -1 to hit. It takes 147 moves to attack. The average survivor has 100 speed, so this means they will get 2 attacks every three turns - for a few swings. When your stamina drops, so does your speed, and this quickly becomes 2 attacks per 4 turns.
> 
> -1 to hit means you're going to miss a considerable amount. That means you might only be hitting the monster 0-1 times of every 4 turns, at which point it would have healed 40hp.
> 
> Pupating brutes are later game monsters and a pipe spear is an early game weapon. I'd say it's working as intended

Thx fot explain and maths, seems that you are right. Closing ticket
