### ISSUE TITLE
Survivors can use reach attacks diagonally

### ISSUE THREAD

**Issue by AzTheProtoGoat** [CleverRaven/Cataclysm-DDA#60721]
### Describe the bug

As we know, our survivor can only reach 1 tile away while attacking diagonally using reach attacks. However when we give an NPC a weapon with reach capabilities (Bill in this example, as that's what my NPC survivor is using as of right now)
Then she's able to do reach attacks diagonally.

### Steps to reproduce

1. Get a friendly NPC, make them use a weapon with reach 
2. Position them in a way that an enemy is positioned diagonally
3. NPC proceeds to do the reach attack

### Expected behavior

I expected the NPC to be able to only reach 1 tile away, knowing how reach attacks work when we wield a reach weapon. 

### Screenshots

![image](https://user-images.githubusercontent.com/112546133/188268427-25f6e24c-7f08-4ea2-9f91-7999c67c4445.png)

![image](https://user-images.githubusercontent.com/112546133/188268441-32cb9a2a-9863-448d-b951-60482a9354bd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 02a1199 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    <color_light_blue>Lighter Weariness</color> [light_weariness]
]

**Comment by lightinthefog** [comment]
does this happen with circular distances turned off?

**Comment by AzTheProtoGoat** [comment]
It happens with them being on

**Comment by lightinthefog** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/36232
this pull addressed it in 2019, but it is possible that npcs are still using square distances for the attack check even if the player is using a different one

**Comment by AzTheProtoGoat** [comment]
that's most likely the case then
