### ISSUE TITLE
Watches are uncomfortable to wear on bare skin.

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#60733]
### Describe the bug

Watches seem to be marked as uncomfortable to wear unless you have gloves. Anyone who wears a watch especially if they never take it off will know this isn't true.

### Steps to reproduce

1. Make sure you aren't wearing anything on your hands.
2. Equip a wristwatch or any of it's alternatives (fancy watch, diver's watch, etc.)
3. Press @ and view the effects active on your character, see the "uncomfortable (left/right hand" effect on you.

### Expected behavior

A watch should be comfortable to wear on it's own. It seems that the game considers it armor.

### Screenshots

![image](https://user-images.githubusercontent.com/56202842/188288164-2aa48ab3-4f88-444d-b76b-ff957a33c8c3.png)
A watch, worn with nothing else.
![image](https://user-images.githubusercontent.com/56202842/188288187-9fcc0475-926f-4b03-bda8-269bb2a5a0fd.png)
The status effect, visible from the @ menu.

### Versions and configuration

- OS: Windows 10 Version 1909
- Game version: e853744 Experimental build 2022-09-03-1643
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [
Dark Days Ahead [dda], 
Disable NPC Needs [no_npc-food],
No Fungal Growth [no_fungal_growth]
Bionic Professions [package_bionic_professions],
Magiclysm [magiclysm],
No Rail Stations [No_Rail_Stations]
]

**Comment by anoobindisguise** [comment]
Sometimes wearing a watch can get irritating because of how sweat can get trapped under it, but that's a property of anything that doesn't breathe so this does seem a little unintended.

**Comment by snipercup** [comment]
I had this issue with both the watch and the headlamp. I think it shouldn't be uncomfortable.

**Comment by Consoleable** [comment]
I'm also having this issue with rings, and also the rings from Magiclysm as well

**Comment by Doitallornot123** [comment]
This may be a bad guess, but i noticed the JSON armor flag "padded" says: "This armor counts as comfortable even if none of the specific materials are soft." I imagine most jewelry lack this tag and are made of metals or plastic. This would make them uncomfortable to wear unless there is something padded or made of soft material below it, like gloves.

**Comment by Daved27hundred** [comment]
> This may be a bad guess, but i noticed the JSON armor flag "padded" says: "This armor counts as comfortable even if none of the specific materials are soft." I imagine most jewelry lack this flag and are made of metals or plastic. This would make them uncomfortable to wear unless there is something padded or made of soft material below it, like gloves.

so, all that's needed is to add the padded flag to watches?

**Comment by propurty** [comment]
I'm having the same issue with a lanyard but for the torso. Doesn't actually matter if I put comfortable clothing under it either. So yeah, definitely something wrong going on.
