### ISSUE TITLE
New "Sets" Category in Armor Crafting Tab

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#60741]
### Is your feature request related to a problem? Please describe.

As part of my continued work towards nesting armors, I would like a "SETS" category to be added to the armor section of the crafting menu.  This "SETS" tab would contain ONLY NESTS and would be the broadest overview of each individual set of craftable equipment in the game.

For example, a nest there could look like this.
![image](https://user-images.githubusercontent.com/52714184/188298619-cde3b627-3700-46c0-9984-124fa649c3f4.png)

To clarify, this would not remove ANY NESTS from other categories, it would just provide the player with a very broad level overview if they just want to see what they can make in any given set.

### Solution you would like.

I'm unable to spend the time to learn C++ right now, so if this isn't doable in JSON anyone who wants to help me out would get huge kudos from me.

### Describe alternatives you have considered.

Remaking the entire crafting menu, but I'm not going to do it, and I have no idea when/if it will ever be done.

**Comment by chrispikula** [comment]
So what category would the 'sets' be in?  Would you make a new armor category, to go with head/legs/feet/torso, etc?

**Comment by ANickelN** [comment]
That's exactly the idea, that there would be a new category.  The route you're describing to pick chitin armor is what is displayed in the image I posted.
