### ISSUE TITLE
More military combat knives

### ISSUE THREAD

**Issue by Altogolik** [CleverRaven/Cataclysm-DDA#60749]
### Is your feature request related to a problem? Please describe.

Now in the game there are few knives that can be found in the military, we need more options for the interest of the game, I would be very interesting to find new rarer variants, not just m9
In real life, many military personnel change their knives and use other more appropriate options.

### Solution you would like.

I want the game to have rarer and more powerful versions of combat knives, so they are different
need cool knives at the end of the game (A few examples)

Ontario MK 3 Navy Knife (not a big but very dangerous knife is great for killing)
https://i.gyazo.com/a0b10135e307da1fcfb1812410a49011.jpg

Fairbairn-Sykes (Legendary British Knife)
https://i.gyazo.com/0785e0042118f49fc7c8682fd7b4e9af.jpg

Gerber Mark II (Commando’s Knife)
https://i.gyazo.com/799b9efd923da2189ccd6a3383eeb495.jpg

Cold Steel Recon Tanto (variation of Japanese knife)
https://i.gyazo.com/4bd7abb0cb147cdf756539af5a46b4b6.jpg

Boker Applegate-Fairbairn (Excellent stealth knife)
https://i.gyazo.com/b6053f381d19007ae1f6722d7eef2873.jpg

Glock 78 \ 81
https://i.gyazo.com/63ef0a8f9f79da5bf486672b4af42d58.jpg

TROIKA KNIFE (modern very sharp knife perfect for killing, the metal is very strong allowing for a sturdy blade with dangerous stabbing damage)
https://i.gyazo.com/0198cb3c2327e46a06dc5059a4e2e091.png

### Describe alternatives you have considered.

More combat knives more

**Comment by GuardianDll** [comment]
Good idea, but do you know what the probability a common US soldier would equip a japanese tanto knife? or british one?
So they must be made with meaningful probability
Also the good way woudl make them as `variants` of common combat knife item

**Comment by Zireael07** [comment]
@GuardianDll Tanto knives could be around in dojos, not soldier drops

**Comment by Altogolik** [comment]
@GuardianDll British knife can be added as an antique (it is very popular) and tanto, yes in the dojo, and the military too (it is a modern knife, not original, it is made in many places)
Cold Steel is an American company.

**Comment by GuardianDll** [comment]
Well, then i see no problem

**Comment by Altogolik** [comment]
In fact, the Gerber Mark II is a more modern version of the British Fairbairn-Sykes (if the British one is not suitable, you can keep the Gerber)

**Comment by estebandellasilva** [comment]
Should Police Stations have a chance to spawn one of those lillegal knifes where you cannot patch up the wounds?
Like the Jagdkommando Tri Dagger or the Wasp Injection Knife

**Comment by GuardianDll** [comment]
Yes

**Comment by Altogolik** [comment]
@estebandellasilva I don't know about adding the Wasp Injection Knife, how do you imagine refilling the gas ? (That would be very inconvenient) Only if you ignore that and make the gas infinite.
The police can confiscate the Jagdkommando knife and it makes sense that it would be there.

**Comment by estebandellasilva** [comment]
They seem to use cartridges - since weapons can already used batteries this would not be a problem ... maybe we can even add whipped cream because they look similar to those used in thise whipped cream makers

https://blade-city.com/blogs/gun-knife-blog/wasp-injection-knife#:~:text=On%20Wasp%20Injection%2C%20the%20knife's,the%20world's%20largest%20land%20predators.
