### ISSUE TITLE
Nested categories are always shown up top

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#60742]
### Describe the bug

When checking the crafting menu, nested recipes are always shown up near the top of the menu as they don't require anything to craft and are always "craftable" (in reality you are just opening the menu further).

### Steps to reproduce

Open up the crafting menu, debug all recipes and see the massive spam of nested recipes up top.

### Expected behavior

If you are unable to craft anything in that nested group, it should turn dark like a standard recipe and not be near the top.

### Screenshots

![image](https://user-images.githubusercontent.com/52714184/188298769-5951ef51-8b04-40d2-84c8-7ac40ea293f2.png)

**In this picture, ideally the socks and t-shirt would be at the top, as I can ACTUALLY craft them.**

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: c968cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungus [No_Fungus],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

I'm not sure this is easily fixable, but I figured I would make an issue for it anyways.

**Comment by PatrikLundell** [comment]
I agree it's a worthy goal to have nests indicate whether they contain anything craftable or not.

**Comment by RelMayers** [comment]
Nice, someone didn't do proper testing on PR Again.

**Comment by snipercup** [comment]
#60683 helps but you're right. they should be colored and only the recipes and categories you can actually craft should be on top

**Comment by bombasticSlacks** [comment]
I'm pretty sure #60683 fixes this entirely. It determines lf the nest is "craftable" now based on if you can craft anything in it and color coordinates them similar to other crafts. So just like anything else it is sorted based on rules from the availability data structure. 

Someone other than me should load an up to date copy of the game and try to confirm this.

**Comment by ANickelN** [comment]
Fixed by #60683
(Sorry, I hadn't updated at the time)
