### ISSUE TITLE
cant wear clothes 

### ISSUE THREAD

**Issue by reeiDELGADO** [CleverRaven/Cataclysm-DDA#60748]
### Describe the bug

unable to wear any clothes on NPC

### Steps to reproduce

I don't know why and how it happened

### Expected behavior

expected to be able to wear clothes on NPC 

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2102J20SG; Release: 11; Incremental: V12.5.1.0.RJURUXM; 
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Бионические профессии [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Альтернативные символы карты [alt_map_key],
    Whaleys Hair Mod [WHALEYHAIR1],
    Характеристики за навыки [StatsThroughSkills]
]

### Additional context

VERSION: 0.F-3
Signal SIGSEGV: Segmentation fault
STACK TRACE:
# 4: 0x79abf70638 __kernel_rt_sigreturn
# 5: 0x78b7a7257c player::sort_armor()
# 6: 0x78b7d98364 game::npc_menu(npc&)
# 7: 0x78b7aa82b0 avatar_action::move(avatar&, map&, tripoint const&)
# 8: 0x78b7e183d4 game::handle_action()
# 9: 0x78b7d793f8 game::do_turn()
#10: 0x78b80996d4 SDL_main
#11: 0x78b964b5f0 Java_org_libsdl_app_SDLActivity_nativeRunMain

**Comment by NetSysFire** [comment]
This is missing lots of vital info. In order to be able to reproduce you need to give us proper steps to reproduce and potentially also a save.
