### ISSUE TITLE
Spells durations should be human readable instead of in ticks

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#60753]
### Is your feature request related to a problem? Please describe.

Most other locations in json have moved to days, hours, minutes, seconds but spell durations are still exclusively in seconds.  I've basically memorized how many seconds are in a day now and try to grasp how long something will last as a fraction of that number.  This is probably ridiculous when we are talking about new contributors. 

### Solution you would like.

Exactly as it's performed in effects durations.

### Describe alternatives you have considered.

We could use the Starstruck universe timekeeping and talk about nargon's and what not.

**Comment by Maleclypse** [comment]
@GuardianDll let me know if I've missed anything.

**Comment by GuardianDll** [comment]
Spells duration inside the json is writed in ticks (ie 100 means 100 ticks means 1 second)

**Comment by Maleclypse** [comment]
> Spells duration inside the json is writed in ticks (ie 100 means 100 ticks means 1 second)

Probably means I've misjudged all my times recently/forever.

**Comment by GuardianDll** [comment]
Ouch

**Comment by GuardianDll** [comment]
And for learning info (random discord image) 
![unknown-149](https://user-images.githubusercontent.com/67688115/188720960-8f14224b-4826-4edf-91dc-c81342d3d1b4.png)
