### ISSUE TITLE
Sun Mage attunement perk applying double the intended perception bonus

### ISSUE THREAD

**Issue by DuraiPapers** [CleverRaven/Cataclysm-DDA#60771]
### Describe the bug

The Sun Mage perk is intended to be giving +5 perception, in practice it's increasing base perception by 5 and applying a permanent +5 buff, totalling 10

### Steps to reproduce

1. Create a new world with Magiclysm enabled
2. Reveal the map tile using debug mode, find an attunement altar or reset the world if there isn't one
3. Debug any Magus and Kelvinist book/scroll so you can get their associated traits
4. Debug any 2 Magus and Kelvinist spells to level 15 
5. Teleport to the attunement altar, attune yourself to be a Sun Mage
6. Initially your perception will be +5 base, if you take a single step the buff will kick in and you'll be at +10 forever

### Expected behavior

Expected that you'd be either receiving the base perception buff OR the permanent buff, but not both. 

### Screenshots

![bugreport](https://user-images.githubusercontent.com/112840972/188356711-43edce73-e2e8-4aac-b2d9-33e498bf4aeb.png)

### Versions and configuration

d060cb9

### Additional context

Character in the screenshot has 7 base perception, for the sake of posterity.

**Comment by GuardianDll** [comment]
Good spot
For the future, you can debug attunement directly, same as kelvinist and magus classes
/confirmed
