### ISSUE TITLE
Crash due to inventory management bug 

### ISSUE THREAD

**Issue by Ge4ok** [CleverRaven/Cataclysm-DDA#60778]
### Describe the bug

I've put M4A1 into Double leather rifle case from the ground + like 50 bullets of 5,56 NATO caliber. As soon as I did it the game crashed and now I no longer have an option to play cause the game crashes instantly. Also, i was overburdened, however don't know if that's the case. 

### Steps to reproduce

1. Take M4A1 + ammo 
2. Take Double Leather rifle case 
3. Put the stuff into the case
4. Receive crash and have no way to play the game after 

### Expected behavior

That the stuff I put into the case won't crash the game 

### Screenshots

![image](https://user-images.githubusercontent.com/96683895/188411960-4a540b35-15d0-41fe-980e-ca072bbdfcfa.png)
![image](https://user-images.githubusercontent.com/96683895/188412000-4561c94b-f4a9-4a9c-9d7d-13427df57950.png)
![image](https://user-images.githubusercontent.com/96683895/188412015-4f568452-5c47-4fc5-9614-1a9c24961d90.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9488453/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9488454/debug.log)
[Holliday.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9488471/Holliday.zip)

**Comment by Computer-Engineer-Man** [comment]
I attempted to reproduce the bug and I was unable to. Are you still able to reproduce the bug?
