### ISSUE TITLE
Bionics usage costs no time.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#6077]
A lot of the bionics have no time usage while they should have.

Simply adding:
moves -= x;
To the if statement in the bionics.cpp file should help.
With x being the time uses in int. (100 is one normal cata turn).

These bionics do not have a time cost when activated:
bio_painkiller
bio_nanobots
bio_night
bio_resonator
bio_teleport
bio_blood_anal
bio_blood_filter
bio_lighter (The finger flamethrower)
bio_leukocyte
bio_geiger
bio_radscrubber
bio_adrenaline
bio_claws
bio_blade
bio_emp
bio_hydraulics
bio_magnet
bio_flashbang
bio_shockwave

Think a few of these should have some time cost. Not sure how much. Or which ones however.
##

**Comment by illi-kun** [comment]
Move cost to some of the listed bionics were added by @Coolthulhu in #17317.
