### ISSUE TITLE
Dialogue condition for contested rolls

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#60773]
### Is your feature request related to a problem? Please describe.

I'd like to see dialogue conditions expanded to allow contested rolls.  This would allow us to create some random chance in areas of skill and stats in a way that probably replicates hacking and lockpicking but makes them expandable in a much more jsonized fashion than currently.

### Solution you would like.

I'd like to be able to select a skill and a stat and then roll them against a difficulty.   I'm open to how the math actually works but one example I'm envisioning is if the chosen skill and stat were combined and that was rolled as a percentage against the difficulty.  I'm not sure if that provides enough range for an average success rate maybe it could be theoretical +practical + stat all times 100 against difficulty times 100.  

Ideally the player would be able to see their chance of success before deciding.

### Describe alternatives you have considered.

Any other math that makes sense would also work.  Could do skill/stat against difficulty level as an option too instead of it being skill+stat against difficulty.

**Comment by Maleclypse** [comment]
@Ramza13 I didn't want to tag you late at night but I was thinking this might be something that you would be interested in potentially adding for it's impact in the EOC system?

**Comment by Ramza13** [comment]
So I think you could probably do a super complicated expression to do this now.  That said I don't mind adding something to make is simpler.  What is the math for this?  Just random number between 0 and skill level, check if its higher than x?

**Comment by Maleclypse** [comment]
I think that could work.  I'm wanting to make something like
```
"examine_action": {
      "type": "effect_on_condition",
      "effect_on_conditions": [
        {
          "id": "EOC_KEYPAD",
          "condition": { "u_has_skill": { "skill": "deduction", "level": 1 } },
          "effect": [
            { "u_roll_contested": { "u_val": "deduction" }, "difficulty": 4 },
            { "u_message": "You are able to figure out the code to the keypad from nearby clues.", "popup": true },
            { "u_transform": { "terrain_transform": "t_keypad_door_locked", "t_keypad_door_unlocked } }
          ],
          "false_effect": {
            "u_message": "The control panels' screen flashes before displaying \"UNAUTHORIZED\" in bold red letters.",
            "popup": true
```

I've probably jacked up all the object names above but I hope that conveys what I'd like to be able to do?
