### ISSUE TITLE
Random error in test suite from itemgroup tests

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#60784]
### Describe the bug

ERROR : src/item.cpp:1495 [ret_val<void> item::put_in(const item &, item_pocket::pocket_type, const bool)] tried to put an item (hd_tow_cable) count (1) in a container (backpack) that cannot contain it: pockets unacceptable because item is too long, item is too short, or pocket is holding too much weight6.102 s: shot_features

### Steps to reproduce

Run tests hit random seed that tests this itemgroup in this fashion.

### Expected behavior

Tests pass

### Versions and configuration

current test suite as of 9/5/22

**Comment by mqrause** [comment]
Probably also #59873

**Comment by casswedson** [comment]
definitely a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/59873 the comments in the issue point out this exact error in previous ci runs
