### ISSUE TITLE
"Bad tag" error when activating "Report PE012/08-178"

### ISSUE THREAD

**Issue by MrDraMaster** [CleverRaven/Cataclysm-DDA#60794]
### Describe the bug

Activating the "Report PE012/08-178" item causes two "Bad tag" errors, one for `<bold>` and one for `</bold>`.

### Steps to reproduce

1. activate "Report PE012/08-178"

### Expected behavior

The text is shown without any exceptions getting thrown.

### Screenshots

![one](https://user-images.githubusercontent.com/37799858/188513888-ceaa4aca-be38-48c7-9912-cc6c7fd84a7c.PNG)
![two](https://user-images.githubusercontent.com/37799858/188513894-1f3c4c36-6a6e-447c-bf05-fa2ca4927d32.PNG)
![three](https://user-images.githubusercontent.com/37799858/188513897-f8014fe5-f422-4793-8cc3-30c0542aa3e2.PNG)
![four](https://user-images.githubusercontent.com/37799858/188513906-c03393fc-b06a-48d8-8e06-2501c5174265.PNG)
![five](https://user-images.githubusercontent.com/37799858/188514150-b6abbaf2-0a00-4c40-b695-39892115a05b.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 324793f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

looking at `data/json/snippets/lab.json`, all four snippets between line 192 and 214 have a set of `<bold></bold>`

**Comment by casswedson** [comment]
/confimed
other than in code there aren't any other similar uses of these tags, probably just someone hoping to get more complex text rendering in item descriptions, anywhere really, it would be nice

**Comment by casswedson** [comment]
/confirmed ah yes I don't know how to use the thing I implemented

**Comment by Venera3** [comment]
It definitely did change the color slightly (to cyan, IIRC), but it didn't bold even when I did them. Oh well, I'll go scrub them.
