### ISSUE TITLE
No Medium Steel Plate Armor for Big Boys and Girls

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#60798]
### Is your feature request related to a problem? Please describe.

While translating the absolute mind numbing amount of steel armor options, I realized that somebody missed adding an XL medium steel option to all three types of plate armor (light, normal, heavy).

This is despite the fact that there is apparently a faction camp crafting recipe for it (if one was to test it, I'd be pretty sure it would not ouput anything)

### Solution you would like.

While it's perfectly understandable that something got missed amongst that unholy mess, it'd be desirable if only for the sake of conformity to have those 3 armor options added (and appended to the proper nested categories).

### Describe alternatives you have considered.

Not allowing XL mutants to wear medium steel plate armor I guess? I mean most people don't go for medium anyway but still.

### Additional context

Like disclaimed before, I haven't actually gotten into the code myself to check this out, and this could just be some Transifex weirdness, if it is, then my most sincere apologies.

**Comment by Computer-Engineer-Man** [comment]
I went into the game and it seems that there are XL variants for the medium steel plate armor.

**Comment by sadenar** [comment]
Then this may instead be an issue of them not getting extracted for localization then, because there is most definitely no XL variant for it on Transifex, which may indicate that it is not getting translated.

**Comment by Computer-Engineer-Man** [comment]
![image](https://user-images.githubusercontent.com/115521142/197549596-5bf3e3e6-48c1-4f74-9887-73445483edcc.png)
I was mistaken, it's under the category but it's mild steel not medium steel. Yet when I took a deeper look into the code it seems that XL mild steel plate armor is actually the medium steel plate armor's as shown below.
![image](https://user-images.githubusercontent.com/115521142/197550888-7ab5914b-e991-4f9a-b6e3-85da60c078b4.png)
It seems this is a name bug, it is actually in the game but named wrongly.
