### ISSUE TITLE
Batch Crafting, Error Message and Crash

### ISSUE THREAD

**Issue by mny3020** [CleverRaven/Cataclysm-DDA#60804]
### Describe the bug

Whenever I try to batch craft any item, the game crashes.  Only occurs when crafting in base area.

### Steps to reproduce

Batch Craft any Item, receive error message, crash

Error Message:
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: e2e7914
TYPE: St12length_error
MESSAGE: basic_string::_M_create

(For background, my base is kind of set up as a pack rat, Lots of Loot Zones, and 4 NPC Followers.  Crashes, with all loot zones disabled/enabled, with followers present/gone. There are a lot of items in the base, which may or may not be reason for the crash.)

crash.log & debug.log attached

### Expected behavior

Go into crafting menu, press b, batch craft items as usual.

### Versions and configuration

Os: Windows 10
Game Version: Experimental: 2022-09-06-0724
Graphics: Tiles
Ingame Language: English
Mods Loaded: DDA, Disable NPC Needs, No Fungal Growth, Bionic Professions, Blaze Industries, Magiclysm, Alternative Map Key, Extra Mutated Scenarios, Mythical Martial Arts, Translate Complex Dialogue, Sees-player icon, sees-player (run,crouch bleed, etc..)

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9495244/config.zip)

**Comment by KHeket** [comment]
I try to batch craft purifed water and have simular crash

**Comment by OnTheDouble** [comment]
Same thing, "short cordage piece" for me.
![crash-report](https://user-images.githubusercontent.com/82908191/188654156-ac6f532c-efed-4c1d-a000-0a828fa1ff75.png)
[Moark.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9497626/Moark.zip)

**Comment by OnTheDouble** [comment]
But food batching works? Okay...
![2022-09-06_17-39-00](https://user-images.githubusercontent.com/82908191/188663984-bf5f2988-f267-491e-9f12-a6f71b9d718f.png)

**Comment by leoCottret** [comment]
It must be because of the number of items, I tried to craft a batch of hide bags with 50 raw hides lying around, no problem, then with 1200 it crashed

**Comment by OnTheDouble** [comment]
My short cordage pieces were available in huge quantities because I had raided a farm and had ridiculous amounts of straw and such. I guess you might be right.

**Comment by latogato** [comment]
It not working with clean water. I tried to craft it with fire, cofeemaker, water purifier, next to a pond or a water in a jug. Sometimes it just freeze, but most of the time it crash with the same error message you inserted above. It crash after i press 'b', so i don't see the batch list.

**Comment by KurzedMetal** [comment]
I had this happen on experimental 09-06-1356 too in a pristine world / char created today.

**Comment by Zachert45** [comment]
Can confirm that its some special condition, Have not found a pattern yet in testing but the error also seems to cause auto-failure on single crafts as well until you stop the craft, after that the single craft completes as normal, this may be tied to the bulk crafting issue as even when testing bulk afterwards it still causes crashing going to try and revert a build or two to see if the issue still exists, should help narrow down that at least.

**Comment by ZeroInternalReflection** [comment]
Based on my own testing, it's not item quantity or recipe-specific, but instead based on the current subcategory.  The 'favorite' and 'recent' subcategories will crash, while the same recipes on the same save in their main category will not crash.
It looks like the indentations from nested crafting recipes don't get cleared when going to batch, and the mismatch causes a crash on small subcategories.
![Screenshot from 2022-09-06 12-01-21](https://user-images.githubusercontent.com/89038572/188682556-2fc81739-e4dc-4491-9d51-c57124f07082.png)

I've done some preliminary testing on @OnTheDouble 's save above and:
1. It crashes when attempting to batch something from the 'favorite' or 'recent' subcategories
2. It does not crash when attempting to batch short cordage pieces from "Other", though the indentation is wonky.
3. It does not crash, and has proper indentation after making the following change:

```
--- a/src/crafting_gui.cpp
+++ b/src/crafting_gui.cpp
@@ -1368,6 +1368,7 @@ const recipe *select_crafting_recipe( int &batch_size_out, const recipe_id goto_
                     current.push_back( chosen );
                     available.emplace_back( chosen, i );
                 }
+               indent.assign( current.size(), 0 );
             } else {
                 static_popup popup;
                 auto last_update = std::chrono::steady_clock::now();

```

![Screenshot from 2022-09-06 12-04-36](https://user-images.githubusercontent.com/89038572/188683601-dcc8f21e-0bfc-47ca-b538-fdce81c6d7a5.png)

I won't be able to write up/fully test a PR for a bit, but it _looks_ like a simple fix

**Comment by OnTheDouble** [comment]
Hey nice. I didn't realize it's about Recent or Favorite. Seems so obvious when you pointed it out.

@bombasticSlacks might have an insight since they are doing a lot of good work on nested crafting right now. Not sure if that would be appropriate to tag people here but oh well.

**Comment by bombasticSlacks** [comment]
yeah I didn't extensively test batch crafting, the indentation for sure might be messing with it or causing out of bounds issues. If it's an easy fix someone just has to PR it 😄
