### ISSUE TITLE
Fixing Atomic Coffee!

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#60816]
### Is your feature request related to a problem? Please describe.

Honestly I'm making this to probe some people for some feedback. The atomic coffee has been a hot topic, with some people wanting it removed, others wanting it to stay, others just not caring. 

### Solution you would like.

Hear me out: We already have a sketchy atomic-related drink, atomic energy drink. It's not as dumb as atomic coffee, as this ~~offbrand Bonk!~~ energy drink can't be made, and the power of the atom is more than likely a marketing gimmick. This would allow for atomic coffee to still be used in some niche roles. How would this new atomic coffee be made? By replacing the water with atomic energy drink of course! This would also require the stim level of atomic coffee to be bumped, as currently the atomic energy drink is more potent than atomic coffee. 

### Describe alternatives you have considered.

Deadass just adding Bonk! Atomic Punch! or something similar to Crazycata

**Comment by chrispikula** [comment]
Current context for atomic coffee:
#60765

**Comment by Computer-Engineer-Man** [comment]
The PR mentioned by chrispikula was merged and seems to address this issue at least partially.
