### ISSUE TITLE
Nested recipes show all recipes, even unlearned ones 

### ISSUE THREAD

**Issue by Torbenbeta** [CleverRaven/Cataclysm-DDA#60810]
### Describe the bug

With the new scroll-able nested recipe sub categories introduced in pull request #60761 ,  the nested category shows all recipes of the nested group, even unknown ones.
E.g. a new character with zero skills has access to the nested group maces (in weapons, primary skill fabrication 1 needed)
Upon expanding the nested group, all mace-recipes are shown (morningstar [at fabrication 6], bronze mace [at fab 5], ...), even though the character should not know them. The same happens with all other nested groups.

### Steps to reproduce

1. Make a new world with a new character without skills and/or proficiencies.
2. scroll through the crafting menu and expand a nested group
3. See all recipes belonging to the group

### Expected behavior

I expect that the menu shows only the recipes known to the character. It should behave as the other recipes not in nested categories, showing known recipes and hiding the others.

### Versions and configuration

OS: Linux Mint
Game Version: build from 2022-09-06  19532fe9559c897722da0976625428269cf18ab2
Graphics: curses
Ingame language: English
mods: [dda], [no_npc_food], [no_fungal_growth], [package_bionic_professions]

**Comment by FalloutFalcon** [comment]
This is still a issue and you can create these unlearned recipes as well. If you then drop these items the game will not let you finish them.

**Comment by l29ah** [comment]
Repro: https://tinystash.undef.im/il/2BN1jTMBoqN1RfUrMo2CV5vLPPunGd4Vw5Y5mvxz9pC9z8cPViSvgxTLrVRgQ2PrEnS7LTrMHb4rux3mr6Lf8UdF.zip
`short rope` recipe.
