### ISSUE TITLE
Error message when interacting with evac shelter computer

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#60824]
### Describe the bug

When I start a new game as a survivor, I try to interact with the computer and I get the following message:

 DEBUG    : No valid value.

 FUNCTION : std::string str_or_var<T>::evaluate(const T&) const [with T = dialogue; std::string = std::__cxx11::basic_string<char>]
 FILE     : src/condition.h
 LINE     : 90
 VERSION  : 8c78e92

### Steps to reproduce

1. Start as a survivor
2. Interact with the computer
3. Get the error message

### Expected behavior

We shouldn't get an error after interacting with the computer

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/188874942-7d0e0a85-8d8a-4cc4-8852-3321f0331556.png)
After the error message, I can use the computer freely.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 8c78e92 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by EIIKaO** [comment]
It may be the same problem with #60347
I have actually already created a workaround for its problem by yesterday. >> https://github.com/EIIKaO/Cataclysm-DDA/commit/646b2a320f5db1de21b2ebe2601cc2247d93f708
Hope I would like to submit a PR within a few hours.

**Comment by EIIKaO** [comment]
I have tried to make the fixes as small as possible to not interfere with your future development plans.
If there still are problems, please feel free to point it out to me.

**Comment by NetSysFire** [comment]
This looks like #60831 has fixed this. Yell at me to reopen if it is still not fixed.
