### ISSUE TITLE
Error when trying to deploy mattress

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#60823]
### Describe the bug

I get the following error message when trying to deploy a mattress via the use menu while wearing a suitcase:

 DEBUG    : Failed to obtain target item

 FUNCTION : void avatar_action::use_item(avatar&, item_location&)
 FILE     : src/avatar_action.cpp
 LINE     : 1165
 VERSION  : 8c78e92

It is caused because I can't equip the mattress since I'm wearing a suitcase

### Steps to reproduce

1. Wear a suitcase
2. Try to deploy a mattress with the use menu
3. Get the error

### Expected behavior

It should let you know that you can't deploy the mattress because your hands are occupied.

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/188868283-cfdee1d0-3de6-41fd-93da-b9e81497b7ee.png)
I am wearing a suitcase and am unable to wield the mattress
![image](https://user-images.githubusercontent.com/88143686/188868362-9793a450-6a86-48f9-92db-7dd4a559a5fe.png)
And here I stop wearing the suitcase and therefore can wield the mattress

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 8c78e92 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Hirmuolio** [comment]
Same as #60570 
The problem being caused by full hands is new info.
