### ISSUE TITLE
Debug wish menu uses generic guns even when brand names is set to true

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#60829]
### Describe the bug

as the title says, this makes searching for things difficult if you're not used to their generic names

### Steps to reproduce

set Show gun brand names to true on line 10 of interface options
load a debug world
search for mossberg
find no shotguns

### Expected behavior

that all UI would use consistent naming and respect interface options

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: e45b649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    return_the_nut [return_the_nut]
]

**Comment by ZhilkinSerg** [comment]
Debug menu should show both names.

**Comment by YourCompanionCube** [comment]
adding to this, it also happens in pocket white/blacklisting menus
