### ISSUE TITLE
"Hostile is dangerously close" message does not trigger while unloading nearby containers

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60830]
### Describe the bug

While trying to use a personal unload zone, set to "yes" on all the optional unload stuff, to unload several corpses and some clothes with MOLLE attachments, I was attacked by a zombie. I did not get any warning messages before "You were attacked by the [zombie type]". I had "hostile spotted" turned off in the distractions manager, but "Hostile is dangerously close" was enabled.

### Steps to reproduce

Position yourself so that a zombie is approaching to attack you but you can't see the zombie, and attempt to unload using a personal sorting zone.

It's possible this occurs during the detaching molle step or something like that, it's hard for me to tell.

### Expected behavior

I get interrupted by relevant messages while performing slow actions.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/188951766-c9992bcc-d616-4a8b-b082-240b80c10a89.png)
![image](https://user-images.githubusercontent.com/5107449/188951817-7d16d1b7-cf8d-4ba5-ac94-aebacc507fec.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: e2e7914 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by MrHrulgin** [comment]
I just had this same thing occur to me, so it's still an issue as of Game Version: cdc3058 [64-bit]
