### ISSUE TITLE
Stepladders "Failed to obtain target item" when activated with broken arm

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60834]
### Describe the bug

When you attempt to (a)ctivate a stepladder on the ground, but you can't pick it up due to a broken arm, the game will let you try to activate it, but throws an error.

It will let you activate it if you put it in your inventory first.

### Steps to reproduce

1. Break arm
2. Spawn stepladder on the ground
3. Attempt to (a)ctivate it

### Expected behavior

The game either lets you activate the ladder like normal, or if you can't do it with one arm, it either won't let you do it in the first place, or gives you an in-game message explaining why you can't put up the stepladder.

This behavior should be the same whether you the ladder is in your inventory or on the ground.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/188970144-bae4528e-e7a2-43b7-ac2b-3359ea80d02c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: e2e7914 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This applies to both the wooden an aluminum stepladder

**Comment by NetSysFire** [comment]
Might be the same cause as with #50236.

**Comment by Night-Pryanik** [comment]
This is essentially the same as #60570 - both stepladder and mattress can be deployed to furniture and both cause an error if they're lying on the ground and you can't wield them.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 21 October 2024. 
Activating stepladder lying on the ground with broken arm gives you the `You couldn't pickup the stepladder.` message and stopping the activation activity without any debug messages.
