### ISSUE TITLE
Practice - vehicle maintenance

### ISSUE THREAD

**Issue by ProfaneServitor** [CleverRaven/Cataclysm-DDA#60848]
### Is your feature request related to a problem? Please describe.

Mechanics 2 is a point at which character can install simplest gasoline engines onto vehicle and leave dense city areas. Without a vehicle the only safe way to leave a city is by clearing it inside out, which can be particularly difficult on higher urban density settings.

Leveling mechanics to level 2 is inconsistent. It can be done with learning kits, but they are rare; it can be done by reading a book, but it is slow; and it can be done by repairing pipes or installing/removing car parts, but that's tedious. It would be nice to have a consistent way to access that level.

### Solution you would like.

A craft which allows leveling mechanics consistently.

Most bicycles and cars are sold with manuals which contain instructions how to maintain it. These might spawn in homes and vehicles. Alternatively, this craft might be available from Under the Hood.

**Comment by PatrikLundell** [comment]
Isn't it intended that start in cities should result in difficulties regarding moving around and leaving the city? My first vehicles have always been ones found in a working condition. However, I don't think you need much mechanic to repair a bicycle, and you can't safely go faster than that with all the wrecks and vehicles on the city streets anyway.

You don't need to clear the city inside out to be able to leave, just clear a path (and hope you don't run into a fox with a tail of zombies along the way).

**Comment by phoeo** [comment]
> and you can't safely go faster than that with all the wrecks and vehicles on the city streets anyway.
You can and you should. Moving faster than 19 km/h is needed to make sure that dogs and hunters don't freeload in the basket.

And even after you leave the city, the problem of grinding mechanics persists.
