### ISSUE TITLE
[Magiclysm] Black Dragon Scales mutation is preventing the development of Scaled Hands and Black Dragon Claws mutation

### ISSUE THREAD

**Issue by Destrogon** [CleverRaven/Cataclysm-DDA#60845]
### Describe the bug

Imma try to describe this as best I can.

So, in the Black Dragon mutation line, there are two mutations, Scales Black Dragon Scales and Black Dragon Claws. For some reason, when the player acquires Black Dragon Scales, Scaled Hands and its evolved mutation, Black Dragon Claws will not develop or mutate, even with the use of Debug mode. However, if the player has only the Scales mutation, the prerequisite mutation for Black Dragon Scales, the Scaled hands mutation will appear as will its evolved state

### Steps to reproduce

1. Have the Black Dragon Scales Mutation
2. Use debug mode to try to give yourself Scaled Hands

### Expected behavior

Should be able to get Scaled hands and Black Dragon Claws if you have Black Dragon Scales

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 8c78e92 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens],
    Stats Through Kills [stats_through_kills]
]

**Comment by catdach** [comment]
I was unable to replicate this with debug mode: 
![image](https://user-images.githubusercontent.com/93795131/189184771-ef97c4f4-22f0-4ba9-8cf2-7a3a07d7e658.png)

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 5664fa2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens],
    Stats Through Kills [stats_through_kills]
]
