### ISSUE TITLE
Bow fire drill can't be "recharged" when you find it's run out of charges because you can't light a fire to "recharge" it

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#60849]
### Describe the bug

It was dark and I tried to light a fire with a bow fire drill. It didn't work, because the hidden charges had run out (examining it can give you an approximate status "almost running out" or something like that prior to that), but there is no up front indication. I'd then tried to "recharge" it (i.e. craft a new bow fire drill from the old one plus a new branch), and found I couldn't because it was too dark to craft...

### Steps to reproduce

1. Wait until it gets dark.
2. Use a bow fire drill until it runs out of hidden charges.
3. Try to "repair" the bow fire drill by crafting a new one out of the old one plus a branch.
4. Find that you can't, because it's dark, so you need a bow fire drill to recharge the bow fire drill.

### Expected behavior

The bow fire drill recharge should be possible in the dark. It both doesn't seem to be impossible to take a branch and make a starter stick receptacle in it in darkness, and it definitely isn't fun from a game play perspective.

Alternatively, restore the charges to the UI so the player has a chance to see that it's running out without having to examine it frequently.

Alternatively change the bow fire drill item string so that the item description contains the vague status description up front, rather than bury it in the examination action.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 4f45027 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

**Comment by mqrause** [comment]
You could add the `BLIND_EASY` or `BLIND_HARD` flag to the recipe. Probably the latter.

More involved changes that could possibly address both this and #59093 would be welcome.
