### ISSUE TITLE
[Xedra Evolved] Crash in mutation menu for "Walking the shadowed path of blood."

### ISSUE THREAD

**Issue by Acrepe** [CleverRaven/Cataclysm-DDA#60840]
### Describe the bug

Crash upon tabbing away from "Walking the shadowed path of blood." when in Examine mode

### Steps to reproduce

1. Make a character
2. Spawn an infectious bloodsucker (Moroi, Strigoi)
3. Get bitten until vampirism occurs
4. Wait to develop "Walking the shadowed path of blood." mutation
5. Enter mutation menu, enter examine mode, scroll down to "Walking the shadowed path of blood."
6. Press tab and receive a seg fault

### Expected behavior

For the game to not crash when tabbing away from "Walking the shadowed path of blood."

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 34f7773 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9522179/config.zip)
[Burkettsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9522181/Burkettsville.zip)

**Comment by Maleclypse** [comment]
I'm unable to replicate this error on the most recent experimental.
Let me know if I you're doing something different.

![shadowed path](https://user-images.githubusercontent.com/54345792/189248632-90130554-f4fd-4ea6-8b8f-9e6ec5b43e3f.png)
![shadowed path mutation menu](https://user-images.githubusercontent.com/54345792/189248633-597ffa9f-9609-40a6-98ed-fb08b7901c46.png)
![shadowed path mutation menu2](https://user-images.githubusercontent.com/54345792/189248635-570198f1-cb50-4631-b956-860741c8308e.png)

**Comment by Maleclypse** [comment]
I'm closing this since I can't replicate in current experimental.
