### ISSUE TITLE
Magellan Helmet CA from aftershock cools entire body

### ISSUE THREAD

**Issue by Phrux** [CleverRaven/Cataclysm-DDA#60858]
### Describe the bug

Magellan helmet CA from aftershock sets the temperature of the entire body to 10 when powered

### Steps to reproduce

1. Make a player with a Magellan helmet CA and a charging box+power
2. Charge helmet
3. Put on charged helmet and turn it on

### Expected behavior

I expected it would only regulate the temperature of the head, since I am not wearing the entire exosuit

### Screenshots

[https://cdn.discordapp.com/attachments/642349261320880128/1017447499566420101/without.png](url) [https://cdn.discordapp.com/attachments/642349261320880128/1017450783043747910/heat3.png](url)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: b1fb6f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    DinoMod [DinoMod],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by John-Candlebury** [comment]
It looks like its climate control flag affecting the whole body instead of just the covered bodyparts. So its not really an aftershock specific bug (although the item that triggers it is from the mod.

**Comment by John-Candlebury** [comment]
Fixed when the Climate control effects were moved to JSON,
