### ISSUE TITLE
Make books generic for the illiterate trait

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#6085]
Basically, when you are illiterate, you don't know if you have a book called "Easy Cooking Recipes" or "How to wage a thermonuclear war".

Make all books read as "Book" for those with illiterate, description, "a book", of course they won't stack, but it will reinforce the trait.
##

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.

FWIW this is an awesome idea.
