### ISSUE TITLE
AppVeyor builds are constantly failing.

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#60867]
### Describe the bug

Since the ccache implementation AppVeyor builds are constantly failing because they would otherwise take more, than the current timelimit, which is 90 minutes at the time of writing. Other failed builds can be explained by errors in the C++ code.

### Steps to reproduce

1. Make a PR or commit to a PR
2. Watch AppVeyor CI build fail due to a timeout after being queued for hours.

### Expected behavior

AppVeyor CI doesn't time out ~~and it utilizes ccache properly to minimize queue time~~.

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-11200-gf284f9dd8d

### Additional context

See for example:
- https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/44654202/messages (The ccache implementation)
- https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/44716622/messages

**Comment by Stadler76** [comment]
The question is: Is AppVeyor CI still needed? And if so: If the timeout is raised to, let's say: 120 minutes, would it finally utilize ccache.

**Comment by akrieger** [comment]
Nb. the reason the ccache implementation is causing this is likely because it added ObjectCreator to the default solution so we could better utilize vcpkg and github action machines. ObjectCreator's dep on qt is very heavy, and I'm betting AppVeyor is just building the entire solution and thus now also building qt, which is causing the perma-timeouts.

**Comment by Stadler76** [comment]
> Nb. the reason the ccache implementation is causing this is likely because it added ObjectCreator to the default solution so we could better utilize vcpkg and github action machines. ObjectCreator's dep on qt is very heavy, and I'm betting AppVeyor is just building the entire solution and thus now also building qt, which is causing the perma-timeouts.

I realized that, but what would be the preferred solution? Fix AppVeyor or ditch it? I'd say at least disable it completely until the issue is resolved. And even if we fix it by getting a longer timeout, would it then finally use ccache to speed up build times? If not, I'm quite certain, we have to deal with even longer queue times.

**Comment by akrieger** [comment]
It would not. The ccache setup is bespoke to the GitHub workflows.

**Comment by ZhilkinSerg** [comment]
I don't think we need to build OC that frequently.

**Comment by akrieger** [comment]
I just realized AppVeyor config is in repo. I'll see if I can make the necessary changes tomorrow.

**Comment by Stadler76** [comment]
Just updated the 'Expected behavior' as it isn't mandatory for AppVeyor to use ccache.
