### ISSUE TITLE
"small lock and key" item spawn locations

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#60877]
### Is your feature request related to a problem? Please describe.

Currently the "small lock and key" item (ID "lock", used for lockpicking practice recipe) doesn't spawn anywhere. The only way to obtain it is from finding a "cargo_lock" vehicle item in a mall or lab. Given that it represents just a common lock and key, it should be way more common.

### Solution you would like.

Add it to common house loot or other such place.

### Additional context

I may have missed something when searching in code since the item ID "lock" is also a commonly used word.

**Comment by utechenko-v** [comment]
"small lock and key" can be obtained by disassembling "filing cabinet" furniture. But I agree that it is good idea to add them to a spawn. I suppose it should be spawned mainly in furniture stores and similar places.

**Comment by GuardianDll** [comment]
We can also make a "lock" and "broken lock" items, add them to some places like locked doors, and consume them in lockpick training

**Comment by PatrikLundell** [comment]
I believe you also get the item from lockers (which makes sense, since you need the item to construct these).

I don't think it makes sense to be present as household loot.

**Comment by propurty** [comment]
I think you can also get them from the strongboxes, or whatever those boxes are called, in the living quarters/military rooms of a TCL for example.
