### ISSUE TITLE
Localization: string for “rock” translation is used for both throwing stones and music genre

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#60879]
### Describe the bug

Current “rock” string in transifex (string No 9122) is used for both throwing stones and music genre:
Developer notes for that string:
~ Item name
~ Snippet in category “<musicgenre_noun>”
We need to separate them, since in other languages it has separate translations.

### Steps to reproduce

1. Add translation for "rock" as stones for throwing in transifex.com for some language (e.g. Ukrainian)
2. Get translated file and add it to game, switch to the language with translation
3. Listen to music for some time (using mp3 player or stereo in a car)
Actual result: translation for "rock" as stones is used to describe a music genre

### Expected behavior

There must be separate strings for “rock” translation as a throwing stone and as a music genre

### Versions and configuration

Observed in "master-cataclysm-dda" in transifex.com

**Comment by GuardianDll** [comment]
You can add a comment field to them, you just need to find where this words exist in json

**Comment by utechenko-v** [comment]
I found locations of "rock" string:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/snippets/music.json#L171
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/ammo.json#L486
But I don't know how to make it use separate entities. I suppose there should be a way to mark string in music.json to make it use separate translation entity.
Currently .PO file has one place for translation (e.g. uk_UA.po):
```
#. ~ Item name
#. ~ Snippet in category "<musicgenre_noun>"
#: data/json/items/ammo.json data/json/snippets/music.json
msgid "rock"
msgid_plural "rocks"
msgstr[0] "камінь"
msgstr[1] "камені"
msgstr[2] "каменів"
msgstr[3] "камінь"
```
Probably we need something similar to additional clarification in "\<musicdesc_evaluation\>"  category, to distinguish it from others, e.g. Snippet in category "\<okay\>"?
```
{
    "type": "snippet",
    "category": "<musicdesc_evaluation>",
    "text": [
      "amazing",
      "funky",
      { "text": { "ctxt": "<musicdesc_evaluation>", "str": "okay" } },
      "pretty good",
      "sweet",
      "sick",
      "totally danceable",
...
```
