### ISSUE TITLE
Pressing 'b' for batch in the recipe/crafting menu when crafting 'amplifier circuit' crashes the game

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#60889]
### Describe the bug

Pressing 'b' for batch in the recipe/crafting menu when crafting 'amplifier circuit' crashes the game

### Steps to reproduce

1. Open the crafting/recipe menu
2. Filter to find recipe for amplifier circuit
3. Press 'b' (batch)
4. Game crashes

### Expected behavior

No crashes

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/189463202-1881c869-0af9-49da-bfe5-ae58dc00be37.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 2b52aa6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries]
]

**Comment by ZeroInternalReflection** [comment]
This is likely a duplicate of #60804, where it crashed on trying to batch craft any search result.
After merging of #60819 (~2 hours ago), batch crafting of amplifier circuits works as expected.

**Comment by jeffplata** [comment]
- Game Version: 8c2607e [64-bit]

Yeah, this version fixed it.
