### ISSUE TITLE
EOD suit lacks a post apocalypse value

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#60887]
### Describe the bug

The EOD suit items lack post apocalypse prices, meaning traders trade them for market value, making them extremely valuable

### Steps to reproduce

Look at the EOD suit's value

### Expected behavior

I expected that the EOD suit would not cost market value

### Screenshots

![image](https://user-images.githubusercontent.com/32277062/189446132-0ee08964-2053-4162-afb2-29ca23bca234.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1556 (1909)
- Game Version: 5986364 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by anothersimulacrum** [comment]
Yep, all yours!
