### ISSUE TITLE
Cannot drag vehicles directly into deep water

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#60892]
### Describe the bug

You cannot drag vehicles into deep water directly, you'll be instead prompted to dive into the water, and you will effectively stop dragging the vehicle (upon returning to land the message "Can't find grabbed object" will appear). Grabbing a vehicle while already in deep water leads to the same result.

### Steps to reproduce

 1. Find a location where land and deep water directly meet
 2. Spawn a light (enough to be dragged by the player) vehicle capable of floating in water
 3. Grab vehicle
 4. Drag vehicle to deep water shore
 5. Attempt to move into the deep water
 6. Accept the prompt to dive
 7. Notice the vehicle no longer being in arms grasp

Alt:
 1. Be in deep water that has a direct connection to land with a light (enough to be dragged by the player) vehicle in arms reach
 2. Grab the vehicle
 3. Swim away from the land
 4. Notice the vehicle no longer being in arms grasp

### Expected behavior

I can drag vehicles into the water despite its depth.

### Screenshots

Naturally occurring deep water shore
![boatdrag](https://user-images.githubusercontent.com/32048635/189469386-7c0a5140-3880-4368-b6e2-e05663cd305e.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 70905b5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It works as expected when dragging through shallow water.

**Comment by PatrikLundell** [comment]
You won't have much strength in your pulling effort while swimming. In the real world you'd push the boat into the water, rather than drag it, but the game has support for pushing only a small set of vehicles.
