### ISSUE TITLE
When flung from a roof fall damage iterates indefitinely

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#60896]
### Describe the bug

When the survivor is flung while downed the impact will repeat indefinitely, leading to an instant kill (or a softlock with Debug Invulnerability) without them moving down a Z-level.

### Steps to reproduce

1. Modify a monster with a smash attack to have a cooldown of 1 turn
2. Move to a roof and spawn the monster 1 tile away
3. Wait for the monster to reach the adjacent tile
4. (Optional, to verify looping) Modify all limb health to an arbitrary large number or add Debug Invulnerability
5. Add `downed` to yourself and wait a turn for the special to fling you off the roof
6. Behold dying (and falling multiple times, if you have a high health) or softlocking the game when invulnerable

### Expected behavior

Falling one story to happen once.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 0.F-11164-g42abc28f21-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Not *terribly* common, but still turns a technically-survivable fall into an instakill.

**Comment by Venera3** [comment]
This was me confirming for Guardian, so I'm bumping it up to S2 like the loose cannon I am.

**Comment by NetSysFire** [comment]
>like the loose cannon I am.

One-upping you by making this a blocker. This sounds nasty enough that this should be fixed before release.

**Comment by GuardianDll** [comment]
Thats nasty, but probability to reproduce it in the original game is way too small
Dont think its really worth to put it into stable tracker

**Comment by anoobindisguise** [comment]
Any bug that can result in the player instantly dying should be a release blocker IMO

**Comment by Venera3** [comment]
I agree. Figuring out *why* it happens would be helpful, but if nobody has the time or inclination to do so a bandaid fix of the flinging function removing the downed effect should be straightforward - in any case not a problem that will hold Stable up, but slapping blocker on it helps clean it up in the short-term.

**Comment by Night-Pryanik** [comment]
Tested right now on 0.F-11297.
The situation has nothing to do with `downed` effect. Infinite damage happens when flung from a roof even without any effect.

**Comment by GuardianDll** [comment]
Btw for fast recreation you can just teleport yourself 1 tile up, and then immediately teleport 1 tile up again

**Comment by NetSysFire** [comment]
This also happens when you get teleported into open air by a portal.
