### ISSUE TITLE
Luty SMG should be craftable

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#60893]
### Is your feature request related to a problem? Please describe.

I get frustrated when I find the anarchist AAA book and I cannot make one of the most famous anarchy guns, the Luty!

### Solution you would like.

I would like for the AAA manual to include recipes for the various Lutys. It'd require like 6 fabrication or something

**Comment by kevingranade** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/22688

**Comment by pantherpusher** [comment]
I'm sorry I got blob brain
