### ISSUE TITLE
Using armed martial arts moves that require unarmed skill don't refresh Unarmed experience

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#60908]
### Describe the bug

I have a character with Krav Maga, which can use weapons. I have 3 unarmed combat skill. I use a combat knife to kill many zombies, regularly triggering the Takedown Technique which requires 3 unarmed combat skill. In my sleep, I lose my edge, dropping to Unarmed 2.99, and removing my ability to use Takedown until I punch zombies for a little bit. This seems counterintuitive? 

### Steps to reproduce

Have exactly enough unarmed to use a martial arts skill on a character.
Use armed combat to trigger said skill.
See Unarmed skill level drop, losing access to said combat skill.

### Expected behavior

I would expect using a martial art that allows weapons to either base its skill unlocks on the best of weapon or unarmed skill, depending on what you're wielding. If my martial art lets me use daggers and I'm wielding one, the skill unlocks should happen as my Piercing Weapons skill goes up.  

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 49242cd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by TheShadowFerret** [comment]
Krav Maga uniquely being both armed & unarmed makes me think most techniques should be split into a melee & fist version with melee/unarmed skill requirements for each. 🤔

**Comment by anoobindisguise** [comment]
On a related note, has anyone noticed martial arts shredding their gloves? I was using Krav Maga with a combat knife when I realized my activity suit had been completely shredded by the combat techniques. That... doesn't seem right.

**Comment by MrHrulgin** [comment]
> 

Yes, specifically my gloves take damage when doing the moves that depend upon unarmed skill. It does seem to make some sense, though the rate of damage does seem to be quite high.
