### ISSUE TITLE
NPC 'trying to find necessary items to do the job'

### ISSUE THREAD

**Issue by AzTheProtoGoat** [CleverRaven/Cataclysm-DDA#60907]
### Describe the bug

NPC has resources in front of him in a camp, yet he is still trying to find the items, which causes a lot of lag

Note : The hammer was out of LOS of his while constructing, still it shouldnt create THIS much lag

### Steps to reproduce

1. have an NPC on construction work in a rather enclosed building
2. set up a blueprint for walls etc.
3. after finishing one of those, the npc will try to find the resources 100 times or more every second, causing lag

Additional note : Swapping places with an npc seemed to 'fix' him for the duration of creating the current thing

### Expected behavior

expected the NPC to do stuff as usual instead of having trouble with it. or at least for him to look for stuff in the camp

### Screenshots

![image](https://user-images.githubusercontent.com/112546133/189502970-99c14d92-9398-43f3-8404-4896670eb29c.png)

https://www.youtube.com/watch?v=5C059I8QI70

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 8f44037 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    No Hope [no_hope],
    Make bows great again [bow_opness],
    Magiclysm [magiclysm]
]

### Additional context

[Gumball.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9541452/Gumball.zip)

**Comment by AzTheProtoGoat** [comment]
the swapping only worked cause it gave him LOS on the hammer, which i forgot to put near the workspace*

**Comment by jim-huynh** [comment]
This is related to a change from https://github.com/CleverRaven/Cataclysm-DDA/pull/35649

![image](https://user-images.githubusercontent.com/3409545/193986898-148da44b-ee82-45a7-8b0f-c883f5b3fad8.png)

I removed this change from my local environment and NPCs are able to find tools even when they start off in their enclosed house without direct line of sight to the tools.  Still need testing to see if it causes NPCs to infinite loop due to light levels.

**Comment by arkhaeart** [comment]
Can confirm this issue in 0.G release verson. I gave a NPC an order to disassemble some furniture in a camp, and he keeps spamming these messages even despite having screwdriver and hammer directly adjacent to him, even if i place a camp stockpile zone there.

**Comment by jzburda** [comment]
Can confirm this is an issue when it comes to vehicle disassembly. They will try around 100 times per in-game turn to "Try to find the necessary tools to do the job" This results in massive hangs as they try up to 40,000 times to find something they cannot find. In this case, I have to crawl over to them, tell them to please stop messing with the space time continuum, and then figure out which tool they don't have. Then it'll work fine.

[
https://i.imgur.com/CIqZe4Z.png](url)
