### ISSUE TITLE
Tool usage for vehicle construction

### ISSUE THREAD

**Issue by BollandP** [CleverRaven/Cataclysm-DDA#6090]
I think that the flat requirements of part installation/removal don't make sense for quite a few parts.

I tried building a cheap fully-wooden vehicle for transporting lumber, but adding wooden frames requires a welder/duct tape and wrench. Now I would imagine that duct tape would be sufficient, but why not use a hammer and nails to put the frame together? I also miss fully wooden wheels :) I want my box car!

Another quirk is that anything can be installed using duct tape. Need that engine installed? Duct tape. Need a wheel locked in place? Duct tape. It makes sense for smaller/simpler parts, but not for any critical parts (wheel, engine). I know that in folklore, duct tape can hold anything together, but we are surviving a zombie apocalypse here.

While the wheel change mechanism is very nice, changing a bicycle wheel doesn't really require a jack. Now I know bicycle wheels can be installed anywhere, but still. Or is there any system for wheel bearing capacity, so that we can't have a tank on casters?

Any other components I missed? Durability decrease when installing criticals with duct tape, perhaps? Let's get the ideas flowing.

------------------
It will take me some time to learn how to be a proper git to actually contribute any changes.
In the meantime, I throw these suggestions and see what sticks and what the opinions on them are.

**Comment by illi-kun** [comment]
General idea of this issue is already implemented, so various tools are required for various vehicle parts installation. Jack is also not needed anymore for installation of wheels on light vehicles.

This issue can be safely closed.

**Comment by kevingranade** [comment]
Er, not that I noticed, some parts require different tools, but it's
defined in a gnarly ball of code in veh_interface.
BrvapDin had made a start at making part installation work like crafting
and construction, but then abandoned it before it was mergeable.
