### ISSUE TITLE
Switch fire to M320 crash the game

### ISSUE THREAD

**Issue by devavizard** [CleverRaven/Cataclysm-DDA#60912]
### Describe the bug

Bug occurs in modded gun with sight attached. 

### Steps to reproduce

1. Find an assault rifle with under barrel support.
2. Give it scope.
3. Attach M320.
4. Switch firing mode to M320.
5. Game freeze,

### Expected behavior

Able to use M320.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 5986364 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-11297.
Got M4, installed ACOG, installed M320. Pressed `f` to go into aim mode, pressed `s` to change firing mode to M320. Was able to successfully fire M320.

**Comment by devavizard** [comment]
I forgot one little detail. When I get a gun the next thing I do is changing its default firing mode [f keys] to be always precise. 

![freezing_when_switching_to_underbarrel_m320](https://user-images.githubusercontent.com/113159317/191872364-937be0ec-66e8-4cb4-9b06-bcd1e04a4505.png)

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: e5b3ca9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    DinoMod [DinoMod],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by Night-Pryanik** [comment]
Yeah, now I can confirm.
