### ISSUE TITLE
Bike racks on two-tile vehicles causing merges 2: Goldblum Boogaloo

### ISSUE THREAD

**Issue by DPavonis** [CleverRaven/Cataclysm-DDA#60915]
### Describe the bug

On a two tile vehicle, with bike racks on both tiles and sub-vehicles loaded on both racks, attempting to unload one of the sub-vehicles will cause it to merge with the other.

Similar behavior to  #60453 though unrelated to name as the game forgets the name of the sub-vehicles on load.

### Steps to reproduce

1.) Have a two tile vehicle with bike racks on each tile with sub-vehicles positioned on either end
2.) Load both sub-vehicles onto their respective racks
3.) Save and reload game
4.) Attempt to unload a vehicle from the rack

### Expected behavior

That vehicle parts on bike racks not merge into one-another.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: 8f44037 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Attached is a save with a prepared test vehicle. Simply rack the two sub-vehicles, save the game, reload, then attempt to unload the vehicles.

[Keedysville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9541812/Keedysville.zip)

**Comment by irwiss** [comment]
For a small fix
```diff
diff --git a/src/savegame_json.cpp b/src/savegame_json.cpp
index 23674b9c502988a22a8ae8816932ed3b7597935b..c3a485dcffa4423faa1c54f14ec9fa2b35f1d5ea 100644
--- a/src/savegame_json.cpp
+++ b/src/savegame_json.cpp
@@ -3278,7 +3278,7 @@ void vehicle_part::serialize( JsonOut &json ) const
         json.member( "carry" );
         json.start_array();
         while( !carried_copy.empty() ) {
-            const vehicle_part::carried_part_data &x = carried_copy.top();
+            const vehicle_part::carried_part_data x = carried_copy.top();
             carried_copy.pop();
             const bool pivot = x.mount == tripoint_zero;
             const int mount_offset = x.axis_is_x ? x.mount.x : x.mount.y;
```
#60905 will also fix it, I tried splitting commits when submitting the PR but messed up, sorry, that was my bad
