### ISSUE TITLE
Pushing 1-tile vehicles causes them to fall through extra z-levels

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#60919]
### Describe the bug

When pushing 1-tile vehicles off roofs or similar high places, the vehicles may drop through solid terrain such as roofs or ground.

### Steps to reproduce

1. Find a high place you can push vehicles off of.
2. Find a 1-tile vehicle such as a swivel chair or an ice cream cart.
3. Push the vehicle off the roof.
4. Find the vehicle.

### Expected behavior

Expected small vehicles to not drop through solid terrain without leaving a hole.

### Screenshots

![chair peculiarities](https://user-images.githubusercontent.com/56027287/189525125-cefb2a62-466e-4241-b6e9-b9d926965efe.png)

### Versions and configuration

Game version: 5986364
Mods: dda, no_npc_food, no_fungal_growth, package_bionic_professions

### Additional context

Driving a 1-tile vehicle off a high place seems to work fine.

**Comment by Night-Pryanik** [comment]
Looks suspiciously similar to one of the bugs mentioned in #57720.
