### ISSUE TITLE
mini ammo boxes cant be cut or disassembled 

### ISSUE THREAD

**Issue by nopenoperson** [CleverRaven/Cataclysm-DDA#60928]
### Describe the bug

mini ammo boxes cant be cut or disassembled. they are made of paper and you should be able to cut or disassemble them

### Steps to reproduce

try to cut it with a knife. try to disassemble

### Expected behavior

i expect to be able to cut or disassemble a paper box

### Screenshots

![attemptingtocutminiammoboxes](https://user-images.githubusercontent.com/75625092/189542541-a6595213-66ae-4872-a84b-4254e0e0736b.png)
![disassemblingofminiammobox](https://user-images.githubusercontent.com/75625092/189542554-7cdb1e6c-8a9f-4800-86b2-14d19a163205.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.1256 (1903)
- Game Version: 1045fea-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
/confirmed

@GuardianDll, "confirm" does not work, please type the exact command

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: b9c5366 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
