### ISSUE TITLE
Autodrink from inventory

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#60948]
### Is your feature request related to a problem? Please describe.

With sweating implemented, there's now an actual reason to carry water during hot summer days, which is a positive change. However, fluid loss can now happen really quickly, especially if when performing long-term actions such as crafting, so it's easy to end up dehydrated if you aren't constantly interrupting those activities to drink. Some, like butchering, can't even be interrupted.

### Solution you would like.

Add an option that makes the player character automatically drink any drinks in their inventory. This system should kick in at least under the same circumstances as the auto drink zone, i.e. while reading, crafting, etc., but ideally it should always be active. By default it shouldn't activate in combat, but otherwise it seems reasonable to expect the PC to take a drink when they start to get thirst.

Maybe make a switch so it's Off/Only water/Any drink, so people can decide if they want to automatically drink soda or not.

**Comment by PatrikLundell** [comment]
There definitely has to be something to allow you to forbid drinking the water you're fetching from the river on the way back to base where your clean water is waiting for you (and where you're going to convert the river water into clean water).

**Comment by Terrorforge** [comment]
There's already a NO_AUTO_CONSUME flag to prevent autodrinking e.g. booze, which I imagine this system would use same as the zone-based autodrink.

... but regular unclean water doesn't have that flag for some reason? I would guess there's some other logic in the autodrink algorithm that prevents drinking it, otherwise that's really dangerous.

**Comment by hyiltiz** [comment]
stale bot please
