### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jatsco** [CleverRaven/Cataclysm-DDA#60942]
### Describe the bug

When the Advanced Inventory Manager is opened in the game, it will crash

### Steps to reproduce

Press "/"to open advanced inventory manager

### Expected behavior

Will open the "advanced inventory manager"

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HONOR; Model: JLH-AN00; Release: 11; Incremental: 4.2.0.186C00; 
- Game Version: 2924a24 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝) [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions]
]

### Additional context

15:04:22.618 : Starting log.
15:04:22.618 INFO : Cataclysm DDA version 2924a24
15:04:22.619 INFO : [main] C locale set to C.UTF-8
15:04:22.619 INFO : [main] C++ locale set to 
15:04:22.619 INFO : SDL version used during compile is 2.0.12
15:04:22.619 INFO : SDL version used during linking and in runtime is 2.0.12
15:04:22.674 INFO : [options] C locale set to C.UTF-8
15:04:22.675 INFO : [options] C++ locale set to 
15:04:22.675 INFO : Read Android system language: 'zh_Hans_CN'
15:04:22.675 INFO : Setting language to: 'zh_CN'
15:04:22.675 INFO : [i18n] Scanning core translations from /storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/lang/mo/
15:04:22.675 INFO : [i18n] Scanning mod translations from /storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/
15:04:22.675 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/] failed with "No such file or directory".
15:04:22.857 INFO : Read Android system language: 'zh_Hans_CN'
15:04:22.888 ERROR SDL : (error message will follow backtrace)#01: 0x7989c72088 DebugLog(DebugLevel, DebugClass)
#02: 0x798a78bb54 printErrorIf(bool, char const*)
#03: 0x798a7895d4 gamepad::init()
#04: 0x798a79d0f8 catacurses::init_interface()
#05: 0x798a164964 SDL_main
#06: 0x798bd095f0 Java_org_libsdl_app_SDLActivity_nativeRunMain
Backtrace emission took 0 seconds.
(continued from above) ERROR : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/sdl_wrappers.cpp:26: SDL_GameControllerOpen failed: Couldn't find mapping for device (0)
15:04:22.913 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
15:04:23.469 INFO : Read Android system language: 'zh_Hans_CN'
15:04:23.469 INFO : Setting language to: 'zh_CN'
15:04:23.470 INFO : Read Android system language: 'zh_Hans_CN'
15:04:23.560 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/] failed with "No such file or directory".
15:04:23.614 INFO : Read Android system language: 'zh_Hans_CN'
15:04:23.622 INFO : Read Android system language: 'zh_Hans_CN'
15:04:23.623 INFO : Read Android system language: 'zh_Hans_CN'

**Comment by the-unknownperson** [comment]
I don't know if this particular log is related to this issue, but I'm experiencing the same thing, so I'll send it anyway
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9602989/crash.log)

**Comment by ZeroInternalReflection** [comment]
the-unknownperson's crash log appears to be a different error than jatsco's, but it does match #59629 and #60047.  #59821 is also a crash on opening the advanced inventory menu, but doesn't provide a log, so I'm not sure of the cause of that one.

I've got a fix in progress for the crash going through "trim_and_print", but I've been unable to replicate jatsco's crash above.
