### ISSUE TITLE
Tweakable distances for binocular

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#60941]
### Is your feature request related to a problem? Please describe.

Right now all binoculars give only x2 range to your scouting abilities, when in reality we have a lot of different types of them, from cheap chinese plastic version with 0 quality, to professional 1.5kg tools, monoculars, and even telescopes, that are not designed for this, but can be used for scouting

### Solution you would like.

Make a separate field for item, that describe, how far the character can see with it, bond it to some real values, and make more spotting tools (can work better with #60940)

**Comment by chrispikula** [comment]
Would this go likewise with reallocating the small lens distribution?

Would you want to give smartphones a small multiplier, if used in camera-zoom mode?  (1.25x, or so?)

(Re, small lens: a lot of other stuff that doesn't actually use user-modifiable lenses, like smartphones, and other pinhole camera things, but has them anyways.  There's an issue floating around somewhere about it.)

**Comment by GuardianDll** [comment]
Cheap smartphones has near the same zoom as my own eyes, from my experience. Dont know how useful it is, but sure, why not, the game just need to pick up the biggest value.
