### ISSUE TITLE
Make scouting more time consuming

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#60940]
### Is your feature request related to a problem? Please describe.

At this moment scouting process is instant - you just peek out of radio tower for a second, and now you know everything around the player. 

### Solution you would like.

Separate enchantment field, that describe how long player spend ticks to scout N tiles nearby - depending on how we represent scouting, it can lasts from few minutes (i have a perfect memory, and can memorize stuff from the first sight) to an hour (i write every important point of this megacity into my personal map)

**Comment by ANickelN** [comment]
Might be a bit too much, but could be cool to finally be able to see nuance on the overmap screen as well if scouting is implemented (not knowing what the buildings actually are unless you are closer or they are large and obvious)

**Comment by GuardianDll** [comment]
Thats a separate issue, that already described in #60246

**Comment by KHeket** [comment]
I think its better to add paper and electronic map(in smartphone or notebook) and than make map drawing in them time consuming. Becouse as for me, its very unrealistic, that your character remeber big map in your head so detailed
