### ISSUE TITLE
Radio activation mod is not consumed on use, radio activation mod duplication

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#60949]
### Describe the bug

Using a radio activation mod on a suitable item does not consume the mod. Using a radio activation mod to change the signal color will spawn an additional radio activation mod in the player's inventory or the ground if there is no space.

### Steps to reproduce

1. Find a radio activation mod.
2. Find a grenade.
3. Apply the mod to the grenade.
4. Check inventory.
5. Apply the mod to the grenade and choose a different color.
6. Check inventory.

### Expected behavior

Expected the radio activation mod be attached to the item.
Expected no additional radio activation mods to appear in the case that the radio activation mod were a tool of some sort, like a staple gun?

### Versions and configuration

Game version: b9c5366
Mods: dda, no_npc_food, no_fungal_growth, package_bionic_professions

### Additional context

I suppose the radio activation mod should not disappear if you change the signal color, since it's basically flicking a switch on the thing? As the attached mod is not an actual modification you can't remove it and you need another one to change the color anyway.

**Comment by Hirmuolio** [comment]
Most likely simply adding `"SINGLE_USE"` to the radio mod will fix.
