### ISSUE TITLE
Backrooms Mod and Portal Dungeons

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#60957]
### Describe the bug

When playing the Backrooms Mod, when a Portal Storm starts, the portal dungeon would spawn right under you and/or in your current over map tile, replacing everything on that over map tile.

### Steps to reproduce

1. Start a Backrooms Mod map
2. Wait/Debug Portal Storm
3. Portal Dungeon spawns

### Expected behavior

Portal Dungeon should spawn a few over map tiles away from you

### Screenshots

![Screenshot_2022-09-13-11-31-04-1531498682](https://user-images.githubusercontent.com/95905384/189801882-c7ebb443-4168-47a5-b9a9-0fc282b2968f.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: d9f3bb7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Artifact Jewelries [Artifact Jewelries],
    The Backrooms [backrooms]
]

### Additional context

Would be nice if the Portal Dungeon spawns somewhere else or a mod where you can disable Portal Storms

**Comment by Ramza13** [comment]
Hmmm so I know what's going on here.  One solution would be to fix the underlying code so if it can't find a location it doesn't spawn the dungeon.  Another would be to disable portal storms in backrooms and the third would be to make it work by transforming a different kind of terrain.

Having never touched the mod should it have portal storms at all?

**Comment by Kywi001** [comment]
> Having never touched the mod should it have portal storms at all?

it shouldnt have weather effects at all since you arent technically on earth.

but I guess the portal storms are fine due to both being a dimensional anomaly where you are both underground and aboveground inside the backrooms and you are both in the past, preset and future when portal storms are up.

so either, 
1. disable portal dungeons
2. make the portal dungeon only spawn the small section of it that is not the alien grass (although Im not sure how hard it will be to just spawn a small portion of it without massively breaking the entire OMT)

Note: apparently, the portal dungeon can despawn and the walls and items comes back

**Comment by Kywi001** [comment]
note, accidentally tapped the close button, sorry

**Comment by onura46** [comment]
Do any other mods remove portal storms? If so, there's probably some code in the region settings that allows for that. I'll look into that this week/weekend when I have time, unless someone else gets to it first.

**Comment by onura46** [comment]
This fix that just got merged should work, even in your existing saves (pretty sure). I figured fixing this thing deleting all your items was best for now. We can re-assess portal storms in the Backrooms in the future.
