### ISSUE TITLE
Give laser turrets an internal power reserve

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#6096]
When you think about it, the current laser turret is pretty silly.  I can't picture ANY military fielding an automated point-defense system that could be defeated by a blasted CLOUD.  Also the idea that the small solar panel these contain provides enough energy to allow the turret to fire constantly as long as it's exposed to light is crazy.

I think a simple solution to this would be to give laser turrets an internal battery reserve that would store the power the built-in panels generate, and have the turret draw on that reserve when it fires.  This would allow for a more realistic system;  the turrets can fire day or night, so long as they have enough stored power.  And even during the day, a prolonged engagement would drain power faster than the panels could restore it, eventually exhausting the turrets' reserves and shutting it down.

Turrets could also have the RECHARGABLE flag;  you can't just stuff AAs in them, but you can toss them in a trunk with a recharge station and refill their reserves even if the sun isn't being cooperative.

I think these changes would make the laser turrets make a lot more sense;  they were designed for use by armed forces to reinforce an area quickly and temporarily, say an overnight encampment or roadblock.  The squad carries a few in their vehicle, probably in a storage unit that has a recharger.  When they reach their destination, they unload them, set them up, and they're good to go.  The energy-based nature of these greatly simplifies logistics; a patrol doesn't have to carry large amount of ammunition to load these with.  However, this also means the laser turret is not suitable for permanent base defense; the turret will run out of power in a protracted battle.
##

**Comment by Leland** [comment]
I'm closing this for now as there hasn't been a discussion in years, but if there's still interest by anyone, let me know here and I'll reopen; or feel free to make a new issue.
