### ISSUE TITLE
Extension cables connected to appliances are permanently lost

### ISSUE THREAD

**Issue by phoeo** [CleverRaven/Cataclysm-DDA#60960]
### Describe the bug

If you use extension cables on appliances or wall wirings, they can't be recovered. Even if you take down the appliance, it will only yield the appliance, but not the cable.

### Steps to reproduce

<ol>
<li>Have two appliances nearby, and extension cable in inventory</li>
<li>Use cable to connect appliances</li>
<li>Examine appliances; notice that cable is a "vehicle part" of both appliances, but there is no option to disconnect it</li>
<li>Take down, smash or deconstruct any appliance, or even both. Notice that cable is not recovered</li>
</ol>

### Expected behavior

There should be an option to disconnect cable from appliance.

Deconstructing appliances should return connected cables and other extra parts, if they will be added in the future.

### Screenshots

[![Screenshot-from-2022-09-13-14-48-49.png](https://i.postimg.cc/nrGpHhrq/Screenshot-from-2022-09-13-14-48-49.png)](https://postimg.cc/K3jdfFnY)

### Versions and configuration

0.F

**Comment by phoeo** [comment]
Extension cables can still be recovered from vehicles.

**Comment by dseguin** [comment]
This was resolved in #60618 and #60621. Can you update your build and try again? Or at least list the build number you're using

**Comment by phoeo** [comment]
Seems to work now

**Comment by s22chan** [comment]
If you connect a wall wiring to wall wiring, unplugging appliance on the wall wiring doesn't recover the cables.
