### ISSUE TITLE
NPCs can't use elevators

### ISSUE THREAD

**Issue by phoeo** [CleverRaven/Cataclysm-DDA#60967]
### Describe the bug

If player uses elevator and has followers, followers will be stuck on previous level.

### Steps to reproduce

<ol>
<li>Go to mine</li>
<li>Activate elevator</li>
<li>Spawn followers</li>
<li>Use elevator</li>
<li>Notice that NPCs are stuck on another level. They may try to use stairs though.</li>

### Expected behavior

NPCs should teleport with player.

### Versions and configuration

0.F

### Additional context

Probably connected to general inability of NPCs to use portals.

**Comment by Night-Pryanik** [comment]
It was an issue in stable 0.F, but it's no longer an issue in 0.F-11282.
