### ISSUE TITLE
Consequences for carrying (too many) artifacts

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60966]
### Is your feature request related to a problem? Please describe.

Now that artifacts provide buffs while in your back pocket like in S.T.A.L.K.E.R. you can get pretty insanely powerful by carrying lots of them around. Although they are typically pretty hard to get (locations include portal storms, strange temples, mine finales, distorted labs, and a few others) and they have an opportunity cost of taking up space in your inventory depending on how big the artifact is, there should still probably be some increasingly dire limitations to having too many, especially with the spooky XEDRA anomalous artifact reports seen near them.

### Solution you would like.

Some examples:
- Teleglow
- Micro-teleports (safe teleport, move 1 space) - potentially fatal due to car driving, should probably be prohibited while driving a car
- Radiation (same as in STALKER)
- Attention
- Artifacts straight up vanishing from reality (only in extreme cases, from carrying way too many)
- EMPs?
- Other malicious effects?

effects should probably only kick in after carrying more than 1 artifact, and be minor unless you really get greedy. I don't know how specifically it should be balanced.

**Comment by MNG-cataclysm** [comment]
Artifacts usually have a negative effect, unless you're extremely lucky. These can stack when carrying several artifacts, which I feel is enough punishment.
