### ISSUE TITLE
Idea for new vehicle part: Battery case

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#6097]
It's a little odd that it takes a welder and hacksaw to change a car battery.  You should be able to just pull the thing out.

I suggest we make a small part "battery case" that allows a car battery to be installed on that tile of the vehicle.  So long as the case is there, no other tools are required to add or remove the battery, which takes only a few minutes.  This would also make recovering random vehicles more realistic;  you just bring along a can of gas and a spare battery;  pour the fuel in the tank, swap in the battery, and drive.

This would also be useful for non-moving "vehicles" like welding carts and lighting arrays.  Say you have a lighting system built in your basement, and a solar array outside.  When the battery in your basement lighting system runs down, you just pull it out, lug it upstairs, swap it for the fresh one you had charging in the solar array, and carry the loaded one back downstairs.  This would also make it so people don't have to knock huge holes in their houses just to have a solar-powered interior kitchen.

**Comment by narc0tiq** [comment]
This doesn't need to be open anymore.
