### ISSUE TITLE
Some buildings/objects seem to burn forever (months+)

### ISSUE THREAD

**Issue by nakanakafresh** [CleverRaven/Cataclysm-DDA#60973]
### Describe the bug

I lit a bed in an adobe walled home on fire near my base a few days ago. Now I keep getting this error message. The fire is not spreading and is contained as a small fire on the bed. I've waited an hour next to the fire and it doesn't happen.

I've seen this message before on a previous character, and the house on fire kept burning for months even when living right next to it. The following error message is spammed anytime I'm within a few tiles of the burning object.

 DEBUG    : Setting terrain t_open_air at (20,126,0) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : bool map::ter_set(const tripoint&, const ter_id&, bool)
 FILE     : src/map.cpp
 LINE     : 1975
 VERSION  : b9c5366

### Steps to reproduce

I'm not entirely sure. The house I lit was an adobe walled house. Will include a screencap and debug below.

### Expected behavior

Houses generally burn down within a day or so. 

### Screenshots

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9561079/debug.log)
![image](https://user-images.githubusercontent.com/45909369/190017329-ef2d1df9-22af-4625-865a-3196f2810fef.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: b9c5366 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Fires only progress when within the reality bubble, which is why fires in places you just pass by can persist for months.

This bug report is wholly or mostly a copy of #56242.
