### ISSUE TITLE
Blacksmith won't take currency straps

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#60978]
### Describe the bug

i recently went through the blacksmith/ammo bank questline and went to have the blacksmith make me some armor, but when i first asked i couldn't pay for it since i had compressed all my merch into straps, on a related note i feel disassembly being the only way to decompress currency straps is easy to miss, for a little while i thought i *couldn't* decompress them

### Steps to reproduce

complete blacksmith's quest to acquire the gun for her friend
fill inventory with merch straps or bundles
be unable to buy armor

### Expected behavior

that people would accept money whether it's in a paper loop or not

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: e45b649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    return_the_nut [return_the_nut]
]

### Additional context

i suspect that this also applies to some other NPC conversation based transactions

**Comment by harperers** [comment]
/confirmed

Neither the blacksmith or gunsmiths will accept merch straps or bundles as valid currency. This might also be happening to other NPC traders that should accept them, but i couldn't find any.
