### ISSUE TITLE
Inability to equip companions with desired carried items when lacking own inventory space

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#60970]
### Describe the bug

I believe this is particularly bad in an Innawoods start, although I suspect a shower victim may have the same problem:
I started with a (potential) companion with no inventory space whatsoever, who was carrying a wooden spear. My character starts with a woven basket (standard Innawoods survivor).
After finally making a stone axe capable of chopping trees, I tried to get the companion to wield it (normal trade doesn't work either way, as the companion has no inventory capacity, and my character certainly has nothing that would be capable of containing a spear, and the hands are not used as the receiving end of trades), but requesting the companion to wield it is met with a refusal as the spear is considered a superior weapon, and orders to drop things that aren't used are met with the message that there's nothing that's not used.

### Steps to reproduce

1. Start a standard Innawoods start.
2. Recruit the starting NPC.
3. Spawn a stone axe (or anything else that isn't a good weapon).
4. Try to get the companion to wield the axe.

### Expected behavior

Either the availability of a direct order to wield a specified item, or a confirmation request (e.g. "The weapon I'm currently using is better. Are you sure you want me to switch to this item?").

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 4f45027 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

While Innawoods is hit particularly by this due to a lack of abundant carried containers, I don't think the issue itself is mod specific.

**Comment by NetSysFire** [comment]
Sounds plausible. I wonder if this is related to #60748, but its incredibly vague, yet it sounds vaguely the same.

**Comment by PatrikLundell** [comment]
There is a possible relation, but as you say, there isn't really anything to say what that person's problem actually is.

**Comment by NetSysFire** [comment]
Why close?

**Comment by PatrikLundell** [comment]
Closing the issue, as I found the hand ARE actually valid trade targets. However, the basket attached to the hand blocks the wielding of two handed items. Thus, it would be better with a trade response message informing you of why you can't receive the trade.

**Comment by PatrikLundell** [comment]
Something weird is actually going on.

Here I've given my companion a stack of rocks to wield, and after it has been carried back I tried to trade for it. For some weird reason the companion refuses to trade items away because there's no room for the non existent trade in the other direction:
![Screenshot (259)](https://user-images.githubusercontent.com/22739822/190229538-592c48e2-818f-4aa1-a92d-9eadbbe3f490.png)

This is not an isolated case, and can be worked around by asking the companion to equip the straw basket (which somehow works when wielding two handed item).

I've also seen inconsistencies in what I can carry in the basket, which sometimes is three, and sometimes four standard rocks (i.e. not flaked etc.).

**Comment by PatrikLundell** [comment]
Something weird is actually going on.

Here I've given my companion a stack of rocks to wield, and after it has been carried back I tried to trade for it. For some weird reason the companion refuses to trade items away because there's no room for the non existent trade in the other direction:
![Screenshot (259)](https://user-images.githubusercontent.com/22739822/190229538-592c48e2-818f-4aa1-a92d-9eadbbe3f490.png)

This is not an isolated case, and can be worked around by asking the companion to equip the straw basket (which somehow works when wielding two handed item).

I've also seen inconsistencies in what I can carry in the basket, which sometimes is three, and sometimes four standard rocks (i.e. not flaked etc.).
