### ISSUE TITLE
Obsoleted rail rifle ammo should not be craftable

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#60987]
### Describe the bug

#39438 obsoleted rail rifles, but not their ammo. The ammo has been sitting there, taunting me. Just look at it!

https://github.com/CleverRaven/Cataclysm-DDA/blob/b991a1bab26d0fb8a6f9068ab4e9c9639ab76e26/data/json/items/ammo/metal_rail.json#L6

### Steps to reproduce

Open crafting menu
Cry (optional)

### Expected behavior

It should not be possible to craft ammo without function or purpose.

### Versions and configuration

8fdb861

**Comment by robotic-gamer** [comment]
the ammo should probably be shifted to the aftershock mod given that it is still used there.
