### ISSUE TITLE
Escape stone in inventory permanently locks you there after update. 

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#60988]
### Describe the bug

If you have an escape stone from a portal storm event, they automatically activate after throwing an error stating they are not allowed to have charges.  

If you have thrown it on the ground before upgrading, as soon as you approach the escape stone, the error occurs and it kills you by smashing you into the grass. 

### Steps to reproduce

Have an escape stone from before 9-10-2022 update. 

Update to 9-14-2022 experimental.

Wait for game to throw the error. 

### Expected behavior

Not being trapped or killed?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 913d296 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]
]

### Additional context

 DEBUG    : Item escape_stone was loaded with charges, but can not have any!

 FUNCTION : io
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\savegame_json.cpp
 LINE     : 3040
 VERSION  : 913d296

**Comment by irwiss** [comment]
Reproduction save; [Peach.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10396671/Peach.zip)
Load it and wait a few turns

**Comment by irwiss** [comment]
Possible fix;
```patch
From 31601a508043b4f3841cb3809a28f45da47691a5 Mon Sep 17 00:00:00 2001
Date: Thu, 12 Jan 2023 00:54:26 +0200
Subject: [PATCH] Obsolete escape_stone, move functionality to portable_portal

---
 data/json/items/nether.json                |  6 +++---
 data/json/obsolete.json                    | 11 +++++++++++
 2 files changed, 14 insertions(+), 3 deletions(-)

diff --git a/data/json/items/nether.json b/data/json/items/nether.json
index 2fa1d95001..5c7e0601f7 100644
--- a/data/json/items/nether.json
+++ b/data/json/items/nether.json
@@ -1,7 +1,7 @@
 [
   {
     "type": "TOOL",
-    "id": "escape_stone",
+    "id": "portable_portal",
     "name": { "str_sp": "portable portal" },
     "color": "magenta",
     "use_action": {
@@ -20,7 +20,7 @@
     "id": "unstable_rift",
     "name": { "str_sp": "unstable rift" },
     "color": "red",
-    "copy-from": "escape_stone",
+    "copy-from": "portable_portal",
     "use_action": {
       "type": "effect_on_conditions",
       "description": "Seems like a random spatial distortion.",
@@ -33,7 +33,7 @@
     "id": "calming_stone",
     "name": { "str_sp": "calming anomaly" },
     "color": "red",
-    "copy-from": "escape_stone",
+    "copy-from": "portable_portal",
     "use_action": {
       "type": "effect_on_conditions",
       "description": "Seems like it could calm local conditions.",
diff --git a/data/json/obsolete.json b/data/json/obsolete.json
index 0ba94011a0..cf13637565 100644
--- a/data/json/obsolete.json
+++ b/data/json/obsolete.json
@@ -1039,6 +1039,17 @@
     "volume": "175 ml",
     "pocket_data": [ { "pocket_type": "CONTAINER", "rigid": true, "max_contains_volume": "170 ml", "max_contains_weight": "450 g" } ]
   },
+  {
+    "type": "TOOL",
+    "id": "escape_stone",
+    "name": { "str_sp": "portable portal" },
+    "color": "magenta",
+    "volume": "250 ml",
+    "weight": "250 g",
+    "symbol": "@",
+    "description": "This defies easy description, it feels solid but the surface is yielding.  Looking at it you have a strange desire to call it a door.",
+    "flags": [ "SINGLE_USE" ]
+  },
   {
     "id": "bio_railgun",
     "type": "bionic",
-- 
2.36.1.windows.1
```

This obsoletes old item and renames the id to new one
This means players that previously had escape stone will have to spawn a `portable_portal` (matching the new name given to it in one of previous PRs) via debug menu
