### ISSUE TITLE
Trying to place makeshift chemical crafting appliances instead places different appliances, sometimes gives errors

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#60995]
### Describe the bug

When I try to place an any appliances related to ammonia production, I get an error message saying "item ammonia_machine_reactor is not base item of any appliance!", or a similar error for the corresponding item of whichever other appliance I am trying to place. After pressing either space or i, I find that, instead of the appliance I was trying to place, I have instead placed a standing lamp.

Something similar happens with nitrogen generators: while it doesn't give me any error messages, it does place a makeshift water electrolyzer instead of a makeshift nitrogen generator.

### Steps to reproduce

1. Try to place any appliances related to ammonium production
2. See the error message
3. See a lamp where your desired machine should be

OR

1. Try to place a makeshift nitrogen generator
2. See a makeshift water electrolyzer where your makeshift nitrogen generator should be.

### Expected behavior

I expect that, when I try to place the intended appliance, I will get the intended appliance where I place it.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 32ee0b1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Useful Helicopters Experimental [useful_helicopters],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Cooler Versatility [coolervers],
    Custom Bionics [custom_bionics],
    XEAS [XEAS]
]

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture_and_terrain/appliances.json#L486-L601 all the ammonia related appliances have ` "item": "ammonia_machine_reactor",` instead of their corresponding base item set

**Comment by AmarinReyny** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture_and_terrain/appliances.json#L486-L601 all the ammonia related appliances have ` "item": "ammonia_machine_reactor",` instead of their corresponding base item set

So, should I change it to the corresponding base item set?

**Comment by irwiss** [comment]
Yep, they should match the component in the construction.json - e.g. `ap_electrolyzer_makeshift` should have `electrolyzer_makeshift` as it's "item"

**Comment by AmarinReyny** [comment]
> Yep, they should match the component in the construction.json - e.g. `ap_electrolyzer_makeshift` should have `electrolyzer_makeshift` as it's "item"

Excellent. Thank you! I'd upload the fix as a PR, but I don't know how to do that...

**Comment by anoobindisguise** [comment]
#60104
I already had a fix for this pending for awhile

**Comment by AmarinReyny** [comment]
> #60104 I already had a fix for this pending for awhile

Ah, okay. Thank you!
