### ISSUE TITLE
whitelist does not prevent nested containers to hold items

### ISSUE THREAD

**Issue by StevenLesseps** [CleverRaven/Cataclysm-DDA#60992]
### Describe the bug

First aid kit box allows spare parts like shotgun hulls and rifle primers to go inside prescription bottles and supplement bottles with pills even though it has only drugs whitelisted.

### Steps to reproduce

1. Get empty first aid kit box
2. Whitelist drugs category in pocket settings
3. Insert prescription bottles, supplement bottles etc. containing multivitamins, aspirin, etc. No other such bottles should be in player's inventory elsewhere, inside the said box only.
4. Pickup some spare parts - rifle primers, shotgun hulls, ammo casings.
5. Picked items go inside the bottles.

### Expected behavior

When I whitelist category I expect it follow the nested containers inside that pocket as well, otherwise I will have to set whitelist for each bottle.

### Screenshots

![image](https://user-images.githubusercontent.com/72020112/190106121-b8c91092-cd6b-47fe-93b2-046d70aa8dc5.png)
![image](https://user-images.githubusercontent.com/72020112/190106427-d8fbaeb1-0d9f-4dda-91cf-8be2048138fe.png)

### Versions and configuration

9c88952 (tiles)
2022-09-13-0704
Windows x64, Experimental
English

**Comment by Je55eah** [comment]
Be thoughtful please, I am about to report a competing issue. I often want pickup to go into a nested container rather than the big one.
