### ISSUE TITLE
[Innawood] starting NPCs are often doomed asthmatics

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#60990]
### Describe the bug

The asthmatic starting NPC is fairly common and their quest is reasonable in the base game. However, they ought to be banned from the Innawood mod since you don't have any reasonable chance to find an inhaler before they die.

### Steps to reproduce

1. Make Innawood standard start.
2. Talk with the starting NPC and ask if you can do something for them.
3. Repeat the steps above until you get an asthmatic NPC.
4. Realize you'd starting with a soon to be dead NPC.

### Expected behavior

Those NPCs doomed to die should be purged from the set of available mod NPCs on account to already having succumbed to their disease.

A worse alternative would be to make inhalers craftable from a twig and two leaves, or something like that.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 4f45027 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

**Comment by Light-Wave** [comment]
The inhaler quest is overwritten in Innawood with a quest to get some spurge tea. See [data/mods/innawood/npcs/missiondef.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/cbc6fcd93c341dbb37bb5d476b88885275144b95/data/mods/innawood/npcs/missiondef.json).
Spurge tea is autolearned in Innawood and requires cooking 1 and survial 1. It should be perfectly possible to get that before the NPC dies.
