### ISSUE TITLE
diagonal movement allows zombies to cross walls of cars

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#61003]
### Describe the bug

if any creature move diagonally they can go in and out cars just like ghosts

### Steps to reproduce

leave your car in a diagonal position in a way that you make sure the zombie would move diagonally and enter the vehicle with no difficulties

### Expected behavior

the protections of the vehicle would work equally well, regardless of the direction the creature is comming from. I am favourable to surprises in the game, the problem with this however is that it straight out limits the player and forces you to be overly conservative and is not even a surprise, it is just a given.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Base System release 2.7; Release: 2.7; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: Língua do sistema []
- Mods loaded: [
    Dias escuros à frente [dda],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

maybe adding vertexes of square as variables, particularly for objects, and propagating vehicle configurations and states from the tile automatically could be a solution

**Comment by Hirmuolio** [comment]
Master branch has part duplication feature that blocks off diagonal entries.

**Comment by Zireael07** [comment]
0.F is veeerry outdated by this point
