### ISSUE TITLE
Are trapdoor spiders intended to migrate all over the place?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61017]
### Describe the bug

When I started the game I found trapdoor spider traps in a bunch of trees, and stayed well clear of those. However, after 18 days these buggers have dug mounds all over the place without actually placing any new trapdoors anywhere.

### Steps to reproduce

1. Start a [Innawood] game with trapdoor spiders somewhat near.
2. Detect the traps and stay well away from them and any spiders that may be visible.
3. Wait.
4. Found that the buggers have tilled themselves over several world tiles and threatening to surround or overwhelm you.

### Expected behavior

Trapdoor spiders should stay close to their doors, only leaving to chase prey, and then return to their doors, rather than chase animals all over the place (a guess: I've seen some animal corpses, but only near to their original location) and then stay there to migrate further.

### Screenshots

The spiders started in the wooded tile at the bottom right corner of the screenshot.

![Screenshot (260)](https://user-images.githubusercontent.com/22739822/190378536-5a840694-0aa3-4902-aaaa-2fca127f73a8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 4f45027 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

I sort of verified that the spiders were responsible by saving the game and then walk around the mounds (still well away from the original location), and had the companion grabbed by a spider. As expected, fighting it would result in death unless managing to run away (or save scum) when having neither armor or weapons (or skill).

On the other hand, there's another trapdoor spider group a bit further away that I've passed by somewhat frequently, but with no indication of mound generation (or corpses).

There's also a nearby mound filled area I've avoided because of the worm indication, but saving, walking around there, and save scumming has not given any indication of what caused them. I don't see those mounds spreading either.

Edit: Gave up the save after seeing a spider from the crafting spot. Getting overrun happened faster than expected...

**Comment by Venera3** [comment]
Yeah, trapdoors are weird and need a pass before stable. I'm self-assigning it to make sure it happens, but if somebody wants to tackle it in the meantime that's even better.
