### ISSUE TITLE
Containers can have undefined max_contains_weight

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#61035]
### Describe the bug

JSON_INFO.md says `max_contains_weight` is mandatory.

`max_contains_weight` is not mandatory.

See also #61034 and https://discord.com/channels/598523535169945603/598529174302490644/1020198227913486358 (development discord)

CDDA will not throw errors if a container's `max_contains_weight` is undefined, it *displays* (possibly it does not actually set it?) an arbitrarily high value instead (something like 2,000,000kg). However, this causes errors - if an itemgroup tries to spawn multiple of a contained item it instead spawns multiple containers, each containing 1 of the specified item. Below is a boilerplate version of the problem, where any `any_old_item_2` will spawn as 2 containers of 1 each.

```
{
    "id": "duplicating_containers",
    "type": "item_group",
    "subtype": "collection",
    "entries": [
      { "item": "any_old_item", "charges-min": 1, "prob": 40, "container-item": "jug_plastic", "sealed": false },
      { "item": "any_old_item_2", "count": 2, "prob": 100, "container-item": "undefined_weight_container", "sealed": false },
    ]
  }
```

### Steps to reproduce

Use the above boilerplate itemgroup, but substitute `ammonia_liquid` for `any_old_item_2` and `pressure_tank` for `undefined_weight_container`. Look at spawns. Notice you will always get 2 pressure tanks of liquid ammonia.

### Expected behavior

The game should throw an error during loading if a mandatory field is missing. 

### Versions and configuration

https://github.com/CleverRaven/Cataclysm-DDA/commit/b9c53661134207d13f0ec466a06cd98a5437b08a

**Comment by Hirmuolio** [comment]
Related; #60636
