### ISSUE TITLE
Add use action to smartphone for alarms

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#61039]
### Is your feature request related to a problem? Please describe.

The only way to use the alarm function on a device is to be prompted right before trying to sleep.

### Solution you would like.

Add a use action to devices with the ALARM flag to manage and freely set an alarm to go off daily, without needing the device in the inventory.

Smart devices could have the additional feature of setting multiple alarms that goes off just one time or repeats throughout certain days of the week.

Multiple alarms would benefit characters that are heavy sleepers.

The alarm could stop on it's own after a few minutes, or go off indefinitely, the battery of the device should slowly drain while the alarm is going off.

### Describe alternatives you have considered.

Also adding a timer function to smartphones to have an alarm go off after a set amount of time. 

### Additional context

![image](https://user-images.githubusercontent.com/50155659/190596838-79adabc4-04bf-4d3a-a5f7-e079ddccb5b6.png)

**Comment by NotSeawhite** [comment]
IIRC, you can set alarms by pressing `|`.

**Comment by Entity-y** [comment]
I must have missed that while looking through the key bindings, as the binding says that key is for waiting and nothing about an alarm.

That alarm interface would be good to work off of to manage multiple alarms. The minimum amount of time for setting an alarm is 30 minutes, being able to input an exact time and have it repeat daily would be a step to the right direction.

**Comment by Quintovir** [comment]
The current alarm functions are more a timer than an alarm.
I would like to see an actual alarm clock where you set the time for it to go off. I would use this for when I'm trying to fix my sleep schedule by setting the "time to go to sleep" alarm 30-60 minutes from the time I woke up last.
Bonus feature would be multiple timers that can be customized for days, hours, and minutes. This would be useful for when I'm trying to keep my followers busy doing base mission with as little downtime as possible.
