### ISSUE TITLE
Craftig pelt or fur clothing needs a tool with fabric cutting qual of 2

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#61048]
### Describe the bug

I don't know if its a bug, but right now the only tool with fabric cutting qual of 2 is kevlar shears, or maybe  the tailor's kit, but you need kevlar shears to craft this.

This makes the crafting of any pelt or fur clothing nearly impossible without high-tech like kevlar...

### Steps to reproduce

1. Make a player with all recepies known.
2. Search for fur or pelt clothing in the crafting menu
3. Look at the needed tools / quality

### Expected behavior

You should be able to cut fur or pelt with simple scissors

### Versions and configuration

Win 10
Experimental Version fd6463d4
Build 2022-09-16-0958

**Comment by nopenoperson** [comment]
yeah many of them need fabric cutting 2 that only the kevlar shears have
