### ISSUE TITLE
"Loaded bad ter!" exception for temple_stairs and temple_finale after update

### ISSUE THREAD

**Issue by MrDraMaster** [CleverRaven/Cataclysm-DDA#61050]
### Describe the bug

Loading my save, "Loaded bad ter!" exceptions were thrown for "temple_stairs" and "temple_finale"

### Steps to reproduce

1. load game with "temple_stairs" and "temple_finale" terrain in the overmap files
2. see exceptions

### Expected behavior

no exceptions thrown, "Strange Temple" still visible on the overmap

### Screenshots

This used to be a "Strange Temple"
![grafik](https://user-images.githubusercontent.com/37799858/190699543-ee0134b6-b822-42d5-a559-f3b420f98528.png)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: fd463d4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Last time I played on this version without issue: https://github.com/CleverRaven/Cataclysm-DDA/commit/5dee013dc46812184604ff4bfd5d7f1270ffe292

I'm guessing that this PR https://github.com/CleverRaven/Cataclysm-DDA/pull/60046 didn't include some migration code?

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9586084/debug.log)

ZIP of the two overmap files in my save that have the terrains:
[temple_terrain.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9586191/temple_terrain.zip)

**Comment by ChromePoptart** [comment]
I can confirm this.

- Just updated from 9c889520b13268ce8a431a1c9e054b6ee9ae6ca3 to cdcb0713fee71d4186c2f242c1b8309d93911944
- Only one temple_finale error and many (20-30?) temple_stairs errors encountered when first loading save after update.  (I didn't try saving and opening again to see if the errors went away.)
- I haven't actually encountered the temple while playing this character/world, so I can't comment on what happened to it after the update.  I also don't know where the temple would be in the overmap, and so don't know what to include save-game-file-wise that might help.


==========

 DEBUG    : Loaded bad ter!  ter temple_finale

 FUNCTION : void overmap::unserialize(std::istream&)
 FILE     : src/savegame.cpp
 LINE     : 552
 VERSION  : cdcb071

[debug__temple_finale.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9591776/debug__temple_finale.log)

==========

 DEBUG    : Loaded bad ter!  ter temple_stairs

 FUNCTION : void overmap::unserialize(std::istream&)
 FILE     : src/savegame.cpp
 LINE     : 552
 VERSION  : cdcb071

[debug__temple_stairs.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9591775/debug__temple_stairs.log)

==========

**Comment by ChromePoptart** [comment]
/confirm
(see above post -- not sure if adding "/confirm" via editing an existing post will cause the tag to change)

**Comment by ChromePoptart** [comment]
/confirmed
(see above post -- not sure if adding "/confirmed" via editing an existing post will cause the tag to change)
