### ISSUE TITLE
Craftable foot crank

### ISSUE THREAD

**Issue by Beatdotroot** [CleverRaven/Cataclysm-DDA#61054]
### Is your feature request related to a problem? Please describe.

it doesn't make a whole lot of sense that, despite how advanced a survivor may be at metalworking and mechanical crafting, they cannot make a foot crank, which appears to be just a few gears and a chain.

### Solution you would like.

The foot crank should be craftable, perhaps with mechanics and fabrication involved.

**Comment by Zireael07** [comment]
dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/59213

ref: https://github.com/CleverRaven/Cataclysm-DDA/pull/42497
