### ISSUE TITLE
Stone spear worse than wooden spear in every way

### ISSUE THREAD

**Issue by Beatdotroot** [CleverRaven/Cataclysm-DDA#61052]
### Describe the bug

The stone spear, despite taking significantly more skills and time than the wooden spear, is worse off than the wooden spear in every way.

### Steps to reproduce

1: Look at the stats of the wooden spear
2: Look at the stats of the stone spear
3: See the the wooden spear has universally better stats

### Expected behavior

I expect the stone spear to operate as a better weapon than the wooden spear.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: fd463d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Mythical Martial Arts [MMA],
    Mining Mod [Mining_Mod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Alternative Map Key [alt_map_key],
    Gun Cotton [guncotton],
    Generic Guns [generic_guns],
    Blaze Industries [blazeindustries]
]

**Comment by anoobindisguise** [comment]
Copper spear is 22 pierce, stone spear could easily be 23-25 + possibly STURDY. Although I don't know how durable a piece of hard flint is, the stone spear has quite a bit of work put into its construction so it could probably be justified. Compare to steel spear with 32 damage.

**Comment by PatrikLundell** [comment]
A problem with sharp stone (such as obsidian, but it should hold for flint as well) is that while it can be extremely sharp it's also brittle, so it would chip easily. Thus, I wouldn't make it sturdy.

**Comment by AirRice** [comment]
> A problem with sharp stone (such as obsidian, but it should hold for flint as well) is that while it can be extremely sharp it's also brittle, so it would chip easily. Thus, I wouldn't make it sturdy.

Due to wood having less chip resistance than stone the stone spear would break if the game considers the wood stick part to have broken, which doesn't quite reflect the thinking here, but that's not really a problem with this issue specifically. I'll probably put in a small scale PR for this.
