### ISSUE TITLE
Gelled gasoline is not associated with the AAA guide book

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#61064]
### Describe the bug

[HHGC](https://nornagon.github.io/cdda-guide/#/item/gelled_gasoline) mentions AAA Guide as a reference for Gelled Gasoline, but the book never mentions any recipe.

My PC with 3.7 practical skills in applied science and holding the AAA Guide cannot craft the gelled gasoline.

### Steps to reproduce

Debug applied science to 2 or higher.
Debug and read AAA Guide.
Check craft screen. No gelled gasoline.

### Expected behavior

The references for gelled gasoline should be updated, please.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/190838683-574a7239-5fb6-4f77-a877-9a8e5fc0e659.png)
![image](https://user-images.githubusercontent.com/29348635/190838698-8781b78f-d92d-479b-bcfd-1c3afdd1b84b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: fd463d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries]
]

**Comment by RenechCDDA** [comment]
It does, gelled gasoline is one of the recipes which is aliased as "Stuff THE MAN doesn't want you to know".

Make sure you have the actual *disguised* AAA guide and not the tourist's driving manual. They have the same display name because the anarchist's cookbook version is disguised.

**Comment by jeffplata** [comment]
Oh. Okay. It's clear now.
