### ISSUE TITLE
Updated vehicle action menu has 2 'e' shortcut keys

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#61065]
### Describe the bug

Updated vehicle action menu has 2 'e' shortcut keys. And it broke muscle memory for getting off controls, shift+6, Enter.

### Steps to reproduce

Press shift+6 on a drivable vehicle; mine is a motorbike.

### Expected behavior

Expecting no duplicated shortcut keys and consistent placement of menu items. The previous press e while on vehicle controls brings up the examine vehicle screen feels more intuitive.

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/190840193-1211b3ed-07d6-41bc-b78d-cae8a4724c0f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: fd463d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries]
]

**Comment by irwiss** [comment]
Your old keybinding has been saved in your config, if you want the new one you'll have to delete keybindings.json file in your config directory, or press `^` then `?` and rebind "Toggle engine" to `s` or something else you like

**Comment by jeffplata** [comment]
Any way to rearrange the menu items? I want the old sequence.

**Comment by Night-Pryanik** [comment]
Duplicate keybindings is due to OP's config, so this is a non-issue. Rearranging menu items isn't possible through ingame means.
