### ISSUE TITLE
Recrafted Pump Fire Drill Out of Fuel when put into hiking backpack

### ISSUE THREAD

**Issue by SmurfzXD** [CleverRaven/Cataclysm-DDA#61076]
### Describe the bug

Crafting a refueled Pump Fire Drill and wielding it has it show the correct like new fuel level. As soon as I put it into my hiking backpack it reverts to Fuel: almost completely burned out.

### Steps to reproduce

1. Recraft Pump Fire Drill with Plank
2. Wield/examine Newly crafted Pump Fire Drill and see refreshed fuel.
3. Place into backpack and see that the Fuel level reverts back to almost burnt out and cannot be used.

### Expected behavior

Retains the refreshed charges when placed into backpack.

### Screenshots

![in inventory pre craft](https://user-images.githubusercontent.com/13267755/190864073-9bb28ba4-56e8-41a2-b8cc-0d76271f3400.png)
![post craft](https://user-images.githubusercontent.com/13267755/190864104-4fb08aaf-893a-42b0-9799-91d94a7dc08e.png)

![pump drill gif](https://user-images.githubusercontent.com/13267755/190864663-ab147696-712f-4840-9d18-6181a956cfce.gif)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 6a176f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Innawood [innawood],
    DinoMod [DinoMod],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Retains charges as long as it isn't put into the backpack.

Save file attached.

[Naples Park_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9592034/Naples.Park_copy.zip)

**Comment by PatrikLundell** [comment]
I suspect I had the opposite case: a drill that didn't seem to have its charges depleted (every time I examined it it was claimed to be almost full). I've used up one batch of tinder, and was somewhere on the second one (and might have found some while foraging as well).

In my case I had the drill lying in my pile-of-stuff all the time except when I needed to light a charcoal smoker or a smoking rack, so it frequently passed out of the reality bubble.

**Comment by SmurfzXD** [comment]
Yeah I saw your post when initially combing to see if this was reported already.  Recently remembered about the Fire Piston and just swapped to that as I have no clue what could cause this behavior. I only really know how to make crafting recipes at the moment.
