### ISSUE TITLE
Many rigid armors cannot actually be worn as full sets due to coverage overlap, including riot armor, plate armor, etc.

### ISSUE THREAD

**Issue by Malorn-Deslor** [CleverRaven/Cataclysm-DDA#61086]
### Describe the bug

Many rigid armors currently can only be partially worn. For example, with riot armor you cannot wear a pair of hard arm guards which are supplied with the riot gear. Nor can you wear the hard leg guards with the riot armor as the riot armor provides partial coverage of the arms and legs.

This becomes MUCH more of a problem when dealing with plate mail, with a cuirass making it impossible to wear any sort of rigid leg or arm armor at all, despite only providing 19% coverage. This is obviously not intended or realistic, since a cuirass was always designed to overlap with leg and arm protection.

Even more oddly, you can assemble cuirass, leg and arm plate into a full set of plate mail which can be worn, but only if you have the entire set, and only if they are all of the same material quality. So clearly these are meant to be worn together. Medium Steel chest-plate and it's variants all have the same issue.

### Steps to reproduce

Spawn any chest piece.
Wear it.
Spawn arm or leg from the same set.
Try to wear those as well.

### Expected behavior

I would expect to be able to wear different parts of the same armor set that were historically worn together and can be worn together in the real world. 15% coverage should not be completely preventing the wearing of other items which are rigid. Or they should not be providing such tiny coverage and thus preventing wearing other armor.

My suggestion would be to have a set threshold of coverage which locks out other rigid armors, perhaps 20%? And then ensure that all sets intended to be worn together do not provide coverage overlap past that threshold.

### Screenshots

![image](https://user-images.githubusercontent.com/46245363/190882356-50e4b8b0-06dd-4a62-bb87-b7fb40019690.png)

![image](https://user-images.githubusercontent.com/46245363/190882369-1519f5bd-ab3b-4d16-818e-1f75a8fbe5a6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: e8b202d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    No Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by catdach** [comment]
Was unable to reproduce, I could wear the medium steel set pieces together fine with no coverage overlap. 
![image](https://user-images.githubusercontent.com/93795131/191352143-a03a2737-d451-4c33-b1f9-ee5b329ae0cd.png)
Could mix and match with other plate set pieces as well.
![image](https://user-images.githubusercontent.com/93795131/191352971-29eddbc1-3b7f-4e47-aef7-b3b58df8444e.png)

It's true that the riot armor and hard arm/leg guards cant be worn together, but I'm not convinced that they're really supposed to be a set.

not sure what you mean by:
> "pair of hard arm guards which are supplied with the riot gear"

I couldn't find any examples of item groups or professions that include both the riot armor and hard arm guards that don't also include other miscellaneous armors that clearly aren't meant to be worn together. including all the swat and police gear item groups. Except for one named "prison_armor" which is not exactly a standard one.

the hard arm/leg guards are much more commonly paired with the **hard chest guard** item instead.

**Comment by Malorn-Deslor** [comment]
The medium/high/tempered plate armors are the new plate armors, try using the old cuirass and such. Basically, the items that drop off of a feral armored servant or are found in a mansion, that's where I encountered the problem. The new plate armors have arm and leg armor which is not 'rigid' and thus no overlapping problem occurs.

As to riot armor... what arm and leg guards DO you think go with riot armor? Riot armored zombies drop hardened leg and arm guards, and the prison armor room gives you a 'set' of riot armor, riot helmet, and hardened arm and leg guards. The riot armor itself has very low coverage on leg or arm, so it clearly is intended to be paired with something.

![Riot Gear](https://user-images.githubusercontent.com/46245363/191369175-f1dc3881-54a4-490c-a2d6-5d3eeb4cfa98.jpg)

That guy has quite a bit more than 15% leg and arm coverage there. So if riot armor is meant to be standalone, it would need a lot more coverage. I doubt that was the intent, given the way riot armor spawns with leg and arm guards in multiple places.

**Comment by catdach** [comment]
> try using the old cuirass and such.

Tested with the old version of plate mail as well, again it works fine. There is a distinction that the old plate set's arm and leg guards come in pair, while the new sets use individual left and right pieces, so I'm guessing that's what's causing the confusion.
![image](https://user-images.githubusercontent.com/93795131/191373582-119e4328-8e1c-4eba-a907-be7d1b8d2eed.png)

> The new plate armors have arm and leg armor which is not 'rigid' ...

I don't know what to tell you, that's just not correct. 🤷 
![image](https://user-images.githubusercontent.com/93795131/191374473-9f341812-6c5b-4df3-9267-64495e18cadb.png)


As for the riot armor, I'm not sure where you're getting 15% arm/leg coverage from. It has **60/55%** leg/arm coverage, not 15%. 
![image](https://user-images.githubusercontent.com/93795131/191376891-1fd861b7-5149-4984-ba9c-9edbb5b7aa39.png)
it's pretty clearly not just a chest piece, So yeah, I think it's stand alone.

As for the hard arm/leg guards, they are only ever associated with riot armor in prisons. Not at police stations, or police stations, or police cars, or swat trucks. Only prisons. They will drop from "riot-armored zombies" but **only in prisons** and not elsewhere. Like I'm not guessing here, I'm looking at the code that defines how items spawn and what drops from zombies. out of the like 20ish item groups where riot armor appears **at all** there is **only one** that has both which doesn't also have a ton of other miscellaneous armor.

**Comment by Malorn-Deslor** [comment]
Wait... what? Cuirass did conflict... I know it did... hold on. I'll recreate the exact circumtances by spawning and killing a feral.

Ok, I am wearing a Cuirass, no other rigid armor.

![image](https://user-images.githubusercontent.com/46245363/191380669-526204ff-4c4e-4237-870b-acb787d8bf16.png)

I can't put on chainmail leggings, because I can't wear two items on the hip that are rigid.

![image](https://user-images.githubusercontent.com/46245363/191380720-ddcd8d7b-8538-4e9f-a4d1-25e4b79a6771.png)

I can wear high steel leg guards, as you pointed out already.

![image](https://user-images.githubusercontent.com/46245363/191381038-932e0309-3f0e-479e-92da-c35cdc468ef9.png)

And yes, it also blocks sleeves.

![image](https://user-images.githubusercontent.com/46245363/191381253-efb1b332-3a86-4a8f-b6a4-f8fb4dbc7eb5.png)

So yeah, my fundamental problem remains, the ferals were wearing these items, there is no sane reason I should not be able to wear them. I'm glad it's not every piece of armor, but it's still a problem.

**Comment by catdach** [comment]
ooohh freaking **_CHAINMAIL_** yeah that's... yeah, I think see the problem. Well, it's a couple problems really.

**Comment by Malorn-Deslor** [comment]
I...guess? I didn't really realize until this whole discussion just how detailed the body mapping has gotten, down to hips and such. I agree chain-mail shouldn't be rigid, that's certainly true. But maybe it's just overlapping, etc, I hope there is some thought between the various armors, so the rigid problem doesn't happen too often with different arm/leg/chest pairs. Though that does have some realism, we also don't have the easy option of just bending a plate or two to get it to fit.

**Comment by bean-b** [comment]
In terms of riot armor, that armor never really made any sense, and so I've updated the armor to have much more coverage etc
