### ISSUE TITLE
"Dash" effect spells throw up repeated ledge prompts, behave strangely

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#61083]
### Describe the bug

Things get weird if you try to use a "dash" spell, such as "Short leap" from the mutation "Leaping legs" or Xedra Evolved's "Spring-heeled jump", to try and cross empty space. You get repeated "Really step into ledge?" prompts. If you say "No" to all of them, you're moved across without issue. If you say "Yes" repeatedly, you take fall damage, but are still moved across.

When trying to mvoe across Z-levels (with experimental 3D active), attempting to move more than one tile horizontally will also trigger the "Really step into ledge"? message, but choosing "no" causes you to not move at all.

### Steps to reproduce

1. Give yourself Lagomorph and Leaping Legs.
2. Attempt to jump from one building roof to another

### Expected behavior

It just lets me jump across.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/190876520-c51e572c-063f-4bf0-ae3c-033640c3cfa6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 19c4eb4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

**Comment by actually-a-cat** [comment]
Duplicate of #53532?

**Comment by Terrorforge** [comment]
Ah, so it is. Closing this, then.
