### ISSUE TITLE
Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#61095]
### Describe the bug
```

 DEBUG    : Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

    "description": "Slip prevention modifier",
    "mod_type": "x",
    "value":
            ^
             {
      "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
      "override_encumb": true,


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 947
 VERSION  : 29cdbc1
```

### Steps to reproduce

1. Create new world.
2. Try to create new character in that world.

Or try to load any save.

### Expected behavior

Game works.

### Versions and configuration

Build: 2022-09-18-0726 
Version: 29cdbc1

### Additional context

Game works on build: 2022-09-17-0626, version cdcb071

**Comment by KHeket** [comment]
Happens to me too
Seems problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/50143 or [Cataclysm-DDA experimental build 2022-09-17-2114](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-09-17-2114) becouse I have this crash on [Cataclysm-DDA experimental build 2022-09-17-2114](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-09-17-2114) and later versions
@akrieger can you check?

**Comment by BjoHart** [comment]
Same here!

**Comment by akrieger** [comment]
I'm guessing it's not possible to upload a save with this issue. Can you describe if the character has any particular bionics or traits that stand out? Something to do with 'slip prevention' like shown in the error?

**Comment by RDru** [comment]
> I'm guessing it's not possible to upload a save with this issue. Can you describe if the character has any particular bionics or traits that stand out? Something to do with 'slip prevention' like shown in the error?

You can just try to start a new character/game.

**Comment by akrieger** [comment]
I did so last night fixing other bugs but didn't encounter this, is why I ask. Maybe need a fresh master again.

**Comment by akrieger** [comment]
Still can't repro this morning. The relevant block of json is
```
  {
    "type": "character_mod",
    "id": "slip_prevent_mod",
    "description": "Slip prevention modifier",
    "mod_type": "x",
    "value": {
      "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
      "override_encumb": true,
      "limb_score_op": "+",
      "denominator": 6.0
    }
  },
  ```
  
  which definitely has a non-zero denominator.

**Comment by akrieger** [comment]
If you can reproduce the issue, there should be a file at `data/cache/json/` called `character_modifiers.json.1661386734000.fb` or similar (it'll start with `character_modifiers.json` and end in `fb` but the numbers might be different). Can you please upload that to this issue so I can take a look at the compiled json? If your actual `character_modifiers.json` doesn't look like what I pasted there then please upload that also.

**Comment by akrieger** [comment]
Just to make extra sure I downloaded both the original and msvc versions of the reported build and did the same thing (new random world new random character) and didn't hit it.

**Comment by RDru** [comment]
Also checked.
I have downloaded cdda-windows-tiles-x64-2022-09-18-1424.zip
Unpacked it to new folder, clicked 'play now' and the bug still exists.

Here is the whole cache folder since there is no json in there.
[cache.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9594309/cache.zip)

**Comment by akrieger** [comment]
@RDru can you upload `data/cache/`, what you uploaded looks like the `cache/` folder at the root of the game folder.

I have a speculative fix in mind and I'll try to upload a test build for you, but because I can't repro it I can't be sure it's correct.

**Comment by RDru** [comment]
Right. Here is the file.
[character_modifiers.json.1663507380000.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9594405/character_modifiers.json.1663507380000.zip)

**Comment by akrieger** [comment]
Alright, super weird. The parser is supposed to give exactly the same output no matter what but it's giving very different results for you. Can you replace your file with this one and see if that lets the game load correctly for you? I'm trying to diagnose why the file output is all broken.
[character_modifiers.json.1661386734000.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9594486/character_modifiers.json.1661386734000.zip)

Are you running windows with a non-US English default language or codepage? That could be a clue but I thought I handled such cases.

**Comment by RDru** [comment]
Replaced the file. Now there is error in another one. 
` DEBUG    : Error: Json error: data/json/professions.json:358:92: Ratio must be positive

    "sub": [
      { "present": [ "ANTIWHEAT" ], "absent": [ "MEATARIAN" ], "new": [ "cornbread" ] },
      { "present": [ "ANTIWHEAT", "MEATARIAN" ], "new": [ { "item": "meat_cooked", "ratio":
                                                                                           ^
                                                                                            0.72 } ] }
    ]
  },


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 947
 VERSION  : df589a5
`

Something with end of line character?
I have Poland region on Win10.

**Comment by akrieger** [comment]
Can you try the explicit -msvc build? I'm testing some things now. I'm not sure it's EOL related but an error on the parser end using locale-dependent parsing functions. https://github.com/CleverRaven/Cataclysm-DDA/releases/download/cdda-experimental-2022-09-18-1424/cdda-windows-tiles-sounds-x64-msvc-2022-09-18-1424.zip

**Comment by akrieger** [comment]
Testing my hypothesis in https://github.com/akrieger/Cataclysm-DDA/actions/runs/3077961768 and seeing if the non-msvc builds are using locale dependent parsers.

**Comment by RDru** [comment]
Tested on that msvc build and it works fine. Started a new world and character, saved, loaded it.

**Comment by akrieger** [comment]
Great, thanks for confirming. I'll put a fix in a minute.

**Comment by akrieger** [comment]
-confirmed

**Comment by Zigoos** [comment]
I still have this error.


` DEBUG    : Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

    "description": "Slip prevention modifier",
    "mod_type": "x",
    "value":
            ^
             {
      "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
      "override_encumb": true,


 FUNCTION : bool main_menu::load_game(const string&, const save_t&)
 FILE     : src/main_menu.cpp
 LINE     : 999
 VERSION  : 5a82316
`

**Comment by akrieger** [comment]
FTR I still cannot reproduce this, despite setting my Windows locale to Polish. Calculator shows 0,5 for 1/2 but I can create, save, and load games just fine. Still trying though.

**Comment by RDru** [comment]
I have just tested cdda-windows-tiles-x64-2022-09-24-0526.zip and starting new game, saving and loading works for me.

**Comment by akrieger** [comment]
Seems to be an issue with windows 7 specifically. Possibly a defect in the localized parser implementations for the msvcrt. The cross build links against it dynamically so there's no way to bundle it with the latest msvc redistribution. Maybe installing a more recent version of the redist would work.

**Comment by ilya-pirogov** [comment]
I have exactly the same issue on MacOS. Version `0.F-12404-g25a0ca0fa7`. It was built with the following arguments:
```
make app RELEASE=1 TILES=1 SOUND=1 LOCALIZE=1 LANGUAGES=ru USE_HOME_DIR=1 CMAKE=1
```

Debug log: https://gist.github.com/ilya-pirogov/5f88fafb71b732c73601da8ff4769614

**Comment by akrieger** [comment]
*sighs with bone deep exhaustion*

I'll see about importing https://github.com/google/double-conversion and using that because the `_l` parsers and flatbuffer's locale independent logic seem subtly fallible somehow, probably due to implementation details of the locale functions.

**Comment by akrieger** [comment]
@ilya-pirogov what's the value of `LC_ALL` in your shell environment?

**Comment by ilya-pirogov** [comment]
@akrieger It's undefined. I tried to set it to `LC_ALL=C` but it seems not helping.

**Comment by akrieger** [comment]
```
13:58:31.764 INFO : Cataclysm DDA version 0.F-12404-g25a0ca0fa7
13:58:31.764 INFO : [main] C locale set to en_US.UTF-8
13:58:31.764 INFO : [main] C++ locale set to
...
13:58:31.969 INFO : [options] C locale set to ru_RU.UTF-8
13:58:31.969 INFO : [options] C++ locale set to ru_RU.UTF-8
13:58:31.969 INFO : Setting language to: 'ru'
...
13:58:33.635 INFO : Setting language to: 'ru'
```

I wonder if that is having an unexpected effect. The game starts by setting the locale to en-US. I'll poke around, maybe don't need to do anything special, maybe just hardcode en-US locale for the locale independent parsing.

**Comment by akrieger** [comment]
I can reproduce on mac with the instructions you gave. I'll see if it repro's on other platforms where I'm more comfortable debugging. Thanks for the tip and log.

**Comment by ilya-pirogov** [comment]
I did git bisect and narrowed down this bug to these commits:

https://github.com/CleverRaven/Cataclysm-DDA/commit/ec3f896d5b82938a91bdcbbf71a4e94837741fdf
https://github.com/CleverRaven/Cataclysm-DDA/commit/2833d7a974f9ea8194b15ae5b4dcb13b109586bc
https://github.com/CleverRaven/Cataclysm-DDA/commit/97d6a4836dbe41f7d5155d028d5b38c537acae10
https://github.com/CleverRaven/Cataclysm-DDA/commit/ca9428d3eb71d9dfa468bad3dae25df0282d9e99

Also I figured out that the bug is reproducing only when you create a new world. When I create and start a world in any build before Sep 16 and then update the build to any new version it works just fine.

I hope it can be helpful!

**Comment by akrieger** [comment]
I know where the underlying issue is, the only problem is the workarounds I've applied so far haven't been working. I think it's because the C locale specific functionality is just weird. But I think I have a workaround for your specific case, which I tested and seems to work, so I'll put that up in a PR now.

**Comment by LyranRenegade** [comment]
I just did a fresh install of the latest experimental version cff8200 (tiles)
and have the same error on creating a new world, i do run win 7
