### ISSUE TITLE
Latest experimental can't open mod_tileset.json

### ISSUE THREAD

**Issue by PrecociouslyDigital** [CleverRaven/Cataclysm-DDA#61093]
### Describe the bug

On latest experimental, attempting to load any mod with a `mod_tileset.json` results in the error:
`00:53:54.506 ERROR : src/main_menu.cpp:947 [bool main_menu::new_character_tab()] Error: Failed to open tile info json: data/mods/secronom/mod_tileset.json`

### Steps to reproduce

1. Create a world with a mod that defines a mod_tileset.json
2. Attempt to load the world

### Expected behavior

I would expect that the mod_tileset.json can load correctly

### Versions and configuration

I can't generate a report since I can't load any worlds.
- Windows 11
- CDDA Experimental a3c6a29

### Additional context

[Save Folder](https://github.com/CleverRaven/Cataclysm-DDA/files/9593326/Cuervo.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9593330/config.zip)

**Comment by PrecociouslyDigital** [comment]
Small correction: This doesn't happen with `sees_player_hitbutton`, but does with BL9 and sercronom. I've attatched zips of the exact copies I use of those mods below.
[BL9-master.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9593331/BL9-master.zip)

[Secronom-Zombies-master.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9593332/Secronom-Zombies-master.zip)

**Comment by ZhilkinSerg** [comment]
We don't support third party mods here.

**Comment by akrieger** [comment]
Fixed by #61089
