### ISSUE TITLE
Nuke silos down stairs can spawn upon open space

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#611]
A nuke silo down stairs can spawn on open space, causing you to drop down to the lowest level. From there on there will be no escape. As there is no stairs up.

The up stair can also be encased in rock. If you then jump in the hole around the nuke you will be stuck forever.

**Comment by mugling** [comment]
Closed due to age. Can reopen if reproducible in any recent version of `master`

**Comment by Soyweiser** [comment]
I think it might be fixed, or at least become very very unlikely. Look at this image: http://prntscr.com/bnqg60 the gray areas used to be open space. now they are floor panels. So the likelyhood of spawning above nothing is greatly reduced (if not removed alltogether, assuming the open space/ledges only spawn next to the missile, and the stairs don't spawn next to the missle. (the stairs only seem to spawn in the brown area).

Tried about 10 missile silos of the master.
