### ISSUE TITLE
Crash on save (Windows 11 & Windows 10)

### ISSUE THREAD

**Issue by artphi** [CleverRaven/Cataclysm-DDA#61105]
### Describe the bug

Hello,
I have a crash that occurs when saving a game that has already been saved previously

### Steps to reproduce

1. Create a new word + new character
2. Save your progression and Quit the game
3. Close the game.
4. Restart the game and load the save.
5 Save (or quick save) the game
5. The game crash here and the save is not made

### Expected behavior

I was expecting the game to save

### Versions and configuration

- OS Windows 11
- Game Version: Cataclysm-DDA experimental build 2022-09-20-0515 x64 (MSVC and no-mscv) and previous
- Graphics version: Tiles
- Ingame language: French
- Mods loaded: None

### Additional context

No crash.log avaiable...
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9594971/debug.log)

**Comment by BrettDong** [comment]
Have you tried both the non-MSVC version and the MSVC version?

**Comment by artphi** [comment]
I tried both version...
The game always crash.
It crash on Windows 10 too

**Comment by akrieger** [comment]
Can you upload the save that you're reproducing this issue with?

**Comment by artphi** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9610791/save.zip)
Here is the save folder.

**Comment by artphi** [comment]
I tried with the stable version and it crashes too
I even tried with Cataclysm Bright Nights, and it crashes too.
I tried it on two different computers, and it doesn't change anything.

**Comment by akrieger** [comment]
I can't reproduce the crash with that save. How very strange.

**Comment by artphi** [comment]
Found!!!
The Acronis Anti-Virus found a problem with the application.
It thinks that it is a maleware that modifies files...

![image](https://user-images.githubusercontent.com/1532001/191552129-ffadb803-5088-4727-8391-592eb9805a81.png)

**Comment by NetSysFire** [comment]
This might be something beyond our control. I have no idea about signing binaries but I heard that might be expensive, so that is not really doable for us.
Perhaps the only way is to complain to Acronis and tell them about the false positive. Besides, does this happen with the vanilla windows defender? Defender is usually far more reasonable to deal with and 3rd party AV software tends to be a mess.
