### ISSUE TITLE
Unable to create new character

### ISSUE THREAD

**Issue by Denchik050** [CleverRaven/Cataclysm-DDA#61107]
### Describe the bug

Can't create a new character in any existing or new world

### Steps to reproduce

1. Create new a new world or have old one
2. Try to create a character, chose any world

### Expected behavior

Expected character creation tab.

### Versions and configuration

 DEBUG    : Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

    "description": "Slip prevention modifier",
    "mod_type": "x",
    "value":
            ^
             {
      "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
      "override_encumb": true,

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 947
 VERSION  : df589a5

**Comment by akrieger** [comment]
Probably fixed by #61102. In the meantime, use the -msvc builds which don't have this bug.

**Comment by akrieger** [comment]
Dup of 61095.

**Comment by Denchik050** [comment]
> Probably fixed by #61102. In the meantime, use the -msvc builds which don't have this bug.

thanks~
