### ISSUE TITLE
Add batch savings to the pasta extruder

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#61108]
### Is your feature request related to a problem? Please describe.

It takes far too long to make pasta with the pasta extruder.

### Solution you would like.

Please add batch savings to the pasta extruder. 
Maybe 85-90% with more than 2 units.

### Describe alternatives you have considered.

Eat no pasta :(

**Comment by SmurfzXD** [comment]
I'd stay it takes about the right time, you need to figure you still have to make an extremely long and thin piece of dough before it can be extruded.

**Comment by BjoHart** [comment]
What about this tool?
[https://www.amazon.com/Adamo-Life-Electric-Pasta-Maker/dp/B09TDHXNDN/ref=sr_1_12?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=pasta+machine&qid=1663531569&sr=8-12](url)

**Comment by chrispikula** [comment]
There already is a mechanical, unpowered pasta extruder in game.

**Comment by BjoHart** [comment]
> There already is a mechanical, unpowered pasta extruder in game.

I know. But you get no batch savings from that.
Maybe someone could add batch saving to this pasta extruder?

I mean, most of the time is spent preparing the dough.
It doesn't take long to press the dough through the pasta press.

**Comment by Zireael07** [comment]
+1 to adding batch savings here
