### ISSUE TITLE
Emitting corpses and the pulp action

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#61117]
### Is your feature request related to a problem? Please describe.

So, we all know and love smokers.  That big plum of can't see slowly walking towards you.  

Now.

What if we made it _worse?_  Make it so that even when the zombie dies, it keeps emitting that smoke, or poison gas, or whatever, until you pulp it.

Or, vice versa, have an effect go of when it gets pulped, such as if a boomer, by small chance, didn't explode.  Sort of like an acidic zombie, but with worse consequences.

### Solution you would like.

A way to make zombie corpses still have emit effects that are toggleable by pulp state.

Might be magic effect, might be death effect, I don't know.

### Additional context

@SenpaiSlime mentioned that this might be a bit rough with NPC logic?

**Comment by SenpaiSlime** [comment]
@chrispikula this sounds like two things when i think about it, we need A, zeds to have defineable effect similar to the acidic zeds on pulp (or body destruction past pulping in geneal), and B, for items (the corpse in this instance) to be able to continue using the spell the living version had (is this actually doable already? like this would technically be like a grenade exploding multiple times?
