### ISSUE TITLE
Leather Padded Pants Encumber Arms?

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#61119]
### Describe the bug

Leather-Padded Pants encumber arms for some reason, pants encumber legs afaik

### Steps to reproduce

1. Obtain leather padded pants
2. Check Item encumbrance
3. Realize that doesn't make sense.

### Expected behavior

Pants shouldn't show any arm encumbrance.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.978 (21H2)
- Game Version: e5b3ca9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    The Backrooms [backrooms]
]

**Comment by anoobindisguise** [comment]
Yup, I am aware and am pending a fix for thst shortly. Mb

**Comment by anoobindisguise** [comment]
fix pending in #61063 since those are already modifying those pants to be canvas
