### ISSUE TITLE
Ability to count kills using EoC

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#61129]
### Is your feature request related to a problem? Please describe.

I just wanted to make some stuff, but found there is no such ability in EoC

### Solution you would like.

"u_kill" or "npc_kill" with ability to specify exact id(s), species, fraction or flag, both for monsters and for NPCs

**Comment by Ramza13** [comment]
So what do your goals for this look like?  What you want to do shapes how it would be set up.

So right now what you could do is create a death eoc for a specific monster which would increment a variable upon you killing it.  If you only want to track a one or a few monsters this could work.  

Achievements seem to track this, so another way might be to simply add a dialog condition for achievements or there system.

**Comment by GuardianDll** [comment]
In my case i want to store killed monster and add them to variable, to use in the enchantments, that will be added in #60788
its different from calling EoC like amigara works, and i dont really know how achievements works to use it

**Comment by Ramza13** [comment]
So the question is do you care about all killed monsters or just one or two types?  If its just one or two it can be done right now with death eocs.  If its more than that it probably makes sense to add c++ to handle it.

**Comment by GuardianDll** [comment]
Any. At this moment i plan to use it in Xedra Evolved mod, but i believe it can also be used somewhere else

**Comment by Ramza13** [comment]
Ahh in that case I'll add it to my todo list, might be a good chance to leverage all the achievements stuff as conditions.

**Comment by Zireael07** [comment]
I remember at least one (probably Lua-era) mod that cared about kills and triggered effects either on X kills of specific enemy type or X kills total so there are definite use cases

**Comment by ZhilkinSerg** [comment]
> I remember at least one (probably Lua-era) mod that cared about kills and triggered effects either on X kills of specific enemy type or X kills total so there are definite use cases

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/stats_through_kills/modinfo.json

**Comment by GuardianDll** [comment]
Oh yes, count a danger points can also be reasonable
