### ISSUE TITLE
autopickup

### ISSUE THREAD

**Issue by JDdeen** [CleverRaven/Cataclysm-DDA#61121]
### Describe the bug

game cant save autopickup config

### Steps to reproduce

1. run the game
2. open autopickup manager and make a new rule
3. save changes

### Expected behavior

i expected that autopickup would work?

### Screenshots

![cataclysm-tiles_2022-09-19_15-41-34](https://user-images.githubusercontent.com/5080484/191020022-36960c2c-ab8a-4c55-b58c-0994fbb4ca29.png)

### Versions and configuration

win 10
https://github.com/CleverRaven/Cataclysm-DDA/commit/fa2837c0b29de5a6e03f457ddddb59c1c364d52f tiles
system language

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9598954/debug.log)

**Comment by NoddingCrow** [comment]
Confirmed on Game Version: fa2837c / Tiles.
Additionally existing autopickup rules no longer apply; autopickup.json is still in the config folder where expected so would seem whole thing is pointing at a dummy file.

**Comment by rioM1** [comment]
I have the same issue. It looks like the path for the auto pickup .json is not auto-generated correctly. A workaround that works for me is adding the --configdir <your config folder> argument when launching the game. You can put it in a shortcut's target.

**Comment by Malorn-Deslor** [comment]
Same problem here as well. Glad it wasn't just me, I spent an hour trying to figure out if I messed up my file architecture.

**Comment by akrieger** [comment]
Someday I'll learn the syntax correctly.

/confirmed
