### ISSUE TITLE
Steel ballistic plate description says it require "Tempered carbon steel" for repair, but in fact it needs "chunk of medium carbon steel"

### ISSUE THREAD

**Issue by utechenko-v** [CleverRaven/Cataclysm-DDA#61132]
### Describe the bug

Description of material for a steel ballistic plate is misleading. 
The description says one of its material is "Tempered carbon steel", so the same is required for repair. 
But in fact steel ballistic plate can be repaired using "chunk of medium carbon steel".
Also there is no way to repair a steel ballistic plate using a tailor kit or similar, despite plate is shown in repair menu.

### Steps to reproduce

1. Spawn a partially broken steel ballistic plate, e.g. "|\\"
2. Spawn tools for metal repair - welder kit with battery, welding googles etc.
3. Spawn 100 "chunks of medium carbon steel"
4. Spawn a tailor kit with thread charges
5. Spawn 100 synthetic fabric
6. Activate a tailor kit and try to repair broken steel ballistic plate
7. Activate a welder kit and try to repair broken steel ballistic plate

**Actual result**:
Steel ballistic plate is present in repair menu for the tailor kit, but on select it show message that "Your |\ steel ballistic plate is not made of any of (list of fabric types like cotton, leather etc.)"
Steel ballistic plate can be successfully repaired using welder kit and "chunks of medium carbon steel";

### Expected behavior

Description of a steel ballistic plate should show correct material for repair - medium carbon steel (or chunk of medium carbon steel);
And (probably) it should not be repaired with a tailor kit, and should not be in repair menu for that tool.
Or, in case if tailor kit is allowed - it should repair a steel ballistic plate using synthetic fabric (one of plate's materials)

### Screenshots

![image](https://user-images.githubusercontent.com/16246933/191116854-d4b1491c-ccc8-4680-a95a-9ab7877e7880.png)

### Versions and configuration

build type: windows-tiles-x64
build number: 2022-09-14-0616
commit sha: 5dee013dc46812184604ff4bfd5d7f1270ffe292

mods: dda, no_npc_food

**Comment by Drew4484** [comment]
Specifically a tempered item should require medium carbon steel and a welding **kit**.
