### ISSUE TITLE
Flamethrower doesn't count as source of fire for purpose of lighting up bombs

### ISSUE THREAD

**Issue by ProfaneServitor** [CleverRaven/Cataclysm-DDA#61143]
### Describe the bug

If player has dynamite and flamethrower and nothing else, they can't ignite dynamite's fuse. Attempting to activate dynamite will yield message:
```
You need a source of fire!
```

### Steps to reproduce

1. Spawn dynamite
2. Spawn flamethrower
3. Wield dynamite
4. Try to activate dynamite

### Expected behavior

Characters should be able to use flamethrower's igniter as source of fire. Or at least get a message that it isn't safe.

### Versions and configuration

9c889520b13268ce8a431a1c9e054b6ee9ae6ca3

**Comment by Night-Pryanik** [comment]
1. Adding `"use_action": { "type": "firestarter" }` to flamethrower allows using it as a firestarter.
2. `a`ctivating flamethrower to light a fire on the ground correctly consumes charges.
3. `a`ctivating flamethrower to light a fuse of a dynamite doesn't consume charges.
4. It looks like for some reason `use_charges` doesn't work with `GUN` item type, flamethrowers included.
5. Changing item type of flamethrower from `GUN` to `TOOL` makes lighting a fuse of a dynamite consume charges of flamethrower.
6. Despite I conducted limited testing, and flamethrowers seem to work fine after the change, changing item type feels wrong and may have unintended consequences, and I think it's better to investigate why `use_charges` doesn't work with `GUN` item type (I failed at that).
