### ISSUE TITLE
Can't permanently save auto pickup rules

### ISSUE THREAD

**Issue by TurtsMcSquirts** [CleverRaven/Cataclysm-DDA#61144]
### Describe the bug

Modifying the auto pickup manager's rules and attempting to save returns this error:

Failed to write auto pickup configuration to "": moving temporary file ".9148.temp" failed

The rules are then saved only for the duration of the session, but are then purged when restarting.

### Steps to reproduce

1. Open auto pickup manager
2. Add any rule
3. Attempt to save changes

### Expected behavior

The rules should be permanently saved between sessions, as they have been in previous versions.

### Screenshots

![nopickup](https://user-images.githubusercontent.com/113976440/191207889-4816d166-33df-4efe-8e76-96dfd798c126.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 72591f7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    Xedra Evolved [xedra_evolved],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Dorf Life [Dorf_Life],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by TurtsMcSquirts** [comment]
accidentally closed. my bad.

**Comment by JDdeen** [comment]
you can try one of the temporal solutions in https://github.com/CleverRaven/Cataclysm-DDA/issues/61121

**Comment by akrieger** [comment]
Are these the global or character autopickup rules? Global was fixed by #61125, I thought character rules were always working.

**Comment by TurtsMcSquirts** [comment]
It's fixed now. Thanks!
