### ISSUE TITLE
Add new camp mission to upgrade barebones to field

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#61142]
### Is your feature request related to a problem? Please describe.

I am spiraling into madness as I find I began the wrong kind of camp and have been on that path for over 60 days and several hours of my life, and with no other options and with input from folks on the discord I come here.

### Solution you would like.

I would like the addition of a camp mission which allows transforming a barebones camp to one of the 2 varieties of field camp.

**Comment by RenechCDDA** [comment]
If you simply need to correct a mistake in an existing save, consider use of the hammerspace mutation - it will ignore material and crafting time requirements. You can 'magic' up a new camp in a few IRL minutes.

**Comment by pantherpusher** [comment]
That is not the whole of it as being able to upgrade a barebones camp makes sense

**Comment by PatrikLundell** [comment]
It would probably be rather tricky to implement:
- Field base camps can only be placed on fields, while the barebones one can be placed anywhere. There is no memory of what type of terrain a barebones camp was placed on, however, so there's no easy way to determine whether a field base camp would have been legal to place at the location.
- Any work in progress that isn't present in both variants could cause issues on a transition.
- Logic to allow transitions would cause undesirable ties between different camp types, requiring maintenance each time a new variant was added to the of variants.
- The camp logic does not contain any support for detecting manually ordered constructions as fulfilling any construction order dependencies. This means constructing redundant functionality, possibly right on top of ones already existing (such as a new well replacing the well already constructed manually on that tile).
- Camp construction does not detect anything constructed, so their constructions replace whatever was there with whatever the blueprint said should be constructed.

The purposes of the barebones camp are to allow the placement of a camp anywhere, and to free you of the restrictions of what to construct and where to construct it. It would make somewhat more sense for the barebones camp to somehow support buildings blueprints, but there's neither any support for free placement of blueprints nor any support for detecting whether the blueprint could legally be constructed at that location (which may be in open air, a cave wall, on water, etc.). The field base camp mostly avoids the terrain collision issue by demanding to be place on fields, which are mostly free of obstacles, but you'll get oddities such as trees disappearing without trace if you place it (or any of the field expansions) on such terrain, and would probably get even stranger results of placed on a "field" pond.

**Comment by Zireael07** [comment]
> There is no memory of what type of terrain a barebones camp was placed on

Adding this should be as simple as storing an id variable - and the rest are acceptable limitations imho.
