### ISSUE TITLE
lost keypress on Wayland

### ISSUE THREAD

**Issue by schauveau** [CleverRaven/Cataclysm-DDA#61154]
### Describe the bug

I am running a recent git version as a Wayland application. Everything appears to works fine except that pressed keys are not always detected when a key was already pressed. It is as if a key release event was invalidating all keys that are currently pressed. 
   

### Steps to reproduce

1. Start CDDA as a native Wayland application by setting SDL_VIDEODRIVER=wayland
2. Load a game and position the character so that it can move freely 
3. Press the RIGHT key.
4. Press the LEFT key while keeping the RIGHT key pressed.
5. Release the RIGHT key while keeping the LEFT key pressed.

The character stops moving even though the LEFT key is still pressed.

### Expected behavior

The character should start moving to the LEFT 

The X11 version does that which is, imho, the correct behavior.  

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux bookworm/sid; Release: unstable; Codename: sid; 
    - Wayland Compositor: Sway
- Game Version: 0.F-11358-gcdcb0713fe [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by ZhilkinSerg** [comment]
This is probably something to be fixed in SDL/Wayland.

**Comment by schauveau** [comment]
Probably! I can reproduce the behavior with this small SDL code.
[sdlkey.cc.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/9610548/sdlkey.cc.txt)
I will search in the SDL bug reports.

**Comment by sonphantrung** [comment]
As the issue mentioned above is now closed, should we also close this?

**Comment by ZhilkinSerg** [comment]
> It is still an issue in the experimental build 2022-12-09-0649

It depends on which SDL version you will use to compile the game.

**Comment by ThePeiLin** [comment]
> Deleting or commenting line 3205 of the file sdltiles.cpp might solve this issue, but I don't know if that would cause any other problems.
> 
> ![cdda_bug](https://user-images.githubusercontent.com/47449134/209305907-fef2835d-256e-499f-bffb-436d73585ba0.png)
> 
>
