### ISSUE TITLE
Skills still rusting with Enhanced Memory Banks

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61150]
### Describe the bug

Skills still rusting with Enhanced Memory Banks
List of traits and bionics of my character will be below, I think probles is in forgetful trait

### Steps to reproduce

1) Make character with simular skills
2) Up some skills
3) Wait for a while. At screenshots you can see, that it needed 1 day to rust shotguns from 3 to 2(99%) and athletics from 2 to 1(99%) 
there is also lots of other skills rusted for 1% for this 1 day

### Expected behavior

I installed Enhanced Memory Banks and expected not to loose skills while I have this bionic turned on

### Screenshots

<details>
  <summary>Screenshots</summary>
  
![Снимок экрана (100)](https://user-images.githubusercontent.com/102726167/191242528-ff8f58bf-0860-4790-9586-257deb2315a2.png)
![Снимок экрана (102)](https://user-images.githubusercontent.com/102726167/191242518-3d156a32-7c53-4595-97b8-ebbacd8b22f2.png)

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: cdcb071 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by GuardianDll** [comment]
its because `{ "value": "SKILL_RUST_RESIST", "add": 20 },`, which means you have 20 out of 100 to resist a skill rust. To make it `you can't forget skills you've already learned` 20 must be replaced with 100

**Comment by Terrorforge** [comment]
Duplicate (and confirmation) of #54095

Sounds like an easy fix, though

**Comment by KHeket** [comment]
> its because `bio_memory` has `{ "value": "SKILL_RUST_RESIST", "add": 20 },`, which means you have 20 out of 100 to resist a skill rust. To make it `you can't forget skills you've already learned` 20 must be replaced with 100

Can you make some programming magic and fix this? Becouse I am not computer magician and dont know how



> Duplicate (and confirmation) of #54095
> 
> Sounds like an easy fix, though

That pr and mine - both have labels "need congirmation" but one of it must be "confirmed"

**Comment by GuardianDll** [comment]
> Can you make some programming magic and fix this? 

Only because you're so kind
