### ISSUE TITLE
Translated name resources does not load properly( path_info.cpp )

### ISSUE THREAD

**Issue by EIIKaO** [CleverRaven/Cataclysm-DDA#61163]
### Describe the bug

If you use option USE_LANG, name resources does not load properly.
To put it plainly, if you run c:dda with a non-English setting, the localized name resource will not be loaded properly and the English name resource will be used instead.
As a result, all random names of the world and NPCs will be in English.

### Steps to reproduce
Case 1
1. Set Options-Interface-Languages to [ KO/RU/ZH_CH ]( bacause these languages have localized wolrd names )
2. Create World
3. Confirmed that given non-localized world name

Case 2
1. Set Options-Interface-Languages to [ JA/ZH_TW ]
2. Create World
3. Confirmed that the names of various worlds were given( JA/ZH_TW have only one name for world, ﾄﾑ or Tom )

### Expected behavior

Localized names are generated and given.

### Screenshots

Japanese users should not have any worlds generated except for the one named ﾄﾑ( meaning Tom ).
![001](https://user-images.githubusercontent.com/109350502/191346097-3385d1a8-ba7e-465d-be15-3cc6bfa7c600.png)

This is the only world generated correctly( just kidding )
![002](https://user-images.githubusercontent.com/109350502/191343774-c0114ab4-1d30-4212-b5bb-71c355cdd0ea.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 0.F-11527-g25fd53ce63 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (台灣) [zh_TW]
- Mods loaded: [
    烏日到站 [dda],
    取消 NPC 需求 [no_npc_food],
    真菌節育 [no_fungal_growth],
    生化職業 [package_bionic_professions]
]

### Additional context
Here is an example of my proposed solution.
```diff
diff --git a/src/path_info.cpp b/src/path_info.cpp
index 4debd9434d..c99f0350f3 100644
--- a/src/path_info.cpp
+++ b/src/path_info.cpp
@@ -191,7 +191,7 @@ cata_path find_translated_file( const cata_path &base_path, const std::string &e
     const std::string loc_name = language_option.empty() ? SystemLocale::Language().value_or( "" ) :
                                  language_option;
     if( !loc_name.empty() ) {
-        cata_path local_path = base_path / loc_name / extension;
+        cata_path local_path = base_path / (loc_name + extension);
         if( file_exist( local_path ) ) {
             return local_path;
         }

```
My first issue. I apologize if I have been rude about anything.

**Comment by akrieger** [comment]
Oh hey you even included the fix. That fix looks good to me, and it's my fault, sorry! Do you want to make a PR for it too?

**Comment by EIIKaO** [comment]
I am not familiar with this part at all.
May I leave this to you?

**Comment by akrieger** [comment]
Sure thing, I'll do it right now.
