### ISSUE TITLE
Boots are erroneously labelled as "not repairable."

### ISSUE THREAD

**Issue by Aerin-of-the-Toast** [CleverRaven/Cataclysm-DDA#61162]
### Describe the bug

Several variety of boots (I haven't checked everything, but only noticed with boots so far) are listed in their description window as "This item is not repairable." However, they're still repairable with a sewing needle, as per the norm.

### Steps to reproduce

1. Make a new character with some boots, combat boots, steeltoed boots, etc.
2. Check the item's description window and note it labels the boots as not repairable.
3. Spawn in a sewing needle, sewing kit, tailor's kit, etc.
4. Note that you can repair (or refit or reinforce) the boots regardless.

### Expected behavior

For the boots to list that they're repairable with sewing needles.

### Screenshots

![image](https://user-images.githubusercontent.com/75549031/191346989-91b46371-23c5-4be8-b95d-fd20ade3d39f.png)
From the entry for "pair of boots."

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: a9b1db4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Testing shows that this issue is actual for any armor that have its material(s) defined not in base object, but rather in `armor` -> `material` object. Boots are an example of such armor, amongst many other items.

**Comment by captainego** [comment]
This appears to be a result of calculating the repair tools for an item before we calculate the materials for the complex armor cases.  The necessary change is in Item_factory::finalize_post.  

I have a potential fix in my local build, but I want to do some additional testing and code cleanup before submitting the PR.
