### ISSUE TITLE
Dialogue with Mr.Lapin cause crash

### ISSUE THREAD

**Issue by Dionyse** [CleverRaven/Cataclysm-DDA#61171]
### Describe the bug

When talking to NPC Mr.Lapin, if I choose "Heard anything about the outside world?" and then "Anyone nearby I should meet?" and "Seems like a deal to me.", the game stuck and crashes. Reproduced as well when I generated Mr.Lapin in another world with another character.

### Versions and configuration

0.F.3, with no mods, all default settings

**Comment by Maleclypse** [comment]
Duplicate of #47220?
