### ISSUE TITLE
The JSON crafting flags "BLIND_EASY" and "BLIND_HARD" seem to be bugged

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61178]
### Describe the bug

"BLIND_EASY" causes crafting in darkness to be at 32% of the efficiency of crafting with light (2 minutes -> 6 minutes 11 seconds), while "BLIND_HARD" doesn't allow crafting at all.

### Steps to reproduce

1. Modify the data/json/recipes/tools_primitive.json "recharge" recipes for fire_drill to add the "BLIND_EASY" flag and the recipe for fire_drill_large to add the "BLIND_HARD" flag.
2. Load a game.
3. Move to an area that's dark (may debug change the time or go into a basement. I did the first)
4. Debug spawn both types of fire drills and two sticks.
5. Try the crafting recipes for both.
6. Note that the "BLIND_EASY" one is possible, but at a triple of the time.
7. Note that the "BLIND_HARD" one is noted as being possible but hard, but actually isn't possible with a tellback of it being too dark to craft.

### Expected behavior

"BLIND_EASY" should make a craft possible with no or minimal increase in crafting time while in darkness.
"BLIND_HARD" should make a craft possible to craft in darkness, but at a substantial increase in crafting time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 0.F-11537-g89803505c4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

If the bug is found and fixed, #61177 ought to be changed to use "BLIND_HARD".

Edit: The cause of the issue is that the flags depend on the character skill level exceeding the required skill by an amount, and these recipes don't have any skill associated with them, so the character can't exceed that non existent skill level.
Tested that by modifying the recipes to require the survival skill.

The crafting.cpp Character::lighting_craft_speed_multiplier operation ought to check for the absence of a required skill and ignore any demands for exceeding the level. This could be done either by modifying the operation itself or by modifying exceeds_recipe_requirements() to return 10 when there isn't any requirement, in which case you don't have to change #61177, as it would not make any difference.

**Comment by mqrause** [comment]
It probably works as intended, but the documentation doesn't make it very clear. You need a skill level 2 higher than the recipe requirement when crafting in the dark with `BLIND_HARD`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/89803505c4ed1651a01169f1e8c207a4e86e8b87/src/crafting.cpp#L146-L158

**Comment by PatrikLundell** [comment]
I believe the code should be changed such that an absent skill should make BLIND_EASY being done at no penalty, while BLIND_HARD should be made at an arbitrary reduction, such as 50% speed.
The change should be done in lighting_craft_speed_multiplier, to avoid potential side effects.

I agree the rest of the code probably works as intended, although there ought to have been a separate feedback message for a lacking skill, rather than just say you can't craft.

**Comment by mqrause** [comment]
/confirmed

Kinda late, but yes, the flags not working for recipes without skills is a bug.
