### ISSUE TITLE
Unable to continue an in-progress craft that has not been memorized yet.

### ISSUE THREAD

**Issue by Davidcanvil** [CleverRaven/Cataclysm-DDA#61194]
### Describe the bug

I started making a cuirass, while having fabrication 8 (8 required) but having the recipe from a book, not memorized. Once it reached 10% i stopped to have a drink, After that when i try to continue i get the message "You don't know the recipe for the cuirass and can't continue crafting".

I've done it all in a vehicle with an electric forge, workbench etc, trying to activate it in the workbench or manually or wielding with no luck, always with the books beside me.

### Steps to reproduce

1. Start making a cuirass with fabrication 8 and the recipe not memorized, with the book by your side (welding and metallurgy)
2. at some point in the process stop making it.
3. Attempt to continue the craft.

### Expected behavior

I expected the craft to continue with no issues, In this save i continued other crafts without problems.

### Screenshots

![image](https://user-images.githubusercontent.com/29451978/191704075-9c4be456-a808-4d68-ba3e-26fc0ebe688c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 564b786 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Manual Bionic Installation [manualbionicinstall],
    Portable Autodoc [portable_autodoc],
    Safe Autodoc [safe_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens],
    DinoMod [DinoMod]
]

### Additional context

I'm uploading the save

https://drive.google.com/drive/folders/1VisNHDhMAjPK9QMNXKjxwuWnPwVkVVAX?usp=sharing

_No response_

**Comment by Davidcanvil** [comment]
After trying to find the source of the error I think it may come from the player not knowing the recipe and not having the recipe at hand, but for some reason I am allowed to start the craft. Thus when I try to continue crafting, it checks again for the recipe and the game finds out I do not know the recipe nor I have a book. The book I had is "Welding and metallurgy" which has recipe for sheet metal armors in general, but not plate armors.

**Comment by Torbenbeta** [comment]
Probably related to issue #60810 and pr #60761.

**Comment by Davidcanvil** [comment]
Yeah, it seems it is exactly issue  #60810 , you can then close this one.
