### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by CrackerHax** [CleverRaven/Cataclysm-DDA#61196]
### Describe the bug

If you are wielding a foldable vehicle and activate it, it spawns unfolded version but you still have it wielded as well, so you end up with 2 of them.

### Steps to reproduce

Wield foldable vehicle and activate it.

### Expected behavior

It's supposed to disappear from your inventory.

### Versions and configuration

Windows 10
latest cdda

**Comment by CrackerHax** [comment]
cdda-windows-tiles-sounds-x64-2022-08-29-0151

**Comment by CrackerHax** [comment]
> Too lazy to properly fill out the version info...

Didn't have to do it at all. You should be thanking me, idiot.

**Comment by ZhilkinSerg** [comment]
> > Too lazy to properly fill out the version info...
> 
> Didn't have to use my time to submit a bug at all. You should be thanking me, idiot.

Yes, you should stop wasting everyones time in here.

**Comment by CrackerHax** [comment]
If I didnt know it wasnt a bug now I wouldnt have posted. Are you retarded?
