### ISSUE TITLE
Add more ammo types to the ammunition banker

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#61190]
### Is your feature request related to a problem? Please describe.

I find it frustrating when I want bulk of a not too out there type of ammunition, only for the guy (who's supposed to be the authority post-apocalypse wise when it comes to ammo) to not be willing to give me something like .30-06

### Solution you would like.

I'd like a few more ammunition options to be added to the gunsmith artisan NPC for exchange, likely at a rate that isn't 1:0.9 for the harder to find rounds like 30-06 or 7.62x54R or the magnum handgun rounds

### Describe alternatives you have considered.

A new NPC who specializes in harder to find ammunition but charges exceptionally more for them, maybe having managed to get their hands on some factory production scale hardware and knowing exactly how valuable their stuff is.

**Comment by kevingranade** [comment]
I wouldn't object to this happening,  but we can not support issues asking for arbitrary content additions in the repo, there are too many issues.
