### ISSUE TITLE
Auto pickup only the items, not the containers they're in

### ISSUE THREAD

**Issue by TurtsMcSquirts** [CleverRaven/Cataclysm-DDA#61207]
### Is your feature request related to a problem? Please describe.

Currently, if every item in a container can be found in your auto pickup rules, your character will take the whole container instead of removing the items from the container. This can save a bit of time while looting, as picking up every individual item is slower. However, this also leads to a lot of bloat in your inventory, because containers most often take up quite a bit more volume than the items they hold.

I have many questionably valuable items on autopickup, so frequently my character picks up entire wallets, pairs of pants, coats, backpacks, or even corpses because they contain exclusively things I want. The most amusing offender is kevlar dog harnesses, which are frequently the only item a Z-9 (small enough to fit in some large backpacks) has in their inventory, so I sometimes unknowingly shove an entire dead dog in my bag and wonder why my character is over encumbered.

Containers picked up this way must later be unloaded to properly sort their contents, creating busywork of unloading hundreds of wallets, or digging through stacks of backpacks and pants.

While the current implementation saves my character a bit of game time, in my opinion it should cost less real time. I am grateful for all the time the feature saves overall, even with the small gripes.

### Solution you would like.

Items in containers, with the exception of liquids, sealed foods, or foods in containers which slow spoilage should not be picked up with the container itself.

An ideal solution would be to allow players to exclude certain items from auto pickup, so they would never be taken, even if they contain other items in the rules list. For instance, adding "!*wallet" to exclude wallets using the !. As a bonus, this could help players shorten their rules list by making wildcards more broadly applicable, potentially reducing lag when first loading the list by walking over items.

Tangentially, it would also be cool If my character could automatically remove batteries from electronics, or magazines/bullets from guns without having to take the whole gun/flashlight etc. and unload them later.

### Describe alternatives you have considered.

Maybe add a toggle or operator in the rule text itself that indicates that the character should pick up both the item and its container together.

Alternatively, it could pick up both the item and its container only if both are found in the auto pickup rules list.

A partial solution could be to add an 'Unload' zone to the zone manager that would allow followers or the player to automatically unload all the automatically picked up containers in a square as a job, similar to the current 'Disassembly Work' zone.

**Comment by Terrorforge** [comment]
> An ideal solution would be to allow players to exclude certain items from auto pickup, so they would never be taken, even if they contain other items in the rules list. 

That exists. Just type in the name you want to exclude, go to the right where it says "Include" and hit enter to change it to "exclude".

**Comment by TurtsMcSquirts** [comment]
Wow, I'm blind. Thanks!
