### ISSUE TITLE
[Innawood] Override the bulletin board recipe with something easy

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61201]
### Is your feature request related to a problem? Please describe.

The bare bones base camp requires the manual construction of a bulletin board to be useful. However, the standard bulletin board requires resources that are a bit hard to acquire in Innawood (nails and planks). Therefore, I suggest the recipe for the bulletin board should be overridden by something comparatively simple to construct in that mod.

### Solution you would like.

Construct a "bulletin board" from e.g. 3 sticks and a short string/cord (which would make a tripod) in Innawood, and also make sure the deconstruction/bashing doesn't magic up the standard resources, but rather things based on the local recipe.

A short string/cord requires a little work to get, but not that much.

### Describe alternatives you have considered.

Leave it as is.

**Comment by Light-Wave** [comment]
Having a way to do it without metal sounds perfectly reasonable. Although I don't think 3 sticks offers enough of a structure to put bulletins on. Perhaps a few more would be needed.

Also note that if you create a base camp in a plains tile and choose basecamp version 2, it comes with a bulletin board for free.

**Comment by PatrikLundell** [comment]
Yes, it's specific to the bare bones camp version, as all other versions have a board in a fixed location (varies per camp version), but the bare bones camp can't have one as there's no known location that is safe to place a bulletin board on.
As you point out, you can use field base camp version 2 as an alternative base camp starting point and just ignore the upgrade progression, but you'd then get to camp in the middle of a field with no protection from the elements for quite some time. You'd also have a bit more work adding custom recipes to your camp.

The reason I think the bare bones base camp is particularly suited for Innawood is that it would allow you to mark your starting cave (for the standard starts) as a camp (although camps don't support 3D, so the "basement" won't be included). That would essentially be analogous with how there are base camps for the evacuation shelters.

It can also be noted that the bulletin board is just a McGuffin selected as a rather arbitrary interface item for base camps: it doesn't realistically contain the functionality to order people about. That's the reason I proposed a very simple alternative construction recipe.

**Comment by Light-Wave** [comment]
Sounds perfectly reasonable, although I'd say use a few more sticks and maybe a long cordage instead, to make it somewhat believable that you could make a functional bulletin board from the material.

**Comment by PatrikLundell** [comment]
What about:
- 6 branches/3 long branches
- 1 long string/long cordage string
- 6 tan bark/birch bark?

**Comment by Light-Wave** [comment]
Ah yes, bark. Forgot that existed. That's much better. I approve.
