### ISSUE TITLE
JSONIFY BIO_OP_TAKEDOWN

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#61200]
### Is your feature request related to a problem? Please describe.

BIO_OP_TAKEDOWN is used by zombie wrestlers and several dinos in DinoMod, as well as the bio operator zombies it was designed for. When it fires, it talks about "mechanically" harming the opponent. This makes sense for bio operator zombies but not zombie wrestlers and dinos.

### Solution you would like.

JSONIFY this monster special attack so that a zombie wrestler or dino can do the thing "brutally" instead

### Describe alternatives you have considered.

Create a new monster special attack that mimics the same effects, not sure if this is currently possible

### Additional context

Many players have complained to me about this. Doesn't break anything but it's a chink in the realism armor

**Comment by sonphantrung** [comment]
Aside from the mechanical takedown, there's also `BIO_OP_DISARM`, `BIO_OP_IMPALE` and `BIO_OP_BIOJUTSU`
