### ISSUE TITLE
healing_rate_medicine multiplies healing for every bandaged limb

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#61202]
### Describe the bug

I'm just going to include a pretty picture and a save for easy testing.
![Untitled5](https://user-images.githubusercontent.com/84619419/191776866-c2b6c351-ae64-4212-be90-d4c76384497b.png)

### Steps to reproduce

Load save, bandage and disinfect desired number of limbs, advance 6 hours and compare results to image.

### Expected behavior

My head wounds should not heal faster just because I have bandaged the rest of my broken body. If anything, they should heal *slower* because the rest of my body is hurt.

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: 0.F-11529-gb93112f290-dirty [64-bit] (reporter note: compiled with extra debug messages ONLY)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Powers.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9626827/Powers.zip)

**Comment by RenechCDDA** [comment]
Other issues:

-There is no modifier for healing_awake mutations, which means that mutations which improve healing do not in fact improve the most common form of healing. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/f1527443045cb728e245d6fcfc83ab49092d3ee2/src/character.cpp#L5847

-There are no unit tests for healing_rate_medicine, which is probably why this has only been found now. Unit tests are good. A unit test to prevent regressions would be very helpful.

-When using a slower healing trait (e.g. imperceptive healer), the head seems to heal at a slower rate than it should. It always has a 50% penalty from bandaging, but I would non-torso limbs healing at *3-4x* the rate of the head, even with both of them bandaged. More testing is required to pin down the cause (or if it's just repeated flukes with very low probabilities)

**Comment by andrei8l** [comment]
/confirmed Using steps from OP on a new save with [2023-02-27-0627](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-02-27-0627)
