### ISSUE TITLE
Crash to desktop when killing APIS

### ISSUE THREAD

**Issue by NewOrlanth** [CleverRaven/Cataclysm-DDA#61218]
### Describe the bug

All in the title. 
Killing poor APIS crash the game. 

### Steps to reproduce

Find a bee hive
Find APIS
Kill him

### Expected behavior

APIS dead. Life continue.

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:25 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8110 x86_64
- Game Version: 65b77c9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by Venera3** [comment]
Can you upload your crashlog from /config (though I'm not familiar with the Mac version, so it might drop it somewhere else).

**Comment by NewOrlanth** [comment]
I don't have a crashlog (crash.log i assume ?) anywhere :/. I just have a debug.log but it doesn't seem to be very helpful.

**Comment by TealcOneill** [comment]
@GuardianDll I've killed Apis three times and haven't seen a crash or any other issue.
