### ISSUE TITLE
"none" crafting recipe

### ISSUE THREAD

**Issue by EternalKitten** [CleverRaven/Cataclysm-DDA#61212]
### Describe the bug

There is a "none" recipe which makes no sense.

### Steps to reproduce

1. Go to _Long Cordage Ropes_ in crafting menu
2. Discover "none" recipe there

### Expected behavior

I expect CDDA to be more materialistic. "none" is not a valid recipe.

### Screenshots

![2022-09-23_18-18-17](https://user-images.githubusercontent.com/82908191/191995278-191a1a6f-8eef-40a2-84d8-6dcc4a33ae39.png)

### Versions and configuration

 cdda-windows-tiles-x64-msvc-2022-09-23-0555.zip

### Additional context

You can only see "none" inside this specific menu, it's not searchable.

**Comment by PatrikLundell** [comment]
The issue in the second, unrelated, post has been reported in #61015. Note that this has nothing to do with the original report, so the original report is not a duplicate of that.
(Take away: please don't mix multiple unrelated issues in the same report, as things get messy and confused).

**Comment by EternalKitten** [comment]
Sorry. I just didn't want to report something that might not be a bug.

**Comment by PatrikLundell** [comment]
No worries. However, bug reports are sometimes incorrect (I believe I've been posting such reports myself...), and it's no big deal. You'd just close them yourself if you find out to be wrong, or someone in charge does it when it turns out it's actually intended (or you didn't interpret what was going on correctly).

**Comment by ChromePoptart** [comment]
This issue was addressed via #62750 and so can, I assume, be closed.

**Comment by EternalKitten** [comment]
Thanks, that's a good fix!
