### ISSUE TITLE
Option to train computer (beginner) does not appear

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#61219]
### Describe the bug

Option to train computer (beginner) does not appear.
Even if a cell phone or a laptop with sufficient charges is in the inventory, no option appears in the creation menu

### Steps to reproduce

1. Create new player
2. Spwan laptop or smartphone with enough charges
3. Search for the option in the crafting menu / practice to train computer (beginner)
4. To test, give yourself all the recipes via debug menu and tada, there is the option to train computer (beginner)

### Expected behavior

The option to train computer (beginner) should always be available once the appropriate device is available in the inventory

### Versions and configuration

Win10 tiles
Experimental 65b77c9
2022-09-24-0526

Mod:
Stats trough skills

**Comment by Terrorforge** [comment]
You need either one theoretical level or certain books to unlock the practice recipe. This is consistent with most other skills.

If that sounds weird to you, remember that Computer skill doesn't represent the ability to use a computer normally. It represents advanced technical knowledge like coding and hacking, which would be very tricky to reinvent on your own from first principles.

**Comment by BjoHart** [comment]
> You need either one theoretical level or certain books to unlock the practice recipe. This is consistent with most other skills.
> 
> If that sounds weird to you, remember that Computer skill doesn't represent the ability to use a computer normally. It represents advanced technical knowledge like coding and hacking, which would be very tricky to reinvent on your own from first principles.

Ahh, thanks! I didn't know that!
