### ISSUE TITLE
Battery System CBM's internal battery compartment is present in Sort Armor menu and has bugged display

### ISSUE THREAD

**Issue by PenceGL** [CleverRaven/Cataclysm-DDA#61213]
### Describe the bug

After #61049, the internal battery compartment on the Battery System CBM shows up in the Sort Armor menu, and has some interesting protection statistics.

### Steps to reproduce

1. Obtain Battery System CBM.
2. Examine internal battery compartment in Sort Armor menu

### Expected behavior

My intuitive feeling is that the internal battery compartment should not be present in the Sort Armor menu at all.

I assume this was just an overlooked bug that came with the fuel system rewrite, and it was not intended to show up in this menu.

### Screenshots

![cataclysm-tiles_EefhtxMCk2](https://user-images.githubusercontent.com/8877847/192013590-dc2e34ff-ba86-4b30-a7dc-99198ec8d0f6.png)

### Versions and configuration

Windows 10
Build: 2022-09-22-0130
Version: 8c5a5eb (tiles)

**Comment by Hirmuolio** [comment]
Built on VS  shows -0.0 for ballistic and 0.0 for rest.
cdda-windows-tiles-x64-2022-09-27-0751 shows massive number for cut and 0.0 for rest.

Seems to be fun compiler specific problem.

Seems like the armor system is not happy when the worn item is `"TOOL"`. Changing it to `"TOOL_ARMOR"` seems to fix.
