### ISSUE TITLE
We can't reach "contributing guidelines" through the hyper-link in underneath this screen( github.com )

### ISSUE THREAD

**Issue by EIIKaO** [CleverRaven/Cataclysm-DDA#61215]
### Describe the bug

There is a hyperlink at the bottom of the screen that says "Remember, contributions to this repository should follow its `contributing guidelines`", but we can't get there by pressing the link.

### Steps to reproduce

1. Open this issue( If you are reading this Issue via a web browser, you are already in this stage )
2. Before posting a refutation of this Issue, please see the note at the bottom of the screen ( to the lower left of the comment button )
3. Follow the notes and click on the "contributing guidelines" hyperlink to check the contributing guidelines.
4. I see a screen that shown the text "../doc/CONTRIBUTING.md", but can't read "contributing guidelines" yet.

### Expected behavior

Enable contributors to read the " contributing guidelines" with one click ( or with equal ease ) before submitting.

### Versions and configuration

Windows 10
Firefox 105.1( 64-bit )

### Additional context

I try to copy from that text( `../doc/CONTRIBUTING.md` ) and paste it into the address bar, but sometimes it fails then takes me to the 404 page and see the jedi guy.

**Comment by GuardianDll** [comment]
I think github accept only links into `.github` folder, when our contribute guidelines exist in `/doc` folder, with all another documentation

**Comment by EIIKaO** [comment]
> I think github accept only links into .github folder when our contribute guidelines exist in /doc folder, with all another documentation

According to the information below,
> If a repository contains more than one CONTRIBUTING file, then the file shown in links is chosen from locations in the following order: the .github directory, then the repository's root directory, and finally the docs directory.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

we can put the CONTRIBUTING file in three places( not sure, I can't test on my repo ). And it seems that the top priority is given to inside of .github(?).

I understand somewhat, that due to distributing issues, the file was changed to a symlink(?).
Anyways, I am a total newbie to website building and github, so I don't know if my claims are correct or not.
