### ISSUE TITLE
UPS CBM no longer provides power unless another UPS is within range

### ISSUE THREAD

**Issue by lordofhate** [CleverRaven/Cataclysm-DDA#61211]
### Describe the bug

Since update #61049, the UPS Bionic does not provide power to items with a UPS conversion mod, unless a charged UPS is also nearby. If a UPS is nearby, the bionic functions as intended draining power from the bionic storage first, but a nearby charged UPS should not be required for the CBM to work.

### Steps to reproduce

Install build 2022-09-21-1254 or higher.
Have a character with a Unified Power System CBM and charged bionic power.
Have the CBM turned on.
Mod an item (soldering iron/arc welder/anything other than phone) with UPS conversion mod.
Ensure no UPS/power source is available other than bionic energy.
Be unable to craft/repair with a message saying the device does not have enough power.

### Expected behavior

As long as bionic power is available and the CBM is turned on, objects that can draw power from UPS should work without another UPS being nearby.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 4ee9085 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by jim-huynh** [comment]
@lordofhate Do you have any power sources with fuel saving on?  If you do, could you turn them off temporarily to see if that resolves the issue?  I found an issue where if I had fuel saving on, certain bionics would not work properly.  I did a commit to fix that issue but it sounds like yours might be from a similar cause.  #61242

**Comment by Hirmuolio** [comment]
Can't reproduce problem. UPS modded soldering iron powered by unified power system bionic works for crafting. So I assume 61242 fixed this.

**Comment by Cupidatis** [comment]
Yeah, it's fixef now
