### ISSUE TITLE
Liquids duplicate when moved using AIM into a container with multiple pockets

### ISSUE THREAD

**Issue by FIM43-Redeye** [CleverRaven/Cataclysm-DDA#61239]
### Describe the bug

When using advanced inventory management to move liquids from a target container into a receiving container, if the receiving container has multiple pockets AN, the liquid is duplicated by the number of pockets the receiving container has.

### Steps to reproduce

1. Make a player with a multi-pocket container and a single-pocket container already containing something (a water bottle will do).
2. Drop the single-pocket container on the ground.
3. Wear the multi-pocket container.
4. Use advanced inventory management to open the multi-pocket container and transfer the liquid from the single-pocket container directly into it.
5. More liquid is transferred than should exist.

### Expected behavior

The content of the target container is removed and transferred to the first pocket that can take it, but no more.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.978 (21H2)
- Game Version: fd463d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Here's an item you can use to test the problem adapted from a cheat item I use.
  {
    "id": "magic_backpack",
    "type": "ARMOR",
    "name": { "str": "pocket universe" },
    "description": "For kicks.",
    "weight": "1 g",
    "volume": "1 L",
    "price": 0,
    "price_postapoc": 0,
    "material": [ "carbide" ],
    "symbol": "[",
    "color": "blue",
    "insulation": 100,
    "pocket_data": [
      {
        "watertight": true,
        "airtight": true,
        "rigid": true,
        "fire_protection": true,
        "pocket_type": "CONTAINER",
        "max_contains_volume": "100000 L",
        "max_contains_weight": "100000 kg",
        "moves": 1,
        "max_item_length": "1 km",
        "spoil_multiplier": 0.0,
        "weight_multiplier": 0.0
      },
      {
        "watertight": true,
        "airtight": true,
        "rigid": true,
        "fire_protection": true,
        "pocket_type": "CONTAINER",
        "max_contains_volume": "100000 L",
        "max_contains_weight": "100000 kg",
        "moves": 1,
        "max_item_length": "1 km",
        "spoil_multiplier": 0.0,
        "weight_multiplier": 0.0
      }    ],
    "warmth": 0,
    "material_thickness": 2,
    "flags": [ "BELTED", "WATER_FRIENDLY", "TARDIS", "SEMITANGIBLE", "STURDY", "SUPER_FANCY", "WATERPROOF" ],
    "armor": [ { "encumbrance": [ 0, 0 ], "covers": [ "torso" ], "specifically_covers": [ "torso_hanging_back" ] } ]
  },

**Comment by EIIKaO** [comment]
I have been trying to reproduce the bug casually for several days and have not succeeded ( cause I was too lazy to install the item provided by the issue owner for verify, so I used the in-game "double 84mm container" < with 2 waterproof pockets > instead ).
Now, I got serious, installed the Issue owners backpack mod and tested it out, was finally able to reproduce the bug.
One thing needs to be added to the reproduction steps, I think.
> 2.1  Wear multi-pocket container( because if that container is in your inventory, you must select "Select items currently worn" before you can select "Select items in container" ).

This may be a case in which it is more difficult to reproduce a bug than to fix it.
I guess that since there is no wearable item in vanilla that has multiple waterproof pockets, nobody but a bored person like me would have had time to verify it.

I know that was too many superfluous words, but that code should solve the problem.
```diff
diff --git a/src/advanced_inv.cpp b/src/advanced_inv.cpp
index dd4bd39f2e..7774b64629 100644
--- a/src/advanced_inv.cpp
+++ b/src/advanced_inv.cpp
@@ -1878,7 +1878,7 @@ bool advanced_inventory::move_content( item &src_container, item &dest_container
 
     std::string err;
     // TODO: Allow buckets here, but require them to be on the ground or wielded
-    const int amount = dest_container.get_remaining_capacity_for_liquid( src_contents, false, &err );
+    const int amount = std::min( src_contents.charges, dest_container.get_remaining_capacity_for_liquid( src_contents, false, &err ) );
     if( !err.empty() ) {
         popup( err );
         return false;

```
