### ISSUE TITLE
Error when try to launch

### ISSUE THREAD

**Issue by Beebuzzman** [CleverRaven/Cataclysm-DDA#61245]
### Describe the bug

Error while initializing the interface: Cannot load font data/font/Terminus.ttf

### Steps to reproduce

just launch cataclysm-tiles in terminal

### Expected behavior

I expected to run the game

### Versions and configuration

OS: Debian sid
Game version: 0.F-3-5
Graphic: tiles

**Comment by BrettDong** [comment]
Sounds like a packaging issue.

**Comment by Beebuzzman** [comment]
Well, I just copied github cataclysm unifont.ttf to direcory /usr/share/games/cataclysm-dda/font/ and it works.
