### ISSUE TITLE
[Magiclysm] Black Dragon Scales and Dragon Meat don't count as valid ingredients

### ISSUE THREAD

**Issue by EternalKitten** [CleverRaven/Cataclysm-DDA#61244]
### Describe the bug

Dragon essense calls for 6 _black dragon scales_ but even though I have 8 lying around the recipe doesn't seem to acknowledge that. 

This is an issue for both _Dragon Essence_ recipes.

You can also see that I have 36 _dragon meat_ but the recipe also doesn't count that.

### Steps to reproduce

1. Hunt a Black Dragon Wyrmling
2. Butcher its corpse
3. Go to Crafting and check both Dragon Essence recipes

### Expected behavior

I expect to see _Dragon Meat_ and _Black Dragon Scales_ applicable for recipes that call for these components.

### Screenshots

![image](https://user-images.githubusercontent.com/82908191/192125475-2afa1869-bb38-4a2f-9069-c800104a34ea.png)
![image](https://user-images.githubusercontent.com/82908191/192125488-257d6850-8e1f-4b8d-98d8-234f6c9f3a1e.png)

### Versions and configuration

 cdda-windows-tiles-x64-msvc-2022-09-24-0526

### Additional context

[Farnam.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9639886/Farnam.zip)

**Comment by Sutremaine** [comment]
The meat and scales don't appear as an option the moment butchery is finished, but passing a turn is enough to get the game to recognise the ingredients.

**Comment by EternalKitten** [comment]
I stand corrected. Thanks for checking this for me. 
![image](https://user-images.githubusercontent.com/82908191/193727316-5e8d03ef-bf61-495d-bab1-98fec3e018f2.png)
