### ISSUE TITLE
Character perk (buff) for talking with yourself

### ISSUE THREAD

**Issue by PackmanDude** [CleverRaven/Cataclysm-DDA#61248]
### Is your feature request related to a problem? Please describe.

It's an idea I got at midnight. It isn't related to any problem, I think.

### Solution you would like.

The idea behind this perk is that we know why people talk to themselves, right? That strange human behavior boosts their cognition and increases focus. So, I made the decision to request that here.

In-game mechanics with this perk:
- It will constantly increase your focus from time-to-time, when you're doing stuff.
- I don't remember if there is a perk for a character, like 'Night Owl', but if there is, then when you have it, talking to yourself will be more often after 12 PM.
- You can't control that, and you can be heard more easily by monsters nearby.

### Additional context

About the third option that I described above, I'm not sure whether to call it a buff or a debuff, because it's really cool, but getting caught isn't a wonderful thing to happen. I think, developers (and contributors ❤️) will find a way to implement that for everyone to be happy with this feature.

**Comment by fungamer2-2** [comment]
Sounds like a good idea, if this is implemented, there should be a setting to turn this off (for example, if the player is trying to stay quiet so as not to be heard by monsters)

**Comment by fungamer2-2** [comment]
In my opinion, I think this sounds like it would be a good trait to have

**Comment by PackmanDude** [comment]
Recently I found that I'm autustic (Asperger's syndrome). Maybe this trait came to mind to suggest, cause I'm dealing with it daily.

IMO, DDA should be replaced with single word ‘bloat’. This kind of trait is not useful for gameplay, nor useless. It's neither. By having to choose traits wisely this may be not a problem. We could add a lot of these “not-useful-nor-useless” traits, to mąkę it near-infinitely list to scroll, but after some time this will still happen.

So, if you close this ~~suggestion~~ issue nobody will be offended (_I think so_). Hope you guys celebrated holidays nice and sorry for adding you an extra work. Stay safe.
