### ISSUE TITLE
Triffid queen breaking ground and falling at -1 level.

### ISSUE THREAD

**Issue by kolya1239** [CleverRaven/Cataclysm-DDA#61251]
### Describe the bug

Maybe other mobs also can do this. 

### Steps to reproduce

1. Spawn triffid queen on earth.

### Expected behavior

She definitely should stay at 0 lvl.

### Screenshots

![image](https://user-images.githubusercontent.com/55348842/192148781-4a4ce528-5609-4483-ba2e-3e9b65b8886f.png)

### Versions and configuration

Last clear BN, Windows.

**Comment by sonphantrung** [comment]
For the reason why this issue got closed: Author reported the bug from Bright Nights, not Dark Days Ahead.
