### ISSUE TITLE
NPC "Do Not Enter" zones

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#61254]
### Is your feature request related to a problem? Please describe.

Not really a problem so much as an annoyance. NPC followers have a tendency to sleep in the bed that my survivor has been using, and every time they do this, they clear away the webs my survivor put there to sleep in. Also, NPCs keep trying to go through barred windows in order to get to where they've decided to go, and then get stuck because, unlike a normal window, a barred window can't be passed trough. Granted, that could probably warrant its own issue, but still...

### Solution you would like.

I'd like to be able to place a zone that prevents followers from entering tiles within that zone. There could even be additional variations that only apply under specific circumstances, such as when there are (or aren't) any visible hostile creatures.

### Describe alternatives you have considered.

1. Debugging walls in and out of existence in order to protect my survivor's bed when not in use

2. Removing bars from every window

**Comment by robotic-gamer** [comment]
have you tried using furniture to block npcs?

**Comment by AmarinReyny** [comment]
> have you tried using furniture to block npcs?

I could, though it'd be tedious, and even then, I think a "do not enter" zone would be useful enough - and for more than just the reasons I've already mentioned - to be a good thing to include in the game.
