### ISSUE TITLE
Settings interface for default character name produces debug message for trim_by_length

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#61266]
### Describe the bug

Attempting to open the "Default character name" setting's string input popup produces this debug message error:

`ERROR : src/output.cpp:275 [std::string trim_by_length(const std::string &, int)] Unable to trim string '' to width 0.  Returning empty string`

### Steps to reproduce

1. Launch the game (in tiles mode?)
2. Navigate to Settings
3. Press enter on the first setting, Default character name.

### Expected behavior

string input popup appears to enter a new name instead of the blank default

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: 0.C-73702-ge615a9db84 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

titlesize should not be zero at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/string_input_popup.cpp#L255, it should probably be 20-30 (the width of the popup minus two) for my and most screen sizes.

Per ZeroInternalReflection#9023 on Discord this issue is also affecting the Android build.

Trimmed backtrace:

    ./cataclysm-tiles(trim_by_length(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0xc51) [0x5643c1849cd1]
    ./cataclysm-tiles(trim_and_print(catacurses::window const&, point const&, int, nc_color const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, report_color_error)+0x36) [0x5643c1849006]
    ./cataclysm-tiles(string_input_popup::draw(ui_adaptor*, utf8_wrapper const&, utf8_wrapper const&) const+0x1a3) [0x5643c1bb5b83]
    ./cataclysm-tiles(+0x2398254) [0x5643c1bb8254]
    ./cataclysm-tiles(ui_adaptor::redraw_invalidated()+0x41d) [0x5643c1c968ed]
    ./cataclysm-tiles(ui_manager::redraw()+0x1e) [0x5643c1c96c6e]
    ./cataclysm-tiles(string_input_popup::query_string[abi:cxx11](bool, bool)+0x5c7) [0x5643c1bb6a17]
    ./cataclysm-tiles(string_input_popup::edit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0x83) [0x5643c1bb7943]
    ./cataclysm-tiles(options_manager::cOpt::setNext()+0x27a) [0x5643c17d730a]
    ./cataclysm-tiles(options_manager::show[abi:cxx11](bool, bool, bool)+0x1f86) [0x5643c182b8b6]
    ./cataclysm-tiles(main_menu::opening_screen()+0x13f1) [0x5643c1265c11]
    ./cataclysm-tiles(main+0x1b26) [0x5643c125c086]

**Comment by turco-ai** [comment]
Can confirm as android user, it gives the error under the android tab in the options menu when tapping on default gameplay shortcuts option.

**Comment by ZeroInternalReflection** [comment]
Now that I've done some testing it looks like this is a lot simpler than I thought it was going to be.
The debugmsg pops up on string_input_popup trying to trim and print the popup title (until this is fixed, `i`gnoring it should work without a crash at this location).
However, the options menu, when asking for input to set a string variable, never sets the title.  It only sets the description.  This appears to fix the issue:

```
diff --git a/src/options.cpp b/src/options.cpp
index 140859a329..22eba501ce 100644
--- a/src/options.cpp
+++ b/src/options.cpp
@@ -893,7 +893,7 @@ void options_manager::cOpt::setNext()
         int iMenuTextLength = utf8_width( sMenuText.translated() );
         string_input_popup()
         .width( iMaxLength > 80 ? 80 : iMaxLength < iMenuTextLength ? iMenuTextLength : iMaxLength + 1 )
-        .description( sMenuText.translated() )
+        .title( sMenuText.translated() )
         .max_length( iMaxLength )
         .edit( sSet );
```

I'm not set up to test the Android version, but I'm betting it's the same issue.  I should be able to write up a PR tomorrow to:
a) Make this change, and
b) Have string_input_popup default to "Default title" or something, which would allow people to see that something has been missed without a debugmsg.
