### ISSUE TITLE
Error when picking up crystallized mana

### ISSUE THREAD

**Issue by Xynon7** [CleverRaven/Cataclysm-DDA#61275]
### Describe the bug

When picking up crystallized mana, I get a popup error about them having 0 weight. Screenshot in context.

### Steps to reproduce

1. Create world with this modlist.
![image](https://user-images.githubusercontent.com/8867601/192200457-4a6fea8c-5746-405f-8a1d-21283a8d8b22.png)
2. Chose the Wizard Vacation scenario, cant remember exact name.
3. In starting room picked up something saying 100 crystallized mana off the floor using advanced pickup mode and this popped up.

### Expected behavior

I expect I can pickup this mana.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 90fc2e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

![image](https://user-images.githubusercontent.com/8867601/192200380-8d3a29f0-2ba3-4755-8083-a3d08b24ed1f.png)

**Comment by snipercup** [comment]
I have this too when moving it into my inventory with the advanced inventory manager.
