### ISSUE TITLE
Steel ballistic plate repair incorrectly flagged to use tempered carbon steel for tailoring tools

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#61277]
### Describe the bug

Despite claiming to repairable with a sewing/tailor's kit (likely due to being part synthetic fabric), the game attempts to use tempered carbon steel to repair it, so it fails to do so entirely.

### Steps to reproduce

1. Use a needle/sewing/tailor's kit on a steel ballistic plate.

### Expected behavior

The game should attempt to use synthetic fabric patches to repair the plate, or otherwise not be repairable with tailoring tools entirely.

### Screenshots

![image](https://user-images.githubusercontent.com/24522330/192246080-0ac4220f-ec75-4136-acce-d2eebf3bc25b.png)
![image](https://user-images.githubusercontent.com/24522330/192246139-e7908921-6dcb-4cb9-ab45-5d4ab233657a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 90fc2e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by utechenko-v** [comment]
Issue may be related to #61132

**Comment by RenechCDDA** [comment]
Technically intentional, per #60428.
