### ISSUE TITLE
looks_like field requirement

### ISSUE THREAD

**Issue by secretstamos** [CleverRaven/Cataclysm-DDA#61285]
### Is your feature request related to a problem? Please describe.

I believe there should be a mandate for looks_like for all new content (items/monster/terrain/furniture) in the main repo.

It takes significantly less development time for the developer adding the item/monster/ect to fill out this field than it does for every tileset to both identify the missing icon and add it.

At least in my own experience this is the largest loss of efficiency.

### Solution you would like.

Require the looks_like field for all new additions

### Describe alternatives you have considered.

Fris mentioned adding a CI check for it instead/in addition, which is an idea I like

### Additional context

I started the Hollow Moon tileset
This also affects new tilesets, not just the existing ones

**Comment by Fris0uman** [comment]
Having a workflow that warns, but don't fail tests, if a new entity is added without looks_like would be nice. Something a bit like the dictionnary spelling check thing, that will remind you to set it up but that you can ignore in the cases where it doesn't make sense

**Comment by secretstamos** [comment]
> Having a workflow that warns, but don't fail tests, if a new entity is added without looks_like would be nice. Something a bit like the dictionnary spelling check thing, that will remind you to set it up but that you can ignore in the cases where it doesn't make sense

Yeah I agree, so long as it isn't something that gets ignored in practice
