### ISSUE TITLE
hub 1 mercenary's dialogue gets mixed with smokes dialogue from the free merchants

### ISSUE THREAD

**Issue by yamil-90** [CleverRaven/Cataclysm-DDA#61283]
### Describe the bug

i think the dialogue options got mixed up, maybe the npc template the used had some leftover code from smokes

### Steps to reproduce

1 - go the the building north from the hub one terminal and talk to norine tracy
2 - ask to join the group (not team)
3 - choose "another time, then"
4 - you are now inside the dialogue options of smokes 

### Expected behavior

the option to join the group should not be there as i think is leftover code

### Screenshots

![image](https://user-images.githubusercontent.com/57334377/192315456-0bb70f87-ff9c-4b65-be11-bbab1f1779f5.png)

### Versions and configuration

- OS ubuntu 20.04
- version a9b1db4 (one of the latest experimental)

**Comment by onura46** [comment]
This has been fixed by #61343, so it should be closed.
