### ISSUE TITLE
Permanently broke my Robofac interaction by interacting with a second robofac

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61289]
### Describe the bug

When finding a second Hub01 after having interacted with the first, they will require you to do the prototype robot quest again in order to talk to you. If you accept this quest, then it will permanently break all future interaction with Hubs01, as the quest will never complete and they will request another copy of the prototype I/O recorder every time you speak with them, and as a result you will only ever be able to speak with them once after doing this.
I also found that, at least in this specific state of broken, you can pass the 10 int "the armor seems warped [...]" check an unlimited number of times and receive an unlimited number of prototype vambraces and greaves. 

### Steps to reproduce

1. Complete the Hub01 prototype robot quest.
2. go find a second hub01.
3. find they want you to do the prototype robot quest again in order to interact with that specific hub01.
4. Accept the quest, bring back the I/O recorder, find out that ALL hub01s will demand another I/O recorder and the quest will never complete, permanently breaking all interactions with Hub01s.

### Expected behavior

Tbh hub01 should be a global exclusive, as unlike the refugee center there's no issue with migos/fungus/triffids spawning right next to them and ruining the location.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 90fc2e4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by BestivusStanleyUpas** [comment]
I'm having the same issue in my game as well.

**Comment by NetSysFire** [comment]
Wasnt Hub01 set to globally unique? If so, I'd close this issue for good but I am not sure

**Comment by anothersimulacrum** [comment]
None of the NPC facnion bases are globally unique.

**Comment by RAldrich** [comment]
I've played around with setting various NPC faction bases to globally unique, and while it sort of works it causes a variety of issues with the current implementation. The largest one is that the breadcrumb missions (for example, Smoke's quest to take the data chip from the refugee center to Hub01) will throw an error if they can't find the relevant overmap location within a certain radius, which permanently breaks the breadcrumb quest.

**Comment by AcidAntOnAMinefield** [comment]
This is still happening as of the latest build.
