### ISSUE TITLE
Scrapper refers to a nonexistent spare bed

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#61295]
### Describe the bug

Dialogue with the scapper/scrap_trader suggests there should be a bed (or two) in the shop or elsewhere in the scrap yard, but there isn't.

### Steps to reproduce

1. Ask the scrapper "Think I could stay here?"
2. Get "Sure, I'm fine with it.  There's a spare bed over there for anyone who needs it.  Just don't hog it.  Someone else might come along."
3. Fail to find bed

### Expected behavior

Bed exists nearby

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: 0.C-73717-gcaf20a88a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ssirenkth** [comment]
Can confirm this in: https://github.com/CleverRaven/Cataclysm-DDA/commit/fd463d46976756135990435f9b00ff295afcdd32 [64-bit]

**Comment by sparr** [comment]
Sorry, the version tag in the original issue was incorrect due to out-of-sync git tags. This was in a recent master, synced within the previous week.

**Comment by MNG-cataclysm** [comment]
#59805 will fix this issue.

**Comment by Fris0uman** [comment]
fixed by #59805
