### ISSUE TITLE
Unload item dialog allows picking up items without triggering stealing check

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#61296]
### Describe the bug

When Unloading a container from the floor you will pick up the unloaded contents, even if picking it up directly would have been theft.

### Steps to reproduce

1. Stand next to a container owned by an NPC, including NPC corpse clothes pockets
2. [U] then choose the container on the ground
3. See unloaded items in your inventory with no stealing notice

### Expected behavior

Same "that would be stealing, continue?" prompt as when trying to pick the container up.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: 0.C-73717-gcaf20a88a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

See #61294 for an equivalent problem with a different dialog.

**Comment by Night-Pryanik** [comment]
I suppose 0.C-73717 version isn't really 0.C? I wonder what's the actual version it is.

**Comment by sparr** [comment]
@Night-Pryanik master as of a few days ago. I asked on Discord if anyone could help figure out why it's building with that old version number but didn't get very far.

**Comment by TealcOneill** [comment]
Was not able to reproduce, testing in the Refugee center storage room causes the guard to aggro and opens the normal chat options for theft.
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]
