### ISSUE TITLE
Artifacts powers erased

### ISSUE THREAD

**Issue by Blorkman** [CleverRaven/Cataclysm-DDA#61308]
### Describe the bug

Since today updating, then saving your game with artifacts will delete their effects.

### Steps to reproduce

1.Update
2.Load a save with artifacts
3.Save
4.Reload
5.Your artifacts are now useless shiny rocks !

### Expected behavior

Artifacts effects being saved obviously.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 5542e8a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Ramza13** [comment]
Crap this is probably caused by #61258.  Do you happen to have a save with artifacts that can reproduce this issue?

**Comment by anoobindisguise** [comment]
I've found the same thing. All my magical napkins, gone.

**Comment by KymasTuran** [comment]
> Crap this is probably caused by #61258. Do you happen to have a save with artifacts that can reproduce this issue? Or actually can you tell me how you get artifacts in game? I've never encountered them and am not sure how to get them which makes debugging hard.

The "easy" way is in "Amigara Mines".

**Comment by Blorkman** [comment]
> Crap this is probably caused by #61258. Do you happen to have a save with artifacts that can reproduce this issue? Or actually can you tell me how you get artifacts in game? I've never encountered them and am not sure how to get them which makes debugging hard.

I do have a save with two artifacts on my character, i found them in a distorted lab. I'd be happy to share it with you if you need it, but mind its 500mb large

**Comment by KymasTuran** [comment]
I can confirm:
- Artifacts made in a new game work as intended, I spawn one using the debug menu.
- Importing saves to a new version and artifacts lost all is data, discover it after browsing and compare save games.
In less words:  the problem is importing old enchant system. New games are ok. 
I guess a warning somewhere is mandatory.
Sorry for my poor english.

**Comment by anoobindisguise** [comment]
If I create a new save file and debug spawn an artifact (max abilities 10 power 10000 max negative power -1000) I can clearly see it has a number of abilities but as soon as I save and quit it loses all of them except for its actives.

**Comment by KymasTuran** [comment]
> If I create a new save file and debug spawn an artifact (max abilities 10 power 10000 max negative power -1000) I can clearly see it has a number of abilities but as soon as I save and quit it loses all of them except for its actives.

What game version? 
I did my test in cdda-windows-tiles-x64-msvc-2022-09-27-0751 and work fine. Only in new games.

**Comment by Blorkman** [comment]
> > > Crap this is probably caused by #61258. Do you happen to have a save with artifacts that can reproduce this issue? Or actually can you tell me how you get artifacts in game? I've never encountered them and am not sure how to get them which makes debugging hard.
> > 
> > 
> > I do have a save with two artifacts on my character, i found them in a distorted lab. I'd be happy to share it with you if you need it, but mind its 500mb large
> 
> Given a followup comment says this doesn't work with newly spawned items copy of your save would be very very useful. I've downloaded large saves before thats not a problem, people often zip them a lot smaller but I'll take it any way you can give it to me. Thanks

Yeah you were right i forgot about the compression, it's smaller, here you go :
https://mega.nz/file/n4hFjKTC#cwxuckuen2MrqfMxZ7keeE9t02oevNRFSEJumL4LPaA
