### ISSUE TITLE
Alter "Vocaloid Body Pillow" description to depict an adult rather than a teenager

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#61303]
### Is your feature request related to a problem? Please describe.

This may considered a rather strange thing to change, but i think the description of the Vocaloid Body Pillow  should be altered since it references the Vocaloid character Hatsune Miku, who is a sixteen year old.

"A big, body-sized pillow with a print of a popular blue-twintailed virtual musician on the front and her scantily-clad version on the back."

### Solution you would like.

Instead of depicting Miku, perhaps a known adult vocaloid character could be depicted/referenced instead, like Kaito or Luka, who are established adult characters. 

The description to this item could be changed to 

"A big, body-sized pillow with a print of a popular  virtual musician with dark blue hair and scarf on the front and his scantily-clad version on the back"

or

"A big, body-sized pillow with a print of a popular virtual musician with long pink hair wearing headphones on the front and her scantily-clad version on the back."

### Additional context

This may be a very strange thing to request to be changed, but I think its even stranger to include the depiction a 16 year old girl on a bodypillow, especially with a provided suggestive subtext.

**Comment by kevingranade** [comment]
Yes it is a strange thing to change, and we're not going to.
