### ISSUE TITLE
Different overmap visibility for tall buildings

### ISSUE THREAD

**Issue by ProfaneServitor** [CleverRaven/Cataclysm-DDA#61306]
### Is your feature request related to a problem? Please describe.

There are tall structures in the game: apartment towers, rocky butte, wind turbines. It would make sense if character could put it on overmap from beyond player's vision field, even if it is obscured by smaller structures like a house. Right now you often don't see them until you are 50 meters from them.

### Solution you would like.

Currently there is a parameter that does something similar, `see_cost`. It is documented here:

https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide-Locations

However it only affects how good is that terrain feature in obstructing vision. It was also implemented before z-levels.

It might help to have similar parameter, like `landmark_visibility`, which would determine from which distance this tile is visible. For backward compatibility it might fall back to `see_cost`.

### Describe alternatives you have considered.

Determine visibility by maximum z-level over that tile. However, it might create issues with some multi-tile features (for, example, plains around refugee center have 3 z-levels of empty air around them) and it might cause weird behavior underground.

**Comment by robotic-gamer** [comment]
perhaps a simpler solution would be to allow player vision to apply in the reverse direction of seeing from an elevated position. (ie if you are on top of the tall building every overmap tile that you have vision of would provide vision of the building you are on if you where at that overmap tile. from there it can be made that seeing something other than "open air" (or any other manually designated tile type) implicitly reveal's the overmap tiles on the ground floor. this solution would solve edge cases like a building blocking sight of another building.
