### ISSUE TITLE
Wedding dress grants 1866 cotton patches when cut up

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#61301]
### Describe the bug

As title. I suspect this is because it's 18L and 9.33 kg of pure cotton.

### Steps to reproduce

1. Cut up a wedding dress.

### Expected behavior

A more normal amount of cotton patches like other clothing.

### Screenshots

![image](https://user-images.githubusercontent.com/24522330/192515023-a6f5239f-3490-4716-8e8f-a1f65520dd92.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: b87b910 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Sutremaine** [comment]
https://www.wedistry.com/how-heavy-is-the-average-wedding-dress/

From the link: 3 to 5 kilos / 7 to 11 pounds is the average weight, but heavier ones can be between 5 and 10 kilos.

I'd expect a heavier wedding dress to have beads or something, and not just MOAR FLOOF, so I guess a wedding dress that doesn't return anything but cotton would be lighter than 9.33 kilos. But I don't know anything about wedding dresses.
