### ISSUE TITLE
Bread is unreasonably dense; pumpkin muffins are denser than gold, can eat over 50kg in one sitting

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#61312]
### Describe the bug

Many bread items have completely wacky density. 100 units of standard "bread" weigh 6kg (6000g) and has a volume of 1.79L (1790cm3), which gives it a density of 3.4g/cc. This is denser than [most rocks](https://www.thoughtco.com/densities-of-common-rocks-and-minerals-1439119), and about 15 times higher than the [actual density of bread](https://modernistcuisine.com/mc/bread-is-lighter-than-whipped-cream/) at ~0.2g/cc. Some, but not all, bread-related products have similarly weird densities. A few examples:

- Cookie: 2.64g/cc
- Boring sandwich: 3.4g/cc
- Wastebread: 4.8g/cc ([denser than Titanium](https://www.angstromsciences.com/density-elements-chart))
- Hardtack: 6.4g/cc
- Hallula: 15g/cc (denser than lead)
- Pumpkin muffin: 20g/cc (denser than gold, within spitting distance of Osmium, the densest substance known to man)

While all of these values are silly and could use adjusting on that basis alone, what actually causes problems is the effect density has on eating. Because of the way satiety is calculated (#36977, #40402), calorie density is largely a function of physical density.

The survivor is able to eat about 1800 pumpkin muffins in one sitting. That's over 50kg, and more than _seventy thousand_ kcal.

That's obviously an extreme outlier, but it has absurd effects much further down the scale. Filling up on hardtack gives you about 4 times more calories than eating a similar amount of _pure lard_.

### Steps to reproduce

1. Spawn 1000 pumpkin muffins
2. Eat all of them

### Expected behavior

Bread is less fattening than literally eating pure fat.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/192599828-019d75c3-a985-4ddc-8f90-c02bccad8e3f.png)
A stomach full of pumpkin muffins

![image](https://user-images.githubusercontent.com/5107449/192604230-fadddb07-18f4-4191-9287-fab3d812a627.png)
A stomach full of hardtack.

![image](https://user-images.githubusercontent.com/5107449/192604650-fc18e492-a70e-421f-9a93-ff431a4e47af.png)
A stomach full of bread

![image](https://user-images.githubusercontent.com/5107449/192604009-f46d3cb0-1324-485c-a490-ad18e33c1c7a.png)
A stomach full of lard.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 3d6730a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RAldrich** [comment]
So I was checking to see if I could fix this just by editing the JSON, and while that can help a bit there's still some oddities in math that make this turn out silly. A few things are happening:

1. As noted, JSON values for these items are nonsense. A better value for something like an apple pumpkin muffin (based on a Starbuck's blueberry muffin) is `V = 200 ml, W  = 99 g, kcal = 330`. That gets you to `0.3 g/kcal`.

The game does several things to the Volume.

1. You chew the food. This removes the water from it (not relevant here as muffins have negative quench), and more importantly, **compresses it until it is as dense as water.** Nothing in your stomach is ever treated as less dense than water. This means that our 200 mL muffin is turned into a 99 g == 99 mL paste (gross).
2. The volume is adjusted if the calorie density is high (this uses the unchewed volume). This isn't strictly linear, but for the muffin the multiplier comes out at 3.16 (it's dense, so it's three times as filling as you'd expect).
3. 99 mL * 3.16 = 313 mL that actually gets ingested

Despite this fairly reasonable volume, I can still eat 53 muffins * 313 mL = 16.5 Liters of muffins. Something must be wrong with the stomach code. **Turning on debug mode, I can see that the effective volume that's getting logged is only 28 mL.** So there must be a bug.

------

Ok so next I checked the JSON vs in-game definitions. Even if I set the JSON to `"volume": "20000 ml"` (a 20 Liter muffin), in-game it only comes up as 0.83 L. So the conversion there is not working as expected at all.

**Comment by RAldrich** [comment]
It's a unit conversion somewhere. Consuming my 20,000 mL muffin with debug mode on shows an effective volume of 313 mL, which is exactly what we'd expect to see from the 200 mL muffin calculation I mentioned above. So something is chopping off two orders of magnitude, and the displayed volume for the item (in inventory) is also nonsense.

**Comment by RAldrich** [comment]
Derp. It's the `stack_size=24`. The original pumpkin muffin data specified some sort of magically dense mini-muffin with 24 portions. Eliminating the `stack_size` causes all the math to work out as expected. 

With those changes, I can only eat 4 muffins before I'm full. So. Sorry for the long-winded investigation that can be summarized as: "yes, we can fix this by updating the JSON values".

**Comment by Karol1223** [comment]
I do appreciate the fact that two years on from this issue being posted we've seen some moves on that front.

Pumpkin muffins are no longer 20g/ml... they're now 30g/ml...

**Comment by Terrorforge** [comment]
I love game development.
