### ISSUE TITLE
Searching proficiency in recipes missing some results

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#61318]
### Describe the bug

Search in recipes for "P:blacksmithing" will not find results such as lump of high steel despite it needing the proficiency and my skill in fabrication over 5. 

### Steps to reproduce

1. Make new game in 1a6085e
2. Enable all recipes
3. Open & menu.
4. Press / and search for P:blacksmithing,lump
5. The results will be empty

### Expected behavior

Since the proficiency is required and trained by crafting high steel lumps, it should show up in the search.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 1a6085e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Aventura.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9660892/Aventura.zip)

**Comment by ZeroInternalReflection** [comment]
This is likely because "lump of high steel" is part of the nested category "lumps of steel", which does not have the blacksmithing proficiency.
I don't think anyone has gotten around to updating filtering for the nested recipe system yet.

**Comment by Merikona** [comment]
If I search for 'lump' however, it will come up with the entire nested tree of lumps of steel. It seems to only not work when I try to search for proficiencies on top? e.g. I search for 'lump, P:Blacksmithing' and that will give no results.

**Comment by Merikona** [comment]
Y'know, I think this also ties back to this bug here. #[60810](https://github.com/CleverRaven/Cataclysm-DDA/issues/60810). I shouldn't have access to lumps of high steel recipe in the first place because I lack the requisite textbook. Yet I see the recipe. Searching not yielding those lumps is actually the correct behavior.

**Comment by bombasticSlacks** [comment]
![image](https://user-images.githubusercontent.com/4514073/193494257-cc8249e8-6a86-44e6-8e3f-8b8299e5fb76.png)

![image](https://user-images.githubusercontent.com/4514073/193494306-5549e25e-0243-4360-900c-ab6d3c9f0cbe.png)

Closing this one, it's just #60810 (which I've got a fix compiling for). The failure to search is the correct behavior, as seen above this works on a character that actually has the recipe.
