### ISSUE TITLE
Seg fault on loading specific area of the map (reproducable)

### ISSUE THREAD

**Issue by VarrenKrytor** [CleverRaven/Cataclysm-DDA#61316]
### Describe the bug

Open attached save file, go up any set of stairs and walk northeast till you are in the middle of the intersection.  Basically head to the LMOE shelter in the northeast.  It will crash near the middle of the intersection

### Steps to reproduce

Open attached save file, go up any set of stairs and walk northeast till you are in the middle of the intersection.  Basically head to the LMOE shelter in the northeast.  It will crash near the middle of the intersection

### Expected behavior

Game doesn't crash

### Screenshots

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9660400/debug.log)
[Loma Linda.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9660401/Loma.Linda.zip)

### Versions and configuration

OS: Windows 10
Version: 5e94c7c (tiles)
Build: 2022-09-27-0518 (19 hours ago)

### Additional context

See Screenshots

**Comment by FooterReal** [comment]
Could this be related to the TODO in the map::route function?

(`TODO: If the origin or destination is out of bound, figure out the closest in-bounds point and go to that, then to the real origin/destination.`)

**Comment by VarrenKrytor** [comment]
Still happening on version 5e89406 (tiles) build 2022-10-01-0458
I'll check in every so often to see if it's fixed.  Until then I just won't be able to play.

**Comment by VarrenKrytor** [comment]
I can confirm this fixed the issue.
