### ISSUE TITLE
Ditch Rubik's short interaction timer to prevent weird min/maxing

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#61324]
### Is your feature request related to a problem? Please describe.

You're supposed to build trust with Rubik by visiting them regularly. To accomish this, there are two timers: one that's a week long, and one that's about 30 hours. Once a timer is up, simply starting a conversation will give you one point of trust and start the timer again.

This results in a weird, game-y loop where the best way to build trust with the Exodii is to hang out in their back yard and bother Rubik exactly every 30 hours. There's no other reason to visit them that often, but even if there were, that time frame is too short. If you want to get the good CBMs within a human lifetime, you're chained to the rocky butte for months.

### Solution you would like.

Drop the shorter timer entirely. The weekly timer gives more wiggle room, and feels more natural since you probably want to return once a week to check out the new wares anyway.

The ideal would be to replace the short timer with better ways to earn trust, like more quests or turning in certain items like anesthetics. But a quick interim solution would be to simply increase the amount of trust you get off the weekly timer. 4 or 5 points seems about right. That way it's about a month and change from unlocking CBM surgery to getting the lategame bionics.

### Describe alternatives you have considered.

Giving an incentive to come back frequently. I really don't like this option, because it just amplifies the anxious feeling that you _have_ to go back as soon as possible.

**Comment by anoobindisguise** [comment]
Massive agree, building trust with the Exodii feels like doing dailies in an MMO. It sucks.

**Comment by Perset** [comment]
Completely true. I don't exactly think that Rubik's dialogue alone is good enough to bask in his company every day, nor is the Exodii base...no clue what otherwise might have motivated this mechanic. It was even better when it was easier to accidentally bump them into hostility, lol! 
Also, not very realistic from a social perspective: weirdly and pointlessly pestering someone every day isn't very endearing, I'd think.
