### ISSUE TITLE
Cutting up 1 yarn results in multiple felt patches.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#61331]
### Describe the bug

Cutting up yarn results in several felt patches which can be disassembly for more yarn, creating an infinite loop of extra materials.

### Steps to reproduce

1. Use any knife to cut up yarn which results in several felts patches

### Expected behavior

Dunno, i think yarn is supposed to turn into something else

### Screenshots

![image](https://user-images.githubusercontent.com/104400556/192869345-c3f1a79f-40d4-44dd-b123-53e6230efecd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 5542e8a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by brassmaster2357** [comment]
Can confirm, you can create multiple felt patches from just one
![image](https://user-images.githubusercontent.com/91400278/192938244-08cf153e-8079-4303-944b-4e08be40da72.png)

**Comment by RenechCDDA** [comment]
/confirmed
(Don't think this will work as I haven't added myself to the list, but we'll try...)

 I was going to suggest an item couldn't be cut up if the resulting 'scrap' item was higher volume, but that's a kludgy solution and doesn't solve all possible edge cases. Curiously, yarn can only be cut up with at least 3 yarn on the ground (which becomes 1 felt patch). Perhaps there is already a check of sorts?

Tested on a slightly older version (72591f7).

**Comment by robotic-gamer** [comment]
I noticed a related issue of wool clothing made from yarn generates far more felt patches then it would take in yarn to make the item ex.
![image](https://user-images.githubusercontent.com/78816055/193425584-8a0219af-c870-46d8-913c-df485eb826a6.png)
this image shows me cutting up a wool poncho which can be made from 910 yarn (19 felt patches worth) to yield 144 felt patches (7200 yarn worth) the core issue seems to be that yarns stats is not in line with felt patches leading to problems.an ex ample would be that seemingly every case of cutting up an item made from yarn into felt patch leading to a net gain of yarn. below is a comparison of 50 units of yarn with 1 felt patch, among other things you'd expect the mass to be the same but clearly it isn't

![image](https://user-images.githubusercontent.com/78816055/193425979-1e0f9534-c551-4162-875a-7dda11e58481.png)
