### ISSUE TITLE
Body Feature encumbrance causing glove impedement on spells.

### ISSUE THREAD

**Issue by Xynon7** [CleverRaven/Cataclysm-DDA#61338]
### Describe the bug

Any modifications to your body that cause hand encumbrance over 5 on each hand will begin causing spells to be more expensive.

### Steps to reproduce

Can be reproduced many ways, but an easy one.
1. Choose any mutant start and take the 8 tentacles trait.
2. Learn a spell.
3. You will see that the spell has a 250 mana additional cost due to your tentacles, as well as always being marked (impeded)

### Expected behavior

As the wording on this feature in spells is "impeded by gloves" I did not expect body features to contribute to this (indeed, I thought tentacles were a good fit for these spells because i wasnt going to wear gloves anyway!). I would expect parts of your body to not trigger an impedement specifying gloves.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 90fc2e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

I was unsure whether to put this as a bug report or a feature request, but from the original wording this seems not to be the intended result and so I have filed as a bug report. My thoughts are that the solution is one of two things
1. This is the intended behavior, in which case I would change the text to not say gloves specifically for these requirements, although I am not sure exactly what phrasing would cover all cases here.
2. This is not intended and we dont want things like Phelloderm and Tentacles to contribute to spell cost (although Phelloderm only contributes if its already past the encumbrance threshold). In this case, it would seem best to me to add an alternate encumbrance grabbing method that excludes encumbrance from body features. I believe something like this already exists, as the status screen does not show the encumbrance from tentacles (it does show the Phelloderm encumbrance since its "armor" and not just a trait).

**Comment by Terrorforge** [comment]
It's the messaging being unclear. All the Magiclysm spell tag descriptions are dogshit, tbh. What "impeded by gloves" actually means is that the spell has the SOMATIC tag, which indicates that you use your hands to cast them. Not only are SOMATIC spells affected by all hand encumbrance rather than just gloves, you must also have your hands free to cast them. Neither of those things are communicated well.

**Comment by Xynon7** [comment]
As far as I can tell actually, Somatic is its own tag, not the same as impeded by gloves. Does something similar though, just with arm encumberance. I suppose any of the stuff based on encumberance would do this.
