### ISSUE TITLE
Crash When Viewing Shoulder Strap

### ISSUE THREAD

**Issue by Pspritechologist** [CleverRaven/Cataclysm-DDA#61344]
### Describe the bug

Viewing the shoulder strap in the crafting menu crashes the game.

### Steps to reproduce

Open the crafting menu, search for or highlight the shoulder strap.

### Expected behavior

View the shoulder strap without the game crashing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1288 (20H2)
- Game Version: cddb9bd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

[Additional Context.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9671670/Additional.Context.zip)
I wasn't able to find the crash.log file, if someone can point out where it was, I'd be happy to add it.

This issue has persisted for over six months of updates for me (As it occurred just now, prompting me to update my six month old game). With some Googling, you can find reports of this from over a year ago, but with iffy responses of reproducibility, as far as I can tell. Thought I may as well throw my hat into the ring of "Doesn't work on my PC."

**Comment by Night-Pryanik** [comment]
I loaded your world and tested on both of your characters there. I searched for shoulder strap in the crafting menu, and I got no crash.
![изображение](https://user-images.githubusercontent.com/11132525/193409666-f0d46ab3-f0ea-4d16-83af-4c1a3e30112e.png)

**Comment by TheShadowFerret** [comment]
Also anti-confirmed
![image](https://user-images.githubusercontent.com/99621099/193421490-09948731-1ce7-4809-94ab-4386005e1250.png)
- OS: Windows
    - OS Version: 10.0.22621.521 (22H2)
- Game Version: cd02b91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by Pspritechologist** [comment]
I have no idea then, it must be some super niche thing, there was at least one other report of this. I'll mess around with my local stuff a bit, sorry for the report.
