### ISSUE TITLE
Torch doesn't burn out properly

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#61358]
### Describe the bug

When a torch "runs out of fuel", it is at the amount you can light it for only 1 second, but it does NOT actually burn out.

### Steps to reproduce

1. Get a torch. The ready to use one.
2. Light it up.
3. Wait for a while.
4. You'll clearly see it isn't actually burned out, just "Almost out of fuel".
5. Try to light it again.
6. 3-4 should happen again and never burn out.

### Expected behavior

Should actually turn into burnt out torch when out of fuel.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 7464d7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by GuardianDll** [comment]
FYI #59552

**Comment by RenechCDDA** [comment]
This is a separate issue, is it not? Flares properly turn into "dead flare", torches just need to do the same thing. The fact they don't is quite surprising, actually.

**Comment by EIIKaO** [comment]
> This is a separate issue, is it not? Flares properly turn into "dead flare", torches just need to do the same thing. The fact they don't is quite surprising, actually.

You are right. It seems bug.
For example,
```diff
diff --git a/src/item.cpp b/src/item.cpp
index 6e7a5aea79..bce1d6bce9 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -13317,7 +13317,6 @@ bool item::process_tool( Character *carrier, const tripoint &pos )
 
         // invoking the object can convert the item to another type
         const bool had_revert_to = type->tool->revert_to.has_value();
-        type->invoke( carrier != nullptr ? *carrier : player_character, *this, pos );
         if( carrier ) {
             carrier->add_msg_if_player( m_info, _( "The %s ran out of energy!" ), tname() );
         }
@@ -13325,6 +13324,7 @@ bool item::process_tool( Character *carrier, const tripoint &pos )
             deactivate( carrier );
             return false;
         } else {
+            type->invoke( carrier != nullptr ? *carrier : player_character, *this, pos );
             return true;
         }
     }

```
In this case, the torch turns into a burnt torch when the fuel runs out.
For now, the code above seems to be working as expected, as far as I have tried torches and flares, as well as chainsaws, electric chainsaws, and MP3 players.
