### ISSUE TITLE
Unable to continue in-progress crafting because unable to pick up

### ISSUE THREAD

**Issue by reusityback** [CleverRaven/Cataclysm-DDA#61354]
### Describe the bug

When I'm trying to craft an anvil, I'm not able to continue the in-progress anvil ("Too heavy to pick up"), although I have enough carrying capacity. The materials (40 lumps of steel, that is 5.2L, 40kg) fit well into the hiking backpack I'm wearing, though.

### Steps to reproduce

1. Start crafting anvil (with lumps of steel)
2. Discontinue crafting
3. Try to resume crafting by "Using item"

### Expected behavior

I was expecting to be able to resume the crafting when discontinuing, because I was able to gather the materials (capacity-wise) and to start the craft.

### Screenshots

![Screenshot_20220929_223921](https://user-images.githubusercontent.com/98353605/193137568-dae731fa-dd99-4a46-a9ff-4416b6a55633.png)
 At the bottom is "in Verarbeitung Amboss (14%)" which I can't resume or pickup although I have a hiking backpack (Wanderrucksack) at the top with enough capacity.
![Screenshot_20220929_224507](https://user-images.githubusercontent.com/98353605/193138445-967c437a-5194-4474-9833-849c9db78718.png)
The hiking backpack has a bag with 50l and 50kg capacity, which should be enough for carrying the anvil, unless it weighs more than it's raw materials.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 65b77c9 [64-bit]
- Graphics Version: Tiles
- Game Language: German
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
The work around for the issue of not being able to resume crafting is to pick the in-progress item up as wielded, not carried (i.e. using the "wield" command). This may knock you down on the ground if the item is too heavy, slowing crafting (happened to my 9 STR character in 0.E-2 with the anvil).
Also note that you may have to make sure you're not "wearing" items in your hand(s) such as a shopping bag, as you may be refused to wield "two-handed" items while "wearing" such items.

**Comment by robotic-gamer** [comment]
alternatively couldn't you just use the construction menu to designate a crafting spot and then just use that?

**Comment by reusityback** [comment]
> alternatively couldn't you just use the construction menu to designate a crafting spot and then just use that?

I'm new to C:DDA so I didn't this feature yet, but thought I should be able to resume it anyways. 

Nevertheless, wielding the in-progress item is a workaround for me.
