### ISSUE TITLE
RM13 Combat Armor's UPS Battery charge are unloadable

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#61363]
### Describe the bug

You can unload an RM13 Combat Armor and get the battery charge without an actual battery

### Steps to reproduce

1. Debug spawn RM13 Combat Armor
2. Unload
3. Get an item "battery (5000)" [incase that it's debug spawned and has 5000 UPS charge

### Expected behavior

Shouldnt be unloadable

### Screenshots

![Screenshot_2022-09-30-15-50-16-1154942919](https://user-images.githubusercontent.com/95905384/193223340-b142f90c-c18a-42b8-9549-15204431bb03.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: 9d1264a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Teleporter [Teleporter],
    Artifact Jewelries [Artifact Jewelries]
]

**Comment by anoobindisguise** [comment]
Oops, I'll add no_unload to it.
