### ISSUE TITLE
Enchantments not working whenever a new change with enchantments are rolled out

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#61364]
### Describe the bug

Enchantments from your currently owned items will stop giving their effects (actives not affected) to you whenever you update into a version that changed something with enchantments.

This includes Nomad Jumpsuits, Artifacts, RM13 Combat Armor and other items that has enchantments.

### Steps to reproduce

1. Play an old version earlier than a version that changed something with them.
2. Spawn an artifact or any item that has enchantments.
3. Update into a version or newer versions with changes regarding enchantments.
4. Earlier spawned artifacts and items with enchantments will stop giving their effects.

### Expected behavior

Their enchantments should not stop giving their effects to you

### Screenshots

151.3 carry weight without Light Nomad Jumpsuit
![Screenshot_2022-09-30-16-23-09-0235067445](https://user-images.githubusercontent.com/95905384/193228187-7b3dcbea-6443-4518-93ee-e52d79b6a2b2.png)

151.3 carry weight wearing pre-existing Light Nomad Jumpsuit
![Screenshot_2022-09-30-16-23-26-0051796727](https://user-images.githubusercontent.com/95905384/193228392-0529423d-ff7d-4d27-aaa7-3929a17ff01d.png)

162 carry weight wearing a newly debug spawned Light Nomad Jumpsuit
![Screenshot_2022-09-30-16-25-42-0122241040](https://user-images.githubusercontent.com/95905384/193228533-0124851a-6520-4799-a268-14f54e48fb4b.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: 9d1264a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Teleporter [Teleporter],
    Artifact Jewelries [Artifact Jewelries]
]

**Comment by Dan1ss1mo** [comment]
can confirm, after each save reaload all enchantments cease to function

**Comment by Ramza13** [comment]
Probably the same as #61308 but this has new details so thank you.
