### ISSUE TITLE
Kevlar gives the Uncomfortable debuff.

### ISSUE THREAD

**Issue by Zyzarda** [CleverRaven/Cataclysm-DDA#61360]
### Describe the bug

When wearing my kevlar security vest, it gives my character -2 speed and a constant pain debuff. I would understand this be the case if I was wearing an actual vest with ceramic or metal plates, but Kevlar is generally not tough enough to cause pain while wearing.

### Steps to reproduce

Wear "security ballistic vest" item, and you will incur a pain and speed penalty.

### Expected behavior

I don't understand why 4.4mm of kevlar weaving would cause physical pain to the wearer.

### Versions and configuration

Cataclysm-DDA experimental build 2022-09-30-0256

Tiles

  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "package_bionic_professions",
  "blazeindustries",
  "xedra_evolved",
  "alt_map_key",
  "crazy_cataclysm",
  "extra_mut_scens",
  "MMA",
  "magiclysm",
  "sees_player_hitbutton"

**Comment by TheShadowFerret** [comment]
Cannot be confirmed

![image](https://user-images.githubusercontent.com/99621099/193421388-5cdf66b8-6497-498b-b687-7d18e19635a5.png)

**Comment by l29ah** [comment]
Cannot reproduce, would be nice if you provided the save.
