### ISSUE TITLE
Windows build test failing

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61378]
### Describe the bug

`20:51:10.318 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp:1501 [put_in] tried to put an item (creepy_doll) count (1) in a container (purse) that cannot contain it: pocket unacceptable because not enough space`
@Maleclypse wanted me to open an issue for this. I've seen a similar error to this quite a few times in previous PRs.

### Steps to reproduce

?? It seems to happen at random and I have no idea how the test works

### Expected behavior

The test should pass, but I don't know what's causing it to fail and as a result, what needs to change.

### Versions and configuration

current

**Comment by mqrause** [comment]
Maybe also #59873, or a similar issue with another item group. A link to a test failure would be nice to get some context.

**Comment by anoobindisguise** [comment]
> Maybe also #59873, or a similar issue with another item group. A link to a test failure would be nice to get some context.

Unfortunately the PR that prompted this issue to be submitted already had that test bumped so it's no longer visible there. (#61328)

**Comment by mqrause** [comment]
For these somewhat random errors in non-required tests, it's better to just leave them as is so people can check where they actually happened.
