### ISSUE TITLE
Fake vehicles tile working a bit TOO well.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#61385]
### Describe the bug

#56143 PR made it so that vehicle tiles sometimes generate a fake part to fill in the diagonal gap. That's great for cars, but it works on something like shopping carts as well, and this makes it impossible to squeeze the shopping cart through a 1 tile gap they normally can go through just fine.

### Steps to reproduce

1. Spawn a shopping cart.
2. Try grabbing and dragging it around tighter corridors. In my case, in some of the military outpost's corridors.
3. Sometimes, diagonally, it refuses to go through the gap it could've went through in previous versions.

### Expected behavior

Should've been able to get it through.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: a4b97ec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by anoobindisguise** [comment]
I haven't seen this with shopping carts but it has happened with 2x1 food carts.

**Comment by FayFlightee** [comment]
![image](https://user-images.githubusercontent.com/71143790/193433332-b8aac800-821c-4521-ae1a-4746cfc76b76.png)

Here's one is similar issue. This one is vehicle welding rig cart, and it just doesn't work.

**Comment by FayFlightee** [comment]
![image](https://user-images.githubusercontent.com/71143790/193433463-b37fe1b2-2921-4a7c-8d30-4a17d829d6b5.png)
Or this. This one the fake part is even OVER a normally impassable tile (on top of metal locker).

**Comment by FayFlightee** [comment]
New issue found, this seems to be **specifically** affecting the diagonal direction from bottom left to top right. The other diagonal line doesn't trigger the fake vehicle part... for whatever reason.
