### ISSUE TITLE
"Folding stock" mod does not reduce gun volume when folded

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#61384]
### Describe the bug

Folding an integrated stock reduces the volume as expected, but folding the stock on a gun with the "fodlable stock" mod doesn't

### Steps to reproduce

1. Install "foldable stock"
2. Fold

### Expected behavior

Folding the stock decreases the effective volume of the gun.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/193407145-fdf38ad0-f5b5-4bea-8f3b-37522f25a00d.png)
![image](https://user-images.githubusercontent.com/5107449/193407177-539e67cb-3ea1-40c2-8f7d-a228245b4abb.png)
Integrated stock

![image](https://user-images.githubusercontent.com/5107449/193407052-2ca36853-22c6-4c48-90bd-5614dfbe286a.png)
![image](https://user-images.githubusercontent.com/5107449/193407592-ccfcffad-1563-4315-a8ac-069181656412.png)
Folding stock mod

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: cd02b91 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

Folding stock mod

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: cd02b91 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

**Comment by Terrorforge** [comment]
I did, that's what doesn't reduce the volume.

Looks like I pasted the wrong screenshot of the modded vz.71. Updated with one that shows the 8folded) version is shorter, but the same volume.

**Comment by Night-Pryanik** [comment]
Well, the description of collapsible wire stock mentions that it reduces length and volume, while folding stock says that it only reduces length. So I'd say everything works as expected.

**Comment by Terrorforge** [comment]
Ugh, right. I couldn't find the original PR, but now that you mention it, that was in there. A folding stuck just sort of sits on the side rather than disappearing into the body like a collapsing stock, so the volume doesn't technically change.

False alarm, feature not bug.
