### ISSUE TITLE
The bug of temperature map

### ISSUE THREAD

**Issue by ObserVanMontage** [CleverRaven/Cataclysm-DDA#61386]
### Describe the bug

The temperature map shows incomprehensible figures in Celsius and Kelvin, in Fahrenheit it simply does not show.

### Steps to reproduce

Opening the temperature map using any assigned key.

### Expected behavior

The temperature should be displayed correctly depending on the unit of measurement.

### Screenshots

![Дарен Далтон _2022-10-01T14-55-08](https://user-images.githubusercontent.com/114693612/193408476-46f4efb4-e159-498e-ac1a-1de0439889bf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: cd02b91 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by RedBloodCat** [comment]
Still a problem
