### ISSUE TITLE
Repairing articles of clothing is laggy asf

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#61380]
### Describe the bug

When I try to repair clothes, the game lags/freezes for a good few seconds.

### Steps to reproduce

1. get clothes to repair and a sewing kit
2. Loading.gif
3. List of items loaded after a while.
4. Change page from 1/3 to 2/3.
5. Loading.gif
6. Repair an item.
7. Loading.gif
8. Try to fit/repair/reinforce.
9. Loading.gif

### Expected behavior

No freezes or lags

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: 5e89406 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Teleporter [Teleporter],
    Artifact Jewelries [Artifact Jewelries]
]

**Comment by KHeket** [comment]
Same is when you are trying to repair with welding kit or soldering iron
Caused by repair rework https://github.com/CleverRaven/Cataclysm-DDA/pull/59827

**Comment by KHeket** [comment]
@Night-Pryanik is there any way to improve performance or return old repair system until new version will not be fast?

**Comment by Lestraus** [comment]
The problem is also occurring on the PC, following the "Rework repair menu #59827".

https://user-images.githubusercontent.com/114821001/193416922-93db35a9-1278-44dc-a699-f6868aee1868.mp4
