### ISSUE TITLE
More Guns in Generic Guns mod

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#61381]
### Is your feature request related to a problem? Please describe.

The current Generic Guns mod is quite boring to play with. You find nothing but sporter carbines in a surplus store!

### Solution you would like.

More varieties for guns. Stuffs like hunting rifle, tiny pistol revolver, semi-auto sniper rifle (DMR)...

### Describe alternatives you have considered.

Add `variants` for each guns. It's weird that the defensive pistol you find are all the same.

**Comment by Maleclypse** [comment]
The solution to this would just be not activating generic guns, then turn off brand names for guns in options in.

**Comment by NotSeawhite** [comment]
Well, I know little about guns, so I play with the mod to make the game less frustrating.
All I know is some pistols use 9mm, others don't.

**Comment by RAldrich** [comment]
I'm not sure why this is an issue - gun brand names are off by default. Simply do not activate the mod and do not enable brand names in the options and you should arrive at your desired state.

**Comment by NotSeawhite** [comment]
One of the reasons why I use Generic Guns is I often face the issue where I find a lot of 7.62mms but I don't know which guns use that.
