### ISSUE TITLE
wasps not bound to nest

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61399]
### Describe the bug

if you keep a wasp nest loaded in your reality bubble for long enough all the wasps (including the queen) not trapped by the nest walls will eventually abandon their nest and wander off in random directions

### Steps to reproduce

debug teleport yourself into the ground beneath a wasp nest and wait a very long time.

### Expected behavior

the wasps, especially the queen to not wander away from their nest

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: aa80ff7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    No Hope [no_hope]
]

### Additional context

probably rarely encountered because its unlikely people will spend long enough near a nest. though it could happen if your base just happens to be close enough for it to load but far enough that you don't initially get into fights with them.

**Comment by Venera3** [comment]
Yeah, some patrol routes for the guards is something I want to hook up. The wasp houses will need to get unhardcoded, and I'd like patrol code to be a bit better with regards to getting kited but it's workable.

**Comment by PatrikLundell** [comment]
Is this related to trap spiders wandering off (#61017)?

**Comment by Venera3** [comment]
Not beyond out monsters not having a "sit on your arse, pretty please" switch - a mob will wander when it doesn't have a target unless it's incapable of moving. Trapdoors have other problems in their implementation, so they're orthogonal at best.
