### ISSUE TITLE
Magicalysm Item effects disabled 

### ISSUE THREAD

**Issue by Dembara** [CleverRaven/Cataclysm-DDA#61392]
### Describe the bug

Magic items (e.g. ring of intelligence +2, boots of haste, etc) apply their effects at first when starting a new game. However, upon reloading they stop having any effect.

### Steps to reproduce

1. Reset world. Get some stat-changing magic item.
2. Save and quit
3. Load world (the stat-changes from item(s) are gone).

### Expected behavior

The items should have the specified effect.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.978 (21H2)
- Game Version: 07a9641 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by GuardianDll** [comment]
#61308

**Comment by Kywi001** [comment]
#61364 for more info

You cant fix them in anyway shape or form right now so I suggest to just debug spawn a new set of them.

**Comment by Dembara** [comment]
> #61364 for more info
> 
> You cant fix them in anyway shape or form right now so I suggest to just debug spawn a new set of them.

The problem persists if I spawn new ones. The enchantments only start working when I reset the world.
