### ISSUE TITLE
Houses shouldn't be made of "Field Stone Wall"

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61404]
### Is your feature request related to a problem? Please describe.

These walls are just loosely fitted rocks without mortar. That's completely inadequate for building homes but many houses and mansions are made from them.

### Solution you would like.

Remove from the pool.

### Describe alternatives you have considered.

Change them to fitted, mortared cobblestones.

**Comment by utechenko-v** [comment]
I think adobe brick walls for regular city houses should also be revised. I suppose adobe walls are suitable for some huts in swamps or something like that.
