### ISSUE TITLE
Medical primer triggering cannibalism mood debuff

### ISSUE THREAD

**Issue by Blorkman** [CleverRaven/Cataclysm-DDA#61411]
### Describe the bug

When injecting medical primer, it is treated as being made of human parts, and as such triggers the massive mood debuff.
This is because the medical samples it is crafted with can be crafted from human samples, but its an alternative to the main way of obtaining them : dissecting motionless deers, helpless dogs, and twitching spiders that can be found in dermatiks hives. Also i did not try other human sample based primers but i guess it's the same problem since they can be crafted from human samples.
For those who wonder, "human samples are human parts, so isn't it intended that they trigger the cannibalism debuff ?", i cannot agree because it simply makes no sense : primers are processed mutagenic serums that you inject with a syringe, they should not trigger the cannibalism debuff, because you don't eat them (even if you did, human sample based primers are surely not human meat slurry, more like human genetic material slurry). Especially for the medical primers/samples that are really not of human origin despite being craftable from human samples.

### Steps to reproduce

1. Consume a medical primer (or probably any primer crafted with human samples)
2. You get the cannibalism prompt (if you don't have the cannibal trait)
3. If you proceed you will get a hefty mood debuff

### Expected behavior

Mutagenic primers should not trigger the cannibalism mood debuff when injected

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: b87b910 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment]
perhaps the cannibal debuff should scale with amount of human flesh contaminated material you consume. this would result in the mood debuff for mutagens becoming neglectable due to how small and light mutagens are.

**Comment by Blorkman** [comment]
> perhaps the cannibal debuff should scale with amount of human flesh contaminated material you consume. this would result in the mood debuff for mutagens becoming neglectable due to how small and light mutagens are.

This may be a good idea, but still in the case of mutagenic primers it should not trigger it at all. Think about it this way : would getting a blood transfusion mentally scar you ? Of course not, despite blood being human material.

**Comment by PatrikLundell** [comment]
I obviously don't have any first hand experience, but I would expect the mere act of cannibalism to cause a major emotional effect, rather than scaling with the volume, although I could imagine there being an additional barrier between "ritual" cannibalism in the form of a very small piece (and the ritual context possibly reducing the impact), and "sustenance" cannibalism, possibly with new hits for additional parts consumed.

The blood transfusion example is a good one, and there are also other cases where injected substances have been of human origin, e.g. growth hormone for treatment of growth deficiencies.
