### ISSUE TITLE
make hidden items unusable

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61414]
### Is your feature request related to a problem? Please describe.

designating a container with items that is in your inventory as hidden does not stop you from consuming the items in there (ie a plastic painkiller bottle with multiple types of pills). this means you can't use this feature to do things like make it so you can't accidently use an item that you really don't want to use by accident (grenades, Datura seeds etc. ).

### Solution you would like.

items in containers that are set to hidden can't be used for anything until the container is set back to unhidden.

### Describe alternatives you have considered.

confirmation you would like to use a potentially dangerous item.

### Additional context

this would also fix the issue of you being able to use items that were in a preexisting container set to hidden (first aid boxes, wallets  etc.)

**Comment by Kywi001** [comment]
Ngl, as someone who hides almost everything, this is gonna be a huge pain in the ass.

Other suggestion:
Have a special tag that you can add to an item so you can never use them unless you untag them.

**Comment by andrei8l** [comment]
The opposite of #52706.

**Comment by jiornojiovanni** [comment]
I don't think this is a good feature to add like this. It is much better to add something like "mark as forbidden" or something like that

**Comment by robotic-gamer** [comment]
should I create a separate issue for a "mark as forbidden" ability, or should I just convert this issue over to the better idea?

**Comment by RAldrich** [comment]
Is the existing "favorite" functionality insufficient here? Tagging an item as a favorite causes it to show up as bright purple and warn when you try to use it in a crafting recipe.

I've personally never "accidentally" used a grenade.
