### ISSUE TITLE
CTD without log. Game freezes.

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#61425]
### Describe the bug

No logs make very difficult to track whats going on.

### Steps to reproduce

Hallucinating because I start with opiates and crack dependence. I think is linked with some hallucination spawn.
The crashes are random. Game often freezes and CPU is stuck at max demand. Must be some kind of loop?
Close game using task manager. No logs.
This is not new , happens in several versions.
After character recovers the game work normal, that is  the reason I think hallucination and monster spawn is the cause. Or perhaps old rig?

### Expected behavior

No freeze or some log file.

### Versions and configuration

Win 7
Last experimental, tried several version and no changes.
Tried with no tiles too.
No sound.

**Comment by EIIKaO** [comment]
> Hallucinating because I start with opiates and crack dependence. I think is linked with some hallucination spawn.

I think there is enough possibility.
May be related to #60371 ( the guy in this attached saved data is also in drug abstinent ).
But in my experiment, both of issues can't reproduce yet.

**Comment by Nebnis** [comment]
I think this has to do with enemies trying to spawn inside walls and places where they can't move. Or enemy movement in general. I had this happen with my alcohol withdrawal character too, and very incredibly often. I had the exact same problem of that guy with my game constantly hanging on lab spawn, i debugged teleported him elsewhere and it stopped but after a while it came back again. I have a feeling a specific hallucination might be causing this which is why you can't reproduce, there is quite a lot of them! 

My other save happens less often with no alcohool syndrome(also lives near a lab spawn on top)

**Comment by KymasTuran** [comment]
Thanks for answer.
I finally can sleep after edit JSON files and disable hallucination.
I have a theory: After browse inside the files with the purpose of disable the effect I found one where a "group monster" is called in hallucinations. But in hallucinatory state I see monster I made myself and from mods too.
Having account that there still bugs where NPC-hallucination throw guns to monsters and the gun is real and can be picked (prompt for steal) I guess that one of the monster or NPC  have a effect like amigara for example that make the game hang.
For fix this I suggest a list of monster and personalized NPC without guns and lock away the ones outside that list. Mods must add what monster goes for the "Hallucination group".
Hope my english is clear enough :p

**Comment by jiornojiovanni** [comment]
Strange. Time to time it happens to me, but i never play with traits that cause hallucinations. Today i lost two new characters for this, one for the crash and one for the freeze (feelsbadman)

**Comment by Nebnis** [comment]
> Strange. Time to time it happens to me, but i never play with traits that cause hallucinations. Today i lost two new characters for this, one for the crash and one for the freeze (feelsbadman)

what are the traits your character got? where you sleeping? Is there monsters around

**Comment by jiornojiovanni** [comment]
> what are the traits your character got? where you sleeping? Is there monsters around

![immagine](https://user-images.githubusercontent.com/31773561/194007380-39ca2dd3-0b49-47be-8532-c8d97777b1fa.png)
These were the traits
When it crashed i was just wandering around, when in froze i was sleeping (they were two different characters, with the same preset)

I'm pretty sure there were no monsters around.
