### ISSUE TITLE
Crash axe stats are higher than reasonable 

### ISSUE THREAD

**Issue by Rllaman** [CleverRaven/Cataclysm-DDA#61434]
### Describe the bug

The crash axe literally says in its description that it's supposed to have the same stats as a hatchet. However, it deals 17 bashing and 28 cutting damage, while the hatchet deals 10 and 20 respectively. This makes it far better than almost any weapon in the game of the same weight.

### Steps to reproduce

This issue is obvious.

If necessary, create a new character, spawn a crash axe, and compare its expected DPS to any other weapon.

### Expected behavior

A crash axe is basically a hatchet, so they should be similar.

If anything, it should be slightly weaker than a small axe that was designed to be used in combat.

### Screenshots

![Screenshot_20221003-133330](https://user-images.githubusercontent.com/96686771/193642482-9a070fc4-4563-4228-a56a-f3a636791abe.png)
![Screenshot_20221003-133253](https://user-images.githubusercontent.com/96686771/193642525-f4b30f42-8435-4504-b187-9c8f168fc1bc.png)

### Versions and configuration

Latest version

**Comment by anothersimulacrum** [comment]
It would be appropriate to make it's stats match that of the hatchet.

**Comment by Ezrashaw** [comment]
If its still open, I'd like to work on this.

**Comment by Rllaman** [comment]
> If its still open, I'd like to work on this.

Sure, that would be good. I just reported this, but I don't know how to fix things myself. Thanks.
