### ISSUE TITLE
activating frozen honey comb lets you "eat it" without item loss

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61433]
### Describe the bug

if you activate a frozen honey comb get the mood bonus from eating it but you keep them item

### Steps to reproduce

get a honey comb
make it frozen
activate it
observe mood bonus while still having the item

### Expected behavior

not being able to eat an item without actually eating it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: aa80ff7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    No Hope [no_hope]
]

### Additional context

the honey comb was from a hallucinated bee bot (see #61432)

**Comment by Aut-Baron** [comment]
I mean, you can get a mood bonus from food taste without eating it. Basically I mean licking the honey comb taste good.

**Comment by PatrikLundell** [comment]
I wouldn't be surprised if the code found edible honey, decided that it should be eaten, and then tried to re-find an unfrozen honey comb to remove it, failing to find it, and then just continue one.

Another possible failure reason is cache issues in which the cache is cleared between locating the honey comb and the removal of a matching honey comb item after eating it.

Does it matter where the honey comb is located (i.e. in the character inventory as opposed to a nearby location, possibly in another world tile)?
