### ISSUE TITLE
Using diary with records of killed mon_endless_hunger causes game-locking error

### ISSUE THREAD

**Issue by Sutremaine** [CleverRaven/Cataclysm-DDA#61445]
### Describe the bug

 DEBUG    : invalid monster type id "mon_endless_hunger"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mtype]
 FILE     : src/generic_factory.h
 LINE     : 448
 VERSION  : edb21b9

Attempting to access or read diary entries with kill lists containing Endless Hungers causes a json error, as does accessing the normal kill list. On some entries, tapping the Space button repeatedly does not clear the error, leaving the game stuck on that screen.

### Steps to reproduce

Have an older experimental version (25th August in this case), update to more recent version (1st October). Have Endless Hunger kills, from before and after date of older version. Access diary or kill screen in more recent version.

### Expected behavior

No error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: edb21b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Xedra Evolved [xedra_evolved],
    No name (mods_personal) [mods_personal]
]

### Additional context

I doubt it's the stuff in mods_personal doing it, since that was active in my last game update, but here you go anyway?

[cdda modded item list.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/9701341/cdda.modded.item.list.txt)

**Comment by NetSysFire** [comment]
You got quite a few mods there. Can you try and reproduce it with just the default mods? Spawn and kill it with debug powers and then use the diary.

**Comment by GuardianDll** [comment]
How you can kill one in natural way?

**Comment by robotic-gamer** [comment]
esc (access menu)
display key binding menu (to access key binding)
scroll to bottom (to put debug menu in view)
add a keybinding from the "debug menu"
go back to game
hit key for debug menu
go to spawning
select spawn monster
use search tool to find the monster you want to spawn
spawn it
go back to main debug menu
go to map
select kill in area
select 1 by 1 zone for monster
kill monster

**Comment by Sutremaine** [comment]
I can't spawn the monster on the recent version (either 1st October or the most current e39079b) because it doesn't exist anywhere any more. Restoring it to the nether.json monster file fixes this error, but that's not enough by itself because if it does get spawned it'll be missing its death effect and special attack. So I removed any reference to those two things and popped it into the currently-empty obsolete.json. The creature entry still needs some details for the bestiary, and it'd probably be a good idea to give it a weight of one gram. Without its death effect it leaves a corpse that weighs nothing, which will probably cause some problem somewhere at some point.

PR to make those changes and put it in the "obsolete" file?
