### ISSUE TITLE
Non zombie enemies should not be made of tainted meat

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61448]
### Is your feature request related to a problem? Please describe.

As is current, there are a lot of Nether and adjacent enemies that aren't zombies, but still produce tainted meat when killed, which is suitable for mutagens. Examples include the leech plants, Mi-Gos, Flaming Eyes and some others. Since these are not creations of the Blob, their meat shouldn't contain blobmatter.

### Solution you would like.

There should likely be another category of meat. Currently we have:
- Human food (anything pre cataclysm)
- Edible but poisonous alien meat (toxins in mutant fauna)
- Edible alien meat (Demihuman meat and albino penguins)
- Inedible alien meat (tainted zombieflesh)
There should likely be another "type" to represent something that isn't close enough to your biology to eat safely but also isn't zombie flesh and isn't capable of making mutagens. 

### Describe alternatives you have considered.

What should happen if you eat a Mi-Go corpse anyhow?

**Comment by Sutremaine** [comment]
Maybe meat with 0 calories and no vitamins. It looks and cooks no worse than mutant meat, but the intestines can't take any nutrients from the stomach-churned slurry. For the player, this allows recipe practice but makes the meat useless as actual food.

**Comment by fairyarmadillo** [comment]
I imagine eating a mi-go would be like trying to eat a starfish or something. [It would not go well.](https://youtu.be/F_KfeoXJWG0)
