### ISSUE TITLE
Pseudo furniture in fields [no hope]

### ISSUE THREAD

**Issue by ProvoGo** [CleverRaven/Cataclysm-DDA#61453]
### Describe the bug

Pseudo furniture is showing up in fields

### Steps to reproduce

Make world with the mod no hope
Go to fields
Find pseudo furniture

### Expected behavior

That there are no pseudo furniture

### Screenshots

![Weird bug](https://user-images.githubusercontent.com/36768970/193716423-05241a08-dd17-42be-9211-66ad704b99af.PNG)

### Versions and configuration

Windows 10

e39079b

tiles

English

dda, no_npc_food, no_fungal_growth, package_bionic_professions, no_hope

**Comment by Night-Pryanik** [comment]
Could you please provide a savegame demonstrating this bug?
