### ISSUE TITLE
Prompt for taking off hand encumbrance when crafting

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#61457]
### Is your feature request related to a problem? Please describe.

Hand encumbrance makes crafting times much longer, character should be smart enough to automatically take off gloves during crafting without manual micromanagement by player.

### Solution you would like.

A prompt or setting to automatically take off gear and put it back on during crafting, if it interferes with crafting.

### Describe alternatives you have considered.

Removing negative effects of gear on crafting speed.

### Additional context

Could be extended to other actions that are affected by gear encumbrance, like climbing up/down so you throw your backpack up/down before proceeding.

**Comment by PatrikLundell** [comment]
Crafting isn't a clear cut case, since you may need to wear the gloves in order not to get frost bite on the hands when crafting in cold locations.
