### ISSUE TITLE
Bugged Hazardous waste sarcophagus

### ISSUE THREAD

**Issue by Blorkman** [CleverRaven/Cataclysm-DDA#61467]
### Describe the bug

I knew from other bug reports that the elevator wasnt working, but by trying to debug teleport i found out that they simply have no underground structure : its only solid earth from top to bottom. Is this known ?

### Steps to reproduce

1. Debug teleport to level -1 to -10 of an hazardous waste sarcophagus
2. Only solid earth to be found

### Expected behavior

Pretty obvious : an underground structure should be here

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: b87b910 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
The sarcophagus is at Z=-2, not -10. #60068 relevant also

**Comment by Blorkman** [comment]
> The sarcophagus is at Z=-2, not -10. #60068 relevant also

No you misunderstood what i said, there is NO sarcophagus whatever level i checked with clairvoyance, z=-2 included

**Comment by sonphantrung** [comment]
Provide save file please, it'll speed up the whole bug report process

**Comment by Blorkman** [comment]
Here you go, you just have to teleport to one of the two on the overmap
https://mega.nz/file/3pQiyTrR#d1_FtIzIWMry4ScQ2wIKZy3WBcn1fZYueoakwdIEl-s

**Comment by Blorkman** [comment]
Ok so my bad, the basement DOES generate, its just that i cannot figure out how to debug teleport between Z levels, if someone could tell me how i would very much appreciate, thank you.
