### ISSUE TITLE
glass fragments as pebble type ammo

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61463]
### Is your feature request related to a problem? Please describe.

ranged weapons that use pebble type ammo like slingshots are easy to craft early game in "urban areas" (city, lab etc) but ammo for them is very hard to come by in sufficient quantities.

### Solution you would like.

being able to break up glass shards into smaller fragments for use as pebble type ammo

### Describe alternatives you have considered.

breaking up ceramic shards into pebble equivalent.

### Additional context

given that most glass is found in thin sheets it would should be fairly easy to just break along where the glass is thin to create the smaller fragments.

**Comment by Zireael07** [comment]
IIRC ceramic shards used to be an ammo option, but I don't recall the reasons for removal (would likely apply to glass shards too)

**Comment by robotic-gamer** [comment]
> IIRC ceramic shards used to be an ammo option, but I don't recall the reasons for removal (would likely apply to glass shards too)

perhaps they were considered "too big". a glass shard is 0.03L and 0.07kg, while a marble is 0.01L and 0.00kg.
more significantly a ceramic shard is 0.25L and  0.75kg
if this was the problem a different item as ammo could fix it.

**Comment by NotSeawhite** [comment]
I wonder if it can damage anything other than your hand..

**Comment by Kywi001** [comment]
It can probably do damage, but given it's a shard and not something round, goodluck even remotely hitting using it as an ammo

**Comment by Kywi001** [comment]
> how much better would a pebble you got by smashing rock be in terms of roundness?

Definitely better than glass shards, since glass shards have a thinner part, the most you can do to turn a glass shard into a projectile is by throwing it like a shuriken or like how you would throw a card, afterall, cdda glass shards are big enough to allow us to create a glass shiv while pebbles are, well, just as small if not smaller than marbles.

**Comment by robotic-gamer** [comment]
I am going to close this since with everyone's comments glass is unsuitable. that and I realized crudely forged copper projectiles would work better.
