### ISSUE TITLE
Add various countries flags

### ISSUE THREAD

**Issue by sonphantrung** [CleverRaven/Cataclysm-DDA#61462]
### Is your feature request related to a problem? Please describe.

New England and the US in general are multicultural places!

### Solution you would like.

Add flags representing various countries like French flags, United Kingdom flags, Russia flags, etc.

### Describe alternatives you have considered.

- Just having an only country flag: America flag
- Do this myself, but I think this can be a good opportunity for new contributors to join in

### Additional context

[https://en.wikipedia.org/wiki/Demographics_of_New_England#:~:text=New%20England%27s%20European%20American%20population,Portuguese%20descent%20exist%20as%20well.](https://en.wikipedia.org/wiki/Demographics_of_New_England#:~:text=New%20England%27s%20European%20American%20population,Portuguese%20descent%20exist%20as%20well.)

**Comment by NetSysFire** [comment]
Could be great for environmental story telling, too. Especially since there is basically a cold war going on between the US and China ingame.

**Comment by mlange-42** [comment]
We will definitely need flagpoles!
