### ISSUE TITLE
Hounds of Tindalos and teleglow

### ISSUE THREAD

**Issue by Blorkman** [CleverRaven/Cataclysm-DDA#61460]
### Is your feature request related to a problem? Please describe.

I find teleglow and Tindalos hounds to be very cool mechanics, but the later would need a bit of balancing. I know that extradimensionnal eldritch predators arent meant to be "balanced", but CDDA is a game and for the moment the Tindalos rift mechanic can be summarized as "you know about it and dont trigger it or you die". I don't mean that it should be easier, but it should not be an absolute death sentence as it is. Currently if you have 3 hours or more of accumulated teleglow, you are almost guaranteed to trigger a Tindalos rift, but some teleglow penalties dont trigger before 6 and 10 hours of teleglow ! Wich mean the player will basically never experience them.

### Solution you would like.

A solution i had in mind was simply making it so the fog doesnt spread with the hounds, maybe also making the hounds stronger to keep it extremly hard, but not impossible.

### Describe alternatives you have considered.

Another way would be to make tindalos rifts a 10+ hours of accumulated teleglow penalty, considering its basically the hardest challenge any survivor can currently encounter i think.

**Comment by John-Candlebury** [comment]
That's not the fog, but the "portal" that briefly opens during a corner teleport.

**Comment by Blorkman** [comment]
So you confirm that they dont spawn endllesly ? 
If so i take back the first idea i proposed, but the second one and the point i made still holds

**Comment by John-Candlebury** [comment]
No Im just making an observation that the fog is just cosmetic.

**Comment by Blorkman** [comment]
Ok anyway to make it clear and simple, my point is that since its the harshest penalty of teleglow, it should trigger later than the other ones.
