### ISSUE TITLE
There is no way to extinguishing you from fire

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61468]
### Describe the bug

There is no way to put of fire from your clothes. You cant pour water on yourself, you cant extinguishing it by fire extinguisher, you cant wallow in the sand/dirt, you cant sprinkle yourself with sand or earth, only way to put out fire is to step into the water tile, which are not neaby almost always
Fire is also too deadly and fast killing and equipment destroing. It can destroy clothes by few seconds

### Steps to reproduce

Make character
Spawn fire extinguisher and bottle of water
Burn some furniture/bushes
Equip few jumpsuits or other clothes
Step into fire
Try to put out fire from your clothes by using fire extinguisher or spreading water on yourself
See, that fire will kill you no matter what will you do

### Expected behavior

Ability to put out a fire from yourself by:
1) water
2) fire extinguisher
3) wallowing in the sand/dirt/on the floor
4) sprinkling yourself with sand or earth

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 01d15e7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NetSysFire** [comment]
>wallowing in the sand/dirt/on the floor

Waiting a turn should make the character do that already though

**Comment by Kywi001** [comment]
If you're still standing on the fire source when you try to extinguish yourself, it will take forever to extinguish yourself, but if you step out of the source and extinguish yourself, even just dropping a water in your tile should be enough to extinguish yourself, this is what I usually do when a laser turret sets me on fire

**Comment by ZhilkinSerg** [comment]
Step out if fire.

**Comment by Night-Pryanik** [comment]
Related: #52929.

**Comment by RenechCDDA** [comment]
![image](https://user-images.githubusercontent.com/84619419/202471880-8dba7db0-988f-4fd9-a9b6-155019a7c26b.png)

Echoing the above comments, it is possible to put yourself out and entering water will douse you.
