### ISSUE TITLE
basecamp logistics expansion

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#61469]
### Is your feature request related to a problem? Please describe.

it would improve the experience on city exploration, for instance by allowing you to know what books and components you already have and what you can do with them and given the computers hability it is not unrealistic

### Solution you would like.

the basecamp would have an expansion called "basecamp logistics" that would be accessible for you at long distance as long as you have any kind of computer device with you; it would show in the player's menu as "access storage", which would have a list of itens and a list of recipes that would be accessible according to the storage area, simmilar to that of the construction menu, except that it would not be associated with the actual construction function.

in order to build that expansion you would need computing and electronic habilities, a power source, a radio source and cables and the materials to build a computer device.

in order for the feature to be useful you would also need to request your NPC, by the basecamp menu, to "register itens". Which would take some time and maybe also have some moral penalty

something that could be further considered is bringing a basecamp mission of city exploration, which would list the total itens on the cleared areas (X tiles away from zombie activity) with name and quantity; from where you could request your NPC to bring some itens for you.

**Comment by jiornojiovanni** [comment]
Honestly this is a feature that can be extended also outside faction camps. IRL you could keep an inventory by using very simple software like a text editor (or excel If you are fancy).  Maybe you can define an area that your character keeps track of? And when you have a smartphone/laptop/e-ink tablet you can see the list.

It can also be made an activity to update the list of item or it can be done automatically (i kinda prefer this)
