### ISSUE TITLE
Items placed within a zone belonging to a faction no longer has the steal flag if you 'a'ctivate it 

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#61478]
### Describe the bug

I deployed a sleeping_bag in a loot_unsorted zone belonging to the faction, wasteland_scavengers. The blanket will show the steal flag and warn you if you try to take it, but the sleeping bag can be activated and carried away with no issues. 

### Steps to reproduce

1. Create a new piece of mapgen with the line '{ "item": "sleeping_bag", "x": 4, "y": 14, "chance": 100 }' under place_loot. 
2. Box that area in with { "type": "LOOT_UNSORTED", "faction": "wasteland_scavengers", "x": [ 3, 7 ], "y": [ 13, 17 ] } under place_zones. 
3. Go into game and 'a'ctivate the sleeping_bag. You will roll it and it no longer has steal flag. 

### Expected behavior

You shouldn't be able to interact/activate with the sleeping bag. And if you do, the steal flag should still be there. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 0.F-11766-g842db3755e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
The same as #61294?
