### ISSUE TITLE
Ammo loaded into magazines breaks gunsmith / banker.

### ISSUE THREAD

**Issue by KayDeeTee** [CleverRaven/Cataclysm-DDA#61477]
### Describe the bug

Attempting to convert 5.56 when loaded into a stanag magazine or .300BLK clip, gives an "You don't have a 5.56 NATO M855!" popup, then the NPC says "If you are seeing this I am bugged and confused. You should report this fact on the GitHub.", You can then select any ammo type including 5.56x45.

The ammo won't be taken from you, and when attempting to claim your trade in a day, the NPC will just say "The transaction is complete, here are your items.", won't give you anything, and won't reset back to accepting more trades, functionally softlocking the NPC permanently.

I assume this issue applies for ammo that isn't 5.56 but I didn't test them. 

### Steps to reproduce

1. Teleport to gunsmith
2. Spawn 7x Stanag 30-round magazines (30/30)
3. Attempt to do a transaction
4. Wait a day
5. Attempt to claim your bullets

### Expected behavior

Should probably take the bullets out of the magazines, instead of breaking.

### Screenshots

![image](https://user-images.githubusercontent.com/6253118/193940169-51109b1d-1e2a-48a3-a733-4908d9564a2e.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.2; Release: 20.2; Codename: uma; 
- Game Version: 1cdaee9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Kywi001** [comment]
You can even trade ammo without the actual ammo resulting in this error too
