### ISSUE TITLE
Add Bojutsu manual 

### ISSUE THREAD

**Issue by MaxD98** [CleverRaven/Cataclysm-DDA#61487]
### Is your feature request related to a problem? Please describe.

There's no book manual for Bojutsu, unlike any other martial art. If you search for Bojutsu in Hitchhiker's Guide you won't see the "Found in" section, so this means there's no way to learn Bojutsu through reading. You can't obtain it even through a pretty rare Close Quarters Battle CBM. Only "legal" way to learn Bojutsu is "Melee Training" hobby, which is really expensive (it's worth 6 points), and it's description don't show Bojutsu as avaible martial art. But you actually can pick Bojutsu and use this style through this hobby.

### Solution you would like.

Add the book manual for this martial art. I think some players will find this fighting style pretty usefull for it's dexterity-based block buff and and bash damage bonus.

### Describe alternatives you have considered.

Make Bojutsu exclusive for Close Quarters Battle CBM.

**Comment by TheShadowFerret** [comment]
>Its description don't show Bojutsu as available martial art.

This wasn't fixed 🤔
