### ISSUE TITLE
Add moar ASCII title arts

### ISSUE THREAD

**Issue by sonphantrung** [CleverRaven/Cataclysm-DDA#61494]
### Is your feature request related to a problem? Please describe.

I'm tired of seeing "Cataclysm: Dark Days Ahead" ASCII title on the screen

### Solution you would like.

Add moar titles (which rare odds), representing iconic figures of the game, like Foodperson, zombie hulk, moose, Dino Dave, Kevin, etc.

### Describe alternatives you have considered.

Continue to live with bland-looking titles, which only gets fancy when some holidays come (Halloween, Christmas, Easter Egg)

### Additional context

![image](https://user-images.githubusercontent.com/94152483/194241801-748ace25-7a7b-45cb-b5af-77502e45f296.png)

**Comment by ZhilkinSerg** [comment]
Just make a pull request with new title screens. There is no need to have an open issue for that.
