### ISSUE TITLE
Rigid outer eye/mouth items can be worn alongside helmets if the helmet has a visor

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#61495]
### Describe the bug

As title.

### Steps to reproduce

1. Wear a motorcycle, riot, or similar type of helmet.
2. Raise the helmet's visor (if not already raised)
3. Wear the rigid eye/mouth clothing (screenshot shows light amp goggles)
4. Lower the visor

### Expected behavior

Visor cannot be lowered while wearing a rigid item in a conflicting slot

### Screenshots

![image](https://user-images.githubusercontent.com/24522330/194258308-cc751282-a761-4573-99d3-cf2e3149fbca.png)
![image](https://user-images.githubusercontent.com/24522330/194258374-46cdd7df-244c-4341-8028-0b7f007f1c37.png)
![image](https://user-images.githubusercontent.com/24522330/194258420-dc62066a-e082-457b-92d9-600aacda053c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 3f63c44 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
It really depends on what these rigid items are. Glasses ought to be fine, but night/IR/AR/VR goggles that have a significant bulk ought to prevent the lowering of the visor on account of being in the way.
