### ISSUE TITLE
Lab stairs can spawns in closed off areas.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#6151]
The lab stair can go down into one of the barrack or prison ends. And the prisons do not have consoles that allow you to open up the locked door from the inside.

http://prntscr.com/2teem5

Related to: https://github.com/CleverRaven/Cataclysm-DDA/issues/6127
##

**Comment by Leland** [comment]
Closing this in favor of the master science lab issue #10958.
