### ISSUE TITLE
distribution_source::check_consistent_with test fails for map special house_21

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#61510]
### Describe the bug

```ERROR : src/mapgen.cpp:1290 [virtual void mapgen_value<std::__cxx11::basic_string<char> >::distribution_source::check_consistent_with(const mapgen_value::value_source &, const std::string &) const [Id = std::__cxx11::basic_string<char>]] inconsistent default value distributions for parameter exterior_wall_type in map special house_21 ([ t_brick_wall:6, t_rock_wall:3, t_wall_wood:3, t_drystone_wall:2, t_adobe_brick_wall:4, t_concrete_wall:4, ] vs [ t_brick_wall:6, t_rock_wall:3, t_wall_wood:3, t_concrete_wall:4, ])```
Slightly aligned:
`[ t_brick_wall:6, t_rock_wall:3, t_wall_wood:3, t_drystone_wall:2, t_adobe_brick_wall:4, t_concrete_wall:4, ]` vs
`[ t_brick_wall:6, t_rock_wall:3, t_wall_wood:3, t_concrete_wall:4, ]`

Likely related to https://github.com/CleverRaven/Cataclysm-DDA/pull/61430

Failed runs:
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/3198818202/jobs/5224582044#step:16:723
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/3200750530/jobs/5228014184#step:16:729
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/3200704700/jobs/5227926562#step:16:704

### Steps to reproduce

Doesn't seem it always reproduces, but fairly often in latest PRs

### Expected behavior

Tests don't fail

### Versions and configuration

Latest master

**Comment by mqrause** [comment]
It seems `house_hoarder_palette` also needs the adjustment the other palettes got.

**Comment by Maleclypse** [comment]
Super weird but every way I'm trying to fix it shows as already done?

**Comment by mqrause** [comment]
Oh yeah, my bad, I think I looked at old json. You already adjusted that one.

The actual culprit seems to be the Mythos mod which overrides `standard_domestic_palette` and `standard_domestic_palette_abandoned` with the old values.

**Comment by PatrikLundell** [comment]
Note to OP: This is a very clear example of why filling out the "Versions and configuration" section with the data the game allows you to capture to the clipboard is useful: That info lists all the mods used, which "latest master" as of some random point in the past doesn't, which saves on people's time when trying to reproduce and fix issues.

**Comment by mqrause** [comment]
Considering this is about CI failures, that doesn't really apply to this issue.
