### ISSUE TITLE
Merchant pockets

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#61530]
### Describe the bug

Merchant like the HUB, Refugee and Isolate have furniture an the items are taken or deposited here. But some others like Valhalla and Scrap don't and the offer is reject because "don't have appropriate pockets for that".
Its intended? If not I suggest check all merchant. 
- The cop that spawn in police station have only is personal items for sale, but she/he is surrounded by valuables. Not to mention is suicide behavior (if the NPC stay in place is perfectly safe except for hulks)
- Homeless are filthy rich :p and ask for items they sold.
- Cowboy merchant take my shotgun an give nothing? Also as nothing for sale.
I know how to add stuff to a list (I add the 25 magnetrons to the already rich homeless) but I don't know hot to make the items be deposited in furniture.
I know is not right to mention several bugs in a single report.

### Steps to reproduce

Try to sell something like a rifle to certain vendors.

### Expected behavior

Accept the offer normally.

### Versions and configuration

Win 7
Experimental cdda-windows-tiles-x64-msvc-2022-10-05-1937

### Additional context

I like boobs

**Comment by MNG-cataclysm** [comment]
PR #59805 will fix this for the scrap trader.

**Comment by KymasTuran** [comment]
> PR #59805 will fix this for the scrap trader.

Marvelous!
Can you spare a moment to tell me how you make the items go to the furniture instead of  inventory of the vendor? Just a hint, I try to learn reading the json file.

**Comment by Merikona** [comment]
You can do this by specifying zones. e.g. https://github.com/CleverRaven/Cataclysm-DDA/pull/59805/files#diff-ff656033e3362b00fb980e907669c0e2e0e4a4e0619ea6db78c243f2ce849b02R165
