### ISSUE TITLE
Strange hypovolemic shock bug.

### ISSUE THREAD

**Issue by Dignut** [CleverRaven/Cataclysm-DDA#61538]
### Describe the bug

I recently updated to build 2022-10-02-1703 and I've noticed that my character seems to now crash after achieving ANY tier of hypovolemic shock, this is a newly made char for the build that I've been playing on for a bit now. weird thing is I made a bunch of other characters and tested various things like disabling various recently added mods and those newer chars seemed to be ok weirdly enough, even with the same mod setup as the problem character, I was wondering if this was a known issue or a fatal fuckup in the char's save, the error is stated as an "arithmetical error" and is of the "signal" type.

### Steps to reproduce

1.Load save
2.Achieve hypovolemic shock
3.game crashes immediately.

### Expected behavior

Hypovolemic shock continues as normal without issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 01d15e7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Crow's Hairstles 2: Natural [hairmod2_natural],
    Bionic Professions [package_bionic_professions],
    Arcana and Magic Items [Arcana],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9738738/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9738739/debug.log)

**Comment by RenechCDDA** [comment]
Unable to reproduce. Looking over the log, it appears to be related to a body part. Of all the mods in your mod list, only magiclysm adds a body part (void eye), and its addition is newer than the version you are reporting the error in. Nonetheless I tried reproducing the error by inducing hypovolemic shock from that body part. No error occurred.

Please provide the save for this issue.
