### ISSUE TITLE
Equipment weight distribution

### ISSUE THREAD

**Issue by Dan1ss1mo** [CleverRaven/Cataclysm-DDA#61549]
### Is your feature request related to a problem? Please describe.

How much equipped items affect carry capasity of charecter should be affected by how well item weight is distributed across charecter body. Wearing 20 kg plate armor would be a lot easyer then wearing 20 kg in your backpack.

### Solution you would like.

I would really like to avoid solutins that would require adjustments to every single equipable in the game, so there are two that i came up with:
1) make it so that carry capasity is not affected by weight of equipped items at all, as there is already encumbrance system which discourage you from wearing to much heavy staff as well as hard restriction on how many items can be put on each layer. Insted weight and encubrence of the equpment would affect fatigue, and stamina cost. The effect should be adjusted by individual item weight relative to it encumbrance, as well as which body part that they occupy(gloves shouldn affect how fast you get tired as much as ballistic vest or somthing like that). So items with same weight but different encubrence would have differnt effect of how fast you charecter get tired by carring staff around(for example proper chest plate would have better weight distribition then the one made from metal sheet even if they have the same weight). Strength obviously should play role in that as vell.
2) Its rather simular, but instead of removing equipped items weight entirely add weight distribution modifier, which  would be automatically calculated based on parameters mentioned above and do not add any additional penalties(with the exeption of maybe reducing overall carry capasity a bit). Considering there is item weight multiplier for pockets, i asume this varians should be easyer to implement.

### Additional context

Nomad gear special effect could also be adjusted to work with this system, rather then just give you some bonus carry capacity

**Comment by Kywi001** [comment]
Removing the weight of the equipped gears is a huge no-no, it would cause some issues where players could abuse it.

While I do agree that some wearable items can be nitpicked into being easier to carry being worn than being backpacked but thats not a reason to do said suggestion.

Carry weight is how much stuffs you can carry.
Encumburance is how much you can move your body while wearing something on that part of your body.

Both aren't the same and is needed, if you're still gonna cry about the said system, you can always craft a foldable shopping cart.

**Comment by Dan1ss1mo** [comment]
> Removing the weight of the equipped gears is a huge no-no, it would cause some issues where players could abuse it.
> 
> While I do agree that some wearable items can be nitpicked into being easier to carry being worn than being backpacked but thats not a reason to do said suggestion.
> 
> Carry weight is how much stuffs you can carry. Encumburance is how much you can move your body while wearing something on that part of your body.
> 
> Both aren't the same and is needed, if you're still gonna cry about the said system, you can always craft a foldable shopping cart.

I'am fine with current system, but i think what i proposing make some sense. I understand that encumbrance and carry weight are separate things. My point is: distributing weight more evenly will allow you to carry staff with less effort(ore more staff with same effort) which is represented by carry capacity. Implementing it only to some item's thought may be good idea. The impact of this system on regular clothing would be minimal any way.
