### ISSUE TITLE
Cutting up makeshift bandages (crafted from 1 cotton patch) can be cut up to get multiple cotton patches

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#61566]
### Describe the bug

A player can create multiple cotton patches from a single cotton patch, as long as the player mentally thinks of it as a bandage before cutting it up.

### Steps to reproduce

1. Craft makeshift bandage using 1 cotton patch
2. "Cut up" the makeshift bandage
3. You will get usually get 11 to 14 cotton patches from what was once 1.

### Expected behavior

Makeshift bandages should not break the laws of conservation of mass. Should only get 1 cotton patch.

Maybe remove the ability to cut them up, instead being able to disassemble them to return the single cotton patch.

### Screenshots

![Screenshot (457)](https://user-images.githubusercontent.com/38295275/194749586-15ae0627-0665-4927-9966-1f03b9c8707a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 91310b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by actually-a-cat** [comment]
This is because cotton patches used to be larger (back when they were called rags)

I think the correct solution would be to craft makeshift bandages from cotton sheets instead, and align their size/weight with them (it's already kinda close)

**Comment by FlyingSpaceRhino** [comment]
I've found that this also happens with "antiseptic soaked rag", so this issue likely exists for other similar items as well.
![Screenshot (471)](https://user-images.githubusercontent.com/38295275/195259727-f492e1c4-2609-4376-92d6-2121db960ca7.png)

**Comment by LiramuIorin** [comment]
can do something about that too and update the pull request, if you want.

**Comment by strategineer** [comment]
Seems like this original issue has been resolved by https://github.com/CleverRaven/Cataclysm-DDA/pull/61992 specifically (https://github.com/CleverRaven/Cataclysm-DDA/pull/61992/files#diff-1c83fa5000d8e5c822831984469aaf9b1474d581da3e5752f70920524e42678e and https://github.com/CleverRaven/Cataclysm-DDA/pull/61992/files#diff-05b491d0da1a090113a035ee9106f0ab73b0206e63b457872f83fd66b7b0a235).

But it seems like rags are in a bit of a weird place right now https://github.com/CleverRaven/Cataclysm-DDA/pull/54256/files#diff-975fd9112243b1d868c6e2e244be9e1a1154ab1f0ded33c00b0d75b39c1b31a4R140
