### ISSUE TITLE
Cataclysm-DDA failed to build with "error C2015: too many characters in constant " with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [CleverRaven/Cataclysm-DDA#61567]
### Describe the bug

Cataclysm-DDA failed to build with "F:\Cataclysm-DDA\src\unicode.cpp(105,17): error C2015: too many characters in constant " with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?
**Error info:**
```
10>F:\Cataclysm-DDA\src\unicode.cpp(105,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(105,26): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(105,35): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(105,44): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(105,53): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(105,62): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(105,71): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(106,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(106,26): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(106,35): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(106,44): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(106,53): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(106,63): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(107,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(107,26): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(107,35): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(107,44): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(107,53): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(108,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(108,26): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(108,35): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(108,44): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(108,53): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(108,62): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(109,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(109,26): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(109,35): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(109,44): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(109,53): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(110,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(110,26): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(111,17): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(111,27): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
    10>F:\Cataclysm-DDA\src\unicode.cpp(111,36): error C2015: too many characters in constant [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]
```
**Error log:**
[Cataclysm-DDA_build_C2015.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9741282/Cataclysm-DDA_build_C2015.log)
**patch log**
[Cataclysm-DDA_ARM64EC.patch.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9741284/Cataclysm-DDA_ARM64EC.patch.log)

### Steps to reproduce

1. open x64 native tools command prompt for VS 2019
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\Cataclysm-DDA
4. git -C "F:\Cataclysm-DDA" apply f:\Cataclysm-DDA_ARM64EC.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
5. cd F:\vcpkg
6. bootstrap-vcpkg.bat 2>&1
7. vcpkg.exe install --recurse zlib sdl2 sdl2-ttf sdl2-image --triplet arm64-windows --clean-after-build 2>&1
8. F:\Cataclysm-DDA
9. mkdir build_arm64ec & cd build_arm64ec
10. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCURSES=OFF -DLOCALIZE=OFF -DTILES=1 -DBUILD_TESTING=OFF  -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows ..
11. set PATH=C:\tools\msys64\usr\bin;%PATH%
12. set _CL_=/permissive-
13. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release CataclysmDDA.sln /t:Rebuild

### Expected behavior

I expected build fine and does not error

### Versions and configuration

OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.19)

**Comment by ZhilkinSerg** [comment]
You may try to change single quotation marks to double quotations marks in `accented_characters` vector in `unicode.cpp`.

**Comment by YangYang129** [comment]
@ZhilkinSerg I changed single quotation marks to double quotations marks in `accented_characters` vector in `unicode.cpp`. This project failed to build with "error C2440: 'initializing': cannot convert from 'initializer list' to 'std::vector<std::pair<char32_t,std::set<char32_t,std::less<char32_t>,std::allocator<char32_t>>>,std::allocator<std::pair<char32_t,std::set<char32_t,std::less<char32_t>,std::allocator<char32_t>>>>>'"
![image](https://user-images.githubusercontent.com/86757616/194790574-a43752fc-3ed8-43df-aa1e-43fa73b0a1c7.png)

error info:
F:\Cataclysm-DDA\src\unicode.cpp(104,91): error C2440: 'initializing': cannot convert from 'initializer list' to 'std::vector<std::pair<char32_t,std::set<char32_t,std::less<char32_t>,std::allocator<char32_t>>>,std::allocator<std::pair<char32_t,std::set<char32_t,std::less<char32_t>,std::allocator<char32_t>>>>>' [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles-common.vcxproj]

**Comment by YangYang129** [comment]
@BrettDong I run `set _CL_=/utf-8 /permissive- ` and rebuild, display following error, Could you please help look at this issue?
11>CVTRES : fatal error CVT1100: duplicate resource.  type:MANIFEST, name:1, language:0x0409 [F:\Cataclysm-DDA\build_arm64ecaa\src\cataclysm-tiles.vcxproj]
    11>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt [F:\Cataclysm-DDA\build_arm64ecaa\src\cataclysm-tiles.vcxproj]

**Error log:**
[Cataclysm-DDA_rebuild_linkerror.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9743754/Cataclysm-DDA_rebuild_linkerror.log)

**Comment by ZhilkinSerg** [comment]
Try to disable incremental linking

https://stackoverflow.com/questions/12267158/failure-during-conversion-to-coff-file-invalid-or-corrupt

**Comment by YangYang129** [comment]
@ZhilkinSerg I run `set _LINK_=/incremental:no` and rebuild, these two errors still display:
 CVTRES : fatal error CVT1100: duplicate resource.  type:MANIFEST, name:1, language:0x0409 [F:\Cataclysm-DDA\build_arm64ecaa\src\cataclysm-tiles.vcxproj]
         LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt [F:\Cataclysm-DDA\build_arm64ecaa\src\cataclysm-tiles.vcxproj]
