### ISSUE TITLE
Graffiti doesn't cull/adjust when walls retract

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#61561]
### Describe the bug

Graffiti sprites don't respond correctly to retracting walls for isometric tilesets, leading to graffiti that appears to be inside of a wall and/or floating.

### Steps to reproduce

 1. Use "Ultica_iso" tileset
 2. Go to a wall tile that has graffiti
 3. Either have auto-retracting walls enabled and get close enough, or manually bind the wall retraction affect to a key and toggle it.
 4. Floating art

### Expected behavior

Graffiti culls as expected if it is inside of a wall and/or the wall has moved/retracted.

### Screenshots

_Inner-wall graffiti_
![ultiso_part](https://user-images.githubusercontent.com/32048635/194734223-e06d29d3-9f21-4438-af17-88e4e591d443.png)
_Floating graffiti_
![ultiso_full](https://user-images.githubusercontent.com/32048635/194734221-7a702177-0297-4cfe-bb76-e1f82728bb4e.png)
_Ultica for reference_
![ultica](https://user-images.githubusercontent.com/32048635/194734219-a3216142-2d30-4ceb-856d-d356cb850c98.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 91310b2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mlange-42** [comment]
Can confirm that. Intentionally did not make them retract as it would currently cause floor graffitis to sink into the ground.

Generally, retraction turned out to be a suboptimal solution and we should probably replace it by partial transparency toggle or transition.

**Comment by mlange-42** [comment]
Also, we currently need the "inner wall" part as we can't distinguish on what side of the wall the graffiti should display. But at least, we can distinguish between wall and floor now.
