### ISSUE TITLE
Better Accessibility for Pockets

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#61568]
### Is your feature request related to a problem? Please describe.

When I unwield or pick up something, it doesn't tell me which pocket the item will be stored. It's really inconvenient when I want to store an item into a specific container.

ex) I have a leather backpack and a hoodie. I want to un`w`ield a combat knife but I don't know which pocket will be used. It'll just say 'Store in inventory'.
ex2) I want to pick up a pistol into a messanger bag, but it goes into a holster. (This could be solved by touching the pocket settings, but I still don't know where the pistol will be stored.)

### Solution you would like.

Ability to store an item (or items) into a specific non-holster pocket when picking up or unwielding.

Indicator that shows where the item(s) will be stored when picking up.

### Additional context

PLEASE STOP HOOKING AN MRE PACKAGE ON MY CARABINER STRAP

**Comment by sonphantrung** [comment]
You can do 'insert item into container' by following these steps:
1. In the 'i'nventory screen, select a container
2. Select insert
3. Now you see insert item into pocket, you now just do insert like what u do when picking up items

**Comment by NotSeawhite** [comment]
I forgot to mention 'insert' too, it takes a long time scrolling to manually insert items

**Comment by sonphantrung** [comment]
Actually, you can filter items by using the `/` key, just like item pickup

**Comment by NotSeawhite** [comment]
Android CDDA refuses to accept typing in any language other than English. It won't let me use item filters and auto pickups :(
