### ISSUE TITLE
Sorting zones remove items out of active "cleaners"

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#61583]
### Describe the bug

If you have a loaded and activated "cleaners", such as washing machines or autoclaves, the auto-sort will RIP ITEMS OUT OF THEM and making the items NOT cleaned.

### Steps to reproduce

1. Any washing machines will do, but for sake of simplicity, just spawn a luxury RV. Make sure the battery is loaded, and one of the tank has water.
2. Set an unsorted loot zone over the washing machine, and a loot zone that would include whatever you're trying to clean with the washing machine.
3. Put something inside the washing machine to clean.
4. Use O menu's sort items.
5. You'll see the items got ripped out of the containers.

### Expected behavior

considering we NORMALLY cannot just reach items inside those without deactivating them first, why does the auto sort can, and break things at that?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 349262c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by NetSysFire** [comment]
Feels like the active appliance might be missing the `SEALED` flag, but haven't tested that. A way to test that would be to place a sealed crate (or similar) inside a sorting zone and see if the items get removed, too.
