### ISSUE TITLE
Training dummy installation requirements 

### ISSUE THREAD

**Issue by Rllaman** [CleverRaven/Cataclysm-DDA#61596]
### Is your feature request related to a problem? Please describe.

The items "training dummy" and "armored training dummy" both require an item with digging 2 to install, representing burying the bottom of the dummy in a small pit.

However, they can be installed even on surfaces where this doesn't make sense, such as concrete, carpet, or the second floor of a building.

### Solution you would like.

There are a few reasonable options

1. Remove the ability to install the dummy on hard terrain.
2. Remove the shovel from the requirement. Possibly add additional boards and nails to the training dummy recipie to represent building a base for it to stand on.
3. Create new items/furniture to represent both training dummies that need to be buried in the ground, and ones that can be set up anywhere.

### Describe alternatives you have considered.

Option 2 from above seems like the simplest to implement. Boards and nails are incredibly easy to come by, so adding a few more wouldn't really affect gameplay.

Someone might argue that a wooden dummy actually able to withstand blows from combat training without a solid anchor might be harder to build, and could require more fabrication skill or time than a simpler one that has the stability of being buried in the ground. However, such a dummy should certainly be possible to create.

**Comment by Numbuh474** [comment]
They can also be placed inside walls, which has been useful for my space-limited mini base but probably isn't an intentional feature.
