### ISSUE TITLE
Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#61597]
### Describe the bug

Got this error:
```
 DEBUG    : Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.

 FUNCTION : trim_by_length
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp
 LINE     : 275
 VERSION  : 737dc71
```
When I was trading with hub01 and scrolled down to the next page of my inventory to trade

### Steps to reproduce

1. Go to hub01 trader
2. tab to your inventory selection
3. scroll down to the next page

### Expected behavior

Scroll to the next page without showing the error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.978 (21H2)
- Game Version: 737dc71 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Possibly related to #61591?

**Comment by ZeroInternalReflection** [comment]
I'm guessing that what's happening here is that:
1. The trade UI is trying to display two columns, one with the name of the item to be traded, and the other with the price/discussion of why the person you're trading with isn't interested in buying/selling
2. It attempts to trim both to fit, which is quite tricky for long item names and small terminal sizes.  It seems to lean towards keeping as much of the item name as possible
3. Some combination of item names and terminal size results in the trade ui having 0 space available for the "hey the trader isn't interested in this" message
4. Trim_by_length then gives a warning telling us that this particular string is never going to print.  The screen _should_ still be usable if you `I`gnore the warning, though `Spacebar` probably isn't going to get you anywhere.

There are a couple of things that would help in testing this out and finding a fix:
a. Does your config/debug.log have a stack trace for this error?
b. What terminal size are you using?  I'm guessing it's smallish (e.g. 80x24)
c. Could you post a screenshot of your `i`nventory?  Presumably there's an item there where the name is just the right length to confuse the trade ui.

**Comment by snipercup** [comment]
A. This is the part of my debug.log:
```
13:59:08.612 ERROR GAME : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\do_turn.cpp:414: game:monmove: zombie soldier can't move to its location!  (15:58:0), pavement
14:24:39.709 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:04.122 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:06.066 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:06.611 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:07.018 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:07.354 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:08.091 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:09.763 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:10.588 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:11.109 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:11.292 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:12.142 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:12.516 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:12.747 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:12.908 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:13.108 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:13.301 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:13.667 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:14.036 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:14.429 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:14.804 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:15.325 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
14:25:15.825 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
[ Previous repeated 6 times ]
14:25:16.056 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp:275 [trim_by_length] Unable to trim string 'Hub 01 will not buy back their own gear' to width 0.  Returning empty string.
15:17:28.597 ERROR SDL : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\sdlsound.cpp:713: Failed to play sound effect: Tried to play a chunk with a bad frame id:environment variant:daytime season:spring
15:17:28.657 ERROR SDL : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\sdlsound.cpp:713: Failed to play sound effect: Tried to play a chunk with a bad frame id:environment variant:daytime season:spring
```
B. my terminal size:
![image](https://user-images.githubusercontent.com/50166150/194906789-84720f5e-7166-42e3-bb1e-9517370b1e04.png)

C. This is my current inventory. I don't know what I had when I started the trade but if it was one of my favorited items it was definitely there
![image](https://user-images.githubusercontent.com/50166150/194906990-9d169896-a0bd-49fa-91e7-2e34105f2375.png)
![image](https://user-images.githubusercontent.com/50166150/194907078-3b6ca141-7ad8-4305-b75d-5da392f9d182.png)
![image](https://user-images.githubusercontent.com/50166150/194907126-a1b2ef4b-1af3-4124-9c35-3f0bdc14167e.png)

**Comment by ZeroInternalReflection** [comment]
The "Hub 01 modular defense system" certainly seems like a likely candidate for the particular string trimming failure you hit.  It's certainly a long enough item name to interfere with things, even at your terminal size.

However, this isn't too difficult to replicate.  I've got a fix in progress that prevents the error when looking at Smokes' equipment on a narrow window.

About to produce a debugmsg (Note the odd trimming of the refusal message for the duffel bag):
![Before--Improper_trimming](https://user-images.githubusercontent.com/89038572/195481907-6ac74191-624a-4014-bd10-7c82a7f395a4.png)
After tweaks (at minimum terminal width):
![After--Proper_trimming](https://user-images.githubusercontent.com/89038572/195481963-12b1a15b-8ac0-410c-9ec0-4293a0b02a90.png)

Since the change is deep in inventory_selector, which gets used on a lot of different screens, I'm still testing to make sure it doesn't break anywhere else.

I'm also thinking that there should be a popup on attempting to select an untradeable item to tell you their full reasons for refusal.  Otherwise, people on small screens might not be able to figure out why they can't trade something.
