### ISSUE TITLE
Game dont load. Its only me?

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#61609]
### Describe the bug

Game dont load.
(continued from above) ERROR : src/main_menu.cpp:999 [bool main_menu::load_game(const string&, const save_t&)] Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

### Steps to reproduce

Download last version. Load save from anterior version.

### Expected behavior

Load normally.

### Versions and configuration

Win 7
cdda-windows-tiles-x64-2022-10-11-0249

**Comment by Zireael07** [comment]
Looks like a reoccurrence of a recent issue. Are you on a locale that uses commas for decimal place instead of a dot?

**Comment by KymasTuran** [comment]
I play in english but windows is in spanish. And yes, we use 1.000,10

**Comment by Zireael07** [comment]
@akrieger: Looks like #61095 is occurring again (the reporter is on today's build)

**Comment by akrieger** [comment]
Windows 7 is known to be broken with the non-msvc modes. I tried multiple workarounds with the other reporter including reinstalling the latest visual studio redistributable. I don't know if it's something more fundamentally broken in the msvcrt or just a 'compatibility' behavior, but the localized parsers ignore the locale specifier. However, the -msvc- builds work, so I encourage people to switch to those.

**Comment by KymasTuran** [comment]
> Based off this report and followup debugging I did with one of the earlier reporters, Windows 7 is broken with the non-msvc modes. I tried multiple workarounds with the other reporter including reinstalling the latest visual studio redistributable. I don't know if it's something more fundamentally broken in the msvcrt or just a 'compatibility' behavior, but the localized parsers seemingly ignore the C locale. However, the -msvc- builds work, so I encourage people to switch to those.
> 
> If we really want the non-msvc builds to work with windows 7 we would have to substitute the localized number parser with a hand rolled implementation, which I could pull out of the old json implementation. Or I can see if it's something weird with function local static initializers. I just prefer to minimize changes to third party code as much as possible.

Forgive my ignorance. Question:
This mean I need the msvc version and that's all?

**Comment by akrieger** [comment]
Yes, please try the -msvc- build. It should work, and you can keep using it. The saves are compatible between versions, it's the same game just built differently.

**Comment by KymasTuran** [comment]
> No worries, sorry my answer was overly technical :) Yes, please try the -msvc- build. It should work, and you can keep using it. The saves are compatible between versions, it's the same game just built differently.

It work.
Thank you. 
Hope this hub help someone else with the same problem.
I did a double report (https://github.com/CleverRaven/Cataclysm-DDA/issues/61410) need delete one?

**Comment by Zireael07** [comment]
@KymasTuran That duplicate is already closed, issues can't be deleted on GitHub

**Comment by mqrause** [comment]
> If we really want the non-msvc builds to work with windows 7 we would have to substitute the localized number parser with a hand rolled implementation, which I could pull out of the old json implementation. Or I can see if it's something weird with function local static initializers. I just prefer to minimize changes to third party code as much as possible.

I don't think it's worth it to implement a custom solution to support an operating system that hit EOL almost 3 years ago.
