### ISSUE TITLE
ma_buff source tracking

### ISSUE THREAD

**Issue by nopenoperson** [CleverRaven/Cataclysm-DDA#61608]
### Describe the bug

if you try to replace stuff in martialarts.json with a mod you get stuff like this:
`DEBUG    : Error: buff_aikido_static1 (class ma_buff) has two definitions from the same source ()!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : 1cdaee9`

### Steps to reproduce

make a mod, try to replace stuff in martialarts.json with a mod 

### Expected behavior

i expect json files to be moddable 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362.1256 (1903)
- Game Version: 1cdaee9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
]

### Additional context

techniques.json seems to work fine as long as you avoid trying to replace"tec_debug_eoc_demo"

**Comment by PatrikLundell** [comment]
It seems support for mod overrides isn't universal. I've failed to override construction recipe group entries as well (ended up making an Innawood bulletin board entry addition since trying to override the bulletin board entry resulted in a duplication complaint.
