### ISSUE TITLE
Performance issues with lots of clothing

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#61618]
### Describe the bug

When you have lots of clothes in one area and press W to wear them, it takes some time for the screen to show.

### Steps to reproduce

1. Spawn 10 000 monocles 
2. Press W

### Expected behavior

I expect to be able to select which one of my 10 000 monocles to wear today be accomplished in a reasonable time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: b3c2d3b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[hello debugger!.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9758929/hello.debugger.zip)

**Comment by Ezrashaw** [comment]
Tried this on the latest experimental (note OP was from August). Spawning 10,000 monocles takes ~10 seconds (for me) and then opening the wear menu takes 1/2 a second. Putting on the monocle is instant.

**Comment by anothersimulacrum** [comment]
Profile:
Fair amount of vector allocation/deallocation.
![Screenshot from 2022-10-12 14-34-39](https://user-images.githubusercontent.com/42699974/195421437-e43c67cc-a3da-4868-8f0f-dcb10f521383.png)
