### ISSUE TITLE
mon_null from nested mongroups spawns invisible "human" enemies

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#61622]
### Describe the bug

When explicitly spawing `mon_null` from a nested monstergroup called via `age_grow` instead of not spawning it spawns an invisible, immobile "human" enemy that shows up in the compass.

### Steps to reproduce

1. Set up a monster growing up into a nested mongroup with `mon_null` as an entry (or checkout my `meat_cocoon` branch)
2. Trigger a growup
3. Behold invisible humans littering the landscape
4. (optional) Add `mon_null` to any normal mongroup and behold the humans not spawning

### Expected behavior

NULL_ID not spawning anything. 

### Versions and configuration

On commit `cd02b91a17023608f98f698965bbcfbafb2abb22`

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 0.F-11738-gac1cc169a1-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Standard combat test suite [standard_combat_test]
]

**Comment by dseguin** [comment]
Seems to be an easy fix:

```diff
diff --git a/src/monster.cpp b/src/monster.cpp
index cb156c90e4..d7d4b0ff38 100644
--- a/src/monster.cpp
+++ b/src/monster.cpp
@@ -411,7 +411,7 @@ void monster::try_upgrade( bool pin_time )
             } else {
                 new_type = MonsterGroupManager::GetRandomMonsterFromGroup( type->upgrade_group );
             }
-            if( !new_type.is_empty() ) {
+            if( new_type ) {
                 poly( new_type );
             }
         }
```

That'll prevent monsters from upgrading into `mon_null`

**Comment by Venera3** [comment]
Cheers, I'll check that later today!

**Comment by Venera3** [comment]
Well I get `invalid monster id ""` debugmessages and *corpses* of humans, so that's progress!

**Comment by dseguin** [comment]
Oh, I think I see what's going on. Try this:

```diff
diff --git a/src/monster.cpp b/src/monster.cpp
index cb156c90e4..75625c9904 100644
--- a/src/monster.cpp
+++ b/src/monster.cpp
@@ -380,10 +380,11 @@ void monster::try_upgrade( bool pin_time )
             return;
         }
 
+        mtype_id old_type = type->id;
         if( type->upgrade_into ) {
             poly( type->upgrade_into );
         } else {
-            mtype_id new_type;
+            mtype_id new_type = mtype_id::NULL_ID();
             if( type->upgrade_multi_range ) {
                 bool ret_default = false;
                 std::vector<MonsterGroupResult> res = MonsterGroupManager::GetResultFromGroup(
@@ -411,7 +412,7 @@ void monster::try_upgrade( bool pin_time )
             } else {
                 new_type = MonsterGroupManager::GetRandomMonsterFromGroup( type->upgrade_group );
             }
-            if( !new_type.is_empty() ) {
+            if( new_type ) {
                 poly( new_type );
             }
         }
@@ -422,8 +423,8 @@ void monster::try_upgrade( bool pin_time )
         }
 
         const int next_upgrade = next_upgrade_time();
-        if( next_upgrade < 0 ) {
-            // hit never_upgrade
+        if( next_upgrade < 0 || old_type == type->id ) {
+            // hit never_upgrade, or hit mon_null
             return;
         }
         upgrade_time += next_upgrade;
```

**Comment by Venera3** [comment]
No humans, but the cocoons stick around on unsuccessful growup (and they spawned some critters at least once after an unsuccessful growup, still sticking around somehow).

**Comment by dseguin** [comment]
Ah, I was confused about the desired behaviour. I'll take care of this one.
