### ISSUE TITLE
Mutation armor balance; epicuticle vs phelloderm

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61624]
### Is your feature request related to a problem? Please describe.

Balance of mutation armors is pretty whacky. One one end we have Epicuticle which absolutely insane, occupying PERSONAL and providing 7.5/5/2.5 (3mm arthropod_leather) defense at 100% coverage all for 1 encumbrance *and* it has perfect breathability. On the other hand is the utterly garbage Phelloderm providing 2.5 defense (2.5mm veggy matter) across the board on PERSONAL layer for *5* encumbrance, literally between 5-15x worse defense:encumbrance than epicuticle depending on damage type with no breathability whatsoever. Somewhere in the middle is Light Fur with 4/2.5/2 (2mm fur) for 2 encumbrance, high warmth and low breathability, and it occupies the SKINTIGHT layer unlike the other two, so it will conflict. Balance of other fur types is wildly inconsistent too.
Finally there is my pending PR #60505, where integrated scales would fall somewhere between fur and epicuticle (obviously way worse than the latter) but may also be too powerful depending on our present intended balance.

### Solution you would like.

How strong exactly should any given mutation armor be? I imagine they should be more efficient and covering than a typical suit of armor, and it's OK for a particular mutation line to have "better" armor than one of its neighbors, but as is the balance is so far out of whack that there's no way this is right.

**Comment by fairyarmadillo** [comment]
Shouldn't all integrated armor have 100% breathability, since it's literally your skin?

Epicuticle could simply be made thinner and phelloderm thicker. Epicuticle is supposed to just be a normal skin layer strengthened by the addition of chitin, not a hard outer shell like the later bug mutations.

**Comment by Venera3** [comment]
Mutation armor should get to be pretty strong, especially since the limb changes will probably make armoring yourself pretty debilitating. That said, for properly off-phenotype stuff (Scales, Chitin, Bark/Phelloderm) I'd lock the complete skin replacements consistently behind thresholds and add pre-thresh precursor "patchy" variations - confering the same armor with 20/30% coverage, potentially also being uncomfortable.

Sweating I think should be disabled for most, but I haven't looked into that part of code to see if it's more actionable to add it as a trait field ("Insect/Spider/Lizard Metabolism" as a master trait for all their adjustments), per armor or per limb.

**Comment by anoobindisguise** [comment]
> Mutation armor should get to be pretty strong, especially since the limb changes will probably make armoring yourself pretty debilitating. That said, for properly off-phenotype stuff (Scales, Chitin, Bark/Phelloderm) I'd lock the complete skin replacements consistently behind thresholds and add pre-thresh precursor "patchy" variations - confering the same armor with 20/30% coverage, potentially also being uncomfortable.
> 
> Sweating I think should be disabled for most, but I haven't looked into that part of code to see if it's more actionable to add it as a trait field ("Insect/Spider/Lizard Metabolism" as a master trait for all their adjustments), per armor or per limb.

Post threshing will be a pretty dramatic balance shift, but I assume it will be part of a broader effort to really lock all the good stuff in a given tree behind its threshold. I assume you can become furry without post thresholding since mammal->mammal is a lot "easier" than mammal->arthropod or mammal->plant... could a furry survivor still sweat, poorly? Or do they have to start panting to cool off instead?

**Comment by Venera3** [comment]
Yeah, fur and furlike stuff should be lower level, and for e.g. Chimera I have no problems with the armor being frontloaded to hammer the "you're pureeing your phenotype" point home.

Panting would be a nice function, yeah. Muzzles will get limbed as mouth replacements, and another added issue to gas masks would be welcome - again, I'll need to look into it if 0% breathability fur and a sweat_score or whatever on the muzzle would be actionable.
