### ISSUE TITLE
Wielded weapons are damaged despite using "Force unarmed" style

### ISSUE THREAD

**Issue by Joanakor** [CleverRaven/Cataclysm-DDA#61639]
### Describe the bug

Wielded weapons are damaged despite using "Force unarmed" style. I usually use this mode to smash furniture while holding a flimsy weapon, but after another "shoulder-check" my spear got damaged.

### Steps to reproduce

1. Wield a weapon (best seen with flimsy)
2. Switch to "Force unarmed" style
3. Beat a wall until weapon is damaged

### Expected behavior

Weapons do not get damaged with "Force unarmed" style.

### Screenshots

![cataclysm-tiles_WCgKkHzFeJ](https://user-images.githubusercontent.com/30211338/195382509-fd554240-5987-4f22-b6ed-5522ced5164c.png)
![cataclysm-tiles_GUFkBY5m3D](https://user-images.githubusercontent.com/30211338/195382501-ea1d00af-4aab-452d-bbc5-52234932b9ed.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 26e35a7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Joanakor** [comment]
I feel like these bug is connected to mine - https://github.com/CleverRaven/Cataclysm-DDA/issues/54117

**Comment by Night-Pryanik** [comment]
Fixed by #61765.
