### ISSUE TITLE
for some reason zombie appeared infront of my character out of nowhere and then there is a horde of zombie in a already cleared mansion

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61636]
### Describe the bug

![image](https://user-images.githubusercontent.com/63102395/195311349-30ae7091-f6f9-4227-b97a-59dd1845940b.png)

### Steps to reproduce

1. either because of playing 2 different experimental version on a world
2. or maybe leave the game by alt f4 then rejoin and it appeared

### Expected behavior

no zombie infront and no horde in a already somewhat cleared mansion

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9763770/debug.log)

**Comment by Zireael07** [comment]
Do you play with hordes on?

**Comment by PatrikLundell** [comment]
The posted error message is, unfortunately, not that uncommon. It can be generated when new monsters are to be spawned, but the location targeted is occupied already. Some monsters can spawn new ones, and the location intended for a spawning monster may already be occupied by something else. Some monsters can also spawn new monsters on "death" with the same risk of errors.
