### ISSUE TITLE
A long-sleeved shirt conflicts with a bra

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#61634]
### Describe the bug

Maybe I misinterpret what a long-sleeved shirt is but I did not expect it to conflict with a bra. Maybe the shirt belongs on the normal layer instead of the close to skin layer?

![image](https://user-images.githubusercontent.com/52621858/195264411-3c2b5627-470a-43a7-88e1-c839cc11676a.png)
![image](https://user-images.githubusercontent.com/52621858/195264449-ddea276d-6c83-4832-931e-33cf87b8b594.png)

### Steps to reproduce

1. wear a long-sleeved shirt and a sports bra
2. press +

### Expected behavior

No conflict between underwear and clothing it is often worn under.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: 87d0378 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment]
bigger issue is that a lack of benefit and better options for close to skin pretty much means going commando is the optimal way to play in every playthrough, making bras and underwear pretty much only good for raw materials.
