### ISSUE TITLE
small space heaters are shamelessly good

### ISSUE THREAD

**Issue by harmonickolobok** [CleverRaven/Cataclysm-DDA#61630]
### Describe the bug

"small space heater"(all 3 versions - vehicle, appliance and item) provides A LOT more "fd_hot_air2" fields than a "large space heater", but consumes half as much electricity.
This is probably because of difference in emissions generated by them:

Large space heater's emission:
{
  "id": "emit_heater_vehicle",
  "type": "emit",
  "field": "fd_hot_air2",
  "intensity": 3,
  "qty": 3,
  "chance": 100
},

Small space heater's emission:
{
  "id": "emit_hot_air2_stream",
  "type": "emit",
  "field": "fd_hot_air2",
  "intensity": 3,
  "qty": 50
},
This translates to 50 copies of "fd_hot_air2" with intensity 3 vs 3 copies for large space heater.

It uses the same emission as "metal grate" furniture with "id": "f_vent_hot_air2_stream":
  {
    "type": "furniture",
    "id": "f_vent_hot_air2_stream",
    "description": "This is a metal vent, you can feel hot air seeping out of it.",
    "copy-from": "f_vent_cold_air2_stream",
    "symbol": "~",
    "color": "red",
    "emissions": [ "emit_hot_air2_stream" ]
  },

### Steps to reproduce

1. In one room use "Place Large Battery" from construction menu
2. In the same room use "Place Large Heater" from construction menu to place large heater near large battery
3. In another room use "Place Large Battery" from construction menu 
4. In the same room from step 3. use "Place Small Heater" from construction menu to place small heater near large battery
5. Activate heater in the first room and check number of "hot air 2" fields spreading in this room after 1 second of heater's work
6. Activate heater in the second room and check number of "hot air 2" fields spreading in this room after 1 second of heater's work
7. Compare

### Expected behavior

I expected large space heater to be more effective in heating the room than small space heater(i.e. large space heater generating more "hot air 2" fields)

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental, cdda-windows-tiles-sounds-x64-msvc-2022-09-14-0616
- Graphic version: Tiles
- Ingame language: English
- Mods loaded: "Dark Days Ahead", "Disable NPC Needs", "No Fungal Growth", "Bionic Professions", "Blaze Industries", "Stats Through Kills"

**Comment by AoifeWM** [comment]
It seems like maybe the intention was for the small space heater to read `"qty": 3, "chance": 50` instead of `"qty": 50`? that would give it the same efficiency as the large one in terms of electricity:fd_hot_air2 unless `chance` does something different than expected.

**Comment by harmonickolobok** [comment]
Please don't close the issue^_^
I think it can be fixed by creating a new emission in json that would be about half as effective as emission for the large space heater
