### ISSUE TITLE
Zombies in the back bay of the evac center will join overmap hordes.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#61648]
### Describe the bug

Zombies in the back bay of the evac center will join overmap hordes.

### Steps to reproduce

1. Create a world with wandering hordes turned on.
2. Go near the evac center. (I got this to happen by approaching it from the back and moving around the building to the side opposite the bay with zombies.
3. Leave the area and make some noise.
4. Observe the horde

### Expected behavior

These zombies would not join an overmap horde and potentially break a quest.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: cd5924e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Portal Storms [Fewer_Portal_Storms],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

I suspect this isn't really worth fixing.

**Comment by KymasTuran** [comment]
Correct me if I m wrong but as far I know the Z you need to wipe to clear the quest is generated by the quest. This mean the horde feature can be used to lure the Z and later kill just one?

**Comment by Inglonias** [comment]
That does make sense. Hmm.

Like I said, I doubt this is worth actually fixing.
