### ISSUE TITLE
Inconsistent trading and inventory handling

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61642]
### Describe the bug

I'm foraging and harvesting stuff, and try to offload the items collected to my companion. The weird think is that not all of my items are shown for trade, although I've so far not detected any case of my companion not showing any items.
I've not set up any kinds of rules for hiding, pocket preferences, etc. so that shouldn't come into play, especially since the hidden object can show up a short while later. It's also not a case of mismatching carrying capacity, since both my character and my companion are restricted to what fits in a straw basket (starting Innawood equipment, with a character made one for the companion).

The other weird thing that may or may not be related is that the carrying capacity varies for no apparent reason. Usually I can carry 3 standard rocks in the basket, but sometimes a fourth one, and most of the time I can carry 4 lumps of clay in it, but sometimes 5 or even 6.

### Steps to reproduce

1. Start with a character and a companion that both are restricted to a straw basket for carrying inventory items. However, my character is usually also wearing a full small water skin that's never been shown to contain any of the carried items.
2. Forage stuff and fill up the inventory.
3. Bring up the trade screen to hand the collected items over to the companion and check to see whether all items collected are available for trade. If they are, retry (e.g. after handing what you can over to the companion, continue to forage, and then return to base to drop off everything before trying again).

### Expected behavior

I should be able to hand everything collected over to a companion provided the companion has exactly the same inventory capability (and isn't incredibly weak, unable to carry the items).

### Screenshots

My inventory:
![Screenshot (263)](https://user-images.githubusercontent.com/22739822/195407222-87b612e2-dfbd-45da-b440-b698416f7a9e.png)

Trying to offload the items. Note that only the food items are available this time, although that can vary so only some food items are visible, some non food items are available as well, all the way to everything being available:
![Screenshot (264)](https://user-images.githubusercontent.com/22739822/195407327-c8587bdc-c644-420d-82c3-975cd2e59fbd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 64e17c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]
+ "mod" to disable portal storms
+ Bare bones basecamp addition of recipes for steel from bog iron and plant thread from plants.

### Additional context

Another weird behavior is that the ability to carry "twohanded" items is inconsistent. The basket usually blocks the ability to carry such items, but occasionally does not.

**Comment by EIIKaO** [comment]
> I'm foraging and harvesting stuff, and try to offload the items collected to my companion. The weird think is that not all of my items are shown for trade, although I've so far not detected any case of my companion not showing any items.

I checked the code, Since I have seen the code in this area before.
The conditions for items to appear in the trade are as follows.
https://github.com/CleverRaven/Cataclysm-DDA/blob/cd5924e68ef7e3e203cf17533cf45a06f7209889/src/trade_ui.cpp#L51-L56

After testing in-game further, it seems that some items obtained by gathering from the bushes do not have a faction value. In other words, the faction of the item is not belongs your faction ( does not meet the condition `loc->is_owned_by( _u )` ) and therefore those items do not appear on the trade screen. This seems to affect items that have been handled by `iexamine_helper::handle_harvest`

If you generate those items ( wild herb or mushroom ) in the debug menu, the faction is set and they will appear on the trade screen.

The suspected cause was briefly reported.

**Comment by EIIKaO** [comment]
Laugh at me.
This is most likely caused by the PR I created ( #60961, apart from the part I wrote above ).
I will report back when I can confirm.

**Comment by PatrikLundell** [comment]
I tried to get any of the various debug selections to display item info, but didn't find anything. However, your wielding work around did "convert" my mugwort and dogbane forage catches into being possible to trade. Weirdly enough, foraging plant matter isn't always hidden, but it is most of the time, I think.
Conversely, fruit/berries and other stuff that is placed directly into the player inventory is usually, but not always available for trade.

Happy to see you think you're onto something (and hoping the above may at least not muddy the waters).
