### ISSUE TITLE
Rubik emotes about hearing his own robots

### ISSUE THREAD

**Issue by Veskaida** [CleverRaven/Cataclysm-DDA#61655]
### Describe the bug

Rubik will periodically emote "Huh? I think I just heard heavy thuds.." upon hearing the sounds of his various friendly robots walking around the area.

### Steps to reproduce

1. Stand near Rubik
2. Pass time until one of the robotic friendly robotic creatures moves, outside of Rubik's line of sight.
3. Rubik will emote "Huh? I think I just heard heavy thuds.."

### Expected behavior

Rubik probably should not say anything when his own robots move around the area, even if he cannot see them.

### Screenshots

![23123](https://user-images.githubusercontent.com/115378524/195514661-0e8c0bda-0bce-4d58-baf7-48d93e7105e5.png)

### Versions and configuration

Windows 10
CDDA ver. 06962c4
English
Cuteclysm
Dark Days Ahead, Bionic Professions, Magiclysm, DinoMod, Disable NPC needs, No Fungal Growth, SpeedyDex, Stats Through Kills

### Additional context

This is probably why Rubik got exiled here: nobody else wanted to keep putting up with his crap.

**Comment by PatrikLundell** [comment]
/confirmed

It can be noted that companions (and the PC) do the same thing with own faction animals housed in the livestock expansion. Rather annoying to be interrupted every tile when hauling stuff...
