### ISSUE TITLE
Ability to use EOC to spawn items in characters inventory or in relation to them

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#61650]
### Is your feature request related to a problem? Please describe.

I have an EOC for spawning a new artifact that the PC crafts.   
```
{
    "type": "effect_on_condition",
    "id": "eoc_artifact_spawn",
    "condition": { "compare_int": [ { "u_val": "vitamin", "name": "creative_spark" }, ">=", { "const": 1 } ] },
    "effect": [
      { "u_assign_activity": "ACT_GENERIC_EOC", "duration": "1 seconds" },
      { "arithmetic": [ { "u_val": "vitamin", "name": "creative_spark" }, "-=", { "const": 1 } ] },
      { "queue_eocs": [ "EOC_ARTIFACT_SPAWN" ], "time_in_future": 1 },
      { "u_add_effect": "manic_fugue", "duration": "2 minutes" }
    ],
    "false_effect": [ { "u_message": "You don't have enough creative juice to enter an inspired state.", "type": "bad" } ]
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_ARTIFACT_SPAWN",
    "condition": { "u_has_effect": "manic_fugue" },
    "effect": [
      { "mapgen_update": "spawn_minor_spark_artifact" },
      {
        "u_message": "As you leave the fugue state, you realize you have managed to create a thing.  Now to figure out what it does.",
        "type": "info"
      }
    ]
  }
```
When it fires off the artifact spawns randomly somewhere around the character but there's no telling where it will be and it's often 10 or more tiles away from the character which can be confusing if you are indoors and it spawns outdoors.

### Solution you would like.

I'd like to be able to either spawn the mapgen update directly on the characters tile or to spawn things into the characters inventory or both options.

### Describe alternatives you have considered.

I'm sure there are likely other workarounds.

### Additional context

Tagging @Ramza13 to let him know I made the issue.  :)

**Comment by Ramza13** [comment]
@Maleclypse #63522 should fix this issue now.  Let me know if you have any questions or need more features for it.
