### ISSUE TITLE
Kicking destroys clothing inappropriately

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#61658]
### Describe the bug

Certain martial arts attacks, such as Muay Thai's kicks, use the legs and feet. This seems to cause an inordinate amount of wear and tear to gear worn in these locations, quickly destroying the pants, shoes, and socks of any survivor using these styles. While it makes sense that your pants would occasionally get ripped while kicking things to death, it seems to be happening much too quickly. You can completely destroy a pair of shoes or pants on 20-30 zombies, which is not that many in the grand scheme of things.

There is a second, possibly separate issue, and that's that kicking sometimes damages items which are not worn on the feet or legs. Are these attacks not checking gear appropriately?

### Steps to reproduce

Make a survivor that knows Muay Thai
Go fight things
Watch your clothing get obliterated

### Expected behavior

Tough materials like denim and leather should not really be taking damage at all from kicks unless the target is covered in barbs or something. Real life martial artists aren't constantly replacing their gi pants. Additionally, it seems weird that durable items like shoes and boots are getting destroyed by kicks that leave even bare feet totally unharmed.

Furthermore, attacks appear to be inappropriately causing damage to inappropriate items, as seen in the screenshot below. The ear plugs in question were worn at the time and not held.

### Screenshots

![image](https://user-images.githubusercontent.com/94415528/195550654-3bcac231-8150-46fe-8eab-e55acb4d813f.png)

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 07a9641 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
This also happens with Krav Maga even if you're wielding a weapon. My activity suit shredded in like a minute from Krav techniques and I didn't even realize until a zapper shocked me.

**Comment by nopenoperson** [comment]
yeah its a bit extreme atm.  anything using the elbow attack vector will destroy a lot of clothing worn on the upper body
