### ISSUE TITLE
Various "unconnected" sprites have wrong default rotation

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#61653]
### Describe the bug

Multi-tile supporting tiles can rotate unexpectedly depending on their situation, such as being near a wall or simply out in the open. This is most apparent in NeoDays, but occurs in other tilesets.

### Steps to reproduce

 1. Have a multitile supported tile such as a bathtub or fire burst (in a compatible tileset)
 2. Depending on the tile, it may rotate only to walls, or rotate unnecessarily; see attached screenshots.

### Expected behavior

Tiles do not arbitrarily rotate their sprite.

### Screenshots

_NeoDays_
![neorotatt](https://user-images.githubusercontent.com/32048635/195487646-5492375d-3d0b-458f-b4dd-334211ef65c0.png)
_BrownLikeBears_
![blbrotatt](https://user-images.githubusercontent.com/32048635/195487879-05907a00-9383-4dd1-83ab-1a78270e2fcf.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 91310b2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

(In NeoDays, however I assume it is the same for other tilesets) the sprites have ``"rotates": "false"``, and only one ``"fg"`` entry for ``"id": "unconnected"``. Their is a possible workaround available by assigning the same sprite four times via an array, but that doesn't seem intentional and would need to be done for every affected sprite across every tileset where visible.

**Comment by mlange-42** [comment]
Looks like `rotates` is set to `true` for multitile sub-tiles during loading: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L1096

For the sprite list solution, 2 sprites should be sufficient.

**Comment by mlange-42** [comment]
> Looks like `rotates` is set to `true` for multitile sub-tiles during loading: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L1096

This seems necessary as the information which tile of the same subtile index is to be used is encoded through rotation (e.g. to distinguish the different end_piece tiles). And if there is only a single sprite in the 
sub-tile list, it assumes that it should be rendered rotated (instead of choosing from the list).
