### ISSUE TITLE
Artisan Weapon "the Disorder" not firing

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#61665]
### Describe the bug

The the Disorder is not proccing "Sweet Hit Spot" that allows it to use a .22lr blank as catalyst to deal massive damage.

### Steps to reproduce

1. Spawn the Disorder
2. Spawn some enemies
3. Hit them, hit them a lot

### Expected behavior

It should proc the skill atleast once in a while.
To be honest, since it requires ammo, it should be a non crit skill.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: 16c6b00 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Teleporter [Teleporter],
    Artifact Jewelries [Artifact Jewelries]
]

**Comment by robotic-gamer** [comment]
does the special attack require some minimum skill your character doesn't have? also is the weapon base game or from some mod?  I've never heard of it before and its not in the item browser.

**Comment by Kywi001** [comment]
> does the special attack require some minimum skill your character doesn't have? also is the weapon base game or from some mod? I've never heard of it before and its not in the item browser.

Its a base game weapon obtainable from the blacksmith, I dont think that it needs a skill level since it just needs an ammo and procs on crit, will double check tho.

**Comment by Kywi001** [comment]
Update, it can proc on 0 skill, tested on another character, procs roughly 30% of the time, but for some reason, it never proc on the save that Ive been playing for a long time now even if I set my stats low and set my skills up.

**Comment by Kywi001** [comment]
Update, found the problem, will be closing this one and open a new one due to it may be affecting more than this weapon
