### ISSUE TITLE
Radiation doesn't seem to cause mutations anymore

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#61664]
### Describe the bug

I'm not sure when it started, but I took a break from the game for a week or so and came back, and now my characters are no longer mutating when irradiated. More specifically, the game _tries_ to mutate them, but fails, either with a message "You feel strange" but with no actual change, or just a "You feel something straining inside you, yearning to be free!".

I ordinarily do expect this behavior, but only after I've already accrued a lot of mutations, not when I'm completely human still.

### Steps to reproduce

1. Become extremely irradiated.
2. Wait for a mutation message
3. No actual mutations

### Expected behavior

Should normally mutate when irradiated enough.

### Screenshots

![image](https://user-images.githubusercontent.com/24522330/195638030-e30f5319-3721-4b34-a2f4-3ab014194e5f.png)
![image](https://user-images.githubusercontent.com/24522330/195638113-52bc3aba-e0ad-4eef-a69c-cf7bebaa9400.png)
![image](https://user-images.githubusercontent.com/24522330/195638327-efe9557f-03f6-4fb2-88b6-005805d7b843.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 16c6b00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The issue specifically is noticeable to me because I only play prototype cyborgs and they ordinarily start mutating like crazy a week or so in thanks to their constant irradiation, however now there's no changes whatsoever. Initially I thought I had just hit a low chance of getting no new mutations at the start even though I didn't have any yet, but no, it doesn't seem to work at all. I have around 10 traits that I started with already, and I do have Robust Genetics, I am unsure if this has anything to do with the issue.

Attempting to mutate via the debug menu seems to work fine and as expected. Might be an issue with just radiation.

**Comment by robotic-gamer** [comment]
just speculation on my end but maybe radiation induced mutation was not updated to add mutagenic compounds to the player so the game has no valid mutation to select.

**Comment by Ilysen** [comment]
Looking into this now. I'm gueeeessing that it's because dummy mutations are prioritized for a category if they can be, and the `ANY` category that's assembled for "true random" mutations (like radiation) erroneously probably includes those dummies. Should be a quick fix tho.

**Comment by Ilysen** [comment]
PR made with the fix. sorry! good catch.
