### ISSUE TITLE
wild rice as a harvestable plant

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61663]
### Is your feature request related to a problem? Please describe.

a fair number of cooking recipes requires rice specifically to be made. the problem with this is that the only real source of rice is dried rice which will eventually rot in the long run making rice effectively unobtainable.

### Solution you would like.

wild rice to be added to the game to give a way to farm or forage rice in the long run as a substitute for dried rice (that and wild rice could be dried into dried rice). certain varieties of wild rice actually do grow in the area where the game takes place so it would be a sensible addition from a realism perspective. https://en.wikipedia.org/wiki/Wild_rice

### Describe alternatives you have considered.

remove dried rice's shelf life so it won't rot away in the long run and thus become unscavengable.

### Additional context

wild rice seems to grow in similar conditions to lotuses and and cattails so it could be added to those locations. wild rice can be grown deliberately so it would make sense fore it to be plantable.

**Comment by merrygin** [comment]
No kidding, just earlier today i wrote down to do exactly that (plus some additional stuff) later this month. what a funny coincidence xD 
So yeah, will get around to do this prob. end of october/november at the latest, if nobody else wants to do itbefore.

**Comment by NetSysFire** [comment]
I approve of this. Wild rice is native to New England (https://gobotany.nativeplanttrust.org/species/zizania/palustris/). Also see https://www.eattheweeds.com/wild-rice/
