### ISSUE TITLE
Curing roe recipe requires "water" specifically

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61660]
### Describe the bug

The recipe ought to accept clean water as well.

### Steps to reproduce

1. Find some roe (at least two)
2. Try to craft "curing roe"
3. Find that you can't, because you've cleaned all your water...

### Expected behavior

Since there presumably isn't any particular microbial activity required for the curing process, clean water should work (at least) as well as untreated water.

### Screenshots

Recipe. Note that "water" at the end doesn't allow for "clean water" as an alternative.
![Screenshot (265)](https://user-images.githubusercontent.com/22739822/195578231-4140f5e8-fcb1-4ed5-a193-a748af755be8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 64e17c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]
+ "mod" to disable portal storms
+ Bare bones basecamp added recipes for lump of steel and plant fiber

### Additional context

Obviously a rather minor issue (unless you're very short of containers). Should be rather easy to modify the recipe.

**Comment by Computer-Engineer-Man** [comment]
I'm gonna give this one a shot. If there is anything I do wrong please let me know.
