### ISSUE TITLE
Gallon-sized zipper bag won't fill with water from tank while in inventory.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#61661]
### Describe the bug

I had 2 gallon-sized zipper bags in inventory.  Attempted to fill a bag with water from a hot water heater.  Got message that I poured water into the bag, with some left over, but there was no water in my inventory or on the ground.  Dropped one bag on the ground and filled it just fine.  Wielded the other bag and filled it just fine.  Apparently the bags won't fill while in inventory.

No water was removed from hot water heater despite message saying it was.

### Steps to reproduce

1. make player with two gallon-sized zipper bags, pack, hot water heater with fresh water.
2. `e`xamine hot water heater, fill container, gallon-sized zipper bag.
3. Fill fails.
4. drop one bag on floor
5. `e`xamine hot water heater, fill container, gallon-sized zipper bag on floor.
6. Fill succeeds.
7. `w`ield empty zipper bag.
8. `e`xamine hot water heater, fill container, gallon-sized zipper bag in hands.
9. Fill succeeds.

### Expected behavior

If filling zipper bags in inventory is possible, then attempting to fill there should succeed.
If filling zipper bags in inventory is *not* possible, then attempting to fill there should provide an appropriate fail message, rather than a false message about putting the liquid in the bag.

### Screenshots

![Screenshot_zipper_bag](https://user-images.githubusercontent.com/64863108/195586567-cca35571-3d0f-4556-b6bb-1662969a9deb.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-11821-g64e17c66cd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
I assume the pocket the bags were in couldn't expand enough to fill water into the bags. But yeah, in that case at least the messaging needs to be improved. It should also be possible to improve the handling to actually fill the bag and then try to move it into a bigger pocket or query what to do with it (wield/drop) if there is none, reloading does something like that for example.
