### ISSUE TITLE
Impossibly large fridge/freezer items

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#61681]
### Describe the bug

Freezer has an item size of 900 L
Fridge has an item size of 800 L

There exists no vehicle in the game that can fit these volumes, implying that they were assembled on the spot despite being found in garbage dumps and similar places as they are impossible to transport by vehicles.
Freezer has only 450 L of space inside of it used for storage, implying that only 50% of the total appliance volume is used for storage.

### Steps to reproduce

Compare appliance item sizes to max storage capacity of vehicle parts.

### Expected behavior

Being able to load a fridge/freezer into a truck.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.329 (2004)
- Game Version: feaf1b8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I think there's other appliances with similar size issues that should reasonably fit into trucks, but don't.

**Comment by PatrikLundell** [comment]
The Cataclysm caused a persistent damage to the reality such that pre-cataclysmic vehicle cargo spaces got divided up into separate spaces rather than the previous contiguous ones, which explains why large items could be moved around with limited effort in the earlier world. ;)

A work around is to wield these items. It really isn't much more dangerous than driving around constantly using a phone, and the risk of hitting moving traffic is very low in the post apocalyptic world.

**Comment by KHeket** [comment]
I saw a good idea before to make cargo space united, but its hard to realise
Much more easily idea to make new cargo tile with bigger volume, and make it unwalkable (like 200 Liter barrel), or make simular to livestock storage tile, but for furniture. Tile, which can held only 1 big item, like livestock storage can held only one animal(including cows with bodysize more bigger than 500L)
But there is one way to transport fridges - you can disassemble them for parts and then craft it at your base. But its consuming a lot of time. There is also still no ability to disassemble and craft regular fridges, despite I have opened pr for it for a long time ago
https://github.com/CleverRaven/Cataclysm-DDA/issues/58083
