### ISSUE TITLE
Unintended byproduct of crossbow practice

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#61683]
### Describe the bug

Intermediate crossbow practice needs 20 wooden broadhead bolts and return 30.

### Steps to reproduce

1. Practice advanced crossbow.

### Expected behavior

Return of the 20 bolts needed for doing it and not getting any extra out if thin air.

### Screenshots

![imagen](https://user-images.githubusercontent.com/43771067/195823714-8f81b482-0361-4213-931e-6250d0c4ea72.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: feaf1b8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Xedra Evolved [xedra_evolved],
    Xedra Expanded No Class Limit [xedra_no_class_limit],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
It doesn't return 30, it returns a randomized amount less than that.

**Comment by Zireael07** [comment]
So the crafting screen shouldn't claim it returns 30, duh.
