### ISSUE TITLE
`hit_you_effect` enchantment doesn't work with items

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#61693]
### Describe the bug

`hit_you_effect` enchantment doesn't work, if you use them in items

### Steps to reproduce

<details>

  <summary>1. Copypaste the json below somewhere in the game</summary>

```json

  {
    "type": "enchantment",
    "id": "ENCHANTMENT_VAMPIRISM",
    "hit_you_effect": [ { "id": "xedra_weak_healing", "once_in": 3 } ]
  },
  {
    "id": "xedra_weak_healing",
    "type": "SPELL",
    "name": "Weak healing",
    "description": "Heal 1 hp.  Used in various enchantments.  You can see it only in debug.",
    "valid_targets": [ "self" ],
    "min_damage": -15,
    "max_damage": -15,
    "effect": "attack",
    "shape": "blast",
    "flags": [ "SILENT"  ]
  },
  {
    "type": "GENERIC",
    "id": "qiang_healing",
    "name": { "str": "spear of life", "str_pl": "spears of life" },
    "description": "Long, dense spear, maded out of people's fears and dangers.  It can steal a life from creature it attacks, healing you for a bit.",
    "weight": "1398 g",
    "color": "light_gray",
    "symbol": "/",
    "material": [ "forged_dreamstuff", "wood" ],
    "techniques": [ "WBLOCK_1", "IMPALE" ],
    "volume": "2500 ml",
    "longest_side": "180 cm",
    "cutting": 37,
    "to_hit": { "grip": "weapon", "length": "long", "surface": "point", "balance": "good" },
    "flags": [ "DURABLE_MELEE", "SPEAR", "REACH_ATTACK", "NONCONDUCTIVE", "SHEATH_SPEAR", "MAGIC_FOCUS" ],
    "weapon_category": [ "POLEARMS", "SPEARS" ],
    "qualities": [ [ "COOK", 1 ] ],
    "relic_data": { "passive_effects": [ { "id": "ENCHANTMENT_VAMPIRISM" } ] }
  }
```
 

 </details>

  2. spawn the `spear of life`
  
  3. try to attack a debug monster
   
  4. find no spells is casted, and 0 damage were healed

### Expected behavior

Being able to cast spells while attacking

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: c12b0ce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

### Additional context

May be related to #60566

**Comment by RedMisao** [comment]
I think the problem for this and https://github.com/CleverRaven/Cataclysm-DDA/issues/61694 is that `passive_effects` is not "activating" (for lack of better term) the enchantment_id referenced inside, setting the enchantment as inline works properly, which may serve as a workaround.

I've tested this by:
* bio_ankles referencing a custom enchantment_id (it works), 
* a custom effect referencing the same enchantment_id (it works), 
* copying and pasting the enchantment data as inline (it works), 
* aura_feral referencing the custom enchantment_id (didn't work, only the existing inline enchantment was "active"), 
* moving around the .json field containing the enchantment_id to check if it was a loading order issue (didn't work).
