### ISSUE TITLE
makeshift battery battery charger

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61698]
### Is your feature request related to a problem? Please describe.

- recharging batteries requires materials not easily obtainable in the wilderness/rural locations
- very simple batteries can be constructed using two different metals and a bit of salt water soaked paper

### Solution you would like.

the ability to use a simple crude battery to recharge proper rechargeable batteries.
idea is a rechargeable battery can be inserted into the makeshift battery device to be recharged at the cost of consuming charges of the makeshift battery device. when the makeshift battery device runs out of charge the only remaining use for it is to be dissembled for some of the materials back.
the makeshift battery can be constructed from scrap metal, copper/aluminum, paper/carboard/cotton scrap, salt water, a bit of wood carved into a trough to hold everything together, and some wiring to connect it to the battery to be recharged.

### Describe alternatives you have considered.

making makeshift batteries that can be directly used in devices

### Additional context

since the makeshift batteries can be made to any size it would probably make sense for there to be multiple versions for each size of rechargeable battery.
it might also be a good idea to make a version that functions as a crude UPS so things like smartphones can be recharged.

**Comment by Zireael07** [comment]
I seem to recall makeshift batteries in the past, they were removed because the power output was very small IIRC?

**Comment by robotic-gamer** [comment]
> I seem to recall makeshift batteries in the past, they were removed because the power output was very small IIRC?

that's part of why I am suggesting using the makeshift battery to recharge a normal battery rather then putting the makeshift battery directly in a device. this way the design of the makeshift battery is not constrained by the dimensions of proper batteries and so can be built as large as needed to accomplish the task of recharging.
