### ISSUE TITLE
Artifact passive  "MAX_HP" is not working

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#61701]
### Describe the bug

The extra hp show, but the hit point reset back to is original number after a turn. 

### Steps to reproduce

Example: you have 100 hp plus the bonus an artifact with this passive give like 110 in total, heal from any source, you got 105 hp. A few moment later you got 100 again.
You need : an artifact with MAX_HP and some way to fast heal.

### Expected behavior

The normal extra HP bonus without losing it few moment later.

### Versions and configuration

Windows 7
cdda-windows-tiles-x64-msvc-2022-10-11-1637

### Additional context

Still single.

**Comment by alp7292** [comment]
MAX_HP doesnt works in any case for me my suggestion is fixing MAX_HP enchantment and applying into the traits and mutations instead of using hp_modifier_secondary and hp_modifier as they causes issues if two different mutation use hp_modifier or hp_modifier_secondary

**Comment by GuardianDll** [comment]
Yep, just decided to test it, but something brick it up.  Regeneration also doesn't work
```json

  {
    "type": "mutation",
    "id": "DEBUG_HP",
    "name": { "str": "Debug 9000 HP" },
    "points": 99,
    "valid": false,
    "description": "If you need to survive the bug attacks.",
    "relic_data": { "passive_effects": [ { "values": [ { "value": "MAX_HP", "add": 9000 } ] } ] },
    "debug": true
  }

```


```json

  {
    "type": "mutation",
    "id": "DEBUG_HP_REGEN",
    "name": { "str": "Debug Regeneration" },
    "points": 99,
    "valid": false,
    "description": "Heal yourself from this stupid bug attacks.",
    "relic_data": { "passive_effects": [ { "values": [ { "value": "REGEN_HP", "multiply": 100 } ] } ] },
    "debug": true
  }
  
  ```

**Comment by alp7292** [comment]
> Yep, just decided to test it, but something brick it up. Regeneration also doesn't work
> 
> ```json
>   {
>     "type": "mutation",
>     "id": "DEBUG_HP",
>     "name": { "str": "Debug 9000 HP" },
>     "points": 99,
>     "valid": false,
>     "description": "If you need to survive the bug attacks.",
>     "relic_data": { "passive_effects": [ { "values": [ { "value": "MAX_HP", "add": 9000 } ] } ] },
>     "debug": true
>   }
> ```
> 
> ```json
>   {
>     "type": "mutation",
>     "id": "DEBUG_HP_REGEN",
>     "name": { "str": "Debug Regeneration" },
>     "points": 99,
>     "valid": false,
>     "description": "Heal yourself from this stupid bug attacks.",
>     "relic_data": { "passive_effects": [ { "values": [ { "value": "REGEN_HP", "multiply": 100 } ] } ] },
>     "debug": true
>   }
>   
> ```

is these debug options in game if it isnt it would be very good

**Comment by GuardianDll** [comment]
They are not. I thought to add them, but found the effect is bricked
Hope someone who will fix it will also add them into the game

**Comment by alp7292** [comment]
map memory enchantment also needs to be removed from game as its useless

**Comment by Solusphere** [comment]
Just confirming this is still a problem in 2023-02-16-0640. Artifacts with this effect visually increase max health, but the "missing" health cannot be recovered.
