### ISSUE TITLE
Alternative way to produce liquid ammonia

### ISSUE THREAD

**Issue by yoshiquest** [CleverRaven/Cataclysm-DDA#61707]
### Is your feature request related to a problem? Please describe.

When looking into the requirements for mutagen, it seems to require a rather rare form of ammonia. The current way of making it is somewhat cumbersome and it would be nice to have an alternative.

### Solution you would like.

It should (probably) be possible, both realistically and in game, to produce anhydrous ammonia (aka liquid ammonia) from ammonium hydroxide (aka ammonium solution). And a recipe should be added that does this.

### Describe alternatives you have considered.

Just leaving it as is.

### Additional context

I'm no chemist, but I did look it up and found this video: https://www.youtube.com/watch?v=4epBHiBbbmU
Which seems to make sense, though this results in a gas that would need to be pressurized/refrigerated.
It also calls for concentrated ammonium hydroxide specifically, so maybe it would require quite a lot more of the household stuff to produce.
Again, I'd appreciate if someone better versed in chemistry could chime in.
EDIT: better, more detailed video of the process:
https://www.youtube.com/watch?v=I_DD2_7QkRk

**Comment by robotic-gamer** [comment]
I suspect ammonia solution can be converted to anhydrous ammonia by distillation and or desiccants.

other ways of producing ammonia
- dry distillation of protein rich organic materials (ie nails, protein powder etc)
- dry distillation of coal (also produces other useful substances such as an impure kerosene analog)
- heating reactive metals (magnesium, aluminum etc.) in nitrogen gas followed by exposing the metal to water)

also worth mentioning that the easiest way to produce liquid ammonia in game is to get it as a byproduct of making saltpeter from ammonium nitrate (best acquired from commercial fertilizer) and lye powder.
