### ISSUE TITLE
Unrepairable but resizable items need "refit using ..." when examined.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#61713]
### Is your feature request related to a problem? Please describe.

Some items, such as the chainmail coif and turnout boots, are not repairable, but can be refitted.  Normally a repairable item will say, "Repair with ...," but since these are not repairable, you have to run through all your repair tools looking for one that works.

I figured out how to refit the unrepairable turnout boots, but never did figure out how to refit the unrepairable chainmail coif.  The arc welder would reinforce horse chainmail, but wouldn't resize the coif.  The tailor kit handles the horse chainmail and the chainmail chausses (poor fit), but not the coif.

### Solution you would like.

If an item is not repairable, but can be refitted, it'd be nice if the line saying, "This item can be refitted," could be adjusted to include a, "with ..." phrase.

### Describe alternatives you have considered.

Another option is to change the "Repair with ..." line to be "Repair or refit with ..." but it's good knowing when something can be resized but not repaired.

Perhaps have "Repair or refit with ..." if both are possible, "Can't be refitted.  Repair with ..." and "Can't be repaired.  Refit with ..." when one is possible, and "Can't be repaired or refitted" when neither is possible.

### Additional context

The chainmail coif (poor fit) `e`xamine screen showing it can't be repaired but can be refitted.  Interestingly, it says I know of nothing that can be made with it, but the Faraday suit can be made with it once you figure out how to resize it (but that recipe is not memorized, so maybe that's OK.).

![Screenshot_chain_coif](https://user-images.githubusercontent.com/64863108/195989508-35600d4e-7661-4e36-a4e0-f1680072c51a.png)

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-11968-g74abea8db3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Yes, the section that mentions things that can be made out of an item is limited to known recipes. The description ought to change to include the Faraday suit if the recipe is in a book within crafting range, at least if your skill level is sufficient to make it.
