### ISSUE TITLE
Portal storm "Investigate Strange Location" is bugged

### ISSUE THREAD

**Issue by Luca-spopo** [CleverRaven/Cataclysm-DDA#61714]
### Describe the bug

```
 DEBUG    : completed mission 12 was not in the active_missions list

 FUNCTION : void avatar::on_mission_finished(mission &)
 FILE     : src/avatar.cpp
 LINE     : 355
 VERSION  : 74abea8
```

My character experienced a portal storm. Once the storm was over, I moved outside, and got this error.
The mission in question is almost certainly the "Investigate Strange Location" mission because it showed up under my "Completed" quests but was never added as a new quest in the beginning.

Going to the location specified in the quest... and there was nothing there.

The location was right next to my house, and I dont think there would have been enough space to spawn anything interesting there anyway. (I know some portal dungeon spawns, but I don't want the spoilers)

### Steps to reproduce

1) Load the save
2) Exit the vehicle and enter my house
3) Craft or something for a few hours
4) Portal storm will start - the time it takes is random - and the time it lasts will also vary.
What is consistent is that a portal storm does happen, and if you wait it out and walk around you'll get this error

### Expected behavior

Mission "Investigate Strange Location" should be added to my mission list.
And there should be something interesting when I do visit the mysterious location

### Versions and configuration
MacOS
74abea8 - I think this is the latest experimental at the time of writing

### Additional context
[New Serbia 19.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9792250/New.Serbia.19.zip)

**Comment by Luca-spopo** [comment]
Okay the issue only seems to exist if I spend the storm hiding in my house.
If I am outside for the entire storm then the dungeon spawns as expected, I get the mission as expected, and things work

**Comment by stasalcatraz** [comment]
The same bug. My character spend the storm inside my killdozer with shuttered windows.

**Comment by harakka** [comment]
On cdda-windows-tiles-x64-2022-11-11-1028, couldn't reproduce with the given instructions using the save in the original post (New Serbia 19.zip).

**Comment by gettingusedto** [comment]
The issue can be reproduced with these steps.
1. Wait/change the weather to portal storm
2. Wait for the portal storm to pass or change back to clear
3. Go to the overmap tile the "Investigate Strange Location" mission pointed out
4. Error screen
![Screenshot_20230111-041005](https://user-images.githubusercontent.com/78019001/211663794-b764d323-7656-4b8f-9bde-31006d1c9558.jpg)

Tested and reproduced in a new clean world.
- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 4bae173 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms]
]
