### ISSUE TITLE
broke torso while sleeping

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61712]
### Describe the bug

dying in sleep

### Steps to reproduce

1.(maybe) using a character with nicotine and caffine background
2.sleep

### Expected behavior

without dying

### Screenshots

![image](https://user-images.githubusercontent.com/63102395/195988735-abbc60bf-5352-4877-976a-26c9d5b8dae4.png)

### Versions and configuration

latest experimental verison as today 0819
![image](https://user-images.githubusercontent.com/63102395/195988677-9edd9b4b-2bc9-48d6-9a29-a77c8b1e32cb.png)

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9792159/debug.log)

**Comment by robotic-gamer** [comment]
without more information it kind of looks like your character died from dehydration.

**Comment by blablase** [comment]
i did drink like 0.75L of water and also not using any cigarettes because i want to lose the addiction affect

**Comment by PatrikLundell** [comment]
Do you have any idea how long the character was asleep? I regularly encounter going to sleep with a positive hydration state but waking up Very Thirsty, or even dehydrated (have happened at least twice during the first month of summer), in particular when it's warm, but the temperatures have been lower than the daytime ones, where water is depleted very rapidly.
I suspect it's dehydration, with the character losing water too fast and somehow not waking up.

**Comment by blablase** [comment]
i actually try drinking till full and then go to sleep , still it didnt work

**Comment by blablase** [comment]
also was sleeping for like 2 hours

**Comment by blablase** [comment]
it actually increase to 4 hours when i drink till full and then the hunger stat go down too quickly idk about the thirst stat

**Comment by blablase** [comment]
when i change bed tile the timer go up and down while the bed being just nothing on it

**Comment by blablase** [comment]
![image](https://user-images.githubusercontent.com/63102395/196031547-66447c59-7ec2-4e5c-8ab2-d975419bf47b.png)
it really said that i am dehydrated even though im trying to sleep for 3 hours while i have drank full amount of water like belly full, also i slept easily the day ago while sleeping like 24 hours without any trouble maybe because im using 2 addiction background plus metabolism

**Comment by blablase** [comment]
i actually found what cause it (maybe), because for some reason my food and water consumption get so high that my full belly got depleted in under 3 hours maybe because i was near end nicotine withdraw and my stat from parched returned to verythirsty after i went to sleep, before i went to sleep i was going around picking fruit to fill my hunger while at it the high food consumption was gone and that it

**Comment by PatrikLundell** [comment]
Filling the belly doesn't say much. After getting dehydrated I can fill the belly, but I'm still Very Thirsty and have to wait until some of the water gets processed somewhat before drinking more.

However, I still think the PC should wake up unless heavily drugged, rather than dying. In fact, the point at which the PC should wake up is probably the point at which the first point of damage is taken.

**Comment by Leland** [comment]
> i actually try drinking till full and then go to sleep , still it didnt work

So it sounds like you're saying:

1. Your character was parched
2. They drank some water
3. They went to bed
4. Your character dies

I would agree that that doesn't sound like expected behavior.

>  In fact, the point at which the PC should wake up is probably the point at which the first point of damage is taken.

This is also true, and deserving of a separate issue.

**Comment by blablase** [comment]
> Filling the belly doesn't say much. After getting dehydrated I can fill the belly, but I'm still Very Thirsty and have to wait until some of the water gets processed somewhat before drinking more.
 didnt get that message the changing from "parched" to a higher thirst status
> However, I still think the PC should wake up unless heavily drugged, rather than dying. In fact, the point at which the PC should wake up is probably the point at which the first point of damage is taken.
did not use any drug also did not also recieve the first point of damage it just instant die

**Comment by PatrikLundell** [comment]
No, you probably started taking damage when the message about the dry eyes started showing up, but given how quickly sleep can progress early on, you might not have had time to see it. In order to have time to see it you'd either have to stare at the character stat display, or, at the very least, somehow see that it changes out of the corner of your eye and have time to see something is happening before death happens.

The last sentence of my comment indicated how I think it should work, not how it currently works.

**Comment by blablase** [comment]
> No, you probably started taking damage when the message about the dry eyes started showing up, but given how quickly sleep can progress early on, you might not have had time to see it. In order to have time to see it you'd either have to stare at the character stat display, or, at the very least, somehow see that it changes out of the corner of your eye and have time to see something is happening before death happens.
oh i did see the eye getting dry message and no there is none stat fluctuate like nothing happen and then the torso from full bar to zero

**Comment by blablase** [comment]
> No, you probably started taking damage when the message about the dry eyes started showing up, but given how quickly sleep can progress early on, you might not have had time to see it. In order to have time to see it you'd either have to stare at the character stat display, or, at the very least, somehow see that it changes out of the corner of your eye and have time to see something is happening before death happens.
> oh i did see the eye getting dry message and no there is none stat fluctuate like nothing happen and then the torso from full bar to zero

**Comment by PatrikLundell** [comment]
If the sidebar doesn't show damage taken there may additionally be something not working properly with the sidebar.

**Comment by robotic-gamer** [comment]
I find a good indicator of how dehydrated a character is to look at how bad the speed malus is.
