### ISSUE TITLE
Compilation error: trait_INFIMMUNE not declared

### ISSUE THREAD

**Issue by thialfi17** [CleverRaven/Cataclysm-DDA#61727]
### Describe the bug

In trapfunc.cpp line 278 the trait_INFIMMUNE is not declared because it was removed and replaced with a flag by a pull request that was merged just before the pull request that was merged that referenced it. I would fix it myself but I'm not familiar with the processes involved.

### Steps to reproduce

Try and compile the code from master

### Expected behavior

Compilation to run

### Versions and configuration

- 

### Additional context

Error caused by the combination of the two following PRs/commits
 - [Moving infection immunity to a flag](https://github.com/CleverRaven/Cataclysm-DDA/commit/0615f31c169eb6cf49ce535f33358a1225b3677d)
- [Caltrops can infect players who stand on them](https://github.com/CleverRaven/Cataclysm-DDA/commit/8789a3100c7ebe0065118573b27d96d189740966)

**Comment by anothersimulacrum** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/61719
