### ISSUE TITLE
Magic rings worn left side only

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#61733]
### Describe the bug

I'm trying to wear two magic rings. Both are equipped to the left hand with encumbrance penalty.

### Steps to reproduce

1. Make a player with two magic rings. For example ring of strength +4 and ring of dexterity +3.
2. Equip rings.
3. Both rings are equipped to the left hand. 

### Expected behavior

Rings should be equipped to the left and to the right hands

### Screenshots

![screenshot](https://user-images.githubusercontent.com/2695146/196028713-0642753f-aac2-48e9-8d94-93d7a3ff4265.png)

### Versions and configuration

- OS: Ubuntu 22.04
- Game Version: 0.F 27c1f39
- Graphics version: Tiles
- Ingame language: English or Ukrainian
- Mods loaded: [
  "dda",
  "aftershock",
  "blazeindustries",
  "xedra_evolved",
  "package_bionic_professions",
  "magiclysm",
  "no_npc_food",
  "no_fungal_growth",
  "speedydex",
  "StatsThroughSkills",
  "Tamable_Wildlife",
  "MMA",
  "translate_dialogue",
  "extra_mut_scens",
  "sees_player_retro"
]

**Comment by Blorkman** [comment]
You can switch the side your wearing something by going to the armor layer menu, selecting it from "all", and going to the desired limb with the arrows. If you dont know what the armor layer menu is, search your keybinds

**Comment by stasalcatraz** [comment]
I can not find "armor layer" in the keybindings. If i try to change side from sort armor menu or from worn items in advanced inventory  - game does not allow it because of conflict with another ring (which is on the same side) or with the ring itself as you can see in the log messages on the screenshot.

**Comment by Blorkman** [comment]
ah yeah i see, indeed its a bug

**Comment by Sutremaine** [comment]
I believe this can be gotten around by wearing one ring, swapping it to the right side, and then putting on the other ring.

**Comment by Night-Pryanik** [comment]
Related to #53258.

**Comment by stasalcatraz** [comment]
> I believe this can be gotten around by wearing one ring, swapping it to the right side, and then putting on the other ring.

No, you can not change side. The ring conflicts with itself.
