### ISSUE TITLE
Thin smoke traverses walls

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#61741]
### Describe the bug

(At least some types of) thin smoke can traverse (at least some types of) what should be solid walls.

This _sounds_ like a duplicate of #14894, but that issue was resolved years ago. Perhaps something about walls, thin smoke, or permeability has changed since then.

### Steps to reproduce

1. Build a couple of smoking racks at one of the outside corners of an evac shelter. See screenshot.
2. Stuff each one half full of vegetables and half full of fruit, load them both full of charcoal.
3. Light both smokers.
4. Go back inside, close all the doors and windows, and stand in the corner where the smokers are.
5. Wait a bit.
6. Choke on smoke.

### Expected behavior

Smoke doesn't traverse the evac shelter's "white wall".

### Screenshots

![image](https://user-images.githubusercontent.com/118625/196043409-aa3a47ff-7dc9-453e-936d-df6e2e41da0b.png)

### Versions and configuration

- OS: Windows 10 Pro
- Game version: 0.F-3
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: No major modpacks but a whole bunch of the included small mods. Happy to test with mods disabled if this proves irreproducible

**Comment by mikegogulski** [comment]
NB: The charcoal kiln south of the 2 smokers was not operating during this period.

**Comment by TealcOneill** [comment]
@GuardianDll Wasn't able to replicate. I filled up smokers enough to last several days and surrounded it with white walls and never saw any smoke passing into or through them.
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-0120 731bdaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
