### ISSUE TITLE
Crafting Neoprene Sheet Yields 9, but Recipe Indicates Yield of 1

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#61753]
### Describe the bug

I was surprised to see that, upon finishing crafting the neoprene sheet recipe, that nine units of neoprene sheet were created.  Given that the recipe doesn't indicate that it makes anything other than a single unit (i.e., no "recipe makes" quantity nor any byproducts shown), I was expecting crafting the recipe to create only a single unit of neoprene sheet.

![image](https://user-images.githubusercontent.com/109529281/196076772-ad04f335-0749-4ff7-892a-916247842bc1.png)

### Steps to reproduce

1. Start crafting neoprene sheet recipe.
2. Upon finishing the crafting, check that nine units of neoprene sheet were created as a result.

A few things to note:
- I tried crafting the recipe twice, and both times resulted in nine units each.
- The recipe uses applied science as its primary skill with a difficulty level of 5.  I only tried this on my character with an applied science level of 4.  When I did the two crafting attempts, one failure was encountered during each.  Not sure if the results could be different if no failures were encountered.
- Here are the specific components I used:
![image](https://user-images.githubusercontent.com/109529281/196077568-a124eea5-5059-47d8-a197-46b087dfa112.png)

### Expected behavior

Either:
1. crafting the neoprene sheet recipe once should result only in one unit of neoprene sheet being created, or
2. the neoprene sheet recipe should be updated (probably via whatever controls the "recipe makes" value) so that it shows that the result of crafting the recipe one time will be nine units.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 4bf0543 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots]
]

**Comment by RenechCDDA** [comment]
Well, 9 is the intended result. But *why* it's not displaying that is curious.

**Comment by RenechCDDA** [comment]
/confirmed to ward off the stale bot. My comments here were before I got those permissions.
