### ISSUE TITLE
Profession with Brutal Strength trait negative stat bug

### ISSUE THREAD

**Issue by Leonovers** [CleverRaven/Cataclysm-DDA#61763]
### Describe the bug

When i set watgrown bodyguard profession and lowered strength to 4 and switched profession to another one i have my strength -3.

Also, for some reason this profession trait Brutal Strength takes my points as if i upgraded strength myself, but Im not sure if this is inteded or not.

### Steps to reproduce

1. Start new game with custom character
2. Set profession to watgrown bodyguard or any other with Brutal Strength trait
3. Lower strength stat to minimal 4
4. Switch profession to any other profession without brutal strength trait
5. Now your strength stat is -3

### Expected behavior

Still having 4 strength stat. Because if you can't do this manually, why you should can do it that way?

### Screenshots

![image](https://user-images.githubusercontent.com/5488253/196225908-3e15e256-9e87-4650-8589-8f808e066779.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 0b1898c [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Альтернативные символы карты [alt_map_key],
    Мифические стили ближнего боя [MMA],
    Перевод сложных диалогов [translate_dialogue],
    Сценарии с доп. мутациями [extra_mut_scens],
    Характеристики за убийства [stats_through_kills],
    Характеристики за навыки [StatsThroughSkills],
    Скорость от ловкости [speedydex]
]

**Comment by Stone94** [comment]
I was able to replicate this, chose vatgrown bodyguard, checked strength at 15, lowered to 4, switched to vagabond (no brutal strength) and strength was -3.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 18 October 2024.
