### ISSUE TITLE
Lamp oil cannot be crafted from rotten tainted fat

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#61779]
### Describe the bug

Possible regression of #29770.

The `lamp_oil` recipe in `data/json/recipes/chem/fuel.json` includes the component list `any_fat` as well as the `ALLOW_ROTTEN` flag. Thus, rotten tainted fat should be craftable into lamp oil. Alas, it is not. See screenshots.

### Steps to reproduce

1. Spawn in a copper pot, a bunch of tainted fat, a bunch of water, and start a (contained?!) fire or have a fueled smoking rack/mess kit or such around.
2. Wait for the tainted fat to rot (couldn't figure out how to spawn it in rotten).
3. Attempt to craft tainted fat (rotten) into lamp oil. Fail. Cry.

### Expected behavior

Rotten tainted fat can be crafted into lamp oil.

### Screenshots

![image](https://user-images.githubusercontent.com/118625/196418511-5c9be68a-c15e-4943-b35b-be426d89d004.png)
![image](https://user-images.githubusercontent.com/118625/196418652-322e1281-08ca-403c-82d1-5cf9c3840ca8.png)
![image](https://user-images.githubusercontent.com/118625/196421344-fc255395-f32a-426c-a3d9-7649c5b78fcd.png)

### Versions and configuration

- OS: Windows 10 Pro
- Game version: 0.F-3
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: No major modpacks but a whole bunch of the included small mods. Happy to test with mods disabled if this proves irreproducible

**Comment by Maleclypse** [comment]
In experimental fat can’t craft kerosene at all.

**Comment by RenechCDDA** [comment]
> In experimental fat can’t craft kerosene at all.

It certainly can? Both the rendered forms and unrendered fat are valid inputs.

Crafting with rotten ingredients works on experimental (7ce3f1a) though

**Comment by Maleclypse** [comment]
> > In experimental fat can’t craft kerosene at all.
> 
> It certainly can? Both the rendered forms and unrendered fat are valid inputs.
> 
> Crafting with rotten ingredients works on experimental ([7ce3f1a](https://github.com/CleverRaven/Cataclysm-DDA/commit/7ce3f1a3747980ebf930c970fd8e9bb3f5ef8b0c)) though

Lamp oil in 0.F -3 is Kerosene in experimental.  Crude lamp oil has replaced the easy fat recipe.
`{
    "result": "crude_lamp_oil",
    "type": "recipe",
    "activity_level": "NO_EXERCISE",
    "category": "CC_CHEM",
    "subcategory": "CSC_CHEM_FUEL",
    "skill_used": "chemistry",
    "difficulty": 2,
    "time": "5 s",
    "batch_time_factors": [ 95, 5 ],
    "autolearn": true,
    "components": [ [ [ "edible_tallow_lard", 2, "LIST" ], [ "tallow_tainted", 2 ], [ "cooking_oil", 16 ], [ "cooking_oil2", 16 ] ] ],
    "flags": [ "ALLOW_ROTTEN" ]
  }`
The catalytic cracking method of producing kerosene is as follows 
`{
    "result": "lamp_oil",
    "type": "recipe",
    "activity_level": "NO_EXERCISE",
    "category": "CC_CHEM",
    "subcategory": "CSC_CHEM_FUEL",
    "skill_used": "chemistry",
    "difficulty": 3,
    "time": "30 m",
    "result_mult": 10,
    "byproducts": [ [ "diesel", 40 ] ],
    "batch_time_factors": [ 80, 4 ],
    "book_learn": [ [ "catalytic_cracking_handbook", 5 ] ],
    "qualities": [ { "id": "CUT", "level": 2 }, { "id": "COOK", "level": 3 }, { "id": "EXTRACT", "level": 3 } ],
    "tools": [ [ [ "surface_heat", 40, "LIST" ] ], [ [ "water", 100 ], [ "water_clean", 100 ] ] ],
    "components": [
      [ [ "chem_washing_soda", 1 ] ],
      [
        [ "edible_tallow_lard", 10, "LIST" ],
        [ "tallow_tainted", 10 ],
        [ "cooking_oil", 160 ],
        [ "cooking_oil2", 160 ],
        [ "any_fat", 60, "LIST" ],
        [ "ghee", 160 ]
      ]
    ],
    "//": "Making kerosene from (tainted) fat directly is less efficient than using lard/tallow, but allows processing of spoilt fats. See #29770.  Needs 10% of volume of the fats in washing soda.  I've reduced the yield percentages from what was acheived in this laboratory based article Performance of Thermochemical Conversion of Fat, Oils, and Grease into Kerosene-like Fuel in Different Production Scales.",
    "flags": [ "ALLOW_ROTTEN" ]
  }`
which requires a catalytic cracking reactor. 

Anyway what I was trying to say is that they are different items in experimental.  Thanks for confirming that it should be closed as completed.
