### ISSUE TITLE
additions to medical treatments

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#61771]
### Is your feature request related to a problem? Please describe.

What lead me to this was primarily how the game treats bleeding and wounds. Right now you can go directly to arterial bleeding, if you lack adequate protection or have hypovolemic shock, due to prolonged fighting with recorrent bleeding. So the game stays between an effect that is too hard, so that its occurance must be limited and the other that does not adds change to the gameplay except for leading the player to avoing being surrounded, especially under negative effects, that is too generic for some encounters (like monsters with sharp edges, such as the predator). After the fighting is over you can just take some food and water and come back to normal, and you did just considered not being surrounded, not the severity of the wounds that could be caused by those sharp edges.

### Solution you would like.

some wounds should require treatments such as sutures and to not make the player overly conservative, those could be find on "survival manuals" with roughly the same frequency as antibiotics. An extra activity could be added to an item such as a needle, and it should work simmilarly to repairing clothes, except for the different menu item and habilities required.

Also the success chances of each attempt of self treatment, for some conditions, such as those involving pain, like this one, could be conditioned by strength and survival hability. Otherwise at some attempts the user could receive a message saying he was "stopped by pain" and also that he was screaming during the process. It would bring the added bennefit of incentivising the player to do explorations with a NPC more often.

### Describe alternatives you have considered.

The game could have an extra menu for "operations", mirroring the recipes menu. So for instance doing suture, would require some needle, thread and needed habilities under "operations". Also instead of "survival manuals" those instructions could be provided along with other basic books, such as self help, the idea of the "survival manual" was for it to be post-cataclysm, but I am not sure.

### Additional context

I gave this title because, in the same way that adding that medical treatment could be useful, others also could be thought about to add some challenges and balances to the game, or more mechanics could be involved. One such example is extracting bullets

**Comment by TheShadowFerret** [comment]
Good issue but

>One such example is extracting bullets

*Eye twitch*

**Comment by bean-b** [comment]
There is also a super WIP long term plan to re-write the hp system as a wound system, and i imagine changes like this would go hand in hand. That being said it could be a long time before we have a wound system.
