### ISSUE TITLE
CI Random failure

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#61776]
### Describe the bug

ERROR : src/item.cpp:1501 [ret_val<void> item::put_in(const item &, item_pocket::pocket_type, const bool)] tried to put an item (poppirate) count (1) in a container (corpse) that cannot contain it: pocket unacceptable because item too big5.365 s: shot_features_with_choke

### Steps to reproduce

Run CI a thousand times a day.  See it happen maybe.

### Expected behavior

CI passes when the changes don't cause it to fail.

### Versions and configuration

CI all day long

**Comment by nopenoperson** [comment]
ive seen this atleast one time

**Comment by mqrause** [comment]
Pop-up Pirate game is over 8000 liters big, probably meant to be ml instead.

**Comment by Zireael07** [comment]
@mqrause Has a fix incoming in #61941
