### ISSUE TITLE
MSXotto+ full windshield doesn't change shape when being reshaped

### ISSUE THREAD

**Issue by Setmaster** [CleverRaven/Cataclysm-DDA#61781]
### Describe the bug

No matter the chosen shape the full windshield always looks the same despite there being tiles for its different positions.

### Steps to reproduce

Use MSXotto+ tileset
Spawn a vehicle with full windshield such as a luxury RV
Notice the windshields look odd
Attempt to change their shape
Notice there are no changes in shape

### Expected behavior

Windshield look changes when its shape is changed

### Screenshots

![image](https://user-images.githubusercontent.com/5375992/196443844-2e944a2c-2cd0-4f24-84b7-2b9abd375295.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 216e10c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Cataclysm++ [Cata++],
    Xedra Evolved [xedra_evolved],
    Pixel's Various Fuckery [Pix's Shit],
    DinoMod [DinoMod],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Tamable Wildlife [Tamable_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Fris0uman** [comment]
Because there's no sprite for Full windshield in MSX currently, not much that can be done about it on the game side. SHould probably open an issue in the tileset repo about it https://github.com/I-am-Erk/CDDA-Tilesets
