### ISSUE TITLE
Appliance power usage when crafting depends on battery size

### ISSUE THREAD

**Issue by ZeroInternalReflection** [CleverRaven/Cataclysm-DDA#61787]
### Describe the bug

The number of battery charges used by an appliance during crafting seems to vary depending on what battery is attached.
This behaviour is probably masked in many cases by the use of multiple batteries and attached power sources such as solar panels.

### Steps to reproduce

1] The attached save has two rows of test appliances with different batteries and all required materials for crafting
2] Go to each FOODCO kitchen buddy and craft oatmeal (10 charges per crafting screen).  Observe the following:

| Attached battery | Charges used  (1 oatmeal) | 
| ------------- |-------------:|
| Small storage battery | 10 |
| Car battery | 0 |
| Medium storage battery | 10 |
| Large storage battery | 0 |
| Very large storage battery | 0 |

| Attached battery | Charges used  (10 oatmeal) | 
| ------------- |-------------:|
| Small storage battery | 100 |
| Car battery | 35 |
| Medium storage battery | 100 |
| Large storage battery | 5 |
| Very large storage battery | 5 |

3] Go to each welding kit and craft a fuel bunker (200 charges per crafting screen).  Observe the following:

| Attached battery        | Charges used          | 
| ------------- |-------------:|
| Small storage battery | 200 |
| Car battery | 100 |
| Medium storage battery | 200 |
| Large storage battery | 10 |
| Very large storage battery | 10 |

4] Start experimenting with other batch sizes
5] Start experimenting with combinations of batteries
6] Observe that different battery combinations seem to behave differently
7] Get a headache

### Expected behavior

The number of charges used when crafting should be the same no matter what battery combination is provided.
As I understand it, the charges used when crafting proceed in steps of ~5% at a time, which suggests that the first step proceeds correctly for the large/very large storage batteries, but breaks afterwards.  For the car battery, I have no idea.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 27c1f39 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[2022-10-18_Appliance_power_usage.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9812130/2022-10-18_Appliance_power_usage.zip)

I've done a similar test with a vehicle-mounted welding rig, and in all of the cases I tested, the expected number of charges were used.

**Comment by RenechCDDA** [comment]
/confirmed

Thank you for the excellent reproduction save. I got slightly different results though. For the car battery, 10 batch of oatmeal it somehow used... 35 battery? For medium storage battery, 10 batch of oatmeal it used 105. (Both of these results are still erroneous, but I'm curious *why* they differed, and by an equal amount in opposite directions). All other results were as you reported.

**Comment by ZeroInternalReflection** [comment]
There definitely seems to be a random component as well.
Walking the same path to the car battery, crafting 1 oatmeal (0 charges used), then 10 oatmeal (35-40 charges used), then another 10 oatmeal (40-45 charges used).  Crafting from the car battery I've had anywhere from 35 to 60 charges used on 100 expected.

**Comment by ZeroInternalReflection** [comment]
There was a random component, and I should have controlled for it.  The test character had the minimum skill required, which meant they occasionally screwed up and lost progress, adding another 5% in time/charges.  That appears to be where the 10*oatmeal 35 vs. 40 and 100 vs. 105 discrepancy came from

I've also been going from select_crafting_recipe, adding messages to the log about what's happening every step of the way.  After a very long chain of functions, I discovered some odd behaviour in vehicle::discharge_battery().  Compare the following:

![Small_storage_battery draining as expected](https://user-images.githubusercontent.com/89038572/196727081-3de3901d-7996-4a1a-b9ee-a350845bd88f.png)

![discharge_battery outputs messages indicating that there are two car_battery parts](https://user-images.githubusercontent.com/89038572/196727089-f1c53aed-fc4a-4e25-9c33-f81abf8397dc.png)

For the car battery, large storage battery, and very large storage battery, it's draining the full expected amount for the craft.  However, it's draining some of it from a second, hidden battery.
Now to figure out where that hidden battery is coming from.

**Comment by ZeroInternalReflection** [comment]
Alright.  I have a working theory.  A fix for this _particular_ issue seems to be relatively simple, but that would probably be masking some underlying weirdness that'll be more complicated to fix.

1. vehicle::get_edge_info() and related functions seem to expect vehicles to be >1 tile wide.
2. All appliances thus get marked as edges by get_edge_info(), ready for the addition of fake parts (this is not exclusive to appliances.  Adding a welding rig to the front of a bicycle demonstrates the bonus fake part that I believe to be superfluous)
![Fake_welding_rig_on_bicycle](https://user-images.githubusercontent.com/89038572/196851545-8f7ca55c-07f0-42ab-a7b8-40f14ad94d6d.png)
3. The appliance versions of car batteries, large storage batteries, and very large storage batteries have the flag "OBSTACLE", while the vehicle versions do not
4. Since an appliance car battery is an obstacle on the edge of a vehicle, vehicle::refresh() adds a fake part for it
5. I'm not entirely sure why this part doesn't get displayed, but it's always there
6. When it comes time to use the battery (not just for crafting), vehicle::discharge_battery() does not check if a part is fake before draining charge from it
7. Thus, when draining the appliance battery, it _averages_ out to ~1/2 of the expected drain, but since discharge_battery() goes by charge level as a percentage, it's uneven, particularly for very large capacity batteries (e.g. it tries to drain the fake part 100->99% before draining the real one)

Adding a check for fake parts to vehicle::discharge_battery() (and charge_battery(), since this impacts that too.  You're charging fake batteries with your solar panels) seems to result in the correct power consumption:

```
@@ -5227,7 +5232,12 @@ int vehicle::discharge_battery( int amount, bool recurse )
     // Key parts by percentage charge level.
     std::multimap<int, vehicle_part *> dischargeable_parts;
     for( vehicle_part &p : parts ) {
-        if( p.is_available() && p.is_battery() && p.ammo_remaining() > 0 ) {
+        if( !p.is_fake && p.is_available() && p.is_battery() && p.ammo_remaining() > 0 ) {
```

This seems like a good check to have, but I'm not sure I could consider it 'fixing' the issue, and modifying fake part generation is probably beyond my c++ abilities.

**Comment by RenechCDDA** [comment]
>Adding a welding rig to the front of a bicycle demonstrates the bonus fake part that I believe to be superfluous)

In my *playing* experience this happens depending on the heading of the vehicle although I don't see how or if that is handled in vehicle::get_edge_info. 

I am not sure I understand this part though, to clarify: Did you reproduce this bug (incorrect power draw due to fake parts) in vehicles, outside of appliances? (NB: If the fix below works it should work across any type of vehicle part.)

> * The appliance versions of car batteries, large storage batteries, and very large storage batteries have the flag "OBSTACLE", while the vehicle versions do not
> * Since an appliance car battery is an obstacle on the edge of a vehicle, vehicle::refresh() adds a fake part for it

Wow, that makes sense but I wouldn't have expected it. 

>This seems like a good check to have, but I'm not sure I could consider it 'fixing' the issue, and modifying fake part generation is probably beyond my c++ abilities.

While working on my reply to this I was trying various things and I believe that modifying vehicle::discharge_battery should eliminate the problem. In my testing I was getting the fully expected and correct battery cost for any size of batch, including multiple batches in a row. There should be a PR linked shortly before or after this comment, it would help to have someone independently verify if this fixes the behavior.
