### ISSUE TITLE
Can't pour water/liquids on pots

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#61789]
### Describe the bug

Pots/canning pots cannot be used as containers for liquids, even if empty. They currently cannot be.

### Steps to reproduce

1. Spawn a pot in your inventory
2. Either go near bodies of water, like rivers, or try to spill liquids like milk or tea into your pot

### Expected behavior

Pots should be considered possible containers to store liquids.

### Versions and configuration

build type: windows-tiles-x64
build number: 2022-10-18-1022
commit sha: cb004569cc118e4e1cca1928902808ee484a82cd
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/cb004569cc118e4e1cca1928902808ee484a82cd

**Comment by Jerald-of-Libya** [comment]
Not a bug. these items have the quality "containing 1". They can contain liquids, but only when on the ground or wielded. 

Tooltip specifically states that they will spill when you put them inside a pocket. You can think of them as not having a proper lid or cap, so you can't really carry them around in your bag if they have any water inside.

Try wielding them, or placing them on the ground when you interact with a body of water.

**Comment by cataclysmsurvivalist** [comment]
> Not a bug. these items have the quality "containing 1". They can contain liquids, but only when on the ground or wielded.
> 
> Item description specifically states that they will spill when you put them inside a pocket. You can think of them as not having a proper lid or cap, so you can't really carry them around in your bag if they have any water inside.
> 
> Try wielding them, or placing them on the ground when you interact with a body of water.

Noted, then I'll set this "bug" as fixed. While I imagined pots came with lids, especially if you crafted them, this is a good enough answer.

**Comment by Jerald-of-Libya** [comment]
Added minor correction to my comment.

You can still file an issue or create your own pull request if you think specific containers should be non-spill though. If you think it's water-tight and can handle getting turned upside-down without spilling, then it should be fine.
