### ISSUE TITLE
Hide/show button to hide items when repairing

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#61785]
### Is your feature request related to a problem? Please describe.

When using repairing tools like sewing kit, soldering iron or welding kit, allow us to hide fully reinforced items, items already fitted and can't be further reinforced and materials and vehicle parts already at max durability.

### Solution you would like.

-show/hide reinforced items
-show/hide fitted and cannot be reinforced items
-show/hide max durability items (for welding kit and soldering irons)

**Comment by Zireael07** [comment]
QoL tag candidate?
