### ISSUE TITLE
All NPCs are 175cm and 25yrs old

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61788]
### Is your feature request related to a problem? Please describe.

Currently basically every (randomly generated) NPC is the exact same age and height. This is obviously just an unfinished feature.

### Solution you would like.

NPCs should be varyingly old and tall.

### Describe alternatives you have considered.

Probably using a standard distribution of some sort to determine what is the "normal" age of cataclysm survivors (probably the younger and healthier) and "normal" height per population distributions.

### Additional context

Too lazy to do this myself but it bears mentioning.

**Comment by mqrause** [comment]
> using a standard distribution of some sort

I think random characters already do something like that that can be used for npcs, too.
