### ISSUE TITLE
Towels Wet from Swimming Aren't "(active)", Never Dry

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#61792]
### Describe the bug

Towels that become wet due to being exposed to water during swimming will never dry.

My guess as to what's happening:
If the player enters a body water with a towel that isn't in a waterproof container, it makes sense that the towel becomes wet.  In that case, the towel (presumably) acquires whatever internal flag that results in it showing the "(wet)" suffix.  This seems to be the same flag that is set when the player activates a towel to dry themself off.

However, when the player activates the towel and it becomes wet from the drying off action, the towel item also acquires whatever flag results in the "(active)" suffix.  My understanding is that being "(active)" causes item processing to check each turn if anything needs to be done with the active item -- in this case, item processing checks if enough time has passed for the towel to dry off, which I assume then results in the towel losing both the flags causing "(wet)" and "(active)".

If the towel automatically becomes wet during swimming, it acquires the "(wet)" flag, but not the "(active)", I'm assuming because the wet-tening happened without the player taking any action or activating anything.  Because the towel is not flagged as "(active)" the logic in item processing to check if the towel should dry off is never invoked, meaning the towel will never lose the "(wet)" flag.

In this image, the reinforced towels acquired "(wet)" from swimming, whereas the non-reinforced towels acquired "(wet)" (and "(active)") from manually activating them to dry off the player.
![image](https://user-images.githubusercontent.com/109529281/196549843-cf85d077-9e7c-4549-9c50-a20dc0823af5.png)

Seems like a fix could be to update the code that applies the "(wet)" flag to the towel while the player is swimming so that the code will also apply the "(active)" flag.

(Note:  I'm not sure if there are other items which can have the "(wet)" flag applied to them beyond just towels.  If there are, I haven't tested them, but I'm guessing a similar problem might exist with those items, too.)

### Steps to reproduce

1. Have two towels
2. Put one towel (towel A) into a waterproof container and the other towel (towel B) into a non-waterproof container
3. Find a river
4. Jump in the river or something like that
5. Get out of the river and observe towel A is dry and labeled "towel" and towel B is wet and labeled "towel (wet)"
6. Activate the towel A to dry oneself off, noting that it will become wet and labeled "towel (wet) (active)"
7. Wait a while
8. Observe that towel A will eventually dry and return to being labeled "towel", while towel B will remain wet and labeled "towel (wet)"

### Expected behavior

Towels should dry off regardless of whether they became wet due to swimming or player activation to dry themself off.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 4bf0543 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots]
]

**Comment by RenechCDDA** [comment]
/confirmed by waiting a day with a wet towel from swimming in my inventory.

In related testing...
![image](https://user-images.githubusercontent.com/84619419/197164753-fc77e374-f1e1-4e43-bac1-7e42cbda6558.png)

**Comment by ChromePoptart** [comment]
😆 I hadn't thought of that as a testing method -- certainly an interesting juxtaposition in that result!
