### ISSUE TITLE
spending like 6 hours just to make clean water and food then just to eat and still get 20% underfed and 20% thirst status

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61807]
### Describe the bug

high calories and water consumption while too little stomach to store them or the stomach just dont burn content fast enough(most of these content fill with water with a slow burn is weird since it depend on different organ to process food which is faster)

### Steps to reproduce

1. use trait fast metabolism and metabolic intercharge
2. survive

### Expected behavior

something like faster water processing or maybe
![image](https://user-images.githubusercontent.com/63102395/196745344-80822e65-eab3-47c0-bfb3-a90214d1692a.png)

https://www.healthline.com/health/digestive-health/how-long-does-it-take-for-water-to-pass-through-your-body#digestion-factors
also metabolism increase food digestion speed
![image](https://user-images.githubusercontent.com/63102395/196744453-16371ec8-d55b-4182-ab4a-0b0022722e64.png)
https://cookthink.com/how-long-does-it-take-for-water-to-boil/#:~:text=Boiling%20water%20on%20high%20is,water%20to%20boil%20on%20high.

took me like so much time just to boil that much water ingame

about the food part is it took like 4 hour from full to very hungry or lower 

kinda weird that a full stomach cannot last like 7-10 hour
even in real life i just need to eat like 320gram of food about 720 calo and that is full enough for in this game i ate like 12-15 tallow a day and still get underfefd status

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9822213/debug.log)

**Comment by blablase** [comment]
> Duplicate of #54501

what about the water consumption crap

**Comment by Fris0uman** [comment]
What about it? Your issue doesn't explain anything

**Comment by blablase** [comment]
> What about it? Your issue doesn't explain anything

sorry my issue title and its problem is just in a general saying, that the title just not what i actually want to say but i think i just make another issue that focus straight on the problem sorry
