### ISSUE TITLE
canned blood

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61806]
### Is your feature request related to a problem? Please describe.

there is no practical way in game to preserve blood for later consumption

### Solution you would like.

being able to can blood in glass jars (either small or large)

### Describe alternatives you have considered.

drying the blood and turning it into a powder.
mixing with ethanol to preserve the blood.

### Additional context

a while back here there was discussions on preserving blood and the conclusion was that salting, and or drying are not viable ways to preserve blood. to my knowledge canning blood was not considered.

**Comment by utechenko-v** [comment]
Animal blood can be stored in a freezer. But I support the idea, it would be good to have ways to preserve it. (offtopic: IMO blood should have quench > 0, but not zero as it is now)

**Comment by KHeket** [comment]
> Animal blood can be stored in a freezer. But I support the idea, it would be good to have ways to preserve it. (offtopic: IMO blood should have quench > 0, but not zero as it is now)

but blood is too salty, its like seawater, and it also must have quench less then 0. There is 90% water in blood, but unrine have 91-96% of water but you cant also use is for hydration becouse of salt and lots of elements, it will dehydrate you
![image](https://user-images.githubusercontent.com/102726167/197181975-247d6061-83e6-4c37-a231-d7dc2da5b9e7.png)

![image](https://user-images.githubusercontent.com/102726167/197182281-9b3e519d-8d01-4359-8778-0b0568fec6d6.png)

**Comment by Zireael07** [comment]
That previous discussion seems to have been #49672
