### ISSUE TITLE
half-face gas mask is unconfortable to the mouth

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#61805]
### Describe the bug

Half-face gas mask, when worn makes the mouth unconfortable.

### Steps to reproduce

1. Make a new world.
2. Spawn in half-face gas mask.
3. Wear the half-face gas mask.
4. Uncomfortable mouth.

### Expected behavior

Being comfortable like the regular gas mask.

### Screenshots

![Screenshot_20221019-204725](https://user-images.githubusercontent.com/78019001/196724986-c0426ad9-28c4-4f75-8071-b1db679ae2b4.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: c837fff [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Misc Sprites [misc_sprite]
]

**Comment by nopenoperson** [comment]
Confirm.
