### ISSUE TITLE
Character with "Hates Vegetables" trait will also dislike pemmican made with berries.

### ISSUE THREAD

**Issue by TiLath** [CleverRaven/Cataclysm-DDA#61828]
### Describe the bug

Title.

### Steps to reproduce

1. Make a character with "Hates Vegetables" trait.
2. Batch craft all your meats into pemmican with berries.
3. Realize you screwed up.

### Expected behavior

Maybe further separate the pemmican into berry or veggie versions?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 1b0bd36 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Translate Complex Dialogue [translate_dialogue],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by nopenoperson** [comment]
/confirmed

when you make pemmican it turns into 50% veggy matter regardless of what you use to make it despite most of the options involving berries
