### ISSUE TITLE
Allow EOC effects to insert and remove item faults and flags.

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#61827]
### Is your feature request related to a problem? Please describe.

Brought up by the recent flux of EMP mechanics, these are a set of additions that would allow to define how EMPs affect items entirely with json.

The goal here would be making EMPs only temporarily disable items when you play with Aftershock, so the effect remains dangerous but not crippling like in Vanilla.

### Solution you would like.

This would require the following additions

- The ability for EOCs to insert  flags to items located on a area, including those carried by characters inside it.
- The ability to filter which items by their flags, so only items with the electronic flag are valid targets.
- The ability to remove item flags and faults based on a timer.

### Describe alternatives you have considered.

Natively allowing our already existing faults to resolve after a time interval

**Comment by nopenoperson** [comment]
append/delete type stuff would also be sweet and all kinds of item modifications really

**Comment by anothersimulacrum** [comment]
> The ability to remove item flags and faults based on a timer.

This gets really complicated if the item moves.

**Comment by GuardianDll** [comment]
what a lost
