### ISSUE TITLE
Friendly turrets of craftman and exodii quadrupeds shoot you with no reason

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61837]
### Describe the bug

Custom plated turrets defeners of blacksmith and gunsmith houses or exodii quadrupeds will shoot you, if you step on the dead body of enemy right after it was killed

### Steps to reproduce

1) Teleport to exodi base/blacksmith and gunsmith houses or spawn Custom plated turret or exodii quadruped
2) Spawn zombid
3) Wait robots to kill it. Important! They must be shooted. Becase if monsters will be killed in melee combat - the bug may not to be reproduces
4) Step on the dead body
5) Wait for some time
6) You will be shooted. But if you get out of dead body - they will stop shooting

### Expected behavior

I dont want to die for no reason

### Screenshots

<details>
  <summary>Custom plated turret kill for no reason</summary>

 ![Снимок экрана (116)](https://user-images.githubusercontent.com/102726167/197178289-4d37ee12-76ec-41aa-9c43-eb987a645d88.png)

![Снимок экрана (117)](https://user-images.githubusercontent.com/102726167/197178297-6683c0ae-51ea-465f-8981-54474841367a.png)

 ![Снимок экрана (118)](https://user-images.githubusercontent.com/102726167/197178304-6c8afe22-c231-4b20-8afc-77189b0624a2.png)

</details>

<details>
  <summary>Exodii quadruped kill for no reason</summary>

![Снимок экрана (112)](https://user-images.githubusercontent.com/102726167/197178309-dd2c6c50-b579-4cee-b557-2725fcb1fd32.png)

![Снимок экрана (113)](https://user-images.githubusercontent.com/102726167/197178311-484b64ca-425c-4a72-93ed-998f98bfd253.png)

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bean-b** [comment]
Had this happen before with the exodii turrets

**Comment by Venera3** [comment]
See the duplicate for background.
