### ISSUE TITLE
Zombie bodies dissapear if there is alive zombie above it

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61836]
### Describe the bug

I like to leave zombie bodies unsmashed to train skills on them in future. But, when you bring lots of bodies in one place and then you come back to this place after a long time - some of bodies dissapear because of rotting and inability to ressurect because of standing leaving zombie above it

### Steps to reproduce

1) Teleport to wind turbine
2) Raise your skills to 10
3) Spawn locksmith kit and open wind turbine door
4) Spawn zombie dogs. Press "i" in monster select menu to [i]ncrease group to 6 points. It will be enough
5) Kill zombies dogs by debug meny. Debug menu > map > kill all monsters
6) Bring 4 full stored tiles of bodies into the wing turbine. You can also unload dog suits
7) Scroll some time by debug menu. Debug menu > map > change time. 30-60 days will be enough
8) Wait for some time. 5-10 minutes
9) See only 4 dogs in wind turbine, and no more bodyes
If the portal storm appearing - just change the weather to clear by map > change weather > clear

### Expected behavior

I dont want to lose valuable training material. And I want to make... TRAINING ZOMBIE GYM HEAL YEAH. Or zombie arena

### Screenshots

<details>
  <summary>Windmill full of dogs dead bodies</summary>

![Снимок экрана (107)](https://user-images.githubusercontent.com/102726167/197174191-73e53ffc-066a-430b-b654-ad7aea4eda96.png)
![Снимок экрана (108)](https://user-images.githubusercontent.com/102726167/197174212-04891967-7695-4442-a43a-10e86e0ffb70.png)

</details>
<details>
  <summary>Wating for 5 minutes after scroll time for 30-60 days</summary>

![Снимок экрана (109)](https://user-images.githubusercontent.com/102726167/197174218-fc6beb9c-4728-4266-b260-f9618a3fdceb.png)

</details>
<details>
  <summary>Only 4 dogs in wind mill and all dead bodies disappeared</summary>

![Снимок экрана (110)](https://user-images.githubusercontent.com/102726167/197174227-536c9f7c-0508-470b-8852-f5e23ce0bde2.png)

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment]
perhaps corpses that could still reanimate should be made to never rot. this way the corpses would just "wait" until there is free space to reanimate. also the lack of rotting can be rationalized as the corpse not being truly "dead".

**Comment by KHeket** [comment]
> perhaps corpses that could still reanimate should be made to never rot. this way the corpses would just "wait" until there is free space to reanimate. also the lack of rotting can be rationalized as the corpse not being truly "dead".

Unsmashed corpses should be unrottable, yeah. And ruly rotting must be stated only after smashed

**Comment by Night-Pryanik** [comment]
The same as #53547?

**Comment by KHeket** [comment]
> The same as #53547?

Seems to be. Different situations but I think simular mechanic problem, but I wander, why linked issue isnt confirmed

**Comment by KHeket** [comment]
I dont know the mechanic of dead body, which can be ressurected, but, if smashed and unsmashed corpses have different id (or some king of identificator, so the rot flag can be removed from unsmashed corpses
