### ISSUE TITLE
Apis drop integrated sclerotin claws

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61832]
### Describe the bug

If you kill Apis at bee hive it will drop sclerotin claws, after equip - you cant unequip it because of integrated flag
And can someone tell me how to direcly delete only this claws? Because I have long run game, and dont want to delete all items and missions by debug menu. I need to delete only this claws

### Steps to reproduce

Teleport to bee hive
Kill Apis
See sclerotin claws droped
Equip it
See, that it unequippable because of integrated flag

### Expected behavior

No integrated items drop

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 63ed2c9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Partly? confirmed? I was able to kill Apis and she did drop her claws. I had no issues removing them though.
![image](https://user-images.githubusercontent.com/84619419/197161106-f60363b1-1191-407c-bed2-e6cf0e70e15c.png)


/confirmed as there IS a bug here, just maybe not as described. The claws should not be dropping.

Likely needs a fix like #60968.

You can resolve your unable-to-drop problem by going to `data/json/items/armor/integrated.json` and removing the INTEGRATED flag from integrated_chitin3_claws. After that load your save, drop the claws, save the game again, and then re-add the flag.
