### ISSUE TITLE
Blacksmith and gunsmith won't accept merch straps or bundles.

### ISSUE THREAD

**Issue by harperers** [CleverRaven/Cataclysm-DDA#61842]
### Describe the bug

They will accept normal merch as $2.50, but straps and bundles are both treated as normal trade items.

### Steps to reproduce

1. Spawn in merch straps or bundles
2. Trade with either npc and see that they undervalue them.

### Expected behavior

merch straps and bundle should be treated as currency for them.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations]
]

**Comment by andrei8l** [comment]
Just copy the price rules from `free_merchants` to `isolated_artisans`
```diff
diff --git a/data/json/npcs/factions.json b/data/json/npcs/factions.json
index 7cc071e953..9ee4e09e97 100644
--- a/data/json/npcs/factions.json
+++ b/data/json/npcs/factions.json
@@ -343,6 +343,10 @@
         "knows your voice": true
       }
     },
+    "price_rules": [
+      { "item": "money_strap_FMCNote", "fixed_adj": 0 },
+      { "item": "money_bundle_FMCNote", "fixed_adj": 0 },
+    }
     "epilogues": [
       { "power_min": 0, "power_max": 149, "id": "epilogue_faction_isolated_road_0" },
       { "power_min": 150, "id": "epilogue_faction_isolated_road_150" }
```
Probably the same for `tacoma_commune`
