### ISSUE TITLE
Lumbermill quest "Find 6 Blankets" Broken

### ISSUE THREAD

**Issue by harperers** [CleverRaven/Cataclysm-DDA#61841]
### Describe the bug

Lumbermill faction quest "Find 6 Blankets" is uncompletable.

### Steps to reproduce

1.Start the quest
2. Bring 6 Blankets
3. He doesn't accept them.

### Expected behavior

The quest should complete after bringing him 6 blankets.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

I also tried this with quilts, since the quest mentions they are interchangeable.

**Comment by harperers** [comment]
I've been looking into this for a bit, and it turns out to be because the quest accepts multiple items through the use of `u_has_item` which means that the items have to be in your inventory to be accepted for the quest. It is not very convenient to try and fit 6 blankets in your inventory, so it should use the functionality of `MGOAL_FIND_ITEM:` of finding nearby items. I have no clue how that could accomplished for multiple potential items.

**Comment by onura46** [comment]
I was looking into this as well recently. Just by chance I watched a streamer run into the same bug, and I can confirm it. There are multiple extant missions already using this syntax that may suffer similar problems. They are: 

- MISSION_GET_DRIVEBELTS
- MISSION_LUMBERMILL_GET_6_BLANKETS
- MISSION_GET_ANTIBIOTICS
- MISSION_LEARN_ABOUT_CATTAIL_JELLY (uses `u_sell_item` to sell multiple items for credit that are _not_ exclusive like these other missions, therefore does not run into the same problems. may still not be the most graceful way to write the quest, though)
- MISSION_BUILD_CAMP_3
- MISSION_BUILD_CAMP_4
- MISSION_RANCH_DOCTOR_SUPPLIES (uses `u_consume_item` to consume multiple items that are _not_ exclusive like these other missions, therefore does not run into the same problems. may still not be the most graceful way to write the quest, though)
- MISSION_RANCH_SCRAPPER_TOOLS_FOR_SCRAP (uses `u_consume_item`, however runs the possibility of consuming multiple items that are supposed to be exclusive)

It _might_ be theoretically possible to program better checks with the use of arithmetic and EoCs, else some kind of convoluted switch-case. You might be able to pop out to dialog effects and use something like `u_bulk_donate` in the `"end"` section. I stared at the code for three hours tonight trying to make sense of it and couldn't so...

The better solution would be to either expand `MGOAL_FIND_ITEM` or make a new mission type that can accept multiple different kinds of items and increases the count with which one you donate. Call it `MGOAL_FIND_ITEM_FROM_LIST` maybe. Ideally, you could specify how many of each item you'd need (eg. NPC requires 24 eggs, but 12 chicken eggs are the size of 1 dinosaur egg or something, so you'd want to account for that).

**Comment by onura46** [comment]
Adding some more information here from Renech on the dev Discord:

> Taking a look at it, MGOAL_FIND_ITEM_GROUP needs to be taken out the back and shot. I tried tracking the blame history to find a single cause but honestly I think everyone's just avoided touching it because its a dumpster fire...

> ...missiondef.cpp does NOT like finding an `item_group` defined for the mission , its erroneously matching to item which causes the game to think its trying to load a recipe. I think that's down to the way item groups are dynamic but... ugh. Is this even worth untangling? 

`MGOAL_FIND_ITEM_GROUP` does not currently work, and it was quietly removed from a old quests in #33325.
