### ISSUE TITLE
Invisible ant lion larvae

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61856]
### Describe the bug

My character was exploring a field when when suddenly a limb was impaled by an ant lion larva. As far as I understand, magical burrowing monsters are supposed to be telegraphed by either a moving mound trail or a trap. Neither was present (I did look carefully around the area when the attack occurred, and there was nothing indicating anything being off anywhere).

### Steps to reproduce

1. Walk around on fields (?) until attacked by ant lion larva.
2. Look around to see what warning signs you had missed.
3. Find nothing.

### Expected behavior

I would expect a clearly visible trap to be present (similar to trapdoor spiders), allowing humans to stay clear of the area (or at least take a calculated risk).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 64e17c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]
+ "Mod" to disable portal storms
+ Added bare bones basecamp companion recipes
It may be relevant to mention that the tileset used was the default (Ultica)

### Additional context

It may be a case of an invisible trap field (has happened in the past for some traps around e.g. LMOEs), so it might be a tileset issue rather than a monster issue.

As an aside, the ant lion larvae would be monsters that could be made exclusive to the new sand patches, given how the real world insects have their traps in sand (and those traps are very visible).

**Comment by NetSysFire** [comment]
These larvae are actual monsters and I have seen them being spawned in terrain like underbrushes or shrubs, which hides them from you unless you are right next to their hiding place (identical to items hidden there).

Can you post a screenshot of where it happened? Just to rule out them hiding in a shrub or something.

**Comment by PatrikLundell** [comment]
Thanks for looking at it @NetSysFire.

I teleported my character back to the area. My character should have been attacked while at the northernmost of the blood stains (I fled back towards the south). Grass isn't sufficient to hide anything, so I don't see any hiding place.
![Screenshot (269)](https://user-images.githubusercontent.com/22739822/197327168-a9b47e72-51c5-4e75-a094-6af2e99db3ca.png)

I decided to make some further investigation by moving my character toward the area and suddenly was grabbed by some unrevealed source with no interrupt indication (only a grabbed symbol and a log text once NO LONGER GRABBED, which is too late to be helpful in this context), which I obviously missed, so I backed up until grabbed again:
![Screenshot (270)](https://user-images.githubusercontent.com/22739822/197327376-8450839e-65be-4f49-a625-c8217667b7cd.png)

**Comment by NetSysFire** [comment]
Hmm. Can you try giving yourself the Debug Clairvoyance and Debug Clairvoyance Super mutations? Is the larvae visible using this (press V or whatever the keybind was to look at nearby monsters and items)?

Someone on IRC once reported that fungal tendrils could pierce you through Z-levels, they discovered it in a lab while a fungal tower was above. I have a feeling the larva might be glitched into the ground or something.

If you can still not see the larva, try entering the terrain editor and see if there is indeed a trap, but afaik traps can not grab you, so I think (and hope) you will have success with the above.

>As an aside, the ant lion larvae would be monsters that could be made exclusive to the new sand patches

This is actually a nice idea. Giving them a very low density spawn would work. I'll think about this.

**Comment by PatrikLundell** [comment]
I added both mutations (the "game" was still in the background, so it's still at the position of the last image):
![Screenshot (271)](https://user-images.githubusercontent.com/22739822/197330594-f6f756d3-76b5-4d8f-8bc3-7cab258962bd.png)

As can be seen, the monster is actually there a few tiles away, but invisible:
![Screenshot (272)](https://user-images.githubusercontent.com/22739822/197330749-d65843b4-b7c7-4653-8739-a3ba8816566b.png)

**Comment by NetSysFire** [comment]
I can confirm they are invisible unless the player is literally right beside it, this may be because of the `DIGS` flag. However, they are completely immobile which makes it less of a disaster. I see multiple problems here:

- It is not communicated to the player what grabs them and if there is a message, it appears buggy.
- The point of antlion larvae is a stationary, well hidden threat. Yet it appears there is no spotting profiency for their burrows. #61845 may improve that with a field, but it needs tileset support in order to work.
- Even though it sets a trap, its main targets are not intelligent humanoid creatures but other insects or small mammals. So yes, it should be at least a bit more obvious that something is hidden there. Especially since these fellas are 106 kg and 80 L in volume.

**Comment by PatrikLundell** [comment]
- I don't believe anything should be able to grab you without being visible unless you're completely blind, so grabbing should reveal the creature. It's the same issue with the damnable trapdoor spiders: they're invisible when grabbing a companion unless you move right up to them. If such a change was made, the lack of notifications would be solved, as a monster being revealed would result in a standard monster detection warning. Strangely enough, I've seen giant worms of various kinds being visible at a range next to a road, although they were inexplicably immune to ranged weapons, so the DIGS flag might only be half the reason for the invisibility. A creature that's grabbing can't simultaneously be hidden below ground and be afforded the protection of being protected by the soil.
- I don't think #61845 would solve the detection issue, as that seemed to result in an effect only while the monster is moving, which an immobile monster isn't doing. Also, a trap ought to be detectable (and thus also possible to fail to be detected), which the graphic effect doesn't do.
- I also don't think this monster should have a long range grab. The real world insect throws sand at the ants entering their trap to cause them to slide down the slope towards them, but I don't know how you'd represent that in the game without modelling the funnel they build.

**Comment by Zireael07** [comment]
For your last point, I think an effect or trap would be enough (the funnel is effectively a trap)

**Comment by NetSysFire** [comment]
>I don't believe anything should be able to grab you without being visible unless you're completely blind

The cause for that is the long-range pull and grab:

https://github.com/CleverRaven/Cataclysm-DDA/blob/4036654162e255219d9518be844b6bd91c9ac28c/data/json/monsters/insect_spider.json#L2946-L2948

This is most definitely something that needs to be tweaked.

**Comment by anoobindisguise** [comment]
Antlions should probably spawn inside a sinkhole trap? Or would they trigger it and die to their own sinkhole

**Comment by PatrikLundell** [comment]
Without knowing, I'd guess not being affected by a sinkhole trap would require either flying or the introduction of a flag that renders the creature immune to such traps. However, I agree a sinkhole trap would be somewhat similar to how real ant lions operate.
