### ISSUE TITLE
NPC entered infinite loop

### ISSUE THREAD

**Issue by Luca-spopo** [CleverRaven/Cataclysm-DDA#61857]
### Describe the bug

```
 DEBUG    : NPC Travis 'Sixteen' Glover entered infinite loop.  Turning on debug mode

 FUNCTION : void (anonymous namespace)::monmove()
 FILE     : src/do_turn.cpp
 LINE     : 515
 VERSION  : 74abea8
```

I had given the NPC a lot of work - to sort out all the items in a large area, but it was certainly not "infinite" work

### Steps to reproduce

Load the save attached
Move rightwards towards the mansion
As you approach the mansion, this error will happen

### Expected behavior

NPC should not be in a loop

### Screenshots

n/a

### Versions and configuration

n/a

### Additional context

[New Serbia 33.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9843820/New.Serbia.33.zip)

**Comment by PatrikLundell** [comment]
/confirmed

(Using a version compiled on the 10th of October).
