### ISSUE TITLE
Support for Bionic Professions with Innawood

### ISSUE THREAD

**Issue by azraile** [CleverRaven/Cataclysm-DDA#61850]
### Is your feature request related to a problem? Please describe.

Trying to run the mods together just leads to a hard crash when I try and load the world.... which kinda sucks because I think it would be neat to run a bionic in a world with no real way to fix  bionics and only really the options to find some one that can remove them if damaged.   

Some of them would give you some advantage at the start  (particuarly the bionic prepper) but as time goes on and the bionics brake down would lead to problems....

### Solution you would like.

There is no need to add any of the items into the world though maybe making it so anyone with any surgery skill can remove bionics would be helpful.

### Describe alternatives you have considered.

Just not using them ofcorse lol

But I think they would be neat....

**Comment by GuardianDll** [comment]
Magiclysm already works with innawood
Think bionic profession has crash due the lack of map it can start the scenario

**Comment by azraile** [comment]
thats good to know will edit that part out....

Dose that mean it would be easy to add the professions to the map? O.o

**Comment by NetSysFire** [comment]
CC @Light-Wave

**Comment by Light-Wave** [comment]
I tested creating a world with both Innawood and bionic professions. I created an Bionic Athlete and didn't have any problems. I could play, load and save without crashes. Could you perhaps be a bit more specific in what you are trying to do and how it crashes?
