### ISSUE TITLE
Unwarranted "component loss" of water when crafting

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61866]
### Describe the bug

Whenever I try to craft something that uses water as a component (at least clean and salt, but probably regular as well) I'm immediately met with a message that the water has been lost, do I want to replace it? Doing so results in repeated loss of more water (I think I have eventually gotten crafting going, but I'm not sure). Reject the replacement cancels the crafting, but when I resume the 0% craft and then replace the water I succeed in "resuming" the crafting.

### Steps to reproduce

1. Store your water in clay pots and clay canning pots (may or not be relevant).
2. Craft anything you shouldn't have any problem crafting based on proficiency or skill requiring water as a component.
3. Fail and loss the water.
4. Give up.
5. Resume the crafting.
6. Accept to toss good water after the bad.
7. Succeed with your crafting.

### Expected behavior

No unwarranted losses of water.

### Screenshots

![Screenshot (273)](https://user-images.githubusercontent.com/22739822/197356739-319452e9-fc9b-4d84-ba9e-02d36759ff88.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 64e17c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]
+ "Mod" to disable portal storms
+ Bare bones basecamp companion recipes

**Comment by RenechCDDA** [comment]
/confirmed

I should have opened an issue for it when I ran into it before, but I thought "Ahh surely that wouldn't happen anywhere else".  The issue comes from any items with the type "TOOL" that have pockets (see #59539 for the same issue) The clay canning pot is defined as a TOOL with such a pocket.

Items inside such containers will be deleted when initially trying to pull them out during crafting.  Doesn't delete them when resuming the craft though.

**Comment by PatrikLundell** [comment]
Thanks @RenechCDDA. It looks like you've put in work to identify the issue, which I haven't done.

I can mention that I've encountered it for a fair while, but since it's only annoying (it's fairly easy to just clean new water passively), I hadn't bothered to make an issue for it.
