### ISSUE TITLE
`SPAWN_GROUP` spell effect doesn't work with item_group

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#61884]
### Describe the bug

`SPAWN_GROUP` spell effect doesn't work with item_group, even when the doc says the opposite

### Steps to reproduce

<details>
  <summary>1. Copypaste the json below</summary>

```json

  {
    "id": "innamagic_animsit_scroll_spawn",
    "type": "SPELL",
    "name": "Spawn Animist Scroll",
    "description": "Spawns a random animist scroll from group.",
    "valid_targets": [ "self" ],
    "min_damage": 1,
    "max_damage": 1,
    "effect": "spawn_item",
    "effect_str": "animist_scrolls",
    "shape": "blast",
    "min_duration": 17280000,
    "max_duration": 69120000,
    "flags": [ "SPAWN_GROUP", "SILENT", "RANDOM_DURATION" ]
  },
  {
    "type": "item_group",
    "id": "animist_scrolls",
    "items": [
      { "item": "spell_scroll_banishment_lesser", "prob": 100 },
      { "item": "spell_scroll_bleed", "prob": 100 },
      { "item": "spell_scroll_boneclub", "prob": 100 },
      { "item": "spell_scroll_disruption_bolt", "prob": 100 }
    ]
  }
```

</details>

2. Cast a Spawn Animist Scroll spell
3. Find it triggers error, and spawn `undefined-animist_scrolls` item

### Expected behavior

Spawn a random item from loot group
Same ability for EoC would be also good (especially good if there would be a counter to not repeat himself)

### Screenshots

 ```
DEBUG    : Missing item definition: animist_scrolls

 FUNCTION : find_template
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 2367
 VERSION  : 26a4725
```

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

**Comment by ZhilkinSerg** [comment]
Item spawn from item group was not implemented as mentioned in https://github.com/CleverRaven/Cataclysm-DDA/pull/40656. Someone is yet to do that.
