### ISSUE TITLE
Make waterwheels a power generating appliance

### ISSUE THREAD

**Issue by yoshiquest** [CleverRaven/Cataclysm-DDA#61886]
### Is your feature request related to a problem? Please describe.

Currently (assuming I haven't missed something) one is able to hook up a power generating waterwheel to a vehicle to generate power, but can't just construct it standalone right next to a river. You can even build water mills, which are very similar, but not power generating water wheels!

### Solution you would like.

Add the existing water wheel and large water wheel as buildable appliances next to the water. Pretty sure power generation can be kept the same too.

### Describe alternatives you have considered.

Continue having to make dummy vehicles I guess? But I'm pretty sure the appliance system was meant to prevent people from needing to do that....

### Additional context

This could also potentially be expanded upon with additional applications, such as an even larger appliance-only waterwheel, or even a buildable dam (might need a better simulation of water and pressure before doing that though).

**Comment by PatrikLundell** [comment]
The reason I backed off on making a waterwheel appliance when I implemented a wind turbine one is that appliances are single tile "machines", and water wheels only work when placed over flowing water. When building a water wheel "vehicle" you have to start with a tile on land that acts as an anchor, but with an appliance you'd have to somehow allow it to just magically hover over the water without any support. The back off happened when I realized the issue during testing, as I didn't find levitating machinery to be appealing.

**Comment by yoshiquest** [comment]
@PatrikLundell
Aren't there water mill constructions now though? Wouldn't it be possible to make it work similarly to those? (Haven't actually tried building a mill in game though)

**Comment by PatrikLundell** [comment]
I think there are water mill constructions (I've never build one either), but I haven't investigated how they work. They're "furniture" however, not appliances.

**Comment by kevingranade** [comment]
No apparent way forward here, needs a multi-tile appliance... somehow?
