### ISSUE TITLE
Chitin armor kit seems to have nonsensical repair/install requirements

### ISSUE THREAD

**Issue by Jerald-of-Libya** [CleverRaven/Cataclysm-DDA#61888]
### Describe the bug

Chitin armor kit (item), chitin ram , chitin plating all have wildly different repair/install costs.

Chitin ram seems to be coded as steel for some reason and needs a welder, while chitin plating seems to not need much at all to attach/repair.

See attached screenshots.

### Steps to reproduce

1. Spawn 2 chitin armor kits
2. Install 1 ram and 1 plating 
3. Notice that rams require welders, and plating has no other requirements to install
4. Hit them with a bat or something so that they're both damaged
5. Notice the odd repair costs. Chitin ram requires welder and steel, while chitin plating requires just glue/tape and no chitin.
6. Uninstall one of the parts
7. Notice the repair cost for the uninstalled armor kit. This one actually makes sense as you're using tape + chitin to actually fix the thing.

### Expected behavior

Chitin armor kits have no metal in them, so no need for welding. Also, no repairing with steel.

Chitin armor plating should also require chitin to fix instead of just glue/tape.

### Screenshots

Chitin plating repair:
![image](https://user-images.githubusercontent.com/44783693/197413694-f44bf4ef-ada4-4bf0-87eb-f6dfe3f69453.png)

Chitin plating install:
![image](https://user-images.githubusercontent.com/44783693/197416444-2c4cd415-2cd1-423a-b26a-41595fee470b.png)

Chitin ram repair:
![image](https://user-images.githubusercontent.com/44783693/197413814-9fae5f4a-c3e4-480c-9f95-3dcd0dce0475.png)

Chitin ram install:
![image](https://user-images.githubusercontent.com/44783693/197416468-76e418aa-1573-42ae-971c-3687af298cea.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.2130 (20H2)
- Game Version: cc65209 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'll most likely fix this myself. Just putting this here so I can link it on the pull request. Will probably check out the acid chitin variants as well.

Edit: Confirmed that the biosilicified chitin armor kit/ram/plating follows exactly the same trend.

**Comment by PatrikLundell** [comment]
It's not necessary to make an issue for something you intend to fix yourself, as there's nothing wrong with just a PR fixing something that's wrong. However, giving people a chance to provide input can occasionally save some work by not having to change an implementation due to comments at that stage. However, it's not uncommon for comments to not appear until the PR is submitted...

**Comment by Jerald-of-Libya** [comment]
Good points. Weird how this all works. I for one have recently done some nitpicking AFTER a PR got merged as well. 😅 

It's probably gonna take me quite a while to actually do the PR due to laziness though, so I was hoping somebody could agree/disagree with my points, or even beat me to releasing a fix.

**Comment by fairyarmadillo** [comment]
This was partially addressed here, but rams were not addressed: https://github.com/CleverRaven/Cataclysm-DDA/pull/47969

There are actually a lot of vehicle install recipes that inappropriately call for welding materials, it looks like several of the json entries were copy-pasted without anyone sanity checking the install requirements.
