### ISSUE TITLE
salt from bleach

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61897]
### Is your feature request related to a problem? Please describe.

you can easily get salt from bleach since when bleach is heated
3 NaOCl--> 2NaCl + NaClO3
with further heating
2 NaClO3 --> 2NaCl + 3O2

### Solution you would like.

a very easy recipe to get salt from bleach by simple heating

### Describe alternatives you have considered.

leaving as is.

### Additional context

worth mentioning is that sodium chlorate (NaClO3) when mixed with something like sugar becomes a viable explosive like gunpowder.

**Comment by ZhilkinSerg** [comment]
In-game bleach is probably scented.

**Comment by Kywi001** [comment]
Isn't it easier to get salt than bleach in huge quantities already?

**Comment by robotic-gamer** [comment]
> In-game bleach is probably scented.

nothing in the game suggests that it is scented, also cdda is a simplification of real life so if in game scents were an issue you would expect things like trying to make plain sugar by boiling sweet liquids or grinding candies to also be an issue due to impurities. and yet those recipes are already in game suggesting impurities can also be ignored.
Also worth mentioning is that the chemicals to make it scented are almost certainly organic compounds which can easily be burned off by heavy heating, hence even if bleach was scented simple heating would still give salt without scenting chemicals.


> Isn't it easier to get salt than bleach in huge quantities already?
in general yes but there is several fairly likely situations where it would be useful most notably is that there isn't really a early game uses for bleach but there is several for salt (except for bleached bandages, but even then boiling them is more cost effective anyway). 
more generally I think this recipe should be added because
- it takes a common chemical and turns it into a different commonly used chemical
- the recipe could be done trivially as your just heating bleach with no need to do the heating carefully since salt doesn't burn.

**Comment by ZhilkinSerg** [comment]
> also cdda is a simplification of real life

It is not.
