### ISSUE TITLE
7.62x51 blocked by car door

### ISSUE THREAD

**Issue by nopenoperson** [CleverRaven/Cataclysm-DDA#61892]
### Describe the bug

you are very very likely to get shots blocked by car  until you destroy the frame

### Steps to reproduce

![blockedbycar](https://user-images.githubusercontent.com/75625092/197490501-ed19cbb1-7b8a-4114-a199-475538202999.png)

dump mag into zombie in car

### Expected behavior

i expect this to go through a car door, through a zombie and exit out the other side of the car atleast 90% of the time

### Versions and configuration

super os 
best version of cdda

**Comment by MNG-cataclysm** [comment]
Is the car door open or closed?
