### ISSUE TITLE
more options to drop magazines after reloading

### ISSUE THREAD

**Issue by nopenoperson** [CleverRaven/Cataclysm-DDA#61894]
### Is your feature request related to a problem? Please describe.

to auto drop magazines after reloading you have to go into pocket settings and set every pocket to not allow autoinserting or something else that blacklists magazines.
![autoinsert](https://user-images.githubusercontent.com/75625092/197498776-027aa59c-4015-44e7-9da4-59bac228801e.png)

magazines dont count as containers so this option does nothing:
![dropempty](https://user-images.githubusercontent.com/75625092/197499157-dcafe362-de92-44c6-af86-ca8d9681a48f.png)

the "Unload container" function thats unbound by default also doesnt recognize firearms  as containers:
![nocontainer](https://user-images.githubusercontent.com/75625092/197499478-91471b24-9943-474b-b6d0-07262f52aa42.png)

### Solution you would like.

other simple ways to drop magazines directly from the gun to the ground.

**Comment by harperers** [comment]
perhaps the best solution to this would be to allow changing global pocket settings?

**Comment by RAldrich** [comment]
I'm not sure that forbidding pockets gets at the heart of the issue, which is that sometimes you want to do an (serious) emergency reload and don't want to take the time to stuff the mag back into your pouch.

I can't think of any other time you'd want to drop a mag on the ground. The decision point for this is when you hit the reload button, not when you're configuring your pockets and inventory settings.

**Comment by kholat** [comment]
make 2 reload buttons, 1 for quick reload the other for tactical
et voila

**Comment by RAldrich** [comment]
> make 2 reload buttons, 1 for quick reload the other for tactical
> et voila

Adding another keybind makes our already pretty bad control scheme even worse.

I think we could probably just make you automatically drop it on the ground when there is an adjacent monster (and make that a toggle in options) and call it good enough.
