### ISSUE TITLE
Relic pain modifiers aren't applied (c++ fix suggested)

### ISSUE THREAD

**Issue by Sutremaine** [CleverRaven/Cataclysm-DDA#61900]
### Describe the bug

Relics that should reduce pain don't do this.

### Steps to reproduce

Easiest with Magiclysm because you can debug yourself the Life Conversion spell and an Animist life-athame. The spell does consistent damage and therefore pain, and the knife is supposed to reduce pain while wielded. Casting Life Conversion at level 20 causes 8(?) pain without the athame, and the same with it.

To test this with pain in general and exclude Magiclysm, I gave the athame's pain-reducing capabilities to a butcher knife and modded pipe-wielding feral humans to do 10d1 damage (and have no rocks), and then checked how many strikes it took to get over 90 pain.

With no mutations, it took 13 strikes to get to 91 pain, with or without the knife. 7 pain each time.
With the Pain Resistant mutation, each strike caused 4-6 pain. With the knife, it took 19 strikes to get to 95 pain (5 average), and with no knife it took 21 strikes to get to 94 damage (4.5 average).

### Expected behavior

Relics with pain reduction should reduce pain. Stat boosts are working fine; don't know about any other relic passives.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 71bdf7b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

void Character::mod_pain( int npain ) in character.cpp checks for pain-modifying mutations and calculates the new level of pain, but it doesn't check for pain-modifying json (presumably, the check for that should go after the mutation-checking). I don't know how to write the code for that. Here's the whole thing:

```
void Character::mod_pain( int npain )
{
    if( npain > 0 ) {
        if( has_trait( trait_NOPAIN ) || has_effect( effect_narcosis ) ) {
            return;
        }
        // always increase pain gained by one from these bad mutations
        if( has_trait( trait_MORE_PAIN ) ) {
            npain += std::max( 1, roll_remainder( npain * 0.25 ) );
        } else if( has_trait( trait_MORE_PAIN2 ) ) {
            npain += std::max( 1, roll_remainder( npain * 0.5 ) );
        } else if( has_trait( trait_MORE_PAIN3 ) ) {
            npain += std::max( 1, roll_remainder( npain * 1.0 ) );
        }

        if( npain > 1 ) {
            // if it's 1 it'll just become 0, which is bad
            if( has_trait( trait_PAINRESIST_TROGLO ) ) {
                npain = roll_remainder( npain * 0.5 );
            } else if( has_trait( trait_PAINRESIST ) ) {
                npain = roll_remainder( npain * 0.67 );
            }
        }
    }
    Creature::mod_pain( npain );
}

**Comment by ZhilkinSerg** [comment]
There is code that handles various effects in a different place

https://github.com/CleverRaven/Cataclysm-DDA/blob/71bdf7b3615a48176498ef8baad7cd9886166c64/src/character.cpp#L9662-L9684
