### ISSUE TITLE
"Ran out of available textures in the pool" (replicable, with save)

### ISSUE THREAD

**Issue by Sutremaine** [CleverRaven/Cataclysm-DDA#61918]
### Describe the bug

Unskippable error when approaching leftover swarm structures and their attendant twisting blades.

Duplicate of #54088 and #58080.

### Steps to reproduce

Load save (ignore vamp mutation errors), walk south until swarm structures around the corner are well within the reality bubble.

If both of them remain, the error happens quite quickly.
If one of them is debug-killed, the other can send a few waves of blades at the local wildlife before the error happens.
If neither of them send out blades, they run out their timer and disappear normally.

### Expected behavior

No error. Or, portal storm creatures disappear immediately upon re-entering the reality bubble if it's been [their timer] seconds of non-portal-storm weather.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 71bdf7b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Xedra Evolved [xedra_evolved]
]

### Additional context

https://github.com/Sutremaine/big_save_file_01

Zip file's about 43MB, and 7z isn't supported for attachments here. Config folder added because it was requested in #54088.

**Comment by anothersimulacrum** [comment]
If this indeed has a reliablebrepro cae, could we perhaps close the others and leave this open?

**Comment by Brambor** [comment]
Closing as duplicate instead of as completed.
