### ISSUE TITLE
U.I. Lies to the player - the Activity Suit

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#61915]
### Describe the bug

Activity Suit gives 100 coverage for the whole body. If you examine it and spend about half an hour scrolling down on the [e]xamine item UI, you will reach to the part where the important details are. If you pay attention, you can see that it states the following:

- "This gear **completely protects** you from electric discharges (which is true, can confirm);
- "This clothing **completely protects** you from radiation (which, so far, seems to be true);
_- "This clothing **completely protects** you from any gas. (which is 100% false, seeing I got prompted if I wanted to step into a toxic gas tile, and I, indeed, got poisoned._ 

### Steps to reproduce

1. Create a new world in a lab or something where toxic gas is guaranteed to happen (or spawn in some bloated zombies, really). Create your average Survivor.
2. Spawn Activity Suit.
3. Spend some precious time scrolling down in order to read Activity Suit's description;
4. Step on a gas tile;
5. Notice how you get poisoned.

### Expected behavior

I would expect the UI to have the important information visible to me, as well as said information to be true and not a red herring or an outright lie.

### Versions and configuration

Windows 7
e532171
no mods worth mentioning.

### Additional context

This seems to be a recurring problem with a lot of items. Not necessarily the "misinformation", but mainly the UI being so overly bloated that it is outright uncomfortable to get any information. It is painful to wade through a menu window that features endless amounts of information that is either not explained to the player or that is poorly conveyed to the point where the player is left even more confused.

For example: 
Unexplained Information: nowhere in the game we are told what Breathability does exactly. Yes, we can discern that it has to do with sweating and stuff, but the point is: Is 30% better than 80%? Number% of what exactly, what unit is this? It's the same thing with the "protection for (body part)". What is the "red%" and the "green%"? Where in the game is this explained? Or rather, why are these values so cryptic and placed in a makeshift-columnesque way under "protection" with no further context to them? 

This then brings up yet another issue: why do we have a new line for each little inch of body? The foot arches, the pinky finger, the bottom lip, the back of the hand? Can't we just have the flat numbers for the flat limbs, if the coverage and protection values are the same? Or rather, why not have just a table with the values for that item, instead of several dozens lines per limb?

The other problem is: Why do we need half-a-screen of Ascii art to depict the coverage of an article of clothing? Everyone knows how much a pair of socks cover. And then at the bottom you have the actual information players need and want to read (does it conduct electricity? does it let water through? is it flimsy?) as well as whether it can be repaired or not and if so, how/with which items. But all of this important information is buried under so much fluff and so much bloat. 

This was mentioned by another user before and it was, seemingly, ignored. 
https://github.com/CleverRaven/Cataclysm-DDA/issues/59820

**Comment by AcidAntOnAMinefield** [comment]
If that's the case, then the UI needs revamping.  Gas and Smoke do not affect any other body parts other than the mouth. If your item has "It completely protects you from x" and it doesn't completely protect you from X, that's a problem. Don't have that flag for the item if it requires an extra component for it to be true - especially if said extra component can do exactly that without that suit. ie: the gas mask completely protects you from Gas/Smoke even if you're naked.

**Comment by Bossrman** [comment]
I previously made an issue about this (I also mentioned the other hazmat suits) the "completely protects from all gases" AFAIK ONLY protects from insecticidal gas (which is only a problem if you are insect or arachnid mutant) and does literally nothing if not also worn with a gas mask, the gas mask has minor effects when worn without a type of hazmat suit.

**Comment by bean-b** [comment]
most other environmental protection suits have a line on the end of "It requires a separate gas mask for full protection.". Seems like that could be added to the activity suit?

**Comment by AcidAntOnAMinefield** [comment]
> most other environmental protection suits have a line on the end of "It requires a separate gas mask for full protection.". Seems like that could be added to the activity suit?

This, and probably move that information to the top, because it's really, really easy to ignore it given the sheer amount of text one has to go through to find relevant information.
