### ISSUE TITLE
Locking pliers do not count as pliers, and intergrated multitool CBM does not count as Multitool to Reveal Wall Wirings

### ISSUE THREAD

**Issue by Zakastra** [CleverRaven/Cataclysm-DDA#61919]
### Describe the bug

Neither locking pliers or integrated multitool CBM can be used to Reveal Wall Wirings

### Steps to reproduce

Have locking pliers and or Integrated Multitool CBM, attempt to Construct "Reveal wall wirings" the option is not available.

### Expected behavior

Integrated Multitool CBM should be able to perform all the tasks a standard multitool should, and Locking Pliers are similar enough in size and function that they should also be able to preform this task.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA]
]

**Comment by Knut-Aage-Hofseth** [comment]
``` 
 {
    "type": "construction",
    "id": "app_wall_wiring",
    "group": "reveal_wall_wiring",
    "category": "APPLIANCE",
    "required_skills": [ [ "fabrication", 0 ] ],
    "time": "0 s",
    "qualities": [ { "id": "CUT", "level": 2 } ],
    "tools": [ [ [ "pliers", -1 ], [ "multitool", -1 ] ] ],
    "pre_flags": "WIRED_WALL",
    "pre_special": "check_no_wiring",
    "post_special": "done_wiring",
    "activity_level": "LIGHT_EXERCISE"
  },
```
The construction recipe uses a tool requirement for pliers, as there is no tool quality related to being pliers. 
Either create a tool quality for pliers and add them to the relevant tools and recipes or add the missing tools to the recipes.
