### ISSUE TITLE
focus number keep lowering when the current focus trend number is higher 

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61920]
### Describe the bug

while the focus trend number range from 50-70 (and the pain range from 19-70) for 7 hours the focus keep dropping in a fast rate

### Steps to reproduce

no idea
maybe just killing a horde of zombie and get pain level to highest redest pain level

### Expected behavior

following the focus trend

### Screenshots

![image](https://user-images.githubusercontent.com/63102395/197800559-780cedbf-0702-4811-9b72-ea111341e100.png)

### Versions and configuration

[Uploading debug.log…]()

**Comment by PatrikLundell** [comment]
Focus is lost at a high rate when training some skill(s). Killing zombies train skill(s), such as the skill of the weapon(s) used, and dodge if in melee, plus the general ranged/melee combat skill, so it drops very rapidly when fighting.

Disabling training of the skills used will block the draining of Focus (as well as any training of the skills, of course).
