### ISSUE TITLE
Advanced nomad harness dont work properly

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61926]
### Describe the bug

Advanced nomad harness cant fully protect you from simple 31°C

### Steps to reproduce

Create character with scenario - wilerness and profession - commercial cyborg to make less botton pressings. Spawn advanced nomad harnees, equip it and turn on. Set tumpature to 31°C. See, that its cant protect you from no so high temrature
Sometimes it will work properly and setting body temrature to 10°C or close to it temrature like on the third screenshot, mostly that happends, when you fully close your game and load it again, but after some time advanced nomad harness start work bad

### Expected behavior

I want properly working advanced nomad harness

### Screenshots

<details>
  <summary>Advanced nomad harness is off</summary>

![image](https://user-images.githubusercontent.com/102726167/197837971-882eba70-f0e9-485c-a420-47274d5ca2f5.png)

</details>

<details>
  <summary>Advanced nomad harness is on</summary>

  ![image](https://user-images.githubusercontent.com/102726167/197838047-51c438f8-7310-4d01-8755-4e36c7730920.png)

</details>

<details>
  <summary>Advanced nomad harness rarely working good for a short time after reloading the game</summary>

  ![image](https://user-images.githubusercontent.com/102726167/197839974-b3c5c9ef-2736-4ba8-9db8-9ae288038da8.png)

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 577ab49 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RAldrich** [comment]
I'm not sure I understand the issue. In your second and third screenshots, your body part temperatures are all well within safe ranges (anything under 70 will allow you to survive by sweating). What is going wrong?

Note, the temperatures in the "ENCUMBERANCE AND WARMTH" table are NOT degrees Celsius. They're an arbitrary transformation of the internal body heat (which is also arbitrary and not Celsius). This is a confusing and bad design IMO, but the point is that anything under 70 is "OK".

**Comment by KHeket** [comment]
> I'm not sure I understand the issue. In your second and third screenshots, your body part temperatures are all well within safe ranges (anything under 70 will allow you to survive by sweating). What is going wrong?
> 
> Note, the temperatures in the "ENCUMBERANCE AND WARMTH" table are NOT degrees Celsius. They're an arbitrary transformation of the internal body heat (which is also arbitrary and not Celsius). This is a confusing and bad design IMO, but the point is that anything under 70 is "OK".

Maybe i'm wrong, but earlier nomad harness setting bodytemprature in "@" menu to 10, also at hot weather. And I think, bionic sci-fi costume, which draining lots of energy, should protect you from 30°C-50°C, but if its ok - ok

**Comment by RAldrich** [comment]
Gotcha! I can't speak to how it used to be, but right now the suit has this attribute:

```
"has": "WORN", "condition": "ACTIVE", "values": [ { "value": "CLIMATE_CONTROL_HEAT", "add": 50 }, { "value": "CLIMATE_CONTROL_CHILL", "add": 50
```

So it is able to compensate for + or - 50 degrees C.

Note that the temperature code is **complicated**. It's pretty normal that you would warm up a bit if you're exerting yourself heavily. The suit should still help a ton, which based on your screenshots, it is.

**Comment by Knut-Aage-Hofseth** [comment]
From /src/weather.h

/**
 * @name BODYTEMP
 * Body temperature.
 * Body temperature is measured on a scale of 0u to 10000u, where 10u = 0.02C and 5000u is 37C
 * Outdoor temperature uses similar numbers, but on a different scale: 2200u = 22C, where 10u = 0.1C.
 * Most values can be changed with no impact on calculations.
 * Maximum heat cannot pass 15000u, otherwise the player will vomit to death.
 */

To me it looks like it is compensating for about 5 degrees. I get chilly at 11 C and warm at 31 C ambient. But I am very unsure about how much of this I understood when I tried to find out if this was a bug.
