### ISSUE TITLE
realistic blackpowder vs smokelesspowder damage

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61925]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/63102395/197834486-34fef364-f98c-403f-a7e4-22d448190db0.png)

### Solution you would like.

maybe buff smokelesspowder or debuff blackpowder bullet

**Comment by anoobindisguise** [comment]
"3x less powerful" is kind of meaningless. 3x less power... per grain? You'd use more grains. Muzzle energy of the lead ball? Compared to which modern bullet? Further, our gun damage is equal to the square root of the muzzle energy (usually) so "3x" may not translate directly to 3x less damage.

**Comment by kevingranade** [comment]
Insufficiently sourced. Some cartridges may be extremely space limited,  but it's a per cartridge thing, not a blanket multiplier.
