### ISSUE TITLE
Debug Spawning is broken for unknown number of Monsters

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#61928]
### Describe the bug

Attempting to test Korg's new c++ language for #59149 I discovered that debug monster spawning is broken for some of the Nether monsters at minimum.  It's impossible to spawn albino penguins and hunting horrors.   So I went and downloaded experimental from the site and it remained impossible to spawn those monsters.

### Steps to reproduce

Character.
Debug Spawn Monster - Hunting Horror
Watch nothing happen
Debug spawn Albino Penguin
Watch again
Spawn Mi-go
Mi-go is now charging you to attack

### Expected behavior

Being mauled by the other monsters I wished to test

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 577ab49 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved]
]

**Comment by RenechCDDA** [comment]
![image](https://user-images.githubusercontent.com/84619419/197853642-decb371b-accd-48c0-a2d8-b4c64d850b72.png)

Unable to reproduce. Might want to try on a perfectly fresh copy of CDDA? It is certainly a strange problem to encounter.

**Comment by GuardianDll** [comment]
/confirmed on my copy
- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

**Comment by RenechCDDA** [comment]
> It is a perfectly fresh copy of DDA lol. Are you on 64 bit mscv?

cdda-windows-tiles-x64-msvc-2022-10-25-1140.zip

Sorry, might have been too fast on the gun here. Does this require https://github.com/CleverRaven/Cataclysm-DDA/pull/59149/commits/09985e2c983070fcbdb74436e8a26bc90642ddb4 ? I was going by the game version report, and assumed it wouldn't generate the same hash (or would apply `-dirty`).

**Comment by GuardianDll** [comment]
In my case its totally crean 4 day old version, and i cant spawn them

**Comment by GuardianDll** [comment]
oh lol, i found the reason

**Comment by Maleclypse** [comment]
> > It is a perfectly fresh copy of DDA lol. Are you on 64 bit mscv?
> 
> cdda-windows-tiles-x64-msvc-2022-10-25-1140.zip
> 
> Sorry, might have been too fast on the gun here. Does this require [09985e2](https://github.com/CleverRaven/Cataclysm-DDA/commit/09985e2c983070fcbdb74436e8a26bc90642ddb4) ? I was going by the game version report, and assumed it wouldn't generate the same hash (or would append `-dirty`).

It doesn't require that.  But that's where I found it. Then tested it on https://github.com/CleverRaven/Cataclysm-DDA/commit/577ab49447a874317f47309da21776844f7bff9c [64-bit]

**Comment by GuardianDll** [comment]
they both have SUNDEATH flag, which immidietely kills them when they are on the sun
thats why Renech were able to spawn them **under the roof**

**Comment by GuardianDll** [comment]
Case closed

**Comment by Maleclypse** [comment]
Ok wow, I'm gonna make a death message for SUNDEATH lol
