### ISSUE TITLE
smokeless gunpowder crafting recipe

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61923]
### Is your feature request related to a problem? Please describe.

it's craftable in a crude form from the setting

### Solution you would like.

https://www.youtube.com/watch?v=NkcJlaXb7gw for how to make nitrocellulose dissolving it in acetone ethanol sollution

how to make acetone
![image](https://user-images.githubusercontent.com/63102395/197818420-c9ad5e6a-7a52-4737-8f9b-4fed68075edc.png)

calcium carbonate making 
![image](https://user-images.githubusercontent.com/63102395/197822713-48037aeb-d0a6-48b4-8f42-7de27933e5fc.png)

how to make calcium chloride dihydrate
![image](https://user-images.githubusercontent.com/63102395/197823189-0db42720-41c6-4b7f-8a0c-7a2fa0abd40f.png)

how to make cacl2 
![image](https://user-images.githubusercontent.com/63102395/197823346-6ca97fb8-3ff8-4ed1-aa82-e96b193d7dd3.png)
![image](https://user-images.githubusercontent.com/63102395/197823455-6067bed7-c4a6-4f0d-8bbc-f685009ea331.png)

how to make sodium carbonate
![image](https://user-images.githubusercontent.com/63102395/197823614-ae694683-6348-41e3-9e25-08aaa00becc5.png)

distilled water
![image](https://user-images.githubusercontent.com/63102395/197823811-3adeb235-39aa-4dc6-a9f2-51e0a506daac.png)

![image](https://user-images.githubusercontent.com/63102395/197829316-5d56b34f-fad4-4ef9-8890-6b5071c3f61a.png)
 
how to make ether
![image](https://user-images.githubusercontent.com/63102395/197829419-c1e8c29b-8f9d-4fc0-9e61-befab4a7f428.png)

how to make chlorine
![image](https://user-images.githubusercontent.com/63102395/197830685-1be9c524-68a3-4d43-9ccd-b7a4e5ec0f03.png)

how to make ethylene 
https://youtu.be/I-10WJ_t4NQ?t=92

how to make anhydrous ethanol 
https://youtu.be/ratR1ngcWss?t=45

how to make koh
![image](https://user-images.githubusercontent.com/63102395/197829963-4aad1aa2-c5b3-4df7-bba8-88b0bc4f5940.png)

**Comment by GuardianDll** [comment]
![image](https://user-images.githubusercontent.com/67688115/197837982-4c7f963f-6d0d-4974-8893-5bcbf03bc0a3.png)

**Comment by MNG-cataclysm** [comment]
A good home recipe is referenced on page 121 of [The Anarchist Cookbook](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxtaWNoenJ1MXxneDo1ZGFhZDZiZTIwZjQ3ZTUy)
