### ISSUE TITLE
PARROT_AT_DANGER cannot select the player as a "danger"

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61931]
### Describe the bug

Monsters with the PARROT_AT_DANGER flag can only yell their parrots at other monsters, they cannot parrot at the player.

### Steps to reproduce

1. Spawn a cunning feral. 
2. Observe that it doesn't talk.
3. Spawn a dog. 
4. Observe the cunning feral parroting at the dog.

### Expected behavior

The cunning feral should be able to parrot at the player.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1098 (21H2)
- Game Version: 577ab49 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

**Comment by pshepjr** [comment]
Thanks for opening this, I noticed this too and it is very disappointing :(
