### ISSUE TITLE
Merchant(s) / Traders need to change their items regularly

### ISSUE THREAD

**Issue by adamdeno** [CleverRaven/Cataclysm-DDA#61939]
### Is your feature request related to a problem? Please describe.

I am not 100% sure but refugee center merchant items remain till you reset the world...

### Solution you would like.

New items introduced and old items deleted.

Like lets say he has specific items for trade , maybe after a week or any specified time those items reset and new trades show up idk , shouldnt have to be super complicated.

### Describe alternatives you have considered.

idk the limitations but i think just deleting and inserting new items would work fine.

### Additional context

Again for clarification , i dont know if that feature already exists , i tried searching up trades on here and nothing showed up , and in my run i survived for 2 days where my current day is when i found the refugee center and havent progressed through the days to check on it , if its an already existing feature , i am sorry for my lack of research.

**Comment by anothersimulacrum** [comment]
This is indeed an existing feature,
