### ISSUE TITLE
Persons can be farmed for combat experience

### ISSUE THREAD

**Issue by Numbuh474** [CleverRaven/Cataclysm-DDA#61948]
### Describe the bug

Person aggression can be dropped by landing hits on them. Combining this with the portal storm enemy disappearance bug can allow a survivor to farm whatever combat skills they want on them.

### Steps to reproduce

1. Wait indoors for a portal storm.
2. During the storm once a Person has spawned go outside, fight some monsters a bit and go and back inside.
3. Wait for the storm to end. If you are still able to see Persons they will not despawn naturally.
4. Attack a Person until its aggression drops to "tracking". A fast weapon with a sweep or stunning attack works best. This is not necessary if you are able to kite or stunlock the Person but will prevent it from attacking back and disappearing.
5. Equip your weapon of choice or go unarmed and go to town on it.
6. Enjoy level 10 in combat skills.

### Expected behavior

I expect that Portal Storm monsters should disappear when the storm ends. Failing that, I expect that Persons should not be able to be engaged in combat.

### Screenshots

![image](https://user-images.githubusercontent.com/35499003/198200630-78a18a7a-048d-4555-a5fa-2997eae19a8f.png)
![image](https://user-images.githubusercontent.com/35499003/198200938-61fe958c-1147-4fe8-beef-9a1b6f17dbec.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 0.F-12130-g90e9a75e28 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by GuardianDll** [comment]
I knew it
We need a flag for monsters to prevent agression fall (or maybe we can use agression value more than 100?)
/confirmed

**Comment by GuardianDll** [comment]
Nightmare, that can't damage you
Nah, too good to be feature
