### ISSUE TITLE
Dissection ought to always progress prof_intro_biology unless the creature is completely alien

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61952]
### Is your feature request related to a problem? Please describe.

I was trying to progress Principles of Biology (= prof_intro_biology in the JSON files) by dissecting inedible monsters I needed to get rid of, but found that this did nothing. Delving into the JSON files, the reason seems to be that only some classes of creatures progress the knowledge of the basics, while others only progress dependent proficiencies. That does not make much sense to me, as anything you'd need to grasp the basics for also ought to train the basics unless the roots are twisted to the edge of recognition.

Trains the basics:
- bird.kson
- Feral_humans.json
- fish.json
- mammals.json (with no advanced proficiencies)
- mutant_mammal.json
- nether.json, (only the albino penguin)
- zanimal_upgrade.json
- zed-animal.json
- zed-classic.json
- zed-winged.json
- zed_acid.json
- zed_burned.json
- zed_children.json
- zed_command.json
- zed_electric.json
- zed_ferrous.json
- zed_lab.json
- zed_misc.json
- zed_skeletal.json
- zed_survivor.json
- zed_obsolete.json

Do not train basics:
- cyborg.json
- insect_spider.json
- mi-go.json
- nether.json (all but the albino penguin)

### Solution you would like.

Add Principles of Biology to cyborg.json and insect_spider.json.

### Describe alternatives you have considered.

Some warning text indicating you'd have to start with vertebrates before you can learn something from invertebrates, and similarly (for some reason) you'd have to start with vertebrates before trying to make sense of cyborgs.

**Comment by RenechCDDA** [comment]
It is strange to me that physiology requires *specifically non-zombie unmutated humans and only humans* to learn, given the description is "An in-depth understanding of how humans and animals operate.".

I think dissect and weakpoint proficiencies just need more PR passes over the monster files in general.

**Comment by PatrikLundell** [comment]
I agree with this additional note. Physiology ought to either apply to everything Principles of Biology applies to (after it has been added to the missing categories), or be changed into Vertebrate, Mammalian, or Primate Physiology and be applied to all the applicable creatures. In the latter case, the description ought to be changed accordingly, and additional Physiology groups be constructed unless those parts can be considered to be covered by the bird, insect, etc. specializations that currently exist.
