### ISSUE TITLE
Electrohacks disappear when they break after failing hacking

### ISSUE THREAD

**Issue by srbeets** [CleverRaven/Cataclysm-DDA#61957]
### Describe the bug

Trying to hack a gun safe using an electrohack, got a critical failure message: "Your electrohack is ruined!"
Went to find the electrohack in my inventory or the ground to repair it or retrieve the battery from it, but can't find it - appears to have been deleted

Note: when reproducing, found that I would get a 'You cause a short circuit!' message at the same time as getting the 'Your electrohack is ruined' message

### Steps to reproduce

1. Fresh character, lowest intelligence, no computer skills
2. Find safe needing hacking tool
3. Spawn electrohack, high capacity battery; load battery into electrohack
4. Use tool to hack safe until electrohack is ruined

### Expected behavior

Potential bug? With the ability to mod the electrohack, I would expect that a 'ruined' electrohack would be an unusable, but repairable or disassembleable item in your inventory that you can fix/recover resources from. At least let me recover my heavy battery from it!

On the other hand, if it is considered disposable, change the wording from 'ruined' (makes me expect a 'ruined electrohack' item) to 'breaks' to match hairpins? 
Maybe remove the ability to mod it? That made me think of it as a long-term use item

### Versions and configuration

- OS: Windows 10 x64
- Game Version 0.F-3 stable
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda

### Additional context

[Hopkinton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9882204/Hopkinton.zip)

Additional Note: found earlier bug report here: [#41544](https://github.com/CleverRaven/Cataclysm-DDA/issues/41544)
That was suggesting that electrohacks shouldn't break/get ruined anymore?

**Comment by nopenoperson** [comment]
ive extensively used this item and ive never managed to ruin one before
