### ISSUE TITLE
Island Prison A apparently floats

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#61954]
### Describe the bug

A post on the subreddit stated that the old island prison has no earth/rock underneath it. The poster wanted to dig a bunker for portal storms and found that underneath the island is submerged water. 

### Steps to reproduce

1. Spawn in a new character with the island prison challenge start, select Island A.
2. Enter construction menu, select "dig downstair."
3. Enter completed flight of stairs into the abyss below.
4. drown, probably.

### Expected behavior

There should be solid earth and solid rock underneath the island. 

### Screenshots

![image](https://user-images.githubusercontent.com/56202842/198360135-35258437-ba54-47ca-bc51-ab1e6e472483.png)
Oh joy, I can't wait to start work on my bunker-
![image](https://user-images.githubusercontent.com/56202842/198360267-93820290-a073-4ff5-91bb-7fcc3f92d5f6.png)
HRRGLBRBLRG

### Versions and configuration

- OS: Windows 10 Version 1909
- Game version: a338bfd Experimental build 2022-10-27-0619
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [
Dark Days Ahead [dda], 
No fungal growth [no_fungal_growth, 
No rail stations [no_rail_stations].
]

**Comment by MNG-cataclysm** [comment]
/confirmed

I'll get started on fixing this.

**Comment by MNG-cataclysm** [comment]
Now that I see it, a lot of lake specials float.

**Comment by Night-Pryanik** [comment]
I wouldn't call this a bug. It's just inconvenience factor. To fi this, one need to define several z-levels of land under the island with absolutely nothing of interest in them.
We just don't have a handy way to say "it's an island".

**Comment by MNG-cataclysm** [comment]
@Night-Pryanik Would defining land beneath it be an acceptable solution?

**Comment by Night-Pryanik** [comment]
Yeah.
