### ISSUE TITLE
Can't repair XX parts on vehicles

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61962]
### Describe the bug

You can no longer select XX broken parts for repair with a brand new part when previously you could repair these with a second copy of the part.

### Steps to reproduce

1. Find a vehicle with XX broken parts.
2. Attempt to (r)epair
3. find you can't select it

### Expected behavior

I should be able to repair the part like I could before without potentially having to swap everything else in the event of the frame.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 30de2d1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
IIRC that wasn't "repairing", just swapping out with less keypresses.
