### ISSUE TITLE
Persons cannot see you when you stand near certain walls.

### ISSUE THREAD

**Issue by Numbuh474** [CleverRaven/Cataclysm-DDA#61965]
### Describe the bug

Persons, which have the ability to always see the player, will be sometimes unable to do so if the player is standing next to certain walls.

### Steps to reproduce

1. Find or acquire a Person.
2. Stand next to a metal wall.
3. Marvel at the anti-psionic abilities of solid steel.

### Expected behavior

If an enemy can see you no matter where you hide, then that enemy can see you no matter where you hide.

### Screenshots

![image](https://user-images.githubusercontent.com/35499003/198525561-fb3e64b6-5829-4fd9-a968-1aa25464d4bf.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 0.F-12130-g90e9a75e28 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
Easy fix is to add `ALWAYS_SEES_YOU` to `person`
```diff
diff --git a/data/json/monsters/nether.json b/data/json/monsters/nether.json
index 43fb205b1b..18093fc7a6 100644
--- a/data/json/monsters/nether.json
+++ b/data/json/monsters/nether.json
@@ -1358,7 +1358,8 @@
       "STUN_IMMUNE",
       "WEBWALK",
       "ALL_SEEING",
-      "ALWAYS_VISIBLE"
+      "ALWAYS_VISIBLE",
+      "ALWAYS_SEES_YOU"
     ],
     "special_attacks": [
       {
```
Hard fix is to figure out what's wrong with `reachability_cache`

**Comment by GuardianDll** [comment]
It seems ALWAYS_VISIBLE flag already contain the functionality of ALWAYS_SEES_YOU, so adding a flag won't fix the issue

```c++

    if( critter.has_flag( MF_ALWAYS_VISIBLE ) || ( has_flag( MF_ALWAYS_SEES_YOU ) &&
            critter.is_avatar() ) ) {
        return true;
    }
    
```

**Comment by andrei8l** [comment]
> It seems ALWAYS_VISIBLE flag already contain the functionality of ALWAYS_SEES_YOU, so adding a flag won't fix the issue
> 
> this code is the only thing where ALWAYS_SEES_YOU is used
> 
> ```c++
>     if( critter.has_flag( MF_ALWAYS_VISIBLE ) || ( has_flag( MF_ALWAYS_SEES_YOU ) &&
>             critter.is_avatar() ) ) {
>         return true;
>     }
>     
> ```

I think you're misreading that. It says I can see you if either I have `ALWAYS_SEES_YOU` and you are the avatar, or you have `ALWAYS_VISIBLE`.

However, in this case, `ALL_SEEING` should have covered this case already because `Person` has max sight range. `reachability_cache` appears to be working correctly, so the proper fix here is to move the `ALL_SEEING` bit before the reachability cache check:

```diff
diff --git a/src/creature.cpp b/src/creature.cpp
index d2b2ddd9bd..118770248e 100644
--- a/src/creature.cpp
+++ b/src/creature.cpp
@@ -330,6 +330,13 @@ bool Creature::sees( const Creature &critter ) const
         return true;
     }
 
+    const int wanted_range = rl_dist( pos(), critter.pos() );
+
+    if( this->has_flag( MF_ALL_SEEING ) ) {
+        const monster *m = this->as_monster();
+        return wanted_range < std::max( m->type->vision_day, m->type->vision_night );
+    }
+
     // player can use mirrors, so `has_potential_los` cannot be used
     if( !is_avatar() && !here.has_potential_los( pos(), critter.pos() ) ) {
         return false;
@@ -350,13 +357,6 @@ bool Creature::sees( const Creature &critter ) const
     };
 
     const Character *ch = critter.as_character();
-    const int wanted_range = rl_dist( pos(), critter.pos() );
-
-    if( this->has_flag( MF_ALL_SEEING ) ) {
-        const monster *m = this->as_monster();
-        return wanted_range < std::max( m->type->vision_day, m->type->vision_night );
-    }
-
     // Can always see adjacent monsters on the same level.
     // We also bypass lighting for vertically adjacent monsters, but still check for floors.
     if( wanted_range <= 1 && ( posz() == critter.posz() || here.sees( pos(), critter.pos(), 1 ) ) ) {
```
It's currently only sort-of-working because the reachability cache isn't a full LOS check and returns some false positives.
