### ISSUE TITLE
Bundles of Cotton Sheets yields cotton patches when dissembled instead of sheets.

### ISSUE THREAD

**Issue by qxxt** [CleverRaven/Cataclysm-DDA#61971]
### Describe the bug

Bundles of Cotton Sheets yields cotton patches when dissembled instead of cotton sheets.

### Steps to reproduce

1. Craft bundle of cotton sheets.
2. Dissemble it.

### Expected behavior

It should yield cotton sheets, clearly.

### Screenshots

![Screenshot from 2022-10-28 17-30-05](https://user-images.githubusercontent.com/57898942/198567224-5c83cc98-5c86-4473-8d46-f70d1c2f0c96.png)

![Screenshot from 2022-10-28 17-31-52](https://user-images.githubusercontent.com/57898942/198567266-4e55388f-5026-4217-b0da-ae7adec178d3.png)

### Versions and configuration

build type: linux-tiles-sounds-x64
build number: 2022-09-25-0649
commit sha: 90fc2e4586dac617d0823438cbb2bba5dd1ad356
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/90fc2e4586dac617d0823438cbb2bba5dd1ad356

**Comment by MNG-cataclysm** [comment]
I'll fix this soon.
