### ISSUE TITLE
Pen and Notebook

### ISSUE THREAD

**Issue by ZwodahS** [CleverRaven/Cataclysm-DDA#6197]
This is a feature that is probably wanted by all hoarder.

Initially I just wanted a way to enter text in the game to keep track of what I want to do and what I have done between the different gaming session. I end up using a simple text file to do this.

However, I kind of also want to be able to know what kind of tools I already have when I loot hardware store, what kind of books I already have when I loot libraries.

So I was thinking what if we have a notebook in game, that automatically update itself when I pick up a tool, or a books.

I know we could just open a text file to manage this but wouldn't it be nice (and make sense) for there to be a book and pen to let us write things down ?

Hope this can open up some discussion.

**Comment by mugling** [comment]
Closed as over two years old and with sufficiently limited appeal so as to be unlikely to be implemented any time soon
