### ISSUE TITLE
Cannot debug mutate wings for my character

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#61986]
### Describe the bug

I can't give my character wings via the debug menu.

### Steps to reproduce

1. Make a player
2. Use the debug menu to try to give them some sort of wings (bird wings, butterfly wings, etc.)
3. The character gets wing stubs instead.

### Expected behavior

I get the mutation I actually picked.

### Screenshots

I get the threshold message in the log, indicating that I may need to be post-threshold to get these wings, but I figured the debug menu should ignore that.

![image](https://user-images.githubusercontent.com/2125926/198747575-b86b6f59-b29b-493b-97f8-7d2d7cc66120.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 0dc563e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

**Comment by GuardianDll** [comment]
It should ignore that, but it doesnt
You need to pick threshold mutation first, and then give yourself a mutation

**Comment by Venera3** [comment]
It *shouldn't* ignore that, just like it doesn't ignore trait/bionic conflicts, otherwise testing new traits becomes a crapshoot. It should probably be smart enough to thresh you on its own, though.

**Comment by MNG-cataclysm** [comment]
I think we should close this issue, since everything works as intended in regard to the debug menu.
