### ISSUE TITLE
.json Documentation

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#6198]
In https://github.com/IOSYN/Cataclysm-DDA/blob/master/data/json/overmap_terrain.json there are lines like:
"sym" : 79,

Where is the mapping between the syms and the numbers behind them? I think we might need to document that somewhere in the /docs/ directory.
##

**Comment by Leland** [comment]
Merging with #16560, which is newer but has more discussion
