### ISSUE TITLE
Every evac shelter holdout asks for cattail jellies as their intro quest

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#61987]
### Describe the bug

Every single survivor who has boarded up their evac shelter wants you to get them 80 cattail jellies. I don't wanna do that.

### Steps to reproduce

1. Make a player
2. Find an evac shelter that has a survivor (the terrain id is `shelter_X_survivor`)
3. Ask them if they need a job
4. Go get cattail jellies

### Expected behavior

I expect them to have a semi-random quest like the standard NPC you meet in an evacuee start

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 0dc563e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

It's possible this is working as intended, but it seems odd to me.

**Comment by Golfavel** [comment]
Can confirm this.

**Comment by MNG-cataclysm** [comment]
This is working as programmed, since the mission is defined as what the NPC should offer. I don't know of any way to assign random missions to static NPCs, though. If there is, we could use that for quite a few random holdouts.

**Comment by Inglonias** [comment]
Alright. So this is working as intended, though it isn't necessarily the best implementation. Since these guys aren't randomly spawned NPCs, they can't have random quests. That's good to know.

We can mitigate this issue by having different offered quests for each variant of the evac shelter, but that doesn't resolve it. I'm torn between closing this issue and starting a new one as a feature request, or just leaving this up. Hmm.
