### ISSUE TITLE
Viking Traders don't seem to know their stock

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#62001]
### Describe the bug

Found the "vikings", checked them out, talked to their trader(?) / warehouse keeper / whatever it is they do. They only show me the stuff they have on them, despite having full shelves around them. 

Completed a couple quests for them, nothing changed other than the trader being more willing to sell me the ammo to the weapon they refuse to sell me anyway(?). 

Debugged in a different world, completed all quests via that way, and they still do not show anything other than their personal inventory. 

### Steps to reproduce

1. make a world
2. debug reveal map
3. visit the "vikings" 
4. try to trade with the "warehouse manager"
5. notice they only offer you access to whatever it is they're holding.
6. debug complete all the quests for them, check their trade menu again, notice how it doesn't change in size. 
7. wonder why they have so much stuff on display if it isn't available for sale. 

### Expected behavior

I would expect the shopkeep to have access to the stuff around them. 

### Versions and configuration

Windows
Tiles
7082ac9 - 2022-10-29-0658
No particular mods.

### Additional context

I had the scrap yard guy nearby so I decided to pay him a visit and he seemed fine(?). So not sure what the deal is with the dogwhistle people.

**Comment by andrei8l** [comment]
This just needs more zones defined [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/743cc4474a1696665e1bc33a3b7a7d5c1ddee14c/data/json/mapgen/valhalla_cult/mapgen.json#L196). The existing zones aren't correct either as they're placed on top of a wall.

**Comment by MNG-cataclysm** [comment]
/confirmed

I'll start fixing that.
