### ISSUE TITLE
Blankets make sleeping uncomfortable

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#62015]
### Describe the bug

There is comfort bonus for sleeping
But, if there is blanket or sleeping bag on the tile designed for sleeping (bed, leather car seat, armchair and etc) - you loose your comfort bonus, no matter, where you sleep and how much pillows/teddybears you have

### Steps to reproduce

Teleport to house with bed
Make your character tired. Debug menu > player > edit player/npc > choose you character > set needs > set fatigue to 200
You can also spawn watermelon to eat and drink it
Repeat before sleeping for future tests

Sleep on the bed without anything
See comfort bonus
Spawn pillows and teddybear
See comfort bonus

Sleep on the bed with only blanket/sleeping bag
See no bonus
Sleep on the bed with pillowns, teddybear and blanket/sleeping bag
See no bonus

### Expected behavior

I want big bonus for sleeping under the blanket/sleeping bag with pillows and teddybear

### Screenshots

<details>
  <summary>Sleep without anything</summary>

![Снимок экрана (127)](https://user-images.githubusercontent.com/102726167/198873770-3ba5dc24-c101-44c7-9164-4b236108627b.png)
![Снимок экрана (126)](https://user-images.githubusercontent.com/102726167/198873795-50a2ce9f-7ec9-4a98-8bd6-a271865a5a62.png)
  
</details>
<details>
  <summary>Sleep with pillows and teddybear and without blanket</summary>

![Снимок экрана (130)](https://user-images.githubusercontent.com/102726167/198873670-801910b9-6df9-438f-b0db-b1cf7fb78686.png)
![Снимок экрана (129)](https://user-images.githubusercontent.com/102726167/198873669-fbd1442b-0972-44e7-bb10-33d64dce977d.png)
  
</details>
<details>
  <summary>Sleep only with blanket</summary>

![Снимок экрана (133)](https://user-images.githubusercontent.com/102726167/198873863-14a47269-06f8-4845-ae4f-d9ac4d2d2d9b.png)
![Снимок экрана (131)](https://user-images.githubusercontent.com/102726167/198873862-79ba183f-08fa-415a-aeaf-da9e17cb4d01.png)
  
</details>
<details>
  <summary>Sleep with pillows and teddybear and blanket</summary>

![Снимок экрана (122)](https://user-images.githubusercontent.com/102726167/198873881-5c269904-faf7-43af-902d-e6c1a84e5d1d.png)
![Снимок экрана (123)](https://user-images.githubusercontent.com/102726167/198873882-e312369f-2d2a-4938-a6fe-cd2f20c98061.png)
  
</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 944a61d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by KanterDev** [comment]
This doesn't seem to be working as intended, I was able to get the moral bonus with a sheet, and also able to get it with no covering while my character was "cold", but I was not able to get it at all with a blanket.

I'm not 100% sure but I suspect this has something to do with the way warmth is calculated while sleeping. If this is related to warmth maybe "got cozy" is a better way to communicate this over "got comfy"

![image](https://user-images.githubusercontent.com/89065534/198890313-c58a2e3b-2296-4813-b594-b19db4a75acb.png)
![image](https://user-images.githubusercontent.com/89065534/198890331-7c33e497-ee66-4580-b311-4c077e4b936d.png)
![image](https://user-images.githubusercontent.com/89065534/198890417-9a4f8139-53b0-4188-bec2-042b17c5d60d.png)

**Comment by KHeket** [comment]
> This doesn't seem to be working as intended, I was able to get the moral bonus with a sheet, and also able to get it with no covering while my character was "cold", but I was not able to get it at all with a blanket.
> 
> I'm not 100% sure but I suspect this has something to do with the way warmth is calculated while sleeping. If this is related to warmth maybe "got cozy" is a better way to communicate this over "got comfy"

Yeah, I tested it with sheets from windows - and got comfy bonus too
I also checked a few more blankets grass and electric blanket - no bonus
One emergensy blanket with naked chracter - yes bonus
2 or more emergensy blanket with naked chracter -  no bonus
One emergensy blanket with chracter with two jumpsuits - no bonus
I also spawned 20 sheets, and there was no bonus
