### ISSUE TITLE
Small dogs still zombify, despite ``delete`` field used in their JSON definition

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#62019]
### Describe the bug

In #61668 I made the smallest dogs not zombify. Or, well, I thought I did. The code is there, it should work. It was such a simple change I didn't even bother to test it. The problem is that now it turns out my way to remove the ``zombifies_into`` field didn't work. This was brought to light in #62008 where it turned out that ``copy_from`` and ``zombifies_into`` have a deep romance that cannot be broken by conventional means. Using ``delete`` will simply be ignored, while supposedly (I did not test that myself, however, that is what I was told is the case) setting ``zombifies_into`` to ``mon_null`` _does_ stop the zombification while not removing the warning icon on a corpse.

### Steps to reproduce

1. Find a small dog like a beagle, a chihuahua or a dachshund
2. Murder
3. Notice the revival warning icon
4. Check the code and notice that the ``zombifies_into`` should be properly removed
5. Cry

### Expected behavior

``delete`` should not randomly lose its expected functionality on just one random field. I'd hazard a guess it doing just that isn't expected considering #61668 was approved and merged.

### Screenshots

A beautiful corpse of a dachshund with a revival warning icon despite the code implying the monster shouldn't zombify.
![obraz](https://user-images.githubusercontent.com/68503002/198889451-0df38ef4-d971-4e26-9c78-8a18e05edb0a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: aa2a276 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Didn't test it but I think it'd be worthwhile to take a look at what happens whether a monster using ``copy_from`` from some other monster that zombifies has a ``zombifies_into`` defined but aimed at a different zombie. Which zombie will it revive as?

**Comment by terryjacob200** [comment]
Tested in windows-tiles-sounds-x64-2022-10-30-0948 with base DDA only.  Beagle Chihuahua Dachshund all revived.  Puppies of all did not revive.   Is that enough or should I try "delete" on other creatures?

**Comment by Karol1223** [comment]
> Puppies of all did not revive.

Puppies should be unaffected since they use ``copy_from`` the labrador puppy which in itself doesn't revive, so them not reviving is expected but honestly thank god that at least that works how its expected to work.

**Comment by NetSysFire** [comment]
`delete` does not work, but why does explicitely overwriting `zombifies_into` to `mon_null` not work either?
