### ISSUE TITLE
molle webbing and sling for Hub 01 modular defense system

### ISSUE THREAD

**Issue by Dan1ss1mo** [CleverRaven/Cataclysm-DDA#62020]
### Is your feature request related to a problem? Please describe.

I think that main feature of hub 01 modular defense system should be tactical flexability. I can't see any reason why hub can't make they're high tech armor with ability to integrate molle webbing in to it in mind. 

### Solution you would like.

 I think the best solution would ither make mds copatible with load bearing vests or to introduce special load bearing vest designed for mds specifically 

### Describe alternatives you have considered.

RAldrich offer the adding cargo module insert that would give you more carry capacity at the cost of defence. I personally do not agree that ability to attach specific pockets for you're mags, grenades,holsters to combat armor is such a luxury that would require sacrificing defence as tradeoff. Why such usefull technolgy utilized in modern military gear should not be part of super high tech 3d printed armor?

**Comment by RAldrich** [comment]
I do not like this change, and do not think it fits the faction's theme. Hub 01 armor is a prototype 3D printed out of advanced materials, and **explicitly** uses "Hub 01 proprietary connectors" to attach the parts to modular defense system. The Hub is custom building extremely high tech prototypes in a sealed off bunker, they would have zero incentive to make it compatible (they're not trying to sell or distribute it to anyone except themselves and the player).

Adding mollee webbing to all the parts would both mess with the materials in the armor and rob the armor of it's high tech, bespoke theme. It would become just another tacticool camo vest covered in pouches. I say leave it as is - it already has a great selection of pockets.

**Comment by bean-b** [comment]
I wonder if this could be a crafting recipe? Like take the existing hub01 armors and add a molle webbing to them yourself, seems something that would totally be available to a survivor with crafting abilites and doesnt violate the hub01s thoughts about prototyped armor without molle webbing? I dont know just a thought

**Comment by Dan1ss1mo** [comment]
> I do not like this change, and do not think it fits the faction's theme. Hub 01 armor is a prototype 3D printed out of advanced materials, and **explicitly** uses "Hub 01 proprietary connectors" to attach the parts to modular defense system. The Hub is custom building extremely high tech prototypes in a sealed off bunker, they would have zero incentive to make it compatible (they're not trying to sell or distribute it to anyone except themselves and the player).
> 
> Adding mollee webbing to all the parts would both mess with the materials in the armor and rob the armor of it's high tech, bespoke theme. It would become just another tacticool camo vest covered in pouches. I say leave it as is - it already has a great selection of pockets.

I doesn't nessesary want to add webbing to armor it self, just being able to wear LBV with it is more then enough. The selection of pocket's is not nearly as good as combination of what LBV, molle webbing belt and survivor rigging is offering. Yet you can't properly use any of those becouse high-tech 3d printed armor is so bulky that it covers both outer and strapped layer. If hub really prefer they property gear, nothing stops them from producing (and potentially selling to player) they own lbv and molles(with fancy hub 01 marking). The only change that would be required to implement this is to remove strapped level coverege

**Comment by Dan1ss1mo** [comment]
The protection value (mainly because of coverege) are just not good enough to justify such gear restrictions. Just good old chainmail would offer way more reliable defence pretty much all the time

**Comment by Dan1ss1mo** [comment]
> I wonder if this could be a crafting recipe? Like take the existing hub01 armors and add a molle webbing to them yourself, seems something that would totally be available to a survivor with crafting abilites and doesnt violate the hub01s thoughts about prototyped armor without molle webbing? I dont know just a thought

Not sure, as RAadrich mentioned, it is 3d printed and made of advanced materials (at least tier 3 variant) so modifying it would probably be tricky

**Comment by RAldrich** [comment]
>  The selection of pocket's is not nearly as good as combination of what LBV, molle webbing belt and survivor rigging is offering.

So why not use that combination of gear instead?

> The protection value (mainly because of coverege) are just not good enough to justify such gear restrictions. Just good old chainmail would offer way more reliable defence most the tim

That is a metagame argument. What does the armor value of chainmail have to do with anything?

> high-tech 3d printed armor is so bulky that it covers both outer and strapped layer.

It's not that it's bulky (it's not at all, it's volume is 0.25 L), it's that it's a poncho. It just happens to be a poncho that has armor inserts. [This](https://www.reddit.com/r/cataclysmdda/comments/xwp0og/hub_mercenary_gear/) is my personal favorite interpretation of what it looks like.

What's the issue with simply wearing a harness over the top and taking the associated encumbrance penalty? I understand the desire to optimize your loadout, but if there aren't downsides to making a choice then it's not really a choice.

**Comment by Dan1ss1mo** [comment]
> > The selection of pocket's is not nearly as good as combination of what LBV, molle webbing belt and survivor rigging is offering.
> 
> So why not use that combination of gear instead?
> 
> > The protection value (mainly because of coverege) are just not good enough to justify such gear restrictions. Just good old chainmail would offer way more reliable defence most the tim
> 
> That is a metagame argument. What does the armor value of chainmail have to do with anything?
> 
> > high-tech 3d printed armor is so bulky that it covers both outer and strapped layer.
> 
> It's not that it's bulky (it's not at all, it's volume is 0.25 L), it's that it's a poncho. It just happens to be a poncho that has armor inserts. [This](https://www.reddit.com/r/cataclysmdda/comments/xwp0og/hub_mercenary_gear/) is my personal favorite interpretation of what it looks like.
> 
> What's the issue with simply wearing a harness over the top and taking the associated encumbrance penalty? I understand the desire to optimize your loadout, but if there aren't downsides to making a choice then it's not really a choice.

The problem is that low encumbrance is really the only great thing about this armor. You already sacrifice protection in favour of it if you using MDF. And by taking encumbrence penalty from overlapping clothing you kill the only advantage it has. Currently all mantles are just straight up worse in terms of both utility and protection then regular heavy ballistic vest and i really don't think it should stay this way.

**Comment by Dan1ss1mo** [comment]
If the only problem is the fact that it's poncho, then i don't see anithing preventing from re-flaworing it into some kind of tunic instead. It would actualy be far more practical for combat becouse you realy don't you're clothing flailing around then you fighting

**Comment by RAldrich** [comment]
> A custom-designed poncho for the true frontier explorer, made with aramid fibers and robust ripstop nylon. Striped in brown and blue, the white seal of Hub 01 is emblazoned proudly on the front. It features several quick access pouches attached to a waist drawstring, and two waterproof dry bags for carrying liquids. It also features several tight clamps and velcro strips around the waist and shoulders; perhaps something attaches to them.

To be honest, I don't think it even needs a flavor rework. Based on the existing description I would not complain too much about removing the "strapped" layer from it.

On that note, I'm actually not sure why it has the strapped layer. In-game, I can clearly see that it does, but the JSON for it only specifies:
```
"flags": [
    "STURDY",
    "OUTER",
    "WATERPROOF",
    "VARSIZE",
    "RAINPROOF",
    "HOOD",
    "SOFT"
```

Note the absence of `BELTED`. Where is the "strapped" layer coming from?

**Comment by Dan1ss1mo** [comment]
> > A custom-designed poncho for the true frontier explorer, made with aramid fibers and robust ripstop nylon. Striped in brown and blue, the white seal of Hub 01 is emblazoned proudly on the front. It features several quick access pouches attached to a waist drawstring, and two waterproof dry bags for carrying liquids. It also features several tight clamps and velcro strips around the waist and shoulders; perhaps something attaches to them.
> 
> To be honest, I don't think it even needs a flavor rework. Based on the existing description I would not complain too much about removing the "strapped" layer from it.
> 
> On that note, I'm actually not sure why it has the strapped layer. In-game, I can clearly see that it does, but the JSON for it only specifies:
> 
> ```
> "flags": [
>     "STURDY",
>     "OUTER",
>     "WATERPROOF",
>     "VARSIZE",
>     "RAINPROOF",
>     "HOOD",
>     "SOFT"
> ```
> 
> Note the absence of `BELTED`. Where is the "strapped" layer coming from?

![image](https://user-images.githubusercontent.com/112878543/199820932-2eaa2802-0308-4116-bb6c-4ec2fe57dcaa.png)
