### ISSUE TITLE
Way to obtain Alpha samples is unreasonably awful.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#62029]
### Is your feature request related to a problem? Please describe.

While not limited to just the Prime/Elf-A mutation branch, alpha samples may just be the standout example to how limiting the new sample system can be. It can only be obtained by defeating very rare enemies that only _may_ show up in labs, with no other way to be obtained.

So, trying to cross the Prime threshold not only requires you to find the Alpha Preliminary Report - by itself an extremely rare manual that isn't guaranteed to be found even as a reward for lab finales - but you also have no way of farming for what you need.

### Solution you would like.

Allow alpha samples to be alchemized by combining regular human samples with something else, or simply replace alpha samples with human samples in the Alpha recipes.

### Describe alternatives you have considered.

Or even consider dialing back on the sample system for some branches. I understand that samples can be useful ways to specify which mutagen you're going for, I agree that it's preferable to the older days for when mutagens for animalistic mutation branches only needed generic chunks of meat as ingredients, but I don't think _every single_ branch in the game needs to narrow it down so much.

We already have human samples and purifiers, are specific "alpha" samples really necessary here? As I said, this isn't even exclusive to Prime mutants, I don't think we also need bird samples when just using bird eggs made as much sense.

**Comment by anoobindisguise** [comment]
Alpha samples are OK, in theory, but they raise a question of how the first alpha mutant was created. If you need alpha samples to make an alpha mutant, how did you get the first alpha mutant? Might be just some XEDRA magic that doesn't need explanation but it feels a little weird.

**Comment by bean-b** [comment]
Alpha primers are some of the easiest mutagens to loot, which i do think balances it out some

**Comment by cataclysmsurvivalist** [comment]
> Alpha primers are some of the easiest mutagens to loot

How and where?

**Comment by bean-b** [comment]
I find alpha primers in the locked metal rooms of labs very often, more so then other mutagens.
 However I haven't gotten a charchter up to the crafting level of mutagens so ofc my experience would be different.

**Comment by cataclysmsurvivalist** [comment]
I have played hundreds of games over the past 4 years, most of which start in labs, and I obtained prime mutagens as lab finishers exactly once.
In fact, before that game, I didn't even know alpha mutagens existed in the open world and thought you had to make them yourself.

**Comment by bean-b** [comment]
Are you playing on expiremental? I've found them not in the finals, but in the locked rooms inside of labs

**Comment by Maleclypse** [comment]
> I have played hundreds of games over the past 4 years, most of which start in labs, and I obtained prime mutagens as lab finishers exactly once. In fact, before that game, I didn't even know alpha mutagens existed in the open world and thought you had to make them yourself.

You're in the wrong labs if you are hunting for alpha in the procgen (old) labs.

**Comment by Zireael07** [comment]
Related: #54412

**Comment by RenechCDDA** [comment]
> You're in the wrong labs if you are hunting for alpha in the procgen (old) labs. There's a microlab where one in eight or so of the monsters drop alpha samples.

~~Sorry which microlab tile is supposed to be this? `mon_mutant_alpha` only spawns with a 50% chance in the firebreak tile (one of several versions) and the only other place it appears is in `GROUP_MUTANT_EVOLVED` where it has an eye-watering 1% chance to appear.~~ Okay, I've never seen the ratkin lab either. And apparently the *mouse of NEMA* drops alpha samples on dissection? Why? It has no indication that it will do so or any relation to alphas whatosever. Especially if you dissect all its friends and get nothing but rat samples *how would you possibly think this random weirdo mouse is going to drop alphas*?
