### ISSUE TITLE
`electric spinwheel` doesn't satisfy recipes that demand `spinning wheel`

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#62033]
### Describe the bug

Including `heavy duty thread`.

### Steps to reproduce

Try crafting `heavy duty thread` with an `electric spinwheel`.

### Expected behavior

Being able to.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

omg zipped save file too big can't upload

**Comment by anoobindisguise** [comment]
I did see the electric spinwheel added at the time I was adding canvas stuff but since there weren't versions of these for crafting regular thread or cotton sheets I opted to not create such versions of canvas thread and sheets, but they should definitely be there at some point.

**Comment by Night-Pryanik** [comment]
Fixed by #62331.
