### ISSUE TITLE
Hallucinated NPCs drop items which tag as 'Stolen' and delete Tamed animals from nearby zone 

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#62032]
### Describe the bug

Not sure if issue relates to #61450 or #58640 but current character does not have Kaluptic Psych as a trait but I made-consumed  food with Hallucinogenic Mushroom and the (human) NPCs that appear under the influence always drop a Lighter which when picked up; tags the item as Stolen.

And any NPCs that spawn in my Cave scenario are all deleted/replaced. Had 2x Scott Horses tamed for Milk and when the others spawned: they outright deleted my horses which even when unlocking Admin menu: they are nowhere/displaced on the map.

EDIT: Checked and found my tamed animals an entire Z level below the ground in a cave under my cave. Bizarre. 

Savegame is available to attach if needed. 

### Steps to reproduce

1. Start Innawoods w/Lonely Cave scenario.
2. Spawn tamed animals in Cave from Innawoods/Dino/MegaFauna.
3. Consume food with Hallucinogenic properties.
4. Ride out the trip with all NPCs spawning/attacking/speaking to you. Do NOT attack or interact with any of them. Keep crafting/sleeping etc.
5. Search surroundings when buff has faded. Any Human generated NPCs will drop (multiple) Lighters or clothing items. 
6. Any tamed animals sharing the Cave space will be removed to a lower/upper level.

### Expected behavior

I expect this to...not...happen I guess?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 0dc563e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna],
    DinoMod [DinoMod]
]

**Comment by AcidAntOnAMinefield** [comment]
I want to add to this that it seems on occasion it's impossible to even pick up stolen items. Be it wearing/wielding them directly or just trying to pick them up, even if you say "yes" to the prompt.

**Comment by evankimori** [comment]
Issue has not repeated itself since recent updates. Will reopen issue if it appears again.
