### ISSUE TITLE
Matchbooks/matchboxes have barter value independent of how many matches are in them

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62044]
### Describe the bug

So, while sorting out my survivor's loot, and specifically separating the "useless except for trading" items from the "completely useless" items, I happened to notice that match containers have their own value, completely independent of how many matches they contain; likewise, matches themselves have no value. This doesn't make sense, as in practical terms, what's useful for post-apocalyptic survivors is the matches themselves, not the container they come in. Even with the container having a striking surface for lighting matches, that's something you could reasonably replicate with the surface of a random rock you find on the ground.

### Steps to reproduce

1. Debug spawn matchbooks/matchboxes
2. Look at their barter value
3. Empty the spawned match containers
4. Look at their barter value again, along with the barter value of matches

### Expected behavior

I expect that value of a match container would depend on how useful it could plausibly be to a survivor, and that depends on the number of matches the container contains; the container itself is completely useless otherwise (with the possible exception of being disassembled into paper or something, but even that goes back to "you could easily just find other stuff on the ground for this exact putpose").

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 4bf0543 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Useful Helicopters Experimental [useful_helicopters],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Cooler Versatility [coolervers],
    Custom Bionics [custom_bionics],
    XEAS [XEAS],
    return_the_nut [return_the_nut],
    consume_the_nut [consume_the_nut],
    Reproduction mod [perverts]
]

### Additional context

There are other container with similar problems, where the barter value depends on the container itself, and not how useful the container can plausibly be depending on how much of the useful contents it contains (or doesn't contain). I don't have a comprehensive list of all such items, though.

**Comment by RAldrich** [comment]
As you might expect, this is because the price is set [on the container](https://github.com/CleverRaven/Cataclysm-DDA/blob/072a7a3054179f23a924134a5e6e2ef381aeb69f/data/json/items/tool/fire.json#L164) and not [on the match item](https://github.com/CleverRaven/Cataclysm-DDA/blob/c74c53e7fde4296f1d6ea020931fc0b630702008/data/json/items/ammo.json#L85-L95).

Do containers sum the value of their contents when trading? If yes, this is a simple JSON change: to keep prices the same, remove the container price and set the match price to 50 / 32 = 1.5 round up to 2.

**Comment by PatrikLundell** [comment]
As a side note, safety matches require the striking surfaces of match boxes to be lit, and virtually all matches nowadays are safety matches (they were invented 100 or so years ago). The old matches seen in cowboy movies are the older unsafe ones that can be lit at any rough surface (such as unintentionally the inside of your pocket or backpack)

**Comment by AmarinReyny** [comment]
> As a side note, safety matches require the striking surfaces of match boxes to be lit, and virtually all matches nowadays are safety matches (they were invented 100 or so years ago). The old matches seen in cowboy movies are the older unsafe ones that can be lit at any rough surface (such as unintentionally the inside of your pocket or backpack)

... Really? I could have sworn that I've personally matches being lit by striking any sort of rough surface, not just the striking surface of their container, and it didn't seem like anything was different about those matches.

Then again, my memory is shit, so... I could just be wrong.

**Comment by AmarinReyny** [comment]
> @PatrikLundell AFAIK a lot of matches sold in USA are still the older kind that can be struck against anything
> 
> European matches, on the other hand...

... That definitely would explain what I remember, then. As someone who was born into this fucked-up backwards hellhole and has since been too poor to leave, I can definitely say that "America sucks" is the explanation for a lot of things.

**Comment by PatrikLundell** [comment]
Being a European, I didn't realize the US was 100 years behind in that area as well. I guess it's great to have the freedom to accidentally set your pants on fire...

However, the items in the game are described as being the safety kind, as far as I understand from discussions about collection of red phosphorous from the striking surfaces.

**Comment by AmarinReyny** [comment]
> Being a European, I didn't realize the US was 100 years behind in that area as well. I guess it's great to have the freedom to accidentally set your pants on fire...
> 
> However, the items in the game are described as being the safety kind, as far as I understand from discussions about collection of red phosphorous from the striking surfaces.

In that case... maybe the container could still have some value, but a greatly reduced amount, while the matches themselves make up the rest?
