### ISSUE TITLE
The MSVC team recently test Cataclysm_DDA project failed to run "Cataclysm-test-vcpkg-static-Release-x64.exe" test on Windows

### ISSUE THREAD

**Issue by fangzhouxia** [CleverRaven/Cataclysm-DDA#62041]
### Describe the bug

Hi all,
Cataclysm_DDA failed to run "Cataclysm-test-vcpkg-static-Release-x64.exe" test with MSVC on windows. Could you please help look at this issue or provide some workarounds? Thanks in advance.

### Steps to reproduce

1. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
2. git clone https://github.com/microsoft/vcpkg F:\gitP\CleverRaven\vcpkg
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
4.  cd F:\gitP\CleverRaven\vcpkg
5. .\bootstrap-vcpkg.bat -disableMetrics
6. .\vcpkg integrate install
7. cd F:\gitP\CleverRaven\Cataclysm-DDA
8. mkdir build_amd64 & cd F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64
9. msbuild /m /p:Platform=x64 /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64 /t:Rebuild
10. cd F:\gitP\CleverRaven\Cataclysm-DDA
11. F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64\Cataclysm-test-vcpkg-static-Release-x64.exe

### Expected behavior

Build seccessfully

### Screenshots

None

### Versions and configuration

VS version: VS2019(16.11.20)
Operating system: windows server 2019
the commit of Cataclysm_DDA we use is 300ec6d

### Additional context

[test.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9909061/test.log)
[test.log.0.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9909063/test.log.0.log)
[test.log.2.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9909064/test.log.2.log)

**Comment by BrettDong** [comment]
You need one extra step before running the test executable:
https://github.com/CleverRaven/Cataclysm-DDA/blob/300ec6db71e2b76c6b3bca23f92d9698b57f025b/.github/workflows/msvc-full-features.yml#L169

**Comment by fangzhouxia** [comment]
@BrettDong Hi, following the steps above a new problem occurred. could you take a look at it for me? Thanks in advance.
![Capture](https://user-images.githubusercontent.com/109721669/200465551-69f8fbbd-b0ce-497b-ba71-2f98ac13050f.PNG)

**Comment by BrettDong** [comment]
> @BrettDong Hi, following the steps above a new problem occurred. could you take a look at it for me? Thanks in advance.
> 
> ![Capture](https://user-images.githubusercontent.com/109721669/200465551-69f8fbbd-b0ce-497b-ba71-2f98ac13050f.PNG)
> 
> 

You are not executing the command in PowerShell.

**Comment by fangzhouxia** [comment]
The result seems to be the same in PowerShell.
![Capture01](https://user-images.githubusercontent.com/109721669/200521032-2f4635aa-ed5c-4653-b058-e710ea05e60e.PNG)

**Comment by fangzhouxia** [comment]
@BrettDong, could you give me your steps and the version of the tool used?
