### ISSUE TITLE
Steel chain material should offer way less bash resist

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#62056]
### Describe the bug

Currently steel chains give the same ammount of bash protection as solid steel plate of the same carbon grade. This is not very realistic, chainmails are cut-resistant type of armor, and to some degree pierce-resistant, but are terrible at protecting from blunt force. 

### Steps to reproduce

Look at json of materials or at armors in game. 

### Expected behavior

Bash resist for chains eing somewhere between 2x to 4x lower. 
To compensate for that, lower a bit encumrance of most armors made from steel chains.

### Versions and configuration

300ec6d (tiles)

### Additional context

I am not sure how would this affect chainmail being too easilly damaged from blunt attacks. Person wearing chainmail would get most of the force but chainmail itself should still be resistant to ripping even from supernatural strenght punches.

**Comment by anoobindisguise** [comment]
So the one issue with this is that with the way platemail works, it is technically thin sheets of plate "floating" on top of solid chainmail instead of thicker sheets of plate with the gaps filled by chain. That will need to have a solution before chain and solid steels are given different protective values.

**Comment by bean-b** [comment]
Is there currently not a way to specify an armor has say 90% steel protection and 10% chain protection resulting in 100% protection overall? Like does armor currently have to be 100% chain and 90% steel in order to accomplish the same results?

**Comment by anothersimulacrum** [comment]
There is not a way to do that.
https://github.com/CleverRaven/Cataclysm-DDA/pull/56328
