### ISSUE TITLE
Stationary Concrete Mixer

### ISSUE THREAD

**Issue by Basher6079** [CleverRaven/Cataclysm-DDA#62058]
### Is your feature request related to a problem? Please describe.

Portable concrete mixers by default hold a medium battery. This only allows for 10 units of concrete, or 12 for high-capacity batteries. Furthermore, construction also requires charges- 1000+ for some faction camp buildings. This requires multiple mixers, battery compartment mods, etc, even if you have enough power.

### Solution you would like.

I propose adding an "Appliance" form for the concrete mixer to allow it to connect with your power grid. Then everything can be run off a single mixer without constant need to change batteries. You don't need to add a new item recipe, just a construction recipe "Place Concrete Mixer" that converts con_mix to an appliance.

### Describe alternatives you have considered.

Major Solutions:
Add an item and recipe for a stationary concrete mixer.
Add an item and recipe for a concrete mixer vehicle part.

Minor Solutions:
Change the current concrete mixer to use heavy batteries.
Change how crafting works so batteries are swapped automatically.

### Additional context

I've created a mod that does exactly what I want to do, but I don't understand Github well enough to make the change on my own.

[I've posted it here.](https://github.com/Basher6079/CDDA-Stationary_Concrete_Mixer)

**Comment by harperers** [comment]
there are so many different electrical tools that would benefit from being given this treatment- so perhaps a good solution would be an electrical item mod that allows a tool to connect to power grids?
