### ISSUE TITLE
Drill press doesn't give drilling quality

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#62053]
### Describe the bug

As title

### Steps to reproduce

Try to make a recipe that requires 'drilling X' without any other tools

### Expected behavior

That it would provide equivalent or better drilling quality as the cordless drill

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: cc65209 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    return_the_nut [return_the_nut]
]

### Additional context

Also the recipes it does work for should be using the quality instead of specifying specific drills (this appears  to be mostly the chainmail recipes and casing conversions for .460 Rowland and .380 ACP)

**Comment by BarndoBoi** [comment]
/confirmed
on version 6f0e11a 2022-11-10-1351.
