### ISSUE TITLE
Hide Bionics Sprite

### ISSUE THREAD

**Issue by Capruccino** [CleverRaven/Cataclysm-DDA#62065]
### Is your feature request related to a problem? Please describe.

The Blood Filter CBM, among many others, has very visible sprite changes on some tilesets, i'd like to have the option to have them not appear on the character.

### Solution you would like.

Add the (H)ide Sprite option to the Bionics screen, to make it in line with the mutations and armor screens.

### Describe alternatives you have considered.

Facial Distortion CBM gives the ability to hide sprites

**Comment by Maleclypse** [comment]
It doesn't appear that any of the tilesets that ship with the game display a blood filter CBM.
