### ISSUE TITLE
Nonrigid nested containers can't store picked up items

### ISSUE THREAD

**Issue by akrieger** [CleverRaven/Cataclysm-DDA#62068]
### Describe the bug

I have a high priority gallon zip plastic bag I set to accept soap. I pick up a stack of soap. The soap is instead distributed among a variety of pockets instead of the empty high priority gallon bag. I would understand if it at least partially/totally filled the bag and distributed the remainder, but none ends up in the gallon bag.

### Steps to reproduce

- Spawn a nonrigid container like a plastic zipper bag, as well as a wearable container like a backpack.
- Wear the backpack, put the plastic bag in the backpack.
- Set the priority on the bag to a high value
- (Optionally) set an item whitelist for a specific item that fits in the bag.
- Spawn soap and put it on the ground.
- Pick up the soap.

### Expected behavior

Soap goes in the plastic bag not into the backpack.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 0.F-12257-g579e201ecc-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by akrieger** [comment]
Just in case, the zip where it repros:
[soap_repro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9933409/soap_repro.zip)

**Comment by EIIKaO** [comment]
This is maybe caused by my PR( #60961 ) with incomplete.
Actually, I have already created a code that deals with the problem you mentioned.
As soon as I can confirm that there is no conflict with the current code, I would like to submit a PR for the solution.

**Comment by EIIKaO** [comment]
This image is an example of loading the save data you attached and picking up the soaps(66).
![ac](https://user-images.githubusercontent.com/109350502/199869126-30b47821-7ec7-4ef5-b13e-e3f7493057dc.png)

The reason why the zip does not contain all of the soaps is because of the loot sling capacity limitation of the zip's parent.
![ad](https://user-images.githubusercontent.com/109350502/199869143-2d1878a6-1493-4e16-ae5f-05cf88b07bde.png)
Is it as you would expect?

**Comment by akrieger** [comment]
Uhhhh. I thought it used to be in a different pocket, but possibly it was in a sub pocket of the sling. Let me test further :D 😅

**Comment by EIIKaO** [comment]
No, you are right to point out the problem.
The images above shows the attached save data loaded and picked up in my personal previous build.
If I load and pick it up with the latest release build, it does not go into the ZIP, as you pointed out, but into the other bag.

**Comment by akrieger** [comment]
Ok cool, glad you could reproduce. I also reproduced with the gallon bag inside the primary pocket of the hiking backpack with plenty of room to spare.
