### ISSUE TITLE
Crash in main menu

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#62062]
### Describe the bug

Trying to switch to `Load` in main menu in certain circumstances (see below for steps to reproduce) lead to CTD.

### Steps to reproduce

1. Have a world with at least one character in it, start playing in it, save the game, and close the game.
2. Start the game one more time.
3. Create another world, start playing in it, but don't save your character in it.  Opening tutorial is probably the easiest and fastest way to do it.
4. Close the game without saving.
5. Start the game one more time.
6. Delete the second world.
7. Try to switch to `Load`.
8. Crash.

### Expected behavior

No crash.

### Screenshots

I have this disposition:
![изображение](https://user-images.githubusercontent.com/11132525/199727609-999a2f71-9844-4298-8b3b-100bc1084f38.png)

I'm going to delete `TUTORIAL` world
![изображение](https://user-images.githubusercontent.com/11132525/199727801-0b9d4348-d941-4c4f-b907-d883379c73ef.png)

After deletion I have this disposition:
![изображение](https://user-images.githubusercontent.com/11132525/199727977-e51ca25f-b72a-42bb-aa05-5f99d3377335.png)

If I press left to go to `Load` (or use my mouse for it), I'll get crash.

### Versions and configuration

Windows 10 x64, 0.F-12232, default mods only.

### Additional context

`crash.log` ain't generated at all. `debug.log` doesn't have anything useful.

**Comment by alef** [comment]
Can't reproduce on Windows 10 x64 7fbae08ff9, both Release and Debug builds.

**Comment by Night-Pryanik** [comment]
Huh, that's strange. I can't reproduce it on my Windows 11 x64 laptop either. I'll retest it once again tomorrow on my Windows 10 x64 PC.

**Comment by Night-Pryanik** [comment]
That's REALLY weird. I got NO crash on worlds named `Helloworld`, `test_world`, `World`. I got a stable crash on `Yelvington` world name. Could you please retest with a world named `Yelvington`?

**Comment by Night-Pryanik** [comment]
If you have an **empty** `Yelvington` world, after deletion of empty `TUTORIAL` world you don't get the crash, but rather an empty menu entry like this:
![изображение](https://user-images.githubusercontent.com/11132525/202899727-f9635837-185e-46e7-ab50-cea0b9f7a206.png)

**Comment by alef** [comment]
1. I deleted two old debugs worlds from `[World]` menu.
2. I created a new default world named _Yelvington_
3. I pressed the left arrow key
4. Error caught at https://github.com/CleverRaven/Cataclysm-DDA/blob/b3b97e047a516efb6bf8939748a49b78fc516fe2/src/main_menu.cpp#L259

The STL runtime in Debug mode reports _vector subscripti out of range_.

`sub_opts` has one element but `y + sub_opt_off` is 1. It should be zero.

(from the VS 2022 Debug Immediate window)
```
y
0x00000000
sub_opt_off
0x00000001
sub_opts[0]
"<color_c_white>Yelvington (0)</color>"
    _Mypair: {_Myval2={_Bx={_Buf=0x000001cca30b8db8 "P—\v£Ì\x1" _Ptr=0x000001cca30b9750 "<color_c_white>Yelvington (0)</color>" ...} ...} }
sub_opts[1]
Array index out of bounds.
```

**Comment by EIIKaO** [comment]
I have investigated the relevant part, based on the error logs provided by alef, and it seems to be caused by an overflow in `last_world_pos` after deleting the world.

The mechanism is the last[ loaded ]world ( = the world focused by the submenu, refer to 1st screenshot ) is at the bottom in the world list, and the deleting of other worlds ( = the world above it, refer to 2nd screenshot ) causes the `last_world_pos` to overflow( I trust the words `Yelvington` is not forbidden at all ).

As a matter of fact, I can't quite understand that the relationship between `sel2` and `sub_opt_off` in code because of its complicated, but after some investigation and testing, at least the following modifications will prevent the crash I think.

```diff
diff --git a/src/main_menu.cpp b/src/main_menu.cpp
index 0822ecffeb..dc62ef6825 100644
--- a/src/main_menu.cpp
+++ b/src/main_menu.cpp
@@ -723,7 +725,8 @@ bool main_menu::opening_screen()
             } else {
                 sel1 = max_menu_opts;
             }
-            sel2 = sel1 == getopt( main_menu_opts::LOADCHAR ) ? last_world_pos : 0;
+            sel2 = sel1 == getopt( main_menu_opts::LOADCHAR ) ? std::min(
+                       world_generator->all_worldnames().size() - 1, last_world_pos ) : 0;
             on_move();
         } else if( action == "RIGHT" || action == "NEXT_TAB" ) {
             sel_line = 0;
@@ -732,7 +735,8 @@ bool main_menu::opening_screen()
             } else {
                 sel1 = 0;
             }
-            sel2 = sel1 == getopt( main_menu_opts::LOADCHAR ) ? last_world_pos : 0;
+            sel2 = sel1 == getopt( main_menu_opts::LOADCHAR ) ? std::min(
+                       world_generator->all_worldnames().size() - 1, last_world_pos ) : 0;
             on_move();
         } else if( action == "UP" || action == "DOWN" ||
                    action == "PAGE_UP" || action == "PAGE_DOWN" ||

```
Also need to be modified on mouse click and on key shortcut area.
Just for your information.

**Comment by Night-Pryanik** [comment]
I understand this is some kind of OoB stuff. What I don't understand is why it's happening only on specific world name. I tested world with names `Uelvington`, `Ye`, `Y`, `reallylongworldname` and some other - none of them didn't crash, only `Yelvington` for some reason.

**Comment by EIIKaO** [comment]
Did you **create a new world with that name**?
In my environment, I have confirmed that crashes occur ( and do not occur in builds with workarounds ) with the previously mentioned world name,` test_world`, `World`, and now `Uelvington`, `Ye`, `Y`, `reallylongworldname`( in the case of `Helloworld`, it comes on top of `Tutorial` and does not crash ).
If we had renamed the save data folder and pretend to changed the worldname, it would lose focus and thus no longer meet the crash condition( even in the method of the rename, it can crash if the character is created in that world, loaded, and only after focus is set ).

**Comment by Night-Pryanik** [comment]
> Did you create a new world with that name?

Yes, I've created world with that name several times, deleting them after each crash.

**Comment by EIIKaO** [comment]
If you create a character with one of these non-crash world names, load it after saving, delete the Tutorial and try to switch to load, does it not crash?

In my case, as mentioned, if the world name comes below Tutorial, it crashes.

**Comment by Night-Pryanik** [comment]
Heh. I opened my game with 3 worlds - 2 of them from non-crash list, 1 of them is `Yelvington`. I decided to delete all of the worlds to test the situation one more time. I deleted two of "safe" worlds, pressed left to switch to `Load`, and got this:
![изображение](https://user-images.githubusercontent.com/11132525/203552215-bc0c9dd8-0142-4c6e-b4aa-c93d2bea68b9.png)

**Comment by EIIKaO** [comment]
It looks like a buffer overrun.
I tested the same way and no such screen appeared and it crashed immediately.

It is strange that in your environment the crash.log is not created in the first place. In my case, it generates a crash.log similar to alef.

**Comment by Night-Pryanik** [comment]
> It is strange that in your environment the crash.log is not created in the first place

Maybe I'm searching it in the wrong place? It should be in `config` folder, right?

**Comment by EIIKaO** [comment]
Yes, it was in `config`.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10075841/crash.log)
