### ISSUE TITLE
Unhardcoding ``RANGED_PULL``

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#62063]
### Is your feature request related to a problem? Please describe.

Been thinking about worms lately and how fun it'd be to have different evolutionary stages have different chances to pull the player in for hugs. But that's not possible because ``RANGED_PULL`` is hardcoded. As it stands any monster using this special has the same chance to pull and that's not really ideal.

### Solution you would like.

JSONifying ``RANGED_PULL`` to allow the modification of damage, range, pull chance and possibly some other variables I'm missing that could be useful in this regard.

### Describe alternatives you have considered.

Not opening this, since JSONifying this is supposedly already on the radar. It's also entirely possible to work with what's given, it'd just be better to have this specific special be adjustable.

### Additional context

@Venera3 you asked to be pinged here so here you go

**Comment by GuardianDll** [comment]
I believe the spell of the same effect may be used for this - just make a 1 spell of a few levels, and defy different pull strength (aka damage_min and damage_max) and range (range_min, range_max), and use it
Except pull effect has some issues, it seems as best approach

**Comment by Maleclypse** [comment]
Closed by #64999
