### ISSUE TITLE
Can we just check for liquids rather than all items when deploying furniture?

### ISSUE THREAD

**Issue by JXMss** [CleverRaven/Cataclysm-DDA#62072]
### Is your feature request related to a problem? Please describe.

The method of #53724 (checking for items on tiles when placing furniture) is simple and effective, but I feel that the detection is too broad and rough(In reality, a large number of items are not crushed by the furniture and a significant proportion of the furniture has plenty of space on the side near the floor to store items.), and breaks some existing or future gameplay mechanics that will be implemented, such as simple item hiding (to avoid NPCs taking supplies at will), or using the planting system to simulate regular output actions such as beekeeping, composting or other no-agricultural actions(which would have to be directly masked by the deploy_furniture function to avoid letting the player get the seeds).
As I showed on the forum: [https://discourse.cataclysmdda.org/t/a-frustrating-update/28289](https://discourse.cataclysmdda.org/t/a-frustrating-update/28289)

### Solution you would like.

Only detect and mop up liquids when deploying furniture.

### Describe alternatives you have considered.

We can change the code
```
    if( here.has_items( pnt ) ) {
        p.add_msg_if_player( m_info, _( "Before deploying furniture, you need to clear the tile." ) );
        return cata::nullopt;
    }
```
to this
```
    if( here.mop_spills( tripoint_bub_ms( pnt ) ) ) {
        p.add_msg_if_player( m_info, _( "You moped up the spill when deploying furniture." ) );
        p.moves -= 35;
    }
```
or simply not prompted.

### Additional context

1. I can program but am not at all good at C++. But with the help of others I managed to modify it and compile it through. The game works fine and is as expected
2.  If we end up passing the request, can we add it to the code of the 0.G stable version?

**Comment by Maleclypse** [comment]
Everything that enters experimental and isn't removed goes into the next stable which in current time is the 0.G stable that hasn't been released yet.

**Comment by JXMss** [comment]
> Everything that enters experimental and isn't removed goes into the next stable which in current time is the 0.G stable that hasn't been released yet.

Glad to hear that and thanks so much for your reply. I will try to do a merger as soon as possible :)

**Comment by JXMss** [comment]
PR attempted in #62089

**Comment by JXMss** [comment]
#62089

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/a-frustrating-update/28289/2

**Comment by JXMss** [comment]
The fix PR is here, all green and waiting for a merge

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/a-frustrating-update/28289/5
