### ISSUE TITLE
Mysterious crash to desktop

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#62078]
### Describe the bug

Random crash to descop with segmentation fault text. Screenshot below. I am also playing on russian version, but I dont think that it is the reason

### Steps to reproduce

I dunno what is causing this crash, becouse always it happens accidentally. In forests, while gathering berries, in open field
 just simple walking to distination point. I dont know how to find out the reason. But in happens 5 times in this game, and lot of time in privios games

### Expected behavior

I expected no crashes and no starting again from last save point

### Screenshots

<details>
  <summary>crash screenshot</summary>

  ![image](https://user-images.githubusercontent.com/102726167/200024564-1d671c0c-af9e-4488-8b70-fa94c0072bf3.png)
</details>

And I dontknow why after each crush my character duplicates
<details>
  <summary>screenshot</summary>

  ![image](https://user-images.githubusercontent.com/102726167/200024750-65be4209-5458-4372-8eb0-abc1090692fb.png)
</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 300ec6d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9940227/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9940228/debug.log)

**Comment by NetSysFire** [comment]
Looking at crash.log it appears to be related to autosave and more specifically, it processing items in containers. Can you save manually or does it crash, too?

**Comment by KHeket** [comment]
> Looking at crash.log it appears to be related to autosave and more specifically, it processing items in containers. Can you save manually or does it crash, too?

I can save. I am playing for a long time, one time I have crash while manual saving. And there is crash messages about items in conteiners, when I am loading game after segmentation fault crash. I will try to screen them, when it happen again, and send here logs

**Comment by NetSysFire** [comment]
>And there is crash messages about items in conteiners

Sounds like some stuff got corrupted. So far it really does sound like an issue related to saving. Does this happen in a clean new world, too?

**Comment by KHeket** [comment]
> > And there is crash messages about items in conteiners
> 
> Sounds like some stuff got corrupted. So far it really does sound like an issue related to saving. Does this happen in a clean new world, too?

What do you mean by clean world?

**Comment by PatrikLundell** [comment]
Clean world = New world with a new character (so there's no existing save that may contain corruptions).

**Comment by KHeket** [comment]
> Clean world = New world with a new character (so there's no existing save that may contain corruptions).

Its always happening after some time, or I dont remember this on clean world

**Comment by KHeket** [comment]
It happend again after a long time, when I came to mass graveyard. There was no crash messages after reloading. And I also played for a long time without crashes


<details>
  <summary>Crash screenshots</summary>

![image](https://user-images.githubusercontent.com/102726167/200153303-1597ff92-4965-4bd0-a49d-73591459c565.png)

Place where the crash was. When I came here again - no problem. Manual saving is ok, no crash

![image](https://user-images.githubusercontent.com/102726167/200153472-12252814-2d2f-4817-a4b4-69f2dd470f14.png)

</details>

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9945119/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9945120/debug.log)

**Comment by mqrause** [comment]
Looks like it tries to serialize an invalid `item_location` from the pickup activity. It crashes trying to access the pockets, indicating the item doesn't exist. Not sure how that happens, though. I would have guessed it's related to #52426, but that doesn't sound too likely when it happens this regularly.

**Comment by KHeket** [comment]
Happend again while I gathering berries in new game. And also there was no crash, until I didnt wear all this (at screenshot below) stuff and went for gathering. I am now sure, but I thinh problem is in pair of drop leg pouches, becouse there was no crashes, but when I equipped them - here it is after some time. Or something else. I dont know. May be just lucky for crash
What should I do? Do you need me to still sending crash logs there with describes of situations?

<details>
  <summary>Crash screenshots</summary>

![image](https://user-images.githubusercontent.com/102726167/201194285-ddd48ede-ae2e-46a5-b930-1268e1182f2c.png)

![image](https://user-images.githubusercontent.com/102726167/201195235-5199c736-5140-4f44-b8a3-776594627e80.png)

</details>

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9984276/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9984277/debug.log)

**Comment by EIIKaO** [comment]
From the latest attached crash.log, it appears that there is a problem with the process when picking up items.
This seems a bit different from the problem expected in the earlier crash.logs.

I have tried to create a similar situation ( equipped with a large number of backpacks includes pair of drop leg pouches, wielding  body bag in my hand, and carrying items close to the weight limit ) to collect berries and other resources, but no crashes occurred.

This has already been discussed, but if you could attach a save file where the crash can be reproduced, we can do a more detailed analysis.

**Comment by KHeket** [comment]
Problem is in inability of forced reproducing. Becouse I have crash in one sutiation, and then came to this place again and make simular action (not identical, because I cant remember all steps) - and no crash. And I dont know how to find out the problem

**Comment by KHeket** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10024090/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10024091/debug.log)

Another one crash, now with crash text after loading. I will send here text on english, and screenshots on russian. Happend becouse of me trying to manualy saving. I was recording game, and show you last 15 seconds. I used . Manualy saving triggered the crash. I will try to reproduce it. So its didnt happend becouse of picking up something

<details>
  <summary>Crash message</summary>

 DEBUG    : parent location does not point to valid item

 FUNCTION : void item_location::deserialize(const JsonObject&)
 FILE     : src/item_location.cpp
 LINE     : 802
 VERSION  : 90c0612

![image](https://user-images.githubusercontent.com/102726167/202246986-3f9c407a-a53e-45ad-8715-e8adbfdc2346.png)

</details>

<details>
  <summary>Video</summary>

https://user-images.githubusercontent.com/102726167/202247654-5215d6c2-e6fb-43e2-a6b8-9aa24afe98a6.mp4

</details>

**Comment by KHeket** [comment]
Tryed to reproduce - no crash. Killed a lot of zombies standing at the place, where I saved on video, spawning quick save - no crash happend. But there was new crash message after first save. No new info in crash log, but lot  of messages in debug log. And no crash to windows, just massage in game
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10024300/debug.log)

**Comment by KHeket** [comment]
I have save file with reproducable situation, but size of it is 1.7 GB, how can I load such big file to github?

**Comment by mqrause** [comment]
You'd have to upload it to a third party site, but even then 1.7 GB is pretty insane. Maybe someone has some advice on how to shrink it down to a more manageable size.

**Comment by PatrikLundell** [comment]
Much of the time the .mm1 directory within the save can be removed from a copy of the save before that copy is zipped up. As far as I understand this directory contains the "memory" of what you've seen, which usually isn't important for bug reproduction and analysis. If that's done I'd verify the modified copy still is capable of reproducing the issue before posting it, though.

It's often possible to delete the map details of everything that's not in the immediate vicinity of the player, but that's more fiddly and first requiring figuring out "in which folder" the player currently is.

Regardless, any save manipulation should be done on a copy of the save so the original isn't harmed.

**Comment by KHeket** [comment]
> Much of the time the .mm1 directory within the save can be removed from a copy of the save before that copy is zipped up. As far as I understand this directory contains the "memory" of what you've seen, which usually isn't important for bug reproduction and analysis. If that's done I'd verify the modified copy still is capable of reproducing the issue before posting it, though.
> 
> It's often possible to delete the map details of everything that's not in the immediate vicinity of the player, but that's more fiddly and first requiring figuring out "in which folder" the player currently is.
> 
> Regardless, any save manipulation should be done on a copy of the save so the original isn't harmed.

I have deleted sounds and mm1 directory and dicrease game size to ~ 1 GB and zipped it have size of 140 MB. But for now I need to find way to overcome the github limit in 25 mb. Do somebody know a good third party site or something else?

**Comment by Zireael07** [comment]
Dropbox is one of the free sites that can comfortably store 140 MB (iirc it has 2 GB for free). MEGA is another

**Comment by KHeket** [comment]
Thx for dropbox. Here is the link to the file
https://www.dropbox.com/s/slor0fv7hvmu8ug/cdda%20%E2%80%94%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.7z?dl=0
To reproduce crash, make shure that autopickup is on, its set to F2, then go to the pile of items and see the crash. I will also attach video

https://user-images.githubusercontent.com/102726167/205385470-6adfef25-5f84-475e-a800-6a851141f6c8.mp4
