### ISSUE TITLE
稳定版自动物品分配快捷键bug Stable automatic item allocation shortcut key bug

### ISSUE THREAD

**Issue by wlxxy1** [CleverRaven/Cataclysm-DDA#62088]
![589D5C9E-F71F-4557-8691-71E511558C9B](https://user-images.githubusercontent.com/114584593/200216904-5692f1a8-eff6-4adf-9622-b0078c8fb5b0.jpeg)

![0F0C089F-47D7-4D84-8D49-54AD665B093B](https://user-images.githubusercontent.com/114584593/200216896-410d33a9-f3ef-4227-baa4-7e5d05f02b05.jpeg)
### Describe the bug

您好开发者大佬！
我在游玩cdda f3稳定版的过程中发现了一个很明显的bug比较影响游戏体验，就是物品自动分配快捷字符功能会给拾取的物品全分配同样的字符导致无法使用快捷键，不知道稳定版什么时候会更新呢，希望能够早日更新修复掉这个bug，感谢开发者！

Hello, developer boss!

In the process of playing the cdda f3 stable version, I found an obvious bug that affects the game experience, that is, the automatic allocation of shortcut characters to items will assign all the same characters to the picked up items, resulting in the inability to use the shortcut key. I don't know when the stable version will be updated. I hope it can be updated as soon as possible. Fix this bug again. Thank you, developer!

### Steps to reproduce

1、进入游戏
2、高级物品管理
3、查看物品

1. Enter the game

2. Advanced Item Management

3. View items

### Expected behavior

希望能够自动分配不同快捷键

I hope to automatically assign different shortcuts.

### Screenshots

![6116E16F-0A1A-4266-923C-DE0E163D4A2E](https://user-images.githubusercontent.com/114584593/200103989-6578873d-9288-46ff-af9b-f68f8292328e.jpeg)
![E61D72CD-9A7D-4E6C-A177-FC9F9C8C5578](https://user-images.githubusercontent.com/114584593/200103984-9e2c4b93-fd41-45e2-a9d9-8b43bc35a4b5.jpeg)

### Versions and configuration

游戏版本稳定版f3
系统win10/安卓/ios

Game version stabilized version f3

System win10/Android/ios

**Comment by JXMss** [comment]
兄弟，界面最好设置为英文，否则大多数开发者看不懂
Dude, the interface better be set to English, otherwise most developers won't be able to read it.

另外，0.F稳定版如果没有很明显的恶性bug，不会再更新了
In addition, the 0.F stable version will not be updated again without a very obvious nasty bug.

**Comment by 993499094** [comment]
Hello, player!
Please switch to English UI!
(And by the way, the 0.F-3 is very old, try get the new one!)

**Comment by PatrikLundell** [comment]
The usage of the same character for the same item in both the item at the original location and the ITEMS TO PICK UP column is not a bug. When you select 'c' to pick up it will also appear in the ITEMS TO PICK UP panel to the right with the same letter. Pressing that letter will deselect it from the set of items to pick up.

It looks like a bug that what seems like identical items (I don't know Chinese) all get the same letter, but there might be some reason for it (and I wasn't able to get the same letter assigned in my brief test with the "same" food item of different ages).

@993499094: 0.F-3 is the latest stable version, so there is no newer one to get. It's possible to switch to the latest Experimental version, but not everyone is comfortable with doing that.

**Comment by 993499094** [comment]
> 在原始位置的项目和要拾取的项目列中对相同的项目使用相同的字符不是错误。当您选择“c”来取件时，它也会出现在右侧的“要取件”面板中，并带有相同的字母。再次按下该字母将从要拾取的项目集中取消选择它。
> 
> 看起来相同的项目（我不懂中文）都得到相同的字母，这看起来像一个错误，但可能有一些原因（我无法在我的简短测试中得到相同的字母与不同年龄的“相同”食品）。
> 
> @993499094: 0.F-3 是最新的稳定版本，所以没有更新的可以获取。可以切换到最新的实验版本，但并不是每个人都愿意这样做。

The problem he encountered was:
cell phone, bough and cherries, are all [c] key
matches, plums, chamomile, are all [d] key
Repeated shortcut keys are automatically assigned.
