### ISSUE TITLE
HUGE is less penalizing than LARGE

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#62085]
### Is your feature request related to a problem? Please describe.

The mutation LARGE has the penalties of 10 torso and arm encumbrance. This is ridiculously devastating.
By comparison, HUGE has the penalties of being huge (no cars/normal clothes), slightly less HP (cancels out the HP gain from its strength so it's basically neutral), and getting tired 15% faster. It's significantly easier to be HUGE than LARGE as a result because being HUGE has no encumbrance penalties. 

### Solution you would like.

Either HUGE should also have the penalties of LARGE or only HUGE should have encumbrance penalties and LARGE should just make you tired faster, or some other solution that results in being LARGE being less strenuous than being HUGE.

### Describe alternatives you have considered.

No clue how to go about this. HUGE was also intended to (possibly) be made post-thresh only.

**Comment by Venera3** [comment]
Mid-level transitional traits being worse than the end stage is a theme in invasiver mutations - your phenotype shifted enough to be a bother but not enough for it to make sense to you, so you're debilitated until you push your way out of the uncanny valley. It's `Inconveniently` large for a reason.

With how enc scales +10 on top of whatever you're wearing won't really make that big of a difference by the time you're mutating, but that's beside the point.

**Comment by anoobindisguise** [comment]
> Mid-level transitional traits being worse than the end stage is a theme in invasiver mutations - your phenotype shifted enough to be a bother but not enough for it to make sense to you, so you're debilitated until you push your way out of the uncanny valley. It's `Inconveniently` large for a reason.

Right, though Freakishly Huge should also likely be inconvenient, right? You don't have HUGE_OK yet. I guess the question is if it should get worse before it gets better or steadily improve from that initial huge drop.
