### ISSUE TITLE
Welding kit inconsistencies

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#62082]
### Describe the bug

Currently you can combine arc welder with asbestos welding blanket to get "welding kit" that is used just like regular arc welder but can also repair tempered steel. 
This item can be used to deploy furniture-type welding kit rig. And this rig has soldering iron functions while it does not include soldering iron. 
It also cannot be installed in vehicles. As side note, just putting welding blanket into storage of vehicle welder won't help in repairing tempered steel. 

On the other side, regular "vehicle welding rig" item consists of arc welder, soldering iron, steel frame and some copper wire. And it can then be deployed as furniture or as a vehicle part. 

### Steps to reproduce

Get items described above

### Expected behavior

Include soldering iron in welding kit or remove soldering iron function from welding kit rig.

Give steel frame and copper wire requirements to both types of welding rigs or to none of them. 

Make a vehicle mounted version of welding kit rig

### Versions and configuration

a2e6920 (tiles)

**Comment by AcidAntOnAMinefield** [comment]
Welding Kit Rig shouldn't even be a thing, considering there's a Vehicle Mounted Welding Rig. There's also a Welding Component Kit, which probably should be the intended item for those weird "Welding Rigs" you mention, seeing the WCK does have a Soldering Iron component.
