### ISSUE TITLE
More ways to get welding blanket

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#62093]
### Is your feature request related to a problem? Please describe.

More and more weapons, armors ond other items are getting different steel grades, and best ones require very specific item in order to repair, an asbestos welding blanket. This is very rare item, especially in older worlds.

### Solution you would like.

1. Make refugee center trader sell it from time to time as his stock is already tool-oriented. This would help older worlds solve problem of lack of blankets. 
2. Way to craft asbestos blanket from asbestos. Then make asbestos sheets spawn in the world in some stores, at junkyards etc. 
Maybe some buildings should spawn asbestos when their roofs are destroyed or deconstructed. 

### Describe alternatives you have considered.

1. Add fiberglass welding blankets. Add fiberglass sheets. 
2. A way to mine and refine raw asbestos from earth. Probably out of scope of the game.

**Comment by Drew4484** [comment]
Fiberglass is the solution here, it's just harder to implement because there's so many uses for it that we probably need different varieties of it and sources for each of those varieties, then recipes to use those new materials.

**Comment by nopenoperson** [comment]
asbestos was a 20th century thing. should be made from other materials like carbon, kevlar, nomex, pbi and so on

**Comment by ccaviness** [comment]
I made https://github.com/CleverRaven/Cataclysm-DDA/pull/63706 which adds a makeshift welding blanket.
