### ISSUE TITLE
PC with strict humanitarian trait should not suffer morale penalty when killing zombie kids

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#62096]
### Is your feature request related to a problem? Please describe.

PC with strict humanitarian trait should not suffer morale penalty when killing zombie kids, as the trait says they are "definetly not people".

### Solution you would like.

Cancel the morale penalty when killing zombie child for PC with the strict humanitarian trait.

**Comment by Venera3** [comment]
What does "I'm not gonna eat humans but gracken are fair game" have to do with "hahah screw them kids"?

**Comment by matt32106** [comment]
Where do you read that the trait is Gracken specific?! Does it not apply to all creatures?

**Comment by AcidAntOnAMinefield** [comment]
> Where do you read that the trait is Gracken specific?! Does it not apply to all creatures?

The trait is in relation to eating, not killing. 
If you do not want to have the morale penalty for killing kids, start with Psychopath.
Yes, morale penalty for killing Zombie Children is stupid, but it is what it is, it's easy to deal with anyway.

**Comment by Zireael07** [comment]
> The trait is in relation to eating, not killing.

Oooh. That's not called out clearly enough, I was confused a bit too

**Comment by AcidAntOnAMinefield** [comment]
I agree and think the Trait Name is strange, however, I do think the description is clear enough as it says;

> (...) Therefore it's okay to **eat them**, right?

**Comment by matt32106** [comment]
The trait says that the PC considers things that look vaguely human from elsewhere are  definetly not people. I understand that as being all zeds & humanoid monsters. Is this a wrong assumption? If I am wrong maybe the description could more clear and if I am right then it would only be logicial that if you do not consider z kids as people you shouldn't get the morale penalty.

**Comment by Zireael07** [comment]
@AcidAntOnAMinefield I am kinda with Matt here on "not consider them people = no morale penalty" though

**Comment by Venera3** [comment]
It applies to demihumans - as in nether creatures or Magiclysm lizardfolk and the like.

**Comment by Zireael07** [comment]
@Venera3: That's even LESS clear than the fact it only applies to eating

**Comment by AcidAntOnAMinefield** [comment]
@Zireael07 OK here's the entire description of the trait:

> You're convinced that these things **that look vaguely human from elsewhere** are definitely not people. **Therefore it's okay to eat them**, right?

"From elsewhere" ie not earth. The Zombies are dead people - they don't look "vaguely human", they look entirely human, except they're rotting. If you've ever seen a dead person or a decomposing corpse, they don't stop looking human. 

I honestly am unsure how this is "less clear" when it is laid out surprisingly well in the description, but if this is an issue, it's probably better to not have flavoured descriptions of things and change them all to technically accurate descriptions.

**Comment by Zireael07** [comment]
"Eat them" is clear now that I have the whole description, but "from elsewhere" isn't. 

We probably can rewrite the elsewhere bit to mention "alien" or "mi-go" or something, right?

**Comment by AcidAntOnAMinefield** [comment]
I can see why in that regard, although given CDDA has become this mishmash soup of "every game thing ever done into one", everytime I see something that makes reference to something being from "somewhere", that's where my mind goes: "oh not from earth, got it." But yeah. It could be clearer.
