### ISSUE TITLE
Dinomod locks base game mutations behind Dinomod-specific thresholds

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62097]
### Describe the bug

Dinomod changes the "horns" mutations and their subsequent upgrades from the base game to make them require threshold mutations that aren't in the base game, preventing characters who previously would have been able to get them from getting them without going with one of the Dinomod thresholds.

### Steps to reproduce

1. Make a world with Dinomod enabled
2. Play in said world
3. Try to get horns without also having Dinomod-specific threshold mutations
4. Fail
5. Lament the fact that cow mutants can't get horns any more

### Expected behavior

I expect to be able to use Dinomod without locking other mutant types out of getting horns

### Versions and configuration

OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/4bf05439a172529647ca4f41fbe7085f74edb6c1 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
C.R.I.T Expansion Mod [crt_expansion],
<color_light_blue>BL9-100%-monster-resilience-version [BL9_100monres],
<color_light_red>Secronom [secronom],
<color_light_red>Secronom+ Lore Expansion [secronom_lore_expansion],
Aftershock [aftershock],
Arcana and Magic Items [Arcana],
Blaze Industries [blazeindustries],
Magiclysm [magiclysm],
Xedra Evolved [xedra_evolved],
DinoMod [DinoMod],
Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
Extra Mutated Scenarios [extra_mut_scens],
Mythical Martial Arts [MMA],
Translate Complex Dialogue [translate_dialogue],
Magiclysm No Class Limit [magiclysm_no_class_limit],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills],
Tamable Wildlife [Tamable_Wildlife],
Useful Helicopters Experimental [useful_helicopters],
Arcadia Mapgen [custom_arcadia_mapgen],
Cooler Versatility [coolervers],
Custom Bionics [custom_bionics],
XEAS [XEAS],
return_the_nut [return_the_nut],
consume_the_nut [consume_the_nut],
Reproduction mod [perverts]
]

### Additional context

After looking through the files, it looks like this is a result of trying to extend the mutations to include Dinomod-specific threshold requirements, when the mutations in question never had any threshold requirements in the first place. Should be a simple fix.

**Comment by LyleSY** [comment]
Sure does and not intended
