### ISSUE TITLE
When you smash a zombie, gear around should have a chance to get filthy

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#62095]
### Is your feature request related to a problem? Please describe.

When you smash a zombie, gear around should have a chance to get filthy.

When I see this kind of carnage: https://imgur.com/Q2ANTG6.png I have trouble imagining my PC using the kitchen tools as if they were clean.

### Solution you would like.

When zombie are S'd blood is sent around, in the squares where this happens, each object should get a chance to get the filthy attribute. The "chance" of this happening could be an option. 

### Describe alternatives you have considered.

None

**Comment by TheShadowFerret** [comment]
>The "chance" of this happening could be an option.

Physics of gore flying doesn't refuse to apply based on a whim, I think it should be mandatory 😈

**Comment by matt32106** [comment]
What I meant with this "option" is that the "get filthy %" for each object could be tuned up&down with a parameter, 0 would cancel the effect and 100% would mean that all objects in the square would get filthy, x% = each object has a x% chance of getting filthy.

**Comment by fairyarmadillo** [comment]
Waterproof clothing could protect items worn in lower layers on the same bodypart from this effect.

**Comment by matt32106** [comment]
> Waterproof clothing could protect items worn in lower layers on the same bodypart from this effect.

I was not even thinking about the PC's gear but this is a good addition I think.

**Comment by Kywi001** [comment]
Making everything clean filthy around you when smashing zombies (including worn items), should make the squeamish trait even more of a challenge.

like make a player with squeamish trait get morale penalty and other penalties when the clothes gets filthy and if the player doesnt take the filthy clothes, it auto unequips said clothing part.

**Comment by kevingranade** [comment]
Filthy isn't a little splash of blood, it's caked on rotting blood and viscera from being worn by a literal walking corpse.

**Comment by Zireael07** [comment]
Doesn't blood and viscera happen when smashing a zombie to pulp, though?
