### ISSUE TITLE
Holstering V29 laser pistol in harness causes unskippable black screen/crash

### ISSUE THREAD

**Issue by AR700SAW** [CleverRaven/Cataclysm-DDA#62103]
### Describe the bug

Holstering the V29 laser pistol (with or without weapon mods, with or without bionic energy in reserve) in the survivor harness or nomad harness' holsters causes a black error screen (that you cannot press space to skip) when you next press (w)ield ('error: contents has no pockets')

### Steps to reproduce

1. Make new character
2. Use debug menu to spawn in a survivor harness or nomad harness & a V29 laser pistol
3. Wield then holster the laser pistol in a harness' holster
4. Press (w)ield again & black error should occur

### Expected behavior

Expected to holster & unholster laser pistol without issue. Seems to work fine for ballistic guns

### Screenshots

![Black screen error image](https://user-images.githubusercontent.com/117548220/200146291-387e986a-6354-4d28-8deb-b53df1c39c14.png)

### Versions and configuration

    OS: Windows
        OS Version: 10.0.22621.674 (22H2)
    Game Version: bd17c48 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
    ]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9944866/debug.log)

**Comment by RenechCDDA** [comment]
/confirmed

This produces a debug message for me. It does not prevent ignoring the error, nor does it crash. The provided debug log does appear(?) to indicate a crash. The debug message seems to repeat indefinitely until you choose to (i)gnore it, which for many people would be the same as crashing.

https://github.com/CleverRaven/Cataclysm-DDA/blob/66f52ce4a7d40bf4afb4091070761c5d53dcbb96/src/item.cpp#L11004

Changing this ammo check to `ammo_remaining() > 0` appears to resolve the problem. The laser pistol appears to contain **-1** ammunition, a value that often stands in for infinite values.
