### ISSUE TITLE
Bloodless monsters can still get bled by butchery, leave blood splatter on ranged hits

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#62113]
### Describe the bug

Monsters with `bleed_rate 0` like late-stage zombies can still be bled on butchery, and leave blood splatters when hit by ranged attacks.

### Steps to reproduce

1. Spawn and kill a skeletal juggernaut
2. Butcher and bleed it to see it somehow still has blood
3. Spawn another and shoot at it with a big gun
4. Behold glorious blood splatters

### Expected behavior

Non-bleeding monsters not having blood, preferably *without* having to explicitly define separate `_no_blood` harvest lists.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 0.F-12281-gac5fe8ca5b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Standard combat test suite [standard_combat_test]
]

### Additional context

Mostly as a reminder for myself to take care of it sometime, but a good first C++ issue in any case.

**Comment by alef** [comment]
✋ I would like to work on this.
