### ISSUE TITLE
aftershock: makeshift rail rifle excessively short length

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#62116]
### Describe the bug

the makeshift rail rifle only has a length of 14cm. by comparison the 9mm handgun the "glock 17" has a length of 23.3cm.

### Steps to reproduce

look at the length of a makeshift rail rifle

### Expected behavior

the makeshift rail "rifle" being long like a rifle and not be shorter than most pistols

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/200192125-f4bc55a3-2f9a-48d3-b5a0-433330f465e8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex]
]

### Additional context

fun fact if you mod a makeshift rail rifle with a folding stock then fold it the length statistic goes away. I actually think that its length is now negative because it will refuse to be put in any container (note all containers seem to have a minimum accepted length, with containers that would logically only have a maximum length just using 0 as the minimum accepted length).
edit: just noticed that this gun also has 0 recoil, despite how fast it fires ammo out.

**Comment by ERRORCODE509** [comment]
> just noticed that this gun also has 0 recoil, despite how fast it fires ammo out.

In it's defence, a railgun theoretically shouldn't have recoil.

**Comment by Profugo-Barbatus** [comment]
That's not true - Railguns don't magically cheat physics. The recoil forces are applied a bit different in an electromagnetic weapon, but the thing as a whole is going to push back with equal and opposite force to the shot. And at a damage well in excess of 7.62x51 I'd expect similar or greater kinetic energy, so it should kick pretty hard. Random steel rod isn't gonna make for a more damaging projectile, its gonna be making up for it with sheer mass.

Considering the damage it does and description of accelerating to the point of combustion of metal, its gotta have some mighty long rails, even with aftershock shenanigans.

**Comment by ERRORCODE509** [comment]
Apologies, should have said it wouldn't have _much_ recoil. Yes, the force will be the same, but it's the impulse that's different. To quote a user on Reddit who can explain better than myself:

> Looking strictly at energy input, the recoil will be almost the same. The difference is impulse. The force that drives the projectile in a traditional gun is delivered in a very short time and generates a large force over a very short time. The railgun will generate a smaller force over a longer period of time, resulting in less "recoil" like you might imagine, but generating the same force over the longer time.

So yes, force-wise the recoil is about the same. In practice, however, the recoil felt by the user will be significantly lower than an equivalent force from a conventional firearm. The recoil of a weapon of this type would be significantly easier to control due to the lower impulse.

**Comment by aaronstevenson408** [comment]
[https://www.aliexpress.us/item/2251832758905847.html](url) this might be close to what they are imagining in the description , maybe some stats that might be useful in the description

**Comment by aaronstevenson408** [comment]
So if we imagine that this is a railgun that is shooting rebar , as seen in the original commit #42395, it is shooting rebar so my last comment is not correct on that toy shooting a projectile. however after looking into it rebar weighs much less than steel round of similar sizes. looking into the codebase (i will be opening another issue with projectile weight in mind) , so maybe we should use rebar_rail as the main projectile or add that projectile to the list of acceptable ammo that can be fired and we need to add a definite length to it using "longest_side":   but until we figure out the length of the metal rail projectiles we cannot know the length of the gun.

**Comment by aaronstevenson408** [comment]
Also this makeshift weapon is half the volume of the hk_g80 and around the same weight which may have to be fixed.
