### ISSUE TITLE
Inconsistencies with detailed protection info screen

### ISSUE THREAD

**Issue by bean-b** [CleverRaven/Cataclysm-DDA#62126]
### Describe the bug

1. The protection screen doesn't include protection from inserted armor. I.e. I should have 2 protection on my eyes and my mouth from the plastic face shield, but instead it shows I have 0 protection (and 0 encumbrance) 

2. Additionally, the max possible protection values combine layers which cannot be combined. For example, it says i have 30 maximum protection because both the cataphract armor and leggings both cover the legs, but sense they dont overlap over any specific body parts, the maximum actual protection value is 15.

### Steps to reproduce

1. Wear armor that either has protective inserts, and observe the incorrect protection and encumbrance values.
2. Wear armor that doesnt overlap in specific body parts, but overlaps in larger body parts, and observe incorrect protection values.

### Expected behavior

1. I expect the encumbrance and protection values for my face shield to be repersented
2. I expect the maxmimum protection value to be 15, not 30.

### Screenshots

**1**

![Screenshot_20221107_035204](https://user-images.githubusercontent.com/84480476/200423659-973c7cd8-5ca4-458f-954c-237180692aff.png)

![Screenshot_20221107_035613](https://user-images.githubusercontent.com/84480476/200423799-fc8cf5a1-73d3-4e59-ac19-a3756fe71987.png)

![Screenshot_20221107_035707](https://user-images.githubusercontent.com/84480476/200423960-4ea9ae7b-940c-46ef-ab3d-19fe4678545d.png)

![Screenshot_20221107_040731](https://user-images.githubusercontent.com/84480476/200425662-01f142a5-442f-49a9-88fd-96d657e8ecb7.png)

**2**

![Screenshot_20221107_035759](https://user-images.githubusercontent.com/84480476/200424219-7066d7f9-2d43-4374-8346-ad86c6343b0c.png)

![Screenshot_20221107_040621](https://user-images.githubusercontent.com/84480476/200425491-c5238acc-f6b9-4b48-9b65-4a55e5a3ec36.png)

![Screenshot_20221107_040635](https://user-images.githubusercontent.com/84480476/200425526-20661195-596b-48a3-aa07-63dc02e17b3e.png)

![Screenshot_20221107_040649](https://user-images.githubusercontent.com/84480476/200425552-e46ffeb6-6579-40e8-a6ae-2d578a784c68.png)

![Screenshot_20221107_040705](https://user-images.githubusercontent.com/84480476/200425605-68d493a2-913b-4a6b-97ee-09dbdc9ae93d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.674 (22H2)
- Game Version: f8e17c4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Minor nitpick regarding the error description: The last "word" of point 2 of the description should presumably be 15 as per the expected behavior entry (you can edit the report to correct it).

**Comment by bean-b** [comment]
yep, fixed

**Comment by sunrosa** [comment]
This appears to still be a problem in 0.H Stable Candidate 2024-09-01-2220
