### ISSUE TITLE
unable to repair my car

### ISSUE THREAD

**Issue by hunjixin** [CleverRaven/Cataclysm-DDA#62137]
### Describe the bug

left some part unable to repair, when i click r but tell me there is no damaged part

### Steps to reproduce

not sure how to  reproduce but i try many experimental version

### Expected behavior

shoud repair the damaged part or i may lost my car

### Versions and configuration

build type: linux-tiles-x64
build number: 2022-11-08-1137
commit sha: b26a1e8b2b89ae8ef8c508c68a7ff3b1da081986
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/b26a1e8b2b89ae8ef8c508c68a7ff3b1da081986

i met this issue in windows and then i move this save to linux mint also not working (upgrade to newer version

**Comment by casswedson** [comment]
from #52744 tl;dr you can't repair vehicle parts under certain circumstances; you can't just bring it back to new from a super damaged state

**Comment by RenechCDDA** [comment]
Please provide a reproduction save or at least images. Parts are meant to be unrepairable if they've degraded enough (#52744), which I assume is what is happening in your circumstance.

**Comment by hunjixin** [comment]
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9969556/save.zip)
@RenechCDDA

**Comment by hunjixin** [comment]
@casswedson  yes,  you are right
