### ISSUE TITLE
ability to treat monster wounds

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#62141]
### Is your feature request related to a problem? Please describe.

Currently hurt pets and mounts slowly regenerate health, but if they are bleeding or just not healing fast enough there is nothing you can do to save your friend or get them back to full health

### Solution you would like.

Ability to bandage, disinfect etc on monsters in the same way the player can do this to themself or NPCs

### Describe alternatives you have considered.

Just use Magiclysm or Arcana to do this with powerful magics

### Additional context

Inspired especially by recent Rycon and Critsy Bear videos which both dealt with this issue, either by repeated vicious pet murder or magical powers

**Comment by Maleclypse** [comment]
So I think you'd do this in monexamine.cpp.   

```
void bandage_animal( monster &z )
{
    if( z.has_effect( effect_bleed ) ) {
        return;
    }
    item_location loc = bandage_loc();
    if( !loc ) {
        add_msg( _( "Never mind." ) );
        return;
    }
    z.remove_effect( effect_bleed, 1_turns, true );
    z.bandage_item = cata::make_value<item>( *loc.get_item() );
    loc.remove_item();
}
```
