### ISSUE TITLE
Katana disappears after crafting while having the Urban Samurai mission "Find a real katana"

### ISSUE THREAD

**Issue by FellsHollow** [CleverRaven/Cataclysm-DDA#62140]
### Describe the bug

When I went to craft a katana for my Urban Samurai, it disappeared after I finished it. I had a mission "Find a real katana" and even though in the 'P' log it said wielding - katana, "Mission 'Find a real katana' successfully completed", I was not, in fact, wielding anything at all. It seems like completing the mission consumed the katana I had made.

### Steps to reproduce

1. Create Urban Samurai with the mission "Find a real katana".
2.  Craft a real katana (components may not matter, but I used leather instead of fur pieces).
3.  Mission completed but katana is consumed.

### Expected behavior

I expected to be able to keep my katana after crafting, but I had to spawn one in to replace my hard work. I was able to keep the spawned katana.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: cb00456 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

I'm not sure whether or not the info I provided will help, but I'm hoping someone can reproduce this issue and have it fixed.

**Comment by MNG-cataclysm** [comment]
/confirmed
On version a2e6920 2022-11-04-0831.
