### ISSUE TITLE
River Cave Entrance Ramp Misaligned

### ISSUE THREAD

**Issue by CDDABen** [CleverRaven/Cataclysm-DDA#62157]
### Describe the bug

Hello,

The river cave entrance ramps seem to be misaligned with the internal ramps, which causes enemies to be near impossible to lure out, with them instead congregating around the internal ramp tiles.

Thanks,
Ben

### Steps to reproduce

1. Head down a river cave entrance ramp.
2. Look up, to see that the internal ramp doesn't align with the external ramp.

### Expected behavior

That external ramps line up with internal ramps, so that creatures/NPCs can readily navigate up and down.

### Screenshots

![Screenshot_20221110-104118](https://user-images.githubusercontent.com/63902861/200963684-7fa28aef-8cca-4c0e-9a65-022e051d7aef.png)

![Screenshot_20221110-104626](https://user-images.githubusercontent.com/63902861/200963712-b1e84df5-7e09-4474-8e20-e98a833f9d1f.png)

### Versions and configuration

- OS: Android
- Game Version - "cdda-android-x32-2022-06-01-0513.apk"

**Comment by Maleclypse** [comment]
I couldn't make this happen on a recent build.  Is this a rare mispawn?
