### ISSUE TITLE
Encumbrance based on weight, rather than volume?

### ISSUE THREAD

**Issue by Spaceb0i** [CleverRaven/Cataclysm-DDA#62169]
### Is your feature request related to a problem? Please describe.

Encumbrance is, naturally, quite a big deal in Cataclysm, as it necessitates that a balance be struck between protection, storage, and freedom of movement. Currently, containers (backpacks, load bearing vest, pants, etc) calculate the amount of added encumbrance based on volume. This can create aggravating and unrealistic situations where carrying large, very light objects (say, a shark plushie) adds more encumbrance than carrying kilos upon kilos of scrap metal or other dense objects. In real life, people are slowed down by having _heavy_ objects in a backpack or other container, not by having _large_ objects. Compare carrying a jacket versus a large laptop in backpack, for instance.

### Solution you would like.

Encumbrance incurred by objects in containers should be based on weight, not volume. This means that for a given container, encumbrance would be calculated based on kilograms rather than liters. Each different container can still retain a unique modifier for how much encumbrance each kilogram incurs based on where and how it distributes weight (A kilogram in a backpack is much less encumbering than a kilogram in an ankle sheath). The uncomfortable nature of the _volume_ of a container on the body is already largely modeled by its base encumbrance.

### Describe alternatives you have considered.

-A simultaneous volume and weight encumbrance modifier could work in theory, but adds more complexity than it's worth. 

-The downsides of encumbrance could be partially transferred to carried weight, but this would completely negate the limb-specific effects of carrying weight in different places

**Comment by Inglonias** [comment]
This is true when dealing with items in containers, but when it comes to worn items in a combat situation (arguably where encumbrance matters the most), you don't want to be wearing parachute pants, or a vastly oversized shirt. Large items get caught on things and get in the way.
