### ISSUE TITLE
Achievement bug

### ISSUE THREAD

**Issue by NVRSLP101** [CleverRaven/Cataclysm-DDA#62172]
### Describe the bug

After getting the Killo achievement the game would suddenly crash

### Steps to reproduce

by just getting the achievement killing any hostile mobs

### Expected behavior

I expected that the game would suddenly crash by getting the achievement.

### Screenshots

![image](https://user-images.githubusercontent.com/117978753/201306430-86a7d302-9d4e-4af7-bc4b-ae4c2958cd38.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

### Additional context

[Uploading Killo achievement crash.zip…]()

**Comment by NetSysFire** [comment]
Can not reproduce on latest experimental. Your save also did not get uploaded.

![image](https://user-images.githubusercontent.com/59517351/201331420-a9bf5ec7-ce47-4c52-bb1c-0ef8e1344c0c.png)

**Comment by NVRSLP101** [comment]
[Killo bug save file.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9993681/Killo.bug.save.file.zip)

**Comment by NVRSLP101** [comment]
[Crash and debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9993684/Crash.and.debug.zip)

**Comment by NVRSLP101** [comment]
The stable version for me  0.F-3 [32-bit] is crashing during getting the achievement then please wait loading thing it would suddenly minimize the game  :(
