### ISSUE TITLE
Sinks Turn in the wrong way when deconstructing around them

### ISSUE THREAD

**Issue by aaronstevenson408** [CleverRaven/Cataclysm-DDA#62184]
### Describe the bug

when deconstructing furniture around sinks the turn awkwardly 

### Steps to reproduce

Deconstructed the counter underneath
Deconstructed counter above  

### Expected behavior

The edge that normally faces wall should face wall. 

### Screenshots

![image](https://user-images.githubusercontent.com/64069763/201458935-d7c947b5-21f4-4360-acda-1919fdf8d1f7.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2251 (22H2)
- Game Version: 4852b20 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]

### Additional context

Seems to just be cosmetic (because you cant get water from the sinks) , probably a low priority bug

**Comment by Je55eah** [comment]
likewise, refrigerators turn when connected to the grid.

**Comment by TealcOneill** [comment]
Was not able to reproduce, all furniture items are static when deconstructing and smashing nearby walls. @GuardianDll 
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
I think there was such issue before, but it was fixed long time ago
