### ISSUE TITLE
Trading with NPC using specific amount

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#62186]
### Describe the bug

Marking an item for specific amount would switch the selected item upward once, this makes it so you can't trade the item you want to trade with a specific amount.

Although this bug doesn't happen everytime.

### Steps to reproduce

1. Go to a survivor/hub01/refugee/rubik for a trade
2. Have multiple items in your inventory
3. Try to trade an item with a specific amount
4. Item selected will switch upward once

### Expected behavior

Expect it to allow me to specify the amount I want to trade of the item I selected without switching it upwards once

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: bd17c48 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Teleporter [Teleporter],
    Artifact Jewelries [Artifact Jewelries]
]

**Comment by andrei8l** [comment]
Couldn't reproduce but maybe I don't understand the issue. What does "switch upwards" mean?

Btw you can use +/- to de/increase the selected amount of the highlighted item.

**Comment by Kywi001** [comment]
> Couldn't reproduce but maybe I don't understand the issue. What does "switch upwards" mean?
> 
> Btw you can use +/- to de/increase the selected amount of the highlighted item.

Inventory sample
-some other items
- Merch (10)
- Merch bundle (10)
- some other items

I wanted to trade 2 merch bundles, when I press the key bind of "mark specific amount" while selecting the merch bundle, the selection would shift upward selecting Merch instead of the Merch Bundle.
This happens around 30% to 50% of the time, mostly when my inventory have a lot of things on the list.

**Comment by andrei8l** [comment]
That sounds like your keybind for `Mark a specific amount` conflicts with an invlet. Can you try with a non-alphanumeric keybinding?
