### ISSUE TITLE
Disassemble number 5 while wanering through the bushes.

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62181]
### Describe the bug

I haven't fought anything with my character yet, but an error message appeared that said something about empty air and then after I pressed space I was granted an achievement for disassembling number five and I was marked as not being a pacifist. 

### Steps to reproduce

I have no idea. 

### Expected behavior

It probably wouldn't have happened.

### Versions and configuration

English Linux Tiles 1351

**Comment by PatrikLundell** [comment]
At a guess, you wandered near a crater or a collapsing building and some "furniture" was found to be in empty air, prompting a report (known issue). In addition to that, some creature was also there and fell to its death, which then incorrectly was attributed to you. I don't know about disassembly, but it might be something being smashed by falling as well.

**Comment by DSeyka** [comment]
>I don't know about disassembly
The achievement doesn't have to do anything with actual disassembling, it's just about killing any robot.

**Comment by AcidAntOnAMinefield** [comment]
This issue is easy to replicate if you do a Lab Start and just happen to start in a Research Facility lab. 
Easy way to fix this (I suppose?) would be to make the craters *not* explode when they enter reality bubble or remove them entirely - THAT by itself sometimes causes a huge slowdown (and once managed to make the game crash on me).

**Comment by Je55eah** [comment]
Those explosions are cool though. My nephews were watching me play for some minutes and they were saying "wow, don't go over there" when the explosions were happening. Perhaps it could be a toggle in the settings for low spec systems.
