### ISSUE TITLE
Lightstrips kill batteries instantly

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#62185]
### Describe the bug

Lightstrips kill batteries instantly even though its `power_draw` is only 1J.

### Steps to reproduce

1. Disassemble a flashlight and get a lightstrip OR debug spawn a lightstrip
2. `r`eload the lightstrip with any battery
3. `a`ctivate the lightstrip
4. Witness the battery disappear instantly

### Expected behavior

I expected the lightstrip to not eat the battery away.

### Screenshots

![IMG_20221112_211551](https://user-images.githubusercontent.com/52661206/201474935-0c8c8c9d-e8da-4cec-a33c-b47177ee85de.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G950N; Release: 9; Incremental: G950NKSU5DVG2; 
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles

### Additional context

It happened no matter what mods were in.

**Comment by Night-Pryanik** [comment]
This bug should've fixed by #61994. Could you please update to the latest experimental and recheck if this issue is still valid?

**Comment by NotSeawhite** [comment]
It works, thanks for telling me
