### ISSUE TITLE
Umbrella is 11 cm length and in my rain coat...

### ISSUE THREAD

**Issue by 0x9conc1** [CleverRaven/Cataclysm-DDA#62195]
### Describe the bug

I found an umbrella and was shocked by its basic melee parameters, but when I was needed to unload the coat to put it off and was asking would to store the umbrella in INVENTORY (to stop it wielding) I was shocked even more (actually, only after realizing that it is in the coat when started looking for where the umbrella is).

### Steps to reproduce

Look at it.

### Expected behavior

L = 1.5 seems ok, but
Weight = 0.14 kg and Length = 11 cm seem unnatural (btw 4 inches - it's transitive).

So it needs to be naturated.

### Screenshots

![cdda1](https://user-images.githubusercontent.com/73962707/201496506-44ad2280-3c03-423d-bd2a-5d5a343e046b.png)
![cdda2](https://user-images.githubusercontent.com/73962707/201496510-3e32ed77-320d-4a79-b675-6e0eb0fcbc7f.png)

### Versions and configuration

Game Version: 0.F [64-bit]

**Comment by Qrox** [comment]
Perhaps you got a cocktail umbrella.
