### ISSUE TITLE
Doors, hinges, and shotguns.

### ISSUE THREAD

**Issue by Computer-Engineer-Man** [CleverRaven/Cataclysm-DDA#62190]
### Is your feature request related to a problem? Please describe.

As far as I know currently, the only way to get into a secured area (think locked wooden doors, metal doors, etc.) is to either pick the lock of the door to get into it or break the door down. I have had numerous occasions where I was unable to break down a metal door but break down a wall next to the door to get in. 

Frankly, I think this is stupid. 

Firstly, in order to break down a wall to get into somewhere it is equal to taking down an entire wall enough so you can easily walk through it and put something new there if you wanted to.

Secondly, if you had a gun (which I believe most survivors have a surplus of) and don't care about noise, you should be able to use a shotgun to break down the lock or hinges on doors.

Lastly, why can't I just make a human sized hole through a wall and crawl through it instead of breaking down the whole damn wall?

I believe there should be no reason why it is harder to destroy a door than a wall if you are being smart about it. Mainly, targeting the weak points of the door, mainly hinges, locks, and the actual outline of the door connected to the wall.

### Solution you would like.

Being able to have a variety of options to break into secured areas.
Firstly, being able to shoot the hinges off of a door to quickly and loudly remove a door.
Secondly, being able to have an option to quickly make a player-sized hole through a wall. It was mentioned that maybe you'd have to crawl through it and it could have sharp edges. 
Lastly, being able to quickly break down a door by destroying either the hinges or the outline of the door. 

### Describe alternatives you have considered.

When shooting a metal door maybe have it ricochet if the gun is low enough caliber. Only being able to either lock pick, open, or break a door or wall to get into a secured location.

### Additional context

Beginning of the conversation in discord:
https://discord.com/channels/598523535169945603/598523535169945607/1041048599456391250

**Comment by robotic-gamer** [comment]
another option to get though metal doors (or walls), is to use an electric hand drill on it. it would take a long time and use a lot of battery charge (you'd probably need more than one battery) but the player would eventually remove enough material to allow passage.

another option would be to use a forge to slowly melt off parts of the wall

another option would be to grind the obstacle to nothingness with something like an angle grinder, or some kind of makeshift scrapping tool that uses a diamond as the tip.

lastly you could use corrosive chemicals to corrode the obstacle until it no longer obstructs the player.

**Comment by PatrikLundell** [comment]
Metal doors intended to resist forced entry (as opposed to regular doors that just happen to be made of metal) are typically designed to block you from accessing and destroying hinges and locks.

**Comment by Cenness** [comment]
Related PR https://github.com/CleverRaven/Cataclysm-DDA/pull/45489  
 and quote from https://github.com/CleverRaven/Cataclysm-DDA/issues/45574

>anothersimulacrum:
That PR focuses specifically on pickaxes, but it is intended that you cannot mine doors with any mining equipment.

Personally I just revert that change in my installation.

**Comment by Computer-Engineer-Man** [comment]
> Metal doors intended to resist forced entry (as opposed to regular doors that just happen to be made of metal) are typically designed to block you from accessing and destroying hinges and locks.

A quick search actually shows the opposite. Looking up metal security doors actually shows the majority of doors actually have their hinges out, as shown in the picture here. Perhaps military bases would have different doors but at least for the seemingly vast majority of exterior metal doors the hinges seem to be on the outside. From a quick google search this is done so it's easier to get out in case of a fire and save space that can be used inside.
![image](https://user-images.githubusercontent.com/115521142/201776177-258df340-23ac-4753-acf1-90fbe8946b0a.png)

> That PR focuses specifically on pickaxes, but it is intended that you cannot mine doors with any mining equipment.

This issue is actually entirely unrelated to reverting how pickaxes or mining equipment interact with doors. This is bringing up the fact that in real life you are able to do the following. Instead of removing an entire wall, remove just enough to climb through or be able to shoot or break/take apart hinges to take down an entire door.

**Comment by Cenness** [comment]
>This issue is actually entirely unrelated to reverting how pickaxes or mining equipment interact with doors

But it is. If doors are supposed to resist gas powered jackhammer, no firearm would help one open it.  

>This is bringing up the fact that in real life

Yeah. It would be awesome to be able to use slugs to destroy locks or use breaching charges to blow off entire thing off. Alas, as you can see maintainers have more nuanced opinion on that.

**Comment by Computer-Engineer-Man** [comment]
> If doors are supposed to resist gas powered jackhammer, no firearm would help one open it

I admit I do believe that if you are using a jackhammer or a pick axe it would make sense logically that you could break down pretty much any door but that's still outside the scope of this issue. This issue isn't about how durable doors are, but more about using shotguns on hinges/locks and making a small hole to go through walls would make sense logically.
