### ISSUE TITLE
NPC allies become hostile when interacting with bandit-owned objects.

### ISSUE THREAD

**Issue by CDDABen** [CleverRaven/Cataclysm-DDA#62199]
### Describe the bug

Hello,

When I opened the door of an RV belonging to an inherently-hostile bandit, in an effort to reach him, my two NPC allies simultaneously became hostile against me.

The version I'm using is from several months back, so this might have already been fixed. Sorry if that's the case.

Thanks,
Ben

### Steps to reproduce

1. Interact with a bandit-owned object, while in sight of a friendly NPC (it may require several interactions, such as also stepping into a vehicle, for NPCs to get angry).

### Expected behavior

I would expect that my allies wouldn't become hostile against me, for interacting with something belonging to a hostile bandit. Not assigning ownership to objects belonging to inherently-hostile NPCs might be an easy fix.

### Screenshots

![Screenshot_20221113-143650](https://user-images.githubusercontent.com/63902861/201504116-8678eda0-0327-4066-9986-a9f3a22136e5.png)

### Versions and configuration

 OS: Android
 Game Version - "cdda-android-x32-2022-06-01-0513.apk"

**Comment by NotSeawhite** [comment]
I imagine this happens because the followers hate stealing someone's stuffs, but Hell's Raiders' stuffs aren't excluded. Probably an oversight?
