### ISSUE TITLE
Disableing Nukes has little effect

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#622]
When you disable the nuke nothing really happens. Only the terminal is disabled.

A disabled nuke should, imho, give a large morale boost. (You are doing your part for nuclear disarmament). And stop the nuke gas and other gas from spawning around the nuke.
##

**Comment by Leland** [comment]
Closing - this is 2.5 year old suggestion that hasn't seen discussion in just as long. Feel free to comment here or open a new issue if there's still interest.
