### ISSUE TITLE
How do you clear/whitelist hobbies/background in mods?

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#62203]
### Describe the bug

I am playing around with a total conversion mod where it would make sense to have completely different hobbies, because it aims for a middle ages look and feel. There was no meth addiction back then, and you couldnt play videogames either.

### Steps to reproduce

1. Look at scenario and profession black/whitelisting.
2. Try to clear the list of hobbies so you only have the ones you explicitely whitelist.
3. There is apparently no way?

### Expected behavior

You can black/whitelist professions, scenarios and spawned locations, but why not backgrounds?

### Versions and configuration

experimental

**Comment by mqrause** [comment]
Hobbies currently have no concept of permitted/prohibited. One way to add it would be to mirror `scenario::permitted_professions` for hobbies and use that instead of `profession::get_all_hobbies` in the relevant places.
