### ISSUE TITLE
Taking an elevator to Z-level -1 instead brings you to the Z-level above the highest elevator-accessible Z-level

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62210]
### Describe the bug

Using the elevator (specifically, t_elevator and t_elevator_control) to get to Z-level -1 instead brings my character to one Z-level above the highest Z-level accessible from said elevator.

### Steps to reproduce

1. Debug in an elevator and its controls on both Z-level -1 and a different Z-level
2. From the elevator controls on the level that isn't Z-level -1, select Z-level -1.
3. Find yourself on the roof (or whatever else is immediately above the highest Z-level accessible by that elevator)

### Expected behavior

I expect that using the elevator to go to Z-level -1 will take me to Z-level -1, and not leave me stranded on a roof or a floor with no elevator access.

### Versions and configuration

OS: Windows
OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/4bf05439a172529647ca4f41fbe7085f74edb6c1 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
C.R.I.T Expansion Mod [crt_expansion],
<color_light_blue>BL9-100%-monster-resilience-version [BL9_100monres],
<color_light_red>Secronom [secronom],
<color_light_red>Secronom+ Lore Expansion [secronom_lore_expansion],
Aftershock [aftershock],
Arcana and Magic Items [Arcana],
Blaze Industries [blazeindustries],
Magiclysm [magiclysm],
Xedra Evolved [xedra_evolved],
DinoMod [DinoMod],
Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
Extra Mutated Scenarios [extra_mut_scens],
Mythical Martial Arts [MMA],
Translate Complex Dialogue [translate_dialogue],
Magiclysm No Class Limit [magiclysm_no_class_limit],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills],
Tamable Wildlife [Tamable_Wildlife],
Useful Helicopters Experimental [useful_helicopters],
Arcadia Mapgen [custom_arcadia_mapgen],
Cooler Versatility [coolervers],
Custom Bionics [custom_bionics],
XEAS [XEAS],
return_the_nut [return_the_nut],
consume_the_nut [consume_the_nut],
Reproduction mod [perverts]
]

### Additional context

This will happen no matter what floor I was on prior to trying to go to Z-level -1.

**Comment by andrei8l** [comment]
/confirmed uilist doesn't like retval -1 
https://github.com/CleverRaven/Cataclysm-DDA/blob/7fbae08ff93a829cafdd738eac95a5017cd10deb/src/ui.cpp#L536-L538
