### ISSUE TITLE
The MSVC test Cataclysm_DDA project failed to run test on Windows

### ISSUE THREAD

**Issue by fangzhouxia** [CleverRaven/Cataclysm-DDA#62225]
### Describe the bug

Hi all,
Cataclysm_DDA failed to run test with MSVC on windows. Could you please help look at this issue or provide some workarounds? Thanks in advance.

### Steps to reproduce

1. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
2. git clone https://github.com/microsoft/vcpkg F:\gitP\CleverRaven\vcpkg
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
4. cd F:\gitP\CleverRaven\vcpkg
5. .\bootstrap-vcpkg.bat -disableMetrics
6. .\vcpkg integrate install
7. cd F:\gitP\CleverRaven\Cataclysm-DDA
8. & "C:\msys64\mingw64\bin\mingw32-make" -C lang -j2
9.  mkdir -p ./data/mods/TEST_DATA/lang/mo/ru/LC_MESSAGES -ErrorAction SilentlyContinue
10. msgfmt -f -o ./data/mods/TEST_DATA/lang/mo/ru/LC_MESSAGES/TEST_DATA.mo ./data/mods/TEST_DATA/lang/po/ru.po
11. mkdir build_amd64 & cd F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64
12. msbuild /m /p:Platform=x64 /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64 /t:Rebuild
13.  cd F:\gitP\CleverRaven\Cataclysm-DDA
14. F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64\Cataclysm-test-vcpkg-static-Release-x64.exe

### Expected behavior

Build seccessfully

### Screenshots

![image](https://user-images.githubusercontent.com/109721669/201813679-8ebd5bf3-64b2-4297-b6d0-b50fd5bf479d.png)

### Versions and configuration

VS version: VS2019(16.11.20)
Operating system: windows server 2019

### Additional context

[log 3.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10008652/log.3.log)

**Comment by alef** [comment]
Can't repro with 90c06120, VS2022(17.4.0) on Windows 10, built in Visual Studio IDE with open Cataclysm-vcpkg-static Solution, in both Debug and Release for x64.

![image](https://user-images.githubusercontent.com/3899581/201905693-b19ddaf7-d34e-4cc6-a90a-a1db739e6ad0.png)
