### ISSUE TITLE
NO_BREED doesn't work for eggs

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#62223]
### Describe the bug

Assigning the NO_BREED flag to a monster like DinoMod does still produces eggs if that monster copies from an adult with egg data. 

### Steps to reproduce

1. Start a game with DinoMod loaded
2. Debug spawn a juvenile acrocanthosaurus and feed it catfood
3. Wait for delicious eggs

### Expected behavior

No eggs until adulthood

### Versions and configuration

Most recent experimental

### Additional context

Flagged in most recent Rycon video https://www.youtube.com/watch?v=Lq7efdvsM8E&t=1967s

**Comment by LyleSY** [comment]
I have the skills to manually rebuild these in JSON to no longer have egg laying content in them and document the error, but I don't have the ability to rewrite the C++ to make the NO_BREED flag work for egg layers. I'm willing to do it, but if someone with the skills wants to fix the bug, that's 100% my preference

**Comment by NetSysFire** [comment]
i just assigned you because that will fix stalebot from closing the issue without me having to assign a priority :p

**Comment by Karol1223** [comment]
Is this still happening? I just tried reproducing it on the latest experimental and could not pull this off with the Acrocanthosaurus specifically (granted I didn't tame mine)

Passed 60 days, nothing, teleported away, passed 30 days there, also nothing when I came back

**Comment by LyleSY** [comment]
Agreed, I can't reproduce now either. Thanks to you and to whoever fixed.
