### ISSUE TITLE
Belt linkages should be craftable

### ISSUE THREAD

**Issue by irRegularGuy646** [CleverRaven/Cataclysm-DDA#62232]
### Is your feature request related to a problem? Please describe.

if you can hammer some scrap metal together with enough accuracy to make a drop-in auto sear, you should be able to make a loop of metal to hold a bullet

### Solution you would like.

you should be able to craft individual 40mm, .223, .308, and .50 linkages. probably out of small metal sheets or scrap metal.

**Comment by kevingranade** [comment]
Nope,  turns out these things are notoriously difficult to make.
