### ISSUE TITLE
Loose Solar Panels cannot be repaired

### ISSUE THREAD

**Issue by grimmspector** [CleverRaven/Cataclysm-DDA#62235]
### Describe the bug

Solar panels loose in inventory or on the floor cannot be repaired by any tool. The 'e'xamine description reads "This item is not repairable." When mounted to a vehicle, solar panels can now be repaired!

### Steps to reproduce

1. Dismount a solar panel from a vehicle that's already damaged.
2. 'e'xamine the panel, or attempt to repair it by some means.
3. Fail to repair the panel.

### Expected behavior

The solar panel should be repairable by at least the same methods used while it's mounted to a vehicle, if not more / easier since it's free to work with when not mounted.

### Screenshots

![Catacylsm-DDA_Solar_Panel](https://user-images.githubusercontent.com/65185497/201968793-66f9c536-4369-4618-a7bd-03dfebde7dec.png)

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental Build 2022-11-12-1938
- Graphics Versino: Tiles
- Ingame language: English
- Mods loaded: dda no_npc_food, no_fungal_growth, package_bionice_professions, blazeindustries, magiclysm, culinary_days_ahead, MMA, MMA_Mods_Extension, vamp_stuff, magirevamp, demon_spider_a, speedydex, stats_through_kills, Tamable_Wildlife

**Comment by grimmspector** [comment]
Report incorrect.

**Comment by Maleclypse** [comment]
> Report incorrect

I'm closing this because I think that's what you are saying to do.
