### ISSUE TITLE
Bugged interaction of portal storm and exodii base

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#62240]
### Describe the bug

Rubik instaling to me cbm, and portal storm starter. And turrets killed me for no reason. Nice game over
I tried to reproduce it - and turrets just teleportated from their places, and also they shooted portal monsters

### Steps to reproduce

1) Teleport to exodi base
2) scroll the time for 1 year from debug menu
3) Make portal storm
4) Sit in Rubick room for few hours. Kill Rubik from debug menu to prevent him to open the door
5) See your death or gansta shooting of robots everywhere, or telepotations of stationary turrets, which are under the roof, so they are isolated from portal effects
6) Turn off you computer, hide under blanket and cry becouse of loosed progress

### Expected behavior

So make pls something with it, is very ass burning, when you are loosing your character for no reason. Rubik is portal traveler, who teleported whole metal castle and operating army of drons and deadly walkable quadruped simular to tanks, so he know about portal storms, so he must have physical barier (glass dome over castle, or something like that), or some device, which make anti portal electrik/magick/magnetic/love field, or make  his base underground. If he teleported so big structer from another world, he can teleport out a lot of dirt to make big pit and place into it his base, or his drones can just dig pit. Or make all base closed from outer world, metal tower without windows

I have also good solution. Create portalweahter detector, selling by rubick, or its recipe to make it by your own. We already have "unfamiliar electronic thingy" and few more strange parts, which you can see, if try to disassembly exodii worker or quadruped, and there is no use of them. So make Rubik seling them as an part of portalstorm detectetor
If you want to make operation, or go to sleep, or something time comsumind and risky for your life - detecter will say to you, that storm is coming. For a day or two before the storm. If you try to install cbm by Rubik - he can also warn about coming storm, to prevent your death

I dont know the mechanic of portal storm appearing, but it, anyway, have minimum days between storms, and detector can show you a chance of portal storm apearing

Idea with field, which will protect you from portal storm monsters and effects also good. We have protective filed cbms, we have portal clousing artifacts, we have rewards for portal dungeon, whick can turn off started portal storm, so there must be technology, wich will not allow portal monster in protective field, and also will save you from effects

But anyway, problem with portals and exodii base remains

### Screenshots

![image](https://user-images.githubusercontent.com/102726167/202007549-12b88a51-1980-4fed-b130-bf115d9e11a2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: fae2b2a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by SariusSkelrets** [comment]
It sounds like that lasting aggro bug: something enrages a neutral then the neutral now sees you as a hostile after it's done with the  other hostile
AFAIK the forge borns of magiclysm are another example of this problem

**Comment by KHeket** [comment]
> It sounds like that lasting aggro bug: something enrages a neutral then the neutral now sees you as a hostile after it's done with the other hostile AFAIK the forge borns of magiclysm are another example of this problem

Anyway, will aggro bug be resolved or not - if you are under surgery operation during portal storm, and robots and turrets will shoot only portal mosters - can accidentally hit you when shooting, or can can accidentally hit another robots/Rubik. So there must be solution to fully isolate rubik and his robots from gansta-ghost shooting
