### ISSUE TITLE
Possibility for NPC survivors of the helicopter crash start.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#62244]
### Is your feature request related to a problem? Please describe.

In the description for the helicopter crash scenario, it’s stated that, “Hopefully some of the soldiers that were with you also survived the accident.” As things stand, this sentence is practically void given that, in no possible universe, is there a scenario were any soldiers survive the crash save for the player. Whilst I concede that the notions of “hopefully” and “did” are two very different hypotheticals, especially within the context of the Cataclysm, I believe that it’d be rather neat if there was the possibility for some wounded NPC soldiers to spawn during the scenario.

### Solution you would like.

Leaving aside the pure code feasibility of such an implementation, I believe it would be interesting if there was a chance for one or two wounded NPC soldiers to spawn alongside you during the scenario. I think that this would make the scenario, already interesting in of itself, more appealing as it would give you a functional goal. As matters stand, the start practically feels like a rural version of the car crash scenario, with the only change being that, if you’re lucky, it has the chance to conveniently deposit you next to a farmhouse, rural building, LMOE shelter, cabin, ETC.

### Describe alternatives you have considered.

Failing this, perhaps the start might provide you with a mission to try and find some fellow soldiers who might have baled out during the crash.

**Comment by Kywi001** [comment]
Would be nice if there's a scenario exclusive mission for this,

"Rendevous with other possible surviving military members"

Where you have to go somewhere where they've might landed during a chute take off, then this mission has 2 to 3 chains where you have to check another location after checking the 1st one and check if they're still alive or not.

**Comment by DoctorBoomstick** [comment]
Exactly the sort of mission I was picturing. The only question would be how the player character knows where to start searching for any survivors? You could, I suppose, just point at an over map tile and tell the player, here be your mission target, how we do for all our other location dependent missions. That being said, that still wouldn’t answer how the character knows that survivors would be in that specific location.
The three possibilities I personally see are,
1.	Have the player go to a prearranged rendezvous point. It could be established by the mission description that, prior to game start, the player character and their fellow military team had agreed to meet up at a specific safe zone in case of an emergency bailout. My thought process goes that the rendezvous point should potentially be a safe, noticeable, and clear building somewhere in the countryside. The zone in question could, for example, be a cleared military outpost, some large rural structure, a radio tower, or an airfield.
2.	Have the player be directed to head towards the end location the helicopter was traversing to, working off the idea that any survivors might have tried to reach their destination on foot. In this scenario, I’m thinking that the location in question could perhaps be a functional Old Guard base, an airfield, or even just the refugee centre.
3.	Point the player to go towards the last reported location of a paratrooper team that jumped before whatever emergency caused the helicopter to nose-plant cockpit first into terra firma.
