### ISSUE TITLE
Reduce ethics-based morale maluses by talking it out

### ISSUE THREAD

**Issue by perryprog** [CleverRaven/Cataclysm-DDA#62250]
### Is your feature request related to a problem? Please describe.

There are certain morale maluses that arise from "ethics" based issues, like killing zombie children. (Currently this is only the "guilt" in magic_spell_effect.cpp, I believe). These penalties can be pretty extreme, and it would make sense that there would be ways to alleviate it through in-game methods.

### Solution you would like.

It could be interesting to have opportunities for dialog with NPCs (perhaps only trusted companions) to talk about just what you've done, and for that to alleviate some of the penalty you're experiencing. It'd also be interesting if you fail a check based on various... stuff (NPC trust, charisma, and so on) for the NPC to possibly be offended by your action and for the penalty to get even worse.

As alternatives for this, perhaps even having options to journal that provide a less extreme bonus (like a 25% reduction compared to a 50% reduction that talking it out could give). It also might be amusing to have autodocs to have something similar, but even worse—an [ELIZA](https://en.wikipedia.org/wiki/ELIZA)-homage could be pretty funny.

In cases that you have no maluses from being a murdering child-killing monster, this could simply be a discussion on how messed up the world currently is (aaa cataclysm oh no), which leads to a morale bonus.

### Describe alternatives you have considered.

This is a fairly substantial feature (plus lots of dialog) for a very minor inconvenience that's generally not too common. It's _probably_ not worth implementing unless we want to add more circumstances where the player is getting distressed from something in a mechanical sense.

### Additional context

Idea from @NetSysFire on IRC. az-ssh suggested the possibility of the NPCs being horrified at what you've done.

**Comment by AcidAntOnAMinefield** [comment]
The player being "sad" by killing something (in self-defense) that's trying to kill them is a bit of a silly concept. No one is "sad" by being able to avoid being killed. Giving more fuel for the broken NPCs to just turn against you for no reason whatsoever doesn't seem like a good idea, game wise, considering they are already very limited on the purpose they serve, and their intelligence is subpar at best - which leads to them making some really strange decisions that on occasion even go against the orders they were given.

**Comment by Zireael07** [comment]
@AcidAntOnAMinefield: I think this malus should be renamed to something else than "sad" - after all, even soldiers and cops struggle with accepting the fact they killed people, even in self defense

Agreed that  this shouldn't lead to NPCs turning on you

**Comment by Owlblocks** [comment]
While I appreciate the latin, I'll admit it was a bit confusing, as it took me a good 15 seconds to realize you were pluralizing malus, and it wasn't a typo of "mail".

**Comment by perryprog** [comment]
Yeah I figured it was 50/50 on which was correct; I probably should've just gone with maluses. Will amend so no-one else gets confused.
