### ISSUE TITLE
Typo getting in my hair

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#62265]
### Describe the bug

Discovered a minor typo while localizing on Transifex in the description of "Hair: white, buzz cut" which is the following
-"Your w hair has been shaved close to the head."
This is of course absolutely unplayable and should be fixed to this:
-"Your white hair has been shaved close to the head."
before anybody is willing to bother playing CDDA ever again.

### Steps to reproduce

1. Check the string itself or check in game if the hair mutation indeed has a typo.

### Expected behavior

There not being a typo

### Versions and configuration

Latest experimental

**Comment by Zireael07** [comment]
"This is of course absolutely unplayable" and "before anybody is willing to bother playing" are probably ironic, but irony/sarcasm do not transfer well online plus many people on here are not native speakers of English and may take it at face value.

Please refrain from this when making bug reports.

**Comment by robotic-gamer** [comment]
is a viable alternative something like this?

Discovered a minor typo while localizing on Transifex in the description of "Hair: white, buzz cut" which is the following
-"Your w hair has been shaved close to the head."
This is of course absolutely unplayable and should be fixed to this*:
-"Your white hair has been shaved close to the head."
before anybody is willing to bother playing CDDA ever again*.

*=sarcasm
