### ISSUE TITLE
Item spawn test CI failure

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#62267]
### Describe the bug

```src/item.cpp:1501 [ret_val<void> item::put_in(const item &, item_pocket::pocket_type, const bool)] tried to put an item (pockknife) count (1) in a container (afs_corpse_old) that cannot contain it: Can't store anything in this.```

### Steps to reproduce

Run CI 10k times a day

### Expected behavior

CI to run perfectly every single time. Nah friend this is what randomized CI is for.

### Versions and configuration

Current CI

**Comment by BrettDong** [comment]
It was reported in #62220

**Comment by Maleclypse** [comment]
Oops didn't see that.  Thanks!
