### ISSUE TITLE
New Location: University / University Campus

### ISSUE THREAD

**Issue by jo-onis** [CleverRaven/Cataclysm-DDA#62277]
### Is your feature request related to a problem? Please describe.

Basically the thought originated while I was looking for places to find chemical equipment, which is only available at limited locations currently. But it feels like an overall good location to include in the game

### Solution you would like.

The idea is a new location, University or University Campus

Universities usually conduct various kind of research, and they can have multiple faculties. It could be a great resource for knowledge and research equipment of various kinds.

Possible things it could contain:
* Lecture halls
* Cafeteria
* Dorms
* Library
* Research rooms (for different faculties)
* Workshops (used by mechanical engineer students and similar)

New zombie variation (good for immersion, although I don't know what would make it unique?):
* University student

Game balance / difficulty:
I'm imagining that it would be medium difficulty, it should probably be easier to loot than a research facility, but still have a decent amount of zombies

The amount of loot obtainable probably needs to be balanced, but ideally there would be a chance to get lab analysis kits and good workshop tools or similar, if lucky

Scope:
Since the scope is rather big maybe it's possible to divide it up a bit so not everything needs to implemeted at once

### Describe alternatives you have considered.

Alternatives:
Small university (single faculty)
Big university (multiple faculties)
University + Campus area

### Additional context

I mainly just want to get the idea started, any suggestions or changes to the idea are welcome

**EDIT:** I looked through the mapgen and saw there is already a "Campus" location. However I've never seen it in any of my world generations? Am I missing something? Perhaps it only needs to be adjusted when it spawns (?)

**Comment by LovamKicsiGazsii** [comment]
> **EDIT:** I looked through the mapgen and saw there is already a "Campus" location. However I've never seen it in any of my world generations? Am I missing something? Perhaps it only needs to be adjusted when it spawns (?)

It's intended to be a faction hub.  The location and the NPCs are unfinished though, so there's a reason why you can't find them on the map.

**Comment by jo-onis** [comment]
> >
> It's intended to be a faction hub. The location and the NPCs are unfinished though, so there's a reason why you can't find them on the map.

Thank you for the response, that explains a lot : )
Maybe it is possible to have both a hub versions and a normal versions of the same locations, kind of like how there are looted  / unlooted versions ?
