### ISSUE TITLE
items disappear from vehicle

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62275]
### Describe the bug

I piled some things inside a cop car. They were still there after most of the trip, but then the whole pile disappeared.

### Steps to reproduce

I have not reproduced it. Everything was dropped into the cargo space next to the spare tire. The car was slightly crooked when loaded and when I checked the pile again, but when the things were missing it was parked straight.  

### Expected behavior

The items ought to still be there.

### Screenshots

![things that disappeared](https://user-images.githubusercontent.com/12481255/202641185-219ac20b-d2f3-4823-8196-03ce584103f7.png)

### Versions and configuration

Linux 6f0e11a

**Comment by robotic-gamer** [comment]
possibly not a bug, its possible you put the pile on the ground and failed to notice it when you drove off. This is easy to prove/disprove by going back to where you loaded the items and seeing if they are on the ground.

**Comment by Je55eah** [comment]
I drove around and verified that the items were still in place at a midpoint in the journey.
