### ISSUE TITLE
Giant Cocoon seemingly appearing from nothing inside my base

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#62285]
### Describe the bug

A giant cocoon has formed inside the 2nd floor apartment room I've been living in despite all windows/doors being closed. I haven't seen any giant caterpillars/giant butterflies or their eggs.

I recently mutated Kaluptic Psychosis, which leads me to think it may be the result of a bug with hallucinating either a giant caterpillar or the cocoon itself which somehow became real.

### Steps to reproduce

1. Have Kaluptic Psychosis.
2. Wait around for a while and see what happens.
3. Wish you had a better idea of what steps could be taken to reproduce this weirdness.

### Expected behavior

Giant cocoons are supposed to only form from giant caterpillars that survive for a certain number of days, not spontaneously generate and draw the ire of Louis Pasteur.

### Screenshots

![image](https://user-images.githubusercontent.com/23239811/202771813-25ef9fe4-f8a8-49b7-9e40-3ac7e86e5c85.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 65e5b97 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by robotic-gamer** [comment]
I ran into a similar bug in the past, my character was getting hallucinations from drug withdrawal. what seemed to be happening is some hallucinations seem to "fail" to go away when your character stops hallucinationing. they still act like normal hallucinations and go away as usual when you try attacking them.

**Comment by gisaku33** [comment]
You were right, after hitting it the cocoon disappeared.
![image](https://user-images.githubusercontent.com/23239811/202829366-7b786e79-e189-445f-a367-285b3c4ab14d.png)
 It seems like a hallucination that failed to go away for whatever reason. I'm going to reload and see if it will eventually emerge into a real giant butterfly.
