### ISSUE TITLE
Cardio invalid trait ID

### ISSUE THREAD

**Issue by ZacPJ** [CleverRaven/Cataclysm-DDA#62289]
### Describe the bug

I am unsure if this is the exact bug but my game keeps crashing every day or two when I sleep. The issue showed up as an error once and it caused the game to totally freeze. It keeps happenning around the 6am mark in game.

 

### Steps to reproduce

1. Sleeping at night seems to cause the error every now and again around 6am.

### Expected behavior

Sleeping should not cause a crash or freeze.

### Screenshots

![error](https://user-images.githubusercontent.com/48377964/202827101-5a1da532-4fdf-48b7-9157-82bef9738be1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: c7d375c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    No Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Megafauna [megafauna],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10045746/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10045747/crash.log)

**Comment by ZhilkinSerg** [comment]
@Maleclypse There is mention of non-existing `CARDIO` trait in Xedra Evolved mod:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3d89e40cea43810fb256b754d5878c0ac0c874b2/data/mods/Xedra_Evolved/npc/trait_groups.json#L46

https://github.com/CleverRaven/Cataclysm-DDA/blob/3d89e40cea43810fb256b754d5878c0ac0c874b2/data/mods/Xedra_Evolved/npc/trait_groups.json#L63
