### ISSUE TITLE
Better QOL if all containers "won't be inserted" by default.

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62286]
### Is your feature request related to a problem? Please describe.

When picking up loot, new loot goes into new containers and things get disorganized. 

### Solution you would like.

Rather than requiring the player to manually toggle off "auto pickup" on every new item it would be better if only selected items needed to be toggled on. 

### Describe alternatives you have considered.

...

**Comment by Terrorforge** [comment]
Honestly, yeah. I understand the logic that filling up non-worn containers helps preserve inventory space, but I find the chaotic mixing, not to mention the dropping bugs, to be a much bigger problem.
