### ISSUE TITLE
``directed_push`` spells with negative damage will cause extremely weird behaviour when used on monsters

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#62298]
### Describe the bug

It's best if you look in the screenshots first

So the flies there? There's only one of them. Only one is a real frigate fly. Somewhere under them is a twisted hive (a monster using said spell, for a PR I was working for, the PR is #62287). The hive pulled the frigate fly in and it started progressively duplicating said fly.

Now, these flies do not move, do not attack (at least I think they don't, one used acid but I think it was the real one while it was still alive) and cannot be attacked (there are no messages about missing but they don't get hit either). They all disappear once the hive (i.e. the monster that caused this with the spell) is killed, however.

Initially, I thought this only happened when the spell is used on a monster adjacent to the caster but I am not convinced that's the case anymore. I can't, however, tell whether it is or isn't. Things got out of hand fast here.

Additionally, when the spell is used on the player (or a monster) they can be pulled onto the same tile as the caster. Which, well, not ideal in itself either.

### Steps to reproduce

1. Copy the changes from #62287
2. Spawn a twisted hive
3. Spawn any monster that's not from the zombie faction
4. Wait a bit until the hive can use its pull spell
5. Notice that the monsters at one point or another start duplicating

As an additional note I'd advise to use slower monsters. I'm not sure what would happen if the monsters were to manage to run away faster than they're pulled.

### Expected behavior

The monsters shouldn't creature indestructible duplicates. And the player or monster shouldn't be pulled on top of the caster either.

### Screenshots

![obraz](https://user-images.githubusercontent.com/68503002/202864792-0b1ed2f7-e9a8-4a78-ba0c-fe4672cd2050.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2251 (22H2)
- Game Version: aa2a276 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Standard combat test suite [standard_combat_test]
]

**Comment by GuardianDll** [comment]
/confirmed, after some tests in a fresh build
