### ISSUE TITLE
spear stats are strange

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62304]
### Is your feature request related to a problem? Please describe.

The level 0 simple knife spear appears to be functionally equal to the level 1 makeshift knife spear an the level 2 homemade halfpike is actually less capable...

### Solution you would like.

It seems like there should be some progression here or at the very least the halfpike should be performatively equal.

### Describe alternatives you have considered.

Do they have the same stats, but break less often when fabricated more expertly?

**Comment by DSeyka** [comment]
Simple knife spear is flimsy AFAIR.

**Comment by DSeyka** [comment]
Simple knife spear is flimsy, makeshift knife spear is not.

**Comment by PatrikLundell** [comment]
Doesn't a half pike have longer reach than a spear?

**Comment by DSeyka** [comment]
No, only actual pikes have long reach attacks. This seems intentional, too: see https://github.com/CleverRaven/Cataclysm-DDA/pull/61482 for reference.

**Comment by oosyrag** [comment]
Simple knife spear and homemade knife spear are made by securing a manufactured knife to a stick, which takes less knowledge/skill than making your own blade (spike) out of a chunk of steel. Just because it's harder to make doesn't automatically mean it should be better. "Progression" doesn't exist as far as normal game design goes, CDDA is more of a simulation.

**Comment by Je55eah** [comment]
And what makes the knife stick  superior weapon when compared to the half pike? I can see the argument for them having the same stats, but increasing durability.

**Comment by oosyrag** [comment]
Homemade halfpike is created with a spike shaped from a lump of steel, possibly by banging on it with a rock. One would expect a manufactured knife blade to pierce better.
