### ISSUE TITLE
Merchant no longer offer items around

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#62308]
### Describe the bug

New game and now merchants like homeless camp and some from mods only have for sale the items in is backpack.

### Steps to reproduce

Homeless camp, guy surrounded by items, trade for inventory.

### Expected behavior

Trade items around them.

### Versions and configuration

Win7
cdda-windows-tiles-x64-msvc-2022-11-17-0622

### Additional context

Maybe is this: https://github.com/CleverRaven/Cataclysm-DDA/pull/62146

**Comment by KymasTuran** [comment]
And the items I sell to him go directly to the "wood stove" outside.

**Comment by andrei8l** [comment]
Sounds like it's working [as intended](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#shop-restocking) and maybe that location was relying on the old behaviour of littering trader items on the floor. Can you upload your save file please?

**Comment by KymasTuran** [comment]
> Sounds like it's working [as intended](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#shop-restocking) and maybe that location was relying on the old behaviour of littering trader items on the floor. Can you upload your save file please?

Yes, is that. Homeless got everything on floor. Already try extend the area of "LOOT_UNSORTED", "faction": "wasteland_scavengers", "x": [ 11, 11 ], "y": [ 9, 9 ] change the first numbers to 10.12 and thats solve it but cause the items around spawn empty.
Well if its working as intended never mind them. 
Thank you.

**Comment by MNG-cataclysm** [comment]
I tested this with the homeless on the 11-28-2022 release, and the merchant sold items around him.

**Comment by KymasTuran** [comment]
> I tested this with the homeless on the 11-28-2022 release, and the merchant sold items around him.

For me the Homeless only sell items at its feet and in front, The others around are ignored. In the mapgen,  at the bottom line there is this: "items": { "~": [ { "item": "homeless_broker_sell", "chance": 100, "repeat": [ 30, 45 ] } ] }
Wich means all these tiles around the NPC receive items.
Weird thing is: if I extend the range of floor tiles the list become corrupt, and all food containers are empty. I already noted this selling items to Smoke and the HUB, after a while, next visit and the food is gone and the NPC sell empty container for 0 $.
The numbers I change for extend the "available items area" are these:   "place_zones": [
        { "type": "LOOT_UNSORTED", "faction": "wasteland_scavengers", "x": [ 11, 11 ], "y": [ 9, 9 ] },
        { "type": "LOOT_CURRENCY", "faction": "wasteland_scavengers", "x": [ 11, 11 ], "y": [ 10, 10 ] }
But like I said, its corrupt in some way.
I tested with a non mod game version cdda-windows-tiles-x64-msvc-2022-12-02-1620
Hope my english is clear enough,

**Comment by MNG-cataclysm** [comment]
> > I tested this with the homeless on the 11-28-2022 release, and the merchant sold items around him.
> 
> 
> 
> For me the Homeless only sell items at its feet and in front, The others around are ignored. In the mapgen,  at the bottom line there is this: "items": { "~": [ { "item": "homeless_broker_sell", "chance": 100, "repeat": [ 30, 45 ] } ] }
> 
> Wich means all these tiles around the NPC receive items.
> 
> Weird thing is: if I extend the range of floor tiles the list become corrupt, and all food containers are empty. I already noted this selling items to Smoke and the HUB, after a while, next visit and the food is gone and the NPC sell empty container for 0 $.
> 
> The numbers I change for extend the "available items area" are these:   "place_zones": [
> 
>         { "type": "LOOT_UNSORTED", "faction": "wasteland_scavengers", "x": [ 11, 11 ], "y": [ 9, 9 ] },
> 
>         { "type": "LOOT_CURRENCY", "faction": "wasteland_scavengers", "x": [ 11, 11 ], "y": [ 10, 10 ] }
> 
> But like I said, its corrupt in some way.
> 
> I tested with a non mod game version cdda-windows-tiles-x64-msvc-2022-12-02-1620
> 
> Hope my english is clear enough,

It's not really corrupt, that's just a weird interaction between merchant zones and items placed by mapgen. If you change the zone to include the floor, I'd convert all the item groups the homeless broker sells into loot zones, and remove the mapgen-placed items. The merchant items will spawn inside the zone based of the shopkeeper groups. 
I had to figure this interaction out the hard way, don't worry about it.
