### ISSUE TITLE
Crash when trying to (w)ield a greyed-out item from the pick up (g) menu

### ISSUE THREAD

**Issue by aleksandrtikh** [CleverRaven/Cataclysm-DDA#62318]
### Describe the bug

When pressing (w)ield button on a greyed-out item (too large/heavy, or a liquid) in the pick up menu, the game hangs and closes.

### Steps to reproduce

1. Find an item you can't pick up (e.g. have no inventory space to put things in, or find a liquid)
2. Open pick up menu near it (g)
3. Try to (w)ield the greyed-out item

### Expected behavior

The game shouldn't close unexpectedly

### Screenshots

![image](https://user-images.githubusercontent.com/39463222/203003593-e05e2383-efe3-4177-a3fe-4cb76ed71087.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 36 (Thirty Six); Release: 36; Codename: ThirtySix; 
- Game Version: f6e4f2f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

There's no crash.log file in cataclysmdda-0.F/config
The issue might be related to https://github.com/CleverRaven/Cataclysm-DDA/pull/61575 fix, as it's a recent fix in related functionality (I was testing it when I encountered this issue)

**Comment by gettingusedto** [comment]
Sounds like #62314
