### ISSUE TITLE
Milk and Chocolate milk do not seem to reduce thirst.

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62311]
### Describe the bug

My character has been drinking a lot of milk but it doesn't seem to reduce thirst at all.

### Steps to reproduce

Thirsty character drinks milk and becomes more thirsty.

### Expected behavior

Modest reduction in thirst.

### Versions and configuration

Linux 22-11-10

**Comment by NetSysFire** [comment]
1. You dont have all the required info in your Versions and configuration part of the report.
2. Chocolate milk has a quench value of 36. Milk has a quench of 25.

So far I cannot reproduce anything and I suspect one of your used mods, which is supposed to be in that auto-generated report, overrides something.

**Comment by Je55eah** [comment]
Linux
Experimental build 2022-11-10-1351 6f0e11a
tiles
english
dda, no_fungal_growth, alt_map_key

**Comment by oosyrag** [comment]
Doesn't seem to? You can check thirst by going to debug menu, player, edit player, needs. 

Also thirst doesn't change immediately upon drinking.
