### ISSUE TITLE
proficiencies should show sources in the detailed menu reached from the @ screen

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#62312]
### Is your feature request related to a problem? Please describe.

it came up in discord discussion that you can't see which proficiencies a corpse might give you without all of a) standing on the corpse, b) having a light on, c) hitting `B`utcher, and d) cursoring down to the dissect option, even if you've dissected the creature before (and thus your character might remember better than the player which things it gave)

### Solution you would like.

this is primarily focused on e.g. dissection proficiencies, where it would be nice for the game to remember which creatures you dissected to get progress on a particular proficiency, and show them in the proficiencies window. i don't know how reasonable it would be to extend that to e.g. other sources for other proficiencies, or how the game might track which things you'd *actually done* in order to get that progress (it definitely shouldn't show ALL of the possible sources for a proficiency if you haven't dissected all of them).

### Describe alternatives you have considered.

i dunno, giving up on proficiencies? 

the original request was to be able to cursor down to dissect and see which proficiencies a corpse gives even in the dark, but doesn't seem consonant with a lot of our design, particularly if it works on things you've never dissected before. and if the game is tracking which things you dissected, then this issue's proposal should in principle be on the table.

### Additional context

the screen in question.
![image](https://user-images.githubusercontent.com/1569754/202928811-8f6b28c0-0ab2-487b-8714-bfa6aa559a8d.png)

too tired for mockup, please use imagination.

**Comment by PatrikLundell** [comment]
With the current haphazard assignment of creature knowledge proficiencies it's very important to actually be able to see if dissecting this particular invertebrate contributes to the knowledge of invertebrate biology, or if it's one of those that yield nothing (not to mention all the ones that only provide subsequent proficiencies, but don't contribute to the prerequisite).
If you'd change the system to somehow guarantee that new/modified creatures always would fit into the system and contribute to the proficiencies they ought to contribute to an experience based display might make sense, but I don't think the required system will be constructed.

I've certainly lugged corpses with me to dissect, only to find that they don't actually contribute to anything they ought to have contributed to, thus wasting time and energy on a useless corpse.

I guess it might be possible to cram dissection info into the creature and corpse item display info, but it's likely it would contribute more to clutter than it would actually help.

**Comment by esotericist** [comment]
your first paragraph confuses me immensely, so there's some kind of miscommunication happening. i get the feeling that you've somehow misunderstood my suggestion, but it's possible i'm just failing to comprehend what you mean for some other reason.

but just in case: all i'm asking for is for the proficiencies screen to remember something a player *might* remember if they have less fallible memory than i do, and that the survivor certainly should.

> I've certainly lugged corpses with me to dissect, only to find that they don't actually contribute to anything they ought to have contributed to, thus wasting time and energy on a useless corpse.

i mean, you could just bring up the butcher menu? are you also moving corpses around in the dark for some reason?

> I guess it might be possible to cram dissection info into the creature and corpse item display info, but it's likely it would contribute more to clutter than it would actually help.

i don't think this is necessary any more than making butchery let you examine the results without light is necessary.

**Comment by PatrikLundell** [comment]
It appears I've misunderstood your suggestion, as I understood it as replacing the current info with an experience based one. If it's somehow in addition to what we currently have it's not a problem.

I move corpses away from dangerous areas so I can dissect/butcher them without being interrupted by other hostiles. I've also loaded corpses up into my vehicle for dissection back at the base where I have a light source when it's getting late in the day so it would be dark when the dissection is finished, resulting in traveling in the dark if I was to do it in the field.
