### ISSUE TITLE
GIANT size

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#62324]
### Is your feature request related to a problem? Please describe.

DinoMod attempts to model creatures that are bigger than the game engine supports, meaning a lot of weird hacks and lack of realism. Some of that is going to be really hard to fix but some (I hope?) will be a lot easier and I think once it's in the game it will lead to late game vanilla content that uses it. One simple one is that the game does not define a larger monster size than HUGE so the game physics effectively cap out there. Defining GIANT in code will begin to allow that larger weirder content

### Solution you would like.

GIANT, about the size of a whale. Physics including sound, vehicle towing, collisions etc to support it. Ramming into a sauropod hulk with a jeep should feel like it.

### Describe alternatives you have considered.

N/A

### Additional context

This could be used by many many late game things once it's specified, from mutants to blobs to zombie evolutions. It would be used immediately by the sauropods in DinoMod and probably the mosasaurus and tyrannosaurus. EDIT: just the sauropods and some hulk or juggernaut evolutions

**Comment by TiberianErin** [comment]
sounds good
will do it when i learn how
