### ISSUE TITLE
Items in internal containers (like from CBMs) that are set to "hidden" still show up in the drop menu

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62328]
### Describe the bug

So, my survivor has many, many CBMs, including multiple CBMs that have container items integrated into her body. Said containers can be seen and interacted with in the inventory menu, and I can set their contents to "hidden" so that said contents don't clutter up menus. However, this does not work for the "drop" menu - the contents of the containers are always visible, and contributing to clutter, no matter what their containers are set to in any other menu - and I can't modify the settings of said containers within the drop menu, since they don't actually show up in the drop menu, even though their contents do.

### Steps to reproduce

1. Get a character with CBMs that install containers for fuel into the character's body
2. Fill up said containers with their respective fuel
3. Hide the contents of said containers from the inventory menu
4. Enter the drop menu
5. See that the contents of said containers are visible in the drop menu

### Expected behavior

I expect containers set to have their contents hidden will not have their contents show in the drop menu

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: fbfd667 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Useful Helicopters Experimental [useful_helicopters],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Cooler Versatility [coolervers],
    Custom Bionics [custom_bionics],
    XEAS [XEAS],
    return_the_nut [return_the_nut],
    consume_the_nut [consume_the_nut],
    Reproduction mod [perverts],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune]
]

### Additional context

If I were to hazard a guess, I'd say that maybe the fact that the containers themselves don't appear in the drop menu might have something to do with their settings not applying within the drop menu?

**Comment by andrei8l** [comment]
> If I were to hazard a guess, I'd say that maybe the fact that the containers themselves don't appear in the drop menu might have something to do with their settings not applying within the drop menu?

Exactly this and that's intentional behaviour, though maybe we can add a special case for CBM containers

**Comment by NotSeawhite** [comment]
this is kinda out of topic, but i'm very concerned about your modlist

**Comment by AmarinReyny** [comment]
> this is kinda out of topic, but i'm very concerned about your modlist

How so?
