### ISSUE TITLE
crash while wield body bag in pickup view

### ISSUE THREAD

**Issue by hunjixin** [CleverRaven/Cataclysm-DDA#62323]
### Describe the bug

crash while wield body bag in pickup view
but in press w, and select body bag, wield success

### Steps to reproduce

1. press g to enter pickup view
2. select body bag and press w

### Expected behavior

use wield sucess or  should not crash

### Screenshots

dont know how to take screenshot on mint system

### Versions and configuration

version b4d56d32400dc53fd0d054b1bffaaf7c64282478
os mint

**Comment by hunjixin** [comment]
its my save  https://github.com/hunjixin/imgpool/blob/master/save.tar.gz. body bag is left

**Comment by DSeyka** [comment]
Can confirm, apparently https://github.com/CleverRaven/Cataclysm-DDA/pull/62317 didn't fix this. :(

**Comment by andrei8l** [comment]
You need to wait for https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-11-21-1524 to finish building
