### ISSUE TITLE
More convenient carabiner straps (and others)

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#62320]
### Is your feature request related to a problem? Please describe.

Not a duplicate of #61568

Sometimes, my character just decides to put big stuffs on the carabiner strap without telling me. I have to manually find which item it is, and move the item via pocket settings or by dropping. It's really annoying.

I know, pocket settings exist, but prohibiting the pocket from auto-inserting also stops me from strapping my rifle on it without manually inserting it.

### Solution you would like.

Options to add shortcuts to individual pockets for `'Stop wielding item?'` menu, similar to holsters

### Describe alternatives you have considered.

I hardly can think of any other alternatives. Maybe making the carabiner straps or stuffs on your bag not auto-insertable?

### Additional context

![무제263_20221121182629](https://user-images.githubusercontent.com/52661206/203014594-a597892c-469a-4dce-865e-0069d38b96d2.png)

This is what I imagine when my laptop is hooked on a backpack.

**Comment by Je55eah** [comment]
I haven't seen a carabiner in game yet, but if you are describing the long pockets that take weapons and stuff then I think the answer might be to use the whitelist feature to only allow your preferred weapon or to only allow specific categories, such as weapons or guns.

**Comment by NotSeawhite** [comment]
I actually tried those, but it takes way too much time configuring those. No, I'm not lazy, it just lags so much in android, and sometimes it doesn't work at all.
