### ISSUE TITLE
Game constantly reports what's immediately beneath me, even while sleeping

### ISSUE THREAD

**Issue by MichaelMacha** [CleverRaven/Cataclysm-DDA#62339]
### Describe the bug

Every single turn, including while doing passive things (and things which would inhibit me from knowing, like sleeping) the game checks the contents of the tile I'm on, and reports as much to me. This is accompanied by noticeable slowdown of play.

### Steps to reproduce

Pile anything underneath a player, and then attempt to read a skill book or sleep, and watch the results.

### Expected behavior

I shouldn't know if something changes while I'm asleep, and it's excessive for the game to check and report on the tile every single frame, isn't it? I feel like this is a waste of resources.  I'm on an Ryzen 7 at nearly 4.0 GHz, and sleeping alone takes up 6% of my processor. On my older machine it might seriously be unplayable.

### Screenshots

You can see in a screenshot here that it's reported the presence of blankets and pillows over 8000 times. I don't recall this being an issue in the past. It will continue into the hundreds of thousands if I let it!

![Cataclysm Screenshot](https://user-images.githubusercontent.com/7585255/203353208-2059bc97-000b-4a27-bff8-95ee82ad1526.png)

### Versions and configuration

OS: Linux Mint 20.3 Una
Game Version: 0.F-2022.11.18 (c7d375c)
Graphics Version: Tiles
Ingame Language: English
Mods: dda, no_npc_food, no_fungal_growth, package_bionic_professions, aftershock, blazeindustries, xedra_evolved, MMA, StatsThroughSkills

**Comment by MichaelMacha** [comment]
I've confirmed that this issue continues into version 57ec78c on the same transferred world. I checked if it could be mitigated by moving to a different square, and it's admittedly been a while since I last played; but reading and sleeping still seem to take a long time.

As you can see in the screenshot, it continues to report to me that there's a folding knife in my space, in spite of nothing happening that might change that.

![Cataclysm Screenshot 2](https://user-images.githubusercontent.com/7585255/203362565-b3cb321b-2a96-4763-a270-05309a01ef11.png)

**Comment by andrei8l** [comment]
That's in a TCL, right? I was aware of this problem in #58546 but fixing it was out of scope for that PR. Can you please provide your save file to verify?

**Comment by andrei8l** [comment]
Yeah please archive and upload the world directory to a third-party site like https://send.vis.ee/. I'll prune it and re-upload it here in case someone else wants to investigate.

**Comment by MichaelMacha** [comment]
Sure. I threw it on Drive so it has some permanence. Here's the link.

https://drive.google.com/file/d/1LswsPuJ9btB7k7YUU0jQhZYxpzKDwXGV/view?usp=share_link

**Comment by andrei8l** [comment]
/confirmed caused by mapgen updates that overlap the main map, as expected

Thanks for the save file; pruned and reuploaded: [Oso.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10069279/Oso.zip)

**Comment by MichaelMacha** [comment]
Hey, @andrei8l, just to clarify about your comment on TCL, and potentially recognizing the problem. Is this something which is known not to happen at other locations?

**Comment by MichaelMacha** [comment]
WORKAROUND: Stop trying to use all-of-TCL as a studio apartment and study somewhere else. Apparently.

I grabbed a cleared out two-story house as a fallback camp, some distance away from TCL, and sleeping and studying now take just a pinch of time instead of the twelve minute stretches they used to. So the problem is most certainly with one of the unique features at TCL.

Hopefully this won't be too hard to fix, and thanks for the attention guys.

**Comment by TiberianErin** [comment]
never before have i seen a video game's core mechanic bug out because of a structure that the player takes up as a base.

**Comment by MichaelMacha** [comment]
@TiberianEuan Welcome to the dynamic and fast-paced community of CDDA, I suppose.

There are some interesting things there, in the way of underground rail cars and the like; but I think they could be implemented better right now.

**Comment by mark-ik** [comment]
I'm confused, isn't part of the slowdown just that you're sleeping in a place with a lot of items? That's been a longstanding issue no matter where you stay; if you pack shelves with items in your base, the game slows down.

**Comment by andrei8l** [comment]
> I'm confused, isn't part of the slowdown just that you're sleeping in a place with a lot of items? That's been a longstanding issue no matter where you stay; if you pack shelves with items in your base, the game slows down.

Maybe, but in this case the slowdown mostly comes from the overtuned EOCs in the TCL calling update mapgen functions every turn.
