### ISSUE TITLE
Upcycled turret will attack player if player stands on the tile of the enemy it most recently killed

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#62343]
### Describe the bug

If a player stands on the corpse of a monster that an upcycled turret killed, the turret will proceed to shoot and kill the player.

@Venera3 noted on Discord a possible cause: " Mobs remember their target position, and the gun targeting check is only if there's nothing on the tile (not if it's a foe)", and so this behavior isn't limited specifically to upcycled turrets.

### Steps to reproduce

1. Spawn upcycled turret and a monster hostile to it. 
2. Let the turret kill the monster. 
3. Stand on the monster's corpse. The turret will soon decide to shoot you.

### Expected behavior

Upcycled turrets should not shoot the player unless they are provoked and become hostile to the player.

### Screenshots

These screenshots show: The setup to reproduce the bug, and the fact that the turret does not attack until you've reached the exact tile that the monster was killed on. 
![setup](https://user-images.githubusercontent.com/38295275/203496348-959f4ebc-6ae0-4d43-964a-89f4b613b9ca.png)
![approached](https://user-images.githubusercontent.com/38295275/203496370-1d20422e-7656-46f8-af37-7fcf01e44cc9.png)
![attacked when on corpse](https://user-images.githubusercontent.com/38295275/203496376-03093c3b-9ce7-4898-9305-28b2644cc8e3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: b3b97e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Venera3** [comment]
I'm fairly certain the problem lies in `monster::attack_target` returning whatever is standing on the targeted position regardless off hostility (or at least player hostility). I'll take a look later today.

**Comment by KHeket** [comment]
I have already discribed this bug before https://github.com/CleverRaven/Cataclysm-DDA/issues/61837, this also happens with plated turret or exodii quadruped
