### ISSUE TITLE
Deprecate assigning numeric shortcuts to items in inventory screens

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#62341]
### Is your feature request related to a problem? Please describe.

I am always frustrated when...

... picking up or inserting partial stacks of items. Very often, the inventory screen has other items that can be operated on, which have numeric shortcuts assigned to them. So, instead of picking up 10 items A, the character ends up picking up the full stack of item B (marked with 1) and the full stack of item C (marked with 0).

### Solution you would like.

Deprecate assigning numeric shortcuts in the inventory / pickup / insert screen. Leave them in the wear / wield / takeoff interfaces, which operate on single items only instead of stacks - they're actually useful there.

**Comment by andrei8l** [comment]
That would be a simple matter of calling `inventory_selector::set_invlet_type( SELECTOR_INVLET_ALPHA )`.

In the meantime you can also use the `Mark a specific amount of selected item` keybind which is unbound by default.

**Comment by DalenTalas** [comment]
> In the meantime you can also use the `Mark a specific amount of selected item` keybind which is unbound by default.

This is a good workaround, and I've been using it since.
