### ISSUE TITLE
Kevlar dog harness still cannot be disassembled.

### ISSUE THREAD

**Issue by G0BL1N** [CleverRaven/Cataclysm-DDA#62359]
### Describe the bug

Despite this being merged: https://github.com/CleverRaven/Cataclysm-DDA/pull/59030
I can't seem to be able to actually disassemble Kevlar dog harness in-game.
Is there something changed after this PR that's causing a bug? Or am I not understanding the game correctly?

### Steps to reproduce

Try to disassemble Kevlar dog harness

### Expected behavior

I expected to be able to disassemble/salvage it, especially since PR that supposed to fix it was already merged, and the item, in face, doesn't have to have NO_SALVAGE flag right now

### Screenshots

![image](https://user-images.githubusercontent.com/18249498/203778591-9357cdf8-b40b-4a84-aa56-0b172106b875.png)
![image](https://user-images.githubusercontent.com/18249498/203778618-3423fa07-62ef-43d7-a6f7-f61b5e853330.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1110 (21H1)
- Game Version: 63bf9d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
That PR allows you to cut it up, not disassemble it. To actually disassemble it, the recipe needs to be reversible or it needs an explicit disassembly recipe.

**Comment by G0BL1N** [comment]
My bad, thought I tested cutting up. Seems to work, sorry for this 😅
