### ISSUE TITLE
Decimals not being detected

### ISSUE THREAD

**Issue by Foxsgithubcrappyaccount** [CleverRaven/Cataclysm-DDA#62353]
### Describe the bug

At least on two occasions the code register decimals (Ex. 2.0) as zero.

### Steps to reproduce

1. Download from the website
2. Generate a world
3. Error pops

### Expected behavior

It should run idk.

### Versions and configuration

- Windows 7
- Latest experimental version.
- English
- Tiles
- STK, STS, Tamable wildlife, Xedra evolved and magiclysm.

**Comment by andrei8l** [comment]
You'll have to be a bit more specific. Decimals where? What error pops up?

**Comment by Foxsgithubcrappyaccount** [comment]
> You'll have to be a bit more specific. Decimals where? What error pops up?

Mainly in the .json regarding modifiers. 
 DEBUG    : Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0

    "description": "Slip prevention modifier",
    "mod_type": "x",
    "value":
            ^
             {
      "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
      "override_encumb": true,


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 973
 VERSION  : 4034a38

I tried modifying the files but that didn't do much. I think it had to do with something other than the .json itself.

**Comment by mqrause** [comment]
Upgrade your windows or use the msvc build.
