### ISSUE TITLE
[Innawood] Making cement and a concrete mixer is possible, but concrete isn't autolearned

### ISSUE THREAD

**Issue by Mystic-Spider** [CleverRaven/Cataclysm-DDA#62364]
### Is your feature request related to a problem? Please describe.

I was planning on making the faction base out of concrete, since it seems much cheaper in terms of resources. But I only realized that you can't actually make concrete after making the concrete mixer. 

It feels like an oversight, since making concrete is such a simple process.

### Solution you would like.

Simply make the concrete recipe get autolearned.

**Comment by JazzGlobal** [comment]
I know the request was to make cement auto learned but are there examples of making recipes auto learned only after obtaining / crafting another object first? Is this even something we'd want to do since auto learning would cover this anyhow? Just questions as I learn more about the code base
