### ISSUE TITLE
[Innawood] Make some kind of breathing filter available

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#62379]
### Is your feature request related to a problem? Please describe.

There is nothing available that allows you to protect yourself from inhaling fungal spores or get sickened by entering mi-go structures. It would be good if some kind of primitive "gas mask" would be made available.

### Solution you would like.

The introduction of a makeshift gas mask recipe.

**Comment by Mystic-Spider** [comment]
We do have makeshift air filters. Something to use it on that isn't the steam engine would be great. Especially for those scout towers. I almost died to a surprise Goliath Rex in one because of my low speed.

**Comment by PatrikLundell** [comment]
I believe those air filters are flat ones intended to be inserted into a pipe, rather than something that's intended to sit flush to the face. I guess you could use the makeshift air filter a possible component for a human mask, but I suspect it would be easier make that part out of fabric and charcoal.
