### ISSUE TITLE
[Innawood] Make rubber boots available

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#62378]
### Is your feature request related to a problem? Please describe.

There doesn't seem to be anything you can craft that protects your feet from getting burned by acid. Biosilicate chitin boots don't work (not 100% coverage), and rubber boots seem like they should be sufficiently easy to produce from rubber (which you can make) to be reasonable to be available.

### Solution you would like.

Make rubber boot recipes auto learned.

### Describe alternatives you have considered.

Modify rubber boot recipes so they can actually be made if they currently contain components that can't be acquired (like plastic sheets).

**Comment by Mystic-Spider** [comment]
Not rubber boots, maybe. But something like birchbark shoes. Made from rubber.

**Comment by PatrikLundell** [comment]
It's possible to make a makeshift vacuum mold, allowing you to mold rubber, so rubber boots ought to be possible (soles can be made for other footwear, like fur boots). Wraps of rubber wouldn't be water (or acid!) proof.
