### ISSUE TITLE
[Innawood] Big Book of Useless Recipes

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#62377]
### Is your feature request related to a problem? Please describe.

Currently you eventually get a huge clutter of useless recipes in your lists of known recipes. The word "Useless" here refers to the fact that it's impossible to actually craft them, because it's impossible to get the ingredients in Innawood, not whether you'd get any use of what the recipes would have produced.

There are sort of three different categories of such recipes:
- A glut of armor assembly recipes, in particular chain and plate, that assemble armor (pieces) from sub pieces that cannot be produced.
- All the recipes that require synthetic, nomex, or kevlar components, including all survival gear and other unavailable components (such as alternators).
- Miscellaneous recipes that require either components that cannot be crafted, or components that can only be "crafted" by deconstructing something that produces these items even though they were originally constructed out of something you could actually produce (like power converters that were originally makeshift power converters).

There are two problems with these recipes:
- They can fool you into thinking you can actually craft these items, wasting resources trying to produce the prerequisites until you encounter one that actually can't be produced.
- Clutter (that can be worked around by binding the key that allows you to hide recipes and then manually spend time to hide the junk).

### Solution you would like.

Have the mod make all of these recipes learnable only from The Big Book of Useless Recipes, which is nowhere to be find to hide them from the mod.

### Describe alternatives you have considered.

Check carefully that each prerequisite can actually be produced before committing to the pursuit of some item.

### Additional context

Unfortunately, there's probably a maintenance cost to such a book, as things would have to be updated as recipes are changed to actually be (un)implementable.

Also note that the usage of something unavailable in a recipe doesn't automatically make it a useless recipes, only the mandatory use of such ingredients. A lot of recipes allow the use of a wide range of threads, for instance, including unavailable ones, but that's not a problem as several types are available.

**Comment by Mystic-Spider** [comment]
The armor parts can actually be forged in a faction base's smithy. I recommend making the effort to build one. 

Otherwise, yes, this would be a good change. Though some NPCs can spawn with things like plastic bags. Which makes some seemingly impossible recipes viable.

**Comment by PatrikLundell** [comment]
Hm, so there are companion recipes there unavailable to the player (apart from the drop hammer ones)? That shouldn't be the case and should be an oversight.

It's true you can get some odd items through what's essentially glitches in the loot generation adjustments for the mod. I've gotten a rebreather with charges from a feral diver, but I consider that to be a glitch (like the lighters both of my companions had: they're lying in a corner as "forbidden stuff".

**Comment by LyleSY** [comment]
This is a cool approach and good QOL enhancement. I don't think this is happening before the next stable but I like it after
