### ISSUE TITLE
Place compiled, cached JSON files in $XDG_CACHE_HOME

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#62384]
### Describe the bug

Currently, `$XDG_CONFIG_HOME/cataclysm-dda` contains a `cache` dir with the compiled config files.

### Steps to reproduce

1. Have a fresh installation of cdda
2. Start it.
3. Have cache in your config dir, not the cache dir.

### Expected behavior

They should be placed in `$XDG_CACHE_HOME` (defaults to ~/.cache), since this is not the actual, effective config.

Minor issue as the config files are small enough that it does not break things. Some people have the cache dir mounted as a tmpfs (in-ram storage) for extra speed and can not benefit from that.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-12326-gfae2b2ac65b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
Save file fb cache should also be moved out of world directories since they blow up the size and aren't needed for bug reproduction (or really anything besides load perf).

**Comment by NetSysFire** [comment]
Removing low priority because I did not realize saves included massive amounts of them

**Comment by PatrikLundell** [comment]
The original issue might be OS specific, but doesn't the point @andrei8l makes apply to all versions?

**Comment by akrieger** [comment]
The cache dir locations are chosen to make them easy to find and automatically clean up when their corresponding source gets deleted. They also need to be resilient to eg. overridden/customized folder locations. The world cache is inside the world folder so if a world is deleted, so are the flatbuffers, automatically, without any bespoke additional logic needed. Any other location they could grow unbounded without extra checks inside the game at startup to find and clean up unneeded caches. The goal was to be as minimally invasive without adding unnecessary overhead anywhere else. Obviously, we could do more complicated bookkeeping, but I didn't want to block the stack on that being finalized.

> Some people have the cache dir mounted as a tmpfs (in-ram storage) for extra speed and can not benefit from that.

A large benefit benefit of the flatbuffers is that they're persistent, so they're parsed & compiled once and reused after. It's still faster than the old code to parse them on the fly, they're that much more efficient to load from, but it's still a hit to drop them on reboots.

**Comment by akrieger** [comment]
And, yeah, it's about a ~50% size regression on save size, but the end result on compressed save size is like 12mb vs 6mb. It's proportionately large but the net result isn't worth worrying about for bug reporting.
