### ISSUE TITLE
Hazard meteorology quest, crash after trying to sleep, constantly getting error after restarting

### ISSUE THREAD

**Issue by geskeca** [CleverRaven/Cataclysm-DDA#62381]
### Describe the bug

I was doing the hub hazard meteorology quest during a portal storm, and went in and then out of some portal thing that appeared which gave me powers(?), then after the NRE thing beeped a couple times I tried to go to sleep and then the game locked up. I restarted and then this "No default provided for int_or_var_part" error started appearing, even after updating to the latest experimental the error doesn't go away

### Steps to reproduce

Not sure if this is reproducible but,
Stand outside in portal storm for the hazard meteorology quest
Also go inside a strange vortex for the "Investigate Strange Location" quest that appears in a portal storm and then go back out
Try sleeping after portal storm ends

### Expected behavior

Not for this error to appear

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 0236ecd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

My old version where I originally got this error was 76eefb9

**Comment by John-Candlebury** [comment]
This is not a bug with Hazard Meteorology. Its either from the Portal Dungeon or from other storm effect

**Comment by GuardianDll** [comment]
`No default provided for int_or_var_part` is a known issue (#61716), yet i can't recreate the bug on the last dev version
