### ISSUE TITLE
Add Standard long hair for the new hair colour types

### ISSUE THREAD

**Issue by Spacer-1970** [CleverRaven/Cataclysm-DDA#62382]
### Is your feature request related to a problem? Please describe.

There should be standard long hair for the new hair colours (e.g Hair: blue, long , Hair: purple, long , etc) for all the new colours of hair that have been added like blue, purple, green and pink.

### Solution you would like.

There should be standard long hair for the new blue, purple, green and pink hair colours.

**Comment by KilroyWasHere451** [comment]
Created pull request to add color variations to not only the long hairstyle, but also crewcut, mohawk, 'fro, and medium-length hairstyles.
#62657

**Comment by LyleSY** [comment]
This was closed by by #62663

**Comment by LyleSY** [comment]
Sigh, not merged yet sorry
