### ISSUE TITLE
Android: Add options to bind or change default for Esc and SoftKeyboard

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#62387]
### Is your feature request related to a problem? Please describe.

~~It wasn't mentioned anywhere (without searching outside documentation) that double tap is Esc (go back) on the Android version.~~ This is pretty critical to be able to navigate the game. It also doesn't show up when changing keybindings, which leaves the user unable to get out of said keybinding menu. The natural thing to do is hit the back button, which brings up the soft keyboard, which also doesn't have an ESC button by default, leaving the user even more frustrated and half their screen now covered. All in all a decidedly unfriendly first impression, and a barrier to entry.

### Solution you would like.

I'd like for default to be the back button to be bound to ESC, which is natural and intuitive when a user wants to go back. The soft keyboard can be double tap instead.

Preferably, these would have the ability to be user defined in keybinding or options, but I understand that would require additional code and testing.

### Describe alternatives you have considered.

~~Simply having a popup or some prompt at startup or install that lets the user know that double tap is back would be better than nothing.~~

~~Alternatively it could be mentioned in a readme or maybe a the play store description at the very least.~~

### Additional context

The Android experience is actually quite great in general after getting set up, but the [initial setup](https://www.reddit.com/r/cataclysmdda/comments/ppwq9f/cataclysm_dda_on_android_an_indepth_tweaking_guide/) required to do so is rather arduous. I think this would be a nice new user experience improvement to be included for a stable release.

**Comment by ZhilkinSerg** [comment]
There is Conrols section in game description:

![image](https://user-images.githubusercontent.com/16213433/204074940-1cdffcd5-277d-4c01-9997-9328c1df481d.png)

There is also Help & Controls menu accessible during very first launch of the app with the following text:

https://github.com/CleverRaven/Cataclysm-DDA/blob/45f41b9c9f9fa5a82d12623cd2014f950a49d2a3/android/app/src/main/res/values/strings.xml#L6

**Comment by Zireael07** [comment]
That menu should be shown not just on first launch. Many people will skip through "intro" messages w/o reading them carefully, unfortunately (and relying on people reading the long description in Play market isn't a good idea either, most people downloading the Android port already know the game from desktop so won't bother tapping "see more" since the description begins with what they already know.

**Comment by Qrox** [comment]
We could assign virtual keycodes to these gestures so people can rebind these keys in the keybindings menu to whatever actions they want.
