### ISSUE TITLE
dropping spillable liquids like acid in a pit contains it to that tile

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#62399]
### Is your feature request related to a problem? Please describe.

liquids like acid when dropped on the ground spill over to adjacent tiles when there is enough of it, even when dropped on a pit, covering the tile the player is standing on

### Solution you would like.

have liquid pored into a pit be contained to that tile, ideally only spill over to an adjacent pit tiles

### Describe alternatives you have considered.

poring acid off the side of a ledge to a zlvl below so it doesn't spread onto the tile your standing on

### Additional context

![image](https://user-images.githubusercontent.com/115079701/204078305-22636447-dbe3-42ec-b432-f8e0ba06f6fd.png)
![image](https://user-images.githubusercontent.com/115079701/204078310-d315a5da-ac9a-4a24-acbb-404aecfe3cb3.png)
![image](https://user-images.githubusercontent.com/115079701/204078314-7f8fc73b-2ef5-4906-9ec7-49cf6ab4a2b7.png)
ideally want it do this instead
![image](https://user-images.githubusercontent.com/115079701/204078332-91278ee3-2f4a-4e7f-ae0a-162d199f9344.png)

**Comment by RenechCDDA** [comment]
`LIQUIDCONT` exists for furniture and terrain(notably the `recess`) and has similar abilities, but does not have a definable capacity outside of the tile limit, and would not spread liquids evenly among adjacent tiles. However if the goal is only to prevent spillage, adding it to pits would make sense. (NB: I think `LIQUIDCONT` has some functions in examining/using or not-dirtying contained liquids so this may not be entirely appropriate).

**Comment by flybye3o6** [comment]
i will test that

**Comment by flybye3o6** [comment]
that doesn't work because acid when dropped on the ground turns into a field fd_acid
in fact trying to drop acid off a ledge doesn't work either 
![image](https://user-images.githubusercontent.com/115079701/204080230-dc2c2644-9e76-4ca3-b0c5-1c37069307a3.png)
![image](https://user-images.githubusercontent.com/115079701/204080235-04f4bafa-5b63-4093-88f7-3fb18739fc3c.png)
![image](https://user-images.githubusercontent.com/115079701/204080242-12e36582-98b2-4d50-b9d2-12022e9e6374.png)

**Comment by flybye3o6** [comment]
though likely ill take that idea and make a clay/plastic sheet lined pit as a primitive way for storing liquids
if there is a way to convert clean water back into unclean water when dropped, you can drop clean water into a recess and it remain clean
![image](https://user-images.githubusercontent.com/115079701/204080465-f563bd3e-2d7c-4c75-85ba-b8da5b07deb9.png)
