### ISSUE TITLE
XformScale inoperative

### ISSUE THREAD

**Issue by ZeroCreate999** [CleverRaven/Cataclysm-DDA#62397]
### Describe the bug

Setting XformScale but inoperative

### Steps to reproduce

![Uploading XTZEP94X}9QOW7}MJZ`2SGH.png…]()

### Expected behavior

The relevant configuration is which to read

### Versions and configuration

CDDA 0.F-3

**Comment by ZhilkinSerg** [comment]
What is XformScale?

**Comment by mqrause** [comment]
Kinda seems like spam to me.
