### ISSUE TITLE
Conditional enchantments doesn't work

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#62391]
### Describe the bug

Sometimes, in some conditions i didn't research to the end, the conditional enchantments doesn't work
let's pick an example: Wolf sledge in xedra evolved:

I thought to make him a progressive item, so its bash damage increases each spell level
so i make an enchantment:

```json

  {
    "type": "TOOL",
    "id": "mace_magic",
    ...
    "bashing": 27,
    "relic_data": {
      "passive_effects": [
        {
          "type": "enchantment",
          "has": "WIELD",
          "condition": "ALWAYS",
          "values": [ { "value": "ITEM_DAMAGE_BASH", "add": { "u_val": "var", "spell": "summon_mace_magic" } } ]
        }
      ]
    },
    ...
  }
  
  ```
  
  Looks nice for me, isnt it? So i open the game, and see `DEBUG: Expected an int, got a 9`, that point exactly at `"add"` part
  Okay then, i see #61258, think "its not possible it doesn't work, i definitely do something wrong". So i spend time, investigating it, and find i need to move `enchantment` outside of an item. now it's 
  ```json
  
    {
    "type": "TOOL",
    "id": "mace_magic",
    ...
    "bashing": 27,
    "relic_data": { "passive_effects": [ { "id": "WOLF_SLEDGE" } ] },
    ...
  },
  {
    "type": "enchantment",
    "id": "WOLF_SLEDGE",
    "has": "WIELD",
    "condition": "ALWAYS",
    "values": [ { "value": "ITEM_DAMAGE_BASH", "add": { "u_val": "var", "spell": "summon_mace_magic" } } ]
  }
  
  ```
  Yay, now the game boot up. With huge expectations i spawn a sledge, debug 200 lvl of spell, attack a monster... and see default 27 damage. It just doesnt work.
  And it seems the error with items (and maybe with effects, but i did not tested it yet), #62358 worked nice and easy, without any issues

Maybe the `relic_data` cause this?
### Steps to reproduce

<details>
  <summary>Not working json</summary>
  
```json

  {
    "type": "TOOL",
    "id": "mace_magic",
    "name": { "str": "wolf sledge" },
    "description": "A long, solid, crafted steel haft, and a massive, comma-like head.  It feels really massive, but it is easy to wield, and each your level it deal more and more damage.  You even can whisper ancient words to it while you throw it, and it will always return to your hands.",
    "weight": "2150 g",
    "volume": "1750 ml",
    "longest_side": "130 cm",
    "color": "dark_gray",
    "symbol": "/",
    "looks_like": "sledge",
    "material": [ "steel" ],
    "techniques": [ "WBLOCK_1", "SWEEP", "BRUTAL" ],
    "flags": [ "SHEATH_SPEAR", "DURABLE_MELEE", "ALWAYS_TWOHAND" ],
    "weapon_category": [ "GREAT_HAMMERS" ],
    "bashing": 27,
    "relic_data": {
      "passive_effects": [
        {
          "type": "enchantment",
          "has": "WIELD",
          "condition": "ALWAYS",
          "values": [ { "value": "ITEM_DAMAGE_BASH", "add": { "u_val": "var", "spell": "summon_mace_magic" } } ]
        }
      ]
    },
    "to_hit": { "grip": "solid", "length": "long", "surface": "any", "balance": "neutral" },
    "use_action": { "type": "cast_spell", "spell_id": "mace_pipe_magic_throw", "no_fail": true, "level": 0, "need_wielding": true }
  }

```
  
</details>

<details>
  <summary>Working json</summary>
  
```json

  {
    "type": "TOOL",
    "id": "mace_magic",
    "name": { "str": "wolf sledge" },
    "description": "A long, solid, crafted steel haft, and a massive, comma-like head.  It feels really massive, but it is easy to wield, and each your level it deal more and more damage.  You even can whisper ancient words to it while you throw it, and it will always return to your hands.",
    "weight": "2150 g",
    "volume": "1750 ml",
    "longest_side": "130 cm",
    "color": "dark_gray",
    "symbol": "/",
    "looks_like": "sledge",
    "material": [ "steel" ],
    "techniques": [ "WBLOCK_1", "SWEEP", "BRUTAL" ],
    "flags": [ "SHEATH_SPEAR", "DURABLE_MELEE", "ALWAYS_TWOHAND" ],
    "weapon_category": [ "GREAT_HAMMERS" ],
    "bashing": 27,
    "relic_data": { "passive_effects": [ { "id": "WOLF_SLEDGE" } ] },
    "to_hit": { "grip": "solid", "length": "long", "surface": "any", "balance": "neutral" },
    "use_action": { "type": "cast_spell", "spell_id": "mace_pipe_magic_throw", "no_fail": true, "level": 0, "need_wielding": true }
  },
  {
    "type": "enchantment",
    "id": "WOLF_SLEDGE",
    "has": "WIELD",
    "condition": "ALWAYS",
    "values": [ { "value": "ITEM_DAMAGE_BASH", "add": { "u_val": "var", "spell": "summon_mace_magic" } } ]
  }

```
  
</details>

### Expected behavior

It works

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 10a3f17 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

### Additional context

@Ramza13 save my sanity please

**Comment by anoobindisguise** [comment]
is it not working for the same reason as #62200 maybe?

**Comment by GuardianDll** [comment]
as you can see, if i try to apply same fix as 62200, the game wont be able to process it, and just fall with `Expected int, got 9` error

**Comment by Ramza13** [comment]
Added it to my list.  I'm getting a lot more free time and looking to start fixing stuff like this finally.  Thanks as always for the testing and report..
