### ISSUE TITLE
QOL - Make it possible to add "deconstruction zones" in the zone manager

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#62401]
### Is your feature request related to a problem? Please describe.

I want to deconstruct a big set of furnitures but it takes a lot of keypresses.

### Solution you would like.

it would be nice to be able to create deconstruct zones in the zone manager as there is one for disassembly

**Comment by flybye3o6** [comment]
dose construction: blueprint < deconstruct (simple) furniture not work?
i know its not intuitive but im pretty sure that dose work
