### ISSUE TITLE
Extension Cords and Wired Tools

### ISSUE THREAD

**Issue by Playyne** [CleverRaven/Cataclysm-DDA#62416]
### Is your feature request related to a problem? Please describe.

With the appliance system in a quite functional state at the moment, it feels kind of strange to not be able to plug certain tools into the household power grid like you can do in reality. It is possible with furniture or vehicle-sized appliances, but small kitchen appliances like food processors, water purifiers, hotplates, and so on still run on internal batteries. Battery-powered kitchen appliances do exist in reality but aren't particularly commonplace. This was I assume a compromise for gameplay purposes back in the day, since according to the story, the public power grid was out due to the cataclysm, and no system that simulated mains power existed yet. We have one now, so I think it would be a good addition for the game if it were possible to incorporate normally cord-powered tools into the appliance system.

### Solution you would like.

The way I think you'd go about implementing this would be to give certain wired tools a POWER_CORD flag where it would make sense (like hotplates, but not flashlights) that lets them draw power from a nearby appliance power network in range. But this might be a bit finicky if you don't want to use the appliance power in some cases. Another would be to implement a "kitchen counter top" appliance, or allow certain spaces or storage furniture tiles to be wired with an "extension cord hub" appliance, where the flagged tools can either be installed through some unique menu, or just placed into it as items, to draw power (and charge the internal battery if present).
Some tools could have their internal battery compartments removed, to make them purely grid-powered, like most kitchen appliances are, but that might be a harsh balance change many would dislike. Adding additional tool mods, like a power cord attachment to exclusively battery-powered tools, or a battery compartment to exclusively cord-powered tools would add some depth and customization.

### Describe alternatives you have considered.

The UPS conversion kit used to work similarly to my suggestion where you could leave modded tools in a recharge station on a vehicle and let it draw power from the vehicle grid. That quirk was removed around the time battery magazines were implemented, so restoring that feature in some way would be a quick and dirty solution.

**Comment by ParaplegicRacehorse** [comment]
I think this is a great idea, especially if it lets me 'place [item]' on top of existing furniture.  Having to move or destroy useful countertops just to set a stereo on it is annoying.

For power-tools, batteries are the way to go, since the world is currently moving in that direction anyway.  Other items, and especially kitchen appliances, would benefit greatly from this.

(also, @Playyne, the hotplate would be corded while the mess kit would still be battery operated or burn some sort of fuel)
