### ISSUE TITLE
Character should not get dehydrated/starving without  notice when working

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#62411]
### Is your feature request related to a problem? Please describe.

I think it happened to my characters several times: get involve in some construction, disassembly, item fabrication for several hours and discover that your PC is dehydrated or starving. IRL you would stop your activity before getting to that stage. 

### Solution you would like.

Implement a safe guard mechanism to prevent PCs from getting too starving/dehydrated/exhausted... when doing tasks that take a long time. Maybe it could use a similar mechanism to the one  that makes you not work when morale is too low?! Or just a simple message box "your character is hungry/thirsty/sleepy, do you want to continue?"

### Describe alternatives you have considered.

Getting too hungry/thirsty/sleepy affects your morale enough that you stop work-like tasks.

**Comment by andrei8l** [comment]
This is already a thing in experimental versions
