### ISSUE TITLE
Additional Tags for Crafting

### ISSUE THREAD

**Issue by Grendel-0** [CleverRaven/Cataclysm-DDA#62419]
### Is your feature request related to a problem? Please describe.

When trying to figure out what I could make or find in terms of armor pieces, I realized that I could put on another "close to skin" piece of gear in a location. However, there doesn't appear to be a good way, at least in game, to find a way to pick these items out.

### Solution you would like.

It would be lovely if the crafting menu also let you search armor by the coverage layer. Even better, if you could also search by body part.

EG, L:close to skin,b:head

### Describe alternatives you have considered.

Look through every of the dozens or hundreds of items and check the layer yourself. If there's a list you can search online more easily, I haven't found it.

**Comment by KHeket** [comment]
And also it will be helpfull to have ability to search by covering layes via inventory manager and inventory, becouse it will make sorting of clothes and armor much more easyly
