### ISSUE TITLE
Aiming should get better if crouch/prone

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#62410]
### Is your feature request related to a problem? Please describe.
Aiming precision does not improve when the gunner crouch or gets in a prone position. 

### Solution you would like.
Precision and/or aiming speed should improve when crouching and even more when prone. 
Something like : standing +0 crouch +5% prone +10%

### Describe alternatives you have considered.
For balance, aiming could be worsened when standing.
standing -5% crouch +0% prone +5%

**Comment by ZhilkinSerg** [comment]
What would be the reason to aim better? I can only see reasons why one would aim worse.

**Comment by Zireael07** [comment]
Same reason why waiting makes your aim better (Stabilizing)

**Comment by matt32106** [comment]
> What would be the reason to aim better? I can only see reasons why one would aim worse.

https://www.sciencedirect.com/science/article/pii/S2214914719301965

The experimental results have shown that lowest aiming error is obtained when soldiers fire their weapon in the prone or trenched positions.

**Comment by ZhilkinSerg** [comment]
> > What would be the reason to aim better? I can only see reasons why one would aim worse.
> 
> https://www.sciencedirect.com/science/article/pii/S2214914719301965
> 
> The experimental results have shown that lowest aiming error is obtained when soldiers fire their weapon in the prone or trenched positions.

So, crouching does not help?

**Comment by Zireael07** [comment]
Kneeling, which is pretty much crouching + stabilizing in CDDA (as in, you do not move), is between standing and prone, so does help: https://ars.els-cdn.com/content/image/1-s2.0-S2214914719301965-gr8.jpg (pic in the article linked above)
