### ISSUE TITLE
Crash on Autotravel

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#62435]
### Describe the bug

Auto traveling crashes to desktop without explanation or error message, tested on both Android and Windows, error occurs on both randomly.

### Steps to reproduce

1. Autotravel to distant tile
2. Wait
3. Crash

### Expected behavior

Auto Travel does not crash the game.

### Versions and configuration

Os: Windows 8.1
Game Version: 2022-11-27-1427 (Tiles)
Mods Loaded:
  "dda",
  "package_bionic_professions",
  "aftershock",
  "crt_expansion",
  "magiclysm",
  "DinoMod",
  "crazy_cataclysm",
  "my_sweet_cataclysm",
  "MMA",
  "blazeindustries",
  "Tamable_Wildlife",
  "BL9_100monres",
  "secronom",
  "sierra_madre",
  "Arcana",
  "Cata++",
  "Medieval_Mod_Reborn",
  "World_on_fire",
  "Youkai_Disco",
  "Arcana_aftershock_Patch",
  "Arcana_Cata++_Patch",
  "Arcana_Dinomod_Patch",
  "Arcana_Magiclysm_Patch",
  "demon_spider_a",
  "ew_pack",
  "FIC_Weapons",
  "craftgp",
  "Arts' Guns",
  "arsenal_breach",
  "PK_REBALANCE"

Removed third party mods, had no effect.

**Comment by ZhilkinSerg** [comment]
Savegame?

**Comment by Theawesomeboophis** [comment]
I can't provide right now as I don't have access to my pc until the weekend.

**Comment by Theawesomeboophis** [comment]
[Boophis World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10254280/Boophis.World.zip)

**Comment by ZhilkinSerg** [comment]
Cannot reproduce using one of latest game versions, so it could've been fixed. Also you have helluva third party mods - some of them could be the culprit.

**Comment by Theawesomeboophis** [comment]
I thought that too, but when I removed the mods, the same problem occured, but it seems to have been fixed by something as it no longer happens on latest version.
