### ISSUE TITLE
Allow certain weapons (spears, chainsaws, makeshift daggers) to be 'stuck' inside an enemy, forcing the player to either spend a turn removing them, or 'letting go' of the weapon inside the enemy's body.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#62438]
### Is your feature request related to a problem? Please describe.

After checking out a lot of historical weapon articles and videos, it seems to me that general consensus when placing swords as the more popular weapon compared to the spear, despite the latter's superior range, is the fact that spears are very 'individualistic' weapons in that they're reserved for taking care of one enemy at a time, while swords have a lot of versatility when fighting more than one enemy at once. With that in mind, I think the best way to balance them would be to make spears stronger as ranged options, but at the cost of making them slower.

### Solution you would like.

Heavier weapons like spears, daggers, rapiers and others could have a small chance of getting stuck inside a monster's body when you use them, at which point the player could have several options on how to continue fighting. They could let go of the weapon and back off if there's a horde too close to remain fighting, or they could yank it off by standing their ground (S) and resume fighting the usual way. Or the more daring option, to actually **lean in** on the stuck weapon and cause major bleeding, which would be especially devastating if the weapon in question is a chainsaw, as the motorized blade would keep digging into the flesh.

This would also open up the possibility of giving weapons more personality by the different ways they could use. Chainsaws, as mentioned, would be used _specifically_ to get stuck and dig in deep into the zombies, playing up to their cool factor. Makeshift weapons would be the least favourable to this, being more likely to stay stuck in a zombie even if they're slashing weapons. Spears would be quite slow, but also give a lot of damage in return. However, since most of them are one-way weapons, letting them remain inside an enemy is the least favourable - in fact, I think yanking them off the bodies would be the best way to cause bleeding, as if they remain inside it would almost 'block' the blood loss that they're supposed to cause. Throwable javelins would always get stuck with a meaty critical bonus (and shatter inside the enemy if it's a pilum) if the player's throwing skill is high. Rapiers and other fencing swords are also thrusting weapons, but they would be the least likely to get stuck, as being swords, the swordsman/woman would be able to take them out with the flick of a wrist, especially if they have the Fencing martial art.

As a necessary drawback, players who have their weapons stuck would be obviously stuck alongside the weapon unless they either spend a turn to yank it off or let it go. If a weapon is let go, it will either stay inside the monster in question and only retrievable when it dies, or it would fall off on its own depending on the weapon - this would almost always happen with the combat chainsaw, given its sharp automatic edges, for example.

**Comment by Night-Pryanik** [comment]
We have such system a very long time ago (2013-2016), but eventually it was removed in #18754. I don't think this system will ever return.

**Comment by alp7292** [comment]
not fun to play with
