### ISSUE TITLE
Advanced AR glasses cannot be turned off once used to play music

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#62447]
### Describe the bug

AR glasses borrow a lot of functions from e-ink tablets and smartphones, but one thing that was overlooked was a way to switch off the active state. The only thing that sets them to active is playing music, and turning off the music again does not properly switch off the active state. For that matter, neither does letting the battery die.

### Steps to reproduce

1. Open save.
2. Toggle music on glasses.

### Expected behavior

Turning off music being played on AR glasses should stop the batteries from being drained.

### Screenshots

![image](https://user-images.githubusercontent.com/6116024/204302329-8cddb0e3-c68a-4f5a-b8ae-74d40940d54c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.819 (22H2)
- Game Version: 4034a38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context
[Smiley Park (2).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10125716/Smiley.Park.2.zip)

**Comment by FellsHollow** [comment]
I have also been experiencing this issue. Could anyone take a look at this? It's a stale request.
