### ISSUE TITLE
"sounds_like" for guns

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#62442]
### Is your feature request related to a problem? Please describe.

One of the current problems with adding guns and ammo is that right now all new guns are completely silent, as most soundpacks don't cover everything.

### Solution you would like.

We should be able to define a "sounds_like" in JSON to cause a gun to use the sounds of a different gun that likely already has sound effects.

### Describe alternatives you have considered.

no clue how hard this would be.

**Comment by Night-Pryanik** [comment]
Essentially the same as #61706.
