### ISSUE TITLE
Weight load in inventory not being recalculated when 'W'earing a full backpack

### ISSUE THREAD

**Issue by akrieger** [CleverRaven/Cataclysm-DDA#62458]
### Describe the bug

I noticed while loading up loot that the reported load total in my inventory wasn't updating from what my regular gear added up to. I picked up a backpack that weight ~80lb with everything in it but my inventory still reported I was carrying 20/108lb.

### Steps to reproduce

1) Load the attached save.
2) 'W'ear the backpack at my feet.
3) See the weight in my inventory doesn't increase despite the enormous load.

### Expected behavior

I should be at or over my weight limit.

Interestingly, the 'd'rop menu shows the current correct total.

Entering the pickup menu with 'g' seems to have updated my weight total correctly.

### Screenshots

<img width="1276" alt="Screenshot 2022-11-28 at 7 03 03 PM" src="https://user-images.githubusercontent.com/667719/204428762-5db02aa1-9ce2-495d-9cf4-d4ca953d134f.png">

Drop menu:

<img width="1512" alt="Screenshot 2022-11-28 at 7 12 46 PM" src="https://user-images.githubusercontent.com/667719/204429693-4e86f3b3-9e48-4ca9-a65f-488283b73324.png">

### Versions and configuration

- MacOSX
- Version [0.F experimental](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-11-28-0706)

### Additional context

[Kataclysm 8.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10109394/Kataclysm.8.zip)

**Comment by akrieger** [comment]
This seems to repro if I drink out of a hydration pack out of the 'E' menu, which seems to not update my current weight correctly. If I then drop the backpack containing the pack, and pick it back up again, my weight doesn't register right.

**Comment by mqrause** [comment]
Carried weight is cached, so wearing something seems to miss the invalidation call. Pickup and drop menus probably just don't use the cache cause they do more complex calculations anyway.
