### ISSUE TITLE
Videos and functional video / DVD players

### ISSUE THREAD

**Issue by jo-onis** [CleverRaven/Cataclysm-DDA#62467]
### Is your feature request related to a problem? Please describe.

Gaining theoretical knowledge is limited to books, and it feels like something that logically should exist within the game. It also gives the opportunity to have a lot of fun references to various movies and tv shows within the game

### Solution you would like.

The Idea is to have videos that the player can find in various locations.
The two main category of videos would be **For fun** and **Educational** videos

It would essentially work just like books to, but the main difference is that either a laptop or a TV with a video player is required to watch it.

Summary:
* Ability to "watch" a video, (maybe most easily done by activating laptop or tv -> watch video?)
* TV as an appliance that can be installed with the power grid system
* Add videos to locations that makes sense, like the cinema, malls, gas stations
* movie rental store (new location) 

### Describe alternatives you have considered.

Since the scope is large maybe a first step could be to make it possible to watch videos on the laptop and just a handful of videos.
Adding new locations and appliances could be something to consider at a later stage

### Additional context

A potential issue (or feature?) is that it would  bypass the "Hates books" negative trait by giving the player an additional method of gaining theoretical knowledge

**Comment by snipercup** [comment]
This is a good idea and it will be interesting to find out what is the most realistic way to find/use them. I did some quick research and I can't find a movie rental store in new englend in my 5 minute search, but public libraries most definitely have them. Also found a woodturners club in connecticut that has a library of dvd's actually about woodturning. A reddit thread shows users flexing their (blu-ray) dvd collection of up to 10000 disks but how many of them live in new england?

Haven't found any data on blu-ray players yet but a generic 'game console' will be able to play them or perhaps a stand-alone blu-ray dvd player

**Comment by flybye3o6** [comment]
schools should have alterative learning media both old and new
would be nice to find more knowledge on USBs and SD cards unique to them
would also be nice if you can have for fun watching with NPC followers that could improve you relations with them slowly over time gaining trust
could also have some traits for people that learn theory faster by watching or by reading or by mentoring from an NPC

**Comment by jo-onis** [comment]
@flybye3o6 Making it possible to find them on USB-drives and SD cards or any type of external harddrives be a great idea since It's how most people store their movies nowadays.
I also like the idea about watching movies together with NPCs, it could be something that they participate automatically in when they are nearby

And now that you mention digital, copies, maybe it could be possible to make so that the player can burn discs onto external storage, then you would essentially just need one USB or harddrive for all the videos.

**Comment by jo-onis** [comment]
A few loose ideas about content that could be considered educational:

**How was it made (season 1)**
_Can bring your fabrication up to 3_
A show showing various manufacturing processes for everyday objects.

**I should be dead (season 1)**
_Can bring your survival up to 3_
A show about people surviving in the wildereness with harsh weather conditions.

**The dealers of the wheels (season 1)**
_Can bring your mechanics up to 3_
A show about a group of people restoring old cars in their garage

**Comment by Kamayana** [comment]
- 'a'ctivating a screen to watch a movie makes sense for a laptop, but for a TV it would lose out on a quintessential part of the TV experience: watching it from a couch on the other side of the room. I had a thought that you could make 'a'ctivating a screen start the video, but you won't actually stop and watch it until you use use 'R'ead (now 'R'ead/Watch) from anywhere in view of the screen. I feel this would make the experience much more true-to-life; you could even go get snacks in the middle of a movie without interrupting anyone watching with you.
- Movie theaters/Drive-in theaters might make sense as a source for movies, as almost all theaters are digital nowadays. [DCP](https://en.wikipedia.org/wiki/Digital_Cinema_Package)s could just be reskinned encrypted USB drives, though it would be odd to allow copying those theater-quality movies to any device.

**Comment by jo-onis** [comment]
@Kamayana Yeah it would make sense to be able to watch it from further away, Maybe it's a bit like the stereo system appliance in that regard? You turn it on, and it gives a passive boost, then in order to focus on whats on you could use the 'R'ead menu like you said. The character wouldn't actually learn anything unless focusing on it. This way it would also be possible to have the TV on in the backgroud while crafting too for a passive morale boost. Any NPCs in the room maybe hunker down on nearby sofas and chairs as soon as the TV is turned on

Maybe when activating the TV the player would be prompted which video to put on. And only after that it would show up under the Read menu as "**Watch on TV**". If the player also has a Laptop and other videos at hand these would show up under the Read menu as "**Watch on laptop**"
