### ISSUE TITLE
Cataclysm-DDA failed to build with fatal error CVT1100 and LNK1123 with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [CleverRaven/Cataclysm-DDA#62461]
### Describe the bug

Cataclysm-DDA failed to build with fatal error CVT1100 and LNK1123 with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?

**Error info:**
```
     9>CVTRES : fatal error CVT1100: duplicate resource.  type:MANIFEST, name:1, language:0x0409 [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles.vcxproj]
     9>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles.vcxproj]
```
**Error log:**
[DDA_build_error.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10112718/DDA_build_error.log)

**Patch log:**
[DDA_ARM64EC.patch.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10111983/DDA_ARM64EC.patch.log)

### Steps to reproduce

1. Open x64 native tools command prompt for VS 2019
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\Cataclysm-DDA
4. git -C "F:\Cataclysm-DDA" apply F:\DDA_ARM64EC.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
5. cd F:\vcpkg
6. bootstrap-vcpkg.bat 2>&1
7. vcpkg.exe install --recurse zlib sdl2 sdl2-ttf sdl2-image --triplet arm64-windows --clean-after-build 2>&1
8. F:\Cataclysm-DDA
9. mkdir build_arm64ec & cd build_arm64ec
10. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCURSES=OFF -DLOCALIZE=OFF -DTILES=1 -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows ..
11. set PATH=C:\tools\msys64\usr\bin;%PATH%
12. set _CL_=/utf-8 /permissive-
13. set _LINK_=/incremental:no
14. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release CataclysmDDA.sln /t:Rebuild

### Expected behavior

I expected build fine and does not error

### Versions and configuration

OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.21)

**Comment by ZhilkinSerg** [comment]
Try solutions described here - https://stackoverflow.com/questions/10888391/error-link-fatal-error-lnk1123-failure-during-conversion-to-coff-file-inval

**Comment by akrieger** [comment]
Note the cmake build on windows is being updated heavily in #61880, it might be worth trying with that.

That said, why are you using cmake? Are the checked in projects insufficient?

**Comment by alef** [comment]
Try with setting the environment variable `VCPKG_ROOT=F:/vcpkg` and the use `-DCMAKE_TOOLCHAIN_FILE=F:/Cataclysm-DDA/build-scripts/MSVC.cmake` instead of `vcpkg.cmake`. Inside `MSVC.cmake` there is an _include()_ to _vcpkg.cmake_.
The default in linking uses `/MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed` which I guess conflicted with `https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/resource.rc`. For that, I have set `/MANIFEST:NO` in my toolkit file link options.

**Comment by YangYang129** [comment]
@ZhilkinSerg Thanks for your info. According to description, I run `set _LINK_=/incremental:no `and rebuild, these two errors still display:
9>CVTRES : fatal error CVT1100: duplicate resource.  type:MANIFEST, name:1, language:0x0409 [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles.vcxproj]
     9>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt [F:\Cataclysm-DDA\build_arm64ec\src\cataclysm-tiles.vcxproj]

**Comment by YangYang129** [comment]
@akrieger Thanks for your info. Not supported ARM64EC in Cataclysm-vcpkg-static.sln

**Comment by akrieger** [comment]
Alright, that's fair. I can see what it takes to at least partially support it. Maybe not arm64ec for its deps but for the core binary.

**Comment by akrieger** [comment]
#62482 adds arm64ec to the main solution.

**Comment by akrieger** [comment]
The main cdda solution supports arm64ec as a target platform now. I'd be curious to hear if that works for you or if we need more work. It seemed to at least compile on my machine and generated an arm binary successfully.

**Comment by YangYang129** [comment]
@akrieger Thanks for your investigating and info. According to your update, I run `F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64ec>msbuild /m /p:Platform=ARM64EC /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64ec /t:Rebuild  /p:WindowsTargetPlatformVersion=10.0.22618.0 `, display two error:

     3>test_main.obj : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function #__std_init_once_link_alternate_names_and_abort$exit_thunk (EC Symbol) [F:\gitP\CleverRaven\Cataclysm-DDA\msvc-full-features\Cataclysm-test-vcpkg-static.vcxproj]
     3>F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64ec\Cataclysm-test-vcpkg-static-Release-ARM64EC.exe : fatal error LNK1120: 1 unresolved externals [F:\gitP\CleverRaven\Cataclysm-DDA\msvc-full-features\Cataclysm-test-vcpkg-static.vcxproj]

Error log:
[DDA_updated_msbuild_error.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10128620/DDA_updated_msbuild_error.log)

**Comment by BrettDong** [comment]
https://github.com/microsoft/STL/issues/2655

**Comment by akrieger** [comment]
>      2>Link:
>         Cataclysm-vcpkg-static.vcxproj -> F:\gitP\CleverRaven\Cataclysm-DDA\build_arm64ec\cataclysm-tiles.exe

But it did link the main binary successfully.

**Comment by BrettDong** [comment]
So please try the latest Visual Studio and MSVC toolchain and see if the missing symbol problem is resolved.

**Comment by YangYang129** [comment]
@alef @BrettDong @akrieger Thanks for your investigating and info. This project has been built pass
**Steps:**
1. F:\Cataclysm-DDA
2. mkdir build_arm64ec & cd build_arm64ec
3. set VCPKG_ROOT=F:/vcpkg 
4. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCURSES=OFF -DLOCALIZE=OFF -DTILES=1 -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=F:/Cataclysm-DDA/build-scripts/MSVC.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
5. set PATH=C:\tools\msys64\usr\bin;%PATH%
6. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release CataclysmDDA.sln /t:Rebuild
