### ISSUE TITLE
Bulk nails appearing in gun stores

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62471]
### Describe the bug

Nail are appearing in bulk amounts in at least some gun stores.

### Steps to reproduce

Raid a few gun stores. Look for nails.

### Expected behavior

Not so many nails at the gun store.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12406-gc7d375c903 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
/confirmed

From looking at the json it's probably from the `looted_store` item group, which contains an entry of `[ "nail", 5 ],` (that is, a probability of 5 for a group of *100 nails*).

It's not *that* common but it is noticeably more useful than any of the other garbage.

![image](https://user-images.githubusercontent.com/84619419/204646366-91f732c4-8452-4c82-8c87-5db6de414376.png)
