### ISSUE TITLE
Combat knife/Modified combat knife won't attach as mod to SMGs

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#62479]
### Describe the bug

The combat knife used to be attachable to SMGs like H&k MP5A2 or Uzi. Not anymore, even though there is a free underbarrel mount slot.

### Steps to reproduce

1. Have the following ready: H&K MP5A2 or Uzi and combat knife or modified combat knife.
2. Mod the SMG with the knife.
3. Game won't allow it.

### Expected behavior

The SMG should accept the knife as a mod. What's the underbarrel mount for?

### Screenshots

![image](https://user-images.githubusercontent.com/29348635/204684110-2ba191fa-a238-429e-ad01-f4ab9a09d9c2.png)
![image](https://user-images.githubusercontent.com/29348635/204684173-fede6310-e0aa-4f09-8c6d-1f79c5e130c8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600
- Game Version: 8f1cbbf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
You need to use a bottom mount.

![image](https://user-images.githubusercontent.com/84619419/204684574-77b6ffeb-4847-4aac-ad59-0249039763ea.png)

**Comment by jeffplata** [comment]
You mean there's a bottom mount aside from the underbarrel mount? I wonder what guns have those.

**Comment by jeffplata** [comment]
Got it. 
Find gun with underbarrel mount. 
Craft bottom mount. 
Prep and hold gunsmith kit. 
Activate bottom mount. Success hopefully
Activate combat knife. Success always
