### ISSUE TITLE
Can't wear hard hat with attachments/contents

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#62483]
### Describe the bug

A hard hat with contents can't be worn directly. Hard hat attachments are placed inside the hardhat's pockets, and prevents wearing the hard hat.  A hard hat can only be worn when empty.

### Steps to reproduce

Find hard hat with contents "attached", try to wear it. 

### Expected behavior

Can wear hard hat along with it's contents, like any other clothing.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: OnePlus; Model: HD1900; Release: 11; Incremental: 2202112156; 
- Game Version: 45e6e56 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]

**Comment by casswedson** [comment]
should be fixed by #62257
your game version just happens to be a little older than the fix, update and give it another try
