### ISSUE TITLE
[MegaFauna] Add Relevant Proficiencies to Megafauna

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#62491]
### Is your feature request related to a problem? Please describe.

The various wildlife in the megafauna mod lack the 'Principles of Biology' Proficiency, which is a stark contrast to the basic wildlife in CDDA.

### Solution you would like.

Add the Principles of Biology Proficiency to the Megafauna weakpoint list.

**Comment by evankimori** [comment]
Pinging for an update here. Was anything adjusted where this was concerned? I just realized in my own gameplay of this same issue.

**Comment by merrygin** [comment]
I didn't update yet, no. Unfortunately didn't have the time yet - I need to finish up one big old PR I have sitting around, but after that this is right on top of my schedule. :) 

If anyone wants to do it before, feel free though!
