### ISSUE TITLE
Propose to heat food in consumption menu, if there is some heat sources nearby

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#62502]
### Is your feature request related to a problem? Please describe.

I have heat packs in my MRE
I do not use them
I'd like to use them, but its hella lot of micromanagement

### Solution you would like.

Toggle in consumption menu: "ask", "always heat", "only if free", "never"
Each respond for ability to heat up food, if the food accept heating, and if you have some fire or heat source nearby.
Ask - just gives a popup for each consumption action (maybe also add "yes for now" option, that accept heating for this and all next constumption action, but turn back to "ask" if you close the menu) 
Always heat - always try to heat food when you eat
Only if free - allow to auto heat food only if it cost -1 charge (like fire or atomic heater) (maybe also allow to defy what sources may work here - ability to autoheat food in there is an oven nearby, but not from your chemistry set?)
Never - never try to heat food

**Comment by Zireael07** [comment]
Candidate for the Quality of Life label.
