### ISSUE TITLE
Refugee broker giving me nothing for supplies, nor taking anything.

### ISSUE THREAD

**Issue by WreckingAbandon** [CleverRaven/Cataclysm-DDA#62527]
### Describe the bug

The refugee broker, upon getting to the part where he's supposed to tell me how much he's gonna be giving me, tells me I'll receive 0 merch for my 10 meat jerkies. Upon accepting I do get nothing, but my 10 jerkies are still with me.

### Steps to reproduce

1. Go talk to refugee broker while having something like meat jerky in you inventory.
2. Accept the deal.
3. Notice that you do get 0 merch but your meat jerky is still with you.

### Expected behavior

Have it work as usual.

### Screenshots

![Screenshot_20221202-205744_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/105814022/205299750-4ed53a07-1a3b-4c3b-8f18-5571cc338a92.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G9550; Release: 9; Incremental: G9550ZHS6DUD1; 
- Game Version: 380d899 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
/confirm broken by #60939

specifically [this part](https://github.com/CleverRaven/Cataclysm-DDA/pull/60939/files#diff-dbaa22c0fa33ea5e52a18f1ce46db9dcd13311330a9e5130fff6bdf18d67629bR1642-R1647) discards `topic::item_type` and `topic::reason`
