### ISSUE TITLE
 Some of the gun accessories do not work

### ISSUE THREAD

**Issue by g2009532** [CleverRaven/Cataclysm-DDA#62523]
### Describe the bug

I know that the bug related to gun accessories was fixed once in a previous version, but some of them still don’t work properly. First of all, I found in the experimental version released recently that there are still bugs in the gun accessories: the accessories that improve recoil and speed up the aiming speed do not work when installed in the gun.

As an example, when the gun is equipped with the under-barrel laser sight, in theory, the accuracy of firearms will be improved to a certain extent, and the aiming time should be shortened. In fact, the information displayed in the item details column is exactly the same. But unfortunately, when you press the f key to aim, you will find that the aiming time is not shortened, but even longer. However, there seems to be some improvement in accuracy.

The second point is that the gun’s accessories had no effect on improving recoil. No matter how many accessories the gun is equipped with to improve its maneuverability, no matter how much the recoil display of the gun in the menu is reduced, when pressing the f key to aim, and when pressing the "." key stabilizes the firearm, there is no improvement in recoil for any firearm.

While I regret that this issue may cause Kevin has to dive into a mountain of code, looking for bugs that he doesn’t know where to hide and damage his hairline, I still wish for a speedy resolution.

### Steps to reproduce

1. Make a player with two same guns, one with no accessory and another has.
2. Try to aim.
3. There's no way to increase aim level.

### Expected behavior

The accuracy of firearms will be improved to a certain extent, and the aiming time should be shortened, and there should have some improvement in recoil.

### Versions and configuration

Game Version : from 0.f.3 to the newest experimental version

**Comment by oosyrag** [comment]
Most attachments will make a gun take longer to aim, due to the increased weight (and volume/bulkiness).

Recoil has nothing to do with dispersion/accuracy. Recoil affects how long it takes to return to a particular level of accuracy after firing.

**Comment by g2009532** [comment]
Although most accessories will reduce the speed of aiming, accessories such as laser sights can increase the speed of aiming. But such accessory do not work correctly.
In addition, the lack of improvement in recoil I described actually means that the aiming time required to restore optimal accuracy after firing is not reduced. When you use a firearm without any accessories press f to aim and press. AIn addition, the lack of improvement in recoil I described actually means that the aiming time required to restore optimal accuracy after firing is not reduced. When you use a firearm without any accessories press f to aim and press . to Stabilize the gun, after you fire, you will need a certain amount of action points to stabilize the gun again for optimal accuracy.But firearms with all the recoil-improving accessories you've got take the same amount of time to recover, which is obviously not the way they work.

**Comment by g2009532** [comment]
> Most attachments will make a gun take longer to aim, due to the increased weight (and volume/bulkiness).
> 
> Recoil has nothing to do with dispersion/accuracy. Recoil affects how long it takes to return to a particular level of accuracy after firing.


Although most accessories will reduce the speed of aiming, accessories such as laser sights can increase the speed of aiming. But such accessory do not work correctly.
In addition, the lack of improvement in recoil I described actually means that the aiming time required to restore optimal accuracy after firing is not reduced. When you use a firearm without any accessories press f to aim and press. AIn addition, the lack of improvement in recoil I described actually means that the aiming time required to restore optimal accuracy after firing is not reduced. When you use a firearm without any accessories press f to aim and press . to Stabilize the gun, after you fire, you will need a certain amount of action points to stabilize the gun again for optimal accuracy.But firearms with all the recoil-improving accessories you've got take the same amount of time to recover, which is obviously not the way they work.

**Comment by oosyrag** [comment]
Confirmed laser sight isn't working on a USP. Wonder if I'll be able to hunt this one down before stable.

**Comment by oosyrag** [comment]
Recoil/handling mods are also definitely working. The moves required to reach precise aim level on subsequent shots is lowered with a forward grip as opposed to without.

**Comment by g2009532** [comment]
I think this problem may not only exist in the USP .. In fact, I have tested many weapons before, including rifles, submachine guns and pistols.All of them have such problems.And not only the laser sight, but also some other accessories that can speed up the aiming speed are not effective.-------- 原始邮件 --------发件人： oosyrag ***@***.***>日期： 2022年12月14日周三 上午9:47收件人： CleverRaven/Cataclysm-DDA ***@***.***>抄送： g2009532 ***@***.***>, Author ***@***.***>主    题： Re: [CleverRaven/Cataclysm-DDA]  Some of the gun accessories do not work (Issue #62523)
Confirmed laser sight isn't working on a USP. Wonder if I'll be able to hunt this one down before stable.
