### ISSUE TITLE
Impossible Shapes get seen by you while blind

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#62522]
### Describe the bug

I was exploring in a portal storm and an impossible shape spawned, so I activated my Optical Dampers bionic. Nonetheless, I "get a very clear view of the impossible shape" and get the "saw something that hurts to remember" morale debuff.

### Steps to reproduce

See above

### Expected behavior

Being blind should make me immune to that.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 90bc485 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment]
I thought it was intentional that the PC sees them to represent the fact that you are viewing them like the creatures in From Beyond?

**Comment by DalenTalas** [comment]
Recommend leaving this in as Not A Bug. Impossible Shapes violate the laws of (simulated) physics (and reality) by definition.
