### ISSUE TITLE
Kevlar shears do not have the shearing quality like normal shears

### ISSUE THREAD

**Issue by 10asd28** [CleverRaven/Cataclysm-DDA#62531]
### Describe the bug

Upgraded version of the same item lacks a fundamental propriety.

### Steps to reproduce

Compare the two items.

### Expected behavior

Kevlar shears should have at least Lever 1 shearing quality.

### Screenshots

![image](https://user-images.githubusercontent.com/54365106/205327809-5324110e-ed1c-4779-88d7-9fb4dd67e7dc.png)

### Versions and configuration

Version: 380d899

**Comment by bean-b** [comment]
I believe it is because kevlar shears are basically just heavy duty scissors and not actualy shears, because 'shears' can both mean the wool gathering type or just a fancy name for scissor type devices

**Comment by 10asd28** [comment]
> I believe it is because kevlar shears are basically just heavy duty scissors and not actualy shears, because 'shears' can both mean the wool gathering type or just a fancy name for scissor type devices
Would they not be able to shear sheep? If that's the case their name should be changed, as it's misleading.

**Comment by bean-b** [comment]
This is the first image for me for kevlar shears. I'm admittedly not super knowledgeable about sheep shearing, but it does seem to be much more like regular scissors then shears. I do see how the name is confusing, and i could see it being changed, although 
kevlar shears does seem to be the correct name.
![image](https://user-images.githubusercontent.com/84480476/205351298-2314c452-fec0-4b0a-ad08-8e8b86d83994.png)
another kevlar shear
![image](https://user-images.githubusercontent.com/84480476/205351747-4b260d5c-d86a-44a3-a577-46c6edbfbe74.png)

wool shears
![image](https://user-images.githubusercontent.com/84480476/205351598-fa6bef1c-74a4-4931-aa23-47051b2ca908.png)

**Comment by Maleclypse** [comment]
This is a case of the english language being complicated and you shouldn't shear animals with kevlar shears nor should you cut paper with your wife's fabric scissors.

**Comment by Zireael07** [comment]
Could a better description of "kevlar shears" clarify this? I admit I was confused too, and while not a native, I'm an English major, yet I never knew that shears do not necessarily shear wool :P

**Comment by bean-b** [comment]
> Could a better description of "kevlar shears" clarify this? I admit I was confused too, and while not a native, I'm an English major, yet I never knew that shears do not necessarily shear wool :P

I think a better description of shears could be good!
