### ISSUE TITLE
The Bōjutsu martial art needs an update

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#62541]
### Is your feature request related to a problem? Please describe.

Bōjutsu was originally added in #50010, but the author went missing shortly after publishing the PR and it ended up being merged without changing from its original design, even though it contains the now in extinction feature of block counters (Which was being removed from all martial arts at the time, but the PR in question was merged until much later so it did not receive attention in #51949 ), the martial art did not take any suggestions into account when merged unless they were implemented directly by reviewers/mergers, so several issues with the martial art remain without attention or solution from when it was first designed.

@Hymore246 made a good [comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/50010#issuecomment-908772079) about the issues the martial art presented in its inception (And which continue until now):

> At a glance, I think this style is overpowered. It is a weapon style that has a lot of damage boosting techniques that do not require any effort to use. The only one that does require a buff is VERY strong, weighted to happen more often, and comes from an OnMove buff that boosts damage even further. Combined with the damage cap remover (which I am not 100% sure we should do, might want to ask a dev) it does a lot of damage. Lastly, it isn't like the style's weapons need the boost either. The Long Stick (weakest weapon) has 18 bash damage and the Ironshod Quarterstaff (strongest weapon) does 32 bash damage. I don't understand how the "damage potential is super high" is a weakness given all these things. Also, being able to stun or knockdown enemies with a counter is VERY good. Good enough that the counters in Dragon Kung Fu and Medieval Swordsmanship have damage penalties to compensate.
> 
> From my research, Bojutsu is versatile. You can strike a lot of way with a Bo Staff so the style has potential. Here are some thoughts that might help improve the style:
> 
>     1. Get rid of he damage boosts. If you want to keep one, save the boost for something that requires a buff or is a buff that doesn't happen often.
> 
>     2. For the life of me, I cannot find videos of people using the staff spin in a fight. I think it might just be a kata to get the practitioner used to moving the staff around. Still maybe it could be used as a shielding technique/buff to keep enemies at bay? Also having the staff spin as an OnMove buff is a bit silly conceptually because it means the player is spinning that staff 24/7 as they move around the world. Helicopter power!
> 
>     3. Misdirection seems to be a big part of Bojutsu. It is _really_ easy to lose track of the staff and get hit with a different side or a different spot than you expected. This might be hard to add to the game but +Accuracy seems like the easiest way to show that. +Crit Chance might work too but that is a strong type of buff.
> 
>     4. I recommend using "double strike" as the style's theme/gimmick. Sort of like you hit with one side of the staff and follow up with the other. You could do it a number of different way but the feint/disarm video showed it being a quick follow up to a strike. Maybe a have a Rapid (or even a 50% move cost) tech with high weighting enabled from an OnCrit buff? Another way might be to mess around with move cost reduction when you hit several times in a row.

### Solution you would like.

- To see the counters removed so the martial art style is normalized like the rest with the respect of counters, since they are supposed to be being phased out.
- To see an adjustment of the power levels of the martial art, since it does seem pretty overpowered in raw damage in contrast with the other styles already balanced with one another.
- To give a new gimmick to the martial art, since it only seems to care about raw power while also giving stuns, downing, and being quick... 
- To see more love for this staff-only style

### Describe alternatives you have considered.

To just leave it as it is and forget about it?

### Additional context

You can easily see the techniques and buffs of the style in the description of the original PR (It hasn't changed since then), or with the [hitchhikers guide](https://nornagon.github.io/cdda-guide/#/martial_art/style_bojutsu).

**Comment by Maleclypse** [comment]
I wonder if the staff spin could do a pushback attack with zero damage on living creatures to represent them moving away from wildly flying wood and a low damage attack on zombies/monsters with no fear of being hurt.  I imagine this would require the spell/eoc system being tied into MA but I don't know if we have that yet.

**Comment by Termineitor244** [comment]
> I wonder if the staff spin could do a pushback attack with zero damage on living creatures to represent them moving away from wildly flying wood and a low damage attack on zombies/monsters with no fear of being hurt. I imagine this would require the spell/eoc system being tied into MA but I don't know if we have that yet.

I do not think we have a system in place for something like that, but it could be interesting to try it in a martial art.
