### ISSUE TITLE
Ethanol Burner CBM charges at high speed and generates high heat.

### ISSUE THREAD

**Issue by bocchisaimu** [CleverRaven/Cataclysm-DDA#62557]
### Describe the bug

When the Ethanol Burner CBM is activated, it charges instantly to maximum power and emits high heat.

### Steps to reproduce

1: Install Ethanol Burner CBM.
2: Fill Ethanol Burner CBM with fuel.
3: Start Ethanol Burner CBM.

### Expected behavior

Ethanol Burner CBM generates power slowly and dissipates heat slowly.

### Screenshots

![before　Ethanol Burner CBM](https://user-images.githubusercontent.com/74813915/205473984-c2a4a11d-e0a3-42a0-88d3-7bdd4bfef8ec.png)
![after Ethanol Burner CBM](https://user-images.githubusercontent.com/74813915/205473991-7f13decc-587f-4c19-b836-46ba0c14338a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: ec0f3a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I am Japanese and have no experience using github, so I may not be able to write well. Sorry.

**Comment by anoobindisguise** [comment]
The issue is that fuel like ethanol, methanol, and denatured alcohol are each 1 mL, but other stuff is bigger (vodka is like 36 mL each. Other alcohols are 250 mL) so it's burning tens or hundreds of times as much fuel as expected, so the game has to generate 1.5 mJ of waste heat instantly instead of gradually as expected which crestes the thermonuclear heat cloud hotter than a migo tower that then quickly incinerates you jf you stand still in it.

**Comment by DalenTalas** [comment]
So, kids, what have we learned today? DO NOT fuel your Ethanol Burners with vodka unless standing something really really cold. Siberia comes to mind as the most appropriate area.

(Add obligatory joke about bears fueled by thermonuclear balalaika reactors.)
