### ISSUE TITLE
Advanced Inventory Manager Hanging Open

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62553]
### Describe the bug

Periodically, my advanced inventory manager hangs open and won't be closed via the normal escape key. When and why this happens appears inconsistent, but it has only occurred after moving an item from one pane to the other.

### Steps to reproduce

Unknown

### Expected behavior

UI should close consistently.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12607-ge1d367543b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Kamayana** [comment]
I actually investigated this issue myself and opened #62551 for it. It turns out it specifically occurs when you move an item to a space adjacent to it, and then immediately try to close AIM.
