### ISSUE TITLE
Greyed-out overmap

### ISSUE THREAD

**Issue by reusityback** [CleverRaven/Cataclysm-DDA#62568]
### Describe the bug

Suddenly, when I wanted to target a fast travel on the overmap, the overmap greyed out leaving only notes as markers.

### Steps to reproduce

Have this bug occur... 

I don't know what happened.

### Expected behavior

To not have this happen again and a way to save the savegame

### Screenshots

![Screenshot_20221204_220402](https://user-images.githubusercontent.com/98353605/205515725-ed8815b3-013b-46dd-b013-b271c334fbd2.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: ec0f3a4 [64-bit]
- Graphics Version: Tiles
- Game Language: Systemsprache []
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10149490/debug.log)
Savegame: [2022-12-03.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10149492/2022-12-03.zip)

**Comment by ZhilkinSerg** [comment]
You have pressed `w` (that toggles visible weather overlay) instead of `W` (that confirms auto travel destination).
