### ISSUE TITLE
[Innawoods] Random Spawn Trader is Modernist

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#62566]
### Describe the bug

The trader npc that spawns randomly is modernly clothed and armed.

### Steps to reproduce

1.Spawn or Find Trader NPC (back Holster with ar-15)
2. Compare to other Npcs

### Expected behavior

All Npc's in innawoods should have only primitive clothing and weapons. It doesn't make sense that the random trader npc breaks this rule.

### Screenshots

![image](https://user-images.githubusercontent.com/91917075/205510649-da7d6f3e-6854-4f0c-95e2-17681b8d8bc2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.819 (22H2)
- Game Version: 380d899 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Megafauna [megafauna],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by LyleSY** [comment]
Closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/62597
