### ISSUE TITLE
Appliance "welding kit rig" doesn't allow repairing tempered carbon steel materials 

### ISSUE THREAD

**Issue by harmonickolobok** [CleverRaven/Cataclysm-DDA#62569]
### Describe the bug

Appliance "welding kit rig" is created by contruction menu "Place Welding Kit" using item "welding kit".
Item "welding kit" is a direct upgrade of "arc welder" by allowing repairing items made of "Tempered Carbon Steel" and "Tempered Carbon Steel Chain" materials. However when placed as appliance it works only as base "arc welder".

### Steps to reproduce

1. Place fully charged "very large storage battery" as appliance using construction menu "Place Very Large Battery"
2. Have 2 "welding kit" items, and a charged medium battery
3. Place one of the "welding kit" items using contruction menu "Place Welding Kit" next to placed "very large storage battery"
4. Reload the other "welding kit" with medium battery
5. Have a damaged item made purely from "Tempered Carbon Steel"(for example "tempered nodachi").
- to damage an item you can drive a moderately heavy vehicle over that item(run wheel over it)
6. Activate item "welding kit"(with loaded medium battery) and check that damaged item made from "Tempered Carbon Steel" is in the list. Note "welding kit" written in top left corner in "Tool:" section.
7. Interact with appliance "welding kit rig". See that there's no choice like "Use welding kit". Choose instead "Use arc welder". Note the absence of that damaged item made from "Tempered Carbon Steel" in the list. Also note "arc welder" written in top left corner in "Tool:" section.

### Expected behavior

Appliance "welding kit rig" is able to repair items made of "Tempered Carbon Steel" or "Tempered Carbon Steel Chain" materials just like "welding kit" item.

### Screenshots

![ItemWeldingKitRepairMenu](https://user-images.githubusercontent.com/6259259/205518814-f69b6047-563b-4f22-9867-f950eba5d3f2.PNG)
![WeldingKitRigInteractMenu](https://user-images.githubusercontent.com/6259259/205518818-e8baa3d7-0ba8-4694-bf1b-700fb81ed5fa.PNG)
![WeldingKitRigRepairMenu](https://user-images.githubusercontent.com/6259259/205518822-153b7339-3778-4e37-8ea0-6101703c6142.PNG)

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental, cdda-windows-tiles-sounds-x64-msvc-2022-12-01-2057
- Graphic version: Tiles
- Ingame language: English
- Mods loaded: "Dark Days Ahead", "Disable NPC Needs", "No Fungal Growth", "Bionic Professions", "Blaze Industries", "Stats Through Kills"

**Comment by harmonickolobok** [comment]
I guess it's because this appliance is directly inherited from "welding_rig" without overriding "pseudo_tools" parameter (data\json\furniture_and_terrain\appliances.json):
  {
    "type": "vehicle_part",
    "id": "ap_weldkit",
    "name": { "str": "welding kit rig" },
    "description": "A welding rig combined with a fireproof insulating blanket allows for advanced welds and repairs to tempered steels that draws power from the vehicle's batteries.  You still need glare protection.  'e'xamine the tile with the rig to use it to repair items in your inventory.  If you attempt to craft an item or perform a repair that requires a welder, you will be given the option of using the welding rig.",
    "item": "welding_kit",
    "flags": [ "CARGO", "OBSTACLE", "APPLIANCE" ],
    "copy-from": "welding_rig"
  },

**Comment by harmonickolobok** [comment]
However when I added:
"pseudo_tools": [ { "id": "welding_kit", "hotkey": "w" }, { "id": "soldering_iron", "hotkey": "s" } ] to the end of definition of "ap_weldkit" appliance and tested - game crashed.

**Comment by TealcOneill** [comment]
Was not able to reproduce, I could easily repair any tempered carbon steel items. @GuardianDll 
OS: Windows
OS Version: 10.0.19045.4291 (22H2)
Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]
]
