### ISSUE TITLE
Random Scav/Trader NPCs Are Bad Followers

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#62565]
### Describe the bug

While Npcs that spawn as traders can be recruited, they don't take orders from you and potential block your activities. this even includes items they have not transferring ownership, preventing them from being moved.

### Steps to reproduce

1. Find or spawn wasteland trader npc (the one with the back holster and ar-15)
2. Recruit them into your party
3. Perform various npc tasks such as assignment to faction camps or zone tasks.
4. Note their abnormal behavior.

### Expected behavior

If they are recruitable like with normal random npcs, or even the guaranteed npcs such as the refugee beggars, it would stand that random trader npcs would be able to be ordered about like normal.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.819 (22H2)
- Game Version: 380d899 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Megafauna [megafauna],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Kantonine** [comment]
![image](https://user-images.githubusercontent.com/91917075/205511679-14d217fb-2f91-45d1-b4f6-2332150b7a1b.png)
This might also be helpful to see as well (Bernie is the NPC in question)

**Comment by andrei8l** [comment]
`SCRAP_MERCHANT` has `"common": true` but it should be false
