### ISSUE TITLE
Canvas items can be repaired only with needle or bone needle

### ISSUE THREAD

**Issue by WarBarista** [CleverRaven/Cataclysm-DDA#62595]
### Describe the bug

When I tried to fix my duster with a sewing kit, I couldn't do it. Looking into the description of the item, I found that it can only be repaired with a needle or bone needle. The same situation happened with work pants and a work T-shirt.

### Steps to reproduce

1) Use the sewing kit to repair  the duster
2) Find that there is no duster in the list of repairable items

### Expected behavior

I expected that I would be able to repair canvas duster  with sewing kit.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: bc4a745 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Магиклизм [magiclysm],
    Развитая XEDRA [xedra_evolved],
    Характеристики за убийства [stats_through_kills]

### Additional context

I feel like the majority of canvas items (or all of them) has the same issue, yet I am not sure.

**Comment by WarBarista** [comment]
I am sorry for the extremely long delay, but here is the screenshot of my duster and tailor's kit, which strangely mentions only needle and bone needle. I haven't modified the game file and I  am using only the abovementioned mods. Maybe it is  concerned with  the language? I guess I will check this.
![Снимок экрана (44)](https://user-images.githubusercontent.com/73230104/206662355-2cbd624c-1035-4405-bb7a-4f453a6bded2.png)

![Снимок экрана (46)](https://user-images.githubusercontent.com/73230104/206662963-8d05aacd-33b9-4efe-87f8-97a8901e7c5a.png)

**Comment by Night-Pryanik** [comment]
Could you please post your savegame somewhere? I'll test in on my machine.

**Comment by WarBarista** [comment]
Alright, I hope i've done the export right
[Фронтон.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10193477/default.zip)
