### ISSUE TITLE
"stats_tracker" in .sav massively bloats save game load time

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#62591]
### Describe the bug

The contents of "stats_tracker" in the .sav of world folder accumulate heavily over the course of a world save and cause the time to load the world to skyrocket.
I have included a world save that takes over 25 minutes to load along with a .sav with "stats_tracker" deleted. Said save is only on summer, day 7.

### Steps to reproduce

1. Download the attached save (warning, it is very large)
2. attempt to load the world save in game. Observe long load times.
3. Replace the .sav with the contents of the secondary folder or manually delete the contents of "stats_tracker" such that it looks like "{ },"
4. Load times should be almost instant.
5. Run a profiler and see exactly where in the code this is breaking down.

### Expected behavior

Load times shouldn't become so insanely long. "stats_tracker" is, near as I can tell, entirely superfluous information although I do not know this for sure.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 6d45ade [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

### Additional context

https://drive.google.com/file/d/1neCBlaZYR_aN9wWVBvWy-SZntfH3T571/view?usp=share_link

**Comment by ZhilkinSerg** [comment]
![image](https://user-images.githubusercontent.com/16213433/205821992-a377ee24-1b19-4783-82f9-4e7e701777f6.png)

![image](https://user-images.githubusercontent.com/16213433/205822084-ca9db73a-53f1-4f73-8ef4-5d37d788dc91.png)

![image](https://user-images.githubusercontent.com/16213433/205822146-066713c2-000d-49c7-9a6c-7ae687d24738.png)

![image](https://user-images.githubusercontent.com/16213433/205822165-f340e3a6-0b7c-4128-b24e-c5a122b06f4c.png)

**Comment by ZhilkinSerg** [comment]
Linted `stats_tracker` node from `#VmVyb25pY2EgS25pZ2h0.sav`

[stats_tracker.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10162874/stats_tracker.zip)

**Comment by kevingranade** [comment]
evemt_ty p_event_source::get() is making a copy of the event_multiset, that sounds expensive.

**Comment by ZhilkinSerg** [comment]
`avatar_enters_omt` is especially big there - clearing removing it loads instantly.

**Comment by RenechCDDA** [comment]
#61407 seems related, but neither the reporter nor triage mentioned any abnormally long load times. The save in that issue had 66,727 entries of `avatar_enters_omt` in it. This save appears to have 39,981 instances in it, according to the cleaned stats_tracker.

Unfortunately the save from the linked issue is 404'd, but I've been trying to load the save from this one and it's been using all of a single core's CPU for 25 minutes and counting. Building from 053ba983c0f1bd6bd86d61742420de50e19bb281 (current master at the time of this writing)

**Comment by RenechCDDA** [comment]
With #64844 merged, this save now takes 15 seconds to load.
