### ISSUE TITLE
0.G String Freeze

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#62603]
We're on the final path of stable! With blockers nearly out of the way it is time to enter String Freeze. At this point we will stop merging any PRs that change translatable strings in the game, such as dialogue, item descriptions, and anything else a player might read that would need to be translated to another language. This will give our beloved translators some time to get caught up so that Stable can release with language support.

As usual, some sufficiently small PRs may be allowed through the filter, and any PRs which work towards solving release blockers are exempt from this. However by this stage of Freeze, we will be dramatically reducing the rate at which we merge things for a little while. Please bear with us during these final stages.

Please follow along the [0.G project tracker](https://github.com/CleverRaven/Cataclysm-DDA/projects/50) to see what else needs to be done before we can get this release out. Very little remains!

Note that in previous years we have sometimes at this point created a new 'experimental' branch to merge completed PRs that are stuck in freeze, but due to limited available developer time I don't think we'll be doing that this time around. It will just have to be a bit quiet for a while. With luck it should be short!

**Comment by Hirmuolio** [comment]
Could #62363 and #62365 get in before stable so the "joule as power" json do not get into stable.

**Comment by perryprog** [comment]
Can #62234 get in before stable, as it fixes the currently broken install target on *nix systems.

**Comment by misterprimus** [comment]
Can we add https://github.com/CleverRaven/Cataclysm-DDA/issues/51172 ?

**Comment by Altogolik** [comment]
A broom is not cool, I want a flying motorcycle (developed by a technomagician)

**Comment by reinerh** [comment]
Debian will have their [soft freeze](https://release.debian.org/) in about two weeks. Is there a chance 0.G will get released before so that it can make it into the next Debian stable? (I'm maintaining it in Debian and would upload it asap)

**Comment by NetSysFire** [comment]
@I-am-Erk, @kevingranade how close are we to release? Is the above possible to accomplish?

**Comment by cake-pie** [comment]
I'm hoping #63488 can make it into 0.G so that the new character swap feature doesn't ship with known flaws.
