### ISSUE TITLE
Material inheritance and armor

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#62607]
### Is your feature request related to a problem? Please describe.

Per discussion with Korgent about material inheritance, I've written a proposal for how inherited materials would impact armor.

### Solution you would like.

Key points would be: 
1. Grouping materials, all steels, bronze, iron, copper, etc. so they can be used interchangeably like toolsets. 
2. Determining what can be interchangeable on armors. Steel and bronze chainmail could be swapped out, but swapping nylon belts for leather straps may not be as viable.
3. Encumbrance is primarily determined by form rather than weight. As long as materials are roughly equal in density, swapping between them should not significantly impact encumbrance. Bronze platemail will be heavier, but the result will not be bulkier.
3. Breathability and warmth are determined by material score, so that will allow players to make warmer or more breathable versions of some clothing.

**Comment by bean-b** [comment]
I'm sure it would be hard to implement, but from a ux perspective if the crafting process of say plate mail went -> craft light platemail -> choose material -> craft it, it would be very user freindly imo, and allow items with materials like graded steel to be devolved and crafted very easily

**Comment by Zanthra** [comment]
Add in the light medium and heavy variants for things like platemail and survivor gear.

**Comment by PatrikLundell** [comment]
I'm definitely in favor of reducing recipe clutter. However, one potential issue is that different materials may require different proficiencies different skill levels (and possibly even skills), and different tools, such as redsmithing vs. blacksmithing, and "normal" cutting vs. kevlar shears.

The current half broken recipe compression system illustrates some of the problems with its top level requirements description not bearing any obvious relation to the (available?) recipes within it.

**Comment by Zanthra** [comment]
Have the base recipe show up in blue, similar to current variant recipes, then when selected it would open a new "crafting configuration" window, where on the left it has the material, weight, and other selectable options, and on the right it shows a preview of the crafted item using those materials. The material options on the left could highlight when you have the materials necessary for crafting. At the top of that right hand panel would be the skill requirements, proficiencies, crafting time, and failure chances just as it shows for the previews currently.

This could be used to replace the old system where people choose what materials to use in crafting in general, such as when you have multiple types of thread, or different food ingredients (of which there are actually 2 systems, one gives you a set of combinations of materials with a 1 2 3 etc list, and the other steps through each material in detail).

**Comment by Raikiri** [comment]
Is it ok to reopen stale but important issues like this hoping that somebody could pick them up?

**Comment by bean-b** [comment]
> Is it ok to reopen stale but important issues like this hoping that somebody could pick them up?

i think so, stale bot has a bad habbit of marking as stale and closing all sorts of things. Its kinda silly imo, closing issues doesnt mean the issue is actually fixed and just results in people spending more time re-opening issues and stuff
