### ISSUE TITLE
Crater explosions being counted as player kills.

### ISSUE THREAD

**Issue by Danificada** [CleverRaven/Cataclysm-DDA#62605]
### Describe the bug

monsters killed after walking close to a crater map extra gave me achievements and kills, and made me lose the pacifist conduct, even though i didnt set the explosive.

### Steps to reproduce

walk close to a crater with monsters inside and watch them die and give you kills

### Expected behavior

a random explosion not giving me kills.

### Screenshots

![image](https://user-images.githubusercontent.com/71234906/205998319-6c7fa025-8101-4985-8831-f1029a51cc0f.png)
![image](https://user-images.githubusercontent.com/71234906/205998418-2d508f7c-c34f-411a-987f-5450c4b12650.png)
![image](https://user-images.githubusercontent.com/71234906/205999232-8995e7fc-0844-49a6-84d4-8bf6c89ce6c6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2251 (22H2)
- Game Version: 7fedebb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by DSeyka** [comment]
Seems to be same issue as https://github.com/CleverRaven/Cataclysm-DDA/issues/62181
