### ISSUE TITLE
Cannot insert solid fuel into bionic fuel containers (affects mods)

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62617]
### Describe the bug

So, as described [here](https://github.com/chaosvolt/cdda-arcana-mod/issues/304), there are some issues with the way solid fuel is handled by bionic fuel containers - specifically, there is no way to insert solid fuel into said containers. They can't be reloaded, trying to insert the fuel from the inventory menu doesn't work, etc..

### Steps to reproduce

1. Use a mod that adds a bionic that turns solid fuels into electricity
2. Try to load said fuel into the bionic's fuel container
3. Witness that you cannot

### Expected behavior

I expect fuel containers to work just as well with solid fuels as they do with liquid fuels and batteries.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: fbfd667 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Useful Helicopters Experimental [useful_helicopters],
    Arcadia Mapgen [custom_arcadia_mapgen],
    Cooler Versatility [coolervers],
    Custom Bionics [custom_bionics],
    XEAS [XEAS],
    return_the_nut [return_the_nut],
    consume_the_nut [consume_the_nut],
    Reproduction mod [perverts],
    Magiclysm Runes in Arcana Recipes [Custom_ArcanaRune]
]

### Additional context

I know that I'm experiencing this problem with content from a non-mainlined mod, but given that we've tried making the mod work on that end, and ended up realizing that A. we can't make it work even with making sure that the bionics'/containers' code matches up perfectly with their vanilla counterparts, B. there otherwise is no indication that the problem comes from the mod itself, we think it's pretty safe to say that there's something wrong with the way the game handles solid bionic fuel. This would also mean that this problem will effect not just Arcana, but any mod, or even future vanilla content, that adds in bionics/containers meant to use solid fuels.

EDIT: Just to be clear, the bionic fuel containers are coded in a way that matches the way bionics now work in vanilla to a t. They still don't work.

**Comment by Hirmuolio** [comment]
I found the problem. There is weird check in reloading code that allows reloading `CONTAINER` type pockets only with liquids.
This is most likely to make it more convenient to reload bottles with drinks.

You can use the insert method instead. Look at the fuel tank and select (i)insert item. There you can put the essence in.
Except that one seems to be bugged and does weird things...

You may also need to disable fuel saving mode. Single charge of essence has 1200 kJ of energy and fuel saving mode will try to not waste it.

**Comment by AmarinReyny** [comment]
> You can use the insert method instead. Look at the fuel tank and select (i)insert item. There you can put the essence in.
> 

Already tried the insert method. It didn't work.

> You may also need to disable fuel saving mode. Single charge of essence has 1200 kJ of energy and fuel saving mode will try to not waste it.

That'd be something to worry about if and when we finally manage to get any essence into the container.
