### ISSUE TITLE
Large Cardboard Boxes & Thievin'

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#62619]
### Describe the bug

Deploying a large cardboard box and sliding it onto an owned item will allow you to move the item out of it's owner's sight without repercussion.

This is giggly fun when you want to steal a rifle or something a dead guy dropped in the refugee center, but it's economy breaking when used to appropriate a merchant's entire wares. When wares respawn, it's just a free-for-all.

### Steps to reproduce

Deploy a cardboard box next to a merchant's wares. Slide it on top of the items you want. Drag it away.

You may need to deconstruct furniture if the items are sitting on something, but once you do, the spare parts become owned by you and are no longer a hindrance.

### Expected behavior

Merchants should notice you stealing their entire shop contents, furniture and such if they are standing next to you while you do it.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ab877e4bed0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by TheShadowFerret** [comment]
~~Dino Dave doesn't want this to be fixed~~

**Comment by DalenTalas** [comment]
Similar issue when (I)nserting owned items into a container. This can be done without repercussion.
