### ISSUE TITLE
Using Hand Mirror increases stats for a turn

### ISSUE THREAD

**Issue by MrCumberdale** [CleverRaven/Cataclysm-DDA#62620]
### Describe the bug

Using a hand mirror, either to change your eye color or your eye color, has your stats increase briefly.
Change seems linked to either Stats through skills and Stats through kills, as in only the stats that have beed modified by those two mods seem to increase.
This can be chained endlessly as changing eye color or skin color doesn't take a turn, resulting in extreme stat boosts.

### Steps to reproduce

- Have Hand Mirror in the inventory
- Activate 'Hand Mirror' item
- Choose either from options 'Change the eye color' and 'Change skin color'
- Accept any colour that it gives as options

### Expected behavior

Stats that have been already increased via mutations or from the mods Stats through Kills and Stats through Skills gain additional points right after the eye colour has been changed; this change will persist for a small number of turns.

### Screenshots

![1A](https://user-images.githubusercontent.com/119970960/206325575-c2d23f10-dc88-43ad-a986-eef749fe3f63.png)
![1B](https://user-images.githubusercontent.com/119970960/206325587-aa964238-b3d7-4a82-9bcf-023251362266.png)
![2A](https://user-images.githubusercontent.com/119970960/206325637-b22d34be-bc1d-4336-bd2d-856d597ef5e6.png)
![Uploading 2B.png…]()

### Versions and configuration

- OS: Windows 10
- Build: Experimental 2022-12-07-0631
- Tiles: 8fabe5e
- Ingame language: English
- Mods loaded: 
![image](https://user-images.githubusercontent.com/119970960/206326566-cd50083c-e455-4f5b-a12e-63c27eb842a6.png)

### Additional context

Save file: https://mega.nz/file/akdxxbzZ#QkESYPXvdPPWYW84jYtlJc7mq1o2x7a0aFAOxApNUrU

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
