### ISSUE TITLE
Ask "group guard" or "group follow" give "Impaired Hearing" to mi companions.

### ISSUE THREAD

**Issue by KymasTuran** [CleverRaven/Cataclysm-DDA#62639]
### Describe the bug

Using the "group x" command give "Impaired Hearing" to my followers for a short time.

### Steps to reproduce

Give group command.

### Expected behavior

Not give "Impaired Hear"

### Versions and configuration

Windows 7
cdda-windows-tiles-x64-msvc-2022-12-08-0630

**Comment by NotSeawhite** [comment]
Aright. From what I have heard, the power of 'yelling' depends on your strength.
So the stronger you are, the louder you will be.
This usually happens if you're a mutant with a crackhead strength.

**Comment by KymasTuran** [comment]
> Aright. From what I have heard, the power of 'yelling' depends on your strength. So the stronger you are, the louder you will be. This usually happens if you're a mutant with a crackhead strength.

Thank you! That´s explain why after start a new game the "bug" was gone.
