### ISSUE TITLE
NPC spawning as valhallist shopkeeper

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62642]
### Describe the bug

NPC spawning as valhallist shopkeeper

### Steps to reproduce

Find NPC

### Expected behavior

Not.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ab877e4bed0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
The description is a bit too terse to be unambiguous.

Do you mean:
1. A random NPC encounter outside of that faction's base is both recruitable and lablelled as a Valhallist shopkeeper (possibly with an inventory); or
2. A Valhallist shopkeeper in the appropriate location is also a recruitable NPC; or
3. Something else?

**Comment by intergalacticdata** [comment]
A random, recruitable NPC in an inappropriate location.

**Comment by MNG-cataclysm** [comment]
> A random, recruitable NPC in an inappropriate location.

What location is this!

**Comment by intergalacticdata** [comment]
I think it was an apple orchard, but I don't recall for sure. there was a big pile of wares just laying in the field.

**Comment by intergalacticdata** [comment]
The character is long dead and the npc munged into something more reasonable. I'll keep an eye out for any more weirdness and save a copy before I start munging npc stats if I see it again.

**Comment by Drew4484** [comment]
Resolved by #62533
