### ISSUE TITLE
NPC with improper class spawning in Bandit Mission

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62641]
### Describe the bug

Mission: Kill Bandits, first in the old Guard chain

Outside of the cabin, one of the NPCs spawned as non-hostile and recruitable. She also seemed to offer faction missions. Her base class appears to be 'Female Scientist'

### Steps to reproduce

Unknown. Try the mission, perhaps.

### Expected behavior

I expect all NPCs to be bandits, or for non-bandits to be guarded, rather than standing outside alone.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ab877e4bed0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Night-Pryanik** [comment]
I suppose that's just random neutral NPC spawned next to your mission target location.
