### ISSUE TITLE
Riot Armor Molle Usage effects Torso

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#62647]
### Describe the bug

The riot armor suit description mentions that the Molle webbing is on the thighs, yet when in use the torso is re-labelled as Outer AND Strapped.

### Steps to reproduce

1. Spawn riot suit
2. Spawn any pals item
3. look at riot armor encumberance.

### Expected behavior

Pals attachments should only effect the body part they are strapped to. meaning one can wear a tac/load bearing vest and riot armor with gear strapped on the thighs without extra encumberance.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.819 (22H2)
- Game Version: 50d81a1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bean-b** [comment]
Is there a way to define in json that the molle is attached to the thighs? If not, I may just update the description for the molle to be on the torso, as i was able to find at least one example of riot armor with the molle attachments on the torso
