### ISSUE TITLE
Ember carrier ammo amount is inconsistent

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62659]
### Describe the bug

Ember carriers only take 50 tinder when unlit. When lit, they hold 100.

### Steps to reproduce

Craft Ember carrier. Observe. Light it. Observe.

### Expected behavior

Ammo amount should be consistent. Ammo should not disappear when extinguished.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: a6e65d3103f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by DalenTalas** [comment]
Confirmed, encountered this issue earlier.
