### ISSUE TITLE
Subdermal Carbon Filament CBM interferes with Electroshock Unit and Heat Drain CBMs

### ISSUE THREAD

**Issue by harmonickolobok** [CleverRaven/Cataclysm-DDA#62658]
### Describe the bug

Installed Subdermal Carbon Filament CBM prevents Electroshock Unit and Heat Drain CBMs from triggering just like if we have some clothes on our hands.
It says in description of pseudo item for "subdermal carbon filament" that it does not conducts electricity, but at the same time that it won't hinder special attacks that involve mutated or cybernetic anatomy.

### Steps to reproduce

1. Install "Electroshock Unit", "Heat Drain" and Power Storage CBMs
2. Activate both "Electroshock Unit" and "Heat Drain" CBMs
3. Try to successfully hit a warm and non shock proof creature with an unarmed attack(don't wear anything on hands).
4. Note the messages saying "You shock the <monster>" and "You drain the <monster>'s body heat"
5. Install Subdermal Carbon Filament CBM
6. Repeat step 3.(hitting a creature)
7. Note the absence of messages from step 4.

### Expected behavior

Expected Subdermal Carbon Filament to not block player character's special attacks from Electroshock Unit and Heat Drain

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental, cdda-windows-tiles-sounds-x64-msvc-2022-12-01-2057
- Graphic version: Tiles
- Ingame language: English
- Mods loaded: "Dark Days Ahead", "Disable NPC Needs", "No Fungal Growth", "Bionic Professions", "Blaze Industries", "Stats Through Kills"

**Comment by anoobindisguise** [comment]
SCF needs to be conductive, that's probably my bad. No clue about the heat drain though, it may not be checking the right flag. Tbh tho it's probably ok to just revert SCF to being invisible bionic armor as it used to be. It's not super necessary that it has an intgrated armor since it has a fairly uniform 100% coverage
