### ISSUE TITLE
Save suddenly got corrupted

### ISSUE THREAD

**Issue by Dancheek** [CleverRaven/Cataclysm-DDA#62654]
### Describe the bug

Saved the game as usual and exited, now loading save throwing out errors and all map is completly reseted except my character and its items

### Steps to reproduce

https://drive.google.com/file/d/1DMl72Ulp570ZcjNmMzqgZm-HoxdaQufn/view?usp=share_link

Download the world and try to load it

### Expected behavior

Loading save normally as always

### Versions and configuration

- OS: windows 10 build 1607
- Game version: 0.F-3
- Ingame language: Russian

**Comment by MNG-cataclysm** [comment]
How long have you had your current version of Cataclysm?

**Comment by Dancheek** [comment]
> How long have you had your current version of Cataclysm?

I have played like two month with no issues at all

**Comment by andrei8l** [comment]
```"last_updated":14586920,"body":{"@@@@@@@@@@@@@...```
Your save file appears to have been corrupted by a hardware or file system failure.

**Comment by Dancheek** [comment]
> `"last_updated":14586920,"body":{"@@@@@@@@@@@@@...` Your save file appears to have been corrupted by a hardware or file system failure.

I thought about it, but all other files seem fine, and i didnt experienced other signs of any system failures

**Comment by andrei8l** [comment]
Well there's 2.4MiB of binary garbage where text should be, so I'm 99% sure this is a file system failure. These things happen all the time but they are harmless and/or go unnoticed (unless you have ECC memory and a checksumming file system). They can be caused by cosmic rays or whatever and are not indicative of a general system failure.

**Comment by Dancheek** [comment]
so we decided its evil cosmic rays and im closing the issue? not the game bug i mean

**Comment by Dancheek** [comment]
I dont think going undeground for playing cdda is an option for me, but thanks for the advice and all help anyway, glad someone replied and helped
