### ISSUE TITLE
Background allows to bypass the traits restrictions

### ISSUE THREAD

**Issue by Telenkov-Dmitry** [CleverRaven/Cataclysm-DDA#62689]
### Describe the bug

I am playing on the experimental version (build number: 2022-12-10-0923). 

I am using single pool. I discovered that if you go past the traits restriction (12 and -12) via choosing backgrounds, you will be able to start a game. Not sure if it's expected behavior

### Steps to reproduce

1. Click create new character
2. Choose single pool
3. Go to traits and choose whichever up to the limits (good, bad or both doesn't matter)
4. Choose backgrounds that add traits
5. See the traits going past restrictions
6. Start the game

### Expected behavior

What: I expected an error message when trying to start a game, which says that the traits restrictions are bypassed. The game shouldn't start.
Why: In my opinion we should not be able to bypass the restrictions in any way. Maybe a **discussion** is required to clarify whether this should be expected or not.

### Screenshots

![image](https://user-images.githubusercontent.com/31540432/206897288-7fcc4784-7373-449d-9a35-83813f3f37a9.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: f9cc1b1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by intergalacticdata** [comment]
This is, in fact, happening. 

I don't see a problem with it. We have so many valid ways to make a character, there's no reason to call this way invalid.
