### ISSUE TITLE
Charge consumption error

### ISSUE THREAD

**Issue by Drew4484** [CleverRaven/Cataclysm-DDA#62706]
### Describe the bug

Items with charges can act as fuel even if the item is the incorrect type and loaded into a different pocket.

### Steps to reproduce

1. Spawn a combat exoskeleton and a power armor generator, wear both. 
2. Spawn a chunk of steel, load it into the generator frame storage pocket.
3. Unload the diesel storage tank.
4. Activate the armor.
5. Note that the armor is powered by chunk of steel and does not consume the chunk.

### Expected behavior

Multi-pocket tool items should be possible but need some way to designate which pocket is the fuel supply.

### Screenshots

![image](https://user-images.githubusercontent.com/57647637/206943461-6fe7b9e9-5276-4dcb-b821-e84dfb39cc95.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: f5eec2f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Aftershock [aftershock]
]

**Comment by mqrause** [comment]
Seems to be an issue beyond just consumption. I'll try to look into it soonish, if no one wants to grab it.
<details><summary>large image</summary>![grafik](https://user-images.githubusercontent.com/38702195/207018737-706f7d22-f75a-4788-9bbf-684400f89c8b.png)</details>
Charges listed in the description is sum of charges of all contained items, not just diesel.

![grafik](https://user-images.githubusercontent.com/38702195/207019019-e908db02-f953-49e2-a6c9-3fefeec6e608.png)
Same goes for the inventory screen.
