### ISSUE TITLE
CTD after factioncamp Cantine-smokers was finished

### ISSUE THREAD

**Issue by SamGondra** [CleverRaven/Cataclysm-DDA#62713]
### Describe the bug

When I try to move after finishing the smoker+Charcoal kiln construction I simply Crash to Desktop

### Steps to reproduce

Load the attached Save
[Jensen-reduced.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10208329/Jensen-reduced.zip)
Click away irrelevant debug msg
try to move
marvel at your desktop

### Expected behavior

No Crash?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2251 (22H2)
- Game Version: f643cd5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10208367/debug.log) 
There is no Crash log in my config folder, and there is no new Debug log entries for all the tries to load and fix the game myself
zipped Savefile is in the Steps to reproduce section

**Comment by RenechCDDA** [comment]
/confirmed on b758c62

Does not occur on 6957090. After moving one tile, you get the following(image) log messages

![image](https://user-images.githubusercontent.com/84619419/207158362-9b38bed7-cbed-401e-837c-51aff5115384.png)

**Comment by SamGondra** [comment]
Thanks for the help!
Should I change the title of the issue to match the actual problem?

Also the Item unloaded were Ammocans from a military Bunker, in particular 5.56 belts
