### ISSUE TITLE
Glass door fridges should work like regular fridges.

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#62710]
### Is your feature request related to a problem? Please describe.

The glass door fridges (`f_glass_fridge`) that appear in grocery stores, gas stations, what have you, are literally just fridges with an insulated glass door, yet the player can't make use of them like a regular fridge. They serve as obstacles and sources of scrap but not much else.

### Solution you would like.

The glass door fridge should be installable as an appliance like the common fridge is.

### Describe alternatives you have considered.

If there's a real reason why this isn't a thing, the description should be changed to point it out.

**Comment by oosyrag** [comment]
The appliance system is (relatively) new. Someone just needs to do it.

**Comment by motzmartin** [comment]
Very nice issue.

**Comment by Maleclypse** [comment]
Closed by #69266
