### ISSUE TITLE
'g' Pickup menu no longer shows item description

### ISSUE THREAD

**Issue by SabrinaMori** [CleverRaven/Cataclysm-DDA#62718]
### Is your feature request related to a problem? Please describe.

Previously it was easy to just scroll trough the items and see their descriptions, cause i'm not that experienced in the game i would read those a lot, but now i need to press E every time i want to see the item description, which is way slower than just being able to scroll trough.

### Solution you would like.

Adding back a window that would show item description without having to do any button presses

### Describe alternatives you have considered.

Making it an option to enable, but i really don't know why it's been removed in the first place, it was really useful, now Pickup menu is just an inferior version of AIM

**Comment by SabrinaMori** [comment]
Stable and Experimental comparison, yes the new menu is way cleaner and organized, but not having easily available descriptions is really painful.

![2022-12-13_03-51](https://user-images.githubusercontent.com/41236348/207199477-ab928499-4ce7-4cae-a9dd-2a38b8995d94.png)
 ![2022-12-13_03-51_1](https://user-images.githubusercontent.com/41236348/207199487-4d20e782-3b7d-4aab-8954-6c592d16dc83.png)

**Comment by oosyrag** [comment]
+1 miss the old way

**Comment by andrei8l** [comment]
The examine window/pane from the contents examiner (#51252) can be easily repurposed for this

**Comment by Zireael07** [comment]
This should be marked as an accessibility issue due to how useful it is to VI players

**Comment by Zireael07** [comment]
Please reopen - it's an accessibility issue
