### ISSUE TITLE
Make "5.56x45mm/.300BLK 10-round clip" useful. Allow speedloaders with non-empty magazines.

### ISSUE THREAD

**Issue by Zanthra** [CleverRaven/Cataclysm-DDA#62721]
### Describe the bug

If a magazine has any bullets loaded in it the game will exclude speedloaders from the ammunition avaialble to reload the magazine.

With common 30 round STANAG magazines, this means you can load only the first 10 rounds into the magazine using a speedloader.

Additionally, ammunition contained inside another magazine is also hidden from available ammunition. So any further 10 round clips are not available, and neither is the ammo inside them. To load the remaining 20 rounds into the magazine, you first have to unload the 10 round clips, then load the bullets into the magazine.

To fix this, the function item_pocket::can_reload_with in src/item_pocket.cpp should be changed to allow any speedloader that has ammo less than or equal to the remaining capacity in the magazine. This is the relevant check.

https://github.com/CleverRaven/Cataclysm-DDA/blob/2594fd915cfb8ce51066095790be037beb801b83/src/item_pocket.cpp#L1479-L1487

### Steps to reproduce

1. Have an empty STANAG magazine, and 3 "5.56x45mm/.300BLK 10-round clip"s with compatible ammo in them.
2. Reload the magazine, and observe the first reload gives the clips as valid reload options.
3. Attempt to load the next 10 bullets into the magazine, and observe that you have no valid ammo to reload the magazine with.

### Expected behavior

After loading the first 10 rounds into the magazine from the clip, I would expect to be able to load the next 10 rounds into the magazine from another clip.

### Versions and configuration

cdda-windows-tiles-sounds-x64-msvc-2022-12-02-0627

**Comment by GuardianDll** [comment]
That's a good info about how to fix it, but i think its better to make a separate flag - you definitely can put few rounds from 556 clip or shotgun speedloader, but not from revolver one
@catdach you may be interested due the #58580

**Comment by Zanthra** [comment]
I think that checking that the ammo in the speedloader is less than or equal to remaining ammo capacity in magazine is reasonable in that case, even for revolver or shotgun speedloaders.

Alternatively you can check the max ammo capacity of the speedloader against the remaining capacity in the magazine. These checks should not negatively affect current speedloaders (and could allow half revolver speedloaders).

The downside is that with the 5.56 speedloaders you cannot reload some ammo from the speedloader clip if the magazine does not have a multiple of 10 capacity remaining.

**Comment by Zanthra** [comment]
Above I proposed two alternative checks. Let me rewrite them here for clarity.

1. Allow use of the speedloader if the **remaining ammo** in the speedloader is less than or equal to the remaining ammo capacity in the magazine. If your speedloader has 4/10 rounds in it, and your magazine has 25/30 rounds in it, you can reload. If the magazine has 27/30 rounds in it you cannot.
2. Allow use of the speedloader if the **ammo capacity** of the speedloader is less than or equal to the remaining ammo capacity in the magazine. If your speedloader has 4/10 rounds in it, and your magazine has 18/30 rounds in it, you can reload. If the magazine has 21/30 rounds in it you cannot.

Some additional info.

https://www.youtube.com/watch?v=M3Hs4do69ms

Here is a video. At 0:40 he loads 8 rounds into the shotgun with a speedloader, then at 0:50 he loads another 4 rounds into the shotgun with another speedloader so he has 12 rounds in the tube.

Assuming that the speedloaders are all filled, the two alternative checks I proposed are equal, as the ammo in the speedloader and the ammo capacity of the speedloader are equal. This will be the common case.

The second check keeps Revolver speedloaders as they are currently. Revolvers already have explicit limits on the speedloaders they can use, so the capacity of the Revolver speedloader is equal to the capacity of the magazine. Because of that, the second proposal is equivalent to checking if the magazine is empty as it is now.

One could argue whether or not a partially loaded revolver speedloader is reasonable to refill some of the fired chambers, but then you have the issue of casing extraction. Extracting casings is easy if you just dump them out if they are all empty, but you have to be more selective if only some of the chambers are fired before you use the speedloader, which would slow you down.

**Comment by GuardianDll** [comment]
oh, yes, /confirmed, as this is a lot more precise answer how to fix it comparing to another issues about it
