### ISSUE TITLE
Professions that are supposed to start with spells do not

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#62729]
### Describe the bug

When using a mod with spells and creating a new character from a profession that's supposed to start with magic, no actual spells are granted even though the character select screen indicates they should be. Attempting to cast a spell provides the message "You don't know any spells to cast."

### Steps to reproduce

1) Make a world including a mod that provides spells
2) Choose a profession that begins with spells (such as Novice Necromancer in the Magiclysm mod)
3) Try to cast a spell, receive "Character has no spells to cast" message

### Expected behavior

A profession that starts with spells should provide those spells 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: e40157c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

**Comment by casswedson** [comment]
I can bring up the spell casting menu (meaning I can cast spells) right after spawning a novice necromancer in magiclysm
![image](https://user-images.githubusercontent.com/58050969/207668267-40a417de-aa7c-41d6-9f44-9b2224d155b7.png)
my version:

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: a72dc5d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

**Comment by Standing-Storm** [comment]
Huh.

I first noticed the problem in version b8eb345, so I downloaded the latest experimental yesterday and reproduced it. To rule out user error, just now I deleted yesterdays' experimental and downloaded today's, unzipped it to a clean folder, loaded it up, and:

![Test1](https://user-images.githubusercontent.com/120433252/207746977-49287cc4-bc46-45e9-b099-e609f7fcd649.png)
![Test2](https://user-images.githubusercontent.com/120433252/207746989-c6db186c-1692-405e-a7e8-837666480ffa.png)

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: a72dc5d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

**Comment by Standing-Storm** [comment]
User error, disregard
