### ISSUE TITLE
All my artifacts stopped working after #62700

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#62728]
### Describe the bug

My artifacts are no longer applying passive effects. If I spawn a new artifact, it works, but the ones I had already do not give my passive effects.
Oddly enough my RM13 armor seems to still be applying climate control and whatnot so not everything lost its effects.

### Steps to reproduce

1. Migrate an existing character with artifacts.
2. Notice they aren't giving passives anymore.

After some testing it looks like they're getting deleted upon being serialized/deserialized. After loading my game and then saving, all passive_effects in artifact relic data was deleted.

### Expected behavior

Fixing bugs for enchantments shouldn't introduce new bugs for enchantments.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1219 (21H2)
- Game Version: e40157c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment]
Which version have you updated from? You can check `debug.log` to see which versions are mentioned there.

**Comment by anoobindisguise** [comment]
> Which version have you updated from? You can check `debug.log` to see which versions are mentioned there.

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: f5eec2f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions]
]

**Comment by KymasTuran** [comment]
Look like this one is back https://github.com/CleverRaven/Cataclysm-DDA/issues/61308
