### ISSUE TITLE
Found a Bug with the Custom Plated Turrets

### ISSUE THREAD

**Issue by Cataclysmanic** [CleverRaven/Cataclysm-DDA#62737]
### Describe the bug

I was playing the most recent experimental. I had accidentally bumped into and damaged a turret while visiting the Artisans. It was a little agitating considering they block some of the walkways, and the buggers are so hard to see in the Ultica tileset. I had survived so long and it felt kinda like a let down to die like that. Shame me if you must, but I save scummed it and reverted to an old save. Alt+f4, reload the game.

Now, the problem after that, is that once I had loaded into the world, EVERY turret at the gunsmith's shop was hostile to me. I was swiftly gunned down. This was back in time, before I had hit them.

I activated debug mode, teleported away, moved far from the location, and came back with god mode enabled. The turrets all went back to ignoring me. The Artisans were not hostile to me at all throughout.

### Steps to reproduce

1. Attack a custom plated turret with melee
2. Die
3. Alt+F4 to quit the game
4. Reload a save of the same world. Your starting point must be nearby the same turrets, but before you hurt one of them
5. The turrets will be hostile

### Expected behavior

After loading into an older save the turrets shouldn't be hostile toward me, but they were.

### Versions and configuration

- OS: Windows 10
- Game Version: b758c62 (tiles)
- System Graphics: Tiles (Ultica)
- Ingame Language: English
- Mods Used: DisableNPCNeeds, DisableFungalGrowth

**Comment by Venera3** [comment]
Terminating the game when it's doing the on-death save will lead to weird behavior, and is not supported.
