### ISSUE TITLE
Allow players to play on the piano.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#62732]
### Is your feature request related to a problem? Please describe.

Recently, I came across a musician’s basement, which had a charming piano located in the recording booth. I walked my character up next to it and pressed €, confidently expecting to be able to indulge my inner apocalyptic pianist and play some toons on it. No such option came up, and I can only assume that one cannot interact with the piano furniture.

### Solution you would like.

We can play a wide array of other item based instruments, from saxophones to guitars. As such, I think that it’d be neat if one could also play upon the piano just for the fun of it.

### Describe alternatives you have considered.

Alternatively, perhaps a portable keyboard could be created which could be deployed and played, though I don’t know why the both of these things can’t exist alongside one another.

### Additional context

![Screenshot at 2022-12-14 08-36-10](https://user-images.githubusercontent.com/102766473/207534123-129d8593-6fc8-4ab0-8c5f-ab5e2f0cd557.png)

**Comment by GuardianDll** [comment]
It seems `examine_action` does not support the additional fields, that seems to be mandatory for `"use_action": { "type": "musical_instrument",`
