### ISSUE TITLE
Can't use tab key to change the page of settings and can't hold arrow keys or hjkl to move the scrool bar.

### ISSUE THREAD

**Issue by BreakingLead** [CleverRaven/Cataclysm-DDA#62734]
### Describe the bug

Same as the title.
I'm not a native English speaker so I'm sorry for some weird sentences.

### Steps to reproduce

1. pacman -S cataclysm-dda-tiles
2. > cataclysm-dda-tiles
3. Press "t" then "O".
4. Press tab or shift-tab.
5. Nothing happened.
6. Hold "j" for 10 seconds.
7. The cursor only moves 1 step.

### Expected behavior

I expected that I can flip the page to Interface or Graphics menu. But nothing happened.
And, I can hold arrow keys to move cursor fast.
There's no this problem in the Terminal version.

### Screenshots

![2022-12-14_17-55](https://user-images.githubusercontent.com/30070684/207564228-82ff7dfa-fcb1-4768-a000-d3e91c7fc62a.png)

### Versions and configuration

- OS: Archlinux
- Game Version: 0.F.3-2
- Graphics Version: Tiles
- Ingame Language: English
- Mods loaded: No

**Comment by BreakingLead** [comment]
Almost I can't play the game.

**Comment by BreakingLead** [comment]
It's not desktop environment or Xorg's problem. I tried to change to Wayland but doesn't work.(In all linux CDDA tiles version of my computer)

**Comment by ZeroInternalReflection** [comment]
I've been unable to replicate this in Arch Linux with either stable or experimental.

1. Are you using a non-English/non-QWERTY keyboard?  There are some issues with support of non-English keyboard setups that I believe are still outstanding (#22664).
2. Do you have this issue on all menus?  Or just the options menu?  The "Color Manager" screen uses similar keys for navigation.  Does it work properly?
![Screenshot from 2022-12-16 12-01-36](https://user-images.githubusercontent.com/89038572/208150521-8e9c610c-cecd-4a8a-8fba-9034eb264003.png)
3. Have you tried a more recent build? (https://cataclysmdda.org/experimental/)  0.F.3 is fairly old at this point, as is the AUR build (https://aur.archlinux.org/packages/cataclysm-dda-git)

**Comment by BreakingLead** [comment]
1. I currently use the generic 104 key keyboard layout(en_US).
2. Yeah, this issue is on all menus .and I found that I can't use all keys expect number keys and letter keys. ESC key is not usable.
3. I tried the latest build but it doesn't work. But I found there's no this issue on Windows version (using wine).

**Comment by ThePeiLin** [comment]
Deleting or commenting line 3205 of the file sdltiles.cpp might solve this issue, but I don't know if that would cause any other problems.
![cdda_bug](https://user-images.githubusercontent.com/47449134/209305907-fef2835d-256e-499f-bffb-436d73585ba0.png)
