### ISSUE TITLE
Leather Jacket and Trenchcoat encumbrance inconsistency

### ISSUE THREAD

**Issue by Rimplestilt** [CleverRaven/Cataclysm-DDA#62746]
### Describe the bug

The leather jacket and leather trenchcoat have values that seem inconsistent. A leather jacket has greater encumbrance when both empty and full compared to the counterpart.

Example, if i was to run through the woods or wherever IRL, i would choose a jacket over a trenchcoat and my movement would be hindered far more with the latter. 

### Steps to reproduce

Examine the stats of both items and see the encumbrance is less on the trenchcoat which is heavier and larger, and should cover areas the jacket would not irl.

### Expected behavior

I believe the encumbrance should either be increased for the trenchcoat, or reduced for the jacket - likely the former. This change would likely apply to other trenchcoats as well.

Ideally, a trenchcoat would cover and encumber the upper sections of legs, but i suppose there that might present layering issues.

### Versions and configuration

N/A (newest experimental on Android)

**Comment by oosyrag** [comment]
I'd recommend bring the trench coats up to their material jacket equivalent +1 encumbrance, and add Legs (thigh) coverage with a lesser amount of encumbrance.

**Comment by SabrinaMori** [comment]
I'm gonna try to take this one

**Comment by Rimplestilt** [comment]
Awesome, thanks! I was going to say, i wont be able to get to it real soon so

**Comment by Raiph-Benesz** [comment]
I shall offer myself to learn C++ and how to contribute to CataDDA's development to try and tackle this issue as my way to dip my leathery hairy feet into the cold waters of open source video game development.
