### ISSUE TITLE
[No hope mod] Vehicles spawn

### ISSUE THREAD

**Issue by DesLandysh** [CleverRaven/Cataclysm-DDA#62740]
### Is your feature request related to a problem? Please describe.

The vehicles spawn are not related to other items spawn set by this mod, this make mod unbalanced: norm to survive but difficult to move over map. (I usually decrease the loot spawn to 0.75 to get looting even more interesting) 
1) Too many ropes in fully damaged vehicles makes surviving easier than in vanilla.
2) Too many metal drops from bashing XX-damaged vehicles.
3) Needed vehicles parts are too far from eash other to combine them.
4) So it's easier to create a vehicles from scratch.

### Solution you would like.

So I suggest to tweak some parameters:
1) Spawn less vehicles at all to prevent ropes & metal industry
2) Spawn vehicles in **a little bit** better condition

**Comment by Night-Pryanik** [comment]
1. Ropes spawn in the mod is the same as in vanilla. You get ropes from destroying seatbelts. Getting ropes from cars isn't very hard both in vanilla and in the mod. So to eliminate rope industry, you need to remove ropes as a substitute for seatbelts.
2. The same for metal industry. Bashing cars to get metal isn't hard in both vanilla and in the mod.
3. and 4. Crafting vehicles from scratch is one of the intended goals of the mod.
