### ISSUE TITLE
Modification of the existing 'military supply drop' 

### ISSUE THREAD

**Issue by GFYguy** [CleverRaven/Cataclysm-DDA#62749]
### Is your feature request related to a problem? Please describe.

Currently, the military air drop that occurs occasionally in fields seems a bit off, in both the area around it and the loot it can contain. it seems silly that they would be dropped so far from a squad of soldiers that they would be completely untouched, and i dont think such a group needs 32 grappling hooks in a single crate.

### Solution you would like.

A change in its loot tables and the area around these drops,

- The loot should contain mostly MREs, Ammunition, fortifications like sandbags, and consumable/specialist equipment, such as antimaterial rifles, launchers, explosives, acetylene torches and the like. as well as occasional standard military equipment. 
- somewhere between 4-8 zombified/feral soldiers should be there, as well as a few military corpses, with possibly half built fortifications with one or two of the crates having already been opened by the squad of troops they were meant for.

**Comment by andrei8l** [comment]
Why would there be airdropped supplies for a soldier squad in the middle of friendly country? It's much more likely that these supply crates fell off the back of a transport plane during the initial portal storms. So 32 grappling hooks (or other base supplies) are perfectly fine.

**Comment by GFYguy** [comment]
> Why would there be airdropped supplies for a soldier squad in the middle of friendly country? It's much more likely that these supply crates fell off the back of a transport plane during the initial portal storms. So 32 grappling hooks (or other base supplies) are perfectly fine.

If they fell off during initial storms, they probably werent meant to land safely, and will most likely have borderline unusable contents buried a few feet in the dirt. It seems more likely when the blob was first making the riots and such break out, april 10th 2023 is when the military were canonically deployed, it would stand to reason that in the 20 days before game start, a few squads had supplies dropped to them when they got stranded or surrounded by feral and risen civilians.

**Comment by oosyrag** [comment]
Random airdropped supply crates would almost certainly be for civilians in the form of food, water, tents, blankets, flashlights/batteries, and informational flyers in my personal cataclysm disaster management plan. Basically what you would find in an evac shelter.

Considering this is home territory, the government would have more efficient, direct ways to keep troops supplied, and even if airdrops for military supplies were called for, they would be targeted and quickly used or otherwise secured.

Random airdrops are more like hey we're calling this a loss and not sending in any more boots or wheels on the ground, but we still want to try to help so whoever finds these, good luck! From that point of view a pistol with some ammo and perhaps some survival tools/kits wouldn't be too farfetched. With the assumption that zombies wouldn't have much use for a supply crate.

**Comment by GFYguy** [comment]
thats why i want it changed from random dropped crates to already partially secured ones. if the speed at which everything went to hell is to be believed, it stands to reason in the chaos, soldiers getting stranded and surrounded with desperate need for supplies would be dropped said supplies via air and subsequently fail to use/secure it either due to themselves becoming feral or the enemies around them finally closing in and overwhelming them.

**Comment by GuardianDll** [comment]
Accidentally found pretty comprehensive list of what can be supply dropped - its part of `FM 10-500-1: Airdrop Support Operations in a Theater of Operations`
![image](https://user-images.githubusercontent.com/67688115/209823900-83ad69c9-565b-420f-9148-296e935d2360.png)

**Comment by GFYguy** [comment]
can you link the document? even if making a JSON is over my head, i can most likely get all of these possible items converted to their ingame equivalents.

**Comment by GuardianDll** [comment]
its from <https://www.globalsecurity.org/military/library/policy/army/fm/index.html>, from `FM 10-500-1` `Airdrop Support Operations in a Theater of Operations` and below (each link is a separate file, and the page allow only 4 manual per day, if you don't use any trick to avoid it)
I'd be glad if you process it and convert info into exact game items and numbers, itll make process much easier for me to implement
