### ISSUE TITLE
Disable auto-note creation for favorited items when hauled

### ISSUE THREAD

**Issue by crumblingTHX** [CleverRaven/Cataclysm-DDA#62765]
### Is your feature request related to a problem? Please describe.

When hauling a favorited item and having the setting "Auto notes (dropped favorites)" enabled, everytime the player moves to a new tile it creates a note on the overmap for each time the character picks up and drops the item during hauling.

### Solution you would like.

Auto notes for favorited items should not be created during hauling.

### Describe alternatives you have considered.

This is a very minute issue that isn't pressing whatsoever, and isn't technically a bug as it is correctly creating notes everytime an item is dropped. Generally most players will pick up or carry favorited items on their person rather than dragging them around, but I happened to notice it when dragging an autoclave that I had marked as a favorite when I had no more space in my apparel.

This can just be avoided by simply picking up the item or by disabling the auto-note creation for dropped favorites setting.

### Additional context

Running game version 8fabe5e with default mods for this game version.
[An image of an overmap with tons of notes created via the Auto notes feature](https://imgur.com/a/v2b86rz)

**Comment by Raikiri** [comment]
I'd like to add that the proper solution would be to probably remove the note whenever an item is picked up. This would fix both the hauling spam problem and general spam when you drop and pick up your favoured backpack multiple times for combat.
