### ISSUE TITLE
Acidic monsters have tainted blood when bled.

### ISSUE THREAD

**Issue by Stoopedhooy** [CleverRaven/Cataclysm-DDA#62762]
### Is your feature request related to a problem? Please describe.

Acidic monsters are impossible to bleed using Butcher menu for their Sulfuric Acid, it can only be gathered using blood draw kit, despite descriptions implying they have acid in their veins.

### Solution you would like.

Sulfuric Acid should probably be possible to gather from acid zombies and monsters using bleed option in butcher menu.

### Describe alternatives you have considered.

Possibly, bleeding acidic zombies should require special tools and precautions or bear the risks of getting acid burns, unless the survival or healthcare is low, etc.

### Additional context

![image](https://user-images.githubusercontent.com/76749054/208250186-afc246f2-2293-4762-ba33-4673d8ebbbcc.png)
![image](https://user-images.githubusercontent.com/76749054/208250257-b4fd5fee-a9f7-4d97-a96d-915431f44566.png)
![image](https://user-images.githubusercontent.com/76749054/208250204-9ef6e01f-fcfd-46cc-9833-39f5a70474b1.png)
![image](https://user-images.githubusercontent.com/76749054/208250228-629180d9-6cda-4f55-81d9-4f9e20bf1b92.png)

**Comment by Night-Pryanik** [comment]
Which version are you using?

**Comment by Stoopedhooy** [comment]
Oh hello, sorry for late response, I am using this version.
Was acid blood added just recently? 😅
![image](https://user-images.githubusercontent.com/76749054/208283590-ae1b531e-5445-43ad-a23a-ff5efecf92ea.png)

**Comment by Stoopedhooy** [comment]
Apparently I am a bit late here, been suggested before in #62306 and #61516 with much interesting mechanics.
