### ISSUE TITLE
SOCIAL_LIE, SOCIAL_PERSUADE, and SOCIAL_INTIMIDATE enchantment values don't work correctly

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#62771]
### Describe the bug

When using an enchantment to modify social effects (ex: { "value": "SOCIAL_PERSUADE", "add": 25} ), the effects are inconsistent and do not obviously follow from the values provided in the enchantment. 

### Steps to reproduce

1) Create an enchantment that directly modifies social chances
2) Speak to NPC, check chances, cast spell, speak again
3) Chances to do not change by the expected value

### Expected behavior

{ "value": "SOCIAL_[FOO]", "add": 25 } should add +25% chance to persuade/intimidate/lie as appropriate.

### Screenshots

![Social enchantment](https://user-images.githubusercontent.com/120433252/208317759-02128b4c-2ab4-4c35-9a57-230a3f1e37fc.png)
![pre-suggestion](https://user-images.githubusercontent.com/120433252/208317813-12c17a5e-e597-4c48-a0af-f1eebdd1c5f2.png)
![Post-suggestion](https://user-images.githubusercontent.com/120433252/208317845-13f6dff7-a151-407c-bea7-cc557948af38.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: a72dc5d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

### Additional context

("Mind Over Matter" is my WIP psionics mod)

**Comment by GuardianDll** [comment]
/confirmed with the same json in 59756b0
surprisingly `"skills": [ { "value": "social", "add": 5 } ]` doesn't work also, when installing `bio_pitch_perfect` (which uses `"skills": [ { "value": "throw", "add": 5 } ]`) works perfectly
