### ISSUE TITLE
Grappling Hooks - Multiple Issues

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#62775]
### Describe the bug

Multiple issues with grappling hooks.
1) When a grappling hook is used to store an item, the item will be mulched if the grappling hook is deployed.
2) When the character climbs down a worn grappling hook, their torso encumbrance is not updated until they take the grappling hook down.
3) Grappling hooks cannot be retrieved from above or descended when previously deployed.

### Steps to reproduce

To reproduce:
Note your torso encumbrance.
Spawn a grappling hook.
Wear it.
Note your torso encumbrance.
Put an item in the grappling hook.
Note your torso encumbrance.
Climb down from a rooftop.
Note your torso encumbrance.
Wait a minute.
Note your torso encumbrance.
Take down the grappling hook.
Note your torso encumbrance.
Look for your item.
Climb back on the roof.
Look for your item.
Deploy grappling hook.
Climb back up.
Try to retrieve grappling hook.
Try to climb down grappling hook.

### Expected behavior

Items should not mulch. 
Encumbrance should update before the character begins climbing.
You should be able to pull a previously deployed grappling hook up from above and/or descend it.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12810-gdf83f9a8413 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by NotSeawhite** [comment]
You can even use the hook as a weapon forever since you can just deploy the hook to reset the damage..
