### ISSUE TITLE
Unrolled sleeping bag is the same size as rolled one

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#62776]
### Describe the bug

Both have volume of 1L.

### Steps to reproduce

1. craft it
2. roll / unroll
3. observe no change in volume

### Expected behavior

rolled is smaller than unrolled

### Screenshots

![image](https://user-images.githubusercontent.com/13402666/208327145-a706d83a-f7fc-4d60-882b-baef29a1183a.png)
a 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 59756b0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
I agree, the volume of the bag shouldn't magically change. The difference is one is flat, the other is rolled up into a rough cylinder

**Comment by oosyrag** [comment]
As far as volume goes, I'd say it's reasonable to have a rolled sleeping bag take up less space than an unrolled one, by virtue of compression of the stuffing. 1l is a tiny space for a sleeping bag to fit in either way, so I'd say the unrolled one should take up way more space. Unless the assumption is that even when unrolled the survivor can pack it into an ideal space of 1l anyway, which kind of defeats the purpose of having a separate rolled item in the first place.

The weight/mass should absolutely be the same, but that's not what op is talking about.

**Comment by GuardianDll** [comment]
It was changed in #55902, specifically to reduce the amount of keypress for player - no need to unroll it, you can use it in any moment, and wear without additional micromanagement

**Comment by Drew4484** [comment]
> It was changed in #55902, specifically to reduce the amount of keypress for player - no need to unroll it, you can use it in any moment, and wear without additional micromanagement

Closing.
