### ISSUE TITLE
AIM autoswapping madness

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#62784]
### Describe the bug

AIM pane direction selection buttons have different behaviour depending on their current state. For example, if I want to direct the current pane to the left (direction 4), I press 4. But if the current pane is already pointing to the left, then it will swap panels instead. This strange behaviour completely breaks muscle memory as it depends on the current state of AIM and requires actively reading where each pane is currently pointing to before choosing a direction. I realize it's a feature, but in practice I find it so annoying that I genuinely don't see how anybody can find it useful as it completely invalidates muscle memory when using AIM as it requires active reading of its current state before executing any action.

### Steps to reproduce

1. Open AIM
2. Press "4" on the current pane
3. Observe that if the pane has already direction "4" selected, it switches panes instead

### Expected behavior

Each selection direction button should have the same behaviour regardless of which direction the current pane is pointing to. If direction "4" is already selected, pressing it again should do nothing.

### Versions and configuration

Current experimental

### Additional context

Last time I asked about this issue was many years ago and back then I was told that AIM was undergoing a rewrite anyway and this behaviour was going to be changed. However, I don't think it went through. This strange feature interferes with my usage of AIM to the point where every time I open it, I spend 1 second to press the buttons to select the panes I want, and then spend the next 5 seconds trying to figure out where the panes actually ended up and how to re-do it again.

I don't even think there should be an option to maintain the current behaviour of how counterintuitive it is. However, I am genuinely curious what other people think about this so please upvote if you agree with me and downvote if you do rely on this feature.

**Comment by andrei8l** [comment]
Duplicate of #45900. No reason to re-post it.

**Comment by Raikiri** [comment]
That issue was even addressed into @satheon49 's pull request : https://github.com/CleverRaven/Cataclysm-DDA/pull/45903 that unfortunately did not get merged because they "were not doing it this time because what if somebody relies on it". I really hope that maybe now is a somehow better time or somebody else can re-evaluate it after years. Especially considering that the game now has received many more QoL features than it used to have, I hope the maintainers might have changed their opinion as I genuinely can't see how anybody would consciously prefer the current behaviour.

**Comment by andrei8l** [comment]
We're on the cusp of a new release so it definitely isn't the time to change UX. Either way, the correct approach is to open a PR with your intended changes since there's already an open/stale issue about it.

**Comment by Raikiri** [comment]
I definitely don't intend this change for the next stable version. My hope is to re-consider it and then maybe take action after 0.G. As for the changes, @satheon49 has already submitted a pull request, my hope is that the administration re-evaluates the problem in the light of [much more dramatic] recent changes.
