### ISSUE TITLE
Exceptions thrown when importing relatively young game from version Frank

### ISSUE THREAD

**Issue by crowder** [CleverRaven/Cataclysm-DDA#62780]
### Describe the bug

See attached .zip from my config/ directory for error output

### Steps to reproduce

Load my world into the release called cdda-windows-tiles-sounds-x64-2022-12-18-0616

I can provide the whole world save/ dir, if that is necessary.

Thanks in advance!

### Expected behavior

I expect no exceptions during this first load of my world/character (I could be wrong?)

### Versions and configuration

- OS: Windows
- cdda-windows-tiles-sounds-x64-2022-12-18-0616

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10255149/config.zip)

**Comment by PatrikLundell** [comment]
"Frank" is an incomplete description. There are several Frank version, so you need to provide the number for the description to be complete.

**Comment by crowder** [comment]
Sorry, more specifically 0.F.3
