### ISSUE TITLE
Nearby UPS no longer works for UPS-modded tools

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#62795]
### Describe the bug

As far as I remember, any UPS-compatible tools used to be able to access a UPS if it's sitting in range. This is no longer the case and a nearby UPS is no longer used to charge UPS-compatible tools unless the UPS is directly inside of the player's inventory.

### Steps to reproduce

1. Make a player with a UPS and a UPS-modded tool. For example, a firearm repair kit.
2. Put the UPS on the ground next to the character and try to use the "Repair" function on the firearm repair kit (UPS)
3. Observe that it says you need a UPS to do that

### Expected behavior

I expect tools to be able to access a UPS if it's not directly in the player's inventory but is nearby

### Versions and configuration

Current experimental

**Comment by flybye3o6** [comment]
![image](https://user-images.githubusercontent.com/115079701/208673283-e4b389d8-ae23-4772-a996-677802889d98.png)
can confirm it doesn't work, also doesn't work if the `firearm repair kit` is on the ground on the same tile as the `UPS`
`advanced UPS` doesn't seem to work even if it is in your inventory
also i seem to only be able to install the `UPS conversion mod` on the `firearm repair kit`

**Comment by andrei8l** [comment]
Easy fix, but this also lets you use UPS guns when the UPS is in pickup range which is definitely *NOT* intended behavior.
```diff
diff --git a/src/character.cpp b/src/character.cpp
index 70d6744afd..5c18cb39e5 100644
--- a/src/character.cpp
+++ b/src/character.cpp
@@ -8606,6 +8606,10 @@ units::energy Character::available_ups() const
         available_charges += units::from_kilojoule( i->ammo_remaining() );
     }
 
+    inventory temp;
+    temp.form_from_map( pos(), PICKUP_RANGE, this, false, true );
+    available_charges += units::from_kilojoule( temp.charges_of( itype_UPS ) );
+
     return available_charges;
 }
 
```

**Comment by Raikiri** [comment]
I mean sure, it's maybe a little more QoL than you'd expect, but what is its worst case consequence? That somebody will fire a laser rifle from a UPS sitting in a charging station? Sure, I guess it saves some micromanagement of swapping two UPS's, but does not seem like an unreasonable of convenience to have.

I guess an alternative would be to have an argument in that available_ups(bool use_remote) and set it to false for tasks such as firing guns, but I honestly don't see a reason why it's even necessary.

**Comment by Hirmuolio** [comment]
I'd say for consistency sake all ups items should work with same rules. So if UPS flashlight can be powered by ground UPS then UPS guns should too.
The quick fix above will most likely cause problems with crafting UPS use (it uses a bit different code and can use ground UPS without issues). Will need to comb through that mess to see if/what breaks.
