### ISSUE TITLE
Soft items can ignore container weight limits

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#62792]
### Describe the bug

When the pick up action is looking for a pocket to store certain kinds of items (soft items with a charge count, i.e. bandages), it will ignore the weight limits of parent containers when looking through its child containers, which lets you carry a heavier weight than a container is supposed to let you. Containers can begin to behave irrationally when this happens, with contents getting silently dumped onto the ground. Lastly, the feedback on weight limits is not very clear, only vaguely saying you can't add items or that there isn't room rather than explicitly saying it's too much weight.

### Steps to reproduce

1. Start a new game, drop all items and clothing with pockets.
2. Spawn a garbage bag, 100 glass bottles, 300 bandages, and 10 pebbles.
3. Wield the garbage bag and pick up the bottles. You should pick up 22, and the bag should be nearly at its weight limit.
4. Pick up the pile of bandages. You should collect them all. If you examine the garbage bag you can see it's carrying above its weight capacity.
5. Drop a single bandage, then pick it up again. With no indication in the message log, bottles will automatically be dropped on the ground to put the garbage bag back under its limit.
6. Drop everything but the garbage bag.
7. Get a new set of 22 bottles.
8. Attempt to pick up the pebble stack. It should behave properly, only adding as much as the bag can carry, refusing to add more. However, the messages from the game do not make this clear, saying "does not fit any pocket" even though the problem is weight, not volume.

### Expected behavior

For the bandages to behave the same way as the pebbles, acknowledging the weight limit, and for the game to tell me I couldn't get all the items because of that weight limit.

### Screenshots

![image](https://user-images.githubusercontent.com/6759778/208595016-165d2171-db90-4302-a14c-262a933da56a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2364 (22H2)
- Game Version: b7312f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/085319a1b7c482d6240dec4d33c492c93889d674/src/character_attire.cpp#L2344-L2347

I believe it's that part that's missing the weight check. The amount to fill the pocket with needs to be limited by parent weight capacity there.

If that's really the culprit that would also mean it works for all items with charges but only for nested containers with rigid pockets.

**Comment by anoobindisguise** [comment]
Can say I've seen the same thing happen. The silent dropping of items has made me so paranoid, it's really awful.

**Comment by mqrause** [comment]
I thought the silent part was fixed in #54268, is that still happening without any message?

**Comment by Kamayana** [comment]
> I thought the silent part was fixed in #54268, is that still happening without any message?

That sounds like exactly what's happening, yes. No message, you just suddenly have more room in the container, you step away, and see that stuff was dropped on the ground.
