### ISSUE TITLE
Rework disassembly times/results

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62797]
### Is your feature request related to a problem? Please describe.

A lot of items have really bizarre, nonsensical, and often inconsistent disassembly times.  Why would it take 2 hours to disassemble a spike on a stick? Why does it take 10 hours to disassemble a regular pair of boots, when disassembling steeltoed boots takes only a few minutes? Etc..

Speaking of boots, there are multiple types of footwear only yields soles when disassembled. What about the rest of the shoe/boot? Leather/cotton/etc. patches and chunks of other materials where applicable, strings from shoelaces, etc. should also be obtainable.

### Solution you would like.

I'd like for a re-examination and re-working of disassembly times and results to ensure both consistency and realism.

### Describe alternatives you have considered.

None that I've come up with.

**Comment by AmarinReyny** [comment]
> The reason for a lot of them taking hours upon hours is they are classed as reversible crafts rather than proper disassembly recipes. This means you get the same resources you'd put into crafting these items but it also takes just as long. Now, 99% of the time this is completely inapplicable because of the crafting time but this doesn't stop anyone from using the flag (I'm guilty of it myself, though I do have a PR correcting my mistake ready).
> 
> Yes, they absolutely should be reworked because most reversible recipes shouldn't be. Unfortunately, a lot of people omit this side of the code, it's fairly rare to see new or reworked disassembly recipes nowadays, so this is most likely going to take a longer while before any of these changes start appearing at large.

Ah... good to know, regardless. Thank you for informing me.

**Comment by Raikiri** [comment]
every time this problem is brought up, somebody reminds that you can cut clothing instead of disassembling it: it's a much faster process that probably is much closer to what you expect in terms of time and efficiency

**Comment by AmarinReyny** [comment]
> every time this problem is brought up, somebody reminds that you can cut clothing (with any tool that has cutting) instead of disassembling it: it's a much faster process that probably is much closer to what you expect in terms of time and efficiency

I don't want to cut things up, though, given how it wastes some of the other materials my survivor and the people of her growing post-apocalypse civilization would would otherwise receive from their scavenging and salvaging industry.
