### ISSUE TITLE
You can somehow attach appliances on a bike rack

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#62809]
### Describe the bug

I should elaborate; since the appliances are technically vehicles...

### Steps to reproduce

1. Find a pre-existing vehicle or debug spawn a vehicle (or construct a vehicle via construction menu)
2. Attach a bike rack on it
3. Drag the desired appliance you want to cluster to the next of bike rack
4. Attach the appliance on the rack
5. Observe the cluster you have just created

### Expected behavior

Not being able to attach an appliance on a bike rack.

### Screenshots

![20221222_015723](https://user-images.githubusercontent.com/52661206/208961721-8651d2b6-66e5-4cd7-9afb-ec90f3ee46bf.jpg)
Interacting a vehicle with a bike rack, with an ASRG on the next

![20221222_015733](https://user-images.githubusercontent.com/52661206/208961711-895b8d78-65fc-4ac4-9fc2-9e876e9c3c72.jpg)
The appliance got vehicle'ized and lost its functions, I have to manually remove the appliance and place it on the ground in order to use it.

![20221222_015756](https://user-images.githubusercontent.com/52661206/208961724-99fab41b-753a-4c0a-93e7-704afd9af58a.jpg)
Examining the ASRG

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G950N; Release: 9; Incremental: G950NKSU5DVG2; 
- Game Version: b7312f8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I was so excited that I could finally attach an ASRG on my car.. I am so disappointed.

**Comment by Raikiri** [comment]
why does it need to be forbidden?

**Comment by NotSeawhite** [comment]
> Maybe the solution should be instead to not break appliances when they are detached?

In that case, appliances would be pointless since you can just attach another vehicle on it.

**Comment by NotSeawhite** [comment]
Also, those are not really an intended feature but a bug.

**Comment by DalenTalas** [comment]
My vote is for "not a bug". Transporting large furniture (like freezers that do not fit into cargo carriers) becomes very difficult otherwise.

**Comment by NotSeawhite** [comment]
I can see you guys hate this issue, but this is quite game breaking.

Perhaps they could add a vehicle part that can rack appliances or buff the cargo spaces. Bike racks are supposed to rack vehicles.

**Comment by Zireael07** [comment]
@NotSeawhite This has already been fixed by the linked PR

**Comment by NotSeawhite** [comment]
I know, I just feel like people hate this
