### ISSUE TITLE
Useless cotton patch recipe creating cotton patches from cotton patches.

### ISSUE THREAD

**Issue by Stoopedhooy** [CleverRaven/Cataclysm-DDA#62805]
### Describe the bug

There is a recipe creating cotton patches from cotton patches in the span of 0 seconds.

### Steps to reproduce

1. Start a new character.
2. Open crafting menu.
3. Search for "cotton patch" recipe.
4. You find aforementioned recipe.

### Expected behavior

I expect there to not be such a recipe. Pretty harmless thing, but otherwise a little weird.

### Screenshots

![image](https://user-images.githubusercontent.com/76749054/208890162-03fcc0bf-275f-4906-9b3a-798ce7848dff.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.782 (20H2)
- Game Version: 4179a45 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by oosyrag** [comment]
"//": "This should be obsoleted once we're sure nobody has any rags left and they're removed from any recipes i missed.",

**Comment by Stoopedhooy** [comment]
Thanks for explanation. Should I close the issue then?

**Comment by oosyrag** [comment]
No, it's something that needs to be addressed, I'm just not sure how best to go about it.
