### ISSUE TITLE
[Magiclysm] Maybe there could be a "cleaning spell?"

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#62811]
### Is your feature request related to a problem? Please describe.

Frequently having a screen covered in blood, bug guts, and more, makes it difficult for me to be able to tell what I'm looking at, which makes it a lot harder to loot bodies, identify corpses to butcher, and so on. Relying on the "list all items around player" button and walking around with a mop might help somewhat, but they're very tedious, especially in places where a bunch of zombies, monsters, and/or other enemies have been killed/re-killed. Finally, there's the fact that Magiclysm, a mod that introduces high-fantasy magic use and other wizard-like things, seems to be missing one of the most classic tropes about wizards...

### Solution you would like.

I'd like an AOE spell that allows tiles to be cleaned over a large area.

### Describe alternatives you have considered.

Maybe a spell that summons animated mops that automatically clean adjacent tiles and seek out tiles that aren't clean? Though I kinda get the feeling that this would be harder to implement than a spell that just cleans a large area at once.

**Comment by sadenar** [comment]
Could be a fun thing for air/fire/water oriented magics.

**Comment by GuardianDll** [comment]
Not really possible with current mechanic - we have a "remove field" spell effect, but it can target only one specific field, not range

> Could be a fun thing for air/fire/water oriented magics.

Elaborate please?

**Comment by AmarinReyny** [comment]
> Not really possible with current mechanic - we have a "remove field" spell effect, but it can target only one specific field, not range
> 
> > Could be a fun thing for air/fire/water oriented magics.
> 
> Elaborate please?

Would it not be possible to adapt what mops do into a spell effect?

**Comment by GuardianDll** [comment]
No. Mop is a hardcoded action, and it need to be redone to work outside of `use_action`
The only we can get without additional code (because i don't know how to do code) is "you summon a magic mop, now you need to clean stuff manually"

**Comment by AmarinReyny** [comment]
> No. Mop is a hardcoded action, and it need to be redone to work outside of `use_action` The only we can get without additional code (because i don't know how to do code) is "you summon a magic mop, now you need to clean stuff manually"

Oh, damn... so, even animated mops that automatically mop adjacent tiles wouldn't work, either?

**Comment by GuardianDll** [comment]
No, as monster's can't do actions, their attacks either hardcoded, specially defined, or... spells

But again, a way to target all fields for spell's remove_field action seems for me the easiest way - still require a code, but allow us to "cast a spell and make a room clean" and not wait till magic-powered roomba clean stuff around

**Comment by AmarinReyny** [comment]
> No, as monster's can't do actions, their attacks either hardcoded, specially defined, or... spells
> 
> But again, a way to target all fields for spell's remove_field action seems for me the easiest way - still require a code, but allow us to "cast a spell and make a room clean" and not wait till magic-powered roomba clean stuff around

Is there a way to apply the remove_field effect multiple times for each relevant field, or no?

**Comment by GuardianDll** [comment]
there is, but do you really want to make 3k string addition just to handle cleaning all possible fields?

**Comment by AmarinReyny** [comment]
> there is, but do you really want to make 3k string addition just to handle cleaning all possible fields?

Fair point... Even if I have the free time, I doubt I'd have the attention span to do it. I suppose I _could_ just add to it piece by piece over time (especially if those pieces are added as they're needed in-game), but I somehow doubt the end product would be extremely laggy.

**Comment by cake-pie** [comment]
I have some ideas for this I'd like to try, but currently already have too many balls in the air. Hope to come back to this a bit later -- commenting to prevent bot from closing.
