### ISSUE TITLE
Fabrication Workshop anvil and workbench upgrade requires "1 anvil" twice

### ISSUE THREAD

**Issue by DorianWang** [CleverRaven/Cataclysm-DDA#62825]
### Describe the bug

The camp upgrade "anvil and workbench" for the Fabrication Workshop version 2 requires two anvils, which are listed as two "1 anvil" entries.

### Steps to reproduce

Make a Modular camp
Select a Fabrication Workshop v2 as an expansion
Upgrade the forge twice

### Expected behavior

The anvil requirement should be reduced to one "1 anvil" and consume only 1 anvil. If the two anvil requirement is expected behaviour, it should be listed as "2 anvils" instead.

### Screenshots

![One Anvil](https://user-images.githubusercontent.com/6524694/209059981-3a34f1bb-ae54-4d1f-bd7f-77e2c735d04e.png)
![Two Anvils](https://user-images.githubusercontent.com/6524694/209059990-b4e5917d-78b9-443e-a1f9-597ac4ab7fcc.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2364 (22H2)
- Game Version: 59756b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

If the anvil requirement in recipe_modular_workshop_common.json is removed, only 1 anvil is listed in the requirements and the recipe appears to function correctly (consuming 1 anvil). I am unsure if this would be the correct place to fix this.

**Comment by PatrikLundell** [comment]
There should only be a single anvil involved, and only one was required when the recipe was tested.

Looking at the recipe as it is in Master at the time of this writing I don't see anything odd, and the file hasn't been changed for 10 months.
I don't know what the "requirement" in the recipe refers to. "anvil" is mentioned only as a "blueprint_resources" and a "components" element, where the former provides the anvil capability for further crafting, and the latter is the anvil that's "consumed" in to process. Thus, I don't know what's going on here.

**Comment by DorianWang** [comment]
This seems to affect the recipe in general, screenshot from latest experimental with only default mods (af92bd2):
![Fabv1](https://user-images.githubusercontent.com/6524694/209157598-02791f2f-ec14-44c9-a2d9-c5279b1af398.png)

Maybe something changed with the way camp upgrades calculate their requirements?
