### ISSUE TITLE
Church Community epilogue and <the_cataclysm>

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#62822]
### Describe the bug

The epilogue of the New England Church Community does not convert the <the_cataclysm> object correctly.

### Steps to reproduce

1. Meet the New England Church Community
2. Die
3. See <the_cataclysm>

### Expected behavior

It appropriately converts the object.

### Screenshots

![the_cataclysm](https://user-images.githubusercontent.com/32048635/209044891-2d9aa125-59f5-4f4a-8556-4b19326f7243.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: c58154a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Maleclypse** [comment]
Closed by #66668
