### ISSUE TITLE
Plank recipes "recipe makes X" are not displayed

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#62823]
### Describe the bug

Plank recipes (long plank -> plank -> short plank) suposedly make multiple and it is in the JSON, but player cannot see it as "Recipe makes" is missing in the recipe.

### Steps to reproduce

1. look in crafting menu at recipes for plank and short plank

### Expected behavior

I can always see how many a recipe makes.

### Screenshots

![image](https://user-images.githubusercontent.com/13402666/209046820-7aafc781-4bf0-4cfa-a22b-6756d9e09f83.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: ab60b1b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

From discord:
> I was going to say it might only exist for food but that's wrong, I don't see a reason why it doesn't display how many of the thing you get.  Presumably the "result_mult" means that it does only make 1 it just multiplies that and gives it to the player.  So it's possible that using result_mult circumvents whatever mechanism tells the player how many you get

**Comment by RenechCDDA** [comment]
Related: #61753
