### ISSUE TITLE
Valhallist camp stray palisade wall

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#62820]
### Describe the bug

There is a single palisade wall amongst the log walls surrounding the valhallist camp

### Steps to reproduce

1. Go to a valhallist camp
2. Notice palisade wall between the gate pulleys

### Expected behavior

Either the entire perimeter is palisade wall or log wall.

### Screenshots

![pali](https://user-images.githubusercontent.com/32048635/209042057-7a13abda-29b9-4650-b076-fc818263ae8d.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: c58154a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
I've never seen that faction, but it looks to me like this is a palisade gate that would open/close when the pulley are used.

**Comment by MNG-cataclysm** [comment]
> I've never seen that faction, but it looks to me like this is a palisade gate that would open/close when the pulley are used.

This is true, I tested it a few times without the palisade and the gate wouldn't open.
