### ISSUE TITLE
Support compilation for uClibc without locale

### ISSUE THREAD

**Issue by Shatur** [CleverRaven/Cataclysm-DDA#62847]
### Is your feature request related to a problem? Please describe.

I trying to compile this game for my retro handheld Anbernic RG280V. But It contains uClibc with locale disabled (it is in experimental stage with this libc and the maintainers disabled it for these devices). So it have `locale.h` header, but functions `setlocale()` / `localeconv()`, `newlocale()` / `freelocale()` / `uselocale()` / `duplocale()` are unavailable:

```
In file included from /mnt/Files/Code/gcw0-toolchain/Cataclysm-DDA/src/third-party/flatbuffers/util.cpp:49:
/mnt/Files/Code/gcw0-toolchain/Cataclysm-DDA/src/third-party/flatbuffers/util.h:223:15: error: ‘locale_t’ does not name a type; did you mean ‘socklen_t’?
  223 |       typedef locale_t locale_type;  // POSIX.1-2008 locale_t type
      |               ^~~~~~~~
      |               socklen_t
/mnt/Files/Code/gcw0-toolchain/Cataclysm-DDA/src/third-party/flatbuffers/util.h:227:5: error: ‘locale_type’ does not name a type
  227 |     locale_type locale_;
      |     ^~~~~~~~~~~
```

### Solution you would like.

It would be great to fix flatbuffer library compilation without locale support. I assume it could be possible if `LOCALIZE` compile option is disabled?

### Describe alternatives you have considered.

Maybe use a more mature serialization library instead of the vendored `flatbuffers`?

**Comment by akrieger** [comment]
We already have LOCALIZE disabled for flatbuffers. Not sure what you mean by 'more mature' though. It's at least 9 years old now.

I can try looking into what's needed for this but maybe it'd be better filing an issue against flatbuffers upstream because this issue with uClibc is not cataclysm specific.

**Comment by ZhilkinSerg** [comment]
Did you try to compile and run older version w/o flatbuffer? Because I don't think it is necessary to fix anything while CDDA won't even run on a device with 512MB RAM.

**Comment by Shatur** [comment]
> Did you try to compile and run older version w/o flatbuffer?

Didn't know. I could try!

> Because I don't think it is necessary to fix anything while CDDA won't even run on a device with 512MB RAM.

This device can emulate games up to and including PS1. I can also run DevilutionX, FreeHeroes2 and OpenLara natively. Do you think that CDDA consumes more resources?

**Comment by BrettDong** [comment]
I'm sure 512 MB of RAM is not enough for CDDA unless you make some modifications.

**Comment by Shatur** [comment]
Sad to hear :(

**Comment by ZhilkinSerg** [comment]
> PS1

had 2MB RAM. Even compressed raw CDDA data is 2.5 times more.

**Comment by Shatur** [comment]
But emulation takes more. Also I can run 3D games like I mentioned above no problems.

**Comment by Zireael07** [comment]
@Shatur RAM usage is not just a function of whether a game has 2D or 3D graphics. Early console games were subject to their hardware restrictions, so even emulated they won't get past a certain size.

**Comment by Shatur** [comment]
@Zireael07 Sure, the last sentence was for native games such as Quake 3 Arena or OpenLara. Didn't know that CDDA consumes more.
