### ISSUE TITLE
basecamp mission of building railways

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#62844]
### Is your feature request related to a problem? Please describe.

that would not be immediately achievable for players, however after having a great enough number of NPCs and supplies that is a possible work that could bring some bennefits, and I am also suggesting it because electrification of buildings has been achieved on experimental. It can reduce incidents on common paths, make it possible on practice, to use vehicles of unlimited length (that is a lot of cargo and passenger space) and achieve the separation of energy source and the vehicle, so that this expansive part could stay secure.

It could also possibly be used to reduce time for missions, such as those of clearing forests and getting logs, then it would be viable to do those at much further lengths. For it the vehicle could be marked as property of the basecamp and used by the NPCs as needed

### Solution you would like.

enabling construction of railway as a basecamp mission and allowing it to be used for missions on the basecamp, for reducing time of missions and cargo transportation costs, besides the regular uses of vehicles. Using the logic of electrification of buildings for achieving it. The mission would add some fixed amount of cost of each required item for each tile of the construction and the number of NPCs involved would reduce the construction time for each tile.

The construction would start with the control station, that maybe could require some book and hability on computation, electricity and mechanics, then the railway itself

### Describe alternatives you have considered.

maybe the book could be too much and just the habilities themselves suffice

**Comment by Drew4484** [comment]
Building a railway, even a small one, is anyone incredible amount of work and would consume a similarly incredible amount of resources. Even with automated equipment, you've still got the cost of the rail bed, the ties, and of course the rails themselves, which are nearly impossible to manufacture to tolerance outside of heavy industry.

**Comment by PatrikLundell** [comment]
Apart from the construction itself, there is also the issue of the absence of a lot of logic that would be required to actually do anything useful with it:
- The system doesn't really support power transfer outside of the reality bubble. You can sort of make it work, but it cuts out irregularly (I've constructed an appliance/outdoor extension cable chain from a river to my cave base over some 6 or so world tiles, and the power cuts out irregularly so I have to go to sufficiently close to the water turbine to get it going again).
- The away mission logic doesn't support the usage of vehicles of any kind, nor does the game support companion vehicle driving.

**Comment by jfferson** [comment]
> Building a railway, even a small one, is anyone incredible amount of work and would consume a similarly incredible amount of resources. Even with automated equipment, you've still got the cost of the rail bed, the ties, and of course the rails themselves, which are nearly impossible to manufacture to tolerance outside of heavy industry.

okay, so it is far away; at least it brings good use for industry anyway. Anyway for both comments I understand either things have a long line of dependencies in development

**Comment by jfferson** [comment]
> Apart from the construction itself, there is also the issue of the absence of a lot of logic that would be required to actually do anything useful with it:
> 
> * The system doesn't really support power transfer outside of the reality bubble. You can sort of make it work, but it cuts out irregularly (I've constructed an appliance/outdoor extension cable chain from a river to my cave base over some 6 or so world tiles, and the power cuts out irregularly so I have to go to sufficiently close to the water turbine to get it going again).
> * The away mission logic doesn't support the usage of vehicles of any kind, nor does the game support companion vehicle driving.

either way ownership of vehicles on basecamp is something that would be interesting to be provided.
Somethings that would allow it are this workflow of controllers or functions: objective (mission) -> context -> agent -> actions -> related unities
and restricting it to bycicles, as that would make realistic to ignore every obstacle on map, with exception to rivers

**Comment by Drew4484** [comment]
> > Apart from the construction itself, there is also the issue of the absence of a lot of logic that would be required to actually do anything useful with it:
> > 
> > * The system doesn't really support power transfer outside of the reality bubble. You can sort of make it work, but it cuts out irregularly (I've constructed an appliance/outdoor extension cable chain from a river to my cave base over some 6 or so world tiles, and the power cuts out irregularly so I have to go to sufficiently close to the water turbine to get it going again).
> > * The away mission logic doesn't support the usage of vehicles of any kind, nor does the game support companion vehicle driving.
> 
> either way ownership of vehicles on basecamp is something that would be interesting to be provided. Somethings that would allow it are this workflow of controllers or functions: objective (mission) -> context (vehicle) -> agents -> actions -> related unities and restricting it to bycicles, as that would make realistic to ignore every obstacle on map, with exception to rivers

Though this is getting very far off topic from the original subject, you could add a variant of a basecamp task that has extended range/less time required but requires a folding bike in stock.
