### ISSUE TITLE
Cutting cloth to sheets before patches (Makeshift bandage balance)

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#62861]
### Is your feature request related to a problem? Please describe.

Since the change to make makeshift bandages from cotton sheets/patchwork cotton sheets (very reasonable change), there has occasionally been confusion voiced about how to quickly access materials for a makeshift bandages. The previous way of cutting up clothing for bandages (also reasonable) results in patches, which no longer can be quickly turned into makeshift bandages (the issue). I imagine this concern will be echoed well into the future if it remains as is for stable release.

Currently, the cut action calls for `// Decompose the item into irreducible parts`, with the result being a cotton item is shredded into small cotton patches unsuitable for bandaging wounds (until you sew them up again into a patchwork cotton sheet). This is unintuitive for a player who has the materials and tools to cut up clothing quickly, but is unable to do so to make the desired bandages in an emergency situation. The controls/implementation of the game gets in the way of the desired action. 

Given that it takes less time and effort to cut an item into larger pieces as opposed to small pieces, and that the intent or goal of the player may be to acquire those larger pieces those larger pieces in the first place, it's frustrating that there is no option to do so.

### Solution you would like.

Cut items such as clothing are first cut into (patchwork) cotton sheets, and then further cut into patches. 

Instead of the cut action defaulting to result in the smallest possible part based on the mass/volume/material of the original item, it would result in the largest reasonable piece instead (minimum 2 parts, otherwise resulting in the next smaller unit of material instead).

Optional ideas:
Add choice to recursively cut into irreducible parts (effectively preserving current behavior of the cut up action).
Failure chance on individual pieces, resulting in the smaller item instead.

### Describe alternatives you have considered.

The alternative would be to manually add more deconstruction recipes to result in cotton(and other material) sheets from. I intend to do this for common items such as tshirts and pants as a temporary fix that could be applied for stable, as the above would be a more significant c++ change that may not be suitable to develop at this point during feature freeze.

However, I don't think this is an ideal solution for the following reasons:
1. It's going to be a lot of work adding/changing deconstruction recipes to the multitudes of clothing items in game, prone to mistakes, discrepancies, and simply missing items. Could be a maintenance burden.
2. My understanding of "deconstruction" is careful deconstruction of an item to salvage it's constituent parts used for crafting. For example, taking a shirt apart at the seams to recover the thread and each piece of cloth fully. This also makes sense in the context of default/undefined deconstruction being the exact opposite of the crafting recipe. (As an aside, the default/undefined deconstructing could probably be adjusted tp taking less time than the construction recipe, maybe half as much? With exceptions defined as deconstruction recipes for those things that take significantly less time to take apart than to put together, or possibly more time than it takes to put together.)
3. In the context of bandage making, we would be unable to have two deconstruct recipes to differentiate between deconstructing quickly for the emergency bleeding situation, or for deconstructing slowly and carefully to salvage more parts. I think the desired solution above would be best suited to represent this, allowing the cut action to be quick, and deconstruct to be careful. Cutting a shirt could result in a couple patchwork cotton sheets, while deconstructing would result in cotton sheets and thread.

### Additional context

For consistency's sake, the size of a shirt should allow for two or three 12 inch by 24 inch pieces of cloth to be cut from it. It doesn't make sense that you can only get five pieces of 6 square inch patches from a shirt as in the current deconstruction recipe. This would also be in line with requiring 3 cotton sheets to craft a shirt to begin with.

**Comment by oosyrag** [comment]
@Karol1223 You mentioned in discord that cutting giving cotton sheets would be a step backwards, wanted to ask for your thoughts after I elaborated some more.

**Comment by flybye3o6** [comment]
could also make more makeshift bandage recipes, like making a batch of them directly from a sheet you pulled off the window or from a bed
same with thread, it seems dumb to get thread from a sheet by first cutting it up a few times then pulling the threads apart

**Comment by Karol1223** [comment]
I was summoned so there I am to clear some things up

> Decompose the item into irreducible parts

This is the key here. That's how cutting up works and, without c++ changes, that is how it _should_ work, in my opinion, as that is the most foolproof solution. Having said that, I fully agree with your idea of changes **as long as it does incorporate c++**. I did say that changing the cotton cut result to cotton sheets is a step backwards as that is quite literally undoing the PR that initially changed rags into (smaller) cotton patches. The **ideal** solution here would be to have the possibility of cutting code to determine whether the item is big enough to provide sheets. Volume, however, is a pretty bad indicator of this. Volume takes into account the thickness of the item (which reducing with simple cutting is doable but pretty bad from experience) as well as free space between parts of the item (although this should theoretically not apply to clothing but I am not sure whether it does or not, volume of items at the moment is a mess in itself).

> My understanding of "deconstruction" is careful deconstruction of an item to salvage it's constituent parts used for crafting

Not the case. Disassembly of items can be anything. It may be carefully picking out thread from a t-shirt, it may be cutting a jerrycan with a hacksaw, it may be throwing a glass bottle on the ground really hard. Limiting your definition of disassembly to just careful processes is going to hinder you in the long term, although where applicable (such as fabrics) I'd say that making cutting the fast and less efficient process as opposed to disassembly's plucking out thread from the t-shirt is appropriate.

**Comment by Zireael07** [comment]
> This is the key here. That's how cutting up works and, without c++ changes, that is how it should work, in my opinion, as that is the most foolproof solution. 

However players are often negatively surprised by the time it takes. Also disassembly sometimes is made this, too (e.g. boots and t-shirts being taken apart into leather pieces and thread)

**Comment by oosyrag** [comment]
> could also make more makeshift bandage recipes, like making a batch of them directly from a sheet you pulled off the window or from a bed same with thread, it seems dumb to get thread from a sheet by first cutting it up a few times then pulling the threads apart

I'm pretty firmly against crafting recipe bloat. Multiple recipes for the same item irk me, even when they do make sense or are necessary. Alternative component choices are preferable, but come with their own issues.

> Having said that, I fully agree with your idea of changes **as long as it does incorporate c++**. I did say that changing the cotton cut result to cotton sheets is a step backwards as that is quite literally undoing the PR that initially changed rags into (smaller) cotton patches. The **ideal** solution here would be to have the possibility of cutting code to determine whether the item is big enough to provide sheets.

I have some ideas to go about implementing this with minimal changes to the current code. It might be relatively simple to go backwards from the current salvage results as they are to result in sheets. For example, given 8 patches is worth 1 sheet of material, if the salvage action would currently result in 20 patches, it would just be one more step to divide by 8 to result in 2 patchwork sheets and 4 patches. Will have to put it together and test to see how well it works in practice and nail down any exceptions or edge cases, probably after stable stable drops. In the meantime I've got the other PR to utilize disassembly for more patchwork cotton sheet sources for now.

**Comment by Zourin2** [comment]
The underlying problem isn't that clothes shred to patches, but that it's now substantially harder to use spare clothing (or not spare) to make makeshift bandages without a library of intermediate steps.

**Comment by Brambor** [comment]
Just a thought: Cut up could bring up a menu to choose the desired result. For example, if you want to cut pants into cotton sheets or cotton patches.

It is just a QoL menu, as the player would be able to do that by cutting up repeatedly. Given that your idea is implemented.

My proposal gets useful when you "cut up everything" and the implementation gets interesting.

**Comment by oosyrag** [comment]
> Just a thought: Cut up could bring up a menu to choose the desired result. For example, if you want to cut pants into cotton sheets or cotton patches.
> 
> It is just a QoL menu, as the player would be able to do that by cutting up repeatedly. Given that your idea is implemented.
> 
> My proposal gets useful when you "cut up everything" and the implementation gets interesting.

> Optional ideas:
> Add choice to recursively cut into irreducible parts (effectively preserving current behavior of the cut up action).

**Comment by Brambor** [comment]
> Optional ideas:
> Add choice to recursively cut into irreducible parts (effectively preserving current behavior of the cut up action).

Sorry, I didn't get that player would provide a stopping function to the recursion. I read it as an implementation view.

**Comment by oosyrag** [comment]
I'm imagining it as similar to the current butcher menu, where there's an option to recursively disassemble as the last choice.
