### ISSUE TITLE
Heating and air conditioning should not be 'free'

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62866]
### Describe the bug

Apparently heating and air conditioning are tied to vehicle controls. Simply sitting on a bike or the driver's seat of a wagon, etc is enough to make a character more comfortable.

### Steps to reproduce

Walk on a bike's control tile.

### Expected behavior

Climate control should require an actual running engine, orsome sort of resource consumption.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12833-g4179a45695f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
>Simply sitting on a bike or the driver's seat of a wagon, etc is enough to make a character more comfortable.

Incorrect.

Vehicle "climate control" happens in only 2 circumstances:
1) You are within an *enclosed* vehicle, and there is windspeed. The vehicle shelters you from the wind, just like being inside or underground.
https://github.com/CleverRaven/Cataclysm-DDA/blob/0458778cf69ac0a0198da64572cfe425712c2560/src/character_body.cpp#L426-L428
2) You are within an *enclosed* vehicle, **and the vehicle's engine is on.**
https://github.com/CleverRaven/Cataclysm-DDA/blob/0458778cf69ac0a0198da64572cfe425712c2560/src/character_body.cpp#L437
https://github.com/CleverRaven/Cataclysm-DDA/blob/0458778cf69ac0a0198da64572cfe425712c2560/src/character.cpp#L3522-L3537

**Comment by intergalacticdata** [comment]
You are correct. I wasn't paying attention to wind speed nearly as much as toe temp.
