### ISSUE TITLE
Combine Sheet and Cotton Sheet into a single item

### ISSUE THREAD

**Issue by Rydelfox** [CleverRaven/Cataclysm-DDA#62860]
### Is your feature request related to a problem? Please describe.

The sheets you can get from smashing windows are a sheet, made of cotton, but are a separate item from Cotton Sheets. This means that despite being a sheet of cotton, they can't be used in recipes that require a Cotton Sheet.  In cases that allow a Patchwork Cotton Sheet, you can cut the sheet up, then sew it back together to make it more usable.  Probably the most obvious example of this is the Makeshift Bandage recipe, which takes Cotton Sheets and Patchwork Cotton Sheets, but not Sheets.

### Solution you would like.

Turn Cotton Sheet and Sheet into a single Cotton Sheet item

### Describe alternatives you have considered.

Have all sources of Sheets drop or craft Cotton Sheets instead
Have all sources of Cotton Sheets drop or craft Sheets instead
Have all recipes that accept Cotton Sheets accept Sheets as well, and vice versa

**Comment by Rydelfox** [comment]
Nevermind - realized Sheet and Cotton Sheet are different sizes

**Comment by oosyrag** [comment]
Leaving a note here that sheet disassembles into patchwork cotton sheets.
