### ISSUE TITLE
Rubber dog rainsuit: various inconsistencies

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#62863]
### Describe the bug

The item "rubber dog rainsuit" (`data/json/items/armor/pets_dog_armor.json:rubber_harness_dog`):

- Is named as if it is made of rubber;
- Has a description stating it is "thin plastic";
- Is crafted from plastic sheets, duct tape, cotton patches, and one of various fasteners;
- Disassembles into up to 8 plastic sheets and 8 cotton sheets (the latter being odd because that's way more cotton than goes into it);
- Is repaired with plastic, neoprene, and rubber, neither of the last two being components, though they are plausible repair materials,
- Inherits Bash 5 from `kevlar_harness`, which seems implausible.

I tried to put this on my dog and she tore out my throat. I bled out and she feasted on my carcass.

### Steps to reproduce

1. Spawn in a rubber dog rainsuit.
2. Behold the horror.

### Expected behavior

Item's properties are more tightly defined and inconsistencies cleared up across name, description, crafting ingredients, disassembly and butchering products, and melee damage.

### Screenshots

![image](https://user-images.githubusercontent.com/118625/209451308-592f0dc7-287b-489e-8888-891bd2bcd300.png)
![image](https://user-images.githubusercontent.com/118625/209451315-006ed610-7391-4a87-b1dd-cdd3d25f4d47.png)
![image](https://user-images.githubusercontent.com/118625/209451318-8d1ea030-d105-4aa2-b2b3-84bd386bcc6a.png)

### Versions and configuration

- Windows 11
- Game version 2022-12-29-b7312f8
- Tiles
- English
- Mods: all of them

**Comment by flybye3o6** [comment]
defence stats are gained from materials used, thickness and percentage, with a thickness of 0.1 and those materials it isnt providing protection, that Bash 5 is melee stat for if you weld it, alot of items have this im not sure why
its stats should be changed to be more inline with the raincoat which it is made from(make it about 1kg and volume could come down alittle bit, you are adding clasps and duct tape to it but not 1kg and 2.75L worth extra) and neoprene could be swapped out for cotton, and the pockets reduced(i assume you are making new pockets but they probably should be that good), and add waterproof flag(if it works) thats my suggestions anyway
as for the rubber i did some digging, rubber doesnt seem to be as fleshed out as much as it could be, its also implied by descriptions that there is 2 types of rubber synthetic and natural, the synthetic seems to be most common and is used interchangeably with plastic in some cases, there is also a lot more work that could be done on (dis)assembly for rubber items
seems like rubber just needs some love and attention
![image](https://user-images.githubusercontent.com/115079701/209456146-a2d0b10e-be15-401e-97b4-6a403ec54d84.png)
![image](https://user-images.githubusercontent.com/115079701/209456157-4600c6f3-57c4-4d44-94b3-0103d53ebda3.png)
![image](https://user-images.githubusercontent.com/115079701/209456152-b56783c1-faf7-42da-a108-36a52412f3db.png)
![image](https://user-images.githubusercontent.com/115079701/209456411-7309f871-7255-48d9-94b5-0505f3964cf4.png)
dog rainsuit's pockets
![image](https://user-images.githubusercontent.com/115079701/209456564-ea180ee1-8d80-460f-8edc-3f9e632785b3.png)
raincoat's pockets
![image](https://user-images.githubusercontent.com/115079701/209456554-dce74a5c-c6af-47cc-8fc1-b2beb515a452.png)
