### ISSUE TITLE
[User Experience] The crafting UI should show if hands are encumbered

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#62868]
### Is your feature request related to a problem? Please describe.

I have just found out that crafing time depends on hand encumbrance. It happened like this:
1. I knew how long crafting a throwing stick is supposed to take
2. I noticed a substantially longer crafting time
3. I sat there puzzled for several minutes trying to figure out whether this is a bug and what is causing this

![image](https://user-images.githubusercontent.com/52621858/209464291-cdbcda0d-f5d7-46d1-9fe0-58280fc0216a.png)
0 hand encumbrance

![image](https://user-images.githubusercontent.com/52621858/209464283-bd168b96-488c-492a-adc9-16212a9b0bf3.png)
20 hand encumbrance

### Solution you would like.

We should display a warning in the crafing UI under the "Proficiencies used" line
![image](https://user-images.githubusercontent.com/52621858/209464550-6f978ad2-f913-4816-bcb6-1570a21aa858.png)

**Comment by flybye3o6** [comment]
![image](https://user-images.githubusercontent.com/115079701/209465186-92bbf7d6-1e6d-41ec-b6ef-cb22e165543a.png)
the way i normally can tell if my hands are encumbered is the top right of the crafting screen, but this only says crafting is slowed down but not why, if it could say hands encumbered or low light next to it

**Comment by Night-Pryanik** [comment]
Something like this?
![изображение](https://user-images.githubusercontent.com/11132525/209467291-85a06f2b-cc77-4b00-a6bb-3548e88ef233.png)
