### ISSUE TITLE
Non-rigid containers in inventory don't fill up with liquids when asked to

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#62872]
### Describe the bug

Trying to fill up a non-rigid container in inventory transfers no liquids.

Workaround: Throw the container on the ground, fill it there, and pick it up when filled.

### Steps to reproduce

Have a huge container (`hiking backpack`) with a `gallon-sized zipper bag`
<details><summary>Get to a toilet, examine and decide to pour liquid into a container</summary>

![image](https://user-images.githubusercontent.com/13402666/209471930-4606baf2-c56a-4f2a-9f3b-37c011d59c95.png)</details>

<details><summary>Choose yours `gallon-sized zipper bag`</summary>

![image](https://user-images.githubusercontent.com/13402666/209471936-fe320635-d883-4bb4-8981-d3f68ed73a6a.png)</details>

<details><summary>This message appears in the log, but no liquid is transferred!</summary>

![image](https://user-images.githubusercontent.com/13402666/209471954-589c4c3d-6dc6-42a7-b781-c5f82bf713bc.png)</details>

### Expected behavior

Firstly, the solution:
1. Calculate how much can a container be filled to still fit into ANY non-blacklisted (etc.) pocket. (If only the same pocket were checked, a `gallon-sized zipper bag` in my pans would decide to contain only 0.25 L instead of throwing it into my `hiking backpack` for full 4.5 L).
2. Fill it up.
3. Throw into a suitable pocket.

Secondly, be truthful:
If I don't fill it up, then don't tell me I did!
E. g. check for volume transferred > 0 L
And a debug warning for when this happens.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 99451f2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
I can't reproduce this on the slightly older 622e8472f8. Starting with a naked character I did this:
![grafik](https://user-images.githubusercontent.com/38702195/209474161-3be7f140-afe2-4936-b108-87c4921e5579.png)
The described case can only happen if the parent pocket has no capacity for a single charge of the liquid. Although yes, the success message needs some checks to properly inform players what happened (and possibly why).

Having the bag move to a different pocket to allow it to fill up as much as possible is a different thing, though. Not sure if that's worth pursuing as opposed to something like requiring you to actually wield the container you want to fill up or leaving it as is with proper messaging.

**Comment by oosyrag** [comment]
Unable to reproduce on latest experimental.

Are you sure your gallon sized zipper bags were in your backpack? They were probably in your pant or shirt pocket or something, so the parent container didn't have enough additional space for a unit of water.

**Comment by Brambor** [comment]
I will try doing it again and adding a save file. There might be some misunderstanding on my part.

**Comment by moxian** [comment]
Repro save: [Bonneau.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10329358/Bonneau.zip)

Try to fill gallon-sized zipper bag with the water from the nearby pond.
You will get the message of 
![20230101-194419-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/210182943-17685178-710e-424d-8d1d-169f59c17487.png)
yet the bag will remain 
![20230101-194449-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/210182947-ad8a8c71-fe6d-4659-b349-b741718cebbd.png)
