### ISSUE TITLE
Make "Build Bed" a single multistep recipe

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#62871]
### Is your feature request related to a problem? Please describe.

Usually, multistep constructions are exactly that (single construction with multiple steps) and take only one slot in the construction menu (less clutter)
A perfect example where it isn't but should be used is Building a Bed

<details>
<summary>3 constructions of a bed</summary>

![image](https://user-images.githubusercontent.com/13402666/209471493-6c3d6900-d8bd-4a03-8d37-1378d1692bc1.png)
![image](https://user-images.githubusercontent.com/13402666/209471500-fed74ba3-f43f-4f28-8b27-fcb55372651c.png)
![image](https://user-images.githubusercontent.com/13402666/209471501-90c3e354-bc01-4a8c-8807-11888f7d2a1b.png)
</details>
<details>
<summary>Some example of multistep construction</summary>

![image](https://user-images.githubusercontent.com/13402666/209471717-ee61cba9-ab9f-4243-b857-f18b94818fce.png)
</details>

### Solution you would like.

Single construction with two steps. The two steps should be the two more granular recipes.
This single construction should replace the three constructions.

**Comment by flybye3o6** [comment]
![image](https://user-images.githubusercontent.com/115079701/209512691-201b6898-3b9a-4ce6-92d6-6f59c1df4a95.png)
something like that?

**Comment by Night-Pryanik** [comment]
Yeah, that's good. You can open a PR with your changes.
