### ISSUE TITLE
[Magiclysm] Infinite Teapot

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#62884]
### Is your feature request related to a problem? Please describe.

So... We have infinite whiskey in Magiclysm. But what about infinite teapot?
If they can use enough magic to make flasks with endless whiskey, there's no doubt they also did it for teapots.

### Solution you would like.

Add a magic teapot that creates infinite green tea.

### Additional context

I wonder how the wizards actually make those..

**Comment by GuardianDll** [comment]
Btw you don't need to close it, it will be closed automatically (or by one who merge the pr) if you mention it in the PR's description
