### ISSUE TITLE
Isherwoods leave their guns on the floor

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62897]
### Describe the bug

They have guns.. with no bullets.. and they just stand on top of them. This makes them trivial to steal just by making noise.

### Steps to reproduce

Find an Isherwood standing on their rifle. Make some noise out of their line of sight and watch them abandon their weapon to investigate.

Take the weapon using whatever method you prefer.

### Expected behavior

Rifles should be in their inventory... and loaded.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12833-g4179a45695f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by oosyrag** [comment]
#55780

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
