### ISSUE TITLE
Salvaging certain rubber items provides far less rubber than it should

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#62890]
### Describe the bug

Salvaging (cutting up) a rubber object that has a disassembly recipe results in far less rubber than one would expect, usually nowhere near the amount disassembling it would provide.

### Steps to reproduce

1. Spawn a carving knife, three rubber tire strips, and a rubber hose.
2. Disassemble the first tire strip into 5 thick rubber chunks, and then disassemble those thick chunks into 16 chunks of rubber each, for 80 chunks total.
3. Use the knife and cut up the second tire strip. The result will be merely 4 chunks of rubber, 20 times less than disassembling provides. Also, the thick chunks are skipped entirely, though that's not entirely unexpected, since cutting an object is implied to be slapdash.
4. Disassemble the third strip into 5 thick rubber chunks, and then use the knife to cut up those thick chunks. Every attempt will inexplicably fail, leaving you with nothing.
5. Use the knife to cut up the rubber hose, you should get 14 chunks of rubber, a proper amount. Note that the hose doesn't have a disassembly recipe.
6. Oddly, the rubber sole seems to bypass this bug despite having a disassembly recipe. Salvaging results in 3 chunks. I can't tell what the sole is doing correctly that other rubber objects are not.

### Expected behavior

I'd expect cutting up an item to give me a little less than the results of a careful disassembly, but not _this_ much less. It feels like the game is thinking rubber chunks are far larger than they actually are and erroneously calculating conservation of mass because of it. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2364 (22H2)
- Game Version: 8fc80f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by oosyrag** [comment]
Salvage (cutting up) has nothing to do with having a disassembly recipe or not. The materials returned from salvage are calculated by the salvage function depending on a few variables. The disassembly recipes on the other hand are explicitly defined so they may not always make sense.

Leaving a note to link this to #62861, I plan on diving into the salvage code after stable and rubber would be addressed as well.

**Comment by Kamayana** [comment]
> Salvage (cutting up) has nothing to do with having a disassembly recipe or not. The materials returned from salvage are calculated by the salvage function depending on a few variables. The disassembly recipes on the other hand are explicitly defined so they may not always make sense.
> 
> Leaving a note to link this to #62861, I plan on diving into the salvage code after stable and rubber would be addressed as well.

There's definitely _some_ kind of interaction with the disassembly recipe. For example if I change the spatula's uncraft recipe from chunk_rubber to plastic_chunk then cutting it up results in plastic - no edits to the spatula's materials at all. This part of the cut_up function seems to be responsible for that: [iuse_actor.cpp#L1559](https://github.com/CleverRaven/Cataclysm-DDA/blob/47a73ad305e0f41d55a371ac71a7d65292a31679/src/iuse_actor.cpp#L1559). This would get addressed in a revisit to the salvage code anyway, though, so I'm all for that.

**Comment by oosyrag** [comment]
Ah you're right, I did miss that
