### ISSUE TITLE
make large plastic sheets an auto pickup when taken off the floor.

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#62902]
### Is your feature request related to a problem? Please describe.

I always keep a large plastic sheet on me whenever I want to butcher or dissect an animal far from my base, however I find it somewhat annoying that the sheet isn't picked up automatically when its taken off the ground. this has resulted in me losing my butchering sheets multiple times and having to find a new one.

### Solution you would like.

Instead of having the sheet be a manual pickup, I think it should be automatic (unless there isn't enough space for the player to carry it)

**Comment by oosyrag** [comment]
Have you tried using the existing auto pickup feature?

**Comment by 7erracotta** [comment]
oh wait, thats a thing? i never knew about that.
