### ISSUE TITLE
 Cataclysm-DDA failed to runtests with WARNING : opendir [./test_user_dir/mods/] ,[lang/mo/] failed with "The system cannot find the path specified.".

### ISSUE THREAD

**Issue by nnfdnkns** [CleverRaven/Cataclysm-DDA#62919]
### Describe the bug

Cataclysm-DDA failed to runtests with WARNING : opendir [./test_user_dir/mods/] ,[lang/mo/] [./test_user_dir/gfx], [data/cache],[./test_user_dir/mods], [./test_user_dir/save/Test World/mods] failed with "The system cannot find the path specified.". .Could you please help look at this issue?

### Steps to reproduce

1. git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
2. git clone https://github.com/microsoft/vcpkg F:\gitP\CleverRaven\vcpkg
3. cd F:\gitP\CleverRaven\vcpkg
4. git rev-parse --git-dir 2>&1
5. git clean -xdf 2>&1
6. git fetch --recurse-submodules=no --force 2>&1
7. git reset --hard 61a704c 2>&1
8. .\bootstrap-vcpkg.bat -disableMetrics
9. .\vcpkg integrate install
10. mkdir F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64
11. cd F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64
12. msbuild /m /p:Platform=x64 /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64 /t:Rebuild 2>&1
13. cd F:\gitP\CleverRaven\Cataclysm-DDA
14. F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64\Cataclysm-test-vcpkg-static-Release-x64.exe 2>&1

### Expected behavior

Cataclysm-DDA runtests successfully

### Screenshots

**error ifo:**
F:\gitP\CleverRaven\Cataclysm-DDA\tests\vehicle_test.cpp(387): FAILED:
  CHECK( player_folded_veh.damage() == preset.item_damage_second_fold )
with expansion:
  1962 (0x7aa) == 1961 (0x7a9)
with messages:
  preset.folded_vehicle_item.str() := "folded_bicycle"
  preset.item_damage_first_fold := 1689 (0x699)
  preset.item_damage_second_fold := 1961 (0x7a9)
  preset.part_damage_second_unfold := 18582 (0x4896)
  preset.part_damage_third_unfold := 21582 (0x544e)
test cases:      980 |      979 passed | 1 failed
assertions: 28216638 | 28216636 passed | 2 failed

### Versions and configuration

OS: Windows server 2019
Compiler: VS 2019

### Additional context

log:
[test.log.2.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10315200/test.log.2.log)

**Comment by BrettDong** [comment]
`WARNING : opendir [./test_user_dir/mods/] ,[lang/mo/] failed with "The system cannot find the path specified."`

It's only a warning. The test failure you got is unrelated to this message.
