### ISSUE TITLE
Crater-creating explosion random events are way too common

### ISSUE THREAD

**Issue by Error-String-Expected-Got-Nil** [CleverRaven/Cataclysm-DDA#62925]
### Is your feature request related to a problem? Please describe.

I have, in my current playthrough, encountered no less than 5 craters in the 6 days (in game) this save has been up. Probably more. Granted, this is from frequent exploration, but it's a bit ridiculous.

Besides this, what exactly the craters were/were caused by was extremely unclear and I was left wondering if it was a bug for awhile before I asked online to see if anyone else had any ideas.

### Solution you would like.

Reduce the frequency of these craters spawning.

### Describe alternatives you have considered.

Leave it as is, I guess. Or maybe put something in them to actually indicate what's going on.

### Additional context

These things.
![Screenshot (1849)](https://user-images.githubusercontent.com/103805191/209916020-c3ebd030-6546-4291-af06-90f10648873d.png)

EDIT: As if to punctuate my point, I got another one of these things not 2 minutes after posting this suggestion. It's ridiculous.

**Comment by PatrikLundell** [comment]
As far as I understand, the explosion is intended to have happened as part of the mess of the cataclysm itself, and I would assume at least the small ones to be artillery or bomb craters. However, I don't think the current map generation logic supports the generation of "realistic" craters where the top and bottom layers match up, and so the work around to place an explosive that's detonated as the map comes into the reality bubble is used, as the explosion logic is capable of generating craters that are consistent on both levels.

**Comment by Night-Pryanik** [comment]
Why should they be less common? What's your rationale? "I think they are too frequent" is way too subjective.

**Comment by GuardianDll** [comment]
Why are they happen btw? something bombard the planet? gas leak? what's the reason from lore side?

**Comment by PatrikLundell** [comment]
As far as I understand they're military strikes against the gigantic horrors that supposedly caused havoc during that time. I believe there are or will be one or more locations featuring the corpse of such a horror, but as far as is known they all disappeared when the reality shattering cataclysm weakened into the current mess. After all, gravity defying critters from dimensions with different laws of physics may have a hard time dealing with the physics of our dimensions once the rules have been almost(?) completely restored on the macro level.

**Comment by DSeyka** [comment]
Making those explosions invisible and inaudible would be a decent workaround.
