### ISSUE TITLE
[Backrooms] Unable to place all configured specials, some missions may fail to initialize

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#62924]
### Describe the bug

See title.

### Steps to reproduce

1. Start a generic custom character in a backrooms world.
2. Get this non-fatal warning-info thing when you enter the world.

### Expected behavior

No error.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-12810-gdf83f9a8413 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    The Backrooms [backrooms]
]

**Comment by Maleclypse** [comment]
Hmm we need to figure out a way to disable that warning via json in mod settings probably.  Exoplanet could use it as well.

**Comment by Procyonae** [comment]
Should be fixed for Backrooms by #74434 as it uses a whitelist now

**Comment by NetSysFire** [comment]
Yeah, can no longer reproduce.
