### ISSUE TITLE
Toggle snap to target does not toggle off

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#62939]
### Describe the bug

Pressing '*' to toggle snap to target when aiming does not toggle off.

### Steps to reproduce

Begin aiming.
Press '*' 
Press it again.

### Expected behavior

Toggle implies that it can be toggled both on and off

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12833-g4179a45695f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by irwiss** [comment]
It appears to be temporary toggle by design
https://github.com/CleverRaven/Cataclysm-DDA/blob/b02264e743079020c4af2abb04458befe061c6e3/src/ranged.cpp#L237-L239

If you want to toggle permanently change it in options

**Comment by JazzGlobal** [comment]
> It appears to be temporary toggle by design
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/b02264e743079020c4af2abb04458befe061c6e3/src/ranged.cpp#L237-L239
> 
> If you want to toggle permanently change it in options

Any idea why it's this way? I see that there are comments indicating it was left that way intentionally but should it be?

**Comment by irwiss** [comment]
No idea, I'm not the author and I don't think I ever used either option, if I wanted to look around I'm fine with just moving the cursor + view together
