### ISSUE TITLE
Infinite loop in long activities

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62941]
### Describe the bug

Some long activities simply hang in an infinite loop. Not easily repeatable, but happen not quite rarely. This time, I was dismembering a corpse. Have done other long activities in this area w/o issue. Interface is simply frozen.

Afraid I have no debugging symbols available.

#1  0x0000000001e112b8 in options_manager::get_option(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
No symbol table info available.
#2  0x0000000001365a07 in Character::weary_threshold() const ()
No symbol table info available.
#3  0x0000000001365b01 in Character::weariness_level() const ()
No symbol table info available.
#4  0x000000000136578e in Character::maximum_exertion_level() const ()
No symbol table info available.
#5  0x00000000013657e6 in Character::exertion_adjusted_move_multiplier(float) const ()
No symbol table info available.
#6  0x0000000001f20ae8 in player_activity::do_turn(Character&) ()
No symbol table info available.                                                
#7  0x00000000015b3986 in do_turn() ()                                         
No symbol table info available.                                                                                                                                
#8  0x0000000001a50fea in main ()                                                                                                                              
No symbol table info available.                                                                                                                                

### Steps to reproduce

Play the game. I have no idea.

### Expected behavior

Long activities should at least progress. CPU should not spike while time freezes.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12833-g4179a45695f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrei8l** [comment]
Please provide a save file where this happens

**Comment by BrettDong** [comment]
Nothing actionable without a save to reproduce the bug.
