### ISSUE TITLE
Autodrive drives over some risky terrain

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#62943]
### Describe the bug

Autodrive can drive over some risky terrain, sometimes to a fault. I've not only experienced it driving over deep water (safely, but barely so), and recently have just been thrown into a crater due to it.

### Steps to reproduce

1. Get a vehicle (the various bicycles seem to be the most affected)
2. Autodrive it (intentionally through some risky terrain, such as a pond or crater)
3. Notice its xtreme manuevers and/or failure as it crashes/sinks the vehicle

### Expected behavior

Autodrive assuredly makes 0-risk maneuvers by itself.

### Screenshots

![above](https://user-images.githubusercontent.com/32048635/210123839-c7f2db09-f777-4ee0-b24e-4c1bc37d4601.png)
![under](https://user-images.githubusercontent.com/32048635/210123842-97069827-807d-48f1-8cc7-705d9a5b5eb2.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: e171fb3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex]
]

### Additional context

Potential duplicate of #56402

**Comment by intergalacticdata** [comment]
It'll also drive you quite a bit into raging fire before stopping w/ the vehicle partially in the fire.

**Comment by toweroglass** [comment]
in my most recent game i had it drive right over a crater and somehow not fall in.

**Comment by inverimus** [comment]
Autodrive will almost always drive straight through newly formed craters. My guess is because they get created after the path has been chosen.
