### ISSUE TITLE
Allowing players to disable tracking monsters distraction

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#62948]
### Is your feature request related to a problem? Please describe.

Especially while auto-driving, you'll occasionally run across some creatures/monsters, and be disrupted by a dialogue asking if you want to stop doing so and take manual control. This makes sense if you're running head-first into a mass grave or just any monster group you don't want the auto-drive to handle alone; however, you also commonly get the same disruption called when a creature is just tracking you and is not actively hostile, commonly from canines and/or moose, and there is no difference for the auto-drive.

### Solution you would like.

For their to be a separation between actively hostile monsters, and simple creatures that are tracking you.

### Describe alternatives you have considered.

 Ignoring all monsters and hoping to not be surrounded by a horde

**Comment by Night-Pryanik** [comment]
Related to #23828.

**Comment by PatrikLundell** [comment]
"Tracking" can turn into an attack, especially if your path happens to pass close to the critters. Even if a critter isn't actively hostile, it can still decide to move into the path of the vehicle, and there are places you don't want to spend more time than necessary (such as e.g. any fungal expansion).
