### ISSUE TITLE
Filtering/Searching clothing by layer/coverage

### ISSUE THREAD

**Issue by mlgproftw** [CleverRaven/Cataclysm-DDA#62958]
### Is your feature request related to a problem? Please describe.

With all the new sub-parts added to the body part system it has become extremely tedious to manage clothing. Finding which clothing covers what area, what layer that clothing is etc. If you have a stack of clothing it's really hard to find and compare the different clothing you have for different body parts and different layers. This issue has already been addressed somewhat in the crafting menu where you can filter by description but it's still quite inadequate. The show items or inventory menu however are still really bad where it's impossible to know which clothing covers what area and what layer that clothing is on unless you already know by memory, even then you have to peruse through them all and compare them individually.

### Solution you would like.

Add ways to filter clothing by the area they cover or the layer they are on. 

Example: 
Covers:Torso, Layer:Close to Skin

I found out that "covers:" is already a filter in the game filtering manuals by what subjects they cover, but that filter is already there with "s:" so there's no need for "covers:" to act the same way "s:" does.

### Describe alternatives you have considered.

Simply implementing the crafting menu's description filter could also work

**Comment by oosyrag** [comment]
Have you tried the (+) Sort Armor interface?

**Comment by mlgproftw** [comment]
The sort armor interface only works for clothing you are already wearing (unless I am mistaken). My issue is with sorting through stacks of clothing that you might have stored on the ground or in a container etc. (mostly to find out which ones you _want_ to wear). A temporary solution could be just wearing every clothing and sorting them through the sort armor menu, but this would take way more time than necessary and doesn't really make sense in my opinion.

**Comment by DSeyka** [comment]
I would also like these filters to work in crafting menu, if anyone decides to tackle this, pretty please.
