### ISSUE TITLE
Crash when (e)xamining the bikerack when towing cable is installed on the racked vehicle

### ISSUE THREAD

**Issue by marilynias** [CleverRaven/Cataclysm-DDA#62953]
### Describe the bug

When towing a vehicle with the towing cable installed on a bikeracked vehicle, the game crashes when you try to (e)xamine the bikerack.

### Steps to reproduce

1. Spawn a vehicle with bikerack and a bike
2. attach bike to bikerack
3. spawn another vehicle to be towed
4. attach a towing cable to the bike and the other vehicle
5. (e)xamine the bikerack

### Expected behavior

opening the actionmenu to be able to remove bike from rack, either stating that you cant remove bike while towing or removing towing cable in the process

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 7f881d8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10328690/debug.zip)

**Comment by PatrikLundell** [comment]
A work around is to detach the tow cable from the towed vehicle rather than from the towing one. This will detach the cable from both vehicles without the need to examine the bike rack.

However, I believe it used to work to detach the cable from the towing vehicle's biking rack.

**Comment by marilynias** [comment]
I had a simmilar issue to https://github.com/CleverRaven/Cataclysm-DDA/issues/59546 except i couldnt detach the cable. I had to edit the save files to remove  the cable.
