### ISSUE TITLE
Ubuntu SDL don't start.

### ISSUE THREAD

**Issue by CEHA** [CleverRaven/Cataclysm-DDA#62967]
### Describe the bug

New year - new system. I decided to switch from Debian to Ubuntu - I'm caught a bunch of freezes of the system itself, but about the game :
SDL:
`Error while initializing the interface: Cannot load font data/font/Terminus.ttf` 
Curces:
All is ok.

### Steps to reproduce

1. Install Ubuntu
2. Install CDDA-SDL

### Expected behavior

Gaming

### Screenshots

Black screen.

### Versions and configuration

Lenovo G575
Ubuntu 23.04 AMD64
CDDA Latest 

### Additional context
The logs looked like this:
https://askubuntu.com/questions/1352158/libgl-error-failed-to-load-drivers-iris-and-swrast-in-ubuntu-20-04

Return to Debian SID/Bookworm/Unstable - all work great.

**Comment by CEHA** [comment]
Return to Debian SID/Bookworm/Unstable - all work great.

**Comment by andrei8l** [comment]
Sounds like you need to install the right GPU driver. Can you upload your `debug.log` please?
