### ISSUE TITLE
Can't lead cows(specifically) by the leash.

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#62973]
### Describe the bug

I have found a farm with horses, sheep and cows. I tamed all three, and led horses and sheep into pens, but i can't seem to lead cows. I leash them, i "lead them by the leash", but they are not moving to follow me no matter how far away i get. And I'm not getting a "you lose hold of your leash" message either.

### Steps to reproduce

- Load the attached save
- `e`xamine the friendly cow nearby
- attach leash to a cow (use long rope)
- `e`xamine the cow again
- `l`ead cow by the leash
- move away
- see cow not following 

I want to stress again that this is somehow only the issue with cows (i tried with two different ones) - sheep and horses handle it fine.

### Expected behavior

Cow stays close to me

### Screenshots

![20230103-013000-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/210289835-b2def232-2d52-43e9-9fba-18043b183ade.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: ba42c0a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Winters-cow.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10333955/Winters-cow.zip)

P.s.: the *third* cow i tried respects being leashed. So it's not the issue with cows in general, but only specifically with the two i ran into first.

**Comment by DalenTalas** [comment]
I'm seeing this with pretty much any animal. I suspect this has something to do with movement speed differences.
