### ISSUE TITLE
Cataclysm-DDA failed to runtests with F:\gitP\CleverRaven\Cataclysm-DDA\tests\vehicle_test.cpp(387): FAILED: CHECK( player_folded_veh.damage() == preset.item_damage_second_fold ) with expansion: 1962 (0x7aa) == 1961 (0x7a9)

### ISSUE THREAD

**Issue by nnfdnkns** [CleverRaven/Cataclysm-DDA#62978]
### Describe the bug

Cataclysm-DDA failed to runtests with F:\gitP\CleverRaven\Cataclysm-DDA\tests\vehicle_test.cpp(387): FAILED: CHECK( player_folded_veh.damage() == preset.item_damage_second_fold ) with expansion: 1962 (0x7aa) == 1961 (0x7a9). Could you please help look at this issue?

### Steps to reproduce

git clone https://github.com/CleverRaven/Cataclysm-DDA F:\gitP\CleverRaven\Cataclysm-DDA
git clone https://github.com/microsoft/vcpkg F:\gitP\CleverRaven\vcpkg
cd F:\gitP\CleverRaven\vcpkg
git rev-parse --git-dir 2>&1
git clean -xdf 2>&1
git fetch --recurse-submodules=no --force 2>&1
git reset --hard 61a704c 2>&1
.\bootstrap-vcpkg.bat -disableMetrics
.\vcpkg integrate install
mkdir F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64
cd F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64
msbuild /m /p:Platform=x64 /p:Configuration=Release ..\msvc-full-features\Cataclysm-vcpkg-static.sln /p:OutDir=F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64 /t:Rebuild 2>&1
cd F:\gitP\CleverRaven\Cataclysm-DDA
F:\gitP\CleverRaven\Cataclysm-DDA\build_amd64\Cataclysm-test-vcpkg-static-Release-x64.exe 2>&1

### Expected behavior

Cataclysm-DDA runtests successfully

### Screenshots

![image](https://user-images.githubusercontent.com/109710140/210321945-08f34349-5205-4a41-96c4-b98834f13209.png)

### Versions and configuration

OS: Windows server 2019
Compiler: VS 2019

### Additional context

log:
[test.log.2.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/10335121/test.log.2.txt)

**Comment by ZhilkinSerg** [comment]
Follow issue template.
