### ISSUE TITLE
Using meds via activating their container consumes the whole stack

### ISSUE THREAD

**Issue by PersonGuyThe** [CleverRaven/Cataclysm-DDA#62997]
### Describe the bug

I am quite new and don't know the proper names for the different menus/actions, so I will also refer to them with their default keybindings.

When activating a container (i -> select the container -> RETURN -> a) which holds certain meds, namely pills, one of the listed actions is to consume said med. _Doing so will consume the entire stack of the med instead of one portion,_ contrary to what is shown in the activation menu (where it says -1).

This effects meds which do not have a specific target, such as pills and saline solution. Meds which are then applied to limbs, such as bandages and antiseptic, are not prone to this.

Selecting and activating the med from the inventory directly, or using the consumption menu (E) still works fine.

I happen to be playing on the Dec 27 experimental build, but I didn't see anything like this addressed in the changelogs since then. Please correct me if I'm wrong.

### Steps to reproduce

1. Pick up any container holding multiple aspirin
2. Open the inventory ( i )
3. Highlight the container
4. Select it (RETURN)
5. Activate (a)
6. Take the consume action 
The container will no longer have any aspirin, no matter how many it contained originally

### Expected behavior

I expect only one aspirin to be consumed, as the action is described with a -1 ( ex. Consume aspirin(8)(-1) )

### Versions and configuration

OS: Windows 10 x64
Game Version: Experimental 2022-12-27-0658
Graphics Version: Tiles
Language: English
Mods: dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions

### Additional context

I know the consume menu is better, still trying to break noob habits

**Comment by mikegogulski** [comment]
I'm on the same version and can confirm this, at least with respect to plastic painkiller bottles and small plastic bottles. In addition to more than the expected single tablet disappearing on activation, the popup action menu looks rather odd:

From plastic painkiller bottle:
![image](https://user-images.githubusercontent.com/118625/211900380-627b76ff-91bd-4889-b38c-c08e9c4980d6.png)

From small plastic bottle:
![image](https://user-images.githubusercontent.com/118625/211900512-e39e0d3d-fca3-457d-b3c9-dba1c525c947.png)
