### ISSUE TITLE
Vomiting is too aggressive

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#62999]
### Is your feature request related to a problem? Please describe.

Currently any time you become queasy you're almost guaranteed to vomit, even if you don't have the Weak Stomach/Nausea/Vomitous traits, and even if you have triple dosed on heartburn medicine. Further, when you vomit, you instantly empty your entire stomach and delete all nutrition you are currently digesting. This isn't true to real life, as it takes a lot of vomiting to actually clean out your stomach rather than a single upchuck totally evacuating the contents of your stomach. In addition, even people who experience seasickness don't always vomit, even without a stomach soother, and that's over the course of several hours, as in game even giving it a few minutes you're exceedingly likely to have vomited even in the best possible conditions. Strong Stomach does actually have a pretty good effect on your vomit chances, but they're still clearly too high.

### Solution you would like.

Vomiting should be a lot less likely, and possibly be in degrees - being covered in boomer vomit would probably be worse for you than getting nauseous from a medication or mutagen for example. Further it shouldn't totally throw up everything in your stomach at once but rather a percentage of its contents.

### Describe alternatives you have considered.

Throwing up while wearing a face covering, especially a gas mask, should probably have consequences of some sort since it's pretty silly that you can magically project your vomit out of your sealed power armor with no additional consequences compared to regular vomiting. 

Getting queasy might also reasonably reduce your speed as it currently literally only makes you vomit and nothing else when IRL nausea can be very debilitating.

**Comment by PatrikLundell** [comment]
It can also be noted that vomiting can only purge the body of the stomach contents, not the stuff that's moved further down into the system (intestines), where flushing has to be done through the rear end. Thus, only some of the "stomach" contents should actually be available for vomiting, reducing the calorie cost of vomiting.
