### ISSUE TITLE
Cannot load "5.56x45mm/.300BLK 10-round clip" speedloader with bullets into non-empty magazine

### ISSUE THREAD

**Issue by Actdye** [CleverRaven/Cataclysm-DDA#62992]
### Describe the bug

I can use clips when loading an empty magazine, but if the magazine will not be completely empty (like 10/30), the magazine turns from green to red and I cannot use clips to reload that magazine. 

### Steps to reproduce

1. Make a player with M4A1 rifle, 2 x 5.56x45mm/.300BLK 10-round clip (10/10) and empty STANAG magazine (30 rounds)
2. Load one clip into the empty magazine
3. Try to load another one clip into non-empty magazine

### Expected behavior

I expected that the clips could help to reload a magazine to the full capacity. 
I think there would not be much use to use clips to load the magazine to one-third of its capacity because it would be more convenient to unload these clips and reload the magazine manually, which is monotonous process. 

### Screenshots

![bug_1](https://user-images.githubusercontent.com/100567229/210611737-aea32e74-588a-41e7-b4bd-7b48f091893d.png)
![bug_2](https://user-images.githubusercontent.com/100567229/210611751-be40ccaa-f9a1-46e1-b354-80688918361a.png)
![bug_3](https://user-images.githubusercontent.com/100567229/210611756-46a171d9-3743-4cc3-a5c6
![bug_4](https://user-images.githubusercontent.com/100567229/210611772-89dfad60-d807-497e-9282-2e6801aa72e1.png)
![bug_5](https://user-images.githubusercontent.com/100567229/210611798-f6f43fcd-bee6-4b7f-b23e-4d10f7d734a0.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.10; Release: 22.10; Codename: kinetic; 
- Game Version: 5772feb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[bug_clip_map.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10346211/bug_clip_map.zip)

**Comment by GuardianDll** [comment]
duplication of #62721
