### ISSUE TITLE
"Turned on dashboard" instead of "Turned on dome lights"

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#62991]
### Describe the bug

Turning dome lights on and off in my vehicle, regardless of whether or not I'm driving and regardless of whether or not I'm in the seat with the controls, results in "Turned on dashboard" and "Turned off dashboard" instead of "Turned on dome lights" and "Turned off dome lights"

### Steps to reproduce

1. Make a minimal vehicle with a control station as shown in my second screenshot
2. Turn dome lights on and off in various combinations of vehicle on/vehicle off, in seat/not in seat.
3. Observe incorrect messages.

### Expected behavior

The message log displays something reflecting that it's the dome light(s) being toggled, not the dashboard.

### Screenshots

![image](https://user-images.githubusercontent.com/118625/210613661-d8f961f4-d384-4b0e-b4d9-2ce34852f7f6.png)
![image](https://user-images.githubusercontent.com/118625/210613785-b58bc1a5-a1dc-4526-a050-da3fe6304d9b.png)

### Versions and configuration

Windows 11 Pro
2022-12-27-0658
Tiles
English
Lots of mods installed

**Comment by Zanthra** [comment]
The only dome light in that vehicle is the active feature of the dashboard. If you were to install another item, such as a second dashboard or an electronics control unit that is also a dome light, you would get a message about both of them being turned on or off simultaneously when you toggle the dome lights.

![image](https://user-images.githubusercontent.com/30186391/210699938-36f9c189-9d8a-432e-8bc6-14134c6f7f03.png)

**Comment by mikegogulski** [comment]
Oh! Thank you for clarifying that. I didn't notice any change in lighting because I (foolishly) tested this during the day.

It still seems a tad confusing, but I confess that I can't really think of a way to make the behavior clearer that isn't silly, like requiring separate "turn on dashboard/ECU" options or having it say "well, no dome lights here, but...".
