### ISSUE TITLE
Lanyard is uncomfortable

### ISSUE THREAD

**Issue by YourCompanionCube** [CleverRaven/Cataclysm-DDA#63002]
### Describe the bug

Lanyards are considered uncomfortable because their material is plastic

### Steps to reproduce

wear a lanyard and nothing else
see the uncomfortable (torso) status

### Expected behavior

that a piece of ribbon wouldn't cause chafing

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2364 (22H2)
- Game Version: a00a2ec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    No Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    return_the_nut [return_the_nut]
]

**Comment by Maleclypse** [comment]
Wearing a lanyard shirtless is uncomfortable.

**Comment by YourCompanionCube** [comment]
i've never found it to be uncomfortable (nor have the many lifeguards i've seen) but it definitely isn't as bad as wearing chainmail without padding is (and i've done that too, it *sucks*) which is what the uncomfortable tag is supposed to represent

**Comment by Maleclypse** [comment]
Give it the padded effect then. Easy fix.

**Comment by Maleclypse** [comment]
My work lanyard would be quite uncomfortable but it has no fabric parts so I’ll approve it if you make the change you want to see.

**Comment by YourCompanionCube** [comment]
tbh the only reason i don't make a bunch of little commits like this is i've never had the energy to learn github, i know the JSON isn't that hard
