### ISSUE TITLE
Expandable containers in small or full pockets provide no feedback

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#63003]
### Describe the bug

Expandable containers report their total capacity, but may only expand to the space they are in when used. There is no feedback to the user as to why this happens.

This leads to confusion as to why a condom, for example, reports 3.75L of storage and only fills to .25L.

### Steps to reproduce

Put a condom in a mostly full pocket and milk a cow or whatever.

### Expected behavior

The user should be provided with some feedback as to why they are only able to partially fill their container.

### Versions and configuration

I don't have a running game atm, but the latest experimentals have this behavior.

**Comment by Brambor** [comment]
Duplicate of #62872
