### ISSUE TITLE
Metabolic Exchange does not recharge bionic power when activated

### ISSUE THREAD

**Issue by borisshvonder** [CleverRaven/Cataclysm-DDA#63006]
### Describe the bug

The Metabolic Exchange CBM consumes the chemical energy (character gets hungry) but does not recharge the bionic power as it supposed to.

### Steps to reproduce

1. Create character with "Bionic Patient" profession.
2. Open Bionics menu ("p" key)
3. Activate "Blood filter" bionic to consume some power
4. Activate "Metabolic Interchange" bionic
5. Wait for an hour ("|" key)

### Expected behavior

The bionic power should go up to 250kJ. The metabolic interchange should turn off itself automatically.

Instead, the bionic power stays at 249.400kJ, the metabolic interchange does not turn off and the character becomes hungry.

### Screenshots

![image](https://user-images.githubusercontent.com/41071175/210874409-b86167bb-abb8-44ff-bb84-bbcae4a75e9b.png)

### Versions and configuration

OS: Windows 10
Game package:  cdda-windows-tiles-x64-msvc-2023-01-04-0604.zip
Tiles: Yes
Version String: 2023-01-04-0604

### Additional context

The metabolic exchange does not seem to work at all. It is also quite confusing that it is displayed as "(inactive)" when activated.

**Comment by andrei8l** [comment]
It appears to be working correctly. You have fuel saving enabled so the CBM won't turn on for less than 0.25 (efficiency) *1kcal = ~1kJ (see the `inactive` bit at the end).

Fresh characters go hungry after an hour anyway. Try eating a pizza or double-checking your calories with the debug menu if you want to be perfectly sure.

**Comment by borisshvonder** [comment]
Thank you for clarification. It wasn't obvious to me that Metabolic Exchange could be activated permanently and then it would activate/deactivate itself automatically. I think it used to be different.
