### ISSUE TITLE
Unused .22 casings spawning where they should realistically be used casings

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#63000]
### Describe the bug

The game scatters the map with random spent casings, probably representing gunfire during the chaos of the cataclysm. Take a walk outside and you'll see a few random casings scattered around. But you'll also find that the .22 casings you see are unused, despite representing the leftovers of past gunfire. I think this is an unintentional side-effect of #62562.

### Steps to reproduce

1. Take a scroll around some random fields, using 'V' to list the items in your field of vision.
2. You'll eventually find unused .22 casings, representing the now-forgotten art of firing a bullet without using its primer.

### Expected behavior

Used .22 casings should be spawning instead of unused .22 casings, because these casings are probably from past gunfire rather than Santa sprinkling bullet casings across the world as a gift to handloading enthusiasts.

### Screenshots

Took a single step outside from my starting evac shelter and immediately found an example.
![Screenshot 2023-01-04 202517](https://user-images.githubusercontent.com/38295275/210701602-13e2d744-679e-4ee8-9885-98e5b6d40c31.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: a00a2ec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth]
]

**Comment by anoobindisguise** [comment]
I thought those were hardcoded, not jsonified. They should probably use a different itemgroup then to represent the casing difference.
