### ISSUE TITLE
Disassemble favourite items prompt "Are you sure?"

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#63022]
### Is your feature request related to a problem? Please describe.

I opened the disassembly window and pressed `f` for search, but `/` is for search, so I disassembled my favourite __* hammer__ instead.

### Solution you would like.

Before disassembling favourite items, prompt "Are you sure you want to disassemble X?"

**Comment by cake-pie** [comment]
Duplicate of #62687 and will be resolved by #63123

**Comment by Brambor** [comment]
> Duplicate of #62687 and will be resolved by #63123

Thanks, closing then as #63123 will not close it automatically.
_Unfortunately, another awesome feature that will not be in 0.G since we are in string freeze :/_
