### ISSUE TITLE
A felt patch recipe gives more than 1 felt patch per craft.

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#63025]
### Describe the bug

i don't know if this is intended, but if you craft a felt patch using wool staple, clean water, and soap bars you get 27 felt patches instead of 1, it doesn't say you get more than 1 on the crafting menu. and 27 is an odd number (pun definitely intended)

i am playing with megafauna and innawood, i don't know if this is innawood related but the origin doesn't say so.

### Steps to reproduce

1. make a felt patch from this recipe
2. notice you get a lot more than one

### Expected behavior

only getting 1 felt patch?

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/211140863-92da2b27-9132-4a39-9f5f-de2bba104b6d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 6df9e6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Megafauna [megafauna]
]

**Comment by cake-pie** [comment]
The output number of 27 is intended, and seems reasonable -- the input of one 500ml / 200g wool staple should be able to yield multiple patches.
https://github.com/CleverRaven/Cataclysm-DDA/blob/c4b37691185b32b230c8ce8692fab89f0acc2892/data/json/recipes/other/materials.json#L345

That means this is a problem of the crafting GUI not reflecting the correct output quantity and stats.

**Comment by flybye3o6** [comment]
felt patch is 3g and 18ml, wool staple that its made from is 200g and 500ml, i can understand volume loss because it is being compacted but weight conversion should actually yield 66 instead of 27, but im not sure on the process, but definitely not 1 felt patch for 1 wool staple

**Comment by flybye3o6** [comment]
> That means this is a problem of the crafting GUI not reflecting the correct output quantity and stats.

there was a PR that was recently merged that was talking about this #62831 
is it posable that this is already fixed by this

**Comment by Devengel** [comment]
ahh i see! its seems to be a GUI issue then

**Comment by flybye3o6** [comment]
![image](https://user-images.githubusercontent.com/115079701/211147661-ac41dc79-db16-4342-a5b8-606c4baac074.png)
issue is already fixed, still a weight inconsistency though

**Comment by Devengel** [comment]
ahhh apologies!, i will mark as closed then.
