### ISSUE TITLE
NPC's given non-camp Tasks cannot perform job unless manually handed tool

### ISSUE THREAD

**Issue by Zourin2** [CleverRaven/Cataclysm-DDA#63041]
### Describe the bug

NPC's, when assigned to tasks such as 'do farming work' or 'chop trees in area', will fail the task unless they possess a container large enough to hold the tool, or the player manually equips it to them as their wielded item.

I believe this is because most tools are too large to place in their inventory, thus they fail the 'appropriate tool' check.  When attempting to hand a tool, such as an axe or shovel, to them via 'lets trade', or 'use this item', the NPC complains they do not have the space for the item, because most pack containers cannot fit these tools.
This may also have to do with task failure spam because they CAN find the tool, but they cannot pick it up. 

Expected behavior is that NPC's should stow their current wielded item into their inventory if the tool is too big to put into their bags if the initial pickup fails. Also, NPC's should consider their hands as a container of (near?)infinite size if not occupied.

### Steps to reproduce

1. Strip a Follower of all storage and wielded items.
2. Place a shovel on the ground in a designated Tools zone.
3. Designate a farm plot zone.
4. Ask the Follower to "please do some farming work"

The NPC will then walk to the tools zone, spam the logs about task failures, and resume following the player.

### Expected behavior

NPC's should be able to have basic self inventory management wield tools when their storage capabilities are insufficient.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.963 (22H2)
- Game Version: 28d1538 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mikegogulski** [comment]
There is a class of problem here that extends to things like attempting to hand a follower a tool to use (say, a hoe) and them telling you "no, my current weapon (paring knife) is better".

**Comment by Zourin2** [comment]
The inability to holster/sheath their equipped weapon/tool further extends to not being able to effectively swap between a melee weapon and a ranged one. 
Yeah, this one digs deep into NPC behaviors
