### ISSUE TITLE
"Remove Gravel" construction blueprint is sysiphean (and has a bonus "Make gravel floor" bundled in)

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#63045]
### Describe the bug

I have set up some construction blueprints to remove gravel from the would-be field, and sent NPC to work on them. They complained a bit about not having tools, but otherwise were doing something. From time to time i was getting notifications that "Remove gravel" and "Make gravel floor" tasks were getting complete. The latter one was weird to see, but i chalked it up to a display error or something. The progress was also rather slow, but i thought that's just how NPCs be (i don't have much experience with them really).

Until just now i was passing by and noticed that there is an in-progress construction on a dirt field. And that is a "make gravel floor" construction. Which would explain all of the above issues (slow progress, interminent lack of tools).

Except i don't have any "make gravel floor" blueprints defined. I have no idea why the NPC decided it was a good idea. This is a bug.

### Steps to reproduce

Load save file, examine the `Y` zones, see that the defined zones are all "remove gravel"
Look at the construction in progress nearby, see that it is "Make gravel floor" not "remove gravel"

Wait for an hour. See the gravel floor construction get finished, and a gravel removal one get started.

Wait another hour. See the gravel removal get finished, and gravel construction get started...

This repeats seemingly infinitely...

### Expected behavior

No gravel on my farmland >:(

### Screenshots

![20230109-041557-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/211241240-1d745211-9c1c-4771-8cc0-bbb4e2dd508e.png)
![20230109-041611-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/211241243-b5437833-c6af-4794-a1f7-fb5c82b3b55a.png)
![20230109-041618-cataclysm-tiles](https://user-images.githubusercontent.com/7831163/211241252-59a5c7e9-391d-4a27-b2e4-a9407aa4a085.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: ba42c0a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Save: [Winters.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10370367/Winters.zip)

**Comment by andrei8l** [comment]
/confirmed Unintended consequence of looking for prerequisites in different construction groups. `make_gravel_floor` has neither `pre_terrain` not `pre_special` so the current checks fail to catch this loop:

https://github.com/CleverRaven/Cataclysm-DDA/blob/0d36b186623dac4efe8ac1d20757361615554a03/src/activity_item_handling.cpp#L887-L889

Simplest solution is to add `"pre_flags": "DIGGABLE"` (or something similar) to `make_gravel_floor`.
Full solution needs to correctly consider constructions with only `pre_special`, but I'm not entirely sure those are valid definitions.

**Comment by moxian** [comment]
> looking for prerequisites in different construction groups

Your wording implies that looking in different construction groups is deliberate? What is a use case for this?

**Comment by andrei8l** [comment]
> Your wording implies that looking in different construction groups is deliberate? What is a use case for this?

Quite a few constructions need a pit as a prerequisite. Most fences need a fence post. Pit itself needs a shallow pit. Letting the construction activity look through other groups saves a lot of JSON.
