### ISSUE TITLE
Allow backgrounds/hobbies to grant items and CBMs

### ISSUE THREAD

**Issue by NegInfinity** [CleverRaven/Cataclysm-DDA#63055]
### Is your feature request related to a problem? Please describe.

At the moment it is not possible to mix several scenarios together, for example, you can't have a "Wilderness" start, where your character is "Naked an Afraid" AND a "Bionic Patient". That happens because "Naked and Afraid" and "Bionic Patient" are both professions and you can only have one. 

The reasonable idea in this scenario is to create a custom background mod that could grant you bionic patient CBMs, and this way you'd be able to mix it with other scenario.

However, it turns out that "CBM" entry is simply discarded, as such a background that has "CBMs" entries, simply grant nothing.

### Solution you would like.

Allow Hobbies/Backgrounds to grant both CBMs and items. That would allow user to mix more scenarios in more interesting way. 

### Describe alternatives you have considered.

Another possibility would be to allow user to select their items and bionics freely at the start of the game. 

### Additional context

Normally it would make sense to scenario to define where you are, and for both your profession AND background - what you have and what you can do. This way you could make a background that grants you a multitool or a pocket knife, for example, and mix it with a different starting scenario.

**Comment by ZhilkinSerg** [comment]
Right now you can use debug menu to grant any items to your character. You can also create a mod with whatever additional scenarios, start locations and/or professions you want (e.g. combine wilderness start with new profession that contain features from both naked and afraid and bionic patient).

**Comment by NegInfinity** [comment]
> Right now you can use debug menu to grant any items to your character. You can also create a mod with whatever additional scenarios, start locations and/or professions you want (e.g. combine wilderness start with new profession that contain features from both naked and afraid and bionic patient).

You certainly realize that this is not the same thing, as you'd need to duplicate every scenario for every variations of it, and debugging items you need removes element of surprise regarding the place where you changed. Whereas proposed change would allow you to mix any hobby with any start from any mod. 

Also, given that hobby is probably the same class as profession, this should be a fairly simple modification.

**Comment by ZhilkinSerg** [comment]
No, you don't need to duplicate all scenarios - you only add combinations which you want to experience.

**Comment by kevingranade** [comment]
The reason we don't do this is it becomes difficult to impossible to guarantee that the resulting character can actually carry all their items.

**Comment by NegInfinity** [comment]
> The reason we don't do this is it becomes difficult to impossible to guarantee that the resulting character can actually carry all their items.

Bionics do not require pockets, and the reasonable idea in case of items is to make character drop their items if they can't carry them. Even if they don't have pockets, they can always haul. 

In addition to bionics there's also mutations. For example at the moment Unwilling Mutant is only available through The Experiment scenario and you can't mix it with anything either.
