### ISSUE TITLE
Forage zone

### ISSUE THREAD

**Issue by Relvl** [CleverRaven/Cataclysm-DDA#63059]
### Is your feature request related to a problem? Please describe.

I am always frustrated, when i need to enable auto-forage in the settings and walking here and there in the forest looking something specified like the garlic.

### Solution you would like.

Instead of behaving like this, there should be foraging zone. Exactly the same as the tree cutting zone.

**Comment by PatrikLundell** [comment]
It likely shouldn't be as simple as the tree cutting zone. A tree cutting zone has the objective of cutting trees into logs (possibly with the ultimate objective to clear a path, but that's not a function of the zone itself), while foraging usually has a lot of different objectives. Most of the time you don't want to pick up all the stuff you find (in particular stones, as they are very heavy), but rather react according to what you happen to stumble upon.

**Comment by Relvl** [comment]
The auto-forage function does not collide with the auto-pickup function in any way. In the same way as in the case of auto tree cutting. Let the character run around the bush in the same way and forage it. And then in the same zone, you can make auto-sorting, and pick up what you need manually.
And it's not about simplicity. Now forage makes almost no sense, except when you need to collect a small amount of specific supplies. The player has to either press a lot of keys, or turn on auto-movement, and skip huge territories. This is comparable in convenience to manual felling of trees.
The goal of the zone is just to improve the gaming experience, remove the need to look for every unexplored bush, and run to it, avoiding other obstacles. I assume that this will benefit the project.

**Comment by Zourin2** [comment]
The only issue is the sheer size the zone would have to be. By the time you set up the zone and foraged it, you could have probably just done so anyway. Furthermore, it would be an activity you could only really do once a season or so.

It's a lot easier to simply turn on auto-walk and auto-pickup with appropriate rules, and map-walk through to a random part of the forest, then do the same back.
