### ISSUE TITLE
Crash upon loading game

### ISSUE THREAD

**Issue by Lamb009** [CleverRaven/Cataclysm-DDA#63073]
### Describe the bug

After playing in the same world for a while as one character, eventually a bug came up where that character couldn't load anymore, so I made a new one. Then I played a while using the previous character's base. Now the game won't finish loading into the game world and just closes out at the end of the loading process. I'm on mobile on Android. I've had a lot of issues with this game and really like it, but I'm nearly at my wits end with all the issues. 

### Steps to reproduce

Play with a character a while in a world, then make a new character, try to load in a second character in the same world, then try to load the previous character again, and it should crash. 

### Expected behavior

Play with a character a while in a world, then make a new character, try to load in a second character in the same world, then try to load the previous character again, and it should crash. 

### Versions and configuration

The stable version of the game with magiclysm installed on Android.

**Comment by BrettDong** [comment]
Nothing actionable with this crash report.
