### ISSUE TITLE
Certain practice recipes can't be memorized if you find the books too late into the game

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#63078]
### Describe the bug

I'm sorry, but this issue is really hard to explain. Please see steps to reproduce, it's much easier to do this way.

### Steps to reproduce

1. Make sure your Dodge skill is 3 or higher.
2. Spawn a book "Dance Dance Dance!"
3. This book has a recipe called "Dancing" that allows you to practice your dodge up to 2. Try it out.
4. The recipe won't be memorized. Unfortunately, you will never learn how to dance without a book in your hand, destroying any hope of a proper romantic evening with an NPC.
5. But there is still hope. This recipe can be memorized if:
- You practice Dancing when your base Dodge is 0 or 1. Upon reaching the next level through practice, you will memorize the recipe.
- You can find the recipe in .json and change "skill_limit": 2 to something higher than you have. E.g., if your base dodge is 3, change skill limit to 4. And once again, if you level your dodge through practicing dancing, you will learn the recipe. And also become a cheater.
6. Same thing applies to many other practice books. E.g., you will never memorize Basic Mechanics - Robotics or Basic Mechanics - Engine if you found relevant books by the time your mechanics is already at 10.

### Expected behavior

I expect to be able to learn recipes even if they don't improve my skills anymore, if only for the sake of making those books not yellow. When I come across a yellow book, I take it as a challenge. But in this case, it's a challenge that I will never overcome. It's also quite sad I can't dance without looking at the book all the time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1455 (21H2)
- Game Version: 0808fe7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

Playing with skill rust turned off, in case it's relevant.

**Comment by PatrikLundell** [comment]
Skill rust will allow practice recipes to increase the practical skill back up to the recipe's max training level when a skill has rusted below it. I have no idea whether that would result in the learning of the recipe, though.

And you won't be able to get a romantic dance encounter with an NPC or companion regardless of whether you'll be able to learn the training recipe or not, as training recipes only train skills and proficiencies and there is no "Dancing" proficiency.

**Comment by Zireael07** [comment]
I think the part about romantic dancing was just fluff this person wrote for roleplay

**Comment by dom4op** [comment]
> Skill rust will allow practice recipes to increase the practical skill back up to the recipe's max training level when a skill has rusted below it. I have no idea whether that would result in the learning of the recipe, though.

I know it will. If I find a book with Basic Mechanics - Robotics recipe but I have Mechanics 10, I can just wait until skill rust brings my skill back to zero, and then I can train it to 1 using "Basic Mechanics - Robotics" recipe, so I can put the book on my gray books shelf. I dearly hope that's not intended game design, though.
