### ISSUE TITLE
boat rental placed with incorrect rotation

### ISSUE THREAD

**Issue by Vaskritaya** [CleverRaven/Cataclysm-DDA#63075]
### Describe the bug

A structure known as "boat rental" generated incorrectly, 90 degrees rotated from what it should be. this results in ugly terrain.

### Steps to reproduce

1. find boat rental on a lake
2. maybe get lucky? no idea how generation works, or if this would happen all the time.

### Expected behavior

The coast should be flush with the terrain around it.

### Screenshots

![image](https://user-images.githubusercontent.com/22992007/211812773-d07b0ed0-ff99-46eb-bd61-42f441989149.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: bb53c11 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]

**Comment by LovamKicsiGazsii** [comment]
Same as #62544. The boat rental itself generates properly, it's the lake shore underneath it that rotates incorrectly.
`predecessor_mapgen` doesn't seem to work well with hardcoded OM tiles, or at least terrain with a `NO_ROTATE` flag.

**Comment by Vaskritaya** [comment]
closing this, since its a duplicate
