### ISSUE TITLE
Inconsistent context-sensitive construction menu

### ISSUE THREAD

**Issue by Ishindri** [CleverRaven/Cataclysm-DDA#6308]
As of experimental 9.0-4801-g2256662 on Windows 7, I don't think the context-sensitive construction menu is working properly.  With the filter on, the list still contains constructions I can't make due to 1) insufficient skill, 2) not having the proper tools, or 3) not having the proper materials.  It filtered out a lot of the list, but it also left in a bunch of seemingly random unusable constructions.

Unfiltered:
![before](https://f.cloud.github.com/assets/5974640/2260748/3a36c1aa-9e45-11e3-9462-4b3e2deb749e.PNG)

Filtered:
![after](https://f.cloud.github.com/assets/5974640/2260750/41b65508-9e45-11e3-86c6-0a3d2fce6bf9.PNG)
##

**Comment by Zireael07** [comment]
Is the issue still the case? Is the issue about filtering or about highlighting the legal tiles?

**Comment by kevingranade** [comment]
It's still about filtering, the context thing is a side issue.

**Comment by alkemann** [comment]
It seems to work as described as far as I can tell.

**Comment by Qrox** [comment]
Fixed by #37436?

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
