### ISSUE TITLE
Chunks of Unknown Material won't drop any relic

### ISSUE THREAD

**Issue by Relvl** [CleverRaven/Cataclysm-DDA#63086]
### Describe the bug

1. `EOC_PORTAL_ARTIFACT_WEAK` may spawn monster `mon_archunk_weak` (`portal_storm_effect_on_condition.json`)
2. Monster `mon_archunk_weak` should disappear on death and drop `ps_artifact_weak` item group @ 100% (`nether.json`)
3. `ps_artifact_weak` has a procgen `netherum_tunnels` (group `ps_artifacts`) (`portal_storm_loot.json`, `relic_procgen_data.json`)

This never happens. Killing `chunk of unknown material` won't lead to anithing.
After killing this monster prints a log `The chunk of unknown material disappears.`. 
I've looking some code, and found one place that can produce this: `src/monster.cpp:2619` -> `src/mondeath.cpp:211`.
Looks like OR game counts this monster as hallucination, OR it's lifespan is end.

![image](https://user-images.githubusercontent.com/4003026/212171208-a584220b-2754-42d4-ab57-064e9d70b2a1.png)

### Steps to reproduce

1. Wait for any Portal Storm
2. Wait for chunk of unknown material appears
3. Kill it and get nothing

### Expected behavior

Like as programmed in the files - killing a monster should lead to obtaining a relic.

### Screenshots

![image](https://user-images.githubusercontent.com/4003026/212170338-f175ab52-e149-4c4e-8e59-2d6a4b0e1fec.png)
![image](https://user-images.githubusercontent.com/4003026/212170370-a852f0a2-ddfb-4fb2-af3a-12e3241bdacb.png)
![2023-01-13_00-46-33](https://user-images.githubusercontent.com/4003026/212170397-20a18215-332c-4342-a377-6764d63a1748.png)

### Versions and configuration

OS: win 10
Game: Exp 2023-01-09-0857
Lang: RU/EN
Mods: Evolved XEDRA, Magiclysm, CRIT

**Comment by Maleclypse** [comment]
Artifact spawns on - OS: Windows
    - OS Version: 10.0.22621.1105 (22H2)
- Game Version: 6fa16de [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

**Comment by Maleclypse** [comment]
![chunk drops artifact most recent releas](https://user-images.githubusercontent.com/54345792/212819317-f4a3186b-836b-49ba-afdb-e270c01049e2.png)
Also works on - OS: Windows
    - OS Version: 10.0.22621.1105 (22H2)
- Game Version: d6d5349 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by kishitoku** [comment]
I can confirm that if I kill a wild resonating chunk, it just says "it disappears" and drops nothing every time (tested 10 times in a row by reloading saves). However if I spawn in a chunk via the debug menu, it drops artifacts reliably. This seems to clearly indicate something is not working right in their drop code. Seems like https://github.com/CleverRaven/Cataclysm-DDA/issues/61659 either did not get fixed or is resurfacing.

Temporary workaround: Manually spawn in resonating chunks when you encounter one then kill it to get your reward.

**Comment by kishitoku** [comment]
![Untitled](https://user-images.githubusercontent.com/74622599/224554639-db86d91c-dd8b-4c5f-a795-9efeea41a06a.png)

**Comment by SariusSkelrets** [comment]
Can confirm too: chunks spawned without debug drop nothing when killed

Chunks spawned with debug functions work as intended

- OS: Windows
    - OS Version: 10.0.22621.1555 (22H2)
- Game Version: 227f527 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Should be resolved by #66118
