### ISSUE TITLE
Can't search/filter using "welding" quality in AIM

### ISSUE THREAD

**Issue by Vasil-Dimitrov** [CleverRaven/Cataclysm-DDA#63094]
### Describe the bug

I can't seem to search for "welding" quality using the Advanced Inventory Manager.

### Steps to reproduce

1.  Have an "arc welder" in your inventory
2. Confirm that it has "2 welding" quality
3. Open the AIM and select your inventory
4. Filter using "q:weld"
5. Returned results are empty

### Expected behavior

1.  Have an "arc welder" in your inventory
2. Confirm that it has "2 welding" quality
3. Open the AIM and select your inventory
4. Filter using "q:weld"
5. Arc Welder should be in the results

### Screenshots

Game Version:

Today I finally decided to upgrade to version 2023-01-08-0614 (windows) in hopes it is fixed but I see it is still there.

### Versions and configuration

Version 2023-01-08-0614 (windows)

Mods loaded:

- no_npc_food
- no_fungal_growth
- package_bionic_professions
- blazeindustries
- magiclysm
- alt_map_key
- my_sweet_cataclysm
- mma
- speedydex
- stats_through_kills
- statsThroughSkills
- translate_dialogue

### Additional context

This is not a new issue so it is most likely a very old bug.

**Comment by Brambor** [comment]
Can confirm but with `makeshift arc welder` (I don't have arc welder).

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 7c3a129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Brambor** [comment]
Doesn't work in `V`iew menu too.
