### ISSUE TITLE
"byproduct_group" spawns containers and doubles up

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#63106]
### Is your feature request related to a problem? Please describe.

`"byproduct_group": [ { "item": "chem_ethanol", "charges": [ 200, 250 ] }, { "item": "salt", "charges": [ 100, 150 ] } ]`
no `"charges"` or `"result_mult"` in the recipe, even with `"charges"` or `"result_mult"` set to 5 in recipe still gives double, so pretty sure it has nothing to do with that
![image](https://user-images.githubusercontent.com/115079701/212447035-013808f5-b67d-4147-9ff3-40d317c9d75c.png)
![image](https://user-images.githubusercontent.com/115079701/212447124-049c960b-246b-4fc7-8b8a-1d12bfa863b4.png)
![image](https://user-images.githubusercontent.com/115079701/212447206-06d1fd55-9b7d-4c2d-94d2-5777e7f9b42b.png)

### Solution you would like.

byproduct group not to spawn containers and not double up

**Comment by RenechCDDA** [comment]
What version are you experiencing this on?

**Comment by flybye3o6** [comment]
- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: b3b97e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Please update to the newest experimental, #62148 should prevent doubling of byproduct groups when they are in a container. Spawning them *without* a container requires adjustment to the recipe, but that is now possible. I simply haven't put the PR in yet.

**Comment by flybye3o6** [comment]
ah thank you i missed that
