### ISSUE TITLE
"consumption_effect_on_conditions" triggers linked EOC twice. 

### ISSUE THREAD

**Issue by TGWeaver** [CleverRaven/Cataclysm-DDA#63107]
### Describe the bug

Code: The EOC related command "consumption_effect_on_conditions", which lets you trigger an EOC when consuming something, triggers its related EOC(s) twice. No items in the core game use this function, which is probably why it hasn't been noticed.

EOCs that otherwise work normally will be doubled, so the problem is definitely with this specific form of call function.

### Steps to reproduce

Find an existing EOC, or create a simple one which only prints a message. Then create a simple comestible, like a pill, which is linked to that EOC with the "consumption_effect_on_conditions" function. Here's an example of such a basic test:

[
  {
    "id": "EOCpill",
    "type": "COMESTIBLE",
    "comestible_type": "MED",
	"consumption_effect_on_conditions" : [ "EOC_test_message" ],
    "name": { "str": "EOC pill" },
    "description": "A pill to trigger an EOC when eaten.",
    "weight": "15 g",
    "volume": "5 ml",
    "material": [ "flesh" ],
    "symbol": "!",
    "color": "red"
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_test_message",
    "effect": [
        { "u_message": "An EOC was triggered by eating a pill." }
	]
  }
]

Now spawn the item in during a game and eat it. The message will display with "x2".
Use a more complex EOC and it will immediately become apparent this effect is not limited to message displays; the entire EOC will in fact trigger twice, including all effects and functions. Other methods of triggering EOCs still work normally, it is only this call that seems to be doubled.

For contrast:
1. Start a game
2. Open debug menu and choose Game > Activate EOC
3. Activate "EOC_test_message". The message will appear a single time.

### Expected behavior

Relevant EOCs should only fire once per consumption.

### Screenshots

![double eoc](https://user-images.githubusercontent.com/45330325/212472456-3aea4c14-92ba-48db-a861-84ce0b177d42.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 7c3a129 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by TGWeaver** [comment]
I have just discovered that this only happens when the `comestible_type` is `MED`. If the exact same code is used but it is changed to `FOOD`, the EOC only triggers once. So it's something to do with how meds are consumed.

**Comment by Light-Wave** [comment]
I see the problem now. In `src/consumption.cpp` in function `consume_med` on [line 1723](https://github.com/CleverRaven/Cataclysm-DDA/blob/13153b452a43d9d68abb44d3d8de6a316833f67a/src/consumption.cpp#L1723) it calls `activate_consume_eocs`. However, a few lines earler, it calls `consume_effects` which may also call `activate_consume_eocs`. `consume_med` needs to not call `activate_consume_eocs` if `consume_effects` have already done so, but otherwise still make the call.

One solution would be to replace line 1717 to 1723 with something along the lines of
```
        you.modify_morale( target );
        activate_consume_eocs( you, target );
    } else {
        // Take by mouth
        if ( !you.consume_effects( target ) ) {
            activate_consume_eocs( you, target );
        }
    }
```
I'm not in a good position to compile and test that right now though, so if someone else wanna get this done, that would be appreciated.
