### ISSUE TITLE
Allow survivors to compile research on monsters they encounter

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#63126]
### Is your feature request related to a problem? Please describe.

I enjoy collecting pics of various monsters during my playthroughs. I enjoy reading monster descriptions even more, many of which leave me wondering. Why is zombie hunter crawling on all fours? What was different about this human that the blob affected them in such a way? The lore of DDA is fantastic, and there is much joy in discovering every new bit of it.

However, collecting pics is just a vanity project that some players do because they lack long-term goals.

### Solution you would like.

Let the players conduct research on monsters. It could be done in the following steps:

1. Find a laptop and use it. There will be a new option, "Compile a monster research"

2. You click this option and it will present you a list of options (zombie, zombie child, K-9, etc). The options will only show up if:
- You already killed one of these monsters (checked from your kill list)
- The monster's extended research data is prepared and merged in the game (they can be added as the game develops)

3. Then you will have a promt that asks you to upload:
- High-quality picture from any other device or SD card
- Blood sample results on USB drive
- Pass a check on corresponding weakpoint proficiency (no proficiency - no progress)
- (not sure if possible, but) Autopsy report - basically check if you made a dissection of this monster. Might not be necessary if weakpoint proficiency is possible to check

4. After everything is uploaded, you have completed your research. Now the monster's description is extended. You can browse your collection of pictures to see it, or access from laptop's new research menu to see it. The new description is all the monster's stats and additional scientific desensitized text, expanding the lore and answering some questions. Example text could be something like: "This is a zombie hunter. Evolved from a particularly fast human in good health, most likely military or hunting background. Compared to other zombies, it has enhanced sight, hearing, and speed. Therefore it developed movement habits that involve all four limbs and utilize newfound abilities to full extent. It is however more fragile, *add science mumbo-jumbo*"

Sorry, not a native English speaker here, so I can't write nearly as good as whoever wrote descriptions for monsters in the game.

### Describe alternatives you have considered.

Leave it as it is. Players can look up stats in json or hitchhiker's, and not all questions are meant to be answered.

I guess some people might have an issue with desensitized descriptions, but then again - if you dissected so many corpses you got a weakpoint proficiency, surely you're conducting some sort of scientific undertaking?

### Additional context

Feel free to close if that's against the current policy. Was throwing ideas on Discord, and others suggested to submit this here. Cheers!

**Comment by kevingranade** [comment]
In broad strokes I'm not against having some kind of compilation of knowledge, but the core concept of "scientific research" isn't going to go anywhere. You aren't going to get monster stats, you aren't going to get a development history.

The most it's going to do is merge together observations from several sources, pictures, combat impressions, and a potential autopsy, and possibly do something like track progress on unlocking weakpoint knowledge.
