### ISSUE TITLE
make it possible to pass time while driving a vehicle (meant for power gen)

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#63135]
### Describe the bug

if you remove the wheels, add feet pedals, a seat, and alternators, you can manually generate power. you should be able to pass time while doing this, so you don't have to hold 5 or tab for 10 IRL minutes

### Steps to reproduce

none (see description)

### Expected behavior

ability to pass time, if we're concerned about people accidentally waiting while driving vehicles, one solution is to check if it has enough wheels, if so, prevent the ability to wait for a set amount of time. a nice compromise.

### Versions and configuration

none

**Comment by Golfavel** [comment]
This would also be useful for aircraft and potentially even rail-bound vehicles.
