### ISSUE TITLE
Inserting items into dropped pockets 

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#63130]
### Is your feature request related to a problem? Please describe.

Everytime I try to put some stuffs into a container that is heavy, I always wonder why can't we just put them without picking them up.
Something like inserting your items into a backpack without picking them up or holding them.

### Solution you would like.

A keybind that allows you to insert items in pickup menu.

### Describe alternatives you have considered.

Being able to interact with items in pickup menu.
Something like a pickup menu that functions like inventory.

### Additional context

those 60L tanks are way too heavy :(

**Comment by Vaskritaya** [comment]
i believe this is the intended function of the container view in the AIM, but it is currently completely broken (see https://github.com/CleverRaven/Cataclysm-DDA/pull/62547 )
