### ISSUE TITLE
Duplicated recipes are silently overwritten 

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#63138]
### Describe the bug

When two recipes with the same `result` exist without an `id_suffix` to differentiate them, the game overwrites the first one that if finds with the last one that it finds. In other words: *Load order matters.*

### Steps to reproduce

Debug a character to know all recipes

Look at recipes for zinc powder

See there is only one recipe, despite two being present in the files

https://github.com/CleverRaven/Cataclysm-DDA/blob/d6d5349c992826d17eee88822464e1d83aa6ae70/data/json/recipes/recipe_medsandchemicals.json#L1421-L1434

https://github.com/CleverRaven/Cataclysm-DDA/blob/d6d5349c992826d17eee88822464e1d83aa6ae70/data/json/recipes/other/materials.json#L307-L320

See also: #62743

### Expected behavior

If two of the same recipe are loaded from the same source (e.g. both from DDA) then it should throw an error on loading to indicate there is erroneous data.

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: d6d5349c992826d17eee88822464e1d83aa6ae70
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment]
Ideally any test checking for this would continue to allow mods to use this method of overwriting recipes so that Innawoods and other mods continue to work properly.
