### ISSUE TITLE
Some mild weapon needs hammering 4 instead of 3 to craft 

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#63132]
### Describe the bug

Some mild steel weapons, like mild steel estoc, jian, longsword, rapier, scimitar, and wakizashi for some reason needs hammering 4 to craft instead of hammering 3 every other mild steel weapons have. There's no such tool that provides hammering 4 tool quality and drop hammer is camp only.

### Steps to reproduce

1. Unlock all recipes and go into crafting menu
2. Check the recipe for the weapons mentioned.

### Expected behavior

Hammering 3, instead of hammering 4.

### Screenshots

As shown in the [HHG](https://nornagon.github.io/cdda-guide/#/tool_quality/HAMMER) 
![Screenshot_20230116-223000](https://user-images.githubusercontent.com/78019001/212715595-8d5d54e5-3f4a-4511-8834-407e6881bff0.jpg)

Mild steel estoc
![Screenshot_20230116-224042](https://user-images.githubusercontent.com/78019001/212716732-7051262d-6949-4a87-9eb3-e139917c0a6e.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 583923e [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Misc Sprites [misc_sprite],
    Magiclysm [magiclysm],
    Graffiti [graffiti],
    Misc Sprites: Magiclysm Edition [misc_sprite_magiclysm]
]

**Comment by Maleclypse** [comment]
Drew please let me know if the current behaviour is intended.

**Comment by Drew4484** [comment]
> Drew please let me know if the current behaviour is intended.

Not intended, no. I'll look at the Blame to see if I can pin down how these got changed since tool quality shouldn't be any different except for the higher grades that need additional tools entirely.
