### ISSUE TITLE
player-made downstairs being blocked off by creatures permanently if they dont have space to push past

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#63133]
### Describe the bug

this is my mine, downstairs is where it is. if you push past the creature, while there is no way for them out. it will be "blocked" off permanently. the way i accessed the mine was it was surrounded by walls, with one opening being a door. it is closed in this instance so the creature just blocked it off, which happens to be a muskrat.

### Steps to reproduce

make downstairs, put creature down there, have no way for them to go anywhere else. notice you can't go down anymore.

### Expected behavior

have them swamp places across Z levels, or be teleported to the surface.

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/212723401-c8896795-3e60-40e1-8449-c0868d7f3b1c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: d6d5349 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Megafauna [megafauna]
]

### Additional context

bless your soul
[Babylon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10427626/Babylon.zip)

**Comment by Qrox** [comment]
#59351 made it possible to displace a pet in this situation, but not non-friendly creatures to be consistent with the behavior of horizontal movement. For example, if a muskrat and the player character are both in a one-tile wide corridor, you either have to kill the muskrat or let it flee to get past.

**Comment by evankimori** [comment]
What makes this one more problematic is that even with Admin mode: you have to create an additional stairwell down to get to the layer to kill/remove the Creature to regain access. 

Given that creatures (esp untamed ones mentioned by @Qrox) 'wander' into lower levels at random and get stuck there and (can't?) come back up locks off the lower level.

**Comment by Qrox** [comment]
You can press tab to attack creatures on a different z-level. Of course it would be nice to be able to specify the creature to attack across z-levels like one would on the same z-level, and fixing the creature z-level movement bug would make this issue less problematic, but these are separate issues (the latter being #35665).

**Comment by Devengel** [comment]
you can?! darn it, i wish it would say that along the passage blocked off message

**Comment by evankimori** [comment]
Well there's a change you can add in then @Devengel if it suits the situation! I never knew you could attack another Z level. I've still not used the Peek mechanic that much and wondering if it's possible to Range attack a creature out of cover.
