### ISSUE TITLE
Hebrew in Portal storm message displays incorrectly. 

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#63163]
### Describe the bug

Hebrew is written right-to-left, but the Hebrew in the creepy portal storm message displays left-to-right making it nonsense. It's supposed to say אמת (emet, "truth") and then מת (met, "death"), but it displays as תמא (meaningless but similar to תמ"א [the acronym for an urban renewal program in Israel designed to make old buildings earthquake resistant]) and תמ (a misspelled version of the man's name "Tom"), which undercuts the creepiness. The first time I saw I was so confused trying to figure out what it was even trying to say that it had no scary effect at all. 

It's written correctly in the snippets JSON, so something is getting mixed up when it's displayed. 

### Steps to reproduce

1) Wait during a portal storm 
2) Creepy message that is supposed to be the golem activation/deactivation phrase comes out garbled. 

### Expected behavior

The Hebrew should be reproduced in game the way it is written in the effect_on_condition.json snippets file (right-to-left)

### Screenshots

![image](https://user-images.githubusercontent.com/120433252/213087340-5a61d0d8-14d7-4367-9ed0-f310ca39ef3a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: b8eb345 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Magiclysm Chill Pill [magiclysm_chill_pill],
    New Spells for Magiclysm [new_magi_spells],
    Targeted Mutagens [targetedmutagens],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
They are written the "wrong way" in text but unicode-aware editors flip them around. Our text printing function for tiles isn't aware of this bit of unicode. All right-to-left languages have this issue.

<details>
<summary>proof</summary>

![Screenshot from 2023-01-18 07-36-51](https://user-images.githubusercontent.com/68240139/213092753-63b4fc8b-5245-413d-aacf-beba2aa9712b.png)

in raw text they are in the "wrong" order `מ` then `ת`

**Comment by Standing-Storm** [comment]
Would it be worth writing them backwards in the JSON so they display correctly in-game until the text printing is updated?

**Comment by andrei8l** [comment]
That would break the text in curses builds instead. The only real fix is to implement bidirectional support, which we need for some localization anyway, but this one issue is not a high priority. How do you know those voices from the nether are speaking in (our version of) Hebrew? Or maybe they're talking backwards.

**Comment by Standing-Storm** [comment]
Fair enough!

> Or maybe they're talking backwards.

Even the Nether can't get mixed Hebrew/English text right 😔
