### ISSUE TITLE
Make more recipes create "transitional" items that "self-complete" over time into the desired product

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#63173]
### Is your feature request related to a problem? Please describe.

I like how certain recipes don't directly produce the end product you're trying to obtain, but instead produce "transitional" items that will eventually become the item you want to make, like tanning pelts/hides, soaking dandelions, sourdough starters, and so on. However, I feel like there are far more items that this can/should apply to, especially when it comes to cooking recipes that require a lot of time, when much of that time would reasonably involve things like, for example, sticking a batter-filled pan in the oven to bake, and waiting for that to finish.

Speaking of baking, I know that this would probably be far more intensive than simply changing recipes and adding new items for said recipes to produce, but I also feel like it would be both more realistic and better for time management to have ovens act as a way of cooking transitional items into the desired final product, thus enabling player characters to do something else while they wait.

### Solution you would like.

Add in more transitional items, and change existing recipes to create them (and to require less time, due to a significant part of the crafting process becoming semi-automated).

Also, I know that this would probably be far more intensive than simply adding items/changing recipes, but I also feel like it would be both more realistic and better for time management to have ovens act as a way of cooking transitional items into the desired final product, thus enabling player characters to do something else while they wait. There could even be different oven types, such as a "basic" oven that risks burning whatever's in it if the player character forgets to stop the baking process once the item is finished baking, and a more "advanced" oven that turns itself off when the baking is complete in order to prevent burning the food.

### Describe alternatives you have considered.

Pretending that the automated parts of baking in real life wouldn't apply to baking in CDDA for some unknown reason

**Comment by Brambor** [comment]
See #62616 they even have a bread example.

**Comment by AmarinReyny** [comment]
> See #62616 they even have a bread example.

Ah, okay. Thank you for letting me know! I guess this makes this issue redundant.
