### ISSUE TITLE
The RANDOM_AOE spell flag is recalculated every time the spell target tile changes

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#63180]
### Describe the bug

When targeting a spell with the RANDOM_AOE flag, the AoE is recalculated separately for every possible target tile. This means the optimal strategy is to keep moving the target tile around in a square until the maximum possible AoE is obtained, thus removing any actual randomness. 

(Screenshots below taken in sequence, moving the target one tile over each time)

### Steps to reproduce

1) Create a spell with the RANDOM_AOE flag
2) When targeting, move the targeted location
3) Spell AoE radius is different for every square

### Expected behavior

The affected radius of spells with the RANDOM_AOE flag should probably be hidden from the player , only showing a possible range in the spell description like RANDOM_DAMAGE does. 

### Screenshots

![image](https://user-images.githubusercontent.com/120433252/213353136-bef347f9-9b82-4f68-9f8f-8ae633d5ed21.png)
![image](https://user-images.githubusercontent.com/120433252/213353142-638f427d-cd97-42e1-8f4d-155fecb6ee7e.png)
![image](https://user-images.githubusercontent.com/120433252/213353175-e43278aa-ad44-499d-91e0-85bafa2f4d56.png)
![image](https://user-images.githubusercontent.com/120433252/213353205-7d86e953-4c5b-4201-98cd-52f845fd2eb1.png)
![image](https://user-images.githubusercontent.com/120433252/213353224-0c8a2b05-4ace-44f3-a69b-7b05f8aa6a40.png)
![image](https://user-images.githubusercontent.com/120433252/213353279-c854703e-5434-4354-96d8-5df27a0529f2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 950acde [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter]
]

**Comment by Standing-Storm** [comment]
If this is intended behavior then I have a suggestion instead of a bug report, but maybe MAGIC.md should be updated to indicate RANDOM_AOE works differently than RANDOM_DAMAGE and RANDOM_DURATION

**Comment by GuardianDll** [comment]
I mean, i works exactly like another RANDOM_ flags - it picks one value between min and max, and apply it to spell

**Comment by Standing-Storm** [comment]
The other flags don't tell the player what the value is in advance, though.
