### ISSUE TITLE
Dragging a cart while swapping with friendly animal puts cart under you

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#63185]
### Describe the bug

Position C: Cart P: Player, A: Animal
`CPA`
_Cart to the west of Player who's to the west of Animal._

I think that the Player moves east, and drags the Cart east.
At the same time, player is trying to swap with the Animal, so that the Player would be at A and the Animal would be at P.
This fails, because Cart is already at P, so Animal and the Player don't move.
However the Cart already moved to P, so now both the Player and a Cart are at P.
Cart is IMPASSABLE, so the Player shouldn't be able to occupy the same tile.
The Player stops dragging the Cart.

### Steps to reproduce

Dragging an impassable Cart try to go into a friendly chicken's tile
All happening on a straight line, either west-east or diagonal.
`CPA -> ??P`
_Cart Player Animal; Player tries to go to the Animal's tile while dragging the Cart._

### Expected behavior

A solution where two entities don't occupy the same tile.
Probably: "You cannot swap with the chicken dragging cart like that." possibly adding: "Where would the chicken go?"

Important note: these configurations work correctly right now and the solution shouldn't break them:
```
AP <-> PA
 C      C
```
_Animal west of Player with Cart to the south of either of them. The Player can swap with the Animal, the Cart doesn't move._

### Versions and configuration

Like 2023-01-18 experimental (not @ PC right now).

**Comment by Raikiri** [comment]
Maybe related, but swapping with mechs allows putting them into vehicles. Note that you're explicitly forbidding from entering vehicles while riding a mech. Not sure if it's a bug or a feature.
