### ISSUE TITLE
Unarmed Combat & Bionic Claws Experience gain

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#63186]
### Describe the bug

Bionic claws seems to have been missed in the changeover from weapons to armor.

### Steps to reproduce

Make a bionic monster w/ an unarmed martial art. Pop claws and go fight. Check experience.

### Expected behavior

Unarmed experience should be gained.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12936-g5772febbd59-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Hope [no_hope],
    Brigandine and chainmail [brigandine]
]

**Comment by Maleclypse** [comment]
Can you check this on a release from today?  #62578 was merged three days ago and might have addressed this, might not have if bionic unarmed weapons are treated differently but needs to be checked.

**Comment by intergalacticdata** [comment]
I have those changes in my build. I poked this a bit and it's linked to the fake bionic weapon. 

It should probably get the INTEGRATED tag and some special handling with the existing BIONIC_WEAPON tag to avoid breaking saves.
