### ISSUE TITLE
Enchantments increasing Max HP continually reset to pre-enchanted value

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#63195]
### Describe the bug

1. When applying an enchant that increases HP through the MAX_HP ID value, HP resets to the pre-enchant base every few of in-game minutes. 

### Steps to reproduce

1) Start a world with Magiclysm
2) Debug in the Gaia's Chosen attunement, which uses an enchantment attached to it to increase max HP by 30%.

>   "values": [ { "value": "MAX_HP", "multiply": 0.3 } ], )

3) Debug in the Restoration druid spell and cast it
4) Watch as HP heals up slightly toward the new value but then resets down to pre-enchantment max

### Expected behavior

An enchantment that says it increases Max HP should allow HP to actually reach the new Max HP.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 950acde [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by alp7292** [comment]
also check #61701
