### ISSUE TITLE
Pale Skin prevents installation of alloy plating CBMs

### ISSUE THREAD

**Issue by paulthenerd** [CleverRaven/Cataclysm-DDA#63229]
### Describe the bug

It seems that the mutation 'Pale Skin' prevents the installation of certain CBMs, including alloy plating. I haven't been able to test too many different combinations as in my current world Rubik only has arm alloy plating for sale at the moment, but it does not let me install it unless I debug away pale skin. The message it gives is 'not compatible with patient's body'.

Funnily enough, full on Albino seems to work fine!

### Steps to reproduce

1. Make a player with Pale Skin
2. Go to Rubik and try to install an Arm Alloy Plating CBM

### Expected behavior

I expect that the paleness of my character's skin shouldn't impact the ability to put metal plates under it!

### Screenshots

With Pale Skin...

![image](https://user-images.githubusercontent.com/45760026/213888784-fbfb3de5-d0a1-4666-a4e1-6928ba8e5739.png)
![image](https://user-images.githubusercontent.com/45760026/213888795-fe1c42f5-8a0f-48f2-9d84-cb497fe76932.png)

Without...

![image](https://user-images.githubusercontent.com/45760026/213888805-ffc28cbf-c431-4129-a6ba-b5267e5e846b.png)
![image](https://user-images.githubusercontent.com/45760026/213888813-95917d42-cddb-4740-8615-c5072231836b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: c033542 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
This is because alloys were replacing your skin and pale skin was a mutant-only skin type. #61790 would fix this FWIW.
