### ISSUE TITLE
Suffocated by evil nursebot while installing CBM

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63225]
### Describe the bug

I used an autodoc in a lab to install my first CBM, a trickle charger. Didn't check properly if the nursebot was the friendly kind or the hostile kind, and it turned out to be the hostile kind.

After I got the "Successfully installed Trickle Charger." the nursebot attacked. Afaik they're supposed to pull you onto the autodoc and remove your CBMs, but instead I just suffocated from the nursebot's grab. I'm pretty sure it's supposed to take more than one enemy grabbing you, but in any case the nursebot isn't supposed to kill.

### Steps to reproduce

1. Have no CBMs
2. Successfully use autodoc while hostile nursebot is present

### Expected behavior

Nursebot removes the CBM instead of killing you.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/213875998-574d955b-40f6-47a7-a88f-7b534b1f12de.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 020de8e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sky Island [skyisland]
]

### Additional context

I'm playing the third-part Sky Islands mod by TGWeaver, which is why the log keeps going after I died, but that shouldn't influence anything that happened up until the death itself.

**Comment by NetSysFire** [comment]
I would almost say "works as intended", but grabs suffocating you are a weird change which was implemented by #61060 and #54227. Not all grabs should cause one to suffocate imo.

CC @bombasticSlacks.

**Comment by bombasticSlacks** [comment]
Yeah there are plans to make this more in-depth and simulate actual crushing. For now though I can fix oddities like this by making it so only enemies that can push doors in can suffocate you. I'm on holiday but next week can fix this.
