### ISSUE TITLE
I can't figure out how to close the keybinding menu, also Escape key isn't working

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#63232]
### Describe the bug

There seems to be no way to close the keybinding menu? Escape doesn't do anything, Backspace doesn't do anything.

This feels like a nightmare. Am I missing something obvious?

Speaking of the Escape key, it doesn't do anything on any other menu either? And where did the pause menu go?

I'm so confused.

I just found while typing this that I needed to press Space to close the "Craft something first" pop-up for repeat crafting. Like, what? Specifically the Space key and no other key?

Help

### Steps to reproduce

enter the keybinding menu with ? and proceed to suffer

### Expected behavior

I expect to be able to press **something** to exit the menu. It doesn't have to be Escape, just please

Also I expect to be able to press Backspace to delete what I've typed in the search.

### Versions and configuration

are you kidding me i can't access the main menu because Escape isn't working

i'm on garuda linux, tiles sounds version

**Comment by andrei8l** [comment]
Can you share your config folder please

**Comment by k4gi** [comment]
[I can try](https://file.io/Sa22c8OcOiuE)

i've noticed the escape key, backspace key, are working fine in the terminal version

i guess i may as well include that config too

[here?](https://file.io/pDzZ2zqvN3TV)

**Comment by andrei8l** [comment]
Are you using an IME? Try changing the input mode to keycode (options -> interface -> use key code input mode)

Do you have a very sensitive mouse or some other input hardware? Try disconnecting them. There's a known bug where mouse movement can block keyboard input.

**Comment by k4gi** [comment]
i don't think i'm using an IME, and key code input mode didn't help.

disconnecting my mouse didn't help either.

i tried installing the cataclysm-dda-tiles package from the AUR and it has the same problem.

the enter keys and arrow keys are not working either

curses version is still fine

**Comment by riskaasmara** [comment]
It's a bit late but. In Garuda Linux (and Arch ) if you have fcitx5 running, its most likely the problem (in my case). You can to try kill it before starting Cataclysm. Until the implementation of SDL input to keycode finished. IME really have bad interaction with Cataclysm currently.
