### ISSUE TITLE
Smoked sausage and wasteland sausage spoilage inconsistent

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [CleverRaven/Cataclysm-DDA#63249]
### Is your feature request related to a problem? Please describe.

Smoked sausage is smoked, salted fat and meat.
Wasteland sausage is the exact same thing, but without the fat and a little more wiggle room on the ingredients.
Smoked sausage has a spoilage time of 3 weeks.
Wasteland sausage has a spoilage time of 8 weeks.

This is an inconsistent.

### Solution you would like.

Change the spoilage time of sausages to match. Google tells me hard sausages keep about six weeks outside the fridge, and I'd wager you can probably stretch that just a little, so if we were to keep current values I'd lean towards eight. Otherwise, maybe change both to six?

**Comment by Nebnis** [comment]
6 weeks from google is from heavily industrialized packaged sealed sausages. If you open them and leave them out of fridge, they rot really fast. Summer sausages can be eaten for like 6 days give or take opened and non-refrigerated, but this is really a hard thing to research about if people are talking about quality or just being "safe". I guess lowballing to 2 weeks for some homemade heavy salted sausage can kinda be good enough

**Comment by Nebnis** [comment]
Just because you are tighting some meat inside a plastic bag, it doesn't mean it is oxygen free, or else we wouldn't need  a vacuum seal machine for literally any other product. And even then the natural casings still go bad

**Comment by ProjectileWaterfowl** [comment]
Just think there's not much point to making it last less long than it's components, which can be assumed to be smoked meat and fat.

**Comment by Nebnis** [comment]
Ye it really depends how the sausage was cooked and what ingredients in it. But the gist of it, you need to completely dehydrate the sausage to last a long while,So another recipe for dry sausage would need to be added  where you smoke it again like dehydrated meat
