### ISSUE TITLE
feathers fat deposits and rabbit fur thin skinned and thick skinned armor value doesnt works

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#63254]
### Describe the bug

feathers fat deposits and rabbit fur thin and thick skinned armor value doesnt works

### Steps to reproduce

not needed

### Expected behavior

they should work

### Versions and configuration

latest

### Additional context

legs arms hands and foot is not valid for armor instead it needs to be

"arm_l", "arm_r", "hand_l", "hand_r", "leg_l", "leg_r", "foot_l", "foot_r",

**Comment by anoobindisguise** [comment]
A lot of these should probably be converted into integrated armor.
