### ISSUE TITLE
Unarmed combat skill leveling with unarmed weapons, gauntlets and bare-handed

### ISSUE THREAD

**Issue by MedievalYeetMachine** [CleverRaven/Cataclysm-DDA#63257]
### Describe the bug

Even after #62578, using an unarmed weapon or a gauntlet leads to both unarmed combat and bashing skill rising. Additionaly, bashing skill increases 2-3 times faster than unarmed combat.
When fighting bare-handed, unarmed requieres to kill almost twice the amount of targets to gain the same exp as fighting armed. This affects melee skill too, also gainig only half exp, compared to fighting armed.
The two issues voiced in #61682 are stil present:

1. Fighting unarmed your skills rise much slower, even though you spend more time/perform more hits. This affects both "melee" and "unarmed combat" skills.
2. Wearing unarmed weapons, gloves or boots (if you use style that has techniques using said vector), raises both bashing and unarmed (~3% bashing for 1% unarmed).

### Steps to reproduce

1. Make a character
2. Hit some monsters unarmed
3. Note the rate at wich you gain xp
4. Get a melee weapon, hit some more monsters
5. Notice xp % going up faster
6. Wear gauntlets or unarmed weapon and hit some more
7. Notice bashing rising, and rising faster than unarmed combat

### Expected behavior

1. Unarmed combat rising at the same rate as bashing **or** unarmed rising at the same rate as melee skill **or** some where inbetween 
2. Wearing unarmed weapons rising either only unarmed skill, or rising mainly unarmed skill + a bit of damage type skill

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: b96b791 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Standard combat test suite [standard_combat_test]
]

**Comment by intergalacticdata** [comment]
Confirmed.

I've noted the following:
Even when disabling melee and all damage types, unarmed experience is dramatically slowed. There IS xp gain, but it is not nearly as fast as it should be.
Wearing something as simple as medical gloves on the hands will cause this problem.

**Comment by kevingranade** [comment]
Looking at https://github.com/CleverRaven/Cataclysm-DDA/blob/90241395f8d0832feb2d2a93bb6c465eec8d1e3b/src/melee.cpp#L441
The test for unarmed vs armed might be erroneous, it uses weapon.is_null() instead of checking for unarmed style fighting more generally, resulting in it instead practicing based on whatever kind of weapon damage the wielded item has.
This does not explain the claim that unarmed practices extra slowly when no weapon is wielded.

**Comment by MedievalYeetMachine** [comment]
Would that still be an issue if there is no **wielded** item? When testing i used steel gauntlets and brass knuckles, **wearing** both.

**Comment by intergalacticdata** [comment]
> This does not explain the claim that unarmed practices extra slowly when no weapon is wielded.

What I observed was focus does not drain quickly while the hands are covered. Rather than every hit draining a bit, it would be every 3rd or fourth.

**Comment by intergalacticdata** [comment]
Further observations with all skills disabled except unarmed:
Unarmed at skill level 4, fighting a vine beast.

Focus trending towards: 108
Wearing damaged medical gloves: 37 hits wear required before focus visibly drained
Removing gloves: 40 hits required.

So focus seems to be draining roughly the same.

With gloves, hits to gain 1%: ~50
Without gloves, hits to gain 1%: ~45

So i dunno. Confirmation bias I suppose.

**Comment by intergalacticdata** [comment]
With empty/naked hands:
When turning on training for melee and weapon types, they are training significantly faster across the board. Everything except unarmed is gaining multiple percent while unarmed doesn't visibly rise. 

XP isn't being split by damage / damage type is it? I'm working w/ Aikido vs. an armored mob, so most of the damage will be coming from the weapon, rather than the style.

**Comment by kevingranade** [comment]
Need a melee practice test to nail this down. It looks like wielding a weapon that is *supposed* to count as unarmed, or wielding anything while using a "force unarmed" style will result in leveling melee skills based on the stats of the wielded item.
If there is a similar effect based on wearing items on the hands I don't know what could be causing it, a test should clear that up too.

**Comment by MedievalYeetMachine** [comment]
Okay, did a bit of testing, here's results:
Wearing Impact Knuckles = +10% bashing, no increase in unarmed
Wearing Skewer Knuckles = +1% unarmed, +1% bashing, +4% piercing
Wearing Steel Knuckles = +10% bashing, no increase in unarmed
Wielding Punch Dagger = +20% piecing, no increase in unarmed
Punch Dagger doesnt rise unarmed probably because #62578 got rid of UNARMED_WEAPON flag, but temporary flag is only added to worn items. So while worn weapons are supposed to work fine, held weapons dont have a flag to mark them as unarmed anymore. At least that what i think is happening here.
Wielding a weapon and using "Force unarmed" seems to only increase unarmed skill.
Wierd that wearing bashing inly weapon stoped rising unarmed, or slowed it down significantly. The only difference is focus (testing at ~10, first test was at ~20) and stats (16/16/16/12, first test was 8/8/8/8).
