### ISSUE TITLE
Grid Fridge and Freezer randomly turn off

### ISSUE THREAD

**Issue by EvaShark** [CleverRaven/Cataclysm-DDA#63266]
### Describe the bug

The grid powered fridge and freezer in my survivor camp randomly turn off when I leave and come back to my base. Sometimes it's just one, sometimes it's both. Both my standling lights are unaffected and I have over 80k reserve power so they aren't running out.

Save file attached

### Steps to reproduce

Have a grid fridge and freezer installed
Drive away to do stuff
Return and check if they're on or off.

### Expected behavior

The appliances stay on

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: d2e3eda [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[Burkburnett.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10487515/Burkburnett.zip)

**Comment by andrei8l** [comment]
The fridge and batteries are on different submaps. If you approach from the wrong direction, they don't get loaded at the same time.

#60681 will fix most of these cases, as long as you use wall wiring instead of extension cords.

**Comment by EvaShark** [comment]
Alright, I'll distribute batteries around the 4 corners of the base and see if that mitigates it, thank you!
