### ISSUE TITLE
PSILOCYBIN

### ISSUE THREAD

**Issue by Panicode** [CleverRaven/Cataclysm-DDA#63263]
### Is your feature request related to a problem? Please describe.

THERE IS FUNGAL MONSTERS IN THE GAME. THEREFORE FUNGAL IS AN ADEQUATE THEME FOR GAME, YEAH?
THEREFORE. MUSHROOM ARE FORAGING REAL
WE SHOULD PSILOCYBIN MAGIC MUSHROOM FROM FORAGE

DRUGS

### Solution you would like.

ADD MAGIC PSILOCYBIN MUSHROOMS PLEASE

**Comment by NetSysFire** [comment]
You can already get hallucinogenic mushrooms by foraging. By the way, your usage of the caps lock key does not make this easier to read.
