### ISSUE TITLE
"prevent_weapon_blocking": true also prevent leg and arm block

### ISSUE THREAD

**Issue by Dan1ss1mo** [CleverRaven/Cataclysm-DDA#63271]
### Describe the bug

Martial arts with "prevent_weapon_blocking": true flag make charecter to be unable to block at all, even while unarmed

### Steps to reproduce

1. Set melee and unarmed to 5 or more
2. learn Taekwondo
3. let somthing hit you for a while
4. Observe that you don't block anything

### Expected behavior

You should be able to block with legs and arms

### Versions and configuration

Windows, no mods, d6d5349 experimental 
[Unarmed_test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10493001/Unarmed_test.zip)

### Additional context

removing "prevent_weapon_blocking": true seems to fix the issue

**Comment by Dan1ss1mo** [comment]
Seems like I'm nblo

**Comment by Termineitor244** [comment]
/Confirmed in the most recent version of the game, this needs to be fixed before stable I say...

![imagen](https://user-images.githubusercontent.com/53200489/214466822-fb1fc0c2-f8ee-4852-a500-eadf7f8d02b8.png)
No blocking with Taekwondo active, no weapons wielded.

![imagen](https://user-images.githubusercontent.com/53200489/214466929-4bda14f0-d7b3-4a86-944b-d50d0981ba58.png)
I changed to brawling, the blocks started immediately...  

Please re-open the issue unless you found something else?
