### ISSUE TITLE
Radiation badges aren't supposed to reset. But in the game they do, sorta.

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#63283]
### Describe the bug

Some sidebars (custom, labels, labels narrow, thick and probably others I forgot) have a "Radiation" field. If you put on a radiation badge, this field shows the color of its film strip, which is very convenient.

However, the radiation badge isn't supposed to reset. If it was a brand new green-colored badge and you got a dose of radiation, it will turn yellow and *stay* yellow, unless you get even more radiation and it will go red/black. Bottom line, it will never become green again.

In the game, radiation badge (the item) doesn't reset. But the sidebar color does.

Here is my character's radiation badge - you can see it says "orange" at the bottom.

![image](https://user-images.githubusercontent.com/49651777/214658234-dc299b25-20bf-442e-89f9-e8178666b0f0.png)

The rad exposure happened some time ago, and after a lot of sleep, water and Prussian blue tablets some of that radiation went away. The badge still says "orange", but the sidebar says "blue"

![image](https://user-images.githubusercontent.com/49651777/214658600-d0abe18d-c0f1-4ff1-9932-e86642be1dac.png)

Tested it on several other sidebar layouts - everything that has "Radiation" field works the same. They don't show the badge's film stip color - they show your current radiation level instead.

### Steps to reproduce

1. Put on a radiation badge
2. Bathe in radiation until it changes colour
3. Walk away from the source of radiation and eat a dozen Prussian blue tablets
4. Watch how your sidebar "Radiation" field changes colour to less severe (yellow, then blue, then green) while your badge's colour remains orange/red/black

### Expected behavior

I expect the sidebar Radiation field to show the current colour of the badge

### Versions and configuration

OS: Windows
OS Version: 10.0.22000.1455 (21H2)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/0808fe73d76702995326fd16114e47aa60848a7d [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
No Fungal Growth [no_fungal_growth],
Bionic Slots [cbm_slots]
]

**Comment by cake-pie** [comment]
This is a sidebar UI issue and not a problem with the badges. The sidebar widget was jsonized in #55079 and from [comments there](https://github.com/CleverRaven/Cataclysm-DDA/pull/55079#issuecomment-1029607408) it was known that the implementation had some flaws:

> I can see that it would be complicated trying to get a stored item value like radiation out of an NPC talker condition...
> 
> Having the sidebar show personal radiation (but only while wearing the badge) may be a little unrealistic, but probably more useful to the player.
> 
> I would guess there's a chance of a discrepancy between sidebar badge color and the displayed color on the description of the badge itself

Ping @dseguin for your attention, in case you haven't seen this yet
