### ISSUE TITLE
Game crashes when repairing backpack filled with items. 

### ISSUE THREAD

**Issue by Lucidcake20** [CleverRaven/Cataclysm-DDA#63286]
### Describe the bug

when using a sewing kit in cataclysm dark days ahead, on a backpack bag with xx- durability that is filled with multiple items, the game will crash. I assume this is because the bag breaks when trying to repair the bag and the game doesn’t know how to handle the dropping of the stuff once the bag breaks. I say this because when I unload the bag and try to repair it, and it breaks the game did not crash. I tested this multiple times and found this out. 

### Steps to reproduce

1. Fill a backpack with items
2. Make the backpack XX-durability 
3. put on the backpack
4. Get a rag to repair the bag
5. Use a sewing kit with 200/200 charges 
6. Attempt to repair the bag with Tailoring one.
7. Should say 0%chance of repair 6.6% chance of failure. If not just try to repair the bag anyway.
8. Do not wield the sewing kit , activate the sewing kit from inside the bag while wearing the bag. 

### Expected behavior

I expect the bag to break and the game to crash, due to the fact the game does not know how to handle dropping the items from the bag onto the ground when the backpack breaks also dropping the sewing kit. 

### Versions and configuration

Cataclysm dark days ahead 0F-3
-disable NPC needs [no npc food]
-bionic professions
-C.R.I.T Expansion mod

[ran on Ubuntu linux latest update]

**Comment by Brambor** [comment]
Haha, `Expected behavior` is what you would expect the game to do if it weren't broken, not the result of `Steps to reproduce`.

**Comment by NetSysFire** [comment]
0.F-3 is the latest stable, but it will not receive backports anymore because 0.G is very close. Try again with the experimental.
