### ISSUE TITLE
[Innawoods] Chainmail armors are a vast dead end in the tech tree

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63294]
### Describe the bug

There's hundreds of recipes utilizing chainmail sheets, but no recipe (as far as i can see) to actually make them as they are not autolearned. I feel like innawood's level of technology should allow them. In general I think metal armors should be craftable.

If this is not a bug and it's not considered to be appropriate to craft them in innawoods, then probably the entire tree of armor recipes should be removed rather than selected components at its root.

### Steps to reproduce

1. Get fab 7 in innawoods
2. Observe hundreds of inaccessible recipes in the "armors" category

### Expected behavior

I expect to be able to craft recipes that I unlock instead of discovering that they have missing pieces.

### Versions and configuration

Current exprimental

**Comment by Light-Wave** [comment]
Fair point. It would make sense to make all the chainmail components autolearned, indeed.
