### ISSUE TITLE
Hard Cheese recipe doesn't require or train any of Cheesemaking proficiencies

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#63292]
### Describe the bug

In order to make hard cheese, you need to make curdling milk, which requires Principles of Cheesemaking. Then you put it in a fermenting vat and get curdled milk as a result. Finally, you turn your curdled milk into hard cheese, which _does not require a proficiency_.

I'm not an expert on making cheese, but from what I've seen in documentaries, both processes (curdling milk and making cheese from it) are equally delicate. Seems like an oversight to me.

### Steps to reproduce

1. Look at the recipes. Alternatively, look at the screenshots provided below.
2. Note the proficiencies required.
3. If it's intentional, feel free to close the issue.

### Expected behavior

I expect making hard cheese to require/train Principles of Cheesemaking and probably Cheesemaking Expert too.

### Screenshots

![image](https://user-images.githubusercontent.com/49651777/214805554-6f04e5c9-59d7-4ead-8eb0-916f0becde0a.png)
![image](https://user-images.githubusercontent.com/49651777/214805597-8aea34ab-cc09-4b6e-b044-0ced6a517aa5.png)

### Versions and configuration

OS: Windows
OS Version: 10.0.22000.1455 (21H2)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/0808fe73d76702995326fd16114e47aa60848a7d [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
No Fungal Growth [no_fungal_growth],
Bionic Slots [cbm_slots]
]

**Comment by flybye3o6** [comment]
`"data/json/recipes/recipe_food.json"`
`"cheese_hard"` is in line 3188
slot in 
```
    "proficiencies": [
      { "proficiency": "prof_food_prep" },
      { "proficiency": "prof_cheesemaking_1" },
      { "proficiency": "prof_cheesemaking_2" }
    ],
```
between `"qualities"` and `"tools"` and lint it for good measure would be an easy first time PR
i also think hard cheese and cottage cheese would be good candidates for `"delayed_transform"`

**Comment by Termineitor244** [comment]
/confirmed

The cheesemaking proficiencies are only used in 2 items (the expert one in only one item...), this can be seen here:
https://nornagon.github.io/cdda-guide/#/proficiency/prof_cheesemaking_1

I think this is a general problem with many of the food crafting recipes, but cheese makes a good start to include missing proficiencies!

**Comment by Termineitor244** [comment]
@Maleclypse , this issue was already fixed, could you close it as completed?
