### ISSUE TITLE
Error with a random encounter NPC in the refugee centre.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#63296]
### Describe the bug

Recently I paid a visit to the local refugee centre, and discovered a new survivor NPC (here pictured) standing in the lobby directly next to the window to smoke’s room. Given that this particular NPC was not present the last time I had turned up at the centre, I can only assume that she forms part of the random encounter system. Upon jumping into dialog with the NPC and choosing the “have you seen anything interesting,” option, I am presented with an error stating, “error: out of bounds on randomized directions.”
![Screenshot at 2023-01-26 17-59-20](https://user-images.githubusercontent.com/102766473/214900155-af733476-0f9c-4f90-bb04-483833a6649b.png)

### Steps to reproduce

1. create a Caracter and get to a refugee centre.
2. let some time pass until a new NPC with a, “survivor,” suffix to their name shows up in the lobby. Leave the centre and return later if needed.
3. initiate dialog and select the, “have you seen anything interesting out there,” dialog option.
4. observe the described error.

### Expected behavior

I expected that a usable piece of information would be provided by the NPC, either detailing a location you could go and check out or some random info.

### Screenshots

![Screenshot at 2023-01-26 18-10-11](https://user-images.githubusercontent.com/102766473/214904131-2846337c-1e78-4e89-9aaa-5246d84da664.png)

### Versions and configuration

OS: Ubuntu 18.04
- Game Version: 9bede42
- Graphics version: Terminal
- Ingame language: english
- Mods loaded: dda", no_npc_food, no_fungal_growth, personal_portal_storms, Arcana, xedra_evolved, alt_map_key, useful_helicopters, Tamable_Wildlife, speedydex, No_Rail_Stations, MMA, Tankmod_Revived, MA

**Comment by PatrikLundell** [comment]
My guess is that the game tried to generate a location, failed, and then tried to refer to that non existent location rather than falling back to saying that nothing of interest has been seen.

**Comment by DoctorBoomstick** [comment]
Likely, I’d also wager that the inclusion of the Ma mod also contributes somewhat. I’ve heard that it can make city and special location spawns generate farther than they normally would in the base game, so perhaps that has something to do with this.
