### ISSUE TITLE
Sublimbs broken after resurrection

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#63314]
### Describe the bug

After resurrected from death with the portal storm's resurrection reward, all of the sublimbs like eyes, hands, feet got broken.

### Steps to reproduce

1. Give yourself the "Marked" trait
2. Get yourself killed.
3. Get resurrected
4. Check the medical menu 

### Expected behavior

Not breaking my hand, feet, eyes, and mouth.

### Screenshots

![Screenshot_20230128-032054](https://user-images.githubusercontent.com/78019001/215190583-b0b79ea5-6371-4929-a288-e5a1edad126e.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 16f2625 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Misc Sprites [misc_sprite],
    Magiclysm [magiclysm],
    Graffiti [graffiti],
    Misc Sprites: Magiclysm Edition [misc_sprite_magiclysm]
]

**Comment by TGWeaver** [comment]
This seems to be a direct result of #63259 . EOC effects no longer change sub-limb HP, but death still does, so the limbs are broken but don't recover along with the other parts.

**Comment by GuardianDll** [comment]
![image](https://user-images.githubusercontent.com/67688115/215195565-21ca427f-c234-4306-8c1a-1edbb605ba22.png)

@Ramza13 I think something went wrong :derpy:

**Comment by Ramza13** [comment]
Doh, I tested it with a custom EOC as opposed to death.  Easy enough to fix I'll do it later today.
