### ISSUE TITLE
Bare Bones Basecamp description too long

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#63319]
### Describe the bug

The description for "Faction Base Bare Bones Basecamp" is too stonking long.

https://github.com/CleverRaven/Cataclysm-DDA/blob/4b6270c53d386cc07cfab78984d3461e796da3a8/data/json/recipes/basecamps/recipe_groups.json#L100-L104

It doesn't fit properly on the screen when choosing what kind of base to set up, so some of the information that it is trying to convey gets lost.

![stokinglongdesc](https://user-images.githubusercontent.com/28502722/215249110-35486883-8360-4d18-a78f-c91fa719283d.png)

### Steps to reproduce

roll a new basic evacuee character in a new world on default settings
make the starting evac shelter NPC into a follower (roll one with a fetch quest and debug spawn whatever they want)
Talk to them: `f` for the tutorial, `d` about faction camps, and `c` is to build a camp here
Behold longtext

### Expected behavior

**Please do not simply shorten the description.**  It is important to communicate to the player that this kind of camp functions different from the others. There proper solution is to have a better way to present this information.

One possibility is to have `name` and `description` be separate properties of each possible camp type, and change the UI so that as you scroll through the names of possible camps at the location, the corresponding `description` is displayed below or to one side.

Info for other camp types can be taken from `TALK_FACTION_CAMP.json`

### Versions and configuration

4b6270c

**Comment by TheShadowFerret** [comment]
>Please do not simply shorten the description. It is important to communicate to the player that this kind of camp functions different from the others.

*Shortens it without losing information*

"Faction Base Bare Bones Basecamp.  Manually add bulletin board to use.  No construction.  Can be constructed anywhere.  Access to crafting recipes using Supplies zone covered furniture and appliances."

->

"Barebones Faction Basecamp. Manually add bulletin board to use. No construction. Constructable anywhere. Access to crafting using Supplies zone covered furniture & appliances."

![image](https://user-images.githubusercontent.com/99621099/215298198-2e22e5c6-29db-4a2b-8968-6fbb311c52e4.png)

**Comment by cake-pie** [comment]
Sure you can do a bit of rewording, but it's not a complete solution -- what about smaller screens or window sizes? There is a fundamental problem here of UI/presentation that is not suited for conveying that amount of information.
