### ISSUE TITLE
Ideas for future PRs 1: Survivor Armor balance/consistency

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#63332]
### Is your feature request related to a problem? Please describe.

**_### Warning:_** _These are the ramblings of my free mind while spacing out at work, somewhat edited and proof-cheeked for consistency, read at your own discretion, I would like to make the changes proposed in this issue, but decided to share them here in case someone has a better idea or wants to implement them faster than I (Since I don't actually have much free time lately)._

Improve the encumbrance (by items inside pockets) of several survivor items, like the survivor harness (egregious encumbrance for storing a fire arm in contrast with the back holster), the survivor light body armor (A mere 2L of storage gives 4 extra encumbrance...), the survivor body armor should be renamed to something like survivor vest, since it only covers the torso, and it should become just an improved version of a Kevlar vest, the same way the mercenary coat is an improved version of a ballistic vest.
The survivor cargo pants give a little too high encumbrance too, especially when in contrast with the standard cargo pants, the survivor version is just marginally better in storing things when taking only encumbrance by volume into account, they need to be an actual improvement fro the normal cargo pants (They were changed when the mercenary pants were added, but the survivor pants were left alone and they are now severely lacking in encumbrance per volume stored).

The survivor boots have several problems too, the material thickness is all over the place, which makes the protection values of the light and normal survivor boots be very close (in fact, the light survivor boots are almost as good at protecting your feet than the normal ones, which makes no sense), the same problem presents itself when comparing the survivor cargo pants.

The recipe for the survivor cargo pants needs to be altered, too, to include leather (Or changed to the new standards set by the mercenary armor and kevlar jumpsuits, with a base layer of Lycra/synthetic fabric, and the material of the (standard) survivor cargo pants altered since right now it's only a slightly thicker light survivor cargo pants (As per the current improvement stages of survivor armor).

The survivor gloves (light and normal) are... Weird, too, they do have a good difference in armor values, but the light one seems too... Useless, it should be a little thicker and/or have less encumbrance. The survivor gloves in general should have way less encumbrance, several other gloves have better stats than these ones, and the survivor ones can only be crafted or found by a serious stroke of luck with a veteran survivor zombie, so they need a good audit or something.

The mercenary coat and pants are too warm, they have the same thickness as the US ballistic vests, but have more than double the warmth, even though they are very similar items (In fact, the mercenary coat is just a ballistic vest with an expansion for the arms and some small improvements, as per the recipe), and the mercenary armor is very high level in crafting, so I would expect at least a similar level of warmth if the overall thickness is maintained.

The Kevlar jumpsuits are very underwhelming too, they need to be a little more robust, they feel pretty subpar as it is, <s>maybe having a third, dispersed layer of kevlar panels would help to make it a more attractive armor</s> (Not possible because of the mandatory thickness of kevlar panels, in fact, they seemed to be originally made of kevlar panels but where changed because of its thickness).  The light kevlar jumpsuits could also just increase the thickness of the second layer of kevlar, the kevlar vest, another normal layer clothing, has a thickness of 3.3 mm kevlar (and it is realistic, since similar vests in real life have a total thickness of [4mm](https://www.safeguardarmor.com/pages/protection-levels). the light kevlar jumpsuit in particular could have a 0.5 / 1.0mm increase, either as an expansion of the present layers, or as a third layer that only protects the most important/rigid parts of the body (less coverage). As an additional note, these armors should make use of the "cover_vitals" field.

Improving survivor dusters and trench coats by making them less encumbering and more protective in vital areas, since they suck at everything and are a horrible waste of time for most if not all survivors with enough resources/time/skills for them, <s>maybe implementing the ablative system for them</s> (Ablative system rejected since the mercenary coat already makes use of it...)
A maybe better idea is to improve these 2 items by transforming them into special cargo coats/dusters, with straps, a hidden holster and a hidden sheath for a knife, basically expanding the idea behind the survivor belts and turning it into the new survivor coats/dusters, that's the best idea I can think of to improve these items.

### Solution you would like.

- Wide use of the new (not so new now) "volume_encumber_modifier" entry for survivor pockets, making them somewhat better than similar items that already make use of it, since they are, well, high level, specialized survival pockets.
- Rebranding of the survivor body armor into a survivor vest, which would basically be a Kevlar vest plus.
- Thickness/base encumbrance balance audit of at least the survivor boots, gloves and survivor cargo pants.
- Substantial reduction of warmth provided by the mercenary coat/pants in accordance with the US ballistic vest that they are based around of.
- Better protection values for the light kevlar jumpsuit, it lost a lot of appeal after its materials were changed from kevlar panels to normal kevlar sheets.
- A salvation for the survivor dusters/trenchcoats, maybe in the form of turning them into storage coats, or into easier to make (in materials, skills, etc.) mercenary coats, or something. 
- Use of the "cover_vitals" field in survivor/kevlar jumpsuits armor (mercenary armor already makes use of it)
- Use of a new base layer of Lycra/synthetic fabric for most (if not all) survivor armor, in accordance with the kevlar jumpsuits.

### Describe alternatives you have considered.

To let these iconic armors die into nothingness.

### Additional context

As I said in the beginning, I would like to personally make the changes proposed here, but I would really appreciate anyone else willing to tackle this issue, survivor armor is in dire need of a change to survive in some form (Or to at least survive in a decent shape until its obsolesce). 

Also, sorry for my ramblings to anyone brave enough to read this far.

**Comment by Drew4484** [comment]
There's going to be a very useful application of 'survivor' gear shortly after Stable when the new limb systems are implemented. Once we suddenly have a variety of possible limbs that won't fit it salvaged clothing, the survivor gear seems like the best place to start with making custom designs. 

I would sit on this idea for now, maybe write up some additional details and a plan for a PR so we can add it to the ongoing list of armor projects.

**Comment by Termineitor244** [comment]
> There's going to be a very useful application of 'survivor' gear shortly after Stable when the new limb systems are implemented. Once we suddenly have a variety of possible limbs that won't fit it salvaged clothing, the survivor gear seems like the best place to start with making custom designs. 
> 
> I would sit on this idea for now, maybe write up some additional details and a plan for a PR so we can add it to the ongoing list of armor projects. 

Oh, the new limb system, I have been waiting for it for a long time now. Survivor armor definitely would benefit from its implementation, I would refrain from any big changes, then, but I still would like to make some small changes to the encumbrance and thickness values of the most unfun variants, to be more useful until more comprehensive changes can be made.

Thanks for the info!!

**Comment by ProjectileWaterfowl** [comment]
The encumbrance for the firearm in the survivor harness is because it's slung in front, which gets in the way a LOT but is readily available. Compare with the single point sling and load bearing vest with sling. The survivor cargo pants (while having less storage and encumbering more empty) actually do scale better as they fill while also packing in some Kevlar layers for good protection. Normal cargo pants are 1 encumbrance when empty, 9 when full, with 7.16L of space. Survivor cargo pants are 5 encumbrance when empty, 10 when full, with 6.70L of space. That's a lot better encumbrance/liter!

**Comment by Termineitor244** [comment]
> The encumbrance for the firearm in the survivor harness is because it's slung in front, which gets in the way a LOT but is readily available. Compare with the single point sling and load bearing vest with sling.

Huh, I hadn't really considered it like that, it is true that you can easily access the firearm with the survivor harness, justifying its current maximum encumbrance, I still think it would be good to see a few points of maximum encumbrance reduced from it, but that's just more of a personal preference.

> The survivor cargo pants (while having less storage and encumbering more empty) actually do scale better as they fill while also packing in some Kevlar layers for good protection. Normal cargo pants are 1 encumbrance when empty, 9 when full, with 7.16L of space. Survivor cargo pants are 5 encumbrance when empty, 10 when full, with 6.70L of space. That's a lot better encumbrance/liter!

Very true! I should have confused the numbers given the haste with which I was writing this section, still, the improvement is not really much, and I don't think the pants would stay much in its current iteration given the existence of the mercenary pants for protection, they could repurpose themselves as a lesser armored but great storage per encumbrance medium, since the role of armor pants is already filled by mercenary pants and the legs portion of Kevlar jumpsuits, a topic for discussion definitely.

> I also think the Kevlar jumpsuits are fine. The light Kevlar jumpsuit sacrifices overall protection for better protection for the encumbrance, which works fine. It's made of the same stuff as the regular one, just less, so it's a pretty straightforward trade. The light and normal Kevlar jumpsuits both basically serve the role as a flexible base layer of armor to go under your bulkier, more rigid gear, so IMO they're already perfect for what they do.

I don't have much of a problem with the normal Kevlar jumpsuits, but the light one seem really underwhelming in contrast with a Kevlar vest, which was what my character had in hand for torso, normal layer armor, I think they need a little more thickness, or lesser warmth, for it to be really worth it in contrast with other options (specially with the normal Kevlar jumpsuit, the only real drawback is the warmth and greater resources needed, since the encumbrance increases only by a little).


> I agree on some of the other stuff, especially the gloves, which I've never had a good reason to use.

Yeah, the gloves suck really hard, they are the first thing I'm changing if I get around to implement any of this, they are useless.

Thanks for the opinions!
