### ISSUE TITLE
Processor boards dropped by Milspec Searchlights don't group with other ones or themselves

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#63333]
### Describe the bug

Processor boards dropped by Milspec Searchlights don't group together with processor boards obtained through other methods or other processor boards dropped by searchlights, creating bloated item lists that must be pagedowned through if the player accumulates many processor boards.

### Steps to reproduce

1. Debug spawn a bunch of processor boards.
2. Debug spawn a bunch of milspec searchlights.
3. Kill the milspec searchlights.
4. Lump the milspec searchlight processor boards in with the "normal" processor boards.
5. Observe them forming dozens of separate piles: 1 single pile for all the "normal" processor boards, and dozens of individual 1-2 piles of processor boards.

### Expected behavior

Processor boards from milspec searchlights should group together with other processor boards and themselves.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1455 (21H2)
- Game Version: f097346 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
/confirmed The variables used by the searchlight code aren't cleared on death

![Screenshot from 2023-01-29 07-03-48](https://user-images.githubusercontent.com/68240139/215306090-2552548f-4c20-4061-ba5a-2803f2ae99af.png)

https://github.com/CleverRaven/Cataclysm-DDA/blob/b483a8854efb0e9589f26b5415bf431d7386c133/src/monattack.cpp#L3841-L3867
