### ISSUE TITLE
60L tank of water not boiling on a brazier fire

### ISSUE THREAD

**Issue by gneiss562** [CleverRaven/Cataclysm-DDA#63343]
### Describe the bug

60L tank of non-clean water sat on lit brazier for several days with a constant well-fueled fire and did not become clean or even get hot. Reproduced on multiple clean default setting saves in multiple worlds. 

### Steps to reproduce

spawn and deploy brazier, spawn 60L tank and fill with water. spawn wood, put wood in brazier space as normal and light a fire. mark firewood source and stock with wood. put the 60L tank of non-clean water on the fire and wait indefinitely for it to never be (hot) or (clean).

### Expected behavior

the water in the tank should get (hot) and then presumably boil and become (clean) water when left in a fire. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 690e38e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I noticed the fire never gave a message like "this fire is well fueled and will burn for almost a day" or anything like that, as it had done previously, even when fueled with dozens of planks or lots of logs. it always gives "without fuel this fire will go out in 9 to 10 hours" or even less time. I am running the latest experimental as of 1/29/23. this system was working as intended a few days ago when I last played.

**Comment by NetSysFire** [comment]
Without testing, my guess is that braziers are somehow hardcoded and thus treated differently.

**Comment by Brambor** [comment]
> Without testing, my guess is that braziers are somehow hardcoded and thus treated differently.

I am obtaining clean water by boiling water on a brazier. It worked ~1 month ago. I didn't try recently.

**Comment by Profit0004** [comment]
It is possible that the tank being so large is not able to get heat fast enough from the brazier to make it hot and boil.   This would be more likely if the surrounding temperature is lower than normal like underground or during the winter.   I also have had problems getting 200L tanks of water to boil to clean on some heat sources but if you have a wood stove you can almost always do up to 200L.  
* Just looked at how the fire works quickly and the raws that make the different flame containing furniture.  I am pretty sure all fire types are handled the same, the important thing I think is how much fuel is in the device burning which is where the actual limits come in.
