### ISSUE TITLE
Greatbow volume is too big for bow sling

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#63356]
### Describe the bug

Can't put a wooden greatbow which has 6,25 Volume into a bow sling(even though it says you can put in that container in the description). The max capacity for the bow sling is 5. If nobody else do it, may i increase the volume for the bow sling to 7 or something to account for other future bows?

### Steps to reproduce

Make a bow sling
Make a wooden greatbow
Can't put inside

### Expected behavior

I assume you supposed to

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 27d6b46 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots]
]

**Comment by Creationary** [comment]
Are greatbows actually a real thing? I'm pretty sure they only occur in fantasy settings - where they're often over 2 meters in length while strung.

Perhaps there isn't an apropos place for them in vanilla cdda?

**Comment by DSeyka** [comment]
>Are greatbows actually a real thing?

They don't appear in loot, they can only be crafted, and are supposed to be an archery option for mutated characters.

**Comment by Nebnis** [comment]
> > Are greatbows actually a real thing?
> 
> They don't appear in loot, they can only be crafted, and are supposed to be an archery option for mutated characters.

They actually can't be worn by mutants and i figured adding an extra volume for bow sling for this would help them out

**Comment by DSeyka** [comment]
I don't disagree, I was merely pointing out why it's a thing in the game when it's not a thing IRL. :)

**Comment by Creationary** [comment]
Then there should maybe be a special sling for them, instead of making adjustments to an existing item that might cause unforseen consequences.
