### ISSUE TITLE
Solar Panels Providing Power When Underground

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#63376]
### Describe the bug

I've modified and dug out around the basement of a hunting lodge to create a space to park my mobile base during the winter.  One big concern I had when planning for this strategy was power generation, given that the vehicle wouldn't be getting any power from its solar panels while underground.  Having found a few CASRGs to provide constant power while underground, I went ahead and carved out the base.

I notice now that, after moving my vehicle underground, its solar panels are still generating power.  I would expect that the power reported in the 'Examine vehicle' screen would remain constantly at -580W (the vehicle has 4x120W freezers and 1x100W refrigerator) throughout the day/night cycle.  Additionally, given that I have 5 CASRGs connected to the vehicle, I would expect examining any one of them would constantly show a 'Grid battery power flow' of 75W (5x131W - 580W).

- At 11:40am (plenty of sun), grid power flow is shown as +684W and vehicle power is shown as +29W:
  - ![image](https://user-images.githubusercontent.com/109529281/215840120-cae7fc99-f229-4113-9c47-f8647c2b97bb.png)
  - ![image](https://user-images.githubusercontent.com/109529281/215840356-82e69db9-458b-4d37-ac3b-833d9d7b1f52.png)
- At 8:35pm (no sun), grid power flow is shown as +75W and vehicle power is shown as -580W:
  - ![image](https://user-images.githubusercontent.com/109529281/215840479-df40e0c7-4cc8-4c8e-bb2c-1f3bd9640d16.png)
  - ![image](https://user-images.githubusercontent.com/109529281/215840890-bd0a1e01-1531-4c93-9d8b-3293141e3826.png)

In case it's relevant, I will add that I did use the map editor to change terrain tiles at surface level (level 0) when digging out terrain in the hunting lodge basement (level -1) caused the ceiling terrain to fall and open air to be exposed.  Maybe it's possible that doing this made there appear visually like the basement was completely covered when looking at it on level 0, but didn't correctly set flags for the map editor-altered terrain to correctly obscure sunlight.

For reference, here's what the level 0 terrain looks like now:
![image](https://user-images.githubusercontent.com/109529281/215841823-0f43030f-8eca-4a43-94ff-a50483a0ad65.png)

[Side note -- let me know if a separate report should be created for this]  One of 'Grid battery power flow' or 'Appliance power consumption' seems to be wrong for CASRGs, since the five individual CASRGs each show 'Appliance power consumption' of 130W yet the five of them linked together reports total output of 655W (5x131W).  Is this maybe an effect of having to calculate 'Reactor power output' separately from 'Appliance power consumption'?
![image](https://user-images.githubusercontent.com/109529281/215839866-b330f052-fb98-473e-92c8-6a263263ddfe.png)

### Steps to reproduce

I haven't tried reproducing this outside of my current game's state.  I suppose it could be tested in a new, fresh game via debug menu by teleporting to level -1, using map editor to clear an area of tiles, spawn in a vehicle with solar panels, and then check the vehicle's power flow at various times/levels of sunlight.

I also haven't tested if solar panels obscured via other method (i.e., pulling into a level 0 garage with a roof or other obscuring tiles over it) still produce power.

### Expected behavior

Solar panels should produce no power when obscuring terrain is present above them.
(I'm not sure how complicated the math here gets with sun angle and z-levels.  For example, what if a vehicle on level 0 is not obscured by any level 1 terrain, but then there is obscuring terrain at level 2?  Seems like there wouldn't be light more much of the day, but some might hit when the sun is at a low enough angle for incident light to pass under the obscuring level 2 terrain and through the open level 1 terrain.)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 7921045 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by ChromePoptart** [comment]
I believe I figured out the cause for this unexpected behavior.  After poking around using the map editor, I realized that the "floor" terrain tiles (what was left after I used "Deconstruct Simple Furniture" to remove carpet from the original hunting lodge basement tiles) have the "roof" flag set to "yes", whereas the "dirt" terrain tiles (left after digging out walls and solid earth around the basement) instead have the "roof" flag set to "no".  I used the map editor to change all of the "dirt" tiles under the vehicle to "floor", and the power generated by the solar panels immediately dropped to zero.

So, the issue here seems to be that determining whether or not a tile has a roof over it is determined by the terrain on the tile itself and not based on what terrain is on the same tile but one z-level higher.  I'm sure there are design considerations for why the system was implemented in this way.

![image](https://user-images.githubusercontent.com/109529281/216361292-e1122162-d28a-456d-8fe8-0b738658346e.png)
![image](https://user-images.githubusercontent.com/109529281/216361339-0c5efe76-a546-42ae-9748-e7998c586207.png)

**Comment by alp7292** [comment]
how roofs works is really weird we should have actual roofs

**Comment by andrei8l** [comment]
/confirmed the relevant code only checks for the `INDOORS` flag and your vehicle is over some `t_dirt` tiles which don't have the flag

https://github.com/CleverRaven/Cataclysm-DDA/blob/908472cac4573948cba92f5f72e13b2a8bc01212/src/vehicle.cpp#L7410-L7411

**Comment by Night-Pryanik** [comment]
Apparently it doesn't matter what type of terrain is above the underground tile to determine whether it's indoor or outdoor.

I found a cavern. In its underground part I spawned a solar car.
![изображение](https://github.com/user-attachments/assets/daa97e93-9e8f-4eee-b2da-5a5cb46b12c9)

Here's the ground part of the cavern, with oak tree standing right above the solar car.
![изображение](https://github.com/user-attachments/assets/15f43226-fb56-4490-96b6-cdf18e9f13b0)

The solar panel part, which has the `dirt` terrain right above it, is considered as being "inside".
![изображение](https://github.com/user-attachments/assets/4b8894df-3bd5-4094-9e39-36f23e713a9c)

As a result, solar car doesn't generate any power while being underground
![изображение](https://github.com/user-attachments/assets/a7d16ea3-9e62-4e28-ae52-cc2b8d33e48d)

For comparison, solar car on ground level do generate power
![изображение](https://github.com/user-attachments/assets/a853b2a3-2bbf-44b8-889f-87bfcdf7d39c)

Using map editor might lead to some weird behavior, but I think that this issue ain't happening naturally, so I'm closing it until reconfirmed.
