### ISSUE TITLE
Power armor generator frame does not work as UPS

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63372]
### Describe the bug

As far as I understand from the item's description, power armor generator frame is supposed to power UPS items. It also has IS_UPS flag set, but for some reason it does not actually power UPS items. It does power the armor, but it does not power anything else.

### Steps to reproduce

1. Create a character with power armor generator
2. Fuel it with diesel
3. Attempt to use any item with a UPS mod. For example, a firearm repair kit with a ups mod attached.
4. Observe that the item does not work.

### Expected behavior

I expect the power armor generator frame to act as a UPS

### Versions and configuration

Current experimental

### Additional context

If the generator is not supposed to act as a general-purpose UPS, that's in my opinion a little weird but fine too, however it's probably worth clarifying that in the item description, because you'd expect this huge generator thing you're carrying on your back should be able to power your flashlight.

**Comment by andrei8l** [comment]
Can't reproduce

[output.webm](https://user-images.githubusercontent.com/68240139/215724599-eb7941ff-3de7-4671-a491-c83b2025d071.webm)

**Comment by Raikiri** [comment]
@andrei8l wait wait wait. How come your generator frame is shown as if it's _inside_ of the power armor? My setup is like this:
I wear my "field combat exoskeleton", my "power_armor_generator", and "power_armor_frame", items are named like this and they're all worn on the body.

The generator frame https://nornagon.github.io/cdda-guide/#/item/power_armor_generator does mention ICE in its description, but it's literally named "power armor generator" and is shown as an independently worn item, when yours is shown somehow nested?

I can't find either "exosuit frame" or "exosuit gasoline ICE power supply" on nornagon: https://nornagon.github.io/cdda-guide/#/search/exosuit%20frame

So I'm either wearing my items dramatically wrong or we're looking at different items or different version of CDDA? I'm running the current experimental.

**Comment by andrei8l** [comment]
You didn't respect the template so I made some guesses. Either way, it works fine with the vanilla exoskeleton too

[output.webm](https://user-images.githubusercontent.com/68240139/215940551-7a021b23-fccd-46f3-803f-7803674820be.webm)

**Comment by Raikiri** [comment]
I primarily created this issue because I assumed the UPS part of the generator was completely disabled/not intended to work. If it's supposed to work, then I'll come up with a more specific example of how mine failed.

**Comment by Raikiri** [comment]
After running some additional tests, I realized that my problem seems to do with deconstruction tasks that require charges. For example [assuming you have a power armor generator equipped already]:
1) Spawn a geiger counter
2) Spawn a soldering iron with a battery
3) Observe that the geiger counter can be deconstructed (which would use charges from its battery)
4) Attach a UPS mod to the soldering iron instead
5) Attempt deconstruction again, see that it says it requires 14 soldering iron charges
6) If you get a UPS now, then deconstruction will actually detect its charges and will allow to use it

So this problem seems to be specifically related to the power armor generator and not other UPS's

**Comment by andrei8l** [comment]
/confirmed `inventory::charges_of()` specifically checks for the UPS tool, unlike other visitable implementations

<details>
<summary>Potential solution</summary>

```diff
diff --git a/src/visitable.cpp b/src/visitable.cpp
index ca9a3a95e3..edc54e14ab 100644
--- a/src/visitable.cpp
+++ b/src/visitable.cpp
@@ -15,6 +15,7 @@
 #include "character.h"
 #include "colony.h"
 #include "debug.h"
+#include "flag.h"
 #include "inventory.h"
 #include "item.h"
 #include "item_contents.h"
@@ -804,7 +805,9 @@ static int charges_of_internal( const T &self, const M &main, const itype_id &id
     bool found_tool_with_UPS = false;
     bool found_bionic_tool = false;
     self.visit_items( [&]( const item * e, item * ) {
-        if( filter( *e ) && ( id == e->typeId() || ( in_tools && id == e->ammo_current() ) ) &&
+        if( filter( *e ) &&
+            ( id == e->typeId() || ( in_tools && id == e->ammo_current() ) ||
+              ( id == itype_UPS_off && e->has_flag( flag_IS_UPS ) ) ) &&
             !e->is_broken() ) {
             if( id != itype_UPS_off ) {
                 if( e->count_by_charges() ) {
@@ -817,7 +820,7 @@ static int charges_of_internal( const T &self, const M &main, const itype_id &id
                 } else if( e->has_flag( STATIC( flag_id( "USES_BIONIC_POWER" ) ) ) ) {
                     found_bionic_tool = true;
                 }
-            } else if( id == itype_UPS_off && e->has_flag( STATIC( flag_id( "IS_UPS" ) ) ) ) {
+            } else if( id == itype_UPS_off && e->has_flag( flag_IS_UPS ) ) {
                 qty = sum_no_wrap( qty, e->ammo_remaining() );
             }
         }
@@ -913,7 +916,10 @@ int inventory::charges_of( const itype_id &what, int limit,
     }
 
     const itype_bin &binned = get_binned_items();
-    const auto iter = binned.find( what );
+    const auto iter = std::find_if( binned.begin(),
+    binned.end(), [&what]( itype_bin::value_type const & it ) {
+        return it.first == what || ( what == itype_UPS_off && it.first->has_flag( flag_IS_UPS ) );
+    } );
     if( iter == binned.end() ) {
         return 0;
     }
```
visitable must die
</details>

**Comment by Raikiri** [comment]
Can this be relevant https://github.com/CleverRaven/Cataclysm-DDA/issues/62795 or is that an issue of its own?
