### ISSUE TITLE
Switch default "Aim window display style" to Numbers

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63388]
### Is your feature request related to a problem? Please describe.

The "Bars" style is really unintuitive and confusing, especially to new players. It makes virtually no sense unless you already know that it represents percentage chance of various kinds of hit.

The Numbers display makes obvious and gives a much more useful overview of your actual hit chance. However, many players don't even realize that it exists, as it's buried deep in the Settings menu, and you don't particularly have any reason to go looking for it because why would you even assume that it exists?

### Solution you would like.

Just change the default setting for Settings->Interface->Aim window display style from "Bars" to "Numbers

### Describe alternatives you have considered.

As far as I'm concerned we could just remove the bars entirely, but I'm sure someone out there likes them. Might be useful if you have trouble reading little numbers, so probably worth preserving as an accessibility option if nothing else.

**Comment by zeeb92** [comment]
`Just change the default setting for Settings->Interface->Aim window display style from "Bars" to "Numbers`
Why not both? I suggest having both.

**Comment by MelacholicMimic** [comment]
Your entire argument is an appeal to possibility. Unless you can establish that a significant majority of the playerbase prefers the percentile style there is no point in discussing this. 

<details>
  <summary>I'm also in complete disagreement with you</summary>

   > The "Bars" style is really unintuitive and confusing, especially to new players.

I found them to be sufficiently self explanatory when I first started playing. 

> The Numbers display makes obvious and gives a much more useful overview of your actual hit chance.  

No. The bars tell me everything I need to know with a single glance. 
With percentages I not only need to focus on each number I also need to mentally combine 'great' and 'normal' to get the information I actually want. I'd also assume they are a pain to read on mobile. 

> as it's buried deep in the Settings menu, and you don't particularly have any reason to go looking for it

If you can't be bothered to look at the options you don't deserve to have them. 

</details>

**Comment by Terrorforge** [comment]
Well it's not like I've run a formal poll, but every time I've told someone about this their reaction has been "wow that's so much better!!"

> If you can't be bothered to look at the options you don't deserve to have them.

what the fuck, dude.
