### ISSUE TITLE
Tool quality levels that could be set based on actual physical measures

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#63386]
### Is your feature request related to a problem? Please describe.

From a discussion in #63375:
> Depending on the ore's hardness, I guess you could just try smashing it with another rock of harder material

This came about due to the concern about requiring a chisel to break ores into smaller pieces for smelting, which for innawoods might lead to a problem of "needing the tools to process the ore you need to get the tools" (in @PatrikLundell's words. The likely solution for that scenario would be some innawoods-specific version of the recipe that uses cruder tools/process and takes longer.)

Which got me thinking, it would be so much more convenient for content contributors if some tool qualities were not just arbitrary ordinal numbers but had actual basis in some physical property. This would allow fine tuning recipe requirements with better real world basis.

### Solution you would like.

`CHISEL` can be based on (10×) Moh's hardness of the material, so recipes can set tool requirements depending on what material is being worked. Innawoods can have alternative recipes in case a "chisel" (= wedge shaped tool) isn't available, that would utilize an alternative (mod-specific) `SMASH` tool quality -- also corresponding with material hardness -- to crudely pulverize the material.

Other possibilities (hardness): `GRIND`, `DRILL`, `DRILL_ROCK` -- although for drilling it is currently drawing a distinction between hand-powered vs power tools, which starts going into the territory of having tool quality with multiple sub-parameters.

Pickaxes are an interesting possibility that don't currently have a quality; it could affect ability to mine through certain materials, and impact mining speed.

`BOIL` can be based on the temperature that the receptacle can withstand, which enables more accurate tuning of what receptacles are usable in a recipe. This can extend to smelting recipes; depending on the melting points involved it may not be compulsory to use a clay crucible.

`ROPE` could use tensile strength to determine what load it can withstand.

### Describe alternatives you have considered.

Stuff currently works as it is; so I guess it is up for discussion whether the suggested changes are worth the potential benefits.

**Comment by Karol1223** [comment]
Very much yes. Boil specifically has been my Achilles heel. I've added a few items with this quality and I always just added a number that felt somewhat right because I have no idea what the quality is actually supposed to represent.

**Comment by Raikiri** [comment]
As a counter-argument to consider, currently if a user sees a tool with a quality of 4, it's probably more advanced than at least 3 other tools. This helps to create a context while looking at a single item.

**Comment by cake-pie** [comment]
It turns out that `LIFT`, `JACK` and `SELF_JACK` are already set based on physical quantity; each tool quality level corresponds to 500kg capacity. So the idea is not completely unprecedented.

> As a counter-argument to consider, currently if a user sees a tool with a quality of 4, it's probably better at its job than at least 3 other tools. This helps to create a context while looking at a single item. This is particularly useful with tools that have many qualities such as survival knives and multi tools.

I don't think it makes as much sense to do this with things like knives or screwdrivers or wrenches; or at least nothing straightforward immediately springs to mind. So probably not a huge concern.
