### ISSUE TITLE
Long Plank>Spear shafts/Long Pointy Sticks

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63398]
### Is your feature request related to a problem? Please describe.

Long Planks are 8 feet long. Long Pointy Sticks are 80 inches long. Spear shafts are 70 inches long.

We should be able to cut Long Planks down into spear shafts or long pointy sticks.

### Solution you would like.

Add Long Plank to the recipes in question, or a Long Plank>Long Stick recipe.

**Comment by PatrikLundell** [comment]
A piece of plank would be a lot weaker than a stick that's made from a branch or a sapling where the full tree rings are preserved, rather than just a section cut out of tree rings of a mature tree.

**Comment by Creationary** [comment]
So have spear shafts historically only been crafted from perfectly round sections? That seems far-fetched.

**Comment by PatrikLundell** [comment]
I can't see that preparing the surface would do much to affect the structural properties of a piece of wood. It would help to protect the wood from being affected by moisture and might protect the surface a bit, but I don't think it penetrates beyond the surface.

Usage of wood has historically been more particular than in modern times, at least for some purposes, such as timber for ship building. I wouldn't be surprised if they spent some effort in trying to find good wood for spears, as they didn't have power tools, and so would have to spend a fair bit of time to process the raw product. Thus, spending extra time to reduce the risk of wasting a lot of time producing something that can't be sold would make sense.
However, I don't have any information of how spear wood selection was actually done, and I can certainly imaging an average Joe stuck in the Cataclysm making a lot of mistakes of all kinds that someone with basic knowledge of the processes involved would not make (such as cutting a piece off a plank, including a prominent knot, and they try to use it to make a spear, only to have it break at the first thrust (at least that's what this average Joe would guess would happen)).

**Comment by Aerin-of-the-Toast** [comment]
> So have spear shafts historically only been crafted from perfectly round sections? That seems far-fetched.

Spear shafts were historically cut from coppiced young trees (similar ish to how we get long sticks ingame), not cut from long planks. So, yes.

**Comment by Sepentine** [comment]
> A piece of plank would be a lot weaker than a stick that's made from a branch or a sapling where the full tree rings are preserved, rather than just a section cut out of tree rings of a mature tree.

Most handles for tools like shovels or baseball bats are made out of a plank or just any large section of wood. It doesn't seem like it makes too large of a difference

https://www.youtube.com/watch?v=gYUVN6iHof0

**Comment by Sepentine** [comment]
> > So have spear shafts historically only been crafted from perfectly round sections? That seems far-fetched.
> 
> Spear shafts were historically cut from coppiced young trees (similar ish to how we get long sticks ingame), not cut from long planks. So, yes.

Spears are a very basic weapon with countless variations, there's no definitive way to make a spear. As long as it has a shaft and head its a spear, most modern blacksmiths just cut the shaft from a large piece or plank of ash, it doesn't seem to make any difference as far as the rings go.

https://www.youtube.com/watch?v=dcrRhnzV2Fo - here's an example of a spear made without using a sapling, this is the only way I've seen modern blacksmiths make spears, and honestly as long as it gets the job done it doesn't really matter, its the apocalypse after all.

**Comment by Sepentine** [comment]
> I can't see that preparing the surface would do much to affect the structural properties of a piece of wood. It would help to protect the wood from being affected by moisture and might protect the surface a bit, but I don't think it penetrates beyond the surface.
> 
> Usage of wood has historically been more particular than in modern times, at least for some purposes, such as timber for ship building. I wouldn't be surprised if they spent some effort in trying to find good wood for spears, as they didn't have power tools, and so would have to spend a fair bit of time to process the raw product. Thus, spending extra time to reduce the risk of wasting a lot of time producing something that can't be sold would make sense. However, I don't have any information of how spear wood selection was actually done, and I can certainly imaging an average Joe stuck in the Cataclysm making a lot of mistakes of all kinds that someone with basic knowledge of the processes involved would not make (such as cutting a piece off a plank, including a prominent knot, and they try to use it to make a spear, only to have it break at the first thrust (at least that's what this average Joe would guess would happen)).

the game is set in modern times, we should look at modern times for an example, there's no point in doing something to be perfectly historically accurate in the apocalypse its function over form

**Comment by Sepentine** [comment]
> A piece of plank would be a lot weaker than a stick that's made from a branch or a sapling where the full tree rings are preserved, rather than just a section cut out of tree rings of a mature tree.

you need a source for this. most modern examples use a large section of wood put through a lathe, and these are toolsmiths and blacksmiths that have both options at their disposal. If making tools or spearshafts from saplings is more practical you'd see it done more often, but it seems there's absolutely no issue with making shafts from chunks of wood as it is the most common way that we make them nowadays.

**Comment by Zireael07** [comment]
@Sepentine spears are kinda an innawoods weapon in CDDA, so I expect pre-modern techniques to be used
