### ISSUE TITLE
Inability to recover from weariness while doing various food prep recipes

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#63412]
### Is your feature request related to a problem? Please describe.

There are numerous food recipes that are LIGHT_EXERCISE when they are usually not that difficult (such as making bread, roasting meat or acorns or whatever, canning food, etc) and because even light exercise prevents you from recovering weariness, doing them simply makes you more tired. I would expect that spending some time making sandwiches, jarring jam, etc should help me recover from tiring activity like digging holes, killing zombies and blacksmithing, but due to game mechanics this is not possible. It's especially bad because many of these are basically minimal effort (sealing food in jars and watching them boil is apparently light exercise for the entire several hours it takes to complete).

### Solution you would like.

Either the majority of food prep and most chem recipes (such as breaking down wood into sugar or methanol) should be NO_EXERCISE or the weariness recovery system should be changed so that you can reduce your weariness while doing very easy but nonzero activities.

### Additional context

I can definitely work on this myself after my cooking costs PR merges but I just wanted to make sure I wasn't the only person with this complaint.

**Comment by actually-a-cat** [comment]
I definitely would expect to recover from serious weariness while doing 'light' activity. Or generally, to recover at some non-zero rate whenever my activity level is lower than the corresponding weariness level.
