### ISSUE TITLE
Fishes on the land are somehow hard to hit

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#63415]
### Describe the bug

They have really high dodge, but it doesn't seem like there's any difference whether they're on the land or not.
They could be.. slippery and jumpy but it shouldn't be THAT hard to hit, right?

### Steps to reproduce

1. Bring a fish to the land with a boat
OR Debug spawn a fish on the land
2. Try to hit the fish
3. Observe the dominance the fish is asserting

### Expected behavior

I thought I would miss at least less than excepted.

### Screenshots

![IMG_20230204_085451](https://user-images.githubusercontent.com/52661206/216733199-9c53f81b-1cc2-4dae-a502-fa877cfaaeea.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 12; Incremental: G991NKSS3CVI3; 
- Game Version: a14b798 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]

### Additional context

This could be a new way to train melee...

**Comment by Karol1223** [comment]
While you were fighting the apocalypse, the Carp were studying the blade...
