### ISSUE TITLE
Lower Helicopter Fuel Consumption Rate

### ISSUE THREAD

**Issue by crp763** [CleverRaven/Cataclysm-DDA#63419]
### Is your feature request related to a problem? Please describe.

After testing various helicopter flight profiles, I'm finding that helicopters across the board are burning fuel many times faster than their real life equivalents. The civilian helicopters are also too heavy since they're being built from steel frames.

Using a helicopter pilot with max vehicle skills and spawning in undamaged helicopters, I found the following:

BLACKHAWK:
- The fuel capacity is accurate. The weight and size are a bit low, but in the right ballpark
-Burns fuel at about 3x the IRL rate. In game they can fly for anywhere from ~1-1.5hr depending on their speed, but IRL the Blackhawk has an endurance closer to 3-4.5hrs.

MEDEVAC
- Fuel capacity is about right. Weight is about 2x high, should probably be made from lighter frames. Only military helicopters are made from steel frames, civilian models are usually made from composites or aluminum which are many times lighter.
-Burns fuel at about 6-8x the IRL rate. In game can only fly for 0.5hr at the most efficient cruising speed, but real 4-seater medevac models have an endurance in the range of 3-4hrs.

SMALL FLIER
- Too heavy and carries too much fuel. In-game version weighs 4749lbs and carries 400L of fuel. IRL single-seaters weigh in at 500-100lbs and carry 50-100L of fuel. Even the larger models (mostly military) top out around 2500lbs and 200L.
- Top speed is too high (225mph in game vs ~100mph IRL)
- Burns fuel at too high a rate. Even with the 400L fuel capacity, can still only fly 1-1.5hrs. Single seaters IRL are usually designed to an endurance time of 2-2.5hrs on a 50-100L tank.

ALL MODELS
- Burn way too much fuel at max speed, to the tune of several liters of fuel per second. IRL helicopter speed is limited by blade aerodynamics, not engine performance. Helicopters are only going to burn fuel at about twice the rate when flying at max speed compared to cruise. Eg. the Blackhawk in game can only fly for about 50s at max speed, but in real life could sustain max speed for close to an hour.

### Solution you would like.

- Fuel consumption rate of all motors should be decreased across the board. Most helicopters should be able to stay in the air 2.5-4.5hrs if flying at normal cruising speeds. They should be able to fly for roughly half that long when either hovering in place or flying at their max design speed
- Civilian models should be constructed from extra light frames to represent aluminum/composite construction, and the maximum flight weight of these vehicles should be adjusted to match their new weights
- Civilian models should have lower max speeds. While military combat helicopters can usually push speeds over 200mph, common civilian models usually top out somewhere in the 100-150mph range
- The single seater should probably carry less fuel (50-200L range), and have its own rotor with a lower lift capacity than the one used for the medevac

I did not run extensive tests for the Apache, the Osprey, or the 2 seater, but they have similar issues.

### Additional context

See below spreadsheet for in-game flight time calculations, sorted by vehicle model and mode of flight.
[cdda_helicopter_flight_times.xlsx](https://github.com/CleverRaven/Cataclysm-DDA/files/10608266/cdda_helicopter_flight_times.xlsx)

**Comment by crp763** [comment]
I downloaded the source code and the fixes look relatively straightforward, I'll make the necessary update and initiate a pull request.

**Comment by Termineitor244** [comment]
It would be good if you can correct any numbers that are out of place, the helicopters were added in #33829, which tried to make use of real life numbers for fuel consumption as well as fuel capacity, but the author has gone missing since so not much has been changed to them since their original inception in the game.
