### ISSUE TITLE
Asking for items as payment gives you $500 worth of barter value from the NPC's inventory

### ISSUE THREAD

**Issue by Chadtholomew** [CleverRaven/Cataclysm-DDA#63410]
### Describe the bug

Asking for items as payment gives you $500 worth of barter value from the NPC's inventory, which is way too much. First, many NPC's don't even have any stuff on them (would be nice if they did), and second, this is really bad for balance when you are doing a vendor's quest especially when they already give you a reward of merch or tokens. Third, it would be nice if I could go back and select a different reward like training if that NPC didn't have any items on them, or preview their inventory before selecting that option. Finally, the NPC already gives you a reward of merch, what's the point of getting an additional reward? The UI lets you pick "no payment necessary" but that is after he gives you a stack of merch, shouldn't the merch be a reward option instead then?

### Steps to reproduce

Go to the refugee shelter and complete quests for the merchant then ask for items as a reward. He will give you free 500 dollars of barter value on top of the stack of merch that he gives you.

### Expected behavior

I expected to get far less than $500 from them.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: a5ec978 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    No Hope [no_hope]
]

**Comment by andrei8l** [comment]
This is not a bug, unless you find a mission with a reward that doesn't match its value in JSON.

The documentation is missing for this bit, but the reward comes from the `value` member of a mission definition (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/npcs/missiondef.json)
