### ISSUE TITLE
Mutant Scraps Worth Too Much

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63427]
### Describe the bug

Mutant meat scraps are worth 50 cents each. Just like chunks.

### Steps to reproduce

Butcher a mutant.

### Expected behavior

Should be worth 5 cents and not 50

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 8774a17 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
/confirmed a lot of the items in `carnivore.json` have proportional `price` instead of/but not `price_postapoc`

<details>
<summary>example fix</summary>

```diff
diff --git a/data/json/items/comestibles/carnivore.json b/data/json/items/comestibles/carnivore.json
index 767691cf4b..9ec7b053ef 100644
--- a/data/json/items/comestibles/carnivore.json
+++ b/data/json/items/comestibles/carnivore.json
@@ -322,7 +322,7 @@
     "name": { "str": "scrap of meat", "str_pl": "scraps of meat" },
     "description": "A tiny scrap of raw meat.  It's not much, but it'll do in a pinch.",
     "cooks_like": "meat_scrap_cooked",
-    "proportional": { "weight": 0.1, "volume": 0.1, "price": 0.1, "calories": 0.1 },
+    "proportional": { "weight": 0.1, "volume": 0.1, "price_postapoc": 0.1, "calories": 0.1 },
     "delete": { "flags": [ "SMOKABLE" ] },
     "vitamins": [ [ "calcium", 0 ], [ "iron", 1 ] ]
   },
@@ -379,7 +379,7 @@
     "description": "A tiny scrap of raw meat from a heavily mutated animal.  It smells unappealing, to say the least.",
     "looks_like": "meat_scrap",
     "cooks_like": "mutant_meat_scrap_cooked",
-    "proportional": { "price": 0.2, "calories": 0.5 },
+    "proportional": { "price_postapoc": 0.2, "calories": 0.5 },
     "vitamins": [ [ "mutant_toxin", 2 ] ],
     "delete": { "flags": [ "SMOKABLE" ] }
   },
```

</details>

Alternatively, make proportional price affect both `price` and `price_postapoc` by the same factor since this error appears to be widespread
