### ISSUE TITLE
Lotus is solid for vehicles

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63448]
### Describe the bug

Driving amphibious vehicles in and out of water is made more difficult by lotuses, which you can crash into.

### Attach save file

n/a

### Steps to reproduce

Make vehicle, try to move it through a lotus

### Expected behavior

Driving over lotus.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 8774a17 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
/Confirmed (on an experimental a few months old).

**Comment by GuardianDll** [comment]
To fix someone need to add "NOCOLLIDE" flag [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/furniture_and_terrain/furniture-flora.json#L198)
Easy 1 string fix
