### ISSUE TITLE
The save (and the game itself) breaks after restarting computer 

### ISSUE THREAD

**Issue by someblockhead** [CleverRaven/Cataclysm-DDA#63443]
### Describe the bug

The issues began happening to me in experimental versions, but for whatever reason, trying to reproduce this bug on latest stable seemed to create an even more extreme effect. For example, on Cataclysm-DDA experimental build 2023-01-31-0703, when loading into a save, it would either change the map, or the zombies. (I will include the debug file for that version of the game, hopefully it helps.) However, when loading into stable after shutting down my computer, unplugging it, and turning it back on, everything broke. (See screenshots.) 

I suspect this is either a software or hardware issue that is breaking the game; I am running this game on a very old Probook 6560b, which were first produced in 2009. The battery does not work, so the laptop must be plugged in to operate, and this issue seems to be exacerbated when I have to frequently shut down and unplug my laptop to move from place to place. I have been debating posting this bug report for a while since it may very well just be an issue with my computer and not the game, and I do not want to waste anyone's time, but I think it might be good to post this here in case there is anything that can be done, in the case it is a software related issue. (I'm going to get a new computer soon. I swear.)

Doing fresh installs of Cataclysm does not seem to do much. The errors, crashes, and bugs just happen again eventually.

I am very sorry for the long-winded explanation, I'm not sure how to summarize this problem more effectively, with its convoluted nature.

### Attach save file

[Stillwell County-trimmed (exp 2023-01-31-0703).tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10611986/Stillwell.County-trimmed.exp.2023-01-31-0703.tar.gz)

(I had unfortunately lost the save to the game I had gotten the screenshots from in stable.)

### Steps to reproduce

1. Start a game in a fresh install of Cataclysm DDA, then save and quit.
2. Restart the game and your computer (in my case, shut down computer, unplug, plug back in), and re-enter the game, load your save.
3. Errors happen, then the game becomes completely unplayable, or the environment/zombies are completely changed.

### Expected behavior

I would load into the game without unexpected errors and be able to play the game as intended. The game would save correctly.

### Screenshots

![frank-stable-on-load](https://user-images.githubusercontent.com/123577733/216841650-cba354d4-80f9-4c7d-b2c6-eee11fefc87f.PNG)
![frank-stable-02](https://user-images.githubusercontent.com/123577733/216841706-30448d1a-e42d-4e6d-9f0a-dae296e49fb0.PNG)

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-3 Frank-3, experimental build 2023-01-31-0703
- Graphics version: Tiles
- Mods loaded: Default

### Additional context

[debug-crash-stable.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10611953/debug-crash-stable.zip)
[debug-exp-2023-01-31-0703.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10611958/debug-exp-2023-01-31-0703.zip)

**Comment by andrei8l** [comment]
Loading a save from experimental into the last stable is not supported. Your debug log shows a few corrupted files (and the log from the stable version is corrupted as well) so it looks like you have a hardware or file system problem.

**Comment by Raikiri** [comment]
are you using a launcher? if so, which one?

**Comment by someblockhead** [comment]
> are you using a launcher? if so, which one?

I'm not using any launchers; just downloading directly from the website.

**Comment by someblockhead** [comment]
> Loading a save from experimental into the last stable is not supported. Your debug log shows a few corrupted files (and the log from the stable version is corrupted as well) so it looks like you have a hardware or file system problem.

I should clarify I didn't load any saves from experimental into last stable. I did think it was a hardware/file system issue.
