### ISSUE TITLE
Paper wrapper distorts space

### ISSUE THREAD

**Issue by Kromgart** [CleverRaven/Cataclysm-DDA#63451]
### Describe the bug

Items inserted into the "paper wrapper" ignore some item-dimension restrictions on parent containers.

For example, you cannot normally put a rock into glass bottle (probably because of the "max item volume" restriction). But if you put the rock into a paper wrapper, then it goes through the bottleneck just fine!

### Attach save file

N/A

### Steps to reproduce

1. Make a player with a rock (volume 0.25L), a glass bottle (item max volume 0.017L) and a paper wrapper.
2. Try to 'insert' into the bottle. The rock is not shown in the list.
3. Insert the rock into the paper wrapper.
4. Now try to insert into bottle. You now can insert "paper wrapper > rock" just fine!

I tried few other bags (zipper bag and plastic bag) and they behave properly (cannot insert them into the bottle when they are loaded with a rock, _unless_ you put them inside a paper wrapper before!).

### Expected behavior

Containers should not allow to insert items in them if these items do not fit, even if the items are hidden in a magic paper wrapper.

### Screenshots

![magic_wrapper](https://user-images.githubusercontent.com/1553853/216963780-52b46200-a4c1-46e0-9752-9541c56cae85.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-13232-g07f6a2e6ac-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    kromgart_sidebar [kromgart_sidebar]
]

**Comment by mqrause** [comment]
/confirmed

https://github.com/CleverRaven/Cataclysm-DDA/blob/c8bebe2dc0da2e842d6828299680bb0f1a8caeba/src/item_pocket.cpp#L1308-L1317

Soft containers are still considered soft even when they contain hard things.

The easy solution to this case would be to consider containers as hard when they contain hard things, but I'm not too happy with that since it shouldn't be just binary.
