### ISSUE TITLE
Sorting zones freeze

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63452]
### Describe the bug

Sometimes my sorting zones enter a state where the game freezes permanently every time I try to auto sort them. It only happens when I accumulate enough crap, so it's very hard to track down exactly what it's related to. However, thanks to the recently added feature, I now can upload a trimmed down version of the saved game where the issue is still reproducible.

### Attach save file

[Columbia Heights-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10664147/Columbia.Heights-trimmed.tar.gz)

### Steps to reproduce

1. Shift-o
2. Select all zones
3. Witness a freeze

### Expected behavior

I expect the game to not freeze when I use zones

### Versions and configuration

Current experimental.

### Additional context

The bug seems to be related to the current location of my vehicle. If I move it to a different place, it no longer freezes.

**Comment by andrei8l** [comment]
/confirmed It gets stuck on `MAG_DESTROY` items in the unload zone. Items are sourced from vehicle and map, but `MAG_DESTROY` items are only removed from the map.

<details>
<summary>Potential fix</summary>

```diff
diff --git a/src/activity_item_handling.cpp b/src/activity_item_handling.cpp
index 2957d47578..6fe67a3df1 100644
--- a/src/activity_item_handling.cpp
+++ b/src/activity_item_handling.cpp
@@ -2323,7 +2323,11 @@ void activity_on_turn_move_loot( player_activity &act, Character &you )
                         }
                     }
                     if( it->first->has_flag( flag_MAG_DESTROY ) && it->first->ammo_remaining() == 0 ) {
-                        here.i_rem( src_loc, it->first );
+                        if( this_veh != nullptr ) {
+                            src_veh->remove_item( src_part, it->first );
+                        } else {
+                            here.i_rem( src_loc, it->first );
+                        }
                         num_processed = std::max( num_processed - 1, 0 );
                         return;
                     }
```

</details>

**Comment by Raikiri** [comment]
Do I understand correctly that a workaround for this issue is to disable my unloading zone?

**Comment by andrei8l** [comment]
Yes. Let me know if that's not sufficient.

**Comment by Raikiri** [comment]
That character had an accident with a really unfortunate grenade throw tonight, so he's not too concerned with zone problems anymore.

I did not even realize that my character was _also_ engaging the unload zone while selecting the "Sort out my loot (all)" option. I hope your fix gets merged soon, because I reckon this is exactly the thing that kept breaking zones for some people, while working perfectly fine for others. I bet people who never experienced freezes just never set an unloading zone.
