### ISSUE TITLE
Cutting up heat packs yields cotton patches

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#63454]
### Describe the bug

As the title suggests, cutting up heat packs yields cotton patches somehow?

### Attach save file

Shouldn't be necessary. Not that I have any heat packs on my savefile left anyway.

### Steps to reproduce

1. Find a heat pack
2. Cut up the heat pack
3. Behold the glorious material transmutation

### Expected behavior

It is made of plastic. It has no connections to cotton. It should either not be cuttable (depending on the irl size, not sure here) or give plastic chunks when cut.

### Screenshots

![obraz](https://user-images.githubusercontent.com/68503002/217036676-56c7af12-7a2e-4f85-b1b4-ebc0d230b151.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 908472c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

How, even? I've been trying to find ways to connect json to the cutting code and kept failing, how in tarnation do we have a bug that overcomes that?

**Comment by mqrause** [comment]
You can craft heat packs using a cotton patch, and that determines what you can salvage. Not sure that makes sense for the kind of heat pack this is supposed to represent. Removing cotton from the recipe should default to plastic instead.

**Comment by andrei8l** [comment]
> How, even? I've been trying to find ways to connect json to the cutting code and kept failing, how in tarnation do we have a bug that overcomes that?

https://github.com/CleverRaven/Cataclysm-DDA/blob/908472cac4573948cba92f5f72e13b2a8bc01212/src/iuse_actor.cpp#L1570-L1571

**Comment by Karol1223** [comment]
Seriously? Cutting somehow connects to the recipe? That's... weird. And something that I never thought even applied, it's very hard to notice.
