### ISSUE TITLE
Cant see through vehicle windows within two tiles

### ISSUE THREAD

**Issue by larsenf** [CleverRaven/Cataclysm-DDA#63463]
### Describe the bug

I just installed two extra turret mounts above the driver set and center of my apc based vehicle and now me sight distance is limited to 1 tile within two tiles of the windshields. When outside the vehicle i cannot see into it within two tiles of the reinforced windshield. de installing the the mounted m249, turret mounts and the reinforced windshield does not give me normal visibility.

It is also doing this with the open back door.

### Attach save file

[Juno Beach.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10671699/Juno.Beach.zip)

### Steps to reproduce

Move towards the vehicle windshield (or where it obviously was), move towards the back of the vehicle, move the the outside directly in front of the vehicle and then step back from it.

### Expected behavior

I expect to always have vision though the windshield and open tiles during the day.

### Screenshots

![image](https://user-images.githubusercontent.com/10336792/217155164-e8785ae1-428f-43dc-92cc-4903815cfe3c.png)
![image](https://user-images.githubusercontent.com/10336792/217155635-f5c25364-4948-43c3-9916-1706e3aff154.png)

![image](https://user-images.githubusercontent.com/10336792/217155248-d0e5f86e-a465-4ce4-8361-72303decb1ab.png)
![image](https://user-images.githubusercontent.com/10336792/217155284-90d0342e-5f9d-4352-a244-2eb43897482a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
Not a bug. Your character is crouching behind a 45% cover (provided by the cargo space) so they can't see past it

**Comment by larsenf** [comment]
omg thank you so much. i feel like a moron wasting your time.

**Comment by andrei8l** [comment]
You didn't waste my time and you're not a moron. The mechanics of this game aren't always clear and the crouching indicator in Ultica isn't the most visible either.

**Comment by Raikiri** [comment]
I really hope you didn't go bashing Z's while crouched, man
