### ISSUE TITLE
CDDA experimental builds doesn't launch on mac

### ISSUE THREAD

**Issue by Magical2x5** [CleverRaven/Cataclysm-DDA#63475]
### Describe the bug

Game launches but no window is shown

### Attach save file

N/A

### Steps to reproduce

1. download osx-tiles any experimental build
2. launch 

### Expected behavior

i expected to see the main menu

### Screenshots

i cant open game

### Versions and configuration

macOS Ventura 13.2 (22D49)

**Comment by BrettDong** [comment]
Tried https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-03-25-0112 on macOS 13.2.1 Ventura on M1 and the game opens fine.
