### ISSUE TITLE
Make "Generate minimized save archive" not disable achievements

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63470]
### Describe the bug

With the new (amazing) feature that generates a trimmed down save file being mandatory, it causes achievements to become disabled whenever it's used, even though practically cheating with this feature is challenging at best.

### Attach save file

N/A

### Steps to reproduce

1. Start a new character
2. Main Menu -> Debug Menu -> Info -> Generate minimized save archive
3. The game prompts you that it'll disable achievements (and it does)

### Expected behavior

If possible, I'd like to not disable my achievements even though I know I can re-enable them, because it kind of breaks immersion.

### Versions and configuration

Current experimental

**Comment by GuardianDll** [comment]
@andrei8l
