### ISSUE TITLE
Red Error on Trying to Create/Load character on experimental version (unable to play)(Still applies for 0.G)

### ISSUE THREAD

**Issue by LordPancitoFresco** [CleverRaven/Cataclysm-DDA#63482]
### Describe the bug

Fresh install, latest experimental version from hours ago, create a world without even looking as it doesnt matter, attempt to create a custom character or hitting "play now!" and i get a red text

I spoke about this on the cdda discord and someone told me "Possibly issue #61095 again" and to remove all the .0 from all the values from in the character_modifiers.json , so i did that but then i get a different issue

I include this last part in case it helps

### Attach save file

N/A

### Steps to reproduce

1- Create world, with any mods so i just left the default ones
2- Press New Game and then any of the options like "Custom Character"

### Expected behavior

be able to create/load a character 

### Screenshots

![Cdda Error 1](https://user-images.githubusercontent.com/64502015/217409929-3c717917-acd2-421f-b990-ea3a858425cc.png)
number 1 is what happens on fresh install without changing anything

![Cdda Error 2](https://user-images.githubusercontent.com/64502015/217410025-7a574da1-f03d-4fdb-b3e0-a52f5e3448a5.png)
number 2 is after i manually remove the .0 from all the values in character_modifiers.json as i was told in the discord, i include
this one in case it helps

(i just read the "Do not take a screenshot of the crashing window. " right before sending this but im leaving them in anyway to prove i actually have a problem, as nobody else in the discord seems to have the same happen to them)

### Versions and configuration

- Windows 7
- Game Version (c8bebe2)
- cdda-windows-tiles-x32-2023-02-07-0628
- English

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10680839/debug.log)

The first debug log is just what initially happens on a fresh install without touching anything.

But after i do the manual edit removing all the .0 values from the character_modifiers.json is this other one:

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10680915/debug.log)

i dont know if they are the same or if it says something different but im including it in case it helps

**Comment by LordPancitoFresco** [comment]
something i forgot to add is that i also tried the 64bit version in case it was that but there was no change, and since i read that earlier issue that i was told about in the discord, my system locale is set to "English (United States)"

**Comment by anothersimulacrum** [comment]
Looks like a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/61095
