### ISSUE TITLE
When comparing items, encumbrance values that only exist on one item are shown in green when they should be red

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#63496]
### Describe the bug

When using 'I' to compare two items which have only partially overlapping coverages (such as something with head coverage, and another with head eyes and mouth coverage), the encumbrance values that only exist in one item are shown in green, implying they are a good thing. However, encumbrance is normally shown in green if it's lower, and an item that doesn't cover something logically has encumbrance 0, which is definitely better than an item that does cover the part and causes encumbrance there.
Therefore, on the side where there does exist a value that doesn't exist on the other side, that value should be shown in red. Or yellow, like how a length value comparison with one side missing it works, but I would prefer red.

Also, I am not sure if warmth and breathability are _meant_ to be red for both items in my screenshot, is that an issue too?

### Attach save file

N/A

### Steps to reproduce

1. Compare a firefighter helmet with a motorcycle helmet
2. Notice a surprising amount of green in the encumbrance section of the motorcycle helmet, look closer and notice what is happening

### Expected behavior

I expected that the values shown in green would indicate less encumbrance, not more, because that's how it works when the values are being compared. You can see the normal behaviour in the attached screenshot where 34 head encumbrance is correctly marked in red as it is higher than 27 head encumbrance.

### Screenshots

Left: firefighter helmet, right: motorcycle helmet
![image](https://user-images.githubusercontent.com/67428677/217686815-9aba6d5b-89ea-4328-aece-d6819a4127b6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 908472c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    50bmgpistol [50bmgpistol],
    DinoMod [DinoMod]
]

**Comment by Kamayana** [comment]
I have also noticed both of these, and yeah the warmth and breathability both being red doesn't feel like it should be that way. I think it might even be caused by the same thing as the encumbrance.
