### ISSUE TITLE
Insert item shows wrong error message if there is no space for any available items

### ISSUE THREAD

**Issue by airportation** [CleverRaven/Cataclysm-DDA#63495]
### Describe the bug

The message shown when there is no space in the container item falsely claims that "Your inventory is empty." even if that's not the reason for why you can't insert an item from your inventory into it, such as when the container item is full. It does also say below that "There are no available choices.", but together with the upper error message that can be understood to mean the same thing.

### Attach save file

N/A

### Steps to reproduce

1. Put a gun in your holster
2. Select the holster and, in its item options, press 'i'
3. Notice it will not say anything to the effect of the holster being too full, instead claiming your inventory is too empty (see screenshot)

### Expected behavior

It should say something to the effect of "Your inventory contains nothing that would fit.", because that's the actual problem.

### Screenshots

![image](https://user-images.githubusercontent.com/67428677/217685573-ef1bcc92-cd39-4c9b-b332-843e3f23e446.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 908472c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    50bmgpistol [50bmgpistol],
    DinoMod [DinoMod]
]

**Comment by Raikiri** [comment]
> Your inventory contains nothing that would fit
It's not only your inventory though, "i"nsert allows inserting items from the ground too. So should probably be something like "There's nothing that you can put inside".

However, I'd argue an even better way would be to show the full list of items grayed out and saying "does not fit", because it's very confusing if the item you're trying to insert is not available or it does not fit. So I'm not a fan of not showing items that don't fit.
