### ISSUE TITLE
Slow movement in CDDA-Soundpack

### ISSUE THREAD

**Issue by Xayrlen** [CleverRaven/Cataclysm-DDA#63503]
### Is your feature request related to a problem? Please describe.

In my current playthrough I settled on a sandy island for a change. I've been using Ottopack's Soundpack mainly and now wanted to try out CDDA-Soundpack. The first and most annoying problem I noticed is a slow tile movement sound effect the game played when you moved through difficult terrain. And boy, the whole island is a difficult trait because of the sand. To say this is annoying to hear is to say nothing.

### Solution you would like.

The problem is, the slow-terrain sound is too long for places filled with obstacles which basically start to loop non-stop and overlap. That sound effect file should hardly excess half a second in a length to not be annoying.

### Describe alternatives you have considered.

What I immediately did to avoid this nuisance it instantly copied the same sound effect from a different soundpack, so I wouldn't have to listen to that constantly due to my circumstances.

**Comment by Fris0uman** [comment]
Should probably post the tissue to the soundpack repo https://github.com/Fris0uman/CDDA-Soundpacks/issues

**Comment by Fris0uman** [comment]
Solved in https://github.com/Fris0uman/CDDA-Soundpacks/pull/69
