### ISSUE TITLE
Add descriptions for stat values

### ISSUE THREAD

**Issue by MikeAllen775** [CleverRaven/Cataclysm-DDA#63523]
### Is your feature request related to a problem? Please describe.

There is no context on what the meaning of stat is.  Am I smart with a 10 intelligence?  What does a value of 5 or 18 in a stat mean?

Having a short description for a stat value to gives **players** an idea of what it means.  Possibly more important though, is that it might help **developers** determine what a realistic stat requirement is.  For example, is 18 strength a lot? Top 1%?  Is an 18 strength requirement for a bow too high?

### Solution you would like.

I would like to see a descriptor of the value of stats, even if it's a general description over a point spread.

For example:
1-3 = Poor
4-7 = Below Average
7-9 = Average
10-14 = Above Average
15-16 = Great
17-18 = Exceptional

I would like to see the descriptor trailing the stat in the character creation stat screen and the "@" player character sheet.  Something like "Strength 10 (Above Average)".  Either that, or display the descriptor in the "hover" text description area.

Maybe after that, I would love to see a quick review of stat requirements based on this idea, if it's implemented.

### Describe alternatives you have considered.

I personally would love to see a more flavorful text in the "hover descriptions", something specific to the stat itself.  Something like:

"You're as strong as 10 men!"
"You're have the strength of a newborn babe."

Maybe even something humorous.  But I'm not sure that would fit all player sensibilities, though.

### Additional context

Background for the suggestion:

As a new player, before I started playing, I learned of the "Elf-A" mutations, and decided I wanted to do that, and get good with a bow.  I created my character with my personal idea of a classic fantasy elf, with low strength (5), high dexterity (10), and high perception (11).

I soon found out that a 5 strength might be described as toddler strength, and that the best bow in the game requires an 18 strength!  But what does 18 strength mean?  Is it godlike?  Or just the high-end of average?  

Naturally, I recreated my character and gave him an 18 strength (because I discovered that unless you start very high, the odds of getting to 18 in-game are unlikely), which required that I "cheat" and turn off point counting.  I discovered that the best bow in the game is awesome, but sadly I rarely use it, because I can now slam-dunk zombies with my massive ham-hands.

**Comment by GuardianDll** [comment]
I like the idea, and we already have this info in balance document, but it contain only comparison about strength

**Comment by MikeAllen775** [comment]
@GuardianDll What file is that in?

**Comment by NetSysFire** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md

**Comment by Snaaty** [comment]
The information is already in the balance doc, so the devs should be aware of it. But to me it makes sense to display the meaning of it to the players to give them a better idea of what their character ist like. 

I think a neutral description similar to the one in the balance doc should be good for most players?

To be honest, for a simulationist game like this the stats do feel out of place and practically none of them have a proper real-life equivalent. (Strength? -> which muscles?, Dexterity? -> being a brilliant pianist sure doesn't help with lockpicking, Intellligence? -> we don't even know how to measure that in real life, -> Perception? Do people actually have genuinely different levels of perception, beyond being short or far-sighted?) Popular RPGs always roll with stats, that's where CDDA has them from I suppose, I imagine one day perhaps CDDA can move away from them, even though they're currently still everywhere in the code afaik. 

Ah sorry, to derail your suggestion anyway, I got carried away a bit. I like your idea.

**Comment by MikeAllen775** [comment]
@NetSysFire Thanks!  I checked it out, and it's pretty much close to what I expected.

@Snaaty I agree that it's hard to boil down a person's capabilities into a series of scores, but without it, how could we make comparisons in game (or even real life)? Even in real life, we sometimes assign arbitrary values to people ("I've seen prettier, they're a 7 at best"), but we usually make comparisons instead ("clever as a fox", or "like a bull in a china shop").

Back on topic, I guess the dev's have had a sense of what the numbers mean before now.  I still wouldn't mind having it there for players though.  It might be too late for me, but future new players will probably be grateful.

On a side note, I've read several other posts specifically about the 18 strength requirement on the Compound Greatbow, and as heated as it got, I'm going to steer clear of opening that can of worms again.  I'll just play a burly elf!

**Comment by anoobindisguise** [comment]
Is the game balance doc even still accurate? I thought Erk had said at one point it needed to be rewritten.

**Comment by NetSysFire** [comment]
>Average damage: 6 (normal day one threat; zombie, wasp)

I think some of it is outdated.

>about the 18 strength requirement on the Compound Greatbow

I think it can be better handled though. I have done some archery irl and using a bow that has a higher draw weight you can handle will make cause you to shoot slower (as it takes more time to pull back the bowstring) and your arm muscles tremble after a few shots, resulting in even slower drawing of the bowstring and decreased accuracy. And there is a big difference between attempting to shoot it with 17 strength vs trying at 8 strength. The latter being impossible while the former has just a penalty. Out of scope for this issue though.

>we sometimes assign arbitrary values to people

I think this is a fun suggestion though. This ranges from a simple popup stating e.g 8 = average to something more complex. A more complex thing I could see it being implemented as are "status messages" for traits and effects. E.g being malnourished and the resulting strength penalty would result in a "You are bone thin and you can see barely any muscles." while 9 strength would usually display "You have slightly pronounced muscles but they are still very modest.".

**Comment by Snaaty** [comment]
Honestly I feel like the attributes could probably mostly be subsumed into skills/proficiencies. When the attributes where initially made up, proficiencies did not exist yet. 
And perhaps thinking more in the line of traits for conditions that are "unusual", like NetSysFire suggested where a particularly fit survivor maybe gets bonuses to stamina e.g. 
The more I think about it, the more ridiculous the stats sound tbh. I get it's a common trope but it's surprising to me that no one has tried to axe them so far considering their tenuous connection at best to real life characteristics. Untangling all instances of the stats from the code sounds a bit like a pain though, so maybe that's why. 

Anyway (sorry) back on topic: Do you think the stats description should be put into the character creation window maybe? As that would typically be the first situtation in which a new player is confronted with abstract numbers and has to gauge the type of character he wants to play.
