### ISSUE TITLE
Player should start with recipes for starting skills. [$5]

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#6352]
Say you start with a tailoring at 4 or 5. You should also start with all recipes that require 4-5 tailoring skill (assuming you have any other required skills as well).

This will make starting with skills a more valid decision in character creation.

**Comment by Chase-san** [comment]
This is fairly straight forward to implement, just adding a small bounty to move it from most peoples 'to do eventually' to their 'to do soon' lists. I could do it, but super busy these days with work.

**Comment by Coolthulhu** [comment]
@OzoneH3 implemented this one. Should I close?

**Comment by mugling** [comment]
Yes, there's no need for it to remain open

**Comment by codemime** [comment]
Has he received his five bucks? :stuck_out_tongue:

**Comment by Chase-san** [comment]
I think he needs to go to the bounty page and claim it, then someone verifies it, and he gets his 5 USD.
