### ISSUE TITLE
Error when trying to re``f``ill a vehicle tank

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#63535]
### Describe the bug

An error screen pops up when pressing f to refill a tank in a vehicle. Sometimes happens just when examining the vehicle. The weird part is it only happens on that one specific vehicle (that I built).

### Attach save file

[TrailBalls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10713077/TrailBalls-trimmed.tar.gz)

### Steps to reproduce

1. Examine the vehicle (the one the character is standing in)
2. If no error screen yet - press ``f`` to refill tanks
3. Behold the error screen

### Expected behavior

Man I'd really rather not see error screens that'd be grand

### Screenshots

![obraz](https://user-images.githubusercontent.com/68503002/218251079-0c785b99-40f2-451f-8fcd-efdaf368e064.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 2ee4928 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
/confirmed

This part:
https://github.com/CleverRaven/Cataclysm-DDA/blob/7216560e9acd3cbe7d2976a3489965fb3f481ada/src/vehicle_part.cpp#L261

tries to turn an `ammo_type` into an `itype` which is not universally valid. Most `ammo_types` have names matching an `itype` but a lot of chems and spare parts have `"ammo_type": "components"` and `components` is not (also) an item.

**Comment by irwiss** [comment]
liquid soap fails ammo_type lookup in some way, examining the vehicle will fail drawing fuel indicators, if you siphon to a container then save/exit/reload the game you'll get an error when you press `f` with the container on hand/nearby instead

minimal change that stopped the error is changing to comestible like so:
![image](https://user-images.githubusercontent.com/6560075/218254251-49af589e-3a70-4034-8a71-7e32cb9a6466.png)

**Comment by mqrause** [comment]
> minimal change that stopped the error is changing to comestible like so: ![image](https://user-images.githubusercontent.com/6560075/218254251-49af589e-3a70-4034-8a71-7e32cb9a6466.png)

Please use type `GENERIC` with `"stackable": true` instead. This whole thing of making items ammo or comestible to make them stack is a horrible hack. And the `components` ammo type is a part of that.

**Comment by Karol1223** [comment]
> Please use type GENERIC with "stackable": true instead. This whole thing of making items ammo or comestible to make them stack is a horrible hack. And the components ammo type is a part of that.

Don't liquids have to be comestible to properly function as a liquid? I was under the impression they do, since about all liquids are comestible. Including stuff like bleach... I do think that at least they can't freeze when not comestible.

**Comment by mqrause** [comment]
Right, freezing is a thing, so comestible might actually be the right call here. (Although comestible just for freezing isn't ideal either.)
