### ISSUE TITLE
Simple mace and trench mace have the same stats despite the latter obviously meant to be an upgrade

### ISSUE THREAD

**Issue by DSeyka** [CleverRaven/Cataclysm-DDA#63538]
### Describe the bug

Trench mace requires simple mace as a component but has the same stats.

### Attach save file

N/A

### Steps to reproduce

Have fab 1 and look at mace recipes

### Expected behavior

Trench mace being better than simple mace

### Screenshots

![image](https://user-images.githubusercontent.com/66876732/218262017-f0578ec5-21d5-4f4a-b6bc-d72fc03439f4.png)
![image](https://user-images.githubusercontent.com/66876732/218262001-dc2c266d-5124-40bb-82a1-39df5efbd964.png)
Note them being identical, combat-wise.

### Versions and configuration

- Game Version: 7216560 [64-bit]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Seems trivial to fix and I'd even do a PR myself if I had any idea which numbers to use.

**Comment by actually-a-cat** [comment]
Simple mace is fragile, trench mace isn't, that's a significant upgrade.

**Comment by DSeyka** [comment]
Indeed, wasn't easy to notice! Not an issue then, I guess.

**Comment by DSeyka** [comment]
Indeed, wasn't easy to notice! Not an issue then, I guess.

**Comment by DSeyka** [comment]
Indeed, wasn't easy to notice! Not an issue then, I guess.
