### ISSUE TITLE
"Steel ballistic plate" Can not Be Repared

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#63532]
### Describe the bug

Currently, "steel ballistic plate" items do have "Repair" function associated and in my understanding, are intended to be repairable. However, the material required for repair is "Tempered Carbon Steel" while the "repairing tool" is one from the sewing kind (bone needle, needle… tailor's kit), not the welding/metalworking one. "Welding kit" is listed however, but not (makeshift) arc welder.

Making an attempt to repair "steel ballistic plate" with sewing/tailor's kit results in error message that the item is not made of any of the appropriate materials. And the item does not show in makeshift arc welder's repair list at all.

### Attach save file

[Klamath-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10712625/Klamath-trimmed.tar.gz)

### Steps to reproduce

1. Access Tailor's kit repair menu via a>"tailor's kit">"Repair";
2. Select "steel ballistic plate" and attempt to repair it.

### Expected behavior

I believe sewing line of repair tools were attached erroneously, as the item is mostly "steel" (even though "Synthetic Fabric" is listed as a secondary material in "Material" entry).
Only "welding kit" is described as being able to repair "tempered metal". It is a pain to get one (it is not craftable), but I can understand this is intended. In this case using "bone needle" (a way lower tech item) and repairing with "Synthetic Fabric" (again, way more easily available than "Tempered Carbon Steel") completely breaks balance (why even bother with welding line?).

So, my proposal is to remove "Synthetic Fabric" and sewing line of tools altogether. Requiring a "welding 2" tool quality (to allow "arc welder") or restrict exclusively to "welding kit"… I'm not sure. Neither is craftable and must be found and I don't know about their rarity (haven't found either yet).

### Screenshots

![ballistic_plate_01](https://user-images.githubusercontent.com/125039757/218241093-a66ecc0a-fe82-409a-a4bf-104767c15679.png)
![ballistic_plate_02](https://user-images.githubusercontent.com/125039757/218241096-6f07bdd3-5a99-4e43-a3be-25de86c76d2e.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 95521e0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Drew4484** [comment]
A welding kit is assembled from a welder and a welding blanket. This is the only tool to repair tempered steel with.

**Comment by Alm999** [comment]
> A welding kit is assembled from a welder and a welding blanket.
Yes, but both "ark welder" and "welding blanket" are not craftable and must be looted. I don't know whether it is easier to found these two items separately, or get the whole thing pre-assembled, but that's besides the point.

IMO, "bone needle" and its ilk are misplaced here, as is "Synthetic Fabric" material, as allowing to repair via sewing completely outclasses the "welding route" making finding "welding kit" and "Tempered Carbon Steel" not worth the hassle.

**Comment by Alm999** [comment]
Another addition to the topic: currently, the **welding 2** quality is also being provided by (craftable from salvageable junk) "[vehicle] welding rig", which is on par with "arc welder".

Shall be repairing of steel ballistic plates also allowed for this station, or "welding tempered steel" must remain a "welding kit" exclusive feature?

**Comment by Drew4484** [comment]
> Another addition to the topic: currently, the **welding 2** quality is also being provided by (craftable from salvageable junk) "[vehicle] welding rig", which is on par with "arc welder".
> 
> Shall be repairing of steel ballistic plates also allowed for this station, or "welding tempered steel" must remain a "welding kit" exclusive feature?

There is also a Vehicle Welding Kit which functions identical to the Welding Kit.

The limitation is not the welding rig, rather the requirements for repairing tempered steel. The process requires a long cooling period under the insulated blanket. Normally this is hours, but we don't apply that time cost for every tempered weld. Just find the blanket and you're set.

**Comment by Alm999** [comment]
Well, this all is fine, even if tertiary… These ballistic plates are not THAT good to start hunting for some blanket.

The main issue remains: currently, the sewing line of tools is listed in the "repair" section, despite the plate not having any of the appropriate materials (it can be fixed only with "Tempered Carbon Steel", even though it is stated in the description that it is also made of "Synthetic Fabric"), as neither needles, nor sewing/tailor's kits deal with steel.

**Comment by utechenko-v** [comment]
I logged a related issue some time ago (currently stalled): https://github.com/CleverRaven/Cataclysm-DDA/issues/61132#issue-1378534051

**Comment by Alm999** [comment]
> I logged a related issue some time ago (currently stalled): [#61132 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/issues/61132#issue-1378534051)

Maybe the issues should be merged together, as one.

On another note, the whole "steel" line of repairs is a mess. The namings are misleading and inconsistent. "Hardened katana", for example, is *stated* to be repairable with "Case Hardened Carbon Steel", but in reality it needs "chunks of low carbon steel", that are are up of "Low Carbon Steel". And so on, and so forth…

I think, the whole system should be reworked/cleaned up so a player could know *exactly* what items are needed, not have some vague hints.
