### ISSUE TITLE
``DIGS`` and ``BORES`` integration

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#63546]
### Is your feature request related to a problem? Please describe.

At the moment ``DIGS`` allows the monster to... well, dig, but the monster is stopped ENTIRELY the second it encounters non-diggable terrain. Such as asphalt. Which roughly translates to - go on the other side of the road and the monster worm the size of a truck can't get to you. Stupid, isn't it? I thought adding the ``BORES`` flag may allow them to tear through the terrain but it did not. Hence I am here.

### Solution you would like.

Allow a monster with both ``DIGS`` and ``BORES`` flags to destroy non-diggable terrain in its path. This would allow stuff like Graboids (and possibly Mole Crickets once we get there) to destroy infrastructure and oh golly that's a hell of a mental image.

### Describe alternatives you have considered.

Possibly additional integration of ``CAN_DIG`` but honestly I think that may be unnecessary considering that flag already handles going over non-diggable terrain.

**Comment by Snaaty** [comment]
Honestly I _like_ that the weird digging worms can't get to me as long as I stick to the roads? It does sometimes make for a fun little run to the next road with weak early survivors, or when carrying too much stuff or when not paying enough attention to dirt mounds. Tbh I thought this was 100% intended behavior.

**Comment by PatrikLundell** [comment]
These monsters are unnaturally capable as is. When was the last time you checked the driving speed of a truck through solid earth, let alone rock? I think the road safe haven is a good thing.

Being the size of a truck might imply strength in some way, but digging truck sized tunnels by pushing the earth to the sides would be a tremendous task that wouldn't be done at running speed.

**Comment by Karol1223** [comment]
> Being the size of a truck might imply strength in some way, but digging truck sized tunnels by pushing the earth to the sides would be a tremendous task that wouldn't be done at running speed.

Nobody ever mentioned running speed. Not to mention that nothing you pointed out solves the underlying issue - digging creatures can't travel past non-diggable terrain. Even if you don't want them to be able to get a person standing on asphalt there is NO argument for them not being able to dig under the asphalt to reach the other side of the road.
