### ISSUE TITLE
Heat Does Not Kill Parasites

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63548]
### Describe the bug

Deep freezing is supposed to kill parasites; however, extreme heat does not appear to do the same, when you load up a tank with meat or human blood.

### Attach save file

N/A

### Steps to reproduce

Make fire. Fill tank with human blood. Place brazier, log, and tank. Ignite and wait 6 hours. Notice how there's no flag saying it's safe to eat.

### Expected behavior

Removal of parasites from extreme heat.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 95521e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

**Comment by Maleclypse** [comment]
OK so am I understanding that you want to extend the "heat cleans water over time" function to include meat?

**Comment by Grubleafeater** [comment]
> OK so am I understanding that you want to extend the "heat cleans water over time" function to include meat?

No, no. I mean, that would be good too, but I'm talking about the 'deep freezing has killed parasites' function.
