### ISSUE TITLE
Butchery morale penalties check for the Trait ID instead of using a flag.

### ISSUE THREAD

**Issue by actually-the-artificer** [CleverRaven/Cataclysm-DDA#63558]
### Describe the bug

When eating human flesh, the morale penalty checks the ID of the trait instead of being linked to a flag. This is problematic for modders who desire to make their own non-human mutation trees.

### Attach save file

[Johnstown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10716032/Johnstown-trimmed.tar.gz)

### Steps to reproduce

1. Unzip the save file.
2. Place unzipped file in save folder.
3. Load up save file.
4. Butcher the human corpse.
5. Observe no known morale penalty.
6. Eat a piece of flesh from the butchered corpse.
7. Observe your non-human character, in this case a slugcat, get depressed upon eating a human.

### Expected behavior

I expect that a non-human creature (no matter how sapient/intelligent) would NOT get depressed upon chowing down on human meat.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: d26a0f4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Rainworld Slugcats [slugcats]
]

### Additional context

"Rainworld Slugcats" is my personal content mod, including a slugcat mutation line for survivors, some Rainworld-sourced items, and the option to play as a dimensionally-displaced slugcat of the rain world.

@Venera3 here is my issue report.

**Comment by Venera3** [comment]
Half the interactions are handled by the JSON character flags, the other half checks for the traits by id - moving to the former only needs replacing the `has_trait` checks with `has_flag` ones and testing.

Self-assigned to remember doing this, but it's a pretty straightforward first C++ issue if somebody wants to tackle it before me.
