### ISSUE TITLE
Kevlar wetsuit recipe contains no Kevlar

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63564]
### Describe the bug

There is no Kevlar in the recipe for the Kevlar wetsuit, except optionally using some Kevlar thread. The same goes for all the varianst - thick, XL, etc.

### Attach save file

N/A, trivially reproducible

### Steps to reproduce

Look at the recipe for the Kevlar wetsuit.

### Expected behavior

An item with Kevlar in the name and material list an explicitly stated to be "padded with layers of Kevlar" should probably require Kevlar to craft.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/218336300-494b07cc-8667-4333-bebc-36581e2b0560.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 95521e0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sky Island [skyisland]
]

**Comment by ZhilkinSerg** [comment]
See #61156

**Comment by anoobindisguise** [comment]
this is because sewing_kevlar doesn't contain kevlar sheets like sewing_cotton_patchwork or somesuch. I don't know how I didn't notice that lol.
