### ISSUE TITLE
Update M 20-32 Mine/Countermine Operations manual to actually instruct on countermine operations

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#63569]
### Is your feature request related to a problem? Please describe.

With the introduction of the proficiencies system, the check for disarming traps has been weighted such that your Trapping proficiency matters far more than your Devices skill. Even with 8 devices skill and no encumbrance, you're still more likely than not to blow yourself up attempting to disarm a landmine if you don't have any relevant proficiency.

This leaves the M 20-32 Mine/Countermine Operations in an awkward position. It only teaches the player up to level 3 devices skill, and the recipes for landmines and booby traps. Not only is this woefully insufficient for actually disarming landmines, a player who has learned everything the book has to offer has little reason to assume such a low level of skill is insufficient before they actually attempt to disarm a landmine, which will likely be the last thing they do with that character.

### Solution you would like.

Implement a Principles of Trapping proficiency practice recipe, and include it in the mine/countermine operations manual. Potentially also include a Trap Setting proficiency training recipe, though whether this would disrupt balance might be worth it's own discussion. Personally, I find it more realistic that someone would learn to set and disarm landmines by reading a US army manual on that exact subject than by placing and disarming 200 nailboard traps.

### Describe alternatives you have considered.

Add the following passage to the description of the M 20-32 Mine/Countermine Operations manual:
"The latter chapters of the book dealing with countermine operations have all been furiously torn out, and "JUST THROW ROCKS AT THEM!!!" has been shakily written in blood on the inverse of the back cover."

**Comment by strategineer** [comment]
I'm taking a look at this!

Any thoughts on what sort of tools (if any) you would need to practice these two proficiencies? Actual explosives seem dangerous :)
