### ISSUE TITLE
Low-tech variant of tree_spile / change tree tapping code?

### ISSUE THREAD

**Issue by merrygin** [CleverRaven/Cataclysm-DDA#63578]
### Is your feature request related to a problem? Please describe.

Tree spiles for tapping maples and harvesting maple sap should be possible to craft with relatively low technology available, i.e., without steelworking. 

It's a technique NE Native Americans used long before settlers arrived, probably using shaped bark or wood as spiles. So a) it makes sense to have it, but also b) seems like a fun addition for more wilderness oriented playthroughs. I originally planned to add it in #61896 but seemed too involved to get finished quickly and since I don't know enough c++.

The main problem is that the tapping functionality of the tree spile is coupled explicitely to the metal "tree_spile" item in iexamine.cpp.

### Solution you would like.

@flybye3o6 suggested on discord (see below) that you could just (mostly?) duplicate the tapping method in iexamine.cpp for a new tree_spile_2 item. This would be a good middle way between the two alternatives mentioned below, but maybe it is unnecessary amounts of additional code?

### Describe alternatives you have considered.

Easiest alternative solution would be to just make a crafting variant of the tree spile and change the description of the item so it doesn't say it is specifically made of metal. Downside is that the items material properties would not be representative of the actual crafting recipe used (you would probably change it from being "material: "steel"" to "material: steel, wood"). So this would definitely be only a provisional change.

Another option would be to totally change the way the tapping works to instead make the code look for an item flag/tool quality when the player examines a maple:

1. Pro would be greater codewise elegance and adaptability for other tapping uses in the future (e.g., tapping pines for tar, tapping birches for sap). 
2. Con would be that actual c++ is needed different than to the other solutions; especially the code for taking away the spile from the tree would need to change.

### Additional context

flybye306's verbatim from discord for future reference:
"you will probably need to make another terrain t_tree_maple_tapped to differ the 2
in iexamine.cpp line 3887  iexamine::tree_maple and line 3929 iexamine::tree_maple_tapped is what you wanna be talking a look at...
you will need the new tree_spile_2 to have a different result, otherwise when you go to take it off your cheap tree spike it turns into the default one. 
you'll need to ask for some help on how to modify the first bit of code as im unsure, but the 2nd bit can just be copied and have the IDs changed you will also need to add static const itype_id itype_tree_spile( "tree_spile_2" ); in line 180 and { "tree_maple_tapped_2", &iexamine::tree_maple_tapped_2 }, in line 6734, and you'll need to make that tree_maple_tapped_2 terrain in data/json/furniture_and_terrain/terrain-flora.json"

**Comment by cake-pie** [comment]
> tool quality

This would be the much better approach and shouldn't be that much harder to do

**Comment by PatrikLundell** [comment]
What about placing the spile on the tree tile, possibly hidden? If so it would be possible to separate the exact tool used for the tapping from the tree's state of being tapped.
Retrieval of the spile should stop the tapping state, and there would be a complication with detection of this happening of the item was picked up directly (as opposed to being retrieved via an interaction).

**Comment by merrygin** [comment]
So a bit like a fishtrap, just that it a) needs a tree tile instead of water and b) spawns sap instead of fish?
