### ISSUE TITLE
Turtlenecks are not hats

### ISSUE THREAD

**Issue by MochaModifier** [CleverRaven/Cataclysm-DDA#63570]
### Describe the bug

'Turtleneck' and 'Turtleneck shirt' causes additional encumbrance when wearing hats (any head clothing or armor on the normal layer)

When rolled, these turtlenecks don't cover the mouth, but still somehow covers the head. 

### Attach save file

[Platte Woods-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10718308/Platte.Woods-trimmed.tar.gz)

### Steps to reproduce

1. Acquire a 'turtleneck shirt' or 'turtleneck shirt (rolled)
2. Acquire any article of clothing or armor that occupies the head (normal layer)
3. wear both
4. character is affected with extra encumbrance from wearing two items on the head (normal layer)

### Expected behavior

Turtlenecks should not occupy the same space/layer as a hat - especially if you roll the neck down. 

When worn correctly, a turtleneck should either cover the torso, arms and neck, or just the torso and arms when the neck is rolled down.

### Screenshots

![image](https://user-images.githubusercontent.com/38334602/218361948-d8579813-b034-458a-8032-f0f0d624a679.png)
![image](https://user-images.githubusercontent.com/38334602/218362033-4a3d8c7b-4339-452b-a3ff-13c11ede7010.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 7216560 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

Recreated issue on a 'Start Now!' save, spawning a random hat, and both turtleneck items.
Used latest experimental version, but issue has existed for some time. Noticed several issues with other common clothing items and layering issues - including bras

**Comment by merrygin** [comment]
Can confirm - turtleneck (rolled) still covers the throat, which technically is part of the head. The problem is likely rather that the cotton hat (and many other hats) just cover the entire head, which technically includes the throat?

**Comment by MochaModifier** [comment]
> Can confirm - turtleneck (rolled) still covers the throat, which technically is part of the head. The problem is likely rather that the cotton hat (and many other hats) just cover the entire head, which technically includes the throat?

I suppose it's just that, there isn't really a 'slot' for the throat/neck, so the turtleneck was extended to cover the head slot?
Scarves and other similar articles of cothing also cover the neck (and would cover more the nape of the neck in some cases) - but these do not cover the head slot.

A turtleneck if anything, should be treated like a shirt that is also a very small scarf - only rolling it removes mouth coverage all together instead of adjusting temperature control. 
![image](https://user-images.githubusercontent.com/38334602/218781356-69c90f74-9b7d-4e0f-b7b2-cd35f0b6e134.png)
I tried to find something that could come close to what Turtlenecks are doing in game - and you could compare this to how a scarf is worn (when covering the mouth)
![image](https://user-images.githubusercontent.com/38334602/218782124-f6b7d204-0c44-4059-ac40-340e9c1fa932.png)

The turtlenecks 'neck' should if anything, occupy the 'close to skin' coverage when compared to a hat. I don't think it's possible for clothing to cover different layers on the body though - this might make sense otherwise. As a shirt, a turtleneck is too loose to be close to the skin like a bra. But as a hat, it's to tight and low to interfere with baseball caps or the like.

And look at the image again - if you pull the neck up high enough that it could interfere with most hats; you now have the problem of covering the eye slot too, and you are now blindfolded by the turtleneck. (I will admit, I have used a turtleneck in this way to sleep while traveling before)

**Comment by anoobindisguise** [comment]
So basically every helmet and hat needs audited to (in most cases) not cover the neck - this is resulting in a loss of coverage for a ton of helmets as without neck coverage you can have at most 80% and many such as a bike helmet or hard hat will have 40-60%. But most helmets don't actually cover the neck, so once that split is made we can have more dedicated neck armor such as gorgets. Though some helmets such as the armet, barbute and tactical full helmet should still cover neck.

**Comment by MochaModifier** [comment]
had lacked the perspective to consider that, but sounds like a fair assessment

**Comment by RenechCDDA** [comment]
/confirmed

For turtlenecks specifically the straightforward way to resolve this is to remove head coverage. But in general the differentiation of the neck as a sub-part (for coverage, as mentioned above) would probably be ideal.
