### ISSUE TITLE
Have literacy be a proficiency? 

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#63577]
### Is your feature request related to a problem? Please describe.

I feel like literacy suits the proficiency-system perfectly, as such I am interestend if it could be transformed to be part of that system. Literacy is not a static skill, it is easily improved and once a certain level is reached, it is generally easy to maintain.

This would allow for characters to start illiterate, yet gain literacy through studying with special practise-reading books. I imagine perhaps one proficiency for "basic literacy" and one for "advanced literacy", with basic being a requirement for reading any books and advanced boosting the reading times especially of advanced books. 

Most characters would start with at least basic literacy, so I suppose there is a certain risk of adding a bit of bloat, which I see to be the biggest point against adding literacy as a proficiency. 

### Solution you would like.

a) proficiency "basic literacy": 
- trained by special reading-learning books
- requirement to read any books at all
- medieval peasant start starts without this, otherwise arguably most character starts start out with this proficency known

b) proficiency "advanced literacy/speed reading": 
- trained by reading difficult books, perhaps more so through special speed-reading guides
- Makes reading difficult books faster
- Backgrounds with highly educated characters would start with this
- Some overlap with the "fast reader" trait, I think it makes sense to have this be a "trainable" trait though, as that is also the case IRL

### Describe alternatives you have considered.

Keep literacy trait-based to avoid proficiency bloat.

**Comment by anothersimulacrum** [comment]
The current illiterate trait represents unwillingness or incapability of learning to read. A low cost 'never learned to read' trait could be available to which this system would apply.

**Comment by anothersimulacrum** [comment]
Closing as stale.
