### ISSUE TITLE
Magiclysm New Character Duplicate definition bug

### ISSUE THREAD

**Issue by Silversnake555** [CleverRaven/Cataclysm-DDA#63588]
### Describe the bug

 This occurs even if all mods are disabled except base DDA and Magiclysm

DEBUG    : Error: mon_mirror_image (mtype) has two definitions from the same source (magiclysm)!

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 986
 VERSION  : 88fbd38

### Attach save file

N/A since no save can be created

### Steps to reproduce

1.Create World and include Magiclysm
2. create ne wcharacter

### Expected behavior

Character Creation menu would open up, but it didnt

### Versions and configuration

Windows x64 latest experimental

**Comment by GuardianDll** [comment]
It should not be a thing, as there is only one mon_mirror_image definition in the magiclysm. Try to update your game?

**Comment by Silversnake555** [comment]
I am already on the latest experimental, will try downloading the not-yet-committed version and check
(though I tried to use a fresh config/ game folder etc it didnt help)

**Comment by GuardianDll** [comment]
I'll try it check later, but there was 0 magiclysm updates in last.. weeks or so, and i started with a fresh copy of the magiclysm few days ago, and got no errors at all

**Comment by Silversnake555** [comment]
I used 7z to extract again and now it's working
sorry for wasting your time
