### ISSUE TITLE
Fridge upon deconstruction and placing becomes immune to damage type it was previously destroyed by

### ISSUE THREAD

**Issue by Feniks-Gaming** [CleverRaven/Cataclysm-DDA#63598]
### Describe the bug

If you disassemble a [refrigerator furniture item](https://nornagon.github.io/cdda-guide/#/furniture/f_fridge) then go into the construction menu and set it back down as an [fridge appliance](https://nornagon.github.io/cdda-guide/#/vehicle_part/ap_fridge) it becomes impossible to damage it with pipes or planks even though you could when it was still furniture.

### Attach save file

[Hosmer-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10737388/Hosmer-trimmed.tar.gz)

Here is a safe file. I am in my base next to my indestructible fridge 

### Steps to reproduce

Go to any house with a fridge
Disassemble it it either using disable furniture or [e] menu
Go to building menu
Place down the fridge
Take a plank or a pipe and try to break it. 

### Expected behavior

Fridge breaks as it would otherwise prior to being reassembled. 

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 170527d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

It has been confirmed on reddit as existing issue by other player more info in this post https://old.reddit.com/r/cataclysmdda/comments/10ww322/new_players_come_here_weekly_questions_and/j8k0hvw/?context=3

**Comment by Raikiri** [comment]
what on earth is "male damage"?

**Comment by DSeyka** [comment]
Heh, it's "melee damage", I presume.

**Comment by Feniks-Gaming** [comment]
melee stupid autocorrect.
