### ISSUE TITLE
Enchantment PAIN has no impact

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#63596]
### Describe the bug

As far as I can tell the enchantment PAIN has no impact.  I've set enchantments using both negative and positive numbers and the enchanted character continues to heal from 44 pain to 32 pain in 1 hour no matter how I adjust the enchantment and reset the world.

### Attach save file

[Aftershock Injection test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10736685/Aftershock.Injection.test-trimmed.tar.gz)

### Steps to reproduce

Create a world with aftershock
debug in a cbm testing character
install chemical injection rig cbm 
cause 44 pain 
turn on pain suppression cbm power
wait 1 hour
see 32 pain remains.
Test in different ways with different values in `{
    "id": "afs_healing_injection",
    "type": "bionic",
    "name": { "str": "Pain Suppression Injection System" },
    "description": "The chemical injection system and microcomputer that when activated gives a burst of chemicals that allows your blood to work a little harder at stabilizing the body and then flushes your system with a powerful anesthetic that allows you to continue operating at high capacity.  Upon deactivation, the user may experience extreme lethargy, sudden loss of consciousness, among other symptoms that may prove potentially fatal if not in a safe location.",
    "flags": [ "BIONIC_TOGGLED" ],
    "enchantments": [
      {
        "condition": "ACTIVE",
        "values": [
          { "value": "ARMOR_BIO", "add": 7 },
          { "value": "ARMOR_COLD", "add": 5 },
          { "value": "PAIN", "add": 450 },
          { "value": "METABOLISM", "multiply": 1.5 },
          { "value": "REGEN_HP", "multiply": 2 }
        ]
      }
    ],
    "deactivated_eocs": [ "afs_eoc_hangover_healing" ],
    "act_cost": "100 J",
    "react_cost": "20 J",
    "time": "1 m"
  },`
See that nothing you adjust changes anything regarding pain rate.

### Expected behavior

I would expect that something would impact the pain rate either negatively or positively.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1105 (22H2)
- Game Version: 88fbd38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

### Additional context

Could be solved by addressing #62875

**Comment by Owlfren** [comment]
Confirmed, PAIN does not make a difference.

**Comment by andrei8l** [comment]
It only exists in an enum with no other associated code.
<details>
<summary>These enchantments are also not implemented:</summary>

ATTACK_COST
BONUS_DAMAGE
BONUS_BLOCK
ATTACK_NOISE
SOCIAL_LIE
SOCIAL_PERSUADE
MAP_MEMORY
SKILL_RUST_RESIST
ITEM_DAMAGE_AP
ITEM_WEIGHT
ITEM_ENCUMBRANCE
ITEM_VOLUME
ITEM_COVERAGE
ITEM_WET_PROTECTION

</details>
