### ISSUE TITLE
Cant open the game

### ISSUE THREAD

**Issue by DeCEll-1** [CleverRaven/Cataclysm-DDA#63605]
### Describe the bug

I had some errors while playing yesterday and i ignroed them, it worked but today when i opened it it chashes.
People on discord said attach the config too so here it is:
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10744166/config.zip)

### Attach save file

Since i cant open the game i cant use debug to create the file so here is the world:
[Dunlay.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10744368/Dunlay.zip)

### Steps to reproduce

Open the game.

### Expected behavior

The game to open.

### Screenshots

![resim](https://user-images.githubusercontent.com/70160402/219069764-6fb67d04-9233-4970-bc4e-389cd638aa2f.png)

### Versions and configuration

Windows 10

cdda-windows-tiles-sounds-x64-2023-02-06-0628 (zip files name) (
build type: windows-tiles-sounds-x64
build number: 2023-02-06-0628
commit sha: 908472cac4573948cba92f5f72e13b2a8bc01212
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/908472cac4573948cba92f5f72e13b2a8bc01212
)

Tiles

English

[
  "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "package_bionic_professions",
  "aftershock",
  "blazeindustries",
  "magiclysm"
]

### Additional context

crash.log
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10744607/crash.log)
debug log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10744608/debug.log)
save file
[Dunlay.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10744611/Dunlay.zip)

Thanks.

EDIT my vehicle is gone and i am sure some of the map tiles are corrupted too.
EDIT 2 i save scum with alt f4 if it will help

**Comment by andrei8l** [comment]
A lot of the map files are corrupted but the save eventually loads for me, including with the build you linked. The error looks like the one in #61095 but you're not on Windows 7.

Try the msvc build though.
