### ISSUE TITLE
Crash when generating starting location after previously aborted failed attempt

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#63601]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/170527d6c15564fbfb806d272a69a16976e00c4e/src/mapgendata.cpp#L46-L58

It crashes trying to initialize `default_groundcover` in this constructor.

Callstack:
![grafik](https://user-images.githubusercontent.com/38702195/218911997-ce9a7b26-e56b-4c78-a3b4-b5f986d1e99f.png)

### Attach save file

n/a

### Steps to reproduce

1. Create a world with city size 0
2. Make a character in the wilderness scenario with desert island starting location and confirm
3. Failed to generate starting location
4. Select "no" when asked to try again
5. Load template from previous attempt (not sure if that's necessary, but that's what I did to reproduce)
6. Change starting location to one of the other options and confirm
7. Crash

### Expected behavior

No crash

### Versions and configuration

Actually did this on the branch from #60885, but due to the nature of the crash I'm very confident it has nothing to do with that. That branch is built on 95521e0ea24b8e59b617d0d65105adb3dd89d48a.

**Comment by aahue1889** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/41269#issuecomment-643844040
- It looks like this is a known issue for the "Desert Island" Feature from the creator.
- Looking into it further.

**Comment by aahue1889** [comment]
I can confirm and repro the issue: Reposting steps here for further clarity.

Create a world with city size 0
![image](https://user-images.githubusercontent.com/8581536/219815650-11a8e85a-2311-4120-ae7a-f23cbbe67dec.png)


Make a character in the wilderness scenario with desert island starting location and confirm
![image](https://user-images.githubusercontent.com/8581536/219815700-8ce31177-71e0-4da2-865b-f6315ff73313.png)

Failed to generate starting location
![image](https://user-images.githubusercontent.com/8581536/219815728-5418fc43-47e9-4b14-9f70-73e0687c5558.png)


Select "no" when asked to try again
![image](https://user-images.githubusercontent.com/8581536/219815753-7b00c70b-6ef2-4194-9d24-edfab7417b09.png)


Load template from previous attempt (not sure if that's necessary, but that's what I did to reproduce)
**Change starting location** to one of the other options and confirm
Crash

----

Will Continue to look into issue thrown below - but can confirm crash

![image](https://user-images.githubusercontent.com/8581536/219816009-42f4afd1-296f-4c3b-a0d9-903b2cd5c2ee.png)

**Comment by aahue1889** [comment]
Potential Fix:
Hitting “NO” executes the else portion of code which DOES NOT flush the MAPBUFFER and Overmap_buffer (I added the highlighted yellow portion of code)
![image](https://user-images.githubusercontent.com/8581536/219903454-b587bf61-9bc7-4942-91fe-28bc09f3647b.png)
![image](https://user-images.githubusercontent.com/8581536/219903459-0b6ec2ee-2680-4d5f-887e-916faf446d87.png)
---

If user later decides to attempt rebuilding the world after making changes to the Starting point; then the logic will occasionally use ‘unflushed’ values from the previous failed attempt to create the world:

Here is an Example of this behavior; a gigantic number was passed to boosted_percent_str which would later cause a failure in other functions 

![image](https://user-images.githubusercontent.com/8581536/219903475-4080ba4f-9e91-49d0-b818-bd0949515926.png)

See a regular session in comparison that does not pass strange  values

![image](https://user-images.githubusercontent.com/8581536/219903488-23673a72-f906-413c-9ee3-6a73bf937517.png)

----

After I made the highlighted changes; I **was able to change the starting location without any crash**

I am now running a few more tests to confirm this as well

----

Separately the below exception

![image](https://user-images.githubusercontent.com/8581536/219903594-57415c9a-c748-4a47-99e1-5bdf4a0a7a80.png)

**I was not able to find an appropriate solution to**; it would require me to wrap my head around how mapgen is working - in particular the logic around Desert Island as a start point. This seems to have been a known issue; https://github.com/CleverRaven/Cataclysm-DDA/pull/41269#issuecomment-643844040

**Comment by mqrause** [comment]
> **I was not able to find an appropriate solution to**; it would require me to wrap my head around how mapgen is working - in particular the logic around Desert Island as a start point. This seems to have been a known issue; [#41269 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/41269#issuecomment-643844040)

The desert island start itself is a separate issue. The relevant issue here is the crash, so if your fix solves that, then it's appropriate.
