### ISSUE TITLE
Reduce number of files (it's over 9000!)

### ISSUE THREAD

**Issue by falcorr** [CleverRaven/Cataclysm-DDA#63613]
### Is your feature request related to a problem? Please describe.

There are currently something like 9000 (!) files in the C:DDA installation. If you're extracting the archive or moving these files around on a conventional drive, it's _a huge, time-consuming pain_. This is especially a concern given the rapid pace of development and the need many feel to update the game.

### Solution you would like.

Please reduce the number of files drastically, e.g. by keeping most of them in archives the game accesses at runtime, or whatever creative wizardry comes to mind.

**Comment by leemuar** [comment]
> it's a huge, time-consuming pain

Please provide time measurement of these operations on you machine and you machine's specs

**Comment by kevingranade** [comment]
I second the request for supporting information.  In addition to actual time spent,  please outline the exact operations you are performing and pertinent details such as OS version.

**Comment by Zireael07** [comment]
Not OP, but I can tell you copying a new install to an USB stick on a laptop couple years old (8 GB RAM, 3Ghz processor IIRC, HDD drive) took AGES. As in, upwards of 10 minutes, and that was a long time ago, when the number of files involved was smaller.

(I did quite a lot of that, as well as deleting, as that was before launchers, and I always kept at least the one previous version if not two, in case)

**Comment by leemuar** [comment]
Idea to discuss: compile several JSON files on the same directory level to a single file.
Knowing how JSON loading works it might do the trick. But it need more research to not break objects dependency and loading order.
