### ISSUE TITLE
Invalid enum string 'SIGHT_RANGE'

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#63616]
### Describe the bug

 DEBUG    : Failed to read from "./save/Magic Island/#TmlraQ==.sav": Invalid enum string 'SIGHT_RANGE' for 'enum enchant_vals::mod'

 FUNCTION : read_from_file
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\cata_utility.cpp
 LINE     : 422
 VERSION  : f0927ac

Caused by #63562

### Attach save file

[Magic Island-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10755061/Magic.Island-trimmed.tar.gz)

### Steps to reproduce

1. Make a save with base game and Magicalysm mod on game version prior to #63562
2. Spawn and equip any enchanted item.
3. Update the game
4. Load saved game

### Expected behavior

Game loads

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 170527d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm],
    Sky Island [skyisland]
]

**Comment by GuardianDll** [comment]
Interestingly, vanilla and in repo mods do not use this enchantment, same as sky island mod. Wonder where you found it

**Comment by RDru** [comment]
> Interestingly, vanilla and in repo mods do not use this enchantment, same as sky island mod. Wonder where you found it

I started this run at build 2023-02-05-0608

**Comment by RDru** [comment]
I wouldn't post a bug report it this could be ignored :) 
Ignoring the error returns to main screen.

**Comment by GuardianDll** [comment]
oh hell
@Ramza13 Do we have any way to obsolete enchantment?

**Comment by Ramza13** [comment]
Oh wait the sky mod isn't in repo so I didn't update it.  Hmmm I'm sure we can add something to at least just warn you and then ignore it or something

**Comment by GuardianDll** [comment]
Sky mod do not use this enchantment also

**Comment by RDru** [comment]
This bug is from Magicalysm items. Dropping all enchanted items allows for save to load but deletes all those items.

**Comment by Cenness** [comment]
> This bug is from Magicalysm items. Dropping all enchanted items allows for save to load but deletes all those items.

Any item with relic_data will trigger it.

**Comment by anoobindisguise** [comment]
Can confirm. In order to load my save (I had about 800 instances of MAP_MEMORY and RELIC_DATA across 8gb of savefile) I had to delete all those entries.
