### ISSUE TITLE
Weather/environmental system improvements.

### ISSUE THREAD

**Issue by Asmitha90** [CleverRaven/Cataclysm-DDA#63620]
### Is your feature request related to a problem? Please describe.

Weather system is an untapped resource for this game, but there are some factors that are limiting it. I'm suggesting some small improvements to help making new weather types/environmental conditions

### Solution you would like.

Options that would help a lot:
-Being able to tie/limit weather to a specific tile type, building, etc.
-Being able to tie weather to a specific season.
-Being able to tie, weather to day/night only.

### Describe alternatives you have considered.

dk, mayby someone smatert can come up with something better.

**Comment by ehughsbaird** [comment]
It looks like weather can take arbitrary conditions to run, so most, if not all, of this should be possible https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/WEATHER_TYPE.md.

**Comment by ZhilkinSerg** [comment]
Yes, basically everything is already supported through `condition` attribute and it just need implementation of new weather types:

![image](https://user-images.githubusercontent.com/16213433/219501690-748672ad-c269-42ef-a471-572f4b9d3233.png)
