### ISSUE TITLE
10mm auto guns can't be loaded with .40 S&W

### ISSUE THREAD

**Issue by T-rexsuper1** [CleverRaven/Cataclysm-DDA#63626]
### Describe the bug

There currently is no way to load .40 S&W in a 10mm auto magazine. Found this issue in Colt Delta Elite 10mm, but it probably exists on other 10mm auto guns. 

### Attach save file

Don't think a save could help solve the issue

### Steps to reproduce

1. Get your hands on a empty 10mm auto handgun magazine and some .40 Smith and Wesson rounds. 
2. Try to load the magazine with the rounds you have and be met with nothing

### Expected behavior

I expected my 10mm auto Colt Delta Elite to be able to chamber and fire the .40 S&W handgun cartridges I looted from a zombie cop.  

### Versions and configuration

Windows 10
[Cataclysm-DDA experimental build 2023-02-15-0620]
No mods
Chibi Ultica 

### Additional context
People often run 40 smith and wesson in their 10mm handguns and smgs with no issues. It is absolutely possible and causes no issues for the gun.
_No response_

**Comment by ArahnaBytes** [comment]
> People often run 40 smith and wesson in their 10mm handguns and smgs with no issues.

Because they swap barrel specifically fitted for much shorter .40 cartridge and some times swap recoil spring with magazine too?

**Comment by T-rexsuper1** [comment]
> > People often run 40 smith and wesson in their 10mm handguns and smgs with no issues.
> 
> Because they swap barrel specifically fitted for much shorter .40 cartridge and some times swap recoil spring with magazine too?

No. That's the thing, they swap nothing. Look it up.

**Comment by T-rexsuper1** [comment]
> > People often run 40 smith and wesson in their 10mm handguns and smgs with no issues.
> 
> Because they swap barrel specifically fitted for much shorter .40 cartridge and some times swap recoil spring with magazine too?

![image](https://user-images.githubusercontent.com/30936470/219942944-5e75dfb9-f606-44d7-925d-642993219111.png)

**Comment by RenechCDDA** [comment]
Quora(your image is of https://www.quora.com/Is-it-safe-to-shoot-a-40-S-W-from-a-10-mm-pistol) is not an acceptable source. (Any 'source' which consists of unqualified, unvetted individuals posting whatever they like is never going to be acceptable.)

If you have other details to support this, such as manufacturer statements, operating manuals, etc. please provide them.
