### ISSUE TITLE
Failed to play sound effect: Tried to play a chunk with a bad frame id

### ISSUE THREAD

**Issue by Draconus-1993** [CleverRaven/Cataclysm-DDA#63632]
### Describe the bug

The crash consistently when approaching bandits

### Attach save file

[Quakertown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10768354/Quakertown-trimmed.tar.gz)

### Steps to reproduce

1 - go est following the road until yoy get closer to the bandit showed in the map
2 - crash

### Expected behavior

you should not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: c571723 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    Owlfren's Map Additions [owlfren_mapping],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by ZhilkinSerg** [comment]
Which soundpack do you use?
