### ISSUE TITLE
Split boots and gloves from hazmat and activity suits

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63631]
### Is your feature request related to a problem? Please describe.

The hazmat and activity suit (including Hub 01 jumpsuit) exist as integrated garments that cover every part of the body except the face. This causes significant problems for mutants, because the activity suit is pretty much the only practical acid/electrical defense in the game, and even a single equipment-restricting mutation will completely prevent them from using it.

It's also unrealistic. I haven't done extensive research, but looking around the internet I cannot find a single example of a hazmat or CBRN suit that doesn't have the gloves and boots as separate pieces. Sometimes even the bodysuit isn't one piece.

### Solution you would like.

Take the gloves and boots off the hazmat/activity suits and make them separate items. This would still leave Huge mutants and those with certain mutations like horns in the cold, but it would give less extreme mutants with paws or hooves a lot more leeway.

### Describe alternatives you have considered.

Allow players to modify or craft from sratch XL activity suits. This would also adress the problem, but it doesn't make a tremendous amount of sense. I don't know a lot about hazardous material protection, but I have to assume it would be difficult to modify by hand without compromising its effectiveness, and I have no idea if it would be possible to make from scratch.

Another option would be to introduce some craftable middling, hazmat-ish gear. Counterintuitively, the most important factor in resisting acid is actually environmental protection, and there's a huge gulf between normal, non-hazmat armor which sits at around 3 and does basically nothing, and the activity suit at 20 which offers complete immunity. Something approximating a [military CBRN suit](https://cqc.co.uk/cbrn/cbrn-oversuits/) that's resistant but not immune (10 env. or so?) with XL variatns wouldn't go amiss. But then someone would have to research and implement that from scratch. Plus, it would still make sense to split the hazmat suits anyway, so it's not like we can't do both.

### Additional context

Obviously not getting in under the freeze(s), this would be for after 0.G

**Comment by Raikiri** [comment]
Honestly if I was a mutant with horns and I found an activity suit, I'd just say "screw that" and just cut holes in the hood. Even if that compromises my protection a bit, it's still much better than not wearing it at all.

I feel like right now mutants are unrealistically punished for having mutated physiology to the point of not making any sense.

**Comment by Terrorforge** [comment]
I actually disagree. In most ways, the game is if anything too generous to mutants. E.g. for most headgear, you don't even have to cut holes to fit your horns. You just craft the XL version which has exactly the same stats as the normal version and go on your merry way.

It's just that this particular problem is omnipresent and has few other practical solutions, so it's a pretty major buzzkill.
