### ISSUE TITLE
Recharging power grid by gas oven

### ISSUE THREAD

**Issue by showervic** [CleverRaven/Cataclysm-DDA#63649]
### Describe the bug

When using oven connected to a grid it recharges the grid battery, so there is possibility to create power from nothing.

### Steps to reproduce

1. Create power grid with connected battery, solar panel and gas oven 
2. Use oven, i.e. for heating up food
3. See major grid battery charge level increase. Tops empty large storage battery after 1-2 uses of oven

### Expected behavior

No jump in grid battery charge level

### Versions and configuration

Windows 10

### Additional context
related 
https://github.com/CleverRaven/Cataclysm-DDA/issues/62511#issue-1471496858

**Comment by andrei8l** [comment]
Can't reproduce. Why not provide the save file?

[output.webm](https://user-images.githubusercontent.com/68240139/219857310-556c1df1-e155-474b-a0de-159b515fab3c.webm)

**Comment by andrei8l** [comment]
/confirmed Happens on `Use Oven` rather than crafting

[output.webm](https://user-images.githubusercontent.com/68240139/219857469-bcf792a9-54b5-4a4b-b56f-3b5abd4b47f8.webm)

**Comment by showervic** [comment]
Pretty sure its reproducible. Saw it in 2 games at least.
