### ISSUE TITLE
Ninjas need ninjutsu

### ISSUE THREAD

**Issue by AkdoolTheSlimy** [CleverRaven/Cataclysm-DDA#63648]
### Is your feature request related to a problem? Please describe.

I tried the ninja profession, as expected of a weeb like me. However, I couldn't help but notice that ninjas don't even get ninjutsu. This displeases me.

### Solution you would like.

Ninjas should be able to ninjutsu. This would please me.

### Describe alternatives you have considered.

You can nerf the class if you want. Remove light step. Increase the point cost. Do what you gotta do, I'm not the balance guy. I don't know what's broken. I just know these current ninjas are phonies!

**Comment by Termineitor244** [comment]
You can add the martial art with the appropriate hobby. I added the profession and decided against including ninjutsu so you can roleplay as either a real ninja, trained in ninja arts, or some random dude very fixated into ninja cosplay, whatever fits your needs.

**Comment by AkdoolTheSlimy** [comment]
Fair enough. I thought it was a little odd, since the two are usually directly linked (it's in the name!), and ninjutsu works perfectly with the katana you start with. I see where you're coming from, though. Open ended also makes sense. Come to think of it, you could use it to start a pc who uses Niten Ichi-Ryuu this way.

Unrelated, but thanks for adding the profession! I feel like previous versions lacked professions using historical weapon styles (like this or HEMA), so it's nice that someone's filling in some of those gaps.

**Comment by Termineitor244** [comment]
You're welcome! I actually added it as part of several cosplay professions (cheerleader? Patriot? The death itself?), but professions using these types of weapons could definitely find a niche with them, a medieval knight works as both cosplay and provider of more historical weapons for example.
