### ISSUE TITLE
Not enough strength to remove vehicle part, while having a higher strength

### ISSUE THREAD

**Issue by stasalcatraz** [CleverRaven/Cataclysm-DDA#63658]
### Describe the bug

My character has 9 strength and can not remove cargo space from flatbed truck (require 8 strength).

### Attach save file

[Wyndmere-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10775172/Wyndmere-trimmed.tar.gz)

### Steps to reproduce

1. Make character with 8 or more strength.
2. Spawn a hacksaw.
3. Spawn a vehicle with cargo space (e.g. Flatbed truck).
4. Try to remove cargo space.

### Expected behavior

I expected that cargo space would be removed

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: d24dd45 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    No Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by irwiss** [comment]
Your hands are hurt so your lift strength is lower than the strength stat, the linked PR should add a hint for this
