### ISSUE TITLE
Melting frozen liquids in pants causes segfault

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#63659]
### Describe the bug

Putting melting items in pants causes a segfault (frozen water, frozen milk, etc).

### Attach save file
[Bechtelsville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10775255/Bechtelsville-trimmed.tar.gz)

### Steps to reproduce

- Put frozen milk item in your pants (don't ask me why)
- Wait for it to melt
- Game crashes

See attached game file. Pass a few turns to trigger the crash.

### Expected behavior

Soggy pants

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.10; Release: 22.10; Codename: kinetic; 
- Game Version: d2a681e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10775252/crash.log)

[Bechtelsville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10775251/Bechtelsville-trimmed.tar.gz)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10775253/debug.log)

**Comment by andrei8l** [comment]
/confirmed trivial error

```diff
diff --git a/src/item_pocket.cpp b/src/item_pocket.cpp
index 0d0dd987a9..0def692023 100644
--- a/src/item_pocket.cpp
+++ b/src/item_pocket.cpp
@@ -1784,12 +1784,12 @@ void item_pocket::leak( map &here, Character *carrier, const tripoint &pos, item
                     continue;
                 }
                 pocke->add( *it );
-                contents.erase( iter );
+                iter = contents.erase( iter );
             } else {
                 iter->unset_flag( flag_FROM_FROZEN_LIQUID );
                 iter->on_drop( pos );
                 here.add_item_or_charges( pos, *iter );
-                contents.erase( iter );
+                iter = contents.erase( iter );
                 carrier->add_msg_if_player( _( "Liquid leaked out from the %s and dripped onto the ground!" ),
                                             this->get_name() );
             }
```
needs a test unit
