### ISSUE TITLE
relic_data ignored on old items

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#63670]
### Describe the bug

relic_data on equipped item ignored after updating from 2023-02-15-0620 to 2023-02-19-0652

### Attach save file

[relic_data.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10776920/relic_data.zip)
Save is from step 5

### Steps to reproduce

1. Make world with Magiclysm on 2023-02-15-0620 or older game build
2. Make a character, note it has 1000 mana
3. Spawn and equip ring of wizardry, notice that max mana raised to 1800
4. Update game to 2023-02-19-0652
5. Load save, ignore/continue on warning, notice that max mana is at 1000
6. Spawn a new ring of wizardry - you now have one ring that works and one that doesn't

### Expected behavior

Items with relic_data to continue providing effect

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 05b28a6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

### Additional context

Probably result of a https://github.com/CleverRaven/Cataclysm-DDA/pull/63655

**Comment by RDru** [comment]
I can confirm this. All relic items don't do anything after update.
#63616
