### ISSUE TITLE
Paid bounties for implementing certain features

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63686]
### Is your feature request related to a problem? Please describe.

I'd like to be able to financially motivate implementing certain features. I'd like to be able to add money either for implementing milestones of certain features or to be able to support certain developers that are working on particular features that I'm interested in directly.

### Solution you would like.

One hypothetical implementation can work like this:

1) I create an issue with a bunch of milestones, then ask the core team for permission to assign a bounty to it. If the core team gives me the green light, I proceed.
2) I assign a certain amount of money for each milestone.
3) I transfer upfront the amount of money for all milestones combined to a bank/pot that's maintained by a trusted 3rd party developer. Ideally this should be a developer not directly involved in implementing the said feature, but well-known in the community. For example Kevin or Erk.
4) Ideally I want other people to be able to add their own contribution to these milestones if they feel like they want to support the initiative.
5) If somebody implements the said milestone, they're paid from the pot by the maintainer mentioned above (Kevin or Erk). 
6) If the issue expires or it's no longer relevant, I get refunded whatever is remaining in the pot, minus commission.

### Describe alternatives you have considered.

Directly supporting individual developers with patreon or similar services.

### Additional context

It's important to note that once I send my bounty, I'm fully trusting the dev team to manage it. They will decide when my milestones are completed to avoid any conflicts. 

Hopefully there's a pre-existing service that could offload some stages of this process in a centralized way.

**Comment by RenechCDDA** [comment]
Already exists. https://app.bountysource.com/teams/cataclysm-dda

Money is not really an effective motivator, at least not in the amount anyone is willing to put up.

**Comment by Raikiri** [comment]
@RenechCDDA interesting. One thing that I immediately see is that there's no direct connection from the github issue to the bounty. If it said right in the title that there was a bounty, it could motivate more people to both support it and to implement it. Another problem that I see is that people seem to randomly fund their own issues that sometimes don't seem to make much sense. I think there should be some sort of an approval process from maintainers to "greenlight" that it's an actual issue and that its solution can be actually merged.

**Comment by RenechCDDA** [comment]
It is in fact in the title, too. Take for example 49472 - [NPC] Allow allied NPC's to be tasked to complete nearby "craft in progress" items [$50]. There is also a github tag: https://github.com/CleverRaven/Cataclysm-DDA/labels/Organization%3A%20Bounty

The payout process already includes this. Per their FAQ:
```
When a bounty claim is submitted by a developer, the claim is put into a two week verification period. Backers are notified by email and can then accept or reject the claim.

If all Backers vote to accept the claim, it is processed immediately and the developer is awarded the bounty.
If any Backer fails to accept the claim, it remains in the two week waiting period.
If any Backer has an issue with the claim, they can reject it. Claims cannot be paid out until the dispute is resolved and the rejected status is lifted.

**Comment by Raikiri** [comment]
You're right, I didn't notice the label. Bounty at the end of the issue name is almost invisible. I also don't like how that website manages disputes with "if any backer fails to accept the claim". Screw that, the more backers there are, the higher the chance that somebody will reject the claim. It should be another person deciding when a given issue is done.

**Comment by RenechCDDA** [comment]
It is up to the CleverRaven team to merge such solutions in the first place, so they do have ultimate say in whether a given solution is accepted.

Bountysource has been the service used by CleverRaven for all previous bounties that I am aware of, so if you have an issue with how they handle disputes it would probably be best to take it up with them.

**Comment by kevingranade** [comment]
I'm not handling anyone's money directly,  and I'm not endorsing a solution where anyone else does either,  it's irresponsible. The path forward is find us a bounty handling service better than bountysource.
I'll also note that the results of having a Bounty solution in place for many years have been at best marginally positive,  so don't expect people to put a ton of work into something with a checkered track record.

**Comment by Raikiri** [comment]
I could argue that maybe the results were marginal at best _because_ the service is subpar and its integration with github (or reddit!) could be better.

What I want to safeguard against is a situation where a user creates a bounty for a feature that they want, somebody jumps on it and makes a pull request, but then it turns out that the feature is actually unwanted and no solution would be ever merged. That's why I think it's important to have a process of "greenlighing" an issue or a feature by one of the maintainers to basically say "yes, we don't mind this being a thing. go ahead and fund it if you like".

**Comment by Zireael07** [comment]
Should not be autoclosed imho

**Comment by kevingranade** [comment]
This is not something we are actively pursuing. If you have a *much* better service to recommend feel free to open an issue about that,  but this is not actionable.
