### ISSUE TITLE
Error message when triggering Summon Shadows artifact effect

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#63684]
### Describe the bug

When activating an artifact with the "Shadows form around you" active effect, the game returns an error message. Occasionally a couple shadows will spawn, but typically none will.

### Attach save file

[Warden_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10779148/Warden_2.zip)

### Steps to reproduce

1. Obtain an artifact with the summon shadows active effect. 
2. Activate it.
3. Observe error message.

### Expected behavior

Shadows should be summoned without generating an error message.

### Screenshots

![image](https://user-images.githubusercontent.com/19789267/220000317-7af3d624-7a76-4e5d-a855-e1e5ff9f4959.png)
![image](https://user-images.githubusercontent.com/19789267/220000538-54a3fddf-2b9f-4aa8-9cc4-11c3d19ed914.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: 05b28a6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Apologies for the nested archives on the save file, it's 1mb over the upload limit in zip form and Github doesn't accept .7z files.

**Comment by anoobindisguise** [comment]
Are you doing it during the day? Shadows die instantly in the day while outside. That could be why the error is happening and would be worth testing.
