### ISSUE TITLE
Black screen and crash to homescreen 

### ISSUE THREAD

**Issue by Saintblizzard** [CleverRaven/Cataclysm-DDA#63698]
### Describe the bug

When opening the app, there is a 75% chance of instant crash to homescreen

Upon loss of app focus, returning to the app renders the screen black while inputs still work 

### Attach save file

In additional files

### Steps to reproduce

Opening the app should reproduce the error

Returning to the app should properly work

### Expected behavior

I expected to be able to play the game and put my phone on standby to return to the game later without having it lose focus

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: ELE-L29; Release: 10; Incremental: 10.1.0.150C431; 
- Game Version: c7738a5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[additional files.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10787836/additional.files.zip)

**Comment by Saintblizzard** [comment]
Reinstalling seemed to have fixed issue, however, upon first start up I did not select the software rendering option (which I did select with prior installation), might be what caused the crashes prior to reinstalling

**Comment by AnotherSeawhite** [comment]
Can confirm. The game can either segfault crash or go black screen with software rendering on.
