### ISSUE TITLE
EMP Scenario

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#63708]
### Is your feature request related to a problem? Please describe.

i wanna play a world where all electronics on the surface start out fried and have frequent/constant weather that causes EMP and any new unshielded electronics brought up to the surface will be fried

i want electricity off the table for most of the game but still have a means of using it eventually 

if the player wants to use electricity they will have to build their base underground and ether find an unbroken generator underground(very rare) or rebuild one just like they will have to do for most other appliances and items, solar will be completely unusable

light above ground will need to use things like fire, flares, and glowsticks, no more flashlights and all batteries are empty
vehicles will need to use non-electric power sources, maybe an engine mod that allows combustion engines to work again without power, steam engines would make a comeback to provide mechanical power which could also run some appliances (drills, saws, ect)
microwaves would be the go to appliance to look for when looting, they are a faraday box and could have a slim chance someone left some goodies in 1, also they can be modified for transport by cutting off the plug and fraying out the grounding wire and letting it drag across the ground

EMP protection will work by having 2 things, grounding wire that goes to the soles of your feet or hangs off your belt and drags on the ground behind you, and faraday coverings, could just be pouches covered by it or a backpack with a grounding wire attached so you can throw it on the ground and it'll still work or your wearing a faraday suit and all pockets within are protected, faraday and grounding wire needs to be made out of conductive metals iron, copper, aluminum, silver, gold, brass

disassembling fried electronics should yield no useful components(circuits, processors, ram, power converters, ect) materials like solder, copper wire, plastic should still be recoverable, making finding intact electronics very valuable for disassembly and repair of other devices
high tech EMP shielding materials could be found in labs underground and used to shield your electronics, it could a magic thing that doesn't require a grounding wire but very rare and only enough to protect 1 device
CBMs from my understanding use a different power type so should be unaffected but now you have less power sources to recharge them, can also give you some sort of sickness if used too much on the surface to balance them out

### Solution you would like.

- mod that adds EOC that makes all tiles above zlvl -1 have EMP effect that fries all unshielded electronics

- add more ways to shield your electronics including shielding for vehicles, mostly methods of grounding and faraday covers 

- system to repair fried electronics for those items that cant be rebuilt from scratch, requiring many electronic components almost enough to completely rebuild the device

- disassembly of fried electronics should yield no electric components, replace them with electronic scrap at a highly reduced amount

**Comment by MNG-cataclysm** [comment]
This would best be implemented as a mod of some sort.
