### ISSUE TITLE
Smokes do not trust me

### ISSUE THREAD

**Issue by BoruMaboru** [CleverRaven/Cataclysm-DDA#63715]
### Describe the bug

When I triggered the quest for between bringing the solar panels and deliver propectus to smokes. Suddenly smokes don't want to trade with me.

NOTE : After several debugging, smokes want to trade with me again after completing the 100 jar mission.

### Attach save file

https://send.vis.ee/download/47886e04b079723f/#AmqRxQE26lZzuctLqnrEZg

### Steps to reproduce

1. Do the quest of return prospectus or solar power for smokes.
2. Check the trade option dialogue.

### Expected behavior

Smoke can trade with me again.

### Screenshots

![hate smokes](https://user-images.githubusercontent.com/123331915/220330243-22b0c133-7665-456a-b662-55df94321d43.png)

### Versions and configuration

cdda-windows-tiles-x64-2023-02-21-0336

**Comment by andrei8l** [comment]
I've played through Smoke's mission tree and couldn't reproduce. This needs a save file and/or more info.

**Comment by Zireael07** [comment]
The recent similar issue I recall was due to the user picking up stuff that was the faction's...

**Comment by BoruMaboru** [comment]
> I've played through Smoke's mission tree and couldn't reproduce. This needs a save file and/or more info.

I've added the save file recently

**Comment by andrei8l** [comment]
Your trust with the Free Merchants is `-8` but there's no indication why.
