### ISSUE TITLE
Hits that fail to penetrate armor train dodging

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#63725]
### Describe the bug

![image](https://user-images.githubusercontent.com/59517351/220511460-cd048c6a-cbf2-4437-a8c3-8c3f53fe86ec.png)

### Attach save file

N/A

### Steps to reproduce

1. Wear all full suit of tempered steel plate armor (I also wore a jumpsuit, socks and a ninja hood below it for comfort), including demi-gauntlets, close helm and sabatons.
2. Have 8 in all stats and 0 dodging.
3. Spawn a hulking horror (or a skeletal zombear or something)
4. Spam .
5. Apparently just standing there in that super heavy plate armor while pretty encumbered and letting it absorb damage trains dodging.

### Expected behavior

Require actual dodges or misses. These are direct hits but the armor protects the character, so there is no dodging involved.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-13110-gb96b791cfec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Venera3** [comment]
Confirmed on `99ad23585cf34566cc888474e4d7db6810f16be2` via Debug Invincibility.

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 13 October 2024. Gave myself Debug Invincibility, set dodge to 0, spawned zombie brute. Got several `The zombie brute hits your x, but fails to penetrate armor`, checked that dodge isn't advancing. Closing until reconfirmed.
