### ISSUE TITLE
Instant death by integer overflow if stored kcal > ~2,100,000

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#63727]
### Is your feature request related to a problem? Please describe.

Currently the integer limit to stored calories caps out around this number and causes it to become massively negative if you exceed it, killing you instantly. At that point you would be about 250 kg overweight which is dangerously high although probably not enough to kill you of a heart attack outright. (Note that the game thinks you are over BMI 400 because it calculates BMI incorrectly, you are in reality closer to BMI 100 - see #60597). Regardless of whether that's way more than anyone should ever achieve in the apocalypse it is clearly a bug as an integer overflow is not normal behavior.

### Solution you would like.

There are four solutions I can think of:
a) warn the player if they are above 2 million stored kcal and then cause them to die of a "scripted" heart attack if kcal > ~2,100,000
b) raise the limit on stored kcal somehow (probably not possible without breaking a save)
c) hardcap stored kcal at ~2,100,000 and don't allow it to become bigger than that
d) ignore this "problem" because it is unlikely to matter in normal gameplay.

### Describe alternatives you have considered.

see above

**Comment by PatrikLundell** [comment]
b) ought to be possible by using a 64 bit integer rather than 32 bit. I don't know if (de)serialization supports 64 bit integers, nor if all platforms CDDA is run on do, however.

250 kg overweight is an enormous amount for a human, but might not be for a ursine mutant (a quick search indicate bears can lose a third of their body weight during hibernation), although ursine mutants probably don't hibernate.

**Comment by pjf** [comment]
```c++
if ( stored_kcal > 2100000 ) {
    printf( "Are you *sure* you wish to eat the mint? It's wafer-thin." );
}

**Comment by PatrikLundell** [comment]
I have a guess at what that rather unclear reference to something many likely don't know about might refer to, but it's neither that clear, or helpful to those who might get that part, and many people likely wouldn't know about it anyway.

**Comment by kevingranade** [comment]
C/d
Just cap it, 250kg of dead weight is pretty absurd.

**Comment by anoobindisguise** [comment]
> C/d

What do you mean by this? Cease and desist?

**Comment by Skrassh** [comment]
Implement option C and it's unlikely to be hit in normal gameplay.
