### ISSUE TITLE
Skunks (Mephitidae and the rest of the Musteloidea superfamily)

### ISSUE THREAD

**Issue by Mustelon** [CleverRaven/Cataclysm-DDA#63724]
### Is your feature request related to a problem? Please describe.

[https://upload.wikimedia.org/wikipedia/commons/e/e7/Striped_Skunk_%28Mephitis_mephitis%29_01_%28cropped%29.jpg](url)

While otters and weasels and other musteloid-related species are already represented in the game, there is not just a lack of ferrets and minks and wolverines and other common mustelid and other mammalian and other species of Massachusetts/New England represented in the game so far as of pre 0.G. I also have just noticed from the Hitchhiker's Guide to the Cataclysm by checking it out, that literally no skunks or other Mephitidae species are represented at all in Cataclysm DDA, and quite frankly because Cataclysm: DDA's setting originally originates and/or originated in the New England region of the Northeastern United States of America, the entire Musteloidea super-family is widely under-represented in Cataclysm: DDA.

### Solution you would like.

Adding and coding the data and illustrating tileset art of skunks and other species of the Musteloidea super-family into Cataclysm: DDA.

### Describe alternatives you have considered.

Continuing to play future versions of Cataclysm: DDA without much Musteloidea representation outside of weasels and otters.

### Additional context

https://en.wikipedia.org/wiki/Mephitidae
https://en.wikipedia.org/wiki/Musteloidea
https://en.wikipedia.org/wiki/Category:Mammals_of_North_America

**Comment by Karol1223** [comment]
Briefly checking iNaturalist, which is usually my go-to for animal rarity and presence in a region, we're only really missing skunks, fishers and some less-relevant mustelids like stoats and martens (maybe minks, not sure if we have minks). We already have a weasel, an otter and a raccoon. Wolverines are not present in the region. With ferrets I'm not even sure what you are talking about, they are not a wild animal.
