### ISSUE TITLE
Base Camp projects won't consume resources

### ISSUE THREAD

**Issue by Draconus-1993** [CleverRaven/Cataclysm-DDA#63722]
### Describe the bug

Base Camp projects won't consume resources

### Attach save file

[Quakertown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10797597/Quakertown-trimmed.tar.gz)

### Steps to reproduce

1- go to the main board
2 - start a project supposed to consume resources
3 - the resources are still there
4 - optionally start another project with the same resources that should be now depleted...

### Expected behavior

resources are depleted during the building process

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: c571723 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Arcana and Magic Items [Arcana],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    Owlfren's Map Additions [owlfren_mapping],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
/confirmed

Although there's a huge mess in the storage zone, I reduced it to one tile containing 12 heavy wooden beams and then tried using them for single "Wooden Panel, [made from] Wooden Beams" crafts. The beams were not consumed.

**Comment by PatrikLundell** [comment]
Not exactly surprising that construction crafting is found to be subject to the same problem as regular base camp companion crafting...
