### ISSUE TITLE
Ethanol burner should burn drunk alcohol instead of a fuel tank

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#63734]
### Is your feature request related to a problem? Please describe.

#35339 caused the Ethanol burner to work like the gasoline fuel cell instead of its original implementation (drink alcohol like Futurama) but this is is less realistic. While DEFCs are definitely a real thing and have a hypothetical max efficiency of 96% (much lower in practice) it would not be ideal to have an internal ethanol tank that you fill from outside your body - it would be difficult to pour alcohol in it and would be a needless skin breach and infection risk.

### Solution you would like.

Having the bionic utilize your mouth-hole would be a lot more convenient for the bionic user. If it interfaces with your digestion and extracts the ethanol from the drink into a DEFC (preventing kcal gain from it as well as inebriation presumably since the alcohol is being reprocessed) this would make for a more "realistic" bionic that doesn't involve pouring alcohol into a fuel hatch. Plus it currently accepts non-pure alcohols, so the fuel hatch would likely get contaminated with other stuff mixed into the alcohols.

**Comment by andrei8l** [comment]
> Plus it currently accepts non-pure alcohols, so the fuel hatch would likely get contaminated with other stuff mixed into the alcohols.

As opposed to your stomach/digestive system which only ever contains pure alcohol?

**Comment by Fris0uman** [comment]
No please, this doesn't make any sense. You can put gasoline in a tank but not alcohol?
