### ISSUE TITLE
Quickdraw proficiency 

### ISSUE THREAD

**Issue by T-rexsuper1** [CleverRaven/Cataclysm-DDA#63748]
### Is your feature request related to a problem? Please describe.

I am always frustrated when I see the description of holsters, scabbards and sheaths (etc.) with the words "it takes a bit of practice getting used to" but the game never actually acknowledges the fact that you have experience with those kinds of things. It takes whopping 6 seconds to get your rifle off the sling in your hands which is just a god awful amount of time for someone with 10 marksmanship and 10 rifle skills to have. Here's the proposed solution:

### Solution you would like.

Quickdraw proficiency. The more you draw your weapon from its holster, scabbard, sling or sheathe, the more familiar you become with the steps required to get your gun or knife in hands the fastest. 
Should be about 2-3 tiers of proficiency. Example:
Beginner gunslinger: boosts your time to draw weapons from sling or a holster (scabbard, sheath) by 15%. 
Intermediate gunslinger: 30%
Master gunslinger:50%. 
Numbers are very rough but you get the general idea. 

### Describe alternatives you have considered.

Make dexterity affect draw time I guess. Maybe it already does? Maybe it does but not enough? Still would be pretty neat. 

### Additional context

About realism:
Currently it takes about 600 time units or 6 seconds to take the rifle off the sling which is just not the actual time it takes for people to get their gun in a ready position. With 50% boost 3 seconds is perfectly realistic amount of time for an experienced shooter to take out their rifle. 
With pistols it's similar. Half a second to draw from a holster is reasonable, but fastest hands can do that in under quarter of a second. Why shouldn't our survivor do that with enough practice?

**Comment by DSeyka** [comment]
>The more you draw your weapon from its holster, scabbard, sling or sheathe, the more familiar you become
This seems abusable but I like the idea nonetheless.
