### ISSUE TITLE
Why are bionic slots not in the main game?

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63742]
### Is your feature request related to a problem? Please describe.

Currently there's almost no reason to not have CBM's installed unless you're running aftershock that gives them slot costs. I understand that the ultimate goal is to rework transhumanism on a fundamental level, but for an intermediate stepping stone solution having at least some downsides to installing ungodly amounts of CBM's seems like a much better option than having none limitations at all.

### Solution you would like.

I'd like the aftershock CBM slots to be a part of the main game.

### Describe alternatives you have considered.

Alternatively I guess we can just wait until somebody steps up and implements the new vision of what CBM's are supposed to eventually become, but nobody knows when that's going to actually happen.

**Comment by Fris0uman** [comment]
See this https://github.com/CleverRaven/Cataclysm-DDA/issues/28273 and this https://github.com/CleverRaven/Cataclysm-DDA/issues/16920 the second one is pretty old not sure if it's valid or not.

**Comment by Raikiri** [comment]
Those issues as ancient, and that's exactly why I'm proposing to have at least something already implemented right now: bionic slots, rather than nothing. And then we can take all the time in the world to implement a better system.

**Comment by Nebnis** [comment]
I completely agree with raikiri, aftershock system is more than fine as interim
