### ISSUE TITLE
Too much cattail jelly from mission

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#63754]
### Describe the bug

There is too much cattail jelly rewarded for completing the cattail jelly mission to fit into the zipper bag container, causing an error:
```
 DEBUG    : tried to put an item (cattail_jelly) count (13) in a container (bag_zipper) that cannot contain it: pocket unacceptable because item too big

 FUNCTION : ret_val<void> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1512
 VERSION  : af2fe0d
```

### Attach save file

[TESTING-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10818186/TESTING-trimmed.tar.gz)

### Steps to reproduce

 1. Find an NPC with the cattail jelly mission (evac shelter survivors are the easiest to find and always provide the mission currently)
 2. Take and fulfill the mission requirements
 3. Turn in the mission
 4. Too much jelly

### Expected behavior

The NPC isn't overly generous with jelly

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: af2fe0d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context
Not the same as #44066, which also seems to be resolved now that zipper bags can contains liquids.
_No response_

**Comment by Quintovir** [comment]
I got the error too.

**Comment by Alm999** [comment]
Yep. The same error for me as well.

Can we get the "Confirmed" status on this issue?
