### ISSUE TITLE
We need a flag to supress the experience gain from monsters

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#63750]
### Is your feature request related to a problem? Please describe.

We have a person and a breather, that both work as a punch bag to train your melee skill. Both are sort of illusions, that should not teach you anything. 

### Solution you would like.

Make a monster flag, that do not allow to train melee by attacking this creature

**Comment by Venera3** [comment]
`melee_training_cap` defaults to 10, but it should be what you're looking for. I'm working on setting it automatically but haven't landed on a nice enough calculation yet.

**Comment by GuardianDll** [comment]
Oh yes, undocumented monster field that do exactly what i need. Thank you
