### ISSUE TITLE
[#995] Sourceless pain being inflicted

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#6375]
I haven't really thought much of it, but this seems to have been around for a while now. Every now and then, for no discernible reason, a point of pain will be added. I've started hurting while reading and running. At first, I thought it was just painkiller wearing off, and I'm sure there has been some of that, but there have been definite instances when I just start hurting. And it's not encumbrance pain, either. Is there some sort of hidden function that adds pain with exertion? It would make sense with running, but reading? Not so much.

**Comment by i2amroy** [comment]
After several checks of various pain and painkiller stuff I can't replicate this at all and am assuming fixed in the latest experimental. Should someone encounter this again we can reopen.
