### ISSUE TITLE
Police car's sound is distorted (@'s soundpack)

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63765]
### Describe the bug

Sometimes CDDA plays strange clicking noises during its sound playback. Vormithrax encountered this problem a bunch of times on his streams. I can now repro this problem reliably in any police car when I drive.

### Attach save file

[Boulder Junction-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10824351/Boulder.Junction-trimmed.tar.gz)

### Steps to reproduce

1. Enter any police car
2. Turn on the engine
3. Wait a couple of sound loops
(tried with @'s soundpack)

### Expected behavior

I expect the sound to not be distorted and to not produce clicks.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: c69ea7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This started happening about a month ago, so the problem has to be somewhat recent

**Comment by akrieger** [comment]
#63214 must have reintroduced #61889 which I fixed in #61944. But no build is worse than a clicky build.

**Comment by akrieger** [comment]
Unfortunately #466 is still open.

**Comment by Raikiri** [comment]
i wonder how come it's specifically police cars that seem to be affected the most

**Comment by akrieger** [comment]
So it's actually in both the MSVC and the mxe cross builds. My PR only fixes the MSVC build.
