### ISSUE TITLE
Items with NO_TAKEOFF flag can be taken off by putting in player's bags.

### ISSUE THREAD

**Issue by pedestrian4** [CleverRaven/Cataclysm-DDA#63777]
### Describe the bug

Items with NO_TAKEOFF flag (like Foodperson mask) can be taken off just by inserting it in player's bags.

### Attach save file

N/A

### Steps to reproduce

1. Start a game with foodperson or just generate foodperson mask by debug
2. Turn on that item and make sure player can't take off it.
3. Hold or wear a bag.
4. Select the bag and [i]nsert that item in it.
5. The inner item can be dropped from the bag.

### Expected behavior

It should be not.

### Versions and configuration

OS: Windows 10
Game Version: experiamental 2023-02-23-1227

**Comment by ferociousdork** [comment]
Confirmed. You can also trade it to an NPC and get it off that way.
