### ISSUE TITLE
I think there may be a break in breaking thresholds

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#63779]
### Describe the bug

I've had several tests recently where I was unable to break threshold normally in the Mi-go mutation line and I had assumed that it was a problem with the line and I've started work on a PR to add more mutations in 0.H experimental since I figured that was the issue.  But since then I've noticed a couple of comments about people being unable to go post thresh on other trees.  I'm wondering if we have a widespread breakdown in breaking threshold and I unfortunately won't have access to a computer for the next week to really test this.  

### Attach save file

N/A

### Steps to reproduce

Make character
debug in mutagens and primers.
consume and mutate over time
cross threshold or don't

### Expected behavior

Threshold crossing

### Versions and configuration

recent experimentals

### Additional context

I'm posting this issue as I won't be able to look into it for a few weeks.

Things I've considered. Adding any mutations via mods might break the system and basegame lines work in unmodded games.
All threshold breaking is broken
Or myself and many others don't have the patience to attempt passing the threshold for however many days it now requires.

**Comment by Maleclypse** [comment]
OK tested Lupine, started a new character and debugged in 12 mutagenic catalyst and 12 lupine serum.  Took in 2-3 of each every  time I was no longer warping over two weeks.  Achieved Wolf but watched dozens of times that it flip flopped between gray fur and light fur and having the mutation man's best friend and losing it with no replacement mutation. Removed instability a couple of times but also let it build up to over a thousand several times.   It might be best if if we changed instability to be a roll remainder situation where if you rolled good or bad mutations and were out of pre-threshold good or bad mutations in your category you automatically got the other anyway.  It was definitely frustrating watching the same mutations change over and over again.  I'm going to try and test the remaining categories as well over time.

**Comment by Raikiri** [comment]
Is that because Light Fur and Gray Fur are both positive mutations so the game sees it as fair to give you Light Fur when you already have Gray Fur, effectively regressing it?

I think I noticed similar behaviour in other mutations chains too.

**Comment by Maleclypse** [comment]
> man's best friend and losing it with no replacement mutation
Maybe but that doesn't explain why I also saw a significant amount of shifts between man's best friend and losing it with no replacement mutation.  They may have different causes.

**Comment by Raikiri** [comment]
Man's best friend requires Light Fur as well, maybe that's somehow related? Can you reproduce this problem if you remove Light Fur from its dependencies?

**Comment by Cupidatis** [comment]
I found troubles with manatouched mutations in Magiclysm. Good Mana Regeneration can't be added with this primer and because of this you can't become post threshold mutant.
