### ISSUE TITLE
There is a too little farmland compared to reality

### ISSUE THREAD

**Issue by Sepentine** [CleverRaven/Cataclysm-DDA#63784]
### Is your feature request related to a problem? Please describe.

Realistically if you look at a map Massachusetts its mostly farmland or woodland, there are fields but not as much as in cdda.

### Solution you would like.

 we make a new type of terrain like forest tiles or field tiles but rather farmland, if the crop rows all go the same direction and end at the edge of a map square shouldn't it be possible to make it a terrain type or a map extra to have it cover large areas of land in a semi-realistic manner instead of just a square or fenced in field? and if its a terrain type it wont take up large areas and prevent other spawns like the current large farm are but rather just fill in the empty spots

### Describe alternatives you have considered.

you could make rural mapgen much more dense and just up the spawn rate of farm fields. Or have them spawn on the sides of roads like food carts or gas stations

**Comment by gettingusedto** [comment]
you mean #62037?

**Comment by Sepentine** [comment]
> you mean #62037?

yep, these farms are objectively worse than the ones we had before

**Comment by GuardianDll** [comment]
I don't think NE is a truly farmland world, the Massachusetts itself has only 7% of area covered with farms
