### ISSUE TITLE
Spent Phenotype means instability and I haven't mutated yet

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#63782]
### Describe the bug

I'm gaining instability without having mutated yet.  I have debug mutated debug mutations and if those give instability that would be a problem as well.

### Attach save file

n/a

### Steps to reproduce

take mutagen and primer, wait 6 hours and don't mutate.  See there is instability anyway.

### Expected behavior

No instability til after I mutate.

### Screenshots

![Spent phenotype no mutations](https://user-images.githubusercontent.com/54345792/221335061-d407e0b9-63a5-47ed-84bc-2c64309c6b1c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: 88fbd38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Zireael07** [comment]
Why close?
