### ISSUE TITLE
Gas Mask Filters Duplicating

### ISSUE THREAD

**Issue by LegioVII** [CleverRaven/Cataclysm-DDA#63787]
### Describe the bug

When reloading a gas mask that has been previously unloaded, the filters will "combine"  and be duplicated when the Gas Mask is reloaded. I.E. I reloaded a Gas Mask and had one filter that was 100/100 and one that was 27/100. When I used the option to reload the gas mask, it displayed a filter with 127/100. I selected the option a discovered a brand new 27/100 filter in my inventory along with the existing one. 

### Attach save file

N/A

### Steps to reproduce

1. Get a gas mask
2. Get two existing filters (Unknown if one has to be partially used or not)
3. Unload the Gas Mask
4. Reload the Gas Mask
5. Select that option that shows a number over 100
6. Check inventory for duplicated filters

### Expected behavior

The expected behavior was that I would choose which filter to reload and it would insert that individual filter without duplicating the other one. 

I expect this to happen because Gas Mask filters ideally don't perform mitosis whenever they are inserted into a Gas Mask.

### Screenshots

![GasMaskFiltersMitsosis](https://user-images.githubusercontent.com/113361715/221363827-66ace4c2-84e6-4a40-ae94-ff74f421ceab.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: cb0c155 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth]
]

**Comment by ehughsbaird** [comment]
Could not reproduce on dc8a598f522b2c37805932b1c006dbf66e62f237

![image](https://user-images.githubusercontent.com/44244083/221389353-4197f5f8-95df-405e-8a79-4e1c42da553c.png)
![image](https://user-images.githubusercontent.com/44244083/221389358-636338ba-69cb-49c6-9742-93fb3f80412a.png)
![image](https://user-images.githubusercontent.com/44244083/221389360-a681a5e9-82bb-4982-8cb1-b45ef578faf1.png)
![image](https://user-images.githubusercontent.com/44244083/221389361-b868bda1-0d17-410d-b884-b70556bd96f8.png)
