### ISSUE TITLE
SD card gains weight

### ISSUE THREAD

**Issue by sabnol** [CleverRaven/Cataclysm-DDA#63786]
### Describe the bug

Storing photos on a SD card with previously stored books causes it to gain weight, presumably depending on the amount of stored books.

### Attach save file

N/A

### Steps to reproduce

1. Make a player character with a bunch of books, an e-link tablet and camera
2. Store the books on a e-link
3. Store the books on a SD card
4. Take a photo of something
5. Store the photo on the SD card from point 3

### Expected behavior

i expected that the sd card would normally store both the photos and books

### Versions and configuration

OS: Windows 10
Version: 170527d

**Comment by ehughsbaird** [comment]
Confirmed on dc8a598f522b2c37805932b1c006dbf66e62f237

**Comment by ZhilkinSerg** [comment]
Must be fixed with #65248
