### ISSUE TITLE
Trying to shutdown a hostile nurse bot result in a crash

### ISSUE THREAD

**Issue by Xindage** [CleverRaven/Cataclysm-DDA#63781]
### Describe the bug

During my game i was trying to shutdown a nurse bot so i could rewire it on future but using the dazzle gun on it to try shutdown it result in it grabbing me in the process, if i accept to shutdown it the game freeze and them close in silent.

### Attach save file

[Shelby-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10830097/Shelby-trimmed.tar.gz)

### Steps to reproduce

1. Shot the defective nurse bot with the dazzle gun.
2. Reach the nurse (it'll start to be hostile toward you.
3. Try to deactivate the nurse.
4. The game MAY freeze during it or not, if you successfully disable it, reload the save and try again.

### Expected behavior

Deactive the nurse robot 100% of the times without crash.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 17a7444 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],No Fungal Growth [no_fungal_growth],Bionic Professions [package_bionic_professions],Aftershock [aftershock]]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10830105/debug.log)
There is the log file after loading the save and repeating the steps that i mentioned over there: Keep in mind that its not a !00% chance to crash, from 5 tries 4 crashed 1 does not, so it must be something wrong during the disabling process.

**Comment by andrei8l** [comment]
The save file is bugged due to a dumb bug and I haven't been able to reproduce after multiple tries. Can you please manually archive the folder and re-attach it? (or merge #63783 locally and regenerate)

**Comment by Xindage** [comment]
i'll use my original save so, here:
[Shelby.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10832872/Shelby.zip)
around 17mb of data, my save still allow me to reproduce the bug but i may want to note a extra thing, i have noticed this error happening while my npc is nearby me when the nurse grab it as well.
