### ISSUE TITLE
Soulfire attunement causes passive aoe damage to npcs.

### ISSUE THREAD

**Issue by MoonlitRiverlight** [CleverRaven/Cataclysm-DDA#63792]
### Describe the bug

Soulfire attunement causes passive aoe damage to npcs. This can't be turned off and results in npcs turning hostile.

### Attach save file

N/A

### Steps to reproduce

1. Attune Soulfire.
2. Stand near any entity.

### Expected behavior

Either that aura not existing, being toggleable, or targeting only aggroed mobs.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 05b28a6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Make bows great again [bow_opness],
    XEAS [XEAS],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Add Rice [rice],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Bionics Systems Recipes [bio_recipes],
    Climate Defying Farming [climate_defying_farming],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Culinary Days Ahead [culinary_days_ahead],
    Dried Fruits [dried_fruits],
    No name () [],
    Garden Pots [growable-pots],
    Large capacity storage CBMs [eps_cbm],
    Makeshift Items Mod [makeshift],
    MOD to grow tea leaves [More tea leaf],
    Pixel's Various Fuckery [Pix's Shit],
    The Cool Mod [cool_mod],
    The Glory Of Cereal! [CerealMod],
    Thermal Electric UPS [thermal_ups],
    Bug's life [Bug's life],
    Jury-Rigged Robots [jury_rigged_robots],
    CDDA Variety Pack [ks_variety_pack],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Diluted Mutagens [diluted_mutagens],
    Even More Mutations [even_more_mutations],
    Extra Mutated Scenarios [extra_mut_scens],
    Food Irradiator [food_irradiator],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    More Survivor Notes [more_survivor_notes],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs [mutant_npcs_new],
    NPC Recruitment Options [recruitment_options],
    Tekitou Map Commercial Overhaul [tekitoumap],
    Translate Complex Dialogue [translate_dialogue],
    Vampiric Stuff [vamp_stuff],
    Beta National Guard Camp [national_guard_camp_alt],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    No Rail Stations [No_Rail_Stations],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Sarcophagi Access [sarcophagi_access],
    Ships From Oa Additional Buildings [Ships],
    Water Towers [water_towers],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Merchant Mod [Merchant],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Easy Proficiency [sch_easy_proficiency],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by GuardianDll** [comment]
it can be turned off in recent development version, so fixed already
