### ISSUE TITLE
Indoor Tamed Animals Teleport During Portal Storms; May Die.

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63796]
### Describe the bug

Tamed and tied down animals go missing during portal storms and I tend to find them dead afterwards. This can happen even indoors, it seems(and people on the discord have mentioned that this even happens underground!)

### Attach save file

N/A

### Steps to reproduce

Tame and tie down animals, wait for portal storm.

### Expected behavior

Indoor animals to be safe.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 95521e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

**Comment by Ramza13** [comment]
Is anyone still seeing this?  I spawned up a world and tried to reproduce it and didn't see anything but its possible I'm missing steps or simply unlucky at getting it to happen.
