### ISSUE TITLE
Quickload keybinding lost

### ISSUE THREAD

**Issue by hulu-lu** [CleverRaven/Cataclysm-DDA#63809]
### Describe the bug

I don't know what happened but somehow the game lost the quickload keybinding after version [experimental build 2023-02-25-1926]

### Attach save file

N/A

### Steps to reproduce

Download version [build 2023-02-25-1926] and later version
Open the game and enter keybinding settings
compare the game and you find the quickload disappeared.

### Expected behavior

Have quickload back.

### Screenshots

![Capture](https://user-images.githubusercontent.com/24808189/221421582-0cff5e91-5ee4-40af-b1ad-9110bf10fd22.PNG)

### Versions and configuration

OS: Windows 10 22H2
Game version: [experimental build 2023-02-25-2058]

**Comment by andrei8l** [comment]
Not a bug. See #63767
