### ISSUE TITLE
Having water in a not watertight container on player crashes the game

### ISSUE THREAD

**Issue by teackot** [CleverRaven/Cataclysm-DDA#63807]
### Describe the bug

If water gets defrosted inside a not watertight container in players inventory or if player puts on an item containing such container, the game will crash without any debug messages. 

### Attach save file

[Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10833734/Test-trimmed.tar.gz)

Frozen water is in inventory, game will crash in 15-20 ingame minutes

### Steps to reproduce

1. Put frozen water into a non watertight container (e.g. messenger bag)
2. Stand next to a fire and wait for water to defrost
3. Game crashes

OR

1. Put frozen water into a messenger bag
2. Drop the bag next to a fire and wait for water to defrost
3. Wear the messenger bag
4. Game crashes

### Expected behavior

Water should spill when it gets defrosted in a not watertight container

### Versions and configuration

- OS: Arch Linux
- Game version: 79a4e9f
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, no_fungal_growth, no_hope, translate_dialogue, cbm_slots

**Comment by andrei8l** [comment]
Duplicate of #63659

**Comment by teackot** [comment]
Yes
