### ISSUE TITLE
Ki Strike damage blocked by wearing gloves

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63804]
### Describe the bug

If you have "Ki Strike" and wear any kind of gloves or unarmed weapon, the extra damage from Ki Strike does not get applied. This happens even if the "glove" in question is integrated armor.

Presumably this is a side effect of the changes to unarmed weapons, going from wielded weapons to worn gloves, but I haven't been able to find the exact point in the code where it breaks.

### Attach save file

[MA Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10833334/MA.Test-trimmed.tar.gz)

### Steps to reproduce

1. Give yourself Ki Strike and high Melee/Unarmed skill. Do not wear gloves.
2. Hit some zombies and note the damage.
3. Put on any gloves.
4. Hit some more zombies and note how much lower your damage is.

### Expected behavior

Ki Strike should still work while wearing gloves.

Based on references in the code (melee.cpp lines 1325-1328) Ki Strike is supposed to apply on top of unarmed weapon damage. And just from a gameplay perspective, it would be one thing if it couldn't be used in conjunction with unarmed weapons like skewer knuckles, but you can't wear gloves at all. And obviously it's complete nonsense that it doesn't work with integrated armor.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/221401733-8a358806-23c5-4261-88d9-3b47f78b9f21.png)
This is a character with Ki Strike, 10 in every skill and debug incincibility active. Note how when I put on the tactical gloves (middle of the log) I go from dealing 28 damage on a normal hit to struggling to even reach 24 on a critical.

![image](https://user-images.githubusercontent.com/5107449/221402059-0c92f160-5c3a-4e94-a7cd-10ec369e22e2.png)
Same with integrated armor.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: f1bc060 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA]
]

### Additional context

Thanks to [u/Vrk_](https://www.reddit.com/user/Vrk_/) on Reddit for bringing this to my attention.

**Comment by kevingranade** [comment]
Your test is inconclusive, because ki strike has an explicit bonus for "pure unarmed", so some loss of damage is expected and AFAICT intended. IIRC a str 8 character without the ki strike bonus is going to be dealing low single digit damage when unarmed,  so there's clearly still a bug in play.

In a broader sense, this is a question for @Hymore246 
Ki strike is magic, so it works however they want it to.

**Comment by Terrorforge** [comment]
Right you are. I can't believe I forgot to test without Ki Strike to see the base damage. But now I have, and I can confirm that it still adds ~10 damage (at Unarmed 10) if you're wearing gloves. I was still going to argue it ought to be changed, but the more I think about it, the more I like that it has this weird little caveat.

However, this mechanic doesn't seem to be explained anywhere. If it's intended, it should definitely be mentioned in the Ki Strike description.

Also, it feels unintuitive that the full bonus is blocked by mutated armor. That's your skin, it _is_ pure unarmed. I do actually like keeping it as a benefit for (mostly) human martial artists, but then that should also be reflected in the description.

(I can PR a new description myself, I just need confirmation that the current mechanics are intended and desired.)

**Comment by Terrorforge** [comment]
That would be easy enough to implement as an enchantment effect, more or less as I did for the magiclysm fist weapons in #64193 but reading the player's Unarmed value for the bonus damage. Would have to remove whatever hardcoded functionality Ki strike currently has, though.
