### ISSUE TITLE
Disabling/enabling an entry in the Safe Mode window does not give a visual indicator of any change.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#63816]
### Describe the bug

When I enable or disable an entry I made in the Safe Mode window I see no visual change.

### Attach save file

[Baldwin Park-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10834837/Baldwin.Park-trimmed.tar.gz)

### Steps to reproduce

Enable or disable any entry you have in the Safe Mode window.

### Expected behavior

Enabled and disabled entries in the Safe Mode window should have a distinct color to tell them apart.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.3; Codename: Sikaris; 
- Game Version: 0.F-13409-g7597f1b928 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by strategineer** [comment]
The colors do switch from white (enabled) to light gray (disabled) although it can be very hard to see depending on the color theme:

![image](https://user-images.githubusercontent.com/2420411/228423046-d8032e00-1319-47ce-ad60-338842959364.png)

Green and red might be a better option.

**Comment by strategineer** [comment]
True but we're already using green and red in this way elsewhere in the UI (for example, the keybindings menu) so I'm not sure if using green and red here would be an issue (at least it would be consistent).

The color theme system makes it easy (relatively) for someone with color blindness to customize the colors used by the game to suit their needs.

But there's a point to be made that the default color theme should work for as many people as possible.
