### ISSUE TITLE
Hibernation should actually let you skip a season, like how hibernating animals do IRL.

### ISSUE THREAD

**Issue by actually-the-artificer** [CleverRaven/Cataclysm-DDA#63819]
### Is your feature request related to a problem? Please describe.

I am frustrated when characters with Hibernation cannot actually 'skip a season' like how hibernating animals do IRL. 

### Solution you would like.

Instead of behaving like this, Hibernation should ACTUALLY skip a entire season if the player wants. We should really make a way to cap it so thirst and hunger are sufficient before the player uses this so their character won't starve through the whole winter.

Say the player hibernates on the first day of winter; the game will fast-forward to Day 1 of the next spring. With this mutation, obviously the player can't do things that most characters will do during this time (crafting/reading/etc) which is a fair trade-off I feel.

### Describe alternatives you have considered.

Keep Hibernation as it as.

### Additional context

I dunno how this mutation works currently.

**Comment by ZhilkinSerg** [comment]
Hibernation mutation works as advertised in its description. You should not expect it to skip time.
