### ISSUE TITLE
Cannot fill pre-existing pit after removing a column and rebar.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#63817]
### Describe the bug

After I used a jackhammer to remove a column and sawed off the rebar, the pit that remains cannot be filled with soil.

### Attach save file

[Baldwin Park-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10834960/Baldwin.Park-trimmed.tar.gz)

### Steps to reproduce

1. Use item (a) on the entrenching tool.
2. Press 4 for "Fill pit / tamp ground".
3. Press 9 on the numpad where the pit is.

1. Open the Construction menu (*).
2. Search for "Fill pit with dirt".
3. The option is greyed out and cannot be used. 100 soil is within reach.

### Expected behavior

The non-user made pit from where columns were built should be possible to be filled in with soil.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.3; Codename: Sikaris; 
- Game Version: 0.F-13409-g7597f1b928 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by flybye3o6** [comment]
you dont have enough soil to fill the pit, you have 100 soil nearby you need 350
then you need another 50 soil to fill the shallow pit, so you 400 soil to fill a pit

**Comment by Quintovir** [comment]
OK, thanks.

I didn't notice that the #4 stage wasn't showing and that requires 350 soil.
