### ISSUE TITLE
segfault when dropping all?

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#63827]
### Describe the bug

i just happened to drop everything i had and game segfaulted when i hit enter, a rapid search of latest commits show this as possible cause #63811

### Attach save file

[Emerald Lake Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10838195/Emerald.Lake.Hills-trimmed.tar.gz)

### Steps to reproduce

1. load game
2. hit drop items key -> hit all items except favorites -> hit confirm
3. game crashes

### Expected behavior

no crash

### Versions and configuration

Windows 10
experimental build 2023-02-27-0253
Tiles
English
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "Tamable_Wildlife",
  "stats_through_kills",
  "speedydex",
  "package_bionic_professions",
  "blazeindustries",
  "extra_mut_scens",
  "MMA",
  "translate_dialogue",
  "No_Rail_Stations"

**Comment by harakka** [comment]
Reproduces on current RC at time of writing (https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-02-27-0627), release blocker?

**Comment by andrei8l** [comment]
Fixed by #63811. Forgot to link it
