### ISSUE TITLE
Add defrost option to things that can heat food

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#63830]
### Is your feature request related to a problem? Please describe.

So, my survivor is the type that wants to build a new civilization capable of withstanding what the civilizations of the old world couldn't. Making this happen requires a *looooot* of resources. Some of these resources expire after a while, and many of these resources can't (or at least shouldn't, given the plans for them) be preserved in any way other than freezing them. However, frozen resources tend to be unusable in recipes that don't involve the use of a tool that will heat them up - as such, they need to be thawed beforehand.

Now, thawing these resources could happen in a couple of different ways - one is to leave them in a hot place for a while until they thaw, and the other is to use a tool that can heat food. Both of these methods are flawed, however. For the first one, leaving them somewhere tends to lead to them being forgotten about, which of course means that my survivor will eventually go back to where they are, and realize that there's a bunch of rotten ingredients lying on the floor, making them useless for many purposes. The other method's problem is that it takes too much time out of my survivor's busy schedule, with her having to stand there waiting for things to not just thaw, but get _**hot**_. That, and from what I've been able to tell, heating things up iss an all-or-nothing deal - I can't stop heating things halfway and find that they're at least not frozen, because the heating progress has to go all the way to 100% for it to do anything at all (aside from wasting time and fuel).

### Solution you would like.

I'd like for there to be an option with food-heating tools to simply **_defrost_** frozen foods and other recipe components, which would take less time and fuel, and bring the frozen item to being cold, rather than hot.

### Describe alternatives you have considered.

-Manually making a heat source-dependent copy of every recipe that does not already require a heat source

**Comment by anothersimulacrum** [comment]
Defrost is automatic if the recipe uses a heating tool.

**Comment by AmarinReyny** [comment]
> Defrost is automatic if the recipe uses a heating tool.

Yeah, but not all recipes do.

**Comment by PatrikLundell** [comment]
And, as @AmarinReyny mentioned, some ingredients aren't eligible for use as components when frozen. Some are, but it's inconsistent.

By the way, there is one exception to the "heat until hot" rule, and that's water, where the text states that the heating process is cut short because the character prefers the water cold.

I've used a work around for milk for my characters, and that is to take a bottle of milk from the fridge, drink it, move a bottle of milk from the freezer to the fridge, and then drink that one the next day. It's still a work around and it's a special case, though.

**Comment by Grubleafeater** [comment]
Understand that this is NOT a solution to the issue, but rather, a stopgap:

Place the item you wish to defrost into a steel drum and drop it in a brazier. Place log in brazier and ignite.

As long as you remember before the brazier goes out, the heat will preserve the item the same as freezing.

**Comment by AmarinReyny** [comment]
> Understand that this is NOT a solution to the issue, but rather, a stopgap:
> 
> Place the item you wish to defrost into a steel drum and drop it in a brazier. Place log in brazier and ignite.
> 
> As long as you remember before the brazier goes out, the heat will preserve the item the same as freezing.

Does this work with sufficiently hot temperatures in general, or just with fire?
