### ISSUE TITLE
[Android] Game crashes when i try to boot it up

### ISSUE THREAD

**Issue by Saylol222** [CleverRaven/Cataclysm-DDA#63839]
### Describe the bug

game crashes when i boot up the app

### Attach save file

N/A

### Steps to reproduce

start the app

### Expected behavior

i play game i have fun

### Versions and configuration

OS: Chromebook / Android
Version: c7738a5
Tiles
English
Mods: Magiclysm, Blaze industries, No NPC Needs, Stats by kills, Speedydex,

### Additional context

VERSION: c7738a5
Signal SIGSEGV: Segmentation fault
STACK TRACE:
# 5: 0x9205b7c cata_cursesport::curses_drawwindow(catacurses::window const&)
# 7: 0x92ed980 ui_adaptor::redraw_invalidated()
# 9: 0x8605b34 realDebugmsg(char const*, char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#10: 0x8295894 void realDebugmsg<char const*, char const*>(char const*, char const*, char const*, char const*, char const*&&, char const*&&)
#11: 0x83c70a8 read_from_file_json(cata_path const&, std::__ndk1::function<void (JsonValue const&)> const&)
#12: 0x8e524c0 Name::load_from_file(cata_path const&)
#13: 0x92c6474 set_language()
#14: 0x8b42000 SDL_main
#15: 0xba035f0 Java_org_libsdl_app_SDLActivity_nativeRunMain

**Comment by Saylol222** [comment]
redownloaded the app and it worked

**Comment by waveyl** [comment]
Please close your issue if it works
