### ISSUE TITLE
Mi-Go Guard Shriek Pierces Earplugs

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63844]
### Describe the bug

Mi-Go Guards have Shriek-Stun. While wearing earplugs, you don't hear the shriek, but still get dazed by it.

### Attach save file

N/A

### Steps to reproduce

Spawn migo guard and earplugs. Wear earplugs.

### Expected behavior

If I can't hear it, it shouldn't daze me.

### Screenshots

![image](https://user-images.githubusercontent.com/42578905/221976083-7675dc0f-5166-4af0-b6ca-1be42172e9e5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: e6e4825 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

**Comment by ferociousdork** [comment]
This is the slaver beam attack applying the effect though, not the shriek-stun (you can deduce that from the "antennae" message):
https://github.com/CleverRaven/Cataclysm-DDA/blob/8c0f9606b89bc7b8545f702228a8d4912602d6f5/data/json/monsters/mi-go.json#L93-L96

It seems the dazed effect apply message could be more general, which is the cause of the confusion here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/8c0f9606b89bc7b8545f702228a8d4912602d6f5/data/json/effects.json#L472-L476

Shriek-stun does check if the player can hear the shriek:
https://github.com/CleverRaven/Cataclysm-DDA/blob/8c0f9606b89bc7b8545f702228a8d4912602d6f5/src/monattack.cpp#L616-L618

**Comment by Grubleafeater** [comment]
Ah. To be fair, i did check their file and it says they have shriek and shriek stun. :P
