### ISSUE TITLE
(Innawoods) Tailor Kit does not have Shearing Quality despite ingredient tool

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#63843]
### Describe the bug

Tailor Kit in Innawoods modpack does not have Shearing quality as base ability of tool despite consuming Kevlar Shears as ingredient. 

### Attach save file

[Boles Acres Megafauna-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10851789/Boles.Acres.Megafauna-trimmed.tar.gz)

### Steps to reproduce

Create Tailor Kit for IW and no shearing ability is present thus animals cannot be sheared unless kit is disassembled or Bronze Shears are crafted.

### Expected behavior

Expected function.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: e5b399d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna]
]

**Comment by Maleclypse** [comment]
Kevlar shears aren’t animal shearing shears

**Comment by Zireael07** [comment]
@Maleclypse This is like the third or Xth time it comes up, can they be renamed as it trips up people, especially non-native English speakers.

**Comment by evankimori** [comment]
Remember this is the Innawoods modpack I mentioned. Screenshots and abilities show otherwise.

![image](https://user-images.githubusercontent.com/43046067/222165294-f24f0b2f-11ad-40a5-8e8c-30d2f82cf85a.png)

Updated today with latest build Experimental. You can still Wield and Shear animals with it.

![image](https://user-images.githubusercontent.com/43046067/222165599-f84282d2-c791-4943-9157-22a8cb9f7199.png)

...or am I misunderstanding something?

**Comment by Light-Wave** [comment]
> @Light-Wave Not sure how you want to handle this.
> 
> @Zireael07 I found they are also referred to as Kevlar Cutters, I'll put up a PR tonight for it.

The PR you created sounds like a good way to resolve this, yes.
