### ISSUE TITLE
Theft from the refugee center according to Reddit 

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#63850]
### Describe the bug

p.s. It is extremely easy to steal from the Refugee Center without consequences.

Step 1: Designate an Loot: Unsorted Zone over the entire Center.

Step 2: Designate a Loot: Custom Zone in a hidden corner. Leave the filter blank so that it catches every item.

Step 3: Auto-sort. You will move every item you can reach to your corner.

Step 4: Get away with it. After you move everything, someone will get mad and tell you to return it. However, the goods aren't in your inventory, so nothing happens. You get 5 Anger with whoever catches you, but that's it.

Step 5: Remove the 'stolen' flag. Picking a stolen item up and dropping it makes it yours. Advanced Inventory Manager makes this very simple to do en-masse. And, since you moved everything to an unwatched corner, no-one will get mad.

### Attach save file

N/a

### Steps to reproduce

Described above 

### Expected behavior

The refugee center to go incredibly hostile in response. No forgiveness possible

### Versions and configuration

Reddit report. Could be old.

**Comment by Basher6079** [comment]
I figured this would end up here.
Version: 2023-02-08-0648 (2 weeks ago)
So, probably still works.

**Comment by Leonkoithara** [comment]
I would like to note Step 4 doesn't happen on my build. i.e nobody gets mad or asks us to return items. Even the anger levels are the same as before.
