### ISSUE TITLE
0.G version string is incorrect

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#63859]
### Describe the bug

0.G is marked as experimental on my phone and the main menu version string is d6ec466.

### Attach save file

N/A

### Steps to reproduce

1. View the main menu

### Expected behavior

I expected the version string to read 0.G

### Screenshots

![Screenshot_20230301-201046](https://user-images.githubusercontent.com/2125926/222308083-c0a0121f-08fb-4323-9de8-b0c6ad09cfed.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Google; Model: Pixel 5a; Release: 13; Incremental: 9471150; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Maleclypse** [comment]
Partially fixed by #63862.

**Comment by waveyl** [comment]
> Partially fixed by #63862.

Not fixed.
![image](https://user-images.githubusercontent.com/22638873/222343202-54262750-ab10-46c3-9eed-f3110d5b3846.png)

**Comment by rumly111** [comment]
it is probably related. on linux desktop the stable 0.G version extracts to `cataclysmdda-0.F` directory

**Comment by anarchy79** [comment]
I have the same issue. Not sure how to do this, or what to post. I'm on 5.15.0-116-generic #126-Ubuntu SMP, I installed the latest version Gaiman, in-game version shows d6ec466, and like the gentleman above I too had it extracted into a F-0 directory. Please let me know which other information I can provide you with to facilitate the best remediation.
