### ISSUE TITLE
Android Playstore Compatibility Bug?

### ISSUE THREAD

**Issue by BlondeElf** [CleverRaven/Cataclysm-DDA#63857]
### Describe the bug

Hello there, just making a small post to share an issue that is not letting me see both Stable and Experimental on the Playstore app,

To build a timeline, my latest version was the experimental on the playstore that had its last update in 2022 December i think, around 5 Feb i remember seeing them both stable and experimental in the Playstore, and around 24-25 Feb thats when i noticed i stopped seeing them on the Playstore app, also noticed other few people having the same issue too,

Today i checked the Experimental on the playstore using a link to it and it said that my phone was incompatible with it, which i find kinda surprising since it ran decently,

Maybe something happened that involves how system compatibility works on CDDA releases around 5 Feb - 25 Feb? something directly or indirectly happened that could had accidentally slipped more systems into the incompatibility tag?

Edit: i still cant install it using the latest APKs (both 64x and 32x), it does the process in a normal way until it gets stuck at around 75% and stops for 15-20s until it finally pops the "failed installation" ending, storage isnt causing this just to be sure,

info about my phone etc:
Samsung J7 2016
Android 8.1.0 (latest update for mine it seems)
Argentina Playstore

### Attach save file

N/A

### Steps to reproduce

1. search for both CDDAs versions using a system that has Android 8.1.0 or lesser version?

### Expected behavior

i would had expected to see both releases on the Playstore since its pretty decent,,

### Screenshots
![IMG_20230301_210843](https://user-images.githubusercontent.com/126730439/222295959-878400b0-692d-4068-93d3-062c5774cabe.jpg)
![20230302_033341783](https://user-images.githubusercontent.com/126730439/222354950-ba930b39-5da3-489e-bfa8-98adabe0edb5.jpeg)
![20230302_033421510](https://user-images.githubusercontent.com/126730439/222354964-1ebd71ab-529a-436f-90f2-4d81752c9152.jpeg)
![20230302_033438935](https://user-images.githubusercontent.com/126730439/222354991-7e94133d-49b1-4f96-8180-834e7a671955.jpeg)

### Versions and configuration

- OS [Android 8.1.0]
- RAM [2.0 GB (400mb reserved)]

### Additional context

the red letters in the screenshot says like "This App isnt compatible anymore with your Device, contact the Devs to obtain more info."

**Comment by Drew4484** [comment]
For what it's worth I can see/download both versions. Tested March 1st, 2023. Running a Pixel 6 Pro, Android 13, build number TQ1A.230205.001.D2.

**Comment by ZhilkinSerg** [comment]
Use APK from github releases page instead of Playstore version. I think minimum RAM on Playstore is currently set to 3 GB.

**Comment by harakka** [comment]
> I think minimum RAM on Playstore is currently set to 3 GB

Has this changed recently? We've had a bunch of people on Discord reporting they can no longer see the game on Play Store even though they could previously, and I've been trying to find out what the commonalities are.

**Comment by harakka** [comment]
Another similar report on Discord, Android10 Moto G7 Play 2GB. From user POV this is a regression since they aren't informed anywhere that the requirements have been changed, but I'm not sure how to inform people since they can't see the app on Play store in the first place any more.

Would it be possible to build APKs with the old API level requirement so that the manually downloaded APKs at least would run on a wider selection of devices? If this is an intentional deprecation it should probably be at least mentioned in release notes.

The Store page of an individual app still shows "Android 4.0 and up" as required OS btw.

**Comment by RenechCDDA** [comment]
> Would it be possible to build APKs with the old API level requirement so that the manually downloaded APKs at least would run on a wider selection of devices? If this is an intentional deprecation it should probably be at least mentioned in release notes. I get that a lot of these devices are old as balls but just based on feedback I see on Discord we seem to have a lot of players on them.

As far as I can tell, the supposed "compatibility" is a feature of the play store and is set there. It cannot be changed on the build side. https://stackoverflow.com/questions/55233073/how-do-i-specify-a-minimum-ram-requirement-for-my-app

**Comment by harakka** [comment]
> As far as I can tell, the supposed "compatibility" is a feature of the play store and is set there. It cannot be changed on the build side. https://stackoverflow.com/questions/55233073/how-do-i-specify-a-minimum-ram-requirement-for-my-app

Your link relates to minimum RAM requirement, which is on Store side. The API level is a different concern and is set in the Android package manifest.
