### ISSUE TITLE
Roll Grenades Down Stairs Without Peeking

### ISSUE THREAD

**Issue by Error-String-Expected-Got-Nil** [CleverRaven/Cataclysm-DDA#63864]
### Is your feature request related to a problem? Please describe.

Consider the following situation:
![image](https://user-images.githubusercontent.com/103805191/222320483-78f8be12-377c-4726-8234-7c62577d2770.png)

I am at the top of these stairs. There are zombies in the room below, packed tightly and crowding around said stairs. I got some grenades from killing other zombies above. The obvious solution is, of course, to toss a grenade down- but one problem, I need to peek down the stairs to do so.

That wouldn't normally be too hard, but because the zombies are crowding around the stairs, I am unable to reliably peek down and throw the grenade. If I pull the pin, there's a risk one will step on the stairs, and then I'm sitting there looking stupid and holding a lit grenade I can't get rid of, because the zombie on the stairs is preventing me from peeking to throw the grenade.

### Solution you would like.

Add some kind of action to timed grenades that lets you roll them down stairs after lighting them so you don't need to peek the stairs first. It doesn't really make sense that you can't toss a grenade down just because a zombie is on the landing.

### Describe alternatives you have considered.

Allowing peeking up/down into occupied spaces? But I imagine there are significant technical limitations for that.

**Comment by Raikiri** [comment]
I'd argue it shoudl be possible to put a grenade on stairs without it rolling. So it's hard to tell one case from the other.

**Comment by Error-String-Expected-Got-Nil** [comment]
What do you mean exactly? Like you try to roll it and it fails?

**Comment by Raikiri** [comment]
Like if there's 3 stairs down, it should be possible to put a grenade on the current floor and leave without it rolling downstairs.

**Comment by Error-String-Expected-Got-Nil** [comment]
I mean yeah, you should still be able to drop it on your current floor. But I mean I want a specific option to make it roll down to the next floor.

And yes, that's exactly the solution I'm suggesting/requesting. I want to be able to blind throw a grenade without peeking.

**Comment by Qrox** [comment]
You can aim at a different z-level with 3d fov on but the last time I tried bullets were stopped by stairs. Not sure about grenades but I suspect it is the same.

**Comment by Error-String-Expected-Got-Nil** [comment]
3D FOV is explicitly a buggy feature, and I think rolling grenades down stairs is basic enough that it should be possible without it, even if you can do that.

**Comment by Error-String-Expected-Got-Nil** [comment]
3D FOV is, as I understand it, in no way a priority and is basically just a test. Fixing it is not a viable alternative.

The criticism that it's a bit specific is fair, but still, it seems like such an obvious thing to do, no? As I said, why should a zombie being on a stair's landing prevent you from tossing a grenade down?

I think one level seems reasonable. Can't imagine in what case you'd want to roll it more than one down.

**Comment by Qrox** [comment]
We could just allow throwing downstairs and treat stairs as partial obstacles and check your throwing skill to determine how many levels down you can throw. But misaligned stairs may make it harder to implement if that's still a thing.

By the way, I always have 3d fov on and never encountered any noticeable bug. I always felt it's simply because no one cared enough to make it the default and remove the option unless I missed something.

**Comment by Error-String-Expected-Got-Nil** [comment]
The main issue is figuring out how to perform the action in the first place. And I still think one level is enough for all practical purposes.

As for 3D FOV, if that were the case, I'd think someone would at least remove the note warning that it's buggy/experimental.
