### ISSUE TITLE
Custom fonts won't work in android

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#63871]
### Describe the bug

There's no way to change fonts in android. However, brute forcing by swapping unicode.ttf works. But I want to change fonts normally.

### Attach save file

N/A

### Steps to reproduce

1. Get a font ttf.
2. Install it into your game data by putting the font into fonts folder, and change fonts.json in config folder.
4. Open the game.
5. The font doesn't change.

Brute force method:
1. Get a font ttf.
2. Find the unicode.ttf in your game data.
3. Move unicode.ttf to somewhere, install the font you downloaded and rename it to unicode.tff. Like Indiana Jones!
4. Open the game. The font is changed, but since the unicode is on disguise, it can't print texts that unicode has.

### Expected behavior

I expected the font to be changed without any trouble.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 13; Incremental: G991NKSU3EWB1; 
- Game Version: c64acea [64-bit]
- Graphics Version: Tiles
]

**Comment by Qrox** [comment]
You should also change `config/fonts.json` if you haven't yet done so.

**Comment by AnotherSeawhite** [comment]
I forgot to mention that. I did edit the json in config folder.

**Comment by AnotherSeawhite** [comment]
I edited the steps so it won't cause any confusion.

**Comment by AnotherSeawhite** [comment]
> Do you add full path to new font files in `config\fonts.json`? Or does it contain just font file name?

Apparently I had to write the FULL path, like `/storage/emulated/0/`. No wonder why Terminus won't work. Thank you for the help.
