### ISSUE TITLE
0.G version not working in Windows XP SP3

### ISSUE THREAD

**Issue by carthago814** [CleverRaven/Cataclysm-DDA#63885]
I describe it as a bug because version 0.F-3 works fine under the same PC without errors. I found no description of the system requirements for different versions, only bug reports for Windows XP for past versions of CDDA, so it is bug after all.

An error occurs when running exe file of build for Windows x32 (cdda-windows-tiles-sounds-x32-2023-03-01-0054.zip):

**The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll.**

When running the MSVC x32 build exe file (cdda-windows-tiles-sounds-x32-msvc-2023-03-01-0054.zip), the error is different:

**cataclysm-tiles.exe is not a valid Win32 application.**

After that, the game simply doesn't start.

Fully updated Windows XP SP3 x86 is used, the MS Visual C++ Redistributable packages also are installed, which are aviable under WinXP.

**Comment by Raikiri** [comment]
which msvc redist versions do you have installed?

**Comment by andrei8l** [comment]
Windows XP is 10 years out of support and there's nothing we can do about this. The mingw version might work, but you're still on your own.

**Comment by Qrox** [comment]
The game does not use `GetTickCount64` directly so that is probably a problem with the MinGW cross compiler.

**Comment by BrettDong** [comment]
`mingw-w64` targets Windows 10 by default:

https://github.com/mirror/mingw-w64/blob/aa08f56da559016f10336dddca85d59f9bdc9e02/mingw-w64-headers/configure.ac#L134-L142

And MXE also set minimum Windows target version to Windows Vista in https://github.com/mxe/mxe/pull/2660.

**Comment by BrettDong** [comment]
To build a windows XP compatible binary, one needs to first build a MXE toolchain with https://github.com/mxe/mxe/blob/master/plugins/windows-xp/gcc-overlay.mk enabled.

**Comment by BrettDong** [comment]
> it can only solve the first problem I encountered

The second problem is outright not going to be solved. Microsoft intentionally drops support for Windows XP in modern MSVC versions.

**Comment by kevingranade** [comment]
I wouldn't turn down a windows xp build job if someone felt like assembling one, but given the complexities outlined in the thread it doesn't seem likely, and given effort vs number of users I can't really treat it as a priority for the project.
