### ISSUE TITLE
Mafia Boss Profession Double Tuxedo

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#63882]
### Describe the bug

Mafia Boss Profession starts with 2 Tuxedos - 1 with an item and one empty

### Attach save file

N/A

### Steps to reproduce

Create Mafiaboss - Notice that he wears 2 Tuxedos

### Expected behavior

While wearing 2 Tuxedos is something that you can totally do ... i would say that job would belong to some kind of weird class

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/222544691-6600c115-967b-4ce2-85a6-dfd16271b549.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 8765d30 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Termineitor244** [comment]
/confirmed

A simple one line change will fix this.

**Comment by Pointabc** [comment]
Created a PR for this issue "fix double tuxedo in json #63941".

**Comment by Pointabc** [comment]
@estebandellasilva can you check this issue? It was fixed and merged.
