### ISSUE TITLE
Crash when inserting items into some worn items

### ISSUE THREAD

**Issue by PlatoSoft** [CleverRaven/Cataclysm-DDA#63894]
### Describe the bug

Game crashed when I tried to insert makeshift wooden arrows into a worn large quiver. Total vanilla game without mods, clean install of 0.G.

### Attach save file

N/A
A similar thing happened earlier in the same game when i tried to insert something into a leather belt, but i can't reproduce it consistently, so the save game won't help, i think? There seems to be some other variable that I am not aware of yet, so the first time i ignored it, but now it happened again with the quiver, so I thought i'd create an issue at least so you can look into it.

### Steps to reproduce

1. Wear an item
2. Try to insert something via the item menu (enter + i)

### Expected behavior

The game not randomly crashing when using the insert function.

### Versions and configuration

OS: Windows 10
Version: 0.G dafb974 (2023-03-02-1808)
Graphics: Tiles
Language: English
Mods: None/Standard

### Additional context

Both crashes prompted the same message: SIGABRT: Abnormal termination
[crashlog.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10877691/crashlog.zip)

### EDIT:
This also seems to happen when activating worn items like in the case of a scabbard or a belt, not using the insert function.

**Comment by MochaModifier** [comment]
I'm also experiencing this issue. Started a new world for latest version, lab start. No issue until after I'd explored a few floors - maybe an hour or so of gametime?

To expand on what's been posted - picking items up seems to be fine. Using white listing and pocket priority to ensure an item goes to a specific container doesn't cause a crash. You can put a smartphone into a waterproof case this way just fine, but if you take it out and try to [i]nsert it, the game crashes after showing a progress spinner.

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: dafb974 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

trimmed save in case it helps - should be able to insert an item and reproduce crash
[Holdrege-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10877971/Holdrege-trimmed.tar.gz)

**Comment by Kamayana** [comment]
Replicated. It's my doing, from here: https://github.com/CleverRaven/Cataclysm-DDA/blame/master/src/activity_actor.cpp#L3965

I've learned since then what causes this (calling map.make_acrtive() on an item that's not on the map) so I'll work on fixing it.

**Comment by adamkad1** [comment]
Oh someones fixing it. good.
