### ISSUE TITLE
JSONable night vision ranges

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#63897]
### Is your feature request related to a problem? Please describe.

Currently, all possible night vision ranges are hard-coded to specific mutations or traits. If you want to let a character see in the dark, you need to either give them one of those specific traits or an effect with the NIGHT_VISION flag that lets them see to the limits of normal vision. 

### Solution you would like.

An enchantment value that adjusts the range of a character's night vision, (hopefully) compatible with existing traits, so it would be possible to write bonuses to night vision that are compatible with any level of night vision a survivor might have (or curses that can reduce it).

**Comment by Venera3** [comment]
After  #62092 merges you will be able to modify `nightvision_score` through any effect.

**Comment by anothersimulacrum** [comment]
Looks like #62092 was merged.
