### ISSUE TITLE
Unarmed attacks destroy attacker's armor suits

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63899]
### Describe the bug

If you attack unarmed while wearing any suit (activity suit, hub suit, full chainmail suit, etc), some attacks trigger the "the force of the blow damages your %armor name%". This used to also destroy power armors as per https://github.com/CleverRaven/Cataclysm-DDA/issues/63221 , then power armors specifically got UNBREAKABLE_MELEE flag here https://github.com/CleverRaven/Cataclysm-DDA/pull/63635 , however the fundamental issue remains: there's lots of other armor suits that can be damaged by your own attacks.

Every armor suit that covers your hands seems to be affected. The problem is particularly bad for suits that you can't repair: chainmail, faraday, immersion suit, etc.

I originally suspected that the problem is specifically affecting power armors since it's the only armor that you can't wear with knuckles, however in-game testing has shown that wearing knuckles (I tested with scrap knuckles) over an activity suit still damages it.

### Attach save file

N/A

### Steps to reproduce

1. Put on any armor suit that covers hands (such as activity suit) and optionally scrap knuckles
2. Start punching zombies in melee

### Expected behavior

I expect you to either not damage your own armor or to at least damage the knuckles, not the suit.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: c69ea7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Raikiri** [comment]
I did more thorough testing to figure out exactly which martial arts are affected. I think mystery is sort of solved: looks like it's only martial arts that include kicks. However, some techniques that I did not expect to be leg-based are actually leg based, such as takedowns and throws:
![image](https://user-images.githubusercontent.com/1657728/222902311-4646996d-d7fe-41b5-89fc-acc81b195671.png)

You can see that my suit got torn when I executed a throw from Bionic Combatives.

I guess in this case it's intended because there's nothing on my legs that could protect my armor. I'm still not sure if it's a good thing to consider cases of self-damage like this desirable. What do you guys think?

**Comment by Tharn** [comment]
This is in part because martial arts currently causes way too much damage to hand armor as well. What you're seeing as a more rare thing with kicks happens at several times the rate with knuckles and glove items. Even steel gauntlets get shredded after few opponents.

That armor gets procced when kicks happen (the same could be said for knee/elbow hits if those were in the game, or rather they should be expected to happen *sometimes* because MA is not a perfectly exact science) is not the part I would take issue with, but overall just the rate at which armor of the martial artist gets damaged currently.

**Comment by Tharn** [comment]
Okay, after some further playing the issue is not as dire as I described it. Weak skin-layer stuff will actually last a while, and gauntlets/knuckles don't lose much HP. I was practicing against a blob when my first Zentai disintegrated, maybe that had something to do with it also.
