### ISSUE TITLE
Changing faction reputation through EOCs seems disconnected from the rest of its use.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#63907]
### Describe the bug

#63815 added a way to alter faction reputation through EOC’s, and use it as a condition. While very amazing and quite useful, my testing had revealed that changing faction standing this way is a bit disconnected from the rest of the reputation system.

### Attach save file

N/A
Use this JSON to test what I mean:
{
    "type": "effect_on_condition",
    "id": "EOC_TEST",
    "effect": [ { "u_message": "You feel untrusted" }, { "arithmetic": [ { "faction_trust": "free_merchants" }, "-=", { "const": 2 } ] } ] 
}

### Steps to reproduce

When I change the faction reputation value below zero, even to -100, usual effects don’t apply. NPC’s of that faction won’t try to kill me on sight, I can freely trade with any merchants normally, and my standing with them in the “Other Factions” screen remains what it was before the change: ex. “Valued” for the Free Merchants.

### Expected behavior

I believe that these things should correspond to EOC changes, such as faction members attacking me if I set my reputation to -100 through an EOC.

### Versions and configuration

Playing in the windows tiles x64 experimental of 3/2/2023. 

### Additional context

I didn’t know if I should classify this as a bug report or not, as it was just unexpected behavior from my testing and project development.

**Comment by Ramza13** [comment]
So I'm taking a look at this and under the hood there are a few things going on.  First a faction has different values for likes_u, trusts_u and respects_u which do different things.  Right now EOCs can only modify trusts_u so I'll add access to the others.

Take a look at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FACTIONS.md for what they all do.
