### ISSUE TITLE
More welding rods in the world

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#63902]
### Is your feature request related to a problem? Please describe.

Welding rods were added a while ago and while they're perfectly reasonable, but you're always running out and creating them is a repetitive chore.

### Solution you would like.

It would be nice if more of them existed in the world. Given how many it takes to do even minor tasks, any location where welding was done or welding supplies were sold should have many more than can currently be found.

This would also prompt the player to explore and loot specific locations more.

Off the top of my head, places to find welding rods could be:

Any blacksmith shop
Any garage
Zombie technicians
Steel mills
Light Industry
Construction sites
Hardware stores
Hardware megastores
Workshops

Some likely exist in these places already, but it's usually hardly enough to justify the trip.

It'd also be nice if we could get NPCs to make these for us, as the process is pretty easy, it's just time-consuming. Fatima at the Refugee Center or the blacksmith lady who lives with the gunsmith dude should do it on request for money and materials. I don't know if there's a faction camp job to craft them, but that'd be another idea.

### Describe alternatives you have considered.

Make welding jobs cost fewer welding rods, or just make Smokes or somebody sell them.

**Comment by matt32106** [comment]
I bought about 2000 of each from the refugee center IIRC
