### ISSUE TITLE
Exploding Craters cause several problems

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#63914]
### Describe the bug

The Exploding "Craters" (red [o] on overmap with "There is a crater here." autonote) cause a ton of problems:

- if you do a Lab Start, they will automatically kill enemies just as soon as 1 turn passes.
- they explode the moment they enter visual range (and the PC hears the explosions.). Said explosions damage items nearby as well.
- these explosions screw with "achievements" and the player's kill list (doesn't matter where you start the game, if an explosion just happens to occur somewhere where zombies are and they die, you will be awarded the kills); 
- more often than not it leads to several full-screen error messages about monster placements, missing tiles or multiple monsters on the same tiles (this is not one you can replicate immaculately, but it occurs frequently enough to be a bother);

These are not the craters with a lot of rubbish where they land. These are the ones that can randomly spawn like body sites and stuff. 

### Attach save file

N/A - this is easy to replicate.

### Steps to reproduce

1. Turn auto-notes on if you have them off so you can see things like "craters", "loot crates", "crashed helicopters", etc.
2. Create new character in Lab Start scenario - bottom of a science Lab is a good enough start. 
3. start the game and hope you get into a lab that is underneath a Research Facility. 
4. Check if full-screen errors occur (they vary);
5. Even if 3 isn't accurate, just pass 1 turn and pay attention to the log. If reproduced correctly, you will see messages about certain achievements.
6. Check your kills list afterwards, and notice that you killed creatures for no reason other than existing. 

Most of this is very easy to replicate given the sheer amount of deaths one can accrue under certain circumstances. This has been an issue ever since those craters were made to be explosive and not radioactive.

### Expected behavior

I would expect these craters to not explode, at all. Either they are already static craters or just remove them completely.

### Versions and configuration

- Windows 7; 8765d30 (tiles) - Build 2023-03-02-1307
- default map created, no mods
- Language: english.

**Comment by Snaaty** [comment]
I understood the explosions to be intended to happen when the player gets close. Stuff crashing down from the sky or explosives seems more fun to me than just craters that don't offer any interaction anyway. Just my humble opinion.

**Comment by AcidAntOnAMinefield** [comment]
I can see that, but what would be the justification for the ones that happen in the middle of nowhere, plain fields? 

Plus it's also weird that it gives the player the kills upon spawning too. 

As for "explosion", for me the understanding of "what is an explosion" is that it's something that requires ignition. Things crashing down from a half-destroyed building aren't that imo.

**Comment by Night-Pryanik** [comment]
A pair of issues hardly qualifies as "a ton of problems".

**Comment by AcidAntOnAMinefield** [comment]
> A pair of issues hardly qualifies as "a ton of problems".

A pair of issues that I can outline among many other oddities that happen too, which can range from several full screen warnings about "misplaced creatures" or "cannot place creature on open air" or stuff like that. 

Things that I could not capture or memorise, most of them because they happen frequently enough for me to think it's unrelated to this issue either. 

This is a problem being reported, being snarky and pedantic about language just for the sake of it is kinda unwarranted - then you wonder why people have negative feelings about how things happen here.

**Comment by KittyTac** [comment]
> I understood the explosions to be intended to happen when the player gets close. Stuff crashing down from the sky or explosives seems more fun to me than just craters that don't offer any interaction anyway. Just my humble opinion.

No, it's just a way to generate craters. They're not meant to actually be crashing down as you walk. Note how one can't flal onto your base. I wish there was a better way to generate them tbh.
