### ISSUE TITLE
Un-cosmetibled items are (active) for some reason

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#63922]
### Describe the bug

Related to #63434 and #62800

The title.

### Attach save file

N/A

### Steps to reproduce

1. Change the game version to prior to #63434
2. Create a world, debug summon a lot of bandages (roughly 200)
3. Update the game to recent versions
4. Load the save

### Expected behavior

I expected the bandages to not haunt me.

### Screenshots

![IMG_20230304_152800](https://user-images.githubusercontent.com/52661206/222880869-074725d6-2cad-4de3-9cef-35288ff51de3.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 13; Incremental: G991NKSU3EWB1; 
- Game Version: 4ea6fb5 [64-bit]
- Graphics Version: Tiles
]

**Comment by cake-pie** [comment]
Due to temperature processing for comestibles.

I wonder if a hacky test like this to force deactivate them would suffice
```
if(!has_temperature() && last_temp_check != calendar::turn_zero) {
    last_temp_check = calendar::turn_zero;
    active = false;
}
```
If this causes collateral to other items that are supposed to stay active then we may have to resort to an explicit migration list.

**Comment by AnotherSeawhite** [comment]
oopsie.
