### ISSUE TITLE
[XEDRA Evolved] Certain spell artifacts turns into normal artifact after save load

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#63939]
### Describe the bug

Certain artifacts, like `muscles` turns into normal artifacts after saving the game and then load the save.

### Attach save file

N/A

### Steps to reproduce

1. spawn in a bunch of `muscles`,
2. save and quit,
3. load into said save,
4. normal artifacts.

### Expected behavior

not morphing into normal type of artifacts.

### Screenshots

Before a save/load
![Screenshot_20230305-000525](https://user-images.githubusercontent.com/78019001/222919573-070f3553-63dc-4138-aba2-c76079ad750f.jpg)

After
![Screenshot_20230305-001225](https://user-images.githubusercontent.com/78019001/222919613-a7a444cc-9d36-4a4e-836b-c9c0727ca117.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: c1e38de [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No scent tracking zombies [no_scent_tracking_zombies],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

### Additional context

Apparently some artifacts don't change, like `hurricane lamp with thorns`.

**Comment by GuardianDll** [comment]
![image](https://user-images.githubusercontent.com/67688115/222922675-d2d8b644-8b80-4917-adb0-63d47029cc73.png)
![image](https://user-images.githubusercontent.com/67688115/222922756-4bac725b-79b4-4a36-9f6b-2dafdb8286a6.png)
/confirmed - in my branch im modifying the minor_spark_artifacts and respective procgen, and it picks the stats from exactly this procgen
current theory - if item has `artifact_` in the id, the game read it incorrectly, and replace it with actual artifacts
for example, between items `deck_of_tarot_cards` and `artifact_right_eye` the second one do not turn back as intended
![image](https://user-images.githubusercontent.com/67688115/222923061-1d3dcc44-4007-4922-a506-ed943171a788.png)
![image](https://user-images.githubusercontent.com/67688115/222923185-342ab0a4-cc91-4671-8530-cd4b90fadf68.png)

**Comment by GuardianDll** [comment]
@Maleclypse may i bother you?
![image](https://user-images.githubusercontent.com/67688115/222923346-6138db2f-3a60-4014-a293-85b72db88778.png)

**Comment by Maleclypse** [comment]
> @Maleclypse may i bother you? ![image](https://user-images.githubusercontent.com/67688115/222923366-63a031d5-61e2-4e10-a9d4-998afbdd4448.png)

Ok so I thought I saw someone say they were going to fix this but I'm guessing I should fix it myself if it isn't up yet?
