### ISSUE TITLE
I can't create world error version game 0.G Gaiman

### ISSUE THREAD

**Issue by Deathstray** [CleverRaven/Cataclysm-DDA#63936]
### Describe the bug

I downloaded the new stable version on March 4, 2023 and when I decided to create a world, I get the error data/json/character_modifiers:json119:13 denominator cannot be set to 0

If I am from Russia and I use a translator to translate into English, so there may be a completely different meaning of the text below, I will write the text in Russian if the English is wrong

Я скачал новую стабильную версию 4 марта 2023 года и когда я решил создать мир то у меня выходит ошибка data/json/character_modifiers:json119:13 denominator cannot be set to 0

Если что я из России я использую переводчик что бы перевести на английский поэтому может быть совсем другой смысл текста снизу я напишу текст на русском если английский будет неправильный.

### Attach save file

![image](https://user-images.githubusercontent.com/126969199/222914579-ce47fcf9-fcad-482b-b1de-72f4718371cd.png)

### Steps to reproduce

.

### Expected behavior

1)Went into the game
2)Pressed to create a world
3)I was expecting the creation of the world, but an error occurred

### Screenshots

![image](https://user-images.githubusercontent.com/126969199/222914352-613956b8-2f74-4314-a682-f77b0c66ae04.png)

### Versions and configuration

-OC Windows7 version game 0.G Gaiman(It's written in the game d6ec466) Language Russian

**Comment by Bluemonotony** [comment]
I got a similar problem, i can create a world but when creating a character that error appears, I also use windows 7

**Comment by Deathstray** [comment]
> У меня похожая проблема, я могу создать мир, но при создании персонажа появляется ошибка, я также использую Windows 7

Ну что ж теперь будем ждать

**Comment by RenechCDDA** [comment]
Upgrade your windows or use the msvc build.

Related/duplicate of #61095

**Comment by Deathstray** [comment]
> Обновите свои окна или используйте сборку msvc.
> 
> Связанный/дубликат #61095

Thank you for helping
