### ISSUE TITLE
Hub 01 crash (related to npcs and mechs)

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63937]
### Describe the bug

The game hard crashes when I enter a certain area of hub 01 on level -1

### Attach save file

[Boulder Junction-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10888992/Boulder.Junction-trimmed.tar.gz)

### Steps to reproduce

1. Load the provided savegame
2. Go directly north
3. Crash happens when you step through the second doorway

### Expected behavior

I expect the game to not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: c69ea7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Looks like the problem has to do with the mech going through a doorway, because I can explore that area without the mech just fine.

**Comment by andrei8l** [comment]
The version you're using has a bug in the archive generation when the player is underground so this save archive is unusable. Can you please use a newer version to generate it? The [stable release](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.G) should be fine

**Comment by Raikiri** [comment]
Ah dang. Unfortunately I have already cleared that area and there are no more bugged spots left. I found 2 points in the hub that reliably froze, and I'm fairly sure they froze when I came into a line of sight of specific NPC's that were trying to fire at me riding my mech. If I was not in the mech, there was no freeze. Only 2 out of a couple dozen NPC's ended up being bugged like that.
