### ISSUE TITLE
Shells don't seem to stop limbs from getting hit

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#63930]
### Describe the bug

When using a shell mutation to hide, your limbs can still be hit by monsters.

### Attach save file

N/A, it's easy to reproduce.

### Steps to reproduce

1. Give character Roomy or Nacreous Shell mutation.
2. Use it to hide.
3. Spawn a hostile monster nearby.
4. Wait and see what happens.

### Expected behavior

That it functions as the description says.

### Screenshots

![image](https://user-images.githubusercontent.com/52408044/222901189-b53b3ffa-581f-4a4f-aac8-bdec3cd30135.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 4ea6fb5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

If it just reduces the chance then this is moot, but the game isn't clear about it. And the chance seems to not be reduced much in that case.

**Comment by GuardianDll** [comment]
The shell protect only torso, and i see no action that can make you actuallhide inside

**Comment by KittyTac** [comment]
> The shell protect only torso, and i see no action that can make you actually hide inside

Yeah but you can activate it and it's supposed to hide you. It reduces your vision like it would.

I should have mentioned this is supposed to work with Roomy Shell and Nacreous Shell, I'll clarify.

**Comment by RenechCDDA** [comment]
Might have been broken at the time but it's definitely working now. 
![image](https://user-images.githubusercontent.com/84619419/236645790-ca483ecb-9d29-4a00-bca9-00dad8000d43.png)
