### ISSUE TITLE
Missing feedback for vehicle work while morale is too low

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#63948]
### Describe the bug

When trying to work on a vehicle when your morale is too low (-50), the action will fail as intended.  However no information is given to the player why it fails either in the vehicle screen or in the sidebar.

### Attach save file

N/A

### Steps to reproduce

1. Have tools on hand required to perform vehicle work.  For example, a screw driver to remove a seat belt.
2. Lower player morale below 50.  Such as killing a zombie child or butchering a human corpse.
3. Try to remove a vehicle part such as a seat belt.
4. Nothing happens and there's no feedback to the player.

### Expected behavior

When morale is too low to work on a vehicle, some sort of warning or pop up should tell the player that they cannot work on that while their morale is too low.

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Generic Guns [generic_guns]
]

**Comment by cake-pie** [comment]
Cannot reproduce.

With low morale:
![withlowmorale](https://user-images.githubusercontent.com/28502722/222956824-1fc3a9c4-8c03-40a8-aaf2-ad7e7a826062.png)

Going to try removing that seatbelt:
![toremoveseatbelt](https://user-images.githubusercontent.com/28502722/222956798-87ae746c-5e11-404e-bb48-8700db66f198.png)

Informative message is displayed:
![toolowmoralemsg](https://user-images.githubusercontent.com/28502722/222956793-86a755c1-96a6-4636-9b1e-7a7410e13ee7.png)

**Comment by Hirmuolio** [comment]
Can reproduce in `cdda-windows-tiles-sounds-x64-msvc-2023-03-21-1229`, `cdda-windows-tiles-x64-2023-03-21-1229`, `cdda-windows-tiles-sounds-x64-msvc-2023-03-21-1229` and latest master (compiled with Visual studio 2022).

Drive the car (so it moves).
Try to remove seatbelt.
No message is shown. It just goes back to the vehicle menu as if nothing happened.

Following it in debugger the part `msg = _( "Better not remove something while driving." );` is reached. But I could not find where that message is supposed to be made made visible.
