### ISSUE TITLE
Nailboards shouldn't destroy hard wheels

### ISSUE THREAD

**Issue by MochaModifier** [CleverRaven/Cataclysm-DDA#63943]
### Is your feature request related to a problem? Please describe.

Casters and similar hard wheels are treated like inflatable tires, and are destroyed by simple nailboards

Casters are typically hard rubber or plastic wheels - the idea that a nailboard would outright destroy (maybe damage) them is completely opposite of expectation

### Solution you would like.

Caster wheels and similar hard wheels (like skate wheels) shouldn't be outright damaged by going over hazards like nailboards

### Additional context
![image](https://user-images.githubusercontent.com/38334602/222924538-9be2fe9e-8936-46a2-a73d-97354d371dcb.png)

**Comment by cake-pie** [comment]
Yup, gets more absurd:
![roller](https://user-images.githubusercontent.com/28502722/222952549-36f9e85e-751b-42ec-aa70-923c5014c26c.png)

**Comment by cake-pie** [comment]
did this:
![roller-roll](https://user-images.githubusercontent.com/28502722/222953071-1599ba33-aee7-4b00-a1d2-87077273c38b.png)
consequences:
![roller-dmg](https://user-images.githubusercontent.com/28502722/222953074-68b16a3a-71e7-45e2-8232-4f154279ed82.png)
