### ISSUE TITLE
Caught cold while wearing active gas mask

### ISSUE THREAD

**Issue by Shauntungosaurus** [CleverRaven/Cataclysm-DDA#63955]
### Is your feature request related to a problem? Please describe.

I put it on and haven't taken it off or run out of charges for the past in-game month, since the last time i caught the flu and decided i'd rather have less head armor than keep catching the cold a day after the last one ended because my character is really unhealthy. It's been activated ever since, only down 8 charges since i haven't gone anywhere i'd need it i guess. So how did i catch the cold through a damn _gas mask?!_ 

### Solution you would like.

Wearing an active gas mask should make your character immune to the flu and colds.

### Additional context

Also, how the hell do you get a character out of the death valley of lifestyle health you get for starting with XXXL? I've been doing everything i can, eating -health foods only when there aren't other options, burning stamina and training athletics, and eating multivitamins. I've gone too long without sleep at times, but that's just because its impossible to _not_ with the flu or cold since they keep making you more tired. 
The very first thing i did was put my character on a starvation diet(no food only water and vitamins), got down to overweight in maybe 2 weeks and normal in 1 more. it's been almost 2 months now and it's still "Feel Awful"

**Comment by Quintovir** [comment]
The # 0.G (Gaiman) big release patch notes say:

> gas masks no longer make you immune to getting sick

**Comment by Cenness** [comment]
#61058 
>the mouth isn't the only vector for disease, and there's no way to wear a gas mask 24/7 because you have to take it off to eat, drink, etc, which exposes you to disease in intervals
