### ISSUE TITLE
Fonts screwed up

### ISSUE THREAD

**Issue by Abalieno** [CleverRaven/Cataclysm-DDA#6395]
It seems the new version can't digest the font I always used for Cataclysm.

![catabug2](https://f.cloud.github.com/assets/4656436/2305716/0fe683ce-a267-11e3-87b9-c7366f0285a4.gif)

It's a font called VGA8 with size 9x9
I just copied over from a previous Cataclysm install along with FONTDATA, and that's the output.

The old version works fine.

**Comment by mugling** [comment]
> And it works fine on last experimental (I guess pre-SDL2).

Presumably this is fixed in `master`. Please re-open if reproducible in any recent version
