### ISSUE TITLE
Can't Attack Water Creatures On Boat

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63959]
### Describe the bug

When I'm driving my boat sometimes creatures end up on it. Don't want them there, but it happens. Boat scoops them up or something.

Well, when that happens, the creatures can't be attacked.

### Attach save file

[Emida-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10890820/Emida-trimmed.tar.gz)

### Steps to reproduce

Get creature on ship. Try to attack.

### Expected behavior

Should be able to attack.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

**Comment by PatrikLundell** [comment]
Sounds like the corresponding bug with land vehicles. In that case the creatures that were immune to attack also, fortunately, were unable to attack the player.

**Comment by Grubleafeater** [comment]
Indeed. I'm able to get them off my damn boat by 'firing' my spear at them tho.
