### ISSUE TITLE
Amphibious Self-Jacking

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63957]
### Is your feature request related to a problem? Please describe.

If it floats, then you don't need to lift it to put wheels on or take wheels off.

### Solution you would like.

Give hulls some sort of stacking self-jacking, or something? But it should only apply in water?

**Comment by kevingranade** [comment]
You want to change tires on a vehicle UNDERWATER to avoid needing a jack. No that is not a reasonable option.

**Comment by Zireael07** [comment]
No, not every floating vehicle is gonna have tires underwater completely.
