### ISSUE TITLE
0.G android, Crafting menu crashes game

### ISSUE THREAD

**Issue by JDaggon** [CleverRaven/Cataclysm-DDA#63950]
### Describe the bug

Game crashes whenever I try to access the crafting menu.

### Attach save file

N/A

### Steps to reproduce

1) Make/Load up character

2) Press crafting menu hotkey or select from menu

3) Have game crash

### Expected behavior

I expected to be able to access the crafting menu.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: motorola; Model: moto g(7) power; Release: 10; Incremental: 7287f; 
- Game Version: eed25b0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

VERSION: eed25b0
St12length_error vector
STACK TRACE:
# 4: 0x7491df9100 __cxa_get_exception_ptr
# 8: 0x74375ebf48 std::__ndk1::vector<cata_cursesport::cursecell, std::__ndk1::allocator<cata_cursesport::cursecell> >::__append(unsigned long)
# 9: 0x74375eaabc catacurses::newwin(int, int, point const&)
#11: 0x74382eb964 ui_adaptor::redraw_invalidated()
#12: 0x74375b590c select_crafting_recipe(int&, string_id<recipe> const&)
#13: 0x7437599da8 Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)
#14: 0x7437819fb0 game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
#15: 0x7437824b88 game::handle_action()
#16: 0x7437668c54 do_turn()
#17: 0x7437b347f8 SDL_main
#18: 0x74919ca5f0 Java_org_libsdl_app_SDLActivity_nativeRunMain

**Comment by giakhanh7901** [comment]
They still haven't fix this yet

**Comment by RenechCDDA** [comment]
/confirmed on 936b383
```
VERSION: 936b383
St12length_error vector
STACK TRACE:
# 4: 0x792e833100 __cxa_get_exception_ptr
# 8: 0x78d2c47e68 std::__ndk1::vector<cata_cursesport::cursecell, std::__ndk1::allocator<cata_cursesport::cursecell> >::__append(unsigned long)
# 9: 0x78d2c469dc catacurses::newwin(int, int, point const&)
#11: 0x78d3947b38 ui_adaptor::redraw_invalidated()
#12: 0x78d2c11528 select_crafting_recipe(int&, string_id<recipe> const&)
#13: 0x78d2bf59c4 Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)
#14: 0x78d2e788f4 game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
#15: 0x78d2e834cc game::handle_action()
#16: 0x78d2cc46f4 do_turn()
#17: 0x78d31907f4 SDL_main
#18: 0x792e64a5f0 Java_org_libsdl_app_SDLActivity_nativeRunMain
```
