### ISSUE TITLE
Bionic claws error when wielding a new weapon

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#63956]
### Is your feature request related to a problem? Please describe.

 DEBUG    : Wielded weapon doesn't match the expected weapon equipped from Bionic Claws

 FUNCTION : void Character::process_bionic(bionic&)
 FILE     : src/bionics.cpp
 LINE     : 1597
 VERSION  : c1e38de

### Solution you would like.

Game to automatically deactivate my bionic claws without an error message when I wield another weapon without manually deactivating the claws

### Describe alternatives you have considered.

Being unable to wield other items until I manually deactivate

**Comment by Night-Pryanik** [comment]
#60550.
