### ISSUE TITLE
game is slow sgain at loading large quantities of items

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#63962]
### Describe the bug

i tried to insert a large quantity of full containers into a bigger bag, the loading time of the insert command has been awfully looooooong, just after stable release, game performance was faster

### Attach save file

[Emerald Lake Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10891458/Emerald.Lake.Hills-trimmed.tar.gz)

### Steps to reproduce

1. load game
2. try to insert something into the wielded body bag
3. notice how long it takes to open up the menu

### Expected behavior

i don't expect instant loading times with so many items to parse, but i noticed things got slower recently

### Versions and configuration

Windows 10
build 2023-03-05-0007
Tiles
English
[
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "Tamable_Wildlife",
  "stats_through_kills",
  "speedydex",
  "package_bionic_professions",
  "blazeindustries",
  "rub_reb",
  "No_Person",
  "extra_mut_scens",
  "MMA",
  "translate_dialogue",
  "No_Rail_Stations"
]

### Additional context

there will be 2-3 mod missing errors, those are minor json tweaks i made for myself, and has no actual meaning for this issue

**Comment by andrei8l** [comment]
Can't reproduce. I've tried the linux build and all 4 windows builds from [2023-03-05](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-03-05-0007) but the insert menu opens up pretty much instantly

![Screenshot from 2023-03-05 13-35-05](https://user-images.githubusercontent.com/68240139/222958107-b3419753-26e7-44ba-bae1-d99552120a71.png)
