### ISSUE TITLE
Make the distance which triggers "hostile is dangerously close" a parameter or at least increase by 1

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#63965]
### Is your feature request related to a problem? Please describe.

The dangerously close message happens too late when you hit I or N in the dialog window, the Zed is in a nearby square. So it forces the user to interrupt his task as soon as a Zed comes in his range to avoid getting hit if he uses I or N.

### Solution you would like.

Allow the user to define the distance which triggers the hostile is dangerously close

### Describe alternatives you have considered.

Increase the distance to 2 or 3 squares

**Comment by Cenness** [comment]
In-game help  
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/distraction_manager.cpp#L22
and code  
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/game.cpp#L327
says it 5 squares.  

You not standing near something that can break line of sight, do you?

**Comment by matt32106** [comment]
I often have the monster ending just on an adjacent square when this happens. Ok, I'll try to make a save that shows the issue. Glad to know it is supposed to be 5 btw, thanks for checking.

**Comment by matt32106** [comment]
Ok, I managed to reproduce it:
In the save attached:
- hit | then wait 1 minute
- "Police bot spotted" answer I (ignore)
- "The police bot is dangerously close" answer Y to cancel waiting
- bingo the bot is in the adjacent square and NOT 5 squares away

Pb my save is too big (80MB instead of 25MB)

**Comment by Cenness** [comment]
Confirmed on
OS: Windows 10.0.19045.2604 (22H2)
Game Version: a15868c [64-bit]

**Comment by matt32106** [comment]
Bug opened instead -> #64033
