### ISSUE TITLE
Introduce performance testing

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#63967]
### Is your feature request related to a problem? Please describe.

Historically there have been quite a few performance problems. And they have been solved on case by case basis, leading to their reappearance, see recurring issues with inventory management/item pick-ups.

### Solution you would like.

Add matrix of saves:
* fresh start
* one month after, vehicle, some simple base
* half-year later, tons of items in base, npc followers doing their things
* middle of a mil. base warehouse
* middle of trans-coast logistics underground
* apartment/office tower
* exodii castle
* deep woods

and scenarios to test:
* load save: <5 minutes
* first 10 random move actions after loading: <10 seconds
* save game: <1 minute
* open inventory: <10 seconds
* pick up/drop items, non AMMO type, 1, 100, 1000, MAX_ITEM_IN_SQUARE: <10 seconds per item group
* pick up/drop items, AMMO type, while having some in inventory, 1, 100, 1000, MAX_ITEM_IN_SQUARE: <10 seconds per item group
* wield an item: <10 seconds
* wear an item: <10 seconds
* sleep: <10 seconds per in game hour
* craft: <10 seconds per in game hour

Both list aren't exhaustive and times are barely educated suggestions

### Describe alternatives you have considered.

Continue to watch contributors play whack-a-mole

**Comment by Raikiri** [comment]
Unfortunately automated performance testing can get really obnoxious due to task scheduling of the build machine. If something just happens to interrupt the build process on the build machine, you can get wildly inaccurate results and false positives.

So it's probably worth running each test multiple times and then discard outliers.

**Comment by Cenness** [comment]
Github has support for [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners) that can be [selected](https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-self-hosted-runners) for a specific job.  
Game is still single threaded so there is no need for a beefy machines. And as probably tests will require interfacing with a full build it won't be feasible to run them on each pr. That means periodic (daily? weekly?) runs. And that means that runners could be powered off for most time.
