### ISSUE TITLE
"Tried to remove item  error when using nearby antiseptic

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63963]
### Describe the bug

After updating from 0.G, I died on my Sky Islands save and went to heal up. I stood next to my loot pile and used E->m to activate my medications. After using a few Antiseptics, I started getting this error every time I used one:
![image](https://user-images.githubusercontent.com/5107449/222953326-3ad3bfe7-11a6-4810-96b6-b1fbeb176916.png)

The antiseptic effect seems to be applied, but the antiseptic item is not consumed.

I also got some errors about consumables when I loaded the save earlier, but they're not happening on the current save so I can't reproduce them.

### Attach save file

[Mantra-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10891497/Mantra-trimmed.tar.gz)

This is a Sky Island save, so I'm including the mod as well to make sure it works:
[CDDA-Sky-Islands-main.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10891502/CDDA-Sky-Islands-main.zip)

### Steps to reproduce

1. Install Sky Islands (for compatibility)
2. Load save
3. Attempt to use antiseptic

### Expected behavior

Normal behavior like using consumable should not throw errors.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 7762a54 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sky Island [skyisland],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

Presumably related to #63500.

Also all my bandages and medical gauze disappeared, except for a single item called "bandage (active)", which I assume is also related, but I figure that falls under the "at your own risk" part of updating on a running save.

**Comment by Terrorforge** [comment]
Update: This appears to happen you try to use the last unit of Antiseptic in any given bottle

**Comment by andrei8l** [comment]
/confirmed happens for heal tools with `ALLOWS_REMOTE_USE`, from the map/vehicle, that can't be picked up.

This assumption is no longer valid:

https://github.com/CleverRaven/Cataclysm-DDA/blob/a0af8a61227b08914ed42e07eb59a2916efece24/src/iuse_actor.cpp#L3336-L3340
