### ISSUE TITLE
Inventory Management through Effect on Conditions

### ISSUE THREAD

**Issue by Computer-Engineer-Man** [CleverRaven/Cataclysm-DDA#63985]
### Is your feature request related to a problem? Please describe.

Something that would be immensely useful would be a way to manage the players inventory through EoC's. Specifically, being able to do the following regarding items in inventory would make EoC's far more versatile.

- Spawning
- Deleting
- Un/equipping
- Editing
- Checking count

### Solution you would like.

{ "inventory_item", "ITEM_NAME", "spawn/delete/equip/unequip/edit", { "const": quantity } }
or
{ "inventory_item": [ { "ITEM_NAME", "spawn/delete/equip/unequip/edit", { "const": quantity } } ] }
and
{ "inventory_item", "count", "ITEM_NAME" }
or
{ "inventory_item", "name": "ITEM_NAME" }

The 2nd one would probably be easier to have since it would allow for easier multi-item management. Perhaps const is optional and edit would simply change the existing quantity while spawn/delete would add or subtract. 

### Describe alternatives you have considered.

Not being able to manage inventory through EoC's.

### Additional context

Any other suggestions would be greatly appreciated.

**Comment by Computer-Engineer-Man** [comment]
Also a way to save the current state of the inventory. Possibly done through a statement like the one below.

{ "inventory_item", "save/load", { count: SLOT_NUM } }

Where SLOT_NUM would simply be a arbitrary number where you can save inventory to an assigned number.

**Comment by Ramza13** [comment]
So you are already capable of spawning or removing inventory items.  u_spawn_item and u_remove_item_with will handle those cases.  u_has_item or u_has_items or u_has_item_category will handle testing if you have items.  What kind of editing would you like to see?

**Comment by Computer-Engineer-Man** [comment]
Primarily equipping and detecting and changing things like charges. A couple use cases below.

- Saving inventory states, namely equipped items and inventory items.
- Altering specific charges of items. I'm imagining a "charge item" spell that edits a item with charge less than max.
- Changing charges of items. Think a "water to wine" or "easy purification" spell.

Also forgot to mention above but it would be extra useful to detect wielded items.
