### ISSUE TITLE
Evac center camp doesn't have enough beds even if I put them there

### ISSUE THREAD

**Issue by silvermistshadow** [CleverRaven/Cataclysm-DDA#63986]
### Describe the bug

To start with, I'll describe some slightly related difficulties I've had with the faction camp system in regards to evac centers- the previous two worlds I made them on, I was not prompted to pick between bare bones and evac center camp types, and I had to make the bulletin board myself. Now on this world, I did get that prompt. And it made me a bulletin board. I put my food and stuff in, and went to select 'expand base'. 'Not enough beds' it says, so okay, I go make some beds. 7 of them. I check back in. 'not enough beds' ... how many does it need? It doesn't say, and no answered me in #player-help, so here I am. I made them on the first (ground) floor of the evac center, so there shouldn't be any problems as far as I know...

Oh and while I'm here... uh, how do you set up zones after the initial thing at the bulletin board? I couldn't find it in any of the action menu sections.

### Attach save file

[Bloomfield-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10893893/Bloomfield-trimmed.tar.gz)

### Steps to reproduce

1. Make a faction camp at an evac center (oh, this may be important: This is the first time I've made it at the evac center that I started at instead of one I found on the way to the refugee center, since the refugee center was, for once, not a thousand miles away... not literally but the others were far away)
2. Be told there aren't enough beds by the bulletin board after setting up the zones and dropping food in
3. Make beds
4. Still not enough beds?
5. ???
6. profit!

### Expected behavior

Either for there to be enough beds, or some kind of feedback on why there aren't enough beds, or if they have to be surrounding the bulletin board or something

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
You have to make the beds via the bulletin board by assigning an NPC to making it.  We unfortunately have no way to identify furniture constructed outside of the bulletin board method as belonging to the faction camp.  Please clarify if you made them using the NPC bulletin board tasks.

**Comment by Cenness** [comment]
>7 of them

this
https://github.com/CleverRaven/Cataclysm-DDA/blob/463060d0f30eb6ac6250bc255470cc39fe740763/src/basecamp.cpp#L289-L292
and this
https://github.com/CleverRaven/Cataclysm-DDA/blob/463060d0f30eb6ac6250bc255470cc39fe740763/src/faction_camp.cpp#L1400-L1405
seem to suggest that you'll need at least 16

**Comment by PatrikLundell** [comment]
The basecamp code gates expansions behind upgrade constructed beds such that you can build one expansion for every two beds. This means player/NPC constructed beds do not count.

Since I neither like it nor am able to see any logical reason for this arbitrary restriction, field basecamp version 2 and the bare bones basecamp both have the "number of beds" set to 16 immediately as basecamp construction to negate the restriction, but nothing has been done to other basecamps, as someone presumably made the restriction for some kind of reason (although I suspect it to be a forced upgrade path gamey reason).

It can be noted that field basecamp version 1 can only have 7 expansions, as its upgrade path only provides for 14 beds. I think other basecamps are subject to the same restriction.

The camp scanning functionality ought to be able to be modified to scan for beds, but that would change the progression logic for existing basecamps. It would also be possible to just remove the "beds required for expansions" tie completely (which would be my preference). However, that, again, changes logic that someone created for some reason.

**Comment by PatrikLundell** [comment]
You're already defined 3 expansions, and it might be that this that either you've topped out the number of beds the center can hold (although I thought it was more), or that further rooms are gated behind the construction of the cooking capability (yes, many base camps have rather strict and not particularly intuitive upgrade paths. Any of the 3 construction options will count as cooking capabilities.

**Comment by Maleclypse** [comment]
> The basecamp code gates expansions behind upgrade constructed beds such that you can build one expansion for every two beds. This means player/NPC constructed beds do not count.
> 
> Since I neither like it nor am able to see any logical reason for this arbitrary restriction, field basecamp version 2 and the bare bones basecamp both have the "number of beds" set to 16 immediately as basecamp construction to negate the restriction, but nothing has been done to other basecamps, as someone presumably made the restriction for some kind of reason (although I suspect it to be a forced upgrade path gamey reason).
> 
> It can be noted that field basecamp version 1 can only have 7 expansions, as its upgrade path only provides for 14 beds. I think other basecamps are subject to the same restriction.
> 
> The camp scanning functionality ought to be able to be modified to scan for beds, but that would change the progression logic for existing basecamps. It would also be possible to just remove the "beds required for expansions" tie completely (which would be my preference). However, that, again, changes logic that someone created for some reason.

Is there any reason at this point to keep the older defined upgrade path basecamps?

**Comment by PatrikLundell** [comment]
There would have to be a decision by those who make such decisions to make, or at least support such a change.

Apart from that, you have to tread carefully when updating basecamp progression to ensure you're not breaking existing basecamps that have been started but not finished.
