### ISSUE TITLE
No Warning for Dropping Finger Firelighter

### ISSUE THREAD

**Issue by Abstrusle** [CleverRaven/Cataclysm-DDA#63999]
### Is your feature request related to a problem? Please describe.

Dropping the finger firelighter onto the same tile as the player burns them for massive damage, and in some cases, immediately ends the game. There is no warning for this event, and it could easily occur with a simple mispress (such as when crafting and you drop the wielded item). Technically, this would apply to throwing as well, as according to the description, if you miss and hit your own tile, I doubt you'd still intend to light yourself aflame.

### Solution you would like.

The finger firelighter should rest on the ground until all remaining turns expire, and instead be activated to initiate a fire on that spot. This would be most appropriate for the spell's description, in that intent is necessary to ignite anything.

### Describe alternatives you have considered.

Considering there are exceedingly few reasons to set the player character flame, destroying the item entirely, rather than setting the tile alight, may be an option. Dropping the finger firelighter onto the same tile should at least warn the player.

**Comment by Victaria90** [comment]
This is still a major issue. Drop your fire lighter that says "is safe and will only ignite with intention" in the description you will instantly burst into flames. so will most things you drop it on.
