### ISSUE TITLE
Glare penalties stack up continuously while in sunlight and not protected, and then persist for a long time while back in the dark

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#64008]
### Describe the bug

As of latest experimental Glare got its duration increased, so it stacks up indefinitely the more you're out in the sun and will persist even after leaving the sunlight or putting on protective gear. Having protective gear in the first place will stop it though.

### Attach save file

n/a

### Steps to reproduce
1. Step into sunlight while not wearing sunglasses or a hat.
2. Wait a few turns and come back inside and then you still having glare.
3. Go back outside and wait much longer (10+ minutes)
4. Observe glare lasting a ton of time while inside.

### Expected behavior
Glare should be removed immediately upon leaving sunlight.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 799c507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by cake-pie** [comment]
> should be removed immediately

AIUI it shouldn't be immediate. It takes a few seconds for vision to recover from glare, a quick search will bring up stats / research studies esp. related to driving at night. But it certainly shouldn't persist to the extent of being measured in minutes.

> most people's eyes recover from glare within 3 to 5 seconds; however, recovery times of 7 seconds or longer is not uncommon. Typically the time to recover from glare increases with age -- [source](https://www.streetwisedrivingacademy.org/uploads/1/0/6/7/10672962/night_driving_and_visibility_3.pdf)

> glare recovery times were relatively constant up to about 56 years of age, after which they became significantly prolonged -- [source](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1475-1313.1989.tb00936.x)

> glare recovery time tends to increase with age to the point where it sometimes takes up to 25 seconds -- [source](https://sgi.sk.ca/pro-driver/-/knowledge_base/pro-drivers/night-vision)

> recovery times ranged from 0.45 s to 3.10 s for the myopic eyes and 0.30 s to 2.25 s for the hyperopic eyes -- [source](https://pdfs.semanticscholar.org/2b6d/de1c82effdead25f18ab5186e73bff136187.pdf)

> relatively low doses of alcohol significantly prolong recovery times following bright light exposure; these changes can be seen for several hours following alcohol ingestion -- [source](https://www.nature.com/articles/257481a0)

> use of alcohol delays recovery from glare during nighttime driving -- [source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3678693/)

Thus the issue stems more from:
- unexplained tenfold (!!!) increase in duration
- stacking? perhaps a cap is needed.
