### ISSUE TITLE
aircraft carrier ferals difficulty score 

### ISSUE THREAD

**Issue by alien10000** [CleverRaven/Cataclysm-DDA#64000]
### Is your feature request related to a problem? Please describe.

aircraft carrier ferals difficulty scores are too low especially the officers who have guns and are only ranked at 3 which means after some evolution they could be hidden in the UI also most of aircraft carrier ferals share the same ascii so you you have to manually scan all of them but some of them even share names to but have different weapons. 

### Solution you would like.

i think this information should be more clearly told to the player through the means already created to do so in the UI.

**Comment by Maleclypse** [comment]
I believe there is a manual difficulty field that can be set for monsters in json.   That's why I'm listing this as a good first issue. If I'm wrong someone feel free to correct me and I'll re label this.

**Comment by anoobindisguise** [comment]
I'd also like to complain that Devil Dogs and Twisted Leathernecks have the exact same icon (yellow Z). However they are not the same - one can punt you off the deck into the water, and the other cannot. Very easy to mistake the one that can for the one that can't which can be a pretty easy death.

**Comment by sas1018** [comment]
I can tackle this one if no one else has started work!
