### ISSUE TITLE
MSX+ new hairstyles are drawn in front of mutations incorrectly

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#64013]
### Describe the bug

Previous hairstyles (Hair: Color, Length) are layered behind mutations such as Lupine Ears, but new hairstyles (Hair, Length) are drawn in front of such mutations.

### Attach save file

n/a

### Steps to reproduce

1. Spawn a character with some variant of an old hairstyle (blond, black, red, white, gray, brown)
2. Mutate Lupine Ears or other ears and watch that your ears are drawn in front of your hair.
3. Change your hairstyle to the new hair system (Hair, Medium Length for example, to select pink, green, blue, etc) 
4. Observe ears are drawn behind the hair.

### Expected behavior

New hairs should layer like the old hairs.

### Screenshots

On the left is a character with Lupine Ears and blond hair. On the right is a character with Lupine Ears and green hair.
![bug](https://user-images.githubusercontent.com/56016372/223289569-a4ea0270-77a1-4c21-a361-570c4f76be9b.PNG)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 799c507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Golfavel** [comment]
This should probably be sent over to https://github.com/I-am-Erk/CDDA-Tilesets/issues

**Comment by Fris0uman** [comment]
No it looks like an issue on the code side, the new traits might not be on the right layer in there https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mutations/mutation_ordering.json , or color variants don't respect the layer system
