### ISSUE TITLE
Skitterbots and Hacks do not make sounds

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#64028]
### Describe the bug

This has been something I've noticed a long time ago but always chalked it to me not paying attention. 

Skitterbots and Hacks have no audio cues to them that would allow a player to "hear" them. Which is rather strange because it is very much impossible given one is (literally) skittering on the floor with its thin metal limbs and the other is (apparently) a drone with several with blades/taser/explosives, using propellers for its movement.

Given the recent PR for the Shocker Variants making sounds (#63402) (great job, by the way!), maybe it's time these get addressed too, seeing everything else in the game has its own sound or at least "a" way for the player to know of their presence via audio cues. It really isn't fun opening a door to then having a skitterbot or a Tazer Hack stepping adjacent to the player on the immediate same turn the door is opened.

### Attach save file

N/A - easy to spot in any condition

### Steps to reproduce

1. create a world, start in a lab and find a 3x3 section.
2. close one of the rooms off so they have no way to escape.
3. Ensure no cyborgs or zombies or any noisy creatures are nearby / within ear shot.
4. spawn several hacks and skitterbots in that closed room, no need to enter it;
5. Pass some time / "Wait" and observe as no sound is reported to the player.  

### Expected behavior

I would expect "skitterbots" to make a "skittering" sound, albeit a bit on the metallic side perhaps, unless their legs are made of plastic. 
I also expect drones to make drone noises (propeller sounds, similar to like a swarm of bees perhaps?)

### Versions and configuration

Windows 7 
(8765d30) - Build 2023-03-02-1307
default map created, no mods
Language: english.

**Comment by AnotherSeawhite** [comment]
I could also make this, but right now I don't have enough sanity to do githubbing in mobile.
