### ISSUE TITLE
Error in the string-indicator of physical activity

### ISSUE THREAD

**Issue by DedulkoN** [CleverRaven/Cataclysm-DDA#64023]
### Describe the bug

I noticed that in the indicator of physical activity, substitute strings are not used.
Checked the translation - it is.

### Attach save file

Not needed

### Steps to reproduce

1. Start game in russian
2. Run
3. Look to activity interfase

### Expected behavior

The string must be from the list of strings to be translated.

### Screenshots

![image](https://user-images.githubusercontent.com/36064675/223362070-c73a6208-3686-4570-a409-9fb6ed38e195.png)

### Versions and configuration

0.G - stable
language - russian

**Comment by RenechCDDA** [comment]
/confirmed 

Translations appear in the ru.po file, but they do not show up ingame.

![image](https://user-images.githubusercontent.com/84619419/223780395-575efadf-108a-4552-a1d4-d84c8730d964.png)


Here's a language with more coverage than Russian (according to transifex)

![image](https://user-images.githubusercontent.com/84619419/223777605-c85ede52-444e-4d42-b580-6394ab7fd489.png)

It's strange though, it *should* be returning a translated string?

https://github.com/CleverRaven/Cataclysm-DDA/blob/2f71c08df21be86657a19fe7fc2616f74bde1332/src/display.cpp#L717-L730

**Comment by ferociousdork** [comment]
The `text` entries here should pass the translation context:
https://github.com/CleverRaven/Cataclysm-DDA/blob/2f71c08df21be86657a19fe7fc2616f74bde1332/data/json/ui/activity.json#L7-L44

E.g. `"text": { "str": "Moderate", "ctxt": "activity description" }` instead of ` "text": "Moderate"`.
