### ISSUE TITLE
(V) menu should have a way to show items inside containers

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#64037]
### Is your feature request related to a problem? Please describe.

When looking at all nearby items with the (V) menu, items on corpses or in other containers aren't shown, which makes it challenging to loot after a big fight, since you need to visit each corpse separately.

### Solution you would like.

The (V) menu could include items inside containers. Perhaps this could be toggleable?

**Comment by mqrause** [comment]
See #56623. Corpse pockets currently are the only transparent ones, but you aren't meant to be able to see the contents of all containers.

**Comment by matt32106** [comment]
Why would you see from a distance the content of most containers?

**Comment by nornagon** [comment]
Cool, #56623 has all the info I wanted.
