### ISSUE TITLE
Installing certain CBMs causes crash to desktop

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#64036]
### Describe the bug

Having Rubik install Artificial Night Generator CBM caused a crash to desktop.
Installing bio_recycler also causes a crash. Removing "enchantments" entry from bio_recycler cbm stops the game from crashing.

### Attach save file

bio_night https://ufile.io/vfpd3c9w

bio_recycler https://ufile.io/bbo1cqhj

### Steps to reproduce

1. Get Artificial Night Generator CBM
2. Ask Rubik to install it
3. Observe silent crash to desktop during the activity

### Expected behavior

No crashing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.329 (2004)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Unable to reproduce.

![image](https://user-images.githubusercontent.com/84619419/223605419-e983abf9-7bb5-483f-bfca-654f4166d137.png)

Please provide additional details or a reproduction save.

**Comment by RenechCDDA** [comment]
Just for good measure I repeated until the installation failed. No crash.

![image](https://user-images.githubusercontent.com/84619419/223606735-659c95ad-1250-4205-a21a-579114ab1d6d.png)

Also tried enabling bionic slots. No crash.

**Comment by andrei8l** [comment]
It only crashes with the msvc build. The other builds are find and ASan doesn't find any issue either.

**Comment by akrieger** [comment]
Can someone please reupload the save to gdrive or some other service that doesn't set off alarm bells from my antivirus/adblocker?

**Comment by andrei8l** [comment]
https://send.vis.ee/download/1ef3b7a34c3ef857/#6dahuHJvIgAaF2vIC7O_rA

**Comment by andrei8l** [comment]
Based on the crash log provided by akrieger, this simple patch should fix it
```diff
diff --git a/src/bionics.cpp b/src/bionics.cpp
index 48554acf89..a2434af44a 100644
--- a/src/bionics.cpp
+++ b/src/bionics.cpp
@@ -2785,6 +2785,7 @@ bionic_uid Character::add_bionic( const bionic_id &b, bionic_uid parent_uid )
         }
     }
 
+    invalidate_pseudo_items();
     update_bionic_power_capacity();
 
     calc_encumbrance();
@@ -2798,8 +2799,6 @@ bionic_uid Character::add_bionic( const bionic_id &b, bionic_uid parent_uid )
     }
     effect_on_conditions::process_reactivate( *this );
 
-    invalidate_pseudo_items();
-
     return bio_uid;
 }
 
```
but I don't have access to msvc to test.

**Comment by SurFlurer** [comment]
> but I don't have access to msvc to test.

@andrei8l  I tested with this patch and can confirm that this patch works! Thank you!
