### ISSUE TITLE
Placeholder "child" enemy appears (due to fungalization?)

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#64039]
### Describe the bug

I was attacked by a few enemies simply called "child" whose description states that they're placeholders that should not be seen by the player.

This happened while I was burning down a "fungal flowers" location with a mass grave right next to it, so I'm guessing it has something to do with zombie children not properly turning into fungal zombies.

### Attach save file

[Magic-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10913146/Magic-trimmed.tar.gz)

### Steps to reproduce

I'm guessing spawn a zombie child next to some fungaloids, but for an example of this having already happened consult the provided save file.

### Expected behavior

Placeholder monster does not appear in the game world.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/223526989-61871749-dfb4-4edc-b115-8d5fed687379.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 463060d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by Karol1223** [comment]
Fixed by #63996

**Comment by Terrorforge** [comment]
Closing this, then.
