### ISSUE TITLE
Can't access items in appliances with Examine after connecting them to the grid

### ISSUE THREAD

**Issue by Warfoniusz** [CleverRaven/Cataclysm-DDA#64042]
### Describe the bug

I remember playing a few months back and being able to access items in my frige/oven/freezer etc. with [e]xamine terrain, furniture or items after they've been connected to the grid. Now it's not possible, as only the appliance menu pops up after examining. The only way to access items in the appliance is to use Advanced Inventory Manager.

### Attach save file

N/A

### Steps to reproduce

1. Connect fridge (or other appliance with storage) to the grid
2. Put items into it
3. Try to get them with [e]xamine

### Expected behavior

The expected behaviour is to be able to get items from the appliance either by using [g]et items in the appliance menu or having the item selection appear after closing the appliance menu.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Alm999** [comment]
You can also use g'rab command to get stored goods.

**Comment by aahue1889** [comment]
Looking into

**Comment by aahue1889** [comment]
I can confirm that this is happening
- in 0.F-13360
Hitting 'e' will open the Grid Menu 
![image](https://user-images.githubusercontent.com/8581536/223845690-badc40fd-2e3d-430b-8bad-cb54edfe37c5.png)
----
Checking older versions

**Comment by aahue1889** [comment]
![image](https://user-images.githubusercontent.com/8581536/223854941-eaa20ea4-e5f6-46db-8088-f0169776f4c9.png)
Build version: 0.F-3

Does not open a 'grd menu' at all so user will not experience this in older versions
----

I don't think this is a bug; but a feature change. I can work on making the changes in the backend if I have confirmation that this is truly a bug.

**Comment by aahue1889** [comment]
Also confirmed on the 0.G Stable release
- e no longer checks contents of fridge, instead it pops up the 'Grid Menu'
-
