### ISSUE TITLE
[feature request] using the exodii to "travel to other dimensions"

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64050]
### Is your feature request related to a problem? Please describe.

i've been reading #lore-and-design and one of the comments got me thinking. What if you finish enough tasks for the exodii (either completing all of their missions, or earning high trust) they would allow you to travel with them once or more to other dimensions. since the lore document mentions they jump to other worlds due to a "time limit" caused by the blob, making the world too dangerous to live in.

technically this would transport your character, with everything they can carry to a new world, essentially a new save. from that they can choose to either use the same world parameters, or alter them. And they would spawn in the exodii faction base, or, due to portal storm shenanigans, be dropped off somewhere.

i think this would be a nice idea, if you got a nice character, and you want to continue playing them, but with a new world, from things like old saves, and/or corrupted worlds (bugged missions etc). or the enemies got difficult (i could see this happening with future enemy additions. or really fast evolution)

i would imagine this resetting everything, including the exodii.

### Solution you would like.

none

**Comment by actually-the-artificer** [comment]
This could also be a way to end the game without player death.

**Comment by estebandellasilva** [comment]
Could also be an intresting starting scenario

**Comment by kevingranade** [comment]
This set of features would take literally years to build,  and it's already right there in the design document.  I'm not saying it's not worth doing,  but it's definitely not worth having an issue sitting aroubd for the next several years just to highlight it.
