### ISSUE TITLE
Blunt Damage Causes Bleeding

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#64060]
### Describe the bug

Blunt only weapons are causing bleeding. 

### Attach save file

N/A

### Steps to reproduce

1. grab/spawn any blunt only weapon
2. hit something
3. examine status of monster

### Expected behavior

blunt only damage should not cause bleeding, as lacerations as a effect aren't simulated as far as I know

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: 9777f4e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sky Island [skyisland],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by Kantonine** [comment]
Quarterstaff with only starting traits 
[Coalgate-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10921602/Coalgate-trimmed.tar.gz)

**Comment by matt32106** [comment]
Can you try to hit one of your fingers/hands/toes with a hammer to make sure it does not bleed? In my experience it can bleed. 
Or use a baseball bat on your head/nose, I am sure there will be some bleeding.

**Comment by anoobindisguise** [comment]
I see this happen with my bare fists, a zombie was Bad Bleeding by the time I finished punching it to death.

**Comment by Venera3** [comment]
Yeah, I think my deprecation of make_bleed might have messed something up along the line. I'll look into it.
