### ISSUE TITLE
(Blackpowder ammo) Firearm fast-degrade durability to XX

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#64067]
### Describe the bug

Not sure if intended...

Anyway, Flintlock guns in current have a tendency break after one shot and require a full repair with the Firearm Repair Kit which in itself is done incrementally so it takes in excess of 75+ Solder and 5+ Scrap Metal to repair. 

Issue is more due to the gun being insta-ruined and not going down in durability levels.

Tested with Debug spawning multiple rifles and multi-firing 100+ shots at a Turkey. Gun will insta-ruin at random after a shot. 

### Attach save file

[Boles Acres Megafauna-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10924319/Boles.Acres.Megafauna-trimmed.tar.gz)

### Steps to reproduce

- Craft Flintlock Musket/Rifle and load with Paper Cartridge choice of ammo.
- Fire at target or monster.
- Gun randomly will break entirely to XX quality state and not go down durability levels. 

### Expected behavior

Firearms should proceed to degrade under Durability system esp since Black Powder Fouling mechanic is in play as well-not explode into a million pieces. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 936b383 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna]
]

### Additional context

- Issue only tested with Paper Cartridge ammo. Not sure if problem persists with Shot ammo.
- If "Fouling and Lubricate" Mend was used before repair/durability failure: Fouling status reappears as soon as Gun is Mended. 
- Added: using Lubricate outright breaks the gun if used when weapon is at full durability. Wtf.

**Comment by RenechCDDA** [comment]
I wasn't able to get them to rust instantly, but the rest was extremely quick (~50 minutes), in line with the confirmed bug for 
* #63515

Behavior does not appear to have changed since that report.

**Comment by evankimori** [comment]
> Behavior does not appear to have changed since that report.

Which is odd because the previous 2ish Experimental builds didn't have this issue AFA I played. I'm playing more Innawood than DDA admittedly and as such: the Flintlocks are the pinnacle of guns for the modpack for a while and never encountered this issue before updating to 936b383.

Edit-added an additional issue RE: the Fouling re-appearing after Repairing.

**Comment by evankimori** [comment]
Okay and just discovered that Lubricating one when at full durability insta-breaks the weapon now. Wtf.

**Comment by RenechCDDA** [comment]
Just to be clear are you reporting the damage to XX happening in a period of time shorter than 5 minutes or so? That is to say, *different behavior than the other bug report*? I tried again with your save, and it took approximately 3 hours for it to degrade.

![image](https://user-images.githubusercontent.com/84619419/223827132-8595e546-cfdb-44fe-9231-4cf4b23061e0.png)

If yours is degrading within a few minutes or *only a handful of turns* then that is a new, separate bug.

**Comment by evankimori** [comment]
Ok wow. I never had that 'Rusting' issue show up in past Experimental in my experience but that isn't normal at all.

In addition to your screenshot there: the 'passive rusting' after firing a round AFTER Repairing and NOT using Lubricate is breaking down the weapon to where when you try to Lubricate-it insta-breaks the gun **in the time** it takes to Repair/Mend-Lubricate it seems...at least out of my testing so far.

Will do some more testing at home as I have to hit the commute but this is def a new issue I have not encountered with past builds.

**Comment by evankimori** [comment]
Updating to b1675c4 tonight and will do some more testing.

**Comment by evankimori** [comment]
Tested as well with a worldgen and new character, editing Character to 10 Mechanics to Accurize Gun and got this crash attempting to Lubricate gun:

 ```
 (dbghelp: RtlUserThreadStart+0x21@0x7ffc8c1c26a1[ntdll.dll+0x526a1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
```

**Comment by evankimori** [comment]
Same setup as previous test with build and Game Report.

Tested with: 
- M1 Garand and Black Powder-loaded 30-06 ammo. 
- Winchester M70-Black Powder 300 ammo.

Black Powder Fouling leads to Faulty prefix being attached (to Garand) and total XX Rusting happens within 3600+ heartbeats. 

Issue seems across the board with Black Powder loaded ammo w/respective firearms. Should I test more firearms and ammo loads?
