### ISSUE TITLE
Flannel Jacket Inconsistency

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#64066]
### Is your feature request related to a problem? Please describe.

Flannel Jackets are described as being made from denim, yet haven't been touched by the introduction of denim as a material separate from cotton. 

### Solution you would like.

Update the flannel jacket stats to reflect recent design choices.

### Describe alternatives you have considered.

Change the description for the jacket.

**Comment by Zireael07** [comment]
Uh, as someone who often wears flannel, it's very much NOT denim. It's soft not thick. I think the material should stay as "cotton"

**Comment by strategineer** [comment]
huh... If that's the case, I wonder if the "flannel" jacket in-game was meant to be a plaid/tartan jacket instead?

[From Wikipedia](https://en.wikipedia.org/wiki/Flannel)

> The term "flannel shirt" is often mistakenly used to refer to any shirt with a [plaid](https://en.wikipedia.org/wiki/Plaid_(pattern)) or tartan pattern. However, 'flannel' refers simply to the fabric, and not all flannel shirts are plaid.
