### ISSUE TITLE
(936b383) Blanching > Blanched Acorn issues 

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#64065]
### Describe the bug

Minor complaint of the changes to the system from previous setup AND a current issue/bug. 
(Disregard complaints if necessary. I have played Experimental with the changes since the beginning and this is an opinion.)

Complaint: 
- Current Blanching Acorn system does not work well w/ (A)ctivation to test items in bulk when they are ready. Activating the item in a container extracts a single, dropped item- needing spamclick Activate to 'test' for completion. 
- This as such has lead to a very unwieldy spam Activate  and/or (E)at to check if Acorns are ready-either filling Hunger/Drink meter oddly and once full: you have to wait until you are hungry again to test or risk throwing up or needlessly delayed processing.
- As such from above: it has made Acorns -much- less attractive to make Cooking Oil as other sources are significantly easier. (e.g. Shelled Nut(s) or Fat > Cooking Oil etc)
- **_tl;dr_** This single use processing system is pointlessly frustrating to process use, much less for large batches. 

Bug:
- Blanched Acorns generated from Blanching Acorn recipe does not show up as Nut Paste ingredient.
- Spawning Blanched Acorns from Debug works but the player recipe result does **not**.

Suggestion:
- Alongside adjustments or bug fixes on back end code: I feel like at this point Nutrition should be removed from Blanching items to remove the micromanage and the container-activate system can be replicated a-la Rising Cream Jar or Sealed Yeast Culture for ease of use. 

### Attach save file

[Boles Acres Megafauna-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10923414/Boles.Acres.Megafauna-trimmed.tar.gz)

### Steps to reproduce

Spawn Debug Blanched Acorns (Fresh) from Debug works.

Use Blanching Acorn Recipe, wait out in-game time, recipe result of Blanched Acorns does not work for any recipe requirement. 

### Expected behavior

I'm willing to do more testing but the Acorn changes are relatively annoying to use, even given that the game spawns/harvests an obscene amount of them per season.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 936b383 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna]
]

### Additional context
Error attached when trying to Unload Blanched Acorn from Canning Pot container after Eat/Activate testing.

```
 DEBUG    : Tried to handle_liquid a non-liquid!

 FUNCTION : bool liquid_handler::can_handle_liquid(const item&)
 FILE     : src/handle_liquid.cpp
 LINE     : 440
 VERSION  : 936b383
```

**Comment by RenechCDDA** [comment]
>Blanched Acorns generated from Blanching Acorn recipe does not show up as Nut Paste ingredient.
>Spawning Blanched Acorns from Debug works but the player recipe result does not.

/confirmed as this is indeed happening and a bug. `acorns_blanching` are a liquid. `acorns_blanched` is a **solid**. Transform doesn't seem to be able to handle that, and the item factory (for crafting) is expecting your `acorns_blanched` to be a solid. When it finds them in liquid form, it (silently) discounts them as a valid crafting ingredient.

>Error attached when trying to Unload Blanched Acorn from Canning Pot container after Eat/Activate testing.

Confirmed and related, as above.

>Current Blanching Acorn system does not work well w/ (A)ctivation to test items in bulk when they are ready. Activating the item in a container extracts a single, dropped item- needing spamclick Activate to 'test' for completion.

Confirmed. See also #51417 for a feature request related to it. I should probably go looking for that code at some point.

**Comment by flybye3o6** [comment]
quick fix would be to remove the liquid state
im already working on this though it mite take awhile for what im planning, iv tried a few methods and havent liked many of them, if you have suggestions id love to hear them, expect the blanching process to completely change
also what are the most common containers people use to put acorns_blanching into, also needs to be innawood compatible so clay pots n such

**Comment by evankimori** [comment]
> quick fix would be to remove the liquid state im already working on this though it mite take awhile for what im planning, iv tried a few methods and havent liked many of them, 

First off: thank you for your hard work in advance. :) <3 Cheers! Always great when feedback isn't treated as hostile. 

>if you have suggestions id love to hear them, expect the blanching process to completely change also what are the most common containers people use to put acorns_blanching into 

Keeping the minimum batch processing @ 2x or4x Acorns is a good start because even early Innawoods Spring-you do not find a lot of them w/average of 4-8 which can fit in Clay Pot/Clay Urn which are basically standard issue items in the mod because without those: you're not lasting a week. Given my testing some months back:
- Clay Teapot - 2 units.
- Clay Crucible - 4 units.
- Clay Pot - 8 units.
- Clay Urn - 16 units.
- Clay Canning Pot - 100 units.

**THESE MAY HAVE CHANGED in recent Experimental so grain of salt.** 

Upgrading from here: 
- Wooden Bucket
- Wooden Barrel
- 60L Tank (needed anyway for Steel processing late-Innawoods and tank is Tool-usable even while filled)
- I KINDA don't recommend processing be put into Construction-based tanks but that's just me. Your call there.

>also needs to be innawood compatible so clay pots n such also tying to find a way to auto transform so you dont have to keep checking if its done

Danke! The batch processing of Activation from some Experimental back (circa Nov 2022...ish?) worked back then but I can't explain how the background worked for that so regressing to that style may (not) work if code and association has changed. :(

Either way: you can count on me to test any ideas you come up with. Not sure what else I can contribute persay to add to design end other than removing Nutrition value to prevent Auto-Eat triggering but that's a personal choice for me as sometimes when long-crafting, I end up consuming all my Blanched and then wonder why my character is pissed off.  XD Bounce some ideas off the thread here if needed or message on Discord!

**Comment by flybye3o6** [comment]
my first attempt from months ago mite of been my best attempt but im not in love with it, it dose make it so when you activate a stack it dose the whole stack but adds an extra step and item, but if i can make it auto transform when the times up that will be a step removed

for the auto transform i was thinking about testing delayed action instead of delayed transform and have some way for the item to activate as soon as it comes into existence, should work for both crafted or spawned, i will do that some other time ill try to get this fixed asap

i was inspired by `Rising Cream Jar` to do something like that but when i tried it months ago the recipe and item bloat got a bit much, but if people dont mind having a bunch of nested recipes for each vessel and extra items i will take another look at it

im also trying to get a weak tannin byproduct out of it, with other plans to make tanning more accessible especially for innerwood early game, this is a larger project then i thought and i need to do more research which is going to take me time but likely my first attempt was my best

**Comment by flybye3o6** [comment]
okay i did some testing and there is a bug with all delayed transform actions
test fermenting yogurt
spawned in, waited the time, activated it
transforms one and drops it on the ground and doesn't activate the rest
also tested soft adobe bricks
spawned in, waited the time, activated it
transforms only one but keeps it in inventory and doen't activate the rest

**Comment by evankimori** [comment]
That's pretty odd if it is those items follow the same template as your Blanching > Blanched or vice versa...

I'm the last person to ask about back end code but have you bounced this issue in Discord off the other coders to see some additional input?

**Comment by flybye3o6** [comment]
yea a coder will need to take a look at it, i took a look at item.cpp and iuse_actor.cpp and i couldnt figure it out, i didnt test this yet but it seems to try to weld the item when you activate it which is why its dropping liquids on the ground

i also realized something, why i gave up on `Rising Cream Jar` because i tried giving it spoilage, and because its all 1 item when the item spoils it takes the glass jar with it, i had the idea that before it disappears it could delete itself and spawn the jar in its place, but i didnt know how to do that

**Comment by evankimori** [comment]
Thank you for your attempt anyway. Hope someone with more know-how will notice this in time or a solution comes to you. :) <3

**Comment by flybye3o6** [comment]
also curing roe is another transform item that goes from liquid > solid (post apoclayptic caviar) with delayed transform and it too cant be used for crafting (caviar and egg sandwich) but in 0.F it works just fine, so its not a problem with liquid > solid or any state change

**Comment by RenechCDDA** [comment]
As of 0039fccba34303ce72b6fe1d80b38f6b877436d1 this appears to have been fully resolved. Not 100% sure what resolved the inability to craft into nut paste, but the stack transformation was definitely thanks to #65245

**Comment by NafenX** [comment]
I'm still getting weird bugs with blanched acorns on current experimental. Finishing the process of blanching gives an error about treating a non-liquid as a liquid, the result often ends up with blanched acorns inside of a container that have 0.00 volume and don't show up when trying to craft using blanched acorns (I have over 100 blanched acorns on the floor, but in crafting screen it shows I have only 69.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/28961736/b5d85baf-fe8a-47d9-953d-94b8a2baaa18)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/28961736/d02d30cb-0cdc-4d6c-93f8-e34b09427721)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/28961736/5efec9d5-233b-46ed-ad5d-ec950748395b)
