### ISSUE TITLE
Crater map specials that kill something on spawn count as player kills

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#64075]
### Describe the bug

As I was wandering through the plains having not attacked anything yet, I suddenly lost Pacifist conduct and saw hummingbirds die from some explosion. I then saw all the corpses are inside a crater map special.

### Attach save file

N/A

### Steps to reproduce

1. Spawn new character so you have Pacifist conduct(w/ a high spawn rate to make reproduction easier).
2. Wander through the plains or other terrain where craters can spawn until one happens to be created on top of something living.
3. Watch you lose Pacifist conduct and their deaths be added to your kill count.

### Expected behavior

Existing near craters doesn't count as killing

### Screenshots

![image](https://user-images.githubusercontent.com/99621099/223909545-852cd4e4-c4a1-4bad-b579-3485db3f6d1c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: b1675c4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by AcidAntOnAMinefield** [comment]
Mentioned it in 63914 too.

**Comment by terryjacob200** [comment]
Sorry to comment on a stale issue but I encountered this bug.

Am on 0.G stable.  Was driving across a field when the explosion that happens with the crater special happened and killed several crows.   Three crow kills were added to my kill list despite them being killed by mapgen.

Mod list:  no_npc_food  ,personal_portal_storms ,no_fungal_growth ,crazy_cataclysm.
