### ISSUE TITLE
Climbing down with a grappling hook removes stepladder.

### ISSUE THREAD

**Issue by terribleperson** [CleverRaven/Cataclysm-DDA#64085]
### Describe the bug

If you climb off a roof above a stepladder while you have a grappling hook, the game asks if you want to climb down with your grappling hook. If you say yes, the stepladder is replaced by the grappling hook rope. Removing the rope does not restore your stepladder. 

### Attach save file

[Testworld-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10937140/Testworld-trimmed.tar.gz)

### Steps to reproduce

1. Spawn a stepladder. 
2. Activate the stepladder to place it against a single story building.
3. Spawn a grappling hook and make sure it's in your inventory.
4. Use the stepladder to climb onto the roof.
5. Climb down off the roof over the stepladder. When prompted to use the grappling hook, say yes.
6. Observe that the stepladder no longer exists. 
7. Remove the rope to find that your stepladder is well and truly gone. 

### Expected behavior

Using a grappling hook should not delete your stepladder. I would expect the grappling hook to not be offered as an option if a stepladder already exists in that tile, or maybe the stepladder could be kicked to the side when you climb down. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by flybye3o6** [comment]
grappling hook is a furniture when deployed so will override any other furniture in that tile
suggested fixes are to have a check if there is furniture already in the tile and give a warning asking if you want to use your grappling hook [yes use it] [no but climb down] [cancel]
if grappling hook could function in a different tile layer on top of terrain, furniture, traps and fields

**Comment by Night-Pryanik** [comment]
I guess this is the same as #58745.

**Comment by anothersimulacrum** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/58745
