### ISSUE TITLE
Armor sort menu CTD on non-wearable items

### ISSUE THREAD

**Issue by NoddingCrow** [CleverRaven/Cataclysm-DDA#64093]
### Describe the bug

The armor sort menu crashes to desktop when navigating over items that should not be wearable but that are still equipped - in my example, the joint roach which is not itself equippable but is left equipped after an equipped joint burns down. Other confirmed example includes cigarette stub similarly. 

Appears similar to #64058 so paging @bombasticSlacks as requested! 

### Attach save file

[Test World Please Ignore-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10940322/Test.World.Please.Ignore-trimmed.tar.gz)

### Steps to reproduce

Load attached save file, or spawn in a joint or cigarette, light it, and wear it. 
Wait 10 mins for the joint or cigarette to burn out.
Open armor sort menu +, navigate over the joint roach or cigarette stub that the character still has equipped.
Experience your desktop.

### Expected behavior

Not hard crashing to desktop. Perhaps auto-unequipping non-wearable items, though I'm unsure how many other cases this might include.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: fac3c33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10940495/debug.log)

**Comment by bombasticSlacks** [comment]
Thanks

**Comment by sarseev** [comment]
Happens to me as well but CTD is caused even by bionics that add pseudo equipment items such as battery charging compartment. Test save attached, CTD started appearing after installing the battery system CBM. Haven't tried @bombasticSlacks patch yet.
[Sewaren.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10943660/Sewaren.zip)
