### ISSUE TITLE
Using stairs next to ledge prompts player to "climb down"

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#64098]
### Describe the bug

Pressing > to go down stairs/ladders when you're next to a ledge prompts you to "climb down" instead of just going down the stairs.

### Attach save file

[Magic-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10942013/Magic-trimmed.tar.gz)

### Steps to reproduce

1. Find (or build) a ladder next to a ledge
2. Attempt to go down it

### Expected behavior

I just climb down the stairs.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/224316287-8ecee1f3-fbf8-476f-a0bf-7f8052eaaa9a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: fac3c33 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

Presumably caused by #63900

edit: confirmed. reverted to a version just before #63900 and the problem went away

**Comment by PlatoSoft** [comment]
Can confirm, this has me stuck on a Silo atm.

**Comment by Night-Pryanik** [comment]
How would you like this to be fixed? 
Add an additional `Descend `option in `Climb where?` menu? More flexible, but also more keypresses.
Or simply prevent appearing `Climb where?`menu when standing on stairs next to ledge?

**Comment by RAldrich** [comment]
I think preventing the `Climb where?` menu from appearing when standing on stairs is the much better solution. It is intuitive, preserves the prior functionality, and players can still climb down if they need to for some reason by activating the ledge as the used to have to do. Adding extra keystrokes for basic movement should be avoided.

**Comment by Terrorforge** [comment]
On the rare occasions I need to actually climb somewhere, I just (e)xamine the gap anyway. I would prevent the menu from showing on stairs.
