### ISSUE TITLE
Getting info that effective skill will be lower because of missing proficiencies when all proficiencies are learned  

### ISSUE THREAD

**Issue by Neokami** [CleverRaven/Cataclysm-DDA#64092]
### Describe the bug

All crafts that require proficiencies in which you have all learned are showing with the "Your effective skill will be ## levels lower than normal" it seems that it is 1 * the number of proficiencies required(if learned) is showing in the craft menu

### Attach save file

N/A

### Steps to reproduce

1. learn proficiencies for crafting
2. look at craft menu when proficiencies are learned

### Expected behavior

for the effective skill level to be only lower for each proficiency not learned/skill level not met

### Screenshots

![image](https://user-images.githubusercontent.com/6130984/224275204-057a0a2e-aa4b-4d8f-8d3a-d20cec5b5209.png)
![image](https://user-images.githubusercontent.com/6130984/224275271-96653880-ec61-49db-a871-07ca68706879.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: fac3c33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
My fault, fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/64089
