### ISSUE TITLE
Downloaded encryption codes (for mission) not shown on USB drive - save attached

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#64126]
### Describe the bug

I am doing the download encryption codes mission. I opened the console, download the codes but they are not shown on the USB drive. See save attached.

### Attach save file

[Usher-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10946853/Usher-trimmed.tar.gz)

### Steps to reproduce

E to open console
Enter 3 times
The console says Software downloaded
Look at inventory, the 3 USB drives all look empty (it seems that in fact the codes are downloaded to the USB drive but they are just not showing in the inventory window).

### Expected behavior

One of the USB drives should display the fact that it contains the codes

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 7762a54 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    Bionic Professions [package_bionic_professions]
]

**Comment by aahue1889** [comment]
Going to try and Repro for Windows

**Comment by anoobindisguise** [comment]
It looks like the bug where USBs don't show their contents struck again. It happens once per experimental apparently.
You probably have the software, the usb js just not telling you.

**Comment by matt32106** [comment]
>  the USB is just not telling you.
Yes! I tried teleport to base and I could complete the mission. I'll EDIT the dezscription of the bug, thanks.

**Comment by aahue1889** [comment]
Do you know if there is a fix in the making for this? I am interested in looking for a fix.

**Comment by aahue1889** [comment]
Repro Steps:

I can confirm this issue on windows OS as well
-----

To quickly repro Spawn a Random NPC on Overmap

![image](https://user-images.githubusercontent.com/8581536/224508530-e118cbac-c6ca-424d-93f6-dd0d0aabf93c.png)

Go to Edit Player/NPC from debug menu and select newly spawned NPC and "Add Mission" to them

![image](https://user-images.githubusercontent.com/8581536/224508591-fc7163bc-b05b-4a19-bb0f-408a05817ec0.png)

Add Download encryption codes

![image](https://user-images.githubusercontent.com/8581536/224508642-38593691-03b4-43fc-bb48-8deda9fba046.png)

-----

Speak to NPC and Accept mission - Debug Teleport to the expected location and find the Computer with Encryption Codes

I had to find them here - -2 Down in Lab

![image](https://user-images.githubusercontent.com/8581536/224508816-d3684c82-1b88-4384-adae-bb3ae3046fb0.png)

![image](https://user-images.githubusercontent.com/8581536/224508834-49a1ecf1-26e0-4be6-888f-7ebb332c2d91.png)

---

After the download you will no change the the USB you downloaded

![image](https://user-images.githubusercontent.com/8581536/224508872-6db7ffe6-2731-4b1a-99dc-5c8ae62a9541.png)

--

However (as mentioned above)
We can still complete the mission; its just that both the USB and Mission do not update upon you completing the download. 
![image](https://user-images.githubusercontent.com/8581536/224509153-571b1c90-7201-44e5-9713-6e326b2eb88f.png)

**Comment by aahue1889** [comment]
So if I were to go about fixing this:

I'd look for how "pocket_type": "SOFTWARE" can be surfaced in the Item description

```
  {
    "type": "TOOL",
    "id": "usb_drive",
    "symbol": ",",
    "color": "white",
    "name": { "str": "USB drive" },
    "description": "A USB thumb drive.  Useful for holding software.",
    "price": 10000,
    "price_postapoc": 10,
    "material": [ "plastic" ],
    "weight": "18 g",
    "volume": "5 ml",
    "pocket_data": [
      **{ "pocket_type": "SOFTWARE", "max_contains_volume": "1 L", "max_contains_weight": "1 kg" },**
      {
        "pocket_type": "EBOOK",
        "rigid": true,
        "max_contains_volume": "1 ml",
        "max_contains_weight": "1 g",
        "weight_multiplier": 0.0
      }
    ],
    "to_hit": -3,
    "flags": [ "MC_USED" ]
  },
```

**Comment by andrei8l** [comment]
I broke this in #63579

Quick fix:
```diff
diff --git a/src/item.cpp b/src/item.cpp
index 43aedd8496..e106d0c510 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -13758,7 +13758,9 @@ item const *item::this_or_single_content() const
 
 bool item::contents_only_one_type() const
 {
-    std::list<const item *> const items = all_items_top();
+    std::list<const item *> const items = is_software_storage()
+                                          ? all_items_top( item_pocket::pocket_type::SOFTWARE )
+                                          : all_items_top();
     return items.size() == 1 ||
            ( items.size() > 1 &&
     std::all_of( ++items.begin(), items.end(), [&items]( item const * e ) {
```
I would prefer to see `item_contents::all_items_top( const std::function<bool( item_pocket & )> &filter )` exposed at the `item`-level though.
This also needs a test unit in `item_tname_test.cpp`

**Comment by aahue1889** [comment]
So what is the etiquette for something like this? @andrei8l 
- Are you going to be responsible for the fix?

**Comment by andrei8l** [comment]
> So what is the etiquette for something like this?

I've fixed this one but don't be afraid to just submit bug fixes. You won't step on anyone's toes.
