### ISSUE TITLE
Broken battery tools will lose the functions that doesn't require battery

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#64122]
### Describe the bug

Title.

### Attach save file

N/A

### Steps to reproduce
Play on the version prior to #64116 for convenience

1. Spawn a mess kit with medium battery.
2. Electrocute yourself or dive into deep water.
3. Make sure the mess kit is broken
4. Activate the mess kit

### Expected behavior

I expected it to at least work like a small camping pot.

### Screenshots

![Screenshot_20230311_075510_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/52661206/224444018-dd34d43a-2d25-45e4-a5e5-229c40ba308d.png)

### Versions and configuration

- Game Version: 97c2e25 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by AnotherSeawhite** [comment]
#64116 detonated the whole bug, but there could be still an issue where you can't use a feature that doesn't matter whether the tool is broken or not.

**Comment by Karol1223** [comment]
> #64116 detonated the whole bug, but there could be still an issue where you can't use a feature that doesn't matter whether the tool is broken or not.

The function can't be bugged when the function is removed

**Comment by anothersimulacrum** [comment]
> #64116 detonated the whole bug, but there could be still an issue where you can't use a feature that doesn't matter whether the tool is broken or not.

If that's your intent, please re-title the issue.
