### ISSUE TITLE
Having to select items twice to drop them

### ISSUE THREAD

**Issue by Neokami** [CleverRaven/Cataclysm-DDA#64135]
### Describe the bug

When using `D` to drop items you move the things to the right side to drop, press enter and nothing drops but the window stays open and you need to move the items again and the second time you press enter to drop they drop.

### Attach save file

[Hat Creek-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10947656/Hat.Creek-trimmed.tar.gz)

### Steps to reproduce

1. open multidrop menu
2: Select items you want to drop
3: Press enter, items will not drop and drop list will be reset
4: select items again
5: press enter to drop
6: items will drop

### Expected behavior

items will drop first time you selected them and press enter

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 59c0d6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
/confirmed broken by #64106

specifically this line https://github.com/CleverRaven/Cataclysm-DDA/commit/12f7bc1af90b2bbb00abc5fa0cf4817faf65bbc8#diff-3c1e632de4a2469f1892e0d5c3469ff0fb28369937d9c1fd9be04c102a52775dR2376 which was probably added by mistake

**Comment by MochaModifier** [comment]
From what I can tell, this may be more an issue of the UI not closing - I've attempted to drop once, and rather than try and drop the item again I hit escape.
Doing this, you see the item has dropped (assuming the drop was valid)

**Comment by kebkaldanil** [comment]
> /confirmed broken by #64106
> 
> specifically this line [12f7bc1#diff-3c1e632de4a2469f1892e0d5c3469ff0fb28369937d9c1fd9be04c102a52775dR2376](https://github.com/CleverRaven/Cataclysm-DDA/commit/12f7bc1af90b2bbb00abc5fa0cf4817faf65bbc8#diff-3c1e632de4a2469f1892e0d5c3469ff0fb28369937d9c1fd9be04c102a52775dR2376) which was probably added by mistake
Yep, after removing this line, the bug is gone
