### ISSUE TITLE
Sealed items spawn old or near rotten

### ISSUE THREAD

**Issue by MochaModifier** [CleverRaven/Cataclysm-DDA#64138]
### Describe the bug

Have been finding canned goods and other sealed food items which are listed as both sealed, but also old or going rotten.

Perhaps more nonsensically, you can open an MRE and find that the crackers or cookies have begun to spoil, but the lobster seafood medley is perfectly good. Or the reverse, and the ratatouille is about to go off.

### Attach save file

[Martyr-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10947972/Martyr-trimmed.tar.gz)

### Steps to reproduce

1. start looting food items that are sealed
2. you should eventually find some that are (old) but also still (sealed)

### Expected behavior

Sealed foodstuffs like MREs, canned goods, etc. should be in equally good condition.

I say this, keeping in mind that 'best by' dates in no way reflect the expected time for food to rot; sealed dry or canned goods especially remain shelf stable for years and years past whatever date the FDA mandated be printed on the can.

### Screenshots

![image](https://user-images.githubusercontent.com/38334602/224472094-4385adfb-176c-49af-92bb-2eca2a8bb367.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 59c0d6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by MochaModifier** [comment]
Also should note that some items are so old that, within hours of opening a bag of chips - they have become rotten and inedible. That's just not what happens if you open a bag of chips, stale or not

**Comment by anothersimulacrum** [comment]
Possibly a consequence of https://github.com/CleverRaven/Cataclysm-DDA/pull/63639

**Comment by MochaModifier** [comment]
> Possibly a consequence of #63639

Most likely this.
It's also very odd that zombies are walking around with old or rotting candy in their pockets, just days after becoming zombies.

**Comment by Kromgart** [comment]
/confirmed

I can reliably reproduce this with nested item_groups (like MREs). 
Working on a fix now.
