### ISSUE TITLE
 Error:json error: data/json/monsters/slugs.json:28:22: Expected an object, got a 10

### ISSUE THREAD

**Issue by Deathstray** [CleverRaven/Cataclysm-DDA#64146]
### Describe the bug

I had the error at first Error: Json error: data/json/character_modifiers.json:119:13: denominator cannot be set to 0 but I was told to either update windows or download -msvc- I downloaded -msvc- I go into the game and try to create a world but the Error:json error: data/json/monsters/slugs.json:28:22: Expected an object, got a 10 help.

### Attach save file

Error:json error: data/json/monsters/slugs.json:28:22: Expected an object, got a 10

### Steps to reproduce

.

### Expected behavior

1 game launch
2 world creation 
3 character creation
4 start of survival

### Screenshots

![image](https://user-images.githubusercontent.com/126969199/224486518-a9b3fc4d-3f1e-4dda-bda9-8bf67b38179a.png)

### Versions and configuration

- OC Windows 7 game version 0.G Gaiman(It's written in the game d6ec466) Language Russian

**Comment by ZhilkinSerg** [comment]
You have probably updated your game improperly ( e.g. copied updated game files over existing old version).There is no mentioned file in 0.G version.

**Comment by ZhilkinSerg** [comment]
File was deleted in https://github.com/CleverRaven/Cataclysm-DDA/pull/57005
