### ISSUE TITLE
Cauterization of the wound.

### ISSUE THREAD

**Issue by Lilimday** [CleverRaven/Cataclysm-DDA#64144]
### Is your feature request related to a problem? Please describe.

In the "F" version, it was possible to easily stop the bleeding with fire and any knife - the pain of cauterization and the chances of infection is a fair price for not bleeding out in the initial stages without hemostatic powder. Please return this opportunity.

### Solution you would like.

Return this opportunity.

### Additional context

Versions and configuration
OS: Windows
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/d6ec466140839dd70c1a43671eb4a08b007695c2 (https://github.com/CleverRaven/Cataclysm-DDA/releases/download/0.G/cdda-windows-tiles-x64-msvc-2023-03-01-0054.zip [64-bit]
Graphics Version: RetroDays
Mods loaded: Dark Days Ahead [dda]; Magiclysm ; Speedydex ; StatsTroughSkills ; stats_trough_kills ; Tamable_Wildlife ; no_npc_food ; personal_portal_storms ; no_fungal_growth

**Comment by Karol1223** [comment]
Absolutely not. There have been discussions for AGES about how our implementation of cauterization was completely unrealistic and stupid. Irl this is nowhere near as simple. Not to mention the cauterization mechanic has not even worked for ages and was just a noob trap. No, just no.

**Comment by Venera3** [comment]
No.

**Comment by Lilimday** [comment]
> Absolutely not. There have been discussions for AGES about how our implementation of cauterization was completely unrealistic and stupid. Irl this is nowhere near as simple. Not to mention the cauterization mechanic has not even worked as intended for ages and was just a noob trap in this regard, it only worked to stop bleeding and not disinfect as advertised. No, just no.

o_O Of course, cauterizing a wound will not disinfect it, who would have thought that? There will be a burn, pain, soot-dirt. But when blood is gushing out of your artery like water from a fountain, and you have three minutes until you die, it's better to deal with the soot in the wound later.
Ok, thanks for the reply anyway - the unknown is always worse. I'll look for bandages.
