### ISSUE TITLE
Unable to climb back down wind turbine ladder

### ISSUE THREAD

**Issue by shell1610** [CleverRaven/Cataclysm-DDA#64149]
### Describe the bug

Climb up wind turbine ladder and when trying to climb back down am prompted to climb multiple directions except the safe path down the ladder. Tried multiple turbine towers and it will only let me jump down.

### Attach save file

[Barada-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10948723/Barada-trimmed.tar.gz)

### Steps to reproduce

1. Climb up ladder to top of wind turbine
2. Try to climb back down ladder

### Expected behavior

I expected to be able to use the ladder back down as I was always able to before.

### Screenshots

![image](https://user-images.githubusercontent.com/67021960/224491025-21f22565-cd11-417c-bb80-f223df542951.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 8c09248 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Night-Pryanik** [comment]
This should be fixed in #64140. Could you please retest on latest experimental?

**Comment by shell1610** [comment]
> This should be fixed in #64140. Could you please retest on latest experimental?

Yes, latest update fixed it, thanks
