### ISSUE TITLE
Liquid bandage spawn issues

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#64150]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/4392434962/jobs/7692328436#step:17:562

It seems all spawns are just `liq_bandage` without any container set. I can't find any references to `liq_bandage_spray` apart from the item definition.

### Attach save file

n/a

### Steps to reproduce

Probably chance based.

### Expected behavior

Liquid bandage spawns in an appropriate container.

### Versions and configuration

1bcb3b2a2b4ca54eaf5ef462f78f4d09efd19d82

**Comment by Drew4484** [comment]
Can confirm this caused a test failure on #62456.

**Comment by cake-pie** [comment]
Derp on my part. :facepalm:
