### ISSUE TITLE
Museum diversity

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#64160]
### Is your feature request related to a problem? Please describe.

All museums in the game are the same generic history museum with medieval weapons and armor and historical guns. This is not realistic per https://en.wikipedia.org/wiki/List_of_museums_in_Massachusetts , which enjoys hundreds of different museums on different topics.

### Solution you would like.

Many different museum types with different types of loot, especially (in order):

Historic House 31%
Local history 13%
History generic (the thing we have) 12%
Art 9%
Industry 3%
Maritime 3%

### Describe alternatives you have considered.

A larger museum complex with the same variants except for historic house.

### Additional context

Inspired by a recent discussion on large bones in devcord

**Comment by Vaskritaya** [comment]
There is a "textile mill museum" as well, so there's that. But yeah, more variety for the actual museum is needed.
