### ISSUE TITLE
Have some way to filter full magazines or batteries

### ISSUE THREAD

**Issue by Neokami** [CleverRaven/Cataclysm-DDA#64166]
### Is your feature request related to a problem? Please describe.

Using the custom sorting zones I'd like to be able to sort out fully loaded magazines and full batteries into separate piles by adding something in the filter to specify that. 

### Solution you would like.

Instead of showing `light battery (100/100 battery)` as the name of the items something like `light battery (100/100 battery(Full))` 

### Describe alternatives you have considered.

Edit: using a symbol as [chphilli](https://github.com/chphilli) suggested `%` would be a decent way to go as that would not cause too much screen clutter

**Comment by chphilli** [comment]
Wow -- I was literally looking at the code to see if I could find a way to do exactly this last night. It seems like a custom filter prefix (I toyed with '%:' as an idea) that looked at the count of an item (if it's countable) might work, but I didn't get anywhere close to trying to build or test out the idea.

**Comment by MochaModifier** [comment]
> Wow -- I was literally looking at the code to see if I could find a way to do exactly this last night. It seems like a custom filter prefix (I toyed with '%:' as an idea) that looked at the count of an item (if it's countable) might work, but I didn't get anywhere close to trying to build or test out the idea.

perhaps a bit more drastic, but would it be possible to mark or flag a container as 'full' at time of filling? Could just look for magazines and batteries using that then rather than work out fullness each search.

**Comment by Neokami** [comment]
if it were to be used on all containers it would probably have to tell you if it is full because of weight or volume but with batteries and magazines weight does not matter
