### ISSUE TITLE
Advanced Inventory Manager switches to wrong location in wrong panel when toggling ground vs vehicle

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#64171]
### Describe the bug

When viewing the AIM and pressing a direction key toward a vehicle storage part, the view in the active panel should toggle between the vehicle and the ground. Instead, some unexpected changes happen to both panels.

### Attach save file

N/A

### Steps to reproduce

1. Stand east of a vehicle with trunks to your west and northwest
2. Press `/` to open the AIM
3. Press `3` `Tab` `9` to target irrelevant locations in both panels of the AIM
4. Press `4` to select the vehicle storage to your west
5. Press `4` again and observe that your focused panel has switched to the southeast/`3` direction and the other panel has switched to the west vehicle storage

### Expected behavior

The second press of `4` should have switched the focused panel to the ground to the west, and not changed the other panel.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.4; Codename: Sikaris; 
- Game Version: 0.G [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I believe this worked as expected in 0.C, but I could be misremembering.

**Comment by Neokami** [comment]
you can toggle between the storage and tile using `V` which is the "toggle vehicle" key when in AIM.
