### ISSUE TITLE
refactor github actions to avoid save-state and set-output deprecation impacts

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#64180]
### Describe the bug

As outlined in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ these features are being deprecated,  and we need to refactor our actions that use them before enforcement starts in June.

### Attach save file

N/A

### Steps to reproduce

See article.

### Expected behavior

Working gh actions.

### Versions and configuration

GH actions

**Comment by casswedson** [comment]
#63169 and some previous work might have updated everything already; grep isn't showing any use of `set-output` or `save-state` (that is in master's .github folder)

**Comment by BrettDong** [comment]
These deprecated commands are updated in our own workflows. But some dependencies used in our workflows are still using them.
