### ISSUE TITLE
Aero-Evaporator is overpowered

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#6419]
It can fill any container, no matter the volume, with clear water, for very small time and same low energy value, which basically makes all other water sources obsolete. Moreover, now it's craftable. I propose lowering it maximum water output per activation to ~2 units.

**Comment by mightyagrippa** [comment]
This seems fixed, #8774 balanced it to two or fewer doses of water per use and it's been that way for a while.
