### ISSUE TITLE
[Magiclysm] Summoned items don't have length

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#64198]
### Describe the bug

Despite having a longest_side specified in their item definitions, items that are summoned via magic have no length. This leads to absurd situations such as being able to put a "great sword of judgement" (same size as a zweihander) in your backpack.

### Attach save file

Trivially reproducible

### Steps to reproduce

1. Learn and use any spell that summons an item

### Expected behavior

Items have length, even when conjured magically.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: eb8e722 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by GuardianDll** [comment]
Interestingly, but its not true, its something else
my game contain `"longest_side": "70 cm",` for `stormhammer`, but despite this, spawning it using debug shows it still has no length
![image](https://user-images.githubusercontent.com/67688115/224568604-cd93705c-3a75-4b03-a258-fb7df4cef44b.png)

**Comment by Terrorforge** [comment]
Hrm. But there seems to be nothing else connecting them? And it's happening to at least items in ethereal_items.json and the sword of judgment in the Crusader spell file. But not every summoned item - the pocket sun has a length, despite having zero volume. Something wrong with the materials, maybe?

**Comment by Rewryte** [comment]
Done some testing on this. The item::length() function will give a length of 0mm for all items that are made of a liquid material. As concentrated mana is considered a liquid, any items made of it will have 0 length. By changing the stormhammer to steel, I was able to summon one with the correct length of 70cm.

**Comment by GuardianDll** [comment]
And liquid it because of what? This exact bug occured when hardened mana got `rigid:false` boolean, not sure how it's related to liquid materials

**Comment by Rewryte** [comment]
Sorry spoke too soon. It's the `"soft": true` property. Turning that off in the concentrated mana material will make item length behave properly.

**Comment by GuardianDll** [comment]
I mean i know it, it was done in #63795, specifically to avoid summonned items slow you down. I guess the issue that `soft` property has a wrong name, as it actually means `liquid`

**Comment by Rewryte** [comment]
Ah, I wasn't aware of that PR. Liquids and soft materials share the same check, hence my initial confusion.

`if( made_of( phase_id::LIQUID ) || ( is_soft() && is_container_empty() ) ) {
        return 0_mm;
    }`

Splitting out the conditions show that `( is_soft() && is_container_empty() )` is returning true. But even if we can modify `is_container_empty()` to return false for non-containers, further down the function `is_soft()` is checked again.

`units::length max = is_soft() ? 0_mm : type->longest_side;`

So unfortunately I can't see how to give concentrated mana items length without making changes to every other soft item in the game.
