### ISSUE TITLE
Tiny / Unassuming treats body parts as oversized clothing?

### ISSUE THREAD

**Issue by MochaModifier** [CleverRaven/Cataclysm-DDA#64203]
### Describe the bug

Noticed erroneous encumbrance on body parts, which didn't line up with equipped gear.
Stripping naked showed I was somehow being encumbered.
Using the debug menu, I narrowed it down to the Tiny trait (and post threshold trait Unassuming)

The mouth, torso, arms and legs gain 3 to 4 encumbrance 

When I start a brand new character, I find adding tiny inflicts even more! Between 13 and 17 to the limbs, torso and mouth.

### Attach save file

[Martyr-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10951997/Martyr-trimmed.tar.gz)

### Steps to reproduce

1. Create a character
2. Give it Tiny or Unassuming + Diminuitive
3. You should see erroneous encumbrance on limbs, torso and head

### Expected behavior

Being tiny is rough enough as is - limbs shouldn't be getting random encumbrance unless wearing oversized gear. 
Being nude should give zero encumbrance barring other factors.
Being unassuming+diminutive may be giving less encumbrance per it's description - it's almost like it's treating the body parts as oversized clothing?

### Screenshots

![image](https://user-images.githubusercontent.com/38334602/224570942-9e7f9e94-a729-4f70-af86-3adb952e85a9.png)
![image](https://user-images.githubusercontent.com/38334602/224571268-a36853e4-f348-4624-ad08-f2a0f0d95e90.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: eb8e722 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by anothersimulacrum** [comment]
Probably the obesity, due to https://github.com/CleverRaven/Cataclysm-DDA/pull/60597

**Comment by MochaModifier** [comment]
> Probably the obesity, due to #60597

Hmm, that makes sense - though I wonder, does becoming tiny not affect your current body mass?
I.e., if a fresh test start survivor with a health weight was given the Tiny mutation... is that making me obese?

**Comment by MochaModifier** [comment]
Tested and found stored calories / body weight was the cause affecting encumbrance. 
Mutating to tiny evidently causes the relative scale for 'obese' to shift, meaning a character of healthy weight becomes obese or morbidly obese post mutation.
Closing this issue as a result.
