### ISSUE TITLE
Allow spell-use skills such as Spellcraft to gain experience through use

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#64201]
### Is your feature request related to a problem? Please describe.

Currently, Spellcraft is unique among skills in that it cannot gain XP through usage. The only way to train Spellcraft is by studying spells in books, which mostly works fine for a bearded wizard learning spells from ancient tomes (though even there it can run into odd issues, such as https://github.com/CleverRaven/Cataclysm-DDA/issues/60924 ), but doesn't fit any other paradigm like psychic powers or someone who casts intuitive magic thanks to inhuman heritage (like a D&D-style sorcerer) or other types of magical powers. 

### Solution you would like.

Allow Spellcraft (or other skills that use spells) to improve on use like all other skills.

**Comment by GuardianDll** [comment]
Casting a spell of difficulty X also train skill, responded for this spell, to level X
Repeatedly casting spell with `metaphysics` skill and difficulty 5, you can train metaphysics skill to level 5

**Comment by Standing-Storm** [comment]
Ah, I didn't realize this was already intended! Perfect
