### ISSUE TITLE
Adding turkish foods.

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#64204]
### Is your feature request related to a problem? Please describe.

Adding Turkish foods for more food variety.

### Solution you would like.

Adding a rare book that gives recipes for turkish foods.
Making turkish foods appear in foodplaces.(arguable)

Planned foods:
Salça: salça will be used in other turkish food recipes and can be used on bread.
Pide
Lahmacun
Mantı
İskender
Baklava
Menemen
Dolma
Sarma
Ayran

### Additional context

There are very popular turkish foods that i left out because there are alternatives to it which will be in the recipe book like meatballs(köfte).or just a different variation of alredy existing food for example Ramazan Pidesi. its bread but slimmer and with more crust. its consumed in ramadan month as an alternative to bread.

More food suggestions are always welcome.
i will leave this as a issue. i will work on it when i am available.

**Comment by EirenexTheDragon** [comment]
Pekmez , A Mulberry or Grape based Syrup, could be used in place of Maple syrup or to create a sweet unique meal by mixing it with scrambled eggs

**Comment by jgute** [comment]
Hi, I am new to this game and I am currently working on this feature with a friend. Our plan is to add the foods to the relevant cosmestibles jsons, then add the recipes to the relevant recipes jsons. Then we will add a book for the Turkish foods to cooking.json. Please let me know if there's something else that should be done as well.

**Comment by anothersimulacrum** [comment]
That sounds good, thanks for looking at it!

**Comment by leemuar** [comment]
should be closed probably, PR is merged now
