### ISSUE TITLE
Applying hacksaw or torch to prison metal grate windows produces boarded up window

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#64217]
### Describe the bug

When using a hacksaw or torch to get through a `t_metal_grate_window` (or the `t_metal_grate_window_*` variants), the result is `t_window_reinforced` (or the equivalent variant).

### Attach save file

N/A

### Steps to reproduce

1. Find prison or other source of t_metal_grate_window
2. [a]pply hacksaw
3. observe window is now mysteriously boarded up with wood

### Expected behavior

Empty window frame after bars are cut out.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.4; Codename: Sikaris; 
- Game Version: 0.G [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The existing construction path for making a metal grate window involves going through a wooden boarded up window first. This is weird because the boards make the window non-TRANSPARENT, but applying the metal grate makes it TRANSPARENT again, without producing the boards as a byproduct.

This whole construction, deconstruction, and torch/saw chain should probably all get a minor overhaul so these things make more sense. There should be a path from glass to glass+bars that remains transparent, and vice versa, without the wooden non-transparent step in between.

**Comment by Maleclypse** [comment]
/confirmed

```
{
    "type": "terrain",
    "id": "t_metal_grate_window",
    "name": "window with metal grate",
    "description": "Metal bars made into a grate for a window.  Highly durable and will stand against any foe.",
    "examine_action": "bars",
    "looks_like": "t_window_bars",
    "symbol": "#",
    "color": "light_gray",
    "move_cost": 0,
    "roof": "t_flat_roof",
    "oxytorch": {
      "result": "t_window_reinforced",
      "duration": "9 seconds",
      "byproducts": [ { "item": "pipe", "count": [ 1, 12 ] }, { "item": "sheet_metal", "count": 4 } ]
    },
    "hacksaw": {
      "result": "t_window_reinforced",
      "duration": "10 minutes",
      "message": "You finish cutting the metal.",
      "byproducts": [ { "item": "pipe", "count": [ 1, 12 ] }, { "item": "sheet_metal", "count": 4 } ]
    },
    "flags": [
      "TRANSPARENT",
      "NOITEM",
      "CONNECT_WITH_WALL",
      "BARRICADABLE_WINDOW",
      "BLOCK_WIND",
      "REDUCE_SCENT",
      "WINDOW",
      "SUPPORTS_ROOF"
    ],
    "bash": {
      "str_min": 50,
      "str_max": 75,
      "sound": "metal screeching!",
      "sound_fail": "clang!",
      "ter_set": "t_window_empty",
      "items": [
        { "item": "steel_lump", "prob": 25 },
        { "item": "steel_chunk", "count": [ 1, 4 ] },
        { "item": "scrap", "count": [ 1, 5 ] },
        { "item": "glass_shard", "count": [ 75, 125 ] }
      ]
    }
  },
```
