### ISSUE TITLE
Spellcraft (and other spell-based skills) cannot increase through use

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#64211]
### Describe the bug

Currently, Spellcraft is unique among skills in that it cannot gain XP through usage. The only way to train Spellcraft is by studying spells in books, which is different from every other skill in the game and runs into odd issues with skill rust (see https://github.com/CleverRaven/Cataclysm-DDA/issues/60924 ). 

### Attach save file

N/A

### Steps to reproduce

1) Start game with Magiclysm enabled
2) Debug in a spell with Difficulty higher than 1, such as Nature's Commune (Difficulty 4).
3) Cast spell repeatedly
4) Spellcraft spell does not gain any XP at all.

### Expected behavior

Using Spellcraft should increase it, like all other skills do. 

### Screenshots

![image](https://user-images.githubusercontent.com/120433252/224579421-373eb464-c92a-46c1-af48-9598602a88e6.png)
![image](https://user-images.githubusercontent.com/120433252/224579470-53a59e88-ab85-405e-99b2-a9ed0ed2e4f2.png)
![image](https://user-images.githubusercontent.com/120433252/224579487-a7c43d0a-15e4-4c39-8aae-ef032518b3b8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 0c1731a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by TheShadowFerret** [comment]
> "Your skill in the arcane.  Represents magic theory and all that entails.  A higher skill increases how quickly you can learn spells, and decreases their spell failure chance.  **You learn this skill by studying books or spells.**"

>~Spellcraft skill description

This is intended.

**Comment by GuardianDll** [comment]
> difficulty
> How hard to cast the spell. Higher difficulty make spell easier to fail, but also train your spell skill to the difficulty level (spell with difficulty 10 can train user to spellcasting lvl 10)
MAGIC.md

It is not intended, and description should be edited also
\confirmed

**Comment by GuardianDll** [comment]
Whole my life was a lie
![IMG_20230313_003436](https://user-images.githubusercontent.com/67688115/224580947-f4056f5e-9138-4b7e-8af0-5af89c43d361.jpg)

**Comment by Standing-Storm** [comment]
Is there a rationale for why it was built this way? It limits any magic to a paradigm of "bearded old man studies ancient tomes" and cuts out any other possibility like innate talent or gifts from some kind of Nether being.

**Comment by GuardianDll** [comment]
Legacy mostly - the mod was created 4 years ago, and a lot of infrastructure was built specifically for the magiclysm mod
