### ISSUE TITLE
Linux build no longer runs on Debian due to missing glibc versions

### ISSUE THREAD

**Issue by RAldrich** [CleverRaven/Cataclysm-DDA#64210]
### Describe the bug

I suspect this is caused by #64011.

I run CDDA on a Debian machine - specifically `Debian GNU/Linux 11 (bullseye)` via crostini on ChromeOS. This has worked seamlessly until now (just untar the Linux build and you're good to go). Since the above commit, the game fails to launch with the error messages:

```
./cataclysm-tiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./cataclysm-tiles)
```

This makes sense, as the most recent Debian stable release (11.5 in December 2022) only supports glibc 2.31-13 (you can find that information here: https://tracker.debian.org/pkg/glibc).

Just to be specific: my glibc version is as up-to-date as I'm able to make it and is:

```
libc6:
  Installed: 2.31-13+deb11u5
  Candidate: 2.31-13+deb11u5
  Version table:
 *** 2.31-13+deb11u5 500
        500 https://deb.debian.org/debian bullseye/main amd64 Packages
        500 https://deb.debian.org/debian bullseye-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

What are the dev team's thoughts on Debian support? Is there any way to estimate how many users might be impacted? While I don't want to stand in the way of modern compiler support, and can definitely resolve this on my end by changing my personal distro, rebuilding my machine is a pain. So I thought I'd raise the issue here.

### Attach save file

N/A

### Steps to reproduce

Download the most recent cdda-linux-tiles-x64 build and untar on a Debian machine. Attempt to run cataclysm-launcher.

### Expected behavior

N/A the error is expected.

### Versions and configuration

Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.159-20950-g3963226d9eb4
Architecture: x86-64

Any build after #64011 was merged.

**Comment by BrettDong** [comment]
Change Linux release build environment to Ubuntu 20.04 and compile with a GCC version <=10 should fix this.

**Comment by kevingranade** [comment]
I see now, yes that's my mistake, I should not have bumped the release builds all the way to -latest. In fact we need to double check if we can use a non default older gcc and glibc for release builds.

**Comment by jbytheway** [comment]
GCC and glibc versions should be mostly independent (although maybe not entirely so). It would be nice if we could still use a newer GCC with the older glibc for release builds, because newer GCC will presumably have better optimisations.

**Comment by BrettDong** [comment]
The GCC version we can use is limited by the version of `libstdc++` available on the user's system. If we use a GCC later than that, there is a risk of getting undefined symbols in the C++ standard library.

**Comment by BrettDong** [comment]
OP has encountered the issue:

> `libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./cataclysm-tiles `

**Comment by Alm999** [comment]
Oh, and I just updated from Fedora 30 to 37 in order to satisfy the "GLIBCXX_3.4.29" requirement.

Well, it should happen sooner or later…
