### ISSUE TITLE
Straw Beds Give Just 5% of its Straw on Deconstruction

### ISSUE THREAD

**Issue by SolventMercury** [CleverRaven/Cataclysm-DDA#64227]
### Is your feature request related to a problem? Please describe.

I started making my base in a Junkyard, which happens to have some straw beds in the lot, and wanted to move one inside. However, deconstructing a straw bed gave me just 8 piles of straw, out of 160 needed to create a new one. This doesn't make any sense - how would straw be lost in this process? It's practically amorphous - it can't get damaged or lost, it'd be like losing water from pouring it out of a bottle and into a bucket. I can't break water - maybe a small amount can evaporate, but straw doesn't evaporate, so it doesn't have that excuse.

### Solution you would like.

Deconstructing a straw bed should realistically give at least 80-90% of its resources, if indeed any are lost at all.

### Describe alternatives you have considered.

N/A

### Additional context

N/A

**Comment by dgreenlee1** [comment]
I would like to contribute a fix to this issue, please let me know if any changes are needed or further action is required.

**Comment by SolventMercury** [comment]
You didn't get your pull request right. You merged your change into the master of your own fork - which does absolutely nothing for the main fork.

**Comment by dgreenlee1** [comment]
Thanks for the heads up! I retooled the submission and I think it's going
through correctly now.

**Comment by SolventMercury** [comment]
Alright, looks good to me. Issue can be closed when that gets merged in.
