### ISSUE TITLE
Improving No NPC Needs

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#64221]
### Describe the bug

There are a number of things that cause NPCs to experience needs even with NPC Needs turned off but our tools for handling these types of things have improved since that mod was created.

### Attach save file

N/A

### Steps to reproduce

Gather NPC followers,  let them experience thirst and hunger but be unable to force them to eat and drink without taking over the NPCs directly.

### Expected behavior

The stated needs that are modded out to not be regularly impacting my NPCs

We have Effects on Condition now that could be created to reset hunger, thirst and calories to baseline every day at dawn.  This wouldn't even be a very complicated EOC probably.

### Versions and configuration

N/A

**Comment by anoobindisguise** [comment]
This would be a good time to mention that turning off No NPC Needs makes it impossible for NPCs to lose instability.

**Comment by Maleclypse** [comment]
> This would be a good time to mention that turning ON No NPC Needs makes it impossible for NPCs to lose instability.

Does that mean NPCs don't regenerate blood after losing it and will eventually die of hypovolemia if the take enough wounds even if the heal from them? Or are NPCs immune to blood loss other than hp damage?
