### ISSUE TITLE
Rubik has random debt depth

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#64226]
### Describe the bug

Each vendor in multiple exodii bases has a separate and random value for how much they can owe player, ranging in my testing from $100 to $700.

Having low values forces player to find another exodii base or an autodoc to install high value cbm.

### Attach save file

[Baseline-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10956941/Baseline-trimmed.tar.gz)

### Steps to reproduce

1. Find/spawn exodii_base
2. Rubik can owe you $100 max
3. Find/spawn another exodii_base
4. Rubik can owe you $700 max

### Expected behavior

* random values should be always higher than installation cost of the most pricy cbm
* ~first exodii base should despawn right before you find another one~

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: c50f83d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by PatrikLundell** [comment]
I don't see any reason for why there should be any relation between CBM installation costs and the maximum dept Rubik is willing to be in.

It would be horrible to go on an exploration trip and have your reasonably conveniently located Exodii base teleport away.
It is true that multiple "unique" locations is a problem, but it would be even worse to have only one spawn only to have it immediately be destroyed by threats (mycus, fire ants, etc.). Until there is a way to ensure the "unique" locations remain safe from random destruction and are accessible (not e.g. on an island with a broken bridge generated, or a mycus field covering the only path) multiple instances is less bad.

**Comment by Cenness** [comment]
>why there should be any relation between CBM installation costs and the maximum dept

Because exodii are supposed to be the only source for cbms. So I'm assuming autodocs will not be able to install cbms in future.  And problems with globally_unique will be fixed somewhen in future, no doubt, so you won't be able to reroll max debt.
If installation cost of a cbm is greater than max debt player can't get it installed.


>go on an exploration trip and have your reasonably conveniently located Exodii base teleport away

>first exodii base should despawn **right before you find another one**

**Comment by PatrikLundell** [comment]
Unless things have changed since I last played, you pay for CBM installation at the time of installation. If, however, the implementation has changed such that installation cost has to be drawn from an account into which you have to deposit before a CBM installation can be performed, yes, the account should be able to contain enough funds to cover every installation your current trust level allows.

I obviously don't understand what your "despawn" comment is supposed to mean, so just repeating it louder doesn't provide any additional understanding. Despawn just before detection of another one seems like teleporting it to me (although I guess despawn might mean reset of any progress as well as a move to a worse location.

**Comment by RAldrich** [comment]
By "despawn" They're asking for the Exodii base to be made a globally unique location through the specific mechanism of removing old locations when you discover a new one.

This is not possible for a variety of reasons, and while many people are interested in globally unique NPC locations, removing already discovered locations is not a solution we're considering. If you'd like to learn more please search for the various existing issues on the subject.

**Comment by I-am-Erk** [comment]
This probably should be solved, rubik shouldn't really accept any debt at all.

**Comment by RenechCDDA** [comment]
This is definitely the amount Rubik is willing to owe you. So you can trade them... IDK, 10 thingies and they'll owe you $100. But if you trade them 1000 thingies, they're still only willing to owe you $100.

The calculation is in npc::max_credit_extended. https://github.com/CleverRaven/Cataclysm-DDA/blob/3c95a24b86217764ebbc3d075805f48783644d22/src/npc.cpp#L2074-L2093

It would be pretty simple to short-circuit this logic with a flag if desired.

**Comment by I-am-Erk** [comment]
We can just define Rubik's altruism as a flat value, there's an option for that already

**Comment by RenechCDDA** [comment]
Oh, so there is. Well it's VERY easy when it already exists.

So rubik's definition, here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3c95a24b86217764ebbc3d075805f48783644d22/data/json/npcs/exodii/exodii_merchant_definitions.json#L2-L12

Needs a defined personality, like this: (Not these values exactly! Probably!)
```
  "personality": {
    "aggression": -1,
    "bravery":  2,
    "collector":  -3,
    "altruism":  4
  }
```

The NPCs.md documentation for reference: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#npc-instance-definition
