### ISSUE TITLE
Character creation STAT-panel bugged visuals

### ISSUE THREAD

**Issue by Wyghab** [CleverRaven/Cataclysm-DDA#64242]
### Describe the bug

The STAT panel when creating a new character doesn't properly display the effects of the statistic you are inspecting. 

Strength: Carry weight and bash bonus decreases whenever a point is added or removed.

Dexterity: To hit and Throwing penalty go down regardless of what you press. Ranged penalty only goes down when you remove dex, but doesn't raise to match afterwards.

Intelligence: Read time and crafting bonus increase/decrease towards their max/min values of  140% and 0% respectively.

Perception: Performs as expected?

Pressing the up and down arrow keys also seem to affect whatever all stats are displaying, as if they are decreasing the stats in the background. Even pressing up the keyguide with '?' displays the same issues as decreasing stats. Pressing ESC twice will also exhibit the behaviour. I am led to believe that any actions on the screen applies a downward shift of 1 to all stats displayed in some manner.

### Attach save file

N/A

### Steps to reproduce

1. Attempt to create a character, any background, profession or scenario.
2. Skip all details and tab to the STAT page.
3. Increase Strength.
4. Decrease dexterity, then Increase it back again.
5. Increase Intelligence-
6. Increase and Decrease Perception.
7. Now Tab forward or backward, and then back to the STAT panel again.
8. Simply go up and down between strength and Dex.
9. Refresh the tab and try '?', or press ESC twice.

### Expected behavior

I expect the stats to reflect their value in terms of primary and secondary effects.

### Versions and configuration

a98d542 (tiles)
build 2023-03-13-1427

**Comment by Wyghab** [comment]
Well I hunted the bug down to originating from #60597 where it applied weight class penalties inside avatar::reset_stats().
This causes a loop of penalties to be stacked up because the character is not properly weighted. Changing the characters height to below 158 or below allows to intended behaviour on all stats. But it even if the BMI portion is fixed, it still reveals an issue with the current design that newcharacter employs for the STAT section, whereas the information displayed can be polluted by effects on the character being applied over and over by the reset_stats() called on the players avatar.

**Comment by anoobindisguise** [comment]
working on a fix for this.
