### ISSUE TITLE
Graboids Should not Occur in Earlygame

### ISSUE THREAD

**Issue by SolventMercury** [CleverRaven/Cataclysm-DDA#64247]
### Is your feature request related to a problem? Please describe.

Why are graboids? I can't outwalk them, I can't outrun them, they're "the size of semi trucks", can't be seen until they reveal themselves, and show up in innocuous places very early in the game. I just got murdered by one on day 2 in probably the cheapest death this game has given me because I thought the pile of dirt (which I didn't notice until it was very close already) would be a half worm or something. This is worse than a zombie hulk or shocker brute showing up, because these are both combat encounters you can avoid - you can spot them from a distance and, failing that, just start sprinting in the opposite direction, but unless you're very near some pavement, the graboid can chase you down and kill you, and you likely won't see it coming because it will run up to you outside your view distance. While new piles of dirt showing up would be obvious in most games, if it happens outside your zoom radius, you won't see an icon on the mini-map, you won't see an entity on your entity list, and it won't proc safe mode, so all of the tools designed to tell the player they are in danger fail them despite the fact that a character paying attention should, in universe, easily be able to see or hear it coming.

### Solution you would like.

Graboids should not show up until the game can reasonably assume they'd be able to deal with them. Making them the product of an evolution line rather than a day one spawn would be a very good idea. Might also be advisable to add sounds in-game for tunneling monsters moving through the ground (especially large ones) so the player could hear them coming instead of solely relying on visual cues.

### Describe alternatives you have considered.

Making the graboid weak enough for an early survivor to actually fight them would take away something from the game, but it's still possible. Could also limit spawn locations to places like caves where player would expect higher risks to occur.

**Comment by RAldrich** [comment]
I agree. While there is only a 3% of a GROUP_WORM spawning one of these (and they count as 20 smaller worms, so it has to be a pretty major spawn), that's still pretty high for something that clearly mutated to show up on day 1. Someone could easily add a `starts` value to the entry in bugs.json to fix this.

It's also possible you're running into one that's generated by an old guard mission. That one should probably stay as is.

**Comment by SolventMercury** [comment]
> I agree. While there is only a 3% chance of a GROUP_WORM spawning one of these (and they count as 20 smaller worms, so it has to be a pretty major spawn), that's still pretty high for something that clearly mutated to show up on day 1. Someone could easily add a `starts` value to the entry in bugs.json to fix this.
> 
> To be clear, they already ARE the evolution of the small worms (on a 60 day half life), you just also have that 3% chance on day 1.
> 
> It's also possible you're running into one that's generated by an old guard mission. That one should probably stay as is.

I encountered two. I have no clue if it was a mission, but I didn't see the evac center anywhere near if that's at all relevant.

**Comment by SolventMercury** [comment]
> How many hours should this starts value be? 180?

I'm not sure, you'll have to ask around.
