### ISSUE TITLE
Skill 0 and Training recipes are extremely hard regardless of Skill

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#64241]
### Describe the bug

0 skill recipes like clean water, heavy duty threads or lockpicks as well as all Practice crafts have a super high failure chance at all skill levels, l this is pretty extreme even at a default 8 int and just ridiculous at int 4.

### Attach save file

This can be seen in a fresh save file

### Steps to reproduce

1 - Make a new character with high skill
2 - Check recipes like clean water

### Expected behavior

Higher skill makes crafting easier even at int 4

### Screenshots

0 Skill 8 INT
![Screenshot_1](https://user-images.githubusercontent.com/39201027/224830197-91891800-5eb5-4d5b-82df-9e7308514974.png)
10 Skill 8 INT, same success as if they had zero
![Screenshot_2](https://user-images.githubusercontent.com/39201027/224830208-8b8bb04b-46a4-4bc0-9faa-cb7ac6e7f31b.png)
Recipes that take 1 or more skill to craft works normally
![Screenshot_3](https://user-images.githubusercontent.com/39201027/224830212-7461f37c-3a27-47dd-8294-6a571716d613.png)
![Screenshot_4](https://user-images.githubusercontent.com/39201027/224830546-7e778d6c-cb28-438e-a65d-4bd3a69ec8cf.png)
Any craft or practice at int 4 becomes nearly impossible
![Screenshot_5](https://user-images.githubusercontent.com/39201027/224831778-ed97559d-ffd0-4c14-bcb1-d355f261e174.png)
![Screenshot_6](https://user-images.githubusercontent.com/39201027/224832484-beabb33b-d539-4d62-a65e-7dc5035d2ff0.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: a98d542 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

The same thing happens with all training regardless of skill, this is definitely a bug since I've been playing with a 4 int survivor and around the time the new crafting odds display was introduced this started to happen, Why you can even fail in practice makes me confused to since you're not actually making anything most of the time and needing to replace lost components is just frustrating

**Comment by Alm999** [comment]
Well, a can /confirm this being the case
