### ISSUE TITLE
Broken reward for Gather cattail stalks to create cattail jelly quest

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#64245]
### Describe the bug

When you complete the quest to collect 80 cattail stalks, the questgiver attempts to give you cattail jelly in a zipper bag.  This is not a valid container for cattail jelly and the game throws an error, preventing the cattail jelly from being given to the player.

### Attach save file

N/A

### Steps to reproduce

1. Be given cattail jelly quest by NPC.
2. Complete the quest.
3. Receive error message.

### Expected behavior

The reward should be in a watertight container such as a bottle instead.  Be sure the container is large enough to contain the reward, 7 units of jelly is 0.25 L.

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Generic Guns [generic_guns]
]

**Comment by Neokami** [comment]
This is something I have happen to me a few times now, I'm not even sure you get the reward because of the error. I think it is because a single cattail jelly is 0.04L that multiplied by 7 is 0.28 which is more than the 250ml zipper bag size. Although if you have 7 cattail jelly it only takes up 0.25L.

**Comment by TheDarkMaster13** [comment]
I don't know if the reward is 7 units or more, I only included that as a reference since that's what you get for doing the recipe yourself.

**Comment by sparr** [comment]
This will be resolved by #64488 is merged
