### ISSUE TITLE
Crafting filter `m:no` is cluttered with recipe groups

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#64259]
### Describe the bug

When attempting to view unlearned recipes with `m:no` as the crafting filter, every recipe group is displayed, *as well* as the contents of those recipe groups which the player already knows.

This makes it hard to see what the actual unlearned recipes are, as most results aren't relevant.

### Attach save file

N/A

### Steps to reproduce

1. Start or load a game
2. Go to the `&` crafting menu
3. Go to `f`ilter
4. Type `m:no` as the filter

### Expected behavior

Recipe groups are either not shown, or only shown if an un-learned recipe is in them.

### Screenshots

Sample screenshot showing recipe groups, in addition to some unlearned recipes. Bandaging group has been expanded to show that basic known recipes (eg: makeshift banadage) are being erroneously shown.

![mmmm-no](https://user-images.githubusercontent.com/12072/224964272-8333ef94-17a3-473c-8104-131ea563cffc.png)

### Versions and configuration

Version is cb644353a1cc066d70f8d1323afb3fd550c814bb with a few local patches applied (none of which relate to recipe groups).

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-558-gae6b4535a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms]
]
```

### Additional context

First reported in #63091.

Reporting here in a separate issue because I *feel* like this should be an easy fix which I'm willing to attempt, but I'm still finding my way around the recipe and recipe filtering code.

**Comment by Brambor** [comment]
Have you tried fixing it @pjf ?
Any luck? Any blockers?

**Comment by pjf** [comment]
@Brambor : Life has been a blocker. :)

As far as I can tell, every recipe group is marked as un-memorised, which is why they all show up. Unfortunately I wasn't able to find where the `m:no` search happens in the codebase in the time I had available.
