### ISSUE TITLE
Zombies move and grab in the same turn when they shouldn't have the moves to do so

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#64267]
### Describe the bug

Oftentimes while waiting in place for one turn for a zombie to move to me, I find that the zombie also immediately grabs me after moving towards me despite being less than 100 speed and often moving diagonally - it should have no way to do this. I never observe those zombies moving and attacking on the same turn, it is only ever moving and then grabbing.

### Attach save file

n/a

### Steps to reproduce

1. Spawn a tough zombie or normal zombie.
2. Walk away from it and stop one tile away from it by pressing 'tab' or '.'.
3. Notice it can never make a claw/punch attack this way as long as you had a tile gap before waiting.
4. Observe the zombie stepping towards you and grabbing you despite not having the moves.

### Expected behavior

A zombie with less than 100 speed should never be able to take two actions when you wait 100 turns. This would be expected for zombie dogs and runners which can sometimes move and attack in the same turn due to having 105 speed but not for standard zombies (70 speed) or tough zombies (85).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1574 (21H2)
- Game Version: d4f3815 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by Termineitor244** [comment]
/confirmed.

**Comment by anothersimulacrum** [comment]
I cannot reproduce this.
Both with a normal and a tough zombie, spawn them and let them get within one tile by waiting. When they get to an adjacent tile, move back one tile and repeat.
I am never grabbed.
With some added debug messages:
The 'metabolic rate' message is printed every turn.
![image](https://user-images.githubusercontent.com/42699974/225365110-806c6aae-4ad6-46e0-b09c-0ccccac5ce33.png)
Turn on debugmode with all filters except character and effects, and apply this patch:
```diff
@@ -457,6 +457,7 @@ void monmove()
             critter.move(); // Move one square, possibly hit u
             critter.process_triggers();
             m.creature_in_field( critter );
+       add_msg_debug(debugmode::DF_MONSTER, "Monster %s at (%d, %d, %d) acted. Moves left: %d", critter.get_name(), critter.posx(), critter.posy(), critter.posz(), critter.moves);
         }
 
         if( !critter.is_dead() &&
diff --git a/src/monmove.cpp b/src/monmove.cpp
index 720eac9e32..9b42f8900e 100644
--- a/src/monmove.cpp
+++ b/src/monmove.cpp
@@ -799,9 +799,12 @@ void monster::move()
 
         if( local_attack_data.cooldown == 0 && !pacified && !is_hallucination() ) {
             if( !sp_type.second->call( *this ) ) {
-                add_msg_debug( debugmode::DF_MATTACK, "Attack failed" );
+                add_msg_debug( debugmode::DF_MATTACK, "Attack failed, moves left %d", moves );
                 continue;
-            }
+            } else {
+                add_msg_debug( debugmode::DF_MATTACK, "Attack success, moves left %d", moves );
+           }
+
 
             // `special_attacks` might have changed at this point. Sadly `reset_special`
             // doesn't check the attack name, so we need to do it here.
```
Here's what a grab looks like:
![image](https://user-images.githubusercontent.com/42699974/225365628-3e60d469-d75f-4150-af97-e3364f802dbd.png)

**Comment by anothersimulacrum** [comment]
> I never observe those zombies moving and attacking on the same turn, it is only ever moving and then grabbing.

Because a grab is the first thing they try to do. If they try to grab, they spend 80 moves. Then they try to bite, which will cost 100 moves if they can try. Then to scratch, etc.

So of course the only thing you see when they have sufficient moves is that a zombie moves and grabs, because that's the first thing they try.

**Comment by kevingranade** [comment]
> A zombie with less than 100 speed should never be able to take two actions when you wait 100 turns. 

This is not true,  as long as the first action is fewer moves than their speed,  it's possible and intended.
