### ISSUE TITLE
module 'pytz' has no attribute 'UnknownTimeZoneError'

### ISSUE THREAD

**Issue by loeuekken** [CleverRaven/Cataclysm-DDA#64269]
### Describe the bug

-Updated the launcher to V1.6.10
-When starting got error:
![grafik](https://user-images.githubusercontent.com/34602382/225122347-b98930c3-e485-416c-a060-1c9d65892dd4.png)
-Launcher didn't start

### Attach save file

N/A

### Steps to reproduce

For me just starting the launcher. This has not happened in the last version of it (the day before) and i have no idea why it does now.

### Expected behavior

Launching the launcher

### Versions and configuration

-On Win10, Build 19044.2604
-German/DE localization
![grafik](https://user-images.githubusercontent.com/34602382/225125042-57d3e209-b498-4945-ad21-4ecc205ec2eb.png)
The python version my installation of the CDDA launcher came with ((?) - sorry, it has been a while, just been updating since then)

### Additional context

As the error suggests, pytz does not have desired attribute.
For me this worked (in \babel\localtime\\\_\_init_\_.py):
![grafik](https://user-images.githubusercontent.com/34602382/225123973-b2c3b656-e84a-4cbd-8265-facc763818d9.png)

**Comment by harakka** [comment]
Wrong repository, post at https://github.com/DazedNConfused-/CDDA-Game-Launcher.

**Comment by anothersimulacrum** [comment]
The game launcher is a separate project.
