### ISSUE TITLE
Get rid of the "evolved zombie siege" variant of Mi-Go towers

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#64263]
### Is your feature request related to a problem? Please describe.

Currently there is a variant of the Mi-Go tower that spawns a legion of Hulks, Wrestlers, Nightstalkers and Pupating Brutes. There presumably was a master involved, but there is no master present at the site. These are obviously supremely dangerous for a day 1 survivor and will usually join a horde to ambush you later unexpectedly.

### Solution you would like.

This variant should only spawn later on into the cataclysm, such as winter by default. The zombies didn't have time to evolve this far yet and it's not great gameplay (don't ever go near a migo tower otherwise it might generate hulks etc which will later join a horde and ambush you)

### Describe alternatives you have considered.

Get rid of it entirely.

**Comment by Maleclypse** [comment]
Convert it to an EOC encounter that starts in Winter? Otherwise we don't really have a way for mapgen to spawn based on time from cataclysm.

**Comment by Snaaty** [comment]
This is just a tangent, but are Hordes enabled by default now? I remember never using them back in the days and have kept them turned off ever since.
