### ISSUE TITLE
Implement .json overrides for all Action category_id entries in iuse.cpp

### ISSUE THREAD

**Issue by leefy-greens** [CleverRaven/Cataclysm-DDA#64276]
### Is your feature request related to a problem? Please describe.

Often, there are situations where adjustment of the moves consumed by these actions would be desirable, either from individual gameplay tuning/preferences, or modding.

### Solution you would like.

Create a .json file with override entries for each category_id from src/iuse.cpp (ACT_*), to allow the adjustment of 'moves' and/or duration for each, respectively.  This would allow for adjusting these actions to take more or less time, in-game, in moves.

### Describe alternatives you have considered.

Vastly increasing the related stats, temporarily, that are the dependencies for the moves and/or time_duration calculations for each Action category_id.  Memory editing the moves calculations during run-time.

**Comment by ZhilkinSerg** [comment]
We already have json type to store player activities data, but I don't think it would be possible to store duration there as it could be not a fixed duration, but some dynamically calculated value.
