### ISSUE TITLE
Game crashes when I unload my hoodie

### ISSUE THREAD

**Issue by Boonlike** [CleverRaven/Cataclysm-DDA#64278]
### Describe the bug

Game is consistently crashing whenever I try to unload my hoodie.

### Attach save file

[Hedwig Village-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10982382/Hedwig.Village-trimmed.tar.gz)

### Steps to reproduce

Load my save
Unload my hoodie

### Expected behavior

I expect my hoodie to unload without crashing the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1265 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I have a casserole pot in my hoodie with some items in it. If I unload the pot first, then unload my hoodie, there's no crash.

**Comment by katemonster33** [comment]
I was able to reproduce this on my machine with this save.

It appears what is happening is, the game sees the open casserole dish inside the inventory of the hoodie, and so unloading the hoodie causes it to spill. The game automatically tries placing spilt items into the "best" pockets for those items, and the pocket it chooses happens to be the casserole dish currently being dumped out. This creates an infinite loop where the item is dumped out of the dish, only to be put right back into the dish.
