### ISSUE TITLE
Automatically Use Oven Nearby

### ISSUE THREAD

**Issue by newbie-forever** [CleverRaven/Cataclysm-DDA#64283]
### Is your feature request related to a problem? Please describe.

Currently, nearly everything related to the heating up function of the oven is manual, which is very inconvenient when you want to cook or eat

### Solution you would like.

Oven should be automatically used for unfreezing frozen ingredients for cooking and heating foods when eating.

**Comment by flybye3o6** [comment]
already for crafting heating up frozen ingredients should be automatic if there is a heating source in the crafting recipe and within 6 tiles
but not for things like making a sandwich which dont use heating in its recipe, recipes like these are what your talking about
example: buttered toast will show you have no butter if the butter is frozen

a means for recipes without heating to use heating when defrosting and ideally include energy and time cost added to the recipe
i think for the crafts that use heating, the defrosting of the frozen ingredients is done for free
maybe a defrost/warm up option could be added to the consume menu, with time and energy cost added to the consume time, though food that is inedible in frozen form dont show in this menu, maybe have them another category or another menu to reduce clutter(inedible in current form)
