### ISSUE TITLE
Warning about liquid ammonia missing when starting crafting

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#64287]
### Describe the bug

When you try to craft a recipe that uses liquid ammonia, you'll get a warning that it is missing and be asked to consume a new unit.  Saying yes will repeat the warning.  Saying no, but then resuming crafting, works as intended as a work around.

Possibly this is a canister issue?

### Attach save file

N/A

### Steps to reproduce

1. Get a liquid ammonia canister and the rest of the ingredients needed to craft something.  Ex: Mutagen.
2. Attempt to craft the recipe.  Saying yes repeats the prompt.
3. Say no, then work on the craft as a workaround.

### Expected behavior

The recipe should consume the ingredients as normal and proceed straight to crafting with no warning prompt.

### Screenshots

![image](https://user-images.githubusercontent.com/6277016/225507285-c27e52b5-1ba7-416f-be01-9f32d91fe293.png)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Generic Guns [generic_guns]
]

**Comment by TheDarkMaster13** [comment]
Actually the problem is more confusing than I thought it was, as you sometimes do have to consume the ammonia and sometimes you don't.

**Comment by RenechCDDA** [comment]
Is the ammonia actually being destroyed? There was a discourse "report" after this issue was previously cleared up with a different sort of reproduction: https://discourse.cataclysmdda.org/t/liquid-ammonia-evaporating-while-cooking-mutagen/28503/2

**Comment by PatrikLundell** [comment]
The description sounds like a similar issue with clay canning pots. When using any recipe ingredients stored in a clay canning pot such a prompt appeared, and the ingredients were consumed twice: first when the crafting failed, and then again when it was resumed. It was reported that the cause was that the clay canning pot had some tool properties (I believe more items were affected, but that's the one I specifically know of).

**Comment by RenechCDDA** [comment]
I've now specifically tested this and in no circumstance on d6ec466 (0.G) can I get this to happen. Please provide a reproduction save.

**Comment by TheDarkMaster13** [comment]
[Saugus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11045982/Saugus-trimmed.tar.gz)

Here's my save from inside my base.  You should be able to start a new recipe of mutagen using ammonia immediately after loading to repeat the bug.  Version and mod information is in the OP.

**Comment by RenechCDDA** [comment]
Aha! I am indeed very stupid, thank you for the reproduction save because using it allowed me to *automatically* load the mods instead of remembering to select them.

/confirmed

Aftershock still has a `pressure_tank` listed as a `TOOL`!

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/3fc5efa77e928ae44b01fa7c43f65a4314ee2aab/src/vehicle.cpp#L5189-L5191
this case is getting hit in the save, not relevant to ammonia issue but i'll subscribe so I don't forget
