### ISSUE TITLE
invalid trait id "mut_exo_strength"

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#64291]
### Describe the bug

an error screen about `invalid trait id "mut_exo_strength"` popped up in my current run.

### Attach save file

[Colmar Manor-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10989906/Colmar.Manor-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save.
2. error screen.

### Expected behavior

said error screen not popping up every time i play the save.

### Screenshots

![Screenshot_20230316-180914](https://user-images.githubusercontent.com/78019001/225599840-7046b63d-4bb4-4b83-8426-d3e455d84cd9.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 50046e8 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Massachusetts [MA],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/enchantments.json#L83 and https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/enchantments.json#L93 reference this mutation, but there is no such
Probably #64119 respond for this
