### ISSUE TITLE
(blaze industries) KitchenMaster cooking buddy not recognized as dehydrator

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#64290]
### Describe the bug

just updated to try the new stuff, tried to cook something, and noticed my vehicle mounted KitchenMaster is not good as dehydrator anymore

### Attach save file

[Emerald Lake Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10988471/Emerald.Lake.Hills-trimmed.tar.gz)

### Steps to reproduce

1) load save
2) open craft menu
3) navigate to any recipe using Foodco kitchen buddy dehydrator
4) KitchenMaster cooking buddy dehydrator is not recognized

### Expected behavior

not sure if both kitchens are supposed to run at the same efficiency, but the expected behavior is that i'm able to dehydrate with it like prior to the update 

### Screenshots

![image](https://user-images.githubusercontent.com/42104923/225559785-7e2b4c0c-7731-4144-8b56-301f35c95860.png)
![image](https://user-images.githubusercontent.com/42104923/225559894-f0968a8a-afbb-4322-86fb-7724446cb5fe.png)

### Versions and configuration

windows 10
build 2023-03-16-0615
tiles
english
[
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "Tamable_Wildlife",
  "stats_through_kills",
  "speedydex",
  "package_bionic_professions",
  "blazeindustries",
  "rub_reb",
  "No_Person",
  "extra_mut_scens",
  "MMA",
  "translate_dialogue",
  "No_Rail_Stations"
]

**Comment by anoobindisguise** [comment]
@cake-pie mentioned this to me but I didn't get around to fixing it and forgot. I'll post a fix today
