### ISSUE TITLE
Android builds failing

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#64293]
### Describe the bug

The Android Builds for the newest experimental versions of the game are failing to generate after #64152 was merged.

### Attach save file

N/A

### Steps to reproduce

Look at the experimental builds after the PR in question was merged.

### Expected behavior

To have experimental builds for android generating correctly. 

### Versions and configuration

N/A

**Comment by jbytheway** [comment]
> OSX is failing too: https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/4437676544/jobs/7789080345#step:16:137

I've opened #64314 to fix the OS X build.
