### ISSUE TITLE
Army Jacket and Army Equipment naming inconsistencies

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#64300]
### Describe the bug

For a while now, I thought the Army Jacket was renamed to "combat blouse", which, you know, fair. 

But it seems like that isn't the case. The item is still in the data base, it's required for some recipes and it's dropped by strange monsters. It just stopped existing in military places: 
soldier zombies don't drop them anymore, [lab] Barracks do not have them in the lockers either. Haven't seen them in FEMA Camps and Military Helipads either. 

### Attach save file

n/a easy to reproduce

### Steps to reproduce

1. Create world and player
2. check military spaces mentioned above for "army jacket" notice they don't exist. 
3. kill a bunch of soldier zombies, notice they also don't drop them anymore. 
4. wonder why feral humans and cunning ferals drop them instead (according to Hitchhiker Guide).

### Expected behavior

I would expect military personnel to drop military gear, and for non-military personnel to drop non-military gear (or at best "military cosplay gear" , like "cammo jacket", "cammo pants", not "army pants", etc.). 

### Versions and configuration

- windows
- 53f9146
- no mods needed

### Additional context

I noticed this after someone on a discord channel asked for help in regards to finding "army jacket", but only finding "army winter jackets" instead. 

It has been a while since I myself have seen the existence of "army jacket". Now I don't know whether it was a rename - I can't find any PR that outlines why this is the case.

**Comment by AcidAntOnAMinefield** [comment]
OK that's fair but the question is still there:
Why replace the army jacket with combat blouse in the other places? military zombies drop combat blouses/combat shirts, not army jackets - unless they drop army *winter* jackets. Isn't this an inconsistency?

**Comment by AcidAntOnAMinefield** [comment]
I am not talking about the leather jacket, I am talking about the one I am linking now:
https://nornagon.github.io/cdda-guide/#/item/jacket_army

OK so perhaps renaming it to "cammo jacket" and removing the "favoured by the military" text would be a good start, followed by renaming the "army winter x" and "army pants" into "combat winter x" or "combat x" or "military x" perhaps for the sake of consistency would be better thing to do.  

I am pointing this out because it is confusing seeing a lot of "army x" but no army jacket, until the army jacket shows in unrelated places.

**Comment by fairyarmadillo** [comment]
An army jacket and a combat blouse are two different things. The blouse is a padded shirt that was recently added to provide protection for areas not covered by plate carrier vests. The jacket is a lightweight and mostly unarmored jacket. You are mistaken in thinking one was renamed to the other.
