### ISSUE TITLE
Allow construction of pavements and sidewalk

### ISSUE THREAD

**Issue by Armadillidius** [CleverRaven/Cataclysm-DDA#64325]
### Is your feature request related to a problem? Please describe.

Pavements and Sidewalks does not have construction recipe, it is reasonable considering the difficulty of paving with asphalt.
However, I think it is possible to build pavements and sidewalks with rock or brick pavers as an alternative to asphalt.

### Solution you would like.

Add construction recipes for pavements and sidewalks using rocks or bricks and other material such as concrets.

### Describe alternatives you have considered.

Add new terrains for paved rock/brick road.

### Additional context

Building a base camp is one of the pleasures of this game, so I think it's good to have more construction options.
Also, I was wondering about the lack of building recipes that use rocks and bricks for paving.

**Comment by Zireael07** [comment]
Why close?

**Comment by Armadillidius** [comment]
Sorry, it was accidentally closed.
