### ISSUE TITLE
When applying a bandage or an antiseptic, the resulting effect quality is greater than expected

### ISSUE THREAD

**Issue by Winged03** [CleverRaven/Cataclysm-DDA#64339]
### Describe the bug

When you apply a bandage or an antiseptic, the resulting bandaging or disinfecting quality effect is one tier higher than the actual bandaging/disinfecting quality of the item that you used. This lasts only one turn, i.e. the turn you are in after you applied the item. When you skip one turn, the effect turns to the expected value. For example, if you apply a bandage that has an "Actual bandaging quality: poor", the first turn after you do so you will have a "Bandaged [average]" effect, which then gets reduced to "Bandaged [poor]" after one turn.
The reason this is bothering me is that if you decide to bandage your damaged limbs sequentially, you will be confused by what the limb selection menu displays when you activate a bandage. The last bandaged limb will always has better bandaging quality than you expected it to be, but after the application of the next bandage it turns to the expected value, while the last bandaged limb always has greater effect quality than it should.

### Attach save file

N/A

### Steps to reproduce

1. Make a player with default skills, spawn a bandage.
2. Damage one of your limbs.
3. Note the actual bandaging quality of an item. Apply the bandage on one limb.
4. Observe that the effect you received is one tier higher than expected.
5. Skip one turn.
6. Observe that the effect quality got lowered.

### Expected behavior

The resulting bandaging/disinfected effect should be the same as the one mentioned in the applied item description.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 363272a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by matt32106** [comment]
Is it not skill or proficiency related?

**Comment by Winged03** [comment]
Doesn't seem like it. With better skill or proficiency, the applied effect quality is better, but the bug remains, it still shows that the received effect is one tier higher than "actual bandaging quality" of an item, for one or two turns after application.

**Comment by matt32106** [comment]
I confirm your report, same issue forme.

**Comment by MochaModifier** [comment]
Have been experiencing this as well - it seems to be more that at the instant you treat the wound, it is at it's "maximum quality", which the UI shows as being a step above.
The next instant (easy to see by going to apply another bandage) you see that the wound has the expected treatment quality.

It's possible that the skill level is causing treatment to briefly go JUST a point above expected quality - but then it immediately drops to the expected quality.
