### ISSUE TITLE
[QoL] Automatically use tinder from inventory or nearby when lighting a fire

### ISSUE THREAD

**Issue by Light-Wave** [CleverRaven/Cataclysm-DDA#64338]
### Is your feature request related to a problem? Please describe.

Right now in order to start a fire with a fire drill or an other fire starter with the REQUIRES_TINDER tag, you have to have a piece of tinder on the tile you want to light. While I don't mind having to spend tinder, the extra steps required to place a piece of tinder on the tile is a bit annoying.

### Solution you would like.

If there is no tinder on the tile you're trying to light, the game should check your inventory and surrounding tiles for tinder, and if it finds a source, pull 1 tinder from there to the tile you're lighting. We don't want to just delete the tinder, since that would negate the slightly increased burn time that the tinder provides. If there are more than one source of tinder, perhaps the player should be asked which source they want to draw from.

### Additional context

The relevant code is in [src/activity_handlers.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/ce6abcdb376cfef925efcd4f4a371b9f9d5ec026/src/activity_handlers.cpp), in start_fire_do_turn( player_activity *act, Character *you ). 
See the line `if( !here.tinder_at( where ) ) {` 
Perhaps a way to do it would be to after this line add a nestled if statement that checks if it can find tinder nearby, and if it can, use it. If it can't, then cancel the activity as before.

The fact that drills require tinder was changed in #62662.

**Comment by NyarlathotepZERO** [comment]
TBH, I was quite surprised to find that this issue was only 4 days old.
