### ISSUE TITLE
Atomic Coffee Maker

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#64348]
### Describe the bug

Recently, (not sure which update) has changed the atomic coffee maker to require charges, while other 'atomic' items such as the atompot or atomic smartphone doesn't.

### Attach save file

[Willow City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11006573/Willow.City-trimmed.tar.gz)

### Steps to reproduce

1. load up the save.
2. attempted to create water with atompot.  See that it works.
3. destroy atompot (or get away from it so it doesn't default) and try to make water with atomic coffee maker.
4. notice it says it requires a list of items, one of them being an atomic coffee maker that needs charges.

### Expected behavior

the standard atomic item has no charges/last indefinitely.

### Screenshots

![cdda bug](https://user-images.githubusercontent.com/50846380/226058358-9ffc5f1e-32c1-43d5-95e4-932d0de5de0c.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: 7863db8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    Xedra Evolved [xedra_evolved],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/64345

**Comment by JonnieCache** [comment]
The issue as far as I can see is that the atomic coffemaker has been updated to require a medium battery, but despite the magazine type being defined in the json you cannot insert batteries into it ingame, and it is not listed as taking batteries.

**Comment by flybye3o6** [comment]
#64336

**Comment by Terrorforge** [comment]
This is an intended change, but it does create an inconsistency in Aftershock. The Aftershock version of the item should probably be reverted to its old functionality

Or I guess you could change the other atomic items to the coffeepot's new behavior where it offers a massive discount rather than infinite free energy, but I'm not personally a huge fan of that solution.

**Comment by flybye3o6** [comment]
or radical change, take the atomic stuff out of the base game and put it all in Aftershock, RTGs shouldnt be consumer items, military and secret labs sure maybe, i found this stuff just in normal houses
