### ISSUE TITLE
unlimited trade with Hub 01

### ISSUE THREAD

**Issue by gbaromhunter** [CleverRaven/Cataclysm-DDA#64346]
### Describe the bug

When trading with Hub 01, there is no limitation. Even if it's specified they don't trust you or trade is not permitted, if you try you will succeed with all the items.

### Attach save file

[Satartia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11006169/Satartia-trimmed.tar.gz)

### Steps to reproduce

1. complete a mission for the hub 01
2. attempt a trade without credits or trust
3. see that even if the trade in theory is not permitted, you can attempt and it will be accepted

### Expected behavior

you should not be able to complete a trade if you do not have the proper requisites

### Versions and configuration

windows, experimental version

**Comment by andrei8l** [comment]
How are you selecting the items?

**Comment by andrei8l** [comment]
I can't reproduce. I've tried all the `Mark ...` shortcuts (right arrow, mouse click, mark selected amount, press number then right arrow, category select, autobalance) but the unavailable items can't be selected.

**Comment by MikasaTanikawa** [comment]
Could confirm (at least in cdda-experimental-2023-03-21-2334 on win7).

Items could be selected only with `+` and `-` keys (numpad or regular). Also could sell back restricted items; see screenshot.

![Screenshot - 24_03_2023 , 01_30_55](https://user-images.githubusercontent.com/128552044/227381741-f87f0288-9295-43f1-906c-3a55ba402216.png)
