### ISSUE TITLE
Longsword +2 (Magiclysm) can not be used with Iron Heart martial art (Mythical Martial Arts)

### ISSUE THREAD

**Issue by andreiostanin** [CleverRaven/Cataclysm-DDA#64358]
### Describe the bug

Longsword+2 from Magiclysm isn't a valid weapon when used with Iron Heart style. Wiki says longsword should be a viable weapon (https://cddawiki.chezzo.com/cdda_wiki/index.php/Mythical_Martial_Arts_(mod)#Iron_Heart).

### Attach save file

[Huntersville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11008208/Huntersville-trimmed.tar.gz)

### Steps to reproduce

1. Learn "Iron Heart" style from Stormguard Warrior book (Mythical Martial Arts mod)
2. Equip Longsword +2 (Magiclysm mod)

### Expected behavior

I expect Longsword +2 work with Iron Heart

### Screenshots

<img width="1280" alt="screen" src="https://user-images.githubusercontent.com/114659656/226099073-0df38897-5cd1-4f32-9f49-eb7f868fb071.png">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: 2c69d7b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by Terrorforge** [comment]
Not a bug, the wiki is just outdated. Iron Heart uses medium swords, which the long sword is not.
