### ISSUE TITLE
Crash when cancelling fast travel

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#64355]
### Describe the bug

Crash when cancelling fast travel

### Attach save file

[Alexandria Bay-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11007800/Alexandria.Bay-trimmed.tar.gz)

### Steps to reproduce

Start the game
Open map
Double tap "W" to make fast travel
Press "no" when the message "Travel to this point? (Case sensetive)" appeared
Crash

### Expected behavior

No crash

### Screenshots

<details>
  <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/102726167/226091365-c975ef48-6309-49af-826f-54ff806ccf72.png)

![image](https://user-images.githubusercontent.com/102726167/226091334-238f4d5d-c1e1-41a5-bb80-79404ba6f1d1.png)

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 645d863 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11007804/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11007805/debug.log)

**Comment by BrettDong** [comment]
It's caused by #64174.

**Comment by BrettDong** [comment]
Should be fixed by #64353.

**Comment by KHeket** [comment]
> Should be fixed by #64353.

Yep. Problem fixed, thx
