### ISSUE TITLE
[XEDRA Evolved] Missing word in description

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64366]
### Describe the bug

There is a missing word (presumably cast?) in a class description (see screenshot)

### Attach save file

N/A

### Steps to reproduce

1.spawn strict eater-of-dreams class spell learner item
2.see missing word when you get the lock-out message

### Expected behavior

N/A

### Screenshots

![Untitled](https://user-images.githubusercontent.com/71761521/226111028-0efa9627-7c51-4d91-ad14-557f0c055ac1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 645d863 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Maleclypse** [comment]
Also a double period and extra space at the end of the dreamer text.

**Comment by Pointabc** [comment]
Created a PR for this issue "Fixed translation and double spaces" in json https://github.com/CleverRaven/Cataclysm-DDA/pull/64442".

**Comment by Maleclypse** [comment]
Fixed in 64442
