### ISSUE TITLE
Blank effects on the Effects tab of the @ screen

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#64376]
### Describe the bug

Somehow, a blank effect or two appeared on my character's effect's tab in the @ screen. When highlighted it doesnt show anything.

### Attach save file

[Floraville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11009761/Floraville-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save.
2. open the character's @ screen
3. blank effect.

### Expected behavior

the blank effect(s) not being there.

### Screenshots

![Screenshot_20230319-052822](https://user-images.githubusercontent.com/78019001/226143635-6a22d3e7-e64b-40da-88df-132631563147.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: a577338 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod]
]

**Comment by misterprimus** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/45959491/226151320-926cf002-6597-48ec-b6d7-bb4016cd7ff1.png)

**Comment by strategineer** [comment]
looking at the save file, these are the effects I found on the character

```
{
    "bandaged": {
        "torso": {
            "eff_type": "bandaged",
            "duration": 20039,
            "bp": "torso",
            "permanent": false,
            "intensity": 1,
            "start_turn": 5254394,
            "source": {
                "character_id": -1,
                "faction_id": "",
                "mfaction_id": ""
            }
        }
    },
    "hunger_blank": {
        "bp_null": {
            "eff_type": "hunger_blank",
            "duration": 86400,
            "bp": "bp_null",
            "permanent": true,
            "intensity": 1,
            "start_turn": 5363700,
            "source": {
                "character_id": -1,
                "faction_id": "",
                "mfaction_id": ""
            }
        }
    },
    "bad_food_ennui": {
        "bp_null": {
            "eff_type": "bad_food_ennui",
            "duration": 1,
            "bp": "bp_null",
            "permanent": true,
            "intensity": 2,
            "start_turn": 5252400,
            "source": {
                "character_id": -1,
                "faction_id": "",
                "mfaction_id": ""
            }
        }
    }
}
```

A newly created character has the following effects:
```
{
    "hunger_blank": {
        "bp_null": {
            "eff_type": "hunger_blank",
            "duration": 86400,
            "bp": "bp_null",
            "permanent": true,
            "intensity": 1,
            "start_turn": 5212800,
            "source": {
                "character_id": -1,
                "faction_id": "",
                "mfaction_id": ""
            }
        }
    }
}
```

So it doesn't seem like there's any effect that's unaccounted for. Might be a UI bug?

**Comment by strategineer** [comment]
In this case, the following line was the culprit:

player_display.cpp
```
for( const std::pair<std::string, std::string> &detail : enchantment_cache->details ) {
    effect_name_and_text.emplace_back( detail );
}
```

I'll implement a fix on the UI side for this.
