### ISSUE TITLE
Linux curses build seems to be non-functional

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#64389]
### Describe the bug

Ever since the 16th of March, when I tried to install the then-latest experimental curses build of the game on my Ubuntu Linux virtual machine, the game has refused to so much as open. The game simply doesn’t run in terminal, nor does it bring up an error message, which I and my screen reader have been able to catch. 0.G stable runs just fine, and the last functioning copy of the game that I’ve been able to confirm runs is build 77852f8.

### Attach save file

N/A

### Steps to reproduce

Grab an Ubuntu distribution of Linux (in my case, Ubuntu 18.4 running as a virtual machine).
Grab the latest experimental Curses build of the game.
Try to run it and find that nothing happens, either when trying to run the game through the terminal or simply pressing on the cataclysm_launcher file.

### Expected behavior

I expected that the game would allow me to play the game and do things within the game.

### Versions and configuration

OS: Ubuntu 18.04
- Game Version: [: Terminal
All other details irrelevant.

**Comment by andrei8l** [comment]
Ubuntu 18.04 loses support in April and we've switched our runners to 20.04
