### ISSUE TITLE
Book variants do not overwrite the skill they train (and overall status of AAA)

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#64408]
### Describe the bug
Book variants do not overwrite the skill they train
### Attach save file
N/A
### Steps to reproduce
Spawn a `Science of Revolutionary Warfare`, see it has no driving skill
Check https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/book/driving.json#L236, see it has one
![image](https://user-images.githubusercontent.com/67688115/226313663-945faffc-ee8c-42d3-bdcc-3cd6bfae4ef8.png)
### Expected behavior
Fix the variant skill inheritance
Change `AAA Guide` to train chemistry, and not driving skill
Split `AAA Guide` variants into separate books, with respected recipes (hard)
### Versions and configuration
- OS: Windows     
- OS Version: 10.0.19044.2728 (21H2) 
- Game Version: 72e5ffe [64-bit] 
- Graphics Version: Tiles 
- Game Language: System language [] 
- Mods loaded: [     
Dark Days Ahead [dda],     
Disable NPC Needs [no_npc_food],     
Portal Storms Ignore NPCs [personal_portal_storms],     
No Fungal Growth [no_fungal_growth],     
Bionic Professions [package_bionic_professions] 
]

**Comment by anothersimulacrum** [comment]
This isn't a thing variants can do, or that I would expect them to be capable of. I can look at why it's not reporting unvisited members for that.

**Comment by anothersimulacrum** [comment]
Resolved in https://github.com/CleverRaven/Cataclysm-DDA/pull/64494
