### ISSUE TITLE
Hang on attempting wield with many items

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#64406]
### Describe the bug

If container has non-zero wield cost (pocket_data[].moves) and a lot of items inside, opening wield menu takes ages of irl time - more than 10 minutes in provided save.  
Changing cost to 0 makes menu open in under one minute.

### Attach save file

[wcost.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11016568/wcost.zip)

### Steps to reproduce

1. in game\data\json\items\armor\storage.json L2400:
    change to
    ```
        "weight_multiplier": 0.00,
        "volume_multiplier": 0.00
    ```
    so character could actually stand,
2. in game\data\json\items\armor\storage.json L2398: change `"moves": 1,` to `"moves": 0,`
3. spawn and wear debug backpack
4. grant char every item
5. try to open wear menu - it opens almost instantly
6. try to open wield menu - it opens in a minute
7. save and exit
8. in game\data\json\items\armor\storage.json L2398: change `"moves": 0,` to `"moves": 1,`
9. load game - it will take a lot of time
10. try to open wear menu - it still opens almost instantly
11. try to open wield menu - game window hangs, ~10 minutes for the menu to show

### Expected behavior

Move cost shouldn't influence how long it takes to open a menu
Menu should open in less than a minute
Subsequent menu access should be instantenous - add per-item caching maybe?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: b738ae2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by andrei8l** [comment]
You have ~9000 unique, non-stackable items in the pocket universe. The wield menu does open several orders of magnitude slower than the inventory so this does look like a real bug, but fixing it has mostly only academic value.

**Comment by ZhilkinSerg** [comment]
> But why it's faster with zero move cost? Neither [item_handling_cost](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L6706) or [obtain_cost](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_pocket.cpp#L2029) have special path for 0.

Because game is processing while items are being moved.
