### ISSUE TITLE
A warning if you are going to overwrite a character

### ISSUE THREAD

**Issue by Neokami** [CleverRaven/Cataclysm-DDA#64413]
### Is your feature request related to a problem? Please describe.

I have noticed that since I have set up a preferred name I always forget to change it when testing or checking things to do with other professions. If I make a character using the same name as another character in that world it does not warn that the other character will be replaced.

### Solution you would like.

The best thing I can think is having another "are you sure" popup when making a character, something along the lines of
`|------------------------------------------------------|`
`|                     /| WARNING |\                    |`
`|    [Character name] already exists in [World Name]!  |`
`|    Continuing will overwrite the previous character. |`
`|------------------------------------------------------|`

**Comment by ZhilkinSerg** [comment]
Huh?

![image](https://user-images.githubusercontent.com/16213433/226424919-d9635bdc-2235-48bf-8bd1-55f9480b7183.png)

**Comment by strategineer** [comment]
Ya, this feature was implemented here https://github.com/CleverRaven/Cataclysm-DDA/pull/22378/files

The regression seems to be here https://github.com/CleverRaven/Cataclysm-DDA/commit/a1bf4e975be#diff-da8a925e8abf39943d87477831cecd3686ad13b250b7bc1c4bd74ffeaaefce34L758
