### ISSUE TITLE
Auto eat will make you eat any comestible, even if its poisonous

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64433]
### Describe the bug

Title, Due to that. it will also spam the "are you sure you want to eat this? its poisonous..." every turn if you're crafting/waiting

### Attach save file

N/A

### Steps to reproduce

1.make auto eat zone
2.put edible, but poisonous food in the zone, such as elderberries.
3.wait or craft something, make yourself hungry to make it appear faster

### Expected behavior

For it to eat only non-poisonous food.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 127ec42 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
Then it should probably also avoid food your character is allergic to, as well as the hiddenly poisonous category called Junk Food.
