### ISSUE TITLE
cryptic error when generating a spawn for a new character

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64435]
### Describe the bug

Game throws a cryptic error (screenshot) when trying to place the newly-made-character.

### Attach save file

N/A

### Steps to reproduce

1.download the two files, the world file and the template file
2.use the template with the given world
3.game either hangs or gives you the error

### Expected behavior

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/71761521/226636937-29f97a7a-75e6-4d7a-8500-bc794875b411.png)
[Depths Of Jupiter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11029361/Depths.Of.Jupiter.zip)
[magic apprentice.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11029365/magic.apprentice.zip)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 127ec42 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by BrettDong** [comment]
Might be related to https://github.com/CleverRaven/Cataclysm-DDA/pull/63611.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/64421
