### ISSUE TITLE
Mutation fur can be cut up with knives.

### ISSUE THREAD

**Issue by Wyghab** [CleverRaven/Cataclysm-DDA#64445]
### Describe the bug

Fur gained from mutations can be cut up for fur patches.

### Attach save file

N/A

### Steps to reproduce

1. Create any character.
2. Use debug menu to mutate sleek fur.
3. Spawn a cutting implement
4. (a)ctivate your cutting implement and cut up your fur

### Expected behavior

I expect cutting up your own fur (basically your skin) is not a good idea, if possible it should give a lot of pain and regrow very slowly.

### Screenshots

![image](https://user-images.githubusercontent.com/47194578/226740721-19fbf35f-dbb5-415c-a590-3b75f49815e8.png)
![image](https://user-images.githubusercontent.com/47194578/226740739-b8b64318-38d3-4f71-81a5-f90e6b14deeb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: b738ae2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by TheShadowFerret** [comment]
> If possible it should ~~give a lot of pain and regrow very slowly~~ **lead to your inevitable death by skin infection from cutting off your pelt(cuz loose hairs don't make a fur patch)**.

FTFY :3

**Comment by anoobindisguise** [comment]
this hasn't been true for literal months, fur integrated armors are made of a separate material.

**Comment by TheShadowFerret** [comment]
>this hasn't been true for literal months, fur integrated armors are made of a separate material.

```
{
    "type": "material",
    "id": "mut_fur",
    "name": "Mutant Fur",
    "density": 1.1,
    "specific_heat_liquid": 0.02,
    "specific_heat_solid": 0.02,
    "latent_heat": 333,
    "soft": true,
    "bash_resist": 0.5,
    "cut_resist": 0.31,
    "bullet_resist": 0.25,
    "acid_resist": 1,
    "fire_resist": 1,
    "chip_resist": 8,
    "breathability": "POOR",
    "repaired_with": "fur",
    "salvaged_into": "fur",
    "dmg_adj": [ "ripped", "torn", "shredded", "tattered" ],
    "bash_dmg_verb": "ripped",
    "cut_dmg_verb": "sliced",
    "burn_data": [
      { "fuel": 1, "smoke": 3, "burn": 1, "volume_per_turn": "1250 ml" },
      { "fuel": 1, "smoke": 5, "burn": 2 },
      { "fuel": 1, "smoke": 10, "burn": 4 }
    ],
    "burn_products": [ [ "corpse_ash", 0.035 ] ]
  }
  ```
  
  Why is there a salvaged_into here 😛

**Comment by Wyghab** [comment]
> this hasn't been true for literal months, fur integrated armors are made of a separate material.

While I'm quite certain I saw a fix for integrated armors in the past, I'm not bug reporting an ancient version of the game, but an experimental from within the week. The version shown (generated by ingame report) has the latest merged PR as the menstruation misc items. For completeness sake I am currently updating my game to test it once again on the most recent version.

**Comment by Wyghab** [comment]
![image](https://user-images.githubusercontent.com/47194578/226789603-516e834e-50e9-46cc-87c6-70869b350636.png)
As you can see, it still works on latest experimental.
![image](https://user-images.githubusercontent.com/47194578/226789677-187149c2-256e-49f5-9618-47d4a02f640d.png)
![image](https://user-images.githubusercontent.com/47194578/226789740-f0e8b51e-8038-4397-aa27-1655ed95737f.png)
