### ISSUE TITLE
Vehicle Lights are inside vehicle. Should be outside?

### ISSUE THREAD

**Issue by Loodrogh** [CleverRaven/Cataclysm-DDA#64444]
### Describe the bug

If I install vehicle headlights on my vehicle, in my opinion, they should first illuminate the outside/surroundings of the vehicle. However, it seems that they only/first illuminate the interior. Assuming they are located at the edges of the vehicle, they also illuminate outward. But as soon as I place them in the interior of the vehicle, they only illuminate the inside. This means that they do not project light outward when all curtains and doors are closed. 

Is there a way to install the lights explicitly inside or outside?

### Attach save file

[Final Aphorism-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11033363/Final.Aphorism-trimmed.tar.gz)

### Steps to reproduce

1. Install a headlight/floodlight inside a vehicle, but not on the edges. (maybe just above your driving seat, or back at the trunk)
2. make vehicle light-protected. So curtains to all windows and doors.
3. close all curtains -> dark inside
4. optional: wait until sunset
5. turn lights on.

### Expected behavior

Lights should be visible outside. The surroundings should be flooded with light. It should remain dark inside.

Maybe give an option if Lights should be installed inside, or on top (if roof is on that tile), or on edge (if you have a vehicle wall there).

### Screenshots

![Lights CDDA](https://user-images.githubusercontent.com/68752459/226737625-595b0bf9-d530-4117-931c-39539b8618c1.jpg)

F=Floodlight ON
C=closed Curtains on Windows/Doors
O=opened Curtain on open Door

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Undead People
- Game Language: Systemsprache [German]
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Wyghab** [comment]
To me that looks like it's working as intended, since the light is not mounted on the roof, but inside the vehicle. Naturally the light doesn't pierce the walls or ignore the inside.

**Comment by Loodrogh** [comment]
> To me that looks like it's working as intended, since the light is not mounted on the roof, but inside the vehicle. Naturally the light doesn't pierce the walls or ignore the inside.

So is there a way to install the light outside?? Otherwise, I'm surprised that I've never noticed that before. I thought floodlights were roof-mounted lamps that are attached to the outside of the vehicle.

**Comment by nemesis688** [comment]
In my game I have a floodlight mounted on the outside edge of my vehicle and the light passes through the heavy-duty boards into the interior. I suspect its cause the outside boards of vehicles don't have roofs by default. It does feels wrong even if its working how its supposed to though.

**Comment by Loodrogh** [comment]
From the lights.json:

 "id": "floodlight",
    "type": "vehicle_part",
    "item": "floodlight",
    "location": "on_roof",
    "description": "A very bright, circular light that illuminates the area outside the vehicle when turned on.",

**Comment by pjf** [comment]
I think this one has been around for a while, and I remember hitting it myself.

Most notably, it's described in:

- #34764

**Comment by Loodrogh** [comment]
> Most notably, it's described in:
> 
> * [Floodlights blocked by vehicle structure #34764](https://github.com/CleverRaven/Cataclysm-DDA/issues/34764)


Jep, that's it. Sad to see it's around since nearly 4 years. So that makes floodlights a bit useless. 
I tried this with normal and broad headlights too. It's the same thing. When it's not on the edge of vehicle, it seems it is (b)locked inside the car walls. 

Like the reporter mentioned above, I wanted to use this in combination with cameras for night too. Now you have to use many more lights and therefore power, to cover/enlighten areas around you.

Also noticed, that you can install (broad and normal) headlights on a tile with solarpanels but no floodlight.


So this case can be closed. Although without solution...
