### ISSUE TITLE
Game crashing on player death when using a custom EoC of type "PREVENT_DEATH"

### ISSUE THREAD

**Issue by ProAtWorkHere** [CleverRaven/Cataclysm-DDA#64448]
### Describe the bug

I have written a simple test mod that uses the PREVENT_DEATH EoC to prevent dying and the game is crashing occasionally when it is triggered, in particular if a teleport is used (debug menu and u_teleport both exhibit this behaviour) before dying again. It appears to only happen when dying from a monster's attacks. It is inconsistent in it's occurance, but an almost sure-fire way to get it to happen is with the provided save file. I have also had this crash occur even without using a teleport, but that is much rarer and hard to reproduce. I have stripped down the player reviving EoC as much as possible, and the issue persists.

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11034781/test-trimmed.tar.gz)

### Steps to reproduce

1. Use long-range teleport to go to another overmap tile, with monsters present.
2. Allow yourself to die to the monsters.
3. In most cases, the game will crash upon death. Sometimes it does not happen unless multiple deaths are incurred. This save seems to fairly consistently cause the crash with this method.

### Expected behavior

The EoC should function consistently and not crash the game when being triggered.

### Versions and configuration

OS: Windows 10 Pro 64-bit
Version: 0.G stable
Graphical Version: Tiles
Ingame Language: English
Mods Loaded: default mods and my test mod provided with the report.
[eoc_crash_test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11034804/eoc_crash_test.zip)

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11034805/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11034806/debug.log)

**Comment by andrei8l** [comment]
/confirmed the `killer` variable isn't cleared on resurrection and the game crashes on next death if the previous killer doesn't exist anymore

Potential patch:
```diff
diff --git a/src/creature.cpp b/src/creature.cpp
index d8353c32ef..596725947a 100644
--- a/src/creature.cpp
+++ b/src/creature.cpp
@@ -1829,9 +1829,7 @@ Creature *Creature::get_killer() const
 
 void Creature::set_killer( Creature *const killer )
 {
-    // Only the first killer will be stored, calling set_killer again with a different
-    // killer would mean it's called on a dead creature and therefore ignored.
-    if( killer != nullptr && !killer->is_fake() && this->killer == nullptr ) {
+    if( killer == nullptr || !killer->is_fake() ) {
         this->killer = killer;
     }
 }
```
