### ISSUE TITLE
Hub NRE math improvement

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#64451]
### Is your feature request related to a problem? Please describe.

Currently the math in NRE printout data is still not that reasonable. I simulated different strategies in the format of data that got printed out ( prioritize large data, prioritize medium data, etc. ), I found that it's particularly low-rewarding to prioritize large data than prioritizing medium data. "Prioritze" here means the player will always try to print that type of data, as long as it's possible. If not possible, fallback to the other two types.

Here are a table, showing the expected income in the portal storm using different strategies. The left two columns are the length range of portalstorm (the actual length is an uniform distribution between them). The right part is different (price in HGC, time needed) combinations, representing the preference in printing out that type of data.

min_length | max_length | 1,5 | 5,15 | 18,125 | 50,125 | 70,125
----| -----|-----|----|-----|-----|------
120 | 240 | 38.6001 | 63.2072 | 23.4258 | 56.9976 | 77.875
135 | 255 | 41.5392 | 68.3937 | 25.5267 | 63.4473 | 86.1572
150 | 270 | 44.6046 | 73.3533 | 27.8915 | 69.1441 | 94.9766
165 | 285 | 47.4888 | 78.4808 | 30.1563 | 75.6433 | 103.803
180 | 300 | 50.6116 | 83.1138 | 32.1332 | 81.2671 | 112.698
195 | 315 | 53.6674 | 88.2018 | 34.3852 | 87.7259 | 121.396
210 | 330 | 56.5722 | 93.1439 | 36.6221 | 93.9679 | 130.155
225 | 345 | 59.5814 | 98.3811 | 38.9536 | 100.235 | 138.667
240 | 360 | 62.6515 | 103.409 | 40.7364 | 105.004 | 145.186

The sheet is generated using the C++ code below.

```
#include <cstdio>
#include <cmath>
#include <iostream>
#include <random>
void trial( int price, int time )
{
    int min = 2 * 60, max = 4 * 60;
    for( int i = 0; i <= 8; i++ ) {
        min += 15;
        max += 15;
        random_device seed;
        ranlux48 engine( seed() ); 
        uniform_int_distribution<> distrib( min, max );
        int sum = 0;
        for( int j = 0; j < 10000; j++ ) {
            int random = distrib( engine ); 
            int longp = random / time;
            int remain = random % time;
            sum += price * longp;
            if( remain > 15 ) {
                sum += 5;
            } else if( remain > 5 ) {
                sum += 1;
            }
        }
        double income = sum / 10000.0;
        std::cout << income << "\n";
    }
}
int main()
{
    int price, time;
    std::cin >> price >> time;
    std::cout << '\n';
    trial( price, time );
}
```
It's visible that large data is inferior in income compared to the medium one, thus making Hub a bad task assignor.

### Solution you would like.

I think the reward of large data should be drastically increased. Increasing to 50 HGC will result in the same reward expectation as medium data, thus this should be the lower limit, assuming Hub will take one large data more preciously than 25/3=8.3 medium data. Increasing to 70 HGC will result in approximately the same income gradient from medium data to large data as from small data to medium data.

### Describe alternatives you have considered.

Or we can decrease the time needed to print a large data. Lowering from 125 minutes to 50 minutes will result in a nearly same reward expectation as medium data.

**Comment by John-Candlebury** [comment]
The reward for the longer data is supposed to mostly be a large amount of faction reputation, although I haven't added any way for you to cash on that. The monetary rewards can probably be adjusted upwards even then, although I rather not have exact parity against the short ones.
