### ISSUE TITLE
Player/Item duplication

### ISSUE THREAD

**Issue by H3LL-J3F3** [CleverRaven/Cataclysm-DDA#64461]
### Describe the bug

Player can duplicate items by dying and forcing the game to quit. Re-launching the game allows loading the same character with a duplicated character dead on the ground.

### Attach save file

N/A

### Steps to reproduce

1. Quick save the game
2. Abandon character
3. Force the game to exit before being returned to the main menu (Alt-F4)
4. Re-launch the game. The character that died is still available to load
5. On loading, character is in the state from the last quick save and a duplicated copy of the character with items is present in the world (but dead)

### Expected behavior

Character should no longer be able to be loaded or the duplicate (dead) copy of the character should not be present in the world

### Screenshots

![Capture1](https://user-images.githubusercontent.com/121635735/226803200-977321ef-c878-4fc5-90d0-91afc1514af0.PNG)
![Capture2](https://user-images.githubusercontent.com/121635735/226803202-b100c8f8-f524-4fe7-b68b-42b3b038cd19.PNG)

### Versions and configuration

- OS: Windows 10
- Game Version: d68b877329 (latest Head)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions

**Comment by irwiss** [comment]
Whethe body is left or not depends on the exact point you kill the game process during the dying sequence

Either way save scumming bugs are basically non bugs https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#user-content-Rogue_Like

**Comment by H3LL-J3F3** [comment]
That's fair, there are certainly easier ways to accomplish a similar affect (debug menu). Just seems like a potential indication that the character and world could get out of sync  in other (non savescumming) situations. Will close and open a new issue if I come across such a situation.
