### ISSUE TITLE
Delayed Transform for liquid phase unusable in stacks

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#64471]
### Describe the bug

"use_action" `"delayed_transform"` is bugged for liquid phase items such as `fermenting yogurt` and `curing roe`
when activated it will transform them one at a time, and because they are liquid they will drop on the floor becoming dirty and unable to be picked up

previously in 0.F when activating one of these items it would transform the whole stack and leave it in its container
changes to code for transforming charges one charge at a time has caused this
```
if( it.count_by_charges() && it.count() > 1 ) {
        item take_one = it.split( 1 );
        do_transform( p, take_one );
        p.i_add_or_drop( take_one );
```
possibly a way for liquid to skip over this could be the quickest fix

### Attach save file

N/A

### Steps to reproduce

1. craft fermenting yogurt
2. place all fermenting yogurt in gallon jug
3. wait/debug change the time
4. activate fermenting yogurt
5. finished yogurt will be on the ground and stack of fermenting yogurt will still be in its container

- 

1. get 10 glass flasks (or any container with 0.25L)
2. craft fermenting yogurt
3. split fermenting yogurt into the 10 glass flasks so there is one in each
4. wait/debug change the time
5. activate fermenting yogurt one by one
6. yogurt will stay in its container

### Expected behavior

transform for liquid phase to work as it did before
transform the whole stack in a container at once and leave it in that container

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 9d3d406 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

#64065 problem first brought to attention
#63277 changes to code that makes transform use charges one at a time

**Comment by andrei8l** [comment]
/confirmed We talked about this on discord

> possibly a way for liquid to skip over this could be the quickest fix

That sounds about right.
