### ISSUE TITLE
Cooking recipes act like the atomic coffeemaker needs charges

### ISSUE THREAD

**Issue by lurkinglikeamofo** [CleverRaven/Cataclysm-DDA#64484]
### Describe the bug

When attempting to make clean water with the atomic coffeemaker, the crafting recipe acts as if it needs charges which makes it unusable. 

### Attach save file

[Villa Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11046266/Villa.Hills-trimmed.tar.gz)

### Steps to reproduce

Get an atomic coffeemaker, stand next to a body of water and look up the clean water recipe. You won't be able to make it. 

### Expected behavior

I expected to be able to make clean water like I've done in the past, is this a bug or an intended change?

### Screenshots

![atomiccoffeemaker](https://user-images.githubusercontent.com/93702587/227081550-b549ae76-2107-4908-bd4b-80276f282ef6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: d2ccb85 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]

**Comment by irwiss** [comment]
After https://github.com/CleverRaven/Cataclysm-DDA/pull/62180 atomic coffeemaker is a slightly more efficient one, the scifi variant moved to Aftershock mod

**Comment by kevingranade** [comment]
Working as intended,  needs a power source now.
