### ISSUE TITLE
windows reported CDDA EXE is dangerous

### ISSUE THREAD

**Issue by konamichou** [CleverRaven/Cataclysm-DDA#64487]
### Describe the bug

windows reported CDDA EXE is dangerous

### Attach save file

1

### Steps to reproduce

1

### Expected behavior

1

### Screenshots

![image](https://user-images.githubusercontent.com/11663256/227106067-dfe961d2-f09d-4d8c-8ebd-b1a00082dc76.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: d2ccb85 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝) [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    XEDRA 超进化 [xedra_evolved],
    大魔法 [magiclysm],
    穷途末路 [no_hope],
    巨兽 [megafauna],
    恐龙世界 [DinoMod],
    更多变异场景 [extra_mut_scens],
    甜蜜大灾变 [my_sweet_cataclysm],
    疯狂大灾变 [crazy_cataclysm],
    神话武术 [MMA],
    翻译晦涩对话 [translate_dialogue],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    驯服野兽 [Tamable_Wildlife]
]

**Comment by andrei8l** [comment]
VirusTotal does not find any issues for the [msvc](https://www.virustotal.com/gui/url/d297fec41870c0fa2901b8b1f95409db0af8881e2df92576521d921ba674ec34?nocache=1) or [mingw](https://www.virustotal.com/gui/url/fc13e4863a929f9c1c21829e62fa4c8782564b308d0cd2f14e9e7d125217e3b7?nocache=1) builds

**Comment by RenechCDDA** [comment]
There was another user reporting the same detection in the development discord earlier today.

https://discord.com/channels/598523535169945603/642349261320880128/1088113577904316527

![image](https://user-images.githubusercontent.com/84619419/227107288-1037fcd5-9cbd-4e1e-bd70-98fc1b862239.png)

 It is almost certainly a false positive, but I'm not sure what (if anything ) could be done about it.

**Comment by Maleclypse** [comment]
This is a perennial problem with the newer experimentals.  Go a few days back and you should be able to get a version that's not quarantined or wait a few days for windows to decide this version shouldn't be quarantined.

**Comment by ZhilkinSerg** [comment]
False positive. Try to use antimalware software without bad heuristics.
