### ISSUE TITLE
The "Pickled Offal in a 3L Glass Jar" recipe throw an error.

### ISSUE THREAD

**Issue by Brixyia** [CleverRaven/Cataclysm-DDA#64498]
### Describe the bug

After trying to craft the recipe for the pickled offal, I got the error given bellow.
The game made 12 Unsealed 3L Glass Jar containing only one "charge" of Pickled Offal.

### Attach save file

The game is a few day later, I had to eat all the Offal to realize that I now had a dozen of empty 3L Glass Jar.
[Highland Heights-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11054369/Highland.Heights-trimmed.tar.gz)

### Steps to reproduce

1. Craft the 3L version of the Pickled Offal recipe
2. Wait for the craft to finish.

### Expected behavior

Don't throw any error, and give a unique Sealed 3L Jar.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: 4ad1388 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

   #14
     (dbghelp: RtlUserThreadStart+0x28@0x7ff968f2a9f8[ntdll.dll+0x5a9f8]), 
     (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
     (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
 Backtrace emission took 0 seconds.
 (continued from above) ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:09.445 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:10.006 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:10.453 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:10.677 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:10.885 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:11.110 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:11.397 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:11.766 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:12.437 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:13.269 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:17:13.269 ERROR : src/item_components.cpp:140 [item_components item_components::split(int, size_t, bool)] component water can't be evenly distributed to resulting items
 21:58:27.543 ERROR GAME : (error message will follow backtrace)

**Comment by mqrause** [comment]
Oops, seems I forgot to adjust mod recipes.
