### ISSUE TITLE
Crash to desktop with Exosuit Repair action from Exosuit maintenance gantry

### ISSUE THREAD

**Issue by NewOrlanth** [CleverRaven/Cataclysm-DDA#64495]
### Describe the bug

When using Exosuit maintenance gantry, Exosuit repair action, CDDA crash to desktop instantly.
It's an old problem but i can't find the previous big report and i thought it was fixed in 0.G but not.

### Attach save file

[MyNewWorld-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11051548/MyNewWorld-trimmed.tar.gz)

### Steps to reproduce

1 - Create a vehicle
2 - Spawn a MetalMaster forge buddy and install it in the vehicle as Exosuit maintenance gantry (which is a kind of weird, and lost is forge and kiln capabilities in the meantime but anyway).
3 - Use it and select "use exosuit repair kit"
4 - Select "repair" option
5 - Look at your beautiful desktop wallpaper. 

### Expected behavior

Not crashing. 

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin MacBook-Air.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112 x86_64
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

I can't find any crash.log file :(

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11051600/debug.log)

**Comment by SurFlurer** [comment]
Possibly duplicate of #63740.
