### ISSUE TITLE
Block attempt always fail under certain situation. 

### ISSUE THREAD

**Issue by asvc233** [CleverRaven/Cataclysm-DDA#64492]
### Describe the bug

When you enabled a martial art that doesn't allow any body block, and wearing an armor that has the same or even better blocking ability than your weapon, the blocking attempt automatedly get canceled. 

The problem is caused by line 2204 - 2215 in melee.cpp. Since the body armor is no worse than weapon under such situation, worn_shild is true and goes into body block check. If the MA doesn't allow arm block, leg block, or nonstandard block, the block attempt returns false always.  

### Attach save file

N/A

### Steps to reproduce

1. Picking a martial art that doesn't allow body block. 
2. Wearing an armor that has WBLOCK and BLOCK_WHILE_WORN flag. 
3. Holding a weapon that has the same or worse WBLOCK flag. 
4. Blocking attempt fails. 

### Expected behavior

I expected that my character would prefer weapon block even when wearing a better body armor if the MA doesn't allow body block. 

### Screenshots

![%DJM1FMSLM3 `9%{_~7`YE9](https://user-images.githubusercontent.com/52769304/227153555-c19e54cf-5188-4e8d-9d38-993691036486.png)
![{N7~7D2166{@YQYV294U}25](https://user-images.githubusercontent.com/52769304/227153556-2b4e88e1-7b8e-45bc-917b-3528a6b58935.png)

### Versions and configuration

-OS: windows 10
-Game version: experimental 2023-03-21-0556
-mod: dda

### Additional context

I tested with a character that has 80 str and 10 melee which nearly guarantees a total block. Both the weapon and armor have medium blocking ability. When wearing the armor, no block attempt shows up in debug message. Dropping the armor add back the blocking ability.

**Comment by Terrorforge** [comment]
Can confirm. Using Silat (no arm/leg blocks) with a Holy Shield (Magiclysm item with WBLOCK_3) leaves you unable to block with any weapon, but with krav maga (has arm/leg block) you still get the block.
