### ISSUE TITLE
[0.G] wrong santa_jacket coverage when loading game (i386)

### ISSUE THREAD

**Issue by reinerh** [CleverRaven/Cataclysm-DDA#64504]
### Describe the bug

When creating and starting a new game on an i386 platform, the following error is printed:
```
ERROR : src/item_factory.cpp:1209 [void Item_factory::finalize_post_armor(itype&)] item santa_jacket has coverage 101 for material cotton.
```

### Attach save file

N/A

### Steps to reproduce

Just start a game.

### Expected behavior

I expect the game to start without printing errors.

### Screenshots

![santa](https://user-images.githubusercontent.com/3106950/227344126-833c9d4a-4c71-406f-b59c-e48965d84a71.png)

### Versions and configuration

- OS: Debian Linux
- architecture: i386
- Version: 0.G

### Additional context

When you press space to continue, it prints a similar error about a few other items.

**Comment by RenechCDDA** [comment]
You've updated your game incorrectly by extracting the new download on top of the old one. Perform a fresh install.

**Comment by reinerh** [comment]
It was a fresh install. I actually installed a Debian package, which leaves no traces of an old installation. And I can reproduce it in a clean chroot environment where it has never been installed before.

**Comment by reinerh** [comment]
The error was actually first detected by Debian's CI tests. And i386 is currently the only architecture where it happens, so I think it's somehow related to running CDDA on this platform.

**Comment by kevingranade** [comment]
Talk to your friendly neighborhood debian maintainer,  we don't have an i386 build and don't have the resources to support it.
I had a chat with someone on the debian project about some floating point issues on various platforms, I don't recall if the solution we came up with applied to i386

**Comment by reinerh** [comment]
@kevingranade That Debian maintainer was me. :-)  We talked about the unittests during build.  
But the problem I'm seeing now is also happening when starting the game normally.
