### ISSUE TITLE
Fatal game error on vehicle movement attempt

### ISSUE THREAD

**Issue by SeamairGB** [CleverRaven/Cataclysm-DDA#64517]
### Describe the bug

Game crashes on attempting to move the damaged wooden carriage with 2 horses forwards from it's current position.
Moving backwards and then moving forwards seems to not kill the game.

### Attach save file

[Оттосен_copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11062180/_copy-trimmed.tar.gz)

### Steps to reproduce

Getting into reins and tackle on right side of wooden carriage and then attempting to move forwards from it's position.

### Expected behavior

On achieving forward speed of 1 km/h with carriage game is expected to crash with fatal error.

### Screenshots

![image](https://user-images.githubusercontent.com/112179678/227531395-e807692b-749a-4e2e-afb3-d426157a9d9d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 37d6251 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

### Additional context

[testing_save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11062377/testing_save.zip)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11062382/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11062383/debug.log)

**Comment by irwiss** [comment]
Couldn't reproduce on 199ac9b7c590e7110c4026997bb145918cdab098, from crash log it looks like something is crashing when accessing map memory, does the crash repeat for you or only happened once?

**Comment by SeamairGB** [comment]
I managed to crash game about 7 times in a row by doing same thing. Try using testing_save.zip, it *may* be different from trimmed save tho shouldn't

**Comment by SeamairGB** [comment]
Okay, trying that again with exact same save I used multiple times it stopped working. That seems to be very... weird. Only thing that changed is that I swapped back to russian language

**Comment by irwiss** [comment]
I can't replicate it on the self-compiled msvc version

cdda-windows-tiles-sounds-x64-msvc-2023-03-24-1105 - seems to load the save ok, no crash, similar to my self-compiled version

cdda-windows-tiles-sounds-x64-2023-03-24-1105.zip - seems to see the world but doesn't detect any characters in it

pretty weird

**Comment by irwiss** [comment]
I suggest you try using the msvc version instead and see if this bug reoccurs; the one where download link has msvc in the name: cdda-windows-tiles-sounds-x64-**msvc**-some-numbers.zip, may be there's yet another issue with mingw locales.

If you're already using it I'm out of ideas, may be someone else will come up with something
