### ISSUE TITLE
Plastic window with close.d curtains???

### ISSUE THREAD

**Issue by hoasd1** [CleverRaven/Cataclysm-DDA#64516]
### Describe the bug

There's added dot in ( plastic window with closed window ) which changed the name of the terrain to ( plastic window with close.d curtains ) that I think it's unintended to be added... right?

### Attach save file

N/A

### Steps to reproduce

1. Enter data
2. Enter json
3. Enter furniture_and_terrain
4. Open terrain-windows
5. Check line 3596

### Expected behavior

From plastic window with close.d curtains to plastic window with closed curtains.

### Screenshots

![Screenshot_20230324-134633](https://user-images.githubusercontent.com/82118059/227513137-41ca5ba4-eb06-479f-806b-750046d71e76.jpg)

### Versions and configuration

Game Version: cdda-experimental-2023-03-23-2229

### Additional context

Would take an alternative by saying it's not a bug it's a feature! x)

**Comment by flybye3o6** [comment]
/confirmed in hhg and in the files and in game
![image](https://user-images.githubusercontent.com/115079701/227515778-5ffeee5c-7e21-4be4-8174-86ba25d4966e.png)

**Comment by hoasd1** [comment]
I know how to use Github but I'm unwilling to do PRs to CDDA in the meantime :l

But look I'm still contributing through doing PRs to Ultica which gets updated to this repository every monday.
