### ISSUE TITLE
Android builds failing to generate (again)

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#64515]
### Describe the bug

Since cdda-experimental-2023-03-24-0154 the android builds have failed to generate, I assume it has to do with #64392, since the other PR merged in that build, #64361, only changed some test values.

### Attach save file

N/A

### Steps to reproduce

Search for any Android builds generated after the version mentioned, meaning, any recent builds from 10 hours until now (at moment of writing).

### Expected behavior

To have android builds generate properly.

### Versions and configuration

N/A

**Comment by mqrause** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/199ac9b7c590e7110c4026997bb145918cdab098/src/sdltiles.cpp#L2821-L2822

Yeah, some Android specific code wasn't updated because we have no Android CI.
