### ISSUE TITLE
kinetic charger Flag

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#64510]
### Is your feature request related to a problem? Please describe.

fitness band uses no power for action that should use power #64505

### Solution you would like.

Flag to add to items that contain a kinetic charger that can generate there own power though momentum
no need for swapping batteries or connecting to a power grid to recharge

a kinetic charger is an electric motor with an off-center weight that swings as you move around generating power on the forward swing and back swing
the power generated is minuscule with crank chargers being superior by a great margin
they do passively generate power for small devices worn on the wrists or ankles when running or walking(shouldn't generate when prone or crouch)

adding a tiny electric motor to the devices disassembly and crafting, though ideally the motor would be even smaller then that
could be added to fitness band and watches or other worn electric devices
could even as act like a battery mod replaces the battery with this self-charging battery option

### Additional context

 wristwatch kinetic charger
![image](https://user-images.githubusercontent.com/115079701/227406794-234a33f4-8697-4dbd-aa6f-15d0ac2d8b6f.png)
![image](https://user-images.githubusercontent.com/115079701/227408112-0f14cbd0-342e-49d2-b72f-901169ae35d1.png)
one directional kinetic charger
![image](https://user-images.githubusercontent.com/115079701/227410759-85888cd9-05fa-454e-8dc9-30b733f0413d.png)
heel strike kinetic charger
![image](https://user-images.githubusercontent.com/115079701/227408244-40a33a5a-4107-4340-b1f1-173834bb8301.png)
there is also these things (doubt they can reliably charge a phone)
![image](https://user-images.githubusercontent.com/115079701/227408395-bcf02694-be67-4c7f-84d4-d9a898edd54c.png)
wave generators would also be a kinetic generator
![image](https://user-images.githubusercontent.com/115079701/227414246-9677d544-3e17-44c9-8bfd-4f6275824a09.png)
![image](https://user-images.githubusercontent.com/115079701/227414395-c5e5f9c2-2fa5-4257-adf3-134d628625b1.png)

**Comment by irwiss** [comment]
I'm having trouble understanding this...

You want fitness band to consume power, but then want to add a flag to make it not consume power?

**Comment by flybye3o6** [comment]
no make it generate its own power with an unremovable battery store and have the action consume power
if warn and if running or waking add x kjs to items battery when moving to new tile

**Comment by irwiss** [comment]
Those devices seem to have about [~1.5kJ of power in them at the highest end](https://engineering.stackexchange.com/questions/12870/what-type-of-batteries-are-used-in-smart-wristband)

> can generate there own power though momentum no need for swapping batteries or connecting to a power grid to recharge

So the only case where it discharges will be when dropped on ground and left alone for months? Well, I don't see the appeal in simulating that, may be someone else will pick it up

**Comment by flybye3o6** [comment]
> So the only case where it discharges will be when dropped on ground and left alone for months? Well, I don't see the appeal in simulating that, may be someone else will pick it up

only case where it discharges is when Activated, technically all batteries should discharge over time but if its not simulated anywhere else i dont see why it needs be be here

>Those devices seem to have about [~1.5kJ of power in them at the higher end] (our battery "unit" is 1kJ)
same thing can be said about most devices that use the smallest batteries already ingame, 50kj battery irl is about 750g
irl button batteries are 2.5kj and thats a 2cm one double the size of the ultra-light battery ingame
