### ISSUE TITLE
[Magiclysm] Mage Blade/Armor don't seem to scale

### ISSUE THREAD

**Issue by rty275** [CleverRaven/Cataclysm-DDA#64526]
### Describe the bug

Mage Blade and Armor are described to scale in power based on your intelligence and spell level. Mage blade remains at 1 cut and Mage armor always has negligible protection no matter how high they're leveled or how intelligent the character is. I tested to make sure they weren't just scaling invisibly, but attacking with the Mage Blade did not deal the amount of damage expected for the level. I also tested to make sure the spells weren't scaling off the Enhanced version's spell level, which they are not.

### Attach save file

[Lindseyville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11064751/Lindseyville-trimmed.tar.gz)

### Steps to reproduce

1. Learn Mage Blade or Mage Armor
2. Cast it
3. Check damage/protection values

### Expected behavior

I expected that the spells would scale as described. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 199ac9b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

**Comment by GuardianDll** [comment]
Duplication of #64065

**Comment by rty275** [comment]
Oop, my bad
