### ISSUE TITLE
CDDA Experimental on Android Phone crashes on launch

### ISSUE THREAD

**Issue by the-unknownperson** [CleverRaven/Cataclysm-DDA#64537]
### Describe the bug

I decided to update the game to the latest experimental build that is available on Android (Cataclysm-DDA experimental build 2023-03-23-2229), only to end up crashing after updating game data.

### Attach save file

N/A

### Steps to reproduce

Launch the game (Both 32x and 64x versions) on the android device

### Expected behavior

Expected to happen: Launch the game normally
I would expect the game to launch normally because I am using a 64x android phone

### Versions and configuration

- OS: Android 11
- Game Version: Cataclysm-DDA experimental build 2023-03-23-2229
- Graphics Version: Android 64x and 32x
- Ingame Language: System language (English)
- Mods Loaded: Magiclysm, My Sweet Cataclysm, DinoMod, Stats Through Skills, Stats Through Kills, SpeedyDex

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11067137/crash.zip)

**Comment by SurFlurer** [comment]
Clear the App's data and restart it (which will trigger the release of assets) probably will fix this for you.

**Comment by TealcOneill** [comment]
@GuardianDll Can't replicate using the latest Android download.
