### ISSUE TITLE
0.G Error Message popping out (Something about santa jacket coverage)

### ISSUE THREAD

**Issue by SilverWheatgrass** [CleverRaven/Cataclysm-DDA#64557]
### Describe the bug

I think among other things, from the log, the error also extends to several other clothing items. 
The error is caused by coverage going over 101? which shouldn't be possible?

My game was modded with built in mods (Magiclysm and Innawoods)

I am on PC using the 32x Tiles stable build think there were also linux user with exact same issue but the thread was locked 

### Attach save file

[Wilder-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11068665/Wilder-trimmed.tar.gz)

### Steps to reproduce

1. I load my save
2. Error message appears
3. I ignore it
4. I quit and load again
5. Error message appears again

### Expected behavior

I expect the message to not appear

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11068666/debug.log)

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/64504

**Comment by Night-Pryanik** [comment]
Closing as duplicate.

**Comment by anothersimulacrum** [comment]
@SilverWheatgrass If you're willing, could you provide some more details about your OS (version)?

**Comment by SilverWheatgrass** [comment]
> @SilverWheatgrass If you're willing, could you provide some more details about your OS (version)?

I'm using Windows 10, update 21H2 (or whichever version is the latest since the issue remains persist for me)

**Comment by anothersimulacrum** [comment]
Are you using msvc or mingw? If so, could you try the other build?

So you are aware, we have dropped 32 bit Windows support for 0.H.

**Comment by SilverWheatgrass** [comment]
> Are you using msvc or mingw? If so, could you try the other build?
> 
> So you are aware, we have dropped 32 bit Windows support for 0.H.

Fyi, sorry that it took quite long to get back. 
Most of the issue immediately disappeared when I ran the save on 64 bit dda.

**Comment by anothersimulacrum** [comment]
Oh, if you can use 64 bit you should always use 64 bit.
