### ISSUE TITLE
[Magiclysm] Magical auras destroyed by fire

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#64555]
### Describe the bug

Various magical auras, like Aura of Protection and Force Shield, can catch on fire and be destroyed. This is nonsensical, as these items represent intangible force fields and other magical effects that it shouldn't be possible to destroy through mundane damage. It also creates some gameplay problems, like Demon Spiders, an already very dangerous enemy, being able to instantly negate your most potent defenses.

This seems to affect items that are made of "magical material", but not ones made of "concentrated mana". Mage Armor isn't destroyed by fire, for example.

### Attach save file

trivially reproducible

### Steps to reproduce

1. Debug raise your strength to a couple hundred so you don't instantly die
2. Cast Aura of Protection and/or Force Shield
3. Spawn a demon spider
4. Wait for it to cast Burning Hands

### Expected behavior

Magical auras don't catch on fire and burn like mundane items.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/227710215-8c3177ad-8796-4bb1-948e-ed954aaa38ae.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 4ad1388 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

I tried fixing this by adding the "unbreakable" flag, but apparently that doesn't protect the item from burning, so I don't know how to fix this.

**Comment by GuardianDll** [comment]
Probable fix: go to https://github.com/CleverRaven/Cataclysm-DDA/blob/66012021564e005fef9aaff3cdc713428abec3fd/data/mods/Magiclysm/materials.json#L194 and put `"burn_data": [ ]` to overwrite the cotton's inherited burn data

**Comment by Terrorforge** [comment]
Nope, doesn't work. So far, the only fix I've found is giving the material a high fire_resist. But then if the garment has any amount of environmental protection, it also grants the player substantial fire resistance, so something liek Aura of Protection wouldn't really work.

**Comment by Maleclypse** [comment]
So `"burn_data": [ { "immune": true }, { "immune": true }, { "immune": true } ]` makes you immune to fire all over?

**Comment by Terrorforge** [comment]
No, altering the burn data has no effect whatsoever. It doesn't seem to be burning, it seems to be getting destroyed by the direct fire damage.

What makes you immune to fire is setting fire_resist to some high value. It does work as expected (player takes fire damage, but garment is unharmed) if the garment has 0 environmental resist. But if it has env. resist greater than zero, at least a portion of the fire resistance is applied to the player. Elemental resists (fire, acid) seem to be entirely decoupled from material thickness as well, so this happens even if the garment is 0 thickness and otherwise provides no protection whatsoever.

**Comment by Maleclypse** [comment]
"burn_data": [ { "immune": true }, { "immune": true }, { "immune": true } ] is broken then, because in the source code that line is supposed to make the item immune to burning up as shown in your screencap.

**Comment by RenechCDDA** [comment]
> "burn_data": [ { "immune": true }, { "immune": true }, { "immune": true } ] is broken then

Just so you know, I'm working on documenting burn_data right now and can confirm that immune is working as intended for dropped items at the very least.

![image](https://user-images.githubusercontent.com/84619419/235442354-2b4809c7-34c6-4067-9451-39322f57242e.png)

I had to drop tinder on the tile before it recognized there was anything to burn, and even after letting it burn for 30 minutes it's still not been touched.
