### ISSUE TITLE
Triggered bear traps can be set up again, yet still remain attached to your leg.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#64587]
### Describe the bug

Got caught in a bear trap.  Wielded it.  Set the trap in an adjacent space.  But I still couldn't move because my leg was still caught in it.

### Attach save file

N/A

### Steps to reproduce

1. make player.
2. Spawn a bear trap.
3. Get caught in trap (attempt to disarm was my method)
4. Try to move (can't).
5. Wield bear trap.
6. Try to move - still caught in trap.
7. Apply bear trap, set it in adjacent space.
8. Try to move - still caught in bear trap!

### Expected behavior

Either should not be able to manipulate bear trap except to try pry it open, or resetting the trap somewhere else, which necessarily opens the trap, should release you.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-869-g02634b3799 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by jakeberko** [comment]
I was checking out this bug and, during my attempt at replicating it, I noticed that when you try to disarm the trap you also get stuck in the trap. Was this intentional in the design of the bear trap?

**Comment by jakeberko** [comment]
I was checking out this bug and, during my attempt at replicating it, I noticed that when you try to disarm the trap you also get stuck in the trap. Was this intentional in the design of the bear trap?

**Comment by random-cdda-modder** [comment]
still present in 2023-06-04-0530 experimental.

In my opinion while there could be different results from triggering vs disarm-failing traps, it'd be just for this trap(or very few), and other traps would still simply trigger the normal effect.

**Comment by gvlasov** [comment]
I had the same problem, it ruined my character, does anyone have a workaround to get loose? The save file:
[Fulda-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12296363/Fulda-trimmed.tar.gz)

I'm on 0.G

**Comment by gvlasov** [comment]
Found the way: 
- bind Debug meny key
- press it
- "Player..."
- "Edit player/NPC"
- Select yourself
- "Add effect"
- find "beartrap"
- Enter
- set duration 0
- Enter
- I can move again!
