### ISSUE TITLE
Ammo disappears when attempting to reload a magazine

### ISSUE THREAD

**Issue by ephemeralstoryteller** [CleverRaven/Cataclysm-DDA#64588]
### Describe the bug

More specifically: 
When opening the reload menu to reload a magazine with ammo that is not in the inventory, a portion of that ammo disappears. 

The ammo disappears not only when opening the menu, but also closing it.

This does not occur to ammo that is inside the inventory.

### Attach save file

[i am debug-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11071008/i.am.debug-trimmed.tar.gz)

Contains a debug character surrounded by two piles of 9mm ammo, carrying an empty magazine and a Glock 19.

### Steps to reproduce

1. Spawn empty magazine and compatible ammo on the floor.
2. Open the reload menu and then close out of it again. 
3. Look at the total ammo, it should be depleted.
4. Reopen the menu, see that the ammo total has gone down.
5. Put some ammo in inventory. 
6. Open reload menu and close it again, reopening to see that the ammo in the inventory remains constant.

### Expected behavior

Not paying an ammo tax.

### Screenshots

Before:
Spawned in 100 rounds.
![before](https://user-images.githubusercontent.com/11377530/227762059-1e320555-a4d1-4b5d-b408-7b3de1a2b3a8.png)

**Not pictured: ammo total when opening the menu was 70 rounds instead of original 100.**

After opening and closing menu:
![after](https://user-images.githubusercontent.com/11377530/227762058-38320f8c-d1c2-442a-a961-e889c174c69b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1696 (21H2)
- Game Version: d98a4cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Likely related to #64552.

**Comment by Wyghab** [comment]
This is what happened to me when picking up the ammo, while reloading from ground caused crashes instead.

**Comment by ephemeralstoryteller** [comment]
Unfortunately unresolved by #https://github.com/CleverRaven/Cataclysm-DDA/pull/64564.

**Additional testing**: 

Seems related to stacks of ammunition, specifically. If any given stack of ammo on the ground could fill the magazine with no remainder, no ammo is lost from that stack when reloading. However, if _any_ stack nearby has more ammo than could fit in the magazine, it loses ammo.

I seem to have figured out the rough formula for amount of ammo lost: when the magazine is totally dry, it's equal to the amount the maximum capacity of the magazine x2. So, a 15 round magazine would subtract, from every stack of nearby ammo available that has more rounds than could fill the magazine without having a remainder, 30 rounds. 

If you cancel out of the reload menu, it additionally subtracts another magazine's worth of rounds from the nearby pool.

Tested with both a 15 round magazine and a 30 round magazine with 200 rounds of nearby ammunition split into two stacks on the floor.

**Comment by Prime141** [comment]
Can confirm unresolved by #64564, most likely related to #64543

**Comment by AcidAntOnAMinefield** [comment]
Can confirm this is still happening:

Trying to reload a 0/250 8x40 magazine costs 500 ammo for example, but it seems consistent with all other ammo.
