### ISSUE TITLE
Dirt roads and other terrain turning into abandoned drive-throughs at scale

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#64592]
### Describe the bug

Overland map tiles keep turning into abandoned drive-throughs . At first it was just one or two forest paths, but now almost every dirt road in a large farm has done it.

When terrain has already been visited, the drive-through shows on the overland map, but doesn't change the already generated terrain. For example, the yard outside my old base turned into a drive-through on the overland map, with no ill effects to the yard remaining a yard when visited on the zoomed-in map.

However if the terrain hasn't been visited before, it will generate actual drive-throughs, one after another. (See screenshot below)

It looks like any sort of terrain can flip, but roads and paths seem most common. Whenever a tile flips, it's *always* to a drive-through. No other weird terrain transformations have been seen.

### Attach save file

[NoHope-2023-03-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11071650/NoHope-2023-03-trimmed.tar.gz)

### Steps to reproduce

I wish I knew how to reproduce this! It seems to happen at random. However you can load the attached file to see an example of a shattered reality, with lines of drive-throughs intersecting still corn fields, fading away into the distance.

### Expected behavior

Not everything slowly becomes an abandoned drive-through.

### Screenshots

These were dirt roads in the farm before they transformed:

![no-roads-only-drive-through](https://user-images.githubusercontent.com/12072/227777635-f608ea64-9c6c-4554-aed7-5d3255fd7c96.png)

![farm-of-movies](https://user-images.githubusercontent.com/12072/227777678-80479314-74f5-4921-af13-ec99fd5bd29c.png)

### Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-934-g5a1e67f196 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Hope [no_hope]
]
```

Version is d6d06eb1146d46c8eb4e1f9f74f215f80f211380 (`cdda-experimental-2023-03-26-0619`) with some local patches applied, none of which have anything to do with mapgen.

### Additional context

While only a hunch, I suspect this may be related to the weird behaviour we've seen in #64588, #64552, and other issues that suggest we've got a stray pointer or other memory weirdness going on.

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/64564 should fix it once clang-tidy unclogs the CI

**Comment by pjf** [comment]
@irwiss : Gosh dang you're awesome. Thank you! ♥

**Comment by irwiss** [comment]
I actually caused the ruckus in the first place so not that awesome, sorry :)

Migrations after that PR won't silently swallow any random mistakes though, so mass teleportation of fastfood storefronts should stop, hopefully

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/can-my-map-be-fixed/20676/9
