### ISSUE TITLE
Compilation failed on Windows with MSVC and vcpkg - sdl2-mixer dependency is not being installed

### ISSUE THREAD

**Issue by Bbansjkl** [CleverRaven/Cataclysm-DDA#64619]
### Describe the bug

I tried to follow the [compilation guide on for MSVC and vcpkg on Windows](https://github.com/CleverRaven/Cataclysm-DDA/blob/0.G/doc/COMPILING/COMPILING-VS-VCPKG.md) and am getting an error on the step where I build for the first time:

```
Erstellen gestartet...
[...]

2>------ Erstellen gestartet: Projekt: Cataclysm-lib-vcpkg-static, Konfiguration: Release x64 ------
2>Installing vcpkg dependencies to C:\Projekte\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\
2>"C:\Projekte\vcpkg\vcpkg.exe" install "--host-triplet=x64-windows-static" --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\Projekte\vcpkg\\" "--x-manifest-root=C:\Projekte\Cataclysm-DDA\msvc-full-features\\" "--x-install-root=C:\Projekte\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\\" --clean-after-build
2>Warnung: Das Einbetten von "vcpkg-configuration" in eine Manifestdatei ist ein EXPERIMENTELLEs Feature.
2>Fehler: sdl2-mixer:x64-windows-static@2.6.3#1 verf├╝gt nicht ├╝ber das erforderliche Feature libvorbis
2>C:\Projekte\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: Der Befehl ""C:\Projekte\vcpkg\vcpkg.exe" install "--host-triplet=x64-windows-static" --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\Projekte\vcpkg\\" "--x-manifest-root=C:\Projekte\Cataclysm-DDA\msvc-full-features\\" "--x-install-root=C:\Projekte\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\\" --clean-after-build" wurde mit dem Code 1 beendet.
2>Die Erstellung des Projekts "Cataclysm-lib-vcpkg-static.vcxproj" ist abgeschlossen -- FEHLER.

[...]
```

English translation of the error would be something like "Error: sdl2-mixer:x64-windows-static@2.6.3#1 does not contain/support the required feature libvorbis"

I followed the previous steps in the guide to the letter and already tried to reinstall vcpkg, and to check out this repo once more. Didn't fix it.  

Not sure if the compilation guide is missing something or if I made an error anywhere, as this would be my first time working with vcpkg.

### Attach save file

N/A

### Steps to reproduce

1. clean install of vcpkg
2. clean clone of this repo
3. attempt to build the project

### Expected behavior

Compilation should succeed after following the compilation guide's steps.

### Versions and configuration

Windows version: Windows 10 21H2  
Visual Studio version: 2019, 16.11.25

**Comment by PatrikLundell** [comment]
Yes, it would definitely be useful to have instructions on how to update vcpkg in the compilation guide (as well as information that it may need to be updated if a newer version of CDDA won't compile).

**Comment by PatrikLundell** [comment]
The thing is that things break down from time to time because CDDA shifts to a newer vcpkg version. Fistly, it's not clear why things suddenly don't work, and secondly, the instructions for installation of vcpkg are not useful for updating it (unless you remove vcpkg completely first, I guess).
