### ISSUE TITLE
Failure to write options.json file when the game is launched. 

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#64611]
### Describe the bug

The game fails to load, unable to read the options file:

![image](https://user-images.githubusercontent.com/5290912/227811971-683fb011-6f57-41a7-9f16-5967ce423808.png)

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

No errors loading the options file

### Versions and configuration

- Windows 10
- At commit 97c2e25e1ee49b4dc8e321541ffbad566e007990
- The instalation location is, D:\Users\username\Documents\Github\CataclysmDDA\ it all worked properly before rebasing against the current master commit above.

**Comment by kevingranade** [comment]
Looks like the path seperators are messed up.
The path to the temporary file is created here
https://github.com/CleverRaven/Cataclysm-DDA/blob/adb641d20405150feb49288c575cd22274c6daaa/src/mapsharing.cpp#L120

**Comment by akrieger** [comment]
What's failing is the rename() in ::close. The behavior of rename() is implementation defined if the destination already exists. My hunch is the msys crt throws an error but msvcrt just clobbers the original.

**Comment by akrieger** [comment]
@John-Candlebury I can't reproduce the issue. Can you check the permissions on the original config/options.json? Is it readonly for some reason? Or owned exclusively by Administrator or something like that?

**Comment by John-Candlebury** [comment]
Thanks for taking the time to check this. It doesnt seem like it is: 
![image](https://user-images.githubusercontent.com/5290912/229293432-2a07a7a2-0688-4281-b0d1-f6d977a89ef3.png)

**Comment by akrieger** [comment]
I can't think what might've changed recently to affect this except the move to c++17.

Does your Windows username have any non-ascii characters in it by chance?

**Comment by John-Candlebury** [comment]
Its al letters, I dont know what to say tbh. I rebased to master again, tried to compile with Msys2 to the same error, recompiled again with Visual Studio and the game ran properly. 

Found out that so long as the game was compiled from Visual studio I can then execute it from the Msys terminal too, although I'm unsure whether this means anything.

Could it be that Msys needs some extra configuration due to the change and the compiling docs need updating? I set it up two years ago afterall

**Comment by akrieger** [comment]
When's the last time you updated your msys install? `pacman -Syyuu` twice? I can add some extra logging here to try to catch the exception at least in case that doesn't resolve it.

**Comment by John-Candlebury** [comment]
Updating fixed the issue, thanks for suggesting it I wouldn't have thought of it otherwise.

Sorry it was a trivial matter

**Comment by akrieger** [comment]
Not trivial at all! I'm glad the solution ended up being easy but this was quite weird and I've learned of a new edge case. Kinda similar to how only the Linux to windows cross build would fail to parse json floats, but only on Windows 7 with a non-US English system locale set (independent of the game language).
