### ISSUE TITLE
Allow Cody to craft faraday chainmail suit

### ISSUE THREAD

**Issue by Kamejeir** [CleverRaven/Cataclysm-DDA#64617]
### Is your feature request related to a problem? Please describe.

I want to delegate all my intellectual capacity to learn how to smash zombie better, so paying someone else to the specialty work required for a specifically shockproof item is desired. Cody herself says she's part of the Society for Creative Anachronism, and stocks all different parts necessary to make the item, but as the most logical source for the item, she can't. But it's fine, I understand, for she does not have electronics skill. Though there's no other possible source than my own hands, so I wrote this issue.

### Solution you would like.

Here's a laid-out plan for what I intend to add, but was directed from Discord to here when wishing to discuss it. I just wanna know if there's any oddities or flawed premises in this "go ask another person" quest, as well as if the self-prototyping process makes sense.

- The Tacoma Scavenger Boss can provide a quest where someone spotted a particularly valuable piece of loot in a power station that's unnaturally electrically hazardous (I would say shockers, but the individual scavenger would probably throw a molotov), so they need to return and liberate it even at the cost of making a faraday suit (which they conveniently got to hear that it exists from one of the carpenters, flipping through a DIY Compendium that was scavenged). 

  They do this as there's not a disposable alternative, and enclosing suits are too warm and encumbering, as well as being too voluminous to lug around when not in use.
	

- The Scavenger Boss asks you to find someone who is skilled enough to make the item, directing you to the blacksmith that they heard about from caravans, when they were back at the Refugee Center.
	

- You visit Cody and after completing her quest to make up with Jay, tell her about your woes. She tells you that she would love to help, but isn't proficient enough in electronics to figure it out by herself, suggesting to find someone who can.

	
  That "someone who can" being Jenny Forcette in the Refugee Center, a suitably skilled engineer for coming up with how to wire up a chainmail suit. (There doesn't seem to be anyone better than her in electronics in the game from what I found.)

  She tells you she would need a chainmail suit to try making a prototype, so you go get literally anything, plus some merch to make it worth her while. You can ask Cody for a suit, or a LARP replica would also suffice.

  After some time, Jenny provides you with a blueprint. You bring it to Cody and then you're done. The blacksmith will now make you faraday chainmail suit (and I'm confident she will be able to, as she doesn't have trouble with the nomad thingamajig, saying it's very detailed with the instruction).
	
In an alternate universe where you for example made enemies with the Refugee Center or for whatever reason can't find them, you can ask Cody directly and use a suit to prototype into a blueprint yourself.

The requirements assuming the following conditions:

1.  You have near-maxed electronics
2.  The Electroshock Weapons proficiency 
3.  Either the DIY Compendium, Advanced Electronics or Electronic Circuit Theory book (those all providing the recipe for faraday chainmail suit) 
4. You've used her services prior to see the connection and/or have confidence her handiwork is suitable for your ideas.

The self-prototyping going something like this:

- After asking her about it, it spawns a special item with an unlearnable recipe on it, requiring the above. Completing this sends an EoC (with help of what PR 63691 added) that enables some dialogue with Cody and deletes the special item (if possible), that then grants the ability for her to craft faraday chainmail suit.

**Comment by bombasticSlacks** [comment]
This seems fine to me and an interesting addition.
