### ISSUE TITLE
Crash to desktop with no error logs or crash logs when creating a new item with same ID as game but different type

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#64613]
### Describe the bug

I have been working on updating and fixing my mods for 0.G, and I've encountered a crash to desktop that does not result in any error messages. Here is the debug log:

`
-----------------------------------------
17:56:03.366 : Starting log.
17:56:03.366 INFO : Cataclysm DDA version 0bba914
17:56:03.367 INFO : [main] C locale set to English_Canada.utf8
17:56:03.367 INFO : [main] C++ locale set to 
17:56:03.367 INFO : SDL version used during compile is 2.26.4
17:56:03.367 INFO : SDL version used during linking and in runtime is 2.26.4
17:56:03.423 INFO : Number of render drivers on your system: 6
17:56:03.423 INFO : Render driver: 0/direct3d
17:56:03.423 INFO : Render driver: 1/direct3d11
17:56:03.423 INFO : Render driver: 2/direct3d12
17:56:03.423 INFO : Render driver: 3/opengl
17:56:03.423 INFO : Render driver: 4/opengles2
17:56:03.423 INFO : Render driver: 5/software
17:56:03.426 INFO : [options] C locale set to English_Canada.utf8
17:56:03.426 INFO : [options] C++ locale set to 
17:56:03.426 INFO : Setting language to: 'en'
17:56:03.426 INFO : [i18n] Scanning core translations from lang/mo/
17:56:03.426 INFO : [i18n] Scanning mod translations from ./mods/
17:56:03.426 WARNING : opendir [./mods/] failed with "The system cannot find the path specified.".
17:56:03.573 INFO : Active renderer: 1/direct3d11
17:56:03.835 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
17:56:03.847 INFO : Setting language to: 'en'
17:56:03.925 WARNING : opendir [./mods] failed with "The system cannot find the path specified.".
17:56:09.800 INFO : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:68: Tried check if 'vampire_cathedral' had a duplicate, but type 'class overmap_special' does not track object sources
`

It happens before character generation, and seems to hit when the Items portion of the game loading is happening. I cannot get to the save menu, or far enough to enable debug menu.

### Attach save file

N/A

### Steps to reproduce

1. Create a world with Nymall's Foodlab and Nymall's Tools enabled.
2. Attempt to create a character

### Expected behavior

- It to work and allow through with errors if any exist
- The game to kick back to the world selection with an error
- A error log or crash log to be generated

### Versions and configuration

(this is pulled from a working version without the mod Nymalls Tools enabled - cannot generate report if foodlab is enabled)

20:44:32.207 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 0bba914 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Nymall's Tools [nymalltools]
]

**Comment by Nymall** [comment]
[Nymalls_Foodlab.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11074393/Nymalls_Foodlab.zip)
[Nymalls_Tools.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11074394/Nymalls_Tools.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11074395/debug.log)

**Comment by NetSysFire** [comment]
I assume it works fine without your mod, right? Just to make sure it is not a general issue.

Are you familiar with gdb? It can be used to obtain a trace which is very helpful when debugging such crashes. Unfortunately I can not do that for you because I ran out of RAM when loading the debugging symbols.

**Comment by Nymall** [comment]
Yes, this crash happens just with the mods loaded.

After some extensive brute force testing using the pattented delete key, I've narrowed the issue down to this line of JSON:

`
  {
    "id": "mace",
    "copy-from": "spice",
    "type": "COMESTIBLE",
    "name": { "str_sp": "mace" },
    "description": "The outer hull of the nutmeg, mace has a warmer and more citriusy taste, great for deserts.",
    "color": "yellow"
  }
`

I suspect that ID:Mace may already be used somewhere else in the code - the strange part is, this part of the code is old, and previously it worked without crashes on 0.F

**Comment by NetSysFire** [comment]
I can confirm this with your example item. Nice catch. Putting it in gdb I see the following (without symbols):

```
Thread 1 "cataclysm-tiles" received signal SIGFPE, Arithmetic exception.
0x0000555555f9927a in Item_factory::finalize_pre(itype&) ()

Thread 1 (Thread 0x7ffff6fceb80 (LWP 105412) "cataclysm-tiles"):
#0  0x0000555555f9927a in Item_factory::finalize_pre(itype&) ()
No symbol table info available.
#1  0x0000555555f9c3f2 in Item_factory::finalize() ()
No symbol table info available.
#2  0x0000555555f11d34 in DynamicDataLoader::finalize_loaded_data(loading_ui&) ()
No symbol table info available.
#3  0x0000555555e564e8 in game::load_world_modfiles(loading_ui&) ()
No symbol table info available.
#4  0x0000555555e56671 in game::setup() ()
No symbol table info available.
#5  0x00005555560a129f in main_menu::new_character_tab() ()
No symbol table info available.
#6  0x00005555560a3229 in main_menu::opening_screen() ()
No symbol table info available.
#7  0x00005555557d6759 in main ()
No symbol table info available.
```
