### ISSUE TITLE
Crash when killing zombie

### ISSUE THREAD

**Issue by Fumbling-Charade** [CleverRaven/Cataclysm-DDA#64642]
### Describe the bug

Killing a zombie causes a crash to desktop.

### Attach save file

[Woodchopper-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11087541/Woodchopper-trimmed.tar.gz)

### Steps to reproduce

Head to the fire lookout tower to the right and kill a zombie.

### Expected behavior

Not crash.

### Versions and configuration

- OS: Windows 7
- Game Version: 6d311a7
- Graphics version: Tiles (Ultica)
- Ingame language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions, extra_mut_scens, translate_dialogue

### Additional context

[Save file.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11087479/Save.file.zip)
[Crash and debug logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11087480/Crash.and.debug.logs.zip)

**Comment by SurFlurer** [comment]
Duplicate of #64466.

**Comment by Fumbling-Charade** [comment]
No longer happening since setting "Popup window when achievement completed" to Never.
