### ISSUE TITLE
Trailer parks, mines, nursing homes and dump sites are missing the MAN_MADE FLAG

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#64657]
### Describe the bug

It is possible to find overmap structures that should not be available with Innawoods.

### Attach save file

[Inna-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11095597/Inna-trimmed.tar.gz)

### Steps to reproduce

1. Generate a world with primarily Innawoods (no other major conversions)
2. Find structures that shouldn't exist in Innawoods, such as dumpsites and trailer parks

### Expected behavior

No civilization

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Innawood [innawood],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

0.G stable

**Comment by NetSysFire** [comment]
Can confirm. Also mines. Ping @Light-Wave. Those are all mutables.

**Comment by NetSysFire** [comment]
Okay nevermind, it is only an issue with city size != 0, but still an issue.

**Comment by LovamKicsiGazsii** [comment]
I reckon it's caused by missing `MAN_MADE` flags. Nothing to do with them being mutables.

**Comment by NetSysFire** [comment]
They should have the MAN_MADE flag for this regardless, but this is an easy thing to fix. I just confirmed that they are indeed missing the flag.
