### ISSUE TITLE
Mi-Go tower atmosphere is fatally hot to player but not to mi-go NPC prisoners

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#64666]
### Describe the bug

The gas fields that are produced by mi-go furniture are fatally hot to human characters. This goes against the intended design of mi-go towers having living prisoners. The only reason that the NPC prisoner characters inside these placed don't die is that NPCs ignore overheating. A player character standing in the same spot as an NPC will die from heat.

See https://github.com/CleverRaven/Cataclysm-DDA/pull/35618 for attempt to make the atmosphere not lethal.

### Attach save file

N/A

### Steps to reproduce

1. Stand naked inside mi-go tower just like prisoner NPCs
2. Die from heat induced damage to all limbs

### Expected behavior

Not dying from heat like prisoners, alternatively no prisoners though that would be a boring solution.
Having better prisoner storage.

### Versions and configuration

Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
The fields are adding to ambient temp rather than replacing it which is part of the problem. They *appear* to have been balanced around the dead of winter at which point they're oppressive but not as immediately fatal.

**Comment by nornagon** [comment]
Just confirming that I've observed this too. Either the NPCs inside should be dead, or the heat should be reduced. As is, it's basically impossible to rescue the prisoners. (Maybe the [climate control CBM](https://cdda-guide.nornagon.net/item/bio_climate) would do it? But e.g. a vehicle cooler mounted to a wheelchair doesn't. And explosives don't penetrate the outer walls.)

**Comment by nornagon** [comment]
This is still an issue.

**Comment by nornagon** [comment]
Still an issue

**Comment by nornagon** [comment]
bump
