### ISSUE TITLE
Quality of Life Improvement Menu Looting/Dropping/Eating

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#64665]
### Is your feature request related to a problem? Please describe.

With the Current  Version Food iss sorted Differently in the Eat Menu it shows all the Stuff and is sorted by categories - but not by the Place were the Food is. 
I prefer to eat from specific places first but to do that i have to switch between the different views.
(you can switch between hierarchy and categories i think)

Problem iss that this affects the Inventory where categories are great and the Long list you get with the other view can be confusing.
 

### Solution you would like.

Would it be possible to seperate both Menus from each other in regards to that setting? Because currently i have to switch every time if i go eating or looting and its quite annyoing.

### Describe alternatives you have considered.

Dont do anything ... i mean its just a quality of Life change if thats possible

**Comment by kwesting4** [comment]
I always find myself wishing I could sort between calories or quench.
