### ISSUE TITLE
Crash on bandit combat

### ISSUE THREAD

**Issue by BuildusMaximus** [CleverRaven/Cataclysm-DDA#64677]
### Describe the bug

 Upon a couple rounds of tab combat with bandits when there is more than one option for tab to hit, crash to desktop.  Duplicated 5 times.

Killed bandits successfully with ranged and non tab combat, even if they are adjacent. 3x passed.

### Attach save file

[Sheogorath-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11104695/Sheogorath-trimmed.tar.gz)

### Steps to reproduce

Enter cabin
Manuever so you can reach two bandits at once
Tab attack (may take 2-3 swings)

### Expected behavior

Game crashes

### Versions and configuration

21:31:13.825 INFO : Cataclysm DDA version 62d958d
21:31:13.825 INFO : [main] C locale set to English_United States.utf8
21:31:13.825 INFO : [main] C++ locale set to 
21:31:13.825 INFO : SDL version used during compile is 2.26.4
21:31:13.825 INFO : SDL version used during linking and in runtime is 2.26.4
21:31:13.862 INFO : Number of render drivers on your system: 6
21:31:13.862 INFO : Render driver: 0/direct3d
21:31:13.862 INFO : Render driver: 1/direct3d11
21:31:13.862 INFO : Render driver: 2/direct3d12
21:31:13.862 INFO : Render driver: 3/opengl
21:31:13.862 INFO : Render driver: 4/opengles2
21:31:13.862 INFO : Render driver: 5/software
21:31:13.867 INFO : [options] C locale set to English_United States.utf8
21:31:13.867 INFO : [options] C++ locale set to 
21:31:13.867 INFO : Setting language to: 'en'
21:31:13.867 INFO : [i18n] Scanning core translations from lang/mo/
21:31:13.867 INFO : [i18n] Scanning mod translations from C:\Users\barbe\Documents\cdda/mods/
21:31:13.867 WARNING : opendir [C:/Users/barbe/Documents/cdda/mods/] failed with "The system cannot find the path specified.".
21:31:14.368 INFO : Active renderer: 1/direct3d11
21:31:14.744 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
21:31:14.885 INFO : Setting language to: 'en'
21:31:14.961 WARNING : opendir [C:/Users/barbe/Documents/cdda/mods] failed with "The system cannot find the path specified.".
21:31:19.485 WARNING : opendir [C:/Users/barbe/Documents/cdda/save/Sheogorath/mods] failed with "The system cannot find the path specified.".
21:31:20.078 INFO : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:68: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'class overmap_special' does not track object sources
21:31:25.015 INFO : Loaded tileset: UltimateCataclysm
21:31:25.124 ERROR SDL : (error message will follow backtrace)

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11104724/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11104725/crash.log)

**Comment by nemesis688** [comment]
I think I am getting the same crash with zombies and it isn't exclusive to using "Tab" to attack; also happened when I used "f". If I kill a zombie who is adjacent to another zombie the game crashes.

Game Version: 65407fa [64-bit]

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11105094/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11105113/debug.log)

**Comment by Qrox** [comment]
@nemesis688 Your crash is probably the same one as #64466 judging from the crash log.

**Comment by nemesis688** [comment]
@Qrox You are correct. Using the work around stopped it. Weird coincidence for what kill was triggering the level up always seeming to be when enemies died adjacent. Looking more closely at the log (and thinking achievements) I think I see where it indicated it was the achievement bug.

**Comment by BuildusMaximus** [comment]
I had achievements disabled in my game, if you mean it's the achievement crash bug causing it.
