### ISSUE TITLE
[Magiclysm?] Ammo loaded into items cannot be used as spell components

### ISSUE THREAD

**Issue by AGrinningCat** [CleverRaven/Cataclysm-DDA#64671]
### Describe the bug

Items loaded into another item (tinder into ember carrier) do not count towards spell components.

### Attach save file

N/A

### Steps to reproduce

1. Start a game with magiclysm
2. Spawn in, then spawn in an ember carrier (comes with 50 tinder), 50 tinder
3. Teach yourself the flamebreath spell, which requires 100 tinder
4. Cannot cast flamebreath, despite having 100 tinder.

### Expected behavior

Items inside containers count towards spell components if you have them.

### Versions and configuration

CDDA experimental build 2023-03-28-1741

**Comment by RenechCDDA** [comment]
I believe this was resolved with #64706
