### ISSUE TITLE
A mod that purely does the restoration of old stuffs from DDA?

### ISSUE THREAD

**Issue by sonphantrung** [CleverRaven/Cataclysm-DDA#64675]
### Is your feature request related to a problem? Please describe.

IIRC from my memories of Discord, Reddit, discussion threads, the devs said that including a mod that re-add old stuffs that were removed is possible if someone is ready to work with it

### Solution you would like.

If it's OK to include these kinds of mods, I have some sort of ideas, like restoring CBM dissection, re-add removed CBMs, chicken walkers, etc.

### Describe alternatives you have considered.

Don't ever think about those types of mods.

**Comment by kevingranade** [comment]
A mod that does nothing but restore old functionality is not something we would support. Mods need to have a coherent goal so people can work together maintaining it,  and provide a distinct experience for players.

This is documented at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/IN_REPO_MODS.md#what-is-necessary-for-a-mod-to-be-included-in-the-repository

**Comment by Raikiri** [comment]
I thought chicken walkers, makeshift laser rifles, railguns and CBM dissection were both moved to aftershock.
