### ISSUE TITLE
[feature request] Army helmet should have flashlight attachments.

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64672]
### Is your feature request related to a problem? Please describe.

army helmets should have flashlight attachments.

**Comment by anoobindisguise** [comment]
Wear a headlamp?

**Comment by Devengel** [comment]
i want less things to see in my inventory. headlamp works but i'd rather attach it to a army helmet

**Comment by Daved27hundred** [comment]
Why use tape? modern army helmets as well as certain others should have flashlight mounts on them. We have helmet attachments now as far as I can tell

**Comment by Devengel** [comment]
because i didn't know. 😁
