### ISSUE TITLE
Can't enter the portal storm dungeon

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#64673]
### Describe the bug

When i step into the portal storm dungeon's swirling vortex, it does not take me there.

### Attach save file

[Presto-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11101242/Presto-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save
2. enter the vortex
3. no portal storm dungeon

### Expected behavior

being able to enter the portal storm dungeon

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 6d311a7 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No scent tracking zombies [no_scent_tracking_zombies],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

**Comment by andrei8l** [comment]
/confirmed bisecting lead to https://github.com/CleverRaven/Cataclysm-DDA/commit/b411b72968b950119a0c3f285cdd6a5d13df0ddf  and I haven't investigated further
