### ISSUE TITLE
Charcoal Disappears When Filling Smoker

### ISSUE THREAD

**Issue by MaddMugsy** [CleverRaven/Cataclysm-DDA#64688]
### Describe the bug

Stack of charcoal disappears if larger than the capacity of the smoker.

Possibly related to [64588](https://github.com/CleverRaven/Cataclysm-DDA/issues/64588)?

### Attach save file

N/A

### Steps to reproduce

1. Build a charcoal smoker
2. Spawn in a stack of 96k charcoal
3. Go to reload smoker - it will autofill 90000 as the max value
4. Fill with any value - I used 12k (single load of meat)
5. Smoker contains specified value, the rest of the stack has vanished

### Expected behavior

Remaining charcoal continues to exist.

### Versions and configuration

- OS: Win 10 x64
- Version: 2023-03-30-0117
- Language: English

**Comment by SurFlurer** [comment]
Has this been fixed by #64634 ?
