### ISSUE TITLE
'Night Vision' trait preventing related mutations

### ISSUE THREAD

**Issue by NotDucc** [CleverRaven/Cataclysm-DDA#64680]
### Describe the bug

Starting with the Night Vision trait seems to prevent any vision-related mutations aside from direct upgrades (high + full nightvision), including but not limited to: Reptilian IR, Cephalopod Vision, Fey Vision, Ursine Vision, and Infrared Vision. 

While traits currently are designed to prevent negative traits from becoming positive or positive traits to negative, I have a feeling they aren't supposed to prevent mutations that can exist alongside it with no issues.

### Attach save file

N/A

### Steps to reproduce

1. Make a character with 'Night Vision' trait.
2. Attempt to debug mutate the character with 'Infrared Vision' or any mutation previously mentioned in the report.
3. Player gains the 'Full Night Vision' mutation, but not the desired 'Infrared Vision' mutation.

### Expected behavior

I expect to be able to get mutations related to either seeing in the dark or having IR vision regardless of whether or not they could see well in the dark already.

### Versions and configuration

- OS: Windows 10
- Game Version: 0.G Stable
- Graphics Version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/25201 - characters cannot have mutation of the same type.

**Comment by NotDucc** [comment]
Oop, guess you're right on that, it does normally remove night vision (except in the case of Infrared, though it turns out I was being dumb and forgot that's a post-threshold mutation, so that is still obtainable) and I was thinking of an older version before that was merged. 

Still, most of these are flat upgrades to Night Vision yet they're barred from the player if chosen as a trait, which seems slightly counter-intuitive to me with the system in place. However, if that part was done intentionally, then all is good with it.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/63974
