### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Devinil** [CleverRaven/Cataclysm-DDA#64693]
### Describe the bug

The game ramdonly (maybe while autosaving) crashing multiple times.

### Attach save file

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11111904/crash.log)

### Steps to reproduce

Just walk a few mins and wait for the game to autosave maybe.

### Expected behavior

Error screen and crashing

### Versions and configuration

[VERSION.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/11111921/VERSION.txt)

**Comment by BrettDong** [comment]
Duplicate of #64466
