### ISSUE TITLE
(65407fa) (Boiled) Makeshift Bandage crafting not creating batches properly.

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#64707]
### Describe the bug

(Prob an issue from Innawoods as well.)

Crafting Makeshift Bandages with the 3x unit or 1x batch with (Fibercloth) Sheets vs Patches isn't working properly.

Patch AND Sheet recipe crafts 1x instead of 1x/8x as prior therefore player must cut up Sheet > Patches to get proper recipe returns.

### Attach save file

[InnaMega Techworld-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11116587/InnaMega.Techworld-trimmed.tar.gz)

### Steps to reproduce

- Craft 2x Fibercloth Sheet. 
- Disassemble 1x into 8x Patches.
- Craft Makeshift Bandage using Patch and Sheet recipe.
- Both recipes result in 1x Bandage only.

### Expected behavior

Not.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 65407fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Innawood [innawood],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Megafauna [megafauna],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    DinoMod [DinoMod]
]

**Comment by RenechCDDA** [comment]
/confirmed although I'm not fully sure I understand the issue.

The fibercloth sheet--->makeshift bandage recipe in innawoods should make 8 bandages, it makes one.

https://github.com/CleverRaven/Cataclysm-DDA/blob/bd3116f0c20459b3dabee0b4a28794e831e2bf55/data/mods/innawood/recipes/medsandchemicals.json#L253

Happens even in a fresh world with only innawoods loaded.

**Comment by RenechCDDA** [comment]
Oh, it looks like this was just a simple find&replace error. For recipes, `charges` was supposed to be replaced with `result_mult` but for the innawoods recipes* they got `count` instead.

*For... just that specific file, somehow, because the other innawoods recipe got `result_mult`!

**Comment by evankimori** [comment]
Thanks for the quick response, much appreciated. :)
