### ISSUE TITLE
"Armorsmithing" and "Quenching & Tempering" proficiencies not learning

### ISSUE THREAD

**Issue by sacredsky** [CleverRaven/Cataclysm-DDA#64709]
### Describe the bug

Crafting both "tempered steel close helm" and "tempered steel sabaton". The only lacking Proficiencies is "Armorsmithing", and "Quenching & Tempering". But can not see it from the Proficiencies screen after I crafted for a while. 

### Attach save file

[德卢斯-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11116601/-trimmed.tar.gz)

### Steps to reproduce

1. Craft a "tempered steel close helm" or"tempered steel sabaton" or other similar recipes.
2. No "Armorsmithing" and "Quenching & Tempering" showing in Proficiencies screen

### Expected behavior

"Armorsmithing" and "Quenching & Tempering" showing in Proficiencies screen, should be learning

### Screenshots

![image](https://user-images.githubusercontent.com/9583737/228978322-98cd9391-20dc-4b9a-bacb-d10b8939d79b.png)
![image](https://user-images.githubusercontent.com/9583737/228978338-02903107-d428-4051-909d-ed65b77b36a1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions]
]

**Comment by actually-a-cat** [comment]
How much is "a while"? Proficiency XP is granted at 5% craft progress intervals (i.e. at 5% progress, then 10%, then 15, and so on), which on a 1 week craft means it's normal to not get any proficiency progress until over 8 hours of crafting in.

**Comment by sacredsky** [comment]
> How much is "a while"? Proficiency XP is granted at 5% craft progress intervals (i.e. at 5% progress, then 10%, then 15, and so on), which on a 1 week craft means it's normal to not get any proficiency progress until over 8 hours of crafting in.

Oh, I never know that. I thought it was a similar XP system for skill. Because my skill level up, but not seeing proficiency. Both crafted recipes are 3%. So that's the issue. Thanks.
