### ISSUE TITLE
segfault crash upon picking up items

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#64719]
### Describe the bug

Sometimes when picking up items the game will print a "tried to add duplicate entry" error screen and then segfault. It used to do that error screen and not segfault which was obviously undesirable but now it is completely untenable.

### Attach save file

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: f3e9c4e
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: debug_write_backtrace+0xb5@0,000,7FF,75C,D64,AD5[cataclysm-tiles.exe+0x5b4,ad5]), 
  #1
    (dbghelp: log_crash+0x372@0,000,7FF,75C,D28,A32[cataclysm-tiles.exe+0x578,a32]), 
  #2
    (dbghelp: signal_handler+0x57@0,000,7FF,75C,D28,E87[cataclysm-tiles.exe+0x578,e87]), 
  #3
    (dbghelp: seh_filter_exe+0x178@0,000,7FF,75E,181,950[cataclysm-tiles.exe+0x1,9d1,950]), 
  #4
    (dbghelp: `__scrt_common_main_seh'::`1'::filt$0+0x16@0,000,7FF,75E,3AD,1F2[cataclysm-tiles.exe+0x1,bfd,1f2]), 
  #5
    (dbghelp: _C_specific_handler+0xa0@0,000,7FF,75E,152,6A4[cataclysm-tiles.exe+0x1,9a2,6a4]), 
  #6
    (dbghelp: _chkstk+0x11f@0,000,7FF,B5E,F32,41F[ntdll.dll+0xa2,41f]), 
  #7
    (dbghelp: RtlRaiseException+0x434@0,000,7FF,B5E,EE1,4A4[ntdll.dll+0x51,4a4]), 
  #8
    (dbghelp: KiUserExceptionDispatcher+0x2e@0,000,7FF,B5E,F30,F4E[ntdll.dll+0xa0,f4e]), 
  #9
    (dbghelp: inventory_entry::make_entry_cell_cache+0x2d@0,000,7FF,75C,DC3,6BD[cataclysm-tiles.exe+0x613,6bd]), 
  #10
    (dbghelp: selection_column::on_change+0x8e@0,000,7FF,75C,DC4,63E[cataclysm-tiles.exe+0x614,63e]), 
  #11
    (dbghelp: inventory_selector::on_change+0x3d@0,000,7FF,75C,DC4,47D[cataclysm-tiles.exe+0x614,47d]), 
  #12
    (dbghelp: inventory_multiselector::toggle_entries+0x389@0,000,7FF,75C,DCD,F39[cataclysm-tiles.exe+0x61d,f39]), 
  #13
    (dbghelp: inventory_multiselector::on_input+0x1bd@0,000,7FF,75C,DC4,B1D[cataclysm-tiles.exe+0x614,b1d]), 
  #14
    (dbghelp: pickup_selector::execute+0x6c3@0,000,7FF,75C,DBC,0E3[cataclysm-tiles.exe+0x60c,0e3]), 
  #15
    (dbghelp: game_menus::inv::pickup+0x613@0,000,7FF,75D,83C,923[cataclysm-tiles.exe+0x1,08c,923]), 
  #16
    (dbghelp: game::pickup+0x2df@0,000,7FF,75C,E49,2DF[cataclysm-tiles.exe+0x699,2df]), 
  #17
    (dbghelp: game::do_regular_action+0x1,1a4@0,000,7FF,75D,337,C44[cataclysm-tiles.exe+0xb87,c44]), 
  #18
    (dbghelp: game::handle_action+0x944@0,000,7FF,75D,341,0B4[cataclysm-tiles.exe+0xb91,0b4]), 
  #19
    (dbghelp: do_turn+0xe90@0,000,7FF,75C,D6D,080[cataclysm-tiles.exe+0x5bd,080]), 
  #20
    (dbghelp: WinMain+0xae7@0,000,7FF,75C,BF6,1E7[cataclysm-tiles.exe+0x446,1e7]), 
  #21
    (dbghelp: __scrt_common_main_seh+0x106@0,000,7FF,75E,14F,2E2[cataclysm-tiles.exe+0x1,99f,2e2]), 
  #22
    (dbghelp: BaseThreadInitThunk+0x14@0,000,7FF,B5E,CE7,614[KERNEL32.DLL+0x17,614]), 
  #23
    (dbghelp: RtlUserThreadStart+0x21@0,000,7FF,B5E,EE2,6A1[ntdll.dll+0x52,6a1]), 

### Steps to reproduce

I don't know how to consistently reproduce the error that leads to the crash but I can confirm whenever it happens it causes a crash. It happens most frequently when looting zombie corpses.

### Expected behavior

there shouldn't be an error and there definitely shouldn't be a crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: f3e9c4e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by andrei8l** [comment]
Good thing there was a crash log or otherwise this bug report would have been unsolvable
