### ISSUE TITLE
Military sniper spawns with an magazine for wrong gun.

### ISSUE THREAD

**Issue by Wyghab** [CleverRaven/Cataclysm-DDA#64728]
### Describe the bug

The military sniper profession starts with an M14 magazine for their spare ammo for their M24 rifle. The ammo can be used, but the magazine is incompatible.

### Attach save file

N/A

### Steps to reproduce

1. Start with Military Sniper as profession ( or check in chargen ).
2. Check starting gear for your spare ammo.

### Expected behavior

I expect the ammo to come in a compatible magazine, in this case a box or speedloader would be more fitting than the magazine of a different gun.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 31e2f3c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Tamable Wildlife [Tamable_Wildlife],
    Bombastic Perks [bombastic_perks]
]

**Comment by random-cdda-modder** [comment]
military sniper starts with M24 gun and M14 mags: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/professions.json#L4710

m24 expects mags with size 5: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/gun/308.json#L329

m14 mags are size 20 instead: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/magazine/308.json#L123

probably m14smallmag should be provided instead?

**Comment by Quintovir** [comment]
https://en.wikipedia.org/wiki/M24_Sniper_Weapon_System

5-round internal magazine (M24)
5-round detachable box magazine (M24A2, M24A3)

If the M24 variant in the game uses an internal magazine, then the Military Sniper start shouldn't give you an M14 magazine.
