### ISSUE TITLE
[Magiclysm] Shocking Lash Max level = 0

### ISSUE THREAD

**Issue by ProfessorBright** [CleverRaven/Cataclysm-DDA#64738]
### Describe the bug

When learning Shocking Lash from Applied Meteorology book or Scroll the max level of the spell is 0 and it doesn't do anything when cast.

### Attach save file

[Callery-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11125683/Callery-trimmed.tar.gz)

### Steps to reproduce

1. Create character
2. spawn in Shocking Lash Scroll
3. Read to learn the spell
4. Open spellcasting menu and try to cast Shocking Lash

### Expected behavior

Spell should have max level of 20, have stats, and damage targets when cast.

### Versions and configuration

CDDA Experimental Build 2023-03-31-1431

**Comment by GuardianDll** [comment]
\confirmed
![image](https://user-images.githubusercontent.com/67688115/229241390-bbcd7d8c-dd75-45e5-ad08-f27789e42025.png)
i believe the spell inheritance was broken recently, maybe after #64416 
<details>
  <summary>(tho when i tried to learn a spell, i got segfault, duh)</summary>
 The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: a33c958
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x7ff700167010[cataclysm-tiles.exe+0x237010]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x140237010),
    0x140237010    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/char_traits.h:1121    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff70014f933[cataclysm-tiles.exe+0x21f933]), 
    (libbacktrace: log_crash+0x1de@0x14021f933),
    0x14021f933    src/crash.cpp:918    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x14021f933    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:85    log_crash
  #2
    (dbghelp: @0x7ff70014fb5b[cataclysm-tiles.exe+0x21fb5b]), 
    (libbacktrace: signal_handler+0x52@0x14021fb5b),
    0x14021fb5b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:137    signal_handler
  #3
    (dbghelp: raise+0x21b@0x7ff84fa3adfb[msvcrt.dll+0x2adfb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #4
    (dbghelp: abort+0x1b@0x7ff84fa3f1fb[msvcrt.dll+0x2f1fb]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: @0x7ff6fff3441c[cataclysm-tiles.exe+0x441c]), 
    (libbacktrace: achievements_tracker::report_achievement(achievement const*, achievement_completion)+0xa8@0x14000441c),
    0x14000441c    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:1648    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(string_id<achievement> const&)
    0x14000441c    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:1640    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find(string_id<achievement> const&)
    0x14000441c    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:869    std::unordered_map<string_id<achievement>, achievement_tracker, std::hash<string_id<achievement> >, std::equal_to<string_id<achievement> >, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> > >::find(string_id<achievement> const&)
    0x14000441c    src/string_formatter.h:792    achievements_tracker::report_achievement(achievement const*, achievement_completion)
  #6
    (dbghelp: @0x7ff6fff34ced[cataclysm-tiles.exe+0x4ced]), 
    (libbacktrace: achievement_tracker::set_requirement(requirement_watcher*, bool)+0x2d5@0x140004ced),
    0x140004ced    src/string_formatter.h:686    achievement_tracker::set_requirement(requirement_watcher*, bool)
  #7
    (dbghelp: @0x7ff7008b158b[cataclysm-tiles.exe+0x98158b]), 
    (libbacktrace: stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)+0x91@0x14098158b),
    0x14098158b    src/stats_tracker.cpp:161    void watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&>(void (stat_watcher::*)(cata_variant const&, stats_tracker&), cata_variant const&, stats_tracker&) const
    0x14098158b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:322    stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)
  #8
    (dbghelp: @0x7ff7008b1820[cataclysm-tiles.exe+0x981820]), 
    (libbacktrace: stats_tracker::transformed_set_changed(string_id<event_transformation> const&, event_multiset const&)+0x50@0x140981820),
    0x140981820    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, event_multiset const&, stats_tracker&, event_multiset const&, stats_tracker&>(void (event_multiset_watcher::*)(event_multiset const&, stats_tracker&), event_multiset const&, stats_tracker&) const
    0x140981820    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:313    stats_tracker::transformed_set_changed(string_id<event_transformation> const&, event_multiset const&)
  #9
    (dbghelp: @0x7ff7008b158b[cataclysm-tiles.exe+0x98158b]), 
    (libbacktrace: stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)+0x91@0x14098158b),
    0x14098158b    src/stats_tracker.cpp:161    void watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&>(void (stat_watcher::*)(cata_variant const&, stats_tracker&), cata_variant const&, stats_tracker&) const
    0x14098158b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:322    stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)
  #10
    (dbghelp: @0x7ff70107ee53[cataclysm-tiles.exe+0x114ee53]), 
    (libbacktrace: void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const+0x63@0x14114ee53),
    0x14114ee53    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const
  #11
    (dbghelp: @0x7ff7008b1f76[cataclysm-tiles.exe+0x981f76]), 
    (libbacktrace: stats_tracker::notify(cata::event const&)+0x90@0x140981f76),
    0x140981f76    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:370    stats_tracker::notify(cata::event const&)
  #12
    (dbghelp: @0x7ff7001e6d32[cataclysm-tiles.exe+0x2b6d32]), 
    (libbacktrace: event_bus::send(cata::event const&) const+0x26@0x1402b6d32),
    0x1402b6d32    src/event_bus.cpp:1108    __gnu_cxx::__normal_iterator<event_subscriber* const*, std::vector<event_subscriber*, std::allocator<event_subscriber*> > >::operator++()
    0x1402b6d32    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:58    event_bus::send(cata::event const&) const
  #13
    (dbghelp: @0x7ff700856b27[cataclysm-tiles.exe+0x926b27]), 
    (libbacktrace: stats_tracker::deserialize(JsonObject const&)+0xb1f@0x140926b27),
    0x140926b27    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_function.h:312    ~map
    0x140926b27    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_function.h:312    std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cata_variant, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cata_variant> > >::~map()
    0x140926b27    src/monster.h:791    ~event
    0x140926b27    src/monster.h:791    cata::event::~event()
    0x140926b27    src/item.h:4703    stats_tracker::deserialize(JsonObject const&)
  #14
    (dbghelp: @0x7ff700784ae0[cataclysm-tiles.exe+0x854ae0]), 
    (libbacktrace: past_game_info::past_game_info(JsonObject const&)+0x3ca@0x140854ae0),
    0x140854ae0    src/third-party/flatbuffers/base.h:317    decltype ((({parm#1}.deserialize)(*this)),(true)) JsonValue::read<stats_tracker>(stats_tracker&, bool) const
    0x140854ae0    src/third-party/flatbuffers/base.h:1143    bool JsonObject::read<stats_tracker>(char const*, stats_tracker&, bool) const
    0x140854ae0    src/past_games_info.cpp:41    past_game_info::past_game_info(JsonObject const&)
  #15
    (dbghelp: @0x7ff701242bbb[cataclysm-tiles.exe+0x1312bbb]), 
    (libbacktrace: void std::vector<past_game_info, std::allocator<past_game_info> >::_M_realloc_insert<JsonObject>(__gnu_cxx::__normal_iterator<past_game_info*, std::vector<past_game_info, std::allocator<past_game_info> > >, JsonObject&&)+0xab@0x141312bbb),
    0x141312bbb    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_vector.h:175    void std::__new_allocator<past_game_info>::construct<past_game_info, JsonObject>(past_game_info*, JsonObject&&)
    0x141312bbb    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/process.h:516    void std::allocator_traits<std::allocator<past_game_info> >::construct<past_game_info, JsonObject>(std::allocator<past_game_info>&, past_game_info*, JsonObject&&)
    0x141312bbb    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_uninitialized.h:462    void std::vector<past_game_info, std::allocator<past_game_info> >::_M_realloc_insert<JsonObject>(__gnu_cxx::__normal_iterator<past_game_info*, std::vector<past_game_info, std::allocator<past_game_info> > >, JsonObject&&)
  #16
    (dbghelp: @0x7ff700785919[cataclysm-tiles.exe+0x855919]), 
    (libbacktrace: past_games_info::ensure_loaded()+0x5b3@0x140855919),
    0x140855919    src/past_games_info.cpp:145    past_games_info::ensure_loaded()
  #17
    (dbghelp: @0x7ff700785c81[cataclysm-tiles.exe+0x855c81]), 
    (libbacktrace: get_past_games()+0x14@0x140855c81),
    0x140855c81    src/past_games_info.cpp:179    get_past_games()
  #18
    (dbghelp: @0x7ff700279b90[cataclysm-tiles.exe+0x349b90]), 
    (libbacktrace: achievement_attained(achievement const*, bool)+0x12d@0x140349b90),
    0x140349b90    src/cata_utility.h:361    achievement_attained
  #19
    (dbghelp: @0x7ff701159427[cataclysm-tiles.exe+0x1229427]), 
    (libbacktrace: std::function<void (achievement const*, bool)>::operator()(achievement const*, bool) const+0x27@0x141229427),
    0x141229427    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_function.h:591    std::function<void (achievement const*, bool)>::operator()(achievement const*, bool) const
  #20
    (dbghelp: @0x7ff6fff34592[cataclysm-tiles.exe+0x4592]), 
    (libbacktrace: achievements_tracker::report_achievement(achievement const*, achievement_completion)+0x21e@0x140004592),
    0x140004592    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:794    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index(std::__detail::_Hash_node_value<std::pair<string_id<achievement> const, achievement_tracker>, false> const&) const
    0x140004592    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:2298    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase(std::__detail::_Node_const_iterator<std::pair<string_id<achievement> const, achievement_tracker>, false, false>)
    0x140004592    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/alloc_traits.h:969    std::_Hashtable<string_id<achievement>, std::pair<string_id<achievement> const, achievement_tracker>, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> >, std::__detail::_Select1st, std::equal_to<string_id<achievement> >, std::hash<string_id<achievement> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase(std::__detail::_Node_iterator<std::pair<string_id<achievement> const, achievement_tracker>, false, false>)
    0x140004592    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:746    std::unordered_map<string_id<achievement>, achievement_tracker, std::hash<string_id<achievement> >, std::equal_to<string_id<achievement> >, std::allocator<std::pair<string_id<achievement> const, achievement_tracker> > >::erase(std::__detail::_Node_iterator<std::pair<string_id<achievement> const, achievement_tracker>, false, false>)
    0x140004592    src/string_formatter.h:806    achievements_tracker::report_achievement(achievement const*, achievement_completion)
  #21
    (dbghelp: @0x7ff6fff34ced[cataclysm-tiles.exe+0x4ced]), 
    (libbacktrace: achievement_tracker::set_requirement(requirement_watcher*, bool)+0x2d5@0x140004ced),
    0x140004ced    src/string_formatter.h:686    achievement_tracker::set_requirement(requirement_watcher*, bool)
  #22
    (dbghelp: @0x7ff7008b158b[cataclysm-tiles.exe+0x98158b]), 
    (libbacktrace: stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)+0x91@0x14098158b),
    0x14098158b    src/stats_tracker.cpp:161    void watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&>(void (stat_watcher::*)(cata_variant const&, stats_tracker&), cata_variant const&, stats_tracker&) const
    0x14098158b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:322    stats_tracker::stat_value_changed(string_id<event_statistic> const&, cata_variant const&)
  #23
    (dbghelp: @0x7ff70107ee53[cataclysm-tiles.exe+0x114ee53]), 
    (libbacktrace: void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const+0x63@0x14114ee53),
    0x14114ee53    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const
  #24
    (dbghelp: @0x7ff7008b17ca[cataclysm-tiles.exe+0x9817ca]), 
    (libbacktrace: stats_tracker::transformed_set_changed(string_id<event_transformation> const&, cata::event const&)+0x4a@0x1409817ca),
    0x1409817ca    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:304    stats_tracker::transformed_set_changed(string_id<event_transformation> const&, cata::event const&)
  #25
    (dbghelp: @0x7ff700f37c0a[cataclysm-tiles.exe+0x1007c0a]), 
    (libbacktrace: event_transformation_impl::state::event_added(cata::event const&, stats_tracker&)+0x8a@0x141007c0a),
    0x141007c0a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:312    ~map
    0x141007c0a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_algobase.h:312    std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cata_variant, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cata_variant> > >::~map()
    0x141007c0a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/predefined_ops.h:791    ~event
    0x141007c0a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/predefined_ops.h:791    cata::event::~event()
    0x141007c0a    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_tree.h:589    event_transformation_impl::state::event_added(cata::event const&, stats_tracker&)
  #26
    (dbghelp: @0x7ff70107ee53[cataclysm-tiles.exe+0x114ee53]), 
    (libbacktrace: void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const+0x63@0x14114ee53),
    0x14114ee53    src/stats_tracker.cpp:161    void watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&>(void (event_multiset_watcher::*)(cata::event const&, stats_tracker&), cata::event const&, stats_tracker&) const
  #27
    (dbghelp: @0x7ff7008b1f76[cataclysm-tiles.exe+0x981f76]), 
    (libbacktrace: stats_tracker::notify(cata::event const&)+0x90@0x140981f76),
    0x140981f76    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:370    stats_tracker::notify(cata::event const&)
  #28
    (dbghelp: @0x7ff7001e6d32[cataclysm-tiles.exe+0x2b6d32]), 
    (libbacktrace: event_bus::send(cata::event const&) const+0x26@0x1402b6d32),
    0x1402b6d32    src/event_bus.cpp:1108    __gnu_cxx::__normal_iterator<event_subscriber* const*, std::vector<event_subscriber*, std::allocator<event_subscriber*> > >::operator++()
    0x1402b6d32    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/charconv.h:58    event_bus::send(cata::event const&) const
  #29
    (dbghelp: @0x7ff7004948c7[cataclysm-tiles.exe+0x5648c7]), 
    (libbacktrace: void event_bus::send<(event_type)21, character_id, string_id<spell_type> const&>(character_id&&, string_id<spell_type> const&) const [clone .isra.0]+0x14b@0x1405648c7),
    0x1405648c7    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/predefined_ops.h:312    ~map
    0x1405648c7    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/predefined_ops.h:312    std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cata_variant, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cata_variant> > >::~map()
    0x1405648c7    src/event_bus.h:791    ~event
    0x1405648c7    src/event_bus.h:791    cata::event::~event()
    0x1405648c7    src/omdata.h:25    void event_bus::send<(event_type)21, character_id, string_id<spell_type> const&>(character_id&&, string_id<spell_type> const&) const
  #30
    (dbghelp: @0x7ff70049524d[cataclysm-tiles.exe+0x56524d]), 
    (libbacktrace: known_magic::learn_spell(spell_type const*, Character&, bool)+0x7bd@0x14056524d),
    0x14056524d    src/generic_factory.h:1803    operator()<char [16]>
    0x14056524d    src/generic_factory.h:1803    known_magic::learn_spell(spell_type const*, Character&, bool)
  #31
    (dbghelp: @0x7ff700495b95[cataclysm-tiles.exe+0x565b95]), 
    (libbacktrace: known_magic::on_mutation_gain(string_id<mutation_branch> const&, Character&)+0x45@0x140565b95),
    0x140565b95    src/generic_factory.h:2433    known_magic::on_mutation_gain(string_id<mutation_branch> const&, Character&)
  #32
    (dbghelp: @0x7ff700083f90[cataclysm-tiles.exe+0x153f90]), 
    (libbacktrace: Character::on_mutation_gain(string_id<mutation_branch> const&)+0x2a@0x140153f90),
    0x140153f90    src/character.h:9028    Character::on_mutation_gain(string_id<mutation_branch> const&)
  #33
    (dbghelp: @0x7ff70065b1e3[cataclysm-tiles.exe+0x72b1e3]), 
    (libbacktrace: Character::mutation_effect(string_id<mutation_branch> const&, bool)+0x265@0x14072b1e3),
    0x14072b1e3    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/std_function.h:539    Character::mutation_effect(string_id<mutation_branch> const&, bool)
  #34
    (dbghelp: @0x7ff70065b3e4[cataclysm-tiles.exe+0x72b3e4]), 
    (libbacktrace: Character::set_mutation(string_id<mutation_branch> const&, mutation_variant const*)+0xe@0x14072b3e4),
    0x14072b3e4    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/std_function.h:222    Character::set_mutation(string_id<mutation_branch> const&, mutation_variant const*)
  #35
    (dbghelp: @0x7ff700495053[cataclysm-tiles.exe+0x565053]), 
    (libbacktrace: known_magic::learn_spell(spell_type const*, Character&, bool)+0x5c3@0x140565053),
    0x140565053    src/generic_factory.h:1793    known_magic::learn_spell(spell_type const*, Character&, bool)
  #36
    (dbghelp: @0x7ff700495413[cataclysm-tiles.exe+0x565413]), 
    (libbacktrace: known_magic::learn_spell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Character&, bool)+0x33@0x140565413),
    0x140565413    src/generic_factory.h:1747    known_magic::learn_spell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Character&, bool)
  #37
    (dbghelp: @0x7ff6fff732ef[cataclysm-tiles.exe+0x432ef]), 
    (libbacktrace: activity_handlers::study_spell_finish(player_activity*, Character*)+0x190@0x1400432ef),
    0x1400432ef    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/tuple:3677    activity_handlers::study_spell_finish(player_activity*, Character*)
  #38
    (dbghelp: @0x7ff7011593c7[cataclysm-tiles.exe+0x12293c7]), 
    (libbacktrace: std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const+0x27@0x1412293c7),
    0x1412293c7    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/stdio.h:591    std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const
  #39
    (dbghelp: @0x7ff6fff93dd4[cataclysm-tiles.exe+0x63dd4]), 
    (libbacktrace: activity_type::call_finish(player_activity*, Character*) const+0x3e@0x140063dd4),
    0x140063dd4    src/activity_type.cpp:120    activity_type::call_finish(player_activity*, Character*) const
  #40
    (dbghelp: @0x7ff700793060[cataclysm-tiles.exe+0x863060]), 
    (libbacktrace: player_activity::do_turn(Character&)+0x778@0x140863060),
    0x140863060    src/string_formatter.h:374    player_activity::do_turn(Character&)
  #41
    (dbghelp: @0x7ff7001b7429[cataclysm-tiles.exe+0x287429]), 
    (libbacktrace: do_turn()+0x3dc@0x140287429),
    0x140287429    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/std_function.h:496    do_turn()
  #42
    (dbghelp: @0x7ff70156fe01[cataclysm-tiles.exe+0x163fe01]), 
    (libbacktrace: main+0x1f90@0x14163fe01),
    0x14163fe01    src/main.cpp:815    main
  #43
    (dbghelp: @0x7ff6fff313ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: _tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #44
    (dbghelp: @0x7ff6fff314c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #45
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff8503c7614[KERNEL32.DLL+0x17614]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #46
    (dbghelp: RtlUserThreadStart+0x21@0x7ff8505826a1[ntdll.dll+0x526a1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

</details>
