### ISSUE TITLE
Remove suffocate ability from mass of zombies

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#64731]
### Is your feature request related to a problem? Please describe.

Suffocation by zombie group is imbalanced. Trained person (all skills up to 10 points) will die in 1 minute because of magicaly lack of air in the fight, nevermind what armor is he using (I tested it with full set of hub 01 soldier armor and heavy survivor mask, gloves and boots surraunded by 8 simple zombies) and its fully unrealistic

1) In reality to suffocate a human you need to squeeze his throat with both of your hands, or using unstruments like pillows/ropes, or, if you come behind the victim - you can suffocate him with bend of the elbow and help with free hand to not let the victim free, and also in most cases you must be stronger than the victim. 
But for this you need to understand, that lack of air can kill your opponent. Zombies are unintellegent, aggressive, clumsy, not smart, they dont know about physiology and strategy, they will bite, grab, scratch, but will not try to suffocate a person. Even if there is few zombies around you, you are in move, and you can take a few breaths, because zombies fingers are not dexterous and  enough to fully close mouth of trained person or keep throat squeezed for more than 1 minute

2) Your throat can be easyly be protected from suffocating, there is a lot of ways, most of which can be used in modern armor (football/sport/army neck protectors) I think, hub 01 armor can protect you from this too. Mediveal helms and armor are also often protect your neck

3) Trained and healthy person can live without air for more than 1 minute. After 1-2 minutes the average person loses consciousness. And also death from lack of air is coming after 5+ minutes . Its very unrealistic, that lack of air is physically hurting your torso. Stamina draining may be better than this

4) Default and lots of zombies are weaker, than a human. You can be nude and unskillful and kill 1 by 1 even the one or more tough zombie (with strength equal to 8, what is simular to average person). So you are powerfull enough to fight and get a lot of chances to breathe even when surrounded by lot of powerfull zombies

5) If you want to make fighting versus lots of zombies dangerous - you already made it bu grab upgrade, because now you cant break the grab from few zombies and also very slowed by them

### Solution you would like.

Suffocating technique can be moved to few speacial monsters (and removed from others), some of potential suffocators: vine beast, zombie vrestler, zombie master, skeletal master, zombie bio-operator, and may be few more monsters, which can make such technique by learned skills before zombofication (wreslers/masters) or anatomical features (vine beast or, may be, octopus like monters)
Zombie grabbers are dangerous enough for now because of grab upgrade, and its default zombie only with more powerfull arms (so there is no speacial skills and abilityes, exept grapping, because there is no reason, that human will train only hands and suffocating skills before zombification), simular to tough zombies, its just atletic mans, muscules don't mean skil

### Describe alternatives you have considered.

Leave all as it is unrealistic

**Comment by ZhilkinSerg** [comment]
It is not like zeds are strangling your characters. They are causing compressive asphyxia.

**Comment by KHeket** [comment]
> It is not like zeds are strangling your characters. They are causing compressive asphyxia.

But for compressive asphyxia your chest must be squeezed by powerfull force (maybe by zombie ambals or hulks) but not by default zombies. And your chest also can be protected by armor, medieval, as example, or football armor

And dont close my issue until there will not be good dicussion. I typed it for 30+ minutes and with lot of proofs of my opinions, and you just closed it by small sentence. it's very disrespectful

**Comment by andrei8l** [comment]
> But for compressive asphyxia your chest must be squeezed by powerfull force (maybe by zombie ambals or hulks) but not by default zombies. And your chest also can be protected by armor, medieval, as example, or football armor

People die in crowd crushes from regular humans who aren't actively trying to murder them. You can start reading [here](https://en.wikipedia.org/wiki/Crowd_collapses_and_crushes)  (Wikipedia link). There's a link at the bottom with a very long list of known crowd crushes. The premise of this issue is wrong so there's not much to discuss.

**Comment by ZhilkinSerg** [comment]
> And dont close my issue until there will not be good dicussion. I typed it for 30+ minutes and with lot of proofs of my opinions, and you just closed it by small sentence. it's very disrespectful

I've closed your issue because there is nothing to discuss - you think zeds are strangulating your characters while they are simply get crushed by the crowd.

**Comment by KHeket** [comment]
> crowd crushes from regular humans

Crowd crushes are not the same as a 8 zombies. There even getting suffocating from 2 zombies, as I tested now. So there is fully unrealistic and not sumular to compressive asphyxia and crowd crushes. If there will be 20-30 zombies around me - may be its the case, but not for my situation. Also from wiki "When a body of people reaches or exceeds the density of four to five people per square meter"
Crowd crushes become becouse of hundreds, thousands and more humans, not just by little group

> I've closed your issue because there is nothing to discuss - you think zeds are strangulating your characters while they are simply get crushed by the crowd.

There is a lot to discuss, as I mentioned above. So, please, reopen this issue

**Comment by Kamayana** [comment]
The creator of the crushing mechanic mentions a few times that the mechanic could be improved in #54227 and #63225:
> The intent was to design a system that gets around traditional armor. Additional bonuses or in the case of powered armor ignoring this seems reasonable but this would be a first step that could then be tweaked and built on.

>Yeah there are plans to make this more in-depth and simulate actual crushing. For now though I can fix oddities like this by making it so only enemies that can push doors in can suffocate you. I'm on holiday but next week can fix this.

So it's fairly clear to me that this issue shouldn't be closed as not planned because it clearly is. At the very least I think a character should be wholly protected against it if their torso and head are covered in rigid armor, since no part of their respiratory system would be getting crushed there.

**Comment by KHeket** [comment]
@bombasticSlacks can you take a look at this pr?

**Comment by bombasticSlacks** [comment]
Sure, everyone already explained to you that you don't understand what the system is trying to represent.

Though valid, your point about oxygen has nothing to do with grabs, that would be an issue about how long the character can hold their breath which would extend to other things like being underwater.

> So it's fairly clear to me that this issue shouldn't be closed as not planned because it clearly is. 

This is true, and the change to make crowd crush better is still planned, but it has nothing to do with an issue about strangulation. 

> At the very least I think a character should be wholly protected against it if their torso and head are covered in rigid armor, since no part of their respiratory system would be getting crushed there.

This really only means power armour, anything else has belts and adjusters which can be pushed in cause more pressure. If someone wants to make power armour immune to suffocation, that's *already* been mentioned as being ok.

> I'd be for rethinking the threshold of two as well, as just having two people on you doesn't seem like it should be enough to start causing asphyxiation. As KHeket points out the wiki says the IRL threshold is 4-5 people per square meter, which sounds better to me.

You already know that this is planned to be changed, why do we need to keep pinging people over this.


Since I'm here I was already planning on doing this but with the changes to base grabs (which are getting overhauled RN by the way) I wanted to wait for that to settle before doing any further work.

**Comment by Shados** [comment]
@bombasticSlacks now that the grab changes are done, are you still planning to rework this? I just had a character be 'suffocated' by three zeds, while wearing junk plate and a motorcycle helmet, which seems absurd.

I'm also having trouble envisioning how a zombie grappling onto or colliding with a belt or other fastener on rigid armour could cause an increase in pressure. If anything, it might _unfasten_ something?

Also, the linked wikipedia article on crowd crushes is not a useful source. Following the references on claims made leads either to sources that don't support what they're being referenced for, or sources that just repeat the claim without providing any research or further sources. I'm certain there's some *actual* research out there on this, but it's not to be found from that page, sadly.

**Comment by bombasticSlacks** [comment]
@Shados I am not planning on reworking this as I'm currently on hiatus from developing DDA.

> Also, the linked wikipedia article on crowd crushes is not a useful source. Following the references on claims made leads either to sources that don't support what they're being referenced for, or sources that just repeat the claim without providing any research or further sources. I'm certain there's some actual research out there on this, but it's not to be found from that page, sadly.

Nobody is using the article on crowd crushes as a source, but it does have a list of examples of it happening, which is what was said above.

> I'm also having trouble envisioning how a zombie grappling onto or colliding with a belt or other fastener on rigid armour could cause an increase in pressure. If anything, it might unfasten something?

They aren't colliding, the point is any non exo framed armour *can be tighter*, you put your junk plate on, fastening it to yourself, so a creature can apply more pressure to your torso through it.

I also want to be clear that a rework of this system would be *worse* for the player, not better, as you could also be knocked over and trampled, things which in DDA translates to *stunned* and *taking free damage*.

Please don't ping me on a closed issue and include that you just had a character die, it makes you sound salty and reactive. That plus the fact that I above-mentioned we should "stop pinging people about this" means I'm going to block you and will be locking this issue. If you would like to contribute to the game your own solution without "conflicting sources", go for it, but I will not be involved.
