### ISSUE TITLE
Steam: Adjust description a bit

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#64730]
### Is your feature request related to a problem? Please describe.

Reading the page at https://store.steampowered.com/app/2330750/Cataclysm_Dark_Days_Ahead/ leaves a question: The game is free and open source, so where does the money go?

### Solution you would like.

It would be nice if you could mention that the money is used for e.g sponsoring a specific dev (in this case, you) which will use it to dedicate some time to developing or helping with the costs of the forum. Something along the lines of "The game is free and open source, but the profit made with this version goes towards developing the game, thank you very much for financially supporting us.".

Another thing I noticed is that the mature content description is missing gore (depends on tileset, so you could write "depends on used tileset") and graphic descriptions. The latter can be found in some mutant organs when you butcher certain enemies and is definitely not for the faint of heart.

**Comment by ZhilkinSerg** [comment]
Money is coming to publisher. End of story.

**Comment by NetSysFire** [comment]
>Money is coming to publisher

Yes and that is very much not clear or documented anywhere in a public place. I am not arguing either, so I will reopen because other things in this issue havent been addressed yet.

**Comment by ZhilkinSerg** [comment]
What exactly do you want to achieve here? It is a common knowledge money from game sales is going to a publisher. It should not concern anyone where the money is going next.

**Comment by GuardianDll** [comment]
Question is "where this question should be posted"

**Comment by ZhilkinSerg** [comment]
> Question is "where this question should be posted" Steam version is effectively new fork, so it has to have some specified place to post issues (maybe steam forums (or how it is named))

Obvious answer is to use Steam forums for the said game.

**Comment by NetSysFire** [comment]
The developer is CleverRaven though, which is right here. @KorGgenT is right on here, too.

Besides, I do not think it is justified to be that hostile for an honest and good faith suggestion.

>Obvious answer is to use Steam forums for the said game.

If it should be so obvious, then I encourage you to add a new entry to our issue templates to redirect steam things to the steam forums.

**Comment by KorGgenT** [comment]
all right i'll try to address your concerns, but ZhilkinSerg is correct, steam specific things should go on the steam forums, or even the email listed in the sidebar of the steam page.

1) i've followed the template that some other games which are open source use regarding saying where the money goes. Mindustry, tales of maj'eyal
2) the gore stuff was posted within the steam mature content survey. the extra stuff at the bottom is extra stuff i added
3) i'll run it by kevin and see what he things about adding a link to the steam forums about steam bug reports.
