### ISSUE TITLE
[Android] Migration from java to kotlin for android project 

### ISSUE THREAD

**Issue by vladimirlisovskij** [CleverRaven/Cataclysm-DDA#64737]
### Is your feature request related to a problem? Please describe.

Currently, kotlin is the preferred way to develop applications for android. Therefore, switching to kotlin will make the project more attractive for new contributions and possibly make it easier to support in the future.

### Solution you would like.

Migration from java to kotlin for source code files for android project
Migration from groovy to kotlin for gradle files for android project

**Comment by vladimirlisovskij** [comment]
I can start doing it if you approve.

**Comment by ZhilkinSerg** [comment]
No. We use SDL2 glue which is in Java.

**Comment by vladimirlisovskij** [comment]
@ZhilkinSerg Kotlin will run on the JVM, so java code can be called from kotlin code and vice versa

**Comment by ZhilkinSerg** [comment]
It is not about runtime. Code is in Java here and in SDL upstream repo, if you will change it to Kotlin and then we decide to update it from upstream it would be just an unnecessary burden.

**Comment by vladimirlisovskij** [comment]
Now I understand
I'm closing the issue for the reasons described above
Thanks for your replies!
