### ISSUE TITLE
Mounting a horse, setting it to run, then dismounting it causes you to run without losing stamina

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64739]
### Describe the bug

The game changes it to "walk", but you still keep the speed. Running without losing stamina

### Attach save file

N/A

### Steps to reproduce

Mount horse
set it to run, maybe run a few tiles
dismount, see that you still have the speed of running

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 87e5215 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Devengel** [comment]
funnily enough the only way i noticed it was because the game was going extremely fast contrary to the usual.

**Comment by SurFlurer** [comment]
Funny, I cannot reproduce locally. May you provide a trimmed save file?

**Comment by Devengel** [comment]
I think i misunderstood the speed of triffids greatly. i tested it a bunch of times and it's just that the vine beasts are slow.
