### ISSUE TITLE
quartered corpse counts as a pocket (see screenshot

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64741]
### Describe the bug

title
![image](https://user-images.githubusercontent.com/71761521/229244254-5dc7fb05-e2f3-40c1-8fb3-88120d90783a.png)

### Attach save file

N/A

### Steps to reproduce

Quarter corpse, pick up stuff. maybe lots of stuff.

### Expected behavior

for it to not be a pocket

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 87e5215 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Qrox** [comment]
I mean, a carcass quarter does have a chest/abdomen cavity which _could_ be considered a pocket...
