### ISSUE TITLE
Activating Curing Porkbelly out of a fridge uses two

### ISSUE THREAD

**Issue by Rasengetsu** [CleverRaven/Cataclysm-DDA#64752]
### Describe the bug

When you activate slab of raw curing porkbelly from inside a refrigerator, two charges are used up to return a single cured product.

### Attach save file

[Yarmouth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11128524/Yarmouth-trimmed.tar.gz)

### Steps to reproduce

1. Craft multiple slab of raw curing porkbelly
2. Keep in fridge for 8 hours
3. Activate while still in fridge
4. Two charges are used

### Expected behavior

Only use one charge of porkbelly

### Screenshots

![image](https://user-images.githubusercontent.com/61328903/229269198-4dcd00da-0405-45d9-a6ec-b4b1d80a7631.png)
![image](https://user-images.githubusercontent.com/61328903/229269202-b1b5fbaf-5ab5-42f7-99f5-3c5b8b867880.png)
![image](https://user-images.githubusercontent.com/61328903/229269203-7fc2dd2f-468b-46aa-bc38-1d6b3ace322e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: a33c958 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by SurFlurer** [comment]
Has been fixed in latest experimental. Probably by #64634.
