### ISSUE TITLE
Refugee Broker only pays for one item

### ISSUE THREAD

**Issue by Rasengetsu** [CleverRaven/Cataclysm-DDA#64753]
### Describe the bug

The broker in the refugee center in charge of receiving foodstuffs in exchange for merch only pays you for a singular item despite taking the whole stack.
He correctly declares how much it is worth but then just scams you. Heh.

### Attach save file

[Yarmouth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11129267/Yarmouth-trimmed.tar.gz)

### Steps to reproduce

1. Verify currently owned merch
2. Offer food item (smoked meat)
3. Be given merch worth a single item in exchange for three items.

### Expected behavior

I expect to be paid for all my goods!

### Screenshots

![image](https://user-images.githubusercontent.com/61328903/229285363-1076d304-a123-4dfb-b5e0-d4dcf63ca3e6.png)
![image](https://user-images.githubusercontent.com/61328903/229285371-e77a9eb4-f5a3-4581-ab10-d663940efd8d.png)
![image](https://user-images.githubusercontent.com/61328903/229285383-c7ff178a-5974-4af8-872f-b574d99da92d.png)
![image](https://user-images.githubusercontent.com/61328903/229285395-d9b9886a-f14d-45c0-8cb1-82fed51caa3a.png)
![image](https://user-images.githubusercontent.com/61328903/229285410-3302bf29-035d-443f-a4f8-7a1ef2de903a.png)
![image](https://user-images.githubusercontent.com/61328903/229285418-ed15e4b5-8930-4574-b305-028c1bd3e9b1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: a33c958 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Only tested with smoked meat; unsure if applied to other items.

**Comment by Rasengetsu** [comment]
Upon further testing, it seems if I drop my meat and offer just a single one, I do not get paid. Perhaps he is banking the value until enough has been given.

**Comment by estebandellasilva** [comment]
> Upon further testing, it seems if I drop my meat and offer just a single one, I do not get paid. However, a subsequent donation is then paid. Perhaps he is banking the value in dollars until enough has been given to trade for merch and since they are worth 2.50 each, a single item is not enough to get paid while three meats is only enough for two merch.

meaning that if you give him 5 pieces you should receive 4 merch to test that theory

**Comment by Rasengetsu** [comment]
Yes, I have indeed received 4 merch from 5 smoked meat. So the issue isn't that he's not paying but rather that the interaction is weird and unclear.
