### ISSUE TITLE
Safe Place scenario issue regarding Lake Cabin and Lighthouse Island.  

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#64758]
### Describe the bug

Despite being a location available for the player to spawn in if they've chosen the Safe Place scenario, the locations of Lake Cabin and Lighthouse Island are populated with swimmer zombies and are thus, not safe. 

### Attach save file

N/A

### Steps to reproduce

1: Make a new character, and set the Scenario as Safe Place.
2: Choose either Lake Cabin or Lighthouse island as starting location
3: locate the zombies, 
4: (Optional) Show them who the boss is around here.

### Expected behavior

Since these are listed as locations in the Safe Place scenario, they are supposed to be safe.

### Versions and configuration

Using the latest experimental build.  2023-04-01-1436

**Comment by NetSysFire** [comment]
Theres two options: Remove the swimmer zombies or remove the safe place status. After looking at it ingame, an isolated lighthouse and a fairly remote cabin should not have a handful of swimmer zombies just strolling around.

**Comment by 7erracotta** [comment]
> Theres two options: Remove the swimmer zombies or remove the safe place status. After looking at it ingame, an isolated lighthouse and a fairly remote cabin should not have a handful of swimmer zombies just strolling around.

yeah, i think removing the swimmer zombies would be a good idea
