### ISSUE TITLE
NPC invited me on a quest, then stole all my stuff

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#64771]
### Describe the bug

I got the MISSION_GET_SAFE_BOX mission from my starting NPC, and once I closed the dialog, the NPC walked over to my stash of items (which was in the evac shelter) and started picking things up and eating my food.

### Attach save file

[Chanhassen-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11131117/Chanhassen-trimmed.tar.gz)

### Steps to reproduce

I haven't tried to reproduce this on a fresh character, but I'm guessing it would happen with this mission reliably?

### Expected behavior

The NPC shouldn't take my stuff without asking! And shouldn't eat when no_npc_food is loaded.

### Screenshots

![Screen Shot 2023-04-01 at 8 53 37 PM](https://user-images.githubusercontent.com/172800/229330397-a97dadb0-f1a9-4003-a075-e6d882bb3147.png)

![Screen Shot 2023-04-01 at 8 58 17 PM](https://user-images.githubusercontent.com/172800/229330505-8b9e3aa4-62cf-4f35-8c3e-9a7e47fa3f90.png)

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin wilson.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
- Game Version: 0.G-986-ga33c958e6f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by nornagon** [comment]
Found this in "NPC vars":

```
Character Name: Percy Sorenson
|;key;value;
|;was_sleeping;false;
|;sleep_health_mult;1;
|;quarter_stam_counter;0;
|;THIEF_MODE;THIEF_ASK;
```

it seems like THIEF_ASK is supposed to make the npc ask before taking stuff...?

**Comment by nornagon** [comment]
seems similar to https://github.com/CleverRaven/Cataclysm-DDA/issues/54822

**Comment by nornagon** [comment]
I couldn't find a way to clean this up using the existing options in the debug menu, so I made https://github.com/CleverRaven/Cataclysm-DDA/pull/64775.

**Comment by MochaModifier** [comment]
The eating thing is odd, I had noticed NPCs spawn as underfed or worse - and if this is true, they will devour anything and everything you ask them to hold (while also constantly stopping anywhere and everywhere to do so)

Weirder still is they never seem to gain calories, so this behavior is permanent as far as I can tell - even if you start a camp and feed them through >distribute food.

**Comment by epsimpson** [comment]
> The eating thing is odd, I had noticed NPCs spawn as underfed or worse - and if this is true, they will devour anything and everything you ask them to hold (while also constantly stopping anywhere and everywhere to do so)
> 
> Weirder still is they never seem to gain calories, so this behavior is permanent as far as I can tell - even if you start a camp and feed them through >distribute food.

I noticed this, too.  I thought they might eat if they are underfed despite no_npc_food.   I have an NPC with -24% underfed.  On a whim I gave her over 100 protein rations over a few days, keeping some in her inventory all the time.  She's very happy, but no change in weight / underfed status.  Using version 0.G-1067-ge084982901
