### ISSUE TITLE
Tactical shotshell pouch not spawning in game.

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#64782]
### Describe the bug

Tactical shotshell pouch is not included in MOLLE attachment distribution list, resulting in inability to get this pouch from drops.

### Attach save file

N/A

### Steps to reproduce

Kill monsters dropping MOLLE bags, tactical shotshell pouch never drops.

### Expected behavior

Every MOLLE attachment should have a chance to drop from MOLLE gear, including tactical shotshell pouch.

### Versions and configuration

Recent experimental.

### Additional context

During my playthrough I've observed that there are not a lot shotshell oriented attachments available. But after a bit of code digging it seems that the problem is not the lack of dedicated pouches, but in their distribution list that prevent their spawning.

**Comment by nexusmrsep** [comment]
I believe this is the relevant distribution group:
https://github.com/CleverRaven/Cataclysm-DDA/blob/379bb17874082e79b0b2dd1f3e8f45d70123a227/data/json/itemgroups/custom_lbvs.json#L14

**Comment by Ruminator24** [comment]
I think this should be tagged as a good first issue, it sounds simple enough to readd the pouch back to the list.
