### ISSUE TITLE
Security profession and trans-coast start

### ISSUE THREAD

**Issue by Kurokitsune0366** [CleverRaven/Cataclysm-DDA#64794]
### Describe the bug

The security guard profession has no training with a gun or their baton. This seems illogical as security guards should have training with both. Also, the expandable baton is not compatible with Eskima even though this martial art can be done with knives or a baton. The security lanyard does not affect automatic defenses despite claims that it does. 

### Attach save file

N/A

### Steps to reproduce

Start a game

### Expected behavior

Correct skills and behaviors 

### Versions and configuration

Windows 11 
Version 6753c7f

**Comment by Wyghab** [comment]
The baton is in fact compatible with eskrima, once you activate it to extend it. The unextended one does not have the Baton tag.

**Comment by Kurokitsune0366** [comment]
I had no idea you had to extend it. Oh that hurts me. Well fair enough but I do still think the profession should have a few skills for there job description.
