### ISSUE TITLE
Crop yields are way too good/easy

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#64807]
### Is your feature request related to a problem? Please describe.

Once you have a farm going in CDDA, you basically never have to worry about food again. What's more, all you really need is a digging stick. AFAIK the game never checks any skills, nor does it care about actual sunlight levels, soil quality, contamination, or water.

Obviously some of these are a long way off, but crop yield seems like the easiest fix, and one that will help bring some challenge back to the midgame.

Wheat and barley are the worst offenders. Google says one or two square meters should be sufficient to grow enough wheat for a loaf of bread, which the game says is about 770 calories, or 22 units of flour. Each harvested "wheat" item is 667 calories, and can be made into 15 units of flour. You get multiple per plot so you can make a lot of bread with very little land.

But why bother? You can just eat the wheat as-is. It cuts the calories down to 500, but it's instant and wheat keeps forever, while bread takes a long time to make and goes bad quickly. Furthermore, wheat is pocket-sized.

So you can instantly harvest wheat with no tools and it is a forever food that takes up no space, is as nourishing as pemmican, and is easily digestible by a normal human.

### Solution you would like.

**PLANTING:** Crops should be picky about when they're planted, especially in New England. Currently you can plant anything any time and get multiple yields of the same crop per year. 

**WHEAT AS AN ITEM:** Wheat should be changed so it can rot [edit: or not, see comments] and its portion size should be much smaller, about a handful of berries, and it should have meaningful dimensions, currently it is mega tiny despite being 600+ calories. This would allow it to reasonably be used to make seeds or single servings of soup without having to use up a whole kilo of wheat berries, and it would also allow for smaller crop yields. It should also just be straight up inedible unless processed, akin to corn or acorns, unless the survivor is a grain eating mutant (bird w/gizzard or cattle w/ruminant)

**HARVESTING:**

GRAINS
Oats, hay, wheat, barley, canola, wild rice
These plants are all tiny heads of seeds that grow on tall grassy stalks. Any tool with the grass cutting ability should be able to harvest a plot relatively quickly. It's hard work, but in the videos I've seen, sickles and scythes can clear a two meter square plot in five or ten minutes.

In the following video, Adam Ragusea, a layman, describes and shows the process of harvesting a plot of wheat only a little bigger than two square meters using a pair of garden shears instead of a grass cutting tool. He says this was painstaking and difficult work that took him half a day: https://www.youtube.com/watch?v=ee8PL7ToXcg - This suggests that harvesting should be possible with any cutting tool at a massive penalty (like, it should take thirty to sixty times longer) if a grass cutting tool is not available.

Once picked, grains are heaped up to dry. After that, they need to be threshed. This means bashing the cut stalks with a flail or something so that they release their seeds. Then, you winnow them, which you can do by leaving them out in the wind, or with an electrical fan. The dry non-seed parts are really light and they just blow right away.

LENTILS
Lentils you have to pull out of the ground by hand, they're like a really short grass with very small roots, so they come right up without tools. You have to thresh and winnow them, like grain.

BEANS AND SOYBEANS
Most varieties of bean seem to require a trellis or other support for the plant to grow, but soybeans don't. Pinto beans (a random dry bean chosen as an example) appear to yield around 2000 pounds per square acre, or 1 pound per 2 square meters. Beans are fairly simple to pick by hand.

Dry beans dry in the field, but not completely. The cut/picked plants are usually left somewhere to dry for a bit after being picked. I'm not sure this needs to be modeled as they're not being like, stuck in a food dehydrator or anything, but I'm not sure.

TRELLIS PLANTS
Grapes and hops are also grown on trellises, but are very simple to harvest. Hops are usually dried before storage.

EVERYTHING ELSE
I think everything else ought to be harvestable by hand. You could require a digging implement for potatoes, but I've seen people just get at them with their hands so it doesn't seem super necessary. Even harvesting cactus isn't really very difficult.

**YIELD:** Currently, yields feel fairly arbitrary. I think we should begin with the assumption that a plot is two meters square and apply a typical plant of that species' expected yield as a maximum, and then dramatically lower the amount if the planter does not have the requisite proficiencies. You should generally also only get one yield per year.

It may be the case that it's impossible to store planter proficiency/skill data on each crop tile. In that case, it could just check the harvester, though that's probably less than ideal in terms of simulation - for most plants, picking them isn't really a matter of skill, but knowing when, where, and how to plant can make a huge difference. I have tried to grow a fair bit of food in my life, and even in a classroom setting with an experienced botanist helping me out, I made some heartbreaking mistakes (RIP: every pumpkin i have ever tried to grow but one)

**LIFESPAN:** Crops should have a lifespan and die off when they reach the end of it. This would have the added benefit of making winter/late game towns (and farms!!) look a lot more apocalyptic, since nobody's alive to replant anything.

### Describe alternatives you have considered.

n/a

**Comment by MochaModifier** [comment]
While most of this seems agreeable - wheat berries having not shelf life isn't so outrageous.
The shelf life of what berries is pretty ridiculous so long as they're kept in favorable conditions. 
[If you're feeling peckish and adventurish, you can apparently raid a pharaos tomb, and expect to find perfectly viable wheat berries (in some tombs)](https://farmfreshwheat.com/blog/storingwheatberries)

Long term food storage could use some changes, this isn't the place for it - but aside from cool dry tombs, things like plastic buckets with mylar bags for are very common for food storage among modern day preppers. 

Keeping things like wheat berries should be entirely feasible, whether you use a modern or ancient approach. They shouldn't rot any time soon, unless we want to simulate things like humid storage conditions or how wet things get while stored.

**Comment by fairyarmadillo** [comment]
It's pretty humid in most of New England, so I think we shouldn't be assuming wheat is stored in ideal conditions unless it is. You're right that many other food items would need to be looked at in that case, too, though.

**Comment by MochaModifier** [comment]
Pretty much, unless it was noted elsewhere, I suspect most rot times for food have been based on what's posted online - and for simplicity I'd assume that those estimates presume ideal conditions.
Lot of assumptions, so if anyone knows better please feel free to fill in here

**Comment by Karol1223** [comment]
> Pretty much, unless it was noted elsewhere, I suspect most rot times for food have been based on what's posted online - and for simplicity I'd assume that those estimates presume ideal conditions. Lot of assumptions, so if anyone knows better please feel free to fill in here

These are pretty wrong assumptions. We often get people crying about how for example fruit rot way too fast - that's because for the most part the rot is supposed to take conditions of 'the item is left on the grass' into account. The weather should be taken into account but so should the effect of bacteria and the such. Most rot timers are (supposed to be) designed with this in mind.

**Comment by Zireael07** [comment]
@Karol1223 Some items do account for that, some don't. It's a mishmash depending on whether the person had access to more detailed rot times or just the "default" assumptions of having a fridge on hand

**Comment by Karol1223** [comment]
> @Karol1223 Some items do account for that, some don't. It's a mishmash depending on whether the person had access to more detailed rot times or just the "default" assumptions of having a fridge on hand

Unfortunately you're fully right on that, hence me saying they're (supposed to be) that. It's similar with caloric and vitamin contents as well as several other factors with food (fun being the most obvious one).

**Comment by Broken27** [comment]
> <strike>Once you have a farm going</strike> in CDDA, you basically never have to worry about food.

Fixed that for you.

**Comment by natsirt721** [comment]
I agree with your premise; some thoughts on your implementation details:

Wheat berries, being similar in makeup to seeds, I would expect to rot in a similar fashion to seeds. In game, seeds do not rot, so I don't think wheat berries should either. 

If you're going to introduce tool requirements for harvesting, I'd expect it to be consistent: list all the harvestable crops in the game, propose tool qualities (existing or new) that are needed to harvest them, and see where it goes from there. I would expect that the programming would be relatively simple™ - showing that you've done the legwork to compile the changes goes a long way towards making that happen.

The wheat berry item could certainly use a balance pass, mainly in caloric yield. I'm not sure I agree with your position that the berries should be inedible, but I also don't know much about that - I think a reduction in caloric yield would be sufficient. A quick google suggests that the bulk density should be around 0.77 g/cm3, whereas it currently sits at 203g / 0.25L = 0.812 g/cm3 - not too far off, really. I also wouldn't consider 0.25L to be 'mega-tiny', but you do you. FWIW, buckwheat has less than half that density, with a 180g / 0.5L = 0.36 g/cm3  - this should be reconciled unless there is a considerable physical difference between wheat and buckwheat berries that I am unaware of. Also, why is buckwheat in `raw_veggie.json` but wheat lives with all the non-bread flour-based foods in `wheat.json`? I digress.

If nothing else, changing the harvest for grain crops to drop stalks and requiring the player to thresh the stalks to retrieve the berries should absolutely be added. To be really complete, you could require winnowing as a separate step, but I would probably consider a single craft recipe for both steps - there isn't much else to do with 'beaten chaff' than winnow it. I would add two things; a crafting recipe with a bag and flail as tools for manual threshing, and a constructible mechanical threshing machine for higher volume use. I would also consider allowing the advanced harvester to perform threshing of grains, or adding a separate part to perform this step.

So three things I would have done, in order of importance:
1. Require threshing of grains crops to get grain berries
2. Balance pass on `wheat` item and related grains
3. Harvesting requirements for crops

**Comment by fairyarmadillo** [comment]
Seeds can go bad irl, the issue is that a seed in the game represents a cleaned dried seed, but we skip that step. Adding it seems like it would help turn farms into free food machines.

**Comment by fairyarmadillo** [comment]
> If you're going to introduce tool requirements for harvesting, I'd expect it to be consistent: list all the harvestable crops in the game, propose tool qualities (existing or new) that are needed to harvest them, and see where it goes from there. I would expect that the programming would be relatively simple™ - showing that you've done the legwork to compile the changes goes a long way towards making that happen.

I took your advice and edited the OP a bit to suggest which plants would need harvesting tools and further processing. Planting seasons, growth times, and yield per meter squared would also be useful to anyone who wants to poke at this, but I don't have those numbers just now.

**Comment by MochaModifier** [comment]
Also, why is buckwheat in `raw_veggie.json` but wheat lives with all the non-bread flour-based foods in `wheat.json`? I digress.

Regarding this, it's because Buckwheat is a name for several different plants, all of which aren't cereals, and are unrelated to wheat. Buckwheat is more closely related to knotweed and rhubarb; it's high starch content however lets it fill a similar culinary use as true cereals like wheat.

Speaking of buckwheat, you can eat both buckwheat and wheat berries as a porridge (which I assume is what cooked buckwheat is meant to be, given the ingredients).

Some other recommended uses I could find online included adding wheat berries to soups, salads, burritos, or simply eating them plain with salt, pepper and olive oil.

Wheat berries should very much be a food; but unlike other berries in game - wheat berries are actually seeds, and are also known as a kernel [according to the Kansas Farm Bureau ](https://www.kfb.org/WebsitePageFile/File/A4999F31-C619-4FB6-BF22-074DA6143FC1/WheatFunFactGuide.pdf)

**Comment by fairyarmadillo** [comment]
> Some other recommended uses I could find online included adding wheat berries to soups, salads, burritos, or simply eating them plain with salt, pepper and olive oil.
> 
> Wheat berries should very much be a food; but unlike other berries in game - wheat berries are actually seeds, and are also known as a kernel [according to the Kansas Farm Bureau ])
>

In all of these cases they are cooked to soften them. I have a bunch in my cupboard. They would not be edible raw any more than rice or beans are.

**Comment by fairyarmadillo** [comment]
The bot probably shouldn't autoclose issues that are actively being mentioned. It seems kinda aggro lately.
