### ISSUE TITLE
Stacks of Multiple Items Deleting Items on Partial Pickup

### ISSUE THREAD

**Issue by Grim914** [CleverRaven/Cataclysm-DDA#64823]
### Describe the bug

When grabbing stacks of ammo (All I have tested so far,) you pick up the ammo but it deletes the same amount from the stack you just picked up. 

For example; picking up 400 out of 1000 ammo will pick up 400 rounds and delete 400 rounds from the stack, leaving only 200 left on the ground. 

I have a backup save if needed

### Attach save file

[Kenova-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11150785/Kenova-trimmed.tar.gz)

I believe this is right after I had picked up 100 rounds of 5.56 and noticed that 200 rounds disappeared from the pile on the ground.

### Steps to reproduce

1. Have a stack of ammo
2. Pick up partial amount of stack
3. See picked up ammo and the stack on ground missing double the amount you picked up

### Expected behavior

Selected amount would be picked up and nothing from the ground pile would be deleted

### Screenshots

![Pickup 50 of 100](https://user-images.githubusercontent.com/129883155/229858328-73af380a-d8b7-478c-9e9a-4336c2346fce.png)

Here I pick up a 50 out of 100 5.56 NATO off of the ground

![Post Pickup Floor](https://user-images.githubusercontent.com/129883155/229858330-e691db6e-2d91-460e-83f0-c9f7569bb2e3.png)

50 Rounds are in my inventory

![Post Pickup Inventory](https://user-images.githubusercontent.com/129883155/229858334-1e1cefb4-e428-4660-b9cd-cd875dc5c558.png)

The remaining 50 rounds that should be on the ground have disappeared

### Versions and configuration

-Windows 10
-66a079d or build:2023-03-24-0154
-Tiles
-English
- "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "aftershock",
  "package_bionic_professions",
  "blazeindustries",
  "magiclysm",
  "crazy_cataclysm",
  "extra_mut_scens",
  "my_sweet_cataclysm",
  "MMA",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"

**Comment by irwiss** [comment]
sounds similar to what https://github.com/CleverRaven/Cataclysm-DDA/pull/64634 fixed, try reproducing on newest version

**Comment by Grim914** [comment]
Could not reproduce on the lastest build. Problem solved. Thanks! C:

**Comment by SurFlurer** [comment]
If you believe the issue has been fixed, you can close this issue. Thanks!

**Comment by Grim914** [comment]
Oh sorry didn't know that was on me!
