### ISSUE TITLE
[Magiclysm] Animist spells do not summon anything

### ISSUE THREAD

**Issue by jiornojiovanni** [CleverRaven/Cataclysm-DDA#64824]
### Describe the bug

The animist summon spell do not spawn anything. Also true for the vodoo dolls.

### Attach save file

N/A this bug is also reproduced on a new world and a new character

### Steps to reproduce

1. Spawn as necromancer, learn spell in other ways
2. Use the spell
3. You get the success message but nothing happens

### Expected behavior

Where is my zombie senpai 😢 

### Screenshots

![immagine](https://user-images.githubusercontent.com/31773561/229862515-990e0352-8bf6-4ff5-9737-181db7a4955d.png)
x

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: e084982 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by GuardianDll** [comment]
/confirm at e084982.  I tend to believe its another bug caused by #64416 because it's the only recent change in the spell code

![image](https://user-images.githubusercontent.com/67688115/229865825-46fbeb41-0f18-4a6d-bc06-d6a6e108b433.png)
