### ISSUE TITLE
Can't change the shape of seats and saddles

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#64827]
### Describe the bug

Change shape option in vehicle menu doesn't work for seats and saddles, and potentially others. I can make it work for frames, quarterpanel and windshields though.

### Attach save file

N/A

### Steps to reproduce

1. get a tileset with dedicated sprite for bicycle (OPTIONAL)
2. try to change the saddle for scooter saddle
3. the sprite is the same
4. if you open othe menu again it's still open to the defautl and nothing happened (If you do the same for a frame the menu will reopen on the frame shape you chose)

### Expected behavior

The sprite changes if the tileset supports it and the shape menu opens on the shape I chose instead of just the top of the list

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 0.F-14540-ge084982901 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Looking at the code it seems that the change shape option actually only works for variants but doesn't do anything for shapes aside from listing them in the menu
https://github.com/CleverRaven/Cataclysm-DDA/blob/e084982901e3d99e5d8b6f41c6ec74e0bd71cafb/src/veh_interact.cpp#L2125

**Comment by irwiss** [comment]
oh welp, i forgot to mark this issue, https://github.com/CleverRaven/Cataclysm-DDA/pull/65871 should resolve this
