### ISSUE TITLE
Constant dissections on humans should make the player character desensitized to autopsies

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#64835]
### Is your feature request related to a problem? Please describe.

Human dissections are a part of becoming a Prime human, yet only cannibals, psychopaths, and non-human mutants get the ability to dissect corpses without getting depressed. This is somewhat counter-intuitive gameplay wise, but it also just does not make any sense realistically either. A huge part of work for doctors, surgeons and police workers is seeing the insides of people. I don't think being able to stomach the insides of other humans makes you a monster, especially if your desire is not to cannibalize them, but for genuine medical (or in this case, evolutionary) reasons.

### Solution you would like.

While butchering and eating humans should always disturb your character unless he/she is a psychopath, the player should get slowly used to opening human corpses if it is done frequently. Maybe at around the same rate it requires to master the Physiology proficiency, or longer.

**Comment by fairyarmadillo** [comment]
What if having the principles of biology or physiology proficiency were what removed the debuff? That would make characters who come out of chargen with pre-cataclysm autopsy experience be unbothered by it, too.

**Comment by anoobindisguise** [comment]
#61172 
Discussed at length there and would resolve this issue.

**Comment by cataclysmsurvivalist** [comment]
> What if having the principles of biology or physiology proficiency were what removed the debuff? That would make characters who come out of chargen with pre-cataclysm autopsy experience be unbothered by it, too.

It fits the proficiency, but the issue with making Physiology needed to stop the morale debuff is that morale is what determines how quickly you master a proficiency in the first place. Making the number of dissections needed to stop the debuff different from the number needed to master Physiology would make it slightly more realistic than your character getting massive debuffs up until the second he masters a proficiency, at which point he has zero issues with it.
There's a similar mechanic with killing zombie children, where the Small Humanoids proficiency and the number of enemies you need to kill to stop feeling awful when you fight them are separate.

**Comment by Omnikron13** [comment]
Tbh it doesn't feel entirely right that you get the same pretty massive morale penalties for the various butchering options. I wouldn't expect somebody would be as traumatised and disgusted with themselves after dissecting ferals, presumably to try and learn something about why they've gone feral/are ignored by zombies/etc, as they do when for example skinning them like they're gonna do a Buffalo Bill or literally _butchering_ them with, presumably, the intention to _eat_ them.
Dismembering being again the same level is getting even more extreme, as your character seemingly had no qualms caving  their head in with a frying pan or doing whatever unspeakable thing 'pulping' actually entails that so reliably ensures the thing is incapable of rising. (By the name, 'pulping' a body sounds even more psychotic than dismembering it, if you ask me. =P)
