### ISSUE TITLE
Hallucinations give you clairvoyance

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#6484]
![screen shot 2014-03-06 at 9 56 09 pm](https://f.cloud.github.com/assets/4412171/2353550/3bb5feea-a5a4-11e3-81ce-aae7d55b3062.png)

For example, in this screenshot, I can see that there's a sewer running west-east just south of the basement I'm in, another basement one overmap tile to the west and two tiles south, and another basement two tiles east/three tiles south. I can also tell that the latter basement is a grow-op from the colour of some of the tiles.
##

**Comment by Night-Pryanik** [comment]
Can anyone confirm if this still an issue?

**Comment by John-Candlebury** [comment]
The whole effect causing this was removed so it’s no longer an issue
