### ISSUE TITLE
Inconsistant encumbrance from layer penalties

### ISSUE THREAD

**Issue by Aresf0** [CleverRaven/Cataclysm-DDA#64851]
### Describe the bug

Equiping two clothing items that cover the same body part but different 'specifically covers' body parts, will not get layer penalty if that body part doesn't have any other clothing items that have same 'specifically covers' value and layer, but will get layer penalty otherwise.

### Attach save file

N/A

### Steps to reproduce

1. Spawn 2 spear straps and a whistle.
2. Strip character, then wear a spear strap and the whistle. From '@', layer penalty is 0.
4. Take off whistle, then wear the second spear strap. Layer penalty is 2.
5. Wear the whistle. Layer penalty is 4 now, increased by 2.

### Expected behavior

I expect that wearing a whistle and a spear strap should always get or always not get layer penalty. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by bombasticSlacks** [comment]
The rationale is that if you have conflicts, everything will be getting in everything else's way making things that could coexist, also have issues. Maybe in the future we could fix this but it would require a rewrite of a huge chunk of code to support it and is potentially not something we even want to support.
