### ISSUE TITLE
Seatbelts being foldable is useless

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#64856]
### Describe the bug

There's no foldable seat that allows you to install a seatbelt. So for seatbelts, being foldable is useless, since you'll never get a chance to fold them.

### Attach save file

N/A

### Steps to reproduce

Examine a car, `i`nstall vparts, and find out the fact.

### Expected behavior

There should be foldable seats that allow installing seatbelts.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 0.G-1067-ge084982901-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Karol1223** [comment]
I really wouldn't say that this even remotely qualifies as a bug, to be honest. Like above, having them be foldable incase we get foldable seats makes full sense. Even then, there's no reason NOT to have seatbelts be foldable - they certainly wouldn't cause a problem with folding a vehicle.

**Comment by SurFlurer** [comment]
> I really wouldn't say that this even remotely qualifies as a bug, to be honest. Like above, having them be foldable incase we get foldable seats makes full sense. Even then, there's no reason NOT to have seatbelts be foldable - they certainly wouldn't cause a problem with folding a vehicle.

I totally agree with you. That's why I think there should be such seats above.

>**Expected behavior**
>
>There should be foldable seats that allow installing seatbelts.

**Comment by natsirt721** [comment]
Recommend closing this issue and making a request for the features you actually want, rather than opening a bug report.
