### ISSUE TITLE
After update to 2023-04-06-0152 all non damaged clothing & armor seems to be reinforced

### ISSUE THREAD

**Issue by qoreQyaS** [CleverRaven/Cataclysm-DDA#64876]
### Describe the bug

After updating and loading my save all of my (equipped and non-equipped) non damaged clothing/armor seems to be reinforced.
Even the items which can not be reinforced, but i didn't even have any reinforced gear before the update.

This does not seem to be saved, loading the same save with an older version (after saving with 2023-04-06-0152) is fine, nothing is reinforced any more.

### Attach save file

[Before update](https://github.com/CleverRaven/Cataclysm-DDA/files/11166431/Quivero-trimmed.tar.gz)
[After update](https://github.com/CleverRaven/Cataclysm-DDA/files/11166436/Quivero-trimmed.tar.gz)

### Steps to reproduce

1. Install 2023-04-06-0152
2. load provided save, look at equipped gear, equipped and non-equipped non damaged clothing/armor seems to be reinforced.
3. quit game (save or not save does not matter)
4. Install 2023-04-05-1217
5. load save, look at gear, everything is normal

### Expected behavior

non reinforced gear should be displayed as non reinforced (don't know if it's only a display issue)

### Screenshots

![image](https://user-images.githubusercontent.com/4641233/230274058-5f5e968d-d3ae-4f46-9bdf-69ef36b86635.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
    - Debian unstable/sid
- Game Version: daef9ea [64-bit]
- Graphics Version: Tiles UltiCa/Larwick Overmap
- Game Language: System language [] en_US
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks],
    My sidebar [sidebarfoo]
]

**Comment by qoreQyaS** [comment]
#64622 could be related here

**Comment by RDru** [comment]
what I understand from 64622 is that ++ is old ||

**Comment by qoreQyaS** [comment]
![image](https://user-images.githubusercontent.com/4641233/230324525-6c8fbbb1-1d01-404a-9405-36bd4040396d.png)
this confused me for the boots, but that's just the normal item description. nvm then
