### ISSUE TITLE
Crash on repeated eyebeam

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#6488]
Sleeping in a car near a tear in reality. Floating eye spawned in the middle of the night, used his eyebeam a ton of times, I started to get debug messages, which I spaced past, and then the game crashed.

Debug message won't properly copy/paste over and is different between Notepad and N++, so here's a screenshot of it: http://i.imgur.com/q4I3SFu.png?1

**Comment by mugling** [comment]
Closing as it's an ancient issue and neither further reported nor suspected to be present in `master`. @Waladil please re-open if you can reproduce in any recent version
