### ISSUE TITLE
Expand snippets in notes

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#64892]
### Is your feature request related to a problem? Please describe.

#59602 was already a great improvement but how about the possibility to include snippets within the note-snippet system?

So for example this item
```
  {
    "type": "GENERIC",
    "id": "survnote",
    "category": "books",
    "symbol": ",",
    "color": "white",
    "name": { "str": "survivor's note" },
    "snippet_category": "note",
    "description": "A scrap of paper.  Something's written on it, scrawled in bad handwriting.",
    "price": 0,
    "price_postapoc": 0,
    "material": [ "paper" ],
    "flags": [ "TRADER_AVOID" ],
    "weight": "12 mg",
    "volume": "1 ml"
  },
```
  will display a snippet from "snippet_category": "note",
  which are formed like so:
```
   {
    "type": "snippet",
    "category": "note",
    "text": [
      { "id": "note_1", "text": "\"WE WERE RIGHT THE GOVERNMENT DID IT\"" },
      { 
(etc)
``` 

however in these "text" entries any references to other snippets with <snippet_brackets> aren't parsed 

  
  
  

### Solution you would like.

It would be great if we could enter snippets in there too, so we could have something like this
```
    {   
        "type": "snippet",
        "category": "ha_squatter_note",
        "text": [
            { 
                "id": "ha_squatter_note_1", 
                "text": "A piece of paper with big letters written on it that say:\n\"Sorry, we smoked your stash, come find us at <ha_squat_name>. Shit's getting wild around here.\n<ha_given_name> & <ha_given_name>\""
            },
(etc)
```
with the <ha_given_name> etc actually being replaced with a random name from the snippet section

### Describe alternatives you have considered.

-

**Comment by GuardianDll** [comment]
We already can, you just make a new snippet with custom category in brackets (like `<fuck_you>`), and write a list of what can be put here
I also think we have a few special tags that print the closest city or similar stuff

**Comment by LyranRenegade** [comment]
I don't think it does. I know it is supposed to work and in general you can put snippets in snippets, this is clear and works.,
But this is a special case that probably uses some different code that prevents it from working.
Because this time the snippets are attached to an item on generation they are not getting parsed.
(Due to it being an item with the snippet_category.)
To be clear, I just tried this:

```


    {   
        "type": "snippet",
        "category": "ha_test_note",
        "text": [
            { 
                "id":  "ha_test_note", 
                "text": "Snippet test: <snippet_test>"
            }            
        ]
    },
    {
        "type": "snippet",
        "category": "<snippet_test>",
        "text": [ "TEXT1", "TEXT2" ]
    },
    {
        "type": "snippet",
        "category": "snippet_test",
        "text": [ "TEXT1", "TEXT2" ]
    },    
```
It doesn't work. it just shows "Snippet test: <snippet_test>" in the description
