### ISSUE TITLE
Changing the sizes of cities during gameplay

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#64908]
### Is your feature request related to a problem? Please describe.

I'd like to change the size of cities that I encounter during gameplay.  Something like start in a big huge metropolis that you need to escape from, only to run out into a rural area with only a small village here or there.

### Solution you would like.

Maybe something in the options menu?  Change world-gen on the fly?

**Comment by anoobindisguise** [comment]
There is an option for this, go into "current world settings" in the escape menu.

**Comment by chrispikula** [comment]
> There is an option for this, go into "current world settings" in the escape menu.

[This ](https://www.reddit.com/r/cataclysmdda/comments/123w2oh/the_end/jdwp15g/) and the reply by I_am_Erk indicate that it's, so I'm proposing an alternative.  What shape that would take, I do not know.

>> I mean, to pose a different question: Why is "World defaults" even in the main menu? That's something I've been wondering... who would want to change the world default settings during an ongoing game? (And it IS confusing here, because it makes you wonder which of these settings, if at all, will have an effect on the ongoing game) I think that's something that's only relevant during world creation. So if you want to reduce UI clutter, why not remove the world defaults from the main menu completely, but keep the item category spawn rates inside the world creation menu?
> Why not indeed? You more or less just summarized the start of my recommendations. There need to be some advanced settings windows to couch this stuff, not more things added to an already overbloated tab. Those are exactly the things we're trying to fix. Unfortunately it appears one of the handful of people who most often does those fixes just left.

**Comment by anothersimulacrum** [comment]
I do not think we should support changing settings on a world post-generation.

**Comment by chrispikula** [comment]
But it's realistic that not all cities are the same size.  If there was another way to model my starting senario without having pre-made maps, I'd be interested in that.

**Comment by anothersimulacrum** [comment]
If that is your issue, you should go to "change the worldgen code", not "change settings on an active world".

**Comment by ZhilkinSerg** [comment]
> But it's realistic that not all cities are the same size. If there was another way to model my starting senario without having pre-made maps, I'd be interested in that.

Cities in-game are not of random size.

**Comment by chrispikula** [comment]
> If that is your issue, you should go to "change the worldgen code", not "change settings on an active world".

I didn't want to propose a feature that I know would just be yet another feature that gets eventually closed as 'not planned.'  

> Cities in-game are of random size.

Only slightly.  You will almost never get a metropolis along with a bunch of tiny rural hamlets.

**Comment by ZhilkinSerg** [comment]
> Only slightly. You will almost never get a metropolis along with a bunch of tiny rural hamlets.

The code tells "No":

https://github.com/CleverRaven/Cataclysm-DDA/blob/123606c54c7190fe156f53b968c6c399bf6cf8e2/src/overmap.cpp#L4993-L5005

**Comment by chrispikula** [comment]
> > Only slightly. You will almost never get a metropolis along with a bunch of tiny rural hamlets.
> 
> The code tells "No":
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/123606c54c7190fe156f53b968c6c399bf6cf8e2/src/overmap.cpp#L4993-L5005

Yeah, 1/3 is the smallest the size any new will get, yeah?  So if you start with, say, size 13 cities, you've got zero chance to gen cities the size of 3 or 2.

13 -1(*) = 12, then 1/3 of the time /3 = 4.  

*The other 50% of the time, it keeps the city the same size, as rng(x+1, x-1) is templated to float, and then truncated back to int, afaict.  But 13/3 via int math is still 4, so it doesn't matter. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/123606c54c7190fe156f53b968c6c399bf6cf8e2/src/rng.h#L31-L39

And that doesn't even include the rest of the cities that generate which will be medium or even larger.  Which are distinctly _not_ rural hamlets.

**Comment by ZhilkinSerg** [comment]
> > > Only slightly. You will almost never get a metropolis along with a bunch of tiny rural hamlets.
> > 
> > 
> > The code tells "No":
> 
> Yeah, 1/3 is the smallest the size any new will get, yeah? So if you start with, say, size 13 cities, you've got zero chance to gen cities the size of 3 or 2.
> 
> 13 -1(*) = 12, then 1/3 of the time /3 = 4.
> 
> And that doesn't even include the rest of the cities that generate which will be medium or even larger. Which are distinctly _not_ rural hamlets.
> 
> * The other half of the time, it's +1, but 15/3 = 4, so... no diff.

Don't start with city size 13. Default value is 8 - this is how game is supposed to be played. Anything else can and would cause somewhat broken overmap gen.

**Comment by chrispikula** [comment]
> Don't start with city size 13. Default value is 8 - this is how game is supposed to be played. Anything else can and would cause somewhat broken overmap gen.

Ah, so now comes the argument, 'you're playing the game wrong!'  Well, thanks I guess.  Glad to see such constructive criticism.

And you can have broken overmap terrain just by traveling in a donut shape and afterwards filling in the center.  That's not part of this issue.

**Comment by Zireael07** [comment]
@ZhilkinSerg If a player can set city size X in options, the issue does exists.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg If a player can set city size X in options, the issue does exists.

Anything other than default value can and will break the game by design, so it is not an issue that requires some kind of solution.

**Comment by Zireael07** [comment]
> Anything other than default value can and will break the game by design

Why even offer the options if you say they break the game by design?
