### ISSUE TITLE
Faulty nurse bot only rips one bionic

### ISSUE THREAD

**Issue by AkdoolTheSlimy** [CleverRaven/Cataclysm-DDA#64918]
### Describe the bug

So, I'm 99% sure that the nurse bot is intended to keep ripping CBM's out once they start. However, in recent updates, they will only remove one random bionic. After, they will ignore the pc even if the player walks up to the nurse and the nurse detects more bionics. 

### Attach save file

[Bellflower.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11181269/Bellflower.zip)

### Steps to reproduce

1. Make a Prototype Cyborg in a lab start
2. Find a faulty (hostile) nurse bot.
3. Let her catch you. She'll rip a random bionic out.
4. If you survive, when you awaken walk up to her and wait. The message log will say that she detects something every turn, but she won't actually do anything. Despite still being hostile, she'll leave you alone.

### Expected behavior

Either she keeps ripping while you're out until you run out of bionics, or after ripping one, she leaves and resumes once you awaken.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: fef3110 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
/confirmed The nurse bot doesn't lose `effect_grabbing` so it fails to grab you a second time since #64250.

`grabbing` is added as a permanent effect here https://github.com/CleverRaven/Cataclysm-DDA/blob/e33e1cfd8cd35b6cd912ab71f16f05a1cd068bc3/src/monattack.cpp#L2877

so it doesn't decay and it's never removed otherwise.
