### ISSUE TITLE
Return option to disable skill rust

### ISSUE THREAD

**Issue by showervic** [CleverRaven/Cataclysm-DDA#64916]
### Is your feature request related to a problem? Please describe.

I was always frustrated to start each day with removing skills rust.
Having multiple skills at high levels, it was taking a hour or two each day to craft same recipes over again just to remove rust.
Maybe its realistic, but not a fun at all.
So it would be nice to return the option to disable skill rust completely. 

### Solution you would like.

Revert https://github.com/CleverRaven/Cataclysm-DDA/pull/64708

**Comment by dseguin** [comment]
The option only existed because skill rust wasn't in a good enough state for regular gameplay, but it's been overhauled into a much more compelling feature since then, and the option to remove it is not coming back.
