### ISSUE TITLE
Making cash cards mergeable.

### ISSUE THREAD

**Issue by IOSYN** [CleverRaven/Cataclysm-DDA#6492]
So as it is right now cash cards drop pretty often, but many only have negligible value (say, 5 cents) which isn't enough to buy anything. That's fair enough.

I'm thinking once you've picked up a card, any further cards picked up simply add their total value to that card, then be destroyed.

Pretty sure we can hand-waive this since most cards nowadays are capable of contactless payment. (it also makes fraud lolsome, but still) Not too hard think that in the future you'd be able to transfer money directly to another card.

**Comment by kevingranade** [comment]
ATMs have a "Transfer all" function now, which leaves all your money on one card, people can feel free to add more ATMs to various map tiles, and add the PDA thing if they want, but I don't see a need for an issue about it now.
