### ISSUE TITLE
Selecting weight modifying traits cause crash on character creation

### ISSUE THREAD

**Issue by random-cdda-modder** [CleverRaven/Cataclysm-DDA#64923]
### Describe the bug

Selecting weight modifying traits cause crash on character creation.

### Attach save file

N/A

### Steps to reproduce

1. create default world without any mods to rule their effects out
2. create custom character
3. do not change defaults, tab through to traits selection
4. select Weight: XS or Weight XXL trait
5. see irrecoverable error below

### Expected behavior

expected to work

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: b7ed839 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

 DEBUG    : my_traits and my_mutations were out of sync for XS

 FUNCTION : void Character::toggle_trait(const trait_id&, const string&)
 FILE     : src/mutation.cpp
 LINE     : 193
 VERSION  : b7ed839

**Comment by philippeop** [comment]
Having this same issue on 0d77a97 with the Weight: XS trait

ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mutation.cpp:193 [toggle_trait] my_traits and my_mutations were out of sync for XS
