### ISSUE TITLE
Volumes of magazines and magazine pockets require some adjustment

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [CleverRaven/Cataclysm-DDA#64930]
### Is your feature request related to a problem? Please describe.

I've been trying out guns that don't use STANAGs lately, and I've noticed a lot of the magazines have way more volume than they should. A standard STANAG 30-rounder is 0.29 liters, while an MP5 30-rounder is half a liter. This mainly affects gameplay by making pretty much anything that's not a STANAG incompatible with mag pouches meant to fit them, even though you can easily cram a smaller magazine in one in real life (And while specialized pouches exist, it'd probably be better to abstract it to one or two types).

### Solution you would like.

The magazine volumes should eventually be adjusted, but if it's not expected to happen for it while it might be a good idea to increase the volume of pockets meant to hold most magazines to 0.5L.

### Describe alternatives you have considered.

Declare the use of anything other than 30-round STANAGs as heresy

**Comment by RenechCDDA** [comment]
#60038 needs someone to pick it up and finish it.
