### ISSUE TITLE
Uninstalling damaged vehicle parts damages them further

### ISSUE THREAD

**Issue by LordKaaven** [CleverRaven/Cataclysm-DDA#64936]
### Describe the bug

Whenever I try and uninstall a part from a vehicle, if that part is even slightly below full (++) durability, the process damages the part by an extra "stage" of damage. For example, uninstalling a ++Car Battery, will yield a full durability one, but when removing a |\ durability one, the one extracted will be of |. durability instead.

### Attach save file

[Boozeville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11183229/Boozeville-trimmed.tar.gz)

### Steps to reproduce

1. Find any vehicle with damaged parts
2. Uninstall some of them
3. Despair at their degraded state

### Expected behavior

Parts should extract in the state the vehicle inspector shows them, especially nowadays when repairs are way more difficult than before already.

### Versions and configuration

OS: Win 7
Mods: Disable NPC Needs, Blaze Industries, No Rail Stations, Np Fungal Growth, Portal Storms Ignore NPCs
Versions tested: Experimental 2023-04-07-1955 and 2023-04-08-0613

**Comment by irwiss** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/7e48693fa32d08369992d623c3eff893b5504803/src/vehicle_part.cpp#L96-L98

Seems there's a chunk to normalize part damage when removing that's misbehaving,, i'll fix it soon
