### ISSUE TITLE
Sidebar blocking my entire screen

### ISSUE THREAD

**Issue by AdityaMH** [CleverRaven/Cataclysm-DDA#64950]
### Describe the bug

In Android version, sidebar block my entire map. I can't see anything

### Attach save file

Doesn't need save file

### Steps to reproduce

1. Move sidebar to left in option menu.
2. Enter firing mode

### Expected behavior

I can't change firing mode sidebar position

### Screenshots

![IMG_20230409_153944](https://user-images.githubusercontent.com/33791472/230763160-2a270e8d-b1f5-4d06-ae23-548a1360d8dd.jpg)

### Versions and configuration

OS: Android 10
Version: O.G

**Comment by Rimplestilt** [comment]
tried this and it is better with my sidebar settings which are much more compact using...compact. but the firing menu is always on the right side.  I prefer the sidebar on the right anyways tho.
![Screenshot_20230409-081356_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/120688336/230771972-ef0bf428-3f20-45e2-aa23-748a80a63e50.jpg)

**Comment by RenechCDDA** [comment]
@AdityaMH Can you please use the "Generate game report" option from the in-game debug menu and share it here?

**Comment by AdityaMH** [comment]
> tried this and it is better with my sidebar settings which are much more compact using...compact. but the firing menu is always on the right side. I prefer the sidebar on the right anyways tho. ![Screenshot_20230409-081356_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/120688336/230771972-ef0bf428-3f20-45e2-aa23-748a80a63e50.jpg)

How do you resize firing sidebar?

> @AdityaMH Can you please use the "Generate game report" option from the in-game debug menu and share it here?

For what? Just add option to switch or resize firing side bar side. And this will be fine.

**Comment by PatrikLundell** [comment]
The reason for a request for generated game report information is that it contains a lot of information that might be relevant to reproduction and testing. It's surprising how often "irrelevant" information actually is relevant.

Of course, you can fix it yourself instead, as you've got the hardware/SW that has the issue at hand.

**Comment by AdityaMH** [comment]
I'm notice. Default setting is for very old phone (also impossible to find that phone in this time).

So, i'm fixing for myself.
I'm just:
 - switch "shortcut for overlap screen " to false
 - reduce "shortcut height" till my screen going black then add 1 point. (for me 50)
 - Increase "terminal width" same as your phone height (179 for me).
 - Decrease "terminal height" same as your phone width (39 for me).
 - And if font to small just increase font size, increase "terminal width" and reduce "terminal height" a bit for me (for me 12x24=28 *fw x fh = fz).


And everything going fine and fixed.
![Screenshot_2023-04-10-20-44-52-313_com cleverraven cataclysmdda](https://user-images.githubusercontent.com/33791472/230913278-e58059df-7142-47c3-9eab-e3d50a48d384.jpg)





> tried this and it is better with my sidebar settings which are much more compact using...compact. but the firing menu is always on the right side. I prefer the sidebar on the right anyways tho. ![Screenshot_20230409-081356_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/120688336/230771972-ef0bf428-3f20-45e2-aa23-748a80a63e50.jpg)

Thanks to motivate me.
