### ISSUE TITLE
Wrong coverage values for Kevlar jumpsuit shown in Item discription.

### ISSUE THREAD

**Issue by Spitalier** [CleverRaven/Cataclysm-DDA#64951]
### Describe the bug

The Kevlar Jumpsuit has a 100% coverage value for arms, legs and torso. But the breakdown of the armor values shows 1% worst and 80% best. 19% missing a value in the discription. 
Light Kevlar Jumpsuit and Steel Plated Kevlar Jumpsuit have both the same 100% coverage with a 10/90 breakdown.
I checked the raw jason data for the Kevlar Jumpsuit on HGTC and there is stated a 10/90 split as well, even in the general information.
So I assume that the shown value in the item description is just wrong and it works as intended.

### Attach save file

N/A

### Steps to reproduce

Open item description of Kevlar Jumpsuit in crafting menu or Inventory.

### Expected behavior

Expected stats split for best to worst armor values should be a 10/90 split instead of the shown 01/80.

### Screenshots

![Kevlar Jumpsuit Wrong Coverage indications](https://user-images.githubusercontent.com/98972796/230769536-6b79e78d-ad69-437c-917c-4aa468abbce4.jpg)
![KJS2](https://user-images.githubusercontent.com/98972796/230769542-dedfde98-49dc-4abd-b086-2bf45fe85edf.jpg)
![KJS3](https://user-images.githubusercontent.com/98972796/230769546-6f7dc46a-65db-41bd-9e7c-89e0c213971c.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: e95fede [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Spitalier** [comment]
Same Situation for the Steel plated Kevlar Jumpsuit

**Comment by keampe** [comment]
These suits have 4 layers - 2 at 100% and 2 at 90%. This gives a 1% chance to hit only the 100% layers, an 80% chance to hit all 4 layers and a 19% chance to hit both 100% layers and one or the other Kevlar layers but not both. It's simply not displaying that last 19%, but it is there. 

   - Shane
