### ISSUE TITLE
Suggestion: Add the possibility for a gun to go off in random direction (includung player's guts) if cleaned or worked on while loaded

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#64966]
### Is your feature request related to a problem? Please describe.

I keep reading of people who shot themselves, something or someone nearby because they didn't treat their weapons properly, and I've discovered that there is no penalty whatsoever for modifying or cleaning your gun while it's loaded.

This is REALLY stupid thing to do, and I would like to add this change both for the sake of realism, and as an educational message for people who've only seen guns in games, that if you don't Respect the Gun you'll be in a world of hurt.

### Solution you would like.

I'd love to see people who treat their guns in unsafe way get shot for their stupidity and/or lack of knowledge, and therefore learn to check their guns both in game and IRL.

Over skill level 2 in any firearms skill there should be a popup message telling people that playing with loaded guns is really unsafe.

Over skill level 1 in any firearms skill there should be a popup message of PC wondering if they forgot something.

### Describe alternatives you have considered.

Maybe some select mods could be added safely, like scopes and rail accessories? I'd still prefer to punish people who don't know how to safely handle a gun.

**Comment by fairyarmadillo** [comment]
We generally don't include gotchas like this one, that's why your gun will never explode from loading the wrong ammunition into it, for example.

**Comment by nexusmrsep** [comment]
The game meta has generally moved away from allowing risky behavior without at least promoting the player and in other places it assumes that character does what it takes to make the certain behavior safe.

**Comment by Zireael07** [comment]
^^ And for good reason, since this is a permadeath game

**Comment by sadenar** [comment]
Which gives the question, shouldn't the cleaning time be extended when done on a loaded gun? To add the fact that your character does not to unload the gun before doing the cleaning routine, that extra time being removed if done on an empty gun?
Would both add a little bit more realism to the situation while not being overly punitive or annoying gameplay wise.
