### ISSUE TITLE
Autonomous Surgical Scalpels not work in some location??

### ISSUE THREAD

**Issue by sacredsky** [CleverRaven/Cataclysm-DDA#64964]
### Describe the bug

I have an Autonomous Surgical Scalpels CBM installed.
I am in a FEMA refugee camp. If I dissect corpse inside it, it complains "1 tool with fine cutting of 1 or more" but showing message "You dissect the corpse with a sophisticated system of surgical grade scalpels." and nothing happened. (It showed 5 fine cutting in the butcher menu)

However, if you drag the corpse out of this location, it can dissect. Currently, I only found here has this bug, not sure what the cause of it.

### Attach save file

[德卢斯-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11186303/-trimmed.tar.gz)

### Steps to reproduce

1. Press B to butchery and select Dissect corpse
2. The corpse is not dissect

### Expected behavior

The corpse should be dissected

### Screenshots

![20230409155256](https://user-images.githubusercontent.com/9583737/230796437-a8e6b50d-494a-495b-97ee-fa563cdac52a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1413 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by sacredsky** [comment]
For example, you can drag this corpse north about 30 places or more, it can dissect there.

**Comment by GuardianDll** [comment]
You should activate the cbm to utilize the tool?

**Comment by sacredsky** [comment]
> You should activate the cbm to utilize the tool?

I don't think it is necessary to activate. At least simply drag the corpse to a different location, it will able to dissect.
