### ISSUE TITLE
 Batch crafting cooking from rotted fat/meat resets into completely fresh food.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#64967]
### Describe the bug

Batch crafting over 10+ rotten meat or fat results in the freshness being resetted to the defaul value.

### Attach save file

[Flanida-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11186419/Flanida-trimmed.tar.gz)

### Steps to reproduce

1.Wait for meat or fat to rot
2. Batch craft about 10 or more
3. Food is fresh again

### Expected behavior

The food should remain rotten after cooking i'm assuming.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: b7ed839 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Lives - Extended [extra_lives_extended],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

Someone mentioned in the discord this could have to do with item charges.

**Comment by RenechCDDA** [comment]
It's not due to batch crafting or charges, this is actually cooks_like at work. It's swapping the `chunk of meat (rotten)` with the new component, `cooked meat` (which is in itself also the crafting product).
