### ISSUE TITLE
Make grenades less risky

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#64975]
### Is your feature request related to a problem? Please describe.

Grenades are too risky, when you activating it, lets make it more realistic and survivour friednly

### Solution you would like.

Grenades are very usefull and VERY DEADLY AND DANGEROUS in game, and it necessary to make it better and safety
In reality - most of greandes will not explode after pulling out the pull ring. They will explode after some time after releasing safety lever. So, situation in game is simular to pulling the ring out and releasing safety leveler at once, but in reality you have few more functinality of grenade, which I wanted to be added in the game
1) You can pull the ring, but dont release safety lever. So, countdown to explosion will start only after releasing safety leveler. You can throw a grenade - and it will not explode in your hand
2) You can put pull ring back, so you can store back your grenade for further usage
3) You can pull ring and release safety lever - if its necessary for special time exploding

May be there is more realistic usages of grenades, but this must be in game

To make it simple, we can make it in another way to avoid too big menus

You activate the grenade = you pull the ring out
If you activate activated grenade again - appears pop up menu where you have two options: put the pull ring back or release the safety lever to start the timer before exploding
If you throw it - the timer starts after leaving your hand, if you dont release the safety lever, or it will explode taking into account time after the releasing safety leverer in hand

### Describe alternatives you have considered.

Leave all as it is

**Comment by AnotherSeawhite** [comment]
Maybe simplify to the level of "the lever goes off (the timer starts) when it leaves your hand"?

**Comment by Jan-Blasiak** [comment]
I agree with @KHeket, there are situations there you need to cook a grenade and there are situations where you'd want to throw the grenade at a perfect moment.

There is also a lot of zombie trolling potential by waving a ringless grenade in front of a zombie technician.

**Comment by KHeket** [comment]
> That seems an awful lot of keypresses though. Might be better to make it "pull the ring and release the lever" in one go when throwing or activating a grenade, so you can still cook the grenade. And in case someone really wants to throw a grenade without activating it, an option could be added to the targeting UI.

Usage of grenades are very rarely. And it will not be additional keypresses in most cases

Case 1: (a)ctivate grenade and (t)hrow it - the timer will start after throw (after leaving your hand, simular to releasing the safety leveler after throwing in reality). 
So there is no extra key presses, because the same way you are throwing the greneade in game for now. And in most cases for now you are throwing the grenade immediately, because every second after activation and holding grenade in hand is making you closer to death

Case 2: You (a)ctivate grenade and (a)ctivate it again - pop up menu appears with two variants - insert pull ring back to make the grenade safe, or to release the safety lever to start the timer before throwing
