### ISSUE TITLE
Traits: Stiff knees and bad knees are considered more defensive than fleet footed.

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#64978]
### Describe the bug

The game's character screen creation summary considers stiff and bad knees more "defensive" than fleet-footed.

### Attach save file

N/A

### Steps to reproduce

1. Make a new character
2. Select Bad knees trait, see summary - Defense going up.
3. Deselect Bad knees trait, select stiff knee trait, see summary - Defense going up.

### Expected behavior

Bad knees and Stiff knees makes it harder to survive, so expected behavior is for the defense summary to go down instead of up.

### Screenshots

![image](https://user-images.githubusercontent.com/21962421/230905792-e144d42f-8efa-489d-ac35-e893224dc23f.png)
![image](https://user-images.githubusercontent.com/21962421/230905813-d7aa7025-76a4-4c53-8c9b-2b8ab1de8518.png)
![image](https://user-images.githubusercontent.com/21962421/230905938-705c6bdc-0015-465b-a24e-a758808d3202.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 426b738 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
@bombasticSlacks

**Comment by bombasticSlacks** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/64944 fixes this I think. Basically mobility was being valued backwards.

**Comment by DillonSimeone** [comment]
Confirmed, #64944 fixes this. Closing issue. That was funny, kek!
