### ISSUE TITLE
High strength characters failing to escape from a grab should at least have a chance to drag the grabber along

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#64980]
### Is your feature request related to a problem? Please describe.

being grabbed is dangerous again which on itself is a good change imo.
What is a bit weird is that a strength 10+ character cant get away from being grabbed by a normal zed that he most likely could lift with one hand. So maybe their grab is very strong but then they should just get dragged along.
Because being grabbed not only means you can get bitten, but also that you're completely immobile which doesnt make sense in some situations.

### Solution you would like.

if the player strength is enough compared to the weight of the grabber there's a chance that on attempted movement, when the grab-break failed, he just drags the zed along.

**Comment by Agoelia** [comment]
Agreed, but this should come at a hefty cost in stamina.

**Comment by AcidAntOnAMinefield** [comment]
Currently, having a Str 6 or a Str. 10 character seemingly makes no difference. I've been minute-locked by a singular Zombie Security guard as a Strength 10 starting "unwilling mutant" plenty of times recently. Something's off with the grabbing system.

Monsters should have a "strength" value that checks vs the player's own strength when the grab is applied. If the player's strength is higher, then the chances of breaking the grab should be higher - and then these chances change based on which zombie, how many zombies are grabbing, etc. 

Zombies (as decaying matter) should not be strong enough to individually hold a player in place unless there are massive size or strength differences between the two.

**Comment by LyranRenegade** [comment]
Suggestion is that DEXTERITY mostly rules the chance to avoid being grabbed and STRENGTH the chance of dragging the zed
with a (equal?) Combination of the two ruling the chance getting out of a grab.

If you go accept 6 as a baseline value for the average human being. I can accept zeds' grabs being more tenacious as expected pure from their stats because of the lack of a brain (and feeling any pain).
On the other hand they are indeed rotting away as we speak so that would be an argument for weaker grabs.
In any case, if your avatar has str 8, dex 8 for instance he/she is way above averagely strong/dexterious so they should be mostly immune to being grabbed by a single regular zombie. Chances change with different amount of zombies and of course when they evolve. But something like a rationale could be formulated from that baseline. I mean, i know people make strength 10+ characters all the time because it's allegedly the most convenient stat in the game but that shouldnt mean that strength now gets devalued in the mechanics. 
And an other way to make grabs more challenging is to make the dragging & wrestling free actions taking more time / or indeed stamina as mentioned above.

**Comment by Venera3** [comment]
Dragging enemies is pretty far out of scope for now, to be honest. I'm not opposed to it, but it's not something I will add in this round in any case, especially since it introduces a difference between wait grab breaking and movement grab breaking, not to mention hilarious problems like "what if a monster you can't shake off would move onto a tile of another monster while getting dragged".

**Comment by AcidAntOnAMinefield** [comment]
To complement to the edit I did to my previous post, here's what just happened to me: 

https://ibb.co/KV1T8T4 and https://ibb.co/gzzB2PZ

- Opened the door and immediately the zombie stepped on the tile and grabbed me.

- 1 single decayed zombie did almost all of that limb damage you see there - all of my limbs were | | | | \  after he grabbed me. My character is equipped with full military gear, heavy ballistics vest w/plate, hard leg guards, hard arm guards. 

This is honestly rather off-putting.
