### ISSUE TITLE
Can't fire laser weapons

### ISSUE THREAD

**Issue by shell1610** [CleverRaven/Cataclysm-DDA#64997]
### Describe the bug

When I try to fire laser pistol or rifle, I get an error saying "Attempted to fire zero or negative shots".

### Attach save file

[Andrix-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11201088/Andrix-trimmed.tar.gz)

### Steps to reproduce

1. Load save, try to fire wielded weapon av-22

### Expected behavior

To be able fire weapon

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 3b674c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries]
]

**Comment by Juafr** [comment]
All are Aftershock lasers.

If you don't have a UPS in inventory it will give the error.

If you have the UPS and the gun is loaded it will use both magazine charges and UPS charges. If the gun is unloaded it will shoot anyway using only the same UPS charges.
Magazines for these guns are irrelevant.
