### ISSUE TITLE
Shooting is far too accurate

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#64990]
### Is your feature request related to a problem? Please describe.

Within about 12 tiles against a human-sized enemy, guns in single-fire mode almost never seem to miss if you aim, regardless of light or weather conditions. This makes combat incredibly easy once you find an M4 or other rifle with plentiful ammunition.

https://youtu.be/LyWozhgx83Q?t=1807 - Here is an example of what I'm talking about. In this video at the timestamp, a character with 0 marksmanship or gun skill, 10 perception and dexterity, in total darkness, is able to score an incredibly high hit percentage and wipe out a horde of zombies at close range while taking very little damage. I don't think the situation in this example should be unwinnable, just that the hit rate is too high.

This applies to both players and monsters, and seems to extend to throwing as well. People commonly complain that ferals, for instance, are much too accurate, but they use similar math to player characters who see similar success rates at 1 rank of throwing or higher.

### Solution you would like.

https://americanshootingjournal.com/nypd-accepts-the-reality-that-sight-shooting-is-not-used-in-cqb/ This article from the American Shooting Journal uses NYPD data to show that across 36 close-quarters shootings where a subject was hit, officers fired 311 times and only 36 of those shots struck the target, for a hit rate of 12%.

I'm not suggesting a ~90% reduction in accuracy. These officers were not always aiming precisely, the subjects may have used cover, and police are taught to fire multiple times in succession rather than aim between each shot, which is currently the dominating meta in Cataclysm (the article has further data relevant to this). But these are trained professionals, not random survivors, and to me these numbers suggest that:

* The accuracy rate against moving targets, even when precisely aiming, should be much lower than it is.
* Precisely aiming should be more difficult and time consuming, especially at low skill.

I think also lighting should count for more than it does currently. In the linked video, the character has normal human night vision and it doesn't seem to impact anything other than her visual radius. In reality, it would be harder to hit targets you couldn't clearly see even if you were on the upper end of natural human night vision capability. Obviously if you have mutant vision, bionics, or goggles that might change things.

If I had to chalk the issue up to any one thing, I would say that precisely aiming is too fast and easy, and it's nearly always the best idea to do it unless something is in melee range with you, in which case you can just sort of walk a few steps away.

### Describe alternatives you have considered.

Further penalties could be given to low-skill characters. If you handed a 0 skill person a gun, I would expect them to not intuit how iron sights work, for instance, and they would be badly hampered by poor stance, unfamiliarity with things like the safety, etc.

Barrel length could reduce accuracy in close range.

A point shooting or CQB proficiency could be introduced, with a penalty to aim speed in close range if the character doesn't have it.

Grabs should badly penalize the use of long guns, but not so much for handguns.

Unskilled characters could fire prematurely while aiming, but that might be stupid/annoying. That might be a neat thing for the shakes effect though.

### Additional context

Shooting little enemies like wasps and flesh raptors feels about right, so any changes made to general accuracy might need to tweak size penalties so that these enemies do not become unhittable.

There's also a helpful graphic here, provided by the New York Times, that demonstrates firing accuracy in police encounters at ranges relevant to our player characters: http://www.wehaitians.com/a%20hail%20of%20bullets%20a%20heap%20of%20uncertainty.html

Further data about police accuracy during use of deadly force at different ranges can be found here https://www.politifact.com/factchecks/2018/may/25/shannon-watts/do-more-7-10-police-bullets-miss-their-mark-gun-co/

According to the above data, firing accuracy by police in close quarters deadly force scenarios is usually around roughly 35 percent.

**Comment by natsirt721** [comment]
Maybe related #64849

**Comment by fairyarmadillo** [comment]
I'll ignore your unhelpful tone to point out that the article stated the following:

>>Thirty-four officers (44%) reported that they had used their sights. As such, 56 percent of the officers shot without use of the sights.

Nearly half of the officers in the report were properly aiming. While I am sure the hit rate would have been higher if they'd all been able to do so, I sincerely doubt that the 56% who were unable to use their sights account for all of the missed shots.

If you refer to the primary source linked in the article, they go on to say that the majority of officers listed were discharging their guns within fifteen feet of their targets. 31 percent were moving or struggling. Three of the forty subjects were attacking officers with knives and five were using overwhelming physical force (ie bare hands).

These conditions sound very much like what was demonstrated in the video, and in both the source and the article are indicated to have been a primary reason why it was impossible to assume a shooting stance and aim properly, something the character in the video has no problem doing.

There's also a helpful graphic here, provided by the New York Times, that demonstrates firing accuracy in police encounters at ranges relevant to our player characters: http://www.wehaitians.com/a%20hail%20of%20bullets%20a%20heap%20of%20uncertainty.html

Interpretation of these statistics for our purposes should account for situations where the target is taking cover (ie a two-way gunfight) but the data clearly indicates that no, you don't simply automatically hit whoever you aim at IRL, regardless of what's happening.

**Comment by natsirt721** [comment]
I don't think that the situations of 'a survivor shooting a brainless zombie' and 'a police officer shooting a potentially armed or actively hostile human' are equivalent. Zombies just don't behave like people do, and it is going to be much easier to hit them than a living breathing human who can think and react.

You've clearly put the effort in here and TBH I agree with your core point that firearms feel very strong in the early game, but I disagree that your findings are applicable.

**Comment by fairyarmadillo** [comment]
> They are not. By default they are slower than a walking survivor. And they are not using cover or moving laterally; 

Well most zombies have stumble so they move erratically, and the basic ones move at 70, which is a slow but not ridiculously slow walk.

But you can't really use enemy speed as justification here without totally reworking the aim calculations to check enemy hostility and speed along with size. Many enemies in the game move at human speed or faster, and some are leaping huge distances or flying through the air.

> That's the thing - I don't think that there is any real-world data that is going to align well-enough with the situations we find in game. Killing zombies with a gun is somewhere between hunting a wild animal and a firefight with a human - but the middle ground is just not a situation that happens IRL.
> 
> Again, I don't disagree with the core point, but I don't think that citing police firearm accuracy data is a viable path to closure. At certain places the game crosses the line between real life and speculation - this is one of those times. Its going to be more about 'how does this feel, and how can we change the mechanics so that it feels better' and less of 'dig up enough data to support the changes I want to see'.

In my first post I stated that I don't think the numbers in the police statistics should be the target, just that they're illustrative of how far off base our current numbers are.

The more I think about it, the more I'm convinced that aiming speed is simply too fast. If it scaled a lot more with skill, not only would we have fewer 0 skill John Wicks, we'd see low-skill players forced to take suboptimal shots and guns would go from feeling clumsy but dangerous to properly devastating as you gained skill.

It might also be good to lower accuracy or even lock precise shots behind 3 skill or something on top of that, just to prevent people from complaining that they NEED to use precise shots all the time and guns are "too slow now."

**Comment by natsirt721** [comment]
> But you can't really use enemy speed as justification here

The point is that zombies are slower than people being shot by police, and therefore should be easier to hit than people be shot by police.

> In my first post I stated that I don't think the numbers in the police statistics should be the target, just that they're illustrative of how far off base our current numbers are.

Sure, that's true. But it does muddy the discussion - see how many replies here are about 'your data is incorrect/inapplicable for xyz reason' and not addressing the core issue that you have. 

> The more I think about it, the more I'm convinced that aiming speed is simply too fast.

Oh, you mean [that thing I just said?](https://github.com/CleverRaven/Cataclysm-DDA/issues/64849#issuecomment-1503861628)

**Comment by fairyarmadillo** [comment]
> Oh, you mean [that thing I just said?](https://github.com/CleverRaven/Cataclysm-DDA/issues/64849#issuecomment-1503861628)

Yep. How's about I close this issue to direct the conversation that a way? It feels like we're vaguely on the same page.
