### ISSUE TITLE
Xedra Evolved - Firmament Driver spell missing class and energy source

### ISSUE THREAD

**Issue by Morat2255** [CleverRaven/Cataclysm-DDA#65009]
### Describe the bug

You can check it in game if you want, but it's easier to just look right in the json. In inventor_spells.json, the entry for Firmament Driver is missing the lines:

"spell_class": "INVENTOR",
 "energy_source": "MANA"

If you learn the spell in-game, you'll see that it's listed as classless, and despite the artifact correctly showing the current and final cost, you can actually cast it for free since there's nothing to tell the game what resource that cost should be paid in.

I might just fix it myself later, since it's an easy one, but I might not. TBH, I kinda just want to play the game.

### Attach save file

N/A

### Steps to reproduce

1. Cheat in a String Theory for Dummies artifact and activate it.
2.  Notice that it incorrectly says that the Firmament Driver spell is "Classless", but that it does correctly list the casting cost.
3. Learn the spell and open the spell menu
4. Notice that it still says classless, but also the casting cost is no longer present.

### Expected behavior

I expect that the spell class should be "Inventor", since that's where the spell is found in the json files. I also expect that the casting cost should be paid in mana, or possibly biotic energy or stamina, but most likely the intended resource is mana.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 1ab1bed [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Gigachadicus - Prime Human Overhaul [Gigachadicus],
    No Bionic Slots [no_cbm_slots],
    Resource Crops [resource_crops],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Pneumatic fun [pneumo_fun]
]

**Comment by Devengel** [comment]
Closed PR, GuardianII is working on a PR that is revamping inventor, which includes fixing this issue.

**Comment by TimPollard** [comment]
@GuardianDll 's pull request (#65030) has been merged, and did include a fix for this issue, so it should probably be closed now.
