### ISSUE TITLE
Gunsmith turrets shoots at all moving vehicles

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#65024]
### Describe the bug

Gunsmith's turrets will shoot at all moving vehicles. 

![image](https://user-images.githubusercontent.com/21962421/231409982-4c88c84a-157f-4b25-be50-4fdfb8b9be77.png)

### Attach save file

N/A

### Steps to reproduce

1. New game
2. Reveal overmap
3. Teleport to gunsmith's home
4. Spawn in a vehicle
5. Drive close to the turrets
6. Get shredded into red mist

### Expected behavior

Gunsmith's turrets ignore vehicles?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 3fe23d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by DillonSimeone** [comment]
Maybe not actually a bug. The turrets' behavior should be made clearly intentional, maybe?

![image](https://user-images.githubusercontent.com/21962421/231411781-73187437-4354-41ec-aa83-a1a9c09a63a3.png)

**Comment by DillonSimeone** [comment]
If this is not a bug...

Hm. What about attaching speakers to the turrets that screams at vistors to get out of their vehicle before they're shot. The gunsmith wouldn't want his customers to get shredded, right?

**Comment by KHeket** [comment]
I think, if they dont see you while you are driving in the car - it is ok, that they will shot you, because this car can be recognized by turrets as a robot or a bandit, which hided in the car and trying to get closer to gunsmith base to robb it. But if turrets see you in the car and shooting at you - it a bug. But much more easily to make turrets just dont shoot frindly cars

**Comment by KHeket** [comment]
> Hm. What about attaching speakers to the turrets that screams at vistors to get out of their vehicle before they're shot. The gunsmith wouldn't want his customers to get shredded, right?

In this way, I think, it better to place signs around gunsmith store, simulars to signs near the mine fields, because sounds can attract zombies, spiders and ather monster, and you can just dont hear or miss warning message in the message log

**Comment by Maleclypse** [comment]
Target vehicles should be removed from artisan and Exodii turrets is my suggestion

**Comment by kevingranade** [comment]
I do like the "warning signs outside the turret perimeter" option though,
maybe even with a lil parking lot.

**Comment by stubkan** [comment]
Isn't the bullet bank a place that welcomes visitors and customers?  It doesn't make sense to have his turrets shoot up his customers on purpose.

The Exodii do not expect visitors (they express surprise when you walk in) so that place could have hostile turrets and fit the narrative.

**Comment by TheEskir** [comment]
This side-effect should definitely not be regarded as a feature. Why not just make friendly/neutral turrets check the vehicle faction alignment? 

It's already dumb that they shoot you up when you're neutral or even friendly, but being able to use *their own car* to cheat the system like that should be a good indication that the system needs some moderation.

**Comment by TheEskir** [comment]
> I think, if they dont see you while you are driving in the car - it is ok, that they will shot you, because this car can be recognized by turrets as a robot or a bandit, which hided in the car and trying to get closer to gunsmith base to robb it. But if turrets see you in the car and shooting at you - it a bug. But much more easily to make turrets just dont shoot frindly cars

Oh thank god, I thought I'd have to consider this faction hostile going forward. I already had a bad feeling when this was posted as a pr for the corresponding bug report. 'It's not a bug it's a feature!' is only funny in the memes.
