### ISSUE TITLE
Wheeled Zombies

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#65029]
### Is your feature request related to a problem? Please describe.

What happens when a blob-infected person dies while sitting in a wheelchair? Or while wearing roller skates?

We know the blob is really adaptive, and will take advantage of armor the person was wearing. It'll incorporate Kevlar and bionics into its function. So... what about wheels?

### Solution you would like.

Wheeled zombies should be FAST. Really, really fast, faster than runners. But, because they're using wheels for locomotion rather than feet, they should have a lot of trouble getting over obstacles.

Variants:
- Wheeled Zombie. The zombie of a person who died while sitting in a manual wheelchair. Their flesh has grown into the chair itself, and it is now using the wheels to propel itself very fast on smooth surfaces, but is slowed down greatly by rough terrain. It can bash its way through obstacles, and prefers to do so rather than climbing through windowsills, etc. Common in nursing homes and hospitals; rare elsewhere.

- Wheeled Zapper (Electrical variant). This zombie has incorporated the battery of a wheelchair or scooter into itself. It is a little slower than the default wheeled zombie, but it can defend itself with electricity, zapper style. Common in nursing homes and hospitals; rare elsewhere.

- Stroller Zombie (Child variant). This child died while sitting in a wheelchair or in a stroller. Because there's a lot of vehicle and not that much child to go around, the blob has stretched the child's limbs into tentacles, and created a few new ones, to interface with the vehicle. These zombies are smaller and harder to hit, and they have some armor from having incorporated the vehicle. They are not as fast as a wheeled zombie, but faster than the zappers. Common wherever child zombies are common; rare elsewhere.

- Skater Zombie. This zombie is wearing roller skates, roller blades, or wheelies. They are very fast on pavement, and can climb over obstacles, albeit slowly. They are smart enough to try to stay on pavement. Occasionally seen in the general zombie population.

- Wheeled Amalgamation (Evolved variant). This is a large, fast zombie that has incorporated several bodies into its makeup. It is nearly as fast as the default wheeled zombie, and heavy enough to bull its way through obstacles easily. It hits like a truck, and because it has incorporated some legs into its makeup, it can navigate rough terrain at a speed only slightly slower than a typical zombie.

**Comment by Venera3** [comment]
- Incorporating mechanics is not in character for zombies in the slightest.
- A kid in a stroller would be too small to zombify.

**Comment by NetSysFire** [comment]
I agree and you would probably just get crawling zombies or something similar.

**Comment by chaoticidealism** [comment]
> * Incorporating mechanics is not in character for zombies in the slightest.
Really? Kevlar hulks and Kevlar zombies incorporate the Kevlar into their flesh. Zappers and shockers use the power supply from their bionics. Some zombies throw grenades, so we know the blob can figure out simple tools. A wheel is pretty darn simple.

>     * A kid in a stroller would be too small to zombify.
Then why do we have Creepy Crawlers, Snotgobblers and Anklebiters? All of those imply toddler-sized children. If you kill a chihuahua--which tends to weigh about five pounds--it will revive as a zombie dog. Also, the lore in the science labs implies that the blob can revive an animal as small as a rat.

**Comment by anothersimulacrum** [comment]
> Zappers and shockers use the power supply from their bionics.

No, they don't.

> Some zombies throw grenades

Please list those zombies.

**Comment by fairyarmadillo** [comment]
Kevlar is not mechanical, it's an organic compound synthesized from hydrocarbons using heat and acid. Kevlar hulks have simply produced more of that material in the same manner they produce flesh and bone. This is remarkable but it isn't tool use.

**Comment by SariusSkelrets** [comment]
>  Zappers and shockers use the power supply from their bionics. 
They stopped having bionics some months ago

> Some zombies throw grenades
The grenadiers were turned into the Northrop dispatches long ago, and even before that they didn't threw the grenades, they just knew somehow how to activate their explosive hacks

**Comment by ProfessorBright** [comment]
This DOES make me think about a potentially interesting monster behavior: a sort of joust/charge forward attack where the enemy CAN do a lot of damage if it hits, but if it misses it's forced to keep going forward a few tiles, potentially trampling anything else in its path.

Like the Hulk/Brute's regular attack but with a forced movement component.

**Comment by fairyarmadillo** [comment]
> This DOES make me think about a potentially interesting monster behavior: a sort of joust/charge forward attack where the enemy CAN do a lot of damage if it hits, but if it misses it's forced to keep going forward a few tiles, potentially trampling anything else in its path.
> 
> Like the Hulk/Brute's regular attack but with a forced movement component.

Great idea. Caves of Qud does a few things like this, and they actually have a visual indicator of the path it's taking the turn before it fires, which leads to a lot of panicked scrambling. I don't know if that would be appropriate or possible here, but it might be worth exploring.

If that kind of thing is too video gamey for zombies, it might make sense on a Yrax enemy, since they're supposed to be weird vehicles(?).

**Comment by chaoticidealism** [comment]
> > This DOES make me think about a potentially interesting monster behavior: a sort of joust/charge forward attack where the enemy CAN do a lot of damage if it hits, but if it misses it's forced to keep going forward a few tiles, potentially trampling anything else in its path.
> > Like the Hulk/Brute's regular attack but with a forced movement component.
> 
> Great idea. Caves of Qud does a few things like this, and they actually have a visual indicator of the path it's taking the turn before it fires, which leads to a lot of panicked scrambling. I don't know if that would be appropriate or possible here, but it might be worth exploring.
> 
> If that kind of thing is too video gamey for zombies, it might make sense on a Yrax enemy, since they're supposed to be weird vehicles(?) and can emit light and stuff.

I like it too. It has the same element of challenge as wheeled zombies, but since they evidently don't fit into the coders' vision (I'm not judging), this is a great alternative. 

Could also be eldritch creatures. Having organic wheels certainly isn't beyond the scope of mi-go and their kind, though they do tend to prefer tentacles.
