### ISSUE TITLE
Aborting the world generation cause segfault

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#65033]
### Describe the bug

Aborting the world generation cause segfault

### Steps to reproduce

1. Try to create a new world
2. Abort it in the middle
3. Segfault

### Screenshots

![GIF 12-04-2023 22-35-18](https://user-images.githubusercontent.com/67688115/231578390-1dc3a4a3-76ae-43ba-a93c-634adbce1b52.gif)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: eb85d6b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

**Comment by qoreQyaS** [comment]
on linux this seems different.
i don't know if you actually clicked "reset", but if you did the dialog which shows right after it is out of place.

```yaml
- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 3d15dcc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    My sidebar [sidebarfoo]
]
```

upon pressing the reset button and accept everything seems to be normal. (nothing happens, world does not exists, nothing should happen)

![image](https://user-images.githubusercontent.com/4641233/231602535-545ce8f1-5e68-489e-8ac2-311f26c54220.png)



but when exiting the dialog via ESC and accept the game exits and console shows this
`[1]    950799 segmentation fault  ./cataclysm-tiles`

**Comment by NetSysFire** [comment]
Can not reproduce on 0.G stable on Linux. Feels like this issue was introduced after the stable release.

**Comment by Vaskritaya** [comment]
on linux, it crashes when aborting worldgen on [2023-04-12-1139](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-04-12-1139) and later, but I had rolled back to [2023-04-12-1009](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-04-12-1009) for unrelated reasons and it does not crash when aborting world gen there.
