### ISSUE TITLE
Sounds not playing after update from 2023-04-12-0515 to 2023-04-12-1139

### ISSUE THREAD

**Issue by Spitalier** [CleverRaven/Cataclysm-DDA#65031]
### Describe the bug

After switching from 2023-04-12-0515 to 2023-04-12-1139, the sound pack OTOPACK lost most of its played sounds. The Same is true for CC Sounds as well.

### Attach save file

N/A

### Steps to reproduce

Start game with 2023-04-12-1139 build and use OTOPACK or CC Sound.
Sounds are missing from both packs which worked clearly in the 2023-04-12-0515 build.

### Expected behavior

Sounds playing like in older builds.

### Screenshots

https://drive.google.com/drive/folders/1a8SJ9ZhiGLvqpEE7FVDLuXzG-TutaG5D?usp=share_link

Here are 4 videos i took where I compare the two builds and sound packs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: eb85d6b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by anoobindisguise** [comment]
I can confirm I get the same issue, I get an error about the JSON structure of the sound pack when I boot up the game and then cannot get audio.

**Comment by Golfavel** [comment]
@irwiss

**Comment by SirClarke** [comment]
also getting no sound but no error popped up for me on build 2023-04-12-1708 (if i read it right)
