### ISSUE TITLE
Plants do not leave wood ashes despite there being patches of burned vegetation

### ISSUE THREAD

**Issue by MathTauAthogen** [CleverRaven/Cataclysm-DDA#65041]
### Is your feature request related to a problem? Please describe.

So the wood-ash patches strongly hint that they are patches of forest burned to leave only the residue. But if I play pyromaniac with a forest for real, setting a tree alight and watching it burn with glee, nothing is left behind! Where is my wood ash?

### Solution you would like.

Burning a tree should leave wood ash - that is, setting fire to it with a lighter or other firestarter and letting it burn to completion.

**Comment by NetSysFire** [comment]
Most of the plants have the `FLAMMABLE_ASH` flag. It could be an issue with this flag.

**Comment by PatrikLundell** [comment]
When I've set fire to forest areas there are patches of ash (of two different varieties, I think) left behind. I suspect there's a probability for ash to be left behind rather than a guarantee.

**Comment by MathTauAthogen** [comment]
There are patches of ash, but I burned away a bit of forest and I haven't had any of the "wood ash" item drop - I assumed that would be a way I could get it but if there was any I didn't see it.

**Comment by MathTauAthogen** [comment]
In particular, surely the wood ash item should drop without harvesting - the tiles of wood ash seem to suggest that, after all - that the wood ash was created when a forest burned without human intervention

**Comment by RenechCDDA** [comment]
> Most of the plants have the `FLAMMABLE_ASH` flag. It could be an issue with this flag.

Looks like you're right. (Preface: Have not touched this at all ingame and haven't been burning down any trees)

https://github.com/CleverRaven/Cataclysm-DDA/blob/8846e84f1d71438582caaa4e728fabb3fb791d79/src/map_field.cpp#L1042C4-L1066

It doesn't appear that terrain can *ever* transform into ash. Only furniture with that flag. The first else-if statement(lines 1042-1055) checks **terrain**, and simply modifies the field then sets terrain (sometimes), and nothing else. The second else-if statement(lines 1057-1066) checks **furniture** and simply modifies the field then sets the furniture to an ash pile (sometimes).
