### ISSUE TITLE
Traumatized Traveler at Ancilla bar do not despawn before spawning in a new NPC 

### ISSUE THREAD

**Issue by BlizzDA** [CleverRaven/Cataclysm-DDA#65045]
### Describe the bug

At the HUB01 train terminal a number of quest and trading NPCs will cycle out of the bar, being replaced by a new variant of their own type or one of the others.

NPCs are despawned when new ones take their place, but with 'the traumatized traveler' NPC this does not occur.

Added by: https://github.com/CleverRaven/Cataclysm-DDA/pull/64745

Eventually leading to significant crowding, broken furniture and shattered windows from what may be TTTs reacting to a NPC spawning with the Kaluptic Psychosis trait. (Or telefragging into a window and being scared by the noise of broken glass, typical AI stuff) 

The TTT shares a spawnpoint with the hireable mercenary, which will continue to spawn and despawn with no issue.

The 'pill pusher' NPC added by the same PR does not have the same issues as the TTT.

### Attach save file

[CDDA - Traumatized traveler duplicate NPC bug-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11218387/CDDA.-.Traumatized.traveler.duplicate.NPC.bug-trimmed.tar.gz)

### Steps to reproduce

1. Reach point where the HUB01 Terminal unlocks and its NPCs spawn in
2. Reach point where 'the traumatized traveler' appears in the spawn cycle
3. Wait for the next spawn update to trigger, 'TTT' does not despawn

### Expected behavior

For all these traumatized travelers to get a move on and stop killing the vibes of the place. It's hard to buy a good drink or hire a mercenary when they're crowding the place with their slumped figures and thousand-yard stares. 

### Screenshots

<img width="960" alt="2023-04-13 (4)" src="https://user-images.githubusercontent.com/126328530/231657412-844964fc-1594-45ba-b435-a2685b9312f2.png">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: a8a21a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Nebnis** [comment]
I can confirm that this happens to my save too.

**Comment by John-Candlebury** [comment]
Thanks will make a fix as soon as able.
