### ISSUE TITLE
Rotting corpses leaving bones

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#65052]
### Is your feature request related to a problem? Please describe.

Corpses rotting away should leave bones/skeletons behind. Bones are useful for charcoal and shouldn't disappear into thin air.

### Solution you would like.

Use butchery results to determine what kind of bones should be left behind from a corpse rotting away.

### Describe alternatives you have considered.

Corpses rotting into skeletons, which require further butchery to clean the bones.

**Comment by Venera3** [comment]
With the caveat of extending corpse rot times, sure. Corpses don't get raptured after three days, after all.

**Comment by estebandellasilva** [comment]
Dont see the Problem ... never have corpses ... my car can destroy anything
