### ISSUE TITLE
Taking off the item is instant

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#65062]
### Describe the bug

`T`aking off the item spent no time, no matter of the item type

### Attach save file

N/A

### Steps to reproduce

1. Spawn a character
2. Try to `T`ake off some items
3. See it cost nothing

### Expected behavior

`T`aking off cost the same amount of time as `w`ield the item (both of which can be sticked to some variable in the future)

### Screenshots

Note how the clock show no changes at all
![GIF 13-04-2023 21-06-59](https://user-images.githubusercontent.com/67688115/231859216-ce19e558-47a5-4085-83b5-25432aca113c.gif)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: eb85d6b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

**Comment by hexagonrecursion** [comment]
/confirmed There is an inconsistency: taking off an item via the [T]ake off item menu does consume time, but taking it off via the [I]nventory menu costs nothing

![image](https://user-images.githubusercontent.com/52621858/232987916-083ae34e-3e0f-43b0-9e6b-1c2515dc61ec.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 37 (Thirty Seven); Release: 37; Codename: ThirtySeven; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Fixed by #76869.
