### ISSUE TITLE
Vehicles spawn without water

### ISSUE THREAD

**Issue by Voidsay** [CleverRaven/Cataclysm-DDA#65063]
### Describe the bug

Vehicles that have tanks that should be filled with water or clean water spawn with empty "water tanks". 
Affected vehicles are:
- cabin_cruiser_wood 4 tanks with water_clean
- water_cart 1 tank_small with water_clean
- fire_engine 9 tanks with water
- van_motorhome 1 tank with water_clean
- lux_rv 1 tank with water_clean
- surv_rv 1 tank with water_clean
- rv 1 tank with water_clean
- bus_tour 1 tank with water_clean
- car_atomic_flame 1 tank with water, 1 tank with water_clean (CrazyCataclysm mod)

### Attach save file

N/A

### Steps to reproduce

1. Spawn undamaged fire_engine via Debug Menu
2. Examine vehicle

### Expected behavior

The tanks that have the fuel set to "water" or "water_clean" should spawn 80% full, just like the tanks that are marked with "gasoline" etc. In a perfect world I should be able to spawn a vehicle with any (comestible) liquid filled in the tanks for maximum modding support.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19.2 Tina; Release: 19.2; Codename: tina; (Ubuntu 18.04 equivalent)
- Game Version: f65b2bc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

second test with latest version:
- OS: Linux
    - OS Version: Distributor ID: LinuxMint; Description: Linux Mint 19.2 Tina; Release: 19.2; Codename: tina; 
- Game Version: 026046b-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Test Cart [cart]//custom test mod with different liquids in tanks
]

### Additional context

I've also tried looking for the problematic vehicles in the wild on the off chance that they have a bit of water, but to no avail. This issue seems systemic. All liquids of type "AMMO" (any defined in data/json/items/fuel.json) are spawned without any issue, only "COMESTIBLE" (like water) are silently dropped.

**Comment by RenechCDDA** [comment]
/confirmed

I spawned the fire_engine and found it had no water. It should have water according to https://github.com/CleverRaven/Cataclysm-DDA/blob/0d77a970f86c9624827cec325b69bcd824737f2b/data/json/vehicles/emergency.json#L165

It looks like veh_type.cpp has a lot of debug messages to catch this but for some reason it's silently dropping the water without ever getting to those debug messages. Wasn't able to find any obvious cause.
