### ISSUE TITLE
Portal Storms: Random Dunegon, able to jump off ledge

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#65072]
### Describe the bug

If you run to the right, you can eventually find a gap in the walls and jump off.

I thought this was the solution to the dungeon, my character disappeared into nothingness instantly. No messages, no warning. Just there, then not. See screenshots.

### Attach save file

N/A

### Steps to reproduce

??? What is this witchery ???

### Expected behavior

The dungeon is solved, you've broken through to the other side?

### Screenshots

![image](https://user-images.githubusercontent.com/21962421/232022314-35d8264a-ee06-406b-b298-fcfa79d89776.png)

![image](https://user-images.githubusercontent.com/21962421/232022432-4198ce2d-5c72-4cb0-862a-f6c32d5e04ad.png)

![image](https://user-images.githubusercontent.com/21962421/232022463-e9d81c7d-30f0-4fdc-9022-7efd68b636cd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 026046b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by adamkad1** [comment]
No jump prompt or such?

**Comment by DillonSimeone** [comment]
Jump prompt, but no mention of how far of a fall it was like elsewhere, which got me thinking that it was the solution.

**Comment by Adomatic** [comment]
I have seen this too (although only over on the left hand side). If you peek over the edge, you can see that you're seven floors up, in midair, directly above where you were. It doesn't matter how many times you go into to the portal, you're still seven floors up. I figured (apparently rightly) that one would not enjoy the trip down, and that this was a bug, so I didn't try it. If I'd had a grappling hook I might have tried it, though I'm not sure how long the attached rope actually is.

**Comment by DillonSimeone** [comment]
Yeah, I expected to just go splat seven floor down on the ground, but I
just got Thanos snapped away into dust with no prompt to watch my last
moments, kek.
