### ISSUE TITLE
Weird interaction with crafted cooking oil in specific recipe

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#65074]
### Describe the bug

So for some weird reason, one charge of cooking oil I crafted cannot be used in the fried dandelion and burdock recipe. It appears in the component list as rotten and will not let me initiate the craft. The crafted cooking oil was not crafted from rotten ingredients and is not rotten itself (as cooking oil can't rot)

### Attach save file

[TrailBalls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11234712/TrailBalls-trimmed.tar.gz)

### Steps to reproduce

1. Search up the 'fried dandelions and burdocks' recipe
2. Notice that the cooking oil is considered rotten in the ingredient list
3. Try to craft it anyway (foolishly) and see the game adamantly say no
4. Examine the cooking oil (in inventory) and see that it was crafted from fresh ingredients and isn't rotten
5. (Optional) Cry

### Expected behavior

I want to craft my greens man

### Screenshots

![obraz](https://user-images.githubusercontent.com/68503002/232093400-2bcb335a-b019-401d-aa78-331c2296c3bf.png)
![obraz](https://user-images.githubusercontent.com/68503002/232093430-2b086a0c-42af-48a0-9bbb-6b459a618f18.png)
![obraz](https://user-images.githubusercontent.com/68503002/232093517-b0ff6c92-26a3-40af-b4ea-231517f76df5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 40b1d9d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

All other cooking oil from that batch craft was used up fine. It's the last charge that's not cooperating.

**Comment by RenechCDDA** [comment]
/confirmed the recipe is uncraftable with this one specific animal cooking oil, and displays as brown (rotten component) in the menu.

I edited the recipe locally to add the `ALLOW_ROTTEN` flag.... this does **not** allow the recipe to be crafted.

![image](https://user-images.githubusercontent.com/84619419/232098475-670897e3-653b-4d6c-aef8-51fa72530d66.png)

**Comment by RenechCDDA** [comment]
Interestingly if we spawn another component it gives us the animal cooking oil as a valid component:

![image](https://user-images.githubusercontent.com/84619419/232102021-d398069e-58a9-410e-880e-453088910d71.png)

But selecting it causes the craft to immediately fail *after consuming the cooking oil*.

![image](https://user-images.githubusercontent.com/84619419/232103594-37b7058a-9f59-4534-82e4-4e83f2717df3.png)

Trying to resume the craft gives a warning that the component (animal cooking oil) is missing, so it's not just that it was consumed during crafting. It was consumed and not added to the in-progress item's component listing.

**Comment by mqrause** [comment]
Animal cooking oil is used both as a tool and a component, so with just one charge you can't craft it. Dunno what the issue with multiple charges is, though.

**Comment by Karol1223** [comment]
Ah, well, that resolved itself I guess.

**Comment by Zireael07** [comment]
I think crafting menu not making it clear what's going on when something is both a tool and a component is an ongoing issue - can it be improved somehow?

**Comment by Karol1223** [comment]
Yeah I considered leaving it open for the UI improvement purpose but I'm not quite sure if this qualifies
