### ISSUE TITLE
Perform mandatory formatting rather than just complain until the PR submitter gets it right

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#65087]
### Is your feature request related to a problem? Please describe.

This game has rigid non negotiable formatting rules that have a single permitted formatting. Currently checks are in place to check that the formatting exactly matches the format demanded, and rejects PRs until the submitter manages to match the format.
Since there is only a single permitted format, the checking tools could instead perform the required changes when complaining about them (the PR owner have to be able to know that reformatting has been performed).

### Solution you would like.

- Automatically apply astyle formatting to PRs.
- Automatically apply JSON_format formatting to PRs.
- Automatically apply double blank sentence separation to strings. 

### Describe alternatives you have considered.

Continue to be nagged and have to manually redo what the the mandatory tools did but discarded ("manually" typically means manually running these same tools, as the rules applied aren't documented apart from some examples that include some of the rules).

I have intentionally excluded any code modification requirements, as the suggestions given for rejected code occasionally aren't suitable, but rather require some level of redesign, so these decisions should be made by the PR submitter.

### Additional context

The drawback I can see is that the PR submitter would have to pull the modified PR back to their local copy before doing any additional work on their PRs, or git will probably throw a fit about "conflicts".

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/58916

**Comment by Qrox** [comment]
> The drawback I can see is that the PR submitter would have to pull the modified PR back to their local copy

Another problem is that there's a chance Astyle can break the code like in #64662. Not sure how that happened, it may have something to do with the duplicated suggestion bug which is now fixed and how the author of that PR commited suggestions, but it may make automatic formatting undesirable unless it can be avoided.

> Automatically apply double blank sentence separation to strings

This check can be automatically applied for c++ code using clang-tidy, but the clang-tidy check also comes with other code modification changes. The check for json text currently only suggests changes but cannot apply changes. So applying this automatically is not trivial compared to Astyle and JSON formatting.
