### ISSUE TITLE
Kel-Tec SUB-2000 extra short glitch

### ISSUE THREAD

**Issue by guijan** [CleverRaven/Cataclysm-DDA#65092]
### Describe the bug

It's possible to glitch the Kel-Tec SUB-2000's length and make it extremely short.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a Kel-Tec SUB-2000 with the debug menu
2. Saw off its barrel
3. activate it, press modify attached equipment, and fold it
4. activate it again, and press esc to cancel

Your Kel-Tec SUB-2000 is now 129mm long.

### Expected behavior

It should be 329mm long.

### Screenshots

![2023-04-15-135635_1920x1080_scrot](https://user-images.githubusercontent.com/25590950/232228759-e1017253-59fd-4c91-ac8f-f677fb2fdb55.png)

### Versions and configuration

- OS: OpenBSD
- Game Version: 0.G
- Graphics Version: Terminal
- Ingame language: English

**Comment by anoobindisguise** [comment]
this only lasts until it gets unfolded and re folded then its length normalizes.

**Comment by DoctorBoomstick** [comment]
As the guy who gave the SUB 2000 it’s folding capabilities, what’s happening, I suspect, is the following. The base gun item is only, by default, 35 cm long, with the integral folding attachment adding the rest of the length. This was done as simply giving the “folding_stock” flag to the attachment would not shorten the gun to the extent that it can in the real world, not by a long shot. As such, when you fold the gun, the added length from the attachment is removed, leaving the gun’s base length of 35 cm. This means that when the barrel is sawn in game, the game is removing length from the 35cm long gun item, and not taking the attachment into account, thus resulting in this stupidity. I suspect that the gun shouldn’t have the capability to be sawn off in the first place, as doing so would probably result in you axing off the part which locks the barrel by the buttstock, not sure on this though.

**Comment by irwiss** [comment]
IMO sawing off the barrel should really be removed from practically all guns except pipe rifles, double shotguns, lever operated and similar "primitive" guns.

Most ""modern"" semiauto or more complex guns rely on some kind of gas/blowback/blowforward/recoil operation, sawing off part of the barrel will either destroy the gas pipe entirely or lower the pressure and cause the gun to stop cycling

Meanwhile in game data it seems most guns can saw off barrels almost at will

**Comment by guijan** [comment]
I made a small mistake, this also seems to work without sawing off.
