### ISSUE TITLE
Out of date entry in FMS

### ISSUE THREAD

**Issue by Maddremor** [CleverRaven/Cataclysm-DDA#65100]
### Describe the bug

The entry on [nestable container](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions#user-interface) still refers to the pocket system as something new, and as 0.F as being in the future. I think that section can just be deleted since it is no longer relevant to current or future development. The FMS should contain information relevant to suggestions people might frequently make.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

### Additional context

Writing a report about documentation means I have to disregard the bug report form. It feels dirty to do so.

**Comment by GuardianDll** [comment]
Same as note about disabling Z-Levels

**Comment by sonphantrung** [comment]
There's also the 'mp3 playing music' thing, #56045 sorta made it possible

**Comment by GuardianDll** [comment]
/confirmed.
