### ISSUE TITLE
Crash Axe has butchering quality but is unsuitable for butchering?

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#65115]
### Describe the bug

The 'crash axe' item is CUT quality 1, and BUTCHER quality 16. However the minimum CUT quality for butchering appears to be 2 (I could not find the exact date this was added). 

Therefore if you only have a crash axe for a cutting tool (such as after raiding a firewatch tower with your recently started character), and go to try and butcher a corpse (including dismembering a corpse), you are initially shown that you have a suitable butchering tool (implied by the indication of "your best tool with butchering quality"), but are subsequently given the message that you also need a higher cutting quality tool.

### Attach save file

N/A

### Steps to reproduce

1. Start new character with no items.
2. Obtain crash axe and no other tools.
3. Attempt to butcher a corpse.

### Expected behavior

Assuming that the current stats of the crash axe are not in themselves a mistake, then either the presence of the butchering quality should by itself imply that a tool is suitable for butchering - or, if the minimum CUT level was added to allow for items that may supplement butchering but aren't necessarily enough for butchering on their own, there should be a better way of informing the player of why they can't do what it seems like they should be able to.

Alternatively (or rather in addition), the crash axe by itself sounds like it should at least be able to hack a body apart, even if it wouldn't be capable of finer butchery. Perhaps make the "dismember a body" action omit the CUT level requirement?

### Screenshots

![2023-04-16 17_35_10-Greenshot](https://user-images.githubusercontent.com/6471698/232315133-d7f210d4-51f4-42a4-a35f-f96da3372482.jpg)
![2023-04-16 17_35_23-Greenshot](https://user-images.githubusercontent.com/6471698/232315144-5e90fa12-5ed5-430d-87b1-856437e2831b.jpg)
![2023-04-16 17_35_29-Greenshot](https://user-images.githubusercontent.com/6471698/232315150-c5188bd9-1c42-4d5b-ab76-c48e500a21b0.jpg)

### Versions and configuration

- OS: Windows 8
- Version: 0.G stable

**Comment by Procyonae** [comment]
Plenty of items have butchering without CUT 2, it's reserved mainly for decent knives, but dismembering definitely shouldn't require it imo, maybe "butchering X or cutting 2" instead? It could even look at damage instead of flags if that's not a faux pas
