### ISSUE TITLE
Unify items with delayed actions

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#65114]
### Is your feature request related to a problem? Please describe.

Items can have delayed actions where after X time passes from item being activated something happens.

The problem is that there are currently 3.5 different ways to define this in json.

The different methods of delayed actions:

**1\. Using `transform` with charges.** This is used by most grenades.
The ability to do item transform makes it very versatile.
item -> activated by player -> item transforms -> timer starts -> `use_action` on item activates

Problems: 
* Using charges for this is pretty bad thing and it would be great if charges were not used like this.
* the timer runs only while the item is in reality bubble.
* Can't start on its own and must be started by player activating the item (?).

```
"use_action": {
      "need_wielding": true,
      "target": "grenade_act",
      "msg": "You pull the pin on the grenade.",
      "target_charges": 5,
      "active": true,
      "menu_text": "Pull pin",
      "type": "transform"
    },
```

**2\. Using `delayed_transform`.** This is mostly used by cooking things that "mature" on their own.
item is in active state -> age is checked -> item transforms.

This fixes some of the above problems.
* It is based on item age. So no charges involved and time passes out of reality bubble.
* Does not require player activation.

But overall it can't be used in place of `transform` because it can't trigger `use_action`. It can only transform.

```
"use_action": {
      "target": "milk_cream_jar",
      "msg": "You examine the batch and see that the cream has risen to the top, so you seal the jar up for storage.",
      "moves": 50,
      "type": "delayed_transform",
      "transform_age": 21600,
      "not_ready_msg": "The cream has not risen yet."
    }
```

**3\. `countdown_interval`.** Used by few bombs, mi-go armor and flaming arrow.
item is in active state -> timer starts -> specified action is triggered.

This almost has feature parity with the item transform method. Main benefit being that it does not require player activation.

Problems: 
* Can't require wielding the item before activation.
* Transforming item can add many new features to the item (name change, description change, activation msg change etc.).
* Still only runs in reality bubble,

```
"countdown_interval": 86400,
"countdown_action": { "type": "transform", "target": "migo_plate_overgrown", "msg": "The iridescent carapace plate expands as it grows." },
```

**3.5\. `"type": "countdown"`.** There is literally only one item in the whole repository that uses this (dragon hand scroll in MMA mod).
Before anyone says that one of the grenades also uses it: It does not use it because the copy-from always overrides that action.

This is actually exactly same thing as `countdown_interval` ¯\\_(ツ)_/¯. The only difference is that it now requires player activation.

(note: This crashes game because the count_down action deletes the item before the spell finishes casting and the spell tires to read data from the item)
```
"use_action": { "type": "countdown", "interval" : 10, "name": "Unroll", "message": "You unroll the dragon scroll…" },
"countdown_destroy": true,
"countdown_action": { "type": "cast_spell", "spell_id": "learn_ki_strike", "no_fail": true, "level": 0 }
```

### Solution you would like.

One delayed action to rule them all, one activation to time them. One activation to bring them all, and in time bind them.

For player activated timers using item transform as starting trigger is probably best. So transforming sets active=true and the transformed item would have the timer properties.

The timer action code should be based on turns instead of counting down numbers. This is to keep timer working outside of reality bubble.

Then delete the others.

**Comment by KHeket** [comment]
Can this logic be used to solve this issue https://github.com/CleverRaven/Cataclysm-DDA/issues/64975 ? I am not good in code, but its looks like is should solve the problem with grenades, and we must push somehow this changes

**Comment by Hirmuolio** [comment]
Current plans:

`"use_action"` can mean either "player activated this" or "this item was processed" which creates cascading problems that makes everything hard.

* #66161 makes `countdown_action` more usable. But due to the cascalding problems all timer items can't be migrated to that yet.
* TODO: Create `tick_action`. Similar to the other two actions but only triggered by the per turn item processing.
* TODO: Split the actions in iuse and iuse_actor into use, countdown and tick actions. Delete `bool t`. Big job.
* TODO; Cleanup fallout from the new actions. Stop calling `use_action` in item processing. It is only called when player activates item.
