### ISSUE TITLE
Infinite ball bearing glitch

### ISSUE THREAD

**Issue by solidheron** [CleverRaven/Cataclysm-DDA#65119]
### Describe the bug

blade traps require a tiny motor in the recipe but drop a small motor when disarmed in order to build blade trap you have to disassemble the small motor for tiny motor parts

### Attach save file

[Steens-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11242671/Steens-trimmed.tar.gz)

### Steps to reproduce

1: build blade trap
2:set blade trap
3: disarm blade trap
4: disassemble small motor and build tiny motor and keep excess ball bearings 

### Expected behavior

blade traps should drop tiny motors when disarmed or blade traps.

### Screenshots

no screenshots

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 7376b82 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

no additional context

**Comment by hexagonrecursion** [comment]
Words fine in 0.G - both crafting and disassembly use a small motor

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 37 (Thirty Seven); Release: 37; Codename: ThirtySeven; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
