### ISSUE TITLE
Strange behavior w/NPC followers and Marloss/Mycus items

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65121]
### Describe the bug

If you attempt to feed a marloss item to an NPC via the dialog menu, they will either say they don't trust you enough to eat it (correct and expected behavior), or they will say "thanks" and then not take it or eat it.

If you use the debug menu to take control of an NPC follower and eat the items, they will gain both Mycus and non-Mycus mutations instantly. Checking their needs shows no mutagens in their system, which is normal for Mycus, but I'm not sure where the Blob mutations are coming from.

### Attach save file

N/A

### Steps to reproduce

Get an NPC follower with high trust. Try to get them to eat Marloss items. See that it doesn't work. Take control of them via debug, eat the items, get off-brand mutations.

### Expected behavior

NPCs with high trust should eat and be affected by the Marloss items normally.

### Screenshots

![image](https://user-images.githubusercontent.com/94415528/232325236-773563fc-6997-4947-8ca4-638276834d7d.png)
![image](https://user-images.githubusercontent.com/94415528/232325198-2c5c46d8-f820-4871-bf80-b0b61bab77d4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 736c4b6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by LyleSY** [comment]
This came up a few years ago. My recollection from that time was that all of this was hardcoded and super old.
