### ISSUE TITLE
Stormshaper Axes Volumes

### ISSUE THREAD

**Issue by SilverWheatgrass** [CleverRaven/Cataclysm-DDA#65137]
### Is your feature request related to a problem? Please describe.

It's size is like 0.25l too big to fit in the axe belt clip. 

### Solution you would like.

I personally tweaked it for myself but I think it should be shaved a bit to fit the volume requirements

**Comment by GuardianDll** [comment]
Tweak it, volume doesn't respond for damage anyway
Actually I'd like to see a flag, that force the item to spawn in your hands, if it counted as armor, and just add its own "belt" so you can simply wear any summoned item, but with current mechanic attempt to spawn one automatically wear it, which is not good

**Comment by GuardianDll** [comment]
yeah, i mistaked it
I still have nothing againts tweaking it tho
