### ISSUE TITLE
[CR] gh wiki / player wiki / ingame docs / dev docs / documentation in general

### ISSUE THREAD

**Issue by qoreQyaS** [CleverRaven/Cataclysm-DDA#65135]
### Is your feature request related to a problem? Please describe.

RFC: please blast out ideas.

making changes to the gh wiki is tedious as a user who is not authorized to do these directly and those who have to do it because of that.

the current workflow seems to be
- non authorized user ($user) thinks stuff needs to be changed in the wiki
- $user opens an issue, describes the changes and an authorized user has to edit the wiki to reflect those changes.

in general:
- there is ingame documentation
- there is hhg (https://cdda-guide.nornagon.net/)
- there is a (mostly outdated) mediawiki for players (http://cddawiki.chezzo.com/cdda_wiki/index.php/Main_Page)
- there are docs for developers (https://github.com/CleverRaven/Cataclysm-DDA/tree/master/doc)
  - for me there is no visible distinction what belongs in the wiki or in /doc
- there are comments in the c++ code
- there are comments in the json files

### Solution you would like.

i like the idea of having a wiki which is editable by almost everyone, but i understand this means additional administrative expenditure.

hhg is great because it uses actual ig json data which means it doesn't have to be edited directly to reflect changes
this could be leveraged by using c++/json "comments" (json has no comments, but "//" "//2"... is being used as key for comment data) to create documentation

1. get rid of the gh wiki and put everything in /doc (put redirects in the wiki to keep links intact for a reasonable meantime)
    - this leads to existing PR workflow works for the "wiki"
2. generate certain data in /doc from c++/json comment data via CI
3. generate player (old player wiki) & ingame documentation by using such data via templates maintained in the main repo

### Describe alternatives you have considered.

make the wiki editable for every registered gh user (test it and have a look how much spam there really is?)
this only takes care of the gh wiki workflow issue

**Comment by ZhilkinSerg** [comment]
Docs in `/doc` folder are for contributor (and modder) reference, so anyone could see which data structures can be used to create content for vanilla or mods.

***

GH wiki is for developers (both data and code contributors) as mentioned on its main page. We don't want it to be edited by every authenticated GH user. Any contributions to this wiki should come from within CleverRaven organization.

![image](https://user-images.githubusercontent.com/16213433/232397994-e0550f63-95b8-45e7-9133-6cf9b2ea4171.png)

***

HHG is a data viewer for CDDA. It is generated automatically using game data and it does not need user edits other than contributions to its source code (which go through https://github.com/nornagon/cdda-guide).

***

Player wiki http://cddawiki.chezzo.com/cdda_wiki/index.php/Main_Page (which is linked from developer wiki and CDDA site) can be edited by anyone. It is a third party and we do not have any control. Anyone is free to update it or create a new wiki site either manually or using some templates to generate wiki pages from game data. This is outside of CDDA project scope.

![image](https://user-images.githubusercontent.com/16213433/232400885-dfaf5ba4-7a40-4308-8579-bc49e7b968cd.png)

![image](https://user-images.githubusercontent.com/16213433/232400593-6f3b973c-556c-48b8-96f7-0473833cfa18.png)
