### ISSUE TITLE
Winter wilderness spawns only consist of birds

### ISSUE THREAD

**Issue by ferociousdork** [CleverRaven/Cataclysm-DDA#65140]
### Describe the bug

Started in winter, innawoods, and I'm noticing a distinct lack of mammal spawns. Only turkeys, crows etc. seem to spawn.

A quick check of the forest monster groups reveals that in #63513 every entry got `"conditions": [ "SPRING", "SUMMER", "AUTUMN" ]`, except `GROUP_WILDERNESS_FOREST_BIRD`.

Not only does this exclude mammals from spawning in winter, it also removes any seasonal variety (e.g. reindeer previously had [ "AUTUMN", "WINTER" ])

### Attach save file

N/A

### Steps to reproduce

1. Start in the wilderness in winter
2. Walk around and observe spawns

### Expected behavior

Mammal spawns

### Versions and configuration

Recent experimental, innawoods.

**Comment by Karol1223** [comment]
> reindeer

Do me a solid and don't include those. Reindeer aren't widely present in New England nowadays, I've got a PR making them seasonal spawns.

**Comment by ferociousdork** [comment]
> we have regular deer, reindeer, moose, boar, both foxes, coyotes, and wolves active. Is that what you have in mind here?

Yes, sounds good to me.

**Comment by NetSysFire** [comment]
Wolves are no longer present in New England either.

**Comment by NetSysFire** [comment]
Yes. Also I just found out that I created an issue about this: #62507
