### ISSUE TITLE
Graded Steel Descriptions, a Medium and Mild Tangle

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#65143]
### Describe the bug

Not exactly a bug, but the medium steel grade descriptions of the following weapons:

- Katana
- Rapier
- Cutlass
- Kriegsmesser
- Falx
- Broadsword
- Nodachi
- Zweihänder
- Wakizashi
- Arming Sword
- Longsword
- Estoc
- Scimitar
- Jian
- Cavalry Saber

All have the mention of "made of mild steel" while they are supposed to be made of medium steel.

### Attach save file

N/A

### Steps to reproduce

1. Look up the object
2. Look at the description
3. Realize it's wrong

### Expected behavior

Every description being fixed to mention medium instead of mild steel being the material of the weapon.

### Versions and configuration

Latest experimental

**Comment by irwiss** [comment]
Related https://github.com/CleverRaven/Cataclysm-DDA/issues/64598
