### ISSUE TITLE
Segmentation fault crash to desktop while picking up items

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65166]
### Describe the bug

When I am trying to pick up my weilding items - crash happends. It happen for me for a few times before while looting, but this crash I can reproduce

### Attach save file

[1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11263943/1-trimmed.tar.gz)

### Steps to reproduce

1) Load the save file
2) Pick up by "g" all items in the tile with wielding items (see screenshot)
<details>
  <summary>Pick up all items in this tile</summary>

![image](https://user-images.githubusercontent.com/102726167/232837357-a5f7bda8-c209-4786-8bc4-0277a333a56e.png)
  
![image](https://user-images.githubusercontent.com/102726167/232837599-b0f0ce03-9525-4e1d-9602-5cd9c99ffd3d.png)

</details>

3) See segmentation fault crash to desktop
<details>
  <summary>Crash screenshot</summary>

![image](https://user-images.githubusercontent.com/102726167/232837822-de92ebde-bbe5-4497-996d-59467be16e8c.png)

</details>

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: a052de8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11264001/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11264002/debug.log)

**Comment by katemonster33** [comment]
Could not reproduce the error on latest master, the pickup window does not allow you to select the arc welders, saying "does not fit in inventory"

**Comment by RenechCDDA** [comment]
Okay... and this *doesn't* crash when I compile master in visual studio 2019.

 I'm guessing this is one of those compiler-specific bugs?

**Comment by andrei8l** [comment]
`item_pocket::better_pocket()` doesn't satisfy *[Compare](https://en.cppreference.com/w/cpp/named_req/Compare)*. The effect of that failure is implementation-dependent.

Potential patch:
```diff
diff --git a/src/item_pocket.cpp b/src/item_pocket.cpp
index 3ca17aa011..b50f2bfd36 100644
--- a/src/item_pocket.cpp
+++ b/src/item_pocket.cpp
@@ -382,14 +382,14 @@ bool item_pocket::better_pocket( const item_pocket &rhs, const item &it, bool ne
         return false;
     }
 
-    if( rhs.data->extra_encumbrance < data->extra_encumbrance ) {
+    if( rhs.data->extra_encumbrance != data->extra_encumbrance ) {
         // pockets with less extra encumbrance should be prioritized
-        return true;
+        return rhs.data->extra_encumbrance < data->extra_encumbrance;
     }
 
-    if( data->ripoff > rhs.data->ripoff ) {
+    if( data->ripoff != rhs.data->ripoff ) {
         // pockets without ripoff chance should be prioritized
-        return true;
+        return rhs.data->ripoff < data->ripoff;
     }
 
     if( data->rigid != rhs.data->rigid ) {
```

So there were cases where lhs < rhs due to ripoff AND same rhs < lhs due to remaining volume a bit below.
