### ISSUE TITLE
Large characters and crouching.

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65179]
### Is your feature request related to a problem? Please describe.

Characters who are sufficiently mutated can get quite large, like half again as tall as a grown man, and much bulkier. However, these characters are not prevented from hiding in and behind stuff.

### Solution you would like.

Prevent large characters from being hidden when they crouch behind furniture. Also stop them from hiding in boxes. Maybe make a check to prevent large enemies from doing this as well.

Being large has plenty of advantages and relatively few drawbacks. These changes would help sell the idea that you are just a huge dude.

### Additional context

Going prone should probably be unaffected. Being prone is more dangerous, so it's even balanced!

**Comment by Bulletfang** [comment]
Mutations that significantly increase body size have been due for an audit for a while, but I think it would be wise to wait for that until after all the limb stuff has been added. I love the idea of playing as a huge monster, but currently it does little more than add a bit of strength and make wearing clothes a major pain.

**Comment by fairyarmadillo** [comment]
> Mutations that significantly increase body size have been due for an audit for a while, but I think it would be wise to wait for that until after all the limb stuff has been added. I love the idea of playing as a huge monster, but currently it does little more than add a bit of strength and make wearing clothes a major pain.

Fair point, but I should point out that it also prevents you from getting a comfort bonus from most furniture, sitting in a normal vehicle, or going through windows.
