### ISSUE TITLE
Mission "Find someone to clean up the back bay" breaks if all social checks are failed

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#65185]
### Describe the bug

Boris's mission to find five people to clean up the back bay requires you to get the help of five people total. The teamster will work without persuasion, Smokes will give you either one worker or three depending on how much you pay him, and several others can be persuaded. When you reach five, the quest's done.

However, once you've asked someone you can persuade and they've said no, or if you've asked Smokes and paid him for one worker, you can't ask again. And the only guaranteed worker is the teamster. Meaning that if your persuasion skills aren't up to snuff, or you haven't ingratiated yourself to the people you can persuade, you can fail ALL the persuasion checks and end up with two to four total workers, making the quest impossible to complete.

### Attach save file

n/a

### Steps to reproduce

1. Create character with zero social and disadvantages (just to be sure; I encountered this bug with 6 social and no advantages or disadvantages socially).
2. Find the refugee center.
3. Complete the "clear the back bay" mission.
4. Take the "find people" mission from Boris.
5. Save game to savescum.
6. Ask everybody who can be asked, repeating this until everyone says no.
7. Observe that the quest is uncompletable.

### Expected behavior

Possibilities to solve:
--Option to help clean the bay yourself, adding one to the list (this doesn't solve it by itself, because you can still get stuck if you only buy one helper off Smokes)
--Option to assign NPC companions to help (you might need to find three of them, which is still a bit much, but doable)
--Option to ask other survivors again, after a period of time has passed
--Option to pay Smokes for more than just three workers

Paying Smokes is probably the easiest to code. Have him keep the 5 Merch option to hire another worker until the quest is complete (or until you have five), and you can hire as many workers as you like.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 5b32e27 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
You can improve the save scum reproduction efficiency by saving after each rejection answer (and save scum after each accepting one). I don't think it will take many attempts to fail all checks with  a social skill of zero, though.

**Comment by anoobindisguise** [comment]
This is still a problem and should be reopened.
