### ISSUE TITLE
Add "ammo" category to most resorses items

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65182]
### Is your feature request related to a problem? Please describe.

I noticed, that some items can be moved much more fasters than others. And also some of items fulling all the maximun item count of a tile
Maximum volume of a ground tile is 1000L and 4096 items
Example:
You can place 8000 lump of steel on the tile, wich will be counted like 1000/1000L and 1/4096 items count

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/102726167/232986606-0ff380d1-7eb6-4da7-a46a-e38b62d91a26.png)
  
</details>

But you cant place more than 409,60L of wire or 122,88L of glass shards because of limit of 4096 items per tile . This problem also occurs with lots of other items, like cotton/leather straps and others

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/102726167/232987625-6ba2d83a-b899-4c8e-9947-628b55e1283d.png)
![image](https://user-images.githubusercontent.com/102726167/232987383-3b8f1976-9bc7-4f40-a801-27a86aec9a7d.png)
  
</details>

It also makes item transfer much more longer. For example I moved three piles of items from one tile to another:
1) 1000L of lump of steel - 4 seconds
2) 409,60L of wire - 31 minutes
3) 122,88L of glass shards - 31 minutes

I edited as experement wire in Cataclysm-DDA\data\json\items\generic.json by adding

"type": "AMMO",
"ammo_type": "components"

Simular to lump of steel - and now 1 tile can hold 10000 wires, which is counting as 1/4096 item with 1000L volume, so, if there will be 5000 wires - I can still place here items, because 5000 wires will be  counted like 1 items with 500L density, so I can place more here 4095 items with 500L summary volume

<details>
  <summary>Result</summary>
  
![image](https://user-images.githubusercontent.com/102726167/233000717-6edb4171-fb6a-4721-aeb2-56b2f1639b15.png)
  
</details>

And transfering whole tile of wires costs 4 seconds

### Solution you would like.

Edit a lot of resourses with Ammo code, to make it more logical and also speed up transfering. Also add this to coins, bills and lots of items with high counts

### Describe alternatives you have considered.

1) Leave all as it is
2) Remove ammo code from other resorses like lump of steel

### Additional context

If this changes is ok - I can edit most items by myself

**Comment by Zireael07** [comment]
IIRC this (or a variant of this) has been already suggested, multiple times.

**Comment by GuardianDll** [comment]
Abd rejected the same amount of time - charge system should be used specifically for charges, nothing more

**Comment by KHeket** [comment]
> IIRC this (or a variant of this) has been already suggested, multiple times.

I didnt find any issues, can you link them or say the result?

> Abd rejected the same amount of time - charge system should be used specifically for charges, nothing more

So ammo code must be removed from resorses?
And what is abd?

**Comment by Zireael07** [comment]
abd is typo for and

https://github.com/CleverRaven/Cataclysm-DDA/pull/51531 is a PR that tried to do this for currency and was reverted

https://github.com/CleverRaven/Cataclysm-DDA/issues/48937 this is one of the performance issues that these attempts tried to fix

**Comment by KHeket** [comment]
> There's related disucssion at #60885.
Okey, so removing ammo category from items is ok and adding is not
