### ISSUE TITLE
Active Backup Generator furniture doesn't generate power, doesn't produce a part that generates power when disassembled 

### ISSUE THREAD

**Issue by LordZanos** [CleverRaven/Cataclysm-DDA#65202]
### Is your feature request related to a problem? Please describe.

As title, the active backup generator can't be used in any way to generate power. It can't be set up as an appliance and fueled to generate power, and it doesn't disassemble into parts that can be used to generate power. 

### Solution you would like.

We have appliances that generate power(ASRGs), and we have vehicle parts for generating power(alternators, 7.5kW generator). Backup generators should be convertible to an appliance that uses fuel and generates power, and should produce a part that can be used to convert motive power to epower when disassembled, like the 7.5kW generator.

### Describe alternatives you have considered.

More solar panels.

**Comment by LordKaaven** [comment]
Yeah, it is pretty inconsistent that it does not function, when most other items of this type do. Especially since it is deployed and supposedly powering the checkpoint defences.
