### ISSUE TITLE
Item quotas in pocket settings

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65207]
### Is your feature request related to a problem? Please describe.

Currently, you can use pocket settings to, for example, whitelist a pill bottle for aspirin. This is really handy. However, it would be nice if you could attach a quota to that whitelist that would be satisfied if you reached it. 

### Solution you would like.

So for instance, you could whitelist a pill bottle for aspirin until the count reached 20, at which point the whitelist would be temporarily disabled.

This would allow you to set things up so that, for instance, a pocket could contain no more than 4 shotgun slugs, 20 rounds of 9mm, and an adhesive bandage. Or an IFAK pouch could be flagged to hold 2 medical gauze, 1 pill bottle, 5 hemostatic powder, 1 tourniquet, and 1 small bottle. This way the player could set that up with high priority, then be reasonably assured that their character would automatically attempt to stock the pouch automatically as they looted, rather than simply shoving 40 gauze into the pouch and filling it up before any other items could make it in.

### Describe alternatives you have considered.

n/a

### Additional context

It's possible this is made more difficult by some items being charges, and some not. I understand that the charge system is weird.

**Comment by ProfessorBright** [comment]
I'd like to see this feature extended to the various storage zones as well. It would allow me to have my NPCs maintain a stockpile of, for example, sticks and logs for Basecamp A's use, and a second pile containing the excess to be transported to Basecamp B.
