### ISSUE TITLE
Xedra Evolved + magiclysm: spell window too small

### ISSUE THREAD

**Issue by Adomatic** [CleverRaven/Cataclysm-DDA#65211]
### Describe the bug

I am running both XE and magiclysm. If I hit f1 to cast a spell, most of them seem fine, but some of them are too long to fit into the window that displays the spells, and so the requirements kind of pile up at the bottom and then run off the right hand side of the last line, so it becomes impossible to see some of them. This is especially annoying in the case of spells with requirements, where I can't tell why I can't cast them.

### Attach save file

[Ryder-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11290616/Ryder-trimmed.tar.gz)

### Steps to reproduce

Load both magiclysm and XE mods.
Learn some magiclysm and XE spells including e.g. Ion Rifle
Press F1
scroll down to (e.g. Ion Rifle)

Expected result: a big enough window to show me everything about the spell

Actual result: a window where it runs off the end

### Expected behavior

See above

### Screenshots

<img width="923" alt="image" src="https://user-images.githubusercontent.com/57644033/233493934-fddf8bf6-25fa-465f-add4-5297faa74033.png">

### Versions and configuration

- OS: MacOs
    - OS Version: Darwin Ottrageous.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Xedra Evolved [xedra_evolved],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
You are on stable correct? #63705

**Comment by Adomatic** [comment]
Yes. You should be able to see that from the 'Versions and configuration' section, yes?

**Comment by Maleclypse** [comment]
Hopefully the fix to both of your issues will be backported to 0.G - 1 whenever it is released.

**Comment by Maleclypse** [comment]
closed by #63705
