### ISSUE TITLE
Color filter or shader mask for Sprites

### ISSUE THREAD

**Issue by Rimplestilt** [CleverRaven/Cataclysm-DDA#65227]
### Is your feature request related to a problem? Please describe.

Having a separate sprite for color variants is old school, and building architecture for shader usage in CDDA would be really great in general. This would probably take a bit to add, but is a feature i imagine is very useful and desired eventually, and more advanced shader options could really take Tilesets to the next level.

### Solution you would like.

Allow for colorization of sprites. Hairstyles are a great place to start, followed by carpets and the like. This will trim down on the sprite sheet, and make customization of some assets easier in game. 

I think the simple solution is the ability to apply a simple filter on specific sprites that can change their hue, saturation, and brightness. This would probably work okay for hairstyles and sprites with only a single hue.

The more advanced approach would be a sprite color mask, with a copy of the sprite in another channel with RGB values that allow for much greater control of color variation.

### Additional context

I don't know anything about implementing this, but i think it is a capability we should have.

**Comment by fairyarmadillo** [comment]
I realized the other day that having sprite scaling would be really funny for large and small mutants. It might look bad in some tilesets due to the resulting difference in pixel size, but if it's possible to pull it off without looking terrible, that would be cool.

**Comment by Rimplestilt** [comment]
yeah im not sure how scaling would work, but something like that could be used for animals as they grow possibly too. For example, an animal may have a baby and adult form, where as the baby grows, the sprite grows from 50-100%, then changes to adult form. And the adult form would change from 50-100% as well.

I am def most excited for the potential of sprite color masking. sort of like this, but more advanced perhaps.

![dynamic-shaders-for-recoloring-sprites](https://user-images.githubusercontent.com/120688336/233752675-f5560401-9db6-4856-a693-961252b53366.png)

This explains it a bit. I just don't know how difficult the concept would be to implement, if it would be through SDL shaders for CDDa or? https://www.youtube.com/watch?v=4dAGUxvsD24
