### ISSUE TITLE
Disassembling an old watermelon gives fresh wedges

### ISSUE THREAD

**Issue by DarkDaskin** [CleverRaven/Cataclysm-DDA#65224]
### Describe the bug

Disassembling a perishable gives fresh products despite the original item was old.

### Attach save file

[Lauderdale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11298407/Lauderdale-trimmed.tar.gz)

### Steps to reproduce

1. Make a character with a knife and a watermelon.
2. Wait until the watermelon gets old.
3. Disassemble the watermelon.
4. You get fresh watermelon wedges.

### Expected behavior

Disassembly results should inherit freshness from the original item.

### Screenshots

![изображение](https://user-images.githubusercontent.com/200260/233706507-236d7371-0bf7-4547-8f93-24330f634068.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 709df6b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    EZ-Mode Medical [fast_healing]
]

**Comment by Karol1223** [comment]
I'm more curious about the screenshot saying you got 80 wedges from a watermelon... how?

**Comment by DarkDaskin** [comment]
It allows to disassemble multiple identical items at once, but does not show that number in the log.

**Comment by Karol1223** [comment]
Ah, that'd be charges doing that. Yeah, I forgot melons have those. I was worried the freshness calculation somehow started multiplying results.
