### ISSUE TITLE
Subdermal carbon filament not showing on the equipment layers

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#65259]
### Describe the bug

The Subdermal carbon filament suppose to create an layer of outfit which cannot be removed, and provide defences, but they are missing in the latest experimental.
However the multitool cbm still showing up on the equiment menu.

### Attach save file

N/A

### Steps to reproduce

1.Create character
2.Implate Subdermal carbon filament CBM
3.It's not showing on any of the equipment  layer menu

### Expected behavior

Showing up on the various menus like it did in 0.G stable.

### Versions and configuration

latest experimental

**Comment by fairyarmadillo** [comment]
This is not a bug. #62815 reverted it to a non-integrated system.
