### ISSUE TITLE
Solitary power cord on vehicle cannot be removed.

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#65265]
### Describe the bug

If I plug one appliance into the vehicle, and something shoots at the appliance so that the power cord gets damaged and drops onto ground, the other end of power cord on the vehicle cannot be regularly removed. I have to bash it until it breaks or drops onto ground, too.

### Attach save file

[npcneed-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11303008/npcneed-trimmed.tar.gz)

### Steps to reproduce

1. Load the save file.
2. Shoot at the ASRG until the power cord breaks down. ( Note that auto turrets will do the same thing----not necessarily player's fault.)
3. Find that you cannot remove the power cord on the vehicle. And you cannot unrack the bike now.

### Expected behavior

1. I don't think the power cord should exist as an item, since it's somewhat "fake".
2. There should be a way to uninstall the power cord, besides violently bashing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 0.G-1503-ge8a1eafffb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Kamayana** [comment]
You actually can't unrack the vehicle right from the start of the save. Experimenting a bit, it looks like there are two separate bugs here: plugging an appliance into a racked vehicle makes it unrackable, and smashing a power_cable off doesn't remove the part at the other end like it does when unplugging it normally. I'll make sure #64334 fixes these.
