### ISSUE TITLE
John Bailey's zombie kill count appears as a float in dialogue

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#65261]
### Describe the bug

This is a rather minor bug. It's only a matter of game immersion. John Bailey's `npc_val:zkc_john` appears as a float in dialogue.

"I'm up to 10.000000 so far."

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11302942/test-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.
2. Talk to John Bailey, and proceed to the topic `TALK_RC_John_Bailey_ZKC`.
3. Find out the number has a decimal point and 6 following zeros, which is unnecessary in real person-to-person dialog.

### Expected behavior

I would like to see the kill count as a integer.

### Screenshots

![图片](https://user-images.githubusercontent.com/22912139/233822773-4212721c-9697-49bb-a99b-f2c9ffeee3ff.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 0.G-1503-ge8a1eafffb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by gettingusedto** [comment]
the same can be said in BombasticPerks mod
