### ISSUE TITLE
clothings don't have normal durability state

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#65277]
### Describe the bug

In latest experimental, whenever I try to repair some clothings, it always went straight from damaged ( |\ ) to reinforced ( ++ ), vice versa, I can't seem to see a normal state ( || )

### Attach save file

N/A

### Steps to reproduce

1. Create a character
2. You will find all her clothes are in ++ state
3. Damage them by getting in a fight.
4. All damaged clothes will go straight from ++ to |\

### Expected behavior

Have a normal state of equipments ( || )

### Versions and configuration

latest experimental

**Comment by GuardianDll** [comment]
There is no "reinforced" anymore, it's just a 100% hp of an item

**Comment by irwiss** [comment]
|| appears between 1 and 999 damage, currently item damage is simulated (e.g. when item gets damaged by a monster hit, or an attack dings the weapon) in 1000 "chunks" so you'll mostly see || on vehicle parts or stuff generated by mapgen, this might change in the future
