### ISSUE TITLE
Replace Vehicle Part Function

### ISSUE THREAD

**Issue by SilverTemper** [CleverRaven/Cataclysm-DDA#65297]
### Is your feature request related to a problem? Please describe.

Having to take off all the parts of a vehicle tile to replace the damaged frame is tedious and wastes the resources needed to reattach everything.

### Solution you would like.

Being able to simply replace a vehicle part with a part identical in all but damage would alleviate this problem.

**Comment by SeanMirrsen** [comment]
I would rather have a function that automates the process, rather than one that skips it. Bake all the necessary work and resources for deinstalling/reinstalling subcomponents into one action, and do it.
