### ISSUE TITLE
Chunks of unknown material dont drop artifacts

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65303]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/pull/56566 chunks of unknown material was added. And after death they should drop artifact. I killed few of them in game - and there was no artifacts afters its death
I debug spawned chunks - after killing debug spawned chunks they are dropping artifacts
I also create world, hided in btr and wait. After chunks was spawned by the game (not by debug menu) - after killing it they still dont drop artifact

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11323606/test-trimmed.tar.gz)

### Steps to reproduce

1. Spawn with debug menu chunk of unknown material/pulsating chunk of unknown material/resonating chunk of unknown material
2. Kill it by weapon or by debug menu - artifact drop

Naturally, chunks will spawn if the player is outside, but for reproducing being outside during portal storm for too long is deadly. So to get natural chunks (not spawned by debug menu), there is few ways
Fing them during the game, or make needable situation by debug menu:

1. Spawn  Armored Personnel Carrier (БТР in russia), remove 200L tanks and close you like on the screenshot. Also remove roof tile overhead, check screenshot
<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/102726167/234314558-695e6752-d627-4cac-b421-2ad78dab99de.png)

</details>

2. Take by debug "menu debug clairvoyance super"
3. Start by debug menu portal storm
4. Wait for chunk of unknown material, no matter which type - they all shuold drop artifacts
5. Kill it by weapon or debug menu - see no artifact dropped
I also made this situation in attached save file, and also waited until 2 resonating chunks of unknown material will spawn, so you can test it in save file

### Expected behavior

All three types of chunk of unknown material (chunk of unknown material/pulsating chunk of unknown material/resonating chunk of unknown material) should drop artifacts

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 853ea1c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by SariusSkelrets** [comment]
Can confirm

Non-debug chunks won't drop anything despite being expected to always drop an artifact on death

OS: Windows
OS Version: 10.0.22621.1555 (22H2)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/227f527ef25badb2c129f7cd1ae238b3acf42e35 [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: 
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]

Debug invincibility works well for long waits in hostile environments

**Comment by Ramza13** [comment]
So the reason this happens is that monsters spawned with a lifespan don't drop anything on death.  All portal storm spawns have a lifespan so they don't last forever.  Not sure the easiest fix.

**Comment by KHeket** [comment]
> So the reason this happens is that monsters spawned with a lifespan don't drop anything on death. All portal storm spawns have a lifespan so they don't last forever. Not sure the easiest fix.

I don know, should it work, but we have spellcasting system on death, like gazoline zombies, wich will explode after death, and we have, as example, temple with artifact and mines with four Amigara horror, after which death arifact will be spawned, so is it possible to combine spellcasting upon death + artifact spawning effect?
