### ISSUE TITLE
Tilesets using ascii are much slower than graphical tilesets or turning tiles off

### ISSUE THREAD

**Issue by ZombieRoboNinja** [CleverRaven/Cataclysm-DDA#65312]
### Describe the bug

I'm playing on the windows tiles version of 0.G. When using any tileset that uses ascii like asciitiles, Larwick Overmap, or SurveyorsMap, the game runs significantly slower than using any graphical tileset, like Ultica, MSXotto+, RetroDays, or setting the 'Use Tiles' option in the graphics tab to False. This slowdown is the most obvious in areas with a lot of enemies and items using a zoomed out view. Just to be clear, the issue isn't that there is slowdown or lag, the issue is that asciitiles experiences significantly more lag than the other tilesets (or using no tileset).

### Attach save file

N/A (This problem relates to the performance of a tileset, not an issue with a game mechanic or crash)

### Steps to reproduce

1. Using any graphical tileset, go to an area with lots of items, like the center of a city.
2. Hold down a movement key to walk in a straight line, noting how much real time it takes to get from 1 point to another.
3. Switch to the asciitiles tileset. Match the zoom level from the graphical tileset. Starting from the same point, walk the same direction. The pauses between steps are significantly longer, and the game is much laggier.

### Expected behavior

If anything, I figured lower resolution tilesets without animations should perform better, not worse. Given the same zoom level, asciitiles should perform the same or better than a high resolution tileset. And the fact that the option 'use tiles' set to false performs just as well as a graphical tileset, but asciitiles performing much worse tells me something weird is happening.

### Versions and configuration

OS: Windows 10
Game version: 0.G d6ec466 2023-03-01-0054
Graphics version: Tiles
Mods loaded: Dark Days Ahead, Disable NPC Needs, Portal Storms ignore NPCs, No Fungal Growth, Bionic Professions

### Additional context

I've tested this out on multiple worlds and save files using 2 different desktop computers and 1 laptop and got the same result. I tested version 0.G, experimental, version 0.F, and version 0.E. The issue was not there in 0.E, but has been in the game since 0.F. I'm not sure which build of the game the issue started.

**Comment by SeanMirrsen** [comment]
Are you making sure the view covers a similar area in your testing?

ASCIItiles is slower for me than RetroDays as well, but mostly because it's a smaller font by default, so at default zoom it shows a much larger area. Since the engine performance is dependent on how many glyphs are being rendered, not as much their size (which affects mostly memory I believe), and zoom level is based on the size of the glyphs, then it stands to reason that a smaller tileset will cause a lot more area to be shown, and a lot more glyphs will be rendered, thus degrading performance.

**Comment by Golfavel** [comment]
I cannot reproduce this; ASCIITiles performs identically (within margin of error) to NeoDays when at exact same zoom level (26 tiles above the camera).
