### ISSUE TITLE
Dead Impaled XEDRA officer turns into 1000 Drinking Glasses

### ISSUE THREAD

**Issue by Granitier** [CleverRaven/Cataclysm-DDA#65314]
### Describe the bug

on the entrance to the physics lab, what I believe to be a new encounter of dead XEDRA soldiers with there gear are present, the mercenaries all had gear except for the officier, who upon using the deconstruct furniture menu turned into a 1000 drinking glass 

### Attach save file

N/A

### Steps to reproduce

1. find the encounter
2. find that the officer has no gear yet the mercenaries do
3. use the deconstruct furniture in the construction menu on the dead impaled officer
4. he turns into 1000 drinking glasses 

### Expected behavior

I expected that he would have a special version of the loot of the soldiers around him, but did not, didn't expect to be able to deconstruct him, Maybe it would have given me his gear? got drinking glasses 

### Screenshots

![image](https://user-images.githubusercontent.com/131863678/234531270-fac5f552-39f4-4b56-af8f-687270495faa.png)

### Versions and configuration

Window 10
Version ee6be48

**Comment by NetSysFire** [comment]
You have not properly filled your "Versions and configuration" box. This information is crucial here.

**Comment by Qrox** [comment]
Let me guess, someone used "glass" as the id for deconstruction results?

Yep:

```
data\json\furniture_and_terrain\furniture-alien.json:
  704      "coverage": 100,
  705      "flags": [ "TRANSPARENT", "ORGANIC" ],
  706:     "deconstruct": { "items": [ { "item": "glass", "count": 1000 } ] },
  707      "required_str": -1,
  708      "bash": {
  ...
  727      "move_cost_mod": -1,
  728      "coverage": 100,
  729:     "deconstruct": { "items": [ { "item": "glass", "count": 1000 } ] },
  730      "required_str": -1,
  731      "bash": {
  ...
  748      "coverage": 100,
  749      "flags": [ "TRANSPARENT", "ORGANIC" ],
  750:     "deconstruct": { "items": [ { "item": "glass", "count": 1000 } ] },
  751      "required_str": -1,
  752      "bash": {
```

```
data\json\items\generic\dining_kitchen.json:
  307      "type": "GENERIC",
  308      "category": "container",
  309:     "id": "glass",
  310      "name": { "str": "drinking glass", "str_pl": "drinking glasses" },
  311      "symbol": "U",
```

**Comment by Saylol222** [comment]
lmao
