### ISSUE TITLE
Removing a shoulder strap from a gun keeps its clothing status

### ISSUE THREAD

**Issue by Saylol222** [CleverRaven/Cataclysm-DDA#65317]
### Describe the bug

title says all

### Attach save file

[Timpson-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11334494/Timpson-trimmed.tar.gz)

### Steps to reproduce

1. put shoulder strap on a gun
2. remove the strap
3. still be able to put it on

### Expected behavior

not being able to wear the gun

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Google; Model: octopus; Release: 11; Incremental: 9844704; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

looking at the mods again removes clothing status

**Comment by irwiss** [comment]
Will be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/65300

**Comment by Saylol222** [comment]
k
