### ISSUE TITLE
Flashlight Pocket Cannot Accommodate Flashlight + Light Battery

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#65319]
### Describe the bug

The flashlight pocket added in #64932 cannot accommodate a flashlight if it is using a light battery (which is their standard battery).  The flashlight + light battery weighs more than the pocket allows.  It does work when using an ultra-light battery, as that lowers the overall weight.  This is presumably a mistake, since flashlights spawn pretty much exclusively with light batteries, and most people probably don't even know they could use an ultra-light battery.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a flashlight and an army helmet
2. Try to insert flashlight in helmet.  Observe flashlight fits in helmet pocket correctly.
3. Remove flashlight and load it with a light battery.
4. Attempt to put flashlight in helmet pocket again.  Observe that it cannot fit, because it weighs too much.
5. swap out light battery for ultra-light battery.  Observe that it can now fit in the pocket.

### Expected behavior

There's no indication in the PR that this was intentional.  I assume they didn't test it properly, I'm going to assume they spawned an empty flashlight, saw that it fit in the pocket, and assumed it was fine.  They probably didn't test it with the battery in there.  If the intention is to accommodate a flashlight in your helmet, it should do so with the battery that spawns in it 99% of the time.  IE: it should allow for a flashlight with a light battery to fit in the helmet pocket.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 531e7be [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    No Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Bombastic Perks [bombastic_perks]
]

### Additional context

I only tested it on the Army helmet, specifically.  It's possible other helmets are not broken, but I'm going to assume they just copy-pasted the pocket data among all the affected helmets.  So, probably it won't work with any of them, I just didn't test any of the other helmets.

**Comment by Kantonine** [comment]
I've noticed this in my save. The flashlight pockets dimensions are the same for both hard hats and tactical helmets, with airsoft helmets having no pocket as well.
