### ISSUE TITLE
Segfault repeatable to a limited degree (Attacking acid ants at lumber mill who are attacking npc's)

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#65325]
### Describe the bug

Fighting ants causes a segfault generally it's on my action/turn attacking the ants that causes it rather than it happen by itself not that i've verified that.  

### Attach save file

[Zakhadia_BigCity_copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11337138/Zakhadia_BigCity_copy-trimmed.tar.gz)

### Steps to reproduce

Climb over the fence start fighting the acidic ants was trying to help out the lumber mill but it's probably a lost cause, but i didn't know that at the time of arriving.

### Expected behavior

Fighting ants without it segfaulting and probably meet my demise as acid ant fights seldom go well. 

### Screenshots

![image](https://user-images.githubusercontent.com/5264667/234700091-e2978b01-ef32-42eb-b524-0645b979146b.png)
![image](https://user-images.githubusercontent.com/5264667/234700112-17e961ad-3fb5-4de4-b456-a8ce044d1677.png)
![image](https://user-images.githubusercontent.com/5264667/234700142-6f556dac-064e-4082-bdbe-d4656d69cd5d.png)
![image](https://user-images.githubusercontent.com/5264667/234700149-e18fbbc5-a6c7-43de-a195-32bb2da663c6.png)

### Versions and configuration

- OS: Windows
    - OS Version: 7 64bit
- Game Version: 01203da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Mythical Martial Arts [MMA],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Mining Mod [Mining_Mod],
    Dorf Life [Dorf_Life],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Ignore the mining mod errors i've already reported them to Chaosvolt.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11337143/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11337145/debug.log)

**Comment by RenechCDDA** [comment]
This was fixed by #65466
