### ISSUE TITLE
behavior of difficulty values in character creation

### ISSUE THREAD

**Issue by hr-shafiei** [CleverRaven/Cataclysm-DDA#65333]
### Describe the bug

im talking about the values which determines the difficulty in character creation.
for example, near-sighted reduces the lifestyle value by 1 but Irreparable also reduces it by 1 while it has a much stronger negative impact on difficulty .
and there is many more
i think it needs a whole rework

### Attach save file

-

### Steps to reproduce

-

### Expected behavior

-

### Versions and configuration

-

**Comment by ZhilkinSerg** [comment]
You can easily modify `points` value of mutations with `starting_trait` = `true` and create a pull request with your proposed changes.

https://github.com/CleverRaven/Cataclysm-DDA/blob/5f2a60d7e3ee4756ad6acc4906acce930730cec6/data/json/mutations/mutations.json#L262-L273

**Comment by Proxima-b** [comment]
Aren't those points belong to the old point based char creation system? 
The new evaluation system needs a field.

**Comment by hr-shafiei** [comment]
im gonna close this and post a new issue to explain better

**Comment by ZhilkinSerg** [comment]
> im gonna close this and post a new issue to explain better

You can edit current post.
