### ISSUE TITLE
cold resistance trait disables weak stomach

### ISSUE THREAD

**Issue by hr-shafiei** [CleverRaven/Cataclysm-DDA#65330]
### Describe the bug

cold resistance trait disables weak stomach.
is this unintentional or is that a thing ?
i mean, i myself am pretty strong against cold but im not sure about the quality of my stomach !

### Attach save file

-

### Steps to reproduce

-

### Expected behavior

-

### Versions and configuration

-

**Comment by Fris0uman** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/issues/65330
