### ISSUE TITLE
*unhappy Cannibal noises* scraps of human meat turn to normal meat upon dehydration

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#65344]
### Describe the bug

Dehydration Scraps of Human Meat returns ... normal dry Meat.

### Attach save file

N/A

### Steps to reproduce

Get Scraps of Human meat
Get Dehydrator and maybe a hotplate
Make dehydrated meat with scraps of human meat
Realize it turns to normal meat 
*unhappy cannibal noises*

### Expected behavior

Well Human Meat ... upon drying should not turn ... unhuman?

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/234977825-2dd3bd65-b203-48df-9bdf-da617d1ecd2f.png)
![image](https://user-images.githubusercontent.com/89189872/234977906-ffd8c29f-c7b2-4757-b10c-7a67003ce7cd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 48ed876 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Qrox** [comment]
When you look at the item description of the dehydrated meat does it say it contains human flesh?

**Comment by estebandellasilva** [comment]
> When you look at the item description of the dehydrated meat does it say it contains human flesh?

![image](https://user-images.githubusercontent.com/89189872/235170336-0fbba23a-c182-49f6-823b-944a9c392fa8.png)
no

**Comment by Qrox** [comment]
So the smoking and crafting code replaces components with their "cooks_into" counterpart without adding component information to the counterpart, and scraps of human meat "cooks_into" cooked scraps of meat, so as a result dried scraps of human meat has normal cooked scraps of meat as the component. Probably need to add the original item as the component of the "cooks_into" item to fix this.
