### ISSUE TITLE
Annoying numpad_navigation feature is causing distress for players, should be removed

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#65349]
### Describe the bug

Earlier today I found myself cannot type any quantity in the (d)rop and (g)rab menu, and there was a "Numpad On" label on the upper-right corner of the menu:
![image](https://user-images.githubusercontent.com/33013708/235006841-f7c04bc8-d867-42ce-b3af-72b1624e6db3.png)

After hours of investigation, I found out that there was a value in uistate,json called numpad_navigation:
![image](https://user-images.githubusercontent.com/33013708/235007042-6b304ede-178a-4e70-a33d-28b3b0c937cd.png)

By setting it to false (I have no idea why it had been set to true) and reload the save, I can type the quantities in these menu as usual.

So I shared my finding on the discord community, I found out that other player has been plagued by this issue, even wastes huge amount of time re-mapping controls.

I don't think anyone would use numpad key to navigate the menus, this feature should be removed.

### Attach save file

N/A

### Steps to reproduce

*

### Expected behavior

Not having the numpad_navigation for menus.

### Versions and configuration

latest experimental

**Comment by Proxima-b** [comment]
Or at least provide a method of turning it off in-game

**Comment by Kamayana** [comment]
There is an in-game setting for it, F5 by default:

![image](https://user-images.githubusercontent.com/6759778/235013043-c5a8f904-c9be-4d0c-a698-6ea09f152248.png)

I myself use the numpad for menu navigation, so I would not want it removed.

**Comment by Proxima-b** [comment]
Well that settled it
