### ISSUE TITLE
"place in inventory" of wielded item bypasses move cost for short rope

### ISSUE THREAD

**Issue by angryreindeer** [CleverRaven/Cataclysm-DDA#65348]
### Describe the bug

I will test this further in debug mode when I have a chance. In this specific case, I have a nailboard and my only worn container is a short rope. When putting away the nailboard by pressing 'w', the "place in inventory" option has a move cost of 210. Retrieving it, or placing it in the container, the cost is 1936. It does not perform this way with a messenger bag, but an AR-15 with a short rope acts in the same way as a short rope with a nail board.
![Screenshot from 2023-04-27 16-39-51](https://user-images.githubusercontent.com/132019884/235003214-c01a4326-40fa-4def-953e-ab6a3b7f7cdb.png)
![Screenshot from 2023-04-27 16-40-06](https://user-images.githubusercontent.com/132019884/235003230-585e92f4-2352-435a-88d9-f1d8899cc6c0.png)

### Attach save file

N/A

### Steps to reproduce

- Start a game and activate debug mode.
- Spawn a short rope.
- Wear the short rope.
- Spawn an item.
- Wield the item.
- Unwield the item by pressing 'w' and note the move cost for each option.

### Expected behavior

Storing an item in a container should be the same regardless of the used context menu.

### Versions and configuration

OS: Debian 11
Game Version: 2b55182 (experimental)
Graphics Version: tiltes - "UNDEAD_PEOPLE (NEW VERSION)"
Ingame language: English
Mods loaded: None (this was tested in the tutorial, without any mods)

**Comment by GuardianDll** [comment]
#65062?
