### ISSUE TITLE
Cannot type number to specify quantities

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#65345]
### Describe the bug

Usually if I want to pick up a certain bumber of things, I would type a number and input right arrow key to pick up, but this method is broken somehow.

### Attach save file

[Slum.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11347688/Slum.zip)

### Steps to reproduce

1. Load the save
2. try to pick up 10 of the 36 mutant meat
3. type 10 and hit → arrow key
4. still shows picking up all 36 chunks of meat

### Expected behavior

*

### Versions and configuration

c3f26cd

**Comment by GuardianDll** [comment]
Try to use `!`?

**Comment by Proxima-b** [comment]
> Try to use `!`?

Isn't that the key for safe mode? how is it related?

**Comment by Proxima-b** [comment]
idk why, but deleteing the uistate.json seems to fix the issue

**Comment by GuardianDll** [comment]
I meant instead of trying to print the number as it is, press `!` abd then trying to write a number

**Comment by Proxima-b** [comment]
> I meant instead of trying to print the number as it is, press `!` abd then trying to write a number

I already found out it's because of the numpad navigation (that I don't know how to turn off)

**Comment by andrei8l** [comment]
> I already found out it's because of the numpad navigation (which seems has no way of turning off)

There's a hotkey for it

![Screenshot from 2023-04-28 05-46-32](https://user-images.githubusercontent.com/68240139/235042256-11c3aa20-5e38-4b16-b740-8c4247fe7793.png)
