### ISSUE TITLE
Math function displays different behavior depending on system region format

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#65351]
### Describe the bug

Dealing with a bug report in Mind Over Matter (my psionic powers mod) which makes heavy use of math function in the various powers: other people were reporting that the max spell level for their powers was zero--it's supposed to follow the formula { "math": [ "( u_val('intelligence') * 1.5 )" ] }--and that other similar errors occurred in the other math-dependent JSON fields such as max_damage and min_range. On investigation, it was found that both people reporting the bug had their region formatting (not system language) in non-English languages, one in Russian and one in Polish. On changing my region formatting to Polish I was able to instantly replicate the bug. 

### Attach save file

[Hidden Timber-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11349065/Hidden.Timber-trimmed.tar.gz)
Mind over Matter: 
[MindOverMatter-main.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11349069/MindOverMatter-main.zip)

### Steps to reproduce

1) Start with regional setting in English (World)
2) Load above game, attempt to use a power.
3) Max level 12, 1.5 times Intelligence of 8 as expected.
4) Fully exit game, change regional setting to Polish (Poland)
5) Load above game again, attempt to use a power
6) Math function fails, max level is 0.

### Expected behavior

Math function is consistent across region formats.

### Screenshots

Region format in English:
![image](https://user-images.githubusercontent.com/120433252/235032552-6070d1fd-5f86-40c9-961c-f9578ea26f5e.png)
Region format in Polish, note range and damage also affected:
![image](https://user-images.githubusercontent.com/120433252/235032744-af6b503a-8d4b-437d-a8ba-ea9b53558f54.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 45a7c24 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter]
]

### Additional context

I also tested a few other region formats:

Russian (Russia): Fails
Japanese (Japan): Works correctly
German (Germany): Fails
French (France): Fails
Chinese (Simplified, China): Works correctly
Hebrew (Israel): Works correctly
Indonesian (Indonesia): Fails
Spanish (Spain): Fails
Korean (Korea): Works correctly

**Comment by andrei8l** [comment]
Please test with the builds from [this release](https://github.com/andrei8l/Cataclysm-DDA/releases/tag/cdda-experimental-2023-04-28-0428). I can only confirm that the PR above fixes the problem on linux.

**Comment by Standing-Storm** [comment]
With the above Windows MSVC build and region format set to Polish, the math calculates correctly: 
![image](https://user-images.githubusercontent.com/120433252/235167158-76c799b1-513c-467c-aba7-3d94b716600b.png)
