### ISSUE TITLE
Crafting menu freezes on nested recipes

### ISSUE THREAD

**Issue by lyxerexyl** [CleverRaven/Cataclysm-DDA#65395]
### Describe the bug

Crafting menu freezes when your cursor was moving to nested recipes holder (android and low-end laptop)

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

https://user-images.githubusercontent.com/121940682/235374111-b72790cf-fbf8-49bd-9767-8ffcfbb78489.mp4

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: OPPO; Model: CPH2269; Release: 11; Incremental: 1680510347543; 
- Game Version: 0.G [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by mqrause** [comment]
Probably duplicate (and very extreme case) of #62739
