### ISSUE TITLE
Ethanol Burner CBM being so good at it's job it can kill the user

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#65393]
### Describe the bug

Ethanol Burner CBM accepts alcohols. When burning it the player gets heated so much they start getting damaged from heat.

### Attach save file

N/A

### Steps to reproduce

1. Install Ethanol Burner CBM
2. Pour Riesling alcohol into Internal Ethanol Tank
3. Activate the bionic with empty bionic power

### Expected behavior

I expect to not have my limbs burned from using a non-faulty bionic.

### Screenshots

![image](https://user-images.githubusercontent.com/77662682/235371714-5e5c67ea-7f7c-4092-bf23-2dbd239a62e5.png)
![image](https://user-images.githubusercontent.com/77662682/235371729-327837b5-4447-4b09-9b37-c94626ac0841.png)
![image](https://user-images.githubusercontent.com/77662682/235371777-2f6b0a8b-8e85-4cbb-b7f1-3d0b9aa4027b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 45a7c24 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Bombastic Perks [bombastic_perks]
]

**Comment by bocchisaimu** [comment]
This issue is related to #62557.
