### ISSUE TITLE
Game crashes constantly without a crashlog

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#65407]
### Describe the bug

I've gotten into a state in the game where the game will completely crash without any sort of evidence why a few moves after the current save was made. I've attached the save file where it happens. The character is currently in a mutable microlab. There is no crash log.

### Attach save file

[Stony Creek.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11364234/Stony.Creek.zip)

### Steps to reproduce

1. use attached save.
2. take a few steps in any direction.
3. crash.

### Expected behavior

no crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 3010c62 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by andrei8l** [comment]
/confirmed `item::energy_consume()` gets stuck in an endless loop after one of the UPSes runs out of battery. Introduced by #65289, but AFAICT the buggy code has been there since #63978.
