### ISSUE TITLE
Free items from NPC's if sold leather backpack

### ISSUE THREAD

**Issue by VolleyballofDeath** [CleverRaven/Cataclysm-DDA#65406]
### Describe the bug

When a empty leather backpack was sold to an NPC they would proceed to immediately drop it after the trade was complete, any item below the price of the leather backpack could be taken for free, such as a 72/100 lighter in my case
[North Amherst-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11363268/North.Amherst-trimmed.tar.gz)

### Attach save file

[North Amherst-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11363271/North.Amherst-trimmed.tar.gz)

### Steps to reproduce

1. Get a leather backpack
2. trade it to NPC for items
3. get backpack back
4. profit

### Expected behavior

The NPC either does not accept or does not drop the backpack

### Screenshots

Not Applicable

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The NPC in question also refuses to pick up weapons because of a lack of space hence why I was trying to give it a backpack

**Comment by fairyarmadillo** [comment]
If this is an allied NPC, they will always trade you anything for free. It's only neutral NPCs that you actually need to barter with.

If you want them to use the backpack, walk into them and choose "sort inventory" while it's under their feet, or go into the dialog menu and tell them you want them to use an item, then choose the backpack. They should put it on.

**Comment by Omnikron13** [comment]
It might be a nice lil QoL improvement if you were able to select items your character has from that 'Sort armor' screen, rather than have to go through the dialogues or drop it on them first. Would cut out a few keystrokes and consolidate a bit of functionality into one interface.

**Comment by VolleyballofDeath** [comment]
It is an allied NPC
