### ISSUE TITLE
Auto Butcher uses "Quick Butchery" rather than "Dismember Corpse".

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#65402]
### Describe the bug

When setting auto pulp/butcher to "Autobutcher", your character uses the quick butchery option, rather than the quicker "Dismember" option. I can only assume this is because the "Dismember" option is a newer one, and autobutcher was never switched over to it.

### Attach save file

n/a

### Steps to reproduce

1. Wear a watch and spawn in a scalpel.
2. Kill some things.
3. Check your butchery options to see how long each option takes.
4. Turn on autobutcher.
5. Step onto one of the corpses.
6. Monitor the time and see how long the butchery takes.
8. Notice that the time elapsed is equal to "Quick Butchery" option rather than "Dismember".

### Expected behavior

When you're trying to autobutcher acid-filled corpses to put them out of commission, you're not trying to save any of the parts; you just want to cut them up so they can't get up again. Your character should use the quickest option available, leaving "Quick Butcher" for situations like, "I've just killed a bear, but I don't have a butchering rack, and anyway, I can't preserve that much meat before it spoils."

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: a825587 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Omnikron13** [comment]
If the sole reason that the 'butcher' auto-option (and kinda by extension the 'dismember' (sub)option) is to be used is basically a slower and more convoluted pulp you have to do for acid filled corpses, might it not be a better UX improvement to do something like add a 'dismember instead' option to the 'Pulp acid filled corpse?' dialogue?

(Does kinda raise the question of if dismembering should also be possible from adjacent tiles like pulping too imo, but I think that's rather getting into the weeds over what exactly 'pulping' actually involves and why it's faster than dismembering, and possible from farther away... =P)

The 'butcher' auto-option should probably be renamed no matter what tbh, or at least be more specific in the description, as 'Butcher' is also the exact name of an action/keybind which brings up a menu which has like half a dozen options in it.

**Comment by chaoticidealism** [comment]
> might it not be a better UX improvement to do something like add a 'dismember instead' option to the 'Pulp acid filled corpse?' dialogue?

Yeah, but that's more of a feature request, really. And more complicated than just switching the auto-butcher option to Dismember.

**Comment by Omnikron13** [comment]
> > might it not be a better UX improvement to do something like add a 'dismember instead' option to the 'Pulp acid filled corpse?' dialogue?
> 
> Yeah, but that's more of a feature request, really. And more complicated than just switching the auto-butcher option to Dismember.

Oh yeah, definitely. I actually came across this because I was gonna put that feature request in.

Switching autobutcher to an action which is actually kinda a black sheep of the 'butcher' menu raised some questions for me though. Like, if the only reason to do that butcher option anyway is as a 'sepcial case pulp', is it really the best fix to do that? It results in a niche option buried under 'autobutcher', which isn't really butchering, as the solution to minimise busy work for the player, doesn't it?
