### ISSUE TITLE
Easier Debug Building

### ISSUE THREAD

**Issue by Raygaming4483** [CleverRaven/Cataclysm-DDA#65410]
### Is your feature request related to a problem? Please describe.

I like to build stuff like massive structures or areas for roleplaying but building takes hours for me since you would need to change tile by tile in debug and if I activate debug hammerspace and crafting virtuoso building will be limited with requirements in where you place them so it'll take even longer time

### Solution you would like.

So if possible can you please add a multi tile building feature like you toggle something like the ID dirt everytime you click or move the pointed tile will transform into a dirt or anything you selected?And also the overmap editor can you please bring back the previous one with the filters and everything rather than this new scrolling?Its hard to find the mapgen that I want since I need to scroll than just put the mapgen ID in the filter

### Additional context

![Screenshot_2023-05-01-20-47-17-19_a77f7b094295b5a083bf400fa615cbfb](https://user-images.githubusercontent.com/56256886/235453794-0f5a41ef-c102-45b0-b61b-8c8a52c1c680.jpg)
![Screenshot_2023-05-01-20-47-12-24_a77f7b094295b5a083bf400fa615cbfb](https://user-images.githubusercontent.com/56256886/235453821-1bf2efa4-8be1-41f0-b706-d7ee918e6408.jpg)
![Screenshot_2023-05-01-20-46-38-04_a77f7b094295b5a083bf400fa615cbfb](https://user-images.githubusercontent.com/56256886/235453856-75379769-870f-4ecd-a320-b7b504e780b7.jpg)

**Comment by Qrox** [comment]
You can select multiple tiles in the map editor but admittedly the controls are not the most intuitive. I think you can press tab to switch to multi-tile selection and use direction keys to change the selection size, and you can open the keybindings menu to see all supported actions. A paint mode using mouse might be more intuitive but that is not currently supported AFAIK.

You can disable android native UI in the settings which should change the UI in your second screenshot back to the previous game UI.

**Comment by Raygaming4483** [comment]
@Qrox Thanks for the tip!😃
