### ISSUE TITLE
Purifier is Way More Powerful than It Should Be

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#65428]
### Describe the bug

During my research on how the new mutation system works (and how to get rid of the obligatory "Frail" mutation from the "Abandoned" start) I've discovered several issues with the "purifier" and its routine:
1) it is way more powerful than it should be, capable of erasing multiple mutations per attempt;
2) it does not honor the "phenotype" system, erasing all mutations indiscriminately;
3) it is "hell-bent" on erasing, performing the task even if there is not enough of it left (I understand, a 100 units per attempt are required, however, it is doing its job even with 12…20 units left).

### Attach save file

[Silver Hill-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11370514/Silver.Hill-trimmed.tar.gz)

### Steps to reproduce

There are all the needed components in the inventory. Mutations "Fast Reflexes", "Fleet-Footed", "Light Step", "Pretty", "Quick", "Weak Scent", "Addictive Personality", "Frail", "Heavy Sleeper", "Lactose Intolerance", "Lightweight", "Meat Intolerance" and "Weak Stomach" are made erasable (the "base trait" flag has been removed), the other ones, not associated with physical condition ("Stylish", "Squeamish", "Truth Teller", "Slow Reader")  have been left with "base trait" intact and are protected from erasing.

Steps:
1. Consume "purifier" and inject "mutagenic catalyst".
2. Do something while waiting for the process to unfold.
3. Observe the purifier erasing all the mutations left and right, sometimes 2-3 per attempt, while granting only 100 "instability" (indicating that it counted only as one mutation, not three).

### Expected behavior

I expect the purifying process respect and acknowledge the "Phenotype" system and only erase negative mutations, as long as we are not "over budget".

I also expect a purifier to not be so strong and only erase one mutation per attempt, adding 100 instability per each mutation, not attempt.

Finally, I expect purifier to actually stop when there is not enough of it left (less than 100 units), not keep doing the whole process as long as it has anything to erase.

### Screenshots

Starting point:
![zealous_purifier_01](https://user-images.githubusercontent.com/125039757/235605919-f67c431e-7edc-421a-ba9e-ffd54ea51e25.png)
Here we go!
![zealous_purifier_02](https://user-images.githubusercontent.com/125039757/235606031-2df4d2ff-5906-407f-8383-bc5fb83ef8d7.png)
Our first attempt. Three lost mutations in one go!
![zealous_purifier_03](https://user-images.githubusercontent.com/125039757/235606100-67ad5fe1-737a-411f-8f24-8a8e31834be9.png)
And it continues…
![zealous_purifier_04](https://user-images.githubusercontent.com/125039757/235606262-4284f479-7d5e-4545-a135-b9b9aeb420e0.png)
At this point we've lost our "Human Purification" indicator. Surely, this must mean the purifier has ran out of juice…
![zealous_purifier_05](https://user-images.githubusercontent.com/125039757/235606350-5354cff9-f894-4ac6-84df-4e9bf3b21fa6.png)
Yep! Only 15 units remains. Oh, and BTW, these 6 mutations have added only 200 instability. Seems legit: purifier consumed has turned into instability "unit per unit".
![zealous_purifier_06](https://user-images.githubusercontent.com/125039757/235606536-5e2dd07f-0e66-420b-b3f0-137680de0f5b.png)
Wrong! Still going, even with 15 units of purifier left!
![zealous_purifier_07](https://user-images.githubusercontent.com/125039757/235606876-1ff352d9-a09c-4e2b-81bd-a7c5674e9d05.png)
Here is what it looks like now… 
![zealous_purifier_08](https://user-images.githubusercontent.com/125039757/235607041-66757b51-5c31-4038-93ae-272df2f2ec0d.png)
And it only consumed 8 purifier units (or, most probably those 7 units were simply washed away naturally, making these mutations free). Time to call it a day and go to bed.
![zealous_purifier_09](https://user-images.githubusercontent.com/125039757/235607195-3a203cd1-e088-4915-8ade-9c1358dfa82b.png)
It is still going!!! Four mutations this time! The game even acknowledges that it "lacks primer". Does not stop purifier from doing its job, now totally for free.
![zealous_purifier_10](https://user-images.githubusercontent.com/125039757/235607507-7e9389ed-ee76-4195-ab24-478bde668674.png)
It completely erased each and every available mutation, apart from "Lactose Intolerance" (that is somehow also protected, maybe because it is a starting perk that can not be gained by mutation system and thus exempt from the whole process altogether)
![zealous_purifier_11](https://user-images.githubusercontent.com/125039757/235607959-e5fced9c-43dd-4d19-a0c4-e073a03e7216.png)
Oh, and by the way, we still have 5 units of purifier left. Not that it has anything to purify now…
![zealous_purifier_12](https://user-images.githubusercontent.com/125039757/235608706-a341e01d-0800-4f29-8942-06a9bdf63063.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ffc75ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

None.

**Comment by Venera3** [comment]
Differentiating between negative/positive traits needs it to incur instability on trait removal, otherwise it's a freebie.

Removing one trait on attempt is reasonable.

**Comment by Alm999** [comment]
Well, I am of the opinion that *any* change in mutation list shall incur instability, no matter targeted or not (because it *is* an intrusion in the current character's DNA and damages it). And if a player was too greedy and impatient and overdosed in purifier then yes, (s)he shall be punished for that just like with normal mutations: chances of positive mutations removals shall rise and negative ones drop.
