### ISSUE TITLE
SD Cards don't like both pictures and books in them

### ISSUE THREAD

**Issue by FarmWizard** [CleverRaven/Cataclysm-DDA#65427]
### Describe the bug

You go to upload your pictures from your camera into an SD card with books on it and what do you know? It vomits them out as physical hardcovers.

### Attach save file

[West Virginia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11370371/West.Virginia-trimmed.tar.gz)

### Steps to reproduce

Take an SD Card, rename it. Move pictures onto it, then try and move books into that same SD card, or vice versa.

### Expected behavior

SD Card should be able to hold all those kinds of things realistically, but if not I guess a popup message about an error with filesystem or encoding problems since you can't co-mix the two.

### Versions and configuration

0.G Steam Version

**Comment by TealcOneill** [comment]
Confirmed on 195b437. This one is tricky to pin down and seems to be doing several things. Sometimes it deletes both the pictures and the book from the card, other times it drops the book, I even saw it delete the SD-Card once. This is very weird.
