### ISSUE TITLE
Social activities - A way to improve skill

### ISSUE THREAD

**Issue by Knut-Aage-Hofseth** [CleverRaven/Cataclysm-DDA#65430]
### Is your feature request related to a problem? Please describe.

With skill rust you need a way to boost practical skill in Social. There is only so much Trading you can do, and trading currency back and forth to build up Practical skill feels like cheating.

Using Practice recipe to top up on Practical skill limits you to Lvl 6 Practical. And since the Practical is what is used for Social checks I would like a better way to gain and top up Practical Social Lvl.

### Solution you would like.
*Edit:
Suggestion:
Play_Game action gives a small amount of social xp if you play with friends.*

A practice recipe for higher level skill could solve this, but a pure practice recipe does not make much sense for social skill.

My proposed solution is an activity that you can do with followers. Something along the line of reading to a group of followers? Host a poker game with followers perhaps. Or run a DnD game since we have the Dungeon master book and can find character sheets?

I do not know is the activity or the recipe is best, but something that needs followers to be involved to be able to done and that allows you to spend time to gain practical Skill in Social.

**Comment by Adomatic** [comment]
Playing with pets might increase it a bit too. But yeah, right now there is clearly no practical, sane way to increase social beyond 6, unless you count 'trade .22 LR shells one at a time to a trader for six days' or something like that.

**Comment by fairyarmadillo** [comment]
The board games would be perfect for this. Some of them are quite complicated, it'd be neat to see that carry over into social skill.

**Comment by fairyarmadillo** [comment]
> This is currently beyond my skill level to code, but I might try just to learn. I will not be hurt if someone else does it before I manage to figure it out.
> 
> Quick check shows that those Items has Play_Game use action. If we can add a check for crafting helpers here and award social xp if that returns positive. Exact value to be balanced in eventually.

I was actually going to get started on this today, but I think it's a good project to learn on and I have no problem letting you sort that out for the practice (not that I'm great at C++ myself 😆 ). My one piece of advice would be to assign a value in the JSON entry for each game that states the game's complexity, and then tie that complexity score to what skill level the game teaches to. If you wanted to get fancy, you could even pull the logic from books and make that complexity score also make the game less fun for people below a certain intelligence level.

So like mahjong and chess could be pretty difficult, while snakes and ladders would be more accessible. It might be fun hunting for a good game to play with your 6 int NPC, or exciting to score a complex game that would allow you to do some advanced training.

**Comment by Knut-Aage-Hofseth** [comment]
> > This is currently beyond my skill level to code, but I might try just to learn. I will not be hurt if someone else does it before I manage to figure it out.
> > Quick check shows that those Items has Play_Game use action. If we can add a check for crafting helpers here and award social xp if that returns positive. Exact value to be balanced in eventually.
> 
> I was actually going to get started on this today, but I think it's a good project to learn on and I have no problem letting someone else sort that out for the practice (not that I'm great at C++ myself 😆 ). My one big idea would be to assign a value in the JSON entry for each game that states the game's complexity, and then tie that complexity score to what skill level the game teaches to. If you wanted to get fancy, you could even pull the logic from books and make that complexity score also make the game less fun for people below a certain intelligence level.
> 
> So like mahjong and chess could be pretty difficult, while snakes and ladders would be more accessible. It might be fun hunting for a good game to play with your 6 int NPC, or exciting to score a complex game that would allow you to do some advanced training.

Don't let me stop you. I would start from scratch with c++ and can not promise to make any good progress on this. To me it would even be interesting to see someone elses take on the code and compare to my try to learn from that.

**Comment by fairyarmadillo** [comment]
> Don't let me stop you. I would start from scratch with c++ and can not promise to make any good progress on this. To me it would even be interesting to see someone else's take on the code and compare to mine try to learn from that.
> 
> I am unsure about complexity with training social here. Since it is not the game teaching you Social skill, but playing it with someone (being social) that trains Social skill. Perhaps not think complexity but how much you need to read the other players to succeed that determine how much Social skill you can get from a given game?

How about I take a crack at it and then @ you in the PR, and you can jump in and help out how/if you want?

My thinking is that the game is providing the architecture for the social activity, which is not terribly different from how social interactions work in-game. Negotiating a holdup, talking someone into trusting you despite you being a hideous mutated freak, or haggling over the cost of bullets are all fundamentally just the same activity, but vary in complexity.

Getting into a granular evaluation of 1) how hard the rules are to understand and 2) the level of mind-reading required to succeed in the game is probably more complex than is appropriate for such a simple system, and it would make it more annoying for people trying to add games in future PRs. If I just say snakes and ladders is 1 and bridge is 10, then everyone knows what that means.
