### ISSUE TITLE
Nerf/rework/obsolete frog mother

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65438]
### Is your feature request related to a problem? Please describe.

Frog mother is strong, have a lot of hp, fast regeneration, fast speed, have jump ability and have long range summon attack with tadpole constrictor, wich will grab you and suffocate to death or let you to drop your weapon, and you cant do anithing to it, and also frog mother have strong grab by itself
Its the most dangerous creature. If you in the middle-late game meet 1 by 1 juggernaut or hulk - you can shoot them, with a lot of ammo shooted ammo or not - you will survive, may be loose some health, but survive. If you meet any other creature - with good gun or high melee skills you can kill them and survive, at least 1vs1, but if you meet frog mamma - you need to blow it with grenade laucher or hide in car with gun at the roof, or spam tonn of ammo

### Solution you would like.

Nerf/rework/obsolete it
By the disription it have stubby legs with no feet - so it must be very slow and dont have ability to jump
Make its summon attack being not long range, let it summon tadpole constrictor only near by itself, or remove this ability, because creatures wich can summon creatures is very slow/stationary or dying upon summoning
Remove/nerf its regenaration, because it have faster regeneration, than hive halk, desolluted devouver or pupating zombie, but all of them is much more slower and dont have super deadly ability to summon grabbers

Or make something else, because as for now - its unreasonable deadlyest creature. I tryed to kill it by skill 5 character with m249 - and its just jump to you, ignoring your weapon because of super fast regeneration, summon grabbers, wich will let you drop you weapon because of making you too weak by grabs, and than it will kill you

Its just big zombified frog, but it also very strange, because all mutated wild animals cannot be zombifed or they will become amalgalas. As example:
Greate tusked moose - after dead cant ressurect
Thorny moose shambler - will ressurect as a Thorny moose shambler
Dire woolf - will became amalgamation
Insects - will became amalgamation
So mutation of creature is preventing it from zimbification, and let them only ressurects as it was before dead, or transform into amalgamation
Even the most deadly zombie wolf type is boneplated - but you can kill it with gun. And wolfs are also bigger than frogs in nature, and for some reason frogs became bigger than wolf, and frogs are not insects, so we cant make their zombidication/mutation simular

### Describe alternatives you have considered.

Leave all as it is unreasonably deadly

**Comment by Nebnis** [comment]
What gets me about this monster and shoggoth is just how oppressive the regeneration is. If you ever meet this and shoggoth and you can't run away, then it is an almost guaranteed death scenario, since only a grenade can effectively kill it. I would like to see at least their regeneration being reduced to something reasonable like 5 or something, since both shoggoth and frog mother are already incredibly deadly now in other ways like with the tadpoles and the multiplication.

**Comment by KHeket** [comment]
> What gets me about this monster and shoggoth is just how oppressive the regeneration is. If you ever meet this and shoggoth and you can't run away, then it is an almost guaranteed death scenario, since only a grenade can effectively kill it. I would like to see at least their regeneration being reduced to something reasonable like 5 or something, since both shoggoth and frog mother are already incredibly deadly now in other ways like with the tadpoles and the multiplication.

But the shoggoth at least very slow, and very slower than frog mother, it cant jump, shoggoth can't range attack you with grab monsters, and shoggoths are very rare, I saw them only in labs and rarely in subway tunnels. You can just run away, and also powerfull gun and some ammo can kill them, when frog mamma in super-fast-regenerative-strong grabb-distance killer. Deathclaws from fallout is pussys near the frog mamma

**Comment by Aerin-of-the-Toast** [comment]
It's meant to be a very dangerous miniboss of source. Most lategame threats are fairly toothless, if anything the game world needs more things that are vaguely threatening to a survivor with an assault rifle like the frog mother, not less.

**Comment by Nebnis** [comment]
> It's meant to be a very dangerous miniboss of sorts. Most lategame threats are fairly toothless, if anything the game world needs more things that are vaguely threatening to a survivor with an assault rifle like the frog mother, not less.

I completely agree with you but you can't hardly kill with anything but a grenade (which will include yourself too). So that falls into the other extreme as well, If an endgame character with guns is too strong, then the answer are more monsters with ballistic resistance not immortal ones where the answers are narrow. Specially when you can meet them randomly out there.

A good example of boss enemies with good design are the mutants from the labs. They all have very good specific answers to them but not in a way that flat you into the ground if you meet them without a car.

**Comment by sonphantrung** [comment]
Hmm, so the frog momma:
- Has 400 HP + 40 regen, 12 bash, 2 cut, 1 ballistic/cut/stab, definitely requires high power to combat with it.
- Has a speed of 60, with an occasional 2-4 tiles leap per 12 turns, not too fast actually.
- Has a typical grappler's special attacks, **and can spawn tadpoles that has 200 SPEEDS!!!**. Imagine getting grab by the frog and her children, pure agony right here
But, here's the thing: To even see her in the game world, either the zombullfrog evolving into the frog mother in the half-life of 34 days

**Comment by Nebnis** [comment]
Tonning down just the regen would be enough for me. People really underestimate how ridiculous 50/hp a turn is, you need to be right on top of them, (which means you are now royally fucked by the tadpoles) so you can spam burst/auto on a rifle/smg and pray to god you kill it or else the tadpoles/mother will.

**Comment by KHeket** [comment]
> * Tune down her ridiculous regen as you said, to the level of a gigantic naked mole-rat (15 iirc)
> * Tune down her children's speed, as the normal tadpoles in game have only like 70 Speeds.

Is no one will do it, I will make it by myself later, and I think, it better to reduce its regen to the middle regen of animals/swamp creautures or amalgamas or how the creature borned from dead insects cocoon names, because if the frog mamma have such unreasonable high regen - its make no sense

**Comment by KHeket** [comment]
And also tabpoles must be nerfed to their speed, because it newborn froggy creatures. And speed of frog mamma also must be nefed, because it have crippled legs by the discription, and in reality frogs not fast runners, they are good jumpers, but big zombie frog cant be as fast as a big zombie human in runing, it also should be much more slover in runing

**Comment by KHeket** [comment]
> It's meant to be a very dangerous miniboss of sorts. Most lategame threats are fairly toothless, if anything the game world needs more things that are vaguely threatening to a survivor with an assault rifle like the frog mother, not less.

Its ok, if minibosses are locolized and lore resonable about being minibosses, like mutants in labs, triffid queens, but if even prepeared you can randomly meet this deadly super puper fast grapper creature in the swamps or forests neaby while gathering vegetation - its not ok. And also all must be close to realism, so making unreasonable deadly creature in the open field just for miniboss challenge is not ok

**Comment by AcidAntOnAMinefield** [comment]
What was even the reason for the Frog Mother's existence to begin with? 
Is it even lore friendly, especially given it is friendly towards zombies?

**Comment by sonphantrung** [comment]
> What was even the reason for the Frog Mother's existence to begin with? Is it even lore friendly, especially given it is friendly towards zombies?

Well, the frog momma is encountered as a result of either a zombullfrog evolves (half-life of 34 days), colossal croaker revives
