### ISSUE TITLE
Shelter B-19 Computer errors out when examined

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#65437]
### Describe the bug

When interacting with the computer in the B-19 shelter, this error occurs:
```
DEBUG    : Tried to use an invalid beta talker.

 FUNCTION : actor
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 1803
 VERSION  : ffc75ab
```

### Attach save file

[Damascus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11375765/Damascus-trimmed.tar.gz)

### Steps to reproduce

1. Load my save
2. Interact with computer to the north with (e)xamine
3. Error out!

### Expected behavior

Computer screen appear with lore about the shelter.

First time interacting with a B-19 shelter computer, so I'm not sure what else should be there. 

### Screenshots

![image](https://user-images.githubusercontent.com/21962421/235735274-d429cd8c-1940-4803-84ef-a72256360177.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: ffc75ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

This seems related to https://github.com/CleverRaven/Cataclysm-DDA/issues/65313

**Comment by Proxima-b** [comment]
I can also confirm this

**Comment by levlazarev** [comment]
![image](https://user-images.githubusercontent.com/74716293/236096423-bf9ac8e8-b0b0-40f4-a681-e21d7aea5111.png)
Confirming that I'm still seeing this.

**Comment by bombasticSlacks** [comment]
You had to scroll by the text for the Open PR that fixes the issue to post that. 

![Screenshot_20230504-003559](https://user-images.githubusercontent.com/4514073/236107383-a27d6394-7013-4782-a44b-4b4337cf64f3.png)
