### ISSUE TITLE
Invalid beta talker issue still persist

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#65443]
### Describe the bug

When I tried to talk to the console with another character, this error message appeared:

 DEBUG    : Tried to use an invalid beta talker.
 FUNCTION : talker* dialogue::actor(bool) const
 FILE     : src/npctalk.cpp
 LINE     : 1803
 VERSION  : ffc75ab

### Attach save file

[Wasted.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11377478/Wasted.zip)

### Steps to reproduce

1. Load the character Cathy
2. Talking to the console
3. Error

### Expected behavior

No error.

### Versions and configuration

latest experimental.

**Comment by omni-Var** [comment]
Having the same issue with the addition that the consoles never respond with dialog access. This means no access to any information the dialog may provide, as well (including directions to the Refugee Center.)
