### ISSUE TITLE
Chain link fence merged with filing cabinet in church

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#65462]
### Describe the bug

Theres a filing cabinet that merged with chainlink fence in the same tile in church for some reason

### Attach save file

[Stark City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11394205/Stark.City-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save
2. chainlink fence and filing cabinet merged with each other

### Expected behavior

Filing cabinet and chainlink fence not merging with each other in churches.

### Screenshots

![Screenshot_20230504-132231](https://user-images.githubusercontent.com/78019001/236126824-745f4c2b-62b4-4f7b-a70f-d5d3adeff27c.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 1570318 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by TealcOneill** [comment]
Confirmed on 195b437. This is a bug with the "church_2ndfloor_1" terrain from this file "data/json/mapgen/church.json"
