### ISSUE TITLE
Pocket Dimensions

### ISSUE THREAD

**Issue by Raygaming4483** [CleverRaven/Cataclysm-DDA#65468]
### Is your feature request related to a problem? Please describe.

So you know that some or I guess most items can cause lag as long as you have a lot of it in the inventory right?(But I guess maybe it only occurs on Android?) and if you try to solve it by making a vehicle it's very hard to drive(because of the turn by turn movement) or if you put it in a base your search area will be limited and hoarding your loot back to base makes it very hard(especially in zombie infested areas) so what if you get a mobile base like a vehicle but you can just carry it by hand?

### Solution you would like.

So that's where the personal pocket dimension comes in, you can bring your base everywhere literally in your pockets!Its like the escape stone where you can go in back and forth while also store your base in there!

### Describe alternatives you have considered.

I have some knowledge in modding in this game but I don't know how to make an item have an effect that teleports the user to a pocket dimension separate from the real world and then back to the place where the item was activated in the real world, so I'll leave this idea to the masters of modding, if this idea gets implemented it might open possibilities in making dungeons, separate dimensions, new planets or no clipping to the backrooms and not actually starting in the backrooms like the mod

**Comment by GuardianDll** [comment]
Sky island mod exist, tho it's not in repo because original author has some personal problems IRL

**Comment by Ramza13** [comment]
So this would be sorta possible right now via json but kinda hacky.  Right now the issue is creating a pocket dimension that saves your changes/items would be awkward.  It wouldn't be too hard a c++ change to make it easier to do, if anyone is actually planning on implementing this ask me and I could add it in.

**Comment by Raygaming4483** [comment]
Hmm, I see......I might need to dive into the files of   the sky island mod for a while

**Comment by Zireael07** [comment]
Instead of envisioning more workarounds and hacks, the basic issue of having many items causing lag should be fixed, SOONER rather than later. Charges were once considered a solution (albeit a hacky one) but recently the trend seems to be to move away from charges in general.

**Comment by Raygaming4483** [comment]
Yeah been racking my brain trying to make a mod with the sky island and magiclym as reference for two days.......I thought I had progress but nope I didn't, But there's a possibility, as long as I know how to teleport to a very specific location like this [ 0, 0, 0 ] using EOC......is it even possible?let me know if somebody knows the code please.....Sooooo yeah! I don't know anymore!!~~, I guess I'll just give up on it *(FOR NOW)* and just use translocation gates in magiclym or make a massive mobile base for lag reduction I guess😭😭

**Comment by Raygaming4483** [comment]
Ohhhh!!!I finally found an alternative!!!I created a mod with a back to back portal which you can go back and forth ayyyy!!!Now I just need to integrate it to my own modpack......do you guys know how to upload your own mod to GitHub?I wanna share my mod to everyone in the community 😀
