### ISSUE TITLE
Safe artifact activation

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65471]
### Is your feature request related to a problem? Please describe.

Artifacts often are very dangerous to activate. The most deadliest effects, which I met - 1) I burned in fire 2) Portal opened at my base and monsters killed me

### Solution you would like.

I have managed few ways to make it safe, I dont know princeple of activating artifact, but
1) Use npc. Give artifact to him and ask to activate. I dunno, is it posible for now
2) In some caves I saw broken miner robot, in Russia it translated as a sapper robot. So, sapper bots can be added to game, there is lots of them in reality, so you can build one, make remote conrol - and activate artifact by sapper bot
3) We have radioactivation mod - so use it on artifact
4) May be some kind of mehanical activation. Long rope or mechanism, or stationar mechanism with distant activation. Workbench with robo hands
5) If artifacts need only living creature - use zombies/animals. Make mechanism to let their hands activate artifact. Catch raccoon and make it under influence of remote electric mechanism(Like in exosceleton gloves) activate artifact. There is a lot of ideas to make it real
6) If artifacts need meaningful activation, which means, that you must think about activation - use zomborgs, exodii worker or cyborgs. Hack them/install something conrolling in their head - remote controll them. May be Rubik can sell items, which you can install in human/feral/zombie/zomborgs/intelligent zombie(like zombie masters/necromant) head and controll them. Because in case of zomborgs, if there is no human or organic flesh - so how the blob capture them?
7) May be some scanners of artifact or distant activaters selled by Rubik/Hub-01? 
8) Give artifact to Hub-01 workers, pay some gold coins and wait for 1-2 days, than return and they will say properius of artifact. I think ther will be very usefull for hub too, because they will get a lot of information about mistery object. Or mase the same thing, but Hub-01 will reward you for new since information and give the artifact bach and will also ask you to sell it to them. Or make simular mechanic with Rubik
9) Buy exodii worker from Rubik and use it for your purpose

### Describe alternatives you have considered.

Leave all as it is

**Comment by andrei8l** [comment]
This raises the question: how are artifacts even "activated", outside of Magiclysm? Most of them are regular items modified by the nether so there's no button or obvious method. Do you brush them? Tickle them? Hold them tightly and tell them you love them? Unless we can answer that, we probably can't consider remote activation.

**Comment by KHeket** [comment]
> This raises the question: how are artifacts even "activated", outside of Magiclysm? Most of them are regular items modified by the nether so there's no button or obvious method. Do you brush them? Tickle them? Hold them tightly and tell them you love them? Unless we can answer that, we probably can't consider remote activation.

We can solve this question here. So, telling them you love them - is good idea. Remote control activating stereosystem or speaker which will say this words, or use two two-way radio

But seriously, in this question we need lore and artifact expert

**Comment by fairyarmadillo** [comment]
Labs sometimes have rooms that appear to be devoted to testing artifacts. It'd be neat if they could be used to safely do this somehow.

**Comment by cosmo-naut** [comment]
> This raises the question: how are artifacts even "activated", outside of Magiclysm? Most of them are regular items modified by the nether so there's no button or obvious method. Do you brush them? Tickle them? Hold them tightly and tell them you love them? Unless we can answer that, we probably can't consider remote activation.

Perhaps artifacts need to be expanded further so that rather than being used directly, they mimic whatever item they are based on and are used when that item would be used.
For example: if an artifact is a lockpick it would be used whenever you open a door with it, a lighter could activate any time you ignite it and a rock could activate when thrown at someone.

**Comment by fairyarmadillo** [comment]
Artifacts are partly based on SCPs, and it's a running theme with some of those that you have to do something inane to make them work. I'd suggest having some of them (50%?) activate when used as intended, and some of them have a random action trigger taken from a list. So a rock might activate when you threw it, or it might activate when it gets hot enough, or when you shout, or when it's used to smash something, etc. Space Station 13 uses a similar solution for its artifacts, where you sort of have to puzzle out how to get them going, though there are ways to get hints.
