### ISSUE TITLE
Grabs not broken by Brutal Strike pushing grabber away

### ISSUE THREAD

**Issue by DeciusBrutus** [CleverRaven/Cataclysm-DDA#65484]
### Describe the bug

Zombies continue to grab the player while no longer adjacent after being forced back with Brutal Strike technique. 

### Attach save file

Not included 

### Steps to reproduce

1. Get grabbed by a creature that can be grabbed. 

2. Hit them with a baseball bat that sends them reeling. 

3. They get knocked away but retain their grip on you. 

### Expected behavior

Any forced movement by other than the grabbing creature should either fail to break a grab and fail to move the involved combatant, or move the combatant involved in the grab and break the grab. 

Also expected is that stunning a grabber would also break any grab they have. 

### Versions and configuration

Version: f9caeb7 64 bit

mods loaded: dark days ahead
Bionic professions
Disable NPC needs
No fungal growth
Speedydex
Stats through kills
stats through skills
Translate complex dialogue
Tamable wildlife
Blaze industries 
Magiclysm
DinoMod
sees-player, run, crouch, bleed icons, retrodays 
portal storms ignore NPCs

**Comment by Venera3** [comment]
This is mostly visual, this grab will get cleared automatically at the start of your next turn. Nevertheless handling grabbers getting knocked back could be cleaner.

**Comment by anoobindisguise** [comment]
> t



> This is mostly visual, this grab will get cleared automatically at the start of your next turn. Nevertheless handling grabbers getting knocked back could be cleaner.

One problem with this is that the monster can move back to you and re grab you in the same turn as you make the attack because many weapons with the knockback property are slow enough for that to happen.
