### ISSUE TITLE
Segfault when installing new pieces to my massive deathmobile, fine while interacting with other vehicles

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#65481]
### Describe the bug

My deathmobile weights in at 50k, and have 7.5k volume of cargos in it. When I try to install something new in the vehicle, a segfault occurs.

However, when I try to do the same for other vehicles, the vehicle menu works as expected. Crash and debug log attached.

My deathmobile have a deathrocket mounted to the bikeracks on the backside, otherwise, all should be normal.

### Attach save file

[Damascus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11402970/Damascus-trimmed.tar.gz)

### Steps to reproduce

1. Load my save
2. (E)xamine my deathmobile
3. (i)nstall anything to the edges of my vehicle
4. Segfault!

### Expected behavior

I expected the vehicle parts install sub-menu to come up in the menu instead of a segfault. 

### Screenshots

![image](https://user-images.githubusercontent.com/21962421/236368512-1ca757fd-5080-4f5e-b95f-e06c8cb0e6f0.png)

![image](https://user-images.githubusercontent.com/21962421/236369266-98e9fce0-dc3c-4a2a-b863-b1e5166bb5c2.png)
(Red circled area is where I've been able to trigger the segfault each time.)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 7c613dd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11402978/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11402979/debug.log)

**Comment by mqrause** [comment]
This should be fixed by #65472 in the newest version.

**Comment by DillonSimeone** [comment]
Confirmed, #65472 fixes this. Good catch, thanks!
