### ISSUE TITLE
the npc morale has no time limitation

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#65492]
### Describe the bug

My NPC follower dont want to study from books, becouse she is too sad. 
I switched control to here, and find this:
![image](https://user-images.githubusercontent.com/24881844/236565877-75a319ff-3556-4b84-a54f-16a2a102b061.png)

she remembers everything that happened to her

### Attach save file

[Yarrow Point-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11409998/Yarrow.Point-trimmed.tar.gz)

### Steps to reproduce

1. Make your npc follower to do sad things.
2. After few days npc still had morale penalties 

### Expected behavior

NPC morale should be turned off or had same time limitations as for players. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1555 (22H2)
- Game Version: 2acc6f4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Oooh yeah, that's a nasty one. Good find, and confirmed. 

I haven't dissected the issue, but it looks like `Character::update_morale` and related functions are only called for the player? 

https://github.com/CleverRaven/Cataclysm-DDA/blob/d3ea970c8d37cdfe52942e8a16a6b2da76f27a42/src/do_turn.cpp#L690-L696
