### ISSUE TITLE
No Shoes debuff while swimming

### ISSUE THREAD

**Issue by sdgoihew** [CleverRaven/Cataclysm-DDA#65500]
### Describe the bug

As in title

### Attach save file

[Lost-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11411656/Lost-trimmed.tar.gz)

### Steps to reproduce

1. Swim without shoes
2. Get debuff

### Expected behavior

No debuff while swimming

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/115432842/236606828-ec9ef54e-9341-4ef7-89d2-66692ab7b3bc.png)

### Versions and configuration

experimental build 2023-05-05-2116

**Comment by RenechCDDA** [comment]
Confirmed, but it's just a display issue. Doesn't seem to actually affect movecost.

**Comment by Night-Pryanik** [comment]
> it's just a display issue. Doesn't seem to actually affect movecost.

Actually this indeed increase move cost.
