### ISSUE TITLE
Cant use safe mod properly in any language

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65513]
### Describe the bug

I have lots of monsters in safe mod manager, here is part of screenshot, copy-past text from config/safemod and zipped safemod.json

<details>
  <summary>Spoiler warning</summary>

[safemode.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11413264/safemode.zip)

![image](https://user-images.githubusercontent.com/102726167/236637919-c317103f-5683-416b-8a3f-2b168821137a.png)

[
  { "rule": "лось", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*кабан*", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "deer", "active": false, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*олень*", "active": false, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*", "active": false, "whitelist": false, "attitude": 0, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "глазобот", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "военный прожектор", "active": true, "whitelist": true, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "гигантский жук-олень", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*оса*", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*паук*", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*муравей*", "active": false, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "пума", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "волк", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*пчела*", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "полосатый кот", "active": true, "whitelist": true, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*многоножка*", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "colossal croaker", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "deathrattle serpent", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "гигантская божья коровка", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "*муравей*", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "Церберложник", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "lady bug", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "дерматик", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "полосатый котенок", "active": true, "whitelist": true, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "огромный жук-олень", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 },
  { "rule": "", "active": true, "whitelist": false, "attitude": 3, "proximity": 0, "category": 0, "movement_mode": 2 }
]

</details>

And because of them and if you type anything and playing at russian version of the game - safe mode will not trigger and alarm you about hostile npc. And you cant even make it alarm you about friendly/neutral npc, no matter what you will type

If you make rule in safe mod manager that way

<details>
  <summary>Spoiler warning</summary>

![image](https://user-images.githubusercontent.com/102726167/236638210-dc0a47fb-c27c-4db7-b94e-7d14d05c6293.png)

</details>

It will be triggerd on any npc, bandit, survivors, hostile, friendly, neutral, but you cant reproduce it in russian, and its make fast travel and lots of actions deadly dangerous, as example - fast traveling by the road and be killed by bandit road trap and by bandits, or some freak npc with big gun wandering and coming to you, than became angry beacuse you are not too social - bam bam bam, you die

### Attach save file

N/A

### Steps to reproduce

Launch the game
Turn on russian langeage
Try to make safe mod manager to react on friendly/neutral npc or on bandits/hostile npc when you are already have options in safe mod
See, that nothing dont work. I tried человек, люди, нпс, нпц, and lots of ather words, I tried use all of latters like *ч* because you by typing this, safe mod will alarm you about all monsters with letter "ч" in name, but nithing works
Die
You can also type only * in safe mod manager, and it will alarm about everybody, but only if the game is on english. If you make it in russian - it will ignore npc. check chreenshots below

<details>
  <summary>Spoiler warning</summary>

![image](https://user-images.githubusercontent.com/102726167/236638693-3ff2d704-ed59-4728-acd2-be1a128fc1f1.png)

![image](https://user-images.githubusercontent.com/102726167/236638729-1b5eba83-0780-45e8-a1d3-495758fb9600.png)

</details>

And also, if you make this rules in safe mod manager on english version - than swap to the russian - they will work until the restart. But if you swap to russian, clear all safe mod manager list, than type rules as I showed - they will not work

### Expected behavior

Safe mod manager work properly on all langeage

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 87b083f [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by KHeket** [comment]
@Maleclypse I tested my problem at a last experemental - and it is still exist. Safe mode still dont work in russian language at npc

**Comment by Maleclypse** [comment]
> @Maleclypse I tested my problem at a last experemental - and it is still exist. Safe mode still dont work in russian language at npc

It auto closed when Night's PR that said it fixed it was merged by me 2 hours ago.  The newest experimental probably won't have that new merge in it until tomorrow.  Can you test then?

**Comment by KHeket** [comment]
Still dont work with russian langeage at latest experementals. I think, with other langeages will be the same problem

**Comment by KHeket** [comment]
[1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12506107/1-trimmed.tar.gz)
And tested is at latest experimental, driving near bandits
- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 3315e1f [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by inverimus** [comment]
This is not working for me in English either.

1. Set some rules in safe mode.
2. Turn off "enemy spotted" in distractions.

Now safe mode doesn't work almost at all. With "enemy spotted" enabled safe mode works, but doesn't properly follow the rules, it warns for enemy spotted at any distance.

**Comment by RenechCDDA** [comment]
The `fixes` keyword was included in #75781 but github did not automatically link it for some reason. This should be resolved with that PR's merger.
