### ISSUE TITLE
Stamina regeneration stat mess up the butchering activity

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#65515]
### Describe the bug

If you have something, that gives encumbrance on your mouth (so it changes the stamina regeneration rate, which scales from breathing score), and decide to butcher a corpse (the one that spend lot of time, like full butchering or dissecting), it rapidly consume your stamina. When the stamina is consumed, it gives prompt: `Continue after break`, `Maybe later` and `Finish it`. Pressing `Finish it` makes impossible to interrupt activity manually.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a mask, that has huge mouth encumbrance (like bondage mask or Foodperson mask)
2. Spawn a zombie
3. Kill it
4. Try to dissect it
5. Your stamina is rapidly consumed, and the prompt to rest appear
6. Press `Finish it`
7. You can't stop the dissecting anymore.

### Expected behavior

I can stop the dissection whenever i want, and not stuck in dissecting dozens of corpses for 20 hours

### Screenshots

![GIF 06-05-2023 22-46-12](https://user-images.githubusercontent.com/67688115/236645988-990c0068-52a2-4531-967d-b9b98f1b79e9.gif)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: bbfa357 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA]
]

**Comment by TealcOneill** [comment]
Confirmed on 195b437.

**Comment by GuardianDll** [comment]
Resolved by #72099
