### ISSUE TITLE
Survivor spills his Yogurt

### ISSUE THREAD

**Issue by FarmWizard** [CleverRaven/Cataclysm-DDA#65520]
### Describe the bug

I went to make yogurt, put it into a gallon ziplock as you do, and waited. Once it was finished I went to 'activate' it to get the yogurt out and surprise! It went right on the floor. Only way to get the yogurt actually is to open it over a bathtub.

### Attach save file

[West Virginia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11414198/West.Virginia-trimmed.tar.gz)

### Steps to reproduce

Make fermenting yogurt, place into a container in your inventory, wait, and then activate it. It dumps it on the ground and now you have a sad survivor.

### Expected behavior

You would expect the survivor wouldn't spill the yogurt and instead the game would prompt you to put it into a container like with a lot of cooking based tasks but apparently not.

### Versions and configuration

0.G Steam Version

**Comment by estebandellasilva** [comment]
Since this has been fixed ... does that mean its no use crying of spilled milk?
