### ISSUE TITLE
Alonso cannot have his pants :(

### ISSUE THREAD

**Issue by Ruminator24** [CleverRaven/Cataclysm-DDA#65525]
### Describe the bug

It seems that if you discover too much of the area before going to Alonzo and attempting to start his mission, it ends up failing since it can't find the appropriate sex shop. I do apologize if this bug report is nullified by the fact that I used the debug "reveal map" to show this off, but I recall this happening a few times before, where I would acquire either binoculars or a portable telescope, use the radio towers to discover as much area around me as possible, and then while going around, attempting to start up every mission in the refugee center, end up with an error for Alonzo's. 

Now I'm wondering if the same error might appear if a player was searching an area around them, before starting up a npc's mission, such as "kill my mom" or "find my dog", since they might also require map spot to be allotted for the mission? 

### Attach save file

N/A 

### Steps to reproduce

1. Make a player
2. either debug reveal the map around the refugee center (testing) or use binoculars/portable telescope and stand on top of radio towers
3. Go to the refugee center and start up Alonozo's pants mission
4.  Get an error regarding that the mission can't be started due to not finding an available sex shop
5. now be stuck with a unremovable mission

### Expected behavior

I would expect the mission to instead look for a sex shop outside of the area around the refugee center, instead of breaking.

### Screenshots

![alonzo nopants](https://user-images.githubusercontent.com/131492998/236677877-cc56d7cb-d06d-48b4-9210-1d4ef94a00d4.PNG)

### Versions and configuration

- Windows 10
- Version d6ec466 64bit
- Tiles
-  English
- None

### Additional context

The mission will work normally if the player doesn't attempt to discover the entire area around the sex shop before starting the mission, it seems to only break if the player discovers the map around the refugee center before starting the mission.

**Comment by stubkan** [comment]
This is an old bug, because the sex shop is a quite rare location - I suggested using an alternative more common location in the comments of this older bug report.

#48029

**Comment by MaratValeev** [comment]
Still actual. Version:
build type: windows-tiles-sounds-x64-msvc
build number: 2024-08-20-2247
commit sha: 4180cc3e486e2ee4c78b05bbfa2a880d98ef26de
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/4180cc3e486e2ee4c78b05bbfa2a880d98ef26de

**Comment by stubkan** [comment]
All it requires is someone to make it not try to find a super-rare location.  I provided a solution already, perhaps someone else can CTRL+C and CTRL+V the fix into a PR
