### ISSUE TITLE
Unable to install electirc forge to the vehicle

### ISSUE THREAD

**Issue by Sheggy942** [CleverRaven/Cataclysm-DDA#65553]
### Describe the bug

While trying to install electric forge, the menu says : "The installed wiring part shares the structure location". Tried this with frames, instead of wiring - same result. Tried attaching it to the tile without frames - don't even given an option to do so.

### Attach save file

[Tunnelton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11430400/Tunnelton-trimmed.tar.gz)

### Steps to reproduce

1. Obtain electric forge.
2. Try installing it to the vehicle

### Expected behavior

Expected - electic forge installs in my vehicle

### Screenshots

![Screenshot_161](https://github.com/CleverRaven/Cataclysm-DDA/assets/133005710/c6765bc9-81a2-48af-a999-c4d4766a0be1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: ea17d8e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    No Rail Stations [No_Rail_Stations],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RenechCDDA** [comment]
Electric forge is actually an appliance, it's supposed to be getting filtered out of the listings (going to have to look into this...). What you want is "mounted electric forge". That appears to be working fine.

**Comment by Sheggy942** [comment]
Sorry, took me some reading to do, but figured it out in the end. Sorry for inconvinience.
