### ISSUE TITLE
Autoforage not working

### ISSUE THREAD

**Issue by bjnation** [CleverRaven/Cataclysm-DDA#65564]
### Describe the bug

Auto-forage is not working as intended, as in when you're walking in the woods underbrush is not being auto foraged.

### Attach save file

N/A
[Brennanville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11437458/Brennanville-trimmed.tar.gz)

### Steps to reproduce

1. Create new character in default evac scenario
2. Auto-pickup in options is enabled
3. Auto foraging is toggled to "everything" or "bushes"
4. Walk through woods near bushes and trees

### Expected behavior

I expected it to forage as I walked around the woods.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: ea17d8e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key]
]

**Comment by RenechCDDA** [comment]
Your auto features is set to disabled. You must enable auto features before autoforaging will activate.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/323cee3f-c502-46a5-b2fc-a7212acf8696)
