### ISSUE TITLE
After defeating amigara horors ther is no artifact

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65583]
### Describe the bug

If amigara hororsor at least one of it dies not from player but, for example from fire - the artifact will not drop
Also, if you kill one or more amigaras not at the final floor - artifact will not drop too

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11451946/test-trimmed.tar.gz)

### Steps to reproduce

1) Find mine with amigaras
2) Place flameable items like sticks at the 1 tile
3) Activate the computer
4) Flame sticks
5) Let one or all amigaras die from fire
6) See no artifact
<details>
  <summary>Example and result</summary>

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/84ae98b0-2356-454f-bb4b-742537721964)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/23ff647c-0b1f-4478-b966-3deb832da1d4)

</details>

For the second example - call the amigaras, but run back to rump on the next level and let amigaras follow you, kill all or one of them them on the floor above, then kill the others - see no artifact at the last room, but artifact will spawn at the floor, where you have killed the last amigara

I also leave character save with amigara mine in zipped trimmed archive

### Expected behavior

If my characher have high computer skill to safely activate computer - I should be rewarded with artifact, even if I kill amigaras with my sharp mind and some prepared items

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 627309c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by stubkan** [comment]
Sometimes it spawns outside the room, make sure you fully check the whole area including outside the room.  This can cause people to think nothing spawned, but it does.

**Comment by KHeket** [comment]
> Sometimes it spawns outside the room, make sure you fully check the whole area including outside the room. This can cause people to think nothing spawned, but it does.

I checked all floor with debug clairvoyance and saw no artifact after burning amigaras
