### ISSUE TITLE
Down stairs block pathfinding for purposes of crafting reach

### ISSUE THREAD

**Issue by GlitterLich** [CleverRaven/Cataclysm-DDA#65593]
### Describe the bug

Stairs leading down block pathfinding for purposes of crafting reach as if made of an impassable tile; the game cannot see crafting components if the path leading to the components is "blocked" by a down stairs tile. Up stairs are not affected by this issue.

### Attach save file

[Hibernia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11470783/Hibernia-trimmed.tar.gz)

### Steps to reproduce

1. Get in your workshop
2. Surround yourself with down stairs
3. No crafting components will be visible in the crafting menu, even if normally within the 6-tile range

### Expected behavior

As a passable tile, down stairs should not block crafting component visibility

### Versions and configuration

- OS: Windows 7 64bit
- Game Version: 0.G Stable / d6ec466 64bit
- Graphics Version: Tiles
- Ingame Language: English
- Mods loaded: dda, bionic professions, blaze industries, magiclysm, disable npc needs, portal storms ignore npcs, no fungal growth, tamable wildlife, translate complex dialogue, mythical martial arts, no rail stations, sees_player_retro

### Additional context

The issue also applies to wooden down stairs, ladders leading down, and up/down ladders.

**Comment by RenechCDDA** [comment]
Unable to reproduce. Can you provide a reproduction save?

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/689b0b7b-f325-41c1-8fcd-fe65bf1477d9)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/df39f60e-05fb-4326-beb8-361fc4288d2e)


I tried `t_stairs_down`, I tried `t_wood_stairs_down`, I tried all the *up* stairs too. I even tried the broken stairs and the partially constructed stairs.

**Comment by GlitterLich** [comment]
Strange! I was able to see some components in my workshop but not the ingredients in my lab/kitchen. I'll let you people figure out what differentiates the two. I'm attaching my save; [Hibernia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11470783/Hibernia-trimmed.tar.gz)

**Comment by RenechCDDA** [comment]
....You got *enough* food?!

Thank you for the save. Very very weird, and very very confirmed.

**Comment by RenechCDDA** [comment]
Aha, it's because **those stairs actually go somewhere**. My debug spawned stairs did not! For some reason, the pathfinding is only considering that stairs can be taken to their intended destination, and not walked through.
