### ISSUE TITLE
The requirements to build metal bars are missliding 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#65602]
### Describe the bug

I was trying to make my own underground prison to store armored Z , so i could train weapon skills easely. 
And i found that i cant build metal bars, they require some kind of "floor" 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/e2e8c613-a60b-4d73-9005-58b1ee0ebd4f)

but it's not "floor" missing, its the "roof". And not just any roof, it's only roof made from wood needed. 

Recipe to build metal Bars:
{
    "type": "construction",
    "id": "constr_bars",
    "group": "build_metal_bars",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 5 ] ],
    "time": "60 m",
    "tools": [ [ [ "oxy_torch", 4 ], [ "welder", 20 ], [ "welder_crude", 30 ], [ "toolset", 30 ] ] ],
    "qualities": [ [ { "id": "SAW_M", "level": 1 } ], [ { "id": "GLARE", "level": 1 } ] ],
    "components": [ [ [ "pipe", 6 ] ], [ [ "sheet_metal", 2 ] ] ],
    "pre_terrain": "t_floor",
    "post_terrain": "t_bars"
  },

The only recipe with gives "t_floor" :
{
    "type": "construction",
    "id": "constr_floor",
    "group": "build_roof",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 3 ] ],
    "time": "120 m",
    "qualities": [ [ { "id": "HAMMER", "level": 2 } ], [ { "id": "SAW_W", "level": 2 } ] ],
    "components": [ [ [ "wood_sheet", 1 ], [ "wood_panel", 2 ] ], [ [ "2x4", 6 ] ], [ [ "nail", 40 ] ] ],
    "pre_note": "Must be supported on at least two sides.",
    "pre_special": "check_support",
    "post_terrain": "t_floor"
  },

Also there are some other recipes , for example build carpet,  require same "t_floor" with is actualy a wooden roof 

### Attach save file

[Yarrow Point-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11465615/Yarrow.Point-trimmed.tar.gz)

### Steps to reproduce

1. try to build metal bars outside of building.
2. try build different floors to much requerement 
3. after some time find that is's not floor, but roof needed. 

### Expected behavior

i am not sure what is needed to be changed info or actual requerement. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: a1ee886 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
The game only has a single slot for "terrain" in its data structures, and that single slot has to cover the ground, a potential roof, as well as any construction (that isn't "furniture") such as bars in a single value. Furthermore, the game currently has a fixed value "terrain" turns into when smashed/removed.

The above is an explanation for why things are the way they are, not an excuse.
