### ISSUE TITLE
Unbalanced cost for certain professions.

### ISSUE THREAD

**Issue by AstroMcSpaceBalls** [CleverRaven/Cataclysm-DDA#65600]
### Describe the bug

The dodgeball player profession should be buffed or have a different cost because other jobs have better stats with lower costs.

dodgeball player -2

+2 Athletics
+1 Throwing
+1 Dodging

Notable equipment:
Sling Pack

Basketball player -1

+2 Athletics
+3 Throwing
+2 Dodging

Notable equipment:
Runner pack

Baseball player -1

+2 Athletics
+3 Throwing
+1 Melee
+1 bashing

Notable equipment:
Baseball Bat

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A? _(first time writing a bug report so I'm not too sure on formatting yet)__

### Versions and configuration

- OS: Windows 10
- Game Version: O.G

**Comment by GuardianDll** [comment]
Points was essentially obsoleted by #64697, which invalidates this issue
