### ISSUE TITLE
Allow Pillow fort to be build on any type of floor not just on "floor".

### ISSUE THREAD

**Issue by BoruMaboru** [CleverRaven/Cataclysm-DDA#65616]
### Is your feature request related to a problem? Please describe.

I always want to build pillow fort for decoration purpose, but it need specific type of floor to be build on and it just only one. I don't want to build an entire floor just for pillow fort.

### Solution you would like.

Allow it to be build on every type of floors not just one.

**Comment by PatrikLundell** [comment]
The game only has a single slot for "terrain" in its data structures, and that single slot has to cover the ground, a potential roof, as well as any construction (that isn't "furniture") such as the fort in a single value. Furthermore, the game currently has a fixed value "terrain" turns into when smashed/removed.

The above is an explanation for why things are the way they are, not an excuse.

**Comment by Qrox** [comment]
I think pillow fort should be a furniture though, if it isn't already one.

**Comment by Nebnis** [comment]
> The game only has a single slot for "terrain" in its data structures, and that single slot has to cover the ground, a potential roof, as well as any construction (that isn't "furniture") such as the fort in a single value. Furthermore, the game currently has a fixed value "terrain" turns into when smashed/removed.
> 
> The above is an explanation for why things are the way they are, not an excuse.

man this explain a lot of things like fire-ring needing a fukken pit lol
