### ISSUE TITLE
Ploblem with item repairing or damaging

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65612]
### Describe the bug

For now there is 5 item durability levels. \. , |. , |\ , || , ++ . But if you wear all ++ quality clothes - after damaging they will become |\ , not || . And during repairing you will need to move through two levels, |\ > || and || > ++ . So, or the game dont show you, that item damaged from ++ level to || , or the game ignore the || level and after damaging items moving right from ++ level to |\ 

If you are wearing all  items in |\ quality - after damagind they will go to |. level , as intented

### Attach save file

N/A

### Steps to reproduce

Play the game, spawn and wear lots of items with ++ quality, spawn the zombie, let him hit you, see, that items will damaged from ++ quality to |\ , not to ||
You can also spawn lots of zombies/feral humas, kill them via debug menu, wear lots of clothes |\ quality, spawn a zombie, let him him hit you and see, that items will go fron |\ quality to |. , and then form |. to \.

### Expected behavior

Dont miss the durability level and dont let me waste resourse to air

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: d06ee82 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
Also, if you damage any weapon or gun, it immediately goes to |/ which is equivalent to 2 damage levels ( |. from before) which means the melee weapon loses 2 ticks of damage, and the gun goes to -4 damage right away, and it takes 2 cycles of repair to fix it.

**Comment by KHeket** [comment]
@irwiss can you check pls?
