### ISSUE TITLE
Increase costs of Weight XXXL trait

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65614]
### Is your feature request related to a problem? Please describe.

After lots of updates, the Weight XXXL trait became a very hard trait, which now dont looks like free points, but a very hard challenge. For more than 2-4 months of the game your stamina will be very low and draining for too fast, you will be exhausted just for walking, runing for a few tiles, and you every weapon will eat your steamina like donuts, you will be sick very often (some times after having common cold or flue for 2 weeks, you have them again on the day after curing), and you cant improve your health even with vitamins or good diet

### Solution you would like.

Before updates the XXXL trait worth -1 point, but for now its at least -2 points or started healtcare must be at least -50 or -75 points, but not -200 , because XXXL weight, as I know, even make you health bad, and you are not drug addict to have -200 start health points, you are just very very fat

**Comment by Karol1223** [comment]
Points are effectively unsupported since #64697

**Comment by KHeket** [comment]
> Points are effectively unsupported since #64697

thx for info
