### ISSUE TITLE
Balance Pass for Unarmed Clothing

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#65630]
### Is your feature request related to a problem? Please describe.

Currently, the unarmed clothing items (6 varieties of Knuckles, Studded Gloves and Cestus) have a rather strange power curve, where many are flat-out terrible, yet Skewer Knuckles are amazingly good. Impact Knuckles used to be good (slightly too good re: armor damage, probably), and the nerf made them pretty much terrible again. The slowest of various, cheaper craftable unarmed items with only 1 more bash.

What I'm proposing is to condense the power curve from 1-10 which now has many items on the low end and an easy 10, down to a 3-8. Weak items get buffed, Impact Knuckles get buffed (though not as much as it used to be before the nerf), and Skewer Knuckles get a small nerf. Even then, Skewer Knuckles take the highest aggregate score of DPS and Damage-per-Stam easily. It's the only weapon in the list with +1 to-hit. Which is fine.

I have taken into account the difficulty to craft these items as a rough guideline of which tier they're sitting in. The buff to these items is roughly proportional with their current damage.

Now, the general buff to Bashing damage and how that relates to armored enemies is the most important thing here. I can say that on a late-game munchkin with 20 DEX and 20 STR, max melee and unarmed skills, using Impact Knuckles with 9 Bashing, killing a Kevlar Hulk with your fists is still a *tedious affair* and something like Pankration throwing damage will be far more reliable than using another martial art with perfect equipment. But critical damage does proc actual low-digit damage to the Hulk. I am not sure if this was possible with Impact Knuckles at Bashing 5. Frankly, I took one look at them and thought they were reasonably nerfed but to an unreasonable amount. These, along with Skewer Knuckles, make up the top two unarmed items for Martial Artists, both in utility and in difficulty to craft them, yet Impact Knuckles were reduced to 5, while still being the slowest of the bunch at speed 77. Compared to a 73-speed 12 total-damage item. That's a dead item.

Anyway, here's my table for proposed changes, and what that breaks down to in numbers. Keep in mind that these numbers are with a munchkin character, and are only intended as being very close-to-maximum of what's attainable in CDDA. Look at them as relational power numbers more so than discrete. And notice that after the proposed nerf, Skewer Knuckles are *still* easily the best. The slight nerf subtracts more points from the first 2 columns than what it gives to vs. Armored.

This also makes a point that adding piercing damage to the unarmed attack is massively useful (see Damage-Per-Turn vs. Unarmed and Fast) just because so many enemies aren't very much armored, that it's almost out-of-line to the rest of the unarmed lineup.

### Solution you would like.

A general buff to most Unarmed Clothing items, and a slight nerf to Skewer Knuckles to bring it closer in line.

Cestus: Bash 2 -> Bash 5
Brass Knuckles: Bash 4 -> Bash 6
Nail Knuckles. Bash 2 Pierce 3 -> Bash 4 Pierce 4 
Scrap Knuckles: Bash 4 -> Bash 6
Steel Knuckles: Bash 4 -> Bash 7
Studded Gloves: Bash 2 Pierce 1 -> Bash 2 Pierce 4
Impact Knuckles: Bash 5 -> Bash 9
Skewer Knuckles: Bash 2 Pierce 10 -> Bash 3 Pierce 6

The weights and therefore Speed ratings remain unchanged. This leaves Skewer Knuckles as the DPS and Stamina King and gives Impact Knuckles (and arguably, Steel Knuckles) a place in the lineup.

Let me know what you think. This is what would make sense to me after having played the game for a very long time - but I make no claims to be right.

### Describe alternatives you have considered.

It's possible I am undervaluing damage vs. armored. But consindering the amount of squishy, dangerous enemies now in the game and the amount of armored ones that do more than play "be a wall" with you, I find it hard to see this point. One of those Shell Muntants will still require a rifle to make a dent, Kevlar Hulks are killable in that it's a chore and you get thrown around plenty because of general killing speed being about 1/3rd to half that of an armed survivor, I think. So about where it's supposed to be. Equipping the same survivor with a decent rapier, even without martial arts he's a much more capable killing machine. The DPS aggregate (three DPS calculations added together) for a tempered rapier is around 280. Even higher since I haven't tested this with a character of max Piercing skill. Skewer Knuckles, still being the highest of the bunch, get 160 post-nerf. With the upside that Unarmed fares well in the Stamina department, which just the DPS aggregate excludes. But then, unarmed fights take up that extra amount of time.

### Additional context

![unarmed clothing 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/13466852/57e505a1-3596-4290-98ec-f9f7f4acb63e)

**Comment by Jarewill** [comment]
Thank you for taking the time to do this, unarmed weapons really needed a buff.
However I feel scrap and steel knuckles should be one point weaker.

Scrap knuckles are just a "mass of scrap metal crudely beat into shape", so I feel it shouldn't be on par with brass knuckles, that are an actual forged weapon.
Maybe toning them down just slightly to 5 bash would be better, maybe even give them 1 cut to show that they are crude.

Meanwhile steel knuckles just seem the same as brass knuckles, but with a different material.
This is also more of a question, would steel make any difference in force compared to brass?

Also comparing to the others, impact knuckles' 9 bash seems like a big jump between other weapons.

**Comment by Tharn** [comment]
I'm flexible on the details. I also considered Steel Knuckles at 6 and Impact Knuckles at 8, seeing how Steel Knuckles are still a fast option. But that would give us 3 weapons at the same damage with slightly different speeds, which to me sounds uninteresting at these low values.

Impact Knuckles used to be 12, then were nerfed to 5. I feel this is reasonable.

**Comment by fairyarmadillo** [comment]
@Tharn I actually have a problem with skewer knuckles being at the top of the DPS charts. Those weapons are not very common or effective in real life - almost every tool designed to help people punch harder (even lethally) has relied on bashing damage and hand protection rather than the addition of a pokey bit.

Since stab procs bleeds, I think that's enough of a perk on its own to suggest bumping it off the top spot for DPS and letting something like impact knuckles take the top spot.

**Comment by fairyarmadillo** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/ddadd159-13a0-4cca-98bf-462f16de75bc)

Like I'm sorry but this feels like gas station ninja gear, it could hurt, sure, but I'd be much more worried about something like what we see below.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/bb971dc3-079e-4759-a9b1-41537c60a3a2)

**Comment by Tharn** [comment]
Well, going strictly by game description, those aren't skewer knuckles. They read more like this. That first image of yours would conceivably be closest to a Punch Dagger, though with knuckles.

![skewer knuckles](https://github.com/CleverRaven/Cataclysm-DDA/assets/13466852/64070221-526d-4ff3-a2b2-c5e456897eb7)

**Comment by fairyarmadillo** [comment]
I wouldn't agree with that statement, no. Bash seems pretty much in the middle, with cut as the worst and stab as the best. I tend to play with bashing weapons because I prefer the techniques they come with (stuns etc), but because bleed, weakpoints, and martial arts exist, I think stab wins hands-down.

**Comment by Tharn** [comment]
That's interesting, I hadn't even considered that. The table doesn't give a very good score for Skewer Knuckles vs. Armored, though it's actually better than the score it got at 2 Bash 10 Pierce (score being 21). So going by what the game gives me, the loss of 4 Pierce had less of an impact than gaining 1 Bash. I'm not sure I would agree with an even bigger nerf.

**Comment by fairyarmadillo** [comment]
But people did run around with katanas for hundreds of years, and every so often a news story drops about someone being killed or injured with one today. It's a highly effective weapon with a proven track record that has become outmoded, but is no less useful.

Ditto for the cestus, studded gloves, and brass/steel knuckles. These are items which are still sold commercially today and have a long historical record of use. Something like scrap knuckles works because they're a low-quality handmade imitation of this sort of thing, and I think nail knuckles are fine because they're strictly worse than their counterparts and already do a good job of representing some deranged crap a bored survivalist would make in his garage.

So that leaves me wondering about skewer and impact knuckles. These frankly feel made up for video game reasons - a "survivor" tier of gear spawned by the apocalypse. But the fact that they're outperforming pre-cataclysm factory-made items with the same form factor and designed for the same purpose feels really off to me.

**Comment by Tharn** [comment]
Also, I just found this. Very cool.

https://www.martialtribes.com/fist-weapons/

**Comment by fairyarmadillo** [comment]
> Also, I just found this. Very cool.
> 
> https://www.martialtribes.com/fist-weapons/

Many of these weapons used to exist in the game as unarmed weapons (ie katars) and lost their unarmed flag or were outright removed as it was determined that something like a pata, katar, or bionic sword is a melee weapon, not an unarmed weapon. A pata cannot simply replace your fist in melee combat, it's a large object which demands you treat it differently from your hands.

**Comment by Tharn** [comment]
Exactly, but no one says that it has to be this huge. A survivor faced with kevlar'd opponents that are immune to pain, and the will to fight them with his fists is prone to imagine some kind of a spiked thrusting extension to his knuckles. It'd work perfectly well shrinking down the idea of a Pata to a couple of steel plates with short daggers or spikes on them.

**Comment by fairyarmadillo** [comment]
To-hit values aren't arbitrarily adjusted for balance like that, they're based on the item's physical properties as laid out in game_balance.md.

**Comment by Tharn** [comment]
It is insofar as that it's a functional extension of your closed fist. The spike is turned forward and is used to slash at weak points, yes. It's not identical. I don't understand the intricacies of physical properties relating to to-hit, but it's certainly odd that Skewer Knuckles are the only item in the list with a to-hit bonus, as if they were functionally different than Impact Knuckles but with less beef behind the steel and two spikes attached. How does that make it easier to hit? Know what I mean? Betwee Punch Dagger (-1) and Karambit (-1) and Skewer Knuckles (+1) I don't see the reason for these values. The "Fist" that needs to connect does not change between any of the Unarmed Clothing items, I would say. I understand why small bladed weapons get a penalty.

**Comment by fairyarmadillo** [comment]
Good catch. Most of them didn't have to-hit values set, and the skewer knuckles had a bad one. I've updated it.

They're now +3 for all of them, except the skewer, studded, and nail knuckles, which are +2. See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md to make sense of the changes in the PR.

**Comment by Tharn** [comment]
With to-hit being roughly a 10% performance increase per point (I've read this here somewhere) that'd require us to probably down-adjust the stats a fair bit, if they were made that high.

Them all being at 0 and Skewer Knuckles being at -1 would certainly curb it pretty well even at 3 Bash 6 Stab, I'd say. No need to step on poor Martial Artists jugulars any harder. The spikes on something like Studded Gloves aren't really aimed, they're just very shallow "bumps" all over the item, like a piece of very tightly studded armor. That's my impression at least. What else has points on it?

**Comment by fairyarmadillo** [comment]
The document is explicitly that a flat bludgeon with spikes on it is -1. If the spikes are enough to do stab damage, they probably meet that requirement. If they don't meet that requirement, they probably aren't enough to do stab damage. Can't have it both ways.

I think your math is off on the value of to-hit. Characters don't really miss attacks that often and as I've said, miss recovery is common. With most martial arts giving you stuns and moves that strike more quickly and the speed of a punch already being very fast, I don't think the downgrade is going to hurt them.

Furthermore, unarmed isn't meant to be balanced. It's intended to be strictly worse in almost all ways than using a real weapon. Unarmed weapons help non cyborgs/mutants close the gap a little, but it's not intended to have any kind of parity with proper melee.

**Comment by Tharn** [comment]
Well, it already is that even with pre-nerf Skewer Knuckles or Impact Knuckles at Bash 9, like I said in the opening post. You're looking at half the killing speed at best, and while a Martial Artist has utilities to help with grabs and do throws and stunlocks, he also spends at least twice the amount of time in actual combat. And with several opponents, that adds up to many painful opportunities for the Martial Artist to receive something back.

**Comment by Jarewill** [comment]
> seeing how Steel Knuckles are still a fast option. But that would give us 3 weapons at the same damage with slightly different speeds, which to me sounds uninteresting at these low values.

My primary concern was that steel and brass knuckles didn't seem to be all that different from each other, only in material, weight and the steel ones having the HAMMERING quality while the other did not for some reason.
Both weapons share the same description, skill requirements, volumes, lengths, coverage, encumbrance, flags, so I was led to believe that they are the same weapons, just made of different materials.
I couldn't find any information about effectiveness of brass vs steel when it comes to unarmed weapons, so I would imagine they would be practically the same.
Also if you are going to balance it out by speed, it might be worth noting that the steel knuckles have a slightly higher speed than the brass knuckles, combine that with slightly higher damage and the old brass seems to have no reason to be picked.
 
> Impact Knuckles used to be 12 Bash, then were nerfed to 5 Bash. They, along with Skewer Knuckles are supposed to be the two best unarmed clothing items which are the most difficult to craft. I feel this is reasonable. They are still the slowest of the bunch.

I was still around when that PR was made and the main reason for that nerf was because there's only so much you can do with unarmed weapons.
They will lag behind even a club because of the bonus velocity swinging causes over punching.
My primary concern anyway was the sudden jump between damage values: Brass is 6, steel is 7 and suddenly impact is 9.
I understand that they are supposed to be the best unarmed weapons, but I feel there's only so much you can improve over a pair of brass knuckles, which still see a lot of use today.

**Comment by Tharn** [comment]
Impact Knuckles are also the slowest unwarmed clothing item though at speed 77, while Steel Knuckles are fairly fast at 73. Look at Impact Knuckles more in relation to Skewer Knuckles, as these two share crafting difficulty and lategame unarmed weapon status. Steel Knuckles are more something for mid-game at the latest, though at 7 and with the speed they have, they're only 2-3 DPS points behind Impact Knuckles in each category but easily beat them in Stamina by a whole lot. So, don't forget the speed values.

I understand the concern of all of them being essentially Fist Plus weapons, and why should they get any numbers beyond a certain threshold? They also need to feel that they're worth using at all, though, as they add a small amount of encumbrance and I'm not exactly sure if they slow the strikes down at all. Between regular gloves a survivor wears, and Unarmed Clothing on top, and possibly the suit for kicks/knees, the speed calculation is arcane to me. But I know that speed 77 makes the 9 Bash rather mediocre, all things considered. "Score Sum" does count stamina and that's not always a concern for late-game survivors, but it's not such an all-round weapon.

**Comment by fairyarmadillo** [comment]
A natural human being should probably not expect to be able to beat an ultra-muscled twelve foot tall undead monstrosity to death with their hands, no.

**Comment by Tharn** [comment]
Agreed, but seeing whether that was still the case was the point of the test there. And exactly at which points we see outcomes changing, and how. I honestly would have expected the 9 Bash to fare better than it did, which reassured me that we're erring on the side of caution with the new stats.

**Comment by fairyarmadillo** [comment]
Apologies then, I was reading that wrong.

One thing to consider is that these unarmed weapons by themselves really aren't even in the middle tier of what you can do with unarmed. A crustacean mutant who starts with 8 in every stat will get to 19 strength, and can further enhance themselves with bionics on top of that. The giant pincer mutation adds 12 bash damage and brutal strike, and the clawed mammal mutants can get +8 to +11 cut damage on their unarmed attacks, to say nothing of what hooves and saber teeth can do.

**Comment by Tharn** [comment]
It's interesting that you see this change as closing the door. I see it as the opposite.

I see this more as giving options to characters that want to go only (or more) towards CBMs, and generally giving some utility back to regular survivors with attainable and craftable answers rather than "perfect" answers like stacking certain mutations.

What Unarmed couldn't do before the change, it won't be able to do afterwards. But higher Bash thresholds give some breathing room to dealing with certain situations. The Piercing part of these items really only helps with the stuff that Unarmed can already do, so we're effectively curbing raw DPS vs. unarmed and agile foes and giving several items a chance to deal with Armor - if the armor is weak or the survivor strong enough.

But yeah, the separate Glove item, the stats and the skills all play into unarmed damage - so unlike with high-end medieval weapons the Unarmed Clothing only makes up what, 1/3rd of the capability overall?
