### ISSUE TITLE
Compiling with LOCALIZE=0 results in all random names being "Tom"

### ISSUE THREAD

**Issue by inverimus** [CleverRaven/Cataclysm-DDA#65640]
### Describe the bug

When I compile with LOCALIZE=0 everything with a random name is named Tom. This includes random character names, NPCs, cities, and random world names. Trying to randomize the world name does not change it.

The debug.log looks like it detects the language correctly, its only the random names that do not work.

13:22:11.744 INFO : Cataclysm DDA version 0.G-1864-g9a4259f567-dirty
13:22:11.745 INFO : [main] C locale set to en_US.UTF-8
13:22:11.745 INFO : [main] C++ locale set to en_US.UTF-8
13:22:11.748 INFO : [options] C locale set to en_US.UTF-8
13:22:11.748 INFO : [options] C++ locale set to en_US.UTF-8

### Attach save file

N/A

### Steps to reproduce

1. Compile with LOCALIZE=0

### Expected behavior

The normal name lists should be used.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling;
- Game Version: 0.G-1864-g9a4259f567-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]

**Comment by Inglonias** [comment]
What the hell?

**Comment by Ivan-Shestakov** [comment]
same here on version 0.F-15559-g7aab1255dc (on macos 13.4)

**Comment by BaumgeistOne** [comment]
Happens on my (linux) system too; really unfortunate, playing while everything and everyone is named "Tom" just isnt any fun at all...

**Comment by BaumgeistOne** [comment]
Could this be related to the change https://github.com/CleverRaven/Cataclysm-DDA/pull/65109 or the fix https://github.com/CleverRaven/Cataclysm-DDA/pull/65548 ?

@perryprog maybe some more ifdefs are missing?

**Comment by perryprog** [comment]
Thanks. Looking.

**Comment by perryprog** [comment]
In this case the solution wasn't more ifdefs, but less. Thanks again for the ping.

**Comment by BaumgeistOne** [comment]
Thank you very much! :D
