### ISSUE TITLE
Add a way to guaranteed obtain all prototype armor parts and hub-01 modular equipment

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#65652]
### Is your feature request related to a problem? Please describe.

In game exists tree more prototype hub-01 armor parts 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/35501aac-1842-431b-abc6-481f10c5f1eb)
But I didnt find any way to obtain them

### Solution you would like.

Add ability to buy prototype armor parts (helmet, greaves, vambraces, skirt, mantle) from hub-01 vendor, after completing first mission with robot-prototype. The best way is make it through dialog, buying them for gold coins
Because they are prototypes, so each prototype part will cost 1 coin
And sometimes you need to wait for too long to find modular head gear in hub-01 trade stock, so it will be fine, if we can buy it via dialog for 1 coin too, and also add ability to buy the same way modular defense system for 1 coin, becase may be you want to buy it for your companinons
As example, the scenario can be the next way: after completing first mission and finding corpse of dead scientist, when you return to hub, they will come to a decision, that to increase the survivability of their personal - its better to provide them with full set of prototype armor, not only skirt and mantle. And how, because its cheaper and faster to craft than ballistic, kinetic and fireproof types of armor - they have some of them in the storage for selling

### Describe alternatives you have considered.

Leave all as it is

**Comment by andrei8l** [comment]
They sell you better armor pieces once you finish two missions for them. You're not "their personnel" after one mission, but you can still get the full prototype set too if you pick the right dialogue option.

**Comment by KHeket** [comment]
> you can still get the full prototype set too if you pick the right dialogue option.

I checked all dialogs after first mission - there is no prototype armor I can get



> They sell you better armor pieces once you finish two missions for them. You're not "their personnel" after one mission

They do, but to get full set of needable armor can take for too long, and sometimes they didnt sell special parts, like modular headgerar or other parts, so it will be very good, if you cand guaranteed but modular defence and head gears and not best, but quite good for begining armor parts. And because my character is not their personnel - they will sell this armor for coins. If you are enough good to get for free h12 robot disarming rifle, nre recorder and ups with heavy battery in - I think you are enough good to buy prototype armor

**Comment by KHeket** [comment]
I checked files, you need int 10 to have ability to take full set, but also it dont have the headgear and helmet. So my suggestion is steel actual

**Comment by TieSKey** [comment]
Hey I second this. 
I think the modular defense system and the modular headgear should be always for sale after 1st mission. 
As it is now, there is a really good chance of them selling helmets that can't be used because you don't have the modular headgear. 

Heck, I have a 12 int character, already completed 3 missions, got a soldier helmet but can't use it for lack of the modular... feels really weird.
