### ISSUE TITLE
Unreasonable weights(and perhaps volumes) for extension cords and blade traps

### ISSUE THREAD

**Issue by shoozzzh** [CleverRaven/Cataclysm-DDA#65650]
### Describe the bug

An extension cord is 30 feet long. An outdoor extension cord is 100 feet long. But both of them weighs the same as jumper cable(0.07kg), which is too light. The same thing happens to their volumes.
The components of a blade trap all together weigh 2.66kg, but a blade trap weighs 6.14kg, which is against the law of conservation of mass.

### Attach save file

N/A

### Steps to reproduce

We all can see this in game.

### Expected behavior

I expected that extension cords and their outdoor variations should weigh much more than a jumper cable do. Maybe approximately in direct ratio to their lengths(a jumper cable is 3 feet long). So do their volumes.
A blade trap is supposed to weigh, at least, similarly to its components.

### Versions and configuration

Game Version: newest experimental build(on 5/15/2023)

**Comment by estebandellasilva** [comment]
On that note jumper cables seem to be to light too
