### ISSUE TITLE
Cannot pry open electronically locked wooden door despite description

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#65663]
### Describe the bug

I cannot activate my crowbar to pry open a wooden door with an electronic lock, despite the fact that the description of the furniture says I should be able to.

### Attach save file

[Athena-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11482861/Athena-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save file
2. Look at the door immediately to my character's west
3. Activate the crowbar
4. You can't

### Expected behavior

Either I should be able to pry open the door, or the description of the door should give me a reason I cannot.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 59c577e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    ASCIITiles overmap color fix [colors_fix_asciitiles],
    Lonely Evac Scenario [Lonely_Evac]
]

**Comment by Inglonias** [comment]
I am stupid. Activating the crowbar works as expected.

**Comment by GuardianDll** [comment]
If that's so, it can be fixed with #65552 then
