### ISSUE TITLE
Recipes that imply using a clay canning pot/canning pot don't work even if you fulfill all requirements

### ISSUE THREAD

**Issue by Kordian459** [CleverRaven/Cataclysm-DDA#65679]
### Describe the bug

I was trying to craft a 3L jug tomato sauce. 
Had all components and tools required  but the game doesn't allow me to start crafting.
Had the crafting book I needed in my inventory.
Tested with "nearby fire" and oven with full powered hotplate.
Also tested 0.5 L jug fruit jam, doesn't work.
"Byproduct: clean water" stays grey.

Tested similar recipes that use "pressure cooker" and have similar issues.

### Attach save file

N/A

### Steps to reproduce

1. get all tools needed for 3L jug tomato sauce
2. get all components needed for 3L jug tomato sauce
3. get an heating source (fire or electricity powered tools)
4. get a crafting book with 3L jug tomato sauce (like You Can Can At Home or Cucina Italiana)
5. try to craft 3L jug tomato sauce
6. game will show you that you have all requirements fulfilled (green lighted)
7. Byproduct line will stay grey
8. game won't allow you to craft this recipe
9. 

### Expected behavior

I'd expect to be able to craft my 3L tomato sauce jar

### Screenshots

![Immagine](https://github.com/CleverRaven/Cataclysm-DDA/assets/16650638/16f37285-93e5-4dc3-9611-bd9b1fb7a8f3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: a5245ca [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    MSX Alternative Floor Tiles [UDP_Old_Floor],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    MSX Fake Snow [UDP_BN_FAKE_SNOW]
]

**Comment by RenechCDDA** [comment]
No idea what is going on here but something that immediately strikes me is that the acid portion of the recipe is missing.

**Comment by RenechCDDA** [comment]
Debugging hammerspace gives us an actual error message: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/9af339dc-0983-4618-9edb-2db0f56a5b57)

It does not like that the tools and components (clean water) are the same.

**Comment by RenechCDDA** [comment]
I've confirmed this issue goes all the way back to the merging commit for the cooking energy cost rebalance (https://github.com/CleverRaven/Cataclysm-DDA/commit/4508944ecc70d5ca3570029cad071a83e0d88403).

So it was not broken by a subsequent change.

**Comment by RenechCDDA** [comment]
Interestingly, if we remove the canning_acid_large component (which isn't showing up in the GUI for some reason) it actually works.

*Doubly interestingly*, removing the using canning_low_heat entry does not allow it to work. 

Ah and.... canning_acid_large needs to be *components* not **tools**. Trying to define a second set of tools silently fails!

https://github.com/CleverRaven/Cataclysm-DDA/blob/7e63a04983ebd969a627898695549ea60f45c6bd/data/json/requirements/cooking_tools.json#L101-L107

So we have two issues. 

First, the direct symptom: canning_acid_large needs to be **components**! Simple json fix.

Second, including a requirements set like that silently fails... this needs fixing on the back-end.

**Comment by RenechCDDA** [comment]
>Second, including a requirements set like that silently fails... this needs fixing on the back-end.

Aaand this part is going to be someone else's problem as I have become thoroughly convinced it's outside my abilities.

**Comment by GuardianDll** [comment]
what about close this one as fixed by #65761, and make a new, that specify the silent fail issue separately?

**Comment by I-am-Erk** [comment]
I agree with GuardianDLL, it sounds like this was closed by #65761 but if nobody's done it yet, the silent fail should probably get an issue post.
