### ISSUE TITLE
Feedback about mobile portal storms 

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#65687]
### Is your feature request related to a problem? Please describe.

@Ramza13 
PR in question #65606

Having played the new portal storms, i would say it is a lot better than before, it is almost perfect with them being mobile weather now. Having a bunch of its danger be immobile or just creepy was also a really good idea which means you gotta pay attention where you going and a mistake will get you crippled bad, it seemed fun to be caught into a forest rather than "oh bother i gotta start another character" that was before.

In my opinion i feel the biggest issue is that the effects spawn TOO OFTEN, way way way too often and even an endgame character will get massively crippled if they spend even a few min outside much less the entire duration having to chase one to the center for the dungeon/rewards.

### Solution you would like.

*The constant movement restriction from the effects happening often make too swingy about you getting screwed because you constantly getting caged by darkness or re-winded every 4~5 turns. Maybe i got lucky but if the frequency of this effect was toned down, this would not be an issue at all. Maybe it could be one of the raise ires thing?

*Ire in general builds too fast and could be slowed down.

*The random pain gotta go tbh, it just gotta go. It gives you massive pain out of nowhere with basically no counter play. I'm usually not a fan of no counterplay effects like this and the previous ones but this one pretty much snowballs and spirals you into death, this is hands down the worst effect from everything happening now. Could also be a monster/obstacle that causes the pain or maybe reduce the pain tier to something much smaller so it would only punish you if you also get hit by other things along with it.

*Shifting masses/chunks of unknown will decimate you with their toughness/durability because of the all outlined above since you can just randomly get stuck or get max tier pain out of nowhere as they spawn very often. The chunks don't despawn either. Also they don't even drop artifacts anymore due to some bug, i killed dozens of them with no artifact drop, so portal storms feels extra bad with the high risk and low rewards. I know there can't be a carrot on a stick for every content but for something so risky like this, it will either hide in the basement again and completely ignore it or we can have something to actually tackle the content.

*Maybe could add an item that triggers or attract a storm? Or make the HUB01 quest about it.

**Comment by fairyarmadillo** [comment]
I think we should also tone the talking way down. It loses a lot of its oomph when you see the same specific lines over and over in rapid succession, not to mention the annoyance factor when they're interrupting actions.
