### ISSUE TITLE
There is no initial scenario selected when using scenario whitelisting

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#65692]
### Describe the bug

Very odd bug. This results in the default scenario being loaded and selected despite whitelisting done by a mod.
This is a regression. I am fully certain this has worked in the past.

@bombasticSlacks told me they would be willing to look into this.

### Attach save file

n/a, but you need to have a tiny mod instead:

```json
[
  {
    "type": "SCENARIO_BLACKLIST",
    "subtype": "whitelist",
    "scenarios": [ "wilderness" ]
  },
  {
    "type": "scenario",
    "id": "wilderness",
    "name": "Wilderness",
    "points": 0,
    "description": "You find yourself amongst trees.  The screaming and the moaning is fainter this far from civilization, but you'd better know what you're doing out here.",
    "start_name": "Wilderness",
    "allowed_locs": [ "sloc_field", "sloc_forest", "sloc_river" ],
    "professions": [ "naked" ],
    "flags": [ "LONE_START" ]
  }
]
```

Create an empty mod folder, put the above into scenarios.json and use a generic modinfo.json:

```json
[
  {
    "type": "MOD_INFO",
    "id": "scenariotestmod",
    "name": "Test mod",
    "authors": [ "NetSysFire" ],
    "description": "This is a test mod to reproduce a bug.",
    "category": "total_conversion",
    "dependencies": [ "dda" ]
  }
]
```

### Steps to reproduce

1. Create a world with the above mod. I also disabled the bionic professions one, but might not be related.
2. Now create a new character.
3. Press tab to switch to the scenario tab. Notice how the right panel already displays the correct scenario info:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59517351/3689e286-ae2b-4417-aeba-0d8580229631)

4. Press tab again.
5. Notice the full list of professions, as if you had the default scenario that is not even whitelisted.
6. Backtab. Press enter to explicitely select the only available scenario.
7. Notice how the selected entry is now green and you will no longer get the full list of professions when you press tab again.

In my case it is annoying and also disrupts my mod testing workflow because if I do not pay attention and do not do the extra keypress which is required to not trigger the bug, I will get a spawning error because I removed evac shelters in the full mod. The provided mod is as minimal as possible to just trigger the bug and do nothing else.

### Expected behavior

The weirdness does not happen.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 627309c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Test mod [scenariotestmod]
]

**Comment by bombasticSlacks** [comment]
@NetSysFire Is adding the external options a reasonable solution? Or do you think more needs to be done?

**Comment by NetSysFire** [comment]
Which external option?

>Afaik this has never worked without it.

I am 100% certain it has. According to file metadata, it last worked at around October 17th to 30th, possibly also up to December 5th or January 27th. Its when I last worked on that mod and modified those files.

**Comment by bombasticSlacks** [comment]
Sounds like it could be a regression from my Survivor Mode changes then. 

This is on my list to look into, there aren't many things on said list right now but I want to finish some other stuff up first :)

**Comment by NetSysFire** [comment]
It would be amazing if anyone of you could quickly confirm this so this issue will not get staled.
