### ISSUE TITLE
Make chainmail recipes reversible

### ISSUE THREAD

**Issue by ProfessorBright** [CleverRaven/Cataclysm-DDA#65696]
### Is your feature request related to a problem? Please describe.

I noticed the Horse Chainmail recipe is reversible, but the chainmail you can make for people to wear is not. 

I assume this is not intentional, and it seems weird that you can't snip apart the links in a chainmail coif, but I'm not an expert on chainmail. 

### Solution you would like.

Let players break down chainmail armor pieces into chainmail sheets. 

I assume just adding the reversible tag to all the chainmail pieces would be sufficient? Otherwise we'd have to make an uncraft recipe for each one, and that does seem taxing.

### Describe alternatives you have considered.

Make the horse chainmail non-reversible. Seems less realistic though.

### Additional context

The line to copy and paste into each chainmail recipe if we go that route: "reversible": true,

**Comment by MNG-cataclysm** [comment]
Apparently, a recipe cannot be reversable and have byproducts, and all the chainmail recipes have byproducts. We'd have to make uncraft recipes for the chainmail pieces.

**Comment by ProfessorBright** [comment]
I think Chainmail armor pieces don't have byproducts any more, or I am mis-reading something in the recipes.

Also I just spotted a mistake on my part: Coifs actually are reversible as of 5/12.  I only tested on leggings and sleeves and just made assumptions. Weirdness.
