### ISSUE TITLE
Bionic Claws CBM and the pseudo item it creates should be consistent in stats/description

### ISSUE THREAD

**Issue by cosmo-naut** [CleverRaven/Cataclysm-DDA#65707]
### Is your feature request related to a problem? Please describe.

The Bionic Claws CBM description states:

Vicious claws have been surgically installed inside your fingers, allowing you to extend and retract them at the cost of a small amount of power. These do considerable **_cutting damage,_** but prevent you from holding anything else while extended.

Where as the item it creates, `bio_claws_weapon` deals pierce and bash damage.
The item also has cutting and butchering qualities.

### Solution you would like.

`bio_claws_weapon` should be changed to reflect that it is used for predominantly cutting.
Currently the item has 8 bash and 16 pierce, I propose it should have 8 pierce and 16 cutting.

### Describe alternatives you have considered.

Change the description of the CBM so that it reflects this is a piercing and bashing weapon. 
Different damage values than the ones I listed above

### Additional context

[Bionic Claws CBM](https://cdda-guide.nornagon.net/bionic/bio_claws)
[bionic claws item](https://cdda-guide.nornagon.net/item/bio_claws_weapon)

**Comment by RenechCDDA** [comment]
Looks like a simple transcription error introduced with #64386

https://github.com/CleverRaven/Cataclysm-DDA/commit/b2ac3dd5e1c6402ef954e770f081855a75d804b4#diff-dbd725072a2fbc9605773da6918227536a0d977dcb3a13b9349eb2530b2e88d1

Doesn't appear to be a systematic problem.
