### ISSUE TITLE
Helmet pocket items that don't cover the head don't seem to cause encumbrance

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#65704]
### Describe the bug

Ablative pockets that contain stuff for a different limb don't encumber that limb. I don't know if they protect the limb either as that's harder to test but the limb doesn't show any encumbrance.

### Attach save file

n/a

### Steps to reproduce

1. Spawn a hard hat and face shield.
2. Wear hard hat with face shield.
3. Notice although face shield says "2 mouth and 2 eyes" encumbrance it actually has 0.

### Expected behavior

They should give the encumbrance they say they do. And provide protection if they don't actually do that (I don't know if they do and haven't tested)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: a4f928b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

this'll be really important for @Drew4484's project of putting pauldrons, gorgets and hip guards into pockets for various armors.

**Comment by Termineitor244** [comment]
/confirmed.

**Comment by bombasticSlacks** [comment]
I can fix this when I'm making some other changes to ablative armour, there will need to be a few meaningful changes for sure. Though yeah, as it stands, you need some coverage on a limb to have the ablative armour work at all. Though you don't need coverage on the sublimb which is the last thing I worked on.
