### ISSUE TITLE
Mutagenic Slurry decays should be consistent in what it decays into

### ISSUE THREAD

**Issue by cosmo-naut** [CleverRaven/Cataclysm-DDA#65706]
### Is your feature request related to a problem? Please describe.

Currently when the Mutagenic Slurry vitamin decays it becomes the following:
```
      [ "mutagen", 8 ],
      [ "mutagen_bird", 1 ],
      [ "mutagen_cattle", 1 ],
      [ "mutagen_feline", 1 ],
      [ "mutagen_fish", 1 ],
      [ "mutagen_gastropod", 1 ],
      [ "mutagen_insect", 1 ],
      [ "mutagen_lizard", 1 ],
      [ "mutagen_lupine", 1 ],
      [ "mutagen_medical", 1 ],
      [ "mutagen_mouse", 1 ],
      [ "mutagen_rat", 1 ],
      [ "mutagen_troglobite", 1 ],
      [ "instability", 1 ],
      [ "mutant_toxin", 2 ]
```

I'll ignore `mutagen`, `instability` and `mutant_toxin` and focus on the others because these just enable the system to work.

I believe the intended purpose is so that imbibing Mutagenic Slurry will give an even chance of random mutations.
However I notice some classes are absent, and some are present which perhaps should be absent.

Currently missing from this list are:

```
      mutagen_alpha
      mutagen_batrachian
      mutagen_beast
      mutagen_cephalopod
      mutagen_chimera
      mutagen_elfa
      mutagen_human
      mutagen_plant
      mutagen_raptor
      mutagen_rabbit
      mutagen_slime
      mutagen_spider
      mutagen_ursine
```

### Solution you would like.

I'm of the opinion that the mutagenic slurry should include all 'natural' mutation classes but exclude the 'man-made' mutation classes, as well as some of the aggregate classes.

This would mean removing medical from the pool, but adding batrachian, cephalopod, plant, rabbit, spider and ursine.
While choosing to leave out alpha, beast, chimera, elfa, human, raptor and slime.

### Describe alternatives you have considered.

Plant could go out, slime could go in.
One could make the argument that human could go in as well, maybe you're just as likely to mutate back to human as you are into other creatures.
Raptor could go in because technically it's natural, so could beast.

### Additional context

I'm pretty happy to take this on as my first issue in the repo, just wanted to get some eyes on it

**Comment by Maleclypse** [comment]
Does it even provide enough mutagen to allow the PC to randomly mutate or does it need to decay into several hundred of each vitamin or tens of them?

**Comment by fairyarmadillo** [comment]
Alpha, medical, chimera, beast, and elf-a are specially prepared cocktails that had to be specifically developed to work as they do. Slime is an alien and should probably be left out. Human would probably cause problems.

So those shouldn't be in the general pool. Everything else looks like it was omitted by mistake.

**Comment by cosmo-naut** [comment]
> Alpha, medical, chimera, beast, and elf-a

Should raptor be included in that list as well? I think it has its own research notes so I imagine it was also prepared

**Comment by cosmo-naut** [comment]
> Does it even provide enough mutagen to allow the PC to randomly mutate

If nothing has changed since the original PR #55233 then no. 
Relevant parts:
> Generic mutagen provides 325 generic "mutagen" nutrient, which is required for all mutations
and
> Every 30 to 45 minutes, a check will be done for the player having 450 or more generic mutagen vitamin

It seems to me however that the `325` figure might actually be off. A standard flask of generic mutagen creates 25u of mutagenic slurry, and each unit of slurry decays into 8 units of the mutagen vitamin for a total of 200, less than half what is required to start actually mutating.
