### ISSUE TITLE
Detaching shoulder strap from gun makes it wearable for free

### ISSUE THREAD

**Issue by Glimmerglaze** [CleverRaven/Cataclysm-DDA#65719]
### Describe the bug

Detaching a shoulder strap from a gun doesn't make it not a clothing item immediately, it only changes its coverage location to "nothing".

### Attach save file

[Mill Valley-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11509694/Mill.Valley-trimmed.tar.gz)

### Steps to reproduce

1. Download Stable (0.G). (I downloaded cdda-windows-tiles-x64-msvc-2023-03-01-0054.zip, specifically)
2. Choose SWAT Officer (or other profession with a shoulder strap gun)
3. Wield (or take off) gun.
4. Activate gun.
5. Detach shoulder strap from gun.
6. Wear gun.

### Expected behavior

Upon removing the shoulder strap, the gun should no longer be wearable, because it no longer has a shoulder strap.

### Screenshots

<img width="1920" alt="magic_gun" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/41975117/6cb7406b-a3d8-4e94-8182-a43f0e18226b">

The gunmod removal preview. Note the green bars and "Coverage: Nothing".

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

**Upon Save and Reload, the gun will correctly cease being wearable.**

It won't be unequipped, however. Fortunately, the game doesn't crash either. It will simply continue to list the gun as equipped, with no green bars.

Checking the Armor layer info screen, after removing the shoulder strap, the gun continues to be described as "water friendly". But it does lose the Cotton armor properties of the shoulder strap, and is listed with 4 Bash, 4 Cut, 2.50 Ballistic protection. The gun in this case is an MP5, which is made from Steel and Plastic, and indeed those values are the average of Steel and Plastic's inherent bash_resist, cut_resist and bullet_resist values in materials.json.

**Comment by Saylol222** [comment]
made a issue like this, some guy said it will be fixed or something

**Comment by Saylol222** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/65317#issuecomment-1523600790
