### ISSUE TITLE
Shorts Made from Cotton, killed for their leather

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#65714]
### Describe the bug

Shorts
Description says they are made from Cotton
Disassembly recipe suggest they are made from Leather

### Attach save file

N/A

### Steps to reproduce

Get some shorts
Look at the description
Disassemble them

### Expected behavior

Things made from cotton to not provide leather (while i do enjoy that its kinda unrealisitic)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/a89ea91d-a5c2-4d41-b95a-ac79bd34dbcd)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 3ea0365 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Karol1223** [comment]
Oh come on I thought I fixed that. Give me a moment.
