### ISSUE TITLE
0 damage crits are causing problems

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65717]
### Describe the bug

I'm don't know when this happened, but at some point it became possible to score critical hits without doing any damage - there used to be a minimum base damage you had to overcome, I think it was 5% of the enemy's HP, though I may be mistaken. This circumvents the need for weakpoint proficiencies and makes it trivial to stunlock any enemy, even ones you have no hope of hurting. 

This is probably inadvertantly overpowering several items and martial arts, which can presently tie armored enemies up with inescapable stuns and chip/bleed them down.

### Attach save file

N/A

### Steps to reproduce

Make a survivor with a cudgel, 1 strength, and 3 melee, walk up to a juggernaut and hold tab to keep it stunlocked for well over a minute.

### Expected behavior

There are instances (ie Aikido) where it may be reasonable to stun an enemy that you cannot damage, but an infant armed with a table leg should not be able to indefinitely halt an M1 Abrams main battle tank by lightly tapping it. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/fd99bae7-520d-4872-bcf8-6691068f4ff9)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/96546a13-045b-4d56-baa5-5498bc81f4f7)

This 1 strength 3 skill survivor with no martial art can indefinitely stunlock this juggernaut with a cudgel (proccing precise strike), provided he does not run out of stamina. At 6 or 7 strength, the character occasionally does damage, which can be enough to slowly kill the juggernaut, who cannot fight back at all.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: d3ea970 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'm not sure exactly what caused this. I can find https://github.com/CleverRaven/Cataclysm-DDA/pull/46455 but that's supposed to only work for ranged attacks, and it was reverted.

**Comment by fairyarmadillo** [comment]
Also, maybe unrelated, but 13/40 of the hits shown here are critical. That seems pretty high considering this is an enemy with 6 melee and a character with only 3.

**Comment by anoobindisguise** [comment]
> Also, maybe unrelated, but 13/40 of the hits shown here are critical. That seems pretty high considering this is an enemy with 6 melee and a character with only 3.

enemy melee doesn't affect your crit chance, crits just happen when you roll well above its dodge. if you roll even better than that you can get double crits. skeljug is a huge target and has 0 dodge so your melee rolls result in lots of crits.
not necessarily saying that's how it should work, that's just why it works like that.

**Comment by fairyarmadillo** [comment]
Closing this as it's not necessarily relevant thanks to the recent changes to stuns and zombies. TY Venera3!
