### ISSUE TITLE
Repair Problem Plastics - Maybe general Problem

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#65723]
### Describe the bug

Was trying to repair a Plastic Jerrycan with 2 of the listed Tools to do so.
Am Unable to perform the action

### Attach save file

[Elverson-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11511701/Elverson-trimmed.tar.gz)

### Steps to reproduce

Not sure if this is exactly reproducable - 
for me it was find certain items that should be repairable with a soldering iron 
try to repair them 
be unable to

### Expected behavior

if the item has listed the item it needs to repair - give me the ability to repair it

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/1cf516c0-aec4-4aab-bd1f-4f5bb7ac9312)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/23738de4-7f82-4116-b806-f9659f7cde46)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/d0b6eb59-5a4d-49c5-a45e-ddc793357917)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/51379614-4b77-4614-a690-a5b19bb265ff)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: e7264c3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I had the same issue with a car battery - officially it was listed as  repairable but i was unable to repair it

**Comment by ajkrupka** [comment]
I had the same experience with sheet metal and car batteries. I tried using a soldiering iron on it's own, one attached to a vehicle workstation, and one as part of a firearm repair kit, to no luck.

**Comment by Hirmuolio** [comment]
I think it is due to the degradation system. You can't repair item above its degradation level and the broken jerrycan you have has 3500 damage and 3500 degradation on it.

I don't think the degradation is visible anywhere without use of debug mode. I think it would be good to have degradation level shown similarly to how damage is shown.

**Comment by estebandellasilva** [comment]
Then the issue iss that its not being communicated that an items conditon is beyond repair

**Comment by Quintovir** [comment]
It seems that only car parts that have a green or have just reached orange degradation can be repaired with either an arc welder or soldering iron.

Here's a bunch of steel frames that are lightly damaged/degraded:
![Repair_Bug1](https://github.com/CleverRaven/Cataclysm-DDA/assets/28264543/7dcd5b47-9421-4268-a512-9726c38d31b7)
When I use an arc welder to repair them, only 4 on the west side can be repaired:
![Repair_Bug2](https://github.com/CleverRaven/Cataclysm-DDA/assets/28264543/2b348705-b315-4c6e-8621-4d5f20dcabfe)
