### ISSUE TITLE
"The The" on cunning feral's attack

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#65729]
### Describe the bug

One of the cunning feral's attack message has two "The" instead of one. My english may not be good, but i'm certain two "The" is excessive.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a cunning feral
2. let'em attack you
3. "The The"

### Expected behavior

one "The" instead of two

### Screenshots

![Screenshot_20230519-113323](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/8751e907-6f47-4d65-b42c-52aeb0e9f45b)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 9688cf4 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by Venera3** [comment]
Mattacks use display name (with a capitalized `The` leading). Removing the the starting with this line:
<https://github.com/CleverRaven/Cataclysm-DDA/blob/e7264c3b4d33036a5f310c3ec8a5d0a93187f784/data/json/monsters/feral_humans.json#L94>
will fix it.
