### ISSUE TITLE
Autodrive can drive you into the heated area around lava

### ISSUE THREAD

**Issue by StorytimeStorey** [CleverRaven/Cataclysm-DDA#65730]
### Describe the bug

The weight that tells autodrive "lava is dangerous" doesn't seem to take into account the area around lava. Had a character drive straight into adjacent lava squares. 

### Attach save file

N/A Only came up as a possible bug far after the save was lost

### Steps to reproduce

- find a lava vein along main travel route
- autotravel to the adjacent tile
- have your wheels melt and your body be viciously burned

### Expected behavior

The weight given to lava probably is working as expected. However I don't think it considers the area *around* lava to be dangerous. Extreme temperatures in a square is either not included in weight for pathfinding, or pathfinding with lava should be expanded to give the area around the lava a significant weight. 

I only know Dijkstra's when it comes to pathfinding, so I'm assuming that's the general idea here. 

### Versions and configuration

Windows 10
fd3e69b
stats with kills

**Comment by estebandellasilva** [comment]
It also does not avoid landmines it cannot see ...
