### ISSUE TITLE
Autowalk really wants to drown you

### ISSUE THREAD

**Issue by StorytimeStorey** [CleverRaven/Cataclysm-DDA#65731]
### Describe the bug

When autowalking near a river or body of water, it will use the shore as the safest method. However it will struggle to know that water *isn't* the best method of travel, and will constantly try to make you swim. If you misclick, you'll end up drowning. 

### Attach save file

N/A 

### Steps to reproduce

- Find a river
- autowalk somewhere nearby, especially with a bend in the river
- be wet

### Expected behavior

The weight given to deep water is clearly not enough. Swimming should be mostly a controlled task due to its danger. Currently it must consider deep water a low weight compared to other options.

I only know Dijkstra's in regards to pathfinding. 

### Versions and configuration

Windows 10
fd369b (tiles)
2023-05-05-0050

**Comment by KHeket** [comment]
Happend to me to. Sometime autowalk also like to try to go through acid splits or webs
