### ISSUE TITLE
Error: Json error: data/json/character_modifiers.json:134:13: denominator cannot be set to 0

### ISSUE THREAD

**Issue by Erranted** [CleverRaven/Cataclysm-DDA#65749]
### Describe the bug

Unable to start character creation process, game gives an error message and returns to main menu.

### Attach save file

N/A

### Steps to reproduce

Create new character (Either custom, preset, random, or "Play now!")

### Expected behavior

Character creation window opens up/Game starts

### Versions and configuration

OS: Windows 7 professional 64 bit service pack 1

Version: build type: windows-tiles-x64
build number: 2023-05-20-0514
commit sha: ddac6a3d8fb62a53f542dc017c39dbbdcce4fa00
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/ddac6a3d8fb62a53f542dc017c39dbbdcce4fa00

Tiles

Interface language: English 

### Additional context

Debug log

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11521778/debug.log)

Looks similar to https://github.com/CleverRaven/Cataclysm-DDA/issues/61095 so I upload `character_modifiers.json.-4753099152000.fb` from `data/cache/json/` because it was asked for in that post.
Also my system language is Russian (because it was asked if windows was with a non-US English default language or codepage), although path to game directory uses english-only symbols.

[character_modifiers.json.-4753099152000.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11521782/character_modifiers.json.-4753099152000.zip)

**Comment by ehughsbaird** [comment]
Are you using the `-msvc` build? #61095 and https://github.com/CleverRaven/Cataclysm-DDA/issues/63936#issuecomment-1460574950 (linked from #61095) seem to suggest that is the way to work around this.

**Comment by Erranted** [comment]
I've switched to `-msvc` build, and it works fine.
