### ISSUE TITLE
Crits should contest the higher of dodge or melee

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65759]
### Is your feature request related to a problem? Please describe.

Currently, crits are checked against monster dodge. This works fine for a lot of enemies, but creates a problem as the game progresses - most of our more difficult enemies are very large and have low dodge scores and are paradoxically easier to tie up with stuns.

Zombie Hulk - 5 melee, 0 dodge
Skeletal Juggernaut - 5 melee, 0 dodge
Armored Centipede - 6 melee, 0 dodge
Melded Task Force - 8 melee, 0 dodge
Shoggoth - 10 melee, 0 dodge
Frog Mother - 5 melee, 2 dodge
Skull Zombie - 4 melee, 1 dodge
Feral Security Guard - 6 melee, 1 dodge
Deathtrap Spider - 6 melee, 1 dodge
Cerbearus - 6 melee, 3 dodge
Giant Wasp Queen - 7 melee, 3 dodge

This means that at around 3 skill (where things like Eskrima's stunning strike tend to kick in), the primary consideration in combat becomes whether or not you are faster than the opponent. Relative skill and even the ability to deal damage quickly fall off dramatically. It doesn't quite trivialize these enemies, but the player's reward for improving their skill rapidly falls off once they can consistently crit.

This change would likely create a higher skill ceiling for melee fighters and reduce the overall dominance of fast stunning weapons without making these items useless. Characters of middling skill would still be able to stunlock individual zombies, and high-skill characters would perform more or less as they do now.

### Solution you would like.

Crits should either check the higher of an enemy's melee or dodge, or they should check the average of the two. Melee is a defensive skill for the player, and there's no reason it shouldn't be one for the enemy as well. A hulk isn't a sitting target, it's a fast and effective melee fighter which isn't likely to stand there and give an opponent easy openings.

It's easy enough to drop something like

```
bool Character::scored_crit( float target_dodge, melee_skill, const item &weap ) const
{
    return rng_float( 0, 1.0 ) < crit_chance( hit_roll(), std::max( target_dodge, melee_skill ), weap );
}
```

in melee.cpp, but there is more code in item.cpp which is beyond my ability to understand, seemingly related to calculating DPS on the weapon display.

### Describe alternatives you have considered.

Increasing dodge on bulky endgame monsters.

Giving large enemies an inherent resistance to crits.

Making armor or HP add some kind of crit resistance.

### Additional context

This only pertains to melee crits, which are handled separately from ranged ones. Ranged combat has its own problems, but they would need to be addressed separately.

**Comment by Venera3** [comment]
The core problem are not crits, it's the fuckton of CC techs that trigger off them - and the fact MA techs don't do any sort of filtering on target.

I do want to get around to that sometime this cycle, with techs filtering on target size/weight/bodytype/species/flags at least, and a consequent audit of all the techs in mainline, but it's not my next thing personally.

Re crit chance isolated I agree that including melee skill makes more sense than dodge, since the latter is a stand-in for everything from being tiny to being made of nether gloop, whereas skill correlates well with "should you melee this" pretty good in theory.

**Comment by fairyarmadillo** [comment]
It makes sense to me on some level that a sufficiently skilled (and statted) character could David and Goliath a juggernaut by striking weak points, getting it to trip over itself, etc, but 3 skill is like, basic familiarity with a subject, and such a person tapping a car-sized monster with a piece of wood isn't that, so it's good to hear it's being looked at.

If you haven't seen it, I also want to direct you toward https://github.com/CleverRaven/Cataclysm-DDA/issues/65717 which is exacerbating the problem.

**Comment by Venera3** [comment]
> It makes sense to me on some level that a sufficiently skilled (and statted) character could David and Goliath a juggernaut by striking weak points,

That's what weak points are for, then - which is why I'm of the personal opinion that crits asa concept are not really necessary anymore (but removing them would at the very least necessate a wholesale rewrite of all MAs).

**Comment by fairyarmadillo** [comment]
Wouldn't be the first time. Or the second. Or third 😆
