### ISSUE TITLE
Descriptions ignore Show Gun Brand Names

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#65778]
### Describe the bug

In description, even with "Show Gun Brand Names" option on, it still ignores those systems.

### Attach save file

[Nightmare-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11524893/Nightmare-trimmed.tar.gz)

### Steps to reproduce

1. Simply spawn in a gun. I'd recommend M18 as it is the one I use.
2. Check the description, "Compatible magazines" section.

### Expected behavior

Should've shown the actual Gun Brand-ed magazine names.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71143790/274541a8-c130-486e-87e8-6d4a0442124a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: c3ffd0c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    Bombastic Perks [bombastic_perks],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by DoctorBoomstick** [comment]
Can also confirm that this happens when viewing all the possible compatible guns for both magazines and gun mods, as well as when looking at the requirements for any craft which requires a firearm, like the Glock auto sear plate.
