### ISSUE TITLE
Make crude heating elements usable as well

### ISSUE THREAD

**Issue by BlueDragonFire** [CleverRaven/Cataclysm-DDA#65788]
### Is your feature request related to a problem? Please describe.

A large amount of crafting recipes that require heating elements do not accept using crude heating elements as an alternative. Notable examples are: most electrically heated clothing, the 60L heated tank, and the electric forge. 

According to HHG, heating elements are used in a total of 23 recipes while crude heating elements are only used in 12. Something I am sure is just a simple oversight.

### Solution you would like.

Allow crude heating elements to be used as an alternative in all recipes that require normal heating elements

**Comment by OmegaCenti** [comment]
I am attempting to add cruse heating elements to all recipes that use normal heating elements as a new contributor. Hopefully this is something I can cut my teeth on, so to speak
