### ISSUE TITLE
Unarmed XP still broken

### ISSUE THREAD

**Issue by Heitomos** [CleverRaven/Cataclysm-DDA#65780]
### Describe the bug

I started a Black Belt at level 8. After killing over 100 zombies with my bare fists, I didn't gain a single % of XP. Using Maui Thai, and 

Testing
Unarmed 0 to 5: Some XP is gained, but only on misses. Actual hits seem to be ignored.
Unarmed 6+: No XP seems to ever be gained.

Melee 6+: XP still trickles in as you fight.

### Attach save file

N/A

### Steps to reproduce

1. Create a Character with 0 Unarmed.
2. Fight some stuff
3. Observe XP gain
4. Increase Unarmed to 6+ with debug
5. Murder loads of stuff
6. Observe no XP gain

### Expected behavior

I should see my XP increase, if slowly, when murdering a horde.

### Versions and configuration

- OS: Windows
Version: Latest Experimental

**Comment by fairyarmadillo** [comment]
Skills don't train if you outlevel your opponent. Six skill is more than almost any monster in the game has.
