### ISSUE TITLE
Thyme oil should not be perishable

### ISSUE THREAD

**Issue by BlueDragonFire** [CleverRaven/Cataclysm-DDA#65787]
### Is your feature request related to a problem? Please describe.

Both thyme and cooking oil are non-perishable items. I don't consider this a bug, but it does not make sense that the product of two non-perishable items results in something that is not only perishable, but also only lasts 4 weeks. This also makes thyme oil one of if not the only perishable anti-septic in the game.

### Solution you would like.

Make thyme oil non-perishable

**Comment by Tharn** [comment]
Strictly speaking, you don't make essential oil by mixing regular oil with a herb 1:1. You use the pure herb and distill the essential oil out of it. So what we're having in-game are not actually essential oils, and in that sense they could be perishable as a homemade oil-based balm with plant essence would be.

Also, wintergreen oil is made by exactly the same formula, however it's called an "ointment infused with wintergreen oil" which is closer to what it actually is. I'd suggest all 3 items either get a description similar to wintergreen oil, or all 3 have their recipes changed & the cooking oil part removed.

And in that case, they could all be made non-perishable. This is speaking strictly from a realism standpoint. From a usefulness standpoint, all 3 items are not particularly great and bothersome to craft. I would just make all 3 non-perishable regardless.

**Comment by BlueDragonFire** [comment]
Not a bad idea, though thyme oil is actually very useful as an ingredient in making bandages

**Comment by Tharn** [comment]
Yes, it just takes a lot of time to produce a single thyme oil, and who goes and does a big-scale thyme farm? That's what I mean. ;)
