### ISSUE TITLE
Test suite sometimes emits errors when trying to place om specials

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#65798]
### Describe the bug

The "basic build and test" is too frequently falsely failing .

There is an overmap specials placement error here:
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5041755441/jobs/9041739756#step:16:213

also the same errors at:
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5038528633/jobs/9036093563#step:16:353

Fixing this is beyond my capabilities. Hopefully someone will notice this and fix this problem.

### Attach save file

N/A

### Steps to reproduce

1. Create a PR.
2. See that "Basic Build and Tests" failed.
3. Find out this error message.

### Expected behavior

There should be less false positive in Basic Build and Tests.

### Versions and configuration

N/A

**Comment by Tread4** [comment]
Can confirm - had my PR tests fail due to issues with generation of mutated monster overmap specials.
My PR was not even remotely touching overmap, map or locations code so the fail seems unrelated to it.

**Comment by SurFlurer** [comment]
Closing now as it's improved a lot these days.
