### ISSUE TITLE
Way to forget a specific recipe

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#65797]
### Is your feature request related to a problem? Please describe.

Xedra evolved adds few research mechanics. To prevent use to research more stuff there exist in remainder, I'd like to remove recipes in the end. Alas, there is no way to perform it

### Solution you would like.

Being able to remove recipes from character's brain

**Comment by WreckingAbandon** [comment]
Would Hide not be enough?

**Comment by GuardianDll** [comment]
Player may miss the fact they have nothing to research
Tho now i think it may cause issues, if someone tries to add new thing into research, but player has no recipes anymore

**Comment by Maleclypse** [comment]
Can’t you set a false effect message “there are more more recipes to learn this way”?

**Comment by GuardianDll** [comment]
i did, but i found it is not as clear
i transformed it into popup now, but it is not merged yet
