### ISSUE TITLE
Cant start the game

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#65792]
### Describe the bug

for whatever reason i cant seem to start the game on my phone

### Attach save file

N/A

### Steps to reproduce

1. open the game on mobile
2. crash

### Expected behavior

not crashing

### Versions and configuration

- OS: Android 7
- Game Version [ 1898b63 (32-bit)
- Graphics Version: Tiles

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11526545/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11526547/debug.log)

**Comment by WreckingAbandon** [comment]
Can confirm.

It also mentions something about a VOID, but I didn't read expecting it to reappear again in case the crash was not a fluke.
