### ISSUE TITLE
Dehydrating food with a dehydrator requires several times the charge its battery can actually hold.

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#65799]
### Describe the bug

After the "fix" to cooking energy costs it takes 1980 charges(!?) to dehydrate meat and 990 charges for most other food which is somewhat of an issue considering the medium batteries of the food hydrator only hold 500 charges when fully charged... 

### Attach save file

N/A

### Steps to reproduce

Try to dehydrate some food with a battery powered food dehydrator.

### Expected behavior

That the food dehydrator is capable of dehydrating food

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: 620e114 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Karol1223** [comment]
The problem is the food dehydrator still using batteries. Should be solvable after the PR for connecting items to the electric grids gets merged.

In the meantime use the modular kitchen rig with the dehydrator attached as a substitute.
