### ISSUE TITLE
New Civilian Monsters are too Plentiful

### ISSUE THREAD

**Issue by XP-Whiz** [CleverRaven/Cataclysm-DDA#65796]
### Is your feature request related to a problem? Please describe.

As of #64142 being merged there are a few new neutral civilian monsters that are meant to depict humans that haven't gone feral but haven't evacuated cities or have remained trapped in them. I'm posting this issue to hopefully invite further civil discussion on the implementation.

My main issue with these new monsters is that there's an abundance of them. I play pretty frequently and have already put a relatively significant time into the version with these new monsters, even though it was merged only hours ago. I've already played several city starts, and it needs to be said that for every 5 road tiles in cities, there's about 5 or more panicked/petrified civilians.

This seems bizarre considering the lore as well as gameplay implications. The half-life of these civilians evolving into feral humans is half a day, which also means that if you don't spawn in a city, approaching one will be met with more than double the amount of ferals you'd usually see.

### Solution you would like.

I'd like to see the spawning of these new monsters be greatly reduced. It doesn't make sense in terms of lore or gameplay for there to be hordes of non-feral humans roaming cities just for them to evolve the next day. I'd also like to see the areas they can spawn and their behavior tweaked a bit.

### Describe alternatives you have considered.

I'm open to hearing what others have to say about alternatives and compromises, but personally I think the spawning just needs to be tweaked to make more sense and be less intrusive. 

### Additional context

I'd like to state just for the record that I actually love this merge. I almost exclusively play city starts and I think it brings extra strategic movement and intrigue to an otherwise monotonous game of running from downspout to downspout. I think the author of the merge has great ideas and implemented them beautifully other than the amount spawned.

**Comment by NetSysFire** [comment]
Author of said PR here. Glad you like it.

>My main issue with these new monsters is that there's an abundance of them.

That is intended actually, but I explicitely asked for feedback in my PR but unfortunately did not get any regarding the number of spawns. They are designed to die quickly. On day one, there will still be a fair amount left and due to monster upgrading, their numbers will dwindle quickly.

Of course, I still get your issue with this. I can try reducing the pack size every day and make them evolve more often into zombies than ferals.

>I'd also like to see the areas they can spawn and their behavior tweaked a bit.

What do you have in mind?

Also, do you have any other feedback, as you appear to have played with the change a lot so far? E.g would you think that adding subtypes of those civilians (e.g a panicked person which is searching for their family or a petrified person who only spawns in the ICU beds of a hospital) could be worth it?

**Comment by XP-Whiz** [comment]
> That is intended actually, but I explicitely asked for feedback in my PR but unfortunately did not get any regarding the number of spawns. They are designed to die quickly. On day one, there will still be a fair amount left and due to monster upgrading, their numbers will dwindle quickly.

I get that, and I have to say I'm mixed on the abundance of spawns after playing longer. In hindsight, I only really ever saw how they work in small or medium sized towns. Maybe in the larger towns they die a lot quicker, which again would be a part of the reason I like this merge a lot. It sorta shakes up zombie movement from slow shuffles in random directions to various packs chasing roaming civilians. 

> Of course, I still get your issue with this. I can try reducing the pack size every day and make them evolve more often into zombies than ferals.

I was under the impression that they only evolve into ferals. If I'm mistaken and they evolve into zombies as well, that actually changes a lot. I figured it would be a situation where if left unchecked outside of the reality bubble, clumps of the civilians would all evolve into ferals at once.

> What do you have in mind?

For this section, I actually take back what I said. I played a bit longer and I don't think it's actually an issue.

> Also, do you have any other feedback, as you appear to have played with the change a lot so far? E.g would you think that adding subtypes of those civilians (e.g a panicked person which is searching for their family or a petrified person who only spawns in the ICU beds of a hospital) could be worth it?

For feedback of what I've seen so far, it looks like the only issue of genuine concern is that for the outskirts of towns or just small towns in general, the civilians seem to outrun the zombies into the wilderness, causing some small towns to be almost pre-cleared. For the subtypes though, I'd actually love to see stuff like that. That sort of flavor and depth to the world is what makes CDDA stand out, I think. I was sort of playing around with the idea in my head of a petrified civilian covered in blood and guts that the zombies ignore in the way they ignore ferals.

All in all, after playing more, I'm starting to the number of spawns as something that isn't necessarily a bad thing. Honestly can't wait to see what the spriters come up with as well if we get various sprites.

**Comment by Nebnis** [comment]
Someone raised a point in the discord that you don't turn into ferals progressively, you either are one or aren't. And if i interpreting the docs correctly, these are one of the part of the population that are only affected by the blob psychosis but not necessarily full feral, kinda like a stuck limbo. I feel like they should just evolve to zombies instead(meaning they died) because as outlined by the OP, this is kinda making the feral population bigger.

Which raises something else i was wondering about , would they be able to feed themselves? Because i would like to see their half life extended and maybe spawn some in cabins/farms/etc as well. Probably a variant from cities that aren't prone to get themselves killed in isolation.

**Comment by NetSysFire** [comment]
>Someone raised a point in the discord that you don't turn into ferals progressively, you either are one or aren't.

I am only in the development channel via an IRC bridge. And yes turning them into zombies is something that I will fix, together with the other issues.

>Which raises something else i was wondering about , would they be able to feed themselves?

They are the ones who will die during the initial chaos, as outlined in the PR description. The things you are thinking of are NPCs.

**Comment by sadenar** [comment]
Maybe a way to make them a little bit less of an issue would be to limit their spawns to areas where it would have made sense for large amounts of people missing evacuation/massing up and where these new monsters/npc-like creatures would have had a chance to survive until game start?

That or like XP said, to him it seems to be mostly a gameplay issue with smaller city sizes, so I have no idea how monster spawning works, but would there be a way to disable them spawning in cities under a certain number of overmap tiles?

**Comment by fairyarmadillo** [comment]
A possible fix for this might be to look at redoing the timing of these enemies and the starting scenarios. It occurs to me that if there are a bunch of sufficiently sophisticated crazed civilians around, the game might convincingly represent an earlier stage of the Cataclysm. Then you could have a starting option that's like "one day post cataclysm" that's closer to what we see now, or you could begin a week (or whenever) earlier when there are more of these dudes around.

**Comment by anoobindisguise** [comment]
These ones should probably turn into zombies instead of ferals. Given that they actively are getting killed by zombies they wouldn't feralize.
