### ISSUE TITLE
Insta crash on Latest Android x32

### ISSUE THREAD

**Issue by FickDiddler** [CleverRaven/Cataclysm-DDA#65800]
### Describe the bug

On the Latest Android x32 version, the app just instantly closes the moment I open it after it's done downloading the files.

### Attach save file

N/A

### Steps to reproduce

1. Download the app.
2. Watch it crash the moment it is done downloading the files.
3. It also crashes if you try opening it again.

### Expected behavior

Playability.

### Versions and configuration

Latest Android x32

**Comment by NetSysFire** [comment]
Closing as duplicate of #65792
