### ISSUE TITLE
crash when repairing with UPS modified soldering iron and makeshift welder

### ISSUE THREAD

**Issue by Wilkman26** [CleverRaven/Cataclysm-DDA#65825]
### Describe the bug

crash when repairing with UPS modified soldering iron and makeshift welder

### Attach save file

[Maxville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11549143/Maxville-trimmed.tar.gz)

### Steps to reproduce

1. a to active an item
2. select either makeshift welder or soldering iron
3. attempt to repair lockpick kit or car battery

### Expected behavior

I should be able to repair car battery and car battery without the game crashing

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 6169c4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 6169c4f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff6b11ea6a4[cataclysm-tiles.exe+0x25a6a4]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x14025a6a4),
    0x14025a6a4    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/ios_base.h:1121    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff6b11cbdb3[cataclysm-tiles.exe+0x23bdb3]), 
    (libbacktrace: log_crash+0x1de@0x14023bdb3),
    0x14023bdb3    src/crash.cpp:918    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x14023bdb3    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:85    log_crash
  #2
    (dbghelp: @0x7ff6b11cbfdb[cataclysm-tiles.exe+0x23bfdb]), 
    (libbacktrace: signal_handler+0x52@0x14023bfdb),
    0x14023bfdb    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:137    signal_handler
  #3
    (dbghelp: @0x7ff6b1baf862[cataclysm-tiles.exe+0xc1f862]), 
    (libbacktrace: gnu_exception_handler+0x152@0x140c1f862),
    0x140c1f862    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crt_handler.c:287    _gnu_exception_handler
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ff9b1b87ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ff9b27f23df[ntdll.dll+0xa23df]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ff9b27a14a4[ntdll.dll+0x514a4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ff9b27f0f0e[ntdll.dll+0xa0f0e]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff6b0fdcaac[cataclysm-tiles.exe+0x4caac]), 
    (libbacktrace: repair_item_finish(player_activity*, Character*, bool)+0x96a@0x14004caac),
    0x14004caac    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/tuple:2328    repair_item_finish(player_activity*, Character*, bool)
  #9
    (dbghelp: @0x7ff6b2272a97[cataclysm-tiles.exe+0x12e2a97]), 
    (libbacktrace: std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const+0x27@0x1412e2a97),
    0x1412e2a97    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/stdio.h:591    std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const
  #10
    (dbghelp: @0x7ff6b0ff6938[cataclysm-tiles.exe+0x66938]), 
    (libbacktrace: activity_type::call_finish(player_activity*, Character*) const+0x3e@0x140066938),
    0x140066938    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/char_traits.h:162    activity_type::call_finish(player_activity*, Character*) const
  #11
    (dbghelp: @0x7ff6b187ddd2[cataclysm-tiles.exe+0x8eddd2]), 
    (libbacktrace: player_activity::do_turn(Character&)+0xa9c@0x1408eddd2),
    0x1408eddd2    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/std_function.h:372    player_activity::do_turn(Character&)
  #12
    (dbghelp: @0x7ff6b123ea18[cataclysm-tiles.exe+0x2aea18]), 
    (libbacktrace: do_turn()+0x734@0x1402aea18),
    0x1402aea18    src/gamemode.h:549    do_turn()
  #13
    (dbghelp: @0x7ff6b26b0a5c[cataclysm-tiles.exe+0x1720a5c]), 
    (libbacktrace: main+0x23e2@0x141720a5c),
    0x141720a5c    src/main.cpp:823    main
  #14
    (dbghelp: @0x7ff6b0f913ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: _tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #15
    (dbghelp: @0x7ff6b0f914c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #16
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff9b0fe7614[KERNEL32.DLL+0x17614]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #17
    (dbghelp: RtlUserThreadStart+0x21@0x7ff9b27a26a1[ntdll.dll+0x526a1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by RenechCDDA** [comment]
Update to latest, this should be resolved by #65708

**Comment by Wilkman26** [comment]
Just confirming that updating to latest experimental did fix the issue. Thanks again.
