### ISSUE TITLE
allow guns to be used with turret mounts while gun mods are attached.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#65821]
### Is your feature request related to a problem? Please describe.

As of action taken in PR #64934, weapons such as the AR-15, M27 IAR, M4A1, and M16A4 can no longer be mounted as turret guns due to the fact that they require, like the HWP, an installed gun mod to fire. 

### Solution you would like.

Weapons should be mountable even with gun mods installed.

### Describe alternatives you have considered.

If it would be simpler to implement, then allowing guns to be mounted with just a mod in the bore slot would also fix this issue, though I believe it’d be all around better if we simply allowed any mods to remain on a weapon when it’s mounted.

**Comment by Tharn** [comment]
Adding to this, could the rail or underbarrel mount be required to be present & unoccupied as the attachment point for the turret?
