### ISSUE TITLE
[Magiclysm] I believe the summoned druid bow got missed in the bow damage rework

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#65826]
### Describe the bug

The crafted druid bow and the summoned druid bow should be on par with each other.
Unless I'm misunderstanding how damage is calculated for it since it doesn't use real arrows, I believe it's damage should be 9 instead of 29

the crafted bow is at: data/mods/Magiclysm/items/enchanted_ranged.json : rune_druid_weapon
the summoned bow is at: data/mods/Magiclysm/items/ethereal_items.json : druid_recurve

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

current code base

### Additional context

Should be an easy PR

**Comment by GuardianDll** [comment]
It deal 29 damage because it has lack of 5x crit damage
It has lack of crit damage because it uses no ammo

**Comment by Xpyder** [comment]
29 damage vs 9 with a x5 crit, the 9 would have to crit 64% of the time if I'm mathing correctly.

I've not done a lot of archery since the bow changes as I've found bows to be underwhelming.  Is that a reasonable average for someone with good bow skills?  Or am I misunderstanding the math?

**Comment by Xpyder** [comment]
That sounds reasonable then.
