### ISSUE TITLE
Throwing items can cause crash

### ISSUE THREAD

**Issue by Mer1ck** [CleverRaven/Cataclysm-DDA#65834]
### Describe the bug

Throwing an item past an enemy causes a segmentation fault CTD.
When throwing an item at an enemy, it works as expected an nothing really happens. Though, if you aim just past the enemy, the game freezes and crashes with a segmentation fault if it happens to hit the monster/npc. If the item misses, it lands on the floor behind them as expected. This was tested using several different items on both a monster and npc.

### Attach save file

Attached below with crash logs

### Steps to reproduce

Find an npc/monster
Find a rock or something similar
Aim one tile past the npc/monster
Throw item, and repeat until crash.

### Expected behavior

Item should either miss, or impact and resolve as if you had aimed at the creature.

### Versions and configuration

OS: Windows 10 x64
Version: 09b378d x64 
Graphics: Tiles
Language: English
Mods: DDA

### Additional context

Zip file containing a testing save and relevant .log files attached below.
[Throwing Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11554029/Throwing.Crash.zip)

**Comment by anoobindisguise** [comment]
- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: e565014 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

Seeing the same thing happen.

**Comment by anoobindisguise** [comment]
/confirmed
can I run that command?
