### ISSUE TITLE
"Psychopath" trait shouldnt disable "Killer Drive"

### ISSUE THREAD

**Issue by harmez7** [CleverRaven/Cataclysm-DDA#65849]
### Describe the bug

they disable each other so you cant have both of them on your character

### Steps to reproduce

try to have both "Psychopath" and "Killer Drive" trait on your character

### Expected behavior

i think you can be a Psychopath & enjoy killing at the same time

**Comment by GuardianDll** [comment]
FYI if you plan to make a pull request, it's not necessary to make an issue

**Comment by harmez7** [comment]
ok thanks

**Comment by harmez7** [comment]
it was a wrong issue anyways
