### ISSUE TITLE
Disassembing item causes deadlock (+ looping memleak)

### ISSUE THREAD

**Issue by sdgoihew** [CleverRaven/Cataclysm-DDA#65845]
### Describe the bug

As in title. Item is a shirt, that contains 3 subitems (in pockets, including smartphone with 120/120 battery in it).

(dunno if useful) Stacktracing responsible thread gives:

remove_ammo + 5e

0 cataclysm-tiles.exe!itype::has_flag+0x30
1 cataclysm-tiles.exe!item::has_flag+0x11a

...
22 cataclysm-tiles.exe!malloc_base+0x44
...
28 cataclysm-tiles.exe!free_base+0x1c
...
30 cataclysm-tiles.exe!item::is_frozen_liquid+0x23
...
34 cataclysm-tiles.exe!std::vector<double,std::allocator<double> >::_Emplace_reallocate<double const & __ptr64>+0x167
...

0 cataclysm-tiles.exe!string_id<json_flag>::is_valid+0xd
1 cataclysm-tiles.exe!item::has_flag+0x18

19 cataclysm-tiles.exe!Character::i_add+0x1a5

16 cataclysm-tiles.exe!item::gunmod_find+0x20

4 item::is_null + 40
...
12 item::has_flag + f0

remove_items_with + 10e

19 cataclysm-tiles.exe!disassemble_activity_actor::start+0xa4

0 cataclysm-tiles.exe!safe_reference_anchor::safe_reference_anchor+0x38

0 cataclysm-tiles.exe!std::_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,int> >,0> >::_Find_lower_bound<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >+0x21

0 cataclysm-tiles.exe!std::_Tree<std::_Tmap_traits<string_id<itype>,std::vector<item,std::allocator<item> >,std::less<string_id<itype> >,std::allocator<std::pair<string_id<itype> const ,std::vector<item,std::allocator<item> > > >,0> >::_Copy<std::_Tree<std::_Tmap_traits<string_id<itype>,std::vector<item,std::allocator<item> >,std::less<string_id<itype> >,std::allocator<std::pair<string_id<itype> const ,std::vector<item,std::allocator<item> > > >,0> >::_Copy_tag>+0x1e

4 cataclysm-tiles.exe!item_contents::item_weight_modifier+0x3e
...
10 cataclysm-tiles.exe!item::weight+0x6d1

0 item_pocket::is_type + 7
1 item_contents::best_pocket + ae
2 item::best_pocket + 4f

### Attach save file

[inhell-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11560019/inhell-trimmed.tar.gz)

### Steps to reproduce

1. Make a player, Undercover Operative
2. Try to disassemble your shirt on turn 1

### Expected behavior

-

### Versions and configuration

win10 x64, 81746f6, tiles, default mods

**Comment by RenechCDDA** [comment]
Specifically the "dress shirt" (not the long-sleeved shirt they also come with!) and only occurs when the smartphone is in its pockets. No other items are required.
