### ISSUE TITLE
Zombies taking double professions

### ISSUE THREAD

**Issue by Ruminator24** [CleverRaven/Cataclysm-DDA#65842]
### Describe the bug

When killing zombies, sometimes zombies will drop certain profession "sets", such as a mechanic or a mailman, but lately i've been seeing a lot of times where when killing zombies, it will end up with zombies having double "sets", with zombies carrying both mailman and mechanic sets. I have also seen this problem with the motorcycle sets, where the zombies will spawn with it, ALONG with the regular clothing drops, so you end up with "impossible" combinations.

### Attach save file

N/A

### Steps to reproduce

1. spawn in any regular world (this happens even with default loot settings)
2. spawn in zombies or encounter zombies, and then kill them
3. when you find certain zombies, note that you'll see double sets.

### Expected behavior

I would expect them to spawn with only one set of profession based clothes.

### Screenshots

![buggy motorcycle clothing drops](https://github.com/CleverRaven/Cataclysm-DDA/assets/131492998/a875940a-d25c-4aa4-a0e7-85c282ad82a0)
![double profession](https://github.com/CleverRaven/Cataclysm-DDA/assets/131492998/502583be-4187-4a87-ac08-4fe27fea8a5b)

### Versions and configuration

- Windows 10
- ddd274c
- tiles
- english
- basegame start (meaning all mods as if loaded by default)

**Comment by fairyarmadillo** [comment]
I messed with those a month ago in https://github.com/CleverRaven/Cataclysm-DDA/pull/65234/files but I don't think anything I did would be causing this.

**Comment by Ruminator24** [comment]
Yeah, im not sure what's causing this, but I know i've seen the motorcycle clothes stacking with other things before, even in stable G
