### ISSUE TITLE
No Hope mod, probably: Caravan Merchant and two guards keep spawning near PC, destroying whatever stuff they land on upon spawn

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#65843]
### Describe the bug

When reading/sleeping/practicing and similar activities, a Caravan Merchant and two guards randomly spawn near the PC, destroying whatever stuff they land on (my electric car for me). Sometimes they also spawn with a vehicle so banged up you wonder how they were able to drive that junk.

### Attach save file

N/A

### Steps to reproduce

1. Play with No Hope mod
2. Try to settle in a base
3. ~~So~~ Do something
4. Weird Caravan stuff starts happening

### Expected behavior

I'm not sure. Spawn them somewhere else. On roads maybe. Or check that they spawn on a sensible spot with nothing to destroy. Not on top of my electric car :(

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/29348635/a6e70c85-3074-4894-91e0-e645084c25a8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/29348635/93748df1-ff23-479c-8382-171f07addfdf)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: 81746f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope]
]

### Additional context

It is the fourth time this happened in this run, as described here:

https://www.reddit.com/r/cataclysmdda/comments/txi29j/comment/jlfhp4s/?utm_source=share&utm_medium=web2x&context=3

In the attached image, the group spawned in the same spot twice, on top of the electric car. The second image was the first time, the first my second. This time with a truck.

**Comment by AzyWng** [comment]
Been having this issue with my own save as well - only, I haven't installed any mods besides the default ones.

**Comment by KHeket** [comment]
@bombasticSlacks can you check? Because I saw only you mostly worked on randenc_caravans.json and eoc

**Comment by bombasticSlacks** [comment]
@andrei8l just figured out the issue. A fix should be coming soon.
