### ISSUE TITLE
It is possible to scan books in merchant's inventory without buying them

### ISSUE THREAD

**Issue by Demivan** [CleverRaven/Cataclysm-DDA#65840]
### Describe the bug

It is possible to scan books that are in merchant's (probably in any other character) inventory without buying them.

In merchant's case, this leads to getting all his books for free.

### Attach save file

N/A

### Steps to reproduce

1. Stand near merchant that have books in their inventory
2. Select "Store a book" from e-ink tablet action list
3. There are books from nearby merchant's inventory listed for scanning
4. You can successfully scan a book

### Expected behavior

Books in merchant's and other character inventories should not be scannable.

### Screenshots

![screenshot_2023-05-24_22-20-11_439975570](https://github.com/CleverRaven/Cataclysm-DDA/assets/2339406/00e80735-d139-4996-b295-b9e3187a4f7a)
After successful scan:
![screenshot_2023-05-24_22-28-14_831241636](https://github.com/CleverRaven/Cataclysm-DDA/assets/2339406/a1ef8969-1a31-424b-8b58-56044aac6e0c)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 4704851 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Qrox** [comment]
Perhaps they are releasing the books under the CC BY-SA 3.0 license.

**Comment by inverimus** [comment]
Does this have to do with being able to scan unread books now which doesn't pick them up?

**Comment by FATM0USE** [comment]
it almost certainly does since this also apples to books that are flagged as owned but not being carried by anyone (like all the books in the refugee center).
