### ISSUE TITLE
Guns too tiny for carry holster(And other problems?)

### ISSUE THREAD

**Issue by Ruminator24** [CleverRaven/Cataclysm-DDA#65847]
### Describe the bug

The new carry guns that the zombies have is cool, but there's a few oddities with them. One oddity is that some guns will not spawn in their holster, but instead in the zombie's inventory. Another oddity is that when a gun does spawn in the holster, it will have no magazine if it's a semiautomatic.

### Attach save file

N/A

### Steps to reproduce

1. spawn a ton of zombies and then kill them all
2. check zombies for concealed carry and notice that it's a bit wonky

### Expected behavior

I would expect holstered guns to at least have their magazines, even if it's empty, or that the guns spawned with the zombie to have a fitting holster.

### Screenshots

![too smalle](https://github.com/CleverRaven/Cataclysm-DDA/assets/131492998/0816f3db-540f-4f43-bec1-e84ad870eb34)
![no magazine](https://github.com/CleverRaven/Cataclysm-DDA/assets/131492998/ef829e37-bc8a-4568-8468-43f49c8839a8)

### Versions and configuration

- Windows 10
- ddd274c
- tiles
- english
- basegame start

### Additional context

I'd assume the problem would be remedied by simply adding more types of holsters that can spawn with the zombie for concealed carry, especially for smaller guns. I'm not sure what causes the magazine problem, other than there being a problem with how charges are set.

**Comment by RenechCDDA** [comment]
There's a debug message if the container-item of an item group is too small to contain its contents. For the first image you posted, the Ruger is actually **too small** (160mL vs 250mL minimum) to fit in the holster (so the opposite problem, and one that does not have a debug message afaik).

I can't confirm whether they're actually from the same item group at the moment.

**Comment by TimPollard** [comment]
Yeah, it probably needs a re-work to get two lists of guns, one for full size holsters, and one for small holsters. (Alternatively the holsters should be re-worked to not have such small minimums).

The issue with lack of ammo/mags was also reported in #65412, though my attempts to fix that haven't gone anywhere. (I'm clearly misunderstanding the Class and Inheritance structure of Cataclysm somewhere)
