### ISSUE TITLE
Selecting trait Weight: XS or Weight: XXXL results in error message

### ISSUE THREAD

**Issue by sdgoihew** [CleverRaven/Cataclysm-DDA#65855]
### Describe the bug

As in title.

### Attach save file

N/A

### Steps to reproduce

1. Launch cdda
2. Create custom character
3. Select one of negative traits `Weight: XS` or `Weight: XXXL`

### Expected behavior

Selecting trait without error message

### Screenshots

![cdda2](https://github.com/CleverRaven/Cataclysm-DDA/assets/115432842/8c0937d8-b707-47e5-81fc-b11ed9cac696)
![cdda1](https://github.com/CleverRaven/Cataclysm-DDA/assets/115432842/a2608575-6a40-4942-bbbf-e5f30faf80c2)

### Versions and configuration

Win10 x64, tiles, a4a8dab (and many experimental builds before with same problem)

**Comment by KHeket** [comment]
Can confirm. Every time I creating a character with this trait - this message appears, but it also dont effect anything

**Comment by Savengrr** [comment]
I am not sure what the starting kCal should be nowadays (I would assume 125k stored kCal) but its been 20+ and I was wondering why I was still obese and I'm rocking 520993 kCal. 

I assume this to be a bug where it sets a value just inside the maximum allowed ranges for xxxl and minimum for xxxs. 
A new character with xxxl has 625000~ kCal.

**Comment by random-cdda-modder** [comment]
also reported here #64923

to me, message appears and cannot continue chargen as pressing space bar does not continue the game (game is either frozen of error happens in a loop)

**Comment by SurFlurer** [comment]
Can /confirm.
