### ISSUE TITLE
Defense gamemode starts with Segfault

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#65854]
### Describe the bug

Getting an immediate Segfault when selecting "Defense" gamemode and selecting the Mansion start. This is repeatable.

Same thing happens in the nightly from today, build number: 2023-05-25-1546.

### Attach save file

N/A

### Steps to reproduce

1. Select Defense gamemode.
2. Hit Tab through character creation.
3. Select Mansion start. Press S.

### Expected behavior

The game promised me a mansion.

### Screenshots

![seg](https://github.com/CleverRaven/Cataclysm-DDA/assets/13466852/999f061b-aa68-4be6-80ff-010201246668)

### Versions and configuration

Win 10 x64 Pro

build type: windows-tiles-x64-msvc
build number: 2023-05-14-0843
commit sha: 9a4259f56731c94ea315baa785d3804af24661dc
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/9a4259f56731c94ea315baa785d3804af24661dc

### Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11567449/logs.zip)

**Comment by sonphantrung** [comment]
The 'Defense' gamemode hasn't been updated for years...

**Comment by Tharn** [comment]
I almost figured something like that. Seems odd to have an option proudly displayed in the main menu that results in a Segfault. Should be commented out in the code until they'd come back to it.

**Comment by RenechCDDA** [comment]
It's just a result of an overlooked interaction, Mansion_Wild was renamed and migrated to Mansion_Road_1, the old obsoletions/migrations were removed, so now the *hardcoded* reference to Mansion_Wild doesn't know what it's looking for.

I would personally appreciate if you did not imply anything about contributors "pride" or how they should work. Both PRs involved in getting here were good, solid work.

**Comment by Tharn** [comment]
Cheers for looking at it.
Didn't mean to imply anything, s'all good.
