### ISSUE TITLE
Game crashes at specific part of the map.

### ISSUE THREAD

**Issue by nikitazoshchuk** [CleverRaven/Cataclysm-DDA#65864]
### Describe the bug

My game crashes when I go to specific area of the map or zoom out so that area is visible.I tried different tilesets and got same result.

I'm using catapult launcher and game version 2023-05-26-0534.
When I use 2023-05-24-0416 version everything works fine. 

### Attach save file

[16-0 big-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11578169/16-0.big-trimmed.tar.gz)

### Steps to reproduce

Open save file with game version 2023-05-26-0534. I saved at the exact location of the crash.

### Expected behavior

Game crashes after loading save.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: 3800362 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

### Additional context

Game report is generated in version 2023-05-24-0416.

**Comment by NetSysFire** [comment]
Can reproduce. I get the following error in the terminal:

```
cataclysm-tiles: src/catacharset.cpp:350: std::wstring utf8_to_wstr(const string&): Assertion `sz != static_cast<size_t>( -1 )' failed.
```
