### ISSUE TITLE
Portal storms dont change weather.

### ISSUE THREAD

**Issue by Aism4n** [CleverRaven/Cataclysm-DDA#65861]
### Describe the bug

I got issue with new portal storms on experimental. My portal storms are 10x10 squares and i literally have to run with my NRE recorder like idiot, trying to find the right tile with "portal storm" weather while its moving. Next time storm happened - i didnt find any location that change weather to portal storm at all.

### Attach save file

[Никак-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11575841/-trimmed.tar.gz)

### Steps to reproduce

Load save file. 
Go to portal storm center. 
Nothing happenes.

### Expected behavior

Should be more like "reallity tears apart", weather change to portal storm with really badass event right in the centre of storm + happy NRE recorder.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/105210191/eb962f28-996a-4171-a9ae-e49557e68ed1)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/105210191/8f807ac7-358d-49a7-8ef0-72720284d6ce)

### Versions and configuration

OS Win 10
Ver: DDA exp 2023-05-26-0841 64b
Graphic: Chibi Ultica + MSxotto+ overmap
Language RU (but i changed it on screenshot so you can read with ingame function)
World mods: noNPCfood, no fungal, personal portal storms, package bionic professions, blaze ind, translate dialogue, extra mut scen.

**Comment by Nebnis** [comment]
I experienced something similar twice in my save now, it seems that portal storms wont spawn anymore, i get reality breaking/mission but no weather change. Might have to do with updating an old save/world?

**Comment by Aism4n** [comment]
Yes, its most likely issue with old world saves. I tested on world setting copy and portal storms work well. But old world is bugged.

**Comment by Aism4n** [comment]
UPD: Its still possible to find a spot like 10x10 or 15x15 where weather change to "Portal storm" (centre) but stil no close/distant portal storms.

**Comment by ektoplazm** [comment]
[Artesian-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12100681/Artesian-trimmed.tar.gz)
- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 55a749a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

in the save portal storm just started, but nothing happens. mission destination is clear too
