### ISSUE TITLE
[Port Request] TISH Stuff

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#65881]
### Is your feature request related to a problem? Please describe.

I saw three Prs for Tish which I thought would make perfect additions to dda and wanted to put them here:
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/71
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/66
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/68

### Solution you would like.

I think these are great gameplay additions and I would like to see them ported to dda in some form, especially the npc command because it opens up a lot of tactical possibilities during combat encounters.

**Comment by Procyonae** [comment]
>Average 8/8/8/8 survivor with average weight and no mouth protection, while being in contact with one infected random NPC or feral, has a 50% chance to get sick every turn

That sounds really annoying if the only way to tell if they have a cold is infrequent coughs, sickness doesn't really add anything to the game imo, it's just a huddle down and do nothing for a while and this sounds like it would probably increase the chance of getting it, I like the premise of the change alot mechanically but gameplay wise it sounds like it would just suck and encourage perma wearing gas masks more which seems silly. I don't do much with NPCs but that change looks sensible if somewhat abusable

**Comment by Theawesomeboophis** [comment]
It's still better than the current implementation where your character randomly contracts the flu out of nowhere, but I understand your argument as well. Further tweaking for dda may be needed.

**Comment by Procyonae** [comment]
I'm not against the change itself at all just the numbers that PR talks about, it's kinda hard to tell though without actual testing

**Comment by Theawesomeboophis** [comment]
Yeah, they do seem a bit high, I think 10% would be better.

**Comment by Night-Pryanik** [comment]
"50 chance" is outdated info, please don't pay attention to it.

Right now you have a _chance_ to get sick only if NPC or a feral _coughs_ on you, which happens only once per 30..300 seconds and only for NPCs or ferals who are already sick with cold or flu, which is itself a very rare event (1% per spawned NPC). If you standing adjacent to NPC or feral in that moment, you environmental protection and health value plays a role to determine if you will actually get sick.

Overall chance to accidentally get sick is very, very low, unless you're super-actively interacting with sick characters and standing right next to them 24/7.

**Comment by Maleclypse** [comment]
#66001 will resolve one of these
