### ISSUE TITLE
Christian community's dorm leader gives infinite blankets.

### ISSUE THREAD

**Issue by Irets** [CleverRaven/Cataclysm-DDA#65880]
### Describe the bug

The dorm leader at a Christian community (Church retreat) gives infinite blankets because you can ask to join the commmunity over and over again.

### Attach save file

[Helvete-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11582678/Helvete-trimmed.tar.gz)

### Steps to reproduce

1. Find a Christian community
2. Ask the dorm leader if you can join the community
3. Be accepted and receive a blanket
4. Repeat steps 2-3 for infinite blankets

The duplication can be done with or without closing the dialog window.
The option to join the community never disappears.

### Expected behavior

I expect being able to join the community *once* and receive the item.

There should be a check in place to see if I've already become a member of that **particular** Christian community.
If such system doesn't exist, the dialogue option to join the community should disappear after using it once on that **particular** NPC.

### Screenshots

![maim_1685209875](https://github.com/CleverRaven/Cataclysm-DDA/assets/50279814/a0c4b7cb-7385-4c24-b18a-ad7a7b7174f0)

### Versions and configuration

OS: Gentoo Linux
Game version: 0.G-2094-g00d4cf13ca-dirty
Graphics version: either
Ingame language: English
Mods loaded: nothing added nor removed from the default world generation options

**Comment by SurFlurer** [comment]
Turns out that `u_has_var` is returning true when you do not have that var......

**Comment by Irets** [comment]
Thank you for looking into it.
How will it work once fixed?

Will the option to join become community specific? Or am I "globally" part of any and all Christian communities?

**Comment by SurFlurer** [comment]
> Will the option to join become community specific? Or am I \"globally\" part of any and all Christian communities?

You will globally become joinee of all Christian communities. That's because the identifier is stored in the player character, not the npc. And the current implementation doesn't make variables' names unique to each community.

**Comment by Irets** [comment]
It's a bit silly that if you join a community, another community at the other side of the world now acknowledges you as their member too. Glad to hear that there has been an ongoing idea to make them unique.

Thank you once again.

**Comment by Zireael07** [comment]
As they said - this is the case for all factions. To avoid this problem, refugee center and the like should be globally unique, but the work on this seems to have stalled
