### ISSUE TITLE
No Hope Military Base Unavailable

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#65891]
### Describe the bug

The Overrun Scenario is broken in worlds using the no hope mod due to inability to generate military base.

### Attach save file

N/A

### Steps to reproduce

1. Create World with no hope
2. Choose Overrun Scenario in Custom Character

### Expected behavior

No-Hope should realistically have all of the same locations as vanilla CDDA, albeit with less loot and more danger

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/e88d5799-cff1-4097-a796-975b157e3ae2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: 81bef92 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    No Hope [no_hope],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    No Bionic Slots [no_cbm_slots]
]

**Comment by GuardianDll** [comment]
Location was removed from no hope due the balance issues, but the scenario was left untouched, it seems

**Comment by Night-Pryanik** [comment]
The solution is to blacklist the scenario from the mod.

**Comment by Kantonine** [comment]
what about the aircraft carrier, is it fine to keep?

**Comment by Kantonine** [comment]
> Location was removed from no hope due the balance issues, but the scenario was left untouched, it seems

What about the aircraft carrier, is it fine to keep?

**Comment by kholat** [comment]
the aircraft carrier does spawn in No Hope (can confirm cuz I just found it)
