### ISSUE TITLE
Custom close helms are somehow worse than greathelm in both protection and encumbrance

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#65904]
### Is your feature request related to a problem? Please describe.

In game, custom steel close helms are supposed to be pinnacles of plate head protection, taking days to craft even with all proficiencies, yet even the best one (tempered steel close helm) has next protection values for head:
<html>
<body>

Thickness | 1.3mm | 1.0mm
-- | -- | --
Coverage | 100% | 1%
Bash | 13.75 | 1.00
Cut | 13.75 | 3.00
Ballistic | 9.38 | 2.00

</body>
</html>

Compared to greathelm's values:
<html>
<body>

Thickness | 2.5mm | 2.5mm
-- | -- | --
Coverage | 100% | 100%
Bash | 15.00 | 2.50
Cut | 15.00 | 7.50
Ballistic | 7.50 | 5.00

</body>
</html>

Greathelm can be hammered out in less than a day from scrap steel, if you don't know.

The steel on close helms is too thin. Most helmets sold today (and made historically, too) are at least 1.5 mm thick, reaching up to 2.5 mm. And if the custom cuirasses have the metal thickness of 4 mm in game, so why the head has to have THAT much lower protection?

The other problem is that despite greathelm IRL sits on the wearer's shoulders over the armor and doesn't allow to rotate itself with the head (unlike the close helm, that can turn with the head and rests on the shoulders under the gorget), it has lower head encumbrance value of 49 vs 54 of close helm. I repeat, a helmet that forces you to turn with your whole body to see a threat that is not directly in front of you allows you to react to threats better than a helmet that can turn with your head.

Finally, in-game armet, that is pretty similar in construction to close helm has neither of the close helm's drawbacks, as it has both good thickness and reasonable encumbrance.

Also, why close helm has conductive flag despite (supposedly) having a leather lining? And why its leather layer has only 1% coverage? Same goes for many other custom-built armors (like nomad plate armor, despite it has 100% coverage with 3 layers of fabrics, it's still conductive, and custom plate armors all have 1% leather coverage for some reason), though.

### Solution you would like.

1. I think copying armet's material thicknesses and head encumbrance values would be reasonable. 
2. Increase crafting cost in metal by about 1.5-2 times. 
3. Maybe make a light close helm variation with 1.5 mm thick plating.
4. Warmth value of close helm should be increased to 15. 0% breathability still applies.
5. custom plate armor pieces with leather in their recipes should get 90-100% leather coverage with 2 mm thickness
6. Custom plate armors should have their conductive flag removed, unless the leather/textile is to be be removed from their recipe (which is unrealistic, because padding is important). 
7. Warmth value of close helm should be increased to 15. Breathability value of 0% still applies, so it should be essentially a nerf for wearing one in warm weather.

### Describe alternatives you have considered.

1. Nerfing non-custom-made plate helmets into ground. Neither fun nor too realistic.
2. Having a top-of-the-line custom-made helmet overmatched by a tin can cobbled together from scrap metal.

### Additional context

References:
1. Commercially available close helm with known weight and thickness (16 gauge steel is about 1.5 mm): https://www.by-the-sword.com/p-42205-european-close-helm-16-gauge-steel.aspx Some historical examples are even heavier, and thus likely to be thicker.
2. Another commercial example: https://www.eviltailors.com/en/helmets/42789-close-helmet-ca-1520-16-mm-steel.html
3. Historical cuirassier helmet with known weight: https://www.metmuseum.org/art/collection/search/26524
4. Historical tourney helmet with known weight: https://www.artic.edu/artworks/147140/gorget-and-close-helmet-for-foot-tourney-at-the-barriers

None of those have less than 1.5 mm thickness, even those with unspecified thickness are too heavy to have such thickness.

**Comment by Drew4484** [comment]
The leather in the plate armor does not represent a padded layer, it is the leather straps used to secure plates in places. For the close helm it is not intended to be a liner as those are separate pieces. Neither the helm or plate are intended to be worn without an additional layer beneath them, which can be conductive or not as the player choses.

The close helm is definitely on the lighter side for a helmet, any helmet is going to be a trade between protection and mobility. A tournament helm would often be significantly heavier, with the resulting increase in protection, but equipment meant for a formal tournament was not particularly useful on a battlefield due to weight and protection over mobility. 

As for the recipe issues with other helmets, they are typically older entries that haven't been updated. Anything using ungraded steel (or even the occasional iron) is due for a review.

If you want to proceed with this, there is definitely room for heavier helmets added, but consider that those will have higher penalties associated with them.

**Comment by randomtyper** [comment]
> The leather in the plate armor does not represent a padded layer, it is the leather straps used to secure plates in places. For the close helm it is not intended to be a liner as those are separate pieces. Neither the helm or plate are intended to be worn without an additional layer beneath them, which can be conductive or not as the player choses.
> 
> The close helm is definitely on the lighter side for a helmet, any helmet is going to be a trade between protection and mobility. A tournament helm would often be significantly heavier, with the resulting increase in protection, but equipment meant for a formal tournament was not particularly useful on a battlefield due to weight and protection over mobility.
> 
> As for the recipe issues with other helmets, they are typically older entries that haven't been updated. Anything using ungraded steel (or even the occasional iron) is due for a review.
> 
> If you want to proceed with this, there is definitely room for heavier helmets added, but consider that those will have higher penalties associated with them.

Aye, that mostly explains it. Ungraded steel helmets will need a bumpdown in thickness (to 2 mm, perhaps?) and increase in encumbrance, as I understand from your words. And removal of leather as a liner. 

As for new close helms, maybe reclassify current one as light and add medium (1.75 mm steel, 59-64 enc as with extremity plate armor progression) and heavy (2.25 mm steel, 64-69 enc as with extremity plate armor progression) close helms?

Nomad plate armor is unobtainable in-game, so I will retract that question.

**Comment by randomtyper** [comment]
Closing the issue. The new close helms were added, the old helms shall wait for revision.
