### ISSUE TITLE
Full auto can have multiple targets

### ISSUE THREAD

**Issue by BoruMaboru** [CleverRaven/Cataclysm-DDA#65903]
### Is your feature request related to a problem? Please describe.

The bullet wasted so much on one target, even that one target already dead while the bullets also destroying the corpse with the loots it dropped. This making the full auto mode only gun become avoided by some players. 

I know the bullet spray already randomly hit another target, but I want it become more selectable than randomly hit friendly and making me end up hated by a faction.

### Solution you would like.

Multiple targets only allowed on full auto while also giving many drawbacks like inaccuracy and maybe accidently kill the player if the gun become too unstable.

**Comment by Qrox** [comment]
I think allowing some degree of control of the line of fire during burst fire/full auto is reasonable, but considering that normal people have reflex time in the range of a few hundred milliseconds there should be some delay for that control.
