### ISSUE TITLE
Hub 01 Bar punctuation issues and apricots

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#65911]
### Describe the bug

During the long trundle of translation, I spotted a number of punctuation inconsistencies in the hub 01 bar dialogue which I'll list here as well as the needed fix, it's mostly missing periods/extra punctuation marks:

- Just making sure people don't ask stupid questions -> Just making sure people don't ask stupid questions.
- Sorry I rather be left alone right now -> Sorry I rather be left alone right now.
- Take the anchor and leave the coin.  Its a deal?. -> Take the anchor and leave the coin.  Its a deal?
- Sure, let see what you offer -> Sure, let see what you offer.
- It'll get done -> It'll get done.
- Not interested after all -> Not interested after all.
- [5 HGC] Its a deal -> [5 HGC] Its a deal.
- Sure, just let me find the cash -> Sure, just let me find the cash.

I'm less sure of the following three since they seem to be written prompts of actions rather than dialogue, so not sure if they should have punctuation, but some similar descriptions of actions in this dialogue section do?

- Offer to buy the anchor for 1 HGC -> Offer to buy the anchor for 1 HGC.
- Attempt a friendly approach -> Attempt a friendly approach.
- Press on in search of a reaction -> Press on in search of a reaction.

Additionally, completely unrelated aside from the fact that I found these issues at roughly the same time, and this is the reason I added apricots in the title, the description and item name of "handful of irradiated apricots" is inconsistent as it is the following:

- An irradiated apricot.

The description should probably be changed to refer to multiple apricots just like the description of the regular handful of apricots.

### Attach save file

N/A

### Steps to reproduce

1. For the dialogue:
2. Talk to the people in the Ancilla bar
3. Look at the dialogue for the listed typos
4. For the apricots:
5. Irradiate apricots

### Expected behavior

Expected behavior for all of this is for there to be no typos

### Versions and configuration

Typos spotted on Transifex, so in game as of latest experimental

**Comment by Procyonae** [comment]
Unless they're purposefully talking weird or I'm missing the context I'd suggest the grammatical adjustments of:
Sorry I rather be left alone right now. -> Sorry, I'd rather be left alone right now.
Sure, let see what you offer. -> Sure, let's see what you have to offer.

Also the anchor one is missing an apostrophe though I'd suggest that "We have a deal?" sounds better regardless (And probably makes more sense to translators).
Take the anchor and leave the coin. Its a deal? -> Take the anchor and leave the coin. It's a deal?

**Comment by sadenar** [comment]
Adding a three more I found since then to the bag, we have:

Starting location Clothing Store is typo'd:
- Clothe Store -> Clothing store

A swear sentence for danger elevation probably has improper capitalization:
- It's going South pretty [swear] fast. -> It's going south pretty [swear] fast.

Simple missing period on a return to safety NPC statement:
- Clearing the world, one [Name_b] at a time -> Clearing the world, one [Name_b] at a time.

**Comment by sadenar** [comment]
Another two to the stack:

Caviar and egg sandwich does not seem to have a plural, as in for the plural form it should be changed this way:
- caviar and egg sandwich -> caviar and egg sandwiches

Windmill construction task description is missing a period while all building task descriptions I've seen so far do:
- Let's build a windmill to allow us to grind flour efficiently -> Let's build a windmill to allow us to grind flour efficiently.

**Comment by sadenar** [comment]
Some camp dialogue string's translation context mentions a third component that is not present in the string, this specific string from what I gather is to give potential faction camp locations when NPCs are asked about it:

- ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16321433/578189e6-932c-47ff-b467-eed9cdbc1d7e)

Misspelt don't in what I assume is a monster snippet for some kind of nether monster? Might be shadows since their attack text is just above in transifex, but unsure:

- "Please dont" -> "Please don't"

**Comment by sadenar** [comment]
Another one, depends on whether Valhallists ever get unobsoleted, but if they do, this needs fixing:
- I don't need anything, just gotta got. -> I don't need anything, just gotta go.

**Comment by Procyonae** [comment]
The screenshotted one is to do with something temporarily commented out in the C++ so I'm gonna leave it alone but the rest of the fixes are on the way ^^
