### ISSUE TITLE
Duffel Bags only hold a gallon and a half of inventory

### ISSUE THREAD

**Issue by jake1203n** [CleverRaven/Cataclysm-DDA#65919]
### Describe the bug

The duffel bag, despite being described as a huge bag, only carries 6 liters of inventory, equivalent to a small backpack.

For reference, here is a picture of an adult wearing an actual 6 liter backpack. https://m.media-amazon.com/images/I/81hPHpWMVvL._AC_UX679_.jpg

### Attach save file

N/A

### Steps to reproduce

https://imgur.com/a/ZEyRX7m

Just spawn a duffel bag into your inventory.

### Expected behavior

The smallest duffel bag I can find online is 30 liters.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/4eef1c35-1f32-4667-92e7-ed13b7e5a5de)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 0.G Stable STEAM [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Magiclysm [magiclysm]
]

**Comment by Procyonae** [comment]
That's the size of the empty bag it holds 35L
