### ISSUE TITLE
gas station should connect with the roads

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#65914]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/b560a6b7-c82c-4ae3-a5a0-50c5b04dcca9)

i have to drive through the pavement and a light pole to access the pumps. i don't know if it is possible to fix this sort of issue but a report issue wouldn't hurt anyway.

this is exaggerated by my vehicle size but you get the issue.
### Attach save file

[Depths Of Jupiter-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11592613/Depths.Of.Jupiter-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

The mapgen was generated a few months ago but here it is anyway
- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: c038a17 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Procyonae** [comment]
Afaik there's no easy way to solve this, it's the case for all city buildings with road. You can make them copy-from generic_city_building_no_sidewalk so they just have field terrain there instead and some similar abstract generic_city_building_road could be made with a new flag "ROAD_CONNECTION" or similar that works the same way "SIDEWALK" works but that would a) be hardcoded ew and b) still be kind of hacky bc you'd need to have one road entry that has to work for all maps and SIDEWALK affects diagonal tiles too which would make it more complicated

**Comment by Procyonae** [comment]
Duplicate of #50279
