### ISSUE TITLE
Mood Swings not swinging mood

### ISSUE THREAD

**Issue by Swootch** [CleverRaven/Cataclysm-DDA#65928]
### Describe the bug

The trait 'Mood Swings' does either nothing, or so little that I've not noticed it doing anything once in dozens of hours of real time playing. The former is suspected since I've never seen a status in any menus related to the trait.

### Attach save file

[Lake of the Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11599952/Lake.of.the.Hills-trimmed.tar.gz)

### Steps to reproduce

1. Choose 'Mood Swings' trait on character creation.
2a. Notice it not doing anything ever.
2b. Don't notice it doing anything ever.

### Expected behavior

Mood swings: Your morale will shift up and down at random, often dramatically.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: cbf5743 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks]
]

**Comment by Bulletfang** [comment]
Spring day 79, my character had his first mood swing that I noticed (it was chosen as starting trait). Is something making it trigger exceedingly rarely only?
