### ISSUE TITLE
Turning off battery modded MP3's deletes the battery in latest experimental version c038a17 

### ISSUE THREAD

**Issue by anonya1** [CleverRaven/Cataclysm-DDA#65921]
### Describe the bug

When turning off a battery modded MP3 (Light, medium and heavy battery mod), the battery placed inside is completely deleted.

### Attach save file

N/A

### Steps to reproduce

1. Apply any battery mod to mp3
2. Reload MP3+1 with battery
3. Turn on and off MP3+1
4. Battery is now completely gone

### Expected behavior

Battery should remain inside MP3+1 with reduced charge from turning on.

### Screenshots

![cataclysm-tiles_1xSkJCbcYi](https://github.com/CleverRaven/Cataclysm-DDA/assets/42488634/b6a24dbe-e00a-4c78-be2e-ee53a34b1857)

### Versions and configuration

- Windows 10
- Version: c038a17 
- Language: English
- Mods loaded: Default

**Comment by Kamayana** [comment]
I'm able to reproduce. It also affects a laptop with a heavy battery mod, so it's not just the MP3 function but all transforms.

It's a consequence of the automatic cable pocket creation I added in #64334. The issue no longer occurs after removing this line:
https://github.com/CleverRaven/Cataclysm-DDA/blob/dc4fd35c153befbdfd979e3a643fcf4e1b113621/src/item_factory.cpp#L3691
Will look into a proper fix.
