### ISSUE TITLE
Mercenary bosses still have placeholder descriptions.

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#65925]
### Describe the bug

The `mercenary ghost` and `mercenary officer` on the 2nd floor of the "red carpet" labs (or physics labs) share the exact same descriptions as the `black-ops zombie` and `zombie bio-operator`. I remember looking at the PR that added it back when it was a draft, and it had those descriptions then, I assumed that they were placeholders and would be replaced once the PR was ready, but it seems that candlebury forgot them.

### Attach save file

N/A

### Steps to reproduce

1. Spawn in the mercenary ghost/officer or go to the location they appear
2. compare their descriptions to the black-ops zombie and bio operator

### Expected behavior

They should have their own, unique descriptions. I was considering writing them but I think candlebury should be the one to do it. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56202842/b3774573-7ec7-4a2b-a07f-4077842b85d6)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56202842/948ed353-ebfe-4cf9-9a96-e8ca2845d9bf)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56202842/fc7219e6-f49a-4ab2-9d6a-8d2edf758152)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56202842/7f73d43e-c1e3-42bf-9c3b-2274f9c9dea1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.2274 (1909)
- Game Version: a56edc8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    Xedra Evolved [xedra_evolved]
]

**Comment by John-Candlebury** [comment]
I'm not at fault tho.

**Comment by Daved27hundred** [comment]
I wasn't intending to point fingers, sorry if it came off like that

**Comment by mark-ik** [comment]
We should maybe update the mercenary ghost's drops to differ from the black-ops zombie, too. The merc officer is guaranteed to drop a phase immersion suit, so I incorporated that into its description. The merc officer probably doesn't need to do electric damage, either.

mercenary officer:
This reanimated soldier of fortune wears a tarnished suit of interlocking, reflective plates. A large revolver and an intimidating machete are strapped to the suit's waist, but it needed neither to incapacitate targets in life, judging by its intimidating stature.
mercenary ghost:
It is difficult to see the figure beneath the shadowy mist that obscures it, but glimpses of black tactical armor on its limbs suggest it may be as hard to hurt as it is to hit.

Lemme know if these are good!

**Comment by Daved27hundred** [comment]
@mark-ik the spikes they're impaled on before you fight them say `Their form seems twisted and refracted in the light of the strange glowing crystal that has seeped out of the ground and impaled their body.` Adding something to their descriptions mentioning that would be a good idea.
something like `their body is warped as though you were looking at them through a shattered prism` sound good?
