### ISSUE TITLE
'New' world creation menu feature is confusing

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#65930]
### Describe the bug

When I as a user try to generate the world in the games main menu, it opens up this 'new' menu with 3 fancy schmancy sliders.
There are however 2 other options of world generation at play: 
using World Defaults under Options, or using Advanced Settings in this word generation menu, pressing the 's' button.

So my question (to myself) is: which of these 3 options is the game going to use when I press 'f' to actually generate a world?
There is zero indication about this anywhere whatsoever, so the question cannot be answered other then by fiddling around.

I have figured out some things about this:
If you go to Advanced world gen like in the olden days and input your settings, it will actually kinda "remove" the sliders, well they will still be there but the yellow pointer thingy wont, so thats kinda an indication I suppose?
However if you set World Defaults, it seems to use world defaults but the yellow pointers are still drawn on the sliders, the game seems to use the actual World Default settings tho.

Anyways this is weird and confusing to me, does this feel normal to anyone else?

### Attach save file

N/A

### Steps to reproduce

1. In main menu press W and enter to open up the worldgen menu
2. observe an odd new menu with no indication of what is being used for the to-be generated world other than the giant sliders.
3. fiddle around with also the Options menu -> World defaults and also the (old) Advanced settings under World -> Create world

### Expected behavior

There should be some sort of confirmation thing, a switch or something that shows the user "ok look, these settings are being used, these others are not"

### Screenshots

![MizYDoh](https://github.com/CleverRaven/Cataclysm-DDA/assets/33296847/30810b01-1d97-4348-9fa7-27cc33c024b1)
"default" screen, also same if you use World Defaults

![Y78Dhzo](https://github.com/CleverRaven/Cataclysm-DDA/assets/33296847/a90bb0fb-871d-482b-915e-681e6903ed3c)
sliders remain but the pointers are gone if one uses Advanced Settings and changes something

### Versions and configuration

- Win10
- cdda-windows-tiles-x64-msvc-2023-05-26-0841

**Comment by fairyarmadillo** [comment]
Definitely feels like a downgrade from the old system to me. I also can't make heads or tails of the new options menu.
