### ISSUE TITLE
New modular AR-15 and M4 carbine aren't mountable on vehicle turret mounts

### ISSUE THREAD

**Issue by TaiGambol** [CleverRaven/Cataclysm-DDA#65931]
### Describe the bug

The new modular AR-15 and M4 carbine cannot be mounted on a turret mount for a vehicle.

### Attach save file

[Testing Vanilla_copy2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11602996/Testing.Vanilla_copy2-trimmed.tar.gz)

Save shows two metal frames with turret mounts, one with a labelled Modular AR-15 (on the left), one with a labelled Obsolete AR-15 (on the right).

### Steps to reproduce

1. Make a character, build a vehicle frame and turret mount, spawn in a new AR-15
2. Attempt to install the AR-15 into the turret mount.
3. 'Mounted AR-15' will not be available as an option.

### Expected behavior

The ability to install the AR-15 as a mounted weapon

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2364 (21H1)
- Game Version: dc4fd35 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

I tried to look up where weapons were defined as being mountable as turrets myself, to offer a fix instead of a complaint, but I can't seem to find anything on that.

**Comment by GuardianDll** [comment]
Duplication of #65821

**Comment by TaiGambol** [comment]
> Duplication of #65821

Didn't see that. Should I close this then?

**Comment by TheShadowFerret** [comment]
> Should I close this then?

Yes
