### ISSUE TITLE
Gambeson ingredients significantly heavier than finished product

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#65944]
### Describe the bug

Gambeson requires 66lbs of padding but only weighs 22lbs

### Attach save file

n/a, trivially reproduceable

### Steps to reproduce

make a character with tailoring 4
check the recipe for Padded Gambeson and the resulting item
check the recipe for Gambeson Batting and the resulting item

### Expected behavior

I would expect the final item to weigh at least as much as the padding you insert into it

(I don't know if the gambeson is too light or if the recipe requires too much padding, someone who's familiar with gambesons should probably weigh in on the realistic weight)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 00d4cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by anoobindisguise** [comment]
Are you sure? The gambeson requires 153 clumps of batting, which each weigh 50 grams = 7.65 kg of batting in total. Each batting recipe is 200 grams of stuff and should make 4 per.

**Comment by Xpyder** [comment]
Ah, I missed that the recipe makes 4, thank you!
