### ISSUE TITLE
Change Illiterate (slow, fast reader) to a profession with tiers

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#65953]
### Is your feature request related to a problem? Please describe.

I never played with illiterate, maybe I would if it didn't mean I would have to stay till the end.

You can remove illiteracy by changing genes. That's weird as hell.

### Solution you would like.

Tiers would differentiate in:

- reading time bonus
- maybe an intelligence cap on books (representing vocabulary)
- how can they be learned (cannot read on how not to be illiterate)
- work/time needed to obtain

Tiers:

- Illiterate - cannot read (0%) (not a profession, but the absence of Reading)
- Knows alphabet (First Grade) - extremely slow reading (5%?), can't read some words, abysmal vocabulary (English words are read and pronounced differently, so an adult couldn't read them too => intelligence capped reading? 3? 4?) learnable from NPC, PC programs, (something else?); 
- Puts words together - very slow reader (10-15%?) (poor vocabulary => intelligence capped reading 5-6?), like 2nd or 3rd grade, from this point on, can be self-thaught
- Reads sentences fine - slow reader (65%?), (so-so vocab => intelligence capped reading 7? 8? 10?)
- Reading - basic adult (100%) (no cap on reading)
- Fast reading - (115-120%?) enjoys books, lots of vocabulary, slowly learned by reading (100 hours proficiency?) can be practised (crafting -> proficiencies) for much quicker obtainment, written in some "Read fast, save time!" book
- Superhuman reading - (150%?) (fun addition? is it realistic?) represents nearly full vocab (as in knows nearly every word), amazing and quick word comprehension, reads sentences, not words and some other cool sh*t; learning this is extremely involved task, cannot be learned by just reading, needs some special book about reading like an olympiad reader or smth

I think reading should be learned much slower than other professions. As in _**every level could take 100 hours**_.

Also to add hiding professions (from @-menu) would be nice as tiers "Knows alphabet" to "Reading" are assumed, so should be hidden by default to not clutter, but they can be viewed in the profession menu and unhidden there.

### Describe alternatives you have considered.

Quoting @anothersimulacrum from #63577

> The current illiterate trait represents unwillingness or incapability of learning to read. A low cost 'never learned to read' trait could be available to which this system would apply.

It could be split into a mutation "Will never read and refuses to" and a proficiency - simply didn't learn to read.

### Additional context

I can see @Snaaty beat me to it with a bit different approach #63577

I would try to implement my approach, but I don't have time right now.

**Comment by PatrikLundell** [comment]
Genes have an impact on medically caused illiteracy: if the eye micro saccades are screwed up they can make it extremely hard to discern letter shapes and cobble the fuzzy shapes together in the correct order. Correcting the genes and regrow the person to the current state could probably fix that part of the problem if it was possible to do.

The connection of intelligence and vocabulary with literacy is odd. While a low intelligence might reduce the rate at which vocabularies are learned and might also reduce the rate at with literacy is learned, it's not directly connected. It's quite possible for an illiterate person to have a rich vocabulary and be able to use it well. It's true, however, that many words are rarely used in daily speech, and almost exclusively encountered in written material.

It's also possible for people with low intelligence to have a rich vocabulary, and there's a genetic disorder similar to Down's Syndrome that leads to a similar range of reduced intelligence, but with a normal range of vocabulary, resulting in a perception of the subjects of the latter disorder being more intelligent than those suffering from the former, even though tests would rate them at the same level.

**Comment by Inglonias** [comment]
[The illiterate trait is intended to be all-or-nothing.](https://github.com/CleverRaven/Cataclysm-DDA/issues/27312#issuecomment-450053736). It's designed as a challenge trait for players who want to play as a character that doesn't use books to learn recipes or skills.

**Comment by estebandellasilva** [comment]
Then Technically there should be 2 traits 
Illiterate - being unable to read
alliterate - being able to read but uninterrested to do so

Regarding reading becoming a proficiency ... i can tell from knowledge there are some people that are just ... slow readers my brother reads at a snails pace but he reads a lot of books every year ... but its not getting better at all.

**Comment by Inglonias** [comment]
We have a trait like that. It's called "Hates Books". You can't pick it from the traits screen anymore, but it's still accessible via background. It makes books less fun, and caps their enjoyment at zero.
