### ISSUE TITLE
EOD helmet has unreasonably and unrealistically low encumbrance for its protection

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#65952]
### Is your feature request related to a problem? Please describe.

In game, EOD helmet has next protection values:

<html>
<body>

Material | Rigid Kevlar | Nomex
-- | -- | --
Thickness | 7.5mm | 7.5mm
Coverage | 100% | 100%
Bash | 22.50 | 7.50
Cut | 30.00 | 7.50
Ballistic | 37.50 | 7.50

</body>
</html>

And head, eyes and mouth encumbrance of 20, 10 and 15 respectively.

Which leads to a problem: an unpowered armor piece (the battery is for headlight) that weighs 5.6 kg and has better protection than many other pieces is somehow less encumbering than an army helmet (23 fitted). Unrealistic and unbalanced, at least in my opinion.

An EOD helmet IRL would severely restrict head movement (comparable to heavy medieval helmets, it weighs about as much as some of those, too), especially if worn with EOD jacket with a collar.

Meanwhile, in-game EOD jacket has pretty reasonable 80 encumbrance (maybe even a bit too much, though).

If the helmet in question is modeled after something like an Advanced Bomb Suit, it would be not realistic to make the visor kevlar, too. Thick plastic (like on ballistic goggles) would be much more representative of the face shield material.

If talking even more realistically, EOD suits should not have such extreme ballistic protection value. Their job is absorbing blast wave impact (high blunt resistance) and covering whole body from fragments (that usually have much lower penetration capabilities and velocity than actual bullets).

### Solution you would like.

Increasing EOD helmet head encumbrance to 40-50. 60 at most. That's it.
Optionally, changing eye (and maybe mouth) protection material to about 15-20 mm of plastic (on IRL Advanced Bomb Suit faceshield is made of acrylic glass and polycarbonate).

### Describe alternatives you have considered.

1. Decreasing EOD helmet protection and weight to approximate Advanced Bomb Suit helmet (weighs 3.6 kg).
2. Having an overperforming and unrealistic armor piece in game.

### Additional context

EOD helmet analysis study: https://www.mdpi.com/2076-3417/10/22/8227 Outer hard shell is about 4 mm. The rest is shock-absorbing foam. Does the game have a specific shock-absorbing (blunt damage resistant) material, btw? Something like quilted cotton, but more advanced. Maybe neoprene?

**Comment by anoobindisguise** [comment]
Per its weight, it would have like 90+ encumbrance iirc.
