### ISSUE TITLE
Skater is mutation

### ISSUE THREAD

**Issue by CatWithFourEyes** [CleverRaven/Cataclysm-DDA#65950]
### Describe the bug

Skater is considered a mutation, and not a proficiency, which in my opinion more correct. Also it's impossible to train it or get another way ingame without debug mode. 

### Attach save file

N/A

### Steps to reproduce

Start game, take Skater background.
Find it in mutations list. 

### Expected behavior

I assume, that skater is a proficiency, and must have some ways to train it, like prolonged use of rollerskates, or with some special furniture, like Parkour Expert can be obtained.

### Versions and configuration

- OS: Windows 10 Pro 22H2
- Game Version: experimental 0.G 2023-05-31-0617
- Graphics Version: Tiles
- Game Language: English
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions] ] (also checked on CDDA only)

**Comment by GuardianDll** [comment]
i wonder does adding `"profession": true,` fixes it or not?

**Comment by CatWithFourEyes** [comment]
> i wonder does adding `"profession": true,` fixes it or not?
{
    "type": "mutation",
    "id": "PROF_SKATER",
    "name": { "str": "Skater" },
    "points": 1,
    "description": "You are skilled in maneuvering on skates.  You suffer lower penalties to dodging and are less likely to fall down if hit in melee combat while you're wearing rollerskates or rollerblades.",
	"profession": true,
    "valid": false
  },
  
  Result - still in "traits" menu.

**Comment by Terminutter** [comment]
The professions system has so much potential for development - totally agreed. Having parkour expert moved to it was great, and I could see some other things like martial arts eventually fitting in it so you start off learning it, rather than reading a book 50 times and becoming a master.
