### ISSUE TITLE
Watermelon calories and quench seem absurd

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#65967]
### Describe the bug

Watermelons are split into two pieces and each offer 1355 calories and 826 quench each. While they can be separated into 16 watermelon wedges with a knife, this... this doesn't look right.

### Attach save file

[Athena - X-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11630665/Athena.-.X-trimmed.tar.gz)

### Steps to reproduce

1. Find a watermelon.
2. uhhhhhhhhhhhhhhhh

### Expected behavior

I don't actually know. If this is correct, it feels absurd.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/2125926/1db80825-9e97-4495-bbcb-a4dc137877b4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 50f00e9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Lonely Evac Scenario [Lonely_Evac]
]

**Comment by kilozombie** [comment]
[The USDA says that a good-sized watermelon is around this 1300-1500 kcal range](https://fdc.nal.usda.gov/fdc-app.html#/food-details/1102698/nutrients), but those values should be halved when you cut the watermelon in half, I assume.

**Comment by fairyarmadillo** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/65924
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/8f2ab34d-bf6e-4ca5-9801-e1451dea0e82)

This PR should close this issue. Watermelons and wedges are separate items, disassembling them destroys the watermelon and gives you much more reasonable wedges instead.

**Comment by Karol1223** [comment]
These are full watermelons not wedges, like Fairyarmadillo said. I changed that during my fruit rework. The problem is for some god-forsaken reason watermelons still love to spawn in stacks of 20... and I can't tell you why. I checked itemgroups. I can't see what would do that. I thought it was from the default stack (which got removed during the fruit rework so that's also not it). The quench may be too high because I calculated it from water content of the fruit, but the calories add up.

**Comment by fairyarmadillo** [comment]
> I won't tell you to change that back but just to point this out - I left full watermelons edible just for shits and giggles. Normal non-mutated players still aren't able to eat them because they'll get a popup about becoming engorged if they try (even if starving). Having them be edible meant large mutants could possibly eat them whole (I believe, anyway) but if you believe it's best to make them inedible that's your call.

It was funny, but my reasoning was twofold - the item had like a 10 or 20 minute consume time, which could be a nasty surprise for a suitably large character with an inattentive player, and I also didn't want it showing up as edible in your eat menu if you couldn't ever actually eat it. This was partly for neatness but also to avoid player confusion.

**Comment by Inglonias** [comment]
So, leaving these things as edible but leaving their ridiculous (but accurate) values would probably tell a reasonable player that something is up that should make them think twice before consuming. On the other hand, if someone else looks at 853 quench and thinks there's no way that can be right, then we're going to get more issues like this one.

As this is currently intended behavior, I'm inclined to close this issue. Whether it should be possible to eat an entire watermelon whole is a different question.
