### ISSUE TITLE
Car Doors Crash the Game

### ISSUE THREAD

**Issue by EmDotRand** [CleverRaven/Cataclysm-DDA#65975]
### Describe the bug

Attempting to step on an open car door freezes then crashes the game.  Updating the game did not resolve the bug.

### Attach save file

See Additional Context

### Steps to reproduce

1. Start a new character.
2. Find a car.
3. Open one of its doors.
4. Try to step on it.

### Expected behavior

My character moves onto the car door with increased move cost.

### Versions and configuration

See Additional Context

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11639225/debug.zip)
[Willernie.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11639255/Willernie.zip)

**Comment by irwiss** [comment]
Can't reproduce using either of the 2 cars in attached save on 464a535543f14f3e52493f8636b3eb23f56dc023 (latest master)

**Comment by SurFlurer** [comment]
Cannot reproduce on MSVC build either.

**Comment by SurFlurer** [comment]
Cannot reproduce on linux either.

**Comment by RenechCDDA** [comment]
Do you have a crash.log? Can you describe the actual crash? i.e. Do you get an error message, does it "ctd", does it *freeze* and force you to close it?
