### ISSUE TITLE
Sewage treatments are not connected to sewage systems

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#6597]
So it seems the generation of sewers broke at some time.

Sewers are astonishingly rare but foremost, sewage treatments never connect with sewage systems. I can remember that in older versions, sewage treatments _always_ were connected.

Seen in 0.A and even 0.9.
##

**Comment by ZhilkinSerg** [comment]
https://github.com/ZhilkinSerg/Cataclysm-DDA/tree/mapgen-sewer-connections
