### ISSUE TITLE
|| 4" Casters make moving a cart harder.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#65972]
### Describe the bug

My strength 6 character uses a foldable cart he calls "gopher".  After updating to the newest experimental, he can no longer pull the cart except on streets, and even on streets my messages gets spammed by, "It takes some time to move the gopher."

Removing the casters lets me once again pull the cart over grass, and over roads without spam messages.

### Attach save file

[Holcomb-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11635822/Holcomb-trimmed.tar.gz)

### Steps to reproduce

1. Open save.  Character should already have an EMPTY foldable cart grabbed.  
2. Drag the wheeled cart around.  See lots of, "It takes some time to move the gopher" messages, and you strain yourself pulling it on the grass.
3. Remove casters.
4. Drag the cart around.  You will have no problem dragging it over the street or the grass to the left.

### Expected behavior

Wheels make a cart easier to move over pavement, dirt and short grass.

If || no longer means "like new," it still means nothing more than a wobbly wheel, which doesn't make it more difficult to move than no wheels at all.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-2161-g1484ebeee9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sly's Skill Antirust [slysskillantirust]
]

**Comment by epsimpson** [comment]
I tried it with ++ health casters.  Still easier to drag a cart over pavement without them.

**Comment by anoobindisguise** [comment]
Question, do you hear it making "a scraping noise" when it is without any caster wheels?
The if statement in grab.cpp checks for `grabbed_vehicle->valid_wheel_config()` otherwise the strength requirement is always 10x higher (if it has wheels, it checks for its current traction like the standard vehicle offroading calc). It's possible it's passing the valid_wheel_config() check despite not having any wheels.

**Comment by Inglonias** [comment]
A save file would be incredibly useful for diagnosing this issue. You can generate a minimized save archive from the info section of the debug menu while in-game.

**Comment by fairyarmadillo** [comment]
Could this be related to #64867 ?

**Comment by Inglonias** [comment]
I'd put money on it, yeah.

**Comment by epsimpson** [comment]
Sorry, I had to step out after submitting this.  

No scraping noise, you probably know that by now.  Didn't know about #64867, it explains the "takes some time" messages spamming the message box.  If I were a survivor with these crafting skills, I'd make some larger wheels to replace the casters (still single tile), rubberize them to reduce road noise, and find a way to muffle that shopping cart rattle.

**Comment by fairyarmadillo** [comment]
@anoobindisguise you may want to take a look at this.

**Comment by anoobindisguise** [comment]
> Sorry, I had to step out after submitting this.
> 
> No scraping noise, you probably know that by now. Didn't know about #64867, it explains the "takes some time" messages spamming the message box. If I were a survivor with these crafting skills, I'd make some larger wheels to replace the casters (still single tile), rubberize them to reduce road noise, and find a way to muffle that shopping cart rattle.

OK so the issue is that the wheel-less shopping cart is somehow being considered as a wheeled vehicle otherwise it would be subject to wheelless behavior. I know that a wreck was being considered as a wheelless behavior so something is going wrong in vehicle.cpp OR I am misapplying a function from vehicle.cpp in grab.cpp

**Comment by anoobindisguise** [comment]
No, after testing it it looks like the shopping cart is making a scraping noise after all while wheel-less. 
I'll look over the wheeled formula and make sure that str_req never is multiplied by >10.

**Comment by anoobindisguise** [comment]
I'm having some trouble replicating this issue. I've never found an instance where a shopping cart got easier to move after removing the casters.

**Comment by Golfavel** [comment]
> I'm having some trouble replicating this issue. I've never found an instance where a shopping cart got easier to move after removing the casters.

[Cape Yakataga-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12045087/Cape.Yakataga-trimmed.tar.gz)
Game Version: bf5848d [64-bit]

Notice the move/speed indicator. When moving the top cart (that has casters), it's defaulting to 180 on the road, occasionally going up to 380; on the nearby grass field, it varies between 400-600. Without casters, it defaults to 100 (which is also the movement speed when not dragging anything), occasionally jumping up to 300.

**Comment by esotericist** [comment]
i haven't loaded the above attached save, but i'm personally experiencing it on a build from just a few days ago. lightly loaded (like, all of 9kg contents) cart got stuck immediately on grass, removed casters, was able to drag it just fine.

after i tried removing the casters, i was able to confirm the cart was easier to dragon asphalt without them, too.

[Nitro-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13250338/Nitro-trimmed.tar.gz)


```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: 0.G-4845-gc5c85bd9bb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]
```

**Comment by esotericist** [comment]
also i'd like to add while putting this on the proposed blocker list that *four inch* casters should be expected to move at least somewhat across grass and dirt. maybe not truly difficult terrain while extremely heavily loaded, but i sure as heck pull things with similar wheelbases across grass, dirt, and even up/down hills all the time iRL, and i am far from typical strength.

**Comment by UNOwenWasMe** [comment]
Experiencing the exact same issue, cannot drag my shopping cart over grass at all if there's even just ~10kg in it. It literally just says I lack the strength to drag it and it refuses to move. If I take some stuff out, I can drag it, but I strain myself and I get a lot of pain. From dragging a shopping cart.

**Comment by Inglonias** [comment]
Can you reproduce the issue? Ideally, provide a save file as well. You can generate a minimized save archive from the debug menu

**Comment by esotericist** [comment]
> Can you reproduce the issue? Ideally, provide a save file as well. You can generate a minimized save archive from the debug menu

how many saves do we actually need for this? i count three, including mine.

**Comment by Inglonias** [comment]
That is a fair point.

@UNOwenWasMe I take it back. You don't need to provide us a save file if you don't want to.

**Comment by RenechCDDA** [comment]
Very funny bug. Anything below 100kg can be dragged for free, wheels or not.

```
09:15:03.451 ERROR : Cataclysm-DDA\src\grab.cpp:106 [grabbed_veh_move] str_req before 0-wheel pull is 0
09:15:04.216 ERROR : Cataclysm-DDA\src\grab.cpp:108 [grabbed_veh_move] str_req after 0-wheel pull is 0
09:16:24.240 ERROR : Cataclysm-DDA\src\grab.cpp:106 [grabbed_veh_move] str_req before 0-wheel pull is 0
09:16:24.865 ERROR : Cataclysm-DDA\src\grab.cpp:108 [grabbed_veh_move] str_req after 0-wheel pull is 0
[ Casters reinstalled ]
09:16:32.425 ERROR : Cataclysm-DDA\src\grab.cpp:90 [grabbed_veh_move] base str_req is 0
09:16:33.208 ERROR : Cataclysm-DDA\src\grab.cpp:92 [grabbed_veh_move] mc is 0
09:16:33.793 ERROR : Cataclysm-DDA\src\grab.cpp:101 [grabbed_veh_move] str_req before traction is 1
09:16:34.305 ERROR : Cataclysm-DDA\src\grab.cpp:104 [grabbed_veh_move] str_req after traction is 8
```

**Comment by RenechCDDA** [comment]
It is absolutely a bug that a human being exerts no force whatsoever to push a 99kg solid block of steel across asphalt. That will be changing.
