### ISSUE TITLE
Underground Zombie suggestions.

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#65979]
### Is your feature request related to a problem? Please describe.

I've been thinking for a bit about how to spice up the underground zombie scene and I coalesced around a few main ideas to give underground areas a bit more of a unique adaptation showing our blobby eldritch friend reacting or experimenting with its playthings.
This list is mainly me writing down/sharing my ideas if anybody finds them cool enough to bother, I might at some point add them to the game when I have time for it.
The main things I think the game could use are distinct location based original zombies showing zombified people that were present in the main underground areas we have (mines, subways and sewers) that would converge into 3 main archetypes:

1. Sessile/Dead Space Corruption like evolutions responding to restricted spaces and low activity of underground environments
2. Fast, very aware of their surroundings but blind horrors
4. Worm/Snake-like crawler evolutions

### Solution you would like.

From the previously discussed archetypes I've mentioned, I've so far thought up the fellow monsters:

- Zombified Sanitation Employee : Pretty self explanatory, just a walking sewer worker that happened to get zombified.

- Crawler Sewer worker : Not sure of a name yet, but basically just a base sewer crawler for later crawler/sessile evolutions.

- Zombified Metro Worker : Same as first suggestion, just a walking working person that got Z'd.

- Subway Crawler: same as previous crawler, just the base material the later sessile/crawler evolutions will work with, perhaps could have a cool bit in their description about how it looks like they literally got ran over by a moving train?

- Slumped Crawler: Simply a miner zed that got caught in a tunnel collapse/mining accident, leaving most of its lower body ruined, missing or nonfunctional

- Worm/Grub: Name could change, first stage crawler evolution, blob started salvaging the three previously discussed crawlers by improving their speed with more strength on the arms to drag themselves and lower part coalescing into a tube-like shape

- Crawling Horror: end stage of the crawler line, although further variations could be introduced, this zombie's lower side is now vaguely snake/wormlike and the extremities of its two very strong arms it drags itself with have morphed into necromorph-like bone spears, the resulting monster being a pretty fast, creepy and dangerous piercing damage focused crawler

- Wall wretch: This crawler or walking zombie has started gluing itself to a tunnel surface, its arms elongating to a freakish reach, each part (upper and lower arm, fingers) elongating equally, main attack is a pretty long grab and pull move pulling you towards it to get bitten, nothing ridiculous, probably normal zombie damage capabilities.

- Cnidarian Horror: end stage of the wall wretch, its arms have evolved into stems with 10 extremely long and spindly filaments garnished with jellyfish-like sting organs capable of slowly poisoning and slowing down the player. Probably needs to be balanced to be a support monster that becomes truly dangerous when misjudging the situation and it receiving backup while it weakens the player.

- Wheezing wretch: A crawler or walking zombie going through the same process of sessile adaptation as the wall wretch, but its limbs atrophying while its abdominal cavity stretches to absorb toxic gases within its environments it can then release on the player as a cone of gas when within range, like the other sessile line, more of a support zombie to other dangers within the dark tunnels than a serious standalone threat.

- Firedamp wretch: Evolution of the wheezing wretch and gaining a two stage attack ability of throwing a new kind of flammable gas in the first stage while perhaps cuing in the player somehow that the zombie will then have a cooldown for a few turns before being able to set fire to/detonate its cone of gas. This would of course be a very cool but powerful and perhaps game-ending attack, so careful balancing and clues should be involved to make the firedamp effect strong but not completely unfair.

- Pale things: Somewhat fast quadrupedal and more or less blind pack monsters with sharp teeth evolved from the various underground walking zombies that I visualize more like the pack mutants of Metro, not that concerning alone, pretty concerning when you start having more than a couple chasing after any noise prey could be making.

- Bristling Horrors: I realize I'm not being very inventive with the amount of horror zombies I'm proposing, but names can change. This would be a late game evolution of the pale thing where the pale thing has grown larger and evolved a mat of hair-like sensory appendages on its back able to blind-sense minute alterations in the air currents of the somewhat stable atmosphere of underground environments. Extremely fast, very scary to fight in melee, and the blind sense would mean that even invisibility derived from mutations, bionics or artefacts would be useless to hide, you can't outrun it, you can't hide from it, lets hope you were using a torchlight to spot them before getting within its perception range. Overall just supposed to be a very scary end game monster that doesn't happen to be another hulk.

### Describe alternatives you have considered.

1. Not thinking about more cool monsters ideas
2. Putting more cool monster ideas

**Comment by fairyarmadillo** [comment]
Most of what you're describing already exists and spawns in the tunnels, they're just not zombies, which makes sense because there generally aren't tons of people running around in subway tunnels and mines. "Pale things" in particular are just feral trogs. Mutants and nether creatures don't directly zombify, but they do produce amalgamations who already do a lot of this stuff.

Also can we please retire "horror" as a noun in this game? 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/d2888356-caa0-4ab7-966e-ed7e6022e834)

**Comment by sadenar** [comment]
> Most of what you're describing already exists and spawns in the tunnels, they're just not zombies, which makes sense because there generally aren't tons of people running around in subway tunnels and mines. "Pale things" in particular are just feral trogs. Mutants and nether creatures don't generally zombify, but mutants do produce amalgamations who already do a lot of this stuff and specifically have the Dead Space vibe you're describing.
> 
> Also, I think we should retire "horror" as a creature name in this game:
> 
> ![image](https://user-images.githubusercontent.com/94415528/243076039-d2888356-caa0-4ab7-966e-ed7e6022e834.png)

I myself agree that horror is probably an overused name for monsters, and would totally accept any smarter and more original names anybody who likes these concepts could come up with.
However I don't agree that the feral troglobites and amalgamations already occupy the niches I lined out as they are explicitly the blob repurposing mutant flesh into engineered abominations, while most of what I listed is simply the blob repurposing normal zombies to underground environments.
