### ISSUE TITLE
Gallon zipper bags cannot collect water from a lake

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#65996]
### Describe the bug

Gallon-sized zipper bags cannot draw water from an infinite source like a lake or river. This is despite the fact that their item description says that they can contain liquids.

### Attach save file

[Athena - X-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11644388/Athena.-.X-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save file
2. Attempt to put water from the lake immediately to my character's north into the zipper bag
3. `gallon-sized zipper bag can't to expand to add any more water` appears in your message log, and it won't fill the bag.

### Expected behavior

Either remove the "can contain liquids" part of the item, or allow it to expand to contain water from a lake.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 5325c6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Lonely Evac Scenario [Lonely_Evac]
]

### Additional context

Also, there's a typo in the message that appears, but that's a secondary concern.

**Comment by mqrause** [comment]
The error message means it's inside another pocket and filling it would expand it beyond that pockets capacity. (And there's a typo in the message.)

**Comment by Inglonias** [comment]
I am able to fill the container while wielding it. That said, this still shouldn't be happening, since my hiking backpack had plenty of space if I recall correctly...

**Comment by mqrause** [comment]
There might be space in the backpack, but not in the pocket the zipper bag is in. See #62872 as a previous issue about this.

**Comment by SurFlurer** [comment]
Maybe we can first pull out the zipper bag, fill it with water, then insert it back?

**Comment by kilozombie** [comment]
Backpacks have multiple containers, some small and some large. Seems likely to me that the unfilled zipper bag is being automatically put into the smallest container that can fit it, instead of the big main pocket. You can fix this by moving it into the bigger pocket before filling it, or filling it in your hands and then letting it get automatically placed somewhere it'll fit (as SurFlurer said).

**Comment by Inglonias** [comment]
Alright. This is looking more and more like a mistake on my part. Closing the issue.
