### ISSUE TITLE
Implement variable objects as possible inputs for emitters

### ISSUE THREAD

**Issue by LightDimf** [CleverRaven/Cataclysm-DDA#65993]
### Is your feature request related to a problem? Please describe.

Some types of JSON objects have fields that accepts variable objects as input instead of constant values thus providing possibility to more dynamical mechanics. But most of the json types doesn't support variable objects as input to it's fields.
One of such type is emitters.

### Solution you would like.

Implement variable objects as possible input for emitters json fields. More specifically:
- "qty" - dynamical amount of fields placed which also would mean dynamical radius of space where fields are created;
- "chance" - dynamical chance of spawning the fields each time fields is emitted;
- "intensity" - dynamical intensity of the emitted field.

### Additional context

Many other json object types would also benefit from implementing variable objects as their field types.

**Comment by Maleclypse** [comment]
#61947 should give you a model to follow in extending random amounts
