### ISSUE TITLE
Reading in the dark or it never gets dark

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#65997]
### Describe the bug

Reading in the dark seams to be possible in this release version (2023-06-02-0045).

Or it never gets dark at night (not sure), allowing reading through out the night sans light source.

### Attach save file

[Alfalfa-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11644396/Alfalfa-trimmed.tar.gz)

### Steps to reproduce

1. Wait until night (dark).
2. Read book.

### Expected behavior

Expected to be prompted that it was too dark to read.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 1484ebe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Magiclysm [magiclysm],
    MST Extra [MST_Extra],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Dorf Life [Dorf_Life],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by GuardianDll** [comment]
some nights are just less dark because of full moon, so you still can read (albeit really slow)

**Comment by TadhgEomonn** [comment]
Okay. Have not experienced it before (in game), but I will accept the possibility of reading on a moon-bright night.

Sorry if this has wasted anyone's time.
