### ISSUE TITLE
Science lab under a small pond.

### ISSUE THREAD

**Issue by JWEgamer** [CleverRaven/Cataclysm-DDA#66008]
### Describe the bug

There seems to be a bug where a science lab entrance spawns under a pond, making it inaccessible. 

### Attach save file

[Pueblo-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11646152/Pueblo-trimmed.tar.gz)

### Steps to reproduce

Not sure how to reproduce it, just found a pond that was labeled as "forest" on the map. (Not a map extra) and looked down using the experimental 3D vision, And saw a science lab under the pond.

### Expected behavior

I expected to see nothing under the pond but saw a science lab. And if this was intentional then I expected to be able to dive down into the lab.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/125152103/d3293d0a-76a8-49f9-96d2-86bef9bf7702)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/125152103/d6131fd5-4a8c-4aef-b82f-683b1c3a9dd3)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/125152103/4a572c78-93d9-4ae4-8290-9e4e005ace88)

### Versions and configuration

Windows 10
Build: a307843 (tiles)
Normally generated world with no mods.

**Comment by terryjacob200** [comment]
Attempted to replicate on d6ec466 in a world with no mods base [dda] only.

Debug spawned both types of lab vents then spawned "mx_pond_forest" and "mx_pond_forest_2" on the "forest" tile that hides the vent.   The vent was overwritten by the pond but there was no indication of the map extra despite auto notes being on.

I was not able to see down into the labs with 3d vision on.

**Comment by anoobindisguise** [comment]
I've had this happen a couple times too.

**Comment by Procyonae** [comment]
I'm pretty sure #66123 fixes this, the current OMT directly copies forest which I think is why it's ending up with extra spawns that it shouldn't get like this, these variants of pond purposefully don't provide autonotes though which is odd, adding them appears trivial if that would be appreciated, I don't see an issue with them overwriting stuff they just shouldn't be spawning on this tile in the first place
