### ISSUE TITLE
Stealing large amounts of items over the advanced inventory manager

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#66004]
### Is your feature request related to a problem? Please describe.

I was always frustrated, when i could not steal large amounts of items over the advanced inventory manager, because of the thief mode, which can not be disabled, for the advanced inventory manager.
![thief mode](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/4c330653-cc35-4778-ad62-b033f0dc2ed1)

### Solution you would like.

There should be a way to disable thief mode for the advanced inventory manager as well, so you do not have to pick up hundreds of items manualy to do so.

**Comment by Luca-spopo** [comment]
Im running into the same issue
