### ISSUE TITLE
Pluggged in Smartphone does not charge when plugged into vehicle controls

### ISSUE THREAD

**Issue by Pennerbart** [CleverRaven/Cataclysm-DDA#66007]
### Describe the bug

I asked on the discord what the plug-in feature of the Smartphone should do, and I was told that the Smartphone should recharge when plugged into vehicle controls. But the smartphones battery charges did not increase over time. But while plugged in the smartphone doesn't use charges when in use.

(This is my first post here so I am sorry if i messed up something)

### Attach save file

N/A

### Steps to reproduce

1. make a character with a smartphone
2. use up some charges
3. Plug the smartphone into an vehicle with working controls and full battery 
4. wait for a couple of hours
5. check if charges are different than before

### Expected behavior

I expected the smartphone to regain spend charges while pluuged in for hours

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 5325c6e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by macrosblackd** [comment]
I can confirm - plugged in a 90/120 smartphone and while it never discharged, it never gained charge either.
