### ISSUE TITLE
Game crashing quest item from doctor at Refugee

### ISSUE THREAD

**Issue by Vgoloshivskiy** [CleverRaven/Cataclysm-DDA#66019]
### Describe the bug

Doctor at refugee center gives item without description in order to download map item is data_card.

### Attach save file

[Grant Center-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11651882/Grant.Center-trimmed.tar.gz)

### Steps to reproduce

Load in a game it will inform you about item without description this item was given by Doctor formission find Lab Tunnels.
Try to use console to download map.
Game crashes.

### Expected behavior

I get memory card or usb with lab tunnels?
idk my first time getting this far.
Another issue is that all USB quest data is always named lab data for exeption of infection data (workstation data, encryption codes, research archive)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56963648/f406b982-3732-4635-a6b6-ebf4d1106ad7)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 4f70c47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11651938/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11651940/debug.log)

**Comment by SurFlurer** [comment]
Can /confirm. data_card has long been obsolete and no one bothered to cleanup the usage of it.

**Comment by RenechCDDA** [comment]
Here's the culprit, as mentioned. https://github.com/CleverRaven/Cataclysm-DDA/blob/4f113f720614bf82dfa7f49c6c29b2067d05a4a2/data/json/npcs/refugee_center/surface_staff/NPC_old_guard_doctor.json#L198

These references also need to be changed:

https://github.com/CleverRaven/Cataclysm-DDA/blob/4f113f720614bf82dfa7f49c6c29b2067d05a4a2/data/json/npcs/computers/TALK_TRAIN_DATA.json#L16

https://github.com/CleverRaven/Cataclysm-DDA/blob/4f113f720614bf82dfa7f49c6c29b2067d05a4a2/data/json/npcs/computers/TALK_TRAIN_DATA.json#L35

https://github.com/CleverRaven/Cataclysm-DDA/blob/4f113f720614bf82dfa7f49c6c29b2067d05a4a2/data/json/npcs/robofac/robofac_intercom/robofac_intercom_missions.json#L28

https://github.com/CleverRaven/Cataclysm-DDA/blob/4f113f720614bf82dfa7f49c6c29b2067d05a4a2/data/json/npcs/robofac/robofac_intercom/robofac_intercom_missions.json#L30
