### ISSUE TITLE
Modified versions of sword bayonet and combat knife seem to be redundant, or their changes are not described well enough

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#66011]
### Is your feature request related to a problem? Please describe.

Currently in game there is an option to craft a modified versions of sword bayonet and combat knife. These options seem to not add any functionality to the weapons, despite adding a flag. Weapons with underbarrel rails do not accept neither of the variations, and weapons with underbarrel mounts can accept the default versions anyways.

### Solution you would like.

1. Explaining the changes or flags better if there is a real mechanical difference between the versions (would be helpful if descriptions mentioned flags like "RADIO_MODABLE" (for example: "this item can be modified to receive remote commands"), like "STR_DRAW" and "MAG_COMPACT" are mentioned);
2. Adding that mechanical difference (say, modified bayonets can be attached to underbarrel rails);
3. Removing the variations if there is no actual difference between modified and unmodified items.

### Describe alternatives you have considered.

Doing nothing about it.

### Additional context

Honestly, I am just confused why there is an item modification that does not have a reasonably noticeable difference.

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md

`PUMP_ACTION` Gun has rails on its pump action, allowing to install only mods with PUMP_RAIL_COMPATIBLE flag on underbarrel slot.
`PUMP_RAIL_COMPATIBLE` Mod can be installed on underbarrel slot of guns with rails on their pump action.

**Comment by randomtyper** [comment]
So, the only reason that flag exists is because of mounting items on pump rails? Despite IRL no bayonet will be directly attached to the pump and pumps with rails do not need special changes for the attachments like front grips.

**Comment by RenechCDDA** [comment]
See #23725 for the implementation details. It still seems to be relevant, as the KSG still exists.

**Comment by randomtyper** [comment]
Of course, Kel-Tec. Right. Still doubt about viability of bayonets on pumps, though. A dedicated bayonet lug slot and optional ability to install a bayonet on underbarrel slot (as modification to the bayonet, likely without pump rail compatibility) would be quite a bit more realistic imo.

Here is an example of bayonet for KSG-like gun. It's either that or spikes protruding from the magazine tubes: https://www.reddit.com/r/knives/comments/w75ucf/does_anyone_have_a_kel_tek_folding_bayonet_that/

**Comment by randomtyper** [comment]
Alright, with the context of the issue changed, I think there is no reason to keep this issue up.
