### ISSUE TITLE
regex based log tracker

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#66021]
### Is your feature request related to a problem? Please describe.

there are some things that the player needs to keep track of during the gameplay and after some time of ausence you tend to slip a few things or some important things just go easily unnoticed, like the latest meals, medications, itens one might have dropped distant from their settlement, things that went broken. Also the log present in the game has an understandable limit of lines, so it is not enough to just feature filtering on that log

### Solution you would like.

having a separated log, which is fed from transparent regex filtering of the overall log. The filtering might not need to be executed on every turn necessarily. It might be executed after counting some number of lines added and started from the line corresponding to the latest counter. As for the interface, that change can be implemented by adding a second tab that the player would see to the side of the overall log

**Comment by Zireael07** [comment]
Isn't this what diary is for?

**Comment by SurFlurer** [comment]
> Isn't this what diary is for?

I'm not aware of a way to easily add one line of log to the diary. Is there such a way? Maybe there should be one.
