### ISSUE TITLE
Throwing grenade into crowd of zombies & corpses crashes the game

### ISSUE THREAD

**Issue by DvdMiller** [CleverRaven/Cataclysm-DDA#66023]
### Describe the bug

As the title says, an active grenade thrown directly into the middle of the crowd crashes the game once it arrives, I was driving a bicycle while doing it but I have yet to be able to replicate the issue while on foot, perhaps because the crowd disperses too quickly  in that case.

### Attach save file

[Harveysburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11653459/Harveysburg-trimmed.tar.gz)

### Steps to reproduce

1. Wield grenade from inventory in hands
2. Hop on bicycle and begin driving directly to the west where the group of zombies are
3. Activate grenade (when close ofc)
4. Throw active grenade and have it land directly inside crowd of the zombies and corpses that are to the west
5. The game will crash if it does land directly within the crowd, the only times it hasn't is when I have missed them.

### Expected behavior

For the grenade to blow up the zombies, not the game itself 

### Versions and configuration

- OS: Windows 10
- Game Version: a307843
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions

**Comment by SurFlurer** [comment]
Might will be fixed by #65984?

**Comment by RenechCDDA** [comment]
Confirmed it has been resolved by the linked issue.
