### ISSUE TITLE
corpses, alongside some butchering yields are fireproof

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#66039]
### Describe the bug

While trying to dispose of a zombie dog's corpse by starting a fire, I noticed that I instead get the message "There is nothing to light there." 

I then lit a nearby shrub on fire and tossed the zombie dog onto it, but the dog's corpse wouldn't burn no matter what.

### Attach save file

N/A

### Steps to reproduce

1: kill a mob, such as a zombie
2: attempt to set the dead zombie on fire, or set it on top of other burning materials
3: Try butchering a separate zombie and see if any of its butchering yields can be set on fire as well.

### Expected behavior

I expected the corpse to burn/

### Versions and configuration

Latest Experimental Version.

**Comment by gettingusedto** [comment]
this is probably more of an issue of items burning inside a `FIRE_CONTAINER` furniture burn longer than items that's isnt inside such furnitures.

**Comment by RenechCDDA** [comment]
>While trying to dispose of a zombie dog's corpse by starting a fire, I noticed that I instead get the message "There is nothing to light there."

Intentional. You can't just put a lighter to a corpse and have it go up like a barbecue.

>I then lit a nearby shrub on fire and tossed the zombie dog onto it, but the dog's corpse wouldn't burn no matter what.

Would need to see the save, but flesh should burn just fine in larger fires. It even provides a decent bit of fuel (not a lot, but *some*).
