### ISSUE TITLE
Can lose Epicuticle while retaining Chitin Charapace and Feathers underneath.

### ISSUE THREAD

**Issue by Swootch** [CleverRaven/Cataclysm-DDA#66049]
### Describe the bug

The Feathers mutation from the bird tree can override/replace your Epicuticle without doing anything to your Chitin Charapace, leaving you with a full-body-uncomfortable armor you can't unequip (Chitin Charapace is integrated armor). You also apparently then have feather underneath that Charapace. **Furthermore** your Chitin Charapace will eventually molt, which causes your Epicuticle to reappear, without making you lose your Feathers mutation. Trying to fix this with in-game means proved to be very difficult because trying to remove Feathers leaves you with Rough Skin, which is a pre-requisite for Epicuticle, but you already have Epicuticle (ordinarily you lose Rough Skin when it turns into Epicuticle).

### Attach save file

N/A

### Steps to reproduce

1. Get Insect mutations Epicuticle and Chitin Charapace.
2. Take Bird mutagen and happen to get the Feathers mutation.
3. Feathers replaces your Epicuticle, leaving the Charapace intact for further complications.

### Expected behavior

Chitin Charapace is lost before Epicuticle, since one is presumably growing out of the other.
Alternatively, the Charapace is simply destroyed upon molting the next time, since it presumably can't regrow without an epicuticle.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 4602415 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks]
]

**Comment by fairyarmadillo** [comment]
I did molting, so I'll take a look at this.
