### ISSUE TITLE
Modify Weariness Gain by Fitness & Athletics

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#66053]
### Is your feature request related to a problem? Please describe.

Not a problem, exactly, but more a logical inconsistency. Weariness currently appears to be a static pool for everyone - tasks that are high intensity cause weariness at the same rate whether you're fat or thin, fit or floppy. It's simple, easy, and a bit unrealistic.

In practice, weariness is strongly linked with fitness. Someone who is healthy and used to pushing their body for hours at a time will grow both tired and weary much slower than a greenhorn attempting the same work. Work in physical labor for a time and you'll find that the veterans, who haven't managed to injure themselves, can go all day without issue.

### Solution you would like.

Modify the rate of weariness gain based on fitness and possibly athletics. Low fitness, faster weariness. High fitness, slower.

### Describe alternatives you have considered.

Leaving it as is.

### Additional context

[PubMed on exercise and fatigue](https://pubmed.ncbi.nlm.nih.gov/19402743/ ) Only sort of related, but still interesting.

**Comment by fairyarmadillo** [comment]
This might be a good niche for athletics. Its contribution to the stamina pool is currently quite small, but if we think of it as being a knowledge skill that governs form and ergonomics rather than just a redundant measure of cardio fitness there's definitely room to expand it.
