### ISSUE TITLE
Character Sprites Drawn in front of Terrain/Furniture sprites instead of behind them

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#66052]
### Describe the bug

The character sprites got drawn infront of the terrain/furniture sprites instead of behind it, making standing behind terrain/furniture that has tall sprites like bookcases and trees looks weird.

### Attach save file

[Clintondale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11677249/Clintondale-trimmed.tar.gz)

### Steps to reproduce

1. spawn in a furniture/terrain that has tall sprites. In my case i used MSXotto+ and bookcase.
2. stand behind it
3. standing on the bookcase

### Expected behavior

The character sprites drawn behind the tall sprites.

### Screenshots

![Screenshot_20230607-195140](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/b2f307db-4e85-4048-a102-777cbdeb63e9)
![Screenshot_20230607-192511](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/e8d8c463-c820-4f83-8c7b-4068ac30eb93)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: fd8bbfe [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    cable stuff [cablestuff]
]

**Comment by Qrox** [comment]
Likely caused by #65738. @Rewryte could you look into this? I think it might have something to do with b2bd55b82d30e6fd54f7914a5578f989e603b438. It should probably draw all layers of each row before drawing the next row when drawing each z-level.
