### ISSUE TITLE
Parts Removed from Vehicles Cannot be Repaired

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#66074]
### Describe the bug

When removing a part from a vehicle, no matter how repairable it is while in place, repairability falls to match the part's damage. Parts can be repaired in situ, but once removed they cannot. If anything, parts should be much more repairable when not already attached to a vehicle.

### Attach save file

This is trivially reproducable.

### Steps to reproduce

1. Open new world in recentish experimental (I have it consistently on one of the 6/5 releases)
2. Spawn tools for repairing (welder, materials, mask, etc) and removing parts (saw, etc)
3. Approach vehicle
4. Observe that vehicle parts can be repaired while interacting with vehicle
5. Remove damaged but repairable part
6. Observe that the same repairable parts can no longer be repaired, and that their repairability has fallen to match their damage

### Expected behavior

Parts remain as repairable or more repairable when removed from a vehicle. Possibly eliminate repairability limit once a part is removed, or at least increase it drastically.

### Versions and configuration

Win 11 x64 tiles + sounds
V: 4602415 (and others)

**Comment by Moumix3** [comment]
Can confirm this is happening in my game as well, and seeing how awfully the degradation system is communicated (or rather not communicated at all), it took me most of 2 hours to understand what was happening and why I couldn't repair anything. Seriously annoying :(
