### ISSUE TITLE
Reclining Seats are uncomfortablely comfortable according to the description(Tsundere Alert)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#66075]
### Describe the bug

Recylining Seats can be used as beds ... according to the provided description they make uncomfortbale beds ... but allow you to sleep comfortably in them ... 

### Attach save file

N/A

### Steps to reproduce

Get a Reclining Seat
Read its description

### Expected behavior

Tsundere Reclining Seat Chan should decide if its comfortable or not to sleep in.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/a6d9103d-71a0-4a5a-a4dc-c01bbbfbf29a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: fc3bc85 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by fairyarmadillo** [comment]
They're two relative definitions of comfort. It is more comfortable than the ground, but less comfortable than a bed. So I guess it's just an iffy description.
