### ISSUE TITLE
Chainlink fences merged with filing cabinet in this garage's office

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#66092]
### Describe the bug

There's filing cabinets that merged with chainlink fences in this garage's office.

### Attach save file

[Clintondale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11709525/Clintondale-trimmed.tar.gz)

### Steps to reproduce

1. open attached save
2. filing cabinets merged with chainlink fence

### Expected behavior

Filing cabinets not merged with chainlink fences

### Screenshots

![Screenshot_20230610-023006](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/a1775ed2-1712-485d-a163-ab3e6166e36a)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: f9dc830 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    cable stuff [cablestuff]
]

**Comment by Procyonae** [comment]
Caused by #64866 adding chainlink fence to the roof palette when the map was using the same letter for filing cabinets and hadn't defined the terrain underneath it, I'll have a dig to see if I can find whether it effected anything else

**Comment by Procyonae** [comment]
Well that was quite a rabbit hole, ended up only finding one other instance but found plenty of other stuff that wanted updating too ;D #66103
