### ISSUE TITLE
[BombasticPerks] Error on perk selection

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#66095]
### Describe the bug

 DEBUG    : I don't know what to say for TALK_PERK_MENU_WAYOFTHEFIST. (BUG (npctalk.cpp:dynamic_line))

 FUNCTION : dynamic_line
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 1394
 VERSION  : 41f05da

### Attach save file

N/A

### Steps to reproduce

1. Create a world with Bombastic Perks mod
2. Create character
3. Kill something to gain perk
4. Try to choose way of the fist
5. See the error

### Expected behavior

No errors

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 41f05da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bombastic Perks [bombastic_perks]
]

**Comment by RDru** [comment]
@bombasticSlacks

**Comment by bombasticSlacks** [comment]
Thanks for the bug report, #66097 

That menu selection isn't a thing anymore it used to hold the 3 perks for way of the X, but I moved everything to their own section.
