### ISSUE TITLE
Can't install/remove vehicle part.

### ISSUE THREAD

**Issue by AkumaAikawa** [CleverRaven/Cataclysm-DDA#66114]
### Describe the bug

I can't install/remove vehicle part, everything else seem to work fine, can still drive, can turn on installed parts, change shape etc... The install and remove button also don't light up even though it can be use. I also put a screen shot of what may have cost the error, this happen after I update to the latest version.

### Attach save file

[Poestenkill-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11712506/Poestenkill-trimmed.tar.gz)

### Steps to reproduce

1.Examine vehicle.
2.Install or remove part.

### Expected behavior

The window close but nothing happen.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/46323107/26168c23-440f-4f55-92e4-22130b86561f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 102697f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by irwiss** [comment]
The reason nothing lights up is morale penalty for murder - try installing something and it'll show it in right panel

**Comment by AkumaAikawa** [comment]
Thank you, it didn't warn me about negative morale like with crating so I forgot
