### ISSUE TITLE
Allow martial arts to apply any effects onhit or oncrit

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#66111]
### Is your feature request related to a problem? Please describe.

#66034 has left a few of the martial arts in a rough state, but also opened the door for them to do more interesting things than just stun spam. A missing piece of the puzzle however is the ability to apply effects other than the few hardcoded choices currently available on hit or on crit.

This could have all kinds of interesting interactions with ie the grab system, it will also help with moving mutation attacks over to martial arts, as it'll allow things like envenomation to be jsonized.

### Solution you would like.

Just a couple new json fields in martial arts entries for applying effects to self or enemies on hit, applying effects to self or enemies on dodge, applying effects to self or enemies on miss, and applying effects to self or enemies on crit.

### Describe alternatives you have considered.

n/a

**Comment by Venera3** [comment]
MAs can already apply any effect via the `tech_effects` array.

**Comment by fairyarmadillo** [comment]
Awesome. Great work everybody, we did it!
