### ISSUE TITLE
Audit recipes using standard planks for using short planks too or instead of

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#66126]
### Is your feature request related to a problem? Please describe.

The short plank added by #60750 is used solely for the wooden chair of the same PR. Many recipes currently ingame use the 122cm standard plank, even ones where the end length implies wasting over half the length of it.

### Solution you would like.

Audit of recipes using planks to use short planks as either a substitute or whole replacement(to reduce mass conservation problems)

### Additional context

So many existing constructions dropping full 2x4s will make manufacturing items with short planks annoying if the player also doesn't also have  wood sawing 2.

**Comment by Karol1223** [comment]
My plan down the line was to also implement specific tool handles similar to how we have spear shafts, though that'll have to wait a bit before I get to that. Making it use short planks, for now, is a good substitute, yeah.
