### ISSUE TITLE
[Xedra Evolved] Hammering spell's created item's ability does not destroy the item when used

### ISSUE THREAD

**Issue by Farsan13** [CleverRaven/Cataclysm-DDA#66129]
### Describe the bug

The Hammering spell from the Dreamer school creates a "constructed hammer": a sledgehammer with an active ability to "Smash A Target" to deal 360-500 damage to an adjacent cell. 

The description of the object says that activating the ability will destroy the hammer, but the hammer it is not destroyed after using it, and the ability can be spammed without any additional cost.

### Attach save file

[Xedrian-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11714209/Xedrian-trimmed.tar.gz)

### Steps to reproduce

1. Learn the Hammering spell (From the nail object or debug)
2. Cast the spell to create and wield a "constructed hammer"
(Attached save file is at this place)
3. Activate the constructed hammer object as many times as you want.

### Expected behavior

I expected that the hammer would disappear after using the ability, as the description of the object says. Also, this ability is overpowered if you are allowed to reuse it instantly without any costs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 4a3740d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod]
]

**Comment by GuardianDll** [comment]
/confirmed
ok wtf? it has SINGLE_USE flag, but somehow doesn't uses it?

**Comment by GuardianDll** [comment]
Some people blame #63434, but i still see no way to fix it

**Comment by akrieger** [comment]
Fixed by #69229.
