### ISSUE TITLE
copy-from does not work for bodyparts

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#66134]
### Describe the bug

`copy-from` does not work for mandatory bodypart fields.

### Attach save file

N/A

### Steps to reproduce

1. Add the following bodypart definition:
```
  {
    "type": "body_part",
    "id": "eyes_bulging",
    "//": "Slightly larger, but still boring eyes",
    "name": "bulging eyes",
    "accusative": { "ctxt": "bodypart_accusative", "str": "bulging eyes" },
    "heading": "Blg Eyes",
    "heading_multiple": "Blg Eyes",
    "copy-from": "eyes",
    "opposite_part": "eyes_bulging",
    "hit_size": 0.9,
    "hit_difficulty": 1.25
  },
```
 2. Load game, observe complaint about missing encumbrance text

### Expected behavior

copy-from working for these lines as well

### Versions and configuration

Commit `ec7537a482c188b4775b79bf46f4ad6b33a80608`

### Additional context

This exact definition worked when I originally started work on limbs, so something broke along the way.

Ed:
0.G works with the definition

**Comment by Venera3** [comment]
Of course I screwed up the *next* definition, but the error message was not very helpful. Nothing to see here, move along.

**Comment by GuardianDll** [comment]
So it works?

**Comment by Venera3** [comment]
Indeed it does. The error message arrow points at the definition *before* the one that is missing the values, which tripped me up.
