### ISSUE TITLE
Dream Armour is always uncomfortable

### ISSUE THREAD

**Issue by PVM1234** [CleverRaven/Cataclysm-DDA#66147]
### Describe the bug

Dream armor is uncomfortable despite having close to skin clothes.

### Attach save file

[Shellsburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11716124/Shellsburg-trimmed.tar.gz), 
[Dillard-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11716135/Dillard-trimmed.tar.gz)

### Steps to reproduce

Make a character with dream armour, and an infiltration suit, or close to skin garment, and cast the spell.

### Expected behavior

I expected that the armor conjured by the spell would not be uncomfortable, at least when wearing an infiltration suit, as it stands the spell will always make you uncomfortable, and i don't think this is intended.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 602e9a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]
also
- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

So I generally play on stable, and when i cast this spell for the first time I noticed that it made my character uncomfortable. I didn't initially think much of it, because i figured that it was probably fixed in experimental. long story short i decided to check, and since it hasn't i figured i should post this. I think there are two ways to resolve this that I can think of, the first would be to make dream armor operate on a layer other than the personal aura, which seems to come before everything, that way would make it similar to the technomancer spell that summons plate mail. the second would be to move where the aura layer is, if it were after the outer layer for example, then if there are summoned barriers, and the like they would protect your clothes too.  I am not a programmer so I don't know much about how difficult that would be. also its my first time using this site so I hope I filled this out correctly. @KorGgenT @Maleclypse

**Comment by PVM1234** [comment]
Oh i forgot, one save file is from the latest experimental, and the other is my stable save.

**Comment by Maleclypse** [comment]
Fixed by a PR I can't find
