### ISSUE TITLE
Molting Effects Cut Off

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#66143]
### Describe the bug

The molting process added by #65459 added some molting related effects to inform the player they are going to molt and to get to a safe place.  Unfortunately, they are all cut off in the effects window, and so a player will not know the danger of molting.  There is no way to scroll this effect to read it, and as far as I know, effects do not appear elsewhere for the player to see.  Screenshots below.

### Attach save file

N/A

### Steps to reproduce

Debug one of the Carapace mutations
Use debug time travel and move forward until you get a message in the log that you will need to molt soon.
Check new molting related effect in the character menu
Observe that it appears to be only given one line and that it is too long to be read, even at normal scaling/font settings
Be sad

### Expected behavior

The point of the effect is to relay to the player that they will be immobilized by the molting process, as being immobilized for 5-15 minutes is pretty devastating if you're out in the zombie apocalypse.  But because it's cut off, players will not know this.  This will inevitably lead to people being killed and frustrated by the molting system -- which is a really neat mechanic that we don't want people to be mad about.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41651793/16f4ad29-5812-4be3-aa76-66019b67f279)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41651793/0ae00d1b-5803-4349-975f-32d537c1bf9e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 615c246 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

There also appears to be a typo in the regular molting effect, as seen in the screenshot above it says "somewheret" It's either a typo or there's supposed to be a linebreak and so it jammed the two words together.

Additionally, for those of us that scale our games, this lack of scrolling will be even more of an issue, as we'll see even less of the effect description.

**Comment by NetSysFire** [comment]
CC @fairyarmadillo, the PR author.

**Comment by fairyarmadillo** [comment]
IMO the problem is that effect descriptions can scroll off the edge at all. At the very least the player should be able to hit enter to pop up a more detailed view of the effect in a new panel or something.

I think that would be the ideal solution, but I don't know enough C++ to do that, so the only fix I can think of would be to change the string to something much shorter. I'm open to doing that, but as OP pointed out though, on 2X scaling, which is what I use, there's very little room to fit much of anything, so I'm not even sure what would be a good solution.

Thoughts?

**Comment by TheMurderUnicorn** [comment]
That section of the screen does have support for scrolling down (can be seen when viewing various encumbrances) but yeah, without a way to force effects to wrap, scrolling won't kick in because it just puts it all on one line.  Having a popout as you suggested in my opinion is the most ideal option, but yeah I would have no idea how to implement that, either.  I had never noticed this was an issue until today.  If you look at the weariness effects, those DO word wrap. (this is lightly weary)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41651793/f6a18673-0b71-4c14-8c85-d48c07aa7bf2)
So there may be a way to do it, I just have not looked at it, and it's possible that's somehow hardcoded and not do-able in json.

**Comment by fairyarmadillo** [comment]
Looks like \n in the description string will cause a line break. I'm not available to make a PR at the moment but I'll put one in later tonight to do that if someone else hasn't by then. Thanks for pointing this out.
