### ISSUE TITLE
Alternative map keys mod not working on all tiles

### ISSUE THREAD

**Issue by VladMasarik** [CleverRaven/Cataclysm-DDA#66142]
### Describe the bug

When using the the Alternative map keys mod, some tiles on the map should be changed from regular `^` character to a first letter in the name, eg. `h` for hardware store. However, this doesn't work for all variations of the buildings, eg. `^` is replaced with `h` for `s_hardware` tiles, but `s_hardware_1` is still kept as `^`, 

### Attach save file

[Boynton Beach-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11715693/Boynton.Beach-trimmed.tar.gz)

### Steps to reproduce

1. Disable tilesets for the overmap, eg. set it to `false` and use pure ASCII
2. Generate new map with the `alt_map_keys` mod enabled
3. Reveal the map using debug menu
4. Search for hardware stores, some of them will have just `h`, and some of them will be marked as `^`
5. In debug > teleport > long range > when you however over the `h` tiles, you can see it is just a `s_hardware` tile, while the `^` tile will be `s_hardware_1` or other variations.

### Expected behavior

The mod tries to make some locations more readable by replacing the `^` tiles. However, this is not done in all cases, and I would expect every variation of the hardware store, and other buildings to have their appropriate tiles, eg. `h` in case of the hardware store. Without it, the map is inconsistent.

### How it is currently:
![before](https://github.com/CleverRaven/Cataclysm-DDA/assets/28529900/030e2dc6-bc0c-4da9-aff5-808ed0f55348)

### With a custom fix:
![after](https://github.com/CleverRaven/Cataclysm-DDA/assets/28529900/de28cb05-c6e9-4569-abff-5a64bc745a81)

### Versions and configuration

```
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: 602e9a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key]
]
```

### Additional context

As you can see in the screenshots, I was able to fix the issue myself in the case of hardware stores. I changed these lines https://github.com/CleverRaven/Cataclysm-DDA/blob/e40864f9989a843c7f6525084e0ec87a9c30c674/data/mods/alt_map_key/overmap_terrain.json#L537-L544

To this:
```
  {
    "type": "overmap_terrain",
    "id": ["s_hardware", "s_hardware_1", "s_hardware_2"],
    "copy-from": "s_hardware",
    "name": "hardware store",
    "sym": "h",
    "color": "light_cyan"
  },
```

There is a fix, however it seems that it would require including every possible `id` for each variety of the tile. **I am happy to create a PR for a fix myself**. My single question though is, is there any other way to include all possible variations without having to specify each `id` of the variation?

I thought that the `looks_like` field would solve this issue by default, but I am opening this issue because it doesn't seem to. https://github.com/CleverRaven/Cataclysm-DDA/blob/e40864f9989a843c7f6525084e0ec87a9c30c674/data/json/overmap/overmap_terrain/overmap_terrain_commercial.json#L250-L258

**Comment by irwiss** [comment]
looks_like is for graphical tiles, only followed when graphics code probes for the specific bitmap and doesn't find it in current tileset
There's nothing to lookup in ascii as characters are always there (ignoring unicode-only font issues), so you need to enumerate ids to override
