### ISSUE TITLE
Things that need to be done for bionic limbs

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66182]
### Is your feature request related to a problem? Please describe.

I'm trying to brainstorm the things needed to be done to allow limbs that act as bionics and figured I'd make it an issue to help track those things and see if I'm missing anything.

### Solution you would like.

- Limbs need to be able to specify whether they're bionic or not.
- If a limb is bionic, it needs to drain bionic energy in place of calories/stamina and (not) set activity level accordingly. This could be done by moving stamina drain into a boolean function in character.cpp that finds limbs and then either tries to drain stamina or bionic energy depending on what's appropriate (dodging and walking/running would use the legs, while attacking/throwing would use arms, and swimming would use both) then the relevant function could short circuit if the stamina/energy check doesn't have enough of its resource. If the player has only one bionic limb, and one human limb, then the usage needs to be half and half, and presumably would allow the player to keep doing those actions without bionic power but with half the total limb score.
- Limbs need to be able to give bionic slots of the type of whatever limb they're mimicing, so a bionic arm needs to give however many arm_r/arm_l slots for bionics to be installable even though its id might be arm_r_bionic_1. Otherwise the bionic slots system needs to be re written.
- Limbs need to be able to wear clothing like the limb they're mimicing, or for paired clothing need to not wear that clothing while the other limb does. For example if you have a human right arm and a bionic left arm with a fusion blaster for a left hand, you need to be able to wear a hoodie over both arms, and a pair of work gloves only on your right hand.
- Bionic limbs need to ignore temperature, pain, wetness, filthy gear, have innate armor, and not be traditionally healable or mendable. Most of these should already be possible iirc.
- Bionic limbs need to be installed in pairs (such as replacing a leg also replacing the foot so you need to change two limbs at once)
- Limbs need to affect your base body weight and change your healthy stored kcal. For example if you had both legs and both arms replaced with bionics your healthy stored kcal would need to be halved (and presumably your current stored kcal would also be halved as part of the installation process) and your weight derived from BMI would need to be half as much for muscle and base body weight (so if you were 2 meters tall normally and had 12 strength, instead of 24 * 2^2 you'd have 0.5 * 24 * 2^2 to get your total body weight derived from non-fat sources. A function would need to be done to tally the total bodymass percentage from each of your limbs and adjust calculations accordingly.

**Comment by GuardianDll** [comment]
> Limbs need to be able to give bionic slots of the type...

Could be solved by copying `bionic_slot_bonuses` from mutations
```json
"bionic_slot_bonuses": { "torso": 20 },```

**Comment by anoobindisguise** [comment]
Technically for bionics it also works to give a limb negative bionic slots on a limb, janky but it works. I think that would probably allow installation if you had 0 of those slots and then give you say, 20 of them for use by other bionics (assuming you have 0 slots for a limb if you don't have that limb anymore)

**Comment by estebandellasilva** [comment]
> Bionic limbs need to be installed in pairs (such as replacing a leg also replacing the foot so you need to change two limbs at once)
Why?

> If a limb is bionic, it needs to drain bionic energy in place of calories/stamina and (not) set activity level accordingly. This could be done by moving stamina drain into a boolean function in character.cpp that finds limbs and then either tries to drain stamina or bionic energy depending on what's appropriate (dodging and walking/running would use the legs, while attacking/throwing would use arms, and swimming would use both) then the relevant function could short circuit if the stamina/energy check doesn't have enough of its resource. If the player has only one bionic limb, and one human limb, then the usage needs to be half and half, and presumably would allow the player to keep doing those actions without bionic power but with half the total limb score.

then should limb also provide additional batter capacity which helps you excced the current 2000kj limit? because if you have 4 bionic limbs this can get ugly very fast
Also about how much energy are we talking?

**Comment by anoobindisguise** [comment]
> then should limb also provide additional battery capacity which helps you excced the current 2000kj limit? because if you have 4 bionic limbs this can get ugly very fast Also about how much energy are we talking?

Well how many kcal does it take a human to walk 10 feet? And then 1 kcal has 4.1 kJ of energy, and the human uses their energy at something like 30% efficiency. So if it takes about 25 steps to burn one kcal, you're looking at about 160-200 joules per step if the bionic body has a similar efficiency of a human body. Or a hypothetical maximum efficiency of like 50 J per step. Maybe you install wheels for legs which are more efficient and faster, but suck at traversing obstacles.
