### ISSUE TITLE
Smashing a car panel crashes the game

### ISSUE THREAD

**Issue by die-rod-go** [CleverRaven/Cataclysm-DDA#66185]
### Describe the bug

The game crashes when attempting to smash parts of a car.

### Attach save file

[Denning-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11740718/Denning-trimmed.tar.gz)

### Steps to reproduce

Head upstairs and leave the shelter through the left side doors and head to the car immediately visible in the south west. Smash the rear right body panel (not the solar panel). 

If this is the car then that's what you need to smash
```
. . . .
. . . .
. . . .
. . . .
. . . .
. . .#.
```

after smashing enough times the game will crash

### Expected behavior

I expect to get materials and for the game to not crash

### Versions and configuration

OS - Windows 10
Game Version - e806e37 (tiles)
English
No Mods

### Additional context

 DEBUG    : no display part at mount (-3, 1)

 FUNCTION : vpart_display vehicle::get_display_of_tile(const point&, bool, bool, bool, bool) const
 FILE     : src/vehicle_display.cpp
 LINE     : 64
 VERSION  : e806e37

**Comment by RenechCDDA** [comment]
Not a crash, but confirmed.
