### ISSUE TITLE
Make mesh colanders craftable.

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66198]
### Is your feature request related to a problem? Please describe.

The recipes for fresh gelatin and mozzarella cheese require a mesh colander, which is infuriatingly rare to find in kitchens and cannot be crafted.

### Solution you would like.

Since a mesh colander is pretty much a bowl-shaped fine mesh, it shouldn't be too hard to craft one. It currently disassembles into a sieve, so that OR a steel mesh should be one of the components. The other components could be 

### Describe alternatives you have considered.

Several other recipes that use the mesh colander allow for the use of the cotton patch, sieve or wicker sieve as a tool, so one could make the fresh gelatin and mozzarella cheese recipe use the same and remove the exclusivity of the mesh colander.

The mesh colander could have its spawn rate greatly increased, as it is a very simple/common kitchen tool, notably used for straining noodles and washing fruits/vegetables, and other tasks that require a sieve-like bowl.

**Comment by martosss** [comment]
I agree... I started making a coffee machine and chose a mash colander as a part, since I had one ... grave mistake, I messed while crafting and now I don't have another spare mesh colander to finish the recipe!
