### ISSUE TITLE
[Magiclysm] High-end armor needs to have it's crafting time rebalanced

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#66199]
### Is your feature request related to a problem? Please describe.

It's completely insane that I have to wait over a week to craft stuff, it's just 20 minutes of just skipping time and browsing the internet, there is the fun gameplay in that?

### Solution you would like.

Reduce crafting time considerably to like: a day. The high end armor is already very hard to obtain, no need to add additional CBT with crafing time.

**Comment by Jan-Blasiak** [comment]
I also might add that other Magiclysm crafting times are similarly CBT. I've been crafting for an IRL hour already, just walking between bed and a crafting table.

**Comment by estebandellasilva** [comment]
which armor ? Because just shouting crafting time to long ... is meaningless if you dont show which ones are the problem

**Comment by Jan-Blasiak** [comment]
Sorry it took so long:

![obraz](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/6cbedc5c-7aba-44aa-980c-fbbe06188a11)

![obraz](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/d13c27d6-cbc5-46a3-a50b-051199d72694)

![obraz](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/e0847514-9bcf-4416-b327-58449ca2f331)

![obraz](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/1f9f047f-f6e6-4f62-a3ac-723eda538367)
