### ISSUE TITLE
Raw snail not made of flesh

### ISSUE THREAD

**Issue by 6DollarSuit** [CleverRaven/Cataclysm-DDA#66190]
### Describe the bug

The snails foraged are not considered flesh until they are crafted into purged gastropods. While they're raw, meat intolerance doesn't apply.

### Attach save file

N/A

### Steps to reproduce

1. Make a character with meat intolerance
2. Forage until you find snails
3. Observe that there is no allergy warning until after you craft it into purged gastropod

### Expected behavior

I expected raw snails to be made of flesh, since they are an animal.

### Screenshots

![temp](https://github.com/CleverRaven/Cataclysm-DDA/assets/36578094/f90cf729-3516-46a9-9dc9-f03cac4f6dce)
![capture](https://github.com/CleverRaven/Cataclysm-DDA/assets/36578094/8baf3887-3df2-479a-b48c-926810f67fe0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 24cc123 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Translate Complex Dialogue [translate_dialogue],
    Generic Guns [generic_guns],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Monsters [No_Fungi],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
It has no material at all. Simple fix.

**Comment by fyhannes** [comment]
Issue has been solved by merged PR #66569 and can be closed.

**Comment by RenechCDDA** [comment]
Indeed it has.
