### ISSUE TITLE
Make scalpels easier to obtain or craftable

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66201]
### Is your feature request related to a problem? Please describe.

It's currently very difficult to obtain a scalpel, the best (not counting CBMs) tool for dissection. The only guaranteed places to find them are from a Mad Scientist (who only spawns in specific areas like labs, rarely), or a Hospital (which is a very dangerous, zombie-filled area). All other spawn points (both enemy and location) have it as a very rare drop. 

Annoyingly, you're also unable to craft a scalpel, even though you're able to craft many other metallic blades of similar size and cutting edge.

### Solution you would like.

Create a recipe that allows a player to craft a scalpel (or a 'makeshift scalpel', which is bigger/bulkier/worse as a weapon but has the same fine cutting quality as a proper scalpel). 

It may require some medical books to obtain the recipe (purely so you know what it looks like) or could be auto-learned at higher levels of the health care skill (since the PC constantly references 'wanting a scalpel' when dissecting without one, they must know what it is).

To craft it, it could use the same kind of material/tools/skills/proficiencies you'd use to make a survival knife, folding knife or diving knife.

### Describe alternatives you have considered.

Adding the scalpels fine cutting quality to other blades. 

Increasing the spawn rate of the Scalpel (guaranteed in doctor's office, moderate chance from doctor/nurse NPCs or locations medical care was provided/expected).

Make mad scientists less rare, or add a 'surgeon' type zombie who would carry such surgical equipment regularly.

**Comment by RenechCDDA** [comment]
I don't see how a survivor is going to fabricate something equal to a medical scalpel. Their placement is intentional, too. They're found in places you'd actually find scalpels (NOT doctor's offices which have no use for them).

**Comment by Zarhon** [comment]
> I don't see how a survivor is going to fabricate something equal to a medical scalpel. Their placement is intentional, too. They're found in places you'd actually find scalpels (NOT doctor's offices which have no use for them).

What about the autodocs outside of hospitals (lab, prison), or the nurse bots? Those don't have any scalpels spawning either (they do spawn anesthetic kits though) and are outright meant for surgery. You can't get them from disassembling/smashing the autodoc/nurse bot either (a scalpel would have to be on one of the 'arms' for them to work), and it's highly unlikely there wouldn't be surgical tools anyway for doctors assisting/monitoring the surgery (e.g. if something goes wrong, a doctor would have to intervene immediately with their own tools).

**Comment by randomtyper** [comment]
> Adding the scalpels fine cutting quality to other blades.

X-Acto knife is already there. Found in (almost) every house, 2 fine cutting quality. Does its job really well for beginning. Dunno how you didn't stumble on one.
