### ISSUE TITLE
Rename the replica/display versions of weapons and armor to differ them from 'genuine' weapons and armor.

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66200]
### Is your feature request related to a problem? Please describe.

Almost every 'replica' version of a weapon or armor (usually made from budget steel or aluminum) has an identical name to the non-replica versions of the item. For example, 'rapier' is the name for both the aluminum (replica) version and the steel (crafted/proper weapon) version. In a pile of items or from its tileset appearance, you cannot tell which is which until you inspect its description/material. 

This can also cause some confusion/disappointment for newer players who are not aware that the medieval weapon/armor they picked up from a Fancy Feral/Mausketeer or found in a museum is not the legitimate article.

### Solution you would like.

Have the name of any 'replica' version of an item that shares a name with its non-replica version be changed. For example, the aluminum rapier could be renamed to 'replica rapier' or 'display rapier'.

### Describe alternatives you have considered.

Renaming the non-replica/crafted versions of the weapons something else. Changing the tileset for replica versions of the items to be different from the 'real' ones.

**Comment by Zireael07** [comment]
I believe this is by design?

**Comment by Broken27** [comment]
> I believe this is by design?

It's bad design.

It's a gotcha to new players than don't know about the replica versions, and it doesn't make any sense in world, where the replica versions should be obviously different from a real weapon.
