### ISSUE TITLE
Faction camp expansion construction result in harmless(?) error messages

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#66215]
### Describe the bug

The following error message is produced when trying to build a log chicken coop in livestock expansion 1: 
DEBUG    : invalid overmap terrain id "faction_base_modular_livestock_coop_log_northeast"

 FUNCTION : convert
 FILE     : C:\Cataclysm-DDA\src\generic_factory.h
 LINE     : 479
 VERSION  : 0.G-2341-g4cd1bf1a1d

A similar message is produced when trying to build a concrete coop in livestock expansion 2 during work to use parameterized palettes, complaining about the new name of the expansion.

Edit:
The same thing happens when expanding a faction base, complete with the replacement of the overmap description with "% nothing":
 DEBUG    : invalid overmap terrain id "faction_base_modular_hub_room1_log_northeast"

 FUNCTION : convert
 FILE     : C:\Cataclysm-DDA\src\generic_factory.h
 LINE     : 479
 VERSION  : 0.G-2341-g4cd1bf1a1d

### Attach save file

N/A

### Steps to reproduce

1. Create a livestock 1 basecamp expansion.
2. Build a (log) chicken coop.
3. Get the error message.
4. See that the expansion name on the overmap has changed from the name given when the expansion was created to "% nothing".

### Expected behavior

Construction of buildings on an expansion should not result in the replacement of the expansion type on the overmap.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 0.G-2341-g4cd1bf1a1d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I'm modifying livestock expansion version 2 (JSON files only) and saw the error message and the destroyed overmap description and then went on to test with the corresponding construction of the unmodified livestock expansion 1 and observed the same issue. Thus, I don't think the error is related to my work.

I assume any companion recipe construction work (as opposed to zone construction, which probably isn't affected, although I wouldn't bet on that either) in any base camp and expansion to be subject to this.

**Comment by SurFlurer** [comment]
Probably due to my #66070. I'll try to fix it.
