### ISSUE TITLE
Move Aftershock titanis/terror bird to Megafauna

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#66226]
### Is your feature request related to a problem? Please describe.

So, I used both Aftershock and Megafauna in one of my runs. I met a terror bird, and thought it was a Megafauna beast. Some time later, I was surprised to learn it was an Aftershock beastie. An animal that existed in RL and should have been in Megafauna somehow was in the same file as various alien and non-real creatures (it was in aliens.json).

### Solution you would like.

A Megafauna version of titanis.
Addition of child terror birds/titani.
Rebalance the stats:

- all, or at least most phorusrhacidae should have GOODHEARING flag, based on the article that was based on a study of a well-preserved phorusrhacidae skeleton: https://spectrum.ieee.org/terror-birds-hunted-by-sound
- Weight rebalance - t. walleri is estimated at 150 kg while Aftershock one tops out at 120 kg
- Other changes, like aggression adjustments?

More terror birds?
Tameable titanis? They were likely smart enough to be tameable.

### Describe alternatives you have considered.
Moving titanis to where it belongs - Megafauna mod instead of making a new version.
None.

### Additional context

Some info on titanis walleri and its fossils:

https://www.researchgate.net/publication/249521166_Revised_age_of_the_late_Neogene_terror_bird_Titanis_in_North_America_during_the_Great_American_Interchange
https://www.floridamuseum.ufl.edu/florida-vertebrate-fossils/species/titanis-walleri/
https://en.wikipedia.org/wiki/Titanis

Some info that will be likely used for new titanis version (current terror bird already can grab, though):

http://antediluviansalad.blogspot.com/2015/09/terror-birds-cometh-new-theory.html?m=1

**Comment by randomtyper** [comment]
@merrygin, do you mind another contributor to your mod?

**Comment by Drew4484** [comment]
This was specifically added to Aftershock, you could certainly copy it but please don't remove it in the process.

**Comment by randomtyper** [comment]
> This was specifically added to Aftershock, you could certainly copy it but please don't remove it in the process.

Okay, copy and rework as a separate creature it is then. Still a bit weirded out by the presence of titanis in AFS, though.

**Comment by Maleclypse** [comment]
closed by #66244
