### ISSUE TITLE
microlab_sub_connector incorrect on z-4

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66220]
### Is your feature request related to a problem? Please describe.

The [hardcoded](https://github.com/CleverRaven/Cataclysm-DDA/blob/4cd1bf1a1d757ac28139688e974f0e5dba473a56/src/overmap.cpp#LL3481C13-L3481C13) microlab_sub_connector used to connect various labs to subways places the wrong kind of subway for z-4 connections, "subway_\*" instead of "lab_subway_\*" including microlabs, void spider nest and the TCL

### Solution you would like.

microlab_sub_connector to get replaced dynamically with the appropriate "lab_subway" instead if on z-4 or the connections to be unhardcoded

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/f4af6274-1dcc-4383-9962-24ebe9d3a2ca)
Screenshot showing incorrect subway

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/2ba33ec2-59e6-476f-9e31-dd909cf91445)
Screenshot showing correct subway adjacent

**Comment by Venera3** [comment]
The actual solution is to do away with the hardcoded subway generation entirely and use the partly-JSON connection system. That needs yeeting old labs, which is also something we should get around to sooner or later.

**Comment by Procyonae** [comment]
I appreciate that's a better solution but this specific issue isn't actually present on old labs or the old central lab so could be done with a relatively minor fix

**Comment by Procyonae** [comment]
I will add this is nothing todo with the old labs as such, the JSON connection stuff has no way to handle z level stuff this is the current workaround used for all labs, sewers use a duplicate for open sewers too, I'll probably fix this in a subway PR soon tho
