### ISSUE TITLE
Crash when activating worn telescopic umbrella

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#66227]
### Describe the bug

When activating telescopic umbrella that is worn instead of wielded, it crashes.

### Attach save file

N/A

### Steps to reproduce

1. get a telescopic umbrella
2. (W)ear it
3. (a)ctivate it
4. crash

### Expected behavior

Not crashing

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 4cd1bf1 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Aftershock [aftershock],
    cable stuff [cablestuff]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11763331/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11763333/debug.log)

**Comment by Procyonae** [comment]
Personally I just get an ignorable error and it still activates and becomes wielded
```
 DEBUG    : item location does not point to valid item

 FUNCTION : void item_location::make_active()
 FILE     : src/item_location.cpp
 LINE     : 1027
 VERSION  : dd93a95
```
