### ISSUE TITLE
The vehicel mounted heaters and the cooler use like 20 times more energy than there description says they need!

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#66237]
### Describe the bug

While testing the vehicel mounted heater and cooler, i noticed that they use up way more energy than the description from them says. Even while seeing that iam producing more energy, than i should consume, i still lost energy and my battery drained.

### Attach save file

![Test1](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/dc3d7944-130d-47c6-acc1-01295ccaa85f)
![Test2](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/b01eff86-ef62-4206-9cdc-99c9b7c2f533)
![Test3](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/79f5ec32-d462-4922-b5aa-00da6641a33a)
![Test4](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/745de198-486c-410a-b611-e88b2d2ebd52)
![Test5](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/4208266c-7527-45e7-ac11-d86418c9f610)

### Steps to reproduce

1. Spawn a solar vehicel with at least 1000 energy production in debug mode
2. Install a vehicel mounted cooler or heater and turn it on and see if your energy consumption is still higher than your energy lose, and make sure your storage battery is full
3. Wait like 5 or 30 minutes and look at your storage battery and see that even though you produce more energy than you consume, you still drained your battery 

### Expected behavior

Your storage battery should remain at 100%, as long as you have an energy surplus.

### Versions and configuration
Windows 10
Build: 2023-06-16-0558
Version: d5cc239 (tiles)
Mods: Dark days ahead [dda],
Blaze Industries [blazeindustries],
Magiclysm [magiclysm],
Xedra Evolved [xedra_evolved],

**Comment by SurFlurer** [comment]
Can /confirm . I observed the same phenomenon.

**Comment by SurFlurer** [comment]
More precisely it's this part:
https://github.com/CleverRaven/Cataclysm-DDA/blob/6d6c3a255dcdd6340830815ad0a14503b06c78b9/src/vehicle.cpp#L7480-L7498

So `last_update` doesn't get updated every turn, but `interval` assumes this.
