### ISSUE TITLE
Windows Security detects .exe as Trojan

### ISSUE THREAD

**Issue by JoeIlluminati** [CleverRaven/Cataclysm-DDA#66242]
### Describe the bug

After playing for a couple days on an experimental build, Windows Security flagged the .exe as a Severe Threat and quarantines the file.
I tried to reproduce the issue by deleting the folder off my computer and unarchiving the download I had in my Downloads folder, but after doing so it is immediately flagged and quarantined.

I recognize this could be difficult to reproduce, but I figured it wouldn't hurt to raise this up in case others are experiencing a similar problem.

### Attach save file

N/A

### Steps to reproduce

Can't confirm this reproduction will work as Windows Security seems to have cached the files fingerprint or something similar, but this is what I initially did before encountering the issue.

1. Download and unarchive the tiles non-msvc archive of the version 3f9a827fa99838594ad044ca6a8869bfd190dc1d
2. Create a new world, played 2 characters that died rather quickly and unlocked some achievements
3. After 2nd character dies, delete world and close game
4. Open game
5. After about 10 seconds of loading, game crashes and Windows Security alert pops up notifying a threat was blocked and quarantined.

### Expected behavior

I expect that the game would not be flagged as a trojan :)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6212038/9068a840-14a7-4b43-85cc-3503a378222d)

### Versions and configuration

- OS: Windows 10 Home Version 10.0.19045 Build 19045
- Game Version: 3f9a827fa99838594ad044ca6a8869bfd190dc1d
- Graphics version: Tiles w/ sound
- Ingame language: en
- Mods Loaded:

**Comment by Dude385** [comment]
I had this issue earlier today as well. However mine triggered a couple hours into a session in a world I had started a couple weeks ago. I was also running experimental but I hadn't updated my game since the 7th of this month. I'm on Windows 10.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/136861947/2ca3bea9-49e2-44b2-befb-7e747d34a821)
Hoping someone can let me know if this is a real issue.

**Comment by SurFlurer** [comment]
If you believe this is a real threat to your cyber security, it's always possible to audit the code (all open source!) and compile the executable using Visual Studio or something. There's a set of comprehensive guide on compiling the game .

**Comment by Qrox** [comment]
@SurFlurer This is very likely a false alert, but there's also the theoretical possibility that the build matrix is compromised and the build artifact is injected with content not in the code, so what I recommend is to use some online AV service to analyze the file and see if most AVs report it as clean.

**Comment by andrei8l** [comment]
VirusTotal says the builds are clean so this is yet another false report

[msvc build](https://www.virustotal.com/gui/url/9b7e02771b6fd4f3938afaf7b6cf6001c4f7c8534e221ead2d8cd9af3bd15182)
[mingw build](https://www.virustotal.com/gui/url/a1b6909014bb375b3471b1f870602b3b93757e2fc9ed66c31fd4094aa6bd86dd)

There are still several bad memory accesses that can be seen in builds with ASan and/or `-D_GLIBCXX_ASSERTIONS` and my guess is that the antivirus misidentifies one of these as malicious action.

**Comment by ZhilkinSerg** [comment]
False positive just as always.

**Comment by NetSysFire** [comment]
I think the way to go here is to actually report this as a false positive to the windows defender folks, but I have unfortunately not much experience with that.
This is more or less basically an upstream windows defender issue.
