### ISSUE TITLE
Potential changes to the Prison and Nursing Home labs

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66249]
### Is your feature request related to a problem? Please describe.

Nursing home lab unlore friendly
Prison lab sad
Me change them

### Solution you would like.

Just outlining some plans to open them for discussion, very open to changes
Currently plans:
Remove mutagen, mutagen related items and mutants from the nursing home lab. Replace them with general medical supplies and narcotics.

The prison lab is a bare bone sad looking thing that goes into an old style lab
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/e349ba87-27f6-429e-9de7-c88391b5a33f)
So I'm considering removing it and replacing it with a z-4 subway entrance with subway trains that have containment units to transport the prisoners to actual labs to provide a partial explanation for where all the labs are getting test subjects from that occurs at a more frequent rate than the current lab, while also providing a unique way to get to the z-4 subways. A lab specifically under the prison does make sense to me as it's state property (nearly all US prisons appear to be state owned) but this seems both more interesting and lore friendly as per fairyarmadillo's comment regarding labs under buildings.

**Comment by fairyarmadillo** [comment]
I think it is great that we have XEDRA disappearing people from these locations, but it doesn't make a lot of sense to put the facility directly underneath them. It'd be way easier for them to secretly kidnap and transport test subjects to remote locations than it would to hide security staff and screaming mutants ten feet under a vibrant community.

**Comment by Ruminator24** [comment]
It is a little hard to hide the fact that people disappear in a nursing home, except if they have no family.

**Comment by sadenar** [comment]
A good alternative to the nursing home would be hopitals, with triage being done on people that won't be missed but won't croak during transport, also would allow some cool mixed backgrounds of "Sure the scientists turned me into a mutant abomination, but that's probably better than dying in an hospital bed... maybe"

**Comment by fairyarmadillo** [comment]
There are plenty of people in nursing homes who aren't in constant contact with their family. It wouldn't be that hard for the military industrial complex to disappear a person who was near the end of their life and then send the family (if they even care) fake ashes. It's a thing that actually happens IRL on accident often enough.

The main issue is that having a mutagen lab directly under a populated area makes absolutely zero sense. Even as cavalier as they were, XEDRA knew this stuff was incredibly dangerous and took the utmost precautions to make sure they didn't contaminate anywhere with it. The only reason the blob got out is that they didn't understand that it wasn't a microorganism in a sense that they understood.

A good alternative would be the ability to discover a disappearing person conspiracy in locations with vulnerable people (hospitals, prisons, nursing homes, homeless shelters) that you could trace back to a lab in a remote area. Even just snippets/notes/lore bits would be good.

**Comment by pshepjr** [comment]
Hi, as the creator of the nursing home lab, there are some pretty big key points that I think are being missed. Of course, if it is ultimately decided still that it should be removed, I won't argue:

* The lab is not intended to be involved with XEDRA in any way - the Shady Hills corporation is a standalone entity
* Shady Hills was trying to make an "immortality" serum. They were "borrowing" elderly people from their nursing home(s) for this purpose. The elderly were not always "permanently disappeared", they were brought to the lab for studying and then returned in most cases.
* There is lore to be found in the computers of the nursing home that show this to be a rather big conspiracy. Further, there is evidence that Shady Hills was NOT necessarily competent in what they were doing. They were buried in multitudes of lawsuits and potentially struggling as a result. The end of the world simply happened before they were exposed on a greater scale.
* The emails found in the computers also indicate that the nursing home prices were very cheap - implying they were preying on poor elderly people with no financial ability to hire a legal defense.

TL;DR - Shady Hills experimented on poor people in attempt to extend human life. They were not necessarily competent in their practices and were in serious legal trouble.

If it is determined the lab should be removed, I would recommend simply deleting the Shady Hills variant of the nursing home. Or else you will need to comb through the lore entries on the computers, too (or I guess just disable those).

**Comment by Procyonae** [comment]
> Hi, as the creator of the nursing home lab, there are some pretty big key points that I think are being missed.

So I'll be real it's been a while since I read all the computer messages and I hadn't looked at your PRs making the map nor several attacking it since, originally I were just thinking of attacking the prison lab to keep some flavour there before someone yeets it entirely for it being the old lab type and peeps brought up the nursing home lab so I figured I might as well alter both. I've now reread some of the messages and looked through all the PRs that show up when you search nursing home.

First off I don't have any interest in getting rid of the lab anymore, the fact that it's nothing to do with XEDRA as well as the large amount of written dialogue that's more than I remember makes it both unique and interesting. I appreciate the work you put into this and to then have multiple peeps come in and outright obsolete various parts of it must suck already >_>

That said I will say the mutants (that you didn't even put there) and all the random mutagen types don't make much sense to me, if you could provide an explanation as to how the Shady Hills corporation got their hands on not only mutagen but the recipes for it that'd be great, like from what I've seen it would make more sense for them to be using medical/alpha mutagen over the random assortment that currently spawns.

Sorry for coming at this without even bothering to check any of the maps history first and apologies in advance if I missed an explanation for the mutagen stuff in game or in the various PRs. Thanks again for making a cool map ^-^

**Comment by fairyarmadillo** [comment]
Mutagens are a XEDRA only thing, developed by specific named doctors and tightly controlled by the government. Alpha and medical in particular are some of the more complex and experimental ones and absolutely should not exist outside of XEDRA facilities.

**Comment by pshepjr** [comment]
Thank you for the kind words, Procyonae. Based on what fairyarmadillo said it would indeed seem the mutagens don't make sense to be there. And as you mentioned i didn't put the mutant enemies originally but they probably shouldn't be there either. 

The lab would still make sense if the mutants and mutagens were removed. As was mentioned, a large amount of medical supplies would make more sense. Could probably also add narcotics (cocaine is mentioned as something they were trying with). 

I don't have any intentions of working on this in the near future however, but if someone wishes to make such a change I certainly wouldn't argue.

**Comment by Procyonae** [comment]
I'm happy to make the changes at some point reasonably soon unless someone else gets to it first, I'll make sure to mention you on the PR if I do
