### ISSUE TITLE
multi-stage rubble piles, and rubble generation

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#66269]
### Is your feature request related to a problem? Please describe.

demolish a whole 5 lvl office tower and there is barley any rubble created
rubble spawned in the air and lands on rubble on the ground deletes the falling one
most other furniture when falling on rubble destroys it(not going to change just pointing out it contributes to less rubble)
rubble has no verticality to it, is it a light covering on the ground or a full pile you cant see over?
dumpsites only cover being fridges washers and cars that spawn

### Solution you would like.

already testing the multi-stage tiles and mapgen, seems promising, dumpsites seem more interesting
need help with
- _bash transforming full f_rubble into lower stage f_rubble_ (<done) and spawning the extra as f_rubble in an adjacent tile (ideally in the opposite direction of the bash, meaning you could use this to knock over a pile on top of an enemy on the other side)
- updating f_rubble stages when other rubble mite land on them transforming it into the next stage up
- if f_rubble cant transform into the next stage up (rubble of different types) skip over to another adjacent tile until it can spawn new f_rubble or update another pile
- damage mechanics for rubble falling on player and creatures (where is the code for that so i can look at it)
- furniture sealed container (when clearing f_rubble stage the items hidden underneath get kicked out to an empty space, if you are standing on f_rubble when clearing it throws up an error, i want the items already hidden underneath to be put in the new stage, _bashing causes the spawned items to be dropped in the new stage_)
- ~~suggestions for names and descriptions of tiles, not going to leave it as 1/4 2/4 3/4 full~~ _using pile<mound<heap<mountain adjectives_
- suggestions for buildings and methods that consistently cause rubble to spawn for testing on (big bomb on big building spawns no rubble)(some older mapgens use tiles on higher zlvls that turn into t_dirt when destroyed)
- ~~suggestions on how/where to find mutable dumpsites (when i debug spawn them they dont look right)~~ _overmap spawns need to be done in an unloaded area_
- ~~using item_group as a byproduct~~ ~~suggestions for item_groups to use for the different rubble piles (will likely make new custom ones)~~ _made custom item_groups_ and will need to do a lot of balancing, `trash` aim is to be "not worth doing" only worth it for the desperate, `building/rock/wreckage` aim is to be "almost worth doing" with rare useful finds, `landfill` aim is to be "only just worth doing" with moral penalties because of the smell, `landfill` will have everything from `building/rock/wreckage` and mostly `trash` but most of the useless stuff is rotted away leaving only the less useless stuff to find
- examples of item_groups being used and defined in code (rubble has some hardcoded item drops id like to swap out for item_group so it can be edited in json)
- `f_rubble_landfill` to leave behind a `t_pit_shallow` when fully cleared out (~~could do this by converting it from `furniture` to `terrain`~~ _this works and still functions like it did before_ but now the NPCs and auto activity dont work `There is something blocking the location for this task.`)
```
    "type": "construction",
    "id": "constr_clear_rubble_landfill",
    "group": "clear_rubble",
    "category": "OTHER",
    "qualities": [ [ { "id": "DIG", "level": 2 } ] ],
    "required_skills": [ [ "survival", 0 ] ],
    "time": "3 m",
    "byproducts": [
      { "group": "rubble_landfill", "count": [ 2, 5 ] }
    ],
    "pre_terrain": "t_rubble_landfill",
    "post_terrain": "t_pit_shallow",
    "activity_level": "EXTRA_EXERCISE"
```
it works for construction, iuse, iexamine, but not zone action (maybe AI pathing related)
```
    "type": "terrain",
    "id": "t_rubble_landfill",
    "name": "recess of covered landfill",
    "description": "Trash topped with dirt and grass, you could dig it up but is the smell it's hiding worth the treasure…",
    "symbol": "#",
    "color": "green",
    "move_cost": 6,
    "max_volume": "750 L",
    "flags": [
      "TRANSPARENT",
      "UNSTABLE",
      "ROUGH",
      "PLACE_ITEM",
      "MOUNTABLE",
      "CONTAINER",
      "SEALED",
      "ALLOW_FIELD_EFFECT"
    ],
    "bash": {
      "sound": "thump",
      "ter_set": "t_null",
      "str_min": 40,
      "str_max": 100,
      "str_min_supported": 100,
      "bash_below": true
  },
    "examine_action": "rubble"
```
### Describe alternatives you have considered.

updating stages should be doable but if the spawning of extra f_rubble in an adjacent tile is not or too much trouble, will have the extra be converted into item drops, at a reduced amount

### Additional context

#61677
```
"furniture": {
      "#": [ [ "f_rubble", 3 ], [ "f_rubble_landfill", 3 ], "f_rubble_rock", [ "f_wreckage", 2 ], [ "f_rubble_2", 2 ], [ "f_rubble_3", 1 ], [ "f_rubble_4", 1 ], [ "f_rubble_landfill_2", 2 ], [ "f_rubble_landfill_3", 1 ], [ "f_rubble_landfill_4", 1 ], [ "f_wreckage_2", 2 ], [ "f_wreckage_3", 1 ], [ "f_wreckage_4", 1 ] ],
      "z": [ [ "f_rubble", 3 ], [ "f_rubble_landfill", 3 ], "f_rubble_rock", [ "f_wreckage", 2 ], [ "f_rubble_2", 2 ], [ "f_rubble_3", 1 ], [ "f_rubble_landfill_2", 2 ], [ "f_rubble_landfill_3", 1 ], [ "f_wreckage_2", 2 ], [ "f_wreckage_3", 1 ], [ "f_null", 4 ] ],
      ".": [ [ "f_rubble", 3 ], [ "f_rubble_landfill", 3 ], "f_rubble_rock", [ "f_wreckage", 2 ], [ "f_rubble_2", 1 ], [ "f_rubble_landfill_2", 1 ], [ "f_wreckage_2", 1 ], [ "f_null", 12 ] ]
```
![rubblestages](https://github.com/CleverRaven/Cataclysm-DDA/assets/115079701/7110fcb7-cf43-42fe-b261-97104f7458ea)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/115079701/9f8e887f-b183-4254-ae8b-6b6f656461e8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/115079701/e6a1ae3b-8b40-472b-9978-6caebd848fc1)
full f_rubble spawned at zlvl 2 and f_rubble 1/4 spawned at zlvl 4, result at zlvl 1
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/115079701/9d42a730-512f-4874-9a75-c4b2bbee2d17)

**Comment by Procyonae** [comment]
> suggestions for buildings and methods that consistently cause rubble to spawn for testing on (big bomb on big building spawns no rubble)(some older mapgens use tiles on higher zlvls that turn into t_dirt when destroyed)

You can use this to spawn rubble https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAPGEN.md#place-rubble-and-smash-existing-terrain-with-rubble
Equally if you manage the directional rubble on bashing make sure you have a fallback in case of stuff like this

**Comment by Procyonae** [comment]
> ~~suggestions on how/where to find mutable dumpsites (when i debug spawn them they dont look right)~~ overmap spawns need to be done in an unloaded area

If you don't need the whole mutable you can spawn the individual OMs even right on top of yourself with Debug ->  (m)ap -> (M)ap Editor -> (o)vermap -> Search with / for dumpsite -> Regenerate to your hearts content and Apply to replace the OM

**Comment by flybye3o6** [comment]
> Equally if you manage the directional rubble on bashing make sure you have a fallback in case of stuff like this

interesting, i was seeing this happen but wasnt sure, it was only happening with natural spawns and not debug map spawns, ill keep the terrain override in mind though im sure it wont be a problem in dumpsites, it mite when i start testing multi-lvl building demolition

**Comment by Procyonae** [comment]
It would be really nice if eventually you could take a normal map and just apply bash randomly to the bottom to create a randomised destroyed variant for things like the desolate/abandoned buildings rather than them being their own maps

**Comment by Procyonae** [comment]
How're you doing with this? ^^

**Comment by flybye3o6** [comment]
this is going to be a long project for me, im still learning to code and i dont have alot of time to work on it
tiles, construction, map gen, item groups, and iexamine are done, if nothing else i can put that out
had to scrap the code i was working on and start again

**Comment by Procyonae** [comment]
Feel free to come round the devcord and open a draft PR so peeps can help if you get stuck ^_^
