### ISSUE TITLE
Bug? No, its a feature

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#66275]
### Is your feature request related to a problem? Please describe.

There was a bug, which was fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/66055
But as for me - its very useful feature. By this fuction you can find rocks, plant (like burdock), boxes, items and creatures in woods without spamming "V"iew menu. Without this feature by default sprites of trees and lots of structures because of 2d graphic just laying at other sprites. You cant find by "V" big furniture like rock and farmable plants

### Solution you would like.

Like in most games, there is function to highlight items by pressing a button. So make this bug as a toggleable function by a key

### Describe alternatives you have considered.

Leave all as it is and make it harder to find items and creatures in woods and other terrarion

**Comment by Qrox** [comment]
It may give a misleading illusion of height though. Maybe it will be better to give some transparency to the sprite instead when toggled.
