### ISSUE TITLE
Constant level of brightness on levels 1 and higher and -1 and lower. Allowing to read despite lack of apparent source of light.

### ISSUE THREAD

**Issue by SerN95th** [CleverRaven/Cataclysm-DDA#66279]
### Describe the bug

Constant level of brightness on levels higher or lower than 0 regardless if there is no source of light. This allows the player to read books on higher and lower levels. On the other hand, crafting doesn't seem to be affected. Possibly Related to #65997.

### Attach save file

[Jessup-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11781207/Jessup-trimmed.tar.gz)

### Steps to reproduce

1. Go down or up to a Level other than 0.
2. Read a book.

### Expected behavior

1. Going down into lower and higher levels should not give constant level of brightness unless there is a source of light. 

2. Expected to be prompted as being too dark to read

### Screenshots

LEVEL -1 (EVAC Shelter Basement)

![Denis Barker _2023-06-18T17-59-07](https://github.com/CleverRaven/Cataclysm-DDA/assets/64409013/6890c1b0-7f97-494b-a709-33a2a7ba144c)

LEVEL 1 (2-story Motel Bathroom)

![Denis Barker _2023-06-18T18-03-13](https://github.com/CleverRaven/Cataclysm-DDA/assets/64409013/f2245d10-3cac-4ef4-b418-09119fc47f45)

LEVEL -4 (subway)

![Denis Barker _2023-06-18T18-12-16](https://github.com/CleverRaven/Cataclysm-DDA/assets/64409013/500e4b73-ccab-4dad-b387-33faba739898)

LEVEL -2 (Apartment Complex) 

![Denis Barker _2023-06-18T18-23-20](https://github.com/CleverRaven/Cataclysm-DDA/assets/64409013/7f18be7d-5933-4960-8582-0fee8cc6cc0e)

I tried crafting, and it seems to be working as expected; however, when I read a book, my player seems to be able to read it despite having no apparent source of light.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1848 (22H2)
- Game Version: 2af2001 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Moumix3** [comment]
Having the same issue in my newest game. Game version is 38bfec9

**Comment by rtxyd** [comment]
same problem still exist in newest version. brightness is abnormal if you are not in level 0. [](https://github.com/CleverRaven/Cataclysm-DDA/commit/471d75e552bd3a20684d8ef6d561f0e3427e1d4b)
