### ISSUE TITLE
Project has become unworkable after path changes

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#66273]
### Describe the bug

#65822 has unfortunately made the project unworkable for me (I'm using Windows 10, Visual Studio 2022). After updating my fork and building, the game said I had no saves available, even though there were plenty in `./save`. Looking in the directory, I saw that the game had created new folders named `.save`, `.config`, etc., and was trying to use those.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/208cec11-09b1-44d3-8183-aa7a5f56db2a)

After copying my saves into that folder they would show up, but fail to load with this error:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/0af37a25-abcc-4f3f-a3f1-edba86725747)

I'm able to start a new game just fine and load into the game, but after save-quitting and trying to load the save it just created, I get the same error.

I made a fresh clone of the newest upstream to see if that would fix it but that was even worse - the .exe couldn't even get to the title screen, just showing the error `Failed to write options to "./config/options.json": opening file failed`.

Noticing that #65822 affected the paths, I tested it by resetting my fork to that commit (a6233fc5fa01cda4ffa400670b426e1fae44f15e), and it failed. I then reset to right before that commit (ef1335a59be293eec1531f8002c7453ad9fd2423) and it worked fine.

### Attach save file

N/A

### Steps to reproduce

1. Clone current repository.
2. Build
3. Run and it'll create `.save`/`.config` directories it shouldn't be using.

### Expected behavior

For the paths to not get mucked up.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: a36cd132e5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

The user **Love** has said on Discord that Android builds fine, so this might be Windows-specific.

**Comment by rselias** [comment]
Same issue. Also on Windows.

**Comment by SurFlurer** [comment]
Same issue. Me on Windows too.

**Comment by Alm999** [comment]
This is the same issue:
https://github.com/CleverRaven/Cataclysm-DDA/issues/66261

**Comment by PatrikLundell** [comment]
/confirmed

Windows (Visual Studio) as well.

It worked two days ago, but the code downloaded and compiled today does not find the saved games.
As noted in the report, .config, .save, .templates, and .font directories were created. These directories are empty.

**Comment by Procyonae** [comment]
Is anyone working on a fix for this bc if not temporarily reverting the PR would seem like a good idea

**Comment by alef** [comment]
> Is anyone working on a fix for this bc if not temporarily reverting the PR would seem like a good idea

Yes. The function [lexically_normal()](https://en.cppreference.com/w/cpp/filesystem/path/lexically_normal) transform `./` to `.`, that's why all those `.dir/` instead of `./dir/`.
Problem is some paths are still using string concatenation instead of `fs`' append operator.
Will fix that in https://github.com/alef/Cataclysm-DDA/tree/fix-66273 .
