### ISSUE TITLE
13 assassins in the span of 15 minutes.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#66283]
### Describe the bug

I wanted to travel to HUB-01 to pawn off some of my surplus stuff, I got ambushed by **13 asassins** in the span of 15 minutes.

### Attach save file

[Castle Valleyyy_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11781758/Castle.Valleyyy_2.zip)

### Steps to reproduce

Walk around near refugee ranch, HUB-01, on save load you'll load to a bunch of asassins who appeared from thin air.

### Expected behavior

Being ambushed from time to time,

Being able to see your assassins coming.

NOT having a bunch of killers pop up en masse out of thin air.

### Screenshots

![Zrzut ekranu (505)](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/1ff2099f-4dc1-4746-a9a5-d4e544ebd526)
![Zrzut ekranu (504)](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/b90f916b-8454-4b57-b196-1126f8926e33)
![Zrzut ekranu (503)](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/212be5f4-3ddb-41aa-829b-74257e2e53d7)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 9a4259f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by Jan-Blasiak** [comment]
Additionally, there is more and more of them after each spawn after I walked around the HUB-01

**Comment by Jan-Blasiak** [comment]
![Zrzut ekranu (507)](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/343b5c95-9455-413b-ae29-648dbfb9d323)

Now they literally spawned AROUND ME and BLASTED ME TO DEATH in the same turn

**Comment by Jan-Blasiak** [comment]
After I TPd away from them, took spawned panaceus and let them walk away...

They stopped spawning.

Just like that.

**Comment by Jan-Blasiak** [comment]
I let two groups walk away after spawning and afterwards I was free to walk to HUB-01 and do my business and walk away.

**Comment by Jan-Blasiak** [comment]
Can it have anything to do with the fact that for the previous two in-game weeks I've been crafting and mutating instead of walking around?

**Comment by anoobindisguise** [comment]
Um, are you allowed to just confirm your own issue?

**Comment by Jan-Blasiak** [comment]
Um, am I? I thought that people who have received the permissions to use this command were considered responsible enough not to abuse it.

If I misused it, then I'm sorry and I won't do it again.

**Comment by Maleclypse** [comment]
> Um, am I? I thought that people who have received the permissions to use this command were considered responsible enough not to abuse it.
> 
> If I misused it, then I'm sorry and I won't do it again.

It's preferred that you not confirm your own issue, however, you provided better video evidence than we have of bigfoot and it's my general policy that solid video evidence and/or cut pasted in game error messages are good enough to confirm things.  I'll load up your save tonight if I have a chance. :)

**Comment by Jan-Blasiak** [comment]
Just to clarify, the Assassins seemed to constantly respawn as long as I kept wiping out groups, when I stopped, TPd away al let them walk into the sunset they dried up in about two or three spawns and teleports.

They didn't seem to be able to home in on me when I gave them about 15 tiles of free space.

**Comment by Maleclypse** [comment]
Confirmed.  I turned on debug invulnerability and managed to get 20 assassins in less than five minutes by wandering around about 6 overmap tiles.   Wild

**Comment by Jan-Blasiak** [comment]
Update on the save.

I've determined that the "Asassins" are a Keter class SCP which does not originate on our world.

![Zrzut ekranu (508)](https://github.com/CleverRaven/Cataclysm-DDA/assets/61629226/7d9b8e3d-089d-4e2e-a994-875eb2c3dabc)

Additionally I've discovered that Asassins follow me even into the Labs.

**Comment by Jan-Blasiak** [comment]
[Castle Valley_2_the_sequel.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11858183/Castle.Valley_2_the_sequel.zip)

**Comment by Jan-Blasiak** [comment]
I've attached the save in the moment of the screenshot above

**Comment by Perset** [comment]
> Um, are you allowed to just confirm your own issue?

I lol'd hard

**Comment by MNG-cataclysm** [comment]
I tested this again with the release on 7/9/2023, with the new changes from #66703, and I couldn't reproduce it. I believe it's fixed.
