### ISSUE TITLE
Plugged in devices dont work for recipes that require charges

### ISSUE THREAD

**Issue by AzTheProtoGoat** [CleverRaven/Cataclysm-DDA#66286]
### Describe the bug

Recipes that require charge dont account if a device is plugged in via a vehicle

### Attach save file

not needed

### Steps to reproduce

1. Plug in a laptop computer into a car
2. Check a computer practice recipe

### Expected behavior

Recipe should be available

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/112546133/fddf9519-7ecd-4b0e-b931-dbd93685425f)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/112546133/cf56356a-1bdc-4691-b4b1-463b3e03b203)

### Versions and configuration

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/112546133/ad538884-8efc-415d-8987-709abbcc6f0c)

**Comment by Kamayana** [comment]
I'll work on fixing this
