### ISSUE TITLE
City size zero doesn't stop roads from spawning

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66307]
### Describe the bug

City size of zero is apparently supposed to prevent roads from spawning altogether but in game it does not do that.

### Attach save file

n/a

### Steps to reproduce

1. Create a world with city size of zero.
2. Observe the existence of roads.

### Expected behavior

Either roads should not spawn or the description should be updated to reflect roads not being disabled.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56016372/c1309eb3-57f8-474a-af27-fb71cad3a00e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: e6e9461 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/6060d00d3f28462d440a65b9907af198401ed9a9/data/core/game_balance.json#L298

**Comment by anoobindisguise** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/blob/6060d00d3f28462d440a65b9907af198401ed9a9/data/core/game_balance.json#L298

OK so, should the descriptor claiming that city size = 0 be corrected to indicate it doesn't stop roads spawning, or should overmap.cpp be special cased to check if the current world's road size is 0 OR the bool is flagged as false?
