### ISSUE TITLE
Crashed while moving items?

### ISSUE THREAD

**Issue by Ruminator24** [CleverRaven/Cataclysm-DDA#66301]
### Describe the bug

I somehow crashed moving stuff from my motorcycle to my pile.

### Attach save file

[lonley-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11783699/lonley-trimmed.tar.gz)

### Steps to reproduce

1. simply move stuff from the motorcycle to the pile.
2.  crash

### Expected behavior

I would expect not to crash

### Versions and configuration

- Windows 10
- 9168cb4
- Tiles
- English
- default

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11783710/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11783711/debug.log)

**Comment by RenechCDDA** [comment]
Duplicate of #65166
