### ISSUE TITLE
Void Spider boss fight should be moved to XEDRA Evolved

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66305]
### Is your feature request related to a problem? Please describe.

The new boss fight is pretty cool and I feel uncomfortable shitting on all the hard work done by Candlebury and Bombastic that made it happen but after playing through it a couple times I can't help but feel like it's just totally out of place for the rest of the game. It's a very "video gamey" fight with an enemy that spawns reward loot at the end, and that loot generally has quasi-magical properties such as the indestructible minecraft bedrock samurai armor.

### Solution you would like.

This whole fight feels a lot more on theme with XEDRA evolved which is a much more "sci-fi" take on the apocalypse with traditionally video-gamey elements.

**Comment by fairyarmadillo** [comment]
Agreed on all counts.

**Comment by andrei8l** [comment]
> t's a very "video gamey" fight with an enemy that spawns reward loot at the end

We don't need to avoid game mechanics just because they intersect video game tropes.

There are many plausible reasons for this void spider to have shiny loot. Maybe they collected it as part of nesting behavior, or to impress a mate, or maybe an unprepared adventurer/trader/ronin/broken exodii/whatever fell through a portal into the nest.

**Comment by John-Candlebury** [comment]
It spawns shiny loot on the dried out corpses of its previous victims. At the stage of the game where you are expected to fight them. you yourself would most likely drop shiny loot (cbms) if you happened to die in it. 

Wheter the loot that spawns in game currently is appropiate for the setting is a completely different matter from whether the fight itself should stay in the game.
