### ISSUE TITLE
Invalid recipe id bug on Dark Days of the Dead mod

### ISSUE THREAD

**Issue by rizkiv1** [CleverRaven/Cataclysm-DDA#66311]
### Describe the bug

Invalid recipe id on classic_zombies or Dark Days of the Dead mod.

### Attach save file

N/A

### Steps to reproduce

1. open craft menu

### Expected behavior

No error

### Versions and configuration

-    OS: Windows 8.1
-    Game Version: 2023-06-19-0542 | `8846e84` (tiles)
-    Tileset: default
-    Language: English
-    Mods:
      -  default
      -  Dark Days of the Dead mod
-    Launcher: Fris0uman/CDDA-Game-Launcher

### Additional context

```
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "light_minus_atomic_battery_cell"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "light_atomic_battery_cell"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "medium_atomic_battery_cell"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "heavy_atomic_battery_cell"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "rm121aux_mod"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "bot_rifleturret"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "bot_crows_m240"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "bot_dispatch_military"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "bot_science_bot"
ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp:67 [obj] invalid recipe id "bot_dispatch"
```

**Comment by rizkiv1** [comment]
[Marcola-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11787648/Marcola-trimmed.tar.gz)

**Comment by rizkiv1** [comment]
well, i can mitigate it with `i`gnore when error show up. Trying to redownload and run on different installation, still same.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11789755/debug.log)
[Coopertown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11789756/Coopertown-trimmed.tar.gz)

**Comment by RenechCDDA** [comment]
Still no reproduction over here. The only thing I can see that differs is that in your debug log your system locale is set to `English_United States.1252`, which is what windows 7 uses (I am running windows 10, and use `English_United States.utf8`). Windows 7 has had a number of bizarre locale errors with very strange symptoms.

I see you commented on #62767 which has the same symptoms(on linux no less?) but without reproduction or any obvious reason there's little that can be done.

**Comment by RenechCDDA** [comment]
The other interesting entry from your debug log is this:

```
(continued from above) ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp:333 [error_skipped_members] (json-error)
Json error: data/json/monsters/fish.json:863:17: Invalid or misplaced field name "copy-from" in JSON data

    "name": { "str_sp": "oversized crayfish" },
    "description": "A mutant crayfish the size of a dog, with a brown carapace, claws, and long antennae.",
    "copy-from":
                ^
                 "mon_giant_crayfish",
    "proportional": { "hp": 0.5, "speed": 1.1, "morale": 0.67, "melee_dice_sides": 0.67 },
    "volume": "30 L",
```

Complete nonsense, as that's not been touched and copy-from is a perfectly legitimate field. Yet the invalid recipe id errors all start after it. Could the "invalid recipes" be some weird flexbuffer caching issue? Sure! But if so, that just makes them a symptom of this original error, assuming it is the cause.

I would still stake it as a locale issue, but again: without reproduction or any obvious reason there's little that can be done.

**Comment by RenechCDDA** [comment]
**Important reproduction step: Open the crafting menu.**

Recipes are supposed to be checked on load, and you did not mention this so I did not think to do it. I re-used your save to test another bug and found it by accident.

**Comment by RenechCDDA** [comment]
Okay so this has nothing to do with locale! Those items are *blacklisted* by the mod's settings.

recipe_dictionary::finalize_internal is supposed to handle deleting the blacklisted recipes but doesn't seem to actually be doing so? I tried moving the blacklist to dda and it still errors out.

**Comment by RenechCDDA** [comment]
To put down some more info for anyone working on this in the future: The issue is that the nested recipes still exist inside of the nested_category_data of nested categories.

So the function needs something like the below. **This is an example to help anyone trying to fix it and does not actually work.** I tried to slice it a few ways but I'm not a C++ professional.

https://github.com/CleverRaven/Cataclysm-DDA/compare/master...RenechCDDA:Cataclysm-DDA:nested_blacklist

**Comment by ZhilkinSerg** [comment]
@RenechCDDA  Invalid and/or blacklisted recipe entries should be removed from `nested_category_data` when iterating through `obj` in the very top of `recipe_dictionary::finalize_internal`

```C++
void recipe_dictionary::finalize_internal( std::map<recipe_id, recipe> &obj )
{
    for( auto &elem : obj ) {
        for( const auto &nest : elem.second.nested_category_data ) {
            if( !nest.is_valid() || nest->will_be_blacklisted() ) {
                elem.second.nested_category_data.erase( elem.second.nested_category_data.find( nest ) );
            }
        }
        elem.second.finalize();
        inp_mngr.pump_events();
    }
```

With that change there are no any load errors and I can see errors with only following three recipes when opening crafting menu while `DDotD` mod is enabled (which is probably caused by something elese):

- `bot_crows_m240`
- `bot_dispatch`
- `iv_mutagen_lupine`
