### ISSUE TITLE
Basecamp expansion Workshop 2 Saltwater pipe crash

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#66318]
### Describe the bug

When trying to construct the first phase of a saltwater pipe the game terminates.

Callstack when debugging:
 	cataclysm-tiles.exe!std::string::size() Line 4276	C++
 	cataclysm-tiles.exe!std::hash<std::string>::_Do_hash(const std::string & _Keyval) Line 5312	C++
 	cataclysm-tiles.exe!std::_Conditionally_enabled_hash<std::string,1>::operator()(const std::string & _Keyval) Line 2170	C++
 	cataclysm-tiles.exe!cata::hash_combine<std::string,std::hash<std::string>>(unsigned __int64 & seed, const std::string & v, const std::hash<std::string> & hash) Line 21	C++
 	cataclysm-tiles.exe!cata::tuple_hash::operator()<std::string const ,cata_variant>(const std::pair<std::string const ,cata_variant> & v) Line 58	C++
 	cataclysm-tiles.exe!cata::hash_combine<std::pair<std::string const ,cata_variant>,cata::auto_hash<std::pair<std::string const ,cata_variant>>>(unsigned __int64 & seed, const std::pair<std::string const ,cata_variant> & v, const cata::auto_hash<std::pair<std::string const ,cata_variant>> & hash) Line 21	C++
 	cataclysm-tiles.exe!cata::range_hash::operator()<std::unordered_map<std::string,cata_variant,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<std::string const ,cata_variant>>>>(const std::unordered_map<std::string,cata_variant,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<std::string const ,cata_variant>>> & range) Line 76	C++
 	cataclysm-tiles.exe!std::hash<mapgen_arguments>::operator()(const mapgen_arguments & args) Line 35	C++
 	[External Code]	
>	cataclysm-tiles.exe!basecamp_action_components::choose_components() Line 856	C++
 	cataclysm-tiles.exe!basecamp::common_salt_water_pipe_construction(const mission_id & miss_id, expansion_salt_water_pipe * pipe, int segment_number) Line 2662	C++
 	cataclysm-tiles.exe!basecamp::start_salt_water_pipe(const mission_id & miss_id) Line 2849	C++
 	cataclysm-tiles.exe!basecamp::start_upgrade(const mission_id & miss_id) Line 1826	C++
 	cataclysm-tiles.exe!basecamp::handle_mission(const ui_mission_id & miss_id) Line 1521	C++
 	cataclysm-tiles.exe!iexamine::bulletin_board(Character & you, const tripoint & examp) Line 1931	C++
 	cataclysm-tiles.exe!map_data_common_t::examine(Character & you, const tripoint & examp) Line 578	C++
 	cataclysm-tiles.exe!game::examine(const tripoint & examp, bool with_pickup) Line 6084	C++
 	cataclysm-tiles.exe!game::examine(bool with_pickup) Line 5940	C++
 	cataclysm-tiles.exe!game::do_regular_action(action_id & act, avatar & player_character, const std::optional<tripoint> & mouse_target) Line 2220	C++
 	cataclysm-tiles.exe!game::handle_action() Line 3014	C++
 	cataclysm-tiles.exe!do_turn() Line 538	C++
 	cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 826	C++
 	[External Code]	

The last sane part of the call chain (before the hash juggling mumbo jumbo) was:
cataclysm-tiles.exe!basecamp_action_components::choose_components() Line 856
There args_ has the value of {map= {size=0}}, which doesn't seem reasonable, and is probably what causes the code to blow up (although the "find" function should have handled such a situation).

### Attach save file

N/A

### Steps to reproduce

1. Create the workshop version 2 expansion (in a location reasonably close to a swamp, allowing for a pipe to be constructed).
2. Spawn the equipment for making the saltwater pipe.
3. Order the pipe to be constructed and verify that you accept that X additional jobs are required to finish it.
4. Have the game terminate (or caught on an exception if debugging (at least when compiled with debugging: haven't tested debugging release mode))

### Expected behavior

It would still work...

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 0.G-2494-g22e9c95c2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I think someone recently modified things to use maps rather than lists, and this may be a case that wasn't covered or tested properly.

**Comment by PatrikLundell** [comment]
I suspect #62498 to be the cause of this. Could someone knowledgeable (e.g. @mqrause ) please have a look at whether that's the case?

**Comment by mqrause** [comment]
A quick glance at the code tells me it's likely not caused by #62498 because that only affects _item_ components, but the issue here seems to be _recipe_ requirements.

**Comment by PatrikLundell** [comment]
Thanks for checking, and sorry to bother you.

**Comment by mqrause** [comment]
It's not a bother, but I can't assist further with the issue currently.
