### ISSUE TITLE
Aiming at low skill levels should be considerably less powerful

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66326]
### Is your feature request related to a problem? Please describe.

Currently the player is a crack shot even at zero skill and can flawlessly hit every shot on enemy zombies if they precise aim. Their aiming is too fast, and their odds of landing a hit are too high (no matter how much a novice aims their gun, they're never going to get a solid hit %).
Police in general have pretty low hit rates, from 20%-33% or so and are trained with their guns. That alone implies that the current hit rate (90-100%) See some stats listed in #64990.

### Solution you would like.

Base aiming speed should be lower at low skill, and scale upwards towards normal levels at higher guns/marksman skill. Hit rates should be lowered (a simple fix would be to adjust the size-based hit rates so that normal sized enemies have a lower % of hit rate). Enemies moving and especially leaping should have a more serious effect of throwing off your aim. For a very low skill shooter, most shots should be misses (which is currently not the case at all)

### Describe alternatives you have considered.

There are a million ways to work around this and I don't have any definite solution. I am not super familiar with aiming code.

**Comment by SirPendrak** [comment]
Hitting moving targets, even if they just approach you, should be like 3x times harder. If they move sideways then even harder. Hitting stationary probably could stay the way it is.

**Comment by kilozombie** [comment]
Huge fan of all of this. I'm curious, how should this affect non-gun aiming? (throwing, slinging, archery)

**Comment by fairyarmadillo** [comment]
They use most of the same code, so I imagine it would be the same result for them.

**Comment by fairyarmadillo** [comment]
I agree that it's a little strange that two gunmen with zero skill at what I would guess is 10-20 meters (game distances are fuzzy) will pretty much always hit each other if they fully aim. I'm not sure if this PR needs to solve that issue or if it can be pushed out to a later addition.
