### ISSUE TITLE
Direct Floodlight Appliance Seems to be Unobtainable?

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#66344]
### Describe the bug

So I'm not 100% because the naming is so confusing, but the standing directed floodlight appliance added in #65655 by @waxcatape appear to be unobtainable.  To construct the directed floodlight, you require an item called "disconnected standing directed floodlight".  However, this appears to not be craftable, does not spawn in any location, and cannot be found on existing vehicles.  The only existing items appear to be the directed floodlight or the disconnected standing floodlight.  Neither of these can be used for the construction of the appliance called the standing directional floodlight.

The point of the PR was to add directional facing, but we cannot access the appliance that lets you have directional facing.  Not sure how this was not caught in testing, unless they were using debug hammerspace or something.  I may completely be missing something because the naming here is very confusing when they all have basically the same names.  If I am wrong let me know and I'll withdraw the issue.

I just double-checked the PR again and searched through the game files -- it really does appear to be unobtainable, which renders that whole PR pointless?  I'm worried I'm missing something but I'll post the issue anyway.

### Attach save file

N/A

### Steps to reproduce

1. Ensure you are not using debug hammerspace or similar magic construction.
2. Open construction menu and find the "Standing Directed Floodlight"
3. Observe that it requires a "disconnected standing directed floodlight"
4. Search HHG for this item and find that it does not spawn and is not craftable
5. Search for the vehicle part of the same name and find that it does not exist on any vehicles
6. Be confused and annoyed that it appears unobtainable

### Expected behavior

I mean their PR says they tested it and it worked.  Just sort of expect it to work.

### Screenshots

I don't really know how to show in screenshots that something doesn't exist.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 6060d00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

If I'm missing something just let me know and I'll close the issue.  But after looking at this for a while it seems to be unobtainable.

**Comment by TheMurderUnicorn** [comment]
Yo, look at the hustle on this dude.  Respect for submitting a fix within an hour of it being pointed out.

**Comment by waxcatape** [comment]
Thank you for pointing it out!
