### ISSUE TITLE
Map memory does not remove previous location of furniture

### ISSUE THREAD

**Issue by 9921622** [CleverRaven/Cataclysm-DDA#66349]
### Describe the bug

Map memory does not remove the previous location of furniture ie. chairs, bookcase, tables, plant pots, etc.
I have tried deleting everything cdda related on my pc and re installing. But the same bug occurs

### Attach save file

[Taylor Creek-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11811514/Taylor.Creek-trimmed.tar.gz)

### Steps to reproduce

1. Look at furniture (furniture is visible to player)
2. Move furniture
3. Look away (furniture is NOT visible to player)

result: There now will be two places where the furniture appears to be in. 1. the previous location 2. the current location

### Expected behavior

There should only be one location in map memory the furniture is located. I expect this to happen since my last game (an experimental build from around the start of April) did not have this issue.

### Screenshots

step 1
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/39788517/793096b7-cad4-4b9c-809c-ca4cabb946f7)

step 2: moved right benches right by 1 tile
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/39788517/011eb39b-b4e0-47b5-9118-39ff4c085252)

step 3: there are now double the amount of benches to the right of the player character
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/39788517/42147086-f02b-42b9-9e2a-0ea8dca23b99)

when furniture is visible again the duplicate benches disappear:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/39788517/8339a74e-841d-4583-9ae2-494de65478f2)

replicating steps 1 - 3 repeatedly
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/39788517/dac95345-9b16-4cb3-923e-edc73f95a279)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: fef7122 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

If I'm missing something just let me know and I'll close the issue

**Comment by RenechCDDA** [comment]
Should be resolved by #66327. Please update to the newest experimental.

If this does not resolve the issue, comment and I can reopen it.
