### ISSUE TITLE
Hauling and Advanced Inventory, 'Segmentation Fault' Crash

### ISSUE THREAD

**Issue by kylesjob** [CleverRaven/Cataclysm-DDA#66366]
### Describe the bug

I tried to haul collapsible drums of water across the ground after moving some drums together with advanced inventory, and the game crashed with a Segmentation Fault error.

### Attach save file

[DeBary-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11824015/DeBary-trimmed.tar.gz)

### Steps to reproduce

1. Advanced Inventory move some drums together
2. Haul them across the ground.
3. Crash?

I don't know if this is causing it or not, as I can't get it to reliably replicate, because it only seems to crash whenever I'm trying not to replicate it. Hope the debug log or something helps in that regard.

### Expected behavior

I expected to be able to haul some drums, because I hauled some other items into my house just fine.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.2057 (21H2)
- Game Version: df4108a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11824027/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11824028/debug.log)

I think the crash mostly happened while I was trying to use advanced inventory to move all the items out of the Cube Van.

**Comment by RenechCDDA** [comment]
Resolved by #66360
