### ISSUE TITLE
A new way to handle defence

### ISSUE THREAD

**Issue by M7mdKady14** [CleverRaven/Cataclysm-DDA#66363]
### Is your feature request related to a problem? Please describe.

**I intend to implement this change if and only if I get the approval of the devs or whatever force accepts changes**

defence in the game doesn't make a lot of sense when you think about it.

first there is dodge and block attempts. you can dodge or block five incoming attacks in one turn with **the same efficiency** as blocking or dodging one attack.
the expected outcome is that more and more attacks against you means having a harder and harder time blocking or dodging attacks until you regain your position or balance.

second is the way the defence process goes. attempt to dodge, if failed, attempt to block, if failed, take the hit.
first of all, attempting to dodge and then failing that dodge, only to block it completely is EXTREMELY difficult.
from my experience as an amateur boxer, there about 4 ways to defend an attack (that is not a grab).

1. is to deflect and that is not in the game and won't be discussed

2. is blocking and that is when you steady yourself for the attack and attempt to block it.

3. is dodging while keeping minimal defences. focus should be noted that the dodge takes importance and the block (if you can call it that) is only in case you get hit and to lessen the damage and not completely block it

4. is complete dodging with no block at all and that is the arms down, full body movement the type that Mohamed Ali used to do. and it is very risky as getting hit would get you full damage while only providing a small boost to your dodging ability compared to the guarded dodge.

that means that dodging at full power and blocking at full power on the same attack is not possible and you have to compromise on one thing or you end up with a really bad dodge and an equally bad block that is worse than just blocking or just dodging.

third, there are some scenarios where attempting to dodge is futile and you end up wasting stamina like attempting to dodge against an attack from a highly skilled enemy. in that scenario, you would've been better if you used that wasted stamina and effort to increase your block.
that goes both ways as there are times when dodging is absolutely necessary and blocking the full attack is impossible and even a partial block would still end up killing or disabling you like attacks from hulks and giants where you would've been better if you used that wasted time and effort to increase your dodge chance.

### Solution you would like.

ok so here is the revised version of the block/dodge rebalance.

we have 4 main actions we can take during an incoming attack. dodge, block, (dodge and block), take the hit.

the selection proccess is similar to how AI functions and the end result mimics what humans do.
it assigns values from 0 to 100 (values) with 0 being taking max damage (take the hit is always 0) and 100 being taking no damage at all.

- for dodge, it's value is based on the dodge chance and how lethal the attack is if not dodged. so having a 100% chance to dodge means the dodge value is at 100 and should be prioritized. having something like a 50% dodge chance doesn't mean it's value will be 50. it could be higher if the attack was mild and would probably be negated by worn armor on that body part or it could be lower if the attack was lethal or deal high damage.

- for block, it's value is based on how much it can block from the attack, with 100 value given if all damage is negated and lower values for less and less damage negated.

- for dodge and block, it's value is based on the same principals as the dodge and the block combined, but calculated with inferior dodge and block (maybe half or something).

finally they are sorted from highest to lowest and you pick the (highest - penalty) where that penalty is a value between zero (you always pick the best option) to 50 (arbitrary).

the penalty is a value dependent on various factor but mostly the melee skill and maybe head or eye encumbrance (if you are experienced in melee combat and more likely to make the better choice).

there is the scenario where the highest value is something like 30 (no option from the three is good and you will take damage regardless) and the penalty brings it to zero (if lower just bring it to zero) and that makes you choose "take the hit" to simulate indecisiveness.

and then we have presets which are basically a set of functions that the final values go through one more time before it is presented and picked from. here is some simple ones that I just picked and need to be fine tuned with trial and error

- "default" preset which has all of it's functions as: f(x)=x which basically does nothing
- "dodge more" preset which has the dodge functions as something like f(x)=2x or f(x)=x+30 and has the inverse for block
- "block more" preset which does the same as the dodge preset but for block
- don't bother with defence unless you can fully negate the damage" preset (great naming btw) which makes the "take the hit" value something like 80 or something higher meaning you are more likely to take the hit. (there is the thing about the penalty which might make you dodge or block even if their values are lower than the 80 at attack even when choosing this preset. you can attribute that to natural instinct to defend oneself and higher melee skill makes you hesitate less to take the attack)

you can change presets the same way you can change your movement mode from walk to run etc.

the second change addresses the way dodge and block attempts work

this one is simple, you have a value called "instability" that increases when you dodge, block, move, or make an attack and resets to zero when you regain your turn or it can decrease with certain techniques.

it makes dodging and blocking worse off as it goes up

the increase is based on attack speed and melee and weapon skill if it was an attack, terrain move cost and atheistic skill when you move, dodge skill and how much dodge did you have compared to what you needed (dodging an attack by a hair gives more instability compared to dodging it easily), same with block.

do note that blocking shouldn't increase instability by much (it should be the least) while dodging is the highest increase rivaled by really big and heavy attacks

overall result means that dodging one attack is safer and easier to do (most of the time) compared to blocking one attack. while blocking multiple attacks is safer and easier than dodging multiple attacks.

**pros over old system**

- character has greater control over what he chooses to defend himself while still not requiring extra input from the player aside from the preset thing which I will mention in cons

- character is now not limited by an arbitrary hard limit on how much he can dodge/block but instead it gradually or exponentially (trial and error is required to find the right balance) gets harder to dodge/block

- character's defensive options gets worse when using large weapons like a big hammer compared to a small weapon like a knife which is realistic (one way to combat this is wearing heavy armor and choosing a "don't bother defending if you can't prevent the damage" preset)

**cons over the old system**

- player might micro manage the fun out of the game by constantly switching presets depending on enemy type and amount and gear used even though the default preset does what it is probably the optimal thing to do.

- the only time when you'd want to use presets like "dodge more" or "block more" is to bypass the penalty of indecisiveness by inflating the value of what you want to do and deflating the value of the thing you don't want to do to make the penalty negligible in comparison 

- both changes result in worse overall defence for the player with low melee skill but better defence for players with higher melee skill (I don't really know if this is a con or not but I'll just put it here)

**Comment by Zireael07** [comment]
> first there is dodge and block attempts. you can dodge or block five incoming attacks in one turn with the same efficiency as blocking or dodging one attack.
the expected outcome is that more and more attacks against you means having a harder and harder time blocking or dodging attacks until you regain your position or balance.

I think the tiring dodges do achieve a bit of this.

> that means that dodging at full power and blocking at full power on the same attack is not possible and you have to compromise on one thing or you end up with a really bad dodge and an equally bad block that is worse than just blocking or just dodging.

That's a very good point that I just <3 about this proposal

**Comment by fairyarmadillo** [comment]
A lot of martial arts already do some of this, but it might be kind of neat if you got a bonus to block/dodge if you passed your turn instead of moving or attacking. You could try to read the enemy's attack speed and attack when it was safe to do so.

OTOH this would make slow hard-hitting weapons worse than they already are, and I don't know if that's needed right now.

**Comment by Ruminator24** [comment]
I feel like giving hard hitting weapons an extra effect when they hit an enemy would be good, perhaps? maybe a force a knockdown and leave them down for a good couple of seconds, or cripple them somehow, but i'm not entirely sure.

**Comment by fairyarmadillo** [comment]
That wouldn't really make sense in most cases and many weapons already do inflict effects. That wouldn't work at all.
