### ISSUE TITLE
Gasmask dosen't accept cartrige anymore

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#66367]
### Describe the bug

The gas/filter mask no longer accepts inserts.
The description no longer says anything about compatible magazines.

### Attach save file

N/A

### Steps to reproduce

1. Make a player with gas mask and cartriges.
2. Try to reload the mask

### Expected behavior

Reloading the mask like it worked before.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: b3e4a9c [64-bit]
- Graphics Version: Tiles
- Game Language: Systemsprache []
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by VincentRoyceMorgan** [comment]
Gasmask cartridges have been changed. Not a bug.
https://github.com/CleverRaven/Cataclysm-DDA/pull/66057
