### ISSUE TITLE
"rust_slowdown" is applied after 0.16% of a level has rusted instead of after 16%

### ISSUE THREAD

**Issue by pingwin43** [CleverRaven/Cataclysm-DDA#66370]
### Describe the bug

from [skill.cpp:388:](https://github.com/CleverRaven/Cataclysm-DDA/blob/fdfd598755a367f7f607ed5d2bcd371c5641d1d7/src/skill.cpp#L388)
```
   float rust_slowdown = std::max( static_cast<float>( std::sqrt( _rustAccumulator / level_exp ) ),
                                    0.04f );
    // rust amount starts at 4% of a level's xp, run every 24 hours.
    // Once the accumulated rust exceeds 16% of a level, rust_amount starts to drop.
    int rust_amount = level_multiplier * rust_multiplier * 16 / rust_slowdown;
```
According to the comment `rust_slowdown` is supposed to stay at 0.04 as long as `_rustAccumulator / level_exp < 0.16`

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

comment should reflect what code actually does or not maybe not give numbers

### Screenshots

quick proof I'm not mad (or at least THAT mad):
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/136499479/57fa9816-2d75-4393-977d-52157aee9f52)

### Versions and configuration

any version since  Aug 12, 2021 to present day

### Additional context

I see 3 resolutions to this:
1. make the comment say rust slows down after 0.16% has rusted (which probably doesn't make much sense)
2. make code do what the comment says by changing `0.04f` to `0.4f`
3. just get rid of the comment or at least the number in it
I know it's an incredibly small thing but I feel like it could be misleading to people trying to understand the codebase

**Comment by I-am-Erk** [comment]
That does indeed look like a decimal error on my part.
