### ISSUE TITLE
Unseen tiles not updating properly.

### ISSUE THREAD

**Issue by Vgoloshivskiy** [CleverRaven/Cataclysm-DDA#66388]
### Describe the bug

If you move furniture tiles where that furniture was will still display furniture even if after moving furniture you seen that empty tile again.

### Attach save file

[Cedar Mills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11836375/Cedar.Mills-trimmed.tar.gz)

### Steps to reproduce

Move furniture
move into another room 
see that tile from which you removed furniture still has it displayed if you dont see that tile

### Expected behavior

Previously worked fine

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56963648/86415c00-4afa-4ea6-ad96-602de213ccd8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: df4108a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by fairyarmadillo** [comment]
I have noticed this as well.

**Comment by martosss** [comment]
I agree that this is weird, our character should be "smart enough" to know that when he moves a piece fo furniture,the old position should get empty, so either dark/unscouted(maybe there's a secret below that furniture? We don't know what's below it), or scouted if the game is nice.

**Comment by Vgoloshivskiy** [comment]
> I agree that this is weird, our character should be "smart enough" to know that when he moves a piece of furniture,the old position should be empty, so either dark/unscouted(maybe there's a secret below that furniture? We don't know what's below it?), or scouted and empty if the game is benevolent.

You can check this rooms and see that they are empty but it will still draw furniture there after you leave (damn it is quite hard to explain what is happening).

**Comment by Vgoloshivskiy** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/66327
