### ISSUE TITLE
Fatigue or weariness as spell power sources

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#66398]
### Is your feature request related to a problem? Please describe.

@Standing-Storm requested this for #66391, as these cannot be used directly and require workarounds to affect fatigue & nothing can affect weariness.

### Solution you would like.

Spells can specify fatigue or weariness as spell power sources

**Comment by Standing-Storm** [comment]
Specifically, Fatigue can be affected by the recover_energy spell effect, but it can't be an energy_source. IIRC weariness basically can't be affected by anything at all--not spells, not EoCs, not anything. Even the debug menu only lets you reset it to 0, not manipulate it with any granularity.
