### ISSUE TITLE
More improvised weapons and armour!

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#66393]
### Is your feature request related to a problem? Please describe.

At the start of the game, like in most survival situations, you're left essentially barehanded as far as weapons go. You might find a knife or bludgeon at the start, but you're generally left very vulnerable. This is especially true if you start somewhere infested, like in a city. Yet I feel that with some craftiness, and a bit of time, you could create a variety of improvised weapons and armour beyond what CDDA currently allows!

### Solution you would like.

Currently we have a fair amount of improvised stuffthat can be made in a short time, including cut planks, glass shivs and carpet armour. But these barely scratch the surface of improvised weaponry and armour.
Shirts and jackets stuffed with paper, scraps of cloth and whatever else is available!
Clubs made out of newspapers, like the infamous Millwall Brick.
Various sharp implements taped or wrapped to rods and sticks, either in the form of short spears or improvised warpicks.
Things stuffed in socks beyond rocks, including bars of soap, phones, and various other materials.
Pillow armour, either strapped, taped or stuffed into clothing somehow.
And of course, layered clothes made into armour. Not just worn one above the other, but sewn or taped together, like certain recipies already within the game.

### Describe alternatives you have considered.

Just leaving the area of improvised stuff be left barren...

### Additional context

Just looking around my own apartment I can see several pieces of "material" that with a bit of time and effort could be turned into effective enough arms and armour. Taping a knife to a mop, tying my pillows to my arms, etc... I feel like this niche of "initial survival" is currently missing from CDDA, and needs some filler. Unfortunately I don't know how to program, so I'm putting this out there as a suggestion instead. Satisfy me, please!

**Comment by Aerin-of-the-Toast** [comment]
Believe me, I'm adding all the improvised junk arms and armor I can think of :p
Though there is a certain point where the weapon or armor is so bad it's worse than wearing nothing or using just a stick or plank as a weapon. 
As fun as weapons like the rock-in-a-sock is I don't think I've ever made one since it's worse than just slapping people with a pipe, for instance.

**Comment by Beardtongue** [comment]
All things being equal, short spears and pillow armor aren’t bad ideas 😁

**Comment by Kantonine** [comment]
> All things being equal, short spears and pillow armor aren’t bad ideas 😁

don't we have javelins for short spears? and I don't know how effective pillow armor can be. Wooden chestplates and war masks have been discussed before for Innawood/mainline purposes. another idea I had is from a video by weaponsandstuff93 who used cutting boards as replacement plates for an osprey vest, it wouldn't be too hard to transfer that over to a Iotv/Plate Carrier.

https://www.youtube.com/watch?v=cg_GVV2L1RU

**Comment by Beardtongue** [comment]
> > All things being equal, short spears and pillow armor aren’t bad ideas 😁
> 
> don't we have javelins for short spears? and I don't know how effective pillow armor can be. Wooden chestplates and war masks have been discussed before for Innawood/mainline purposes. another idea I had is from a video by weaponsandstuff93 who used cutting boards as replacement plates for an osprey vest, it wouldn't be too hard to transfer that over to a Iotv/Plate Carrier.
> 
> https://www.youtube.com/watch?v=cg_GVV2L1RU

Yeah, my bad on the javelins. You should know, though, that I’m approaching pillow armor with a very specific image in mind
![](https://i.imgur.com/Oy2J54n.gif)

**Comment by Beardtongue** [comment]
On a more serious note, one improvised weapon I do hope we see at some point is the monkey’s fist or slungshot, which is basically a more serious version of the rock-in-a-sock. There aren’t that many chain/rope weapons yet and I could stand to see more representation— not to mention everybody and their mom who does pop survival stuff has probably seen or made at least one.
https://en.m.wikipedia.org/wiki/Slungshot

**Comment by S0ZDATEL** [comment]
>Taping a knife to a mop

I'm no shiftmade weapons expert, but I guess you are trusting your tape too much. Wouldn't the knife just get loose and fall off the mop after like one hit with it? I don't think there is a reasonable amount of tape to hold a knife on a mop for a repeated use as a weapon...
