### ISSUE TITLE
Gas Masks Cannot be Reloaded / Refilled

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#66405]
### Describe the bug

As of a recent update (I'm currently finding it on fb56b93) all gas masks, filter masks, rebreather masks, etc appear to have no valid ammunition defined for them and can no longer be refilled by any means.

### Attach save file

[Union Lake-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11850135/Union.Lake-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. View inventory
3. Observe rebreather mask, winter survivor mask, gas mask carts, rebreather carts, and filter mask carts
4. Attempt to (r)eload rebreather or winter survivor mask
5. View details of either mask
6. Observe compatible magazines

### Expected behavior

The ability to use gas masks, especially since they're now necessary to make welding wire (via acid), something we suddenly need hundreds of times as much of as before. Also, you know, as masks.

### Versions and configuration

fb56b93 - Win 10 x64 tiles sounds
Arcana + Compatibility with Magiclysm are the only two non-standard mods

**Comment by Maleclypse** [comment]
The json looks good on master. Did you update your game or was this fresh on a new download?

**Comment by Ichthysdekilt** [comment]
I did a fresh download and copied the saved game into it. Is there something more I should be doing?

**Comment by RDru** [comment]
You need new "ammo". It's like magazines now. #66057 
Personally I have spawned some new filters and destroyed the old ones.
