### ISSUE TITLE
Hub01 combat gear needs some reflavoring

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66410]
### Is your feature request related to a problem? Please describe.

Currently Hub01 armor is designed as being clipped onto a poncho. This would be wildly impractical, as armor should be tightly affixed to your body and a poncho is loose, meaning it would get in the way, be highly unwieldy, and probably not as protective.
In addition it feels a bit weird that Hub01 has designed an entirely new set of armor whole cloth instead of simply re-tooling existing proven designs. Combined with their "hybrid weapons platform" which combines wildly different calibers all into one gun their whole thing feels a little excessive. Like why did they spend so much R&D trying to replace the M4 and US Army vest? Especially as we can find their troops wore "XEDRA containment armor" which is just a US Vest with ESAPI inserts.

The 3D printed bracers and greaves make some sense as they work in tandem with existing ballistic vests and provide an obvious benefit in the post apocalypse (the need to cover up your whole body from zombies etc) but even then there are existing armors like riot gear that would be much faster and easier for them to work with and re print rather than making an entirely separate system. Maybe they tweak the riot gear to be more covering on arms/legs and combine that with vests, and maybe they try to make ballistic inserts that are more durable than ESAPI geared towards more conventional non ballistic threats.

### Solution you would like.

Personally I think their entire Modular Defense System should be done away with. They should offer regular and "retooled" riot arm and leg guards as protection (with a possible UHMWPE upgrade).
I personally want to replace their torso protection with either US vests or a brand new Powered Combat Vest, RM12b maybe. This would behave similarly to RM13 but be a less advanced, torso only version, similar to the ones from Opposing Force, and represent the precursor to RM13 and be more widely produced and utilized. Rivtech is canonically integrated with XEDRA and they already have access to Riv tech per Ulysses O'Rourke's existence. It would give them a cool techy thing that they had been working with before the Cataclysm actually happened that became a logical, marketable thing for them to produce with their nanofabricator, rather than deciding to invent an entirely new kind of armor post-cataclysm (since they just used US gear before the cataclysm as evidenced by the XEDRA kill team you find in the physics lab). Later they could integrate it with the 5pt anchor as they do with the MDS. Personally I'd also want to distribute this gear to Bio-Operators who appear to be basically XEDRA spec ops units, appearing primarily in labs. The powered ballistic vest would give some explanation for "their malfunctioning gear sends out showers of sparks". 
I don't think the HWP is conceptually workable. A rifle that can convert from 5.56 to shotshell to 30~06 (exodii bullets) would require so many replacement parts that you're essentially just bringing different rifles in each case and there's no clear advantage to its creation as opposed to just using M4s or other proven, existing platforms. 

### Describe alternatives you have considered.

There may be more logical explanations for the Hub coming up with a whole new system of armor and weaponry after the cataclysm that I'm not aware of.

**Comment by fairyarmadillo** [comment]
I don't think anything in the entire game should bear visible XEDRA branding. Maaaaybe internal documents but even that seems like a wildly unnecessary security risk. It's beyond top secret, who are they advertising to?

Hub 01 is also a robotics factory, not a munitions factory. If they are applying their resources toward customizing existing designs for specific purposes, or trotting out prototypes, fine, but it doesn't make sense that they've made this impossible gun and armor with a never-before-seen form factor.

**Comment by John-Candlebury** [comment]
Feel free to reword the description of the MDS base piece to your liking.

I'm unlikely to support the removal or extensive mechanical reworks of the Hub 01 gear mentioned in this issue. They already offer interesting advantages/disadvantages when compared to equivalent pieces, are properly balanced, and more importantly are effective at fullfiling the design goals I have laid for the faction as a whole. I consider their designs to be final baring the discovery of problems that present actual gameplay consequences.

**Comment by randomtyper** [comment]
Maybe make the bio-operators into feral enemies, while you are at it. Will explain why they have some of their skills remaining (signature takedown). And add a gun-armed version just because it makes sense.

**Comment by Kantonine** [comment]
all of the robofac armor is supposed to be prototypical, with stuff like the XEDRA containment armor and regular m4's, m27iar's and similar weapons being the M.O.  I do agree with the oddity about the MDS and MDA being poncho-like, but it could be argued that when the mantle and skirt are placed within the MDS/A the armor also clips to yourself.

**Comment by fairyarmadillo** [comment]
I have a huge problem with the idea that a semiautomati gun smaller than an m4 could effectively fire 12 gauge shells, 9mm, 5.56, and 7.62. That does not sound physically possible to me. If it were feasable, it would have been done IRL, but nobody has ever managed such a thing to my knowledge, even as a prototype or hobby project. 

The barrel is not the only part of the gun involved in firing, and the entire process of ejecting cartridges and moving the action relies on specific mechanical forces exerted by the round when the powder goes off. 7.62 NATO puts out something like 62,000 PSI of pressure when it goes off and 9mm is literally half that, worlds apart in terms of physics.

7.62 NATO is also designed to work with a 22 inch barrel, but the designated marksman HWP is only 21 inches long total. At the very least, the item is much too small for what it does.

**Comment by anoobindisguise** [comment]
> Feel free to reword the description of the MDS base piece to your liking.
> 
> I'm unlikely to support the removal or extensive mechanical reworks of the Hub 01 gear mentioned in this issue. They already offer interesting advantages/disadvantages when compared to equivalent pieces, are properly balanced, and more importantly are effective at fullfiling the design goals I have laid for the faction as a whole. I consider their designs to be final baring the discovery of problems that present actual gameplay consequences.

So the problem is even if they're balanced gameplay wise, that's not the real issue compared to it being very weird for hub01 to have. Yes, they have access to the nanofabricator to print their own armor, but why would they spend valuable time inventing brand new armor? And a brand new attachment system? Especially if it's not any better than existing designs (US vest and riot gear for limbs) surely they would know this in preliminary testing, and why continue to commit resources towards it?
Also, I'm not sure what you mean by the faction's design goals. Hub01 wants to be self sufficient and coax mercenaries into doing their grunt work with specific incentives but they don't need the MDS to do that. Like they could give you pre-programmed defensive robots, or mass-produced versions of existing gear, and that would still be enticing.

**Comment by andrei8l** [comment]
> but why would they spend valuable time inventing brand new armor? 

They're nerds stuck in a lab with no financial oversight or survival worries. What else are they going to do?

**Comment by John-Candlebury** [comment]
> So the problem is even if they're balanced gameplay wise, that's not the real issue compared to it being very weird for hub01 to have. Yes, they have access to the nanofabricator to print their own armor, but why would they spend valuable time inventing brand new armor? And a brand new attachment system? Especially if it's not any better than existing designs (US vest and riot gear for limbs) surely they would know this in preliminary testing, and why continue to commit resources towards it? Also, I'm not sure what you mean by the faction's design goals. Hub01 wants to be self sufficient and coax mercenaries into doing their grunt work with specific incentives but they don't need the MDS to do that. Like they could give you pre-programmed defensive robots, or mass-produced versions of existing gear, and that would still be enticing.

Feel free to write dialogue, new loot drops, or quest lines that answer those questions in ways that maintain the MDS.

Also note that partial answers are implied already by current mechanics, Hub makes the MDS because they have the capacity to, but cant make the ceramic composites of ballistic plates and theyare interested in armor that can function in the long term.

**Comment by bombasticSlacks** [comment]
>  I don't think the HWP is conceptually workable. A rifle that can convert from 5.56 to shotshell to 30~06 (exodii bullets) would require so many replacement parts that you're essentially just bringing different rifles in each case and there's no clear advantage to its creation as opposed to just using M4s or other proven, existing platforms.

You are describing an AR-15 
https://www.brownells.com/gun-parts/shotgun-parts/shotgun-receiver-parts/gen-12-upper-receiver-12-gauge/

People like them because they are comfortable with the control group and lower 🤷 it would be the same deal but just a different platform.

**Comment by anoobindisguise** [comment]
> You are describing an AR-15 https://www.brownells.com/gun-parts/shotgun-parts/shotgun-receiver-parts/gen-12-upper-receiver-12-gauge/
> 
> People like them because they are comfortable with the control group and lower 🤷 it would be the same deal but just a different platform.

So why not just issue AR-15s? Even if they're mass-produced by fabricator, it's a known and proven platform. What advantages does the HWP offer that is worth giving up STANAG mags and familiarity with the platform and all the time investment needed to make it useful? Armalite didn't invent theirs overnight.

**Comment by bombasticSlacks** [comment]
Because they were on the prototype to the HWP before the Cataclysm as seen on the strike team. Presumably before that they were on another bullpup platform like the MDR of one of the Israeli rifles. 

I think another group could be on high end AR platforms, presumably the new SIG guns, but the Hub stuff already works, and most people seem to like it.
