### ISSUE TITLE
Game crashes when trying to start a run in a particular world.

### ISSUE THREAD

**Issue by aGreenJelly** [CleverRaven/Cataclysm-DDA#66427]
### Describe the bug

Generated a new world and tried to start a game with a new character. Game crashed three times when I tried to start the Evacuee scenario. Other worlds give no such error.

### Attach save file

N/A

### Steps to reproduce

1. Generate a world.
2. Create a character.
3. Try to start the world in the Evacuee scenario
4. Game crashes immediately without loading in to the world.

### Expected behavior

For the game to start after character creation is complete.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 8776427 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Generic Guns [generic_guns],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11857215/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11857216/crash.log)

**Comment by RenechCDDA** [comment]
Can't reproduce, nor make much sense of the provided crash log. Can you upload the world itself? Should be pretty tiny since you haven't been able to play in it.

Also, does this only happen on that world? Can you make other worlds which do not crash on loading them?

**Comment by aGreenJelly** [comment]
> Can't reproduce, nor make much sense of the provided crash log. Can you upload the world itself? Should be pretty tiny since you haven't been able to play in it.
> 
> Also, does this only happen on that world? Can you make other worlds which do not crash on loading them?

I tried to upload the files in the save\World\ folder but got an alert that the file type was not supported. Should I try to upload them somewhere? 
No other worlds have had this crash on the version I'm playing.

**Comment by RenechCDDA** [comment]
Just zip them up before uploading.

**Comment by aGreenJelly** [comment]
[Pronto.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11857555/Pronto.zip)
Ah, there we go, I think. Sorry for the trouble.

**Comment by irwiss** [comment]
/confirm

I caused it in https://github.com/CleverRaven/Cataclysm-DDA/pull/66399
To reproduce have to start in shelter a few times to trigger the random mapgen applying (on msvc build, or may be i didn't try enough times on clang), not 100% sure on the correct solution as i can't find a "we're in mapgen stage still" flag

**Comment by akrieger** [comment]
I have a stack in #66480 with an array OOB explaining how it's crashing.
