### ISSUE TITLE
Bring back the point pools

### ISSUE THREAD

**Issue by whoami1i1i1i** [CleverRaven/Cataclysm-DDA#66426]
### Is your feature request related to a problem? Please describe.

I mean the single point and multi point pools during character creation

As of now, there's only the "survivor" option which is nothing more than renamed free form, which I never used as that felt like utter cheating to me

I understand that you can re-enable the old ones in the settings, but the game says they're "not balanced anymore" and "legacy"

I'm sure there are many like me that aren't happy with this change, in fact I have seen complaints like mine already, and all I ask for is to bring the old ones back (enabled by default, not "leagacy" anymore) and keeping them balanced...

I just can't play like this, I had to go back to 0.G...

### Solution you would like.

Both the new survivor mode and the old point pools can and I think _should_ coexist
The ideal solution would be to simply re enable the point pools by default and keep them balanced, giving the player an option to either go for the survivor (previously known as freeform) mode with the indication of how strong the character is, or use the point pools without those indications, instead having the hard limit of points

**Comment by irwiss** [comment]
Points are just as much "cheating" as freeform, unless you unironically think taking Ugly, Truth Teller, Rigid Table Manners is equivalent to having Robust Genetics or Quick

The option is still there in world options (for now)

**Comment by RenechCDDA** [comment]
I would like points to stay around more or less indefinitely, personally. Yes, you can game the system and yes some of the points cost need reconsidering but if those are the only barriers I'll be happy to take an afternoon tweaking the values to fully account for metagaming.

**Comment by whoami1i1i1i** [comment]
> Points are just as much "cheating" as freeform, unless you unironically think taking Ugly, Truth Teller, Rigid Table Manners is equivalent to having Robust Genetics or Quick
> 
> The option is still there in world options (for now)

There is a difference, and quite a considerable one at that
In freeform, you can do whatever you want without any limits, you could pick every single positive trait and max out everything if you wanted to without picking a single negative trait
In the pool modes not only you need to pick for some negative traits (which admittedly can be pretty much nothingburgers) and (this is important) there is a limit as to how many positive ones you can pick, unlike in freeform
I agree that the point system is far from ideal, and I admit my suggestion was pretty lame
However I believe there is big potential to be had in the point system, and that the survivor system by _itself_ would not be an ideal option for all of the players, for example you could separate positive and negative traits into combat, livestyle, defense etc. categories taking inspiration from the survivor mode indicators
So for example for picking a positive combat trait, you would also have to pick a negative combat trait, all with a set limit of how much you can do it (like the 12 point limit from the old pool modes, regardless of how many points to spend you actually have)
That would prevent going with really overpowered combat traits and compensating for that with the nothingburgers like ugly, truthteller and so on
I was mainly focusing on traits here, but this also could apply to all the other sections of character creation I think

**Comment by SariusSkelrets** [comment]
> So for example for picking a positive combat trait, you would also have to pick a negative combat trait, all with a set limit of how much you can do it (like the 12 point limit from the old pool modes, regardless of how many points to spend you actually have) 

It doesn't address the point system's problem: the player will still pick strong positives and unimpactful negatives, but now with every category. There's "nothingburgers" in all categories and with your example the player would be motivated to pick them all.

Freeform allowing to take positives without negatives isn't a problem as the player can take negatives that have effectively no impact with points.
