### ISSUE TITLE
Lycra should be much less protective

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66433]
### Is your feature request related to a problem? Please describe.

IRL lycra (even a nylon/lycra blend like in game) is super shitty as a protective material, being extremely flimsy and also unsuitable for sewing other materials onto it as a base layer, but in game it's a very strong material with 2/2/2 defense.

### Solution you would like.

Protection should be much worse, and gear relying on Lycra for protection (nomad gear for example) shouldn't be made of it.

**Comment by fairyarmadillo** [comment]
Lycra should also not appear in most of the locations it's used, such as the scavenger suit. Lycra is a skin-tight stretchy material, and there are many cases in the game where very heavy non-stretchy materials are sewn to it. I don't think any item made of leather and lycra would last very long as the leather would fail to stretch with the lycra and tear off of the garment.

I feel like people are misunderstanding what it is, or simply choosing it for its superior in-game stats.
