### ISSUE TITLE
Misc Military additions and Reworks

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#66432]
### Is your feature request related to a problem? Please describe.

With the addition of many new features for military item groups, such as older helmets, modern helmet attachments, and usable ablative pockets and PALS webbing, a few things have slipped through, such as fleshing out non modern military/paramilitary gear and minor modern clothing.

### Solution you would like.

- Military Field Shirts, either as a new item or as a older variant of the combat shirt or sheriff's shirt
- Slight rework of PALS system (if necessary) to allow for non torso MOLLE attachment such as drop leg and ballistic thigh panels
- Ballistic thigh Panels and Drop Leg Panels with PALS webbing
- Older Tactical Chest rigs such as the ALICE System and related prototypes and alternative international stand-ins
- Flak Jackets or similar gear.
- Something along the lines of the original PASGT System of both helmet and vest and possible variants
- Vest-Mounted Assault Pack

### Describe alternatives you have considered.

touch grass

### Additional context

drop leg panel:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/3b139fad-c865-484c-a11a-c8ece7d41f62)

Ballistic thigh panel with PALS webbing
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/8cd099fb-3456-44a0-b588-850c7948be42)

ALICE Harness
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/b8299780-3c3b-4fc6-b210-001d9dc16dd2)

Individual Integrated Fighting System (IIFS) Components
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/7f92fc4d-93d4-4b99-b898-9436ba95a271)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/85dee31c-ee44-4f1a-ae67-130e92d93bc4)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/13393c76-4c9f-43ec-b9b9-863961bb01c1)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/c98efe28-9416-4e88-9995-c9363c283ccd)

SADF Battle Jacket P83
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/1ce99828-5b60-4b85-b420-c257815a7fe7)

Field Shirt
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/ad06e302-acb6-4260-9a62-8f2814cab8fa)

Vest Mounted Pack
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/30ee4748-c89c-4b89-845b-c29459080570)

**Comment by Kantonine** [comment]
all images are presented as examples, it doesn't have to be perfectly recreated imho

**Comment by anoobindisguise** [comment]
the nylon aketon/gambeson kind of serves the role of a flak jacket but dedicated historical items would work too. more variety = more good right?
