### ISSUE TITLE
MELEE_DAMAGE enchantment should affect bashing damage to tile

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#66434]
### Describe the bug

by using magic in magicalysm you can deal insane damage in melee but that doesnt affects your bashing damage on tile.
 for example you can break the reinforced glass with homewrecker but not with pipe mace but if you use magic to multiply its damage by 1.5 you should be able to break it.

### Attach save file

not needed

### Steps to reproduce

get Gravity Control and bash a terrain and realize it deals same damage.

### Expected behavior

MELEE_DAMAGE enchantment should affect bashing damage to tile

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 7070a09 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    MST Extra [MST_Extra],
    DinoMod [DinoMod],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/DinoMod Patchmod [Arcana_Dinomod_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
Need to tie the enchantments into the bash function

https://github.com/CleverRaven/Cataclysm-DDA/blob/1b983260a71eb6df6b9109eb18b3c3cd0255887b/src/map.cpp#L2915-L2956

**Comment by fyhannes** [comment]
Merged with #66735.

**Comment by alp7292** [comment]
ok
