### ISSUE TITLE
Disabling edge scrolling unbinds pretty much every key until you enable it again.

### ISSUE THREAD

**Issue by SunkenLotus** [CleverRaven/Cataclysm-DDA#66443]
### Describe the bug

Pretty much as mentioned in the title.

I disabled edge scrolling since I use a dual monitor setup. It was getting on my nerves when I had the map open and would move the mouse to my second monitor.

After disabling edge scrolling, I was no longer able to do anything else. I'll include a screenshot of the message log as it isn't entirely like the usually message you receive upon pressing an unbound key. While I'm not sure if it's save related, I will also include a copy of the save file this occurred on.

### Attach save file

[Mystic Sky-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11859287/Mystic.Sky-trimmed.tar.gz)

### Steps to reproduce

1. Have "Hide mouse cursor" set to "HideKB" (I don't know if this is actually relevant. Read additional context for reasoning).
2. Have "Edge scrolling" set to "Normal".
3. Restart app.
4. Load a character.
5. Esc -> Options -> Interface -> Mouse Control Options.
6. Change "Edge Scrolling" to "Disabled".
7. Esc -> "Save changes?" (Y)es
8. Attempt to move.

### Expected behavior

Keybindings aren't temporarily lost.

### Screenshots

![image_2023-06-25_102207054](https://github.com/CleverRaven/Cataclysm-DDA/assets/137209216/14652558-77af-48af-a7c6-e24f81151de4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1848 (22H2)
- Game Version: 1b98326 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    No Bionic Slots [no_cbm_slots]
]

### Additional context

I'll add a few bits of info that may or may not be useful.

- My mouse control options are as follows;
- Enable joystick = True
- Hide mouse cursor = HideKB
- Edge scrolling = Normal

* * *

- When I changed the "Edge scrolling" setting to anything other than normal, I would lose 90% of my keybinds. 
- The keybinds returned when switching the setting back to normal.
- I could reproduce this bug each time I changed this setting to anything other than normal.

* * *

- At one point, I changed the setting to "Disabled". Losing the keybinds once again.
- Instead of changing it back, I changed the setting for "Hide Mouse Cursor".
- I changed the setting from "HideKB" to "Show". This also changed the keybinds back to how they should be.
- After doing this, I am no longer able to reproduce the bug. Even if I set it back to HideKB and change the "Edge scrolling" setting again.

**Comment by RenechCDDA** [comment]
Can't reproduce on 
- OS: Windows
    - OS Version: 10
- Game Version: 8846e84 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Bombastic Perks [bombastic_perks]
]

**Comment by Qrox** [comment]
Could you upload your `config/options.json` and `config/keybindings.json`? It might be easier to see what's going on with those files.

**Comment by RenechCDDA** [comment]
> Could you upload your `config/options.json` and `config/keybindings.json`? It might be easier to see what's going on with those files.

Those are actually in the minimized save archive. I did apply them to test, but the result was the same.

**Comment by Qrox** [comment]
> Those are actually in the minimized save archive.

Oops, forgot that was a thing...

Anyway, according to `options.json` the keyboard mode was set to symbol when OP uploaded the save, but the messages in the screenshot suggest it was using the key code mode (only key code mode supports keypad number keys), so the OP might have accidentally switched the keyboard mode when changing options. According to `keybindings.json` the directional actions in the default mode did not have any key code bindings, which is consistent with the behavior in the screenshot.
