### ISSUE TITLE
Error with well distributed gear buff from wearing nomad gear

### ISSUE THREAD

**Issue by Nrtgf** [CleverRaven/Cataclysm-DDA#66444]
### Describe the bug

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            Tried to get cost timer of well_distributed but doesn't have this mutation.

 FUNCTION : time_duration Character::get_cost_timer(const trait_id&) const
 FILE     : src/mutation.cpp
 LINE     : 638
 VERSION  : 137c24d

### Attach save file

[Worthington-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11859316/Worthington-trimmed.tar.gz)

### Steps to reproduce

Wear an advanced nomad bodymesh advanced nomad jumpsuit and a nomad harness at the same time

### Expected behavior

To have the well distributed gear buff

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 137c24d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Im getting spammed every tick by a error causing lag its a easy workaround but fustrating

**Comment by bombasticSlacks** [comment]
I believe this was fixed 4 days ago #66364

**Comment by RenechCDDA** [comment]
This was already resolved, as noted. Please update to a newer experimental.
