### ISSUE TITLE
Completely broken translation (missing)

### ISSUE THREAD

**Issue by Getenari** [CleverRaven/Cataclysm-DDA#66440]
### Describe the bug

No translations at all except for English (in the experimental builds), downloaded the last two - when entering offers to choose only English, in the settings no other than English. mac os 10.15.7

ALSO it still worked correctly on build cbf5743

### Attach save file

no save file what it must be? 

### Steps to reproduce

please make translation

### Expected behavior

i except translation

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/46865750/725d161c-e69a-4ed6-966e-a9902a95cb67)

### Versions and configuration

mac os 10.15.7

### Additional context

- OS: MacOs
    - OS Version: Darwin Emils-MacBook-Air.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64
- Game Version: 00a5498 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by GuardianDll** [comment]
Do you download it using launcher? I recall they omit downloading all translations to increase the speed of updating, and only English + your system language are presented

**Comment by Getenari** [comment]
No, I downloaded it through the site where all the builds are posted. from this https://cataclysmdda.org/experimental/
вы говорите на русском?

**Comment by Getenari** [comment]
> Do you download it using launcher? I recall they omit downloading all translations to increase the speed of updating, and only English + your system language are presented

No, I downloaded it through the site where all the builds are posted. from this https://cataclysmdda.org/experimental/
вы говорите на русском?

**Comment by Getenari** [comment]
> Do you download it using launcher? I recall they omit downloading all translations to increase the speed of updating, and only English + your system language are presented

can i fix it somehow?
