### ISSUE TITLE
UPS_ON incorrectly transforms into UPS_off rather than UPS_OFF

### ISSUE THREAD

**Issue by NoddingCrow** [CleverRaven/Cataclysm-DDA#66453]
### Describe the bug

#66020 added the ability to turn UPS units on and off to stop them automatically draining dry while you're trying to disassemble everyones' smartphones.  
unfortunately, if you turn off an active UPS it no longer has an activation option! How strange! 

Had a quick look at electronics.json, and it seems it's a very understandable mixup between the classic UPS_off and the new and shiny UPS_OFF. 
Interestingly this doesn't *actually* brick the UPS, as the old classic UPS_off still has the IS_UPS flag so it still works! It just isn't *Off* like you'd expect. 

Anyway, trivial fix to anyone looking for an easy first contribution, line 766 of \data\json\items\tool\electronics.json
<3

### Attach save file

N/A

### Steps to reproduce

1) Spawn in or otherwise find a UPS_ON  ("UPS  (on)")
2) activate your UPS_ON, it now says "UPS" rather than "UPS (off)"
3) attempt to activate your "UPS", and see that "You can't do anything interesting with your UPS"! Oh no!

### Expected behavior

I expect items with an on-off switch to not suddenly lose their switch! 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 8ee94d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Ruminator24** [comment]
Oops, my bad. I was having trouble finding all of the old id's for the UPS item so i may have missed some, my bad
