### ISSUE TITLE
Removing an integrated pocket deletes its contents

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#66452]
### Describe the bug

If an integrated armor pocket (such as the Holdout Pocket from Bombastic Perks) is ever removed, the contents vanish rather than falling out onto the floor.

### Attach save file

N/A

### Steps to reproduce

1) Start a game with Bombastic Perks enabled.
2) Using the debug menu, grant yourself the Holdout Pocket mutation
3) Place something inside the holdout pocket
4) Remove the Holdout Pocket mutation
5) Item is completely gone.

### Expected behavior

Item falls on the floor, the way it does if an update changes a pocket size or possible contents. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 7871941 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Bombastic Perks [bombastic_perks]
]

### Additional context

I'm not sure this scenario can come up during normal play (maybe if you have a battery in an internal compartment and then ask Rubik to remove the internal battery CBM?), but I ran into it while working on Mind Over Matter

**Comment by RenechCDDA** [comment]
Confirmed it happens in the Rubik scenario.

**Comment by Standing-Storm** [comment]
Solved by #75565
