### ISSUE TITLE
3D iso vision fixes, please

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#66469]
### Describe the bug

Current implementation of 3d iso vision (#66383) lack of walls on the levels below. 
It makes transparent areas that confuses a bit. (orange marks)

Also some areas duplicates when on level above zero. (red marks)

### Attach save file

N/A

### Steps to reproduce

Climb on the roof of two-story building and select Ultica-ISO tileset.

### Expected behavior

It would be great if we can render all tiles connected to the visible or remembered.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6676374/992802f8-d007-4665-883c-c2fe7198eb49)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 4ad39d3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by vetall812** [comment]
BTW, thank you @Rewryte very much!

**Comment by vetall812** [comment]
I've added some brightness noise to the 'unknown' tile and now we can see rendered and really empty cells:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6676374/ceda4193-efcb-49f5-b28a-4ee76eff5d2d)

**Comment by Rewryte** [comment]
> Also some areas duplicates when on level above zero. (red marks)

Duplicate tiles might be a height_3d bug.  What tiles are those?

> Current implementation of 3d iso vision (#66383) lack of walls on the levels below.

My current idea is to make some tiles like `t_wall` exempt from occlusion culling, or maybe make a json flag for it.  I have yet to put it into code.  Have to fix map memory first.

**Comment by vetall812** [comment]
> > Also some areas duplicates when on level above zero. (red marks)
> 
> Duplicate tiles might be a height_3d bug. What tiles are those?

Almost any tile. Street lights, cars, pavement... Can't figure out the logic, sorry.

> > Current implementation of 3d iso vision (#66383) lack of walls on the levels below.
> 
> My current idea is to make some tiles like `t_wall` exempt from occlusion culling, or maybe make a json flag for it. I have yet to put it into code. Have to fix map memory first.

You may try connection group json property. It might help. 'walls' afaik.

**Comment by Qrox** [comment]
Just to mention that I'm currently working on a fix for this by adding an occlusion culling algorithm for isometric mode. It look good so far but there are a few rendering issues that still needs fixing, and I need to test its performance too.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/11890223/85bac0ad-9fac-4ba7-ae07-4bf0ca16234b)

**Comment by vetall812** [comment]
One of the possible solution to render walls on lower levels is to draw tile beneath when current tile have at least one neighbor t_open_air.

**Comment by Qrox** [comment]
I think that will work with the current way of only rendering the top visible tiles, but a proper occlusion culling method will be needed once we switch to rendering based on the tile's actual visibility. Anyway, it's a bit more complicated to make it fast than I had expected, and my fix also revealed several bugs in the code so I first need to clean up the rendering code before I continue working on it.
