### ISSUE TITLE
Felt, wool, and cotton balance

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#66467]
### Is your feature request related to a problem? Please describe.

I am always frustrated when trying to play innawoods with tailoring, due to the tool and component requirements.

Cotton / plant fiber section:
So much of tailoring is around cotton sheets.  You can make a 12in by 24in cotton sheet from a mere 50 thread, but to sew together a patchwork cotton sheet takes 8 cotton patches... and to make a cotton patch takes a rag, which is woven from 80 thread, or 80 plant fiber (or 80 thread, from a felt patch).  If someone has no thread and only has plant fiber, getting patchwork cotton takes forever.

Felt section:
There's no craftable felt sheet like there is for cotton sheet; one can only make a patchwork felt sheet.

Consider gambeson batting, which you can make with 1 wool staple, or 67 felt patches, or 200 yarn.  But it takes 20 wool staples to make 200 yarn, and 2.5 wool staples to make 67 felt patches.  I suppose this is somewhat explainable by density, but then consider a full wool beret, which takes 6 felt patches, meaning you can make 4 of them from 1 wool staple.  And then, you can turn 1 felt patch into 50 thread, but only with a spinning wheel, (which is not craftable)!  All of these things just don't seem to fit together in the same way that leather and fur seem straightforward from hides and pelts.

### Solution you would like.

Plant fiber -> "hemp" -> cotton substitute in most major "cotton" recipes.
Rework wool and felt

### Describe alternatives you have considered.

Greater yields of wool staple in butchering

**Comment by danielkwinsor** [comment]
Sorry, I didn't mean to say that I play with this innawoods mod.  I meant that is my play style.  I am not sure of how this mod might affect the recipes, but I'm playing on vanilla.

Some of those numbers sound good.  That kind of realism is what I'm looking for, but then also accounting for gameplay balance.  One point I'd like to express better is that I'm thinking of things in a survival situation, where this isn't going to be fine cotton, and where something like some hemp (plant fibers) seem suitable to mix in.  But I can't really make much clothing out of plant fibers.

**Comment by Krieger1999** [comment]
No one even mentions that Fiber cloth sheets just use 5 plant fiber in comparision to cotton, who uses 50 thread per sheet, even though both materials have the same volume and mass.
Why does no one sees this obvious issue.
