### ISSUE TITLE
Frog Mothers are extremely strong, arguably more dangerous than zombie hulks

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#66477]
### Is your feature request related to a problem? Please describe.

As of right now, Frog Mothers are extremely dangerous foes to face. They possess a health pool of 400, only 80 below a Skeletal Juggernaut's/Zombie Hulk's, but regenerate 40 hit points per turn, meaning that unless a skilled character is constantly hitting them hard with a strong weapon (such as a halberd or tempered nodachi), they will outlast a character and likely kill them through sheer attrition. This is made worse by the fact they have the ability to grab and pull the player from up to 4 tiles away and summon 5 Tadpole Constrictors close or right next to the player (even from a distance), each of which can grab the player and leave behind pools of acid when they die. Considering the changes made to grabs, this makes even facing a lone Frog Mother extremely dangerous - arguably more dangerous than a skeletal juggernaut or hulk.

This combined with a Frog Mother's ability to leap (despite a flavor text describing it as having "small, stubby legs with no feet") makes even getting away from one extremely difficult.

Frog mothers also currently evolve from Zombullfrogs with a half-life of 34 days. Compare this to a normal zombie evolving into a zombie hulk - they must first evolve into a zombie brute with a half-life of 30 days (which may not happen considering the wide number of evolutions a zombie can have), which then evolves into a zombie hulk with a half-life of 42 days (which, again, is not guaranteed because the brute can evolve into a number of other things, including itself).

Frog mothers also do not bleed. In testing I hit one with a zweihander multiple times only for it to have no effect at all on its health or bleeding status - unless one consistently hits it for over 40 points each turn (and ideally far more than that), it will not die. A lack of bleeding seems to be a trait common to a variety of higher-level monsters, but in this instance, the inability to bleed makes the frog mother even harder to kill.

https://cdn.discordapp.com/attachments/598523535169945607/1122907024267685970/image.png
https://cdn.discordapp.com/attachments/598523535169945607/1122907110607425699/image.png

Frog mothers also appear to be faster than the player by default, despite being listed as having a speed of 60 on the Hitchhiker's Guide. In my testing, it even began to flee - which, combined with its very fast regeneration, meant my character's attacks had no effect, despite dealing triple-digit damage earlier (see screenshots above)

All this makes frog mothers both somewhat common and extremely unpleasant to fight at all, arguably more dangerous than hulks and juggernauts. The same overpowered character I used for the above screenshots was able to kill a zombie hulk with only a few strikes of a tempered nodachi and the Niten Ichi-Ryu style, and they took relatively little damage in doing so (which likely would've been even less if they were wearing armor).

To summarize/TL;DR: A zombie *hulk* is easier for an OP character to kill than a frog mother because the frog mother regenerates HP extremely quickly, can flee, and has a number of abilities to slow the rate at which a character can damage it (such as grabbing from a distance and spawning enemies that can also grab the player).

I can only assume a non-OP character stands next to no chance of killing a frog mother.

This does not seem right to me.

### Solution you would like.

**Reduce the rate at which Frog Mothers regenerate HP.**

I believe this is the most important change to make. I'm not very familiar with regenerating monsters or what's considered an acceptable rate of monster regeneration, but 40 seems a bit much considering it takes some very dangerous weapons and considerable skill to deal more than 40 HP in a single strike. My first instinct for a number is 15 hp/turn, but lower might be better. For reference, pupating zombies regenerate 10 hp/turn, and a miracle lurker restores 12 hp/turn. Sludge crawlers and shoggoths also restore 50 HP/turn, but those are mutants and some kind of cosmic entity, not zombies (I also think 50 hp/turn is a bit much, especially combined with high armor, but that's not relevant to this discussion). I'm unsure what other monsters regenerate HP to make a good yardstick for regen, so if I've missed an example, please let me know.

**Reduce the amount of HP Frog Mothers have.**

Not nearly as important as reducing their regen, but it may help.
Again, as of right now their health is only about 80 points below a juggernaut or hulk's, but their regen means their health is effectively much greater unless the player can either reliably deal over 40 points of damage per second or hit for over 400 in a single go). In order for this change to be effective, I suggest combining this with reducing the frog mother's HP regeneration in order to make them far less durable.

**Remove the Frog Mother's ability to leap.**

This won't help the issue of the Frog Mother's extreme durability, but it will at least make getting away from one easier.
The flavor text for the Frog Mother reads (emphasis mine):
A large, bulbous creature with an extremely large mouth and ***small, stubby legs with no feet***. Drenched in an oily greenish-black substance, its flesh seems to rapidly decompose and reconstitute itself, and it is covered in large, white pustules that seem ready to pop.

Unless these legs are far stronger than they appear (and able to launch off like a frog's despite a lack of feet), I don't understand why frog mothers have the ability to leap.

**Allow Frog Mothers to bleed**

Again, this probably won't help the issue of extreme durability (even Heavy Arterial bleeding takes at least three or four turns to kill a standard zombie that's already heavily injured), but combining it with the other changes listed here should help somewhat.
Other zombies and zombified creatures can bleed. Unless the ability to regenerate HP means a creature is completely unable to suffer bleeding wounds (which I'd say is nonsense since those wounds can still be made and still take some time to heal), these upgraded zombie frogs should be able to, as well. This change should probably also be made to other high-level zombies as well (In my brief testing with a zombie hulk and an intentionally overpowered character, dealing 60 and 70 HP of damage with a tempered nodachi did not cause it to bleed).

**Make evolution of zombullfrogs into frog mothers much slower**

Won't make existing frog mothers weaker, but will mean there are far fewer of them in future.
As stated before, an ordinary zombie has a half-life of 30 days to evolve into a Zombie Brute, and a further 34 day half-life to evolve into a zombie hulk - and these may not happen considering the wide variety of other possible evolutions a zombie can have. Contrast with the zombie bullfrog, which only has the frog mother as an evolution and evolves into one with a half-life of 34 days. Assuming an equal number of zombies and zombullfrogs, this would therefore mean a greater number of frog mothers would be present after a month than zombie hulks after an equal amount of time.

### Describe alternatives you have considered.

Removing frog mothers entirely and replacing them with a different upgraded zombull frog?

Never picking fights with frog mothers ever (which means never going into places they can appear, such as swamps and sewers)?

**Comment by NetSysFire** [comment]
I am slapping good first issue on this since the actual thing is easy to adjust.

I agree with all of the points so far and especially the leap ability seems to be an oversight. 
Also being able to change the regeneration rate of a creature would help here, too.

By the way, great writeup, thank you for putting so much thought into this.

**Comment by KHeket** [comment]
> On the contrary, a character with few skills is easily capable of killing one given a full magazine of ammunition and a rifle.

Try this in the game. And if you dont have minigun 308 and 500 bullets - you will die. You are the guy, which said, that acid bear is much more dangerous than frog mother, when in game you can easily kill acid bear
<details>
  <summary>Spoiler</summary>

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/28bb639e-fc7b-422b-987d-d6f7f3925383)

</details>
I dunno what is your point to so activily save this unbalanced creature, but stop it please. Lots of people reasonable proved, that frog mother should be nerfed/rewoked/obsoleted

There is also one mine issue about it https://github.com/CleverRaven/Cataclysm-DDA/issues/65438#issuecomment-1580671362 (which I will close now, to prevent this good issue from closin) and pr [65702](https://github.com/CleverRaven/Cataclysm-DDA/pull/65702) with lots of debates about frog mother, but I am too tied debate with this guys, which just dont want to listen to others and dont want to reach a consensus

**Comment by fairyarmadillo** [comment]
The open PR #65702 will address many of the issues in question by making the creature less common and removing its intelligence without compromising its intended difficulty. At that point you'll see them less often and they'll walk into traps and fire, which should make them less of a hassle.

**Comment by AzyWng** [comment]
While I'm grateful for the open PR's changes, my primary issue is the fact the frog mother regenerates 40 hp each turn. If that were removed or even merely reduced, I don't think it would be nearly as dangerous as a zombie hulk (my brief testing suggests the hulk can deal more damage due to its ability to smash, scratch, and bite the player - though the Hitchhiker's guide lists the zombie hulk's basic attack as 4d8+0 bash [anywhere between 4 and 32 damage], and the frog mother's as 5d6+5 bash [anywhere between 10 and 41 damage).

Again, my testing with a fairly skilled 10/10/10/10 character and a high-grade weapon had me dealing triple-digit damage several times only for the frog mother's regeneration to outheal those attacks.

I'll admit that I hadn't tested attempts to outrun a frog mother. I also wasn't aware that zombullfrogs were relatively rare to begin with, and I'm not as familiar with places where zombullfrogs might spawn.

I don't use guns often enough to know what kind of rifle and ammo is capable of killing a frog mother, and with the changes that have been made to aiming (with lower skills appearing to penalize both aim time and aim effectiveness), I believe even a highly skilled survivor may have difficulty outshooting a frog mother's regeneration. Again, I'm rather unfamiliar with guns and ammo, so a more knowledgeable opinion would be welcome.

**Comment by RenechCDDA** [comment]
I understand you are using the zombie hulk as a benchmark, but is there any particular reason why their relative strength shouldn't be independent of zombie hulks? It's okay if they're stronger. It's okay if they're weaker. They're... their own thing. They are very dangerous. This is intentional and *desired*. The strongest enemies should be dangerous, even to a late-game survivor. This is a cataclysm! The exodii aren't leaving high-evolution worlds because the enemies die easily, they're leaving because the enemies *don't die easily.*

> Again, my testing with a fairly skilled 10/10/10/10 character and a high-grade weapon had me dealing triple-digit damage several times only for the frog mother's regeneration to outheal those attacks.

As you've pointed out, their regeneration is per-turn. Dealing 100+ damage in four turns is worse than dealing 50 damage in one turn.

> I don't use guns often enough to know what kind of rifle and ammo is capable of killing a frog mother, and with the changes that have been made to aiming (with lower skills appearing to penalize both aim time and aim effectiveness), I believe even a highly skilled survivor may have difficulty outshooting a frog mother's regeneration. Again, I'm rather unfamiliar with guns and ammo, so a more knowledgeable opinion would be welcome.

I admit to not having fought any/used any guns since #66347 was merged, but any rifle firing in burst or fully automatic will make swiss cheese of them, as you simply do many times more damage than melee. Even a semi-automatic rifle will do fine as long as you keep using the lower aim levels.

This remains true across all common ammo types, the only time it wouldn't be true is *maybe* something like the cx4 storm or other "pistol-caliber carbines" which are technically "rifles" but fire handgun rounds.

**Comment by NetSysFire** [comment]
Since there is an open PR, I removed good first issue. The only other thing that remains is that the regeneration rate appears to be hardcoded and not really configurable per monster.

**Comment by RenechCDDA** [comment]
> Since there is an open PR, I removed good first issue. The only other thing that remains is that the regeneration rate appears to be hardcoded and not really configurable per monster.

It appears to be a json set value?
https://github.com/CleverRaven/Cataclysm-DDA/blob/f13d34ade880ad7b8f291a7e7dbd6103e6b86f4e/data/json/monsters/zed_misc.json#L40

https://github.com/CleverRaven/Cataclysm-DDA/blob/04770e3d51dbc14a4ea5c0f13362f3bdde37e3c6/doc/MONSTERS.md?plain=1#L72

**Comment by NetSysFire** [comment]
Ah, thanks for clarifying. I missed that one. Everything should be set now.

**Comment by AzyWng** [comment]
> It's okay if they're stronger. It's okay if they're weaker. They're... their own thing. They are very dangerous. This is intentional and desired.

In that case, I suppose I don't have much right to argue for making any changes to them at all. Which I guess would mean I should close this issue (especially considering there's one already open relating to this)?

> As you've pointed out, their regeneration is per-turn. Dealing 100+ damage in four turns is worse than dealing 50 damage in one turn.

You've got a point. I hadn't taken that into account the time it took for my character to land those 100+ damage blows (the nodachi takes 166 moves to swing, which will only get slower and slower as pain and stamina loss take their toll).

A few tests with my OP character build (OP for a starting character, at least) managed to get the frog mother down to one or two pips of health before it started fleeing. (I tested twice with 5.56 rifles and once with a Cobray Streetsweeper). From there the fact the frog began fleeing and that their weapon ran out of ammo (I was using 30-round magazines for the rifles) meant they struggled to land a killing shot even with precise aim, and that allowed the frog mother to regenerate... basically all of its HP. It's entirely possible a more skilled character using a more powerful weapon, or perhaps one modified for better accuracy/faster aim times/less recoil would be able to kill it.

The tadpole constrictors do seem to make the frog mother harder to kill with guns at close range, as while trying to focus on it, the tadpoles repeatedly grabbed my character and caused them to drop their rifle a few times.

Here's my character's stats and skills. I also used this for testing melee versus a zombie hulk and the frog mother. Again, while this is "overpowered" for a starting character, I can definitely see characters with greater skills and equipment being able to kill a frog mother.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45751345/fb929d18-8efa-4660-ba17-c7f58eec910d)

**Comment by CatWithFourEyes** [comment]
> A few tests with my OP character build (OP for a starting character, at least) managed to get the frog mother down to one or two pips of health before it started fleeing.

Not sure, that this ranged skill levels is adequate for even mid-game character, not speaking about lategame ones. And 5.56 is not so good at taking down late game "big bad things", .308  (like M14 EBR/SCAR-H) is much more appropriate for this task. Also, many ranged characters would use a grenades/molotov for backup. 
Only problem with Frog Mothers, i think, that they are too smart, and starting to flee to regenerate, for "undead" enemy.

**Comment by Nebnis** [comment]
I have tried to balance the monster in my #65702 and the summary of the consensus there were that it is okay for the frog mother to require specialized weaponry to be killed, aka no melee. The main issue i found was that frogs spawn everywhere now outside swamps, and since bullfrogs pick a fight with anything, they will all turn into frog mothers eventually. So i think it was agreeded that they are too common, so the PR remove their fear of fire and makes them a bit more rare by adding another monster that should be still hard but not at level of frog mother. I did quite a bit of testing with the monster.

**Comment by TheSaddestGoomba** [comment]
This might be a bit late/ancillary to the conversation but I have been laying out some notes for a big Amphibian Additions PR.
One of the concepts is a new frog zombie variant called a Frog Jockey that would also implement some changes to Frog Mothers. Idea being that they themselves are weaker than zombullfrogs but are more nimble and harassment focused. Their real unique feature is being 'absorbed' by Frog Mothers for buffs to their health, healing and tadpole spawning. The idea being that they fuse onto the momma like anglerfish do.
This would hopefully be neither a straight nerf nor buff to Frog Moms but rather add nuance and variability. The Moms would  become less common by virtue of diluting their spawn rate with the Jock's. The balance will need significant work but may justify some nerfs to base Frog Moms, while allowing them to reach or exceed previous limits through "fusing" new mates.

**Comment by KHeket** [comment]
> Not sure, that this ranged skill levels is adequate for even mid-game character,

Its quite good range skill level even for late game character, because of very low ammo density in the game. You cant always use gun like gunsmith character because you will fast run out of ammo


> And 5.56 is not so good at taking down late game "big bad things"

Big bad thing is kevlar hulk and hulk, both can be killed by 5.56, and both much more easir than frog mather, or mutants in the labs, like shoggot or mutant with shell, both are have special locations

I wonder about you guys. You are crying about realism all the way, but when somebody create unbalanced creauteres and others want to fix it - you dont want to do it. How do imagine creature, which will fully regenerate from 1% to 100% for a few seconds? Did you watching too much X-men with wolverine? In reality or non **magic** universities you need energy for regeneration, you need material, you cant, even if you mutant from another water, air, energy or some substance. 
**You cant make flash from air**
But frog mother do. And frog mother is the simular creature like zombies, deers etc
How can you scientifically even in sci-fi cataclysm reality explain such fast regeneration?

**Comment by NetSysFire** [comment]
The default answer for everything lacking in lore is "the blob". But that is no excuse to create unbalanced creatures or absurd things that simply do not make sense and so far it looks like more people are in favor for balancing it than people against performing these changes.

**Comment by KHeket** [comment]
> The default answer for everything lacking in lore is "the blob"

If it is not in magic world, and vanila cata dont have magic(without mod) - so blob is a creature/bacteria/something from another planet/universe coming through portals. And if portals theoretically possible - creature, which will recombinate body to make its regenerate as god - not. It is okay for common creature. It is good for boss, like kraken, shoggot, both you can meet anly in labs/blob pits/kraken caverns, but when this creatures can randomly find you somewhere - is bad

Best idea is to make speacial location like "Frog mother egg pit", simular to caves, where frog mother will lay eggs to spawn froggies. And all will be happy. Most players will not met randomly this unbalanced creature in field, and frog mamma lovers will have their loved unbalanced creature in game

**Comment by KHeket** [comment]
Is the 88 spring good for this creature? Is the ability to breaking walls and spawning tadpoles through the window bars are good?

<details>
  <summary>HOLY COW IT IS THE FROGGY GOD SLAYER</summary>
  
![Снимок экрана (213)](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/60d8a288-144c-49a2-8228-0a4071cfcfc1)
![Снимок экрана (214)](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/1908f559-ed31-4d11-ac92-3db7752c4690)
![Снимок экрана (215)](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/ec31ac23-230a-47e3-9d25-b68d55045e3e)

</details>

 No? May be spawning tadpoles through the reinforced glass is imbalance or ? I dont know

<details>
  <summary>One more imbalance thing of this imbalanced creature</summary>
  
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/e1f0dfc6-0d98-4f19-8a56-98983ae4bbd8)

  
</details>

I dont know, do the guys, which are in love with frog mother, playing the game, but as a very lot cdda player I still understand, that this creature is fully unbalanced and its speed, speed of tadpoles, regeneration should be nerfed
