### ISSUE TITLE
Noisemaker CBM (non-faulty)

### ISSUE THREAD

**Issue by QuafflesV** [CleverRaven/Cataclysm-DDA#66489]
### Is your feature request related to a problem? Please describe.

Intentionally making noise to attract hostiles to your position is sometimes a valid tactic. Various tools can fulfill this role, including the whistle, noise emitter, compressed air horn, and car horn. These each have their own drawbacks: low noise volume, high bulk, being consumable, and being attached to a vehicle. A Noisemaker CBM exists, but it is a malfunctioning CBM that emits noise randomly.

### Solution you would like.

A functional Noisemaker CBM that produces a loud noise on activation (similar to whistle or air horn) would be a neat utility CBM.

### Describe alternatives you have considered.

A CBM that produces a continuous loud noise (or siren) similar to the noise emitter, or provides an option for both continuous and on-activation noise.

**Comment by sadenar** [comment]
Perhaps a voice amplifier that allows you to shout extra loud/be more intimidating?
