### ISSUE TITLE
Array out of bounds in `pl_sees`

### ISSUE THREAD

**Issue by akrieger** [CleverRaven/Cataclysm-DDA#66480]
### Describe the bug

Used 'play now' option to create a new game. Hit this debug assertion.

`map_cache.lm[player_character.posx()]` returns an array of size 132. `player_character.posy()` is 1796, waaay out of range.

### Attach save file

[Tallaboa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11872772/Tallaboa.zip)

Save has no characters, try creating a random character but use that world to start in.

### Steps to reproduce

In MSVC debug build, use 'play now' to create a new game.

### Expected behavior

Doesn't debug assert.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/091feb45-403b-49bd-a13a-b84b155534ec)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/0c106203-5c45-4282-bbf4-c5def8bcfc0b)

### Versions and configuration

Win 10 64 bit f13d34ade880ad7b8f291a7e7dbd6103e6b86f4e

**Comment by RenechCDDA** [comment]
I believe this is a dupe of #66427

**Comment by akrieger** [comment]
Perhaps, but mine has more debug information and a stack trace :)

**Comment by akrieger** [comment]
Yep that's the right one and #66431 fixes.
