### ISSUE TITLE
Request to Add Outdoor Garbage Can's to the game.

### ISSUE THREAD

**Issue by ChadSanchez** [CleverRaven/Cataclysm-DDA#66492]
### Is your feature request related to a problem? Please describe.

Add Outdoor Plastic Garbage Can's in front of about 25% of Suburban Houses. Most Homes in America/ New England participate in a system where Garbage collectors will come and take away their trash so long as they place their trash in designated plastic bins out in front of their house.

Adding in Plastic Garbage can's in sizes that vary between that of 32 Gallons, 64 Gallons, and 96 Gallons. would ultimately lead to the game being more realistic.

### Solution you would like.

In my head, The ideal implementation of outdoor Garbage can's would be to act as a worse version of a shopping cart that sits in front of nearly every suburban house.

Loot the house and then just stick everything in their Garbage can. Then move on to the next house, rinse and repeat until your done looting.

Then just drag all the Garbage can's back to your base.

If you use Zone manager to just dump everything in the can's then you will quickly become the Horder King.

### Describe alternatives you have considered.

If making the Garbage bins some kind of plastic vehicle is too difficult. Then simply making them large plastic rigid containers that size in 32, 64, and 96 gallons.

Since the Garbage bins would now be a type of item container. You could possibly make them spawn in as dirty, and you might have to clean them before you could store certain items in them.

### Additional context

I just found it kind of unrealistic that Garbage bins weren't in front of like a quarter of houses.

Here is a set of pictures depicting what Garbage bins look like.

https://imgur.com/a/sSfOcmr

**Comment by RenechCDDA** [comment]
Many cities/counties/municipalities also provide recycling bins to residents, to encourage their use. (See https://spectrumnews1.com/ma/worcester/news/2022/01/13/new-recycling-bins-worcester-with-lids-deliveries for example).

Recycling services tend to be run side-by-side with trash services, picking up on the same day(s).
