### ISSUE TITLE
A project for an old lab removal checklist

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66491]
### Is your feature request related to a problem? Please describe.

Yeeting old labs has been on the tables for a long time, I'd like to help hasten their full removal so new non hardcoded stuff can occur

### Solution you would like.

A checklist of everything blocking old lab removal potentially with a category for stuff that wouldn't block removal but that would like to be moved.

From a quick discussion in the lore channel on the devcord a couple of things are:
The CVD and nanofab want moving nanofab being a blocker, CVD potentially not, both could be accessible through the hub physically or through dialogue.
Refugee centre doc quest that sends you to labs

I'll start digging into these to see if I can handle them.

### Describe alternatives you have considered.

Maintaining an open issue on this myself but as I'm not a senior dev nor know much about the plans or history that doesn't make much sense.

**Comment by fairyarmadillo** [comment]
These issues aren't necessarily blockers, but we should consider them:

* There aren't other places to find CBMs other than Rubik. We need more exodii sites.
* The prototype cyborg enemy likewise needs a new home. It'd probably do better as another faction's attempts to reverse-engineer the exodii. I could see the Hell's Raiders testing cybernetics on their prisoners. Hub-01 too, though I don't think they have the means, and they also don't come across as pointlessly cruel, more just cold and calculating.
* There are probably a couple of finale-only items that would get essentially obsoleted. If these can all appear in lab tower finales then it's probably fine.
* We may want to turn lab towers up a tiny bit.
* CVD could be moved to the Research Center, or placed in non-mutagen labs (the regular kind). It's the most believable out of the super-science devices and sticking it in a chemistry lab seems reasonable to me.

**Comment by kilozombie** [comment]
Old labs are the only place I know of to find teleporter traps, a.k.a. the only good place to find teleporters for Magiclysm.

**Comment by KHeket** [comment]
New labs dont have microcentrifuge with computer, which are needed for doctor quest from refuge center and also microcentrifuge is good sourse of accumulators and betavoltaic batteries

**Comment by Procyonae** [comment]
Maleclypse opened one 🎉 https://github.com/orgs/CleverRaven/projects/16/views/1
I'll open issues with the individual points to add to it soon
