### ISSUE TITLE
I get messages about mobs breaking grabs while not seeing them

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66519]
### Describe the bug

The messages for mobs breaking grabs does not check if the player sees them before being printed into the chat log.

### Attach save file

n/a

### Steps to reproduce

1. Teleport above a physics lab at z=0.
2. observe messages from zombies down below.

### Expected behavior

run the check for if the player sees it.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56016372/885553f9-6285-46a0-bc8b-1095663c982d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 9a44ac7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

**Comment by Venera3** [comment]
Oops.
It's a straightforward `add_msg->add_msg_if_player_sees` change, I'll get to it if nobody bites.

**Comment by aschuhardt** [comment]
I'd like to take this one as my bug-fix here.
