### ISSUE TITLE
Senior citizen age is randomized which can result in hilariously young characters.

### ISSUE THREAD

**Issue by Elshad19** [CleverRaven/Cataclysm-DDA#66521]
### Describe the bug

This is probably a design problem rather than bug and it is pretty self-explanatory. Here in this screenshot, my senior citizen character is 18 years old. I don't know how retirement works abroad, but here you can only retire after age of 65 (this changes according to your job).

### Attach save file

None

### Steps to reproduce

I did randomized start (Play now!). So, I guess you need to choose particular scenario.

### Expected behavior

Age should be appropriately determined according to realistic standards.

### Screenshots

![IMG_20230629_133004](https://github.com/CleverRaven/Cataclysm-DDA/assets/87479123/e20db553-cc0a-4867-a3b2-0ef11f626aa1)

### Versions and configuration

I play on mobile and I use the experimental build from couple days ago.

**Comment by ZhilkinSerg** [comment]
Age for that profession should be set through EOC on scenario start (though there is no dialogue effect for that - one could be added).

**Comment by Procyonae** [comment]
Duplicate of #59511
