### ISSUE TITLE
Magiclysm: Activating non-empty endless teapot causes the error

### ISSUE THREAD

**Issue by Demivan** [CleverRaven/Cataclysm-DDA#66524]
### Describe the bug

```
 DEBUG    : tried to put an item (tea_green) count (2) in a container (mteapot) that cannot contain it: pocket unacceptable because not enough space

 FUNCTION : ret_val<void> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1574
 VERSION  : f13d34a
```

### Attach save file

N/A

### Steps to reproduce

1. Activate non-empty endless teapot
2. Get an error

### Expected behavior

Teapot should fill up and not cause an error

### Screenshots

![screenshot_2023-06-29_14-21-38_925729488](https://github.com/CleverRaven/Cataclysm-DDA/assets/2339406/e16c0c3b-bbdd-4b91-ac1c-3e3c91ddebf9)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: f13d34a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Magiclysm [magiclysm]
]

**Comment by RenechCDDA** [comment]
Simple fix json:

```
  {
    "id": "mteapot",
    "type": "GENERIC",
    "copy-from": "teapot",
    "category": "tools",
    "name": { "str": "endless teapot" },
    "description": "A small metal teapot.  Teatime wouldn't be complete without one.",
    "price_postapoc": "2500 USD",
    "use_action": {
      "target": "tea_green",
      "msg": "You check the teapot and discover it full of sweet tea!  Sadly, it's cold.",
      "container": "mteapot",
      "target_charges": 2,
      "need_empty": true,
      "moves": 50,
      "type": "transform"
    }
  }
```

(removal of unused relic_data, addition of need_empty to use_action)
Endless flask needs this applied too.

`need_empty` needs to be documented in json_info.md.

`sealed` `qualities_needed` and `target_ammo` are not relevant here but also lacking documentation.

**Comment by Demivan** [comment]
Should it be `need_empty`? That would mean that you cannot activate it. It would work, but feels like a less elegant solution.
I think instead of adding 2 `tea_green` it should set it to 2. `target_charges` says that it is "Number of charges the transformed item has", but looks like this is not what is happening.
