### ISSUE TITLE
Heat/cold tolerance and homeostasis interactions.

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#66539]
### Describe the bug

Cold-blooded cancels cold-tolerance, and cold and heat tolerance are mutually exclusive. This is not how nature works.

Cold and heat tolerance mutations in the game have nothing to do with speed, they're only about damage. The assumption that all cold-blooded creatures are injured by cold weather is false.

* Many ectothermic organisms, such as alligators, fish, crustaceans, frogs, insects, spiders, and some plants can survive in temperatures far below what would kill a human. In some cases, these animals become sluggish or totally dormant during the cold season, but their biology protects them to varying degrees from temperatures which would give humans frostbite or hypothermia. Alligators spend all winter sleeping in frozen ponds. Fish have antifreeze in their blood and crabs can just kind of sit on the bottom of the ocean and wait for warmer weather if the water's too cold. You can put many insects in the freezer and they'll just fall asleep without coming to harm. There are many trees that live in boreal forests etc.

* Many organisms are both heat and cold tolerant, including tardigrades, camels, some plants, insects, and likely others I can't name off the top of my head.

* Mutants tend to have integrated armor that makes keeping warm difficult for them. It is not always appropriate to simply assign warmth values to their armor. An insect doesn't have a warm shell nor an endothermic metabolism to warm itself, it's just got special anatomy for avoiding injury from extreme cold.

### Attach save file

N/A

### Steps to reproduce

Try to have both heat and cold tolerance, try to be cold-blooded with cold tolerance.

### Expected behavior

Heat and cold tolerance should not be mutually exclusive, and should have no interaction with any of the endo/ectothermic mutations.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: ce2aa59 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

There has been some discussion of introducing special unique mutations to IE Plant to make it able to be cold tolerant and cold-blooded, but you'd have to make an individual unique mutation for nearly all of the cold-blooded mutants, and it would still run into more edge cases than just removing the bad restriction. I also don't see what unwanted circumstance this would be avoiding.

**Comment by anoobindisguise** [comment]
On the contrary cold tolerance has EVERYTHING to do with speed and very little to do with damage. It affects how likely you are to get a speed debuff from Chilly or Cold status effects and it affects how much of a speed malus you get from Cold Bloodedness (It is the same enchantment as climate controlled armor) 
My gut instinct to resolve this is to keep the mutual exclusivity between cold tolerance and heat dependence and then introduce a post threshold mutation to most cold blooded mutants that makes them immune to damage from freezing.

**Comment by fairyarmadillo** [comment]
My mistake, I didn't realize the tolerance mutations were using the climate control system. Now I'm not sure what to do.
