### ISSUE TITLE
Change the strings “K mass” and “K dynamics” to be more understandable

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#6653]
From what I heard from the forums, most people seem to have no clue what the strings “K mass” and “K dynamics” mean. Those strings appear in the vehicle menu.

The answer to this is in vehicle.h:
```
// Combined coefficient of aerodynamic and wheel friction resistance of vehicle, 0-1.0.
// 1.0 means it's ideal form and have no resistance at all. 0 -- it won't move
    float k_dynamics ();

// Coefficient of mass, 0-1.0.
// 1.0 means mass won't slow vehicle at all, 0 - it won't move
    float k_mass ();
```

However, I doubt not many players would look into the source code to discover what those two strings mean.

I therefore suggest to change the strings “K mass” and “K dynamics” to something more meaningful, something which could be understood more intuitively.

My suggestion for “K mass”: “mass coefficient”. This should be obvious. The coefficient of mass is the mass coefficient.
And for “K dynamics”: “friction coefficient”. Well, it could be understood as wheel friction on the floor and on (kinda) “friction with the air” aka aerodynamics.

Other suggestions are welcome.

**Comment by slitherrr** [comment]
I disagree that "correctness" is the approach to take, as much as "understandability". I would advocate the same if "clean water" were described as "trace minerals dissolved in dihydrogen monoxide"--the latter is correct, arguably *more* correct than the former, but it is not the better user interface.

It's possible that what is being presented isn't really what needs to be presented--even if you know what the numbers mean, you only really know that you want them closer to 1.0. I would suggest presenting more interesting derivatives, like "Fuel consumed per unit distance (at a reasonable speed, or possibly at a couple of speeds)" and "Turns added when dragged".

**Comment by KA101** [comment]
Issue: there's only so much space on the screen, so prefer to keep these brief if possible.

**Comment by slitherrr** [comment]
There's probably some brainstorming there. "Fuel Efficiency" and "Drag Encumbrance"? Do you know how much space there is to work with, exactly?

I would hope that those names matter less than that they present units that are actually meaningful in a game context, like "units of gasoline to go 50 squares at 48 km/h", so there's no problem not being long-winded as long as the number has some basis in the in-game world (and the units with the number can hint at that, too).

**Comment by drbig** [comment]
Seeing that this issue is a year old - what about just removing the "K mass" and "K dynamics", given they are confusing and nobody seems to actually pay any attention to them?

**Comment by Wuzzy2** [comment]
The information can still be useful. IF the player understands it. This is the problem.
I am against removing. The age of this issue is not a valid argument IMO.
