### ISSUE TITLE
Fiber cloth sheets use 10 times less materials, than regular cotton ones!

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#66543]
### Describe the bug

The Fiber cloth sheet from the innawoods mod, does use plant fiber, which has the same value as regular thread, but still uses 10 times less plant fiber, than cotton sheets uses thread.

### Attach save file

![Fibercloth sheet 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/7cef59a2-6dbc-4f97-8233-3bf98405c467)
![fibercloth sheet 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/c71319e4-fd23-4c6a-8c4a-aeee674f81ec)
![fiber 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/4df38c21-b13c-417b-9668-3b46e2c9ffcb)
![fiber 4](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/4eb001af-d908-4121-b50a-4c63bcfbd049)

### Steps
 to reproduce

Just look at the crafting menu und Fiber cloth sheet in innawoods and compare tít with the cotton sheet.
Also look at plant fiber and thread and see that they use the same volume and mass.

### Expected behavior

The Fiber cloth sheet should also use 50 plant fiber, like the cotton sheet uses 50 thead.

### Versions and configuration

Windows 10
Version: 83224ec (tiles)
Build: 2023-06-30-0603 (5 hours ago)
mods: Innawoods, Dark days ahead

**Comment by anoobindisguise** [comment]
I'm aleady working on this stuff. Thread weights are wrong in general (by weight it takes 4800ish thread to weave a sheet) but I'm reworking plant fiber to represent specifically stuff like hemp that's strong enough to mimic cotton. Withered plants would be the shitty stuff you find lying around everywhere which wouldn't be useful for much.

**Comment by fairyarmadillo** [comment]
> I'm aleady working on this stuff. Thread weights are wrong in general (by weight it takes 4800ish thread to weave a sheet) but I'm reworking plant fiber to represent specifically stuff like hemp that's strong enough to mimic cotton. Withered plants would be the shitty stuff you find lying around everywhere which wouldn't be useful for much.

I hope you're not axing withered plants for cordage. The amount of stuff you can twist into cord is pretty wild and I think we should definitely err on the side of generosity there.
