### ISSUE TITLE
Hub01 Not always generating via FEMA data mission 

### ISSUE THREAD

**Issue by RanikOrtega** [CleverRaven/Cataclysm-DDA#66555]
### Describe the bug

On Latest experimental when speaking to smokes about the FEMA data mission. The messages that you are marking the location down will display as normal but it seems like 50% of the time no actual location will be added on map or in journal. 

![CCDA-Fema](https://github.com/CleverRaven/Cataclysm-DDA/assets/14862800/05ec7211-9e10-46ac-b001-4567a82f25c8)

 

### Attach save file

N/A

### Steps to reproduce

Generate world. 
Teleport to Refugee center. 
Speak with Smokes and ask about other locations to start Unknown Recipient mission

### Expected behavior

Smokes dialogue for Unknown recipient should generate the Hub01 location or mark it's location. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 83224ec [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by gettingusedto** [comment]
it's also the case for the exodii mission about checking out the hub.

**Comment by anoobindisguise** [comment]
search radius likely needs to be expanded.
