### ISSUE TITLE
Consume (E) and other commands no longer show the location of the item around you.

### ISSUE THREAD

**Issue by teapot156** [CleverRaven/Cataclysm-DDA#66565]
### Describe the bug

Previously, trying to use the "E" consume command used to show the location of the consumable items around you. This no longer functions and instead a huge consolidated list appears with no indication whether or not the item is to your west, northwest, etc. Please restore this function.

### Attach save file

N/A

### Steps to reproduce

Place a cooked meat to your west and another one to your east and hit "E" (consume). The two cooked meats will be separate listings in a merged list with no indication which one you're eating. 

### Expected behavior

I expect to know whether or not I'm eating the cooked meat to my left and not the one "in my inventory or on my display rack to my right", hypothetically speaking.

### Versions and configuration

93d1f4a (tiles)
2023-06-29-1423 (a day ago)
Windows x64 / experimental

**Comment by RenechCDDA** [comment]
Not a bug.

**Comment by andrei8l** [comment]
Press `;` to switch to hierarchy mode and you'll see them separated by location
