### ISSUE TITLE
Autodrive will not work

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#66576]
### Describe the bug

Autodrive won't work no matter where I set it go. I keep getting the message that says ``can't see the path forward``

### Attach save file

[TrailBalls-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11925546/TrailBalls-trimmed.tar.gz)

### Steps to reproduce

1. When you boot up the save, you'll already be in a moving vehicle
2. Open the map and autodrive anywhere. I was trying to repeatedly go to the basecamp to the east
3. Cry at the repeated ``can't see the path forward`` messages

### Expected behavior

I expect autodrive to work. May I add, although I last played on this save at the end of May, it did work with the exact same vehicle on the exact same path, so this is not an issue with the vehicle or save but with the code.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 9afa65c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Procyonae** [comment]
/confirm Tested on latest stable, tried moving around a lil bit but still nothing

**Comment by Karol1223** [comment]
So uh... works on the newest experimentals, now. I have no idea what fixed it. But it works... so I guess I'm closing this?
