### ISSUE TITLE
Monsters can see proportional further in the Weather "fog", compared to the Players vision, which just gets worse!

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#66586]
### Describe the bug

The current Weather "fog" allowes monters, to have proportional more vision, than the Player Charackter, even though both should be evenly affected, by the Fog or weather in general.
Example;
A Woodland wight can see over 40 tiles in clear weather and at ca. 11.00 a.m., while the Player can see over 60 tiles. Under the same conditions but with fog does the Woodland wight can see over 35 tiles and the Players can see over 35 tiles!
The visiblity of the woodland wight does decrease, in the afternoon and also in the early morning but is still much more than it should be in comparision to the player reduced range of vision.

### Attach save file

![Fog 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/f6b37596-4844-4506-bbe7-b393f99c4df4)
![Fog 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/44ff569c-ce53-41da-9fc7-36983e9b6a12)
![Fog 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/aedc4a32-0e1e-4a5b-ba88-a497279f7cbb)
![Fog 4](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/e5e349f3-f833-46b4-b138-8227df9d8568)
![Fog 5](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/1b948ac9-83e2-4efa-b23d-6483cbecf3ea)
![Fog 6](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/88eee572-94ad-4e5f-9fbf-a546ec4b64ff)
![Fog 7](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/9e1ea094-b541-41ea-8211-d3f5b4d1d551)
![Fog 8](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/4d647363-09bf-484c-94b5-3fa231d410eb)
![Fog 9](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/21c6905b-aed1-4f9b-b8d5-ad10547e151e)
![Fog 10](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/fc9c090a-03f6-437b-9db2-e5a5ae2c1cbb)

### Steps to reproduce

1. Use the debug menu to create fog and make the time 11.00 a.m. and place a woodland wight at maximum sight range.
2. See that the woodland wight can see you.
3. Now make it 5 p.m and see that the woodland wight can not see you
4. Now make clear weather and put the woodland wight at maximum sight range at 5 p.m
5. See that he can not see you, change to 11.00 a.m and have the same result.
6. Now set a woodland wight exactly 40 Tiles away from you with the current conditions
7. See that he can see you.

### Expected behavior

Example;
The maximum sight range of the woodland wight should not be the same as the Players sight range, under the weather condition fog and in the morning or noon.

The maximum sight range of the woodland wight should proportional decrease as the players vision does.
Woodland wight vision at clear weather and in the morning is 40 tiles and the player does have a 60 tile vision. The woodland wight does have 66,66667 % of the players vision and that should apply to the woodland wight in the fog as well, which would be 23,33333 tiles and in general to all monsters.

### Versions and configuration

Windows 10
Version: 9afa65c (tiles)
Build: 2023-07-01-0707 (10 hours ago)
mods: Dark days ahead

**Comment by Zireael07** [comment]
Why close?

**Comment by Krieger1999** [comment]
Because it actually does make sense, that zombies see as far as you in the fog. Because this does not depend on how good your eye sight is but how far the fog density allows you to see.
