### ISSUE TITLE
Portal Storms Stop Occurring after 1st Storm

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#66598]
### Describe the bug

After the first portal storm a player experiences, no more portal storms will correctly spawn. The player receives the 'reality is breaking' message, but no actual storm effects such as monster spawning or even the portal storm portal overlay appears.  Eventually the reality is healed message appears, but this does nothing as no portal storm was actually there.  Furthermore, while the center of the portal storm mission does spawn, moving to the center does nothing, with no text dialogue prompt that there is supposed to be.

### Attach save file

Save file is in the middle of a false portal storm.  Mission to find center is active, 'reality is breaking message' appears, but there is no actual portal storm.

[Demopolis.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11928724/Demopolis.zip)

### Steps to reproduce

1. Use debug menu to set time to 1 year to guarantee first portal storm / get past the no portal storm time period.
2. Wait for first portal storm to finish.
3. Use debug menu to pass more time / manually wait for a second portal storm.
4. See that despite a second portal storm 'beginning' nothing actually happens.

### Expected behavior

Portal storm should begin, portal storm center should give the dialogue option, etc...

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: b7db497 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

While I used debug commands to efficiently debug the issue, I have frequently encountered this issue in normal gameplay without debug commands to set time.

**Comment by KHeket** [comment]
@Ramza13 I saw, that you made portal storms mobile. Can you chech this plz?
