### ISSUE TITLE
[Mind over Matter] Casting spells shows '%s' as name in message log

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#66599]
### Describe the bug

When casting a spell from Mind Over Matter, the message log writes out 'You cast %s' instead of using the actual name such as 'You cast [Ψ]Force Shove'

### Attach save file

N/A

### Steps to reproduce

1. Enable Mind Over Matter mod
2. Give strange crystal, yellow with debug commands
3. Activate crystal to gain telekinetic powers
4. Cast Momentum Alteration
5. Observe that message log says 'You cast %s'

### Expected behavior

Message log should contain name of actual spell

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: b7db497 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Mind Over Matter [mindovermatter]
]

**Comment by Standing-Storm** [comment]
This is related to the use of the WONDER flag, which I reported here: https://github.com/CleverRaven/Cataclysm-DDA/issues/64117

**Comment by fyhannes** [comment]
This issue is because the "extra_effects" in `drain.json` can invoke "death_fakespell" which has its message defaulted to "You cast %s!". A fix for this could be to create a dummy spell that has an explicit message of "", and replace the "death_fakespell" with that dummy spell.
