### ISSUE TITLE
Missing migrations for old crater terrain

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#66606]
### Describe the bug

`Loaded invalid oter_id 'crater_core'`

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/7ca80753-8edd-44fe-a5bf-775e2b376a59)

Likely caused by #66499

### Attach save file

https://github.com/CleverRaven/Cataclysm-DDA/files/11918824/Asharoken-trimmed.tar.gz

### Steps to reproduce

Load world from before #66499 with crater terrain

Get error, open map and see nether chewed ifeld

### Expected behavior

Save compatibility

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: 0.G-2753-g37003bf75a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

@Procyonae

**Comment by Procyonae** [comment]
🤦 Forgot I had to separate the id bc it was substring searching for large vs small
