### ISSUE TITLE
Possible crit issue with guns

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#66609]
### Describe the bug

Crits from firearms work on a sliding scale. You can get grazing hits (a negative multiplier), good hits (a positive multiplier), and critical hits (a larger positive multiplier). Good and critical hits have an intensity denoted by the number of exclamation marks in their messaging. Dispersion appears to be capping certain ammunition types below critical hits, resulting in some odd behavior. Additionally, results are very static: Assuming you aim, you either always crit, or you never do.

All tests are done against standard zombies at 4 tiles away.

Using a Barrett M107A1 and .50 BMG M33 Ball I am able to reliably get "Critical!!" hits for 200-260 damage.
Using an M110A1 and 7.62x51 M80 ammunition I am able to reliably get "Critical!!" hits for 80-160 damage.
**Using an M4A1 with 5.56 M855 I am only able to get "Good hit!" hits for 35-48 damage.
Using a Glock 17 with 9x19 JHP I am only able to get "Good hit!" hits for 30-33 damage.**

The cause appears to be the dispersion thresholds starting on line 2286 in ranged.cpp.

### Attach save file

N/A

### Steps to reproduce

1. Make a character with an M4
2. Set your skills to 10.
3. Try to shoot a zombie. Note that it's only ever going to say "Good hit!"
4. Spawn a Barrett, M110A1, or a compound hunting bow.
5. Try to shoot a zombie. Note that you can get a Critical!! or a Critical!

### Expected behavior

All firearms should have a chance to either score criticals or not. If some are better or worse at it then fine, but it shouldn't ever be impossible or guaranteed.

The current system makes it impossible to one-shot a healthy human or zombie with an M4, no matter how good of a marksman or how lucky you are. I don't love one-hit kills but you'd think a high-powered rifle would sometimes blow someone's head apart or go through their heart, like they can IRL.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/c968a0d6-ff0d-4817-ab12-8b68951bd5d8)

Test character for reference.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: ce2aa59 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

#66326 is not the cause of this, as it appears to be a long-standing issue.

The critical hit calculations are scuffed in general. It should not be the case that someone can simply score a critical hit every single time they attack. Even professional marksmen on a range with no external stressors and infinite time to aim don't always bullseye stationary targets, let alone stressed survivors shooting at other human beings or extradimensional monsters that are taking evasive action or charging them down.

**Comment by GuardianDll** [comment]
crit mechanic should be obsoleted prior to weakpoint mechanic

**Comment by fairyarmadillo** [comment]
> crit mechanic should be obsoleted prior to weakpoint mechanic

There are a couple issues with this. One is that bows are balanced around doing 10x crit damage, another is that most enemies will need multiple weakpoints that do a lot of extra damage or guns will turn into peashooters, and finally the crit mechanic appears to be the entirety of the damage roll for guns. Grazing hits are essentially a negative crit, so at the very least these ought to be left in.

There's probably more to it than that, but off the top of my head I can see a few barriers to implementation.
