### ISSUE TITLE
Deconstruction cannot give items charges - MRE

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#6661]
http://smf.cataclysmdda.com/index.php?topic=14.msg98714#msg98714

Currently opening a MRE gives a nice empty matchbook. Which is a bit silly. We should implement a way of using charges and fix the MRE's.

(A quicky and dirty way to fix the MRE would be to just create single use matches. And make those work like a normal matchbook. Perhaps using them like thread and a sewing kit).

**Comment by Rivet-the-Zombie** [comment]
This has been fixed.
