### ISSUE TITLE
Starting to run out of ideas for how to call those typo issues

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#66620]
### Is your feature request related to a problem? Please describe.

Yet another typo hunt for however wants to fix them from what I find while translating, will keep adding what I find as long as this isn't taken up by somebody, but for now I have 12 miscellaneous things needing fixing.

### Solution you would like.

All other similar faction discovery missions use "check out that [interesting location]", seems out of place for only the artisans to stand out:
- Check out bullet bank -> Check out that bullet bank.

Judging gruff answer received due to you failing a godco mission from their leader, I'm pretty sure "expected of" is better English:
- As expected for such a person… -> As expected of such a person…

Miscellaneous godco mission player character dialogue which I assume is to ask for more information, not really sure what was intended there, I assume It'd got fat fingered into I'd:
- I'd really help me in getting your stuff to you faster. -> It'd really help me in getting your stuff to you faster.

This is a very weird way to formulate that building a cellar will allow you to preserve small game you catch in traps, not sure of the needed fix:
- Digging a root cellar will allow us trapping small game and preserving it.

In this Isherwood dialogue you have to choose, either it's a period and there's a capital We or it's a comma and there's none:
- Hello, We don't see many people these days. -> Hello, we don't see many people these days.

Very superfluous comma on this bug dissection snippet:
- It is difficult to work, as the spongey tissue tears apart under your tools -> It is difficult to work as the spongey tissue tears apart under your tools

Boris (from refugee center) dialogue missing a capital letter after an exclamation mark:
- Great!  let's get started. -> Great!  Let's get started.

The fact you need supports for roofs could definitely be better worded there, or just removed since we don't mention the precise relationship of "roof needs wall" in every wall description:
- A solid adobe brick wall, sturdy enough to support a roof with enough walls and to keep out any unwanted visitors.

This needs an end period after tool:
- The [object] is too large and/or heavy to work on.  You may want to use a workbench or a lifting tool -> The [object] is too large and/or heavy to work on.  You may want to use a workbench or a lifting tool.

Russian flag description is lacking an end period:
- A simple horizontal tricolor flag of white, blue and red -> A simple horizontal tricolor flag of white, blue and red.

This Magiclysm book plural is pretty goofy, I think it would be better to leave it as just "small notebooks" that would get distinguished from other similar items by just having... a different description? But idk:
- copies of small notebook -> small notebooks

The bicycling skillbook being intended as a cycling magazine, it would make more sense for its plural to be "issues" instead of copies:
- copies of Bicycling -> issues of Bicycling

The description of the Cerebral Booster CBM probably could use a description of what the coprocessors actually do when implanted in your grey matter, even if it's techno babble, instead of just being "have a +2 to Int":
- A set of bionic coprocessors that are implanted in the user's brain, granting a +2 bonus to intelligence.

### Describe alternatives you have considered.

- Ignoring typos I find
- Fixing typos myself

**Comment by Moumix3** [comment]
> This is a very weird way to formulate that building a cellar will allow you to preserve small game you catch in traps, not sure of the needed fix:
>
>   Digging a root cellar will allow us trapping small game and preserving it.

I'm thinking: "Digging a root cellar would allow us to preserve the small game we trap." (or something along this vein)
