### ISSUE TITLE
Bugged 'Portal-In' Thing

### ISSUE THREAD

**Issue by kylesjob** [CleverRaven/Cataclysm-DDA#66625]
### Describe the bug

On the 3rd Z-Level of a farm Silo, there is a structure called 'Portal In', which i'm guessing is supposed to be a place where a portal used to be. Problem is, it's on the 3rd floor, and is creating dirt flooring in the air. I found it only because of the shadows that it was casting on the ground.

### Attach save file

[Canton Valley-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11931649/Canton.Valley-trimmed.tar.gz)

### Steps to reproduce

1. Climb up the ladder the character is standing next to
2. Hit confirm for the warning
3. Step foot on floating island

### Expected behavior

I expected there to be an unmolested Silo.

### Screenshots

![Screenshot_7](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/15c55816-4573-49cb-869e-55e18034037c)
![Screenshot_8](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/68459763-b06c-4ad5-b7f6-e01906d0957e)
![Screenshot_9](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/b9063dc6-58be-4f41-a2d5-59738659664d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.2057 (21H2)
- Game Version: 6c5ffff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Procyonae** [comment]
Duplicate of #56682
