### ISSUE TITLE
Why did you remove Earth cybernetics?

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#66632]
### Is your feature request related to a problem? Please describe.

Cybernetics used to be found in vaults in secret XEDRA labs, but now you buy them from Rubik instead. I wanted to know the rationale behind the lore change, but unfortunately can't find any references to it. Was the change made because "the lore did not make sense"? Was it made because bionics were too hard to get? Too random? I have found dozens of places where "Cybernetics were brought to Earth after the cataclysm" is stated as a fact, not none provide any explanation.

### Solution you would like.

After someone in the know responds with a link I will update doc/Lore/technology.md to include the link

**Comment by GuardianDll** [comment]
Bionic create the most impact for player at the beginning - armor, integrated tools, different benefits and QoLs. Despite this, the only way to obtain them is raid the lab - dangerous high-tier end-game location with turrets and occasional shoggoths. To raid it you should find and prepare weapon, armor, medicine, tools, train skill and profs - in quantity enough that you don't need any bionic anymore

**Comment by hexagonrecursion** [comment]
> Bionic create the most impact for player at the beginning - armor, integrated tools, different benefits and QoLs. Despite this, the only way to obtain them is raid the lab - dangerous high-tier end-game location with turrets and occasional shoggoths. To raid it you should find and prepare weapon, armor, medicine, tools, train skill and profs - in quantity enough that you don't need any bionic anymore

Thank you. It would be helpful if you could link to the source. Surely there must have been a discussion between core contributors. Maybe even a debate or a vote.

**Comment by Zireael07** [comment]
@hexagonrecursion Don't recall voting but remember the topic being discussed - I *think* in Github issues but I can't find them now

**Comment by CSHague** [comment]
It's honestly all a little silly. The implication is that all of the super tech was a result of extra-dimensional exploration so setting a date on it is superfluous. If they were exploring the Nether in 80s, 90s or oughts then it could be argued that technology crept ahead utilizing the super-materials they found there. At least, that's my understanding for the existence of the plutonium cells: A substance allows the directly decay of plutonium into electricity. It literally did not matter if the year was 2040 or 2023 or 1989, all that matters is that alien material science drove forward technology by doing impossible stuff. It's like in XCOM: Enemy Unknown, where you start selling alien alloys to regional governments and they start fielding laser weaponry from alien materials science that people are convinced to believe are normal technological developments.  The year is almost completely irrelevant.

   And if there's one thing I believe was always a strong narrative is that "Yes, humanity would mine Hell for resources if they could" Now the story appears to be less compelling, honestly. "This just  happens everywhere and it's not really anyone's fault" is not a very compelling story thread, frankly.

**Comment by hexagonrecursion** [comment]
@Zireael07 I have read the titles of [every issue that mentions cybernetics created between 2020-10-07 and 2021-01-02](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aissue+created%3A2020-10-07..2021-01-02+bionics+OR+cbm+OR+cybernetics+) and did not find anything relevant. Here is why I chose this specific range:

- [Here](https://github.com/CleverRaven/Cataclysm-DDA/pull/46376#issuecomment-753509450) on 2021-01-02 @Venera3 says "In the nearish future they will be reworked to be of off-dimensional origin, accessible through a dedicated alien (kinda.) faction". I take this to mean that by that point the fate of cybernetics was already decided
- [This PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/44692) re-adds the doctor that installs CBMs to tacoma commune. It was merged on  merged on 2020-10-07. I take this to mean that at that point the decision has not been made yet.

**Comment by hexagonrecursion** [comment]
I found a mention of cybernetics and Exodii lore [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/45744#issuecomment-736139456) (2020-10-01)

Still can't find source by searching for "exodii" prior to that date. [There are only tree issues](https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aissue+created%3A%3C%3D2020-10-01+exodii+)

**Comment by hexagonrecursion** [comment]
@Zireael07 
> I think in Github issues

I have downloaded every issue that was created before 2020-10-01 and modified after 2019-02-20 that mentions bionics, cbm, or cybernetics and merged all the comments into one file. I then used grep to find every mention of bionics, cbm, or cybernetics in the file and manually analyzed every result. I did not find the original source I was looking for. I think the discussion must have happened somewhere else (pull requests, reddit, discord, etc.)

[Here is the file containing all comments from all issues I downloaded](https://github.com/CleverRaven/Cataclysm-DDA/files/12171454/CBM-comments.txt)

Here is the code I used to download and merge it:
```sh
set -eu

mkdir ~/CBM-comments/

for RANGE in '*..2017-12-31' '2018-01-01..2018-12-31' '2019-01-01..2019-12-31' '2020-01-01..2020-10-01'; do
	gh issue list \
	--repo CleverRaven/Cataclysm-DDA \
	--search "created:$RANGE updated:>=2019-02-20 bionics OR cbm OR cybernetics sort:created-asc" \
	--json author,title,createdAt,body,comments \
	--jq '.[] | ., .comments[] | {author:.author.login, title, body, createdAt}' \
	--limit 2000 \
	--state all \
	> ~/CBM-comments/body-$RANGE.txt
done

cat ~/CBM-comments/* > ~/CBM-comments.txt
```

**Comment by Zireael07** [comment]
Yes, it's entirely possible I am misremembering and the discussion happened on some different platform

**Comment by hexagonrecursion** [comment]
I have found many posts and discussions on [r/cataclysmdda](https://www.reddit.com/r/cataclysmdda) and [discourse](https://discourse.cataclysmdda.org). I-am-Erk appears to be the authority on Exodii and new CBM lore.

Here are a couple quotes that answer some of the questions I had:
- ["Lab cbms aren't going away until they've been adequately replaced by an equivalent different dungeon for cbms. [...] labs are the richest loot pinata in the game and really need to be broken up a bit."](https://www.reddit.com/r/cataclysmdda/comments/wbgtll/comment/iiav21w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
- ["The core concept is to make cbms easier to get, and more reliable - so you get the bread and butter stuff early and work harder to get the game breaking stuff."](https://www.reddit.com/r/cataclysmdda/comments/t3xum7/comment/hyxhiew/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
