### ISSUE TITLE
waterproof_smart_phone_case has no variant bejewelled_smart_phone_case

### ISSUE THREAD

**Issue by EternalKitten** [CleverRaven/Cataclysm-DDA#66637]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82908191/2a9abe05-a922-4297-9ab5-ba49b33bef9b)
I saved my game, updated it to cdda-windows-tiles-x64-msvc-2023-07-03-1556 and got this error on load.

### Attach save file

[Rowley.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11939808/Rowley.zip)

### Steps to reproduce

I am not sure, sorry.

### Expected behavior

I expect to never see debug messages ever again.

### Versions and configuration

OS WIn10 64 bit Intel i7 3820 AMD RX580 8GB VRAM 16GB RAM 500GB SSD
cdda-windows-tiles-x64-msvc-2023-07-03-1556.

### Additional context

I have no smartphones or smartphone cases anywhere near me. Not that I know of.

**Comment by EternalKitten** [comment]
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11939845/debug.zip)
Here's the debug.log mentioned in the error.

**Comment by RenechCDDA** [comment]
Looks like #66462 deleted that specific variant. I would suppose it needs a migration?

**Comment by RenechCDDA** [comment]
Should be resolved by #66648

If this isn't resolved, drop a comment and it can be reopened.

**Comment by EternalKitten** [comment]
Thank you for fixing this for me, mate! Really appreciate it.
