### ISSUE TITLE
spell_level_adjustment does not account for spells whose traits are calculated using the math function

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#66641]
### Describe the bug

Trying to make holding on to a matrix crystal enhance psionic powers the way Mind over Matter lore suggests it should. However, it looks like math only calculates based on the original level of the power, totally ignoring spell_level_adjustment.

Dev version of Mom:
[MindOverMatter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11940584/MindOverMatter.zip)

### Attach save file

[Roundup-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11940602/Roundup-trimmed.tar.gz)

### Steps to reproduce

1) Open the spellbook, notice range and damage on Fountain of Flames level 2
2) Wield a strange crystal, red
3) Open the spellbook, Fountain of Flames is now level 6 (+4) but the range and damage are the same. 

### Expected behavior

spell_level_adjustment and math properly work together

### Screenshots

Power level 2: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/db869938-6d9d-42f3-b3fa-5e6b72eed100)

Power level 6, holding crystal, same damage and range (casting time, which does not use the math function, is properly updated): 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/4147cbad-ac32-4af7-a11b-20c433865478)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 10875c2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Mind Over Matter [mindovermatter]
]

**Comment by andrei8l** [comment]
/confirmed but title is a backwards and this is not specifically a math problem

This line
https://github.com/CleverRaven/Cataclysm-DDA/blob/5eaa4573a1bec1b41d96ed8bcb89f49267f082a4/src/talker_character.cpp#L340
should probably use `get_effective_level()` instead
