### ISSUE TITLE
Dehydrating milk takes WAY too much power

### ISSUE THREAD

**Issue by CSHague** [CleverRaven/Cataclysm-DDA#66646]
### Describe the bug

Dehydrating milk seems like an incredibly energy intense activity. According to the guide it says it takes 1716 kJ of energy to produce just 3 grams of powder from 250 mL of milk. The industrial process to make [fatty milk powders takes 9076 kJ to make an entire kilogram.](https://www.researchgate.net/publication/269765004_Energy_Consumption_in_the_Processing_of_Dairy_and_Feed_Powders_by_Evaporation_and_Drying)   That's around 275kJ per unit in-game. Even assuming the player is even half as efficient as this industrial process it should not be taking more than 3 medium batteries to dehydrate 250 mL unit of milk. The issue here is that only heat is being counted but modern dehydrators use atmospheric control processes (fans, in home units) which are significantly more efficient than using heat alone. Commercial and laboratory dehydrators use hard vacuums, for instance. Potential solution is to add a new tool quality and recipes that account for appropriate energy use for atmospherically-controlled low-heat drying applications.

More research: [a 440W food dehydrator](https://excaliburdehydrator.com/collections/sale/products/3500cdb-excalibur-5-tray-no-timer-clear-door) can[ dehydrate 1.9L of milk in 10 hours.](https://www.excaliburdehydrator-recipes.com/recipe/dehydrated-milk/#) So .44 kW * 3600 = 1584 kJ per hour * 10 = 15840 kJ for 10 hours of explicit operation. 250mL of milk should take roughly 1881 kJ by this recipe.  That makes the listed figures roughly correct, however, this is misleading since the machine won't be operating at full power the entire time. Maximum power is used to heat the element and run the fans but since these machines operate at relatively low temperatures they won't be operating at maximum power during the whole process only when both the fans and the heating elements are on at the same time. This particular model has a range of 105F to 165F. The recipe requires a minimum of 135F for food safety but could run lower as USDA cooking standards can allow pasteurization at lower temps for longer time. This recipe is also for 1% milk. Whole milk would have slightly less water to remove. 

### Attach save file

N/A

### Steps to reproduce

1. spawn in ingredients and tools to make powdered milk using a food dehydrator, loading a medium battery in the dehydrator
2. start the recipe
3. replace medium battery on dehydrator
4. replace medium battery on dehydrator
5. replace medium battery on dehydrator
6. receive 1 unit of powdered milk

### Expected behavior

Energy consumption values that match the reality of device being used.

### Versions and configuration

Game version current experimental

### Additional context

Probably worth it to simply remove batteries from food dehydrators. There's very few instances where a medium battery now will actually complete a job. The old ones operated on magical principles but new values make batteries mostly untenable.

**Comment by nornagon** [comment]
Seems like the recipe was written assuming the dehydrator was operating at full power the whole time. Triangulating a more reasonable figure:

- you mentioned the industrial process takes about 275 kJ per 250 mL unit, but this process includes hard vacuum and other techniques unavailable to the survivor.
- [this link](https://www.ukjuicers.com/info/dehydrator-faqs-a603#:~:text=dehydrator%20will%20typically%20cost%20less%20then%20%C2%A31%20to%20run%20for%2024%20hours) suggests 1 GBP per 24 hrs. Energy price in the UK is around 20–30p per kWh so this is about 5 kWh over 24 hrs, for about 5kWh/24h ~= 0.2 kW ~= 200 W actual usage, even though the power rating for dehydrators is around 400–500 W peak. This would give about half the energy usage that the current recipe specifies, around 900 kJ per unit.

It seems like something around 500–1000 kJ per unit dehydrated is a more reasonable value for energy usage for this recipe. That's still above the available charge in a medium battery! It does seem like a battery-powered dehydrator is a bit silly; as far as I can tell this isn't really a thing in the real world. But in any case the energy usage for the milk powder recipe is still too high.

**Comment by nornagon** [comment]
NB https://github.com/CleverRaven/Cataclysm-DDA/pull/66847 added the ability to link up a food dehydrator to a grid.
