### ISSUE TITLE
u_consume_item causes segfault

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#66640]
### Describe the bug

Working on Mind over Matter and trying to use EoCs to swap the charged matrix crystals to drained ones instead of giving them the SINGLE_USE flag. However, when I add a { "u_consume_item": "matrix_crystal_pyrokinesis", "count": 1 } (and so on) to the appropriate EoC file ("eoc_matrix_awakening.json"), the game crashes after using a matrix crystal.

Dev version of Mom:
[MindOverMatter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11940430/MindOverMatter.zip)

### Attach save file

[Roundup-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11940432/Roundup-trimmed.tar.gz)

### Steps to reproduce

1) Load game
2) Activate a pink strange crystal, which does not use u_consume_item
3) EoC fires successfully and activates psionic awakening.
4) Use any other color of crystal, all of which do use u_consume_item
5) Segfault

### Expected behavior

Game does not segfault due to a JSON change

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 10875c2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Mind Over Matter [mindovermatter]
]

### Additional context

Crash and Debug logs: [config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11940444/config.zip)

**Comment by RenechCDDA** [comment]
Crashes on first attempt with given code.

Crashes on **2nd attempt**(same trace) if `"condition":{ "u_has_items": { "item": "matrix_crystal_vitakinesis", "count": 1 } },` is added, which the docs suggests is necessary.

**Comment by RenechCDDA** [comment]
As the crash log is somehow truncating the stack trace (another issue...?), here it is from VS:

 	cataclysm-tiles.exe!item_pocket::is_type(item_pocket::pocket_type ptype) Line 2104	C++
	cataclysm-tiles.exe!item_contents::has_pocket_type(item_pocket::pocket_type pk_type) Line 1420	C++
 	cataclysm-tiles.exe!item::ammo_consume(int qty, const tripoint & pos, Character * carrier) Line 10542	C++
 	cataclysm-tiles.exe!Character::invoke_item(item * used, const std::string & method, const tripoint & pt, int pre_obtain_moves) Line 6802	C++
 	cataclysm-tiles.exe!avatar::invoke_item(item * used, const tripoint & pt, int pre_obtain_moves) Line 1442	C++
 	cataclysm-tiles.exe!Character::invoke_item(item * used, const std::string & method, const tripoint & pt, int pre_obtain_moves) Line 6735	C++
 	cataclysm-tiles.exe!Character::use(item_location loc, int pre_obtain_moves, const std::string & method) Line 11922	C++
 	cataclysm-tiles.exe!avatar_action::use_item(avatar & you, item_location & loc, const std::string & method) Line 1157	C++
 	cataclysm-tiles.exe!avatar_action::use_item(avatar & you) Line 1072	C++
 	cataclysm-tiles.exe!game::do_regular_action(action_id & act, avatar & player_character, const std::optional<tripoint> & mouse_target) Line 2291	C++
 	cataclysm-tiles.exe!game::handle_action() Line 3018	C++
 	cataclysm-tiles.exe!do_turn() Line 531	C++
 	cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 780	C++

**Comment by RenechCDDA** [comment]
Yeah ok, so the problem is that the eoc is activated by the use item it's consuming. If you activate the eoc independently there's no problem.

It consumes the item ---> the item is consumed ---> but also the item is **used** ---> well the item is gone, so...

**Comment by Standing-Storm** [comment]
Hmm...let me try something then

**Comment by Maleclypse** [comment]
So should this be closed as completed?

**Comment by Standing-Storm** [comment]
Yes, I think so.
