### ISSUE TITLE
Weird things about fuel bunker

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#66651]
### Describe the bug

There are a bunch of inconsistencies about the fuel bunker, especially after the charcoal overhaul.

1. Filling this vehicle part up with coal, charcoal, and carbon electrode rods respectively, you can see that the displayed content volume is different, which is counterintuitive. See the screenshots below.
2. In the vehicle interaction interface, the content volume is displayed in two places, and the two places have different values. See the screenshots below.

### Attach save file

[vehtest-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11943746/vehtest-trimmed.tar.gz)

### Steps to reproduce

Load the save, and examine the vehicle nearby.

### Expected behavior

I expect they have consistent displayed volume, and consistent content volume between different kinds of fuel.

### Screenshots

![2023-07-04-104119](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/363b0319-fdae-4455-9d93-0c42ec5e1e27)

2.5L coal lump VS 12.5L charcoal vs 500.0L carbon electrode rod.

![2023-07-04-104157](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/05ffe7c3-e11f-4354-9859-e1f3a465d2ad)

12.0 L at left VS 12.5L at right.

![2023-07-04-104207](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/c2517d36-0028-4cae-8b99-bbb03659aa0b)

2.0 L at left VS 2.5L at right.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 19858bf5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by anoobindisguise** [comment]
Ok so it's using charges like a gun magazine instead of a given volume like other tanks. That should be changed.
Carbon electrode rods should probably also not be usable this way.
