### ISSUE TITLE
EoC result recipes only run the EoC once when batch crafting

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#66671]
### Describe the bug

Working on MoM and have a recipe that results in the following EoC: 

>  "id": "EOC_CENTERING_MEDITATION",
        "effect": [ { "math": [ "u_val('vitamin', 'name:vitamin_psionic_drain')", "-=", "1" ] } ]

When done one-by-one, it works as expected--checking player needs shows that the vitamin goes down by one every time.  However, when batch-crafting, Psionic Drain still only goes down by 1 even if done in a batch of 5 or 10, as though the EoC only runs when the entire batch is completed. 

Dev version of MoM: 
[MindOverMatter.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11952567/MindOverMatter.zip)

### Attach save file

[Roundup-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11952569/Roundup-trimmed.tar.gz)

### Steps to reproduce

1) Load attached game
2) Check player needs, notice that the "Psionic Drain" vitamin is 22. 
3) Perform the 'Centering Meditation' recipe, vitamin goes down to 21.
4) Perform a batch of 10 Centering Meditations, vitamin goes down to 18 (1 + natural 2h vitamin decay), not 11 or 10.  
5) Perform a batch of 5 Centering Meditations, vitamin goes down to 16. ( 1 + natural decay), not 13 or 12.

### Expected behavior

Recipes that run a result_eoc run it for each recipe completion in a batch craft. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 8eb8c32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Mind Over Matter [mindovermatter]
]

### Additional context

If I change the recipe result EoC to 

>   "id": "EOC_CENTERING_MEDITATION",
>    "effect": [ { "u_spawn_item": "copper" } ]

and run a batch of 10, the result is 1 copper.

**Comment by mqrause** [comment]
/confirmed

Yeah, the recipe eoc code currently doesn't take batch size into account at all. It's currently handled at the end of `Character::complete_craft` in `crafting.cpp` for anyone interested in working on it.
