### ISSUE TITLE
The ability to have unlimited engines in a vehicle if they don't drive the wheels

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66695]
### Is your feature request related to a problem? Please describe.

Currently there is a hard limit on the number of engines per vehicle (1 normally or 2 if you're a master mechanic) but this isn't a realistic limit as you could easily have disconnected engines in the vehicle purely to generate power.

### Solution you would like.

Engine installation should probably be able to determine which wheels the engine drives, which would be extremely complicated but allow for things like individual engines per wheel as is the case for some IRL vehicles. The simplest solution though would be a binary "provides/doesn't provide motive power" flag on the engine upon installation.

### Describe alternatives you have considered.

Like above a more comprehensive system of "what engine drives what wheel if any" would be good to have but it would be terribly complicated and probably not necessary. The current system of all cars being 4WD isn't totally realistic but it's "good enough".

### Additional context

Vehicle code is terrifying

**Comment by MNG-cataclysm** [comment]
Why do we have a hard cap of engines, anyways? What's stopping someone from adding as many engines as they want to and making an ultra-powerful car?

**Comment by KHeket** [comment]
In reality we have the example of multiple engines on the working vehicle https://en.wikipedia.org/wiki/BelAZ_75710
So, its have 2 electricity generators connected to 1 diesel engine, and its construction is generating power for 4 electric motors, two at each axel, I dont know, is there any other exampleof such conctruction. and can you make this for regular car, but in theory you can do it
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/7f78f97a-2d1c-4a4d-9d2b-6a9054f9c3d0)

**Comment by MNG-cataclysm** [comment]
We could just remove the artificial hard cap on engine limits as a result of this. Yes, you would have an ultra-powerful vehicle, but it'd bird through gas like nothing, making it a natural regulating limit to vehicle power.

**Comment by randomtyper** [comment]
> In reality we have the example of multiple engines on the working vehicle https://en.wikipedia.org/wiki/BelAZ_75710 So, its have 2 electricity generators connected to 1 diesel engine, and its construction is generating power for 4 electric motors, two at each axel, I dont know, is there any other exampleof such conctruction. and can you make this for regular car, but in theory you can do it ![image](https://user-images.githubusercontent.com/102726167/251289895-7f78f97a-2d1c-4a4d-9d2b-6a9054f9c3d0.png)

I see this, and raise you this https://en.wikipedia.org/wiki/ZIL-135 (two engines, each driving wheels on their side and not their axis, should have logically had problems with asymmetric power, but actually worked well for its purposes) and this https://en.wikipedia.org/wiki/Chrysler_A57_multibank (five engines cobbled into one, used on Shermans).

**Comment by SurFlurer** [comment]
> We could just remove the artificial hard cap on engine limits as a result of this.

I agree. There are already many limitations to multiple engine vehicles, such as reduced fuel efficiency, and impossible skill requirements. Hardcode such a limit isn't elegant.

**Comment by alp7292** [comment]
i think there is a hidden debuff for 2 engine vehicles in game that causes  2 small engine vehicle to have less power than same 1 engine vehicle it should also be removed or tweaked

**Comment by randomtyper** [comment]
Funnily enough, Smart Controller part's manual states that Snart Controller supports from 2 to 5 controllable engines, despite player can only install two.
