### ISSUE TITLE
Keep running game after player death to see aftereffects.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#6670]
cosmodius95 complained on IRC that he couldn't see the epic aftereffects of his death by vehicular explosion.  It shouldn't be too hard to change "you died, hit space to exit" to "you died, hit space to exit or . to see aftereffects of your death" (needs better wording).
Basically set a flag that skips the player turn (might be as easy as not giving any moves back?) and continuing to advance and draw game world turns (though vision will need a hack, otherwise there will be no vision, alternately swap in an "observer" player)

**Comment by veox** [comment]
Isn't this functionality already present in 0.C?..

**Comment by Zireael07** [comment]
Yes it is, it ought to get closed.

**Comment by DavidKeaton** [comment]
I guess I never tagged this in my deathcam PR, my b.
