### ISSUE TITLE
No response error when talking about rubik that you already met the hub

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#66712]
### Describe the bug

When i told rubik about the fact that i already met the hub, this error screen came out

 DEBUG    : I don't know what to say for TALK_EXODII_MERCHANT_mission_1_met_hub. (BUG (npctalk.cpp:dynamic_line))

 FUNCTION : std::string dialogue::dynamic_line(const talk_topic &)
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/npctalk.cpp
 LINE     : 1394
 VERSION  : 47f8c6e

### Attach save file

[Old Mill Creek-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11970162/Old.Mill.Creek-trimmed.tar.gz)

### Steps to reproduce

1. open the attached save
2. talk to rubik about the job they can't do
3. select `"Well today's your lucky day, my metal friend. I already know the place quite well"`
4. error screen as mentioned above

### Expected behavior

Not erroring out.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 47f8c6e [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks]
]

**Comment by GuardianDll** [comment]
/confirmed.
