### ISSUE TITLE
Add a makeable bomb or grenade which can make some noise

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#66725]
### Is your feature request related to a problem? Please describe.

This type of bomb or grenade can make noise before exploding, attract nearby enemies to pass by, and then explode. I think this is a very useful thing

### Solution you would like.

Perhaps it can be made by combining a noise emitter with a grenade？

**Comment by GuardianDll** [comment]
It's a good idea, but it require some timer mechanism/extended tnt fuse to make a bomb explode after some time - emitting noise for 4 seconds before grenade explode is super not viable

**Comment by Rocket-F-1024** [comment]
But that's too troublesome. You need to first take out the noise emitter, activate it, put it back in the container, then take out the grenade, activate it, put it back in the container, and finally throw the container out. Such tedious operations may lead to attracting other zombies, or the grenade exploding in the player's hands in advance. If we have a noise bomb, we just need to take it out, activate it, and throw it out.

**Comment by kilozombie** [comment]
> It's a good idea, but it require some timer mechanism/extended tnt fuse to make a bomb explode after some time - emitting noise for 4 seconds before grenade explode is super not viable
> 
> But technically it should be solved by such type of bombs with delayed fuse, that you put in a container with noise emitter, activate both, and throw a container, no need to make a separate item

Then surely it would be as simple as duct-taping together both such items to make a new item, yeah? That could be a viable enough crafting recipe.

**Comment by ashGlaw** [comment]
The closest to getting this to work that I have come across is attaching radio control mods to a noisemaker and an explosive. That way you can place them, and then activate them after you've already moved away.
