### ISSUE TITLE
[Xedra Evolved] Leg Weight Suspension System incorrect Coverage / Material

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#66721]
### Describe the bug

The inventor item Leg Weight Suspension System has incorrect coverage and material.  First, it is described as "compact leg attachments", implying it is some form of device attached to a person's legs.  However, right now it covers the hips.  In addition to being an incorrect definition this also makes it conflict with the inventors force field belt item.  Furthermore, it currently is made up of a very thin layer of aluminum.  The item is crafter from a leather belt, electronics, and pipes, so it should have more durability and protection than it currently does.

### Attach save file

N/A

### Steps to reproduce

1. Enabled Xedra Evovled
2. Look at Leg Weight Suspension System's incorrect coverage and material

### Expected behavior

LWSS should cover the legs instead of the hips and should not be made of a thin layer of aluminum

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 47f8c6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    No Fungal Monsters [No_Fungi],
    Modularvests [modularvest],
    Aftershock [aftershock],
    Tileset Aftershock [tileset_aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Blaze Industries [blazeindustries],
    Tileset Blaze Industries [tileset_blazeindustries],
    <color_light_green>Cataclysm++</color> [Cata++],
    Magiclysm [magiclysm],
    Tileset Magiclysm [tileset_magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Mana Cores [manacores],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Nechronica Redux [Nechronica_Redux],
    Advanced Gear/Technologies [advtech],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    CBM Equipment [CBM_Arms],
    Food preservation via ionizing radiation [irradiate-food],
    Garden Pots [growable-pots],
    Incinerator [incinerator],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Pneumatic fun [pneumo_fun],
    Rivtech Beam Swords [beamswordmod],
    XEAS [XEAS],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Alternative Map Key [alt_map_key],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Magiclysm [MMA_Magiclysm],
    Translate Complex Dialogue [translate_dialogue],
    Dream of Flight [dream_of_flight],
    Bombastic Perks [bombastic_perks],
    Whaleys TALL Buildings [whaleys_tallbuild],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    No Bionic Slots [no_cbm_slots],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Resource Crops [resource_crops],
    Resource Crops for Magiclysm [resource_cropsMagic],
    Sly's Mighty Morphin Mutation Station Reworked [sly_mutation_improvements],
    Stats Through Kills [stats_through_kills],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Minimod: No Skill Rust [minimod_no_rust],
    Minimod: Unpersoned [minimod_unpersoned],
    Targeted Mutations [targeted_mutations],
    Personal Modifications [personal_modifications]
]

### Additional context

Not sure if this is worthy of another bug, but some of the inventor items are defined as rigid when they shouldn't be.  For example, the Leg Weight Suspension System and the Force Shield are mechanical devices belted onto a person in various forms.  For example, the Force Shield is "small, thin torus with a huge battery case, and a belt", which would mean that the force field should be able to be strapped over an actually rigid piece of armor.  Therefore, these items shouldn't be rigid.

**Comment by GuardianDll** [comment]
Ok can you please make a whole list of inconsistencies that you found with all inventor's items, so i can clean them all at once?

**Comment by b3brodie** [comment]
Can do.  I've been noting things down as I craft them but I'll take a broader look
