### ISSUE TITLE
active defense system protects against electricity

### ISSUE THREAD

**Issue by Kenshut** [CleverRaven/Cataclysm-DDA#66727]
### Describe the bug

active defense system protects against electricity, but the description says that it reduces the speed of objects, so it should protect only from mechanical impact.

### Attach save file

N/A

### Steps to reproduce

1 -  Turn on CBM active defense system 
2 - find lightning source
3 - let the lightning strike you

### Expected behavior

I think the active defense system should not protect against electricity

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120565475/b7f53600-376a-4e55-97ab-b49e1a94f6cd)

### Versions and configuration

OS: Windows
    - OS Version: 6.1 7601
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: ru 
- Mods loaded: [
    [dda],
    [no_npc_food],
    [personal_portal_storms],
    [no_fungal_growth],
    [package_bionic_professions],
    [stats_through_kills]
]

**Comment by anoobindisguise** [comment]
It doesn't protect against it, it just displays the message regardless of damage type even though it offers no protection against it. That could be fixed tho.
