### ISSUE TITLE
weight in morbidly obese not decreasing after a month of starvation

### ISSUE THREAD

**Issue by yamil-90** [CleverRaven/Cataclysm-DDA#66741]
### Describe the bug

i haven't been eating for about 3 months but my char is still morbidly obese. i used a bathroom scale and i've been at 127 for like a week. i only drink water and take some vitamins but im not seeing any decrease in weight

### Attach save file

[McGuffey-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11986937/McGuffey-trimmed.tar.gz)

### Steps to reproduce

1- drink water to survive
2- wait a couple of days
3- check weight with bathroom scale

### Expected behavior

im not sure but after like 90 days of not eating i should've lost some weight

### Versions and configuration

- OS Ubuntu 22.04
- cata version 17a4f06 tiles version

**Comment by RenechCDDA** [comment]
You have 466,425 stored kilocalories, and you've not been burning very many of them.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/2df3fd88-8d8d-4254-92ff-096266ac9e0d)

For comparison a healthy survivor **of your height and age** has about... 106k on start.

Literally try exercising.

**Comment by yamil-90** [comment]
lol it seems that i need to starve for 120 more days to burn the rest of the calories.... i guess i will look for a threadmill or something like that. 
thank you! :D
