### ISSUE TITLE
RANGED_DAMAGE should affect throwing damage

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#66751]
### Describe the bug

#66407 added RANGED_DAMAGE and it works as intended for "ranged weapons" but doesnt works for throwing damage

### Attach save file

not needed

### Steps to reproduce

give yourself high amount of RANGED_DAMAGE like { "value": "RANGED_DAMAGE", "multiply": 90.0 } and throw rocks or throwing axes and see it doesnt granting any damage

### Expected behavior

RANGED_DAMAGE should affect throwing damage

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: b69ae48 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    alpermodd [alpermm]
]

### Additional context

instead of RANGED_DAMAGE affecting throwing damage maybe we can add a seperate THROWING_DAMAGE

**Comment by GuardianDll** [comment]
Would be better to make separate `THROWING_DAMAGE` imo

**Comment by MorvarchPrincess** [comment]
Seconded on it being better as a seperate enchant, means nuance is much better.

**Comment by alp7292** [comment]
we can also add special THROWING flag to some weapons like staff sling so they will benefit from "THROWING_DAMAGE" and not from "RANGED_DAMAGE"
