### ISSUE TITLE
stab weave kevlar vs ballistic weave kevlar

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66762]
### Is your feature request related to a problem? Please describe.

IRL there are like 50 billion versions of kevlar to choose from with specialized purposes but there are two main distinctions - ballistic weave (extremely tight machine precise weave) and stab weave (loose weave). Both kinds are rather poor at their opposite - stab weave doesn't do much vs bullets and ballistic weave doesn't do much vs knives.

In game however there's only one kind of kevlar, which appears to be a ballistic weave based on its stats (2.4 stab and 5 ballistic).

### Solution you would like.

Kevlar could probably be split into two different versions, with ballistic weave for example being largely the same or having slightly lower cut/stab while stab weave kevlar could have the inverse, 5 stab prot and only like 2 ballistic prot. Many pieces of gear could be converted to this - the robofac MDS, cut resistant gear, dog bite suits, stab vests, etc. While ballistic vests would remain ballistic kevlar and be the primary source of that resource.

### Describe alternatives you have considered.
Continue wearing bulletproof dog bite suit to gunfights.

_No response_

**Comment by fairyarmadillo** [comment]
My google research into this suggests that the main difference is that stab vests have a hardened insert (with resin?) and not that they use a different kind of fabric, but I was having trouble finding anything about the actual specs.
