### ISSUE TITLE
[Mind Over Matter] Using Power Contemplation Recipes does not give Powers on Level Up

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#66772]
### Describe the bug

Many of the powers in Mind Over Matter are learned via leveling up a spell / power to level 7 or 15.  The easiest way to get to at least 7 with the early powers is using the contemplation practice recipes for experience in them.  However, if a power reaches the required level to obtain a new power when using the contemplation recipe, no new power is gained.

### Attach save file

N/A

### Steps to reproduce

1. Awaken to any psionic path (ex pyrokinesis)
2. Use contemplation recipes to level a spell (ex quell fire) to level 7
3. Observe that you do not learn the spell defined in "learn spells"

### Expected behavior

Spell is learned when reaching appropriate level using contemplation recipes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 47f8c6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    No Fungal Monsters [No_Fungi],
    Modularvests [modularvest],
    Aftershock [aftershock],
    Tileset Aftershock [tileset_aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Blaze Industries [blazeindustries],
    Tileset Blaze Industries [tileset_blazeindustries],
    <color_light_green>Cataclysm++</color> [Cata++],
    Magiclysm [magiclysm],
    Tileset Magiclysm [tileset_magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Mana Cores [manacores],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Nechronica Redux [Nechronica_Redux],
    Advanced Gear/Technologies [advtech],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    CBM Equipment [CBM_Arms],
    Food preservation via ionizing radiation [irradiate-food],
    Garden Pots [growable-pots],
    Incinerator [incinerator],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Pneumatic fun [pneumo_fun],
    Rivtech Beam Swords [beamswordmod],
    XEAS [XEAS],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Alternative Map Key [alt_map_key],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Magiclysm [MMA_Magiclysm],
    Translate Complex Dialogue [translate_dialogue],
    Dream of Flight [dream_of_flight],
    Bombastic Perks [bombastic_perks],
    Whaleys TALL Buildings [whaleys_tallbuild],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    No Bionic Slots [no_cbm_slots],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Resource Crops [resource_crops],
    Resource Crops for Magiclysm [resource_cropsMagic],
    Sly's Mighty Morphin Mutation Station Reworked [sly_mutation_improvements],
    Stats Through Kills [stats_through_kills],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Minimod: No Skill Rust [minimod_no_rust],
    Minimod: Unpersoned [minimod_unpersoned],
    Targeted Mutations [targeted_mutations],
    Personal Modifications [personal_modifications]
]

### Additional context

Maybe add a spell learn effect if beyond a certain experience point into the contemplation EOC?

**Comment by casswedson** [comment]
can /confirm getting to level 7 via practice recipes does not trigger `learn_spells`

**Comment by RenechCDDA** [comment]
Resolved by #68946
