### ISSUE TITLE
Improve monster LOS faction checks

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#66789]
### Is your feature request related to a problem? Please describe.

"one of the bigger problems with scaling up reality bubbles is the faction identification los stuff scaling painfully"
Kevin Granade : "To expand on that, something that's very expensive and has so far been very resistant to optimization is that for every monster  In the bubble it has to do a vision check to every monster in an opposing faction.
 So say you have a 100 monsters on the map split into 2 factions that both hate each other you have to do 50^2 vision checks every turn checking the visibility of something like 30 tiles each
Increasing the reality bubble radius by one means increasing the total number of tiles by about 5%, which does very bad things once it's squared"

### Solution you would like.

Kevin : "Anyway what you do is starting at each monster you do a flood fill of every tile that is either transparent or navigable.  Every reachable tile is added to the zone the monster is in and then as you find monsters you also add them to that same zone.
 You do this pass over all the monsters every turn or ideally once per map invalidation and then when you're doing the faction to faction sight checks you can eliminate any monster that is not in the same zone. 
Alright I just remembered the thing that makes it where you don't have to invalidate every turn. basically you treat things like fields that are only opaque transiently as if they were transparent which is pessimistic in that it will still trigger a sight check in some instances where it could have been avoided but it lets you avoid rebuilding the zone map every turn and you only have to invalidate it when the map shifts or when there's a terrain change.  
A really nice detail is you don't actually maintain a map of zones to monsters or vice versa all you have to do is keep it around during the flood fill, you label the monsters or their entries in the monster tracker with which zone they've been added to and then when it's time to do the inter monster aggression checks all you do is check whether their zone is the same."

### Additional context

Drew4484 (Pings/DMs are fine) — Today at 5:53 PM
Does this mean flying creatures are resource hogs?
kevingranade — Today at 5:54 PM
No it means everything on the surface is essentially in the same zone 
Basically the zones end up being "outside" plus any closed rooms
The main use case this addresses is big facilities either above ground or underground with closed off rooms. it trivially keeps any monsters in those closed rooms from having to check for each other's presence
There's a more complicated version you Could write that has a separate set of zones for each type of locomotion but again I think making it pessimistic instead is probably going to get us a lot of wins
How often do we have a situation where you have a monster that can't fly in an open topped area that it can't reach the surface from
kevingranade — Today at 6:03 PM
At first I thought I was going to have to add sent permeabilitly to transparency and navigability, but it turns out this is only vision based so the only time a monster is going to try to for example bash down a door is because it can either see a monster through the door which is covered by transparency or if it can smell an enemy through the door which is covered separately by the scent tracking which doesn't have the same scaling problems as vision

**Comment by Inglonias** [comment]
Figures it's the LOS code.

**Comment by marimarigi** [comment]
One turn is just one second. It's probably more efficient if they don't recognize everything every second.

**Comment by Maleclypse** [comment]
Closed by #68097
