### ISSUE TITLE
A flag on armor that explicitly *dis*allows wearing it without a mutation

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#66795]
### Is your feature request related to a problem? Please describe.

I want to work on implementing digitigrade boots, but I want to make them wearable only by digitigrade mutants and not humans. As far as I can tell there is no system that allows that.

### Solution you would like.

Flags that can be the reverse of "ALLOWS_TAIL" etc, only making something wearable _with_ a certain mutation.

### Describe alternatives you have considered.

Making the digitigrade boots be wearable by humans and saying they are "adjustable" but that seems like a kludge.

### Additional context

This should probably be implemented in the mutation, like ALLOWS_TAIL is, so the flags can be not hardcoded and remain generic.

**Comment by fairyarmadillo** [comment]
It may be better to wait for animal legs to get made into their own bodyparts a la gastropod foot so that the flag could check for a bodypart rather than a mutation.

**Comment by KittyTac** [comment]
> It may be better to wait for animal legs to get made into their own bodyparts a la gastropod foot so that the flag could check for a bodypart rather than a mutation.

This is imo more versatile and would do the same thing, with more versatility for mutations that won't give limbs. You won't have digitigrade legs without the mutation.
