### ISSUE TITLE
Attics?

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#66799]
### Is your feature request related to a problem? Please describe.

Basements are fine and dandy, but I also feel it'd make sense for certain homes to have attics, which would function similarly to basements except with a bigger level of dust to it, so to speak.

### Solution you would like.

If I might be personal for a few moments, one thing I've realized about my family is that we are natural hoarders, and so the house where I grew up has an attic filled with boxes of random stuff. And this perfectly describes my idea for how attics could work in CDDA: They're like basements, except far more randomized, a bit less likely to contain zombified people or monsters, and hidden from ground level. The key difference would be that you could tell if a building has an attic by scaling a non-attic building and just looking around, but then you'd still need to figure out where the "hidden ladder" is located inside that building.

### Describe alternatives you have considered.

Simply not having attics?

**Comment by Procyonae** [comment]
The only particular issue with attics in general I see is how you're making the ladder work to avoid the issue with overhead lights where we'd need a new terrain for every "floor type /w overhead attic hatch" so you probably want the overhead hatch to be furniture or to add better support for overhead stuff in general, the actual examine -> map update needed isn't super simple either. The only other issue is currently all buildings have flat roofs and attics are housed inside v roofs so you'd probably want to add roof ramp variants which is adding quite a bit of work (and current ramps are fairly jank in non straight orientations). Also idk about New England but here alot of attics aren't properly floored and you'd fall straight through unless you stick to beams so representing that with like a "thin roof" terrain that acts like opaque open air that turns into open air when you step on it might be cool.
