### ISSUE TITLE
suitcase

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#66812]
### Describe the bug

...why is just holding the suitcase's handle uncomfortable and even painful?

### Attach save file

[Nightmare-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12014180/Nightmare-trimmed.tar.gz)

### Steps to reproduce

1. Just get a suitcase. In my case, it was the large 115L one from private airport.
2. Wear it.

### Expected behavior

...Why is it uncomfortable? The handle is literally intended as a handle.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 55526ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

**Comment by GuardianDll** [comment]
Well, you answered it for yourself: you wear it
We can't emulate using a second arm yet, so you equip it, and as this "clothes" is not padded, it rub your skin

**Comment by FayFlightee** [comment]
> Well, you answered it for yourself: you wear it We can't emulate using a second arm yet, so you equip it, and as this "clothes" is not padded, it rub your skin

No reason the suitcase's handle is THAT uncomfortable.

**Comment by RenechCDDA** [comment]
The material is plastic. If it should be comfortable to wear(doubtful) it just needs the PADDED flag added.
