### ISSUE TITLE
Fire safety devices, emergency lighting, emergency escape routes in buildings

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66819]
### Is your feature request related to a problem? Please describe.

Not a single building in New England adheres to fire safety standards. There are no emergency lights (which turn on if a fire is detected and light the path to the nearest exit), there are no doors that can remain open during emergencies (preventing stampedes or being trapped in a burning building), there are no fire alarm devices devices in any building or automatic sprinklers, fire extinguishers are rarely found / placed somewhere they'd not be helpful (they're usually right next to an entrance/exit or fire hazards.

Many areas that the player discovers are places with a large volume of people and are currently in the middle of an emergency - they would at the very least have emergency lights active for when things go bad.

### Solution you would like.

Adding small emergency lights (lightstrip-like) on roofs, that lead to the closest exit to most buildings that would have a fire safety code. Adding roof sprinklers that activate and extinguish fires when smoke or fire reaches their square. Giving buildings fire escape doors or exits. Adding more fire extinguisher boxes (like the ones in square/subway labs) to most commercially used buildings.  

### Describe alternatives you have considered.

Not doing any of that and pretending the New England fire safety officials are hilariously inept/corrupt/pyromaniacal. 

### Additional context

As someone who worked on fire safety features for buildings, every building needs to have: Appropriate amount of fire extinguishers placed in strategic areas/every floor, a clear exit path lit by emergency lights, access for a firetruck/firetruck ladder on every side of the building, fire safety doors or fire-containing doors (designed to last 30-90 minutes in a fire before failing), automatic fire dispatch alarms or sprinkler system activation devices. 

New England buildings are all fiery deathtraps. But we all knew that already.

**Comment by Procyonae** [comment]
I will say several of these like sprinklers would require power so should be non operational

**Comment by TheSaddestGoomba** [comment]
Emergency sprinklers definitely do not need power to function, they're failsafes. They usually operate on pressure already in the system, released by a glass cartridge breaking at a certain temperature.

**Comment by Procyonae** [comment]
> Emergency sprinklers definitely do not need power to function, they're failsafes. They usually operate on pressure already in the system, released by a glass cartridge breaking at a certain temperature.

Huh that's cool

**Comment by teapot156** [comment]
Sounds like someone had a little accident
