### ISSUE TITLE
"Fire Menu" New keybindings just for aim, then shoot manual

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#66829]
### Is your feature request related to a problem? Please describe.

When aiming with ranged weapons, i very often have to press the button for steady my aim, to fire when I am exactly ready.
This is the only way for me to deal with many zombies in a firefight.

### Solution you would like.

I would like to have an option to jump to the three different shooting modes quickly, but not to fire, just to aim.
Then I can make fine adjustments if I want to.
Just some key bindings would do the job.

### Describe alternatives you have considered.

Pressing the button for steading the aim 100000 times more........

**Comment by ashGlaw** [comment]
I've felt the same frustration. Maybe a key in the aim menu to toggle whether aim and shoot are coupled out not, defaulting to coupled, would be a good way to handle it
