### ISSUE TITLE
Miniature Clown Bicycles

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66823]
### Is your feature request related to a problem? Please describe.

Now that we have a 'skateboard' vehicle and appropriate mechanics that let you stumble/fall off of a unstable vehicle like that, more vehicles of the same nature can be added. The tiny bicycle driven by clowns is one such example.

### Solution you would like.

Add a one-tile, slow, muscle-powered, foldable vehicle that operates like a skateboard in terms of stumbling/falling/launching out of it on collisions, but has the description and features of a bicycle. It may require a unique 'miniature bicycle' vehicle part of some sort.

Give such a vehicle (in its folded state) to the Clown starting profession. Have the vehicle sometimes spawn in any areas you'd expect a clown to be in, or rarely in bike shops.

### Describe alternatives you have considered.

Adding a unicycle instead.

Not clowning around.

### Additional context

![86165_1000x1000](https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/9a5b973a-f334-4872-a570-7e24079b70d9)

**Comment by Procyonae** [comment]
Small feature requests like this and your atomic light request are unlikely to make it into the game unless you do it yourself

**Comment by fairyarmadillo** [comment]
There's already a children's tricycle for clowning around. Bikes and kayaks should probably get the code for falling off, but they don't have it yet.
