### ISSUE TITLE
Anchor LIGHT_[X] flag's value to a real world unit of measure

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#66825]
### Is your feature request related to a problem? Please describe.

I got an idea for a PR to add some new small light sources. To add light sources, there is a need to assign those relevant luminosity values, but LIGHT_[X] flag is not tied to any real life unit that measures power of a light source. When I read the .md file about flags, I only got next info:
"LIGHT_[X] Illuminates the area with light intensity [X] where [X] is an intensity value. (e.x. LIGHT_4 or LIGHT_100). Note: this flags sets itype::light_emission field and then is removed (can't be found using has_flag);"

As such, accuracy of the game suffers significantly, because contributors have to guesstimate the value.

### Solution you would like.

- Anchor LIGHT_[X] flag's value to lumen, with X = luminosity of light source in lumen (so 300 lm headlamp has LIGHT_300).

- Non-rotating non-focused stationary lights get 0.5-0.75x multiplier to their luminosity (so IRL 600-800 lumen household lamps are closer to ingame value of 200 for standing lights).

- Focused lights (car headlights, but not wide-angle) get a 2x multiplier to their luminosity (so 1000-4000 lumen car headlight is close to ingame value of 6000).

- Adjust power consumptions and luminosities of light sources so that most LED light sources produce about 100 lumen/W (there are IRL LED lights that produce ~200 lumen/W, those will be for more rare light sources).

- Write all this stuff into .md doc for JSON flags.

### Describe alternatives you have considered.

Other way of determining light intensity.

Having to guesstimate light intensity for every new light source.

### Additional context

Info on LED lamp efficiency:

https://en.wikipedia.org/wiki/LED_lamp#Comparison_table

Some napkinmath time:

This flashlight has 0.6 V voltage and uses AA batteries that have peak current of ~2 A, as such, this light has wattage of 1.2 W while having 165 lm luminosity. That's a bit over 100 lm/W.

https://www.amazon.com/ORCATORCH-Underwater-Rotatable-Batteries-Included/dp/B07BDKRFJG

This flashlight has 1.5 V voltage and uses AA batteries that have peak current of ~2 A, as such, this light has wattage of 3 W while having 450 lm luminosity. That's about 150 lm/W.

https://www.amazon.com/RAYVENGE-Headlamp-Underwater-Flashlight-Stainless/dp/B0BD6GVJH2

**Comment by Hirmuolio** [comment]
The light code is some weird stuff.

Light values go from 0 (no light) to 100 (sort of max light but not really). For example noon sunlight at its peak illuminates tile to around 125 light level.
Then comes heavy-duty flashlight that illuminates a tile to light level of 500.
The light system is full of this kind of weirdness that makes it impossible to tie it to real numbers like lumens.

Well it could be done that the json defines real sensical lumens but the code then converts them into this nonsense used by the game.

**Comment by randomtyper** [comment]
> The light code is some weird stuff.
> 
> Light values go from 0 (no light) to 100 (sort of max light but not really). For example noon sunlight at its peak illuminates tile to around 125 light level. Then comes heavy-duty flashlight that illuminates a tile to light level of 500. The light system is full of this kind of weirdness that makes it impossible to tie it to real numbers like lumens.
> 
> Well it could be done that the json defines real sensical lumens but the code then converts them into this nonsense used by the game.

The current system, however weird it is, works well enough for the intended purposes - simulating dynamic lighting in ASCII turn-based game. The main problem for contributors is that there is no internal consistency among the artificial light sources.

I want to have it at least like with the gun damage, where there is a given formula for calculating damage based on a real value - muzzle energy (not the most realistic solution, but works).

Finally, if there is at least some sort of system, it will be much easier to change all of the components if changes to lighting as a whole will come.
