### ISSUE TITLE
Allow even more commonly-used tools and appliances to be plugged into electrical grids

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66824]
### Is your feature request related to a problem? Please describe.

There are a bunch more frequently-used (for crafting or gear repair/maintenance) survivor tools that should be pluggable into an electrical grid, but can't be. These include:
- Space heaters
- Induction hotplate and other hotplate-using tools
- Soldering iron
- Electric firestarter
- Gunsmith/firearm repair kit
- Radio
- Electrolysis kit
- Electric forge/kiln
- Food dehydrator
- Aim game target practice kit

### Solution you would like.

Add the feature to plug such appliances into an electrical grid, as was recently added to existing items with that feature.

### Describe alternatives you have considered.

Doing this for EVERY electrical tool. 

Adding a wireless recharger tool which you can plug in, which then acts as a battery recharger for any tools on the same space/container or gives other tools the 'plugged in' feature.

**Comment by Kamayana** [comment]
I'm currently finishing up a second pass on the cable code, and once that's done I'll make another PR for a lot more pluggable items
