### ISSUE TITLE
Selecting target container for picking up.

### ISSUE THREAD

**Issue by S0ZDATEL** [CleverRaven/Cataclysm-DDA#66845]
### Is your feature request related to a problem? Please describe.

We have a complex pocket system, but when the player picks up items, it selects where to put them without asking the player, so if the player wants to put an item in a specific pocket, they have to either change the pocket priority, pick it up and change the priority back, or pick it up and then manually move it from one pocket to the other.

### Solution you would like.

Maybe when the player picks up stuff, the game should also ask them where they want to put it?

### Describe alternatives you have considered.

There may be a target pocket selector in grab menu where the player can select where the items will go.

### Additional context

The inventory management is kinda hard now, also it would be easier if the advanced inventory screen would allow placing items into containers from anywhere and not just from another container, so the player could just select the whole inventory on one side and a backpack on the other and move items from anywhere in their inventory into a backpack. Right now it just says "Source must be a container."... or select two containers, for example to move items from a bag into a backpack. I don't understand this at all, what's the point if it doesn't even allow you to select two containers on two sides, and doesn't allow you to move items into a container if the source isn't a container too, so it just never works... also, if I move items from a pocket with the highest priority into a general inventory, it will just move it back into the same pocket, only wasting time. Would be better if moving item from a container into inventory would mean something along the lines of "move it anywhere except where it was originaly".

**Comment by andrei8l** [comment]
You can do this already with roughly the same number of actions.
1. Open inventory menu.
2. Examine the target container
3. `i`nsert

I wouldn't want to get asked for a destination every time I pick something up. Especially when picking multiple somethings that collectively can't fit in one pocket.

**Comment by S0ZDATEL** [comment]
You can `i`nsert only items from your inventory. So, if I see a knife that I want to put specifically in my pocket, I have to either have to set high priority for the pocket, or pick the knife into wherever it goes and then `i`nsert it from there into the pocket, wasting time.

And you won't be asked every time you want to pick up items, it may remember the last option. Like in advanced inventory, where it may remember the tiles you moved the items to and from. So, it will be just a selector that you can change while picking up items.
