### ISSUE TITLE
Add some agricultural machines for threshing and winnowing

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#66857]
### Is your feature request related to a problem? Please describe.

Recently, there has been a major update in the agricultural system, where grains need to be dried, threshed, and winnowed before they can be used. However, currently, these operations can only be carried out manually. I hope to add some machines to help with the work.

### Solution you would like.

The following picture shows a type of thresher used in rural China, which can be driven by human or electric power. Its principle is to thresh grains on straw through high-speed rotating stick like objects (such as nails).
![11af-1bab031b202dd135a181e5cbf4972f59](https://github.com/CleverRaven/Cataclysm-DDA/assets/83650722/da921553-512b-4f55-bdbf-919fe1137f9d)
![279174824](https://github.com/CleverRaven/Cataclysm-DDA/assets/83650722/ba261b68-dd2d-44e5-a176-278ca54c78de)

The following figure shows a type of winnower used in rural China, which can be driven by human or electric power. Its principle is to blow out wind through high-speed rotating fan blades, blowing out lighter husks, while heavier grains will be left behind and fall.
![QQ图片20230713050141](https://github.com/CleverRaven/Cataclysm-DDA/assets/83650722/2b23228b-82e8-4039-9cae-34a635d4e74c)
![u=2081671367,2408685480 fm=253 fmt=auto app=138 f=JPEG](https://github.com/CleverRaven/Cataclysm-DDA/assets/83650722/17de2d97-c0b9-459b-b6e4-0077e1bbddaa)

Also, did this agricultural update miss the step of adding grain husking?

**Comment by GuardianDll** [comment]
Massive probelm with such tools in the game is that to make it work, you need to make a duplication of every recipe, so the time boost would be applied

**Comment by Rocket-F-1024** [comment]
> Massive probelm with such tools in the game is that to make it work, you need to make a duplication of every recipe, so the time boost would be applied

Currently, there are only 6 crops in the game that require threshing and winnowing, I think it wouldn't have a significant impact on the game's operation

**Comment by fairyarmadillo** [comment]
I didn't touch corn, no. I suppose husking it could be a disassembly task, but you don't need to husk corn to dry it irl so it and popcorn would need double the recipes for everything.

**Comment by Rocket-F-1024** [comment]
> I didn't touch corn, no. I suppose husking it could be a disassembly task, but you don't need to husk corn to dry it irl so it and popcorn would need double the recipes for everything.

Corn does not require husking, but crops such as wheat, barley, oats, and buckwheat require husking before use, their chaff cannot be removed through the threshing process.

**Comment by fairyarmadillo** [comment]
What? Are you talking about winnowing? That's unrelated to husking maize.

**Comment by Rocket-F-1024** [comment]
> What? Are you talking about winnowing? That's unrelated to husking maize.

No,what I'm talking about is removing the hard shell of the seed.

**Comment by fairyarmadillo** [comment]
"Husking" refers to removing the leafy green husk from around a cob of maize by hand-peeling it. No such process is necessary for the other grains, as the seedheads have been bred to come easily out of their hulls during the threshing process, except for rice which has to be milled.
