### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by 0rthus** [CleverRaven/Cataclysm-DDA#66854]
### Describe the bug

Upon starting a new game, it shows an error and crashes to the main menu screen. Tried it with only vanilla content and got the same result.

### Attach save file

N/A

### Steps to reproduce

1. Start the game.

### Expected behavior

No crash

### Versions and configuration

- OS: Windows 10
- Game Version: 68c0a0b (64-bit)
- Graphics Version: Tiles
- Ingame Language: English
- Mods Loaded: Bionic Professions, DinoMod, Magiclysm, Mind over Matter, Xedra Evolved, MegaFauna, Alt Map Key, Bombastic Perks, Crazy Cataclysm, MMA, Bionic Slots, Slowdown Fungal Growth, SpeedyDex, Stats through Kills, Stats through Skills, Tamable WIldlife, Aftershock, Pixel's Fuckery, Vermilion, Crazy Labs, Light Weariness, Magic Rewamp, No Rust, AutoDoc Harmeless Perfect, More Survivor Notes, Culinary Days Ahead, World on Fire, Deadly Zombie Virus

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12032419/crash.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12032428/save.zip)

**Comment by RenechCDDA** [comment]
Already resolved, update to the latest version.

**Comment by 0rthus** [comment]
I see, thanks
