### ISSUE TITLE
Local Keybinds inside Inventory Organization window take precedence over Filtering 

### ISSUE THREAD

**Issue by AeroCross** [CleverRaven/Cataclysm-DDA#66855]
### Describe the bug

Inside the Inventory Organization window (default: "i" > "i"), the default keybinds for going up and down are the arrow keys. I rebound those to k and j locally. After that, I tried filtering (default "/") and k and j were no longer letters I could type in the filtering field. They would instead pan up or down.

### Attach save file

N/A

### Steps to reproduce

1. Open Inventory Organization (i > i)
2. Open Keybinds (?)
3. Define a new local keybind for Pan Up (+ > a)
4. Use "k" as the new keybind
5. Save changes (esc > Y)
6. Enter filtering mode (/)
7. Try to enter the letter "k"

### Expected behavior

I would expect the letter k to appear in the filter bar. For example, I would be able to type "Cracker"

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1848 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I have confirmed this issue also happens with the following keybinds:

- Pan Up (k)
- Pan Down (j)
- Go to first entry (G)
- Go to last entry (g)

I have not tried with any other.

**Comment by Brambor** [comment]
What is `Pan Up` in step 3?
I set `k` as a keybing for `Page up` instead.
I could write in filter `/` just fine.

Couldn't reproduce in inventory `i`, so I tried AIM `/`:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/c2324bad-d708-45af-bd25-ee71f4008c05)

So I opened Advanced Inventory Manager
It has `Pan Up` already set with keybinding `k`.
Works as expected when outside filter.
When filtering `/` I can write `k` without a problem

~newest master today
- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 0.G-3932-g14da1f6223-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

I might try with your version too...

**Comment by AeroCross** [comment]
Hi @Brambor! Thanks for looking into my issue.

I have confirmed that this works in the stable 0.G and in today's master.

According to your comment, the issue is not reproducible because it not in the correct screen.

The bug appears in the **Inventory Organization** window, which the default keybind is `ii`.

In that window, you will see that Pan Up (which _is_ bound in screens like AIM), is not bound. If you bind it, and then try filtering, it will not work as intended. Instead, Pan Up will take precedence, instead of being able to enter something in the filter.

**Comment by AeroCross** [comment]
@Brambor, did something happen with the `/confirmed` command that made this issue not triaged correctly?

**Comment by Brambor** [comment]
> @Brambor, did something happen with the `/confirmed` command that made this issue not triaged correctly?

I thought it would do something. Since it didn't I thought people would read it to see it is confirmed.

It didn't do anything and I am not sure if I don't have the permissions or if it just does nothing.
