### ISSUE TITLE
`Unload Container` ignores `NO_UNLOAD`

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#66850]
### Describe the bug

I managed to unload a cardboard roll of duct tape with `Unload Container`, despite it does not appear in `Unload Item` and said cardboard roll have a `NO_UNLOAD` flag on them.

### Attach save file

N/A

### Steps to reproduce

1. bind your keybind to `Unload Container` if you haven't done that
2. spawn in duct tape roll
3. try to unload it with `Unload item` and see it does not appear in the menu
4. Try unload it with `Unload container` and see it does appear in the menu
5. unload the cardboard roll and enjoy the unloaded duct tape

### Expected behavior

Not being unloadable for the containers that has `NO_UNLOAD`.

### Screenshots

For this test, i've stripped myself from the stuff i have and only have the cardboard roll in my inventory

Unload item
![Screenshot_20230712-234122](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/5d376db8-63ec-40b7-8e0a-a767675d927e)

Unload container
![Screenshot_20230712-234137](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/4dd29eb1-e121-46c9-9781-d285878f620a)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 68c0a0b [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks]
]

**Comment by RenechCDDA** [comment]
Confirmed, likely missing a flag check...
