### ISSUE TITLE
Locations shouldn't be spawning naked human corpses that resurrect as naked zombies

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66861]
### Is your feature request related to a problem? Please describe.

There are several locations in the game that spawn completely naked dead "human" corpses. These almost instantly resurrect into actual zombies even upon freshly starting the game but have no clothes, because they weren't spawned with an itemgroup. Examples of this include mass grave sites, apartment complexes and looted gun stores. It doesn't make much sense that these people would be naked - maybe their backpacks were taken away and they were stripped of valuables but the clothes on their back shouldn't be gone too.

### Solution you would like.

Locations like this should just spawn living zombies instead of human corpses which resurrect almost instantly into naked zombies, which would give those zombies actual clothes instead of having nothing.

### Describe alternatives you have considered.

Remove the corpses entirely?

**Comment by Procyonae** [comment]
You can just spawn the corpses with items contained in them to get around this, might have a look at the maps you mentioned later
