### ISSUE TITLE
Gastropod foot is a serious detriment

### ISSUE THREAD

**Issue by hatamekyu** [CleverRaven/Cataclysm-DDA#66886]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/138999792/6b317646-ad79-424b-80e2-5eb791dc4b5f)

They really like hitting that unarmored squishy gastropod foot....

### Solution you would like.

sorry to add another gastropod post, but surely there would be a way to get some sort of protection for your new entirely unarmored vitals, right?

**Comment by fairyarmadillo** [comment]
This could partly be fixed by making the snail's torso proportionally much larger, which would direct more attacks toward its shell. Muscle consolidation could make its arms smaller too.

**Comment by hatamekyu** [comment]
Oh yeah, another thing I noticed is that the gastropod foot is the one that prevents torso armor from being worn as well, not the shell
