### ISSUE TITLE
Skeletal Juggernaut/Hulk can launch cars up z levels and get them stuck there

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#66905]
### Describe the bug

After a horde of zombies (including a skeletal master, who produced multiple hulks/juggernauts) noticed me from the 2nd level of a house through a window, they started to approach. As I was going towards the stairs to face them, a car that was in a garage underneath, that the zombies pathed through, suddenly got launched upwards, ending up on the second level, mostly wrecked, and with the floor missing underneath it. See screenshot for details.

### Attach save file

[Orland Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12052819/Orland.Hills-trimmed.tar.gz)

### Steps to reproduce

Uncertain if this works or not:

1) Go to the second level of a house, one with a garage and a vehicle inside the garage
2) Get spotted by a hulk/juggernaut through one of the windows on the second floor (activate experimental 3D view if you haven't)
3) Lead the hulk/juggernaut towards the vehicle in the garage.

### Expected behavior

Cars do not get yeeted up z levels, through the roof/floor of the second level.

### Screenshots

<img width="938" alt="Screenshot_1" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/6d91aedf-1e8f-4a82-9733-aa58bb519ba0">
<img width="901" alt="Screenshot_2" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/39234303/6fb8df74-638f-4191-89f1-da3de851ec1e">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: bf5848d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by esotericist** [comment]
hmmm. is the real bug the fact the vehicle goes up, or the fact there isn't structural damage to the house in the process? i am torn, but cautiously leaning towards the latter.

**Comment by Procyonae** [comment]
I mean what are they meant to be doing to the vehicle in the first place, vehicles COM are low enough to the ground that nothing's coming along and hitting it into the air which is what I thought they do, if they're meant to be grabbing and throwing it ig it might make a couple holes in the z0 floor but I feel like anything more than that is pretty silly, throwing it 8m up through two floors is pretty ridiculous.

**Comment by TheEskir** [comment]
Petition to have this be a feature. Would be neat if the car still fell down again afterwards. Maybe have it cause a fire too, for added dramatic effect.

No, in all seriousness though, this would be grest for crazy cataclysm
