### ISSUE TITLE
Backpacks options to fit Large/Huge anatomy.

### ISSUE THREAD

**Issue by kj122576** [CleverRaven/Cataclysm-DDA#66908]
### Is your feature request related to a problem? Please describe.

Was trying a run with the Extra Mutated Scenarios mod, playing as a post threshold ursine, when I noticed I couldn't use a duffel bag. I thought this was odd but accepted that maybe I'd just need to refit it or something of that nature, but when I tried to do so with a tailors kit I lucked into, I had no option to resize it. Looking further into my options, there were no XL versions of the backpacks available.

### Solution you would like.

As in Real Life, unless your body shape actively interferes with wearing items on your back I think that Backpacks should generally fit any size of mutant due to most having adjustable straps.

### Describe alternatives you have considered.

Alternatives that would also be acceptable is either allowing resizing of backpacks as with other clothes, or to add XL variants as with other forms of clothing. Further alternatives would be adding more backpacks that fit mutant anatomy, though due to the needed labor it's also the least reasonable alternative.

**Comment by randomtyper** [comment]
Slap "OVERSIZED" flag on ones that have adjustable straps,. Should be an easy work and a good first PR, the main reason it was not done earlier is that most contributors are busy with other things.

**Comment by Procyonae** [comment]
Ye duffel bags specifically have OVERSIZE as of #66063, if there are any bags without it that you feel should have it in newest exp happily point them out
