### ISSUE TITLE
Hand paddles can be used on land!

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#66900]
### Describe the bug

Hand paddels can be used on land! Iam not a Sailor but i guess that can not be right XD. They are even more efficent than foot pedals from a bicycle. 

### Attach save file

![hand paddle](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/04687a4f-81a4-4f23-9603-6e062ac83ca8)
![hand paddle 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/9ca4d64c-d92a-44c4-98ec-01d7930acf6a)
![hand paddel 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/bb311a62-3a46-428e-a8b1-210d6f94943d)

### Steps to reproduce

Just make yourself a hand paddle bicycle and drive around. Notice that you can even do that! And it is more efficent than using a normal bicycle!

### Expected behavior

Not beeing able to efficently use hand paddels on land! 
It would be enough to just not let the player use them, if there not on water.

### Versions and configuration

Windows 10
Version: 9b054bd (tiles)
Build: 2023-07-14-0542 (6 hours ago)
mods: Dark days ahead

**Comment by ashGlaw** [comment]
Now I'm picturing some sort of bizarre bicycle/rowing machine hybrid. I guess you'd steer with your feet?

**Comment by Krieger1999** [comment]
> Now I'm picturing some sort of bizarre bicycle/rowing machine hybrid. I guess you'd steer with your feet?

Haha!
Rowing though air, with hand paddles is realy ridicilous.

**Comment by fairyarmadillo** [comment]
https://www.youtube.com/watch?v=nGJkfwq8uoI

doot doot

**Comment by estebandellasilva** [comment]
Row, row, row your bike
Gently down the street
merrily, merrily, merrily, merrily,
Life is but a game.
