### ISSUE TITLE
Damaged armor should lose coverage

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66907]
### Is your feature request related to a problem? Please describe.

One of the most important parts of armor sustaining damage should be coverage loss. If your gambeson gets a tear in it, most of it will still be pretty protective but the specific location the tear happened will not be. This would lead to small % losses in total coverage until it's in tatters which barely cling onto your body anymore. This would also be an important consideration for hazmat - if your hazmat suit gets a tear and goes from 100% to 99% coverage, you're probably screwed if you needed that hazmat for hazmat reasons.

### Solution you would like.

Gear sustaining damage should lead to small losses of coverage.
This should probably not affect any BELTED gear because having damaged storage gear would be almost beneficial since it makes it less likely to get targeted by attacks and thus damaged.

### Describe alternatives you have considered.

There are a lot of armors that should become basically useless after being used to absorb damage. Any ballistic vest is going to only be able to absorb a few rounds before becoming deadweight vs bullets. Likewise bike helmets are meant to be thrown away after they're used once to protect your head in a crash. But these items are usually STURDY and can sustain dozens or hundreds of attacks before degrading.

**Comment by Qrox** [comment]
> This should probably not affect any BELTED gear because having damaged storage gear would be almost beneficial since it makes it less likely to get targeted by attacks and thus damaged.

I think if it's realistic then it's fine. The problem is rather that damaged storage gear can hold as much items as undamaged ones.

> Any ballistic vest is going to only be able to absorb a few rounds before becoming deadweight vs bullets

The armor plates in-game already have a chance of turning into shattered plates after abosobing enough damage. For the vest itself (presumably made of some ballistic fabric), won't it still have protection in other places even if it is damaged in one place?

**Comment by fairyarmadillo** [comment]
> The armor plates in-game already have a chance of turning into shattered plates after abosobing enough damage. For the vest itself (presumably made of some ballistic fabric), won't it still have protection in other places even if it is damaged in one place?

Soft kevlar relies on the weave being able to distribute impact across a wide area of the body by having long and intact threads which are pulled taut against each other across the garment. When you start shooting a vest, in addition to ripping some of the fibers, the impact of the bullet also stretches them, which starts to create weak areas where the fabric is technically intact, but some of its ballistic protection goes away.

Police and security forces usually throw vests away after they get hit even once, or they use them for messing around on the range etc. I think a survivor could probably peel off the nylon cover and just take out and replace some of the damaged sheets without worrying too much. But guns should generally damage all types of armor a lot faster than they currently do.
