### ISSUE TITLE
AR-15s duplicating 

### ISSUE THREAD

**Issue by Fuppy1337** [CleverRaven/Cataclysm-DDA#66926]
### Describe the bug

Whenever I've left my AR-15 back at base, specifically if I've worn it over the shoulder with the strap, sometimes when a zombie grabs and pulls something off it'll create a new AR-15 to pull off out of thin air.

### Attach save file

[Cove City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12063017/Cove.City.zip)

### Steps to reproduce

1. Wear a AR-15 via the rifle strap
2. take it off and leave it somewhere
3. have a zombie grab an item off of you only to find an AR-15 created from thin air 

this is the only way that I've seen it replicated in game.

### Expected behavior

a zombie pulls another item off of your person rather than a nonexistent AR-15

### Versions and configuration

OS: Windows 10
Game Version: bf5848d (64-bit)
Graphics Version: Tiles (MXotto+)
In-game Language: English (US)
Mods Loaded: Stats Through Kills

### Additional context

the steps to reproduce doesn't create an AR-15 each time, but it did happen to me twice over a two hour play period. so it can't be all that uncommon.

**Comment by RenechCDDA** [comment]
Not able to reproduce and this save seems to be entirely unrelated?

**Comment by Fuppy1337** [comment]
> Not able to reproduce and this save seems to be entirely unrelated?

yeah sorry, I wasn't sure what's relevant to this. I'll try and mess around with it a bit more to see if I can find a specific condition that makes it happen.
