### ISSUE TITLE
 leaping amalgamation is too strong-too early-in monster evo

### ISSUE THREAD

**Issue by teapot156** [CleverRaven/Cataclysm-DDA#66921]
### Describe the bug

These cocoon monster are excessive and appear before the zombie predator-which they exceed in combat.

3 leaping amalgamations ambushed me out of nowhere and theres nothing that you can do without advanced weaponry.

Having thick hide, high agility, and high pierce? 

### Attach save file

N/A

### Steps to reproduce

Combat and compare to zombie hunter / predator

### Expected behavior

There needs to be some kind of weakness to every zombie type unless its an elite/rare class.

The same thing happened when flesh-raptors were first added. It's like the creator of the monster designed it too be the most effective with considering the balance.

(Please thoroughly test monsters before you add)

### Screenshots

N/A

### Versions and configuration

16edf49 (tiles)
2023-07-15-0601

### Additional context

N/A

**Comment by teapot156** [comment]
I'm looking at its stats:

The problem with it is it has too much HP (or armor). Given that its armor is apart of its characteristics-i'd say a change to HP is in order. Zombie dog has 36, Zombie has 80, zombie predator has 90 at 31 difficulty, **leaping amal is 135 hp at 33 difficulty** (also PATH_AVOID_DANGER_2, HARDTOSHOOT, 30.0 ballistic armor, 16.0 bash armor,  16.0 pierce. Very short cooldown on leap and bite.) Good luck with escape.

**Comment by teapot156** [comment]
**The vigilant amalgamation** as another extremely annoying monster from the group.

 Its fast, has great eyesight, flees from you, and continually screams again louder than the **screecher zombie**. Another instance where this added monster group over-writes the roles of other zeds. 

Can someone please explain how I can disable this entire group of monsters?

**Comment by Venera3** [comment]
They happen after spending 6 hours as a corpse, turning into a cocoon, then leaving for at least a day, then returning. Add to that them being limited to medium+ cocoons and they are comparatively rare - barring frequently-reactivated areas like subways I suppose, though the cocoons are easily cleaned up by anything zombie-hostile.

If you want to mod them out you can remove the non-null entries in the high-level cocoon group.

(I have tested them :) )
