### ISSUE TITLE
An improvement on swimming mechanics (buoyancy in particular)

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#66932]
### Is your feature request related to a problem? Please describe.

Currently swimming in game is... Not in a good state. Neither in terms of realism, nor in terms of enjoyability. Let's just look at few examples.

Example 1: Character with 0 in athlethics, can float in water when naked. Sounds legit so far, human body is slightly buoyant and one won't drown unless he panicks, which is the main reason of drowning IRL (and is not modeled in game so far). Now, let's give the character some appropriate clothing. Say, a wetsuit. IRL those beside keeping divers warm also provide a degree of floatability (or at least do not contribute to drowning of the wearer), CDDA strives to be realistic, so that should work, right? WRONG. Character is better off wearing nothing when swimming if whe wants to not drown. This also leads to moments where wearing something like a wool hoodie when swimming is better than wearing a full wetsuit set.
Example 2: Character with 0 in athlethics. Again. He has a jerrypack. Empty one. Which way of bringing it on the other side of the river is better (is faster/does not drown the character)? Wearing it or crossing with it in hands? RL logic would suggest both ways should not drown the character, as the one of the original German jerrycan's (after which modern jerries are modeled) selling point was that it could float even when filled with gasoline (it has an air pocket). As for speed, IRL wearing a jerrypack on front/back would free up hands to help swim faster. In game... Well, good news first: jerrypack will not drown the character. BUT only if character holds it in hands when swimming. Well, it could be explained that character uses the jerrypack as swimming aid, but that implies that character can somehow use a metal ingot for same purpose. Or a non-watertight backpack full of same metal ingots. Wearing a jerrypack will drown such character, though. 

I hope the discrepancies are obvious enough for the reader that I can go to conclusions of this part of issue.

In the current state of the swimming mechanics, there are next issues:
1. Swimming clothing (that is not specific pieces like swim fins, swim goggles and air tanks) is not beneficial to the player for their IRL purposes (besides warmth, it is important, but there are other reasons why wetsuits are used over olden diving suits, mobility in particular) - providing buoyancy and increasing swimming speed (example: https://en.wikipedia.org/wiki/History_of_competitive_swimwear#Non-textile_swimsuits). IRL wearing a wetsuit won't reflect so adversely on one's swimming/flotation capabilities to make wearing nothing at all (or even clothing that is hands down bad to swim in, like said wool hoodie) more viable (as it is in game now);
2. Watertight containers capable of floating (such as jerrycans that can float even when filled) do not help character with not drowning when worn (jerrypack)/carried in inventory (jerrycan);
3. Heavy items carried in hands have no effect on character's floatability. In game, the best way to cross a water obstacle is packing your stuff into a bag and carrying it while swimming across that obstacle. While keeping stuff that can be waterlogged (like boots) over water is a good idea IRL, carrying all your inventory in your hands (even panties/briefs/trunks/bikini) should not be the best way to cross water obstacles, as that gear restricts hands and pulls on them, restricting swimming and buoyancy capacities. After all, it is weird if you have to take off a wetsuit to cross a river, right? Ideally, if character wears only wetsuit gear (water friendly, with waterproof as a maybe) and has a floatable dry bag, he should be able to cross the river with no preparation (because he is already prepared by wearing all that not necessarily optimal and somewhat specialized gear) and fear of drowning.

### Solution you would like.

The preferred by me and probably the easier way of making all this make at least some sense would be:
1. All clothing that has WATER_FRIENDLY flag has its current volume subtracted from the carried weight used in swimming speed calculation. As water has ~1 g/ml density, it would allow for clothing that is denser than water (has weight in grams/volume in ml ratio of >1) to compensate for some of its weight, and for clothing that is less dense than water to compensate not only its weight, but allow to help lift some other item. This will allow to make diving rigs (buoyancy controllers), too;
2. Clothing with WATERPROOF but without WATER_FRIENDLY flag gets its volume subtracted, but only when worn. When it is in some container, it gets waterlogged, which is represented by it not contributing to player's buoyancy;
3. Other clothing does not compensate for its weight and buoyancy;
4. Rigid watertight containers (items, not clothing) contribute their whole volume in weight compensation, they will still be able to drown you if you filled them with something dense (like ammonium nitrate or steel chunks);
5. Non-rigid watertight container items contribute their filled volume;
6. Weight compensation should be added from the first container in stack (so a filled zipper bag inside a gallon-sized zipper bag is not counted towards formula, but the gallon-sized zipper bag is counted, and if that gallon sized zipper bag is inside a dry bag, only dry bag volume is counted);
7. Possible edge cases: dive bag is of mesh variety (filled with water on submersion), but will count towards weight counteraction with all its contents, may want to use a more complex formula for clothing with containers, something like this: (unloaded_volume - watertight_containers("magazine_well")) + watertight_containers( compare(return largest: "magazine_well" or "contains_volume"));
8. Alternatively, allow that as dive bag is not waterlogged even if filled with water (easier to move with in water, does not pull wearer down as much), and buoyancy force realistically should affect all items in player's inventory in some way anyway;
9. Alternatively, make all clothing that fits the requirements only contribute its unfilled volume (then dry bags do not fit the bill, as they are expandable and are truly watertight);
10. Make items held in hands participate in swimming speed calculation, introduce a check on whether the arms are free and apply a bonus to swimming speed if true.

Wearing appropriate swimming clothing should reward the player in relevant activities (as it is beneficial IRL), allowing to cross water obstacles without much/any preparation while not needing to use specific tradeoffs (swim fins) and spending consumables (rebreathers, scuba tanks), especially if sufficiently lightweight in terms of equipment, on the other hand, wearing inappropriate clothing (fur coats, winter jackets, plate armor), should punish the player even if one takes it off, without being able to circumvent it through swimming with it in hands.

The new mechanics will hopefully lead to more interest in water-centered gameplay, and, thus, more water-centered content.

### Describe alternatives you have considered.

Splitting swimming speed (most adversely affected by filled and carried inventory volume, then encumbrance and weight) and buoyancy (affected adversely by inventory weight, affected positively by item volume, almost not affected by encumbrance).

Calculate density of each item and assign modifiers according to flags and properties (water friendliness, water tightness, water proofness), calculate average adjusted density of player's inventory and then use that value in swimming calculation formula(s), with values lower than 1 g/ml being beneficial to buoyancy and values higher than that value being detrimental.

Make too high of buoyancy not allow to dive under the water, this will allow to yeet the FLOTATION flag and replace it with a more granular and realistic system.

Finally, a final alternative, allowing CDDA Chezzo Wiki to still be a viable source of information on the swimming mechanics.

### Additional context

None. Will add if needed.

**Comment by physics-enthusiast** [comment]
Concurring on the current buoyancy system making little physical sense. If there are no objections, I would be interesting in implementing some of the above suggestions. Assuming swim speed is a simulation of drag limiting the speed at which you can move through water (and hence increasing movecost), I think it's fine to leave it as is and just decouple sink/swim from it. Maybe additional changes could include allowing a character with negative buoyancy to still remain above water at the cost of stamina drain (up to a maximum downwards force compensation depending on STR, mutation modifiers and certain equipment worn).

**Comment by Frank-Einstein** [comment]
I just started playing this game a few days ago and today I spawned on a small island with an helicopter crash scenario. I wasn't able to swim even half way before I drowned, even tho I barely had basic stuff on me... I'm curious to know what I was supposed to do here. It doesn't seem really fair.
