### ISSUE TITLE
Protection values are displayed incorrectly

### ISSUE THREAD

**Issue by deepvelocity** [CleverRaven/Cataclysm-DDA#66930]
### Describe the bug

When checking body parts status, I noticed that protection values for environmental/fire/acid are displayed incorrectly sometimes: worst/median/best do not correspond to actual worst/best values.

### Attach save file

[Olaton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12063188/Olaton-trimmed.tar.gz)

### Steps to reproduce

1. Put on items from the screenshot on the character
2. Check body status ("{" by default)
3. Be surprised

### Expected behavior

I expected to see actual worst, median and best values for those protections.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/4355197/27398516-edd4-412c-ac4d-b2981d05557b)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/4355197/26133cac-eef6-4b99-a914-bb1426c7a30d)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/4355197/e7035347-61fa-4cc8-a0bd-5b01ca14591c)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/4355197/72e9c360-03ff-4cb9-aa62-d93da06ffaaa)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: e2b65580c7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
Looks like it doesn't like your fur kevlar jumpsuit. Judging by the values, it's due to the recent resist changes. The display just isn't very smart.

**Comment by bombasticSlacks** [comment]
It's because acid and fire use the roll value for a different reason than standard armor. For standard armor it is a roll to see if the armor is counted, for environmental it's something else.

So for best worst and median we just sum all values with a roll of 0 (everything protects), 100 (nothing protects), 50 (some stuff protects), but passing those to environmental messes things up.
