### ISSUE TITLE
strenght stat should affect ranged weapons that requires arm strenght

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#66935]
### Is your feature request related to a problem? Please describe.

a character with strenght 19 has the same throwing damage as the one with 8. but when it comes to throwing arm strenght is very important.

### Solution you would like.

scaling throwing damage with strenght. i think %5 damage increase per strenght above 8 would be good while %5 decrease below 8. 
adding THROWING flag to ranged weapons that require arm strenght like staff sling. making their damage scale scale with strenght.

### Describe alternatives you have considered.

none

### Additional context

in #66751 i also suggested adding THROWING flag for weapons that requires arm sthrengt to benefit from "THROWING_DAMAGE" and not from RANGED_DAMAGE enchantment. (if added)

shot put is a good sport.

**Comment by fairyarmadillo** [comment]
Strength already does add to the damage of thrown weapons. Per ranged.cpp:

```
int Character::thrown_item_adjusted_damage( const item &thrown ) const
{
    const std::optional<int> throw_assist = character_throw_assist( *this );
    const bool do_railgun = has_active_bionic( bio_railgun ) && thrown.made_of_any( ferric ) &&
                            !throw_assist;

    // The damage dealt due to item's weight, player's strength, and skill level
    // Up to str/2 or weight/100g (lower), so 10 str is 5 damage before multipliers
    // Railgun doubles the effective strength
    ///\ARM_STR increases throwing damage
    double stats_mod = do_railgun ? get_str() : ( get_arm_str() / 2.0 );
    stats_mod = throw_assist ? *throw_assist / 2.0 : stats_mod;
    // modify strength impact based on skill level, clamped to [0.15 - 1]
    // mod = mod * [ ( ( skill / max_skill ) * 0.85 ) + 0.15 ]
    stats_mod *= ( std::min( static_cast<float>( MAX_SKILL ),
                             get_skill_level( skill_throw ) ) /
                   static_cast<double>( MAX_SKILL ) ) * 0.85 + 0.15;
    return stats_mod;
}

```

**Comment by alp7292** [comment]
oh i guess rocks are not heavy enough
