### ISSUE TITLE
Submachine guns need a range bonus review.

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#66947]
### Is your feature request related to a problem? Please describe.

In game, all MP5 series guns have a bonus range of 14. The MP5A2 (225 mm barrel), MP5K-PDW (140 mm barrel length, some pistols have longer ones) and MP5SD (a proprietary silencer that slows bullet to subsonic speed), despite all of them have differing barrel lengths and constructions, all of those increase range of a 9x19 mm FMJ bullet by factor of 2 from 14 to 28. This translates to ~330 m effective range if going by tiles*12 formula, despite IRL the effective range of MP5A2 is stated to be about 150-200 m. The effective range for MP5K is even lower at 100 m.

Sources:
https://weaponsystems.net/system/227-Heckler+&+Koch+MP5
https://weaponsystems.net/system/229-Heckler%20&%20Koch%20MP5-K
https://www.militarytoday.com/firearms/hk_mp5.htm

At the same time, P90, which has the same stated effective range of 200 m (with caveats: it defeats Level 3 body armor at 200 m while having "maximum effective range" of 400 m, at which bullet delivers 85 J of energy to target) as full-sized MP5A2 (200 m).
Despite that, the ingame P90, which has a barrel 264 mm long has the same bonus range (0 tiles) as a FN 5-7 with barrel length of 122 mm.

Quoting https://www.remtek.com/arms/fn/p90/data/concept.htm:
"Three rounds are available for the P90 at this time. The standard ball round, called the SS190, features an overall length of 1.6 inches (40.5 mm), a projectile weight of 31.0 grains (2.02 grams) and a muzzle velocity of 2,345 fps (715 mps). The SS190 projectile features steel core in front of an aluminum core toward the base. The bullet penetrates about 10 inches (26 cm) of 10 percent ballistic gelatin, according to testing conducted at the Royal Canadian Mounted Police Academy in September 1997. The SS190 round will also penetrate 48 layers of Kevlar, the typical "Flak jacket" (including CRISAT protection, which is a combination of titanium and Kevlar) worn by infantry to protect them from shrapnel produced by exploding devices, or a standard PASGT (U.S. Kevlar) helmet at 150 meters (164 yards), which is the effective range of the P90 Personal Defense Weapon. The weapon will still defeat Level 3 body armor at 200 meters (219 yards). The "maximum effective range" using the NATO definition (the maximum range where a weapon's projectile will still deliver 85 joules on target) is 400 meters (437 yards). Thus, according to NATO standards, the P90 is theoretically able to deliver a lethal wound on a protected target at 200m and an unprotected target at 400m if the round hits a vital area. Personally, I would not be enthusiastic about engaging targets beyond 150m with the standard SS190 round."

Yes, 5.7x28 is not a long-ranged round, but I think a barrel that is over 2x as long should have at least some effect.

The situation is even less logical when looking at PS90, which has a 16 inch (407 mm) barrel... And has no bonus range. At all.

### Solution you would like.

Easy fix: axing the range bonus from MP5s, as it looks suspiciously like someone just copied bullet ranges to guns and they added together.

Hard fix: giving bonus ranges from +1 up to +5-7 tiles depending on barrel length. No +14 range tho.

### Describe alternatives you have considered.

Nerfing bonus range of MP5K and MP5SD to ~7 tiles. Still more than IRL at 21x12=252 m, but much more consistent in terms of logic (shorter barrel -> worse ballistics -> lower range).

Buffing P90 bonus range to about 13-14, putting it about on par with MP5A2 in terms of range. Giving PS90 bonus range of ~18, putting its range at 32... Wait... Wait.

Kel-Tec P50 has a pretty long barrel, too, it may use ~6 tile range bonus.

Having no semblance of consistency in submachine gun stats. Having machine pistols be as good at long ranges as full-size SMGs. Having SMGs with 2/3-8/9 of assault rifle range.

### Additional context
None

**Comment by randomtyper** [comment]
Wait, Kel-Tec SUB-2000 has 18 bonus range. What?

Hm, MP40 got +12 range while having 251 mm barrel (longer than MP5), sure, we can give some slack on account of MP 40 being traight blowback, but MP5 still has shorter barrel, so it should not have more than +12.

Aight, I am pulling out Blame tool...

**Comment by randomtyper** [comment]
@anoobindisguise, did not expect such BS from you.

**Comment by anoobindisguise** [comment]
?
Looks like a copy-from error. They're inheriting the range when only the default mp5a2 should have it.

**Comment by randomtyper** [comment]
> ? Looks like a copy-from error. They're inheriting the range when only the default mp5a2 should have it. Range is already arbitrary but I saw that the effective range of a MP5A2 was 4x that of a Glock 17 (200m vs 50m) so compared to Sub2000 or Cx4 Storm +14 was lesser but still existent.

The problem is that Cx4 has almost the same range as an intermediate round rifle (500 m IRL for M4 carbine). While having MUCH less aerodynamic and powerful cartridge and only having longer barrel to compensate.

Truly, Karol's axiom in work: "If it has such high values, maybe it shouldn't? Instead of pulling other stuff to this level?"

**Comment by randomtyper** [comment]
Argh, screw it, guess I got another PR to make in some time...
