### ISSUE TITLE
Both info and import are bound to "i" by default in debug menu

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#66945]
### Describe the bug

When opening the debug menu, both info and import are bound to the "i" key. This makes it so that the key binds listed in the attach save file can cause confusion when hitting i and the import menu opens instead of the info menu.

### Attach save file

N/A

### Steps to reproduce

1. Open debug menu
2. hit "i" key
3. have import menu open instead of info

### Expected behavior

In the bug submitting form, one of the steps is attach save file, which lists that hitting "i" will open the info menu. This can easily be figured out, but it is still a discrepancy I believe should either be fixed in the game or on GitHub.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/20823837/4608345c-efc9-4818-9cab-b6e8913368a7)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-3026-g30fe61a8fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RenechCDDA** [comment]
Should be resolved by #66794
