### ISSUE TITLE
Plugged in tools cause crash when repairing

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#66944]
### Describe the bug

When I try to repair using a soldering iron/arc welder that is plugged in, I get a seg fault. If I repeat the same steps with either tool using batteries, it works as intended. 

### Attach save file

[Tonica-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12064447/Tonica-trimmed.tar.gz)

### Steps to reproduce

1. Have broken item
2. Have arc welder plugged into stationary power grid
3. use the action menu to activate the welder then choose repair
4. choose the item to repair and have the game segfault

### Expected behavior

I should be able to repair with plugged in appliances the same way I can with ones on battery. 

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-3026-g30fe61a8fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12064460/crash.log)

**Comment by Kamayana** [comment]
I'll take a look.

**Comment by teapot156** [comment]
if the plugged in tool has a battery, it wont crash. IE. makeshift welder. Problem is that sort/zones tend to pull batteries from tools

**Comment by ilovehans10** [comment]
> if the plugged in tool has a battery, it wont crash. IE. makeshift welder. Problem is that sort/zones tend to pull batteries from tools

I don't think I have ever had a battery removed from a tool by a zone. I don't have batteries in my tools because I don't want all of my batteries tied up in devices.

**Comment by Kamayana** [comment]
The error is specifically caused by the repair menu trying to write the name of the ammo in the window, and since a plugged in device doesn't have any batteries, it's trying to write the nonexistent name of nonexistent ammo. I did fix it in my cable rework PR, though that's a big PR so it might take a little longer to be reviewed
