### ISSUE TITLE
After choosing weight: XXXL you will start the game with guaranteed common flu

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#66943]
### Describe the bug

After choosing weight: XXXL you will start the game with guaranteed common flu

### Attach save file

N/A

### Steps to reproduce

1) Create a character with weight: XXXL trait
2) See, that you will have common flu guaranteed right after the game is starded

### Expected behavior

Not to have flu at the begining of the game

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 30fe61a [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Без ж/д станций [No_Rail_Stations]
]

**Comment by Night-Pryanik** [comment]
This shouldn't be an issue anymore after #66334.

**Comment by GuardianDll** [comment]
user's Game Version says it happened exactly on the version that got 66334

**Comment by KHeket** [comment]
> This shouldn't be an issue anymore after #66334.

I waited for your good flu/cold update and always playing with XXXL trait, and I tested it at your version. So this changes in flu/cold logic causing illnes at the begining. May be problem in very bad health because of big weight, I dunno

**Comment by anoobindisguise** [comment]
Every single npc in my world became sick after the update as did my character who was Feel Great / Phase Immersion'd. I think it's not just xxl
