### ISSUE TITLE
IR doesn't see through smoke

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66948]
### Describe the bug

Infrared vision should be able to see through smoke as it does IRL but it does not in game.

### Attach save file

n/a

### Steps to reproduce

1. Spawn IR goggles and wear them and turn them on.
2. Spawn smoker zombies.
3. Observe being unable to detect the smokers through IR.

### Expected behavior

IR should show up through smoke clouds.

### Screenshots
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56016372/50e698c7-835c-4edf-87f4-0e5a12de1960)

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 944de85 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by PatrikLundell** [comment]
Don't think I can claim to confirm it as my encounter with this issue happened a year or so ago, when I tried to use IR goggles exactly in order to deal with a smoke zombie. However, I'm not the least surprised to see that it hasn't fixed itself since then.

**Comment by teapot156** [comment]
Unless its hot smoke… is the smoke hot? 😉

**Comment by PatrikLundell** [comment]
You're not burned by the smoke, so it shouldn't be hot. IF it was hot, the smoker zombie would have to be even hotter though.

**Comment by teapot156** [comment]
What if he's releasing a gas that's reacting with the air and is being ignited-heating up as a result.

**Comment by PatrikLundell** [comment]
You're not burned by the smoke, and there is nothing in the description indicating the smoke is hotter than the zombie producing it.

**Comment by Profit0004** [comment]
IR is scattered by smoke and is used as a defense system in some military vehicles and infantry because of it.   I believe this is intended, and if not logically it should be.

**Comment by kholat** [comment]
Generally when people refer to "smoke" it means some particulates in the air that usually scatter visible light, IR passes through. If the zombie is hot and the smoke is cool, you should be able to see it through IR, but i think this zombie is actually meant to be "made out of smoke", so you cant discern things from IR imaging if the emit all the same.

**Comment by PatrikLundell** [comment]
I very much doubt smoker zombies would evolve to deal with IR detection given that this is a very specialized threat they're almost never exposed to, even if military smoke usage has evolved into providing IR masking.

Anyway, there is nothing indicating the smoker zombie not being a zombie but a smoke cloud. Rather, it seems to emit smoke, possibly through fairly low temperature burning (again, there is no burn damage from engaging them).

**Comment by kholat** [comment]
I said this judging from the fact that it leaves no corpse, instead it explodes. That is, to me, indicating its somehow made out of smoke (then IR should not work). If its not and its a "normal" zombie, then IR should work yeah, considering this game sees all zombies as constant temperature creatures.

So its a question of what it actually is.
