### ISSUE TITLE
Dropping an active (on) chainsaw, and then doing anything else crashes the game

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#66946]
### Describe the bug

Dropping an active (on) chainsaw, and then doing anything else, crashes the game.

### Attach save file

N/A really, reproduction is per the steps, but i made a test char for a clean world with a chainsaw in hand.
[Testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12064531/Testing-trimmed.tar.gz)

### Steps to reproduce

1: Spawn in either a gasoline or electric chainsaw that is off. Fuel\battery if you need.
2: Wield it, and turn it on.
3: Drop it.
4: Move, pause, or do anything that takes time.
5: Game crashes.

### Expected behavior

I expected the game not to crash ^^

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12064517/debug.log)

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12064518/crash.log)

**Comment by RenechCDDA** [comment]
Should be resolved by #66866

**Comment by EternalLaughter** [comment]
Ah, that's a big one, i see!
Then i'll close this report.

**Comment by NetSysFire** [comment]
Reopening because said PR is not yet merged. @Hirmuolio will need to add that to their PR.

**Comment by EternalLaughter** [comment]
I assumed then that since this was closed it was fixed. But as i'm testing build 0517, the merge after https://github.com/CleverRaven/Cataclysm-DDA/pull/66866 i can still reproduce a game crash for both types of chainsaws as specified above.
