### ISSUE TITLE
Creating mutagen samples from post-thresh mutant NPCs

### ISSUE THREAD

**Issue by GalacticApple** [CleverRaven/Cataclysm-DDA#66957]
### Is your feature request related to a problem? Please describe.

While there are certainly plenty of samples in labs and plenty of animals out in the wild, there still might not be quite enough for mutating large numbers of NPCs (as I'd say that samples are the primary bottleneck in mutagen production).

I've been using the new mutation system to make myself a custom super-mutant that pulls from multiple mutation trees. However, in the very late game I wanted to start getting a bunch of followers together and expanding my faction. As part of this, I also wanted to mutate them in a similar way I did with my main character. However, this is simply not practical with the current availability of samples. 

### Solution you would like.

My idea was that if samples are just bits of blood, hair or tissue that represent some genetic "essence" of a mutagen category, I thought that it would make sense for post-threshold mutants to be able to produce samples of their relevant category. This could be done by having the player-mutant use a blood draw kit to produce a unit of [insert category]-mutant blood. This could then be incorporated into a new recipe that would use this to produce a sample. 

Since making samples this way would require you to have already gotten post-thresh, this method would only be practical in the later game. Also, since you can't spam the blood draw kit without suffering from blood loss, there is still a limit to how many samples you can make at once. As such, this method could be seen as a valid alternative for creating a mutant army without having to explore multiple Gigs worth of territory to amass the needed samples.

### Describe alternatives you have considered.

An even more powerful (though more difficult to implement) addition would be that the blood created by the draw kit is specific to *you* (or whoever the blood is drawn from). This would be used to create a generic sample of *you* which would be used in a generic *you* mutagen. This mutagen would then mutate its users towards whatever mutations you had at the moment you drew the blood. This would allow you to much more easily mutate followers to your "ideal" without having to worry about their genetic damage or managing multiple mutagen strains.

**Comment by fairyarmadillo** [comment]
I don't think there's any real need to allow the player to create a ton of super mutant NPCs without doing any real work, and samples aren't just bits of skin and hair. You have to kill and dissect a mutated creature to get them. They're left vague on purpose, but in general you should be picturing very specific bits of brain and organ matter. There is by design no humane way to collect these samples.

If you want to mutify a lot of NPCs, go raid labs. They have plenty of samples and mutagens.
