### ISSUE TITLE
npc_test frequent test fail

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66968]
### Is your feature request related to a problem? Please describe.

npc_test is failing the test case npc-board-player-vehicle very frequently with ```(~[slow] ~[.],starting_items)=> ../tests/npc_test.cpp:386: FAILED:
(~[slow] ~[.],starting_items)=>   REQUIRE( companion->pos() == player_pos + point( 2, 0 ) )
(~[slow] ~[.],starting_items)=> with expansion:
Error: (~[slow] ~[.],starting_items)=>   (61,62,0) == (62,60,0)``` 

### Solution you would like.

Tests not to fail all the time
~~As far as I can tell this is happening bc the NPC decides to get in the back reclining seat of the ambulance rather than the passenger seat because it's a shorter distance. I have no idea whether the test intentionally only wants them to go for the passenger seat or not.~~
No idea what the problem is see the PR below for a failed fix

### Describe alternatives you have considered.
~~Just allowing the other seat in the test.~~
Removing the test until someone finds a proper solution

**Comment by SurFlurer** [comment]
Related:
https://github.com/CleverRaven/Cataclysm-DDA/pull/66877#issuecomment-1636900306

**Comment by Procyonae** [comment]
I'm testing a fix now ^_^
