### ISSUE TITLE
Keep getting the "You've stepped into some sludge" constantly without cause

### ISSUE THREAD

**Issue by tylerhardy** [CleverRaven/Cataclysm-DDA#66963]
### Describe the bug

Keep getting the "You've stepped into some sludge" constantly when there is nothing around me to sludge my character.  Been going on for over a couple of in game days.

### Attach save file

[](url)
[Elkview-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12065871/Elkview-trimmed.tar.gz)

### Steps to reproduce

Walk around and message appears with not slime/sludge entities nearby.  

### Expected behavior

I expected to not continuously be sludge when not moving or when not around slime/sludge entities.  

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/8368225/45a72f60-fd23-403e-a70f-96649deac7e2)

### Versions and configuration

- Windows 11
- 30fe61a (tiles)
- Use terminal not tiles for graphics
- Mods, Not sue, I just used the default in world creation
- English

**Comment by Procyonae** [comment]
I mean there is literally a pupating zed in vision but waiting on the tile shouldn't spam the message regardless

**Comment by tylerhardy** [comment]
Oops, haha, didn’t realize one was in sight.  I just noticed that I also get the message spammed while sleeping which I image isn’t expected behavior, haha.

**Comment by Procyonae** [comment]
I can't tell why this is happening nor what caused it, about the only relevant recent PR I can see is #66700 but I can't tell how that would've caused any issues

**Comment by eturner** [comment]
This happens to me when I load my world in a build from sources pulled yesterday. But not in my build from the 11th.
I had to go back because it crashes during sleep with hundreds of sludge messages, though the crash may be unrelated.

**Comment by teapot156** [comment]
Getting this. Anybody check sewers?

**Comment by FinWeirdoh** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91383778/9df9a40e-e017-44cf-9823-f06eb908b564)
I get stepped on sludge messages while waiting near town.. If I move away from town messages stop appearing.

**Comment by FinWeirdoh** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91383778/2afe6564-55ef-41aa-9742-11e4aee678e6)
same bug seems to effect web and smoke messages too

**Comment by teapot156** [comment]
> ![image](https://user-images.githubusercontent.com/91383778/254261209-2afe6564-55ef-41aa-9742-11e4aee678e6.png)
> same bug seems to effect web and smoke messages too. This all happened while driving past the bugged town spot

Can you debug and check -z levels?

**Comment by FinWeirdoh** [comment]
> Can you debug and check -z levels?

I used debug and revealed a multilevel science lab under the area where bug happens. Anything else I should check for?

**Comment by hatamekyu** [comment]
This always happens whenever i'm near or in a lab.. It's weird.

**Comment by teapot156** [comment]
> > Can you debug and check -z levels?
> 
> I used debug and revealed a multilevel science lab under the area where bug happens. Anything else I should check for?

I’ll check my area later to see if theres a correlation.

**Comment by Procyonae** [comment]
I guess it must be incorrectly reporting other things in those fields as though they're you, I'll have another look

**Comment by Procyonae** [comment]
> I guess it could be incorrectly reporting other things in those fields as though they're you, I'll have another look

Ye that seems to be what's happening, I'll see if anyone knows why that's suddenly happening

**Comment by Procyonae** [comment]
#67010 seems to have fixed this

**Comment by Relvl** [comment]
Looks solved after the update

**Comment by NetSysFire** [comment]
Closing as fixed.
