### ISSUE TITLE
Typos in recipes for weapons and armor (bo, brigandine armor)

### ISSUE THREAD

**Issue by WhitePaperWraper** [CleverRaven/Cataclysm-DDA#66975]
### Describe the bug

The following armor recipes seem off to me:
armor_qt_coat_brigandine_shoulders
armor_hc_coat_brigandine_shoulders
armor_ch_coat_brigandine_shoulders
The recipes for all of these items look kinda like this:
> Components: 1 high steel brigandine coat OR 1 pair of high steel shoulder guards 

Same happened with the upgrades to 'bo' quarterstaff , specifically the following items:
ch_steel_staff
hc_steel_staff
lc_steel_staff
mc_steel_staff
qt_steel_staff
The recipe look like this:
> Components 1 bō OR chunk of medium carbon steel (2) 

There may be more, those are all I found manually

### Attach save file

N/A

### Steps to reproduce

1. Open the game
2. Get high fabrication
3. Check recipes for quarterstaffs
Or check item browser: [here](https://cdda-guide.nornagon.net/item/armor_hc_coat_brigandine_shoulders), [here](https://cdda-guide.nornagon.net/item/ch_steel_staff)

### Expected behavior

Both/all items are consumed by the recipe

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/38476420/ece1af8e-75f2-4cd6-babf-fb1559718627)

### Versions and configuration

- OS: Windows
    - OS Version: _Windows 10_
- Game Version: 237374d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Procyonae** [comment]
/confirm Thanks for listing the ids ❤️

**Comment by Night-Pryanik** [comment]
Fixed by #67006 and #67009.
