### ISSUE TITLE
Typo Extinction

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#66977]
### Is your feature request related to a problem? Please describe.

You know the deal now, I find random typos and minor issues while translating, I write them and what I think would be a good fix into an issue, I let whoever wants to fix them make a PR or add it to one they already got cooking.

### Solution you would like.

The ones we have today are the following:

Minor typo on Godco Foodguard NPC dialogue:
- Nope, you can't do that.  I'd like to help you, bit we've already got enough mouths to feed. -> Nope, you can't do that.  I'd like to help you, but we've already got enough mouths to feed.

Not sure if a typo exactly, a quick search online revealed to me that English was was weird about capitalization after ellipsises (these -> ...) but this weed/meth smoking complaint looked weird to me:
- Oh, wow, that smell… can I have some? -> Oh, wow, that smell… Can I have some?

Cut eggplant doesn't seem to have a plural, I'm pretty sure this isn't intended since all other cut fruit/vegetables have a pluralized version:
- cut eggplant -> cut eggplants

Sorbet is weird, scoops are mentioned on its plural, but not its singular:
- sorbet -> sorbet scoop

Ditto for gelato:
- gelato -> gelato scoop

This NPC complaint about you blocking them needs a period at the end:

- Gotta get past you, [player name] -> Gotta get past you, [player name].

Spiked tail player/npc attack messages lack proper punctuation (an exclamation mark at the end):
- You sting [Target] with your tail -> You sting [Target] with your tail!
- [NPC] stings [Target] with their tail -> [NPC] stings [Target] with their tail!

Battles axes refer to low, medium and high carbon steel, while this terminology is what we use in code to refer to these grades, the overwhelming majority of graded steel items use mild as well as medium and high quality steel to refer to them, as such:
- low carbon steel battle axes -> mild steel battle axes
- medium carbon steel battle axes -> medium steel battle axes
- high carbon steel battle axes -> high steel battle axes
The references to low, medium and high carbon steel in their descriptions should also be changed to mild, medium and high.

Same for steelshod quarterstaves:
- low carbon steelshod quarterstaves -> mild steelshod quarterstaves
- medium carbon steelshod quarterstaves -> medium steelshod quarterstaves
- high carbon steelshod quarterstaves -> high steelshod quarterstaves

Same for maces:
- low carbon steel maces -> mild steel maces
- medium carbon steel maces -> medium steel maces
- high carbon steel maces -> high steel maces

Same for maces:
- low carbon steel maces -> mild steel maces
- medium carbon steel maces -> medium steel maces
- high carbon steel maces -> high steel maces

Same for survival knives:
- mild carbon steel survival knife -> mild steel survival knife
- medium carbon steel survival knife -> medium steel survival knife
- high carbon steel survival knife -> high steel survival knife

Same for trench knives:
- mild carbon steel trench knife -> mild steel trench knife
- medium carbon steel trench knife -> medium steel trench knife
- high carbon steel trench knife -> high steel trench knife

Same for kukris:
- mild carbon steel kukri -> mild steel kukri
- medium carbon steel kukri -> medium steel kukri
- high carbon steel kukri -> high steel kukri

There's a description of a video in the e-logs file that's about a gigantic marine creature attacking a ship and getting slapped with fighters, it's obviously too big of a string to reference entirely here, but here's the specific bit needing fixing:
- rose of hooked barbs digging into the steel plating -> rows of hooked barbs digging into the steel plating

### Describe alternatives you have considered.

- Not fixing typos
- Fixing typos myself
- Not enjoying making lists of random stuff

### Additional context

Typos!

**Comment by Procyonae** [comment]
On it
