### ISSUE TITLE
There is way to much fog in the "no Hope" mod!

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#66995]
### Describe the bug

The no hope mod does significantly increase the amount of fog on the map, over the entire year. That does significantly lower the efficiency of solar panels, which is one of the most important energy source in the no hope mod, because there is almost no fuel in the no hope mod. 

The following screenshoots show how the weather looks like without the no hope mod in spring
and with the no hope mod in spring.

### Attach save file

Without no hope mod, in spring.
![Ohne no hope mod](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/b574f35a-4c8c-4361-a9c8-9f5b6dbb388a)

With no hope mod, in spring.
![Mit no hope mod](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/e1598b5b-c3a9-4559-81a0-2375525212f5)

### Steps to reproduce

1. Make yourself a world with the no hope mod and without the no hope mod
2. Go to a radio tower on the highest spot with binoculars with the no hope mod enabled and without the no hope mod enabled
3. Look into the sky and see that with the no hope mod enabled you see mostly just fog, in spring and also over the entire year
4. and without the no hope mod you see significantly less fog, in spring and also over the entire year.

### Expected behavior

I do not know if that is intended or not. But that makes the mod needlessly more tedious, because of your solar panels working at ca. 30% efficiency almost the entire time. 
So i hope that the weather could please be normalized, like the weather is in the current Dark days ahead version.

### Versions and configuration

Windows 10
version: 624dc0f (tiles)
build: 2023-07-18-1357 (2 hours ago)
mods: No Hope, Dark days ahead

**Comment by Procyonae** [comment]
Looks like the No Hope uses a different base humidity of [90](https://github.com/CleverRaven/Cataclysm-DDA/blob/624dc0fff29201ae611ca61cbeddb45250a07add/data/mods/No_Hope/regional_map_settings.json#L1235) instead of [70](https://github.com/CleverRaven/Cataclysm-DDA/blob/624dc0fff29201ae611ca61cbeddb45250a07add/data/json/regional_map_settings.json#L1309) leading to more fog, idk whether it's intentional as to whether it needs fixing but it's a one number change if you want to make it locally

**Comment by Krieger1999** [comment]
> Looks like the No Hope uses a different base humidity of [90](https://github.com/CleverRaven/Cataclysm-DDA/blob/624dc0fff29201ae611ca61cbeddb45250a07add/data/mods/No_Hope/regional_map_settings.json#L1235) instead of [70](https://github.com/CleverRaven/Cataclysm-DDA/blob/624dc0fff29201ae611ca61cbeddb45250a07add/data/json/regional_map_settings.json#L1309) leading to more fog, idk whether it's intentional as to whether it needs fixing but it's a one number change if you want to make it locally

Thanks
