### ISSUE TITLE
strange repeated crashes 

### ISSUE THREAD

**Issue by hatamekyu** [CleverRaven/Cataclysm-DDA#67005]
### Describe the bug

crash keeps happening occasionally when i move..
Got no clue what causes it...
The sludge issue is also here too.

### Attach save file

[Stockington-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12089411/Stockington-trimmed.tar.gz)

### Steps to reproduce

walk around and kill stuff, it'll happen eventually

### Expected behavior

expected it to not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: d7f9f9e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    Standard combat test suite [standard_combat_test],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue],
    Extra Mutated Scenarios [extra_mut_scens],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

### Additional context

[crash and debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12089339/crash.and.debug.zip)

crash logs

**Comment by hatamekyu** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/138999792/3b3f6fd1-562a-4b34-9e9e-80a33814bdb6)
note: move here. It WILL crash

**Comment by Procyonae** [comment]
The save you've uploaded isn't what the form asks for, noone can test that one it's not got the world or associated files etc, edit your post and read what it says and I'll test it ^^

**Comment by hatamekyu** [comment]
Alright, sorry. I'll do that

**Comment by hatamekyu** [comment]
Is this it?

**Comment by Procyonae** [comment]
/confirm Didn't crash the first time I tried (walked all over the place and checked upstairs and down) but then I alt-F4d and tried again from scratch and almost immediately crashed on moving with this log in the console 
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by hatamekyu** [comment]
Weird. that one isn't showing up for me.

**Comment by hatamekyu** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/138999792/7fffd815-f4e2-433b-9ba8-342381b11ec1)
It may have to do with the smoke ..? 
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12089495/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12089496/crash.log)

**Comment by Procyonae** [comment]
Potentially related to #66963

**Comment by jjanisze** [comment]
Additional crashlog
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12089583/crash.log)

Symptoms experienced:
1) Initial flood of messages informing me I stepped into sludge when I haven't. These messages occur randomly every couple of turns, presumably as zombies walk into sludge themselves. Also applies to smoke and other effects. This presists for hundreds of turns. 
2) Flood of messages stops
3) Crash follows soon (dozens of turns) thereafter

**Comment by bombasticSlacks** [comment]
#67020 this actually fixes it
