### ISSUE TITLE
Dried bread (or something similar)

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67019]
### Is your feature request related to a problem? Please describe.

CDDA has all sorts of dried food,but not the bread,why not add it?

It has been around for a long time in human history,so i think it would be logical to implement it into the game.

It was usually made by leaving cut bread (slices) in a dry,hot place (I've made some of those myself at one point)

### Solution you would like.

Create something like "Sliced bread" crafting recipe which could use the mechanic of tanned skin ("activating" the slices and leaving them for some time) 

Usually they get fully dry in about 5 days (maximum) and last for about 3-6 months (it depends on storing conditions)

The dried bread that is kept in a dry place and clean space(counters, shelves,etc) last longer 

### Describe alternatives you have considered.

You might also just make those "slices" recipe and just make it possible to put them in the food dryers (coal, electronic ones for example)

The "slices" recipe itself will be like a slice of bread (for example - 1 loaf of bread turns into 12 slices) which together will be the exact amount of calories as the uncut counterpart,will be easier (faster) to eat,but will spoil faster.

### Additional context

I know that it might be hard to balance and implement,but i think it'll be worth it,and will make bread a more usable,long lasting source of food. (And if there's already such a thing, screw me,i guess)

**Comment by Profugo-Barbatus** [comment]
Already exists in the form of [Hardtack](https://cdda-guide.nornagon.net/item/hardtack) - Drying regular packaged breads doesn't really provide any preservative value that I'm aware of, just has cooking opportunities as you stale it. 

If there are recipes that make sense they can be added, but should probably have some justification. Most of what I'm seeing with a quick poke around indicates that outside of breadcrumbs which'll keep for a couple weeks, everything else you dry outta bread is a matter of days on the shelf, or 'use day of making'. Six months is gonna need a reasonable source as I find it hard to believe all of history put up with hardtack and other such efforts if it was as easy as "just leave the bread out".

**Comment by Krieger1999** [comment]
> Already exists in the form of [Hardtack](https://cdda-guide.nornagon.net/item/hardtack) - Drying regular packaged breads doesn't really provide any preservative value that I'm aware of, just has cooking opportunities as you stale it.
> 
> If there are recipes that make sense they can be added, but should probably have some justification. Most of what I'm seeing with a quick poke around indicates that outside of breadcrumbs which'll keep for a couple weeks, everything else you dry outta bread is a matter of days on the shelf, or 'use day of making'. Six months is gonna need a reasonable source as I find it hard to believe all of history put up with hardtack and other such efforts if it was as easy as "just leave the bread out".

It would be cool to be able to dry sourdough bread. Because it is by fare the most cost efficient (apart from killing cows) and rewneable food source in the game currently.

**Comment by Krieger1999** [comment]
> > Already exists in the form of [Hardtack](https://cdda-guide.nornagon.net/item/hardtack) - Drying regular packaged breads doesn't really provide any preservative value that I'm aware of, just has cooking opportunities as you stale it.
> > If there are recipes that make sense they can be added, but should probably have some justification. Most of what I'm seeing with a quick poke around indicates that outside of breadcrumbs which'll keep for a couple weeks, everything else you dry outta bread is a matter of days on the shelf, or 'use day of making'. Six months is gonna need a reasonable source as I find it hard to believe all of history put up with hardtack and other such efforts if it was as easy as "just leave the bread out".
> 
> It would be cool to be able to dry sourdough bread, which only lasts 1 week and can be easy mass prouced. Because it is by fare the most cost efficient (apart from killing cows) and rewneable food source in the game currently.

**Comment by Profugo-Barbatus** [comment]
Making bread better because "it would be cool" doesn't really fit with the design goals. From my surface scraping, drying sourdough slices out to crackers gives a life span of ~ a week. Sourdough already lasts 8 days. No real problem adding the recipe, especially if there's cracker-using recipes out there already. It just wouldn't have any unexpected preservation properties.

Hardtack is already easily mass produced - It has huge batch crafting time savings, only needs super available ingredients, and has easily learned skill and proficiency requirements.

**Comment by Krieger1999** [comment]
> drying

Hardtack is nothing in comparision to sourdough bread. Takes way to long to produce, costs way more  and also you can make way less. 

If its not possible to dry sourdough bread, then ok. You can still freeze food.

**Comment by Profugo-Barbatus** [comment]
Sorta looks like Sourdough is actually way out of line rather than hardtack being too weak - It uses ~450 cals of flour and ~50 cals of sourdough starter to produce ~1700 cals of bread (with no oil), and does that in 20m when sourdough baking (Disregarding rising the dough) is usually an hour long (~20m in a closed oven, then another ~40m with the oven open). Compared to regular bread, flatbread, wastebread, or brown bread, its way out of line for the raw mats going in.
