### ISSUE TITLE
Marijuana Dependance background

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#67016]
### Is your feature request related to a problem? Please describe.

We already have backgrounds for most other drug addictions/dependancies, so why not good ol' Mary Jane? It seems to be all the rage right now.

### Solution you would like.

Introduce a weed dependancy background.

**Comment by wolf51687** [comment]
Kevin's girl cheated on him with a weed user. Never gonna happen.

**Comment by JeveGreen** [comment]
> Kevin's girl cheated on him with a weed user. Never gonna happen.

Ah yes, because making a game worse for purely personal reasons is totally acceptable.
I don't wanna push on a man's weak spot, but ffs...

**Comment by Zireael07** [comment]
I don't see how not having a single background is "making a game worse".

**Comment by JeveGreen** [comment]
> I don't see how not having a single background is "making a game worse".

It's the principle behind it. "I don't like thing because personal reason, thus it won't be touched on." It's limiting something for a purely egotistical reason, and I don't like the idea that one of my favourite games could potentially be made limited, objectively worse, for such reasons. It goes beyond this single issue.

**Comment by Zireael07** [comment]
Ah. In this case, we agree.
