### ISSUE TITLE
Somewhat rare crashes

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67024]
### Describe the bug

Sometimes when traveling over long distances (doesn't matter if on foot or in the vehicle) without saving the game,it would crash.

It seems to be most frequent when player travels through unexplored forest.

### Attach save file

N/A

### Steps to reproduce

1) Travel over a long distance (preferably in unexplored forest) without saving the game.
2) the game would crash at some point 

### Expected behavior

The game shouldn't crash for no reason 

### Screenshots

N/A

### Versions and configuration

0.G (Gaiman) stable release of CDDA

### Additional context

Try equipping something that increases the area of view (binoculars for example)

#67023 looks like the problem is somewhat similar

**Comment by Procyonae** [comment]
Not providing a crash log, save or sensible reproducible steps make this not very useful and #67023 is an experimental issue and is very unlikely to be related if you're on stable like you've put

**Comment by Procyonae** [comment]
You look like you're playing with the MST_Extra mod and that's causing errors, have you got the latest 0.G update?https://github.com/chaosvolt/MST_Extra_Mod/releases

**Comment by GlordXd** [comment]
> You look like you're playing with the MST_Extra mod and that's causing errors, have you got the latest 0.G update?https://github.com/chaosvolt/MST_Extra_Mod/releases

I'll see about latest cdda update,and yes,i have the latest version of mst (close the issue if you see it as needed)

**Comment by GlordXd** [comment]
So,i got the latest version of stable,and problem doesn't seem to occur anymore,thanks for the tips
