### ISSUE TITLE
Rarely crash after movement

### ISSUE THREAD

**Issue by DPurple** [CleverRaven/Cataclysm-DDA#67023]
### Describe the bug

SIGSEGV: Segmentation fault
mostly happen while generating map

### Attach save file

N/A

### Steps to reproduce

It happen randomly, even after new save.
but not very offen

### Expected behavior

More stable, or may have a emergency save before crash?

### Versions and configuration

Experimental version which at git commit 55a749adc079527392bf11709c9293a61444bb4a
Download page show as "Cataclysm-DDA experimental build 2023-07-19-0508"
file is cdda-windows-tiles-sounds-x64-msvc-2023-07-19-0508.zip
Didn't using tilesets, audio is enabled

### Additional context

Here's crash.log & debug.log
and a mini coredump
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12095850/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12095851/debug.log)
[cataclysm-tiles.exe.5764.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12095854/cataclysm-tiles.exe.5764.zip)

**Comment by GlordXd** [comment]
I've had something similar: the game would crash for no reason if the player travels long enough in the unexplored areas (especially in forests) without saving the game, doesn't matter if the player is on foot or in the car.

**Comment by SurFlurer** [comment]
According to your crash.log ( although not very complete ), I think this is the same issue as #67011 .

**Comment by DPurple** [comment]
> According to your crash.log ( although not very complete ), I think this is the same issue as #67011 .

thx for replay,I have some similar crashes before (around 7-14 days, with experimental version from each day)
I can provide some more coredump, but i didn't remenber those version
[CrashDumps.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12096537/CrashDumps.zip)

**Comment by SurFlurer** [comment]
Now that that issue has been fixed, please play and test if this kind of rare crash still happens.

**Comment by SurFlurer** [comment]
Oh god, the crash recorded by crash.log seems to be the same issue with #67045 .

The reason for this crash is because processing items on the map assumes a null carrier. 

Related: #66292

**Comment by DPurple** [comment]
After 10hour play, it didn't crash anymore, I think this issues can be temporarily closed
