### ISSUE TITLE
Amphibian Additions

### ISSUE THREAD

**Issue by TheSaddestGoomba** [CleverRaven/Cataclysm-DDA#67029]
### Is your feature request related to a problem? Please describe.

Amphibians feel lacking as both monsters and natural wildlife. The natural varieties are lackluster compared to the diversity of birds and fish in game. Unlike those groups, amphibians have mutant monsters but those also feel under-developed.

### Solution you would like.

Add more specific natural species that function like wildlife and expand mutant varieties beyond size-growth.

### Describe alternatives you have considered.

Let the bugs rule the swamp.

Perhaps splitting the first phase into two. Starting with natural species and then handling frog/toad mutants as a second stage.

### Additional context

Here's what I've planned out so far.
Add in regional natural species that lay their own eggs, hatch into their unique larval forms and grow into adults.
Natural species will also rarely lay unusual eggs.
I'd aim to start with two natural species from each of these broad groupings: frogs, treefrogs, toads, and salamanders.
Additional natural species should be rather simple to implement thereafter.

Mixed in with the natural species are unusual ones (strange bullfrog, odd toad, etc.) that will grow into mutant and monstrous species.
These mutants will then "breed true", laying exclusively unusual eggs of their own at varying stages.
These mutants can zombify upon death and I plan to add a variety of new zombie forms for them.
Burned zombie versions are simplified down to three, assigned based mostly upon body size.

Frogs

- Bullfrogs will remain largely as-is, with their mutants occupying the ever-increasing-size niche.
- Giant Bullfrogs lay Giant Eggs which hatch into Giant Tadpoles. Most become Giant Frogs and continue the cycle. Others will grow into larger tadpoles as big as alligator gar. The oldest of these pack hunters may grow larger still.
- The new species will be Leopard Frogs and a mutant strain that develops electric eel like bioelectricity. Staticskins cause moderate shocks on contact, while Stuntongues can launch their tongue like a taser. Their shared zombie is the Shocker Frog.
- Both frog lines share a new zombie species for their smallest versions, the Frog Jockey. Frog Jocks can partly fuse with other zombphibians granting them rapid regeneration and possibly reduced cooldowns.

Toads
- Fowler's Toads and Eastern American Toads are the choice natural species.
- The existing size-growing toad line will be associated with the American Toad and will be given a 'mega' evolution. The Warted Monstrosity is comparable to the Colossal Croaker but the intent is to develop it into its own niche/combat style. 
- Fowler's Toad will have a mutant strain that grows larger to a point. More notably they gain a noxious stink cloud, a hard faceplate for burrowing, and finally a venomous beaked bite
- The two lines will have unique mega zeds but share Gastro Bufo and Bilious Bufo at earlier stages.
- I am considering a Toad Jockey zed as well to contrast the Frog Jockey by hopping onto the player and inflicting debuffs/conditions.

Treefrogs
- The Gray Treefrog's mutant offshoot will expand its color-changing camouflage and develop powerful poison. Zombie versions will become shady and excel at hunting players down.
- Spring Peepers are named for their distinct chirps. Their mutant cousins turn this into a deafening chorus. Their zombies weep tears of poison as they hit-and-run the player.
- Both share a final zedvolution, the Deathmist Frog produces a thick cloud of poison around itself that continues to emanate even from its corpse, adding a challenge to the usual corpse disposal.
- I have some thoughts for arboreal giant tadpoles and something called a Batrachian Strangler that may also come from this grouping.

Salamanders
- Hellbenders are the first salamander species. The second, and maybe third species are undecided pending some research.
- Hellbender mutants grow larger and more aggressive, gain powerful regeneration, and also produce immense amounts of slime. They live in and will attempt to drag players into hazardous waters.
- Hellbender zombies split into two 'megas', the River Hydra, with ludicrous regen & multiple bites (that can be reduced by severing heads), and the Skinnamander, a giant walking mass of twitching skinfolds that seek to envelope and suffocate the living.
- My sparse ideas for mutant salamanders include the Swollen and Distended variants that produce copious amounts of filthy slime that fouls water sources and generally makes a mess.
- Naturally there should be a fire-related version. Currently I'm thinking one that spews a flammable sludge before sparking it alight with grinding teeth or some other weird mouth mechanism.
- Mud Puppies seem a good inclusion, likely copying over and reskinning the mutant axolotls from TropiCataclysm.

Mummies
- The partially burned remains of great amphibians come back as something reminiscent of dried out frog carcasses stuck between window screens. Could perhaps be substituted for zeds in hot, arid conditions?
- These are also similar to the Scorched Zombies, even releasing an opaque cloud on death.
- Leaping Husk is the smallest of the three. It retains a frequent leap and can close on players quickly. It releases a small puff of sickening, opaque gas on death.
- Batrachian Mummy takes the middle slot and will fill for most salamanders and mid-sized mutant frogs. The leap is reduced to an intermittent skip and its death cloud is larger.
- Colossal Frog Mummy only comes from the frog 'megas'. It has lost its leap and moves ponderously but releases a house-filling amount of sickening gas on death.

PHASE 1 [#67259] - Implement Natural Species for Frogs, Toads, & Treefrogs
  - [X] JSON Entries
    - [X] MONSTERS
    - [X] EGGS
    - [X] EGG GROUPS
    - [X] SPAWNING GROUPS
  - [X] Testing
    - [X] Test Spawning
    - [X] Test Growth & Reproduction

PHASE 2 [#68197] - Monstrous Frogs & Toads			
  - [x] Shared JSON Details		
    - [x] WEAKPOINTS	
    - [x] HARVEST	
    - [x] SPAWNING GROUPS	
  - [x] Audit Existing JSON		
    - [x] Audit Giant Bullfrogs	
    - [x] Audit Giant Toads	
  - [x] JSON New Frog & Toad Mutants		
    - [x] MONSTERS	
      - [x] Giant Tadpoles
      - [x] Electric Frogs
      - [x] Mega Toad
      - [x] Stinky Toads
    - [x] SPAWNING GROUPS	
  - [x] Testing		
    - [x] Test Spawning	
    - [x] Test Growth & Reproduction	
    - [x] Effects Test	
    - [x] Combat Test	

PHASE 3 [#70219] - Treefrog Monsters & Bonuses			
  - [x] JSON New Treefrog Mutants		
    - [x] MONSTERS	
      - [x] Jumbo Treefrog
      - [x] Wailing Frog
      - [x] Mimic Frog
    - [x] GROUPS
      - [x] Monster
      - [x] Upgrade
      - [x] Spawning
    - [x] Add PARROT Calls/Croaks
  - [x] Testing		
    - [x] Test Spawning	
    - [x] Test Growth & Reproduction	
    - [x] Test Croaks	
    - [x] Test Flags
    - [x] Combat Test	

STRAY EXTRAS
  - [ ] Update Foul line with slippery grease, enabled by #69555
  - [ ] Add dissection snippets to mutants
  - [ ] Add to lab animal spawns
  - [ ] Add giant eggs to recipes
  - [ ] Add more calls/croaks
  - [ ] Add eating flags/mechanics
  - [ ] Complicate factions for in-fighting/cannibalism
  - [ ] Recalculate volumes, weights, and densities
  - [ ] Test and adjust monster difficulties
  - [ ] Add "Herp Food" item for Tamable Wildlife	
  - [ ] Create nest spawns for burrowing/mud-bathing toads and others
  - [ ] Add neotenic lines: tadfish from Tropicata, buoy-like float toads, unnamed porpoise/leopard seal-like pack hunters
  - [ ] Add 'slither' line, tree dwelling giant tadpoles and their mature forms, batrachian strangler/arboreal frogpole

PHASE 4 - Undead Amphibians			
  - [ ] JSON New Frog & Toad Zombies		
    - [ ] MONSTERS	
      - [ ] Jockeys
      - [ ] Shocker Frog
      - [ ] Z-Toads
      - [ ] Zombie Neotads
      - [ ] Zombtreefrogs
      - [ ] Burned Batrachian Zombies
    - [ ] SPAWNING GROUPS	
  - [ ] Audit Existing JSON		
    - [ ] Audit Zombullfrog, Mom & Dad	
    - [ ] Audit Gastro Bufo	
  - [ ] Testing		
    - [ ] Test Spawning	
    - [ ] Test Resurrection & Evolution	
    - [ ] Effects Test	
    - [ ] Combat Test	

PHASE 5 - Salamanders, Both Natural & Monstrous			
  - [ ] JSON Entries		
    - [ ] Natural Salamanders, Efts, & Eggs	
    - [ ] Mutant Salamanders	
    - [ ] Zombie Salamanders	
  - [ ] Testing
    - [ ] Test Spawning
    - [ ] Test Reproduction & Growth/Evolution
    - [ ] Effects Test
    - [ ] Combat Test

**Comment by GlordXd** [comment]
I hope this gets some attention,its definitely interesting and seemingly well written.

**Comment by TheSaddestGoomba** [comment]
> I hope this gets some attention,its definitely interesting and seemingly well written.

Thanks, I hope to be able to do much of it myself.

**Comment by fairyarmadillo** [comment]
Mutants should probably not be shooting electricity, as mutant stuff is supposed to be biologically themed and at least halfway believable. If it's a zombie or a nether creature that's another story, so just a mild reskin should do it.

The other ones all seem excellent.

**Comment by TheSaddestGoomba** [comment]
> Mutants should probably not be shooting electricity, as mutant stuff is supposed to be biologically themed and at least halfway believable. If it's a zombie or a nether creature that's another story, so just a mild reskin should do it.
> 
> The other ones all seem excellent. Why no grabby tongues though? Monsters can cast spells now so you could just copy the batrachian mutant spell and have them yoink dragonflies from a few tiles out.

Agreed, I only plan for the zombie version (Shocker Frog) to be able to project electricity outward. The Staticskin and Stuntongue would be more like an electric eel. Probably won't even do electric damage mechanically but cause stun and high pain.

Hmm, there could certainly be more grabby tongues. It would be especially nasty on the Stuntongue, bringing you in close for more shocks. I guess I was mostly thinking of the ones large enough to snag the player but seeing them pluck Giant Dragonflies out of the air would be excellent.
