### ISSUE TITLE
army gear should be nylon only and not cotton+nylon or have GOOD breathability

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#67030]
### Is your feature request related to a problem? Please describe.

IRL, we use blends of cotton and nylon for certain clothing for specific reasons but in game, such garments are treated as being two independent layers of cotton and nylon rather than a fiber blend. This makes the breathability of those armors arbitrarily worse for no good reason as cotton has equal or inferior defense to nylon and is is only AVERAGE while nylon is GOOD.
This affects the combat blouse, combat shirt, army jacket and army pants.

### Solution you would like.

The reason these clothing pieces are worse is a bit gamey due to the way material layers are interpreted, but personally I'd just make them mono nylon and get rid of the cotton altogether.

### Describe alternatives you have considered.

Make breathability hard-set to GOOD for such armors.

**Comment by fairyarmadillo** [comment]
IMO we need a nylon+cotton blend material that has half the acid protection and breathability of either parent material, and this should broadly be applied to most of the workwear and uniforms in the game.
