### ISSUE TITLE
Heavy Punching Bag Sack is NOT used for construction Heavy Punching Bag

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#67036]
### Describe the bug

When you deconstruct heavy punching bags you find, you can get this thing called heavy punching bag sack.
So I checked the construction recipe out of curiosity... and it does NOT use the sack. Instead it uses... PLASTIC BAGS!?

### Attach save file

[Nightmare-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12101867/Nightmare-trimmed.tar.gz)

### Steps to reproduce

1. Find or spawn a heavy punching bag.
2. Deconstruct it, you'll get a heavy punching bag sack.
3. Now try to construct heavy punching bag. You'll find it does NOT use the sack.

### Expected behavior

Maybe something expected to get punched and kicked should not be held together by potato chips plastic bags.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: d7f9f9e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Termineitor244** [comment]
/confirmed.

**Comment by alp7292** [comment]
if we are goung to fix recipe we should alse have a way to craft heavy punching bag sack (if there isnt)

**Comment by CatchScratch** [comment]
@NetSysFire Thank you for updating issues with the "Good First Issue" label. I'm trying to learn how to contribute and the label helps a lot.
