### ISSUE TITLE
Error regarding smoke effect on loading save 

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#67037]
### Describe the bug

Receiving the following error on loading the save with any build after 2023-07-17-2538:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56372745/24f53935-5c24-4d25-a431-9fed653b784e)

I receive the following error if I continue, save, and reload:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56372745/0b1cddb5-af3b-430c-aeb0-8d420626154a)

Probably related to #66660 (like @Kamayana's [comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/66660#issuecomment-1641223692) suggests).
I'd ignore it if the second error wasn't persistent after reloads.

### Attach save file

[Dark Days Ahead-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12101920/Dark.Days.Ahead-trimmed.tar.gz)

*Please ignore Player_Mod, just a blank mod for when I want to test modding.

### Steps to reproduce

1. Update to latest build.
2. Load save.

### Expected behavior

No error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: a2fd9a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Player Mod [Player_Mod]
]

**Comment by teapot156** [comment]
Also getting this. Received a message that log was actually filing up from this.

**Comment by new02DAY** [comment]
Closing since it's an old save/experimental build issue, so new games shouldn't run into any trouble. For reference for anyone else: I managed to solve it by replacing the old smoke effect id in my save with smoke_lungs (using Notepad++).
