### ISSUE TITLE
Zero-duration exercise leads to infinite loop

### ISSUE THREAD

**Issue by Dandy1096** [CleverRaven/Cataclysm-DDA#67052]
### Describe the bug

I attempted to use an exercise machine. I must have accidentally not input a duration for the exercise- maybe I clicked through the menu too rapidly- according to the save file my exercise attempt ended on the same turn that it began. I don't recall what intensity I chose.

`{ "turn": 5239052, "message": "You start your workout session.", "count": 1, "type": 5 },`
`{ "turn": 5239052, "message": "You finish your workout session.", "count": 1, "type": 5 },`

I am trapped in an infinite loop, where the game advances time rapidly but the controls are locked. I can't open menus or manually cancel the workout in any way.
Of course, before I could react the game autosaved, which means loading the save locks me into the infinite workout.
The game advances for several hours until a zombie dog finally finds and kills me, about seven or eight hours after I began my infinite workout routine.

### Attach save file

[Centertown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12111439/Centertown.zip)
Creating a minimized save archive is impossible. I cannot enter the `ESC` menu ingame, because the game locks my controls completely. It's a relatively new world, first day, so it's not a very large file, but I apologize for the inconvenience.

### Steps to reproduce

1. Use an exercise machine.
2. Do not input a duration.
3. Infinite loop.

### Expected behavior

I expected that there would be some check to see if the workout had already ended, or that there would be some way to cancel it.

### Versions and configuration

Experimental build 2023-07-20-0251, Windows x64-tiles-sounds version. No mods or other noteworthy configurations.

**Comment by RenechCDDA** [comment]
Very funny, but I'm not sure how you have managed this. It won't accept a blank value.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/3e862e29-8dba-4bfa-8387-ff5702656682)

Investigation is continuing....

**Comment by RenechCDDA** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/f31c06f4-92b8-47cc-bc53-373ab7e46a90)

Okay, so. Actually *very* funny. Somehow the game thinks your character has -7,683,606 moves or so, or in other words the game thinks you need to spend moves equivalent to about 21.333 hours of exercise.

I'm still not sure how it's done this!

**Comment by RenechCDDA** [comment]
I gotta say this is a fun one, *and I still don't know what's going*. But I was able to reproduce this exact occurrence ingame, unfortunately I couldn't reproduce it a second time when I had recording software going.

I *am* able to reproduce a very similar bug by inputting a negative value (e.g. `-1`) for exercising time... but only when *choosing to continue* and only if you do it... four times in a row.

**Comment by RenechCDDA** [comment]
15:29:52.159 ERROR : \Cataclysm-DDA\src\player_activity.cpp:264 [do_turn] you moves is 6100 moves_left is -6000
15:29:54.910 ERROR : \Cataclysm-DDA\src\player_activity.cpp:264 [do_turn] you moves is 372100 moves_left is -6000
15:29:56.808 ERROR : \Cataclysm-DDA\src\player_activity.cpp:264 [do_turn] you moves is -20251572 moves_left is -6000

So our moves are being exponentially increased here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/1ba9bc838ddaba2fe3941e3c9d4337da24d996c2/src/player_activity.cpp#L263

moves_left is negative, subtracting a negative is just addition.... we end up multiplying our moves by input(in minutes)^2 every time we continue the activity. Hence why this is stupidly hard to reproduce - your input has to overflow to a negative number in x^3 (but only about half of all such numbers will do so)

But how did moves_left become negative?

**Comment by Dandy1096** [comment]
> But how did moves_left become negative?

I recall just pressing enter through the dialog box that popped up without taking the time to read it. Is it possible the game initializes moves_left with a value of -1, or skipping the dialog box somehow returns a value of -1?

**Comment by RenechCDDA** [comment]
There might be some weird combinations of entries where it's possible, I think it's even theoretically possible if you overflow the initial input (rather than use a negative). But this is almost certainly what happened, even if the specific inputs (of -1 -1 -1) didn't happen.

Because of the fact the moves are being calculated all over the place, it's hard to say exactly what number made it in. Many entries are possible.
