### ISSUE TITLE
Teleporting assassins

### ISSUE THREAD

**Issue by Dimasw99** [CleverRaven/Cataclysm-DDA#67057]
### Describe the bug

The spawning mechanic for assassins currently allows them to not only spawn right next to you but also inside your moving car.
I have observed assassins spawn in next to me in both auto walk and normal. With auto walk even having them spawn inside a car.

### Attach save file

[Singe_copy_copy_copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12113469/Singe_copy_copy_copy-trimmed.tar.gz)

### Steps to reproduce

1. Kill some thugs that spawn in from either the "wooden fort" or a "Survivor Encampment"
2. Spend a lot of time crafting, mutating, reading or simply just passing time.
3. Get ambushed randomly by either backtracking or staying too long at one spot.

### Expected behavior

Assassins should approach the player either from a distance or lay an ambush inside a house without them spawning in too late when the player is close. Likewise there should a limit of how many assassins are currently around as not to create a horde of them on accident.

### Screenshots

![grafik](https://github.com/CleverRaven/Cataclysm-DDA/assets/21098781/cdffb4d0-aefe-4bad-94fd-0438f599073a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3086 (21H2)
- Game Version: 408af4a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_cyan>Remove Vehicle Degradation</color> [remove_vehicle_degradation],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    <color_light_green>Cataclysm++</color> [Cata++],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Useful Helicopters Experimental [useful_helicopters],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Dimasw99** [comment]
In an unrelated note. The assassin in the far back of my VR is using a "Ruger Precision Rifle" using .300 which he can burst fire in a 5 shot burst. A bolt action rifle that does 72 dmg per hit

**Comment by fairyarmadillo** [comment]
How do they even know where the player is? How do they have endless guys and gear to throw at them? How do they know the player killed their people if none of them survived and there were no witnesses?

**Comment by Dimasw99** [comment]
> How do they even know where the player is? How do they have endless guys and gear to throw at them? How do they know the player killed their people if none of them survived and there were no witnesses?

I have killed over 30 assassins already compared to the 8 thugs that started it all.

**Comment by fairyarmadillo** [comment]
The Hell's Raiders assassins at the very least should be disabled. Bandits are always hostile, the player will always be forced to kill them. The meta is now to just never interact with them because they pull a nothing personnel kid on you, none of which seems desirable.
