### ISSUE TITLE
Flaregun sometimes forgot to return camera back to avatar

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#67053]
### Describe the bug

Sometimes, when you shoot a flaregun, it doesn't reposition the camera back. If camera stay at the same z-level, its just minor inconsistency, just press `:` and it's gone, but if you aim on different z-levels, the camera can't reposition you back, and you stuck, seeing only z-level above instead of z-level you are on

I actually met this bug long before, got it while using sling, but was not able to recreate before

### Attach save file

[debug_copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12112171/debug_copy-trimmed.tar.gz)

### Steps to reproduce

1. Teleport yourself on a roof
2. Spawn few debug monsters above
3. Spawn flare gun and bunch of signal flare
4. Start to shoot
5. Eventually your camera will stuck

### Expected behavior

Camera is repositioned always
`:` reposition camera across z-levels

### Screenshots

bug, recreated on the same z-level
![GIF 19-07-2023 23-39-06](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/2f6077d4-7178-49f1-bb5b-a2b15df1a867)

bug, recreated on different z-level
![GIF 19-07-2023 23-45-34](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/c9ba06bb-521a-4b29-bc54-22cb34745394)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: c347c8a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

**Comment by RenechCDDA** [comment]
Well, I believe you but I ended up shooting 180 flares before giving up. I wasn't able to reproduce it even with your settings.

**Comment by GuardianDll** [comment]
huh, neither do i (at e4cce13)
was there some changes, that could fix it then?
