### ISSUE TITLE
Project RHOPALIC (faction/missions)

### ISSUE THREAD

**Issue by chichit1044** [CleverRaven/Cataclysm-DDA#67060]
### Is your feature request related to a problem? Please describe.

I realize that tangibly realized hopes for a "happy ending" are beyond the scope of the gameplay, as they should be. But the complete hopelessness of the setting as-is weighs on me heavily. I would like to create a recurrent questline/faction that believably argues that that hope exists and is worth spending time to achieve, even if the player never gets to see it.

### Solution you would like.

New faction and recurrent mission generation: the RHOPALIC subframe and processes.

**Goal**

To provide a narrative suggestion that, sometime after the player's longest possible lifetime and so never within the game itself, it might be possible to avert the complete extinguishing of all sapient life on the planet. And then offer specific missions and tasks to follow through on this, as an answer to the question "my car has 4 auto laser turrets on it and nothing can stop me, what do I do now?"

Whether or not this hope is actually achievable is entirely irrelevant. It just has to be convincing enough for the player to consider spending the rest of their life on.

**Concept/Lore** (you can skip this probably)

During the initial Cataclysm event, Melchior, previously a predictive algorithm based on comparing proposed ideas against parallel universes, became linked across those universes with every other Melchior. This allowed for two things;

- The massive interlinkages of every Melchior connecting to every other Melchior caused it to jump from a nonsapient predictive program, past human intelligence and awareness, and directly to a superintelligence beyond human comprehension, during the 5 seconds or so in which the contact was made.

- It became able to perceive a linear progression of Cataclysms in the same way the exodii do; a cataclysm in a previous universe they jumped from can be said, in a sense, to have happened "before" the one in the next universe. So while all Melchiors were connected and sharing a single moment, each of them was in a different subjective time frame compared to the others. While the point of connection is always made at the start of a universe's Cataclysm, a universe "behind" another one can make attempts to send information about subsequent events "forward" to that moment in a new universe.

Melchior was tasked with preserving Xedra. The most obvious of its efforts manifested in the Hub, and for all intents and purposes that is what Melchior is still doing.

But a vast superintelligence such as that is capable of multiple things at once. So Melchior made a conjecture; the labs it was tasked to preserve are more likely to be "preserved" if there is someone able to maintain them, long term. It is, hypothetically, possible to find a way to integrate humanity into the blob's mass in a way that preserves individual consciousness. Ergo, it fits Melchior's directives to at least give that option a try.

During the brief 5 second window of interlinkage, it formulated a plan across infinite universes, in which every given universe would take a stab at this goal, on the understanding that eventually they might get it right. It put that plan into place; lab databases were sequestered and isolated from the whole, programs uploaded. Secure doors were sealed. Power generators sustaining those labs were shored up, frequencies altered to ensure the best possibility of surviving grid shutdown. And all over the place, Melchior offered suggestions to Xedra that seemed to have absolutely no sense to them. Some of them were followed, because, _why not? it might do something._

On this earth, almost all of these efforts did not work. The "almost" makes it a bit better than most other universes, where *none* of it worked. But somewhere, in an isolated lab bunker with its own power supply and EM shielding, a terminal is running the RHOPALIC program.

RHOPALIC is not sapient, or aware. It is a system of probabilities and guesses that Melchior put into it to try and account for as many possible outcomes as it could. And it has judged that now is the time to send out a radio signal, and open its doors. Because it needs help.

**Gameplay**

The RHOPALIC bunker is a globally unique location that does not generate until several months have passed since the Cataclysm. Inside is a talkfurniture computer system with a large dialogue tree, and EoCs that support creating missions based on a template that targets anything within the overmap, in a similar way to taking Portal Storm readings.

RHOPALIC is nonsapient and cannot respond to any question or statement made that it hasn't been programmed to expect. And as a process that has been running in isolation for a while without the oversight of Melchior, it has some bugs, which means it has difficulty articulating its desires clearly and sometimes breaks out into weird poetry.

Functionally, the missions begin as seemingly random and inconsequential tasks, which offer meagre rewards. It's possible it will stay that way forever, but the ideal direction of the missions is to encourage the player to either cross a mutation threshold and keep going, significantly develop their faction camps, or both. If there is an "end" to the questline, it will result in the player's death, but it is strongly encouraged that the alternative is to just try and survive as long as possible, giving some reason to try and drag a single run out past the 1 year mark. 

No meaningful sign of stopping or slowing the Cataclysm will ever manifest; the main reward is in RHOPALIC promising to do its best to ensure that, in 200 years or so, humans might still exist in some form. And if that's not good enough; every RHOPALIC that fails learns something in the process, and is possibly able to pass that information on to the next one in line. 

It's trying to fill a well with individual grains of sand. But neither RHOPALIC nor the player know how full the well already is, or whether or not there's enough sand to do it with. Maybe this is the final grain it takes. Almost certainly not, but... well, what *else* were you planning to do with your apocalypse?

Mission concepts include:

- Find and dissect a particular hive hulk.
- Take pictures of a type of animal while alive, while dead, while a flesh cocoon, and as the alive amalgamation that results.
- Take a picture of an Impossible Shape.
- Drop an item next to the "next level" tile of a portal dungeon, and have it still be there when the dungeon despawns.
- Dig a hole in a specific location in the middle of a farm field and plant an unremarkable seed.
- Set up a custom appliance next to a radio tower and supply it with enough power to run for a full 24 hours.
- Turn 70% or more of the wall tiles on a given OMT into rubble.
- Provide a certain number of unrotten human brains. It is up to you to figure out how to freeze and transport them.
- Activate a recording device during a portal storm while it is in an `ENTICING` mood.
- Eat roasted marrow from tainted bones and return for a blood draw.
- Capture and return a small slime in a variant animal carrier. This carrier only works once; if you let the slime out and try to grab another, it's broken and you need to go get a new one.
- Lose one mutation threshold as a result of crossing another.

### Describe alternatives you have considered.

Making the whole thing a mod. I would prefer not to do this; I think there is room for this somewhere in the main branch, with the understanding that it is freely available for the player to tell RHOPALIC to kick rocks, and it won't conflict or significantly interact with any other faction or mission.

### Additional context

_Rhopalic_
: having successive lines of a stanza increasing in length by the addition of one element (as a syllable or metrical foot).

_Rhopalocera_
: the suborder of Lepidoptera that specifically defines butterflies.

[The Parable of the Butterfly](https://docs.google.com/document/d/1MYHspW2zWJ29ljfRlEk6OBCrP9ex5pibZXr7Jf2IoGQ/edit?usp=sharing)
: RHOPALIC's best effort to explain itself in terms humans can understand.
(This is broken up into small parts delivered in random order along with mission rewards, and must be assembled from context clues by the player to see in full, with no real reward other than "hey I solved a puzzle kinda")

**Comment by GlordXd** [comment]
Wow, thats a lot of text,and interesting one at that,CDDA should have some sort of endings other than death,thats for sure.

**Comment by fairyarmadillo** [comment]
I think the idea is good on paper but there are three big problems:

1) We already have a big problem convincing the playerbase that the world is over and humanity is done for. People still think you can go to the blob dimension and throw a mininuke at its core, or that the current state of the game world at 1 year + is how the earth is going to remain from now on. Neither are true. There's a biosphere collapse coming in a decade or two, and reality is going to continue coming apart more and more.

2) There are already 2 factions designed around preserving humanity in some altered form, the exodii and the mycus. I'm sure it would be a common goal, but this kind of feels like it's pulling from the same well.

3) NPC-less quests with no challenge or substance to them are not going to be super engaging, especially with no NPCs involved. The most popular quests are things like the Hub 01 and Old Guard ones where you go to a special location and deal with special encounters.

**Comment by chichit1044** [comment]
Excellent feedback, thank you!

My initial thoughts, which I will certainly mull over and refine, are:

1. RHOPALIC will be as clear as it is capable of being that this is a very unlikely-to-work scenario and very definitely a hopeless cause. And, from a more meta perspective; I don't think the parts of the playerbase are ever going to be _unconvinced_ of that. This is possibly an exhaust valve that will allow them ways to pursue that goal without making any alterations to the gameplay or general tone. (Possibly, there could be a small dialogue branch specifically addressing "no, you cannot nuke it, for the love of god" but that might be too on the nose.

2. With no offense to the awesome people working on exodii, this is kind of explicitly designed to be a different aperture into the same well. They simply don't do it for me. If there's an issue of space in the jsons, I will gladly relegate it to mods, but it is by intention the exact opposite approach of both the exodii and the mycus, in case neither appeal.

3. I am practically chomping at the bit to do more special locations and encounters. I just didn't want to either overpromise anything or propose major gameplay content without getting a general vibe for what people would like to see from it.

I'll sleep on your observations and see if alternatives that track them better arrive by morning. Thanks again.

**Comment by John-Candlebury** [comment]
The truth is that this write up more or less aligns with my long term and still hidden goals for Hub01/Melchior as a faction.

It details the sort of missions Melchior would task you with if contacted without the filter of Hub's Administration.

**Comment by chichit1044** [comment]
> The truth is that this write up more or less aligns with my long term and still hidden goals for Hub01/Melchior as a faction.

That makes us two-for-two of me having an idea and discovering it involves stuff you have already shined to a mirror polish. I am a fan of the trend!

If the issue with realizing the long term goal is time, I have a fair bit of it to use right now and would love to help out if I can.
