### ISSUE TITLE
"Unload nearby containers" on a dropped active mp3-player cause SEGFAULT.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67066]
### Describe the bug

"Unload all" on a dropped active mp3 player cause segfault.

### Attach save file

N/A

### Steps to reproduce

1. Make player with mp3 player (and light battery).
2. Turn on mp3-player and drop it on the ground.
3. Make a Personal-zone with "onload all" near the player from the zone menu.
4. Select "unload all nearby containers" from the sort zone menu.
5. SEGFAULT crash.

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.6085 (1607)
- Game Version: 2c4c7ee [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Kamayana** [comment]
Confirmed. The culprit is that `mp3_on()` is getting called with `t == false` and `*p == nullptr`:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/6fd35209-63c4-424f-9ca3-4fb64d8e2d96)
