### ISSUE TITLE
Weird bug when crafting stone hammer

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67067]
### Describe the bug

Today I've tried to craft a stone hammer, everything was going ok,and then game asked me if i want to use water for crafting it,i pressed yes,and about half a second later i got back to the same "choice" menu,it kept repeating,until i pressed no (one could say its a loop)

### Attach save file

[Пробный мир-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12122880/-trimmed.tar.gz)
 (Ignore the russian name)

### Steps to reproduce

1) get needed components to craft a stone hammer
2) the resource of water for it must be on the ground and in a container
3) the game would ask a permission to use said water
4) press yes
5) about 0.5 seconds after player will get the same pop-up choice,and it will keep repeating until player presses "no"

### Expected behavior

I didn't expected a "loop" when crafting stone hammer 

### Screenshots

![Screenshot_20230721_135514](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/bf74db21-390e-4760-bd1e-af6f20b4f527)

Notice how is there 12 units of water used in crafting (which is FAR more than it needs)

### Versions and configuration

0.G (Gaiman) stable release of CDDA

![Screenshot_20230711_212156](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/283bfaa3-e1f4-4d0b-94ff-403225aed389)

### Additional context

I'll give additional info if needed

**Comment by RenechCDDA** [comment]
It sounds like something I resolved in #64706, but I'm unable to load the save to check (neither github nor windows seems to like your filename). (This was merged post-0.G so it makes sense you could still be experiencing it in 0.G)

Can you re-save with latin characters only and re-upload?

**Comment by GlordXd** [comment]
> It sounds like something I resolved in #64706, but I'm unable to load the save to check (neither github nor windows seems to like your filename). (This was merged post-0.G so it makes sense you could still be experiencing it in 0.G)
> 
> Can you re-save with latin characters only and re-upload?

I'll try to replicate it in another world with correct name

**Comment by RenechCDDA** [comment]
(nevermind to the above, just swapped to 7-zip and got it open)

The clean water is in the clay canning pot, which definitely had this problem in 0.G. See #61866

This is resolved in experimental, so I am closing the issue.

**Comment by RenechCDDA** [comment]
Oh, and if you'd like to work around this while remaining on 0.G there's basically two ways:

1) Don't store crafting components in clay canning pots.

OR

2) Change the clay canning pot from `TOOL` to `GENERIC` in data/json/items/generic/dining_kitchen.json

**Comment by GlordXd** [comment]
Thanks,i might consider going into experimental builds,so i can get better game experience (and be more effective with buh reports)
