### ISSUE TITLE
Game crash in the settings 

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67071]
### Describe the bug

There is a error in the settings under some conditions,more context below.

### Attach save file

No save file,but i have a debug thingy.

 DEBUG    : invalid ItemType

 FUNCTION : auto options_manager::show(bool, const bool, bool)::(anonymous class)::operator()(const ui_adaptor &)::(anonymous class)::operator()(const options_manager::PageItem &, bool) const
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/options.cpp
 LINE     : 3504
 VERSION

### Steps to reproduce

1) go to settings,press this specific option 
![Screenshot_20230721_174328](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/5e4f7ee4-d087-4c1d-a4a5-f8d4a5a22a94)
2) it will open up additional options,scroll through them down,then up to the "main" option that opens additional ones
3) try to close it
4) error

### Expected behavior

Settings are the last thing i expected to give an error.

### Screenshots

Screenshot is above 

### Versions and configuration

Experimental release of CDDA (version - 6dc51c7)
Language - English 

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12129905/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12129906/debug.log)
I'll provide more information if needed.

Edit: please,check the other options in that section in this way,i suspect that they might do the exact same error.

Edit 2: every single option in the red square causes the exact same error as above.(There are not just errors,those are abnormal termination errors)

![Screenshot_20230721_181435.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/d2d564d5-4432-4d93-92da-a167da35ea38)

Edit 3: it occurs in more recent builds as well, 82773c3 for example

**Comment by WhiteCloud0123** [comment]
A simple solution is to modify the first 'Android Shortcut Options' to a different name. After local testing, there will be no further crashes.
