### ISSUE TITLE
Limited music on MP3 players.

### ISSUE THREAD

**Issue by S0ZDATEL** [CleverRaven/Cataclysm-DDA#67078]
### Is your feature request related to a problem? Please describe.

It's inconsistent that laptops have a limited amount of songs that you need to load from SD cards, but an MP3 player magically have new songs all the time.

### Solution you would like.

Give the MP3 player similar mechanics to a laptop with a limited amount of songs and an ability to load new ones from SD cards.

### Describe alternatives you have considered.

Leaving everything as it is is fine, but it just feels inconsistent.

### Additional context

Maybe the same could be applied for other methods of listening to music, like stereo systems...

**Comment by TheEskir** [comment]
I'd prefer if:
- Songs are only copyable from laptops/e-inks
- mp3 players took sd-cards with music on them as an insertable

I'm not aware of any 'traditional' mp3 players that can accept sd-cards but also have internal storage and/or ways to copy between the two.
