### ISSUE TITLE
515.1608 crashing to desktop

### ISSUE THREAD

**Issue by kilozombie** [CleverRaven/Cataclysm-DDA#67081]
### Describe the bug

Having recently updated BYOND to specifically version 515.1608, the version the server's apparently running, I crashed three times early on in a shift playing Warden on Snaxi. Instant CTD, no lock-up. All three crashes were in the brig when doing brig-related things like running around and being near players.

### Attach save file

N/A

### Steps to reproduce

Run BYOND 515.1608 on Windows 10 and play the game. And get unlucky.

### Expected behavior

I was playing on some 514 build before which basically never crashed, although I was having issues with roundstart freezing up my client.

### Versions and configuration

N/A

**Comment by RenechCDDA** [comment]
This is the github for CDDA, it sounds like you're looking for SS13. I don't know which repository that is, but it isn't this one.

**Comment by kilozombie** [comment]
AAAAAAA I'M SO SORRY
