### ISSUE TITLE
Skid Lid is Uncomfortable

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#67099]
### Describe the bug

Skid lid is uncomfortable to wear.

### Attach save file

N/A

### Steps to reproduce

1. Wear a skid lid
2. Uncomfortable feeling.

### Expected behavior

Comfortable to wear.

### Screenshots

![Screenshot_20230723-014553_1](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/5ca74130-9c8b-4630-b737-cdbad338aa68)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: cfdb9d3 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks]
]

**Comment by GlordXd** [comment]
For the note,i was able to reproduce it.

![Screenshot_20230722_222623.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/f1dee2a0-6c1b-4f3e-b74a-9c96a6c95599)



- OS: Android
    - OS Version: Manufacturer: ZTE; Model: ZTE Blade A5 2019; Release: 9; Incremental: 20191012.104430; 
- Game Version: 6dc51c7 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue]
]
