### ISSUE TITLE
Bringing the old look of settings in some way

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67092]
### Is your feature request related to a problem? Please describe.

I've got into experimental builds recently,and the look of new settings (compared to the stable release) looks very alien to me,so why not make an option that brings back the old look of the settings?

### Solution you would like.

Create an optional setting that makes the option menu look like the old one (the one from 0.G)

### Describe alternatives you have considered.

Its not really a big deal,but it would be a nice thing,and i believe its not that hard to make.

### Additional context

No context really,just a QOL suggestion (and if there's something like this already,feel free to point it out)

**Comment by Zireael07** [comment]
Care to post some screenshots for comparison?

**Comment by GlordXd** [comment]
Sure thing 

![Screenshot_20230722_144911.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/ff775faa-6cbe-42b4-8e90-8c539f2f8f06)

^This is the old one (i think its more intuitive and easier for the brain to remember and recognise)

![Screenshot_20230722_144949.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/abc803f4-d4c5-4cd2-ac1d-c9e9368d4616)

And thats the old one (its looks nice and organised,but less intuitive,and i think more clicks are required to navigate though it, compared to the old one)

**Comment by Night-Pryanik** [comment]
> i believe its not that hard to make

Essentially it's duplicating the current amount of lines in the code, and we're talking about hundreds, if not thousands, of lines.

**Comment by Procyonae** [comment]
An expand all button as a compromise maybe?

**Comment by GlordXd** [comment]
> An expand all button as a compromise maybe?

Interesting,a good alternative I'd say,my main idea was to able to see all options, without constantly opening (and then closing) them.

The secondary idea (goal?) was to reduce the amount of clicks needed to navigate the options,just as i said above.

And making the "expand all" button seems much easier than my idea about making that optional setting,again,very nice idea.

**Comment by alp7292** [comment]
new one is just organized you can just expand all
