### ISSUE TITLE
Obscure EOC tele examine action cache bug

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67114]
### Describe the bug

While testing for edge cases in how #66917 works, I discovered that if I place a stepladder and step onto it's location and then get teled by an EOC I could still use it to climb the next turn despite it being nowhere near me

### Attach save file

[Wanette-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12138650/Wanette-trimmed.tar.gz)

### Steps to reproduce

I've recreated what I did in the save with these steps but can't reproduce the bug myself so gl if anyone tries to tackle this >->
1. Deploy stepladder to the east
2. Move east to tele
3. Climb onto the greenhouse roof despite having no stepladder

### Expected behavior

Cache to be dirtied correctly on an EOC tele

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: f43a3a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Chichitech Lore and Extras [Mod_ID]
]

**Comment by chichit1044** [comment]
oh my _god_. that is... genuinely delightful to think about. a wile e. coyote style of climbing an invisible ladder and only noticing a second later that it's not there.
