### ISSUE TITLE
Burgers are (Worse) Hot Sandwiches

### ISSUE THREAD

**Issue by i-enjoy-tea** [CleverRaven/Cataclysm-DDA#67129]
### Describe the bug

According to the data on the Hitchhiker's Guide site, at some point in March 2023 somebody changed the burger recipes so that a cheeseburger is almost identical in requirements to a deluxe sandwich except that it requires heat and more time. This change in the meat category applies to all variations of the burger.

This appears to be a change in the recipe from 'meat_red' to 'meat_cooked', which has resulted in an absolute butchering of the recipes. Raw meat (which one would expect to be minced up into a patty) is no longer a valid ingredient in favor of "precooked" options despite the recipe requiring a heat/power source for the meat, and whoever did this even added a comment of "power usage mostly for the meat, though this arguably doesn't even need power since meat is pre cooked" and left the cooking part in.

The worst part of this is that the entire concept of a burger has been completely thrown out of the window as the valid ingredients in lieu of an actual hamburger patty are now things such as: cracklins, jerky, _just_ bacon, bologna, SPAM, canned chicken, all sorts of fish and shellfish, sausages, or even _aspic_.

I think most people can agree that there should be certain standards for recipes even in the apocalypse and that you can't just throw the above things in between bread and call them a burger. If a hot/toasted sandwich/melt or whatever is desired, then I feel like it should probably be its own separate item.

----

Also this has also made me aware as to how inferior the burger recipes are compared to the deluxe sandwich, which honestly shouldn't be so. Despite requiring almost the same ingredients, a slightly higher cooking skill, more time, access to heat/power, and half the portions (1 instead of 2), the cheeseburger is vastly inferior. Even with the EATEN_HOT flag, the hot meal bonus for this item is only +2 for a total of 7 morale.

It should at least be on par or better than the sandwich IMO, with the deluxe cheeseburger being unquestionably superior (currently it is at a meager base 7 enjoyment despite it being a very strict and demanding recipe). Hamburgers would probably be slightly worse but they are much more complicated than the meat sandwich in comparison.

### Attach save file

N/A

### Steps to reproduce

1. Make a new character
2. Acquire burger recipes through play or debug
3. Look at them

Alternatively, just look [here](https://cdda-guide.nornagon.net/item/cheeseburger?v=cdda-experimental-2023-07-22-2222)

### Expected behavior

I expect a burger recipe to actually look like a burger recipe and not a worse clone of the sandwich recipe that also needs to be cooked.

Specifically, revert the changes and make it use meat_red instead of meat_cooked again. The time and heat/power required were not even reduced in the change to use "precooked" meat, so nothing even needs to be changed there.

Also while we're at it, maybe buff the enjoyment of the burger recipes as mentioned above? Maybe increase the crafting time slightly to compensate if they get buffed since 9 minutes seems kind of short even if it was the original recipe time.

### Versions and configuration

Cataclysm-DDA experimental build 2023-07-23-2055

**Comment by Vaskritaya** [comment]
relevant PR for this change according to git blame:
https://github.com/CleverRaven/Cataclysm-DDA/pull/62180

**Comment by Theawesomeboophis** [comment]
Ah yes, my favorite way to prepare a burger, with pickled fish and cracklins.
