### ISSUE TITLE
Recipe for non-canned kompot yields the same result every time regardless of ingredients.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67121]
### Describe the bug

Recipe for non-canned kompot yields the same generic kompot with 135 calories and 25 % vitamin C regardless of which ingredients you use (unlike the canned versions).

### Attach save file

N/A

### Steps to reproduce

1. Make a player with: survivor mess kit, sugar, clean water and some fruits/berries, e.g. apples and kiwis.
2. Set food handling to >= 3
3. Make kompot recipe.
4. It will generate a generic kompot with 135 calories and 25 % vitamin C regardless of which ingredients.

### Expected behavior

I expect non-canned kompot work the same as canned kompot and have a different names, calories and vitamins depending on which ingredients you use.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.6085 (1607)
- Game Version: bd86ffe [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by RenechCDDA** [comment]
...Sure but that's because of the literal error you get about the components not being able to be split. Please include that information in the future?

**Comment by FinWeirdoh** [comment]
If there is component slitting error then its same bug I´m having with french fries. https://github.com/CleverRaven/Cataclysm-DDA/issues/67064

**Comment by ampersand55** [comment]
> ...Sure but that's because of the literal error you get about the components not being able to be split. Please include that information in the future?

Oh, I think I just [I]gnored it the first time it happened in game and forgot.
