### ISSUE TITLE
Revive zombies respecting their death cause.

### ISSUE THREAD

**Issue by S0ZDATEL** [CleverRaven/Cataclysm-DDA#67126]
### Is your feature request related to a problem? Please describe.

Right now zombies revive into themselves or their evolved version.

### Solution you would like.

Maybe track the cause of their death and revive them with respect to their wounds? For example:
| Cause of death | Revives into |
|--------|--------|
| Critical to a head | Brainless zombie |
| Critical to a leg | Crawling zombie |
| Acid | Decayed zombie | 

### Additional context

We would need to decide what to do with zombies other than normal ones. For example, if a crawling zombie dies from a critical hit to a head, should it revive as crawling or headless? But this could at least be applied to normal zombies.

**Comment by Qrox** [comment]
It would make more sense to keep the zombies' wounds (that the blob cannot or doesn't bother to repair) after revival and migrate the brainless/crawling/decayed zombies into normal zombies with wounds to avoid having to design a wounded counterpart for every kind of zombie which also solves the problem you mentioned about multiple wounds.
