### ISSUE TITLE
Game keeps crashing on Mac OS

### ISSUE THREAD

**Issue by DonDawsy** [CleverRaven/Cataclysm-DDA#67138]
### Describe the bug

The game will crash sometimes after killing an enemy. I have tried copying the save to a Windows PC, and I can keep playing there so this must be a Mac specific issue. 

Just started a fresh game in a fresh world, and played for about 2 hours before it happened. It happened on an earlier save too in a different world.

### Attach save file

[Carsonville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12147540/Carsonville.zip)

### Steps to reproduce

Kill creature

### Expected behavior

Expected not to crash

### Screenshots

![SCR-20230724-plfg](https://github.com/CleverRaven/Cataclysm-DDA/assets/62935851/ef4aa90d-5daa-462c-83de-8f277d7718ae)

_No response_

### Versions and configuration

-OS: MacOS Ventura 13.4.1 (c)
-Game Version:  Cataclysm DDA version 0.G-3179-gc238a025bf

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12147533/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12147534/debug.log)

**Comment by LyleSY** [comment]
As far as I can tell the achievement it's failing to find does exist in .G https://cdda-guide.nornagon.net/achievement/achievement_arcade_mode?lang=el&v=0.G

**Comment by DonDawsy** [comment]
Yeah I found it as well, not sure what triggers the achievement though. When I load the game on Windows and kill a few zombies I get the same error, but the game doesn't crash and I can just ignore it. On the Mac it always throws the Segmentation Fault and crashes.
