### ISSUE TITLE
Torch, The Louverture, and other flame weapon changes

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#67136]
### Is your feature request related to a problem? Please describe.

In game, you come across many enemies that are nigh invulnerable to everything except fire. Weapons with the FLAMING flag do have a snippet on fire damage "You Burn the X". However, there is no other effects other than increased damage. This also applies to The Louverture mace's spell of shooting out flame clouds by igniting gas, you would expect ignited clouds of gasoline to light enemies on fire, right?

### Solution you would like.

Weapons with the FLAMING tag should be able to give the burning status to monsters on hit, and The Louverture's weapon spell should be able to do the same.

### Describe alternatives you have considered.

Not do this? ~~idk~~ maybe allow warding off monsters that fear fire with torches?

**Comment by fairyarmadillo** [comment]
The extra damage the flaming weapon is dealing is fire damage, which does bypass most enemy armor. I don't see any particular reason that brief contact with a burning stick would set someone on fire though, it's not like they're covered in accelerant.
