### ISSUE TITLE
Dating or hooking up plus sexuality and gender identity 

### ISSUE THREAD

**Issue by natenmdemon** [CleverRaven/Cataclysm-DDA#67149]
### Is your feature request related to a problem? Please describe.

There's not a lot of characterizations and social interactions. 

### Solution you would like.

There needs to be sexuality and gender identity, the ability to date or hookup,

**Comment by dseguin** [comment]
This is a hard "no", sorry.

**Comment by RenechCDDA** [comment]
To quote Kevin Granade, project lead: "the game does not and will not have a representation of sex"

**Comment by natenmdemon** [comment]
It doesn’t need to explicit like the screen can turn black or something.
But I’m confused what do you by that?
