### ISSUE TITLE
Unloading items

### ISSUE THREAD

**Issue by Dlightfull** [CleverRaven/Cataclysm-DDA#67158]
### Is your feature request related to a problem? Please describe.

I am often frustrated when i unload items and they go to my inventory. 

### Solution you would like.

I would like to have an option to unload the items on an outside tile.

**Comment by EternalLaughter** [comment]
Have you tried binding and using the "unload container" key?

**Comment by Dlightfull** [comment]
> Have you tried binding and using the "unload container" key?

I did after you told me and it works wonders! Thank you very much good sire!
