### ISSUE TITLE
Impossible to start a blacksmithing career from scratch after the Bonanza update

### ISSUE THREAD

**Issue by Dlightfull** [CleverRaven/Cataclysm-DDA#67157]
### Describe the bug

After the Big Blacksmithing Bonanza update (67103), it became impossible to start blacksmithing without looting instruments. Before that, one could craft his own instruments one by one, getting a full set needed for the more complicated jobs. That meant that one could start crafting metal gear only by having access to metal and a forge. 

Now, some instruments needed in the recipes are only available by looting, since they need themselves as a tool for crafting. Maybe it is realistic this way and it's intended behavior, but then i ask myself how did blacksmithing as a profession be available in the real life, since they would've not been able to craft their own tools...

### Attach save file

N/A

### Steps to reproduce

1. Make any player and get enough fabrication to access blacksmithing recipes.
2. try to make a full set of tools for the most complicated crafts.

### Expected behavior

I expected it would be possible to either craft those tools without themselves as a requirement or to be able to use more mundane tools, craftable without overly complicated requirements.

### Versions and configuration

Version a91199f

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/140479772/78bff1cc-2fe3-496b-975a-ba0bffd6b8f0)

**Comment by PatrikLundell** [comment]
I agree that there should be a way to progress blacksmithing from scratch. This can be achieved by replacing the requirement of a tool's own tool quality to make it with a requirement for a lower level of quality that then has to be provided by a simpler, possibly makeshift, tool (that obviously can be made by simpler tools still).
Another way to achieve this is to provide an additional recipe for the tool that requires "lesser" tools but requires considerably longer time. An example of an alternative tool is the polishing stone, which is a pain to make, but it provided a way to climb the tool ladder (I haven't checked whether this remains the case, of it it was broken as well).

Once the progression path has been restored, the workshop expansions need to be updated to provide the recipes to create all the tools (at least workshop expansion 2, which was tuned to provide such a path).

**Comment by EternalLaughter** [comment]
I would also prefer all the tools that are logically craftable, be so, so you can actually bootstrap yourself, if you want to or have to.
As for the specific issue here, flatjaw tongues, or well many types of tongues, they are perfectly craftable without tongues.
It will take more time. How much, i don't know.
A quick google actually makes me think this is a thing for new smiths, making tongue without tongues.

https://www.youtube.com/watch?v=dHrgefJ7NvI 

https://www.youtube.com/watch?v=3vOqFw0959s

**Comment by Karol1223** [comment]
Tongs can be cast but we don't have a fully-fledged system for casting and a way to simulate cast versions being less durable (also see: #67144). This applies to many of our tools. As it stands, our metalworking is in shambles when it comes to realism and I opened Pandora's box by fixing one part of it without touching the rest.

**Comment by TrueChevaleresse** [comment]
With all due respect, should changes that are actively detrimental to gameplay like this not be reversed or delayed until such a time as the supporting systems are also corrected to make them into positive changes? I've noticed several changes to isolated functions or items that ignore the fact that games are made of _systems_ and thus can't always be improved by making line-by-line changes, like the ones resulting in this issue.

**Comment by Karol1223** [comment]
> With all due respect, should changes that are actively detrimental to gameplay like this not be reversed or delayed until such a time as the supporting systems are also corrected to make them into positive changes? I've noticed several changes to isolated functions or items that ignore the fact that games are made of _systems_ and thus can't always be improved by making line-by-line changes, like the ones resulting in this issue.

Reminder you're playing experimental. Experimental is for experimenting. Things will break. Not all changes will be immediately positive. Not all PRs will do everything in one part.

**Comment by PatrikLundell** [comment]
It can also be noted that @Karol1223 is hard at work on a PR addressing these issues, hampered by pesky types (like me) throwing in additional issues while looking at the changes.

I plan to to update the Workshop 2 expansion recipe ladder once that work has been done.

**Comment by TrueChevaleresse** [comment]
> Reminder you're playing experimental. Experimental is for experimenting. Things will break. Not all changes will be immediately positive. Not all PRs will do everything in one part.
> 
> Merging PRs like this isn't a problem as long as they don't break the entire game. It's part for the course.
> 
> Truth be told it'd be nice if we had this clarified somewhere because I feel like it's a common disproporiton between what players expect (and are used to from other games) and how development works around here.

Well, yes. It's an experimental version. The point of an experimental version is to change things that need changing. This is a keystone of a common playstyle, and it's currently broken, so it should change again, until it can be changed a third time in a way that doesn't break the playstyle. It also means that imperfect solutions (e.g., something like the spinning recipes where you can make the same item at greater time/material/failure expense with inferior tools) are viable to bundle in to fill out obviously missing features.

It's also important to remember that a significant portion of players aren't actually playing stable and randomly breaking things for people who play experimental but aren't actively modding/debugging said breaks away is something to be avoided where possible.

**Comment by PatrikLundell** [comment]
It's a matter of balancing the size of changes and the ability of reviewers to review the volume versus the wish to make a complete set of changes in one sweep.

It's also a matter of contributors not necessarily being able to foresee that changes will affect things outside of the immediate scope of the changes, as well as contributors not being familiar with the areas those ripple effects impact.
