### ISSUE TITLE
Pair of chelsea boots has a typo.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67153]
### Describe the bug

In the description it says "dawning and doffing", when it should be *donning*.

### Attach save file

N/A

### Steps to reproduce

Look at the description. See the incorrect homonym. 

### Expected behavior

I'd expect the proper word to be used?

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/6d6699c9-8dd5-4772-b787-6bc5da9d8a1c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 520db0c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by terr-steak** [comment]
Can confirm that the description in data/json/items/armor/boots.json has the incorrect usage of 'dawning', instead of the correct 'donning'. (ln# 1643)
