### ISSUE TITLE
Allow mutation visibility values to be referenced in dialogue conditions

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#67152]
### Describe the bug

In the mutation documentation, a visibility entry is referenced for use in NPC dialogue, which dictates how visible your mutations are. Despite my research, this value cannot be referenced in dialogue conditions for use as it was intended.

### Attach save file

N/A

### Steps to reproduce

1. Make new dialogue
2. Try to reference it in a condition
3. Fail miserably

### Expected behavior

I expect to be able to call on this when I need to.

### Versions and configuration

OS: Windows 11
-Game Version: cdda-windows-tiles-x64-2023-07-09-0709
-Graphics Version: Tiles
-Ingame Language: English (US)
-Mods: Default Mods

### Additional context

If nobody wants to code this, I suppose I could make an EOC that adjusts a personal variable that governs total mutation visibility, and use that value instead.

**Comment by RenechCDDA** [comment]
What condition are you using exactly? I do not and have not seen any condition for mutation visibility.

**Comment by MNG-cataclysm** [comment]
`
{
  "id": "LIGHTEATER",                         // Unique ID.
  "name": "Optimist",                         // In-game name displayed.
  "points": 2,                                // Point cost of the trait.  Positive values cost points and negative values give points.
  "vitamin_cost"                              // Category vitamin cost of gaining this trait (default: 100)
  "visibility": 0,                            // Visibility of the trait for purposes of NPC interaction (default: 0).
`
Found in MUTATIONS.md, it says it's for NPC interaction, yet I can't figure out how it's used, as it only returns an error.
@RenechCDDA

**Comment by SurFlurer** [comment]
Yes, the current only use case for `visibility` field is to generate a list of visible mutations for description of characters.

src/mutation.cpp: L2294
```
std::string Character::visible_mutations( const int visibility_cap ) const
{
    const std::vector<trait_id> &my_muts = get_mutations();
    return enumerate_as_string( my_muts.begin(), my_muts.end(),
    [this, visibility_cap ]( const trait_id & pr ) -> std::string {
        const mutation_branch &mut_branch = pr.obj();
        // Finally some use for visibility trait of mutations
        if( mut_branch.visibility > 0 && mut_branch.visibility >= visibility_cap )
        {
            return colorize( mutation_name( pr ), mut_branch.get_display_color() );
        }

        return std::string();
    } );
}
```

**Comment by MNG-cataclysm** [comment]
Do you think this should be eclipsed by an EOC-based system, or expanded upon in C++ for dialogue conditions?

**Comment by SurFlurer** [comment]
To make it clear, do you want to edit mutation visibility on the fly?

**Comment by MNG-cataclysm** [comment]
> To make it clear, do you want to edit mutation visibility on the fly?

Through EOCs? Probably not, as that could lead to some weirdness with particular interactions after an alteration, if the value was unable to be changed back by natural means.

I.E A fully mutated character talking to xenophobic people like nothing was out of the ordinary, if their visibility value was changed via an EOC.

**Comment by SurFlurer** [comment]
> I.E A fully mutated character talking to xenophobic people like nothing was out of the ordinary, if their visibility value was changed via an EOC.

Alright, thanks for explanation, but I have another question: What's your use case of the visibility value? Could you please elaborate?

**Comment by MNG-cataclysm** [comment]
> Alright, thanks for explanation, but I have another question: What's your use case of the visibility value? Could you please elaborate?

I was going to use it for some new dialogue with the God's Chosen (#67111). I wanted to use it as a catch-all check to see how visibly mutated the player was to another NPC and create/restrict dialogue options based off of that. I wasn't planning on checking for any specific mutations, just if the visibility number was above a particular value, like a `u_val` check.

That way, someone with a minor mutation could probably get by talking to the more xenophobic members of the group, while a post-threshold beast character would get turned away.

**Comment by Maleclypse** [comment]
Fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/67293
