### ISSUE TITLE
Frag Grenades are OP

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#67162]
### Describe the bug

When frag grenades were first converted over to using the shrapnel system, they worked about like you'd expect, chewing up soft targets but working poorly against armor, and failing against really powerful enemies. At some point, something changed, and now they pretty much one-shot any enemy in the game. Shoggoths, skeletal juggernauts, the melded task force, kraken, frog mother, and jabberwock all get one-shotted by a single frag grenade, which easily does 400-700 damage even a couple of tiles away.

A note in the task force's JSON suggests that this is entirely unintentional:  

> "//": "483 L and HARDTOSHOOT to prevent a frag autokilling them, adjust when grenades are a bit less deadly to large things.",

I'm not totally sure how this happened. I know there were some changes to critical hits that reduced or removed the damage threshold, and changes to shrapnel, especially surrounding shotguns, but I can't pin down the specific PR that caused this.

### Attach save file

n/a

### Steps to reproduce

Make a survivor
Throw a grenade at anything
It dies if it's near the center of the blast unless it's got obscene armor values
Since most powerful monsters are also slow, this is very easy to do

### Expected behavior

I don't think common hand grenades should be one-shotting regenerating armored flesh colossi. Maybe a rocket or something, sure.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 6060d00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Krieger1999** [comment]
> ### Describe the bug
> When frag grenades were first converted over to using the shrapnel system, they worked about like you'd expect, chewing up soft targets but working poorly against armor, and failing against really powerful enemies. At some point, something changed, and now they pretty much one-shot any enemy in the game. Shoggoths, skeletal juggernauts, the melded task force, kraken, frog mother, and jabberwock all get one-shotted by a single frag grenade, which easily does 400-700 damage even a couple of tiles away.
> 
> A note in the task force's JSON suggests that this is entirely unintentional:
> 
> > "//": "483 L and HARDTOSHOOT to prevent a frag autokilling them, adjust when grenades are a bit less deadly to large things.",
> 
> I'm not totally sure how this happened. I know there were some changes to critical hits that reduced or removed the damage threshold, and changes to shrapnel, especially surrounding shotguns, but I can't pin down the specific PR that caused this.
> 
> ### Attach save file
> n/a
> 
> ### Steps to reproduce
> Make a survivor Throw a grenade at anything It dies if it's near the center of the blast unless it's got obscene armor values Since most powerful monsters are also slow, this is very easy to do
> 
> ### Expected behavior
> I don't think common hand grenades should be one-shotting regenerating armored flesh colossi. Maybe a rocket or something, sure.
> 
> ### Screenshots
> _No response_
> 
> ### Versions and configuration
> * OS: Windows
>   
>   * OS Version: 10.0.19045.3208 (22H2)
> * Game Version: [6060d00](https://github.com/CleverRaven/Cataclysm-DDA/commit/6060d00d3f28462d440a65b9907af198401ed9a9) [64-bit]
> * Graphics Version: Tiles
> * Game Language: System language []
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Portal Storms Ignore NPCs [personal_portal_storms],
>   Slowdown Fungal Growth [no_fungal_growth],
>   Bionic Professions [package_bionic_professions],
>   No Rail Stations [No_Rail_Stations]
>   ]
> 
> ### Additional context
> _No response_

That took way way to long for someone to notice that!

**Comment by anoobindisguise** [comment]
> Maybe, include 40mm frag grenades, if they use similar system? (can't check currently) Not sure about HEDP ones, since interacting of shaped-charge jet and (un)living tissues is vague matter.

I've shot the MTF with 40mm grenades and they work about as well as it seems like they should, taking 3ish hits to kill since each grenade has 200 base damage. They do not one shot it, it's just a problem with frag grenades.

**Comment by Inglonias** [comment]
Not only can I confirm this, I reported it myself a while ago (and it was closed due to being stale, so I don't think this qualifies as a duplicate) ( #57734 )

**Comment by fairyarmadillo** [comment]
Does anyone understand what the specific problem is? Am I right that shrapnel is critting when it shouldn't be? Or are too many pieces hitting?

**Comment by RenechCDDA** [comment]
This seems pretty intentional. Fragmentation grenades are incredibly deadly and anything standing next to them *should* die. The monster's JSON comment can be wrong, but that doesn't make grenades wrong, it simply makes the *monster* wrong.

More specifically, there is a [test for this](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tests/explosion_balance_test.cpp) which hasn't seen any substantial changes since Kevin rebalanced grenades based on real-world data. I am inclined to believe that it is working as intended without some direct proof that the behavior has changed.

**Comment by fairyarmadillo** [comment]
Found the issues. 

1) Shrapnel is calculated as a swarm of projectiles moving at a speed relative to their distance from the epicenter of the explosion. They do damage based on their velocity squared times their mass divided by two thousand. However, and I think this is unintentional because I found a similar bug with EAT_FOOD, projectile velocity does not start to decay until the projectiles are one tile out, so that a zombie standing on top of a grenade takes exactly as much damage as one standing adjacent to it. The projectiles in both cases are all traveling at exactly the same speed, but for every subesquent tile, they rapidly lose velocity. Both cases would probably be deadly to a normal human, but standing five feet away from a grenade is an entirely different issue than standing directly on top of one.

Did the game change the way it calculates XYZ distances at some point? Did it used to count your current tile as -1 and adjacent tiles as 0? It certainly doesn't work that way now, and given that this was causing some bugs I've had to squash elsewhere, I wonder if it was changed at some point.

2) Grenades (and only grenades. Pipebombs and small homemade grenades do not appear to have this issue) are showing some weird behavior where a creature adjacent to a grenade will absorb every single piece of shrapnel traveling in that direction. I tested this with juggernauts and with humans. In both cases, the bombs always made a perfect 3x3 square of dead enemies, but not even one piece of shrapnel ever gets past those enemies. Anyone standing even one tile over is fine, and only 9 enemies will be hit even in a test chamber packed with dozens of them. Testing with small homemade grenades and pipe bombs, 9 enemies still died, but 20 or more would be hit by varying amounts of shrapnel as you would expect.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/f2b08f54-bf34-4718-9268-fa79a74fc684)
Here's an image of that in action. None of the armored zombies except the 9 closest to the grenade were harmed at all. I tested this on armored zombies, juggernauts, and feral humans. All tests killed exactly 9 enemies and no shrapnel hit any others.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/10606fed-ba6a-4d64-bcfa-95f92a2094d1)
Here's an image of a pipebomb. This killed 11 ferals and shrapnel struck about twenty of them in total. A small homemade grenade performed similarly, but not as well.

3) The small homemade grenade has a much smaller number of fragments, but they do way more damage somehow despite being quite a bit slower, making it better at killing armored enemies. The small homemade grenade is literally a tin can with gunpowder and nails in it, but it's still instantly lethal to pretty much any adjacent enemy I think probably that and the pipebomb need to be downtweaked. Both would certainly be dangerous to an unarmored person and would cause a lot of chaos, but they shouldn't be red misting juggernauts and armored zombies.

So in short
- Fragment velocity decay should begin in adjacent tiles, not one tile out. I believe this was either an oversight or a bug that popped up more recently.
- We should figure out why every single piece of shrapnel that goes through a tile hits a character standing in it. If you're standing five feet in front of me and there's a grenade five feet in front of you, I do not expect that I would be totally unharmed when it went off.
- Pipebomb and homemade/small homemade grenades need a balance pass. Part of the problem here may be that explosion fragments always have 0 armor penetration and only do flat damage. 5.56 rounds are only like 1/3 as fast as shrapnel at its epicenter but they have 13 arpen, which allows us to make sure they will kill a guy in a leather jacket but won't easily penetrate a juggernaut.

**Comment by kevingranade** [comment]
Your speed issue is a red herring, velocity doesn't decay remotely fast enough for the difference between 0 tiles distance and 1 tile distance to be meaningful. It does decay meaningfully at ~10m or so,  but even then the risk attenuation is dominated by fragments spreading out,  not loss of velocity.
The outcome of two human sized targets (the one standing on the tile and the one adjacent to it) blocking all the fragments is surprising and bears further investigation, which includes checking what happens with a single target standing next to a detonation looks like. I suspect there might be something happening with the special casing for a target standing in the same time as the bomb.
You haven't established that pipebombs are out of line,  they do in fact generate a large number of extremely damaging bomb fragments that will do a ridiculous amount of damage to a nearby target. It's analogous to being shoot dozens of times simultaneously. If a single shot will do any damage at all,  many bomb fragments will cumulatively do massive damage.  I don't recall if juggernaughts are completely immune to small guns, if they're not,  it's a given that a pipe bomb is going to mess them up. 
The homemade grenades are a red herring, they should just be removed as filing a tin can with gunpowder isn't going to make a working bomb anyway.

**Comment by fairyarmadillo** [comment]
Juggernauts are all but immune to most handguns, having 36 ballistic armor. 5.56 has a hard time hurting them but can get the job done. Kevlar hulks and armored zombies require high caliber rifles. This can be overcome by weakpoints, but shrapnel doesn't interact with the weakpoint system - IMO the fragments should have some amount of armor penetration and should have a chance to hit weakpoints which is individually much lower than the player's as weakpoint chance is skill-based and the frags are just randomly flying.

The issue with pipe bombs is that they are deadlier than grenades, which I don't think is right. They're also invariably lethal at close range, which again isn't what happens in real life. Walter Moody Jr killed two people in the late 1980s with two pipe bombs. In both cases, there were two people standing near the package when it was opened, and in both cases one was killed and one was injured. These were normal humans wearing normal clothes, not giant monsters covered in armor that can stop bullets.

Can bombs certainly do exist and were used in world war 1, though our recipe might need some improvement: https://en.m.wikipedia.org/wiki/Jam_tin_grenade

**Comment by fairyarmadillo** [comment]
[[](https://caselaw.findlaw.com/court/al-court-of-criminal-appeals/1401686.html)](https://caselaw.findlaw.com/court/al-court-of-criminal-appeals/1401686.html)

> When Judge Vance opened the package, the bomb inside detonated, killing him almost instantly.   Judge Vance's wife, Helen Vance, was seriously injured by the blast.   The pipe bomb was constructed of a steel pipe approximately five and one-half inches in length and one and one-half inches in diameter, sealed at each end with threaded end caps;  it contained smokeless gunpowder and a homemade detonator fashioned from the hollowed-out barrel of a ballpoint pen.   The device was designed to explode when the lid of the box in which it was contained was opened.   Numerous nails had been secured to the pipe with rubber bands;  the nails served as projectiles upon detonation.

Frank Black Pipe & Supply co. ( http://www.frankblackpipe.com/uploads/pipe_weight_chart.pdf ) says that a steel pipe of that diameter is about 3.6 lbs per foot - there are heavier and lighter examples as wall thickness can vary, so I picked the one in the middle. Cut down to 5.5 inches, that's 1.65 pounds for the pipe alone, or 0.75kg. Given that the device is filled with nails, smokeless powder, and a detonator, I think we can safely say that these elements would account for the remaining amount. So yes, his bomb was about a kilogram. His may have been more dangerous than ours as the trial states that parts of it were welded, and the nails he used for shrapnel (ours has none) are cited in explaining some of the more serious injuries.

I was mistaken in citing his case. There were three explosions mentioned in the trial. One killed Judge Vance and seriously injured Mrs. Vance, who had to undergo surgery as she took a piece of shrapnel to the liver. That would arguably kill an unarmored player character in our game since we don't have that kind of medical care.

Another critically injured Robert Robinson, who only died later as a result of his injuries. The third explosion was caused when Mrs. Moody accidentally opened a package containing a similar pipe bomb at their home. It exploded right in her face and injured, but did not kill her. She had injuries to her hand, leg, and one eye, but no major organs.

So we have a ~1kg pipe bomb made with smokeless powder that killed 50% of the unarmored normal humans who were in the immediate vicinity. IMO that's a far cry from a .88kg pipe bomb that always kills 100% of the skeletal juggernauts, kevlar hulks, melded task forces, power-armored zombies, etc who are standing within 1 tile of it. I'm not saying the grenades shouldn't kill these enemies, just that it shouldn't happen to all 9 of them 100% of the time - real life examples don't bear that out against ordinary unarmored humans, and these are huge fantasy monsters we're dealing with.

And even if the small homemade grenade should be obsoleted or changed, its current stats ( power 150, casing_mass 200, fragment_mass 0.4 ) are still enough to do the 3x3 square of death pretty much every time.

If this is happening solely because of the possible issue you pointed out with adjacent enemies being treated as if they're standing atop the grenade, then I'm just bikeshedding and if so I apologize.

**Comment by Montimorency** [comment]
Just a frivolous comment - I don't make any recommendation as to the game mechanics, since I'm fine with a tradeoff of PC vulnerability to explosions in exchange for the ability to ice high-tier mobs with common explosives - but infantry fragmentation grenades and similar devices are not as lethal as some people think. The trouble is with distribution, the sub-random variation in direction and size of fragmentation, meaning the difference between being peppered by some miniscule 
splinters that won't affect your performance at 1 m, to having a limb severed at 20 m. Written accounts and formal reports on the matter are quite common from the world wars and other conflicts, and moreover we have an extreme amount of realtime video evidence from Syria and Ukraine on how people react to nearby or point-blank grenade detonations. Death, on the spot 
 or from wounds, is far from guaranteed - even when the grenade lands on your very back. Just like the historical record tells us. 

As for armor penetration, there is none in real-world terms. Fragmentation grenades - that is, not hollow charges - have no armor penetration value to speak of, except against regular civilian motor vehicles. Among military platforms, there is no armor rating above "softskin" I am aware of that permits susceptibility to grenade fragments. Since the game is set in the US: STANAG 4569 Level 1 ranks grenade fragments as no greater a threat than "5.56×45mm NATO Ball (M193) at 30 meters with a velocity of 937 m/s."

Not that games often try, or need to, exactly model the kinematics of explosions. 

Making hollow charges is relatively easy, and there are plenty of hobbyist videos demonstrating it on YT. You could whip up something in your garage that would disable almost any WW2-era tank - or indeed any tank period, from above.  So there's no barrier to rebalancing for realism if we wanted to, where the most uparmored enemies would be completely 
immune to melee and kinetic weapons (except rare weakpoints or special items), and highly resistant to all but the heaviest thermal/kinetic-explosive devices, but open to critical damage from handcrafted chemical energy grenades, mines, and launcher charges (requiring a relatively-small quantity of actual explosive filler). If we were also to simulate real US military versions of such munitions, they should be mega-rare loot I think, as a unit would not reasonably be authorized to load them out from centralized storage depots until right about the lore-point at which the USG is already collapsing. 

(I don't know how the game's power armor/exoskeletons are supposed to work, or what Exodii armor is available, but heat and overpressure may be more relevant dangers to simulate for those than penetration per se. Zombies, unlike PC, are presumably not very vulnerable to overpressure.)

**Comment by fairyarmadillo** [comment]
You'd be better off opening a new issue I think, as this one is closed, but do give the new grenades a try first. I haven't had a chance to try them, but based on video evidence I've seen I do agree with your premise as far as frag grenades go.
