### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#67171]
### Is your feature request related to a problem? Please describe.

You know the drill, I comb through the game, I find errors, typos, weird sentences, lack of punctuation, I list it in an issue, somebody fixes it if they feel like it.

### Solution you would like.

Weird formulation in the upgrade description of "faction_base_modular_firestation_fireplace", not exactly sure of how to fix, aside from the fact that "grab a pot" is weird enough that I don't really get what the intended meaning is:
- Now that we have some cover, we should build a fireplace for cooking and grab a pot.  Let's put it in that dining area.

Same in "faction_base_modular_firestation1_brazier":
- Now that we have some cover, we should set up a brazier for cooking, and grab a pot.  Let's put it in that dining area.

Same in "faction_base_modular_firestation1_stove":
- Now that we have some cover, we should build a stove for cooking and grab a pot.  Let's put it in that dining area.

Steelshod quarterstaves nested group has capitalized letters when every other nested group does not:
- Steelshod Quarterstaves -> steelshod quarterstaves

Isherwood dialogue for the quest about hunting what got Barry, the end of that sentence is meh, what does "he managed to allude it" even mean? My advice would be to just cut it off, but reformulating it as "if he can bring himself to share what happened":
- Barry and Carlos went to hunt down something that killed our livestock, they tracked it into the forest.  It grabbed Barry and ran off, Carlos might be willing to tell you the story, he managed to allude it.

This e-mail in the retirement community service center logs has a very weird ending, I get the start of it being a noise complaint from one resident at the noise produced by their neighbor, but the end of the string is pretty confusing, not sure how to fix:
- FROM: Larry Landborn, Unit B11
  TO: Shady Hills Corporation, Service Portal
  RE: Noise complaint

  Hello.  I am once again requesting your help with my neighbor in B10.  There are loud sounds from all times of day.  She claims her grandkids are visiting but they are there every day!

Effect description of the Setting Sun buff in MMA has the following typo:
- You moved in such a deceptived that you have turned your opponent's attack against them. -> You moved in such a deceptive way that you have turned your opponent's attack against them.

Nested group description for mild splint vambraces has a typo (splintmail) that makes it different from the other 4 grades:
- Recipes related to forging various sizes of splintmail vambraces. -> Recipes related to forging various sizes of splint mail vambraces.

Description for mild and medium steel mirror armor is the following:
- Recipes related to constructing various sizes of Arabic style mirror armor.

But for the other 3 grades it is:
- Recipes related to constructing various sizes of viking style mirror armor.

Pretty sure this is an error since well, vikings didn't have mirror armor

The attack messages of the following DinoMod mutations need an exclamation point at the end:
- Serrated Teeth
- Triceratops Horns
- Horned Tail
Triceratops Horns could also use a rephrasing, right now it sounds more like there's a single horn with three points than three horns.

### Describe alternatives you have considered.

Waiting until I get more typos.

**Comment by Procyonae** [comment]
I got you

**Comment by Zireael07** [comment]
"Grab a pot" is literally what it says. The player is supposed to pick up (have) a  pot, i.e. a cooking implement

**Comment by Procyonae** [comment]
It's not really obvious from the JSON when this crops up but I agree "that" -> "this" could well be a good change (or even "the" if you're only allowed one of each?) if someone knows
