### ISSUE TITLE
player with common_cold be infected again

### ISSUE THREAD

**Issue by lcy03406** [CleverRaven/Cataclysm-DDA#67179]
### Describe the bug

It's now weeks after the player and NPCs cought in a 'common' cold, the player still has common cold effect. 
I checked the saved files and my backups, see the effect's duration is getting longer.

### Attach save file

[WorldA-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12167506/WorldA-trimmed.tar.gz)

### Steps to reproduce

1.Make a player and some NPCs.
2.Get common cold for them.
3.Stay with NPCs together.
4.See common cold duration getting longer.

### Expected behavior

common cold will cure eventually and get immuned for some days.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2364 (21H1)
- Game Version: 88768e1 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝)<color_dark_gray>（94.3%）</color> [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    XEDRA 超进化 [xedra_evolved],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    巨兽 [megafauna],
    恐龙世界 [DinoMod],
    Mining Mod [Mining_Mod],
    疯狂大灾变 [crazy_cataclysm],
    更多变异场景 [extra_mut_scens],
    神话武术 [MMA],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Useful Helicopters Experimental [useful_helicopters],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    生化插件槽位 [cbm_slots],
    驯服野兽 [Tamable_Wildlife],
    特色升级能力 [bombastic_perks]
]

**Comment by Night-Pryanik** [comment]
Could you please elaborate on steps to reproduce, point 2? What did you mean by "get common cold for them"? Already spawned NPCs, if they didn't initially spawn infected, can't get common cold at the moment.

Also, your expected behavior is working right now: common cold is self-cured eventually, and character gets an immunity for it for 100+ days.

**Comment by lcy03406** [comment]
Sorry  I don't know why exactly, and I don't know debug commands. My player and NPCs got cold while playing.

**Comment by lcy03406** [comment]
I think i have fixed this.

When the body is full of virus, and immunity is working, a cough nearby does not really matter,  the duration should not be extend many days.
