### ISSUE TITLE
FORCEFIELD enchant doesn't seem to work at values below 1

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#67178]
### Describe the bug

While FORCEFIELD, "add": 1 works properly, making the character immune to all damage, lower amounts don't seem to protect to the degree that they should. Even very high values like 0.99 result in a large amount of damage getting through and no attacks blocked.

### Attach save file

[Mindenmines-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12167413/Mindenmines-trimmed.tar.gz)

### Steps to reproduce

1) Add the following JSON somewhere so it loads properly: 

`  {
    "id": "force_field_generated",
    "type": "effect_type",
    "name": [ "Rippling Air" ],
    "desc": [ "The air around you is wavering strangely." ],
    "apply_message": "The world takes on a slightly bent look, as though you're a straw inserted into a glass of water.",
    "remove_message": "The world snaps back into focus.",
    "rating": "good",
    "max_duration": "1 minutes",
    "enchantments": [ { "condition": "ALWAYS", "values": [ { "value": "FORCEFIELD", "add": 0.999 } ] } ]
  }`

2) Load above game and spawn in with no armor surrounded by hulks
3) Pass one turn while under the effect of Rippling Air, which should make you nearly immune to damage.
4) Explode into chunky salsa

### Expected behavior

Forcefield effectiveness matches the listed numbers

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/a7cd0909-ae8c-4d2c-b18f-8569f519d987)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 88768e1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Mind Over Matter [mindovermatter]
]

**Comment by SurFlurer** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/5d69feefd204fce9f3a4a39e1e6293157fee74eb/src/magic_enchantment.cpp#L653

This returns an int. So value lower than 1 will likely to be treated as 0.
