### ISSUE TITLE
Make all graded weapons use copy-from

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67189]
### Is your feature request related to a problem? Please describe.

There's huge amounts of unnecessary JSON bloat that make changes and maintenance a PITA

### Solution you would like.

I'm going through each file making everything copy from the medium steel version, sanity checking values and adding handle mats and varying grade prices

For now weapons can only be repaired with their blade material, ideally damage would roll against material portions to decide what's been damaged tho imo so there'd be a low chance the handle would need repairing

This should make removing non graded versions much easier when we get to that point

Current handle mats I'm using based off of #59254:

Non-graded
`"replace_materials": { "mc_steel": "steel" }`
Mild
`"replace_materials": { "mc_steel": "lc_steel", "leather": "lc_steel" }`
Medium
`"material": [ { "type": "leather", "portion": 1.1 }, { "type": "mc_steel", "portion": 8*x  } ],` (Portion depends on weapon)
High
`"replace_materials": { "mc_steel": "hc_steel" }`
Hardened
`"replace_materials": { "mc_steel": "ch_steel", "leather": "kevlar" }`
Tempered
`"replace_materials": { "mc_steel": "qt_steel", "leather": "kevlar" }`
Budget Steel
`"replace_materials": { "mc_steel": "budget_steel" }`
Aluminum
`"replace_materials": { "mc_steel": "aluminum", "leather": "nylon" }`

Current prices I'm using:

Non-graded
Direct copy of Medium
Mild
`"proportional": { "price_postapoc": 0.75, "price": 0.75 },`
Medium
(Depends on weapon)
High
`"proportional": { "price_postapoc": 1.05, "price": 1.05 },`
Hardened
`"proportional": { "price_postapoc": 1.1, "price": 1.1 },`
Tempered
`"proportional": { "price_postapoc": 1.15, "price": 1.15 },`
Budget Steel
`"proportional": { "price_postapoc": 0.1, "price": 0.1 },`
Aluminum
`"proportional": { "price_postapoc": 0.05, "price": 0.05 },`

### Describe alternatives you have considered.

Removing the graded part of graded weapons names or handling the names and prices through #67615
Moving durable melee to just the hardened and tempered versions (ideally it would be more granular than the current flag)
Copying from each lower grade for higher grades (so hc would copy mc but ch would copy hc and qt would copy ch)
Adding extend functionality to portioned materials so I can add wire mat portions (the wire is the same mat as the blade so I can't replace it without overriding materials altogether)

### Additional context

**DONE**

**IN-PROGRESS**
- [x] #66956

**Comment by Drew4484** [comment]
Steel density doesn't significantly change between grades so as long as the handle material weights look good, that's fine with me. 

The repair material is an issue, the hc and qt stuff is supposed to be a PITA to fix. I'd rather hold off on that change until repairs_with is handled. 

Other than that, this looks good. Since we didn't have the material replace at the time, adding all of these was a nightmare so I'm glad to see it get cleaned up.

**Comment by Procyonae** [comment]
> Steel density doesn't significantly change between grades so as long as the handle material weights look good, that's fine with me.

Yeah I figured as much from a little research, I'll try to figure out a sensible way to deal with the handle weights

> The repair material is an issue, the hc and qt stuff is supposed to be a PITA to fix. I'd rather hold off on that change until repairs_with is handled. The hc and qt should use kevlar/plastic for their handle materials (this is a bit of handwavium to represent a customized grip).

They are just kevlar atm bc I can't add the wire material seperately due to them being the same as the blade so there's no way to use replace_materials to add the thermo resin part of the handle as I explained above. If repairing them with kevlar is too easy then ig I'll try manually adding repairs_with to all grades bc bombastic said making replace_materials work with repair_with would be hard

> Other than that, this looks good. Since we didn't have the material replace at the time, adding all of these was a nightmare so I'm glad to see it get cleaned up.

I mean without replace-materials everything but the weight and the couple of minor annoyances I PRed were already possible

**Comment by Procyonae** [comment]
Nvm I worked out how to make replace_materials work with repair_with \:D

**Comment by Procyonae** [comment]
What do you want me to do about DURABLE_MELEE though? From your original PR it looks like you were going for it on ungraded and hc and up but there doesn't seem to be any consistency in the actual files and making mc and ungraded different is weird imo.
I'm tempted to make the damage differences consistent too whether flat or proportional bc they're currently all over the place.
Equally if you want ch and qt to be a PITA to repair why are they currently repairable with lc and mc respectively?

**Comment by Procyonae** [comment]
On hold until kevin decides what's to become of graded weps after [devcord discussion](https://discord.com/channels/598523535169945603/598535827169083403/1134130079853707294)
