### ISSUE TITLE
Stream Mutable Test Fail

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67192]
### Describe the bug

The mutable streams added in #67065 are sometimes failing to place which causes required test fails like https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/5670359354/job/15365104268?pr=67185

I plan on fixing this myself when I've got some other stuff done, it doesn't seem to be very frequent so I'm not considering it urgent

### Attach save file

N/A

### Steps to reproduce

Run the tests lots of times

### Expected behavior

Tests not to fail

### Versions and configuration

N/A

**Comment by Maleclypse** [comment]
Closed as completed per Procyonae
