### ISSUE TITLE
"Zombie" progression path

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#67200]
### Is your feature request related to a problem? Please describe.

We currently have mutants, mycus, and cyborgs as progression paths. I have an idea for a fourth, and that's that you'd use nether mumbo jumbo to become sort of a half-zombie, gaining a ton of weaknesses and being shunned by all, but also getting the ability to unlock zombie evolutions for yourself.

The blob's "immune system" would detect this irregularity in the same way a human's immune system spots cancer cells. Hordes could become aware of you at all times and you'd occasionally get relentless hulks or other hunter-killers coming after you specifically. Liutenants who seek you out would do so earlier and more often.

The goal would be to create a new high-challenge high-reward playstyle that would saddle the player character with a lot of drawbacks, but eventually allow them to gain powers that would not be feasable for a normal mutant or cyborg.

### Solution you would like.

Through exploring nether dungeons, the player can eventually find hints about a long-dead civilization that used some kind of non-reproducible science or nether technology to try to assimilate into XE037 while keeping some degree of self-control and sanity. It was a last-ditch effort from a world that realized it was doomed.

This effort failed because it turns out the Blob doesn't like it when its food does this kind of thing. That's not to say it was directly conscious of their efforts, but the attempted mass adoption of this technology led to a rapidly worsening portal storm situation and greatly increased hostility from that world's zombies, who became much more effective at hunting the survivors down, and seemed to be able to find them wherever they hid.

One artifact/device/injection/whatever exists in a chunk of that world which is now floating around the multiverse and can be accessed under the right conditions. The player can find it and use it, but it won't do anything at first.

The next time the player character dies (and only this one time!), they get warped back to that area and their body is reconstructed. They now have a huge set of disadvantages, including reduced speed, greatly reduced intelligence, and an inability to speak to people. They appear to be a zombie and are shoot on sight for all factions, but they are not friendly to zombies. Additionally, they gain the Hunted trait, and if wandering hordes are enabled, nearby hordes will always be attracted to their tile.

But they still retain a spark of intelligence and biologically speaking are not completely dead in the same way a zombie is. By doing specific things, they can start to unlock positive mutations as their body adapts in a similar way to a zombie's - ie taking a lot of damage unlocks regeneration, burning a lot of calories unlocks brute muscle. They can even get acid and grabby powers, or regain a bit of lost brain function.

By far the coolest thing would be the ability to get necromancer/master type powers and briefly exert control over zombies in the area. This would only last for several seconds and afterwards, controlled zombies would get some kind of blob rage buff and come after you hard.

As we get more player-hunting blob liutenant enemies, these could be especially interested in revenant characters, coming earlier and more often for them. The blob could also mess with you in other ways, like more frequent portal storms or just randomly upgrading stuff while you were in the middle of fighting it.

### Describe alternatives you have considered.

* Simply not doing this. I'm half-expecting it to get shot down which is fine, but it has potential so I feel like I should post it.
* Just doing bone/grabber/whatever as traditional mutation lines. I think that would be sort of lackluster in application though as the more interesting (for gameplay) zombie mutations are either pseudomagical or incompatible with being alive.

### Additional context

The details don't matter too much here, so if there's a lore-friendlier way for the player to try to hijack the blob in their veins, that's fine too. I assume this will need heavy use of nether BS to handwave the fact that it's basically magic, but afaik that's what the nether is for.

I don't think this should feel like the blob is an intelligent actor who is aware of you, just that you're a particularly irritating bacterium in its gut and the antibodies come at you harder than they normally would.

I also don't think becoming a revenant should obviate the survival mechanics. Mycus sort of does this already and I have to admit it's a bit boring. A revenant should be only just undead enough to make them feel zombie-ish and should otherwise need to eat and probably breathe.

Rolling out something like this would IMO help experienced players tackle a new and interesting challenge as well as fulfilling the same kind of gameplay fantasy that being an undead does in games like Urbandead, Left 4 Dead, etc., especially if you could temporarily make zombies friendly or trick them into acting on your behalf.

**Comment by GuardianDll** [comment]
Lol no. The only way you can accept a zombie path is if you'll die

**Comment by fairyarmadillo** [comment]
> Lol no. The only way you can accept a zombie path is if you'll die

You do die. Did you read the proposal?

I spent a bit of time on this and posted it in good faith for review. I don't think "lol no" is a very polite response, even if younl believe the idea's a no-go.

**Comment by TrueChevaleresse** [comment]
Existing mutations do already hijack XE037 to do beneficial stuff for you. Neither for nor against the idea, but just pointing that out.

**Comment by Karol1223** [comment]
This feels like a MASSIVE lore thing to consider. I am not a fan and I don't exactly think it's fit for mainline, but I feel like trying to propose something like this for mainline would be of big enough scope to warrant Kevin himself to answer.

And yes, I do keep saying mainline because the idea of this in gameplay (putting lore aside entirely) is very interesting to me so even if it's rejected for mainline I think this could make an amazing mod.

**Comment by GuardianDll** [comment]
I just thought there was a lot of discussions with similar proposes, that was rejected
That probably was unpolite from my side, my apologies

**Comment by fairyarmadillo** [comment]
> But also I have to say that at a first glance with a title like that I had to roll my eyes. I'd suggest maybe trying to edit it into something less extreme-sounding so people aren't discouraged to read the description. But hell if I know what I'd title it...

Revenant is a little D&D-y, but I feel like it conveys the Dhampir-but-with-zombies situation here. I do want to kind of be up front about what it is in this idea post though, so the right people notice it.
