### ISSUE TITLE
Integrated Multitool doesn't specify its units of power clearly when you're out of power.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67217]
### Describe the bug

When you're low on power, the bionic multitool's error message is ambiguous. 

### Attach save file

[Langes Corners-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12187893/Langes.Corners-trimmed.tar.gz)

### Steps to reproduce

Start as a Bionic Prepper, run out of power, try to use the multitool, have it say you need 20 bionic power, rather than 20 kJ.

### Expected behavior

I would expect an error message to specify units. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/6360f8c5-7bd4-4909-93d5-76113929c0fc)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 520db0c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by deepvelocity** [comment]
It uses 20 KJ per use, not 20 Joules. All charges come in KJ by default.

**Comment by ilovehans10** [comment]
> It uses 20 KJ per use, not 20 Joules. All charges come in KJ by default. It's also in line with arc welder, which uses 20 KJ per use.

It could be nice to make it say "intergrated multitool needs 20 KJ of bionic power".

**Comment by MrHrulgin** [comment]
Updated bug report to more clearly describe problem, thank you both.
