### ISSUE TITLE
Straw is fireproof

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#67215]
### Describe the bug

Piles of straw are apparently fireproof. Them not being usable as tinder is one thing, but I threw them in the fire and after lying there for 30 minutes straight THEY WERE ONLY HOT!? 

### Attach save file

N/A, this should be replicable on all saves

### Steps to reproduce

1. Find a pile of straw
2. Throw it into a fire pit
3. Realize you can't light the fire pit
4. Throw in some wood and light it
5. After roughly 30 minutes check that the straw is fine. Just a wee bit warm

~~Bonus 6th step because it becomes even more hilarious as time passes - apparently they do get burnt up after a little bit longer than 30 minutes. They're less flammable than wood, bone or flesh, apparently, as butchery refuse and bone burnt long before them in my test case.~~ I confused myself. This didn't happen. I put it back into the stockpile and forgot.

### Expected behavior

It should burn???

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: c85ffe1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

As a bonus, I want to attach the hellish scenes happening on my loot pile right now
![obraz](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/9f8b3fd7-bb52-4357-8b3e-0885c3101569)
Apparently, they're charge based and comestible now? And so this happens. Beautiful, honestly.

**Comment by Karol1223** [comment]
Further edits: No, I think I am a moron. I have put it back into my stockpile before I was writing it. It doesn't seem to get burnt up AT ALL

**Comment by fairyarmadillo** [comment]
#65924 changed some things about straw, switching it to a comestible as several mutants can eat it and farm animals will also need to be able to do so. Its flammability can probably be solved by switching it to dry_veggy. It doesn't have charges set in its json.

**Comment by Procyonae** [comment]
I thought mowing wet grass and getting straw was ridiculous enough ;D

**Comment by fairyarmadillo** [comment]
Regular veggy should also be burnable though. It's not like carrots and potatoes are fireproof.

**Comment by Karol1223** [comment]
So for veggies being burnable, I summon @RenechCDDA the man who made things burn and made other things not burn but I am just about sure veggies are supposed to burn just *bad*. I thought they had the same flammability as flesh, though flesh did burn in my test case and this did not.

If they got changed to comestible and don't have charges manually defined we'll have to wait until the PR removing charges from solid comestibles gets merged. Which is unfortunate but understandable if they do indeed have a reason to be comestible.

But yeah they def need a material swap.

**Comment by fairyarmadillo** [comment]
I must be losing my mind. We don't have a dry_veggy material. This would be useful for things like dead leaves and other herbaceous matter which is sometimes edible.

**Comment by Karol1223** [comment]
> I must be losing my mind. We don't have a dry_veggy material. This would be useful for things like dead leaves and other herbaceous matter which is sometimes edible.

We definitely do (or did) have dry plant material

**Comment by Procyonae** [comment]
It's just called dry_plant ye

**Comment by mqrause** [comment]
I indirectly tested this with #67516 and the straw burned up after 15-20 minutes (waiting 4x 300 heartbeats). It's still probably a more sustainable fire starter than turning it into 50 tinder if you take it out of the fire right away.
