### ISSUE TITLE
Hostile Thug in Isherwood farm

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#67213]
### Describe the bug

I have found the Isherwood farm for the first time and found a Thug by the name of Nicholas Burger in the field by Claire Isherwood.
He is hostile, refusing to talk, but also just stands there unless you enter the field. I did not see any mention of him by the locals so suspect he is there in error.

### Attach save file

[Forney-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12186725/Forney-trimmed.tar.gz)

### Steps to reproduce

Just found while visiting the farm.

### Expected behavior

I would expect either for him to not be hostile or for someone to mention him as a threat to deal with or avoid.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51954159/c65e958d-bb4c-489e-a498-eaaaccc21e4b)

### Versions and configuration

Windows 11
Playing with Cataclysm-DDA experemental build 2023-07-27-1306
Part of the farm first viewed but not approached I think in builds on the 25th

**Comment by KHeket** [comment]
I thinks, houses at this farm shouldnt be damaged like others random variants. And I also very often meet zombifed creatures at the territory of the farm. I think, its better to prevent them from spawning here becaouse of npc safety and logic, that family will at least make this little territory safe from zombies

**Comment by Froffy025** [comment]
isherwoods spawned with a wasp nest on top of their silo that dropped down and killed literally all of their cattle in my latest run, which doesn't feel right. i'm not sure the lore behind how fast wasps are to set up, but i'd imagine they'd solve the issue with buckshot or something long before a nest ever comes into play.

**Comment by Procyonae** [comment]
Extras can spawn there as a side effect of special_forest and special_forest_thick being defined as forest and forest_thick in regional_map_settings.json which is to make the sparseness work right I think
