### ISSUE TITLE
Nylon gambeson incorrectly lists that it "keeps you dry in the rain"

### ISSUE THREAD

**Issue by teapot156** [CleverRaven/Cataclysm-DDA#67221]
### Describe the bug

Looking at the description of the Nylon Thin-sleeved Gambeson it says it's basically waterproof.

It's a big cloth coat so it's not really the case. Actually, it would behave pretty much like a sponge so it isn't even water friendly. Straight up water hostile.

### Attach save file

N/A

### Steps to reproduce

Put it on and go out in the rain. It absorbs water. It also makes sense, so np but it should say that.

### Expected behavior

I expect Big Tailor not to lie to me before I invest a work week making the thing.  Good armor though.

### Screenshots

n/a

### Versions and configuration

Any Version

### Additional context

N/A

**Comment by Procyonae** [comment]
> It's a big cloth coat
It says it's nylon right in the name dude

**Comment by fairyarmadillo** [comment]
Are you sure you're not getting wet from sweat? The item has the waterproof flag, but it also has 60 warmth because its basically 20 windbreakers worn at once.

**Comment by teapot156** [comment]
> Are you sure you're not getting wet from sweat? The item has the waterproof flag, but it also has 60 warmth because its basically 20 windbreakers worn at once.

I'll check it again. Maybe
