### ISSUE TITLE
dairy farm needs a better road connection

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67228]
### Describe the bug

the road leading to this dairy farm is not good

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/d6ba6f26-50a5-490d-9982-40988f040cf6)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/3e4edf91-da60-4a10-b83b-5002be191f13)

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Maybe a dirt terrain to the gate?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0.G-3254-g0e2a1a5085 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Procyonae** [comment]
Dairy farm ideally wants turning into a mutable to fit in with the other mutable farms but I'm not against a better road connection in the mean time I just skipped over it in #66463 for that reason
