### ISSUE TITLE
Is Typopheus Happy?

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#67224]
### Is your feature request related to a problem? Please describe.

The typo boulder must once again be rolled up a hill, I will add new stuff to this as I go, but the basic gist is that I find typos, lack of punctuation, obvious copy errors, bad english, weird syntax... while translating and then list it up into an issue for anyone willing, new contributor or grizzled veteran, to fix if they feel like it.

### Solution you would like.

This description of the creature "electric demon" from Magiclysm, should probably end with "With the exception of its caster/summoner" instead:
- Small, pure electric elemental, it jumps from target to target, and attack anything on his sight. Except of caster.

The attack message of the orc archer from Magiclysm should probably end with an exclamation point:
- The orc shoots you with laser accuracy -> The orc shoots you with laser accuracy!

Faction camp talk string explaining to the player the Bare Bones camp has a weird capitalization problem going on, either say Bare Bones Camp or bare bones camp:
-  The Bare bones camp is the most flexible kind of camp as you can build them anywhere[ellipsing the other 170 words]

Same with the modular field camp explanation string:
- The Modular field camp is the second most flexible kind of camp,

Modular field camp's explanation string also has a weird double space after the 8 in step 1, and while you're at it, it could use reformulating:
- You can build up to 5 more rooms or shacks, 3 on each side of the camp in version 1, and a total of 8  in version 2. -> Version 1 will allow you to build up to 5 more rooms or shacks, 3 on each side of the camp, while version 2 allows you to build up to 8 more all around its perimeter.

The problem child modular field camp string does not stop being an issue there however, as in the closing paragraph, it introduces the option to use tents very abruptly, which could be changed the following way:
- so you aren't constrained by what you start with.  Tents are fast to put up, but fragile and likely to get destroyed by zombies.  The central building has to be made from a 'real' building material, while the rooms can be made from tents. -> so you aren't constrained by what you start with.  If you are limited in ressources, tents are a fast and cheap way to provide shelter, but fragile and likely to get destroyed by the first zombie stumbling in, as for the central building, it will have to be made from a 'real' building material.

Not explicitly a typo, but this hint was forgotten by the police bot obsoletion:
- Police brutality lives on it seems.  It's just more mechanical now, with all the cops dead and cop robots roaming free on the loose.  If you'll get arrested who will give you justice?  A zombie judge?  Will they put you in a zombie prison?  No thanks, I'll pass.

This one could also be removed, as it is not exactly good advice, or changed to suggest that laying traps around you when sleeping in an unfamiliar place is a good idea:
- If you're spending the night in a dangerous area, grab a shovel and dig pits all around your camp.  If it's more than one night, you might want to put broken glass or sticks inside the pits for better effect

Attack messages of Dinomod's special dino attacks Horn and Horns should have a period at the end for consistency on the armor absorption strings, also, using they for a single horn is bad English, so change to "it":
- [Enemy]'s horns hit your [Body Part] , but they glance off your armor! -> [Enemy]'s horns hit your [Body Part] , but they glance off your armor.
- [Enemy]'s horns hit [NPC], but they glance off their armor! -> [Enemy]'s horns hit [NPC], but they glance off their armor.
- [Enemy]'s horn hit your [Body Part] , but they glance off your armor! -> [Enemy]'s horn hit your [Body Part] , but it glances off your armor.
- [Enemy]'s horn hit [NPC], but they glance off their armor! -> [Enemy]'s horn hit [NPC], but it glances off their armor.

Same thing with these bite attacks:
- [Enemy] tries to rip your [Body Part] with its sharp teeth, but fails to penetrate your armor! ->[Enemy] tries to rip your [Body Part] with its sharp teeth, but fails to penetrate your armor.
- [Enemy] tries to rip a gash into [NPC], but fails to penetrate their armor! -> [Enemy] tries to rip a gash into [NPC], but fails to penetrate their armor.
- [Enemy] tries to pull your [Body Part] apart with its sharp teeth, but fails to penetrate your armor! -> [Enemy] tries to pull your [Body Part] apart with its sharp teeth, but fails to penetrate your armor.
- [Enemy] tries to pull away a large chunk of flesh from [NPC], but fails to penetrate their armor! -> [Enemy] tries to pull away a large chunk of flesh from [NPC], but fails to penetrate their armor.
- [Enemy] tries to bite into your [Body Part] with its sharp teeth, but fails to penetrate your armor! -> [Enemy] tries to bite into your [Body Part] with its sharp teeth, but fails to penetrate your armor.
- [Enemy] tries to bite into the flesh of [NPC], but fails to penetrate their armor! -> [Enemy] tries to bite into the flesh of [NPC], but fails to penetrate their armor.

Funny typo in the chartreuse green pants description (boddy):
- An almost florescent set of yellowish-green pants with two deep pockets.  Considering that chartreuse has better night-visibility than most other colors, these pants, apart from being a nightmare to match with other hues, would probably be an ill-advised choice to dawn if you wish to keep your legs attached to your boddy.

Aftershock Prepnet dialogue string missing an end period and slightly bad English towards the end:
- Here?  Fruits and berries.  Maybe the occasional piece of farm equipment, but you need crypto coins -> Here?  Fruits and berries.  Maybe the occasional piece of farm equipment, but you'll need crypto coins.

Xedra Evolved's dreamdrossed quarterstaff has no plural from what I can tell:
- dreamdrossed quarterstaff -> dreamdrossed quarterstaves

Optional, since it's an abstract, but pseudo terrain's description annoys me:
- this should never actually show up, it's a pseudo terrain -> This should never actually show up, it's a pseudo terrain.

### Describe alternatives you have considered.

- Not pointing out typos, errors, and miscellaneous stuff that sticks out to me while translating.
- Fixing them myself.

**Comment by Procyonae** [comment]
Roger that
