### ISSUE TITLE
Add actual effects of stats to the stats screen for character creation

### ISSUE THREAD

**Issue by teapot156** [CleverRaven/Cataclysm-DDA#67237]
### Is your feature request related to a problem? Please describe.

I've been playing this game for awhile but had no clue how detailed certain things like stats are. It would be nice to see that dexterity isn't just hit chance but also dodge base, for instance.

### Solution you would like.

Put what's the first image, into the 2nd. Red circles mark what I'm talking about.

![7-28-23 9-39-10 AM](https://github.com/CleverRaven/Cataclysm-DDA/assets/38711875/d2fe4764-2253-4800-9c3c-5a13c66eacdb)

Detailed strength effects should be listed. Lots of room for it.

![168124610-66481862-dc14-483c-8c9b-1d6b72238052](https://github.com/CleverRaven/Cataclysm-DDA/assets/38711875/0ff5c93b-699f-43ff-b5fa-ffc3cc830210)

### Describe alternatives you have considered.

Keep everything the way it is. This also creates an unnecessary learning curve of going to the wiki. Some people never use it so they may never understand.

### Additional context

N/A

**Comment by Night-Pryanik** [comment]
You mean something like https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/70 ?

**Comment by anoobindisguise** [comment]
The wiki is also usually wrong.
FWIW I've tried multiple times to figure out what "ranged penalty" does but I can't seem to figure it out. So it's definitely confusing.

**Comment by teapot156** [comment]
> 

Yes, it says "merged commit into master...". Why don't I see it?

**Comment by teapot156** [comment]
> You mean something like [Cataclysm-TISH-team#70](https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/70) ?

Yes, it says "merged commit into master...". Why don't I see it?

**Comment by Night-Pryanik** [comment]
It's created and merged in another fork, not in DDA. I plan to port it to DDA someday.

**Comment by Zireael07** [comment]
@Night-Pryanik That's very good to know

**Comment by teapot156** [comment]
> It's created and merged in another fork, not in DDA. I plan to port it to DDA someday.

Please do. I think it's more important than people realize.

**Comment by teapot156** [comment]
These proceedings are closed.

**Comment by Zireael07** [comment]
No, it is not closed as the PR hasn't been ported to DDA yet.

**Comment by teapot156** [comment]
> No, it is not closed as the PR hasn't been ported to DDA yet.

These proceedings have been reopened
