### ISSUE TITLE
(Seg error/game crash) Dropped active music instruments crash the game

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67234]
### Describe the bug

If you take an active musical instrument in your hands and try (d)ropping it,then doing anything that takes a turn (walk,wait etc),the game would crash.

### Attach save file

[Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12193032/Test-trimmed.tar.gz)

### Steps to reproduce

1) take an musical instrument in your hands 
2) (a)ctivate it
3) drop it while its active
4) do anything that takes at least 1 turn
5) the game crashes (not even an error screen pops up)

### Expected behavior

I dont even wanna say anything tbh

### Screenshots

Not needed

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: ZTE; Model: ZTE Blade A5 2019; Release: 9; Incremental: 20191012.104430; 
- Game Version: 6dc51c7 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Innawood [innawood],
    MST Extra [MST_Extra],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

Im not sure if it works with other instruments (I've only seen it happen with the bone flute) please, check the other instruments aswell.

Edit: I've got this thing,maybe it'll help 
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12193661/crash.log)

**Comment by Hirmuolio** [comment]
Can't reproduce.

Log says crash is in `musical_instrument_actor::use`.
For dropped items `musical_instrument_actor::use` just does immediate early exit so it doesn't even do anything.

https://github.com/CleverRaven/Cataclysm-DDA/blob/125a961fd993becd90917d7f21d365fb94dd583e/src/iuse_actor.cpp#L2030C5-L2033C6

    if( !p ) {
        it.active = false;
        return std::nullopt;
    }

**Comment by SurFlurer** [comment]
> * Game Version: [6dc51c7](https://github.com/CleverRaven/Cataclysm-DDA/commit/6dc51c77b71c98a9253a54fd240622d9851cd6dd) [32-bit]

Would you like to update your game and test if this still happens?

**Comment by GlordXd** [comment]
> > * Game Version: [6dc51c7](https://github.com/CleverRaven/Cataclysm-DDA/commit/6dc51c77b71c98a9253a54fd240622d9851cd6dd) [32-bit]
> 
> Would you like to update your game and test if this still happening?

As for the 82773c3 (the latest build at the moment im writing this) the issue no longer occurs,i guess i just got a little outdated.
