### ISSUE TITLE
master json broken

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#67238]
### Describe the bug

The following error report is issued when trying to load a save using just downloaded and compiled master:

 DEBUG    : Error: Json error: data/json/effects.json:1�807:21: Expected an object, got array

      "Your eyes burn out of smoke, and you hardly see anything."
    ],
    "apply_message":
                    ^
                     [
      [ "Your eyes mildly irritate.", "bad" ],
      [ "Your eyes watering out of smoke.", "bad" ],

 FUNCTION : load_game
 FILE     : C:\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1035
 VERSION  : 0.G-2849-g79cb8e52b7

### Attach save file

N/A

### Steps to reproduce

1. Download master
2. Compile
3. Try to load a save.
4. Get JSON error report.

### Expected behavior

master shouldn't contain rejected JSON content.

### Versions and configuration

Can't generate info since the game won't load to a stage where it can be generated.
- Windows
- Experimental master as of a few minutes ago (about 1400 hours GMT)
- Default "mods" as of the creation of the save probably a year ago, but with most recent change a month or so ago (CDDA, no NPC food, probably bionic professions)

**Comment by SurFlurer** [comment]
> VERSION : 0.G-2849-g79cb8e52b7

Sorry if I'm insane or something, but this doesn't look like master?

I saw `Game Version: 0.G-3254-g0e2a1a5085 [64-bit]` in other issue reports.

**Comment by PatrikLundell** [comment]
It was compiled from a fast forwarded master, although execution was after I'd made a branch from it with no code changes (I had changed a different JSON file, placing a makeshift hammer on construction rather than a hammer as a result of a makeshift hammer input), but the compilation happened before that anyway.

I have no idea of how version ids are generated, nor whether the error report pulls out the correct number when compiled locally.

Regardless, of others have reported it as well, their version number may be "better", and it's better still if it's confirmed to no longer be an issue in the current master.
