### ISSUE TITLE
New type of label for issues(ignore this pls)

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67248]
### Is your feature request related to a problem? Please describe.

I've noticed that contributors and devs dont reply to every single one of issues,and thats perfectly understandable,no one has free time 24/7 nowadays,but because of that it seems like they ignore them,so i figured out it would be nice to add a new lable - "Checked"

### Solution you would like.

The label itself,or a new thing which identifies that the issue has been viewed by the devs/contributors (idk how it works on github thought,so there might be some room for imagination)

### Describe alternatives you have considered.

Anything else you might come up with.

### Additional context

Its probably too big of a request,and this label might be useless (or potentially very overused) but im just giving some ideas,who knows,maybe the higher ranks of this community will hear me,and do something like this

(_if everything fails,i can always try to bribe them with pictures of cute cats_)

**Comment by Karol1223** [comment]
There is just no way this would work. Okay, one person reviews it, and marks it as "Checked". What does that mean for absolutely anyone else? Just because someone looked at an issue doesn't mean anything at all. Does it mean other contributors don't need to look at it because someone else did? I just don't see the reasoning here.

**Comment by GlordXd** [comment]
> There is just no way this would work. Okay, one person reviews it, and marks it as "Checked". What does that mean for absolutely anyone else? Just because someone looked at an issue doesn't mean anything at all. Does it mean other contributors don't need to look at it because someone else did? I just don't see the reasoning here.

Eh,i kinda regret making the whole issue already,so I'll just close it i guess
