### ISSUE TITLE
Leather seat is too small

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67263]
### Describe the bug

leather seat length of 20cm , which means it perfectly fits inside my messenger bag.

i don't know about the other seat kinds.

### Attach save file

N/A

### Steps to reproduce

Look at it in HHG or in-game

### Expected behavior

Big seat means big comfy, i think.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0.G-3254-g0e2a1a5085 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by GlordXd** [comment]
20 cm? Thats like,an average electronic tablet (and im pretty sure thats not an baby seat)

**Comment by Karol1223** [comment]
It doesn't have a defined ``longest_side`` so it's calculated as a perfect orb. No need to thank me for that mental image.

**Comment by GlordXd** [comment]
> It doesn't have a defined ``longest_side`` so it's calculated as a perfect orb. No need to thank me for that mental image.

You're telling us that the game recognises the seat as an orb? Thats... unexpected

**Comment by Karol1223** [comment]
Everything that doesn't have a manually defined length defaults to either a perfect orb or a perfect cube and I'm not 100% sure which but logic dictates it'd be the orb

**Comment by GlordXd** [comment]
What a time to live...i cant even search up the average car seat size,cuz its measured in a weird way,the "baby car seat recommendations" are seemingly the only search result,and apparently google freaks out when asked direct questions

**Comment by Inglonias** [comment]
go find someone you know with a car and bring a tape measure.

**Comment by estebandellasilva** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/89189872/59f2352a-1045-4b10-abd7-e7afae53445a)
even then with 20 cm it would be to small to sit on ... this one iss 75cm thats probably usable
