### ISSUE TITLE
[MoM] Vitakenesis Banish illnes bug

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#67260]
### Describe the bug

You can't cancel menu of purge diseases when make it.

### Attach save file

[20.07_-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12206151/20.07_-trimmed.tar.gz)

### Steps to reproduce

1. Learn this ritual
2. Use it
3. Try to cancel

### Expected behavior

You can do it

### Screenshots

![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/52249080/34fa2603-2cc4-4a3b-93c4-452f30f8501e)
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/52249080/87023743-d689-4da2-b84e-621c111d2663)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 0cc8ad5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Bionic Professions [package_bionic_professions],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Stats Through Kills [stats_through_kills],
    Useful Helicopters Experimental [useful_helicopters],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Standing-Storm** [comment]
This looks to be a problem with any use of "run_eoc_selector"
