### ISSUE TITLE
Minor error in english dialogue of 'Father Greenwood'

### ISSUE THREAD

**Issue by ClockworkCryptid** [CleverRaven/Cataclysm-DDA#67274]
### Describe the bug

small mistake in his dialogue when asking about Helena:

'Greenwood looks over his their shoulder ...'

### Attach save file

[West Nyak.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12207862/West.Nyak.tar.gz)

### Steps to reproduce

1. Ask about church
2. Ask about helena

### Expected behavior

Either 'Greenwood looks over their shoulder' OR 'Greenwood looks over his shoulder' but both is a bit much

### Screenshots

![Screenshot from 2023-07-29 20-25-55](https://github.com/CleverRaven/Cataclysm-DDA/assets/8989024/3c5c96ab-31cf-48a4-94ab-05492f396345)

### Versions and configuration

Linux mint cinnamon 21.2
0e1489e
Tiles
Language set to system deafult, which is English (UK)
dda, no_npc_food, personal_portal_storms, no_fungal_growth, No_Rail_Stations

### Additional context

not that i think its relevant, but save file provided just in case

**Comment by sadenar** [comment]
@Procyonae Confirmed simply by looking into transifex, mentioning you since this would be a good addition to the next Typo PR
