### ISSUE TITLE
Slot Machines claim to want money, but won't accept it

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67278]
### Describe the bug

If you interact with a slot machine, it says "You need $10 to play." However, it still says this even if you have a cash card with more than $10 on it, or $10 bills. 

### Attach save file

[Langes Corners-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12208023/Langes.Corners-trimmed.tar.gz)

### Steps to reproduce

Have cash and card, try to interact with a slot machine. Try to use the card, Try to use the $10 bill. See nothing happen.

### Expected behavior

I would expect that if slot machines were usable, you'd be able to use them if you had currency. And I'd expect if they weren't usable, you wouldn't get an error message that made it seem like you could use them if you brought currency.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/e6fdfd94-822b-4178-93cc-07365000fc2d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 0cc8ad5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by MNG-cataclysm** [comment]
It's an inbuilt morality feature, keeps survivors from wasting valuable 10$ bills on those machines.
