### ISSUE TITLE
Lighting level always shows "bright" if player is not on level 0. Reading in totally dark is possible.

### ISSUE THREAD

**Issue by rtxyd** [CleverRaven/Cataclysm-DDA#67286]
### Describe the bug

Same problem with #66279, Player on upstair or underground will make lighting aways *shows* "bright", if it's totally dark, unable to craft, but able to read books. If on level 0, lighting will change according to the environment and can't read books in total dark.

### Attach save file

[哈蒂斯堡-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12208615/-trimmed.tar.gz)

### Steps to reproduce

1. go upstair or downstair, make sure it's not floor 1.
2. go to a totally dark place and read a book.

### Expected behavior

1. can't read in totally dark.
2. light level display should change according to environment.

### Screenshots

level -1 totally dark

![level -1](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/306d6df9-ee85-4497-a9b3-919a90a7ff0b)
level 0 totally dark

![level 0](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/3f2c6d56-4fbd-437c-b415-7f4c61025a10)
level 1 totallt dark

![level 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/92779383-4c35-4bb2-99ec-25290c6576f3)

### Versions and configuration

OS: Windows 10
Game Version:  https://github.com/CleverRaven/Cataclysm-DDA/commit/5cca2134b2cbbe6787bb83a5493454495f195e9c [64-bit]
Graphics Version: Tiles
Game Language: 中文（天朝）
Mods loaded: [
Dark Days Ahead [dda],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by andrei8l** [comment]
/confirmed This check is nonsense

https://github.com/CleverRaven/Cataclysm-DDA/blob/5cca2134b2cbbe6787bb83a5493454495f195e9c/src/character.cpp#L2699

From: #65835
