### ISSUE TITLE
Basecamp text wants reworking

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67296]
### Is your feature request related to a problem? Please describe.

Loads of the basecamp text/dialogue is unimmersive, referring to things in gamey ways for example "version 1" etc is used alot when referring to different levels of expansions over say "basic [expansion]", and explaining stuff to the player in 4th wall breaking ways. Also NPCs refer to "you" alot when "we" would make more sense imo, if you're discussing camp stuff with an NPC then I think it's fair for them to assume they're involved with the camp or theoretical camp.

### Solution you would like.

I'm not suggesting we remove all the tutorially stuff or anything, basecamps are complicated and require explanation but rephrasing stuff to sound more real or making some of the heavily explanatory bits into thoughts after the dialogue or say certain bits being your NPCs having "drawn up detailed plans" for the different base types would do alot for immersion imo.

### Describe alternatives you have considered.

Doing this myself but writing isn't my forte and my to do list is long

**Comment by PatrikLundell** [comment]
Well, not being particular creative, I couldn't come up with any better half line (to fit available space in places) discriminator between different versions of the same thing. Didn't want to use "improved", "enhanced" or anything like that which would be somewhat insulting towards the original versions' author(s).

That said, I'm in no way against better descriptions by someone capable of providing (and implementing) them, and I'd welcome better description texts.
