### ISSUE TITLE
(After shock) Items in pressurized tanks cannot be used for crafting.

### ISSUE THREAD

**Issue by rurero2** [CleverRaven/Cataclysm-DDA#67306]
### Describe the bug

In Aftershock mod worlds, attempting to craft using items in a pressurized tank will result in a "Consume the missing components (and continue crafting?)" message, consuming resources and " "in progress ~~ (0%)" is created and crafting cannot be continued.

Pressurized tanks are "type": "GENERIC" without mods, rewriting "type": "TOOL" in /data/mods/Aftershock/items/containers.json to "type": "GENERIC" fixes the bug doesn't happen.

### Attach save file

[afsh-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12209295/afsh-trimmed.tar.gz)

### Steps to reproduce

1. Prepare the mutagen material. Liquid ammonia is usually produced in pressurized tanks.
Other recipes can be replicated this bug if they use the ingredients in the pressurized tank.
2. Start making mutagens.
3. The message "Consume the missing components (and continue crafting?)" is displayed, resources are consumed, "in progress ~~ (0%)" is created, and crafting cannot be continued.

### Expected behavior

It can be crafted like any other recipe

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

**Comment by RenechCDDA** [comment]
This was resolved by #64706

**Comment by rurero2** [comment]
Oh, I'll be careful next time. Thanks for resolving, RenechCDDA!
