### ISSUE TITLE
[MindOverMatter] destroying glowing crystal yield test tubes of crystalline dusts

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#67300]
### Describe the bug

When i destroyed the glowing crystal in a crystal outcroppings, the crystalline dusts dropped from it is in test tubes. It probably shouldnt do that.

### Attach save file

[Newtonia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12209025/Newtonia-trimmed.tar.gz)

### Steps to reproduce

1. Open attached save
2. Destroy the glowing crystal
3. test tubes filled with crystalline dusts

### Expected behavior

it not being inside test tubes.

### Screenshots

![Screenshot_20230730-181648](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/b330bff6-4203-4cc9-9a76-5d042e58096d)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: d144c9c [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks]
]

**Comment by Karol1223** [comment]
#66853 may be relevant?

**Comment by Standing-Storm** [comment]
Something something Nether bullshit

...if that's intended behavior than I should take out the default container and put it in all the item groups like the linked issue suggests.  I'll get to that in the next couple days.

**Comment by Karol1223** [comment]
> if that's intended behavior
that's the key part really lol
but default container is a whole ordeal, probably safer to just not use that
