### ISSUE TITLE
Random "Invalid alpha talker" of A Shadow

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#67304]
### Describe the bug

I encountered this bug while testing this monster's performance impacts.
```
 DEBUG    : Tried to use an invalid alpha talker.  Callstack: Spell: LTNT_LIFE_DRAIN Caster: A shadow? \ EOC: EOC_LIEUTENANT_DRAIN_LIFE_TERRAIN

 FUNCTION : actor
 FILE     : E:\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 2043
 VERSION  : 0.G-3311-g8964fd7ae1
```

### Attach save file

[usell-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12209270/usell-trimmed.tar.gz)

### Steps to reproduce

To continue this save:
1. Load the save.
2. Wait, and this error message will pop up.

To freshly reproduce:
1. Give myself IR and Night Vision abilities to better see what's happening.
2. Debug set time to midnight, and make myself debug invincible.
3. Debug spawn one A Shadow, debug spawn a vehicle, step into the vehicle and close the door.
4. Wait until this error happens.

### Expected behavior

No errors.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/85fbee4b-bca9-43a7-a09f-990d344e9f90)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/4fa9d557-2b41-49d5-81d7-8bbf004e74ee)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0.G-3311-g8964fd7ae1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Devengel** [comment]
happens to me as well

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/32de0f02-3876-4b2c-8f44-f07bb14d779e)

**Comment by Devengel** [comment]
another one, happens everytime he spawns.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12440316/debug.log)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/c00ebd16-9a78-4ffb-bf0c-f056db41cf10)
