### ISSUE TITLE
Repairing tempered weapons causes a segmentation fault

### ISSUE THREAD

**Issue by Skerald** [CleverRaven/Cataclysm-DDA#67336]
### Describe the bug

Trying to repair tempered weapons will crash the game. I had this happen with rapiers and maces. 

### Attach save file

[Clairfield-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12218227/Clairfield-trimmed.tar.gz)

### Steps to reproduce

1. Load my save.
2. Press a, /, type "weldi", enter, 2, w. or in english: Use the plugged in high-temperature welding kit to repair the mace in your inventory.

### Expected behavior

It not crashing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1556 (1909)
- Game Version: c85ffe1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Prevent Zombie Revivication [no_reviving_zombies]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12218219/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12218220/debug.log)

Maces can still be repaired using wood without crashing. 

I played a long time and periodically checked, if it still crashed. I do remember it happening before I built the car in the save, so probably at least 2-3 60 day seasons. It happened every single time.

I did briefly search for a similar bug report and found nothing.

**Comment by ampersand55** [comment]
You can't get chunks of tempered steel, so there's not way to repair tempered steel items.

See #67335

**Comment by teapot156** [comment]
For the time being just reload the arc welder so it has charges. A plugged in welder crashes the game if you repair when its plugged in and empty. Also, you can loot tge special steal from certain locations

**Comment by Skerald** [comment]
Thanks, that worked. You can apparently use craftable medium steel for repairs.

I will close this, since the bug is already known, this title is misleading and a fix is apparently in the works.
