### ISSUE TITLE
Make hair dryers and fans attachable to modular crafting stations

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#67338]
### Is your feature request related to a problem? Please describe.

Given the changes brought about by the grain farming expansion, tools for pushing air around now have an actual use; that said, given the fact that they're used for crafting - a task that typically requires lots of charges for tools more than it requires mobility - it's going to be a bit inconvenient for players to rely on changing batteries in order to replenish charges for these tools, rather than being able to just plug them in to a power source for extensive usage.

### Solution you would like.

I would like for tools for blowing air to be able to be attachable to modular crafting stations, and to be able to use the charges available to said crafting station rather than tool batteries, please.

### Describe alternatives you have considered.

N/A

### Additional context

It's also pretty realistic to be able to plug them in, since - AFAIK - most blow dryers and desk fans IRL are meant to do that anyway.

**Comment by teapot156** [comment]
Didnt know the fan and hair dryer were anything but parts

**Comment by AmarinReyny** [comment]
> Didnt know the fan and hair dryer were anything but parts

There was a farming change recently, as part of what's going to be a much larger farming overhaul, that basically changes the harvesting of grain into a more realistically laborious task than it previously was, and now harvested grain has to be dried (among other things) for long-term storage. Part of that is giving desk fans and hair dryers an actual use in that drying process.
