### ISSUE TITLE
I would like some way to repair hardened and tempered steel items.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67333]
### Is your feature request related to a problem? Please describe.

I didn't know if I should flag this as a bug or feature request, but there's currently no way to repair hardened or tempered items as they require chunk of hardened/tempered steel which you can't make or find. 

### Solution you would like.

Most realistic could be to add a crafting recipe where you re-harden or re-temper the steel with a flat materials and time cost, but I'd settle for being able to use the high-temperature kit for now.

### Additional context

I'm not going to spend weeks of in-game time to make another tempered close helm.

**Comment by estebandellasilva** [comment]
I could have sworn you could use medium steel to repair tempered steel weapons ... because i hade a saber or something like that and done that

**Comment by ampersand55** [comment]
Nevermind, you can repair stuff, it just isn't displayed correctly.
