### ISSUE TITLE
Cattle fodder(and pills ) need charge in use menu

### ISSUE THREAD

**Issue by HKMist** [CleverRaven/Cataclysm-DDA#67330]
### Describe the bug

![report](https://github.com/CleverRaven/Cataclysm-DDA/assets/50040728/dedb7ae1-3eb0-40b8-9519-b56b974aaddf)
as the screenshot 
pills can be use in eat menu so it is not that a problem

### Attach save file

N/A

### Steps to reproduce

Just get a Cattle fodder and press a

### Expected behavior

It is not a charge item

### Versions and configuration

version 2023-07-31 1024

**Comment by mqrause** [comment]
From what I can see this is purely an issue with the use menu. You should be able to use the cattle fodder from the item menu (`i`nventory > select cattle fodder with enter > `a`ctivate).

I'll try to fix the menu. Not exactly sure whats going wrong there, yet.

**Comment by AltairreAtsu** [comment]
Though I suspect it won't contribute any meaningful information, I am also having the same problem with dogs and dog food. Attempting to activate the item directly from the item menu also did not work. For the same , "Needs one charge" reason.

**Comment by mqrause** [comment]
/confirmed

Yeah, I didn't realize at first that activating cattle fodder is in fact different to activating pills. The linked PR will fix both the menu and actual activations, though.
