### ISSUE TITLE
Killer Drive gets a morale debuff from killing innocent humans while Psychopath doesn't

### ISSUE THREAD

**Issue by cdda-bugreporter** [CleverRaven/Cataclysm-DDA#67332]
### Describe the bug

As the title says the trait Killer Drive gets a morale penalty for killing an innocent person.

### Attach save file

N/A

### Steps to reproduce

1. Make a new character starting as the Death Row Convict or any profession and choose the Killer Drive trait.
2. Spawn in an npc and attack them unprovoked and kill them
3. Check morale penalties

### Expected behavior

I expected to be able to murder innocent people in cold blood with no feelings of remorse. Especially since the trait prevents guilt for butchering mortal human corpses and killing zombie children, it seemed like it was just Psychopath+ with a double-edged sword morale mechanic similar to Pyromaniac. 

The description of the Killer Drive trait suggests that the person does not have empathy, especially when its a starting trait for the death row convict who is described as having been a serial killer before the cataclysm. It feels expected that this person did not feel guilt prior to their conviction, and after breaking out of prison they would no have issue murdering innocent survivors for various roleplay reasons(they felt slighted, for the thrill). If the trait is taken with any other profession, it would make sense that these dark impulses would progress to other human beings after killing animals during their childhood as this person did not have endless monsters to kill before the world ended. 

If Killer Drive is supposed to be more like a bloodlust towards monsters and bad guys only and this is working as intended, maybe it can be changed to not conflict with Psychopath and the two can be used together instead of being conflicting traits. In this case it would make more sense for a serial killer to have Psychopath instead.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: a91199f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Qrox** [comment]
Related: #63745. Should probably check for the "PSYCOPATH" flag for the killing innocent morale penalty after that is merged.
