### ISSUE TITLE
Picking up containers with small items gives you 100s more

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#67341]
### Describe the bug

When picking up a container with small items such as pillboxes of pills, the item is suddenly duplicated when it enters your inventory. This results in the container maxing out and sometimes up to 400 more falling to the floor. 

When I updated version I also had the same thing happen with things exploding out of my backpack and throwing other items unrelated out of it.

I suspect this is a sideeffect of issue #67324

### Attach save file

[Forney-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12222224/Forney-trimmed.tar.gz)

### Steps to reproduce

On the latest version find a pill bottle with some pills (for example Multivitamins)
Confirm the quantity (ie 20)
Pick them up
Watch as lots more pills fall to the floor

### Expected behavior

Pills shouldnt appear out of thin air

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51954159/2ba12202-5449-4a93-86e9-203b386b7e97)

### Versions and configuration

Windows 11
Was ok in Experemental build 2023-07-31-0609, but when I updated to 2023-07-31-1900 it started happening. 

### Additional context

Rolling back the version in the same save, and it still occured, in the same area.

**Comment by Alm999** [comment]
No, the items are not duplicated. I believe it is the effect of the "charges" removal. All "charged" items (e.g. aspirin) were "item (400)". It was so and it *is* so, even if the game have lost the ability to display charges and lists the stack as simply "item". If a player decides to pick up such a stack the item is "converted" on the fly into n-amount of "uncharged" items, so suddenly what *looked* like a singular "item" becomes "item" and another 399 "items" appear "out of nowhere".

I believe, this shall not be an issue with new worlds, but if such a stack was generated already in a previously visited chunk of map it will remain "masked" as a singular item until pick-up action.
