### ISSUE TITLE
Can't use multi-cooker that's plugged into the grid

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#67348]
### Describe the bug

For some reason, i cannot seem to use the multi-cooker when it's plugged into the grid because it has some stuff inside despite not being the case. 

### Attach save file

N/A

### Steps to reproduce

1. set up the electric grid
2. get a multi cooker and plug it into the grid
3. (a)ctivate the plugged in multi cooker
4. `Obstruction detected`

### Expected behavior

Being able to use it when plugged.

### Screenshots

![Screenshot_20230801-174226](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/cc554cf2-b569-40e0-bd14-0da229a5134e)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: a619f82 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Sky Island [skyisland],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Xedra Evolved [xedra_evolved]
]

**Comment by Kamayana** [comment]
This is because it's seeing the cable itself as contents, but also the multicooker a long function that needs some special attention to so it'll actually consume electricity via cables. I should be able to fix this relatively soon now that I'm seemingly finished with my extension cord PR.
