### ISSUE TITLE
Scrolling through the food section of the crafting menu is very sluggish after charge removal

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#67344]
### Describe the bug

Scrolling through the food section of the crafting menu is very sluggish after the charge removal PR (#60885). I ran a profiler, went to the menu, and just held down a key to scroll through the list to see the culprit, and it appears to mainly be a massive number of calls to `Character::compute_nutrient_range()`.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/d1b9c896-592f-4f7e-be7f-529552ce60c7)

### Attach save file

N/A

### Steps to reproduce

1. Open craft menu.
2. Go to the food section.
3. Hold down Down, the menu should occasionally slow down, especially when it selects complex recipes like the reuben sandwich.
4. You can enter filters to narrow things down and spot out recipes that are particularly problematic for some reason.
5. For example, filter to `coffee` and hold down Down to quickly loop through the results. The game noticeably hitches whenever it gets to **atomic coffee**. **Black coffee**, unexpectedly, causes no hitch, even though it appears to be a more complex recipe than atomic coffee.
6. Filter to `bread` and hold down Down to quickly loop through the results. The noticeable hitch comes from **fairy bread**, while **wheat-free fairy bread** causes no hitch at all.

### Expected behavior

For it to scroll smoothly, as it mostly did before charge removal.

My assumption for the slowdown is that it's adding up the nutrients of every single ingredient individually. A more efficient solution would be to get the nutrients of a single instance of an ingredient, and then multiplying that by the number of that ingredient used in the recipe.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0466b4aa85 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by mqrause** [comment]
/confirmed

A pretty good and consistent reproduction case I found is filtering for `c:brown bread` and then just scrolling down.

**Comment by mqrause** [comment]
After getting a slightly deeper look at the code, I don't believe the charge removal has that much of an impact on this. Calculations are all done on recipe requirements, which are more or less pairs of itype and count, fully unaware of charges or not.

The issue is still recipes with complex components. Especially bad is anything containing flour products, probably as a result of #65924. From what I can see all the grains can do infinit grain <-> seed conversion, so maybe that's the issue? Not even sure if that's necessary at all or if grains could just be usable seeds without the conversion.
