### ISSUE TITLE
Need better character spawn placement for roofs

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67347]
### Describe the bug

Afaik the current way character spawning works is it chooses a map at random from the start location then it looks for tiles in that 24x24 that are roofed, if it finds some it spawns you in a random one, if not it gives you an error that it couldn't find a good spot and chooses an entirely random tile.
In the case of roofs if it picks an OM without any roof of it's own (like a stairwell) then it always errors and dumps you in a random tile, often resulting in the character spawning in midair and falling potentially multiple stories.

### Attach save file

N/A

### Steps to reproduce

The shattered sky start (requires meta progress unlock/disabled) is probably the most convenient way to reproduce bc it exclusively spawns you on roofs

### Expected behavior

If it fails to find a roofed space it should look for a floored space and only if it fails to find that (so the entire tile is open air or equiv) should it error and specify which OM it tried and should be removed from the start location/made null in the files so it can't be chosen, and then either reroll or do something else other than dropping you. Alternatively rather than erroring in that case it could just reroll the chosen OM and have some loop prevention

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0.G-3266-g55b7f27d2f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

If you could make debug tele not dump the character in open air where possible that'd be neat too

**Comment by GlordXd** [comment]
I've had something like this once: it was a evac shelter start,i loaded the character in and the game gave me that "cant find a good place error" i tried again and it just spawned me in a middle of nowhere (in a field if i remember correctly) this was a while ago though.

**Comment by Procyonae** [comment]
Yeah this isn't remotely a new error I'm surprised I couldn't find an open issue for it

**Comment by GlordXd** [comment]
I dont think theres a non-programmer way to replicate it on will (because its pretty much almost rng dependent),and probably rare enough that people just ignore the error,and if it repeats,they just make a new world, without addressing the error,because it doesn't really bother them
