### ISSUE TITLE
Strong, huge mutant characters should feel big and powerful

### ISSUE THREAD

**Issue by Skerald** [CleverRaven/Cataclysm-DDA#67343]
### Is your feature request related to a problem? Please describe.

I have played cdda on and off for years and I usually gravitate towards making large or huge mutant melee characters. 

While fun there are some bits that intuitively make very little sense and can cause some parts to feel underwhelming, when doing so.

1. Maximum health has no effect on your pain levels. You would assume, that the same exact injury on say a house cat and a lion would cause one of them more pain. Since maximum health is very often irrelevant, once you max out on pain, it makes playing characters that should feel tanky like cattle or ursine mutants feel underwhelming.

2. Monsters can still throw your huge character around. 

3. Weapon stamina use is seemingly independent of strength or size.

4. Larger, stronger characters get no encumbrance benefits. If I wore a preschooler backpack, I would not be very encumbered, except by its awkward size.

5. There are no XL weapons. If my character can craft an excellent sword, he certainly can try to make one appropriate for his frame.

6. The XL armors have the same thickness as smaller ones, while still having the same encumbrance. Armor gained from mutations also does not scale with size. A quick look at for example turtle shell thickness in real life, shows that increasing size also leads to thicker armor. Some animals get by with just size and very thick skin; there is a reason beyond overcompensating for the existence of elephant guns.

7. Movement speed stays the same. Hulks are essentially huge muscle bound zombies and they are much faster than normal zombies. This might be, because of their incredible strength, but larger strides probably play a role as well. With rare exceptions animals larger and heavier than humans are also faster than them when sprinting. This could just be humans being slow though.

### Solution you would like.

Incoming pain from injuries, but not disease or similar, should be inversely proportional to maximum health.

Smash attacks will not throw same size characters, but will cause more damage, since the energy still has to go somewhere. Kinda like the difference between a spectacular spinning car crash and just driving straight into a wall. 

Weapon stamina use should be dictated by its balance, weight and your strength and or size. Currently the mace and the arming sword use almost the same amount of stamina, despite one being head heavy and the other having a large amount of its mass near the grip, while being of comparable weight, but that might be beyond the already large scope of this request.
Size should affect stamina consumption of attacks, since if you attack with a very light weapon the motion of your arm itself would exhaust you more, than accelerating and decelerating the weapon.

Strength and size should allow you to shrug off a certain flat amount of encumbrance on anything but hands, eyes and mouth. Instead of a flat reduction a percentage could be ignored, but it might feel less intuitive and lead to combinations that result in a 100% reduction or an unsatisfying cap.

XL weapons should be craftable just like XL clothing. Bigger, heavier, but essentially the same as the smaller weapon with more damage and maybe reach.

XL armor and especially integrated mutant armor thickness should scale with size, but increase encumbrance more, which can be mitigated with strength.

Slight movement increases for large and huge characters, because a more realistic amount will be impossible to balance. 

I do realize, that implementing most of what I propose would lead to incredibly unbalanced gameplay, so here are some things, that could even it a bit, while adding verisimilitude:

Permanent hand encumbrance when crafting for bigger size characters. 

Inability or extreme penalties for using normal sized tools including things like screwdrivers, wrenches, sewing kits and welding kits. You should be able to craft your own, but some like screwdrivers will always be difficult to use.

Add guns to the list of unusable tools. Perhaps you can adapt them, but unless you are a master craftsman, the resulting contraption should be very awkward to aim and fire, even if the recoil is unnoticeable.

Needing to crouch to enter most buildings. That would feel great. Gives an immediate sense of scale and weakens combat and escape abilities during a majority of engagements. Assuming of course, that crouching does affect more than move cost and ranged defense. There might even be special high ceiling sections like factories, loading docks or atriums, where you can make a  stand (pun intended), while discouraging fighting in corridors. Perhaps add a "crouch if needed" movement mode. However this would lead to weaker huge monsters, if it applied to them as well and feeling strange, if it did not. 

Some furniture in houses like beds or tables might not be passable anymore and you will have to smash it, this could include doors, but that would be very tedious.

Predators and similar monsters might just try to impale your head, if you are big enough.

Instead of grabbing zombies could "latch on" to larger characters, this might weaken their attacks, but cause more severe penalties than a typical grab. They should only try this, when adjacent to several other zombies. I am picturing them trying wrap themself around a leg, perhaps breaking them off is impossible, without a free hand, until they die and moving will drag them with you.

Bigger targets are already much easier to shoot, so perhaps lower armor coverage of below 95% or 100% coverage pieces for bigger characters against either all attacks or just attacks from intelligent opponents.

Attacks that have an AOE component like acid sprays or explosions should do more damage to larger characters.

Lower chance to evade and more attacks will target your legs. I read that strength already reduces dodge, but size should do so as well.

### Describe alternatives you have considered.

Instead of a lot of little fixes, a central, fluid "scale" stat, calculated from both size and strength, that affects most penalties and advantages, might be easier to work with and easier to grasp for the player. To prevent cluttering the crafting menu and seeing too many weird values, it would work in stages. Strength can only increase this stat up to a point, unless size also increased. The idea being, that most strength increases add bulk to an unchanged skeleton and at higher levels increase the quality of the muscles, but size increases directly affect your normal size.

So a normal sized human with all the strength mutations, bionics and high starting stats, would enjoy significant advantages, but a large part of that strength might not be usable for armor, since it would simply become too bulky. Same for weapons, if your weight is too low, you will swing yourself around, instead of the weapon in the worst case. Larger size characters would be able to benefit from higher amounts of strength again.

This would also prevent very strong normal sized characters from being unable to use tools etc.

So a scale stat 1 is a normal average human, 1,2 a professional bodybuilder, 1,4 a strongman, 1,8 might be the limit from pure strength e.g. a high starting strength character with all of the strength mutations, but no size increases. Actual character height from chargen might influence this or not. Anything past 2 needs a size change mutation and gets hit with all of the penalties with increasing severity.

Benefits should not scale linearly, since smaller size animals are usually stronger pound for pound than larger ones (square-cube law) and because balancing this is going to be difficult enough already. Linear armor increases would quickly make one immortal, until the armor breaks.

So, you would be able to craft a size 1,2 plate armor, with 20% thicker plates and 20% or whatever encumbrance reduction 0,2 scale gives more encumbrance, but 1,4 might only increase thickness by 30% or 35% for example, while still increasing encumbrance by the full amount. This system could replace the current light and heavy versions of clothes. You would be able to equip clothes of size +- 0,2 without penalty, but larger differences will increase encumbrance and eventually become impossible to equip. This mockup also only works, when wearing a single piece of armor per location, but dividing encumbrance among layers, should be possible. For example since outer layers are usually heaviest, larger sizes would increase encumbrance there by a bigger amount. Using percentages for encumbrance reduction might be better though.

This would also allow adding more incremental size change mutations later on with minimal effort.

Of course temporary strength from things like hydraulic muscles would not cause you to suddenly be too small for your clothes.

All numbers are just very rough ideas.

**Comment by GlordXd** [comment]
If this will give us an option to craft a spear out of a tree (or a log at least) then im definitely all for it

**Comment by fairyarmadillo** [comment]
I've wanted to implement latching on for a bit so I can make giant leeches that can stick to even normal or small-sized characters. My idea was to have it be a weaker grab where you bring the enemy with you when you move around. When I get some time I'll look at that again, it'd be pretty simple to contextually have zombies use latches vs grabs when faced with a very large enemy.

**Comment by TheSaddestGoomba** [comment]
Enemies being able to latch on rather than grabbing opens up a lot of design space.
I've got a couple in mind for mutant frog zombies. One that latches onto other zombies to heal/supercharge them and another that latches onto you... and then puts your whole head in its mouth to blind and suffocate you.

That makes me wonder if something similar could be done with pulls, determining who goes toward who based on relative masses.

**Comment by TheDudeWithoutH8** [comment]
I think the "crouching inside corridors" idea could check based on general height, to which it may be advantageous to be rather short as a regular survivor but upscale to being extremely strong yet able to maneuver in corridors. Probably where being almost 2.75m tall is really hard to move around in, because I don't think most buildings have a ceiling above 10ft, and being a few inches away from the ceiling makes it really likely you'll hit your head on a light fixture.

**Comment by AureliaIII** [comment]
wait cattle is bad?
