### ISSUE TITLE
External Cargo Racks as Vanilla Storage >500L

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#67354]
### Is your feature request related to a problem? Please describe.

The cargo space gives plenty of storage, but it always felt odd that the external rack is half the storage, even though it doesn't have any roof to constrain it unlike the cargo space. The external rack also dismounts on damage, is not protected, and overall is just a worse option than the internal one, save for a few niche cases where you don't have enough welding rods and/or bolts. 

### Solution you would like.

Have it be a greater amount of storage. Not something crazy like over 1000L, but something like 600L or 700L would give good incentive to use it. 

### Describe alternatives you have considered.

Just making it 500L like the normal one.

### Additional context

Planning on doing it, but wanted some feedback on it

**Comment by ampersand55** [comment]
I always like more cargo options. 

There seems to exist 25 cubic feet (~707 L) hitch mounted cargo racks on the market ([example](https://www.target.com/p/mockins-xl-hitch-mount-cargo-bag-59-5-l-x30-5-h-x23-5-w-25-cubic-ft-capacity-black-vinyl/-/A-89371009)), so this doesn't seem unreasonable.

The cargo space isn't constrained by the roof as you can move over it, but there should really be a opaque and non-boardable piece of storage too. I'd like the cargo shelving from blaze industries to be mainlined.

**Comment by Paprika-H** [comment]
> I always like more cargo options.
> 
> There seems to exist 25 cubic feet (~707 L) hitch mounted cargo racks on the market ([example](https://www.target.com/p/mockins-xl-hitch-mount-cargo-bag-59-5-l-x30-5-h-x23-5-w-25-cubic-ft-capacity-black-vinyl/-/A-89371009)), so this doesn't seem unreasonable.
> 
> The cargo space isn't constrained by the roof as you can move over it, but there should really be a opaque and non-boardable piece of storage too. I'd like the cargo shelving from blaze industries to be mainlined.

I don't think that's ever gonna be mainlined. It's 2000L, which is 2 cubic meters. Each vehicle tile is about 0.5 meters (tile size varies from thing to thing, for gun ranges its 12 meters) and so you'd need 8 meters of height. not including the volume of the shelving or the preexisting vehicle height

**Comment by ampersand55** [comment]
I mean, there's clearly some wiggle room with regards to cargo. Regular cargo spaces would have to be 2 meters tall for them to fit 500 L and you can walk over them. and a livestock carrier can fit a whole cow.

**Comment by Paprika-H** [comment]
> I mean, there's clearly some wiggle room with regards to cargo. Regular cargo spaces would have to be 2 meters tall for them to fit 500 L and you can walk over them. and a livestock carrier can fit a whole cow.

Two meters is at least possible with cars. And for walking over them, I think that's just cause it'd be odd to not be able to walk over them if they're empty
