### ISSUE TITLE
Game crash when closing certain item menus

### ISSUE THREAD

**Issue by rosecat-dev** [CleverRaven/Cataclysm-DDA#67355]
### Describe the bug

Attempting to close certain item menus (most notably, trying to extinguish a lit candle in my case) causes the game to crash/stop responding.

This issue does not appear to be present in new worlds, only in my existing save.

### Attach save file

[Huber Ridge-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12233093/Huber.Ridge-trimmed.tar.gz)

### Steps to reproduce

1. Acquire and light candle.
2. Enter menu for extinguishing candle/starting fire
3. Attempt to close it in any way

### Expected behavior

I expected the menu to close and the game to continue as regular.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12233161/debug.log)
There is no crash.log file.

**Comment by GlordXd** [comment]
This one's similar (even though not related) and yes,it is my other issue #67210
