### ISSUE TITLE
Bug - Inserting chunk of meat into smoker duplicates meat.

### ISSUE THREAD

**Issue by Nugget-Meister** [CleverRaven/Cataclysm-DDA#67353]
### Describe the bug

See title. Meat not removed, likely a side effect of #60885 

### Attach save file

[Bug Tester.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12231426/Bug.Tester.zip)

### Steps to reproduce

1. Build smoking rack.
2. Insert charcoal.
3. Insert chunk of meat.
4. Chunk of meat not removed from inventory. Meat is somehow still in smoking rack

### Expected behavior

Chunk of meat not duplicated.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/18633499/a8058500-9b11-4a17-8f66-5a9cd4932e8b)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/18633499/9c9b54a9-0abc-4353-835c-e8561e41e34d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: b4c5469 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by mqrause** [comment]
/confirmed

Fix coming soonish.
