### ISSUE TITLE
Cannot drink bone broth

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#67359]
### Describe the bug

#67240 made the bone material inedible but that also means you can't eat anything made of bone such as bone broth.

### Attach save file

n/a

### Steps to reproduce

1. Spawn bone broth.
2. Attempt to consume it.
3. Be told it's not edible in its current form.

### Expected behavior

Bone broth should be edible - give it the water material? Is that enough?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: 4700073 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by EternalLaughter** [comment]
Can confirm, bone broth is inedible.

**Comment by ampersand55** [comment]
Fixed by #67392
