### ISSUE TITLE
Can't open Morale screen from Player Info

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#67362]
### Describe the bug

After my #65896 I noticed many `"QUIT"` actions includes the `m` key I added for only category `"OVERMAP"`.

In case of the `@` menu, it prevents the Morale menu to show, since `m` is the key bound by default.

### Attach save file

N/A

### Steps to reproduce

1. Open the `@` menu in-game
2. Press `m`
3. The UI closes

### Expected behavior

It should show the Morale UI.

Calling `input_context::register_action("QUIT")` seems to load that keybind for `"OVERMAP"` cataegory when the category for the context is not found.
This seems at least the case for "PLAYER_INFO" at `player_display.cpp` `Character::disp_info()`

### Versions and configuration

N/A

**Comment by ZhilkinSerg** [comment]
Works fine for me. Try clearing `config\keybindings.json` - e.g. it might contain some invalid keybindings from the time you have tested your changes.
