### ISSUE TITLE
Cable Rework connection issues and tool charging

### ISSUE THREAD

**Issue by bunny232** [CleverRaven/Cataclysm-DDA#67364]
### Describe the bug

Attempting to connect two adjacent appliances (for instance a battery and lamp) results in an error message 'the power cord can't stretch that far!'
Plugging in a smartphone (and other tools) does not allow them to draw charge from connected batteries to either recharge themselves or for use such as welding cars.

### Attach save file

[testy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12234744/testy-trimmed.tar.gz)

### Steps to reproduce

Spawn/obtain two appliances such as a large storage battery and a standing lamp and place them atleast a tile apart, move them to be adjacent then attempt to connect, receive the 'the power cord can't stretch that far!' error message 

### Expected behavior

The ability to plug in adjacent objects, placing two appliances next to each other results in them connecting but you can not manually connect them.
Plugged in objects should be able to draw from the power source they are plugged into, allowing proper use of an arc welder (many recipes require more then 500-600 charge of an arc welder and vehicle construction simply refuses to begin with an under powered welder.)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1371992/a28632d5-285a-4c7a-985f-09577fff2332)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1371992/991e7a6f-d54b-4562-9366-dbe96ae40fed)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1371992/e7bb83cd-cfac-48e3-bee3-2a50b4caf146)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1371992/30db2628-83c2-4265-b98b-faed45e901a3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 5f9b42d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

https://github.com/CleverRaven/Cataclysm-DDA/pull/66871

**Comment by Kamayana** [comment]
Can reproduce. Looking into it.

**Comment by Termineitor244** [comment]
/confirmed.
