### ISSUE TITLE
refillable lighter only takes kerosene

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#67368]
### Describe the bug

after updating all my gasoline in the lighter fell on the floor and i cant refill my lighter with standard gasoline

### Attach save file

N/A

### Steps to reproduce

aquire a refillable lighter
check if u can refill it with gasoline

### Expected behavior

a refillable lighter should work with gasoline

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 954bca5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]
]

**Comment by JeveGreen** [comment]
This is a recent update, to make refillable lighters use kerosene instead of gasoline, bringing it in line with real such lighters. It's not a bug.

**Comment by Daved27hundred** [comment]
Hi, I made the change. want me to add the ability to fuel them with gasoline back?
