### ISSUE TITLE
Cost of certain activatable mutations is wildly too high

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#67363]
### Describe the bug

Certain mutations have "active" states which use extraordinary amounts of kcal, thirst and fatigue. The kcal costs are already extremely high but these mutations use the exact same values for thirst and fatigue which operate on much smaller scales (dead of thirst at 1200 and exhausted tiredness at 575, compared to kcal which is several tens of thousands normally)
- Combat Adaption: Uses 90 every 10 seconds. This means you will die of dehydration after about two minutes of it being active. It makes you go from fully rested to Exhausted in the span of about a minute. 
- Insect Wings: Costs 3 every second. So you go from fully rested to Exhausted in just over 3 minutes. \
- Snail Trail: Uses 174 hunger and thirst every 100 seconds, though not fatigue - will kill you from thirst in about 15 minutes, and if you ran it all day long like a regular snail monster does it would use 150,000 kcal every day.
These mutations can't actually *kill* you as they stop working if you are at a critical level of thirst/tiredness. But it's extremely silly. Photophore works in the other direction, using only kcal and only about 9 kcal every 5 days. The only one I think is correct is Hyper-Metabolism (9 kcal per second and no thirst/fatigue) since that's for literally regrowing your body like an anime character.

### Attach save file

n/a

### Steps to reproduce

1. Add mutations through debug.
2. activate them.
3. observe your body spontaneously consuming more fuel than a v12 engine.

### Expected behavior

These should use normal levels of energy.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: 4700073 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by fairyarmadillo** [comment]
Snail trail feels appropriate. If you observe snails in the wild, they don't gush out huge puddles of goo constantly, it's something they can do for short periods of time to trap predators so they can escape. It should simply stop working if you are above a certain level of thirst, but changing it would be inappropriate as a sludged tile represents quite a lot of water and that has to come from somewhere.

It is kind of weird that monsters get to casually and constantly break the laws of physics but that's an issue for another day.

Insect wings is completely broken. Activating it doesn't do anything but sap your strength, it always provides a speed boost even when it isn't on.

**Comment by fairyarmadillo** [comment]
https://youtu.be/COOxP3_HFcM

Here's a slug excreting mucus to escape a snake. In this case he used it to prevent being swallowed, but they can also turn it on briefly if smaller critters like ants or beetles try to get them.

**Comment by TrueChevaleresse** [comment]
Slime spawning has a similar issue, though I'm unsure if that's intentional? 350 or so kcal isn't a big deal for a well-fed slime mutant, but going instantly from turgid to dehydrated is.

**Comment by Zireael07** [comment]
@TrueChevaleresse I think it's a balancing thing to prevent spamming slimes
