### ISSUE TITLE
Escape after "Confirm your selection" button input takes you to different item in inventory screen

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#67372]
### Describe the bug

When in the (i)nventory screen, and previewing what you can do with an item (with 'enter' or 'numpad_enter' by default), then pressing escape to go back to the inventory screen, the item selected will be a different one. idk the exact pattern of what the next item will be, but it seems to be a consistent cycle of items.

### Attach save file

N/A

### Steps to reproduce

1. make a player, preferably one with some default inventory items- like security guard
2. open inventory with i
3. confirm selection (enter)
4. press escape, to go back to inventory screen

### Expected behavior

the item selected when you go back to the inventory screen should be the one you were inspecting previously. i expect this because this is how the (E)xamine function works in the same menue, so itd be internally consistent, plus itd just make more sense than moving selection to another item.

### Screenshots

here i have "flashlight" selected:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19196462/d6a5968f-e34b-437f-9368-0813c1ca6550)
then i press enter to confirm selection:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19196462/6f201aab-61b4-4d13-9528-6fe06f7397a8)
then i press escape to return to inventory, and instead of "flashlight" being selected again, its "rubber hose":
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19196462/139e380e-f88b-4ba4-83f1-7096ba90e8ff)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: e0bf2b7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by GlordXd** [comment]
Had this exact issue a few days ago
82773c3
