### ISSUE TITLE
Items affected by new changes to powders and other small items only appear in single quantities

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#67378]
### Describe the bug

Items such as caffeinated chewing gum and cigarettes now only appear to spawn on corpses one at a time (that is, I can only find one on a corpse if it spawns). Occasionally when picking it up, nine other pieces of gum fall to the ground, but that doesn't always happen, meaning that such items become somewhat less common.

On a similarly related note, items found in the world sometimes suffer from a similar issue - instead of finding a painkiller bottle with 20 aspirins in a bathroom, I'll find a painkiller bottle of one aspirin. Occasionally, the other items will appear when I pick up the bottle, or the pills, but this doesn't always happen.

### Attach save file

[Dighton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12240707/Dighton-trimmed.tar.gz)

### Steps to reproduce

1. Make a new character.
2. Kill some zombies or loot some homes.
3. Pick up items like caffeinated chewing gum, aspirins, or other items affected by the changes to powder and other smaller items (lmk which PR this is, I'm having trouble finding it).
4. Note that said items only show up in the "(g)et" menu as one item.
5. Observe that, when picking up the items, sometimes other items appear, causing messages about items falling into pockets or on the ground.
6. Also observe that occasionally these messages will not appear, resulting in only picking up a single item.

### Expected behavior

Items like chewing gum, aspirin, and cigarettes should be found in quantities of multiple right away, not one at a time with the rest sometimes appearing when the player picks the item up.

It should be clear whether there is more than one of an item in a container or just one.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45751345/b1feb666-0123-4870-bcc2-9d3158567c96)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 7e079c0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Wrenchy's Mod [wrenchys_mod]
]

**Comment by mqrause** [comment]
> * Observe that, when picking up the items, sometimes other items appear, causing messages about items falling into pockets or on the ground.

That will happen if the item in question was already spawned before #60885 was merged and is a (one time) side effect of the migration. New spawns will either have the correct quantities or are affected by the issue below.

> * Also observe that occasionally these messages will not appear, resulting in only picking up a single item.

This is because of some issues with updating all the item spawns, see #67325 and #67326.
