### ISSUE TITLE
Tileset support for different sprites for empty and full containers

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#67374]
### Is your feature request related to a problem? Please describe.

I've dabbled in containers recently and two of them - the cardboard roll and the candlestick - would benefit significantly from being able to look differently based on whether they have an item "inside" or not. A cardboard roll with duct tape should be able to look differently than an empty cardboard roll. Similarly, a candlestick could benefit from being able to have a candle inserted visually.

### Solution you would like.

Support for a way to have a container use different sprites when empty and when full

### Describe alternatives you have considered.

Bonus points if the sprites could vary between what's actually in the container so a roll of duct tape can look differently than a roll of toilet paper, but I'm not sure if that's even possible, let alone viable

### Additional context

I'm writing it down in the game repo as opposed to the tileset repo because to my understanding, the game needs support for that for the tilesets to be able to do anything with it in the first place. If I am wrong let me know and I will move this there

**Comment by GlordXd** [comment]
Thats a nice idea,but i think the tileset artists (in my case - ultica) are busy with making sprites for different stuff like rare/obscure monsters,items,tiles furniture and so on

**Comment by Karol1223** [comment]
> Thats a nice idea,but i think the tileset artists (in my case - ultica) are busy with making sprites for different stuff like rare/obscure monsters,items,tiles furniture and so on

This depends on the tilesets and what the artists choose to do. Giving artists more options is never a bad idea and they can only be busy with what they choose to be busy with as it's volunteer work, as is the entire project.

**Comment by GlordXd** [comment]
> > Thats a nice idea,but i think the tileset artists (in my case - ultica) are busy with making sprites for different stuff like rare/obscure monsters,items,tiles furniture and so on
> 
> This depends on the tilesets and what the artists choose to do. Giving artists more options is never a bad idea and they can only be busy with what they choose to be busy with as it's volunteer work, as is the entire project

I understand it,lemme rephrase my thought: From what I've seen so far the monsters and items get updated more often than anything else,and because of that i assumed that artists are "busy" with them because they're more important than the other stuff

**Comment by Golfavel** [comment]
I believe this is technically possible now with the the ``layering.json`` file, but it's not ideal.
