### ISSUE TITLE
Powder items should be treatet similar to liquid

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#67377]
### Is your feature request related to a problem? Please describe.

It's about charges being removed #60885

There is no reason to have powder treated as many individual items. Nor from game or realism point of view.

### Solution you would like.

Like liquids, powder 
- needs to be in container 
- can be counted in ml
- can be poured from container to container
- should get "dirty" when put directly on the ground

Unlike liquids, powder
- cannot be siphoned
- won't extinguish fire (in general)

Technically powder could use current liquid mechanics.

### Describe alternatives you have considered.

Bring back charges to powder

**Comment by mqrause** [comment]
> * should get "dirty" when put directly on the ground

I think in previous talks about this topic it was more or less established that powders should only partially get dirty when put on the ground. As in you can still pick parts of it up normally, but some will definitely be lost. In general I think powders are different enough from liquids to not treat them exactly the same.

But more importantly the charge removal is an ongoing process and more things will lose charges, quite possibly also liquids in the end (but far in the future if I'm the only one working on it). Turning powders into liquids would be a band aid for transitional issues at best. Definitely can be done if powder handling is just too problematic as it is, but as usual shouldn't distract from proper solutions.

**Comment by ampersand55** [comment]
The main problem (I presume) isn't related to the stack changes per se, but how clumsy it is to handle large stacks of items, and currently powders (and pills) are where it's most noticeable. 

I just tested it, and it takes 50 minutes of in-game time to drop 1000 units of sugar from a duffel bag. When you craft e.g. sugar, salt, spices or flour in batch you are easily dealing with stacks of several thousands that you need to move around.

A solution would be batch time saving from moving stacks of the same unit and whatever the performance issue is when you walk in range of large stacks of items.
