### ISSUE TITLE
NPC Paying for skills undervalued.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#6738]
From: https://github.com/CleverRaven/Cataclysm-DDA/issues/6294#issuecomment-37786282
When friendly NPCs offer to teach you skills in exchange for money, you can learn to get your mechanics skill up to level 2 for only $600, which is less than the price of basically anything you can find in a house.

**Comment by mugling** [comment]
Cost issues are largely resolved by #15382
