### ISSUE TITLE
Trying to stand on both broken legs is supposed to be painful, but it isn't

### ISSUE THREAD

**Issue by gvlasov** [CleverRaven/Cataclysm-DDA#67388]
### Describe the bug

When you try to stand on broken legs, you fall down to proning state, and it says:
https://github.com/CleverRaven/Cataclysm-DDA/blob/bdfc14ecc8bae5a0ed47a9f31fe6450d66b0e689/src/avatar_action.cpp#L175

But you don't actually get any pain from that. I think this is a bug.

### Attach save file

[Fulda-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12244539/Fulda-trimmed.tar.gz)

### Steps to reproduce

1. "
2. w
3. k
4. See log

### Expected behavior

Adding pain

### Screenshots
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/4467948/d0154d9c-d10a-48b7-9273-4f086b91cfcf)

\> fall down in pain
\> no pain

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: n/a; Description: Manjaro Linux; Release: n/a; Codename: n/a; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Love your game, guys <3

**Comment by alp7292** [comment]
it just to say that you cant stand up

**Comment by alp7292** [comment]
it there to remind you have broken legs feel free to change text to "you cant stand up with broken legs" if it breaks your immersion.
