### ISSUE TITLE
When hunger is "full", eating won't trigger warning but drinking does it.

### ISSUE THREAD

**Issue by rtxyd** [CleverRaven/Cataclysm-DDA#67391]
### Describe the bug

Only consuming food described as "You drink something" will trigger "You're full already and will be forcing you to ...", but I don't have traits about this. 
_To be honest, This is not a big problem._

### Attach save file

[Marine on Saint Croix-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12245179/Marine.on.Saint.Croix-trimmed.tar.gz)

### Steps to reproduce

1. Creat a blank character (better with "The Last Delivery" scenario). 
2. Drink or eat to full, and then *drink*, trigger warning, and then *eat* (not drink).

### Expected behavior

1. Eating trigger warning "You're full already and will be forcing you to ..." when you are "full" as drinking does.

### Screenshots

![20230803054705 mp4_20230803_060519](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/bf8326c5-5051-45a1-a582-a7169022df93)

### Versions and configuration

OS: Windows 10
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/bdfc14ecc8bae5a0ed47a9f31fe6450d66b0e689 [64-bit]
Graphics Version: Tiles
Game Language: 中文（天朝）
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
No Rail Stations [No_Rail_Stations]
]

**Comment by AzyWng** [comment]
I don't have footage or screenshots myself, but I've been experiencing something similar.

**Comment by ampersand55** [comment]
Same
