### ISSUE TITLE
Wall wiring and Wall light bug

### ISSUE THREAD

**Issue by TehJoker14780** [CleverRaven/Cataclysm-DDA#67402]
### Describe the bug

Wall wiring and wall lights can be stacked infinitely, leading to companions stacking the construction in one spot forever.

### Attach save file

N/A

### Steps to reproduce

Use the zone menu to place a blueprint for wall wiring or wall lights, have resources available, tell a companion to construct.

### Expected behavior

An insanely large stack of those furniture items in one spot that is a huge pain to remove...

### Screenshots

![cataclysm-tiles_F5PfaZwPhc](https://github.com/CleverRaven/Cataclysm-DDA/assets/140563926/05f1b94e-e11c-42f3-9b2f-855817862bcf)

### Versions and configuration

Latest experimental.

**Comment by GlordXd** [comment]
Tip: include the exact build of the game in the issues like this,cuz new experimental builds are released _very_ frequently,so the term "latest experimental" is not very accurate most of the time
