### ISSUE TITLE
Grappling hook cannot be removed from the top

### ISSUE THREAD

**Issue by 10asd28** [CleverRaven/Cataclysm-DDA#67420]
### Describe the bug

The grappling hook that allows you to climb down safely and also provides a way to climb up cannot be detached and recovered from the top point where it was deployed. This is in contrast to how it can be examined and recovered while at the bottom. This makes no sense considering it would be way harder to do the latter than the former IRL.

### Attach save file

N/A

### Steps to reproduce

-

### Expected behavior

I should be able to easily remove the grappling hook from the top by examining it and picking it up the same way I do from the bottom.

### Versions and configuration

Build: 2023-08-01-0917

**Comment by EvanBalster** [comment]
Wrote a PR #68317 that makes this possible for grappling hooks and stepladders.
