### ISSUE TITLE
drugs are ridiculously priced

### ISSUE THREAD

**Issue by irisanuwu** [CleverRaven/Cataclysm-DDA#67422]
### Describe the bug

the prices (barter prices) of drugs per single unit in the latest experimental:
aspirin - 5$ (50$)
codeine - 12$ (30$)
tramadol - 245$ (200$)
prescription sedative - 150$ (200$)
prescription stimulant - 145$ (15$)
and more

not sure if this warrants a bug report but given how crazy the prices are it leads me to believe that this is unintentional. 5$ per aspirin pill is kind of ridiculous in and of itself but the barter value completely breaks the economy given that a single aspirin pill holds as much worth as something like 10 firearms.

### Attach save file

N/A

### Steps to reproduce

open spawn item menu, look up drug items, see the strange prices

### Expected behavior

i expected the drug prices to be a bit more reasonable and not break the trading economy

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1848 (22H2)
- Game Version: 2823063 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by mqrause** [comment]
/confirmed

I did an oopsie with the charge removal, didn't realize prices were dependent on default charges.
