### ISSUE TITLE
yeast in a vat fermenting do not produce the correct amount of items

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67436]
### Describe the bug

title. growing wild yeast, after fermenting, produces 1 yeast. while its supposed to produce more than that.

### Attach save file

None

### Steps to reproduce

throw growing wild yeast in a vat, observe the resultant items are net-neutral in count

### Expected behavior

More yeast?

### Versions and configuration

OS: Windows
        OS Version: 10.0.19045.3208 (22H2)
    Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/c5ecac002fe2d539412b932737f517a270991d20 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Modified monsters and Weather [more_frequent_weather],
    Translate Complex Dialogue [translate_dialogue],
    Blaze Industries [blazeindustries]
    ]

**Comment by Brambor** [comment]
Again, I guess #67356, but I don't have time to check.
