### ISSUE TITLE
Trying to repair a hardened rapier, requires "chunks of mild steel" This is quite the problem

### ISSUE THREAD

**Issue by JestSomeone** [CleverRaven/Cataclysm-DDA#67431]
### Describe the bug

Go to repair the Hardened rapier, says it requires chunks of mild steel, however, the in game text says it requires "Case Hardened Carbon Steel." one of which were not a material that could be used to make the weapon, and both of them seem to be non craft-able.

### Attach save file

N/A

### Steps to reproduce

1. Try to repair a hardened rapier
2. Realize that you cant
3. Spend an hour being very confused

### Expected behavior

I expected that it would have required lumps of mild steel, something that I am able to make, but not chunks. Alternatively, an implementation of chunks of steel and a fix to the text to match what is being used would work too. 

### Screenshots

![Screenshot 2023-08-04 005540](https://github.com/CleverRaven/Cataclysm-DDA/assets/138320279/e39a0abd-01df-4425-8333-51de12b48efc)
![Screenshot 2023-08-04 005638](https://github.com/CleverRaven/Cataclysm-DDA/assets/138320279/321207a7-14a2-40e5-b829-43e4ca405441)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: a0691e5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by ampersand55** [comment]
It's just a display bug. 

You can make chunks of mild steel by disassembling lumps of mild steel which you can craft or buy.

**Comment by JestSomeone** [comment]
WELL... I wish there wasn't 3 different crafting menus in this game, one of which you cant search through and have to have the item before hand.
