### ISSUE TITLE
(Typo/bug report) Inconsistency with the names of the locations in scenarios and ingame

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67444]
### Describe the bug

Theres a scenario called "Safe Place" that has 10 options of starting locations,one of which is the "hermit shack",when chosen and loaded in,turns out to be called "swamp shack" ingame. 

### Attach save file

N/A

### Steps to reproduce

1) create a world and a character
2) choose the "Safe Place" scenario,and choose the "hermit shack" option
3) load in the world and see that they have mismatching names

### Expected behavior

Names to be identical 

### Screenshots

![Screenshot_20230804_190301](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/cd6e6f15-7cc1-4210-9cd3-62e55e9c8b3d)
![Screenshot_20230804_190408](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/4c7ab311-fdf9-41bf-90ae-c3d117780b55)

### Versions and configuration

Language: English
Other information is irrelevant 

### Additional context

![Screenshot_20230804_190422](https://github.com/CleverRaven/Cataclysm-DDA/assets/138254662/d0bff564-d54a-4280-ac3c-91eaf5de2dfe)

Also got this reaaal smol town next to me,on default world settings (unrelated)

**Comment by ZhilkinSerg** [comment]
Normally these names can differ as any starting location can include multiple overmap terrains with different names, so starting location name would be something that describes each and any of the included overmap terrains.

**Comment by GlordXd** [comment]
> Normally these names can differ as any starting location can include multiple overmap terrains with different names, so starting location name would be something that describes each and any of the included overmap terrains.

Meh,its still feels a bit wrong,even though it seems to make sense
