### ISSUE TITLE
[Sky Island] Stat Stone doesn't give most of the stats

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#67445]
### Describe the bug

When activating the Stat Stone, it does not give me any stat except the Missions Completed one somehow.

### Attach save file

[Swinomish Village-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12262587/Swinomish.Village-trimmed.tar.gz)

### Steps to reproduce

1. Open the attached save,
2. Activate the Stat Stone,
3. Barely any stats given.

### Expected behavior

Having the stats shown to me.

### Screenshots

![Screenshot_20230804-230916](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/8d6b8d3a-1ac9-4769-a4fb-ee6e08542af3)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 6c7384d [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Sky Island [skyisland],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Xedra Evolved [xedra_evolved]
]

**Comment by GuardianDll** [comment]
It's because the game can't show custom variables in this way

**Comment by TGWeaver** [comment]
> It's because the game can't show custom variables in this way

What do you mean "in this way"? There's several custom variables in that screenshot alone that are working fine. "Missions complete" and the numbers for pulses are custom.
Also, the code definitely worked when I first wrote it (evidenced by attached screenshot), so unless functionality was removed, something must've changed along the way. I can only confirm that it was working in the initial pre-0.G version; the break could've happened any time after that.
![stat stone](https://github.com/CleverRaven/Cataclysm-DDA/assets/45330325/8305acf2-6b4a-472d-b8d1-b393a652817f)

One thing I will point out is that those fields might be blank until initialized, but I tried to work that code into the scenario initializing code. Either way, if you've completed 5 missions I assume you've been on a handful of raids already and thus they should definitely be filled in.

**Comment by GuardianDll** [comment]
Okay, my second thought now is when i mathified all stuff in mod, all values, that previously was `u_val`, was transformed into global variables, so `<u_val:raidstotal>` can't show it anymore, and `<g_val:raidstotal>` is not a thing yet
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/1fac44cd-23ac-42ab-bea4-7324b388c082)

**Comment by andrei8l** [comment]
> and `<g_val:raidstotal>` is not a thing yet

It should be `<global_val:raidstotal>`. I should probably standarise that to the math syntax so it's look like `<var:raidstotal>` or `<var:u_raidstotal>` or `<var:_raidstotal>`. What do you think?

**Comment by GuardianDll** [comment]
With `u_val` which exist already, I'd stick with `g_var`, but simple `<var:raidstotal>` shoud work also
