### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by reusityback** [CleverRaven/Cataclysm-DDA#67443]
### Describe the bug

After passing some random time in-game, I get this error message, when the game crashes: cataclysm-dda terminated by signal SIGSEGV.

### Attach save file

[2023-07-30-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12262372/2023-07-30-trimmed.tar.gz)

### Steps to reproduce

Play the game.
After a quicksave: Crash.

Sorry, I don't know debugging well.

### Expected behavior

Not crash.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 8964fd7 [64-bit]
- Graphics Version: Tiles
- Game Language: Systemsprache []
- Mods loaded: [
    Dark Days Ahead [dda],
    NPC-Bedürfnisse deaktivieren [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

WARNING : recipe_subset deserialized invalid recipe_id 'null'

**Comment by ZhilkinSerg** [comment]
Could not reproduce it on a latest version trying to wait for hours. How much time have passed on your PC before the crash?
