### ISSUE TITLE
Surrounded in the Dark scenario puts you at a date different than it says in the description.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67450]
### Describe the bug

The Surrounded in the Dark scenario is described as starting at Year 1, Spring, Day 0, Hour 1, or 1 hour after midnight on January 1'st. There's two problems, a small one and a big one: The small: When you start the game, it puts you on Spring, Day 1. The Big: When you complete an achievement it tells you the year as well as the month, and that makes clear that you're actually on **Year 2**, Spring, Day 1.

### Attach save file

N/A

### Steps to reproduce

Start a game with that scenario, check the date.

### Expected behavior

With the difference between Day 0 & Day 1, I'd expect that the scenario description should be updated. With the difference in year, the starting date should be updated to be actually Year 1, 60 days before things really kick off. 

But this scenario is in a weird spot. With the addition of panicked people and other non-zombie things around on the regular start date, I'm really not sure how this start should be playing out mechanically. Regular NPCs that convert to the panicky ones when a zombie shows up? Remove this scenario? I dunno.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 6c7384d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by ZhilkinSerg** [comment]
Calendar information displayed in character creation screen:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/bb0a9ba7-385a-42e3-9403-cc1740189c5b)

Is consistent with what is displayed in the debug menu:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/c28b6167-2fe7-45e1-aefd-e54f68d4c3c7)

However other menus in-game are beg to differ:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/543b41b2-c4ea-4bf2-9c4a-64b837691e38)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/a81111dd-a72e-4902-a480-d63340c3433c)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/b88c20bf-683b-4356-a455-2b2ef29436d1)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/a72ebbf2-24dc-4612-87c9-154a1d7a6c64)

***

This is what you see in a scenario that does not mess with start date/time:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/c154b4ec-f126-4585-a6ac-02a70420f51c)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/4d9c255e-ec48-4b3b-9a92-0b8f8938091e)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/54f32a71-016c-4f4b-9aa3-010f040f8775)

***

It seems there are two issues here:

- game day is displayed incorrectly in debug menu OR in non-debug game UI;
- scenario custom date advances calendar more than displayed.

**Comment by Vaskritaya** [comment]
it seems that the the scenario selection screen display dates as zero-indexed, like in debug. Since they're player-facing, they really should be displayed in a more natural and intuitive way instead.

That being said, this scenario really looks like the time is an oversight, and it should be year 1 (or 0, internally), day 60 (of the year), hour 1 (just past midnight, as currently). The actual scenario only specifies a custom hour, so the rest must be getting automatically populated somewhere.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22992007/2aebeaa9-02a6-4f23-a548-b0997f7b7819)
