### ISSUE TITLE
Truncated Advanced Inventory Description Color Tag

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#67456]
### Describe the bug

Some descriptions in a pane show strange values, like `small cardboard box+ > <color_c_li` in this case.

### Attach save file

N/A

### Steps to reproduce

1. Grab one of those `small cardboard box+` containing bandages
2. Open AIM with `/`
3. Enter the container with `c`

### Expected behavior

The truncated description should not show tags.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/3899581/de84a699-41ff-4eef-9cab-0affc17a403c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 871476b113 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]

### Additional context

The bug happens at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/advanced_inv.cpp#L798 .
Here, `utf8_truncate` cuts the description text including half color tag.
From VS debugging seesion:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/3899581/2be6aee0-2cb1-4e69-9843-6caf2a13b66c)

**Comment by casswedson** [comment]
I don't see any rush to remove the 'need confirmation' label from your bug report
