### ISSUE TITLE
Component **** can't be evenly distributed to resulting items

### ISSUE THREAD

**Issue by new02DAY** [CleverRaven/Cataclysm-DDA#67454]
### Describe the bug

Getting the error "Component threshed_buckwheat can't be evenly distributed to resulting items" when trying to craft buckwheat (and purged gastropods). Might affect other recipes, too, but I've only tried the two.

EDIT: Also ran into this issue with grinding barley into flour.

*Please ignore Player_Mod, just a test/dummy mod folder

### Attach save file

[Dark Days Ahead-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12266021/Dark.Days.Ahead-trimmed.tar.gz)

### Steps to reproduce

1. Load save.
2. Try to craft buckwheat using threshed buckwheat.
3. Error.
4. Ignore error, chaff is created, but buckwheat is not.

### Expected behavior

No error, complete recipe properly

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56372745/b390885a-318b-4908-8df7-57d96f01d612)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 9463676 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Player Mod [Player_Mod]
]

**Comment by MrHrulgin** [comment]
I had the same experience turning a sunflower into sunflower seeds.

**Comment by FinWeirdoh** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/67064 I had the same issue earlier with fries but lately this error seems to have spread to more recipies

**Comment by rtxyd** [comment]
I remember that, some time before rotten food and fresh food will be automatically separated by the game, but this time same type of food stay together untill you consume them to only rotten ones left. May be the culprit.

**Comment by fairyarmadillo** [comment]
Likely another victim of the removal of charges on solid comestibles. The recipes formerly relied on the items having charges and now that they don't the numbers aren't lining up.

I am dealing with a health issue but hopefully in a couple of days I can come fix this.

**Comment by mqrause** [comment]
It's most likely an error in the item component logic, so not completely fixable with json. I'll take a look. But some recipes might need adjustments anyway.
