### ISSUE TITLE
Lightweight containers are prioritized for storage, obscuring contents

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67468]
### Describe the bug

If I raid a vending machine and buy 2 bags of chocolate candy, and look in my inventory I'll end up with an item that says "plastic bag > 4 hidden items". If I open that bag, there's 3 candies, and then the second bag. For some reason, the default storage behavior is to put one of the bags of chocolate candy inside the other one, and so rather than having two plastic bags which describe their contents and show up categorized as Food, I have a single one that doesn't show what it is and is categorized as a Container. This is inconvenient both for manual sorting and for Zone sorting. The same issue arises with many things that are stored in plastic bags, paper wrappers, pretty much any container that can contain others of its type.

### Attach save file

N/A

### Steps to reproduce

Pick up multiple plastic bags containing the same material, see how they nest. 

### Expected behavior

There's two ways this could go: 

1. Either stop nesting bags inside each other like that.
2. Ignore interior bags for the purposes of categorization, so that a plastic bag that only contained food and other plastic bags would fall under the Food category and be named as containing that foodstuff.

Either one would make inventory management much easier.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/c1911252-4649-4c4e-8518-ee15d66ae947)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/d7a4c555-a105-400c-90d9-1986a9a83d26)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/0acbf354-1733-4dac-a04d-b15b5fbd3e22)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 1dbf29a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by MrHrulgin** [comment]
There's an additional oddity. If you take out the original item such that all that's in the plastic bag is plastic bags containing a single type of item, it'll change to calling it "plastic bag > plastic bags", and will change to being in the right category. It's a half step in the right direction. Easier to auto-sort, but still visually ambiguous. 

Without any pads in the top plastic bag (in the Other category)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/8af714f6-55df-4ca1-9f7f-ca52e95a89ab)

With a pad in the top plastic bag (in the Containers category.)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/ab6cd224-b0cb-4a3c-9089-be5fefcb26e7)

**Comment by andrei8l** [comment]
The whitelist for `chocolate candy` accepts any container with only chocolate candies as well. That part is [intentional](https://github.com/CleverRaven/Cataclysm-DDA/blob/383e125594ba442751c94176c948d6501398a274/src/item_pocket.cpp#L2493-L2500).

**Comment by MrHrulgin** [comment]
That makes some sense, but it would be prefer to consolidate the contents (resulting in one empty bag and one with the contents, which would take advantage of the current structure for displaying a container's contents) or fix the display such that secondary containers aren't listed.
