### ISSUE TITLE
om_match_type doesn't work as it should for LINEAR maps

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67469]
### Is your feature request related to a problem? Please describe.

According to this
https://github.com/CleverRaven/Cataclysm-DDA/blob/6fcee48bd897129b0c3bc0793fa3a53064ee4213/src/enums.h#L125-L133
"TYPE" should be able to ignore rotation explicitly for LINEAR maps except unless I'm dumb there's no way to do it because it doesn't recognise road_straight/road_curved etc only resolved oms like road_ns/road_ne etc meaning to check for any road_curved you have to do this
```
"south_west": [
  { "om_terrain": "road_ne", "om_terrain_match_type": "EXACT" },
  { "om_terrain": "road_es", "om_terrain_match_type": "EXACT" },
  { "om_terrain": "road_sw", "om_terrain_match_type": "EXACT" },
  { "om_terrain": "road_wn", "om_terrain_match_type": "EXACT" }
]
```

### Solution you would like.

To be able to either do something like this
```
"south_west": [
  { "om_terrain": "road_curved", "om_terrain_match_type": "TYPE" },
]
```
or anything else that shortens simple checks like that

**Comment by Maleclypse** [comment]
Closed as completed per Procyonae
