### ISSUE TITLE
New character trait and new "sweet_food" flag

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67478]
### Is your feature request related to a problem? Please describe.

When you eat sweet food ingame (like soda or ice cream) while hungry or really hungry, nothing unusual happens, which is not very realistic.

When you eat sweet food irl (again,while being hungry), you get "belly pain" which can lead to headaches and vomiting in some cases.

### Solution you would like.

Add a new flag for food,maybe something like "sweet_food" which will determine the said food.

Add a new trait that will ignore the "belly pain" mechanic and would provide additional morale points when eating sweet food (sweet tooth?)

### Describe alternatives you have considered.

1) Do nothing. Its just one of my ideas that seem ok compared to the rest.

2) Ignore the "belly pain" mechanic and just add the "sweet_food" flag and the trait described above (and some sort of counter-trait which will be the opposite (sore tooth?))

**Comment by ZhilkinSerg** [comment]
I am not aware of such effect in real life.

**Comment by GlordXd** [comment]
I did additional research,and i can say: ignore the "belly pain" mechanic,it would probably be too complicated to be worth implementing (some sweet food is good while you hungry,some is bad,some is really bad and so on) 

Consider the new trait instead,i know that it looks like a worse Gourmand trait,but still,we have some specific traits about food already,why not add this one

**Comment by PatrikLundell** [comment]
Neither am I, apart from the danger of a blood sugar spike in people with diabetes. I'm not saying such reactions do not exist (due to lack of knowledge), but it certainly doesn't apply to the vast majority of people.

It can also be noted that there is already a "junk food" flag applied to sweet stuff (I'm not sure if it is also applied to ultra processed food as well), and the game considers junk food to be incredibly dangerous and thus penalizes any eater of it with a health penalty slap.

**Comment by GlordXd** [comment]
> Neither am I, apart from the danger of a blood sugar spike in people with diabetes. I'm not saying such reactions do not exist (due to lack of knowledge), but it certainly doesn't apply to the vast majority of people.
> 
> It can also be noted that there is already a "junk food" flag applied to sweet stuff (I'm not sure if it is also applied to ultra processed food as well), and the game considers junk food to be incredibly dangerous and thus penalizes any eater of it with a health penalty slap.

So basically the game already got everything i suggested,but not in a way that i described..Alright then, I'll close this
