### ISSUE TITLE
NPCs planting Null crop on bases

### ISSUE THREAD

**Issue by JoaoMagal** [CleverRaven/Cataclysm-DDA#67471]
### Describe the bug

Don't exactly know what is triggering it, but NPCs are inconsistently (but frequently) planting null crops.
The seeds trying to be planted are available in the base storage zones.

### Attach save file

[CataRPG-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12268431/CataRPG-trimmed.tar.gz)

### Steps to reproduce

1. Start game and load the provided save file (only one character in the world).
2. Wait a couple of turns for the npcs to plant a few crops.
3. By a few crops, one of the crops planted should be null;
4. Confirm the planted crop's name via look around (x hotkey); This should trigger the exception, and the "Null" name for the crop on the UI.

### Expected behavior

The NPC should plant the correct crop, according to the zone selected and the seeds available in the base storage zones.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/27467821/38178667-59c5-40e2-a0c4-0b78708371e2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: 87af942 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12268433/debug.log)

**Comment by fairyarmadillo** [comment]
Are they doing thia with seeds of all kinds, or is it only specific seeds? If it's the latter, do those types of seeds always result in null?

**Comment by JoaoMagal** [comment]
Confirmed - this is still happening on the latest experimental.
Seems like it should be the issue I mentioned: He starts planting, even though he has no seeds available for planting, probably because another NPC has already planted the seed he is trying to plant. However, I could be wrong, so further testing should be made.

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 3efd67a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]


**Screenshots:**
The crop in question:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/27467821/f0bcfe5e-7fb5-4e10-bc44-0247909bb811)

The NPC in question:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/27467821/b3be6949-4518-4a19-bfae-f870f6ced9ea)

Message logs while the glitch happened:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/27467821/562cb929-6331-4de7-b0b7-c04ef8b6d5ec)

**Comment by fairyarmadillo** [comment]
I looked into it and this is happening because the c++ stuff for NPCs farming is all coded to use charges for seeds and crops. So someone would need to go through all of that.
