### ISSUE TITLE
Ability to call EoC for professions/hobbies

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#67480]
### Is your feature request related to a problem? Please describe.

Because sometimes you should perform an action, that can't be handled by hobby syntax

Use cases: altering some specific variables for profs, giving special treatment, potential unhardcoding martial arts hobbies using selector 

### Solution you would like.

Ability to call EoC on the start of the game, if scenario is picked

### Describe alternatives you have considered.

Using dirty tricks

**Comment by ZhilkinSerg** [comment]
> Ability to call EoC on the start of the game, if scenario is picked

It should be already supported (see https://github.com/CleverRaven/Cataclysm-DDA/pull/50934).

**Comment by ZhilkinSerg** [comment]
One thing that might be missing is ability to freely check avatar profession and hobbies ids in any of the eocs. This function should be relatively easy to add. And for the start there is `game_avatar_new` event that can be used to access avatar profession - https://github.com/CleverRaven/Cataclysm-DDA/blob/383e125594ba442751c94176c948d6501398a274/doc/EFFECT_ON_CONDITION.md?plain=1#L137.
