### ISSUE TITLE
Long term idea about NPCs

### ISSUE THREAD

**Issue by GlordXd** [CleverRaven/Cataclysm-DDA#67485]
### Is your feature request related to a problem? Please describe.

The world of CDDA is quite gruesome and violent (even the hulk tea-parties been violent lately) but theres something about NPCs (especially hostile ones) that lack this,so I've got an long-term idea

### Solution you would like.

Add "wandering/scout/dealers npcs" to the game,who would traverse the terrain,often on relatively same path,those npcs (hostile or not) will be catchable (you will be able to imprison them) and possibly torture them to get info from them (like the location of their base,loot cache, locations of globally unique locations and so on).

There would be a lot of methods of torturing the prisoners (which will NOT be affected by the gender of the prisoner) 

There also would be a method to convince the prisoner (mainly when the prisoner was initially friendly of neutral before he got captured) so you can be a good guy and do not inflict suffering to others.

The methods of imprisonment would also wary, something of the following: shooting target in the leg; ambushing it at night; setting up some traps (bear traps preferably); using that rope that cowboys used to catch animals and outlaws (idk what its called in English); tasering the target; hitting it real hard until it cant no longer resist etc.

The "psychopath"/"serial killer" trait would have its own unique methods of torture and would give player a morale boost when performing them.

A few unique lab-related items for torture would also be present,like the "psi helmet" which would be found in a box (or some sort of container) with a manual to it,upon reading and learning about it,the player would learn that this helmet was an failed attempt to create a way to control portals with the power of brain waves,the helmet would actually do something (one) of the following:

1) "fry" the brain of the wearer,causing extreme pain,and killing the said wearer if applied for too long.

2) making the wearer very cooperative, allowing to get any info from them, without harming them.

3) when equipped by the player,will grant the player ability to control other humans on psychical level (not the ferals humans tho,their brains are dead,for the most part)

### Describe alternatives you have considered.

Do nothing.

### Additional context

This is a long-term idea,it should not be implemented in like a month,the devs are busy with more important stuff and i understand it.

I've been thinking about this idea for a while,and because of it theres a lot of text,to me it seems like it would fit the CDDA universe well,but thats my opinion,i gotta hear the opinion of other people.

(Even though im not really good with this "suggestion" stuff,like they say "The more and harder we try,the more chances to succeed we will have")

Edit: apparently the whole "torture" thing is not possible (in cdda) for number of reasons,so this whole suggestion can be summarised (without torture) as:

 Travelling npcs that can be captured and threatened/convinced into giving player some sort of valuable info that reveals stuff like loot staches, unique (sometimes global) locations,bases/camps from which captured npcs originate (like hell's raider would reveal the location of their base and such)

**Comment by fairyarmadillo** [comment]
Nobody is going to code any torture content into the game and if they tried it wouldn't get merged.

**Comment by GlordXd** [comment]
> Nobody is going to code any torture content into the game and if they tried it wouldn't get merged.

Well,it was worth trying,maybe if the part about torture will get cut,the other stuff might go through,like the part about traveling npcs, capturing them and getting valuable info from them... without torture,maybe just threaten or convince them,like the player is able to do with regular npcs.

**Comment by estebandellasilva** [comment]
> Nobody is going to code any torture content into the game and if they tried it wouldn't get merged.

No Offense ... but seeing the warcrimes that have been commited in rimworld i doubt das you wont find a guy to programm torture ... not saying anything about the merging but ... people can get creative in many ways

**Comment by GlordXd** [comment]
Well,i should've expected a result like this :D

**Comment by Zireael07** [comment]
I missed the part about torture, tbh. I like the part about wandering NPCs giving you info about the world.

**Comment by GlordXd** [comment]
> I missed the part about torture, tbh. I like the part about wandering NPCs giving you info about the world.

I dont think that even the idea about wandering NPCs will be noticed seeing how this got closed as "Invalid"

**Comment by Zireael07** [comment]
@GlordXd probably a good idea to make a new issue sans the torture part
