### ISSUE TITLE
weird lighting bug (with eternal night)

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67481]
### Describe the bug

Use the save, zoom out, light magically create itself in a wide area and disappears

(ignore the error related to profession)

### Attach save file

[Covenant-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12269245/Covenant-trimmed.tar.gz)

### Steps to reproduce

1.Go one step north
2.Observe light manifesting
3.Go one step south
4.Observe light going away

### Expected behavior

for light to not exist without a light emitter

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 383e125 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by ZhilkinSerg** [comment]
There is some work light switched on

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/010069d3-871c-49c9-8d65-2a92b605a707)

**Comment by ZhilkinSerg** [comment]
This is how the game works.
