### ISSUE TITLE
Inventory selector moves at random

### ISSUE THREAD

**Issue by ImperatorTitanius** [CleverRaven/Cataclysm-DDA#67495]
### Describe the bug

When moving through my inventory, interacting with an item and moving back out via ESC will move the selector cursor at random.

### Attach save file

[Pico Rivera-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12270901/Pico.Rivera-trimmed.tar.gz)

### Steps to reproduce

1. Start new random save and fill inventory with items via debug menu.
2. Spam interact/escape on items and cursor moves at random, not staying on original item.

### Expected behavior

The cursor should stay on the original item.

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/124532767/00c21485-acfb-4854-925c-11c7c37b2438

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 28a3f40 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

This issue has already been reported on in https://github.com/CleverRaven/Cataclysm-DDA/issues/65241, but was marked as stale and ignored.

**Comment by GlordXd** [comment]
I have this problem as well,and i think theres a few issues like this,maybe devs just dont see fixing it as urgent at the moment.
