### ISSUE TITLE
Solar panel technology has evolved a lot since solar panels were first implemented into the game and it's in need of an update.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67498]
### Is your feature request related to a problem? Please describe.

Solar panel technology has evolved a lot since solar panels were first implemented into the game and I think it's time for an update, especially since the recent increased power cost to use many electric appliances. See e.g. #67433. 

### Solution you would like.

Modern solar panels for home use are rated at up to 400W, which is 8 times that of regular solar panels and 4 times that of advanced solar panels in game. Advanced solar panels in the game is described as monocrystalline panels, but that's just the standard now as opposed to older polycrystalline solar panels.

As there's an increased power cost to use many electric appliances now I believe this is a welcome change.

300 W solar panels are about 36 inches by 65 inches= 2340 in^2 / 1.5 m^2, weigh 10 lbs / 4.5 kg (aluminum frame) and 1.5 inches thick, volume = 65 * 36* 1.5 = 3510 in^3 / 57.5 liters. If tilted at a recommended 40 degree angle the ground cross section would be sin 40 * 65 * 36 = 41.7 x 36 = 1504 in^2 or 0.97 m^2.

https://www.ecowatch.com/solar/300-watt-solar-panels

400 W solar panels are about 45 inches by 75 inches = 3375 in^2 / 2.1 m^2 and weigh 45 lbs / 20 kg (steel frame) and 1.5 inches thick, volume = 75 * 40 * 1.5 = 4500 in^3 / 81 liters. If tilted at a recommended 40 degree angle the ground cross section would be sin 40 * 75* 40 = 48.2 x 45= 2169 in^2 or 1.4 m^2.

https://www.ecowatch.com/solar/400-watt-solar-panels

I propose we increase the output of solar panels by a factor of 3 or 4 across the board.

Table of proposed changes:

| Quantity | Current (50W/100W) | Modern 300 W | Modern 400 W |
|---|---|---|---|
| Weight | 14 kg |  4.5 kg | 20 kg |
| Volume |3 L | 57.5 L | 81 L |
| Longest side | 16 cm | 65 cm | 75 cm |
| Ground cross section|  N/A | 0.97 m^2 | 1.4 m^2 |

I also propose we update the name of advanced solar panel to "modern solar panel".

### Describe alternatives you have considered.

Another option is to make the regular solar cells monocrystalline cells and the advanced solar cells perovskite-on-silicon tandem cells, an emerging cutting-edge new solar technology which is expected to be available for market in 2025. Those can capture 30% of solar energy instead of the 20% of modern monocrystalline cells. This would fit the loot categories better, I think.

* https://en.wikipedia.org/wiki/Perovskite_solar_cell
* https://en.wikipedia.org/wiki/Solar-cell_efficiency#/media/File:NREL_PV_Cell_Record_Efficiency_Chart.png
* https://cosmosmagazine.com/technology/materials/perovskite-set-to-transform-solar-generated-electricity/

### Additional context

If it's just json-edits I could make the PR, I just thought I'd get some input/review first.

**Comment by MrHrulgin** [comment]
Not that I'm anyone special, but I can appreciate a change that both helps game balance and matches real world numbers.

**Comment by Profugo-Barbatus** [comment]
I'm all in for there being solar panels that match IRL performance. That being said, Solar Cars present a problem. I wouldn't consider this to be a blocker to modernization, but perhaps these should be a separate non-vehicle line from the existing ones, since they are such a significant deviation in size and output. Or maybe its time for Solar Cars to just be retired entirely - I'm not aware of any solar powered vehicles IRL that aren't single-purpose custom built competition vehicles. As they exist currently, upgrading the panels would make Solar cars even more powerful. Now that CDDA is IRL plus a bit, it makes sense to axe them.

**Comment by ampersand55** [comment]
I don't know why the "Solar Car" is one of the most common vehicles in the highway and parking lot spawn groups. It should probably only be in the cs_car_showroom. 

From the idem id we can conclude the solar car is supposed to be a Toyota RaRa X. which debuted in Solar Car Rally In Noto, Japan in 1992. A total of 8 such cars were built.

12V solar panels for vehicles seem to be mostly sold in multiples of 100 W panels, where the largest single 12V solar panels I've found is [200 W](https://richsolar.com/products/200-watt-solar-panel). 

Perhaps we should just have two types of solar panels:

1. regular solar panels (400W) which can only be installed as appliances 
2. 12V (vehicle) solar panels (200W) which can be installed in vehicles and as appliances. 

And possibly re-introduce advanced solar panels once we know a bit more about commercially available perovskite-on-silicon tandem panels,

**Comment by PatrikLundell** [comment]
I like the notion of a separation between vehicle part solar panels and construction only solar panels (while adjusting the performances to approximate the real world one).

I wouldn't mind re-branding the regular solar panels as old solar panels and the advanced ones as regular ones (while still adjusting the power production).

I would suggest a retention of two different kinds of vehicle solar panels, with the normal one being the supplemental energy one you might find on some cars and camper vans, and perskovite like ones for the dedicated ultra light vehicles that aren't present in the real world apart from for attendance in solar vehicle races (and probably aren't street legal), bug given that portal magic is supposed to have advanced some fields of technology faster than in the real world I think it's reasonable to retain these vehicles as rare valuable loot.

**Comment by Alm999** [comment]
When I *tried* to fix adjustable solar panels with this https://github.com/CleverRaven/Cataclysm-DDA/pull/66478 my alternative idea was to make dedicated non-vehicle "stationary solar panels" with 400-500W output (to be placed on rooftops). Thus, we can keep vehicle-mountable panels with 12 solar cells (probably, adjusting their weight, as 14 kg for meager 50W *is* ridiculous) and a "stationary solar panel" would have 96 solar cells (or 8 x solar panel).

Also, I still consider "foldable" solar arrays losing 33% of output for no particular reason (other that "Quick google shows…") considering in-game we **make** adjustable solar arrays from regular ones, not find them as-is, to not be justified.

**Comment by Alm999** [comment]
Here, I've made a draft PR based on the findings: https://github.com/CleverRaven/Cataclysm-DDA/pull/67508

**Comment by Alm999** [comment]
Some tests are failing now. Apparently, vehicles are not expected to be that efficient (an "Electric Car" with 4 x "solar panel" recharges now four times faster and can travel a lot more than is being expected). Perhaps, a car re-balance is in order. For Electric Car I'd like to have only 2 (symmetry!) panels, but on the roof (above the rear seats), not on the sides. Luxury RVs can also get some love (they are "houses on the wheels"): afterwards, perhaps increasing the count and replacing them to the roof ( https://battlebornbatteries.com/rv-solar-panels-guide/ ) is in order.

**Comment by ampersand55** [comment]
> Some tests are failing now. Apparently, vehicles are not expected to be that efficient (an "Electric Car" with 4 x "solar panel" recharges now four times faster and can travel a lot more than is being expected). Perhaps, a car re-balance is in order. For Electric Car I'd like to have only 2 (symmetry!) panels, but on the roof (above the rear seats), not on the sides. Luxury RVs can also get some love (they are "houses on the wheels" after all): perhaps increasing the count and replacing them to the roof ( https://battlebornbatteries.com/rv-solar-panels-guide/ ) is in order.

Electric cars shouldn't have solar panels at all. I've never seen an electric car with solar panels. Perhaps they could spawn with some foldable deployable solar panels in the trunk, but otherwise they should be retired imho.

The only vehicles that should have solar panels are RV's, and the 4 solar panels they already have could be upgraded to 200 W versions as 800 W doesn't seem unreasonable. 

> In general, you need 300 watts of solar panel power to every 100 Amp Hours of battery storage capacity on your RV. So, if you have two 12-volts or any combination of batteries that equals between 200 to 250 AH, your solar panel output should be no less than 600 watts. Further expounding – for larger RVs with more batteries, like 5th Wheels and Class B motorhomes with between 400-600 AH battery capacity, you should have at least 1,200 watts of solar panel power on your RV.  

https://www.alliancerv.com/blog/how-make-your-rv-solar-and-how-many-panels-does-your-rv-need

Btw, thanks for making the PR!

**Comment by Profugo-Barbatus** [comment]
> but given that portal magic is supposed to have advanced some fields of technology faster than in the real world I think it's reasonable to retain these vehicles as rare valuable loot.

Even if we assumed that they discovered some 100% efficient means by which to make solar panels via portal tech, they wouldn't have gotten so far as to integrate that into consumer vehicles as thats roughly a three to five year development cycle assuming all the parts are already available in widespread manufacturing - Or even thought about using it in vehicles, to be honest. If you have a super efficient solar technology, the answer is to use it to make self sustaining charging stations absolutely everywhere, not slap them onto the roof of cars that'll probably be in a garage for significant portions of their life.

Depending on your location, a 100w panel recharges the battery in a Tesla in ~8-12 months (Assuming average weather, average efficiency, always outside etc). That gets you 100 miles or so of driving. If you replaced that panel with a physically comparable futuretech substitute with 5x yield (near 100% efficiency at that point) you're still spending a month or so sitting outside to top off for a hundred mile trip. Still sounds like it'd be a waste of rare portal tech to use it like that. And as the majority of advanced tech in the lore seemingly comes from a captured plutonium fuel cell powered object that was otherwise just 1990's level tech, it wouldn't explain super solar cells.

The whole thing just doesn't make sense in any real world, regardless of the fundamentals underlying it. Cars just use too much energy.

**Comment by Alm999** [comment]
> Electric cars shouldn't have solar panels at all. I've never seen an electric car with solar panels. Perhaps they could spawn with some foldable deployable solar panels in the trunk, but otherwise they should be retired imho.

Yes, you are quite right. But we don't have electric recharging stations for electric cars in the game right now, so without built-in solar panels those Electric Cars will become quite useless (at least until player finds a solar farm or builds his/her own). I believe having solar panels in "Electric Cars" was a temporary solution.

**Comment by Alm999** [comment]
> Depending on your location, a 100w panel recharges the battery in a Tesla in ~8-12 months (Assuming average weather, average efficiency, always outside etc). That gets you 100 miles or so of driving. If you replaced that panel with a physically comparable futuretech substitute with 5x yield (near 100% efficiency at that point) you're still spending a month or so sitting outside to top off for a hundred mile trip. Still sounds like it'd be a waste of rare portal tech to use it like that. And as the majority of advanced tech in the lore seemingly comes from a captured plutonium fuel cell powered object that was otherwise just 1990's level tech, it wouldn't explain super solar cells.

A Tesla is not a good example of the electric propulsion. It is first and foremost a luxury toy, needlessly heavy and stuffed with auxiliary gadgets. IMHO, the "Solar Car" represents reality much more adequately.
https://electrek.co/2021/10/19/this-solar-powered-electric-bicycle-is-making-a-6500-mile-loop-around-us/
https://thesunpedalride.com/2021/04/16/the-sunpedal-ride-india-2019-on-a-solar-electric-tuk-tuk/
https://www.dbusiness.com/hustle-and-muscle-articles/university-of-michigan-unveils-solar-car-powered-by-amprius-batteries/

The catch is: those extra-large batteries are **heavy** and you need your "Solar Car" to be as light as possible, so only bare minimum mass with just a small battery is needed (no, you won't be driving at night or for 24 hours straight): a battery is needed only to assist in a cloudy day.

**Comment by Profugo-Barbatus** [comment]
I use the Tesla as one of the few all electric cars that's actually in widespread use in the region. The Tuk-Tuk and solar sled all fail that criteria, you'd find none of those floating around New England. A solar bike you might find just by virtue of anybody with a thousand bucks could rig it up so it doesn't need to be sensible, just interesting - But that's vastly different from the thirteen paneled beast we have in game.

If someone wants to build an aluminum racing sled with solar panels, we've got the vehicle crafting system. I'm talking about vehicles that you'll actually find in quantities that justify them spawning in the random cars we find, which is how solar vehicles are found currently. The Solar car doesn't represent reality, and should get axed.

**Comment by PatrikLundell** [comment]
I believe there are actually cars available or as concepts with solar panels on them, although I agree I fail to see the usefulness of it apart from as a gimmick.

From my perspective the work around for the lack (and non function) of charging stations is to have battery swapping bays, something that's been proposed but never taken off in the real world (it may be used in limited situations, such as warehouse based fork lifts).

When I suggested portal hand waving as a way to improve solar panels I wasn't suggesting 100%, just the acceleration of the beginning of introduction of perskovite based panels. It can be noted that the lore seems to indicate portals have been explored for a decade or so in the game world, and tech acceleration doesn't have to imply using portal magic to actually produce the results, but can instead mean that things learned while exploring portals has been spun off into tech that's slightly ahead of where the real world is at, in a similar way that space tech trickles down into ordinary products (and solar panels might be a case of synergy between space and portal tech).

**Comment by ampersand55** [comment]
For electric cars, I think a foldable "vehicle" in the trunk with 4-8 200 W panels mounted on foldable light frames, heavy duty jumper cable and an electric control unit would be a good temporary solution and make electric cars viable.

With 6 panels of 200 W it would take 100000 kJ/6*200W ~= 23 hours of max production to fully recharge a very large storage battery. So lets say 3 days to fully recharge.

**Comment by ampersand55** [comment]
The 13-panneled Solar Car in the game is most likely based on the Toyota Rara X, as it's item id is `rara_x`. This is a very early solar car, based on 1980s solar technology and the game version is probably pretty accurate. The only glaring inaccuracy is that it's made for early solar showcase competitions, but in game it's one of the most common vehicles in the highway spawn group, more common than most vehicles such as 4x4 cars, pickups, busses etc.

A picture of the IRL solar car here:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/27f389c0-e08c-4856-8225-66bc55a2b461)

More pictures (Rara 10):

http://sunlake.org/solar/archaeology/archaeology_j/museum/toyota/toyota.htm

**Comment by estebandellasilva** [comment]
https://sonomotors.com/

its not like there arent any vehicles which use solar power (while not their main use for transportation but for extending the battery life )

**Comment by Zireael07** [comment]
There ARE several solar panel electric cars. Most haven't gone out of prototype stage (like the Toyota mentioned above) but they exist.

Some names/links: https://aptera.us/ ; Lightyear Zero; and the aforementioned Sono (could've sworn there was one more, but google-fu is failing me atm)

**Comment by Alm999** [comment]
Meanwhile, the PR is almost ready. Any additional suggestions?

**Comment by kevingranade** [comment]
No compelling evidence.

**Comment by Alm999** [comment]
Deemed "Invalid" by the "Word of God" without any explanations or counter-arguments.

I regret wasting my time on this.

**Comment by ampersand55** [comment]
If it's any consolation, I play with modern solar panels as a mod based on your PR.
