### ISSUE TITLE
Segmentation fault when trying to accept finishing the camp task of sowing the seeds on a farm

### ISSUE THREAD

**Issue by ForsakenKappa** [CleverRaven/Cataclysm-DDA#67506]
### Describe the bug

The game is crashing, I don't know what to put here ¯\\\_(ツ)_/¯

### Attach save file

[Иннавуд-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12274363/-trimmed.tar.gz)

### Steps to reproduce

1. [E]xamine the camp board
2. Select the option of finishing the sowing task

### Expected behavior

Not crash and make plants sowed

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.6085 (1607)
- Game Version: 9e021bf [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Без ж/д станций [No_Rail_Stations],
    Магиклизм [magiclysm],
    Мифические стили ближнего боя [MMA],
    Сценарии с доп. мутациями [extra_mut_scens],
    Бионические профессии [package_bionic_professions],
    Характеристики за убийства [stats_through_kills],
    Характеристики за навыки [StatsThroughSkills],
    Скорость от ловкости [speedydex],
    Приручаемая живность [Tamable_Wildlife],
    Иннавуд [innawood]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12274318/config.zip)

**Comment by Hirmuolio** [comment]
Something to do with charges removal maybe.

[`if( tmp_seed->count_by_charges() ) {`](https://github.com/CleverRaven/Cataclysm-DDA/blob/28a3f40416ae652e77b213556d41d003d2f09fdf/src/faction_camp.cpp#L3199)

Seeds is not counted by charges anymore? So the code here fails to get the seed and tries to finish farming without seed.

**Comment by ForsakenKappa** [comment]
I'm not suited to fix that bug. Maybe there is a workaround? Feels kind of lame that I can't reclaim my fields, can't use my seeds and that my spare faction member fools around and watches me making nails
