### ISSUE TITLE
SpeedyDex - Standardized Movement

### ISSUE THREAD

**Issue by Mer1ck** [CleverRaven/Cataclysm-DDA#67515]
### Is your feature request related to a problem? Please describe.

Whenever I reach mid-late game, particularly with mods that allow consistent increases to stats (stats through kills/skills, Magiclysm magic items, etc), there always comes a point where nearly every NPC I run into is unable to keep up with my walking speed. This leads to NPCs being even more of a hassle than they already are as I now have to take a pause to wait for them to catch up, which leads to me abandoning them at a camp altogether.

### Solution you would like.

I think the creation of an additional speed setting, perhaps a "Jog" speed. This setting would essentially replace the current "Walk" speed, and have the full benefit of speed enhancements. 
Additionally, the "Walk" speed should have a capped limit so that the player can choose to slow themselves down so that most NPCs or slower pets and companions aren't left in the dust during travel.

### Describe alternatives you have considered.

Continuing to ignore NPCs, or investing in expensive CBMs to enhance their speed

**Comment by ZhilkinSerg** [comment]
Move modes are jsonized, so it would be pretty easy to implement through https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/move_modes.json

**Comment by FIM43-Redeye** [comment]
Move modes don't currently support absolute speed settings. This looks like it'd need changes in code.

**Comment by Mer1ck** [comment]
I noticed that. Depending on how SpeedyDex handles the speed boosts, there doesn't seem to be a way to force a set speed through move_mode.json
My coding limits are at tweaking and duplicating .json files. How difficult would it be to make the kind of changes required to make something like this happen?
