### ISSUE TITLE
Hemostatic Powder is not consumed upon use

### ISSUE THREAD

**Issue by MrBodkin** [CleverRaven/Cataclysm-DDA#67519]
### Describe the bug

When used to stop bleeding, hemostatic powder should be used up and removed from the inventory. I currently have 5 powders in my inventory and I have used them multiple times, but I still have 5.

### Attach save file

[Lemuria-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12285909/Lemuria-trimmed.tar.gz)

### Steps to reproduce

1. Receive a bleeding wound
2. Observe the number of hemostatic powders in your inventory
3. 'Use' hemostatic powder on the wound
4. Observe that the number of powders has not changed

### Expected behavior

Hemostatic powder should be consumed on use.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 28a3f40 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Hirmuolio** [comment]
Probably due to charges being removed this line no longer consumes it.

https://github.com/CleverRaven/Cataclysm-DDA/blob/565ebb75f61c450a29762959b13076280f2ba2f5/src/activity_actor.cpp#L6101

Adding flag `"SINGLE_USE"` on the item seems to work. Probably many medical items need that flag added to them.

**Comment by mqrause** [comment]
That should probably use `use_amount` instead for items that aren't count_by_charges or tools.
