### ISSUE TITLE
Into the Typostrom

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#67518]
### Is your feature request related to a problem? Please describe.

Yet another minor typo, inconsistency, bad English, bad punctuation listing issue filled with the stuff I find while translating, I list those until somebody with too much time on their hands decides to fix them.

### Solution you would like.

The description for the "last" (6th) section of the storage building has a very weird way to formulate that you have the option to go nuts and it further past this section, unsure how exactly to fix it:
- Let's finish our storage building with a last section.  If we really want to, we can then go on to double the volume, but won't that be extreme, when we can use the space to unload loot instead?

Faction camp description for the 7th upgrade the storage building, I get the general gist of it informing you you're going bonkers and doubling its size, but it's probably should end with "lets double the size of the storage building, then proceed with building a seventh section" instead, as right now it makes it seem like the seventh section is just the size of the 6 others combined:
- We want to store EVERYTHING!  Let's double the size of the storage building, proceeding with a seventh section. 

Tacoma additional mission dialogue about the Gather 300 Salt mission, I get the intent of it being "yeah we can't use it for now, but we might send you to get some later when we do have food to preserve" but it's just enunciated so clumsily:
- Salt is key to preserving meat and other perishables… without any excess food it wouldn't do us much good now, but I imagine we'll need to send you out to get more in the future.

Main dialogue string for the Gather 75 Rocks Tacoma mission got a very weird syntax, would be better to be fixed accordingly:
- As quickly as possible, we need to improve the sanitary conditions in the camp. -> We need to improve the sanitary conditions in the camp as quickly as possible. To do so, the first step is to dig a well and construct stone fireplaces in the barn for the migrants to boil water.

Xedra Evolved's qianq of life's plural is spears of life, should be changed to either spear of life or qianq(s) of life

This piece of item description about something likely to fall apart after firing it is the only one of its type to not have [/bad] or [/good] variables on either side of it:
- Stands a somewhat low chance of remaining intact once fired. -> Stands a [/bad]somewhat low[/bad] chance of remaining intact once fired.

### Describe alternatives you have considered.

Not making a list and checking it twice

**Comment by Procyonae** [comment]
I don't get what you think is wrong with the salt one it sounds fine to me

**Comment by sadenar** [comment]
> I don't get what you think is wrong with the salt one it sounds fine to me

Eh might just be a pet peeve of mine, it just didn't look right to me, but if you think it's fine it probably is.
