### ISSUE TITLE
Mend CBM does not use theoretical skill, only practical

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#67510]
### Describe the bug

Mend CBM menu does not use theoretical skill, only practical. I was told this was a bug in the discord, so here i am :)
Trying to mend for example a salvaged arms alloy plating, by going to my inventory, selecting the item and choosing mend, and hitting enter for reset to factory state, tells me I'm unable to mend it this way.

The only skill lacking at the moment is health care 4, which is at 4 theoretical, but only at 3 - 76% practical, and the mend menu put that at 3/4 in red, and does not allow me to mend it.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50793323/8eb8cf85-ae98-451a-ba3d-10dc05dd7c7b)

### Attach save file

Tried a clean world, but eh, couldn't actually find salavaged cbm's to spawn, so imported the char with stuff.
[Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12283740/Test-trimmed.tar.gz)

### Steps to reproduce

Load my save, try to mend CBM, confirm it fails.

### Expected behavior

Well assuming it should use the characters theoretical skill, i would expect it to mend the CBM.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 42ca08e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills]
]

**Comment by oosyrag** [comment]
Resolved by #68312
