### ISSUE TITLE
Barley Seed and Barley recipes result in duplication

### ISSUE THREAD

**Issue by MrBodkin** [CleverRaven/Cataclysm-DDA#67511]
### Describe the bug

The recipe for Barley Seed requires 1 Barley and produces 4 Barley Seeds. The recipe for Barley requires 1 Barley Seed and produces 4 Barley. These recipes can be used repeatedly to produce infinite Barley or Barley Seeds.

### Attach save file

[Lemuria-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12283981/Lemuria-trimmed.tar.gz)

### Steps to reproduce

1. Turn 1 Barley Seed into 4 Barley
2. Turn the resulting 4 Barley into 16 Barley Seeds
3. Repeat

### Expected behavior

The ratio of Barley to Barley Seeds should probably be 1:1, like it is with Wheat and Wheat Seeds.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 28a3f40 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ForsakenKappa** [comment]
Also occurs with buckwheat
1 buckwheat -> 2 seeds
1 seed -> 2 buckwheat

**Comment by fairyarmadillo** [comment]
This is a result of the recent removal of solid comestible charges. I'm not able to work on it at the moment but I'll try to get to it in a couple of days.

**Comment by mqrause** [comment]
Actually this already happened before the charge removal. But the fix is very simple, just remove the `charges` member from all the "reversible" seed recipes like these ones for barley:
https://github.com/CleverRaven/Cataclysm-DDA/blob/b9c3a9a03473fd8ef6cda67363bf5b5bf699c9b3/data/json/recipes/food/seed.json#L124-L138

**Comment by anoobindisguise** [comment]
> Actually this already happened before the charge removal. But the fix is very simple, just remove the `charges` member from all the "reversible" seed recipes like these ones for barley:

So the problem is that your charges PR didn't resolve these conflicts it looks like. The values for volume etc reverted to the previous ones that they had been before-before.

**Comment by mqrause** [comment]
I'm not sure what you mean? This issue is about recipe results. Before my PR they were not specified, which means the recipes would produce default charges. Because my PR removed default charges, it updated the recipes to their explicit values. The recipe results were unchanged.
