### ISSUE TITLE
Riveting as an easy alternative to welding

### ISSUE THREAD

**Issue by nigromancer** [CleverRaven/Cataclysm-DDA#67529]
### Is your feature request related to a problem? Please describe.

The lack of welding rods (and knowledge) in certain situations like the prison island start, is annoying. IRL I could weld with a few batteries and scraps but not well.

### Solution you would like.

A halfway solution for connecting metal frames and other items would be riveting, which has been done since the bronze age, 6000 years ago. It can be done cold or hot and with a hammer, tongs/pliers and a nail or bolt. A hot rivet holds even better as it contracts as it cools. Many early skyscrapers, boats and planes were held together with rivets. 
https://en.wikipedia.org/wiki/Rivet

### Additional context

Riveting allows the attachment of parts but limited repairs of damaged ones unless they are detached, rebuilt and then reattached.

**Comment by GuardianDll** [comment]
For vehicles we can't do such because they do not allow multiple recipes for the same thing
For crafting it's good, if someone decide to spend their time to make recipes that uses it

**Comment by sadenar** [comment]
Also for vehicles it sounds like a very bad idea anyway, for example, on tanks, riveted armor had a tendency to just create a lot of sharp debris when impacted, and I don't think a vehicle with riveted armor/frames would fare much better if you threw it at a wall.
