### ISSUE TITLE
Radio Activation Mod does not denonate pipebombs (and possibly other explosives)

### ISSUE THREAD

**Issue by MrBodkin** [CleverRaven/Cataclysm-DDA#67524]
### Describe the bug

I attached a Radio Activation Mod to a Pipebomb and designated a red signal activation. I then activated my RC Control and pressed the red button in order the send the signal. Instead of detonating the Pipebomb (Radio:R), I got a message saying "You need to wield the pipebomb (radio:R) before activating it." This defeats the purpose of a radio activation. I have only tested this with pipebombs.

### Attach save file

[Lemuria-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12287141/Lemuria-trimmed.tar.gz)

### Steps to reproduce

1. Attach radio activation mod to pipebomb, designating a color to activate
2. Activate RC control and press the appropriate button to send the signal and receive the "Click." message
3. Observe the lack of detonation and the message that follows

### Expected behavior

Sending the correct signal should activate any device with a radio activation mod attached, including explosives.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 28a3f40 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Hirmuolio** [comment]
It is because the explosives can only be activated when player holds them in their hand. This is also checked when remote controller is used.

https://github.com/CleverRaven/Cataclysm-DDA/blob/565ebb75f61c450a29762959b13076280f2ba2f5/src/iuse_actor.cpp#L243

Will have to think some sort of workaround.

**Comment by MrBodkin** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/blob/565ebb75f61c450a29762959b13076280f2ba2f5/src/iuse_actor.cpp#L243

Could the Radio Activation Mod set the need_wielding of the attached item to false? I'm not a modder, I'm just making a guess.

**Comment by Hirmuolio** [comment]
I think all those checks could be moved to `iuse_transform::can_use`.
