### ISSUE TITLE
Hurting an enemy causes it to teleport

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#67527]
### Describe the bug

If you hit an enemy it will teleport to a random tile nearby, as far as I can tell usually out of sight and on the same floor.
Seen in an existing save and in a newly created character and world. 

### Attach save file

[Waitsburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12293012/Waitsburg-trimmed.tar.gz)

### Steps to reproduce

Find an enemy
Close the distance and strike at it
Upon dealing damage it teleports away, with the damage showing from its new location

### Expected behavior

Enemies should not teleport

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51954159/0578c66e-4f90-45f7-b3d0-20ed0c66abce)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: 4de6b26 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Pixel's Various Fuckery [Pix's Shit],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by baldamundo** [comment]
I had the same issue after updating from build 2023-08-06-1506 to build 2023-08-08-1423

**Comment by raymond-w-ko** [comment]
I'm using build 4de6b26 with MoM, and am also experiencing this. I thought I was hallucinating, but I have no such traits or conditions.
