### ISSUE TITLE
Memory cards (SD cards) give access to extradimensional recipes

### ISSUE THREAD

**Issue by Bydth** [CleverRaven/Cataclysm-DDA#67522]
### Describe the bug

The standard memory cards ( called SD cards in the stable) can give the recipes for the various nomad armors, which are otherwise only obtained through buying the blueprints from the Exodii. The recipes for beast and chimera samples can also be downloaded from memory cards.  I'm assuming this isn't intended behavior, as these recipes are clearly otherwise gated behind contact with the Exodii, and there's no real way that random zombies would be going around with these recipes on their phones.

### Attach save file

[testingland-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12286411/testingland-trimmed.tar.gz)

### Steps to reproduce

Download a fresh version of the latest experimental. Make a character survivor with 10 in every skill, to confirm which recipes can be autolearned. Spawn in a storage battery and several hundred (or several thousand) unread memory cards, place the battery, plug in the smartphone and download data from the cards. Search the crafting menu or the stored recipes on the phone and see that the various nomad armor recipes are now stored on the smartphone and are available to craft.

### Expected behavior

These recipes aren't in the potential list of recipes that can be downloaded from memory cards, as the only place they exist in the game world is in the blueprint pamphlets the Exodii (who arrived during or after the cataclysm) are selling. To have one of these recipes on a random memory card, another survivor would have had to made contact with the Exodii, traded for one of the blueprints, scanned just one of the recipes into a phone,  then either copied the design onto a memory card and left it lying around, or gotten killed and revived as a zombie with the recipe stored on the phone.  Same goes for the chimera and beast sample recipes.

### Screenshots

![Screenshot (2413)](https://github.com/CleverRaven/Cataclysm-DDA/assets/135287854/2c7190e9-798e-4e11-a8bc-85181cb81311)
![Screenshot (2418)](https://github.com/CleverRaven/Cataclysm-DDA/assets/135287854/69962b26-3056-4c9d-828b-93b8a306f509)
![Screenshot (2419)](https://github.com/CleverRaven/Cataclysm-DDA/assets/135287854/c8df59e7-ca12-4eb5-a15e-70d9f8b2c1c1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 383e125 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ampersand55** [comment]
Can confirm and looks like it's made that way in the json.

https://github.com/CleverRaven/Cataclysm-DDA/blob/565ebb75f61c450a29762959b13076280f2ba2f5/data/json/items/generic.json#L2222-L2241

Simplest fix would be to increase the level requirements of nomad and sample recipes to 6+.

**Comment by Vaskritaya** [comment]
It would be the simplest, but probably not the best. Beast samples were explicitly made level 5 for gameplay and lore reasons in #66933, so it would be odd to go back on that. Maybe there should be a recipe flag specifically for "esoteric" recipes, similar to `"SECRET"`, so that SD cards any any other future recipe sources can explicitly ignore them?

**Comment by ampersand55** [comment]
Or have `recipes_categories` accept subcategories such as `CSC_CHEM_MUTAGEN`.

**Comment by RenechCDDA** [comment]
Oops! Sorry about not catching this report at the time, I resolved it in #68305.
