### ISSUE TITLE
Wind turbine technology has evolved a lot since wind turbines were first implemented into the game and it's in need of an update.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67533]
### Is your feature request related to a problem? Please describe.

Like solar panels (see #67498), wind power is also a lot less effective in game than in reality. The commercially available wind turbines for home use range between 100 W-1000 W, but the in game turbines can only match that during storms. The in-game wind turbines you craft yourself, but there's no reason you you wouldn't be able to find commercially available wind turbines on roof tops similar to solar panels.

Some comparisons with commercially available wind turbines:

| Turbine | Weight |  Power @ 10 m/s |   Power @ 20 m/s  |
| --- | --- | --- | --- |
| In game wind turbine | 50 kg | 10 W | 20 W | 
| In game large wind turbine | 150 kg | 30 W | 60 W | 
| ATO 100 W Horizontal Axis Wind Turbine | 10 kg | 80 W | 110 W | 
| ATO 500 W Horizontal Axis Wind Turbine | 22 kg | 400 W | 500 W |
| ATO 1000 W Horizontal Axis Wind Turbine | 38 kg | 800 W | 1040 W | 

The start up speed is 2.0-2.5 m/s, optimum wind speed for all of them are about 11.5 m/s and the survival speed ranges from about 40-55 m/s, where the smaller turbines can survive higher wind speeds.

The 100 and 500 W varieties are 12V, meaning they could be installed in vehicles. 

### Solution you would like.

Update them to better match commercially available turbines.

### Additional context

These were used for reference, and seem to be in-line with other commercially available turbines:

* https://www.ato.com/100w-wind-turbine
* https://www.ato.com/500w-wind-turbine
* https://www.ato.com/1000w-wind-turbine-24v48v

Power curve for 500 W version:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/9f79721e-258b-49ad-951b-5554c0af27fe)

**Comment by PatrikLundell** [comment]
I don't think player made wind turbines should be better now than they were 20 years ago as they'd be made the same way from the same materials, but I can't say if player made turbines are in line with reality or not.

When it comes to commercially produced wind turbines it would make sense that improvements might be reflected in lootable wind turbines, provided there should be any of those available (but some of the lootable ones would probably not be brand new). I have no idea about how common such turbines are in New England (and didn't even know commercial wind turbines for private use existed at all).

**Comment by Alm999** [comment]
> …but I can't say if player made turbines are in line with reality or not.

Probably not. I have a feeling this part of content hasn't been touched for a while, so the balancing is questionable (Sometimes referred as "power fantasy", sometimes the other way around).

**Comment by ampersand55** [comment]
I think the best would be to leave the current wind turbines as is, and introduce some additional commercial wind turbines.

**Comment by Calavera20012** [comment]
> I think the best would be to leave the current wind turbines as is, and introduce some additional commercial wind turbines.

Yes that would be best, I am currently working on Sprites for both ingame makeshift turbines and I am basing them on improvised stuff you find online, turbines really are something anyone with a small familiarity with mechanics and a manual can figure out.
