### ISSUE TITLE
Mission Objective Distance indicator in map screen should display its distance in kilometre or miles instead of overmap tiles

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#67549]
### Is your feature request related to a problem? Please describe.

It would be neat to see how long of a distance an objective is in kilometre or miles instead of overmap tiles.

### Solution you would like.

Displaying the objective's distance in kilometre or miles.

**Comment by masema** [comment]
To start, I do like the idea of real world measurements being available for this, I find the tiles distance to be useful. So maybe an option for it to display either or both?

**Comment by PatrikLundell** [comment]
The game fudges distances for various technical reasons, and tiles is the only measurement that the player can use as a useful in game reference. That said, I certainly wouldn't be opposed to the display of both or an option to change from a default of tiles to a display of distances in the unit appropriate for the measurement system setting.
