### ISSUE TITLE
Impassible metal floor in prison island boat house.

### ISSUE THREAD

**Issue by nigromancer** [CleverRaven/Cataclysm-DDA#67546]
### Describe the bug

On the prison island start, the boat house has a metal floor under the sliding door exit to the lake. When raised, trying to ride the boat out of the boathouse is impossible and displays  the message that the boat "doesn't have enough wheels to move".  Debugging the metal floor in those square to replace with deep water solves the problem. 

### Attach save file

N/A

### Steps to reproduce

Try to ride boat out of prison island boat house.

### Expected behavior

I expect to sail out easily.

### Screenshots

N/a

### Versions and configuration

0.F stable d6ec466

### Additional context

N/A

**Comment by Night-Pryanik** [comment]
Please update to at least 0.G and see if this still a problem.

**Comment by GlordXd** [comment]
> 0.F stable d6ec466


Are you a time traveller or something? 0.G is out for like,5 months already,or did a portal storm brought you here?

**Comment by Golfavel** [comment]
"0.F" `d6ec466` is 0.G stable.

**Comment by nigromancer** [comment]
I downloaded the latest stable 0.G but when it unzips, the folder is called 0.F. 
I have no idea why, except the Devs did it - I'm just filling out the form as instructed.
Yes, the problem still exists.

**Comment by Procyonae** [comment]
Works fine for me on experimental
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/c3d878e9-b60d-4aa3-b22f-49a0507edb7f)

**Comment by nigromancer** [comment]
Screen shot showing the metal floor that prevents boats leaving. 
![cdda-metal-floor](https://github.com/CleverRaven/Cataclysm-DDA/assets/86794551/5dc3014f-2ee4-402c-b403-c70266328bad)

**Comment by oosyrag** [comment]
As stable releases are years in the making, issues with stable could have been fixed in the months since then. To contribute more effectively to development, consider using more recent experimental versions.
