### ISSUE TITLE
Cant seem to randomize the starting date of a scenario

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#67558]
### Describe the bug

For whatever reason, i cant seem to randomize the starting date of the cataclysm, only the hour of it, and it defaults to spring day 1, as opposed to the previous build's spring day 61.

### Attach save file

N/A

### Steps to reproduce

1. make a world
2. go to chargen of the world
3. press the randomize date button ~~(which is `^` according to the keybinding menu, not `&` despite what the ui said)~~ (nevermind, it's &. not sure what changed when pressing `^`)
4. see that it doesnt work.

### Expected behavior

randomized the date.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 477c84a [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]

**Comment by ZhilkinSerg** [comment]
Part of cataclysm start date or game start date can only be randomized if scenario if it is marked as "random" in scenario settings.

**Comment by ThePatware** [comment]
Adding on that I've been told that all the start dates (both gameplay and cataclysm) defaulting to Spring 1 should be considered a bug on its own. I'm not at all modding-savvy or git-savvy and this was the only place I could even find out how to change the cataclysm start date - as it is, now all scenarios have become challenge scenarios unless you go into the game's code. Not sure if the comment on here is enough to have that considered or if I need to make a new report.

**Comment by PatrikLundell** [comment]
If it works as described in the PR, changing the date shouldn't require going into the code and recompile, but "merely" changing JSON description (which can be done with any text editor and doesn't require any compiler). That's of little consolation to those who don't understand the JSON formatting or its use in the game, though.
