### ISSUE TITLE
Wall light causes npc pathing issues

### ISSUE THREAD

**Issue by Zoraman26** [CleverRaven/Cataclysm-DDA#67553]
### Describe the bug

"Directed Wall light" appears to prevent NPCs from pathing directly next to them

### Attach save file

[Reed Point-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12303752/Reed.Point-trimmed.tar.gz)

### Steps to reproduce

Place directed wall light,
walk past with npc following
Npc gets stuck and won't path past

### Expected behavior

Npcs have no trouble pathing beside directed wall lights

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/88414058/45ae483b-f98b-4abc-aefb-d5a2babca469

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 477c84a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Generic Guns [generic_guns],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]

**Comment by harakka** [comment]
/confirm

Reproduces with provided save on cdda-windows-tiles-x64-msvc-2023-08-09-1243
