### ISSUE TITLE
Overpowered Water Purification Tablets

### ISSUE THREAD

**Issue by kylesjob** [CleverRaven/Cataclysm-DDA#67551]
### Describe the bug

Using the (a) key to use an item in your inventory, you can use a single water purification tablet to perform the action "Purify some water".

Using this on a container of water, you can purify as much water as you want.

### Attach save file

N/A

### Steps to reproduce

1. Activate a water purification tablet in your inventory.
2. Use it on any container with dirty water.

### Expected behavior

I expected to not be able to purify an entire 200L steel drum of water with one tablet, as the description of the tablet states that it's only capable of purifying 250mL.

### Screenshots

![Screenshot_26](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/bbdc241c-2916-42a8-acf1-3514694f3d07)
![Screenshot_27](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/0eeb971e-dca4-4c61-80a1-4a42bb0c3d9c)
![Screenshot_28](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/e49b9742-e8cf-4b3b-96cc-197af4d64316)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.2057 (21H2)
- Game Version: 80b807a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Blaze Industries [blazeindustries]
]

**Comment by anoobindisguise** [comment]
water purification needs to be looked at anyways, because IRL you can purify an entire gallon of water with something like 1-2 ml of water (or maybe as much as 3-4 if the water is *really* cloudy) but in game it takes 125 ml of bleach (and 10 aspirins and 10 potassium iodide) to make a single pill; based on bleach content alone that should be sufficient for over 300 liters of water.
