### ISSUE TITLE
Nested Scenario Groups

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#67568]
### Is your feature request related to a problem? Please describe.

In a similar way that the recipe list has been improved by nested categories I believe that the scenario menu could be improved in the same way.

### Solution you would like.

Nested groups of scenarios so that similar starts can be grouped together.  Some could be rural, some could be urban, classic challenge scenarios.  We might not fully need it yet, but I think that it could be done before we decide it's required.

### Describe alternatives you have considered.

I dunno.

**Comment by ilovehans10** [comment]
Something else that could be used in tandem with this idea would be a tagging system for scenarios.  This would allow for searching for all the hard, military, rural, mutant, lab, etc. scenarios (things like mods could be automatically applied as tags). To compare to nested scenarios, a strength of this is scenarios could be in two or more categories, but a major downside is that there would have to be some way that tags were conveyed to players/selected (possibly a multiselect menu). These systems could be implemented at the same time and I believe would compliment each other, but I also understand that would be a lot more overhead in the c++.
