### ISSUE TITLE
Inserting unowned items in a container does not trigger stealing check

### ISSUE THREAD

**Issue by deepvelocity** [CleverRaven/Cataclysm-DDA#67565]
### Describe the bug

When Inserting items from around you in container NPCs do not react to you stealing their stuff, even if picking it up directly would have been theft.

### Attach save file

N/A

### Steps to reproduce

    Stand next to a container/items owned by another Faction
    [I], open Insert menu for any container in your inventory
    Spend some quality time watching your character steal items without a care in the world.

### Expected behavior

Same "that would be stealing, continue?" prompt as when trying to pick the items. And reaction from the NPCs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 0.G-3620-gc7e83b28b7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Realted: https://github.com/CleverRaven/Cataclysm-DDA/issues/61296

**Comment by EvanBalster** [comment]
Just came across this issue myself.  Foodperson:tm: threw their bat at a zombie and I used the `i`nsert command to attach it to my backpack.  When I went to tried to give it back to them they got *big mad*.
