### ISSUE TITLE
The addition of nuts and bolts limited the development in Innawood mod.

### ISSUE THREAD

**Issue by miheevv** [CleverRaven/Cataclysm-DDA#67570]
### Is your feature request related to a problem? Please describe.

The addition of nuts and bolts limited the development in Innawood mod. For example, it is impossible to install a control system on a vehicle or create a large windmill. From a practical point of view, this should not be a block, because with electricity and a milling machine, they could easily be made on their own (this is not some kind of rocket science).

### Solution you would like.

I suggest either introducing the crafting of nuts and bolts into the game and / or adding additional recipes for crafting things with the ability to replace them with welding (with an increase in production time in the form of a penalty).

### Describe alternatives you have considered.

The introduction of additional recipes without bolts and nuts, replacing them with welding and increasing the production time in the form of a penalty, could solve the problem.
If you have no desire to make a milling machine and no desire to make it, but there is welding, is it not a problem to use it?

**Comment by kevingranade** [comment]
To be clear,  you're asking for nut and bolt crafting and/or welding as an alternative *in innawoods*, right? (Does innawoods have a lathe? It really shouldn't...)
The crafting logic in innawoods is substantially different from the main game,  so divergences like this are expected.

**Comment by cz5-rgb** [comment]
We could add rivets as a substitute for nuts and bolts, which could be craftable. Needing a screw lathe would be a bit much.

**Comment by cz5-rgb** [comment]
So due to limitations with vehicle recipes, rivets can't easily be added to the base game. I renamed "nuts and bolts" to "rivets" in the mod and added a crafting recipe for them in my game. Not sure if that is an appropriate change, but I'm having fun.

**Comment by lopho** [comment]
Using a manual thread cutting tool should be enough to produce N&B with a forge. So instead of a full blown lathe, a forge & thread cutter & a vice (which I just assume isn't required since most things forge related that would require a vice don't).

I'll look into adding this tool + recipes for the tool and N&B using it.
![thread_cutter](https://github.com/CleverRaven/Cataclysm-DDA/assets/1366969/7d13167a-c7c1-44a2-a1c1-546661b4a063)

**Comment by lopho** [comment]
how does this sound?
```
nut and bolt

anvil 3
hammering 3
metal sawing 2
forge
metal fileset
flatjaw tongs
hotcut
thread cutting set
---
3 scrap metal / 1 chunk of steel
---
makes 4
75% > 2
1 hour
---
pr. of blacksmithing (1.25x, 0.75)
pr. of metalsmithing (1.50x, 0.5)

========

thread cutting set

anvil 3
hammering 3
chiseling 3
forge
metal fileset
flajaw tongs
---
4 chunk of steel / 1 lump of steel
2 pipe
---
makes 1
5 hours
---
pr. of blacksmithing (1.50x, 0.5)
pr. of metalsmithing (2.00x, 0.25)
manual tooling (2.00x, 0.15)
```
2 pipes since it'll be a set of internal and external threading tools

**Comment by evankimori** [comment]
Sounds good so far to me. Would've liked to hear from other users as well.
