### ISSUE TITLE
Can no longer change start time / date on latest exp

### ISSUE THREAD

**Issue by teapot156** [CleverRaven/Cataclysm-DDA#67590]
### Describe the bug

See title, see picture. Using exp as of today.

### Attach save file

N/A

### Steps to reproduce

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/38711875/551510a7-a221-4278-8766-8394c14cebcb)

### Expected behavior

N/A

### Versions and configuration

Latest exp as of today

2023-08-10-2111

**Comment by teapot156** [comment]
Im assuming that #67579 is the cause

**Comment by ZhilkinSerg** [comment]
> Im assuming that #67579 is the cause

No, see #67472.

On the opposite #67579 would expand on that and fix some things.

**Comment by ZhilkinSerg** [comment]
Duplicate of #67558
