### ISSUE TITLE
Crash when loading Dark Days of the Dead

### ISSUE THREAD

**Issue by Mightyjack22** [CleverRaven/Cataclysm-DDA#67594]
### Describe the bug

When loading into a new world with the mod enabled (i've disabled everything but dda and the mod after trying with my normal load order) it will get stuck at finalizing items then crash with no error or crashlogs.

### Attach save file

N/A (Unable to get into a character on that world)

### Steps to reproduce

Enable the Dark Days of the Dead mod, with or without other things enabled along side dda. Load into the world after creating a character. It gets stuck at finalizing items and then hard crashes.

### Expected behavior

I thought the mod would work along side the default loaded mods.

### Versions and configuration

Windows 10
1432bb7
Tiles
English
dda, Dark Days of the Dead [classic_zombies]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12317917/debug.log)

**Comment by kristjanarn** [comment]
Happening to me aswell on experimental build f2dedcb (2023-08-12-0515).
Albeit without the hard crash.

Stops responding while finalizing items, but it loads in fine after ~10-15 minutes.
Tried loading just DDotD & DDA and it's the same.

Game runs mostly fine after loading (1 random CTD, didn't catch the log), but autosaves take a lot longer.
