### ISSUE TITLE
NPC status sidebar

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#67591]
### Is your feature request related to a problem? Please describe.

NPCs die a lot. Some of this is from AI issues, but there are a few other causes. One preventable cause is that it's actually pretty tough to see how your NPC is doing from turn to turn.

### Solution you would like.

I'd like a sidebar element that summarizes your current followers (not those on guard mode), something like this:

```
Luo Meizhen, beggar: |||\--
Sam Smith: |||||
```

We already, I believe, have the code to summarize NPC health as a single line, used in [V]iew.

Additionally, we could include recent NPC snippet dialogue, so that it doesn't get lost in combat message spam: that would look something like this.

```
Luo Meizhen, beggar: |||\--
"I need to put a bandage on this."
Sam Smith: |||||
"Look out, a spam bot!"
```

Finally, we could consider a few critical states, particularly bleeding, that we might want to render in there:

```
Luo Meizhen, beggar: |||\-- (B)
"I need to put a bandage on this."
Sam Smith: |||||
"Look out, a spam bot!"
```

### Describe alternatives you have considered.

It might be nice to have two options: a summary of all your followers that just shows health, and a pane for each individual NPC that shows more data. Then you could have more information on special unique followers you're trying to protect, for example.

**Comment by TheSaddestGoomba** [comment]
Do you think it would be possible to recolor the "NPC dies" messages in the log?
I believe they still default to white and tend to get lost. I've considered looking into it myself but it also seems relevant to this PR.

**Comment by I-am-Erk** [comment]
It should definitely be in red. That's super easy. Just find the add_msg to be m_bad

**Comment by John-Candlebury** [comment]
The functions described here probably deserve to be part of an whole "party management" sheet that summarizes relevant information, can lead to the particular info of each NPC, and can be used to trigger party activities like healing, transferring items and changing combat rules.

It seems unlikely that just a health bar widget would help, it reveals too little information.

**Comment by I-am-Erk** [comment]
I'd love to see that, and now that I know more about npc AI, it wouldn't be as hard to include more as I thought.

- current action is something the npc stores
- we could use the most recent self threat assessment and active danger assessment to display "resolve" as a meter, telling you how likely the npc is to run away
- several active status effects could be given an abbreviation 

So you'd get something like:
```
Luo |||\- (Bleeding), following
Resolve |||--
"Look out, mi-go over there"
```
