### ISSUE TITLE
Move the frequently made suggestion wiki page to the documentation

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#67605]
### Is your feature request related to a problem? Please describe.

As it stands, the frequently made suggestion page is in the repo wiki (https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions) - which works. The issue is that this means this can't be contributed to, and as we've discussed on the devcord several people have encountered the issue where being able to PR directly to the fms would help, but they were unable to do so.

### Solution you would like.

Moving the fms (frequently made suggestions) to the ingame documentation. This would allow any contributor to PR to this (obviously with the standard review and merging procedures), which means we don't have to annoy CleverRaven members any time we think something warrants a mention in there. Since we also now have a website that hosts the documentation (https://docs.cataclysmdda.org/), I don't think this would cause any issue with the availability of this information while making it easier to maintain. The only problem this would cause is the discord bot would need to have its link changed, but I think that's a low sacrifice.

### Additional context

You COULD argue that the fms is not development-related and therefore does not warrant being in the docs - and to that I say I disagree completely. It highlights often brought up things and with 9/10 either says why the common ideas to implement them don't work or says how they would need to be implemented to work. It also serves as a guide (with the failed rationalizations subsection) of how a contributor should think when *developing* for the game. It does stand out from most of our other docs (most similar one is the living lore doc, which is honestly a great idea in itself), but I firmly believe it is still very relevant for the development of the game and, in my eyes, is the no.1 must read for new contributors in the first place.

**Comment by Procyonae** [comment]
The whole wiki should be added to docs (or removed where duplicated/out of date) and just replaced with a link to the online docs imo

**Comment by I-am-Erk** [comment]
completed by [#68779](https://github.com/CleverRaven/Cataclysm-DDA/pull/68779)
