### ISSUE TITLE
Krav Maga is not working with ar-15 and m4

### ISSUE THREAD

**Issue by YuPro** [CleverRaven/Cataclysm-DDA#67600]
### Describe the bug

There is no `"copy-from": "rifle_semi",` and `"copy-from": "rifle_auto",` lines for Modular AR-15 and Modular M4 so Krav Maga is not working with these rifles.

### Attach save file

N/A

### Steps to reproduce

1. Make a player with an AR-15 and learned Krav Maga
2. Toggle Krav Maga on and wield AR-15
3. AR-15 is a not valid Krav Maga weapon

### Expected behavior

Krav Maga need to work with these guns.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23240052/ecbe03d5-c15a-424b-9aff-307c0d9fd7d4)

### Versions and configuration

N/A

**Comment by baldamundo** [comment]
Came here to post the same issue with the M4A1/modular_m4a1

The M4 Carbine/modular_m4_carbine root item seems to work correctly for Krav Maga so i guess the problem is in the variant code?
