### ISSUE TITLE
Using the mouse on menus with nested elements malfunctions

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#67611]
### Describe the bug

Using the mouse on menus with nested elements (e.g., settings) malfunctions and appears to falsely assume all items are visible.

### Attach save file

N/A

### Steps to reproduce

1. Open settings menu
2. Attempt to interact with elements (i.e., not just from top to bottom)
3. Highlight hidden items

### Expected behavior

Only visible elements can be interacted with.

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/24062b38-708c-47b9-9d6a-870bba27280e

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: ed0ff32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Does occur in more recent commit; https://github.com/CleverRaven/Cataclysm-DDA/commit/67cdc6b4ea5b4fca8193f954c4b0fb2e3109bd1a

**Comment by Drew4484** [comment]
Confirmed on build 02942dc.

**Comment by alef** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/assets/3899581/5c79b7be-1d00-4b73-994a-5e8a38d7575b
