### ISSUE TITLE
big slowdown while sleeping

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67625]
### Describe the bug

what it says on the tin, checkout the save

### Attach save file

[Innawood-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12328167/Innawood-trimmed.tar.gz)

### Steps to reproduce

1.open the provided save
2.go to sleep
3.notice the slowdown, and towards the end it speeds up a bit.

### Expected behavior

uh..minimal amount of slowdown possible? im assuming some unintended behaviour is firing every turn or something

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: f2dedcb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Innawood [innawood],
    starry nights [starry_nights],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by MrHrulgin** [comment]
Without checking your save, slowdowns in sleeping or other activities that spend time quickly are common whenever there's something big around, whether that be an NPC base, a lab, or any other situation with a lot of things to track.
