### ISSUE TITLE
Smoking food remove caloric value

### ISSUE THREAD

**Issue by lech14** [CleverRaven/Cataclysm-DDA#67627]
### Describe the bug

When smoking food (in smoker made from build menu) it loses caloric value
I'm not sure if smoked meat loses it or it is lost for dehydrated meat, as i without checking smoked double time for dehydrated meat
When smoking (dehydrating) vegetables (cattail stalk) it also loses caloric value

### Attach save file

[Pound Ridge-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12328389/Pound.Ridge-trimmed.tar.gz)

### Steps to reproduce

There is some cattail stalk in fridge on the ground floor, smoker is on the roof
1. put food in the smoker
2. smoke it to dehydrated level
3. food no longer have calories

### Expected behavior

I expect that food will lose some nutrition, but not all

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/112639662/61c9f8b5-fb67-4476-a3d2-99fc1445e3d0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 3a3d124 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    No Hope [no_hope]
]

**Comment by ampersand55** [comment]
See #67411
