### ISSUE TITLE
Furniture does not update in player's map memory if it's destroyed by an outside force

### ISSUE THREAD

**Issue by Vulp0d** [CleverRaven/Cataclysm-DDA#67638]
### Describe the bug

If an outside force destroys the furniture (for example npc clearing the back bay in the refugee center) it stays in the map memory and never updates, even after reloading the save. The only way for it to update is to have it replaced by something else and removing it.

### Attach save file

N/A

### Steps to reproduce

1. Create a new world and a new character.
2. Head to the Refugee Center and accept quest to clear the back bay.
3. Clear the back bay, finish the quest, accept the next quest to recruit people to clear it and finish it.
4. Notice how the furniture disappears if you enter the back bay and reappears as soon as you leave and close the door.

### Expected behavior

Map memory updates regardless of how the furniture was removed.

### Screenshots

![Zrzut ekranu 2023-08-13 102413](https://github.com/CleverRaven/Cataclysm-DDA/assets/142141427/ca8a59bc-5f5c-4bd3-8b19-7219099bfa8c)
![Zrzut ekranu 2023-08-13 102520](https://github.com/CleverRaven/Cataclysm-DDA/assets/142141427/d7595fac-a3f3-4280-9d1e-eac2bc2e2a71)
![Zrzut ekranu 2023-08-13 102543](https://github.com/CleverRaven/Cataclysm-DDA/assets/142141427/ab729226-2a3b-4d3c-91ba-74d670704956)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 444f3f7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

N/A

**Comment by KHeket** [comment]
Seems the same problem as was in linked issue in https://github.com/CleverRaven/Cataclysm-DDA/pull/66775
@irwiss can you check this pls?

**Comment by KHeket** [comment]
Also black spots doesnot updated, I whink, its the same issue

<details>
  <summary>Spoiler warning</summary>

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/649bddeb-fe2f-4823-b842-67e600797555)

</details>

@irwiss pls take a look
