### ISSUE TITLE
road segments with 3 cars and benches are too common

### ISSUE THREAD

**Issue by irisanuwu** [CleverRaven/Cataclysm-DDA#67649]
### Is your feature request related to a problem? Please describe.

when the road creates a "square" (see below), 3 cars are spawned. given the frequency of abandoned vehicles out of town, this generation is too common and the amount of vehicles within it is excessive for how common the tile is.

### Solution you would like.

make it so this generated segment can spawn as just a piece of road without any vehicles and is a more common occurrence than the existing variant. bonus points for creating variability in the amount of vehicles this segment spawns.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/106341934/4b28e536-b883-4018-9cf6-3a9517805fc5)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/106341934/0d79536e-ba72-470d-a421-ae02d45c7dc6)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/106341934/94e3cf99-c5f1-43fa-b3a6-9fdc12bd58ae)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/106341934/1cef5100-5004-4cd9-b854-3e6973451b5a)

**Comment by Procyonae** [comment]
Or y'know fix connection code so it doesn't form 😉
