### ISSUE TITLE
Arcade machines provide no light when On

### ISSUE THREAD

**Issue by Vendidurt** [CleverRaven/Cataclysm-DDA#67651]
### Describe the bug

Arcade machines dont emit light, and i believe they should

### Attach save file

n/a

### Steps to reproduce

1. Rig up a working power grid in a room which can be made completely dark.
2. Attach Arcade Machine via *build menu.
3. Turn on machine, observe no light changes.

### Expected behavior

Arcade machines are bright IRL. They can certainly get bright enough to read beside. Evacuation Shelter consoles are bright enough to read beside or do crafting work in-game and i feel that Arcade Machines should be at least that bright when powered.

### Versions and configuration

Windows 10 version 1f5aaac

**Comment by Maleclypse** [comment]
Closed by #67658
