### ISSUE TITLE
Laptop screen light is OP

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#67665]
### Describe the bug

Laptop computers can be activated to "light up the screen" which creates one tile of bright light. A single normal medium battery can power a laptop in this state for nearly 150 hours. I've never owned a laptop that could continuously run for over 24 hours, let alone six times that long. Laptop screens also tend to be very dim, even at their brightest setting.

### Attach save file

n/a

### Steps to reproduce

Spawn a laptop and medium battery
Turn it on
Bright as day and lasts almost 6 days

### Expected behavior

The screen should provide only dim light, and it should drain a full battery completely within 20-30 hours of use.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: c5f621c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by I-am-Erk** [comment]
I enjoyed the title of this report.
