### ISSUE TITLE
Crash when npc completes plant fields mission

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#67681]
### Describe the bug

The game crashes when I try to recall npc from plant fields mission. 

### Attach save file

[Deaver-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12346364/Deaver-trimmed.tar.gz)

### Steps to reproduce

Walk upstairs in evac shelter and examine the bulletin board. Select option to complete plant fields mission.

### Expected behavior

Game finishes and seeds were planted.

### Versions and configuration

OS: popos 22

**Comment by fairyarmadillo** [comment]
It's almost certainly due to a lot of stuff in mission_companion.cpp trying to use charges for both seeds and crops.
