### ISSUE TITLE
Chargen considers newly buffed professions overpowered

### ISSUE THREAD

**Issue by venvenvenvenvenvenven** [CleverRaven/Cataclysm-DDA#67685]
### Describe the bug

#67536 buffed profession skills, however, the sample character that is used for power calculations at chargen wasn't buffed to account for this. As a result, even some professions that wouldn't have previously cost many points (e.g. Butler, Traveling Preacher, Paranormal Investigator) are considered powerful or overpowered by the game.

### Attach save file

N/A

### Steps to reproduce

1. Start creating a custom character
2. Pick Butler as your profession
3. Check summary: the game thinks you are OP

### Expected behavior

_Just_ picking a profession probably shouldn't make the game consider you are overpowered, especially if it's something like Butler

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: aa611c5 [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Fris0uman** [comment]
After https://github.com/CleverRaven/Cataclysm-DDA/pull/67663 a character with just the default basic backgrounds is also displayed as Overpowered in the Knowledge category

**Comment by PatrikLundell** [comment]
My newly created character was considered overpowered despite having a large number of negative traits and no skills or proficiencies (I removed the basic life skill ones selected by default). The only thing going for that character is good stats, about what you could achieve with the old joint pool system (and the section corresponding to that being considered overpowered is reasonable).
