### ISSUE TITLE
"hoarder/minimalist" variable for tiles

### ISSUE THREAD

**Issue by yoopgim** [CleverRaven/Cataclysm-DDA#67688]
### Is your feature request related to a problem? Please describe.

ive noticed that overall tiles seem to have the same ammount of loot if they are the same varient, which isnt quite realistic.

### Solution you would like.

i propose a variable be added that is randomized for each tile (maybe on a scale from 1-8) that changes the overall amount of items (and possibly funiture, which i will describe later) on that tile and what condition they are in.   1 could be a tabula rasa, the tile is clean of all furnishings and items except for those attached to the building itself, real life example: a house that you are looking at possibly moving into. 2 is when someone is in the process of moving in. tons of boxes, mostly full of nesecities and a few important personal items, and all the major furniture is there. 3 could be a minimalist lifestyle. basically the items from 2 but more organized and lived with. 4 is standard. 5 has excess items, but still not too much. 6 has excess items spread arround, and some degraded/filthy/rotten. 7 is a hoarders house (think wilburs bathtub video). and 8, in a nutshell, is Mr.Universe's storage unit.

**Comment by ZhilkinSerg** [comment]
We already have house mapgen palette variety - see https://github.com/CleverRaven/Cataclysm-DDA/pull/67187 and https://github.com/CleverRaven/Cataclysm-DDA/pull/64678.
