### ISSUE TITLE
Reload containers to consolidate similar items?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67692]
### Is your feature request related to a problem? Please describe.

For liquids, you can "R"eload them to pour other bottles of the same liquid into the single container. If I had a bottle with 4 antiseptic and one with 5, I could reload either bottle to consolidate the liquids into one bottle. By comparison, organizing dry goods by type is very tedious.

### Solution you would like.

It would be very helpful if "R"eloading to consolidate would be possible for dry goods. Being able to have a single large bag with some aspirin in it and simply reload to consolidate those 18 separate partial small bottles of aspirin would save a huge amount of clicking to handle inventory management.

### Describe alternatives you have considered.

A separate keybind doing the same sort of thing would be fine. Some entirely different theory of how to consolidate small items using zones and having an NPC do it would be fine. I don't honestly have a lot of attachment to a given way of handling it as long as there's some way of consolidating supplies that doesn't involve manually opening every container to pack items into them.

**Comment by PatrikLundell** [comment]
The issue seems to be related to the one in #67672.

**Comment by MrHrulgin** [comment]
In that they're both ideas on how to manage large quantities of small items inside containers, yes.
