### ISSUE TITLE
Defense Mode mod - some bugs

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#67701]
### Describe the bug

1. Game spawns a f ton of Nemesis after a certain time passes.
- This is inevitable as some places spawns you near bodies of waters and some zombies spawns in them, specially crawling zombies and if you enable spider waves, it is highly likely that some neutral spiders don't even go near your base.

2. NPC Merchant Caravan won't spawn if there's any sort of "enemy" that are in the map, even if they aren't spawned from the monster waves.

3. Force teleport are a bit icky and wonky at certain parts of the "fortress", as it doesnt even allow you to move to certain spots of your base.
- You should be able to walk outside of the building for upto 3 tiles away instead of the random 0 tiles to certain side and upto 3 tiles on certain side of the building
- This causes the spawning of Nemesis as well due to how you can't reach certain places.

4. Money gained per wave isn't working and NPC Caravan Merchants will not save owned money and will always reset.
- File states that we should be getting money per wave cleared/survived.

### Attach save file

N/A

### Steps to reproduce

1. Play as usual.
2. Enable some monster spawns, spiders have the highest chance of spawning nemesis due to neutral spiders
3. Starting Day 2 if the map have something hostile that wasnt spawned by monster waves, the NPC Caravan may not spawn
4. Walk outside of the building hugging the walls and you will be forced teleport back to spawn despite being right beside the fortress

### Expected behavior

Nemesis shouldnt be spawning starting day 1

NPC Caravan should be spawning in 2 day regular intervals when wave spawned monsters are all dead

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: 07ae95f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Defense Mode [defense_mode],
    Xedra Evolved [xedra_evolved]
]

**Comment by MNG-cataclysm** [comment]
I'll get on this ASAP.
