### ISSUE TITLE
Bastion fort should have rooms in it's walls and basecamp version (maybe a defense mode one too?)

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#67703]
### Is your feature request related to a problem? Please describe.

Bastion fort is an obvious base locale and the z0 walls should have rooms in them.

### Solution you would like.

Just putting this here as a reminder to myself, if anyone else has suggestions pertaining to the fort though happily chime in below ^-^

### Describe alternatives you have considered.

Being upset that NY isn't in New England so I can't add a globally unique liberty island

**Comment by Kywi001** [comment]
This would have issues on how waves are spawned depending on your position, unless if they can make it so the monster waves spawns only on certain locations

**Comment by Procyonae** [comment]
That's fair I haven't tried the new defence mode yet
