### ISSUE TITLE
[Sky Island] Warp Home warps to where I saved instead of the island

### ISSUE THREAD

**Issue by 6DollarSuit** [CleverRaven/Cataclysm-DDA#67704]
### Describe the bug

After reloading a save where I was on an expedition, the difficulty selector popped up. After re-selecting a difficulty (no other way to close it), the warp home spell only warps me back to the square I saved on. The warp timer also isn't showing anymore, as if I was on the island, but I'm not, I'm in a random field.

### Attach save file

[Coldstream-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12358775/Coldstream-trimmed.tar.gz)

### Steps to reproduce

1. Load the save (and optionally walk a few steps away)
2. Attempt to warp home
3. Observe that you were not warped to the island, and instead were warped to the square you loaded on

### Expected behavior

the "warp home" cheat would warp the player back to the island as it normally would, and that when on an expedition the player would have the warp timer

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/36578094/667dfc1f-447c-44b7-861a-346b960ef579)
The popup window appearing on load

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/36578094/8c2a7180-adf1-433c-ac8b-94e137c62a38)
No warp timer, despite being on an expedition

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 24b09f4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Mare-expectantem** [comment]
I had the same problem with the return statues after I quicksaved and closed the Program.

**Comment by GuardianDll** [comment]
should be fixed by ****
