### ISSUE TITLE
dried beans converted to bean seeds sextuple in size.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67700]
### Describe the bug

A dried bean is 0.04 L. Bean seeds are 0.25 L. They're convertible 1 to 1. I know there was a recent fix to bean/seed conversion, perhaps this wasn't caught then?

### Attach save file

N/A

### Steps to reproduce

Look at dried beans and bean seeds.

### Expected behavior

I'd expect them to be of equivalent volume, probably the 0.04 L number.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 3efd67a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Procyonae** [comment]
I think the seeds are meant to be multiple so the issue would be the 1 to 1 not the volume

**Comment by fairyarmadillo** [comment]
All "handful" items, including all seeds, grains, small fruits (ie strawberries) are supposed to be uniformly 250ml. The PR that removed charges from items erroneously reverted this.

**Comment by fairyarmadillo** [comment]
> > I think the seeds are meant to be multiple so the issue would be the 1 to 1 not the volume
> 
> This is incorrect. "Dried beans" is a cup of beans, "bean seeds" is also a cup of beans, they are literally the same object, and the conversion is meant to be 1:1. The only reason "bean seeds" exist at all as an item is for sorting and zone work.
> 
> All "handful" items, including all seeds, grains, small fruits (ie strawberries) are supposed to be uniformly 250ml. The PR that removed charges from items erroneously reverted this.

On further review, the discrepancy is a little bit weirder than that. 250ml is the basic assumption for handfuls of things, but for some items (dried beans being one of them), the volume needs to be a bit lower, as 250ml is like 700 kcal which is inconvenient for portioning now that we don't have charges.

So basically beans and bean seeds need to be 1:1 but they should both be like 125ml.
