### ISSUE TITLE
Enemies can occupy the same space as the player

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#67709]
### Describe the bug

Using either the shipwrecker spell from Magiclysm and the far hand power from Mind Over Matter, it is possible to make an enemy stand in the same space as the player. You can also make enemies stand on walls with force shove, but that might be intended. This will be resolved the next game turn, but the first time that it happened to me, I worried for a split second that I might have just gotten telefragged. I also haven't seen any other times that two entities occupy the same space, which also makes this feel like it isn't intended.

I assume this is something wrong with directed_push or possibly area_push (which seems to just use directed_push). It would also be nice if similar to how bullets are shown moving their trajectory if when enemies are pushed their full travel was shown, so it is more clear where an enemy goes when moved.

### Attach save file

NA

### Steps to reproduce

1. Give player either shipwrecker or far hand spells from Magiclysm and Mind Over Matter
2. Use the spell a few times when near zombies or other hostiles (I haven't tested with other entities)
3. Observe that sometimes zombies will teleport into your tile.

### Expected behavior

Enemies are thrown next to the player if anywhere

### Screenshots

I will get some when I get back to my computer

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-3439-gc5ecac002f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

I am away from my computer at the moment so my version is from an older bug report, but I had the bug happen back then too. I also know that in my versions/configuration section it doesn't include the MOM mod, but I added that mod after and then had the bug happen.

This bug has been happening for a while, but it has seemed like it could possibly be intended behavior, so I didn't report until now.

**Comment by Brambor** [comment]
Should have been closed by merging #68590

**Comment by Brambor** [comment]
@Maleclypse could you close this as completed since you merged #68590 ?
