### ISSUE TITLE
Taking a photograph out of wallet then putting it back in causes a game crash

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#67728]
### Describe the bug

I took a photograph out of wallet while on a pulped zombie corpse with advanced inventory manager and my game crashed.

I placed MY backpack on the ground and repeated the process and my game crashed.

I pulled the ZOMBIES backpack and placed it on the ground and repeated the process but the game did not crash.

### Attach save file

[South Garcia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12370928/South.Garcia-trimmed.tar.gz)

### Steps to reproduce

1. Load Save.
2. Open Advanced inventory manager. (It is already has wallet opened on left.)
3. Take photograph out of wallet.
4. Place photograph back in wallet.

### Expected behavior

For the game to not crash when I place the photograph back in the wallet, it does not do it when the backpack is taken off of the zombie corpse, only when it is left on the corpse.

### Versions and configuration

Windows 10
cdda-windows-tiles-sounds-x64-2023-08-17-0556
Tiles MSXotto
English
Mods in picture. 
![Screenshot (9)](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/6db51350-9194-4a22-aace-83ff40f11a60)

### Additional context

[Crash logs (with save).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12371072/Crash.logs.with.save.zip)

Edit: Because I am dumb and only gave the save file and not the whole folder originally.

**Comment by Zireael07** [comment]
Did the crash stop, since you closed the report?

**Comment by Fox-Ball** [comment]
> Did the crash stop, since you closed the report?

No, it was more than just the wallet. I opened another issue explaining how it effects every container and not just specifically the wallet and photograph as I thought I did. 

https://github.com/CleverRaven/Cataclysm-DDA/issues/67949
