### ISSUE TITLE
Incorrect Part Shapes for Prison Bus

### ISSUE THREAD

**Issue by kylesjob** [CleverRaven/Cataclysm-DDA#67722]
### Describe the bug

The reinforced windshields and heavy duty door on the prison bus are in an incorrect orientation for tilesets.

### Attach save file

N/A

### Steps to reproduce

1. Enter any world.
2. Spawn a Prison bus via the debug menu.

### Expected behavior

I expected the windshields and door to be in the correct orientation.

### Screenshots

Current Bus:
![Screenshot_40](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/17c7fda5-25d5-4659-8391-e787e40ab5b2)

What it should look like after changing parts to correct orientation.
![Screenshot_41](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/7f19d578-b762-4546-a59c-8b795fb72214)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.2295 (21H2)
- Game Version: 73e0659 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Part Shapes for the 2nd image are 

Reinforced Windshields: Right Vertical
Heavy-Duty Door: Full Right Vertical

**Comment by SnowCritter** [comment]
Confirming this issue in my game as well.
![tileset error confirmation](https://github.com/CleverRaven/Cataclysm-DDA/assets/143063823/c4f1e163-656b-414a-b002-12a5cdae35fd)
