### ISSUE TITLE
Heavy crowbars can't fit in spear straps when they're supposed to.

### ISSUE THREAD

**Issue by sergeirocks100** [CleverRaven/Cataclysm-DDA#67721]
### Describe the bug

You can't carry heavy crowbars in spear straps, despite them having the SHEATH_SPEAR flag.

This is because the heavy crowbar, despite having the necessary flag to go inside a spear strap, is about 13 pounds/6 kilograms, while the maximum carry weight of a spear strap is lower, meaning that it won't fit inside.

I've thought of 3 possible fixes:
1. Increasing the maximum carry weight of the spear strap.
2. Adding in some sort of "heavy-duty" spear strap with a higher maximum carry weight.
3. Removing the SHEATH-SPEAR flag from the heavy crowbar, since it's not going to fit inside a spear strap anyways, and the item info suggesting that it can could cause confusion.

### Attach save file

N/A

### Steps to reproduce

1. Try to put a heavy crowbar in a spear strap.
2. Discover that it won't fit, no matter how hard you try.

### Expected behavior

I expected the heavy crowbar to go inside the spear strap, because the item info says it can fit inside spear straps.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.592 (1909)
- Game Version: f7061f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ampersand55** [comment]
It says "this item can attach to a spear strap of appropriate size", but there aren't any spear straps that can handle items over 4 kg, or indeed any other spear straps apart from the standard "spear strap". 

Though I agree it's confusing.
