### ISSUE TITLE
Make ranged weapon aim modes correspond to hit chance.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67731]
### Is your feature request related to a problem? Please describe.

When using ranged weapons you usually want to hit a certain hit chance threshold and spam a keyboard key rather than to have to choose aim mode that would give a good hit chance. Especially when facing a large number of enemies. 

### Solution you would like.

I would like the aim modes to be something like:

1.    Quick aim - As fast as you can shoot.
2.    Regular aim - Guaranteed non-miss, i.e. great, normal or grazing hit.
3.    Careful aim - Guaranteed great or normal hit.
4.    Precise aim - As good hit percentage as you can get.

### Additional context

#67727

**Comment by fairyarmadillo** [comment]
Hits are not guaranteed and never should be.

**Comment by ampersand55** [comment]
Isn't 0 % probability to miss the same as a guaranteed hit? Then what does the aiming numbers mean? 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/9d964b3f-4025-4707-9a5d-10f3a77470b9)

I debug spawned a RM298 HMG and fired ~100 rounds at a debug monster with 0 % miss (33% great and 67% normal hit chance) and I didn't miss once. So even if the aiming numbers aren't correct they seem to be extremely close to the actual hit chances. 

Lets imagine a scenario where my suggestions would would be useful:

You find yourself holding the ground with a bunch of different monsters running towards you, and you want to have "0 % miss" to better conserve ammo. There are three monsters running towards you.

* First monster you kill at long range with precise aim.
* Second monster you kill at medium range with careful aim.
* Third monster you kill at close range with regular aim.

If you used precise aim on every shot killing the second and third monster would have been to slow and they would have caught up to you, and if you used regular aim on every shot you would have missed most shorts at long range and wouldn't have enough time to kill every monster as they simultaneously got close. 

But if e.g. "careful aim" corresponded to the minimum aim time for "0 % miss" you wouldn't have had to switch between aim modes and could have just spammed the same button in much the same way a close combat character can spam <TAB> when facing multiple monsters. It would be a nice QoL.

**Comment by ampersand55** [comment]
> But there is no Guaranteed hit per se, isn't it? Isn't Precise aim a good example why Regular and Careful aim may not be guaranteed hit? Due to dispersion on long range you may never reach 0% miss threshold regarless of how many movement points you spent.

> Unless you mean Regular aim should also wait till your target move towards you enough. But what if target is moving away from you? What if target is fleeing or just distracted?

If you can't reach the target great/good/grazing hit chance for the aim modes, just have them be as high as you can get them.

> Is this feature actually QoL upgrade is debatable. Like often I find 75% chance to hit good enough if it prevents target moving closer to me. Let me chose how much risk I am willing to take as it is my tactical decision. I get player since certain advancement level may consider ranged tab-to-win a QoL improvement, but I think it is balance issue of late game, not issue with targetting system.

You could still fine tune your aiming chances using the wait button in a tactical situation. The aim levels are just arbitrary short hands anyway, so why not have them be as useful as possible? 

Currently I imagine most people basically only lazily use precise aim all the time as it's almost always the best option unless you've been overrun and monsters are uncomfortably close. 

Adding more useful aim shorthands would open up for more player decision making as more aim modes would become viable to use. You could use precise aim against kevlar hulks hoping to get a crit to penetrate armor better, careful aim against most zombies and regular shot against low hp monsters or heavily injured monsters when even a grazing hit would kill them.

**Comment by Nattfarinn** [comment]
> If you can't reach the target great/good/grazing hit chance for the aim modes, just have them be as high as you can get them.

But it means on long range it would be Quickshot or Whatever because Regular, Careful and Precise would do the same thing: get them as high as possible. If you can't reach 0% miss threshold on grazing hit, you won't reach it on any other anyway, right?

**Comment by ampersand55** [comment]
Yes, in those cases Regular, Careful and Precise would do the same thing. 

When every aim mode has a low hit chance there's no need to have several different shorthand options as you would almost always either not shoot or use the one with the highest hit chance.
