### ISSUE TITLE
Allow NPC opinion variables to be used as dialogue conditions

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#67746]
### Is your feature request related to a problem? Please describe.

Currently, we cannot use NPC opinion variables as dialogue conditions as a way to gate something behind them. I figure this could be a creative stumbling block for many contributors working on NPCs, so I thought I'd point it out.

### Solution you would like.

Allow opinion variables to be used as a dialogue conditional check. This would allow EOCs and dialogue to track what the NPC thinks about you more easily and expand their usefulness to most contributors. This could also help avoid complex variable add-remove relationships for someone looking to track that, and simplify the process.

### Describe alternatives you have considered.

Not asking for this at all.

### Additional context

Example:
`"condition": { "opinion": { "trust": 1, "value": 1, "anger": -1 } }`

`{ 
 "text": "Is there anything I can help you with?", 
 "condition": { "opinion": { "trust": 2, "value": 2, "anger": -1 } },
 "topic": "TALK_MISSION_LIST" 
},
{ 
 "text": "Can you tell me about yourself?", 
 "condition": { "opinion": { "trust": 5, "value": 5, "anger": -4 } },
 "topic": "TALK_MISSION_LIST" 
}`

**Comment by I-am-Erk** [comment]
Yeah, it's surprising we can't use these yet actually. We should be able to have them interact with all the dialogue math functions

**Comment by Ramza13** [comment]
These are in fact available.  npc_anger, npc_trust and npc_value should work with u_val.  They aren't documented which I am working on right now.
