### ISSUE TITLE
Wooden wheel mount requirements are unreasonably high

### ISSUE THREAD

**Issue by Nattfarinn** [CleverRaven/Cataclysm-DDA#67743]
### Describe the bug

Wooden wheel mount requirements are on par with ie. rail wheels. `Mechanics: 2` for install and remove, `Mechanics: 3` for repair. Also require `Fabrication: 4` to make while being just a basic contraption made of wood and wire. Compared to next tech tier, light wheel mount, its requirements are way higher (light wheel mount is just `Mechanics: 1`).

### Attach save file

Save unnecessary

### Steps to reproduce

Look at JSONs:
Wooden wheel mount: https://github.com/CleverRaven/Cataclysm-DDA/blob/d8dba8d8c429293d1deae25ff18fe393c85a8261/data/json/vehicleparts/wheel.json#L15-L17
Light wheel mount: https://github.com/CleverRaven/Cataclysm-DDA/blob/d8dba8d8c429293d1deae25ff18fe393c85a8261/data/json/vehicleparts/wheel.json#L44-L46
Recipe: https://github.com/CleverRaven/Cataclysm-DDA/blob/d8dba8d8c429293d1deae25ff18fe393c85a8261/data/json/recipes/recipe_vehicle.json#L797

Links are leading to `d8dba8d8c429293d1deae25ff18fe393c85a8261` as it is latest commit at the moment of writing this issue tagged https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-08-18-0523

### Expected behavior

I expected that basic wooden wheels will be mountable earlier in progression as being low tech compared to other wheel mounts.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I am playing Stable 0.G, but latest experimental also suffers same issue. See `Steps to reproduce` section.

**Comment by oosyrag** [comment]
Low tech does not necessarily mean low skill or knowledge. That said, wheels being designed to be replacable parts means the changing the wheel shouldn't be too difficult. Not that 2 skill is particularly high.

As for fabrication, maybe wooden wheels aren't as simple as you think they are. https://youtu.be/XkUO2tUfqLg

**Comment by Nattfarinn** [comment]
Wow. I'm done. :P
