### ISSUE TITLE
Joint Torsion Ratchet CBM does not hamper movement when active

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#67748]
### Describe the bug

When active, the Joint Torsion Ratchet CBM does not hamper movement like it says it does. Both my speed and movement costs remain the same regardless of whether it is active or not. Power generation increases when active as normal.

### Attach save file

[Rib Mountain-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12380746/Rib.Mountain-trimmed.tar.gz)

### Steps to reproduce

1. Install Joint Torsion Ratchet CBM.
2. Check movement costs with CBM toggled on and off.

### Expected behavior

The CBM should increase movement costs when toggled to generate more power.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: f7061f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by TealcOneill** [comment]
@GuardianDll I ran back and forth over the same patch of pavement several times. With Joint Torsion Ratchet off movement cost didn't increase, with it on and power at or above fuel saving percentage movement cost didn't increase, with it on and power below fuel saving percentage movement cost increased over time with no seen limit.
Speed didn't change in any case.

**Comment by GuardianDll** [comment]
Agreed, can't find any place in the game where the effect could be applied
I'll fix it later, i have an idea how to make it

**Comment by GuardianDll** [comment]
oh, do you mean it works as it should, as turning it off have a little penalty, and activating it increases the penalty? my brain is still foggy, sorry about that

**Comment by TealcOneill** [comment]
😃 All good! When off there's no penalty, when on and generating power there's a small but increasing penalty.

**Comment by GuardianDll** [comment]
Good for me
Thank you for this
