### ISSUE TITLE
[Mind Over Matter] Instruction Unclear, Lifting Field Is Mediated A Thousand Times

### ISSUE THREAD

**Issue by VoidForge** [CleverRaven/Cataclysm-DDA#67749]
### Is your feature request related to a problem? Please describe.

Currently, the description of telekinesis' contemplation: lifting field recipe does not precisely describe what it does. An unsuspecting player (such as me) might believe that working on this recipe on its own improves lifting field power, while in fact according to #66612 it only updates the lifting field according to the highest level of telekinetic power.

### Solution you would like.

A clearer description on what contemplation actually does.

### Describe alternatives you have considered.

Leave it as it is, because other players aren't as dumb as me.

### Additional context

Experimental Build 2023-08-17-0804

**Comment by VoidForge** [comment]
Solved by #67753.

**Comment by Ballz2ThaWallz** [comment]
My lifting feild is eating my bags I had in them I lost a +2 sword....
