### ISSUE TITLE
Game does not throw out errors if item category is invalid

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67751]
### Describe the bug

what it says on the tin, change some item's category to gibberish (like clay urn) and watch as it doesn't do anything?
the game AFAIK uses the item type as fallback, or throws it into the OTHER category.
### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

throw out error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 0f98415 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by ZhilkinSerg** [comment]
Are there any issues caused by this?

**Comment by Devengel** [comment]
> Are there any issues caused by this?

i forgot to update the issue, but there is a fallback in-case category is invalid, it uses the item type or throws it into OTHER category. still would be nice if there was an error though.
