### ISSUE TITLE
Stop Closing Game Start Date Issues

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#67759]
### Describe the bug

Recent changes removed the option to set a manual start time//date for the game.  We now only have a randomized option or we have to set it manually by editing files.  Removing a feature to add a randomized version without explanation for why it was removed IS a valid issue.  Telling players that if you want to do a very basic thing that has existed in the game for years you have to edit files, that is an issue.  If they're meant to be forced random then why allow us to use the 'default'?  And if they're meant to allow for player freedom, why would you remove the option to set one manually?  And saying "just debug it" or "go edit files" is not an answer, as the majority of players don't know how to do those things.

As far as I have seen, there is no explanation for why it was removed -- if it was a conflict then the *new code* added that conflict.  So it should be resolved as an issue.  Maybe you'd prefer it to be a feature request but it's an issue.  There was no explanation for why this granularity was removed.  The closed issues I saw had no explanation provided, and were simply closed.  That is not a resolution to an issue.

### Attach save file

N/A

### Steps to reproduce

Try to set up a world/start the way you have for at least the last 6 years and observe it no longer works and that you must edit your files or accept completely random start times/dates if you want to play with a non-default.

### Expected behavior

I would expect that adding randomized start dates/times would allow the player to manually input their preference, as they have for the life of the game.  
I would also expect issues not to be closed without any explanation of why.  #67590 was closed as a duplicate (it was not a duplicate) despite being a valid issue.  No explanation was given.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 8c55459 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by 6DollarSuit** [comment]
Seconding that the randomizer with no way to manually input a date is very strange and much less useful than before. All the other instances of optional randomization in character creation are also editable (character name, character height, etc), so at first I thought I was just unable to find the right key to edit it.

**Comment by Zireael07** [comment]
@ZhilkinSerg please provide an explanation instead of closing a third issue without explanation...

**Comment by fairyarmadillo** [comment]
At this point it looks like the issues are being closed out of spite.

**Comment by ZhilkinSerg** [comment]
> @ZhilkinSerg please provide an explanation instead of closing a third issue without explanation...

It is a duplicate of #67674.
