### ISSUE TITLE
Item Tags

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#67760]
### Is your feature request related to a problem? Please describe.

Have you ever been looking for lab journals but can't remember the three different keywords you have to filter by to have them show up in the V menu? Have you ever wanted to sort your items so all your spear weapons are sorted to next to the door even if they don't have spear in the name? Have you ever wanted to automatically pick up any medicine items without adding 20 things to your autopickup menu? If so then item tags may be for you.

### Solution you would like.

Items tags would allow for developers to tag their items with words like magic, tank, wearable, nether corpse, mutagen sample, lab notes, knife, explosive, battery, fluid, covers hands, eye armor, battery operated, gluten free, car power generation, exodii, laser guns, and many more! These tags could be manually applied to items or generated automagically from flags and json traits. 

Tags could then be used for things like searching for items, autopickup, sorting. They wouldn't have any mechanical implications, that would still be handled by flags, but This could also help solve things like should backpacks be containers or clothing.

Pros: Easier items searches, sorting, autopickup
Cons: Extra overhead for item creation, another system to maintain, longer game initialization(?)

### Describe alternatives you have considered.

Adding a way to search for item flags and add flavor flags that have no mechanical cpp purpose.

### Additional context

This would be a long term project and would probably have a **lot** of overhead. Any suggestions, use cases, issues would be appreciated.

**Comment by ZhilkinSerg** [comment]
Kinda relevant forum post - https://discourse.cataclysmdda.org/t/mods-and-respect-setting-parameter/20084

**Comment by ZhilkinSerg** [comment]
Issue with categorization is there is no end to it.

Let's take an apple as an example - it can have following tags:

- small
- light
- solid
- dense as a water
- round
- edible
- green
- yellow
- red
- fruit
- has seeds
- has vitamins

We can continue the list for a long time for each item until memory runs out trying to chug all these tags while loading the game. Where should we stop and say "That is enough item tags"?

**Comment by ilovehans10** [comment]
> * small
> 
> * light
> 
> * solid
> 
> * dense as a water
> 
> * round
> 
> * edible
> 
> * green
> 
> * yellow
> 
> * red
> 
> * fruit
> 
> * has seeds
> 
> * has vitamins

I agree that the sheer volume of tags would be difficult, but over half of these tags (small, light, dense as water, edible, fruit, has seeds, has vitamins) can be automatically from JSON information, or a script tied to the Makefile. Yes, some of the things like the color and shape would have to be added manually, but that isn't hardly as much overhead.

I also agree that finding the "right amount" of tags is going to be very difficult, but I haven't worked with the codebase as much as a lot of people here, so I wanted to get some other opinions about this sort of thing.

The point about the memory hit is a very good point, and I am unsure of how that would be mitigated other than keeping the tag associations in a temporary file. I guess there is also the option of tags like "activatable" not even being attached to items, but instead when autopickup is trying to decide which items to pick up it just checks if the item can be activated.
