### ISSUE TITLE
Climbing up broken stairs puts you in the air.

### ISSUE THREAD

**Issue by Syler1984** [CleverRaven/Cataclysm-DDA#67767]
### Describe the bug

Ground floor level section of staircases is broken, bottom one is intact. Trying to climb from the bottom up will put you in unsafe location causing immediate fall.

### Attach save file

Save file with survivor close to the broken stairs.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12385234/save.zip)

### Steps to reproduce

1. Make any character.
2. Go to someplace with a basement.
3. Map edit ground floor stairceses into empty spaces.
4. Climb down.
5. Climb up and fall.

Removing basement stairs fixes the problem allowing to climb up again.

You can also load my save file to reproduce.

### Expected behavior

Character climbs onto a safe tile, just like with normal climbing.

### Versions and configuration

Windows 11
Version: e085fc6
No mods.

**Comment by Syler1984** [comment]
Btw how can zombies even break staircase down? My character refuses to smash it.

**Comment by angryisosceles** [comment]
I have encountered this as well in version 3efd67a.
