### ISSUE TITLE
Autonomous guns can fire through ballistic glass without damaging it.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67776]
### Describe the bug

Entering the trans-coast logistics facility, I saw a M249 autonomous CROWS II on the other side of ballistic glass. Thinking I was safe, I walked out, still behind the glass, and got shot. The glass is unharmed, somehow. 

### Attach save file

[Langes Corners-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12386498/Langes.Corners-trimmed.tar.gz)

### Steps to reproduce

Enter the trans-coast logistics facility, see a M249 autonomous CROWS II on the other side of ballistic glass. Walked out, still behind the glass, and get shot. The glass is unharmed, somehow. 

### Expected behavior

I expect that the glass would defend me until it broke. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/aa8bd68a-094f-45fb-af5e-4920032961da)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 24b09f4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by fairyarmadillo** [comment]
Not a bug. Ballistic glass is coded to allow some bullets through but reduce their damage to simulate the bullets punching small holes through the material but not shattering it completely. Furthermore it can and will eventually break depending on the caliber being fired through it.

**Comment by fairyarmadillo** [comment]
https://youtu.be/Mt2mzCBnEXg?t=147

Here's an example of how that looks in real life.

**Comment by MrHrulgin** [comment]
I learned something new. Thank you, folks.
