### ISSUE TITLE
[Suggestion] Add way to scroll on stats screen.

### ISSUE THREAD

**Issue by Theawesomeboophis** [CleverRaven/Cataclysm-DDA#67777]
### Is your feature request related to a problem? Please describe.

Now that stats display descriptive effects on game play now and the fact that I play on a Chromebook most of the time nowadays an issue became apparent to me, there is no way to scroll the stats screen. This is not a huge issue, but when you have a smaller screen such as my Chromebook or phone, there's a cutoff by the screen which you can't see past.

### Solution you would like.

I would like to be able to scroll the info on the stats screen like you can with the profession and scenario tabs.

**Comment by Brambor** [comment]
I'm assuming you are talking about this (red rectangle) description being non-scrollable when EFFECTS (red arrow) are selected, as demonstrated by text running off.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/7331cfe8-b6d9-4e9b-9320-9e4abe30d149)

_Please include this screenshot next time your self for clarity ;)_


However, the same menu is scrollable when ENCUMBRANCE AND WARMTH are selected, demonstrated bellow.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/a972e9c3-ae11-482f-a7e7-9f640e215c04)

**Comment by Theawesomeboophis** [comment]
No, I mean the stats tab during character creation.

**Comment by Brambor** [comment]
So I worked on my thing #67847
Sorry, this message is unrelated, I am just closing what I opened here

**Comment by Brambor** [comment]
Relevant screenshots:
STATS
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/75498860-4c98-4d42-8c8a-a05f54d5fbf4)
TRAITS
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/0a8664ee-1cf5-4101-8612-03ae3c9bc155)
DESCRIPTION
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/948037d4-33c4-4060-a596-05af95b52b8f)
