### ISSUE TITLE
[Gameplay Issue] Clothing stores don't have materials or tools

### ISSUE THREAD

**Issue by angryisosceles** [CleverRaven/Cataclysm-DDA#67782]
### Is your feature request related to a problem? Please describe.

There are multiple variations of clothing stores, but not all of them include materials (e.g. buttons, zippers, etc) or tools (e.g. scissors, sewing kits, tailoring kits). It makes sense that not every clothing store would have all kinds of items, but it doesn't seem realistic that they wouldn't even have a basic sewing kit to make alterations.

Additionally, this complicates scavenging - seeing a clothing store on a map, fighting your way to it, and looting it to get the tailoring kit you need is a cool story, whereas seeing a clothing store on a map, fighting your way to it, and discovering that they exclusively sell wedding dresses which they apparently do not alter is a bit frustrating.

### Solution you would like.

Add loot from "SUS_tailoring_tool_drawer", "SUS_tailoring_materials", and similar to all (or most) clothing store variants

### Describe alternatives you have considered.

If balance is a concern, stores could include "weaker" items - e.g. scissors and needles rather than full-on tailoring kits, and simpler materials like cloth patches rather than fasteners and such.

**Comment by Zireael07** [comment]
Most clothing stores in Europe do NOT have anything like this, scissors maybe, but not needles because they just sell ready garments, they don't sew and their employees don't know how to sew, they are just saleswomen

**Comment by fairyarmadillo** [comment]
I have worked in a lot of retail clothing stores and many don't even have a basic needle and thread to reattach buttons.
