### ISSUE TITLE
Road Sign Armor

### ISSUE THREAD

**Issue by kylesjob** [CleverRaven/Cataclysm-DDA#67799]
### Is your feature request related to a problem? Please describe.

I started my first knight playthrough and made some survivor clothes to serve as my protective underwear basically, and went to making some early game armor. My first thought was some road sign armor, as I've played the game Rust before, and because of that, road sign is usually the first thing i think of whenever makeshift armor is mentioned. 
However, there is no road sign armor.
I searched the feature requests for this, and didn't find any.
Probably because real road signs aren't in game yet.

### Solution you would like.

Add road sign armor. 

Potentially 2 variants? Below are 2 variants from the game Rust.
One is an older version, and the other is the newer variant.
My idea for them:
The older one can be used as a shoddily made version that's quite encumbersome, and makes a good bit of noise when walking around as it's basically a shitty bandolier with signs stuck on.
The newer one, however, can have slightly less encumbrance and doesn't have the sound penalty as the signs are carefully hammered into shape and strapped to your body with care.

### Describe alternatives you have considered.

Could probably just skip the shoddy version altogether.

### Additional context

Makeshift Variant:
![Screenshot_49](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/4b5b39f4-277a-45d3-bbd4-21d5248c07c6)

Proper Variant:
![Screenshot_50](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/b86e2b51-36a2-48e9-ade1-dd3cceaf1f97)

Here's some photos from some guys on Reddit that I found on Google Images, to show that it's doable.

![Screenshot_51](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/69a6b584-1dac-4ab7-b7a8-5a64db492d2f)

![Screenshot_52](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/ef09c5e8-d05e-4d39-8d04-7506326e63dd)

![Screenshot_53](https://github.com/CleverRaven/Cataclysm-DDA/assets/53407950/0e8af956-ccbe-4e7b-a835-be2d1bbfc2a3)

**Comment by GuardianDll** [comment]
At first, we don't even have road signs still, somehow
At second, even if they would be here, they would just disassemble into metal pipes and sheet of metal, and we already have hand-made scrap armor in game. We don't have capability to allow player make armor specifically from road signs, and you probably don't want to harvest two dozen of them to just get below average protection with awful coverage

**Comment by Karol1223** [comment]
> We don't have capability to allow player make armor specifically from road signs

I'd argue we do, actually, via variant crafting (road sign armor would just be variant of sheet metal armor regardless). But it'd take adding new items specifically you get from disassembling road signs which I'm meh on

**Comment by anoobindisguise** [comment]
The armored leather jacket and vest are like this. It's sheet metal sewn into leather, you can pretend it's road signs if you want since it's literally just any scrap sheet metal whether that's from a fridge or something else.
