### ISSUE TITLE
Defense Mode: some issues/missing stuffs with Merchants

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#67793]
### Describe the bug

1. missing some item categories to sell, such as: vehicle parts, some more tools, shotguns and it's ammo type, bow, crossbow and their ammo types, some more clothing and armors selections (They really need to sell merch so you can save up for the next time they spawn if they didn't have what you need, as well as clean up/convert extra stuffs you dont need into merch)
2. Selling some items with a fixed number, such as melee weapons that also includes katanas, mace, etc. (and it's usually 7 pieces of each type).
3. Would be nice if theyre selling less items, mostly the guns and melee weapons. (the ammo are fine as is, as monster count really ramp up the longer you survive)
4. Merchants should be invisible to monsters and ignore monsters, since these merchants have an absurb strength, they break your walls in order to shoot monsters.
5. Add a special Merchant that sells Hub01 and Exodii stuffs along with the regular merchant inventory as a very rare spawn.
6. They spawn in and reload all the guns in thwir inventory, making the game kinda, slow, until they fully reload every gun. (Idk if it's possible to make the guns load in with full ammo)

### Attach save file

N/A

### Steps to reproduce

1. Spawn several merchant via EOC
2. Check their wares

### Expected behavior

Merchant should sell shotgun, bow, crossbow and their ammo types.
Should sell some more tools.
Should have more variety and rarity to their wares as a lot of the items are guaranteed to be always there while the others are guaranteed to never spawn.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: b18fdcc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Defense Mode [defense_mode],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Magiclysm [magiclysm]
]

**Comment by MNG-cataclysm** [comment]
Fixed by #67822, I think it should be closed. @Maleclypse

**Comment by NetSysFire** [comment]
Closing as fixed.
