### ISSUE TITLE
Setting game start date to 30-35 years makes the game extremely laggy

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67790]
### Describe the bug
[rewording issue as previously the other issues weren't really bugs]

Title, the comment by ZhilkinSerg below states the bug is caused by item rot and weather calculations

### Attach save file

N/A

### Steps to reproduce

start a new world
set GAME START DATE to 30-35 years
go to city and see that it becomes unbearably laggy

### Expected behavior

minimal lag? i don't know, this is an extreme case. so it's likely not gonna get fixed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 7f91d0c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Innawood [innawood],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by ZhilkinSerg** [comment]
A. I cannot reproduce A. Need specific reproduce steps.
B. This is output of standard function to display time point. I assume it is done like that, so time would be displayed using same width for AM/PM representation.
C. It is related to item rot and weather calc:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/b63b0b5d-9a87-4262-a191-dd4bede54031)

**Comment by Devengel** [comment]
A) reproduction, it seems only if you change it from something other than start of cataclysm that it works.

**Comment by ZhilkinSerg** [comment]
Start of game is only locked to be not earlier than start of cataclysm. You should be able to change it to a later date w/o issues.

**Comment by Devengel** [comment]
Noted, reworded the issue and title, thank you for your help

**Comment by ZhilkinSerg** [comment]
Lag must be caused by game trying to calculate item rot in 1 hour intervals since turn zero for each item.

**Comment by Hirmuolio** [comment]
The rot calculations should get done after few turns (max 100 turns I think. The system staggers how many items process per turn). If it lasts longer than that there is a problem.
