### ISSUE TITLE
Compilation error caused by external gcc file

### ISSUE THREAD

**Issue by Fogapod** [CleverRaven/Cataclysm-DDA#67804]
### Describe the bug

Latest master does not compile. Make command is here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cataclysm-dda-git#n47 (i changed make flags to `make PREFIX=/usr RELEASE=1 USE_XDG_DIR=1 LOCALIZE=0 TESTS=0 LTO=1 RUNTESTS=0 LINTJSON=0 ASTYLE=0 PCH=0 TILES=1 SOUND=1`, compiling tests causes a lot of dangling reference errors).

`/usr/include/c++/13.2.1/bits/random.tcc` causing error is owned by gcc package so it cannot be fixed directly but why is compiler trying to lint external libraries? Is there no way to disable that? It would probably save a lot of time too

### Attach save file

N/A

### Steps to reproduce

try installing https://aur.archlinux.org/packages/cataclysm-dda-git

### Expected behavior

Game compiles

### Versions and configuration

Latest Artix linux, gcc (GCC) 13.2.1 20230801

### Additional context

```
In member function ‘operator()’,
    inlined from ‘operator()’ at /usr/include/c++/13.2.1/bits/random.h:3981:27,
    inlined from ‘sample’ at src/distribution.cpp:73:29:
/usr/include/c++/13.2.1/bits/random.tcc:1660:33: error: ‘__x’ may be used uninitialized [-Werror=maybe-uninitialized]
 1660 |                 __reject |= __x + __np >= __thr;
      |                                 ^
/usr/include/c++/13.2.1/bits/random.tcc: In member function ‘sample’:
/usr/include/c++/13.2.1/bits/random.tcc:1577:20: note: ‘__x’ was declared here
 1577 |             double __x;
      |                    ^
lto1: all warnings being treated as errors
make[1]: *** [/tmp/ccuNeFqf.mk:98: /tmp/ccIbI1el.ltrans32.ltrans.o] Error 1
make[1]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/bin/ld.gold: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:956: cataclysm-tiles] Error 1
```

**Comment by andrei8l** [comment]
Not our problem. Double-check your CXXFLAGS and submit a bug report to your distro.

**Comment by Fogapod** [comment]
Does your build system not support only linting 1st party code? (i have no experience with c++)
These errors keep happening again and again. My suggestion is disabling this behavior or at least adding a switch. If this is impossible, this should be closed

**Comment by andrei8l** [comment]
> Does your build system not support only linting 1st party code? (i have no experience with c++) These errors keep happening again and again. My suggestion is disabling this behavior or at least adding a switch. If this is impossible, this should be closed

That's by default but it probably fails because the code is inlined so it's not coming from a system header when diagnostics run during the LTO step. 

This seems to be a new gcc regression because the variable in question is definitely initialized on all paths (possible upstream report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109418).

You can work around it by adding `-Wno-error=maybe-uninitialized` to your CXXFLAGS.
