### ISSUE TITLE
Random crash when driving vehicle

### ISSUE THREAD

**Issue by UltraBigRat** [CleverRaven/Cataclysm-DDA#67805]
### Describe the bug

Was driving a vehicle running  over zombies and had a crash report appear after which the game couldnt be continued and had to be closed. The report is in additional context. Similar crashes have occured to me previously under similar circumstances.

### Attach save file

[Huntingtown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12395935/Huntingtown-trimmed.tar.gz)
This was taken after the crash had already happened, and the game reloaded to last save.

### Steps to reproduce

1. Drive around
2. Run over some zombies for a while
3. Game suddenly crashes

### Expected behavior

The game continuing and not randomly crashing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 73e0659 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12395918/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12395920/debug.log)
 DEBUG    : no display part at mount (1, 3)

 FUNCTION : vpart_display vehicle::get_display_of_tile(const point&, bool, bool, bool, bool) const
 FILE     : src/vehicle_display.cpp
 LINE     : 64
 VERSION  : 73e0659

**Comment by UltraBigRat** [comment]
Noting that after reloading the save and doing similar actions, the same crash occured again.

**Comment by UltraBigRat** [comment]
I will also note that this does happen on other saves aswell (i havent tested other worlds yet however) randomly while driving a vehicle

**Comment by EvanBalster** [comment]
I just encountered a similar issue after parking my damaged car to do some exploring.  My coupe's windshield was broken, exposing the driver's side front wheel beneath.  I was advancing into a previously unexplored neighborhood with some wrecked cars when the issue appeared.  I was looking into the neighborhood.

```
 DEBUG    : no display part at mount (3, -4)

 FUNCTION : get_display_of_tile
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\vehicle_display.cpp
 LINE     : 64
 VERSION  : 13e9e72
```

```
18:16:30.126 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: debug_write_backtrace+0xb5@00007FF796046C75[cataclysm-tiles.exe+0x536c75]), 
  #1
    (dbghelp: DebugLog+0x2b8@00007FF796045A28[cataclysm-tiles.exe+0x535a28]), 
  #2
    (dbghelp: realDebugmsg+0x1fd@00007FF796048CBD[cataclysm-tiles.exe+0x538cbd]), 
  #3
    (dbghelp: vehicle::get_display_of_tile+0xa3@00007FF796CD5893[cataclysm-tiles.exe+0x11c5893]), 
  #4
    (dbghelp: cata_tiles::draw_vpart+0xcd@00007FF7963B5CED[cataclysm-tiles.exe+0x8a5ced]), 
  #5
    (dbghelp: cata_tiles::draw_vpart_no_roof+0x21@00007FF7963B6671[cataclysm-tiles.exe+0x8a6671]), 
  #6
    (dbghelp: cata_tiles::draw+0x252a@00007FF7963AA88A[cataclysm-tiles.exe+0x89a88a]), 
  #7
    (dbghelp: cata_cursesport::curses_drawwindow+0x154@00007FF796032984[cataclysm-tiles.exe+0x522984]), 
  #8
    (dbghelp: game::draw+0x213@00007FF7960A9BC3[cataclysm-tiles.exe+0x599bc3]), 
  #9
    (dbghelp: ui_adaptor::redraw_invalidated+0x3df@00007FF7961B4A2F[cataclysm-tiles.exe+0x6a4a2f]), 
  #10
    (dbghelp: game::look_around+0x1445@00007FF7960CEF65[cataclysm-tiles.exe+0x5bef65]), 
  #11
    (dbghelp: game::look_around+0x95@00007FF7960CFFA5[cataclysm-tiles.exe+0x5bffa5]), 
  #12
    (dbghelp: do_deathcam_action+0x20f@00007FF79666169F[cataclysm-tiles.exe+0xb5169f]), 
  #13
    (dbghelp: game::handle_action+0xa3f@00007FF79666C23F[cataclysm-tiles.exe+0xb5c23f]), 
  #14
    (dbghelp: do_turn+0xeac@00007FF79604E5CC[cataclysm-tiles.exe+0x53e5cc]), 
  #15
    (dbghelp: WinMain+0xc85@00007FF795ED4585[cataclysm-tiles.exe+0x3c4585]), 
  #16
    (dbghelp: __scrt_common_main_seh+0x106@00007FF797520BAA[cataclysm-tiles.exe+0x1a10baa]), 
  #17
    (dbghelp: BaseThreadInitThunk+0x14@00007FFD23007344[KERNEL32.DLL+0x17344]), 
  #18
    (dbghelp: RtlUserThreadStart+0x21@00007FFD244226B1[ntdll.dll+0x526b1]), 
```
