### ISSUE TITLE
Water take too long to boil.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67827]
### Describe the bug

It takes 17 minutes to boil 1 liter of water from room temperature in game, whereas it takes me about 2.5 minutes to do the same in my kettle from tap-cold water.

According to stovetopedia (apparently that's a thing) it takes 10 minutes to boil a liter of water on a 1200 W induction stove and 4 minutes on a 2000 W induction stove. 

https://www.stovepedia.com/blog/induction-wattage-power-consumption/

According to a test it took 4-6 minutes to boil 4 cups of water in a 1000 W microwave:

https://oxbowtavern.com/naan/cooking-tips/how-long-to-microwave-water-to-boil/#How_long_to_microwave_water_to_boil

### Attach save file

N/A

### Steps to reproduce

1. Clean water recipe.

### Expected behavior

I think we should cut down the time it take for all recipes relying on boiling water to somewhere between 25%-50% of their current values.

### Versions and configuration

N/A

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/678ea9f6-de81-477a-b1af-c705fc9812ba)

**Comment by ampersand55** [comment]
Ah. 

Well, I just just make a PR slicing the time of the recipes down to 1/3. But reading the section on food [GAME_BALANCE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md#preparing-food-and-water) it seems that all cooking recipes are part of a system where 1 unit of "water_boiling_heat" (100kJ) takes 5 minutes. 

100kJ / 5 minutes is just 333 W, which is a lot lower power than any kettle, stove or microwave. Perhaps there's has been some error in the calculations because, if I understand it correctly, GAME_BALANCE.md assumes a 1000w microwave having a 80% effective power transfer (i.e. 800W). 

Assuming a modern 1500 W microwave or induction stove at 80% efficiency it would take 0.8 * 100 kJ / 1500 W = 53.33 seconds to boil 1 unit of "water_boiling_heat", or just over 3.5 minutes to boil 1 liter of water which seems more in line with measured real values.

**Comment by GuardianDll** [comment]
This do not solve the problem, as in this case you make water, boiled by bonfire, cook way too fast than it should
also remember, that when we talk about water boilage, we talk not about single recipe, but about all recipes, that boil water to finish it's craft
Just to mention, i'm a fan of #62618 approach, but it require much more work than straight replace values in the json

**Comment by ampersand55** [comment]
What assumptions are we making about cooking with bonfire? According to [this source](https://thegeekycamper.com/boil-water/) it takes 4 to 5 minutes to boil 1 liter of water over a bonfire, which is in line with kitchen methods. Perhaps we could adjust the rate which a fire burns wood to produce desired heat. 

I think the system in [GAME_BALANCE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md#preparing-food-and-water) seems good apart from the apparent error, and we could just adjust any recipes using "water_boiling_heat" with the correct values. 

PS: I'm also a fan of the approaches you linked.

**Comment by anoobindisguise** [comment]
I only really focused on power and not time. But i'd expect to need about 100 g of wood per charge of water (~10% efficiency, 10-20 MJ per kg of wood depending on water content, base 100% efficiency cost of 100 KJ per charge of water)
so to boil a steel jerrycan's worth of water, you'd need like 8-10 kg of wood (3-4 planks)
