### ISSUE TITLE
Phone Calendar Reminders

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#67831]
### Is your feature request related to a problem? Please describe.

In my world, I just recently had Hub 01 start manufacturing my HWP, and I have also started brewing some meal grubs. Both of these processes take a fair amount of time, and because I am forgetful and don't play super frequently, I am worried that I will forget my meal grubs in their keg and have them die on me.

### Solution you would like.

Similar to how an alarm can be set for later in the day, it would be great if on electronic devices it was possible to set a reminder for x days in the future. It would also be nice if there was a way to specify a time of day for the alarm to go off, so I could have an alarm go off at 09:00 when I am getting ready for the day instead of 12:00 when I am trying to sneak through a lab.

### Describe alternatives you have considered.

The option to automatically set a reminder in your phone when doing things like filling a keg or ordering something that will take time.
The ability to tie a message to the reminder, so you know if it is about your tanning pelts or if Rubik just changed his stock.
Putting the ability to set reminders in a cbm like the internal chronometer or maybe internal memory banks.
Some way to make this available for innawoods people like a calendar you can draw in the mud (I know next to nothing about how less technologically advanced civilizations kept track of dates other than stone calendars).

**Comment by MrHrulgin** [comment]
I love this idea. Being able to set timed reminders would be super helpful.

**Comment by a-chancey** [comment]
For now I've been just adding a new diary entry and manually checking it occasionally. 

I absolutely love the idea, as it would simplify keeping track of things so much.

**Comment by ilovehans10** [comment]
> For now I've been just adding a new diary entry and manually checking it occasionally.

This has been my go to so far, but it is very manual and very dependent on me checking the diary (which I hardly ever do). I know very little c++ but I might take a look at it later and see if I can jerry rig something based on the current alarm code.
