### ISSUE TITLE
Reintroduce Mono-Pool

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#67845]
### Is your feature request related to a problem? Please describe.

I for one, would massively appreciate it, if this game reintroduced the old Point-Pool system. It it still possible to enable it in the options, but as far as I can tell only the "Legacy Multipool" one, which gives all of the points you get from choosing a hard scenario only into your pool for skill points, which is subpar. 

### Solution you would like.

Add the Monopool option back into the game. 

### Describe alternatives you have considered.

Tbh the willy-nilly nature of build your own character feels wildly out of place in CDDA. I feel like maybe adding different difficulty options at character creation that determine how many points you would get would be a very good solution and allow for people looking for a tight survival experience as well as people going for a more RPG approach. Would such a feature be doable?

### Additional context

Thanks :)

EDIT: Disregard what I said here: I have tried to really think about it and made another post where I wrote down most of my thoughts. I encourage discussion there :)

**Comment by Fris0uman** [comment]
We're eventually going to remove points entierly, probably after next stable.
