### ISSUE TITLE
Auto-pickup is confused by cold things (conditional naming issues)

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67846]
### Describe the bug

I have an auto-pickup rule to grab cigars, since they're light and sell well. The search string is "cigar" rather than "cigar*" since I don't want "cigar cutter". But when something is cold the name of the item is actually changed, so my pickup rule ignores a "cigar (cold)" because it's not a "cigar". This isn't really ideal.

### Attach save file

N/A

### Steps to reproduce

Set a pickup rule, see it ignore temperature modified variants. 

### Expected behavior

I'd expect that the rule would grab an item regardless of temperature.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 2c8ae07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
Not only it's hard to do, we also may have some conditional names, that may vary depending on materials (like cooked meat and cooked human meat have different names), which makes it even harder
