### ISSUE TITLE
Dental grills should be fancy.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67844]
### Is your feature request related to a problem? Please describe.

Why aren't they fancy or very fancy? They're made of precious metals and gems and worn in your face, and pretty much everything else that fits that description is fancy.

### Solution you would like.

Fancy grills.

### Describe alternatives you have considered.

Leave it how it is, though I'd be interested in hearing an explanation for exactly why grills don't count as fancy when other decorative items made from similar materials do count.

**Comment by ZhilkinSerg** [comment]
I would love if each character had its own taste and considered different things FANCY.

**Comment by MrHrulgin** [comment]
Agreed. Rather than the tuxedo and fancy dress being the presumed fancy outfit for everyone, having a diversity of outfits that counted depending on the character would be great.

**Comment by Fris0uman** [comment]
The current guidline for fancy is "Is it appropriate for a fancy dinner". Basically tuxedo and fancy dresses, definitly not dental grills.

**Comment by MrHrulgin** [comment]
But that's not the mechanical effect nor based on the description of Stylish, the trait that interacts with the Fancy tag. Stylish just says: "Practicality is far less important than style. Your morale is improved by wearing fashionable and attractive clothing." For you to say that "appropriate for a fancy dinner" is the only way to be dressed fashionably and attractively is assuming a remarkable degree of cultural homogeneity that really doesn't exist in New England. Plenty of people wear fashionable and attractive clothing that isn't "dinner party".

Besides, there's plenty of existing fancy items that don't really fall into that description. Tiaras and golden crowns are not appropriate for a fancy dinner, nor the short santa dress or the sleeveless faux fur duster/trenchcoat, or the H&K operational briefcase, or the leather corset, or the expensive flip-flops, or the tricorne... Looking at the whole list of fancy items, I'm seeing plenty of things that don't fit within that description.
