### ISSUE TITLE
Unable to swap gender in character creation using @ on the "Scenario" tab.

### ISSUE THREAD

**Issue by SnowCritter** [CleverRaven/Cataclysm-DDA#67858]
### Describe the bug

Unable to swap gender during character creation screen using the @ key when on the "Scenario" tab. Works fine on other tabs (Profession, Background, Description).

### Attach save file

N/A

### Steps to reproduce

Create a new world on a new version. Tested with defaults and multiple mods setting for worlds (though not exhaustively) and this does not appear to effect the issue.

New Game > Custom Charecter
Tab to Scenario.
Press @ and nothing will happen.

### Expected behavior

Pressing @ should swap the gender of survivor.

### Versions and configuration

**Issue confirmed present across builds:**
windows-tiles-sounds-x64-msvc
build number: 2023-08-23-0315
commit sha: 2ac6a60178f87bd199f6af9a7010c975dfb1dc24

windows-tiles-sounds-x64
build number: 2023-08-24-0401
commit sha: a79e337fa9eaa75498814c2c5782136241efce85

windows-tiles-sounds-x64
build number: 2023-08-23-0132
commit sha: 6ed14bbf5f79e221858ba9a603a9877b68185f9d

[hr]

**Issue not present in older build:**
windows-tiles-sounds-x64-msvc
build number: 2023-08-06-0454
commit sha: 42ca08e779d04d9dcf46276e79af603d95a19574

[hr]

NOT an exhaustive list of builds with this issue, OR the last know build with it functional. These are just the ones I have checked on.

**Comment by ZhilkinSerg** [comment]
Keybinding registration was accidentally removed here - https://github.com/CleverRaven/Cataclysm-DDA/commit/7f91d0c939af79fe38ffd363fedd983b95701a6c#diff-da8a925e8abf39943d87477831cecd3686ad13b250b7bc1c4bd74ffeaaefce34
