### ISSUE TITLE
Cannot give 'NRE anomaly printout' to HUB 01

### ISSUE THREAD

**Issue by turco-ai** [CleverRaven/Cataclysm-DDA#67850]
### Describe the bug

You can't give the printouts to the HUB as the dialogue option does not appear.

I did notice that if you have both the 'NRE Printout' item and the 'NRE anomaly Printout' item in your inventory the dialogue option to turn both in appears, but if you do not have the 'NRE Printout' item it disappears again.

I also noticed that being outside in the storm gives more printouts than being inside the portal dungeon, this also seems unintended as I'd imagine being halfway to another reality would also provide a lot of valuable data.

### Attach save file

N/A

### Steps to reproduce

1. Accept the NRE recorder mission
2. Enter a portal storm dungeon
3. Get anomaly printouts
4. Take them to the Hub
5. Observe you have no option to turn them in

### Expected behavior

To be able to give them the printouts.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 22031116BG; Release: 13; Incremental: V14.0.2.0.TGLMIXM; 
- Game Version: 8c55459 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by turco-ai** [comment]
It seems the conditions in the code for the dialogue to appear list all the NRE printout items except the 'NRE anomaly printout', the fix might be to add the item ID to the dialogue conditions.

**Comment by anoobindisguise** [comment]
Yeah you have to hold a non anomaly printout in inventory to give them anomaly printouts.
