### ISSUE TITLE
Matchhead loads description and red phosphorus crafting byproduct innacurate

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#67853]
### Describe the bug

Matches IRL are primarily potassium chlorate heads and glass with a red phosphorus cardboard stiker on the box

https://en.wikipedia.org/wiki/Match

The striking surface on modern matchboxes is typically composed of 25% powdered [glass](https://en.wikipedia.org/wiki/Glass) or other abrasive material, 50% [red phosphorus](https://en.wikipedia.org/wiki/Red_phosphorus), 5% neutralizer, 4% [carbon black](https://en.wikipedia.org/wiki/Carbon_black), and 16% binder; and the match head is typically composed of 45–55% [potassium chlorate](https://en.wikipedia.org/wiki/Potassium_chlorate), with a little sulfur and starch, a neutralizer (ZnO or CaCO
3), 20–40% of [siliceous](https://en.wikipedia.org/wiki/Silicon_dioxide) filler, [diatomite](https://en.wikipedia.org/wiki/Diatomaceous_earth), and glue.[[39]](https://en.wikipedia.org/wiki/Match#cite_note-39)

This will lead to issue's with the new matchhead loads implementation being inaccurate and potentially misleading for recipes that actually recall for red phosphorus (eg. Recreational drugs, potential production of phosphorus munitions).

### Attach save file

N/A

### Steps to reproduce

Check match load item desc and red phosphorus recipe

### Expected behavior

Allowing matchbox disassembly to produce cardboard a new item of red phosphorus and use for Methamphetamine recipe.

Change recipe byproduct name of matchhead grinding to potassium chlorate and description of matchhead loads should have potassium chlorate rather than red phosphorus

### Versions and configuration

Latest Experimental

**Comment by anoobindisguise** [comment]
Yeah so at some point someone renamed matchhead powder to red phosphorous. The yield is roughly correct (the guy in the reference vid got 1.8ish grains per box iirc) but it may not be pure enough for actual chemistry, while meanwhile actual red phosporous may be too pure for bullets.

**Comment by TheLyca0n** [comment]
The adhesive on the matchbox strips can be dissolved normally with acetone then scraped off to obtain the purity needed for any experiments as the glass powder is normally extremely nonreactive (I use that term loosely to avoid any implication and I don't advise people do this IRL). The chlorates of the matches themselves would honestly be more desirable and economical for improvised munitions, flashpowder in fireworks IRL is literally just aluminum powder and sodium/potassium perchlorate or just normal chlorates
