### ISSUE TITLE
Some rotten fruits and veggies should have craftable seeds.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67857]
### Is your feature request related to a problem? Please describe.

When I find a rotten tomato, it should still be possible to harvest seeds from it. Not all things that can have seeds should be able to be crafted from rotten produce, but for many of them the seeds should still be viable far after it's no longer edible. 

### Solution you would like.

The following items that have craftable seeds should still be able to harvest seeds from the produce after they're rotten, because the seeds are both incorporated into the piece of the plant we transport (like tomatoes) and aren't damaged by the rotting of the food (like corn):

- grapes
- tomato
- zucchini
- eggplant
- cucumber
- blueberry
- cranberry
- raspberry
- elderberry
- watermelon
- blackberry
- strawberry
- huckleberry
- bell pepper
- chili pepper
- bottle gourd
- cantaloupe melon

This isn't all of the plantable fruits, but they're definitely the things where the edible part and seed part are in a single package, and where the seeds are intended to survive the destruction or rotting of the fruit.

### Describe alternatives you have considered.

Leaving it alone. It's a minor thing, mostly ameliorated by finding seed packets.

**Comment by kingjosh-1120** [comment]
Sounds like an interesting feature to add, will try to work on it
