### ISSUE TITLE
Standard base camp cut logs mission returns results in an unexpected place, appearing that it was missing.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#67862]
### Describe the bug

I send my companion off to cut logs in a nearby forest tile. When returning the companion didn't bring any logs and the tile was found to no longer be classified as forest, so I chalked that one up to somehow giving the order to clear forest instead.

However, a new order was given, and when the companion returns no logs are delivered. I don't see any cleared forest, but I'm not 100% sure where I sent the companion, although I think the tile I sent the companion to wasn't cleared.

Edit: I've changed the title of the report and updated it to reflect what the bug actually does.
The log cutting missions do actually produce logs (and twigs and puddles...): they're just delivered to a completely unexpected location, namely inside a doorway inside the house in a location unrelated to relevant zones and the location of the bulletin board, the PC, and the companion.

### Attach save file

[West Kingston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12429044/West.Kingston-trimmed.tar.gz)

### Steps to reproduce

1. Move or teleport straight north to bare bones base camp Alpha.
2. Walk inside the house and to the first room on the south side to find the "missing" logging products. There is also a spill over into the tile to the SE of the doorway.
3. Wait (using the debug menu) for a day or until the companion task is completed whatever you prefer.
4. Access the bulletin board (by the house wall) and verify the companion task completion is marked as "Recover Log Cutter" and that the "Cut Logs" mission is greyed out.
5. Recall the companion.
6. Return to the doorway and see that the spill over tile now has additional logs in it (and you might get a puddle in the doorway as well: don't know if that's repeatable, although it seems to be).

### Expected behavior

Log cutting missions should result in logs etc. being returned to a reasonable location. If I recall correctly the products used to show up at the feet of the returning companion.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 5ebd5af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

Since the companion returns to the overworld tile next to the base camp, I repeated the task after making sure the companion was located in the same overworld tile as the camp itself before issuing the mission. This results in the return of the companion to the same tile as the departure one (no surprise), but with no logs, and this time I also noted that the forest tile was cleared.
Ordered a Clear Forest mission, which was performed (i.e. the forest was cleared after the companion returned, with no logs).
Ordered yet another Cut Logs mission, and this time the tile was NOT cleared, but nor was any logs produced.

Edit:
The location where the logs end up is (13, 15) in the base camp tile. while the bulletin board is at (23, 16). I've tried to debug spawn another bulletin board inside the house and use that to order the companion to cut logs while both the PC and the companion are well inside the bounds of the house/camp, but the results seem to be delivered to the same tile regardless (assuming the addition of piles in surrounding tiles are spill overs). Thus, it doesn't seem that the delivery location is affected by the location of either the PC or the companion.

It's all weird, but I can live with this level of weirdness, but there remains a bug here, which probably is hard to replicate without the save (or at least a theory of why things get weird).

**Comment by Kywi001** [comment]
> Ordered a Clear Forest mission, which was performed (i.e. the forest was cleared after the companion returned, with no logs).

This clears a whole forest and returns 0 logs.

> Ordered yet another Cut Logs mission, and this time the tile was NOT cleared, but nor was any logs produced.

Did you perhaps performed an emergency recall? This would cancel said job.

I'm currently playing on Defense Mode mod, and I used this just a few PR release back (my current build is 2023-08-22-2245), companion returns with Logs properly. Unless they messed up something, somehow

**Comment by PatrikLundell** [comment]
Yes, I know clearing forests doesn't return any logs (hence my initial thought I might somehow given the wrong order). The test was performed just to see that there wasn't somehow a swap of what the commands did. I could have made it clear the result was as expected, though.

I didn't do an emergency recall. I made sure I completed the orders.
