### ISSUE TITLE
Complaint about tracking temperature

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#67861]
### Describe the bug

 DEBUG    : Item insecticide is active and tracking temperature, but it should not!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 3099
 VERSION  : 5ebd5af

### Attach save file

[West Kingston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12428970/West.Kingston-trimmed.tar.gz)

### Steps to reproduce

1. Travel straight north to base camp Alpha (swerving around forest patch). You can also teleport.
2. Get error report when approaching the camp.

### Expected behavior

No error report.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 5ebd5af [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

There is a pile of "stuff" to the west of the fire ring, with one of them being the offending active insecticide item.

This error started appearing when I moved the save from a week old experimental to this one. Before that the insecticide didn't seem to do anything.

**Comment by snipercup** [comment]
I had this issue too 
/confirmed
