### ISSUE TITLE
Atomic coffeemaker requires charges and boiling water uses more power than a electric forge melting metals

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#67863]
### Describe the bug

Current experimental atomic coffeemaker now is unable to boil or make tea/coffee or other liquid's on it's own without other fuel sources, time and electricity requirement's of boiling and making a 2L jug of coffee now not only take's upwards of 3 hour's but also take's more power than a most industrial uses of power eg. forging consumes 240 energy units while boiling a liter of water takes 1000 energy unit's

### Attach save file

NA

### Steps to reproduce

Try to boil any drinks in the latest experimental with and without a grid

### Expected behavior

Either change description of the Atomic coffee to remove it betavoltaic effects (removing a legacy items effect's and meme humor) or restore original free cooking functionality. For balancing either lower the electricity and time consumption on tea's/drinks reasonable fuel consumption or increase the forges requirement's to ridiculous levels.

### Versions and configuration

Latest experimental

**Comment by Karol1223** [comment]
The atomic coffeemaker was remade to be more realistic while retaining some of its original value (at least that's what I believe happened during its rework) and so does indeed use battery charge - it is *slightly* more energy efficient than a normal coffeemaker (for black coffee 115 vs 125 charges to craft)

The forge energy uses are bullshit, it's a known issue. The solution is to make them realistic, not to fictionalize the cooking costs again.

As for time requirements, that's a separate problem of the character having to stare at the tea as it boils... Which is a problem, yeah, but not an easily solvable one.

**Comment by TheLyca0n** [comment]
Ah cool can probably remove this issue then sorry for the repost
