### ISSUE TITLE
[defense mode] achievements for reaching locations in normal playthrough still happen in defense mode

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67875]
### Describe the bug

i got the achievement for reaching a megastore, all i did was start in defense mode, and picked a random location, which happens to be a megastore

### Attach save file

N/A

### Steps to reproduce

1.start new game with no achievements
2.create a new character with defense mode
3.select megastore as starting location

### Expected behavior

not sure if this is intended

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 0a7633f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Defense Mode [defense_mode],
    Blaze Industries [blazeindustries]
]

**Comment by MNG-cataclysm** [comment]
This is intended, I don’t see much of a problem with it for the time being.
