### ISSUE TITLE
Mi-gos should not drop edible meat

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#67874]
### Is your feature request related to a problem? Please describe.

Apparently, mi-go are dropping tainted meat, like zombies do. That's a bug.

### Solution you would like.

We should add:
- mi-go flesh, an inedible meat with no particular use. If we get further into the ability to do research that could change.
- mi-go carapace, which could be broken down into chitin chunks but may later have purpose of its own

We could also add 'mi-go guts', 'alien fibre', and other things for flavour if desired.

### Describe alternatives you have considered.

They could just drop a generic 'alien meat' but mi-go expressly are from a different location than anything else in game.

### Additional context

Mi-go have a different biochemistry from humans and should probably never be edible.
We could make mi-go flesh a passable fuel for fires so that you can destroy your excess.

I'm happy to write any of the flavour text people may want related to butchering migo and describing their items, if someone decides to do this one.

**Comment by PatrikLundell** [comment]
I don't think mi-go carapace should be made out of chitin, but rather a unique material that's tougher than chitin, should it be possible to use it for anything (which doesn't have to be possible).
I also think mi-go ought to have either bones (of a unique material) or an internal scaffolding of a unique nature (which may or may not be the same material as the carapace).
Mi-go tendons might be a possible material with a possible use (probably stronger than animal tendons, but that might not make a difference when used in crafting, but rather result in the normal product).
Mi-go guts and mi-go organs(?) are potential products that might have some potential future research or quest use.

**Comment by fairyarmadillo** [comment]
XEDRA made a mi-go carapace into a ballistic plate because it's made of some kind of self-healing crystalline matter. You can find it (and the still-living mi-go they were vivisecting) in the bottom of TCL.

**Comment by I-am-Erk** [comment]
Correct me if I missed something but I think this was resolved by #69207
