### ISSUE TITLE
[Bombastic Perks] Activating alchemy perks gives successful message regardless of working

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#67888]
### Describe the bug

When activating on of the alchemy perks when it is off cooldown, a message plays that "You learn a new secret of alchemy." This is supposed to give you a new recipe, but sometimes it plays the message without any new recipes being added to the Xedra tab. Just a guess, but it might be randomly selecting from potential recipes and sometimes selects one that has already been learned.

### Attach save file

[West End-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12439230/West.End-trimmed.tar.gz)

### Steps to reproduce

1. Select the "Basic Alchemical Knowledge" perk.
2. Activate it in the mutation menu without the "Mental Exhaustion" effect.
3. See it display the message "You learn a new secret of alchemy." regardless of whether a new recipe is learned.

### Expected behavior

Either the message should be different to indicate not learning a new recipe, or the perk should always grant a new recipe until all for that tier are filled in (there should be a separate message for that). Maybe using a different method of learning recipes that is more clear on what recipe you've just learned, like spawning a written recipe?

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/5776ec42-8c30-476a-b83e-0af10be9c1a4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: f55fb5c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Maleclypse** [comment]
Ok There's two components to this bug.  One the Small Blessing of Brigit is in the wrong category. `"category": "CC_CHEM",
    "subcategory": "CSC_CHEM_DRUGS",` and two this eoc doesn't have the false_effect to tell you that you've maxed out your recipes you can learn at this level.
