### ISSUE TITLE
"Food Delivery" With Free Merchants Broker does not account for new item-stack implementation.

### ISSUE THREAD

**Issue by MattLanduyt** [CleverRaven/Cataclysm-DDA#67882]
### Describe the bug

The "Food Delivery" option with the free merchants broker, who usually gives 1.00$ for each charge (Now item) of dehydrated fruit, appears to not take into account the new stack system for items and the removal of the old  "Charge" based systems, causing larger than one food "stack" to be only counted as one. This can result in stack sizes of over one dehydrated fruit/sugar/etc. stacks being counted as one, among other issues.

### Attach save file

N/A

### Steps to reproduce

1. Go to free merchant broker with more than one item of "Dehydrated fruit" (Or other food items that are applicable, such as sugar)
2. Select "I'm here to deliver some food supplies."
3. Select your chosen foodstuff for trade
4. The merchant should only display one "Batch" of items (regardless of stack size) to be available for trade.
5. Clicking on this will subsequently delete the entire stack from the players inventory, while only giving the payout of one.

### Expected behavior

Foodstuffs should count individual items for each "Batch", rather than each stack of the item being counted as one.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/25002508/9e4cc8d4-a941-4c58-833f-2f96669790a5)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/25002508/a1d863aa-dd0e-4ff8-b749-cfa91284114c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 0a7633f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No name () [],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Mind Over Matter [mindovermatter]
]

**Comment by underwillowtree** [comment]
It seems that all NPC using "topic": "TALK_DELIVER_ASK" are unable to trade normally.
The same bug is occurring on tacoma nurse and magiclysm forgelord.
Whether you give them 1 item or 100 items that cost $0.25 each, they only pay $0.25.
They don't do the math of how many of that item they were given.
