### ISSUE TITLE
Ability to scan multiple amounts of books in one operation on smartphone.

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#67886]
### Is your feature request related to a problem? Please describe.

Why do you need all these clicks for scanning books? Just make them all selectable in one operation.

### Solution you would like.

Well just make saving screen like dropping screen.  Also need to put energy and time consumption at this screen

**Comment by ilovehans10** [comment]
I have briefly looked at implementing this in the past, and I am not certain, but it seems like this should be similar to #65248.
