### ISSUE TITLE
Skippable Error when launching Escape pod from Aftershock crashing space ship

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#67896]
### Describe the bug

 DEBUG    : Tried to use an invalid alpha talker.  Callstack: Spell: escape_pod Caster:  \ EOC: EOC_ESCAPE_POD_CHAIR

 FUNCTION : talker* dialogue::actor(bool) const
 FILE     : src/npctalk.cpp
 LINE     : 2056
 VERSION  : 96260a5

### Attach save file

N/A

### Steps to reproduce

1. Load a world with AFS and use scenario Crashing Ship
2. Go to the escape pod
3. Launch the pod with you in it.
4. See error.

### Expected behavior

No error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 96260a5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by Maleclypse** [comment]
@Drew4484

**Comment by Drew4484** [comment]
> @Drew4484

This was fixed previously, not sure what broke it again. I'll take a look when I can.

**Comment by trentbuck** [comment]
FTR I can reproduce this as at https://github.com/CleverRaven/Cataclysm-DDA/commit/400add923a65d53dd16ffd8110d65eb8d56925d4
