### ISSUE TITLE
Portal storm artifacts get only integer "multiply" values

### ISSUE THREAD

**Issue by paulenka-aleh** [CleverRaven/Cataclysm-DDA#67905]
### Describe the bug

At the moment artifact generation procedure generates only integer "multiply" values. Therefore some of the enchantments never appear: `MOVE_COST`, `ATTACK_SPEED`, `WEAPON_DISPERSION`. Many other can only get value `1.000000`. This might not be noticeable during a normal gameplay, but but limits modding capabilities.

### Attach save file

N/A. Just start a game a generate artifacts if you need one.

### Steps to reproduce

- Start the game.
- Debug an artifact with `"netherum_tunnels"`, choose values `3`, `500`, `-750`. Create many. (or play a while a explore portal storms).
- Explore save files. (or play around with them).

### Expected behavior

 - Initially I assumed that `"increment"` should be taken into account and the result value must give an integer when divided by the increment.
 - If my assumptions are wrong, random float values should appear with the given min and max for `"netherum_tunnels"` (in a similar way it happens to **add** `MAX_STAMINA` enchantment.
 - Or, if only integer values are somehow expected, `"netherum_tunnels"` and other procedures should never list float values in min and max, [docs](https://github.com/CleverRaven/Cataclysm-DDA/blob/ae4082e877f0d172226ad38e7693099b09ea373b/doc/ARTIFACTS.md?plain=1#L35) should be corrected as well. Doesn't make sense to me at all though and keeps modding capabilities low.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.17763.4737 (1809)
- Game Version: ed0ff32 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Innawood [innawood]
]

### Additional context

After looking into the code, I blame this line for the issue: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/relic.cpp#L713 - here float values are passed into `rng` that accepts two integers. Note that as part of the code https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/relic.cpp#L708-L732 increment is never taken into account.

**Comment by RenechCDDA** [comment]
>At the moment artifact generation procedure generates only integer "multiply" values. 

Yes, confirmed, and simple fix (just needs to change `rng` call to `rng_float`. After doing so, I got multiply values that weren't1.000

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/e94e4621-f533-430b-ae60-6c38ae60e3cb)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/7577a4b3-ae96-4210-b668-dd0a863eedf7)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/118fbdcf-9833-4886-8256-3d3acd5fcaf0)


>Therefore some of the enchantments never appear:

I didn't confirm this one way or the other, but while testing with the above fix applied I got an artifact with ATTACK_SPEED of 3.000 which adds a cost 3 extra moves per attack. So this should also be resolved by the simple fix I proposed.
