### ISSUE TITLE
Revamp(remaster?) the "cult", strange cabin and strange temple

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#67916]
### Is your feature request related to a problem? Please describe.

Albeit two of the more interesting locations, strange cabin and strange cabin feels kinda lackluster, underutilized and gimmicky; not to mention they are wildly out of touch with the L O R E. There is no incentive to clear out a strange cabin except for the lulz and and love of a (probably useless) priest npc, and temples are quite rare and kinda too simple. This concept aims to improve them while also adding interesting and new content and fitting them into the game's current design. It also aims to bring back two removed enemies as something different.

Summoning all the lore and gameplay guys.

### Solution you would like.

BACKGROUND
Our story begins with an eccentric zillionaire and a few of his buddies partaking in occult, classic rich people shit. When rumors of reality breaking and otherworldly entities starting to pour in take hold of the general public, our zillionaire raises an eyebrow and weighs in his resources into these rumours to confirm if they are connected to his esoteric beliefs. Soon enough, he receives his confirmation and obtains a strange artifact, that appeared near the center of a "portal storm", before filthy government agencies could find it first. He toys and messes with this artifact for a bit; altough he gets a mildly weird and pleasant sensation, after observing no esoteric stuff he dismisses it as just an odd space rock and continues on his research with a disappointment. However; soon after his inspection, he begins to see wild dreams, all of which end with him consuming human flesh and blood(these are like Alpha dreams, except more sick and twisted). Although he is horrified at first, he gives into his curiosity later and has a homeless person kidnapped. He dissects him and eats him. Thrilled, he decides to turn this into an occasional thing, and forms a cult-like group with other sick, fucked up zillionaires with similar interests(to whom, he grants accses to his precious artifact)in order to supply them more fresh meat. They buy a defunct mine as a front for their meetings and build a temple-like structure full of hazards that only they know how to pass and buy a remote cabin for their "feasts". As world becomes more unstable and busy to investigate their insanity, they lean into their habit more and more, and begin to change. Their skin becomes paler and paler, they grow in size and become leaner, their fingers and nails fuse into claw like appendages, they lobotomize their friends, family and employees to make them into their thralls, they start seing schizophrenic delusions and their hunger only grows(symptoms of their artifact induced mutation). They become inhuman. And when the world finally falls apart at the beggining of our cataclysm, it becomes their oyster, full of helpless and scattered meat.
P.S: These will be disclosed via notes and terminals.

GAMEPLAY
Player will find out about this "cult" either through previously existing NPC quest, stumbling into the strange cabin by chance or reading entries scattered within the mansion(given that they are the weird rich people buildings). Strange cabin will be revamped slightly, wraith might be removed in favor of more human and believable enemy, perhaps more dementias or by reintroducing flesh angels? Rest of the cabin will be untouched except maybe adding a note implying that there is something deeper to this location. Gameplay starts to diverge once the blood sacrifice is killed. Instead of bumfuck nothing happening, player recieves a message that they irritated an entity, a malicious entity. For the next few days they are haunted by disturbing dreams and a sense of being watched, which gives the player a moral penalty. After this timeframe, they will encounter the star of this concept: the homunculus(don't worry, this time they are different.) They are the cult's members who went through forementioned mutations. It will be a mini-miniboss creature maybe aided by dementias or flesh angels(if reintroduced). It will be purely melee, having some nifty cutting damage because of their forementioned claws and will maybe utilize some special attacks like shriek, bio takedown, parrot and leap(or something else entirely). After being killed the morale penalty will cease, and it will drop a petrified eye and a map to the forementioned mine that is a front to the strange temple. This will be mostly empty save for a few security guards since it is defunct. At its finale, there will be the entrance to the temple. Until the final room it will be mostly same(except the puzzle which spawns bug when failed, maybe change them with dementias). The final room will be different however. Instead of the old bland artifact room, player will find here another homunculus(maybe assisted by creatures again), clad in an altered object artifact that is a kitchen apron that restores some health after a succesful crit along with the artifact that previously spawned here. After being defeated it will drop the apron and another artifact, that grants when activated:
[DRUM ROLL]
The Homunculus mutation, very same mutation that changed the cultists. If Alpha is the delusional übermensch that was created in a lab,  homunculus is its malformed cousin that nether created, a strong and swift, yet hideous and cannibalistic creature that lacks the intelligence and (relative)goodwill towards the humanity of the Alpha.

Its primer will be a concoction of human/demihuman blood and human/alpha sample. Recipe will be discovered from a cultist journal that can be found in the mansion or a recycle center(or maybe in cabin/temple).

THE GOOD
-enhanced strength and dexterity (and maybe perception)
-good nightvision
-cannibalism
-Ability to control humans and animals through pheromones or shrieks(idk about this one)
-tough build, less incoming damage
-claws that enhance unarmed combat greatly

THE BAD
-Albino
-Hideous
-prone to Schizophrenic delusions
-slower crafting because of the claws
-Penalties when haven't consumed human flesh for a period
-disintegration(idk about this one either)
-bad temper

### Describe alternatives you have considered.

Change the lore, or the outcome of this "questline" with something else instead of a new mutation, or any part really. Or don't do this but I really like the idea.

### Additional context

I would appreciate any feedback. I already begun adding some of the content mentioned above, and would like to submit a pr if approved.

**Comment by fairyarmadillo** [comment]
This is a little too elaborate to be believable.

The cult is iirc one of the many blob cults that popped up, essentially people going half-feral and worshiping some malignant idea of an outer god that they cannot perceive or understand. They do not need any special treasure and should probably not be connected to temples or mines or any other weird thing, they're sufficiently weird and cool as is.

**Comment by KeremBabaG** [comment]
> This is a little too elaborate to be believable.
> 
> The cult is iirc one of the many blob cults that popped up, essentially people going half-feral and worshiping some malignant idea of an outer god that they cannot perceive or understand. They do not need any special treasure and should probably not be connected to temples or mines or any other weird thing, they're sufficiently weird and cool as is.

Fair enough, this was an attempt to make them more in line with the current lore and save them from a potential removal. But I still like the idea, would it be more applicable if I made it into a different cult, unrelated to strange cabins and cult and whatnot?

**Comment by fairyarmadillo** [comment]
I don't think anyone was trying to remove them?

**Comment by KeremBabaG** [comment]
yeah I said potential because they are kind of weird and gimmicky as they are

**Comment by KeremBabaG** [comment]
closing because rethinking this
