### ISSUE TITLE
Can't use commercial fertilizer

### ISSUE THREAD

**Issue by CutenessOverloaded** [CleverRaven/Cataclysm-DDA#67929]
### Describe the bug

When using commercial fertilizer:
```
DEBUG    : Tried to fertilize with fertilizer_commercial, but player doesn't have any.

 FUNCTION : fertilize_plant
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\iexamine.cpp
 LINE     : 2723
 VERSION  : 8c55459
```

There should be other items have same problem...

In my guess... (can just briefly read a little C++)

`fertilize_plant()` > `can_fertilize()` > `has_charges()` > `charges_of()` > `charges_of_internal()`

In `charges_of_internal()`,
```
if( e->count_by_charges() ) {
    qty = sum_no_wrap( qty, e->charges );
```
`e->charges` is 0, since https://github.com/CleverRaven/Cataclysm-DDA/pull/60885 `int def_charges = 0;` in _itype.h_
So, `charges_of()` is 0 > `has_charges( fertilizer, 1 )` is `false` > fail to do `fertilize_plant()`

To fix it, maybe
add a `count_by_stack()` or something
or
add another `if` that count item isn't count by charges in the `else` of
```
if( e->count_by_charges() ) {
    qty = sum_no_wrap( qty, e->charges );
} else {
    qty = sum_no_wrap( qty, e->ammo_remaining( nullptr, true ) );
}
```
So to count item that don't count by charges
(feel like myself talking non sense since idk c++ ._.)

### Attach save file

[樱桃山-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12450850/-trimmed.tar.gz)

### Steps to reproduce

1. Get a commercial fertilizer
2. use it on a planted plant

### Expected behavior

Should be behavior just like liquid fertilizer ._.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 8c55459 [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝)<color_dark_gray>（93.6%）</color> [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    心胜于物 [mindovermatter],
    替换小地图图标 [alt_map_key],
    特色升级能力 [bombastic_perks],
    疯狂大灾变 [crazy_cataclysm],
    更多变异场景 [extra_mut_scens],
    翻译晦涩对话 [translate_dialogue],
    发现玩家图标，HitButton_iso版 [sees_player_hitbutton],
    状态图标，retrodays版 [sees_player_retro],
    标准伤害测试套装 [standard_combat_test],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    技能提升属性 [StatsThroughSkills],
    驯服野兽 [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
Sounds like those who removed the charges didn't change (all of) the code for affected items to reflect the change.

This should probably be a call to check for code related to other items stripped of charges as well (or possibly the other way around: check for all usages of charge using code and verify that all the items affected still have charges).
