### ISSUE TITLE
Plzz, My npc are so scared now

### ISSUE THREAD

**Issue by CutenessOverloaded** [CleverRaven/Cataclysm-DDA#67939]
### Is your feature request related to a problem? Please describe.

I just updated my game and NPCs are freaking out seeing zombies and other monsters.

Imagine 5 NPC with spear on hand are scared at a baby zombie.
(exaggerated, but they start being scared after a few more)

### Solution you would like.

1. Let player said something to them that makes them braver (by level of social skills maybe?)
2. Scared by what gear and stats they have, how strong is the player/other npc beside them
3. Let player train them to face zombies (also hope to have feature to train horses not scared of zombies)

### Describe alternatives you have considered.

Fix it back to before? Otherwise NPC will be only a crafting machine.

### Additional context

Can be ignored but it's what I feel like.
As a sergeant of survivors, it heartbreaking to know that people you tread as the best buddies, share them you favorite drinks, give them you favorite gears, now don't trust you are capable to lead them to win the fight and run away when you had already throw yourself in the battlefield...

**Comment by Nebnis** [comment]
How many zombies are coming to you? do you roughly remember?

**Comment by I-am-Erk** [comment]
Please use the bug report template so I can tell if this is something I've already solved and get the details I need to help you.

**Comment by CutenessOverloaded** [comment]
I see a guy saying that there were a new "bravery stat", so I assume they know what they are talking about ._.
So, I haven't report as a bug cause I guess maybe it was some new feature.

It's the closest thing I could get since I didn't have the original save.

![Screenshot (53)](https://github.com/CleverRaven/Cataclysm-DDA/assets/100664452/610f071e-ffc4-4ea2-a5fe-be312859b879)
![Screenshot (54)](https://github.com/CleverRaven/Cataclysm-DDA/assets/100664452/a78c11f5-d5d0-4ca2-97ba-af11bec249e7)


Game save:
[樱桃山-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12470538/-trimmed.tar.gz)

Game report:
- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: c407808 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Standard combat test suite [standard_combat_test],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by I-am-Erk** [comment]
In the screenshot your NPC's appear to still be fighting. I will check the save if I have time, or if someone else can that's neat. This version is after I fixed some things, were they running away too much before and now it isn't as bad?

**Comment by Kywi001** [comment]
I wonder if this is because he made the save before the said stat gets introduced? And 0 bravery means theyre likely to not fight and NPC's before this got implemented defaulted to 0 stat?

**Comment by I-am-Erk** [comment]
No new stats have been introduced
