### ISSUE TITLE
Finishing brewing meal grubs causes segfault

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#67937]
### Describe the bug

I have just finished my first batch of mealgrubs. Unfortunately, when I try to take them out of the Fermenting Vat, my game segfaults. I don't know how to label, but this probably need aftershock added.

### Attach save file

[ASDFDSFA-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12458886/ASDFDSFA-trimmed.tar.gz)

### Steps to reproduce

Go into save
Hit e and choose the tile upwards
Choose yes
Segfault

### Expected behavior

I get some food.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-3906-g23b72a9de8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mqrause** [comment]
What game version is this? The hash 23b72a9de8 doesn't seem to exist.

**Comment by ilovehans10** [comment]
I am not super well versed in git, but my most recent pull/compilation was on e0af2359ca. I have two local commits on my game that only modify a little of the JSON in Magiclysm. I didn't know that would change the game version, but I guess that makes sense.
