### ISSUE TITLE
Hallucination Dropped Weapon

### ISSUE THREAD

**Issue by BlazingRoach** [CleverRaven/Cataclysm-DDA#67938]
### Describe the bug

My character is hallucinating and an npc hallucination spawned near me. I initiated conversation cause why not, and my hallucination attempted to rob me so I attacked them. After their disappearance a makeshift machete was on the ground. Pretty sure that isn't supposed to happen.

### Attach save file

[Francestown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12458916/Francestown-trimmed.tar.gz)

### Steps to reproduce

1. Hallucinate
2. Maybe attack npc hallucination
3. Weapon on the ground

### Expected behavior

Hallucinations don't drop weapons

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 56db4c0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

May have disarmed them, only thought about that way later.

**Comment by ilovehans10** [comment]
I am not 100% sure of the use case of `avatar::disarm`, so if it is used in every case where an avatar stops wielding an item, than none of the following is applicable. Is there a chance that the NPC wasn't disarmed, but instead chose to drop the weapon, as it somehow thought it could do more damage with fists/gloves. I have also had cases where NPCs would choose to throw weapons that would be better used in melee.

A way to test the first option would be to give a hallucination a throwing knife and see if it is still around after the hallucination disappears. To test the second option, I would assume that giving a hallucination a low damage weapon+a high damage glove would work.

**Comment by BaumgeistOne** [comment]
> A way to test the first option would be to give a hallucination a throwing knife and see if it is still around after the hallucination disappears.

I encountered a hallucination NPC, it threw a throwing knife at me, which stayed on the ground after the hallucination vanished.

Also a crossbow appeared near my car after sleeping through some hallucinations.
