### ISSUE TITLE
Fleeing hostile NPCs attempt to chase down and attack

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#67935]
### Describe the bug

I encountered a hostile NPC, failed to calm it which set it to be "fleeing," but it continued to chase after me. The NPC attempts to attack me, but seems to be smashing the ground beneath me instead. It is dealing no damage, but it managed to damage my clothing.

### Attach save file

[West End-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12457490/West.End-trimmed.tar.gz)

### Steps to reproduce

1. Have hostile NPC flee.
2. Observe what happens.

### Expected behavior

The NPC should either flee away or change to attacking.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/c5f9d2c6-8946-4ed0-9996-8232bac135d0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 0fa8bc5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by PatrikLundell** [comment]
May or may not be related, but I've encountered stealth attacking geese, i.e. geese that show the standard white exclamation mark, but make a beeline for me and my companion (who were moving away), only to attack when reaching the companion.

**Comment by I-am-Erk** [comment]
won't be related to geese since the only changes were in npcmove.cpp

I already know the problem and have the solution ready, just need to test it.
