### ISSUE TITLE
Incomplete generation of some locations

### ISSUE THREAD

**Issue by CHCOOH** [CleverRaven/Cataclysm-DDA#67945]
### Describe the bug

Nice to meet you.
First of all, I am new to Github.
I am new to Github, and I am not able to code, so I am not able to check the distribution files, even if it is simple,
I cannot guarantee the appropriateness of both the use and the suggestion because I am not able to check if it is really a bug or not.
Also, please note that I am not fluent in English and that I used DeepL for the translation.
Please understand that we cannot guarantee the appropriateness of the recommendations made by both sides.
---------------------------------------------
Ver:c8461a5
2023-08-19-0656

Problem: Incomplete generation of some locations?

LMOE shelter
military bunker
military outpost
military helipad

The above four locations do not appear in the game as far as I have been able to ascertain.
I was suspicious, so I looked around while opening the map in debug mode and found the aircraft carrier and military base, but none of the above four were found.

Also, when I added the bundled mod "Aftershock", a large number of shopping malls are generated.
Compared to vanilla, it seems more abnormal than excessive.
I'm not sure if this is the case or not....
---------------------------------------------------
**Below this is the original text**.

初めまして。
まず初めに私はGithubを利用するのが初めてであり
またコーディングが出来ず簡易的にも配布ファイルを確認する事が出来ない為に、
本当にこれがバグなのかどうかを確認する事が出来ていない為に利用、提言の双方に置いて適切かどうかを担保できない事をご了承ください。
また英語も出来ず、DeepL翻訳を利用した文章であることも先に断っておきます。
---------------------------------------------
Ver:c8461a5
2023-08-19-0656

問題点:一部ロケーションの生成不備？

LMOE shelter
military bunker
military outpost
military helipad

私の確認できたものでは上記四つがゲーム内に出てきません。
不振に思ったのでデバッグモードでマップ解放しながら見て回った限り、aircraft carrierとMilitary Base は見つかりますが上記四つは一つも見つからなかったです。

また同梱MODであるAftershockを入れると大量にショッピングモールが生成されます。
バニラと比べるとそれは過剰というより異常なほどに感じます。
---------------------------------------------

### Attach save file

N/A

### Steps to reproduce

Since it is a generation rate issue, please generate the world as per normal procedure and check from map release in debug mode.
Or there may be another easy way to check, but I could not find it.

******Original******
生成率の問題なので通常手順通りに世界を生成し、デバッグモードでマップ解放からの確認をしてください。
もしくは他にも簡単に確認する方法があるかもしれませんが私にはわかりませんでした。

### Expected behavior

I think the above four were important factors in bringing excitement and interest to moving around in this game.
It seems to me that not being able to appear or find them would detract from the enjoyment of the game in areas that have nothing to do with replenishing or replacing supplies.

******Original******
このゲームで移動をする上で上記の4つは興奮と興味をもたらす重要なファクターだったと思います。
出てこなくなる、または見つけられなくなるのは物資の補給もしくは代替とは関係ない部分でゲームの楽しさを失うと思われます。

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: c8461a5 [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    削除 - 鉄道駅 [No_Rail_Stations]
]

**Comment by ZhilkinSerg** [comment]
Many overmap special locations are unique (appear only once per overmap) or globally unique (appear only once per world) - they are not guaranteed to spawn on any specific overmap, so basically you just did not find these location due to rng.

**Comment by Kywi001** [comment]
Shouldve checked on a new world too, with all default settings since messing with how near each city from one another greatly impacts map gens

**Comment by CHCOOH** [comment]
Of course I know that generation is not guaranteed, but this is the first time that it has not appeared at all.
This is a suggestion because I am concerned that it is too rare to say that it is just a random factor that happened to not appear.

Of course, I created about 5 maps in vanilla with everything at the specified values, and then opened and checked about 10 of those overmaps in debug,
I have *never* found any of the above facilities.
Is this the expected generation rate for this game? At least in my previous games I was able to discover more.

If it is still a figure of probability, and it is still showing up as normal for other players, then there is not much I can say.
I guess it is necessary to refer to the internal data, but as I mentioned before, I cannot look into the contents of the game.

もちろん生成が保証されていない事は私も知ってはいますが、全く出なくなったというのは初めての事です。
たまたまランダム要素で出なかっただけ、というにはあまりにも出なさすぎるという懸念を持ったための提言です。

もちろんバニラで全てが規定値のマップを5つほど作り、そしてそれらのオーバーマップを10つほどデバッグで開いて確認した結果、
上記の施設を*一度も*発見できなかったのです。
これはこのゲームの想定通りの生成率ですか？少なくとも私の以前のゲームではもっと発見できていました。

それでもなお確率の綾で、他のプレイヤーに置いては通常通り出てきている、というのであれば私が言えることは特にありません。
本来であれば内部データの参照などが必要なのでしょうが、前置きした通り私は中身を覗けないためです。
