### ISSUE TITLE
Using Advanced Inventory to put items into containers on corpses crashes the game. (segmentation fault)

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#67949]
### Describe the bug

As title says it has been happening since I originally opened a ticket about the wallet and photograph, I thought it was just the wallet and photograph at the time. But apparently ANY items you attempt to put into ANY container that a corpse is still wearing will crash the game when trying to do so with advanced inventory manager. 

Note: I have only attempted this with items I am taking from my inventory and placing in said containers on corpses, I have not tried to take items on the ground and place them in containers.  (Most of the time it is an accident when I do it.) Also it doesn't matter whether it is an item that is capable of fitting into said container.

### Attach save file

[Files.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12473535/Files.zip)

### Steps to reproduce

1. Open up any corpse of recently deceased enemy.
2. Work your way to a backpack, pants, cardboard box, etc. (anything they are wearing/carrying.)
3. Open up said container and put something in it, game crashes. 

### Expected behavior

Game not crashing and container to either accept what was attempted to be placed into it, or tell me it doesn't fit and abort the action.

### Versions and configuration

Windows 10
cdda-windows-tiles-sounds-x64-msvc-2023-08-30-0209
Tiles
English
Mod list will be a pic in the zip file with the save, crash, and debug log.

**Comment by andrei8l** [comment]
/confirmed This happens only for corpse items displayed at the top level (#53374). If you enter the corpse, then the container, it works correctly.

This `item_location` is garbage:
https://github.com/CleverRaven/Cataclysm-DDA/blob/c3cc22142eca39fbba8fc33361b8c8875a29db58/src/advanced_inv_pane.cpp#L263
