### ISSUE TITLE
Reinforced glass is far too strong in comparison to RL counterpart. 

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#67944]
### Describe the bug

While watching the a YouTube series by Rycon,  I was noticing how excessively damage resistant reinforced glass was compared to real life.   He was whacking on it with a fire axe and it was not breaking.    In real life I have seen that glass be at least shattered and turn completely opaque with small hits. An assault with a fire axe, while it might not be instant, even a child assuming they could lift a fire axe could eventually penetrate it. 

In the files the damage thresholds for glass walls are 2, 8 and reinforced glass are 60,160. 

While ballistics glass and plexiglass possibly exhibit such strength especially when they get thicker, reinforced glass should be at most 3 or 4 times stronger not 30. 

While I understand this would require labs for example to have their glass walls changed to ballistics glass in many area's in order to feel correct, it would correct a significant discrepancy.   

### Attach save file

N/A

### Steps to reproduce

1. Hit a reinforced glass wall with an object that in real life would completely devastate it. 
2. Observe it is completely unharmed. 

### Expected behavior

Within a margin of error I would expect reinforced glass walls to turn opaque from the first hit of any significant size and then collapse under continual assault. 

### Versions and configuration

N/A

**Comment by fairyarmadillo** [comment]
Glass is all wrong pretty much across the board. Why are car windshields made of normal and not laminated glass? Why is laminated glass so strong?

**Comment by Profit0004** [comment]
> Glass is all wrong pretty much across the board. Why are car windshields made of normal and not laminated glass? Why is laminated glass so strong?

Another good question.  Laminated glass can be incredibly strong, but it depends how it is manufactured, and it is highly dependent on thickness.  Security laminated glass should be very strong, but just standard laminated glass should fail under the assault of even a normal hammer.

**Comment by Kywi001** [comment]
Correct me if I'm wrong, but whacking on a car basicly you smashing random parts in that tile, like, you might be whacking on a windshield, but the game rng's you into hitting the frame sometimes or sometimes both, vehicles in general are whack, like how you can plate armored a windshield and you can still see through it, it's not like you're installing a bunch of rebars into it, we're installing a plate, but yeah

**Comment by I-am-Erk** [comment]
Definitely would be open to some more glass.

For reinforced glass though, we'd also need some kind of variant to represent containment glass in labs and things. Currently reinforced glass could be wire-strengthened glass in a storefront, or it could be 40cm of high tech laminates designed to stop a freight train. We don't distinguish the two and if we weaken one we should probably add the other.

**Comment by Profit0004** [comment]
In walls, we have Laminated [40, 120] to destroy, Ballistics glass [ 80, 200 ],  Reinforced  [ 60, 160 ], Reinforced with closed shutter [ 60, 160 ], and regular glass [ 2, 8 ].    Steel doors are [80, 250]   and brick walls are [60,160]

I believe the way it works is every time a damage roll is made, the object rolls between the two numbers and if it is more than the damage applied, the attack doesn't damage the object. 

Actually now that I look at it, I think it's a bug.   It looks like Reinforced with closed shutter's damage resistance accidentally got transferred to reinforced glass as they are the same and it looks very similar to a metal door and exactly the same as a brick wall, which load bearing brick walls are usually around 8-12 inches thick. 

Anyhow... We do have other options. 

> Definitely would be open to some more glass.
> 
> For reinforced glass though, we'd also need some kind of variant to represent containment glass in labs and things. Currently reinforced glass could be wire-strengthened glass in a storefront, or it could be 40cm of high tech laminates designed to stop a freight train. We don't distinguish the two and if we weaken one we should probably add the other.

**Comment by I-am-Erk** [comment]
Yeah, reinforced with open shutters definitely shouldn't be the same as closed, nor should it be stronger than iirc a log wall.
