### ISSUE TITLE
Tried to put an item (charcoal) count (27750) in a container (fake_char_kiln) that cannot contain it

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#67951]
### Describe the bug

When opening the construction menu, I got this error:
```
 DEBUG    : tried to put an item (charcoal) count (27750) in a container (fake_char_kiln) that cannot contain it: pocket unacceptable because tried to put too many charges of ammo in item

 FUNCTION : put_in
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1601
 VERSION  : c3cc221
```

I tried to find this error in existing issues, but I can't find any.

### Attach save file

[Rainsville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12476862/Rainsville-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Open construction menu
3. Observe error

### Expected behavior

Not throw the error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: c3cc221 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by GlordXd** [comment]
Had this exact issue a few weeks ago.
Just fully loaded the charcoal kiln,it fully burned,i extracted the charcoal ((e) on the kiln),but didn't took it out,then i was getting this error randomly from time to time.
