### ISSUE TITLE
Faction Camp Stuck at Northeast Tent

### ISSUE THREAD

**Issue by BlazingRoach** [CleverRaven/Cataclysm-DDA#67979]
### Describe the bug

When building a modular faction camp version 2 if you put up a tent as the northeast shack it is impossible to develop the central building further. You can build an obstacle course, radio tower, cellar, and well but you cannot add more rooms and beds within the central area.

### Attach save file

N/A

### Steps to reproduce

1. Create Faction Camp version 2
2. Use a tent as the northeast shack
3. Find yourself unable to develop the central building further

### Expected behavior

Allow the player to upgrade the central building when using a tent or allow them to replace the tent with a proper shack.

### Screenshots

![Screenshot 2023-09-01 151135](https://github.com/CleverRaven/Cataclysm-DDA/assets/138542932/c6c83f08-50a2-45b7-925c-038e2da70c9c)
![Screenshot 2023-09-01 151145](https://github.com/CleverRaven/Cataclysm-DDA/assets/138542932/84e2ac1d-9db4-45c3-96b2-c61d554149e2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 53869b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by PatrikLundell** [comment]
/confirmed

I just tried it with a week old experimental, and the progression stops there, as reported. I'll investigate it.
