### ISSUE TITLE
Numpad toggle for item menus is unclear

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#67996]
### Describe the bug

Normally, when in trading/grabbing menus you can use the number keys to select how many of an item you want. Now, my number keys are acting like arrows, with 2 moving my selection down, 8 moving it up, and 6 toggling whether the item is selected or not.

I've tried closing/reopening the game and the issue persists, Karol and Bionicle on the discord confirmed it occasionally happens to them as well but nobody knows how or why.

### Attach save file

[West End-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12506222/West.End-trimmed.tar.gz)

### Steps to reproduce

1. Attempt to select specific numbers of items in grabbing or trade menus.
2. Hope the issue occurs.

### Expected behavior

Number keys should continue to act as they normally do for selecting the number of items instead of as an extra set of arrow keys.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 6248929 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Kamayana** [comment]
Do you have numpad mode on? F5 toggles it.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/ea7e18ce-4032-4da8-953c-8f1f85e7a7df)

**Comment by gisaku33** [comment]
That's exactly it, thank you! I don't see that toggle listed anywhere in either the '?' options or the keybindings menu, I never noticed the "numpad on" in grey text at the top either. It could really use more clarity that it even exists.

**Comment by Kamayana** [comment]
Yeah, this has come up before, it's really unclear. I question if it even needs to exist, too - people without numpads will never want it on, and I play with a numpad and I never want it off (I use a hotkey for quantity selection).
