### ISSUE TITLE
Wrong Sound parameter for build command in release.yml

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#68009]
### Describe the bug

On https://github.com/CleverRaven/Cataclysm-DDA/blob/ccdf5db6bc87e603ab5d53e4a827922d76e94af2/.github/workflows/release.yml#L227
and on https://github.com/CleverRaven/Cataclysm-DDA/blob/ccdf5db6bc87e603ab5d53e4a827922d76e94af2/.github/workflows/release.yml#L250

It says `SOUND=${{ matrix.tiles }}` but sound should say `SOUND=${{ matrix.sound }}`

### Attach save file

N/A

### Steps to reproduce

1. Go to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/workflows/release.yml#L250 and observe

### Expected behavior

sound should say `SOUND=${{ matrix.sound }}`

### Versions and configuration

cdda-experimental-2023-09-04-0852

**Comment by Qrox** [comment]
I think the intention here is to always enable sound for tiles but only include a soundpack if `sound` is `1`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/fe7c8527865dce8f6d35effc0ddc5281d8a41278/.github/workflows/release.yml#L152-L156

The name could be made clearer if that's the case though.

**Comment by snipercup** [comment]
So you're saying that if we'd implement my suggestion to make `SOUND=${{ matrix.sound }}`, we would end up with a tiles version of the game without sound? I thought it was meant to include the soundpack, but I see in your comment that it's determined elsewhere and not in `SOUND=`. 

My suggestion would be to add a `includesoundpack` option in the matix and have the `sound` option to determine the build parameters.
