### ISSUE TITLE
Test error on GitHub: Error: Can't use 'tar -xzf' extract archive file

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#68010]
### Describe the bug

Tests don't pass.

```
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_2d480b16-e76a-485f-98a6-97085e22e42d/85a0837c-7cac-462f-95d7-d0fb4113c5f4.tar.gz. return code: 2.
```

https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/6077679322/job/16487750440?pr=67936

### Attach save file

N/A

### Steps to reproduce

Don't know.

### Expected behavior

Tests pass

### Versions and configuration

N/A

**Comment by casswedson** [comment]
this is probably a random error given the latest runs seem to be behaving as expected https://github.com/CleverRaven/Cataclysm-DDA/actions/workflows/linter.yml
![Screenshot from 2023-09-04 19-02-56](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/f857b169-7c32-43de-9902-4b9aa9fc1a87)

**Comment by akrieger** [comment]
Failure in job setup is unlikely to be our or your fault, yeah.

**Comment by Brambor** [comment]
Another one:
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/6079667695/job/16492493205?pr=67936

So the recommended procedure is to just restart the tests, I assume.
