### ISSUE TITLE
Gun overheating mechanic breaks laser turrets

### ISSUE THREAD

**Issue by YoelFievelBenAvram** [CleverRaven/Cataclysm-DDA#68011]
### Describe the bug

New laser gun overheating mechanic breaks vehicle turrets. I have three salvaged mech lasers on my death mobile. One gun fires a couple times and overheats. Then none of the other lasers will fire. The laser will not cool down until it's removed from the vehicle. When all three guns are removed, only the first one is overheated. It will cool down, and then again only fire a couple times before overheating and no longer working until removed.

### Attach save file

n/a

### Steps to reproduce

1. Attach laser gun to turret mount.
2. Fire it until it overheats.
3. Wait a few minutes to see it won't cool down.
4. Remove gun to initiate cool down procedure.
5. Go back to step 1 and repeat.

### Expected behavior

I would expect the other guns to work when only one is overheated. I would also expect a message that a turret overheated and for the gun to cool down while still attached.

### Versions and configuration

Linux 2023-9-4-1955

**Comment by esavier** [comment]
The same thing happens with only one canon. Few shots and its useless. I was wondering what's wrong with that.

Is there something indicating overheating btw?

**Comment by YoelFievelBenAvram** [comment]
There's no indication that it's over heating while attached to the turret. It just fires two or three times and stops. Manual targeting similarly doesn't return any errors, it just doesn't fire. You can tell it's an overheating issue though because when you remove the gun, it's still hot and starts it's cool down procedure. And it'll stay hot as long as it's on the turret. You can then reattach the gun after it cools down and it'll fire another couple of times before breaking again.

**Comment by Lloydles** [comment]
For ease of reference, the overheating mechanics were added in https://github.com/CleverRaven/Cataclysm-DDA/pull/67959 but don't seem to play well with vehicle turrets.


> There's no indication that it's over heating while attached to the turret. It just fires two or three times and stops. Manual targeting similarly doesn't return any errors, it just doesn't fire. You can tell it's an overheating issue though because when you remove the gun, it's still hot and starts it's cool down procedure. And it'll stay hot as long as it's on the turret. You can then reattach the gun after it cools down and it'll fire another couple of times before breaking again.

I can confirm that this is how it currently works.
To add to this, turrets would likely need a way of knowing to stop firing before a gun critically overheats, to prevent turreted energy weapons from bricking themselves in just a handful of firing cycles.
