### ISSUE TITLE
Enervating Touch spell (from Mind Over Matter) is crashing the game when cast

### ISSUE THREAD

**Issue by rockygr** [CleverRaven/Cataclysm-DDA#68024]
### Describe the bug

When using Enervating Touch on an NPC, the game will crash

### Attach save file

[gooda-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12539443/gooda-trimmed.tar.gz)

### Steps to reproduce

Open spellcasting menu;
Activate Enervating Touch;
Target something (a Speaker is near, helpfully);
The game will crash.

### Expected behavior

The game would not crash when casting a spell.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.2; Release: 21.2; Codename: victoria; 
- Game Version: 35b4e10 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Aftershock [aftershock],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12539439/debug.log)

**Comment by Maleclypse** [comment]
@Standing-Storm

**Comment by Standing-Storm** [comment]
Just loaded up the game and I can't reproduce: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/1475f7ec-4134-4a6a-9a58-7879ff2bc3eb)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/4a54d861-c4bd-4e84-a71a-27e6607c0986)

**Comment by shadowsapex** [comment]
@Standing-Storm i can confirm this bug. after applying the effect, pass a turn. the game will crash. my save file is attached, it only requires passing a turn to see the bug

[Escobares-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12615603/Escobares-trimmed.tar.gz)

i tried it on the starting npc too but it seemed to work fine

**Comment by Standing-Storm** [comment]
That one does crash for me.

If I load it up, debug kill the zombie, spawn a new zombie, and apply Enervating Touch to it, I get this:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/bc30ad5e-e205-4162-b85c-6290b8417910)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/9ebc6dd8-c9e2-41c4-b723-f86b9544cd12)

And then the game crashes.

It looks like changing the damage type to "pure" prevents the crash, so I'll do that for the moment even if it's not fixing the problem.
