### ISSUE TITLE
HWP's CQC configuration performs much worse than stats suggest

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68030]
### Describe the bug

The 12 gauge HWP configuration is abnormally bad, despite the stats and JSON seeming like it should perform similarly to other shotguns. I tested with 10 in all skills by spawning standard zombies 10 tiles away and precise aiming while they approached, shots are extremely inaccurate and deal unusually low damage, 9-62, with the most common numbers being around 40.

Even with 100% hit chance listed, enemies may be hit with only a single pellet, while other times it will say multiple projectiles hit like normal despite dealing vastly lower damage than other shotguns.

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12542858/test-trimmed.tar.gz)

### Steps to reproduce

1. Spawn HWP, along with the close quarters configuration mod and mags/shells, and any other shotgun.
2. Fire at zombies, compare results.

### Expected behavior

The CQC config should perform similarly to other shotguns.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/74596561-a363-4269-ae3b-9d7a3843f0a7)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/f498b9cf-f1c5-4aa2-8cfa-fce913363efd)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/60c32c58-354d-4039-b1cf-1dc4eb3a3659)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 6248929 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

I have no idea what is causing this, and neither did anyone on the discord. I've tried adjusting the JSONS and fiddled with the damage, length, dispersion modifier, removed the choke flag, changing the base HWP's copy-from to be shotgun_base, the changes happened but didn't solve whatever is causing it to act weird.

**Comment by GuardianDll** [comment]
/confirmed
8 tiles from target, all skills 5
missed_by_tiles - number of tiles the attack missed by
missed_by - hit quality, where 0.0 is a perfect hit and 1.0 is a miss

Mossberg 500
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/68b2005e-cf47-4537-9d5a-c7fc95a35c18)
Mossberg 500 with choke
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/62c2d391-7981-4524-a8a2-e6e9bb93e33b)
HWP CQC
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/775e8b32-e755-4693-9d0f-70afa0bf4c1b)
HWP breacher
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/5af8b09d-f723-447e-8fbe-6e6645256f26)
