### ISSUE TITLE
Unable to finish church mission

### ISSUE THREAD

**Issue by Afghani84** [CleverRaven/Cataclysm-DDA#68031]
### Describe the bug

I accepted all missions at the church retreat that I could find. Two of them were "Find cactus seeds" and "Retrieve the fertility supplements" for Gemma Johnstone.
When I came back to the retreat with supplements in my inventory, Gemma asks for seeds but NOT for supplements. I cannot find an option to complete this mission...
[001m Buffalo Center - Home, Sweet Home-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12543056/001m.Buffalo.Center.-.Home.Sweet.Home-trimmed.tar.gz)

### Attach save file

[001m Buffalo Center - Home, Sweet Home-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12543079/001m.Buffalo.Center.-.Home.Sweet.Home-trimmed.tar.gz)

### Steps to reproduce

1. Accept both missions from Gemma (not sure if order is important)
2. Retrieve the fertility supplements
3. There are no options to complete the mission when talking with her

### Expected behavior

I would expect her to ask for supplements the same way that she asks for seeds.

### Versions and configuration

Windows 10
Game version: 2023-09-06-1648
Graphics version: MSXotto+
Ingame language: English
Mods loaded: Disable NPC needs, No Hope, Slowdown Fungal Growth, Alternative Map Key, Stats Through Kills

**Comment by MNG-cataclysm** [comment]
/confirmed. This should be a simple fix.
