### ISSUE TITLE
Vehicle merged with power grid can't be independently taken down

### ISSUE THREAD

**Issue by akrieger** [CleverRaven/Cataclysm-DDA#68046]
### Describe the bug

I have a folding light frame I installed into the grid which I can't take down, even after removing everything else attached to the grid. The `e` menu treats it as an appliance but the 'take down appliance' option is greyed out.

### Attach save file

[Kataclysm.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12562494/Kataclysm.zip)

### Steps to reproduce

1) Load the save
2) interact with the power grid near the character. There is a medium car battery, solar panel, cabin wall with wiring, and the bare light frame.
3) Attempt to take down everything including the light frame.

### Expected behavior

I can take down the frame.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/fba4ae6b-fd1c-476f-a25f-a6613ce2b745)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/ca4e2ac9-34a4-4575-b70d-0ddb7412f500)

### Versions and configuration

Win10 experimental `f07f373c104777a385f5eee642791f40d22396c8`

**Comment by akrieger** [comment]
Nevermind, I had an extension cord connecting this to a fridge I wasn't aware of. Detaching that from the fridge side let me take this down no problem.

**Comment by akrieger** [comment]
Wait nevermind, that let me take down the wall wiring next to the 'power grid' vehicle, but I still couldn't interact with the vehicle as normal.

**Comment by KHeket** [comment]
I have the same issue, when conneted the solar car with placed as a appliance and then merged it - and I cant interact with car anymore, no matter what I am trying to do

**Comment by akrieger** [comment]
The issue appears to be that the remove function is blocked because there are non-frame components on the vehicle. The code assumes that removing the vehicle means returning it to bare part form. Since my wheelchair had a wheel mount (it's an 'axle' location not a 'structure' location) it's hitting this condition and failing.

Seems like there ought to be a way to 'unplug' a vehicle-appliance without having to tear it down completely. I need to study this code more to know though.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/d1c232ba-8e83-423c-8310-b58ebb94f432)

**Comment by akrieger** [comment]
#69624 prevents this from getting into this state.
