### ISSUE TITLE
A few container whitelist settings

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#68043]
### Is your feature request related to a problem? Please describe.

Container settings are very good as a feature, but their UI is a nightmare. While it would be nice to fix that, there are some QoL features that I think would be pretty easy to add and would help a lot.

### Solution you would like.

These are really a couple separate, related issues. I'd suggest all of these should go into a new `q`uick settings button in the inventory manager.

##### 1. Whitelist current contents of a container
Rather than manually whitelisting everything I want to keep in my toolbox, I'd like to be able to just put a bunch of things in it, then add everything currently in the box to the whitelist. Boom, one button, done. I can edit the list later if I want to fine tune it.

##### 2. Dynamic whitelist based on a particular item
I'd like to be able to select a pocket and tell it "store only ammo/magazines that can fit in this weapon" and then select a gun from my inventory. Similarly, "store only batteries that can fit in this tool" would be good. I'm open to similar suggestions.

It's less likely to be useful but it might be neat to be able to choose a particular recipe and whitelist its ingredients to a pocket, eg. "store only ingredients for bread in this box".

##### 3. Copy and invert a list
When I've designated one pouch on my toolbelt as being "for nails, screws, nuts, and bolts", it would be neat to then be able to automatically populate that whitelist to all other pockets in my inventory as a *black*list. This way I can have nails on autopickup but not worry about them filling up every other container, once my nail pouch is full that's it. Likewise I'd like to be able to spread this to just a few pockets through a quicker 'copy and invert' option.

##### 4. White/blacklist presets
We should have some common preset lists, eg. "first aid items", "pistol ammunition", "rifle ammunition", "grenades", "arrows", "bolts", "travel snacks", "construction tools", and things like that. These lists would require curation unfortunately, but even just having a decent start would save a lot of time. In some cases (first aid items for first aid kits) we should have these pre-applied to certain appropriate containers.

### Describe alternatives you have considered.

better UI overall, but I think these help further that.

### Additional context

I'd also like to be able to do the same things with autopickup lists, and it would be neat if the two interacted a lot more. Like, maybe I could make a particular pocket that whitelists ammo for a particular weapon, and as long as that pocket is empty, anything that can go in the pocket is on autopickup. I'd combine that with the "auto whitelist recipe" thing so I could make a bag, dedicate it as a "bread ingredients" bag, then while I am carrying it I automatically pickup anything I can use for bread and put it in the box until the box is full. This is a larger request than this issue is meant to go into though.

**Comment by oosyrag** [comment]
- Allow pocket manager to display all worn pockets at one time

**Comment by Rabadash94** [comment]
>4. White/blacklist presets
>
>We should have some common preset lists, eg. "first aid items", "pistol ammunition", "rifle ammunition", "grenades", "arrows", "bolts", "travel snacks", "construction tools", and things like that. These lists would require curation unfortunately, but even just having a decent start would save a lot of time. In some cases (first aid items for first aid kits) we should have these pre-applied to certain appropriate containers.

Even more, although it may have to be left for the future. Preset lists could be nested to group them under a preset container type. For example, a bag has certain pockets. You can create a preset list that distributes preset items to each pocket.
Of course, for this it would be necessary for the game to have an editor, just as predefined characters can be created. It is important to remember that, in real life, it would take a person no more than a few seconds to decide how to distribute their things in a container.
