### ISSUE TITLE
Scrap tin cannot be crafted into tin powder

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68056]
### Describe the bug

Enormous tin ingots taken from the Exodii can be deconstructed down into scrap tin, which cannot be crafted into anything. 

### Attach save file

N/A

### Steps to reproduce

1. Deconstruct enormous tin ingot after painstakingly hauling it.
2. Weep at your piles of useless scrap tin.

### Expected behavior

Scrap tin should have a way to grind it into tin powder usable for recipes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: e0694d0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by KeremBabaG** [comment]
Hey man I tended to this can you close the issue

**Comment by GuardianDll** [comment]
for furute reference, "closes 68056" or "fix 68056" in the PR body will close the issue automatically
