### ISSUE TITLE
[Mind Over Matter] Transposition does not account for different z-levels

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68050]
### Describe the bug

If you use Transposition on a target on a different z-level, when you swap positions you will remain on the same z-level you were on when you cast it. In my case, I cast it from a roof onto a foal on the grass below, and it placed me in the air above where the foal was.

### Attach save file

[Palm Beach Gardens-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12563947/Palm.Beach.Gardens-trimmed.tar.gz)

### Steps to reproduce

1. Be above target, and cast Transposition.
2. Do your best Wile. E. Coyote impersonation.

### Expected behavior

Transposition should bring you to the same z-level that your target was at.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/aa24add6-e5ea-4c6f-804a-c78e6cd16b64)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 6248929 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Standing-Storm** [comment]
This looks to be a problem with the hardcoded SWAP_POS spell function.  When I tested it in Magiclysm and debugged in Spirit Walk (which swaps places with one of your summons) and Wrathful Spirits (which summons spirits you can teleport to), the exact same thing happened: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/741a707e-2e7a-4a55-83a7-6064ca91970a)
