### ISSUE TITLE
New random characters are babies (e.g. 2 years old)

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#68059]
### Describe the bug

Start a new random game, look at characters age.

### Attach save file

N/A

### Steps to reproduce

Start a new game with default scenario. 

### Expected behavior

Characters should be some minimum age at least - not babies.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: a1c4973 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ZhilkinSerg** [comment]
```DIFF
diff --git a/src/profession.cpp b/src/profession.cpp
index a46f97414bd..b18f7ac8ba0 100644
--- a/src/profession.cpp
+++ b/src/profession.cpp
@@ -195,8 +195,8 @@ void profession::load( const JsonObject &jo, const std::string_view )
         _description_male = to_translation( "prof_desc_male", desc_male );
         _description_female = to_translation( "prof_desc_female", desc_female );
     }
-    optional( jo, was_loaded, "age_lower", age_lower );
-    optional( jo, was_loaded, "age_upper", age_upper );
+    optional( jo, was_loaded, "age_lower", age_lower, 16 );
+    optional( jo, was_loaded, "age_upper", age_upper, 55 );

     if( jo.has_string( "vehicle" ) ) {
         _starting_vehicle = vproto_id( jo.get_string( "vehicle" ) );
```

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/where-are-the-feral-children-and-what-happened-to-the-unborn-ones/28081/22
