### ISSUE TITLE
Zombie dog error

### ISSUE THREAD

**Issue by AshCrimsoner** [CleverRaven/Cataclysm-DDA#68064]
### Describe the bug

Error message

### Attach save file

[Cusseta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12565961/Cusseta-trimmed.tar.gz)

### Steps to reproduce

Zombie dog attacking giant naked mole-rat

### Expected behavior

Error message every time the dog attacks the mole

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

 DEBUG    : Z-Level view violation: the zombie tried to attack the gigantic naked mole-rat.

 FUNCTION : bool monster::melee_attack(Creature&, float)
 FILE     : src/monster.cpp
 LINE     : 1691
 VERSION  : d6ec466

**Comment by Leonkoithara** [comment]
Hi this can be closed as the Giant naked mole rat was obsoleted in #64960
