### ISSUE TITLE
Game now crashes upon trying to load world, Abnormal Termination

### ISSUE THREAD

**Issue by MurmurHummer** [CleverRaven/Cataclysm-DDA#68073]
### Describe the bug

My last play, suddenly ended up crashing midway. (I think perhaps there were too many tiles for the game to load, I was just walking down an empty road, without pausing to allow the game time to think which it hates. So anyway it crashed.)
No biggie, I'll make a new game.
I cannot... get into the character creator.
Maybe just that world is bugged?
No, no, a fresh world still will not allow me to enter.
So, do I need to do a reinstall? (I hope not, I had to fiddle with settings and sound settings and keybindings and how do I transfer my save files? I don't want to lose some of them.)

### Attach save file

N/A

### Steps to reproduce

I don't think I can, I think this is a game-specific thing because the crash broke some of my game's files.

### Expected behavior

Enter character creator, like I have before.

### Versions and configuration

OS: Windows 10
Game Version: 0.G Gaiman
Graphics version: Tiles --- Chibi Ultica and ASCII. (Unrelated probably, but some of the tilesets also crash the game in the same way it's doing now, so I just didn't use them before. But these ones used to be fine.)
Ingame language: English - or default, if that's different.

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12566814/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12566815/debug.log)

**Comment by RenechCDDA** [comment]
Judging from the error it seems to be crashing while reading from your cache. Can you (first back it up - for us!) try deleting the top-level cache folder?

(This one!)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/9922d963-3d34-4521-a9c9-b1cb0dd04404)

**Comment by MurmurHummer** [comment]
Thanks for the suggestion. I backed up, then deleted the contents, then tried again. Unfortunately, it still crashes.
Is there anything else I should try?
![Capture](https://github.com/CleverRaven/Cataclysm-DDA/assets/144566671/257a4e60-0c5b-4ee2-9245-f8531dd12e15)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12566906/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12566907/crash.log)

**Comment by RenechCDDA** [comment]
Well, you can try installing a new fresh copy of CDDA in another location. If *that* crashes, it's not a cache problem.

**Comment by MurmurHummer** [comment]
Strange, I thought a fresh copy would work. But it didn't, it crashed too.
Maybe. I need to try the tried-and-true restart the PC trick. I'll try it and see how that goes.

**Comment by MurmurHummer** [comment]
Restarting the PC did the trick. The problem must have been in my computer's cache or memory or something. I'm so glad that the game works correctly. :) Thank you!
