### ISSUE TITLE
[Magiclysm] Spider climb spell bug

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#68088]
### Describe the bug

When I cast spider climb I get these error messages and the spell doesn't seem to work

DEBUG    : invalid effect type id effect_magus_spiderclimb
FUNCTION : const T& string_id<T>::obj() const [with T = effect_type]
FILE     : src/effect.cpp
LINE     : 94
VERSION  : 36b04f0

DEBUG    : Invalid effect, ID: effect_magus_spiderclimb
FUNCTION : void Creature::add_effect(const effect_source&, const efftype_id&, const time_duration&, bodypart_id, bool, int, bool, bool)
FILE     : src/creature.cpp
LINE     : 1512
VERSION  : 36b04f0

### Attach save file

[Mundete-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12570637/Mundete-trimmed.tar.gz)

### Steps to reproduce

1. Cast spider climb magus class spell
2. Get the error messages

### Expected behavior

I expected to be able to climb around while shooting like a madman muhahahah

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 36b04f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
@Standing-Storm did you accidentally remove some effects in #67914?
https://github.com/CleverRaven/Cataclysm-DDA/pull/67914/files#diff-a0e9d3e6d2424de17a9439449de41273fd9341481efc25d94f0318d22a2834baL728?

**Comment by Standing-Storm** [comment]
Oh dammit. -_-
