### ISSUE TITLE
Refactor Field types to use damage type

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#68083]
### Is your feature request related to a problem? Please describe.

There are more damage types than the ones that fields are hardcoded to act as.  Damage types have been jsonified and the types of damage that fields can do have not.

### Solution you would like.

I would like for fields to have a selectable damage type or types.

### Describe alternatives you have considered.

None

**Comment by ZhilkinSerg** [comment]
I think all field damaging functions are hardcoded in `map::player_in_field`. Maybe we should utilize EOC in there.
