### ISSUE TITLE
Builting railroad rubble should not take such a long time

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#68096]
### Describe the bug

You need to spend a whole 40 minutes laying 500 unit gravel on the ground, that's ridiculous.

### Attach save file

N/A

### Steps to reproduce

1.Builting a railroad rubble.
2.Then 40 minutes gone.

### Expected behavior

The time required to lay a piece of gravel on the floor should not exceed 5 minutes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 59b8ed4 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
If a real railroad was built by just haphazardly spreading gravel over an area and then placing tracks on top it would fail very quickly. A lot more work goes into the construction of a (rail)road intended to sustain a substantial amount of heavy traffic.

**Comment by Rocket-F-1024** [comment]
> If a real railroad was built by just haphazardly spreading gravel over an area and then placing tracks on top it would fail very quickly. A lot more work goes into the construction of a (rail)road intended to sustain a substantial amount of heavy traffic.

The demand for gravel during the laying of ballast does require some calculation, but the laying of ballast itself does not require much time, and the ballast itself requires frequent maintenance
