### ISSUE TITLE
Nyctophobia and ramps. 

### ISSUE THREAD

**Issue by VladTechGames** [CleverRaven/Cataclysm-DDA#68104]
### Describe the bug

Currently when a Nyctophobe attempts to transfer to a dark ramp with a light source on their person they are incapable of doing so, if the ramp is on a different z-level.

This issue also sometimes extends to stairs, but the player can transfer through and have a panic attack rather than being unable to progress.

### Attach save file

N/A ~ Trivial to reproduce.

### Steps to reproduce

Create character with nyctophobia.
Turn on flash light.
Go to any ramp between multiple Z-levels, such as in an office or police department.
Attempt to go underground.

### Expected behavior

I expected to be able to move from one side to the other, but it does not.

### Screenshots

![Capture2](https://github.com/CleverRaven/Cataclysm-DDA/assets/144631237/e42e9f5b-2448-40ee-a562-4787a68069fd)
![Capture](https://github.com/CleverRaven/Cataclysm-DDA/assets/144631237/c787a0a3-9f47-4850-a6b0-1b1f5bdacb22)

### Versions and configuration

OS: Windows 10
Game version: 7e9f117
Graphics: Tile
Language: English.
Mods: No fungal monsters, all default mods.

**Comment by ashGlaw** [comment]
Just a thought, it's not a fix but a workaround, you could toss a light into the empty space above the bottom of the ramp, let it fall and illuminate the space below, and then hopefully proceed. I'm not certain it would work, but I would be very disappointed if it didn't. 

We need light to propagate across z-levels better than it does now
