### ISSUE TITLE
Allow activatable mutations to consume mana

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#68106]
### Is your feature request related to a problem? Please describe.

Working on Biomancer spells which apply mutations and it would be neat if I could make extremely low-cost spell that gives  a mutation but put the main cost onto mana (example--a "rapid regeneration" mutation that consumes mana instead of calories) rather than frontloading the cost into the spell.

### Solution you would like.

A "mana": true option that can be chosen the same way "kcal": true or "thirst": true are when defining a mutation.

### Describe alternatives you have considered.

Some kind of complicated EoC-heavy mess.

### Additional context

I've been thinking of doing a Biomancer mutation path ("Metamorphosist") and having mana-powered mutations would really open up the design space.

**Comment by Maleclypse** [comment]
So it gets a little confusing because 
```
// amount of mana added or subtracted from max
        std::optional<float> mana_modifier = std::nullopt;
```
Already exists but it impacts your max instead of current like say `thirst_modifier`.
