### ISSUE TITLE
Crash on canceling unload after some is poured

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#68115]
### Describe the bug

.

### Attach save file

[0.C-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12589955/0.C-trimmed.tar.gz)

### Steps to reproduce

1. Open AIM, scroll to pot, examine.
2. Unload the pot of ~buttermilk~ heavy cream (in attached save).
3. Pour some into a 0.5l glass jar.
4. 3 charges are left to pour.
5. Press ESC to cancel.
6. The menu is still up and you can arrow UP and DOWN.
7. Press ESC again.
8. Game crashes.the 

TL;DR:
`/eU` `ENTER` `ENTER` `ESC` `ESC`

### Expected behavior

No crash, pot has remaining charges of buttermilk.

Also, the first ESC should close the menu.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: 0.C-79698-g38e387c65d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

crash and debug log didn't catch anything of interest

**Comment by Brambor** [comment]
I don't want to check on master, as I would have to rebuild for another hour. And that is no fun.

But my changes on my development branch should be unrelated...

**Comment by Kamayana** [comment]
Can reproduce on current master. I think you have a typo, though, it's the pot of _heavy cream_ that causes the problem, the buttermilk is in a plastic bottle that has no problems unloading.

It seems like the unload player activity isn't getting properly set to null on step 5.
