### ISSUE TITLE
Zomborg devourer dont drop cbms after dissecting

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#68126]
### Describe the bug

Zomborg devourer dont drop cbms after dissecting. And also zomborg devourer dont drop cbms of eaten zomborgs, so you lost cbms from them

### Attach save file

N/A

### Steps to reproduce

1. Spawn zomborg devourer
2. Dissect
3. See no cbms

### Expected behavior

Zomborg devourer is fusion of 2+ zomborgs. So it should drop x 2+ cbms and plus cbms of eaten zomborgs
I can copy past the cbm drop code by myself, but I cant understand, how can I make them drop cbms of other eaten zomborgs. And as I see, ZOMBIE_FUSE effects is coded in c++, but I dont know this kind of magick yet

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: a677ef2 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by KeremBabaG** [comment]
afaik zombie_fuse doesn't add the loot tables of eaten zombies. But you are right about x2 CBMs. I will make a pr for that

**Comment by KHeket** [comment]
> Why should CMBs from eaten zombies remain in the eater rather than being excreted, and why should they remain in a recognizable form rather than mashed junk?

Because, as the regular devouver drops items, as the zombies can merge with items and materials, like kevlar zombies, rusty zombies, because items from trafromed into slimes monster by blob drop items after death - zomborgs should do it too. Blob can work with flesh, but not alive matter it just leave in the body as a items. And when you are dissecting its body - you can find cbms

**Comment by PatrikLundell** [comment]
Do these critters devour or assimilate zomborgs? If the former I agree CBMs should either remain stuck in them or pushed out without too much damage. If the former they'd probably be destroyed by the chomping.

**Comment by KHeket** [comment]
As typed in zomborg devourer
"Human bodies, robots, and cybernetic enhancements fused together into a colossus, with heads and limbs both biological and robotic sticking out of its bloated body at grotesque angles.  The nature of the thing makes it difficult to estimate how close it is to dying."
So it dont chews other monsters, but fusing with them, making them part of it, and cbms of other fused zomborgs should be fine, but, I think, you will need more time to find cbms, because of chaotic anatomy of devourer

**Comment by actually-a-cat** [comment]
I can confirm this, my character has the bionic scalpels and enough skill to always harvest multiple CBMs from a zomborg corpse, but dissecting 10+ zomborg devourers from multiple groups produced nothing. 

Devourers have the same dissect definitions as regular zomborgs so it seems like they were intended to drop CBMs, and it's a bug that this doesn't work.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.G-12952. Dissected a zomborg devourer, got several CBMs.
![изображение](https://github.com/user-attachments/assets/c0ea0cb7-4552-4f14-9d0e-6d8d7561ba03)

> Zomborg devourer is fusion of 2+ zomborgs.

No, it's not. Zomborg devourer is just an evolved version of ordinary zomborg. Zomborg will evolve into a devourer no matter whether it's fused with someone or not.

Whether devourers should inherit loot tables of devoured monster is a different question. If it's still relevant, open another issue. Right now I'm closing this one.

**Comment by harakka** [comment]
Conceptually devourer absolutely is a fusion of multiple cyborg and non-cyborg bodies, not just a regular evolution the same way eg. brute becomes a hulk. The evolution is there to increase risk over time, not to mean one concretely becomes the other.

**Comment by Night-Pryanik** [comment]
@harakka I reproduced it on latest experimental, my screenshot is from there.

**Comment by harakka** [comment]
Okay,
> Can't confirm on 0.G-12952
confused me since we're on 0.I in experimental.

**Comment by Night-Pryanik** [comment]
> 0.I in experimental

Huh? We're approaching only 0.H if I'm not mistaken?

**Comment by harakka** [comment]
0.H is the next stable release that was branched off from experimental on 2024-01-01, which we are working toward stabilizing and releasing. Meanwhile experimental is progressing at its own pace and is labeled 0.I. At some point 0.I stable will be branched off and experimental will then be labeled 0.J, and so on. Just like always, we want bugs to be reproduced against experimental, so 0.I.

**Comment by Night-Pryanik** [comment]
I'm confused. I don't see 0.I in the list of branches available. Is it a current `master` branch?

**Comment by harakka** [comment]
Yes, 0.I is experimental and therefore the current master branch.

**Comment by Night-Pryanik** [comment]
> I don't know what 0.G-12952 is

That's how MSVS shows the version of latest experimental I compiled on my machine today.

**Comment by harakka** [comment]
Thanks for clearing that up, looks like at least both Windows toolchains are getting an incorrect version string when building locally.
