### ISSUE TITLE
Using Overmap Notes to create strings of text

### ISSUE THREAD

**Issue by zantimer** [CleverRaven/Cataclysm-DDA#68123]
### Is your feature request related to a problem? Please describe.

The overmap readability is quite the ubiquotous problem that isn't really that I can even expect to change, however, I have taken to "writing out" short strings of text via placing Notes to each other like demonstrated in Additional Context, and thought it'd definitely be nice to be able to do it more automatically, making it much more useful of a thing

### Solution you would like.

I could see it being as simple as introducing an new function and/or UI option, that would either loop the existing create_note function per character in passed string and going to neighbour tile  (X + index, Y) to place it, or enclose that within the function to be carried out if the number of non-whitespace signs before the first : delimiter is greater than one

### Describe alternatives you have considered.

doing it myself, which fell apart at "how hard can low level progr-OH MY GOD", genuinely don't know how to bite something seemingly as simple as that, though it's yet another thing making me want to understand it

apart from that, nothing comes to mind, as it's a very basic/fundamental thing in itself

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/99617630/86bc2236-5ef5-4c8f-9c34-ed7c60a3ccff)

**Comment by PatrikLundell** [comment]
It's very much a niche usage, as it relies on there being "irrelevant" terrain under your notes. If you look at the image, you can no longer see if there is forest or field underneath the SCRAP text, and so can't see if it ought to be possible to drive a vehicle there (in this case it should be easy to go around, but that's not always the case).

I'm not opposed to the introduction of an option, but I don't think I'd find much use for it.

**Comment by zantimer** [comment]
@PatrikLundell, it doesn't impact it all that much in all fairness, both with blinking and being able to hide/unhide notes in two keystrokes

In all fairness, it IS by all mean an niche thing - however, I do think it had made getting my head around the overmap much easier

It also could be "stretched" to, for example, "drawing out shapes" from notes so you could for example mark large areas easily and such

Another way would be utilising the city labels, that tend to be much bigger and more readable, though how they work, I have not a clue

**Comment by ilovehans10** [comment]
> It also could be "stretched" to, for example, "drawing out shapes" from notes so you could for example mark large areas easily and such

I love this idea. It could also pair nicely with the new feature that allows notes to be marked as dangerous. Being able to mark a line/rectangle of the map as dangerous instead of a circle would be great.
