### ISSUE TITLE
A few profession suggestions

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#68136]
### Is your feature request related to a problem? Please describe.

As I sit here in my apartment, looking at my fat belly wrapped in a cheap tank top, I began to realize that there are plenty of "professions" that I would like to see implemented into the game for the sake of roleplay; featuring characters in bad/difficult situations pre-cataclysm.

### Solution you would like.

Bum: Maybe you were down on your luck, struggling to find a job, or maybe you were too burnt out to care. Whatever your circumstances, you've been unemployed for a long time. Yet despite this, you're still standing here screaming "fuck the cataclysm!" (Referencing the 8 Mile movie starring Eminem.)
This class would basically be a hobo, but worse. Dressed in baggy clothes, like a hoodie, sweatpants and sneakers, and not equipped with any additional items, nor possessing any additional skills. For people who don't want to go full nudist, but pretty close.

Prostitute: It has been called the oldest profession in human history. Not that it makes you feel any prouder about what you did for a living. You were just lucky that your last "customer" didn't beat you to death as you made your escape.
Obviously, this is a class that comes equipped with raunchy clothing, as well as a number of condoms in whatever pockets they might have. They also come with some social skills, as well as a small skill in unarmed, for dealing with rowdy customers. They're still living on the fringes though, so nothing on the level of a cosplayer or high class escort, but perhaps more on the level of someone who's trying to advertise their body in an alleyway.

Paperless: You've been forced to flee your home country, either because of political oppression, instability, famine, or because you did something really bad. Forced to use the "high risk, low reward" method of human smuggling, you eventually ended up in New England, without any legitimate paperwork. Forced to live off the grid ever since you arrived, the cataclysm has suddenly made you one of the least "alien" things around. Perhaps your survival of harsh circumstances might give you an edge at the end of times...
This is basically the closest you can get to a true urban survivalist. These are grey people who do everything in their power to blend in, whilst at the same time being very vigilant about their own safety. They try to dress "normally" whilst also keeping their features hidden, covering their faces with either baseball caps or scarves, with long sleeved shirts, full length pants, a belt and plain shoes. They don't carry blatant weapons, but do carry a folding knife for the sake of "utility." Needless to say, they are skilled liars, with plenty of social experience so as to blend in, along with the various other skills needed for independance, like making your own meals, fixing your own household gadgets, defending yourself from thugs and staying anonymous when online transactions take place. Despite their harsh circumstances, this "profession" is fairly powerful as far as CDDA is concerned.

### Additional context

I sometimes wish my autism delved more into programming and less into storytelling...

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide-Professions
