### ISSUE TITLE
Coagulant Weave is causing an error, not doing anything

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#68135]
### Describe the bug

Using Coagulant Weave causes an error with no effects.

### Attach save file

[island survival-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12610083/island.survival-trimmed.tar.gz)

### Steps to reproduce

1. if not enough blood, use spellcasting menu to Consume Blood
2. try using Coagulant Weave active mutation
3. get error 

### Expected behavior

The effect working.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77662682/d3c4479a-e708-4534-88a0-0b2996e047f9)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.985 (20H2)
- Game Version: 9ac6153 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by psuedolet** [comment]
It should probably call the blood_weave effect, or the blood_weave effect should be renamed vamp_blood_weave. I'll leave it for someone familiar with the mod.
