### ISSUE TITLE
There should be a way to communicate trader restock to player

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68132]
### Is your feature request related to a problem? Please describe.

From what i've seen in the devcord, there seem to be some confusion on when a trader has restocked their goods. It's not clear to the player in game when a restock gonna happen without asking someone outside the game.

### Solution you would like.

Add something like "X days before restock" or "Days since last restock: X" in traders' trading ui.

### Describe alternatives you have considered.

Communicate it a bit more subtlely, though i'm not sure how.

**Comment by KeremBabaG** [comment]
"subtly" may be something like "come back in x days, I'll have some new stuff in stock", idea itself definitely needs a pr

**Comment by estebandellasilva** [comment]
or if this feature ... iss to be improved somewhat ... you can get them a two way radio and ask ... "when new stuff iss gonna be available"

**Comment by RenechCDDA** [comment]
Was resolved by the linked PR
