### ISSUE TITLE
CrazyCata ideas

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68143]
### Is your feature request related to a problem? Please describe.

Collection of some silly ideas.

LMFAO Shelter - shufflin' zombies - Very fast, but blind and deaf zombies that stumble every turn

Money trees - can be harvested for money

Feral redditor - Wields a torch, tries to light you on fire. Maximum skills, and wears full plate. Randomly parrots "No pockets!", "No skill decay!", "No portal storms!", and "No fungals!". 

### Solution you would like.

Add these things.

**Comment by PGR-14** [comment]
The redditor sounds like hell to go against. Make it a moderator (Severely Obese) & make it have a heart attack after a # of turns

**Comment by kevingranade** [comment]
Omnibus (multiple unrelated topic) issues like this are NOT VALID.
If you want to discuss suggestions, discord and discourse (linked from the readme) are the place to go.
Small suggestions are fine if valid and meaningful, but they MUST have their own issues.
Related issues are also fine if there is some need to discuss fixes or additions together.
