### ISSUE TITLE
Open Container functions and variables have inconsistent and/or confusing names

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#68149]
### Is your feature request related to a problem? Please describe.

There are a number of functions and variables relating to items that cannot be stashed without spilling their contents - buckets and bowls and the like. These kinds of containers are referred to in multiple different ways inside the code, and some of these names are even fairly misleading.

`will_spill` and `will_spill_if_unsealed` functions in item/item_contents/item_pocket. Counterintuitively, these functions return false even if the item is empty and has no contents to spill.

`is_bucket_nonempty` item function returns false if the item could spill and also has contents to spill. If anything should be named `will_spill` it'd be this. Also using the word "buckets" are the many instances of the `allow_bucket` parameter.

- `will_spill` function
- `will_spill_if_unsealed` function
- `handle_spillable_contents` function
- `is_bucket_nonempty` function
- `allow_bucket` parameter
- `open_container` pocket_data json parameter
- `spill_open_pockets` function

All these different terms refer to the same thing, and many of them have problems. `will_spill` and `will_spill_if_unsealed` counterintuitively return false even if the item is empty and has no contents to spill - `is_bucket_nonempty` is the one that only returns false with contents to spill, and yet is named differently. The term "bucket" for these containers is confusing because, for one, they can be sealed until opened for the first time, unlike actual buckets, and it's also odd to use "bucket" to refer to items like opened plastic wrappers. "open_container/pocket" makes sense, but it is weird that a pocket can be called both "sealed" and "open".

### Solution you would like.

I'd expect a consistent terminology among the code for referring to this specific property. I honestly couldn't think of a term I'd be fully enthusiastic about, though - I just couldn't think of a concise, not-already-used term for containers that have an opening that cannot be closed or resealed. "Concave", "spillable", "always open", "unsecure contents", nothing feels right to me. I'm making this a request and not a PR specifically to see if anyone else has ideas.

### Describe alternatives you have considered.

This is a completely non-player-facing thing, so it's nonessential. At the very least, though, I think `will_spill`, `will_spill_if_unsealed`, and `is_bucket_nonempty` should be renamed, because those are particularly misleading.

**Comment by CHCOOH** [comment]
How about "no_lid" etc.

**Comment by inogenous** [comment]
Another option to consider: `watertight` (already used in some places).

**Comment by Kamayana** [comment]
I just thought of `enclosed` and kinda like it.
