### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#68144]
### Is your feature request related to a problem? Please describe.

Just a few ideas I had:

Character Creation: 
- Sub-groups: Some professions should have variants, for instance the rideshare driver could have variants that have a truck or minivan instead of a car, or the football player could have variants like Linemen, Running backs, & Linebackers.
- Addictions: You should be able to add your own addictions & severities.

Items & Features:
- Garage generators: Garages should have a chance to have a generator in them.
- Trading Stations: Free merchants could spawn there w/ random stuff for sale, might be seen being attacked by bandits.
- Paint: The ability to paint cars, could lead to some pretty cool designs as well as making vehicles look better. For instance, camo paint for some Military vehicles, yellow paint for school busses, & random paint on regular cars would help w/ making things look lived in
- Shields: Already a mod (Compatible, I checked), pretty well done, simple, & just makes sense, so why not implement it? https://github.com/MNG-cataclysm/Shields https://github.com/CleverRaven/Cataclysm-DDA/pull/54692
- Object strength: Some objects should be able to be damaged by other damage types, for instance brick wouldn't get hurt by a cutting damage, but wood should. Also piercing damage would be useless for it.
- Boxing changes: Should be able to use w/ certain weapons like brass knuckles
- Ferals: Should shout out things when they see you? Maybe things like "FUCK THE POLICE!" or Laughter/screaming.
- Preferred tastes: A simple thing that may give your character more/less morale from things, for instance your character might like country music & hearty food, but may hate techno & sweets. Could also be modified so that "High-Class" professions could be horrified at the sight of a can of beans.
- Smoking: Nonsmokers should have a chance to cough when puffing a cigarette. If you have a (STARTING) nicotine addiction or have smoked 4-5 cigarettes, it doesn't happen.
- Flags: Some weapons should be able to rot or rust. For instance, a pipe could rust & be weaker, harder to wield, & flimsy (Tetanus too?), a baseball bat could rot & have similar things (Weaker, Flimsy, etc.), could be repaired by replacing parts, like if a fire axe is rotting, you could take off the head (Disassembly) & attach it to a new stick (Becomes an actual fire axe, more or less). You could also treat your items to stop them from rotting/rusting by putting on Borate (Boric Acid) for rot or Oil or Sodium Hydroxide + Potassium Nitrate (Maybe not?) for rust.
- Convention centers: They're empty, COMPLETELY EMPTY. I've found office supplies & soda. No costumes, no cool items, not even a poster. Why not a convention?

Mutagen & Traits:
- Crocodile: Kind of like the lizard one, but more aquatic, stronger, & increased size (Maybe up to large?)
- Rabbit, Mouse, & Rat: Get Anxiety & ADHD, rat also gets night owl
- Bird: Could get either Early bird or Night owl -> Nocturnal
- Anxiety/Paranoia(?): Kind of like Jittery +, if there's a lot of zombies near you (If you can hear them or see them), you'll get shaky hands & lower intelligence, but higher perception & strength (Adrenaline & looking around a lot)
- ADHD: Slower work speed/lower focus level, boredom, & slower reading time (Maybe not? Kind of trying to simulate not being focused), but additional dexterity only for combat.
- Early Bird: You'll wake up good to go, early (6-8?), tire & wear slower in the mornings, & aware, but past evening, you'll tire & wear a lot faster (Good for day raids).
- Night Owl: You'll wake up groggy (same stat & focus reduction as Dead Tired, but can be taken away w/ a cup of coffee), late (8-10?), Tire & wear faster in the mornings, & confused when you're waken up unnaturally (An alarm, loud noise, or attack), but in the evenings you'll tire & wear a lot slower as well as a bit of night vision (Good For night raids).
- Nocturnal: Kind of like a mix of light sensitive & Night owl, you'll get pretty good night vision on your own, less groggy, & better during the night, but if you're up during the day, you'll be confused & have stat reductions
- Bulky: Starting trait that makes you a bit slower normally, but encumbrance & weight slows you down less

MOM:
- Clairsentients should be able to see around them while they sleep, & wake when they see a hostile (Ignoring neutral & friendly    monsters, but waking when they see something like a zombie), or when something dangerous happens (Like a portal storm or being dangerously hungry/thirsty or being too hot/cold).

Professions: 
- Pugilist: A boxing profession cause... why not?
- Student: A small change, give them some caffeine addiction
- Medieval Re-enactor: You'd start off w/ medieval armor (Base version) & a good quality sword, pretty hefty point price.
- Suicide Survivor: Tried to hang themselves at the start but was saved. Starts w/ antidepressants & a rope (Maybe spiritual too?).
- Rioter: Someone who joined actual riots, starts w/ a rioter mask, Kevlar vest (?), & other things like that.

Creatures:
- Panicked Child: I'm thinking of some kind of thing you could do with the Gawky Guardian to calm both of them down 
- Quack Quarterback: Fast, armored, & throws one football at you, but pretty rare
- Lunatic Lineman: Slow, but tanky & strong. Doesn't throw anything, but can grab & Shove/push you around (Like a reverse grabber zombie)
- Feral Father & Dead Daughter: A father w/ an axe in hand, keeping her daughter safe, will ignore you unless you get close (Has some semblance of sanity? Maybe doesn't want to hurt you if front of his daughter?) & then attack
- Feral Firefighter: Wields a fire axe, kind of like how the policeman is a pipe feral +, this is an axe man +, fire resistant, & has a stronger swing. Spawns in Fire stations & rarely around the world
- Feral EMT: Has a syringe in hand w/ morphine, rarer than a lot of ferals & only in hospitals, but if he hits you, you get morphine
- Feral drunkard: I'm betting at least some ferals would be alcoholics, there'd be a variant with a bottle, a pool stick, & brass knuckles. Would spawn in a bar (Or somewhere with a lot of alcohol), or somewhat randomly (Pretty rare).
- Feral Riot officer: Would be pretty slow, but very tanky & would have better perception than other ferals (Cop training)

**Comment by a-chancey** [comment]
I'll comment on what I can:

Character creation variants: I'd love this. We have starting location variants, vehicle would make sense as well. 

Addictions: we already have the ability to add them in backgrounds - unless you're talking about addictions to other things we don't have, which would require someone to add them. 

Garage Generators: +1, I like this. Even if they're just added as a rare entry to the garage vehicle spawn list. 

Trading stations: sometimes free merchant affiliated NPCs set up temporary shops at roadside stops (maybe it's rest areas, it's one of the small POIs) during the day. I've only managed to catch them once or twice. 

Paint: painting something would require a graphical tile to be made for that color, but I think it would be neat, just extra work on tileset makers. 

Shield: we still don't have dual wielding, so maybe soon?

Object strength: smashing just uses the highest bash damage you currently have equipped. Smashing a brick wall with a katana would be useless. And since terrain doesn't have HP, repeated cut attacks against a tree wouldn't be trackable currently. You can certainly bash down a tree with enough strength, but there's actions tied to tools to cut them down (activate an axe). 

Boxing: The current weapons for martial arts were audited last year, I'm sure there's a reason boxing is so limited. 

Yelling ferals: shock zombies do this in crazy cataclysm and it's hilarious. 

Preferred tastes: We already kinda have it for food (like intolerances and sweet tooth). Music would add micromanagement to a passive feature that I don't think people would like, though. Imagine losing morale because a country song randomly played. You'd need to be able to make playlists or skip tracks which seems like unnecessary busy work. I did want to add a bedazzler and a "tacky" trait as the antithesis to stylish lol. 

Smoking causing coughing should be a thing for sure. Even long time smokers cough. 

Item deterioration: the general damage kinda covers this, but I'd love to see it more in depth. There's a desire for item "faults" like engines can have, this would fit in. 

Convention centers: I think they should be makeshift (trashed) FEMA camps. But an abandoned convention could be neat as well

Traits: I like the ADHD and anxiety traits. I think ADHD should also make me randomly stop doing long term tasks like reading/crafting. Especially if I have a handheld game system or arcade machine nearby. I also like bulky.

**Comment by PGR-14** [comment]
Shields: I meant like wearing one, plus maybe a mini direction thing? (See the discussion link I put)
Object strength: I was thinking of a fire axe on a wooden wall, it would break it fast
Suicide survivor: I don't know, I was thinking of Irony? Bad idea anyway

**Comment by PGR-14** [comment]
> Character creation variants: I'd love this. We have starting location variants, vehicle would make sense as well.
Yeah, it would be super handy, w/ more ability to customize.

> Addictions: we already have the ability to add them in backgrounds - unless you're talking about addictions to other things we don't have, which would require someone to add them.
Makes sense, I was thinking of like a custom amount of addiction, like a light, medium, & heavy variants of them, kind of like the 2 caffeine addictions

> Garage Generators: +1, I like this. Even if they're just added as a rare entry to the garage vehicle spawn list.
Yeah, it would make sense

> Trading stations: sometimes free merchant affiliated NPCs set up temporary shops at roadside stops (maybe it's rest areas, it's one of the small POIs) during the day. I've only managed to catch them once or twice. 
Never seen one

> Paint: painting something would require a graphical tile to be made for that color, but I think it would be neat, just extra work on tileset makers.
Just replace the vehicle's silver look w/ a different color (Maybe w/ the paint bucket?)

> Shield: we still don't have dual wielding, so maybe soon?
I was thinking of wearing one & a small directional thing: [https://github.com/CleverRaven/Cataclysm-DDA/pull/54692](url)

> Object strength: smashing just uses the highest bash damage you currently have equipped. Smashing a brick wall with a katana would be useless. And since terrain doesn't have HP, repeated cut attacks against a tree wouldn't be trackable currently. You can certainly bash down a tree with enough strength, but there's actions tied to tools to cut them down (activate an axe).
I was thinking of a wood/log wall being hit w/ something like an axe, some terrain should have a tag or value that allows a certain amount of cut damage through, for instance a brick wall would be basically immune, while a desk should have little to none.

> Boxing: The current weapons for martial arts were audited last year, I'm sure there's a reason boxing is so limited.
Probably, but it would make sense to be able to wield brass knuckles w/ it (Does it do extra unarmed damage if you're wearing it?)

> Yelling ferals: shock zombies do this in crazy cataclysm and it's hilarious.
Yeah, might lead to zombies crowding around them? But they also could be an alarm for players & zombies alike, for instance a player moving around a building & hearing a feral outside, or a feral seeing a player & yelling, attracting zombies.

> Preferred tastes: We already kinda have it for food (like intolerances and sweet tooth). Music would add micromanagement to a passive feature that I don't think people would like, though. Imagine losing morale because a country song randomly played. You'd need to be able to make playlists or skip tracks which seems like unnecessary busy work. I did want to add a bedazzler and a "tacky" trait as the antithesis to stylish lol.
I was pretty tired when I wrote it, but maybe for the food there could be specific tastes, like you might like chocolate & citrus, but not fruity flavors or overly sweet things

> Convention centers: I think they should be makeshift (trashed) FEMA camps. But an abandoned convention could be neat as well
Yeah, I really hate that they don't have anything cool in them.

> Traits: I like the ADHD and anxiety traits. I think ADHD should also make me randomly stop doing long term tasks like reading/crafting. Especially if I have a handheld game system or arcade machine nearby. I also like bulky.
The Old Veteran could have something similar, but w/ a tiny bit of hallucinations (Only stuff like gunshots, yelling, & a helicopter maybe?) to simulate something like PTSD

> I really like the flavor of the feral parent and child; it might be a good fit for the rare barn and broken cabin location. The medieval re-enactor should probably have the mid-level armor and weaponry; a LARPer might have the cheap junk steel stuff, and a HEMA enthusiast might have the authentic quality weapons. The suicide survivor player idea is... probably not advisable; it's something that could be really easily upsetting to folks.

The suicide survivor is a pretty bad idea on my part (I think I was doing something w/ irony?), the LARPer & HEMA profs should also start w/ a martial art like Barbaran Montante or medieval swordsmanship, & the Feral parent & Dead daughter could reinforce the idea that some ferals have some semblance of sanity (I.E. That one survivor story where they realized what was happening)

**Comment by kevingranade** [comment]
Omnibus (multiple unrelated topic) issues like this are NOT VALID.
If you want to discuss suggestions, discord and discourse (linked from the readme) are the place to go.
Small suggestions are fine if valid and meaningful, but they MUST have their own issues.
*Related* issues are also fine if there is some need to discuss fixes or additions together.
