### ISSUE TITLE
Xedra Evolved vampires having trouble exploring during night raids

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#68151]
### Is your feature request related to a problem? Please describe.

I'm playing a vampire with Sky Island mod. Due to the nature of the mod, if I try doing a night raid I almost always end up in an unexplored part of the map and since it is dark I can only see my current overmap tile.
Wandering through the world blinded isn't fun.

### Solution you would like.

Some sort of ability that would illuminate the surroundings briefly, maybe a "Brilliant light" or "lightning bolt".
Artifacts can have an effect that illuminates everything around the player, turning it day for a few minutes. That allowed the player to reveal map terrain as if it was day.

### Describe alternatives you have considered.

The ability working like Satellite View spell from Mind over Matter, revealing a circular region around the player. That would also reveal terrain underground, which isn't ideal.
Raiding during day, bringing an umbrella.

**Comment by Standing-Storm** [comment]
> The ability working like Satellite View spell from Mind over Matter, revealing a circular region around the player. That would also reveal terrain underground, which isn't ideal.

It's possible to set it up so it only works outdoors--see the Earthshaper spell [Reading the Earthbones](https://github.com/CleverRaven/Cataclysm-DDA/blob/d6d150c655ea73070f68f7a8855173cc2f565092/data/mods/Magiclysm/Spells/earthshaper.json#L768) (that one works on Z level 0 or below but you could easily have a version that only works if you're outside).
