### ISSUE TITLE
15x (!) increase in test run time

### ISSUE THREAD

**Issue by ehughsbaird** [CleverRaven/Cataclysm-DDA#68154]
### Describe the bug

After https://github.com/CleverRaven/Cataclysm-DDA/pull/67997, running the full suite of tests takes 3 hours. If that is reverted, it takes 12 minutes.

### Attach save file

N/A

### Steps to reproduce

1. Build tests
2. Run tests
3. Wait 3 hours for tests to complete
4. Revert f12487cefcdd8c18f70ce68f73e09826bdced18d
5. Build tests
6. Run tests
7. Wait ~12 minutes for tests to complete

### Expected behavior

Tests take much less than 3 hours to run.

### Screenshots

`perf` profile:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/44244083/3d7cf286-1a73-4cb6-aa9c-28010801ac03)

### Versions and configuration

Commit d6d150c655ea73070f68f7a8855173cc2f565092

**Comment by RenechCDDA** [comment]
I noticed that my last local test run took an astounding 2 hours, 15 minutes. Previously test runs were around 30 minutes (45 if I was actively using the computer for other things). This is definitely a problem.
