### ISSUE TITLE
A couple of factions for more Cataclysm

### ISSUE THREAD

**Issue by Rabadash94** [CleverRaven/Cataclysm-DDA#68157]
### Is your feature request related to a problem? Please describe.

Cataclysm needs more factions.

### Solution you would like.

Two interesting factions that should be in the game.

- Anarchists

For many, the Cataclysm meant the end of everything they loved, their hopes and dreams. But for others it means the opportunity to start over without the entire corrupt system that was, after all, responsible for their own destruction. Many survivors decided to take advantage of the fact that nothing stood in their way to live in freedom. But they know that might not last long. There will be those who will try to remake everything, including everything that brought the world to its end. Anarchists are willing to prevent this.
And for this they are eager to find someone to take care of the dirty work. Their missions could be to wipe out other factions (Free Merchants? The Old Guard? Who knows?), or at least sabotage their attempts to restore some semblance of order. Perhaps they could get along with bandits, and could even grant the player safe passage to deal with them if they consider the player true to their ideals.

- Mad Scientists

If there is something that a good scientist knows very well, it is that nothing can stop the progress of Science, not even the end of the world. Even more, the Cataclysm has only opened a great field of possibilities that a superior mind should take advantage of to expand their knowledge. The mad scientists are at it, and they have many theories that they are eager to test. Zombies are incurable, but could they be tamed to be used as workers... or soldiers? Can Portal Storms be artificially caused and controlled? What other mutagens are out there? Is there anything that cannot (or shouldn't) be converted into a CBM? Is it possible to communicate with Triffids?
Their missions would consist of obtaining all kinds of research materials, including samples (very strange samples) or even guinea pigs if the player is not willing to be one. All, of course, in order to restore society.

These factions may need some background content, but they remain ideas for the future.

**Comment by I-am-Erk** [comment]
Personally - and I am not writing here as a dev, but as a player, so don't consider this a deterrent to creativity - I'd like to see more work done on the existing factions to add depth, before adding new ones. For example, a mad scientist faction could easily a subgroup within the Old Guard or the Raiders. An anarchist commune could become a subplot at Tacoma Ranch.

These are good things though and we do need more factional story development.

**Comment by Rabadash94** [comment]
>For example, a mad scientist faction could easily a subgroup within the Old Guard or the Raiders. An anarchist commune could become a subplot at Tacoma Ranch.

Yes, and the subplot at Tacoma Ranch could be a possible consequence of the refugees knowing about the Old Guard continuing the experiments that caused all their problems.

**Comment by PGR-14** [comment]
Maybe the Mad Scientists could be a bigger part of XEDRA, cause HUB 01 & HUB 02 were XEDRA labs, but they seem (mostly) sane, so the Mad Scientists should be almost insane (Not feral) & test on themselves w/ mutagen & CBMs

**Comment by I-am-Erk** [comment]
Mad scientists could also be some kind of splinter related to a hub01 side mission

**Comment by TheSaddestGoomba** [comment]
Isn't there a university based faction in the works, the Library? I feel that could fit a few mad scientists.

I've had thoughts of making an independent mad scientist NPC related to the frog updates. Some loony holed up in a swamp shack with a makeshift lab. They're obsessed with amphibians, studying new mutant ones and possibly becoming a mutant/mutating others. I like the idea of being able to convince them to join one of a few factions with different outcomes. Doctor for the commune, researcher for the library, mutagen supplier for the raiders, etc.

**Comment by PGR-14** [comment]
> Isn't there a university based faction in the works, the Library? I feel that could fit a few mad scientists.
Yeah that would be a good idea, maybe there could be factions within the factions? Like for instance the university could be one big faction, but there could be small groups formed from pre-existing circles like the Science AV club, Varsity Football, & HSAVE club (Pacifists). There could be some good relationships between them, for instance the Jocks could be the people that scavenge & guard the place, while the Gifted & AP kids could work/make things they need, & everyone else being kind of like the people in the Refugee Center.

**Comment by huix11** [comment]
t
