### ISSUE TITLE
Dropping items in a filled vehicle container should NOT place remaining items on ground

### ISSUE THREAD

**Issue by TheCarlito** [CleverRaven/Cataclysm-DDA#68161]
### Is your feature request related to a problem? Please describe.

I'm sure every player has experienced the annoyance of dropping items in a vehicle container to the point the container was filled, resulting in remaining items being placed on the ground beneath the vehicle.  Not only is this unrealistic and a waste of time, the notification that it has happened can easily be missed resulting in items being left behind or damaged when the vehicle moves away.

### Solution you would like.

Ideally, the drop process should simply be halted when the vehicle container is full so that any remaining items are kept in the player inventory.

### Describe alternatives you have considered.

Alternatively, I guess the player could be asked if they want to continue dropping items after the vehicle container is filled, if we want to keep the ability to teleport items through the floor of the vehicle for some reason.

### Additional context

I'm finally bringing up this issue after yet again leaving my acetylene torch behind because I didn't see the message that the vehicle container was filled.

**Comment by tofilwiktor** [comment]
I can try working on this. Where can I find the relevant code?

**Comment by Leonkoithara** [comment]
@tofilwiktor I just created a branch to fix this issue. It is working on my local machine will be creating a PR soon.

**Comment by TheCarlito** [comment]
Wow!  You all don't mess around.  Thank you!

**Comment by Night-Pryanik** [comment]
Related: #20727.
