### ISSUE TITLE
Visibility does not update while reading

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#68174]
### Describe the bug

Visibility does not update while reading.

### Attach save file

[Lorman-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12642109/Lorman-trimmed.tar.gz)

### Steps to reproduce

1. Start reading a book shortly before sundown.
2. Keep reading well into the night despite the fact that it should be too dark.
3. Stop reading in the middle of the night.
4. Try to read again.
5. Fail.

### Expected behavior

Visibility should update while reading to prevent the ability to keep reading into the night despite it being too dark to do so.

### Screenshots

![daylightnoupdate](https://github.com/CleverRaven/Cataclysm-DDA/assets/45959491/d4727d6f-5acb-44be-9ecf-6ebc95f1511c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: bb0bdee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Only recent item I found that could be related is: https://github.com/CleverRaven/Cataclysm-DDA/pull/68155

**Comment by CayoDaves** [comment]
I am also having this issue - it effects anything that takes a long time to perform. I have attached pictures of the same thing happening while performing a long crafting action.
![during](https://github.com/CleverRaven/Cataclysm-DDA/assets/92031130/2beb6fe2-f950-44c6-8a4b-3eae4682fb3e)
![before](https://github.com/CleverRaven/Cataclysm-DDA/assets/92031130/71a809c7-cf64-4842-ad81-6c70b8a26066)
![after](https://github.com/CleverRaven/Cataclysm-DDA/assets/92031130/13bd54a2-bdcd-4cec-8a56-41df42a2f037)

**Comment by Leonkoithara** [comment]
I can also confirm this issue does indeed occur
