### ISSUE TITLE
Use ally's items for crafting.

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#68182]
### Is your feature request related to a problem? Please describe.

Whenever crafting, include allies components and tools in the crafting menu. Even if they are sleeping, crafting or doing other activity. It should simulate the crafter taking items from allies who wouldn't protest. Sleeping, crafting, etc. shouldn't be disturbed.

Also, it would solve this unintuitive behaviour:
> Compiled and was able to get this work with a little bit of finagling.  _Didn't realize some of the tools were in my inventory and thus not available._   Love this!

_Originally posted by @Maleclypse in https://github.com/CleverRaven/Cataclysm-DDA/issues/67458#issuecomment-1670168536_
            

### Solution you would like.

I am currently implementing #68183 and would like the crafting_group* to share inventory to craft from. So the crafter who is the centre of crafting should gather items like normal AND include items (and tools) from nearby allies. That way you can order to craft items even if components and tools are in multiple allies's inventories. Also, when switching crafter*, the tools and components wouldn't change making for a more smooth experience.

The components should be used up from allies' inventories. If an ally leaves with a necessary tool, the crafter will stop crafting. So in the crafting menu, it should be noted if a tool is in an ally's inventory (just like when you use up a tool as a component).

While at it
```cpp
enum class usage_from : int {
    none = 0,
    map = 1,
    player = 2,
    both = 1 | 2,
    cancel = 4, // FIXME: hacky.
    num_usages_from
};
```
Here, `usage_from::player` should be changed to `usage_from::character`. `usage_from::allies` should be added to implement the idea outlined in this issue.

*These reference my PR: #68183 

### Describe alternatives you have considered.

Implementing it myself, however, sharing items goes a bit deeper and affects more things, so I focus on my PR.

The tools could be extracted from allies, so that they wouldn't run away with them, but not doing so probably is better. If they are extracted they have to be put somewhere. And then if you order friendly NPC at the base to craft, you suddenly miss a tool they extracted when you leave the base (for deconstructing a car in town, maybe).

Sharing including ally's crafting_inventory (that is the one they use for crafting, this includes items from their surrounding, so they would include their ally's crafting_inventory too recursively), this would create problems such as teleporting items with long chain of allies where everyone would have acces to everything everyone else has.

**Comment by Leonkoithara** [comment]
Hi I'm apprehensive of this change, if I understand correctly, of treating friendly NPCs items as items you own, as this might makes things less flexible in the long term. Such adding selfishness to NPC traits or NPC plotting to steal your items etc.

**Comment by Maleclypse** [comment]
> Hi I'm apprehensive of this change, if I understand correctly, of treating friendly NPCs items as items you own, as this might makes things less flexible in the long term. Such adding selfishness to NPC traits or NPC plotting to steal your items etc. But I would like to note I'm not too familiar with the codebase and maybe this is a minor change and easily extendable if need arises.

These are only NPCs that are in your followers and you already own all of their items if I'm understanding this correctly.  It shouldn't apply to NPCs that are not hostile but are not in your faction.

**Comment by Brambor** [comment]
Probably can use this:

https://github.com/CleverRaven/Cataclysm-DDA/blob/0a3e18c0043cc940c099ceab3bcba6aeb2ec1391/src/character.h#L3451-L3459

To this, add (original_crafter = false) as default. Add recursive call (only if original_crafter=true), asking all allied characters within reach for their inventory (origina_crafter=false, radius=0) - radius=0 for them to not find items around them too.
