### ISSUE TITLE
Staff of the Magi sprites are unaligned

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#68189]
### Describe the bug

all three staffs sprites appears higher than they should

### Attach save file

N/A, unnesesary

### Steps to reproduce

Spawn staff of the Magi(any and all)
hold it
behold

### Expected behavior

to be displayed correctly

### Screenshots

![YPfCnp6Ppg](https://github.com/CleverRaven/Cataclysm-DDA/assets/52901609/ae8ea22a-9b61-4466-bdfe-0d1f7e337d5b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: b7675d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Blazemod - Vehicle Additions Pack [blazemod],
    Disable NPC Needs [no_npc_food],
    Fungi Begone [Fungi_Begone],
    No Bionic Slots [no_cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
(AFAIK) tileset issues should be filed on the [tileset repo](https://github.com/I-am-Erk/CDDA-Tilesets/issues/new)

**Comment by NetSysFire** [comment]
They should, if this isnt caused by a SDL bug or something. But looks like a ultica bug so far.
