### ISSUE TITLE
All professions need to be stripped of any pre-installed CBMs

### ISSUE THREAD

**Issue by Leonkoithara** [CleverRaven/Cataclysm-DDA#68198]
### Describe the bug

Currently according to lore CBMs are other wordly technology developed and brought to our world by the Exodii. Therefore it doesn't make sense for a starter character, one who has never interacted with the Exodii faction to have CBMs pre-installed in them.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

All professions should have no pre-installed CBMs during character creation before starting the game. And perhaps boost the CBM spawns in some locations as the cataclysm progresses as several NPCs would gradually become aware of the Exodii and might have started trading with them.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 0.G-4160-gebf5857fdf-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by gettingusedto** [comment]
Is there any particular basegame profession that have pre-installed bionics in them?

**Comment by Leonkoithara** [comment]
Oh what they have been removed! I apologize I thought the Bionic student/soilders were still part of the game. I mostly use the random character preset to create characters and missed this change.
