### ISSUE TITLE
3-dimensional Z-level support, Core Part 2: efficiently process active items in 3D [$100]

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#6820]
Master Ticket #6822
This will be a "bounty issue" for the development of z-line track development.

This has following requirements:
Process active entities (items, monsters, fields, etc.) on all z-levels.
This should not cause a notable decrease in in performance on an average system.

**Comment by Coolthulhu** [comment]
Does this need something extra done?
The only "notable decrease in performance" I see here would be the larger number of monsters that can happen, but the only big multi-z-level structure we have right now is the lab and those seem to work fine, at least in my tests.

**Comment by kevingranade** [comment]
Yea, I may have accidentally addressed this sufficiently when I was
optimizing monster and item processing in general, if no action is needed
I'll look into closing out the bounty and redistributing the money to other
z-level bounties.

**Comment by Coolthulhu** [comment]
What about the first part (ie. process stuff on all z-levels)?
I extended the code to cover (almost?) all of the stuff and did some minor optimization (mostly fields, because fire was not "3D-ready"). Can I get a part of the bounty?

**Comment by kevingranade** [comment]
If you implemented part and the rest is unnecessary, you'll get the whole
thing.
