### ISSUE TITLE
mods/Magiclysm/mod_interactions/Defense_Mode Invalid or misplaced field name "copy-from" in JSON data

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#68205]
### Describe the bug

I got four errors when I did `save and quit` but I only saved two of them:

1.
```
 DEBUG    : (json-error)
Json error: data/mods/Magiclysm/mod_interactions/Defense_Mode/scenarios.json:3:17: <color_white><color_cyan>Invalid or misplaced field name "copy-from" in JSON data</color>

[
  {
<color_light_red>    "copy-from": "defense_mode_fortified",
</color>
               <color_cyan>▲▲▲</color>
    "type": "scenario",
    "extend": { "allowed_locs": [ "sloc_lake_retreat" ] },
</color>


 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 341
 VERSION  : d5f5217
```

2.
```
DEBUG    : (json-error)
Json error: data/mods/Magiclysm/mod_interactions/Defense_Mode/scenarios.json:5:14: <color_white><color_cyan>Invalid or misplaced field name "extend" in JSON data</color>

    "copy-from": "defense_mode_fortified",
    "type": "scenario",
<color_light_red>    "extend": { "allowed_locs": [ "sloc_lake_retreat" ] },
</color>
            <color_cyan>▲▲▲</color>
    "id": "defense_mode_fortified"
  }
</color>


 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 341
 VERSION  : d5f5217
```

### Attach save file

[Rainsville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12654448/Rainsville-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Press exc->save and quit
3. Observe error

### Expected behavior

Not throw error

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/96d5d34c-365e-482c-a3d3-c27741964ff7)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/eedf1add-8a16-4659-a114-c5e8c2a07962)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: d5f5217 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by b3brodie** [comment]
Further info: The defense mode scenario additions to the Mind Over Matter, Magiclysm, and XEDRA Evolved mods don't function beyond just throwing errors on world save.  They are intended to add extra locations to start defense mode in, but the starting location list doesn't actually contain the new areas.

![defense bug](https://github.com/CleverRaven/Cataclysm-DDA/assets/70666939/6a8fd88c-520a-4641-a5fc-0731b8650d04)

**Comment by RDru** [comment]
This is a bit annoying. Maybe someone should notify @Standing-Storm  ;)

**Comment by Standing-Storm** [comment]
> This is a bit annoying. Maybe someone should notify @Standing-Storm ;)

I don't know anything about Defense Mode--these specific locations were added (I think) in #68172
