### ISSUE TITLE
Let character to cross little creature

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#68201]
### Is your feature request related to a problem? Please describe.

Sometimes its happend, that you are runing from enemies - little cretures like tadpole (not mutant, just regular frog tabpoles) can  block your way. And there is lots of tadpoles at swamps, they are just became a living wall, and this happend with a lot of similar size creature, which are hard to hit because of size. But you can easily cross through it in reality, but in game it can be deadly because of blocking escape route. While you will try to unsuccessfully hit this little creatures - frog mothers, zombies and other enemies can kill you

### Solution you would like.

Make it possible to cross little creatures. The bigger creature is - the more move points it costs. As example
0 move points penalty for rat, frogs, tadpoles and other little creatures
150 move costs for medium sized doggos, gooze, turkey, etc
300 move costs for medium sized creatures, like zombie childrens, zombie crawlers, medium sized blobs, big dogs, pigs
And no way to cross through characther sized and bigger creatures

I dont know, how to realize it better in the game, but the simple solution for me is
Press "e" at the monster which you want to cross - if there is no items or things  to enteract, pop up message with question "Do you want to cross this creature? It will costs 150/300 move points (no points info for little creature), if you press yes - you will stand at the tile of the creature
If there is something else at the tile, you will just chooze the cross action from the list

And its also realistic for enemies. If you want to cross through child, zombie crawler or same sized enemy - they will get move bonus to attack you, but sometines its better to get damage from this creatures, than get hulk punch into face

**Comment by Rabadash94** [comment]
Instead of using the 'e' a menu could appear with the options to attack or cross when "collisioning" with one of those creatures (as happens when trying to cross certain bushes). Some way to configure the default option for those cases could also be added (the current one would be "attack").

**Comment by KHeket** [comment]
> Instead of using the 'e' a prompt could appear with the options to attack or cross when "collisioning" with one of those creatures

It will be good as additional, turnable on option, but not a deffault option, because me and I think big amout of players are comfy with auto attacking at the move direction. And you are very rarely using "e" button at the middle of the fight, so its better, as for me, solution
