### ISSUE TITLE
Wooden arrows/bolts recipe requires metalworking equipment

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#68223]
### Describe the bug

Just noticed that there are two pairs of crafting recipes: simple wooden small game arrow/bolt and **wooden small game arrow/bolt**. They have absolutely identical stats, but vastly different requirements. One requires only cutting 2, and the other needs cutting 2, hammering 2, anvil 3, a forge and a pair of flatjaw tongs, as if it's made of metal. But it is made of planks, just like the "simple" variant.

### Attach save file

N/A

### Steps to reproduce

I believe you need Fabrication 3 and Survival 1 to get the "simple" recipe, and the weird "metallurgy" wooden arrows/bolts are in The Fletcher's Friend book.

### Expected behavior

One of these recipes seems to be a mistake.

### Versions and configuration

Game version: 62505f6

**Comment by PGR-14** [comment]
I think the head is metal, & the shaft is wood

**Comment by eliotcougar** [comment]
> I think the head is metal, & the shaft is wood

Yes, in both recipes... However, one recipe is accessible on day 1, and the other is a late game recipe that requires a lot of equipment and proficiencies...
The only usefulness of the more advanced recipe is that it can be used to train those proficiencies, I guess…

Possible improvements I was considering while trying to fall asleep after a long game session:
1. adjust the item stats to make the more advanced arrows better in some regard at least
2. make crafting of the advanced arrows with proficiencies a lot faster than the more basic arrows, but a lot slower if you don't have the proficiencies. Right now it takes twice as much time without proficiencies, but equal time with proficiencies. Thus, the advanced recipe is pointless.

**Comment by PGR-14** [comment]
That makes sense, that should be fixed, but what about the ones in the hunting supply stores?
Also w/ the hunting supply stores, there should be arrow/bolt kits that allow you to make a few, along w/ the the tools to make them, like a few arrowheads, shafts, & feathers w/ glue & setting

**Comment by snipercup** [comment]
You say they are equal in stats, but this isn't true. The wooden small game arrow has a good chance to recover, while the simple wooden small game arrow has a low chance to recover. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/666cb232-79fd-42b4-85c3-1a1b244aec9d)

Increasing the damage doesn't make sense because the purpose of the arrow is to be used when hunting small game. I do see arguments for adjusting the recipe. Not the requirements, but time spent. Perhaps we can implement batch time savings here. The arguments for adjusting it would have to be based on reality though, so you'd need to explain how it is currently not realistic.

**Comment by Zireael07** [comment]
Strictly speaking chance to recover is not a stat (most people mean damage/to hit when they say "stats")

**Comment by eliotcougar** [comment]
> You say they are equal in stats, but this isn't true. The wooden small game arrow has a good chance to recover, while the simple wooden small game arrow has a low chance to recover. 

Oh, my mistake, I didn't notice that in-game... Also, apparently, the simple wooden small game arrow doesn't require steel chunks.
Then my main issue with the recipe is the requirements. I think it's too much. Anvil 1 (large rock) should suffice. The specific requirement for pair of flatjaw tongs (rare item) can be expanded with any type of pliers (to hold the chunk of steel in place). And the requirements for a forge should be removed or replaced with nearby fire.
All you do, compared to the more basic recipe, is shape a crude blunt tip from a chunk of steel with a hammer, and attach it to an arrow shaft.

**Comment by dchieh222** [comment]
> That makes sense, that should be fixed, but what about the ones in the hunting supply stores? Also w/ the hunting supply stores, there should be arrow/bolt kits that allow you to make a few, along w/ the the tools to make them, like a few arrowheads, shafts, & feathers w/ glue & setting

Can you providee an example of this?

**Comment by eliotcougar** [comment]
> > That makes sense, that should be fixed, but what about the ones in the hunting supply stores? Also w/ the hunting supply stores, there should be arrow/bolt kits that allow you to make a few, along w/ the the tools to make them, like a few arrowheads, shafts, & feathers w/ glue & setting
> 
> Can you providee an example of this?

Maybe these things?.. Probably not very widespread… https://goknapping.com/collections/arrow_making_supplies

**Comment by a-chancey** [comment]
Ooh! I know this one! They're actually not identical - just their damage is. 

Simple wooden arrows have a 1 in 6 chance of breaking each time they're fired. 

Wooden Small Game Arrows are way more durable - they only have a 1 in 35 chance to break - and they have another special flag: NO_GIB

Overkilling an enemy considerably (dealing its maximum HP in overflow damage after reducing the current HP to zero) _instagibs_ the enemy. As in, all you're left with is some meat chunks, fat and an explosion of blood if you're lucky. 

Both of those arrows have a 10x crit multiplier - so a compound hunting bow (10 base damage) will do 100 damage before armor modifiers with either of those arrows if you land a crit. A normal zombie will be one shot with a crit (they have 80hp). A zombie child (40hp) or dog (36hp) will be gibbed with the simple wood arrows. 

Rabbits have 8hp. Dealing 16+ in one hit gibs them, and if you're hunting small game for food, that's gonna be a problem.

**Comment by huix11** [comment]
t
