### ISSUE TITLE
Can't Recover Surveyor when Faction Camp Expansion is impossible.

### ISSUE THREAD

**Issue by EvanBalster** [CleverRaven/Cataclysm-DDA#68227]
### Describe the bug

A follower sent to survey for a faction camp expansion can't be recovered at the end of the three-hour surveying process.  This forces the player to wait 24 hours and execute an emergency recall.  It's not game breaking but feels a bit silly.

### Attach save file

n/a — somewhat easy to reproduce; I don't think a save is very helpful.

### Steps to reproduce

1. Recruit a follower.
2. Start a faction camp in location surrounded by tiles which don't support camp expansion.  eg: forests, fields or rivers.
  * This can be accomplished by rerolling evac shelter scenarios until you begin in a forested area.
3. Send your follower to survey for a camp expansion.
4. Wait three hours.
5. Choose the "Recover Surveyor" option at your bulletin board.

All possible selections will fail and the surveyor will not return.

### Expected behavior

If there are no valid overmap tiles for expansion, the survey mission should be prevented from starting.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13224671/4a434aec-1a4c-47d6-a290-1033802b9273)

An evac shelter located on a forested, swampy riverside.

### Versions and configuration

Experimental 2023-09-18, plus climbing-related commits from my own branch.

```
- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 092a80b61d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
```

**Comment by Kanexan** [comment]
I've definitely had this problem before when building a survivor camp in a vineyard farmhouse; I had to use the Emergency Recall system to get them back.
