### ISSUE TITLE
Z-level Master Tracking Issue

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#6822]
This is for tracking the various components of the z-level project.
Core Components:
#6818  #6820 #6821 #6823 #6824 #6825

Other needed components
 #6819 #7105
##

**Comment by Leland** [comment]
Closing this – work on these have been stalled for forever and the handful of remaining tasks are easily found in the Issues. If we really want to, we could move them into a project.
