### ISSUE TITLE
The kraken drowns!

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#68236]
### Describe the bug

apparently krakens can drown

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53508415/fe244c0f-445a-4e93-b1b4-8d7b188ddf30)

it was knocked into the deep water by a dinosaur

scylla also lacks the swim flag, so i assume the same problem applies to it

### Attach save file

[magic-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12680307/magic-trimmed.tar.gz)

### Steps to reproduce

spawn a kraken
change its tile and all the surrounding tiles into deep water
it'll drown

### Expected behavior

krakens can swim

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 46822d6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Rabadash94** [comment]
It missed the last lesson.

**Comment by Leonkoithara** [comment]
The issue is the kraken is not inheriting the SWIMS flag from its `copy-from` section. Currently it looks like only `looks-like` is being inherited from the parents for monster generation.
