### ISSUE TITLE
Swarms

### ISSUE THREAD

**Issue by Rabadash94** [CleverRaven/Cataclysm-DDA#68233]
### Is your feature request related to a problem? Please describe.

Currently, only zombies form hordes that roam the overmap, but they shouldn't be the only monsters capable of this, as there are others that have an instinct to gather in large groups.

### Solution you would like.

Add "swarms" of bees, wasps and ants that roam the overmap, especially around their hives, near cities (even invading them) and other places they might be attracted to. And, of course, clashing with hordes. Other monsters could also have their equivalents. It would be a good way for the world to continue its course even when the player is far away.

EDIT: Maybe indirectly related to #68097

**Comment by ilovehans10** [comment]
It might also be cool if this was implemented if it could handle NPCs, so you could have wandering Hell's Raiders or Wandering Merchants too.

**Comment by Rabadash94** [comment]
Of course, since zombie hordes are divided by size, swarms should be too. For example, a small bee swarm might be represented on the overmap with a lowercase yellow "b," and a larger swarm might be represented by an uppercase yellow "B." Regardless of the type of insect (or monster), larger swarms should ideally include a queen (or her equivalent), who would attempt to establish a new hive.

**Comment by a-chancey** [comment]
This would be pretty cool, swarms of mutant animals roaming. 

We really need to fix wandering hordes, first, though.
