### ISSUE TITLE
Sports Drink Powder

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#68241]
### Is your feature request related to a problem? Please describe.

Some sports drink companies (such as Gatorade) sell powder sticks that can turn water into sports drink by simply adding the powder. Those are for people who loves sports drink but doesn't like going to the store to buy the drinks. You can think of coffee powder.

### Solution you would like.

Adding sports drink powder.

### Describe alternatives you have considered.

A crafting recipe for sports drink.

### Additional context

Stay hydrated, everyone.

**Comment by Rabadash94** [comment]
Not only for sports drinks, but for many others. It would be good to carry powdered drinks and prepare them when needed, saving inventory space. They could be juices or chocolate too.

**Comment by ilovehans10** [comment]
It looks like these powders can be made from home too with Potassium chloride, Magnesium Chloride, and Salt. I agree that having a Kool-Aid/Nesquik stand in could be neat. It looks like those can be homemade with Jello powder and sugar or cocoa powder and sugar.

**Comment by huix11** [comment]
q

**Comment by Rabadash94** [comment]
It is also possible by dehydrating fruits and with nutritional additions, and if I'm not mistaken, those things can already be done in-game.
