### ISSUE TITLE
Update Math Parser to report which file the error occurs in

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#68245]
### Is your feature request related to a problem? Please describe.

Currently working on a PR and there's a math error somewhere, but the error message does not help me find it:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/bc3d4ace-0974-4755-b6a4-5fae1a23ffc9)

### Solution you would like.

Error message indicates which file the math error was found in

### Describe alternatives you have considered.

Once again going through and replacing all the math expressions I wrote with "1" in every file I changed and see if the error goes away.

### Additional context

The exact problem was:

`{ "math": [ "u_val('thirst')", "=", "0)" ] }`

when it should have been

`{ "math": [ "u_val('thirst')", "=", "0" ] }`

I had to delete all my changes and add the files back one by one to find it.

**Comment by andrei8l** [comment]
/confirm just to reopen. I would like to have this but don't see a way to do it for now since the json classes don't offer any introspection so you don't know where you are in file space.
