### ISSUE TITLE
``properties`` field cannot be overwritten if it's copied by ``copy-from``

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#68270]
### Describe the bug

As per the title, if an item has a ``properties`` field that is carried over via ``copy-from`` from another item, you cannot manually define that field and overwrite what's being copied.

### Attach save file

Rather than a savefile, allow me to point you to #68257 where the tests are yelling at me about it

### Steps to reproduce

Simply look at the animal locker and add a ``properties`` field. Or, I mean, look at my changes in the PR linked above.

### Expected behavior

I expect to be able to overwrite the field, rather than having to avoid using ``copy-from`` on items with said field

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/1305a10a-924d-442a-a650-2196e09d668e)

### Versions and configuration

Not sure if this is applicable as this is a behavior in current tests of the repo? If you need me to boot up the game with the changes and get you version info then sure, I will, but I don't think that's necessary.

**Comment by EvanBalster** [comment]
This sort of array-merging problem comes up with other JSON technologies like [merge patch](https://datatracker.ietf.org/doc/html/rfc7386).

CDDA's solution seems to be the "extend" mechanism, which does some things that `copy-from` can't.  Search for the word "extend" here, maybe it'll do what you need:  https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md

**Comment by Karol1223** [comment]
I am familiar with ``extend`` and have used it in the past. I may need to try using it in this use case, but regardless not being able to override the field is a problem.

Anywhere ``extend`` can be used, the field can also just be overwritten. Do you want to extend flags? That's cool, but you can also just do a new ``flags`` field that will override the ones being copied instead. Same has been true for anything else I've used ``extend`` for, and should be true for ``properties`` as well.
