### ISSUE TITLE
Add a profession who loss legs when game start

### ISSUE THREAD

**Issue by howmokas** [CleverRaven/Cataclysm-DDA#68274]
### Is your feature request related to a problem? Please describe.

Adding a new profession makes @ lose his legs at the beginning but has a wheelchair to increase the difficulty of the game.

### Solution you would like.

It would be cool for a character who lost his legs to survive in the game.Choose a special character through the gameing

### Describe alternatives you have considered.

....

### Additional context

....

**Comment by PGR-14** [comment]
There isn't really a "No legs" thing, but they could have 2 broken ones, but it would make more sense for it to be a trait (Kind of like XXL or XXS).

**Comment by Rabadash94** [comment]
If the player lost his legs at the beginning will be bleeding to death. It should be someone who had already lost his legs before the Cataclysm, but in that case one might wonder how survived and made it to shelter.

**Comment by PGR-14** [comment]
> If the player lost his legs at the beginning will be bleeding to death. It should be someone who had already lost his legs before the Cataclysm, but in that case one might wonder how survived and made it to shelter.

Maybe they came w/ someone else? Teleported? IDK

**Comment by misterprimus** [comment]
> There isn't really a "No legs" thing, but they could have 2 broken ones, but it would make more sense for it to be a trait (Kind of like XXL or XXS) that breaks 1 bone (You can choose an arm or a leg).

Yes, it would indeed only be possible with a "no legs" **mutation**.

**Comment by PGR-14** [comment]
> Yes, it would indeed only be possible with a "no legs" **mutation**.

oh yea, but it still would be better to have broken legs

**Comment by Rabadash94** [comment]
One might also wonder why someone in a wheelchair would be tasked with all sorts of dangerous missions.

**Comment by Zireael07** [comment]
No dangerous missions needed though?

(And I recall a wheelchair challenge start being requested ages ago)

**Comment by ZhilkinSerg** [comment]
That should be possible when limb system is fully finished.

**Comment by Maleclypse** [comment]
#68298
