### ISSUE TITLE
`The %s is too heavy for its engines` is confusing

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#68280]
### Is your feature request related to a problem? Please describe.
When you drive your vehicle with low amount of fuel, and this fuel happens to end, player get's reasonable message `The %s's engine dies!`. Hovewer, in the next move, the message `The %s is too heavy for its engines`, and it often confuses players, since the reason is not engine's malfunction, but lack of fuel
### Solution you would like.
Make a message variant, that tell player the engine has lack of fuel

**Comment by AnotherSeawhite** [comment]
Can confirm, I haven't looked into the code yet but I think it's related to the character still being in control even after the fuel is empty, and how the engine cannot operate after the fuel runs out
