### ISSUE TITLE
The game won't open on Oppo a17k

### ISSUE THREAD

**Issue by Raygaming4483** [CleverRaven/Cataclysm-DDA#68286]
### Describe the bug

Oppo a17k has always been a problematic phone because of its unique "features" now I was able to normally play cataclysm in this phone but when the new system update of Oppo a17k I can't even open cataclysm anymore, I tried downloading the experimental builds, still doesn't work, I tried the older versions, still the same, I also tried to delete the apps that I recently downloaded and restart the phone hoping it would work, still to no avail, I also didn't activate any accessibility features, no draw over other apps, and my internet can even let me watch videos with 1060p settings

### Attach save file

N/A

### Steps to reproduce

1.Download the game in Oppo a17k with its system updated to the latest
2.Open the game

### Expected behavior

It'll show the cdda icon for a few seconds then brings you back to the home screen without any warnings or errors

### Versions and configuration

Oppo a17k
Latest system update

### Additional context

I just hope somebody can find a solution to this 😞😞

**Comment by ZhilkinSerg** [comment]
Accessibility features only affect touch controls, not whether the game would run or not.

The only thing we can suggest here is to uninstall your phone system update and revert back to a previous version.

**Comment by Raygaming4483** [comment]
Yeah I tried doing it but I can't seem to be able to uninstall it😞😞

**Comment by Raygaming4483** [comment]
I shouldn't have bought this specific model😭😭
