### ISSUE TITLE
Shelter NPC tutorial quests brainstorming

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68295]
### Is your feature request related to a problem? Please describe.

The basic random quests you get from the shelter NPC like collecting cattails and killing jabberwock are not a great introduction to the game.

Some mechanics like passive boiling of water and smoking racks are not covered/introduced anywhere in game. First aid mechanics are pretty opaque.

### Solution you would like.

Some survival relevant introduction quests to game basics would be nice. Some specific ones I would like to see:

Premise: We're running low on basic survival supplies!

1. Secure a supply of clean water
 - Have 60L of clean water 
 
Process/mechanics involved - Scavenge/smash to find a 60L tank, commonly available from terrain objects. Find or collect enough clean water to fill it up. Introduces players to smashing things, passive boiling, and hauling/weilding to transport large objects.

2. Secure a supply of food
- Have 20L of smoked meat (or smoked anything?). 

Hunt a large animal, butcher it (butchering rack needed for large animals), craft a smoking rack/charcoal kiln, smoke the meat, store it in a basement.

3. First aid supply
- Makeshift bandages and anaseptic soaked cotton balls.

Learn to scavenge sheets from beds, clothes, and curtains. Stretch out antiseptic use by making soaked cotton balls, which can be gotten from pillows. Explain the way healing works - having a wound bandaged and disinfected is much better than just either/or, and sleeping and health have a large impact on healing speed as well.

3. Get a weapon
- Not sure about the specific trigger for completing this, there are a lot of options. But it's important, and generally enables the ability to complete everything else. Maybe should be the first quest. Maybe pick a specific easily obtainable weapon from smashing and crafting, like a pipe mace or nailboard. These can all be concurrent though, no need for a particular order. Maybe a spear?

### Describe alternatives you have considered.

These can be quests given by the shelter npc, which allows the npc to give tips and explanations about how to go about doing it as well. They can also be starting quests just inherent to the character - not necessarily easy for a new player, but trivial for an advanced player. A general guide for a new player to figure out some important mechanics and goals for surviving.

### Additional context

60L of water and 20L of smoked meat is roughly 2 weeks worth of food supplies for one person, and can be stored in the basement of the shelter to have it last longer than 2 weeks. Large amounts encourage use of passive boiling and smoking rack. There are still other viable methods to complete it by building up slowly or a little bit at a time, emphasizing the freeform nature of the game and rewarding creativity ie. collecting water from water heaters.

**Comment by oosyrag** [comment]
5. Get some wheels
No idea how to trigger this completion either, and it's roughly related to the refugee center quest from the terminal. Makes sense to have some sort of vehicle or bike to get there, but that's not conveyed to the player and a lot of people get discouraged when they see how "far" away the refugee center is, even though it's trivial with a vehicle. Maybe just add it to the quest text as a recommendation.

**Comment by Rabadash94** [comment]
6. Get a set of basic tools
There are certain improvised tools that can be made at the beginning such as a crowbar, hammer, screwdriver, etc.

**Comment by MNG-cataclysm** [comment]
7. Arm yourselves
    Find the materials to craft some basic weapons or scavenge for some. This should probably include early game weapons, such as basic pipe spears, sharp sticks, etc.

**Comment by oosyrag** [comment]
While on the topic of not-very-well-conveyed mechanics - a slightly more advanced quest to introduce the peek-throw - maybe a big bad ranged immobile triffed in a basement that you can bean to death with rocks, molotov, or grenades.

Regarding boarding up windows - I love the idea for how thematic it is, but I hate how useless it is in practice for the game as it is now.
