### ISSUE TITLE
Web Diver can bury the player underground.

### ISSUE THREAD

**Issue by EvanBalster** [CleverRaven/Cataclysm-DDA#68307]
### Describe the bug

After using the "Web Diver" mutation to descend multiple stories, the player phases through the floor, falling an additional story.  This can leave them trapped underground with no means of escape.

I probably introduced this regression in #68265 and discovered it while testing the follow-up #68306.  I intend to fix this bug myself.

### Attach save file

n/a; I created this bug and I'll create a tiny PR to fix it shortly.

### Steps to reproduce

1. Climb onto a second-story roof.
2. Use the debug menu to aid the Arachnid threshold and Web Diver mutations.
3. Try to walk off the building and pick the `w` option in the menu that appears.
4. Return to soil and atone for your crimes against nature.

### Expected behavior

Web diver should put you at ground level.

### Screenshots

Oh no.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13224671/54d21129-8603-41c3-9dab-fcb816c4a21e)

### Versions and configuration

Windows 10

### Additional context

I rewrote the function(s) where this happens so I understand them pretty well.

**Comment by Maleclypse** [comment]
Closed by #68315
