### ISSUE TITLE
Clock timers, temperature sensors and light sensors

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#68330]
### Is your feature request related to a problem? Please describe.

There are several appliances and devices that would benefit from being able to fine-tune their active and inactive periods with timers, temperature sensors or light sensors - such as stereo systems, heaters, coolers, lights/lamps, doors, window curtains...

### Solution you would like.

Adding tool/appliance-only tags called 'set timer', 'adjust temperature sensor settings' and 'adjust light sensor settings'. Items with these tags can be activate to do the following:

Set timer - Set when a device is on/off by specifying clock time. Requires clockworks or similar timekeeping device/materials as a component. May also include a beep alarm to tell you when a device shuts on/off in this fashion.

Adjust temperature sensor settings - allows you to set when a device is on/off depending on the ambient temperature in its current square (or if carried/worn by a survivor, their body temperature). Requires a thermometer or bimetal thermostat as a component.

Adjust Light sensor settings - allows you to set when a device is 'active' and 'inactive' depending on the lighting in its current square. Would require photocells as a component (currently does not exist as a spare part). Treats being in any pocket/container as being in darkness.

### Describe alternatives you have considered.

Having the above function as individual tool mods you attach to devices you want to automate. Using sensor arrays in a similar fashion.

### Additional context

Ha ha automation go brrrrr

**Comment by ilovehans10** [comment]
Related: #67953 (great minds and all that)
