### ISSUE TITLE
Crash when asking the scrap trader when they'll restock

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68346]
### Describe the bug

When i asked this scrap trader when they'll restock their stock after taking look at their wares, it crashes.

### Attach save file

[McBrides-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12729742/McBrides-trimmed.tar.gz)

### Steps to reproduce

1. Open the attached save
2. Talk to the scrap trader and trade with them
3. After opening their trading screen, talk to them `"Find anything good?"`
4. crash

### Expected behavior

Not crashing

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 11f7faf [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    GUT's Tweak Compendium [gut_tweaks_compendium]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12729754/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12729755/debug.log)

**Comment by RenechCDDA** [comment]
Confirmed, `restock` is a nullptr, presumably it is not set before the first *successful* trade.
