### ISSUE TITLE
Pointless and cumbersome nesting of soft containers should be avoided

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#68341]
### Describe the bug

When picking up multiple items in soft containers (such as e.g. plastic bags of salt) you typically end up with one container containing its original contents plus the rest of the containers containing the same thing.

This doesn't achieve anything since the containers are soft and thus no volume is saved, and it messes up the overview of what you're carrying since you now carry one soft container with mixed stuff. It also destroys sorting, as the mixed container ends up in the container zone rather than the zone where the containers would have ended up had they not been nested.

### Attach save file

N/A

### Steps to reproduce

1. Raid a typical household and pick up the various spices that tend to be found together as a single action.
2. End up with nested soft containers.
3. Spend effort sorting it out or just have it all dumped in the container zone.

### Expected behavior

Things should only be placed in containers if the action actually achieves something, such as using space in rigid containers or allowing things that otherwise would be too small to fit in the target pocket to be stored there.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 0.G-3922-g66a0c75e4e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms.

The code is an experimental with a hack to work around zombie and wreck pileups, but the issue is a long standing one.

### Additional context

At least the nesting places all of the containers in a single one, rather than nesting it all the way down...

The removal of charges means you want to avoid picking up anything in double digit numbers out of a container like the plague, unless you absolutely have to (and only if taking the time isn't dangerous).

**Comment by guo87995585** [comment]
I have abandoned the game due to meaningless non stackable items and endless nested containers
