### ISSUE TITLE
Isolation Protocol safezone autodoc

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#68351]
### Is your feature request related to a problem? Please describe.

I found some CBMs in a CBM lab, the only way to install them is to use the autodoc in the danger zone.

### Solution you would like.

An autodoc added to the safezone.

### Describe alternatives you have considered.

Keeping it the way it is, so you can only install CBMs when you stumble upon a CBM lab, with limited time and extremely dangerous conditions.

**Comment by John-Candlebury** [comment]
I agree there should be a way to install  CBMs in a safer manner, but I wouldn't know about simply adding an autodoc to the default safezone.  It feels too convenient.

**Comment by Blueflowerss** [comment]
I made this suggestion before remembering that CBM labs can spawn enclosed with metal walls and doors, so once you clear out the immediate surrounding you should be fine? 
Unless phase skulkers can teleport through walls, is there something that could be done to make CBM labs teleport-proof?
Another thing is that you still have to have is anesthesia for operations, which could be the valuable you have to find in the labs.
And finally, autodocs in IP should be easier to operate with. Not completely safe, but easier than in vanilla. Or maybe paramedic's thing is safer autodoc operations?

**Comment by John-Candlebury** [comment]
Oh I dont remember how long an Autodoc instalations take, I thought the danger you were referring to was the Unraveling Normality stage that triggers after staying for an hour in the same level.

Most likely is that I'll end up making a bossfight room that includes a working autodoc as set dressing,
