### ISSUE TITLE
The Dexterity stat should affect how much damage you deal in unarmed combat.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#68350]
### Is your feature request related to a problem? Please describe.

Compared to weaponry, unarmed combat is extremely reliant on coordination to deal any sort of damage in real life. Not that using weapons doesn't require speed, but a single punch in comparison requires you to put your entire arm, legs, hips and back onto it to even start being effective. As such, while Dexterity should only affect how fast and accurate most of your melee attacks are, it should directly increase your overall damage when you're fighting while unarmed.

### Solution you would like.

Low Dex should decrease unarmed damage, high Dex should increase it. Around one in every 3 to 4 points of Dex should increase the damage your fists do by 1 (or lower it, if your Dex is lower than 8).

**Comment by fairyarmadillo** [comment]
I don't think your first sentence is true. Hitting someone with a fist is not fundamentally different from hitting them with a stick, except that sticks hit harder.

Dexterity is also already the most important stat. I don't think it needs more stuff piled on it.

**Comment by cataclysmsurvivalist** [comment]
But Dex isn't the most important stat, it's Str. And yes, using weapons is different from using your fists on a fundamental level. While both a stick and your fists need coordination when fighting, a weapon is carried by its weight and construction. You CAN increase the damage a weapon does with proper technique, but in most cases, technique is used to actually hit an opponent with good defenses and aim at weak spots, not to improve your damage.

A knife will slice skin no matter where it hits the opponent, the dexterity part comes from the person using it trying to aim for the limbs, veins and organs to deal serious bleeding. While bashing weapons are different from blades in that regard, they will still deal damage even if the person holding them is physically weak - knowing how to use a bat or a stick with proper form means that you tire yourself less and attack more often because your stance is good, but the damage you deal increases by little.

In both cases you could make the case for Dex increasing the damage for weapons. But the damage increase would be extremely minor (not to mention already covered by skills with weapons that the game already has) compared to unarmed strikes.
