### ISSUE TITLE
Profession Based EOC for on start

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#68375]
### Is your feature request related to a problem? Please describe.

We have scenario based EOCs that run once on the start of a new game that uses a specific scenario.  I would like to have profession based EOCs that run on a new game start for specific professions. 
I think this could be run with small tweaks to the existing scenario EOC code.

### Solution you would like.

I would like for it to be added in I believe here is where it would be easiest.
```
void effect_on_conditions::load_new_character( Character &you )
{
    bool is_avatar = you.is_avatar();
    for( const effect_on_condition_id &eoc_id : get_scenario()->eoc() ) {
        effect_on_condition eoc = eoc_id.obj();
        if( eoc.type == eoc_type::SCENARIO_SPECIFIC && ( is_avatar || eoc.run_for_npcs ) ) {
            queued_eoc new_eoc = queued_eoc{ eoc.id, calendar::turn_zero, {} };
            you.queued_effect_on_conditions.push( new_eoc );
        }
    }
    for( const effect_on_condition &eoc : effect_on_conditions::get_all() ) {
        if( eoc.type == eoc_type::RECURRING && ( ( is_avatar && eoc.global ) || !eoc.global ) ) {
            dialogue d( get_talker_for( you ), nullptr );
            queued_eoc new_eoc = queued_eoc{ eoc.id, calendar::turn + next_recurrence( eoc.id, d ), {} };
            if( eoc.global ) {
                g->queued_global_effect_on_conditions.push( new_eoc );
            } else {
                you.queued_effect_on_conditions.push( new_eoc );
            }
        }
    }

    effect_on_conditions::process_effect_on_conditions( you );
}
```

### Describe alternatives you have considered.

Whatever the person coding thinks is best.

**Comment by ZhilkinSerg** [comment]
Maybe you can add scenario specific EOC, check for profession id there and run the required code?

**Comment by Termineitor244** [comment]
This would be very helpful. The assassin convict profession currently achieves this by adding a special trait with the profession and starting the EOC by searching for the trait, but it would be simpler if the game allowed you to directly invoke the EOC from the profession.

**Comment by Maleclypse** [comment]
> Maybe you can add scenario specific EOC, check for profession id there and run the required code?

I can do that for one set of professions that are scenario specific, I learned this morning.  I think there are maybe a couple of roundabout ways to get the same effect for professions that are not limited to specific scenarios.

**Comment by lispcoc** [comment]
Can you use `game_avatar_new` event for this case?

**Comment by Maleclypse** [comment]
Can be achieved with current functionality.
