### ISSUE TITLE
Make tiny animals invisible from afar

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#68387]
### Is your feature request related to a problem? Please describe.

We are getting more wildlife and that's great, but it's causing the compass and notification logs to get cluttered with a lot of stuff about animals which are mostly unimportant to the player.

### Solution you would like.

Some of these animals are very tiny, and IRL survive by being hard to notice. I think it might be more realistic if you couldn't spot them unless you were within a specific range, perhaps a number of tiles equal to your perception score.

This should never be applied to animals which could somehow cause harm to the player, and should pretty much be restricted to innocuous little critters like frogs and tiny birds. It should probably also not be applied to anything squirrel-sized or bigger.

### Describe alternatives you have considered.

These animals should mostly also be given the SMALL_HIDER flag, which will make them a little harder to spot in areas where they have hiding places.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/f70d5cf5-f79a-4459-9108-505f77f28f24)

**Comment by Rabadash94** [comment]
Also with aquatic animals. It makes no sense to be able to see them from a distance if they are, well, underwater. There is also no reason, as far as I know, for a warning to appear in the log every time they jump.
