### ISSUE TITLE
Ability Que up Cut or disassemble tasks

### ISSUE THREAD

**Issue by MacroLP** [CleverRaven/Cataclysm-DDA#68384]
### Is your feature request related to a problem? Please describe.

I am always frustrated when I have to open the cut/disassembly window repeatedly.  Usually I'm looting heavier things and will find a nice quiet place to disassemble them into their lighter materials to haul away.  It feels like it takes too much time to navigate the same menu over and over and over. I think this needs a QOL improvement.

### Solution you would like.

QOL request: I'd like to be able to select multiple objects to disassemble or cut and placed into an action que in the order I selected maybe? Quite like transferring inventory or looting a container or multidrop.  

yesyesyes, I know what you're thinking.  Why not make a disassembly zone and shift-O? Because this also requires tedious loot sorting work. I'd have to strip bodies of clothes first, drop items without easily being able to see what they can disassemble into, and can't select what gets disassembled first and repeat the shift-O menu over and over. Also if I'm short on time I cannot simply **cut** things in this way either.

Would also be nice to have a feature to sort/filter by possible materials or at the very least just by the time required for the task.

**Comment by oosyrag** [comment]
Are the disassemble/cut up everything and disassemble recursively options in the butcher menu insufficient? Or the extra step of getting everything you want to cut up on a tile troublesome? I imagine if you're selecting items to disassemble it's not too different than selecting items to move/sort.
