### ISSUE TITLE
Vehicle heaters prevent full deconstruction

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68388]
### Describe the bug

Small vehicle heaters require 99 mechanics to be removed, i.e. are not removeable, meaning you cannot fully deconstruct vehicles with them installed. With them being in most (all?) cars, it means deconstructing them for parts will always result in a frame with a heater left over.

### Attach save file

[Moroni-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12756413/Moroni-trimmed.tar.gz)

### Steps to reproduce

1. Deconstruct vehicle.
2. Be left with heater on a single frame.

### Expected behavior

Heaters should behave like other vehicle parts and be able to be uninstalled/installed. There isn't really any reason for heating tubes to not be abstracted like fuel tanks connecting to engines.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/2b4768b9-c7f4-498c-8aeb-2df8fa56f00a)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/90da4445-6bdf-4e55-8b11-1e0be1847373)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: d48717d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by GuardianDll** [comment]
/confirmed.

**Comment by RenechCDDA** [comment]
It probably needs a removal recipe defined, 99 mechanics required sounds like a stock placeholder value for undefined value

**Comment by GuardianDll** [comment]
The issue is that vehicle heater is not really a vehicle part - it just a set of pipes and a lever that redirect heat from the engine into the salon - removing is is as impossible as removing the hole from the donut
But the game does not depict it properly, unfortunately

**Comment by RenechCDDA** [comment]
Yeah, well it could just deconstruct as a pipe with a tool requirement of metal sawing 2? Or it could even deconstruct into *nothing* (remove-only)?

**Comment by GuardianDll** [comment]
Yes, it is possible
Is it possible to hide it from the installation menu? That was one of my concerns, because there is no actual way to make it once per vehicle and only if you have an engine on this vehicle

**Comment by RenechCDDA** [comment]
Yeah you can just use the `NO_INSTALL_HIDDEN` flag, although this means players won't be able to install it *at all*.

**Comment by Olaroll** [comment]
Could the integrated heater functionality be added to the `Dashboard` part? Would work well enough I think.
