### ISSUE TITLE
Persistent invalid overmap special id after updating

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#68397]
### Describe the bug

Emits the following after updating from a ~Aug 20 build to one from yesterday. Does not go away after saving. Does not appear happen on a new character in a new world.

```
 DEBUG    : invalid overmap special id "Railroad Station"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = overmap_special]
 FILE     : src/generic_factory.h
 LINE     : 478
 VERSION  : d48717d
```

and

```
 DEBUG    : invalid overmap special id "railroad_city"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = overmap_special]
 FILE     : src/generic_factory.h
 LINE     : 478
 VERSION  : d48717d
```

### Attach save file

[Copper Canyon-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12771883/Copper.Canyon-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.

### Expected behavior

No error.

@ZhilkinSerg added a railroads mod which replaced(?) the no railstations mod in #67713.
Maybe some migration stuff was missed?

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: d48717d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment]
Add railroad mod to your world mods

**Comment by NetSysFire** [comment]
Though the no railstations mod has been default for some time, there are still saves without that mod. Due to the annoying persistent error maybe a temporary migration thingy is in order until your mod either becomes integrated into the base game.

**Comment by Karol1223** [comment]
> Though the no railstations mod has been default for some time, there are still saves without that mod. Due to the annoying persistent error maybe a temporary migration thingy is in order until your mod either becomes integrated into the base game.

We claim to try and keep save integrity between stables - having every single save ported from .G have a persistent error every time it loads isn't exactly that. Either we assume the mod gets merged prior to the next stable or we need some migration.
