### ISSUE TITLE
Ideas for item repair

### ISSUE THREAD

**Issue by lmrterminal** [CleverRaven/Cataclysm-DDA#68409]
### Is your feature request related to a problem? Please describe.

I think CDDA's repair is too unreasonable.  For example, Mjolnir is made of wood, gold, and orichalcum.  When it gets damaged, we just need to use wood to repair it.  While it could be repaired with two other materials, we won't do that.  According to the actual situation, it is obviously impossible to damage only the wooden part every time.

### Solution you would like.

I think we can set a percentage for each component material of the item, and each time the item is damaged, we can determine the materials needed to repair the item based on the percentage of the component material.

**Comment by Procyonae** [comment]
"I think we can set a percentage for each component material of the item" That is already doable with "portion" ye, personally I think damage should roll against that so say it gets damaged twice, once it could damage the orichalcum and once the wood and the item as a whole would still have the same condition |. but you would need to repair once with each in either order to fully repair it. I could probably handle the code myself but idk how to convey it well to the player.
