### ISSUE TITLE
Missing reply for Exodii warehouse mission clarification

### ISSUE THREAD

**Issue by Leonkoithara** [CleverRaven/Cataclysm-DDA#68412]
### Describe the bug

When we ask for clarification when Rubik gives us the warehouse mission, he doesn't know what to say. Most likely because dialogue topic TALK_EXODII_MERCHANT_clarify has not been added yet.

### Attach save file

N/A

### Steps to reproduce

1. Get Rubik's warehouse mission
2. Ask for clarification
3. Refuse to elaborate
4. Leave

### Expected behavior

Get clarification when asked.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 0.G-4363-g8f00a6a4ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Leonkoithara** [comment]
On checking json files I see no clarification dialogues have been added. Is this due to pending changes through #68016 ?

**Comment by RenechCDDA** [comment]
Looks like the topic was just plain missed. It would be nice if we had runtime validation of dialogue branches (maybe there is some technical limitation on this happening?)
