### ISSUE TITLE
giant insects are unrealistic

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#68439]
### Is your feature request related to a problem? Please describe.

There's a reason why there are no giant insects or spiders: it's because things like strength and speed don't scale proportionately with size. IRL a giant insect would probably:

1. Suffocate because its respiratory system is insufficient. Again, there's a reason why a scorpion can get by with book lungs, but human and other mammals have different breathing organs. That's why big land animals are typically mammals.
2. The insect might even collapse under its own weight.
3. Anything smaller than a mouse typically cannot fall to its death. So when something like a house spider, used to being generally unaffected by falls, suddenly becomes huge, it will probably find itself experiencing a lethal fall very soon.

A good example of this is tarantulas vs their smaller brothers and sisters.

Wolf spider: https://www.youtube.com/watch?v=dQS2Q3vDR8M
Tarantulas: https://www.youtube.com/watch?v=K6AigT2hgn8

Perhaps the largest land arthropod is the coconut crab: https://www.youtube.com/watch?v=F8PyLAbrOK8
And this thing is about as fast as a snail.

### Solution you would like.

In general, the approach to giant arthropods should be rethought with this in mind. They definitely should not retain their speed and agility once they get to be so much larger. I get that the "blob" works in mysterious ways, but it should be more subtle. Would the stinger even work to deliver venom at that point? If the insects gets larger, its stinger will quickly also take on a size too large to act as a hypodermic needle.

### Describe alternatives you have considered.

A good first step would be nerfing insect/arthropod speed and agility across the board. They can retain their toughness, as a thicker exoskeleton is still difficult to defeat, but the speed and agility they presently have don't make a whole lot of sense.

### Additional context

Yes, I just died for the third time in a row to a wasp!

**Comment by fairyarmadillo** [comment]
All of this is accounted for if you dissect the bugs. They have endoskeletons, lungs, and lighter-than-air gases holding them up. These animals have specific mutations which enable them to function at their extreme new sizes, and would not necessarily suffer any loss of effectiveness.

I do agree that they shouldn't ALWAYS be flying, but that's more an issue with how monsters work in general.

Small size is also not a prerequisite for envenomation. Snake fangs do the job against humabs better than spider teeth because they are larger. Humans have used poisoned daggers to kill each other for millennia.

I'm not sure if your last line is a joke or not, but wasps aren't particularly hazardous once you know what you're doing. Generally you're just supposed to stay away from them in the early game. Their primary objective is to defend their hive, not bother the player. They can only see in a 15-20 tile radius in broad daylight, which is extremely limited and pretty easy to avoid.

**Comment by Rabadash94** [comment]
As far as I understand, the mutations in the game are not simply exaggerated versions of real-life mutations, but are more coherent and positive mutations due to their not entirely known origin, but which presumably may be related to an intelligent extradimensional agent.

**Comment by misterprimus** [comment]
> As far as I understand, the mutations in the game are not simply exaggerated versions of real-life mutations, but are more coherent and positive mutations due to their not entirely known origin, but which presumably may be related to an intelligent extradimensional agent.

I'm still not sure how such a creature would be able to fly just as easily as the small version without possessing absolutely enormous wings. My understanding is that flight becomes disproportionately more difficult as something becomes bigger and heavier. Same as with something like an ant not requiring a parachute to avoid dying from a fall, whereas a human would need a parachute to do the same.

**Comment by Rabadash94** [comment]
In real life there is already a case of an animal that flies despite the size of its wings (the bee). I also don't see what it has to do with a giant insect getting hurt when it falls if, as far as I remember, I haven't seen such a thing in the game. On the contrary, animals are supposed to avoid those kinds of dangers. A few days ago a PR about something related was merged (#68360).

**Comment by misterprimus** [comment]
> In real life there is already a case of an animal that flies despite the size of its wings (the bee). I also don't see what it has to do with a giant insect getting hurt when it falls if, as far as I remember, I haven't seen such a thing in the game. On the contrary, animals are supposed to avoid those kinds of dangers. A few days ago a PR about something related was merged (#68360).

My point is this ability to fly given the proportion of the wings to the body would not scale if the bee suddenly became larger.

https://www.thenakedscientists.com/articles/questions/could-bee-size-person-fly

**Comment by Rabadash94** [comment]
The only bee in the game that has an exaggerated size is the alpha bee (if I'm not mistaken, it has almost ten times the volume of an adult human), but the others are the size of a dog.
Beyond that, it's important to remember that mutations in the game wouldn't be simple stretches. We have to assume that mutations grant things in the appropriate proportion, and would not be carried out so blindly. Otherwise, it would be necessary to question the realism of zombie evolutions, for example.

The appropriate concept to use would be, not realism, but verisimilitude. Insects with the size of humans would be impossible in the world we know, but not impossible in themselves.

**Comment by misterprimus** [comment]
> The only bee in the game that has an exaggerated size is the alpha bee (if I'm not mistaken, it has almost ten times the volume of an adult human), but the others are the size of a dog. Beyond that, it's important to remember that mutations in the game wouldn't be simple stretches. We have to assume that mutations grant things in the appropriate proportion, and would not be carried out so blindly. Otherwise, it would be necessary to question the realism of zombie evolutions, for example.
> 
> The appropriate concept to use would be, not realism, but verisimilitude. Insects with the size of humans would be impossible in the world we know, but not impossible in themselves.

I'm not aware of any dog sized and weighted creatures that can fly like a bee unless you're talking about a tiny dog breed. There's a reason heavier birds are flightless. Also a reason even flighted birds use different proportion wings and have other compromises like hollow bones to make them much lighted, but obviously this comes with severe limitations to skeletal strength.

Basically, mammals, arthropods, and reptiles generally evolved to have the most functional means of movement. For a large bee to fly, it would need to have either a terribly flimsy skeleton that can be crushed effortlessly and/or use a different means of flying that would not allow it to hover in place just as larger birds cannot hover in place. That sort of flight stops working somewhere around the hummingbird size.

Either that or the large bee would need to have a propulsion that actually works at that scale, like the VTOL propulsion of a Harrier aircraft. Whatever the solution is, the one in the game presently makes no sense. May as well say it's a magical levitating bee, but that would belong in the nether creature category. Interestingly, many nether creatures like the migo make a lot more biomechanical sense than giant wasps.

**Comment by fairyarmadillo** [comment]
Again, they have sacs of lighter than air gas inside of them, which are plainly evident if you butcher them.

**Comment by Rabadash94** [comment]
>Whatever the solution is, the one in the game presently makes no sense. May as well say it's a magical levitating bee, but that would belong in the nether creature category. Interestingly, many nether creatures like the migo make a lot more biomechanical sense than giant wasps.

But the thing that caused the mutations is from another dimension, and is intelligent, which opens the door to multiple theories, except that the mutations are something arbitrary.
I don't see a problem with the proportions either, because I haven't seen them be that sturdy.

In any case, the suggestion could go in the opposite direction: that of adding to the game the consequences of having such insects. For example:

- Add to the insect drops the appropriate organs they would need, if any, just as mutagens give humans organs corresponding to other species.
- Due to the strength that an insect of that size should possess, it is logical that it would make a big noise. The range up to which its noises reach could then be increased. In the case of the alpha bee, the noise produced could deafen those closest to it. It could also repel some light items, and even the player if its weight was low enough.

**Comment by misterprimus** [comment]
> Again, they have sacs of lighter than air gas inside of them, which are plainly evident if you butcher them.

You'd need the bee to have a giant air balloon much larger than the bee's body for that to work. Think the Hindenburg.

**Comment by fairyarmadillo** [comment]
The hindenburg didn't have wings.

**Comment by misterprimus** [comment]
> The hindenburg didn't have wings.
> 
> Just because there are no very large flying birds alive today doesn't mean big things can't fly. There have been some truly enormous pterosaurs in history that had no trouble flying around all day.

If it worked, it would have been used to create a more efficient aircraft already. As it stands, consumer and even small military drones don't use internally housed air sacs because whatever weight reduction they'd cause would likely more than be canceled out by the increased weight caused by the greater hull size needed to house them unless you're talking about making the bees out of the same material and thickness as an air balloon, which would make them laughably flimsy.

The Haast Eagle is, well, an eagle. It cannot hover like a cdda bee because that doesn't work in that weight range. That's why internal buoyancy sacs are typically only a thing in fish and other seaborne animals. So the eagle would be limited to using its flight for the initial attack alone. After that it would be no more than a flightless, hollow boned, flimsy land animal that weights about as much as an overweight Beagle. The eagles I see typically hunt prey far smaller, like rats which they can overpower by being much larger. Against a human the eagle would have to rely on landing a lethal first strike to the jugular or else it loses 10/10 times against even a tonfa-armed man.

**Comment by fairyarmadillo** [comment]
Flying monsters can only hover, that's a limitation of the engine. I agree that soaring, gliding, and swooping would be great additions and things the larger insects should have to do. However adding that is a big ask, codewise.

**Comment by misterprimus** [comment]
> Flying monsters can only hover, that's a limitation of the engine. I agree that soaring, gliding, and swooping would be great additions and things the larger insects should have to do. However adding that is a big ask, codewise.

So just make the bees flightless and slow.

**Comment by fairyarmadillo** [comment]
That would make them pretty much pointless and I don't think destroying good content is ever a good idea, especially not when OP is by their own admission just salty that they lost a run and trying to use a misguided meme to get the monster responsible nerfed.

**Comment by misterprimus** [comment]
> That would make them pretty much pointless and I don't think destroying good content is ever a good idea, especially not when OP is by their own admission just salty that they lost a run and trying to use a misguided meme to get the monster responsible nerfed.

It's still an utterly, impossibly unrealistic creature as I've proven regardless of my initial reason for posting and regardless of why you want to keep it.

**Comment by Papaya-Plan** [comment]
Why does those monsters being impossible or unrealistic mean they should be removed or changed?

**Comment by misterprimus** [comment]
> Why does those monsters being impossible or unrealistic mean they should be removed or changed?

It's my understanding that the general guiding principle behind CDDA is an overall commitment to realism. While there are unrealistic creatures in the game, those that are truly impossible are typically advertised as such and limited to the nether creatures category, like the Flaming Eye. They're also very rare outside of end game areas like labs. Keeping in line with that would either require a Wasp/Bee nerf (either make them glass cannons or slow tanks, but not both) or keep them as fast tanks that they currently are, but rebrand them as magical bees or something and keep them with the Flaming Eye mobs.

**Comment by Papaya-Plan** [comment]
> > Why does those monsters being impossible or unrealistic mean they should be removed or changed?
> 
> It's my understanding that the general guiding principle behind CDDA is an overall commitment to realism.

That sounds like the root of the issue. My understanding is that CDDA has a commitment to _verisimilitude_, which isn't the same as realism. Neither the giant insects or the floating eyes are realistic (nor are either of them intended to be), but they are both believable within the setting itself.

**Comment by Rabadash94** [comment]
Just as Papaya-Plan and I said, the real issue is verosimilitude. And in the case under discussion, the solution would be the one I mentioned above, that is, adding the consequences of having insects like this to the game, instead of nerfing them.

**Comment by misterprimus** [comment]
> Just as Papaya-Plan and I said, the real issue is verosimilitude. And in the case under discussion, the solution would be the one I mentioned above, that is, adding the consequences of having insects like this to the game, instead of nerfing them.

I guess the giant wasp/bee could be made into the Hindenburg with a hydrogen-filled balloon that explodes on death.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45959491/ec2e836a-fd1c-4b9c-b0a0-48bbce91f06a)

**Comment by Papaya-Plan** [comment]
> > Just as Papaya-Plan and I said, the real issue is verosimilitude. And in the case under discussion, the solution would be the one I mentioned above, that is, adding the consequences of having insects like this to the game, instead of nerfing them.
> 
> I guess the giant wasp/bee could be made into the Hindenburg with a hydrogen-filled balloon that explodes on death. ![image](https://user-images.githubusercontent.com/45959491/271852691-ec2e836a-fd1c-4b9c-b0a0-48bbce91f06a.png)

That would only potentially make sense if they died while on fire, and I don't really see the purpose of or need for such a change.

~~Let it bee.~~

**Comment by misterprimus** [comment]
> > > Just as Papaya-Plan and I said, the real issue is verosimilitude. And in the case under discussion, the solution would be the one I mentioned above, that is, adding the consequences of having insects like this to the game, instead of nerfing them.
> > 
> > 
> > I guess the giant wasp/bee could be made into the Hindenburg with a hydrogen-filled balloon that explodes on death. ![image](https://user-images.githubusercontent.com/45959491/271852691-ec2e836a-fd1c-4b9c-b0a0-48bbce91f06a.png)
> 
> That would only potentially make sense if they died while on fire, and I don't really see the purpose of or need for such a change.
> 
> ~Let it bee.~

I guess it just comes down to what the primary devs want. No point in making a PR unless one of them thinks this is a good direction.

**Comment by Rabadash94** [comment]
There will have been tremendous losses to become an anti-insect Tallahassee.

**Comment by ADekema** [comment]
If you wanted to make it realistic than bees and wasps should probably be dangerous becease of their venom and numbers. Not becease of armour or size. I would be in favor of limiting the size of flying wasps and bees to that of a dog, making them appropriately fragile but making their venom capable of actually killing you. Increasing thier numbers would also be a good way to compensate any nerf.

Maybe alpha bees could still be flightless guardians of the nest as they wouldn´t have to move.

**Comment by fairyarmadillo** [comment]
Insects are the pet project of one of the primary devs (Venera3) and wasps in particular were rather recently reworked with tons of mechanical design and locations added. IIRC it's intended that the big boys are large and strong enough to kill humans and fly their corpses back to the nest, and I doubt that any attempt to fundamentally reimagine them is going to fly.

Also it's cool that they can fly and turning them into yellow ants would be boring and lame. We already have ants.

And one-shot kill venom is generally hugely unpopular for a reason.

**Comment by TheSaddestGoomba** [comment]
Would it be appropriate to open a separate issue?: "Make flying insects (and probably manhacks too) noisy"

I think a lot monsters could benefit from warning sounds.

**Comment by fairyarmadillo** [comment]
Yeah, the issue there is that flying creatures automatically have their footstep sounds made waaay quieter. I think that wouldn't be too hard to fix.

**Comment by Fris0uman** [comment]
This comment https://github.com/CleverRaven/Cataclysm-DDA/issues/68439#issuecomment-1741951109 answers the issue
