### ISSUE TITLE
Use string/rope/wire/etc. to make bundles obsolete

### ISSUE THREAD

**Issue by Papaya-Plan** [CleverRaven/Cataclysm-DDA#68442]
### Is your feature request related to a problem? Please describe.

A specific and somewhat arbitrary set of items can be made into easy to transport bundles. Anything else requires pockets.

1. Bundles exist. Arguably they shouldn't. See #68417
2. There's no in-game way to open a container, hold it upside-down, and shake it until empty. Related, when unloading items, you can't control where the contents go.
3. Items require pockets of certain minimum sizes and lengths. Without access to a container with an adequately sized pocket, items can only be transported one at a time, either via hauling or wielding. Sometimes this doesn't really make any sense.
4. Theoretically, a rope can be used to transport items. But since a rope can only contain one item, regardless of item-size and rope-length, your pile of planks becomes a pile of planks except one of those planks has a rope tied around it.

### Solution you would like.

Bundle = Ropes * Pockets

Add functionality to use string/rope/wire/etc. to tie items together. The max size of the bundle would be determined by the length of what you use, and the max weight by the material. A long piece of string can tie together some shirts easily, but probably wouldn't be able to hold together chunks of steel.

Activate the item, it brings up a menu of nearby items. Select everything you want tied together. You now have a bundle of items (Conceptually. The in-game container would either be a rope, string, or maybe a "knot" item). There should also be a minimum volume/length requirement; you cannot tie together a pile of salt, for instance. You could activate the tied-up items to untie them, depositing the contents wherever the bundle is currently located. The time taken would be more-or-less independent of the number of items contained. A knot is a knot.

Thence, when one has multiple reinforced garbage bags full of ~~junk~~ important crafting materials, none of which fit in any pocket, they can simply tied together, and carried to wherever they need to be. It just works.

Other bonus: You are no longer arbitrarily restricted to only being able to tie up cotton patches in groups of 100, even though tying together, say 80 or 120 makes just as much sense.

### Describe alternatives you have considered.

1 Bundle = Rope + Pocket: Removing the one-item limit for containing things in ropes. Store multiple items in ropes, a representation of tying them all together. Works, but the timing is weird. Ropes have a large move cost to add or remove items. Adding or removing items should have a 1-off time-cost of untying the knot and retying it afterwards, but all transfers should be about as fast as picking items off of the ground, since there's no actual container anything is being removed from. Also, you can't combine the potential carrying capacity of multiple strings/wires(/thread?).
2. Piles. A pile would act as a kind of pseudo-container. Piles up to a certain size could easily be wielded like a single object ("You wield your pile of planks."), which I think is an ability the CDDA character should really have, but piles don't maintain structural integrity when placed in most containers. At first I was thinking you could use a rope/string/chain on a pile to make a bundle-like item, but then it occurred to me that if a pile is a single item, and a rope can contain a single item, you can just place a pile in rope, and now you effectively have a bundle, without the need for any bundle JSON. Biggest issue with this approach is the CDDA doesn't use imaginary pseudo-containers, so this whole idea is wrong.

### Additional context

It would be nice if unloading could be expanded, with the aforementioned "hold thing upside-down, shake it a few times" which would be Very Fast. Combine it with more control over where the unloaded items go, maybe the option to bulk-unload, and you can easily consolidate containers. I think you can potentially accomplish _some_ of that functionality with pocket white-lists and priorities as-is, but it's cumbersome, not super intuitive, and doesn't work for, say, emptying your bag of filthy stuff into a washing machine.

**Comment by esotericist** [comment]
of note, there is in-game already an "unload container" action that is default unbound, which dumps the contents of the container on the ground. morally, it *is* the 'turn it upside down and shake it' option, but it doesn't look like it got the same treatment as #68214, which is probably an oversight. (i did a test where i filled a 50L metal box with sugar, it took me from 10:01:36 to 10:04:23. unloading is still in progress, at 3 hours and change as i write this, and i have no idea how much time is left)

@lispcoc do you think that would be easy to add, to at least get that part of this issue's list checked off?

**Comment by lispcoc** [comment]
I won't have time to develop it for a while due to personal commitments, but I'll check it out when I have free time.

**Comment by esotericist** [comment]
that's fair, i just figured it would be good to check with you as someone who just worked on it recently. obviously life comes first
