### ISSUE TITLE
`u_bulk_trade_accept` doesn't respect item containers.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#68456]
### Describe the bug

When using `u_bulk_trade_accept` to sell items, specifically canned ones, the containers that they are not respected by the trade option and will leave the player with a bunch of empty containers. If done with sealed canned goods, you will be left with a bunch of sealed, empty cans.

### Attach save file

N/A

### Steps to reproduce

1. Use any `u_bulk_trade_accept` code that takes canned goods in a repeat response, I used Eddie's trade interaction.
2. Spawn in contained canned goods, I used corn.
3. Trade them all and be left with a bunch of empty cans.

### Expected behavior

I expect that if I sell canned goods or sealed things like that, that I will also sell the can instead of magically removing the food and leaving me with empty, sealed cans.

### Screenshots

Before selling my corn.
![inventory](https://github.com/CleverRaven/Cataclysm-DDA/assets/58958654/aae8c31b-08ab-4e30-92ac-132030b7fb08)
After selling my corn.
![buggy inventory](https://github.com/CleverRaven/Cataclysm-DDA/assets/58958654/ddd49745-7df1-4724-90d6-7d9a5453477c)

### Versions and configuration

-OS: Windows 11
-Game Version: cdda-windows-tiles-sounds-x64-2023-09-26-1218
-Graphics Version: Tiles
-Ingame language: English
-Mods loaded: [ dda, no_npc_food, personal_portal_storms, no_fungal_growth ]

### Additional context

None.

**Comment by harakka** [comment]
/confirm
For sealed goods and liquids it's clear enough that the container should go with the goods, but is there some more universal criteria that can be used?

**Comment by RenechCDDA** [comment]
> For sealed goods and liquids it's clear enough that the container should go with the goods, but is there some more universal criteria that can be used?

Anything with an *automatic* whitelist containing that item. So if you bring in some boxes of sugar that you just looted, turning in the sugar turns in the boxes as well. But if (for some bizarre reason) you whitelisted sugar in your hiking backpack and had it in your hiking backpack, your backpack is not forfeit.

**Comment by katemonster33** [comment]
Came up with #72759 to work on this but could use some feedback. Right now it just looks for sealed cans containing the item but I see we've had the discussion on whitelisted pockets, maybe @RenechCDDA  has an opinion. My worry is that the user might unintentionally give up a vessel they didn't intend to if we open up the logic too much. Like if they've setup their own whitelist in like a cup, they might not have intended to give up the cup.

I think limiting the logic to sealed containers makes the most sense, plus, in my opinion it follows that an organization wouldn't care much about taking food donations in unsealed containers. Like, if Eddie is asking for canned corn, why would he accept corn in an old sock from some rando?

**Comment by MNG-cataclysm** [comment]
Sweet, thank you for doing all this! @katemonster33

**Comment by RenechCDDA** [comment]
#72759 doesn't appear to have fully resolved this. Larger tin cans will be opened and emptied, while small ones are correctly removed. Liquids are also taken right out of their (unsealed) containers and in some cases wielded by the receiving party. Obviously, you should not be able to wield `cooking oil (16)`.

To help with making sure we clean up *all* the instances, I've prepared some saves for testing. In both cases they are right next to the person you need to talk to.

[BULK_TRADE-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15166395/BULK_TRADE-trimmed.tar.gz)
Has a small tin can with turn-in item, a large tin can with turn-in item, and gallon jug with liquid turn-in item

[BULK_DONATE-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15166381/BULK_DONATE-trimmed.tar.gz)
Has 50 smoked meat, should only lose 1 when donating
