### ISSUE TITLE
Autosort consistently deleting items

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#68477]
### Describe the bug

When transferring the contents of a single-tile unsorted stockpile to a single-tile unfiltered custom zone 33 tiles away, approximately two thirds of the items are consistently deleted. This is reproducible in the attached save file.

The autosort process ends with a message saying "You can't reach the source tile. Try again without a cart." I am using no cart, and the source tile is directly adjacent to my character, who never appears to move throughout the process.

### Attach save file

[Terra Alta.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12789225/Terra.Alta.zip)

### Steps to reproduce

Step 1: Check contents of stockpile. Observe that it contains 961.39 liters of items.
Step 2: Activate autosort
Step 3: Observe failure message. Observe that the source tile is completely empty.
Step 4: Observe that the destination tile only contains around 307 liters of items. As far as I can tell, the remainder of the items have completely vanished. (If they've simply ended up on an intervening tile somewhere, I'm unable to find it even with clairvoyance, plus to my knowledge autosort doesn't actually move items in discrete steps like that?)

### Expected behavior

While it would be understandable for the autosort process to fail, take significant time etc given that it's some distance away and the pathing is not direct, it should not delete the items, just leave them at the source tile.

### Screenshots

The zones in question: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19789267/47fa0f94-c20e-4eb4-ab36-668e083ed32e)
Contents of source tile before transfer:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19789267/d03a19f7-6ea9-488c-b736-30059f45e9d3)
Failure message:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19789267/9747ce8f-0188-4918-b039-60e9c4bfe880)
Contents of destination tile after transfer (source tile is now completely empty)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19789267/f826eda4-40e8-463e-a69a-894d54522d77)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 3c606a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
I've repeated the issue with a several weeks old version. Moving half of the items away doesn't help, nor does moving the other half away instead. I've also tried to have the source and/or targets being floor space rather than containers, but with the same error.

**Comment by Solusphere** [comment]
From some quick testing, I can confirm that range and pathing are not a factor. The result is the same whether the destination zone is 30+ tiles away of 2 tiles away.

**Comment by inogenous** [comment]
When running locally here, some items are moved to the expected pile at `(88,93,-3)`. But the rest of the items are moved to another zone, one floor above, at `(61,123,-2)`. This is also visible from some of the displayed messages, some say `You put your (thing) in the dresser`, but some display as `You put your (thing) on the concrete floor`.

![moved-items](https://github.com/CleverRaven/Cataclysm-DDA/assets/123803852/f6fb41ca-1171-4a1b-8ab6-8ecaf748bccb)
![moved-items2](https://github.com/CleverRaven/Cataclysm-DDA/assets/123803852/2e781cdd-5a66-413f-bb63-d48c06692323)

It's still unclear why that destination is picked, and why there is a difference between items.

**Comment by PatrikLundell** [comment]
Good find!

The other zone isn't visible on the list of zones (as zone support only spans the current level... usually).

I'd certainly want zones to support multiple Z levels, but only in a consistent manner... Could it be some side effect of a change someone did to specifically support a single type of zone (disassembly?) for companion use on a different Z level?

**Comment by inogenous** [comment]
This might be a side-effect from the very nice improvements in #65613 , specifically here, where the destination zones are picked: https://github.com/CleverRaven/Cataclysm-DDA/blob/9991e8156b5d14a73d0c6bb1128a5455dc051e61/src/clzones.cpp#L1053

(before the above changes, it only picked points on the same z level)

Some possible changes we could consider here:
* Make the list of zones in `Y` also display zones on different z levels.
* Preferring the "closest" zone as destination when sorting.

About the second point, at the moment it seems like we first determine a list of possible destination zones that are within a certain bound, measured by square distance. Then these are put into a `std::unordered_set<tripoint_abs_ms>`. This makes the ordering of the zones undefined (since it's a `set`). What we could consider doing is instead to
* measure by travel cost instead of square distance
* sort them by travel cost, and pick the closest zone with available space

However, care must be taken to make such a selection with good performance.

**Comment by db48x** [comment]
Is this actually a bug? No items were actually lost, they just ended up on a different floor. Now that the zone list shows the same list of zones that the autosort will pick from, it should be clear enough to users where their items could have ended up.

**Comment by Solusphere** [comment]
Yeah, the "bug" was that the items were being shunted to a location that was invisible to the zone manager at the time, which was successfully addressed by @inogenous. I considered the issue resolved, so I'll go ahead and close it as I don't see any remaining loose ends to tie up with this one.
