### ISSUE TITLE
Carnivorous plants balancing giant insects

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#68476]
### Is your feature request related to a problem? Please describe.

There are more insects than humans out there, especially after the Cataclysm. Sure, due to Blob Magic™ many creatures got more aggressive and even though there are plenty insects, a wasp may still try to prey on a survivor.
However, wasps and other insects also have natural predators, which include carnivorous plants.

### Solution you would like.

There are a [couple](https://newildernesstrust.org/carnivorous-plants-of-the-northeast/) of carnivorous plant species native to New England. Could be cool to have e.g one bladderwort species aggressive to those aquatic nymph larvae and e.g pitcher plants and sundews for regular forests.

Via faction shenanigans, one could make insects attracted to nectar friendly to the plants and the plants remain hostile. The insects should still be able to fight back or flee.
Potentially we could work with scents, too but that may have performance implications.

A carnivorous plant monster would primarily employ grab attacks and if prey is grabbed employ continuous acid attacks over some hours. I would need to test that out a bit but the grabs need to stack and there might need to be a paralyzing attack, too, in order to keep the prey from constantly escaping. The longer you are stuck in a carnivorous plant, the less chance of escaping you have due to the plant continually closing in around you or secreting more sticky juices to get you stuck, which is why I am thinking about more paralyzing or grabbing attacks. The acid attacks should be very slow and low-ish in terms of damage so the actual kill takes a good amount of time so we do not have a herbaceous super efficient killing machine.

A survivor might be too big for a trap to digest and can see them from a distance, anyways. Bumping into one is still very much not recommended, though in real life the digestive juices can not harm your skin unless you bathe in it for two days straight. Due to mutations and Blob Magic™, the plant will be bigger and meaner, so also more dangerous to human skin and the actual chitin and insect insides it is designed to digest.

They would appear rarely and usually benefit the player and become another, usually minor, asset in strategies.

### Additional context

I would be potentially interested in working on this once I finish my current stuff.

**Comment by ADekema** [comment]
I'm not sure a monster would be the best way to represent a gaint plant ingame. It might be better to turn them into traps that litter the forest as that is really how they opperate.

**Comment by NetSysFire** [comment]
Traps are not jsonified yet. That would require me to touch C++. With a monster it is likely possible in just JSON.

**Comment by fairyarmadillo** [comment]
More giant plants in general would also give Triffids more to be doing. IIRC bees are supposed to be pollinating giant triffid flowers.

**Comment by Rabadash94** [comment]
One question that could be raised is if a carnivorous plant caught a zombie, would the items that the zombie was supposed to throw away when it died disappear or would the plant spit them out? Of course the butchering drop would disappear without a trace (except bones, maybe), but presumably that is not the case with everything artificial, at least with some resistant materials.
Also, what would happen if a plant tried to attack a robot or a zomborg?

In any case, adding carnivorous plants would be a good improvement. By the way, I don't know how common that is in New England, but there are people who put carnivorous plants in their garden or backyard, so it might be possible to find those monsters in cities too.

**Comment by fairyarmadillo** [comment]
Also a possible balancing feature - insects and humans respond differently to toxins. If you don't want the carnivorous plants to be instant player deathtraps, they could have a weaker paralytic vs mammal nervous systems compared to insect.

**Comment by Rabadash94** [comment]
Or they could spit acid like acid ants, but in smaller quantities.

**Comment by ADekema** [comment]
Instead of acid you could have the plants use insecticide. It exists ingame and is incredibly deadly to insects but not so toxic to anything else.

**Comment by Leonkoithara** [comment]
There is a json flag trap_avoids which can be used to indicate if a monster will trigger a certain trap, this can be used to avoid zombies getting trapped by carnivorous plants.
