### ISSUE TITLE
GitHub Releases for all Linux and some Windows platforms are no longer being built after #68424 was implemented

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#68475]
### Describe the bug

GitHub releases are no longer being built for all linux and some windows platforms after (i'm assuming) changes from #68424 

### Attach save file

N/A

### Steps to reproduce

1. Look at the release assets at or before #68424 
2. See that release assets are short by 7 platforms for releases after #68424 

### Expected behavior

I expect the automated build system to continue to compile all the various platform releases.

### Screenshots

![CDDAAssetsMissing](https://github.com/CleverRaven/Cataclysm-DDA/assets/85591702/1e5cd51a-85cb-4c30-9876-4c92902bc5e8)

### Versions and configuration

N/A

**Comment by akrieger** [comment]
Your analysis is almost right. If the PR you mentioned broke it, then *that* experimental release would be missing those assets. The real blame is #68399... which tbh I'm not sure why the matrix builds didn't catch the issue.

**Comment by lispcoc** [comment]
sorry, my mistake. #68460 may close this.

**Comment by ZhilkinSerg** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/3fba461b-e3d1-4837-b8df-667d539156f9)
