### ISSUE TITLE
[Aftershock] Switching armor items on / off duplicates enchantment effects

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#68470]
### Describe the bug

When wearing Aftershock armor, turning the item on and off duplicates the enchantment effects it provides. Beyond just cluttering the effect screen this is obviously noticeable when wearing an exosuit because it will give the player hundreds of strength with even just a natural turning on and off of the suit when not in use.  Only taking the armor off the character removes the extra effects.

### Attach save file

N/A

### Steps to reproduce

1. Wear Magellan Helmet
2. Turn helmet on and off several times
3. Move character to update your effects
4. Observe duplicated effects

### Expected behavior

Armor enchantment effects do not duplicate

### Screenshots

![exosuit duplication](https://github.com/CleverRaven/Cataclysm-DDA/assets/70666939/cfa43224-4a53-4ab1-a6ba-5f1770bbe687)
![aftershock armor effects](https://github.com/CleverRaven/Cataclysm-DDA/assets/70666939/fa5fa2f9-0482-4d8f-b12d-ddf4fd8cf98d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: b0bd4f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock]
]

### Additional context

May not be an Aftershock specific bug, but its harder to find similar armor in basegame

**Comment by John-Candlebury** [comment]
Confirmed but its not really an aftershock bug, made the general report in the linked issue. Thanks for the report
