### ISSUE TITLE
Cant have hm12 dazzle rifle anymore because of overheat breaking

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#68484]
### Describe the bug

I have captured pupating zombie in the bear trap, crated lots of ups and heavy batteries to practice marksmanship and rifles, but after some of shots - the hub rifle breaks down. And I cant operate with it no more. So, if it breaks down before I capture the triangle robot - the quest will be failed
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/13c59cc5-3286-4cc6-9629-86dbb42f731c)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/767bded1-a010-4154-b585-512c90d68a70)

#67959 its very good and nice mechanic, but need to be better

### Attach save file

n/a

### Steps to reproduce

1) Take  hm12 dazzle rifle
2) Capture monster with high regeneration
3) Spam 1000+ fires times with overheating
4) See, you cant use your weapon no more

### Expected behavior

Have a way to repair overheated guns

I also gave few good and realistic variants to realize and improve this idea

1) With high electronic and mechanic (something like 6-8  levels in each) skills you can repair guns by yourself via "mend" option of the weapon 
<details>
  <summary>Screenshots</summary>

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/a64b3d61-dc91-4731-8b9b-4383a91749f2)

</details>

2) You can bring the failed gun to hub intercom, or may be to some kind of new mercenary, and they can repair it for gold coins
3) Make regulable level of overheating. For now, if you just hold the fire button and spam fire at enemy - the gun will just cool after overheating by it self and start to fire again, so you just hold the button and wait, until all you energy in ups will end
Make the leveler for autocooling. All way will be the same, but autocooling will start before dangerous level. And it will be good, if the safe level be by default, because I dont think that creators of most laserguns will make overheated breaking risks as good option for their gins. As a possibility for emergency or special situation - yes, but not as a default option
Because is will make lots of unnecessary keypresses for me to watch for overheat level, press wait buttons for cooling and then shoot again
This mechanic will be also very useful for turrets, because for now you cant regulate its heat level, but with this mechanic they can
3.1) You can also make the mechanic, where guns will shoot right after little cooling. Let me explain
Let's imagine, that 100 shoots - is the 100% overheat level, and 60 shots - 60% safe overheat lvl. You place the safety regulator at 60%
And there is two good ways for autocooling mechanic
a) Guns and turrets will cool from 60% to 0% to rapidly shoot lots of laser shots
b) Guns and turrets will slow shooting right after cooling from 60% to 59%.  So, when its cooled by 1% before the safety level - it shoot, and make it again and again
It will be also good to make long cooling more effective, than shooting by little cooling before safety level. Something like
It will take 10 seconds to cool from 60% to 0%, and you can make 60 shots again, but if you shooting after 1% of cooling before safety level - it will take long time, like x2 time slower, than full cooling
4) If it hard to implement in code - may be can be created some kind of modifications for guns, similar to modifications of gunpowder guns
5) Make it possible to buy hm12 dazzle rifle from hub

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 9a345c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by KHeket** [comment]
@John-Candlebury can you check pls? There is lots of good ideas for your mechanic

**Comment by John-Candlebury** [comment]
Not being able to fire thousands of shots and become a living floodlight of laser light death is the point of the overheat mechanic. 

That said:

- I'm not against hub fixing or selling you another dazzler rifle.

- I don't understand what your point 3 means? Is it about configuring the option to not fire even if you press f while being at a specific heat threshold? If that case I dont see the point, just manage it as you do the recoil or reloading for normal weapons, either take the chance to build some distance or swap to something else. Firing 1000s of successive 1 damage shots at a regen creature is a grinding stat, and I'm not going to design complex UI features to make grinding more convenient.

**Comment by kevingranade** [comment]
If you want to make another issue for,  "it's possible to lock yourself out of this mission" with buying or trading in a burned out dazzle rifle as the recommended fix go ahead,  but burning out the rifle if you abuse it is an intended outcome.

**Comment by KHeket** [comment]
> * I don't understand what your point 3 means? Is it about configuring the option to not fire even if you press f while being at a specific heat threshold? If that case I dont see the point, just manage it as you do the recoil or reloading for normal weapons, either take the chance to build some distance or swap to something else. Firing 1000s of successive 1 damage shots at a regen creature is a grinding stat, and I'm not going to design complex UI features to make grinding more convenient.

This point is also solution for turrets, which dont have any safety regulators for now. Yes, it can be used for grinding skills like I do, but it also will make car turrets usable, and if you have good laser rifle or gun - you can fight with lot of regular zombies in cities
