### ISSUE TITLE
passive_mods section of traits/mutations json keeps adding values to the player's stats for every save/load cycle

### ISSUE THREAD

**Issue by nizhuan-jjr** [CleverRaven/Cataclysm-DDA#68493]
### Describe the bug

I made a simple local mod that has an armor that has a worn passive effect of adding a trait:
`
    "relic_data": { 
	 "passive_effects": [ 
     { "has": "WORN", "condition": "ALWAYS", "mutations": [
         "wearing_test_headgear"] }
     ] 
    }
 `
The trait/mutation json has the trait which adds some passive mods to basic stats:
` 
    "passive_mods":{
        "per_mod": -5,
        "str_mod": -5,
        "dex_mod": -5,
        "int_mod": -5
    },
`
Here's the case: My player put on the armor, and he got the trait which reduced his stats from 20 to 15, this was correct and I made a save and exit the game. Then I loaded the save, and his stats changed to 10! I saved and loaded again, his stats changed to 5! After taking off the armor, his stats now becomes 10 (instead of his original 20).
In other words, the passive_mods change characters' both the maximum value and the current value of their stats; this doesn't look right to me.
What I expected is that the trait from the armor should only change the current stats, therefore, the player will get his stats back after taking off the armor.

### Attach save file

The save:
[埃文斯维尔-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12801785/-trimmed.tar.gz)

My simple test mod:
[SimpleTestMod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12801799/SimpleTestMod.zip)

### Steps to reproduce

1.Make a player that has stats of 20-20-20-20.
2.Craft the Test Headgear from the simple test mod(a simple armor gives a simple trait when worn, the trait has a passive_mods section)
3.The player puts on the headgear armor, his stats should be 15-15-15-15 now, then save and exit.
4.Load the save to check the player's stats, which should be 10-10-10-10 now and this is the bug.

### Expected behavior

The passive_mods of the trait from the armor should only change the current stats, therefore, the player should get his original stats back after taking off the armor.
In my case, the stats should be 15-15-15-15 no matter how many times I save&load the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 5621850 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth],
    <color_cyan>奥术与魔法物品</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    大魔法 [magiclysm],
    <color_cyan>奥术</color>/<color_light_green>Cata++</color> 兼容补丁 [Arcana_Cata++_Patch],
    <color_cyan>奥术</color>/大魔法 兼容补丁 [Arcana_Magiclysm_Patch],
    神话武术 [MMA],
    SimpleTestMod [SimpleTestMod],
    <color_yellow>神话武术扩展</color> [MMA_Mods_Extension]
]

**Comment by esotericist** [comment]
should be fixed by #69312
