### ISSUE TITLE
Mound of Typos

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#68497]
### Is your feature request related to a problem? Please describe.

I find typos while translating, I write up typos in a list, people fix them if they fill like it.

### Solution you would like.

The typos today are:

This example EoC for a weight and volume test has weight mistyped:
- [Wight and volume test] -> [Weight and volume test]

Tall mound of gravel has a typo in its description where I'm pretty sure @detahramet mistyped, it should be fixed as such:
- An area of gravel heaped well above your head, difficult to climb -> An area of gravel heaped well above your head, difficult to climb over.

Short mound of clay's description misses a period:
- An area of heaped clay, not easily traversable -> An area of heaped clay, not easily traversable.

Same for short mound of rocks:
- An area of heaped rocks, not easily traversable -> An area of heaped rocks, not easily traversable.

Descriptions of all three broken glass mounds are missing periods too:
- An area of heaped glass shards, not safely traversable.  Just looking at it feel like you'll get tetanus -> An area of heaped glass shards, not safely traversable.  Just looking at it feel like you'll get tetanus.
- An area of broken heaped up to your shoulders, not safely traversable.  Just looking at it feel like you'll get tetanus -> An area of broken glass heaped up to your shoulders, not safely traversable.  Just looking at it feel like you'll get tetanus.
- An area of broken glass heaped well above your head, unsafe to climb.  Just looking at it feel like you'll get tetanus -> An area of broken glass heaped well above your head, unsafe to climb.  Just looking at it feel like you'll get tetanus.

Double period on mound of dirt with harvestable plant:
- An area of dirt heaped up to your shoulders, not easily traversable.  There is a fully grown plant, and will need closer examination to harvest.. -> An area of dirt heaped up to your shoulders, not easily traversable.  There is a fully grown plant, and will need closer examination to harvest.

Tall pile of planks' description needs start capitalization:
- planks stacked well above your head. -> Planks stacked well above your head.

Tall stack of pipes needs its item named to well, tall stack of pipes, its description also needs pipes pluralized:
- tall stack of pipe -> tall stack of pipes
- Pipe stacked well above your head. -> Pipes stacked well above your head.

Description of .22 deringer pistol, miniscule should be minuscule, barrelled should be barreled:
- A four barrelled, adorably tiny pocket pistol, firing the equally miniscule .22 LR cartridge.  Produced in the early 20th century for trappers, its combat effectiveness is questionable to say the least. -> A four barreled, adorably tiny pocket pistol, firing the equally minuscule .22 LR cartridge.  Produced in the early 20th century for trappers, its combat effectiveness is questionable to say the least.

Amatuer Mechanic achievement should be Amateur Mechanic:
- Amatuer Mechanic -> Amateur Mechanic

Get active pamphlet (map item giving you directions to sporty locations) misspells businesses:
- A small pamphlet advertising various local buisnesses encouraging you to get fit.  Using it will add roads, gyms and pools along with shops where you can buy sporting gear to your map. -> A small pamphlet advertising various local businesses' encouraging you to get fit.  Using it will add roads, gyms and pools along with shops where you can buy sporting gear to your map.

Marble floor description misspells beautiful:
- A smooth and flat flooring made of marble tiles.  Beatiful and expensive. -> A smooth and flat flooring made of marble tiles.  Beautiful and expensive.

The MoM skillbook The Miracle of Mindfulness: An Introduction to the Practice of Meditation misspells colleagues and focuses:
- A translation of a letter written by Thich Nhat Hanh to collegues in Viet Nam, this book focues on mindfulness and breathwork.
-> A translation of a letter written by Thich Nhat Hanh to colleagues in Viet Nam, this book focuses on mindfulness and breathwork.

This recently added XE Salamander effect should be corrected:
- Burning Furnance -> Burning Furnace

Description of burning coals skin integrated armor and mutation from XE repeats has two times:
- Your skin has has magickal flames flaring out of it on occasion.  You can operate in warmer climates than normal humans but begin to take damage from getting wet. -> Your skin has magickal flames flaring out of it on occasion.  You can operate in warmer climates than normal humans but begin to take damage from getting wet.

Newly added descriptions of missing legs misspell whether:
- Wether by a serious accident, birth defect, or other means, you have lost your right leg.  You can hobble around, but will likely need a wheelchair or other means of locomotion to get somewhere far. -> Whether by a serious accident, birth defect, or other means, you have lost your right leg.  You can hobble around, but will likely need a wheelchair or other means of locomotion to get somewhere far.
- Wether by a serious accident, birth defect, or other means, you have lost your left leg.  You can hobble around, but will likely need a wheelchair or other means of locomotion to get somewhere far. -> Whether by a serious accident, birth defect, or other means, you have lost your left leg.  You can hobble around, but will likely need a wheelchair or other means of locomotion to get somewhere far.

Description of prosthetic right leg misses the "designing" included in the description of the left prosthetic leg:
- A prosthetic leg, used as a replacement limb for those missing one.  Its modern design and sleek ergonomics make it very comfortable and highly suitable for use, and advanced makes it look exactly like the original.  This one is for the right leg. -> A prosthetic leg, used as a replacement limb for those missing one.  Its modern design and sleek ergonomics make it very comfortable and highly suitable for use, and advanced designing makes it look exactly like the original.  This one is for the right leg.

The background dialogue of left_for_dead_3 NPCs should have protestors changed to protesters, the correct version of the word, in both mainline and Innawoods Backgrounds files, also I'm not really sure why the Innawoods version of the background changes "cop" to "big bruiser" but it doesn't really matter much.

Prosthetic right leg and prosthetic left leg items do not seem to have a plural defined.

The status effect Arythmic of XE should be changed to Arrhythmic, the correct spelling of the word.

Glazed carrots should not have a singular form.

### Describe alternatives you have considered.

Fixing the typos myself, but Proc said they're back so I'll gladly offload the work to somebody else :D

**Comment by Fris0uman** [comment]
Fixed by  #68583 ?

**Comment by NetSysFire** [comment]
Looks fixed here.
