### ISSUE TITLE
Companion corpse smashing setting doesn't respect distance setting

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#68495]
### Describe the bug

When companions are allowed to smash corpses they ignore the setting to keep within 2 tiles of the PC, and runs around uncontrolled towards approaching zombies, into closed rooms (presumably with unbashed bodies in them, but definitely new zombies).

### Attach save file

N/A

### Steps to reproduce

1. Allow your companion to smash corpses, while also requesting them to keep within 2 tiles of the PC.
2. Kill a bunch of zombies.
3. Despair as the moron refuses to follow the PC trying to retreat from new zombies in order to smash corpses, run around and attract new zombies, etc.
4. Order the bugger to leave corpses alone in order for the party to survive the madness.

### Expected behavior

Respect the settings. If there is a restriction on how far away the companion may be from the PC, the companion should move at most that distance away to seek a corpse to smash.
If a companion is involved in corpse smashing, the companion should cease the activity and follow the PC when the range restriction becomes exceeded.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 0.G-3922-g66a0c75e4e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms
+ Local code to work around wreck and zombie stacking issue.

### Additional context

As a side note, it can be mentioned that the companion seems to have a knowledge of the presence of corpses that have not been revealed (such as rushing up the stairs in an apartment building to get into a fight with a zombie for no apparent reason, as well as opening doors with zombies, and, presumably, corpses, behind them).

**Comment by vvbudh** [comment]
I believe I may be having this issue as well. I've told my companion to ignore zombies unless his life depends on it, he will leave zombie corpses intact, he will not bash down obstacles he will open doors to reach a destination.

He will follow closely even when threatened, he will follow you at two paces, he will move freely to attack enemies. (I don't know how to change this one. This is my first companion.)

I asked him what he was doing, he said he was smashing. And that long-term choice systems to hack. I asked him to stop doing that, he said OK. But then he continues to run back towards the burning building and I keep hearing smashing.

**Comment by vvbudh** [comment]
![Uploading Screenshot 2024-05-25 at 9.41.33 AM.png…]()

**Comment by vvbudh** [comment]
<img width="1728" alt="Screenshot 2024-05-25 at 9 41 33 AM" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/84519187/7e3997b4-e5bb-4d7f-bb11-290d0de55fd0">
