### ISSUE TITLE
Bronze requiring a book makes it impossible to forge metal tools in a wilderness game

### ISSUE THREAD

**Issue by Talth12** [CleverRaven/Cataclysm-DDA#68491]
### Describe the bug

A standard hammer requires  hammer 3 to forge and a bronze hammer can only be made with bronze that isn't available without a book.

### Attach save file

N/A

### Steps to reproduce

Look at recipes for hammer and bronze chunks

### Expected behavior

Bronze should be autolearned

### Versions and configuration

2023-10-04-0453

**Comment by Fris0uman** [comment]
If you mean in vanilla this is not an issue. Not having access to modern conveniences when you decide to not use modern conveniences is expected. If you mean specifically for the Innawood mod then tag your issue to be about that mod

**Comment by Talth12** [comment]
It was only changed a few versions ago, in vanilla you have always been able to progress in the woods. Not as quickly or efficiently  as the mod but it has been possible.

**Comment by Fris0uman** [comment]
This is woking as intended in vanilla

**Comment by Talth12** [comment]
@Fris0uman A hammer requires hammering 3 to be made so with out access to bronze a hammer requires a hammer to craft 
making it a mostly useless recipe why would you craft a hammer when you already have a hammer. I think a hammer should require hammering 2 instead of 3 so that you could actually craft one if you didn't have one.
