### ISSUE TITLE
Tin Scrap should replace the scrap metal drop when disassembling cans.

### ISSUE THREAD

**Issue by Zyzarda** [CleverRaven/Cataclysm-DDA#68506]
### Is your feature request related to a problem? Please describe.

Something that's always consistently annoying when doing more rural playthroughs for me is how hard it is to get tin scrap to make into solder. I've never had so much issue gathering a single ingredient when I have 80 containers with the word "tin" in the name. 

### Solution you would like.

Please add a way to process tin cans into scrap tin.

### Describe alternatives you have considered.

Add requiring a tool if it makes it too easy.

**Comment by NetSysFire** [comment]
I am afraid that those "tin" cans are actually made out of steel.

https://github.com/CleverRaven/Cataclysm-DDA/blob/90d75fdc1a09bdaa39bae995fcfb5eff51bf1808/data/json/items/containers/containers.json#L1474

"Tin can" is a common word for any can and actual tin cans are very rare. See https://en.wikipedia.org/wiki/Steel_and_tin_cans

**Comment by Zireael07** [comment]
Yeah, AFAIK 'tin cans" stopped being made of actual tin over 70 years ago
