### ISSUE TITLE
Vehicle wrecks on bridges stopped spawning at some point

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#68504]
### Describe the bug

Just a self reminder to look into and fix this

### Attach save file

N/A

### Steps to reproduce

1. Walk to a bridge
2. See no vehicle
3. :c

### Expected behavior

1. Drive to a bridge
2. See a cluster of vehicles blocking the bridge
3. \>:c

### Versions and configuration

N/A

**Comment by ehughsbaird** [comment]
Was that point https://github.com/CleverRaven/Cataclysm-DDA/pull/41135#issuecomment-657727007, or were they added back since and lost again?

**Comment by Procyonae** [comment]
Looks like it ye, they made the maps JSON rather than C++ and I don't think anyone's hooked up the C++ vehicle placement stuff to them since unless I'm missing something, making bridge specific JSON spawns should be easy enough in the same way I did regular road ones in #67223 though ^-^

**Comment by stubkan** [comment]
Those roadblocks with cop cars, barricades and turrets also have stopped spawning entirely, it seems.  May be related?

**Comment by Procyonae** [comment]
Nope those were spawning fine as of my road PR and others are saying they still spawn

**Comment by stubkan** [comment]
Yes, the spawn frequency of those just went way down, making it seem like they dont spawn anymore.

It is like 10% of the original rate, due to the move to json, I guess
