### ISSUE TITLE
Bring back SPIW weapons

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#68508]
### Is your feature request related to a problem? Please describe.

SPIW weapons were removed from the base game based on painfully false reasons (or rather moved to aftershock). I won't get into details, check #61657 if you are interested but in short; ACRs (which is what the SPIW weapons were) were perfectly feasible and even superior balistic performance wise, but were outperformed by the service rifles of the time in cost and ergonomics and whatnot. It is perfectly possible that rivtech solved these issues with their belkan witchcraft or whatever and it also perfectly suits the current lore and rivtech design.

### Solution you would like.

Bring em back and change their names, descriptions or properties.

### Describe alternatives you have considered.

Provide actual reasons to why they wouldn't suit the game.

**Comment by kevingranade** [comment]
No thanks,  regardless of it being a hypothetically plausible for an alternate reality, is just too far afield to bother with.
