### ISSUE TITLE
NPCs cannot be operated on by Exodii/other NPC surgeons

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68510]
### Is your feature request related to a problem? Please describe.

I recently rescued several prototype cyborgs I found in a lab by disabling them and removing their personality override chips in an autodoc. I brought them to Rubik, but though their menu I could only install/uninstall CBMs on myself.

### Solution you would like.

NPC surgeons like Rubik or Doc Stevens should be able to install/uninstall CBMs in followers for barter value the same way they can on the player.

### Describe alternatives you have considered.

Be able to bring prototype cyborgs to the Exodii directly to have them operate on them, either to save them or use them for their own purposes.

### Additional context

RIP Fiona Spencer, cyborg, and future RIP to the other cyborgs whose implants I can't remove.

**Comment by PatrikLundell** [comment]
The lore changes have made pre cataclysm cyborgs nonsensical. At the least they shouldn't have Exodii CBMs in them, but rather one off hacks installed.

It can be noted that I'd prefer to keep cyborgs in, but the lore changes makes it difficult to explain their existence.

And yes, it would definitely be good if you could get NPCs willing to do CBM work on the PC to also work on companions.

A debug work around should be to switch control to the companion to perform the surgery and then switch it back (I've never used that functionality, but it ought to work).

**Comment by Leonkoithara** [comment]
We can modify the lore so that these cyborgs were NPCs who got CBMs implated in them by the Exodii, however the CBM got damaged or something during combat or normal wear and tear.

**Comment by PatrikLundell** [comment]
No, at least not with how cyborgs are now. They're found in labs and are supposed to have been experimented upon by the government's shadow organizations. They can't be captured Exodii modified people, as the Exodii arrived after the Cataclysm, and so is after the research facilities ceased to work.

Broken cyborgs make no sense with Exodii CBMs: if a second Exodii base/faction were responsible for them you'd have to introduce a reason for why the current faction would work against them. You could of course introduce a system whereby CBMs can be broken and become the various harmful versions, but that's probably a fair bit of work which would also require balancing so that the cyborg route won't become a pain in the posterior (or wherever these CBMs are installed...).

**Comment by MNG-cataclysm** [comment]
What if we changed the lore to include XEDRA managing to acquire broken or dead Exodii members in their portal experimentation, and they then started to experiment on people as a way to reverse-engineer this otherworldly tech? The broken and prototype cyborgs could be prisoners that XEDRA requisitioned to install their prototype versions of this tech on, but the Cataclysm hit and stopped work short?

**Comment by PatrikLundell** [comment]
That's rather iffy, given that there are very few Exodii, so the chance to encounter any should be very slim. It's less bad than the current situation, but I don't think it's good. The only good thing I see is that it would definitely mean the experiments visited blob infested dimensions.

**Comment by MNG-cataclysm** [comment]
Perhaps that same experiment would also be where they sourced XE-037 from, causing the chain reaction and containment breach that ended the world?

**Comment by PatrikLundell** [comment]
The mi-go connection doesn't make sense any longer either, as I believe they're from this dimension, and so the Exodii shouldn't have encountered them before. Also, mi-go biology seems to be unintelligible to humans, and so it shouldn't be possible to base anything on it, especially not for terrestial life forms (I believe mi-go meat isn't digestable to terrestial life, for instance).
