### ISSUE TITLE
[Xedra Evolved] Allow Mad Genius bots to follow you or remain stationary

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68519]
### Is your feature request related to a problem? Please describe.

I made a shotgun bot, which I love with all my heart, but it can't follow. It has legs and moves, but it cannot be told to either remain stationary or follow, so instead it sort of bumbles around after being deployed.

### Solution you would like.

It should be possible to order bots to either follow you or remain stationary, to work as a guard or turret.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/be3b8f93-f631-4d30-bff7-7123753bc1d7)
Look at him.

**Comment by Maleclypse** [comment]
I've marked it as also a Magiclysm problem as unless I am confused it's an issue with all summoned monsters.

**Comment by GuardianDll** [comment]
it is the issue with all summoned monsters #50506

**Comment by gisaku33** [comment]
In this case, the bots aren't summoned by a spell, they are crafted and then placed like the robots in base game. I'm not sure if that's different, though I'm pretty sure manhacks and other similar robots can be told to follow you.
