### ISSUE TITLE
Rendering performance regression while moving

### ISSUE THREAD

**Issue by stubkan** [CleverRaven/Cataclysm-DDA#68528]
### Describe the bug

In the last few months (I took a break, so don't know when this happened) something happened to cause rendering to drop in performance while travelling.  Measuring using a short bridge and observed a doubling of travel time.  It is better or worse in varied places, it can get more severe at times.

### Attach save file

N/A as it will occur on every save

### Steps to reproduce

1. Acquire vehicle or shoes
2. Travel using direction key or pressing/holding pause while moving in vehicle
3. Observe slowed rendering

One may use an older version of the game (Approx 6+ month at least I estimate) to observe the performance difference with the current build

### Expected behavior

The rendering speed should still be equal, the performance debug indicates so.

### Screenshots

The performance drop does seem to vary from place to place, I am unsure how to ascertain what amplifies it.  I attached a captured video showing driving over a short bridge in 0.F and the latest experimental using the same save file.  Holding down pause while driving at a steady 32km/h over the same bridge takes about 6 seconds in 0.F and takes 12 seconds in the latest Experimental as of Fri, 6 Oct.  The same behaviour occurs when tapping pause as holding it down, but I held it down for the video so the spacing of pauses would have been identical.

https://streamable.com/hj7846

I ran the Performance debug tool for 5 seconds in both versions and the output was identical for both, (first result is default zoom, second result is zoomed out once), possibly indicating that the performance debug metric seems to be a partial measuring of the rendering;

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/34361592/fc03aeb9-7783-43f0-864a-98f48a6564b6)

I tried changing the render engine, and found software being the fastest - even though I have a rtx 2060.

### Versions and configuration

Measured performance difference using 0.F vanilla and latest Experimental (6 October) but occuring since a week ago.
Built from source on ubuntu using TILES=1 RELEASE=1 SOUND=0

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21; Release: 21; Codename: vanessa; 
- Game Version: ada11d8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by harakka** [comment]
Just include the saves you used so that people can use those to easily test this.

**Comment by stubkan** [comment]
It appears to have been an issue with drivers.  There must have been some software difference between old/new versions.

Sorry for wasting time - but the issue has disappeared since I reconfigured my system GPU drivers.

**Comment by stubkan** [comment]
It appears to have been an issue with drivers. There must have been some software difference between old/new versions.

Sorry for wasting time - but the issue has disappeared since I reconfigured my system GPU drivers.

**Comment by harakka** [comment]
You can close the issue yourself

**Comment by stubkan** [comment]
> You can close the issue yourself

Im sorry, I tried to close it with that last comment with the "close with comment" option, and searched the whole page for any button to close it...  I cannot discover how to.
