### ISSUE TITLE
Allow math to write to proficiency exp and level

### ISSUE THREAD

**Issue by detahramet** [CleverRaven/Cataclysm-DDA#68529]
### Is your feature request related to a problem? Please describe.

For much the same reason as #68507, as resolved by PR #68490, being able to to read and write to proficiency experience and  would allow more direct manipulation of and interaction with proficiencies.

### Solution you would like.

Allow math to write to to proficiency exp and  like it can for skill level, such as:

`{ "math": [ "u_prof_exp('prof_bow_basic')", "+=", "10" ] },`

and

`{ "u_add_prof": "prof_bow_basic" }`

**Comment by GuardianDll** [comment]
Despite it wasn't ported to math, it is possible to reuse arithmetic syntax and write/read prof values, in format `{ "math": [ "u_val('proficiency', 'proficiency_id: prof_test', 'format: percent')" ] }`
