### ISSUE TITLE
Windows display scaling breaks visuals

### ISSUE THREAD

**Issue by SirDifferential** [CleverRaven/Cataclysm-DDA#68535]
### Describe the bug

The Windows tiles version does not correctly scale on high DPI displays if the Windows display scaling is above 100%. The result is the text getting blurry / faded. See the [linked video](https://plantmonster.net/videos/cdda_scaling_bug.webm). This seems to be something quite bizarre as the bug is only visible on my monitor, not when taking a screenshot or recording with OBS.

Changing Windows display scaling to 100% fixes the bug. My monitor is 2560 x 1440 running at 60Hz.

### Attach save file

N/A.

### Steps to reproduce

* Set Windows display scaling to 125% or 150%
* Start the tiles version of the game
* Open any menu and scroll up or down

### Expected behavior

* No blurry text with display scaling

### Versions and configuration

Latest experimental:

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ab63507 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

Also happens on 0.G:

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment]
Use a different renderer.

**Comment by SirDifferential** [comment]
That did it. OpenGL and Direct3D renderers don't have this problem, Direct3D11 and 12 do.

**Comment by FlyingSpaceRhino** [comment]
To fix blurry text, you can right click the .exe and click Properties>Compatibility>Change high DPI Settings>Override.
You can then increase the font size in the game settings to have large text without blur.
![Screenshot (1755)](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/ae1533da-ff06-4057-ae45-dd151e551ddd)
![before](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/1f3a4a1f-92c0-46f4-84bd-e529f97c6225)
![after](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/0ee4718a-1ccc-40d7-b375-41db5cacf265)
