### ISSUE TITLE
Gas mask cartriges are very short lasting, less than they are in real life.

### ISSUE THREAD

**Issue by MorvarchPrincess** [CleverRaven/Cataclysm-DDA#68554]
### Is your feature request related to a problem? Please describe.

Currently in game, Gas mask cartriges last a very short amount of time. I tested by standing in a gas vent, and my mask was losing 15 charges a minute of waiting, giving each cartridge about a 6m40s lifespan. Compare this to wikipedia, which mentions gasks masks lasting "around 8 hours" in a biological or chemical distuation, or this linked product page for a filter which describes a filter time of at least 20 minutes in worst case for chlorine gas.

https://en.wikipedia.org/wiki/Gas_mask

www.mirasafety.com/products/cbrn-gas-mask-filter-nbc-17-sof

I bring this up because especially in those instances where a gas mask is basically a neccesity (The collapsed tower for example) a gas mask lasts a frustratingly short time.

### Solution you would like.

In absolute worst conditions I think a single gas mask cartridge should last at least three times as long (20 minutes). Depending on how we want to assume the concentration and general nastiness of "toxic gas" and similar is, the cartridge could last up to multiple hours standing in heavy gas, but I'm assuming we want to lean on the more lethal end.

### Describe alternatives you have considered.

Leaving it as is.

**Comment by Karol1223** [comment]
> Depending on how we want to assume the concentration and general nastiness of "toxic gas" and similar is, the cartridge could last up to multiple hours standing in heavy gas, but I'm assuming we want to lean on the more lethal end.

I don't think we can differentiate how different fields of gas affect the filter, so in this case we should assume the worst case scenario and go with the 20 minutes, I believe.

If I am wrong and we can determine this per-field type, that's an entirely different story and opens more possibilities to work with this, but I doubt that's the case.

**Comment by ehughsbaird** [comment]
`gas_absorption_factor` https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#field-types

The pitiful lifespan of gas masks is why I made https://github.com/CleverRaven/Cataclysm-DDA/pull/66913, fighthing through a collapsed tower without it was painful.

**Comment by Karol1223** [comment]
> `gas_absorption_factor` https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#field-types

I am in awe that this exists, not gonna lie

**Comment by Maleclypse** [comment]
Closed by #68570
