### ISSUE TITLE
Inconsistent move costs for worn items

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68552]
### Describe the bug

Dropping worn Rollerblades - 488 moves
Taking off worn Rollerblades, into hands/wielding - 288 moves
Dropping held/wielded Rollerblades - 1 move
Taking off worn Rollerblades without hands free and no inventory space (ends up on floor) - 0 moves
Taking off worn Rollerblades without hands free with inventory space (ends up in backpack) - 0 moves
Inserting worn Rollerblades into backpack - 458 moves

Edit: More inconsistancies
Inserting held/wielded Rollerblades into backpack - 71 moves
Unwielding held/wielded Rollerblades, store in inventory option (ends up in backpack) - 288 moves

### Attach save file

N/A

### Steps to reproduce

- Wait until full turn available
- Do one above action
- Wait remainder turn
- Record time passed - seconds*100 moves (for 100 speed character), + moves spent for passing a turn

### Expected behavior

I haven't looked into the code behind this behavior, nor have I explored the scope of the issue as it applies to other worn items, so I have little reference for what proper values should be.

I'm going to assume I probably shouldn't be able to instantly phase out of my worn Rollerblades in combat, the Rollerblades probably shouldn't be able to instantly teleport from my feet into my pack, and that using the drop shortcut from the inventory should probably roughly be the same move cost as taking off the Rollerblades into my hands and dropping them.

Edit: Getting the item into backpack from wielded should cost the same amount of moves regardless of the method used.

### Versions and configuration

OS: Android
OS Version: Manufacturer: OnePlus; Model: HD1900; Release: 12; Incremental: Q.202303230244;
Game Version: 2c8ae07 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Slowdown Fungal Growth [no_fungal_growth],
  Bionic Professions [package_bionic_professions]
]

**Comment by GuardianDll** [comment]
#65062
