### ISSUE TITLE
Entering vehicles causes the game to crash

### ISSUE THREAD

**Issue by PapaBones** [CleverRaven/Cataclysm-DDA#68558]
### Describe the bug

Whenever I run into any non wreckage vehicle the game instantly crashes with the following terminal output:
```
cataclysm-tiles: src/catacharset.cpp:350: std::wstring utf8_to_wstr(const string&): Assertion `sz != static_cast<size_t>( -1 )' failed.
[1]    15775 IOT instruction (core dumped)  ./cataclysm-tiles
```
Game seems to run fine otherwise, just vehicles are entirely inaccessible. It doesn't matter if I use the latest version of go back to a week or two, also have crashes. 

### Attach save file

[Sea Cliff-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12840391/Sea.Cliff-trimmed.tar.gz)

### Steps to reproduce

Walk into any vehicle that can be operated/isn't crashed.

### Expected behavior

Game should not crash

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 46ed75d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

12:12:14.674 : Starting log.
12:12:14.674 INFO : Cataclysm DDA version 46ed75d
12:12:14.674 WARNING : Error while setlocale(LC_ALL, '').
12:12:14.674 INFO : [main] C locale set to C
12:12:14.674 INFO : [main] C++ locale set to C
12:12:14.674 INFO : SDL version used during compile is 2.0.10
12:12:14.674 INFO : SDL version used during linking and in runtime is 2.28.4
12:12:14.690 INFO : SDL render devices: software, opengl, opengles2
12:12:14.691 INFO : [options] C locale set to C
12:12:14.691 INFO : [options] C++ locale set to C
12:12:14.691 INFO : Setting language to: 'en'
12:12:14.691 INFO : [i18n] Scanning core translations from lang/mo/
12:12:14.813 INFO : Active renderer: 2/software
12:12:15.275 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
12:12:15.280 INFO : Setting language to: 'en'
12:12:17.702 INFO : src/mod_tracker.h:68: Tried check if 'FakeSpecial_s_gas' had a duplicate, but type 'overmap_special' does not track object sources
12:12:22.161 INFO : Loaded tileset: UltimateCataclysm
12:12:22.237 ERROR SDL : src/cata_tiles.cpp:759: The tileset you're using has no 'unknown' tile defined!

**Comment by irwiss** [comment]
Seems to be related to locales, can you check if your distro's locale package is installed?

**Comment by PapaBones** [comment]
> Seems to be related to locales, can you check if your distro's locale package is installed, and the locale-gen generated the correct locales? https://wiki.archlinux.org/title/Locale seems to be the docs to start with

That actually seems to have been the fix. For some reason my locale had a missing line somewhere, I never even went into it in ages so no idea why it got deleted. I even checked there but could not find anything amiss, now I checked and fixed it, game's working now, thanks!

**Comment by TheCYPER** [comment]
This problem seem to occur commonly in Unix-like systems, including Macos and Linux
Also, what are the steps I need to take to setup the [Locale](https://wiki.archlinux.org/title/Locale) in Macos
Many commands mentioned in that doc cannot be used in my shell😢

**Comment by irwiss** [comment]
@TheCYPER I suggest you make a new issue, only the 3 people subscribed to this one or a non-default filter can see this issue got comments, I don't know enough of osx to give advice on it
