### ISSUE TITLE
Horizontal lines on tile borders glitch on some Android phones

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#68567]
### Describe the bug

Horizontal lines appear between sprites

Copied report from there https://github.com/I-am-Erk/CDDA-Tilesets/issues/2129 turns out we don't have an open issue about
Not sure if it's the same as #56680 or a comeback of #27731

Maybe @gettingusedto  can give more info?

### Attach save file

N/A

### Steps to reproduce

Not sure I'm copying report from someone else, looks like an issue with some android device

### Expected behavior

No lines on screen

### Screenshots

![266816983-be82eeec-e774-403e-945c-28f23e25235c](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/c7249584-5e77-483c-a18f-8bab8264762e)

![266816985-9c61af9b-162c-4d81-aa99-4de2593c316c](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/560589bb-63b8-48c8-8d97-ba3f54e3d0c6)

![266816987-58f69cc9-9a6d-4cbb-8350-308fe94d42ad](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/f3ef0cbd-3484-4854-96e4-60ffc3e735bf)

![266816988-db373b4a-9377-45b3-8f8b-e4d4b7522ea3](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/5f1827f2-387b-4a72-aa85-a0a942055c0b)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: a5d2724 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Aftershock [aftershock],
    cable stuff [cablestuff],
    LuckySlotmachine [luckyslotmachine],
    Mind Over Matter [mindovermatter],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    GUT's Contents Compendium [gut_contents_compendium]
]

**Comment by GuardianDll** [comment]
/confirmed, i recall this issue is at least half year old
it is probably a duplicate

**Comment by gettingusedto** [comment]
As the one who gave the game report, yeah it happens to me.

![Screenshot_2023-10-09_04-07-50](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/48ac04f4-7794-4bf6-8919-af58263395aa)

**Comment by ZhilkinSerg** [comment]
Yeah, issue occasionally appears on some devices.

**Comment by harakka** [comment]
This only seems to appear on rotated tiles so there's probably an off-by-one / rounding error in some coordinate after rotation on particular graphics stacks.

**Comment by AnotherSeawhite** [comment]
It's weird. The issue disappears when I use software rendering.
The Left is with software rendering, the right is without it.
![무제234_20231015080456.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/98e20bcc-dcde-4ac7-bf90-b8be48b0cda7)

**Comment by Kalvenor** [comment]
A

> As the one who gave the game report, yeah it happens to me.
> 
> ![Screenshot_2023-10-09_04-07-50](https://private-user-images.githubusercontent.com/78019001/273474119-48ac04f4-7794-4bf6-8919-af58263395aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Njc4NDgsIm5iZiI6MTcwNTc2NzU0OCwicGF0aCI6Ii83ODAxOTAwMS8yNzM0NzQxMTktNDhhYzA0ZjQtNzc5NC00YmY2LTg5MTktYWY1ODI2MzM5NWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE2MTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjM3Nzk0OGU4NWExMTg0NDI5NzYzNTllZTc5Y2M4OWRkMzljYTIyNDRhYmMyMGM1MjY5M2E3MTI5NDg0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mg5WjZ1qLDFGxZMEPmB9y1F71ud8fxXd6TK8hpJ9eWk)

Any solutions yet?

**Comment by RenechCDDA** [comment]
Resolved by #72154
