### ISSUE TITLE
NPCs panic without any hostiles in view

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#68568]
### Describe the bug

Please see attached save. Once the group moves a few steps to the left all of the npcs start to panic and become combat ineffective. The actual hostiles won't come into view until you move even further west. 

This save has a simple example of this happening, but it's much worse in cities.

### Attach save file

[Sugar Bush-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12841884/Sugar.Bush-trimmed.tar.gz)

### Steps to reproduce

Move player west/left a few spaces - watch the squad of ultimate badasses turn to jelly.

### Expected behavior

NPCs should not panic unless the hostiles are an imminent threat. Hostiles that are not detected should not be considered.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19167795/411c10ca-594d-4886-a039-3aeaa8f71b8d)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 21c2466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope]
]

**Comment by pwalsh0** [comment]
In this case you could say maybe the NPCs have higher perception rating - so they can see the hostiles while player cannot. But this also happens if the NPCs are hidden behind a wall or inside a building.

**Comment by pwalsh0** [comment]
Here is a good save to illustrate the problem. Got 3 npcs with me, all of us armed and armored. But then panic far too easily so it's difficult to use them in city.

Suggested fix: NPCs should get a positive morale bonus from other friendly npcs nearby. Thus enabling some kind of defensive formation where they can hold the line.

[vanilla-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12999589/vanilla-trimmed.tar.gz)

**Comment by I-am-Erk** [comment]
Should be fixed by #69213
