### ISSUE TITLE
Refuge merchant fema drive bug

### ISSUE THREAD

**Issue by Racelkatyusha** [CleverRaven/Cataclysm-DDA#68565]
### Describe the bug

If you found a hub-01 first and then go to the refuge center, and ask the merchant to give you the fema drive to deliver it to the hub-01, he will tell you that you already did it even though you never did yet, and I think this prevents spawning the free merchants camp nearby as well or no?

### Attach save file

N/A

### Steps to reproduce

Find a hub-01 first and talk to it, do their field data mission first and do more if you want, then go to a refuge center and find the merchant, talk about other settlements and he will tell you that he already tokd you about them and you already gave them the fema drive even though you haven't, probably because there's also a nearby HUB-01 just to the east, the hub-01 I use is in the west and I have barely talked to the eastern hub-01 but just to check if both will respond the same but nope, both are independent from each other

### Expected behavior

I expected the refuge merchant to give me the fema drive to deliver it to the hub-01, but there's also another hub-01 just to the east, the west hub-1 was my main and first contact, didn't touched the eastern hub-01 futher other than see if it's the same, but no

### Screenshots

None

### Versions and configuration

O.G Stable Version

Playing on Mobile android

### Additional context

None

**Comment by harakka** [comment]
Can't reproduce on c5e873a (about a week old at time of writing), quest seems to work as expected.
