### ISSUE TITLE
Double line box drawing characters in the UI don't use the Terminus font like they should

### ISSUE THREAD

**Issue by Lumi-Virtual** [CleverRaven/Cataclysm-DDA#68589]
### Describe the bug

The double lined box drawing characters ╡╢╖╕╣║╗╝╜╛╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪ render using the default font Unifont instead of Terminus, while the single line characters │┤┐└┴┬├─┼┘┌ do correctly render using Terminus. This possibly extends to more characters but I have not done any more testing to see if that's the case.

### Attach save file

N/A

### Steps to reproduce

Draw any of the double lined box drawing characters along with single line characters in the UI, such as in ASCII art, to see the mismatched fonts.

### Expected behavior

The double line box drawing characters should render using the Terminus font when it's available and being used for the rest of the UI rendering.

### Screenshots

Expected
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65882669/ec3f703f-0841-4c8c-9c55-0a459d78a630)
In game using Terminus
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65882669/6ed3f1a5-58ee-42fa-8dbf-befbfee9bcc0)
In game using Unifont
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65882669/126d2384-03ed-46e4-8f4a-c4211e1f8eed)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment]
Glyphs missing in a used font are taken from default font (unifont).

**Comment by Lumi-Virtual** [comment]
Terminus does support those characters, so they're not missing. You can open it in a font editor to verify.

**Comment by ZhilkinSerg** [comment]
> Terminus does support those characters, so they're not missing. You can open it in a font editor to verify.

Terminus is a bitmap font which includes only specific sizes (`6x12, 8x14, 8x16, 10x18, 10x20, 11x22, 12x24, 14x28 and 16x32`). Maybe you are using some unsupported font size?

**Comment by ZhilkinSerg** [comment]
Here is what I get:

**Terminus:**
![1_terminus](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/cf0607a1-9d3c-47f9-a9d0-d3830df997d1)

**Unifont:**
![2_unifont](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/2ec48419-1fe9-4d8b-983e-f38c95fa38c8)

**Comment by Lumi-Virtual** [comment]
I'm using 8x16. How do I run that text test thing? Also looking at those images closer, it seems like the terminal bounding box line drawing characters don't change at all when switching fonts somehow? You can see that the light single line horizontal characters move up a pixel when switching from Terminus to Unifont but the actual UI box doesn't do that, which is extra odd because the rest of the characters like letters etc in the UI do change with the font.

**Comment by Lumi-Virtual** [comment]
I did some testing and that actually seems to be whats happening. I replaced all the single line box drawing characters in the Terminus font with ┄ and made it use that modified font, and you can see that it isn't displaying that graphic in game. (Also the text looks weird since I didn't export it with bitmap levels but its still Terminus, just aliased weird.)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65882669/66916edc-2cac-42bd-8069-a687ce50010f)

**Comment by ZhilkinSerg** [comment]
> How do I run that text test thing?

Add required text to `\data\credits\en.credits` and see it in Credits menu.

**Comment by Lumi-Virtual** [comment]
Oh I am a fool that certainly was it, I never even knew that was a setting since it was enabled by default. Thanks for your time ^-^
