### ISSUE TITLE
Item transformations result in duplicate Relic_data

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#68605]
### Describe the bug

A regresion of past behavior, where enchantments once set couldn't be modified by item transformations.

The current versions allows item transforms to add to their relic_data. This causes items that use relic data and rely on item transforms to implement (on) and (off) version of themselves to infinitely stack their enchantments whenever they are turned on or off.

### Attach save file

[Pitkin-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12872225/Pitkin-trimmed.tar.gz)

### Steps to reproduce

1. Load into the provided save file, it has all the setup required to experience the bug.
2. Activate the advanced nomad Jumpsuit
3. Notice it gives its related enchantment twice, once from the original item and the second one added by its transform to the on version (since its using copy-from),
4. Turn it off and on again.
5. It now grants its enchantment four times, one added everytime the items transforms.
6. Repeat as many times as desired for increasing enchantment benefits.

### Expected behavior

An item's relic_data should remain fixed through transformations.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 0.G-4194-gb504d0e3c2-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This is the bug causing: #68470

**Comment by GuardianDll** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/734c8f6e-47ee-4fd6-ac6d-6114dddc83ff)
#67835


also #68167 can be close as duplicate

**Comment by GuardianDll** [comment]
@Kamayana may i ask you to help with this? i suppose it's justs a cache invalidation missed in some place
