### ISSUE TITLE
Repair kits must be unloaded before fixing cars with them

### ISSUE THREAD

**Issue by bug-sniper** [CleverRaven/Cataclysm-DDA#6860]
The fact that repair kits are tools should make them usable for whatever their unloadable components are usable for. I should be able to install car parts with repair kits with unloadable duct tape, especially since they are a tool. If not, the extra step of unloading them is only an inconvenience.
##

**Comment by Night-Pryanik** [comment]
Car parts aren't repairable with duct tape anymore.
