### ISSUE TITLE
Vehicle storage space is not working

### ISSUE THREAD

**Issue by NickEmbased** [CleverRaven/Cataclysm-DDA#68610]
### Describe the bug

Can't put some items in vehicle storage, for some unknown reason. Neither sorting zone or putting with advanced inventory is working. Despite having enough space for that. 

### Attach save file

[Трафальгар-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12874953/-trimmed.tar.gz)

### Steps to reproduce

1.Open advanced inventory 
2.Select 1 piece of salt and try to put it in cargo space
3.Get error 

### Expected behavior

Get items in vehicle storage that has sufficient space

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77558147/edeca094-a979-4677-a507-d375a6a30122)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 11a2c1e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by casswedson** [comment]
you're running into the max item cap of a tile; you can only fit like 4K items in a single tile

the message could be improved, like mention something bout too many items rather than "unable to fit"

**Comment by NickEmbased** [comment]
@casswedson  oh thanks for explaining haven't tried figuring this variant out. Seems like great idea about giving message why, also sorting is still kind of quite junky, because when you press "sort out my loot" characer just goes collecting everything in backpack  and then after backpack is full goes dropping  items back on  grass, it gets you softlocked if you dont want to manually pickup hungreds of items and drop them back, so you need to really quick spam ESC and with 5 to stop this because of prompt "Stop wielding"

**Comment by NickEmbased** [comment]
Well, i am closing this now, and will open suggestion about game not giving information why you can't put items despite having space and that you have two spam two buttons just to stop the character to useless sorting
