### ISSUE TITLE
Road blocks are extremely rare and provide too much loot

### ISSUE THREAD

**Issue by stubkan** [CleverRaven/Cataclysm-DDA#68612]
### Describe the bug

It seems that road blocks now spawn extremely rarely - I've only seen one in approx 10 country road-trip games.

In addition to that, the one I saw spawned in the wrong facing, with extremely overpowered loot (half dozen guns, several sets of armour, a bucketload of ammo and grenades) - Due to the rarity of roadblocks, I cannot tell if this is normal, but will report back once I find more.

### Attach save file

N/A

### Steps to reproduce

Try to find a roadblock by driving around.

### Expected behavior

Expected road block frequency to be at least somewhat as frequent as they used to be back when they were C++ generated and not jsonized.

Also, facing the right way.

Also, not handing you a small armys worth of weaponry and gear for free (since all the zombies are occupied with the turrets, you pick them off effortlessly)

### Screenshots

I drive around quite a lot.  Here is the map of the lower half of my current run ;

![screenshot-20231012-031303](https://github.com/CleverRaven/Cataclysm-DDA/assets/34361592/887e9b54-8e70-4ae8-abc2-4a9f9695a3a5)

After a bunch of games, I finally found one roadblock, after thinking they were disabled and not spawning - here it is, you can see it spawned facing the wrong way;

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/34361592/c46613ee-db1c-4cb1-9c72-0fbd8ddaa4ad)

It spawned with 3 SWAT cops, a Z9 as well as assorted dead cops.

This is the LOOT I got from this one location.  NOTE - I play with HALF item spawns, so the regular loot would be DOUBLE this.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/34361592/3272cb5a-0827-4091-b467-22d0e1ea3e36)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21; Release: 21; Codename: vanessa; 
- Game Version: ada11d8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Minimod: No Skill Rust [minimod_no_rust]
]

### Additional context

Due to only finding one roadblock, the metric for measuring its loot is not really good - I will report back once (if) I find another roadblock on my travels, or maybe someone else who has found one on the latest Exp. build can chip in.

**Comment by fairyarmadillo** [comment]
The turrets need to go. They do not provide much of a gameplay challenge and mostly just trivialize the area for the player. They also really stretch disbelief and don't really do anything that the cops who are also posted at the roadblock couldn't have done better.

**Comment by stubkan** [comment]
I was actually working on that stuff when they jsonized the roadblock stuff.  I've just come back to the game now, so .. perhaps fix broken things first.

**Comment by ZhilkinSerg** [comment]
Mapgen extra chances haven't changed much when roadblock mapgen was unhardcoded in #62407, so it must be subjective.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/b58931f9-3fc7-4fc2-aeb9-9e6740f4d708)

**Comment by PatrikLundell** [comment]
The frequency in my game, started 1-2 months ago, seems to be about the same as it used to be.

When it comes to loot I've only cleared out one, and it didn't provide anything to write home about, just standard police stuff you'd find from eliminating the same number of police zombies  (not 5.56 or 7.62 rifle type arms which is what I want). The only thing of value would have been the generator, but the zombies smashed it.

I teleported around to look at my road blocks, and all of them were placed to block N/S access, even though the roads were E/W, with one being diagonal , so N/S might be sort of OK in that case, but not placed where they should be to match the road.
Thus it looks like there would need to be something to rotate the setup for E/W road a version for diagonal roads that could be rotated for the other orientation.

**Comment by stubkan** [comment]
Yes, the jsonizing 5 months ago made it chance of 830.  Although it still not seem indicative of the actual spawn rate - which would make this a bug.

For comparision, 

Roadworks has a spawn rate of 1000, and I have seen a half dozen on this map.
A prison bus, 150 - found one.
Mayhem type, 500 - found a bunch of them.
Roadblock - 830 - only one found.

Of course, it could just be bad RNG rolls, but I've played several games now with a lot of driving around, and usually roadblocks were my main source for gear starting out - so I used to find them more frequently and reliably - this was before the jsonizing though the chance back then was slightly higher - being 1000.

The fact that it only spawns in N/S orientation appears a result of only one roadblock type that will ever spawn now its jsonized and the code does not gather the road context to orient itself unfortunately.

**Comment by stubkan** [comment]
Examining the mapgen reveals why the loot is OP.

Previously, it would generate 1-6 dead cops who spawn with general cop loot and that was it for the loot

But with the new mapgen, it generates 3-6 cop group zombies which can now be upgraded type cops/swat which also drop better loot so that's slightly increased loot there.

Now in addition to that, the new roadblocks will spawn 3 loot zones under each car (which is probably why Patrik reported normal loot, you have to view all items to spot the items under the cars), the 3 loot zones are pretty strong since they each generate 0-9 drops direct from police armory drop list

**Comment by PatrikLundell** [comment]
I can confirm I haven't looked under the cars.
