### ISSUE TITLE
Some zombies spawn with mismatched gun and ammo (.40 vs .357)

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#68622]
### Describe the bug

Please see screenshot. 

This zombie cop has a Glock 22 with a .40 magazine loaded. It is carrying two spare magazines but with the wrong ammo.

This type of magazine can carry either .40 or .357 - this is where the confusion comes from? The gun in this case can only use .40. 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19167795/e58e68e3-5436-4d52-a3a1-6a42b552980e)
 

### Attach save file

n/a

### Steps to reproduce

1. Find zombie with a gun that can use this type of magazine (glock 0.40 / 0.357)
2. Kill zombie
3. Inspect inventory - see if it is carrying right ammo

### Expected behavior

The zombie should carry the appropriate type of ammo (0.40 in this case, instead of 0.357).

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 91b933b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by pwalsh0** [comment]
I don't mind the 5.56 mags - those are for the primary weapon they have dropped I assume.

However the sidearm in the vest with mismatched sidearm ammo = literally unplayable ;)

**Comment by PatrikLundell** [comment]
It's certainly not unplayable. A bit off maybe, and you may have to loot several zombies to get a match, but it's not worse than that.

As far as the 5.56 magazines go, I don't think even American cops are equipped with rifles as their primary arms.

**Comment by pwalsh0** [comment]
Every American is legally required to own an AR-15 I think, even the cops.

**Comment by underwillowtree** [comment]
nested_glock_22
nested_glock_31
nested_acr_300blk
police_armory_glock_22

Possibly these item groups may be causes.
These item groups have magazines that can be loaded with different types of bullets, but they don't seem to have a set of bullets to load.

**Comment by pwalsh0** [comment]
Would have to make 2 versions of the glock magazine - one with 0.40 rounds and another with 0.357 rounds. Then nest the appropriate type with the gun.
