### ISSUE TITLE
[AfterShock] Problems with salvage crossbow

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#68624]
### Describe the bug

_I apologize for the report with several errors, but it was convenient to do it this way_

1. I can’t say for sure that this is a problem, perhaps it was intended this way, but you can’t shoot from a salvage crossbow from your hands, it’s loaded and has UPS, but you can’t shoot. But if you install a crossbow on a car, shooting is possible
**salvage crossbow**
![salvage_crossbow](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/431a7033-7598-4ecb-89fb-14bd92482f3d)
**inventory**
![inventory](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/c5991758-4af2-4482-9052-13c2ff525cd3)
**problem**
![can_t_fire](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/198571cd-dc6d-4217-823c-c27e670ac11e)
1. SIGABRT after installing a loaded salvage crossbow
**already install**
![mount_crossbow](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/933e4b6f-9136-4a8d-84d8-9a538da4875b)
**salvage crossbow is load**
![unload](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/4515df7d-f858-4385-9bef-f032aac31e70)
**bad bolt**
![bad_bolt](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/e14a45fc-22f2-40c2-be2b-b729ea058fe9)
if i try drop(i can't drop) or replece bolt from inventory game crash with SIGABRT

### Attach save file

pre problem save
[Magenta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12886737/Magenta-trimmed.tar.gz)

### Steps to reproduce

1. try fire with salvage crossbow
1. SIGABRT
    1. install **_load_** salvage crossbow
    1. try to free the equipment from the bolt

### Expected behavior

1. no problem shooting a crossbow handheld? (I'm not sure that's not the idea)
2. no crash

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: ab63507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12886857/crash.log)

**Comment by John-Candlebury** [comment]
Partial solution in # #68629 that takes care of not being able to fire while on foot. I'll test the vehicle issue later.

**Comment by watcherPlayer** [comment]
with new commit crossbow work in hand

but sometimes quite rarely when shots are fired a notification appears

 DEBUG    : Stray characters at end of floating point value 369.000000 in item::get_var

 FUNCTION : get_var
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1696
 VERSION  : 356bfe5

**Comment by John-Candlebury** [comment]
Can you please make a separate report for that?
I'll need more context to fix that one too ( by which I mean a save with a before it happens).
I don't think the crossbow is directly related to that error just from looking at where the message is in the game's code.

**Comment by watcherPlayer** [comment]
excuse me please, my last observation is worth developing, I will observe and if the error is stable and repeatable I will publish the topic

I didn’t quite understand what exactly to separate, the problem with the crossbow in the hands was fixed, the problem with SIGABRT was not; SIGABRT separate?
