### ISSUE TITLE
Quicker to merge solar panel and disconnect appliance then to deconstruct furniture

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#68621]
### Describe the bug

There is a discrepancy between taking down a solar panel as an appliance and deconstructing a solar panel as furniture. I encountered this when disconnecting panels from the solar farm.

### Attach save file

[Leighton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12883717/Leighton-trimmed.tar.gz)

### Steps to reproduce

1. Go to construction menu and use 'deconstruct furniture' to deconstruct a solar panel. Observe it takes 20 minutes
2. Interact with a solar panel and input 'yes'  when asked to connect it to the grid
3. Interact with the solar panel again and input 'take down appliance'. Observe it takes 3 minutes

### Expected behavior

An equal amount of time spent taking down the solar panel

### Screenshots

Observe the time on the left side
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/d018b5b7-dfb5-4315-a0c7-f0e37cc6e400)

The first time gap is 20 minutes and the second time gap is 3 minutes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 91b933b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by gettingusedto** [comment]
concerningly enough, taking it down through the deconstruct furniture thing bypass the need of bolt turning tools
