### ISSUE TITLE
Two issues with [Sorting zones] and [Vehicles cargo spaces]

### ISSUE THREAD

**Issue by NickEmbased** [CleverRaven/Cataclysm-DDA#68631]
### Is your feature request related to a problem? Please describe.

Hello everyone! Recently i tried to move all my loot that i gathered for two seasons to vehicle cargo spaces  and got two major problems.

1.I just discovered with other's help there is a limit for items that can be in one tile. So a vehicle can't fit 1 unit of salt despite having 450 liters free. My problem is that game does not state reason why you can not place 1 more grain of salt despite having space, making me think it is a bug rather than feature
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77558147/aff8a743-45f5-4b4a-887c-b688fd9e137b)

2.And because of that when you try to sort hungreds of liters to your car, character wont stop trying to sort them inside and will rather start to pick up every item in a backpack, after that character will wield item in hands and will continue untill every item left is picked up and dropped on same tile. To stop this you have to quickly spam ESC to have miliseconds gap before "Stop wielding" window will open and have to press 5 to stop sorting.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77558147/2577f508-a226-41c7-86f9-8c64f459a37e)

Those two issues makes transporting loot you have to a car very uncomfortable.

### Solution you would like.

1.Write a more concrete reason when you try auto and manually putting item in a cargo space and it fails even with having enough space. Like "Too many items in one space", so you will know it is not a bug.

2.Make character stop sorting when they can't put more items in vehicle so you don't have to spam two buttons within milliseconds to stop useless picking up and dropping items back.

### Describe alternatives you have considered.

1.Remove the limit of items in one cargo (I do not remember having this feature before, and i dont know why it got implemented so i dont know if it is right one) 

2.Make function to stop sorting less annoying when you have to wield hungreds of items, so have only press one button at any moment

**Comment by PatrikLundell** [comment]
As far as I understand, the item limit has "always" been there. The reason it causes trouble now is that charges were removed, so what once one salt item with 1000 charges is no 1000 salt items. At a guess, the item limit is arbitrary and should definitely be revised to handle the item spam resulting from the removal of charges.
