### ISSUE TITLE
Speed adjustments from effects are listed twice in the UI

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#68633]
### Describe the bug

Despite the adjustments applying properly, any adjustment effect is displayed twice within the `@` character screen causing posible confusion,

### Attach save file

N/A

### Steps to reproduce

1. Spawn any character.
2. Use the debug menu and grant you a simple speed adjusting effect (I suggest the monster staggered or frenzy effects since they are simple).
3. Notice that both the sidebar and the speed total sum within the `@` character sheet  displays your correct speed, but the adjustment is listed as if it were aplying twice

### Expected behavior

The UI only prints the speed adjustment once.

### Screenshots

![imagen](https://github.com/CleverRaven/Cataclysm-DDA/assets/5290912/da7ce626-cb69-4407-aa53-e2cb85af0647)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2283 (22H2)
- Game Version: 0.G-4531-g11a2c1e605-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock]
]

**Comment by GuardianDll** [comment]
/confirmed, since #65037 exist

also https://github.com/CleverRaven/Cataclysm-DDA/pull/64612#issuecomment-1506024972

**Comment by alef** [comment]
Adding one speed effect via debug and opening `@` immediately, it will show only one.
But stepping the game forward, it duplicates it.

**Comment by Maleclypse** [comment]
Closed by #70831
