### ISSUE TITLE
Old microlabs failing to generate properly

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#68637]
### Describe the bug

Visited a microlab (the labs that you can reach from a ventilation shaft in the middle of a forest) that I had previously discovered its location, but had not gotten close to until today... And when I went close to its location I found myself bombarded with error messages, since this is not weird in experimental I decided to continue anyway and see if the lab was still functional, but... Well, see the screenshots, the lab did generate, but empty of furniture and most internal walls (walls that touch with rock did mostly generate), there are zombies and a couple of cloning vats/pipes, but I teleported by all the place and it's empty... Some areas even were registered in the overmap as rock, but the lab room was generated anyway (Empty, as all the rest).

I assume this is an error introduced in #68593

### Attach save file

[Bug lab.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12908276/Bug.lab.zip)

### Steps to reproduce

1. Generate a new game in an old version of the game (?)
2. Find a Microlab in your overmap but do not get close to it (Use a map, some reveal lone forest tiles, they are always a ventilation shaft for a microlab).
3. Update your game.
4. Teleport to the general area of the microlab.
5. See the horror.

OR:

1. Open the attached save.
2. Walk to the right.
3. See the errors.
4. Additionally, you can see the empty lab for yourself, the entrance is to the right, marked in the overmap with a note.

### Expected behavior

To have the lab generate properly.

### Screenshots

![Screenshot_20231013_142051_Cataclysm DDA (experimental)](https://github.com/CleverRaven/Cataclysm-DDA/assets/53200489/8d2eba6c-882f-4167-b73c-08029b651869)
![Screenshot_20231013_142127_Cataclysm DDA (experimental)](https://github.com/CleverRaven/Cataclysm-DDA/assets/53200489/a5f37650-8c12-475d-90fb-67374eafd9d6)
![Screenshot_20231013_142149_Cataclysm DDA (experimental)](https://github.com/CleverRaven/Cataclysm-DDA/assets/53200489/e012abdb-2f52-4b34-ad08-fae701ee1f6a)
![Screenshot_20231013_142203_Cataclysm DDA (experimental)](https://github.com/CleverRaven/Cataclysm-DDA/assets/53200489/27512e8d-9bcf-4a1a-b021-2c6247a2d4d6)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A525M; Release: 13; Incremental: A525MUBS6DWH2; 
- Game Version: d4ab613 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

 DEBUG    : No such parameter "labtype"

 FUNCTION : Result mapgendata::get_arg(const std::string &) const [Result = string_id<mapgen_palette>]
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/mapgendata.h
 LINE     : 244
 VERSION  : d4ab613

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            No such parameter "labtype"

 FUNCTION : Result mapgendata::get_arg(const std::string &) const [Result = string_id<mapgen_palette>]
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/mapgendata.h
 LINE     : 244
 VERSION  : d4ab613

**Comment by Termineitor244** [comment]
Attached save file.

**Comment by NickEmbased** [comment]
Got same bug in my game walking close to subway labotory and getting 
DEBUG : No such parameter "labtype"

and getting no lab generated only floor of it

**Comment by redcrate** [comment]
> Got same bug in my game walking close to subway labotory and getting DEBUG : No such parameter "labtype"
> 
> and getting no lab generated only floor of it

I am also getting this error near a subway lab, as well as this:

 DEBUG    : No such parameter "labtype"

 FUNCTION : Result mapgendata::get_arg(const string&) const [with Result = string_id<mapgen_palette>; std::string = std::__cxx11::basic_string<char>]
 FILE     : src/mapgendata.h
 LINE     : 244
 VERSION  : 0e57b43

**Comment by Procyonae** [comment]
This bug should only occur when teleporting to them and shouldn't be seen in normal vanilla gameplay, no parameters get set properly when teleporting within reality bubble of them (I forget which other maps this occurs with off the top of my head)

**Comment by Procyonae** [comment]
Potentially related to #60395

**Comment by Orange01gaming** [comment]
> Potentially related to #60395

I believe it is as Im having both bugs on my save. So sad as I have played this save for 4 years so far and dont want to abandon it.

**Comment by Procyonae** [comment]
Is this still occurring? I didn't see a PR claiming to fix the issue but I've not seen the error while testing in months

**Comment by Orange01gaming** [comment]
I haven't updated in a while as I haven't heard anything here or the other
bug report I was aware of. If it's fixed I'll update tonight and test to
confirm.

**Comment by Orange01gaming** [comment]
It is totally is still occurring on latest experimental with my save.

**Comment by Procyonae** [comment]
As in your save is fine prior to updating and then breaks post updating? (A fix to this is very unlikely to fix existing cases)

**Comment by Orange01gaming** [comment]
No, the save has issues with the pallete bug before updating and after. It
will start but has a couple other bugs. I loaded up much older saves and
those seem to work from about 1 year ago. In other words, they don't have
the pallete bug.

**Comment by I-am-Erk** [comment]
We're continuing to have troubles replicating this on devcord. I'm tentatively inclined to close it, but I have absolutely not problem reopening it if someone can figure it out.
