### ISSUE TITLE
[Magiclysm] For some reason, the orcs in the orc village run to the lower right.

### ISSUE THREAD

**Issue by CHCOOH** [CleverRaven/Cataclysm-DDA#68648]
### Describe the bug

When visiting the orc village, it was curious that the orcs were pooled in the lower right corner regardless of the orientation of the village.
From what I saw in debugging, they always run toward the southeast for some reason.
If blood orcs are present, they break the wall and run off further southeast.

### Attach save file

N/A

### Steps to reproduce

Try the village of Oak.
They are always in the lower right corner.

### Expected behavior

I would say it's a bug, but I don't think it affects much, just interesting.
If I may say so, if you show your face at a corner thinking there is no one there, you will be chased by a large number of orcs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    追加 - Magiclysm [magiclysm]
]

**Comment by snipercup** [comment]
I saw this too. They will come to chase me if I get close. An archer was sneakily standing behind a wall in the northwest, apparently not willing to run southeast like their friends.
