### ISSUE TITLE
[aftershock]If AFS is included, the facility that should be placed in the lake will not be placed.

### ISSUE THREAD

**Issue by CHCOOH** [CleverRaven/Cataclysm-DDA#68646]
### Describe the bug

Lifhthouse, FreshwaterResearchStation, dock, prison, AircraftCarrier, etc. will be located at the lake, though,
AFS will generate a lake without any of these.

We started the game with a scenario that generated 10 worlds each with AFS and 10 vanilla worlds, starting with AircraftCarrier.
Of these, I counted the number of "lakes that had nothing" and the number of "lakes that had something".
Even if the lakes are connected, if they are separated by an overmap, I counted them as separate lakes.
"Nothing happened" : "Something happened."
AFS 
1:1
2:3
1:3
0:4
3:0
1:1
1:3
1:3
1:1
1:1

Vanilla
1:0
4:0
2:0
2:0
2:0
2:0
3:0
2:0
4:0
1:0

In addition
Deleting the \data\mods\Aftershock\maps\overmap_terrain folder seems to solve this problem.

### Attach save file

N/A

### Steps to reproduce

AFSを入れて通常通りに世界を生成してください。

### Expected behavior

I was ready for the world with AFS in it and shrugged it off if I went to the lake to play.

The AFS.
data\mods\Aftershock\maps\overmap_terrain folder　
are not used by "aftershock" but seem to affect its generation. I do not know why.
Similarly, the files in
data\mods\Aftershock\maps\mapgen\tunnels folder
is also not used, but may affect the generation.

### Screenshots

![WS000607](https://github.com/CleverRaven/Cataclysm-DDA/assets/143560102/c6f035ee-4d1f-43d5-8832-bfad3d5d9c61)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    追加 - Aftershock [aftershock]
]

**Comment by John-Candlebury** [comment]
I made several aftershock worlds with increased lake settings and I didn't notice anything out of the ordinary. I believe this just the usual result of specials having to fight each other for placement spots .

Heres a megalake spanning three different overmaps, which all of them placing islands and related specials:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5290912/a104f3de-7cb4-49ea-862f-f45c7a39e706)
Continuation of said lake in two more overamps, still with specials:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5290912/8937aa11-ec30-4f45-84ad-627d0b18ee9c)

Additionally theres nothing in ` \data\mods\Aftershock\maps\overmap_terrain` that should affect lake mapgen.

**Comment by CHCOOH** [comment]
When you say more lake settings, do you mean playing with the json file?
I'm sorry, but could you try it without playing with it, just a couple of times.
As far as I can tell from my stats this time, there is clearly an unusual difference between vanilla and AFS.
However, I can't rule out the possibility that this is a unique problem in my environment (and I have no knowledge of how that might be possible), so if you try it a couple of times under normal conditions and it still doesn't affect you, then I'll leave it at that.

**Comment by John-Candlebury** [comment]
Yeah I had a few empty lakes with normal settings, generally smaller ones that left much of their host over map with land.

I believe this due to the mod `overmap_specials` being prioritized over the vanilla ones, which can result in no slots being left to place content in lakes.  There's simply nothing in the entire aftershock directory that could be causing this interaction beyond and increased number of specials.

**Comment by CHCOOH** [comment]
I see that there is a quantitative limit to the placement of overmap_specials as well as the area.
When I was trying to identify the cause of this problem, I had also generated and tried worlds with only XEDRA, MoM, etc., but the problem only occurred when AFS was included.
So I guess I mistakenly thought AFS was the cause.
If the problem is caused by the quantity limit of map placement, it means that the same phenomenon can occur not only when AFS is added, but also when multiple mods are added, even if the number of mods added is small.
From now on, I will keep this information in mind when adding mods.

Thank you for the explanation and verification.

**Comment by Maleclypse** [comment]
Not an AFS problem. Closing.
