### ISSUE TITLE
[Magiclysm]Triffid vineweaver causes the car to be destroyed instantly.

### ISSUE THREAD

**Issue by CHCOOH** [CleverRaven/Cataclysm-DDA#68647]
### Describe the bug

(I apologize in advance for reporting what I don't know is a bug as a bug.)

I was driving past a triffid vineweaver and my car was destroyed by the Brambies they summoned.
It seems that this was due to the fact that the fragile parts inside the vehicle could not withstand the collision because of the terrain generated in the interior squares of the vehicle as well.

I wasn't sure if it was a bug or not, but decided to report it as it might be unexpected.

### Attach save file

N/A

### Steps to reproduce

Look at it when you try to drive by next to vineweaver.
If the speed is low, the car will be caught; if the speed is high, the car will be destroyed.

### Expected behavior

If a vehicle speeds up to rush past a triffid nest, it may cause an immediate and potentially fatal collision.
This is especially true if the seatbelt is broken.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    追加 - Magiclysm [magiclysm]
]

**Comment by Maleclypse** [comment]
For any future bug hunters this behaviour is intended.
