### ISSUE TITLE
Unjustified Power Loss in Foldable Solar Panels

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#68642]
### Is your feature request related to a problem? Please describe.

Currently "foldable solar panel" has only 66% epower output compared to the basic "solar panel" from which is made.
The "foldable" panel has the same area (and weight), is mounted the same way (on a vehicle frame) and the same solar cells (which **do** have the same efficiency), so any possible loss can occur only in additional wiring, but as the weight is the same, this is clearly not the case.

This issue have been discussed previously in https://github.com/CleverRaven/Cataclysm-DDA/pull/66478 (my previous unsuccessful attempt to fix the issue), so I invite everyone to participate in another round.

P.S. I consider comparison of in-game "foldable" solar panels with real-life pocket gadgets of the same *name* to be incorrect for reasons mentioned above.

### Solution you would like.

My proposal is to restore epower efficiency back to basic solar panel's level unless someone comes up with an estimation how much power can be lost in wiring needed to separate solar cells in a panel and connect them with hinges.

### Describe alternatives you have considered.

Alternatively, we can allow folding of  frame with basic solar panels and make "foldable solar panels" to be more in line with their real life implementations: small low power/weight (un-craftable?) pocket-size gadgets that must be simply dropped on the ground without any mounting and start acting as "battery chargers" for that tile.

**Comment by PatrikLundell** [comment]
Hinges etc. ought to take up some surface area, reducing the area available to the cells. Also, I would expect a foldable panel to be more rugged than a standard one to be able to withstand handling, and some of the ruggedization ought to come from a protective layer on top of the panel, reducing the amount of light reaching the cells.
The number of cells used for a foldable panel should probably be lower than for a regular one, given that the space they would occupy would not be taken up by the folding functionality.

**Comment by Alm999** [comment]
"Hinges etc. ought to take up some surface area, reducing the area available to the cells."
While this might be true, I don't think this can serve as an explanation. The fact that some appliance/vehicle_part "takes one tile" does not mean it takes **entire tile**. Otherwise a foldable bike frame (xl frame) would be the same size as a heavy-duty frame of an armored car, which is not very realistic.

"Also, I would expect a foldable panel to be more rugged than a standard one to be able to withstand handling, and some of the ruggedization ought to come from a protective layer on top of the panel, reducing the amount of light reaching the cells."
This is not the case. Additional "flimsiness" of a foldable solar panel is already accounted for via "durability" modifier of 0.5 in the [vehicle_parts.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicleparts/vehicle_parts.json) file (line 1768). So no, no extra protection is added.

"The number of cells used for a foldable panel should probably be lower than for a regular one, given that the space they would occupy would not be taken up by the folding functionality."
The problem is: a foldable solar panel incorporates *fully* basic solar panel (and can be disassembled to retrieve it), thus consists of the same 12 solar cells: [power_supplies.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/other/power_supplies.json) (line 43). And, as was stated above, additional space for hinges/frame shall not be an issue.

P.S. Defining the "longest_side" would be great.
