### ISSUE TITLE
The generated position of the roof of the cardboard house of the Refugee center is out of alignment.

### ISSUE THREAD

**Issue by CHCOOH** [CleverRaven/Cataclysm-DDA#68644]
### Describe the bug

After completing the cardboard man quest at the Refugee center to the end, a cardboard house will appear on the roof of the Refugee center, but its roof will be generated out of place.

### Attach save file

![WS000606](https://github.com/CleverRaven/Cataclysm-DDA/assets/143560102/279800f5-d521-4555-a04b-d97afdbb49c2)

### Steps to reproduce

Generate a new world and try to complete it in debug mode, etc.

### Expected behavior

Perhaps it was blown away by the wind.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    追加 - Aftershock [aftershock]
]

### Additional context

 DEBUG    : Unable to find and assign mission target evac_center_13_z2.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 258
 VERSION  : cfcc682

**Comment by watcherPlayer** [comment]
+1

**save:**
preliminary step before completing the quest
1. speak trader
2. speak Dino Daiv
[Magenta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12837190/Magenta-trimmed.tar.gz)

**Describe the bug:**
last step in chain quest Dino Daiv into refugee center, when placing a cardboard fort, an error appears and the roof appears at the level z0
error:

 DEBUG    : Unable to find and assign mission target evac_center_13_z2.

```
 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 258
 VERSION  : ab63507
```

![roof_up_level](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/633349a6-2bfa-4838-8bad-639b2340612a)

![roof](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/e2924721-a786-4da8-8050-28b847e87fbc)

**Versions and configuration**

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: ab63507 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by RenechCDDA** [comment]
Duplicate of #69193
