### ISSUE TITLE
Can't take down standing mirror?

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#68651]
### Describe the bug

There is a standing mirror in a mansion that I want to loot and bring back to base (so I can flex in front of it ofc). 

Usually with furniture we can either deconstruct it or examine it and select some option to "take it down". Then we can pick it up and throw it in the van - or carry it etc.

However no such option seems to exist for "standing mirror". Using the examine option only gives options to "examine self" or to change appearance. Should there be another option to undeploy the item? 

### Attach save file

n/a

### Steps to reproduce

Find standing mirror in some house. Try to loot it.

### Expected behavior

Should be able to undeploy or deconstruct standing mirror as with other furniture.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 33b7158 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by Karol1223** [comment]
I don't know if this can be considered a bug or not - because it's not anything unexpected or not working correctly - but that is indeed the case.

Nobody made the mirrors an item form that could be obtained from them and moved around. It's less of a bug and more of a "something nobody ever did". Keep in mind that being able to pick up and transport furniture is NOT the standard. Besides the "deployable" furniture such as deployable tables or braziers, this only applies to seating furniture or appliances.

**Comment by pwalsh0** [comment]
That's fair enough - it just seems like an anomaly compared to all the other furniture items.

Players may want to loot one of these mirrors to practice social skill.

**Comment by Karol1223** [comment]
Yeah of course, it's a valid feature request. In an ideal world we should be able to transport most furniture that's not fused to the floor. I'm just saying that this is something that needs work rather than is broken.

**Comment by PatrikLundell** [comment]
Further comment on @Karol1223's comments: the report ought to have been filed as a feature request rather than bug report, in case that wasn't clear already.

It is indeed a reasonable added functionality.

**Comment by pwalsh0** [comment]
Is it possible to edit the labels? I can't see how. If not then please just close this.

**Comment by PatrikLundell** [comment]
Sorry, no, I don't think it's possible to change the type of the report, so it's more of a note for future submissions.

**Comment by Karol1223** [comment]
It should be possible to manually change labels for some repo members. Not the description but eh. I'll try to bring it to someone's attention on discord if we could switch the labels.

**Comment by PatrikLundell** [comment]
It's possible to change the description line for the poster: To the right of the title line there is an "Edit" button just beside the "New Issue" one (took me quite some time to find that one, originally, and it doesn't help that it's different from the "..." edit indicator for the main text).

That doesn't allow a change of classification, though, so it doesn't help here.
