### ISSUE TITLE
Infrastructure: new class Crafter; Character >: Crafter >: (NPC, Avatar)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#68657]
### Is your feature request related to a problem? Please describe.

I cannot refer to an NPC and the avatar as the same in crafting. More specifically: I cannot make a list of NPCs and the avatar and call functions such as `is_ally` or 
```cpp
recipe_subset Character::get_available_recipes( const inventory &crafting_inv,
        const std::vector<npc *> *helpers )
```

### Usecase
Implementing #68183

First, I make a list, which I do like this:
```cpp
std::vector<Character *> Character::get_crafting_group() const
{
    // GET NPCs
    std::vector<npc *> npcs = g->get_npcs_if( [this]( const npc & guy ) {
        // NPCs can help craft if awake, taking orders, within pickup range and have clear path
        return guy.is_ally( *this )
               && rl_dist( guy.pos(), pos() ) < PICKUP_RANGE
               && get_map().clear_path( pos(), guy.pos(), PICKUP_RANGE, 1, 100 );
    } );

    // RESERVE
    std::vector<Character *> ret;
    ret.reserve( npcs.size() + 1 );  // +1 for player
    for( npc *np : npcs ) {
        ret.emplace_back( static_cast<Character *>( np ) );
    }

    // CHECK THAT CHARACTER IS NPC OR AVATAR, SO NOT A RANDOM MONSTER
    // This can be called by avatar or NPC
    bool friendly_player = false;
    if( is_npc() ) {
        friendly_player = as_npc()->is_player_ally();
    } else if( is_avatar() ) {
        friendly_player = true;
    } else {
        debugmsg( "get_crafting_group called by somebody else than avatar or npc." );
    }

    // GET AVATAR
    avatar &avat = get_avatar();
    if( friendly_player
        && rl_dist( avat.pos(), pos() ) < PICKUP_RANGE
        && get_map().clear_path( pos(), avat.pos(), PICKUP_RANGE, 1, 100 )
      ) {
        ret.emplace_back( static_cast<Character *>( &get_avatar() ) );
    }
    return ret;
}
```
But I would like to do this:
```cpp
std::vector<Crafter *> Crafter::get_crafting_group() const
{
    return g->get_crafters_if( [this]( const npc & guy ) {
        // NPCs can help craft if awake, taking orders, within pickup range and have clear path
        return guy.is_ally( *this )
               && rl_dist( guy.pos(), pos() ) < PICKUP_RANGE
               && get_map().clear_path( pos(), guy.pos(), PICKUP_RANGE, 1, 100 );
    } );
}
```

And I wouldn't have to duplicate original code like this:
```cpp
        bool has_recipe( const recipe *r, const inventory &crafting_inv,
                         const std::vector<npc *> &helpers ) const;
        recipe_subset get_available_recipes( const inventory &crafting_inv,
                                             const std::vector<npc *> *helpers = nullptr ) const;
```
Adding these (and their implementation):
```cpp
        bool has_recipe( const recipe *r, const inventory &crafting_inv,
                         const std::vector<Character *> &helpers ) const;
        recipe_subset get_available_recipes( const inventory &crafting_inv,
                                             const std::vector<Character *> *helpers = nullptr ) const;
```

### Solution you would like.

New class `Crafter` that is a subtype of `Crafter` and supertype of `NPC` and `Avatar`.

This class would implement commonalities between NPC and Avatar so that crafting code doesn't care in most cases whether we ask about NPC or Avatar. (Read as: for all cases of certain methods, **not** some cases for some methods).

I would like this also to include friendly checks between persons. So with a list of Crafters, you can pick anyone and get their allies. Now such a list would have to be `Character` (supertype of NPC and Avatar), who doesn't implement ally code, so we have to call `if (is_npc) {...}, else if (is_avatar) {...} else {dbg("called by somebody else than Crafter or Avatar"); return false}`.

### Describe alternatives you have considered.

 Don't call it `Crafter`, call it `Person` to better reflect that it can be an ally of others. But right now, I would use it crafting code, so Crafter might be better. 

### Additional context

Let's say I implement this. Is it likely to be merged? NPC, Avatar, and Character would all look and behave the same. There would be just another class in between people can use when they don't care if it is Avatar or NPC but need Person's methods.

**Comment by mqrause** [comment]
I'm not sure what your goal is with an extra class? We already have `Character` for implementing commonalities between `npc` and `avatar`.

**Comment by ZhilkinSerg** [comment]
`Creature > Character -> Crafter -> avatar/NPC` does not look like something that makes much sense.

**Comment by ZhilkinSerg** [comment]
You probably just need to move functions like `is_ally`, `is_player_ally`, `is_friendly` and such up to `Character` class.

**Comment by Brambor** [comment]
> You probably just need to move functions like `is_ally`, `is_player_ally`, `is_friendly` and such up to `Character` class.

I will look into that
