### ISSUE TITLE
3d vision: You have to look around `;` at different levels explicitly to be later able to look at places you should have seen.

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#68659]
### Describe the bug

^

### Attach save file

N/A

### Steps to reproduce

0. Have a 3D vision on
1. Make a new character in evac shelter
2. open a window to see outside
3. close the window
4. look around `;`
5. look one floor up `<`
6. Observe: there is nothing on that level
7. cancel look around
8. open window
9. look around
10. look one floor up `<`
11. Observe: there is something visible on that level

### Expected behavior

You don't have to look around `;` explicitly to be later able to look at places you should have seen before.

Failing the above, players are incentivised to `look around` up and down (or simply `;<<<<>>>>>>>>`) whenever possible to get the most explored map possible.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.C-80146-g95bd71b9bd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by jtmusky** [comment]
This is also seems to be true with peeking while crouch if behind furniture/under window. Example, peeking while crouch to "walking" using the `.` direction requires the `<>` toggle.

**Comment by Brambor** [comment]
confirmed in #77112 and by the comment from @ jtmusky 

Now I have the power to add the label :)

**Comment by Brambor** [comment]
It _might_ be ok. Role-playing interpretation: If you didn't look at rooftops, you don't remember them. Still, this would be a nice Quality of Life feature (removing grind for optimal play).
