### ISSUE TITLE
"Play" and "Cull" options for pets share a hotkey

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#68655]
### Describe the bug

When interacting with a pet, the option for Play and the option for Cull are not only disconcertingly adjacent, they actually share a hotkey, which seems to trigger the Cull option when used.

### Attach save file

[Terra Alta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12905426/Terra.Alta-trimmed.tar.gz)

### Steps to reproduce

1: Interact with a pet
2: Note how the two options share a hotkey. Pressing the hotkey triggers the Cull option.

### Expected behavior

The cull option and play option should not share a hotkey. Ideally, they should also not be adjacent, as someone who plays with their pet regularly is very likely to fat-finger it eventually and blow through the confirmation prompt with muscle memory.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19789267/7687190b-8251-443b-b61f-4460b25356a8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: b7d01dd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by ZhilkinSerg** [comment]
Can be easily fixed by changing hotkey in either of those two:

https://github.com/CleverRaven/Cataclysm-DDA/blob/95bd71b9bd2de2c4d00e0a1d7c890ac0c7033fd9/src/monexamine.cpp#L662-L667
