### ISSUE TITLE
The generation of ceilings for some terrains, such as fema camp, does not work well.

### ISSUE THREAD

**Issue by CHCOOH** [CleverRaven/Cataclysm-DDA#68650]
### Describe the bug

It seems that fema camp does not generate ceilings unless you stand on the same level.
Also, if the 3D view is turned on and the viewpoint is moved, it does not seem to work even if you stand on the same level.

I think the same phenomenon was observed in the building-type laboratory, but I could not verify this because I could not find the problem with the debugging function, although I tried my best to find it.

### Attach save file

N/A

### Steps to reproduce

Try going to fema camp.

### Expected behavior

If a ceiling is added, it will not be possible to look inside by shifting the viewpoint.

### Screenshots

![WS000611](https://github.com/CleverRaven/Cataclysm-DDA/assets/143560102/9f691801-8792-4eb4-afdb-b894b28541bc)

After peeking through the viewpoint shift, I climbed to the same level after save and load.

![WS000612](https://github.com/CleverRaven/Cataclysm-DDA/assets/143560102/a1538f96-0279-4abc-97f6-46d4bb1c3aeb)
There is no ceiling where the lower level is visible.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    追加 - Magiclysm [magiclysm]
]

**Comment by GuardianDll** [comment]
#65523
