### ISSUE TITLE
Unable to find and assign mission target bakery

### ISSUE THREAD

**Issue by Lord-Helmchen** [CleverRaven/Cataclysm-DDA#68662]
### Describe the bug

Talked to Dana Nunez, was happy to see a new mission that wasn't there when I last left cdda a few months ago, but:
 DEBUG    : Unable to find and assign mission target bakery.

 FUNCTION : std::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&, dialogue&)
 FILE     : src/mission_util.cpp
 LINE     : 258
 VERSION  : 33b7158

Went back to last save via Alt-F4 and prepared a save directly before tlking to Dana.

### Attach save file

[New Fairfield-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12907867/New.Fairfield-trimmed.tar.gz)

### Steps to reproduce

Talk to Dana, then agree to fetch her centenial sourdough.

### Expected behavior

A bakery is found/placed on the map so the mission has a target location and can be done.

### Versions and configuration

Windows
Experimetal 2023-10-14-0631
Tiles
English

active mods:
dda
no_npc_food
personal_portal_storms
no_fungal_growth
blazeindustries
speedydex
StatsThroughSkills
magiclysm

**Comment by Rabadash94** [comment]
Something similar has happened to me before with another mission. I got that error, but the place was revealed on the overmap although it was not marked as a mission target.
