### ISSUE TITLE
NPCs persist for several turns after receiving fatal damage

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68674]
### Describe the bug

Upon reducing an NPC to ----- torso health, they will continue moving and attacking for several turns afterword with no way to finish them off besides waiting. Additional damage to the torso will have no effect. Loading a save with NPCs at 0 health will cause them to be dead.

### Attach save file

N/A

### Steps to reproduce

1. Shoot NPC until their torso is at -----, verify in debug that they have 0 torso hp.
2. Watch them continue to move and attack as if they weren't dead for several turns.

### Expected behavior

NPCs reduced to 0 torso/head health should die, and not continue being indestructible threats until they finally realize they were supposed to die.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/4a656d67-c830-4cbb-8adc-f7ffdf90970c)
I reloaded a save to test against a friendly NPC, but it also happens with all hostile NPCs like bandits.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by RenechCDDA** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/1c8b34be-35a0-4537-ab54-e91004a28eaf)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/b42a4f29-718e-4ae6-b623-0f4181b825dc)

>Watch them continue to move and attack as if they weren't dead for several turns.

They seem to be dying on the very next turn they get, do you have a scenario where this occurs?

**Comment by gisaku33** [comment]
I can't make a save for it because loading a save with them at 0hp will cause them to die, but I've had them persist for over 10 turns moving/attacking while I waited in place. Went to a debug world, shot an NPC with a .50 cal in the torso, here they are hanging on and attacking.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/4cdb3643-363d-4e20-b7f9-fd53417d7ea2)

**Comment by RenechCDDA** [comment]
I was able to get them to survive several turns after another try, so this is confirmed.

**Comment by RenechCDDA** [comment]
Resolved by #68874
