### ISSUE TITLE
[Xedra Evolved] Vancian bills remain as chargeless items after ripping them

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68677]
### Describe the bug

Vancian bills are described as being torn to activate them, but after using them to cast Rip they remain as items. Attempting to use them again will result in a message about it not having enough charges, but the name remains the same and charges aren't listed anywhere.

### Attach save file

N/A

### Steps to reproduce

1. Use a Vancian bill.
2. See that it remains, attempt to use it again to confirm it doesn't have enough charges.

### Expected behavior

Vancian bills should be destroyed after use, or otherwise show that they are spent and now useless.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Maleclypse** [comment]
OK first solution that comes to mind is to add an eoc as an additional effect that removes the vancian bill from existence?  I wonder how that would work with multiple bills though?   Maybe could do the same thing to some of the other one use items?

**Comment by Maleclypse** [comment]
Vancian bills removed.  If I remake them as something else this still won't be an issue anymore.
