### ISSUE TITLE
Rubik should not mention heavy thuds

### ISSUE THREAD

**Issue by superyuuki** [CleverRaven/Cataclysm-DDA#68689]
### Is your feature request related to a problem? Please describe.

Every time i go for surgery in the Exodii castle my dialogue gets flooded with Rubik asking about heavy thuds.  Since I'm guessing those heavy thuds are the movement of the Exodii quadrupeds I don't see any reason why he would be confused by the source of them.

### Solution you would like.

Rubik should not comment on heavy thuds

### Describe alternatives you have considered.

- The exodii quadrupeds should be 100% silent
- Rubik should comment on the heavy thuds in anglic

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92664603/b70c16c9-0c39-4965-a47b-e289c88df70b)

**Comment by PGR-14** [comment]
Yeah, everything should have a Anglic version for when he's alerted (Maybe through a mutation?)
