### ISSUE TITLE
More Anvils, Sledgehammer Anvils

### ISSUE THREAD

**Issue by jorganmir** [CleverRaven/Cataclysm-DDA#68680]
### Is your feature request related to a problem? Please describe.

It is rather annoying how few ways to make/acquire an anvil there are.  Railroad tracks are probably not the only way, and casting bronze anvils as it is right now relies on  "tin" plates being oddly common in the modern day.

### Solution you would like.

Historical anvils are not that big. A hammer simply does not need to be that much bigger than the hammer hitting it to function. More mass has been preferred, but that's because you can make a high inertia high mass object in a factory, you can't make the mounting for that object on an assembly line.
Small Anvil
https://www.youtube.com/watch?app=desktop&v=tsixmP7KOLU
Makeshift Plate on a log
https://www.youtube.com/watch?v=KPoSJ8kxoCs
Hammer head anvil
https://www.iforgeiron.com/topic/61298-sledgehammer-as-an-anvil/

Norse anvils were not much bigger than some hammer heads(and were not made of excellent steel).  I think sledgehammer anvils would serve fine as anvils.  A bit of metal on a log is an anvil. I'm not sure how anvil quality is determined - is there a determined array of hardy/pritchel holes, a horn, a step, more than one horn, minimum inertia, minimum metal properties? - but making an anvil is not that complicated to get something that can work. If medieval, renaissance, and post enlightenment smiths made metal on anvils that had no horns or pritchel/hardy holes, no steps, then it should be fairly simply to make an anvil that's good enough to craft with, anvil 3

[1700's mousehole anvil](https://i.redd.it/6yt8l0ydii4b1.jpg)
[1300's anvil](https://www.anvilfire.com/anvils/donated_021.php)

If simply using a lump of steel on a log(or other suitable mass) is not enough, than at least hammer heads should be usable to make anvils.

**Comment by Drew4484** [comment]
> See the comments on #64595 and #68386. Using a smaller/lighter anvil is possible but is significantly harder/impossible for some crafts, a stake anvil is not going to make form fitting plate armor. Nothing precludes you from adding additional low-tier anvils or other ways to craft anvils in general.
