### ISSUE TITLE
"Your body tries to mutate, but it lacks a primer to do so and only contorts for a moment." is sometimes a lie

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#68687]
### Describe the bug

This message will appear sometimes to inform you of why you failed to mutate.  However I have tested this thoroughly and now have proof that the message is firing in ways that don't make sense.

### Attach save file

[Test Xedra Sylph-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12911090/Test.Xedra.Sylph-trimmed.tar.gz)

### Steps to reproduce

Consume massive amounts of primer and mutagen,  eventually you will see the message `Your body tries to mutate, but it lacks a primer to do so and only contorts for a moment.` look at your primer vitamins and see they are plentiful.   As shown in the picture below, I took a boatload of primer containing items, then immediately received the message and then without doing anything else but waiting mutated.

### Expected behavior

Message not to appear when I'm not lacking in primer.

### Screenshots

![primer is plentiful](https://github.com/CleverRaven/Cataclysm-DDA/assets/54345792/c09d085f-fe35-4306-9fee-333df32a2034)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 0.G-4555-g0c5cfadf57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks]
]

**Comment by lispcoc** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13540013/58f075c3-bea1-4fd9-88e8-2336356deda2)
Mutations caused by primer are randomly determined to be good or bad. I think the error message is probably because there are no bad candidates when bad mutation is selected.

**Comment by Maleclypse** [comment]
Good mutation if no bad remaining seems best to me.
