### ISSUE TITLE
Add a seperation line above ASCII art pictures

### ISSUE THREAD

**Issue by Lumi-Virtual** [CleverRaven/Cataclysm-DDA#68682]
### Is your feature request related to a problem? Please describe.

It's sometimes ambiguous when viewing an item where the final info section ends and the ASCII picture begins, as there is no separator or line break between them.

### Solution you would like.

There should be a separation line in item menus between the ASCII art section and the previous section that only shows up if ASCII art is enabled and there is art for that item.

**Comment by GuardianDll** [comment]
![изображение_2023-10-15_223701991](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/a0100aac-4d38-47cb-a233-1aa32282c87c)
