### ISSUE TITLE
[Mind Over Matter] Portal storm awakening failures for already awakened paths

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68692]
### Is your feature request related to a problem? Please describe.

When you go out in portal storms, you may randomly attempt an awakening, which will automatically fail if you already have that awakening. As you become a more powerful psychic and get more awakenings, portal storms actually become more debilitating due to practically guaranteeing a failed awakening of some type.

### Solution you would like.

Failure penalties for portal storm awakenings on paths you already have should be reduced or even removed based on how powerful you are on that path. Inexperienced pyrokinetics could still get overwhelmed by fevers, but one with significant enough ability should be able to resist it to at least some degree. Telekinetics capable of levitation should be able to resist being crushed by gravity, etc.

**Comment by Standing-Storm** [comment]
> As you become a more powerful psychic and get more awakenings, portal storms actually become more debilitating due to practically guaranteeing a failed awakening of some type.

This is actually part of the design goals that being a more powerful psion can make something things _more_ risky, not less--the force of a portal storm is so much more powerful than a single human mind that uncontrolled exposure gets more dangerous the more things can go wrong. A more powerful psion has scope for much greater harm if their powers go out of control. 

(and from an out-of-character balance perspective, it should be more dangerous and difficulty to awaken further paths when you already have a few to prevent character power snowballing out of control any  more than it already does)

**Comment by lapis413** [comment]
It will also eventually stop being a problem, having all 7 schools naturally means you have clairsentience, and the starter telepathic shield power can block out the failed awakenings for practically no cost (it provides a flag that blocks the awakenings, along with several other nasty portal storm tricks)
