### ISSUE TITLE
Mikayla wants 2 "bags" of commercial fertilizer, but doesn't recognize 2 canvas sacks of it

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#68715]
### Describe the bug

I brought two canvas sacks of fertilizer to her, but it wasn't recognized as being present.

### Attach save file

[West Kingston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12926733/West.Kingston-trimmed.tar.gz)

### Steps to reproduce

1. Load save and walk over to Mikayla.
2. Talk to her.
3. See that you can only respond that you don't have the fertilizer.
4. Check inventory to see there are two fertilizer in there (since the stupid nesting "logic" placed one bag inside the other I dropped the fertilizer and picked it up again, which didn't help, of course).
5. File bug report (this is the report, so you don't need to do that...)

### Expected behavior

A. The quest would be fulfilled; or.
B. One bag of fertilizer would contain enough fertilizer to count as one bag of fertilizer for quest fulfillment purposes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4542-g6ef93bccde-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

I suspect the quest was screwed up by charge removal, so one bag of fertilizer should have contained more than a single fertilizer item. This bungling might be caused either by the change itself not updating fertilizer bags (and a lot of other stuff, like cement reported in another bug report), or by migration, although I think at least some of my bags, and possibly all of them, would have been generated after the change was made.

**Comment by RenechCDDA** [comment]
She wants 120 units, that should just be made clearer in the information she gives you. (It seems that 120 units can fit inside of one sack, though this isn't related to the charges change. Kind of weird.)

https://github.com/CleverRaven/Cataclysm-DDA/blob/078a7b43be36c11f2431bf52f5f00d2d41c9a53a/data/json/npcs/refugee_center/surface_visitors/NPC_arsonist.json#L196-L198

Easy clarification would be to change the mission offer text to explicitly say `120 units of commercial fertilizer` or so (JSON-only change).

A bit nicer of a change (C++ required) would be a new special phrase replacement, like `<topic_item>` which grabs the amount required for the mission. It would probably be a bit more complicated than a single if-else statement as it needs to identify the topic is in fact part of the mission offer dialogue and then schlep through *what kind of mission it is*.

**Comment by PatrikLundell** [comment]
If it wasn't caused by the charge removal it must have been caused by something else, as that mission didn't require the collection of 120 bags in the past, but the mentioned amount worked just fine.

Given that it's commercial fertilizer in a sack (rather than something in a plastic bag for hobbyist use) I would expect the bag was supposed to actually contain 60 units when found in a store (might potentially be less if found on a farm where some of it may have been used up, although I wouldn't be surprised if an opened bag is an empty bag in that setting, with any leftovers being in the fertilizer machinery rather than a partial bag).

**Comment by RenechCDDA** [comment]
Yes, the most common spawn for commercial fertilizer was 60 units (previously 60 charges). That number may have changed after the charge removal and related item group fixes, so all the more reason for the amount to be explicitly stated and not refer to item group behaviors that may or may not change independent of the mission.
