### ISSUE TITLE
i should not be able to milk a horse named steve......

### ISSUE THREAD

**Issue by yamil-90** [CleverRaven/Cataclysm-DDA#68718]
### Describe the bug

i got steve as a reward from a quest from the isherwoods, saw that the option to milk the horse was available and got 0.5L of milk (?) so..... yeah that just happened.... i think that it is kind of weird to get milk from a horse named steve for obvious reasons

### Attach save file

N/A

### Steps to reproduce

get steve the horse
milk it
drink the milk (optional)  

### Expected behavior

i should not be able to get milk from a horse, if you want to argue that the horse is female and you can technically milk it at least give it another name like pumpkin or something

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.3 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 11f7faf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Maleclypse** [comment]
All animals are schrodinger animals that change gender as needed.  Like Velociraptors in whatever that dinosaur movie was.  Rename the animal if it bugs you.
