### ISSUE TITLE
Problem with mill wild rice

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#68724]
### Describe the bug

If you mill wild rice in a windmill the following debug message pops up

```
DEBUG    : calc_rot_while_processing called on non smoking item: dry wild rice (fresh)

FUNCTION : calc_rot_while_processing
FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
LINE     : 7969
VERSION  : 356bfe5
```

### Attach save file

None

### Steps to reproduce

1. put wild rice
1. start mill
1. wait end
1. get message DEBUG

### Expected behavior

no message?...

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 356bfe5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by Bobtron** [comment]
Can you attach a save file, or add more details on how to reproduce? Is the mill you're using a `Wind mill` or another structure/tool? I'm unable to reproduce this specific bug, but I noticed another bug popup, where the amount of milled products you get was exponential compared to the inputs you gave. 10 dry wild rice milled got 110 wheat-free flour, 20 dry wild rice got 420 wheat-free flour, 100 dry wild rice got enough wheat-free flour to fill several tiles, with each tile having 4096 wheat-free flour.

**Comment by Bobtron** [comment]
Snippet of code here mentions rot checks regarding milling, in iexamine.cpp `mill_activate`

```
for( item &it : here.i_at( examp ) ) {
        if( it.type->milling_data ) {
            // Do one final rot check before milling, then apply the PROCESSING flag to prevent further checks.
            it.process_temperature_rot( 1, examp, get_map(), nullptr );
            it.set_flag( flag_PROCESSING );
        }
    }
```

**Comment by watcherPlayer** [comment]
pre save

[Magenta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13181083/Magenta-trimmed.tar.gz)

1. put wild rice into wind mill (in inventory)
1. start mill
1. wait end
1. get message DEBUG

message only with wild rice

```
 DEBUG    : calc_rot_while_processing called on non smoking item: dry wild rice (свежее)

 FUNCTION : calc_rot_while_processing
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 7971
 VERSION  : 3468373
```
