### ISSUE TITLE
New characters start with martial arts style set to "Force unarmed"

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#68722]
### Describe the bug

Every time I create a new character, they start with their martial arts style set to "Force unarmed". This caused a lot of confusion and a few deaths before I figured out what was going on. 

### Attach save file

[Leicester-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12937616/Leicester-trimmed.tar.gz)

This really shouldn't matter, but fwiw here's a totally vanilla character on a totally vanilla world, who started set to Force unarmed

### Steps to reproduce

1. Create character
2. Check their martial arts style

### Expected behavior

Characters start set to "no style" (or an actual style that they started with)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 078a7b4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
/confirmed 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/4e9d2c46-5f6d-4f08-afb6-323b49a9bfcb)
may #68548 cause it?
