### ISSUE TITLE
Catalytic Cracking Reactor not recognizing grid power.

### ISSUE THREAD

**Issue by johannhawk** [CleverRaven/Cataclysm-DDA#68725]
### Describe the bug

The emplaced Catalytic Cracking Reactor does not seem to work despite being fully charged. It provides the Extraction quality, but fails to recognize power even in a stationary grid.

### Attach save file

N/A

### Steps to reproduce

1) Find a Catalytic Reactor, naturally spawning
2) Deconstruct it, then place it back down somewhere else
3) Connect it to a grid
4) Try to craft kerosene

### Expected behavior

The Catalytic Reactor should be able to accept power from a stationary grid. However, it always fails to recognize when it has enough charges, even when the grid has enough power supply.

### Screenshots

![cdda 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/12373839/17112894-822e-4d27-85ad-744ec2708dfb)

![cdda 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/12373839/1c7014f4-2c96-416d-a368-350069084f5a)

### Versions and configuration

- OS: Windows 10
- Version: 078a7b4 (tiles)
- Graphics: Tiles
- Ingame Language: English
- Mods Loaded: None beyond debug options

### Additional context

[Lake_Delton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12977734/Lake_Delton-trimmed.tar.gz)

**Comment by Maleclypse** [comment]
Can you add a save file to this report?  you can generate it from the debug menu

**Comment by johannhawk** [comment]
> Can you add a save file to this report? you can generate it from the debug menu

Appended it to the end of the report.
Apologies for any inconveniences as i am relaying the bug report from a friend that didn't have a github account and asked me specifically to make it.

**Comment by PatrikLundell** [comment]
I don't know how important it is, but there is a section for a saved game, so it's easier to find when placed there. I would consider this to be a reminder for your next report.

**Comment by atgave** [comment]
it's just a typo in data/json/recipes/chem/fuel.json where it says "catalytic_cracking_reactor" instead of "catalytic_cracking_reactor_tool"
