### ISSUE TITLE
Weapon/Item Degradation & Weapon mods

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#68720]
### Is your feature request related to a problem? Please describe.

Whenever you see a damaged item, it's always just... damaged. Not in any particular way, whether it's been used a bit, hit by an explosion, or was worn on a zombie, it's always the same.

W/ weapons, you can't really add stuff to them (excepting guns), & I'd like to change that

### Solution you would like.

**Item Damage:**
Adding some flags/faults for damaged items w/ various fixes, for instance:

- Dull: For "sharp" weapons (Like axes or knifes), would decrease cutting damage quite a bit, easily fixed w/ metal fileset (or something w/ similar filing qualities).
- Dented: For stuff like aluminum baseball bats & pipes, decrease damage & weapon swing, fixed w/ a propane torch or something? Would be pretty hard to do.
- Rotting: Some wood stuff would eventually rot (if in a humid place/outdoors), decreases durability, damage (If what's used to hit is wood, like a baseball bat), & swing speed (If it has a wooden handle).

You could add a lot more if you wanted too, but I can't think of a ton. Maybe you could add some preventative measures for stuff like rot? Some items would spawn w/ these faults, & anything made w/ these faults would be faulty as well (Like a wood axe using a rotting plank as one of the components).
________________________________________________________________________________________________________________________________________
**Weapon Mods:**
Here's some ideas for some weapon mods:

- Duct tape: Put on the handle, gives you a better swing & grip. Pretty simple.
- Rubber Grip: Melt some rubber or something, gives you a much better swing & grip, as well as making it non-conductive, but irremovable.
- Strap: Kind of like the Shoulder Strap, but for weapons.
- Clip: For small weapons (like a hammer), makes putting it on a belt less costly (Acts like it's smaller, so the belt holds more | outside instead of inside the belt).
- Stock bandolier: (Mainly for shotguns, but you could put it on a rifle or crossbow) You can reload the little bandolier (Not as a magazine), & when you reload the gun, it reloads much faster (Quick note, this is mainly for guns w/out magazines like the 6-Round shotgun).

### Describe alternatives you have considered.

Not doing it.

**Comment by GuardianDll** [comment]
Item Damage: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/5d5bf189-b02f-4ec2-a7b7-fab4e5cb6597)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/64dba457-d686-495c-8cd1-00cf99adc06a)

Weapon Mods:
<https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions>, `“Enhancing” or “modding” melee weapons` section

**Comment by PGR-14** [comment]
Alright, didn't read that, sorry.
Also, what's that "Scratched"/"Shredded" stuff from?

**Comment by GuardianDll** [comment]
From the material, each material has defined set of verbs, applied when the item is damaged - it's just no one used it before because it was the opposite setting to symbol depiction, but recently the option to have both at once was added

**Comment by PGR-14** [comment]
I kind of meant actual things from it, more like "Defects" instead of "Damaged"

**Comment by GuardianDll** [comment]
Fault system is a way to go then

**Comment by PGR-14** [comment]
That's what I meant, sorry for the confusion

**Comment by kevingranade** [comment]
Weapon faults exist, we don't need issues saying "please make this kind of content", we need details of how to make that content work.
