### ISSUE TITLE
DEBUG    : invalid overmap special id "house_09"

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#68737]
### Describe the bug

`DEBUG    : invalid overmap special id "house_09"
`
Started getting it on an existing save right after updating a few minutes ago.

### Attach save file

[Symsonia-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12982687/Symsonia-trimmed.tar.gz)

### Steps to reproduce

Load up the save. Also happens when you go to the overland map and move around.

### Expected behavior

No error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: ed2a948 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

```
 DEBUG    : invalid overmap special id "house_09"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 478
 VERSION  : ed2a948
```

**Comment by ZhilkinSerg** [comment]
Add `package_bionic_professions` to your world mod list (see https://github.com/CleverRaven/Cataclysm-DDA/pull/68668).

**Comment by misterprimus** [comment]
> Add `package_bionic_professions` to your world mod list (see #68668).

To an existing save/world? How?

**Comment by ZhilkinSerg** [comment]
Edit `mods.json` in savegame folder.

**Comment by PatrikLundell** [comment]
That sounds like a weird migration requirement. If the thingie was moved to a mod the thingie should still remain as an (obsolete) unused definition so upgrading to a newer experimental doesn't break migrated saves.

**Comment by ZhilkinSerg** [comment]
I don't think we have that type of migration.

**Comment by misterprimus** [comment]
> package_bionic_professions

Like this?
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45959491/9195ccb2-9368-4787-9880-c0446eed43dd)

**Comment by PatrikLundell** [comment]
@Maleclypse : Regarding #68886 (which you locked, forcing me to try to find some other way to respond, which ended up being this crappy way):
I did not read the full article as the beginning showed what it was about, and my criticism wasn't based on those grounds, but rather on exactly what I said, no more, no less, although you seem to have read ulterior motives into my comments.

Over and out.
