### ISSUE TITLE
Craftable Denim Sheets, Vests, Jackets and Armoured Denim Vests and Jackets

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#68731]
### Is your feature request related to a problem? Please describe.

Denim is unreasonably un-craftable in mainline, being just an alternate cotton weave compared to regular cotton, originally made in its semi modern version in the 1600's in France. To add to this, Denim Jackets and Denim Vests (new addition) should be made craftable, and Armored Versions of Each.

### Solution you would like.

Add a way to craft denim sheets
Add Denim Vests as a item, and a crafting recipe
Add a crafting recipe for Denim Jackets
Add both Armored Denim Vests and Jackets with their own crafting recipes, for parity with leather counterparts

**Comment by Alm999** [comment]
I've not played the game for quite a while, but back in July denim as a material was pretty much useless. Having at least some craftable "armor" (even if it is nothing to write home about) is sure welcome, IMO.

**Comment by Kantonine** [comment]
> I've not played the game for quite a while, but back in July denim as a material was pretty much useless. Having at least some craftable "armor" (even if it is nothing to write home about) is sure welcome, IMO.

Sure is! Denim really ends up being Cotton Mk.2 in my eyes, more breathable than canvas for similar protection, even if water and wind resistance is sacrificed
