### ISSUE TITLE
Scrap armor rework

### ISSUE THREAD

**Issue by G0BL1N** [CleverRaven/Cataclysm-DDA#68743]
### Is your feature request related to a problem? Please describe.

I've discussed it in Discord around a year ago, and just wanted to know if this is still agreed upon. At that time, discussion in Discord mostly leaned towards completely removing it.
Scrap armor has a weird crafting recipe, being made only of random scrap and some ropes/patches. It is borderline unimaginable to be able to craft some kind of protective equipment from randomly shaped lumps of metal and some cloth using only a tool with hammering quality of 1. Furthermore, some parts of it are completely unbalanced. For example, scrap boots have a description of being "uncomfortable", but actually have encumbrance of only 3/6, which is, like, really weird.
Most of all - the "proper" scrap armor, sheet metal armor, was already added to the game by @Aerin-of-the-Toast, which resembles around the same idea - making makeshift armor with random metal sheets and other junk, but is not nonsense like this one.

### Solution you would like.

Scrap armor removal

### Describe alternatives you have considered.

Alternative would be to rework scrap armor, balancing it around some other idea, like gluing scraps of metal to clothes, or moving it to the outer layer, things like this.
Then again, if we look at it from a realistic point of view, such armor would be really uncomfortable and really fragile, so it raises a question - is it worth putting the work into items that no one would actually use? If someone's willing to do it (definitely not me), it might be better, because more content = always better, and it avoids removing items from the game which would break some saves.
If it's decided to leave it in game, at the least, encumbrance of scrap boots, IMO, **_must_** be much, much higher, probably to the point of them not even being worth crafting. Values of other pieces of scrap armor should be also looked into.

### Additional context

Just wanted to get official confirmation that this is still an issue and have it here. 
If it still makes sense to remove it, I will probably finally put my time (now that I have it) into doing it.

**Comment by ADekema** [comment]
I always imagined scrap armour as some kind of lamellar. Random bits of metal bashed into flatish pieces and strung to eachother. You could rework scrap armour into desperation lamellar quite easely by:

1. Remove the cotton patches from the recipe.
2. Add the need for a drilling tool.
3. Restrict metal components to scrap metal only.
4. Increase the amount of thread/string required.
5. Remove the layer of cotton and cotton material from all of the scrap armour pieces.
6. Reduce the coverage to something like 75% becease it should be full of holes.
7. Increase crafting time to account for all of the drilling.

**Comment by G0BL1N** [comment]
1. Wouldn't it be too close to the already existing sheet metal armor? Which is basically what you're describing - makeshift lamellar made by drilling holes in metal parts and tying them together with thread. The only difference between it and the variant of scrap armor you're proposing would be materials, and metal sheets aren't much harder to come by than scrap.
2. In addition to this, IMO, it also doesn't make sense to have it autolearnable at fabrication 3 compared to fabrication 4 of sheet metal armor, because metal sheets are easier to work with than random scrap, not harder.
3. And, again, honestly, I don't see how it would be even possible. Scrap isn't "flat-ish", it's, like, completely random pieces of metal, and I'm not sure hammering would be much of a help. Cold hammering steel ain't easy - try to flatten a screw with a hammer. The only thing that justifies it is that we already have recipes in game that imply cold hammering scrap into flat pieces - like scrap sword, for example. But it itself begs for a rework involving small metal sheet(s). Adding to this, it's already **a ton** of work to make lamellar from flat and thin metal sheets. Chest guard alone takes around a hundred lamellae with several holes in each one - now imagine that with scrap. 
If someone could find a design of some kind of armor even remotely looking like it's made by cold hammering literal random scrap without involving flat metal sheets it would be greatly appreciated, and maybe we can work from there. But, taking all points into account, I personally don't see a situation in which it would be preferable to craft it over sheet metal armor. It would take more time, more skill, and you would end up with a much worse result anyway.

**Comment by CHCOOH** [comment]
This is not really relevant, and not in a "so I want to keep it" kind of way, but the goblins in Magicklism wear this scrap armor.
It's just my image, but I find it humorous and not strange that goblins wear "metal curtains" that are not armor, just pipes, bottle openers and doorknobs tied with string.
Sheet metal armor, on the other hand, feels somehow "intelligent" to me. Goblins are wearing full-fledged armor by cutting holes in sheet metal and threading laces through them!

Of course, we know that goblins have the intelligence to heap up mud walls on their own, connect logs and string together, and build pulley-style doors.
My only thoughts on the agenda of removing scrap armor are the above, and I am not opposed to ultimately removing it.

**Comment by ADekema** [comment]
> It would be too close to the already existing sheet metal armor, which is literally shitty lamellar. It's the same thing that you're describing - makeshift lamellar made by drilling holes in flat metal parts and tying them together with thread. The only difference between it and the variant of scrap armor you're proposing would be materials.

Sheet metal armor is a form of shitty plate not lamellar. I also don´t see how what I´m proposing would be the same as sheet metal armour. The scrap armour I´m preposing would have far less coverage and doesn´t cover the hands and feet. 

I do see your point about the skill to make scrap and sheet metal being a bit to close (3 for scrap and 4 for sheet metal). stringing some small bits of metal together shouldn´t take more than fabriction 0 or 1 and tailoring 1. You also make a valid point about the amount of time it would take to take many small pieces of scrap, bash them flat and drill them all. So I would adjust my preposal to:

Scrap armour: ¨A collection of small metal sheets cut roughly into shape and strung together. You would say it was a form of lemallar if it wasn´t full of gaps and still very uncomfortable to wear¨

Armourthickness: same as now.
Coverage: 75%
encumbrance: 18

recepy: I do think it would be better to replace scrap with small sheet metal. That way the player would safe a lot of time having to drill and shape less pieces. The recepy would look something like this:

**Primary Skill:**
[fabrication] (1)
**Proficiencies:**
[Armorsmithing] (1.5× time, 0.15 skill bonus)
[Garment Closures] (1.5× time, 0.5 skill bonus)
[Joint Articulation] (1.5× time, 0.15 skill bonus)
**Time to Complete:**
1 d
**Activity Level:**
Moderate
**Batch Time Savings:**
none
**Tools Required:**
1 tool with [cutting] of 2 or more.
1 tool with [hammering] of 1 or more.
1 tool with [metal sawing] of 1 or more.
1 tool with [drilling] of 1 or more 
**Components:**
-plenty of sting
-x number of small sheets
Autolearn
[fabrication](1)
Written In
[The Streetfighter's Sidekick]

**Comment by KeremBabaG** [comment]
how about just reworking them instead of removing them

**Comment by G0BL1N** [comment]
> how about just reworking them instead of removing them

I gave reasons to why I leaned towards completely removing it.
However, what @ADekema is proposing does sound mostly reasonable (though fabrication 2 does seem more logical to me), so I'm willing to rework it. As I said, more content = more better, and in general I'm against completely removing some parts of the game, even if maintainers would agree with me.
> This is not really relevant, and not in a "so I want to keep it" kind of way, but the goblins in Magicklism wear this scrap armor. 

This is also a very valid point, as I don't want to deal with mods :)

**Comment by fairyarmadillo** [comment]
@anoobindisguise recently reworked some of the low tech armor, particularly armored jackets and vests, and they now make a lot more sense. I'm not sure if scrap armor got touched but it may be worth looking at that PR to see if some of the work has been done already.
