### ISSUE TITLE
Using a variable_object with u_spawn_item causes segfault on load 

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#68747]
### Describe the bug

Despite the documentation for u_spawn_item indicating that its count parameter can take a variable object, attempting to use a math statement with it causes a segfault during game initialization.

### Attach save file

N/A

### Steps to reproduce

1) Place the following JSON somewhere in the game's files so it loads:

>  {
"type": "effect_on_condition",
"id": "EOC_GAME_EXPLODES",
"effect": [
{ "u_spawn_item": "tunic", "count": { "math": [ "(u_val('strength')"] } }
]
}
2) Attempt to load a game or start a new game.
3) Segfault

Changing the count from a math statement to an integer (e.g. "3") allows the game to load with no trouble.

### Expected behavior

Variable objects work for u_spawn_item [as stated in the documentation](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md?plain=1#L851). Failing that, the game provides an error message indicating the problem rather than crashing without an error. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: f191548 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by andrei8l** [comment]
This bit https://github.com/CleverRaven/Cataclysm-DDA/blob/0ec44abb87dd7048d19220991d442b0618275fd9/src/npctalk.cpp#L2957

tries to evaluate a part of the EOC while parsing it. That's pretty crazy. In this case it fails because the math object has not been resolved yet, but it can fail with any other EOC function.

**Comment by andrei8l** [comment]
/confirm looks like I forgot to confirm above
