### ISSUE TITLE
Item wax tracking temperature.

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#68755]
### Describe the bug

I believe this was introduced after the updated #62843 wax changes, which is nice because wax was also bugging me.

Upon load I get the follow error:

 DEBUG    : Item wax is active and tracking temperature, but it should not!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 3099
 VERSION  : b1d9766
****

### Attach save file

[Fompton-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13043068/Fompton-trimmed.tar.gz)

### Steps to reproduce

1. Load saved game from archive
2. Read wax error

### Expected behavior

N/A

### Screenshots

N/A

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: b1d9766 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Karol1223** [comment]
...the wax PR was initially created prior to the introduction of proper temperature blacklists. I'll try to fix that later today. Apologies for the inconvenience.

**Comment by redcrate** [comment]
> ...the wax PR was initially created prior to the introduction of proper temperature blacklists. I'll try to fix that later today. Apologies for the inconvenience.

No problem, thanks for looking into it.
