### ISSUE TITLE
"Heating up food" mechanic [Quality of life]

### ISSUE THREAD

**Issue by NickEmbased** [CleverRaven/Cataclysm-DDA#68765]
### Is your feature request related to a problem? Please describe.

I survived until winter and cooking while all food is frozen became quite tedious. Having to manually to press 3 and potentially more buttons to heat up single unit of food is quite slow in real life time. To make a "PB&J" you need 2 wastebreads so you have to press 6 buttons to heat up two breads for a single recipe.

### Solution you would like.

Adding function to select more than one unit per use to heat, and more than one type of food in "Heat up food", power used is proportionally to amount of units of food heated, you can see amount of power avalibale and how many it will be used for selected food  just like in "washing menu" 

Additionally more QoL:
Even More advanced "heating up food". 

When you press "heat up food" you can use new filter "r:(Recipte name)" in "heating up food" menu. 
"r:PB&J" will show you all ingeridents that are frozen and required for PB&J recipte, so you can easily select them and heat at once with WAY more less keypresses and searches

### Additional context

For my grammar and If there is a way already to do it in game, my apologies

**Comment by MikkoMMM** [comment]
When I looked at the topic of this, I thought it might be something like adding an auto-heating option to the consumption menu. "Automatically heat up food if charges available (and if it tastes good heated up)", and configurable which devices are considered for that.

I guess these ideas could be combined, the heating up food could get to be more elaborate while for the rest of the situations, consumption would be made more streamlined.
