### ISSUE TITLE
Bread doesn't have calories

### ISSUE THREAD

**Issue by Shieldwall** [CleverRaven/Cataclysm-DDA#68769]
### Describe the bug

crafted several batches of bread and flatbread. Bread has a calorie value of 8, flatbread doesn't have any value at all.

### Attach save file

[Roach-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13047991/Roach-trimmed.tar.gz)

### Steps to reproduce

1. Walk to the root cellar
2. craft bread or flatbread

### Expected behavior

bread should have calorie value closer to a 100, flatbread similar

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/14316224/f5fd2bc4-417c-4669-9d47-5691583001e8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/14316224/d8aea9d7-3f22-4eb5-bfcf-9c7f6bf5f4f0)

### Versions and configuration

- OS Windows 10
- Version experimental 2023-10-03-1753
- Graphics: Tiles
- Language: English
- Mods: [dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions]

**Comment by FATM0USE** [comment]
is this flour you milled yourself? milling produced 0 calorie flour until fixed in #68676

**Comment by Shieldwall** [comment]
> is this flour you milled yourself? milling produced 0 calorie flour until fixed in #68676

dope. Does upgrading the game fix the existing flour?

**Comment by RenechCDDA** [comment]
No, the flour's got bad data written already. You can debug in new flour if desired.

**Comment by Shieldwall** [comment]
well, not amazing. It seems that in the newer version I get 10x flour, but it's 4 calories each. But afaik, that's a known thing.
