### ISSUE TITLE
Audit monster dissection proficiency allocation

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#68760]
### Is your feature request related to a problem? Please describe.

The proficiencies gained from corpse dissection are allocated inconsistently and do not always contribute to prerequisite proficiencies, while leaving you in the dark as to what these are. 

- I look at the partially known "Invertebrate Biology" proficiency and see "Basic familiarity with various types of insects, arachnids, and worms" and start to dissect a newly killed large worm, only to find that it doesn't have any associated proficiencies at all.
- I try to dissect a Panicked Person, and find it to likewise be empty of proficiencies (ferals seem to provide Physiology, and I'm not at all against a morale hit on human dissection).
- I try to dissect an acidic zombie, and find that while I have mastered two of the three proficiencies, I lack the unspecified prerequisites for the third one.
- I try to dissect some flying insect (some kind of wasp or a fly, I think) and find that it doesn't contribute to Principes of Flight, while I think some other flying insect corpse did.

### Solution you would like.

Dissection of creatures falling into a group described by proficiencies would contribute to those proficies or, when prerequisites are missing, the next missing prerequisite proficiencie(s).

Edit: After finally finding (through json files) that biochemistry has chemistry as its prerequisite chain, I realize that makes sense for the proficiency itself, but it then doesn't make sense for it to be gained through dissection, but rather should be gained through study of dissection products (acids, what I've seen so far) via research/training recipes.

### Describe alternatives you have considered.

Fumble around in the dark and accept it's a proficiency lottery.

Edit:
Retain biochemistry as a dissection gained proficiency where you analyze its properties while dissecting, rather than in a chemical examination environment, but then somehow indicate you need to study chemistry to gain the prerequisites, not dissecting lots of corpses.

### Additional context

This is not a new issue...

**Comment by Maleclypse** [comment]
Anyone up for making a python script to build s list of monsters that lack proficiencies?

**Comment by PatrikLundell** [comment]
Manually going through stuff (work in progress, noting as I go):
- Birds:  look OK, but ought to also have Physiology based on the description of that proficiency (they are animals, and the proficiency doesn't say mammals).
- Civilians: Look mostly OK, and a spawned Panicked Person did provide the proficiencies. Civilian police ought to have "prof_wp_syn_armored" as well, as it gets it when zombiefied.
- Cyborgs: Zomborg and zomborg devourer ought to have "prof_wp_zombie" and its precursor "prof_intro_biology" as it's a zombie as well. In fact, all cyborgs should have "prof_intro_biology", as they're all biological at the root.
- Defense_bot: OK (nothing to dissect)
- Drones: OK (nothing to dissect)
- Feral_Humans: 
  - mon_feral_armored_mace should have "prof_wp_syn_armored" as well.
  - mon_feral_prepper could be argued to have "prof_wp_syn_armored" as well, as its zombie version has it.
  - mon_feral_survivalist: ditto
  - mon_feral_militia: ditto
- Fish:
  - mon_alpha_razorclaw: ought to have "prof_wp_basic_bug", as there is no group for crustaceans. There probably should be an advanced group for crustaceans as well.
  - the abstract fish should have "families" entries for basic biology and physiology. A brown trout spawned (derived from the huge abstract fish) did not provide any proficiency. Strangely, "prof_wp_basic_fish", or similar doesn't seem to exist, which I thought used to exist
  - lobster and crayfish: Same as for razorclay. Can be argued to get the natural armor as well, but they're probably too small to get it. Mon_giant_crayfish should get the natural armor as well, though (as well as the corresponding weakpoints).
  - mon_crayfish_giant_larva: Can you really harvest "mutant shellfish" from it, given that the fry copied from doesn't seem to generate a body?
  - mon_razorclay actually has the correct set of "families" (including basic bug) unlike the alpha above. Don't know why the alpha doesn't copy from this.
  - The monster fish do not copy-from any of the abstract fish for some reason, and also lack any "families".

**Comment by PatrikLundell** [comment]
- jabberwock:
  - mon_fleshy_shambler: Add physiology an amagamation
  - mon_flesh_golem: ditto
  - mon_jabberwock: ditto
- kraken_spawn:
  - mon_octopus_stalker: Add basic biology, physiology. A cephalopod one if one exists.
- lab_security_drones: Weird to hide mapgen and EoC in this file...
- mammal: Should some also get natural armor?
  - mon_bat: Lacks physiology and principles of flight
  - mon_bear: Physiology
  - mon_beaver: ditto
  - mon_black_rat: ditto
  - mon_lab_rat: ditto
  - mon_boar_wild_piglet: ditto
  - mon_boar_wild: ditto
  - mon_bobcat: ditto
  - mon_cat: ditto
  - mon_chipmunk: ditto
  - mon_cougar: ditto
  - mon_cow_calf: ditto
  - mon_cow: ditto
  - mon_coyote: ditto
  - mon_coyote_wolf: ditto
  - mon_deer_fawn: ditto
  - mon_deer: ditto
  - mon_dog: ditto
  - mon_dog_bull_pup: not inherited and so lacks "families" (and maybe other stuff)
  - mon_dog_pitbullmix: ditto
  - mon_dog_pitbullmix_pup: ditto
  - mon_dog_beagle: ditto
  - mon_dog_beagle_pup: ditto
  - mon_dog_bcollie_pup: ditto (while adult is inherited...)
  - mon_dog_boxer_pup: ditto
  - mon_dog_chihuahua_pup: ditto
  - mon_dog_dachshund_pup: ditto
  - mon_dog_gshepard_pup: ditto
  - mon_dog_gpyrenees_pup: ditto
  - mon_dog_rottweiler_pup: ditto
  - mon_dog_auscattle_pup: ditto
  - mon_fox_grey: Physiology
  - mon_fox_red: ditto
  - mon_groundhog: ditto
  - mon_horse_foal: ditto
  - mon_horse: ditto
  - mon_lemming: ditto
  - mon_mink: ditto
  - mon_moose: ditto. It also has some significant bash armor, so natural armor?
  - mon_moose_calf: Physiology
  - mon_tusked_moose: Physiology and definitely natural armor
  - mon_tusked_moose_calf: Physiology
  - mon_muskrat: ditto
  - mon_opussum: ditto
  - mon_otter: ditto
  - mon_pig_piglet: ditto
  - mon_pig: ditto
  - mon_rabbit_base: ditto
  - mon_raccoon: ditto
  - mon_sewer_rat: ditto
  - mon_sheep_lamb: ditto
  - mon_sheep: ditto
  - mon_squirrel: ditto
  - mon_squirrel_red: ditto
  - mon_weasel: ditto
  - mon_wolf: ditto
  - mon_reindeer: ditto
  - mon_llama_calf: ditto
  - mon_llama: ditto
  - mon_ferret: ditto
- marloss: a mycus proficiency?
  - mon_marloss_zealot_f: basic biology, physiology
  - mon_marloss_zealot_m: ditto
- mechsuits: They're all broken on defeat, so N/A
- mi_go: Highly questionable that these should have any normal proficiencies given that they're completely dissimilar to terrestial life. Rather than demihuman, they should have their very own proficiency and weakpoint. However, they all have significant natural armor, and that's probably something where a different underlying biology doesn't make a difference.
- misc: Cannot make any assessment of these. Generator might actually be intended to be something real, not suitable for this file, though.
- mollusc:
  - mon_snail_river: basic biology, physiology, bug, if you can actually get a corpse from it.
  - mon_snail_forest: ditto.
  - mon_snail_larva: note that its inheritance should provide the right set, including bug.
  - mon_snail_giant: biology, physiology, bug
  - mon_slug_forest: ditto
  - mon_slug_giant: biology, physiology, bug, natural armor. Arthropod weakpoint an option.
  - mon_sludge_crawler: ditto

**Comment by PatrikLundell** [comment]
- mutant: Wouldn't go astray with a mutant proficiency based on physiology.
  - mon_mutant_experimental: biology, physiology, natural armor
  - mon_mutant_antler: ditto
  - mon_mutant_arthropod: biology, physiology, natural armor, bug (and arthropod weakpoints)
  - mon_mutant_alpha: might remove natural armor from antler, depending on where the natural armor threshold should be.
  - mon_mutant_alpha_boss: as alpha, but definitely without natural armor
  - mon_mutant_mollusk: add bug + arthropod weakpoints (antler provides the rest)
- mutant_mammal: Again, possible introduction of mutant proficiency
  - mon_bear_mutant_3headed: physiology, natural armor
  - mon_beaver_mutant_huge: physiology, natural armor?
  - mon_beaver_mutant_avian: physiology
  - mon_coyote_mutant_shark: physiology
  - mon_coyote_mutant_venom: physiology + whatever mutant acid zombies have
  - mon_wolf_mutant_huge: physiology, natural armor
  - mon_deer_mutant_spider: physiology (+ bug?)
  - mon_deer_mutand_spider_fawn: ditto
  - mon_dog_mutant_mongrel: physiology
  - mon_dog_mutant_loper: physiology
  - mon_dog_mutant_mauler: physiology
  - mon_dig_mutant_thrasher: physiology
- nether:
  - mon_albino_penguin: physiology
  - mon_amigara_horror: biology, physiology
  - mon_blank: ditto
  - mon_blood_sacrifice: biology, physiology
  - mon_dementia: biology, physiology
  - mon_flaming_eye: Does it leave a corpse? Comment indicates it should be demihuman, and so also biology and physiology
  - mon_guzu: biology, physiology
  - mon_gracke: biology, physiology
  - mon_human_snail: biology, physiology
  - mon_twisted_body: biology, physiology
  - mon_yugg: biology, physiology, bug (?)
  - mon_hanging_roper: biology, physiology
  - mon_carrion_grub: remove bug from inheritance?
  - mon_nether_spearfisher: biology, physiology
  - mon_nether_leach: remove bug from inheritance?
  - mon_nether_fish: biology, physiology

**Comment by PatrikLundell** [comment]
- turrets: OK. All destroyed or broken on "death"
- utility_bot: Ditto
- yrax: Ditto
- zanimal_upgrade:
  - mon_dog_skeleton: add physiology
  - mon_wolf_skeleton: ditto
  - mon_zombear_skeleton: add physiology, but that should really be done as addition to mon_zombear rather than override of its families and weakpoint sets.
  - mon_zombear_acidic: Similar to previous point. Finally found what the prerequisites of biochemistry are, and while it makes sense to be a chemistry chain in itself, there's a need to tell the player it's not gained through more dissection. Ideally, it should really be gained through analysis of the acid rather than through dissection, and thus be a research/training recipe.
  - mon_zombie_horse_white; ditto
  - mon_zombie_horse: extend families and weakpoints rather than overriding them.

**Comment by PatrikLundell** [comment]
- zed_ferrous:
  - mon_zombie_rust: physiology
  - mon_zombie_shell: physiology
  - mon_zombie_plated: physiology
  - mon_zombie_urchin: physiology. Name implies it is small, but nothing else seems to support that.
  - mon_zombie_hammer_hands: physiology
- zed_fusion:
  - mon_crawler: physiology. Also ought to be aberration family/weakpoint, possibly natural armor, and probably zombie, as that's what's harvested.
  - mon_devourer: physiology. Why not aberration?
  - mon_devourer_lab_sec: no corpse, no families... Should have synthetic armor weakpoints, though, and possibly aberration.
  - mon_zombie_crushed_giant: No corpse, no families.
  - mon_zombie_gasbag_immobile: ditto
  - mon_zombie_gasbag_crawler: ditto
  - mon_zombie_gasbag_impaler: ditto
  - mon_zombie_scissorlimbs: ditto
  - mon_zombie_hanging_innards: ditto
  - mon_zombie_giant_heart: harvest exempt means no dissection?
  - mon_zombie_living_wall: ditto
- zed_lab:
  - mon_zombie_scientist: physiology
  - mon_zombie_labsecurity: physiology
  - mon_zombie_phase_skulker: no body, no families...
  - mon_zombie_phase_shrike: ditto
- zed_lieutenant: Another file with unrelated stuff like spells, eocs, and terrain. The monster doesn't leave a body.
- zed_misc:
  - mon_frog_mother: physiology. Natural armor?
  - mon_zombullfrog: ditto
  - mon_frog_dad:ditto
  - mon_zombie_biter: physiology
  - mon_zombie_brainless: physiology
  - mon_afs_headless_horror: physiology
  - mon_zombie_brute: physiology. Natural armor?
  - mon_zombie_brute_grappler: ditto
  - mon_zombie_brute_ninja: ditto
  - mon_zombie_grue: physiology
  - mon_zombie_ears: physiology
  - mon_zombie_nemesis: physiology
  - mon_zombie_grabber: physiology
  - mon_zombie_grappler: physiology
  - mon_zombie_hulk: physiology
  - mon_zombie_hunter: physiology
  - mon_zombie_mancroc: physiology
  - mon_zombie_master: physiology
  - mon_zombie_necro: physiology
  - mon_zombie_runner: physiology
  - mon_zombie_regenerating: physiology
  - mon_zombie_predator: physiology
  - mon_zombie_screecher: physiology
  - mon_zombie_shady: physiology
  - mon_zombie_shrieker: physiology
  - mon_zombie_skull: physiology
  - mon_zombie_smoker: physiology
  - mon_smoker_brute: physiology
  - mon_zombie_swimmer_base: physiology
  - mon_zombie_swimmer: physiology
  - mon_zombie_technician: physiology
  - mon_zombie_miner: physiology
  - mon_zombie_thorny: physiology
  -

**Comment by PatrikLundell** [comment]
- zed_prisoner: OK
- zed_radiation:
  - mon_charred_nightmare: physiology. Should it also be aberration and/or natural armor?
  - mon_irradiated_wanderer_1: ditto
  - mon_irradiated_wanderer_2: ditto
  - mon_irradiated_wanderer_3: ditto
  - mon_irradiated_wanderer_4: ditto
- zed_skeletal:
  - mon_skeleton: physiology
  - mon_skeleton_brute: physiology
  - mon_skeleton_electroc: physiology
  - mon_skeleton_hulk: physiology
- zed_soldier:
  - mon_zombie_soldier: physiology
  - mon_zombie_soldier_blackops_1: physiology
  - mon_zombie_soldier_acid_1: extend families rather than replace. Biochemistry...
  - mon_zombie_soldier_acid_2: ditto
  - mon_zombie_kevlar_0: physiology
  - mon_zombie_kevlar_1: physiology
  - mon_zombie_kevlar_2: physiology
  - mon_zombie_military_pilot: physiology. synthetic armor?
  - mon_zombie_marine: physiology
  - mon_zombie_armored: physiology
  - mon_zombie_bio_op: physiology
- zed_survivor:
  - mon_zombie_survivor: physiology
  - mon_zombie_paramilitary: replace weakpoint set (light->normal armor), leave families unchanged (like the mon_zombie_survivor_elite)

**Comment by TheSaddestGoomba** [comment]
I've got a PR draft #68197 that has weakpoints and proficiencies setup for amphibians.

**Comment by Brambor** [comment]
> Anyone up for making a python script to build s list of monsters that lack proficiencies?

Sounds like a perfect job for me!
