### ISSUE TITLE
Skill Rust Not Triggering

### ISSUE THREAD

**Issue by TheMurderUnicorn** [CleverRaven/Cataclysm-DDA#68777]
### Describe the bug

After several people were asking if skill rust was removed, we were talking about it and I started testing it.  After 9 days, I had no skill rust at all, so I'm assuming it's broken/would have triggered by then.  So, looks like skill rust is not triggering.  Version below with the game info stuff, it was the most recent experimental as of the time of me typing this.

### Attach save file

N/A

### Steps to reproduce

Yeah so to do this I just waited until daylight for 9 days, debugging away my fatigue and eating/drinking normally.  I assume that debug time travel would not trigger rust, so I didn't want to do it that way.  So there doesn't seem to be a fast/easy way to test it.

Something like 

1. Have skills
2. Wait a long time
3. Observe no skill rust

### Expected behavior

I expect skill rust to trigger after this period of time.  I think it used to trigger after only a few days.  

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ee51041 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

I was not using any of the traits that modify skill rust in any way.  Now that I think about it, I did debug my skills in this scenario as I did not have a character ready to test, it is possible that debug setting skills may have interfered with rust in some way?  But since other people were reporting this, that seems unlikely to be a factor.

**Comment by ehughsbaird** [comment]
Probably a result of #68490

**Comment by ehughsbaird** [comment]
Looks like this line was removed in error.
https://github.com/CleverRaven/Cataclysm-DDA/pull/68490/files#diff-ae9922f155c3fc7e9550f2615bdb0a2edf16086f4a81ac08205fc5089ec85ff4L409
