### ISSUE TITLE
Autodrive cannot find prerouted path up and down 3D bridge ramps

### ISSUE THREAD

**Issue by Lord-Helmchen** [CleverRaven/Cataclysm-DDA#68788]
### Describe the bug

Autodrive can't see up and down the ramps of 3D brides, and thus can't see a path forward" while following the planned route.

### Attach save file

N/A

### Steps to reproduce

1) get in a car
2) set waypoint to other side of a bridge
3) start autodrive
-> autodrive stops with "Can't see a path foward" before the ramp. Somethimes it does a little 90° flourish before stopping.

### Expected behavior

Autodrive woudfollow it's preplanned route up and down the ramps and over the bridge.

### Versions and configuration

Win
f2f8378 (tiles)
2023-10-21-0518 (4 hours ago)

**Comment by TheRafters** [comment]
Confirmed, been a thing since they were created as far as I can recall.
