### ISSUE TITLE
typo in arabic armor crafting categories

### ISSUE THREAD

**Issue by Vaskritaya** [CleverRaven/Cataclysm-DDA#68799]
### Describe the bug

In the nested categories for several arabic armors, the "hardened steel" category is incorrectly labeled as "tempered steel"

### Attach save file

N/A

### Steps to reproduce

1. get copy of tools of warfare in the arabic world, or just debug all recipes
2. go to crafting menu, find ex. steel mirror armor or  steel face masks
3. "tempered steel X" instead of "hardened steel X"

### Expected behavior

hardened steel category should be labeled as hardened steel, not tempered steel

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22992007/d9b6f758-fef5-4349-bdbb-6f19251eba65)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: e0f5f8a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

**Comment by ZhilkinSerg** [comment]
Translations are handled in Transifex - see https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/. All fixes for non-English languages are handled there.

**Comment by Vaskritaya** [comment]
> Translations are handled in Transifex - see https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/. All fixes for non-English languages are handled there.

You misunderstand. This is for the English language. The armors that are affected are the ones from the "Tools of Warfare in the Arabic World" book.
