### ISSUE TITLE
Quilts and Fur Blanket Crafting and Dissasemble Recipe

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#68795]
### Is your feature request related to a problem? Please describe.

While Sheets, Down-filled Blankets, and regular blankets have disassemble recipes, Quilts lack a recipe, as well as a disassemble recipe for full sized Felt sheets instead of felt patches. this is odd as a quilt shouldn't be unable to be turned into tailoring ready felt sheets, as was a common usage for winter clothing in the 17-1800's. Fur Blankets also lack a disassemble recipe

### Solution you would like.

Add a crafting recipe for either patchwork or full quilts using felt sheets, as well as add a dissasembly for felt sheets
add a disassembly recipe for fur blankets

### Describe alternatives you have considered.

have a seperate recipe for patchwork quilts using felt patches and/or patchwork felt sheets?

### Additional context

my googlefu is weak, but surely someone would be able to gather examples of blankets and such being remade into functional garments

**Comment by a-chancey** [comment]
If they're returning felt sheets, that's a problem, they should be returning felt patches at worst and felt patchwork sheets at best (cut up and disassemble respectively). 

Note that a patchwork sheet isn't explicitly 8 patches seen in a rectangle - it's a 12x24 piece of fabric that's not a contiguous "off the bolt" piece of fabric

I don't want to commit to fixing it if someone else will be able to before me, this is a good first issue and someone could get their contributor status with this

**Comment by Kantonine** [comment]
> If they're returning felt sheets, that's a problem, they should be returning felt patches at worst and felt patchwork sheets at best (cut up and disassemble respectively).
> 
> Note that a patchwork sheet isn't explicitly 8 patches seen in a rectangle - it's a 12x24 piece of fabric that's not a contiguous "off the bolt" piece of fabric

For patchwork quilts? sure thing, but I still think regular quilts should have felt sheets though, or would a woolen quilt not be reasonably able to be taken apart into regular sheets?

**Comment by a-chancey** [comment]
IRL, non-patchwork quilts are almost always three distinct layers - two outer facings and a batting in the middle - but all three can be the same material.

Typically, to keep the inner layer secured, a patterned or decorative stitch is used.

While it could return full felt sheets from a non patchwork quilt, the amount of time spent ripping the stitching might not be worth it.

additionally, we don't really have a material that works as a polyfill batting in game, which most commercially produced quilts would actually have

**Comment by Kantonine** [comment]
> additionally, we don't really have a material that works as a polyfill batting in game, which most commercially produced quilts would actually have

why not cotton balls? pillows in cdda can be taken apart for the cotton balls inside, and it could be a good replacement for the batting for quilts

**Comment by a-chancey** [comment]
Ah I didn't think about cotton balls. I like it, at least until someone decides to add batting.

**Comment by Kantonine** [comment]
https://www.quiltingboard.com/main-f1/quilting-raw-cotton-baten-t291331.html

even some quilters irl used cotton balls in ye olden days

**Comment by DragonWizard23** [comment]
Happy New Year! 

I can try to tackle this issue, but I'd like to make sure I'm understanding the desired solution first. It sounds like this issue has a couple parts:

- Add a crafting recipe for making (commercial grade) quilts from felt sheets and cotton balls. 
- Add a crafting recipe for making patchwork quilts from patchwork felt sheets (or maybe even a bunch of felt patches?) and gambeson batting. I think gambeson batting is the best choice here because a survivor making this recipe simply wants to be warm; patchwork quilts are not held to commercial grade standards. 
- ~~Add a quick cut up recipe for felt sheets that returns felt patches.~~
- Add a disassembly recipe for felt sheets that returns patchwork felt sheets. 
- ~~Add a quick cut up recipe for fur blankets that returns fur patches.~~
- Add a disassembly recipe for fur blankets that returns patchwork fur sheets. 

From devcord, I've been told that the cut up recipes should define themselves based on the material, but the disassembly recipes need to be manually defined. Aside from that, did I summarize this discussion correctly?

**Comment by Kantonine** [comment]
> Happy New Year!
> 
> I can try to tackle this issue, but I'd like to make sure I'm understanding the desired solution first. It sounds like this issue has a couple parts:
> 
>     * Add a crafting recipe for making (commercial grade) quilts from felt sheets and cotton balls.
> 
>     * Add a crafting recipe for making patchwork quilts from patchwork felt sheets (or maybe even a bunch of felt patches?) and gambeson batting. I think gambeson batting is the best choice here because a survivor making this recipe simply wants to be warm; patchwork quilts are not held to commercial grade standards.
> 
>     * ~Add a quick cut up recipe for felt sheets that returns felt patches.~
> 
>     * Add a disassembly recipe for felt sheets that returns patchwork felt sheets.
> 
>     * ~Add a quick cut up recipe for fur blankets that returns fur patches.~
> 
>     * Add a disassembly recipe for fur blankets that returns patchwork fur sheets.
> 
> 
> From devcord, I've been told that the cut up recipes should define themselves based on the material, but the disassembly recipes need to be manually defined. Aside from that, did I summarize this discussion correctly?

id say that works just fine on my end, and gets everything thats neccesary
