### ISSUE TITLE
Problem with grain stook

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#68797]
### Describe the bug

drying cereal stalks through a 'Stooking spot' does not work correctly, after drying all cereals have zero calories, but if you dry them through the crafting system (shift + 7) everything is fine

### Attach save file

None

### Steps to reproduce

1. create 'Stooking spot'
1. put cereal stalks (i try on wheat, wild rice and buck wheat)
1. activate grain stook
1. wait two weeks
1. activate ready grain stook

### Expected behavior

calories > 0

### Screenshots

![grain_stook](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/1b5c99b3-1d26-4255-989c-67a25856ea83)
![wharf](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/4d7a8f19-7b43-4815-85ec-f68c3118d4ec)
![buckwheat](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/a1aa8345-a498-427e-9315-4c1293d0cd65)
![wild_rice](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/75b53267-fb37-47f4-9915-034d578563cc)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: ee51041 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
Is this related to the issue with milling (caused by charge removal)?

**Comment by fairyarmadillo** [comment]
It's because of the charge removal. The following code in iexamine.cpp covers it:

` for( item &it : items ) {
        if( it.has_flag( flag_SMOKABLE ) && it.get_comestible() ) {
            item result( it.get_comestible()->smoking_result, it.birthday(), it.charges );
            recipe rec;
            result.inherit_flags( it, rec );
            if( !result.has_flag( flag_NUTRIENT_OVERRIDE ) ) {
                // If the item has "cooks_like" it will be replaced by that item as a component.
                if( !it.get_comestible()->cooks_like.is_empty() ) {
                    // Set charges to 1 for stacking purposes.
                    it = item( it.get_comestible()->cooks_like, it.birthday(), 1 );
                }
                result.components.add( it );
                result.recipe_charges = it.charges;
            }
            add_msg( _( "You take down the stook as the drying process is now finished." ) );
            it = result;
        }
    }`

That just needs to be changed from charges to count.
