### ISSUE TITLE
Menu hotkeys skip 4 and 6

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#68808]
### Describe the bug

Several game menus that use numbers as hotkeys skip 4 and 6 when assigning hotkeys. This includes at least the main menu (default key: Esc), action menu (RETURN) and item action menu (%).

### Attach save file

[Mind Progress_2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13063365/Mind.Progress_2-trimmed.tar.gz)

### Steps to reproduce

Open one of the relevant menus

### Expected behavior

When a menu is assigning alphanumerical hotkeys in order, it shouldn't just skip things at random.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/75f0ce32-c604-4ba9-a45b-890829d08787)
Main menu. It's showing the key I bound "Sidebar" options to in the main hotkeys rather than giving it a number, dunno if that's relevant.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/b1178027-79c4-431c-a834-f23024a1efe2)
Actions

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/dc43081e-6ce3-4536-89a6-553bcaf08b0f)
Item actions

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: f012990 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

This issue was originally brought up [on Reddit](https://www.reddit.com/r/cataclysmdda/comments/17drqmv/you_know_what_i_hate_the_most_when_it_changes_in/), so it's definitely not just me

**Comment by ZhilkinSerg** [comment]
You probably have `4` and `6` bind to something. What does `?` say in the menu w/o `4` or `6`.

**Comment by Terrorforge** [comment]
It appears #68761 introduced this problem by defaulting 4 and 6 to being bound to the pan left/right function introduced in that PR, and I guess spells use the same kind of menu as the main menu etc.
