### ISSUE TITLE
Preventing Uncontrollable Character

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#68828]
### Is your feature request related to a problem? Please describe.

Although the game allows many actions to be interrupted by pressing “5”, or automatically pops up a warning when the character is threatened, this mechanism does not cover all actions. In cases like #68826 , an action that appears to take “just a few seconds” unexpectedly runs for over a dozen hours, during which the character is uncontrollable. Even a passing wild goose could potentially kill the character. The game’s built-in debug is of no help either, as it also does not respond to player commands.

### Solution you would like.

Add interruption commands for every possible action.

### Describe alternatives you have considered.

Or, before executing each action, assess the potential time it might take, and issue a warning if necessary.

Due to the auto-save feature, sometimes we can't revert to a past save. At the very least, I want to know how to modify the save to stop an ongoing action?

**Comment by toweroglass** [comment]
picking up and dropping items seems to have gone a little off the rails. you can easily move items in seconds via the AIM ('/') menu, but those same tasks will take hours if you just 'd'rop them. every single item will take a full minute. the windmill seems to be doing something similar.
