### ISSUE TITLE
Can't fit armchair in back of van

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#68839]
### Describe the bug

Armchair volume = 570L
Cube Van storage space capacity = 500L

How do we feel about this? 

Suggested fix: Reduce armchair volume to 500L.

### Attach save file

N/A

### Steps to reproduce

Pick up armchair, try to place in back of cube van.

### Expected behavior

Armchair should fit in Van.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 446e59e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by oosyrag** [comment]
/summon @Karol1223 

One possible explanation is that this armchair wouldn't fit within a single square meter tile, and we unfortunately have no way to put items across multiple tiles. 

Although it's not so far off that maybe it could be rebalanced as a somewhat smaller armchair...

**Comment by Karol1223** [comment]
It's important to note that vehicle tiles are not, in fact, 1x1m, but 0.5x0.5m if what I kept hearing on the devcord was correct

An armchair would not fit in that. I did miscalculate seating furniture volume for chairs and stools, because I didn't account for empty space between legs - but the armchair does not have this luxury. The volume for it was calculated correctly, and they're just not particularly easy to transport.

**Comment by oosyrag** [comment]
Until we have some sort of working implementation allowing items stored across multiple vehicle tiles (unlikely), this is probably a no go. I recall a workaround with fridges being strapped to the top of the vehicle as a vehicle part at some point, not sure if that was implemented though. That's another possible solution if anyone wants to go about adding it.

**Comment by Karol1223** [comment]
I do not believe this has been implemented for fridges, but it has indeed been implemented for mattresses - I would not object to someone giving armchairs the same (or similar, since I'm not sure if the mattress adds a new tile onto the vehicle or not - an armchair definitely should) treatment, but artificially lowering item volume solely to pack them inside cargo spaces isn't the way to go.

**Comment by toweroglass** [comment]
[a tied down fridge is in the game.](https://cdda-guide.nornagon.net/vehicle_part/stowed_fridge) i haven't had to do it before, but i assume it works.

i think the solution for the arm chair would be to disassemble it into basic components. IRL you could transport one much easier by removing the back from the seat/arm rests. which could easily be achieved in game.

**Comment by Karol1223** [comment]
> i think the solution for the arm chair would be to disassemble it into basic components. IRL you could transport one much easier by removing the back from the seat/arm rests. which could easily be achieved in game.

This is a sensible approach but would require someone to add several pieces which would be exclusive to disassembling armchairs and a new recipe on top. Current disassembly salvages it into basic resources and you're not getting the full armchair back from that.

**Comment by Maleclypse** [comment]
You could tie it to the roof like the fridge which I think would require it be convertible into a placeable item, basically copying fridge infrastructure.

**Comment by toweroglass** [comment]
> It might be possible for someone interested to create a new item called e.g. disassembled armchair which could be assembled into a regular armchair while an armchair could in turn be taken down into a disassembled armchair. The difficulty here is that it shouldn't be an instant action, but should take some time and require some tools.

I agree it shouldn't be instantaneous, but i don't think it needs to be a 30 minute operation either. irl with the proper tools i could easily roll over a chair and take it apart quickly. obviously it would take me a bit to get out my tupperware of random ikea single use wrenches, but there isn't a CDDA analog for that so the screwdriver i carry around should be sufficient.

**Comment by I-am-Erk** [comment]
What would be really nice, and I think I've been told it wouldn't be all that hard to implement, would be if certain vehicle tiles were treated as a single storage space in terms of volume available when adjacent. So two cargo spaces with volume 500 next to each other would give an available space of 1000, minus the total volume of everything in both spaces.
