### ISSUE TITLE
Screwdriver gives low stabbing exp.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#6883]
When using a screwdriver (damage bash 2, pierce 6) you seem to get a lot more bash exp than stabbing exp. Which is odd as the weapon is mostly a stabbing weapon.

http://smf.cataclysmdda.com/index.php?topic=5838.0

**Comment by illi-kun** [comment]
Tested in the current master. This is not an issue anymore.
