### ISSUE TITLE
Allow item descriptions to reference snippets, the way dialogue does.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#68831]
### Is your feature request related to a problem? Please describe.

I've been trying to create a few items here recently, and I noticed that I cannot call up snippets for use in their descriptions like I can in dialogue, such as using <given_name> or something similar. This makes item descriptions very limited in what they can say, especially for story-related items like survivor notes or lab notes.

### Solution you would like.

I would like to be able to reference snippets in item descriptions the way I can in dialogue, calling them as needed.

### Describe alternatives you have considered.

Manually creating override strings that feature all possible combinations of the snippets I'm trying to use, which is extremely tedious and takes up way too much space.

### Additional context

None at this moment.

**Comment by ehughsbaird** [comment]
You can use snippet categories for this purpose https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#random-descriptions

**Comment by ehughsbaird** [comment]
For doing it in all item descriptions, it looks something like:
```diff
diff --git a/src/item.cpp b/src/item.cpp
index a59761605f..9261f00baa 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -2272,14 +2272,15 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
                 get_avatar().add_snippet( snip_id );
             }
         } else if( idescription != item_vars.end() ) {
-            info.emplace_back( "DESCRIPTION", idescription->second );
+            info.emplace_back( "DESCRIPTION", SNIPPET.expand( idescription->second ) );
         } else if( has_itype_variant() ) {
             // append the description instead of fully overwriting it
             if( itype_variant().append ) {
-                info.emplace_back( "DESCRIPTION", _( string_format( "%s  %s", type->description.translated(),
-                                                     itype_variant().alt_description.translated() ) ) );
+                info.emplace_back( "DESCRIPTION", _( string_format( "%s  %s",
+                                                     SNIPPET.expand( type->description.translated() ),
+                                                     SNIPPET.expand( itype_variant().alt_description.translated() ) ) ) );
             } else {
-                info.emplace_back( "DESCRIPTION", itype_variant().alt_description.translated() );
+                info.emplace_back( "DESCRIPTION", SNIPPET.expand( itype_variant().alt_description.translated() ) );
             }
         } else {
             if( has_flag( flag_MAGIC_FOCUS ) ) {
@@ -2297,7 +2298,7 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
                                    craft_data_->making->result_name(),
                                    percent_progress ) );
             } else {
-                info.emplace_back( "DESCRIPTION", type->description.translated() );
+                info.emplace_back( "DESCRIPTION", SNIPPET.expand( type->description.translated() ) );
             }
         }
         insert_separation_line( info );
```

**Comment by MNG-cataclysm** [comment]
> For doing it in all item descriptions, it looks something like:
> 
> ```diff
> 
> diff --git a/src/item.cpp b/src/item.cpp
> 
> index a59761605f..9261f00baa 100644
> 
> --- a/src/item.cpp
> 
> +++ b/src/item.cpp
> 
> @@ -2272,14 +2272,15 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
> 
>                  get_avatar().add_snippet( snip_id );
> 
>              }
> 
>          } else if( idescription != item_vars.end() ) {
> 
> -            info.emplace_back( "DESCRIPTION", idescription->second );
> 
> +            info.emplace_back( "DESCRIPTION", SNIPPET.expand( idescription->second ) );
> 
>          } else if( has_itype_variant() ) {
> 
>              // append the description instead of fully overwriting it
> 
>              if( itype_variant().append ) {
> 
> -                info.emplace_back( "DESCRIPTION", _( string_format( "%s  %s", type->description.translated(),
> 
> -                                                     itype_variant().alt_description.translated() ) ) );
> 
> +                info.emplace_back( "DESCRIPTION", _( string_format( "%s  %s",
> 
> +                                                     SNIPPET.expand( type->description.translated() ),
> 
> +                                                     SNIPPET.expand( itype_variant().alt_description.translated() ) ) ) );
> 
>              } else {
> 
> -                info.emplace_back( "DESCRIPTION", itype_variant().alt_description.translated() );
> 
> +                info.emplace_back( "DESCRIPTION", SNIPPET.expand( itype_variant().alt_description.translated() ) );
> 
>              }
> 
>          } else {
> 
>              if( has_flag( flag_MAGIC_FOCUS ) ) {
> 
> @@ -2297,7 +2298,7 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
> 
>                                     craft_data_->making->result_name(),
> 
>                                     percent_progress ) );
> 
>              } else {
> 
> -                info.emplace_back( "DESCRIPTION", type->description.translated() );
> 
> +                info.emplace_back( "DESCRIPTION", SNIPPET.expand( type->description.translated() ) );
> 
>              }
> 
>          }
> 
>          insert_separation_line( info );
> 
> ```

Could you make a PR for that please? I don't currently have the capabilities to work with C++.
