### ISSUE TITLE
Smoke Grenades

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#68836]
### Is your feature request related to a problem? Please describe.

I've got other stuff on my plate so I am not in a position to take this on myself, but it would be pretty useful in this game to have smoke grenades. You could use them to break LOS on zombies, get past turrets, all that fun stuff. Police and the army have them, they shouldn't be too hard for a survivor to find or even craft.

### Solution you would like.

I guess I don't know how much smoke they make, how quickly they make it, how big of an area it would fill, how long it would stick around, and whether you can safely breathe it in without a gas mask. I guess anyone trying to implement them would need to know that much. I'm guessing it'd just be a new type of field that is similar to existing smoke but not as noxious.

I don't think they'd be super hard to implement. I guess we could do tear gas grenades too, and whatever other kinds of smoke/gas.

### Describe alternatives you have considered.

Standing out in the open like a goober.

**Comment by gettingusedto** [comment]
you mean this?
https://cdda-guide.nornagon.net/item/smokebomb

**Comment by fairyarmadillo** [comment]
> you mean this? https://cdda-guide.nornagon.net/item/smokebomb

SINCE WHEN?!

Somehow I have never noticed these. I was probably expecting them to be called smoke grenades.
