### ISSUE TITLE
Collapsed tower bugs

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68842]
### Describe the bug

Various bugs related to the flooring in collapsed tower

1. Generated holes in the floor destroy the objects that occupied the space, leaving the debris "floating" above the hole. This debris will update and fall AFTER performing actions such as climbing down, or placing a stepladder on the tile below, resulting in a smashed stepladder or face. 

2. Holes can generate above the nanofab room, allowing the player to climb directly down into the target room. I'm assuming this is not intended, as doing so can (sometimes?) trigger the hole being inexplicably replaced by a metal floor, sealing you below. #66822 probably related, as described by ANID in the comments. Seems like saving and loading within the reality bubble triggers the metal flooring to spawn as well, which I did not observe myself.

### Attach save file

Not available, will try to set one up if others are unable to verify or reproduce.

### Steps to reproduce

1. Find and visit a collapsed tower, climb down a hole, be smashed by falling debris from above.

2. Not sure what triggers the metal flooring/roof to spawn.

### Expected behavior

1. Debris to fall upon loading into the reality bubble or when holes are generated.

2. Metal floor/roof in place when holes are generated.

### Versions and configuration

OS: Android
OS Version: Manufacturer: OnePlus; Model: HD1900; Release: 12; Incremental: Q.202303230244;
Game Version: 2c8ae07 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Slowdown Fungal Growth [no_fungal_growth],
  Bionic Professions [package_bionic_professions]
]

**Comment by a-chancey** [comment]
With regards to number 2, I mentioned this to @bombasticSlacks  over a year ago on discord, when I found out he removed the M202A1 talon from the basement. 

The holes are a side effect of the bash terrain function, as far as I am aware, which happens *in* the nanofabricator room to ensure it's non functional
