### ISSUE TITLE
JSonize Hallucinations

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#68846]
### Is your feature request related to a problem? Please describe.

`static void eff_fun_hallu( Character &u, effect &it )`
is the start of the function that allows hallucinations to function.  This function could be jsonized in order to provide multiple types of hallicangent experiences. Then it could be called by EOCs and impacted by them.  Traits could reduce your susceptibility to hallucinations all kidns of things would open up.

### Solution you would like.

Jsonize it please :)

**Comment by Standing-Storm** [comment]
Seconding this so I can add a "cause hallucination" telepathy power (with some kind of hack to make it seem like monsters you use it on are hallucinating and actually hallucinations when they use it on you)

**Comment by MNG-cataclysm** [comment]
What file is all of the hallucination effects stored in? I'd like to cross-reference them for JSON-izing.
