### ISSUE TITLE
Antiseptic powders spawns 50 bottles, 1 powder each in Doctor's Office

### ISSUE THREAD

**Issue by Vaskritaya** [CleverRaven/Cataclysm-DDA#68857]
### Describe the bug

Instead of a single bottle of 50 antiseptic powders, it incorrectly spawned as 50 plastic bottles, each containing a single unit of antiseptic powder. Presumably a consequence of the comestible charge PR.

### Attach save file

Unfortunately, I only thought to report this well after sorting out the items. That being said, I feel an included save would not be particularly useful or important here.

### Steps to reproduce

1. visit doctor's offices until you find one with bottles of antiseptic powder.
2. see title.

### Expected behavior

A single plastic bottle can contain at least 50 antiseptic powders, so that is presumably the intended result.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: a64a417 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

likely a consequence of https://github.com/CleverRaven/Cataclysm-DDA/pull/60885

**Comment by TheRafters** [comment]
I've also seen this in augmentation clinics. It seems to happen around auto docs there
