### ISSUE TITLE
Character refuses to work due to frustrated, even though he's in a great mood.

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#68853]
### Describe the bug

My character refuses to work, even though he's in a really good mood and doesn't have any negative feelings.

### Attach save file

[帕洛阿尔托-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13105746/-trimmed.tar.gz)

### Steps to reproduce

1 Try crafting any item.

I haven't encountered the same issue in other game progressions, it's only reproducible in this specific save file.

### Expected behavior

Tell me why I refuse to work.

### Screenshots

<img width="1055" alt="3" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/1281487/7c77595e-2a20-4a5d-b845-b1b554036fbb">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 446e59e [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    神话武术 [MMA]
]

**Comment by oosyrag** [comment]
That message is not (directly) related to morale (which would be "Your morale is too low to continue crafting."). It occurs when you work below 20% speed from all factors, including light, work surface, morale, mutations, and manipulation (encumbrance) score.
