### ISSUE TITLE
Antidepressants shafted by charge removal?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#68866]
### Describe the bug

The Refugee Center quest by Uyen to deliver antidepressants has always been hard/tedious because of how rare these drops are, but now it's essentially impossible since the pill boxes contain a single pill each, rather than a reasonable number.

### Attach save file

N/A

### Steps to reproduce

1. Play and clear out dozens upon dozens of homes and other locations of their medical supplies.
2. Continue until you'd managed to find antidepressant, and realized there's only a single pill in each find.

### Expected behavior

The number of pills should be returned to approximately the number they were dropped at previously.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4656-g10cdb0ceaf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

Note that this doesn't necessarily reflect the versions at which the drops were found.

### Additional context

It's probably yet another victim of charge removal where the charges weren't replaced by the corresponding number of items.

**Comment by oosyrag** [comment]
Linking this issue with #68857, in case anyone wants to tackle both at the same time, and also #67915 for an example of a fix.

**Comment by PatrikLundell** [comment]
It looks like antidepressants have an auto generated spawn group of 1-15 pills, but it's just not used for drops (item_groups npc_misc, NC_REFUGEE_DOCTOR_misc).
It seems the same goes for bfipowder, where there is a 1-4 group that's used in some places but not others (item_groups drug_misc, mil-surplus, and surgery).

The npc_misc group seems to be full of entries that should be modified, and most of the entries in NC_REFUGEE_DOCTOR_misc should probably be modified as well.

The drugs_rare item_group uses a count-min/count-max syntax throughout with a 15-60 range for all entries, regardless of what the ranges are elsewhere, which seems odd.

For some reason the item_group NC_CITY_COP_misc has its own auto generated drug entries with a fixed number of items. I suspect that's wrong and that it should instead use the normal 1-X range auto generated groups. The NC_DOCTOR_misc is probably correct in using the "full" bottle groups (I don't know if those groups are consistent with the ranged groups, though).

Making changes from base item to item group seems fairly straightforward, but testing that it actually works does not, in particular for something as rare a antidepressants (internally prozac).

**Comment by fairyarmadillo** [comment]
> The people who "automated" charge removal seems to have done only the automatic part, not the follow up tedious step of ensuring the auto generated groups were actually used where they should be, 

The charge removal PR broke so much stuff that it put me off of contributing for months. A ton of work I'd been doing was wiped out despite people protesting in the comments and it still hasn't all been fixed.
