### ISSUE TITLE
Regarding the UX for disassembly, butchering, deconstruction, etc.

### ISSUE THREAD

**Issue by MikkoMMM** [CleverRaven/Cataclysm-DDA#68868]
### Is your feature request related to a problem? Please describe.

It is a frustration that I can't easily compare cutting up an object and disassembling an object. Sometimes disassembly takes too long to consider seriously, while cutting up might leave components unclaimed that I might want to have. I don't think you can even preview the expected results of cutting up an item anywhere in-game.

The current butchering / disassembly screen also seems messy in that corpses, shortcut options and action+item pairs are mixed in with each other. Sure, yields could be added as columns to the butchering / disassembly screen but you'd still be missing the functionality that the Disassemble items screen added:
* Showing items that are elsewhere than just on the ground beneath you
* Filtering by the components you get for disassembly (or at least it seems that's what adding "d:" to the start of the filter does. How I'm not certain of what the effect even is just shows more evidence that the options you have for filtering should be made more visible and explained, like what's been done in the crafting menu). Sure, advanced filtering could be added to the butchering / disassembly screen, but I'm not sure how much work it would be; it would need to contend with cutting up and disassembly being in the same screen unlike in the inventory framework, plus what to do with all the extra options that aren't items.
* Since that screen seems to use the inventory framework, you could integrate a multi-disassembly similar to how you can select multiple items to drop. If this was tried to be added to the butchering / disassembly screen, you'd have to deal with cases where the player tries to select the same item for both cutting up and disassembly, or what it should do when the player tries to select a butchering option as well as a disassembly option.
* Show/hide contents
* Hierarchy and category views; with butchering / disassembly screen it's just a long list

There's also the thing with Deconstruct Furniture and Deconstruct Simple Furniture that are nested in another menu entirely already. Searching for those is a chore, and they'd be better off to be in a smaller listing somewhere. (Do we *really* need two options for furniture deconstruction, by the way? Another thing to look at at some point.)

### Solution you would like.

I propose revamping the butchering / disassembly screen to have just a list of actions on its top level with an interface more like the construction menu in order to accomodate a large tooltip that some of the options require. When an action is selected, a Disassemble items like screen is shown for things where it might be at all relevant, importantly with expected yields shown. The new structure of the top level of the screen could be:
* a Disassemble items
* c Cut up items
* B Quick butchery
* b Full butchery
* f Field dress corpse
* s Skin corpse
* l Bleed corpse
* k Quarter corpse
* m Dismember corpse
* d Dissect corpse
* f Deconstruct furniture
* F Deconstruct simple furniture
* g Cut grass
* G Remove grass
* S Extract sand
* C Extract clay
* R Remove gravel
* M Remove rubber mulch
* u Clear rubble
* r Disassemble everything recursively
* e Do on every object on current tile
* E Do on every object on all nearby tiles

### Overall changes to workflow

Considering how this all changes the workflow, for item disassembly you'd need one extra keypress even if the current hotkey is removed, and that's not something I'm necessarily suggesting.

Cutting up items was previously only available without information about what the yields are and with the caveats about how the item has to be on the ground beneath the player. In the new cutting up items menu, yields can be seen and the player won't need to worry about dropping items they want to cut on the ground. I'd not even say it adds keypresses, since even in the old menu the disassembly options were on top and thus you'd need keypresses to scroll down to the cutting options.

Butchery is perhaps the most up-in-the-air thing considering the "butcher everything" is in my mind supposed to be superseded by multi-item selection. I don't find the "butcher everything" all that useful since mostly I'm just smashing corpses, and for hunting I would probably hunt one or at most few animals at a time. There are hotkeys for individual butcheries, and even without muscle memory about those it's just two extra key presses compared to what it's like now.

For furniture deconstruction, I think it makes sense to have the option in a more destruction-oriented menu than in a construction-oriented menu. We give it a hotkey whereas now it's missing one, and not being in a tabbed screen, you don't have to go hunting for it every time.

There are miscellaneous extractions, clearings and removals also moved into here. It's the same arguments as with furniture deconstruction, though with less importance since they are less used options in my experience.

### Do on every object

You may have noticed two extra options, "Do on every object on current tile" and "Do on every object on all nearby tiles". I thought about what to do with the options "Butcher everything", "Disassemble everything once", "Disassemble everything recursively" and "Cut up everything". One thing that absolutely wasn't to my liking is doubling the number of options in the menu by having everything have its own individual "x everything" equivalent. And especially the "Butcher everything" felt a bit problematic, seeing how it would kind of follow a menu structure of "item (everything) -> action" whereas every other option had an action already on the top level of the menu, even if it also had the item (everything) specified in these cases.

I never felt these were particularly descriptive about what they meant, and thus I elaborated further that it is taking place on [the ground of] the current tile, or you could also have it affect every surrounding tile as well. The latter option has potential to be implemented at a later time but I don't THINK it's going to be a substantial trouble to have it in from the start if the singular tile variant is already going to be in.

Now, sure these options go counter to the "action -> item" flow, but I didn't want to force making the multi-selection of what to disassemble/whatnot available just yet, and besides there's precedent in the current system. It's mostly just expanding on the current system, meaning you could choose to for example deconstruct all furniture around you with this. Thus, I doubt it would be all that controversial.

I considered leaving out "Disassemble everything recursively", but I think there were bound to be some people who were going to object.

### Hotkey justifications

For hotkeys, I mostly tried to go for minimal damage to muscle memory, but there was a conflict between "Dissect corpse" and "Disassemble everything recursively". I reasoned that with the "probably at some point" coming multi-selection in the disassembly screen the "Disassemble everything once" and "Disassemble everything recursively" weren't going to be as necessary going into the future, and thus gave the "d" hotkey to dissect corpse instead. The first letter of "recursive" is an easy enough mnemonic and "r" is one key away from "d". I thus personally feel it's the best option to solve that keybinding conflict.

The "Do on every object" actions are sort of new options so they got new hotkeys assigned that I felt made sense.

I did consider changing "Quick butchery"'s hotkey to "q" to make the action sequence "Do on every object on current tile" -> "Quick butchery" a bit easier on the fingers. However, I guess I'll leave it up for debate if it should be changed. I don't tend to butcher a whole lot in one go, so it's not that big of a deal for me at least.

### Dissect corpse

There is one special case for an option that requires some extra handling, and that's the Dissect corpse. I think that the proficiencies under "Dissecting may yield knowledge of" could be treated as items in the second screen, or if that seems too dumb, it'll need its own menu. Probably the latter option isn't too hard since there's already one for it, just the description would be redundant to have there. So, keeping a current-style menu for dissection is what I'd suggest.

### Describe alternatives you have considered.

A tabbed disassembly menu was one I seriously considered. And it's not outright even incompatible with this feature request if someone feels it's a desirable addition some time in the future. However, when I started considering "what's special about the butchery menu, and what's special about the deconstruction", I noticed that those provide descriptions for actions. Adding long descriptions to actions on something resembling the disassembly screen would probably not work on small or maybe even reasonably sized screens, and even more so if you also add tabs to the mixture. No, it would be too messy of a screen even for those that could fit it all there, is how I'm looking at it.

I also considered if the butchering / disassembly screen could be improved to be more along the lines of the dissassemble items screen, and outlined big parts of my reasoning against that in the "Is your feature request related to a problem" section. That screen wouldn't be able to accomodate all the other forms of "destruction features" by itself; it would be just unmanageable. A good filtering system could be doable if it was just for items, but I felt like having the destruction features in one menu was better and thus a filtering system would also have to accomodate all that making it even more unwieldy. Sure, you could just not move the construction stuff anywhere from where they are now and just focus on butchery, cutting up and disassembly, but even that feels a bit much. And you'd still be missing features from the disassembly screen, unless taking great pains were taken to reimplement them, but then we'd have a horribly bloated interface and it'd be hard to find the option you wanted to do... and you might as well have just coded my system at that point.

And yeah, my menu revamp suggestion still isn't exactly for "easily comparing cutting up an object and disassembling an object". However, this is more like a compromise between being user friendly when you already know you want to either disassemble or cut up items, and being able to see their results. Right now results for cutting up aren't available as far as I can tell. Really anything is an improvement to that. You could have the info in the full item description if it was really desired. But I think a larger user experience revamp was warranted, my suggestion trying to be it.

**Comment by toweroglass** [comment]
I think a note that says "this item can be cut down into it's basic components" would be preferable to an exact disassembly recipe that shows the exact yield. currently it is based on weight and relevant skill. this is very different to the disassembly recipe where you take the time to salvage as much as possible, threads and all.  This doesn't really need to change but i can see where it might not be obvious that cutting is available and what it does.

a menu similar to the washing kit menu would be pretty sweet, where you could toggle which items you would like to disassemble with the total time calculated in the top right. usually these are the calculations i do in my head where i'll be like ok these items are reasonable, but i'll just cut up that item that will take 8 hours to disassemble. 

That's all i really have an opinion on. My butchery thoughts are that i would like to be able to quickly see that a goose that i field dressed is now a "carcass" without having to select it and see the option is now gone. it's easy to remember which one in the list you've done but seems a little unnecessary.

**Comment by Zireael07** [comment]
My thoughts are that the issue title and the actual content don't match. The actual content is very broad while the title makes it seem like you want every item to be disassemble-able

**Comment by MikkoMMM** [comment]
The title was a leftover from a train of thought, and maybe even then not very descriptive to what I was thinking. I'll maybe give it a more of a discussion feel, if that helps.

**Comment by MikkoMMM** [comment]
> I think a note that says "this item can be cut down into it's basic components" would be preferable to an exact disassembly recipe that shows the exact yield. currently it is based on weight and relevant skill. this is very different to the disassembly recipe where you take the time to salvage as much as possible, threads and all. This doesn't really need to change but i can see where it might not be obvious that cutting is available and what it does.

Yes, it did also occur to me that maybe the exact yields shouldn't be something our character knows. It could be renamed to "Est. yield", or "Max yield". Also I'm not *really* feeling it's a must-have in the item's description, but I've used that info too at times. However, a character should at least be able to see the kinds of things an item is constituted of, even if not the exact amounts. I didn't really feel like taking a stance on that display for this, but I guess if it's something people want to drag into this conversation. Anyway, if disassembly has some kind of a display of this sort, to me it makes sense cutting up should also have some display or another. Nothing changes there, we still should know that if we cut here or there, that component will be unusable but we'd know we still get some materials that the item is composed of.

> a menu similar to the washing kit menu would be pretty sweet
It's very much along the lines of what I was talking about with the multi-selection. Okay, total time in the corner or so is to be added also then.

> My butchery thoughts are that i would like to be able to quickly see that a goose that i field dressed is now a "carcass" without having to select it and see the option is now gone
Hmm, does the order "action -> item" improve this for you? The field dressing should be greyed out à la the construction menu when requirements are missing, if there are no corpses that can be field dressed nearby.

**Comment by toweroglass** [comment]
> However, a character should at least be able to see the kinds of things an item is constituted of,
the materials the item is made of are at the top of the description. that is what you yield. my suggestion would be to put in the little description where you have the boiler plate info like "this item can withstand the abuse of combat" or whatever. 

that might be a bit too much and i think what might be more appropriate is more up to date documentation within the game to explain how these mechanics work.

> Hmm, does the order "action -> item" improve this for you? The field dressing should be greyed out à la the construction menu when requirements are missing, if there are no corpses that can be field dressed nearby.

I don't think so? I think my head just prioritizes it separate, but if i'm understanding you correctly ultimately your way would be easier. Would just need to completely upend how the system works.
