### ISSUE TITLE
Cataclysm DDA and Cataclysm BN interfere with each other in GNU/Linux system

### ISSUE THREAD

**Issue by Brensom** [CleverRaven/Cataclysm-DDA#68867]
### Describe the bug

If I have Cataclysm DDA installed, then when I try to install Cataclysm BN I get the error:
```
error: failed to commit transaction (conflicting files)
cataclysm-bn: /usr/bin/cataclysm exists in filesystem (owned by cataclysm-dda)
cataclysm-bn-tiles: /usr/bin/cataclysm-tiles exists in filesystem (owned by cataclysm-dda-tiles)
Errors occurred, no packages were upgraded.
```

### Attach save file

None

### Steps to reproduce

1. Install Cataclysm DDA
2. Trying to install Cataclysm BN

### Expected behavior

Both versions should install and not interfere with each other.

### Versions and configuration

0.G (DDA)
0.4 (BN)

### Additional context

OS: Arch Linux x86_64
Kernel: 6.1.59-1-lts
local/cataclysm-dda 0.G-2
    A post-apocalyptic roguelike.
local/cataclysm-dda-tiles 0.G-2
    A graphical post-apocalyptic roguelike.

https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3497

**Comment by ZhilkinSerg** [comment]
Let BN developers or Arch package maintainer do something with these ids.
