### ISSUE TITLE
Add hand staunching to consume menu

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68865]
### Is your feature request related to a problem? Please describe.

Staunching by hand is a fairly useful but still obscure feature.

### Solution you would like.

When bleeding only, add a "Staunch wound" to the consum(E) menu, as that is a convenient place used often to apply medications. Upon selecting this, the game should prompt the player to dispose of wielded item/empty their hands. The result could be a fixed period of time/attempts, or until bleeding stops. Or both, whichever occurs first, to prevent bleeding out while trying to staunch a wound that can't be staunched by hand. If the chance to stop the bleed per attempt is available, that could be used as a threshold instead, along with more granular log messages to give feedback regarding the effectiveness of staunching.

**Comment by sparr** [comment]
I came to post a different feature request around making the staunching possibility more visible, and support this one as well.
