### ISSUE TITLE
Scrapper quest for 75 charcoal should probably be for a larger volume

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#68878]
### Is your feature request related to a problem? Please describe.

I've just done a 25 magnetron quest for a scrapper (Fred Terrell, if the name is fixed), and the next quest is for 75 charcoal. The amount should probably be larger since charcoal has been revamped to have its units being a lot smaller than they were previously.

### Solution you would like.

Up the amount by whatever factor was used for the yield and other consumption.

### Describe alternatives you have considered.

Ignore it, as any change is likely to appear after I've fulfilled this quest.

### Additional context

Should it have been a bug report instead? This time the judgement call ended up with a feature request, but it's a coin toss.

**Comment by toweroglass** [comment]
even updating it to the correct calculation, that's an absurdly easy quest to fill after you've scrapped 25 microwaves....
