### ISSUE TITLE
Better Shocker Zombies Balance

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#68896]
### Is your feature request related to a problem? Please describe.

#63402 added `PARROT` special attack for all the shocker variants for balancing purposes, but.... it ended up like this.

![Screenshot_20230928_182923_Cataclysm_DDA_experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/ed49a44d-b779-4d13-b24a-b9d3f563d93c)

Since it emits noises, it was able to bring even more zombies. This basically turns incandescent husk into a killzone, and it made the shockers even more dangerous.

### Solution you would like.

Instead of the shockers making noise with volume of 20, it should be toned down a bit.
Also, someone in Communitycord suggested this idea.

![SmartSelect_20231025_212353_Discord](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/f6a245bb-36ce-4b3d-a541-44ab1bd92a1e)

### Describe alternatives you have considered.

Removing the `PARROT` from shockers entirely, but that would make me sad :(

**Comment by toweroglass** [comment]
i don't think the small swarm they create is overly difficult to deal with and if anything it can make navigating a dark street slightly easier as it bunches them up and you can go around. 

back in the day they made sounds too, i think they were even louder and drew a bigger crowd. i would be bummed if they stopped getting the crew together like they always have.

**Comment by TheSaddestGoomba** [comment]
That touches on something I've wondered about ferals and zombie dogs. Shouldn't they cry out and call nearby zombies?

**Comment by fairyarmadillo** [comment]
Parrots (but not parrot-at-danger) from same-faction monsters ought to be ignored.
