### ISSUE TITLE
Starting classes get sealed cans of half beans

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#68894]
### Describe the bug

Plenty of starting classes (professions) start with sealed containers that are only half-full. The most obvious being the Hobo-class, as portrayed here.

### Attach save file

N/A

### Steps to reproduce

1. Pick Hobo-class
2. See how canned beans are only half-full

### Expected behavior

Having sealed cans be full...?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1466 (21H1)
- Game Version: 13e9e72 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by toweroglass** [comment]
damn, the poor tax is too real.

**Comment by oosyrag** [comment]
Duplicate #67634, thanks for your report.

There is an abandoned(?) attempt at resolving this in #67742, if anyone wants to pick it up or try a different approach.
