### ISSUE TITLE
corded powerdrill in workshop station: pocket with type (MAGAZINE_WELL) not found

### ISSUE THREAD

**Issue by Vaskritaya** [CleverRaven/Cataclysm-DDA#68901]
### Describe the bug

I've inserted a power drill into a workshop station, and receive this and another similar error one after another until i ignore it after interacting with the station, starting crafting, etc. The corded power drill also fails to work as a tool for crafting.

### Attach save file

[Swain-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13168040/Swain-trimmed.tar.gz)

### Steps to reproduce

1. load in. interact with the workshop station to your southeast
2. receive two repeating errors until you ignore with (i).
3. look in crafting menu and search for "t:power drill" to find recipes using a drill.
4. see that the recipes that explicitly need a drill don't "see" my power drill, only the drill press nearby.
5. unplug drill press to your east to absolutely confirm the power drill isn't being detected.

### Expected behavior

Power drills should work like any of the other tools in the workshop station.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 7e9d40f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

Game has been updated through several experimental versions. 

Additionally, this specific power drill had its cord extended, plugged in, retracted, etc. over the course of its use, since I used it well before I had a workshop station. I'm uncertain what specific action I took that broke it, if anything.

**Comment by Fiibii853** [comment]
Can confirm I've also encountered this in my own save

**Comment by TheRafters** [comment]
I'm playing on September 29th build, I encountered the same magazine_well error with a power drill attached to a workshop station.
