### ISSUE TITLE
[Xedra Evolved] Game silently crashes when EOC_VAMPIRES is called

### ISSUE THREAD

**Issue by SteelSirokos** [CleverRaven/Cataclysm-DDA#68906]
### Describe the bug

Game silently crashes when EOC_VAMPIRES is called. Attached save file loads at 0753.32. Game crashes at 0753.34, or if EOC_VAMPIRES is called manually.

### Attach save file

[CDDA-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13169533/CDDA-trimmed.tar.gz)

### Steps to reproduce

1. Load game
2. Wait 2 ingame seconds or manually trigger EOC_VAMPIRES through the debug menu

### Expected behavior

I expected the game not to crash

### Versions and configuration

build type: windows-tiles-x64-msvc
build number: 2023-10-25-1510
commit sha: 7e9d40ff85f2c50d868a88e98e83a99dff4d4c08
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/7e9d40ff85f2c50d868a88e98e83a99dff4d4c08

- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Pixel's Various Fuckery [Pix's Shit],
    World on Fire [World_on_fire],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Dorf Life [Dorf_Life],
    Tankmod: Revived [Tankmod_Revived],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    MST Extra [MST_Extra],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

The crash still happens with all third-party mods removed, and I can confirm that it does not occur if I remove all character traits relating to Vampirism before EOC_VAMPIRES is called.

**Comment by sparr** [comment]
Could this be an instance of https://github.com/CleverRaven/Cataclysm-DDA/issues/68909?
