### ISSUE TITLE
"Safe Place" not safe

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#68902]
### Describe the bug

Selected the "Safe Place" scenario in character creation. Despite the scenario stating that the starting location would be "devoid of the living dead", the farm I started on had zombies in the shed next to the house where I spawn.

### Attach save file

[Mind Progress_2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13168941/Mind.Progress_2-trimmed.tar.gz)
Farm

[Mind Progress_2-trimmed_2.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13169052/Mind.Progress_2-trimmed_2.tar.gz)
Freshwater Research Station

[Mind Progress_2-trimmed_3.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13169095/Mind.Progress_2-trimmed_3.tar.gz)
Cabin

### Steps to reproduce

1. Make a character on the "Safe Place" scenario
2. Select "Farm" in the location selection
3. Possibly repeat a few times, idk if this always happens or if it's random.

### Expected behavior

"Safe Place" starts should not have enemies very close by.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/265a84d4-a7f1-4224-8f50-2fcd593f05f7)
You're not supposed to be here!

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/2c0a5b8a-00fc-43cb-94d6-bc6928960c27)
Again??

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/f6d9bf94-e359-4503-99ff-cd10c801e79d)
Cabin

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 446e59e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Edit: it happened again, this time with a freshwater research station. Have added second save file and screenshot.

Edit 2: A THIRD TIME!! This time in a cabin; there were two zombies in the shed out back.

**Comment by oosyrag** [comment]
Thanks for checking, please keep updating if you're inclined to try all the possible locations.

Then there's the decision to either remove the zombies from the location, or to remove the location from the scenario.

There's also the third option of updating the scenario description. The location itself just says "Safe building", which is technically correct in these cases.
