### ISSUE TITLE
Mod idea - Allow player's character templates to show up as random NPCs 

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68912]
### Is your feature request related to a problem? Please describe.

Just an idea

### Solution you would like.

I have not explored the feasibility of implementing this. But it could potentially be a method for player's to share characters as a vaguely-kinda-sorta-pseudo-maybe can be called "multiplayer"

### Describe alternatives you have considered.

(option to?) Spawn them as ferals/can't be recruited. Your past selves have come to kill you.

**Comment by sparr** [comment]
The game Spore has a concept of "[massively single player]](https://spore.fandom.com/wiki/Massively_single-player)" based on this. Your single player game includes content from other people's single player games.

Expanding the idea a bit here, it could be character templates, or abandoned vehicles or bases, or the player corpses, or buildings in the state another player left them in (already looted, on fire, modified, etc)
