### ISSUE TITLE
Invalid overmap special id "FakeSpecial_house_09" error screen popped up

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68925]
### Describe the bug

Got this error when opening my save.

 DEBUG    : invalid overmap special id "FakeSpecial_house_09"

 FUNCTION : const T &generic_factory<overmap_special>::obj(const string_id<T> &) const [T = overmap_special]
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/generic_factory.h
 LINE     : 478
 VERSION  : 3101388

### Attach save file

[Hawk Point-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13178176/Hawk.Point-trimmed.tar.gz)

### Steps to reproduce

1. open the save attached.
2. error screen

### Expected behavior

not giving me that error screen.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 3101388 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13178191/debug.log)

**Comment by MorvarchPrincess** [comment]
This happened to me when I updated my game, I assume its just one of the variants of house got removed and the game doesn't like that?
