### ISSUE TITLE
Planting cattail in fresh water on existing save crashes the game

### ISSUE THREAD

**Issue by ThePainkiller** [CleverRaven/Cataclysm-DDA#68921]
### Describe the bug

Having updated to latest experimental after #68664 on a pre-existing save, attempting to plant cattails via zone activities crashes the game with the following error:

```
 DEBUG    : invalid recipe id ""

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp
 LINE     : 68
 VERSION  : 3101388
```

### Attach save file

[Innawoods-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13173731/Innawoods-trimmed.tar.gz)

### Steps to reproduce

1. Assign a terrain with `SHALLOW_WATER` flag as a `Farm: Plot` zone with cattail seeds as its designated product
2. Press `O` to bring up zone management and pick `Farm plots` option
3. Debug error mesage shows, game crashes to desktop

### Expected behavior

I expected cattails to be sucessfully planted on terrain with `SHALLOW_WATER` tag without crashing to desktop.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1294508/b4d81b30-99fc-4bcc-b4e9-745556d41bde)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1294508/f68f25f1-357e-4de7-8073-43ce5cfcb8af)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1294508/e1d19114-153f-490c-888f-6252cac69508)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1294508/126baf79-a3ce-4e9c-bda2-9e90d6a62d2f)

### Versions and configuration

- OS: Windows 10 Enterprise LTSC 64-bit SP1
- Game version: 3101388 (tiles) build 2023-10-26-0314
- Ingame language: English
- Mods loaded: Innawood, Mythical Martial Arts, Alternative Map Key, Extra Mutated Scenarios, Translate Complex Dialogue, sees-player-run-crouch-bleed-icons-retrodays, Disable NPC Needs, Portal Storms Ignore NPC's, SpeedyDex, Stats Through Skills, Stats Through Kills, Tamable Wildlife, Bombastick Perks, Zetsukaze's Hair - 0.E Edit

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13173912/crash.log)

**Comment by oosyrag** [comment]
What version did you upgrade from?

**Comment by ThePainkiller** [comment]
> What version did you upgrade from?

I tend to udpate the game daily before launching, so assume any version before that one.

**Comment by oosyrag** [comment]
I was unable to reproduce this with a fresh save migrated to an October 24 build from cdda-windows-tiles-x64-2023-10-14-1823 (e4c0fba), but did confirm that the segfault crash occurs with the same October 24 build when using OP's attached save file.

The PR was merged in https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-10-16-2252

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4699-g1d541b4973-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

I'm going to tentatively guess that a mod is involved? Although nothing is jumping out at me in OP's mod list.
