### ISSUE TITLE
Mutation conflicts with No Legs

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68928]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/26992604/5bdb0c01-66dc-43aa-8e50-120b6c8614f7)

Padded... leg stubs?

### Attach save file

NA

### Steps to reproduce

This was a random character, but I'm sure other similar cases could easily occur.

### Expected behavior

The no legs mutations could probably use a list of conflicting mutations/bionics.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4699-g1d541b4973-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by MNG-cataclysm** [comment]
It's a feature, not a bug.

(I'll fix this one soon.)
