### ISSUE TITLE
Item names sailing off into the sunset, never to be seen again. [$5]

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#6893]
Names on items keep getting longer and longer and longer, at first it wasn't a problem, but playing on a widescreen monitor I went to check the charge on an "reinforced thermo electric balava" that fit. It reads "reinforced thermal electric balaclava (fits) (r" which wouldn't be so much a problem if it weren't for the fact that I don't have the vaguest idea what the charge is.

Can I suggest we use the item screen and have it display item condition, battery, and other information there rather than try to cram all of it into the name? Or at least mirror it there so it's visible when the names are a mile long?

**Comment by KA101** [comment]
Someone might want to tell Narc about this.  I'm thinking eligible.

**Comment by narc0tiq** [comment]
Wasn't my change, and I'm on mobile so I can't look it up easily. The item health bars are definitely eligible, though.

**Comment by KA101** [comment]
Thought those were yours.  >_<

**Comment by OzoneH3** [comment]
There's a bount on this Oo.

Can you just move the 5$ to another ticket like the first Z-Level or something?

**Comment by kevingranade** [comment]
I believe the person who claims it can do that if they want, the only way
to reassign bounties is to wait for them to expire, and this isn't a
cleverraven bounty, so we can't do that.

**Comment by drbig** [comment]
Can this be closed or is the bounty business blocking?
