### ISSUE TITLE
Inform player they could staunch bleeding by pausing with empty hands

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#68939]
### Is your feature request related to a problem? Please describe.

The character's ability to reduce bleeding by pausing with empty hands can be discovered accidentally, but is not apparent otherwise.

### Solution you would like.

When bleeding, occasionally give a message suggesting the player stop moving. If they pause with full hands, give a message suggesting they empty their hands, probably with a cooldown between such messages.

**Comment by sparr** [comment]
#68865 has a different suggestion for exposing this capability

**Comment by sparr** [comment]
I suspect the typical player spends virtually no time with empty hands, so they might never encounter this powerful mechanic.

**Comment by PatrikLundell** [comment]
So you're saying dropping the weapon and waiting is more powerful than just waiting (which produces a message indicating you're trying to staunch the bleeding)? Didn't know about that...

**Comment by oosyrag** [comment]
> So you're saying dropping the weapon and waiting is more powerful than just waiting (which produces a message indicating you're trying to staunch the bleeding)? Didn't know about that...

I wasn't aware you could staunch with something in your hands.
