### ISSUE TITLE
misaligned stairs in subway station

### ISSUE THREAD

**Issue by Vaskritaya** [CleverRaven/Cataclysm-DDA#68957]
### Describe the bug

The stairs in the aboveground section of this subway station are misaligned with the section under it, leading to some strange behaviors. I was able to attack enemies in the maintenance room from the stairway above, since I could "see" down to them, despite them not actually being present if I peeked or stepped down.

### Attach save file

[Swain-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13194765/Swain-trimmed.tar.gz)

### Steps to reproduce

using attached save:
1. load in. try going up/down the subway stairs. issue will become obvious.
2. note the maintenance room on the first sublevel, with bile splatter, brute corpse, etc. these enemies were killed from the northernmost three stairways of the aboveground station.

from fresh save, untested:
1. find station facing a different direction than the subway lines in worldgen?

### Expected behavior

Stairs should obviously be aligned. Perhaps variants of aboveground stations should exist for the purposes of having stairs match to the underground sections?

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22992007/a00b2ccb-b973-40d3-bb3a-f334157e0167)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22992007/36c63f3a-14ed-4e74-80e7-4f1752886c29)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: ce449ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

The station was actually generated in an earlier experimental, about a week or so ago, but unless I missed something, this wasnt noticed or fixed between then and now.

Also, on further inspection, it seems like the subway spawned somewhere where it COULD HAVE faced the proper direction. If it faced the road to its north, everything would have lined up. Perhaps this is relevant?

**Comment by ZhilkinSerg** [comment]
Related to https://github.com/CleverRaven/Cataclysm-DDA/issues/49162 and #45180

**Comment by AmarinReyny** [comment]
I've noticed in my own playthroughs that the sublevel is always generated facing North, regardless of what directions the other Z levels are facing.

**Comment by Procyonae** [comment]
#68496 should fix this when I get back to it
