### ISSUE TITLE
Some references

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#68964]
### Is your feature request related to a problem? Please describe.

I think it would be cool for there to be some items or gear in reference to other pieces of media, we've already got some, like the golden fiddle, but there should be some more of them around.

### Solution you would like.

Putting some of them in, for instance:
- A Vault Jumpsuit (Generic? Maybe w/ randomized numbers)
- Arstotzka Passport
- Bucket (Stanley parable)
- Giant Spoon
- Montag's Helmet (Fahrenheit 451)
- Doom guy action figure
- Bioshock drill
- TF2 Mini regular turret (Maybe you could place it down & have it shoot BBs or something?) (Not the mini turret, but a smaller version of the regular turret)
- Spiffo Plushie
- Coral Paperweight (1984)
- Chicken mask (Hotline Miami)
These shouldn't be actual weapons or gear, more like collectables

**Comment by a-chancey** [comment]
We're actually moving away from explicit references to other games

**Comment by PGR-14** [comment]
Oh sorry, didn't know
