### ISSUE TITLE
Gun stores can stock useless used .22 LR casings

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68968]
### Describe the bug

Gun stores sometimes spawn with large numbers of casings for hand loading, but .22 LR casings cannot be reloaded unless they're unused with their primers intact. There isn't any reason to stock the regular unusable casings instead of the unused ones.

### Attach save file

N/A

### Steps to reproduce

1. Go to a bunch of gun stores, see .22 LR casings that are unusable.

### Expected behavior

Unused .22 LR casings should be in gun stores, instead of ones with their primers used.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/7081f074-2cd7-4487-9406-2ef7a390986f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: f1ba0a7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Vaskritaya** [comment]
maybe a mistake of https://github.com/CleverRaven/Cataclysm-DDA/pull/63699 , or perhaps a following pr that didnt catch the memo that such a change was made?
