### ISSUE TITLE
Milled Roasted Cattail Rhizomes Produces over 5k Flour

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#68978]
### Describe the bug

I milled 30ish Roasted Cattail Rhizome's and the end result was over 5k Wheat-Free Flour from my Wind Mill

### Attach save file

[Scott Lake-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13197220/Scott.Lake-trimmed.tar.gz)

### Steps to reproduce

1. I 100% put 30-ish Roasted Cattail Rhizome in my Wind Mill
2. I left it for a few days while I was out scavenging supplies.
3. Check the Wind Mill and it will cause 5k+ Wheat-Free Flour to be removed from the Mill

### Expected behavior

I dont think it should be 5+ wheat free flour from 30ish Roasted Cattail Rhizomes.

### Screenshots

![flour1](https://github.com/CleverRaven/Cataclysm-DDA/assets/100801849/e6e1c15d-ad29-4c47-ac09-255db4d8bc8e)
![flour2](https://github.com/CleverRaven/Cataclysm-DDA/assets/100801849/ca587ee5-5ec2-4f18-bc99-0687ac5d6648)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 32e562d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by oosyrag** [comment]
Duplicate #68701, a fix is in progress. Thanks for your report!
