### ISSUE TITLE
Significant game slowdown when a vehicle engine is turned on

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#68982]
### Describe the bug

The time it takes for the game to pass 5 minutes via "waiting" becomes significantly longer if the player is inside a vehicle with an engine running.

### Attach save file

[Mainsave-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13198031/Mainsave-trimmed.tar.gz)

### Steps to reproduce

1. Upon loading the save, you'll be inside a vehicle, on the same tile as the controls
2. Try waiting and see how fast the ingame time passes
3. Turn on the engine and repeat the process, see that the time it takes for the game to process 5 minutes increases significantly when the engine is turned on

### Expected behavior

I did expect the engine to slow down the game, but not to *this* point

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: ce449ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Railroads [railroads]
]

**Comment by GuardianDll** [comment]
/confirmed
With nothing in bub:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/90353cb9-850b-49f0-b3f4-56bf8c7752ba)

with car in bub:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/bb0364f8-5d3c-4beb-9e4c-ca35bcd8f74a)

with engine on in bub:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/116b38b7-c74a-4da5-b522-b6cf96da7de6)

**Comment by CoroNaut** [comment]
Extra time from the vehicle just existing? We might be able to separate vehicles that are currently doing something from vehicles that aren't doing anything. That way, we can process the vehicles that aren't doing anything much faster, or skip over them entirely. For example, if there is no power generation/depletion, no broken gas tank leaking gas, etc, then put it into a list that the game could just skip over. Vehicles that are charging or running or have lights on, etc, can be processed normally.

**Comment by Karol1223** [comment]
For the record - if Guardian used my savefile to test this, the vehicle has solar panels and several electronics turned on which probably is the reason for the extra time for it just existing. If Guardian *didn't* test it on my savefile that's a bigger problem, though.
