### ISSUE TITLE
[MoM] Make Concentration Trance, Mood Stabilization, Speed Reader etc. toggleable

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#68983]
### Is your feature request related to a problem? Please describe.

I like MoM a lot. I like that it has a lot of weird utility powers, and I even (kind of) like the commitment to psychic powers being random and unpredictable.

However, this doesn't apply to the powers that interact with learning. It is extremely annoying to babysit Concentration Trance as it runs out over and over again in the middle of a long craft. You can't even get into a rhythm, because the duration is different every time. It's also not really practical to cast it over and over to build up a long enough duration to begin with, because subsequent casts only increase the current duration by 10%, and at any rate the maximum duration is still too short for any substantial training session. Speed Reader is even worse, because it doesn't list the remaining duration and has no clear UI indication that it's run out, just an easily missable message zooming past in the log..

### Solution you would like.

Make the relevant powers toggleable, so they stay on until you turn them off. Concentration Trance already has this functionality to allow the player to drop it when the debuffs become a problem, but it still has limited duration. Probably still have a max duration as a sanity check, but make it something really substantial, like a full 24h.

In order for this to not make those spells free, roll for Drain every so often. I think you could probably use EOCs to replicate the behavior of casting the spell over and over, rolling for drain after a random interval with bounds determined by spell level, but it would probably be fine to just do it statically every hour or so.

I'm not concerned about the stamina cost for repeat casts. It's irrelevant for out-of-combat casts, and you'd very rarely activate these spells after combat starts.

### Describe alternatives you have considered.

Increase dur_add_perc to 100 and max_intensity to something like 24h on the relevant effects so you can just cast it a bunch of times at the start of a session. This would be very simply and it's nice to not have to clutter the menu with a bunch of additional (Remove) spells, but it feels a bit clumsy and I don't think it would work for Speed Reader because it's EOC-based.

### Additional context

This might be a positive change for other long-term buff powers as well. But it's a much less pressing issue for those, because unlike the learning powers you're unlikely to turn them on and then immediately spend 6 hours doing an activity, so it might not be worth cluttering the menus.

Although now that I'm thinking about it, Cloak of Warmth and Thermogenesis strike me as powers you might want to continually re-up while e.g. butchering an animal in the winter or busting down a wall in an ice lab. There are probably others, but I don't have that much experience with MoM yet so I can't name any more off the top of my head.

**Comment by Standing-Storm** [comment]
I originally wanted to do this for out of combat utility powers but did it know how at the time. As you say, I should be able to set up Drain rolls with random intervals (increasing as the power is leveled) using EoC. Stamina cost could then probably just be eliminated entirely and replaced with a small max stamina debuff per effect you have on (representing the concentration required), and each power could be retooled to turn on if it’s off and then then off if it’s on while on causing initial Drain if you’re turning it on.  

A lot of JSON fiddling but I think I already know how to do all of it.
