### ISSUE TITLE
[MoM] "Enhance Strength" mechanics obtuse and unintuitive

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#68981]
### Describe the bug

I've been trying to use the Telekinetic power Enhance Strength, and it took a long time to get to grips with it due to its mechanics being (imo) unnecessarily confusing. Here are a few of the problems I had:

- If you're not wielding anything, the Enhanced Strength item spawns in your hands. It works if it's anywhere in your inventory, but this isn't made clear anywhere, so I got the impression I had to wield it.
- If you _are_ wielding something, it gets put into your inventory where it might end up on the second page, in a hidden container or otherwise obscured, or else fill up a holster and cause problems. You can't use it while naked and wielding a weapon, for example. At least not without filling up your lifting field.
- The value of the Strength increase is based on the level of several other powers, but this isn't stated anywhere so it's easy to get frustrated because levelling it up doesn't seem to do anything

If we want to preserve the "drop to cancel" functionality, I think it would be better if it was wearable. Then it would never end up in weird places, would (almost) always be clearly visible in the inventory and there would be much less confusion about where it needs to be to work. But honestly, it feels super weird to manipulate your psychic powers by going into your inventory and moving an item around, so I think it would be better if it worked like Concentration Trance with a separate power to turn it off.

Also just add something to the description about how it relates to other powers.

### Attach save file

n/a

### Steps to reproduce

Use "Enhance Strength"

### Expected behavior

Powers work in as clear and intuitive a fashion as possible.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/4edb57e9-a34e-40bf-a67a-d52c6397bacd)
Hiding in the back half of my inventory.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 32e562d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I initially started writing up this bug report because it didn't seem to be working at all, but now I can't replicate that so I may have just been getting bamboozled by the usual enchantment delay.

**Comment by GuardianDll** [comment]
@Standing-Storm was it an attempted to prevent players from fighting with this buff? I think you can just replace it with straight str buff, and make EoC event, linked to "player deal damage", and simply remove the effect if event is triggered

**Comment by Standing-Storm** [comment]
That’s exactly what it was and that’s a great solution to the problem. I can implement it as part of working on #68983 too so appropriate buffs (Speed Reader, Concentration Trance, etc) are automatically turned off in combat
