### ISSUE TITLE
[MoM] Power practice recipe not awarding new powers correctly

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#68996]
### Describe the bug

Using practice recipes to level up your existing spells does not award new powers at the appropriate levels. Sometimes they seem to be added after a save and quit, but I've now I've encountered a situation where they are not.

In the attached saved, I leveled up Phase (teleport_phase) through the practice recipe to lvl 9. At this level, it's supposed to grant you Extended Stride (teleport_stride), but it didn't. I used the practice recipe and then cast the spells a few times so there's only 19 exp left until the next level, and made the trimmed save. Casting Phase once levels it up to 10 and grants Extended Stride. Using the practice recipe levels it up to 10 but does not grant Extended Stride, even after a save, quit and load.

### Attach save file

[Mind Progress_2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13199207/Mind.Progress_2-trimmed.tar.gz)

### Steps to reproduce

1. Level to within 1 cast of leveling a spell to the point where it grants the next spell
2. Save
3. Compare leveling up via casting and via practice recipe

### Expected behavior

New spells are granted as normal regardless of how the final xp was earned

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/d6b25e2a-3486-476a-b137-03ee19352581)
Level 10 Phase; no Extended Stride

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 32e562d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

**Comment by Daemonkai** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/66772
same as this?

**Comment by GuardianDll** [comment]
please update your game and test again, this bug supposed to be fixed in #68946, it was merged 2 days ago (your version is three days old)

**Comment by Terrorforge** [comment]
Oh, whoops. I thought I had a more recent version, but it seems I had a disagreement with Catapult. It is in fact fixed on revent versions. My bad.
