### ISSUE TITLE
You cannot wear headphones

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#68991]
### Describe the bug

You cannot wear headphones

### Attach save file

N/A

### Steps to reproduce

1. Acquire headphones
2. Be unable to phone your head

### Expected behavior

To be able to wear headphones

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 033a9b7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by KeremBabaG** [comment]
they aren't a clothing item that's why. Even if they were what would their use be? We have mp3
