### ISSUE TITLE
Some books are not stored to e-devices after the multiselection update

### ISSUE THREAD

**Issue by thoefut** [CleverRaven/Cataclysm-DDA#69012]
### Describe the bug

Some books are not copied into e-devices for some reason

PR in question: https://github.com/CleverRaven/Cataclysm-DDA/pull/68880
Not sure if the breakage is a direct result of the changes, but only noticed it after the update that had it

Can not provide the exhaustive list from the get-go, but encountered more than one
One of the affected books is the **DIY Compendium**
Not sure what affects the availability for storage, would require some code investigation

Before the multi-selection update all books afaik had no issue with being stored to e-devices

Attached a save file with everything ready for repro, reproduction can be done in debug world

Debug report for OS version and game version is from the debug world that has no mods, savefile when I first encountered it has quite a few, but they are all mainline

### Attach save file

[A Great Journey-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13207183/A.Great.Journey-trimmed.tar.gz)

### Steps to reproduce

Can be reproduced from debug world:
1. Spawn an empty e-ink reader and battery for it and reload it
2. Spawn a DIY Compendium manual
3. Try storing the Compendium  into e-ink reader
Notice charge and time is used, but log shows 0 books were stored and you can try to store the DIY again 

### Expected behavior

All books that are available for storing (not present in the e-device reader at the moment of selection) are stored after the selection confirmation

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24360038/921fb4f1-2ffa-4e08-9ef6-53d3ac2264c0)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown> (its an archlinux running in distrobox under Fedora Silverblue, should not affect the stuff here)
- Game Version: e497f5a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by thoefut** [comment]
I do believe I also had this issue with the First Aid booklet when I started this save, but in the debug when I tried to reproduce it it got copied correctly (with the DIY and FA Booklet selected for copy at the same time) :shrug:

**Comment by Lord-Helmchen** [comment]
one of the E[redacted]'s armor blueprints is also affected
