### ISSUE TITLE
New Pride Stockings spawning on Reenactors

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#69015]
### Describe the bug

Selecting the Historical Reenactor or Ahistorical Reenactor professions cause the player to spawn with the new Pride-styled Stockings.

### Attach save file

N/A

### Steps to reproduce

1. Go to character creation menu
2. Select “Survivor” Scenario
3. Open professions tab
4. Scroll down to the Historical Reenactor and Ahistorical Reenactor professions

### Expected behavior

They should only spawn with white stockings, maybe brown or black as well

### Versions and configuration

-OS: Windows 10
-Mods: Bionic Professions, Slow Fungal, Disable NPC needs, Stats through skills.

**Comment by kevingranade** [comment]
We're accumulating a sizeable history of people taking issue with random item variations in different contexts,  but the only time it comes up is when it's representation-related.

As such I am extremely disinclined to make this kind of change.
