### ISSUE TITLE
[Aftershock Exoplanet] Crashing ship anihilated on save load

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#69030]
### Describe the bug

Upon reloading a save in the Emergency Evacuation start everything in the ship got destroyed

### Attach save file

N/A

### Steps to reproduce

1. Start an Emergency Evacuation scenario in Aftershock Exoplanet
2. Save and quit
3. Reload
4. Everything is destroyed

### Expected behavior

Everything is the same as it was when I saved upon reload

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/38fadaf3-b477-4405-b6de-461bf3c7e025)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/5e0f8ecb-65ef-4001-9698-98932c5a28ef)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4634-g9fc0c62841-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by MNG-cataclysm** [comment]
/confirmed, had this same issue with my game.

**Comment by MNG-cataclysm** [comment]
I've figured out what's causing it. It's the self-destruct system spawned with the ship. That same item doesn't trigger in-game until the save-load cycle is done.
