### ISSUE TITLE
Wetsuits have way too much defense due to overtuned Neoprene values

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69037]
### Describe the bug

A wetsuit has 9.2 bash armor. Since bashing is by far the most common damage type, this makes it about as good as chainmail. Given its low encumbrance, it's arguably better than the lighter plate armors.

This is obviously nonsense, and presumably caused by the defensive values of the Neoprene material being much too high.

### Attach save file

Trivially reproducible

### Steps to reproduce

1. Spawn wetsuit
2. Look at its stats

### Expected behavior

Swimwear does not compete with dedicated metal armor in terms of protective value.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/38310dd7-a17e-4228-affc-dee0fef71517)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 6e8a5bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

**Comment by kevindenham** [comment]
I also think this should be looked at again. 9.2 bash resistance for a wetsuit makes no sense at all. What makes it even worse is that it's worn close to skin, so it's stacked with your main strapped on armor. As @Stephen2 mentioned, if you come across a dive shop on day one, wetsuit+dive gloves+diving socks+riot gear makes you nearly invisible against early game zeds.

**Comment by IdleSol** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/c0855217053139af79f888c04d5032813bc78b90/data/json/items/armor/swimming.json#L774-L777

Neoprene:
https://github.com/CleverRaven/Cataclysm-DDA/blob/c0855217053139af79f888c04d5032813bc78b90/data/json/materials.json#L1491

nylon:
https://github.com/CleverRaven/Cataclysm-DDA/blob/c0855217053139af79f888c04d5032813bc78b90/data/json/materials.json#L2360

bash: 0.2 x 1 + 3 x 3 = 9.2

There are two ways to change the protective properties.

1. Change the thickness of the material. But this is contrary to the actual models. (A quick search says that the thickness can be 3, 5, 7 and 9 mm).
2. Change the protection value for the material. Which will affect all things made from it.

**Comment by Zireael07** [comment]
Is the "thickness" in mm?

**Comment by IdleSol** [comment]
I didn't understand the question. The thickness of the material is in mm. Or did I translate it wrong somewhere?

**Comment by IdleSol** [comment]
![pict 1](https://github.com/user-attachments/assets/122161e3-e937-42a8-bf6e-45cc0f7a56f4)
```
    "id": "test_wetsuit",
    "type": "ARMOR",
    "name": { "str": "ALT wetsuit" },
    "description": "A full-body 3 mm thick neoprene wetsuit with nylon lining.",
    "weight": "825 g",
    "volume": "5 L",
    "price": "120 USD",
    "price_postapoc": "5 USD",
    "material": [ "neoprene", "nylon" ],
    "symbol": "[",
    "color": "dark_gray",
    "armor": [
      {
        "covers": [ "torso" ],
        "material": [
          { "type": "nylon", "covered_by_mat": 100, "thickness": 0.7 },
          { "type": "neoprene", "covered_by_mat": 100, "thickness": 2.5 }
        ],
        "coverage": 100,
        "encumbrance": 10,
        "volume_encumber_modifier": 0.0
      },
      {
        "covers": [ "leg_l", "leg_r", "arm_l", "arm_r" ],
        "material": [
          { "type": "nylon", "covered_by_mat": 100, "thickness": 0.2 },
          { "type": "neoprene", "covered_by_mat": 100, "thickness": 2.0 }
        ],
        "coverage": 100,
        "encumbrance": 7,
        "volume_encumber_modifier": 0
      }
    ],
    "//": "Pockets like here: https://mytriathlon.co.uk/zone3-versa-womens-wetsuit---ex-rental-cat-1/",
    "pocket_data": [
      {
        "pocket_type": "CONTAINER",
        "max_contains_volume": "500 ml",
        "max_contains_weight": "1 kg",
        "moves": 130,
        "max_item_length": "11 cm",
        "watertight": true,
        "description": "Back pocket."
      },
      {
        "pocket_type": "CONTAINER",
        "max_contains_volume": "500 ml",
        "max_contains_weight": "1 kg",
        "moves": 130,
        "max_item_length": "11 cm",
        "watertight": true,
        "description": "Back pocket."
      }
    ],
    "warmth": 30,
    "environmental_protection": 10,
    "flags": [ "VARSIZE", "WATER_FRIENDLY", "WATERPROOF", "SKINTIGHT" ]
```

**Comment by kevindenham** [comment]
Thanks IdleSol,

I think that's on the right track, I apologize since my previous numbers were rough approximations. 

If we're going with the same principal that non-torso regions are 1mm thinner, we'd probably want to tweak what you have so the total values of 80% neoprene and 20% nylon amount to 3mm and 2mm respectively. So something like this perhaps:

"armor": [
  {
    "covers": [ "torso" ],
    "material": [
      { "type": "nylon", "covered_by_mat": 100, "thickness": 0.6 },
      { "type": "neoprene", "covered_by_mat": 100, "thickness": 2.4 }
    ],
    "coverage": 100,
    "encumbrance": 10,
    "volume_encumber_modifier": 0.0
  },
  {
    "covers": [ "leg_l", "leg_r", "arm_l", "arm_r" ],
    "material": [
      { "type": "nylon", "covered_by_mat": 100, "thickness": 0.4 },
      { "type": "neoprene", "covered_by_mat": 100, "thickness": 1.6 }
    ],
    "coverage": 100,
    "encumbrance": 7,
    "volume_encumber_modifier": 0
  }
]

**Comment by IdleSol** [comment]
![pict 2](https://github.com/user-attachments/assets/ef7c8336-90e1-4c1b-a9bd-36419bd6dae3)

Not that it will change much.

**Comment by kevindenham** [comment]
Thanks. I looked into it a bit more and thickness ratings for wetsuits are indeed just the neoprene, with nylon just being extra, which is probably why the current neoprene swimwear was 3mm + 0.20. I would say for realism sake, and to avoid having to also modify every other piece of swimwear to be consistent, the torso should probably stay 3mm neoprene while the extremities stick to the 3mm/2mm real life ratio. Sorry for the confusion.

**Comment by Terrorforge** [comment]
Okay so quick glance it's not actually just the wetsuit;[ EVERY clothing item made out of Neoprene](https://cdda-guide.nornagon.net/material/neoprene) has absurd defensive values. Even the wetsuit shorts have 3 bash for 1 encumbrance, and the Thick Wetsuits are straight up competing with plate armor.

The correct solution is to reduce to armor values of the material, not fiddling with the thickness of individual items.
