### ISSUE TITLE
Can't make dedicated sprite for graffiti using `&`

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#69032]
### Describe the bug

Try to make a sprite for `Escape Pods & Vehicle Bay` but neither `graffiti_ESCAPE_PODS_VEHICLE_BAY` nor `graffiti_ESCAPE_PODS_&_VEHICLE_BAY` work as Ids

### Attach save file

N/A

### Steps to reproduce

Try to make a sprite for `Escape Pods & Vehicle Bay` 
Call it `graffiti_ESCAPE_PODS_VEHICLE_BAY`  > doesn't show in game
Call it `graffiti_ESCAPE_PODS_&_VEHICLE_BAY`  > doesn't work either

### Expected behavior

Some id work and the sprite shows up

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4634-g9fc0c62841-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Aftershock: Exoplanet [aftershock_exoplanet]
]

**Comment by Qrox** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/6c2c30c4cb7f38d189ab2e1677ca6187e4134c4e/src/cata_tiles.cpp#L3556-L3558

I think `graffiti_ESCAPE_PODS__VEHICLE_BAY` will work.

**Comment by Fris0uman** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/6cbd225e-dcf6-47a7-8f28-d7acb19a3e43)
Yep it works. I'll update the doc and close this issue
