### ISSUE TITLE
Weak alcohol yields more ethanol from distillation than strong alcohol

### ISSUE THREAD

**Issue by Uranoclaire** [CleverRaven/Cataclysm-DDA#69045]
### Describe the bug

The recipe for ethanol distillation asks for more strong alcohol than weak alcohol to produce the same volume of ethanol.

### Attach save file

N/A

### Steps to reproduce

1: Know the recipe for ethanol
2: look at components required
3: observe that you need more strong mixed than you need weak mixed for the same yield

### Expected behavior

Alcohol becomes increasingly more difficult to distill from a solution as its concentration lowers, while high proof alcohols like Vodka are trivial to distill ethanol out of. As such, I would have expected distilling from an existing high-proof source to be easier than from an equal amount of low-proof source.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/134988746/19b6b459-8297-4613-8d9f-c3e397347f7d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: e497f5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch]
]

**Comment by mqrause** [comment]
1 weak mixed alcohol is equivalent to 7 strong mixed alcohol volume wise. So this is actually either 2.5L of weak mixed alcohol or 0.5L of strong mixed alcohol.

**Comment by Uranoclaire** [comment]
Ahhh, I see. My bad.
