### ISSUE TITLE
crash caused by opening door while on vehicle with merged power grid to solar panel appliance / buggy behavior with vehicles and appliance merged power grids

### ISSUE THREAD

**Issue by Froffy025** [CleverRaven/Cataclysm-DDA#69043]
### Describe the bug

merging power grid on vehicle causes vehicle to teleport oddly
merging power grid on solar panel with car causes opening a door on that car to crash
attempting to drive a car with a merged solar panel causes the solar panel to move with it

### Attach save file

[Bellefontaine-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13221446/Bellefontaine-trimmed.tar.gz)

### Steps to reproduce

1. place solar panel using construction menu
2. merge solar panel power grid with van power grid
3. attempt to open door

### Expected behavior

should still be able to open doors on merged vehicle
driving merged vehicle shouldn't cause the stationary solar panel to move

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 61146fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13221442/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13221443/crash.log)

**Comment by Froffy025** [comment]
also caused by closing the door lol

**Comment by redcrate** [comment]
I have also observed this in one of my games.
