### ISSUE TITLE
Water purification tablets are overpowered

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#69041]
### Describe the bug

It seems a single water purification tablet can be applied to any container of water to instantly purify the whole lot. This seems reasonable when applied to a small container but not for a 200L drum. 

Expected behaviour (realistic): A single water purification tablet can clean 1L water in a few hours. 
Observed behaviour in-game: A single water purification tablet can clean 200L water instantly. 

Suggested fix: Disallow usage on containers with more than 1L water. Change instant use to a recipe taking time - maybe with ingredients of 1 tablet + 1 liter.

### Attach save file

N/A

### Steps to reproduce

Fill large container with dirty water. Activate tablet from inventory, select container as target. Receive large quanity of clean water.

### Expected behavior

Tablets should clean 1L of water in 4 hours. Ideally this shouldn't take labour - just waiting. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19167795/cb5ad144-93a1-4f09-ba49-b9c5505a6f56)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 61146fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by PatrikLundell** [comment]
I think it would make sense to change the logic to be a crafting recipe where you take 4 units of water (1 liter) and one tablet to produce 1 liter of clean water. Such a recipe would result in the request for a container to put the clean water into and could be batched so you could process several lots of water in one go using several tablets.

The tricky part is the waiting, as the crafting system currently doesn't really support that. The work around used is to have the crafting create in process items, but these have the container being part of the item (locking you into using that container specifically)., which we definitely wouldn't want here.

The crafting system doesn't support "process what's inside the container" which would have allowed you to drop as many tablets as needed into the container (so you wouldn't need a new container for the clean water).

Certain container furniture (vats) have special interactions for fermentation, but again, the container is both fixed and "furniture" which isn't desired here.

**Comment by Vaskritaya** [comment]
maybe there could be a very quick recipe that turns 1L dirty water and 1 tablet into 1L "purifying water" or something to that effect. Then, maybe you could leverage rot timers or similar to have that become clean water over time?

While I've never messed with it, it's my understanding you can passively purify water by boiling now as well. Maybe the internal mechanics used there could be leveraged for the purifying->clean step as well?

**Comment by PatrikLundell** [comment]
You can indeed purify water passively by placing a pot with regular water on a fire. I only learnt about this half a year or so ago, but it does work.

**Comment by turco-ai** [comment]
Water purification tablets are a bit overpowered indeed, I calculated how much bleach they have on them based on their recipe and if I recall a single tablet could purify hundreds of liters if not more, putting them into 1L of water would probably give you bleach poisoning 😂
They effectively need to be completely changed including their crafting recipe which would also need some pretty big changes to chemistry crafts assuming no one has touched the tablets since I last checked them.
