### ISSUE TITLE
Grabbing zombies/enemies?

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#69055]
### Is your feature request related to a problem? Please describe.

A while back, I proposed an amendment to the brawling martial art, where you'd learn to shove/push your opponent with minimal damge, but a guaranteed push. Obviously, this idea of mine was shot down quickly, not just because it was unpractical from a gameplay perspective, but because it was plain bad...
But what if, instead of relying on the martial arts' system, we could implemented pushing around opponents through the grabbing mechanic?

### Solution you would like.

Implementing a system where you could, for example, grab a zombie and push it into a nearby trap or ledge, would be not only be a great addition based in realism, but a great situational action for certain scenarios. Everything from forcing opponents into traps to simply pushing zombies off of rooftops.
Of course, this mechanic would need to come with the usual variables, like the character's strength and flexibility, whether or not they're wielding something, the size and flexibility of the opponent, any injuries or other discomforts the character is feeling, etc, etc...
But ideally, I imagine the mechanic would essentially be the character grabbing their opponent like a piece of furniture, and then pushing/pulling them in the desired direction.

### Describe alternatives you have considered.

I also thought about ideas like forcing the zombies to drag along with you at the expense of some (attempted) limited damage, picking up particularly small opponents like zombie children and being able to toss them like rocks, as well as being able to move zombies like you would furniture/small vehicle. But what makes most sense to me, in the context of CDDA, is a simple system of grabbing and pulling/pushing opponents around one tile at a time, with the appropriate buffs/debuffs.

### Additional context

I'm fairly drunk as I write this, so if something is misspelled or otherwise feels out of place, take it with a pinch of salt. :)

**Comment by scanevaro** [comment]
I like the idea of having a grappling system, it makes sense to me. Also, I was just yesterday checking the Wrestler Background to see if it actually had some kind of grappling (it doesn't).

**Comment by EternalEmo** [comment]
Maybe allow the grabbing command to work on enemies as well, except it would fail most of the time depending on the size difference(high chance to fail for similar sized targets) unless you had a grappling/wrestling proficiency(which the wrestler background would provide) that would improve your chances to a reasonable extent.

**Comment by Pabrer** [comment]
i think this is a good idea
