### ISSUE TITLE
Planting trees and bushes with magic/creating a forest through the camp

### ISSUE THREAD

**Issue by Lilimday** [CleverRaven/Cataclysm-DDA#69054]
### Is your feature request related to a problem? Please describe.

Is it possible to enable the creation of trees by magic? As far as I remember, the same Queen Triffid can create trees. Why can't you make a spell that also creates a random tree? (I'm thinking choosing which tree we want or making separate spells for each is too much of a hassle). I’m a little worried that there will be too much temptation to become a magician of a certain direction just for the sake of this spell, maybe you can make it universal, say, by making the spell read from a one-time-use artifact created from the crafting menu.
It would also be logical that if you can cut down forests through the camp menu, then why can’t you plant them? Also using magical ingredients or a lot of time + sooo many calories of payment.
I also remember that it was once possible to create pots in which plants could be grown all year round, how about very large pots with trees? Mobile long-growing tree.

Once upon a time, I proposed including the option to include tree planting, but it was not accepted, stating that the trees should grow for a long time (and this despite the fact that the camps imply more than one season on site).
I still think that waiting several years for the tree to grow for the base is not a problem, but aren’t the methods listed above logical, at least magic for the magicyclism mod? If anyone smarter than me reads this, please take a closer look at the idea.
I remind you that ordinary plants sometimes grow for two seasons, this is also a long time, but no one considers it abnormal to stay in one place to wait for the harvest, I am ready to always live in one place, why can I wait a few years until my maple trees grow.

### Solution you would like.

Possibility of planting trees.

### Describe alternatives you have considered.

Magic (spell, artifact) creating the tree itself or accelerating the growth of a seedling (but then you need the ability to plant a seedling).
Landing through the camp quest menu.
Planting by hand with natural anticipation, possibly accelerated through fertilizer.

**Comment by NetSysFire** [comment]
Feels basically like #49337.

**Comment by Lilimday** [comment]
> По ощущениям это примерно [ #49337 ](https://github.com/CleverRaven/Cataclysm-DDA/issues/49337) .

Trifeds still need to be found, and it is madness to look for living plants and give them kicks in order to plant a couple of trees, I offer adequate methods.
