### ISSUE TITLE
Enabling experimental 3D view cancels companion reading tasks when PC changes levels

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69053]
### Describe the bug

Tasking companions to read books and then transition to another Z level causes those companions to "finish" their tasks, but only when experimental 3D view is enabled.

### Attach save file

[West Kingston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13226439/West.Kingston-trimmed.tar.gz)

### Steps to reproduce

1. Walk downstairs and up to the companion strangely (but not relatedly) removing a bench on the level above, and note that the 3 beggars reading won't care about it.
2. Walk back up, enable experimental 3D view and return back down to the companion downstairs.
3. See that the reading beggars will stop reading.

### Expected behavior

3D experimental view should not affect companion activity, and, if it should have any effect, it should enable 3D activity, rather than kill it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4823-g033a9b7373 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

Non important ramble below.

Discovered it accidentally as upgrading to a new experimental version seemed to degrade companion behavior. However, it turned out I'd forgotten to disable it after desperately trying to get out of the trap formed by a cockroach blocking the path up from a cellar (the type with a ramp, in particular a doomed future Tacoma farm (doomed because it's surrounded by fungaloids on at least 2 sides, and probably all 4)). As I couldn't move past it (warnings on) or attack it (warnings off) I tried to enable 3D view to at least be able to shoot at it, but it still couldn't be targeted. Ended up debug killing the vile critter as it wouldn't come down either.
I believe you can now try to squeeze past zombies blocking stairs (at least I think I've seen that trying to move downstairs), so maybe a similar thing is needed for ramps?

**Comment by Maleclypse** [comment]
I'll try and test this later this week.
