### ISSUE TITLE
plant_stalk can be cooked without heat/fire

### ISSUE THREAD

**Issue by jackledead** [CleverRaven/Cataclysm-DDA#69057]
### Describe the bug

I picked some wild shrub, got a plant stalk (which i believe recently was replaced from the burdock stalk) and I could cook it without having any tools or heat/flame.

If you look at the code I believe it's from some copy_from shenanigans.

{
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "cooked_burdock_stalk",
    "copy-from": "cooked_cattail_stalk",
    "components": [ [ [ "plant_stalk", 1 ] ] ]
  },

### Attach save file

[Mizpah_copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13228588/Mizpah_copy-trimmed.tar.gz)

### Steps to reproduce

debug spawn plant stalk. get recipe. get skills required. press & and make the cooked plant stalk with no fire.

### Expected behavior

I expect to use heat/flame to cook the item like all the other veggie recipes.

### Screenshots

![plant stalk no fire](https://github.com/CleverRaven/Cataclysm-DDA/assets/75153234/529b43ce-b4fd-4358-86a7-5745c3cd0f68)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: d1060e6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Jackledead Infected [jackledead_infected],
    Jackledead Armory [jackledead_armory],
    Grow More Drugs (CDF+) [grow_more_drugs],
    Deadly Zombie Virus [deadly_bites],
    Disable Mutagens [no_mutagen],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Karol1223** [comment]
It is indeed a problem with copy-from. It's been reported on Discord a bunch of times but I believe this is the first GitHub report. It could be trivially fixed in JSON but from what I heard the perfect solution would be to correct C++ copy-from behavior to fix the issue at the core.

**Comment by GuardianDll** [comment]
#60257, both qualities and tools are not inherited
