### ISSUE TITLE
Difficult to maintain sleep schedule without downers

### ISSUE THREAD

**Issue by EvanBalster** [CleverRaven/Cataclysm-DDA#69067]
### Is your feature request related to a problem? Please describe.

I've discussed with some other players on Discord and it seems there's a general pattern that player characters usually take much more than 16 hours to become tired.  Players who casually consume caffeine as they would in real life often report trouble getting their character to sleep.  Many players report using alcohol, cough syrup or other downers as sleep aids in order to maintain a regular sleep schedule.  Those who don't report issues with fatigue or weariness building up as they fail to get enough sleep.

Further observations:

* Players seem to rely more on depressants than stimulants despite their hardworking lifestyle.
* The "less sleep" positive trait seems to be disadvantageous.

### Solution you would like.

Ideally some changes should be made in order to:

• Generally shorten the interval until players feel tired (which they could stave off with stimulants).
• Trend sleep/wake cycles toward 24 hours, especially in the absence of stimulants, depressants, sickness or unusually high physical activity.
• Make stimulants more reasonable to use in lifelike ways (eg, morning coffee).
• Make it easier to sleep in a few hours.

A think a simple, short-term improvement would be to simply reduce the "time to tired" across the board, either by increasing the rate at which it accumulates or changing the threshold.

### Describe alternatives you have considered.

There was some discussion about implementing a circadian rhythm, tying that into systems for sleep, hunger and substance dependency, and making it responsive to cues like sunlight, bright light, food, drugs and physical activity.  This would be a bigger project.

**Comment by Kanexan** [comment]
With regards to making them more reasonable to use in lifelike ways a la morning coffee, I guess two ways of doing it would be to either make stimulants stronger shortly after being woken up, or possibly give some sort of 'grogginess' or 'just woke up' effect for after sleeping that taking stimulants would abate?

**Comment by AlexMooney** [comment]
I hope that a hypothetical grogginess de-buff would only take effect when woken up by some stimulus.  IRL I don't experience it when I'm not being woken up early by an alarm.  Happy to see this project in light of my survivor's difficulties in having a reasonable sleep schedule!
