### ISSUE TITLE
Grenade UI: We're doing this backwards.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#69061]
### Is your feature request related to a problem? Please describe.

Grenades are super annoying in this game, as anyone who likes to explode stuff can tell you.

Disclaimer: I have never thrown a grenade, and the last time I saw a working dummy grenade was c. 1998, but I did talk to some discorders who have, and I read some wikihow articles too. So I'm kind of an expert I guess, really.

As I understand it, the procedure for throwing a grenade IRL is:
- pull the pin
- hold down the spoon so you do not get blown up
- throw the grenade when ready
- the spoon releases when the grenade is thrown/dropped/etc

The protocol in CDDA right now is
- `w`ield the grenade
- `a`ctivate the grenade, pulling the pin and apparently releasing the spoon as well
- `t`hrow the grenade before it explodes in your hand.

This is not very intuitive, and not realistic, and a lot of keypresses, and just kind of stupid. Now, the itnernet has told me repeatedly that "realism" and "fun" are opposites, so I'd like to remove fun from grenades (and other armable throwables) and add realism by making them more intuitive, harder to mess up, and require fewer keypresses.

### Solution you would like.

1. By default, `t`hrowing a grenade that is not armed should *assume* you are going to arm it first. There are very few situations in which you may want to throw an unarmed grenade. We should add the time to pull the pin to the throwing process.
2. `t`hrowing a molotov or other armable device should also assume you are first going to arm it. In the case of molotovs we should check for the fastest available fire source and use that (fewest total moves to get it out of container and light molotov). If players want to use a specific fire source they can `a`ctivate the molotov the old way.
3. If you want to run the timer on your grenade, or drop it in place armed, then the old technique of `a`ctivating your grenade should still work for that. Doing this action should say something like `you pull the pin and release the spoon of the grenade. The fuse is running!`

#### Future directions
1. We could add a way to interact with a grenade/armable device and specify "turn off 'arm by default'", or this could be a setting in options. This would restore old behaviour. There are a few situatiosn where this might be desirable, but not many. (one example is that when AI can respond appropriately to grenades, a non-armed grenade could force NPCs to scatter without wasting your bomb)
2. We may want to add a "grenade proficiency" which decreases time to pull the pin significantly. it's possibly too meta but personally I'd also be willing to have this slightly increase the effectiveness of cover against grenade shrapnel.
3. Some people would still like to see the fail state of "forgot to pull the pin on grenade". I personally don't think that adds much fun to the game, but if we did have such a thing it should be the result of your *character* forgetting because of their inexperience, not the *player*. If I'm playing a veteran navy SEAL, they aren't going to forget how to throw the grenade even if I might. I would suggest that we'd have a low chance of forgetting to arm the grenade based on throwing skill and perception stat, in this case. Having grenade proficiency would drop this chance to zero.

### Describe alternatives you have considered.

We could improve the current UI by warning the player if they're about to throw a grenade that hasnt' been armed, but that's another annoying UI popup for a scenario that we shouldn't really be modelling in the first place.

### Additional context

Some have pointed out that we should also prompt with an "are you sure?" if you try to arm an explosive while it's still in a container.

**Comment by GuardianDll** [comment]
*points toward `drop_action` syntax so one can reuse it*

**Comment by I-am-Erk** [comment]
Can you explain a bit more Guardian, so that we can point potential new contributors in the right direction?

**Comment by GuardianDll** [comment]
I don't know how much it fit, but in theory we can make something like:
```c++
"drop_action": {                  
  "type": "transform",  // reusing the existing use_action syntax
  "target": "grenade_act",  // reusing
  "target_timer": "5 seconds"  // reusing
  "need_fire": 1, // reusing, to handle the molotovs
  "need_fire_msg": "You need a lighter!", // reusing
  "moves" : 500 // reusing, handle the time you need to ignite/pull the pin (this part is the most questionable, as it, at first, doesn't cover the desired grenade proficiency, and it doesn't simulate "i do all the way into my backpack, into box with lighter, pick up the lighter, ignite molotov, then put everything back" or "i use my magnifying glass to ignite the gas soaked rag" that may happen in the game
  }
```
In theory it should give us a syntax that cover most of desired features, while also not making it hardcode, that can be used only by specific set of items in the game

**Comment by I-am-Erk** [comment]
We'd need that to specifically only happen when thrown, not when dropped, but yeah that's a good point.

**Comment by GuardianDll** [comment]
it doesn't matter if the transformation action happens while the projectile fly or before it, the checks are happen before this anyway

**Comment by I-am-Erk** [comment]
> it doesn't matter if the transformation action happens while the projectile fly or before it, the checks are happen before this anyway

My point is that we don't want you to pull the pin if you `d`rop the grenade along with a bunch of other items onto the ground. Only if you throw it.

**Comment by GuardianDll** [comment]
if you mean by dropping on the ground, the drop action is not triggered by it, it only used if you specifically throw the item
i thought to propose a custom boolean like "ask_if_not_possible" that should ask player something like "you can't ignite your molotov, do you want to throw it as it is?", but i don't see the reason for it to not be a default behavior

**Comment by fairyarmadillo** [comment]
This was already discussed at length in [#67977](https://github.com/CleverRaven/Cataclysm-DDA/issues/67966) but auto-activating bombs when thrown was and remains a controversial idea for several reasons, not the least of which being that not all bombs behave in the same way. Better ideas were proposed there, including an option in the throw menu that should make everyone happy.

**Comment by I-am-Erk** [comment]
Ah, this is indeed a dupe, I will move back to 67977.
