### ISSUE TITLE
Jenny pneumatic mission fulfillment reported when it's not.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69079]
### Describe the bug

Looking through my umpteenth library and book store for Jenny's an Fatima's books I suddenly get a message that Jenny's quest has been fulfilled. However, no books I find match the description.

### Attach save file

[West Kingston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13244589/West.Kingston-trimmed.tar.gz)

### Steps to reproduce

Not sure it can be reproduced easily..
- Get Jenny's quest.
- Look for the book.
- Suddenly get a report the mission is completed, with no matching book in sight.

### Expected behavior

The mission being completed on actually handing over the book (which means finding it).

### Screenshots

![Screenshot (285)](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/c7fbc07a-7637-4a8c-9125-18ee2dc2e254)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-4884-g262d6724f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

The save is from a little after the message, as I walked around trying to locate the book. The actual location when the message was received might have been a tile to the E. I've also read a couple of carried books to identify them and see if they might match the contents without having a matching name.

Looking through the JSON files I found that Jenny wanted "book_pneumatics", and searching through all the save files for that identifier returns underground coordinates for all files except one, and that file hasn't been written to today (implying it isn't my current map location, as stuff has been done here).

There's not anything directly below either (debug map reveal), so it couldn't somehow be a lab underneath the book store.

**Comment by EvanBalster** [comment]
I had something similar happen a day or two ago.  I had come to the refugee center in a cargo van containing all the spoils of my first 12 ingame days, including the book "Pneumatic Pnowledge".  Talking to Jenny didn't appear to actually give me a mission.  She thanked me and told me to talk to her again in a few weeks.  When I returned to the truck, I got a mission fulfillment notification.  Then, when looking for the book, I noticed it had vanished from my truck.

**Comment by PatrikLundell** [comment]
I just found the book in a lab, and when I return to Jenny she thanks me for my help, without turning the book in (I still have "my copy" in my inventory). The new quest design isn't very good, in my opinion, both because it's confusing, and because the player may want to keep the book and look for a second copy to deliver (like with other quests where you get the option to not turn the item in), or even just craft the thingie the book has a recipe for before handing the book in.
