### ISSUE TITLE
Can't build fbmc_shelter_2_bedroom_E1 in evac shelter base

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#69088]
### Describe the bug

I have built lots of bedrooms in this base, but am now stuck and cannot figure out why. The error says the area is blocked, but the space seems to be clear. Are the coordinates in json correct for this particular bedroom?

"failed to build the fbmc_shelter_2_bedroom_E1 upgrade, perhaps there is a vehicle in the way"

Also I note the cardinality in the names of the rooms does not match the players sense of orientation. Which way is north? North seems to be "down" from the 2d overhead view - this is very misleading for the player. 

The error message is also not helpful, it should not use variable names, and should provide more helpful information - like what is actually blocking stuff - there is definitely no vehicle here.

Please see screenshot - I expect this bedroom to go in the large clear area of base. 

### Attach save file

[vanilla-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13248761/vanilla-trimmed.tar.gz)

### Steps to reproduce

Load save, go to bulletin board and try to complete build bedroom job.

### Expected behavior

Bedroom should be constructed.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19167795/78eae0ee-5eb1-4ca0-af76-06406264e419)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: f26295a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by PatrikLundell** [comment]
The reason for the orientation confusion is that the shelter can be rotated, but the coordinates in JSON (and the names used) are for the non rotated location. It can be noted that appliances are "vehicles" from the code's perspective, and I believe wall wirings are "appliances" as well.
