### ISSUE TITLE
[Aftershock] Exosuit leaves you blind even while on

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#69087]
### Describe the bug

When wearing an exosuit and powering it up with a exosuit power supply, you are still unable to see anything.

### Attach save file

[Temptest-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13248066/Temptest-trimmed.tar.gz)

### Steps to reproduce

Create a new character
Spawn in an Exosuit Frame and Exosuit Power Supply
Wear the frame, insert the power supply
Turn it on
Wait a few ticks or move about. Notice strength went up by 20 but still can't see.

### Expected behavior

A powered up Exosuit should let you see.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51954159/b3c162a4-f662-48fc-98a5-6a3d2714a6d5)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: f26295a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Aftershock [aftershock]
]

**Comment by Drew4484** [comment]
Resolved by #69048
