### ISSUE TITLE
Smartphone case prevents seeing real time

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#69094]
### Describe the bug

If you have a smartphone in a smartphone case, it will no longer display the real time in the side bar.

### Attach save file

N/A

### Steps to reproduce

1. Acquire a smartphone
2. Notice the real time displayed in the sidebar (assuming your sidebar has a time display
3. Acquire a smartphone case
4. Insert smartphone into smartphone case
5. Notice the time display no longer displaying real time (assuming you have no other item that can show real time)

### Expected behavior

You can still check the time on your phone when it's protected

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: e497f5a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Terrorforge** [comment]
I think this might represent a broader problem with nested containers. I was having similar problems  with binoculars not working and lighters not being recognized when I wanted to light candles when I was carrying my tools in a bag held in my MoM lifting field

**Comment by Golfavel** [comment]
Duplicate of #68075
