### ISSUE TITLE
experimental build 2023-11-03-2250 has severe errors loading or creating world

### ISSUE THREAD

**Issue by Vaskritaya** [CleverRaven/Cataclysm-DDA#69098]
### Describe the bug

Attempting to load an existing world or create a character in a new world causes an error regarding limb eoc stuff. ignoring or continuing both have the same effect of returning to the menu. attempting to load that world a second time causes a number of strange errors about basically every json field, presumably because initialization got all fucked up. 

### Attach save file

N/A

### Steps to reproduce

1. [Download this release](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-11-03-2250)
2. Load a world or attempt to create a character
3. game's broken

### Expected behavior

I expect to be able to play the game past the menu.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22992007/bc067623-93bd-400c-9c8e-41395961cb0d)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22992007/4ad588ab-e53b-4b29-b0b4-217a75596597)

### Versions and configuration

NOTE: This was generated using the previous working experimental version, since I can't get into the game on the affected version. 

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: f349e62 [64-bit] 
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

**Comment by Lord-Helmchen** [comment]
same for me, downgrading to 2023-11-03-2007 allowed the save to load.

**Comment by Termineitor244** [comment]
For the experimental version that you both mention and the error messages, this should be a problem introduced by #69021, @MNG-cataclysm any input in this?

**Comment by MNG-cataclysm** [comment]
Looking at this right now.

**Comment by MNG-cataclysm** [comment]
Found the bug, making a PR to fix it.

**Comment by MNG-cataclysm** [comment]
#69101 is an urgent fix for this. I think it should be merged ASAP to get development back on track, since this error causes all of the basic build tests to break.
