### ISSUE TITLE
Underage sex with Alonso Lautrec is possible (and shouldn't be)

### ISSUE THREAD

**Issue by henrihim** [CleverRaven/Cataclysm-DDA#69108]
### Describe the bug

After looking through his code and verifying if it's possible in a recent playthrough, I've found that there wasn't any way for Alonso to refuse his services to a player's character who is aged 16-17.

### Attach save file

N/A

### Steps to reproduce

1. Create a character with an age variable of 16-17.
2. Spawn or travel to Refugee Center
3. Talk to Alonso and receive his quest
4. Finish quest and talk to him again (with condom in inventory)

### Expected behavior

For Alonso's services to be gated by age.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-S901U; Release: 13; Incremental: S901USQS3CWI1; 
- Game Version: 0997bfc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
Alonso is a sleasebag who shags everyone he can convince to participate (and at least he's not drugging unwilling victims, and he IS using protection), and there is no government left, so I don't think such a character would care one bit about the age.

Personally I find him to be utterly disgusting and won't have my characters have anything to do with him, but if other players do it's their business.

**Comment by fairyarmadillo** [comment]
Alonso is a silly guy who is part of a community watched over by the remnants of the United States government and there's no indication that he is a bad person, just that he is down bad. Furthermore it does not serve our game to have a casual depiction of statutatory rape played for laughs, and because it involves the player character, such a thing may actually be illegal in some places.

Fixing it would be trivial and should be done ASAP, especially if there's room for Alonso to say something funny about it when he backs out.

https://youtu.be/o1LaMtdwMnE?si=rGL0G2vvtXh2ISB4

**Comment by TheRafters** [comment]
Is there any concrete confirmation on which state in New England cataclysm is based in? Because it's 16 everywhere but Massachusetts, where it is 18 according to a cursory Google search of the age of consent in New England

**Comment by henrihim** [comment]
Sadly, there isn't any confirmation beyond a vague 'New England'.

**Comment by toweroglass** [comment]
If there is moral grey area in depicting kids at all in gaming, because no one wants to deal with murdering and abusing them, then why does it need to be possible to roleplay as a teenager?
