### ISSUE TITLE
Animals with special moves to consume food/crops do so far too frequently

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#69121]
### Describe the bug

Animals like dogs and goats consume massively more food than they should. Testing with a rottweiler in a room with dehydrated meat, it consumed roughly 40 pieces every six hours, constantly. The current implementation is ludicrously fast, and since animals don't sleep, constant.

Unknowingly bringing home a dog or goat (or, again, many other animals) can have massively outsized harm to your crops and food stores.

### Attach save file

N/A

### Steps to reproduce

1. Have animal with EAT_FOOD or EAT_CROP near your food or crops.
2. Wait and see them eating constantly.

### Expected behavior

Barring a more extensive system for animals to actually need to eat to sustain themselves, these special moves should be tuned waaay down so that individual dogs/goats/etc can't consume your entire farm or food stockpile over the course of a day or two.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/434ca666-d983-4d52-a829-e7ca9fe47d29)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 48cf076 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by fairyarmadillo** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/66294 added a stomach_size json field. giving this to animals with EAT_FOOD and EAT_CROP will cap their daily food intake according to whatever gets set.

Currently only cockroaches have stomach_size, but it's ready to easily be added to any other critter.

**Comment by fairyarmadillo** [comment]
Actually it looks like I didn't set EAT_CROP up to fill stomachs, but doing so would simply be a matter of copying the code from EAT_FOOD.

**Comment by gisaku33** [comment]
> #66294 added a stomach_size json field. giving this and the EATS flag to animals with EAT_FOOD and EAT_CROP will cap their daily food intake according to whatever gets set.
> 
> Currently only cockroaches have stomach_size, but it's ready to easily be added to any other critter. Doing this would solve the problem and help set them up for better animal husbandry in the future.

I'm not sure that just adding stomach capacities would really address the issue. Since animals don't actually need to eat to live, all that allowing them to eat does is incentivize locking your animals away from your food stores. Wild animals eating your food is one thing, incentivizing you to actually deal with them by killing/removing/taming them, but tamed animals consuming your food/crops just forces you to enclose them, tie them in place, and otherwise keep them separate from your general area.

**Comment by fairyarmadillo** [comment]
> > #66294 added a stomach_size json field. giving this and the EATS flag to animals with EAT_FOOD and EAT_CROP will cap their daily food intake according to whatever gets set.
> > Currently only cockroaches have stomach_size, but it's ready to easily be added to any other critter. Doing this would solve the problem and help set them up for better animal husbandry in the future.
> 
> I'm not sure that just adding stomach capacities would really address the issue. Since animals don't actually need to eat to live, all that allowing them to eat does is incentivize locking your animals away from your food stores. Wild animals eating your food is one thing, incentivizing you to actually deal with them by killing/removing/taming them, but tamed animals consuming your food/crops just forces you to enclose them, tie them in place, and otherwise keep them separate from your general area.

This is what you do in real life.

**Comment by gisaku33** [comment]
> This is what you do in real life. Farmers pen their cows and pigs up separately from their crops, and dogs will generally eat anything in reach if unattended.

In real life, you tie your animals still and leave them in a room so they never eat? Because again, DDA animals don't actually need to eat, so any instance of them eating is purely negative. It's not something they have to do, they don't gain anything by doing it, it's just deleting food/crops on a timer. Putting a limit on the timer doesn't change that it is still fundamentally just deleting things for no gain, and it won't change that the "optimal" thing to do is to never feed them.

Adding stomach volumes to limit how much food/crops they delete will make it less annoying, but I don't think it really changes anything. It makes sense for cockroaches because they are vermin you want to deal with quickly before they cause too much harm, but for tamed creatures that you ostensibly want around it just means you risk food for nothing without tying them in place forever.

**Comment by fairyarmadillo** [comment]
> > This is what you do in real life. Farmers pen their cows and pigs up separately from their crops, and dogs will generally eat anything in reach if unattended.
> 
> In real life, you tie your animals still and leave them in a room so they never eat? Because again, DDA animals don't actually need to eat, so any instance of them eating is purely negative. It's not something they have to do, they don't gain anything by doing it, it's just deleting food/crops on a timer. Putting a limit on the timer doesn't change that it is still fundamentally just deleting things for no gain, and it won't change that the "optimal" thing to do is to never feed them.
> 
> Adding stomach volumes to limit how much food/crops they delete will make it less annoying, but I don't think it really changes anything. It makes sense for cockroaches because they are vermin you want to deal with quickly before they cause too much harm, but for tamed creatures that you ostensibly want around it just means you risk food for nothing without tying them in place forever.

This is not really a sensible complaint. Animals will not eat food which is inside of a container or a piece of furniture. They will only eat food which is left out on the floor. You do not need to lock your dog in a closet, you can simply put your meat in a refrigerator, on a shelf, or in a bag, which is how dogs work IRL. Of course they're going to snap up unattended piles of hot dogs, animals are pretty much the reason we don't leave our food out 24/7 like that. Once stomach size is implemented, you can circumvent this by feeding your dog once a day if you really, really want to leave a cake on the floor. Or you can tie your dog up one tile away from the cake.

Monster AI and offscreen simulation are not yet at a point where death by starvation is a workable mechanic. It is a reasonable goal, but it would need to be implemented in such a way that it would not cause all animals in the game to invariably starve to death because the player is not there to take care of them, and would need some offscreen simulation to handle animals which are outside the reality bubble. Until then, the model for animal food is that it's optional and can confer benefits or prevent debuffs, as described in https://github.com/CleverRaven/Cataclysm-DDA/pull/66294
