### ISSUE TITLE
Documentation: RANGE Enchantment Value does not actually exist

### ISSUE THREAD

**Issue by Grnkchi** [CleverRaven/Cataclysm-DDA#69138]
### Describe the bug

Well. as the title says, there's a 'RANGE' value for enchantments in the documentation (more specifically, in MAGIC.md), but it does not actually seem to exist when one attempts to use it.

### Attach save file

N/A

### Steps to reproduce

1. Attempt to create an ecnhantment effect modifying RANGE.
2. Get an error message when loading the world if the mod / modified base game files have a RANGE enchantment.

### Expected behavior

Either the enchantment working and increasing weapon range, OR not being listed in the documentation.

### Screenshots

![One of These](https://github.com/CleverRaven/Cataclysm-DDA/assets/67743918/c22d257a-f62a-4c50-85c3-658ae2f13d3d)
![Marked](https://github.com/CleverRaven/Cataclysm-DDA/assets/67743918/82f5817f-97f9-42ec-99aa-873c886abc60)

### Versions and configuration

N/A

### Additional context

N/A

**Comment by GuardianDll** [comment]
Can't confirm
https://github.com/CleverRaven/Cataclysm-DDA/blob/20accf27b54ec3dc42d01ae441e31909337406ab/data/mods/BombasticPerks/perks.json#L293-L301

**Comment by Grnkchi** [comment]
I do, yes. That explains the misunderstanding.

**Comment by GuardianDll** [comment]
You can use the documentation related to 0.G by this link https://github.com/CleverRaven/Cataclysm-DDA/tree/d6ec466140839dd70c1a43671eb4a08b007695c2
