### ISSUE TITLE
[Aftershock] Exosuit power supplies do not function in PSU pocket

### ISSUE THREAD

**Issue by TheSpaceMoth** [CleverRaven/Cataclysm-DDA#69143]
### Describe the bug

Exosuit power supplies are not found when stored in the PSU Compartment within the suit.
When a power supply is held in hand the suit can power up and functions properly.
When the power supply is then put into the pocket the suit shuts off and can't be turned on again.

### Attach save file

[Cheneyville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13265945/Cheneyville-trimmed.tar.gz)

### Steps to reproduce

Create a new character/world
Spawn an Exosuit Frame and Exosuit Power Supply
Wear the frame and pick up the power supply as a handheld item
Power up the Exosuit (Optional)
Insert the Power Supply into the Exosuit
Loose power if powered up, and be unable to turn on the suit

### Expected behavior

Power supplies stored in the pockets of the exosuit should be used to power the suit

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51954159/c567eb07-0ce9-4027-a69c-5391ae1f84f0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 20accf2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Aftershock [aftershock]
]

### Additional context

Auxileary power supplies seem to work ok.
If an auxileary power supply is dropped while active, the exosuit remains powered indefinately without drawing power from the main power supply.

**Comment by Drew4484** [comment]
Just to check, this is happening with any of the PSU slot items? Both battery and generator versions?

**Comment by TheSpaceMoth** [comment]
Just tested, looks like its with both.
