### ISSUE TITLE
Propane lantern, smart lamp and electric lantern illuminate player when they should not

### ISSUE THREAD

**Issue by weosk** [CleverRaven/Cataclysm-DDA#69140]
### Describe the bug

When activating a dropped propane lantern both player and lantern get the illumination effect which moves around with the player while the illuminated lamp stays stationary.  

Same thing happens with the smart lamp when it's first activated in the inventory (otherwise the illumination effect won't work at all), deactivated, dropped and activated again remotely. 

This is related to #56679 and #68435

### Attach save file

[Fitzhugh-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13264441/Fitzhugh-trimmed.tar.gz)

### Steps to reproduce

Propane lantern:
1. Drop a loaded propane lantern
2. Activate it with 'a' while it lays on the ground
3. Move a few steps away, see that the light is magically carried with you

Smart lamp:
1. Have a loaded smart lamp and rc control in inventory
2. Drop the smart lamp (as it won't react to the signal in inventory, usefull, but unrealistic, intended?)
3. Activate rc control and press the blue button
4. Smart lamp is listed as "on" but stays dark, illumination originates from the player and moves with him
5. (Optional) If you pick up the lamp now and drop it again, it illuminates their surroundings as it should, illumination still stays with the player. If you press the blue button again, both player and lamp go dark. If you press it another time, again player and smart lamp light up despite distance. 

### Expected behavior

Propane lantern:
Light should stay with the dropped lantern

Smart lamp: 
A dropped, loaded smart lamp should light up their surroundings when activated remotely, as it's their main use case. 
When the rc controls blue button is pressed, the lamp should switch on even when in inventory. 
Light should not be carried magically with the player without the item. 

### Screenshots

Propane lantern:
![Screenshot from 2023-11-06 10-40-17](https://github.com/CleverRaven/Cataclysm-DDA/assets/53002709/045c129b-f33e-4729-ba15-bab0c608c518)

Three dropped smart lamps around, with activation only player is illuminated while not carrying any:
![Screenshot from 2023-11-06 10-27-24](https://github.com/CleverRaven/Cataclysm-DDA/assets/53002709/05b420e2-a3e7-4b15-9f78-f91e89d580e6)

After picking up and dropping, both player and smart lamp shine are controlled by remote:
![Screenshot from 2023-11-06 10-29-08](https://github.com/CleverRaven/Cataclysm-DDA/assets/53002709/e2c115c8-edf2-4bf0-b2e2-3c6e79e62737)

### Versions and configuration

OS: ManjaroLinux
OS Version: 23.0.4
Game Version: 0.F-20accf2
Graphics Version: Tiles
Game Language: English
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs[personal_portal_storms],
Slowdown Fungal Growth[no_fungal_growth]
]

### Additional context

Smart lamp could be such a great tool!

**Comment by PatrikLundell** [comment]
I've seen this issue in 0.G experimental as well, where I've lit an electric lantern dropped on the ground (for a companion to do mining work) and then climbed the stairs and walked out into the dark part of the room upstairs. There's a remaining lit area around the PC which disappears on save/reload.
