### ISSUE TITLE
Missing translatable strings for Sky Island mod

### ISSUE THREAD

**Issue by pedestrian4** [CleverRaven/Cataclysm-DDA#69144]
### Describe the bug

Almost the same problem as this: https://github.com/CleverRaven/Cataclysm-DDA/issues/67072

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/126118675/f54959b4-3200-4afb-8a72-12b59830cece)

The options above and their descriptions are not on Transifex so can't be translated.

It's in data\mods\Sky_Island\EOCs.json

It seems a cool system for mods btw.

### Attach save file

n/a

### Steps to reproduce

1. Start a game with Skyisland mod, with any language selected but English.
2. In a few screens ahead, find not translated texts.

### Expected behavior

It should be on Transifex to be translated.

### Versions and configuration

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/126118675/69102953-5bfa-497f-82af-505931cae03a)

**Comment by GuardianDll** [comment]
/confirmed
If someone knows how to make strings translateable, the code is here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npctalk.cpp#L4558

**Comment by BrettDong** [comment]
They are now translatable on Transifex.
