### ISSUE TITLE
Vehicle heater should not consume energy

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#69177]
### Is your feature request related to a problem? Please describe.
Integated vehicle heater, for now, works as a generic heater, installed onto vehicle, and consume energy upon working
It is not how actual vehicle heater works
### Solution you would like.
Instead, it should be completely energy free, but work only when the vehicle engine is on

**Comment by PatrikLundell** [comment]
That should only apply to combustion engine vehicles, as the waste heat from electric vehicles won't be sufficient for heating purposes.

**Comment by RAldrich** [comment]
It should probably be two different types of heater: no reason you can't have electric heaters in a combustion engine car. Most winterization packages have electric heaters and heated seats IRL (and turning them on without the engine running drains the battery very rapidly. Heated seats in a Tesla has a *huge* impact on range.)

**Comment by Maleclypse** [comment]
Huh activated heated seats would be neat.

**Comment by actually-a-cat** [comment]
Similar story with cooling (but unlike heating, it should have substantial mechanical drag on the engine, like an alternator)

Depending on how much detail we want, arguably there should be a small electrical draw for the blower motor, and in case of AC, also the compressor clutch. Maybe 50W each.
