### ISSUE TITLE
In the advanced inventory manager, when you exit a container, ignore corpses as a container.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#69175]
### Is your feature request related to a problem? Please describe.

Some change made it so that when you're in the advanced inventory manager and enter a container that's on a zombie, you have to exit up through the zombie corpse, which makes it so when you return to the top level that shows everything in the area you've lost your place in the list of items. It used to be that for the purpose of the advanced inventory manager you'd return to the same place, making it easier to check all the containers, but it's now significantly harder to loot all the containers because you keep returning to the corpse instead of the container you started from. 

### Solution you would like.

In the advanced inventory manager, when you exit a container that's on a body, ignore corpses as a parent container. Go directly from the container in the corpse to the top level view.

### Describe alternatives you have considered.

Have a "back" option that takes you back to the last view you were looking at, including your position within the list. This would leave the current functionality to exit container to parent alone.

**Comment by Qrox** [comment]
It would probably make more sense to stop showing corpses' contents at the top level to be consistent with other containers.

**Comment by MrHrulgin** [comment]
That would certainly solve the issue of losing ones' place in the list of items. But I see a pair of issues with that proposed solution:

1. Gameplay flow: A lot of the interesting loot on a zombie is in a container, sometimes in two layers of containers. Having the corpse as yet another layer of containers would serve to further obfuscate the interesting loot, as it would make it so that you had to drill further down to see what's in the small bags inside their backpacks.
2. Verisimilitude: It would mean you couldn't eye a corpse at all and see what they're wearing without "opening" the body. That doesn't seem realistic.

**Comment by Qrox** [comment]
These problems also exist for other nested containers, so perhaps it is better to add a "flat mode" to the AIM that shows everything contained (perhaps with a flag to specify which containers allow seeing their contents without diving into them, but that is not currently implemented in any inventory UIs anyway). Making corpses behave like the rest of the containers would also allow moving corpses without having to navigate through their contents and distinguishing items on the ground from items on a corpse.

**Comment by MrHrulgin** [comment]
An entirely flat mode would be absolutely ideal. No amount of sorting through containers for loot is actually fun or interesting gameplay.
