### ISSUE TITLE
Can't dive underwater.

### ISSUE THREAD

**Issue by ButchLesbianGarfield** [CleverRaven/Cataclysm-DDA#69185]
### Describe the bug

When in an ocean tile, or any tile of deep water, trying to dive underwater will result in the message "Can't go down here!", and the character will not dive underwater.
You can still surface from underwater if you sink the moment you enter a tile, but you can't willingly dive underwater when swimming without weights.

### Attach save file

[Spring Hope-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13300603/Spring.Hope-trimmed.tar.gz)

### Steps to reproduce

1 - Step into any deep water tile with any character.
2 - Try to dive underwater.

### Expected behavior

I expect to be able to dive underwater and surface on command.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/150289832/7eea2996-5217-40b5-922f-906de2c8fca4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 1ceae3c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by gettingusedto** [comment]
river arent deep enough to swim underwater iirc. try lakes.

**Comment by ButchLesbianGarfield** [comment]
Oh that did work, my bad that's a fairly new change I think. Still maybe that text could be changed so it's made more clear where you can and can't dive? It was really confusing to run into this.

**Comment by ButchLesbianGarfield** [comment]
Also, I can still dive underwater even in shallow rivers if I walk into it while carrying something heavy, but I can't dive down on purpose, which makes this extra confusing.
