### ISSUE TITLE
Radio tower upgrade for base camp requires vehicle solar panels instead of solar panel array

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#69189]
### Describe the bug

The radio tower upgrade for the base camp still asks for the small solar panels instead of the solar panel array. 

### Attach save file

N/A

### Steps to reproduce

1. Construct the base camp so that the radio tower mission becomes available
2. Open the camp board
3. Observe radio tower upgrade mission

### Expected behavior

It asks for the solar panel array

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/9960b1a2-65cb-44ac-9030-61a2a63ce1e4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 1ff72fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by pwalsh0** [comment]
Does not seem necessarily wrong? You can just disassemble an array to get the 4 vehicle panels.

**Comment by snipercup** [comment]
> Does not seem necessarily wrong? You can just disassemble an array to get the 4 vehicle panels.

I think 4 solar panels do not produce enough power since they are small ones mounted on vehicles. The alternative is the large wind turbine or 4 small wind turbines. I'm not sure the small ones produce as much power as the other options.
