### ISSUE TITLE
error screen when opening proficiency menu

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#69197]
### Describe the bug

got this error when looking at the progress of the Baton familiarity proficiency in the proficiency menu.

 DEBUG    : invalid proficiency category id "prof_combat"

 FUNCTION : const T &generic_factory<proficiency_category>::obj(const string_id<T> &) const [T = proficiency_category]
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/generic_factory.h
 LINE     : 478
 VERSION  : 7f83155

### Attach save file

[Chatanika-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13303094/Chatanika-trimmed.tar.gz)

### Steps to reproduce

1. open attached save
2. open @ screen
3. open the (p)roficiency menu
4. check Baton Familiarity progress
5. error screen

### Expected behavior

no error

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 7f83155 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Bombastic Perks [bombastic_perks]
]

**Comment by Termineitor244** [comment]
This specific issue was fixed in #69231, already referenced in the PR but the word "fixes" was only used with the other issue, I can't close it myself so @Maleclypse? A little help please?

**Comment by gettingusedto** [comment]
#69231 resolves the issue.
