### ISSUE TITLE
Unable to find and assign mission target evac_center_13_z2.

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#69193]
### Describe the bug

When talking to dino dave to get him home, I got this error:
```
 DEBUG    : Unable to find and assign mission target evac_center_13_z2.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 258
 VERSION  : 1ff72fc
```

Afterwards, the player is successfully teleported to the roof and inside Dave's fort

### Attach save file

[Blue Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13302750/Blue.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Complete the mission by talking to Dino Dave and selecting option A "we've done it, Dave!"
3. Observe error

### Expected behavior

No error shows up

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/3c3473a3-e58d-47b8-b806-a5ad556dc305)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/c345de72-91db-43a1-9c55-cb1d8c6e3d66)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 1ff72fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by harakka** [comment]
/confirm
This came up also on devcord.
It looks like evac_center_13_z2 was migrated to just open air in #66123, I assume author missed that this very specific one was used as a mapgen update target for Dino Dave's mission.

**Comment by RenechCDDA** [comment]
Should be able to place the special on any arbitrary OMT by offsetting it from dave's position using `location_variable_adjust`

This doesn't account for rotation so it might be best off it by making sure dave is right below the spot it will be placed - thus you just need to z-adjust once or twice, and the x and y coordinates are irrelevant.
