### ISSUE TITLE
Combat Proficiency category label error and missing

### ISSUE THREAD

**Issue by DBXData** [CleverRaven/Cataclysm-DDA#69206]
### Describe the bug

In proficiency menu, theres information of how long needed to complete the proficiency, what comes/leads to after the proficiency, the pre-requisites, and category. But while im training to obtain a proficiency called 'Unarmed Technique Proficiency', the bug message suddenly comes up. After I close the bug message, I notice that the combat proficiency I just obtained I noticed the category is blank.
 DEBUG    : invalid proficiency category id "prof_combat"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 478
 VERSION  : 9998269

### Attach save file

[New Vienna-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13306728/New.Vienna-trimmed.tar.gz)

### Steps to reproduce

1. Train unarmed (Beginner) in crafting menu until the proficiency 'Unarmed Technique Familiarity' is obtained
2.  After obtained, open Player Info menu, and press 'p' to go to proficiency menu
3. Scroll down to 'Unarmed Technique Familiarity', and the bug message came up

### Expected behavior

I expect that while checking the proficiency I just obtained, the category label is written and not missing.

### Screenshots

![Screenshot (23)](https://github.com/CleverRaven/Cataclysm-DDA/assets/150338795/63dbffb2-2005-435a-9700-4f06e43bda90)
Category not written and only blank

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 9998269 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

 DEBUG    : invalid proficiency category id "prof_combat"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 478
 VERSION  : 9998269

**Comment by Termineitor244** [comment]
/Confirmed after reviewing the changes merged in #69156, we need to add a proficiency category for combat weapons (`prof_combat`) in [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/b399fbbdba48999d83c3d61c1aa352c54d49bdd2/data/json/proficiencies/proficiency_categories.json)
/good-first-issue

**Comment by detahramet** [comment]
Aw damn it, I knew I missed something with the rebase collapse. Fixing it ASAP.
