### ISSUE TITLE
"This piece of clothing is 'oversized' and does 'not fit' you." is confusing and does nothing.

### ISSUE THREAD

**Issue by Aerin-of-the-Toast** [CleverRaven/Cataclysm-DDA#69204]
### Is your feature request related to a problem? Please describe.

"This piece of clothing is **oversized** and does **not fit** you." is a line that shows up in the description of clothing containing the OVERSIZE trait without the VARSIZE trait. This is a line that makes it sound like the piece of clothing isn't meant to be worn by your normal-sized character, and shows up mostly on two types of clothes: Anything XL (like XL arm guards) explicitly meant for mutants, and anything loosely strapped or adjustable that could be worn by mutants or normal characters fine, like backpacks or quivers. The line makes sense for the former category but not the latter.

The line also implies there's some penalty for wearing that piece of clothing, but no such penalty exists. You can still wear XL gear as a normal character, and there's no encumbrance penalty or anything to speak of.

### Solution you would like.

It seems the issue stems from OVERSIZED being used too broadly.

What's needed is to separate it into two flags. Keep OVERSIZED for XL mutant-specific gear, but apply a penalty to encumbrance if normal characters wear it. Then add a new flag, ADJUSTABLE (or something similar) for any clothing flexible enough or loose enough that it's "one-size-fits-all" like backpacks, quivers, etc. This'll work essentally the way it already currently does, but without the "oversized and does not fit you" line in the description.

### Describe alternatives you have considered.

A much simpler (but incomplete) option is to just yeet the line and quietly continue letting regular survivors wear XL armor without penalty. This is actually fairly reasonable since there's no natural spawns for XL mutant gear and most players have zero reason to craft any unless they're already a mutant, so "normal character wearing XL gear they shouldn't" isn't actually a problem that comes up much at all.

**Comment by PatrikLundell** [comment]
The case I can think of where a player may "abuse" the ability to use XL gear without penalty is when the player replaces the PC so a normal sized character takes over the leadership from an XL size one (temporarily or permanently).

**Comment by fairyarmadillo** [comment]
XL gear should be for big people, who can be anywhere from 8 to 13 feet tall in this game. XS gear should be for small people, who can be between 2 and 4 feet tall. Mutants with strange body parts, such as tentacle faces, slug feet, snail shells, etc. should have to use a different category of gear which is either specifically made for them or flagged to be anatomy-agnostic, such as a bag-shaped gasmask that fits any face. These anatomy-agnostic items should not be XL, they should be their own thing.

This seems like a huge and confusing project.
