### ISSUE TITLE
Weapon Proficiencies, profession and background

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#69215]
### Is your feature request related to a problem? Please describe.

Now that weapon proficiencies are a thing, I figure they should be applied to the appropriate backgrounds. And since no one's made an issue about it yet, I'll be the first guy to throw a stone.

### Solution you would like.

So obviously various fighting and sporting backgrounds would have appropriate proficiencies with their weapon (or no weapon) of choice. Like baseball batters being good with clubs, street fighters knowing how to throw a punch, etc. But I also feel like there's a lot of room for non-combative professions and backgrounds to have some level of familiarity with various weapons, like chefs and butchers knowing how to use knives, fishermen being familiar with spears, medical personnel having some knowledge of self defence, and surgeons being good with knives, and so on.
My point is, for anyone who's willing and able to update the various professions and backgrounds with their appropriate skills in combat, think flexibly.

### Additional context

Fuck, another issue written whilst I'm drunk...

**Comment by TheShadowFerret** [comment]
We already have PRs for this 🤔
#68990 #69007
