### ISSUE TITLE
More Magnets

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69236]
### Is your feature request related to a problem? Please describe.

Powerful magnets are much rarer than they should be. At the moment, they're only found rarely in a handful of locations, and, in vanilla, are only used to craft the breacher loading bearing vest and a handful of mod items. Not only does this make those items unreasonably difficult to obtain, it's also a little silly because such magnets are actually quite common in many everyday objects, and should be both possible to retrieve from and useful in crafting those objects.

### Solution you would like.

Add magnets to the crafting and dissasembly recipes for a variety of relevant items. The wikipedia articles for [alnico](https://en.wikipedia.org/wiki/Alnico#Uses) and [neodymium](https://en.wikipedia.org/wiki/Neodymium_magnet#Applications) magnets list several potential uses, but some relevant highlights include:

- Magnetrons
- Electrical motors
- Speakers, headphones and various other sound equipment

This is rendered somewhat complicated by the fact that most of these applications don't _require_ magnets. For example, you can make an alternator with permanet magnets, but in practice most alternators use electromagnets. In each specific case that's reasonably easy to resolve, e.g. allow players to craft the item with magnets OR electromagnet components but the default dissasembly recipe only gives electromagnet components, but it would take a fair bit of research to establish what's appropriate for every potentially magnetic item in the game.

Alnico batteries are also used to treat [iron ingestion](https://en.wikipedia.org/wiki/Hardware_disease) in cattle and as magnetic stirrers, so they could reasonably spawn in farm supply stores, veterinary clinics and labs either just as magnets or specific "cow magnet" and "magnetic stirrer" items that dissasemble into magnets.

If magnets were made more available, they could also be put to more prosaic uses, such as magnetic clasps on clothing.

### Describe alternatives you have considered.

The current "magnet" item is described as an alnico magnet. My natural inclination is to simply remove this refernce and make it a generic high-power magnet, but when I discussed this with @GuardianDll on Discord, he suggested adding neodymium magnets as a separate item, available among other places through neodymium magnet toys, and allowing recipes to use either alnico or neodymium magnets.

I'm not sure which is better. Differentiating the magnets would be more realistic and help make it feel a bit more grounded, but I don't know enough about magnets to say if alnico and neodymium magnets are different enough that some recipes should only allow one or the other. If they're not, making the distinction feels kind of pointless to me. I open the floor for discussion on the matter.

### Additional context

I was hoping to just do this myself, but it quickly proved to be a larger project than I can accomodate at the moment, so I've decided to throw my thoughts and exploratory research up here in case anyone feels inspired.

**Comment by fairyarmadillo** [comment]
Loose neodymium magnets should rarely show up as office toys at people's desks. Maybe around home desks too. Labs are another logical place.

**Comment by Muaddibo** [comment]
Just to add to this, MRI currently give 0 magnets when disassembled.
