### ISSUE TITLE
"Jerusalem artichoke fruit dessert" not better than "boiled Jerusalem artichoke"

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#69245]
### Describe the bug

boiled jersalem artichokes can be mixed with fruit to make a more enjoyable meal. the result is actually a less enjoyable meal.

Sorry, i don't know what else to write. hopefully this is pretty straightforward. 

### Attach save file

[Toga-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13323556/Toga-trimmed.tar.gz)

### Steps to reproduce

1.spawn boiled jerusalem artichoke
2.it tastes ok!
3.spawn jerusalem artichoke fruit dessert
4.it tastes unremarkable

### Expected behavior

per in-game logic and the description i would expect to make a slightly more enjoyable meal. certainly not a less enjoyable one.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/81603517/120c0dfe-867e-4ea8-8b31-17bf45ba1106)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/81603517/8414cfae-97c9-465d-9632-a9a5d2c3a530)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 767d9b6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by RenechCDDA** [comment]
Simple 1-line fix, just needs a value for the morale.

`"fun": 15,`
