### ISSUE TITLE
diving boots not recognized as wearing shoes

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#69247]
### Describe the bug

I crafted some thick kevlar diving boots and the game gave me a barefoot penalty so i shelved them. i assumed it was because these cover both the inner and normal layer, but i noticed that all variants of diving boots are considered barefoot.

Maybe this is intentional and I'm not following the logic?

### Attach save file

[Toga-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13323703/Toga-trimmed.tar.gz)

### Steps to reproduce

1. spawn and wear any diving boots
2. walk around
3. hear plap plap plap
4. you are not wearing proper shoes

### Expected behavior

I would expect to rock diving boots just like shoes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 767d9b6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by dsmky117** [comment]
I am having this issue. My _hunch_ is that the close to skin flag is causing these not be treated as shoes.
