### ISSUE TITLE
Allow mission placed and named monsters to use snippets for the names

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#69254]
### Is your feature request related to a problem? Please describe.

It would be nice to be able to create a list of potential names for the monsters placed by specific missions.  

### Solution you would like.

ehughsbaird suggested they believe it would be a small change in the section shown below.

It would be a small C++ change here (the constructor and apply function)

[Cataclysm-DDA/src/mapgen.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/f1521a8287467f2b81707ae01cdd01857c6234b7/src/mapgen.cpp#L2329)

Line 2329 in [f1521a8](https://github.com/CleverRaven/Cataclysm-DDA/commit/f1521a8287467f2b81707ae01cdd01857c6234b7)

 class jmapgen_monster : public jmapgen_piece

### Describe alternatives you have considered.

I don't know enough to know what to consider.

**Comment by GuardianDll** [comment]
mapgen (updating which, i believe, is used when mission is generated) already support custom names for monsters
https://github.com/CleverRaven/Cataclysm-DDA/blob/8e12218ad47282d5ccdcb1f90d79eb04b7ed6919/data/mods/TEST_DATA/mapgen-test.json#L222-L224

**Comment by Maleclypse** [comment]
Fixed by ehughsbaird
