### ISSUE TITLE
the integrated vehicle cooler seems to create hot air

### ISSUE THREAD

**Issue by xMordet** [CleverRaven/Cataclysm-DDA#69268]
### Describe the bug

the vehicle cooler seems to create hot air as well as cold air.

### Attach save file

[West End Anniston-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13325770/West.End.Anniston-trimmed.tar.gz)

### Steps to reproduce

go in the save file and look at the active cooler, deactivate it and reactivate it to reproduce

### Expected behavior

only cold air should be produced

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16322450/1460def1-548b-46e5-8de6-8c72bbb12615)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16322450/8ea25c24-fa55-4291-ab2e-1e12fbda6b9b)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16322450/ac9b0f42-d41f-4c4a-a1b1-833c425a4bd9)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16322450/29b04860-ee11-4716-be5f-54300cd07290)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 8e12218 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Massachusetts [MA]
]

**Comment by actually-a-cat** [comment]
This is because your vehicle does not have a muffler. Coolers producing hot air is intentional as that's how real AC works. It normally is emitted at the muffler (not that this makes too much sense) but since there is none here it goes everywhere.
