### ISSUE TITLE
Defense Mode: toggle merchant trading

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#69262]
### Is your feature request related to a problem? Please describe.

I found that playing Defense Mode without the merchant's wares is much more challenging and I find it more enjoyable.

### Solution you would like.

The starting dialogue should allow you to toggle ability to trade with the merchant. Hiring allies should be unaffected.

**Comment by ZhilkinSerg** [comment]
Players can ignore trade if they want an additional challenge.
