### ISSUE TITLE
Tie Athletics into more activities

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69260]
### Is your feature request related to a problem? Please describe.

Athletics is both kind of useless and very difficult to train. You'd think athletic ability would be highly relevant to the zombie-slaying survivor, but it's currently relegated to only affecting swimming, cycling and a minor cardio bonus.

### Solution you would like.

Since cardio represents general fitness, Athletics should represent skill and technique. As it's necessarily a very broad category, it should also have proficiencies representing more specific skills. It should influence many physical activities, and in turn those activities should provide experience towards Athletics and the relevant proficiency. In my opinion, it should affect at least the following:

- Swimming. This is the one thing it already does, there should just be a proficiency on top of it.
- Climbing. Athletics skill and especially the Climbing proficiency should make climbing safer and faster. At sufficiently high levels, it might even allow the player to climb certain walls without supports, [like so](https://www.youtube.com/watch?v=hATYErnjVdI).
- Falling/dropping. Might fall under climbing, but the ability to let yourself down from a high place without injury is certainly a learnable skill. This should decrease the chance and/or degree of injury when dropping down voluntarily, and maybe a little bit when taking involuntary falls.
- Jumping. You can actually jump in this game, but it's a highly limited ability that can only be used to cross a gap of exactly on tile, and only if it's open air and you're very lightly encumbered. Athletics skill and jumping proficiency should improve the jump distance and maximum encumbrance.
- Running. Good running technique ought to decrease stamina cost, and maybe increase speed a little bit.
- Hurdling. A prerequisite for Parkour that partially decreases the movement cost of crossing difficult terrain.
- Lifting. Probably shouldn't affect standard carrying weight, but good technique here might increase the maximum weight you can lift without injury, improve your ability to drag furniture and vehicles and count as higher Strength for vehicle modification purposes.

### Additional context

This suggestion is similar to #61967, but I disagree with the notion that just any physically exerting activity should improve Athletics (that's what cardio is for) and I think it's just as if not more important that Athletics give more tangible benefits as it is that there are more sources of Athletics training.

I also think this approach is a little more practical from a dev perspective because it's more compartmentalized. You can implement, say, climbing integration as its own project without feeling obligated to dig through the code and find every single instance of an activity that could conceivably be considered physically exerting.

**Comment by fairyarmadillo** [comment]
Rowing and biking might work well here, along the same lines as running.

**Comment by Terrorforge** [comment]
> Rowing and biking might work well here, along the same lines as running.

I would've included it, but it turns out that's already a thing. Biking is, anyway. It trains Athletics instead of driving, and there's a few proficiencies associated with it that reduce the stamina costs.

**Comment by PatrikLundell** [comment]
As mentioned, biking is implemented with 3 proficiencies and training of Athletics while using your trusty (folding) bike.

From a player perspective, a proficiency (ladder) allowing you to move heavy stuff without straining (and at all) would be very useful, in particular for characters with mere "average" STR.

Running training could also be very useful. It's probably tricky to implement a new running rate that's sustainable in addition to the current mad dash that leaves you crippled within 200 tiles. An ability that let a character increase the speed to a jog that could be sustained for a significant amount of time would be very useful for disengagement.

It would make sense for a proficiency tree similar to the biking one for use with rowing, although rowing currently isn't particularly useful when all manners of water related monsters can readily attack you from all manners of illogical directions.

**Comment by Spicyshadow** [comment]
A few dragging proficiencies could be handy. Something that gives you a bonus to dragging strength and a reduced chance of straining yourself when dragging heavy objects.

**Comment by Spicyshadow** [comment]
Some thoughts on the proposed proficiencies:

1. Dragging should probably be a different proficiency from lifting. Dragging a couch is very differant from lifting a engine block.

2. The trait fleet-footed currently represent a natural talent and good skill in running. If a running proficiency starts to represent your skill at running than fleet-footed should be nerfed. Something like turning the 15% movecost reduction to 10% and making the running proficiency a 10% movecost and stamina reduction at max level.

3. Climbing proficiency could be greatly expanded into an entire tree. The I can think off would be tree, pole, rock and rope climbing as well as wall running. Tree, pole and rock climbing wouldn´t add much to the game currently but could convince people too add more content. Rope climbing and wall running however could have some utility in the current game. Rope climbing could make you ascent ropes much quicker with a heavier load and wall running could allow a character to quickly scale one level upwards.


Some other proficiency ideas:


1. I think the though feet trait should be a proficiency tied to athletics. If your character starts walking around everywhere barefeet you would get used to it.

2. A breathholding proficiency could be usefull to stay hidden underwater longer and be able to more futher in one dive. It would be especially usefull if we where able to hold out breath on land as well. This would allow us to avoid inhaling smoke and poison gas.

3. A digging proficiency. Would give you a time bonus too digging. 

4. A tree chopping proficiency gives you a time bonus chopping down a tree with a handtool and chopping a trunk into logs.

**Comment by Amam342** [comment]
My own thoughts on this is that athletics should be your general cardio and we probably should be using the proficiency system in order to spice up the skill.

For exemple, you have walking. Walking might seem trivial, but I expect that if you walk a lot, you will stay fit. It's probably not enough to get you past level 1-2, but it's a start.
Now, if you walk a lot in the city for instance, then you could start getting proficiencies for 'city walker' which would have some bonus or other such as faster movement speed.
A good exemple of this for people who say 'why is this needed?' is the idea of walking in a swamp, where you would eventually use less moves per tiles travelled because you're used to travel there.

Note that it's not the only option. Walking a lot in a type of terrain could also improve your footing.

I'd give the same treatement to running, with proficiencies such as city running which increases your speed on asphalt, valley runner, which reduces moves per tile for long grass and the like, etc.


I really like the idea of having climbing proficiencies. I think eventually being able to climb any surface with or without equipment when your athletics and proficiencies are high enough would be great.
