### ISSUE TITLE
Blood Power Generator doesn't produce bionic power

### ISSUE THREAD

**Issue by MagioftheMaki** [CleverRaven/Cataclysm-DDA#69269]
### Describe the bug

I tried the Pseudovamp background and started with a Blood Power Generator. After using Repair Nanobots for a bit, I tried to gain some bionic power back. Instead of gaining power, I lost some instead, the blood was consumed.    

### Attach save file

[Shadowrun-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13325747/Shadowrun-trimmed.tar.gz)

### Steps to reproduce

Waste some bionic power with Nanobots, turn it off again, bleed out some monsters (didn't notice a difference with demihuman or zombie blood), refill the internal blood tank, turn the bionic on and wait 20 seconds.    

### Expected behavior

I expected to gain some bionic power, instead I lost some. One time I got 2 entire bionic power points, most of the time I lost a couple points. I think the internal tank is too small or at least refilling manually is too tedious. My guess is, that turning the bionic on is buggy somewhere, too - the stored blood is gone super fast, nothing gets turned into power - instead it feels like you turned another bionic on und randomly (sometimes) paid a few points for it's activation. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 46fb967 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Maleclypse** [comment]
Try with dragon blood
