### ISSUE TITLE
Defense Mode: MoM waves are too difficult

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#69261]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77662682/b25cf95f-dd83-4c40-b65b-84d9c6edf370)
This is one of the early MoM waves I got, even with teleporter plasma pistol I got destroyed.

### Solution you would like.

Structure the waves differently, like for example:
- Many menders
- 1/2 telekinetics
- 1 seer
Slowly scale that up with current wave number.

### Describe alternatives you have considered.

Disabling MoM waves, which isn't ideal. Since I want to experience a power fantasy end-game with all psychic powers by gaining them from fighting those waves.

**Comment by Light-Wave** [comment]
Tagging @MNG-cataclysm @Standing-Storm 
See also PR #67833 for more info and discussion
