### ISSUE TITLE
Typo broke quarterstaves proficiencies 

### ISSUE THREAD

**Issue by Sevaaas1** [CleverRaven/Cataclysm-DDA#69274]
### Describe the bug

Quarterstaves proficiency generates a error message

### Attach save file

[Meinhard-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13325984/Meinhard-trimmed.tar.gz)

### Steps to reproduce

1. Attached save file, open status windows and a error message will pop up
2. To reproduce in a new character:
3. Generate new character with the first quarterstaff proficiency (Quarterstaff familiar) 
4. Attack an enemy so that quarterstaff proficiency will start to unlock
5. Open status windows, error will popup

### Expected behavior

I expect no error to appear when opening status windows 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 6686bed [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    Xedra Evolved [xedra_evolved],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Blaze Industries [blazeindustries],
    Culinary Days Ahead [culinary_days_ahead],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Mining Mod [Mining_Mod],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana]
]

### Additional context

DEBUG    : invalid proficiency id "prof_quaterstaves_pro"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\generic_factory.h
 LINE     : 478
 VERSION  : 6686bed

**Comment by TheShadowFerret** [comment]
Maces pro also has a typo in its EoC

I shall fix this 👀

**Comment by DeftGrain** [comment]
Updated to most recent experimental as of this moment. Issue is ongoing.


Debug : invalid proficiency id "prof_quaterstaves_pro"

From the generic factory file.

Version 3afb7df
