### ISSUE TITLE
Taking down any battery breaks extension cord connections

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69271]
### Describe the bug

When I "take down appliance" on any battery in my bank, extension cords stop delivering power. Removing and reconnecting the cords seems to fix the problem.

I've tested a handful of different batteries, and it doesn't seem to matter which one you take down, the result is the same either way.

### Attach save file

[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13325849/Mindssachusetts-trimmed.tar.gz)

### Steps to reproduce

- Load up the save file
- Check that the workshop appliances are receiving power
- Take down a random battery
- Check that the workshop appliances are no longer receiving power

### Expected behavior

Removing something from one part of the electrical grid should not break connections to unrelated parts of the grid.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/fe8dba3a-335e-4b53-99b6-5f38b493ebbe)
The batteries and solar panels are directly connected to each other.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/836416e9-0aa5-40cf-9d1a-582430b4c974)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/d8007de1-0a3a-43ff-ab7c-29b6fd760710)
An outdoor extension cord runs from this point on the solar panels, to this workshop station, and then a regular extension cord runs from that to this freezer:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/bf6bbb6d-1568-4238-805c-1b3408faef5e)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/63f02a26-7c17-41c4-ac91-eda1241c6116)
Everything in the workshop area receives power just fine

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/949e68a8-fe9e-45a6-9e67-313b80bfd899)
But if I take down (seemingly) any battery, such as this one, which doesn't have any connections to anything other than the batteries next to it...
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/49284cf4-a2de-41ab-a0ab-82c06d0dada1)
Everything in the workshop loses power.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/4662c17c-c375-4ec7-a684-285b17a5bdaa)
The actual power production is fine, it only seems to be the stuff on the other side of the extension cord that breaks. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 8e12218 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

**Comment by Terrorforge** [comment]
This happened again, and it appears that what specifically occurs is that the extension cord comes loose at the solar panel connection. I'm guessing it's because that whole section is merged, and when I "take down" one battery, it removes the power connections from every part of the unified "vehicle"

**Comment by Fris0uman** [comment]
I vaguely recall that at some point when I was making https://github.com/CleverRaven/Cataclysm-DDA/pull/60681 taking down any appliance of the grid would disconnect every cable, I don't remember if I managed to fix it or not

**Comment by Terrorforge** [comment]
Well, if you did, it broke again.

**Comment by Fris0uman** [comment]
Basically happens there https://github.com/CleverRaven/Cataclysm-DDA/blob/c5cf8ed9030204ce4f29cf901b42c52d3a5f85bc/src/veh_interact.cpp#L3361
When you remove a piece of the grid it drops every cables connected to the grid. There's also a weird behaviour when if you examine a chain of wall wires and select plug from there, the powercord will not be installed in the correct position on the wall wire side
