### ISSUE TITLE
Full screen mode doesn't properly recover all of the screen after alt-tab.

### ISSUE THREAD

**Issue by Prezombie** [CleverRaven/Cataclysm-DDA#6928]
Windows 7. Dual monitors, primary 1920x1200, the other 1280x1024.

If I use fullscreen mode, and have to alt-tab out, when I try to pull CDDA back up, the application covers most of the screen, but a thin strip along the right and bottom of the screen isn't drawn, showing whatever's below the CDDA 'window'. The game functions as is if it is drawing on the whole screen, a bit of the sidebar gets chopped off, rather than resizing to the "new" size.
##

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-7145, Windows XP SP3 x86, tiles, both software and hardware rendering. If this is still happening, ping me.
