### ISSUE TITLE
Cannot put a “wheat–free deluxe sandwich” into a “zipper bag”

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#69294]
### Describe the bug

This is surprising because the sandwich is half a cup, 0.64 lb, and has a max length of 1 inch, while the zipper bag holds up to 1 cup, 1.7 lbs, and 3 inches. Seems like it ought to fit. Or am I doing something wrong?

### Attach save file

[Gulf Breeze-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13327581/Gulf.Breeze-trimmed.tar.gz)

### Steps to reproduce

In the attached save, attempt to (i)nsert a sandwich into a zipper bag. Both are in inventory. Try the gallon–sized bags too!

### Expected behavior

Sandwich goes into bag.

### Screenshots

![Screenshot from 2023-11-12 00-50-31](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/3e4420b9-1aaa-4517-a8c5-eeb58f05340a)
![Screenshot from 2023-11-12 00-51-04](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/f68068f7-3998-47b9-b971-97140b6eb0b9)
![Screenshot from 2023-11-12 01-07-09](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/be901ce8-1083-44fb-beab-0e6bde7b55b8)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 38 (Thirty Eight); Release: 38; Codename: ThirtyEight; 
- Game Version: 0.G-5091-ge09bf78d3d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Railroads [railroads],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by GuardianDll** [comment]
Your zipper bag in the almost full pocket - there is enough space for zipper bag, but not enough space for zipper bag with sandwich. Wield the bag, put a sandwich, and then try to put it into the backpack or where you need it

**Comment by db48x** [comment]
Oooh, I get it now. The zipper bag is inside a toolbelt or whatever, and the toolbelt cannot accomodate the size the zipper bag would expand to once the sandwich is inside.

Maybe it should just take the zipper bag out of its container first.

**Comment by RAldrich** [comment]
I think that having it auto remove/wield the nested container would run into problems when you consider the rest of the insertion code. I can see why you might desire that behavior when manually inserting like you are here, but what about when you 'g'et an item or are using the advanced inventory manager?

It would take an extra check or option to toggle the behavior. Which is maybe fine, but does add complexity to an already complicated system.

**Comment by db48x** [comment]
I am just talking about specifically when inserting an item into a container, which doesn’t or shouldn’t conflict with what it does when you get an item or use the advanced inventory manager. Once the container is chosen, it would then check to see if it would still fit in its parent container. If it would not, then it would remove it from the parent container, perform the insertion, and then either place the container back into inventory, drop it, or place it on a near–by flat surface, just like what happens when you finish crafting an item you cannot hold in inventory.

I haven’t yet looked at the code though, so possibly that would be more difficult to implement than I expect.
