### ISSUE TITLE
Puddle of Blood prevents placement of Step Ladder

### ISSUE THREAD

**Issue by Godfire221** [CleverRaven/Cataclysm-DDA#69307]
### Describe the bug

Puddle of blood prevents Stepladder placement

### Attach save file

N/A

### Steps to reproduce

1. Pulp enough corpses on a tile to create puddles of blood
2. Cannot place ladder on puddle of blood

### Expected behavior

Place ladder onto the bloody floor, but cannot.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/150617424/2cfdc047-89ab-4ed3-8c3a-1b9e52b2f94f)

### Versions and configuration

Cataclysm-DDA experimental build 2023-11-12-0838 Windows Sounds x64

**Comment by ZhilkinSerg** [comment]
OSHA approved
