### ISSUE TITLE
Add craft of "khattabka"(conversion of 40mm into a hand grenade)

### ISSUE THREAD

**Issue by Afavertov** [CleverRaven/Cataclysm-DDA#69308]
### Is your feature request related to a problem? Please describe.

40mm is only useful for selling it. Grenade launchers too heavy to carry around and useless for car(M2 browning is already overkill)

### Solution you would like.

Being able to turn useless munition into useful, but weaker handgrenades.

**Comment by tenmillimaster** [comment]
Can you demonstrate that other types of fuzes one could find (from flashbangs and the like) can be threaded into the cartridges for 40mm?

**Comment by Afavertov** [comment]
In game 40mm using black powder, so it can be ignited with regular(that using in pipe bomb) fuze or flashbang one.
IRL 40mm was midified by training grenade fuzes. IDK about NATO grenades, but judging by photos fuze from flashband will fit in 40mm.
And yes.  On photo this is soviet grenades.(40mm VOG-25, 30mm VOG-17 and VOG-17M.
![300px-Khattabka-vog-17-25-1](https://github.com/CleverRaven/Cataclysm-DDA/assets/89081329/9ae39616-73d5-4ff8-a937-7ac02bc2538a)

**Comment by ZhilkinSerg** [comment]
CDDA takes place in New England. I am pretty sure there aren't a lot of Soviet grenades there.

**Comment by Afavertov** [comment]
I dont think that soviet and NATO grenades following different physics laws. Both has explosives inside.
Ant fuze and maybe additional gunpowder is more than enough to detonate it.

**Comment by tenmillimaster** [comment]
![m213-001.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/7764202/cbe9fce0-9681-4815-b81e-dac771260947)

![y6s2mx2rdsd21.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/7764202/877dcb3b-41e9-48a9-8337-011bfe50fff2)

This fuze does not really look like it would thread into these grenades.

**Comment by Afavertov** [comment]
M433(HEDP) has a shaped charge, so flashbang fuze may not fit by lengh, but it not bigger in diameter.
And just look at guerilla wars. Any weapon or munition can be modified in most unexpected way.
Also this greandes was already used by drones, so removing safety from detonator(like rotor) can even turn it into impact grenade.
![967703_original](https://github.com/CleverRaven/Cataclysm-DDA/assets/89081329/516027a6-512e-4c98-8dd5-b86761f6c84f)
![main-qimg-497bcc78d94851c17b52a4b820c65fce-lq](https://github.com/CleverRaven/Cataclysm-DDA/assets/89081329/bd4660c9-6f44-45ec-9265-1302f0cd0201)

**Comment by GuardianDll** [comment]
\> Any weapon or munition can be modified in most unexpected way.

Yes, but we need a confirmation and real example it is indeed possible, and safe enough

> Also this greandes was already used by drones

Again, proofs is all we need

**Comment by Afavertov** [comment]
There is even guide on youtube about turning it into drone bomb by removing safety from fuze.
https://www.youtube.com/watch?v=8C46LqwIEPU

**Comment by tenmillimaster** [comment]
OK, so you've convinced me that it's possible to defeat the rotation counter safety, creating a impact grenade.

I also see that the ogive is easily removed from the fuze body, but, like you, I also see that the fuze body from most NATO grenade's fuzes is too long - there's not really a clear path between the auxiliary fuze and the ogive as the firing pin assembly is in the way. I'm not convinced that this wouldn't be enough to prevent a grenade fuze from setting off the m55 stab primer, at least reliably so.

I guess you could remove the ogive and fuze body, keeping only the bottom part, and find a way to thread the hole where the m55 stab detonator is, then thread the fuze body into it...I'm not sure if even that would be enough distance to insert a grenade fuze body, though.

**Comment by GuardianDll** [comment]
i suppose we can limit ourselves with impact grenade conversions, but how safe the operation is? how much safety equipment and skills the character need to have to say "yep, i can do it"

**Comment by Afavertov** [comment]
Fuze too long? Who cares, it will work. It isnt wide so most important part of it(with detonation charge)  will fit it. Yes it will ugly and stick out.

About skills for operation. If character not stupid as fuck he wont detonate it because pulling out rotor and hitting detonator with some force is different things, but it easy to fail and ruin fuze. I think 5-6 mechanic is enough. Making proper supressor is harder(8 mechanic) than removing funny rotor.

**Comment by tenmillimaster** [comment]
Making or altering the bottom of the fuze housing to be sufficiently long enough wouldn't be an impossible operation.

**Comment by Afavertov** [comment]
Fuse IS long enough. It even longer than needed, so just attach it with some glue or tape to grenade.

**Comment by tenmillimaster** [comment]
> Fuse IS long enough. It even longer than needed, so just attach it with some glue or tape to grenade.

No I'm saying that the fuze looks like it is too long (I haven't actually checked). To make up the difference one would make a taller fuze body.
