### ISSUE TITLE
Pumpkin seeds wrong ammounts?

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#69309]
### Describe the bug

Processing one pumpkin into seeds used to give 24 seeds, now gives just one seed and pumpkin cuttings.
This presents problems when you want to sow them and when you want to make seed paste as it needs 50 seeds (a whole industrial production of pumpkins) to make just one serving.

### Attach save file

N/A

### Steps to reproduce

Open crafting window with enough survival skill.

### Expected behavior

Pumpkin giving more seeds for whatever reason the player needs.
Irl pumpkins have lots of seeds, a lot more than 24, but that seemed a good number of seeds to be produced from a pumpkin for the game.

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: cc4cb54 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Pixel's Various Fuckery [Pix's Shit],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    Blazemod - Vehicle Additions Pack [blazemod],
    Magiclysm Revamp and Additions [magicrevamp],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Mind Over Matter [mindovermatter]
]

**Comment by KeremBabaG** [comment]
might be affected by charge changes somehow

**Comment by fairyarmadillo** [comment]
A single "pumpkin seeds" item now represents one entire cup of seeds rather than a single seed (which was weird and inconsistent in a lot of places), so the problem is that you should need fewer pumpkin seeds to make seed paste. I'll make a PR to fix this.

**Comment by Shibimon** [comment]
That's great but still be weird to be able to sow just one pumkin from an entire pumpkin.
Im not aware if some other change made seeds OP or whats the reason behind the decision abuot making the serving of seeds just one item.

**Comment by fairyarmadillo** [comment]
> That's great but still be weird to be able to sow just one pumkin from an entire pumpkin. Im not aware if some other change made seeds OP or whats the reason behind the decision abuot making the serving of seeds just one item.

It's not one seed growing one pumpkin. A single tile represents many plants, and can produce many pumpkins based on your survival skill. If you have more skill you can get up to 9 pumpkins with a single seed.

See
https://github.com/CleverRaven/Cataclysm-DDA/pull/65924
https://github.com/CleverRaven/Cataclysm-DDA/pull/67711

The same goes for grains, strawberries, etc. A single "wheat seeds" plants one tile of wheat, which is several square feet of plants, not a single stalk.
