### ISSUE TITLE
Using corded electric chainsaw drops it's cord

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#69315]
### Describe the bug

For some reason, copping a tree using corded electric chainsaw drops the cord item on the floor, despite chainsaw is left intact 

### Attach save file

N/A

### Steps to reproduce

Spawn a corded electric chainsaw and a cord
Extend chainsaw with cord, connect to some vehicle
Activate the chainsaw, chop down the tree
The cord item for some reason is dropped on the ground, but chainsaw still works as expected 

### Expected behavior

Cord is still in the chainsaw after chopping 

### Screenshots

![image-52](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/c4e454e8-b886-4b44-ad09-8bccd07006ba)
![image-54](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/e6062523-9711-4c4f-8ddf-8d2e88992a11)
![image-55](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/57e9deb8-4715-4317-8d81-d1e93415c890)
![image-58](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/1c1413ca-37d4-4734-ba8a-d0184f0e5160)

### Versions and configuration

 e7e0c46

### Additional context

@Kamayana I'm sorry to bother you again, but may you check what's going on here?

**Comment by Kamayana** [comment]
Can replicate.
