### ISSUE TITLE
Game stops working when trying to accept Rubik's first mission.

### ISSUE THREAD

**Issue by FellsHollow** [CleverRaven/Cataclysm-DDA#69325]
### Describe the bug

When I try to accept the mission from Rubik to scout out Hub01, the game freezes. No crash happens, per se, but the game freezes. When I click anywhere on the screen it goes translucent and says "____ is not responding" and I can choose to wait or close. 

### Attach save file

[Hildreth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13330603/Hildreth-trimmed.tar.gz)

### Steps to reproduce

1.  Go through a conversation with Rubik leading up to where he asks you to scout out a location for him.
2.  Try to accept the mission.
3. The game freezes/hangs but does not crash like a classic CDDA crash.

### Expected behavior

I expect to be able to accept his mission without any issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 04484e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by oosyrag** [comment]
Waiting out the freeze results in 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/26992604/c8857c32-b0bb-4145-80bc-8ac2d37214b5)

So the game isn't completely frozen, it's just taking a really really long time to find hub01. Because it can't find it.

**Comment by FellsHollow** [comment]
Okay, that makes sense. What's the solution?

**Comment by oosyrag** [comment]
Well the error shown is the result of waiting, and the problem is still there that it couldn't find a hub01. I think the only solution for your existing world would probably be to debug spawn hub01 in somewhere manually before accepting the quest.

**Comment by FellsHollow** [comment]
I see. Well, I'll look into it. Appreciate your assistance.

**Comment by oosyrag** [comment]
A fix would involve something to guarantee hub01 gets placed in range at world gen. Unfortunately that would not retroactively apply to your save.
