### ISSUE TITLE
Bayonets add useless firing mode to guns

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69337]
### Describe the bug

Adding a bayonet to a firearm allows you to select the bayonet as a firing mode in order to aim the reach attack.

However, as of #69201, bayonets no longer have reach attacks. As a result, the "bayonet" firing mode does nothing at all except clog up the firing mode menu.

### Attach save file

Trivially reproducible

### Steps to reproduce

1. Attach a bayonet to a gun
2. Switch firing mode to the bayonet
3. Attempt to fire the bayonet; note that nothing happens.

### Expected behavior

No useless firing modes that just introduce clutter and confusion.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: d39ddd6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

@tenmillimaster mentioned that they're planning to give some very long guns like the flintlock musket bayonets with reach attacks, so those particular examples would presumably need to keep the bayonet firing mode.

**Comment by tenmillimaster** [comment]
Ah heck.

**Comment by tenmillimaster** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/7764202/d215d56b-ef80-43f6-a629-6fce8c009a0f)
Makeshift bayonet with firing mode

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/7764202/1e7cbc5f-6fc3-4ddc-bb85-b62e7b8872e0)

Makeshfit bayonet with firing mode deleted.

The bayonets do not add any melee damage properties without the firemode defined. This will require some C++ to  fix, I think.

**Comment by tenmillimaster** [comment]
I've gone and reconfirmed that this exists, that the firing mode is added and doesn't do much.
However, this is the way the pistol bayonet used to work pre- #69201. 
I would like for melee gunmods to add their stats without adding a fire mode, but IMO this is more of a feature request and not a bug.

**Comment by Terrorforge** [comment]
Regardless of why it's there or how long it's existed, a gun having a firing mode that does literally nothing has to qualify as a bug.

**Comment by tenmillimaster** [comment]
I asked Kevin about it: > yes it's a good thing, no protest there, but it's not a bug
