### ISSUE TITLE
Add more mill recipe

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#69338]
### Is your feature request related to a problem? Please describe.

For example
roasted coffee beans → coffee powder
dehydrated meat/dehydrated fish/dehydrated lobster → protein powder
dahlia root/potatoes/irradiated potatoes/prepared ground nuts/cooking banana/irradiated cooking banana/cattail rhizome → starch

### Solution you would like.

As mentioned above

**Comment by fairyarmadillo** [comment]
Protein powder's current recipe is actually incorrect, and doing it in a traditional mill would be even more incorrect. Protein powder is made with a spray drying machine, which is something we could add but would probably need like a food processing plant location to go loot it from.

**Comment by Rocket-F-1024** [comment]
> Protein powder's current recipe is actually incorrect, and doing it in a traditional mill would be even more incorrect. Protein powder is made with a spray drying machine, which is something we could add but would probably need like a food processing plant location to go loot it from.

Are other two correct？

**Comment by fairyarmadillo** [comment]
Isn't the starch in game a wet recipe? Mills are for dry things.

Mills probably grind things too finely for coffee, and you typically want to grind a fairly small amount of coffee at a time. Mills are big and grind many pounds of flour at once.
