### ISSUE TITLE
[Menu][Consume Item] Roughly display the calories burned during the day

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#69332]
### Is your feature request related to a problem? Please describe.

I find it very difficult to estimate how many kcal I have burned per day through working.
It usually leads to me losing weight. Then I eat so much again that I become overweight.

### Solution you would like.

Would it be possible to provide a rough overview of the calories burned in the item consumption menu? 
As already available for consumption today. Only roughly, without kcal information,

### Describe alternatives you have considered.

None

**Comment by ZhilkinSerg** [comment]
I think you can already check activity tracker through debug menu.

**Comment by Terrorforge** [comment]
You can get exact calorie consumption by wearing a fitness band (put it on autopickup, they're hard to find intentionally but occasionally show up on zombies) or installing the calorie tracker CBM, but I think it would be fair if it showed a rough estimate when you don't have one, like it does for consumption.

But yes, you can see your detailed calorie consumption/spending statistics for the last 30 days through Debug Menu->Info->Check Game State.

Also fwiw there are virtually no penalties associated with being just barely overweight, so it's totally fine to just eat until you hit that point and then chill out drinking water.
