### ISSUE TITLE
The Isherwood cat is a murderer!

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69349]
### Describe the bug

I finally managed to finish the Isherwood cat quest, and as soon as I did the monster attacked my character. I then went to my car and read the book Claire gave as a reward, and when finished I saw the monster has attacked Claire as well, and she's bleeding.

### Attach save file

Can't upload. Compressed file 31 MB vs 25 MB allowed.

### Steps to reproduce

1. Get Claire Isherwood's cat quest.
2. Save scum until you manage to herd a cat into the house and lock it in there.
3. Try to capture the cat in the supplied cage.
4. Find that you can't because you have to tame it first using non supplied cat food.
5. Return later with cat food.
6. Tame cat and capture it.
7. Return to Claire and try to claim the quest.
8. Fail until you manage to guess that you have to let the monster out first.
9. Let the cat out.
10. Talk to Claire and finish the quest.
11. Immediately get scratched by the cat.
12. Walk back to the car and read the quest reward book.
13. Notice that Claire is reported to have bled a number of times and is still bleeding when you finish checking the book out.

### Expected behavior

The monster wouldn't behave like a cat, but rather not attack its new owner, or at least act cat like in a less offensive manner by running away. At a guess, the quest should affiliate the cat with the Isherwood clan.

### Screenshots

![Screenshot (286)](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/2cfdbecc-6834-4435-a571-d0bfe2f5a406)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-5105-g0a3f4ca1bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms.

### Additional context

Yea, I don't like the specicidal invasive vermin...

**Comment by andrei8l** [comment]
Sorry for going off topic

> Can't upload. Compressed file 31 MB vs 25 MB allowed.

Can you upload that to a third party like https://send.vis.ee/ ? I'm pretty interested in seeing why trimming isn't effective enough in this case.
