### ISSUE TITLE
Climate control mutations are currently overpowered

### ISSUE THREAD

**Issue by ferociousdork** [CleverRaven/Cataclysm-DDA#69343]
### Describe the bug

Climate control mutations ((High) heat/cold tolerance) are currently overpowered. Cold tolerance gives about 37 points of climate control heat instead of the advertised 10. This trivializes winter exploration, since frostbite is unlikely except in the worst weather. My survivor with this mutation was Comfortable in -8C weather being naked.

I assume this is caused by the refactor in #68796, but I didn't verify this. It works fine in an experimental release from September.

### Attach save file

N/A

### Steps to reproduce

1. Start in winter, Day 1, early morning;
2. Go outside and strip, if necessary;
3. Debug toggle the "Cold tolerance" mutation, and observe body part warmth.

### Expected behavior

Cold tolerance should give 10 points of climate control heat.

### Versions and configuration

Recent experimental.

**Comment by prharvey** [comment]
I believe I know what the cause is, should be easy to fix.
