### ISSUE TITLE
Luliya's dialog is broken

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69359]
### Describe the bug

When meeting Luliya at the Exodii base you can as about English, her name, and exit the dialog indefinitely.
As far as I can tell from exodii_Luliya.json you're supposed to have exhausted the first two topics after going through them once, but they're always present.
Also, you're supposed to be able to ask her about music, but that's doesn't appear either.

### Attach save file

Compressed file too large...

### Steps to reproduce

1. Go to the Exodii base and locate Luliya.
2. Talk to her and ask about her talking English and what her name is.
3. Exit dialog.
4. Talk again.
5. See same options.
6. Return after more than 3 days (as I think the music dialog option checks for, which doesn't make any sense to me).
7. See the same dialog options.

### Expected behavior

1. Once you've asked about English that dialog option should be removed.
2. Once you've asked her her name that dialog option should be removed.
3. The music option should appear if you return more than 3 days from meeting her(?), but really should be present immediately, as a wait makes no sense unless it's intended to keep the frequency down, in which case the option should appear immediately on the first visit and then be blocked until 3 days (or whatever) from the last time a jamming session occurred (and not if the topic was brought up but no session occurred).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-5105-g0a3f4ca1bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms.

### Additional context

- The name dialog can be suppressed if the checks use the same "context" value as the ones written by the dialog choice ("name).
- The English check can be suppressed if the correct variable is used ("u_not_english_luliya")  as well as the correct "context" ("language").
- I'm not able to get the music dialog to show up. It's very probably the name check "context" is wrong (should be "name"), but I can't fiddle the comparison to evaluate to true. It could be that "type" should be "timer" (as that's what a lot of other tests seem to use), but that's just a guess. There might also be a need to check for the min/max value of the meeting timer.
On the other hand, the test syntax seems to be copied from TALK_TEST.json. The game crashes if the "u_met_luliya", "general", "meeting" set is used for the test.

Edit: It's also questionable to require superhuman INT to unlock the Arabic language topic. The old character generation system didn't allow for an INT higher than 14 (apart from the completely free system). It's D&D that allows for 18 as a character generation max (before racial modifiers).

**Comment by MNG-cataclysm** [comment]
/confirmed

Luliya's dialogue is indeed busted.
