### ISSUE TITLE
Make diving into water have a chance of cancelling Spore Dusted

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#69352]
### Is your feature request related to a problem? Please describe.

See title.

### Solution you would like.

So you got spore dusted while theres water nearby. Would be cool if diving into water has a chance of cancelling the effect.

It was discussed on the devcord if wetness per body part could work, but that also could mean you can sweat them off. Diving into water means a limb will be soaked, not just damp.

**Comment by fairyarmadillo** [comment]
There are probably a few effects that should do this, like corroding, on fire...it might be worth making submersion something the effect system can check for.
