### ISSUE TITLE
Futile Fighter with enough kills might become an NPC?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#69357]
### Is your feature request related to a problem? Please describe.

I've got a futile fighter who's been following me around for a little bit now, and he's doing ok with me to back him up. I feel a little bad that there's no way for him to be anything more, given the (not so) futile nature of his fight.

### Solution you would like.

If a futile fighter gets X kills or kill assists, turn them into an NPC. It seems deeply unlikely that it would happen naturally, but it would be nice to be able to shepherd someone into a more robust survivor.

### Describe alternatives you have considered.

Leave it be. They'll die soon enough anyway.

**Comment by PGR-14** [comment]
I'd like for that kind of stuff to happen, there's already precedent w/ that one NPC story who used to be a feral, so it'd work w/ the lore, as for the JSON? Maybe it could just remove the Futile Fighter (Not kill), & put down an NPC in it's spot (Neutral, w/ a new backstory?). You could do a similar thing w/ that parent one.

**Comment by detahramet** [comment]
While it would be cool to have (as would a way to save more people on C-Day that aren't  neccesarily NPCs as well), its not likely to get added to Vanilla. The Futile Fight, Gawky Guardian, and so on are non-hostile ferals, and all ferals are basically just still-living zombies.

That said, I think it could have its own in-repo mod, though I'm far from the authority on that.

**Comment by ADekema** [comment]
Maybe you should have a very small chance to return them to normal or convince them to follow you if your speech skill is high enough. Something like you being able to convince the futile fighter or overconfident officer that you need protection or telling the petrified/panicked person that you can protect them. You would have a companion for a while that you could equip and stuff. They could turn into a normal NPC after a while or they could turn into a full feral while the player is close and has presumably armed them.

**Comment by PGR-14** [comment]
I completely agree! Stuff like this should be a core aspect of the game, maybe you could convince the parent one for you to get their kid (Either a survivor (VERY rare) or a zombie child), & have a chance for them to realize what's happening, or attack you for hurting their kid (Feral, or maybe just hostile?).

**Comment by Jan-Blasiak** [comment]
This sounds great, I'd love to have it
