### ISSUE TITLE
Monster Character Aggro isnt tracked through saving/loading

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#69363]
### Describe the bug

Monsters that sepparatedly track monster and character aggro become hostile when the game saves and loads.

### Attach save file

N/A

Due to being a save/loading error.

### Steps to reproduce

1. Spawn a bunch of yrax deltas and a zombie. They will anger and fight without aggroing the player.
2. Quicksave and load.
3. The deltas are hostile now

### Expected behavior

Saving and loading has no effect on aggro.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 0.G-5067-g5f06425034-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock]
]

**Comment by Maleclypse** [comment]
loaded a world and followed instructions and confirmed
