### ISSUE TITLE
Aqueous sprite being annoying

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#69360]
### Describe the bug

When being a post-threshold slime (All of them), usually the player's sprite is a slightly dark green, but every so often it just becomes light green. Sometimes after having the correct color, it changes to the light green version instead.
Might be intentional?
If there's a way to force the dark green one, I'd be ok w/ it.

### Attach save file

N/A

### Steps to reproduce

just boot up any slave & make yourself a post-threshold slime (Debug -> Player -> Player/NPC -> Mutation -> Mutation Category -> Slime -> Post-Threshold mutations)

### Expected behavior

It probably should be dark green (The sprite has a better quality), but it could be intentional

### Versions and configuration

-Windows 10
cdda-windows-sound-x64-2023-11-10-1610

### Additional context

I'm only doing this w/ debug menu (Doing a scenario for myself)

**Comment by fairyarmadillo** [comment]
It's not a fix for the actual tileset issue you're having (might help if you tell us which one you're even using), but you can clear this up in your game by pressing [ and then selecting any mutations you don't want to show on your sprite, and press , over them. This will toggle their visibility.

**Comment by PGR-14** [comment]
Chibi Ultica; I tried different combinations of them, but it didn't work

**Comment by PGR-14** [comment]
A bit more context, I've had it happen w/ or w/out integrated mods, & I added a few extra mutations to the SLIME category (In the game's files, not w/ a mod)
