### ISSUE TITLE
RUN_NPC_EOCS Dialogue function is non functional.

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#69362]
### Describe the bug

As per title, it appears that while such dialogue functions are loaded by the game, they don't actually trigger

### Attach save file

N/A

### Steps to reproduce

1. Travel to the Refugee Center where the sole current use of this function is located (the guard shift)
2. Wait for more than an hour so the related EOC triggers.
3. The guard shift doesnt happen.

### Expected behavior

The guard shift triggers

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 0.G-5067-g5f06425034-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock]
]

**Comment by lispcoc** [comment]
It seems to be working correctly in my environment. Which NPC is the problem?

**Comment by John-Candlebury** [comment]
You are right, the effect was subtler than expected.

What prompted this issue was the EOC found in my current pr: https://github.com/CleverRaven/Cataclysm-DDA/pull/69364/commits/ef8127a3e61130ec786be4b18e0fa69db334cad1

If documentation is correct, this should be enough to cause the EOC  to run in every npc in the current bubble, but it isnt, and I couldnt diagnose the cause from setting breakpoints. (I suppose its possible for the docs to be wrong)

**Comment by lispcoc** [comment]
I was the one who advised GuardianDll regarding this document, but it appears that the information I provided was incorrect.
The correct behavior is as follows

| `local` | `unique_ids` | result                                     |
|--------|--------------|--------------------------------|
| false   | not set         | Do not run                            |
| true    | not set         | EoC runs for current bubble |
| false   | set                | EoC runs for global              |
| true    | set                | EoC runs for current bubble |

I think setting `local` to true will probably give you the desired behavior.

**Comment by John-Candlebury** [comment]
Ah thank you, that get the EOC to run. Really appreciate the help.

(No idea why the player gets teleported but I must have missed something else)

**Comment by John-Candlebury** [comment]
@lispcoc  since you clearly are more familiar with this than me, do you know why the following snippet causes the player to teleport, so long as they have followers

```
  {
    "type": "effect_on_condition",
    "id": "EOC_AFS_AUGUSTMOON_SHUTTLE_TP",
    "effect": [
      { "u_run_npc_eocs": [ "EOC_AFS_TEST_AUGUSTMOON_TP" ], "local": true }
    ]
  },
  {
    "type": "effect_on_condition",
    "id": "EOC_AFS_TEST_AUGUSTMOON_TP",
    "condition": "u_following",
    "effect": [ { "u_teleport": { "global_val": "location_variable" } } ]
  }``
```

Does the player somehow count as an NPC as far as `npc_run_eocs` is concerned?

**Comment by lispcoc** [comment]
Apparently the problem is not with u_run_npc_eocs, but with teleport::teleport_to_point(), which is used for teleporting
Regardless of whether you are teleporting a player or an NPC, you are teleporting the player along with NPC.

I think we can fix it as follows, could you please try it?

```diff
diff --git a/src/teleport.cpp b/src/teleport.cpp
index 2952a4bd03..1864049ac7 100644
--- a/src/teleport.cpp
+++ b/src/teleport.cpp
@@ -199,13 +199,16 @@ bool teleport::teleport_to_point( Creature &critter, tripoint target, bool safe,
     }
     //player and npc exclusive teleporting effects
     if( p ) {
-        g->place_player( p->pos() );
         if( add_teleglow ) {
             p->add_effect( effect_teleglow, 30_minutes );
         }
     }
     if( c_is_u ) {
         g->update_map( *p );
+    } else {
+        if( shifted ) {
+            g->place_player_overmap( project_to<coords::omt>( avatar_pos ), false );
+        }
     }
     for( const effect &grab : critter.get_effects_with_flag( json_flag_GRAB ) ) {
         critter.remove_effect( grab.get_id() );
```

**Comment by John-Candlebury** [comment]
Everything is working with that fix. Thanks a lot.
