### ISSUE TITLE
Food displaying as old/rotten only after consumption

### ISSUE THREAD

**Issue by Plaidstone** [CleverRaven/Cataclysm-DDA#69371]
### Describe the bug

Since my most recent return to the game (my first fresh install in, uh, a long time) I've been having some weird behaviour with food. Stacks of a single food item will change from fresh to old or rotten after I eat some of the food; I figured this was because the food was at different levels of spoilage, and was intended. Today is the first time it has happened retroactively; I ate food with no label in the consume menu, and then the game log told me what I had just eaten was old or rotten, and the stack was updated to reflect this.

### Attach save file

[Tunkhannock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13344663/Tunkhannock-trimmed.tar.gz)

### Steps to reproduce

1. Start a game
2. Find some fridges
3. Eat stuff until something weird happens

### Expected behavior

I thought the food would be displayed as old or rotten if old or rotten, rather than being surprised by its status after eating.

### Screenshots

I haven't found another mislabeled rotten item in a few minutes of poking around (rural areas, bah), but I managed to screenshot other unexpected behaviour- food being unlabeled being labeled as _fresh_ after consuming the first item (isn't fresh food supposed to be shown by default if the stack has varying freshness?)
![Screenshot (51)](https://github.com/CleverRaven/Cataclysm-DDA/assets/67881064/67d0b667-7bf3-43f8-8ea0-0c1d8d0aa083)
![Screenshot (52)](https://github.com/CleverRaven/Cataclysm-DDA/assets/67881064/57bfb8ed-acd1-4e4d-b59c-1334e7becf0f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: b0c4ba0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by andrei8l** [comment]
You screenshots show item collation rather than a bug. All items of the same type are grouped under one inventory entry and internally sorted by spoilage. You can find more details in #63270

**Comment by Plaidstone** [comment]
Is that also the case for the other behaviour mentioned? Food being unlabeled, but when you eat it, it's suddenly rotten? I don't just mean the food that's left over- I mean the food the character _just ate,_ without warnings, that did not appear old or rotten in the menu, being listed in the message log as rotten and making the character ill.

**Comment by PGR-14** [comment]
No, It's just an indicator, kind of. Let's say you have some milk, fruit juice, some jerky, soup (sealed), clean water, & some foodplace. The milk would be at the top, then juice, then Jerky, then soup, & then water/foodplace. They're sorted by the spoilage of the longest-lasting item of that type (Milk (Rotten) v Milk (Fresh)) then sealed (sorted w/ previous rules), then non-perishables (sodas, protein rations, etc. I think they're sorted alphabetically), & when you eat something, the list gets updated. You're not actually eating the rotten food, you're just looking at the food you have left.

**Comment by Plaidstone** [comment]
You're misunderstanding. I **DID** eat rotten food. It was milk, unmarked, at the top of the consume menu. When I ate it, the message in my message log was the usual "ick, rotten" message, and my character got sick. Again, it _was not_ labeled as rotten in the consume menu, and no warning was given when I attempted to eat it.

Apologies for the screenshots confusing things, I probably shouldn't have included them, they don't reflect the specific issue I was trying to report.

**Comment by PGR-14** [comment]
Oh, sorry, I didn't realize, sorry.
One of 2 things could've happened: Milk rotted while you ate it (It spoils fast), or it got confused on which to eat

**Comment by Plaidstone** [comment]
The first one is possible, I guess, but I would be surprised (it happened immediately afterwards as well, with unmarked lunch meat being labeled (old) in the "you eat your X" message).
For the latter, this was milk from a single container in a randomly generated fridge; should individual units of the same liquid, in the same container, be assigned different spoil timers during world gen? Is that expected behaviour?

**Comment by PGR-14** [comment]
Not really, perhaps it could be a singular "age" value for everything in the container (When generated), so that everything spoils at the same time (Along w/ arbitrary spoilage values for the player) & so we don't have Old & Rotten.
A different fix could be grouping rotten, old & fresh food separately.

**Comment by andrei8l** [comment]
Your log shows that you did indeed eat rotten food and it's nearly impossible to do that by accident. However, there's no indication why. If you can reproduce this, it's be great to have a save from right before you start eating.
