### ISSUE TITLE
Headlight in a smashed car won't go away when car is gone.

### ISSUE THREAD

**Issue by PartranTiger** [CleverRaven/Cataclysm-DDA#69370]
### Describe the bug

I found a wreck with a headlight on, coming from the back end of the car not the front, and when I couldn't turn it off with a dashboard I smashed the whole car with a sledge hammer. The light remained with no source.

### Attach save file

N/A

### Steps to reproduce

N/A?

### Expected behavior

Should not have sourceless lights

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/103401582/4d34d8ba-6779-4ab2-86a2-258319392ff7)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/103401582/3e7937a4-69f5-499b-8818-535660b88fa8)

### Versions and configuration

OS: Windows 10
Version b0c4ba0

**Comment by andrei8l** [comment]
Save file is pretty important here. Is the light still there on reload?

**Comment by PartranTiger** [comment]
I didn't save the game after finding it. I alt-f4'ed out so it wasn't there infront of my base.
