### ISSUE TITLE
Compressed save too large to upload

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69374]
### Describe the bug

The save compression functionality results in a compressed save that's still too large.

### Attach save file

Obviously not possible... Here's a dropbox link, though.

https://www.dropbox.com/scl/fi/bigzojk9671z4ol7a3kcj/West-Kingston-trimmed.tar.gz?rlkey=cc4fs66bmnjphqlcsms9smcsh&dl=0

### Steps to reproduce

1. Play a lot.
2. Make a bug report and generate a compressed save.
3. Find that the save is still too large to be pasted into the report.

### Expected behavior

Compressed saves should be possible to be passed with the bug reports they're generated for.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-5105-g0a3f4ca1bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms.

### Additional context

Asked to file this report by @andrei8l.

**Comment by andrei8l** [comment]
Thanks!

There are many MiBs of uncompressible garbage like this
```JSON
"fetch_history":{"JdCBnENlyh":10683374,"cezPpsMKRd":10683374,"GOaQjpESpA":10683374,"jbQrzfyBLC":10683374,"CmzYJMawmP":10683374,"TdweMIetPN":10683374,"DxnECzngog":10683374,"bqXjbcIwGb":10683374,"AFPKPzEeAr":10683374,"CFocYNwZrJ":10683374,"BavScCKHXF":10683374,"HQuZejknUN":10683374,"reTSCkvcmO":10683374,"EIWQeJRYZm":10683374,"AwiHBDsJHq":10683374,"BdJNvkmnkt":10683374,"xmdHxQjseA":10683374,"alJOKwXrAV":10683374,"AYpqKWIocs":10683374,"moUbbWdQSO":10683374,"DAMJOdsBCL":10683374,"cwruPlMJXk":10683374,"qyrMwfkswr":10683374,"AABOaJVbRs":10683374,"GgTnxWFjFb":10683374,"ALgnwrJALg":10683374,"BPwaCHfCqr":10683374,"WHfBrDjMyx":10683374,"eesTlEYKUJ":10683374,"FuwosWWMFr":10683374,"eYYPXGguqb":10683374,"ArYFuXFvMW":10683374,"FIqQhLbToM":10683374,"DeVDrcFQqq":10683374,"UHDjdsfncL":10683374,"wDFMgGjSIm":10683374,"CKjVOvCZQZ":10683374,"ABfAFGNgzw":10683374,"UnMMPoYdwQ":10683374,"pKchykUmWr":10683374,"DPhxkohpGh":10683374,"CgtFgtyMnn":10683374,"aeOgUxrWdm":10683374,"QtgZMrYsZl":10683374,
```
I have no idea what that is even supposed to be from a first look

added by #67350 @lispcoc

**Comment by PatrikLundell** [comment]
Good thing you took the initiative to look into it!

**Comment by lispcoc** [comment]
I've opened a PR addressing this issue. This should probably eliminate the bloated save data, but I couldn't find a good way to test it in the environment of the provided save data.
