### ISSUE TITLE
Charging w/ a weapon

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#69384]
### Is your feature request related to a problem? Please describe.

I just thought of an idea where it you attack w/ a weapon while running, you'd potentially do more damage/crit/special attack.

### Solution you would like.

Set up some weapon technique w/ certain weapons which when running, you do more damage or something.
Could potentially work w/:
- Axes
- Spears
- Bayonets
- Anything that's too short for doing this kind of thing (Minimum length of something like 2 feet?)
- Anything too heavy or too light, I.E. something like a Zweihander or a katana would be way too heavy/light to swing like that, more like a wood axe or a regular sledgehammer, could be dependent on strength.

Some things you could add onto it could be a movement requirement (so you couldn't just stand still), a "stumble" when you miss, or adding a risk of losing your weapon into the opponent.

### Describe alternatives you have considered.

Potentially just making the crit chance bigger while running

**Comment by tenmillimaster** [comment]
I believe you're already assumed to be charging with a weapon.

**Comment by PGR-14** [comment]
Not really, cause w/ a spear, just press tab & you'll hit two tiles away, including through stuff like metal bars. I don't think you're doing a charge attack.
Unless you're talking about while running, which I didn't know about.
