### ISSUE TITLE
Bayonets not really working

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#69383]
### Describe the bug

When using a gun, setting the fire mode to "Bayonet", you can't fire it anymore, as well as having to change the firing mode manually.

### Attach save file

N/A

### Steps to reproduce

Grab a gun, fix bayonet, despair

### Expected behavior

Potentially could be intentional, but IDK.
Probably caused by the way whoever wrote the code for the bayonet, possibly could fix it by making it similar to that shotgun w/ 2 magazines.
It should work like that of a spear (2 tiles) w/ long guns (Maybe using piercing skill, spear proficiency, & their respective martial arts?), & w/ pistols would just have a 1 tile version.
You could also do the TAB thing w/ spears where it'll automatically attack 2 tiles away.
Perhaps you could also add a spear charge? There's a reason why charging w/ a spear is a thing.

### Versions and configuration

Tiles, Windows, Sounds, x64, 2023, 11, 10, 1610

**Comment by fairyarmadillo** [comment]
Bayonets are no longer reach weapons, as a rifle with a bayonet is not actually very long. You attack by walking into stuff with them or pressing tab, the fire mode is a leftover thing that will shortly be removed.

**Comment by PGR-14** [comment]
Ok, thanks!
