### ISSUE TITLE
Crash upon killing enemy, segmentation fault

### ISSUE THREAD

**Issue by BlizzDA** [CleverRaven/Cataclysm-DDA#69396]
### Describe the bug

Games crashes upon killing an enemy. May be any death, since it also crashed when I wandered around a bit in an area with zombies and hazards. 

### Attach save file

[Clearlake-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13358314/Clearlake-trimmed.tar.gz)

### Steps to reproduce

1. Open save file
2. Kill something, e.g. a nearby roach
3. Game crashes

### Expected behavior

Game doesn't crash when something dies

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: d586ccb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13358301/crash.log)

**Comment by Myfharad** [comment]
Having the same problem!

**Comment by actually-a-cat** [comment]
can reproduce, trace:

```
#0  0x0000000000000002 in ?? ()
#1  0x000055e6c195a8b5 in monster::attitude_to (this=0x55e6f4729e20, other=...) at src/monster.cpp:1423
#2  0x000055e6c1944a58 in monster::plan (this=this@entry=0x55e6f4729e20) at src/monmove.cpp:730
#3  0x000055e6c0d205ba in (anonymous namespace)::monmove () at src/do_turn.cpp:271
#4  0x000055e6c0d22549 in do_turn () at src/do_turn.cpp:609
#5  0x000055e6c152ad94 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:797
```

**Comment by Mister-Cultist** [comment]
this is happening to me as well. I've been getting a weird bug with the mounted workshop as well but idk if it's connected.
