### ISSUE TITLE
CTD when Killing. Crash Message: "SIGSEGV: Segmentation fault" 

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#69397]
### Describe the bug

Im hard crashing to desktop after killing anything with the crash log being:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: d586ccb
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff7e5aacbc8[cataclysm-tiles.exe+0x27cbc8]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x14027cbc8),
    0x14027cbc8    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/ios_base.h:1122    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff7e5a8d4cc[cataclysm-tiles.exe+0x25d4cc]), 
    (libbacktrace: log_crash+0x1de@0x14025d4cc),
    0x14025d4cc    src/crash.cpp:918    std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
    0x14025d4cc    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:86    log_crash
  #2
    (dbghelp: @0x7ff7e5a8d7a0[cataclysm-tiles.exe+0x25d7a0]), 
    (libbacktrace: signal_handler+0x52@0x14025d7a0),
    0x14025d7a0    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/exception_ptr.h:143    signal_handler
  #3
    (dbghelp: @0x7ff7e64b7ae2[cataclysm-tiles.exe+0xc87ae2]), 
    (libbacktrace: gnu_exception_handler+0x152@0x140c87ae2),
    0x140c87ae2    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crt_handler.c:287    _gnu_exception_handler
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ffc22257ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ffc241d23af[ntdll.dll+0xa23af]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x484@0x7ffc241814b4[ntdll.dll+0x514b4]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ffc241d0ebe[ntdll.dll+0xa0ebe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

### Attach save file

[Scott Lake-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13358357/Scott.Lake-trimmed.tar.gz)

### Steps to reproduce

Kill the Zombie Miner to the left of you and the game should crash.

### Expected behavior

I expect it to not crash.

the CTD happens when I kill anything.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: d586ccb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13358365/crash.log)

**Comment by akrieger** [comment]
Dup of #69396
