### ISSUE TITLE
Have the option to add a way to find on the map locations revealed by a note or visitor's pass?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#69398]
### Is your feature request related to a problem? Please describe.

When I find a body and it has a visitor's pass, or a handwritten note, that's great! I love a clue that'll lead me somewhere interesting. But If I've already explored an area it's impossible to see what block of terrain actually is the hidden location I'm interested in, and once the note is used it's not helpful anymore.

### Solution you would like.

I'd like the note to in some way show me specifically where the revealed location is. Ideal would be a quest that would be completed by using the visitor's pass on the door with a quest marker that points to the location. 

### Describe alternatives you have considered.

Less ideal but also functional would be the ability to re-use the note to zero in on the location on the map or an auto-generated note that is applied to the location in question.

**Comment by PGR-14** [comment]
For the note, go to the lower layer (I.E. a basement), & check for brown spaces, above are the ventilation shafts.
W/ the quest, it'd get clogged pretty fast.
W/ the note on the map, it's a pretty good fix.

**Comment by MrHrulgin** [comment]
Thanks for the tip on how to find them. That's a very helpful stopgap.

**Comment by RenechCDDA** [comment]
There should generally be some sort of UI indication of the newly revealed tiles, but I'm not sure notes is the way to go. (It could reveal many many tiles and placing notes on all of them is... unwise.)

**Comment by PGR-14** [comment]
Maybe just the "special" locations, no roads or trails, just the important stuff
I.E. using a road map would put a note on the washrooms, gas stations, & rest stops, but not on any of the roads.

**Comment by MrHrulgin** [comment]
> There should generally be some sort of UI indication of the newly revealed tiles, but I'm not sure notes is the way to go. (It could reveal many many tiles and placing notes on all of them is... unwise.)

Yeah, this was why I was proposing it be optional. I wouldn't want it for every tile, but being able to look at the places that the map will reveal and optionally tag them at the moment you're reading the map would make it much easier for players to set mini-objectives for themselves.

**Comment by RenechCDDA** [comment]
Good news, this is more or less implemented by #70482
