### ISSUE TITLE
"Repair Gun" mend option is missing

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#69392]
### Describe the bug

#61011 added a way to repair the gun through the mend menu, now it's disappeared and trying to mend damaged gun just told me to repair it with firearm repair kit.

Considering that we're going away with using kits to repair stuff, i hope this was a regression and not just the development going to other direction in this particular mechanic.

### Attach save file

N/A

### Steps to reproduce

1. get a gun
2. damage it somehow
3. mend it to open the mend menu
4. see that such option doesnt exists or otherwise told you to repair with gun repair kit.

### Expected behavior

said option being there

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: d39ddd6 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Bombastic Perks [bombastic_perks]
]

**Comment by ehughsbaird** [comment]
Removed (by the author) in https://github.com/CleverRaven/Cataclysm-DDA/pull/64622
