### ISSUE TITLE
invalid proficiency id "prof_wp_netherium"

### ISSUE THREAD

**Issue by MushroomW** [CleverRaven/Cataclysm-DDA#69390]
### Describe the bug

invalid ID with the new nether creatures proficiency

### Attach save file

N/A

### Steps to reproduce

hit a monster which has this weakpoint proficiency ID

### Expected behavior

no errors

### Screenshots

![Capture](https://github.com/CleverRaven/Cataclysm-DDA/assets/149583377/cbf1a79f-5a4c-4bae-877c-2a23e618884d)

### Versions and configuration

build type: windows-tiles-x64-msvc
build number: 2023-11-11-1910

**Comment by Termineitor244** [comment]
/confirmed since reading the changes introduced by #69141 it seems that the proficiency is actually called `prof_wp_netherium_abomination `so it should be a simple fix. /good-first-issue.
