### ISSUE TITLE
auto_pickup.txt not loaded

### ISSUE THREAD

**Issue by aapo** [CleverRaven/Cataclysm-DDA#6940]
749551235c912caf24932fe44778c504dd616c50

Help-> Auto pickup manager
Rules can be added, modified and saved (and they go to the file).
But auto_pickup.txt is not loaded on next start.

**Comment by narc0tiq** [comment]
It's been over a year since this issue was reported; I'm going to close this now, please reopen or make a new one if the issue persists.
