### ISSUE TITLE
Adding autoclave pouch recipe

### ISSUE THREAD

**Issue by installgentoo** [CleverRaven/Cataclysm-DDA#69404]
### Is your feature request related to a problem? Please describe.

Pouches are made from polycarbonate. We literally have polycarbonate sheets ingame. Balance-wise, autoclave already spawns in difficult sections of the labs, so it's simply annoying, not hard, to then drive around and search for a hospital to find the damn pouches(and probably a second autoclave).

### Solution you would like.

Add this recipe:

```[
  {
    "result": "pouch_autoclave",
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_MEDICAL",
    "skill_used": "chemistry",
    "skills_required": [ [ "firstaid", 6 ], [ "electronics", 5 ] ],
    "difficulty": 5,
    "time": "4 h",
    "autolearn": true,
    "using": [ [ "plastic_molding", 1 ] ],
    "qualities": [ { "id": "CUT", "level": 2 } ],
    "components": [ [ [ "polycarbonate_sheet", 50 ] ] ],
    "proficiencies": [ { "proficiency": "prof_plasticworking" }, { "proficiency": "prof_wound_care_expert", "required": true } ]
  }
]
```

Gatekeep pouches by high healthcare(you gotta understand how to ensure sterilization) and high electronics(understanding how cbms work) to add some minimal challenge. 50 sheets as each sheet is the size of a plastic bag.

### Additional context

Someone pls commit this for me.

**Comment by harakka** [comment]
> Pouches are made from polycarbonate. We literally have polycarbonate sheets ingame. 

Sterilization pouches are bit more involved than "polycarbonate sheets" since they need to be steam permeable and even more so as these are self sealing. These items are not DIYable.

**Comment by esotericist** [comment]
harakka is correct. solution is add a box of them near any autoclave, not adding a nonsense crafting recipe.
