### ISSUE TITLE
The recipe for producing vegetable cooking oil is unreasonable.

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#69413]
### Describe the bug

the recipe for electric oil press / manual oil press:
80 canola seeds -> 16 vegetable cooking oil.
Even if we toiled all day, we would starve to death with such a low harvest.

the recipe for screw press:
24 canola seeds -> 12 seed paste ->160 vegetable cooking oil.
Is the yield of this recipe too high?

### Attach save file

-

### Steps to reproduce

View Recipes

### Expected behavior

Use the right amount of oil crops to make vegetable cooking oil

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: 0d390ce [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth]
]

### Additional context

For convenience,
We can roughly divide these crops into two groups,.
One is 36% oil yield, including peanuts, sunflower seeds, canola seeds; 
One is 18% oil yield of  including grape seeds, cotton seeds, and soybeans.

**Comment by fairyarmadillo** [comment]
Good catch. This didn't get updated when seed sizes/yields were changed. I'll submit a PR for it real quick.
