### ISSUE TITLE
Error occur when finishing cattail mission

### ISSUE THREAD

**Issue by emmanueltudela** [CleverRaven/Cataclysm-DDA#69424]
### Describe the bug

I had a mission given by a pnj, he wanted 80 cattails in a duffel bag.
I got the 80 cattails put them in a bag and gave him the bag.
An error occured saying the item couldn't be put in a bag.

### Attach save file

[Zalma-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13370079/Zalma-trimmed.tar.gz)

### Steps to reproduce

1. Talk to the npc for a mission where he asks you for 80 cattails and gives you a duffel bag
2. Take the 80 cattails put the cattails and put everything that it gives you in the bag
3. Go back to talk with the pnj and finish the mission

### Expected behavior

There should be no weird error screen displayed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13370090/debug.log)

**Comment by emmanueltudela** [comment]
I don't know how you could do the same mission again.

**Comment by gettingusedto** [comment]
fixed by #68077 in experimental

**Comment by emmanueltudela** [comment]
You answer super fast
I'm closing the issue then
