### ISSUE TITLE
Craft menu overestimates calorie maximum

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#69433]
### Describe the bug

When crafting food, it estimates the possible calories in the finished product, showing a range based on the worst and best versions of the recipe. I'm not exactly sure what's going on, but the upper end of the values are way higher than they should be. Take for instance the caviar and egg sandwich. It should come out to around 600 kcal, but it's showing a max of 3159. It may be adding up all possible ingredients rather than simply selecting the highest and lowest value ones.

### Attach save file

N/A

### Steps to reproduce

Open the crafting menu and try to make a food which has variable ingredients, see that the estimated calorie maximum is often much higher than would be possible even under the best circumstances.

### Expected behavior

The max calories should reflect the best version of the item.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/d1e87fc2-b9dd-4d9d-a9e1-548b227aee87)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 0.G-5181-gb1016321b7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by mqrause** [comment]
Nutrients are calculated recursively, so it's possible some intermediate foods have some inappropriate recipe/components that would cause them to have a ton of calories (the recently fixed vegetable cooking oil comes to mind, in case you tested that without the fix, but there might also be others). But it's also possible calculations are actually wrong.

**Comment by fairyarmadillo** [comment]
It seems like it's pretty much all food.

**Comment by RenechCDDA** [comment]
One possible component of the caviar and egg sandwich is 2 hallula which would come out to a minimum of 1000 calories just for that component, not 600.

Although I don't immediately see any combinations adding up to 3k+, this appears to be working as intended.

**Comment by fairyarmadillo** [comment]
> One possible component of the caviar and egg sandwich is 2 hallula which would come out to a minimum of 1000 calories just for that component, not 600.
> 
> Although I don't immediately see any combinations adding up to 3k+, this appears to be working as intended.

How can you say it's working as intended and that there's no 3000 kcal combination in the same sentence?

**Comment by RenechCDDA** [comment]
The recipe has 4 components, 1 of which is substitutable with **11** different options, which means that the recipe itself has 11 different base combinations. All of the components have multiple possible combinations *which are calculated recursively*, meaning there are at least several thousand possible ingredient combinations just from the top two levels of ingredients.

I picked *one* and immediately blew the estimate out of the water. I've seen this a lot, and for meat the answer is always *porkbelly*. Porkbelly is a 1:1 substitution for cooked meat pretty much everywhere despite having 3x the calories. I have run down a lot of recipes that look way too high and it's like oh yep, there's porkbelly way down the chain.

No, I did not calculate every single one of the thousands of possibilities by hand to prove it.

However we have an automated test for this, so I am confidently certain it is correct.

**Comment by mqrause** [comment]
![grafik](https://github.com/CleverRaven/Cataclysm-DDA/assets/38702195/f525a153-c08d-4d8e-83dc-2f9c266bf993)
This is likely (one of) the (main) offender(s). That's more than 10 times the calories compared to the other barley recipes, giving flour an equivalent calorie span that's passed down further to anything made from it, and increased further by varying amounts of flour used in alternatives.

**Comment by fairyarmadillo** [comment]
> ![grafik](https://user-images.githubusercontent.com/38702195/283455459-f525a153-c08d-4d8e-83dc-2f9c266bf993.png) This is likely (one of) the (main) offender(s). That's more than 10 times the calories compared to the other barley recipes, giving flour an equivalent calorie span that's passed down further to anything made from it, and increased further by varying amounts of flour used in alternatives.

Oh, that's a bug. Grain seeds are supposed to be 1:1
