### ISSUE TITLE
[Aftershock] Loading items in the escape pod doesn't let you take them planetside.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#69449]
### Describe the bug

When I tried to throw some loot into the escape pod in the Crashing Ship start to take planetside, it simply disappeared when the pod was launched. I found this very upsetting, because there were several awesome guns and armor in there, along with medical supplies and other such things that I needed to not immediately die when I hit the surface.

### Attach save file

N/A

### Steps to reproduce

1. Get on the crashing ship.
2. Load the escape pod with your sweet loot.
3. Launch to the surface.
4. Watch as your hard work vanishes before your eyes.
5. Feel disappointment as all your items are gone, replaced by the generic escape pod loot.

### Expected behavior

I expect that the launch EOC will transport all of my items with me.

### Screenshots

None.

### Versions and configuration

OS: Windows 11
Game version: cdda-windows-tiles-x64-2023-11-12-0838
Graphics version: Tiles
Ingame language: English
Mods loaded: [ dda, no_npc_food, personal_portal_storms, no_fungal_growth, aftershock, aftershock_exoplanet ]

### Additional context

I think the item EOCs being implemented in #69364 for getting loot to Port Augustmoon could be recycled here and used again.

**Comment by John-Candlebury** [comment]
Can confirm. Issue can be solved using an effect on condition simmilar to `"EOC_AFS_AUGUSTMOON_SHUTTLE_TP"` found here: #69364

**Comment by Maleclypse** [comment]
As a reminder it could be solved but it was specifically set so the PC could only take what was on them and if we wanted to be realistic about it, if the PC has any loose items inside the escape pod when it launches, it blenders their character for an instant death.  You don't leave loose objects during atmospheric reentry.

**Comment by John-Candlebury** [comment]
I believe that was just the justification for the fact that it wasn't possible to transfer map items before.

**Comment by Maleclypse** [comment]
> I believe that was just the justification for the fact that it wasn't possible to transfer map items before.

You are probably right.  But it definitely feels weird to have a start scenario that might let you bring multiple power armors out for your permanent ownership in the first seven minutes.
