### ISSUE TITLE
Option to disable gun ascii images in examine window

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69441]
### Is your feature request related to a problem? Please describe.

The gun's ascii image, if it has one, will pad out the length of the examine window. I use this a ton and having an option to turn these ascii images off would allow me to see relevant information much faster and easier for the items with their image. As it stands, the "9-round combat shotgun", "Glock 22", "PTR 603", and more have ascii images, Others like the "Hi-Point C9", "Taurus Raging Bull", and "Enfield Battle Rifle", etc, don't have images.

It would be a quality of life improvement if there was an option to just disable or enable all gun images.

### Solution you would like.

Option in "Interface"->"QOL Options"->"Show guns ascii images"
There is already a QOL option for showing armor coverage, which is essentially the option I'm looking for, but for gun ascii images.

### Describe alternatives you have considered.

Just ignoring the fact that some weapons have a bigger examine window

**Comment by RenechCDDA** [comment]
This is already an option, please disable it if you do not want it.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/ea10eb79-196f-4126-9dc0-a3dfa2872443)
