### ISSUE TITLE
Add Wikipedia links to world items

### ISSUE THREAD

**Issue by trentbuck** [CleverRaven/Cataclysm-DDA#69474]
### Is your feature request related to a problem? Please describe.

Current flow is:
1. Encounter a “dory” in game.
2. What the hell is a dory?
3. Open browser, search for “dory”, click Wikipedia link.

This happens enough I wish it was streamlined.

### Solution you would like.

Suggested flow is:
1. Encounter a “dory” in game.
2. What the hell is a dory?
3. Click link in game, browser opens directly to Wikipedia page.

The JSON already often has links in comments. We could expose these to the player. It needn’t always be Wikipedia. Sometimes they are links to e.g. the real backpack the game backpack is based on.

For curses I imagine this would like `ls —hyperlink`. For sdl/gui I hope there is some halfway reasonable way to pop up a link on all platforms. If not, this is not with the hassle.

### Describe alternatives you have considered.

• Just open the browser and quack by hand, it’s not THAT hard.

• git grep, then double click on the URL in the source json.

**Comment by gisaku33** [comment]
It seems like a better solution would be simply making descriptions more clear, but in the case of the dory it seems fine already. 

"A well-made spear with a bronze head. Greek in origin. Despite its large size, it was frequently used one-handed."

It's a Greek spear with a bronze head, it's large and can be used one-handed. I'm not sure what other information is necessary.

**Comment by ZhilkinSerg** [comment]
No
