### ISSUE TITLE
FEMA camp random NPC quest badly broken by imbecille NPC behavior

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69479]
### Describe the bug

I did a patient records quest for a random NPC and then got asked to take the NPC to a FEMA camp. That's when things went wrong, as the NPC then immediately started following my character, but refused to present any of the commands you can use for followers (such as to wait in a safe location, or, as the case when things went from bad to worse, decide to run into the clutches of a zombie soldier to pulp the corpse of the other one, more or less ensuring the NPC will die unless the PC manages to defeat the whole horde in melee.
I can't order the moron to not pulp corpses, nor order it to behave in a somewhat sensible manner combat wise.

### Attach save file

File too big...

### Steps to reproduce

1. Find NPC that asks you to take it to a FEMA camp (in my case that quest was preceded by one to find patient records).
2. Stupidly accept the quest.
3. Find that you're now stuck, as you can't tell the NPC to wait until it's safe to visit a camp in any way, nor order the moron not to run into zombies to pulp corpses.

### Expected behavior

After accepting to perform the quest, the you should then be able to control the combat and wait behavior of the NPC so it won't kill itself.
An alternative would be to have another dialog option after accepting to perform the quest to say it's time to come and the NPC will stick to you like a (particularly stupid) dog on a leash until the quest is fulfilled.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/9bc3e2aa-5e03-4cca-9b60-6a981332a698)

And here is the result... The idiot decided it was a good idea to climb the fence to pulp a corpse when more than half a dozen enemies were rushing in.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/50a887d7-642e-4660-82a5-7088efcd3441)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 0.G-5225-g7ae6d0f216 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms

### Additional context

In the screenshot I've just killed one zombie soldier with the NPC running shotgun in the basket of the MC, at which the idiot jumps off to pulp the corpse, oblivious of the oncoming threat, instead to staying put and allow me to take out the other zombie before enjoying itself in a splatter fest.

**Comment by Rabadash94** [comment]
Something similar happened to me, but in the mission of finding corporate accounting ledger. After completing it, I had to accompany the NPC to a bank (I think) to look for I don't remember what. Since the building was in the middle of a city, I took the NPC to a safe place and ordered her to stay and guard the position. Then I went and found what I had to take and when I returned to where I left the NPC she was gone. I searched the surroundings and found the body some distance away, as if she had tried to follow me, but it seemed that she had not done so immediately, or else I would have noticed.

**Comment by PatrikLundell** [comment]
That differs from my case, where I didn't even have the chance of ordering the moron to stay put, but still a related case.

**Comment by Rabadash94** [comment]
Maybe it doesn't differ, because I remember that at first I couldn't give her orders either, but something I did made the menu appear. If I remember correctly, I spoke to the NPC when the mission was unfinished, but I don't remember what else I did and the options to give her orders appeared.

**Comment by PatrikLundell** [comment]
Well, my moron killed itself (one would have thought the logic to run away from overwhelming danger that's been introduced recently would have kicked in, but it only did when it was close to death and bleeding out, which was obviously too late), but before that I tried to speak to it again, with the same lack of useful commands.

**Comment by EricFedrowisch** [comment]
Still have this bug in latest stable 0.H. Attaching save. I have the NPC in the FEMA camp. They won't acknowledge that the quest is done. Still just following me around. Won't take commands.
[The Dark Forest-trimmed.tar.gz](https://github.com/user-attachments/files/17986724/The.Dark.Forest-trimmed.tar.gz)

**Comment by dholmes215** [comment]
I ran into this in O.H (steam).  I could not complete the quest on any of the tiles of the first FEMA camp I went to.  I then went to a _different_ FEMA camp and was able to complete the quest there.  The second camp had a different layout, if that matters.
