### ISSUE TITLE
Loud noises should be much worse (unhardcoding noises effects)

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#69476]
### Is your feature request related to a problem? Please describe.

The only negative effect loud noises apply is deafen you
While it is a real effect of the loud noise, it is not the only one, and it heavily depends on the sound level

### Solution you would like.

I am biased toward EoC, so my idea is to make event `hear_noise`, that can return integer of noise volume; that would be enough for start, but i don't know how computation heavy it may be

### Describe alternatives you have considered.

Some hardcoded solution

**Comment by KeremBabaG** [comment]
What kind of other negative effects would it apply? Nausea?

**Comment by GuardianDll** [comment]
nausea, physical pain, penalty to balance limb_score, insomnia, from fast inspection of google it is the list of stuff i can make personally

**Comment by fairyarmadillo** [comment]
An ASL proficiency and some NPCs who can teach/speak it would be nice, and would give us a basis for permanent hearing loss and bionic replacement. We even already have the bionics.
