### ISSUE TITLE
JSONized item sound

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#69487]
### Is your feature request related to a problem? Please describe.

The current sound generation of items is achieved through hard coding, which makes it difficult to add new soundable items, such as noisy grenades.

### Solution you would like.

JSONized item sound, making it easy to customize the sound's type, volume, text, etc. by JSON.

**Comment by CoroNaut** [comment]
Sounds like a good idea. Furthering this idea, I can imagine that the mp3 player in-game could pull from a music folder. Just put some mp3's or mp4's or webm's in there and select in-game what you want.
