### ISSUE TITLE
floating items

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#69493]
### Describe the bug

Some items float when they should not.

### Attach save file

[Moon-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13398843/Moon-trimmed.tar.gz)

### Steps to reproduce

See floating item.

### Expected behavior

Items that are on a z-level with no floor should go down a z-level each tick until they are on a z-level with a floor.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45959491/767c935e-3ea3-43b7-81ff-a00050ec8a30)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: b2b7cac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by oosyrag** [comment]
Do you have any information about how that item got there in the first place?

**Comment by misterprimus** [comment]
> Do you have any information about how that item got there in the first place?

Probably part of a soldier zed mob spawn, the ones you often see roaming in areas with dropped m4s.
