### ISSUE TITLE
[Xedra Evolved] "All" subcategory for Xedra Evolved's crafting tab

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#69495]
### Is your feature request related to a problem? Please describe.

I find it odd that Xedra crafting tab doesnt have an "All" subcategory to list off all of the available Xedra Evolved's crafting recipes while other crafting tab has them.

### Solution you would like.

Add the "All" subcategory for the Xedra crafting tab.

### Describe alternatives you have considered.

not doing so

**Comment by Maleclypse** [comment]
Can you point me to a PR that shows me how to do that?

**Comment by gettingusedto** [comment]
> Can you point me to a PR that shows me how to do that?

Turns out, it was more simpler than i thought. It's as simply adding `CSC_ALL` into the `CC_XEDRA` like so.
```  {
    "type": "recipe_category",
    "id": "CC_XEDRA",
    "recipe_subcategories": [
      "CSC_ALL",
      "CSC_XEDRA_RESEARCH",
      "CSC_XEDRA_WEAPONS",
      "CSC_XEDRA_ARMOR",
      "CSC_XEDRA_TOOLS",
      "CSC_XEDRA_ROBOTS",
      "CSC_XEDRA_MISC",
      "CSC_XEDRA_ALCHEMY",
      "CSC_XEDRA_ELEMENTAL"
    ]
  },```
