### ISSUE TITLE
Installed tank with water on vehicle and had to dump water out of said tank.

### ISSUE THREAD

**Issue by Amam342** [CleverRaven/Cataclysm-DDA#69491]
### Describe the bug

I installed a tank filled with pure clean water on my car. Then it told me 'what do you want to do with the water inside'.

Confused, I was like 'eh... can you keep it in the tank?' I tried multiple times, but it didn't seem to allow me to insert back the water in the tank. Now, I will assume that my character did not drill a hole under the tank to make the water go away, so... Eh... I assume that something's not working right here.

Important to note, my tank did not have a funnel or anything else installed on it, as I thought I should install the tank on the vehicle first before putting stuff on the tank.

### Attach save file

[Dewar-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13398055/Dewar-trimmed.tar.gz)

### Steps to reproduce

1. Get a car, a water tank filled with liquid and the proper tools to install the tank on your vehicle.
2. Install the tank on the car while it is still filled with water or whatever other liquid is inside.
3. Notice that it prompts you on what to do with the water.
4. Try to put the water back in the tank that is now installed in the car.

### Expected behavior

I would expect that if I attached a filled tank on my car, then the fuel inside would stay in the tank. 

If that behavior is not desired, then I would expect to be warned that the liquid in my tank will be dropped on the ground or has to be transfered out of the tank before the tank gets on the vehicle. Thankfully, these 240L of pure water were something I could easily replace. But I dread what would have happened had that been my only source of water around.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 7245d0b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

This might be a side note, but I couldn't quite figure how to put fluid into a vehicle mounted tank? If anyone could tell me how, I would appreciate. I will research on my own, of course, but if it's not possible, I'd like to be told.

**Comment by gisaku33** [comment]
You should be able to bypass dumping tanks when installing by just pressing escape (may need you to press it twice) when it asks what to do with the liquid. You can put fluids into vehicle tanks by examining the vehicle and pressing 'f' to fill tanks. 's' to siphon/draw fluids from vehicle tanks.

That said, yeah it should definitely give you the explicit option to leave the fluid in the tanks.
