### ISSUE TITLE
[MoM] New power for clairstance. 

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#69497]
### Is your feature request related to a problem? Please describe.

I'm always annoyed with artifacts and their randomness. Maybe with this mod we can see all passive and active effects on them? 
Also some integration with Xedra Evolved and other mods will be good. 

### Solution you would like.

I think it can be realized like note on item using marker but how to get this information I don't know. 
Maybe it could be passive effect of clairstance and/or be scaled. 
For example: at low level you could see positive or negative effects it has or both. At medium levels you see what stats are affected and know separately effects positive or negative at passive and active properties. At high level you know all details. 

### Describe alternatives you have considered.

Also it could be realized like fighting skills are reveal details of damage or survival skill reveal product expiration date. 

### Additional context

Maybe clairstance could review side effects of having too much artifacts.

**Comment by Standing-Storm** [comment]
This would be interesting and definitely in-theme but at the moment I don't think there's any code support for revealing the characteristics of an artifact. Once that's there I would gladly implement this.
