### ISSUE TITLE
Redesign the RM802 into the China Lake Grenade Launcher

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#69502]
### Is your feature request related to a problem? Please describe.

The RM802 makes _ZERO_ sense as a futuristic grenade launcher, seeing as the China Lake grenade launcher already exists. Both share the same:

1. Ammo Capacity
2. Pump Action Capability
3. Ammunition used

It makes sense to do this as it was done with the RM42 Knife being turned into the Fairbarne Sykes Fighting Knife

### Solution you would like.

The RM802 should be remade into the China Lake, with the materials changing from Superalloy and Ceramic to Wood and Aluminium, the requirement of mod mounts to make it tactical instead of giving the slots as is. and adding it to the Aircraft Carrier as loot

### Describe alternatives you have considered.

add in a separate China Lake launcher, and turn the RM802 as is into a more modernized design as was being made by Airtronic

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/7b8a0a31-6533-44c6-b366-9526ce219663)

https://en.wikipedia.org/wiki/China_Lake_grenade_launcher

**Comment by KeremBabaG** [comment]
Yeah makes sense but some other futuristic grenade launcher should be added as well imo

same with rm42

**Comment by Kantonine** [comment]
> Yeah makes sense but some other futuristic grenade launcher should be added as well imo
> 
> same with rm42

How about a Magazine fed Grenade Launcher, But in a smaller cartridge, like the XM25
https://en.wikipedia.org/wiki/XM25_CDTE

or the Neopup PAW-20
https://en.wikipedia.org/wiki/Neopup_PAW-20

**Comment by tenmillimaster** [comment]
The rm802 should be: obsoleted, turned into the China lake variant made by Airtronic, or a different outfit from Rivtech (but only commercially available to licensed contractors, not in military service), or replaced with a Hub version, probably based on the rheinmetall Hydra. I'm most in favor of the latter option.

**Comment by tenmillimaster** [comment]
The rm802 should be: obsoleted, turned into the China lake variant made by Airtronic, or a different outfit from Rivtech (but only commercially available to licensed contractors, not in military service), or replaced with a Hub version, probably based on the rheinmetall Hydra. I'm most in favor of the latter option.

Resolved by #69603
