### ISSUE TITLE
Port Innawoods stream mutable to the main game

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#69503]
### Is your feature request related to a problem? Please describe.

#67065 is pretty amazing and we should have this in the main game, too.

### Solution you would like.

Port it. It may have minor balance implications because it makes infinite water more common again but it also adds realism.

**Comment by Light-Wave** [comment]
If you want to work on this, that's sounds great by me. There might be some issues left to deal with. For example, I'm not sure how streams will deal with roads. But having it in mainline would mean we get more eyes on it, and more developers involved in making it work properly.
