### ISSUE TITLE
Consuming chamomile tea from the ground doesn't destroy the tea but applies it's effect (endless tea)

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#69507]
### Describe the bug

When consuming my Chamomile tea, I get the 'you get very sleepy'  message, but no chamomile tea is subtracted from the container and my thirst doesn't change either

### Attach save file

[Blue Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13400572/Blue.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Press E to open consume message
3. type /tea and press enter to filter for tea
4. Scroll down to the Chamomile tea
5. Hold enter and watch the player get extremely tired

### Expected behavior

Consume only the tea that's there.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/67087d23-85c9-4a69-92e4-e508ae4b1a8a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: e69dc96 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by NetSysFire** [comment]
I can not reproduce with a clean save but the issue definitely exists in the given save.

**Comment by IdleSol** [comment]
You're drinking it wrong :)

Put it on the ground and try to drink it.

**Comment by NetSysFire** [comment]
Curious. This way I can reproduce with a fresh save. But other teas do not appear to be affected.

**Comment by IdleSol** [comment]
Food vs medicines

**Comment by IdleSol** [comment]
You need to watch this PR #68976

- There is an error [cdda-windows-tiles-x64-2023-10-29-1329](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-10-29-1329)
- No error [cdda-windows-tiles-x64-2023-10-28-2231](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-10-28-2231)
