### ISSUE TITLE
Can't make sandwiches with flatbread anymore

### ISSUE THREAD

**Issue by ferociousdork** [CleverRaven/Cataclysm-DDA#69508]
### Describe the bug

Since #69406, I can't make sandwiches with flatbread anymore, as it was not migrated to the `bread_sandwich` requirement. This was probably unintentional.

### Attach save file

N/A

### Steps to reproduce

1. Spawn 2 pieces of flatbread
2. Spawn cooked meat / veggies, etc.
3. Observe no way to craft sandwich

### Expected behavior

Craft sandwich.

### Versions and configuration

Recent experimental.

**Comment by db48x** [comment]
Oops! thanks for fixing it.
