### ISSUE TITLE
Sugar house's tapped mapple trees do not work.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#69514]
### Describe the bug

Pre-setup maple trees with spiles and buckets at [parking lot] near [sugar house] are not inter[a]ctable and thus not working.

### Attach save file

[Weebland-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13401118/Weebland-trimmed.tar.gz)

### Steps to reproduce

interact near maple tree, tree is highlighted as available target, upon selection of tree tile for interaction, nothing happens.

### Expected behavior

trees should be no different from manually set-up maple taps

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ALT; Description: ALT Workstation K 10.2 (Sorbaronia Mitschurinii); Release: 10.2; Codename: SorbaroniaMitschurinii; 
- Game Version: 61b45f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Xedra Evolved [xedra_evolved],
    Blazemod - Vehicle Additions Pack [blazemod],
    No EMP Damage [no_emp]
]

**Comment by 321nick** [comment]
I am getting the same issue, even in recent experimentals
