### ISSUE TITLE
YA Novels for the Exodii

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#69518]
### Is your feature request related to a problem? Please describe.

Chatting in the devcord, we figured that the Exodii would like YA Novels

### Solution you would like.

Adding some Riordan, Wings of Fire, and maybe some Discworld, and dialogue and potential rewards from Rubik.

### Describe alternatives you have considered.

Not:(

### Additional context

This just discussion/a reminder since i don’t have a computer with me.

**Comment by Maleclypse** [comment]
100% do this.

**Comment by KeremBabaG** [comment]
why would they like ya novels

**Comment by DukePaulAtreid3s** [comment]
> why would they like ya novels
Because they value entertainment and culture. Furthermore, a series like, say, Percy Jackson contains mythology they already recognize, but packaged in a new, more modern twist.

**Comment by fairyarmadillo** [comment]
They don't speak english.

**Comment by MNG-cataclysm** [comment]
> They don't speak english.

I think this could be a good jumping-off point for a mission chain, where the Exodii need your help to translate novels into the forms they understand, or find raw materials for new wetware that they could attach to the Great Gray for translating texts originating from the local universe.

**Comment by DukePaulAtreid3s** [comment]
> > They don't speak english.
> 
> I think this could be a good jumping-off point for a mission chain, where the Exodii need your help to translate novels into the forms they understand, or find raw materials for new wetware that they could attach to the Great Gray for translating texts originating from the local universe.

This is nearly exactly what it going to happen, in fact, the first quest will most likely relate to finding something like a Percy Jackson book, and then the next quest would relate to finding some form of picture dictionary, because Rubik would want to share it with other Exodii.

**Comment by fairyarmadillo** [comment]
> > > They don't speak english.
> > 
> > 
> > I think this could be a good jumping-off point for a mission chain, where the Exodii need your help to translate novels into the forms they understand, or find raw materials for new wetware that they could attach to the Great Gray for translating texts originating from the local universe.
> 
> This is nearly exactly what it going to happen, in fact, the first quest will most likely relate to finding something like a Percy Jackson book, and then the next quest would relate to finding some form of picture dictionary, because Rubik would want to share it with other Exodii.

Why? Earth and everyone on it are doomed. It's just another pit stop for them, isn't it?

**Comment by Maleclypse** [comment]
> They don't speak english.

The great grey does and it's the AI that runs their virtual world.  It's the reason that picking up culture from doomed worlds is feasible.  It helps keep the mass of virtual inhabitants happy, which is basically where most Exodii are spending the majority of their time in virtual worlds.  This is all stuff Erk has stated as one of the few things exodii are interested from world to world.  Not every world has plastics, not every world has advanced tech, but every world has cultural items if there is any civilization and those cultural items are what makes the centuries long exodus from doomed world to doomed world bearable.
