### ISSUE TITLE
[MoM] Photokinetic's Candle's Light effect won't deactivate

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#69538]
### Describe the bug

Photokinetic's Candle's Light effect won't deactivate by:

- Casting it again
- Casting "Stop Concentrating"
- Sleeping
- Attacking
- Saving and quitting
- Completely closing the game and loading it them

### Attach save file

Can be seen on a fresh save

### Steps to reproduce

Cast "Candle's Glow"

### Expected behavior

Light would go out as normal

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 6e4f313 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Mind Over Matter [mindovermatter]
]

### Additional context

Also when making a new world to test the bug I noticed that Photokinetic don't start with the "Stop Concentrating" power

**Comment by Standing-Storm** [comment]
#69515 will fix this
