### ISSUE TITLE
Display location name directly when there is only one variant

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#69530]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59517351/a40aa300-df04-4247-8d27-e00d0a25de87)

### Solution you would like.

There is literally only one entry. Display it directly instead of saying it is random out of one entry.

### Additional context

Could be a good first issue. C++ folks may judge this one better.

**Comment by RenechCDDA** [comment]
It looks simple, but it's not. It would seem that the location isn't decided on until later, so at best it displays the (incorrect!) default location.

This is with prison start, which obviously does not start in a shelter.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/7d266017-ec90-45df-84e5-550470ab5cd1)

Here's the code branch for anyone it might help:
https://github.com/CleverRaven/Cataclysm-DDA/compare/master...RenechCDDA:Cataclysm-DDA:start_menu_text
(Note that the changes to character.cpp are to get past a bug I found)
