### ISSUE TITLE
Exiting item menu in inventory sometimes causes previously selected item/s to be different

### ISSUE THREAD

**Issue by Corvo746** [CleverRaven/Cataclysm-DDA#69546]
### Describe the bug

Whenever I open an item in the inventory menu and then close it by double tapping the screen(I'm on mobile, it should be "ESC") it cycles to another precise item in my inventory, for example in a survivor character opening the pocket knife and closing it will select the smartphone and vice versa, but when I open and close the bottle of water it select the pocket knife, it even does this on worn clothing too.

### Attach save file

N/A

### Steps to reproduce

1.make a player, normal survivor
2.go to inventory and select an item
3.notice how the item selected is no longer the same after you exit the item menu

### Expected behavior

The item selected should stay the same even after closing it's menu in the inventory

### Versions and configuration

-OS: ColorOS 13.0 | Android 13

Game Version: 011cbe9 [x32 bit]
Graphics version: Tiles
In-game language: english
Mods loaded: dda, no_npc_food, personal_portal_storm, no_fungal_growth

**Comment by CoroNaut** [comment]
I'm on desktop and I also see this bug. 
If I open the menu for cotton patches and back out, it selects combat machete
Open combat machete and it selects crowbar
crowbar -> combat pistol -> crowbar.
![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/bbf99fab-969c-4cc0-96fe-30c92739928f)

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 4f24d43 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]
