### ISSUE TITLE
Pumpkin seed inconsistencies

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#69549]
### Describe the bug

Pumpkins can either be crafted into seeds/cut pumpkin or deconstructed into them, but the seeds results are inconsistent. Crafting pumpkin seeds yields one .25L seeds item with significantly fewer calories than other pumpkin seeds, while deconstructing a pumpkin yields 6 .25L seeds items with the standard calorie values. The vitamin content of the seeds is also inconsistent.

Pumpkins produce many seeds, a whole pumpkin yielding only enough for a single crop seems strange as well. Maybe for edible seeds there should be a distinction between the amount needed for planting and the amount needed to fry and eat?

(The calorie values listed are higher than default due to the Expanded Digestive System CBM and maybe MoM's Biokinetic passive ability, but that's irrelevant to them being different from each other.)

### Attach save file

N/A

### Steps to reproduce

1. Craft pumpkin seeds.
2. Deconstruct a pumpkin.
3. Compare results.

### Expected behavior

Crafting/deconstruction should yield the same results.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/df07b799-6262-47fe-a7d4-72ac71fddf64)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 725161a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by fairyarmadillo** [comment]
Another in a chain of issues stemming from the comestible charge removal hitting immediately after my big grain and seed overhaul. Another contributor changed the seed amounts in pumpkins but didn't adjust the volume (and missed the craft recipe) so things got a little weird on top of all the issues charge removal caused. It also looks like calorie values were for shelled seeds, while these are still in-shell. I'll get a PR up to change the craft recipe to match the deconstruct.

For context, A single pumpkin is not making six individual seeds via deconstruct, it is making six piles of seeds, each of which is enough to plant an entire tile of pumpkin plants. A single tile can grow ten crops, so a skilled farmer can turn one pumpkin into 60 pumpkins (10 pumpkins times 6 tiles of planted seeds) with a single planting.
