### ISSUE TITLE
some problems with triclopean dog type.

### ISSUE THREAD

**Issue by Blimberryjuice** [CleverRaven/Cataclysm-DDA#69540]
### Describe the bug

Iv just finished crafting "leather dog harness with bones" and then i made it extra sturdy but when i tried to equip it to my "triclopean dog" it said i had no armour available , additionally iv noticed the "triclopean dog" doesn't seems to ever attack enemy's it just stands still in combat even with a dog whistle but perhaps im missing something there.

### Attach save file

N/A

### Steps to reproduce

1.craft "leather dog harness with bones"
2. attempt to equip to triclopean dog.

### Expected behavior

Amour non functional for stated purpose 

### Versions and configuration

- OS: windows 10
- version: d6ec466
- Graphics version: default
- language: english
- mods: disable npc needs , portal storms ignore npcs , no fungal growth.

**Comment by RenechCDDA** [comment]
Please provide a save.

**Comment by Blimberryjuice** [comment]
> Please provide a save.
it keeps telling me the file size is to big , save is like 4 times the accepted limit

**Comment by RenechCDDA** [comment]
You need to use the minimized save archive in the debug menu, as the issue form instructs.

**Comment by Blimberryjuice** [comment]
> You need to use the minimized save archive in the debug menu, as the issue form instructs.

[Dark Fortune-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13402707/Dark.Fortune-trimmed.tar.gz)
this gets deleted afterwards right?

**Comment by RenechCDDA** [comment]
Can't equip the armor on 0.G but experimental works fine.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/72e4c6b7-5cbb-4efa-9fd1-6b975a4c18d6)

I am unsure when or how this was resolved.

>additionally iv noticed the "triclopean dog" doesn't seems to ever attack enemy's it just stands still in combat even with a dog whistle but perhaps im missing something there.

The `animal` faction, which dogs are part of, does not seem to be hostile to zombies so they will never fight. (Boggle is a member of the dog faction, which is perhaps an error?)

>this gets deleted afterwards right?

I'm not sure what you mean. The save you've uploaded will remain on github for... however long github hosts them. You do not need to take any further action.
