### ISSUE TITLE
Inflated base camp construction calorie costs

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69559]
### Describe the bug

I was looking at starting to construct expansions for my bare bones base camp and saw that the calorie costs seem to be about 15000 calories per day. This is either very inflated (if the value is actually kilo calories as is the usual unit), or ridiculously low (if it's only 90 kilocalories).

When dumping food into the calorie store the actual unit seems to be kilocalories.
 

### Attach save file

N/A, both because the save file will be too large and because the issue shouldn't be save dependent.

### Steps to reproduce

1. Create a base camp.
2. Create a livestock 2 expansion (I doubt the type matters, but that's what I created).
3. Contemplate actually constructing stuff, and see the very high calorie costs. Not even the PC is capable of using up so many calories (I think).

### Expected behavior

Either calorie costs based on normal average human consumption, or calorie costs based on the inflated calorie consumption the PC uses for whatever exertion level activity the tasks involved use (in which case construction recipes that don't override the map change costs should tally calorie consumption based on each tile's exertion level, rather than the recipes activity_level, similar to how time and components are tallied). In the latter case, note that the base camp tasks contain a substantial portion set aside for sleep when tasks are longer than "a day".

It can also be noted that the Distribute Food tab claims my food stock of a bit under 500 000 kcal (the same number that's called calories when showing the stock for the construction task) is claimed to last for 190 days, while it would be closer to 30 with the 15000 kcal/day rate. While I made an image of only one task, the others are very close to the 15000 (k)cal per day value as well.

It can also be noted that a lot of food production tasks were net deficits before this change (setting a companion to bake bread and then dump the fresh bread into the calorie store added fewer calories than those used up by the companion, for example)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/071e58d0-a0c8-4f4e-bfdd-e5b40e3c381b)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/f0dc6a05-ccc2-48aa-bf98-77beeb56c30e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 0.G-5296-g011cbe9b43 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ hack to disable portal storms
+ bare bones basecamp custom recipes

### Additional context

The calorie store reported consumption rate seems to match what's been consumed in the past, so a guess is that someone has changed the calorie consumption calculation formula for tasks without changing the reporting of how far stocks would last, leading to a rather substantial discrepancy.

**Comment by RenechCDDA** [comment]
It is kcal.

#65705 added exertion as a cost factor to all faction camp jobs with the default being MODERATE EXERCISE (4x). Previously this factor did not exist. So costs ballooned 4x with that patch, at least. (Crafting recipes have some variance, but all construction is MODERATE_EXERCISE)

The calorie cost calculation before that was simply 2500 calories per workday, which is... like, the base metabolic rate for a human who simply exists.

So yes, the cost went way up, but I can't say that it's necessarily inaccurate. Ideally, instead of a flat 4x it should average the cost of all involved constructions, so that digging pits is way worse than framing wood. But the increase itself is not a bug.

**Comment by RenechCDDA** [comment]
>The calorie store reported consumption rate seems to match what's been consumed in the past, so a guess is that someone has changed the calorie consumption calculation formula for tasks without changing the reporting of how far stocks would last, leading to a rather substantial discrepancy.

What, just for the reported days? That is food for 190 days, not 190 work days. I guess that could be made explicitly clear.

**Comment by PatrikLundell** [comment]
It should be made extremely clear that not only is the estimate for idle companions, but also that the actual consumption rate when actually used would be expected to be many times higher, rendering the figure useless unless you just dump companions into the camp on guard duty or similarly unproductive activities to get them out of your hair. Also, a 4 times increase in exertion cost resulting in a 6 time increase in actual consumption is probably caused by that extreme consumption being upheld during the companion rest periods that extends the time it takes for a job to be completed. The calculation should, at a minimum, be based on the actual work time, not the calendar time used after padding. You could add the base rate for the padding time on top of that if you want to be more precise.

Hm, no, that still doesn't compute. It's 6 times the padded time, not 4 times the padded time, so there appears to be an additional padding on top of the time padding, as if the increased consumption rate was applied first to the padded time and then added half again to account for the idle time (again, and with the full exertion again).

With your formula, the calendar day consumption should be 6667 (4 * 2500 * 2/3) + 833 (2500 * 1/3) kcalories = 7500, not 15000, as I believe the calendar padding is based on 16 hour work days.

**Comment by RenechCDDA** [comment]
>With your formula, the calendar day consumption should be 6667 (4 * 2500 * 2/3) + 833 (2500 * 1/3) kcalories = 7500, not 15000, as I believe the calendar padding is based on 16 hour work days.

Right, that is separate (to_workdays) and has been around forever though.

https://github.com/CleverRaven/Cataclysm-DDA/blob/0026f6f6551a4339c73a9e681905de47cbb0d9c0/src/basecamp.cpp#L88-L96

Though I agree, they probably should not be working at exertion rate during their downtime, and the display for this is inadequate.

**Comment by PatrikLundell** [comment]
I don't have any issue with the padding, as it's reasonable to not work 24 hours a day. My issues are:
- The new code doesn't account for the padding, and thus applies the elevated exertion to the whole time.
- The stored calorie display wasn't updated to reflect the changed usage.
- Those who implemented the new calculation failed to verify that the result of the multiple used actually reflected that multiple, and thus missed a significant error (50% extra on the flawed calculation for a multiplier of 4, resulting in 6 times on the inflated base time).

**Comment by RenechCDDA** [comment]
OK, so help me to understand the ways in which this is wrong and can be made right.

>The stored calorie display wasn't updated to reflect the changed usage.

For this, the **distribute food** mission's description should be something like this?

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/69e01141-cba7-41ab-9458-91ab0f1641b8)

>The new code doesn't account for the padding, and thus applies the elevated exertion to the whole time.

This is understandable, although doing the math for the function might be a bit more complicated.

>Those who implemented the new calculation failed to verify that the result of the multiple used actually reflected that multiple, and thus missed a significant error (50% extra on the flawed calculation for a multiplier of 4, resulting in 6 times on the paddeed base time).

This is the bit I seemed to be missing, and you look to be correct. But just to be clear.

Old: 2500/day \* 1 day \* 1(resting exertion) = 2500 calorie cost

New: 2500/day \* 1 day \* 4(moderate exercise) = *more than 10,000 calories* (about 15k)?

**Comment by PatrikLundell** [comment]
I think your suggestion image is reasonable.

I believe the easiest way to deal with downtime is to have time_to_food reverse engineer the work time:
const int days = to_hours<int>(work) / 24;
const int work_time = days * 10 + to_hours<int>(work) - days * 24;

return 2500 * (work_time * exertion_level + days * 6 * NO_EXERCISE + days * 8 * SLEEP_EXERCISE) / 24;

Note that the above is written there, but not tested in any way, so there may be errors...

The part I can't find in the code is why the multiplication factor ends up at 6 rather than 4 for construction tasks (which is the only one I've looked at), and I would track that down first before changing the formula, as the changed formula makes it harder to see the errors when the factor is made up of several components.
And yes, it definitely looked like 15000 kcal /day for construction.

**Comment by PatrikLundell** [comment]
@RenechCDDA: Are you going to address this? If not, I think I could do it.

**Comment by RenechCDDA** [comment]
Yes, I plan to do this soon.

If for some reason I should disappear or not have anything up in a week or so, guess that means you're up.
