### ISSUE TITLE
Math and Max Mana

### ISSUE THREAD

**Issue by Computer-Engineer-Man** [CleverRaven/Cataclysm-DDA#69556]
### Is your feature request related to a problem? Please describe.

When trying to edit the players max mana pool, the seemingly only way to do it is via the MAX_MANA enchantment. It would be good if we can simply edit the players max mana pool with math directly. 

### Solution you would like.

However, I think this poses a problem with my current understanding of how the max mana calculations work and math functions. With MAX_MANA you can already read to it with math. If you were to try to write to math, you'd have problems with editing the formula directly if you are multiplying. Thus I have below the following solutions I could come up with.

1. Simply adding to the formula.
I lack deep understanding of how exactly math works but if it is possible to just append to the existing formula, this probably would allow math multiplication to work as expected.
Examples: 
(Original Formula) * math_max_mana_multiplication
(Original Formula) / math_max_mana_division
(Original Formula) + math_max_mana_addition
Etc.
Where it'd most likely be just adding the operator and the values.

2. Dehardcoding the formula
If it is possible to simply change the entire formula with math, this would easily solve issues and allow for more creative approaches to how max mana pool functions. This goes a bit outside of the scope of just math but it would also probably need some changes to how math functions to be able to overwrite the JSON mana formula.
Example of the default max_mana formula in JSON:
"max_mana_formula": {  "math": [ "max_mana_formula", "=", "( ( mana_base + ( ( 0.2f + u_val('int') * 0.1f ) - 1.0f ) * mana_base) * guy.mutation_value( "mana_multiplier" ) ) + guy.mutation_value( "mana_modifier" ) - round( max( 0.0f, units::to_kilojoule( guy.get_power_level() ) * guy.mutation_value( "bionic_mana_penalty" ) ) ))" ] }
Clearly to do the 2nd solution would mean adding math functionality to get other things, such as enabling the power level bionic_mana_penalty to be at least able to be read to via math. I tried to turn some of it into what already exists, such as u_val('int'), round(), max(), etc but the remainder I left as it is in magic.cpp on lines 2041-2051. Note this does not include the existing enchantment function call at the end.

### Describe alternatives you have considered.

I couldn't think of any other ways for math to write and retain most functionality with the max mana so if anyone comes up with a better idea it would be greatly appreciated.

**Comment by andrei8l** [comment]
I think this needs a stronger reason than `it'd be nice`. Is there any particular problem that can't be solved with the enchantments (which supports math)? Magic internals are kinda hard to reach from other systems in code so it needs good justification.

**Comment by Computer-Engineer-Man** [comment]
I think after rereading my own feature request I have come to the conclusion this is less about math and more about the nature of the hardcoded max mana formula. Sometime this week I'll make a more coherent feature request regarding what I have in mind. 
But to answer your question, it is impossible to edit the max mana formula with enchantments or math or any existing system.
