### ISSUE TITLE
Wielded item's weight is not updated for barrel

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#69552]
### Describe the bug

Picked an empty 200L barrel, filled it with water while weilding it, can still carry it as if its still empty with low character str.

### Attach save file

[Weebland-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13403690/Weebland-trimmed.tar.gz)

### Steps to reproduce

wield a steel drum
fill with water
enjoy

### Expected behavior

should have effective full weight changed after change of contents weight

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ALT; Description: ALT Workstation K 10.2 (Sorbaronia Mitschurinii); Release: 10.2; Codename: SorbaroniaMitschurinii; 
- Game Version: 61b45f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Xedra Evolved [xedra_evolved],
    Blazemod - Vehicle Additions Pack [blazemod],
    No EMP Damage [no_emp]
]

**Comment by GuardianDll** [comment]
/confirmed
Suppose the game simply forgot to invalidate weight cache when you interact with water
![GIF 19-11-2023 16-53-28](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/ff6b0e0a-e03b-4ace-aaad-6f81ffd71b84)
