### ISSUE TITLE
Candle-Light spell never turns off

### ISSUE THREAD

**Issue by ChaoticBloom** [CleverRaven/Cataclysm-DDA#69564]
### Describe the bug

There is no way to turn off the candle-light power.

### Attach save file

[SageWood-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13404493/SageWood-trimmed.tar.gz)

### Steps to reproduce

1. spawn a character with photokinesis background
2. use candle-light power

### Expected behavior

i expect that when i sleep or use the ability again the power will stop.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: a647a78 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]

**Comment by Standing-Storm** [comment]
Fixed by #69515
