### ISSUE TITLE
Wool version of the Winter Kevlar Jumpsuit

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#69567]
### Is your feature request related to a problem? Please describe.

Wool should be useable as a alternative to Faux Fur or natural Fur for making Winter Kevlar Jumpsuits, as it has moisture wicking properties, and would give felt sheets more use.

### Solution you would like.

Add a Wool Winter Kevlar Jumpsuit, with 50 Warmth to make it cooler than its fur counterparts, as well as only rainproofing, but in return have a much more breathable jumpsuit option for winter

**Comment by Kantonine** [comment]
also a potential wool version of the Winter Survivor Boots that are the same. maybe with slightly less encumberance along with warmth

**Comment by CoroNaut** [comment]
I kind of dislike that we got so many new crafting recipes when custom tailoring of clothing was removed. This issue in particular should've been solved when that happened.
