### ISSUE TITLE
The game freezes for no apparent reason

### ISSUE THREAD

**Issue by Rabadash94** [CleverRaven/Cataclysm-DDA#69562]
### Describe the bug

For some experimental versions, when starting a new character, the game freezes after a few minutes, and without being able to perform any action, and without seeing any message, being forced to quit the game with Alt+F4 (when I do this, I get an OS sign warning that the game is not responding).

### Attach save file

[Tuluksak-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13404422/Tuluksak-trimmed.tar.gz)

### Steps to reproduce

1. Load the saved game.
2. Do something for some seconds or minutes, like walking somewhere.
3. Watch as the game stops responding to anything you do.

### Expected behavior

The game shouldn't freeze.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 011cbe9 [64-bit]
- Graphics Version: Tiles
- Game Language: Español (Argentina) (73,2%) [es_AR]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar Necesidades de PNJ [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Profesiones Biónicas [package_bionic_professions],
    Xedra Evolucionado [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Railroads [railroads],
    ve al jugador, correr, agacharse, sangrando, retrodays [sees_player_retro],
    Armas Genéricas [generic_guns],
    Características por Habilidades [StatsThroughSkills],
    Características por Muertes [stats_through_kills],
    Destreza Veloz [speedydex]
]

### Additional context

The same thing happened in some previous experimental version, but I don't remember which one (I thought downloading the latest one would solve the problem).

**Comment by AcidAntOnAMinefield** [comment]
Yep. Same happens to me. 

After 15-20 minutes, the application just freezes and then either the OS gives me the prompt saying the game is not responding or it just outright closes itself. 

It's been happening for about a week now while constantly remaining up-to-date. 

On occasion, when the game throws in an error screen (either about things not fitting in condoms(?) or about things not being able to spawn in open air, if you try to ignore them, the game will just very much freeze there too.

**Comment by andrei8l** [comment]
From your save I walked west and got a crash that should be fixed by #69558

**Comment by Rabadash94** [comment]
>From your save I walked west and got a crash that should be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/69558

As soon as possible I'm going to try that.
