### ISSUE TITLE
Techniques get double punctuation when used

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#69563]
### Describe the bug

Techniques which have punctuation in their descriptions still get a period automatically from the damage number.

### Attach save file

Reproduction steps complete.

### Steps to reproduce

1. Give self melee skill to use weapon techniques(spotted while using an army bayonet with Rapid Strike).
2. Attack something until the technique triggers.
3. See the technique's punctuation and the automatic period from the damage at the same time.

### Expected behavior

Either an exclamation mark from the technique or period from the damage, not both.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/99621099/0e94a840-6eba-4c34-9a5e-676aa6c9b826)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2715 (23H2)
- Game Version: aec43ef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by harakka** [comment]
/confirm
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/melee.cpp#L2682
The cause seems to be inconsistent writing between hardcoded hit strings like "You gouge" etc and the technique ones that have their own punctuation.
