### ISSUE TITLE
Make drugs use charges instead of by count for performance benefit

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69576]
### Is your feature request related to a problem? Please describe.

Drugs like aspirin are individual items and are counted individually when working with them. It would be a great performance benefit to convert them to charges instead like solder.

Consider a stack of 4096 aspirins, place them on the ground, examine the stack, and select and deselect the stack for pickup. you may notice a slowdown depending on how fast your computer is. On my system in particular, if I spam selecting and deselecting the stack of 4096 aspirin, it will show a clear spike in cpu activity on windows task manager. O(n) speeds.

On the other hand, I could have a stack of solder (100,000) and it is considered as one single item by the game. Much performance. O(1) speeds.

### Solution you would like.

Convert aspirin and other drugs to using charges so the game can combine stacks of drugs much more efficiently. This will effectively be O(1) time instead of O(n) time to process the stack of medicine.

### Describe alternatives you have considered.

Just continuing to play with performance hungry medicine.

### Additional context

I noticed this simply from putting all my medicines into a duffel bag in my main save and noticed that it took a full second any time I did anything with my duffel bag.

**Comment by RenechCDDA** [comment]
Charges are leaving the game, the rationale has been spelled out in the PRs removing them and the many many existing threads complaining.

**Comment by CoroNaut** [comment]
@RenechCDDA Is there some way to provide O(1) performance without charges then? There is a clear benefit to charges.
