### ISSUE TITLE
Stacks of items with high count cause a clear performance impact

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69577]
### Describe the bug

Drugs like aspirin are individual items and are counted individually when working with them. It would be a great performance benefit to consider their stack to be a single item rather than count them in O(n) time.

Consider a stack of 4096 aspirins, place them on the ground, examine the stack, and select and deselect the stack for pickup. you may notice a slowdown depending on how fast your computer is. On my system in particular, if I spam selecting and deselecting the stack of 4096 aspirin, it will show a clear spike in cpu activity on windows task manager. O(n) speeds.

Charges were providing a O(1) speed advantage, but they are being removed.

### Attach save file

N/A This is trivially reproducible

### Steps to reproduce

1. Place 4096 aspirin on the ground
2. Examine the stack
3. Repeatedly select and deselect them
4. Easily notice the performance impact just from selecting them, let alone the crafting menu counting all stacks of all items.

### Expected behavior

Items with higher than average stack counts like aspirin, solder, cotton patches, etc, should be counted as a single item for O(1) lookup.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: eca466b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Would help alleviate #63586

**Comment by RenechCDDA** [comment]
Have you actually profiled this?

**Comment by CoroNaut** [comment]
@RenechCDDA The performance impact is very clear just from selecting a stack of 4096 aspirin. If you want to make doubly sure, put 10,00 aspirin into a duffel bag and then interact with the duffel bag. You will see that there is a slow down.

**Comment by andrei8l** [comment]
The idea is to find where the slowdown is in practice rather than jump to the big O. Many similar performance issues have already been solved and you can help solve this one too with a profile.

**Comment by CoroNaut** [comment]
Unfortunately I don't have all the programming knowledge to generate a proper profile. What I can do is just test in-game and relay that to people who can understand and address the issue. If it's an issue worth fixing of course. All I know is that I can clearly see a slow down and have managed to narrow it down to just "There's a lot of items, and it takes a lot of CPU to interact with them". So, my thoughts are that they are being individually counted, which doesn't seem required. It could be O(1) access.
