### ISSUE TITLE
Deconstructing damaged riot armor does not give damaged components.

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#69572]
### Describe the bug

When using the disassembly function on a Riot Suit, it gives the components at full health.

### Attach save file

N/A

### Steps to reproduce

1.Take a Riot Suit
2. Damage it to |/
3. Disassemble it

### Expected behavior

I expect that the components would be damaged when deconstructed.

### Versions and configuration

Trivial

**Comment by TheShadowFerret** [comment]
/confirmed

This has historically been handled by a lowered chance of component recovery for all things that can be deconstructed.

**Comment by DukePaulAtreid3s** [comment]
There is a lower chance of components, at least now. I am closing this now
