### ISSUE TITLE
Legless characters are (nearly) immune to attacks

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#69575]
### Describe the bug

Enemies are effectively unable to damage characters without legs, as they rarely attack the torso and leg stubs not being real legs cannot bleed from damage.
I was able to beat a z-dog to death and feral human to 60% with a pipe mace while stats are zeroed out from pain and having 1100+ move cost due to being prone.

### Attach save file

N/A

### Steps to reproduce

1. Spawn in as Para-Amputee
2. Spawn in a ~~zombie dog/rot-weiler~~ anything.
3. Watch as they attempt to bite your prone body's leg stub into dust, dealing only pain but no damage or bleed.

### Expected behavior

Enemies are able to attack the arms, torso & head if crouching or prone.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2715 (23H2)
- Game Version: 4f8557f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by TheShadowFerret** [comment]
Update, applies to everything
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/99621099/754fbf6f-176b-4cc9-ac62-b0e6c97dbeb7)

**Comment by MNG-cataclysm** [comment]
/confirmed

I think a good solution for this would be to model leg stubs more like actual flesh. While enemies couldn’t necessarily damage them (since they have 0 HP) attacks could apply pain and bleeding to the character just as well as other limbs.
