### ISSUE TITLE
Vampire stage 3 abilitys not obtainable. 

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#69588]
### Describe the bug

After this FIX #68906 Xedra Evolved EOC fail #68911 was merged, i was not able to obtain vampire stage 3 abilitys.
I do get the emptyness effect and the bloodthirst as stated in the message log but not mortal hunger is replaced with immortal hunger and all the Vampire stage 3 abilitys, that you should get after that. It just says at a certain point, that i can not advance furthur without a mentor and reached the 4. wall.
The vampire stage 3 abilitys are still in my save file but not obtainable though normal means. I can just debug them.

Edit: I testet it again on a new safe, with the same set up and this time i not only did not got the vamp3 abilitys but also did not got gleaming eyes and children of the night!  

### Attach save file

[Bonham-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13416605/Bonham-trimmed.tar.gz)
[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13417755/test-trimmed.tar.gz)

### Steps to reproduce

-Make a charackter in a normal world
-get bit
-evolve to vampire stage 2
-get bloodthirst and emptyness effect but do not get vamp3 abilitys and not the immortal hunger
-get 4. wall message and stop evolving

### Expected behavior

get immortal hunger and vamp3 abilitys and stop evolving after the 4. wall message.

### Versions and configuration

Windows 10
experimentell build 2023-11-20-0516
mods: Dark days ahead, Xedra evolved

**Comment by Maleclypse** [comment]
[Test Vampire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13420278/Test.Vampire-trimmed.tar.gz)
@lispcoc Sorry to bother you.  I've looked at my test save from #68911 and it has gained all the tier three abilities and is now receiving the 4th wall message.  But when I created a new world attached above I'm experiencing the same issue as the person reporting. 

Below is the relevant eoc.  Any advice is appreciated for how this has gotten messed up.  
```
{
          "id": "EOC_VAMPVIRUS2",
          "condition": {
            "and": [
              { "u_has_effect": "vampire_virus", "intensity": 3 },
              { "compare_num": [ { "u_val": "effect_intensity", "effect": "vampire_virus" }, "=", { "const": 3 } ] }
            ]
          },
          "effect": {
            "run_eocs": {
              "id": "eoc_vampvirus_3_trait",
              "condition": { "u_has_trait": "VAMPIRE3" },
              "effect": [
                {
                  "u_roll_remainder": [ "BLOODHASTE", "HYPNOTIC_GAZE", "BLOODBANK" ],
                  "type": "mutation",
                  "true_eocs": [ "EOC_SUCCESFUL_ROLL_REMAINDER" ],
                  "false_eocs": [ "EOC_COMPLETED_VAMPIRE3" ]
                },
                {
                  "u_message": "You feel the absence of your heart beating for several seconds and then it resumes at this new rhythm."
                }
              ],
              "false_effect": [ { "u_message": "You can advance no further without access to a mentor.  (4th wall no further content exists yet)" } ]
            }
          }
        }
```

**Comment by lispcoc** [comment]
I don't know all the elements related to vampires, so I may be saying something off-topic, but there is something strange about comparing "eoc_vampvirus_2_trait" and "eoc_vampvirus_3_trait".

"eoc_vampvirus_2_trait" does not give "VAMPIRE3" when it fails, so it will continue to fail no matter how many times it is executed. Can this trait be acquired elsewhere?
```
        {
          "id": "EOC_VAMPVIRUS1",
          "condition": {
            "and": [
              { "u_has_effect": "vampire_virus", "intensity": 2 },
              { "compare_num": [ { "u_val": "effect_intensity", "effect": "vampire_virus" }, "=", { "const": 2 } ] }
            ]
          },
          "effect": {
            "run_eocs": {
              "id": "eoc_vampvirus_2_trait",
              "condition": { "u_has_trait": "VAMPIRE2" },
              "effect": [
                {
                  "u_roll_remainder": [ "BLOODHEAL", "COAGULANTWEAVE" ],
                  "type": "mutation",
                  "true_eocs": [ "EOC_SUCCESFUL_ROLL_REMAINDER" ],
                  "false_eocs": [ "EOC_COMPLETED_ROLL_REMAINDER_VAMPVIRUS", "EOC_VAMPVIRUS2" ]
                },
                { "queue_eocs": "EOC_ADD_VAMPIRUS_INTENSITY2", "time_in_future": [ "15 days", "8 hours" ] }
              ],
              "false_effect": [
                { "u_add_trait": "VAMPIRE2" },
                {
                  "u_message": "With a popping sound several of your teeth fall out but when you put a finger into your mouth to feel the hole, there are new sharp fangs where you expected nothing."
                }
              ]
            }
          }
        },
        {
          "id": "EOC_VAMPVIRUS2",
          "condition": {
            "and": [
              { "u_has_effect": "vampire_virus", "intensity": 3 },
              { "compare_num": [ { "u_val": "effect_intensity", "effect": "vampire_virus" }, "=", { "const": 3 } ] }
            ]
          },
          "effect": {
            "run_eocs": {
              "id": "eoc_vampvirus_3_trait",
              "condition": { "u_has_trait": "VAMPIRE3" },
              "effect": [
                {
                  "u_roll_remainder": [ "BLOODHASTE", "HYPNOTIC_GAZE", "BLOODBANK" ],
                  "type": "mutation",
                  "true_eocs": [ "EOC_SUCCESFUL_ROLL_REMAINDER" ],
                  "false_eocs": [ "EOC_COMPLETED_VAMPIRE3" ]
                },
                {
                  "u_message": "You feel the absence of your heart beating for several seconds and then it resumes at this new rhythm."
                }
              ],
              "false_effect": [ { "u_message": "You can advance no further without access to a mentor.  (4th wall no further content exists yet)" } ]
            }
          }
        }
```

**Comment by Maleclypse** [comment]
> I don't know all the elements related to vampires, so I may be saying something off-topic, but there is something strange about comparing "eoc_vampvirus_2_trait" and "eoc_vampvirus_3_trait".

Thank you for taking a look at it.  I had apparently made a mistake when changing some messages after testing a previous fix.  I really need to learn not to change anything even if I think it's cosmetic after I do my last test without retesting from the start.  My test world character already had VAMPIRE_3 so he was past the stage where there error was.
