### ISSUE TITLE
[Innawood] Request to add "birch tar" to the mod

### ISSUE THREAD

**Issue by BjoHart** [CleverRaven/Cataclysm-DDA#69582]
### Is your feature request related to a problem? Please describe.

It would be nice if there was an option to make birch tar for the mod in the game.

As an alternative to bone glue for the recipes glue would otherwise be used for.

### Solution you would like.

https://en.wikipedia.org/wiki/Birch_tar

If someone would take the trouble to introduce the material and update the linked recipes, that would be great.

**Comment by Spicyshadow** [comment]
Birch tar is also a disinfectant. This would probably be a good addition to the base game itself not just to innawood.
