### ISSUE TITLE
Knife Training Doesn’t Use Marine or Army Kinves.

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#69599]
### Describe the bug

You cannot preform the knife training action with the Marine Bayonet nor the Army Bayonet.

### Attach save file

N/A

### Steps to reproduce

1. Get a USMC Bayonet/US Army Bayonet
2. Attempt to Practice Knife Familiarity 

### Expected behavior

The ability to perform that action.

### Versions and configuration

Trivial

**Comment by GuardianDll** [comment]
can't confirm - melee, cutting and knife training recipes all use `real_knives` requirements, and this requirement contain both USMC Bayonet/Army Bayonet

**Comment by DukePaulAtreid3s** [comment]
> can't confirm - melee, cutting and knife training recipes all use `real_knives` requirements, and this requirement contain both USMC Bayonet/Army Bayonet

Crap, it might be because I'm on Mac then. I'll find my exact configs later, but it's running on Big Sur and a ~1 week old experimental.

**Comment by GuardianDll** [comment]
it was added in #69427, merged 4 days ago

**Comment by DukePaulAtreid3s** [comment]
Ok, will close then
