### ISSUE TITLE
Retractable telescope has 2 copies of required tools

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69598]
### Describe the bug

Retractable telescope recipe has 2 copies of the same tool requirement. I also noticed the "coilgun" has 2 copies of required tools too. and "tonfa"

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. look in crafting window for retractable telescope or coilgun or tonfa
2. 2 copies of tool requirement

### Expected behavior

One copy of tool requirement

### Screenshots

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/d99d10bf-286d-4a9c-9de0-1392a9eb59f6)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: eca466b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
Retractable telescope uses requirement `surface_heat` and `plastic_molding`, and plastic molding itself contain another `surface_heat`

**Comment by GuardianDll** [comment]
No, it is not a good first issue, you can't resolve it by removing or adding someting into the recipe, one should alter the way UI combine it's requirements to resolve it
