### ISSUE TITLE
[InnaWood] Clothing made from cotton has broken repair skill

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#69593]
### Describe the bug

Clothing made from cotton while playing InnaWood requires level 10 in tailoring. even for absurdly simple items, such as socks/stockings, hoodies, and pants

### Attach save file

[Antone-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13419010/Antone-trimmed.tar.gz)

### Steps to reproduce

1. Spawn any item made with only cotton in, such as socks, stockings, hoodies, and pants
2.  Spawn in different leather, fur, and wool items
3. spawn in any needle or sewing kit
4. observe tailoring repair level needed is maxed out for cotton, but not for leather,  wool, or fur

### Expected behavior

Cotton should retain its necessary skill level to repair for individual items from the base game. being stuck in a prehistorical world shouldn't mean that cotton is somehow unrepairable by anyone other than a master tailor

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/eaf0073d-c031-4242-9eea-c37ce0e2e7a6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 3b4ed90 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Innawood [innawood]
]

**Comment by RenechCDDA** [comment]
materials.json needs `repair_difficulty` assigned for materials it intends to be normally repairable.

**Comment by BjoHart** [comment]
I can confirm this.
Difficulty is very high for clothing made from cotton.

![Tailoring](https://github.com/CleverRaven/Cataclysm-DDA/assets/69985946/d450db77-fdcb-4752-a548-dc989c6fb41f)
