### ISSUE TITLE
Items wielded from ground examine window with only one item cause "There is nothing to pick up" window

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69609]
### Describe the bug

Picking up one item from a list of items on the ground containing only one item will trigger the "There is nothing to pick up" window if that item is wielded with nothing in hand. I assume this message is a automatic fallback for when the list of items you are viewing becomes empty.

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Place one item (In pictures I used tailors kit) on the ground by itself with nothing in hand.
2. 'e' examine the ground where you placed the item
3. 'w' wield the only item in the list
4. "There is nothing to pick up" message appears.

### Expected behavior

Message "There is nothing to pick up" window doesn't appear, since I did in fact pick up the only item on the ground.

### Screenshots

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/4e69e3d0-5a6b-406a-b376-2a2775bc4ba6)
![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/af54ab5a-06ba-49ab-9c49-0a7f5a2c31fb)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: eca466b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    No Monsters [Only_Wildlife]
]

**Comment by mqrause** [comment]
Duplicate of #58473.
