### ISSUE TITLE
tailoring_leather_patchwork overwritten when it shouldn't be

### ISSUE THREAD

**Issue by Pearilous** [CleverRaven/Cataclysm-DDA#69606]
### Describe the bug

recipes calling tailoring_leather_patchwork call a different pool of items than what it's supposed to when

### Attach save file

[Magicalysm2.0-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13423186/Magicalysm2.0-trimmed.tar.gz)

### Steps to reproduce

Make a player with at least 3 tailoring and 1 combat

check spear strap recipe, and compare it to https://cdda-guide.nornagon.net/item/spearsling

### Expected behavior

recipe should match https://cdda-guide.nornagon.net/item/spearsling . but does not.

### Screenshots

https://cdn.discordapp.com/attachments/642349261320880128/1176422906515947530/image.png?ex=656ed035&is=655c5b35&hm=63ccdcf982f95e997d0a43cc0970238a4d1a4a33c3fabc354943fb690091829b&

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a11a36 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    <color_light_blue>Lighter Weariness</color> [light_weariness]
]

**Comment by RenechCDDA** [comment]
OK, glad we figured that one out (on discord). Your version wasn't up to date as you were confused by the launcher.

This issue has been resolved since then, so closing.
