### ISSUE TITLE
Glock can't use 15-round mags?

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#69612]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53100513/dfadff1b-aed3-474b-9342-93dd48990b86)

### Attach save file

[Wooldridge-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13426775/Wooldridge-trimmed.tar.gz)

### Steps to reproduce

1. Get glock
2. 2. Get glock 15 rounder
3. cant reload it with taht?

### Expected behavior

I dont see why it cant.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53100513/9f593310-2c04-4016-ac88-253bc123507b)

See how 15 roudner is missing

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: de7f85e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/8e02002e4d056e5ba8beead476a75e595eb28900/data/json/items/gun/9mm.json#L939
I think we should clarify it somewhere in the description

**Comment by carlarctg** [comment]
@GuardianDll Then there's a different problem, Glock 17s spawned on zombies with glock 15 magazines as spare ammo.

**Comment by GuardianDll** [comment]
can't confirm this, all itemgroups i see specifically omit 15-round `glockmag`
