### ISSUE TITLE
Glitched spawn of bridge of one tile long without roads on both sides

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69611]
### Describe the bug

Edge-case problem when spawning a bridge of length 1 map tile?

### Attach save file

[Lenora.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13426603/Lenora.zip)

### Steps to reproduce

Map generation causes this, no steps. Save file included

### Expected behavior

Bridge of length one should probably appear of very narrow water ways, but should ensure that both sides have a bridge head and roads to connect to.

### Screenshots

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/47b0b095-fcb4-4965-8263-8bcfa56af791)
![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/2eb87e6b-0313-4799-8de1-6e9ea8592f4c)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: eca466b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by CoroNaut** [comment]
I found another occurance
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/128798ab-7005-4aaf-ac71-55e0961096b8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/db56170a-fe7d-4dc1-adbd-0500a409b58f)

**Comment by Procyonae** [comment]
Dupe of #22133 which should never have been closed, #70471 could be used as a workaround if implemented
