### ISSUE TITLE
[Xedra Evolved] Can't repair tsurugi of speed (and possibly other dreamforged stuff) with oneiric hammer

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#69635]
### Describe the bug

Looks like i cant repair the Tsurugi of Speed with the oneiric hammer, but i can repair it like repairing a metal thing with arc welder and similar implements.

### Attach save file

N/A

### Steps to reproduce

1. Get Tsurugi of Speed
2. Damage it
3. get oneiric hammer
4. activate the hammer
5. see that theres no damaged item that can be repaired with oneiric hammer

### Expected behavior

Being able to repair it with the oneiric hammer

### Screenshots

![Screenshot_2023-11-22_08-05-50_1](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/dff98fc1-4ef8-4076-aedb-ceb29fe2f766)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 8e02002 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Bombastic Perks [bombastic_perks]
]

### Additional context

May also happened to some other dreamforged items

**Comment by GuardianDll** [comment]
it is odd, it copies from dreamforged broadsword 🤔
