### ISSUE TITLE
More reality bubbles

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#69634]
### Is your feature request related to a problem? Please describe.

When something fights as you leave, it is no longer in the reality bubble and the fight carries on once you get back, possibly days later.

When you leave NPC that is doing something, it stops doing it, (Didn't make sure this is true.)

_I originally wanted to work on NPC programming for the player, but the NPCs need to be able to deploy reality bubbles to do useful things outside the player's range in a realistic manner - realistic by the game standards, unlike cutting down forests through faction camp, which ignores monsters in that location (I believe, but didn't check.)._ 

More cases I don't know about. How do the forest fires work now? Or a regular fire at the base?

Another might be a monster that follows your scent but is slower than you. Assuming the scent lasts for 4 hours, the monster could catch up with you after 4 hours. (I didn't look up how long the scent lasts.)

### Solution you would like.

Deploy a reality bubble around something interesting giving it some time to complete. Interesting things are listed above.

_I didn't see nor know where the code regarding the reality bubble is so I am assuming all this from my experience and a couple of questions._

**Bubble count**
The number of bubbles would be limited for performance reasons. I assume the game can handle only a few bubbles so they might be reserved for super interesting things like friendly NPCs doing tasks. On the off chance that 100s of bubbles can be handled, we still cannot allow some chain effect to get over the limit,

**Status quo**
If we do not deploy a bubble or stop one, the game will behave like before this change, so the "fail" case is the current case on the master branch.

**Bubble's end**
The bubble stops existing, simply offloading everything, like when something leaves a reality bubble or a game is saved.

**Lifetime**
The interesting thing could end: the fight ends, NPC finishes its task etc. That is a natural time for the bubble to end. However, many times, the thing might not have an ending in sight, Then some counter, like 100 player turns, is the maximum limit the bubble can live before its termination.

Every bubble would have a purpose (NPC crafting, waiting for a fight to end, monster moving (scent example)). This purpose determines the maximum lifetime for a bubble.
1. If NPC should craft for 8 hours, let's give it 8 hours of lifetime (and care about whether the NPC stopped before or whether they need more time).
2. A fight might take 100 player's turns (fine-tune this based on testing). Note that a fight doesn't always end (both parties regenerate too quickly). Or it might chain reaction into more fights.
3. A bubble for a character following someone: hard limit of 1000 turns or when they lose scent (sight) for 25 turns, whichever comes sooner.

The player's bubble lifetime is infinite. Generally not making the player bubble a special case handled outside the reality bubble code would be better, I think.

**Centre**
The bubble has a purpose, e.g. NPC crafting or a fight. The centre of the bubble shall be on that interesting thing (pointer to the character etc.). Not sure if a vector of fighting monsters as the centre is better...

Anyway, the bubble can move as the centre moves as the character moves.

**Chain reaction**
A bubble can trigger the construction of another bubble. This has to be limited by the total bubble count. This is in the default behaviour by design, as the player bubble is constructing bubbles for everything mentioned above.

**Purely technical**

- Bubbles should be saved and loaded.
- Bubbles could have priority so that high priority bubble can be made by sacrificing a lower priority bubble.
- I don't like the idea of postponing a bubble (saving that something was interesting there, but constructing the bubble later, or pausing a running bubble), this could get weird.
- The purpose is saved.
- Range of reality bubble: some fights might not need to simulate more than one chunk, which could save some resources.

### Describe alternatives you have considered.

Increasing the reality bubble width doesn't solve the problems proposed, as there still is an edge that can be crossed.

Bubbles could have a count limit per purpose instead of priority. Then you can always make more bubbles for something specific even if some other count is filled without the need to stop a running bubble.

### Additional context

~I want to propose this as my bachelor's work.~ It is actually scary.

**Comment by Qrox** [comment]
I see two problems here:

1. This might lead to severe performance loss if an "interesting thing" happens to be near a heavily populated area. Currently the player can simply leave the area to regain performance but with multiple reality bubbles the player will no longer be able to do that.

2. Limiting the number of reality bubbles might lead to inconsistent results when player assign the same task to an NPC on different occassions, which IMO is worse than the NPC consistently not doing anything when the player is away.

**Comment by Brambor** [comment]
> 1. This might lead to severe performance loss if an "interesting thing" happens to be near a heavily populated area. Currently the player can simply leave the area to regain performance but with multiple reality bubbles the player will no longer be able to do that.

Let us say, that the first implementation is infrastructure for the ability to let friendly NPCs have reality bubbles. Not necessarily assigning a reality bubble to every interesting thing but limiting it to special cases and implementing it in such a way that accounting for "interesting thing" is as simple as it can be.

In extreme cases, all reality bubbles could be turned off in the debug menu or settings, but this is a path I would not like to follow as it invites more problems.

I am personally not aware of such cases, maybe I move too slowly next to heavily populated areas to notice.

> 2. Limiting the number of reality bubbles might lead to inconsistent results when player assign the same task to an NPC on different occassions, which IMO is worse than the NPC consistently not doing anything when the player is away.

This is a very valid point. The zeroth implementation would create reality bubbles only through the debug menu by direct assignment. The first experimental implementation could explicitly tell the player that they gave an NPC a task but now they are leaving them and it didn't create a reality bubble (this is trivial from an implementation standpoint). I would deem that an acceptable narrative-reality hit. Not limiting the number of reality bubbles can get out of hand from a performance standpoint, so it is required.

**Comment by Brambor** [comment]
If this project fails, I hope that what will be left is a more explicit code about the single reality bubble. Effectively a refactor.

**Comment by fairyarmadillo** [comment]
I think this is worth a try no matter what the results as long as we have a "maximum reality bubbles" setting in the debug options.

**Comment by John-Candlebury** [comment]
I want to mention here that momentarily being able to load additional bubbles for artillery/mortar bombardment has been a desired feature for a long time: https://github.com/CleverRaven/Cataclysm-DDA/issues/15284#issuecomment-181155781

I believe the same goes for scouting with binoculars and sniping, so you would be able to actually see whats nearby from a radio tower

**Comment by andrei8l** [comment]
Instead of more reality bubbles, consider just catching up on missed time when the interesting thing re-enters the one bubble. Meaning you'd simulate the missed time, possibly at reduced resolution/granularity. NPCs already do this for activities.

**Comment by Brambor** [comment]
Also, catching up would introduce more code complexity than additional reality bubbles. I think.

**Comment by kevingranade** [comment]
Other than the examples candlebury lists of briefky "extending" the players reality bubble,  nothing mentioned here are things we want to do with reality bubbles.

Monsters off the map should move around on the overmap, this feature is called hordes, see https://github.com/CleverRaven/Cataclysm-DDA/projects/3
NPCs should move around and interact with the overmap. Any changes they make can be handled the next time the map is loaded. 
Fire should spread on the overmap and the effects should be applied to the map on next load.

**Comment by Brambor** [comment]
Lets say I want to make a feature: programable NPC - give a NPC list of tasks they should do, like: loot a house, bring loot home.

How would I go about implementing that without reality bubble around NPC @kevingranade ?

**Comment by Zireael07** [comment]
@Brambor My guess is "move NPC on the overmap", simulate gathering loot, move NPC on the overmap back to camp.

**Comment by Brambor** [comment]
> @Brambor My guess is "move NPC on the overmap", simulate gathering loot, move NPC on the overmap back to camp.

Does this automatically solve the issue of a zombie spotting NPC?

**Comment by fairyarmadillo** [comment]
> > @Brambor My guess is "move NPC on the overmap", simulate gathering loot, move NPC on the overmap back to camp.
> 
> Does this automatically solve the issue of a zombie spotting NPC?

Some faction camp missions simulate random encounters. There's a danger level on the mission indicating the likelihood that something will go wrong, and a simple skill check to determine what happens.

**Comment by esotericist** [comment]
> > @Brambor My guess is "move NPC on the overmap", simulate gathering loot, move NPC on the overmap back to camp.
> 
> Does this automatically solve the issue of a zombie spotting NPC?

if we hook them into interacting with the low-precision simulation for hordes, it could very well solve that. we don't need the full reality bubble simulation to get 'good enough' results for distant actors.

in general, there's a lot of things that can be handled through course simulation we just don't have to care all that much about the fine details in. there's just a bunch of work that needs to go into enabling that. it is a lot of work, but from a technical difficulty standpoint, it's almost all substantially easier than completely reinventing the fundamentals of "what is a reality bubble".

**Comment by Brambor** [comment]
> in general, there's a lot of things that can be handled through course simulation we just don't have to care all that much about the fine details in. there's just a bunch of work that needs to go into enabling that. it is a lot of work, but from a technical difficulty standpoint, it's almost all substantially easier than completely reinventing the fundamentals of "what is a reality bubble".

My proposal wouldn't change anything about reality bubble, it would just make more of them. What happens when something enters or leaves a bubble would be the same.

My vision is NPCs programmed by player to do player like things. You could even execute that program on yourself, to do some boring task automagically.

But I worry that, if reality bubbles are not implemented, then everything will have to be done twice: once for within reality bubble interaction and once for outside it.

If you can send NPC to loot a town and they are ignored by zombies, that is a balance breaking feature. So all that extra code (overmap handling) is necessary before it can make it into the game. And if overmap differs from reality bubble interaction, then you cannot easily ask NPC to clear all roads simply by walking over them and killing everything that comes at them. These discrepancies are what pushes me to favour this change. Also the proper fix of stopping a fight between fractions indefinitely until you come back.

You just cannot catch-up evaluate some things, because they would come for you sooner. So I see this as a way for the player to experience a world that breaks the impression less by being less player-centric.

I see that you have experimented with reality bubble before, I might yoink some of that code :)

**Comment by Brambor** [comment]
I might just try making this, even if it doesn't make it into the game :(

**Comment by CoroNaut** [comment]
Perhaps as an aside, the NPC's movement on the map could "take away" from loot pools in some overmap tiles. If an NPC scavenges an area, have its loot pool be reduced from 100% to 90% or 80%, etc. So when the player moves there, it will generate less loot. I'm of course not sure how it would work if the overmap tile was already generated fully by the player, if the NPC could just "take" whatever loot you hadn't.

**Comment by fairyarmadillo** [comment]
> Perhaps as an aside, the NPC's movement on the map could "take away" from loot pools in some overmap tiles. If an NPC scavenges an area, have its loot pool be reduced from 100% to 90% or 80%, etc. So when the player moves there, it will generate less loot. I'm of course not sure how it would work if the overmap tile was already generated fully by the player, if the NPC could just "take" whatever loot you hadn't.

Roving gangs of bandits when.

**Comment by esotericist** [comment]
@Brambor while obviously your time is your own to spend how you wish, i would implore you to start with something simpler to build more familiarity with how the game functions. you are holding a great deal of assumptions about how the game works and why it is constructed the way it is that do not match the actual technical realities, and i fear you're going to spend a lot of effort only to end up frustrated.

**Comment by esotericist** [comment]
> Perhaps as an aside, the NPC's movement on the map could "take away" from loot pools in some overmap tiles. If an NPC scavenges an area, have its loot pool be reduced from 100% to 90% or 80%, etc. So when the player moves there, it will generate less loot. I'm of course not sure how it would work if the overmap tile was already generated fully by the player, if the NPC could just "take" whatever loot you hadn't.


this, by the way, is basically the plan.

**Comment by Brambor** [comment]
> @Brambor while obviously your time is your own to spend how you wish, i would implore you to start with something simpler to build more familiarity with how the game functions. you are holding a great deal of assumptions about how the game works and why it is constructed the way it is that do not match the actual technical realities, and i fear you're going to spend a lot of effort only to end up frustrated.

I did some things with CDDA already (see my PR's). I plan to do this as a bachelor's work. I have loot of assumptions mainly because I haven't played the game for a while. I am eager to learn the truth by exploring the existing code.

**Comment by kevingranade** [comment]
```Lets say I want to make a feature: programable NPC - give a NPC list of tasks they should do, like: loot a house, bring loot home.```
CoroNaut pretty much nailed it, we do some kind of estimate of what a location will generate and produce "what the NPC looted" as a result of the looting activity. Meanwhile we leave a marker like "looted some medicine" on the overlap at that location, when/IF(!!!) that location is actually loaded, we use any markers present to adjust the location. Subsequent overmap interactions will also reference any placed markers.
This is a more general mechanism than just looting, hordes of monsters moving through an area would also leave a trail of markers that can resolve to terrain/furniture destruction, item removal or destruction,  interaction with traps, etc.

If this were *just* NPCs interacting I might say go ahead and load a tinymap at that location and edit the real terrain, because NPCs are rare enough that occasionally loading a map chunk to make those edits isn't going to cause an excessive amount of overhead. The problem happens when we're talking about hordes, which would be editing dozens of places scattered all over the overmap every turn because there's so many monsters moving around. Also having all of this monster and NPC activity trigger map generation and even worse, creation of more map terrain would be absolutely terrible for the disk footprint of the save directory.

Given that we need that kind of system to limit the overhead of processing hordes, it makes sense to do the same thing for NPC's as well.

**Comment by Brambor** [comment]
I meant it for NPCs originally, but then realised it could solve the problems mentioned. I didn't think about the disk usage at all. I guess I will try implementing reality bubbles. Then use it for NPCs, and some things mentioned like grenade launchers and binoculars. If some other uses that wouldn't destroy the performance arise, we could try them too.

**Comment by Brambor** [comment]
And I didn't mean to give RB (reality bubble) to every monster to simulate it, just to those who seem like they will probably have impact on player, like the fighting at edge of players reality bubble. I went off and imagined all the problems it could solve, but the CPU might suffer greatly. If not, we can discuss it later, when the basics of RBs are implemented and these kind of things are the next logical step to add to RB's support.

**Comment by CoroNaut** [comment]
A suggestion: Perhaps have the ability for a vehicle to have cameras on it and be able to remote-control it away from the reality bubble. Would be neat if the player had to make a small radio tower to extend its range to like 20-50 overmap tiles or such. It could be an appliance too, so a vehicle with small radio tower on it could be a control station to investigate dangerous areas.

**Comment by Brambor** [comment]
I found something else to work on, there are likely many scary things in the code.

If anyone wants to take this on, they are more than welcome! :)
