### ISSUE TITLE
Crashing upon launch: Android Build

### ISSUE THREAD

**Issue by JDaggon** [CleverRaven/Cataclysm-DDA#69633]
### Describe the bug

Crashing on launch, cannot even reach the menu.

### Attach save file

N/A

### Steps to reproduce

1) Download one of the more recent experimentals

2) Update game 

3) Game crashes upon completion of update, cannot reopen app.

### Expected behavior

The game would launch

### Versions and configuration

OS: Android 10, Motorola G7 power
Version: 8d87411

Rest N/A as game can't launch to get report.

### Additional context

VERSION: 8d87411
Signal SIGSEGV: Segmentation fault
STACK TRACE:
#4: 0x760a8ff690 __kernel_rt_sigreturn
#6: 0x751a49aedc cata_cursesport::curses_drawwindow(catacurses::window const&)
#8: 0x751a5c6120 ui_adaptor::redraw_invalidated()
#10: 0x751974463c realDebugmsg(char const*, char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#11: 0x75194d0f78 void realDebugmsg<char const*, char const*>(char const*, char const*, char const*, char const*, char const*&&, char const*&&)
#12: 0x75194d1d2c read_from_file_json(cata_path const&, std::__ndk1::function<void (JsonValue const&)> const&)
#13: 0x751a082f04 Name::load_from_file(cata_path const&)
#14: 0x751a595b14 set_language(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
#15: 0x751a595988 set_language_from_options()
#16: 0x7519cf0e34 SDL_main
#17: 0x751b50d5f0 Java_org_libsdl_app_SDLActivity_nativeRunMain

**Comment by JDaggon** [comment]
Most recent update fixed issue, apologies.

**Comment by NetSysFire** [comment]
Closing as fixed then.
