### ISSUE TITLE
Monsters occasionally move more often than they should be capable of

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#69642]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/7a27d680-aac4-443d-833b-a0194c9e0f23

Between 0822.20 and 0822.21(game displayed time) the swimmer zombies gets two moves and moves two tiles. There are two debug messages printed to the log.

This should not be possible.

### Attach save file

[Pawnee Station-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13439301/Pawnee.Station-trimmed.tar.gz)

### Steps to reproduce

Load given save, replicate movements in video

### Expected behavior

Monster should not move twice

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: 02f75a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by mqrause** [comment]
Zombies randomly stumble a tile in a random direction sometimes, is it just that or something different?

**Comment by RenechCDDA** [comment]
There is no debug message indicating a stumble, so I do not believe it is a stumble.

https://github.com/CleverRaven/Cataclysm-DDA/blob/02f75a2231393db391d883b357d93b5e26757cb4/src/monmove.cpp#L2275

**Comment by PatrikLundell** [comment]
And it's not a case of the swimmer zombie being fast, so each turn should move them one tile and a bit and the bits eventually adding up to a regular move plus a move due to accumulated bits in a single turn?

**Comment by RenechCDDA** [comment]
The opposite. They have speed 90, and you can see I have speed 100. So they should be "losing" 10 moves per tile we both travel. Basically, I should be outpacing them.

But somehow in one player turn, they managed to move twice (their effective speed was >100).
