### ISSUE TITLE
Visitor's pass usually fails to reveal anything except roads

### ISSUE THREAD

**Issue by actually-a-cat** [CleverRaven/Cataclysm-DDA#69646]
### Describe the bug

Visitor's pass is supposed to reveal a TCL, but usually fails to do so.

As I understand it, it works by revealing TCL tiles within a radius of 90 overmap tiles, but it's nowhere near guaranteed that there will be a TCL within that radius.

### Attach save file

N/A, a blank world is the best place to reproduce this

### Steps to reproduce

1. Create new world
2. Spawn visitor's pass and activate it
3. Observe "You add the facilities to the map" in the log, but most times there are no facilities

### Expected behavior

Since the pass is supposed to point to a specific facility rather than being a general map of an area like other similar items, it should reveal it (and possibly the path to it) regardless of distance, somewhat like how the terminal at evac shelters reveals the refugee center.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 02f75a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Inglonias** [comment]
i've always thought it was a little odd that the visitor's pass revealed roads at all. At the very least, it shouldn't do that.

**Comment by harakka** [comment]
/confirm

Has come up regularly recently on devcord. Here's a save where it seems to reproduce. Repro steps: load save, activate visitor pass. A bunch of roads get revealed but no TCL.

[DEBUG-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13529519/DEBUG-trimmed.tar.gz)

**Comment by Procyonae** [comment]
> i've always thought it was a little odd that the visitor's pass revealed roads at all. At the very least, it shouldn't do that.

If the pass is giving you the exact location of the facility it's presumably going to have to include some surroundings, the road routes to it make most sense in this situation, ideally the revealed roads would be centred around the found TCL rather than always being revealed and around the pass source but it makes more sense than just the TCL being shown imo

**Comment by Inglonias** [comment]
Ehhh. A visitors pass is usually the size of a credit card. You really can't fit much more than an address on it. Certainly not a reasonable size for a legible map.

**Comment by Maleclypse** [comment]
Potentially fixed by #70480
