### ISSUE TITLE
Strange slowdown when examining items in the inventory after picking up an item

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69659]
### Describe the bug

For some reason, I can get my character into a weird state where examining any item in my inventory takes a second to load the examine window, but only after moving a tile.

I'm aware that there might be caching going on? So it would cache your interaction to make them faster, but why would it reset the cache after moving a tile?

Picking up an item seems to recreate the bug randomly. If my character gets into a normal state (without the delay in examining items), it would take picking up quite a few items before the bug happens again. As for when the bug goes away is also pretty random, Please note that I don't think there is anything specifically wrong with the "heavy battery mod" item, which is what I use in my save file to recreate the bug. It happened to me while picking up a gallon jug of bleach, and the m9 magazines in the inventory.

I'm providing a save file where the bug exists upon loading, and a save file before the bug with steps to recreate the bug.

### Attach save file

This save file has the bug immediately upon loading into the game:
[testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13445213/testing-trimmed.tar.gz)

This save file is just before the bug initiates:
[testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13445260/testing-trimmed.tar.gz)

### Steps to reproduce

For the save file with the bug immediately upon loading into the game:
1. Load save file provided
2. 'e' examine any item, or hit 'enter" to open up actions 
3. Notice the second long delay before the window pops up
4. also notice that examining the same item or any others in the inventory again will be instant, like it should be
5. Move the character 1 tile in any direction
6. notice that 'e' examining any item will again take a second to open

For the save file just before the bug initiates:
1. Immediately upon loading the game, open inventory and examine an item.
2. Notice no second long delay 
3. Move character 1 tile left, examine an item in the inventory, no delay
4. Move character 1 tile right, examine an item in the inventory, no delay
5. There is specifically one "heavy battery mod" on the tile directly north-east of the player
6. Examine the tile with the "heavy battery mod" and pick it up
7. open inventory and examine any item, there will be a second long delay to open the examine window
8. closing that examine window and examining other items will now have no delay (like step 4 of the save file with the bug)
9. Move one tile in any direction and you will once again have a one second delay for examining an item.

### Expected behavior

There should be no pause in interacting with your inventory after moving your character.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: eca466b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    No Monsters [Only_Wildlife]
]

**Comment by BrettDong** [comment]
Tried both saves and had no luck reproducing the lag on the latest version today (d573806a578402750cd065bd1ac8864f1c434d04) on macOS. Probably platform dependent (?)
