### ISSUE TITLE
Mitigate skill erosion effects for secondary skills for crafting.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#69650]
### Is your feature request related to a problem? Please describe.

- At current stage of the game, a lot of items with long crafting times exist.
- It is relatively easy to plan how to maintan primary skill level for crafting
- Secondary skill leveling sometimes requires either combat skill or loot that is gained only via combat in reasonable time (eg solder, chem reagents, etc)
- Yet players are crafting usually to make combat bearable after evolution progressing too far for their gear, its a gameplay contraditction

### Solution you would like.

Reduced practical exp gain up to theoretical knowledge level of the secondary skill, helps with maintaining skill which makes sense since you are doing something related, but doesnt serve as a leveling method.

### Describe alternatives you have considered.

Using only theoretical knowledge for secondary skill for crafting

**Comment by ehughsbaird** [comment]
This makes it so that secondary skills in recipes are prevented from rusting:

I'm not sure any sort of outright training would necessarily make sense, but do what you want with this code. It touches about the same places any training would need to touch.
```diff
diff --git a/src/character.cpp b/src/character.cpp
index f6399e973e..81afade5b2 100644
--- a/src/character.cpp
+++ b/src/character.cpp
@@ -2661,6 +2661,17 @@ std::vector<const item *> Character::get_pseudo_items() const
     return pseudo_items;
 }

+void Character::maintain_skill( const skill_id &id )
+{
+    SkillLevel &level = get_skill_level_object( id );
+    // Do not practice if: cannot train or asleep
+    if( !level.can_train() || in_sleep_state() ) {
+        return false;
+    }
+
+    level.practice();
+}
+
 bool Character::practice( const skill_id &id, int amount, int cap, bool suppress_warning )
 {
     SkillLevel &level = get_skill_level_object( id );
diff --git a/src/character.h b/src/character.h
index 4d6066bd9b..8f90b5ee8c 100644
--- a/src/character.h
+++ b/src/character.h
@@ -1191,6 +1191,7 @@ class Character : public Creature, public visitable

         /** This handles giving xp for a skill. Returns true on level-up. */
         bool practice( const skill_id &id, int amount, int cap = 99, bool suppress_warning = false );
+        bool maintain_skill( const skill_id &id );
         /** This handles warning the player that there current activity will not give them xp */
         void handle_skill_warning( const skill_id &id, bool force_warning = false );

diff --git a/src/crafting.cpp b/src/crafting.cpp
index fd025f5ca7..ae4a6d577f 100644
--- a/src/crafting.cpp
+++ b/src/crafting.cpp
@@ -969,6 +969,11 @@ bool Character::craft_skill_gain( const item &craft, const int &num_practice_tic
             }
         }
     }
+
+    for( const std::pair<skill_id, int> &pair : making.required_skills ) {
+        maintain_skill( pair.first );
+    }
+
     return practice( making.skill_used, num_practice_ticks, skill_cap, true );
```

**Comment by freijie** [comment]
Thank you [ehughsbaird](https://github.com/ehughsbaird)
> I'm not sure any sort of outright training would make sense

I understand where it comes from.

My logic is:

If it uses practical knowledge, it should give you some minor practical level exp as well, via reflexon between character's practical and theoretical knowledge and actualy application for crafted item, thus capped by theory, as its a logical limit of what you could possibly gain by reflexion.

If it uses theoretical knowledge, it shouldnt demand practical level in the first place.

**Comment by ehughsbaird** [comment]
> If it uses theoretical knowledge, it shouldnt demand practical level in the first place.
That looks something like this, but I'm not going to read the crafting GUI code, and it's slightly more complicated.

```diff
diff --git a/src/crafting_gui.cpp b/src/crafting_gui.cpp
index 1e1386780c..73e28c4411 100644
--- a/src/crafting_gui.cpp
+++ b/src/crafting_gui.cpp
@@ -210,7 +210,7 @@ struct availability {
             apparently_craftable = ( !r->is_practice() || has_all_skills ) && has_proficiencies &&
                                    simple_req.can_make_with_inventory( inv, all_items_filter, batch_size, craft_flags::start_only );
             for( const auto& [skill, skill_lvl] : r->required_skills ) {
-                if( crafter.get_skill_level( skill ) < skill_lvl ) {
+                if( crafter.get_knowledge_level( skill ) < skill_lvl ) {
                     has_all_skills = false;
                     break;
                 }
```
