### ISSUE TITLE
Items in pocket are hidden in Inventory screen. Bug or Experimental future? 

### ISSUE THREAD

**Issue by LordForce01** [CleverRaven/Cataclysm-DDA#69664]
### Describe the bug

My inventory no longer shows the contents of pockets. The screen only shows what i am wearing and welding. New Red arrow (errors?) point to items with pockets.
![2023-11-22 20_40_25-Cataclysm_ Dark Days Ahead - 7bded00](https://github.com/CleverRaven/Cataclysm-DDA/assets/151807043/ebe747ff-1e00-4aca-a9f2-47410f2ec42a)
When checking pockets nothing is shown for the contents
![2023-11-22 20_49_36-Grammarly Anchor Window](https://github.com/CleverRaven/Cataclysm-DDA/assets/151807043/3ebb705d-28cb-48cc-af50-095bd79acb87)
Advance inventory is not affected
![2023-11-22 20_41_34-Cataclysm_ Dark Days Ahead - 7bded00](https://github.com/CleverRaven/Cataclysm-DDA/assets/151807043/31acd8e3-e743-4d4e-affa-709d82645568)
Multi Drop is effected
![2023-11-22 21_22_45-Cataclysm_ Dark Days Ahead - a647a78](https://github.com/CleverRaven/Cataclysm-DDA/assets/151807043/00e4572d-5a25-4e4e-b3c3-e04e8509bec9)
Interesting note my inventory is still searchable. 
![2023-11-22 20_41_16-Cataclysm_ Dark Days Ahead - 7bded00](https://github.com/CleverRaven/Cataclysm-DDA/assets/151807043/41484b0c-13c6-4beb-8a0b-f461316a7083)

### Attach save file

[Gunn City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13445929/Gunn.City-trimmed.tar.gz)

### Steps to reproduce

My two save files have the issue. New games also have the issue.

### Expected behavior

I expect to see all the items in inventory when opening the inventory screen. 

### Versions and configuration

OS: window 10
Game Version: 2023-11-19-0143
Graphics: Tiles
In game Language English

### Additional context

Logs attached
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13445961/config.zip)

**Comment by andrei8l** [comment]
Press `E`. There's a hint about this in the pick up UI that needs to be added to the general UI as well.

**Comment by LordForce01** [comment]
Much appreciated thank you!
