### ISSUE TITLE
Jawed terror appeared on my boat, I can't attack it, and it can't attack me

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69674]
### Describe the bug

Jawed terror just suddenly appeared on my boat and I was rightfully terrified. I was however happy to note that it was just hangin out watching me steer around. 

In all seriousness, this is a bug that the jawed terror can't attack me, and I can't attack it. I'm not sure if its a Z-level bug? Maybe the jawed terror has some code to stalk and surface at the player whenever it gets a chance, and that bugged out? If it's meant to have an ability to try to crash through the hull, it isn't working. My boat is circular to prevent anything from getting to me while I steer and turn. 

I moved back from my chair in the center of the boat to move away from it, but it moved towards me. Still unable to attack each other even after moving back a tile.

### Attach save file

[Lenora-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13447280/Lenora-trimmed.tar.gz)

### Steps to reproduce

I don't know what caused the jawed terror to appear on my boat. This might be an edge case

### Expected behavior

1. I expect the jawed terror to not even be able to move onto my boat.
2. I expect to be able to at least attack the jawed terror while its on my boat, and for it to attack me.
3. If the Jawed terror bashed on the bottom hull of the boat and got in through a heavily damaged part.

### Screenshots

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/985839ce-cc5c-4a7b-b206-549b2529e544)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: eca466b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    No Fungus [No_Fungus],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
It's a variant of a known issue where critters illegally enter vehicles but remain unable to both attack and be attacked. I'm not aware of it having been claimed to be solved, however (and the previous reports have probably been killed off by the stale-bot by now).

**Comment by CoroNaut** [comment]
Another occurance
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/00cc0ea5-9547-4f12-9168-1dae197ad5e6)
