### ISSUE TITLE
When NPC activates C4, it asks me for how long

### ISSUE THREAD

**Issue by MichaelMacha** [CleverRaven/Cataclysm-DDA#69677]
### Describe the bug

I was creeping up on a bunch of hostile survivors in an evac shelter, and one of them decided to activate a C4. _I_ was then prompted for how long it should be set for.

Naturally I entered "one second" and took out a bunch of them, but the victory kind of rings like false coin... I think that mechanism, wherever it is in the code, needs to consider what the long-term goal of the NPC is and isolate the player from the critical decision of _how long to set the timer for_. This is unfortunately probably beyond my own familiarity, or I'd fix it myself. It feels very C Plus Plusy.

### Attach save file

N/A (couldn't reproduce at this point)

### Steps to reproduce

1. Give a hostile NPC a C4 and a reason to use it
2. Wait for them to activate it
3. Note that the player is crowd-sourced for how long the timer should be set for

### Expected behavior

I would expect, ideally, the AI to determine how long the timer should be set for and make a decision based on that; but if that isn't possible, then it might be nice to have the C4 flagged as an item that NPCs don't use, as that's still more rational than what happened.

### Versions and configuration

- OS: KUbuntu 22.04
- Game Version: 0997bfc (some time ago)
- Graphics Version: Tiles
- Ingame Language: English

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/d573806a578402750cd065bd1ac8864f1c434d04/src/iuse.cpp#L3628

Yeah, the rest of the function looks OK but this one is definitely off. It always asks the player.

**Comment by Inglonias** [comment]
I feel like we should fix this by saying "NPCs can't use C4" because do you trust them with the stuff? I sure as hell don't. And I wouldn't trust them to set the timer properly either.

**Comment by RenechCDDA** [comment]
No, that's wrong. NPCs can activate and use all the other explosives there's no reason they should be disposed from using this one.

They already have AI routines which tell them "If thing is about to explode, THROW IT DUMMY".

**Comment by Inglonias** [comment]
The issue here is that the obvious solution of "let the NPC set the timer" leads to the question of "okay, what's the timer going to be?" How do we tell the player what that answer is? What if they disagree? Do we make this settable in combat commands? Do we make a default timer for all such explosives that all NPCs use? Should that timer be the same for the mininuke as it is for C-4?

**Comment by Inglonias** [comment]
I apologize. I failed to consider hostile NPCs and didn't read the issue correctly. I thought this was about allies.

**Comment by MichaelMacha** [comment]
It likely applies to allies as well, that just changes the circumstances a bit.
