### ISSUE TITLE
Hauling is interrupted when walking over "young tree"

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69684]
### Describe the bug

Hauling is stopped when walking over a "young tree"

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. haul some item
2. Walk over "young tree"
3. Hauling is stopped

### Expected behavior

Hauling shouldn't be stopped.

I noticed that hauling works when climbing over fences, which is very very nice. This scenario is similar, except you don't climb over a fence tile that can't contain items, its a young tree tile that can't contain items.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/90f8eceb-04a8-4284-b8df-00002f7b356f)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5c2611d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by actually-a-cat** [comment]
It's actually a bug/accident that hauling works over fences this way (it might be worth turning that into a feature, but that's beside the point right). It's expected that hauling will stop when stepping on a tile that can't contain items, since hauling always works by picking up items from your previous tile and dropping them on your current tile.

**Comment by CoroNaut** [comment]
Perhaps the player could be given a prompt to move onto a tile that can't hold items then. Also, while auto-traveling, it could automatically path around such obstacles while hauling items. That's how I found out in the first place that young trees stopped you from hauling items. The auto-pathing moved me ontop of the tree while hauling items and I lost all of them in the forest for a little bit.
