### ISSUE TITLE
items somewhat distant from the basecamp are not consumed on its missions

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#69687]
### Describe the bug

if you have left some consumable itens on a storage zone somewhat distant from the basecamp, it may be related to the field of vision, then they wont be consumed when you ask for some of the available basecamp missions. That brings some problem as eventually you may want to use large vehicles, that consume some fuel/energy and occupy large space to transport items and transporting by hand takes considerable time and also due to the production machinery that are not always close

### Attach save file

[normal-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13453160/normal-trimmed.tar.gz)

### Steps to reproduce

1. use the debug menu to produce enough food for the missions and distribute it, close to the bulletin board;
2. then examine it to open the basecamp menu to ask one of the NPCs to do one of the available constructions;
3. then when you check that basecamp construction menu again some distant itens such as nails and planks appear available with the same quantities and they also remain equaly available after the construction, as if nothing happened

### Expected behavior

the itens should be consumed at the time you ask for some basecamp construction and not appear with the same amount available for further basecamp missions

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.13; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: Português (Brasil) [pt_BR]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Vaskritaya** [comment]
probably a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/68919

**Comment by PatrikLundell** [comment]
Yes, it's most likely the same old issue. Distance doesn't seem to be the main factor either.
