### ISSUE TITLE
Talking to NPC's crashes the game

### ISSUE THREAD

**Issue by tommykoning** [CleverRaven/Cataclysm-DDA#69705]
### Describe the bug

when ever i talk to npc the game freezes and automatically closes itself

### Attach save file

[crash test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13460737/crash.test-trimmed.tar.gz)

### Steps to reproduce

walk into a npc and when the game ask you what to do select talk

### Expected behavior

the conversation menu pops up so we can chat, trade, get missions or requite them 

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 23.1.0; Codename: Vulcan; 
- Game Version: 8fc8b57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
I'm not able to reproduce the crash on windows.

Did it not generate a crash.log or other error message? Your save archive doesn't include any crash log. Please describe the crash if you can.

**Comment by tommykoning** [comment]
no it just freezes up and closes the window a few seconds i had to re-install my operating system today and now its acting up this way could that have anything to do with it ?

**Comment by tommykoning** [comment]
nvm i just tried installing cdda manually instead of through catapult and it works perfectly im sorry for the inconvenience if i find a fix i will probably post it in their issues
