### ISSUE TITLE
Extreme morale penalty from performing Old Guard mission

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#69719]
### Describe the bug

I performed the last (?) Old Guard mission of exterminating a bandit lair. As a "reward" my character has been hit with a rather extreme morale penalty of around 390 for killing "innocent" person.
At the time of this report, my character is down to a penalty of 300 after three quarters of a day or so.

### Attach save file

N/A. The save is likely going to be too large, and the issue should be reproducible.

### Steps to reproduce

1. Get the Old Guard mission of eliminating a Hell's Raiders boss.
2. Wait until there is no or little moon (or just hope for the frequent fog) and go to the camp at night.
3. Use night vision to attack the bandits one at a time from the edge of your vision (out of theirs). I used a bow and also thermal vision to be able to find the buggers.
4. Repeat until they're all dead.
5. Find that your character is extremely tired and depressed.
6. Check the character morale tab and see that you've been hit by a massive morale penalty. It might vary depending on whether the number of enemies is static or not (and depending on how long you take to exterminate them).

### Expected behavior

Attacking humans that are displayed as "Hostile" should result in the same capped penalty regardless of whether you attack them first or you're doing the stupid thing of hoping their 100% accurate snap shots won't kill you.
By capped I mean the penalties should be served concurrently, or at least build up to a reasonable limit.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/91dba4c3-7d93-4bc9-8be6-a009c5396c28)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 0.G-5416-g8fc8b57d81 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
+ Hack to disable portal storms
+ Bare bones basecamp personal recipes.

### Additional context

I've been hit with a penalty of 100 or so from the first Old Guard bandit extermination mission, despite being fired on first (open door, see nothing, bang), and it made my character useless for about a day.

In contrast, I didn't notice anything from Smoke's bandit extermination mission. A potential difference is that I first approached those bandits during the day time, and as soon as a bandit became visible (in the damnable fog), my character had an arterial chest wound (bypassing armor) from a snap shot at essentially maximum range. Returned after recovery and eliminated them during the night. Another difference is that those bandits were attacked based on thermal indications rather than night vision ones, which means I (and presumably the character) didn't actually see the hits, but only the thermal representation winking out eventually. I don't think there should be any difference in penalty depending on how you kill them (the game probably isn't able to distinguish a deliberate luring of monsters onto them, but it should be able to detect that trap's you've set up did them in).

**Comment by fairyarmadillo** [comment]
IMO the fix here is to create a hidden "guilty" trait and slap it on all NPCs who are hostile on sight, then put a check for the guilty trait flag in the C++ where this penalty is applied. We do want some more granular bandit interactions, but until we get them, I don't think it's fair to dump a gigantic and long lasting morale hit on people, especially in this situation. It's normal for a duly appointed lawman to feel conflicted about taking down a bad guy, but it's not the same thing as shooting Dino Dave for no reason.

**Comment by PatrikLundell** [comment]
Sounds like a reasonable intermediate solution. I would suggest the "guilty" take down guilt ought to be handled in a similar manner as zombie child killing, i.e. a flat penalty for a fixed duration (which gets adjusted to last from the last killing in case more than one enemy is taken out (note that I'm guessing about how zombie child guilt works based on experience, not any code diving)). Each mission would then carry a reasonable guilt cost.

**Comment by fairyarmadillo** [comment]
I don't think guilty people should apply any real penalty. We don't assess one if you kill in self-defense, and there's no functional difference in the game unless you purposefully let them shoot at you.

That could be revisited when we have better systems, but we don't.
