### ISSUE TITLE
The whitelist in pockets are ignored when using the 'i' insert command

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69717]
### Describe the bug

If a pocket on a container has a white list, it is ignored when using the 'i' insert command in the examine window of the container.

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Get a leg ammo pouch
2. Set the pocket settings for both pockets of the leg ammo pouch to only accept "px4 9x19mm 20-round magazine"
3. Get M9 20-round magazine.
4. Insert M9 20-round magazine into the leg ammo pouch
5. The pouch now contains the M9 20-round magazine illegally.

### Expected behavior

- The insertion of items into pockets should respect the whitelist and blacklist automatically. The stash window could say something like "Item is in blacklist or not in whitelist"

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/2c388572-e3ec-4b3e-b911-141fa412ca04)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/1b5eb47d-a521-404d-b5c1-cec4067d0071)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    No Monsters [Only_Wildlife]
]

**Comment by mqrause** [comment]
Bypassing pocket settings by manual insertion is an intended feature. It's assumed you do that because you want to do it.

**Comment by CoroNaut** [comment]
If you have 2 M9 20-round magazines and they go into a pocket that you don't want them in, there is no way to remove just that item from just that pocket. If The magazine where completely disallowed from going into the pocket that you never wanted it in, there would be no problem. 

I suppose another solution would be another option inside the pocket settings like "toggle obey whitelist/blacklist for manual insertion". Another feature that would mitigate this would probably be the ability to remove items from specific pockets. There is currently no way at all to remove a single item from a pocket if there are multiple of that item in the container. There is no way to remove just the M9 20-round magazine in just pocket 1. The inventory menu displays it as "2 M9 20-round magazines", despite them being in different pockets. That itself is fine, but I can't be precise about exactly which one of those I want removed.

**Comment by andrei8l** [comment]
You can (re)move items from specific pockets with the pocket organize menu (default key `i` in the inventory UI). See https://github.com/CleverRaven/Cataclysm-DDA/pull/58116

**Comment by CoroNaut** [comment]
Oh, I didn't realize that the entire inventory was also considered a container like that. Thanks for that info, I'll close this then. I would prefer a toggle able setting for manual insertion, might make a feature request for that at some point.
