### ISSUE TITLE
Being near fire hurts NPCs and players but not monsters

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#69720]
### Is your feature request related to a problem? Please describe.

Monsters are immune to heat damage caused by standing in a high temperature area that isn't on fire. You can set them on fire easily enough, but temperatures don't affect them.

### Solution you would like.

It would be a lot cooler if temperature did affect them. Or hotter, I guess.

### Additional context

Save file for convenient reproducing of the issue. There's a feral mechanic standing nearby that is immune to the heat that is killing me.
[Apollo-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13462156/Apollo-trimmed.tar.gz)

**Comment by PatrikLundell** [comment]
Would get rid of the pesky wasps that chill out in burning wasp nests, which would be both nice and the expected result.
