### ISSUE TITLE
Crash after dying and restarting too many times

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#69726]
### Describe the bug

My game is crashing after I make more than two or three attempts on this world. Not sure what's happening here.

### Attach save file

This is the world I'm using. Non-standard mods are attached.
[Megalopolis.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13462625/Megalopolis.tar.gz)
[mods.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13462627/mods.tar.gz)

### Steps to reproduce

Make a few worlds, abandon a few characters, repeat until crash occurs. It's unclear what exactly is happening. I suspect my computer is running out of RAM, but can't prove anything

### Expected behavior

Not crashing.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 480d205 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Inglonias Scenarios and Professions [Inglonias_Scenarios]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13462632/crash.log)

**Comment by Inglonias** [comment]
In case this is hardware-related, I'm running on [this laptop](https://www.walmart.com/ip/Acer-Aspire-5-A515-54G-5928-Intel-Core-i5-8265U-1-6-GHz-Win-10-Home-64-bit-GF-MX250-8-GB-RAM-512-SSD-15-6-IPS-1920-x-1080-Full-HD-Wi-Fi-charcoal-blac/796988645)

**Comment by Inglonias** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13462636/crash.log)
It happened again. Uploading log in case it's different

**Comment by BrettDong** [comment]
Your crash log looks very similar to the one in #68500.

**Comment by Inglonias** [comment]
Closed as duplicate
