### ISSUE TITLE
Washing machine accepts infinite soap and doesn't accept water

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69723]
### Describe the bug

Washing machine appliance takes infinite soap and doesn't seem to want to take water. I have a jerrycan full of 80 units of water but it says "You don't have the necessary item at hand" when trying to interact with the washing machine

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Get washing machine, put it down, hook it up to power
2. It takes infinite soap
3. It doesn't take water
4. Can't wash clothes with washing machine

### Expected behavior

It should probably take a reasonable amount of soap instead of an infinite amount, and take water.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/e660c20c-cbe1-422b-bbec-d08bf7ab5266)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
The intended usage seems to be to fill the tank with water and detergent is demanded when you activate the washing machine (it doesn't seem to accept anything but detergent which it used to do).

It's obviously a problem that it accepts anything but water or clean water in the tank. When filling it with water it has a limit to how much it can accept. To make it worse, it used to be that washing machines used magic plumbing to draw water from e.g. a well, so a returning player wouldn't expect to have to add water explicitly (and no, it doesn't work even when placed adjacent to a water tank).
