### ISSUE TITLE
Ferals can't be bled

### ISSUE THREAD

**Issue by SteelSirokos** [CleverRaven/Cataclysm-DDA#69748]
### Describe the bug

Ferals, Hospital Patients, and possibly other creatures with human blood cannot be bled once killed.

### Attach save file

N/A

### Steps to reproduce

1. Kill a feral human/mechanic/etc
2. Open Butcher menu
3. Bleed option is greyed out

### Expected behavior

I expected to be able to bleed ferals.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2715 (23H2)
- Game Version: 66d6c8a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Secronom [secronom],
    Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Pixel's Various Fuckery [Pix's Shit],
    World on Fire [World_on_fire],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Dorf Life [Dorf_Life],
    Tankmod: Revived [Tankmod_Revived],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    MST Extra [MST_Extra],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by MNG-cataclysm** [comment]
Who's been maintaining Miscellaneous Magiclysm Expansions? I thought that it had been abandoned.

**Comment by SteelSirokos** [comment]
> Who's been maintaining Miscellaneous Magiclysm Expansions? I thought that it had been abandoned.

Kenan

**Comment by Maleclypse** [comment]
OK I've tested this with all the in repo mods you have up there all running at once and I'm able to bleed the dead ferals and pour it into a container.  
Unfortunately this means that it's going to be an out of repo mod causing this issue.  If you can search your mod files  that will be the easiest way to find which mod it is and if you can't you'll want to remove all the non repo mods and readd them one at a time until you can't bleed ferals anymore and that will be the mod causing it.  I'll be closing this issue in a few days in case anyone knows what mod is causing that and is able to tell you here.

**Comment by SteelSirokos** [comment]
The problematic mod was World on Fire; I've let Kenan know about the issue. Marking as closed.
