### ISSUE TITLE
The bathroom in the back bay is not cleaned.

### ISSUE THREAD

**Issue by Rabadash94** [CleverRaven/Cataclysm-DDA#69743]
### Describe the bug

After eliminating all the zombies in the back bay and completing the quest "Find someone to clean the back bay", I notice that the bay is cleaned, but not the adjacent bathrooms, as some zombies had entered where they were eliminated. 

### Attach save file

N/A

### Steps to reproduce

1. Complete the mission to eliminate the zombies in the back bay, trying to kill some in the bathrooms.
2. Accept and complete the "Find someone to clean up the back bay" quest.
3. Notice that the bay is clean, but not the bathroom.

### Expected behavior

Any room adjacent to the bay should be as clean as the bay itself.

### Screenshots

![Captura de pantalla de 2023-11-25 10-10-39](https://github.com/CleverRaven/Cataclysm-DDA/assets/144259924/93001b24-f00f-4dc2-9b3d-b5003cde195f)
![Captura de pantalla de 2023-11-25 10-10-50](https://github.com/CleverRaven/Cataclysm-DDA/assets/144259924/a028245c-bc9a-4c32-96a7-3ff5ae8bb4fc)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 8e02002 [64-bit]
- Graphics Version: Tiles
- Game Language: Español (Argentina) (73,2%) [es_AR]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar Necesidades de PNJ [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Profesiones Biónicas [package_bionic_professions],
    Xedra Evolucionado [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Railroads [railroads],
    ve al jugador, correr, agacharse, sangrando, retrodays [sees_player_retro],
    Armas Genéricas [generic_guns],
    Características por Habilidades [StatsThroughSkills],
    Características por Muertes [stats_through_kills],
    Destreza Veloz [speedydex]
]

**Comment by Qrox** [comment]
Makes sense because people don't bath or poop in CDDA, so why bother?
