### ISSUE TITLE
Visual cache is not invalidated when peek between z-levels

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#69742]
### Describe the bug

as title says

### Attach save file

[Cool Guy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13464469/Cool.Guy-trimmed.tar.gz)

### Steps to reproduce

Open the save (and ignore all popup errors)
Peek up using `x` `>`
see the map is as bright as it was in the daylight

Alternatively you can teleport to some location and try to do the same, you won't be able to do the same

### Expected behavior

i can peek up and down properly

### Screenshots

It is dark around me
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/cb8a41ff-ec7d-4f7d-9069-99cc19e4dbc9)
but when i am peeking, i can see everything as in daylight (and for some reason i can see internals of the house? wtf?)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/6f4d6b50-4dc5-40e3-9ed2-25416bc53931)
Trying to peek another floor above shows this
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/8bea47f2-7b96-4267-8fa1-c977990ce6a8)

UPD: after acutally walking on another z-level, the game now says i can't peek here because there is a roof, so i suppose some checkes uses invalid information?
### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 0.G-5454-gb04b16832d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/4eb9a6b7-06ef-40e4-92ae-90b2d230eec0)

**Comment by Ramza13** [comment]
Just took a look at this and didn't see what you are talking about.  Has this been fixed or I missing a step?

**Comment by GuardianDll** [comment]
nope, still here, in 2dea0a7 
Spawned in evac shelter, broke the door to the roof, standed on the ladder, and peeked up:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/13c5a6ab-a67e-4ead-b914-ee9819528cdf)

Teleported to closest gun store, moved to the stairs, peeked up again:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/b7709d83-9e03-4cb3-b088-a72f220dfaba)
