### ISSUE TITLE
Apartments in apartment complexes with peepholes are not locked, and the doors without them are.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#69747]
### Describe the bug

When looting an apartment complex, doors that have peepholes are not locked, and doors without them are.

While it makes sense for there to be the occasional unlocked apartment, this seems like an arbitrary way to decide it, especially since those doors are marked as locked

### Attach save file

Trivial to reproduce, but here's a save anyway.
[Megalopolis2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13465027/Megalopolis2-trimmed.tar.gz)

### Steps to reproduce

1. Do a Large Building start in an Apartment Complex.
2. Go exploring.
3. You'll find locked doors that have peepholes can be opened from the hallway and doors without them cannot.

### Expected behavior

All locked doors should behave the same way.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: bafd5a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Inglonias Scenarios and Professions [Inglonias_Scenarios]
]

### Additional context

Doors without peepholes that are locked can't be unlocked from either side - Given what I know about how we treat locked doors, that's expected behavior, since we can't specify which side of the door the lock exists on for unlocking except in special cases (one side is "outside" and the other is "inside", for example)

**Comment by GuardianDll** [comment]
it is because we don't have locked doors with peephole

**Comment by Inglonias** [comment]
So, it turns out we DO have locked doors with peepholes, but they're not designed for use inside of buildings. Because both sides of the door are indoors, either side can unlock it.
