### ISSUE TITLE
[Innawoods] Craftable Sunglasses

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#69740]
### Is your feature request related to a problem? Please describe.

Tinted Glass lenses are craftable in Innawoods, yet are really only used for the Welding Goggles, meaning the only items with SUN_GLASSES flag are the Snow Goggles, which have 9 encumb, or various hats and caps

### Solution you would like.

basic sunglasses should be able to be made using a set of tinted glass lenses and wire, providing a upgrade to the snow goggles

**Comment by Light-Wave** [comment]
A fair idea, although I think such a recipe could be put in mainline instead of being kept in Innawood.
