### ISSUE TITLE
Ternaries in spell costs work the opposite of the way the game shows that they should

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#69751]
### Describe the bug

#69464 switched Karma Arms and a couple other spells to using a ternary to determine spell cost and casting time, so that turning them on takes time and mana and turning them off is free. This is reflected in the UI, which shows that Karma Arms costs 200 mana to cast and 0 mana to remove.

However, in-game the opposite happens--Karma Arms is free to cast and costs 200 mana to remove.  Casting time works properly.

### Attach save file

[Ohio City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13464751/Ohio.City-trimmed.tar.gz)

### Steps to reproduce

1) Cast Karma Arms to grant the effect
2) Note mana has not gone down.
3) Cast it again to remove the effect
4) Note mana has gone down.

### Expected behavior

Spell casting costs work the way the spellcasting screen says they should.

### Screenshots

<details>
  <summary>Screenshots</summary>
Turning on Karma Arms:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/02dfb9a1-ab00-42dc-b137-940f73eaae7b)

Status screen afterwards (note Mana)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/1e500e42-bada-47e0-a6f8-20ada232c3eb)

Turning off Karma Arms:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/75926dc9-bb65-45f6-a564-f177d0b116ff)

Status screen afterwards (note Mana)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/2d8403c3-6560-4ce7-923d-3bfee9dae21c)

</details>

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 7560c55 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Xedra Evolved [xedra_evolved]
]

### Additional context

The linked PR has the same formula for both cost and time, and time works properly, so there might be something odd in the spell cost code specifically.

I also tested Stalker's Oculars and Devil's Tail and the same bug occurs (and also occurs when I tested it with a Mind Over Matter power).

**Comment by GuardianDll** [comment]
That is odd
To the oddities: you can see that to make casting time 20 seconds, was used not usual `2000` moves, but `200000` - for some reason the game interpret 1 second as `10000`

**Comment by Standing-Storm** [comment]
Is the casting time supposed to be 20 seconds? The listed casting time in the screenshot is accurate (it takes over 30 minutes to cast)

**Comment by GuardianDll** [comment]
oh no, i forgot that i used debug mana that increases time to cast for 50 times;
nevermind then, it's just my memory

**Comment by andrei8l** [comment]
Spell cost is evaluated after casting the spell

https://github.com/CleverRaven/Cataclysm-DDA/blob/bdaa430d8e1edfce364fd600fb24c4c19f30c852/src/activity_handlers.cpp#L3778-L3783

<details>
<summary>This should fix it</summary>

```diff
diff --git a/src/activity_handlers.cpp b/src/activity_handlers.cpp
index d6b19b2ad4..6869b50647 100644
--- a/src/activity_handlers.cpp
+++ b/src/activity_handlers.cpp
@@ -3775,11 +3775,12 @@ void activity_handlers::spellcasting_finish( player_activity *act, Character *yo
             // spells with the components in hand.
             spell_being_cast.use_components( *you );
 
+            int cost = spell_being_cast.energy_cost( *you );
+
             spell_being_cast.cast_all_effects( *you, *target );
 
             if( act->get_value( 2 ) != 0 ) {
                 // pay the cost
-                int cost = spell_being_cast.energy_cost( *you );
                 switch( spell_being_cast.energy_source() ) {
                     case magic_energy_type::mana:
                         you->magic->mod_mana( *you, -cost );
```

</details>
