### ISSUE TITLE
`PREVENT_DEATH` EOC types do not function properly, character still dies.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#69750]
### Describe the bug

EOC's that have the type `PREVENT_DEATH` set don't properly work, as they don't prevent a character dying. They still run on death and do what their effects are listed as, but the character will still die and end the game. This makes it very difficult to work with death prevention things.

### Attach save file

N/A, this happens across all saves.

### Steps to reproduce

1. Write a prevent death EOC for whatever purpose you want. An easy way to test this is with the old portal reward EOC for stopping it, just without any requirements:
`{
    "id": "EOC_PREVENT_DEATH",
    "type": "effect_on_condition",
    "eoc_type": "PREVENT_DEATH",
    "effect": [
      { "u_set_hp": 50, "only_increase": true, "main_only": true },
      { "u_set_hp": 0, "max": true, "minor_only": true },
      { "u_add_effect": "incorporeal", "duration": [ "5 minutes", "10 minutes" ] },
      { "u_lose_effect": "jetinjector" },
      { "u_lose_effect": "effect_adrenaline" },
      { "u_lose_effect": "effect_drunk" },
      { "u_lose_effect": "datura" },
      { "u_lose_effect": "hypovolemia" },
      { "u_lose_effect": "redcells_anemia" },
      { "arithmetic": [ { "u_val": "stored_kcal" }, "=", { "u_val": "stored_kcal" } ], "min": 5000 },
      { "arithmetic": [ { "u_val": "pkill" }, "=", { "u_val": "pkill" } ], "max": 200 },
      { "arithmetic": [ { "u_val": "stim" }, "=", { "u_val": "stim" } ], "max": 200, "min": -100 },
      { "arithmetic": [ { "u_val": "pain" }, "=", { "const": 0 } ] },
      { "arithmetic": [ { "u_val": "thirst" }, "=", { "const": 0 } ] },
      { "arithmetic": [ { "u_val": "fatigue" }, "=", { "const": 0 } ] },
      { "arithmetic": [ { "u_val": "sleep_deprivation" }, "=", { "const": 0 } ] },
      {
        "u_message": "I'd rather not die, I'm still testing stuff.",
        "popup": true
      }
    ]
  }`
2. Go someplace dangerous and let your character die.
3. Observe the popup message, but still watch as your character dies and not be stopped from doing so.

### Expected behavior

I would expect that I can prevent character death with this style of EOC.

### Versions and configuration

- OS: Windows 11
- Game Version: 2023-11-21-0613 (64-bit)
- Graphics Version: Tiles
- Ingame Language: English
- Mods Loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, defense_mode
I was testing some stuff for developing Defense Mode when I found this out.

### Additional context

None at this moment.

**Comment by GuardianDll** [comment]
see #68246

**Comment by MNG-cataclysm** [comment]
> see #68246

That fixed it. I guess they do work, but just very strangely.
