### ISSUE TITLE
Shelves exploded after transporting save to experimental 2023-11-26-0605

### ISSUE THREAD

**Issue by Riooof** [CleverRaven/Cataclysm-DDA#69778]
### Describe the bug

After updating the game I noticed some items changed from item(number) type into X items type
For example salt, sugar etc.
So here comes the problem my warehouse shelf can hold 3.5kL of items but now can only hold 4096 salt which is like 40L or something,I doubt it is a bug

### Attach save file

not needed

### Steps to reproduce

1, get 5k salt
2, build a warehouse shelf
3,put salt in it
4, try to put something else inside  

### Expected behavior

the furniture can only store 2^12 salt, anything else will be dropped on the floor, this makes its huge room meaningless

### Versions and configuration

Gamever: experimental 2023-11-26-0605
Sys:android

**Comment by Qrox** [comment]
Caused by #60885.

**Comment by RenechCDDA** [comment]
I recommend you store your salt in containers. The item limit per-tile is not a bug, nor is the removal of charges.

**Comment by Qrox** [comment]
Why close so fast? Bug or not this needs to be addressed to not break immersion.

**Comment by Qrox** [comment]
Based on the OP's description I think the issue is not about existing salt overflowing the tile but rather not being able to put more than 4096 salt into a tile.
