### ISSUE TITLE
Wider crafting window

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#69770]
### Is your feature request related to a problem? Please describe.

Crafting window is too narrow. It does not show all categories and names are cut off even if there is a lot of space available.
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/26722636/7b2f9ab8-f906-42e9-8a34-c6a3ff75167e)

### Solution you would like.

Crafting window width should increase with the resolution.

### Additional context

My terminal size is 430x90 because my resolution is 3440x1440

**Comment by CoroNaut** [comment]
Your crafting menu is definitely too small for your terminal size. Alongside fixing this, it would be very nice to have the option "Full screen crafting menu" next to "Full screen advanced inventory manager" which is in "Sidebar Interface Options".

My terminal width is 200, height 75. My crafting window looks like this:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/7413ec9a-b14f-4470-910d-1dc6f8e266ea)

**Comment by RDru** [comment]
Forgot to add terminal size info. Fixed that.
