### ISSUE TITLE
Pockets can't select containers with items inside for whitelisting/blacklisting in pocket settings

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69787]
### Describe the bug

If a container has any items inside, it becomes ineligible to be selected for whitelisting in pocket settings.

### Attach save file

[testingarea-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13468867/testingarea-trimmed.tar.gz)

### Steps to reproduce

1. Open save, the steel bottle in your inventory should be empty
2. Try to add the steel bottle to the whitelist in one of the pockets of the survivor distributed rigging
3. You can see that it is listed as an item that can be whitelisted
4. Clear the entries on the survivor distributed rigging
5. Put the matchbook inside the steel bottle
6. Try to add the steel bottle to the whitelist in one of the pockets of the survivor distributed rigging
7. It isn't listed

### Expected behavior

Containers should remain eligible to be whitelisted/blacklisted even if they have something inside them. I shouldn't have to empty the container just to make it eligible.

### Screenshots

Picture 1: The steel bottle has nothing inside
Picture 2: The steel bottle has matchbox
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/edb2819e-c0fb-429a-a290-1d160a0e77df)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/17d5de09-d437-4d61-b5f3-a22392dcef55)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Monsters [Only_Wildlife]
]

**Comment by Willzadl** [comment]
Confirmed on a fresh save

**Comment by CoroNaut** [comment]
Pockets also can't select artifacts to be whitelisted or blacklisted.
