### ISSUE TITLE
[MOM] Ignoring the refreshed message on Wakeful Rest and continuing to meditate causes player to get stuck on pop up window.

### ISSUE THREAD

**Issue by MoonlightKitty26** [CleverRaven/Cataclysm-DDA#69780]
### Describe the bug

If the player is tired, continuing to use Wakeful Rest after the prompt window and ignoring the refreshed message causes you to get stuck with no way to close the pop up. The only way is to close the game externally.

### Attach save file

[Sun Valley - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13468197/Sun.Valley.-.Copy.zip)

### Steps to reproduce

1. Use Wakeful Rest power.
2. When the prompt asking to stop meditating pops up, choose "ignore and continue X".
3. The "You are fully refreshed, and can end your meditations now" window will pop up with no way to close it.

### Expected behavior

I thought the window would close with any button and I could meditate as long as I wanted to and interrupt it when I wanted to.

### Screenshots

![Screenshot (102)](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/3b1fc2db-10d5-4299-b799-c90b2088e6c0)
![Screenshot (103)](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/6aaf7b8e-e171-45a7-9f43-523f3ac4d3e8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: dfb8658 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No Bionic Slots [no_cbm_slots],
    Mind Over Matter [mindovermatter],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extended Freeform [Extended_freeform]
]

**Comment by Standing-Storm** [comment]
I suspect this is related to ##68875
