### ISSUE TITLE
Subway pathing is too close to water and reveals underwater lake

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69789]
### Describe the bug

The lab subway at level -4 is too close to the nearby lake and reveals the underwater of the lake

### Attach save file

[Lenora-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13470227/Lenora-trimmed.tar.gz)

### Steps to reproduce

Mapgen produced it

### Expected behavior

Mapgen doesn't produce it

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/4d497926-8876-45f3-ba85-44b03a1a9ed8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/49ed8e9d-4bf3-44b9-b8ce-a469a683491c)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/e3223ec3-ecb8-4b54-a701-dcc5ed1a72f6)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
I've encountered that in the past. I also have a recent case of a lab cut open in several places by diagonal subway lines.

**Comment by Procyonae** [comment]
#68496 will fix this, the lab issue is separate and only affects old labs, I found where to fix it back along, I think it was interpreting the z-4 lab_subway as part of the lab so not adding walls but I don't think I got round to making a PR

**Comment by Procyonae** [comment]
Ideally I want to make lakes not just cubes at some point too but that's not high on my list rn

**Comment by CoroNaut** [comment]
Probably fixed with the attached merge
