### ISSUE TITLE
Allow heavy rain to soak through clothing and slowly destroy medicinal supplies or damage electronics

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69782]
### Is your feature request related to a problem? Please describe.

I noticed that if I try to swim in deep water, it, it will dissolve medicines like aspirin, codeine, and hemostatic powder and destroy some electronics like "shooters ear plugs" or "advanced AR glasses." I was thinking that heavy rain can also soak through clothing to slowly dissolve medicine and could probably damage electronics. This would have survivors on the lookout and using umbrellas or staying indoors during rain.

### Solution you would like.

The rate at which medicine dissolves and electronics are damaged should be determined by the clothing's environmental and water protection, coverage, and probably breathability. I'm assuming higher breathability would let in more rain.

Of course, if their medicines were in a waterproof container, then there would be no worries. Electronics would have multiple damage levels, like normal tools or clothing. A waterproof mod for electronics would be incredibly nice to see as well.

### Describe alternatives you have considered.

Just being carefree about leaving all my medicine and electronics out in the rain in a pile. I'm sure glad I can have them freshly washed every rainfall!

**Comment by inverimus** [comment]
This sounds distinctly unfun. I believe this was one of the reasons for removing acid rain a long time ago, it just wasn't fun.

**Comment by CoroNaut** [comment]
The idea that early game characters would have a hard time with rain in the apocalypse? I could see even mid-game characters solving this issue completely. It's not like everything you wear is electronic, and waterproof containers are abundant.

**Comment by Spicyshadow** [comment]
Rains don´t happen that often in cataclysm for this to add much. You can go entire seasons without seeing much rain except one or two drizzels.

**Comment by fairyarmadillo** [comment]
Many electronics are effectively rainproof. I've never had my phone get damaged by rain.

Being soggy should matter more than it does, but I can't recall rain ever destroying anything that was in my pocket.

**Comment by CoroNaut** [comment]
I can list a few ways that this is a non-issue to begin with:

1. Backpacks are easily able to deflect light and regular rain, and we can probably assume military bags and pouches are even better. So anything but heavy rain really wouldn't do much. This is just real life. like [fairyarmadillo](https://github.com/fairyarmadillo) said, its really not likely rain would damage electronics in pockets anyways, much less a proper backpack.
2. Waterproof containers are abundant and can contain hundreds of medicinal supplies, aspirin, codeine, tramadol, antifungals, alcohol wipes, hemostatic powder, etc. I don't think the average survivor would be going through more than 30, much less 50 of each of these, and most a quite sizable amount of small waterproof containers can hold 200-500 total.
3. Heavy rain is actually pretty rare when you think about it. Not only heavy rain, but even the chance you _aren't_ under a roof, or in a vehicle, or underground makes it even less likely to affect you.
4. The progression of the player getting damp, soaked, wet is already decently slow already, anything other than heavy rain or thunder/lightning storm doesn't really affect the player to begin with unless they really aren't wearing much.
5. Rain doesn't do anything to the player I'm pretty sure. It does reduce morale by maybe a few points (barely anything) and doesn't even slow your movements or weigh you down at all. The warmth you lose from being wet is also pretty negligible.

[cataclysmsurvivalist](https://github.com/cataclysmsurvivalist), I really don't think its "contrived". This would be something to think about if you see the message "A little bit of your medicine gets wet and dissolves" every 10-15 minutes while in heavy rain. Also if you see "Your advanced AR glasses shock you a little". Anyone with a backpack or adequate clothing would rarely see these messages to begin with.
