### ISSUE TITLE
Make every vehicle tile able to store item

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#69807]
### Is your feature request related to a problem? Please describe.

Currently, many vehicle tiles cannot store item. If I am in a vehicle and I droped something onto the floor it will go out side of vehicle. This is rediculous.

### Solution you would like.

1. Every vehicle tile can store item, just like ordinary non vehicle tiles.
2. Their capacity depend on natures of current tile such as height.
3. Installed components occupy spaces.
5. New mechanism: for all tiles (both vehicle and non-vehicle), move cost increase by how much is that tile filled by items. If its fully filled, it is not passable.
6. New mechanism: if a tile is filled by lots of items, creatures can push them away.
7. New mechanism: tring to place an item into somewhere fully filled make it roll to somewhere nereby.

**Comment by CoroNaut** [comment]
5. I couldn't imagine the lag generated by tons of enemies continuously pushing tons of items around. 
6. Placing items into a full pile and having it roll over already exists in a few scenarios. Other more precise methods of moving items don't allow you to overfill the tile.

**Comment by pedestrian4** [comment]
This idea is being realized at #70184.

**Comment by martinrhan** [comment]
> This idea is being realized at #70184.

That is not exactly what I want. There are still many vehicle parts such as asile, on which when you drop something it just penetrate and get onto the ground.
