### ISSUE TITLE
Completely broken (XX) stylish bifocal glasses still provides full correction for farsightedness and nearsightedness

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69820]
### Describe the bug

Completely broken (XX) bifocal glass still provide benefits of being glasses.

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Get bifocal glasses and have the character have near-sighted and far-sighted mutations
2. Break them to (XX) status
3. Wear the glasses
4. They still provide eye correction

### Expected behavior

1. They provide 100% eye correction for all damage levels except (XX)
2. They provide diminishing amounts of sight for each damage level until (XX), where they provide no eye correction.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by mkrutov** [comment]
I would expect "|\" to represent scratched glasses, "|." and further various level of cracks, so it would make sense for them to gradually worsen, not to be just "working ok" or "not working at all".

**Comment by CoroNaut** [comment]
I'm actually wondering, should eye-correcting glasses even be repairable? I know this would make near-sighted and far-sighted mutations much more difficult to deal with. It would however be more realistic and would need to be rebalanced somehow if that were the case. In any case, gradually worsening glasses seems right.
