### ISSUE TITLE
Limitations of mapgen_update Using EOC

### ISSUE THREAD

**Issue by PipeYume** [CleverRaven/Cataclysm-DDA#69837]
### Is your feature request related to a problem? Please describe.

I have reviewed the EOC documentation and aimed to create blocks for 'om_terrain/om_special' through 'mapgen_update.' However, I observed that it is not possible to generate them near the character, similar to the restriction in debug mode, where manual creation of overmap terrain near the character is not allowed.

Due to this limitation, if I intend to create multiple 24*24 blocks using EOC, I have to manually specify the locations with EOC and place 'update_mapgen' one by one. 

### Solution you would like.

What I mean is, is there a possibility for the creation process to be executed through a single EOC command, followed by an update, for a map larger than the 2424 area? This way, I could generate overmap blocks composed of several overmaps from other mods with ease.

**Comment by GuardianDll** [comment]
I don't think it is possible without a massive changes in how map generation works
