### ISSUE TITLE
Remove CBM '!' examine window in favor of it always being visible

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69844]
### Is your feature request related to a problem? Please describe.

Examining bionics currently will cut off text and its an extra key press than it really needs to be. Currently the window displays CBM name, its power usage, and description. The name and power usage are already there, we really only need the description. 

Picture 1 is how it looks without examine window up
Picture 2 shows examine window pastes overtop existing text and really doesn't need to take up 70% of the entire window.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/b4d455ca-79a0-4846-bb21-73a581751747)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/9d15a054-9f1b-43ed-a79f-5cd33d628943)

### Solution you would like.

Make the examine window always visible on the main CBM window.

This picture is how I propose it be. The description of the cbm you currently have selected will always be visible. This could be done for both active and passive tabs. It's unnecessary to hit '!' on every CBM and frees up the keypress.
![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/b2cd088b-48c2-452c-85e4-5a744ce42fa6)
### Describe alternatives you have considered.

Not making it always visible

**Comment by fairyarmadillo** [comment]
That space is only free because you're not playing on 2x, mobile, or a smaller monitor.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/3d499f55-f9d2-4410-85fd-658497f5ed4c)

This is 2x, which plenty of people use. There is no extra space to put the text.

**Comment by CoroNaut** [comment]
Oh gotcha, I can change the suggestion to move it to the bottom

**Comment by CoroNaut** [comment]
It's also the case that the mutation window also puts the examination area at the bottom, so it would even be better for maintenance.
