### ISSUE TITLE
Deconstructing furniture should show possible results prior to deconstrution

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#69848]
### Is your feature request related to a problem? Please describe.

So if one selects an item for disassembly, a confirmation box is shown with the possible results of the disassembly.
But if one selects some furniture for deconstruction, the action immediately starts. Currently there is (to my knowledge) no way of knowing what deconstructing furniture will do without trying it.

That did not bother me for a long time, because it was clear that the furniture would be deconstructed into parts. But now, there are some furniture items that "deconstruct" into a single, functionally identical item, which then can be used as an appliance or even installed into a vehicle. But which furniture stays intact during "deconstruction", and which doesn't? No way to know, one has to try it.

### Solution you would like.

Add a confirmation box prior to deconstruction of furniture.

### Describe alternatives you have considered.

Maybe a new action "take down furniture" in the construction menu could be added. "Deconstruct furniture" could then once again take on the meaning of "disassemble the furniture" - and both actions could be possible for some furniture.

**Comment by Karol1223** [comment]
"Take down furniture" is basically what current simple deconstruction is. It takes 6 seconds iirc.

It'd be nice if we could define deconstruction results per different types of deconstruction, but that is not possible without C++ support

**Comment by Vaskritaya** [comment]
Showing results similar to the disassembly screen would be excellent. It's always annoying having to go back and forth from the hhg and the game to remember what various machinery in industrial areas can deconstruct into.

**Comment by BaumgeistOne** [comment]
> "Take down furniture" is basically what current simple deconstruction is. It takes 6 seconds iirc.

Didnt know that, thanks. :)

So the intention is that "deconstruction" breaks furniture apart, and "simple deconstruction" just takes it down so one can move it to another place.

Unfortunately, there are a few examples where this does not hold, I should have included those when I wrote the issue, sorry about that.

I dont know anymore which examples I had encounted prior to writing the issue, but I just went through some of the game files (furniture-appliances.json, furniture-industrial.json, furniture-medical.json) and found some examples of furniture that need to be "deconstructed" (not "simple deconstruction"), but yield exactly one item (which then can be used as such, I presume):

f_solar_unit
f_oxygen_concentrator
f_hd_compressor_unit
f_xedra_antenna

So those should probably changed to "simple deconstruction"?

The suggested solution of having a confirmation box before deconstruction should still enhance the game though, I think.

**Comment by Karol1223** [comment]
> So the intention is that "deconstruction" breaks furniture apart, and "simple deconstruction" just takes it down so one can move it to another place.

Like I said, no, it's not the intention because it's not possible with the current sourcecode. It'd require adding support for that in C++. Currently it is not possible to have two different yields for different types of deconstruction.

**Comment by BaumgeistOne** [comment]
> Currently it is not possible to have two different yields for different types of deconstruction.

That is all right with me, because that is not what I meant. Sorry for my post not being clear on that. :)

I just wanted it to be transparent to the player if a deconstruction will yield a single item (which then can be taken somewhere else and placed as furniture again), or if the furniture will be broken down into parts - because it is a bit disappointing if one expects the furniture to stay intact, but it is broken down instead.

So if the intention of the two different "deconstruction"-functions was to indicate to the player which furniture will stay intact, there are some which should be changed - I listed those above.
