### ISSUE TITLE
At some point during inventory management, regular view and advanced view show mismatched results

### ISSUE THREAD

**Issue by Montimorency** [CleverRaven/Cataclysm-DDA#69858]
### Describe the bug

While performing routine raiding and shelter operations, while unloading and loading containers at the shelter the inventory stopped displaying all the items I had been carrying. After some reflection and peeking at menus, I discovered that both the regular inventory screen and the advanced inventory screen display only part of what they used to, but combined do represent the total inventory I believe.

See context below for an example from the screenshots. 

### Attach save file

[DinoMind-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13505743/DinoMind-trimmed.tar.gz)

### Steps to reproduce

It happened and was quickly noticed. How to reproduce is unknown. Attached save represents state as-of. 

In troubleshooting I tried dropping all items from both screens and picking them up again, as well as restarting the program, but the issue remained unresolved. 

### Expected behavior

All items in inventory, unless nested and hidden, should be visible as before. 

### Screenshots

![Cataclysm_ Dark Days Ahead - a1ae476 (2)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151707610/5663b6d2-2d7f-445f-9149-e13380578876)
![Cataclysm_ Dark Days Ahead - a1ae476](https://github.com/CleverRaven/Cataclysm-DDA/assets/151707610/5f336787-4430-4a5d-921b-b7a1b8f49f0a)

### Versions and configuration

- OS: Windows
     - OS Version: 7 SP1
- Game Version: [d12347d](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-11-29-0635) [64-bit] 
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
     - Dark Days Ahead [dda],
     - Disable NPC Needs [no_npc_food],
     - Portal Storms Ignore NPCs [personal_portal_storms],
     - Bionic Professions [package_bionic_professions],
     - Alternative Map Key [alt_map_key],
     - Extra Mutated Scenarios [extra_mut_scens],
     - Blaze Industries [blazeindustries],
     - Mind Over Matter [mindovermatter],
     -Bombastic Perks [bombastic_perks],
     -DinoMod [DinoMod]

### Additional context

Regular view: TOOLS
smartphone case
cellphone
e-ink tablet
flashlight
hammer
**heavy-duty flashlight**
mp3#1
mp3#2
multitool
**pliers
pocket knife
2 small adjustable wrenches**
smartphone [in case]
**socket screwdriver set**

Advanced view: TOOLS
smartphone case
cellphone
e-ink tablet
flashlight
hammer
**lighter
mini-lighter**
mp3x1
mp3x2
multitool
smartphone [in case]
**smartphone#2
smartphone#3
x-acto knife**

Bolded are items visible in one view but not the other.

**Comment by esotericist** [comment]
so on investigation it turns out that in the main inventory view, one of the articles of clothing was set to hidden.

then for aim, the "missing" items are in a toolbox, and aim doesn't show contents of nested inventories the way people tend to expect.

this is working correctly, just a little unintuitively.
