### ISSUE TITLE
Unarmed weapons do not contribute to level progress

### ISSUE THREAD

**Issue by Hasleak** [CleverRaven/Cataclysm-DDA#69851]
### Describe the bug

Whenever player is wielding knuckles (tested on scrap knuckles and steel knuckles) while attacking, unarmed skill is not updated with new experience. Before attacking zombie player has 0 lvl and 0% of progress, after attacking and hitting target for any damage, player still has 0 lvl and 0%.

### Attach save file

N/A

### Steps to reproduce

1. Create a character with no unarmed skill.
2. Spawn knuckles.
3. Wield knuckles
4. Hit enemy for non-zero damage

### Expected behavior

Player gains experience in unarmed combat after striking enemy with knuckles.

### Screenshots

![Before striking](https://github.com/CleverRaven/Cataclysm-DDA/assets/7099451/4f510522-850a-48e6-9d44-9d41ab3aa41f)
![After strike](https://github.com/CleverRaven/Cataclysm-DDA/assets/7099451/5896c961-044d-49f7-9133-427fea3ea81c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 636f820 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by gettingusedto** [comment]
have ya tried wearing it?

**Comment by Hasleak** [comment]
Yes, when character is wearing knuckles (and therefore having the fists as the weapon), level is progressing, but damage done is way lower then what I had when i was wielding them. Fists with wearing knuckles and fists without wearing knuckles seems to deal the same damage. I would assume the game registers using knuckles correctly but somewhere there is a link missing with experience gain.

**Comment by Terrorforge** [comment]
You're not supposed to gain Unarmed xp when wielding unarmed weapons, that's not how those work any more. You're supposed to wear them. But they're definitely supposed to deal bonus damage when you do that - assuming you're striking with your fists and not using a martial art that mostly uses kicks, for instance.

**Comment by Hasleak** [comment]
Ok, so I started new character with default values (str 8 and made melee/dodge 10) and tried to kill one zombie with both wearing knuckles and wielding knuckles. Both ways had similar damage, only wearing them provided any learning experience, but now it becomes a bit disorienting in case of usage. It would be nice to have some kind of description that you need to wear them to get bonuses damage from using them instead of wielding them.
