### ISSUE TITLE
"steel-plated kevlar jumpsuit" requires too much kevlar sheets and doesn't allow patches

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69867]
### Describe the bug

I can't help but notice that the "steel-plated kevlar jumpsuit" requires 160 kevlar sheets or patchwork variant. A single sheet is a 12 inch by 24 inch piece of material. Also notice that it requires 160 lycra patches OR 20 lyrcra sheets and 240 synthetic fabric patches, OR 30 synthetic sheets.

I think it's meant to be 160 kevlar patches OR 20 kevlar sheets.

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Try to craft "steel-plated kevlar jumpsuit" and notice crafting requirement for kevlar sheets.

### Expected behavior

Make it require 160 kevlar patches OR 20 kevlar sheets.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/c3da477a-5d8d-427e-8986-1ac2ae8aed95)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Zireael07** [comment]
@turco-ai If it's the case, it should be made clear in the description

**Comment by turco-ai** [comment]
@CoroNaut Well I'm not the one who made the recipe so you'll have to discuss that with whoever did the tailoring stuff, I was providing context for why the recipe is that way.
Also it doesn't make sense to me, how can 20 sheets of Lycra result in .20mm thickness and 30 sheets of nylon result in .30mm thickness but 20 sheets of kevlar result in 2.30mm thickness? Especially when the recipe itself barely has any byproducts of either meaning most of the fabric is indeed used up.
