### ISSUE TITLE
Game stuck when dismembering zombie

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#69863]
### Describe the bug

When performing a dismember action on a zombie, the game is stuck. This only sometimes happens so it was tricky getting a save that allows reproduction but here it is. If you walk away and come back to the same zombie it might work normally.

### Attach save file

[Blue Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13507007/Blue.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Press B to butcher, press B to select the fat zombie, press m to dismember
3. Observe the game getting stuck and having to close the game to kill it

### Expected behavior

Normal dismsmberment

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/926714b5-4632-4ba9-9acf-e97b35c0bc39)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: d12347d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Willzadl** [comment]
Confirmed
