### ISSUE TITLE
Magiclysm spells effects for speed are formatted wrong in character stats

### ISSUE THREAD

**Issue by larey** [CleverRaven/Cataclysm-DDA#69871]
### Describe the bug

Spell effects that add absolute speed are shown using +x%, whilst spells with relative increase show absolute values

### Attach save file

[DEBUG2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13510227/DEBUG2-trimmed.tar.gz)

### Steps to reproduce

1. Make new character
2. Debug add spells Haste, Bless, Synaptic Stimulation and Windrunning as well as enough mana
3. Cast all 4 spells and pass some turns so your stats update
4. open @ stats

it shows:
current speed 595
bio/mut/effects +425
Blessed +20%
Synaptic Stimulation +30%
Windrunning +20%

### Expected behavior

i expected the numbers to add up: 525 * 1.7 is nowhere close to 595
instead those are flat increases: 100 + 425 + 20 + 30 + 20 = 595

it should either show:
current speed 595
Haste +250%
Blessed +20
Synaptic Stimulation +30
Windrunning +20

or simply show only absolute values:
current speed 595
bio/mut/effects +425
Blessed +20
Synaptic Stimulation +30
Windrunning +20

since haste has an extra +2.5x multiplier and the rest are flat increases

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/20834787/a8f27e58-5ace-4bed-97bf-070d9df5e0f3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth]
]

**Comment by Willzadl** [comment]
When I tried to confirm this, it shows up as flat values. Maybe this has been fixed on a newer patch?
