### ISSUE TITLE
Placing wooden stepladder on open air where a meteor hit causes error

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69870]
### Describe the bug

Attempting to place a wooden stepladder on a lower z-level to descend and ascend safely. The stepladder did successfully get placed below the open air tile where I wanted it, so there is just an error.

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Get wooden stepladder and wield it.
2. Activate the stepladder over open air
3. Error

### Expected behavior

Placing wooden stepladder on open air should attempt to place it below. If the tile you try to place the stepladder on has 2 or more z-levels of open air below, then disallow it.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/26c127b6-3580-4c54-81c3-518727290de8)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Willzadl** [comment]
Confirmed, but the ladder still works as stated.
