### ISSUE TITLE
Aid Books, The Proficient Survivor’s Best Friend

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#69876]
### Is your feature request related to a problem? Please describe.

The process of gaining proficiencies is quite long and arduous, with some of them being vestigial and/or misleadingly named. My idea, the Aid book, aims to Expedite the process of becoming proficient in a fun, balanced, player friendly way, and without just making proficiencies take less experience.

### **The Core Concept**

A new flag and/or type of book, that will be referred to as an _Aid Book_ throughout this documentation. The _Aid Book_ type would assist the player in the acquiring of non-combat proficiencies through specific actions performed (I.E. Dissection)  that vary between books. These would be small to moderate percentile boosts that augment the XP already given by the task. 
You could have as many _aid books_ on your person as you want, but they give diminishing returns past two books. It is important to note that _aid books_ **would not improve proficiencies once gained**. They are exclusively to improve the rate of learning for the survivor. From a realism perspective, these learning improvements would be explained by having the books open nearby while performing  the task. 

### **Electronic Storage Solutions**
This means that books stored on E-Ink Tablet PC, and Smartphone work differently, than standard. A book on a Smartphone can only give 70% of its boost, due to its small screen. A book on an E-Ink Tablet PC would be exempt from that penalty.
“But Paul!” I hear you say, “What about the Integrated AR System?” And to that I say, it is very strong. Due to operating at the speed of thought, the AR System is EXEMPT from the multi book penalty. It would instead use a weighted average of your stored books, prioritizing whichever books grant the highest bonus for the particular proficiency, meaning your overall bonus will be higher.

### **Examples**
-Performing the dissection of a creature awards the player x experience in the principles of Biology. With the biology textbook, functioning at an aid of 10% in that proficiency, the player will be awarded x+(x•0.1) experience instead.

-Urist McSurvivor, world-renowned soap maker, and producer of Coalheart, the legendary limestone cooking pot, has decided to branch out into metal working. He is going to make a set of Scrap Boots, which gives proficiencies in _Principles of Metalworking, Cobbling_, and _Joint Articulations_. He has grabbed 3 books: Metals for Goblins, The Art of Bullying Elves (By making better shoes than them), and Making A Sweater for Your Many-Legged, Webspitting Forgotten Beast. He will only gain 85% of their experience augments. The calculation would look something like x+(x(0.1•0.85))+y+(y(0.25•0.85))+z+(z(0.15•0.85).

### Describe alternatives you have considered.

Making it a practice recipe for certain proficiencies, using the book as a tool. Not doing it is also an option

### Additional context

I am JSON Monkey 3rd class. I do not have the skills to implement any of this, and my next  week is PACKED. Furthermore, I can’t test on Mac, but I am looking into setting up Linux. 
HOWEVER, I am posting this here so other people can see the idea, and work on it or give input. After next Sunday, I will be free again. If anyone would be willing or able to mentor me or even just consent to having random questions about the coding side thrown at them to answer at their leisure, contact me at DukePaulAtreides on Discord.
Thank you all for reading this long, long feature request.

**Comment by fairyarmadillo** [comment]
Gaining proficiencies doesn't actually take very long.

**Comment by CoroNaut** [comment]
I like the idea of aid books to help with proficiency. To me, it feels like a masters handbook of sorts, probably even a 20% boost. But perhaps make them rare and a little more tied to their specific buildings, For example, cobbling to a tailors shop, metalworking to a garage, etc. The people who worked in those buildings before the apocalypse probably benefited from them just as much. The bookstores or libraries already seem to contain more standard books for all walks of life. Of course that's up to you, I'm just considering the world building a little.

Considering the speed of gaining proficiency, it may not be worth it for a masters handbook on garment closures if you already make a lot of clothing. A crafting recipe that takes days with many un-learned proficiencies however, would benefit greatly. it could be very good practice along the way.

I agree that gaining proficiencies doesn't take very long, they should probably take longer. Like, I can learn blacksmithing in 10 hours? Personally, 100+ hours for it shouldn't be a stretch. Electrical circuitry learned in 10 hours? Really? Aid books would provide so much benefit if proficiencies were actually _hard_ to obtain in the first place.

**Comment by Inglonias** [comment]
Isn't this already covered by practice recipes being in skill books? How would this be different? You'd be reading a book instead of performing the practice recipes, that's all. Both are the same from a UX perspective (push a button and wait)

**Comment by CoroNaut** [comment]
I would make the argument that practicing is not always the best option. If winter is coming or you're already in the dead of winter without any clothing stores nearby, It's probably not best to practice your knitting, leatherworking, or garment closures. Having found an aid book, it may considerably cut down the time on the initial craft until you become proficient. Along these lines, I could even see books with multiple bonuses. Perhaps a book all about tailoring that gives slight bonus to a good chunk of tailoring proficiencies, or mechanics book for most vehicle-related proficiencies.
