### ISSUE TITLE
Optionally reduce hauling keypresses

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#69880]
### Is your feature request related to a problem? Please describe.

Hauling was recently updated, and now instead of just being a single keypress, it opens up a window and prompts you to pick from several options, doubling the keypresses involved. This feels clunkier than it used to.

### Solution you would like.

I'm not suggesting reverting the change, but adding a toggle somewhere would be nice, or possibly getting rid of the prompt in favor of some set-and-forget system. Hauling is something I wind up having to do constantly and I don't really care about snowballing other items on the ground (I usually just clear a little path for myself, which is something I'd have to do IRL).

I don't have a simple solution to this as I'm not a big UI person, but I bet I'm not the only person who finds it awkward.

**Comment by actually-a-cat** [comment]
The previous behavior of hauling is still available under a new action, "quick toggle hauling".

**Comment by fairyarmadillo** [comment]
Oh, perfect. Thanks!
