### ISSUE TITLE
Allow u_spawn_item to apply flags

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#69889]
### Is your feature request related to a problem? Please describe.

Trying to re-create the photokinetic ability to irradiate food after it vanished as a byproduce of #69630 without just recreating all the fruit that were removed, and without the ability to spawn an individual item with a custom flag 

### Solution you would like.

Add a "flags" option to u_spawn_item that allow the application of custom flags, the way that custom-flags works for itemgroups. 

### Describe alternatives you have considered.

Create individual itemgroups for every single item, each of which would have one fruit with "custom-flags": [ "IRRADIATED" ] in it, so I can turn a regular fruit into an irradiated fruit via EoC.

**Comment by GuardianDll** [comment]
```json
{ "u_spawn_item": "dreamforged_boots_ench", "use_item_group": true }
```

```json
  {
    "type": "item_group",
    "id": "dreamforged_boots_ench",
    "subtype": "distribution",
    "entries": [ { "item": "dreamforged_boots", "custom-flags": "FIT", "prob": 100 } ]
  }
```
