### ISSUE TITLE
Light sources occasionally fail to update tiles from dark to light or vice versa

### ISSUE THREAD

**Issue by ajdye** [CleverRaven/Cataclysm-DDA#69887]
### Describe the bug

Occasionally, when opening a closed curtain or turning off a flashlight etc, the tiles will fail to update to either being lit or being dark until another action is taken

### Attach save file

[Sister Lakes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13519797/Sister.Lakes-trimmed.tar.gz)

### Steps to reproduce

Stand by a window with a curtain and repeatedly open and close the curtains, around 1 in ever 6 times the tiles will fail to update

### Expected behavior

Tiles should update immediately

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49399994/417b03b6-af81-4763-8de5-71630a7e3217)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 400add9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I am using d3d12 as my renderer

**Comment by CoroNaut** [comment]
I've also noticed this. I usually have an atomic headlamp on and when I turn it off, the light stays for an additional turn. At first I was going to test if it was due to higher than normal speed, but if you have the issue as well, it might just be a bug.
