### ISSUE TITLE
Game crashes if NPC auto-equips the same turn you're equipping them in the armor sorting screen

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#69891]
### Describe the bug

Game crashes if NPC auto-equips the same turn you're equipping them in the armor sorting screen. This is honestly pretty annoying just by itself and it shouldn't happen to begin with, somehow?

### Attach save file

N/A

### Steps to reproduce

1. Spawn NPC with clothing
2. Remove their baseball cap or whatever
3. Try to 'E'quip clothing on that armor slot (same coverage?)
4. Crash!

### Expected behavior

First the bug bad. Second, It'd be great if NPCs didn't just wear things the player unequipped them inmediately.

### Versions and configuration

You know, all these additional hoops and leaps serve as strong discouragement for players to report bugs

**Comment by PatrikLundell** [comment]
Reporters too lazy to give a report with sufficient information to investigate it serves as a strong discouragement for investigators to investigate their reports.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.G-12522. Closing until reconfirmed.
