### ISSUE TITLE
The `player_weapon_drop` effect does not work.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#69902]
### Describe the bug

When I tried to use the `player_weapon_drop` effect, found in `TALK_MUG` in an EOC, my character did not drop their wielded weapon when prompted to. The "You'll be helpless!" message popped up, and gave me the query to proceed, but I didn't actually drop anything when selecting "Yes".

### Attach save file

N/A

### Steps to reproduce

1. Try to have the player drop their weapon using the effect.
2. Answer yes to all prompts.
3. Observe as you never drop your weapon.

### Expected behavior

I expect that the character would drop their weapon.

### Screenshots

N/A

### Versions and configuration

OS: Windows 11
Game Version: 2023-11-21-0613 (64-bit)
Graphics Version: Tiles
Ingame Language: English
Mods Loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth

### Additional context

None at this time.

**Comment by MNG-cataclysm** [comment]
This also didn't work for the `TALK_MUG` dialogue option itself.

**Comment by Ramza13** [comment]
I just tried to reproduce this but it seemed to be working for me as a dialog option and in an EOC gave me an invalid beta talker error but in neither case behaved as you described.  Do you happen to have a save or the code you were using to reproduce this issue?  Thanks

**Comment by MNG-cataclysm** [comment]
> I just tried to reproduce this but it seemed to be working for me as a dialog option and in an EOC gave me an invalid beta talker error but in neither case behaved as you described.  Do you happen to have a save or the code you were using to reproduce this issue?  Thanks

The save I was using is long gone, but I'll try and find the code I was testing it on.
