### ISSUE TITLE
Allow Shooter Earmuffs to be worn in HELMET_EAR_ATTACHMENT pockets

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#69926]
### Is your feature request related to a problem? Please describe.

The shooter's earmuffs item should be able to be worn in the Ear_Attachment slot for various hard hats and military helmets

### Solution you would like.

give the shooter's earmuffs the HELMET_EAR_ATTACHMENT flag

**Comment by tenmillimaster** [comment]
This is what attachable earmuffs are for, though? Earmuffs generally don't work well in combination with helmets, nor do they attach to them.
