### ISSUE TITLE
It's technically possible to wield loose gasses

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#69920]
### Describe the bug

It is possible to wield loose gasses if they are in the overworld, despite not being to pick them up. Note that them being in the overworld is technically already an abnormal behavior - when dropped from being wielded they will disappear normally.

### Attach save file

N/A, not without compiling an edited .exe

### Steps to reproduce

1. Compile #65413
2. Get yourself a biogas digester
3. Fill it up with some random organic garbage. Withered plants work
4. Pass time
5. Examine the digester - see that it now contains loose methane which is a gas
6. The methane cannot be picked up, but pressing the keybind to wield it (default ``w`` I believe) will wield it regardless
7. Drop it and see it disappear

### Expected behavior

I guess I expect this not being possible but I am really not sure if this is a valid bug report given under normal circumstances gasses don't appear outside containers.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/452f08c9-fb40-4ea8-8b70-93b5e4e5523f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 0.G-5550-g848c8bf3ec [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Standard combat test suite [standard_combat_test]
]

### Additional context
~~I am not sure if this is a valid bug report, but it is causing me some headache in getting the aforementioned methane PR to be functional~~ Edit: No, definitely valid. You can wield them out of containers this way.

**Comment by mqrause** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/924079e778f03b0053bae24ede1f52acf0ebe02d/src/character.cpp#L7717-L7719

Just needs another check like this for gases.
