### ISSUE TITLE
Provide debugging symbols for our builds

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#69934]
### Is your feature request related to a problem? Please describe.

It is much harder to obtain a usable backtrace when using the provided builds.

### Solution you would like.

Provide debugging symbols separately as an extra asset. I saw on the devcord that apparently there is an issue with the vscode windows builds but can we at least have them for Linux and mac?

**Comment by ZhilkinSerg** [comment]
I doubt it would be helpful in any neaningful way.
