### ISSUE TITLE
copy-from is not compatible with `pocket_mods`

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#69936]
### Is your feature request related to a problem? Please describe.

Which is super bad because #69725 rely heavily on the fact it should work, and is the only thing that hold this PR back

### Solution you would like.

Make it compatible with copy-from, or provide a code that i can use to make it compatible, if possible (i still can't do it for myself \:'( 

### Describe alternatives you have considered.

i prefer to not think about it

**Comment by EIIKaO** [comment]
Is this problem still unresolved?
If so, I would like to suggest an example code for a solution ( maybe ).

**Comment by GuardianDll** [comment]
Yep, still not resolved
I can compile and test someone's else code, but can't really make my own
From what i understand, inheritance is somehow related to adding code to generic factory

**Comment by EIIKaO** [comment]
>From what i understand, inheritance is somehow related to adding code to generic factory

I thought the same thing.

Please forgiven me I have very little understanding of the background of this issue.
However, after much trial and error, I think I have found one of a solution to the problem - pocket_mods are not inherited by copy-from.
Although, I do not fully understand the context of this part of the code too, so I am not sure if it is a preferable change or not. Please keep this as a reference only.

```diff
diff --git a/src/item_factory.cpp b/src/item_factory.cpp
--- a/src/item_factory.cpp
+++ b/src/item_factory.cpp
@@ -3150,7 +3150,11 @@ void Item_factory::load( islot_mod &slot, const JsonObject &jo, const std::strin
         }
     }
 
-    optional( jo, false, "pocket_mods", slot.add_pockets );
+    JsonArray pockets = jo.get_array( "pocket_mods" );
+    if( !pockets.empty() ) {
+        optional( jo, false, "pocket_mods", slot.add_pockets );
+    }
+
 }

```
I can confirm that pocket_mods, not inherited in the previous code, and now, it will be inherited in the modified code( I'm not sure if it was really inherited, but I have verified that the  GUNMOD added copy-from and removed pocket_mods field is can charge the same ammo as its parent, that couldn't in the previous code ).
Also, I believe that the code modifications themselves do not cause any errors( but may be a redundant ).
Please give it a try if you wish.

**Comment by EIIKaO** [comment]
@GuardianDll 
I just happened to see this issue updated by the stale tag added.
And I thought I might be able to help fix this problem.
I'm glad I could help you.
