### ISSUE TITLE
Error from moving items with hauling, error log included

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69931]
### Describe the bug

Sometimes when moving items with hauling and interacting with said items, I get the error that the target was lost. Included debug log 

### Attach save file

Not reproducible from save

### Steps to reproduce

Unable to reproduce. It seems to happen once, but reloading a save and trying again, its fine?

### Expected behavior

No error from moving items with hauling

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Trimmed debug.log to only contain the error in question
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13537150/debug.zip)

**Comment by GuardianDll** [comment]
Issue was resolved in #69827 4 days ago, your version is one week old
