### ISSUE TITLE
Shell Holders

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#69943]
### Is your feature request related to a problem? Please describe.

Long guns, especially shotguns, can IRL be fitted with mods like you see here:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/4b78d86a-aef4-402a-857c-5b0da26bd215)

These would be tremendously useful in Cataclysm, as similar to the shell holders on the tac vest, they could have a low item retrieval time (the tac vest's shell loops are 25 moves), making shotguns much faster to reload.

### Solution you would like.

I attempted to add these myself, but while the mod worked as a pocket when it was apart from the gun, once I installed it, its pocket became inaccessible. I can't quite figure out how to make it work. Here's what I tried:

```
{
  "id": "12_gauge_shell_holder",
  "type": "GUNMOD",
  "name": {
    "str": "12 gauge shell holder"
  },
  "description": "Designed to be affixed to the side of a shotgun's receiver, this polymer shotshell holder can store six 12 gauge shells for easy reloading.",
  "weight": "16 g",
  "volume": "60 ml",
  "price": 2000,
  "price_postapoc": 50,
  "install_time": "30 s",
  "material": [
    "plastic"
  ],
  "symbol": ":",
  "color": "black",
  "location": "loading port",
  "mod_targets": [
    "shotgun"
  ],
  "pocket_data": [
    { "pocket_type": "CONTAINER", "rigid": true, "max_contains_volume": "1 L", "max_contains_weight": "3 kg" },
    {
      "ammo_restriction": {
        "shot": 6
      },
      "moves": 25
    }
  ],
  "min_skills": [
    [
      "weapon",
      1
    ]
  ]
}
```

If anyone knows how to make this function properly, it'd be a really nice item to have.

### Describe alternatives you have considered.

Using a mag-fed shotgun to kill zombies (heresy).

**Comment by GuardianDll** [comment]
Test this json in the recent experimental, it supposed to work now, after #69828 was merged

**Comment by fairyarmadillo** [comment]
> Test this json in the recent experimental, it supposed to work now, after #69828 was merged

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/eca26111-1a29-48dc-a782-b82b3542dd0a)

Just tried it, doesn't seem to work. I don't see a pocket anywhere on the item, I can't open it, I can't access the holder at all without removing it.

**Comment by mqrause** [comment]
You would need to use `pocket_mods` instead of `pocket_data`, then it might just work.

**Comment by fairyarmadillo** [comment]
> You would need to use `pocket_mods` instead of `pocket_data`, then it might just work.

Thanks, I'll give that a shot.
