### ISSUE TITLE
Automatic stacking of containers inside other containers obscures information

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#69959]
### Describe the bug

When you pick up a bag of a single item, if you have an existing bag of that item it'll try to insert the second one into the first, making everything so much harder to find. Look at this screenshot. These are bags of salt, cinnamon, green tea, and other small items. There's no easy way of telling how much I have of what.

### Attach save file

N/A

### Steps to reproduce

Pick up a bunch of items stored in plastic bags. See how it becomes impossible to see what you have without a lot of work.

### Expected behavior

I'd expect that there wouldn't be this auto-insert function until such time as the ability to report on the contents of the bag could propagate upward, ignoring secondary containers.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/9101f16c-cd59-4236-a981-f0ad64a8550d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 61cbf90 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
What's actually in those plastic bags? They all have whitelists so they shouldn't have picked up random items. Did they spawn like that? A save file would have helped.
