### ISSUE TITLE
Weapon steadiness bar doesn't display partial steadiness, only empty or full

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69954]
### Describe the bug

The weapon steadiness bar should probably display any amount of steadiness.

### Attach save file

[testing3-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13539495/testing3-trimmed.tar.gz)

### Steps to reproduce

1. Get weapon
2. Steady weapon and notice that steadiness either displays 0% or 100% when fully aimed

### Expected behavior

Weapon steadiness bar displays partial steadiness

### Screenshots

First picture shows 0% actual steadiness, second picture is 99% actual steadiness, third picture is 100% actual steadiness
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/101b6a78-b537-4862-b423-51fc4524bb57)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/e1dc4360-7ee4-4716-986e-f2f16ee6f433)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/db132c8b-49a1-419e-8f02-cc548a8e1014)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 5d3940a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by OldFriendEr** [comment]
was bugging me for a while, working on it now
