### ISSUE TITLE
Magiclysm weapons can't be used for weapon practice

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#69968]
### Describe the bug

If I have a +1 halberd, I can't practice with it. This is true of all enchanted weapons.

### Attach save file

[Langes Corners-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13540478/Langes.Corners-trimmed.tar.gz)

### Steps to reproduce

Have an enchanted weapon, be unable to practice.

### Expected behavior

I would expect that they would work like unenchanted weapons for weapon practice.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/5a45ef73-5523-4132-8c95-d4cc89c19c46)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/944ad7f5-513f-4449-88f7-29a5f47c03eb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 61cbf90 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
So I suppose that means that "weapon_category": [ "POLEARMS", "SPEARS" ], doesn't copy-from the halberd?

**Comment by Termineitor244** [comment]
> So I suppose that means that "weapon_category": [ "POLEARMS", "SPEARS" ], doesn't copy-from the halberd?

That would be a common problem for mod weapons, but the problem here is with the practice recipes, which do not use weapon categories, they use item (requirement) groups, and even that is pretty recent, here: #69427.

They have to be manually added to the groups.
