### ISSUE TITLE
Inaccessible labgen in case Subway fails to generate

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#69975]
### Describe the bug

With https://github.com/CleverRaven/Cataclysm-DDA/pull/69912, worldgen generates inaccessible subway-only labs with no subways, if you go further west. 
This behaviour could be replicated in pre-69912 builds by lowering amount of towns and their size. 

### Attach save file

[Mannford.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13541703/Mannford.zip)

### Steps to reproduce
With geo:
1. Make new world.
2. teleport few tiles `h` west
3. reveal map

Without geo:
1. Make new world with city size = 1-4
2. Reveal map
3. If there are no (or very little) subway stations, you're in OM region which has this problem.

### Expected behavior

labs are either not generated at all or have some sort of connections to surface. lab-only subway maybe?

### Screenshots

![lab_no_subway_connections](https://github.com/CleverRaven/Cataclysm-DDA/assets/48674477/8c0d3d91-ca69-4031-9a1d-765bd9b07eea)
![lab_single_tile_subway](https://github.com/CleverRaven/Cataclysm-DDA/assets/48674477/8c192519-0bda-49ea-8674-2f559190eb7f)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: baff13d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by mkrutov** [comment]
The overall lab generation is rather weird in the save.
The research faciltiy in overmap where character is, consists of a single "lab basement" and no actual lab.
The other lab displayed in screenshot, also has an entrance from surface (ventilation shaft) but has only two tiles: one subway entrance tile and one subway tile.
I assume its somehow affected by marvelous changes to Geography.

**Comment by mkrutov** [comment]
stub rail isn't the only problem in screenshot: all the other labs are not connected to surface *at all*. and judging by their looks, they're supposed to have subway connection between them.

I'll take a look later using a build from a week ago on if I'd be able to generate such labs set without geo changes.

**Comment by Procyonae** [comment]
Here there any cities on that 180x180 overmap? Can't remember how the subways spawn but I think they'd need at least 1 city subway station to work

**Comment by RenechCDDA** [comment]
#69912 was merged after the timeframe we'll likely select the recent candidate from, do we need this to be a blocker?

Basically, the "at-fault" PR is from December, so if 0.H branches from mid-November, as we expect, this won't block the stable release.

Still an issue in itself, just doesn't block stable.

**Comment by mkrutov** [comment]
It doesn't seem to be geography-related. If you would generate any region in which there would be no cities (or rather, no subway stations) you would end up with what's in the OP message.

**Comment by Procyonae** [comment]
I think that's still exasperated by the geography changes, I haven't checked yet but I presume heading North-East will eventually start spawning less cities than 1 on average

**Comment by Zireael07** [comment]
"Preexisting but exasperated by geography" is my take on it, too
