### ISSUE TITLE
You can see what is on top of rooftops from below with 3D FoV

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#69973]
### Describe the bug

You can see the top of roofs whilst e(x)amining from lower than them with 3D FoV.

### Attach save file

[Etta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13541379/Etta-trimmed.tar.gz)

### Steps to reproduce

 1. Go to a crossroad
 2. e(x)amine
 3. Go at least one z-level higher than the desired rooftop's level
 4. Know exactly where the birds lay their eggs

### Expected behavior

e(x)amining upwards doesn't reveal something above you just because it's lower than where you're looking.

### Screenshots

_From z-level 1 and upward_
![z-level1](https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/49438983-1a7e-4f71-82d0-de5acac58b8c)
![z-level2](https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/5745a0e1-c9f2-41f0-9c51-fb4f37b695a7)
![z-level3](https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/a9640849-4c1a-4858-a6e4-cbf8782ca1c3)
![z-level4](https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/0ac9e564-7268-4a4f-ab9d-eeec9906d82f)
![z-level5](https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/887f8cc4-65ff-4f5b-82e9-31376d69dbf3)
![z-level6](https://github.com/CleverRaven/Cataclysm-DDA/assets/32048635/5c925da2-0ed1-49c0-ada4-4b57dc3cb60d)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: e1b1331 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food]
]

**Comment by Golfavel** [comment]
This is not intended; even if it was, it's nonsensical and not how vision works. You can't see what's on the opposing side of a building's rooftop just by looking higher up.
It appears to just be an oversight with e(x)amining that causes it to "see" things below the camera's z-level's position that would otherwise be obstructed.

**Comment by fairyarmadillo** [comment]
> This is not intended; even if it was, it's nonsensical and not how vision works. You can't see what's on the opposing side of a building's rooftop just by looking higher up. It appears to just be an oversight with e(x)amining that causes it to "see" things _below_ the camera's z-level's position that would otherwise be obstructed.

You're right, I was misreading your screenshots.

**Comment by Rewryte** [comment]
I am unable to reproduce the issue on a new world or my existing worlds.  Only the one included seems to be affected.  Save file issue?

**Comment by Golfavel** [comment]
No; I can reproduce it consistently in any world. 
Fresh install (settings adjusted ["Experimental 3D field of vision": false>true] ["Vertical range of 3D field of vision": 4>21]), fresh world:
[Escalante-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13621814/Escalante-trimmed.tar.gz)

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: 80f42a0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CoroNaut** [comment]
I was also able to reproduce, (if I understand the issue correctly). I followed the above comments steps. I can see the tops of these buldings despite never being above level 0 in this area. I just used the 'look around' view to go up and down z-levels.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/b26236eb-a76f-43a8-a278-49a53f8125af)
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CoroNaut** [comment]
I also see this weird thing happening where I can see the roofs of some buildings, other buildings I cant, and some weird phantom lines above just grass.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/059fe7e4-4f8a-480f-916b-57a09d0a3dfc)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/af0b0393-c347-4981-a559-a2ec11e19624)

**Comment by Rewryte** [comment]
Disregard my previous statement, I've misunderstood the issue.  It does seem that an invisible non-memorized tile would appear as visible when a character from a z-level below examines a visible tile on a z-level above it.  Because the wrongly visible tile is memorized when this happens, this issue only happens the first time said tile is examined.

I could work on a fix if it isn't already being worked on.

**Comment by Golfavel** [comment]
I presume no one has taken a look, feel free.

**Comment by Rewryte** [comment]
Working on it.  I'm now fairly certain that this has something to do with how `draw_points` in cata_tiles.cpp are generated.  Even though previous fixes to 3D vision allowed these draw_points to recalculate visibility variables each z-level, it does not account for the fact that in certain situations, a draw_point on a specific z-level should not exist in the first place.  I could add a variable that would invalidate a draw_point that should not be there, but I'm also exploring other options that could help improve code maintainability in the long run.
