### ISSUE TITLE
Charge removing update broke overeating warning

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#69995]
### Describe the bug

Before the charge removing update - all food was calculated in charges, but now food without charges can make you overeating, and this can cause character to barf with pain and food loose. For food with charges like fruit jam, souses, mayonnaise and other liquid type food all works as before with warnings  

### Attach save file

N/A

### Steps to reproduce

1) Spawn/find non charge food, like protein rations, cheese, butter and other types of food - eat and see, that you will have overeating warning only after have "engorged" hunger status, with pain and high chance to barf and loosing food
2) Find fruit jam, souses, mayonnaise and other liquid type food, eat and see, that you will have warning, when you are trying to eat at "Full" hunger status

### Expected behavior

I don't want my stomach to barf and fell pain

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: b160939 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
/confirm, tho i am not sure it is caused by charge removal

**Comment by KHeket** [comment]
> i am not sure it is caused by charge removal

I loaded [Cataclysm-DDA experimental build 2023-07-31-0609](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-07-31-0609) spawned 100 portions of cheese, trying to eat it - the warning appeared at "Full" hunger level

I loaded  [Cataclysm-DDA experimental build 2023-07-31-1032](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-07-31-1032) - make the same - and I have the same problem as I mention in first post

**Comment by KHeket** [comment]
@mqrause can you check pls? Because this ultra annoying bug caused by charge removing and it still bugged because of it, and I am still overeating time to time

**Comment by mqrause** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/61d263b6827c363f21bc2addebc871080e24be2c/src/consumption.cpp#L958

Seems to be this check. It's probably enough to remove the check for charges > 0, I don't think that served much of a purpose even before the charge removal.
