### ISSUE TITLE
(Aftershock Exoplanet) Escape Pod invalid alpha talker

### ISSUE THREAD

**Issue by Hegamonia** [CleverRaven/Cataclysm-DDA#69999]
### Describe the bug

 DEBUG    : Tried to use an invalid alpha talker.  Callstack: Spell: escape_pod Caster:  \ EOC: EOC_ESCAPE_POD_CHAIR

 FUNCTION : actor
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 2288
 VERSION  : 9fb0824

### Attach save file

[Aftershock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13553156/Aftershock-trimmed.tar.gz)

### Steps to reproduce

1.) Create character using the Emergency Evacuation scenario
2.) Progress through the map to the escape pod
3.) Ready the escape pod
4.) Step into the pod to produce error

### Expected behavior

The escape pod should teleport the player down to an escape pod on the surface of Aftershock's titular Salus IV. As it stands now, they are trapped on the ship, and are guaranteed to die

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 9fb0824 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock: Exoplanet [aftershock_exoplanet],
    Mind Over Matter [mindovermatter]
]

**Comment by theblacksquid** [comment]
Just want to confirm that the build 2024-01-14-0248 also has this on linux.
