### ISSUE TITLE
Coal can be loaded into camp forge infinitely & loaded camp forge doesn't provide "forge" for crafting. 

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#70005]
### Describe the bug

What it says on the tin. Forge can be only used with charcoal.

### Attach save file

n/a

### Steps to reproduce

1. make forge
2. put coal in
3. put more coal in
4. put more coal in
5. craft stuff.

### Expected behavior

coal is limited to 2000 units,same as charcoal
on second use it should ask "unload X coal?"
on top of which forge with coal should provide forge with charges for forging recipes

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: baff13d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by KeremBabaG** [comment]
the function that define the ammo of furniture takes only the first element in the set of ammo in json, I tried to take a crack at it but failed miserably

iexamine.cpp 4332 if anyone's interested

also lemme try this
