### ISSUE TITLE
[XEDRA Evolved] Zebra agent bodies keep respawning at certain location

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#70003]
### Describe the bug

Once cleared fuel station from all enemies. 
After i returned there, I got newly spawned group of zombie security guards.
Now each time i return in the area i get either unpulped corpses of Zebra agent that soon turn into security guards, or a group of security guards.

### Attach save file

[Orpheus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13559020/Orpheus-trimmed.tar.gz)

### Steps to reproduce

1. Leave the area in question for some time(day or two)
2. return

### Expected behavior

Once killed, should stay dead if pulped and dissected properly.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/25095102/2d2c5192-eeee-450e-9aa9-c9a828142237)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ALT; Description: ALT Workstation K 10.2 (Sorbaronia Mitschurinii); Release: 10.2; Codename: SorbaroniaMitschurinii; 
- Game Version: c435321 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extra Mutated Scenarios [extra_mut_scens],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Tamable Wildlife [Tamable_Wildlife],
    No EMP Damage [no_emp]
]

**Comment by Maleclypse** [comment]
Something is going wrong with the random encounter eoc.

**Comment by Maleclypse** [comment]
If this is still happening I've been unable to reproduce it.
