### ISSUE TITLE
Having a tool with Lifting quality nearby lowers stamina consumption for hits performed

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#70004]
### Describe the bug

What it says on the tin.

with hoist nearby (on next tile): 8500 stamina becomes 8402 after 1 hit
without hoist nearby: 8500 stamina becomes 8386 after 1 hit.

### Attach save file

n/a

### Steps to reproduce

1. build hoist & tackle
2. spawn debug monster
3. stand near hoist & tackle, hit monster with a quarterstaff
4. stand 2 tiles away, hit monster with a quarterstaff

### Expected behavior

same stamina consumption for both actions

### Screenshots

![Screenshot_20231205_122043](https://github.com/CleverRaven/Cataclysm-DDA/assets/48674477/ee65bf45-b281-4d54-8882-07b564f5b1e9)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: baff13d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
Unable to reproduce. Stamina cost is the same regardless of whether I attack with or without a rope & tackle hoist next to the character.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/89eb7453-d63e-4c53-b7a7-86d5debeaed0)
