### ISSUE TITLE
[Magiclysm] Greater Dimensional Bag Unobtainable

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#70000]
### Describe the bug

The greater dimensional bag is not obtainable.  There's a couple of places that it could spawn, such as the black dragon lair or forge of wonders, but currently it does not.

### Attach save file

N/A

### Steps to reproduce

Look in code for spawning definitions

### Expected behavior

Item should be obtainable somehow, even if very rarely / difficultly

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: b2bbf19 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Modularvests [modularvest],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Blaze Industries [blazeindustries],
    <color_light_green>Cataclysm++</color> [Cata++],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Mana Cores [manacores],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Advanced Gear/Technologies [advtech],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    CBM Equipment [CBM_Arms],
    Food preservation via ionizing radiation [irradiate-food],
    Garden Pots [growable-pots],
    Incinerator [incinerator],
    Tileset Blaze Industries [tileset_blazeindustries],
    Tileset Aftershock [tileset_aftershock],
    Tileset Magiclysm [tileset_magiclysm],
    Pneumatic fun [pneumo_fun],
    Rivtech Beam Swords [beamswordmod],
    XEAS [XEAS],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Alternative Map Key [alt_map_key],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Hydroponics [hydroponics],
    Mining Mod [Mining_Mod],
    Mole Mutation [dig_a_tunna],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Magiclysm [MMA_Magiclysm],
    Translate Complex Dialogue [translate_dialogue],
    Dream of Flight [dream_of_flight],
    Bombastic Perks [bombastic_perks],
    Whaleys TALL Buildings [whaleys_tallbuild],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    No Bionic Slots [no_cbm_slots],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Resource Crops [resource_crops],
    Resource Crops for Magiclysm [resource_cropsMagic],
    Sly's Mighty Morphin Mutation Station Reworked [sly_mutation_improvements],
    Stats Through Kills [stats_through_kills],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Minimod: No Skill Rust [minimod_no_rust],
    Mutation Selector [mutation_selector],
    No Fungal Monsters [No_Fungi],
    Personal Modifications [personal_modifications]
]

**Comment by casswedson** [comment]
/confimed /good-first-issue
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/7303b609-34a1-4a24-9388-0b4789353b15)
