### ISSUE TITLE
Error adding corded power drill to mounted workshop

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70014]
### Describe the bug

Got some error messages adding a corded power drill to mounted workshop.

### Attach save file

N/A

### Steps to reproduce

Try to put a power drill in a mounted workshop.

### Expected behavior

No errors?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 61cbf90 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

 DEBUG    : tried to put an item (null) count (1) in a container (corded_powerdrill) that cannot contain it: pocket with type (MAGAZINE_WELL) not found

 FUNCTION : put_in
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1622
 VERSION  : 61cbf90

and also 

 DEBUG    : inserting null into corded_powerdrill's MAGAZINE_WELL pocket failed

 FUNCTION : prepare_tool
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\vehicle_use.cpp
 LINE     : 1790
 VERSION  : 61cbf90

**Comment by Vaskritaya** [comment]
duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/68901 although thats stale as i post this

**Comment by MrHrulgin** [comment]
These errors now trigger any time I examine the vehicle with the workshop with the power drill, so it's not on installation, it's on interaction.
