### ISSUE TITLE
[MoM] Electron Overflow puts empty spell on menu, breaks concentration spells

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#70013]
### Describe the bug

Due to a problem I'm fixing in #70012, letting Electron Overflow reach its first Concentration interval has some odd effects. It puts this "empty" spell on your spell list:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/c7a990d6-e2a2-4e94-a96b-88ef45147158)
This causes the game to throw a number of (seemingly?) harmless errors; see Screenshots.

Whenever I try to craft one of the psychic practice recipes, I get a screen telling me "Excessive error repetition detected" and to file a bug report.

After applying my fix to an already affected save, this also happens when a concentration spell reaches its concentration interval. Sometimes the game crashes when this happens.

#70012 appears to fix this problem going forward but it doesn't fix the problem once present, so it would be nice if we could figure out what the hell happened here so we can fix this on any saves that have already encountered the bug and hopefully prevent it from happening/undo it in the future. The proximate cause seems to be a literal one-character typo, and I don't think we can prevent those from ever happening in the future.

### Attach save file

[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13566842/Mindssachusetts-trimmed.tar.gz)

### Steps to reproduce

1. Cast the broken (current) version of Electron Overflow
2. Wait until one concentration interval passes
3. Attempt to use any practice recipe

### Expected behavior

no phantom spells, no errors

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/ec19f689-f234-4f15-b415-6e2f5dd1df28)
On opening the save.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/cf200f43-af98-4060-b4bd-c7b7132d589c)
On opening the spellcasting menu

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/b223ed8c-c19f-4ba3-9d7a-cba8993d6830)
This is the error I get when trying to craft practice recipes, and when a concentration spell reaches its interval.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: c435321 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

### Additional context

Even if we don't find a general solution I would appreciate any tips on how to manually unfuck this because it happened to my main save and I don't know how to fix it.

**Comment by Standing-Storm** [comment]
Hmm...just spitballing here, but if you make an actual dummy spell with that id, do the errors stop?

**Comment by Terrorforge** [comment]
What ID? Just an empty string?

**Comment by Terrorforge** [comment]
Yes, it shows up in my spell list.

No, I cannot debug-unlearn it. It doesn't show up in the debug spell interface.

**Comment by Terrorforge** [comment]
Okay, it seems that was just my computer having a moment. The spell is gone, and as far as I can tell my save appears to be back to normal.

Should we put in a dummy 'backup' spell with the id "" in case something like this happens again? With a description instructing the player to file a bug report if it ends up in their spell list. I don't know enough about the spellcasting system to say if that would be a bad idea for some reason.

**Comment by Standing-Storm** [comment]
I likewise can't say whether trying to formally put in a "" id would make any tests angry.  It seems like the kind of thing that would explicitly need to be accounted for.
