### ISSUE TITLE
Sky Island Permadeath

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70036]
### Describe the bug

Sky Island mod features a system where when you leave the sky island to go down to the surface and die, instead of ending the save file and going to epilogue, you return to the sky island naked. 

In this BUG, dying is triggering the normal death screen despite using the sky island mod which has its own system(mentioned above). This seems to happen on the second death. 

### Attach save file

Memorial/Graveyard file
[2023-12-06T08-13-15.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13594372/2023-12-06T08-13-15.zip)

### Steps to reproduce

Create a character in a sky island world.
Die on the surface after usign the warp stone.
Go on a second run, and die again.

### Expected behavior

Players that die on the surface are expected to respawn on the sky island. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 1e7d45b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Mind Over Matter [mindovermatter]
]

### Additional context

was also broken on yesterdays experimental (2023-12-06-1516)

**Comment by mkrutov** [comment]
possibly related to https://github.com/CleverRaven/Cataclysm-DDA/issues/69814
