### ISSUE TITLE
Save files ending with a period breaks file explorer

### ISSUE THREAD

**Issue by ikrarkjr** [CleverRaven/Cataclysm-DDA#70038]
### Describe the bug

My computer is totally bugging out after having a world ending with "..." not allowing me to even access that world file in file explorer on windows.

### Attach save file

N/A

### Steps to reproduce

1. Create a world file called "test" 
2. Create a world file called "test..."
3. Open the cdda > save folder in windows file explorer and attempt to delete "test..."
4. "test" will then be deleted instead, and you cannot delete "test..." nor access it anymore.

### Expected behavior

It to function as a normal world file, and be deleted as any other files does.

### Versions and configuration

Windows 10
Version 5d35506 (I doubt this matters though)

**Comment by ikrarkjr** [comment]
https://www.mediamonkey.com/forum/viewtopic.php?t=88681
This seems to be confirmed to be a windows issue. In any case, I think it should be fixed still, so that no one else encounters this horror.

**Comment by alef** [comment]
According to Windows [Naming Conventions](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions):

>  Do not end a file or directory name with a space or a period.

There is already a `cata::ensure_valid_file_name()` but its not used everywhere. It is also missing this special case.

**Comment by RenechCDDA** [comment]
Should be resolved by #70589
