### ISSUE TITLE
Dehydrated Vegetable use in recipes should be made more consistent

### ISSUE THREAD

**Issue by Voideka** [CleverRaven/Cataclysm-DDA#70032]
### Is your feature request related to a problem? Please describe.

Several cooking recipes require rehydrated vegetables, while others can use dehydrated vegetables. For example, neither broth nor vegetable soup can use dehydrated vegetables, but fish soup and woods soup can.

### Solution you would like.

Dehydrated vegetables should be made available to all recipes requiring vegetables (and liquid), making them interchangeable with rehydrated ones.

Ideally this is applied to all forms of dehydrated foods, but I have only briefly looked at vegetables.

From a realism perspective, dehydrated foods should be rehydrated before being used, however I would consider this step to be part of the process of preparing ingredients for a recipe, which is why I think verisimilitude is maintained by simply allowing them to be used without additional steps. The granularity added to crafting by requiring the preparation of individual ingredients becomes burdensome after a point, and I don't think anything is gained from a gameplay or realism perspective by having players rehydrate ingredients before use.

### Describe alternatives you have considered.

The alternative is removing dehydrated ingredients from recipes and only allowing rehydrated ones.

**Comment by fairyarmadillo** [comment]
There's a bunch of stuff you wouldn't need to rehydrate "veggys" for. Soup's a great example, you can just toss 'em into the broth. So we shouldn't really consider disabling cooking with them entirely.

**Comment by Voideka** [comment]
To a degree, but some veggies work this way and some don't. [The recipe here for corn chowder](https://extension.missouri.edu/publications/gh1564), for example, has you rehydrate the corn for 30 minutes before the actual soup-making process. That being said, it is part of the prep-work for making the soup, which is why I think the preferred solution is just incorporating the rehydration process into the recipes themselves.
