### ISSUE TITLE
What's w/ the "Killed the XEDRA officer" achievement

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70043]
### Is your feature request related to a problem? Please describe.

I really don't know where the XEDRA officer is supposed to spawn

### Solution you would like.

I saw it in the achievements list, & checked the guide to check, didn't find anything, so I searched around & found some creatures like Mercenary officer & Mercenary Ghost related to it, spawning from spikes? I haven't really done much long-term playthroughs, & don't know where this is supposed to spawn or where it should happen.

**Comment by CoroNaut** [comment]
Look in subways at level -2, you may come across a "subway station?". There are a few types of labs that can generate from this subway. The one with this achievement is larger than the rest, and contains a physics lab, and the achievement can be found on level -4 of this lab.

This particular lab has about 95% chance to spawn in the -2 subways, so if you're confident you've explored them 100%, I recommend checking in the next closest 180x180 overmap region. Subways generate per-region and don't connect between them. Once again, I can fill in complete details if you'd like, its just that this particular lab has some pretty good story/lore and I'm hesitant to spoil it. :D

**Comment by PGR-14** [comment]
Thanks!

**Comment by Maleclypse** [comment]
Seems to have been answered
