### ISSUE TITLE
[MOM] Cryokinesis

### ISSUE THREAD

**Issue by MoonlightKitty26** [CleverRaven/Cataclysm-DDA#70042]
### Is your feature request related to a problem? Please describe.

If pyrokinesis is based on using the mind to accelerate air particles to generate heat (if I'm understanding the lore properly), then it stands to reason that doing the opposite to decrease heat should, in theory, be possible in some way, shape, or form.   

### Solution you would like.

I imagine Cryokinesis would be able to decrease the temperature to do things like making room temperature or hot food/drink items cold or making them freeze over (Opposite of Banked Flames) or creating a zone of cold air (Opposite of thermogenesis) to counteract dangerous heat. Could also be used to keep the user cool (opposite of cloak of warmth).

I thought that maybe using ice attacks would be possible as rapidly cooling the air might be able to cause moisture to freeze over, but I don't think that there'd be enough water in the air to do anything interesting without violating the mod's philosophy, not to mention where the energy would even go in the first place.

Hypothetically speaking, if this didn't cross over into "magic" territory, some powers I've thought of are:
-"Creating" very small amounts of water to slow down thirst.
-flash freezing targets and doing cold damage, inflicting frostbite and slowing them down.
-Internal Refrigeration, which does the opposite of internal fire and helps keep the cryokinetic cooler.
-"Creating" thin needles of ice that would do piercing damage and cause bleeding
-"Creating" thin layers of ice on the ground to potentially cause enemies/targets who walk over tiles to become downed by slipping

**Comment by PGR-14** [comment]
Maybe it could also be the Pizza delivery driver? There's something in that description about the cryogenics lab, maybe they got their powers from there? Seems like a good idea

**Comment by Maleclypse** [comment]
> Maybe it could also be the Pizza delivery driver? There's something in that description about the cryogenics lab, maybe they got their powers from there? Seems like a good idea

Pizza delivery driver is from Isolation protocol not MoM

**Comment by PGR-14** [comment]
> Pizza delivery driver is from Isolation protocol not MoM
It's In the base game?
Cataclysm-DDA/data/json/professions.json, line 4151
    "description": "You were delivering the last pizza of the night to the local cryogenics lab when hungry zombies attempted to make a meal out of you.  Fleeing for safety, you find yourself with only your wits and some leftover pizza.  And they didn't even leave a tip!",

I just thought it'd be a fun addition to add it in due to the discription
