### ISSUE TITLE
Special Prothetics

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70050]
### Is your feature request related to a problem? Please describe.

The Prothetics we have aren't very durable, plus, it would be cool to have a bionic arm

### Solution you would like.

Some arm things could be:
-Survivor Prosthetic: Almost handmade, you'd need a pre-existing prosthetic, which you'd armor & reinforce (Neuro version too?), as well as some tools w/ it (Lockpick, Shocker? IDK) would require batteries, maybe some special attachments like an axe hand or something
-Multitool Prosthetic: Reloadable w/ Med bat, some tools (Cordless drill, Multitool, Wrench, Etc.), pretty rare to find
-Designer Prosthetic: Essentially a normal prosthetic, but for stylish trait.

Legs:
-Running leg: Would let you run, & faster too.

You could add some more if you'd like

**Comment by Daved27hundred** [comment]
I'm not sure about the tool prosthetics. I did however have an idea a while ago for Exodii prosthetic arms and legs.

**Comment by MNG-cataclysm** [comment]
What about integrated combat prosthetics, like a shotgun arm or sword hand? I can envision survivors having a use for those.

**Comment by CoroNaut** [comment]
I can imagine a battery slot directly in the prosthetic that can power certain functions. If they accept light/medium/heavy battery mods, it would be amazing to see them accept a UPS conversion mod as well. These remind me of the X-Mechs. Perhaps some more advanced prosthetics could be 'experimental'.
Arm suggestion: Power arm (adds additional bash damage using fists or anything you wield in exchange for power)
Leg suggestion: Lifting prosthetic (adds weight capacity, up to you for the amount)

I could also imagine prosthetics with 'module' slots. Then certain functions can be integrated into these modules. For example, An atomic light, or battery light module, takes 1 slot in the arm and can be activated in the arm menu. A multi-tool module could be 4 slots and allow you to take small tools out of your arm. Lockpick could be 2 slots, etc. 

I also noticed that prosthetics already have the artifact information in their JSON. Perhaps we could find very VERY special artifact prosthetics with cool artifact effects.

Anyways, I love the idea.

**Comment by MNG-cataclysm** [comment]
> I could also imagine prosthetics with 'module' slots. Then certain functions can be integrated into these modules. For example, An atomic light, or battery light module, takes 1 slot in the arm and can be activated in the arm menu. A multi-tool module could be 4 slots and allow you to take small tools out of your arm. Lockpick could be 2 slots, etc.

[This man](https://www.bing.com/videos/riverview/relatedvideo?q=artificial+eye+flashlight&mid=6956950280915748005C6956950280915748005C&FORM=VIRE) did something like this with his prosthetic eye, so it's within the realm of possibility and feasibility. It'd probably be a bit easier with a larger prosthetic like an arm or a leg, as there's more space to work with than an eye.

**Comment by CoroNaut** [comment]
You could use the artifact system to increase stats pretty easy actually
![Capture353535353](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/e010a8d0-4620-44fc-ac90-3a615646c18b)
