### ISSUE TITLE
Follower NPC's asthma attack causes severe slowdown when npc is doing crafting task.

### ISSUE THREAD

**Issue by freijie** [CleverRaven/Cataclysm-DDA#70055]
### Describe the bug

Asked NPC to work on some craft
NPC got asthma attack while working on task
Game slowed down to the point where one turn took several seconds to compute
Canceling task of NPC stops the slowdown

### Attach save file

[Naraka-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13604236/Naraka-trimmed.tar.gz)

### Steps to reproduce

Have npc with asthma
Make npc do some crafting work
Be nearby
when asthma attack happens, slowdown starts.

### Expected behavior

follower's attack shouldnt  be an issue for game

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ALT; Description: ALT Workstation K 10.2 (Sorbaronia Mitschurinii); Release: 10.2; Codename: SorbaroniaMitschurinii; 
- Game Version: f971570 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extra Mutated Scenarios [extra_mut_scens],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Tamable Wildlife [Tamable_Wildlife],
    No EMP Damage [no_emp]
]

### Additional context

xedra/mom mods enabled

**Comment by BrettDong** [comment]
<img width="1230" alt="profiler" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/21075502/386bb187-a148-48c9-aec4-f16bcb49fbe9">
