### ISSUE TITLE
AIM can be used to teleport items across the land. 

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#70061]
### Describe the bug

AIM teleports items from containers. 

### Attach save file

n/a

### Steps to reproduce

1. Get an item inside of a container.
2. Open container in AIM
3. Move away from container
4. Open AIM again

### Expected behavior

No teleportation

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 4c4d1d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

It got introduced at some point after baff13d.

**Comment by andrei8l** [comment]
looks like a tiny mistake from fd6906f88e0335684087f0f6d68f5ae1fca50834 (#68226) and it only happens in the [A]ll and [D]ragged panes. 
<details>
<summary>Potential fix:</summary>

```diff
diff --git a/src/advanced_inv.cpp b/src/advanced_inv.cpp
index dc3c4154a8..f0d8e17f17 100644
--- a/src/advanced_inv.cpp
+++ b/src/advanced_inv.cpp
@@ -707,7 +707,7 @@ void advanced_inventory::recalc_pane( side p )
     advanced_inv_area &other = squares[there.get_area()];
     avatar &player_character = get_avatar();
     if( pane.container &&
-        pane.container_base_loc >= AIM_SOUTHWEST && pane.container_base_loc <= AIM_NORTHEAST ) {
+        pane.container_base_loc >= AIM_SOUTHWEST && pane.container_base_loc <= AIM_ALL ) {
 
         const tripoint_rel_ms offset = player_character.pos_bub() - pane.container.pos_bub();
 
```

</details>

**Comment by Kamayana** [comment]
> looks like a tiny mistake from [fd6906f](https://github.com/CleverRaven/Cataclysm-DDA/commit/fd6906f88e0335684087f0f6d68f5ae1fca50834) (#68226) and it only happens in the [A]ll and [D]ragged panes.
> Potential fix:
> 
> ```diff
> diff --git a/src/advanced_inv.cpp b/src/advanced_inv.cpp
> index dc3c4154a8..f0d8e17f17 100644
> --- a/src/advanced_inv.cpp
> +++ b/src/advanced_inv.cpp
> @@ -707,7 +707,7 @@ void advanced_inventory::recalc_pane( side p )
>      advanced_inv_area &other = squares[there.get_area()];
>      avatar &player_character = get_avatar();
>      if( pane.container &&
> -        pane.container_base_loc >= AIM_SOUTHWEST && pane.container_base_loc <= AIM_NORTHEAST ) {
> +        pane.container_base_loc >= AIM_SOUTHWEST && pane.container_base_loc <= AIM_ALL ) {
>  
>          const tripoint_rel_ms offset = player_character.pos_bub() - pane.container.pos_bub();
>  
> ```

This indeed works, I'll be pushing a PR shortly.
