### ISSUE TITLE
Can't install more than 2 engines on vehicle but smart vehicle controller user manual states it supports 2 to 5 engines

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70075]
### Describe the bug

I'm not sure whether its a bug that no more than 2 engines can be put onto a vehicle, or if the user manual for the smart vehicle controller should state that it can only control 2 engines. 

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Try to install more than 2 engines on vehicle
2. You can't
3. Look at user manual for smart engine controller
4. It says it can control up to 5 engines

### Expected behavior

1. Allow up to 5 engines on vehicles
2. Change user manual for smart engine controller to state it only accepts a configuration with 2 engines

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/256af6e1-9051-4317-aa65-9bf36a9a7342)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/dfbae898-6cc5-488e-aa51-948880a26458)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Also note this issue might still be worth considering
#66695

**Comment by PatrikLundell** [comment]
It used to be that you needed a Mechanics level of 4 for each engine you installed (and I believe that still holds for the second engine), so you needed level 12 for the third engine. Since then, skills have been capped at 10, resulting in the inability to ever reach the skill level required for the third engine, and I would assume the controller description hasn't been updated to reflect the effective removal of capabilities.

**Comment by Maleclypse** [comment]
Also I think trains which come with more than two engines can use smart controllers, though they have no where to go.  Since vehicles can spawn with more than two engines and a smart controller to manage those engines I'm closing this as completed.
