### ISSUE TITLE
Laser sight description says it has no drawbacks, but examining a weapon with it equipped reveals its actual drawbacks

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70091]
### Describe the bug

The "rail laser sight" and "underbarrel laser sight" descriptions

> A small visible-light laser that mounts on a firearm's accessory rail to enhance ease and speed of target acquisition.  Aside from increased weight, there are no drawbacks.
A visible-light laser that mounts under a firearm's barrel to enhance ease and speed of target acquisition.  Aside from increased weight, there are no drawbacks.

When inspecting a weapon with the laser sight, it states

> Laser sights are invalid when the target position is **too far** or **too bright**.

The laser sights clearly have drawbacks. A player who isn't looking too closely at all the text on the weapon may miss these crucial details. A player would install them and see that it just takes fewer moves to aim. 

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Get either laser sight
2. Note the description
3. Note that attaching it as a mod gives you additional infomation

### Expected behavior

1. The descriptions of laser sights should probably include the drawbacks
2. The notes added to the weapons details list should be colored to green when adding it to the weapon to show that it is being added, Then red-colored when removing it. (or switch the colors, because it is actually a drawback)
3. Both

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by fairyarmadillo** [comment]
That's not a drawback, it just means it confers no benefit in those conditions. The sentence refers to the opportunity cost of installing it, which other than the weight is nil.

**Comment by CoroNaut** [comment]
The description could notify the player that it actually doesn't do anything if the target is too far or too bright. It is hard to spot this detail unless you're looking closely. The aim speed also shows a single value for regular/careful/precise aim speed rather than two aim speeds. One could believe that the benefits are always active. I suppose that's why I consider it a drawback, because I believed it should always be active. In any case, it could be a bit more descriptive.
