### ISSUE TITLE
JSON_FLAGS.md is missing the ammo effects flag documentation it used to have

### ISSUE THREAD

**Issue by LokkiLusca** [CleverRaven/Cataclysm-DDA#70094]
### Describe the bug

While looking for documentation on the flags for the ammo_effects field, I realised that they weren't covered in the docs. I remembered seeing a list of flags for ammo_effects so I checked O.G Gaiman and found the section I was looking for on line 176 of JSON_FLAGS.md. It is possible that this section was accidentally removed during the earlier flag cleanup.

### Attach save file

N/A

### Steps to reproduce

1. Open Notepad++
2. Target the experimental docs folder with find in file and search "INCENDIARY"
3. One hit on page 157 of JSON_FLAGS.md: ```m235``` M235 TPA (66mm Incendiary Rocket)
4. Target the O.G Gaiman docs folder with find in file and search "INCENDIARY"
5. Two hits in JSON_FLAGS.md, one matching the above and also: ```INCENDIARY``` Lights target on fire.

### Expected behavior

Documentation would list flags currently used in the game's json files.

### Versions and configuration

Game version: Experimental 2023-12-09-0836

**Comment by GuardianDll** [comment]
yes, it was removed from json_info since ammo_effects are not flags, but it's own type
