### ISSUE TITLE
Reward training should not take forever and a day

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#70099]
### Is your feature request related to a problem? Please describe.

So my character finished a mission and got offered some training as a reward, great. But if I take that offer, and the character is tired, or weary, or both, the training basically takes forever - one time it took 24 hours, my character getting parched and dead tired in the process. But if I cancel the training, the reward is (partially?) gone.

### Solution you would like.

Training sessions should have a fixed time frame, like an hour or so. Sure, some characters will then learn more than others, but that is how it works in real life too, right?

### Additional context

Having a fixed time frame would also fix the problem of student and teacher finishing their task at different times...

**Comment by 5batek5** [comment]
I think it would be nice if you could stop the training and then continue it from dialog menu without losing progress of it

**Comment by PatrikLundell** [comment]
The basic problem is, in my opinion, that the training rewards are of extremely low value given that it takes forever and gives you extremely little in return. You're probably better of reading a book for the same duration (assuming you have a book, but they can typically train you only on low levels anyway).

The only training worth taking in my opinion is new martial arts, and that's really only for completeness' sake, as I won't actually use these arts.

**Comment by PGR-14** [comment]
> The basic problem is, in my opinion, that the training rewards are of extremely low value given that it takes forever and gives you extremely little in return. You're probably better of reading a book for the same duration (assuming you have a book, but they can typically train you only on low levels anyway).
> The only training worth taking in my opinion is new martial arts, and that's really only for completeness' sake, as I won't actually use these arts.

But what about in the Refugee center w/ that welder lady? You pay some merch & it takes time to get the proficiency

**Comment by BaumgeistOne** [comment]
Reading a book only gives theoretical knowledge, while training gives practical knowledge. I would not classify that as useless.
