### ISSUE TITLE
Vehicles can spawn overlapped on each other and interacting with them doesn't work the way you expect

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70093]
### Describe the bug

Looking at the pictures, there are technically 3 different vehicles here and they overlap each other. If I try to interact with some of the tiles that contain the parts of 2 vehicles, it may or may not select the other vehicle when interacting (installing or removing parts). This leads to you not actually knowing what vehicle you are modifying.

### Attach save file

[Lenora-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13623791/Lenora-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Examine the "Military cargo truck" immediately in front of the player
3. Attempt to remove the "vehicle tank (60L) (25.3L JP8 fuel)"
4. Wait until the operation is completed
5. You will get the message in the log "You do not meet the requirements to remove the military composite armor plating"
6. Note that the military composite armor plating doesn't exist on the vehicle tile you selected on the "Military cargo truck". The military composite plating is on the front-end of the humvee vehicle.

### Expected behavior

1. Disallow multiple vehicles to spawn overtop of eachother
2. Ensure that the game knows what part you are trying to remove.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/2b6bebba-7226-4959-930e-d2395087168a)

There are technically 3 vehicles here. First picture is the humvee front. Second picture is the cargo truck I am trying to remove the fuel tank from. The third picture is the back-end of the humvee.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/fd1ac6a4-f548-404f-a249-205e1de7c744)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/cdbbd661-a5e1-43bd-a239-9c6fa7bde111)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/b3061d00-7575-48fc-a795-c602baf9e198)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Procyonae** [comment]
Spawning vehicles on top of each other is intentional and definitely shouldn't be prevented, the game handles 2 intersecting vehicles better than 3 but the whole system could do with a look over by someone C++ competent

**Comment by CoroNaut** [comment]
Gotcha, 2 vehicles spawning ontop of eachother is intentional. How exactly is someone able to select one vehicle or the other? There are 2 vehicles, but examining the tile just picks one vehicle. There is no way to specify which vehicle as far as I know. If there really isn't a way, that should probably be made into another issue.

This issue then would be specifically that the game doesn't know what vehicle you are actually operating on.

**Comment by Procyonae** [comment]
Ye where they overlap it should destroy one of the two vehicles tiles and leave some bash yields ideally, it used to be they'd just form one big wreck that was it's own singular "vehicle" I forget why/when that got changed tho

**Comment by CoroNaut** [comment]
I remember that being the case as well, both vehicles being a merged vehicle. In this case, I was actually able to grab the front-end of the humvee and move it around a little inside the military cargo truck. I'm not sure if the code was ignoring the fact that two vehicles were occupying a lot of the same tiles, or if vehicles can be _ontop_ of other vehicles.

**Comment by RDru** [comment]
I have exactly the same vehicles on my save. I have no idea about making locations in CDDA but maybe the problem is not random spawns on each other?
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/26722636/d55fcf41-1288-45a4-bafb-d57ee4d26a94)

**Comment by Procyonae** [comment]
Which map is that, I can check it's not doing anything weird

**Comment by RDru** [comment]
It's military base entrance

**Comment by Procyonae** [comment]
That placement seems conventional
