### ISSUE TITLE
Hammerhand Psychic Spell Cannot Be Toggled Off And Stacks Consecutively (Mind Over Matter)

### ISSUE THREAD

**Issue by Lyrcanrolf** [CleverRaven/Cataclysm-DDA#70092]
### Describe the bug

The Hammerhand spell from Mind Over Matter cannot be toggled off using either the Stop Concentrating spell or using the Hammerhand spell again which causes consecutive uses of the spell to stack hammerhand items in the inventory, leading to multiple hammerhand items in one character.

### Attach save file

[Encinal-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13623540/Encinal-trimmed.tar.gz)

### Steps to reproduce

1. Open the spell menu
2. Cast the hammerhand spell
3. Attempt to toggle the Hammerhand spell off by casting the spell again or using the Stop Concentrating Spell
4. The hammerhand item does not disappear.
5. Using the Hammerhand spell again causes a duplicate hammerhand to stack itself.

### Expected behavior

The hammerhand item should disappear from inventory after toggling it off using either of the two methods, and not stack itself after repeated castings of the spell.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/143777503/c5ba9711-9498-462a-84bd-ace596cc1b37)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3693 (21H2)
- Game Version: f971570 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter]
]

**Comment by Standing-Storm** [comment]
This was fixed in #70059--just update and it should work properly.
