### ISSUE TITLE
Error when trying to use an item attached to a mounted workshop to repair something

### ISSUE THREAD

**Issue by RDru** [CleverRaven/Cataclysm-DDA#70109]
### Describe the bug

Both soldering iron and welding tools cannot be used anymore for repairs when they are in mounted workshop.
Might be cause by #69965 ?

 DEBUG    : tried to put an item (null) count (1) in a container (soldering_iron) that cannot contain it: pocket with type (MAGAZINE_WELL) not found

 FUNCTION : put_in
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1622
 VERSION  : 62ec12d

### Attach save file

[Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13625565/Earth-trimmed.tar.gz)

### Steps to reproduce

1. Select mounted workshop in vehicle
2. Select soldering iron
3. Select repair

### Expected behavior

Mounted tools can be used to repair.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 62ec12d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills]
]

**Comment by Terrorforge** [comment]
Can confirm. I've been having this problem with a soldering iron and a high-tempersture welding kit.

**Comment by redcrate** [comment]
can also confirm, does not seem to cause an issie when disassembling or using with a recipe, only when activated for a repair
