### ISSUE TITLE
The Wield item screen doesn't display items in hidden pockets

### ISSUE THREAD

**Issue by waxcatape** [CleverRaven/Cataclysm-DDA#70106]
### Describe the bug

The wield screen doesn't show items in hidden pockets. This is inconsistent with the use screen, the wear screen, the reload screen. It also means that if you have e.g. a load bearing vest with mag pouches with mags in them and a tactical holster with a gun, you have to keep the contents of the vest unhidden to use the wield menu on the gun. Which means cluttering the inventory screen with mags.

### Attach save file

N/A, should be trivially reproducible.

### Steps to reproduce

1. Spawn a player wearing a load bearing vest with a tactical holster and a chest ammo pouch attached.
2. Put some magazines in the pouch and a gun in the holster.
3. Hide the contents of the vest.
4. Press `w` to show the wield screen and confirm that the gun isn't there. 

### Expected behavior

The wield screen should behave the same as the wear screen, the reload screen or the use screen.

### Versions and configuration

- OS : Linux 6.5.11 (Guix System)
- Game Version: c435321
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, MA, bombastic_perks, translate_dialogue, speedydex,  StatsThroughSkills

**Comment by andrei8l** [comment]
Can't reproduce. Did you maybe force hide all pockets (red chevrons)? A save file would help

[output.webm](https://github.com/CleverRaven/Cataclysm-DDA/assets/68240139/d2f0bd03-c327-480f-a535-bc222f4f13a6)

**Comment by waxcatape** [comment]
> Can't reproduce. Did you maybe force hide all pockets (red chevrons)? A save file would help

It is reproduced in your post. You had to unhide the contents of the pocket to see/wield the gun. This also unhides the mag, which persists after the item was wielded. Now that I look at it closely, I think it's intended behavior and not a bug, because you can wield anything whereas wearing, using or reloading are limited only to some items. I was too cavalier about opening this issue, sorry
