### ISSUE TITLE
Too many weapons were pruned from martial arts styles

### ISSUE THREAD

**Issue by Malorn-Deslor** [CleverRaven/Cataclysm-DDA#70110]
### Is your feature request related to a problem? Please describe.

PR #68582 had many good points, but it went too far. While I do agree with the reasoning that a blunt sword would not cut the way an edged blade would...the example was cherry-picked from fencing. So I'll cherry-pick an example on the reverse, the 2-by-sword. 

First, many martial arts skills are not direct strikes: blocking and positioning would not be effected by a lack of edge, as HEMA would provide apt examples. Even fencing has parrying, which the sharp point has no influence on. So not being able to use all those abilities is just as inaccurate, merely in a restrictive rather than permissive way.

Second, again not including fencing, the difference isn't so great. If you deliver a proper HEMA thrust with a sharpened piece of wood, it will hurt like hell. Far less effective than metal, but still will hurt. Moreover, keep in mind HEMA was created to fight armored opponents, so the thrust not 'penetrating' is something the martial art training is designed to handle. Same with slashing, against an armored target you do not cut 'through' people, no matter what Hollywood would have you believe, and thus a hit with a blunted weapon would behave no differently than an edged hit, except in terms of the damage done.

BTW, even with fencing, I'm pretty sure I could sharpen a car antenna and make use of a fair bit of the abilities of an average fencer, improvised weapons do not entirely negate whole martial arts.

### Solution you would like.

I think being more careful WHICH weapons can be used is a good thing, removing all of them except 'real swords' is too far. Styles are adaptable, humans are not robots preforming preprogrammed actions. Also, a huge amount of the training is done with blunted weapons against human opponents, meaning that while the damage of edged versus non-edged would differ drastically, the technique would not.

I suggest we revert some of the over-zealous removals, since it is highly unrealistic that assume that only historical-grade replicas would be useful with such training. Maybe take a good look at the damage some of those 'fake' weapons do, since I agree the resulting damage of an edged weapon versus blunt differ quite a bit, a real edged blade should be a major improvement over a piece of wood.

I do understand the desire to not 

### Describe alternatives you have considered.

In theory, we could try making all the defensive abilities work with blunt weapons, while preventing offensive techniques, but that is beyond my ability to code and would require a rewrite of how styles work.

Another way would be add some sort of tag to such unsuitable weapons which made the styles less effective, while still usable. Basically right now, using a properly weighted but blunt practice blade, your character is assumed to be unable to use ANY of the knowledge or skill they gained by practicing with the exact same blunt blade.

### Additional context

Just on a further note of realism, the real problem all of our HEMA folks would encounter is that they have not been training with live blades or real combat. A point-based system does not account for a lot of real-world factors, and many HEMA groups have a serious problem with 'light' touches since they are trying to not break each other. This soft-touch approach creates bad habits if they had to land real blows.

The mere fact they can very easily break bones or open wounds with blunted weapons, however, kinda proves my point. Blunt weapons can be used with such styles very effectively, just not as effectively as edged weapons. Again, I feel like #68582 came out of fencing, since that is where the argument of not having a 'point' is most logical.

**Comment by fairyarmadillo** [comment]
Agreed 100%. People practice with blunt weapons and the techniques are absolutely deadly without a sharp edge, that's why they wear protective gear in kendo and HEMA.

**Comment by TheSaddestGoomba** [comment]
As someone that practices HEMA, I second this. The 2-by-sword is essentially a wooden waster. You can perform all the same techniques (there are exceptions but everything I can think of is only relevant for steel on steel, that is, against another sword). They may be less effective but I believe that's mostly represented by the weapon damage values.

On that topic, I've considered adding nylon wasters (much more common than wood in my experience) and steel blunts as rare item spawns.

**Comment by Malorn-Deslor** [comment]
> As someone that practices HEMA, I second this. The 2-by-sword is essentially a wooden waster. You can perform all the same techniques (there are exceptions but everything I can think of is only relevant for steel on steel, that is, against another sword). They may be less effective but I believe that's mostly represented by the weapon damage values.
> 
> On that topic, I've considered adding nylon wasters (much more common than wood in my experience) and steel blunts as rare item spawns.

Yeah, I didn't mention the lack of bind since it would be insanely niche in CDDA, but obviously that is one of the huge differences.

**Comment by Consoleable** [comment]
I agree with this as well, martial arts in cdda usually either add defensive techniques, or modify the weapon damage based on some factor of the weapon. Whether or not a martial art can be used with a weapon should really depend on the shape/weight of the weapon, and whether it's "close enough" to the intended weapons, since the weapon's stats are going to mitigate the usefulness of the martial art if its the right shape but blunt or shitty steel or something. Most martial arts train with blunt/wood versions of weapons anyway.

**Comment by Malorn-Deslor** [comment]
I'm going to start putting a PR together, feel free to help me find more weapons that might need to be added back in, so far I'm only seeing the wooden training ones, but it's entirely possible I am missing others.

**Comment by Malorn-Deslor** [comment]
Resolved by #70367

**Comment by Malorn-Deslor** [comment]
Resolved by https://github.com/CleverRaven/Cataclysm-DDA/pull/70367
