### ISSUE TITLE
[Android] Incomplete indication of disabled skill

### ISSUE THREAD

**Issue by gcmartinelli** [CleverRaven/Cataclysm-DDA#70118]
### Describe the bug

On the Android version, when a skill is disabled it is not mentioned on the skill description box like it happens on the PC version.

### Attach save file

- save file is inconsequential

### Steps to reproduce

- Go into the character sheet ('@')
- Go to the skills panel
- Disable a skill
- Read the description of the skill

### Expected behavior

The phrase **Learning is disabled** should appear in the skill description box for disabled skills. Especially because the shortcut bar makes it hard to see if the skill is light/dark blue.

### Screenshots

![Screenshot_20231209_215500_Cataclysm DDA (experimental)](https://github.com/CleverRaven/Cataclysm-DDA/assets/1650735/1ab1d311-8a72-4590-be68-ea3f81cacd8b)
Android version

![Screenshot 2023-12-09 214653](https://github.com/CleverRaven/Cataclysm-DDA/assets/1650735/0673a455-0edc-481c-9532-ffca3c6c6de2)
PC version

### Versions and configuration

Android: (latest as of 9/Dec/2023) 5194774
PC: 7773670

**Comment by ZhilkinSerg** [comment]
If you are comparing different versions from different OS - please don't. Use APK for same version as you use for PC from releases page - https://github.com/CleverRaven/Cataclysm-DDA/releases.

Though in current case it could be just a screen size issue.

**Comment by gcmartinelli** [comment]
Appologies @ZhilkinSerg; I am not aware how the codebases work and if version numbers are the same. I just went from the assumption that using both the latest version of the Android app (experimental APK) would mean that it is up to date with the latest PC version as well.

**Comment by ZhilkinSerg** [comment]
Binaries for all platforms have same version number.

You are just using latest playstore version which is not the same as the latest version.
