### ISSUE TITLE
Autotraveling on bridges take an inordinate amount of time for the game to process pathfinding.

### ISSUE THREAD

**Issue by Lyrcanrolf** [CleverRaven/Cataclysm-DDA#70113]
### Describe the bug

Attempting to autotravel on an area which would require crossing a bridge causes the game to take a long time to process the pathfinding, accompanied by the 'hang on a bit' message which takes roughly a few minutes for my computer.

### Attach save file

[Encinal-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13625923/Encinal-trimmed.tar.gz)

### Steps to reproduce

1. Open map
2. Attempt autotravel on the cursor location, attached below is the screenshot where the cursor needs to be
3. Map is now stuck at the 'hang on a bit' message

### Expected behavior

Autotravel pathfinding should not take more than a few seconds to process, especially when the area is only a few overmap tiles away from player location.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/143777503/94eaada3-d3f6-4bbb-bd1f-46048911acb0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3693 (21H2)
- Game Version: 3bc7e4f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter]
]

**Comment by Yobrocharlie** [comment]
Must be a mod you’re running champ I don’t get this issue as an experimental vanilla player.
