### ISSUE TITLE
[Android] Make the initial settings available to edit after the initial setup

### ISSUE THREAD

**Issue by gcmartinelli** [CleverRaven/Cataclysm-DDA#70119]
### Is your feature request related to a problem? Please describe.

When you start the game for the first time on Android you are given the following menu:

- [ ] Software rendering
- [ ] Force fullscreen
- [ ] Trap Back Button
- [ ] Native Android UI menus

These options cannot be edited later. 

I argue they should be editable to make it easier for the user to find the best combination on their device.

### Solution you would like.

Make all Android settings editable after the initial configuration.

### Describe alternatives you have considered.

Make all Android settings editable after the initial configuration.

**Comment by Zireael07** [comment]
I'd say this is an accessibility issue so should be exempt from the stalebot

**Comment by Zireael07** [comment]
Again, this is an accessibility issue so should be exempt from stalebot!

**Comment by Zireael07** [comment]
see above!

**Comment by Zireael07** [comment]
Accessibility issues were supposed to be exempt from stalebot
