### ISSUE TITLE
MOLLE pockets being deleted

### ISSUE THREAD

**Issue by jonathan-ng** [CleverRaven/Cataclysm-DDA#70121]
### Describe the bug

Pockets added by MOLLE attachments are being deleted along with their items when an item stored inside the MOLLE item is wielded. 

After this happens, detaching and reattaching the MOLLE attachment does not recreate the pocket.

Saving and reloading seems to reset normal behavior

### Attach save file

N/A

### Steps to reproduce

1. Spawn a new character.
2. Spawn a MOLLE item (e.g. rucksack)
3. drop the item
4. Spawn a MOLLE attachment (e.g. nylon quiver shows an ammo counter in the item name)
5. activate the rucksack to attach the quiver
6. Wear the rucksack
7. insert any item into the rucksack (e.g. starting smartphone)
8. Wield the item
9. MOLLE items no longer has additional pockets

### Expected behavior

Pockets and their items should not vanish.

### Versions and configuration

- OS: Windows: 64-bit
- Game version: 34e5c09 (tile)
- Mods Loaded: None

**Comment by Terrorforge** [comment]
Presumably related to #70044
