### ISSUE TITLE
circular dependency in alt_map_key

### ISSUE THREAD

**Issue by Musickiller** [CleverRaven/Cataclysm-DDA#70123]
### Describe the bug

Hi! I think the rest of issues happen because of the circ. dep.,  but I've added those too, just in case.

If anything else is needed, please tell!

```
 DEBUG    : (json-error)
Json error: data/mods/alt_map_key/overmap_terrain.json:2�106:5: <color_white><color_cyan>JSON contains circular dependency, this object is discarded</color>

    "copy-from": "basement",
    "sym": "b"
<color_light_red>  },
</color>
   <color_cyan>▲▲▲</color>
  {
    "type": "overmap_terrain",
</color>


 FUNCTION : load_deferred
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\init.cpp
 LINE     : 184
 VERSION  : 1278507
```
---
```
 DEBUG    : (json-error)
Json error: data/mods/alt_map_key/overmap_terrain.json:2�110:17: <color_white><color_cyan>Invalid or misplaced field name "copy-from" in JSON data</color>

    "type": "overmap_terrain",
    "id": "basement_bionic",
<color_light_red>    "copy-from": "basement_bionic",
</color>
               <color_cyan>▲▲▲</color>
    "sym": "b"
  },
</color>


 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 341
 VERSION  : 1278507
```
---
```
 DEBUG    : (json-error)
Json error: data/mods/alt_map_key/overmap_terrain.json:2�109:10: <color_white><color_cyan>Invalid or misplaced field name "id" in JSON data</color>

  {
    "type": "overmap_terrain",
<color_light_red>    "id": "basement_bionic",
</color>
        <color_cyan>▲▲▲</color>
    "copy-from": "basement_bionic",
    "sym": "b"
</color>


 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 341
 VERSION  : 1278507
```

### Attach save file

N/A

### Steps to reproduce

1. start a new game in a world with alt_map_key,
2. the issue happens before character is created during finalization step

### Expected behavior

Expected to load without issues.
Because.. it would be cool.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/10563011/7343d4e8-7edb-4b52-af65-f4facbdf3dc0)

### Versions and configuration

- OS: WIndows 10
- G Version: 2023-12-10-03-25
- Tiles
- Russian
- mods:

**Comment by Achpile** [comment]
Happens to me as well. But since alt map mod last edited like 5-6 years ago (judging by git) - something happened to loading routines. I may only guess, but looks like "copy-from" refers to copy from base game entry, but loading this object tries to copy it from itself
