### ISSUE TITLE
Oops!  deleted some items when updating pockets that were added via toolmods

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#70126]
### Describe the bug

When reloading my small game rifle, this error pops up and ammo is deleted from my inventory
```
 DEBUG    : Oops!  deleted some items when updating pockets that were added via toolmods

 FUNCTION : update_modified_pockets
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_contents.cpp
 LINE     : 1867
 VERSION  : 1278507
```

I have already lost a blindfold, STANAG magazines and my nightvision goggles in a similar fashion.

### Attach save file

[Blue Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13628117/Blue.Springs-trimmed.tar.gz)

### Steps to reproduce

1. load attached save
2. Hold shift+R to reload repeatedly
3. Observe the error message
4. Observe the ammunition missing from the inventory

### Expected behavior

Not delete my ammo

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 1278507 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

First I thought it was #70121, but no molle attachments are deleted as far as I can tell. These three pockets are still attached after the error occurs:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/9b09da36-1f04-4222-a0cf-1796b6030cbf)

which is a shame because it it was that bug, I could just put on a hiking backpack but now I don't know

**Comment by mqrause** [comment]
Best I can tell without testing, it actually is the same as #70121. It's not the attachments themselves that are deleted but just the pockets they add, including their contents.

**Comment by Aism4n** [comment]
Got the same issue. Have to return to previous version before "pockets update" to be able to play with molle on my vest.

**Comment by snipercup** [comment]
> Best I can tell without testing, it actually is the same as #70121. It's not the attachments themselves that are deleted but just the pockets they add, including their contents.

Yeah since the pockets are abstract elements tied to the actual bag items in-game. This would be good because now all I have to do is switch to a hiking backpack or something. I will leave this issue open since I don't have the knowledge to confirm this is the same as #70121

**Comment by redcrate** [comment]
Also have this issue, however I was not able to determine what, if anything, was deleted from my sidearm.
