### ISSUE TITLE
Inserting items into containers gives the wrong weight/volume of transferred items

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70134]
### Describe the bug

Inserting items into containers using the insert command on a container will give you incorrect weight and volume for the transferred items. As far as I'm aware, this error is very recent, probably within the last 7ish days that this bug was introduced.

### Attach save file

[testinggg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13629280/testinggg-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Examine the ammo box in the inventory and use insert command
3. Try to insert the 5.56 NATO ammunition into it and notice wild weight/volume calculations

### Expected behavior

Correct weight/volume calculations.

Moving items into and out of the inventory calculates weight and volume correctly. So I'm wondering if the insert command on containers uses a separate function that is essentially a duplicate of the function that moves items into/out of the inventory. If so, they might be able to be collapsed into one function for easier maintenance?

### Screenshots

Notice weight and volume calculations
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/eecbd521-43b6-419c-9aef-a16166bea8cf)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/657128df-7b98-423b-93af-fefd0bde540c)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ynemo** [comment]
I use advenced inventory. If i have more ammo in stack that can be inserted in ammo box, then it cant be inserted. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/95257169-b18e-4753-a3e4-308ecfd2e2e6)

**Comment by CoroNaut** [comment]
Still an issue as of
- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-07-0110 e398be1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

![image](https://github.com/user-attachments/assets/7631189f-32fd-4c40-918f-4361ba2130c6)
