### ISSUE TITLE
Adv. Inventory View has a remote container functionality

### ISSUE THREAD

**Issue by gcmartinelli** [CleverRaven/Cataclysm-DDA#70130]
### Describe the bug

When accessing containers in the Advanced Inventory, if you move away from the container you can still view/interact with it remotely if you open the remote inventory again.

### Attach save file

[Norfleet-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13628840/Norfleet-trimmed.tar.gz)

### Steps to reproduce

Steps to reproduce using the savefile:
1. Open adv inventory (`/`)
2. Select `scorpion ornamented jacket (poor fit)`
3. Press `c` to enter container view
4. Close the advanced inventory (`ESC`)
5. Move away (at least 2 squares) from the original position
6. Open the adv. inventory again
7. `TAB` to switch over to the other pane
8. Select the `spike` on your own inventory and transfer it to the adv. inventory with `ENTER`
9. You've just teleported the spike to the jacket.

### Expected behavior

I expect to not be able to interact with the remote container at a distance. Neither being able to get/put items inside it nor to see it's contents.

### Versions and configuration

- Game version: 7773670

**Comment by CoroNaut** [comment]
Duplicate #70061

**Comment by RenechCDDA** [comment]
As above, duplicate. Already resolved as of my posting.
