### ISSUE TITLE
Items owned by a faction (i.e. steal-able & trigger theft) cannot be hauled or AIM'd, even with thief mode disabled.

### ISSUE THREAD

**Issue by Zarhon** [CleverRaven/Cataclysm-DDA#70159]
### Describe the bug

I cleared out a Hell's Raiders fortress and found a massive stockpile on items inside the wooden hut. When I tried to haul it, or use Advanced Inventory Management to sort it, I was unable to. 

So long as any item is faction owned (in AIM, marked with a pink '!'), you cannot haul or AIM-move them. Turning off thief mode (and the 'this is stealing!' messages) doesn't change anything. 

The only workaround is to manually pick up every item and drop it, which clears the 'faction owned' property and lets you haul and AIM-manipulate them again.

### Attach save file

N/A

### Steps to reproduce

1. Find any faction-owned item. e.g. items from the dead body of a faction member. Check that the items trigger theft warnings.
2. Turn off theft warnings / disable thief mode.
3. Attempt to haul, autohaul, manually haul/drag, or AIM-move the steal-able items. You will be unable to.
4. Pick up the items manually (triggering theft responses), and drop them again. The item can now be hauled/AIM'd, as it no longer counts as faction-owned or faction property.

### Expected behavior

Being able to use AIM to move steal-able items, when thief mode is disabled. Being able to haul/drag steal-able items when thief mode is disabled. Being able to do either when thief mode is enabled by being warned about it and being asked if you wish to proceed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: fed496b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by PGR-14** [comment]
I think it's intentional, so you don't just haul all of the items out of sight & take them, 'cause they're usually in the NPC's view
