### ISSUE TITLE
Auto features' auto pulp can pulp zombies from large distance if you are interrupted when pulping

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70153]
### Describe the bug

If you start a task like butchering a corpse and get interrupted by safe mode, upon starting another pulping task, your character will try to re-do the previous task regardless of distance. 

### Attach save file

The save for the bug where you pulp from large distances:
[testinggg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13639500/testinggg-trimmed.tar.gz)

### Steps to reproduce

1. Load save 1
2. Set the setting in options "auto pulp or butcher" to "pulp adjacent" and enable auto features
3. Move south such that auto-pulp adjacent will attempt to smash the corpse south of you.
4. Get interrupted by the living zombie scientists and select "Yes" when it asks "The zombie scientist is dangerously close! Stop smashing?"
5. Debug kill the living zombie scientist
6. Move up to the zombie scientist you just debug killed and let auto pulp try to smash it
7. The corpse that you were previously smashing and the most recent zombie corpse are both pulped.

### Expected behavior

You should only be able to smash the corpse you've targeted. If you are interrupted when smashing a corpse, it shouldn't be pulped when you go to pulp the next zombie.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/2227743e-5253-4bd5-ac80-122ce1fb43b6)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/a864e25e-7d13-49ab-bab8-c10403e60507)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/4edb10aa-39ed-4dc1-a2fc-bf2753ed7848)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/91fb69ae-5c6c-432a-9ca7-7a6379f79be3)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/10c22f35-a29f-4da0-ace6-abda1fa3c3fe)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
I've seen similar weird behavior with companions who, when ordered to perform tasks, instead have gone off to continue the task they were performing previously. My work around is to order companions to first stop working and then order them to perform the new task, but that is only useful when I interrupt their task, not when they are seemingly not performing a task currently (such as when they stop their task because my character moves to the same Z level they are at when descending into the evac shelter basement).
