### ISSUE TITLE
Restrain cephalopod tentacle count

### ISSUE THREAD

**Issue by OldFriendEr** [CleverRaven/Cataclysm-DDA#70166]
### Is your feature request related to a problem? Please describe.

Cephalopod mutation tree has a combination of mutations that bother me

Tentacles legs - "Your legs have transformed into six tentacles."
4 Tentacles -> 8 tentacles - "Your arms have transformed into four/eight tentacles"
Mouth tentacles - "A set of tentacles surrounds your mouth"  this one doesn't bother me that much

This leaves me a mutant with 14 limb tentacles. 6 for legs 8 for hands.

### Solution you would like.

I would like to model a post threshold cephalopod mutant to have 8 tentacles. My general proposal is to remove additional hand tentacles, by replacing the flavor text, but keeping the functionality exactly the same or adjust it a bit.

**4 Tentacles** - Your arms have transformed into four tentacles, resulting in a +1 bonus to Dexterity, permanent hand encumbrance of 30, and an inability to wear gloves. You can make up to 3 extra attacks with them. Somewhat decreases wet penalties.

Becomes **Tentacle attunement** Prerequisites Tentacle legs, Tentacle Arms - You got accustomed to move and use your tentacles, You can use your tentacles to perform up to 3 extra attacks with them. No +1 dexterity and encumbrance, because this mutation would not replace tentacle arms.

**8 Tentacles** - Your arms have transformed into eight tentacles, resulting in a +1 bonus to Dexterity, permanent hand encumbrance of 30, and an inability to wear gloves. You can make up to 7 extra attacks with them. Somewhat decreases wet penalties.

Becomes **Tentacle mastery** - a post threshold mutation that replaces **Tentacle attunement** 7 extra attacks sounds unreasonable, because some tentacles are still needed to stand on so  maybe just buff existing 3 extra attacks or give other kind of buff

__

### Describe alternatives you have considered.

Those mutations could just be renamed without any adjustments and just leave 3 and 7 extra attacks or not changed at all because the player is not a real cephalopod 

### Additional context

I would like to work on this idea, i made this issue to gauge feedback and collect alternative ideas. I just really don't like the player mutant having 14 limb tentacles, it feels unnatural (😸). 
Overall I would also love some sort of torso shrinkage mutation too, to completely blur the line between leg and arm tentacles, in my opinion cephalopod should have its tentacles growing from its head, but this issue is not about torso.

**Comment by GuardianDll** [comment]
Limb framework was made, and it works fairly okay - see GASTROPOD_FOOT mutation that replace your legs with one single foot

Changing this pseudolimb mutations to actual limb mutation is a better approach, and actually making you accustom to your mutations is pretty nice and nifty mechanic i want to see

**Comment by OldFriendEr** [comment]
This a good point to rework tentacles to the actual limbs while working on this issue. But my main concern is 14 limbs as opposed to 8

**Comment by GuardianDll** [comment]
oh yeah, 14 is surely too much

**Comment by fairyarmadillo** [comment]
The arm tentacles actually do get pared down to two already when you get tentacle rakes. Venera3's proposed idea is that you will be able to specialize as a melee fighter with bad manipulation using tentacle rakes, or a physically weaker but more nimble multi-armed monster.

Not all cephalopods IRL have eight arms. Squid have eight arms plus two tentacles. Nautiluses can have up to 90. I don't think there's any meaningful reason to lower the cap on cephalopod limbs. It's not an octopus, it's a grotesque amalgamation of the entire cephalopod family plus a guy that was stupid enough to drink the green goo.

**Comment by GuardianDll** [comment]
re: mutation granting attacks, i suppose something like #67883 would be handy to have (which is not in abandoned but desire PR list, oddly)

**Comment by fairyarmadillo** [comment]
Storing bonus techniques in a dynamic list is also something I think bombastickslacks wanted weapons to do, so you could have warhammers bash OR stab per attack, rather than both every time. It would help out a lot, and also allow things like incorporating finger razor attacks into martial arts rather than just making punches somehow cut people.

**Comment by OldFriendEr** [comment]
> The arm tentacles actually do get pared down to two already when you get tentacle rakes.

Just want to note that tentacles arms changes to 4 that changes to 8, but nor 4 nor 8 changes to rakes. 
Rakes only require to have any of the 3 mutations  before it, so one can have 8 tentacle arms and rakes. 

But this is why I opened the issue, maybe this is just me 👌

**Comment by fairyarmadillo** [comment]
> Just want to note that tentacles arms changes to 4 that changes to 8, but nor 4 nor 8 changes to rakes. Rakes only require to have any of the 3 mutations before it, so one can have 8 tentacle arms and rakes.

Ah, my mistake. Well as stated in Venera's limbification proposal, they're intended to be reworked in the way I mentioned, where you're choosing between multiarms and rakes.

I am working through a huge list of mutation changes and will try to address this when I do. One way to go might be to undifferentiate arms and legs for cephalopods entirely, as presumably any limb except for the specialized squid tentacles you get from rakes would be capable of both walking and manipulation.
