### ISSUE TITLE
Simultaneous freezing and blistering  

### ISSUE THREAD

**Issue by DaneEnck** [CleverRaven/Cataclysm-DDA#70162]
### Describe the bug

It is possible for a limb to be cold/freezing and blisteringly hot at the same time.

### Attach save file

[Roachtown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13643487/Roachtown-trimmed.tar.gz)

### Steps to reproduce

1. Enter a freezing area 
2. Wait until character is cold/freezing on limbs
3. Create a high temperature fire (ie napalm)
4. Stand next to fire
Limbs will now be blistering and cold/freezing at the same time

### Expected behavior

Either:
a) The intense heat immediately overrides the cold, inflicting blisters on limbs but removing freezing
b) The intense heat takes time to overcome the intense cold, leaving your limbs freezing but not creating blisters until some time has passed

### Screenshots

![Screenshot 2023-12-11 221900](https://github.com/CleverRaven/Cataclysm-DDA/assets/67198266/9a06da01-06de-4f24-ad0a-95b41ca1d0ba)

### Versions and configuration

windows-tiles-sounds-x64
build 2023-11-28-1605

### Additional context

Conceptually, it would be possible to have a blister wound at the same time as freezing, but that's not what this means; the "blistering" effect means the limb is so hot it's beginning to blister, not that it already has blisters. This is supported by the fact that if you step next to a fire, get the blister effect, then step away, the blister effect disappears.

**Comment by justwillpurchase** [comment]
Confirmed reproducible, I am unsure if this is intended.
