### ISSUE TITLE
Items are deleted from pockets upon performing certain actions

### ISSUE THREAD

**Issue by OrthodoxBoy** [CleverRaven/Cataclysm-DDA#70160]
### Describe the bug

Items are deleted from modular pockets periodically. I'm unsure what exactly triggers this, as it's happened before without reloading a weapon. I suspect it occurs when an item attempts to automatically return to your inventory (i.e. an empty magazine) and is redirected to a pocket (in this case, a high-priority whitelisted pocket). However, I can't be sure of this.

### Attach save file

[Cooperstown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13642386/Cooperstown-trimmed.tar.gz)

### Steps to reproduce

1. Open the attached save file.
2. Wield the H&K MP5A2 that is on the ground.
3. Reload the MP5 & the error occurs, deleting all the items contained in the pockets attached to the Riot Armor Suit.

### Expected behavior

I expected that my items would not be deleted upon reloading my firearm.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/153569023/752ca5fb-26e0-4596-b56d-62d9bd490a74)
_Please note that I have edited out my user path folder as it contains part of my IRL name_

### Versions and configuration

- OS: Windows _(Note: this is Windows 11)_
    - OS Version: 10.0.22631.2792 (23H2)
- Game Version: 869bcf8 [64-bit] _(Note: launching with Catapult launcher)_
- Graphics Version: Tiles
- Game Language: System language [] _(Note: this is English)_
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by GoLoT** [comment]
Reproduced following the steps mentioned.

It seems that the empty magazine is being replaced by a full magazine that is stored in a pocket on the black riot armor. Once the magazine is put inside the weapon and removed from the riot armor, a content update is triggered for the armor that is deleting all pockets not belonging to the base item type (a cleanup for pockets that shouldn't be in the item?).

Pockets of type container that are going to be kept are retrieved from base item type: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L1281-L1283
Pockets are removed if not part of the base item type: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_contents.cpp#L1869

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1606943/75bc4b90-b6c8-4c72-9894-a5c4817c9d4e)

After triggering the armor contents update the pocket contents are removed and the description shows the following but the extra pockets are now gone:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1606943/8736624f-443d-41fe-9a91-0d931cef5aa9)

The incorporated items are creating pockets in: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_group.cpp#L663

It looks like this is a case of the extra pockets feature not being aware of the container updates removing containers not present in the base item and that old code wasn't updated to take the "integrated" pockets into account. Adding the pockets coming from `content->additional_pockets` to the list of containers to be kept should fix the issue.

I'll give that a shot locally.
