### ISSUE TITLE
Radio repeater mod does nothing when interracting with a radio station computer

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70170]
### Describe the bug

Radio repeater mod is obtainable from the "plans for a radio repeater mod" by crafting. If crafted and going to a radio station, the "Install Repeater Mod" selection does nothing. If you don't have it in your inventory, it displays a message saying you don't have a repeater mod.

I've also noticed that it does use in-game time when you select the option to install the repeater mod. So maybe the functionality is broken and doesn't throw any errors?

### Attach save file

N/A trivially reproducible

### Steps to reproduce

1. Go to a radio station with capability to install repeater mod
2. Give yourself a radio repeater mod
3. Try to install radio repeater mod
4. Nothing happens

### Expected behavior

I expect the repeater mod to actually do something.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/50a020e3-60a7-48ba-9ae1-7f68aad37fcd)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by KeremBabaG** [comment]
It seems that actually installing one requires you to have a Necropolis old guard mission that only exists in No Hope. Need to clear this one up or make another mission where you need to install a repeater.
