### ISSUE TITLE
Make it possible to attaching to batteries in the item like form

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#70174]
### Is your feature request related to a problem? Please describe.

You can place car, medium, large, very large etc batteries on the ground and attach items to it, but if will be very helpful and comfortable to have ability to attach to batteries directly. Sometimes you can have battery, but don't have ability to place it
As example, you need yo use your arc welder or some instrument it the car, but you cannot build, while you are in the car, and may be because of lack of dashboard (it can be broken) and in other situation, you should be able to connected to battery
Make it also working with laser guns, it will make it more useful
Or you can have lack of space, but have batterie at your fit at the ground, and it will be good to connect grinder machine or reciprocating saw to eat and cut metal bars 

### Solution you would like.

Make it possible to connect to batteries, like medium and large in the item like form without placing it at the ground

**Comment by MrHrulgin** [comment]
That's what the various battery conversion mods are for. If you want a tool to use a different battery type, you can make that happen.

**Comment by CoroNaut** [comment]
Perhaps instead of placing singular light, medium, heavy (and all the other small variants) batteries, we could instead have a "medium battery bank" that can contain say... 10 light batteries, 5 medium, 2 heavy batteries? I'd hate to have to place _singular_ small batteries to use them. Even placing small batteries on vehicles, its just useless in theory and in practice. Having a central location that can hold a bunch of batteries would be ideal. There could be small, medium, large "battery bank" variants, etc.

Honestly after getting UPS or a proper electrical setup for house or vehicle, these smaller tool batteries become almost useless for the day-to-day. If there was a way to offload them in bulk, it would be a good quality of life upgrade and give purpose to a large pile of small batteries.

**Comment by MrHrulgin** [comment]
@CoroNaut Small batteries can already be combined to make medium batteries, which in turn can be made into large batteries. Likewise with the high-capacity variants. If you have plenty of small batteries, there's ways to make them useful.

**Comment by KHeket** [comment]
> That's what the various battery conversion mods are for. If you want a tool to use a different battery type, you can make that happen.

There is no conversion mods for medium. large and very large batteries, and if you can place battery and connect to it - you can also should be able to do it without placing, it will be realistic, because if you can place battery in your backpack or under your feet - you can connect to it. As example - you can place irl car accumulator on/under the table and connect something to it

> I'd hate to have to place _singular_ small batteries to use them

Its different from mine idea, but, if mine idea will be realized, you can make huge battery storage this way. Reveal wall wiring/place something connectable on the ground (battery as example), and you will be able to connect lots of batteries to it and than store it at any nearby tile. 1000L = 25 large batteries (25L each)

**Comment by CoroNaut** [comment]
I understand that small batteries can be combined. Large batteries however are far too available to the player to warrant crafting all your small batteries into large ones. My suggestion is pretty much about how to make them useful, which, removing their charge in mass would do. Other than that, crafting them into larger batteries isn't really useful, and placing down _singular_ batteries would be tedious.

I kind of like the idea of being able to put tons of small batteries on the same tile and connect them with copper wire. This does introduce a big concern though: [Can I connect batteries of different ampere hours in series?](https://electronics.stackexchange.com/questions/253702/can-i-connect-batteries-of-different-ampere-hours-in-series). 

> Combining batteries which are not the same type and/or model and/or chemistry is always a VERY bad idea.

Thus, my suggestion of making a battery bank. The battery bank would be responsible for converting all the batteries into one form of voltage/amperage, etc. Of course it would need some electronics parts to handle that. We could do with a simpler solution and just have battery chargers that only handle light, medium, heavy batteries separately. Something like this would do:
![71hzqn-lslL _AC_UY654_QL65_](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/45c276b4-cb5f-4af0-a191-62b60eca395a)
