### ISSUE TITLE
Soldering iron roadblock in Innawood

### ISSUE THREAD

**Issue by ExEdit0r** [CleverRaven/Cataclysm-DDA#70179]
### Describe the bug

There is a point in Innawood progression, where you create soldering iron and batteries. However, the current implementation of the Soldering iron can not be reloaded with a battery, it requires a connection to a network. 
Portable soldering iron can not be crafted at that stage, so the player is stuck. 
The only solution to debug create a portable soldering iron. 
A member of Discord said that the recipe hasn't been updated to have the portable soldering iron for innawoods.

### Attach save file

Not required I beleive

### Steps to reproduce

With Innawood and DinoMod on. 
1. Get to the progression stage where soldering Iron can be crafted, but portable can not. 
2. Get stuck 

### Expected behavior

Either being able to reload a soldering iron, or be able to craft a portable one at the same time when a normal one is researched. 

### Screenshots

![SD1](https://github.com/CleverRaven/Cataclysm-DDA/assets/34904013/3b860cb1-34d6-4988-a2ac-43623839d729)
![SD2](https://github.com/CleverRaven/Cataclysm-DDA/assets/34904013/8f02b110-a3fc-496a-894a-29f839e948de)

### Versions and configuration

Experimental 
Build 2023-12-122-1858

Mods:
Innawood
DinoMod
Other default mods

**Comment by evankimori** [comment]
Confirming. Secondary roadblock is that Dry Batteries (Entry level power) cannot be installed into vehicle frames to defray the current Soldering Iron issue stated above either. 

Items are not standalone, constructions or vehicle parts.

**Comment by RenechCDDA** [comment]
I am not able to reproduce this. The clay car battery can be placed just fine, and the regular soldering iron can be attached. Blame shows that the ability to construction-place the clay battery has been there since appliances were added to innawoods..

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/4d8466eb-c79a-4063-a47a-a4f300e8d77e)

@Maleclypse Am I missing something?

**Comment by ExEdit0r** [comment]
@RenechCDDA, hello. 
You need a soldering iron with 10 charges to craft your first clay car battery. 
I am pretty sure I was able to craft disposable batteries, but could not insert them in the soldering iron (since it can not be reloaded, only connected to the grid), and a portable soldering iron (that can be reloaded) was not possible to craft at that stage of the progression.

**Comment by RenechCDDA** [comment]
Is this still an issue after #73347?

**Comment by ExEdit0r** [comment]
> Is this still an issue after #73347?
In the current build (2024-05-08-0737) with Innawood+Dinomod mods you can craft Portable soldering iron when you reach Electronics 2. (normal soldering Iron can be crafter at electronics lvl 1). 
However, it requires 10 charges of soldering iron. So the issue is not fixed. 
![CDDA1](https://github.com/CleverRaven/Cataclysm-DDA/assets/34904013/a6949617-19f9-4c19-aa5c-fceb2d920a06)
![CDDA2](https://github.com/CleverRaven/Cataclysm-DDA/assets/34904013/f498ad65-e53d-4e9f-b7ad-8fe2839f7aab)
