### ISSUE TITLE
Remove welder and vacuum molder from test data #70129 bug

### ISSUE THREAD

**Issue by Severhead** [CleverRaven/Cataclysm-DDA#70191]
### Describe the bug

When creating a "stop cock" the vacuum molder or makeshift vacuum molder requires 2 charges. Batteries have been removed.

### Attach save file

[Stream Twitch backup-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13665268/Stream.Twitch.backup-trimmed.tar.gz)

### Steps to reproduce

Load experimental build 2020-12-13-1434 and attempt to create a stop cock.

### Expected behavior

Charges removed for that recipe and have it become a tool required check.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 3c95a24 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]]

### Additional context

no crash or other issue generated by this bug

**Comment by GuardianDll** [comment]
Not a bug, you should connect it to your grid using plug, battery slot for item was removed

**Comment by Severhead** [comment]
Alrighty then I'll run power out to my shop area then. Thanks for the quick reply.
