### ISSUE TITLE
Rivers should vary in width depending on distance to ocean

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#70204]
### Is your feature request related to a problem? Please describe.

Now we have an actual ocean rivers should be narrower in the west get gradually thicker to the east

### Solution you would like.

A math exposed variable assigned to the 180x180 OM that dictates how wide the rivers on that OM should be

### Describe alternatives you have considered.

Ideally they'd also tend to head for the ocean on a macro scale
Ideally rivers would have independent sizes modified by how far from the ocean and able to combine with intersecting rivers rather than forming waterworld esque nightmares like they currently can
The width could be controlled at a smaller scale than OM (like 3 different widths for the bank tiles) which should be doable in future if however this is incorporated is exposed to JSON math once I get around to unhardcoding river maps.
Estuary gen would be cool but I'd rather see #38894 revved first (pls someone, anyone)

**Comment by PatrikLundell** [comment]
Distance from the ocean shouldn't set the river width, but rather the maximum river width. Small water ways should exist everywhere, and the river width should really depend on how large an area is acts as a runoff for (given the constant humidity and fog, there shouldn't be any significant loss of water due to evaporation).

**Comment by Procyonae** [comment]
> Distance from the ocean shouldn't set the river width, but rather the maximum river width.

From a realism perspective yes but currently width isn't maintained across map boundaries (the only reason #38894 wasn't merged was they wanted to fix that too as far as I can tell), meaning if you make it a roll the size could fluctuate dramatically between the boundaries, this is an easier in between until someone figures that out
