### ISSUE TITLE
Software Rendering on Android causes the game to take around five times longer to load than without

### ISSUE THREAD

**Issue by Empyrean-Heaven** [CleverRaven/Cataclysm-DDA#70203]
### Describe the bug

So, some background info. This "bug" was extant all the way back in 0.E and may even go further behind the times. The bug itself is simple. If you load a world with Software Rendering on using Android, it takes a significantly long time to boot up the world. Compare this to loading without Software Rendering, and it is a monumental difference. (Quick side note: I thought this was normal behavior but harakka on Discord claimed that shouldn't be the case.) I daresay a five to ten times increase in load time occurs. I play on Android x32. Not sure if it happens on the x64 versions. I believe the main issue lies in the "Tileset" category when loading, because it stays there for a looooong time.

### Attach save file

N/A

### Steps to reproduce

1. Download the game on Android.
2. Create a basic world. As little bloat as possible.
3. Turn on Software Rendering and boot up the world. Witness it taking ages!
4. Turn off Software Rendering and boot up the world. It takes way less time.

### Expected behavior

Apparently there should be very little difference.

### Versions and configuration

Android x32

### Additional context

Some more things to note on the Android version that I am not sure are bugs: switching tabs in the recipe menu has a little lag in-between. Choosing the Reading hobby causes severe freezing for several moments. This also applies to some other traits. The blue groupings in recipes sometimes lag when going over them. You know, like bandages, etc.

**Comment by ZhilkinSerg** [comment]
Yeah, depending on device enabling software rendering can have negative impact on performance. There is not much we can do - software rendering is more like compatibility issue and should not be normally used.

**Comment by harakka** [comment]
Negative impact on performance is expected, massively inflating load times isn't, especially hanging at the loading tilesets stage. It's possible there's some fairly easy gains there to help people who have to play that way.

**Comment by esotericist** [comment]
> Negative impact on performance is expected, massively inflating load times specifically isn't, especially hanging at the loading tilesets stage. It's possible there's some fairly easy gains there to help people who have to play that way.

all of the things i can think of that could possibly slow down during the tileset loading stage due to renderer type are going to be fairly non-negotiable; we do a LOT of manipulation of the tileset during loading, and if we don't have accelerated operations for them, then yes, that's going to be slowed down.

while i'd love to be wrong, i'm fairly confident that fixing this will almost certainly require either
a) radical redesigns of the renderer (so that we are no longer having to make altered copies of all the tiles at all, or to adjust how atlasing works), or
b) radical redesigns of how we compose tilesets (so that we pre-generate as many of the altered copies of tiles as possible in the tileset itself instead of in the loader, although that could complicate things with e.g. the custom tint options for memory tiles)

**Comment by pwalsh0** [comment]
What platform has android x32 without harwdare acceleration? Every kind of phone has some kind of acceleration, or the UI would be awful. Even the very first generation ones use it.

**Comment by harakka** [comment]
> What platform has android x32 without harwdare acceleration? Every kind of phone has some kind of acceleration, or the UI would be awful. Even the very first generation ones use it.

This isn't a matter of the platform lacking acceleration. There's a long standing graphics issue that mostly shows up on android (#68567) that using software rendering mitigates, which is why people are using it.

**Comment by esotericist** [comment]
we're looking into solutions for that problem, it's just tricky when nobody on the team can reproduce the problem with devices available to them. if we can fix it, we will.
