### ISSUE TITLE
Rolling trash cans spawn in building walls.

### ISSUE THREAD

**Issue by waxcatape** [CleverRaven/Cataclysm-DDA#70223]
### Describe the bug

The new rolling trash can vehicle from #69344 will spawn right in the walls of buildings in cities.

### Attach save file

[Secor-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13679217/Secor-trimmed.tar.gz)

### Steps to reproduce

1. Make a character in a city
2. Look around

### Expected behavior

Rolling trash cans should not spawn in walls.

### Screenshots

https://media.discordapp.net/attachments/598523535169945607/1184998679485100082/screen-1702596053.png?ex=658e0305&is=657b8e05&hm=2e25fdb6438c70521eae64c4daf7e611c11e86961ec12c57bab3e96fa4cafcd3&=&format=webp&quality=lossless&width=1220&height=686

Can't embed here, idk why

### Versions and configuration

OS : Linux 6.5.11 (Guix System)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/0fd10a7d381302ebcb97173354f61cc98548b6d1
Graphics version: Tiles
Ingame language: English
Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, speedydex, StatsThroughSkills

**Comment by MrHrulgin** [comment]
Yeah, I've seen those around as well.

**Comment by Inglonias** [comment]
I've seen this as well. Not a major concern, but something to look into.
