### ISSUE TITLE
Medium-length hair looks bald until you save and reload the game

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#70252]
### Describe the bug

If the player chooses a medium hairstyle (such as medium-length or ponytail) during character creation, tilesets that show hair will instead show the player being bald. This is fixed when saving and reloading the game, or reselecting the hairstyle mutation from the debug menu.

### Attach save file

N/A

### Steps to reproduce

1. Pick a tileset that shows hair, such as Ultica or Chibi_Ultica
2. Create a new character with a medium hairstyle such as medium-length or ponytail
3. When you start the game, you will appear bald.
4. Save and reload the game, the hair will be properly displayed

### Expected behavior

Hair should be shown from gamestart

### Screenshots

character creation
![Screenshot (1783)](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/f3da4ade-ba5c-4982-bffa-f187341d07ee)
character upon gamestart
![Screenshot (1785)](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/84ddf9bd-8705-4c81-b743-2512eeb8dc69)
character upon saving and loading the save
![Screenshot (1786)](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/1b93683c-1a6a-4a0c-8eda-94dfedca82d6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 2ae6aff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context
I think this is somehow caused by #70080 because i never saw this bug until this specific experimental version which added that PR.
_No response_

**Comment by Inglonias** [comment]
That change has since been reverted. Update to the latest experimental and try again?
