### ISSUE TITLE
Cant grab accumulators and solar panels no more

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#70259]
### Describe the bug

You can grab and pull fridges, freezers, forges, lamps and other items and pull it after you, and it works for solar panels and batteries (car, medium, large, very large) but after some update you cannot grab and pull panels and batteries

### Attach save file

N/A

### Steps to reproduce

1) Spawn with debug menu lamp/fridge, place it, grab and pull - you can do it
2) Spawn with debug menu solar panels or batteries (car, medium, large, very large), trying to grab and pull it - you cant do it

### Expected behavior

Be able to grub and pull batteries and panels

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: b37cb38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by kasanryukin** [comment]
Confirmed, issue goes back at least to version 79a8aca

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/8062699/e155c016-8e33-4f07-afa4-99fce8980713)

**Comment by SurFlurer** [comment]
Fixed by  #75397
