### ISSUE TITLE
Defense Mode Merchant is Hungy in a way that is detrimental to fun

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#70277]
### Describe the bug

Whenever the Defense Mode merchant shows up they eat all the food items (that aren't dog or cat food) they have, even vomiting from overeating, in a matter of minutes

### Attach save file

N/A

### Steps to reproduce

1. Install Defense Mode
2. Survive until a merchant arrives
3. Watch as they scarf down all the food they're carrying

### Expected behavior

I expected to be able to buy food that isn't just dog/cat food

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/32277062/071bd461-aacb-4ab0-a210-42c20b428804)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 4482c56 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Defense Mode [defense_mode],
    Bombastic Perks [bombastic_perks],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Yobrocharlie** [comment]
I’m tempted to say that they’re just reloading everything in their inventory

**Comment by pantherpusher** [comment]
Wish they're reload my stomach, my guy's been having sleep for dinner a lot
