### ISSUE TITLE
Invisiblity effect causes all other mob/npcs to disappear.

### ISSUE THREAD

**Issue by sudojones** [CleverRaven/Cataclysm-DDA#70272]
### Describe the bug

Experimental build 2023-12-17-1431 (and 1511); When any ability applies the "invisibility" effect to the player all other npc sprites disappear(I'm not sure if the invisibility effect is being applied to THEM or it's a graphical glitch)

I've tested this with the Cloaking System CBM, magiclysm invisibilty spell and debug/edit player/add effect/invisibility.

I've also tested this issue with multiple tilesets as well as just plain ole' ascii.(the characters that represent the mobs disappear)

I tested version 2023-09-16-0812 and invisibility works as expected. Npcs still visible and lose sight of player.
So something must have changed between 09/16 and now that changed the way the invisibility effect works.

### Attach save file

N/A

### Steps to reproduce

1. Start a game with latest experimental build
2. Do anything that applies the "invisibility" effect

### Expected behavior

Other actors stay visible and merely loose sight of the player.

### Screenshots

**Before Invisible**
![visible](https://github.com/CleverRaven/Cataclysm-DDA/assets/23222783/0513c6a1-85dd-46a5-bfe4-97772374d388)
**After Invisible**
![invisible](https://github.com/CleverRaven/Cataclysm-DDA/assets/23222783/480272b2-e99e-4535-8a67-85acf0438706)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 0f8ac41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    CyberNinja [cyberninja]
]

**Comment by Standing-Storm** [comment]
This would explain why when I spawned in a star vampire a couple days ago to test something else it just wandered around without attacking me. I thought it was some monster faction weirdness but if while invisible it couldn't see me at all, that would explain it too.

**Comment by sudojones** [comment]
> This would explain why when I spawned in a star vampire a couple days ago to test something else it just wandered around without attacking me. I thought it was some monster faction weirdness but if while invisible it couldn't see me at all, that would explain it too.

Yes, invisibility seems to be effecting an entities perception.
But only in the visible spectrum it seems. For instance, if you use infrared vision while invisible, you're able to detect entities that way.

**Comment by andrei8l** [comment]
/confirmed introduced by #70026

This check is backwards
https://github.com/CleverRaven/Cataclysm-DDA/blob/04b6eb249b041653afa14cafd7b897f621100ae3/src/creature.cpp#L388-L390

And I'm pretty sure it's redundant with this one
https://github.com/CleverRaven/Cataclysm-DDA/blob/04b6eb249b041653afa14cafd7b897f621100ae3/src/creature.cpp#L420

unless the intention was to make this monster invisible when adjacent too. In which case it needs a new flag here
https://github.com/CleverRaven/Cataclysm-DDA/blob/04b6eb249b041653afa14cafd7b897f621100ae3/src/creature.cpp#L407

**Comment by Standing-Storm** [comment]
Hmm...why did it work correctly during my testing, then?

**Comment by sudojones** [comment]
The invisibility bug I'm having is happening even without the MoM.
I tested on a new world with only  base CDDA

**Comment by RenechCDDA** [comment]
> The invisibility bug I'm having is happening even without the MoM mod. I tested on a new world with only base CDDA

The code in question runs for all versions of the game, regardless of mods selected.

**Comment by sudojones** [comment]
> > The invisibility bug I'm having is happening even without the MoM mod. I tested on a new world with only base CDDA
> 
> The code in question runs for all versions of the game, regardless of mods selected.

Just realized that after looking at the merge.

I ran a test on a build right before #70026 was merged and invisibility works as expected. 
@andrei8l is right. invisibility bug introduced by #70026.

**Comment by sudojones** [comment]
Fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/70456
