### ISSUE TITLE
Beat Amigara Mine, No Artifact Dropped?

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#70289]
### Describe the bug

Title, killed the horrors, I got the message 'Something spawns near you!' and yet there's nothing nearby. Not sure what's up. I am wearing an artifact robe, if that matters, one that was in fact dropped from one of the same type of mines beforehand.

### Attach save file

[Wooldridge-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13708889/Wooldridge-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

Presumably there should either be an artefact here or a different message if the spawning fails somehow.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53100513/29142f16-5f73-4e9e-8526-22096f428093)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53100513/1e1042e8-2930-4dc5-acbe-c440f2b2e0b3)
No, it's not in the crates.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: de7f85e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by CoroNaut** [comment]
Tried to find artifact from save file, there's no artifacts besides the "royal robe" you are wearing. I'm thinking there was a problem with generating the artifact, the amigara death effect triggered, but no artifact.

**Comment by carlarctg** [comment]
> Tried to find artifact from save file, there's no artifacts besides the "royal robe" you are wearing. I'm thinking there was a problem with generating the artifact, the amigara death effect triggered, but no artifact. I'm guessing the robe is from debug creating an artifact? It would be nice if there was a log entry for the artifact spawning. ![image](https://private-user-images.githubusercontent.com/24307650/291448931-c9b1b1b1-1a60-4bfb-8af4-ebdbd3f7b5a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTY5MTMsIm5iZiI6MTcwMjk5NjYxMywicGF0aCI6Ii8yNDMwNzY1MC8yOTE0NDg5MzEtYzliMWIxYjEtMWE2MC00YmZiLThhZjQtZWJkYmQzZjdiNWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE0MzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0Njg1MmQyMTJkOGRkYjlkZGQxYzQ0YWI3ZTdjZGY0NmRiYmJmNGNkYTgyYzE1ZDMzMDgxMjQxMmI0NmUxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ze-eOJTbXz5YmDwRrGVpXtPiAFAEi1BZ_SH7b17l4vE)

No, the robe was from a previous amigara mine. I was unaware of how logs work so I didn't expect this logdive.

After the artifact failed to spawn, I used debug to try to spawn myself an artifact manually since it didn't work, right before making this bug report. However, when I saw how many prompts there were for variables I didn't know about (how many variables, what type of artifact, etc) I ESC'd out of the artifact spawn with nothing.

**Comment by CoroNaut** [comment]
If you want to spawn an artifact in place of the one you lost, I can give you a rundown:
1. Debug menu->spawning->spawn artifact
2. Choose artifact data: "Netherum_tunnels"
3. Max attributes: "4"
4. Enter power level: "1000"
5. Enter negative power limit: "-1000"
6. It will bring up the look around menu, you can just place it on the floor next to you
7. Is the artifact resonant?: "Yes"
8. And your artifact is spawned, those settings are equivalent to the drop from the amigara mine

As for the missing artifact, it's a mystery to me. I tried 10 amigara mines back to back and they all seemed to work and follow the code properly. Killing the last amigara horror when up the ramp on the level above the "odd fault" will still try to spawn the artifact, but in most cases it should still spawn, unless it spawns in a wall and fail. It will always spawn on the level your character is on.

**Comment by carlarctg** [comment]
> If you want to spawn an artifact in place of the one you lost, I can give you a rundown:
> 
>     1. Debug menu->spawning->spawn artifact
> 
>     2. Choose artifact data: "Netherum_tunnels"
> 
>     3. Max attributes: "4"
> 
>     4. Enter power level: "1000"
> 
>     5. Enter negative power limit: "-1000"
> 
>     6. It will bring up the look around menu, you can just place it on the floor next to you
> 
>     7. Is the artifact resonant?: "Yes"
> 
>     8. And your artifact is spawned, those settings are equivalent to the drop from the amigara mine
> 
> 
> As for the missing artifact, it's a mystery to me. I tried 10 amigara mines back to back and they all seemed to work and follow the code properly. Killing the last amigara horror when up the ramp on the level above the "odd fault" will still try to spawn the artifact, but in most cases it should still spawn, unless it spawns in a wall and fail. It will always spawn on the level your character is on.

Oooh nice, thanks. I guess this issue should be closed if it's non-replicable.

**Comment by Zireael07** [comment]
AFAIK it's an issue that crops up from time to time but never reproduces on demand

**Comment by CoroNaut** [comment]
I'm definitely leaning towards the artifact generation being at fault in this specific circumstance. A bunch of failsafes and debug messages for artifact generation would make this much easier to determine.
