### ISSUE TITLE
啥时候出稳定版？还有营地系统能否继续更新？

### ISSUE THREAD

**Issue by skille111** [CleverRaven/Cataclysm-DDA#70285]
### Is your feature request related to a problem? Please describe.

营地系统能否开放营地与不同势力之间的互动？能否提高营地系统制造效率。

### Solution you would like.

势力互动类似环世界细分，至于效率就可以类似批量生产或营地系统的配方与制造系统挂钩。

### Describe alternatives you have considered.

势力互动可以简化为营地任务，效率简单就是批量操作

### Additional context

希望营地系统能大更以此作为提高后期的内容之一。

**Comment by fairyarmadillo** [comment]
Translated with the help of google translate and ChatGPT as most of our contributors are English-speaking :) Translation isn't perfect but I'll put it here so people can get the gist :

> **Is your feature request related to a problem? Please describe.**
> Can the camp system allow interaction between camps and different factions? Can the manufacturing efficiency of the camp system be improved?
> 
> **Solution you would like.**
> For faction interaction, it could be subdivided similarly to RimWorld. As for efficiency, it could be tied to the camp system's recipe and manufacturing system, perhaps similar to bulk production.
> 
> **Describe alternatives you have considered.**
> Faction interaction could be simplified into camp tasks, and efficiency could be as simple as bulk operations.
> 
> **Additional context**
> I hope the camp system can be expanded upon, serving as one of the improvements for the later stages of the game.

I think Rimworld is a good inspiration. We do have some simulation of interactions between the player's NPCs and other factions with Tacoma, I wonder if we could set up a few quests where the player needs to temporarily donate NPCs to help the various factions out, in exchange for reputation or rewards. We could just copy that infrastructure over, or the bulletin board mission system. Ideas could include cultural exchange with the Exodii, Hub 01 doing medical testing on survivors who aren't stuck in a vault, and guard duty rotations for the refugee center.

To OP: I don't speak Chinese and I'm sorry if this machine translation is wrong, but your suggestions are good. If it will help you, there are also some locations to build a faction camp at where you get extra jobs, such as this one:

给楼主：我不会说中文，如果这个机器翻译有误，我很抱歉，但是你的建议很好。如果对你有帮助，还有一些可以建立派系营地并获得额外任务的地点，比如这个：

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/b2b4cf30-f4c6-4634-ab29-e9853668c0f2)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/e3ce6248-ab09-4604-b0ce-b61e80916ba6)

**Comment by PGR-14** [comment]
Maybe w/ Hub 01, the more mutated the survivors, the more they'll pay, for research of the blob.
The cultural exchange thing could be expanded upon (It's a perfect idea), maybe w/ a new Anthologist NPC (Anglish/Similar language equivalent | Side note here, Maybe it could be like an Ancient Greek scribe?), which would give some fetch quests (I.E. for stuff like the bible, religious clothes, etc. Perhaps w/ a random list?), mail to & from the refugee center (There is an Arabic family there, as well as that Welder NPC, of course after you connect the Exodii w/ the Free Merchants), as well as that NPC trading option for some cash.

Translation for author using google translate:
也许在 Hub 01 中，幸存者变异得越多，他们为研究该团块付出的代价就越多。
文化交流的事情可以扩展（这是一个完美的想法），也许有一个新的选集家 NPC（英语/类似语言等效 | 这里的旁注，也许它可能像古希腊抄写员？），这会带来一些获取任务（即圣经、宗教服装等物品。也许有一个随机列表？），往返于难民中心的邮件（那里有一个阿拉伯家庭，还有那个焊工 NPC，当然在你连接了 Exodii 之后和自由商人），以及 NPC 的一些现金交易选项。

**Comment by skille111** [comment]
我觉得营地系统还可以缝合策略游戏的群战，类似传奇，如果本土化的话可以直接建立一个简单标准，用营地任务系统触发，类似已有的侦察

**Comment by PGR-14** [comment]
Perhaps it could lead to giant battles w/ the Hell's Raiders or other factions, but I've got a few concerns; is the realistic factor really there? The NPCs we have are stupid, & the processing power of most computers isn't there.

Translation:
也许这可能会导致与地狱袭击者或其他派系的大规模战斗，但我有一些担忧；现实因素真的存在吗？我们的 NPC 很愚蠢，而且大多数计算机的处理能力也不具备。
