### ISSUE TITLE
Travelling long distance through water with a boat is a bit of a chore

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#70291]
### Is your feature request related to a problem? Please describe.

Ever tried autodrive on roads/fields vs autodrive on water? water is almost always plagued with more interruptions - partially due to the monster density in water tiles. vs fields and roads which are usually empty, or occasional non-hostile fast monsters that get out of the way quickly (like birds, turkeys, weasles, etc). On water, the small critter monsters (water scorpions, water striders, gooses) are usually hostile, and almost always stop my boat every 3-5 map tiles with "Your about to crash into something!". the worst part? Water collisions dont seem to be modelled with water scorpions anyways, i can press 5 manually and water striders just seem to "teleport" out of the way of the boat, even compared to turkeys and weasles which can be hit by the truck but do very little collision damage to the vehicle.....so why did the game stop the autodrive and warn me about a collision with those creatures? 

### Solution you would like.

-Dont count small creatures that cant be collided with (idk if its a thing with water scorpions or a thing with boats or a thing with vehicles on water tiles) as something that can cancel autodrive

### Describe alternatives you have considered.

-Reducing density of water creatures/commonality of water critter spawns (it seems VERY dense, compared to fields and such)
-ability to set up automatic marking of Danger (like using the R key on a tile when in overmap view) for certain locations

### Additional context

heres a vid showing my issue: i order an automatic drive, it cancels because theres a water scropion infront of the vehicle, but i can just press 5 manually, keep going, and the vehicle doesnt take any damage, infact i dont see any collision messages happening either, so i dont think there was even _any risk_ of damage to the vehicle. https://github.com/CleverRaven/Cataclysm-DDA/assets/19196462/cefa2340-607c-4501-aa5e-323319418d1c

water critter spawn reduction could probably be a seperate issue, but i do think theres a lot more gooses and birds and other such aquatic critter spawns in rivers and lakes then their ought to be. i dont have a source yet but... i mean, im sure someone who lives on rivers and lakes and plays CDDA can look at the river/lake infront of them and see it mostly devoid of geeses and such.

**Comment by CoroNaut** [comment]
Water creatures are talked about a little bit in #70215. I seconded that water creatures out in the middle of the lake provide little game play experience and interrupt travel as you said.

**Comment by Yobrocharlie** [comment]
I Think the density of them is dumb and should be reduced drastically except for along the shore/coastlines
