### ISSUE TITLE
Running [crafting] tests will create files you need to delete

### ISSUE THREAD

**Issue by Kamayana** [CleverRaven/Cataclysm-DDA#70299]
### Is your feature request related to a problem? Please describe.

The test `synthetic_recipe_fail_chances` creates a number of csv files of recipe failure chances. This is fine, but the issue is that this test has the `[synthetic][.][crafting]` tags, so running all [crafting] tests (something I do fairly often if editing crafting-related things) will always create those files, and since they aren't in gitignore they will show as changes and need to be deleted every time.

### Solution you would like.

Either adjusting the tags of `synthetic_recipe_fail_chances` or adding the files it creates to gitignore, preferably the former.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/de5afa70-5680-400c-8780-5409f6bffd72)

**Comment by mqrause** [comment]
It should probably only have `[.]` like some other tests that are only meant for manual execution, `make_vehicle_efficiency_case` for example.
