### ISSUE TITLE
Change first aid properties

### ISSUE THREAD

**Issue by Hypiron** [CleverRaven/Cataclysm-DDA#7029]
I was thinking for a while about other properties of first aid, bandages and so on. What do you think about changing it usage. Maybe instead healing hp right after applying it, it should give you new status, like : dressed [body part] wound. it would heal some hp/time dependable of type of medicaments used and skill i.e. 5hp/h. What do you think about this?
##

**Comment by illi-kun** [comment]
Discussion is continued in #16017.
