### ISSUE TITLE
Zombified Yule Cat corpse provides no dissection education

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70307]
### Describe the bug

If you go to dissect a Zombified Yule Cat, you won't learn anything in the process.

### Attach save file

N/A

### Steps to reproduce

Kill a Zombified Yule Cat, try to dissect.

### Expected behavior

I'd expect to learn at least the basics.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/32fe8389-512d-4caf-b612-b1be81aadb43)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 04b6eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment]
Searching for Yule Cat shows it doesn't exist in data/json, but rather is located in data/mods/Magiclysm/monsters (different files for the monster and the zombefied version).

Add the Magiclysm tag to this issue.

Suggest Magiclysm maintainers audit their monsters to check proficiency families (and possibly weakpoints)

**Comment by Maleclypse** [comment]
I confirmed yule cat is missing them and if I had to guess I'd wager that all the magiclysm monsters are missing weakpoints and proficiencies.
