### ISSUE TITLE
[Bombastic Perks] Guns Affected by the Olde Reliables perk uses generic names

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#70302]
### Is your feature request related to a problem? Please describe.

While Bombastic Perks is loaded, guns that are altered through Bombastic Perks use their generic names, which leads to incongruety if the use gun brand name setting is turned on

### Solution you would like.

Bombastic Perks shouldn't be altering the names of firearms effected by the Olde Reliables Perk

### Describe alternatives you have considered.

tell me to cope i guess?

**Comment by GuardianDll** [comment]
Copy-from do not copy variants? Sound possible
