### ISSUE TITLE
Great Library

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70300]
### Is your feature request related to a problem? Please describe.

Got a quick question, is anyone even working on the library faction?

### Solution you would like.

N/A

**Comment by GuardianDll** [comment]
#69081, but it's stale, and seems related only to it's mapgen

**Comment by PGR-14** [comment]
> Looks like yes. Is there something you want to see? Are you asking if you can work on it?
I'm pretty interested in it, but I'm yet to see any fruit from the tree.
I'm not very good at coding (I have minimal skill, mostly self-taught), but I've got some pretty good ideas on stuff like quests & lore for it.

**Comment by fairyarmadillo** [comment]
You don't need to know any code to write quests, it's all done in json. You can find the files in data/json/npcs. Here's one simple example from /godco/godco_missions:

```
  {
    "id": "MISSION_GODCO_COOK_FOOD_1",
    "type": "mission_definition",
    "name": { "str": "Picky Meals" },
    "description": "Find 20 pounds of salt.",
    "goal": "MGOAL_FIND_ITEM",
    "difficulty": 1,
    "value": 0,
    "item": "salt",
    "count": 2000,
    "origins": [ "ORIGIN_SECONDARY" ],
    "followup": "MISSION_GODCO_COOK_FOOD_2",
    "dialogue": {
      "describe": "I need a supply of salt.",
      "offer": "I know this doesn't sound important, but I am running low on salt.  We don't just need it as a seasoning, it's also vital for food preservation.  Could you find about 20 pounds of salt for me?",
      "accepted": "Don't forget to tell me when you have them.",
      "rejected": "It's okay, I can do without them.  Just let me know if you reconsider.",
      "advice": "There's a lot of places to look.  They are common in house kitchens, restaurants or grocery stores.",
      "inquire": "How is the search going?  Have you found 'em?",
      "success": "I really appreciate your help.  Don't worry, you won't leave empty-handed.",
      "success_lie": "Thanks for trying… I guess.",
      "failure": "Don't worry about it, it's not that important."
    },
    "end": { "effect": [ { "u_spawn_item": "icon", "count": 2 } ] }
  },
```

These few lines contain an entire quest. The originating character wants 2000 units of salt, and rewards the player with 2 icons when they complete the job.  They come from this NPC:

/godco/npcs.json

```
  {
    "type": "npc",
    "id": "godco_chef",
    "name_suffix": "cook",
    "class": "NC_SURVIVOR_CHEF",
    "name_unique": "Simon Weaver",
    "gender": "male",
    "attitude": 0,
    "mission": 7,
    "chat": "TALK_GODCO_chef",
    "mission_offered": "MISSION_GODCO_COOK_FOOD_1",
    "faction": "gods_community"
  },
```

/npcs/godco/members/cook.json contains all of this character's other dialog. /json/mapgen/godco/church_retreat.json places him on a specific map for the player to find. These four files are basically all you would need to know to make a similar NPC with similar content.

All documentation needed to understand the json fields is located here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md

You can get more complex by using EOCs, but I don't recommend trying this until you've done some simpler stuff: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md

**Comment by PGR-14** [comment]
I mean, you probably need an actual building & planning before starting out making them, & the great library project tab is almost barren of planning, that being said, shouldn't someone start on working on it? The only thing there is the bare minimum of a frame (If you can call it that) for the college

**Comment by PGR-14** [comment]
> Is there any documentation on the faction? I didn't see any in the design docs last I checked. I've only pieced together what I know from mentions here and there. I have some thoughts for a wildlife researcher NPC that could intersect in the future.

Side note here, I was thinking of some type of anthologist NPC (Based off of some dude's idea from #70285) in either the college or Exodii faction (Maybe both?) where they have the player get stuff like bibles or traditional garments (Maybe if you're something like a Priest or a Rabbi, you get special dialogue telling them about your religion?).

**Comment by GuardianDll** [comment]
We already have a whole church

**Comment by RenechCDDA** [comment]
There are other avenues to ask questions about development, github's issues page is not one of them. Please do not do this again.
