### ISSUE TITLE
Can remove bionic fuel storage via interacting with a pet

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#70303]
### Describe the bug

Integrated bionic storage spaces (such as one from Ethanol Burner CBM) can be removed by attaching it to a pet.

### Attach save file

None applicable

### Steps to reproduce

1. Gain debug bionic installation
2. Obtain Ethanol burner bionic, dog food, and a dog
3. Install the bionic and tame the dog
4. Interact with the pet and choose "attach bag to pet," then select your ethanol compartment
5. Optionally detach the bag from the pet to obtain the bionic storage as an item form

### Expected behavior

Bionic storage "clothing" cannot be taken off under any circumstance.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 23046RP50C; Release: 13; Incremental: V14.0.9.0.TMYCNXM; 
- Game Version: 79a8aca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries]
]

**Comment by RenechCDDA** [comment]
Whoops.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/4d8c58d4-d6bd-471c-8551-e8fb5203737c)

attach_bag_to(link below) needs to remove invalid items from the listing

https://github.com/CleverRaven/Cataclysm-DDA/blob/132c285d6df0a523c2ee8a32751f747da652934b/src/monexamine.cpp#L176-L212

This can be done with a check against the `INTEGRATED` flag.

**Comment by PerfectlyInternal** [comment]
Just opened a PR that resolves this issue
