### ISSUE TITLE
CONSUMES_RUNES causes error

### ISSUE THREAD

**Issue by OtherBiscuit** [CleverRaven/Cataclysm-DDA#70311]
### Describe the bug

Debug Text:
` DEBUG    : Error: Json error: data/mods/Magiclysm/Spells/animist.json:45:57: <color_white><color_cyan>invalid flags: "CONSUMES_RUNES"</color>

    "components": "spell_components_rune_animist",
    "base_casting_time": 500,
<color_light_red>    "flags": [ "SOMATIC", "VERBAL", "SILENT", "NO_LEGS", "CONSUMES_RUNES" ],</color>
                                                       <color_cyan>▲▲▲</color>
    "difficulty": 3
  },
</color>

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 974
 VERSION  : b2cb811
`

Unknown what caused this, updated to latest experimental and the files I've changed don't involve anything with the flag or runes at all.

Error occurs when the game tries to load character creation in a world with Magiclysm installed.

### Attach save file

N/A; Game does not load

### Steps to reproduce

1. Run Catapult
2. Run Cataclysm:DDA
3. Make a world with Magiclysm installed
4. Attempt to load character creation
5. Error

### Expected behavior

Given that I didn't alter any code involving runes or flags, I expected character creation to load at least.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: b2cb811 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
Magiclysm not present in loaded Mods as the game cannot pass the loading stage.

### Additional context

When this all started, I has been editing code for some future contributions. I imported the changes to test and this error appeared.

I tried loading my original Magiclysm folder but the same error came up; I'm assuming it doesn't have anything to do with edits.

**Comment by ZhilkinSerg** [comment]
Is it reproducible on a fresh install w/o you messing with any of the files?

**Comment by OtherBiscuit** [comment]
> Is it reproducible on a fresh install w/o you messing with any of the files?

Yep, tried that as well. Nothing on my end, may just be a me thing.

**Comment by OtherBiscuit** [comment]
NEVERMIND. Tried again and it worked. FML
