### ISSUE TITLE
Change NPC class definitions to primarily use the same professions as players

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#70310]
### Is your feature request related to a problem? Please describe.

There's an increasingly unnecessary dichotomy in how NPCs and players are defined. We can probably unify this code a lot, and in the process, make random NPCs a little more interesting (maybe?)

For example, this is the code for the npc "DOCTOR" class:
```json
  {
    "type": "npc_class",
    "id": "NC_DOCTOR",
    "name": { "str": "Doctor" },
    "job_description": "I'm looking for wounded to help.",
    "traits": [ { "group": "BG_survival_story_MEDICAL" }, { "group": "NPC_starting_traits" }, { "group": "Appearance_demographics" } ],
    "bonus_str": { "rng": [ -2, 0 ] },
    "bonus_int": { "rng": [ 0, 2 ] },
    "bonus_per": { "rng": [ 0, 2 ] },
    "shopkeeper_item_group": "NC_DOCTOR_misc",
    "proficiencies": [
      "prof_intro_chemistry",
      "prof_intro_biology",
      "prof_wound_care",
      "prof_wound_care_expert",
      "prof_burn_care",
      "prof_dissect_humans",
      "prof_physiology"
    ],
    "skills": [
      { "skill": "ALL", "level": { "mul": [ { "one_in": 3 }, { "sum": [ { "dice": [ 3, 2 ] }, { "rng": [ -1, -3 ] } ] } ] } },
      { "skill": "chemistry", "bonus": { "rng": [ 1, 3 ] } },
      { "skill": "dodge", "bonus": 1 },
      { "skill": "firstaid", "bonus": { "rng": [ 2, 6 ] } },
      { "skill": "speech", "bonus": { "sum": [ { "dice": [ 3, 2 ] }, { "constant": -2 } ] } }
    ]
  },
```

This is the code for the player "medical resident" profession:
```
  {
    "type": "profession",
    "id": "medic",
    "name": "Medical Resident",
    "description": "Fresh out of med school, you've got little in the way of practical experience and just a handful of first-aid supplies.  You just hope it will be enough if 'physician, heal thyself' turns out to be more literal than you expected.",
    "points": 2,
    "skills": [ { "level": 5, "name": "firstaid" } ],
    "proficiencies": [
      "prof_wound_care",
      "prof_wound_care_expert",
      "prof_intro_biology",
      "prof_physiology",
      "prof_burn_care",
      "prof_dissect_humans"
    ],
    "traits": [ "PROF_MED" ],
    "items": {
      "both": {
        "items": [
          "dress_shirt",
          "gloves_medical",
          "socks",
          "dress_shoes",
          "coat_lab",
          "badge_doctor",
          "glasses_safety",
          "wristwatch",
          "water_clean",
          { "item": "bandages", "count": 3 },
          { "item": "adhesive_bandages", "count": 10 },
          "aspirin",
          "stethoscope"
        ],
        "entries": [ { "item": "pants", "variant": "pants_blue" }, { "group": "charged_smart_phone" }, { "group": "full_1st_aid" } ]
      },
      "male": [ "boxer_shorts" ],
      "female": [ "bra", "panties" ]
    }
  },
```

There are also item groups specially designed to go with the NC_DOCTOR class, analogous to the equipment the player starts with.

These specify almost exactly the same information, we really don't need to be treating them as two things.

### Solution you would like.

We should change NPC class definitions to accept professions as an argument, and remove their hard coded itemgroups to instead use the ones offered by professions.

In the process, professions should gain an attribute, `player_usable` or something, which if false means they never show up in chargen and can only be selected by NPCs.

A new NPC class definition might look like this:
```json

  {
    "type": "npc_class",
    "id": "NC_DOCTOR",
    "name": { "str": "Doctor" },
    "job_description": "I'm looking for wounded to help.",
    "traits": [ { "group": "BG_survival_story_MEDICAL" }, { "group": "NPC_starting_traits" }, { "group": "Appearance_demographics" } ],
    "base_professions": [ "medic", "NPC_starting_skills", "NPC_science_type" ],
    "random_professions": {
        "count": [ 3, 5 ],
        "list": [ "some_hobby", "some_other_hobby", "you_get_it" ]
    },
    "bonus_str": { "rng": [ -2, 0 ] },
    "bonus_int": { "rng": [ 0, 2 ] },
    "bonus_per": { "rng": [ 0, 2 ] }
  },
```

In this example, when the game gives an NPC the NC_DOCTOR class, they always then get the stuff in the `medic`, `NPC_starting_skills`, and `NPC_science_type` professions. The latter two would offer the basic sets of skills we expect all doctors to get. Then we pick 3-5 additional random professions from a specified list of options, giving the NPC some backgrounds and their associated proficiencies and skills. There should also be an option to let them randomly select from any possible hobby, and that should be the default.

We no longer randomly adjust skills (or we don't do it as much) although the option is still there for fine tuning, esp for custom NPCs.

this would help future-proof NPCs a lot, in that we'd be using the same profession building blocks  as players. Now we only have to keep them up to date in one spot. This helps to limit the problems I spotted in #67734, which had been present a long time, where NPCs might be missing key skills and proficiencies. It also just makes NPC building more rational, I think.

### Describe alternatives you have considered.

* We don't have to do this at all. The current system works all right. If this is too much work, we shouldn't do it.
* We could use more ways to assign random professions to NPCs, like "choose 0-2 from this list and another 1-2 from this other list" or something.
    * we could also use some better ways to weight items in the list; overall, a recreation of the trait_group structure but for professions would be the ideal dream.

**Comment by RenechCDDA** [comment]
Yeah, I think profession loading could replace large chunks of class definition.

One potential pitfall I see is that it adds another layer of searching. "Oh this NPC has a weird item, let me go look up why" ---> you go to a file to find the NPC's template ---> you go to another file to find the class --> you go to another file to find the profession ---> you go to another file to find the item group ---> you go to another file to find the *nested* item group... It can get nasty real quick.

I think this is mostly a hierarchical question, which is figuring out and clearly marking what should be defined by professions and what should be defined by not-professions. Something to keep in mind is that npc classes, especially in terms of *items*, are way different than most player professions. If the end result of this change would be that we have two piles of professions, one labeled "professions to give to ONLY NPCs" and one labeled "professions to give to ONLY players" (because e.g. the required items are so different), then we didn't accomplish anything useful. 

To be useful the end result needs to meaningfully unify professions as a means of determining some starting values between the player and the NPCs. But *which* starting values? Traits? Stats? Skills? Proficiencies? (Probably not items, for the above reasons).

I am a big fan of this particular diagram in regards to our C++ codebase, because it helps simpletons like me understand what's going on:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/ef68692d-38bc-40c4-b02e-665c8c65f86a)

**Comment by I-am-Erk** [comment]
It's possible we could simply not allow NPCs to use starting items from professions to avoid that, even if the profession is also available to players: profession items shouldn't be randomized, while NPC items almost always should be, so it makes sense that they'd use a separate mechanic. The only downside to this is that then we can't have NPCs get their starting items tweaked by whatever hobby professions they are randomly assigned. However, we don't have anything like that currently anyway, so it would only be a lateral change.

In that case we'd continue to do NPC item assignment the same way we do currently.
