### ISSUE TITLE
Some vehicle parts don't actually get repaired when you repair them from the vehicle menu

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70318]
### Describe the bug

Some objects on a vehicle that get damaged can be repaired, but sometimes they take resources, but don't get repaired. I understand that most vehicle parts are not meant to be repaired fully because of vehicle part degradation, so I'm not sure if there is a conflict with that, or something else. 

In the below steps, I look at the "controls". There is also the right-most "seat" that accepts repairs, but doesn't repair. The heavy duty quarterpanel, some heavy-duty frames, etc, all take repairs but don't change condition.

### Attach save file

[testinggg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13722577/testinggg-trimmed.tar.gz)

### Steps to reproduce

1. Sufficiently damage a vehicle. In my attached save file, I just drove a military cargo truck through a FEMA camp a few times.
2. Try to repair some parts
3. Notice that the "controls" part is available for repair, and takes resources, but its condition doesn't actually change.

### Expected behavior

I expect that if the game gives me the ability to repair a vehicle part, repairing would increase the "controls" condition. If there is some invisible value that gets changed when it gets repaired, it should probably be visible.

### Screenshots

If I try to repair the "controls", it isn't repaired at all despite taking my characters time
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/a2e7b857-f868-4d28-b145-a0e9bd64c17c)

After repairing the 4 parts on this tile, "truck horn", "dashboard", "controls", "seatbelt":
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/210061c5-aa30-4858-8400-6f30f65aa08d)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CoroNaut** [comment]
There is also the fact that windshields can't be repaired while on a vehicle. You can just take them off, repair them to full, then re-install them

**Comment by physics-enthusiast** [comment]
Haven't looked at this specific part of the code here, but maybe this could be related to the fact that ++ is now the max durability and not ||? Just a blind guess.

**Comment by CoroNaut** [comment]
The seatbelt was repaired from "||" to "++". My thoughts was that only some parts are affected by vehicle degradation, which, when repaired, their max durability is "||"? I don't know if degredation can eventually lower a vehicle parts max HP to 0 and have it completely destroyed. I love having these neat intricacies, but I'd like the vehicle degradation could be explained in the help section under vehicles.

**Comment by Icantthinkofanameforthis** [comment]
From what ive seen the green bar at the right of the ++ or || is the max durability so stuff cant be repaired higher than that but since the green bar also includes || lvls of repair as its max maybe there should be a dark green version of the bar to indicate that stuff can be repaired back up to ++ instead of just ||

**Comment by CoroNaut** [comment]
I learned that there are hitpoints on items that are invisible to the player. https://github.com/CleverRaven/Cataclysm-DDA/issues/70332#issuecomment-1865891861. I'm guessing that the issue here is actually that these invisible hitpoints are being repaired to full using _all_ the resources to fully repair the part. If these invisible hit points were on the vehicle interface somewhere, that would let the player have more precise information. Hit points for parts are already modeled, why not let the player see it? If it is intended for the player not to interact with these hit points, then the hit points should not be considered when repairing a part, only the damage levels: "++, ||, ..."

There is also the solution from [Icantthinkofanameforthis](https://github.com/Icantthinkofanameforthis):

> maybe there should be a dark green version of the bar to indicate that stuff can be repaired back up to ++ instead of just ||

Given that _any_ amount of damage can make a part eligible for repair, Having the color "dark green" represent full hitpoints in all scenarios would be informative. It gives the player visual confirmation without requiring that they look deeper into why the part isn't "++".

Personally, adding these invisible hit points to the vehicle interface, and adding the dark green coloring would be best.
