### ISSUE TITLE
Airports should have navigational charts that show the locations of other airports

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#70327]
### Is your feature request related to a problem? Please describe.

Airports tend to be far apart and hard to find. If you find an aircraft it would be nice to also find some other places you could fly it to.

### Solution you would like.

It ought to be easy to make a sectional chart showing airports, runways, tall obstacles such as radio towers and power lines, large roads such as interstate highways, urban boundaries, and large water features. We could then scatter them around anywhere there happens to be an airplane or a pilot.

### Describe alternatives you have considered.

My first attempt:

```json
  {
    "id": "aeronautical_section_chart",
    "copy-from": "abstractmap",
    "type": "GENERIC",
    "name": { "str": "aeronautical section chart" },
    "description": "A large map densely covered in information related to airports, regional flight routes, radio navigation beacons, and other arcana mostly of interest only to an airline pilot. You doubt anyone cares about the airspace classifications or flight restriction zones any more.",
    "color": "light_green",
    "use_action": {
      "type": "reveal_map",
      "radius": 2160,
      "terrain": [
        "ocean_shore",
        { "om_terrain": "city_center", "om_terrain_match_type": "TYPE" },
        { "om_terrain": "runway", "om_terrain_match_type": "CONTAINS" },
        { "om_terrain": "control_tower", "om_terrain_match_type": "PREFIX" },
        { "om_terrain": "stadium", "om_terrain_match_type": "PREFIX" },
        { "om_terrain": "ws_fire_lookout_tower", "om_terrain_match_type": "PREFIX" },
        { "om_terrain": "radio_tower", "om_terrain_match_type": "PREFIX" }
      ],
      "//": "Should also reveal at least the major highways and rail routes, major urban areas, as well as large–scale water features",
      "//2": "See https://aeronav.faa.gov/visual/11-30-2023/PDFs/New_York.pdf or https://aeronav.faa.gov/visual/11-30-2023/PDFs/Boston_TAC.pdf for examples",
      "message": "You add a number of regional airports and other landmarks to your map."
    }
  }
```

This doesn’t yield a very usable map, but maybe it is good enough for now. I think on balance it should leave off the `city_center`, since that turns out to include every tiny hamlet as well as the big cities. Showing the `ocean_shore` without the ocean is pretty unsatisfactory. It takes too long to generate the map, with no feedback to the user. Memory usage goes up a bit as it generates a 24o×24o area around the player. Save file gets a bit bigger. 

As a result it might be better to wait for #70056 to be implemented. We could use it to put airports of significant size down in the major regions, and to sprinkle in general aviation and private airports at a reasonable density in the other regions. Done correctly we would be able to know the locations of the airports before we generate the detailed terrain, so that there would be no delay or excess memory usage as a result of using this map.

Also, there are way too many radio towers and not nearly enough actual airports, but that is an entirely different problem. Someone should design an international airport too, and set up a starting scenario or two for it. Again, out of scope for this particular suggestion.

### Additional context

See https://aeronav.faa.gov/visual/11-30-2023/PDFs/New_York.pdf for the real section map for New England. https://aeronav.faa.gov/visual/11-30-2023/PDFs/Boston_TAC.pdf is a more detailed view of the Boston area.

**Comment by Yobrocharlie** [comment]
10/10 idea and PR

**Comment by Procyonae** [comment]
Having an item generate 18,662,400 OMs isn't very sensible imo :^)

**Comment by db48x** [comment]
It’s only 24×24=576 overmaps, not 18 million.

**Comment by Procyonae** [comment]
Well 24x24x180x180=18,662,400 OMTs then or whatever they're meant to be called
