### ISSUE TITLE
No Hope infrastructure

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#70325]
### Is your feature request related to a problem? Please describe.

No Hope has really annoyed me during multiple PRs bc when you're done with map changes and think you're good to merge, the tests point out that No Hope has a duplicate of the map, requiring you to then reapply all your changes or have to figure out what was different about the No Hope version and apply them to your new version depending how significant your changes are.
This wouldn't annoy me much if the No Hope versions for the most part solely exist to reduce item spawns, which could be entirely replaced by exposing #62583's functionality.
I want to personally make an initial settings setup on character creation akin to Sky Islands difficulty settings that allows changing both #62583's settings and No Hope's own settings for vehicle spawns in-game, following with yeeting most of the duped maps, but need help with infra prior to starting this.

### Solution you would like.

There are two problems with this, firstly #62583 doesn't affect "place_item" and "item", only "items" and "place_items" etc, and upon finishing the setup ideally I'd have some way to "refresh" the reality bubble, although that might be avoidable with #66454 or something similar instead
As a side note a blacklist from the rate setting would also be nice for items such as "keys" etc

### Describe alternatives you have considered.

~~Just rezzing #64586 and putting the existing item spawn rate setting into the category so it isn't even adding a single new line to the settings and seeing how peeps still argue that that's UI bloat somehow~~

### Additional context

I think this is well worth the effort as it makes maintaining both vanilla and No Hope easier while also exposing a very cool but obscure JSON only setting that the vast majority of players are unlikely to know about.
(Example of a PR that I lost interest in due to No Hope being a PITA atm #67720 (I will rez it at some point dw))

**Comment by GuardianDll** [comment]
I don't know how bad this idea is, but i personally would like this settings to be EoCable also, so we can make difficulty settings, like sky island has, affect drop rate of items

Additionally, does it actually reduce amount of stuff, or it straight cut it away? `100 coal` with `ammo 0.5` setting would make it spawn 50 coal, or it will make it spawn 100 coal 50% of the time?

**Comment by Procyonae** [comment]
So I exposed this to EoC and implemented it in No Hope removing most of the dupe mapgen and cleaning up the mod in general in #73268 but the limitations on what item spawns this affects is still an issue.
