### ISSUE TITLE
Infinite Book Glitch: Follower reading from E-Ink Tablet PC prints a copy and deletes book data off device

### ISSUE THREAD

**Issue by aeaean** [CleverRaven/Cataclysm-DDA#70329]
### Describe the bug

When a follower NPC reads from an e-book device (tested with e-ink tablet PC and laptop computer), the book data is removed from the device and the NPC prints a fresh copy of the book in their inventory. 

### Attach save file

N/A

### Steps to reproduce

1. spawn NPC follower
2. spawn e-ink tablet PC, books, batteries (make sure the book is informative to the NPC)
3. scan book
4. instruct NPC to read e-book

### Expected behavior

Book data should not be consumable and using it should not magically conjure a new copy. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2506 (22H2)
- Game Version: dc3b97e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by TealcOneill** [comment]
@GuardianDll Can't replicate. When ordered to read an E-book the NPC learns about the subject and then only has the e-reader devices in their inventory. No books to be found.
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-1833 7f06e9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
