### ISSUE TITLE
Damaged items don't stack despite being the same condition which bloats windows containing items

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70332]
### Describe the bug

Clothing items or tools or anything else that has full durability are able to stack like "7 ++ copper lockets", but damaged copper lockets are never stacked, even if there are two or more of the same item with the same durability. 

Some vehicle parts are able to be stacked while damaged, but it's not consistent. These parts are all on the same tile. See Image 2. 
Guns can be stacked if they have the same ammo, empty, partially full, or full. But once again, if they are damaged, they don't stack. See image 3.

### Attach save file

Trivially reproducible, but included my save, the character is next to the piles of loot in the pictures:
[Lenora-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13732876/Lenora-trimmed.tar.gz)

### Steps to reproduce

1. Get a large amount of a single clothing item, tools, or vehicle parts
2. Damage all of the same clothing, tools, or vehicle part items randomly.
3. Notice that only "++" full durability items stack, and only _some_ damaged vehicle part items stack.

### Expected behavior

I expect multiple items with the same durability to be collapsed. The "amt" column is there, we should use it. This will significantly reduce the amount of scrolling and number of pages when lots of damaged items are collected.

The stacked and damaged vehicle parts makes me think that the functionality for this is there, its just broken.

### Screenshots

I have tons of copper hairpins, copper lockets, copper necklaces, and copper rings. Only the "++" durability items stack. The rest are listed off individually despite many items having the same durability below "++".
Image 1:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/dec48699-545c-4fb9-b0b5-c1d4c99ca6e2)
Image 2: These vehicle parts are all on the same tile. Some stack, others don't for some reason.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/9559f3d9-1779-47c0-ab3a-f1c17d50180a)
Image 3:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/5bbd6173-edcb-45ed-925c-f603a0629cd7)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by andrei8l** [comment]
```diff
diff --git a/src/item.cpp b/src/item.cpp
index d04c60fe0d..5ba9490784 100644
--- a/src/item.cpp
+++ b/src/item.cpp
@@ -1369,7 +1369,7 @@ bool item::stacks_with( const item &rhs, bool check_components, bool combine_liq
     if( is_favorite != rhs.is_favorite ) {
         return false;
     }
-    if( damage_ != rhs.damage_ ) {
+    if( damage_level() != rhs.damage_level() ) {
         return false;
     }
     if( degradation_ != rhs.degradation_ ) {
```

**Comment by PatrikLundell** [comment]
@andrei8l's rather terse comment translated into English:
The code only stacks items with the same amount of damage ("hit points"), whereas damage level is a range of damage that's displayed the same way. This can be rectified by stacking items based on damage level (so items with the bar condition display are stacked in the display, even if their actual damage varies slightly).

**Comment by CoroNaut** [comment]
I didn't realize there were micro-hitpoints that the player couldn't see. This would account for why some damaged vehicle parts are able to stack, while others cant. Having these items displayed, sorted and combined on an invisible value could probably be changed. it only serves to confuse the player.
