### ISSUE TITLE
Mac Startup Problem Solution

### ISSUE THREAD

**Issue by Urist-The-Dorf** [CleverRaven/Cataclysm-DDA#7033]
Hi, I'm on mac and I downloaded CAT:DDA V0.A From the forum thread. I downloaded the mac curse and when I attempted to open it this appeared: DEBUG: Could not read data/raw/keybindings.json   Press space bar... After I pressed space bar it quit the game, what do I do to be able to play?

**Comment by illi-kun** [comment]
That's an outdated issue, I suppose.
