### ISSUE TITLE
Crash after sleeping on first day

### ISSUE THREAD

**Issue by Nukesor** [CleverRaven/Cataclysm-DDA#70330]
### Describe the bug

After sleeping, the game just crashes.
Shortly before the game crashes, the achievement for the very first survived day shown.
The player is sleeping on a deployed rollmat in front of a burning fireplace.

The exact same stacktrace also pops up, when one opens the achievemtn/diary dialog.

### Attach save file

[Karthaus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13731306/Karthaus-trimmed.tar.gz)

### Steps to reproduce

1. Load the attached safe file
2. Sleep

or

1. Open achievement/diary dialog

### Expected behavior

The game shouldn't crash

### Versions and configuration

- OS: Arch Linux 6.6.7
- Game Version: `c7ad898` (64-bit)
  (AUR `cataclysm-dda-git` build)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded:
  - `dda`
  - `no_npc_food`
  - `personal_portal_storms`
  - `no_fungal_growth`
  - `package_bionic_professions`
  - `blazeindustries`
  - `bombastic_perks`
  - `stats_through_kills`

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13731441/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13731442/debug.log)

**Comment by Nukesor** [comment]
I'm closing this for now.

I ran into other problems as well, which were probabl caused by a really old config directory.
I'll reopen this, if I manage to reproduce the issue on a clean start.

**Comment by Nukesor** [comment]
Crash indeed still happens on a fresh save without any pre-existing configurations.

**Comment by RenechCDDA** [comment]
Based on the stack trace it looks a lot like #69703, but this one has more calls before it terminates.

@andrei8l  Can I get your opinion on this?

**Comment by Nukesor** [comment]
I also just checked, if the crash happens when build directly from source and not via `makepkg`, since this apparently adds some security related build flags.

Still happens on a clean build directly on the source.

**Comment by Nukesor** [comment]
The bug also doesn't appear when compiling without `_GLIBCXX_ASSERTIONS`

**Comment by andrei8l** [comment]
The crash-on-wake is the same as #69703. The log here is weird indeed. The `addr2line` code probably needs an update.
<details>
<summary>proper crash log from libbacktrace</summary>

```gdb
STACK TRACE:

    0x564,192,69e,6ab    …/src/debug.cpp:952    bt_full
    0x564,192,69e,6ab    …/src/debug.cpp:1,217    debug_write_backtrace(std::ostream&)
    0x564,192,666,43c    …/src/crash.cpp:85    log_crash
    0x564,192,666,a12    …/src/crash.cpp:138    signal_handler
    0x7f1,d49,85c,70f    [unknown src]:0    [unknown func]
    0x7f1,d49,8ac,83c    [unknown src]:0    [unknown func]
    0x7f1,d49,85c,667    [unknown src]:0    [unknown func]
    0x7f1,d49,844,4b7    [unknown src]:0    [unknown func]
    0x7f1,d49,add,3b1    …/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61    std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    0x564,192,699,d36    /usr/include/c++/13.2.1/bits/stl_vector.h:1,144    std::vector<std::pair<translation, game_message_type>, std::allocator<std::pair<translation, game_message_type> > >::operator[](unsigned long) const
    0x564,192,699,d36    …/src/effect.cpp:555    effect_type::get_rating(int) const
    0x564,192,699,d36    …/src/effect.cpp:577    effect_type::lose_game_message_type(int) const
    0x564,192,699,d36    …/src/creature.cpp:1,746    Creature::remove_effect(string_id<effect_type> const&, int_id<body_part_type> const&)
    0x564,192,6a1,94a    …/src/creature.cpp:1,937    Creature::process_effects()
    0x564,192,666,fa5    …/src/creature.cpp:263    Creature::process_turn()
    0x564,192,666,fa5    …/src/creature.cpp:255    Creature::process_turn()
    0x564,192,42b,c90    …/src/character.cpp:2,334    Character::process_turn()
    0x564,192,758,d0b    …/src/do_turn.cpp:631    do_turn()
    0x564,192,180,794    …/src/main.cpp:798    main
    0x7f1,d49,845,ccf    [unknown src]:0    [unknown func]
    0x7f1,d49,845,d89    [unknown src]:0    [unknown func]
    0x564,192,141,034    [unknown src]:0    [unknown func]
    0xf,fff,fff,fff,fff,fff    [unknown src]:0    [unknown func]
```

</details>

The diary UI crash is unrelated https://github.com/CleverRaven/Cataclysm-DDA/blob/c6f63976b3dac61b37ece26a52c09df048c72417/src/diary_ui.cpp#L301
my best guess is that it was meant to be `std::clamp( max.y / 2 - 4, 3, 7 )`
