### ISSUE TITLE
Add some aquatic plants

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#70341]
### Is your feature request related to a problem? Please describe.

Since we now have the ocean, perhaps we can make the bottom of the water more vibrant

### Solution you would like.

Add some aquatic plants(Including coral, although seems coral is not a plant)

**Comment by fairyarmadillo** [comment]
I did some digging and found a few plants I think would make good additions. These all grow in New England.

As a note, I use the word algae here a lot - algae is not just green slime, it's also the proper name of all the stuff we call seaweed.

Red Algae - We can use this as a catch-all term for non-edible species like Neosiphonia harveyi which basically look like red grassy plants. They tend to grow on boulders and rock formations, but can be found anywhere. Concentration should be heaviest in the deeper parts of the intertidal zone, that is, the part of the ocean which is underwater at high tide and above water at low tide. We don't have tides (I don't think) so we should probably call the intertidal zone anything within one map tile of the beach.

Green algae - Again a catch-all term, but a useful one for species such as Codium fragile ssp. fragile, which is super prolific in New England's waters. It looks like green grass with finger-like branches.

Bladder weed - Colpomenia peregrina, an invasive species that is pretty common nowadays. It looks like little green balloon-shaped growths that especially appear in places you find oysters.

Kelp - Kelp in New England doesn't tend to go all the way to the surface like in other places. A lot of it stays close to the ocean floor, but sometimes it can get up to five meters. So we should have kelp forests (these could be handled like regular forests, with a lot of kelp in one spot), just be wary of making them more than a tile or three high. There are many different species of kelp and we should represent this, but one species called sugar kelp is harvested in New England for human consumption.

Sea Lettuce - Ulva lactuca. This is a small green edible seaweed that grows in intertidal zones. You can forage it IRL by walking around tide pools and other places and picking it off the rocks, but you could also dive in the shallows and get it.

Dulse - Palmaria palmata. This is an edible red algae that is supposedly pretty healthy. Here is a recipe including nutrition facts: https://gooddinnermom.com/seaweed-chips/

Sea Moss - AKA Irish Moss. Another edible algae.

Bladderwrack - Different from bladder weed, this is Fucus vesiculosus. It's edible, nutritious, and is (probably mostly mis)used for its medicinal properties. It's a known anticoagulant, so it could have a similar effect to the one added to aspirin in #70239 

Ideally we're going to have little sub-biomes set up like we do with fields, forests, etc., but until then it's probably fine to just spread this stuff all over.

**Comment by fairyarmadillo** [comment]
SESSILE OR NEAR SESSILE ANIMALS WHICH COULD BE TREATED AS FURNITURE LIKE PLANTS:

Gorgonian soft coral - This stuff forms the more typical branchlike structure you might think of, but it grows only in deep water.
Sea Sponge - These creatures adhere to rocks and would need a knife or something to cut loose. If you get one out of the water and dry it, it should just turn into a sponge like you'd find in a kitchen, or an item with an identical function.


SESSILE ANIMALS WHICH SHOULD BE ITEMS:

I believe we want to include clam beds, tide pools, and underwater rock formations the player could forage in like they do with underbrush. For clams, we may also want them to be something you can find by digging pits on the beach. Some animals are good candidates for inclusion here:

Starfish - These do move around, but not quickly enough for the player to notice.
Star coral - These are really small and not likely to be significant to the player. They just look like weird little rocks, and could probably function as such.
Little Neck Clam: Very small but exceptionally delicious clams.
Cherrystone: Mid-sized clams, also good for eating.
Quahog: Quahogs are very large clams that usually go in chowder or other dishes where you're not eating the thing whole.
Soft-Shell Clam: Another good clam you can dig up on the shore.
Razor Clam: These are usually found close to the beach. Edible.
Mussels: These famously grow all over rocks and piers. Also edible.
Oysters: Again, what can I say. It's an oyster, you can eat it.
Periwinkle: These are tiny little snails that stick to rocks in the surf. We have land snails that can be harvested from underbrush, these should work the same way. You can cook and eat them.
Whelk: I think they should be an occasional tidepool find, but they mostly hang out underwater.

It is safe to eat shellfish raw, but it is NOT SAFE to eat periwinkles raw. I have heard that in Japan they serve raw whelk sashimi, so those are probably fine as long as they're cleaned before eating.

Some percentage of shellfish should be rotten when harvested, as this is a common issue IRL.

**Comment by CoroNaut** [comment]
Waiting patiently to put a tiny kelp and starfish in my 100 gallon aquarium.

**Comment by Rocket-F-1024** [comment]
Now this issue is competed by https://github.com/CleverRaven/Cataclysm-DDA/pull/74271/files.

**Comment by Procyonae** [comment]
I'll close it just bc the issue is specifically for plants but the stuff in [fairyarmadillo](https://github.com/fairyarmadillo)'s last comment would still be cool to see and someone can happily open another issue with it
