### ISSUE TITLE
Mounted V29 won't vent heat

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#70340]
### Describe the bug

Mounted laser pistols won't slowly reduce heat over time like a normal laser pistol would. I confirmed by removing it from the vehicle, which showed a VNT-ing laser pistol that worked normally after I let it cool down.

### Attach save file

[Uploading Wooldridge-trimmed.tar.gz…]()

### Steps to reproduce

1. Mount v29 on car
2. Have it shoot
3. Notice how heat never goes down

### Expected behavior

It should slowly vent heat. That's an automatic thing the gun does, not a human-handled like say pumping a shotgun.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: de7f85e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by GuardianDll** [comment]
update your game, it was fixed in #69551, your version is too old
