### ISSUE TITLE
Have Weight related traits adjust based on characters current weight (fatness not inventory)

### ISSUE THREAD

**Issue by Icantthinkofanameforthis** [CleverRaven/Cataclysm-DDA#70345]
### Is your feature request related to a problem? Please describe.

Was looking over my character that had just gotten to his first autumn with Weight: Normal and Lifestyle: Feel Great and noticed he still has the Trait XXXL and thought hes not fat anymore. Was thinking that should probably change.

### Solution you would like.

As the title suggests have the weight trait change when the character increases or decreases in weight. 

Figure since the 2 starting weight traits you can pick seem to be clothing sizes might as well keep it as such and have them change accordingly.

Morbidly Obese = XXXL
Very Obese = XXL        
Obese = XL   
Overweight = L           
Normal = M         
Underweight = S                                      
Emaciated = XS                  
Skeletal = XXS

### Additional context

I was also thinking these traits could be Cosmetic showing up when mousing over NPCs the way some mutation traits are.

**Comment by PGR-14** [comment]
It'd be good for that Chinese one in the refugee center
