### ISSUE TITLE
MSXOtto+ & Ultica lack LEAVES2 & 3 sprites

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#70356]
### Describe the bug

LEAVES is a mutation with 3 levels and (now) 3 variant forms, but both Ultica and MSXOtto+ only have sprites for LEAVES1's spring/summer form.

Additionally, MSXOtto has a weird messed up sprite for CHLOROMORPH that should probably just be removed. It's layered incorrectly and whatever it's depicting no longer matches what the mutation does, which is to just make you generally more planty.

### Attach save file

N/A

### Steps to reproduce

Load a game in one of those tilesets and get those mutations

### Expected behavior

LEAVES1_WINTER needs a sprite. Per its description this should just be a blonde/brown looking version of LEAVES1

LEAVES2, LEAVES3, LEAVES2_FALL, and LEAVES3_FALL need sprites. Per their description these add progressively more leaves to the player's head and also their arms. The arm sprites may be tricky to depict, but as it's mechanically relevant I suggest at least putting some patterning on the character's arm which can be covered by clothing (which is how the mutation works). The fall versions are just the same leaves but autumn colored. LEAVES3_FALL is described as being especially pretty and has less ugliness than the others as a result.

ROSEBUDS also has 2 new variants. Regular ROSEBUDS is budding flowers, ROSEBUDS is big especially beautiful ones, and ROSEBUDS_FALL is a few little fruits growing from stems on the character's head, which are described as looking sort of like plums.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 0.G-5928-gf7321ea569-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I would simply do this myself, but I have tried and I cannot for the life of me figure out how to get the game to actually display new sprites.

**Comment by Procyonae** [comment]
The tileset repo is seperate to this one https://github.com/I-am-Erk/CDDA-Tilesets

**Comment by fairyarmadillo** [comment]
Thank you, will repost there.
