### ISSUE TITLE
Emergency Sirens

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70357]
### Is your feature request related to a problem? Please describe.

EMS vehicles don't have any sirens

### Solution you would like.

Adding a siren (& perhaps w/ the Red/Blue lights, they could flicker?)

### Describe alternatives you have considered.

Not doing it

**Comment by CoroNaut** [comment]
There are very few animations in the game right now, making some for siren lights would be nice. Lights on vehicles or appliances could perhaps dim and brighten their texture like enemies on the minimap, but in the world.

**Comment by PGR-14** [comment]
Yeah, & the siren could be useful for drawing hordes away from something
