### ISSUE TITLE
Some hotkeys don't work in bionics window

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70350]
### Describe the bug

For some reason, the hotkeys for "Q" and "q" don't work and they close the bionics window. Normally, you would get a message saying that you don't have charge, or you activated that bionic. For a hotkey that isn't assigned to any bionic, it just does nothing, not even close the window. I've double checked that they work in the inventory interface and they aren't conflicting with other commands. or general game keybind.

### Attach save file

[testinggg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13749026/testinggg-trimmed.tar.gz)

### Steps to reproduce

1. Open bionics window
2. "Q" and "q" don't work

### Expected behavior

All hotkeys work if they are not assigned to some higher function like "!" examine or "=" reassign, or others.

Also, if you try to assign a bionic to a key that is already used by the current interface, it should prompt that there will be a keybind conflict.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/a64964f6-7e16-4c11-98aa-0e5e8a81e587)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 7773670 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Icantthinkofanameforthis** [comment]
Had a look and while in the bionics menu if you check the keybindings with ? you can find Q and q are bound to exit screen and will work as you want if a remove keybinding was done on them

![this](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/d1382e8e-3c19-4386-b63f-bab9515cdddb)

**Comment by CoroNaut** [comment]
Well darnit, sure enough, there it is. I even made a comment about how there isn't a popup for conflicting keybinds and fell for it.
