### ISSUE TITLE
Items deleted when detaching certain pockets and then wearing them

### ISSUE THREAD

**Issue by mini-bomba** [CleverRaven/Cataclysm-DDA#70354]
### Describe the bug

Items apparently were deleted when detaching pockets from a MOLLE large rucksack, and then wearing the detached pockets

### Attach save file

[Megler-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13753447/Megler-trimmed.tar.gz)

### Steps to reproduce

- load the attached save file
- detach a sheath from the MOLLE large rucksack (being worn by the character)
- wear the detached sheath
- repeat the above two steps with a nylon holster
- an error pops up ("Oops!  deleted some items when updating pockets that were added via toolmods")

Note: there may be other combinations to reproduce the bug. the error doesn't seem to pop up if any of the above steps were skipped.

### Expected behavior

No error should occur, and no items should be deleted

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-5957-ge42250c2c3 [64-bit] (Note: manually compiled)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Logs from an attempt to reproduce, following the steps listed above: [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13753519/debug.log)
The save file is about 2 months old, and was always used on experimental. I usually recompile the game with new updates before playing.

**Comment by mini-bomba** [comment]
Adding on after further experimenting:
- Seems like the bug can also be triggered by detaching & wearing the sheath and nylon holster in the reverse order (first detach & wear the holster, then do the same with the sheath)
- It also appears that items aren't being correctly transferred from the MOLLE rucksack to the detached pocket on the second detach.
  - If the sheath is detached second, it is empty upon detaching, but the "KA-BAR knife" is deleted from inventory after wearing it. (I assume it was supposed to be transferred into the sheath?)
  - If the holster is detached second, the "M1911 pistol" is deleted instead.

**Comment by CoroNaut** [comment]
#70163 should've fixed this. #70126 is one of the issues that was fixed by it.

**Comment by mini-bomba** [comment]
> I'd recommend updating to the latest release to be sure.

I did an update + recompile before starting the game today.
See the "Versions and configuration" section: I'm using commit [e42250c2c3](https://github.com/CleverRaven/Cataclysm-DDA/commit/e42250c2c32a73c9cc3f091400e521a337388312) which was the latest one on master when the issue was opened

**Comment by showervic** [comment]
Still able to see the issue.
A pocket is reported as attached in host ammo description for some time after the pocket removal. Then its get updated and items are lost with debug message "Oops.."
