### ISSUE TITLE
Can't scroll outside view area with 'x'

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#70351]
### Describe the bug

When trying to scroll out of the viewport to look at a distant object using the x key, you can't, there is just a black screen.

### Attach save file

N/A

### Steps to reproduce

1. Make a character
2. Press x
3. Scroll a few tiles to the side

### Expected behavior

For the view to scroll properly

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/52408044/fdd872a7-1bd6-4a4e-9c47-08fef19e7032)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: e42250c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

If this is some kind of way to increase performance, it's not worth it... you can scroll more if you zoom out but it's very annoying that way.

**Comment by Qrox** [comment]
@Rewryte Might be related to the recent 3D draw point change?

**Comment by snipercup** [comment]
I have this too. It's the same when using V to look that items and monsters around you.
```
- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: e42250c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]
```

**Comment by Rewryte** [comment]
> Looks like the cache is not marked as dirty when moving inside the look around mode.

Yep.  Looks like I missed a spot.  Pushing fix.

**Comment by rockygr** [comment]
Can confirm

**Comment by Gannets** [comment]
> > Looks like the cache is not marked as dirty when moving inside the look around mode.
> 
> Yep. Looks like I missed a spot. Pushing fix.

I was just coming here to report this, thanks for the prompt fix!

**Comment by KittyTac** [comment]
> > Looks like the cache is not marked as dirty when moving inside the look around mode.
> 
> Yep. Looks like I missed a spot. Pushing fix.

<3
