### ISSUE TITLE
Make ocean monster spawns moddable

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#70366]
### Is your feature request related to a problem? Please describe.

A couple of new wilderness spawn groups were created for #70202 but it doesn't look like it has the same features that the others have to allow mods to add monsters

### Solution you would like.

Give the ocean monster groups the same modding options that the other groups have

### Additional context

Discovered testing #70362

**Comment by gkarfakis19** [comment]
Hi. I built those mongroups. I am not sure what the issue is here. I am not very familiar with how mods work, but they should be able to change any json file, right?

**Comment by LyleSY** [comment]
This has happened a few times and it involves some code work that I don't understand. My sense from talking to others in the past is that there is something called something like a "generic factory" and if groups are added to that, they are then made available for modding, but this is a second separate step and does not happen automatically.

**Comment by gkarfakis19** [comment]
Hey. A cursory look at the files shows that the newly added mongroups are absolutely no different than any other mongroup I have seen. I can find no mention of them in any generic factory.
What error are you getting precisely? Are the newly defined spawns just straight up not working for you?

Perhaps you can ask around in discord? Someone is bound to know what's happening.

**Comment by LyleSY** [comment]
Yep, my test wasn't extreme enough. I rebuilt it and got it working correctly. Thanks!
