### ISSUE TITLE
Weapon proficiencies improve and regress while fighting

### ISSUE THREAD

**Issue by Chazoshtare** [CleverRaven/Cataclysm-DDA#70368]
### Describe the bug

I noticed how my character has stopped progressing any weapon proficiencies for some time now. I paid close attention to how their progress changes, only to notice how they progress and regress with each attack.
This applies to all weapon proficiencies that I previously developed, now they're just stuck, to give some examples:
- improved fencing weapons to 44.1% and medium swords to 42.1% with a cane sword
- improved polarms to 55.1% and spears to 61.1% with a pike and other spears

Looking closely attack after attack, the proficiencies seem to just oscillate between XX.0% and XX.2%.

### Attach save file

[Lemay-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13757156/Lemay-trimmed.tar.gz)

### Steps to reproduce

1. Look at Polearm Familiarity to see that you are XX.X% of the way towards learning it.
2. Attack something with a pike.
3. Look at the proficiency again.
(Repeat enough times to see the number change, but always stay within the same boundaries.)

### Expected behavior

Proficiencies improve as normal.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-5961-gc6f63976b3 [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/4610eb63-5628-4d5c-8314-c230e02d7ad1)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/6bf6b937-683c-440d-aa49-3039b882150d)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/15963244-7477-403b-9310-1c1c5130d861)
Cannot confirm

**Comment by Chazoshtare** [comment]
@GuardianDll Did you test it with attacks specifically? In my case, the time of how long I've practiced the familiarity for changes.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9805596/d5e4e48d-af41-4fac-ae7d-e772efdf5acf)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9805596/0ac5f5f4-fa95-4247-84ea-bc0db608e692)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9805596/8412967b-b2b9-42f0-8c58-e3fdfe9c1f2f)

This is with 3 individual attacks. Practicing through crafting menu works as intended, but not through combat.

**Comment by GuardianDll** [comment]
i specifically spawned debug monster, and spend twenty minutes poking it with a spear the character have in its hands
![GIF 23-12-2023 0-13-11](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/50c7b068-8ee9-4134-a8f5-5883834b2e07)

**Comment by Chazoshtare** [comment]
![Peek 2023-12-23 00-22](https://github.com/CleverRaven/Cataclysm-DDA/assets/9805596/ef6fe04a-717f-4771-ab90-ceb52ef3d0cc)
I did exactly the same just now with no effect. Any idea what might be causing this, or what I could check more deeply to get some more insight?

**Comment by CoroNaut** [comment]
If the change is the decimal place, is it potentially a rounding error? If your prof% is 55.2% and increased by 0.049% or less and becomes 55.249%, does the game just round it back down to specifically 55.2%?

**Comment by GuardianDll** [comment]
skill decay do not influence it, and the issue is that second user (me) can't reproduce the error

**Comment by Chazoshtare** [comment]
@GuardianDll I recompiled the game at different commits to see where it stopped working, and it looks like this commit broke it:
https://github.com/CleverRaven/Cataclysm-DDA/commit/fecbe9cfe1ff3ab7395115d381cdf04b871d42db https://github.com/CleverRaven/Cataclysm-DDA/pull/70255

I suppose it's the changes to `melee_eocs`, could it be a platform specific issue?

**Comment by CoroNaut** [comment]
Perhaps this code is responsible for polearms specifically? It is pretty much copy/pasted a crapton for _many_ other proficiencies, so the bug could be bigger than just weapons. The math problem is definitely past this code in particular. Where _exactly_ it is needs to be found out by someone with a debugger to look at values.

https://github.com/CleverRaven/Cataclysm-DDA/blob/c6f63976b3dac61b37ece26a52c09df048c72417/data/json/effects_on_condition/melee_eocs.json#L578-L614

I'm on windows with build "2023-12-08-0500" and I can see everything working as intended, I can get anywhere from 0.00% increase to a 0.13%ish increase on polearm proficiency per attack. 

[testinggg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13758500/testinggg-trimmed.tar.gz)

If I go to windows build "2023-12-22-1957" and load my save, my polearm proficiency is at "1.34%". After attacking once, it goes to "1.00% or "1.03%", "1.06%", "1.09%" or "1.13%" and randomly selects one of those values for every next attack. Which matches the "rand(4)" amount in the above code. This would be in-line with why [Chazoshtare](https://github.com/Chazoshtare) sees the oscillation in values, The proficiency window provides one more decimal place than the general info window pictures they provided. It would be nice to have both places express it in "XX.XX" form.

As it seems, every time the proficiency is written to, it is gotten from the actor, multiplied by 100, converted to an int, then converted to a percent, "XX.X". Then, when the code goes to truncate and round, we get resulting weird behaviors. There are just so many type conversions and math happening to a single value, it just seems reasonable this is the issue. The interface gets one value, while the behind-the-scenes value was truncated and rounded back into the "XX.X" form or similar.

Upon loading save:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/2f542ed9-8952-4283-92c9-1b022df51c52)
After attacking once:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/81f8c80b-b2c1-4f4b-b2e9-17c9c040c08c)

After attacking for quite a long time, upwards of 10 in-game minutes holding TAB to auto-attack, proficiency still hasn't increased in a meaningful way:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/9b38700a-3508-4fd6-9bf3-da14fc1b8f09)

**Comment by inogenous** [comment]
I'm able to reproduce it.

The following code should calculate a `double`-precision percentage, but will only result in integer values: https://github.com/CleverRaven/Cataclysm-DDA/blob/c6f63976b3dac61b37ece26a52c09df048c72417/src/math_parser_diag.cpp#L627-L630

With the following changes, the problem can no longer be reproduced:
```diff
diff --git a/src/math_parser_diag.cpp b/src/math_parser_diag.cpp
index 2446410f7a..da28215b82 100644
--- a/src/math_parser_diag.cpp
+++ b/src/math_parser_diag.cpp
@@ -624,23 +624,23 @@ std::function<double( dialogue & )> proficiency_eval( char scope,
     }
     return [beta = is_beta( scope ), prof_value = params[0], fmt_val]( dialogue const & d ) {
         proficiency_id prof( prof_value.str( d ) );
-        time_duration raw = d.actor( beta )->proficiency_practiced_time( prof );
+        const int raw = to_turns<int>( d.actor( beta )->proficiency_practiced_time( prof ) );
+        const int ttl = to_turns<int>( prof->time_to_learn() );
         std::string const format = fmt_val.str( d );
         if( format == "percent" ) {
-            return static_cast<int>( raw * 100  / prof->time_to_learn() );
+            return static_cast<double>( raw ) * 100 / ttl;
         } else if( format == "permille" ) {
-            return static_cast<int>( raw * 1000  / prof->time_to_learn() );
+            return static_cast<double>( raw ) * 1000 / ttl;
         } else if( format == "total_time_required" ) {
-            return to_turns<int>( prof->time_to_learn() );
+            return static_cast<double>( ttl );
         } else if( format == "time_left" ) {
-            return to_turns<int>( prof->time_to_learn() - raw );
+            return static_cast<double>( ttl - raw );
         } else {
             if( format != "time_spent" ) {
                 debugmsg( R"(Unknown format type "%s" for proficiency, assumning "time_spent")", format );
             }
-            return to_turns<int>( raw );
+            return static_cast<double>( raw );
         }
-        return 0;
     };
 }
```

Also, looking at other code that does similar things (but not directly involved in this problem), this code also looks suspiciously like it might lose precision: https://github.com/CleverRaven/Cataclysm-DDA/blob/c6f63976b3dac61b37ece26a52c09df048c72417/src/condition.cpp#L2456-L2460

**Comment by GuardianDll** [comment]
damn, i'm just an idiot, and tested it not on the most recent stable
shame on me
![GIF 23-12-2023 11-43-53](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/820cba1a-b704-463b-aedc-093095e864a0)
/confirmed

**Comment by inogenous** [comment]
Would also like to take the opportunity to thank @Chazoshtare for such a good and thoroughly prepared written issue. Also, big thanks for @GuardianDll for taking the time to do a PR for the fix. Thank you so much. :heart:
