### ISSUE TITLE
Make Western Gun Belts work more like belts

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#70364]
### Is your feature request related to a problem? Please describe.

Western gun belts are described as having the ammunition stored alongside the back, but this leaves space that would be able to store additional equipment

### Solution you would like.

Western Gun belts should act more like regular leather belts, and allow other items with the BELT_clip flag to be attached to the freespace on the belt, in parity with #67154

### Additional context

![Gunbelt mockup](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/0e5661a9-26d1-4f13-bcaa-05368a9e3de0)

The Gray Box is the Holster (this only shows as it being used on the right side, the orange/yellow oval is the bullet storage on the back, and the other lines are belt clip pockets, supposed to be the same as the regular leather belt

**Comment by PGR-14** [comment]
What's the clear/white square? The front marker or another belt clip

**Comment by Kantonine** [comment]
> What's the clear/white square? The front marker or another belt clip

the white square is the belt buckle

**Comment by PGR-14** [comment]
Ok, thanks!
