### ISSUE TITLE
No fencing proficiency 

### ISSUE THREAD

**Issue by Yobrocharlie** [CleverRaven/Cataclysm-DDA#70380]
### Describe the bug

There is no way to get weapon proficiency in fencing.

### Attach save file

N/A

### Steps to reproduce

1: Make a player
2: get you a sword
3: fight with it
4: go into info
5: get error message

### Expected behavior

To get the proficiency 

### Screenshots

![CDDAerrormk0](https://github.com/CleverRaven/Cataclysm-DDA/assets/126765898/d8b6198f-2a08-48b1-8b04-ef59ffba8291)

### Versions and configuration

Latest experimental
(Experi build 2023-12-21-1710)

**Comment by TheShadowFerret** [comment]
I fixed this in #69276, and the current branch shows it hasn't been reverted 🤔
