### ISSUE TITLE
Vehicle weapons shouldn't shoot into the vehicle

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70387]
### Is your feature request related to a problem? Please describe.

Vehicle weapons shouldn't be allowed to shoot into the vehicle when they are attached to the roof. Would the turret really have more than 25 degrees of gun depression even? 

<img src="https://w0.peakpx.com/wallpaper/455/69/HD-wallpaper-humvee-with-50cal-hb-machinegun-09-humvee-machinegun-05-2011.jpg" width="360">

### Solution you would like.

1. Assuming a 25 degrees turret depression, we can get 4 tile minimum turret range from the center of the turret. If the edge of the vehicle is still inside the minimum radius, it could still be shot into though.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/3d4c9f08-034c-462a-8939-0281a4f67242)

2. Only disallow firing a turret into the vehicle. If a zombie was at the far edge of the vehicle, the turret would effectively have to shoot through the roof to hit it, but its a bit better.

3. Use 3d experimental vision on the vehicle turret. The turret could essentially fire from the height of the vehicle, but use 3d experimental vision from the open air tile above to figure out where around the vehicle it should see. This is by far the most realistic option. Also, the fact that 3d vision is pretty much implemented makes this a great opportunity to make use of it here.

Solution 3 is probably best, but probably more work than just disallowing shooting into the vehicle or minimum tile range.

### Describe alternatives you have considered.

Just firing down 90 degrees into my vehicle anytime my vehicle gets swarmed to easily get out of the situation.

**Comment by fairyarmadillo** [comment]
I think what we may be waiting for here is someone to come along and make vehicle roofs create a floor on the Z level above the vehicle. Items mounted on the roof, like solar panels and turrets, would sit at z+1. This is similar to option 3 but a bit more involved.

There are edge cases where we wouldn't want that, such as an unroofed shopping cart turret, but it wouldn't be impossible to sort that out.

**Comment by Procyonae** [comment]
Waiting for multi z level vehicles for this sounds a bit silly, solution 3 sounds smart with it treating the vehicles roof tiles as being roof terrain on z+1 while it's doing the check and you could modify the vision code to have a variable depression for different lengthed turrets etc if you wanted to go the extra step
