### ISSUE TITLE
small reality bubble

### ISSUE THREAD

**Issue by sasichkamega** [CleverRaven/Cataclysm-DDA#70384]
### Describe the bug

small field of view when the "look around" button is pressed

### Attach save file

[Лампасас-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13759036/-trimmed.tar.gz)

### Steps to reproduce

just hit the "look around" button

### Expected behavior

Expecting a larger scope size

### Screenshots

![изображение](https://github.com/CleverRaven/Cataclysm-DDA/assets/15817985/e101b7cc-b3be-4e40-b601-a814d8acdcee)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: c6f6397 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(86,6%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Бионические профессии [package_bionic_professions],
    Экстра сценарии с мутациями [extra_mut_scens],
    Перевод сложных диалогов [translate_dialogue]
]

**Comment by BrettDong** [comment]
Duplicate of #70351
