### ISSUE TITLE
sludge crawler and zombie crash in the town

### ISSUE THREAD

**Issue by moontheto** [CleverRaven/Cataclysm-DDA#70405]
### Describe the bug

I was in the town luring many zombies to the sludge crawler and throwing Molotov at them 

### Attach save file

[Selinsgrove-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13760885/Selinsgrove-trimmed.tar.gz)

### Steps to reproduce

Go to the area near the Sludge Crawler where a zombie is currently attacking it.

### Expected behavior

fix the bug?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 5cb45b3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13760898/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13760900/debug.log)

**Comment by TealcOneill** [comment]
@GuardianDll Using the provided save I walked around the sludge crawler a bunch and waited time using debug health and never had a crash.
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-1833 7f06e9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
