### ISSUE TITLE
List all items/monster around player (V) view bug similiar to looking previous looking round (x)  

### ISSUE THREAD

**Issue by moontheto** [CleverRaven/Cataclysm-DDA#70408]
### Describe the bug

same as the previous view bug that was fixed when looking around with the 'x' key
but it's for 'V' key to list all monsters or items

### Attach save file

N/A

### Steps to reproduce

Use the 'V' feature and zoom in or zoom out

### Expected behavior

View to scroll properly

### Screenshots

![Screenshot 2023-12-24 133223](https://github.com/CleverRaven/Cataclysm-DDA/assets/28306188/56fa58a6-c1e4-4251-9e36-67ab09ec5faf)
![Screenshot 2023-12-24 133247](https://github.com/CleverRaven/Cataclysm-DDA/assets/28306188/ed5596de-6402-47d1-926e-6a95a934cec1)

### Versions and configuration

OS: Windows
OS Version: 10.0.22621.2861 (22H2)
Game Version: 5cb45b3 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CoroNaut** [comment]
I also see this bug
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0600cfc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by physics-enthusiast** [comment]
See #70379 and #70355

**Comment by harakka** [comment]
/confirm
Yep, this is still around for aiming guns and viewing mobs with v.

**Comment by KittyTac** [comment]
I also still see this.
- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 4456147 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by rockygr** [comment]
Can confirm as well.
