### ISSUE TITLE
Bunch of pseudo terrain

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70400]
### Describe the bug

I keep seeing pseudo terrain in fields (Maybe 1 or 2 every 20 fields?)

### Attach save file

N/A; walk into a field

### Steps to reproduce

Go into a field, & walk around till you find the black pseudo

### Expected behavior

Regular grass

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: a4a6785 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Tankmod: Revived [Tankmod_Revived],
    Healthy Foods [healthy_foods],
    Hauling Space [hauling_space],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    World on Fire [World_on_fire],
    Targeted Mutagens [targetedmutagens],
    Frontier Mods Core [frontier_core],
    Remedy [remedy],
    Remedy: Combat Injectors [remedy_combat_injectors],
    Pixel's Various Fuckery [Pix's Shit],
    Loadout [loadout],
    Jackledead Armory [jackledead_armory],
    Handload [handload],
    Gunsmith [gunsmith],
    Culinary Days Ahead [culinary_days_ahead],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    <color_light_red>Secronom</color> [secronom],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Sly's Starting Spots [slys_starting_spots],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Easy Proficiency [sch_easy_proficiency],
    Custom Portal Storm Size [custom_size_ps],
    Custom Frequencey For Portal Storms [custom_freq_ps]
]

### Additional context

Probably the mods I'm using

**Comment by CoroNaut** [comment]
Adding a save file makes it much easier and much more convenient for people to just load your save with all your mods and see what you see. Without a save, someone would have to manually select all your mods, then start a new world, then attempt to see what you are seeing. 

Also pictures, you can use "Print screen" to just take a full screen shot in-game, then CTRL-V in the comment text box here on github and it will upload a picture of what you see. If you want to crop it, you can CTRL-V paste it into the paint application, use the selection box to select what part of the picture you want, then copy/paste just that selection here on github.

**Comment by PGR-14** [comment]
Yeah, nevermind. It just stopped happening for some reason? IDK

**Comment by teackot** [comment]
I'm having the same issue. Just encountered a couple of pseudo terrain tiles in the field near the road and a garage. Map editor shows that all of them are `t_region_shrub_plains`

- Game version: 7c80ee9 [64-bit]
- Mods loaded: [
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "no_hope",
  "translate_dialogue",
  "cbm_slots",
  "personal_portal_storms",
  "bombastic_perks"
]

Save file: 
[Play-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13855523/Play-trimmed.tar.gz)
Walk around the field and you will find more of these

**Comment by teackot** [comment]
This is a bug in No Hope mod introduced in #70122

**Comment by pjf** [comment]
/confirmed

Playing with No Hope and also seeing this.

**Comment by AnotherSeawhite** [comment]
Can confirm.
![Screenshot_20240215_151502_Cataclysm DDA (experimental) (1)](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/69ac392f-de13-49a8-bcd7-cb9ba1973bdf)

**Comment by Procyonae** [comment]
Fixing it now ^^

**Comment by PGR-14** [comment]
Thanks
