### ISSUE TITLE
SDL Warning prevents compiling

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#70415]
### Describe the bug

Attempting to compile the current build of the game results in:
```

C:/msys64/mingw64/include/SDL2/SDL_main.h:143:17: error: no previous declaration for 'int SDL_main(i
nt, const char**)' [-Werror=missing-declarations]
  143 | #define main    SDL_main
      |                 ^~~~~~~~

```

#70377 sought to fix it but that solution didn't work. I popped into the discord and didn't really see anybody talking about it, so I'm making an issue in case it needs more eyes on it. If it's already under control then please disregard.

### Attach save file

N/A

### Steps to reproduce

Clone the repository, try to compile, fail.

### Expected behavior

The game ought to compile.

### Versions and configuration

If it matters, I'm using MSYS2 and the command I'm trying is $ make CCACHE=0 RELEASE=1 MSYS2=1 DYNAMIC_LINKING=1 SDL=0 TILES=1 SOUND=1 LOCALIZE=1 LANGUAGES=all LINTJSON=0 ASTYLE=0 RUNTESTS=0 -j12

If there's a short-term fix I could do on my end I'd love to hear about it so I can get back to work.

**Comment by ZhilkinSerg** [comment]
`SDL_MAIN_HANDLED` probably needed somewhere

**Comment by fairyarmadillo** [comment]
Is there some other way people are able to compile? I see PRs still going up since this issue began.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/tree/master/doc/COMPILING

**Comment by fairyarmadillo** [comment]
I'm not sure what I'm supposed to make of this link. Is it just MSYS that's having the problem? Is there a way to get it to stop? Is there a specific one that doesn't have the problem?

I asked on the discord but I was told to come here.

**Comment by ZhilkinSerg** [comment]
> I'm not sure what I'm supposed to make of this link.

That link contains all compilation guides for various environments.

> Is it just MSYS that's having the problem? Is there a way to get it to stop?

I am not having any issues compiling using current MSYS guide using command line `make CCACHE=1 RELEASE=1 MSYS2=1 DYNAMIC_LINKING=1 SDL=1 TILES=1 SOUND=1 LOCALIZE=0 LANGUAGES=all LINTJSON=0 ASTYLE=0 TESTS=0`. You are not using `TESTS=0` and the issue appears when compiling tests.

**Comment by fairyarmadillo** [comment]
> I am not having any issues compiling using current MSYS guide using command line `make CCACHE=1 RELEASE=1 MSYS2=1 DYNAMIC_LINKING=1 SDL=1 TILES=1 SOUND=1 LOCALIZE=0 LANGUAGES=all LINTJSON=0 ASTYLE=0 TESTS=0`. You are not using `TESTS=0` and the issue appears when compiling tests.

This fixed it, thank you for explaining.

**Comment by prharvey** [comment]
Compiling tests with MSVC now spams a bunch of warnings that SDL_MAIN_HANDLED is duplicated. The tests still run so it's rather low priority, but it's a little noisy.
