### ISSUE TITLE
Solid rock lab module is capable of spawning in science lab tower

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#70429]
### Describe the bug

The solid rock lab module is spawning in a lab tower which makes no sense, it isn't underground and should be individually removed.

### Attach save file

N/A mapgen produced it

### Steps to reproduce

1. Spawn science lab towers until you get a lab rock room

### Expected behavior

No lab rock module in science lab tower

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/0979b7a6-b334-4377-9eb7-f687adc057c2)

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: c189832 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RenechCDDA** [comment]
>Attach save file
>N/A mapgen produced it

So instead of being able to open your save and immediately identify the OMT and nest which lead to this we should instead blindly stab at the generation until we can get a reproduction?

Please provide the save file as the issue template tells you is mandatory.

**Comment by CoroNaut** [comment]
I left out the save file because this bug is in no way related to my specific save file and was therefore unnecessary and wouldn't help solve the issue in this instance. The OMT is in the picture, but in text it is "Science Lab Tower." I also don't recommend messing with nested mapgen. I'm sorry that my issue was confusing. I can expand and give you more information to help fix the bug I'm talking about. There are four lab ends: the collapsed hallway, the library, the military bunker, and the containment lab ends. This is the file containing them: https://github.com/CleverRaven/Cataclysm-DDA/blob/db664ab68fcb2ed148a799853ca942ab6a48e20c/data/json/mapgen/lab/lab_floorplans_1side.json#L3-L34

These lab ends generate on every level of the science lab tower because of the 2x3 OMT shape with one corner missing. The adjacent corner to the open air corner is always a lab end:https://github.com/CleverRaven/Cataclysm-DDA/blob/db664ab68fcb2ed148a799853ca942ab6a48e20c/data/json/overmap/multitile_city_buildings.json#L2875-L2921

This is where lab ends generate in mapgen.cpp:https://github.com/CleverRaven/Cataclysm-DDA/blob/db664ab68fcb2ed148a799853ca942ab6a48e20c/src/mapgen.cpp#L5447-L5449

>  we should instead blindly stab at the generation until we can get a reproduction?

That's the wonder of the debug menu map editors. We can recreate the scenario without just blindly letting the game generate it. If you mean blindly getting it from the debug menu, I personally wouldn't count 10 seconds of generating it as tedious or difficult. It really isn't necessary in the case of this bug, it's fairly obvious from the floorplan and mapgen code not knowing the difference between floor plans with or without solid rock. A simple fix would be to convert solid rock to concrete wall if level 1 or above.

If you want to specifically place the 1side floorplans and collapsed hallway:
1. Load game
2. Open main menu -> Map -> Map editor -> "Edit overmap/mapgen"
3. Filter for "tower_lab_stairs"
4. Place design at level 1+
Please note that the generation defaults to lab intersection designs, if you want lab ends, select an overmap tile adjacent to another tower lab overmap. If you want to place a lab tower, you can do Debug menu -> Map -> Overmap editor -> Place overmap special -> "office_tower_hiddenlab". You can generate your own lab very quickly. Major props to the people who made the editors.

Here is a fresh testing save file showing that mapgen can produce the bug since you weren't convinced:
[Lincolnshire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13773485/Lincolnshire-trimmed.tar.gz)
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: db664ab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
Please let me know if you want more info about the bug or want me to generate more instances of it.

**Comment by RenechCDDA** [comment]
> I left out the save file because this bug is in no way related to my specific save file and was therefore unnecessary and wouldn't help solve the issue in this instance

I literally told you how it would help.

>I can expand and give you more information to help fix the bug I'm talking about.

If you provide your save as it requests you can spare yourself writing this post again in the future, since it is far, far, faster for me to simply open the save and find the information myself.

**Comment by CoroNaut** [comment]
> I literally told you how it would help.

And I told you how I provided that information in the original post. Feel free to not fix the bug if you don't see the information you need.
