### ISSUE TITLE
Smashing/Deconstructing Sandbags at minefields causes CTD

### ISSUE THREAD

**Issue by BestivusStanleyUpas** [CleverRaven/Cataclysm-DDA#70435]
### Describe the bug

When coming across sandbag barricades at minefields when trying to smash or deconstruct it cause game to crash to desktop. If I restore to older version I do not get the problem.

### Attach save file

[Ashland-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13765407/Ashland-trimmed.tar.gz)
[Ashland-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13765409/Ashland-trimmed.tar.gz)

### Steps to reproduce

Stand in front of sandbag and try to smash or deconstruct it will lock and CTD

### Expected behavior

I expected the sandbag to be demolished so I could proceed

### Screenshots

<img width="1920" alt="bugsplat" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/121656823/e2ee8e62-166b-46d4-91de-927326fa6dc1">
<img width="1920" alt="bugsplat" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/121656823/f320060f-f072-409d-95ed-223e22e99139">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: bdf6181 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
Something is wrong, but I cannot quite confirm the report:
- Downloaded one of the save copies (not sure which one).
- Smashed the sand bags in front twice,
- Game got stuck in what's probably 100% CPU for a number of minutes.
- Error report pops up:
 DEBUG    : Stray characters at end of floating point value 0.000000 in item::get_var

 FUNCTION : get_var
 FILE     : C:\Cataclysm-DDA\src\item.cpp
 LINE     : 1711
 VERSION  : 0.G-5972-g0600cfc627-dirty (the "dirt" is #70411)

It can also be noted there was an error report on loading about some unicode character that couldn't be matched.
- After copying the error report I wrote this, as well as noted that the sand bag wall had resulted in piles of what was probably sand all over the place.

**Comment by GuardianDll** [comment]
/confirmed, the game has difficulty spawning 40000 bags with 1 sand because it is how the game threats twenty of 
```json
  {
    "id": "sandbag",
    "type": "item_group",
    "items": [ { "item": "material_sand", "count": 2000, "container-item": "bag_durasack" } ]
  },
```
