### ISSUE TITLE
Removing firearm mods in unloading zone duplicates mods

### ISSUE THREAD

**Issue by Achpile** [CleverRaven/Cataclysm-DDA#70448]
### Describe the bug

As the title says.

### Attach save file

N/A

### Steps to reproduce

1. Get any firearm with mod(s)
2. Create "Items Unload zone" and select "Yes, remove mods"
3. Put your Gun in the zone and use 'O' to unload everything in that zone
4. Now uninstalled mod is duplicated. One is on the ground and second one is in your inventory.

### Expected behavior

I expect the mods to be on the ground only.

### Versions and configuration

- OS : Ubuntu 23.10
- Game version : 0.G-4 (http://ru.archive.ubuntu.com/ubuntu/ubuntu/pool/universe/c/cataclysm-dda/cataclysm-dda-sdl_0.G-4_amd64.deb)

**Comment by CoroNaut** [comment]
Another issue that is related to removing mods from guns in unload zone #69483.

**Comment by Achpile** [comment]
Just checked it in experimental. Seems to be fixed, sorry for making issue before checking the latest build
