### ISSUE TITLE
Game crashes when returning from peeking down stairs at a subway station

### ISSUE THREAD

**Issue by mini-bomba** [CleverRaven/Cataclysm-DDA#70452]
### Describe the bug

The game crashes when trying to return from peeking down some stairs at a subway station. Does not happen everywhere, seems consistent in this area. Going up and down the stairs seems to work fine.

### Attach save file

[Megler-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13771566/Megler-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save file
2. Move to the nearby stairs leading into the subway station
3. Peek down the stairs
4. Press ESC to return from peek
5. Game crashes

### Expected behavior

no crash :)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-6014-gf94a31e351 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Crash log: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13771594/crash.log)

**Comment by TealcOneill** [comment]
@GuardianDll I tried copying it in this save and repeatedly in various subways in a new save and after >100 attempts I can't replicate it.

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-15-1833 7f06e9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
