### ISSUE TITLE
 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]

### ISSUE THREAD

**Issue by lokkiser** [CleverRaven/Cataclysm-DDA#70457]
### Describe the bug

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            invalid L
 id "null"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]
 FILE     : src/generic_factory.h
 LINE     : 478
 VERSION  : 0600cfc

19:03:25.553 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid L
 id "null"

### Attach save file

[White City.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13773226/White.City.zip)

### Steps to reproduce

Press V (items around)

### Expected behavior

No error

### Versions and configuration

CDDA experimental build 2023-12-24-0559
Running via Catapult

- OS: Windows
    - OS Version: 10.0.19044.3086 (21H2)
- Game Version: 0600cfc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Minimod: No Skill Rust [minimod_no_rust],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Mythical Martial Arts [MMA],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks],
    Created Bionics  [CreatedBionics],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13773240/debug.zip)

**Comment by RenechCDDA** [comment]
Looks like you caused this by setting an invalid mutation(s) through the debug menu. Did you do that?

**Comment by lokkiser** [comment]
I really did that.
I added mod Minimod: No Skill Rust [minimod_no_rust], to already created world
Then some time later i added a few vanilla perks. They seemed to have no prior requirements. Any way to determine which is culprit?

**Comment by Maleclypse** [comment]
Unfortunately this isn’t a bug to be fixed then. My suggestion would be to remove everything you added via debug until it works again and if not possible start a new game and don’t debug in random things in a save you care about. Good luck!
