### ISSUE TITLE
[Sky Island] The warp shards recipes aren't as obvious at first

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#70453]
### Is your feature request related to a problem? Please describe.

Considering the recipes which uses the warp shards are in the 'warp' subcategory in the 'other' category, it may not be obvious at first that you can craft with it unless you gone out of your way to find it, which i feel is not ideal.

### Solution you would like.

Make it its own category instead of being in a subcategory.

### Describe alternatives you have considered.

Not doing so.

**Comment by MrHrulgin** [comment]
I think I originally found out their uses by examining them and seeing the list of craftable items in the description, but having a mod-specific category for crafting would certainly make finding them easier if you were exploring the crafting menu.

**Comment by Standing-Storm** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/6c30d4b0-c0d9-4a8c-be9f-dd45126c147e)

Alright, I'll do it
