### ISSUE TITLE
Carnivore develops Scurvy

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#70474]
### Describe the bug

My late-game Chimera mutant has developed Scurvy due to subsisting exclusively on smoked meat, despite the Carnivore mutation ostensibly making it so you don't have to worry about that.

This could have something to do with the character being a biokinetic (MindOverMatter). Maybe the Efficient System (BIOKIN_NEEDS) multiplier to vitamin absorbtion rates interacts weirdly with the negative vitamin_rate from Carnivore or something.

Alternatively it could be an interaction with another of my dozens of mutations.

### Attach save file

[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13779054/Mindssachusetts-trimmed.tar.gz)

### Steps to reproduce

Make a carnivore, set up an eating zone with nothing but smoked meat and see if they develop scurvy I guess.

### Expected behavior

Carnivores can live off meat without suffering from vitamin deficiencies.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 92a3704 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

**Comment by actually-a-cat** [comment]
Carnivore does significantly reduce the need for vitamin C. It gives you +3 vitC per hour, the natural decay is -4 per hour.

Personally I like it this way, because mutants are supposed to be not put together quite right, and the challenge of getting vitamin C while being unable to eat all the usual sources is mildly interesting.

**Comment by Terrorforge** [comment]
That means you're doing about -24 per day, thus hitting the first penalty level at -2800 after 117 days - which about matches my experience, having been a Carnivore for something like one or two seasons.

I feel like almost 120 days is long enough that it becomes a complete non-issue for 90% of players, but blindsides the remaining 10% (me) so badly that it feels like a bug. I think it should be adjusted one way or the other, so it either actually removes the need to consume vitamin c entirely, or the scurvy actually kicks in some time before winter.

And either way it would be nice to have a little note in the description about this mechanic.

**Comment by Icantthinkofanameforthis** [comment]
gummy or multivitamins it back up?

**Comment by db48x** [comment]
Does the game just not know that even meat contains some vitamin C? Apparently the liver of the polar bear actually has enough vitamin C in it to be toxic to humans. Cooking destroys much of the vitamin C in food though, usually due to the heat. Smoking leaves more of it intact, since it doesn’t heat the meat as much.

**Comment by Terrorforge** [comment]
Some meats such as fish, sweetbread and lung do contain small amounts of vitamin C. As does mutant meat, apparently. But your standard"chunk of meat" does not.

Also you're thinking of vitamin A. Vitamin C is almost impossible to overdose on, because it's a water soluble vitamin that doesn't accumulate in the body the way a fat soluble vitamin like A does.

**Comment by Maleclypse** [comment]
I'm going to update the description to state that "Unless you eat the parts of the meat that include vitamin C you will need to find an alternative source roughly once a month."
