### ISSUE TITLE
"overmap" should be optional in fixed special definition

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#70471]
### Is your feature request related to a problem? Please describe.

Currently the only way to check locations on a fixed special is to define a map to override that location. That works ok if ugly for singular location checks as in the below example, but not for multiple location checks while preserving the existing assigned OMT.
This means #70339 will be considerably more messy than it could be for say islands where for the regular maps I can make them handle ocean and lake predecessors, but the special definition can't handle me checking for [ "lake_surface", "ocean_surface" ] on the surrounding tiles without replacing them with a singular map (which while you could make a hacky solution for correct terrain you couldn't have it show up correctly on the map)

### Solution you would like.

I'd like

```
  {
    "type": "overmap_special",
    "id": "lake_shore_dock_small",
    "overmaps": [
      { "point": [ 0, 0, 0 ], "overmap": "lake_surface", "locations": [ "lake_surface" ] },
      { "point": [ 1, 0, 0 ], "overmap": "lake_dock_small_north", "locations": [ "lake_surface" ] },
      { "point": [ 2, 0, 0 ], "overmap": "lake_surface", "locations": [ "lake_surface" ] },
      { "point": [ 0, 1, 0 ], "overmap": "lake_shore", "locations": [ "lake_shore" ] },
      { "point": [ 1, 1, 0 ], "overmap": "lake_shore_dock_small_north", "locations": [ "lake_shore" ] },
      { "point": [ 2, 1, 0 ], "overmap": "lake_shore", "locations": [ "lake_shore" ] }
    ],
    "city_sizes": [ 1, 20 ],
    "occurrences": [ 0, 5 ],
    "flags": [ "CLASSIC", "LAKE", "MAN_MADE", "WILDERNESS" ]
  },
```

to be able to be written as

```
{
    "type": "overmap_special",
    "id": "lake_shore_dock_small",
    "overmaps": [
      { "point": [ 0, 0, 0 ], "locations": [ "lake_surface" ] },
      { "point": [ 1, 0, 0 ], "overmap": "lake_dock_small_north", "locations": [ "lake_surface" ] },
      { "point": [ 2, 0, 0 ], "locations": [ "lake_surface" ] },
      { "point": [ 0, 1, 0 ], "locations": [ "lake_shore" ] },
      { "point": [ 1, 1, 0 ], "overmap": "lake_shore_dock_small_north", "locations": [ "lake_shore" ] },
      { "point": [ 2, 1, 0 ], "locations": [ "lake_shore" ] }
    ],
    "city_sizes": [ 1, 20 ],
    "occurrences": [ 0, 5 ],
    "flags": [ "CLASSIC", "LAKE", "MAN_MADE", "WILDERNESS" ]
  },
```

Ideally omitting "overmap" would also suppress the overwritten by connection error so you could control the terrain connections can spawn on outside their normal restrictions (to prevent road connections being allowed on rivers for example)
https://github.com/CleverRaven/Cataclysm-DDA/blob/6bd70ae1f8f9280d5a0f2a2ce81601a21198e9d9/src/overmap.cpp#L1344-L1347

### Describe alternatives you have considered.

I'm trying to do this myself but aren't getting anywhere.
Mutable's check_for_locations(_area) could be made generic for both subtypes but I think that would be redundant outside of this usage and require exception handling which sounds way more of a hassle as well as being less neat.

**Comment by I-am-Erk** [comment]
What would it default to if left blank? That might get a little complex depending on how the code is written. Would it be acceptable for it to accept a list of options?

**Comment by Procyonae** [comment]
> What would it default to if left blank?

Nothing, that's my point, I shouldn't need to place a map to control where the special is placed. The way I were trying to do it is to pass down a bogus id (null or whatever) and to then treat that separately (like nests do) but there are a lot of checks present preventing this and I couldn't decide where the best place to attack it was.

> That might get a little complex depending on how the code is written. Would it be acceptable for it to accept a list of options?

If it has to be hacked it'd probably be better to make it just default to whatever map is already there. I don't think that would currently cause problems but might do in the future if peeps start say spawning specials in weird places or running update_mapgen or similar over common maps for missions or whatever.

**Comment by I-am-Erk** [comment]
Ah, I see what you're saying now. I wonder if the best solution might be to allow the equivalent to 't_null', meaning it shouldn't change.

**Comment by Procyonae** [comment]
Yeah I were trying to use the way nests pass "null" but it wasn't similar enough to hold my hand

**Comment by Procyonae** [comment]
Still can't figure out how to do this :c 
It gets read here
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/overmap.cpp#L2758
They'd need to still get found by this function called by overmap::can_place_special
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/overmap.cpp#L1392-L1397
But they get rejected twice here
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/overmap.cpp#L1275-L1313
is_valid is getting called on an oter_str_id which is a string_id<oter_t> so I think it calls
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/overmap.cpp#L389-L394
which I think calls
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/generic_factory.h#L490-L497
which calls
https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/generic_factory.h#L150-L165
and then I'm completely lost.
There's no MAKE_NULL_ID defined in https://github.com/CleverRaven/Cataclysm-DDA/blob/ee1478575ef9992ba98e6525018d08bee05b5c16/src/string_id_null_ids.cpp for oter_str_id but adding one wasn't enough

**Comment by Procyonae** [comment]
Nvm got there during the previous comment, PR coming soon ^_^
