### ISSUE TITLE
Add option to replace a damaged vehicle part 

### ISSUE THREAD

**Issue by Icantthinkofanameforthis** [CleverRaven/Cataclysm-DDA#70488]
### Is your feature request related to a problem? Please describe.

Was checking out vehicles and the frame on the drivers seat was pretty wrecked and thought i cant repair this to a safe level and i sure wish i could replace it without having to take everything off it or damage it to XX risking going too far damaging the other components

### Solution you would like.

An option to be able to switch out any vehicle part below ++ durability as if you were repairing an XX damaged part

### Describe alternatives you have considered.

There is the option of removing the max durability thing if you wanted to go down that route

### Additional context

Sure hope nothing bad happens driving this thing around
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/71b7238e-764c-451f-b6fa-f327aaefbcad)

**Comment by PatrikLundell** [comment]
A problem with replacement is that you have to remove everything "sitting on top" of it before you can remove and reinstall a part. For a seat that means first removing the seat belt (easy and quick to do), while for a frame it means removing everything mounted on that frame.
The fact that you can "repair" a part with XX status by magically replace it is really a bug (or deficiency in the simulation): you really should remove everything mounted on it, remove it, install a new part, and then reinstall the parts (recursively) mounted on it.

I wouldn't object to the ability to go through this sequence with a single order, though, as long as the time taken and resources consumed remained the same (but you would then run the risk of dehydration and heat stroke, as well as being interrupted by night fall). It can also be noted that you might not actually want to reinstall all the other parts, as you may want to replace some of them with ones in better condition.
