### ISSUE TITLE
Game crashes after 'w' (wield) hotkey press.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#70489]
### Describe the bug

Game crashes after typing 'w' for wield.

Intermittent crash, no crash.log generated, able to wield items through inventory, but typing 'w' makes game instantly crash.

It SEEMS like immediately [S]aving and reloading the game (not restarting the game) makes 'w' open the wield menu properly, but if it works and I do it again, [S]ave and reload, then it will ALWAYS crash the next time I hit 'w'.

This was happening for the last two game versions I've compiled.  Since I'm not seeing any bug reports on it, perhaps it's my game file?

### Attach save file

[Justus-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13782729/Justus-trimmed.tar.gz)

### Steps to reproduce

1. open save file.
2. hit 'w' to open wield menu.
3. if game doesn't immediately crash, 'S'ave and exit, then reload the save.
4. hit 'w' to open wield menu. - My game will have crashed by now.

### Expected behavior

no crash.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-6020-g92a370408d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sly's Skill Antirust [slysskillantirust]
]

### Additional context

debug.log below.  No crash.log found (should it be in same folder as debug.log?).

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13782789/debug.log)

**Comment by harakka** [comment]
Please check if this still happens on https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-12-28-0421 or newer. I don't know about crash log not generating, but otherwise potentially sounds like #70156 which was fixed there.

**Comment by PatrikLundell** [comment]
I've seen it, but haven't written a bug report since the save compression results in saves that are too large. It can be noted that the version I've seen it on was about two days ago, and thus should be older than the one @harakka refers to.

**Comment by epsimpson** [comment]
Sorry about the delay - Just compiled 0.G-6049-gd1ecdf45f4 and I haven't gotten it to happen.  Good job!

**Comment by RenechCDDA** [comment]
Closing as completed, then.
