### ISSUE TITLE
Scanned books aren't being properly migrated

### ISSUE THREAD

**Issue by mini-bomba** [CleverRaven/Cataclysm-DDA#70493]
### Describe the bug

Books scanned in previous versions of the game drop out of the device when attempting to bring up the "read stored books" menu (or even enabling a flashlight)
Seems like books can be properly scanned and read after they drop out.

### Attach save file

[Megler-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13786471/Megler-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. Experience errors about batteries being in invalid pockets, continue anyway (errors such as `Non-mod light disposable battery in MOD pocket!`)
3. Activate the smartphone in character's inventory (or any of the e-ink readers on the floor, near the water purifier)
4. Pick "Read stored books"
5. Experience more errors (errors such as `item manual_kickboxing cannot fit into any pocket while loading: pocket with type (CONTAINER) not found`)
6. Move once
7. See books fall out of your inventory

### Expected behavior

No errors occur, books stay in my devices

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/55105495/0f397e01-cff8-41b1-b842-a2b8bf6c89fe)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-6046-g8f6b2d45fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

The attached save was last loaded with a version compiled from commit [2680307575](https://github.com/CleverRaven/Cataclysm-DDA/commit/26803075758565bcfc9c4791c17eabf00af3cb2f)
Quickly looking at the commit history since that commit, I suspect PR #70475 might be related to this.

**Comment by RenechCDDA** [comment]
>The attached save was last loaded with a version compiled from commit [2680307575](https://github.com/CleverRaven/Cataclysm-DDA/commit/26803075758565bcfc9c4791c17eabf00af3cb2f)
Quickly looking at the commit history since that commit, I suspect PR https://github.com/CleverRaven/Cataclysm-DDA/pull/70475 might be related to this.

The commit you've listed is before that PR was merged, or am I misunderstanding?

**Comment by mini-bomba** [comment]
> The commit you've listed is before that PR was merged, or am I misunderstanding?

Yes, the save was last loaded before the PR was merged, but the errors pop up when loading with a version after the PR was merged ([8f6b2d45fa](https://github.com/CleverRaven/Cataclysm-DDA/commit/8f6b2d45fa74b6ebe92035366da7a0ac293e5a37) is listed in the versions section)

**Comment by mini-bomba** [comment]
This can also be replicated without a new save and one version switch:
- Create a new save on a version before the PR
- Scan any book into your phone
- Save & quit
- Load the same save on a version after the PR
- Attempt to open the read stored books menu on your phone
- Book falls out

While with a single book it doesn't seem like a huge issue (and at least the book falls out instead of being completely deleted), with my collection of books on my save it might take even a whole day to scan the books back into the phone. Oh and it'd create a lot of books, since I've got the library copied on quite a few devices.

**Comment by snipercup** [comment]
I have this too. Books disappear from the e-ink tablet pc and drop to the ground. As a workaround I am saving my books to a memory card and loading them in again. Now I am getting stacks and stacks of books (which will do well with traders)
```
- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 394f235 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

```

**Comment by Dirtbug** [comment]
It seems like even new books that I scan into my e-ink tablet don't show up when i try to read them and then fall out of the tablet the next time I try to use it. The same thing happens if I load them into the tablet from a memory card too, even if the books were saved to the memory card in the current version.

**Comment by Caboozles** [comment]
The Atomic Smartphone seems to take that even one step further. If I attempt to turn it on or listen to music it'll give those same errors and dump out my books. This doesn't seem to have anything to do with a new version on my end, as I'm encountering this anytime I turn that on.

**Comment by snipercup** [comment]
What's also weird is when the weight of my e-ink tablet pc increases to 124.4 and I cannot carry it anymore, as if it's the same weight as the books it contains. This happened after I had already dropped the stacks of books a few times. Now there are too many to trade but I guess they make good fuel for the fire
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/ce8895d5-6607-4620-95a9-38cce5d1cd70)

**Comment by mini-bomba** [comment]
> The Atomic Smartphone seems to take that even one step further. If I attempt to turn it on or listen to music it'll give those same errors and dump out my books.

Had the same happen with my regular phone, noted in the issue message with "(or even enabling a flashlight)"

**Comment by Fox-Ball** [comment]
Can confirm this has happened to me on build 2024-01-02-1713. This was after starting a new game as well that build. Scanned three manuals into the phone then activated it and loat them from the phone and duping them onto the ground/inventory.

**Comment by yamil-90** [comment]
tested again with build cdda-linux-tiles-sounds-x64-2024-01-07-0126, had the same problem again with the tablet but the smartphone works fine
