### ISSUE TITLE
Change names of release files, remove build number from filenames in github release page

### ISSUE THREAD

**Issue by KawaiiSelbst** [CleverRaven/Cataclysm-DDA#70505]
### Is your feature request related to a problem? Please describe.

Yes. Some users use console application managers, for example scoop, or launchers for cdda, it is possible to get version 0.G automatically from https://cataclysmdda.org/releases/ page by regular expression `The most recent stable release is ([\\\d\\\-.A-Z]+)?( )` and substitute it instead of `$version`:

`https://github.com/CleverRaven/Cataclysm-DDA/releases/download/$version/cdda-windows-tiles-sounds-x64-msvc-2023-03-01-0054.zip`.

But to get the build number for example `2023-03-01-0054`, will not get it automatically, and you have to change manifest files by hand at each release, instead of the automatic update system to do it. 

### Solution you would like.

Name releases like `cdda-windows-tiles-sounds-x64-msvc.zip`, their versions are already in the link and release description, and inside the archive in the VERSION.txt file, it would make life very easy for those who maintain manifests for console managers and launchers

**Comment by ZhilkinSerg** [comment]
I am not sure which exact problem you are trying to resolve, but you are probably approaching it from a wrong angle. The correct approach is to use Github API to list CDDA releases (i.e. https://api.github.com/repos/CleverRaven/Cataclysm-DDA/releases), then parse the output - there are filenames for assets, tag names, dates and whatnot.
