### ISSUE TITLE
Massachusetts Mod can't start a new game on experimental build

### ISSUE THREAD

**Issue by pjmsam** [CleverRaven/Cataclysm-DDA#70526]
### Describe the bug

When using Massachusetts Mod,it can't start a new game,it say unable to generate a valid starting location,
![cdda1](https://github.com/CleverRaven/Cataclysm-DDA/assets/55694406/a340eec2-9cd9-4587-a7e5-1567b75f0397)

### Attach save file

N/A

### Steps to reproduce

![cdda1](https://github.com/CleverRaven/Cataclysm-DDA/assets/55694406/10f8c5e0-6096-4df2-b249-bdd600eaded7)
start a new world with only Ma mod,build a character,and can't start the game

### Expected behavior

fix the issue,thank,really don't want to go back play stable

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 6ae463e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

can't start with MA mod

**Comment by pjmsam** [comment]
it seems like SELECT_STARTING_CITY cause the "unable to generate a valid starting location" problem(which is true in MA mod). because even don't use MA mod but set
SELECT_STARTING_CITY  to true will also cause this problem,

but even set it to false the MA mod still can't start ,please see the screenshot
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/55694406/df7cf8d3-13ff-4d70-8221-fd29d8d988ca)

this is the option cause the problem
{
    "type": "EXTERNAL_OPTION",
    "name": "SELECT_STARTING_CITY",
    "info": "Allows to select starting city in new character menu.",
    "stype": "bool",
    "value": false
  },

**Comment by I-am-Erk** [comment]
I suspect this has somethingto do with oceans

**Comment by Procyonae** [comment]
It could well do the MA maps stretch out pretty far. `.omap`s in general are working bc I'm having no problems with #70757. It could also specifically be related to the starting city stuff

**Comment by CavanStone** [comment]
> I suspect this has somethingto do with oceans

@I-am-Erk I think you are correct and here is my process for validating this:
  
1) Start a new world and game with the Massachusetts Mod
2) On the description tab of the character creation screen select a specific starting city [C] and choose Pittsfield
3) Binary search the following list to find the coast using the debug option to teleport to city: 
     [Pittsfield, Dalton, Hinsdale, Peru, Worthington, Cummington, Chesterfield, Goshen, Williamsburg, Northampton]
4) Use Teleport to adjacent overmap and reveal map debug options to fine tune your position

I have validated this three times already.  Here is my last attempt.  As you can see the town of Cummington is close to the coast in the game when it is nowhere near the ocean in real life.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/48699248/637d87eb-fb59-48a2-b668-685d1d6e1c52)

**Comment by CavanStone** [comment]
@I-am-Erk 

So there is a quick hacky fix for this.  
1) Copy over the core regional_map_settings.json file over to MA mod directory.
2) Search the json file for "ocean_start_east" and change the value to 69 (the next overmap coordinate over from the outer cape shore.)
3) Optionally change ocean_start_south to 42 (the next overmap coordinate from the south coast of Nantucket.)  I swear I am not making these numbers up!

Here I am in Provincetown, in the latest experimental version:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/48699248/05adc275-43e0-4cfb-aa39-670ebc822716)
