### ISSUE TITLE
Magiclysm enchanted weapons don't increase to-hit

### ISSUE THREAD

**Issue by TaiGambol** [CleverRaven/Cataclysm-DDA#70528]
### Describe the bug

Magiclysm +1/+2 enchantments on weapons are intended to increase the to-hit by an equivalent value, both according to the original PR implementing them and according to the current code; however, they do not currently do this.

### Attach save file

[Magiclysm Testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13799037/Magiclysm.Testing-trimmed.tar.gz)

### Steps to reproduce

1. Create player in world with Magiclysm loaded.
2. Spawn in National Guard Bayonet, Combat Knife +1, Combat Knife +2
3. Observe that to-hit does not change between the three weapons.

### Expected behavior

Weapons' to-hit scores should raise as their enchantment level raises.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47945988/d6ce9c51-4d8d-4e74-ad4c-57d16140e8aa)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2364 (21H1)
- Game Version: c5cf8ed [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

Would've tried to dig in and fix it myself, but I can't even begin to figure out what's actually causing the problem.

**Comment by GuardianDll** [comment]
`relative` field doesn't work with to_hit field, and there is no easy fix to this, not without some dose of a code, at least
/confirm

**Comment by TaiGambol** [comment]
For what it's worth, I'm at least _reasonably_ sure it used to work, but I can't pinpoint any timeframe in which it stopped working.
