### ISSUE TITLE
attachable night vision for helmets?

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#70533]
### Is your feature request related to a problem? Please describe.

What it says on the label. There isn't any night vision pocket on military helmets in game, and I think it would be a good addition considering the real life use of it.

### Solution you would like.

Add a night vision slot for army/tactical helmets, that blocks the face shield attachment. I don't know if it's possible with the current code, I haven't checked. If it isn't I'm up for a pr. That's all.

### Describe alternatives you have considered.

This may have been suggested before, I haven't throughly checked; so I don't really know the discussion around this.

**Comment by b0bhat** [comment]
Would this replace the current light amp goggles, add a new item, or is it possible to modify them to be both wearable and able to fit on the helmet?

**Comment by KeremBabaG** [comment]
add a new item that is primary purpose is to be attached but also could be worn with proper modification

**Comment by Amerinn** [comment]
wouldn't adding a pocket to the proper helmets solve the issue? aka. "this pocket can only accept infrared/light-amp goggles"

**Comment by deltanedas** [comment]
this was done above and should be closed
![%H%m%S-1](https://github.com/CleverRaven/Cataclysm-DDA/assets/39013340/a7aa78ad-1f75-4558-9e8f-8ea20f4eda2d)

**Comment by CoroNaut** [comment]
@KeremBabaG Just pinging to close the issue.

**Comment by KeremBabaG** [comment]
aight cheers
