### ISSUE TITLE
Escalating Game Performance Woes: From Laggy Moves to Complete Freezes

### ISSUE THREAD

**Issue by Radonchnk** [CleverRaven/Cataclysm-DDA#70530]
### Describe the bug

Recently, the game's performance has noticeably declined, with occasional delays of a few seconds for moves to process. However, the current situation is more severe, as the game freezes for 30 seconds or more after each input.

### Attach save file

[Peach Lake-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13799227/Peach.Lake-trimmed.tar.gz)

### Steps to reproduce

Press any move button

### Expected behavior

The game is expected to operate seamlessly, yet it consistently experiences freezing issues.

### Versions and configuration

os - Linux Mint 21.1 x86_6
Kernel: 5.15.0-89-generic 
Shell: bash 5.1.16 
DE: Xfce 4.16 
WM: Xfwm4 
CPU: 11th Gen Intel i3-1115G4 (4) @  
GPU: Intel Device 9a78 
Memory: 4665MiB / 15734MiB 

version - f94a31e
tileset, mods - standard

**Comment by Maleclypse** [comment]
Had you recently read several maps?

**Comment by Radonchnk** [comment]
Sorry, but i do not understand the question

**Comment by Maleclypse** [comment]
#70540 is this your problem? Or if you spawn a clairvoyance artifact are you over a slime pit?

**Comment by akrieger** [comment]
NPC crafting is going haywire somehow.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/fa6016b4-2ea1-4a53-8b67-06ff3046851f)

**Comment by akrieger** [comment]
Spending all its time creating a crafting inventory?
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/af9d96c6-9d08-4f07-8e54-17a5fa3f5d74)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/735afb4d-22c7-493e-87b7-664ce5d00dac)

**Comment by akrieger** [comment]
#70423 would help with this some but it doesn't fix the underlying algorithmic issue. I can't tell if there's a bug here causing a potentially infinite loop or just an inefficient process your save is exposing.

**Comment by akrieger** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/c564ec95-4a11-40cf-bbf1-28c9270c350f)

Maybe there's a large backlog that's not doing backoff correctly.

**Comment by akrieger** [comment]
What seems to be happening is an NPC is trying to do a multi craft but has a computed crafting speed of zero. This causes it to burn all of its moves (nearly 1000) one at a time trying and failing to do a craft, which is very, very expensive.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/e0fb0a29-fe48-4f33-a656-5ac68423023b)

**Comment by akrieger** [comment]
The crafting speed is reduced to zero by a manipulation limb score modifier which ends up with a negative modifier which zeroes everything out.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/29f77c75-6070-4e74-9b70-d7bb04800b6e)

**Comment by akrieger** [comment]
Then even though it is cancelled, it gets pushed into the backlog and automatically retried.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/667719/2be42544-dbdf-452e-8cf2-1f2630402c2e)

**Comment by akrieger** [comment]
This seems to fix the issue by not having the npc loop and fail constantly at crafting
```
diff --git a/src/activity_actor.cpp b/src/activity_actor.cpp
--- a/src/activity_actor.cpp
+++ b/src/activity_actor.cpp
@@ -3380,6 +3380,7 @@
     const int assistants = crafter.available_assistant_count( craft.get_making() );

     if( crafting_speed <= 0.0f ) {
+        crafter.set_moves( 0 );
         crafter.cancel_activity();
         return;
     }
```

but I don't know how to validate it for side effects.
