### ISSUE TITLE
Track dissection/butchery progress so it can be resumed?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70549]
### Is your feature request related to a problem? Please describe.

I've cleared an area, I think. I'm 45 minutes into the dissection of something interesting when a stray zombie wanders over. I kill it easily, only to look back at the dissection target to see it fully restored. This is an awful waste of time, and unrealistic to boot.

### Solution you would like.

Track how long is left on a dissection and allow it to be resumed.

### Describe alternatives you have considered.

Not doing anything.

**Comment by PatrikLundell** [comment]
It would indeed be useful. I've been in that situation a sufficient number of times that  I've started to save before beginning the process and restore the save if it's interrupted...

**Comment by DragonWizard23** [comment]
I've had the same experience. I would be happy to contribute, but this sounds like a C++ change, which is out of my depth.
