### ISSUE TITLE
[MOM] Invalid Biokinesis Practice recipes

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#70544]
### Describe the bug

Some of the biokinesis powers do not have recipes.  This throws errors / prevents learning the powers.
Recipes:
practice_biokin_dash
practice_biokin_adrenaline

Also, biokin_change_appearance doesn't have any method of learning it

### Attach save file

N/A

### Steps to reproduce

1. Create 'Star Athlete' profession and see errors

### Expected behavior

Practice recipes should exist

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 4f6178a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by Standing-Storm** [comment]
Flesh of Clay was an experiment that failed (the functions listed for changing your appearance in the EoC documentation aren't hooked up to EoCs at the moment, only NPC dialogue or item activation).  Once #70264 is done it might be possible to finish it and make it learnable.

The others are an oversight, though.
