### ISSUE TITLE
World Generation Bridge/Trailhead Mashup

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70547]
### Describe the bug

The bridges here are all screwed up.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13800133/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Spawn a world? I dunno. It looks like it might have gone weird because there's two roads with a trailhead between them all meeting at the shore?

### Expected behavior

Bridges that connect.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/94d60aa7-6258-452e-8e80-bedd19b309f6)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/8fee5dd1-5e14-4910-8d06-d7f1664ceb06)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/200d5c71-ec68-417c-8616-96feb56db608)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 04b6eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

This is a fairly valuable bridge for me in this save. If anyone knows a way to make it possible to drive over this without extensive demolition of houses, I'd greatly appreciate it. EDIT: Found the map edit options and did some adjusting.

**Comment by Procyonae** [comment]
Just for other peeps having the same issue, the way to locally fix this is to (bind the debug menu -> ) open the debug menu -> `m` map... -> `M` Map editor -> Move the cursor over the borked 24x24 OMT (you can change z level during this) -> Edit [`o`]vermap/mapgen ->`/` to search -> Enter the OMT you want (bridgehead_ground for z0, bridgehead_ramp or bridge_road for z1) -> It shows you a flashing preview -> `3` Apply if it looks right
