### ISSUE TITLE
Segfault when unloading a gallon jug of rotten milk

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#70559]
### Describe the bug

When I unload a gallon jug of rotten milk, the game crashes

### Attach save file

[Blue Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13801842/Blue.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. press / to open advanced inventory
3. Select the gallon jug with rotten milk in the inventory
4. Press e to interact with the gallon jug and select unload
5. Select pour onto the ground
6. When prompted for a direction, select any direction
7. Observe error

### Expected behavior

Not crash but instead put the milk

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50166150/758c64dd-673d-45d8-bece-cc56a32011c6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 180845b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by snipercup** [comment]
Seems like it crashes when I select any tile to unload into so I updated the description and title

**Comment by Inglonias** [comment]
Worth noting that it does not segfault when using the (`U`)nload interface (save file has container mode set to Manual, you will need to set it to automatic to unload it onto the ground)
