### ISSUE TITLE
Line of Sight Not Shown When Peeking Up Stairs

### ISSUE THREAD

**Issue by AlternateEnding46** [CleverRaven/Cataclysm-DDA#70567]
### Describe the bug

Peeking up the stairs shows absolutely nothing, preventing me from seeing what's above me ahead of time. Walking up the stairs "fixes this" if you were to go back down the stairs and peek again, but not being able to do so before seeing what's ahead is problematic. Tested to see if it reverted to being unseeable after a save, and it does. Description of the exact scenario below.

### Attach save file

[Benevolence-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13802355/Benevolence-trimmed.tar.gz)

### Steps to reproduce

1. Make a new world.
2. Make a new character (in my case augmentation associate on the High Tech Low Life scenario, unsure of if/what other scenarios are affected)
3. Find the nearest staircase and peak up staircase

### Expected behavior

I expected to be able to see what was on the Z level above me after peeking.

### Screenshots

Simply peeking
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155333597/ca213433-f48c-45b2-88a1-c183e04a72e2)
After walking up the staircase, going back downstairs, and peeking again
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155333597/67fd74d9-e77c-4c0b-a0a8-b9e5693e1b77)

downstairs

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3086 (21H2)
- Game Version: d655083 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Procyonae** [comment]
Can't reproduce this with the same mod list and profession/scenario combo on yesterday's experimental
