### ISSUE TITLE
Weapons holstered in MOLLE attached sheath and holster do not display in inventory and ignore holster type restrictions

### ISSUE THREAD

**Issue by cerix2077** [CleverRaven/Cataclysm-DDA#70561]
### Describe the bug

weapons manually holstered into a sheath or gun holster attached to a MOLLE belt are not listed in the inventory but are correctly counted as a part of the number of items contained by the belt, the sheath can holster a pistol and the gun holster can holster a knife, you can put as many items into either holster by (w)eilding a weapon and holstering that weapon from the same menu and still be correctly counted towards the number of stored items

### Attach save file

[New Eden-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13801834/New.Eden-trimmed.tar.gz)

### Steps to reproduce

1. load save attached
2. view inventory, note that the worn MOLLE webbing belt has 3 items in it
3. pickup (g) the 2 guns and knives that are 1 NE of player
4. (w)ield any of the 4 weapons then holster it through the same menu into either the nylon holster or sheath attached to the MOLLE webbing belt (notice that both the guns and knives will have the option to holster into the nylon holster or the sheath despite both weapon types only being compatible with a single one of those holstering options)
5. the item holstered will not be visible in the inventory but the number of items counted in the MOLLE Webbing belt has gone up by one as you would expext it to
6. you can wield and holster all the other weapons in the same way and can put multiple (seemingly infinit) weapons into a singular holster, all weapons holstered this way will not be listed in the inventory but will all correctly be counted towards the number of items stored in the belt
7. picking up any item after causing this bug will dump all bugged items onto the floor

### Expected behavior

Holstered weapons should not be unlisted in the inventory
Pistol holsters should only show as an option to holster pistols, sheaths should only show as an option to holster knives
Holsters and sheaths should only be able to accept one item at a time 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 180845b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

If you wield one of the weapons directly from the ground instead of picking up to the inventory first, the game will function correctly only displaying compatable holsters for the chosen item that are empty and the item will be visible in the inventory. You can drop this succesfuly holstered weapon and weild it from the ground as many time as you like and it doesn't seem to bug out. However as soon as this weapon is weilded from the inventory it will suffer from the bugs described above and will not fix until you reload the save or make a new save while the bugged weapon is on the ground. 

NOTE: It seems this bug can be recreated easily by just starting a new world and adding the MOLLE belt, a holster and sheath and some weapons to holster in them

**Comment by HarlequinD** [comment]
Just to add another symptom and test case relating to the above:

Issue:
When wielding a gun back to a holster pocket attached to a MOLLE armour, the gun disappears until a trigger event, such as activating the MOLLE armour and then cancelling the attach / remove pouch popup.

Wielding back to the MOLLE armour itself works as normal.  

Allowing an auto store of gun to MOLLE armour when picking up a new gun also causes the gun to disappear until a trigger event.

Repro steps:

1. Create new character with US ballistic vest, FN Five-seveN and a tactical pouch. Wear vest and attach tactical pouch. Drop any other pocket armour apart from vest.
2. Pickup gun (goes to tactical holster as expected)
3. Wield gun (goes to hand as expected)
4. Wield gun, select holster. Gun disappears.
5. Activate vest to trigger pouch popup, gun is dropped with message.
6. Wield gun (goes to hand as expected)
7. Wield gun, select US ballistic vest (goes to tactical holster as expected)

Video example of repro steps:
https://github.com/CleverRaven/Cataclysm-DDA/assets/21039656/cc3c4614-0330-4b54-a13a-b0ca0758f017

If this needs it's own bug write up, please let me know and I'll create a seperate one.
