### ISSUE TITLE
Character uses face to smash when not necessary

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#70565]
### Describe the bug

Starting with the Hobo profession (and subsequently with the bindle equipped), you get the "You use your face to smash the object" text (and I'm assuming an accompanying malus) even after dropping it.  Using weapons to smash things seems to work normally.

### Attach save file

N/A
I can provide a save file if nobody is able to replicate this issue.

### Steps to reproduce

1. Start with hobo profession.
2. Drop bindle and attempt to smash nearby object.

### Expected behavior

The text should reflect that my hands are no longer occupied.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/52714184/6041d2c6-917c-42c3-9cf4-1333621016e0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: f7cf4b7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungus [No_Fungus]
]

**Comment by Procyonae** [comment]
Amusingly this isn't even the message for smashing something with your head, it's for smashing something with your **eyes** or **mouth** 😂

**Comment by Maleclypse** [comment]
It’s based on most armored part of your body.

**Comment by ANickelN** [comment]
> It’s based on most armored part of your body.

Okay, my hands, feet and head were equally unarmored seeing as it is the hobo start. 
Why is the face chosen as the default hitting point of those three?

I can't find it in the code, is there a malus for hitting with your face instead of your hands/feet?

If there is:
The selection doesn't make sense because it can prevent your character from escaping a situation he would otherwise be able to escape because he doesn't want to hurt his hands/feet.

If there isn't:
Is there any reason the player would ever be hitting anything with their head if they weren't completely otherwise disabled?  That seems like a great way to give yourself a concussion, and more something that a feral or zombie would do, not a human.

**Comment by fairyarmadillo** [comment]
A wolf or a bear mutant might conceivably bite an object to "smash" it, but I think we can safely remove the ability to use eyes/mouth to smash and if it's needed, re-add it in for fangs later, once they're integrated items.

**Comment by ANickelN** [comment]
> Being able to smash with any body part was purposefully implemented as a move towards non-human body shapes, I don't think arbitrarily excluding body parts is the way to go. It should simply weight manipulation scores more heavily.

Be as it may, it still seems strange that a baseline human would be smashing things with their face if they were given any other option.
