### ISSUE TITLE
No really, make a default keybind for auto-travel mode

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#70562]
### Is your feature request related to a problem? Please describe.

Auto-travel mode is an indispensible tool for navigating dense forests and other similar terrain easily. This feature can single-handedly make traveling long distances much, much easier. This feature already exists, it's in the game, it works great. But it doesn't have a default keybind.

### Solution you would like.

Someone think of a good place to put this. After a little experimentation, I noticed the `Backspace` key is open.

### Describe alternatives you have considered.

My personal preference is to disable the vi-keys (hjkl) and bind auto travel mode to `l` as in "lima", but I realize that may not be the best idea for many reasons.

**Comment by Inglonias** [comment]
Nope. Backspace is for casting spells. Dammit.

**Comment by MrHrulgin** [comment]
I've only ever done it from the map, using Shift-W to set the destination and then again to start moving. A default single-press keybind for something that would automatically move a character long distances seems risky for anyone who might accidentally press it.

**Comment by Inglonias** [comment]
It doesn't automatically move a character over long distances. It's more like a smart "move in this direction" button. It lets you automatically avoid obstacles while moving.

The video below demonstrates its behavior. After turning auto-travel mode on, I only needed to hold the "go north" button to traverse the forest.


https://github.com/CleverRaven/Cataclysm-DDA/assets/2125926/88e4b624-035f-489f-ab59-9ac4e58e6aa9

**Comment by db48x** [comment]
I use F5 for that.

**Comment by ANickelN** [comment]
This would be a great addition to a default keybind.  Makes travel through anyplace with movement hampering foliage or items much safer.

**Comment by physics-enthusiast** [comment]
TIL auto-travel exists.

**Comment by db48x** [comment]
CDDA and Factorio are both games that really reward the player for closely reading the list of available keyboard shortcuts.
