### ISSUE TITLE
player is too big to fit into the inflatable boat.

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#70564]
### Describe the bug

The player character is unable to enter an inflatable boat due to it not having enough space to fit them, due to the recent changes involving vehicles.

### Attach save file

[Droplets apon Droplets-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13802212/Droplets.apon.Droplets-trimmed.tar.gz)

### Steps to reproduce

1. Place "Inflatable boat"
2. attempt re-entry (your character spawns ontop of the seat, so to get the bug you will have to leave the boat)

### Expected behavior

I should be able to fit into the boat.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 6bd70ae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by fairyarmadillo** [comment]
Will bundle this into #70560 , thanks for the heads up!
