### ISSUE TITLE
Can't load save file

### ISSUE THREAD

**Issue by meditans** [CleverRaven/Cataclysm-DDA#70576]
### Describe the bug

I am not able to load this save file. I was probably using an older version of CDDA before, then I updated my system (NixOS), and now I encounter errors in loading the save.
I tried a couple of old revisions of CDDA compiling them myself, and I can get the save to run in a very old one, but it's just broken there. I can try out specific revisions of CDDA, but I'm not sure how I should figure out which.

### Attach save file

[PortArthur.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13804590/PortArthur.tar.gz)

### Steps to reproduce

Try to load the save. You will see some errors, then at the end you will be brought to the home screen again.

### Expected behavior

The save should be playable

### Versions and configuration

- OS: NixOS
- CDDA version: I tried a couple of them, I would be happy to continue the game in any revision

**Comment by ZhilkinSerg** [comment]
```
      "game_start": {
        "event_counts": [
          [
            {
...
              "game_version": [ "string", "git-2022-01-09-0d43a6e2" ]
            }
...
          ]
        ]
      }
```

```
      "game_load": {
        "event_counts": [
          [ { "cdda_version": [ "string", "git-2022-08-20-f65b2bc4" ] }, { "count": 1, "first": 23894113, "last": 23894113 } ],
          [
            { "cdda_version": [ "string", "git-2022-01-09-0d43a6e2" ] },
            { "count": 11, "first": 23640767, "last": 23894007 }
          ],
          [
            { "cdda_version": [ "string", "git-2023-05-12-b1b524eb" ] },
            { "count": 2, "first": 23894113, "last": 23901092 }
          ]
        ]
      }
```
