### ISSUE TITLE
[Old Lab Removal] New place to access the CVD

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#70580]
### Is your feature request related to a problem? Please describe.

The CVD (Chemical Vapor Deposition Machine) is currently only found in old lab finales

### Solution you would like.

A new way to access the machine itself or its functionality through dialogue
Suggested locales: Research Center, chemistry (non-mutagen) labs, ~~unlockable through Hub 01's ancilla bar~~

### Additional context

CVD terrains:
https://github.com/CleverRaven/Cataclysm-DDA/blob/eaa25f5692105726ed2df82d0a13f57fbad0e45f/data/json/furniture_and_terrain/terrain-manufactured.json#L494-L548

**Comment by PatrikLundell** [comment]
I'm not sure locking general functionality behind Hub01 is a good idea, given that you may end up not pursuing that faction because of faction rivalry. 

IF you wanted to provide that functionality for that faction only you could instead have Hub01 do the job for you via dialog.

**Comment by Procyonae** [comment]
I pretty much haven't touched NPC stuff in game, is the faction rivalry stuff implemented?
Which factions is/will it be between?

**Comment by PatrikLundell** [comment]
As far as I understand the Exodii and Hub01 are very much at odds. The Exodii are supposed to have encountered Hub01 variants before, and those tend to become hostile. Hub01, on the other hand doesn't know it will become hostile to the Exodii it doesn't yet know about,.
There are missions for both aimed against each other, and there's supposed to be a breaking point where you have to choose sides, although I don't know if it's been implemented yet.

I also don't know what Hub01 thinks about mutants, but would expect them to be wary of top predator types, but they might feel safe in their bunker and just think they can handle mutants...

I don't think many factions are particularly thrilled about characters with deep ties to Hell's Raiders either. Obviously the Old Guard and Hell's Raiders are at lethal odds (and there are recent additions I'm not thrilled about, given that the non existent "reward" (well, some garbage equipment of no particular value) for performing very dangerous missions for the Old Guard is active hostility from Hell's Raiders: I'm not going to do any Old Guard stuff with any future characters, as it's almost as annoying as portal storms).

In general, I don't think it's a good idea to lock content behind faction affinities unless said content is directly tied to that faction. Hub01 has its gear, which is fine, as it's good, but you can manage without it (although the important piece can be found only in deep danger you may be unable to reach unless you have the item from Hub01). The Exodii have the CBMs, which I think is more problematic. You can still find CBMs in the wild (especially from zomborgs, which presumably aren't going to disappear any time soon), and there are still autodocs (and possibly live medics) capable of performing the operations, but I think your only source of a "starter kit" allowing you to use the CBMs is with the Exodii. On the other hand I don't have an issue with specific CBM related equipment available only via the Exodii (their blueprints and equipment for the cooling suit, for instance, although I'd like to see corresponding items from other factions, in particular Hub01, as overheating is a constant issue, at least until winter). Starting to get CBMs from the Exodii and then turn against them is not a good idea (although I don't think the consequences have been implemented).

**Comment by Procyonae** [comment]
I don't think this means it would necessarily have to be restricted in the long run, you could have the exodii "acquire" the tech later on (even through a quest where you take it or blueprints of it or something) but it'd probably be better short term just moving it somewhere where this isn't a potential future problem

**Comment by kevingranade** [comment]
There's absolutely no reason to keep the CVD machine available and working at all.  The only functionality it has is nonsense and it can just be discarded with no loss to the game.
