### ISSUE TITLE
Add map extra: Shelter transport accident

### ISSUE THREAD

**Issue by Rabadash94** [CleverRaven/Cataclysm-DDA#70585]
### Is your feature request related to a problem? Please describe.

At the refugee center, some NPCs mention being transported on several buses, and that not all of them made it to the shelter, but exploring the map shows nothing of the sort.

### Solution you would like.

Add a new map extra: a crashed bus surrounded by zombies, with some dead refugees lying around. This map extra should appear a few times in a relatively wide radius around the shelter (no idea if that is possible). In addition to immersion and coherence, it could be a way to detect the proximity of a shelter if its location has not been found.
There could also be some survivors.

**Comment by Procyonae** [comment]
I don't think there's any way to have these spawn around the refugee centre other than spawning them via an invisible quest but I don't think we can initiate a quest when an OMT is placed (not reality bubble generated) so having them spawn in advance might be awkward (If someone else could figure this out I'd happily do the map for it)

Other than that this could be achieved as part of 24x24_road_vehicles_special as an alternative to a map extra though it'd lack an map note is that's desired.

**Comment by PatrikLundell** [comment]
While it would fit with the narrative, I don't think it's good from a game play perspective, as it would act as blockers for the player's ability to reach the refugee center. Early game characters tend not to be equipped to handle a zombie mob, and so would be kept from reaching the starting quest hub until they've acquired the means to break through.

For the same reason I don't think it's good to have survivors in those wrecks. It's demoralizing to have to see survivors getting slaughtered as you get there (we already have the various soon to be dying human resembling critters), when you don't have the means to intervene (assuming you'd be able to do so in time even if you had them). It's also weird to have people surviving at the location until you reach it unless it's on the first day, in which case the casualties may just start to get up.

Also, the quest structure has you run back and forth on errands for the refugee center, often ferrying volumes of goods that would be a pain to haul on foot (large cardboard boxes...). Blocking the road (or roads, if you're lucky enough to have more than one) with mandatory wrecks you often can't bypass would not be fun at all.

**Comment by Rabadash94** [comment]
>While it would fit with the narrative, I don't think it's good from a game play perspective, as it would act as blockers for the player's ability to reach the refugee center. Early game characters tend not to be equipped to handle a zombie mob, and so would be kept from reaching the starting quest hub until they've acquired the means to break through.

I don't see how that could happen. Suppose that three accidents appeared around the shelter, at distances in OMTs of, say, 70 W, 85 N and 90 S respectively. That leaves spaces, I think, big enough for a player to reach the center.

>For the same reason I don't think it's good to have survivors in those wrecks. It's demoralizing to have to see survivors getting slaughtered as you get there (we already have the various soon to be dying human resembling critters), when you don't have the means to intervene (assuming you'd be able to do so in time even if you had them). It's also weird to have people surviving at the location until you reach it unless it's on the first day, in which case the casualties may just start to get up.

I was not referring to the survivors being in the same area as the accident, but rather at a certain distance, perhaps with an injury, and unable to reach the shelter without help. They could be the target of a mission and not spawn until assigned.

>Also, the quest structure has you run back and forth on errands for the refugee center, often ferrying volumes of goods that would be a pain to haul on foot (large cardboard boxes...). Blocking the road (or roads, if you're lucky enough to have more than one) with mandatory wrecks you often can't bypass would not be fun at all.

Life is hard, especially when the end of the world comes.

**Comment by PatrikLundell** [comment]
If you have the bus crashes reasonably far away from the refugee center I definitely find it reasonable.

I don't have an issue with quests to rescue people who managed to get away from the crash sites. The issues there would be narrative ones:
- Who would know where they are, but unwilling or unable to rescue them? I can think of the case where someone is injured, someone else is staying behind to help, but it's too far away (and dangerous) for those who continued on to return and carry the injured person on a stretcher, so they need the help of someone with a vehicle, or, barring that, someone to deliver food regularly to the ones left behind until the player is able to get hold of a vehicle.
- The Refugee Center isn't exactly welcoming to additional people, so a quest give would have to be located elsewhere.

Well, I guess you can skip performing stupid fetch quests at the end of the world, especially when you have the meta knowledge of which ones are required to get to the quests that are actually useful.

**Comment by Rabadash94** [comment]
That there are survivors is only a possibility, it seems to me the least necessary for the idea to work. There could, instead, be missions related to finding some personal belonging (there is already a similar mission) of someone the refugees met briefly, as if to rid themselves of doubt about their fate.
They could be missions obtained through dialogue with an NPC, assuming that the player has already found at least one accident site (similar to what happens with the Exodii castle, which can be mentioned to the Old Guard NPC). There would also be no need for the vehicle to be right on the road, as the driver could have lost control and swerved until it crashed into trees or something.
Although I don't know if any of that is possible with the map extras.

If there is no way for a map extra to appear only around a certain location, it might be enough to have them appear on the same overmap, since it is not difficult to interpret where they were going.

**Comment by fairyarmadillo** [comment]
> For the same reason I don't think it's good to have survivors in those wrecks. It's demoralizing to have to see survivors getting slaughtered as you get there

While I agree with the rest of your sentiment and don't think this is a good solution, it's the apocalypse and there should be a lot of demoralizing things happening all the time. The Walking Dead and Romero movies are a nonstop parade of demoralizing things happening, it is thematically appropriate to the genre.
