### ISSUE TITLE
Dropped items are erased if they cannot fit into the tile

### ISSUE THREAD

**Issue by Meister134** [CleverRaven/Cataclysm-DDA#70583]
### Describe the bug

Items are erased if they cannot fit into the tile. Max amount of soil is 200, so if you try placing more than that at once, it gets erased but if you put less than 200, it works as expected. This bug also happens if you try to spawn items through debug.

### Attach save file

N/A

### Steps to reproduce

1. Get more volume than tile can contain at once
2. Drop it onto a tile
3. Watch it dissappear

### Expected behavior

It is supposed to just get pushed onto other tiles or go back into your inventory

### Screenshots

https://imgur.com/a/mA0sp0s

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: eaa25f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
]

**Comment by actually-a-cat** [comment]
Can confirm

Get 150 soil on a tile then drop another 150 on top of it - one stack of 150 correctly spills to adjacent tile
Wield both, creating combined stack of 300 soil and drop it - stack disappears

**Comment by Nukesor** [comment]
Not sure if related, but I encountered a bug where all books in a smartphone are erased if the light is turned on.

This has to be a recent bug, as I updated today and used the master from ~2 weeks ago since then.

```
 DEBUG    : error: item textbook_computer cannot fit into any pocket while loading: pocket with type (CONTAINER) not found

 FUNCTION : void item_contents::combine(const item_contents&, bool, bool, bool, bool)
 FILE     : src/item_contents.cpp
 LINE     : 738
 VERSION  : 0.G-6129-geaa25f56921
```

**Comment by ZhilkinSerg** [comment]
See #69898

**Comment by RenechCDDA** [comment]
This sounds like a regression, in the past(IIRC) it would overflow.

**Comment by Zireael07** [comment]
Yep, I'm like 99% it used to overflow
