### ISSUE TITLE
[Xedra Evolved] Dreamer spells are given to follower instead of player

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#70586]
### Describe the bug

When the player selects a spell to learn during a dream, the spells are given to followers instead of the player. Noticed after several dream prompts that I wasn't learning the spells that I selected. Swapped over to my follower and saw that they learned the spell despite not having the Dreamer trait.

### Attach save file

[Potomac-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13805434/Potomac-trimmed.tar.gz)

### Steps to reproduce

1. Have Dreamer trait and a follower
2. Sleep until asked to select a spell
3. Control follower and check list of spells

### Expected behavior

Controlled Dreamer should learn a spell if they are being prompted to do so during a dream, not the nearby follower that lacks any capacity to dream up magic.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 088e2b5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
@GuardianDll
