### ISSUE TITLE
Innawood progression is broken

### ISSUE THREAD

**Issue by littlejonn3490** [CleverRaven/Cataclysm-DDA#70593]
### Describe the bug

You cant make bronze tools without a sand casting mold, you cant make a sand casting mold without nails, you cant make nails without a sand casting mold

### Attach save file

[Innawood-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13806291/Innawood-trimmed.tar.gz)

### Steps to reproduce

Try to craft a bronze tool

### Expected behavior

I would expect to be able to craft bronze tools in innawood

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59403514/6380a3b6-6c3d-4937-b1ab-090fb8eb47b8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 8297d71 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Innawood [innawood],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks]
]

**Comment by Rokharn** [comment]
> you cant make nails without a sand casting mold

You do not need nails to make casting mold. You need superglue instead. To make some superglue you need better science skill, lvl 3. Nothing impossible at all.
