### ISSUE TITLE
Refugee Center Spawned far enough east and south to be on the edge of a megacity

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#70597]
### Describe the bug

Refugee center spawned far enough east and south that it was forced to spawn right on the edge of a megacity,  Literally impossible to reach in normal gameplay without using debug teleport and guaranteed to be overrun with hordes if the PC does reach it.

### Attach save file

[Test Xedra-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13807352/Test.Xedra-trimmed.tar.gz)

### Steps to reproduce

Generate a bunch of mapgen and use contact us option in evac center and eventually you will encounter something like this.  I was testing something else and found this.

### Expected behavior

Refugee Center to be reasonably located vis a vis starting overmap, Refugee Center to not border a mega city, Refugee center to not have zombies at the front entrance when I first arrive.

### Screenshots

![Screenshot 2024-01-01 232443](https://github.com/CleverRaven/Cataclysm-DDA/assets/54345792/e0a10d31-70d8-4aed-9099-e845e6440c4d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 0.G-6135-g0a0743a320 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by Icantthinkofanameforthis** [comment]
uhh i dont get what the issue is like if your saying you cant get through the city just go around it like you can climb the fences around the refugee center like the north and south look easy to approach from

**Comment by fairyarmadillo** [comment]
I also don't understand the problem here. There are many tiles of forced empty space between the center itself and its perimeter fence, and there's nothing about this area that would be particularly difficult to reach.

**Comment by PatrikLundell** [comment]
While it's true you can reach the refugee center on foot, the quests it doles out essentially requires you to drive there with cubic meters of stuff to deliver, so the refugee center in the image is crippled.

**Comment by fairyarmadillo** [comment]
That part makes sense. I suppose plotwise it's also supposed to be in the middle of nowhere.

**Comment by Procyonae** [comment]
There's barely anything stopping you taking a car through the north, north east corner or south, cars aren't on tracks you can go where you like with a tiny bit of patience, even taking large vehicles through a couple of tiles of forest isn't that much of a PITA if you use fire. Giving it a greater minimum distance from cities would make sense though I'll shove it into #70577. Does anyone know how lispcoc tested #68389 so I can get a good compromise between minimum city distance and average distance from spawn?

**Comment by PatrikLundell** [comment]
Fire doesn't work well currently. Sure, you can set fire to a forest and wait around while it burns (for the area within the reality bubble. All fire set outside the bubble is suspended until it enters the bubble again. If you don't watch the fire it will wait with its burning until you do.

Sure, you can smash your way through the (resource producing) vegetation belonging to the refugee center and tear down as much of the fence you need to get a vehicle through (or get rid of extra vegetation to get through a hole in the fence).
If it was my berry bushes I would not take kindly to someone barging in and smash them to build a dirt road, though.

**Comment by Procyonae** [comment]
> Sure, you can set fire to a forest and wait around while it burns (for the area within the reality bubble. 

You just read a little of a book in your car it's really not that big a deal

> Sure, you can smash your way through the (resource producing) vegetation belonging to the refugee center and tear down as much of the fence you need to get a vehicle through (or get rid of extra vegetation to get through a hole in the fence).
If it was my berry bushes I would not take kindly to someone barging in and smash them to build a dirt road, though.

I mean presumably they also like a safe way in and out so you'd be doing them a favour

**Comment by PatrikLundell** [comment]
Yes, you can read a book or two for a couple of days (with limited gains as your focus tanks), provided you don't overheat in the hot summer weather. It can be done, but it takes a number of days of baby sitting to burn a passage of a reasonable length through a forest.

I hope you don't try to apply that logic in real life, as your neighbors are going to be rather annoyed with your "helpful" pruning of their trees, removal of "obstructive" vegetation and "fire hazards" (real or not) etc.

**Comment by Procyonae** [comment]
> Yes, you can read a book or two for a couple of days (with limited gains as your focus tanks), provided you don't overheat in the hot summer weather. It can be done, but it takes a number of days of baby sitting to burn a passage of a reasonable length through a forest.

Unless this got changed in the last few months I'm pretty sure it takes nowhere near this long, you just park your car looking where you want to go, set all the trees in front up to the width of your car on fire, bash the bushes etc, spend an afternoon reading/repairing your car/crafting something etc and tada you have a treeless path. Also you're in your car why would you overheat just take off your armour.

**Comment by Maleclypse** [comment]
My mistake was in this 
```
"city_distance": [ 3, -1 ],
    "city_sizes": [ 4, -1 ],
    "occurrences": [ 75, 100 ],
    "priority": 1,
    "flags": [ "GLOBALLY_UNIQUE", "SAFE_AT_WORLDGEN", "MAN_MADE" ]
```  I thought we had extended city distance when we added `SAFE_AT_WORLDGEN`  a city distance of three means you can actually have a refugee center inside of a megacity and be considered safe at worldgen.   Also if you load up the save it's only 7 overmaps away and I thought it had spawned over 10 overmaps away from starting overmap.  It's on the edge of acceptable worldgen but not past it.
