### ISSUE TITLE
When I ram my friendly NPC with a tractor going very fast the game crashes. 

### ISSUE THREAD

**Issue by Dykem** [CleverRaven/Cataclysm-DDA#70595]
### Describe the bug

When I ram my friendly NPC with a tractor going very fast the game crashes. I keep trying to mow her down but the game crashes and reloads with her back alive. I took a low-probability gamble and asked her to follow me. She did. I'm playing sky island and want her stuff. >.> Totally normal... 

### Attach save file

[Sky Island Level up-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13806943/Sky.Island.Level.up-trimmed.tar.gz)

### Steps to reproduce

I back up the tractor a tile or two then crank that bad boy up to 95mph or so. As soon as I impact the NPC the game crashes.

### Expected behavior

I expected the NPC to either be thrown or run over. Either way the NPC should be dead, or crippled then dead within 10-20 seconds. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 6ae463e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

The game Log says "Your Planter Tractor's frame rams into Christina Byrd, farmer and stuns it!" and the game crashes at the same time.

**Comment by TealcOneill** [comment]
@GuardianDll fixed by #70687
