### ISSUE TITLE
Give trowels level 2 smoothing quality

### ISSUE THREAD

**Issue by littlejonn3490** [CleverRaven/Cataclysm-DDA#70592]
### Is your feature request related to a problem? Please describe.

I am in a situation where I need level 2 smoothing quality (whatever that means), cannot craft a metallic smoother but have a trowel, which should be functionally the same.

### Solution you would like.

Give trowels the same smoothing quality as a metallic smoother.

### Describe alternatives you have considered.

Remove level 2 smoothing quality as a requirement and combine the metallic and wooden smoothers into one item that just has smoothing quality but doesn't require an entire forging setup to craft. 

### Additional context

How do we even define what a level of smoothing is? A thin piece of wood or a small metal sheet, let alone a trowel, should be able to smooth down some mortar just as well as anything.

**Comment by ANickelN** [comment]
Noticed this earlier when I was evaluating early game construction options.  Not really sure that "smoothing" should have a quality level beyond one.  The difference between a thin piece of metal and a thin sheet of wood for spreading smoothing down mortar seems minimal at best.

**Comment by Icantthinkofanameforthis** [comment]
with the trowel smoother thing i looked up what the tools looked like

this first thing is a trowel with the purpose of light digging for garden work and with the curve would probably be pretty poor for nice level concrete/mortar smoothing work
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/7fe449ed-63f6-40e5-9f4e-f34532d3bfc8)


while this one is a cement trowel which is also referred to as a smoother and it would be garbage for garden digging work
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/169d8cd8-692e-43ff-9af4-791984173ea5)

**Comment by ANickelN** [comment]
Just not sure that the result of using one or the either would result in a change in structural integrity beyond how "smooth" any exterior facing mortar looks.  Seems like you could use a bread knife or a ruler to have "smoothing" quality just as well as the "smoother".

**Comment by littlejonn3490** [comment]
This is sold as a mortar trowel
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59403514/ce9428fc-7570-4566-8606-19aa0a7a9cb6)

And this is sold as a gardening trowel
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59403514/a0b6bb8f-d9f2-4145-87f4-7d661560ac39)

Who are we to say that the trowel in game is flatter or more curved? Assuming its curved like most trowels are, you could flatten it with a rock and it would be flatter for better(?) smoothing but still retain all of its functionality as a digging trowel. This flattening step is so trivial both mechanically and functionally that it isn't even worth adding as an intermediate process, the quality should just be built in.

**Comment by db48x** [comment]
A garden trowel is sharpened to cut through roots, and is usually curved to give it enough stiffness that it can actually penetrate the ground without bending or even crumpling.

A mortar trowel is quite different; it must be flat in order to lay the mortar along the edge of the brick. Go watch a video of someone laying brick to see what I mean.

A smoother with the handle on top would be used for smoothing poured concrete floors. It’s not uncommon to use one a yard wide with a long wooden handle to smooth large slabs of concrete.

I suggest adding a recipe for a mortar trowel that doesn’t involve blacksmithing. Bending and cutting a sheet of steel ought to be able to make something good enough.

**Comment by littlejonn3490** [comment]
Maybe keep it 2 levels of smoothing but make it so a trowel is level 1 and the large smoother is level 2. Level 2 would be for concrete walls and other constructions that are mostly concrete and level 1 would be for brickwork and mortar and the like. That would make the difference between them a little more intuitive, you don't need a massive rectangle to smooth grout across the width of 1 brick, a ruler, garden trowel or any similarly flat object should do that just fine, but when it comes to smoothing a massive concrete slab, you'd definitely want something a lot bigger. Regardless, I should be able to build a brick fireplace with a trowel.
