### ISSUE TITLE
Blaze Industries mod needs a maintainer and some adjustments.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#70608]
### Is your feature request related to a problem? Please describe.

It's been brought to my attention that:
1. Blaze Industries mod doesn't have any active maintainer - ie a person who keeps it up to date and up to code, and
2. it is not really up to code (even beyond the active maintainer criterion).

Specifically, it's currently sort of a non-themed collection of vehicle parts. Some argue that this is a "qol" mod because it makes various aspects of vehicle management easier, but that's not really what that category is for. If it were, pretty much anything could be called a qol mod.

See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/IN_REPO_MODS.md

Note that the 'cheatiness' or power level of the mod are *not* concerns. If a mod fits the content requirements, it can stay, even if it wildly shatters game balance.

### Solution you would like.

First, we need to obsolete the mod until these conditions are fixed.

If the mod has a maintainer, then the bar is lowered quite a lot, but anyone volunteering to maintain this mod should determine exactly what it is trying to do, and bring it under that umbrella. I don't personally think it needs much work to be called a content mod but it does need some sort of unifying vision; we're expressly trying to avoid mods that just "add some stuff that seems cool idk". The bar is low, but there is a bar.

Bear in mind that an obsoleted mod still exists in the code; this will not remove anything from existing saves. Blaze is getting obsoleted even with a maintainer, though; that's just gonna happen. It should be pretty easy to un-obsolete it once these issues are fixed.

**Comment by TheSaddestGoomba** [comment]
I don’t believe I currently have the personal bandwidth or the level of competence with the code to act as a maintainer. This is just some of my thoughts on future direction for the mod:

- Mod Purpose/Niche
  - Predominantly a content mod but also a space for vehicle feature development
  - Broad focus on vehicle-based play, additions and experimentals
  - Provide support for advanced death mobiles and fantastical vehicles
    - Remove (or loosen) the engine # restriction
    - Enable, if not encourage, mobile crawler bases
    - Spiritual reimplementation of old Blaze Mod parts
  - Testbed for experimental vehicle features
    - Submersibles, dirigibles, ultralights and gliders, burrowing vehicles
    - Raiders - driving NPCs
    - Vehicles as antagonists/multi-tile monsters
  - Future-ier setting than baseline, home for many ‘hi-tech’ devices and monsters
    - Nuclear, hi-tech, and fantastical
    - Nuclear powered cars and fixtures, atomic coffee maker, lamp, etc.
    - Home for some obsoleted robots and other mechanicals
- Mod Setting
  - Setting that is ‘a very few decades’ further in the future (30-50 years) before the Cataclysm struck. Would have had more advanced tech resulting from portal research than baseline, and significantly more widespread, commercialized products with their roots in portal research.
  - Post-cata setting leans towards a sort of hi-tech ‘Mad Max’ style apocalypse with mobility being key to ongoing survival.
    - This would likely take until after NPC drivers and wandering hordes are more developed to really manifest.
- Mod Features
  - Mod Faction
    - Blaze Industries as an in-universe entity. Private sector counterpart to XEDRA. Through a combination of market control, political leverage, and the CEO’s celebrity, the company was able to insert itself into the outer layer of Xedra affairs and become a broker for pioneering technologies.
    - Started as a company catering to extreme athletics and survival. Moved into motors and automotive as a jingoistic rebrand throwing back to the halcyon days of american steel; muscle cars with no seat belts and attendants ready to serve at everyone of our Blaze-On™ Checkpoints™. That later expanded into nuclear engines and other hi-tech products after the partnership with XEDRA.
    - Aesthetically, kinda going for a straight-faced but eye rolling EXTREME! Marketing! High-energy, corporate culture vibe. In your face and try hard-y, to go with the reckless and show offy tech.
    - They probably make their own energy drinks.
    - “When you need to Break Out and leave it all behind, you need to Blaze™.”
    - “Bigger is Good, Faster is Better, Farther is Best™.”
- Mod Locations
  - NPC Faction base, Blaze Industries Headquarters (Bee Zee ecH Que). Merchant and quest hub that can outfit the player with advanced vehicle parts and maintenance.
    - The CEO is still around but may actually be several clones or alternate selves.
    - Even after the collapse, they are continuing extra-dimensional research on the sly.
  - Blaze-On™ Checkpoints™ are superstations on major roadways. Similar to the very American trend of deluxe truck-stops, but taken much further with on-site motels, amenities, and service options for all kinds of vehicles, including electric and nuclear.
    - Robot guards and attendants shouldn’t feel out of place here.
- Vehicles, Vehicle Parts, Gear, and Adversaries
  - New mod vehicles out in the world
  - Classic sci-fi jetpacks and hovercraft
  - High-tech survival gear
  - Some updated reimplementation of older blaze mod stuff (blob, crystal, vortex)
    - Jacked grey goo assimilated and formed into working parts
    - Lithoid creatures with severable and regraftable parts
    - Bioengineered and birthed, Cronenbergian flesh-vehicles
    - Spectral, ’hard light’ constructs
  - Eyebots, police and riot control bots
  - Old Wraitheon gundroids and maybe even chicken walkers

**Comment by Maddremor** [comment]
@TheSaddestGoomba If you aren't going to do the work yourself, making a wish list is not going to contribute here.

**Comment by TheSaddestGoomba** [comment]
> @TheSaddestGoomba If you aren't going to do the work yourself, making a wish list is not going to contribute here.

I posted more than a "wish list." This is, as I said, "my thoughts on future direction for the mod". Much of this is addressing Erk's second point in the OP:
_I don't personally think it needs much work to be called a content mod but it does need some sort of **unifying vision**; we're expressly trying to avoid mods that just "add some stuff that seems cool idk"._
I put forward the idea of a faction to act as a center point for the mod's content, a style and tone that sets it apart from DDA, and some content (much of it already extant) that does not fit in mainline but could fit here.

I did not say I wouldn't do any work. I would love to do this work, but the part I cannot do is act as maintainer. No maintainer, no mod, nothing for me to contribute to.

**Comment by RenechCDDA** [comment]
@NetSysFire I don't think this is an issue we want to keep open forever. We've gone three months without anyone stepping up, I think it's fair to say nobody's interested. If we *do* find someone to take up the mantle, it's not going to be through keeping an issue open permanently.
