### ISSUE TITLE
Boil Water In Jars

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#7061]
If you can boil food with water in glass jars, it's reasonable you could clean water with them too. Its a three second copy-paste modification which I did in my jsons, but I cant figure out how to appropriately submit anything, and don't want to look like an idiot and fuck it up. All it did was add the Boiling code from tin cans to jars, but i think it will have the old bug where you can use it even if it's full of stuff already and I dont know how to fix that.

**Comment by Coolthulhu** [comment]
Works now
