### ISSUE TITLE
In the advanced inventory, issues moving items between carried containers and the rest of inventory.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70613]
### Describe the bug

If you are [C]arrying a container with an item, and you try to move it to the [I]nventory, it tells you the item is already in your inventory.
If you are trying to move items from your inventory to the carried container, it will move them, but still show in your inventory. You can "move" them repeatedly, taking up time, despite them not going anywhere.

### Attach save file

N/A

### Steps to reproduce

[C]arry a container with an item. Try to move it to the [I]nventory, It tells you the item is already in your inventory.
[C]arry a container, try to insert something from the rest of your inventory.

### Expected behavior

I'd expect that if you were moving an item out of a carried container, you could put it into general inventory and it would be handled like any other item that was picked up.
I'd expect that when one window is looking inside a carried container, the items within wouldn't show up in the [I]nventory tab so that you could actually transfer items into a new bag without memorizing which of them are already in that container.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/19c9679b-b1bd-497f-a385-7c2fbac57432)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/66fa8e9d-bf4d-45cd-af6a-283a0188418c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 04b6eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Kamayana** [comment]
What behavior would you expect if you try to move an item when its current container is already the best place for it? If it's already in a nice big backpack and all your other containers are mediocre, would you want it to stay in place with a popup telling you so, or would you want it moved to one of the worse containers? 

There's also the situation where it might move from a worse pocket of a container to a better one of that same container, which would mean it technically changes position but would still display the same inside the AIM, how should that be communicated to the player?

This wouldn't be too difficult to implement but I'd like to hear other peoples' thoughts on those two questions before taking a crack at it.

**Comment by MrHrulgin** [comment]
My assumption would be that if the player is trying to move an item out of a container, no one else's idea of optimal storage should stand in their way. I don't know how optimal storage location logic works precisely, but it should try to insert it into inventory excluding the container that it's departing from the list of options. If there's no other possible storage location, it should say that specifically.

The specific issues I've raised here aren't affected by separate pockets afaik, but if an item is moved between pockets with no visible changes to the AIM, a message in the log to the effect of "You reshuffle your inventory between the pockets of your [item]." would go a long way towards making clear what happened.

All of this can be avoided by dropping the container on the ground and then manipulating the inventory from there, but it feels silly to require inventory to be on the ground to be properly shuffled.
