### ISSUE TITLE
Can close door with set bear trap

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#70618]
### Describe the bug

Can close door with set bear trap, may be with another traps this bug occurred too (tribolas, shotguns, mines etc)

### Attach save file

N/A

### Steps to reproduce

1) Find openable door
2) Open door
3) Set bear trap at the doorway
4) Close door

### Expected behavior

I don't know, is it bug or feature, but is looks like you should not be able to close doors with traps

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/1227cb4f-86f4-4b0e-a0e9-432e83fb6ace)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/58c86113-8940-46a9-9a43-8d18738db561)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 641e7f0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
I feel like this is fine to exist as is, it's not like the door would take up enough space to prevent you placing a trap, I doubt it's intentional though. #64710 is vaguely related if someone fancied fixing both at once.
