### ISSUE TITLE
Supposed corruption deletes files 

### ISSUE THREAD

**Issue by SuspiciousSchrodinger** [CleverRaven/Cataclysm-DDA#70624]
### Describe the bug

every so often saves get corrupted, files containing the sections of the maps just go empty, ive saved the game by Save and exit and then quit to avoid breaking anything and it still doesnt work characters survive this problem companions do not 

### Attach save file

[Cochran.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13821977/Cochran.zip)

### Steps to reproduce

1 open the game
2 load the game
3 your map has reset lol 

### Expected behavior

saves not going poof because it ruins hours of grinding 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/118006327/f0bf8db8-26b0-4f4a-b93d-bb81c3f4988c)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/118006327/807cc3d5-a183-4dbe-b60a-5aee67c0de87)

### Versions and configuration

Version: Cataclysm-DDa experimentals build 2023-11-26-2202( has happened  through many different versions), windows 10, english lenguage, chibi ultica tileset, 

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 4f6df0a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Pixel's Various Fuckery [Pix's Shit],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    <color_cyan>Arcana</color>/DinoMod Patchmod [Arcana_Dinomod_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Blazemod - Vehicle Additions Pack [blazemod],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Arcana Addon [Graphical_Overmap_SDG_Arcana],
    Graphical Overmap Secronom [Graphical_Overmap_SDG_secronom],
    No Bionic Slots [no_cbm_slots],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

the problem is that pieces of the map get reset arbitrarily, as  shown in screen shots some parts of the map get regenerated without any  reason.

 DEBUG    : Failed to read from "C:/Users/kenic/Downloads/dda/userdata/save/Cochran/maps/0.9.1/5.301.1.map": Json error: C:/Users/kenic/Downloads/dda/userdata/save/Cochran/maps/0.9.1/5.301.1.map:EOF: input file is empty

 FUNCTION : read_from_file_json
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\cata_utility.cpp
 LINE     : 563
 VERSION  : 4f6df0a
 this is not the only error ar the vehicle not found error will also be present  at loading

**Comment by ZhilkinSerg** [comment]
That is environmental issue. I suggest you to make savegame backups more often.

**Comment by PatrikLundell** [comment]
I assume @ZhilkinSerg means it's an issue with the player's computer? The wording sound like it would be real world environmental issues like e.g. air pollution, or possibly the environment within the game...
