### ISSUE TITLE
Vehicle Colors

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#70630]
### Is your feature request related to a problem? Please describe.

I've noticed that most vehicles with the Ultica tileset are grey. Similarly, other tilesets display all vehicles as the same color, with an exception of military vehicles with armored plating. 

### Solution you would like.

I would like to see more colors of vehicles to add some variety. (I'm not sure if this is the space for explaining possible implementations or not, so I've listed my ideas in the additional context field instead.)

### Describe alternatives you have considered.

Alternatively, I could get used to seeing every vehicle with the same color of paint. 

### Additional context

Here are my implementation ideas:
1. Use C++ to "tint" the color of the current vehicle sprites. I have no experience with C++, but in pseudo-python-code, here's what I imagine. 
```
def sprite_tinter(sprite): 
    #Probably a nested loop over x and y
    for pixel in sprite: 
    #Where each pixel containing RGB channels and
    #tinting_factor is a list of tuples containing multipliers for the color channels
        red_tinted[pixel] = red[pixel] * tinting_factor[0][0]
        green_tinted[pixel] = green[pixel] * tinting_factor[0][1]
        blue_tinted[pixel] = blue[pixel] * tinting_factor[0][2]
    return sprite_tinted
```
I think a method like this could be more easily expanded to have additional color tints, by adding new tinting_factor tuples to the list. The downside of this method is that it requires C++ changes. 

2. Add color variants to the vehicle parts in a tileset directly, by manually creating some select color variants of each vehicle part. I'm not sure what an efficient workflow would be, but I imagine loading the vehicle parts into an image editing software, adding a color or overlay layer, and repeating this for several colors. The downside I see here is that it isn't as flexible for other contributors to add additional tints, and this would increase the size of the tileset. 

In both cases, there would also need to be something that defines and stores the color of the vehicle, so the sprite_tinter or tileset would pick the same tint for the whole vehicle, but could pick different tints for different vehicles, such as a red car, a blue car, a grey car, etc. 

As a side project, it would be cool if the player could paint vehicle parts individually, but I think that is outside the scope of this feature request.

**Comment by Procyonae** [comment]
Related issue #51841

**Comment by PatrikLundell** [comment]
It shouldn't use the variation system used for creatures, where they change appearance every time you encounter them, as the appearance is randomly selected each time (especially jarring with gender bending zombie brutes).

**Comment by DragonWizard23** [comment]
> It shouldn't use the variation system used for creatures, where they change appearance every time you encounter them, as the appearance is randomly selected each time (especially jarring with gender bending zombie brutes).

I agree. There should be some stored value that tracks the color of the vehicle, either part by part or for the whole vehicle, so the vehicle doesn't change color unexpectedly.
