### ISSUE TITLE
Error when using "u_spawn_npc" with "traits"

### ISSUE THREAD

**Issue by PipeYume** [CleverRaven/Cataclysm-DDA#70640]
### Describe the bug

-----------------------------------------
13:49:52.986 : Starting log.
13:49:52.986 INFO : Cataclysm DDA version d1ecdf4
13:49:52.987 INFO : [main] C locale set to C
13:49:52.987 INFO : [main] C++ locale set to C
13:49:52.987 INFO : SDL version used during compile is 2.26.2
13:49:52.987 INFO : SDL version used during linking and in runtime is 2.26.2
13:49:53.038 INFO : SDL render devices: direct3d, direct3d11, direct3d12, opengl, opengles2, software
13:49:53.041 INFO : [options] C locale set to C
13:49:53.041 INFO : [options] C++ locale set to C
13:49:53.041 INFO : Setting language to: 'zh_CN'
13:49:53.041 INFO : [i18n] Scanning core translations from lang/mo/
13:49:53.233 INFO : Active renderer: 1/direct3d11
13:49:53.415 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
13:49:53.428 INFO : Setting language to: 'zh_CN'
13:49:58.834 INFO : src/mod_tracker.h:68: Tried check if 'house_detatched5' had a duplicate, but type 'overmap_special' does not track object sources
13:50:03.922 INFO : Loaded tileset: MshockXottoplus
13:50:03.922 INFO : Loaded tileset: MshockXottoplus
13:50:24.713 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff73c263a48[cataclysm-tiles.exe+0x283a48]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x140283a48),
    0x140283a48    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/ios_base.h:1125    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff73c264971[cataclysm-tiles.exe+0x284971]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x211@0x140284971),
    0x140284971    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/allocated_ptr.h:246    time
    0x140284971    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/ios_base.h:1453    DebugLog(DebugLevel, DebugClass)
  #2
    (dbghelp: @0x7ff73c26592b[cataclysm-tiles.exe+0x28592b]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ac@0x14028592b),
    0x14028592b    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/ios_base.h:514    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  #3
    (dbghelp: @0x7ff73cfcd18b[cataclysm-tiles.exe+0xfed18b]), 
    (libbacktrace: void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*>(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*&&)+0x8b@0x140fed18b),
    0x140fed18b    src/string_formatter.h:795    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    0x140fed18b    src/json.h:78    void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*>(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*&&)
  #4
    (dbghelp: @0x7ff73c7ced68[cataclysm-tiles.exe+0x7eed68]), 
    (libbacktrace: string_id<mutation_branch>::obj() const+0x6a@0x1407eed68),
    0x1407eed68    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/unique_ptr.h:479    generic_factory<mutation_branch>::obj(string_id<mutation_branch> const&) const
    0x1407eed68    src/generic_factory.h:55    string_id<mutation_branch>::obj() const
  #5
    (dbghelp: @0x7ff73c7bef96[cataclysm-tiles.exe+0x7def96]), 
    (libbacktrace: Character::set_mutation_unsafe(string_id<mutation_branch> const&, mutation_variant const*)+0x36@0x1407def96),
    0x1407def96    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/hashtable.h:291    string_id<mutation_branch>::operator->() const
    0x1407def96    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/std_function.h:214    Character::set_mutation_unsafe(string_id<mutation_branch> const&, mutation_variant const*)
  #6
    (dbghelp: @0x7ff73c7bf12e[cataclysm-tiles.exe+0x7df12e]), 
    (libbacktrace: Character::set_mutation(string_id<mutation_branch> const&, mutation_variant const*)+0xe@0x1407df12e),
    0x1407df12e    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/std_function.h:245    Character::set_mutation(string_id<mutation_branch> const&, mutation_variant const*)
  #7
    (dbghelp: @0x7ff73c36e41f[cataclysm-tiles.exe+0x38e41f]), 
    (libbacktrace: game::spawn_npc(tripoint const&, string_id<npc_template> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<string_id<mutation_branch>, std::allocator<string_id<mutation_branch> > >&, std::optional<time_duration>)+0x179@0x14038e41f),
    0x14038e41f    src/cata_utility.h:5339    game::spawn_npc(tripoint const&, string_id<npc_template> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<string_id<mutation_branch>, std::allocator<string_id<mutation_branch> > >&, std::optional<time_duration>)
  #8
    (dbghelp: @0x7ff73c870ad7[cataclysm-tiles.exe+0x890ad7]), 
    (libbacktrace: talk_effect_fun_t::set_spawn_npc(JsonObject const&, std::basic_string_view<char, std::char_traits<char> >, bool)::{lambda(dialogue&)#1}::operator()(dialogue&) const+0x3c1@0x140890ad7),
    0x140890ad7    src/cata_utility.h:5747    operator()
  #9
    (dbghelp: @0x7ff73c86c14e[cataclysm-tiles.exe+0x88c14e]), 
    (libbacktrace: talk_effect_t::apply(dialogue&) const+0x20c@0x14088c14e),
    0x14088c14e    src/clzones.h:1108    __gnu_cxx::__normal_iterator<talk_effect_fun_t const*, std::vector<talk_effect_fun_t, std::allocator<talk_effect_fun_t> > >::operator++()
    0x14088c14e    src/cata_utility.h:5927    talk_effect_t::apply(dialogue&) const
  #10
    (dbghelp: @0x7ff73c2e347e[cataclysm-tiles.exe+0x30347e]), 
    (libbacktrace: effect_on_condition::activate(dialogue&) const+0x27c@0x14030347e),
    0x14030347e    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/char_traits.h:308    effect_on_condition::activate(dialogue&) const
  #11
    (dbghelp: @0x7ff73c28cb57[cataclysm-tiles.exe+0x2acb57]), 
    (libbacktrace: debug_menu::debug()+0x2c79@0x1402acb57),
    0x1402acb57    src/cata_utility.h:3398    debug_menu::debug()
  #12
    (dbghelp: @0x7ff73c3d05d8[cataclysm-tiles.exe+0x3f05d8]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, std::optional<tripoint> const&)+0x2b52@0x1403f05d8),
    0x1403f05d8    src/cata_utility.h:2759    game::do_regular_action(action_id&, avatar&, std::optional<tripoint> const&)
  #13
    (dbghelp: @0x7ff73c3d224f[cataclysm-tiles.exe+0x3f224f]), 
    (libbacktrace: game::handle_action()+0xba7@0x1403f224f),
    0x1403f224f    src/cata_utility.h:3124    game::handle_action()
  #14
    (dbghelp: @0x7ff73c2bc77d[cataclysm-tiles.exe+0x2dc77d]), 
    (libbacktrace: do_turn()+0x645@0x1402dc77d),
    0x1402dc77d    src/gamemode.h:534    do_turn()
  #15
    (dbghelp: @0x7ff73d754207[cataclysm-tiles.exe+0x1774207]), 
    (libbacktrace: main+0x2484@0x141774207),
    0x141774207    src/main.cpp:798    main
  #16
    (dbghelp: @0x7ff73bfe13ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: _tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #17
    (dbghelp: @0x7ff73bfe14c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #18
    (dbghelp: BaseThreadInitThunk+0x1d@0x7ffb7ad1257d[KERNEL32.DLL+0x1257d]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #19
    (dbghelp: RtlUserThreadStart+0x28@0x7ffb7b68aa58[ntdll.dll+0x5aa58]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:31.819 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 57 times ]
13:50:31.836 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:31.966 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:31.969 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:32.100 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:32.105 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:32.236 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:32.241 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:32.373 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:32.380 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:32.513 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 74 times ]
13:50:32.778 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:32.908 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:32.912 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.042 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.046 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.174 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.177 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.307 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.310 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.439 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.442 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.575 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.578 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.709 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.712 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.845 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.851 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:33.981 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:33.985 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.117 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.121 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.250 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.254 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.383 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.386 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.516 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.519 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.650 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.653 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.785 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.788 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:34.918 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:34.922 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.053 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.057 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.189 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.195 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.325 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.329 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.460 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.463 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.593 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.598 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.729 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.737 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:35.868 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:35.873 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.003 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.009 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.138 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.142 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.272 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.275 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.404 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.407 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.539 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.545 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.676 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.680 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.811 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.817 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:36.946 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:36.950 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:37.080 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:37.083 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:37.215 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:37.219 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:37.349 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:37.352 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:37.482 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:37.485 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:37.616 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
[ Previous repeated 3 times ]
13:50:37.620 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""
13:50:37.748 ERROR : src/generic_factory.h:478 [const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]] invalid trait id ""

### Attach save file

None

### Steps to reproduce

```
    {
        "id": "EOC_spawn_npc_test_2",
        "type": "effect_on_condition",
        "effect": [
            {
                "u_spawn_npc": "portal_person",
                "real_count": 1,
                "min_radius": 1,
                "max_radius": 1,
                "traits": [ "GOODMEMORY" ]
            }
        ]
    }
```

### Expected behavior

-

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/81861009/776094d0-f5fd-440c-9abd-235680844322)

### Versions and configuration

cdda-windows-tiles-x64-2023-12-28-1538

**Comment by Procyonae** [comment]
Just for future reference you can upload the log file directly rather than the text
