### ISSUE TITLE
[MoM] Wielded matrix crystals don't seem to do anything

### ISSUE THREAD

**Issue by Awoomy** [CleverRaven/Cataclysm-DDA#70652]
### Describe the bug

In the world I'm currently playing, I have matrix crystals for biokinesis, clairsentience, and teleportation. However, when I wield any of the crystals, none of the levels for any of the powers are adjusted as shown in #66641. To test if this was a mod compatibility problem or a problem with starting with MoM backgrounds rather than using the crystals for awakening, I made a new world with MoM as the only non-default mod, created a default survivor, spawned in 2 pyrokinesis crystals, awakened with one, and wielded the other. None of the spell levels were adjusted and none of the numbers in the description changed, with or without wielding the crystal.

### Attach save file

[Lunds-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13834373/Lunds-trimmed.tar.gz)

### Steps to reproduce

1. Make a survivor
2. Spawn in 2 non-black matrix crystals of the same color
3. [a]pply one
4. [w]ield the other
5. Check the spellcasting menu

### Expected behavior

Wielding a matrix crystal should give a +4 level adjustment to powers of the corresponding class.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155670287/a961fa13-f705-48b2-810c-4181d0c07b86)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155670287/88cab0ea-f7f5-4a4a-b0a7-bcb613329290)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: eaa25f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by Standing-Storm** [comment]
Maybe a side effect of #69473?

**Comment by Awoomy** [comment]
> Maybe a side effect of #69473? #70255 converted everything over to the new format specified by #69473.

The latest experimental I have before that PR is from 12/2/2023. Crystals seem to be working as expected here.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155670287/8daad935-30ce-4ddb-8c71-5dc9f42f1c34)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155670287/7aa68610-df9e-480a-be85-f27846492e4d)

Though, the damage numbers on Fountain of Flames are the same with or without the crystal. I know Fountain of Flames was rebalanced recently, but looking through this version's MoM files, it doesn't seem to be accounting for the level adjustment here.

```
"min_damage": {
      "math": [ "( (u_val('spell_level', 'spell: pyrokinetic_eruption') * 2) + 6) * (scaling_factor(u_val('intelligence') ) )" ]
    },
   
 "max_damage": {
      "math": [ "( (u_val('spell_level', 'spell: pyrokinetic_eruption') * 3) + 26) * (scaling_factor(u_val('intelligence') ) )" ]
    },
```

Another screenshot to show that it's actually hitting for the level 2 Fountain of Flames damage range with the crystal:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/155670287/3baaf9e9-ab73-4f71-b96c-99f7239831fc)

**Comment by Awoomy** [comment]
After looking through MoM's files a bit more, I tried adding the Power Surge effect from Nether Attunement. It still didn't apply any level adjustment or change in the numbers in the description. I think it's likely that the problem is with the 
```
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'BIOKINETIC')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'CLAIRSENTIENT')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'ELECTROKINETIC')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'PHOTOKINETIC')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'PYROKINETIC')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'TELEKINETIC')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'TELEPATH')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'TELEPORTER')", "=", "3" ] },
      { "math": [ "u_spellcasting_adjustment('caster_level', 'school': 'VITAKINETIC')", "=", "3" ] }
``` 
lines shared by the matrix EoCs and the nether attunement boost EoC.
