### ISSUE TITLE
Chainsaw arm

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#70653]
### Is your feature request related to a problem? Please describe.

Now that we have prostethics and whatnot, how about a FUCKING CHAINSAW ARM FUCK YEAH. Groovy!

### Solution you would like.

There are two options:
- A crudely handcrafted one that is just a chainsaw attached at the end of a steel protrusion. This might be inefficient, low to-hit, and maybe even comes with a special effect of cutting yourself. Rule of cool still applies tho plus it actually comes with B-Plan and a permanent tool to cut wood.
- A bionic, that is mobile according to Player's wishes, and thus much less self-destructive, more efficient and deadly. Unlike shotgun arm it would permanently replace one of your arms.

### Describe alternatives you have considered.

idk don't do this I know I'll do it in my game regardless lol

**Comment by MNG-cataclysm** [comment]
How would the amputee control the movement of the chainsaw arm and avoid cutting themselves? Could it rely on neuroprosthetic control methods, or be a bionic of some sort like the shotgun arm?

**Comment by KeremBabaG** [comment]
> How would the amputee control the movement of the chainsaw arm and avoid cutting themselves? Could it rely on neuroprosthetic control methods, or be a bionic of some sort like the shotgun arm?

To adress the first question, its to-hit can be made low. Maybe even add an effect of a chance of cutting self. Of course the latter would be communicated to the player, like "you're definitely going to cut yourself wit this."

And yeah, a bionic could work too. Maybe two seperate ones; a bionic that is properly mobile and less dangerous and another handcrafted one which is a world champion in safety hazard.

**Comment by carlarctg** [comment]
this could probably work as a CC-only thing. maybe asking an npc while having a chainsaw in inventory?
