### ISSUE TITLE
my e-ink tablet got bugged, and a bunch of the scanned books spawned out from nowhere

### ISSUE THREAD

**Issue by yamil-90** [CleverRaven/Cataclysm-DDA#70655]
### Describe the bug

i scanned a bunch of books and when i tried to read them an error appeared, i dont remember the exact message but it was something along the lines of trying to put a book inside somewhere. and after that all the scanned books spawned inside my inventory. I also noticed that my tablet was now empty of books recipes etc. 
i scanned them again but i omitted the book that caused the error in the first place (one about dragons from magiclysm) but when i tried to read a book in the tablet the same error appeared and all the books spawned again.
i also scanned just a couple of books and then y tried turning it off and got the error so it seems like my tablet is probably ruined 

### Attach save file

[Downing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13834735/Downing-trimmed.tar.gz)

### Steps to reproduce

1-load the savefile
2-scan all the books
3-try to read some book in the tablet (sometimes i also get the error from turning off the tablet)

### Expected behavior

not loose all my scanned books and get a bunch of books to spawn in my location

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.3 LTS; Release: 22.04; Codename: jammy; 
- Game Version: b4f834c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm]
]

### Additional context

i found the error message:

 DEBUG    : error: item mag_dude cannot fit into any pocket while loading: pocket with type (CONTAINER) not found

 FUNCTION : void item_contents::combine(const item_contents&, bool, bool, bool, bool)
 FILE     : src/item_contents.cpp
 LINE     : 738
 VERSION  : b4f834c

**Comment by Procyonae** [comment]
Related/dupe issue to #70493
