### ISSUE TITLE
Crash after reaching failed/removd Sky Island Kill mission 

### ISSUE THREAD

**Issue by luk-k** [CleverRaven/Cataclysm-DDA#70650]
### Describe the bug

Build: 2024-01-03-1629
Game crashed after coming near location of not completed mission form previous expedition. Issue was encounter 2 location on that save. Game version was updated to newest experimental 2 times since start of this save. It was observed that mission tied to location do not appear in failed tab after leaving expedition in contrast to kill X creatures ones.

Mods used:
  "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "package_bionic_professions",
  "alt_map_key",
  "MMA",
  "cbm_slots",
  "speedydex",
  "stats_through_kills",
  "skyisland",
  "blazeindustries",
  "magiclysm",
  "xedra_evolved"

### Attach save file

[Sky Island 2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13834106/Sky.Island.2-trimmed.tar.gz)

### Steps to reproduce

1. Start new game with Sky Island
2. Start new expedition
3. Return to sky island using exit point
4. Start new expedition
5. Go to location Kill X type of enemy group from first expedition

### Expected behavior

Game does not crash after reaching location of removed mission.

### Screenshots

![Screenshot 2024-01-04 185050](https://github.com/CleverRaven/Cataclysm-DDA/assets/26330094/9a3f9669-c0a9-429a-88b4-7b90693eb122)
![error](https://github.com/CleverRaven/Cataclysm-DDA/assets/26330094/c6720ee3-02b7-4827-8553-b43ef58336c8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 622d57d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Sky Island [skyisland],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13834093/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13834094/debug.log)

**Comment by physics-enthusiast** [comment]
/confirm I get these occasionally. Is /confirm usable for contributors without commit permissions?

**Comment by hexagonrecursion** [comment]
@physics-enthusiast what is a difference between a segmentation fault and a "straight crash to desktop"? I was under the impression that the game _always_ crashes to desktop when it encounters a segfault.

**Comment by physics-enthusiast** [comment]
Mine tend to freeze up after the SIGSEGV error and force me to manually kill the process. Occassionally it just crashes. Maybe just an OS graphics thing?

**Comment by relinkz** [comment]
Looked into this for a bit, this is what i learned.

mission::find() is called with an ind that does not exist.
the caller of the find() function is spawn_monsters_submap()
```

void map::spawn_monsters_submap( const tripoint &gp, bool ignore_sight, bool spawn_nonlocal )
{
...
        const spawn_point i = current_submap->spawns[sp_i]; // in
            if( i.mission_id > 0 ) {
                tmp.mission_ids = { i.mission_id };
                mission *found_mission = mission::find( i.mission_id );
...
}
```

I am just putting this info here if it helps someone

**Comment by physics-enthusiast** [comment]
Nice, I was wondering where the call was coming from. Since the debug message is printed before the SIGSEGV, we know that at least mission::find manages to return. The problem seems to be that found_mission is not checked to be null, possibly leading to a nullptr dereference somewhere down the line. Maybe the fact that Sky Island marks missions as complete while they are outside the reality bubble has something to do with it? I'll open a PR soon to try a fix but it might be a while before I can test it.
