### ISSUE TITLE
Make inventory EoC pass context variables

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#70658]
### Is your feature request related to a problem? Please describe.

it is difficult to do a lot if item, found by u_run_inv_eocs is not passed to variable

### Solution you would like.

run_inv_eocs stores value they found in some variable

**Comment by Ramza13** [comment]
I'm not quite familiar enough with the context of this to do it.  Can you give me a json example of what you'd like be able to do?  Thanks

**Comment by GuardianDll** [comment]
It was fool of me to not write the EoC that didn't work at that time
I think the issue was something like
```json
  {
    "type": "effect_on_condition",
    "id": "EOC_TEST_1",
    "effect": [
      { "math": [ "_aaaa", "=", "8888" ] },
      {
        "u_run_inv_eocs": "all",
        "search_data": [ { "wielded_only": true } ],
        "true_eocs": [ { "id": "EOC_TEST_2", "effect": [ { "u_message": "You hold <npc_name>, my context val is <context_val:_aaaa>" } ] } ]
      }
    ]
  },
  ```
But since i just tested it, and it works as expected
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/d188365b-4f91-475e-b9d9-07556667e0e0)
I shall close it
