### ISSUE TITLE
Sanity and mental health

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#70662]
### Is your feature request related to a problem? Please describe.

CDDA currently have many things from COC. However, the essential concept, sanity, is missing in CDDA.

### Solution you would like.

Add mental health system, which is in some extent similar to the currently exsisting physical health system, and should have some synergies in between.
There should be various dimentions in mental health system, and each correspond to a type of mental illness. Currently, by my knowledge, there should at least four:
1. Depressive disorder.
2. Anxiety disorder.
3. Phobia
4. Schizophrenia

Due to the brutal nature in which the player character live in, they should be significantly impacted in term of these aspects, even without COC monsters.
For example:
-Seeing smashed human bodies should make some horror and potentially develop phobia, or make the character more resistant to such scenario if it didn't exceed the threshold. 
-Being unhappy for long time may cause depression or anxiety.
-Mythological impact such as effect of COC monsters or cost of a spell may cause schizophrenia (which include hallucination and delusion)

### Describe alternatives you have considered.

None

### Additional context

Maybe another skill, psychology should be added. It can handle mental health, just like the current health care skill handling physical health.

**Comment by GuardianDll** [comment]
Psychical problems are impossible to recreate in the game fully, in any game, it's just not a thing

**Comment by martinrhan** [comment]
> Psychical problems are impossible to recreate in the game fully, in any game, it's just not a thing
At can be recreated partially. And this partial recreation should be meaningful.

**Comment by fairyarmadillo** [comment]
> Depressive disorder.

We have seasonal depression and bad mood, both of which can be treated with antidepressants.

> Anxiety disorder.

We have jittery, which can be treated with sedatives.

> Phobia

We have nyctophobia.

> Schizophrenia

We have kaluptic psychosis, which can be treated with antipsychotics.

**Comment by markianotto** [comment]
> Psychical problems are impossible to recreate in the game fully, in any game, it's just not a thing

I disagree [Infra Arcana](https://www.roguebasin.com/index.php/Infra_Arcana) has a delightful sanity mechanism built in. While somewhat simpler than what is proposed here (there is only one stat called "sanity"), the three proposed points do align to how IA plays. I can highly recommend the game. Possibly we can gain some inspiration from it.

While the game mechanic suits IA, I'm not sure if it would fit to the mission of CDDA, because its not very realistic, at least the way IA implements it. With that said, I think sanity would be a great additional problem to have in CDDA land.

**Comment by Uwuewsky** [comment]
> Psychical problems are impossible to recreate in the game fully, in any game, it's just not a thing

> Seeing smashed human bodies should make some horror and potentially develop phobia, or make the character more resistant to such scenario if it didn't exceed the threshold.

[Dwarf Fortress has a stress system for this.](https://dwarffortresswiki.org/index.php/Stress)

The dwarf receives a morale debuff upon Seeing somebody die, Suffering a injury, Being in conflict, etc. [Unless the dwarf is battle-hardened and accustomed to seeing death.](https://dwarffortresswiki.org/index.php/Combat_hardening) Right now the game character doesn't seem to care at all about any of this.

[A stressful event can become a long-term memory phobia and give debuffs for a long time.](https://dwarffortresswiki.org/index.php/Memory_(thought))

[And a lot of stress leads to game overs](https://dwarffortresswiki.org/index.php/Insanity)

**Comment by kevingranade** [comment]
Not interested, mood/morale is one thing,  but developing and treating specific mental disorders is not something I'm interested in adding to the game.  Specifically I don't see a good way to implement most of the things mentioned in a way that's not offensive to people who have these disorders and doesn't contribute to misinformation about them.
