### ISSUE TITLE
Mental Health System - Game Mechanism Design

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#70667]
### Is your feature request related to a problem? Please describe.

Previously, I posted another issue about [sanity and mental health](https://github.com/CleverRaven/Cataclysm-DDA/issues/70662). That's too much theories gives no idea to people who do the programing. This post describe what the game machanism looks like.

### Solution you would like.

Psychology is complecated. Since our purpose is to put it into the game, we should just find an outline that fit to the game's design, and easy to implement programatically. 
With game design orientation in mind, I believe the mental heath system should have 3 major aspects. 

Happiness 
Short term happiness is just the current morale system. But the term morale should be changed, because morale is something not very specific and stand between happiness and bravery.
Additionally, we should add a long term happiness variable. The rationale is, if the someone has been unhappy for a long time, that person is probably going to get despressed. To simulate this, a simple implementation is just sum up short term happiness as time ticks, and there's a maximun and minimum.
This model also works well for another scenario, a significant unhappy event that greatly impact happiness nagatively and create a trauma, there is a very nagatively large number that last for days are rapidly downgrade long term happiness within a short time.
Then, long term happiness act as an additional modifier of short term happiness. This simulates: 1, the negative feedback loop when someone is developing depressive disorder. 2, Someone with good long term happy life don't get too sad even a impactful negative even happens to them. 3, Someone with depressive disorder is unlikely to get happy even something fun is around.

Stress
The word it self also have meaning of worry, but that should be part of unhappiness in our game machanism design. Here it means fear, dread, panic.
Stress should be similar to the one in Darkest Dungeons. If someone is exposed to horrible environment or see somthing horrible, they got their stress increased. 
Charaters should have their capability panalized when they are stressed, and get mad when stress exceed a threshold.
Taking stress without exceeding the threshold should make the character's mind stronger and more resistent to stress. Otherwise it create a trauma or phobia that make the character more mentaly vulnerable.

Sanity
This is the ability to recognize reality. Low sanity means the person has strong hallucination, delusion, or COC speaking, probably see something beyond reality and human's capability of understanding.
In real world insanity is an outcome of schezophrenia, which is mostly caused by biological and nueral abnorality, and not necessarily related to stress and happiness. In the game, insanity is caused by mythological things, and should have a strong relation to stress and happiness. When someone is highly stressed, they should loss some sanity. If someone has high happiness and acknowledge values of life as a humanbeing, they should have a strong sanity.
Other factors that influence santiy include but not limited to: Knowledge and skill which make the character more rational and confident, mythological spell that cost sanity, etc.

Furthermore, psychology should be added as a new skill. It handle mental health just like health care skill handle phisical health. I charater with high psychology should have some ability to heal trauma or phobia, or make someone less depressive. In reality instanity or schizophrenia cannot be healed by pure psychological appoach as there are some biological and nueral thing to do. In the game sanity cannot be increased by psychology directly and limitedly by resolving stress and depression, or directly by mythological approach.

### Describe alternatives you have considered.

None

### Additional context

None

**Comment by PatrikLundell** [comment]
It's apparent there's a faction who wants to abandon the zombie apocalypse for the Inevitable Descent Into Madness path with Cuthulhu stuff, portal insanity magic, etc. Some of those simultaneously claim that it's important to make things realistic.

I'm completely opposed to the portal and other magic stuff, but have to respect the dimension magic as a corner stone for the current vision.

**Comment by Procyonae** [comment]
Why did you open a second issue for this 6 hours after posting the first when you could've just added it in the description or comments of the first?

**Comment by Zireael07** [comment]
That's probably because the first is strongly rooted in current, realistic DDA, while this takes it in a more gamified direction

**Comment by kevingranade** [comment]
Not interested, mood/morale is one thing, but developing and treating specific mental disorders is not something I'm interested in adding to the game. Specifically I don't see a good way to implement most of the things mentioned in a way that's not offensive to people who have these disorders and doesn't contribute to misinformation about them.
