### ISSUE TITLE
Slight Issues With Denim Recipes

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#70670]
### Is your feature request related to a problem? Please describe.

The Recipes added in #70534 have a few discrepancies, mainly the denim shirt, and the hardened armored jean jacket and vest, which erroneously use cotton sheets and a _Leather_ Jacket in their recipes respectively

### Solution you would like.

Fix the above recipes

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/800be2ea-c2f0-4540-a2ca-723f1a02f1b0)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/f6bc8918-ccb4-4695-b8db-eabde3366097)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/be0e42b2-0093-42e7-a849-9fef8a2610d3)

**Comment by KeremBabaG** [comment]
Oh shit sorry about that, messed something up when copypasting recipes. Fixing right away
