### ISSUE TITLE
SHOW_HIDE_CONTENTS_ALL is not obvious

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#70672]
### Is your feature request related to a problem? Please describe.

There is way too many people, that accidentally use `Show/hide all contents` button in the inventory, and then don't understand how to fix it
So many, it made me to write this suggestion

### Solution you would like.

🤷 
Move it to another button? Add big red message "you hide all your content, press shift+e to turn it back"? unbind it by default?

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/37a9ea16-d5a8-4144-b15b-abdbebf77aa0)

@andrei8l suggestions?

**Comment by andrei8l** [comment]
Add the hint from #64664 to the common inventory_selector too.

Or revert saving the state (#68564)

Or just remove the feature. I added it because people asked for it (#62854) but it seems to be causing too much trouble.
