### ISSUE TITLE
Items in destroyed vehicle cargo are not accessible

### ISSUE THREAD

**Issue by showervic** [CleverRaven/Cataclysm-DDA#70681]
### Describe the bug

Items in destroyed vehicle cargo are not accessible

### Steps to reproduce

1. Find a vehicle with a destroyed part and some items in it. 
2. Explore the vehicle and see the part contains items. Its cargo capacity will look like  3.75L/0.0L
3. Try to get the items via advanced inventory management. Nothing is seen inside.
4. Remove destroyed vehicle part and get the items

### Expected behavior

Items should be on the ground OR cargo capacity should not be 0.0L for destroyed parts. 

### Versions and configuration

game version #622d57d

**Comment by fairyarmadillo** [comment]
The item is on the ground, underneath the broken vehicle tile. You can press g or w to get it, or in your advanced inventory manager, have the second panel target the same tile as the broken vehicle part. You'll see it's there.

**Comment by fairyarmadillo** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/75c4ac7d-87e1-4905-8c19-d66a348ebb11)

Unable to reproduce in a53d7e7. This flashlight was in the seat. I broke the seat, and it moved to the ground below the seat.

What vehicle part specifically did you observe this in? Does updating change the behavior?

**Comment by showervic** [comment]
Never destroyed parts. Observed for cars spawned with already broken parts. Trunks, seats.

**Comment by fairyarmadillo** [comment]
I don't think my cargo space changes could have caused that, it must be an older issue. There's a check in I think vehicle.cpp that shunts items out to the floor when a part breaks, sounds like we just need to add that in when cargo parts are spawned.

**Comment by showervic** [comment]
Started new game and double checked. Before, player could see and get items from broken trunks.

![destroyed trunk items](https://github.com/CleverRaven/Cataclysm-DDA/assets/125735863/a1f5f0fa-a9ba-4d39-8d6e-511e097c595b)

![destroyed trunk items not accessible](https://github.com/CleverRaven/Cataclysm-DDA/assets/125735863/1e38108b-dc73-44c6-b1d9-e8886e9b72eb)

**Comment by showervic** [comment]
Maybe its fine to have items not accessible now. Its not easy to get something out of smashed trunk.
