### ISSUE TITLE
Nailboard traps and caltrops should have a chance to be removed, like bear traps

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#7069]
Currently (0.A Stable) all other traps get used up when triggered, but nailboards and caltrops will stay active indefinitely. Lay them thick enough and you can easily kite an entire town of zombies to death.

I suggest giving them a chance of getting stuck to their victims, much like a bear trap. They would still be available for reuse, but a trap field would need to be maintained.

Spiked pits act somewhat like what I would like for the spikeboards and caltrops, in that they always deal damage, but don't always "break". Speaking of which, I would like to see a chance of pits being reduced to shallow pits when something falls in/climbs out.
##

**Comment by Night-Pryanik** [comment]
Already possible. Should be closed?
