### ISSUE TITLE
Test to catch items above 1000L in volume

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#70707]
### Is your feature request related to a problem? Please describe.

#70706 and #70704 should provide all the information you need. Items above 1000L cannot be dropped onto the ground, ergo they should not exist outside some extremely niche and specific circumstances (which I can't think of any, frankly)

### Solution you would like.

Have the automated GitHub tests catch items above 1000L in volume and prohibit PRs with them from passing the Basic Build so they don't get merged by accident

### Additional context

Uh. Apparently we can have crafting pseudoitems above 1000L in the world. I was told there's an issue about it somewhere. So if anyone takes it upon themselves to write these tests, please take a look at that so that you don't block all tests on all PRs by accident.

**Comment by GuardianDll** [comment]
about crafting pseudoitems there is #62258, #52946 and #36968

**Comment by RenechCDDA** [comment]
This can probably be caught when loading the items in generic factory, no need for a full test.

**Comment by RenechCDDA** [comment]
Whoops, actually meant item factory.

Here's a crude example implementation in item factory:

```diff --git a/src/item_factory.cpp b/src/item_factory.cpp
index 962a101125..988c307f20 100644
--- a/src/item_factory.cpp
+++ b/src/item_factory.cpp
@@ -2102,6 +2102,9 @@ void Item_factory::check_definitions() const
         if( type->volume < 0_ml ) {
             msg += "negative volume\n";
         }
+        if( type->volume > 1000_liter ) {
+            msg += "exceeds max volume\n";
+        }
         if( type->stack_size <= 0 ) {
             if( type->count_by_charges() ) {
                 msg += string_format( "invalid stack_size %d on type using charges\n", type->stack_size );

```

The 1000L limit actually lives in mapdata.h, as `max_volume`. So if this were implemented it probably needs to be promoted to a game constant, mapdata.h needs to refer to the game constant, and the item factory also refer to the game constant.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/b516cbea-ab04-4814-9fc6-bcff056bf607)
