### ISSUE TITLE
When NPC fails to recover a material during vehicle disassembly, it misattributes the failure.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70727]
### Describe the bug

When NPC fails to recover a material during vehicle disassembly, it misattributes the failure.

### Attach save file

N/A

### Steps to reproduce

Put a damaged vehicle in a disassembly zone and have an NPC disassemble it. When they fail to recover an item, see the message attribute the failure to you.

### Expected behavior

I'd expect it to say who failed to disassemble.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/95c0b346-a6f1-4403-86a6-3e80c8932b10)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 04b6eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by RenechCDDA** [comment]
Easy to fix, just needs to supply a different message if the character doing the activity isn't the avatar.

https://github.com/CleverRaven/Cataclysm-DDA/blob/c50e0e2061203c9380d442210da67bdee432980d/src/veh_interact.cpp#L3334-L3344

**Comment by relinkz** [comment]
I will take a look at this. Will take some time to set everything up, just a headsup

**Comment by relinkz** [comment]
I have managed to build the project.

Now I am finding out how to use Debug mode to reproduce the error.

**Comment by relinkz** [comment]
I have put a car in the destruction zone, given an npc a hacksaw and screwdriver, and let the npc deconstruct the car. I have not managed to get the message "you fail to recover..."

My theory is that I need to have welders to do this, I do not know how these work in game, so I am right now learning how to use them.

**Comment by relinkz** [comment]
Sucess:
I managed to reproduce the error, these are the steps I took:
Setup: Spawn all the necessary tools
1. Create a character, with "friends till the end" senario
2. Enable Debug, (use debug hotkey, you need to assign it)
3. Spawn a damage vehicle (Debug menu)
4. Open Zone-manager
5. Add a Vehicle Destruct Zone, On the damaged vehicle
6. Spawn a wrench
7. Spawn a power drill
8. spawn welding googles
9. spawn a backup generator
10. spawn a very large grid battery.

Install and setup the tools for use
1. Place "backup generator", beside the designated zone (construction menu)
2. Place "Large grid battery" (Construction menu)
3. Attach "battery to generator. (activate the backup generator)
4. Attach "arc welder" to the generator
5. Drop "arc welder" beside the generator
6. Attach "power drill" to the generator
7. Drop the "power drill" beside the generator
8. Make Liam wear "welding googles", talk->i want you do to something->use this item->select "welding googles"

Finally:
talk to Liam->i want you to do something->Work at disassemble vehicles.

Wait for some time, and there is a chance that liam will fail.
Observe: "You fail to recover x nuts and bolts"

**Comment by relinkz** [comment]
I have made some changes, but the changes does not solve the error.
I fail to push the changes I made, so next, I will spend some time setting up git correctly.

**Comment by relinkz** [comment]
I found some instructions that I should fork the project and do the changes there, but the issue still persist
'''
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication."
'''
My hypothesis is that my git account need some lovin', will look into this tomorrow
https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-setup-git-locally

**Comment by relinkz** [comment]
I have now set up sso correctly, and have opened a draft PR whith the changes i believe should fix the issue, my next cause of action is to locally build and observe of this change solves the issue

**Comment by relinkz** [comment]
A PR has been merged addressing this issue.

**Comment by RenechCDDA** [comment]
Looks to be resolved by #71036

Thanks for the contribution.
