### ISSUE TITLE
Vehicle part scrapping?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70724]
### Is your feature request related to a problem? Please describe.

At the moment, once I've broken down a car, I'm left with hundreds of pounds of metal I can't use in the form of an engine block and wheel hub assemblies that serves no purpose at all.

### Solution you would like.

Engine blocks and other parts should be disassemblable into pieces of metal of the appropriate kind depending on the material of the engine block. It might require a high rank of metal sawing, as I imagine they're a bit beyond a hacksaw, but they should be able to be broken down.

**Comment by kevingranade** [comment]
A quick search indicates that engine blocks are scrapped with HUGE shredding machines.
They're prohibitively difficult to take appart into chunks otherwise, and it's very questionable what alloy you're going to get anyway.

If anything I'd be tempted to say that scrapping vehicle frames is way too easy and should be looked at pushing in the other direction.

**Comment by MrHrulgin** [comment]
I agree that for modern society it only makes economic sense to use giant scrapping machines. I'd even be in favor of significantly higher time commitments for getting usable metal out of vehicle parts. It's their completely unscrappable nature that bothers me. I've found [a thread](https://www.garagejournal.com/forum/threads/help-cutting-cast-iron-engine-block.460269/) talking about the process of cutting down an engine block for other uses which suggests that with an industrial bandsaw it's straightforward and with an angle grinder and acetylene torch it's possible, but incredibly tedious and expensive. Would it make more sense to have larger metal objects be moved to only really being able to be salvaged in something resembling a full-on machine shop setup?
