### ISSUE TITLE
Duct tape described as liquid when unloading from cardboard roll

### ISSUE THREAD

**Issue by TudorS98** [CleverRaven/Cataclysm-DDA#70739]
### Describe the bug

Traded with refugee center for cardboard rolls containing duct tape. When trying to unload said containers the log gives a message saying "The liquid can't be unloaded in its current state!". 

### Attach save file

[Wrenshall-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13852848/Wrenshall-trimmed.tar.gz)

### Steps to reproduce

1. Obtain cardboard roll with duct tape
2. Open item in inventory
3. Press 'U' for unload 

### Expected behavior

I expected to end up with an empty cardboard roll and some duct tape.

### Versions and configuration

- OS: Windows 11
- Game version: 69cddfe (tiles) build 2024-01-06-0528
- Ingame language: English

**Comment by PatrikLundell** [comment]
While the error message doesn't make much sense, preventing you from destroying your duct tape by unwinding it and pick up all kinds of dust and sand does make sense. A pile of dirty tape with very poor adhesion would be rather useless except as some kind of crappy string.

**Comment by Karol1223** [comment]
Not being to unload the rolls is intentional, I specifically did that on purpose. The real bug report here is that weird log message.
