### ISSUE TITLE
Dumb Character Dialogue Options

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#70744]
### Is your feature request related to a problem? Please describe.

I was thinking of adding additional dialogue options for characters w/ intelligence of <= 4, kind of like in Fo1 & Fo2

### Solution you would like.

Adding a couple of these, for instance w/ Rubik, he'd notice you're a little slow, so he'll sell you a neural booster at a discount (Or as a reward for the warehouse mission?) or maybe just a few extra dialogue options (Nothing too specific)

### Describe alternatives you have considered.

Not doing it; it's mostly a worldbuilding thing, & it might not fit into CDDA too well

**Comment by Zireael07** [comment]
I'd edit the issue title to make it clear you want dialogue for "dumb" characters, not that you think some CDDA dialogue is dumb

**Comment by ADekema** [comment]
It is possible for your intelligence drop below 4 becease of mutation. Maybe have a few options if your intelligence drops to low from mutation. Something like growing instead of spreaking becease your halve bear brain forgets what speech is sometimes.

**Comment by fairyarmadillo** [comment]
Your intelligence dips that low from pain or other effects all the time, but in those cases you're just too distracted by your allergies or having the flu or a bullet in your leg. You wouldn't forget how to use proper English.

**Comment by PGR-14** [comment]
> Your intelligence dips that low from pain or other effects all the time, but in those cases you're just too distracted by your allergies or having the flu or a bullet in your leg. You wouldn't forget how to use proper English.

There's specific values for normal stats; I.E. You choose int 12 in char creation, you get unholy amounts of pain, that value is still 12; it can only be changed due to mutations or through the debug menu.

**Comment by fairyarmadillo** [comment]
I'm a bit worried this would just wind up making fun of developmentally disabled people, or introducing unrealistic caveman talk.

**Comment by PGR-14** [comment]
> I'm a bit worried this would just wind up making fun of developmentally disabled people, or introducing unrealistic caveman talk.

If we go through w/ it, we probably won't add in caveman talk, mostly small misunderstandings & some additional dialogue. I just wanted to add it for RP/Immersion purposes.

**Comment by Rokharn** [comment]
> caveman talk

Sounds reasonably for Innawood and so on, for example.
