### ISSUE TITLE
Failed to write options?

### ISSUE THREAD

**Issue by SirClarke** [CleverRaven/Cataclysm-DDA#70753]
### Describe the bug

The game will not launch it just says this i know it's not very helpful but i do not know much of anything about computers any help would be appreciated if it helps i update the game almost every time i play but now it seems not to work even if i roll back to previous version 

### Attach save file

i can't get into the game to get a file 

### Steps to reproduce

Start the game

### Expected behavior

the game to start

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/31796878/5b685786-40c3-4245-9254-bfc2865b2746)

### Versions and configuration

Windows 10 64bit Experimental

**Comment by KeremBabaG** [comment]
Yeah I'm getting this one as well

**Comment by tallismoore** [comment]
Just came on here to file this bug myself! Super frustrating. For reference, I'm also on Windows, and it seems to apply to the last few experimentals. However, I tried the O.G stable release, and it runs just fine.

**Comment by SirClarke** [comment]
This build works for me so not sure what has changed from this one to the new one
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/31796878/ecb74e65-6a24-41fa-8369-dbe027e4cb52)

**Comment by KeremBabaG** [comment]
> This build works for me so not sure what has changed from this one to the new one ![image](https://private-user-images.githubusercontent.com/31796878/294789268-ecb74e65-6a24-41fa-8369-dbe027e4cb52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjcyOTQsIm5iZiI6MTcwNDY2Njk5NCwicGF0aCI6Ii8zMTc5Njg3OC8yOTQ3ODkyNjgtZWNiNzRlNjUtNmEyNC00MWZhLTgzNjktZGJlMDI3ZTRjYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIyMzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzAwZGQ0NjE1OTgxNTI5NjU1OGEyZGYyZTRlMDUyZWY3N2Q3ODk3ZDM1ZjU3NWNkNjAwNzBkMDRmZDY2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.81qTRTMwp1erK-pwe1UUn_hTWz0dInqAp6sx_5Xj47Q)

wait lemme check the merged prs since then

**Comment by SirClarke** [comment]
thanks for looking hopefully someone knows and it will get fixed soon

**Comment by ZhilkinSerg** [comment]
#70589

**Comment by DMDasher** [comment]
Yeah, I also have this issue.
Here's my debug if that helps.

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13855209/debug.log)

**Comment by Shockeray** [comment]
Same issue for me. I was really confused because I haven't played in like a year and thought I was doing something wrong.

**Comment by davidknapik** [comment]
Came here for a me-too, the following version not working (clean install):

cdda-windows-tiles-sounds-x64-2024-01-07-1954
Windows 11 Home 10.0.22621 Build 22621
Installed under d:\games\cdda (no spaces, weird characters etc.)

Messed around with verifying directory ownership & write permissions before checking here.

**Comment by HeadsetRuler** [comment]
Seems to me the code is seeing the dot at the start of the path as an invalid filename? Adding some exceptions to the heuristics for . and .. in all but the final element should hopefully fix this.

**Comment by jasonaltenburg** [comment]
Same issue. Windows 11 got same message as OP screenshot with cdda-windows-tiles-sounds-x64-2024-01-07-2312

**Comment by SirClarke** [comment]
Nice thanks a lot
