### ISSUE TITLE
Armored Jeans Layering Issue

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#70750]
### Is your feature request related to a problem? Please describe.

Armored Jeans are worn only as overtrousers, due to having the OUTER flag only

### Solution you would like.

Stitching on knee pads and sheet metal should make a pair of jeans bulky enough to be normal layer and outer layer armor

**Comment by KeremBabaG** [comment]
Well what's the issue? it has like 1.5 milimeters of fabric and 6 milimeters of hard plastic at its thickest. I don't think it can be worn under, say, a pair of jeans.
