### ISSUE TITLE
Bayonet Creates Firing Problem

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#70762]
### Describe the bug

If the player selects an attached bayonet as the active firing mode for a rifle, it is no longer possible to shoot the rifle. 

### Attach save file

[Brandywine-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13856138/Brandywine-trimmed.tar.gz)

### Steps to reproduce

1. Make a player with an AR-15 and attach an army bayonet. 
2. Press `f` then switch the active firing mode to the bayonet. 
3. Press `f` again and attempt to fire. 

### Expected behavior

I expected to be able to switch firing modes and fire the rifle after selecting the bayonet as the active firing mode. I partly expected the bayonet to be able to do reach attacks also using `f`, but selecting the firing mode and shooting the gun was what I expected most. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 04b6eb2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This issues doesn't cause the game to crash, but the bayonet must be uninstalled before the rifle can be fired again.

**Comment by Vaskritaya** [comment]
If I remember correctly, there's a keybind for switching firing mode directly, and that works for unfucking the gun. 

The bayonet firing mode doesn't do a whole lot anymore ever since reach attacks were removed from bayonets. Not sure if there's a point to keeping it around since it's just a nuisance as far as I can tell.
