### ISSUE TITLE
Firearm Magazine Size Audit

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#70784]
### Is your feature request related to a problem? Please describe.

A few years ago, when pockets and object length were introduced there was an effort to get items and pockets up to par.  While there was a lot of initial enthusiasm, it is a lot of work and a lot of people (including me) burned out trying to chug through pages and pages of measurements.

While the size of firearms themselves are in a pretty good state due to their large impact on the game, their magazines have unfortunately been left in the dust.  The magazines of smaller firearms are in many cases treated as the same or similar bulk and weight of much larger firearms, negating a distinct advantage of opting for a smaller caliber (the ability to carry more magazines in a smaller space).

### Solution you would like.

This issue will be used for keeping track of the magazine audits that have been completed.
I'm doing it this way instead of making everything a single PR as I previously attempted, because quite frankly if I burn out part of the way through I want at least some of the work to make it to the player base instead of languishing in Github hell.

There are two ways I've been doing this so far.

1. Take a magazine I own, tape up holes and openings and drop it in a big cylinder I've got.  Caveman science, but water displacement doesn't lie.
2. Use ImageJ to analyze dimensions of magazines that I do not own.  Images are sourced from friends and the Internet.  Weight is taken from manufacturers wherever possible, and where it is not I check multiple vendors.

All of the previous work I've done in this regard still holds up, so there will be one or multiple pull requests to quickly merge the work I've already done.

For transparency, the methods I've used to ensure accuracy are here from greatest to least:
IRL Measurements -> ImageJ -> Comparison

For any future work, corrections should probably only be done with a triumphing measure of accuracy, unless there is an obvious error with a previous measurement.  In other words, an audit done through ImageJ should be corrected with IRL measurement, not through comparison.

### Additional context

Relevant PRs include my previous attempt #60038, #37374 (seems to have mainly focused on firearms, which are in an okay place right now) and information from @Hyperseeker added with #70715.

If anyone else is interested in doing this, there are relevant instructions in #37374 for the usage of ImageJ for this project.
This is also a good page: https://serc.carleton.edu/eyesinthesky2/week2/get_to_know_imagej.html

- [x] .22LR
- [x] 9x18
- [x] 7.62x54R
- [x] 7.62x25
- [x] 7.7 Japanese
- [x] .38 Special
- [x] 5.7x28
- [x] 762x39 (AR47 Magazines Unaudited)
- [x] .50 AE
- [x] .44 Magnum
- [x] .32 ACP
- [x] 5.45x39
- [x] .30 Carbine
- [x] .410
- [x] 12 Gauge
- [x] .338LM
- [x] .50 BMG
- [x] .460 Rowland
- [x] .30-06 Springfield
- [x] .38 Super
- [x] .460 Rowland
- [x] .500 S&W Magnum
- [x] .454 Casull
- [x] .357 Magnum
- [x] 4.6x30mm
- [x] .45 ACP
- [x] .300 Winchester Magnum
- [x] .303 British
- [x] .380 ACP
- [x] .357 SIG
- [x] 10mm Auto
- [x] .40 S&W
- [x] 12mm
- [x] 40mm
- [x] 66mm
- [x] .223 Remington
- [x] .308 Winchester
- [x] 9mm Parabellum
- [x] .300 Blackout
- [ ] 5x50
- [ ] 20x60mm

**Comment by Hyperseeker** [comment]
Also relevant: https://github.com/CleverRaven/Cataclysm-DDA/pull/70715

One thing I would like to ask of you is: if possible, provide dimensions (and, if available, online sources) for the audit data. Some of the magazines I'd audited for my own mod took *hours* to source online. I can only imagine that much of it is rounded or imprecise; which, still better than the regular N × 250 ml, may require re-auditing in the future, should better data become available.

To have all this effort run through without leaving a crumb of data for the future devs (and modders like myself) to rely on seems like a waste.

**Comment by ANickelN** [comment]
You're completely correct about that, would leaving it as comments in the JSON work alright?

**Comment by Hyperseeker** [comment]
Comments in JSON should work fine.

Alternatively, should you wish for a cleaner JSON, you can also leave all the sources and dimensions in the body of the PR. When I need to figure out what's the thing supposed to be in the base game (e.g. heavy load bearing vest), I also go through Git blame and find the PR that added it.

**Comment by GuardianDll** [comment]
There is pros and cons of both methods:
Storing sources in item is good approach, but links on the internet tend to die, and sometimes unexpectedly die; for this they allow to know that item is actually sourced from real example, and not guessed (no matter of the state of the link), and doesn't require to dig into 9999 edits through the history of git blame
storing stuff in the body do not burden the json, but also require future contributors to know where to dig - which is not great

despite i didn't put sources in #70715, i regret it a bit, and think i need to actually add them - they aren't that bulky, when styled with our linter

**Comment by ANickelN** [comment]
Okay, so what I've decided on is to leave commenting within the JSON indicating the magazine has been audited, and what method was used (IRL Measurements, ImageJ, Comparison).

Within the PR will be detailed notes of how the calculations were done.  That way, anyone checking blame just has to check the line with the comment to find the information.  

(Not that most of these files have many changes anyways, but this should future-proof)

**Comment by Hyperseeker** [comment]
Wonderful. Is there any chance that, after you're done actually auditing all the stuff, you can add the same info for the .22 LR mags?

**Comment by ANickelN** [comment]
> Wonderful. Is there any chance that, after you're done actually auditing all the stuff, you can add the same info for the .22 LR mags?

The .22lr stuff was actually from the few years old PR so I wasn't keeping track of any sourcing at that time.  From what I remember the 10/22 stuff was personally dunked, and I think most of the rest was ImageJ.  I can go through and revisit it once I've hit some of the bigger culprits.

**Comment by ANickelN** [comment]
@Hyperseeker 
Do you mind if I take some of the information from your mods?  Of course, you are free to do the same to anything I've scrounged up.

**Comment by Hyperseeker** [comment]
You can take anything you want. (If you check #70715, you will find a screen capture of my written approval from the community Discord server.) That said, odds are that everything related to magazine volumes has been ported already. If you find anything, though, do as you please!

**Comment by Hyperseeker** [comment]
Just wanted to check in on the progress of this. I'm looking to continue working on Armory, which relies on these measurements (among others) to correctly model the pockets. My hope is that by seeing this effort through before the 0.H release, the measurements will then be in the base game, and I wouldn't have to re-create them on my (mod) end. (This isn't a guarantee, of course, but I remain hopeful for now.)

Is there anything I can do to help speed this up? Research, image references?

**Comment by ANickelN** [comment]
The biggest hit to productivity is the sheer amount of magazines in the .223/9mm/.308 categories.  If you want to take over 9mm, at my current pace I can likely get through .223 and .308 by February 11th.

**Comment by Hyperseeker** [comment]
If you open a draft PR for what calibers are left to audit, I can contribute my research to the comments. I won't author a PR or a commit myself, but I'm perfectly eager to donate my time to this effort.

**Comment by ANickelN** [comment]
I'll tag you in when I open up something.

**Comment by Hyperseeker** [comment]
The bot reminded me:

@ANickelN, I think you might have missed .450 Bushmaster mags. I did some quick maths, and I think those mags should be about 25% smaller, or thereabouts.
