### ISSUE TITLE
Barter options and limitations for valuable knowledge

### ISSUE THREAD

**Issue by 321nick** [CleverRaven/Cataclysm-DDA#70800]
### Is your feature request related to a problem? Please describe.

Barter system works pretty good for equipment and consummable items: aspirin being worth a dollar or so makes sense, even if your trading someone 1 pill or 10. But when it comes to books and other pieces of knowledge, like schematics, it breaks down. A trader wouldnt often be interested in 2 copies of a chemistry textbook, since you dont get double the valuable information and knowledge within. 

Also, you cant sell digital copies of Ebooks even though they have the same information. ideally, a USB stick with 5 books on it would have the value of those 5 books, assuming the person your selling to doesnt already have the knowledge of those 5 books.

### Solution you would like.

1. once a book (or USB/sd memory card with an e-book stored on it) is sold to a trader, that book cant be sold to them again, and USB sticks/sd memory card with that book copied onto them dont get the value of that book added to their barter value
2. USB sticks/sd memory cards should have the value of the e-books stored on them added to their base barter value

### Describe alternatives you have considered.

maybe low-skill lone NPCs also should also be picky when it comes to buying high-skill level books they cant make heads or tails of, but thats more of an additional thing not an alternative

### Additional context

related to https://github.com/CleverRaven/Cataclysm-DDA/pull/70587 , cause ideally  you could sell schematics once to every faction and get a lot of money for that, but not re-sell the same schematic to the same faction, cause they already read it.

**Comment by IdleSol** [comment]
But the trader can sell the book to another character. So if you do restrictions, it's not for faction traders.

**Comment by 321nick** [comment]
> But the trader can sell the book to another character. So if you do restrictions, it's not for faction traders.

im assuming if anyone sells a book, they either already read it fully or already made a backup of it themselves. ideally the memory would go beyond if they just have the book present or not and should remember if they ever had the book previously, even if they dont have it currently, when it comes to the demand to buy that book again
