### ISSUE TITLE
Backgrounds can accept spells, and display the spells in the UI, but don't give you the spells.

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#70815]
### Describe the bug

Working on #70803 and I have it all set up. It even shows in the UI properly:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/aa63065d-f4eb-4c9e-af65-2a9757524089)

However, upon actually entering the game, none of those powers are granted. Only the default powers from the Teleporter traits: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/b8fb1022-ce3d-40d4-8af6-9e68ff80b9d5)

### Attach save file

N/A

### Steps to reproduce

1) Paste the following JSON somewhere in your game and load Mind Over Matter:
`{
    "type": "profession",
    "subtype": "hobby",
    "id": "late_teleporter",
    "name": "Ascended Teleporter",
    "description": "Something happened during the storms that raged during the Cataclysm, and now you can do things that would have once seemed impossible.  No wall or door is a barrier to you and sometimes when you close your eyes you can travel to places you've already been.  Once you were surprised by a bandit and when he leveled his gun at you, you wished he was somewhere else and he just...disappeared.  Nothing can keep you down now.",
    "points": 13,
    "traits": [ "TELEPORTER", "TELEPORTER_PROTECT" ],
    "skills": [ { "level": 7, "name": "metaphysics" } ],
    "spells": [
      { "id": "teleport_blink", "level": 11 },
      { "id": "teleport_slow", "level": 12 },
      { "id": "teleport_displacement", "level": 10 },
      { "id": "teleport_stride", "level": 12 },
      { "id": "teleport_phase", "level": 12 },
      { "id": "teleport_collapse", "level": 7 },
      { "id": "teleport_farstep", "level": 10 },
      { "id": "teleport_banish", "level": 6 },
      { "id": "teleport_gateway", "level": 4 },
      { "id": "teleport_area_attune", "level": 1 }
    ]
  }`
2) Apply the Ascended Teleporter background to a new character.
3) Check the spellcasting menu.
4) Notice that only Blink and Stutterstep, the default powers granted by the TELEPORTER trait, appear.

### Expected behavior

The character is granted the powers that the UI tells them they will be granted.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: e71d5b1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by FlaKougar** [comment]
avatar::initialize @ newcharacter.cpp:983   is 
`prof->learn_spells( *this );`
This learns spells just from the profession.
Need to do something like` void Character::set_proficiencies_from_hobbies()`
to iterate over hobbies and learn spells from them.   The current profession->learn_spells handles same spell from multiple hobbies correctly so it should be a straight forward to implement.    I don't have a setup to build currently so can't test out a patch for this.
