### ISSUE TITLE
Make u_spawn_monster works properly with mongroups

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#70812]
### Is your feature request related to a problem? Please describe.

U_spawn_monster still unable to spawn multiple monsters out of group, always spawning a single one, including using `"u_spawn_monster": ""`, that should pick random critter around and spawn it's copy

### Solution you would like.

Ability to pick do you want to spawn 50 copies of a single monster, or 50 different monsters 

### Additional context

I tried multiple approaches, none of them was successful
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/08a791c6-1508-4d91-8bea-d0d2a19a4112)

**Comment by Procyonae** [comment]
For clarity `"group": true` currently spawns 50 of the same monster right?

**Comment by Procyonae** [comment]
Can you include what you want the end syntax to look like?

**Comment by GuardianDll** [comment]
No changes in syntax. If someone wants to preserve this feature, they can make some boolean `"single_type": true`, that'd fall back to previous (meaning current) way it works
