### ISSUE TITLE
You can get infinite farthings from Rubick

### ISSUE THREAD

**Issue by phoenix492** [CleverRaven/Cataclysm-DDA#70825]
### Describe the bug

During the dialogue where Rubick asks you questions about the world they've just arrived in, he can give you a shiny farthing if you inform him through an INT 7 check that fusillies and mobbings are guns and cars respectively. If you then select the universal dialogue box options to Look At, Size Up, Yell, etc. The popup stating Rubick gives you a farthing reappears and you'll receive another one. This can be repeated as many times as you want 

### Attach save file

[Godless Wasteland-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13889443/Godless.Wasteland-trimmed.tar.gz)

### Steps to reproduce

1. Talk to Rubick and go through some of his introductory/expository dialogue until he asks if he can ask you a few questions. 
2. Answer his questions and then go down the dialogue tree where you give Rubick this world's words for cars and guns.
3. Once Rubick gives you the farthing, on the line of dialogue that says "Right so, us'n'll write it in the dicky. Here, a shiny brass farthing for crossin' the nation," use one of the "Check" options on the right of the dialogue box.
4. Once you press "okay" to exit, Rubick will give you the farthing again. 

### Expected behavior

I expected to only receive a single farthing, as this is effectively a source of free and infinite, if slow and inefficient, trade value. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/17846991/1e283fea-e144-44c5-af6a-78bf50db9cce)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 5d3d33c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I did not test it, but I wouldn't be surprised if this issue extended to other places in the game you receive an item from an NPC through a similar popup box.

**Comment by MrHrulgin** [comment]
I was able to do the same thing with Rubic, but tested it on the Hub mission trigger where you get the environmental suit and wasn't able to get duplicates, so it's not universal.
