### ISSUE TITLE
Portal storms of death

### ISSUE THREAD

**Issue by Yobrocharlie** [CleverRaven/Cataclysm-DDA#70834]
### Describe the bug

On the newest experimental if you go into a portal storm you will be teleported into the small dungeon with no way out period (unless you feel like quantum tunneling outside and falling six stories to your DOOM) none of the vortexes work and neither does the one you come through work.

### Attach save file

N/A

### Steps to reproduce

1: Go to portal storm with character you’ve put hundreds of hours in
2: Can’t leave it
3: Cry

### Expected behavior

Portal storms should normally let you into the micro dungeon you complete it and get some good temporary buff or some item in exchange for being tired.

### Screenshots

N/A

### Versions and configuration

Build 2024-1-10-0519

### Additional context

I did this with a portal storm dependent person don’t know if that changes or effects anything. I did this first in vanilla and then with a lot of mods so I think that it’s related to the newest experimental branch.

**Comment by Procyonae** [comment]
Dupe of #70832

**Comment by Yobrocharlie** [comment]
Oh okay I’m stupid
