### ISSUE TITLE
Remove mufflers from electric cars 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#70840]
### Is your feature request related to a problem? Please describe.

At least Luxury Electric Coupe has muffler but they require no exhaust system.
I will add other car names when found them 

### Solution you would like.

just remove muffler from electric car spawns

**Comment by kasanryukin** [comment]
As PatrikLundell said, muffles are heat exhaust.  In combustion engines that heat is usually from gasses, but even some electric cars have methods of dumping waste heat from the electric engines and batteries.  Usually it's in the hvac system, but some (like the model y) even have a dedicated heat pump to deal with adding or removing heat from the cabin.

**Comment by Zireael07** [comment]
We could introduce new vehicle part for heat dumps instead of using mufflers. Mufflers on electric cars make no sense
