### ISSUE TITLE
Autopathing up and down

### ISSUE THREAD

**Issue by WyrdDarcnyzz** [CleverRaven/Cataclysm-DDA#70841]
### Is your feature request related to a problem? Please describe.

#70479 introduced a bug that caused you to teleport to the next level down at the position of a staircase down if you were on the same screen as one. This has since been fixed. Thing is, that's actually a brilliant quality of life feature present in a couple other roguelikes, notably Caves of Qud and (I think) Dungeon Crawl Stone Soup. I'd love to see a similar feature implemented here. Not needing to manually path to the staircases when trying to traverse multiple levels (like labs) would cut out a whole lot of keystrokes, and save my wrist some RSI.

### Solution you would like.

The idea is that pressing the "go up" or "go down" keys without having the ability to currently do so would throw up a prompt, as it currently does. The prompt would note that you have no way of doing that, and would then ask if you'd like to path to the nearest staircase up or down and change level. Selecting yes would then have your character use the automove function to seek out the nearest available staircase and automatically use it. You'd specifically want to have it search for staircases or ramps, since having automove throw you off a building would be somewhat problematic. If there are multiple equidistant from the character, it'd select perhaps from a clockwise pattern.

Of course, as with all automove functions, the use of this function would be ENTIRELY as the discretion of the player, with all applicable warnings (and consequences) thereof. As was noted in the discord, turrets don't really care about autopathing.

### Describe alternatives you have considered.

Crying as my wrist screams at me. Or perhaps using mouse move, since it was noted that that is actually a function we have.

**Comment by ZhilkinSerg** [comment]
That only makes sense w/o any additional prompts and only for neighboring staircases in 1 tile radius, otherwise it would bring more troubles (though with safemode on it might not be that bad).

**Comment by WyrdDarcnyzz** [comment]
Given that Safe Mode usually defaults to on anyways, I assume it'd mostly be used with it on anyways. Unless you have Safe Mode turned off by default; in which case, you're taking your life in your own hands anyways lol

**Comment by fairyarmadillo** [comment]
Autopathing is an immersion killer and given that this isn't a game where you're clearing out single levels of a finite dungeon, I'm not sure it makes a lot of sense.

**Comment by WyrdDarcnyzz** [comment]
That isn't really a reason not to add it, more a reason not to use it. I could see it being able to be disabled in the options menu, though I know some folks hate adding new options. 

As far as immersion killing, I can only disagree personally. I use autodrive religiously, and pathing through forests and the like is a nightmare without autopathing. 

And also, having it search only within a certain radius would keep it sane. Admittedly, Qud is mostly sectioned off into discrete tiles, so the autopath is set there to just search the entire tile; it would need to be implemented slightly differently in CDDA.

The idea is to remove a bunch of unnecessary keystrokes without having to resort to using the mouse.
