### ISSUE TITLE
[Magiclysm] Wizard Basement Secret Door Does Not Open

### ISSUE THREAD

**Issue by NthTech** [CleverRaven/Cataclysm-DDA#70856]
### Describe the bug

Currently playing on https://github.com/CleverRaven/Cataclysm-DDA/commit/c51a21b458e962d17f3bd322c38be0260a627f5e, The magic trap underneath the coat rack does not seem to work, and the entrance to the secret room, marked by the inscription, does not open.

### Attach save file

[Magiclysm Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13916663/Magiclysm.Test-trimmed.tar.gz)

### Steps to reproduce

1. Make a new character with The Wizard's Apprentice scenario
2. Use the character to 'G'rab the coatrack, then pull it to the side.
3. Stand on the square the coatrack occupied.
4. Attempt to enter the secret room

### Expected behavior

I expected the secret room to be accessible after triggering the trap that opens the secret room, since this is the designed way to reveal the secret room, and I am unaware of any updates that have changed this method. 

### Versions and configuration

OS: Windows 10
Game Version: c51a21b, 64bit
Graphics Version: Tiles
Mods Loaded: [dda], [no_npc_food], [personal_portal_storms], [no_fungal_growth], [magiclysm]

### Additional context

I tried replicating the bug on two earlier versions as well, namely https://github.com/CleverRaven/Cataclysm-DDA/commit/35e320e3479cf5e0b34738e74dc5975de6a2c4bc and https://github.com/CleverRaven/Cataclysm-DDA/commit/96ae2db850b179ab8cb00f88fc69e664a818e35e. The bug did not occur in https://github.com/CleverRaven/Cataclysm-DDA/commit/35e320e3479cf5e0b34738e74dc5975de6a2c4bc, as the secret room opened as expected. However, the bug did occur in https://github.com/CleverRaven/Cataclysm-DDA/commit/96ae2db850b179ab8cb00f88fc69e664a818e35e with the room failing to open, so the bug was introduced some time between these two commits.

**Comment by mqrause** [comment]
Should be fixed by #70836 once it's merged.

**Comment by NthTech** [comment]
Since it's a known issue with a fix already underway, I'll just close the issue.
