### ISSUE TITLE
"Dud" grenade from booby trap.

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#70854]
### Describe the bug

Ok so went into a cave that had a couple different traps before ultimately leading me to an area where someone setup camp. (No NPCs were actually there.) I set off a trap that ended up dropping a "live" grenade but it never went off. I waited a good couple seconds behind cover. Even went and picked it up and threw it just to see if it would work then, it did not. Note that all the traps were covered in webs.

### Attach save file

Not at my pc atm.

### Steps to reproduce

Set off booby trap, it was like five traps in. The one roght after the mine trap. Throw rock and activate the trap, it drops a "live" grenade but the grenade never explodes.

### Expected behavior

Grenade should explode after 3-5 seconds, I do not know what the fuse is set to.

### Screenshots

No screenshot

### Versions and configuration

Exp version 2024-01-09-0454
Windows 11
English
MoM, Magiclysm, and Xedra as far as game changing mods go.

### Additional context

N/A

**Comment by RenechCDDA** [comment]
Despite the timing, this is NOT related to #70832.

Wagering a guess, this is probably due to the (some months ago) change to how active items work. Not sure on the exact way to resolve it.
