### ISSUE TITLE
Debug spawning menu still shows charges in some cases

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70852]
### Describe the bug

As an example: If you go to the debug item spawning menu and search for duct tape, it shows you an item description that says "Amount: 200." If you spawn 1 duct tape, you get exactly 1 unit of duct tape out of a full roll of 200, rather than 1 full roll with 200 charges. This isn't universal, as some things that had charges show things differently now.

### Attach save file

N/A

### Steps to reproduce

Open debug item spawning menu, see charges still listed.

### Expected behavior

I'd expect that the amount of charges wouldn't display anymore, if it's no longer relevant. This is only a display bug, as asking for 1 unit of duct tape does appropriately give you only 1 unit.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/45711266-8f3d-4778-83d2-5cca8b5f1de3)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/d753b918-a36c-4b58-9998-bfc6bcefa528)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by mqrause** [comment]
> This isn't universal, as some things that had charges show things differently now.

Well the main reason for that is that duct tape still has charges. That also means that probably nothing changed about debug spawning that. You could compare it to 0.G or an even earlier stable to check if anything actually changed.
