### ISSUE TITLE
Duplicate refugee center missions 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#70861]
### Describe the bug

Jenny Forcette gives duplicate mission "Find reference materials about air rifles for Jenny."

### Attach save file

[Leonard-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13919809/Leonard-trimmed.tar.gz)

### Steps to reproduce

1. Talk with Jenny Forcette about her job here.
2. you will recive mission 
3. Ask here same question.
4. You will recive same duplicate mission 

### Expected behavior

She should give only one mission at time 

### Screenshots
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/45aa8e90-ccee-4549-baae-b4cb6cdddf22)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by MrHrulgin** [comment]
I've seen that as well.
