### ISSUE TITLE
Recipe for "cooked plant stalk" requires no actual cooking.

### ISSUE THREAD

**Issue by FrogVoice** [CleverRaven/Cataclysm-DDA#70866]
### Describe the bug

No idea if this is intentional and I'm missing something but the recipe for a cooked plant stalk requires no cooking whatsoever, it just needs the raw plant stalk and magically turns it into the cooked version. It takes 21 minutes so maybe the character is screaming at it really loud to generate enough energy to cook it but that seems rather unlikely.

### Attach save file

[Oakboro-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13922896/Oakboro-trimmed.tar.gz)

### Steps to reproduce

1. Get plant stalk from foraging in the woords.
2. Open crafting menu.
3. Scratch your head at the cooked plant stalk not needing any cooking.

### Expected behavior

It should at the very least require a nearby fire or other common way to cook something.

### Screenshots

![cataclysm-tiles_2024-01-12_19-39-11](https://github.com/CleverRaven/Cataclysm-DDA/assets/63249256/19013b09-e8ea-4532-b037-0fa5cc04328e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 59b70b4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by GuardianDll** [comment]
#69057

**Comment by ANickelN** [comment]
/confirmed
Actually, nevermind.  I'm pretty sure the character screaming at a plant for 21 minutes to cook it is intended.

**Comment by FrogVoice** [comment]
Fixed in #71266
