### ISSUE TITLE
Zombie Hunter doesnt fall down z levels when walking off ledge

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70876]
### Describe the bug

Monster "Zombie Hunter" doesnt fall down z-levels when walking over ledges

### Attach save file

[Rock-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13924856/Rock-trimmed.tar.gz)

### Steps to reproduce

drive around crater, zombie hunter will not fall

### Expected behavior

Zombie Hunter should fall down z-levels

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/107653330/be18446a-fed6-4313-afc0-46dcded4efac)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: c51a21b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

**Comment by fairyarmadillo** [comment]
In that screenshot, he can't fall because there's another zombie under him.

**Comment by Consoleable** [comment]
> In that screenshot, he can't fall because there's another zombie under him.

This zombie hunter came from the west, so passed over several spaces where there were not zombies under them.
