### ISSUE TITLE
Crash, requested mission UID 5 does not exist

### ISSUE THREAD

**Issue by RobotJesuss** [CleverRaven/Cataclysm-DDA#70871]
### Describe the bug

When I try to move towards the warp escape of the Sky Islands mod, the game crashes and gives me

Game crashes giving screen

  DEBUG    : requested mission with uid 5 does not exist

 FUNCTION : find
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission.cpp
 LINE     : 95
 VERSION  : 2a67568

### Attach save file

[Scottsville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13923294/Scottsville-trimmed.tar.gz)

### Steps to reproduce

Follow the road and head towards the extraction noted in the mission

### Expected behavior

Game doesn't crash as I approach extract

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Magiclysm [magiclysm]
]

**Comment by physics-enthusiast** [comment]
Was this a previously visited area where a past slaughter mission may have been generated? If so could be related to #70650
