### ISSUE TITLE
Randomly Crashing

### ISSUE THREAD

**Issue by Pugglee** [CleverRaven/Cataclysm-DDA#70883]
### Describe the bug

The game will crash, with no crash log.  The crash can occur at seemingly anytime whether I am moving, looking at my inventory, or looking at the map.  The crash will happen seemingly randomly.  I believe that the crash may be triggered by autosave but that is a very shaky belief.

### Attach save file

[West Hartford.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13926751/West.Hartford.zip)

### Steps to reproduce

1. Spend time playing until crash occurs, it can take from seconds to over 10 minutes

### Expected behavior

I expected the game not to crash

### Versions and configuration

-OS: Windows 11 -Game Version: catapult-win-x64-23.12a -Experimental Build: 2024-1-13-0233 -Tiles: Ultica, Larwickovermap for map -Ingame: Language: English -Mods Loaded: dda, no hope, mind over matter, blaze industries (marked as obsolete), Mythical Martial Arts, Bionic Slots, Disable Npc needs, Portal storms ignore npcs, speedydex, stats through skills.

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13926754/debug.log)

**Comment by fairyarmadillo** [comment]
Blaze Industries is no longer supported. I'm guessing that's the cause of your trouble.

**Comment by Pugglee** [comment]
The issue was with my computer, don't know what the issue was but it is fixed
