### ISSUE TITLE
Slip prevention modifier - denominator cannot be set to 0

### ISSUE THREAD

**Issue by Rokharn** [CleverRaven/Cataclysm-DDA#70885]
### Describe the bug

Every experimental builds for windows having no msvc version and as result contain very same issue. Last worked: cdda-windows-tiles-sounds-x64-msvc-2024-01-09-0454. Russian windows locale, windows 7. 

Cannot load old saves or even creating new characters. Same for fresh install. 

Info from debug file:

```
 09:26:00.831 ERROR : src/main_menu.cpp:1038 [bool main_menu::load_game(const std::string&, const save_t&)] Error: Json error: data/json/character_modifiers.json:134:13: <color_white><color_cyan>denominator cannot be set to 0</color>

     "description": "Slip prevention modifier",

    "mod_type": "x",
 
 <color_light_red>    "value": { "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
 </color>
            <color_cyan>в–Ів–Ів–І</color>
       "override_encumb": true,
      "limb_score_op": "+",
 </color>
 
 09:26:08.131 ERROR : src/main_menu.cpp:986 [bool main_menu::new_character_tab()] Error: Json error: data/json/character_modifiers.json:134:13: <color_white><color_cyan>denominator cannot be set to 0</color>
 
     "description": "Slip prevention modifier",
 
     "mod_type": "x",
 
 <color_light_red>    "value": { "limb_score": [ [ "grip", 3.0 ], [ "lift", 2.0 ], "footing" ],
 </color>
            <color_cyan>в–Ів–Ів–І</color>
       "override_encumb": true,
       "limb_score_op": "+",
 </color>
 
 09:26:27.756 : Log shutdown.
```

Sounds very same as  [](https://github.com/CleverRaven/Cataclysm-DDA/issues/61095)

### Attach save file

Issue appear before save can be created too

### Steps to reproduce

1. Windows 7 (locale - ru)
2. Download any of last regular cdda version (not the msvc one, anyway there no msvc version for any of new assets)
3. Try to create character
4. Look at game error.

### Expected behavior

Ability to load saves and start new character at the regular cdda versions, not only with msvc ones.

Or msvc builds, which for some reasons not appear for the last days anymore, for newest experimental versions again. Before more people ask same non trivial question about win7 (not everyone can make their own msvc compilation or even find this solution).

### Versions and configuration

- OS: Windows
- OS Version: 6.1 7601
- Graphics Version: Tiles
- Game version: from [2024-01-09-0623] to [2024-01-13-0523]
- Game Language: English [en]

**Comment by Rokharn** [comment]
Msvc version's releases for newest experimental versions now [fixed ](https://github.com/CleverRaven/Cataclysm-DDA/pull/70889)

Issue can be closed.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/just-downloaded-the-latest-stable-version-cant-create-character/29275/2
