### ISSUE TITLE
activate-menu should indicate how many moves the action costs

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#70887]
### Is your feature request related to a problem? Please describe.

So I used the compressed air horn to draw zombies to a certain place during the night, and I discovered that activating the item costs quite some moves. Unfortunately, the move cost is neither specified in the item description nor in the "activate" menu - but it can be relevant information, the zombie hunter gnawing my leg after me using the air horn would certainly agree.

### Solution you would like.

Add the movement cost to the "activate"-menu, just like it is listed in the "wield"- and "wear"-menus. Items that have multiple possible actions should have those move costs listed in the submenu.

Additionally, the activation cost could and probably should be added to the item description.

### Describe alternatives you have considered.

Keep the player guessing/memorizing how long it will take to activate items?

### Additional context

Just tested, the air horn - and the "take a picture"-function of the smartphone - seems to have a move cost of 200, as it took 2 seconds each. Chewing a gum did not advance time, so it seems to have a cost of 0?

**Comment by kasanryukin** [comment]
Most things that use the activation menu take 100 moves to perform their action (with several exceptions).  This is pretty standard across most items, but it would be useful for the action and move cost to appear in the description at the very least.
