### ISSUE TITLE
[Magiclysm] XL demon chitin armor needs no tools

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70884]
### Describe the bug

Unlike the regular sized version, the XL demon chitin armor needs no tools.

### Attach save file

N/A

### Steps to reproduce

Look at the recipes

### Expected behavior

I'd expect the same tools needed to make a larger set of the same armor.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/4f699930-6314-4c0d-ba55-5edd32260646)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/67add9a3-226f-4fb9-96e9-98ee97365f7c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Procyonae** [comment]
Caused by #60257
