### ISSUE TITLE
Crash on opening map

### ISSUE THREAD

**Issue by Pugglee** [CleverRaven/Cataclysm-DDA#70881]
### Describe the bug

When I open the map my game will crash within a few seconds. There is no crash report

### Attach save file

[West Hartford.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13926568/West.Hartford.zip)

### Steps to reproduce

All it takes to trigger the crash is opening the map

### Expected behavior

I expected the game not to crash upon opening the map

### Versions and configuration

-OS: Windows 11  -Game Version: catapult-win-x64-23.12a  -Experimental Build: 2024-1-12-2340  -Tiles: Ultica, Larwickovermap for map  -Ingame: Language: English  -Mods Loaded: dda, no hope, mind over matter, blaze industries (marked as obsolete), Mythical Martial Arts, Bionic Slots, Disable Npc needs, Portal storms ignore npcs, speedydex, stats through skills.

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13926526/debug.log)

**Comment by Pugglee** [comment]
Issue no longer present on version 2024-1-13-0233

**Comment by RenechCDDA** [comment]
Also unable to reproduce on d1474f4ecb76a951d083b0f4c410b1dee0ff2b0b (windows 10, MSVC compiled) so I guess this is good to close?

**Comment by Pugglee** [comment]
Posted comment too soon still seems to crash

**Comment by Pugglee** [comment]
However I am crashing randomly while playing so I will make a separate bug report on that
