### ISSUE TITLE
Very Tall/Short mutations lack of incompatibility with CBM

### ISSUE THREAD

**Issue by RangerFromBaja** [CleverRaven/Cataclysm-DDA#70886]
### Is your feature request related to a problem? Please describe.

Currently Very Tall and Very Short mutations are fully compatible with Titanium Skeletal Bracing and Alloy Plating CBMs, while similar mutations affecting size aren't.

### Solution you would like.

Make both mutations be affected by said CBMs.

**Comment by fairyarmadillo** [comment]
It's intended that they're allowed, as both traits are in line with natural human sizes. I doubt the Exodii would be designing bionics that wouldn't work for the tallest and shortest members of their own species.

LARGE and LITTLE make the character roughly the same height, but represent dramatic and inhuman physiological changes that go beyond height alone, as evidenced by their stat changes. These are outside of the natural range of human expression and make for an acceptable cutoff point.

**Comment by RangerFromBaja** [comment]
I was concerned about locking out people from CBMs as well but didn't mention it because I didn't notice that they were already implemented as starting traits in the character creation menu, I agree with your points.

There is a slight issue of getting the traits after you already have the CBMs installed which didn't quite make sense to me, but I don't know how flexible these are supposed to be to begin with, so if it is possible then I'll just close this.

Otherwise, one solution could be "locking" your height if you have them installed, restricting changing the traits from mutations.
