### ISSUE TITLE
Game time passage is abysmally slow when many items are in view

### ISSUE THREAD

**Issue by Hooplah1** [CleverRaven/Cataclysm-DDA#70892]
### Describe the bug

Any time i can view a few hundred items, of any kind or type, any action that passes time slows down accordingly. the more items in view, the slower the time progression. with my whole medium stockpile in view on the floor, crafting progresses at 1% every few seconds of real world time

### Attach save file

[New Sky Island-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13927994/New.Sky.Island-trimmed.tar.gz)

### Steps to reproduce

1. turn on the lamp in the center of the base
2. attempt to pass any time in view of all the collected items (waiting, crafting, reading, eating, repairing, casting, etc) 
3. go south around the corner and stand on the workbench/hide items from view (but still in crafting range)
4. repeat time passage
5. measure/notice substantial difference

### Expected behavior

i expected many items would slow down performance a bit, but not THIS much. it becomes nearly 1:1 of a 15 minute recipe taking 15 real life minutes to complete. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

something is obviously going wrong because it is ONLY when the items are in line of sight. closing a door (or even just being in the dark/at nighttime) with a thousand items on the other side eliminates the slowdown completely. also, it affects all time passage: waiting/reading/eating/repairing etc, not only crafting, as referenced in #63586

@akrieger

**Comment by BaumgeistOne** [comment]
I cant confirm that in my build (linux); got a whole bunch of errors while loading in, but after ignoring them all, I was able to craft an item taking over an ingame hour in just a few outgame seconds.

**Comment by andrei8l** [comment]
It loads with the out-of-tree version of Sky Islands (https://github.com/TGWeaver/CDDA-Sky-Islands). At a glance, this looks like a duplicate of #62057 and you do indeed have some `MGOAL_FIND_ITEM` missions assigned from EOCs.
![Screenshot from 2024-01-13 15-34-45](https://github.com/CleverRaven/Cataclysm-DDA/assets/68240139/3b90b629-ceb5-497e-8743-2ba17349a5a4)
(drops down to 0.5% at step 4)

**Comment by BaumgeistOne** [comment]
Ok, that explains it - some of the errors were invalidated missions.

**Comment by Hooplah1** [comment]
> It loads with the out-of-tree version of Sky Islands (https://github.com/TGWeaver/CDDA-Sky-Islands). At a glance, this looks like a duplicate of #62057 and you do indeed have some `MGOAL_FIND_ITEM` missions assigned from EOCs. (drops down to 0.5% at step 4)

so if i understand it correctly, go complete the "sticky situation" mission, and itll stop checking every frame for the slime scraps? none of the debug options for that mission are affecting the issue

or, is it because i accepted all 11 skyisland upgrade missions at once, and its checking for all those items every frame?

**Comment by TGWeaver** [comment]
If the "find item" mission code is checking every turn, I can see how having like, ten at a time from the Sky Island upgrade missions would be a real problem. I don't imagine you'd normally ever have that many active missions in normal play, so it probably just hasn't come up in testing until now.
