### ISSUE TITLE
[MoM] Detoxify ability doesn't resolve breathed toxic gas.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70903]
### Describe the bug

A toxic boomer blew up, surrounding me in poison gas, and so I've got the Badly Poisoned (head) effect. But the Detoxification Vitakinetic ability claims that I'm not poisoned and that there's nothing to detoxify.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13929912/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Breath poison gas, see detoxify fail to work.

### Expected behavior

Poisoning being resolved, or if it's not supposed to cure poison gas inhalation, an error message that makes that clear.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/da30f3ae-e4a4-42a9-9d3e-2144f9c6cfb3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Standing-Storm** [comment]
Odd.  Detoxification is set to remove both poison and badpoison, but maybe the general can't apply to the specific (head).
