### ISSUE TITLE
non-space character in display name of clothing items in inventory

### ISSUE THREAD

**Issue by k4gi** [CleverRaven/Cataclysm-DDA#70911]
### Describe the bug

i've been playing with different fonts in my terminal and run into a strange issue.

using the Terminus font in the first screenshot, everything looks normal.

however using Comic Shanns in the second screenshot, the space between clothing health bars and their names appears to be an unknown character, and not a regular old space. what's up with that?

### Attach save file

n/a

### Steps to reproduce

1. set your terminal to use some random font, your mileage may vary with fonts other than Comic Shanns https://github.com/shannpersand/comic-shanns
2. run the game
3. look at clothes in inventory
4. unrecognised character?

### Expected behavior

i was expecting the characters that look like spaces, to be spaces. and therefore to not have this particular issue using random fonts

### Screenshots

![2024-01-14_13-43-05-816018446_cata1](https://github.com/CleverRaven/Cataclysm-DDA/assets/26471575/4324ba8b-65ca-4759-9d30-0eef04dd6014)
![2024-01-14_13-43-05-816018446_cata2](https://github.com/CleverRaven/Cataclysm-DDA/assets/26471575/bda4a636-654c-4c3c-a2d0-a41771f98daf)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.G [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
That is in fact a no-break space. I can't comment on how necessary or supported this actually is by the game, but it's not such an uncommon character that we shouldn't expect it to be supported by a font in my opinion.

https://github.com/CleverRaven/Cataclysm-DDA/blob/1215fbe924fa38c42e1aa336c47d1b9f4ea72d57/src/item.cpp#L9087-L9089

**Comment by kasanryukin** [comment]
This is a non-issue for CDDA; it's a failure of the font you're using not supporting unicode.

**Comment by k4gi** [comment]
ok cool :)
