### ISSUE TITLE
Unable to find and assign mission target farm_isherwood_1

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70913]
### Describe the bug

The trader in the Refugee Center fails to find an Isherwood farm to send me to.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13930301/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Talk to the trader in the Refugee Center and be directed to the farm. Wait several minutes as it fails to find a target.

### Expected behavior

An actual farm.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

 DEBUG    : Unable to find and assign mission target farm_isherwood_1.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 258
 VERSION  : 2a67568

If anyone knows how to fix this in an existing save I'd love to know how.

**Comment by Procyonae** [comment]
It'd be ideal if failing to find a target for quests like this still gave the quest and just waited until you eventually find an acceptable target to make it one. The quest giver can just tell you what kind of thing you're looking for but say they're not sure how to get there from where you are.
