### ISSUE TITLE
Mod pockets delete items

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#70925]
### Describe the bug

I'm trying to get a new type of gunmod working in #70858 and I'm running into an issue - when the gunmod is removed while items are inside of it, the pocket it created on the gun is deleted and the items inside are destroyed with the following error message: 

> "Oops!  deleted some items when updating pockets that were added via toolmods"

I have tried everything I can think of to throw in a hook to empty the pocket when the item is removed, but I can't override the built-in behavior. If anyone who knows the pocket systems better than me can take a look at this, that would be great.

### Attach save file

N/A

### Steps to reproduce

Add the changes from #70858 to your build, compile, see that it all works until you try to remove the gunmod and get the error message.

### Expected behavior

The items should be returned to the player's inventory.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0.G-6446-g9a82599815-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by TheShadowFerret** [comment]
MOLLE pouches are able to be added & removed w/o affecting their contents since #66026 🤔 Would this be able to be copied?

**Comment by fairyarmadillo** [comment]
> MOLLE pouches are able to be added & removed w/o affecting their contents since #66026 🤔 Would this be able to be copied?

I don't think so, because gunmods work differently from MOLLE - instead of placing the item on the gun, it seems to basically delete it and add a new pocket to the gun with its mod data. It also uses an activity_actor function.

Mod pockets also add a new pocket to the gun that isn't tied to a pocket on the mod, so as far as I can tell none of the existing framework is relevant. I've tried testing a few ways to get them to play nice, but it isn't working, so I think I'm stuck.

**Comment by CLIDragon** [comment]
Possibly related to #75565?

**Comment by kevingranade** [comment]
@NetSysFire you confirmed this issue? Please provide reproduction instructions.

**Comment by NetSysFire** [comment]
This has been 6 months ago. I know I did something but not what anymore.

**Comment by kevingranade** [comment]
Ok, we're not keeping a question about an issue that is only triggerable with not-in-the-game content that only exists in a PR that also seems to be abandoned.
