### ISSUE TITLE
[Magiclysm] Elfs are improperly pluralized

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70922]
### Describe the bug

Where there should be feral elves, there are only feral elfs.

### Attach save file

N/A

### Steps to reproduce

Be told that there are 2 feral elfs nearby.

### Expected behavior

Despite their feral nature, they should still respect the vagaries of English grammar.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/68794de3-6f7a-4a4a-818a-c41a9a342c9f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Procyonae** [comment]
On it
