### ISSUE TITLE
house_23 shed has no roof

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#70939]
### Describe the bug

House_23 has a shed with no roof

### Attach save file

Save file: [Apollo-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13932831/Apollo-trimmed.tar.gz)
Non-standard mods: [mods.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13932832/mods.tar.gz)

### Steps to reproduce

1. Load the save file or spawn a house_23 overmap special.
2. Go to the roof.
3. Look at the shed it has no roof.

### Expected behavior

A shed generally has a roof.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/2125926/cba42d7d-8749-440e-911b-37d33526dfde)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 4542f54 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Inglonias Scenarios and Professions [Inglonias_Scenarios]
]

**Comment by HistericalCat** [comment]
I looked into as to why, it appears that the house_23 calls a chunk to spawn in either shed_6x6_junk or shed_6x6_woodworker. Looking at the chunk information for these two, there appears to be no roof for either one, nor does there appear to be any roof for the other shed, shed_6x6_bike. This may be a limitation of chunks, or may be a conscious decision by part of the developers. Hope this helps.

**Comment by Inglonias** [comment]
right. I don't think nested chunks support roofs. If that's the case, we may not be able to fix this without some new code. Damn.
