### ISSUE TITLE
Error on completing camp construction in area with items of the ground

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70959]
### Describe the bug

Error upon finishing construction. Doesn't seem to have caused any issues?

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13934559/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Have full stacks of logs and things on the ground when a construction is complete.

### Expected behavior

No error

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/5c376b6a-4f82-4c17-a90e-8512d5f3b51c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

 DEBUG    : In nested mapgen fbmh_2_center_mideast in update mapgen fbmh_2_center_mideast on faction_base_camp_0, setting terrain to t_floor (from t_dirt) at (12,11) when item log existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

**Comment by PatrikLundell** [comment]
The appropriate change here is to add the flag to keep stuff. The action without any flag present is to issue the error message and keep stuff.
Note, however, that stuff stored where walls appear are deleted regardless of the flag setting. It is, in general, a bad idea to store stuff on construction sites.

**Comment by Rokharn** [comment]
> bad idea to store stuff on construction sites

Not always player have ability to know, where construction appear. 
For example, every time when I build a faction camp at any location, which support modular improvements, I had surprise after mostly any of building task. As result can only solve this problem with save->look->alt+f4->load->prepare->finish task again.

**Comment by PatrikLundell** [comment]
I'm well aware of the problem that there is no way to tell the player where a construction will appear. I've done the best I could with the version 2 ones by clearing out the grass where things will be built, but I'd welcome any better idea.

However, you DO know any construction will be performed within the construction world tile, so you have some indication of where it's a bad idea to store stuff. Far from ideal, yes.

**Comment by Rokharn** [comment]
> I'd welcome any better idea

There is few ways.
Simplest - just a some kind of book with a some kind map, created by ascii art, for example. Not harder, than description of some items, that already have ascii arts.

Harder: some kind of preview after starting task, builded by imaginary construction (something like 'craft place' - construction, that have no conflicts with items on it, but with some visualization. Here conflict with present furniture, so this is harder way ended, but the player can understand what awaits. 
Or as another way of same kind - preview 'constructions' by static 'fog' or something like that, which having no real problems with current furniture and items.


> DO know any construction will be performed within the construction world tile

But I need some safe place to store construction materials for building process anyway. This is decent amount of material to collect for any of this kind of task. 

For example screenshot of player here shows us, that building appear right next to task board, in a place where the player is unlikely to expect it.

**Comment by PatrikLundell** [comment]
Converting the construction into character art is an interesting suggestion, complicated by the mixture of construction instructions (direct placement on a tile, line, square, plus "maps" nested one or more levels deep), and rotation/mirroring. Not something I'm capable of constructing, but an interesting idea.

I've thought about coloring the grass differently, but there are a few issues with that:
- Only the general base camps/expansions are on the ground, and you'd destroy the roof if you tried it inside a building (and some constructions are inside even in a field base camp/expansion setting).
- Aborting the construction would leave this indication behind. Not really catastrophic, as you probably want to do it later, but an issue.

I guess it might be possible to (ab)use the trap framework, but there would have to be a need for tile support, in that case.

The future courtyard of field base camp 2 is suitable for storage of things, as are the world tiles around the camp tile (until you want that space for expansions).
It's true it's not communicated to the player that the areas with the grass removed is intended to indicate the areas where construction is to be performed. I haven't found a good place to mention it (the texts available are rather cramped).
