### ISSUE TITLE
Tacoma commune salt quest error.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70954]
### Describe the bug

Looks like thistles cause an issue when the commune starts growing crops after delivering 300 salt. Looking at the field, the upturned earth did happen as expected, but the thistles are still there.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13934027/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Turn in the 300 salt.

### Expected behavior

No errors.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/8c9c56fc-0210-4967-9d07-611b554a70f6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

 DEBUG    : In nested mapgen tacoma_commune_lumbermill_4 in unknown object in add_mapgen_update_func on ranch_camp_58_east, setting terrain to t_dirt (from t_grass) at (8,2) when furniture was f_thistle.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

and 

 DEBUG    : In nested mapgen tacoma_commune_lumbermill_4 in unknown object in add_mapgen_update_func on ranch_camp_58_east, setting terrain to t_dirt (from t_grass_dead) at (4,3) when furniture was f_thistle.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

and 
 DEBUG    : In nested mapgen tacoma_commune_lumbermill_4 in unknown object in add_mapgen_update_func on ranch_camp_58_east, setting terrain to t_dirt (from t_grass) at (3,7) when furniture was f_thistle.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

**Comment by MrHrulgin** [comment]
Another one of the same sort, with a later quest (turn in 50 pipes):

 DEBUG    : In nested mapgen tacoma_commune_lumbermill_7 in unknown object in add_mapgen_update_func on ranch_camp_58_east, setting terrain to t_conveyor (from t_dirtfloor) at (3,7) when item withered existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

**Comment by MrHrulgin** [comment]
And the next, (2 electric engines)

 DEBUG    : In nested mapgen tacoma_commune_outhouse_8 in unknown object in add_mapgen_update_func on ranch_camp_68_east, setting terrain to t_pit (from t_dirt) at (18,2) when furniture was f_thistle.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

**Comment by MrHrulgin** [comment]
And the next, (150 bleach)

 DEBUG    : In nested mapgen tacoma_commune_clinic_9 in unknown object in add_mapgen_update_func on ranch_camp_59_east, setting terrain to t_wall_half (from t_dirt) at (7,3) when item corpse existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

**Comment by MrHrulgin** [comment]
And another down the chain:

 DEBUG    : In nested mapgen tacoma_commune_junk_shop_12 in unknown object in add_mapgen_update_func on ranch_camp_49_east, setting terrain to t_dirt (from t_grass) at (4,13) when furniture was f_thistle.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding an appropriate clearing flag to the innermost layered mapgen.  Consult the "mapgen flags" section in MAPGEN.md for options.

 FUNCTION : apply
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp
 LINE     : 2966
 VERSION  : 2a67568

**Comment by MrHrulgin** [comment]
At this point, it seems like all of the Tacoma Commune missions that add structures have the same issue. Given that I experienced the same sort of issue with camp building in #70959, perhaps there's something larger regarding structure placement?

**Comment by PatrikLundell** [comment]
A while ago (a bit over a year?) functionality was introduced to either remove "stuff" on top of modified terrain or to remove it. At the same time these error messages were added for the case where "stuff" was detected but no directive on how to handle them was provided.

I would suggest the Tacoma maps should remove items, as it's unlikely the PCs has their stuff there. Base camps and expansions, in contrast, should generally keep stuff, as it's rather annoying to have your loot wiped out by a construction that appears in a "random" place.
