### ISSUE TITLE
Various Itemtype bugs durinng load screen

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#70963]
### Describe the bug

 DEBUG    : itype 'tiharturret' uses undefined flag 'NON-FOULING'. Please add corresponding 'json_flag' entry to json.

 FUNCTION : Item_factory::finalize_post(itype&)::<lambda(const flag_id&)>
 FILE     : src/item_factory.cpp
 LINE     : 735
 VERSION  : b3a8e97

### Attach save file

[Schaumburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13938453/Schaumburg-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. See error messages

### Expected behavior

I have no idea I'm just reporting them all at the same time since it's rare that I get like 10 error messages so I'm trying to divide them so each gets their attention

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: b3a8e97 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Blazemod - Vehicle Additions Pack [blazemod],
    Magiclysm Revamp and Additions [magicrevamp],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by Procyonae** [comment]
This doesn't appear to come from vanilla nor an in repo mod either
