### ISSUE TITLE
[MOD] MagicRevampAdditions bug

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#70962]
### Describe the bug

 DEBUG    : (json-error)
Json error: C:/Cataclsym DDA/dda/userdata/mods/MagicRevampAdditions/worldgen/regional_overlay.json:9:22: <color_white><color_cyan>Invalid or misplaced field name "field_coverage" in JSON data</color>

      "shops": { "magic_shop": 200, "used_bookstore": 225, "magic_academy": 150 }
    },
<color_light_red>    "field_coverage": { "other": { "f_boulder_large": 0.98, "f_glow_boulder": 0.02 } }</color>
                    <color_cyan>▲▲▲</color>
  }
]
</color>

 FUNCTION : void JsonObject::error_skipped_members(const std::vector<long long unsigned int>&) const
 FILE     : src/flexbuffer_json.cpp
 LINE     : 341
 VERSION  : b3a8e97

### Attach save file

[Schaumburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13938455/Schaumburg-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. See error messages

### Expected behavior

I have no idea I'm just reporting them all at the same time since it's rare that I get like 10 error messages so I'm trying to divide them so each gets their attention

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: b3a8e97 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Blazemod - Vehicle Additions Pack [blazemod],
    Magiclysm Revamp and Additions [magicrevamp],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by Procyonae** [comment]
That mod isn't in this repo so idk what you expect us to do
