### ISSUE TITLE
[BUG] Item definitions glitches during world load (posting all of them here)

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#70964]
### Describe the bug

 DEBUG    : vehicle part m4_carbine uses undefined item m4_carbine

 FUNCTION : void vpart_info::check() const
 FILE     : src/veh_type.cpp
 LINE     : 881
 VERSION  : b3a8e97

--------------------------------------------------------------------------------------

 DEBUG    : vehicle part m4_carbine uses undefined item m4_carbine

 FUNCTION : void vpart_info::check() const
 FILE     : src/veh_type.cpp
 LINE     : 881
 VERSION  : b3a8e97

-------------------------------------------------------------------

 DEBUG    : vehicle part m4_carbine uses undefined item m4_carbine

 FUNCTION : void vpart_info::check() const
 FILE     : src/veh_type.cpp
 LINE     : 881
 VERSION  : b3a8e97
-------------------------------------------------------------

 DEBUG    : vehicle part gloopleaisle_aisle is not CARGO and cannot define size

 FUNCTION : void vpart_info::check() const
 FILE     : src/veh_type.cpp
 LINE     : 871
 VERSION  : b3a8e97

### Attach save file

[Schaumburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13938450/Schaumburg-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. See error messages

### Expected behavior

I have no idea I'm just reporting them all at the same time since it's rare that I get like 10 error messages so I'm trying to divide them so each gets their attention

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: b3a8e97 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Blazemod - Vehicle Additions Pack [blazemod],
    Magiclysm Revamp and Additions [magicrevamp],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by KorGgenT** [comment]
this bug is from an out of repo mod
