### ISSUE TITLE
void Item_modifier::modify bug I think during recipes load as I load the game

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#70965]
### Describe the bug

 DEBUG    : in modifier for entry within breaks_into for vpart afs_metal_rig: tried to set ammo for welder which does not have ammo or a magazine

 FUNCTION : void Item_modifier::modify(item&, const std::string&) const
 FILE     : src/item_group.cpp
 LINE     : 586
 VERSION  : b3a8e97

### Attach save file

[Schaumburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13938452/Schaumburg-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. See error messages

### Expected behavior

I have no idea I'm just reporting them all at the same time since it's rare that I get like 10 error messages so I'm trying to divide them so each gets their attention

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: b3a8e97 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Blazemod - Vehicle Additions Pack [blazemod],
    Magiclysm Revamp and Additions [magicrevamp],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by Procyonae** [comment]
This is from Blaze Industries except the version you're using doesn't appear to be the in-repo one as it has a different id and name, so again we can't do much about that. In the in-repo version this vehicle part is migrated correctly

**Comment by KorGgenT** [comment]
this bug is from an out of repo mod
