### ISSUE TITLE
A move away from fighting styles towards mixed martial arts

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#70972]
### Is your feature request related to a problem? Please describe.

Why changes in martial arts are necessary.
1. Most of them are practically useless. Or are of limited use.
2. Studying more than one, provides no benefit.
3. There is a contradiction: martial arts are most useful at the beginning of the game, when they are hard to get. By the end of the game, it's more of a nice addition than something actually needed. And I'm talking about a character focused on close combat. If the character is focused on ranged combat, it's even worse.

### Solution you would like.

The ability to create your own fighting style based on the techniques of the martial arts you have studied.

### Additional context

As is tradition, i apologize for the quality of the text. Deepl translate is used.

Indirectly depends on the following sentences:
- #70969
- #70970

In life, if you know several martial arts, there is nothing stopping you from using techniques from different styles. For example, a stance from boxing and a kick from karate. As long as it's physically possible.

Applied to the game... Let's imagine a style as a thing with many pockets. Multiple pockets for buffs: Static, OnAttack, OnBlock, OnMove, and so on. Multiple pockets for techniques. Some pockets for buffs, may have a nested pocket for techniques.

And so as we learn a style, we get techniques that can be placed in the corresponding pockets. The sum of these pockets will determine the style used.

The way I see it. You need a menu to create a style.
1. Define the direction of the style: style for weapons or style for unarmed combat.
2. Define the type of weapons of the style: swords, staffs, axes and so on. Automatic selection for unarmed combat.
3. Select a specific weapon (all the things I described in #70969 ), for example a hardened steel sword or claws for the unarmed option.

**Note.** Perhaps the 2nd point is superfluous, because by choosing a weapon in the 3rd point, we already determine the type of weapon. But it is necessary to somehow screen out the choice of sword and axe for one style. Limit one style - one weapon? Then we need the ability to copy the style and / or change the weapon in the finished style, without changing the subsequent items.

4. Display available "pockets" into which the player can put the appropriate technique. With filtering by condition:
- learned
- suitable for the purpose of the pocket
- fits the requirements of points 1-3

**Some restrictions.**
I propose to limit the pocket for buffs to one technique. I.e. you can't get two different buffs with the same trigger.
There are 11 pockets in total: Static, OnAttack, OnBlock, OnCrit, OnDodge, OnGetHit, OnHit, OnKill, OnMiss, OnMove, OnPause.

For some triggers, you need nested pockets that define the application of the technique. For example, when OnDodge is received, execute technique_1. In fact, this is a priority setting for the technique. And when dodging, the character will always perform technique_1.

Limitation: the technique must have the OnDodge requirement. For special techniques, a second condition is included: must be of the same combat style.

In addition to these "pockets" for buffs, you need pockets for offensive techniques. Or rather one pocket that can include multiple techniques. Conditionally up to 10 techniques. The peculiarity of this pocket, in the possibility of repeated inclusion of the same technique. Or in the possibility of setting the weight of the technique.

As a result, it is the player who determines the techniques the character uses. If the player enables a single technique, it is always activated, except in the case of triggered techniques.

If the player includes several techniques, each technique has its own weight, depending on the number of included techniques and its repetition (or set weight).

An example of techniques nested in a "pocket": technique_1, technique_1, technique_2.
Then technique_1 is triggered with a 2 in 3 chance.

Ideally, by learning many fighting styles and their techniques, a character is able to create their own fighting style. As an example, a character with a ninja walk, armed with an axe. Which will be enhanced when killed. Or some other combinations.

**Comment by IdleSol** [comment]
>There's nothing stopping you from switching between known martial arts at any time in the game, and I don't think a single one if them is useless.

So the idea is to combine them, not to use them one by one.

**Comment by MrHrulgin** [comment]
> There's nothing stopping you from switching between known martial arts at any time in the game, and I don't think a single one if them is useless.

The thing that's stopping me is the tedium. Are you proposing that the ideal standard is for someone to, in between actions in combat, hit the hotkey to open the martial arts menu and select a new martial art? To do this not just once, but multiple times per combat?

**Comment by fairyarmadillo** [comment]
> > There's nothing stopping you from switching between known martial arts at any time in the game, and I don't think a single one if them is useless.
> 
> The thing that's stopping me is the tedium. Are you proposing that the ideal standard is for someone to, in between actions in combat, hit the hotkey to open the martial arts menu and select a new martial art? To do this not just once, but multiple times per combat?

When applicable. It's two keypresses, requires no setup, and is not something you're doing in between every attack. You flow from one state to another maybe once or twice in a big fight as the situation dictates.

**Comment by kevingranade** [comment]
To get to what you're asking for you need to throw out pretty much all the existing martial arts content and start over from scratch, because every buff, penalty and technique in a given style is balanced against every other buff, penalty and technique in that same style.  If you start mixing and matching techniques every bit of balance goes out the window.

More fundamentally, I don't agree with any of your reasons that a change is necessary. 
Martial arts, especially unarmed ones, are just not that great of a survival technique in the scenario presented by the game, it is intentional that they aren't that effective and that they scale badly as the game progresses.
There isn't enough time in a normal dda playthrough to develop a personal style like you envision.  If you want to roleplay as a highly skilled and experienced fighter,  you can make a custom martial art and add whatever you want to it in json.
