### ISSUE TITLE
Adding randomized pain to the effect of an `required_event": "character_wakes_up"` event EoC crashes the game with no error message

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#70978]
### Describe the bug

As the title. I'm not sure exactly what's wrong because there's no error message.

### Attach save file

N/A--requires modification to reproduce

### Steps to reproduce

1) Add the following JSON to your game somewhere so it loads
`{
    "type": "effect_on_condition",
    "id": "EOC_WAKEUP_KILL_WORLD",
    "eoc_type": "EVENT",
    "required_event": "character_wakes_up",
    "effect": [ { "math": [ "u_pain()", "+=", "rand(35) + 8" ] } ]
}`
2) Start a vanilla CDDA game.
3) Sleep
4) Game silently crashes when you wake up.

### Expected behavior

JSON cannot crash the game, and especially not without an error message.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 40efd24 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

`{ "math": [ "u_pain()", "++" ] }` worked just fine, so it's something about the randomizer that causes the crash.

**Comment by andrei8l** [comment]
/confirmed it crashes if added pain is over the threshold to wake you up
