### ISSUE TITLE
Changing martial style manuals

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#70970]
### Is your feature request related to a problem? Please describe.

There's no problem at all. Just an improvement in gameplay.

### Solution you would like.

Turn martial arts manuals into collections of techniques of the respective style. Actually implement the spellbooks from Magiclysm, only in regards to fighting styles.

Each technique should be studied separately. Each technique should have its own requirements for the time of study and the necessary skills (already in the requirements for use, but not all).

This way, learning the style will be gradual and take more time. An additional plus, it will be possible to regulate the techniques used.

### Additional context

Backgrounds related to martial arts will need to be checked. Specify known techniques from the style and correlate with the corresponding skill.

Conditionally, a black belt knows all the techniques from karate and has melee 5 (or as many as needed to perform any technique). And a white belt, knows one technique (maybe only a stance?) and has melee 1, for the rest of the techniques need to find a guide.

P.S. I apologize for the quality of the text. Deepl translate is used.

**Comment by Vaskritaya** [comment]
I'm not sure this is the ideal way to do it but I agree martial arts manuals need improvement. Going from 0 to total mastery of a style is strange and a relic of older design. 

I feel like the most intuitive way would be to leverage proficiencies somehow. Make MA manuals just contain a practice recipe to train the relevant proficiency. Then, the player's level in the proficiency could determine things like the available skills or the odds of a technique being used.

Perhaps the recent weapon proficiencies would be a good source of inspiration.

**Comment by fairyarmadillo** [comment]
> I'm not sure this is the ideal way to do it but I agree martial arts manuals need improvement. Going from 0 to total mastery of a style is strange and a relic of older design.
> 
> I feel like the most intuitive way would be to leverage proficiencies somehow. Make MA manuals just contain a practice recipe to train the relevant proficiency. Then, the player's level in the proficiency could determine things like the available skills or the odds of a technique being used.
> 
> Perhaps the recent weapon proficiencies would be a good source of inspiration.

Somewhere I posted the idea that reading a martial art manual or finding a teacher should 'unlock' the proficiency, allowing you to switch to that MA and fight in it at little or no benefit except you build proficiency as you do, and unlock moves that way. You could easily do 2-3 tiers per MA. Training with a teacher would also build proficiency, but reading the manual wouldn't.

**Comment by IdleSol** [comment]
>Somewhere I posted the idea that reading a martial art manual or finding a teacher should 'unlock' the proficiency

You can also combine these two options. First you memorize the technique from the manual, then you practice it.

I don't like the fact that it is suggested to put it in "proficiency". It's already too bloated. And it suggests adding multipliers on the effect of the technique, to show the progress of practicing the technique.

+0 damage at 0%, +x% at 100? What about step technique? Or stance? No, it's fun to stand in one place for 8 hours to practice an aikido stance. But it's boring.
