### ISSUE TITLE
[MoM] After extensive meditation on a power I already had, I "unlocked" it and was reset back at level 1

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70980]
### Describe the bug

After extensive meditation on a power I already had, I "unlocked" it and was back at level 1. I had gotten the power up fairly high; no clue what happened to reset it.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13943537/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Just keep meditating.

### Expected behavior

Not resetting to level 1.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/3055b140-d1ae-4a76-8cd5-a92f531595df)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by MrHrulgin** [comment]
I used the debug menu to return Momentum Alteration to level 18, and after a while got a popup notification that told me that I might be able to learn a "new" ability. After a bit, meditating on it again "taught" it to me another time, resetting it again. Perhaps there's some level where it breaks? 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/87abc2ad-63fa-4d1d-bd2d-fc7efa782b13)

**Comment by Standing-Storm** [comment]
Oh dammit I know what happened. 

I'll fix it once my daughter goes to bed.
