### ISSUE TITLE
Camp workshop recipe for flatjaw tongs uses the old, less useful recipe

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70988]
### Describe the bug

There's two ways to make flatjaw tongs, with one of them, using a sand casting mold, added specifically so that it was possible to bootstrap metal tool production. The other one requires flatjaw tongs to make flatjaw tongs. That second recipe is the only one available in the camp workshop 2.

### Attach save file

N/A

### Steps to reproduce

Upgrade a fabrication workshop until you can make flatjaw tongs.

### Expected behavior

I'd expect the recipe to be the one that lets you bootstrap production.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/f3a065d8-4fc9-45a9-94c5-39003b394682)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/e02b35eb-e34f-41e0-a0b3-d9a07ead1406)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment]
The bootstrap process has been broken by changes in recipes (the recipe ladder was tested and worked when the ladder was last updated, which was when tongs were split into forging tongs and cooking tongs), and whoever made the changes apparently did not check where these recipes were used.

**Comment by MrHrulgin** [comment]
I'm sorry, you're absolutely correct. The new tong recipe is at the very bottom of the list, away from all the other tools. Thank you for everything you do to keep this game running.
