### ISSUE TITLE
Paraclesian broke fae ban throws an error due to double definitions / Xedra Evolved

### ISSUE THREAD

**Issue by Noroji** [CleverRaven/Cataclysm-DDA#70993]
### Describe the bug

Game throws an error since last update on experimental with Xedra Evolved active about a double definition.

It seems to be defined in:
1. "paraclesian_eocs.json"
2. "paraclesian_fae_bans.json"

### Attach save file

Happens even with only DDA and XE active, so not needed?

### Steps to reproduce

Activate XE and try to load/create a character.

### Expected behavior

Game loads.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/20514078/21e990d9-e896-4173-ba00-7bb9a5cf0673)

### Versions and configuration

Cannot generate one for that specific problem, as I don't get in game without meddling. 

### Additional context

Game starts if one of the two definitions are removed.

**Comment by Rokharn** [comment]
Same issue. 

Starting [from](https://github.com/CleverRaven/Cataclysm-DDA/pull/70961)

**Comment by Standing-Storm** [comment]
Weird that the tests didn't catch that.

#70979 will fix it.
