### ISSUE TITLE
Accessibility toggle to place map notes on new areas revealed by maps

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#70991]
### Is your feature request related to a problem? Please describe.

As of #70482, reading a map now highlights the particular map tiles freshly revealed by said map, which is an excellent addition and got me thinking that something similar might be added for the benefit of blind and visually impaired players. Currently, there is no realistic way for a blind player to know what a map has unveiled, as they do not have the capability to quickly browse over the map view and visually pick out something that stands out. rather, blind players (speaking for myself) use a mental checklist and search for stuff with the filter option, which obviously means that, bar knowing exactly what a given map, guide, point of interest indicator, whatever, will show, a blind player has no means of knowing what to search for and thus cannot be benefited by using a map.

### Solution you would like.

I would suggest creating an accessibility toggle to enable the showing of map notes on newly discovered areas, which would behave the same as the current map notes and place an appropriate message on the new tile in question. This would allow blind players to just jump into the map notes listing and brows through for anything marked as “newly revealed by map,” thus making in-game maps something one can use without running to the json files to see what a given piece of paper is meant to be showing them.

### Describe alternatives you have considered.

Nothing of note really comes to mind; this seems to, based on my sample size observation of one entire human being, to be the optimal solution.

**Comment by ZhilkinSerg** [comment]
Using map notes for all revealed tiles would be unusable. Imagine a map revealed a straight road that spans across the whole overmap (180 tiles) - that's 180 map notes.

**Comment by DoctorBoomstick** [comment]
Uh, I see I misunderstood how the highlight feature works. I was under the impression that it only pointed out the particular tile that got shown, rather than all the other tiles leading towards it. In that case, I agree that adding a feature for all of that would be horrendous. I maintain, however, that one map note being placed on the POI would be ideal.
