### ISSUE TITLE
NPC camp loggers bring back water

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71007]
### Describe the bug

When a logger returns, among the items teleported to the center of the camp are puddles of liquid. With a fully built camp center, you get a popup letting you know there's nowhere for it to go.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13956613/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Have puddles of liquid in a forest, send a logger. 

### Expected behavior

No random puddles of liquid being brought along with the wood.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/c8da2863-1bf5-44cf-a27c-4f435d8f8a8c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment]
I can confirm the part about bringing puddles home, as that's been the case for a fair while (quite possibly since puddles were introduced). The asking what to do with the water is new, however. I don't think you should be able to bring water back in your pockets, however.

At a guess, the code that selects items to bring back should probably exclude liquids.
