### ISSUE TITLE
"condition": "u_is_outside" as an enchantment condition in a mutation crashes the game

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71006]
### Describe the bug

Attempting to use `"condition": "u_is_outside"` as a condition for an enchantment in a mutation will immediately crash the game if the mutation is selected. Loading or start a game shows no errors relating to the mutation.

### Attach save file

N/A--requires modification to reproduce

### Steps to reproduce

1) Place the following JSON somewhere in your game so it loads: `  {
    "type": "mutation",
    "id": "LETSCRASHTHEGAME",
    "name": { "str": "The Game Crashing Mutation" },
    "points": 4,
    "visibility": 0,
    "ugliness": 0,
    "description": "Crashes the game.",
    "enchantments": [ { "condition": "u_is_outside", "values": [ { "value": "MOVE_COST", "multiply": -0.1 } ] } ],
    "category": [ "BEAST" ]
  }`
2) Using the debug menu, mutate The Game Crashing Mutation
3) The game crashes

`{  "not": "u_is_outside" }` also causes a crash. `"is_day"` causes no problems.

### Expected behavior

Game does not crash, or at least shows an error message with what is incorrect about the mutation

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 46765f2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13956328/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13956329/crash.log)

**Comment by andrei8l** [comment]
/confirmed `talker` split strikes again

```diff
diff --git a/src/condition.cpp b/src/condition.cpp
index ea2d262c30..0d79fc33c5 100644
--- a/src/condition.cpp
+++ b/src/condition.cpp
@@ -1455,7 +1455,7 @@ void conditional_t::set_is_day()
 void conditional_t::set_is_outside( bool is_npc )
 {
     condition = [is_npc]( dialogue const & d ) {
-        return is_creature_outside( *d.actor( is_npc )->get_creature() );
+        return is_creature_outside( *static_cast<talker const *>( d.actor( is_npc ) )->get_creature() );
     };
 }
 
```
