### ISSUE TITLE
Crator in city building throws error

### ISSUE THREAD

**Issue by Luca-spopo** [CleverRaven/Cataclysm-DDA#71002]
### Describe the bug

On the overmap, I can see that a crator spawned inside a city.
when I walk towards it, the game throws this error.

The crator causing this issue is a (reasonable) assumption by me

 DEBUG    : Setting terrain t_hole at (5,28,0) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : bool map::ter_set(const tripoint &, const ter_id &, bool)
 FILE     : src/map.cpp
 LINE     : 2058
 VERSION  : d6ec466

### Attach save file

[Jan24 Rebalanced1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13954721/Jan24.Rebalanced1-trimmed.tar.gz)

### Steps to reproduce

At this point in the save file, the issue has already happened. It happened the moment I stepped on the current tile (I was one tile to the right before this)

### Expected behavior

Either crators should not be created in cities,
Or, crators in cities should automatically delete the furniture/etc in the spot

### Versions and configuration

0.G stable

**Comment by PatrikLundell** [comment]
This is a harmless error (i.e. a report only, but no bad side effects), and it's well known. Despite that, it hasn't been addressed.

By the way, it's spelled "cratEr" (might be useful in the future).

**Comment by Procyonae** [comment]
> Despite that, it hasn't been addressed.

I mean this one isn't as easy as just adding the flag to a nest afaik bc the map extra just places a bomb and the explosion is hardcoded
