### ISSUE TITLE
Commune doctor anesthetic quest bug

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71013]
### Describe the bug

The doctor for the commune has a quest that sends you to build an anesthetic machine and bring 3000 units of anesthetic. If you go to the scrapper boss he'll build you the machine in exchange for some tools, but if you go back to the doctor having done so and with 3k anesthetic on you, he won't recognize that you're ready to complete the quest. If you talk to other members of the commune, they still point you towards the scrapper chief, so I suspect the issue is with that part of the quest.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13959595/Bellaire-trimmed.tar.gz)

### Steps to reproduce

1. Accept the quest from the doctor.
2. Complete the subquest with the scrapper chief.
3. Bring 3k anesthetic to the doctor.
4. Fail to profit.

### Expected behavior

Be able to turn in the quest.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/cad4026a-ac65-4831-87cc-25335e5bceeb)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/d29958eb-7028-460c-a244-9d464368b2f7)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by grzegorgf** [comment]
FYI I encountered this issue post-fix as well, the reason turned out to be recalling the follower after completing the task from scavanger via the faction interface. Recalling through conversation triggers the completion and allows the quest to proceed. If you get stuck, change the "npctalk_var_mission_tacoma_ranch_scavenger_hospital_raid" and "npctalk_var_mission_tacoma_ranch_scavenger_hospital_raid_started" to "no" in the .sav and restart the task.
