### ISSUE TITLE
Vehicles being dragged makes impossible moves.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71029]
### Describe the bug

IRL, If I grab the rear bumper of a car and pull, the car will roll towards me, with perhaps some wobbliness due to the uncontrolled front wheels. In game, if you grab the rear of a car and pull, it'll try to entirely swap the car's direction so that the "front" of it is in the direction you're pulling. This can entirely teleport the car to the other side of you. In the save, [G]rab the bumper of the car to your right, and try to move left. The car will entirely pop to the other side, causing you to stumble and release it. This was the easiest to set up for display, but there's a number of other weirdnesses possible when dragging cars around, including all position-dependent vehicle tiles getting scrambled.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13972126/Bellaire-trimmed.tar.gz)

### Steps to reproduce

[G]rab the bumper of the car to your right, and try to move left. The car will entirely pop to the other side, causing you to stumble and release it.

### Expected behavior

The car would roll towards you as you pull it.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/cb75b39a-164b-442e-bd83-fae21cf27a4a)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/752b1849-f6fb-410f-bb65-8ec3d036a9b6)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/a6bfa84e-fb47-475e-b857-312362e20cb5)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment]
I've encountered this kind of issue when pulling wreckage parts, often causing illogical collisions. I've also accidentally done it with my own vehicle.
I'm unsure if these things should be considered to be confirmations, which is why I haven't confirmed it.
