### ISSUE TITLE
Add a QoL setting to take gloves off before crafting

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71049]
### Is your feature request related to a problem? Please describe.

In CDDA, I often try to keep my character alive by wearing armor, but there is a tradeoff between protection and encumbrance. This tradeoff is good for balance and player agency, but I sometimes get annoyed at the crafting penalty from wearing encumbering gloves. I can manually get around this by taking the gloves off before crafting, then putting them back on afterwards. After some thought, I realized this is the same thing I do in real life when I need extra dexterity for a task when I'm already wearing gloves. 

### Solution you would like.

I would like to suggest an additional quality of life (QoL) setting to solve this problem. 
1. **Never take gloves off when crafting**. -- This is the same as the current behavior. 
2. **Take gloves off when crafting if it is smart to do so**. -- This option sounds clever, but I realize it requires several checks to work. I've included a flowchart below. 

One of the difficulties of this idea is what counts as a "glove". 
Is something a glove if it covers the hand and nothing else? -- If this is our definition, then long gloves get excluded. 
Is something a glove if it covers the hand? -- If this is our definition, then hazmat suits count as "gloves". 

### Additional context

Here's a flowchart I thought of for the checks, made with code2flow.com. 
![Screenshot (299)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/77e6b86e-3ec9-490e-aff2-7cd2548dcaa4)

holli1433 and karol1223 from discord came up with some ideas too. 
![Screenshot (300)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/b6685da1-0ace-4737-a200-c75f3dde3319)

**Comment by GuardianDll** [comment]
Previous attempt, that went into wrong direction and was rejected, is #66224

**Comment by DragonWizard23** [comment]
@GuardianDll Thank you for mentioning that here. Here are my takeaways from that conversation:
- Adding additional checks to ensure the character can safely craft without gloves is helpful, but it should rely **on the data available to the character**. As an example, if the player has a way of measuring radiation, a radiation safety check is good, but if the player doesn't have a way of detecting radiation, the radiation safety check shouldn't run. 
- If the character is interrupted mid-craft, the gloves shouldn't be magically put back on (because the character had already taken the gloves off for crafting and was later unexpectedly interrupted). However, if *the player* decides to interrupt the craft, the gloves should be put back on. The time it takes to put the gloves back on after the player decides to interrupt a craft needs to be accounted for. 
- It would be a good idea to print a message to the log when the character automatically puts on or takes off gloves. That way, the player knows whether the character was wearing gloves for the craft and if the gloves were put back on (if the crafting was interrupted).

**Comment by Brambor** [comment]
Why not give a query:
`Take gloves off for crafting? (Will be put back on, once crafting concludes). (Y / N)`
This avoids cases unforeseen by the programmer.

**Comment by DragonWizard23** [comment]
> Why not give a query: `Take gloves off for crafting? (Will be put back on, once crafting concludes). (Y / N)` This avoids cases unforeseen by the programmer.

I really like the simplicity of this idea. My only concern is that it could get repetitive for the player.

**Comment by Rokharn** [comment]
Is that really so big deal to take off gloves manualy? 

You are miss wet status as well (water proof gloves and rain, for example). Acid maybe. Some crafts require tools like equipment, so at this logic player needs to put on this things (like welding glass, some kinds of laboratory aprons and so on) as well. Most of this things slow down craft. This is Pandora box literally.

**Comment by DragonWizard23** [comment]
@Rokharn Thanks for the feedback. 
> If not check if player will get frostbit at craft time, than playing some mods with extreme temperature like Aftershock can be very dangerous. Same for extreme high temperatures and items with fire immune, which possible.

I think my explanation in my flowchart was lacking, so let me try to explain the cold temperature check I had in mind. Instead of trying to do a time-weighted predicted temperature average for the expected duration of the craft, I figured it would be easier to check if the character's hands would (not) be at a comfortable temperature without the gloves, at the time crafting begins. As far as I know, you can't get frostbite on a limb when that limb is at a comfortable temperature (green on the @ menu). 
You raise a good point about a fire safety check--I think this sounds reasonable. 
> Needs check if gloves a part of costume as well

Yep, that needs to be taken into consideration. That's what I meant when I was discussing what counts as a "glove". :)

**Comment by ANickelN** [comment]
The aforementioned query could work with a setting in the options to manage at what % hit to speed the player should be prompted.
For example: "Query remove gloves when below 90% workspeed"
I think that is a lot more likely to get merged than to try and account for every "what-if" scenario.

**Comment by Cenness** [comment]
Or just write a trivial autohotkey/shortcuts/automateit script? Yes, it would work only where those tools are available.
First - use marker to add unique label to the gloves

in script:
```
  bind to keybind for unequip:
    press T
    press /
    print unique string
    press enter twice

  bind to keybind for equip:
    press W
    press /
    print unique string
    press enter twice
```

**Comment by Brambor** [comment]
The biggest benefit I see in this is the reminder that I have gloves on when attempting to craft. In my base I can easily get to 100% crafting speed. When I am not at that, I **forgot** something.

I would like a reminder for all crafting and reading debufs, so the moment the sun starts going down, I lit a lamp. If I am one tile further from lamp than I should be, I would like to get reminded.

I didn't play the game for a while though.
