### ISSUE TITLE
Very large characters have excessive difficulty using vehicles

### ISSUE THREAD

**Issue by KnifeFightBears** [CleverRaven/Cataclysm-DDA#71042]
### Describe the bug

Very large characters (using the new trait) seem to take a cramped debuff when driving any vehicle. This makes sense in a regular car, it doesn't make a lot of sense in a big rig truck or a huge boat. When cramped, they will repeatedly take damage when driving. This interrupts auto-drive, and makes driving with weak limbs dangerous. I haven't tried every variety of chair yet to see if there's some combo that doesn't cause this, but it seems to be pretty universal across all vehicles. 

Very small cars and excavators seem to be completely unusable by very large characters in-game, even in cases where that wouldn't make sense in real life. I'm sure you'd have a really hard time fitting Shaq into a city car, but he _should_ be able to operate an excavator without an issue.

Spaces within cars become untraversable to very large characters very quickly, the game doesn't seem to make any allowances for storage space in chairs. Considering there is a lot of space below seat cushions and most cars have seat-backs, you would think you would be able to store things in a seat without it making it impossible for Shaq to traverse the car.

### Attach save file

N/A - this impacts all large characters interacting with all vehicles from character creation onward

### Steps to reproduce

1. Make a large character in a recent experimental version using the Very Large trait
2. Interact with any vehicle

### Expected behavior

Very large characters should be able to interact with vehicles in a more realistic way. Cars in real life do not become untraversable to large people because you stuck a magazine in the seat back. Large people can operate excavators. Large people do not have to worry about their limbs breaking when they are normally driving down the road. Large people can comfortably operate large vehicles.

### Versions and configuration

Cataclysm-DDA experimental build 2024-01-14-0248 on Windows 11-x64

**Comment by KnifeFightBears** [comment]
Thanks, I appreciate the attention to this. I think I just got hung up on the hurt nag messages that seem to come up when you're cramped, they interrupt auto-travel and at least give the impression that you are taking damage even if you aren't actually taking damage. 

I was able to fit my Shaq into an excavator by replacing the seat with a reclining seat! Thank you for the advice. Maybe it would be more appropriate for excavators and tractors to have a different kind of seat to begin with than other vehicles? Industrial vehicles often have special adjustable seats:

https://www.google.com/search?q=excavator+seats

**Comment by fairyarmadillo** [comment]
I wish it wouldn't interrupt auto-driving. Maybe there's a way around that.

Also yeah probably most vehicles should have adjustable seats, and maybe the bonus allowance for open-topped vehicles should be raised so that Shaq can be comfortable in a convertible with a reclining seat. That's what he drives IRL mostly.
