### ISSUE TITLE
Small Mutant NPC Faction Proposal

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71051]
### Is your feature request related to a problem? Please describe.

There has always been a problem onboarding people with the mutation system. It's an age-old issue where the mutations logically would be locked in what amounts to an endgame dungeon or three, and once players have cleaned it out and gained the 7-8 applied science and proficiencies needed to craft the stuff, they don't have anything left to do in the game.

The game also doesn't really suggest a logical reason to dose yourself, except that it offers gameplay benefits.

### Solution you would like.

I've got a sketch of a small faction drafted up. This would be a group of two or three test subjects and possibly a now-mutated lab assistant (like, so mutated they barely remember their own name, and thus won't be able to provide much more insight about the organization than the snippets already do) who escaped from a XEDRA lab in the chaos of the cataclysm, and are now hiding out together somewhere. They have decided that since the world's gone to hell, they can use their new abilities to try to survive, and are willing to shelter any mutants who would be unwelcome in other settlements.

Because of their origin, they have access to a small amount of mutagen and some basic knowledge of how it is meant to be used. If the player finds them and is sympathetic to their cause, they will be given a bit of mutagen and instructed to dose themselves with it as an initiation rite. If they comply, they get brought into the fold and can help the faction learn more about what they are. We could even have them provide some limited help crafting the stuff or sourcing recipes, though the intent is still very much that the player will need to go to labs if they really want to get into the system. Maybe once you get a few mutations they send you to a lab, and if you bring back some goodies they can help you figure out what to do with them. Nothing an experienced player would need, but breadcrumbs for newbies.

If the player chooses not to become a mutant, they will still be able to direct mutant NPCs they meet to join the group, or potentially have other interactions with them. If the player would rather not interact with this group, or can't find them, then nothing changes. They are still able to do go into labs and get mutagen and recipes as normal.

Other than simply providing the player with the means to mutate and a reason for their character to consider the idea, the group would also be a chance to show how different mutants behave. Dr. Brundle didn't turn into a guy with fly wings, his entire personality changed as the foreign tissue took over his brain. His change in personality was a big part of the body horror, and illustrating how people deal with that in different ways could be fun.

The overall theme of the faction is nasty, insular outcasts who genuinely care about other mutants, but are extremely lacking in human politeness. I envision their leader as maybe like a death row convict who was mutated against his will, but has found a calling in what he's doing and is deeply committed to protecting his people, who may or may not be as rough as he is but are willing to fall in line.

### Describe alternatives you have considered.

I considered just throwing a PR together, but I'd rather get this greenlit (or not) first, to save myself doing unnecessary work. I'm not ready to get started immediately as I still have a couple big projects going, but since mutations are the thing people are talking about now, I wanted to bring this up.

**Comment by fairyarmadillo** [comment]
@carlarctg this would solve your issue in #71048

**Comment by carlarctg** [comment]
I am a big fan of a concept like this! It would HELP with a lot of concerns, but it wouldn't solve them. This is a sandbox game and just one route towards the 'no midgame mutations' reliant on being lucky enough to find these friends isn't enough. Not to dismiss your work, far, far from it. I love this concept.
I am noting how your concept is more lab-oriented than mine was. Do you have an interest in keeping mutations mostly lab-locked, without pretty much any other way to generate them? If so, why? I don't think it helps if mutations are only found in labs. CBMs for example can (are planned to) be found with Hub 01 as well.

**Comment by fairyarmadillo** [comment]
I don't have the power to change the lore, and the lore says that mutagens came from labs, were never or almost never sent outside of them, and that's where they're going to stay. Any attempts to change that would be far out of scope for this group, who mostly exist to introduce you to the process and help tutorialize it somewhat.

**Comment by fairyarmadillo** [comment]
> I didn't say mutagen, I said mutations. 

Alright, well, none of that is relevant to this proposal. These guys deal with mutagen, so let's not bikeshed here.

**Comment by I-am-Erk** [comment]
I've had ideas for something like this for a while. I'll read your full writeup soon but after a skim some thoughts: I think the interplay between this faction, the free merchants, and the raiders would be interesting and I think this could easily be a fun 'in' to viewing the free merchants as a more negative group and seeing some of the better aspects of the raiders. This group probably needs outside help from a larger faction and in our current game setup, the raiders are the most likely ones to be willing to help them.

**Comment by ashGlaw** [comment]
I think we're definitely overdue for a mutant faction. I like your ideas. I like your suggestions, too, Erk. I think this would be a fine addition to the game. 👍

**Comment by KittyTac** [comment]
As a fan of mutants I'd love this! Both because I am a weirdo, and because, ngl, the system is super confusing for new players so signposting it would be good.

I'd be glad to help with this @fairyarmadillo !

**Comment by PGR-14** [comment]
Quick question about the reward, will we be able to choose the mutagen? Perhaps give the player a list of them (Excluding Raptor, Alpha, & Fey, 'cause those are canonically hard to make in the labs (I think)).

**Comment by fairyarmadillo** [comment]
Yeah that's more or less the plan. I hadn't thought of how this creates RP justification for samples though, that's a good point.
