### ISSUE TITLE
error during JSON loading in tests results in error spam due to trying to save test world

### ISSUE THREAD

**Issue by ehughsbaird** [CleverRaven/Cataclysm-DDA#71050]
### Describe the bug

The following results in a JSON error 

`Json error: data/json/snippets/snippets.json:399:14: missing mandatory member "text"`

```diff
diff --git a/data/json/snippets/snippets.json b/data/json/snippets/snippets.json
index a20564e0c4..d385b758c5 100644
--- a/data/json/snippets/snippets.json
+++ b/data/json/snippets/snippets.json
@@ -393,6 +393,11 @@
       }
     ]
   },
+  {
+    "type": "snippet",
+    "category": "<punc>",
+    "text": [ { "a": null } ]
+  },
   { 
     "type": "snippet",
     "category": "pyromania_withdrawal",
```

But I cannot see it because the test log is filled with
```
ERROR : src/map.cpp:8013 [void map::saven(const tripoint &)] Tried to save submap node (0) but it's not loaded
...
ERROR : src/map.cpp:8013 [void map::saven(const tripoint &)] Tried to save submap node (2540) but it's not loaded
```

### Attach save file

N/A

### Steps to reproduce

1. Apply the diff above.
2. Run `tests/cata_test` (no arguments)

### Expected behavior

I am shown the JSON error, and no attempt is made to save the test world.

### Versions and configuration

On f2c8c58036e1a48099055586e77fe175e9f4cca4, Ubuntu Linux 22.04

**Comment by ehughsbaird** [comment]
08e48390667ce71d53d9df29d478e5dfb18ff88d is the first bad commit

**Comment by SurFlurer** [comment]
I can /confirm this is happening.
