### ISSUE TITLE
Unable to generate a valid starting location Nuclear Power Plant

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71057]
### Describe the bug

Unable to generate a valid starting location Nuclear Power Plant in a radius of 3 overmaps, and I'm reporting this failure.

### Attach save file

N/A

### Steps to reproduce

Try to start at a Nuclear Power Plant

### Expected behavior

Generate a starting location.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/d5ada7da-750a-46e8-b3cf-00b46ab1e296)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 50349bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Procyonae** [comment]
It'd make some sense for chosen starting locations to be able to influence #67723 ig

**Comment by MrHrulgin** [comment]
If it's just a big fussy special that requires trying a few times, why not just have it silently retry, and remove the message that specifically asks for it to be reported?

**Comment by Procyonae** [comment]
That's a general message for any start location that fails to spawn, as far as it knows it could be completely impossible and put you in an infinite loading screen

**Comment by MrHrulgin** [comment]
Ok. Well. I'm out of solutions, but I've reported the issue, as requested.
