### ISSUE TITLE
Display item variants grouped together to reduce clutter. I don't need 45 different flavors of gum.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71066]
### Is your feature request related to a problem? Please describe.

With an increasing variety of items that have flavor names, it's becoming harder and harder to actually manage looting and inventory. While on some conceptual level I can appreciate that there's both hibiscus and mixed-berry chewing gum in the world, but when I'm trying to loot, having a quarter of a page of the AIM be filled with chewing gum flavors makes it harder to actually review and loot what I truly want. 

I'm sure that there are some people who truly want all that detail, and so what I'm thinking about is a mod that hides all that flavorful variation and just shows me "gum". 

I don't need peppermint chewing gum, spearmint chewing gum, wintergreen chewing gum, cinnamon chewing gum, bubblegum chewing gum, mixed-berry chewing gum, strawberry chewing gum, cherry chewing gum, grape chewing gum, orange chewing gum, watermelon chewing gum, blueberry chewing gum, cranberry chewing gum, pineapple chewing gum, green apple chewing gum, apple chewing gum, mango chewing gum, mint chocolate chip chewing gum, vanilla chewing gum, coconut chewing gum, lemonade chewing gum, honey chewing gum, sour apple chewing gum, pomegranate chewing gum, raspberry chewing gum, kiwi chewing gum, peach chewing gum, passion fruit chewing gum, tangerine chewing gum, grapefruit chewing gum, blackberry chewing gum, lime chewing gum, peach mango chewing gum, limeade chewing gum, strawberry lemonade chewing gum, wasabi chewing gum, hibiscus chewing gum, lavender chewing gum, bacon chewing gum, whiskey chewing gum, saffron chewing gum, green tea chewing gum, anise chewing gum, pink peppercorn chewing gum, and cardamom chewing gum.

I just want gum.

### Solution you would like.

An option/mod to hide all of the alternate names for items.

### Describe alternatives you have considered.

Depending more and more on automatic pickup rules and zone sorting so that I don't have to actually look at a pile of unsorted loot.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/15b904ef-e1a6-4dae-bc25-aba73ac9e931)

**Comment by MrHrulgin** [comment]
I'd be happy for it to be mainline, I just didn't want to assume that my preference for all of this distinctiveness to be hidden was as widespread as it apparently is.

**Comment by ehughsbaird** [comment]
This is doable with an option, very similar to https://github.com/CleverRaven/Cataclysm-DDA/pull/70968
Just change the below it to return the value of the option.
https://github.com/CleverRaven/Cataclysm-DDA/blob/6324dc05956346fa371746c7146ab603b8f09fd2/src/item.cpp#L9397

**Comment by XygenSS** [comment]
Even clothes have a ton of color variants now. Bloat is a very real issue.

**Comment by andrei8l** [comment]
> This would be better in mainline. Like items could collapse into a single "pocket" or something that stores all the variants inside of it.

This is already a thing for inventory_ui, it just needs to be enabled in the presets if the perf. impact is considered acceptable. Currently it's only enabled for eat, activate, and reload UIs.

<details>
<summary>Example after flipping the bool for inventory's preset</summary>

![Screenshot from 2024-01-22 00-40-21](https://github.com/CleverRaven/Cataclysm-DDA/assets/68240139/27da3533-6d98-4736-b97e-bba84a26726b)

</details>

**Comment by Uwuewsky** [comment]
Adding fifty types of chewing gum instead of just one, and then putting it all in one abstract pocket definitely sounds like overengineering.

**Comment by fairyarmadillo** [comment]
> > This would be better in mainline. Like items could collapse into a single "pocket" or something that stores all the variants inside of it.
> 
> This is already a thing for inventory_ui, it just needs to be enabled in the presets if the perf. impact is considered acceptable. Currently it's only enabled for eat, activate, and reload UIs.
> 
> Example after flipping the bool for inventory's preset

I'd prefer not to see the variant name for the top item, and this makes it seem like the gum is all inside of the first one. So this is an improvement, but I'd prefer to just see "chewing gum x 50" or whatever.

**Comment by XygenSS** [comment]
Gums could function similar to newspaper pages or flyers, where they do stack but also vary in the descriptions, so if you want to consolidate all your gums into one stack of 50 it automatically does that upon pickup but if you find discreet gum you can check the description to see what flavor it is (and it is recorded in the lore tab).

**Comment by fairyarmadillo** [comment]
While we're at it, the weights on the gum variants are way off. @The-Anjelo-Guy I don't want to dissuade you from adding variants, but the weight on the variants should reflect the distribution of these items IRL. 80% of gum in the US is some kind of mint flavored, and probably 15% is bubblegum flavored, and then you have like 4% cinnamon and all other flavors would occupy that 1% left over. I see you're doing other variants, so please consider this as you go forward.

**Comment by The-Anjelo-Guy** [comment]
> While we're at it, the weights on the gum variants are way off. @The-Anjelo-Guy I don't want to dissuade you from adding variants, but the weight on the variants should reflect the distribution of these items IRL. 80% of gum in the US is some kind of mint flavored, and probably 15% is bubblegum flavored, and then you have like 4% cinnamon and all other flavors would occupy that 1% left over. I see you're doing other variants, so please consider this as you go forward.

Mint and other common flavors - 60 to 20
Uncommon flavors - 20 to 10
Rare flavors - 10 to 1. Don't know nothing about this. If chewing gum flavors is becoming that much of an issue, I'd be more than happy to exclude them all and return to the standard, boring chewing gum item.

**Comment by fairyarmadillo** [comment]
It's a lot of clutter, it's creating UI issues, and it doesn't reflect the real life distribution of these items. Perhaps we should hold off adding more until the problem is fixed.

**Comment by MrHrulgin** [comment]
The gum was the straw that broke the camel's back, so to speak, but it's not just about the gum at the end of the day. It's a difference of opinion regarding the level of flavor in items that's ideal. An option to hide it lets both the flavor-wanters and the item-simplifiers have the experience they want.

**Comment by fairyarmadillo** [comment]
The flavor is a good thing, I'd just prefer to be able to access it through a way other than virtual pockets or inventory spam.
