### ISSUE TITLE
Portal storm crashes the game / Segmentation fault

### ISSUE THREAD

**Issue by Noroji** [CleverRaven/Cataclysm-DDA#71079]
### Describe the bug

Was outside in a portal storm, talking with the nice voice on the other side.  

Game crashed in the dialog as I was about to stop talking with it, restarted and reloaded the last save. Since then the game crashes after a short time of playing, usually some in game minutes. Sometimes I can move around, sometimes I can speak to the voice again for a bit, but after a short time it always ends up crashing again. Waiting inside a basement also crashes. 

### Attach save file

[Meadville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13987698/Meadville-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Wait a bit or go out and take a stroll with my broadsword
3. Games crashes

### Expected behavior

Portal Storms are dangerous, but the level of danger should not be coming through the game into the real world and hamper me from playing. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 3ff9e99 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Sly's Skill Antirust [slysskillantirust],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Extra Mutated Scenarios [extra_mut_scens],
    <color_light_green>Cataclysm++</color> [Cata++],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Kills [stats_through_kills],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Blaze Industries [blazeindustries],
    Make bows great again [bow_opness],
    Xedra Evolved [xedra_evolved],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Magiclysm Revamp and Additions [magicrevamp],
    No Fungal Monsters [No_Fungi],
    Mutation Selector [mutation_selector],
    Mind Over Matter [mindovermatter],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Different sized rings for Mutations [Rings_For_Mag_Mut],
    Dreamforged Fire Axe for the halligan bar [Xedra_Fire_Axe],
    Aftershock [aftershock],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    Targeted Mutagens [targetedmutagens]
]

### Additional context

Also made a backup and removed most mods that aren't bundled with the game. Loads of errors of course, but same behaviour that it crashed after walking a bit in the storm or waiting in my basement.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13987752/crash.log)

**Comment by andrei8l** [comment]
/confirmed introduced by #71019

`target_monsters` can be empty here
https://github.com/CleverRaven/Cataclysm-DDA/blob/3ff9e997ba8e2edda10b49d09c7fc45b2add59da/src/npctalk.cpp#L5787

and probably also in the identical code below

@Procyonae

**Comment by Procyonae** [comment]
> Portal Storms are dangerous, but the level of danger should not be coming through the game into the real world and hamper me from playing.

Skill issue smh
