### ISSUE TITLE
Concrete sacks spawns with 1 concrete only

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#71086]
### Describe the bug

Sacks with concrete are spawning with just 1 unit of it while others like cement or sand are spawning full

### Attach save file

[Town West-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13993889/Town.West-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Teleport to nearby hardware store or construction site

### Expected behavior

They should spawn full if unopened

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: f63af40 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by MrHrulgin** [comment]
I've seen this as well.

**Comment by KeremBabaG** [comment]
lemme look into it

**Comment by Torres84f** [comment]
> lemme look into it

Thanks I just don't understand how concrete has such size since it can only fit like 8 per sack, I understand is the mix of cement+sand+gravel-like aggregate but just one per sack seems a bug.

Maybe lower the weight enough to get 10 per sack as if it were some sort of "quickcrete" ready to mix just with water and that should make enough sense I guess
