### ISSUE TITLE
Bug while trying to build a vehicle

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#71080]
### Describe the bug

I try to build a vehicle of any kind and get this message

 DEBUG    : constructing failed: components size expected 1 actual 4

 FUNCTION : done_vehicle
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\construction.cpp
 LINE     : 1442
 VERSION  : 3ff9e99

### Attach save file

[Town West-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13988074/Town.West-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Hit construction menu try and build a vehicle
3. Get error message and nothing spawns

### Expected behavior

Can't say what to write here

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 3ff9e99 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by Procyonae** [comment]
/confirm I'm kind of amazed I've never seen this before it seems to just dislike that you have more than 1 potential component available, can't handle it and so just eats 1 of everything and fails???

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/8c522b9e-e35c-4c8a-b8b5-401edf9b1385)
After doing it a few times the number of components available drops to 3 and so does the error
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/c6bf62e9-adcc-441e-a845-c97ac90b721b)
so I think that's the cause. It should just need a way to select which you want to use but idk how simple that is given this construction is kinda unique

**Comment by Procyonae** [comment]
At the same time regular constructions don't let you choose between optional components either they just take any without asking

**Comment by KeremBabaG** [comment]
Man what the hell is that code lmao

**Comment by irwiss** [comment]
Can't reproduce, I'm guessing https://github.com/CleverRaven/Cataclysm-DDA/pull/72201 fixed this

**Comment by skamal16** [comment]
I don't think this is fixed. Or at least in my case, I had steel frames and wooden frames available. It did not let me choose and gave the same error report as above but with component size 2. It also used up both the steel and wood frames. I am on 0.H latest.

**Comment by 5batek5** [comment]
Same here, tried to start creating a vehicle. I had 1 foldable light frame in my hands and 3 steel frames nearby when i initiated construction. My character just started construction without asking anything and after finishing it there are this error screen and nothings is builded.
 DEBUG    : constructing failed: components size expected 1 actual 2

 FUNCTION : done_vehicle
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\construction.cpp
 LINE     : 1442
 VERSION  : 2478ae8
