### ISSUE TITLE
Loads of Assassins spawning next to Hub01 when returning after a long time.

### ISSUE THREAD

**Issue by Deinsmeins** [CleverRaven/Cataclysm-DDA#71098]
### Describe the bug

When I traveled back and forth to hub01 a few times to reset the stock, there were a very large number (~50) of assassins spawned next to the hub. The game almost crawled to a halt due to the large number of npcs. Also, they were hostile and shown as attacking, but didn't really attack me for the most part, and if they were, they were mostly dropping their guns and trying to whack me with planks. Only a few of them actually attempted to engage me. Unfortunately forgot to make a save before killing them. Teleported back a couple days later for the bug report, the pile of corpses is still there with a few new assassins on top.

### Attach save file

[Williamsfield-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13996088/Williamsfield-trimmed.tar.gz)

### Steps to reproduce

- Spawn Clairvoyance artifact
- teleport out of the area
- pass a couple days time
- teleport back in
- repeat a few times

### Expected behavior

There should be an upper limit in how many NPCs can wait there for me. 

### Screenshots

![Screenshot from 2024-01-19 15-26-48](https://github.com/CleverRaven/Cataclysm-DDA/assets/157184911/ea8ab926-2403-465a-bdc1-f95647e1775d)

### Versions and configuration

- OS: Ubuntu 22.04.3 LTS
- Graphics: Tiles
- Version: 2024-01-18-0508 (linux-tiles-x64)
- Language: English
- Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, stats_through_kills, blazeindustries

**Comment by andrei8l** [comment]
`debug.log` indicates that they all spawned at the same time so this is probably not an EOC issue (where there is a limit). Triggering the EOC manually only spawns one assassin at a time and up to the correct limit.

Did you get debug messages saying "Failed to place NPC" the first time you encountered this horde? Or was that only after a save/reload?
