### ISSUE TITLE
Pool floaties

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#71107]
### Is your feature request related to a problem? Please describe.

Y'know, i noticed the pools are quite sparse. Im expecting there'd be some pool floaties and general pool related toys, but there isn't any.

### Solution you would like.

Add pool floaties into the game's pools

### Describe alternatives you have considered.

Not doing so.

### Additional context

Whether it should have the `FLOTATION` flag, im not entirely sure.

**Comment by PGR-14** [comment]
Maybe some of them should have the `FLOTATION` flag, but the noodles probably shouldn't

**Comment by MrHrulgin** [comment]
I especially like the idea of water wings as a fragile item that has to be inflated before use, but is more portable when uninflated than the floatation jacket or boogie board.

**Comment by BarndoBoi** [comment]
Pool floaties and foam noodles would be some welcome additions to the poolside, and nobody seems to keep beach chairs by their poolside much. I might take a look at adding some cute wearable pool floaties at some point. Then you could have the perfect drip for a visit to the ocean
