### ISSUE TITLE
Remove obvious descriptions of derived items

### ISSUE THREAD

**Issue by Uwuewsky** [CleverRaven/Cataclysm-DDA#71112]
### Is your feature request related to a problem? Please describe.

Many variant items use a separate description. This creates a burden on translators, on people who do audits and standardization, etc. In some cases, it is possible to remove them and leave the description of the base item.

### P1.
This includes all items whose descriptions can be deleted without losing any information.
Descriptions of some items (armor, but also others) differ from the basic ones only by the presence of a mention of size/material:
```
--pair of mild steel chainmail sleeves
Customized **mild steel** chainmail arm protection. 
Both sleeves have straps to connect them with each other. 
They don't cover the hands, making them less cumbersome and allowing them to be worn with gloves.

--pair of XL medium steel chainmail sleeves
Customized **medium steel** chainmail arm protection. 
Both sleeves have straps to connect them with each other. 
They don't cover the hands, making them less cumbersome and allowing them to be worn with gloves. 
**These are oversized.**
  
--pair of XS tempered steel chainmail sleeves
Customized **tempered steel** chainmail arm protection.
Both sleeves have straps to connect them with each other.
They don't cover the hands, making them less cumbersome and allowing them to be worn with gloves. 
**These are undersized.**
```
In this case, ~15 descriptions can be replaced with one, since the size and material are already mentioned in the item name and in the 'e'/'&' menu:
```
Customized chainmail arm protection. 
Both sleeves have straps to connect them with each other. 
They don't cover the hands, making them less cumbersome and allowing them to be worn with gloves.
```

### P2.
This includes all item variants whose descriptions have some kind of unique information:
```
--medium steel katana
A rare sword from Japan.  Deadly against unarmored targets, and still very effective against armor.
Made with medium steel and with a grip made of leather wrapped in steel wire, this weapon is
comfortable in your hand, though the balance isn't perfect and the edge could be sharper.

--high steel katana
A rare sword from Japan.  Deadly against unarmored targets, and still very effective against armor.
Made with high steel and featuring a sturdy grip, this feels like a proper weapon.
The balance feels right and the blade is quite sharp.
```
Remake such descriptions with "description_append/prepend". Unfortunately many items still dont use "copy-from".

### P3.
Nested recipes use unnecessary descriptions, since the name of the group already speaks for itself.
This way we can reduce the burden by ~500 lines.
```
"name": "steel heavy leg guards",
"description": "Recipes related to constructing heavy leg guards from various types of steel.",
```
We can naively remove the "description", but in this case it would be worth correcting the C++ code(crafting_gui.cpp?), otherwise an empty space will be created in crafting menu. I don't know if it is used ingame anywhere else.

### Additional context

I'm very for P1 and P3. I can work on them. And the rules from P1 are already used by most items.
P2 can be skipped since it affects the perception of the item. Or those with minor differences may be removed.
This issue also does not apply to non-variant items that differ significantly.

**Comment by Procyonae** [comment]
Having the ability to set copy-from descriptions to append to the end of the copy-from item's description in the same way variants of a base item can could be good.

Equally allowing the ability to prepend for both would be good (for whole sentences only to avoid word order issues when translating)

**Comment by Uwuewsky** [comment]
Kay, p1-p2 are waiting for the necessary PR

I looked at what can be done with p3. As already written above, you can simply remove the “description” from json:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5433b569ab2ee3dff086b979d17382fcd5d7de8e/data/json/recipes/nested.json#L9
And the mentioned space gap in the interface probably comes from `\n\n` here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5433b569ab2ee3dff086b979d17382fcd5d7de8e/src/crafting_gui.cpp#L1515

But there is also other code that loads the descriptions and processes them separately for nested recipes. I don't know how it works, what will happen if there is no description in the recipe, and to what extent it is safe to remove unused code. I may come back to this later.

loads (optional) description:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5433b569ab2ee3dff086b979d17382fcd5d7de8e/src/recipe.cpp#L456-L461
this function returns the description of the recipe:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5433b569ab2ee3dff086b979d17382fcd5d7de8e/src/crafting_gui.cpp#L1124-L1126
and here this description is drawn:
https://github.com/CleverRaven/Cataclysm-DDA/blob/5433b569ab2ee3dff086b979d17382fcd5d7de8e/src/crafting_gui.cpp#L1514-L1521
Maybe I missed something
