### ISSUE TITLE
Items of damage -1 once applied revert to damage 0, loose inscriptions.

### ISSUE THREAD

**Issue by cSep** [CleverRaven/Cataclysm-DDA#7112]
in english: 
* improved tents/turrets/sleeping mats loose the shiny once you apply them to the floor.
* they also loose your inscriptions.

fwiw, i use both improve/inscribe to know what to keep/drop/store etc. takes just seconds and make inventory very much easier

**Comment by Coolthulhu** [comment]
I'd mark this as wontfix, except maybe for the turrets. Tracking tents' and mats' status would require adding extra data to furniture or adding some sort of fake furniture/item coupling and so way too much work for such a minor problem.

**Comment by mugling** [comment]
As above
