### ISSUE TITLE
A hitchhikers guide to the cataclysm for the Markdown docs that ship with the game

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#71133]
### Is your feature request related to a problem? Please describe.

I was wondering what it would take to make a hitchhiker's guide for the Markdown documents and nornagon said that it would require the different sections and md files to be tagged appropriately.  This feature request is to figure out what that workload would look like and if it's feasible.

### Solution you would like.

Something that bridges the gap between our current repo documents and something more recognizeable to non devs as a wiki.  Most of the markdown documents are explaining what the various objects and qualities mean/do in game.  Even if the intent of that is to add contributors I believe it would also benefit at least a segment of players.

### Describe alternatives you have considered.

None really

### Additional context

@nornagon

**Comment by Procyonae** [comment]
What would the end result look like?

**Comment by harakka** [comment]
I'd like to point to https://docs.cataclysmdda.org/ that is already generated from the in-repo docs.

**Comment by nornagon** [comment]
I think what would work best would be to document specific things in ways
that hhg could display. Right now hhg only has pages for specific JSON
entities, so generic documentation doesn’t really belong there. But eg docs
for a particular flag, or item, or skill etc could be displayed on hhg.

What specific docs are you imagining getting into hhg?


j
