### ISSUE TITLE
Crash on save load related to the new trickle down bionic change

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#71136]
### Describe the bug

 DEBUG    : Error: Json error: data/mods/Aftershock/migration.json:24:1: <color_white><color_cyan>missing required field "from" in object: 
  {
    "id": [ "bio_microgen" ],
    "type": "bionic_migration",
    "//": "obsoleted from base game as part of https://github.com/CleverRaven/Cataclysm-DDA/pull/70989",
    "replace": "bio_trickle"
  }
</color>

    "replace": "bio_trickle"
  }
<color_light_red>]
</color>
<color_cyan>▲▲▲</color>
</color>

 FUNCTION : load_game
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1038
 VERSION  : 31e4c0e

### Attach save file

N/A

### Steps to reproduce

1. Cant load game so can't provide save
2. Provided save from my last report don't know what else to do 
3. So just load save and see crash

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 9229061 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by physics-enthusiast** [comment]
This seems to cause one of the CI tests to fail also.

**Comment by NthTech** [comment]
This error can also be replicated by attempting to make a new character on a world with aftershock enabled in the 31e4c0e experimental build.
