### ISSUE TITLE
Naked ultralight frames from blaze industries lag the game while on screen

### ISSUE THREAD

**Issue by inchlongqua** [CleverRaven/Cataclysm-DDA#71143]
### Describe the bug

While testing some vehicles construction I noticed that there was significant lag when barebones ultralight frames would be on screen, using any tileset.
The lag would disappear when said frames are covered or get out of the field of view. It doesn't happen when doing the same build with frames, heavy-duty frames, or extra light frames.

### Attach save file

[Volt-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14001972/Volt-trimmed.tar.gz)

### Steps to reproduce

1. Start new world with blaze industries mod enabled, make a new character, debug yourself out in an open field, give yourself debug mutations (hammerspace) for instant building to make things faster.
2. Start a vehicle construction and make a 3x3 pattern or so of ultralight frames. Shape given to said frames doesn't seem to change the behaviour, but I mainly used the default pattern
3. Try to move around with said frames in field of view. Moving is slowed down IRL significantly until the ultra light frames are out of the field of view
4. Cover said frames with aisles, lag disappears even with the vehicle in field of view

### Expected behavior

I expected the frames to behave like any of the other frames ie : not induce lag while in view, since they're from a (although popular and in repo) mod I understand that things might not always be so smooth. I downloaded the .G version of CDDA around april 2023 and blaze industries was in repo at that time, didn't tamper with it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries]
]

### Additional context

No crash, only heavy lag.

**Comment by fairyarmadillo** [comment]
Blaze industries is no longer maintained and has been obsoleted. See; #70612

**Comment by harakka** [comment]
It's still possible someone might pick Blaze Industries up, the json is still shipped and will be there until after next stable, and this is potentially exposing an issue that isn't directly tied to it.

However this is reported against stable, not exp, so would at least need to see if it reproduces on exp.
