### ISSUE TITLE
Text is rendered one pixel too low and characters are cut off

### ISSUE THREAD

**Issue by Lumi-Virtual** [CleverRaven/Cataclysm-DDA#71155]
### Describe the bug

In game menus like item descriptions, the sidebar, etc, every character has the lowest row of pixels cut off regardless of font size. This is most easily seen on full size characters like block elements, and box drawing characters when SDL ASCII lines is turned off.

### Attach save file

N/A

### Steps to reproduce

Look at any full height character in any game menu that isn't replaced with SDL ASCII lines and see its lowest row of pixels is missing.

### Expected behavior

Full characters should be rendered.

### Screenshots

Font size 16
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65882669/0a4663e4-13a2-4684-92c6-fd2f24609c9d)
Font size 32
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65882669/8fe5b401-d860-4365-b218-961fc310f942)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Qrox** [comment]
Does it help if you increase the cell height?

**Comment by Lumi-Virtual** [comment]
sadly not, increasing the font height adds another pixel of gap on the top, and decreasing the font height cuts off another pixel from the bottom. increasing or decreasing the font size makes it use the non bitmap version of the font which ends up looking quite broken
