### ISSUE TITLE
Crash while using Construction menu.

### ISSUE THREAD

**Issue by DarkSanek** [CleverRaven/Cataclysm-DDA#71164]
### Describe the bug

After opening Construction menu and scrolling down or searching for dig game always crashes on my save file. Tried creating new save file and crash doesn't occur.

### Attach save file

[Hope-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14004307/Hope-trimmed.tar.gz)

### Steps to reproduce

1.Open Construction menu
2.Search for Dig or just scroll down(to around crude anvil)
3.Crash happens

### Expected behavior

Game shouldn't crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crashlog_debuglog_save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14004362/crashlog_debuglog_save.zip)

**Comment by andrei8l** [comment]
/confirmed but it's only reproducible with the msvc build. ASan and -D_GLIBCXX_ASSERTIONS on linux don't trigger the crash

**Comment by SirClarke** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14005685/crash.log)

Also getting this one i think hope this helps
