### ISSUE TITLE
e-ink tablet drops literal books when activated in a dark spot where PC needs light to read

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#71169]
### Describe the bug

An error occurs when trying to (a)ctivate the e-ink tablet in a dark place where PC needs light to read. After which, the contents of the device literally drop on the floor or in the PC's inventory.

### Attach save file

N/A

### Steps to reproduce

1. Go to a dark area where light is needed when attempting to read
2. Activate the e-ink tablet PC (must have saved books previously)
3. Books drop

### Expected behavior

There should be no errors. Activate normally.

### Screenshots

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 641e7f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope]
]

### Additional context

also happens with smartphones

**Comment by RenechCDDA** [comment]
Update your experimental, this was resolved.

**Comment by RenechCDDA** [comment]
No further comment in a week, assume this has been resolved. If you still experience this please comment here or open a new issue. Thanks
