### ISSUE TITLE
[Magiclysm] Cavalry saber becomes a cavalry sabre +1 upon enchanting. (Spelling inconsistency)

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71172]
### Describe the bug

Saber or sabre?

### Attach save file

N/A

### Steps to reproduce

Look at the recipe.

### Expected behavior

Consistent spelling, presumably American standard, given the setting.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/363f9256-6926-4572-b7ad-1abc383d0900)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 50349bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by RenechCDDA** [comment]
Easy fix, should be `saber` per the manual of style (American locale, use American spellings).

The item id can (and should) remain `cavalry_sabre`. The mis-usage there is unfortunate but churn on the IDs is undesirable for such a small issue.
