### ISSUE TITLE
Colored Bikini Tops never drops from zombies

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#71186]
### Describe the bug

Zombies doesnt wear matching bikinis, more accurately, they never drop colored bikini tops

### Attach save file

N/A

### Steps to reproduce

1. Kill a lot of zombies
2. Check zombie drops

### Expected behavior

Zombies should be wearing/dropping matching pair of bikinis

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: d4121ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved]
]

**Comment by ashGlaw** [comment]
I've been noticing that bottoms are way more prevalent than tops, too

**Comment by Kywi001** [comment]
Yeah, you generally cant see any "pink bikini top", "blue bikini top" or other colors from zombie drops and a very rare chance they spawn at closets, its been this was for a very long time now, I think ever since they added these, idk how they arent noticing
