### ISSUE TITLE
Some ``copy-from`` weirdness to iron out

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#71199]
### Is your feature request related to a problem? Please describe.

@Procyonae asked me to open an issue to catch the weirdness I caught with ``copy-from`` in my recent PRs so here we are

### Solution you would like.

1. ``copy-from`` causes name inheritance for monsters, but does not do so for items. See #71195. It'd be nice if this was expanded to terrain as well, but for items alone this would allow us to save on some strings.

2. ``copy-from`` implies ``looks-like`` but only for certain types, it seems. It does not appear to do so for monsters, which I found out testing #71170

3. ``upgrades`` fields don't overwrite each other properly.
``"upgrades": {  },`` appears to have no effect at all. While ``"upgrades": { into_group },`` will NEVER be overwritten by ``"upgrades": { into },`` either. This means that coralling this field across ``copy-from`` is a hell and a half. Also found by testing #71170

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/7865bf79-d3c5-4ccb-bec5-ccbb3812fd34)
Guys we should have double checked if ``"upgrades": {  },`` works before using it I think.

**Comment by Karol1223** [comment]
> For 2 monster copy-from already inherits or sets looks_like if it's empty

I was under this impression too but in the PR I linked the resort staff zombies don't have tiles, despite the syntax being made in such a way to inherit from the default zombies?

**Comment by Procyonae** [comment]
> I was under this impression too but in the PR I linked the resort staff zombies don't have tiles, despite the syntax being made in such a way to inherit from the default zombies?

I just tested with some of the resort staff after removing the looks_like and they're still using it for me, maybe you spawned the pseudo dormant ones by accident or something?

**Comment by Karol1223** [comment]
> I just tested with some of the resort staff after removing the looks_like and they're still using it for me, maybe you spawned the pseudo dormant ones by accident or something?

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/4c83531f-7afb-4b0f-84ba-c51919fc3f8d)

``mon_zombie_resort_staff``, so I don't think it's the dormant ones (unless they share IDs?) @Procyonae

**Comment by Procyonae** [comment]
I'll have a look again when I next rebase
