### ISSUE TITLE
Mutation spells do not work properly

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71201]
### Describe the bug

#70146 made mutation spells (IE feline leap) run off of an EOC system, but it broke them in a few important ways.

1. It is not possible to instantly activate the mutations, despite the comments in mutation_activation_eocs stating this is possible. The game will throw an error and fail to load if you omit prep_time as it instructs you to do.
2. Because of the above issue, all mutations such as pounce appear to do nothing when you use them, and only open the spell targeting interface if you pass a turn. This is confusing and less than ideal in practice. People activating single-action abilities will assume they work instantly, like every other action in the game. The purpose of moving things over to EOCs was to reduce confusion and I agree with the premise, but it's worse now IMO.
3. The check for energy_amount is not functioning. You can use feline_leap even if you have 0 stamina.
4. The energy_amount does not appear to be correctly subtracted from the player's stamina. You do lose a pip of stamina when you use feline_leap, but I think that's just based on the normal move cost to get to that tile. I tried making a mutation spell that didn't move the player and no matter how many times I spammed it, I never lose any stamina.

### Attach save file

N/A

### Steps to reproduce

Make a mutant with feline leap, try to activate the ability. Note that the spell interface doesn't pop up unless you pass a turn, where suddenly and very awkwardly, the targeting menu is open.

Note that while leaping may not be reducing stamina as much as it ought to.

Note that you can leap even with 0 stamina.

### Expected behavior

Activated mutation spells should in most cases function instantly when the player presses the button. They should decrement stamina appropriately, and their stamina requirements should be respected.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0.G-6716-ga51f5f31e2-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

attn @guardia

**Comment by SariusSkelrets** [comment]
Can confirm point 2. Noticed that delay in the use of XE's vampire mutation spells

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    Sky Island [skyisland]
