### ISSUE TITLE
Crops should be affected by temperature

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#71200]
### Is your feature request related to a problem? Please describe.

Winter seems to have no effect on crops. Can harvest oats and corn from fields that have been snowed-over for months.

### Solution you would like.

Crops should start to die when the temperature drops below some level.

Temperature should also maybe give a bonus or malus to growth speed - or maybe that is a seperate issue?

**Comment by MrHrulgin** [comment]
If this is implemented, it should be on a crop-by-crop basis. Some plants are killed by snow, some aren't, and some are, but can be harvested after the plant has died.

**Comment by fairyarmadillo** [comment]
This is on my to-do list, it's just a huge pain in the ass and I'm not that good of a coder.

See: https://github.com/CleverRaven/Cataclysm-DDA/discussions/49327

**Comment by pwalsh0** [comment]
I suggest starting with the plants that we find growing in HUGE fields across the map. 

Oats and Corn must die right? 

Or maybe not - some agricultural expert will no doubt chime in. It just reduces the yield?

**Comment by fairyarmadillo** [comment]
Yeah that's all planned.
