### ISSUE TITLE
Moving partially disassembled furniture leaves the disassembly work spot behind

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71206]
### Describe the bug

I was halfway through disassembling an oven when a housefire made me a little too toasty. Rather than giving up the work, I stopped work and dragged the oven further away, only to find that the worksite didn't go with it.

### Attach save file

[Seffner-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14031208/Seffner-trimmed.tar.gz)

### Steps to reproduce

Start disassembling furniture, interrupt yourself, drag the furniture away.

### Expected behavior

The spot to interact with the work should follow the furniture.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/e8121a75-9607-4ffd-9214-453fb2e8c644)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 50349bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment]
I disagree.

Your case is probably an exception, and in most cases you'd want your disassembly zones to remain where you defined them. I would expect the most common reason for moving things away from the zone would be to make sure disassembly work targets the high priority item left in the zone, rather than the low priority item(s) you move away from it.

**Comment by MrHrulgin** [comment]
Is there a difference between a disassembly zone set up through the zone creation screen and the one created when you choose to disassemble furniture through the construction menu? I realize in reviewing the initial report I wasn't clear as to the method used; it was the second. Does that matter?

**Comment by PatrikLundell** [comment]
I don't know. Last time I disassembled furniture through the construction menu it was an all-or-nothing task, so if you were interrupted you had to start from scratch again.

Normal deconstruction (from a PC defined zone) creates an in-progress item that you can then either continue deconstructing like an in-progress construction item (accessed through the item itself) or by placing/leaving it in the disassembly zone and then issue the general disassemble stuff order.

If construction menu disassembly now creates a zone (which doesn't really makes sense to me) it should follow the in-deconstruction item and be removed when done. However, I don't really see the purpose of a zone, as a continuation can be ordered through the in-progress item (assuming that's what happens), and if the PC wants to hand the task over to a companion a zone can be created as normal.
