### ISSUE TITLE
Reloading a weapon/magazine only results in a partial reload

### ISSUE THREAD

**Issue by mike-hoogeveen** [CleverRaven/Cataclysm-DDA#71203]
### Describe the bug

When reloading weapons/magazines, a seemingly random amount of bullets get inserted in them, instead of completely filling them till they are full. This also happens when you use clips to reload a magazine. For example, if you use fully filled 5.56x45mm/.300BLK 10-round clips to reload a STANAG 30-round magazine, a random amount of bullets will be used each reload attempt, instead of using all 10 bullets.

### Attach save file

[McWilliams-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14029783/McWilliams-trimmed.tar.gz)

### Steps to reproduce

1. Have an empty STANAG 30-round magazine and multiple filled 5.56x45mm/.300BLK 10-round clips.
2. Reload the empty magazine using clips till it is full.
3. Observe that you do not end up with 3 empty clips, but multiple half used clips.

### Expected behavior

I expect each clip to be completely used when reloading a magazine, not partially.

### Screenshots

![Untitled0](https://github.com/CleverRaven/Cataclysm-DDA/assets/92297535/e0234887-bd2f-49f2-bb64-e4d5e045d4ea)
![Untitled1](https://github.com/CleverRaven/Cataclysm-DDA/assets/92297535/d8e56109-205a-4d84-a980-27de1f7cbfac)
The first screenshot shows 1 empty STANAG magazine, and multiple filled 10-round clips. The second screenshot shows what happens after reloading the magazine using the 10-round clips, note that only 9 bullets were used out of the third clip, instead of 10.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: dbd4067 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bombastic Perks [bombastic_perks],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by mqrause** [comment]
/confirmed

https://github.com/CleverRaven/Cataclysm-DDA/blob/b3733b0f76df2724a0b6d3ad447b4c690ab33f6d/src/inventory_ui.cpp#L3383

This is caused by this line from the migration to the inventory_selector menu in #70359.
It will only reload as many rounds as the selected menu entry has speedloaders (stack of 5 speedloaders => reload 5 ammo), because speedloaders are a weird mix of magazine and ammo stack.
