### ISSUE TITLE
[Magiclysm] Lashing Tentacles pushes off equipment unrelated to the shoulders.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71214]
### Describe the bug

The spell Lashing Tentacles says that the tentacles grow from your shoulders. But the set of things pushed off when I cast it included things that weren't anywhere near my shoulders. The MOLLE webbing belt is around my waist and certainly shouldn't be a problem. Weirdly, I can put the MOLLE webbing back on while the mutation is active.

### Attach save file

[Seffner-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14034218/Seffner-trimmed.tar.gz)

### Steps to reproduce

Equip a variety of gear and cast Lashing Tentacles.

### Expected behavior

Given the description of the effect I'd expect only rigid items that affect the entire torso or the neck or shoulder sub-bodypart section to be affected.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/eda70798-9fcc-4c6c-8872-bc9ea7a88923)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/1e7b0e1a-a471-4682-9c78-29f994daf371)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 50349bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]
- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 50349bb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Milopetilo** [comment]
Fixed by #71236
