### ISSUE TITLE
Unable to reload Miscellaneous Repair Kits with duct tape from cardboard rolls

### ISSUE THREAD

**Issue by TaiGambol** [CleverRaven/Cataclysm-DDA#71224]
### Describe the bug

Miscellaneous Repair Kits cannot be reloaded with duct tape from cardboard rolls as of Experimental 2024-01-18-0508

### Attach save file

[Testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14040946/Testing-trimmed.tar.gz)
World originally created in 2024-01-24-0635 experimental, downgraded to 2024-01-18-0508 in process of testing when bug was introduced.

### Steps to reproduce

1. Create a character in Experimental 2024-01-18-0508 or later.
2. Spawn a Miscellaneous Repair Kit and a container of Duct Tape.
3. Unload the repair kit, put the duct tape away out of sight.
4. Attempt to reload the repair kit using the cardboard roll of duct tape.
5. The game will claim you have nothing to reload it with.

### Expected behavior

The repair kit pulls the duct tape from the roll, as happened in Experimental 2024-01-18-0411 and earlier (tested).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2364 (21H1)
- Game Version: f2c8c58 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

Issue was first reported by KittyTac on the community Discord. GuardianDLL seems to believe #70359 may be responsible for the issue, which saves me digging through pull requests as I was about to do!

**Comment by Procyonae** [comment]
Dupe of #71090

**Comment by GuardianDll** [comment]
Technically it is more full one because it provide the exact version and probably the exact PR that caused the error

**Comment by TaiGambol** [comment]
Closing due to already being reported, added context/information added in comment on previous report.
