### ISSUE TITLE
Diary lists

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71227]
### Is your feature request related to a problem? Please describe.

Sometimes when you're running around looting, it can be hard to remember if you have a wrench at home. 

### Solution you would like.

The ability to generate lists in your diary with a few keypresses could be useful. The system could check all items in reach (as with crafting) and take inventory of what's available, that way you could refer back to these lists while in the field.

You can do this manually, but is there a reason to make the player do this bookkeeping?

List ideas include : Batteries, food, ammo, tool qualities, fuel.

So food could be like:

PROVISIONS (Spring 67, Year 1)
Dry beans . . . .  x3
Bread . . . . . . . . x7
Diet Cola . . . . . x2
Cooked Creep . x1000

TOOL QUALITIES (Spring 64, Year 1)
HAMMERING 1
WOOD SAWING 1
BOLT TURNING 1
BOLT TURNING 2

New lists would overwrite old ones. We could even make this process consume a sheet of paper and some ink from a pen or marker.

### Describe alternatives you have considered.

Again, the player could just do this themselves, that might even be more immersive. I think we can get some of that lost immersion back by making these lists require writing/typing tools.

The diary is currently an imaginary item. If we want to keep it that way but we want lists to cost paper/batteries, we could simply add "make a list" to the activation menu for computers and writing implements, and generate an item or a file on their phone that shows the information in a popup when activated.

### Additional context

Someone asked for something like this on reddit. Personally I just loot every single useful-looking thing I see and don't think too hard about it, but the apocalypse trope is a character who travels light and knows what they're looking for, this could help with that.

**Comment by Kamayana** [comment]
I _love_ this idea. Would give pen and paper a nice use, too.

**Comment by PGR-14** [comment]
> I _love_ this idea. Would give pen and paper a nice use, too.

& the leather journal

**Comment by Rokharn** [comment]
I am using map marks as memo for now (easy to find anything, using map search). As well as writing on ingame paper (or any other item like water bottle sometimes), using ingame survivalist marker... If the symbol limit were less strict, it might be more useful even at way of big memo lists.

**Comment by IdleSol** [comment]
I have some doubts. Of course, it depends on the way of implementation. And it's too early to talk about them right now.

But wouldn't this feature lead to getting a list of items from locked rooms? Labs, pharmacies, clinics. Go to a closed door, activate the diary and see what it contains.

How will it interact with a large list of items. Especially if the time dependent on the number of items is implemented. When I was building mobile bases. I was carrying around 6000 liters of stuff. I'm too greedy.

**Comment by Kamayana** [comment]
To help with the time cost concerns, it would make sense to show a rough estimate of the time it'll take to write everything down, that's something a person could reasonably predict. I also had a thought that it'd be funny if items with longer names took a fraction more time, but it'd almost certainly be better and make more sense to just assume the player character is abbreviating as needed.
