### ISSUE TITLE
Access to empty container bug exists in function "GetTrait"

### ISSUE THREAD

**Issue by megumin9** [CleverRaven/Cataclysm-DDA#71237]
### Describe the bug

In src/mutation_ui.cpp function ''GetTrait'',  if tab_mode is ''mutation_tab_mode::none'', then the vector ''passive'' is empty but the program will access passive[cursor], which will cause a crash. Is this intended? If not intended, this crash can be prevented as follows:

if( tab_mode == mutation_tab_mode::active ) {
    mut_id = active[cursor];
} else {
    mut_id = passive[cursor];
}

--->

if( tab_mode == mutation_tab_mode::active ) {
    mut_id = active[cursor];
} else if { tab_mode == mutation_tab_mode::passive
    mut_id = passive[cursor];
} else {
    ....
}

### Attach save file

N/A

### Steps to reproduce

In src/mutation_ui.cpp function ''avatar::power_mutations()'', the vector passive and active is empty, and the action is ''TOGGLE_EXAMINE". Because menu_mode is ''mutation_menu_mode::activating'' at first, the memu_mode will change to ''mutation_menu_mode::examining‘’ and the program will call ''GetTrait'', which will cause the bug.

### Expected behavior

The program will not access the vector ''passive'' when passive is empty in ''GetTrait"

### Versions and configuration

Game Version: Cataclysm-DDA experimental build 2024-01-25-0734

**Comment by RenechCDDA** [comment]
>will cause a crash. Is this intended?

Crashes are never intended, really. Thanks for the catch and reproduction steps, but I don't think your proposed fix is still quite there (it ends up returning an empty string, which obviously produces a debugmsg because there is no such ID). It does prevent the crash, I'll give you that.

Here's a better patch which displays the menu without any errors:

```diff --git a/src/mutation_ui.cpp b/src/mutation_ui.cpp
index 0cb6c03d2c..ae1cba367b 100644
--- a/src/mutation_ui.cpp
+++ b/src/mutation_ui.cpp
@@ -636,7 +636,7 @@ void avatar::power_mutations()
                 // switches between activation and examination
                 menu_mode = menu_mode == mutation_menu_mode::activating ?
                             mutation_menu_mode::examining : mutation_menu_mode::activating;
-                if( menu_mode == mutation_menu_mode::examining ) {
+                if( menu_mode == mutation_menu_mode::examining && !passive.empty() ) {
                     examine_id = GetTrait( active, passive, cursor, tab_mode );
                 } else {
                     examine_id = std::nullopt;
```
