### ISSUE TITLE
A levitating player still goes underwater when entering water:

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71232]
### Describe the bug

When you have the LEVITATION, flag, you still physically dive into the water, using up much more stamina when moving and beginning to drown if you run out of stamina. 

### Attach save file

[Bramwell-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14045566/Bramwell-trimmed.tar.gz)

### Steps to reproduce

1) Load save, check your @ screen, notice the "Levitation" effect
2) Enter water to the north. You'll immediately get the message about how your smartphone and matches will be destroyed as though you had dived in.
3) Keep moving north, your Stamina will drop to zero in 4-5 squares and soon after you're begin drowning, despite that you're levitating.

### Expected behavior

Presumably, having the LEVITATION flag means you would be walking on the surface of the water, not diving under it. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: e918859 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

I wanted to make a waterwalking spell for Magiclysm druids but there seems to be a lot of roadblocks in the way.

Related to #70207 but that report didn't mention water at all, so I made this one.

**Comment by RedMisao** [comment]
The name for the `LEVITATION` flag is somewhat deceptive. It grants free movement on open air, not the dnd effect of making the target _float over_ stuff by separating their body from a surface.
I can confirm this bug as I use the flag as workaround for #53532 (tl;dr dashing through z-levels drop you as if you fell, doing damage in the process). Dashing with the `LEVITATION` flag through barbed wire can hurt you, etc.
