### ISSUE TITLE
Commercial fertilizer & ammonium nitrate lack a primary skill

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71249]
### Describe the bug

Commercial fertilizer & ammonium nitrate lack a primary skill, meaning they could be crafted by anyone of any skill level.

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14055556/Orestes-trimmed.tar.gz)

### Steps to reproduce

Make someone with no skills or backgrounds, see what's craftable.

### Expected behavior

Some level of applied science skill.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/11dea68e-d3e2-4579-aef5-cfbf1648503c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 5262627 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by RenechCDDA** [comment]
This is intentional? They are the same 'thing', this just transforms them from one type of item to another. That's also why it takes only one second. You aren't *doing* anything, you're just telling the game "I would like to use my fertilizers as an explosive component now" (or vice versa).

**Comment by MrHrulgin** [comment]
It seemed out of character, as most other recipes that filled a similar role had a stated 0-skill requirement.

**Comment by RenechCDDA** [comment]
0 skill recipes allows it to train the skill to 1, which is clearly not desirable. Staring at a pile of fertilizer and deciding you will now call it "ammonium nitrate pellets" is not going to help you learn anything.

**Comment by MrHrulgin** [comment]
Except that ammonium nitrate pellets aren't instantly convertible to ammonium nitrate:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/72f27ea2-bb08-489d-8868-686c149aa90f)

It makes sense for fertilizer and pellets to not allow skill gain, but not this outlier.
