### ISSUE TITLE
Hub 01 intercom is a little too obviously reusing the same code as other NPCs

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#71243]
### Describe the bug

```
2 seconds You yell loudly.
1 second From the south you hear the intercom saying "Shut up, something is going on."
```

### Attach save file

[Granite Shoals-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14051134/Granite.Shoals-trimmed.tar.gz)

### Steps to reproduce

1. Yell at the intercom.

### Expected behavior

The intercom doesn’t hear you unless you press the button.

An even better solution would also have custom, perhaps even humorous, responses to the “Size up stats”, “Asses personality”, and other interaction options.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 38 (Thirty Eight); Release: 38; Codename: ThirtyEight; 
- Game Version: 51055e0290-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
It doesn't "reuse" the npc code, intercom is an npc, hidden inside a wall

**Comment by db48x** [comment]
That’s exactly what reuse means.
