### ISSUE TITLE
Crafting checks for nearby fire at the start and at the end

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7126]
I start a fire. This is enough to start and finish crafting, even if the fire goes off halfway through. So I can cook normally.

However, if I have an integrated toolset, I will lose some power at the end if the fire is no longer there. If I have no power left, I will still be able to finish crafting normally without it. If there is any other substitutes for a fire in a recipe, they will also be used. With a prompt if you have multiple options.

I propose to remove the end-check for fire to prevent unnecessary power/charges loss. Removing starting check instead is a bad option currently, I'd say, since this creates strong possibility of not being able to finish crafting when you already spent your time doing it.

If fire was more predictable (had countable duration), this could be used to determine if it will last enough for your crafting purposes, so that recipes can be made to require more or less fire and not just the fact that the fire exists at this particular moment. Don't know how to go about the weather, though.
##

**Comment by MisterFox** [comment]
With the advent of the side effect of #23299 this might be possible now -- side effect being that crafting stops if the light level changes. Maybe it could stop if your fire source disappears as well?

**Comment by smolbird** [comment]
Big problem. Players cannot yet automatically manage a fire while crafting. Fixing this issue needs that before it can be worked on.

Also the PR side effect a bug, see: https://github.com/CleverRaven/Cataclysm-DDA/issues/23569

**Comment by slitherrr** [comment]
Another possibility might be for running out of fire mid-craft to interrupt with a dialog for "feed fire", that would cancel the fire-end and craft-end events and move the menu-selected object onto the fire square being used. It special-cases something that should be general, but it's also less typing to get to the desired end result.

**Comment by EvgenijM86** [comment]
There is a construction item called "Mark firewood source" that enables auto refiling while crafting. The idea is good, but in practice I found it to be a micromanagement chore. Why? Because sometimes you want to disable auto-refiling, and the enable it again. So you basically remove it and construct it again - not a big deal. The big deal is that, when you construct it it moves all of the wood to adjacent tiles. So the process looks like this:
To enable:
1) build mark on your wood pile -> your wood pile gets thrown to adjacent tile
2) move your wood pile back to it's original spot
To disable:
1) Press 'e' and then 'Yes'.

And that is a lot of micromanagement for something that is supposed to automate stuff.

**Comment by ifreund** [comment]
@EvgenijM86 That's definitively an problem, but that deserves its own issue as it is outside the scope of this one.

**Comment by Nandorianen** [comment]
I haven't been closely following the development for the last two years, but if nothing changed regarding this issue, this may be relevant.
I just had this thought. How about separating open fire and contained/enclosed fire? What Cataclysm simulates now (if nothing changed) is open fire - unpredictable, dangerous, affected by weather. It doesn't really sound feasible to use fire like that for long-term projects. For these you would be better off using enclosed fire that isn't affected by wind or rain, that cannot spread and that is easy to feed and control. Therefore this kind of fire could be implemented like an effect with predictable duration (simulating that you feed it automatically with charges stored at that tile). It may not even need to be a proper effect: you can just consider it a tool with charges that need not be manually interacted with.
Thus, fire requirements could be split: for something really short any sort of fire would do, for longer projects - only contained fire with enough charges.
