### ISSUE TITLE
Frozen/Deep Frozen labs

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#71277]
### Describe the bug

I tried making a character a while back (Lab staff) in a Deep Frozen lab, didn't work, tried a Frozen lab, still didn't work, but everything else did. Same thing happens w/ the doctor in the refugee center.

Looked in overmap editor, but there wasn't any frozen labs.

### Attach save file

N/A

### Steps to reproduce

Make character w/ lab staff/patient scenario, or go through the doctor's quest progressions to the deep frozen lab & despair

### Expected behavior

Either no lab or lab.

### Versions and configuration

I tried it earlier w/ the latest experimental from the CDDA website (Windows, no mods) & it didn't work.

### Additional context

Currently don't have my computer right now, so I'm just filling this out for now.

**Comment by Procyonae** [comment]
Ice labs are hardcoded and appear as "science lab" with a 10% chance to attempt to spawn per overmap

**Comment by Procyonae** [comment]
First try at spawning in a deep freeze lab worked (admittedly on my 8 day old experimental)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/7749bdd7-228b-48d9-a93c-c2148a57abf5)

**Comment by Milopetilo** [comment]
I was able to spawn in both at deep-frozen & frozen labs on latest experimental

**Comment by Procyonae** [comment]
/invalid huh they changed what you can do since I last checked that's cool
