### ISSUE TITLE
[Mind Over Matter] Combination powers

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#71278]
### Is your feature request related to a problem? Please describe.

Considering a psion can have multiple attunements, it would seem logical that they could possibly use their powers in tandem with one another through practice, trial, and failure. However, nothing of this nature is represented in game, and the branching attunement paths seem very separate from each other.

### Solution you would like.

Add combination powers that psions can learn if they have multiple attunements. These could be variations of existing powers, or entirely new ones that can be discovered from practice. For example, a psion that has attuned to both Photokinesis and Pyrokinesis may be able to amplify the effects of Searing Flash, adding a more powerful blinding effect in addition to the burning fire of the original power, as they can more powerfully manipulate light in addition to fire. Someone with both Electrokinesis and Biokinesis could amplify the way their nervous system works to an extreme degree, speeding up reaction times vastly or positively charging themselves without damaging their flesh.

### Describe alternatives you have considered.

Not having the various powers interact in such a way, keeping them separate disciplines from each other. It's also possible that trees far away from each other may not interact in any way, only the disciplines close to each other in their natures could combine somehow, like a sort of color wheel.

### Additional context

This would open up a lot of opportunities for new powers in the game, along with different representations of psionic powers in some purposes.

**Comment by Standing-Storm** [comment]
I have some ideas for this in the future, but combination powers specifically is a great place to be like "These are harder and you _cannot_ just develop them naturally, you need to-" and then require poking around in labs or finding weirdo psions with quests or going into the Nether (once that's possible), so I haven't implemented any yet.
