### ISSUE TITLE
(Mind Over Matter) Lifting Hand field is not upgrading with powers

### ISSUE THREAD

**Issue by bcmcms** [CleverRaven/Cataclysm-DDA#71296]
### Describe the bug

My Lifting Field is currently stuck at 4.41 lb despite having 10 ranks in a telekinetic power. Testing the output with the attached file
[test_lifting.json](https://github.com/CleverRaven/Cataclysm-DDA/files/14073867/test_lifting.json) shows that my telekinetic rank is stuck at -1, despite having telekinetic powers and completing the lifting field contemplation.

To use my save to test you may need a copy of my Sky Islands mod folder 
[CDDA-Sky-Islands-main.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14073874/CDDA-Sky-Islands-main.zip) which is based off of a PR to the off-repo Milestone 1 Update.

### Attach save file

[Colstrip-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14073863/Colstrip-trimmed.tar.gz)

### Steps to reproduce

1. Load Save
2. Wait a second
3. The debug value will be printed showing -1

### Expected behavior

My lifting field should increase with my highest leveled telekinetic spell, after successfully completing the lifting contemplation craft.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.2274 (1909)
- Game Version: 0f39e72 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by GuardianDll** [comment]
/confirmed with the same EoC that write a debug output

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/47b3cc24-d882-459c-b7ae-6b87348e87f0)

@andrei8l maybe you know the reason it doesn't work?
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdc30581dc882eacf5a9bfd887bbaa0fa61a8b72/src/math_parser_diag.cpp#L725-L731

**Comment by andrei8l** [comment]
It should be
```JSON
{ "math": [ "test_school_telekinetic", "=", "u_school_level('TELEKINETIC')" ] },
```
(string not variable)

same here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdc30581dc882eacf5a9bfd887bbaa0fa61a8b72/data/mods/MindOverMatter/effectoncondition/eoc_mutations.json#L7

**Comment by GuardianDll** [comment]
I have some questions about how to understand where to use quotes, and where not - i always assumed quoteless is always variables

**Comment by GuardianDll** [comment]
well that is weird, i changed output EoC to be `{ "math": [ "test_school_telekinetic", "=", "u_school_level('TELEKINETIC')" ] }`. but it still report -1 level, despite i clearly have spell with higher level
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/8f341e51-9cd7-4c66-a856-b59f2e860199)

**Comment by Standing-Storm** [comment]
> it's because i didn't have a telekinetic trait 

There have been DOZENS of times I've been like "Why isn't X working!?" and it's because I debugged in all the powers to test it and did not debug in the trait.
