### ISSUE TITLE
Base Camp Construction Markers Incorrect

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#71292]
### Describe the bug

Markers for base camp construction were added with #71084.
Unfortunately, they don't seem to be placed properly.

### Attach save file

N/A

### Steps to reproduce

Make a basecamp within an evac shelter.
Select the "build a bedroom N/E/S/W" options and observe the placement of the markers.

### Expected behavior

Base camp markers should be placed properly.

### Screenshots

The selected option was for building the western bedroom out of logs.  Notice the construction markers placed in the bottom left.
![cataclysm-tiles_D53bav2c2A](https://github.com/CleverRaven/Cataclysm-DDA/assets/52714184/e4b8d28f-ccf8-4bc1-a2fa-2b3f3c62ba3d)

The building was placed on the right side of the building, nowhere near the markers.  The same markings were placed for the northwestern bedroom options, so it isn't only one step that is not being placed correctly.
![cataclysm-tiles_mthcwrXzje](https://github.com/CleverRaven/Cataclysm-DDA/assets/52714184/4c531253-a4b2-454c-8f68-f6d5b709f5fe)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 36c0fde [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungus [No_Fungus]
]

**Comment by PatrikLundell** [comment]
Investigating issues is a lot easier when a save file that can be used is provided.

**Comment by ANickelN** [comment]
[Lakewood Shores-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14073812/Lakewood.Shores-trimmed.tar.gz)
It happened the same way in two different shelter types on two different saves so I figured reproducibility wasn't an issue.  Here's the save.

**Comment by PatrikLundell** [comment]
Thanks.
It's not only a matter of reproducibility, but also a matter of possible circumstances (such as version and rotation) that may not be obvious, as well of ease of reproduction: people are far more willing to investigate a save than finding the right (?) location and then go through the task of reproducing the preceding steps.

**Comment by PatrikLundell** [comment]
OK. I think I understand what's going wrong (the save made it a matter of hooking up a debugger to the game running the save and then follow the code down from a breakpoint), but it will take some time to figure out how to solve it.

The issue is that there are basically two ways to rotate maps, and the implementation only handled one of them. Unfortunately, the code dealing with the variant not handled is buried inside the operation doing the actual update and has to be separated out with some care.
