### ISSUE TITLE
[Xedra] Paraclesian profession names don't match starting location names

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71309]
### Describe the bug

While there's a warning that says that you should be sure to pick an origin that matches your profession, not all of the names are the same. I get there's a bit of variation, especially with the gendered names, but when it's important that each profession exactly choose the right origin, it's important for this to be clear. Of greatest note are the pairs of (I think) Kemenysepro/Salamander, Duln/Humullys, and a bit Silvestris/Sylph, but Ierde is the only one that's a 1 to 1 match.

### Attach save file

N/A

### Steps to reproduce

Choose Paraclesian Birth scenario, see the list of professions, choose a starting location, see the names not match.

### Expected behavior

Matching names for ease of selection.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/66bf80f4-27bc-4edb-b48a-d17ff08481f9)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/30fb12cb-f57a-46ac-85aa-9561fd238c8e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Rokharn** [comment]
Interesting moment. For now on practice better to choice wrong location to gain easy access to their 'evolution components' from fae of not your kind of specie.
