### ISSUE TITLE
Filling a Vehicle Tank / Grab, Wield, Use, Eat, and Other Actions on a Vehicle Tile Crashes

### ISSUE THREAD

**Issue by Unbelievable-Salmon** [CleverRaven/Cataclysm-DDA#71300]
### Describe the bug

Whenever I try to grab/wield/use/eat an item  or refill a gas tank on a vehicle tile the game crashes.

### Attach save file

[Painted Post-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14074558/Painted.Post-trimmed.tar.gz)

### Steps to reproduce

1.Load save.
2.Open grab menu (Or try to wield/use/eat adjacent to the vehicle)
3.Select the vehicle's trunk
4.Try refilling the vehicle's tank

### Expected behavior

The UI for the grab/wield/use/eat menu should appear, and the the gas tank should be refillable. 

### Screenshots

N/A

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.2; Release: 21.2; Codename: victoria; 
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crashdata.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14074570/crashdata.tar.gz)

Things I've tried:
-Trying the reproduction steps on a fresh world.
-Trying the reproduction steps on a new install of the game with the same userdata.
-Trying the reproduction steps on a completely fresh install of the game.
They all still crash the game.

I haven't tried other actions like repairing, or mending.

**Comment by BrettDong** [comment]
1. Did you compile the game yourself or did you download a prebuilt binary?
2. What is your system locale?

**Comment by Unbelievable-Salmon** [comment]
> 1. Did you compile the game yourself or did you download a prebuilt binary?
> 
>     2. What is your system locale?

1. I download the game through Catapult.
2. US English.

**Comment by Unbelievable-Salmon** [comment]
> 1. Did you compile the game yourself or did you download a prebuilt binary?
> 
>     2. What is your system locale?

I apologize for my ignorance, I'm sure I'm missing something, but now that I'm on my computer here is the output from my terminal for the locale command:

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by Unbelievable-Salmon** [comment]
Updating my system fixed this for me.

**Comment by Unbelievable-Salmon** [comment]
So weirdly enough this seems to be caused by my computer's update manager. When I had an alert for a new update the game once again crashed the same way it always has, but when I install the update and restart it works again.
