### ISSUE TITLE
Vehicles should be protected from their own smoke

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7131]
I don't know where smoke comes from right now (which tile exactly), but even with mufflers placed outside on the rear of the vehicle, I still constantly encounter smoke in the car. This is annoying.

First of all, smoke should go from mufflers and, preferably, away from the car. 
Secondly, being in vehicle should make you immune or resistant to smoke - both for convenience's sake and for the sake of realism.
Thirdly, vehicles do not even produce that kind of smoke. I imagine it's not very healthy to breathe this exhaust, but it's certainly not that debilitating as a inhaling normal smoke. Some people, me included, even like the smell. So if you do not sit in the closed room with the engine turned on for an hour, you should be completely fine gameplay-wise.

I'd say that smoke from vehicles should be nerfed, changed to some other gas, or removed completely.
##

**Comment by Leland** [comment]
Closing - very old issue. Feel free to ping me here to re-open if there's still interest, or open a new one.
