### ISSUE TITLE
Reading books on a smartphone does not cost battery charges

### ISSUE THREAD

**Issue by random-cdda-modder** [CleverRaven/Cataclysm-DDA#71315]
### Describe the bug

Reading books on a smartphone does not cost battery charges.

### Attach save file

N/A

### Steps to reproduce

1. Create a new default evacuee survivor
2. Move next to the console for light
3. Debug spawn the most boring book you can think of
4. Scan it into the smartphone
5. Observe scanning taking charges off the smartphone
6. Throw the book away
7. Read the book from your smartphone
8. Observe the smartphone battery being just as full as in step 5
9. Smartphone can be used infinitely to read books

### Expected behavior

Smartphone battery depletes while reading

### Versions and configuration

[Cataclysm-DDA experimental build 2024-01-28-0645](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-01-28-0645)

**Comment by random-cdda-modder** [comment]
Could be fixed by adding https://github.com/CleverRaven/Cataclysm-DDA/blob/47cebfe5c1667d9c810875f3410e047e99ea35bb/src/activity_actor.cpp#L2941 to before the battery empty check at https://github.com/CleverRaven/Cataclysm-DDA/blob/47cebfe5c1667d9c810875f3410e047e99ea35bb/src/activity_actor.cpp#L1817

Could someone with a touch on expected game balance give input on how long should you be able to read per charge?

My initial suggestion would be:
```
if( calendar::once_every( 5_minutes ) ) {
    ereader->ammo_consume( ereader->ammo_required(), who.pos(), &who );
}
```

Also note that this should be a separate cost from having the same device provide the lighting required to read in the first place. Using a reader device in sunlight should be easier on the battery than in the dark, but both should still cost ammo. The lighting part is already coded in at https://github.com/CleverRaven/Cataclysm-DDA/blob/47cebfe5c1667d9c810875f3410e047e99ea35bb/src/iuse.cpp#L8780

**Comment by KeremBabaG** [comment]
> Could someone with a touch on expected game balance give input on how long should you be able to read per charge?

well definitely not me but 20 mins per charge seems ok, compared with irl ebook stuff

**Comment by ANickelN** [comment]
Smartphone vs EINK technology is vastly different, so we probably shouldn't be comparing the two.  If you want to represent a smartphone screen being used continuously (reading a book) the phone would likely last anywhere from 6-9 hours or so based on the brightness.
