### ISSUE TITLE
[Xedra] Doll Repair Paste recipe is broken

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71326]
### Describe the bug

The recipe for doll repair paste seems to be displayed incorrectly, as even when I fulfil all stated requirements the recipe is greyed out and won't complete. Also, despite the description saying that paint is needed, the only displayed component is dreamdross or superglue. Also also, it requires a tool with food cooking 2, but doesn't show a need for heat. If that's the case, why not just need a tool with Containing instead?

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14078938/Orestes-trimmed.tar.gz)

### Steps to reproduce

Try to make doll repair paste.

### Expected behavior

Paste instead of no paste.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/9dc69e1d-5360-49e8-a89d-236bd3f44822)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Maleclypse** [comment]
Try this and see if it helps.  The paint list is already in the components so I don't know why it's not displaying but I did fix the superglue or dreamdross and surface heat component.
```
  {
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "result": "doll_repair_paste",
    "category": "CC_XEDRA",
    "subcategory": "CSC_XEDRA_ELEMENTAL",
    "skill_used": "firstaid",
    "difficulty": 1,
    "time": "3 m",
    "flags": [ "SECRET" ],
    "book_learn": [ [ "dollkin_tablet", 0 ] ],
    "qualities": [ { "id": "COOK", "level": 2 } ],
    "tools": [ [ [ "paint_brush", -1 ] ], [ [ "surface_heat", 10, "LIST" ] ] ],
    "components": [ [ [ "paint", 2, "LIST" ] ], [ [ "superglue", 1 ] ], [ [ "scrap_dreamdross", 1 ] ] ]
  },```

**Comment by MrHrulgin** [comment]
I'm sorry, I don't know how to update an item's code to check and see if it'll work. If you could point me towards some instructions I can give it a go.

**Comment by Maleclypse** [comment]
> I'm sorry, I don't know how to update an item's code to check and see if it'll work. If you could point me towards some instructions I can give it a go.

No worries :) I'll try to get to it this weekend and test it.  That way I can see if it solves the paint appearing issue while I'm at it.
