### ISSUE TITLE
turrets should drop its inactive state and ammo when deactivated via a console or ID card reader

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#71332]
### Is your feature request related to a problem? Please describe.

It's kinda weird that the turrets just vanish out of existence instead of just, well, being deactivated. It would make sense if they were mounted to a wall or ceiling but nothing in their description indicates this, they are just on (what I assume to be) tripods.

### Solution you would like.

Instead of despawning they should drop their inactive state and drop their ammo if they have any.

### Describe alternatives you have considered.

Adjust their descriptions (this will also require some sprite work for tileset maintainers) to indicate that they are retractable towards walls/ceilings/ground instead.

### Additional context

I already wrote the code for deactivation instead of despawn. If this makes sense I'll make the pr for it.

**Comment by Rokharn** [comment]
Imagine. Scientist comes into lab, uses id, turret throws ammo on the ground? Why? Scientists used to come to the laboratories every day (probably). Who would reload the turrets every time after each visitor?

More logical, if it's just become neutral or friendly. Or if it disappears into the floor or wall, as is apparently happening now.

**Comment by Qrox** [comment]
Maybe we can create a "retracted turret" furniture for a deactivated turret to turn into, which when deconstructed with the right skills yields the turret plus its ammo.

**Comment by KeremBabaG** [comment]
> Maybe we can create a "retracted turret" furniture for a deactivated turret to turn into, which when deconstructed with the right skills yields the turret plus its ammo.

This makes much more sense. I'm on it.
