### ISSUE TITLE
Some hostile bandits are innocent

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#71341]
### Describe the bug

Random hostile bandits count as innocents for morale calculation. Not every bandit invokes a penalty. It's quite random. In attached save I've cleared the outside portion of one garage and didn't trigger the bug, but on second spawned garage the very first bandit triggered it.

### Attach save file

[Baseline-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14088055/Baseline-trimmed.tar.gz)

### Steps to reproduce

1. Find/spawn bandit_garage
2. Kill everyone
3. Enjoy -100 morale

### Expected behavior

Hostile, actively attacking entities should not count as innocent

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9906246/25116a8b-7c16-4df9-8d2c-2644e61d8178)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: e64a948 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Cenness** [comment]
I should have searched before posting.
Technically a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/69719 and https://github.com/CleverRaven/Cataclysm-DDA/issues/62278 and even as far as https://github.com/CleverRaven/Cataclysm-DDA/issues/30124

I was not clear in my description - it's not every bandit that invokes a penalty. It's quite random. In attached save I've cleared the outside portion of a garage and didn't trigger the bug, but on second spawned garage the very first bandit triggered it.

**Comment by PatrikLundell** [comment]
Yes, but the kill-bot keeps killing off bug reports if the bugs aren't fixed within a fairly short time.

**Comment by harakka** [comment]
> Yes, but the kill-bot keeps killing off bug reports if the bugs aren't fixed within a fairly short time.

That is not a reason to make duplicates. Stale bug reports are just as valid. They just need to be confirmed, that is, reproduced, to un-stale.

**Comment by PatrikLundell** [comment]
Nope. The kill-bot doesn't care whether reports are confirmed or not. It kills them anyway.

**Comment by harakka** [comment]
> Nope. The kill-bot doesn't care whether reports are confirmed or not. It kills them anyway.

This is incorrect. Please stop repeating it. This is part of why we label issues as confirmed.

**Comment by PatrikLundell** [comment]
It appear you are indeed correct. I will take that to heart (and spend effort on confirming reports when warranted).
