### ISSUE TITLE
celery is missing it's seed crafting recipe

### ISSUE THREAD

**Issue by Kupferdrache** [CleverRaven/Cataclysm-DDA#71363]
### Is your feature request related to a problem? Please describe.

Celery seeds are available to plant and use in recipes but the recipe for crafting seed from celery is missing.

### Solution you would like.

Have survial 2 recipe to craft seeds from celery like most other plants already do.

### Describe alternatives you have considered.

Create a Mod for the missing recipe so it can be toggled on/off if it would be imbalanced in the base game.

### Additional context

The idea came to me as I saw my celery going stale and I thought I have to many to eat so craft seeds out of the rest to plant later (seeds luckily don't go bad).

If it is a bug that the recipe is missing:
OS Linux 64-bit
Gameversion: Manjaro Package 0.G-2 Tiles

It is also missing from the hitchhiker's guide, so I asume it is missing in general.

**Comment by MrHrulgin** [comment]
The part of celery that's harvested for eating isn't seed-bearing. It's just the stalk of the plant. There's no way to harvest the seeds from that. To get celery seeds IRL, you have to wait to harvest the seed until well after the window for edible celery stalks have passed. No idea how that's modeled in game, but your idea isn't one that works very well. If the celery is *very* fresh, you may have some luck planting the stalk back in the ground and hoping it'll root, in the same sort of way that we model seed potatoes, but it's iffy, and won't work well with old celery.

**Comment by fairyarmadillo** [comment]
As the person who set this all up, it's definitely intentional that celery does not have a seed-crafting recipe. If you don't want your celery to go bad, consider dehydrating it or making soup, pickles, or some other preserved food. Or just eat it, or feed it to your animals, or become a saprovore.
