### ISSUE TITLE
Portable Soldering Iron cannot be crafted

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#71372]
### Describe the bug

It seems we got a new "portable" version - which is needed for some important items like firearm repair kit.

But there is no way to craft it - just gotta be lucky enough to find one on a zombie scientist it seems. 

 This should not be such a blocking item.

### Attach save file

N/A

### Steps to reproduce

Try to craft Firearm Repair kit and you will quickly run into this blocking issue

### Expected behavior

Should be able to craft a portable soldering iron by combining a light battery mod with a regular soldering iron.

### Versions and configuration

N/A

**Comment by pwalsh0** [comment]
https://cdda-guide.nornagon.net/item/soldering_iron_portable

**Comment by RenechCDDA** [comment]
Closing as duplicate.

Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.
