### ISSUE TITLE
Portal Storm Teleport Effect Becoming Effectively Permanent

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#71375]
### Describe the bug

Happened to be out in a portal storm for a bit, got teleported around a little bit no biggie, a day or two later I started randomly teleporting around uncontrollably. Turns out I got the "Dimensionally Unstable" effect put on me again from the portal storm but it effectively became permanent.

### Attach save file

[Ocean Acres.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14105180/Ocean.Acres.zip)

### Steps to reproduce

I'm not sure how to reproduce honestly but the save has my character currently effected by it.

### Expected behavior

For it to to essentially not be permanent.

### Screenshots

![20240130_173346](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/3e5f07a2-99ef-4484-bf14-93acbd00305c)
![20240130_173432](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/2a087a33-4642-41c5-b767-14a6162861bc)

### Versions and configuration

cdda-windows-tiles-sounds-x64-msvc-2024-01-29-1818
Windows 11
Magiclysm, Mind over Matter, Xedra as far as core content goes.

**Comment by andrei8l** [comment]
From discord: possibly caused by this suspiciously high value for `vitamin_psionic_drain`, which affects the length of `effect_portal_storm_teleport`
![20240130_175717](https://github.com/CleverRaven/Cataclysm-DDA/assets/68240139/ae033e45-9f47-42e8-ac6e-10b1bb38688d)
