### ISSUE TITLE
Permanently winded after swinging a mannequin

### ISSUE THREAD

**Issue by Syler1984** [CleverRaven/Cataclysm-DDA#71384]
### Describe the bug

I started as 6 STR infected shower victim, picked up a mannequin, smashed display case. Immediately my character becomes winded and collapses on the floor. And then they just lie winded and unable to move for more than an hour.

Made another infected character with 4 STR. Spawned a mannequin, 's'mashed a floor. Now poor lad winded without any prospects of recovering. He got exhausted trying to recover for 4 hours and fell asleep, woke up 10 hours later and still winded and paralized (message log in screenshot provided).

### Attach save file

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14112359/save.zip)

Don't ask why i am in a sex shop trying to smash display case with panties..

### Steps to reproduce

1. Be 6 STR (or lower).
2. Be infected.
3. 's'mash anything with a mannequin.
4. Become dead weight.

### Expected behavior

1. Swing heavy object.
2. Tire out.
3. Recover.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/12933526/6916215c-7c54-494e-adcd-c1d0873125bd)

### Versions and configuration

Version: dbd4067

**Comment by Milopetilo** [comment]
I think this is intended behavior, because you're carrying a mannequin that weighs 81.5 kg while your max carry weight is about 37 kg at 6 strength. If you drop the mannequin after becoming winded you recover as normal.

**Comment by MrHrulgin** [comment]
It may be intended behavior, but perhaps if the problem is that the character is carrying too much the message in the log should call that out? "The weight you're carrying drags you to the ground." or something, instead of the general purpose "You're knocked to the floor!", which only describes what happens without saying why? Especially in challenging situations like that, having more clarity of information would be helpful.

**Comment by Milopetilo** [comment]
It does say occasionally when walking `Your body strains under the weight!`, but I do agree that it should probably also tell you when you wield something that puts you over your weight capacity.

**Comment by RenechCDDA** [comment]
The default behavior is not to be able to pick up any object which would strain you like this.

**Comment by Milopetilo** [comment]
Just tested on a fresh install and it does prohibit you from picking up items over your capacity, but not from wielding them.

**Comment by Syler1984** [comment]
> I think this is intended behavior, because you're carrying a mannequin that weighs 81.5 kg while your max carry weight is about 37 kg at 6 strength. If you drop the mannequin after becoming winded you recover as normal.

Yes, weight seems to be an issue, not the smashing. Dropping the  mannequin allows character to recover. Frankly would never have thought that mannequins weight 81.5 kg. It's not a training dummy, just a display prop.
