### ISSUE TITLE
Savegame backup during autosave

### ISSUE THREAD

**Issue by BaumgeistOne** [CleverRaven/Cataclysm-DDA#71405]
### Is your feature request related to a problem? Please describe.

So I just lost my favorite character to a system crash (dont know if cataclysm caused it - but I do know that it used all the RAM available, around 10 GB) during autosave (corrupting the save), and it would've been pretty nice if I could just load a backup of the savefile. Sure, I could do backups manually, and the cataclysm launcher I used on windows does save backups automatically, but.... why doesnt cataclysm simply create a backup save? Just like the "ironman"-mode of some strategy games I play.

It would prevent issues like this, and it should not impact performance noticeably. 

### Solution you would like.

Before doing the autosave, copy the character save file to a backup location. If a crash happened during copy, the original save would be usable. If a crash happened during autosave, the backup would be usable.

### Describe alternatives you have considered.

Letting players use multiple saves per character.

### Additional context

I do know that his game is intended to be a "roguelike", but loosing a character one has been playing for weeks because of save file corruption is... somewhat annoying.

**Comment by Qrox** [comment]
We could probably avoid save corruption by making the saving process atomic, that is, deleting the backup as soon as the new save is successfully written, but I don't know if there's a portable way to implement that.

**Comment by RenechCDDA** [comment]
How I understand this is done elsewhere is that a new file is written to during the save (e.g. "savefile.tmp") and the actual deletion and replacement of the old savefile is only done as the very last step, meaning there is theoretically never any moment where an incomplete save exists.

The real problem is that there are repeated mentions of crashes during autosaves but nobody reports the damn thing.

**Comment by BaumgeistOne** [comment]
Since my whole system crashed and the save was just broken after that, sadly there was not much to report.

> We could probably avoid save corruption by making the saving process atomic, that is, deleting the backup as soon as the new save is successfully written, but I don't know if there's a portable way to implement that.

Did that already happen?
Some days ago, I had started another run, my game crashed during autosave. The save was, of course, broken, but... there was a second save, kind of a backup of the last autosave. Using that one, I was able to continue the run.
Very cool. :D

I should mention that both times, the crash during autosave, and the system crash, happened while I was exploring a lab full of breathers - maybe those are a little bit too busy?

Anyways, sorry for not reporting the second crash, will do if it happens again.

**Comment by Qrox** [comment]
> there was a second save, kind of a backup of the last autosave.

Now that you mention it, I remember it does write to a new file (at least for the player data) before deleting the old one. Although when I said atomic, I mean there should ideally be only two possible states: either the whole world is saved with new files, or the world does not save at all and an error is reported to the player. Ideally there shouldn't be a case where the player is left with no valid save, two saves, or an inconsistent save.

**Comment by BaumgeistOne** [comment]
> Now that you mention it, I remember it does write to a new file (at least for the player data) before deleting the old one. 

In that case it is strange that the old autosave wasnt there when my system crashed. :(
Oh well, stuff happens.
