### ISSUE TITLE
Queue for CBM installation/installing multiple bionics at once

### ISSUE THREAD

**Issue by RangerFromBaja** [CleverRaven/Cataclysm-DDA#71409]
### Is your feature request related to a problem? Please describe.

Currently, installing multiple bionics can get tedious because you need to open the installation menu, choose a CBM, wait for it to install, and in case of Rubik you will also have to go through the dialogue menu beforehand, repeating for each individual installation.

### Solution you would like.

Being able to choose the bionics similar to the book-scanning menu and queue-ing them up for installation in one go would be nice.

### Describe alternatives you have considered.

Decreasing the total operation time based on the amount of bionics being installed, and providing the patient with water if the operating time is somehow dramatically long to avoid dying of thirst.

**Comment by PatrikLundell** [comment]
Not a good idea, because failure can occur, and you probably don't want to get killed by an unlucky case of a failed installation leaving you critically damaged and a second one killing you.

You also do not tend to a get huge number of installation sessions as you run out of CBMs to install.

Of course, as long as it isn't mandatory (forcing cautious players to go through the extra step of aborting selection after one CBM), it won't hurt players who don't want to risk it.

**Comment by RangerFromBaja** [comment]
If you're installing bionics through Rubik (which is supposed to be the main way to get them now) then the risk is low enough for it to simply fail to install a few CBMs at worst, because of various grades of installation failure.

I'm not sure how proficient at installing bionics the Doc from Hub01 bar is compared to Exodii, and installing them yourself through the autodoc is definitely very risky unless your character really knows what they're doing.
if the installation chances are high enough for critical failure I do expect some sort of warning before the installation.

You definitely can get dozens of CBMs by dissecting Zomborgs as well as a lot of power storage CBMs from prototype and broken cyborgs (though those might get obsoleted eventually), and some players may also hold onto them to chrome-up their follower buddies later on too.

In this case getting rid of installation failure completely might also be on the table, from what I can tell it meant to gatekeep players from installing CBMs right away, back when they were a lot more common and could be dissected from a bunch of zombies.
