### ISSUE TITLE
Auto-pickup could do with expanded options

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71413]
### Is your feature request related to a problem? Please describe.

At the moment, auto-pickup only can filter by name or material. So if I want to have my character pick up all ammo and magazines I run across, I have to name them individually, as picking up every bit of steel is a fool's game. As such, I have a long list of autopickup rules that could mostly be boiled down to "Ammo, magazines, manuals, keys, food, drink, drugs."

### Solution you would like.

I'd like to be able to have autopickup rules that could cover any of the categories currently available for AIM sorting: name, weight, volume, density, charges, category, offensive power, ammo/charge type, spoilage, and barter value. Then I could pick up all non-rotten food, all ammo, things with a barter value higher than 1 with a weight and volume of less than .25, etc. Looting is the most tedious part of the game as it is, and already knowing what I want I'd really like to be able to automate it. 

### Describe alternatives you have considered.

Continuing the long tradition of extensive autopickup rule lists.

**Comment by ZhilkinSerg** [comment]
That would probably lead to a pretty poor performance.

**Comment by MrHrulgin** [comment]
But it would be poor performance that the player brought on themselves as they added more layers of rules, so everyone could tune it to their own level of willingness to wait. I'd be happy to have the game pause for a few seconds while it picked up everything I wanted so that I didn't have to spend two minutes perusing 10 pages of items in the AIM to pick out what I wanted from all the dross.
