### ISSUE TITLE
[Xedra Evolved] vampire guide doc is outside XE mod folder

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#71444]
### Describe the bug

XE's Vampire guide doc is outside XE mod folder.

### Attach save file

N/A

### Steps to reproduce

Go to https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/mods

### Expected behavior

Said doc being inside XE folder

### Versions and configuration

Game Version: 9ed0045

**Comment by Maleclypse** [comment]
Frick! This is one thing sublime is awful at.
