### ISSUE TITLE
Allow saving an EoC condition or list of conditions as a variable to be reference elsewhere

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71441]
### Is your feature request related to a problem? Please describe.

For my use case, [take a look at this line](https://github.com/CleverRaven/Cataclysm-DDA/blob/9ed00458dc5f61a90c2e4911a7c92c641e8e36ec/data/mods/MindOverMatter/powers/learning_eocs/biokinesis.json#L21) in the Mind Over Matter power-learning EoCs. That's 43 lines of effects that ban you from being eligible for the MoM power-learning EoCs, repeated for every power, for every path--almost ~7000 lines that all do exactly the same thing. 

It'd be really nice if I could put that in once place and just reference it ~200 times.

### Solution you would like.

Some kind of jmath-esque way to save a single condition or list of conditions and reference them later, either as the sole condition or as part of a larger list of conditions in an EoC. To fix the above 7000 lines it would have to be the latter, since each power has different prerequisites and thus could not re-use the same list of conditions. 

### Describe alternatives you have considered.

7000 lines.

**Comment by GuardianDll** [comment]
*points to set_condition, points that it is still limited to run_eoc_until*

Also i think in this exact case it would be better to have a way to check flag on effect
