### ISSUE TITLE
Can't save the game when character name has special characters in it

### ISSUE THREAD

**Issue by Dirtbug** [CleverRaven/Cataclysm-DDA#71453]
### Describe the bug

The game fails so save when you have characters in your name that windows doesn't allow in filenames. This only started happening after the new achievement saving system. Pretty sure this is related to #71327 trying to save a file with your player characters name as part of the filename.

### Attach save file

N/A

### Steps to reproduce

1.Start a new game and include characters windows doesn't allow in filenames ( / \ : ? * " < > |  ) in your player's name
2.Try to quicksave the game

### Expected behavior

The game should be able to save

### Screenshots

![CDDAsavefailure](https://github.com/CleverRaven/Cataclysm-DDA/assets/38131382/d0deb076-3041-414f-92c2-e822c67e2ce6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: f2cdb18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Xedra Evolved [xedra_evolved],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key]
]

**Comment by ZhilkinSerg** [comment]
Player names should be base64-encoded.

**Comment by db48x** [comment]
The phrase “special characters” means nothing. Why not say just say “punctuation”? Or perhaps “certain specific characters”? Or even “characters not allowed in filenames on Windows”, if you want to maximally precise?

**Comment by Qrox** [comment]
Should be fixed by #74419.
