### ISSUE TITLE
[Xedra] Stalker's Vision gives underground map vision.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71450]
### Describe the bug

When you have Stalker's Oculars active, your darkvision includes map vision. That's great. What's less great is that you also get it around you underground? Nothing in the description implies that it should give underground mapvision.

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14146049/Orestes-trimmed.tar.gz)

### Steps to reproduce

In save, deactivate Stalker's Oculars and go downstairs and look at the map. No vision aside from your tile. Activate Stalker's Oculars, see the map around you.

### Expected behavior

No underground map vision unless implied in the description.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/b158cba4-48f8-47a2-b1d7-a2962d689e6a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Rokharn** [comment]
"Your own eyes are replaced with the eyeballs of an unknown creature, indefinitely, until you toggle them off.  Compound from billions of red crosses inside void dark sclera, they can see much more clearly than any natural creature."

As a matter of fact, the description does not say any specifics about the effects at all. So I'm not sure what exactly the complaint is. I think the intention was that the effect should be determined by the players themselves, whatever it might be.

**Comment by MrHrulgin** [comment]
The "much more clearly" needs to be considered in the context of the mutation it adds, Stalker's Vision, which says: "You now see much better in the light and dark."

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/f0ceafc3-ffc2-4fac-99ee-cc31c58b8271)
