### ISSUE TITLE
There is no charm of marzanna recipe

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#71457]
### Describe the bug

When I play with Xedra mod and perk mod, I found it will pop error when I activate "Initiate Alchemy" perk. After looks through the current json of both mods, I found why : "charm of marzanna" don't have recipe to make it.

### Attach save file

N/A

### Steps to reproduce

1. Open the github
2. Use the search bar to search "charm_of_marzanna"
3. Find out there is no recipe to make that magic trinket.

### Expected behavior

There should be a recipe that `EOC_ALCHEMY2` can teach it to players, thus player can make that trinket ingame.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/97841551/b6f5799e-592a-4022-ba2d-8d0b70e59b27)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3085 (23H2)
- Game Version: c3f3efc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Kills [stats_through_kills],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Mana Cores [manacores],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by MrHrulgin** [comment]
#71059 Is related; spiritshow dust is also missing from EOC_ALCHEMY2
