### ISSUE TITLE
Reduced game performance

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71472]
### Describe the bug

While playing the game, there is a decrease in performance and responsiveness of the game.

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14152222/test-trimmed.tar.gz)

### Steps to reproduce

1. Download the attached save
2. In the place of appearance, walk inside and outside the debugging mobs
3. Pay attention to the responsiveness of the game (speed of movement of the character)
4. Add 10 years to the game time
5. Disable portal storm
6. Repeat steps 2 and 3
7. Exit without saving
8. Load save
9. Open the map and teleport between markers 1 and 2
10. Repeat steps 2..6
11. Walk to mark 1 or 2 (they are the same)
12. Pay attention to lags

### Expected behavior

No lags during the game

### Versions and configuration

- OS: Linux with Portproton (Windows 10.0.18362 (21H1))
- Game Version: eefe420 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]

### Additional context

While discussing the topic #71419, I encountered some strange game behavior.  Attached save, it's a specially created world, for playback. This isn't the first world I've tried to replicate the bug in. 

The results are quite inconsistent.

In the first test world, I created three identical locations. In two of them, lags occurred when replaying steps. The third location did not.

I moved this world to a newer experimental version. Lags started to occur in all three locations. I went back to the old experimental version, lags in all three.

I created a new test world, its save is attached to the report. Created location 1 - no lags. Added location 2, no lags. Added a marker for locations on the map, lags appeared. Removed the marker, lags still appeared.

Separately I want to pay attention that I use the version for windows. But I run it on linux. Perhaps it also affects.

P.S. I apologize for the quality of the text. Deepl translate is used.

**Comment by rtxyd** [comment]
When I doing step 9,  the game became this, and I can't do anything. 
See windows taskmanager the memory occupation is huge comparing to normal game. 
debug file says so, 
<details>
  <summary>ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\pixel_minimap.cpp:144 [request_tex] Ran out of available textures in the pool.</summary>

15:58:56.355 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: debug_write_backtrace+0xb5@00007FF60CACD9A5[cataclysm-tiles.exe+0x55d9a5]), 
  #1
    (dbghelp: DebugLog+0x2b8@00007FF60CACC758[cataclysm-tiles.exe+0x55c758]), 
  #2
    (dbghelp: realDebugmsg+0x1fd@00007FF60CACFA4D[cataclysm-tiles.exe+0x55fa4d]), 
  #3
    (dbghelp: pixel_minimap::get_cache_at+0x148@00007FF60DD07C38[cataclysm-tiles.exe+0x1797c38]), 
  #4
    (dbghelp: pixel_minimap::update_cache_at+0x81@00007FF60DD08C81[cataclysm-tiles.exe+0x1798c81]), 
  #5
    (dbghelp: pixel_minimap::process_cache+0x198@00007FF60DD07F68[cataclysm-tiles.exe+0x1797f68]), 
  #6
    (dbghelp: pixel_minimap::draw+0x47@00007FF60DD07747[cataclysm-tiles.exe+0x1797747]), 
  #7
    (dbghelp: cata_tiles::draw_minimap+0x65@00007FF60CE1C095[cataclysm-tiles.exe+0x8ac095]), 
  #8
    (dbghelp: cata_cursesport::curses_drawwindow+0xa49@00007FF60CAB9F39[cataclysm-tiles.exe+0x549f39]), 
  #9
    (dbghelp: std::_Func_impl_no_alloc<<lambda_66278e0d7b7c51155695763db7f5faf4>,int,draw_args const &>::_Do_call+0x13@00007FF60CD240F3[cataclysm-tiles.exe+0x7b40f3]), 
  #10
    (dbghelp: game::draw_panels+0x3d0@00007FF60CB495F0[cataclysm-tiles.exe+0x5d95f0]), 
  #11
    (dbghelp: game::draw+0x21d@00007FF60CB4867D[cataclysm-tiles.exe+0x5d867d]), 
  #12
    (dbghelp: ui_adaptor::redraw_invalidated+0x3df@00007FF60CC4CD3F[cataclysm-tiles.exe+0x6dcd3f]), 
  #13
    (dbghelp: do_turn+0xf1f@00007FF60CAD55CF[cataclysm-tiles.exe+0x5655cf]), 
  #14
    (dbghelp: WinMain+0xd45@00007FF60C95AAA5[cataclysm-tiles.exe+0x3eaaa5]), 
  #15
    (dbghelp: __scrt_common_main_seh+0x106@00007FF60E01519A[cataclysm-tiles.exe+0x1aa519a]), 
  #16
    (dbghelp: BaseThreadInitThunk+0x14@00007FFB81A27344[KERNEL32.DLL+0x17344]), 
  #17
    (dbghelp: RtlUserThreadStart+0x21@00007FFB823826B1[ntdll.dll+0x526b1]), 
Backtrace emission took 0 seconds.
(continued from above) ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\pixel_minimap.cpp:144 [request_tex] Ran out of available textures in the pool.

</details>


![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/1ccaf82f-5712-4a6c-b8a1-bb7d39e31de2)

**Comment by IdleSol** [comment]
>When I doing step 9, the game became this, and I can't do anything.

Use teleport through the debug menu. This error occurs if you teleport to a marker.

Most likely a translation error. Step 9 involves teleporting to a free field. Not on the marker itself. Any place at a distance of 3-4 global map tiles from the marker will do. So that the marker remains outside the reality bubble.

**Comment by NetSysFire** [comment]
For the "Ran out of available textures in the pool", see:
* #54088
