### ISSUE TITLE
Gut kcal can overflow from eating absurd amounts of food, causing death by starvation

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#71470]
### Describe the bug

Noticed that if a character with enough stomach size ate enough food in a short period of time, the kcal value stored in the gut will become negative, causing a sharp drop in kcal for the character

In my case, my huge character instantly went from "very obese" to "died of starvation" due to that

### Attach save file

N/A

### Steps to reproduce

1. Give yourself a ridiculously huge stomach size multiplier bonus (a consume time of 0 will help test quicker)
2. Spawn and eat absurd amounts of food
3. Check your gut through debug and see the negative number

### Expected behavior

A complete absence of overflows in the game, even when pushing things way past their limits

### Screenshots

![check if gut kcal can underflow](https://github.com/CleverRaven/Cataclysm-DDA/assets/68650913/bbf96afa-272b-4bc9-9e75-f41c1065a8b4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 7fab443 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]

**Comment by AnotherSeawhite** [comment]
Black Hole Stomach taken literally
