### ISSUE TITLE
Bomb fragment damage inconsistency

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71480]
### Describe the bug

There is a discrepancy between the number taken by monsters and the damage listed in the message log. I had a grenade deal more damage in the message log to a caustic zombie solder than it had hp (without dying), and a similar scenario with a regular zombie. 

### Attach save file

[Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14155128/Earth-trimmed.tar.gz)

### Steps to reproduce

Make an explosion near zombies and see if they take more damage than they have hp. 

### Expected behavior

I expected that the damage dealt to monsters from explosion fragments would be the same as the damage reported in the log. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/9c0aded1-545a-4678-bd48-765113d3614e)
![Screenshot (332)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/2fd97bd3-6abe-488e-a088-154d70f69632)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause a crash.

**Comment by Rokharn** [comment]
I think that's how it was intended. After killing a zombie, the level of damage to its body remains. It can wake up after some days, if damage minor, just to kill it (if player do nothing after). It can be totally smashed, if overkilled without needs to do it manually.

**Comment by DragonWizard23** [comment]
@Rokharn Thanks for the comment! I believe you are talking about a different mechanic, where zombies revive with limited health based on how damaged the corpse was. This bug report deals with a different issue. 

For this bug, I threw a grenade at a handful of zombies, and the message log showed that some of the zombies took significantly more damage than their total hitpoints, as shown from HHG. Despite taking more damage than they have health, a couple zombies **did not die**.

**Comment by fairyarmadillo** [comment]
Grenades have been weird for a while now. #67162 brought up that the actual (not listed) damage seems to have gone way up at some point, making a simple frag grenade instantly lethal for pretty much any enemy in the game, even bosses like the melded task force.

**Comment by fairyarmadillo** [comment]
> Grenades have been weird for a while now. #67162 brought up that the actual (not listed) damage seems to have gone way up at some point, making a simple frag grenade instantly lethal for pretty much any enemy in the game, even bosses like the melded task force.
> 
> Separate issue, but possibly related.

Following up on this: I tracked down what was causing #67162 and I don't thini it's not directly related to whatever's going on here.
