### ISSUE TITLE
Add a flying carpet to magiclysm.

### ISSUE THREAD

**Issue by Techmind** [CleverRaven/Cataclysm-DDA#71494]
### Is your feature request related to a problem? Please describe.

Helicopters are rare but very nice, i am frustrated that there are no magic equivalents. This is a staple idea in fantasy.

### Solution you would like.

 Temporarily or permanently summon of magic carpet. Which will be 1-tile vehicle which can fly and cant be modified, can come-up with a preset set of fuel with maybe 10-20 tiles worth of flying for full mana bar (can cost 2k mana).  The spell would be hard to cast (you could do it once per 8 hours of mana regen probably) so it should not require lots of levels to master it.

**Comment by MrHrulgin** [comment]
I like the idea quite a bit, but perhaps having it be a channeled spell that requires concentration would keep it from being abused? Being able to pre-pay the mana cost means you've got a perfectly secure sniper's perch for the duration, but requiring focus and preventing it from being used while you're in combat would mean it would be a great traveling tool without leaving as many cheese holes.

**Comment by Standing-Storm** [comment]
I was thinking of adding a Windwalking spell for Stormshaper or Flight for Magus (could fit either), but it would have a lot of the limitations MrHrulgin descriptions--no spells or ranged weapons allowed while maintaining it and it'd cost mana every square you traveled (ending when you touch the ground again)
