### ISSUE TITLE
Bullwhip allows bites from range

### ISSUE THREAD

**Issue by ALiteralSandwich** [CleverRaven/Cataclysm-DDA#71490]
### Describe the bug

Bullwhips allow a mutant with fangs or saber teeth to bite with long reach attacks.

### Attach save file

N/A

### Steps to reproduce

1. Be mutant with 'Fangs' or 'Saber Teeth'
2. Acquire Bullwhip
3. Attack something with the 'fire' key or tab to trigger a long reach attack
4. ????
5. No profit, it's not supposed to do that!!

### Expected behavior

I expect that a bite should not trigger from a ranged attack. Weird!

### Versions and configuration

c3f3efc

**Comment by fairyarmadillo** [comment]
This is partly fixed by #70797 and will be addressed the rest of the way in its followup PR(s)
