### ISSUE TITLE
Can't push a full trashcan (because there's not enough room for me to fit there)

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71512]
### Describe the bug

If a trashcan is too full for me to enter the cell, it won't let me grab and push it, because it won't let me enter the cell because it's too full.

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14159270/Orestes-trimmed.tar.gz)

### Steps to reproduce

Grab a full trashcan and try to push it. As it can easily be dragged, it's not an issue of strength or weight. 

### Expected behavior

I'd expect to be able to push anything I could pull.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

Possibly a related cause with #71471; it seems like vehicle tiles being too full to move through causes a number of issues with movement.

**Comment by fairyarmadillo** [comment]
Hm, I thought I fixed this. I'll take a look at it later today.
