### ISSUE TITLE
Handheld game systems generally spawn at 100/300 charge

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71514]
### Describe the bug

This is just kind of a trend I'm noticing in the world, but I figured I'd mention it. If a handheld game system spawns in the world, not as zombie loot, it always seems to spawn with a non-rechargeable battery at 100/300 charge. This seems weird. It's been a while since handheld systems used non-rechargeable batteries, right?

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14159381/Orestes-trimmed.tar.gz)

### Steps to reproduce

Run across handheld game systems, see a weird trend.

### Expected behavior

A diversity of charge levels, perhaps? Rechargeable batteries?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Vilab-unavailable** [comment]
I have the same game experience, i found many of those in a single mansion, most at 100 charge
