### ISSUE TITLE
Increased diversity of religious books changes refugee center quest balance.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71513]
### Is your feature request related to a problem? Please describe.

As far as I know, there's only one religious book needed for a quest; you need a copy of the Quran for someone in the refugee center. This was easy enough when there were a handful of different books in the pool of religious texts. Now that there's so much more flavor in that pool, it's significantly more difficult to complete that quest. This would be less of an issue if the possibility of welding training wasn't locked behind providing that book.

### Solution you would like.

A specific quest location so that you can be sure a Quran will be there, if nowhere else, as well as weighting the pool of potential religious books to more closely match the likely distribution in New England. Changing the weights won't make it more likely to find a Quran, as [less than 5%](https://web.archive.org/web/20110304012329/http://b27.cc.trincoll.edu/weblogs/AmericanReligionSurvey-ARIS/reports/part3c_geog.html) of New Englanders weren't either some brand of Christian or non-believers, but would make the range of flavor more realistic.

### Describe alternatives you have considered.

A different item being needed for the quest. I kind of hate that option, as I don't want to remove some of the only visible representation of non-Christian religious belief from the game.

**Comment by fairyarmadillo** [comment]
I always liked that this quest had me looking out for religious books I would normally ignore. Putting one in a specific location makes sense in terms of completability, but it cuts out the fun of actually rummaging through churches and libraries yourself and instead has you just following a quest marker. It'd be nice if there was a way to keep that needle in a haystack hunt somehow.

**Comment by MrHrulgin** [comment]
Yeah, it's just a much, much bigger haystack since so many new books have been added to the holybook pool.

**Comment by ashGlaw** [comment]
I would like to point out that you can often purchase a Quran from the librarian at a Forge of Wonders, but that doesn't help unless you're using magiclysm. The point stands, though, that perhaps you should be able to purchase one from an NPC in another faction

**Comment by fairyarmadillo** [comment]
"Go shopping for me" is a lot less interesting than "risk life and limb to retrieve this meaningful item from the ashes of civilization"

**Comment by MrHrulgin** [comment]
I've used the Magiclysm librarian many times myself, and the expanded pool of options makes that backup unreliable, as even their selection of 20+ options often won't include one.

**Comment by MNG-cataclysm** [comment]
When it's expanded upon, I think that the Great Library might be a good place to complete this quest, purchasing a copy from the merchant there.

**Comment by kevingranade** [comment]
Feel free to add more places that books should naturally spawn, and maybe tune up religious book spawns and shopkeeper offers  (there are legitimately a lot of bibles and qurans in the US), but no,  do not add guaranteed spawns of specific items just to make specific quests easier.

**Comment by kevingranade** [comment]
That's a different kind of quest, "fetch" and "find" are different,  that's intended.
