### ISSUE TITLE
Church Retreat EOC error.

### ISSUE THREAD

**Issue by Croctus** [CleverRaven/Cataclysm-DDA#71511]
### Describe the bug

When completing the chicken coop quest for Darryl at the church retreat, it gives an error and the coop does not spawn.

### Attach save file

[Coatesville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14159275/Coatesville-trimmed.tar.gz)

### Steps to reproduce

1. Create world and spawn the church retreat or travel to it if it's already visible.
2. Do the missions for Darryl until he offers the chicken coop quest.
3. Complete the quest and then wait a few moments. The error will occur and no coop will appear

### Expected behavior

A chicken coop to appear. Similar to other quests such as those at the Tacoma Commune.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3636 (22H2)
- Game Version: c3f3efc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14159284/debug.log)

Here is the debug log. The attached save is just before speaking to Darryl to complete the quest.

**Comment by andrei8l** [comment]
/confirmed godco EOCs use a pretty strange non-global (???)+recurring EOC chain instead of a calling `update_mapgen` from the mission's definition. If there was supposed to be a delay, queuing an EOC would have been better.

**Comment by ChineduOzodi** [comment]
A chicken coop appeared by the emergency shelter I spawned in and am making my base. I haven't done a chicken coop quest though. Is this expected behavior?
