### ISSUE TITLE
Bandits prioritized wielding cans of soda over weapons

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71526]
### Describe the bug

No idea why, but bandits got angry and all went for their sodas.

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14161987/Orestes-trimmed.tar.gz)

### Steps to reproduce

No idea how to reproduce this. It's weird.

### Expected behavior

Using better weapons than soda?

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/73359b84-37b6-4506-bb20-86075c2d2d58)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: cdc3058 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by PatrikLundell** [comment]
I've seen it as well when attacking bandits. They're also fond of throwing cans.

I'm not confirming it formally as it was a time since I attacked bandits (november?), but it's quite probable the behavior hasn't changed.

**Comment by Cenness** [comment]
It wasn't. I've had soda cans thrown at me while testing bug with innocence

**Comment by Vilab-unavailable** [comment]
I see that too

i have just met two bandits who had hanguns and preferred to wield soda can

One started wielding his gun after throwing a can at me

**Comment by Vilab-unavailable** [comment]
once again on last XP, this time the NPC launched their cans at arround 30 tiles away

**Comment by RenechCDDA** [comment]
Puma does not actually have any weapon available in this save, but their friends end up throwing a hatchet and baseball bat as you approach so congrats on finding a different bug.
