### ISSUE TITLE
Containers should sort alphabetically by contents, if only containing a single item

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71520]
### Is your feature request related to a problem? Please describe.

At the moment, if you have trashbag upon trashbag of pills, since keeping them in bottles wastes space and filling a series of bottles is incredibly boring, it will sort those bags alphabetically by the first digit in the number of items it holds. This is far less useful than sorting alphabetically by contents. Caffeinated chewing gum shouldn't be higher in the list just because I have 43 of them as compared to the 545 alcohol wipes.

### Solution you would like.

Sort the containers by contents if that's displayed, not by number of items held. 

### Describe alternatives you have considered.

Leaving it alone. It's minor.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/f4429034-afc9-4d64-8a8a-94bfcb07e231)

**Comment by andrei8l** [comment]
This can probably be solved by moving the contents count to the end of the segment when caching sort keys. Can you provide the save file for that screenshot since it's already nicely set up?

**Comment by MrHrulgin** [comment]
[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14160636/Orestes-trimmed.tar.gz)

Here you go. There's piles of loot in similar containers right next to me.
