### ISSUE TITLE
Item bifocal_contacts_weekly is active and tracking temperature, but it should not!

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#71523]
### Describe the bug

`Item bifocal_contacts_weekly is active and tracking temperature, but it should not!`

### Attach save file

[Cory-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14161284/Cory-trimmed.tar.gz)

### Steps to reproduce

Load save game. Don't know what makes this happen. It just started happening one day.

### Expected behavior

No error.

### Versions and configuration

```
- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: a8c6408 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
```

### Additional context

```
 DEBUG    : Item bifocal_contacts_weekly is active and tracking temperature, but it should not!

 FUNCTION : io
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\savegame_json.cpp
 LINE     : 3117
 VERSION  : a8c6408
```

**Comment by PatrikLundell** [comment]
I can confirm this started to happen recently. It's caused by changes to the item, so when an older save is loaded this message pops up (assuming the item was present in that save). Once you've saved the game it won't appear when you load it the next time.

Not confirming the report officially since this is probably a case where we want the kill-bot to bury the report.

**Comment by b3brodie** [comment]
> I can confirm this started to happen recently. It's caused by changes to the item, so when an older save is loaded this message pops up (assuming the item was present in that save). Once you've saved the game it won't appear when you load it the next time.
> 
> Not confirming the report officially since this is probably a case where we want the kill-bot to bury the report.

Were you able to verify that the error disappeared on save+load? In my own save and also in the linked one the error persists on every load of the save even after saving and quitting.  I think there's an error in whatever migration is supposed to be happening.

**Comment by PatrikLundell** [comment]
I did load my save, saw the error, saved and quit, loaded the game, and the error report did not appear again. In short, yes, I did.

**Comment by misterprimus** [comment]
> I did load my save, saw the error, saved and quit, loaded the game, and the error report did not appear again. In short, yes, I did.
> 
> Edit: I've now also downloaded your save, loaded it, ignored the error, saved & quit, reloaded the save, and the report does not reappear.

I have not tried IGNORING it. And in that case it DOES reappear. I guess I can try (I)gnoring it and if it doesn't make a functional difference.

**Comment by ANickelN** [comment]
Seconding that in my save-game the message does re-occur.

**Comment by PatrikLundell** [comment]
Yes, it seemed only to go away when reloading without exiting the game...

**Comment by Rokharn** [comment]
Ignoring errors is not the same as it's self-fixing, it will still appear in the logs, so it will still happen...
