### ISSUE TITLE
Trapavoid monsters are frozen by being boxed in by traps. Again.

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#71532]
### Describe the bug

Monsters with `"PATH_AVOID_DANGER_1"` and avoid_traps path settings are frozen in place by unavoidable traps in their path, leading to the intergalactic invaders from the Planet Mu to get defeated by a salt circle made of glass shards.

Additionally, even with *non-boxed* trap setups will lead them to derp out even if they have the smart pathing enabled.

### Attach save file

N/A

### Steps to reproduce

Spawn a circle of caltrops, stand in the middle, spawn a mi-go and watch it vibrate along the corner. Teleport outside on the side opposite to them, watch them fail to path around the traps until you are practically adjacent to them coming from a trapless direction.

Spawn a non-full large C of caltrops with an opening on the other side of the mi-go, watch it freeze anyway even though its 50 path_dist should make it path in with no problems.

Do the same in .G Stable, behold the migo not derping out and breaking your face, even if it means an ouchy toe or eleven.

### Expected behavior

At the very least returning to the post - #48588 stage of pathing smartly when no other options are available.
As a stretch goal they could take the expected trap damage into account for the path cost.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/72006894/bb35f02f-8649-4dd7-bfd4-b163b6f05856)
A very rudimentary reproduction setup thrown together after a discord report.

### Versions and configuration

commit `5276eb51baa8ab5a8fe94d77fe3c092eb1d722a9`, built locally using MSVC

### Additional context

As mentioned I already fixed it once but something broke along the way, but I'm not in a position to look into it in the near-term.

**Comment by fairyarmadillo** [comment]
It'd be nice if intelligent enemies like Mi-go or the smarter ferals could, if there were no alternative, spend a few seconds kicking caltrops out of the way or slowly tiptoeing over them, maybe with a % chance to accidentally set off the trap.

**Comment by nornagon** [comment]
Bisected to f724640b848f1b0ea9aaa3ef2ff2fef008f9113e
