### ISSUE TITLE
Broken snippet after dissecting a skeletal zombie

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71531]
### Describe the bug

After dissecting a skeletal zombie (on a large plastic sheet) there is a log message that doesn't load properly. I discovered this bug after updating from 1/21/24 0750 to 2/5/24 0148. 

### Attach save file

This is the save file from before I updated: [Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14166292/Earth-trimmed.tar.gz)

### Steps to reproduce

With my specific save, here are the steps to reproduce the bug:
1. Grab the skeletal zombie from the trunk of the pickup truck (it is in the tile furthest from the front of the truck). 
2. Deploy a large plastic sheet on the ground (there should be one in my inventory but if not, there is one in one of the truck's cargo spaces). 
Note: Step 2 might not be needed for replication, but I'm replicating the circumstances as closely as possible as when the bug occurred. 
3. Dissect the skeletal zombie on the plastic sheet and observe the broken snippet. 

### Expected behavior

I expected that the snippet would display some flavor text about the dissection, instead of <zombie_humanoid_harvest_bone_general>. 

### Screenshots

![Screenshot (342)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/5255b414-2da5-43ec-a0a8-e32d11c4df3a)

### Versions and configuration

This is the updated version when the bug occurred. As mentioned above, the save was previously from the 01/21/24 0750 build. 
- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: a8c6408 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

The bug does not cause a crash, though there is an unrelated error message about contacts that appears when the save loads.

**Comment by NetSysFire** [comment]
It looks like that snippet is not even defined, so that is likely the cause of the error.
