### ISSUE TITLE
Picky Eaters cannot drink Magiclysm potions

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71544]
### Describe the bug

Magiclysm magical potions apparently count as subpar food, making picky eaters refuse to eat them.

### Attach save file

[Hollins-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14172885/Hollins-trimmed.tar.gz)

### Steps to reproduce

1) Hit E
2) "You are not going to drink this."

### Expected behavior

...I'm not sure if this is intended or not, honestly. It just seems a little odd that picky eaters would be snubbing magical potions.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/cdbbcadd-c180-44ea-9355-156d506b7f8d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 22c808f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

This doesn't lock picky eaters out of magical buff effects, necessarily, since organic, artisanal potion fruits exist, it's just kind of weird and unexpected.

**Comment by Rokharn** [comment]
Actually, you can. Put into refrigerator and most of this drinks can feel better, so picky eaters can solve this problem. At least I  (mostly) solved this kind of problems of my character this way. Some of these potions can even be consumed frozen (mostly fruit potions, but not every).

**Comment by Standing-Storm** [comment]
Unfortunately, Freezer Field doesn't actually lower the temperature of food, it just prevents it from spoiling (temperature-lowering on containers is all hardcoded). It's pretty fun that Picky Eaters are like "I refuse to drink this Potion of Ogre Strength unless it's been properly chilled," though.

**Comment by Rokharn** [comment]
> "I refuse to drink this Potion of Ogre Strength unless it's been properly chilled,"

Sounds like a pretty good idea for one of most important for picky eaters spell - 'create ice cubes for drinks'. And maybe ability to ad extra sugar or salt as well. Not sure how such people can live without it. )

**Comment by fairyarmadillo** [comment]
I love that the obvious solution is just to make the potions less yucky, but instead Alphas are bending eldritch forces to our will to make ice cubes 😆 

What if there was a craft that could make them more palatable? Adding some sugar or zero-calorie sweetener to your potion of ogre strength sounds pretty funny. Making full on cocktails out of them is even better.

**Comment by Rokharn** [comment]
Well, if one day we actually get ability to mess our food or potions with salt, pepper or sugar with some random effect (from negative to positive), it will be pretty realistic. Quite often I spoiled my 'beautiful culinary masterpieces' (with difficulty level of fried eggs) with an overabundance of spices,but miracle of mayonnaise saved the day. )

**Comment by Rokharn** [comment]
> annoying to make 6 different variants of every single potion

I think there is another way to do it as well. Like 'abusing' a system for changing the level of taste depending on conditions. As a result, spices become an EOC activator with a random taste modification effect. Not sure how hard it is, but sure, it's possible. 

Another, simpler, but somewhat stupid method is to eat the spices themselves in advance in order to activate the effect of modifying the flavor level of the next dish (or something like 'flavor enhancement potion', effect similar to Gourmand trait).

But 'ice cubes' surely more useful even outside the scope of this mod. We have a whole category of food that tastes better cold or frozen. (Plus ice packs to reduce pain for bruises and headaches would be very helpful as well. But that's a completely different story)
