### ISSUE TITLE
Annoying pop up notification when you trying to pick up item

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#71547]
### Describe the bug

When you are trying to select item in pick up menu, which you cant to pick up - pop up window appears and make you do extra key press, but you are already see the reason, why you cant pick up item
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/8449c026-6aff-450c-b2e0-77d3e60048ea)

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14174042/test-trimmed.tar.gz)

### Steps to reproduce

Be nude
Spawn jerry can
Press key to pick up item
Try to pick up item
See annoying pop up notification

### Expected behavior

Dont have annoying unnecessary pop up menu with extra keypresses problem, or at least have ability to remove this notifications

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 3706e56 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,9%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ZeroInternalReflection** [comment]
The popup was added specifically for people on small screens where the reason you can't pick up/trade/etc. the item doesn't fit.

I'm currently testing a tweak where it caches the available space in inventory_entry and only displays the popup if the denial message got trimmed.  (Polish shown as it's my current go-to for things not fitting in the UI):
https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/f08766d8-19ba-4ba8-911d-2c006df3fe67

This would still result in situations where you get the popup on selection even when the denial message is obvious, but it would ensure you can always actually see the full message.

**Comment by Kamayana** [comment]
It would also be nice if the popup was changed to `popup_getkey`, which lets any keypress close the popup rather than specifically ESC.
