### ISSUE TITLE
u_val('mana')", "+=", can raise mana above maximum value

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71543]
### Describe the bug

I recently added a potion fruit that increases your mana, using `{ "math": [ "u_val('mana')", "+=", "rng(200,600)" ] }`.  When using it recently in game, I noticed that this doesn't take your max mana into account--using it will raise your absolute mana value even if it goes over your max. The next time mana regen ticks, if your mana is over your max it's reset to max.

### Attach save file

[Hollins-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14172826/Hollins-trimmed.tar.gz)

### Steps to reproduce

1) Eat a handful of Starry False Solomon's Seal potion fruits.
2) Mana goes above max mana.

### Expected behavior

Max mana is the maximum barring enchantments that raise it higher.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/e8b54c44-def8-4e05-9cbb-39108f672c7a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 22c808f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

I'm unclear if this is how math is supposed to behave in this case and I should rework the item, but I'm reporting it just in case.

**Comment by andrei8l** [comment]
> I'm unclear if this is how math is supposed to behave in this case

Principle of least surprise - if you expected it to be clamped, that's probably the way it's supposed to work.
Try this:
```diff
diff --git a/src/talker_character.cpp b/src/talker_character.cpp
index 488f47be12..f148d634d6 100644
--- a/src/talker_character.cpp
+++ b/src/talker_character.cpp
@@ -761,7 +761,7 @@ int talker_character_const::mana_max() const
 
 void talker_character::set_mana_cur( int value )
 {
-    me_chr->magic->set_mana( value );
+    me_chr->magic->set_mana( std::clamp( value, 0, me_chr->magic->max_mana( *me_chr ) ) );
 }
 
 bool talker_character_const::can_see() const
```
Or clamp it yourself in the math expression.

**Comment by RedMisao** [comment]
I'm tinkering with an EOC that turns morale into mana, and for what I've seen `math` and `u_val('mana')` can add beyond the pool, like you say.
However, it seems somewhat self-limiting as the bonus is lost after either an INT stat change or the next time the "add mana" timer is refreshed. I'm not sure which one of those is.
