### ISSUE TITLE
FEMA camps have empty ammo cans

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#71552]
### Describe the bug

Almost all ammo cans from FEMA Camps are empty

### Attach save file

N/A

### Steps to reproduce

1. Find fema camp
2. Check lockers for ammo cans

### Expected behavior

They shouldnt be 90~100% empty

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: c3f3efc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved]
]

**Comment by GuardianDll** [comment]
Do you think soldiers should took empty cans with them?
This is a feature, not a bug

**Comment by RenechCDDA** [comment]
^Short way to say "Working as intended".
