### ISSUE TITLE
Something's up with horizontal roads on ASCII map

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#71568]
### Describe the bug

Title

### Attach save file

N/A

### Steps to reproduce

1.Make character
2.Open map
3.Roads on map are cut instead of making up a straight line

### Expected behavior

straight lines

### Screenshots

![Ekran görüntüsü 2024-02-06 143011](https://github.com/CleverRaven/Cataclysm-DDA/assets/30256012/6106377f-0c11-4ea5-a611-97a9ca9629ae)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 12f3944 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Cenness** [comment]
Consequence of this pr https://github.com/CleverRaven/Cataclysm-DDA/pull/71330 switching off SDL ASCII lines by default
You can enable it in Settings/Options/Graphics/Font settings - bottom option for that group

**Comment by MNG-cataclysm** [comment]
/confirm, I have been experiencing the same with my game.
