### ISSUE TITLE
Weird/broken(?) writing on vandalized shelter wall

### ISSUE THREAD

**Issue by KeremBabaG** [CleverRaven/Cataclysm-DDA#71569]
### Describe the bug

It says <full_name> in one of the vandalized writings. I don't think it's intended? maybe a snippet error?

### Attach save file

N/A

### Steps to reproduce

1.Make a new world, create a character with "Squatter" scenario
2.Spawn in a shelter
3.In the basement it's, there

Though since the writings are random it might not come up every time. I assume you can find it in other vandalized buildings as well

### Expected behavior

It's supposed to write the player name I suppose

### Screenshots

![Ekran görüntüsü 2024-02-06 143100](https://github.com/CleverRaven/Cataclysm-DDA/assets/30256012/d3915cd3-e3a0-40f7-8872-f83d2eccf772)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 12f3944 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This might be intended as some 4th wall break maybe, I'm not sure

**Comment by PatrikLundell** [comment]
I doubt many people are keen on randomly generate worlds and TP around to hunt down this (or, for that matter, verify that it's fixed if they can figure out what the problem is anyway).
Thus, a save demonstrating the issue is probably needed.

**Comment by KeremBabaG** [comment]
Alright, I'll attach it tomorrow, studying rn

**Comment by Qrox** [comment]
The `<` in `<3` has made the code think `<3 <full_name>` is a tag, which is not found in the loaded snippets, so the tag is not replaced at all. I'm working on a fix.

**Comment by KeremBabaG** [comment]
Shit forgot to add the save file but that seems likely. I'll look into that
