### ISSUE TITLE
fitover rollerblades

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#71563]
### Is your feature request related to a problem? Please describe.

Having powerful unified armor (e.g like rm13) prevents using really useful stuff like rollerblades. 

Fortunately there's an [existing solution](https://www.inlinewarehouse.com/Doop_Skates_-_Powered_by_Powerslide/catpage-DOOPSKATE.html). Fit-over rollerblades.

This "issue" is meant to track adding this item in the game. 

### Solution you would like.

A `rigid` footwear that is slightly less encumbering than rollerblades, less efficient (speed gain should be tiny bit smaller and even more unstable... But can be worn over other rigid footwear, but not over itself.

Some types of footwear should restrict using this. Anything that's much larger than `leather boots` shouldn't allow wearing this (e.g. power armor). Courtesy of @fairyarmadillo 

### Describe alternatives you have considered.

Not adding this.

### Additional context

I am addicted to speed (running).

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56438982/f3517b5c-9487-4b5b-808a-fb619c53df02)

**Comment by fairyarmadillo** [comment]
Power armor is way too huge and heavy for something like this.

**Comment by Zireael07** [comment]
I like the idea in general but I agree with @fairyarmadillo

**Comment by tornikeo** [comment]
@Zireael07  @fairyarmadillo That's a good edge case. Definitely should restrict what it can be worn over.

Given that we don't restrict even the severely overweight PCs from wearing skates, what should be the common criteria for wearing them? Like, total weight of the armor piece? or only restrict Pow armor?

Also, hopefully we DO agree that a `A full-body suit of sleek black military armor...` could be fitted with a pair of skates on boots.

**Comment by fairyarmadillo** [comment]
I guess my problem is that our power armor isn't making you feel like a gigantic robo suit badass. That's not a problem with the skates themselves.
