### ISSUE TITLE
Add dangerous radius to description of notes/list of notes marking dangerous areas

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71577]
### Is your feature request related to a problem? Please describe.

I often use map notes to keep track of POIs and dangerous areas, and some areas are more dangerous than others. As such, I mark those areas with a larger danger radius for autodrive. However, I noticed there isn't a way to view the autodrive exclusion radius of notes marked as dangerous. 

### Solution you would like.

As a simple implementation, it would be helpful to have the danger radius listed on map notes, available on hovering over them. However, a more complete solution could display the danger radius when looking at the list of notes. My idea for this is to add "DANGEROUS AREA (X)" after the note's description, where X is the radius of autodrive exclusion. This would also make it easier to search for dangerous notes (e.g. "dangerous" or "4"). See Figure 2 for my mock-up in "Additional context". 

### Describe alternatives you have considered.

Instead of adding "DANGEROUS AREA (X)" to a note's description, it might be more elegant to add a column to the list of notes for danger. See Figure 3 for my mock-up of this in "Additional context". 

Another alternative idea is to add a map overlay layer that highlights overmap tiles marked as dangerous by notes. This would also help with the player visualization of available autodrive paths, instead of wondering why autodrive isn't working when there isn't a valid path due to danger and other obstacles. See Figure 4 for my mock-up in "Additional context". 

### Additional context

_Figure 1. The current map notes list._
![Screenshot (344)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/be2c1ecb-69b5-4310-a507-6fb03f4ed147)

_Figure 2. A mock-up that includes the danger radius with the notes._
![Screenshot (343)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/5cc444f1-e5c0-4557-aa78-d316ae7cb633)

_Figure 3. An alternative layout for displaying the danger radius._
![Screenshot (345)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/0f81635d-e4df-470c-8b78-56d52ec40644)

_Figure 4. A map overlay for dangerous areas._
![Screenshot (346)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/844f7b5e-08d0-4325-a766-a565df61a7e0)

**Comment by nornagon** [comment]
Working on this a bit and found a few other bugs to fix.

- #71628
- #71640
- #71641
- #71642
