### ISSUE TITLE
[Mind Over Matter] Fountain of Flame Starts at Range Self

### ISSUE THREAD

**Issue by NthTech** [CleverRaven/Cataclysm-DDA#71572]
### Describe the bug

When creating a new character with the default survivor profession, the Newly-Awakened Pyrokinetic background, and no other changes, the Fountain of Flames spell you start with has a range of self. This renders it useless until you have spammed it enough times to level it up to a point where it has a range of 1.

### Attach save file

[TestWorld-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14186615/TestWorld-trimmed.tar.gz)

### Steps to reproduce

1. Make a character with the Newly-Awakened Pyrokinetic background
2. Use Fountain of Flames

### Expected behavior

Fountain of Flames has a usable range from the outset.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 3eae23b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

I also noticed that it has a maximum range of 4 when I made a debug character to see what how the range changed with rank, but I'm unsure if that's a bug to be mention here or a balancing discussion to be addressed as a separate issue.

**Comment by NthTech** [comment]
What is nether attunement? Is it related to the random messages you sometimes get while concentrating on powers, or is it some other thing entirely? Is there an in-game way to learn more about the feature?

**Comment by Standing-Storm** [comment]
There are snippets of old research you can find related to it, but there isn't a help topic about it or anything.

<details>
  <summary>Exactly what it does</summary>
  
 Higher Nether Attunement increases basically everything about your powers, range, damage, duration, etc., but the higher your Nether Attunement, the more chance you have of side effects when using your powers.
</details>
