### ISSUE TITLE
Translation error. Russian language

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71586]
### Describe the bug

The Honeymooners quest. Confusion over the translation of engagement/wedding ring.  

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

### Additional context

```
msgid "Get two wedding rings for Julian."
msgstr "Достаньте два обручальных кольца для Джулиана."
...
msgid "Get two wedding rings."
msgstr "Достать два обручальных кольца."
```

wedding = обручальных 
I assume it must be "свадебных".

```
msgid "wedding ring"
msgstr[0] "свадебное кольцо"
...
msgid "engagement ring"
msgstr[0] "обручальное кольцо"
```

**Comment by Cenness** [comment]
Looks like translation is managed and is updated by a separate project, see this readme - https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/TRANSLATING.md

**Comment by RenechCDDA** [comment]
Correct, if there is an issue with a language's translation it needs to be addressed on Transifex. There is nothing we can do for you here.
