### ISSUE TITLE
Make "Cut Metal" a pauseable task.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#71588]
### Is your feature request related to a problem? Please describe.

I have suggested this several months ago, and I think it's still a valid suggestion. Cutting metal's progress should be saved. When you saw metal bars, stopping halfway do not make the bars magically restore themselves.

### Solution you would like.

Make cut metal action a pause-able task. We did this with digging pits a long time ago.

### Describe alternatives you have considered.

None

**Comment by RenechCDDA** [comment]
No need to repeatedly post suggestions, closed issues are still considered.
