### ISSUE TITLE
Reducing the width of vehicules and thus roads, by putting their side mirror inside their body

### ISSUE THREAD

**Issue by Vilab-unavailable** [CleverRaven/Cataclysm-DDA#71592]
### Is your feature request related to a problem? Please describe.

I am always frustrated when i see the huge amount of tiles taken by roads compared to everything else, and when my character bump into a vehicules's side mirrors while running away from Zombies.

### Solution you would like.

Putting the side mirrors inside the body of vehicules instead of hanging beyond it would reduce the collidable width of all vehicules by two tiles ( 28 to 40% width savings ).

The basic roads could then be made 3 to 4 tiles thinner without reducing drivability.

### Describe alternatives you have considered.

Ignore it.

### Additional context

CDDA is limited due to performances and playability reasons to a maximum number of viewable tiles, hence tiles are valuable.

Using tiles on unnecessary visually accurate features ( side mirror hanging out of the body of vehicules ) thus causing the need for massively enlarged basic roads is a waste of ressources that also make the game visually uglier.

The tiles saving allowed by thinner vehicules and basic roads could either be used for more elaborate roads, or to make denser and more realistic city blocks.

**Comment by AnotherSeawhite** [comment]
Inboard mirror, which functions exactly like wing mirrors, allows you to install a mirror onto a windshield. But for some reason, only one vehicle has it, which is named `Electrical Locomotive`. Though you can install it by your own with a hand mirror.

Regarding the issue, I think it'd be better for wing mirror's install location to be 'on a door' instead of functioning like a comically large mirror structure.

**Comment by nornagon** [comment]
Roads are crazy huge in real life. I don't think CDDA gets it dramatically wrong. Especially when you take into account that the CDDA road tiles include the sidewalk

<img width="966" alt="Screenshot 2024-02-09 at 22 38 20" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/172800/254f044c-d45e-49bc-a921-cf062c20115f">

Above is from a random residential street in [Athol, MA](https://www.google.com/maps/@42.5982091,-72.2253112,18.99z?entry=ttu). Highways are much wider.
