### ISSUE TITLE
Reloading most gun should take way more than 100 "moves"

### ISSUE THREAD

**Issue by Vilab-unavailable** [CleverRaven/Cataclysm-DDA#71596]
### Is your feature request related to a problem? Please describe.

I am somewhat frustrated that reloading a gun with a magazine is extremely quick in game ( most guns have a reload time of 100 moves ).

This nearly instantaneous reloading compares very poorly to the move cost of actually firing the weapon (usually 160+ for regular aiming, which has terrible hit chance ), and make sidearms and melee weapons completely unnecessary as long as you have filled magazines on hands.

### Solution you would like.

The basic move cost of reloading a gun should be much higher ( 400 - 800 ? ) so that high capacity magazine matter and sidearms have some actual valid uses.

An additionnal prompt while reloading asking what to do with the expended magazine ( drop or store ) in order to have an option to reduce move cost.

### Describe alternatives you have considered.

The new move cost may be artifficialy reduced compared to IRL due to the balance issue of in game distance compression.

### Additional context

requires editing the basic value of reload move cost in CDDA\data\json\items\classes\gun per "basic gun type"

and then modifying by a similar factor every single gun who benefit from an overwrited reload_time in CCDA\json\items\guns\ every caliber

**Comment by Procyonae** [comment]
Is it not currently taking into account the cost to get your mags out of where they're being kept? 100 move cost on top of that doesn't seem unreasonable for some guns.

**Comment by Vilab-unavailable** [comment]
> Is it not currently taking into account the cost to get your mags out of where they're being kept? 100 move cost on top of that doesn't seem unreasonable for some guns.

I think it does, but when you have your magazines stored in relatively quick access pockets it is still extremely quick.

**Comment by KeremBabaG** [comment]
> but when you have your magazines stored in relatively quick access pockets it is still extremely quick.

so it's reasonable?

**Comment by Vilab-unavailable** [comment]
> > but when you have your magazines stored in relatively quick access pockets it is still extremely quick.
> 
> so it's reasonable?

Getting the expended mag out, putting it into your chest ammo pocket, getting the new mag out, putting it in, cocking the weapon

is three time faster than reading it, faster than aiming and firing  at a target 3 tiles ( meters ? ) away

Isn't 100 moves meant to be arround 1second ? doesn't higher skill level reduce reload time even lower ?


Sure balance is a thing in CDDA, especially due to the distance compression, but i think super-fast reload time make it way worse.

Having an empty magazine should be THE moment of vulnerability for the shooter, both for realism and gameplay reasons. This is  when one is forced to run away, or to drop their rifle and grab their sidearm or hatchet.

Currently, the bottleneck of gun firepower isn't the number of rounds in a magazine, but the total numbers of available magazine because it is as fast to fire 28 rounds out of two 15 rounds mags than to fire 29 from a 30 rounds one

**Comment by Procyonae** [comment]
It should probably ask you what to do with the old mag so you can choose whether to pay time to store it or just to drop it, again though that time should already be factored in in the C++ if it's not that's a bug

**Comment by fairyarmadillo** [comment]
Depending on the gun, unloading and reloading can be done in 2-4 seconds by skilled operators: https://www.youtube.com/watch?v=2Q-QVBQVYTA

It should probably scale with skill in the appropriate gun, with the above example being something like the maximum.

**Comment by KnifeFightBears** [comment]
Can we _not_ have a dialog for what to do with the magazine when you reload, or at least an option in the interface to do it automatically? This sounds extremely, extremely tedious

**Comment by Procyonae** [comment]
That's fair I don't tend to use guns except when they're necessary

**Comment by kevingranade** [comment]
There might be room to tune it a bit,  but you haven't made a case for it. The 1s you're talking about is just the "eject the old magazine and insert the new one" time,  it doesn't count time to retrieve a new magazine,  stash the old magazine if desired, or the proceeding and following shots and aim time.  Speaking of,  one of the big costs should be that reloading will reset your aiming for most shooters, the kind of very practiced tactical reload without changing your aim point demonstrated in fairyarmadillo's video would be the exception rather than the rule.

More fundamentally, you're asserting that reloads should have very high impact, but you're skipping over the step of making a case for why they should be. If reloading is slow it should be impaction,  but is it really that slow?

Side note,  instead of a prompt asking what you want to do with an empty magazine,  we could have a seperate keybind for "reload and drop the old magazine" vs "reload and stash the old magazine".

**Comment by Vilab-unavailable** [comment]
Stashing in/out magazines does indeed add to the practical reloading time, but unless those magazine are stashed in a backpack they still dont add much time, thus those extremely uncommon IRL <2s reloading are the 0 skill standard in cdda. 

Hence the reloading time of swapping mags in cdda should be increased because it is currently unrealistically optimistic.


There is also the issues that such fast practical reload in cdda are usually much faster than aiming and firing once again, thus making magazine size and melee backups quite irrelevant because a character can deliver nearly as much DPS with 3x10rounds magazines as with 1x30rounds one.

Hence the reloading time of swapping mags in cdda should be increased for the sake of "balance" and common sense.


In my local copy i added a basic reload time of 300 moves to "base_gun" in cdda/data/json/items/classes/gun in order to have a trickling effect on most guns.

and then went in items/gun in order to tweak and increase the very many overwrites by a similar amount.

3s ( or 1.5s at skill 10 according to comments on flintlock gun reload time ) + arround 1s for the various stashings still look quite optimistic to me, but looks "balanced" in the compressed distance environment of cdda and make reloading impactfull yet not criplling in game.

**Comment by KnifeFightBears** [comment]
https://www.military.com/video/forces/marine-corps/marine-speed-reloads-m4/1107745018001 The marine in this video spends substantially less than one half of one second reloading an M4. It does not appear to have been a great effort on his part to set this up. He's even doing it from a standing position. 

You press a button to drop the mag and you slide in the metal box that is shaped smaller than the magwell and locks in with a click. This is not a complicated action and should not take a lot of time if you know how to do it at all. Maybe 0 skill characters could get a one-time penalty the first time they reload where it takes 3 seconds?

**Comment by kevingranade** [comment]
You're still ignoring the critical point here,  which is establishing how long it should take based on irl precedents.
Closing since you don't seem inclined to do so.
