### ISSUE TITLE
[Magiclysm] Fire Bolt

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#71606]
### Is your feature request related to a problem? Please describe.

We have Magic Missile and Fireball, but there's no Firebolt, which is seen in most RPG games (especially games based on DnD.)

### Solution you would like.

Adding Fire Bolt spell for Magus. (or Kelvinist?)

### Describe alternatives you have considered.

Adding `thrown_damage` on finger firelighter, but that would function in weird way.

### Additional context

IGNIS

**Comment by Standing-Storm** [comment]
There are Point Flare or Nova Flare, which do something similar--unless you mean a line of fire?

**Comment by AnotherSeawhite** [comment]
Can I ask how Point Flare and Nova Flare work? Does the caster heat the specific target, or does the caster 'throw' or anything to cause the heat?

**Comment by MNG-cataclysm** [comment]
> Can I ask how Point Flare and Nova Flare work? Does the caster heat the specific target, or does the caster 'throw' or anything to cause the heat?

From what I undertsand, Point and Nova Flare is the creation of heat at the target point, rather than throwing a projectile. This allows the spell to pass through walls.

**Comment by AnotherSeawhite** [comment]
Thanks for telling, we continued this discussion in Devcord, and Storm told me that it's going to be in the next list of spells.

**Comment by AnotherSeawhite** [comment]
#71739, closing this as completed
