### ISSUE TITLE
ice-cleats! also known as shoe spikes!

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#71615]
### Is your feature request related to a problem? Please describe.

Boomers are nasty, they spew slime that is makes it easy to fall down. 

Fortunately, we humans have invented shoe spikes (ice cleats), that come in various sizes, [very small](https://www.prisma.fi/tuotteet/100027008/snow-fox-pito-liukueste-jalkineeseen-l-41-44-100027008) (for pedestrian stuff)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56438982/af36e7a8-b981-4632-ad9f-abb74d112d37)

and very large, for mountains (That's the one I'm NOT going to add).

### Solution you would like.

See related PR #71617

Just like that rare 'BELTED` rollerblades thingy I've added in #71563 , this is also belted, and (based on my own experience in Finland) should add almost no encumberance. Also, one size fits all.

This thing, when worn, should drastically reduce chances of slipping on the bile. 

As a downside, walking must generate more noise, especially on solid surfaces. Idk if this is easily doable right now.

This issue tracks the addition of this footwear in game.

### Describe alternatives you have considered.

Avoiding all contact with boomers (unrealistic IRL).

**Comment by fairyarmadillo** [comment]
I'm not sure these would work. Cleats dig into ice to hold you steady. There's nothing to dig into on a slippery sidewalk.

**Comment by tornikeo** [comment]
@fairyarmadillo hmm. As I understand it, slime isn't solid. So when you step in it, it kinda moves away from your foot a bit. If you have spikes on your shoes, those spikes _should_ make contact with the asphalt, keeping your foot in-place. 

Am I missing something here?

**Comment by PGR-14** [comment]
Perhaps it'd also give a speed bonus (or nullifier) when on certain terrain? Or remove the unstable debuff (Does it even do anything?).

**Comment by kevingranade** [comment]
Walking on hard surfaces in cleats is definitely not zero encumbrance,  they significantly impede your effective traction.
