### ISSUE TITLE
Bionic limbs?

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#71618]
### Is your feature request related to a problem? Please describe.

Saw the prothesis mod, & thought it'd be a good idea to have bionic replacement limbs

### Solution you would like.

There could be a few different ones, mainly bionic limbs that work about as well as their real counterpart (Except needing to use power, & can be "deactivated" w/ an electrical shock) but also some specialized ones, like a sword arm, shotgun arm (Maybe a variant of the CBM?), or even multi arms (2 pairs of arms, kind of like insect limbs)

**Comment by IdleSol** [comment]
Monomolecular Blade CBM https://cdda-guide.nornagon.net/item/bio_blade
Shotgun Arm CBM https://cdda-guide.nornagon.net/item/bio_shotgun

#71550 Things we still need to do for Bionic Limbs
