### ISSUE TITLE
Extreme lag after zone sorting

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#71626]
### Describe the bug

Installed a new fridge, designated the location in a zone.  Went to auto-sort with the zones and the game got stuck for a few minutes.  When I hit to cancel the auto-sort I've been stuck with a lag of about 3-5 seconds to move one tile.  The sound plays immediately, but nothing changes graphically for that duration.

After closing and re-opening the game, I can no longer move at all, or the game will freeze.

If I use debug teleport to teleport a few map tiles away I can escape and the game plays like normal.

If I try to go back to the base, it freezes indefinitely as soon as the base enters the reality bubble.

I didn't think about it previously, but I had for the first time given three NPCs crafting tasks.  One of them burst into an asthma attack prior the freezing.

### Attach save file

[Lakewood Shores-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14217189/Lakewood.Shores-trimmed.tar.gz)

### Steps to reproduce

Try to walk around in the provided save file.

### Expected behavior

The game shouldn't lag this hard, especially when it was running fine in this area previously.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: a5db177 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungus [No_Fungus]
]

**Comment by andrei8l** [comment]
Duplicate of #70530, and it's now also slightly exacerbated by the changes to `item::stacks_with()` from #70766

**Comment by ANickelN** [comment]
So right now the only fix is to do what?  To debug kill the NPC causing the freeze?

**Comment by andrei8l** [comment]
Apply akrieger's [patch](https://github.com/CleverRaven/Cataclysm-DDA/issues/70530#issuecomment-1874327337) locally, or tell the NPCs to stop crafting.
