### ISSUE TITLE
[Magiclysm] Owlbear egg issues

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71625]
### Describe the bug

There's a couple of issues. The major one is that the rotten status of the owlbear egg doesn't transfer over to the owlbear yolk when it's crafted. The minor one is that there don't seem to be any uses for the yolk, leaving me to drink 2L of raw egg, which sounds truly atrocious. I could be wrong about the edible options for it, but if there are any, they're locked far and away behind some skill, which I wouldn't expect for a simple scramble. At the very least it'd be good to have them usable in all the regular recipes?

### Attach save file

N/A

### Steps to reproduce

Crack a rotten egg, find fresh egg yolks.

### Expected behavior

Rotten yolks from rotten eggs, or perhaps baby owlbear chicks/cubs.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 3eae23b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by NthTech** [comment]
I didn't have any issues using owlbear egg yolks as a cooking ingredient. 1 yolk acts as a substitute for 1 bird egg in recipes, and I was able to scramble the egg just fine.

I did experience the rotten egg breaking into fresh yolk though. I agree that it should probably grow into a baby owlbear, or at the very least produce rotten yolks when breaking a rotten egg.

Tested on 74d1b75, with only magiclysm, no_npc_food, personal_portal_storms, and no_fungal_growth loaded.

**Comment by MrHrulgin** [comment]
Interesting. For me, it says that there's nothing I can do with the yolk, and when I search for recipes that use it there aren't any.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/9c19a59f-de0c-44c6-9c47-7b22d4825d57)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/617eed7d-7c53-41bb-b507-f2ad38843db9)

**Comment by NthTech** [comment]
There's definitely some other issue causing the missing recipe. The change that added owlbear yolk as a component is over a year old: https://github.com/CleverRaven/Cataclysm-DDA/commit/be7e4b65fdc3b9844f44cfff756dc9913bd67a33
