### ISSUE TITLE
Enemy to balance bag dropping

### ISSUE THREAD

**Issue by Jkesler22** [CleverRaven/Cataclysm-DDA#71627]
### Is your feature request related to a problem? Please describe.

I have been playing for several years, and one thing I think has always been missing is the threat of the biggest trolls on earth, thieves.  It can get a little too easy with all the map markers and sorting and zone options and mobile base storages to keep all your stuff safe and secure.  There are really no enemies that combat this.

### Solution you would like.

With the overhaul being done to NPC's and factions, we need new variations of A-hole-grade bandits, ferals, and wildlife.  Feral thieves that will follow from a distance and try to stay out of view.  When you set your bag down to pull out your weapon, they try to steal your bag!  Bandits that will try to rob you is one thing, but a bandit who spots where you live, and brings friends to raid you while you are out.  Even little jerk dinos or rodents that try to swipe your food from your bag while you are not looking!

### Describe alternatives you have considered.

There can be different level of competence/awareness/sight radius depending on the evolution level!  Won't that be FUN!?!?!

### Additional context

I truly hate myself for thinking of this.  Please don't.
EDIT: I suck at spelling...

**Comment by Zireael07** [comment]
Monsters/NPCs that take items have been suggested multiple times. I don't think they are going to happen because they increase tedium/encourage having multiple copies of an item

**Comment by Cenness** [comment]
For a proper sim it would require calculating multiple reality bubbles. That would kill and dismember performance.

I guess you can bypass full sim with another kind of rot, but how would it interact with a fully walled base, traps/turrets and npcs or whatever have you? What if someone place their minibase/boxes in close proximity (or within confines) to an existing npc base - like exodii base, or smith's couple?

>thieves that will follow from a distance and try to stay out of view

Nice idea for a lieutenant mini boss, though.

**Comment by MNG-cataclysm** [comment]
I suppose that the assassin EOC's could be used to randomly summon a thief that homes in on your location, loots stuff, and then leaves. Might make for a nice survivor-on-survivor interaction and illustrate the desperation of people post-apocalypse.

**Comment by Jkesler22** [comment]
> they increase tedium/encourage having multiple copies of an item

But that is kind of the point to the idea.  Take care of your stuff.  It's not really realistic to walk around the apocalypse with a reinforced box of all your belongings in your hands, in my humble opinion.

> That would kill and dismember performance.

This is my biggest concern with the idea also.  The slowdown that can happen from NPC's searching is getting better and more optimized over time, but it would probably incur some processing time when nearby, which could also be a tell that something is amiss.

> how would it interact with a fully walled base, traps/turrets and npcs or whatever have you?

If it were me, and I was scoping out a base that was this well defended, I might just say it's not worth it.  Someone who is not thinking straight or is just "dumber" or less evolved, might not even notice, just start trying to get in and get shot.  The point is not to get around every defense.  It's to ensure there ARE defenses.
