### ISSUE TITLE
[MoM] Concentrating on Coagulation while you sleep

### ISSUE THREAD

**Issue by rty275** [CleverRaven/Cataclysm-DDA#71621]
### Describe the bug

The Coagulation power doesn't deactivate on going to sleep like all the other concentration powers does. I suppose it's not impossible that this is intentional, but if any power could be concentrated on 24/7, Coagulation is not the one I would expect.

### Attach save file

[TestingMoM-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14213409/TestingMoM-trimmed.tar.gz)

### Steps to reproduce

1. Open save
2. Check status menu, take note of four powers being concentrated on
3. Go to sleep
4. Check status menu when you wake, see Coagulation still active

### Expected behavior

I expected that it would turn off overnight like every other concentration power I've experienced. Admittedly, that's only a couple trees so far, so it's possible that there are more like this, but it did stick out to me.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 2013584 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter]
]

**Comment by Standing-Storm** [comment]
This will be fixed by #71437

**Comment by rty275** [comment]
Oh I hadn't realized! Cheers!
