### ISSUE TITLE
Error in the name of the mobs. Mob_name:none

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71634]
### Describe the bug

While traveling, came across a strange display of the monster's name. The name is displayed with the ending ":нет". See screenshot.

"нет" means no, maybe none

### Attach save file

[Пис-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14220232/-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/a48cdc8f-7c73-4654-80c6-21a12de283ef)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 2013584 [64-bit]
- Graphics Version: Tiles
- Game Language: <s>Системный язык []</s> Ru
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    Характеристики за убийства [stats_through_kills]
]

### Additional context

Language switch, turns "оса: нет" to "wasp: нет"

**Comment by andrei8l** [comment]
/confirmed `НЕТ` was serialized as the monsters' unique name. Best guess is that it was caused by this
https://github.com/CleverRaven/Cataclysm-DDA/blob/b1b50ff415361cf039f5fa51bb1b27976eca761d/src/mapgen.cpp#L2429
which translates `NONE`, which in turns fails this check here

https://github.com/CleverRaven/Cataclysm-DDA/blob/b1b50ff415361cf039f5fa51bb1b27976eca761d/src/map.cpp#L8840-L8842
and gets turned into a unique name

simplest solution is to probably just check for `_( "NONE" )`

**Comment by IdleSol** [comment]
On the English locale, everything is normal (or lucky not to meet).
On the Russian local, problems with monsters that are created during random encounters(?).  Road blockade (both versions), wasp nests, exodii, and so on.

**Steps to reproduce**
1. Create a world, a character
2. debug menu / map / spawn map extra / mx_exocrash_1 (or mx_roadblock) = m+m+f (6)
3. skip a few moves to make the monsters appear
4. look at the monster's name in the overview menu (V)
5. Change to the Russian locale
6. Repeat steps 2...4

**Comment by BjoHart** [comment]
German translation is problematic to

**Comment by IdleSol** [comment]
It's too early to close the topic. The problem's not solved

https://github.com/CleverRaven/Cataclysm-DDA/pull/71846#issuecomment-1952914231
