### ISSUE TITLE
Barbaran Montante can disarm talons mutation

### ISSUE THREAD

**Issue by Coach-mdl** [CleverRaven/Cataclysm-DDA#71647]
### Describe the bug

Barbaran Montante can disarm an opponents talon mutation when Swift Atajo is triggered. Likely happens to other melee based mutations too.

### Attach save file

N/A

### Steps to reproduce

Using a fire axe (other compatible weapons should work too) trigger swift Atajo on an opponent with claws or talons.

### Expected behavior

Melee weapons get disarmed, claw remain.

### Versions and configuration

Windows 10
Tiles-sounds-x64-2024-02-02-0710

**Comment by fairyarmadillo** [comment]
Duplicate of #67958
