### ISSUE TITLE
Use batch disassemble dialog for batch crafting

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#71656]
### Is your feature request related to a problem? Please describe.

I want to craft ethanol. For that I need a lot of mixed alcohol. A have a lot of wines and other drinks, literally hundreds of liters. But current batch crafting ui limits what is basically a renaming and pouring from one container to another to a 50, i.e 12.5 liters for one craft, therefore making this kind of recipes really tedious.

### Solution you would like.

Reuse this dialog from batch disassembly:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9906246/383f5805-9820-4f1a-a5b3-8d6e3217be01)

### Describe alternatives you have considered.

Continue to spam "recraft last recipe" action

**Comment by XygenSS** [comment]
Can't you do 'craft as long as possible' > '(b)atch craft ethanol'?

**Comment by Cenness** [comment]
I can, but it just automates spamming recraft and have same interrupts at 12.5 liters.
