### ISSUE TITLE
Missing roofs on some labs

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#71658]
### Describe the bug

While standing at a bridge you can look inside lab

### Attach save file

[Higher Ground-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14229620/Higher.Ground-trimmed.tar.gz)

### Steps to reproduce

1. Elevate yourself near structure
2. Aim down
3. You can see inside
4. They can see you too

### Expected behavior

Enclosed spaces should be hidden from an outside observer without clairvoyance

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9906246/8e4f2c5e-b4bc-4911-b750-c958ac01a249)

Same result with aiming up:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9906246/499e1f5b-af29-42cd-acda-9ed678599998)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: ab8d84c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

You can't see underground parts.

**Comment by andrei8l** [comment]
Don't look like a vision issue. That lab generated without a roof, but it gets added when the save is loaded

**Comment by GuardianDll** [comment]
can't reproduce it either, ab8d84c 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/330ce4d0-30cd-467b-9801-6c154ca2bda1)

**Comment by Cenness** [comment]
Save for second screen [Higher Ground-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14229693/Higher.Ground-trimmed.tar.gz)
But it wouldn't help reproducing it - wh disappears after loading here too.

**Comment by Cenness** [comment]
Can't reproduce it with ordinary houses also. Probably just missing roofs on first load.
