### ISSUE TITLE
Gaining experience while driving

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71657]
### Describe the bug

I have a suspicion that the experience gained in the vehicles skill depends on the mode of travel. I mean manual movement and autodrive. Which is kind of weird.

### Attach save file

N/A

### Steps to reproduce

1. Default world and character (skill vehicle = 0)
2. Find a long straight road (40-50 map tiles)
3. Create transportation (checked on bike, athletics disabled)
4. Save the game
5. Start driving in manual mode (19 km/h) and continue until you get level 1.
6. Memorize the distance covered
7. Exit without saving
8. Load a save
9. Start the movement by auto-traveling and continue until you get level 1.
10. Compare the distances traveled.

### Expected behavior

The same amount of experience, regardless of the way you drive your vehicle.

### Screenshots

![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/1b266816-13f1-462f-a900-04efcb2e016f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 07c9b29 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]

### Additional context

Not that it matters. But the higher the level, the longer it takes to pump.

**Comment by Inglonias** [comment]
This would make sense if experience gain is based on time rather than distance, which I suspect it is.

**Comment by PatrikLundell** [comment]
As far as I know training is based on time, so when I need to train a skill or proficiency I try to select recipes that take a long time and uses few important resources for training when I don't have anything useful to craft.

That's no excuse for a discrepancy between manual and auto, though.

**Comment by Inglonias** [comment]
You're right. If time is calculated different when autopiloting a vehicle, we need to account for that.
