### ISSUE TITLE
Game crashes when attempting to open diary/achievements/scores

### ISSUE THREAD

**Issue by mini-bomba** [CleverRaven/Cataclysm-DDA#71659]
### Describe the bug

As described in the title: pressing the key to open achievements causes an immediate crash.

### Attach save file

[Megler-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14229689/Megler-trimmed.tar.gz)

### Steps to reproduce

1. Load the game on the provided save (or even a new save, as these seem to be affected as well)
2. Press `)` (or the key to open diary/achievements/scores, if you've changed it)
3. Game crashes

### Expected behavior

The diary opens and is fully functional

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-7307-g[ab8d84c5fe](https://github.com/CleverRaven/Cataclysm-DDA/commit/ab8d84c5fe) [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

le crash log, from a new save: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14229698/crash.log)
log from the provided save: [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14229702/crash.log) (likely the same, but attaching anyways)

**Comment by andrei8l** [comment]
/confirmed

This std::clamp is weird
https://github.com/CleverRaven/Cataclysm-DDA/blob/c6f63976b3dac61b37ece26a52c09df048c72417/src/diary_ui.cpp#L301
it should be `std::clamp( max.y / 2 - 4, 3, 7 )`

I thought we already fixed this but I can't find the original bug report ???

**Comment by mini-bomba** [comment]
I've found issue #71508 and the corresponding fix PR #71562, but these seem a bit different, since the diary appears to open in the posted screenshots. Here the game crashes before the diary renders

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.G-12522.
![изображение](https://github.com/user-attachments/assets/6beb8fd6-7a97-4522-9b96-ea729be35c21)
