### ISSUE TITLE
Containers with both aged & unaged food don't display properly in the advanced inventory manager

### ISSUE THREAD

**Issue by Kachow451** [CleverRaven/Cataclysm-DDA#71667]
### Describe the bug

As title, objects may fail to display if stored with aged (rotten/old) goods, and may not be interacted with individually. Issue applies to containers full of the same foodstuff and containers with variable contents. I've tested this with different kinds of food, in different environments (floor vs freezer vs fridge vs box), and at different temperatures. Below is a file documenting the results of _some_ of these tests.

Foodstuffs within containers do not display in AIM when filtered for, but rather the container itself. I assume this is somewhat intended, as containers in AIM can't be collapsed. However, this means that objects can evade your filtering attempts, appearing when you do not want them or not appearing when you require them. 

e.g. searching for "c:food,-rotten" will show all containers not _entirely_ filled with rotten food. It'll remove individual rotten objects, but containers with _some_ rotten food will still display, and you will not be notified of which. Likewise, regular food in a spoiling container will cause the entire container to disappear when searching for "--rotten".

Food in mixed containers, that is, containers that have different food types and spoilage, also seem to be unsearchable. If you search for their item name, you will not find it, presumably because containers display uncollapsed in AIM (and simply "Food" when carrying different contents).

-----
```
TEST A: OLD & ROTTEN
---
Units: 7 (2 Cold & Old, 5 Cold & Rotten)
Container: Paper Wrapper, Plastic Bag
Filters Used: "--rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No*

TEST B: ROTTEN
---
Units: 5 (Cold & Rotten)
Container: Paper Wrapper
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten", "--old"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: Yes

TEST C: COLD & ROTTEN
---
Units: 7 (2 Cold, 5 Cold & Rotten)
Container: Paper Wrapper
Filters Used: "--rotten", "c:food,--rotten", "butter", "rotten", "cold"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Blue Tag)

TEST D: NORMAL & ROTTEN
---
Units: 7 (2 Normal, 2 Cold & Rotten)
Container: Paper Wrapper, Plastic Bag
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Brown Tag)

TEST E: NORMAL & ROTTEN
---
Units: 2 (1 Normal, 1 Cold & Rotten)
Container: Paper Wrapper, Plastic Bag
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Brown Tag)

TEST F: NORMAL & OLD & ROTTEN
---
Units: 3 (1 Normal, 1 Cold & Old, 1 Cold & Rotten)
Container: Paper Wrapper
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Brown Tag)

TEST G: NORMAL & OLD
---
Units: 2 (1 Normal, 1 Cold & Old)
Container: Paper Wrapper
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Brown Tag)

TEST H: FROZEN & OLD, MULTIPLE FOODS
---
Units: 2 (1 Cold & Old Butter, 1 Frozen Cracklins)
Container: Paper Wrapper
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Yellow Tag)

TEST I: FROZEN & ROTTEN, MULTIPLE FOODS
---
Units: 2 (1 Cold & Rotten Butter, 1 Frozen Cracklins)
Container: Plastic Bag
Filters Used: "--rotten", "c:food,--rotten", "--butter", "rotten"
Filterable In Inventory?: Yes
Filterable In Pickup?: Yes
Filterable In AIM?: No* (Brown Tag)
```

### Attach save file

[Hotchkiss-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14231124/Hotchkiss-trimmed.tar.gz)

### Steps to reproduce

1. Find a container of your choice (I tested using a plastic bag & paper wrapper).
2. Place at least two units of food into your container, one aged (old or rotten) and one unaged.
3. Enter the Advanced Inventory Manager, targeting the space or storage unit (freezer, box, inventory, etc.) where the food is located.
4. Attempt to filter for either object, by name or tag. 

### Expected behavior

Items display when filtered for as they fit the search query's criteria. 

A fridge with numerous rotting objects, including a singular apple in a bag of 30, should display all matching objects when filtered for. Currently, AIM treats that bag as nonexistent.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3007 (23H2)
- Game Version: ab8d84c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks]
]

### Additional context

I have no idea what could be causing this, but I can only imagine it has something to do with how AIM handles containers. It also most likely applies to other item types or containers, like with medicare, but don't quote me. More testing required.

Also, while yes, I haven't tested how this interacts with zones, and that zones are _probably_ the ultimate solution to organizing, this still applies to anyone who either:

A) doesn't want to use zones 
B) doesn't know they exist
C) needs to go through their storage/fridge by hand

This problem makes an already somewhat tedious task in any video game even MORE annoying. What's odd about this, as well, is that everything works appropriately OUTSIDE of AIM! In the inventory, on item pickup, the whole shebang. This issue _only seems to occur_ in AIM. I also know that you can enter containers via AIM by hitting c, but that doesn't solve the issue so much as it gives you a tool for dealing with it. Even then, you can't filter for containers with rotten goods properly! Filtering for aged goods will rarely give you hits since it'll likely be mixed up with the unspoilt food it came with. 

A solution? I'm not entirely sure. Could you display all objects individually if they match the search query? Allow collapsible containers in AIM? Maybe "-rotten" should __literally__ exclude it from searches, displaying all other objects within its container—a 32-item paper wrapper filled with 31 frozen cheeses and one rotten cheese would become a 31-item container. Would transferring it cause the rotten item (or non-rotten items, vice versa) to be left behind? Maybe. It seems appropriate that when searching for a particular object, it displays, rather than having to go on an easter egg hunt for it.

I wish I knew how to fix it, but I don't. Still, it's good to bring it up, right?

*Interestingly, the container itself will usually appear if it's searched for... just not when looking for rotten food. There's also a weird thing with hierarchy? When regular, cold butter was searched for along with the rotten stuff, it showed the paper wrapper title in blue. When I did the same thing but with regular, baseline butter, the paper wrapper title was brown instead. The test log has some more examples, but I'm unsure what determines the colour. You would think it would be the stage of decay or which item is more numerous, but it think it has to do with the order in which objects are inserted.

**Comment by andrei8l** [comment]
So to clarify, you want the AIM to filter inside the contents too, just like the inventory UI? I think that would cause more problems than it solves, given that the AIM can't display contents.

**Comment by Kachow451** [comment]
> So to clarify, you want the AIM to filter inside the containers too, just like the inventory UI? I think that would cause more problems than it solves, given that the AIM can't display contents.

I'd like it to be consistent, to be honest. It's frustrating that I sometimes have to dig through every container I just looted to remove rotting items that've stuck around. Being able to _more easily_ and _more accurately_ deal with that would be nice. Aged items appearing/not appearing despite filters is especially egregious, IMO: I can't even trust what I'm being shown. 

Is there a reason why AIM can't display contents? I'm not sure why it'd be unreasonable, but I'm also not super acquainted with CDDA's underbelly, so I can guess some reasons why it's the case. At the very least, rewriting AIM to fit the rest of the UI is unnecessary: it is certainly able to understand that some containers have multiple spoilage levels. I'd be happy if AIM received the "--rotten" filter and returned any container with at least one rotten item.

**Comment by andrei8l** [comment]
> Is there a reason why AIM can't display contents? I'm not sure why it'd be unreasonable, but I'm also not super acquainted with CDDA's underbelly, so I can guess some reasons why that's the case

The AIM is an incredible franken-code and major features are not allowed anymore. There have been (AFAIK) 2 different attempts to rewrite it and they were both rejected for being too large so it's pretty much stuck in limbo unless a senior dev takes over (or lets someone else take over, for real this time).

**Comment by Kachow451** [comment]
> > Is there a reason why AIM can't display contents? I'm not sure why it'd be unreasonable, but I'm also not super acquainted with CDDA's underbelly, so I can guess some reasons why that's the case
> 
> The AIM is an incredible franken-code and major features are not allowed anymore. There have been (AFAIK) 2 different attempts to rewrite it and they were both rejected for being too large so it's pretty much stuck in limbo unless a senior dev takes over (or lets someone else take over, for real this time).

Ah, wonderful. There might still be a chance, but yeah, what a pain in the ass. Appreciate the context!
