### ISSUE TITLE
Filled condom in a wallet.

### ISSUE THREAD

**Issue by S0ZDATEL** [CleverRaven/Cataclysm-DDA#71661]
### Describe the bug

One of the zombies dropped a wallet. Inside that wallet was a blue condom, which itself contained a crack pipe and a zipper bag with some crack.
When I took the condom out of the wallet, I found out that I can't put it back in. As soon as I emptied it, I was able to put it into the wallet.

### Attach save file

N/A, since I've already taken it out of the condom in my save.

### Steps to reproduce

A dumb way to reproduce it:
1. Spawn a lot of zombies with debug menu.
2. Kill them with debug menu.
3. Search for wallets containing condoms containing things. If not found, repeat from step 1.

### Expected behavior

If the player can't put a non-empty condom into a wallet, it shouldn't be in there in the first place.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 1949d26 [64-bit]
- Graphics Version: Tiles
- Game Language: Russian [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

I think it's a cool way to hide your drugs. We all love features that originated from bugs. Maybe make it intentional and let the player store their zipper bags full of crack in their wallet?

**Comment by MrHrulgin** [comment]
There's definitely some weirdness regarding how small items are stored in small, flexible containers in zombie inventories. Having your cell phone in the zipper baggie with your crack is generally not advised.

**Comment by ashGlaw** [comment]
My game has issues with this as well. I get a error screen every so often in areas with zombies. The errors mention condoms spawning where they don't fit.

**Comment by TheRafters** [comment]
This happens with any soft container, I often see cigarette packs with cigarettes and a couple other small items like mp3 players as though the pack has scooped up all the small items it could fit at the time of spawn. The white list is still set to cigarettes too which is a sign something is weird. I've seen paper wrappers do similar things as well.

**Comment by ANickelN** [comment]
/confirmed
You can see this happen with multiple different items being put into inappropriate containers on bodies.

**Comment by droe** [comment]
e442936 still affected:

```
 DEBUG    : error: item condom cannot fit into pocket while loading: item is too heavy

 FUNCTION : void item_contents::combine(const item_contents &, const bool, const bool, bool, bool)
 FILE     : src/item_contents.cpp
 LINE     : 736
 VERSION  : cdda-experimental-2024-03-26-1759 e442936
```

caused by:

- `typeid: "corpse", corpse: "mon_civilian_panic"`, containing:
    - clothes
    - `typeid: "wallet_leather"`, containing:
        - coins and cards
        - `typeid: "condom", variant: "condom_pink"`, containing:
            - `typeid: "mp3"`
            - `typeid: "caff_gum"`
            - `typeid: "pockknife"`

**Comment by Brambor** [comment]
#73313 prevents condoms from doing that since they are sealed.

**Comment by SkuliAdams** [comment]
I believe this issue still exists on the 0.H release candidate, as I encountered a similar error in candidate 2024-06-07-1409. #73313 should probably be back-ported.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/25968150/200e464c-84a2-4c04-8c52-b85a9b23612a)
