### ISSUE TITLE
Tileset bug: Rain gutter appears as a pure black square

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#71662]
### Describe the bug

I found a rain gutter that didn't render properly (using UltiCa). 

### Attach save file

[Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14229950/Earth-trimmed.tar.gz)

### Steps to reproduce

I'm not sure what caused this bug, though there was a crater-forming explosion near this gutter. This gutter is part of an urban city block. As can be seen in the screenshot, other rain gutters still rendered properly. 

### Expected behavior

I expected that the rain gutter would appear normal. 

### Screenshots

![Screenshot (356)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/a99477a6-5e50-41ee-a679-99251b975d12)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: ab8d84c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause a crash.

**Comment by RenechCDDA** [comment]
This is indeed a problem with Ultica and not the game in general.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/b8147259-8be9-4151-9e9c-caa7182781a1)

Therefore, it should be reported on the [tileset repo](https://github.com/I-am-Erk/CDDA-Tilesets). Feel free to link back to this report to make it easier.
