### ISSUE TITLE
Lightmap Transparency Weirdness

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71674]
### Describe the bug

I was looking for a solution for #38958 and #33728 and I ran into a couple of bizarre issues which are beyond my coding abilities. I could simply be misunderstanding the code, but I'd like to bring this to more skilled coders' attention if I'm onto something here:

1) The map cache is only ever updated on the next turn. Even when I dropped extra checks to try to make it more instant, it didn't seem to want to catch up until a second or two had passed or I had moved a few tiles. The reason for this is obviously performance, but it screws with some stuff due to the next issue.
2) The map cache only ever uses one vision mode, and it uses it even if you have multiple types of vision at once. As far as I can tell, the reason IR vision can't see through smoke or gas is that the player can't see through these fields with their normal vision, so the map cache simply isn't drawn for those tiles. Trying to add a check to selectively omit IR from field transparency checks results in the player simply seeing normally with full regular vision through smoke. Not ideal.

3) Around line 130 of lightmap.cpp, the code does a lot of work to try to calculate the transparency of a single tile. Specifically, the comments in the header file state:

```
/**
 * Transparency 101:
 * Transparency usually ranges between 0.038 (open air) and 0.38 (regular smoke).
 * The bigger the value, the more opaque it is (less light goes through).
 * To make sense of the specific value:
 * For transparency t, vision becomes "obstructed" (see map::apparent_light_helper) after
 *   ≈ (2.3 / t) consequent tiles of transparency `t`  ( derived from 1 / e^(dist * t) = 0.1 )
 *   e.g. for smoke with effective transparency 0.38  it's 2.3/0.38 ≈ 6 tiles
 *  for clean air with t=0.038  dist = 2.3/0.038 ≈ 60 tiles
 *
 * Note:  LIGHT_TRANSPARENCY_SOLID=0 is a special case (it indicates completely opaque tile)
 * */
```
 
But as far as I can tell, it's not actually working this way. It's certainly doing all that math, but then at the end it simply decides that either a tile is completely opaque, or it is completely transparent. Line 153 contains a todo to make glass reduce light levels. I thought this would be cool as it would make houses look a little creepier on the inside and would make daytime stealth more interesting. I tried several solutions to get this to work and nothing I did had any impact on light's ability to pass through a tile, except that if value ever reached 0, the tile would become completely opaque.

This means that weather's intended effects on visibility may not be working right. Not sure though - fog seems to work, but is it simply reducing the amount of sunlight?

### Attach save file

N/A

### Steps to reproduce

Go into lightmap.cpp and try to add a case for flagged tiles (IE WINDOW) to reduce the value variable inside map::build_transparency_cache(). I'm aware this isn't the ideal solution but it's an easy way to illustrate the point. You should find that any value other than 0 behaves exactly the same as any other.

### Expected behavior

The code and its notes appear to be saying that if `float value` is less than 0.038, then less than full light should pass through that tile. If this is the behavior we want, then it doesn't seem to be working.

If for performance reasons (or some other thing I don't understand) we don't want the above behavior, and we'd be fine with just a bool, isn't this essentially dead code? It's running this all every couple of turns for every single tile in the reality bubble, isn't it? Could we greatly simplify this process to either reduce lag or make it easier to do stuff with the reality bubble?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0.G-7413-gffe747764b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Pinging @andrei8l here because this came up in a PR they were helping me with, and they seem to know this stuff better than me.

**Comment by andrei8l** [comment]
> The map cache is only ever updated on the next turn.

Probably an issue with order of operations and you need to call `map::invalidate_map_cache()` and `map::build_map_cache()` when you want to force an update out of turn.

> The map cache only ever uses one vision mode, and it uses it even if you have multiple types of vision at once

Building separate caches for different vision modes is likely too expensive; it needs to be profiled. But for things like IR, where we only need to have extra vision on certain tiles rather than the whole FOV, we can probably get away with ad-hoc caching.

<details>
<summary>Quick & dirty hack to use the no-fields transparency cache+bresenham  for IR vision</summary>

This won't work in the general case, for example for IR vehicle/monster cameras.

```diff
diff --git a/src/character.cpp b/src/character.cpp
index dfc7c16581..b150375382 100644
--- a/src/character.cpp
+++ b/src/character.cpp
@@ -10637,13 +10637,7 @@ bool Character::sees_with_infrared( const Creature &critter ) const
 
     map &here = get_map();
 
-    if( is_avatar() || critter.is_avatar() ) {
-        // Players should not use map::sees
-        // Likewise, players should not be "looked at" with map::sees, not to break symmetry
-        return here.pl_line_of_sight( critter.pos(), unimpaired_range() );
-    }
-
-    return here.sees( pos(), critter.pos(), unimpaired_range() );
+    return here.sees( pos(), critter.pos(), unimpaired_range(), false );
 }
 
 bool Character::is_visible_in_range( const Creature &critter, const int range ) const
diff --git a/src/lightmap.cpp b/src/lightmap.cpp
index 16793b93c1..aee0df61e4 100644
--- a/src/lightmap.cpp
+++ b/src/lightmap.cpp
@@ -803,26 +803,6 @@ bool map::pl_sees( const tripoint &t, const int max_range ) const
              map_cache.sm[t.x][t.y] > 0.0 );
 }
 
-bool map::pl_line_of_sight( const tripoint &t, const int max_range ) const
-{
-    if( !inbounds( t ) ) {
-        return false;
-    }
-
-    const level_cache &map_cache = get_cache_ref( t.z );
-    if( map_cache.camera_cache[t.x][t.y] > 0.075f ) {
-        return true;
-    }
-
-    if( max_range >= 0 && square_dist( t, get_player_character().pos() ) > max_range ) {
-        // Out of range!
-        return false;
-    }
-
-    // Any epsilon > 0 is fine - it means lightmap processing visited the point
-    return map_cache.seen_cache[t.x][t.y] > 0.0f;
-}
-
 // For a direction vector defined by x, y, return the quadrant that's the
 // source of that direction.  Assumes x != 0 && y != 0
 // NOLINTNEXTLINE(cata-xy)
diff --git a/src/map.cpp b/src/map.cpp
index 17e4cb2d13..9b0ad58b3c 100644
--- a/src/map.cpp
+++ b/src/map.cpp
@@ -7226,10 +7226,10 @@ void map::draw_from_above( const catacurses::window &w, const tripoint &p,
     }
 }
 
-bool map::sees( const tripoint &F, const tripoint &T, const int range ) const
+bool map::sees( const tripoint &F, const tripoint &T, const int range, bool with_fields ) const
 {
     int dummy = 0;
-    return sees( F, T, range, dummy );
+    return sees( F, T, range, dummy, with_fields );
 }
 
 point map::sees_cache_key( const tripoint &from, const tripoint &to ) const
@@ -7250,8 +7250,11 @@ point map::sees_cache_key( const tripoint &from, const tripoint &to ) const
  * This one is internal-only, we don't want to expose the slope tweaking ickiness outside the map class.
  **/
 bool map::sees( const tripoint &F, const tripoint &T, const int range,
-                int &bresenham_slope ) const
+                int &bresenham_slope, bool with_fields ) const
 {
+    bool ( map::*f_transparent )( const tripoint & p ) const =
+        with_fields ? &map::is_transparent : &map::is_transparent_wo_fields;
+    lru_cache_t &skew_cache = with_fields ? skew_vision_cache : skew_vision_wo_fields_cache;
     if( std::abs( F.z - T.z ) > fov_3d_z_range ||
         ( range >= 0 && range < rl_dist( F, T ) ) ||
         !inbounds( T ) ) {
@@ -7259,7 +7262,7 @@ bool map::sees( const tripoint &F, const tripoint &T, const int range,
         return false; // Out of range!
     }
     const point key = sees_cache_key( F, T );
-    char cached = skew_vision_cache.get( key, -1 );
+    char cached = skew_cache.get( key, -1 );
     if( cached >= 0 ) {
         return cached > 0;
     }
@@ -7268,24 +7271,24 @@ bool map::sees( const tripoint &F, const tripoint &T, const int range,
     // Ugly `if` for now
     if( F.z == T.z ) {
         bresenham( F.xy(), T.xy(), bresenham_slope,
-        [this, &visible, &T]( const point & new_point ) {
+        [this, f_transparent, &visible, &T]( const point & new_point ) {
             // Exit before checking the last square, it's still visible even if opaque.
             if( new_point.x == T.x && new_point.y == T.y ) {
                 return false;
             }
-            if( !this->is_transparent( tripoint( new_point, T.z ) ) ) {
+            if( !( this->*f_transparent )( tripoint( new_point, T.z ) ) ) {
                 visible = false;
                 return false;
             }
             return true;
         } );
-        skew_vision_cache.insert( 100000, key, visible ? 1 : 0 );
+        skew_cache.insert( 100000, key, visible ? 1 : 0 );
         return visible;
     }
 
     tripoint last_point = F;
     bresenham( F, T, bresenham_slope, 0,
-    [this, &visible, &T, &last_point]( const tripoint & new_point ) {
+    [this, f_transparent, &visible, &T, &last_point]( const tripoint & new_point ) {
         // Exit before checking the last square if it's not a vertical transition,
         // it's still visible even if opaque.
         if( new_point == T && last_point.z == T.z ) {
@@ -7294,16 +7297,16 @@ bool map::sees( const tripoint &F, const tripoint &T, const int range,
 
         // TODO: Allow transparent floors (and cache them!)
         if( new_point.z == last_point.z ) {
-            if( !this->is_transparent( new_point ) ) {
+            if( !( this->*f_transparent )( new_point ) ) {
                 visible = false;
                 return false;
             }
         } else {
             const int max_z = std::max( new_point.z, last_point.z );
             if( ( has_floor_or_support( {new_point.xy(), max_z} ) ||
-                  !is_transparent( {new_point.xy(), last_point.z} ) ) &&
+                  !( this->*f_transparent )( {new_point.xy(), last_point.z} ) ) &&
                 ( has_floor_or_support( {last_point.xy(), max_z} ) ||
-                  !is_transparent( {last_point.xy(), new_point.z} ) ) ) {
+                  !( this->*f_transparent )( {last_point.xy(), new_point.z} ) ) ) {
                 visible = false;
                 return false;
             }
@@ -7312,7 +7315,7 @@ bool map::sees( const tripoint &F, const tripoint &T, const int range,
         last_point = new_point;
         return true;
     } );
-    skew_vision_cache.insert( 100000, key, visible ? 1 : 0 );
+    skew_cache.insert( 100000, key, visible ? 1 : 0 );
     return visible;
 }
 
@@ -9413,6 +9416,7 @@ void map::build_map_cache( const int zlev, bool skip_lightmap )
 
     if( seen_cache_dirty ) {
         skew_vision_cache.clear();
+        skew_vision_wo_fields_cache.clear();
     }
     avatar &u = get_avatar();
     Character::moncam_cache_t mcache = u.get_active_moncams();
diff --git a/src/map.h b/src/map.h
index 627382a354..9780a47f25 100644
--- a/src/map.h
+++ b/src/map.h
@@ -602,7 +602,7 @@ class map
         /**
         * Returns whether `F` sees `T` with a view range of `range`.
         */
-        bool sees( const tripoint &F, const tripoint &T, int range ) const;
+        bool sees( const tripoint &F, const tripoint &T, int range, bool with_fields = true ) const;
     private:
         /**
          * Don't expose the slope adjust outside map functions.
@@ -614,7 +614,8 @@ class map
          * the two points, and may subsequently be used to form a path between them.
          * Set to zero if the function returns false.
         **/
-        bool sees( const tripoint &F, const tripoint &T, int range, int &bresenham_slope ) const;
+        bool sees( const tripoint &F, const tripoint &T, int range, int &bresenham_slope,
+                   bool with_fields = true ) const;
         point sees_cache_key( const tripoint &from, const tripoint &to ) const;
     public:
         /**
@@ -1824,12 +1825,6 @@ class map
          * Ignored if smaller than 0.
          */
         bool pl_sees( const tripoint &t, int max_range ) const;
-        /**
-         * Uses the map cache to tell if the player could see the given square.
-         * pl_sees implies pl_line_of_sight
-         * Used for infrared.
-         */
-        bool pl_line_of_sight( const tripoint &t, int max_range ) const;
         std::set<vehicle *> dirty_vehicle_list;
 
         /** return @ref abs_sub */
@@ -2262,7 +2257,9 @@ class map
         /**
          * Cache of coordinate pairs recently checked for visibility.
          */
-        mutable lru_cache<point, char> skew_vision_cache;
+        using lru_cache_t = lru_cache<point, char>;
+        mutable lru_cache_t skew_vision_cache;
+        mutable lru_cache_t skew_vision_wo_fields_cache;
 
         // Note: no bounds check
         level_cache &get_cache( int zlev ) const {
```

</details>

> But as far as I can tell, it's not actually working this way. It's certainly doing all that math, but then at the end it simply decides that either a tile is completely opaque, or it is completely transparent

Take a look at [`castLight()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/3b1dbe69340eaf39ce8fbaaa851d114ff10607d4/src/lightmap.cpp#L853) where transparency is accumulated using [`accumulate_transparency()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/3b1dbe69340eaf39ce8fbaaa851d114ff10607d4/src/shadowcasting.h#L112-L116) and used to attenuate the light ray with [`light_calc()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/3b1dbe69340eaf39ce8fbaaa851d114ff10607d4/src/lightmap.cpp#L1158-L1163).

> Line 153 contains a todo to make glass reduce light levels. I thought this would be cool as it would make houses look a little creepier on the inside and would make daytime stealth more interesting. 

This looks easy on the surface, but I haven't tried it: add a float `translucency` member instead of a bool `transparent` for furniture and plug  it into the transparency cache (multiply probably).

**Comment by fairyarmadillo** [comment]
Damn that was fast lol. I'm not going to try to cram this into the chiropteran PR but I can take a run at it in a separate one unless anyone else wants to weigh in or mess with it.
