### ISSUE TITLE
Add `SMALL_HIDER` flag to more monsters

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#71671]
### Is your feature request related to a problem? Please describe.

#66294 introduced said flag and @fairyarmadillo said in #71554 that many other monsters can use that flag.

### Solution you would like.

Go through the small critters we have and add the `SMALL_HIDER` flag where appropriate. Two notable, already existing examples are cockroaches and cats.

This is a good first issue since it is trivial to resolve, it just requires adding a flag and determining where usage makes sense.

**Comment by FlyingSpaceRhino** [comment]
Similarly, I think the CORNERED_FIGHTER flag could be added to more creatures. And maybe there's some more furniture that could have the SMALL_HIDE flag added.

**Comment by NetSysFire** [comment]
CORNERED_FIGHER is a bit broken at the moment, see #67653.

But adding more furniture is great, too.

**Comment by fairyarmadillo** [comment]
> CORNERED_FIGHER is a bit broken at the moment, see #67653.
> 
> But adding more furniture is great, too.

AFAIK it's not CORNERED_FIGHTER that's broken, it's that some animals, specifically black bears, don't have their morale set up correctly. Somebody tried to fix this in #67892 but ran into test issues. If someone adjusts the test values and reopens the PR, it'll be fixed.

The bear problem existed before CORNERED_FIGHTER, they would just stand there and let you beat on them until their morale got low enough to run, which usually meant they were almost dead.

**Comment by munzaboss** [comment]
Hello I am new and was wondering if I can do this Issue

**Comment by marilynias** [comment]
with #71767 merged, this issue should prob be closed
