### ISSUE TITLE
[Sky Island] Main Room 3 & 4 unlocks don't expand the main room.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71675]
### Describe the bug

Upon crafting Warped Reinforcement, the size of the main room doesn't expand as it said it would. Debug spawning in the items for the 4'th size unlock doesn't grow it either.

### Attach save file

[Sky Island-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14231730/Sky.Island-trimmed.tar.gz)

### Steps to reproduce

Make Warped Reinforcement, see the room not expand.

### Expected behavior

Expansion of the main room.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/0492cbd5-f830-4d69-99ec-43f927937a3e)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/35a31808-23a0-4869-9b78-e64f714dbd08)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/8059b7c5-3ead-4390-81cb-8f71ef941d5e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 3eae23b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by KyrasRisven** [comment]
I can confirm this. From my testing it appears that the function that updates the map from JSON data will fail if an appliance is present, since vehicles and appliances don't appear to have an "ignore these" override flag. Taking down or moving out any appliances in the area before running the EOC causes it expand the room properly.
