### ISSUE TITLE
Scenarios and professions do not account for the gap between outbreak and game start

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#71679]
### Is your feature request related to a problem? Please describe.

There are many inconsistencies of scenarios and professions saying that the world just abruptly ended in minutes. I tried to compile a list of the scenarios:

- The Last Delivery: While the world was falling apart, someone called to order some of Foodplace's delicious food™ and you were sent to deliver it.  You're not sure what's happened to the world, but one thing is certain: that delicious food™ is going to get delivered if it's the last thing you do!
- The Mascot Rises: You just finished your shift and got back in the break room when you heard the alarms and the security door shutting down behind you.  There's a lot of hungry customers out there and you're not sure Foodplace's delicious food™ is going to be enough to satisfy them.
- Crazy Party: After a night of wild partying at a private resort, you awoke to the sounds of police sirens and violence.  You were worried about being arrested, but you'd take that in a heartbeat over being eaten alive, which now seems far more likely.
- Low Profile: You were trying to get some distance from home and keep a low profile.  Days of boredom and a return to bad habits made you overdo it with the booze last night.  You awake and find yourself confused by the strange behaviour of people outside.  Time to sober up and see what's going on.

This does not include professions, but they are affected, too. Be it e.g the Basketball Player or the ambulance/fire department driver.

### Solution you would like.

The descriptions need to be audited and rewritten.

**Comment by MrHrulgin** [comment]
Alternatively, the start dates on them could be changed to match the descriptions.

**Comment by NetSysFire** [comment]
That would be quite hard imo because that upsets monster spawning and more, since nothing so far was made to appear earlier than the game start, so NPCs can also be nonsensical. Rewriting the description would be easier than adjusting everything else.

**Comment by MrHrulgin** [comment]
Fair enough. Changing the descriptions is a much more manageable scope than making the pre-default start experience work well.

**Comment by Night-Pryanik** [comment]
I'm closing this cause #71726 rewritten descriptions of scenarios directly mentioned in this issue. If there are other cases that need to be fixed, it's better to mention them directly too, otherwise it's just a list of wishes.
