### ISSUE TITLE
Inconsistent container behaviour.

### ISSUE THREAD

**Issue by S0ZDATEL** [CleverRaven/Cataclysm-DDA#71682]
### Describe the bug

I have two cardboard rolls with duct tape. One has 124 and the other has 159. When I'm trying to move some tape from the digger one to the smaller one, the game says it can hold only 90 more (by the way, 124+90=214, but should be 215).
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/32978558/fa81849d-ffab-46d7-a741-559564e75e4a)
I'm trying to move just 1, and the game says I can't because the roll has no more space.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/32978558/6af3dbb7-99c2-4c54-9fe5-9891f7b3fb3d)
Testing in debug mode shows I can't do that event to an empty roll.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/32978558/a8032a29-44f1-49ac-bf30-924d369ff7ef)
But I can [i]nsert it. This also behaves strangely, it allows me to insert the tape into the roll, but it does so in chunks, event if I want to insert all 215, it will only insert some random number and stop, but I can keep inserting until it's full.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/32978558/59b9cb34-0cdb-44c3-92b4-30d3b362f987)
And after that I dropped all the other tape from my inventory and could move the tape just fine.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/32978558/ed258fca-bdfd-4f06-8476-efff29b01701)
But if I have event 1 more patch of duct tape in my inventory, it breaks again. So, putting 215 out of 215 onto a cardboard roll is fine, but putting 1 out of 216 says there's no space.

### Attach save file

N/A, since it's easily reproducible.

### Steps to reproduce

1. Using debug menu give yourself a cardboard roll.
2. Drop it on the ground.
3. Using debug menu give yourself 215 duct tape.
4. Using advanced inventory manager put the tape on the roll and get it back.
5. Using debug menu give yourself 1 more duct tape so you have 216 in total.
6. Using advanced inventory manager try putting event 1 duct tape out of the whole 216 onto the roll.
7. Grab the roll and [i]nsert the tape.

### Expected behavior

First, a roll with 124 should say it has space for 91 more, not 90. Second, I should be able to put the tape on the roll as long as there is space for it and no matter the amount of the source. And third, [i]nserting should put as much as it can and not a random amount.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 1949d26 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Might apply to other containers...

**Comment by GuardianDll** [comment]
resolved by #71485, update your game
