### ISSUE TITLE
Should the Electrified Fencing Weapons be so Weak?

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#71683]
### Is your feature request related to a problem? Please describe.

The fencing sport weapons come in three states, their factory made version, their sharpened, more lethal counterparts, and finally their electrified varients. However, when one of the  sharpened fencing Sabers, Foils, or Epee gets a stun gun wired to it, its lethality drops to its pre sharpened state

### Solution you would like.

The Electrified Varients of the Fencing Foil, Epee, and Saber should retain its damage from their sharpened counterparts, as i doubt wiring a stun gun's taser prongs to the tip should drop all the way back down.

**Comment by kevingranade** [comment]
You're literally getting rid of the thing that does the damage, of course it drops it.
To spell it out,  the electrodes are going to prevent it from stabbing into your target. It's essentially downgrading it from a sword to a stun baton.
