### ISSUE TITLE
Documentation: Nested EOC conditions

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#71686]
### Is your feature request related to a problem? Please describe.

The EOC documentation currently lacks any explanation of how nested conditions work.

### Solution you would like.

Some examples, ideally with translations to boolean logic for a common programming language or pseudocode.

### Describe alternatives you have considered.

Messing with EOCs blindly until they work.

**Comment by GuardianDll** [comment]
<https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#boolean-logic>?

**Comment by Inglonias** [comment]
The specific use case I want documentation on is as follows:

```
"condition": {
      "and": [
        { "or": [ { /*Condition A/* }, { /*Condition B*/ } ] },
        { "or": [ { /*Condition C/* }, { /*Condition D*/ } ] },
      ]
    },
```

That being said, I was able to get used to it after playing with this thing for an hour or two.
