### ISSUE TITLE
Auto-eat stops eating above a certain stored calorie when it should eat when you feel hungry.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#71719]
### Is your feature request related to a problem? Please describe.

The character will stop auto eating altogether when they reach some threshold near overweight. Not even when they are hungry. making all that precious food you been cooking rot for nothing unless you manually doing it taking away all the point from this feature.

### Solution you would like.

The player should at very least, try to eat when it feels hungry or what an average person needs to eats in a day to be alive. I can go around 2 days without eating anything from auto-eat because my player went overweight and hasn't hit that threshold yet.

**Comment by kevingranade** [comment]
> what an average person needs to eats in a day to be alive.

That's exactly what it's doing,  you don't need to eat anything to maintain a healthy weight, so it doesn't trigger eating. 

Ideally we would reign in the characters ability to gorge themselves so much so it isn't so easy to get into this state,  but this issue isn't really pushing us towards that solution.
