### ISSUE TITLE
Sheathing doesn't have a number hotkey

### ISSUE THREAD

**Issue by zenforroundeyes** [CleverRaven/Cataclysm-DDA#71720]
### Describe the bug

when switching between sheathable weapons, every option has a hotkey except for sheathing 

### Attach save file

[Sutter-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14239307/Sutter-trimmed.tar.gz)

### Steps to reproduce

just switch between the bow or the knife, or really any weapon I think that you can sheath but in this save thats whats already sheathable. 

### Expected behavior

I expect hotkey for sheathing

### Screenshots

![image_2024-02-13_010803796](https://github.com/CleverRaven/Cataclysm-DDA/assets/118965537/13dfd106-b34c-4363-83ab-1ae59ab264ab)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

I just posted this in the discord group thinking I was being noob but apparently it was a bug and asked to report it.

**Comment by AnotherSeawhite** [comment]
I think it wasn't added for accessibility reasons, because sheaths are technically pockets, with extra function.
You can do a workaround by using pocket settings on your sheath to only accept your knife when storing it into inventory.
