### ISSUE TITLE
hub01 should not be hostile to players

### ISSUE THREAD

**Issue by canglan753** [CleverRaven/Cataclysm-DDA#71732]
### Is your feature request related to a problem? Please describe.

hub01 shouldn't hate the mercenaries who work for them

### Solution you would like.

Change hub01 faction name and description to hub01 Security Personnel In fact, all of hub01's internal NPCS in the game are also security personnel

### Describe alternatives you have considered.

If possible, add a new hub01 faction that unlocks with the hub01 Security Personnel faction but will not have any NPCS belonging to it

**Comment by AnotherSeawhite** [comment]
Hub 01 doesn't want anyone to enter the facility. The faction description explains that they barely go outside. They use special equipment or mercenaries (or their employees with equipment) to do 'outside' jobs for them.

And the reason why Hub 01 is hostile to people (including players, aka their mercenary) is that they really don't like people entering. They even have defensive turrets/guards in case of trespassers.

Though there are some unused files for NPCs inside the facility.

**Comment by canglan753** [comment]
> Hub 01 doesn't want anyone to enter the facility. The faction description explains that they barely go outside. They use special equipment or mercenaries (or their employees with equipment) to do 'outside' jobs for them.
> 
> And the reason why Hub 01 is hostile to people (including players, aka their mercenary) is that they really don't like people entering. They even have defensive turrets/guards in case of trespassers.
> 
> Though there are some unused files for NPCs (not the guards) inside the facility.

But that's the attitude of the intruder, a player who only takes missions in front of the walkie-talkie, why should they be hostile, when they open the camp list and see the attitude of hub01

**Comment by gettingusedto** [comment]
Mostly because of there isnt a way to make them go from neutral to hostile when you intrude into the place besides just making them hostile by default.

**Comment by canglan753** [comment]
> Mostly because of there isnt a way to make them go from neutral to hostile when you intrude into the place besides just making them hostile by default.

So my suggestion is to change the current hub01 faction name and description to hub01 Security personnel, and then add a new hub01 that is neutral but won't have any NPCS belonging to it

**Comment by IdleSol** [comment]
And through fielding and doing damage? I mean, the player enters the territory, enters the field. The result is 0 damage for all hub01 personnel.

As I recall, even followers can become hostile. Anyway on older versions (~0.F) I shot my follower and he responded to me.

**Comment by Vaskritaya** [comment]
> > Mostly because of there isnt a way to make them go from neutral to hostile when you intrude into the place besides just making them hostile by default.
> 
> So my suggestion is to change the current hub01 faction name and description to hub01 Security personnel, and then add a new hub01 that is neutral but won't have any NPCS belonging to it

The new faction that reflects their disposition to the player could have the dummy Intercom NPC belonging to it, since that's how you actually interact with them in the first place.
