### ISSUE TITLE
Teleporting Power Grid

### ISSUE THREAD

**Issue by ShnitzelX2** [CleverRaven/Cataclysm-DDA#71733]
### Describe the bug

When adding/removing batteries to a power grid, the grid can be erroneously split and will teleport.

### Attach save file

[Magasco-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14256609/Magasco-trimmed.tar.gz)

### Steps to reproduce

1. Place 5 storage batteries in a line from left to right, as in the screenshot.
2. Remove the leftmost battery (using the "take down appliance" action).
3. Replace the leftmost battery (using the construction menu).
4. Remove the leftmost battery again.
5. Remove the battery circled in the screenshot. The entire grid will teleport one tile. This example is trivial, but as shown in one of the other buildings in the save, the results can teleport the power grid into the walls.

### Expected behavior

I expected the batteries to not teleport.

(this section of the bug report form is a little redundant sometimes)

### Screenshots

![tpbug](https://github.com/CleverRaven/Cataclysm-DDA/assets/65314588/5088863c-93ac-40a4-830d-6fd582769a77)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3996 (22H2)
- Game Version: 7140bea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Unsure what the cause is here, but it happened fairly regularly with my house in a longer game.

**Comment by ShnitzelX2** [comment]
This issue is likely the same as #71692; the teleporting can cause all sorts of issues, including crashes. This setup in this second screenshot in particular is extremely volatile. Are wall wirings even supposed to connect to a power grid diagonally?

![tpbug2](https://github.com/CleverRaven/Cataclysm-DDA/assets/65314588/53ade669-a739-41b6-8a38-3c44402936c3)

**Comment by Kamayana** [comment]
I'm working on a fix for this right now, actually. Always handy to have another save to test with!
