### ISSUE TITLE
Grenade kills not credited to player 

### ISSUE THREAD

**Issue by baileytom** [CleverRaven/Cataclysm-DDA#71742]
### Describe the bug

You don’t get kill credit for grenade kill

### Attach save file

n/a

### Steps to reproduce

make character with grenade

kill monster with grenade

check kill counter

tfw no credit

### Expected behavior

grenade kill should increment kill counter

### Screenshots

none

### Versions and configuration

windows/ubuntu

### Additional context

I tried to fix this myself but it was too hard

When the grenade goes off, it makes an explosion in explosion_handler. The explosion struct has a field for Creature* source, but in this case it is null. The source field is passed to the projectile function that handles the shrapnel, so the shrapnel that kills the monster does not have an association with the player.

**Comment by baileytom** [comment]
#60910 related

**Comment by CoroNaut** [comment]
I threw a grenade nearby an NPC to kill them intentionally and it didn't record as a kill in the diary or in stats

[TESTINGTHREE-trimmed.tar.gz](https://github.com/user-attachments/files/17082322/TESTINGTHREE-trimmed.tar.gz)

1. Load save
2. Throw grenade close enough to the NPC to kill them without dying yourself
3. Notice the kill doesn't get recorded in kills stats

I threw the grenade, I want my kill stat!

Notice dead NPC to the left from my grenade, but no kills recorded
![image](https://github.com/user-attachments/assets/61fc0ec5-b4b7-4d49-9558-20a0867eaeb3)

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-09-18-0513 7b773c1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
