### ISSUE TITLE
Player lacking hair sprite

### ISSUE THREAD

**Issue by Brody2505** [CleverRaven/Cataclysm-DDA#71746]
### Describe the bug

There is no sprite for hair, making the player and NPCs appear bald.

### Attach save file

[Brody505s World_backup3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14272169/Brody505s.World_backup3.zip)

### Steps to reproduce

just make a new world and character.

### Expected behavior

I expected to have sprite for hair, but there isn't.

### Screenshots

![Screenshot 2024-02-13 161452](https://github.com/CleverRaven/Cataclysm-DDA/assets/1599588
![Screenshot 2024-02-13 161302](https://github.com/CleverRaven/Cataclysm-DDA/assets/159958829/be9f21df-83e8-45cb-9aff-a23216095b78)
29/2b8685c1-f9c6-4c57-8200-c0418f1726d1)

### Versions and configuration

[Windows 10] [Game Version c7f3f24] [UltiCa Tileset] [English] [no mods]

### Additional context

N/A

**Comment by RenechCDDA** [comment]
Tileset issues are handled on the [tileset repo.](https://github.com/I-am-Erk/CDDA-Tilesets)
