### ISSUE TITLE
Immunosuppressants and autoimmune complications

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#71749]
### Is your feature request related to a problem? Please describe.

Idea I had while browsing mutation trees for chimera and prime.

Currently ROT1/2/3 (weakening, deterioration, disintegration) are just a flat damage that comes out of nowhere, is usually a mild annoyance, but can be a danger that lacks counterplay when caught at low hp.

If ROT mutations are reworked to be an autoimmune symptom from mutations it could be temporarily paused by taking prescription immunosuppressants.

Also. immunosuppressants could be required for bionics surgery. Rubik could provide you with a dose, but if you get your fix somewhere else you'd have to source it yourself or possibly risk rejection symptoms.

### Solution you would like.

Prescription Immunosuppressants that spawn in locked areas in pharmacies, doc offices, etc.

If bionics surgery is to require a dose, then maybe the Exodii could have a special formulation they've developed over time or simply salvaged from a more pharmaceutically advanced universe.

The drug also presents an opportunity to add other autoimmune diseases or symptoms be it real-world or as a consequence of mutating. 

### Additional context

Generally more niche and miscellaneous medications in medicine spawns would be great.

**Comment by PatrikLundell** [comment]
I didn't think non biological implants, like hip replacements, pacemakers, etc. required any immunosuppressants because the materials used were bio compatible. CBMs would presumably be made out of similar materials.

**Comment by fairyarmadillo** [comment]
I think being forced to take drugs to not die of CBMs would just annoy most people, but maybe tying that behavior to a trait would be neat. Alpha should definitely get the trait since bionics are messing with human perfection, and because people often see Alpha as a "free" mutation path that doesn't conflict with anything. Probably Elf-A too.
