### ISSUE TITLE
Map generation error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71759]
### Describe the bug

While traveling, came across a strange place. See screenshot.

### Attach save file

[Беллэр-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14283541/-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/a14301de-e168-4496-aca9-e3f34417f332)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: b3733b0 [64-bit]
- Graphics Version: Tiles
- Game Language: <s>Системный язык []</s> Ru
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    Характеристики за убийства [stats_through_kills]

**Comment by MrHrulgin** [comment]
Interesting. Trailheads have been interacting in interesting ways with roads for a little bit now; I've never seen a road trim off a bit of the trailhead, though. What does the map view look like? Is the overlapping tile identified as road or trailhead?

**Comment by IdleSol** [comment]
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/575125e6-160e-4a1d-b104-fba28a1a3c48)
