### ISSUE TITLE
Segfault when reloading a gun with a mag but without conversion kit

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#71754]
### Describe the bug

#70250 changed how Deagle works. It added conversion kits for different caliber.
However, Deagles that existed before #70250 tends to be very broken in newer versions.

### Attach save file

N/A

### Steps to reproduce

1. Get a deagle before #70250
2. Update the game
3. Check the Deagle
4. Try to install a .44 conversion kit, or try to reload, etc. Can't figure out the exact procedure here.
`Oops!  deleted some items when updating pockets that were added via toolmods` debug message might appear or not in this step
Or there can be a segfault crash

If the deagle has a .44 mag but not a conversion kit, trying to reload with .44 Magnum rounds crashes the game

### Expected behavior

I did not expect the deagle to be really broken to the point where it creates a segfault

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 14; Incremental: G991NKSU4FWK7; 
- Game Version: 74e74cf [64-bit]
- Graphics Version: Tiles
- Game Language: 한국어 <color_dark_gray>(53.2%)</color> [ko]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14277681/crash.log)
Might be related with #70359

**Comment by osuphobia** [comment]
@AnotherSeawhite 
I think it is totally solved this time: after the new PR, you can no longer reload a desert eagle with no conversion kit attached, neither without a mag, nor with an empty mag, nor with a partly full mag. And you cannot attach a conversion kit with a mag in the gun, you should first unload it (that's applied in the former PR).
