### ISSUE TITLE
Mutations provided by enchantments do not respect the enchantment conditions

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71751]
### Describe the bug

When adding a mutation to an enchantment, the mutation is applied at all times even if the enchantment has a more specific condition for when it should apply such as `is_day`

### Attach save file

[Firth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14275770/Firth-trimmed.tar.gz)

### Steps to reproduce
Place the following JSON somewhere in your game so it loads:
<details>
  <summary>Somewhat long</summary>

`
{
    "id": "ench_cloak_of_elvenkind",
    "type": "enchantment",
    "has": "WORN",
    "condition": {
      "and": [
        "u_is_outside",
        {
          "or": [
            { "u_is_on_terrain_with_flag": "SHRUB" },
            { "u_is_on_terrain": "t_tree_young" },
            { "u_is_on_terrain": "t_bamboo_tall" },
            { "u_is_on_terrain": "t_grass_long" },
            { "u_at_om_location": "forest" },
            { "u_at_om_location": "forest_thick" }
          ]
        }
      ]
    },
    "mutations": [ "FOREST_STEALTH" ]
  },
  {
    "id": "cloak_of_elvenkind",
    "type": "ARMOR",
    "name": { "str": "cloak of elvenkind", "str_pl": "cloaks of elvenkind" },
    "description": "One of the traditional items of the ancient elven warrior societies, this cloth cloak woven with still-living leaves makes its wearer much harder to spot in forests or dense vegetation.  Infamous for their use during the Vietnam War by elves on both sides of the conflict.",
    "looks_like": "cloak",
    "weight": "1175 g",
    "volume": "3 L",
    "price": 150000,
    "symbol": "w",
    "color": "green",
    "material": [ "cotton", "veggy" ],
    "armor": [
      { "encumbrance": 3, "coverage": 65, "covers": [ "torso", "arm_l", "arm_r" ] },
      {
        "covers": [ "leg_l", "leg_r" ],
        "coverage": 65,
        "encumbrance": 3,
        "specifically_covers": [ "leg_draped_l", "leg_draped_r" ],
        "layers": [ "BELTED" ]
      }
    ],
    "warmth": 30,
    "material_thickness": 0.4,
    "environmental_protection": 3,
    "relic_data": { "passive_effects": [ { "id": "ench_cloak_of_elvenkind" } ] },
    "flags": [ "BELTED", "OVERSIZE", "NONCONDUCTIVE", "WATER_FRIENDLY", "RAINPROOF" ]
  },
  {
    "type": "mutation",
    "id": "FOREST_STEALTH",
    "name": { "str": "Cloak of Elvenkind: Forest Stealth" },
    "description": "You have a much easier time hiding in the forest.",
    "points": 2,
    "stealth_modifier": 60
  }
`
  
</details>

1. Load game. You'll be in the middle of the city, with a bunch of zombies nearby, and a cloak of elvenkind in your inventory.
2. Put on the cloak.
3. Notice that despite the enchantment indicating it should only apply in the forest, or at least when in a bush, most of the far-away zombies immediately lose sight of you.

### Expected behavior

Mutations respect enchantment conditions. Multiple enchantments can be applied per item, so if there's a reason for different enchantment parameters to have different conditions they can be placed on different enchantments.

### Screenshots

Before putting on the cloak:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/95f1860f-85a3-450f-8e7d-fbfaf6aaa9a4)

After putting on the cloak. The far-away zombies have lost sight of the player:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/d4300559-fa09-472b-b099-a175c029d440)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: c7f3f24 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Rokharn** [comment]
Seems u_is_outside include all other conditions. Have you tried using only special conditions?
