### ISSUE TITLE
Recipes for garlic and chili powder are missing id suffixes

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#71768]
### Describe the bug

As the title says, there are multiple recipes for garlic and chili powder, but they get overridden because they lack id suffixes.

### Attach save file

n/a

### Steps to reproduce

Check the recipes in json and notice the lack of some of them ingame.

### Expected behavior

All recipes show up.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 3eae23b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
It would be really great if we could get an organizational way to make sure this doesn't happen.

https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-02-14-2212/data/json/recipes/recipe_food.json#L9560-L9576

https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-02-14-2212/data/json/recipes/recipe_food.json#L4732-L4747

https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-02-14-2212/data/json/recipes/recipe_food.json#L4716-L4731

**Comment by mqrause** [comment]
Something to keep in mind is that mods can intentionally use the same id, so that should only check for recipes from the same source.

**Comment by RenechCDDA** [comment]
> After a bit of testing, adding a check for duplicate ids in recipe_dictionary::load() seems to work. The real trick is sifting through the duplicates one by one. There are apparently a lot of them. Some of them with very strange provenance.

If you have a list or the check code, we can start knocking them out.

**Comment by ZeroInternalReflection** [comment]
> Something to keep in mind is that mods can intentionally use the same id, so that should only check for recipes from the same source.

That's something I hadn't thought of, and might get a bit fiddly, since it doesn't look like recipes currently save their origin.

> If you have a list or the check code, we can start knocking them out.

Well, I'd been going through the ids one by one (see the check at the end) and had fixed about 25 duplicates when I decided to rework things to export a list of the remaining issues.  After about twenty minutes of wondering why it wasn't working, I discovered I'd already dealt with all of the conflicts in the base json files.  I'll see if I can get a PR up tomorrow.  

I have not checked any in-repo mods, and we won't be able to include the check until we have a way of resolving recipe_id conflicts between mods.

```
diff --git a/src/recipe_dictionary.cpp b/src/recipe_dictionary.cpp
index 524550b59c1..9600510e9f8 100644
--- a/src/recipe_dictionary.cpp
+++ b/src/recipe_dictionary.cpp
@@ -437,6 +437,10 @@ recipe &recipe_dictionary::load( const JsonObject &jo, const std::string &src,
     r.load( jo, src );
     r.was_loaded = true;
 
+    if( out.find( r.ident() ) != out.end() ) {
+        debugmsg( "Unable to load recipe_id %s. A recipe with that id already exists.", r.ident().str() );
+    }
+
     return out[ r.ident() ] = std::move( r );
 }
```
