### ISSUE TITLE
Remove attractiveness mutations

### ISSUE THREAD

**Issue by BalthazarArgall** [CleverRaven/Cataclysm-DDA#71771]
### Is your feature request related to a problem? Please describe.

Attractiveness mutations are just holding positive or negative ugliness and visibility values, making them entirely redundant to all other mutations since those can also hold ugliness and visibility values.

### Solution you would like.

Instead of having a whole type of mutations dedicated to represent ugliness and visibility make the other mutations in a line hold these values.

An example for a nondescript mutation line (not real values):

| Mutation | Old values | New values | 
| ----------- | ----------- | ----------- |
| Snout | Ugliness 1 / Visibility 1 | Ugliness 2 / Visibility 2 |
| Ugly | Ugliness 1 / Visibility 1 | Removed |

### Describe alternatives you have considered.

Give attractiveness mutations some gameplay effect. I don't know, maybe they could have some specific dialogue tied to them or something.

### Additional context

Attractiveness mutations may exist for reasons unknown to me. In this case this suggestion should be ignored/deleted.

**Comment by BalthazarArgall** [comment]
After some discussion on the Discord I was reminded that those could apply to non mutated humans that are just naturally ugly/beautiful.

My point still stands that it feels weird to "mutate" into more ugliness/attractiveness. So maybe just remove those for actual mutation trees?

**Comment by fairyarmadillo** [comment]
Extra deformity is a rational consequence of incautious mutation. Somebody who heedlessly chugs bug and bear juice is obviously going to come out looking worse than someone who very cautiously drinks cat juice. 

Alpha and Elf-A represent the progression of natural beauty to unnatural beauty via extra levels of the beauty mutation which are normally unattainable but still linked to what's in reach for humans.

These mutations also do have gameplay effects and specific dialog interactions.

**Comment by BalthazarArgall** [comment]
@fairyarmadillo makes sense, one the possible explanation that I thought about was that those mutations may represent small diformities that exist yet are not worth representing through a multitude of individual small ugly mutations like "crooked nose" or w/e.

Thanks for your time, I will delete this issue ASAP.

**Comment by fairyarmadillo** [comment]
You don't gotta close the issue just 'cause I disagree with the premise, I'm only one contributor. But if you're closing it because I've convinced you, that's another matter 😆

**Comment by BalthazarArgall** [comment]
@fairyarmadillo I was already split on wether or not I should open an issue since I thought I may have missed something.

And I definitely did, after thinking about it for a while and a few remarks (including yours I can't deny that) I think I now understand the purpose of those mutations.

Also I definitely don't want to waste anyone's time, I feel like I was wrong, I close the issue. Now we can all focus on more important stuff, like human sized blood sucking mutants for example, or eventually reworking those awful awful exoskeletons.
