### ISSUE TITLE
Invalid Overmap Terrain id "1869766501" freezes game

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#71772]
### Describe the bug

Every so often I'll play a game long enough that I run into one of these errors. When it loads the map, either opening it when nearby or moving the map focus to the area it's trying to load in, the game hangs. Very annoying. I'm not sure what's wrong

### Attach save file

[Lake Wyola-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14302279/Lake.Wyola-trimmed.tar.gz)

### Steps to reproduce

Open my save and open the map. Move down a few z-levels. Error

### Expected behavior

I'd expect the game to not try to load invalid terrain and nearly crash in the process

### Screenshots

NA

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 0.G-7395-gaeed983b5e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks]
]

### Additional context

DEBUG    : invalid overmap terrain id "1869766501"

 FUNCTION : const T& generic_factory<T>::obj(const int_id<T>&) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 463
 VERSION  : 0.G-7395-gaeed983b5e

**Comment by RenechCDDA** [comment]
Can you check the specific version via debug menu > game > generate game report?

**Comment by RenechCDDA** [comment]
I am not able to reproduce on Windows 10 / 3b1dbe69. I pushed the map all the way down to z -10 without encountering any error. I also tried moving the map around on lower levels and moving the character down there (first the stairs, then debug teleporting).

**Comment by IdleSol** [comment]
Got a bunch of error messages when loading (stage: loading the save, it seems to be on the 2nd step and penultimate or last). In the game itself, there are no errors. (Open maps, go down z levels and open a map).

- OS: <s>Windows</s> arch + portproton
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-04-0557 55f012c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks]
]



```
 DEBUG    : invalid overmap terrain id "dirt_road_3way_east"
 DEBUG    : invalid overmap terrain id "dirt_road_south"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 513
 VERSION  : cdda-experimental-2024-04-04-0557 55f012c
```

```
 DEBUG    : invalid effect_on_condition id "picked_rosebuds_fall"
 DEBUG    : invalid effect_on_condition id "godco_place_herb_garden"
 DEBUG    : invalid effect_on_condition id "godco_place_wall"
 DEBUG    : invalid effect_on_condition id "godco_place_warehouse"
 DEBUG    : invalid effect_on_condition id "godco_place_coop"
 DEBUG    : invalid effect_on_condition id "leaves2_fall_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_fall_timer_plant"
 DEBUG    : invalid effect_on_condition id "leaves2_winter_timer"
 DEBUG    : invalid effect_on_condition id "flowers_winter_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_spring_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_summer_timer"
 DEBUG    : invalid effect_on_condition id "leaves2_spring_summer_timer"
 DEBUG    : invalid effect_on_condition id "flowers_spring_summer_fall_timer"
 DEBUG    : invalid effect_on_condition id "leaves3_spring_summer_timer"
 DEBUG    : invalid effect_on_condition id "leaves_spring_summer_fall_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_winter_timer"
 DEBUG    : invalid effect_on_condition id "leaves3_fall_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_fall_timer_elfa"
 DEBUG    : invalid effect_on_condition id "leaves3_winter_timer"
 DEBUG    : invalid effect_on_condition id "leaves_winter_timer"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = effect_on_condition]
 FILE     : src/generic_factory.h
 LINE     : 482
 VERSION  : cdda-experimental-2024-04-04-0557 55f012c
```

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14864281/debug.log)

**Comment by TealcOneill** [comment]
@GuardianDll Can't replicate. Tried with both a new save and the save from this issue and had no issues at any z-level. Also tried #72814 and found no issue even using the MSXotto+ tileset which IdleSol thought to be the issue there.
