### ISSUE TITLE
Error report when trying to spawn Accuracy International AXMC rifle(V)

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#71784]
### Describe the bug

The following report is generated:

 DEBUG    : loaded a nun or ammo_data() is nullptr

 FUNCTION : gun_info
 FILE     : C:\Cataclysm-DDA\src\item.cpp
 LINE     : 3116
 VERSION  : 0.G-7317-gcb36951ad9-dirty

I'm not interested in this item, but rather looking for errors in my own code by scrolling over all possible items, thus trying to catch ones I've failed to assign appropriate milling info for.

### Attach save file

N/A, but using the one for #71652.

### Steps to reproduce

1. Load the save from the referenced issue.
2. Try to bring up the gun in the title (e.g. by typing AXM in the search entry).
3. Get the report.

### Expected behavior

No report, and presumably some gun related info actually being present.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.G-7317-gcb36951ad9-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Blaze Industries [blazeindustries]
]

**Comment by IdleSol** [comment]
I think that's the same problem: #71781
