### ISSUE TITLE
"Unable to find and assign mission target godco_1" after latest update 2024-02-16-0719

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#71785]
### Describe the bug

After loading save big bilding is generated write on top of me.  
All is fine on older game version. 

### Attach save file

1 Save file befor bug:
[Humarock-trimmed-1.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14311298/Humarock-trimmed-1.tar.gz)

2 Save file after bug:
[Humarock-trimmed-2.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14311304/Humarock-trimmed-2.tar.gz)

### Steps to reproduce

You have to load my save and move few tiles 

### Expected behavior

i expect no new buildings is generated on top of player 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 93c658a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Slots [cbm_slots]

### Additional context

DEBUG    : Unable to find and assign mission target godco_1.

 FUNCTION : find_or_create_om_terrain
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE     : 258
 VERSION  : 93c658a

**Comment by GGgatherer** [comment]
Can confirm, happens on this version to me too.

**Comment by RenechCDDA** [comment]
Was resolved by the linked issue.
