### ISSUE TITLE
loaded a nun or ammo_data() is nullptr

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71781]
### Describe the bug

 DEBUG    : loaded a nun or ammo_data() is nullptr

 FUNCTION : void item::gun_info(const item*, std::vector<iteminfo>&, const iteminfo_query*, int, bool) const
 FILE     : src/item.cpp
 LINE     : 3131
 VERSION  : 93c658a

This error occurs when the upper receiver is removed from the weapon.

### Attach save file

N/A

### Steps to reproduce

1. Default world and character
2. Spawn "m4 carbine+1"
3. Detach gunmods

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 93c658a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ANickelN** [comment]
/confirmed
Removing the upper receiver from a firearm can occur when you choose to "Unload everything" in a tile with the gun mods option enabled.

**Comment by IdleSol** [comment]
If we focus on the m4 carbine. This error occurs for the first time in the game version: [2023-12-27-2158](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-12-27-2158)

If we focus on the ar-15 rifle: [2023-12-11-1357](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-12-11-1357)

Most likely the problem is PR #69725

@GuardianDll I apologize if I disturbed you inappropriately.

**Comment by GuardianDll** [comment]
More like my PR was made based on a new feature (#69828), that have had this bug
