### ISSUE TITLE
Select all option is half broken

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#71793]
### Describe the bug

If you trying to pick up something through "mark/unmark non-favorite items" by default "," while select unpickable item (cannot fit in inventory) - no items will be selected, and you should move you blue aim selector to pickable item and only then press ","

### Attach save file

[1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14317117/1-trimmed.tar.gz)

### Steps to reproduce

Load trimmed save filed - press pick up button > select unpickable item like long pole > try to "mark/unmark non-favorite items" by pressing "," > see, that you cant do it

or

Spawn pickable and unpickable items, try to "mark/unmark non-favorite items" while unpickable item is selected (cannot fit in inventory) - see, the function don't work correctly

### Expected behavior

Correctly working functions

### Screenshots

Moved blue selector to long poles and cant pick up items
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/df54040f-54dd-4d77-b45d-3e293b2f6411)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 93c658a [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,1%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by tmqCypher** [comment]
Confirmed, same issue here

- OS: Android
    - OS Version: Manufacturer: Google; Model: Pixel 6 Pro; Release: 14; Incremental: 11084887
- Game Version: 3535ff7 [64-bit]
- Graphics Version: Tiles
