### ISSUE TITLE
A New Year. A New Batch of Typos

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#71808]
### Is your feature request related to a problem? Please describe.

I translate a lot of stuff to French, a lot of this stuff has some minor spelling, punctuation, grammar or consistency issues, so I write them down into a list for anyone with the time (or me) to fix them all into a large pull request instead of 30 different single string pull requests.
This is one of those issues

### Solution you would like.

Today we have the following issues:

Missing period at the end of colossal zombullfrog's description, also, "the gargantuan" would probably flow better as "its gargantuan":
- This gigantic zombified frog lets out an ear splitting unholy wail as it slowly takes notice of you.  Its lethargic movements are offset by the gargantuan stout leaping legs

The A Study of Nethereum Incursions book of Magiclysm probably is not intended to have a ! at the end for what seems to be a clinical academic history book:
- A Study of Nethereum Incursions! -> A Study of Nethereum Incursions

Magiclysm again, description of Intermittent Fasting Using Biomancy needs an end period:
- A guide to using biomancy to perform extreme intermittent fasting, eating an enormous amount of food only once every 2-5 days, depending on the mage's skill.  The book is filled with both glossy photos of extremely fit, beautiful people and warnings to make sure that your stomach isn't full when the spell wears off

Description of Magiclysm's Biomechanic spell could use a "the" being added at the start:
- Who said human body is weak?  You just need to compress enough mana into your flesh and bones, and you will show them who the real danger is in this world. -> Who said the human body is weak?  You just need to compress enough mana into your flesh and bones, and you will show them who the real danger is in this world.

Two obscure spiritual books seem to have been misspelt according to my (admittedly) cursory Wikipedia search:
- Helliand -> Heliand
- Book of Leister -> Book of Leinster (This one is almost certainly a typo since its own description calls it the Book of Leinster)

Marksman's Eye power unlock message of MoM misspells Marksman:
- As you meditate, all the pieces suddenly come together.  You've unlocked the Markman's Eye power. -> As you meditate, all the pieces suddenly come together.  You've unlocked the Marksman's Eye power.

MoM's NPC message in false EoC effect Enervation Drain 3 needs an extra period removed:
- You feel your life draining away!.

H&K USC 45 carbine description could use one of it's two "popular" dropped as it makes the description feel very wooden and one of them leaving wouldn't hurt (I'd suggest dropping the one describing the ammo personally):
- A compact, lightweight carbine chambering the popular .45 ACP pistol round.  Resembling the popular UMP submachine gun in both its blowback operating system and lightweight polymer frame construction.  This civilian variant is distinguished by its skeletonized stock and 16 inch barrel, and cannot accept UMP parts.

MoM's fear hawk description needs an it's turned into an its:
- A hawk with striking golden eyes.  It's call seems to pierce deep into your psyche even when it's not directed at you.

Bodypart Heading of Dragonfly Eyes in the Limb_WIP mod has an unnecessary double space:
- Dragonfly  Eyes

2 plushie variants were misspelt:
- grecko plushies -> gecko plushies
- opalbinia plushies -> opabinia

Duck plushie got an extra period that should be removed:
- A cuddly duck plushie with soft, yellow fauxfeathers (they are made of cotton!), cute orange feet, and a lovable quack.  This plushie has special water-repellent properties to make it float in water, just like a real duck!.

Dana Nunez's dialogue from the Tacoma Commune needs an extra period removed:
- I'll look into that.  What were you saying before?.

One of the big mutant crammed into small vehicle complaints needs an extra period removed:
- I'm like a sardine over here!.

XE's Like the Overflowing Fountain Undine mutation description needs an extra period removed:
- Like the fountain overflowing with water, the Undine's mana regenerates 50% faster, they have 50% more mana, and their Stamina regenerates 100% faster while standing in or under water..

Player message of the EoC effect ink grand spray could use a "your" added to it:
- Your ink glands spray some ink into attacker eyes! -> Your ink glands spray some ink into your attacker's eyes!

Two instances of book plurals doing a "the the" on two spiritual books:
- copies of the The Orthodox Church -> copies of The Orthodox Church
- copies of the The Ladder of Divine Ascent -> copies of The Ladder of Divine Ascent

Mountable PA md. 68 rifles differ from every other mountable gun variant by having a capitalized Mountable:
- Mountable PA md. 68 rifles -> mountable PA md. 68 rifles

### Describe alternatives you have considered.

- Fixing all this myself
- Not listing these issues
- Waiting until I had more to list those issues

**Comment by GuardianDll** [comment]
while here, back_holster would benefit if someone remove `Whilst initially cumbersome, it becomes much easier to use with practice` line from it

**Comment by Procyonae** [comment]
On it ^-^
