### ISSUE TITLE
creatures are able to "stand" on open air if there's a creature below

### ISSUE THREAD

**Issue by casswedson** [CleverRaven/Cataclysm-DDA#71810]
### Describe the bug

while filling a crater with zeds I noticed that one did not fall, it started moving over the heads of the zeds below

### Attach save file

n/a

### Steps to reproduce

find a hole and fill it zombies
get other zombies to walk over the hole
observe them walk over open air

### Expected behavior

this is a rather tricky bug, since creatures can't share a tile, you would maybe try to kill the creature below, that sounds... prone to bugs as in jumping on top of zeds to kill them

### Screenshots

you can't seem them but there are zombies below this one
![Screenshot from 2024-02-16 20-20-44](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/263ab9ef-535e-429d-a4aa-be45641c70f6)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: dd7a836 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by fairyarmadillo** [comment]
I don't think there's a solution to this that doesn't involve adding code for multiple creatures sharing a tile, a la dwarf fortress.

It doesn't really work all that well in DF and makes the game much more confusing, along with introducing a bunch of ridiculous behavior like dwarves lying down to slither past each other in hallways, so I'd be wary of adding it.
