### ISSUE TITLE
Manure blocks Ranch structures from spawning in

### ISSUE THREAD

**Issue by JustHereToSubmitBugs** [CleverRaven/Cataclysm-DDA#71817]
### Describe the bug

After completing the Ranch quest of acquiring 12 car batteries, I got this error message. Most likely it was just caused by one of the numerous manure piles being in the way of a wall.

Is there a way to force the game to generate the structure again? I would prefer not being stuck in the questline if possible

btw this is the debug message
 DEBUG    : In nested mapgen tacoma_commune_junk_shop_12 in unknown object in add_mapgen_update_func on ranch_camp_49_west, setting terrain to t_wall_half (from t_grass) at (5,17) when item feces_manure existed.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

### Attach save file

N/A

### Steps to reproduce

Throw items around areas that are marked for having structures on them

### Expected behavior

I was expecting the structure to be generated over the manure, which did NOT happen

### Versions and configuration

This happened on the x64-msvc release of Gaiman

**Comment by NetSysFire** [comment]
Please fill in your Versions and configuration section with the information straight from the game and do not fill it in manually.
