### ISSUE TITLE
Neoprene patch. Too high a price

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71813]
### Describe the bug

The price of one patch is $1. The price of a sheet is 35 cents, for a patchwork sheet 60 cents.

<details><summary>Details</summary>

https://github.com/CleverRaven/Cataclysm-DDA/blob/dd7a8369911d36bea19fb39b1cd1d713de31f4bd/data/json/items/generic.json#L3362-L3374

https://github.com/CleverRaven/Cataclysm-DDA/blob/dd7a8369911d36bea19fb39b1cd1d713de31f4bd/data/json/items/resources/tailoring.json#L510-L522

https://github.com/CleverRaven/Cataclysm-DDA/blob/dd7a8369911d36bea19fb39b1cd1d713de31f4bd/data/json/items/resources/tailoring.json#L525-L532
</details> 

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Reducing the price to 4 - 7 cents per patch.

Rationale. 1 sheet = 8 patches. 35 / 8 = 4 (For patchwork 60 / 8 = 7)

### Versions and configuration

cdda-windows-tiles-x64-2024-02-16-0719

### Additional context

Cut the IFAK pouch into pieces and get about 50 patches. Or how to sell a 10-cent item for 50 bucks.

**Comment by ANickelN** [comment]
BANKRUPT THE HUB WITH THIS ONE NEAT TRICK THAT THE ELITES DON'T WANT YOU TO KNOW!  
HOW TO TURN STACKS OF IFAK POUCHES INTO QUICK CASH!

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/52714184/8aa52bf1-196c-4b87-bf95-94e263fe15d7)

Jokes aside, I tested it locally just to make sure I wasn't misreading the code.
/confirmed
/good-first-issue
