### ISSUE TITLE
Hijack dormant zombies hack for monster based item placement

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#71833]
### Is your feature request related to a problem? Please describe.

This is more an interesting idea than a feature request, I'm looking for discussion on whether this is useful and not overly hacky.
#70600 introduced monsters with instantly triggered death effects that create traps, allowing traps to be placed through monster placement. Spawning items with this same method could allow for some useful weighting control in addition to allowing them to spawn more fluidly than items can for example for items peeps would "drop" before zombification (held weapons etc) as well as items you'd expect to find around monsters like spider/roach eggs.

### Solution you would like.

I'd probably implement the above if this sounds good.

**Comment by fairyarmadillo** [comment]
Pregnant roaches already explode with babies when you kill them, adding a few eggs wouldn't be a bad idea. This might also be good for ferals dropping their items.

I don't think we should make every bug imaginable explode with eggs when killed, as it would get old fast. Maybe just pregnant roaches and the mating dragonflies.

**Comment by Procyonae** [comment]
Sorry that's not quite what I mean, the dormant zombies work by using a pseudo monster that turns into a trap, I'm suggesting adding pseudo monsters that go into normal monster groups but that turn into items immediately so when you spawn roaches some of the "roaches" would just be eggs or some of the police zeds would just be rifles for instance.
Pregnant roaches and mating dragonflies (if they have clutches?) dropping eggs sounds like a sensible addition tho separate to this.
Ferals should already be dropping their weapons on death afaik.

**Comment by fairyarmadillo** [comment]
Oh, then I don't think we should go that route as we're currently properly simulating eggs via a timer and making them instead burst open the second the player got near would be a poorer simulation. Plus they're just babies, so they're not gonna be a threat.

We already have funnel web spiders who appear via a trap, and cockroaches can hide under furniture, so bugs popping out suddenly to ambush the player is already a thing.
