### ISSUE TITLE
Lake-sized oceans

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71854]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/2f9a461a-3a6f-4122-8c8d-3a4a5f5a6ddb)

I ran into this while working on some stuff. It may be a known issue, I'm not sure.

### Attach save file

N/A

### Steps to reproduce

Make a character, go east, see oceans that are sometimes not ocean sized.

### Expected behavior

That should be a lake.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0.G-7509-g2296e68931-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
I think Erk said this was a known issue when they added oceans but it doesn't hurt to have an associated issue id #
