### ISSUE TITLE
Game crashes on loading

### ISSUE THREAD

**Issue by cobianic** [CleverRaven/Cataclysm-DDA#71856]
### Describe the bug

When game checks the mod "Secronom+ Lore Exspansion" on loading, it crashes after skipping or ignoring this error:

``` 
DEBUG    : Error: Json error: C:/Games/CDDA/dda/userdata/mods/secronom_lore_expansion/Modification Files/Items/-Essentials/secro_item_categories.json:1:2: <color_white><color_cyan>missing mandatory member "name_header"</color>

<color_light_red>[</color>
<color_cyan>▲▲▲</color>
  {
    "//": "Mutation cores are item with modifiers. Better than status effects.",
</color>


 FUNCTION : load_game
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1038
 VERSION  : 787759e
```

I have tried few buids out of the last ten, from 18-19 February, the same is everywhere. Before I had some experimental version from 15-16 February, certainly before https://github.com/CleverRaven/Cataclysm-DDA/commit/d424c78c6795087faae05691d707287f1ff5fa01 (this patch was the reason I decided to update).

### Attach save file

[Small cities.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14336948/Small.cities.zip)

### Steps to reproduce

Load the save file

### Expected behavior

The game will load if I ignore the errors

### Versions and configuration

- Os: Windows 10
- Graphics: tiles
- Language: English, but could be Russian too
- Mods: "dda", "no_npc_food", "personal_portal_storms", "no_fungal_growth", "aftershock", "package_bionic_professions", "secronom", "secronom_lore_expansion", "bow_opness", "mindovermatter", "xedra_evolved", "Pix's Shit", "MMA", "MMA_Mods_Extension", "cbm_slots", "stats_through_kills", "StatsThroughSkills", "bombastic_perks", "vamp_stuff", "blazemod"

### Additional context

Cannot load into game so don't have access to debug menu, gathered what I could, save is above
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14336998/config.zip)

**Comment by RenechCDDA** [comment]
Contact the mod's author, this is a 3rd-party mod and not something we are responsible for.

**Comment by IdleSol** [comment]
Download the next version of the game. 

>Contact the mod's author, this is a 3rd-party mod and not something we are responsible for.

It's because of the bombastic perks.

**Comment by cobianic** [comment]
@IdleSol, thanks, but it was much simpler, I forgot to update the mods 😖
