### ISSUE TITLE
Pants are Pants, dag nab it! 

### ISSUE THREAD

**Issue by Cyenthies** [CleverRaven/Cataclysm-DDA#71864]
### Describe the bug

Survivor Cargo pants (Both regular and light versions, normal size) appear to have a Encumbrance and/or Movement bug, compared to various other 'pants', whether said pants are cargo, tactical, hiking or generic pants.
All pants are empty of any items that could add encumbrance. All pants are ++ condition.

### Attach save file

N/A

### Steps to reproduce

Start a new game, debug yourself all skills/ profs. etc, 
Spawn a Tailors Kit, 
-Spawn pair of survivor pants, 5 cotton/kevlar patches, repair pants to ++ status.
-Wear survivor pants, open character screen, notice move cost is 104% (red), and a debuff of Encum./Wounds M +4% is listed.
-Remove pants, open character screen, notice move cost is 100% (green), and NO debuff is listed.
  
-Spawn ANY other 'pants', spawn appropriate fabric patches to repair these pants to ++ status.
-Wear these 'pants', open character screen, notice move cost is 100% (green), and NO debuff is listed.

### Expected behavior

All pants, unless made of something much heavier than a 'fabric' patch, unloaded and empty of any items, SHOULD behave the same as far as Encumbrance, (and Wound status, as it was mentioned!), is concerned. Dag nab it.
Now if loaded down with items, yes, they should add encumbrance.

Just my peanuts, and I choose to throw 'em at this here wall.
If I'm wrong about this, feel free to chuck those 'nuts right back, along with an explanation of why my thinking is stinkin', and you'll have my thanks and gratitude! (What it's worth, may as well keep the nuts, ha!)

### Screenshots

![Pants1](https://github.com/CleverRaven/Cataclysm-DDA/assets/95771496/b4362b14-1541-421a-8434-9d6af9f39a5f)
![Pants2](https://github.com/CleverRaven/Cataclysm-DDA/assets/95771496/72c418f7-77bf-4fb6-8fe2-36e595aab302)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 3535ff7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope],
    Alternative Map Key [alt_map_key],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by RenechCDDA** [comment]
They're literally kevlar armor... their base encumbrance is not a bug. They're armor.

**Comment by Cyenthies** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/95771496/718c2aac-7e7e-4d43-8ede-172c55367a5c)
Ok, so, if that is the case, comparing these show both as armor.

**Comment by IdleSol** [comment]
Unconfirmed.

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 3535ff7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

I checked on your same version but without mods.
- jeans (encumbrance = 4): move cost=100
- light survivor cargo pants (encumbrance = 4): move cost=100
- survivor cargo pants (encumbrance = 5): move cost=100

![t2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/c1546c44-2d09-4ae5-8405-33ac5f87f117)

Also paid attention to the characteristics (weight and volume) of the light survivor cargo pants.
![t1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/d1383b6d-eb4d-4b1a-8a83-562bce7c2f73)

In your screenshot: Volume = 3.7, Weight = 2.03
I'm assuming there's something in his pants pockets. Which adds to the encumbrance.  Or maybe it's the influence of one of the mods.

Give it a try:
1. Create a default world and character (survivor / evacuee )
2. Survivor appears wearing jeans with pockets containing items, total encumbrance = 4.
3. Remove everything except jeans and sneakers.
4. Repeat the steps to summon and repair the cargo pants
5. Compare the cost of the move

**Comment by fairyarmadillo** [comment]
The survivor pants are literally 12 times thicker than the other pants. I have been making a survivor suit IRL for a project and I can tell you that any thickness of kevlar added to an ordinary garment really does interfere with your freedom of movement.

I am working on overhauling these items as most of them are badly out of date, so your complaint is noted and I do think the thickness here is a bit extreme, but I should also point out that a 4% reduction in movement speed is not going to be noticable under almost any circumstances.

**Comment by Cyenthies** [comment]
IdleSol, I thank thee, I forgot the basic tenant, ie; Is it STILL an issue without mods? 
Also, I forgot to strip off the other stuff (clothing/armor), that added a move penalty, (MOLLE belt in this case, (with +3 hanging loops), plus an empty load bearing vest w/sling, (for some reason), both gave +1 to move cost, along with +1 for light survivor boots, add the +1 from the light survivor cargo pants = a +4% TOTAL move penalty. Other than the belt, which contained a smartphone somehow (don't ask me), everything was empty. Debugged into existence as it were and fitted/reinforced on the spot.

The original issue was Pants are Pants. If it's made from a fabric base material, no more than 3.5~lbs in weight and is EMPTY, they should be identical encumbrance wise. Once anything is added to those, yep, start stacking encumbrance/penalty.

When tested again, without any mods, player mutations, etc, and with nothing on besides sneakers and the various pants, the experiment proved I was barking up a tree for no reason (at least here.) 
No penalty was noticed. Errp. Hmm, uhh, I'm just gonna close this right here. Don't mind me. Crazy fella, ya know, the media mentions the type all the time. Harmless, mostly.

Fairyarmadillo, good luck! (I jest? It's not too bad, long as it's just 'survivor' stuff, right?). And Thank you. The game wouldn't be the game it is without ya'll folks who's willing to face the Shoggath that is THE game.

I prefer that kevlar EXO myself, was upgraded/introduced to it in an ironic way, and I will say without a doubt, much more flexible version. Bit lighter too, I think.

**Comment by Cyenthies** [comment]
IdleSol, I thank thee, I forgot the basic tenant, ie; Is it STILL an issue without mods? 
Also, I forgot to strip off the other stuff (clothing/armor), that added a move penalty, (MOLLE belt in this case, (with +3 hanging loops), plus an empty load bearing vest w/sling, (for some reason), both gave +1 to move cost, along with +1 for light survivor boots, add the +1 from the light survivor cargo pants = a +4% TOTAL move penalty. Other than the belt, which contained a smartphone somehow (don't ask me), everything was empty. Debugged into existence as it were and fitted/reinforced on the spot.

The original issue was Pants are Pants. If it's made from a fabric base material, no more than 3.5~lbs in weight and is EMPTY, they should be identical encumbrance wise. Once anything is added to those, yep, start stacking encumbrance/penalty.

When tested again, without any mods, player mutations, etc, and with nothing on besides sneakers and the various pants, the experiment proved I was barking up a tree for no reason (at least here.) 
No penalty was noticed. Errp. Hmm, uhh, I'm just gonna close this right here. Don't mind me. Crazy fella, ya know, the media mentions the type all the time. Harmless, mostly.

Fairyarmadillo, good luck! (I jest? It's not too bad, long as it's just 'survivor' stuff, right?). And Thank you. The game wouldn't be the game it is without ya'll folks who's willing to face the Shoggath that is THE game.

I prefer that kevlar EXO myself, was upgraded/introduced to it in an ironic way, and I will say without a doubt, much more flexible version. Bit lighter too, I think.
