### ISSUE TITLE
Monsters and 3d view

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71867]
### Is your feature request related to a problem? Please describe.

I apologize for the quality of the text.

When I saw the new PR #71822 that adds highways. I had a question.

What will happen in case:
- the road passes through z=1 level as a bridge
- a military road blockade event will occur on it (i.e. riot control platforms will appear)
- the game character walks on the z=0 level

I assumed that at some distance, the platform will notice the player, warning him and start shooting at him. There may be errors: shooting through the road. Perhaps the character will not be able to notice the platform or everything will be fine.

I did some tests and the result surprised me. Next, I will repeat what I wrote in that PR.

z=0
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/14fab48d-9b65-4154-9a7e-647802992162)

z=1
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/770cf500-77da-4785-900e-45b759bbe6f2)

Character (z=0) looks up (z=1)
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/1c4b3c49-b8a3-4a3a-bc9e-5e500d52587b)
![4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/f76cbe6d-cb11-4fbf-99d2-183431360d35)
Character, can't see the platform. Platforms do not see the character.

But if you get up close and stand on the tiles marked by the target.
![5](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/2ebf1f8b-6f49-4cbf-9268-a0b4c472d939)
Both the character and the platform see each other. Moreover, the platform hits the character.

And if you pay attention, you can see the casing from the other platform, but you can't see the platform itself. (Maybe it's a bug?)

Did I understand correctly that the 3D view takes into account the character's height? And monsters have no height, so for the game it is 0? In fact, they are flat? So they can only see on neighboring squares.

### Solution you would like.

I would like to propose the following topic for discussion.

Do monsters need to add height? So that they have the same field of view as the character.

What it would do. Monsters will jump out of the upper floors as they notice the player. Or will attack him if they have ranged attacks.

But this will add lag to the game. Just like now, there are small delays when moving on the bridge. But only more so.

Perhaps this is already in the plans? Or someone is working on it?

**Comment by fairyarmadillo** [comment]
Per #67434 Monsters and characters both count their size and (in the case of characters) their posture when looking over ledges. Both use the exact same rules.
