### ISSUE TITLE
Trailheads are spawning way more than they should be.

### ISSUE THREAD

**Issue by jacb345** [CleverRaven/Cataclysm-DDA#71863]
### Describe the bug

trailheads are more common than they use to be in forested areas almost completely drowning out other locations from spawning.

### Attach save file

[Burgin-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14338820/Burgin-trimmed.tar.gz)

### Steps to reproduce

1.create a world and spawn in it.
2.reveal map with debug.
3.count number of trailheads in forested areas compared to other locations.

### Expected behavior

I expected to find a variety of locations with trailheads being common but not completely drowning out other locations from spawning.

### Screenshots

![Screenshot from 2024-02-19 21-53-03](https://github.com/CleverRaven/Cataclysm-DDA/assets/139024208/f680f78a-0935-4fb4-b2e5-e9db5114c73f)
![Screenshot from 2024-02-19 21-52-54](https://github.com/CleverRaven/Cataclysm-DDA/assets/139024208/130a1880-8cd7-4fff-9244-4aa751c34d19)
![Screenshot from 2024-02-19 21-52-42](https://github.com/CleverRaven/Cataclysm-DDA/assets/139024208/4c9bff85-b761-44d9-9c65-84d40f7f0b90)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.3; Release: 20.3; Codename: una; 
- Game Version: 3535ff7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
#67470 increased the number of trailheads by allowing them to spawn non north facing, I didn't change their spawn rate at the time bc it improves the realism of trails for them to have multiple splits and heads and I asked in the discord with screenshots and noone wanted them decreasing but I'm not against any change to them.

**Comment by jacb345** [comment]
I know this is late but you probaly should change them there was a lot more interesting stuff in rural areas before the change now I can never find sugar houses anymore for example because they spawn in the same places as trailheads.
