### ISSUE TITLE
: NONE appears on a migo when using the V inspect menu 

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#71879]
### Describe the bug

: NONE appears on a migo when using the V inspect menu.

### Attach save file

[Travelling – Kopi-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14350708/Travelling.Kopi-trimmed.tar.gz)

### Steps to reproduce

1. Load in and use the V inspect menu

### Expected behavior

not : NONE

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49415411/6f06a263-3591-4e76-836c-da499bbf52a1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 4047b90 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Red's balance setting [Reds_mod],
    Stats Through Kills [stats_through_kills]
]

**Comment by RedBloodCat** [comment]
"Red's balance setting [Reds_mod]" disabling does not change the behavior

**Comment by BrettDong** [comment]
Fixed in #71861. Monsters spawned in an earlier game version still have `: NONE` suffix.
