### ISSUE TITLE
Crafted canned livers are not sealed and will expire.

### ISSUE THREAD

**Issue by Azlyp** [CleverRaven/Cataclysm-DDA#71878]
### Describe the bug

Craft canned liver, I've only tried using the recipe that uses 3L glass bottles and 0.5L glass bottles. and it will not be sealed. Wait a couple of days and it will start expiring.

### Attach save file

N/A

### Steps to reproduce

1. Craft canned liver.
2. Wait.
3. Check to see if it is expiring.

### Expected behavior

Canned food should be sealed.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 5276eb5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    fungal rebalanced [no_fungal_special_attack]
]

### Additional context

N/A

**Comment by Holli-Git** [comment]
/confirm though it only applies to the jars, not the cans
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/78005870/4a4cfff6-daa4-4b12-8997-a49c0a4478fd)
