### ISSUE TITLE
mom: speed reader buffs don't wear off

### ISSUE THREAD

**Issue by casswedson** [CleverRaven/Cataclysm-DDA#71907]
### Describe the bug

speed reader buff is never removed

I suspect that this behavior is present in other powers

### Attach save file

n/a

### Steps to reproduce

get into the clairsentient tree of powers.
cast baseline speed reader power (note the duration), I gain an effect and a trait.
wait 8 hours and I still have the effect and hidden trait.

### Expected behavior

the eocs say that at some point they will remove the effect and the trait

### Screenshots

![Screenshot_2024-02-21_17-18-40](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/f2a8df3b-8e20-46bf-92d4-f7f42202b875)
![Screenshot_2024-02-21_17-19-28](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/47bad5f1-198d-467b-ba39-16db96c21d83)
![Screenshot_2024-02-21_17-20-14](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/91c4b0ce-c8f8-4846-8699-16b261a6207d)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: d6b054c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by MrHrulgin** [comment]
The fact that it says (C) after the power shows that it's a channeled power, as described in the description. As long as you're able to keep concentrating, it's going to keep going. That's why your log says "You feel a strange tingling feeling as you concentrate." You're still maintaining the ability.

**Comment by Standing-Storm** [comment]
You can use "Stop Concentrating" to automatically turn off all your concentration powers, or re-channel each one to turn them off individually. They'll also automatically turn off if you go to sleep or are stunned.

**Comment by casswedson** [comment]
I think there isn't enough in-game explanation of how `(C)` works
```
This power is maintained by concentration and may fail if concentration is
interrupted.  It is canceled by engaging in combat.
```
did not get the point across for me, I would make it say something like this: `This power is continuously maintained by concentration...` mention in some clear way that you can keep them going forever
