### ISSUE TITLE
Treetops dont generate outside of initial reality bubble

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#71909]
### Describe the bug

Climbable trees are so cool!!!
They dont generate outside of initial spawn area though :/

### Attach save file

[Jessie-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14366481/Jessie-trimmed.tar.gz)

### Steps to reproduce

generate a world, go outside of initial generation area, find no treetops

### Expected behavior

Treetops generate consistently

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/107653330/3f636151-8084-4115-9ddd-54915b53dc10)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: d6b054c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by fairyarmadillo** [comment]
So this is apparently a problem with automatically generated roofs. I wasn't aware of it until after I made the PR, and I might not have done so had I been aware of it.

It seems like mostly the game is trying to move away from auto-roofs, is that just because of this bug, or is there another reason to do it?

**Comment by Consoleable** [comment]
> So this is apparently a problem with automatically generated roofs. I wasn't aware of it until after I made the PR, and I might not have done so had I been aware of it.
> 
> It seems like mostly the game is trying to move away from auto-roofs, is that just because of this bug, or is there another reason to do it?

I'm not sure. I think adding treetops is really really cool, because climbing trees is great for games to have, especially games that seek depth like cdda.
