### ISSUE TITLE
Disassembling some plants produces different amounts of seeds than the crafting recipe for seeds

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#71912]
### Describe the bug

Disassembling a zucchini produces more seeds than crafting seeds from the crafting menu.
Disassembly prouces 2 seeds, and the recipe produces one seed.
Also happens with raw bottle gourd (disassembly makes 3, recipe makes 1) and cucumber (disassembly makes 2, recipe makes 1). 
Eggplant disassembly produces less seeds (1 -> 8) as does the disassembly of starry false Solomon's seal (1->2) which seems more sensible since disassembly seems to take no skill and the survivor might not find the seeds or something. It also might not be intended.

### Attach save file

N/A

### Steps to reproduce

1. Find one of the plants.
2. Get survival skill to 2.
3. Observe the recipes.
4. Inspect the disassembly menu.

### Expected behavior

Expected the disassembly results to be the same or worse than the crafting recipe.

### Versions and configuration

Game version d6b054c

**Comment by fairyarmadillo** [comment]
Unintentional, a few were missed as a byproduct of doing everything at once, I'll patch these.
