### ISSUE TITLE
Asks about EVERY item over the weight limit when collecting.

### ISSUE THREAD

**Issue by Lilimday** [CleverRaven/Cataclysm-DDA#71938]
### Describe the bug

When collecting things from plants, the player tries to take EACH item into his hands. Accordingly, every time he asks me “what to do with the thing in my hand.” I'm picking a pine tree - there are a lot of branches, he will pick up ALL the branches and ask about each one. It doesn’t matter whether I start the collection empty-handed or not, the question always arises. Previously, the excess was simply thrown out at the feet when the space in the clothes ran out, but now they ask me about every branch - it’s terrible.

This is not the first time I have encountered this glitch; it happened in an older version. But the glitch went away on its own and did not appear again. In the experimental version in another game, I also encountered this - at some point it stopped, but they killed me there, and now it started again. Please, help.

### Attach save file

[Iskra-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14390746/Iskra-trimmed.tar.gz)

### Steps to reproduce

Try to collect everything you can from the trees; your inventory is almost full; when there is no room, the character will start asking what to do with the items.

### Expected behavior

Let him stop taking every branch when collecting, asking me every time what to do with it.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 78fb2bf [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Магиклизм [magiclysm],
    Медленный рост фунгалоидов [no_fungal_growth],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Приручаемая живность [Tamable_Wildlife],
    Скорость от ловкости [speedydex],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Отключить потребности у НПС [no_npc_food]
]

**Comment by IdleSol** [comment]
Confirmed. I was able to reproduce it. But only once out of 5-7 attempts.

Requirement. There needs to be an election and a change of character.

Assumption. Is the bug affected by NPS traits?

**Comment by Lilimday** [comment]
> Confirmed. I was able to reproduce it. But only once out of 5-7 attempts.
> 
> Requirement. There needs to be an election and a change of character.
> 
> Assumption. Is the bug affected by NPS traits?

I don’t think it’s an NPC, I reset the world, created a new character, didn’t recruit an EPS and went off on my own, started crashing and again pulled everything into my hands.

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: 78fb2bf [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Магиклизм [magiclysm],
    Медленный рост фунгалоидов [no_fungal_growth],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Приручаемая живность [Tamable_Wildlife],
    Скорость от ловкости [speedydex],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Отключить потребности у НПС [no_npc_food]

[Iskra-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14391145/Iskra-trimmed.tar.gz)

**Comment by IdleSol** [comment]
It's the damn beans. 

I don't know why your medium tin contains one bean. And yet it's sealed. As a result, there is space in the tin can, but it cannot be placed in it because it is closed. Throw it away or eat the beans.

How did you create the character? The scenario and the profession. Was the can from the start or did you find it?

**Comment by IdleSol** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/d6c98a1fd9ddd2b72fa459a1ec9c8f4abc502dce/data/json/professions.json#L2195-L2211

```
       { "item": "can_beans" }, 
```
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/adfc1b91-7d64-4e49-91b9-a41cc30cb3e8)

**Comment by Lilimday** [comment]
> It's the damn beans.
> 
> I don't know why your medium tin contains one bean. And yet it's sealed. As a result, there is space in the tin can, but it cannot be placed in it because it is closed. Throw it away or eat the beans.
> 
> How did you create the character? The scenario and the profession. Was the can from the start or did you find it?
Scenario “evacuee” profession “homeless”, I wanted a quiet start in a shelter with NPCs and protein rations, and this damn jar was needed to boil water... He already had a jar of beans from the start.

**Comment by Lilimday** [comment]
I found a “Small cardboard box” with several pizzas, the presence of this box in the inventory also gives this bug. The box was not sealed and was found already in the game. I threw out the pizzas, just left the box in my inventory - then it fills up like a human being and there are no problems.

**Comment by IdleSol** [comment]
Do you have the ability to open this thread back up?

**Comment by IdleSol** [comment]
This PR #71884 prioritizes the containers. I assume the pizza box is prioritized and restricted to: pizza only.

But the game still sees the free volume and tries to put stuff in it.

![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/248da31c-bbc8-4e53-ab0f-af8d4d685343)

**Comment by Lilimday** [comment]
The bug arose again - an empty medium tin can lies in a small cardboard box, the box is in my hands. The jar is empty, but is in the box.

It's funny, I tried to put a small cardboard box (empty) in my knapsack, I started filling it with all sorts of garbage - the box was filled with it inside the knapsack, I tried to empty the "small cardboard box" container while it was inside the knapsack - I was completely thrown out of the game.

**Comment by IdleSol** [comment]
>Is there no item in the settings that would always show me the contents of ALL containers? 

inventory - hotkeys - show/hide all contents: i - ? - D - select the key

**Comment by Lilimday** [comment]
![изображение](https://github.com/CleverRaven/Cataclysm-DDA/assets/127485828/aa887a81-69fa-464c-9d49-33e27887eebf)
I was able to crash out of the game again. Tried to empty a small box of pizza while it was inside a trash bag. Unfortunately, since I was thrown out, the contents were not saved, but I am sure that there was still free space in the package, and a lot of it. I tried again to load the bag in the same way as it was approximately at the moment when the game broke, but again it didn’t work.
Fun fact: every time the game loads, the game spends the longest time thinking about “items”—well, when it gives you a list of what’s being loaded, it obviously thinks about it the longest.

**Comment by Lilimday** [comment]
I don’t understand where he could save the log he refers to. In the config folder?
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14439237/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14439238/debug.log)
