### ISSUE TITLE
Crash while saving

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#71945]
### Describe the bug

The game raise a SIGSEGV when saving

### Attach save file

[Paradise.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14392324/Paradise.zip)

### Steps to reproduce

1. Load the save
2. Try save the game

### Expected behavior

Do not crash

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/3899581/50e5846d-4203-4df7-84f9-9b8349fd8433)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.H-3189-gb76b8b4c5-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Farseer2** [comment]
Doesn't reproduce on latest for me

**Comment by Night-Pryanik** [comment]
Closing until reconfirmed.
