### ISSUE TITLE
[Bombastic Perks] Gaining any perk segfaults the game

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#71944]
### Describe the bug

When selecting a perk with the perk menu, getting the perk segfaults the game.

### Attach save file

[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14391811/Test.zip)

### Steps to reproduce

1. Get enough XP to gain a perk
2. Choose and get the perk
3. Segfault immediately

### Expected behavior

No segfault

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: d6c98a1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]
]

**Comment by SariusSkelrets** [comment]
Can confirm. Used yesterday's experimental, gained the jumpy trait
The game then crashed

**Comment by Standing-Storm** [comment]
Do either of your characters have a threshold mutation? Trying to figure out why it works perfectly for me

**Comment by b3brodie** [comment]
No, the characters have no thresholds.  I have my test character here even without any mutations at all (other than perk menu) and they still crash.  
![about to crash mutationless](https://github.com/CleverRaven/Cataclysm-DDA/assets/70666939/a164d1a8-2e54-4162-b204-98d5e8b3d855)

**Comment by b3brodie** [comment]
If it helps, this is the crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14394898/crash.log)

**Comment by AnotherSeawhite** [comment]
/confirmed
Can confirm it crashes, regardless of mutations.

`#17: 0x72a258ca04 Character::activate_mutation(string_id<mutation_branch> const&)
#18: 0x72a25c4420 avatar::power_mutations()
#19: 0x72a1ebd5ec game::do_regular_action(action_id&, avatar&, std::__ndk1::optional<tripoint> const&)
#20: 0x72a1ecbde4 game::handle_action()
#21: 0x72a1ce1bc0 do_turn()
#22: 0x72a222684c SDL_main`

**Comment by Standing-Storm** [comment]
> No, the characters have no thresholds. I have my test character here even without any mutations at all (other than perk menu) and they still crash. ![about to crash mutationless](https://private-user-images.githubusercontent.com/70666939/307559718-a164d1a8-2e54-4162-b204-98d5e8b3d855.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjQxMzUsIm5iZiI6MTcwODgyMzgzNSwicGF0aCI6Ii83MDY2NjkzOS8zMDc1NTk3MTgtYTE2NGQxYTgtMmU1NC00MTYyLWIyMDQtOThkNWU4YjNkODU1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDAxMTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NWY2MTdjZmU0MjRlOWIzYWRkNzJmNTUwMjMwZjhmMjdlZWMwOTJmOGYxMDdjNzc5ZjhkYmRkMTE5M2U1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ycQz7MTG8Xa4JJ5w8XRG5MObIwWX1Ax2Z7KFAjqIW5w)

Now I’m even more confused. You can see in the screenshot of the testing on #71898, I got a bunch of perks on that test character and never had a problem. I even tested it yesterday afternoon after I saw someone on Discord mention having a problem and it still worked. 

My system and game are also in English.

**Comment by Standing-Storm** [comment]
Just got home, updated Cataclysm to get a fresh game, loaded up Bombastic Perks:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/e4fdcce2-4bf1-40dc-ab01-e813afb047f8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/6484d443-5767-481c-809b-3e8188775765)

**Comment by Standing-Storm** [comment]
Okay, so because it works for me I can't test it to fix it, but can someone please try this and see if the changes I made to perkmenu,json in the following branch fixes the problem: https://github.com/Standing-Storm/Cataclysm-DDA/tree/perk-fixes/data/mods/BombasticPerks
