### ISSUE TITLE
English must be a proficiency

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#71950]
### Is your feature request related to a problem? Please describe.

English must be a learned and learnable proficiency. Default survivor must have one. This is also somewhat related to issue #71947 .

Here's why this would be useful. 

Bionic modules. PC somehow knows how to extract those things from zomborg corpses and, even more absurdly, knows how to reset bionics into original factory state... How on earth? 

Therefore you must have some sort of proficiency with bionics to work with them, along with medical knowledge. 

This knowledge is available to exodii, and the knowledge (say, books) are likely be written in another language than our English. You have to understand that language to begin understanding how to work with bionics. 

Hence this issue. Some books (sources, form doesn't matter) must be written in different language and PC must master it or ask for help to digest that knowledge.

### Solution you would like.

English, like driving should be a default proficiency. Not having it should make reading AND speaking impossible with most things in-game. 

Also, it should be learnable - possibly using live, willing survivors? 

Also, illiterate should be removed as a trait. It's silly.

### Describe alternatives you have considered.

Adding Italian proficiency instead - which should obviously come with a decent cooking proficiency.

**Comment by Spicyshadow** [comment]
Reading and speaking are two differant skills and should be two differant proficiencies. You also don´t learn a language al at once so you should have multiple proficiencies to represent differant levels of language comprehention and reading skill. A reading proficiency should probably also replace the fast and slow reader traits.

**Comment by MrHrulgin** [comment]
Honestly, I don't mind this idea. As it is, the Churl can never overcome their illiteracy, but if instead of a permanent trait they started out with a lower language proficiency it would be something that could be overcome with time. It seems of very niche use in most characters, though,

**Comment by PatrikLundell** [comment]
I don't think English is a good candidate for a proficiency, as everyone would have it. Instead, it's probably better with a negative trait (or potentially removable proficiency) to mark the exception.

Start as a latino (select country of origin here) illegal migrant? It might make sense to start with no English proficiency but then learn over time, but it's probably a huge task to add all the stuff that's needed to allow for this to integrate properly into the game.

Proficiency to varying degrees in other languages would make sense only if there's content that make it relevant. An example where it might be relevant would be if someone would make content to interact with Luliya the Exodii and spending a huge amount of time learning her language. Now, that in itself wouldn't make for good content, so there would have to be "real" content to make that interesting.

**Comment by Icantthinkofanameforthis** [comment]
shouldnt it be reading instead of a specific language?

**Comment by PatrikLundell** [comment]
There are really several components to reading:
- The basic skill of interpreting symbols;
- The ability to read specific sets of symbols. For character based languages the set is limited (the Latin, Cyrillic, Greek, etc. alphabets), while for iconographic languages the set is huge (e.g. Chinese).
- The ability to read the language (stupid spelling rules, etc. which differ by language: for iconographic languages this burden is largely handled by learning the set of symbols, although you'd still have to learn dual usages, where present).
- Iconographic scripts may not even be used by a single language: both Akkadian and Sumerian use the same glyphs, but the pronunciation was different, sometimes completely different.

Trying to read e.g. French if you've only learned the spoken form, but can read English is going to be a struggle (although French is more consistent in its spelling than English, once you understand the sets of spelling rules. There are fewer cases of things like "colonel" actually pronounced as "kernel". You pay for that with a grammar that's inconsistent when spoken as well).

**Comment by tornikeo** [comment]
Guys, you are really overcomplicating this. It's just a proficiency that is supposed to block you from reading more "arcane" information sources that exodii or other intelligent travelers are likely to bring with them... Learning them should require ssome effort and goodwill from said travelers. That's it. There's no other use I see for this.

Also it removes illiterate as a trait, which I think is pretty stupid, so that's a plus.

**Comment by Zireael07** [comment]
@tornikeo Sorry, but unless you can come up with a scenario/profession that would make this interesting to use, and not a variant of illiterate, it's unlikely to happen.

**Comment by tornikeo** [comment]
@Zireael07 the only use-case I had in mind was some sort of arcane literature from exodii. Specifically, bionic martial arts book (or books) or, manuals that allow you to **mend said bionics** into factory state. Right now, the PC **somehow** knows how to reset an unknown piece of implantable tech to factory form - that's ridiculous. How would you ever know that? You have to know the tech - and only guys in town selling that tech are the exodii. Aaand, I don't expect the books about bionics to be in standard english, so you have to know the language first. 

Hence this issue.

What are your thoughts?

**Comment by Qrox** [comment]
Rubik doesn't have to teach you his language though. According to #66515 Exodii has an internal network with a translator which they can connect you to, which can be implemented as an Anglic trait (or proficiency, but that's just implementation detail).

Replacing illiterate with an English proficiency sounds fine but as others said it's unnecessary churn unless it's part of some more interesting change.

Come to think of it, an English speaker can at least understand some of the Anglic Exodii uses; the more intriguing part is how autodocs produced by humans can somehow be compatible with the Exodii CBMs.

**Comment by Zireael07** [comment]
Exodii arcane books/knowledge sources sound very cool but wouldn't use English proficiency as such. As @Qrox mentioned their language isn't English anymore, it's something else

**Comment by tornikeo** [comment]
@Zireael07 That's a good feedback. Let me re-market this to Exodii language proficiency somehow... Closing this in the meantime.
