### ISSUE TITLE
Rubik CBM surgery for NPC followers

### ISSUE THREAD

**Issue by RangerFromBaja** [CleverRaven/Cataclysm-DDA#71960]
### Is your feature request related to a problem? Please describe.

Rubik has no options to install bionics into your followers, the only possible way is to either do it yourself through autodoc or wait until the Doc in the hub01 bar appears.

### Solution you would like.

I'd like for Rubik to install CBMs into my NPCs, especially since it's the main way to get it done for yourself.
Since the Doc has the ability to install bionics into your followers it's likely possible to copy the code for Rubik too.

**Comment by fairyarmadillo** [comment]
You can also switch to them at the faction camp board and have them go down there and get installs done. Last I checked, once Rubik is good with your main he's good with your whole faction, but that could be incorrect/outdated.

**Comment by RangerFromBaja** [comment]
I did try to switch to my follower through debug but it seems that you'll have to go through all the dialogue(and probably the quests) again, it's probably only the faction relations that are the same.
