### ISSUE TITLE
[Magiclysm] Spell Wash the Wounds Clean crashes game when used on body part

### ISSUE THREAD

**Issue by Icantthinkofanameforthis** [CleverRaven/Cataclysm-DDA#71966]
### Describe the bug

found a book that gives the spell wash the wounds clean and figured might as well use it to disinfect wounds for faster healing and tried it out and as the titles suggests the game crashed then tried it again and ya it crashes every time also tried on a testing world in case it was a mod conflict of some type but na still crashes

### Attach save file

[Testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14396068/Testing-trimmed.tar.gz)

### Steps to reproduce

1. have world with magiclysm mod
2. create character
3. debug in a way to get the spell Wash the Wounds Clean either spawn the book 'The Home Mage's Healthcare Manual' and learn the spell use debug to learn the spell in debug menu > player > change spells > yes if it asks to disable achievements otherwise carry on > filter search 'wash' to find spell and pick a lvl above -1 that will let you cast it successfully
4. have 2 of some type of water for spell either clean water, mineral water, salt water or water (you start with a bottle of 2 clean water as a standard survivor)
5. hurt self in some way so you can use the spell on a body part
6. use spell on body part
7. enjoy crash

### Expected behavior

game to not crash with segmentation fault when spell is used

### Screenshots

![segmentation crash](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/15e063e9-bd89-4744-94ea-e48acea6a13c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: e18b7e2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14396074/crash.log)

**Comment by Noroji** [comment]
To add to this:
If you cast the spell and then cancel the cast when prompted to select the limb, it still uses the water. Also, if you are near an infinite water source and then cancel when it asks you to select a limb, you cannot recast it afterwards with the unlimited water source. It looks like it should work, but you cannot select it in the menu to actually use it.

[Masters-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14397379/Masters-trimmed.tar.gz)

**Comment by Standing-Storm** [comment]
As for the additions, that’s standard behavior for component spells—canceling it after casting it uses the components because the spell was successful cast, and you cannot use components that you’re not personally holding (which is why even standing in water doesn’t count)
