### ISSUE TITLE
[Magiclysm] Casting Animated Blade gives a warning about attacking yourself, if you're within the summoning range

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71978]
### Describe the bug

Casting Animated Blade gives a warning about attacking yourself, if you're within the summoning range. As a summon, it shouldn't do that.

### Attach save file

[Orestes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14398390/Orestes-trimmed.tar.gz)

### Steps to reproduce

Cast Animated blade with you inside the summoning range.

### Expected behavior

No warning, as there's no danger.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/eef3202c-72ae-4e91-ad16-09fedfb9cf9e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: e876e86 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by RedMisao** [comment]
This happens for all aoe spells when any "friendly" creature, including the avatar (`self` in this case), is under the aoe, even when the spell itself lacks those as `valid_targets`.
e.g. a damage spell has both `ally` and `hostile` as `valid_targets`. If you delete `ally` and try casting on friendly NPCs, the warning will still show, even while the spell won't deal damage to such targets anymore.
