### ISSUE TITLE
Start Date and Item Spawns

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71972]
### Is your feature request related to a problem? Please describe.

I am willing to work on this issue, but I wanted to get some feedback first as it would be a big change:

Currently, the game treats all items and monsters created during the initial spawn as having been born on the day of the cataclysm. This does not make sense with our timeline.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/Lore/lore-background.md

Beginning the game on the default starting date of April 30th sets the Cataclysm start date to also be April 30th.

We all experienced the COVID pandemic, and should all be familiar with panic buying and supply chain issues. At the slightest hint of any kind of global problem, IRL humans who were not affected by the blob went out and panic-bought all the toilet paper and flour they could find. At the same time, food manufacturing and shipping industries began to see huge losses in productivity because some people couldn't or wouldn't come in to work and shelter in place orders prevented even some willing people from doing their jobs.

Because supply chains are chains, any one point of failure in the process has exponential effects on productivity down the line. If fruit pickers are too sick to work, no fruit can be processed. If it can't be processed, it can't be shipped. If it can't be shipped, it can't be stocked, etc.

- The timeline says that in March, there were worldwide riots, and by the end of the month, these escalated to the point of wanton carnage. We had IRL riots in 2020, but they were not worldwide, and were nowhere near as bad as described here.
- On April 1st, the government is blaming Chinese mind control beams, suggesting that ferality and zombification are becoming commonplace. Obviously that's worse than anything that happened IRL in 2020.
- In Early April, we have history-making destabilizing events like the Rhode Island secession.
- On April 10th, a state of emergency is declared, and it's noted that this came far too late. There are in-game news articles talking about how the government is unable to effectively deliver emergency supplies to the New England Disaster Area because things are too bad all over. This is the point where mixed hordes of zombies and ferals are swamping the shrinking enclaves of sane police and military.
- On April 15th, it turns into Stephen King's The Mist/Black Mesa/STALKER. There are Kaiju, clouds of acid mist melting towns, people and things getting teleported to strange places, etc. From here, the country starts nuking itself. I'm not sure about this but the lore seems to suggest that New England got the worst of it due to its high concentration of XEDRA sites.
- On April 25th, a low-ranking government official says that no help is coming. I assume that by now, what would become the Old Guard has largely been evacuated and there is nobody at the helm in the United States. From here (but I believe much earlier) we can assume that this is also true of just about every industry. Maybe in rare cases, your local bodega has a heroic owner who defends it with a shotgun and welcomes people in to buy what supplies are left, but nobody's picking, processing, packaging, shipping, or delivering more.
- The game begins on April 30th.

Given all of that, I am pretty sure that things like deliveries to restock stores would have begun to drastically slow down in mid-March, and people would have been panic buying from at least that point. From April 10th, there would probably be little to no economic activity taking place.

This goes a long way to explaining why our stores have like, 4 pairs of pants and 3 jackets in them, but a big problem is that at game start, there is fresh food everywhere. Malls have burgers and fries left out on the tables in the food court which were made on April 30th. There are fresh cakes left out in public areas that should have long since been overrun by zombies and hungry ferals. Homes are also full of fresh food that according to its expiration date was made _today_, yet the power is out everywhere and everybody is dead.

Basically, the game looks too much like the rapture and too little like Armageddon. This is probably because initially we were taking cues from things like Romero films, where the zombie outbreak sort of happened overnight.

### Solution you would like.

- map::spawn_item should, instead of making every item be born on the day of the cataclysm by default, make things be 2-6 weeks old. If we had some randomness here, it would help suggest that power (and refrigeration) failed at different times, and maybe some food deliveries made it through.
- The number of looted grocery stores and milsurps should be reduced. I think about 50% would be fine. That way you can reasonably expect that a place will have the kind of stuff you're looking for, but won't be surprised when it's trashed. We may want to reduce the number of items in an unlooted milsurp though - recently in my local area, for about two weeks following an ice storm, every single MRE was gone.
- We could add some snippets about supply chains and panic buying. These would help explain the state of the world and I think would help players understand the world by drawing on our shared real-life experience.
- This should not affect zombie spawns. It's reasonable that some evolved zombies ought to be around on day one, because they died and came back weeks ago, but we should limit where these guys show up for playability reasons. For that reason, I don't think it would be appropriate to simply move the default cataclysm start date back 3 weeks.

### Describe alternatives you have considered.

The No Hope mod tries to depict this by removing a lot of items from the world. While I appreciate the challenge that this adds, I don't think it quite accurately simulates what our timeline is describing. I think a better model than "99% of locations are looted already" is to present an apocalypse that caused a lot of supply chain issues. IMO we're already doing this with our less-than-realistic amounts of items on store shelves, it's just the fresh food that's a problem.

It's reasonable to worry this might make the early game too difficult, but I think between the protein rations in the emergency shelters, the sort-of-edible bugs, the small game everywhere (hello frog legs) and the large amount of shelf-stable food in the game, plus cannibalism and long pork, players are not hurting for calories.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/1072e0ea-4f75-4da3-804c-903173a627c4)

**Comment by IdleSol** [comment]
I'm playing with a x0.1 setting to spawn items.

I have no problems with food. More of a problem with keeping it.

**Comment by Aimless-dude** [comment]
I have to agree. There is so much fresh food when the game starts, you can just glut yourself for about the first week.

I'll also always be a proponent of anything that changes our frankly comically high number of looted milsurpluses

**Comment by kevingranade** [comment]
> map::spawn_item should, instead of making every item be born on the day of the cataclysm by default, make things be 2-6 weeks old.

We can quibble about the distribution of times in a PR, but overall yes this should be happening.

> The number of looted grocery stores and milsurps should be reduced. I think about 50% would be fine.

This doesn't follow from anything else you're saying. Nothing you're talking about here indicates that looting activity is lower than what's implied by the existing mapgen settings.

> We could add some snippets about supply chains and panic buying.

Please do. 

> This should not affect zombie spawns.

Agreed.

**Comment by fairyarmadillo** [comment]
> This doesn't follow from anything else you're saying.

I think the levels of lootedness we see currently are really inconsistent and could be dialed in better, but I'll put a pin in that for now and just try to look at the item spawn/snippet stuff in a PR.

**Comment by Procyonae** [comment]
> map::spawn_item should, instead of making every item be born on the day of the cataclysm by default, make things be 2-6 weeks old.

Identical foodstuffs already rot at different times don't they? How is that done currently other than this?
