### ISSUE TITLE
`"remove_rigid"` removes integrated armor

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#71980]
### Describe the bug

In Xedra Evolved, Arvore has a trait called Bark Skin, which turns their skin into woody integrated armor, and a trait called Hidden Thorns, which when activated, causes thorn to push through their skin. Hidden Thorns has

> "restricts_gear": [ "head", "torso", "arm_l", "arm_r", "leg_r", "leg_l" ],
    "remove_rigid": [ "head", "torso", "arm_l", "arm_r", "leg_r", "leg_l" ],
    "allow_soft_gear": true,

...the idea being that since they're thorns, the Arvore cannot wear metal or similar armor over them. However, when used, the Arvore's barkskin--despite being on the Personal layer and Integrated--is removed.

### Attach save file

[Joppatowne-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14398916/Joppatowne-trimmed.tar.gz)

### Steps to reproduce

1) Activate the "Hidden Thorns" mutation.
2) `Your ++ barkskin is pushed off!`

### Expected behavior

Integrated armor cannot be removed. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/23e76f05-a204-45e5-9226-052267da0a05)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/6adb2417-0d34-47c3-9c47-193d460ba6d1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: e18b7e2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by PatrikLundell** [comment]
It looks to me that the conversion process should be blocked when rigid armor is worn over the bark armor. This would ensure you can't poke someone's eye out with spikes tunneling through a rigid armor. Note that this ought to be on a body part granularity level, so wearing a metal bikini top shouldn't block you from hurting someone with the spikes on your (unarmored) arms.

The alternative is to allow the conversion but have checks in place to ensure it doesn't do anything while covered by rigid armor. The same issue with body part granularity exists in this case.
