### ISSUE TITLE
Electric zeds and missing EMP damage. Bug?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71988]
### Describe the bug

Now a PR #71961 related to repairing things damaged by water and electricity is being prepared for release.

I decided to run some tests, during which I noticed that zed_electric.json zombies don't break my electronics. But memory says they must break.

The tests involved:
- Monsters:
  - shocker brute
  - skeletal shocker
  - shocker zombie (he was involved in most of the tests)
- Items
  - flashlight
  - mp3 player
  - smart watch
  - smartphone

None of the items were broken

### Attach save file

N/A

### Steps to reproduce

Test 1

1. Wear a suit that protects against electricity.
2. Take a bag and put electrical appliances in it.
3. Create a circle of debug monsters (i=3)
4. Summon a certain number of shocker zombie (i=5)
5. Wait for half an hour
6. Look at the electronics.

Test 2
1. Take your clothes off
2. Hold your smartphone in your hand
3. Set the strength to 20 (or more)
4. Summon the shocker zombie
5. Stand under their attacks while regenerating health through the debug menu
6. Look at a working smartphone

Test 3
1. The equipment from the first test
2. Take the EMP grenade
3. Activate it and throw it under your feet.

### Expected behavior

If it's a bug, then fix it.

### Versions and configuration

cdda-windows-tiles-x64-2024-02-26-0558

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 6e1e928 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

The flashlight is too cool to break from a trivial EMP.

UPD. Incandescent husk breaks electronics. But not a flashlight.

**Comment by fairyarmadillo** [comment]
Shockers are not supposed to break electronics, that is a special ability of the incandescent husk. EMP is very different from electricity.
