### ISSUE TITLE
Mouse pointer does not hide

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#72019]
### Describe the bug

`Options -> Interface -> Hide mouse cursor`. When set to `HideKB` or `Hide`, the mouse pointer is still visible. `Use ImGui UI` is set to `False` but I guess this new library it is somehow involved.

### Attach save file

N/A

### Steps to reproduce

1. Build SDL/TILES on Windows
2. Run it
3. Set `Hide mouse cursor` option to hide
4. Mouse pointer still there

### Expected behavior

Mouse hide when typing on the keyboard as before

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.H-3232-g1b3440569-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by katemonster33** [comment]
Looks like ImGui innards do have some code which forces the mouse cursor to be shown every frame. Will open a PR soon to fix it.
