### ISSUE TITLE
Acid's quench power and enjoyability.

### ISSUE THREAD

**Issue by cSep** [CleverRaven/Cataclysm-DDA#7202]
| as is | quench | enjoy |
| --- | --- | --- |
| Weak acid water | -28 | -15 |
| Acid water | -96 | -30 |
| Concentrated acid | -96 | -30 |
| Soap | -96 | -30 |
| Ammonia | -96 | -30 |
| Bleach | -96 | -30 |
| Plant food | -10 | -30 |
| Hops flowers | -20 | -15 |
| Disinfectant | 0 | 0 |

these look and feel a little bit unbalanced to me and I'd like to fix them up a bit. please help discuss.

per http://www.wiki.cataclysmdda.com/index.php?title=Thirst#Thirst   a quench of -48 is the equivalent of 4hrs thirst, -96 8hrs, -192 16hrs, -288 24hrs.  here's another, revised table of maybe better numbers:

| prop2 | quench | enjoy | note |
| --- | --- | --- | --- |
| Weak acid water | -48 | -30 | 4hrs thirst, as enjoyable as plant food |
| Acid water | -96 | -40 | 8hrs thirst, less enjoyable |
| Soap | -72 | -30 | 6hrs thirst and as enjoyable as plant food |
| Ammonia | -96 | -40 | 8hrs thirst, less enjoyable |
| Bleach | -96 | -40 | 8hrs thirst, less enjoyable |
| Concentrated acid | -576 | -96 | 48hrs thirst, now parched and in crisis |
| Plant food | -18 | -30 | 90mins thirst equivalent. |
| Hops flowers | -20 | -15 | unchanged |
| Disinfectant | -12 | -10 | 1hrs thirst, tastier than hops. |

revised to update and include bleach/ammonia/soap/disinfectant for comparison.
##

**Comment by illi-kun** [comment]
All liquids listed here should not be consumable at all.
