### ISSUE TITLE
Linux CI machine needs SDL 2.0.17 or better

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#72022]
### Describe the bug

CDDA fails to compile on the Linux CI machines due to this error:

    #error This backend requires SDL 2.0.17+ because of SDL_RenderGeometry() function

### Attach save file

N/A

### Steps to reproduce

Observe [a linux build](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8059264719/job/22016044229#step:17:369).

### Expected behavior

I expect the build to build.

### Versions and configuration

cdda-experimental-2024-02-26-0558

**Comment by katemonster33** [comment]
Looking at this now. Possibly we need to update the version of Ubuntu used in the workflow file.

**Comment by katemonster33** [comment]
#72024

**Comment by katemonster33** [comment]
actually looks like #72026 will be the solution, closed my PR
