### ISSUE TITLE
Crash when drawing vehicle from above

### ISSUE THREAD

**Issue by inverimus** [CleverRaven/Cataclysm-DDA#72047]
### Describe the bug

For a long time there has been an error when drawing some vehicles from above when using ascii that could just be ignored. Now this is causing a crash.

### Attach save file

[Meta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14436641/Meta-trimmed.tar.gz)

### Steps to reproduce

Load the provided save and go in the room to the right and it crashes.

### Expected behavior

n/a

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling;
- Game Version: 0.G-7690-gd660a13f3a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14436638/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14436640/crash.log)

**Comment by katemonster33** [comment]
based on the description this seems to be specific to curses build. i can look at this tonight
