### ISSUE TITLE
Proposing Resonance  Alternative

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#72041]
### Is your feature request related to a problem? Please describe.

Look, resonance is a way to cap the artifact power - it is necessary. However, effects are also _incredibly_ boring (who likes to have radiation sickness and pain for fun?)

We need something that's more !FUN! and lures the PC into the deadly artifact chasing loop.

### Solution you would like.

Instead of bunch of random PITA effects do this:

- create a class of monsters uniquely related to and attracted by artifact resonance. An alien lifeform that evolved into consuming the anomalous matter OR a sentient alien collector that just gathers these things for reasons unknown. 
- instead of periodic PITA effects, start displaying ominous messages as PC accumulates resonance over time (it should add up)
- At specific thresholds, spawn these special monsters.
- If PC is able to kill the monster, the monster should drop more artifacts to potentially lure the player into the artifact-chasing cycle that will inevitably lead to gruesome death.
- Make the last few stages of the monsters truly, fully unbeatable and all-but-guaranteed to kill you (from personal experience, corner puppies are barely a threat once I have enough artifacts to cause them to spawn - we need something much worse)

### Describe alternatives you have considered.

None

**Comment by ADekema** [comment]
I think it is a bad idea to have resonance spawn enemies that drop artifiects. This would lead to a snowball effect where onse you have a few artifect you could start farming more artifects to get the effects you want. This would completely throw off the power progression as you can build a collection of artifacts with the best stacking effects for every situation giving you a massive spike in power within a very short time.

I do like the idea of stronger and more varied nether enemies showing up when you have to many artifacts. The idea of some eldritch intelligence interacting with you is also an interesting consept.

**Comment by tornikeo** [comment]
@ADekema Look, at some point, having enough resonance must mean a guaranteed, gruesome death, that arrives randomly (even worse than knowing when it will come). The kind of death that the Alt+F4 and thinking very carefully can only delay, but just for a bit. Even with all the artifact power ups included, the PC must die to the last variants of monsters in just a few turns.

I'm still thinking on what kind of monsters I should go for, for this.

**Comment by ADekema** [comment]
The problem is that the death monsters will only show up at higher resonances while you can already farm artifacts at lower resonances. So anyone will still be able to safely farm artifects with a bit of metaknowladge. The only way to prevent this is to have a chance to spawn the death monsters on the first go. This however introduces the problem of having a bit to much resonance being a potential instant death sentance. Something that we tend to avoid.

**Comment by Kywi001** [comment]
How about this?
Depending on how much resonance your player has, different stuffs could happen:

Low: periodic pains and nausea.

Medium: periodic pains and nausea as well as hallucinations and a chance to spawn 1 to 2 mercenary ghost (this guy is from physics lab) and your artifacts migh get activated on its own.

High: periodic pain and nausea as well as hallucinations and a chance to spawn 3 to 5 mercenary ghost and 1 mercenary officer and your artifacts can get activated on their own.

**Comment by tornikeo** [comment]
@Kywi001 merc ghosts a decent threat, but they lack purpose. Like why? Why are they attracted to the resonance?

Something that is attracted to artifacts must somehow be connected to them, possibly:
- it's like a food, a monster that eats artifacts
- or maybe this monster is a some parallel-world survivor that noticed your unusual artifact resonance and breached into your Earth (using artifacts of their own) to kill you. Either to add your artifacts to their collection, or to destroy them.
- Finally, I'm thinking that the the last monster should be a higher dimensional "numismatist", that just is having fun collecting highly unusual lower-dimensional critters like yourself.
