### ISSUE TITLE
Improved animal taming and aggression

### ISSUE THREAD

**Issue by LetterShapedGlyphs** [CleverRaven/Cataclysm-DDA#72043]
### Is your feature request related to a problem? Please describe.

1 - Even with stacking mutations decreasing an animal's aggression, sometimes they'll aggro from you standing near them for too long because PLAYER_CLOSE is not capped at 20 the way HOSTILE_SEEN is
2 - animals change their minds about you being dangerous too quickly/rapidly, while a bit of running away and coming back makes sense, they should eventually make up their minds and commit to fleeing
3 - taming animals because you fed them once is easy but limits the extent to which "taming animals" can be done in any sort of realistic manner (only taming animals already used to humans)

### Solution you would like.

- [ ] Make use of the mutation anger relations with previously hardcoded traits
- [ ] extend that to also allow for fear relations
- [ ] find a better way than iterating through every mutation the player has for each creature nearby
- [ ] ability to define intensity and cap of fear/anger triggers per monster in JSON
- [ ] Long term impacts on Fear/Anger instead of reverting to monster type baseline
- [ ] initial long term fear/anger of baby animals is the average of nearby adults (with a slight bias towards wildness)
- [ ] animal taming/husbandry proficiency? (by food type? by type of need fulfillment? other? TBD)
- [ ] Food, Safety, and Fun (exercise/play) for tamed animals
- [ ] Safety incrementing with time passing not taking damage because trying to teach the AI that a "place" is safe is hard
- [ ] most 'fun' is probably just "not tied down" and having open terrain types around that the animal likes, 'play with' can do something here (chance for players to get slightly hurt when playing with predator type babies or "more wild" adults?)
- [ ] food is obvious and I believe already mostly done

### Describe alternatives you have considered.

Leave everything the way it is, or only implement a few of the more 'obvious' ones of these that don't change any current functionality

### Additional context
Stretch goals or other nebulous ideas-
- [ ] Zone activity for feeding/petting animals?
- [ ] NPCs from a base can help take care of tame animals

**Comment by Norwaivhi** [comment]
Here are some of my thoughts:

1) Safety could be increasing not only from the lack of harm recently, but also take into account the availability of food, as well as the amount of other healthy animals nearby.
--Even if the place was safe, you wouldn't want to stay there if you could not obtain any food.
___
2) I'd imagine there should be a tag, something like "Herd Animal" or "Herd Behavior", or a modifier. Also if some amount is accumulated animal could become "completely tamed".(and become resistant to tameness changes?)
--This way you can sort of modulate how "hard" taming something is - some animals are individuals and won't look at others' behavior, some would require a few of its kind to become a herd, and some are easily herded.
___
3) Proficiency sounds nice, but I struggle to imagine its effects.
--Gatekeeping the Player from taming some animals? Making it so that less amount of food is needed to tame something? The increased effect of the Player's actions on animals? Crafting recipes? (Perhaps some more advanced medicine, foods, tools, etc.)

**Comment by LetterShapedGlyphs** [comment]
> Here are some of my thoughts:
> 
> 1. Safety could be increasing not only from the lack of harm recently, but also take into account the availability of food, as well as the amount of other healthy animals nearby.
>    --Even if the place was safe, you wouldn't want to stay there if you could not obtain any food.
> 
> 2. I'd imagine there should be a tag, something like "Herd Animal" or "Herd Behavior", or a modifier. Also if some amount is accumulated animal could become "completely tamed".(and become resistant to tameness changes?)
>    --This way you can sort of modulate how "hard" taming something is - some animals are individuals and won't look at others' behavior, some would require a few of its kind to become a herd, and some are easily herded.
> 
> 3. Proficiency sounds nice, but I struggle to imagine its effects.
>    --Gatekeeping the Player from taming some animals? Making it so that less amount of food is needed to tame something? The increased effect of the Player's actions on animals? Crafting recipes? (Perhaps some more advanced medicine, foods, tools, etc.)

1 - Other healthy animals nearby makes a lot of sense, but if you're already tracking how much it's being fed it doesn't make sense to me for that to factor into "safety"
2 - That's a really good idea as well. I think I'd still want _some_ level of caring about nearby animals? The ideal would be an animal learning some of it's acceptable behaviors from the parents but since that's super abstracted I just thought about "averaging nearby of the same type" but there should absolutely be a sliding scale between "exactly the average" and "wild baseline"
3 - My main thought was about trying to tame predators or other not domesticated animals. Amount of fun provided by play, chance of injury while playing, chance of injury while feeding, etc. So mostly impacting how long it takes to tame an animal, how risky it is, and how often you might need to do any sort of maintenance tasks to keep them from getting too ornery.

**Comment by Norwaivhi** [comment]
Oh right! I completely forgot about the difference between "I eat" and "I am being fed". Not sure what to point it to directly, but this distinction I feel is crucial when it comes to herds(chickens/sheep/cows/so on) and individualistic animals(dogs/cats/probably any predator you are trying to tame)

>Edit for more thoughts: Could also affect things like 'how long it takes to milk a cow or shear a sheep' and 'how well does the animal listen to you while you're riding it'

Makes sense, especially with riding. Milking a cow? Well... To some extent, maybe ;) 

Fun is still a bit lost on me, it comes off as quite a multi-purpose stat, while for dogs it could literally be "Fun", for chicken it would be "How fine I am with this cage". Maybe there is a better term or separation is needed? (\Clarification\Description)

**Comment by XygenSS** [comment]
Being able to tame wild animals should be locked behind Elfa or some other animal-friendly mutation tree.

**Comment by fairyarmadillo** [comment]
> Being able to tame wild animals (especially predators) should be locked behind Elfa or some other animal-friendly mutation tree.

I always thought it might be fun if post-thresh Lupines could tame wolves, Felines cougars, Cattle moose and deer, etc. Letting Elf-A get in on some or all of that too might be really cool.

**Comment by NetSysFire** [comment]
There is also the tamable wildlife mod which sounds perfectly appropriate for that.

**Comment by Zireael07** [comment]
Related: [#70449](https://github.com/CleverRaven/Cataclysm-DDA/issues/70449)
