### ISSUE TITLE
Failing test: `Text Changes Analyzer / analyze-text-changes (pull_request)`

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#72046]
### Describe the bug

Test fails for reasons unrelated to my PR:
https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8082962435/job/22084936873?pr=72045#step:5:61

### Attach save file

N/A

### Steps to reproduce

1. Make a PR (probably)

### Expected behavior

Test doesn't fail

### Versions and configuration

On current master d660a13f3a

**Comment by Consoleable** [comment]
#72009

**Comment by Brambor** [comment]
> also getting this for my PR #72009

Yeah, I think every PR is affected by this.
