### ISSUE TITLE
changed some settings and after a reset i keep getting segmentation faults 

### ISSUE THREAD

**Issue by tommykoning** [CleverRaven/Cataclysm-DDA#72053]
### Describe the bug

segmentation faults on boot-up (linux)

### Attach save file

N/A

### Steps to reproduce

i updated the game and was getting seg faults, reinstalled it to make sure the game worked. for a bit changed some settings (fullscreen mode, mesurement units, tilepack, soundpack, etc) and made a quick throw away game. closed the window and tried to open it again and i get a segfault 

### Expected behavior

to not get a seg fault

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 23.1.3; Codename: Vulcan; 
- Game Version: 25af268 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]

### Additional context

[Archive.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14439318/Archive.zip)

**Comment by andrei8l** [comment]
Can you try [this build](https://github.com/andrei8l/Cataclysm-DDA/releases/tag/cdda-experimental-2024-02-28-2122) please?

**Comment by tommykoning** [comment]
it worked till i changed screen mode from borderless windowed to maximized

**Comment by andrei8l** [comment]
So you're getting another crash after that? Can you post the crash log? Does it still happen if you launch `./cataclysm-tiles` directly?

**Comment by tommykoning** [comment]
no nvm false alert your build works i made a mistake launching it from the terminal my bad

**Comment by katemonster33** [comment]
If I read the crash log you linked properly, this was an error opening your audio mixer. Maybe we could handle this more gracefully in the future.
