### ISSUE TITLE
Farms should be affected by pests

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#72051]
### Is your feature request related to a problem? Please describe.

In the real world, something like 30% of global crop production is lost to pests every year and that's _after_ accounting for all of humanity's pest-control measures. In a world without those measures, that number would be much higher. But if you stroll up to a farm on the first day of fall, there will be fields of corn rippling in the breeze, ready for the picking, with only the occasional empty spot to represent a particularly choosy animal.

### Solution you would like.

Some sort of abstract way to represent pest damage. Actually spawning animals would only affect crops in the reality bubble (and looking through PRs, it was already tried before in an Aristotelian spontaneous generation sort of way), so it'd be better as a catch-up days after Cataclysm modifier, or some kind of tracking of locusts hordes of the overmap, or something similar. If you show up to a farm in summer or fall, more than half the crops should probably have been eaten. 

Of course, this should also apply to your own crops if you spend weeks away and don't task any NPCs with looking after them.

**Comment by fairyarmadillo** [comment]
I believe a desired feature is to de-hardcode hordes and make them break things and consume resources depending on their members, so that seems like an important method.

I've been working on farming. I want to make unattended crops die based on stuff like weather, irrigation, etc. That will take care of the more natural sorts of die-off.

**Comment by Brambor** [comment]
>  The main thing I need to learn about to do this is where/how/if map tiles store stuff like precipitation and temperature.

I think temperature is used for food spoilage, so it is a part of the catch-up system.
