### ISSUE TITLE
ImGui Keybindings window. Leaves an image artifact

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72065]
### Describe the bug

If you open the keybindings menu window. After closing it, a line remains at the bottom of the screen.

![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/1735e43e-db33-421b-9cf4-fcaf7e3b1169)

The interface must be enabled. ```Use imGui UI: true```

### Attach save file

N/A

### Steps to reproduce

1. Default settings
2. Enable imGui (settings / options / interface / Use imGui UI: true)
3. Open the keybindings menu
4. Close the keybindings menu
5. Look at the bottom of the screen

A similar line appears on any invocation of the keybindings menu. For example:

3. Start creating a new world
4. In the difficulty selection menu, press ```?``` 

or

3. setting /safemode
4. press ```a``` (start creating a new rule )
5. press ```enter``` (set rule name)
6. press ```F1``` (calling the keybindings menu)

### Expected behavior

No "new" lines after closing the key binding menu window.

### Screenshots

![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/62c5a58c-18e5-4507-9654-59648345380b)

### Versions and configuration

cdda-windows-tiles-x64-2024-02-28-2115

### Additional context

If ```Use imGui UI: false```, there's no problem.

I'm assuming the problem is the size of the keybindings menu. It's longer than it should be.

**Comment by velddrinn** [comment]
In ASCII mode (no tileset) it looks like this.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5492522/90247cce-fcc8-4fec-a039-2d7c255707cf)

**Comment by IdleSol** [comment]
I was watching with a blank manager.

**Comment by velddrinn** [comment]
> When you resize the game window, the artifacts disapear.
Confirm.

Still looks like redraw issue. This happens only on unseen (or menu background) tiles:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5492522/9eb323a8-f8fa-4787-915d-5fb74c704b68)
It redraws when forced by window resize.

**Comment by katemonster33** [comment]
I haven't been able to reproduce this with latest Cataclysm, @IdleSol can you re-test?

**Comment by IdleSol** [comment]
cdda-windows-tiles-x64-2024-04-02-1742

The problem remains. And also the problem with resizing the window
![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/4e95eb00-95f6-41f0-8047-194136d5ecb5)

** Steps to reproduce **

1. Default options
2. Enable ImGui
3. Options / Graphics / Graphical display options / fullscreen = no
4. Save changes, close the game and load again
5. Change the size of the window, to an arbitrary size
6. Open the keybindings window
7. Close the key bindings window
8. Look at the artifacts
9. Resize the window again
10. Image artifacts disappear

P.S. I can record a video.

**Comment by IdleSol** [comment]
Did some additional testing.

This problem is most serious in the main menu. In the game itself (after loading the world), resizing the window leaves almost no artifacts. Except for that line at the bottom of the screen (see the first post). Which is not critical.

I don't know the correct terminology. Oh, and it's also in translation. I would pay attention to the size of the window in which the game draws its elements. For the main menu, it's obviously smaller than for the game itself. And in both cases smaller than the window the system allocates. The artifacts occur in the gap between these two windows.

Or some (?) windows with ImGui ignore the window frames set in the game and focus on the frames set in the system.

![test 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/329279ff-580a-4242-b16e-6161e790c474)
![test 4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/3a420912-cd01-4669-970f-3c3e5a017a22)

**Comment by IdleSol** [comment]
dda-windows-tiles-x64-2024-04-05-0445
@I-am-Erk, @katemonster33 

![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/011ff62f-2e54-4e2f-af54-d00e36137b0e)
