### ISSUE TITLE
pseudo tiles appear when useing the "Dark Days of the Dead" mod

### ISSUE THREAD

**Issue by RowanRam** [CleverRaven/Cataclysm-DDA#72062]
### Describe the bug

Lone but consistent psedo tiles appear in my world as of the experimental build 2024-02-26-0341. I am not sure if its mod related or not but I can only guess.

### Attach save file

N/A

### Steps to reproduce

1. download 2024-02-26-0341
2. make a world with the dark days of the dead mod.
3. play it you will eventually see psedo tiles.

### Expected behavior

I created the world and It might have something to do with the Dark Days of the Dead mod.

### Screenshots

![dd1](https://github.com/CleverRaven/Cataclysm-DDA/assets/93171867/41b4e846-a578-4195-ac31-5b135d27f9ee)

### Versions and configuration

- OS: windows 10
- Mods: Base content, Dark Days of the Dead
- Experimental build: 2024-02-26-0341

**Comment by RenechCDDA** [comment]
The `region_terrain_and_furniture` definition is missing an entry for `t_region_shrub_plains`. The field mapgen places this, which is intended to be replaced with a lookup from the `t_region_shrub_plains` array, but the array doesn't exist so it silently fails.
