### ISSUE TITLE
cant create helicopter

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#72069]
### Describe the bug

 DEBUG    : map::board_vehicle: vehicle with unbroken and BOARDABLE part not found

 FUNCTION : board_vehicle 
 LINE     : 1323 

### Attach save file

no

### Steps to reproduce

debug mode ,create helicopter

### Expected behavior

no bug

### Versions and configuration

pc windows

**Comment by ZhilkinSerg** [comment]
Did you try to spawn damaged or undamaged vehicle?

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/8707e52d-1f8a-4f65-87b5-f2ef7621571b)
