### ISSUE TITLE
ImGui Keybindings window. The content depends on the Use ImGui UI option

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72068]
### Describe the bug

I'm not sure it's a bug. I'm talking about the keybindings window for the keybindings window.

settings / keybindings / ```?```

Use imGui UI: false
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/1b2a6c4d-8403-4b2a-8acd-6ba62a5d7424)

Use imGui UI: true
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/deb74466-896c-48c0-9a2f-583289530fe1)

Different number of points.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

cdda-windows-tiles-x64-2024-02-28-2115

**Comment by katemonster33** [comment]
imgui has its own handling of input which is not configurable in the same way it is in CDDA, thus navigation keys like "up" and "down" do not show up in imgui UIs. not a bug.

**Comment by andrei8l** [comment]
It is a regression though
