### ISSUE TITLE
ImGui Keybindings window. Inactive search bar

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72066]
### Describe the bug

The keybindings window (settings / keybindings). The search string does not become active.
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/fda5ad20-3ad2-4cb3-96de-68ded19b83b3)

To be more precise, it sometimes becomes inactive (does not allow you to enter text). The behavior is as follows. When opening a window, the cursor blinks once and disappears. When pressing keys nothing is typed.

The interface must be enabled. ```Use imGui UI: true```

### Attach save file

N/A

### Steps to reproduce

1. Default settings
2. Enable imGui (settings / options / interface / Use imGui UI: true)
3. Open the keybindings menu
4. Try typing. If you succeed, go to the next step.
5. Close the game and open it again.
6. Go to step 3

Alternatively 1.
1. Open the keybindings menu
2. Close the keybindings menu
3. Open another menu (safemode, options or create a world)
4. Close this menu
5. Go to step 1

Alternatively 2.
After opening the keybindings menu, press enter. Try typing in the text

### Expected behavior

The search bar should always be active.

### Versions and configuration

Game version: cdda-windows-tiles-x64-2024-02-28-2115

### Additional context

If you disable imGui, everything works fine.

**Comment by katemonster33** [comment]
I personally am not reproducing this locally. Maybe some more information is needed about your environment? Are you reproducing this reliably? 100% of the time? 50?

**Comment by IdleSol** [comment]
I tried it on two systems
1. archlinux + PortProton 
2. windows 10 (virtual machine)

Basic method: ~80%
Alternatively 1: ~30% maybe a little more
Alternatively 2: 100% 

Can you enter text? If you pressed enter.

**Comment by katemonster33** [comment]
Getting back to this now that I am done with android... So you emulate cataclysm? You don't play on the Linux build?

**Comment by IdleSol** [comment]
Yes, I'm using the windows version (cdda-windows-tiles-x64-2024-03-13-0502). But I run it through the emulator.

**Comment by katemonster33** [comment]
Ok. What happens if you run cataclysm locally?

**Comment by IdleSol** [comment]
The same thing is happening.

**Comment by katemonster33** [comment]
Hi just checking. Still reproducible after #72501? Any change?

**Comment by IdleSol** [comment]
cdda-windows-tiles-x64-2024-03-25-0528

No change. The error still occurs.

**Comment by IdleSol** [comment]
[cdda-windows-tiles-x64-2024-03-26-1759](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-26-1759)

Nothing has changed.

**Comment by katemonster33** [comment]
OK I finally figured out how to reproduce this locally. The problem is that I always open the keybindings screen with the mouse. At least for me, opening the screen with the keyboard seems to be what reproduces the issue. still researching a solution.

**Comment by IdleSol** [comment]
Confirmed. If I use the mouse and don't use the keyboard, I have no problems.

After the keybindings window opens. Press `enter`. Where does the focus go from the window? If it's about the focus at all. Maybe there is a similar signal when using the keyboard?
