### ISSUE TITLE
Certain Recipes have 0 Crafting time, and No Tools needed.

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#72073]
### Describe the bug

So im trying to craft Wheat-Free Flour and I notice that one of the recipes I have has 0 crafting time and no tools needed. I know that shouldnt be, and I don't know why its showing for me. I have not unlocked all recipes through debug since I've looked through all recipes and they are all the recipes I should know based off of current skill levels. 

### Attach save file

[NewEarth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14451029/NewEarth-trimmed.tar.gz)

### Steps to reproduce

1. Check the Food tab 
2. Wheat-Free Flour, Flour, Cornmeal, Bonemeal, Garlic powder, Nut Paste, Seed Paste, (It seems to only appear to recipes that are connected to foods that have a recipe to be ground down like flour/pastes/powders those are the ones I've found) have the 0 craft time, 0 tool needed craft.

### Expected behavior

To not see these recipes.

### Screenshots

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/100801849/f1998409-4f58-4d22-aa15-03b99349b6a1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: a74bf25 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Removes Fungus and Ants [myf_ant_fungal_removal]
]

**Comment by Myfharad** [comment]
Just wanted to highlight I tried a new world with a new character and the problem still persists, even after updating CDDA to the absolute latest build. 19b951c

**Comment by PatrikLundell** [comment]
The recipe is used for milling using a mill, and most of the entries aren't used by the code. The recipe shouldn't be visible to the player ("autolearn": false, with no way to learn it).

I've failed to repeat the issue with a freshly updated and compiled master (the three recipes for wheat free flour I get are the ones expected, i.e. one for each set of tools used).

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.G-7757-g8a1fa0e08a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

It looks like you've somehow managed to get access to all the recipes used for milling using a mill, judging by the number of wheat-free flour recipes you've got in your screenshot.

**Comment by Myfharad** [comment]
> The recipe is used for milling using a mill, and most of the entries aren't used by the code. The recipe shouldn't be visible to the player ("autolearn": false, with no way to learn it).
> 
> I've failed to repeat the issue with a freshly updated and compiled master (the three recipes for wheat free flour I get are the ones expected, i.e. one for each set of tools used).
> 
> * OS: Windows
>   
>   * OS Version: 10.0.19045.4046 (22H2)
> * Game Version: 0.G-7757-g8a1fa0e08a [64-bit]
> * Graphics Version: Tiles
> * Game Language: System language []
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Portal Storms Ignore NPCs [personal_portal_storms],
>   Slowdown Fungal Growth [no_fungal_growth]
>   ]
> 
> It looks like you've somehow managed to get access to all the recipes used for milling using a mill, judging by the number of wheat-free flour recipes you've got in your screenshot.

How weird. Any thoughts as to why it would be doing that on a completely separate world and character? Because it persists onto fresh new worlds…

**Comment by PatrikLundell** [comment]
Not any thought that don't involve changes to files or providing debug access to recipes (and the latter shouldn't carry across worlds, nor, I think, across to new characters in the same world).

Mods can provide file changes, but the only "unusual" mod in your list is the anti ant/fungus one, which I haven't heard of, but it doesn't sound like one that should deal with recipes (although removal of ants might somehow deal with milling of acid ant chitin).

If it was me suffering from this I'd start with installing a fresh copy of C:DDA (not overwriting a previous one) to see if that helps. I'd also try to create worlds with no mods apart from the standard ones, with fairly normal dex/stat ones, and finally with the anti fungus/ant one to find if it's a mod issue.

I'd then proceed to look for anything odd with the recipes by searching for "mill_2_15", as that's the suffix used for the cat tail recipe shown in the image (and that string should be unique, as that's the only recipe using that suffix, and the string isn't something that would normally appear elsewhere), and I'd search both the data/json and mod directories, with the latter in an attempt to catch any override. I'd do the search using Notepad++, but the shitty Windows search may or may not work as a last attempt. Obviously, there may be other suitable tools.
Once the recipe is located (in ...\data\json\recipes\food\milling.json in the base game), I'd verify that `"autolearn": false,` is set for that recipe (that's what makes sure you don't learn the recipe automatically, but only through books, of which there are none).

**Comment by Myfharad** [comment]
> Not any thought that don't involve changes to files or providing debug access to recipes (and the latter shouldn't carry across worlds, nor, I think, across to new characters in the same world).
> 
> Mods can provide file changes, but the only "unusual" mod in your list is the anti ant/fungus one, which I haven't heard of, but it doesn't sound like one that should deal with recipes (although removal of ants might somehow deal with milling of acid ant chitin).
> 
> If it was me suffering from this I'd start with installing a fresh copy of C:DDA (not overwriting a previous one) to see if that helps. I'd also try to create worlds with no mods apart from the standard ones, with fairly normal dex/stat ones, and finally with the anti fungus/ant one to find if it's a mod issue.
> 
> I'd then proceed to look for anything odd with the recipes by searching for "mill_2_15", as that's the suffix used for the cat tail recipe shown in the image (and that string should be unique, as that's the only recipe using that suffix, and the string isn't something that would normally appear elsewhere), and I'd search both the data/json and mod directories, with the latter in an attempt to catch any override. I'd do the search using Notepad++, but the shitty Windows search may or may not work as a last attempt. Obviously, there may be other suitable tools. Once the recipe is located (in ...\data\json\recipes\food\milling.json in the base game), I'd verify that `"autolearn": false,` is set for that recipe (that's what makes sure you don't learn the recipe automatically, but only through books, of which there are none).

I did everything you said, I installed a clean version of CDDA onto a new drive on my PC, I made sure not to add my "No Fungal or Ant" Mod I made (which only removed ant and fungal overmap tiles from spawning) and I started a new game, I put 4 skill points into fabrication, food processing, survival and tailoring. Default evacuee start and I went to search up "Flour" and it still allows me to view the milling recipes that have the 0 craft time and 0 tools needed. I have no clue why. 
![test 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/100801849/e025da5c-ed77-46b7-ab71-bd8d2d4bbe1e)
![test 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/100801849/226c68be-a2a5-4b2c-82c6-dd1aafa349eb)

**Comment by Myfharad** [comment]
Also I checked the milling.json and "mill_2_15" has autolearn false.

**Comment by PatrikLundell** [comment]
Weird. I loaded your save and apart from receiving an error message because I don't have your mod, I repeated your experience, i.e. the recipes that should be hidden were available.
Searching the save file the recipe was listed there among other recipes, and I assume that's the list of learned recipes. However, I haven't found any setting that should make that happen (I believe you can do that with the debug menu, but I assume you definitely didn't do that with your newly created world).

I created a new world with a random character (everything as default as quickly as possible) and debug set all skills to 10. Only the 3 expected wheat-free flour recipes were available to that character.

**Comment by Myfharad** [comment]
> Weird. I loaded your save and apart from receiving an error message because I don't have your mod, I repeated your experience, i.e. the recipes that should be hidden were available. Searching the save file the recipe was listed there among other recipes, and I assume that's the list of learned recipes. However, I haven't found any setting that should make that happen (I believe you can do that with the debug menu, but I assume you definitely didn't do that with your newly created world).
> 
> I created a new world with a random character (everything as default as quickly as possible) and debug set all skills to 10. Only the 3 expected wheat-free flour recipes were available to that character.

I think I found someting! When I made a new character with with default no skills and debugged in Food Handling 4 through the debug menu the 0 craft time 0 tools needed wheat recipe isnt there. 

**BUT** when I put in 4 skills in Food Handling during character creation and check the recipes the 0 craft time 0 tools needed recipes are available.

**Comment by Myfharad** [comment]
My bad I closed it by accident.

**Comment by Myfharad** [comment]
Hopefully you can test to see if that happens to you too.

**Comment by PatrikLundell** [comment]
/confirmed

Yes, I think you found it!

When I increased the Food Handling skill of a character during character creation level 2 added a lot of wheat-free flour recipes, when there should only have been three. This was confirmed when the character was actually created and the crafting recipes brought up: a lot of recipes that should remain unavailable were present.

Thus, it seems there is something missing in the character creation recipe selection that's present in the skill gain selection.

**Comment by RenechCDDA** [comment]
Ah, yes that's technically how it's supposed to work (explicitly overriding autolearn).

Just slap the SECRET flag on the recipes, that'll stop it.

**Comment by PatrikLundell** [comment]
Ah, thanks. I assume the syntax is `"secret" true,`?

**Comment by RenechCDDA** [comment]
No, it's actually a flag (yes recipes have flags). Here's an example.

https://github.com/CleverRaven/Cataclysm-DDA/blob/8a1fa0e08a002a9158eed65f3e457cc6f563aaba/data/json/recipes/armor/bespoke_armor/nomad.json#L83

**Comment by PatrikLundell** [comment]
Thanks, glad I asked...
