### ISSUE TITLE
Bombastic perks crash when selecting perk

### ISSUE THREAD

**Issue by Coach-mdl** [CleverRaven/Cataclysm-DDA#72075]
### Describe the bug

Selecting a perk to buy causes a crash straight. Perks that have caused it are Thick Skull and Tougher or whatever it's called. The one with 5% damage reduction to all limbs. I don't believe it's just these perks though.

### Attach save file

[It's all coming together-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14451731/It.s.all.coming.together-trimmed.tar.gz)

### Steps to reproduce

1. Level up, two kills should do it. Watch out for the zombie dinos to the south. 2. Spend skill point on Thick Skull. Game should immediately crash.

### Expected behavior

It should purchase the skill.

### Versions and configuration

cdda-windows-tiles-sounds-x64-2024-02-26-0341
Windows 10
Modlist: 
  "dda",
  "skyisland",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "magiclysm",
  "mindovermatter",
  "DinoMod",
  "bombastic_perks",
  "crazy_cataclysm",
  "extra_mut_scens",
  "MMA",
  "sees_player_retro",
  "StatsThroughSkills",
  "minimod_no_rust",
  "speedydex"

### Additional context

No Rust is unlikely to be an issue, so id remove it from the mod list. If it is I will eat a cardboard box. Sorry if this is a duplicate of another issue.

**Comment by RenechCDDA** [comment]
Update your install, this was resolved in #71995
