### ISSUE TITLE
[Android] Game data outside Android/data, for real this time

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72086]
### Is your feature request related to a problem? Please describe.

I know this was brought up multiple times, and I know this is probably a duplicated issue.
But I felt like this had to be brought up again.

The latest 'security' update on Android 14, which happened a day or two ago, just blocked most or all the workarounds to gain read and write access to the root dictionary. 
Now there's barely any workaround available. It's nearly impossible for Android 11 or above users to gain access to the game data. (excluding using a PC or laptop but you know why this was brought up)

I really think this is critical. Imagine not being able to post debug/crash.log, unable to access the widely customizable game aspects, etc...

### Solution you would like.

From my experience, some apps create separate files for easy access.
ex)
FL Studio Mobile allows people to save or load projects and creations.
PPSSPP, an open-source PSP emulator project, has a folder that allows people to insert their games/import & export textures/edit save data.

Similar to those, Cataclysm DDA could have a separate folder outside Android/data for accessing saves, JSONs, mods, tilesets, etc.

### Describe alternatives you have considered.

Making a whole dedicated app or feature that allows editing the game data?

### Additional context

I'm not sure if this is going to be closed for duplicate, but I think it was worth opening a new issue.

**Comment by AnotherSeawhite** [comment]
GettingUsedTo taught me a workaround. Using Shizuku and ZArchiver should work.
For anyone having the same issue, I can't give the exact procedures, but there should be a tutorial on internet.

**Comment by Qrox** [comment]
I think in the PC version you can customize the save location by passing paramters to the executable, so customizable save location on Android would be very nice. I don't quite understand the access permission problem though; If Shizuku or ZArchiver can access the data there, I don't see a reason why a file explorer app cannot do the same.

**Comment by pwalsh0** [comment]
I had to use Total Commander to copy in soundpacks - is this what people are complaining about? 

It's a bit annoying but easily solved by just using a different file manager?

**Comment by AnotherSeawhite** [comment]
> It's a bit annoying but easily solved by just using a different file manager?

Apparently, it doesn't seem that easy. I'm not sure about other Android versions, but I'm using Android 14 and had this issue.

**Comment by pwalsh0** [comment]
> > It's a bit annoying but easily solved by just using a different file manager?
> 
> Apparently, it doesn't seem that easy. I'm not sure about other Android versions, but I'm using Android 14 and had this issue.

So am I. Just use a different file manager. Stock android doesn't even come with a file manager I think.

**Comment by AnotherSeawhite** [comment]
> So am I. Just use a different file manager. Stock android doesn't even come with a file manager I think.

Stock android does come with a file manager, and it used to let you access through data.
Also, I kid you not, I tried almost every other file managers.
