### ISSUE TITLE
Some menus are blank. Part 2

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72091]
### Describe the bug

Confirmation window for saving changes. Missing window text.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/7373eac1-c979-4df6-a731-4c0c6db41ca6)

### Versions and configuration

cdda-windows-tiles-x64-2024-03-01-0629

### Additional context

Not only in settings, but also in other windows that ask for confirmation to save changes.

@katemonster33

**Comment by IdleSol** [comment]
Fixed window size?

Warning about using the debug menu
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/5cb413ec-0193-4f6b-bc05-ce1968bd3870)

A question about butchering a human corpse
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/650de9bb-d8fb-4166-8406-c33fbc64b2b5)

**Comment by katemonster33** [comment]
looks like my earlier change to remove auto-sizing of the popup caused it to be too small to fit the text and the buttons. I made a PR.

**Comment by katemonster33** [comment]
@IdleSol  can you please test the linked PR

**Comment by IdleSol** [comment]
I'll check it out after it's merged.

**Comment by katemonster33** [comment]
i dont want to cause another regression, i won't merge it until it's tested

**Comment by IdleSol** [comment]
If you can explain to me how I can test this, without compiling from source. Then I can try.

Do I understand correctly that everything is fine with you?

**Comment by IdleSol** [comment]
cdda-windows-tiles-x64-2024-03-02-2045

It's working.
![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/33c9bbb4-5daa-4343-9c91-ec9b51938ce8)
