### ISSUE TITLE
American Flag as component requiered to craft a makeshift sling

### ISSUE THREAD

**Issue by Bullk9ng** [CleverRaven/Cataclysm-DDA#72094]
### Is your feature request related to a problem? Please describe.

American Flag cannot be Disassembled.

### Solution you would like.

I'd like to be able to Disassemble a flag for crafting material, particularly for crafting a makeshift sling.

**Comment by Rokharn** [comment]
I am pretty sure, using any flags at any ways for crafts is a very bad idea if looking at real world laws. Certain laws should definitely be respected even in the game, because the game may be subject to certain laws.

**Comment by Bullk9ng** [comment]
Really? A piece of cloth when painted with specific colors, magically looses its cloth structure and becomes a relic subject to believes and ideologies? By the way, "real world laws" are discoverable e.g law of thermodynamics or gravity, man-made-regulations (do as I say) are not real laws, they're just make-believe.

**Comment by Rokharn** [comment]
If in games it becomes possible to break country flags into rags, this could become the basis for legal cases, because it falls under a number of legal laws in most countries around the world. So it's surely very bad idea.

**Comment by Bullk9ng** [comment]
Sure, sure, just like harming someone's else's property, or another character, or even imagine killing? wao! that would be preposterous, imagine what would happen if all those things were allowed or permitted in games right?

**Comment by Rokharn** [comment]
There are things that cannot be done in games, but there are those that are acceptable. The laws of different countries, including even amendments to the legislative framework of states within the United States, always have very specific prohibitions on what is permissible in games.
  
If you really want this feature, you can make it yourself for one minute.

**Comment by TheShadowFerret** [comment]
We don't block flags from being burnt or cut up now, this complaint is not valid.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/99621099/29f48c9c-00a3-44d9-8938-f4e4b5a12770)

**Comment by Bullk9ng** [comment]
Ah great, thanks TheShadowFerret!
