### ISSUE TITLE
ImGui window. Default answer choice

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72093]
### Describe the bug

Pay attention to the default choice. Using the character template selection question as an example.

Without imGui - load, with imGui - cancel.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

Use imGui UI: ```true```. Default choice: cancel
![4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/f92e9af6-223e-499d-905a-ca9e3ed51282)

Use imGui UI: ```false```. Default selection: load
![5](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/c0487e21-0820-4226-b7f6-483ea282a874)

### Versions and configuration

cdda-windows-tiles-x64-2024-03-01-0629

### Additional context

@katemonster33

**Comment by Brambor** [comment]
Can confirm.

0. Having imgui set to false in options
1. Launch the game
2. Settings -> Options -> Interface
3. Use Imgui UI set to true
4. ESC to escape menu
5. Empty popup appears
 ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/01a44951-d508-4624-b087-f85ffb888db4)

Having imgui set to true in options
1. open keybindings
2. add already used keybinding to something
3. (presumably) The conflict menu appears, but it is blank
4. You would expect the menu to not be empty
 ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/d31d3e88-07a4-4d63-8b6c-27df304221cb)
6. Furthermore, closing keybindings menu, popup should appear "Save changes" - but it is empty again
 ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/c2e1aadd-8d99-4f52-beb8-9c6e2fc46727)


Note: the above happens only with Imgui UI, the curses UI works as expected

**Comment by Brambor** [comment]
Probably the same problem as #72091

**Comment by Brambor** [comment]
Sorry, I didn't read this properly.

My problem is unrelated and resolved.
