### ISSUE TITLE
Hollow-bones are Not Osteoporosis-affected-bones

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#72095]
### Is your feature request related to a problem? Please describe.

There have been discussions about hollow bones mutation like https://github.com/CleverRaven/Cataclysm-DDA/issues/48406

As mentioned above, hollow bones are not lighter(and that's how DDA deals with it right now). Furthermore, they are even stronger than mammal bones in general.

Light bones, or Osteoporosis-affected-bones, are more fragile of course, but bird bones are denser as well, and studies have shown that as as bone density increases, so do bone stiffness and strength. The pneumatized structure of hollow bones even gives birds cardio bonus (They can take in oxygen while both inhaling and exhaling)! So, the description _Your body is very light but also FRAIL_, and <1  weight_capacity_modifier, of the hollow bones mutation, may not be as realistic as it seems.

On the other hand,  hollow bones tend to shatter and splinter while mammal bones tend to break relatively cleanly. Therefore, the EXTRA_BASH damage debuff seems like a good design. And IMO, a <1 mending_modifier should also be implemented, both for game balance and for realistic reason (higher risk of comminuated fracture).

https://www.discovery.com/nature/Why-Do-Birds-Have-Hollow-Bones

https://avesbiology.com/birdrespiration.html

https://ornithology.com/bird-bones-2/

https://www.researchgate.net/publication/335927510_Fracture_Analysis_of_Wild_Birds_in_South_Korea

I've noticed that @fairyarmadillo has been dealing with the bird wings mutation recently, what do yo think of these things?

### Solution you would like.

Change the stats of  hollow bones mutation:
Remove <1 weight_capacity_modifier
Stamina_regen_modifier/cardio_multiplier enhancement (15% is ideal, see https://avesbiology.com/birdrespiration.html#:~:text=Exchange%20of%20gases%3A,Maina%20et%20al.%201989).)
Add <1 mending_modifier

### Describe alternatives you have considered.

Maybe a nerf of movecost_modifier/attackcost_modifier to light bones/hollow bones mutation as well?
Osteoporosis doesn't make you a good runner/fighter. Hollow-bones may bring some benefits, but 20% is enormous.

### Additional context

N/A

**Comment by fairyarmadillo** [comment]
Hollow bones aren't just human bones which have become hollow, they're a further modification of light bones, which are human bones that have reduced in density and possibly thickness. So they should definitely keep the weight capacity modifier.

If you implement a cardio modifier, they should probably lose their move and attack speed modifier, as they're both sort of representing the same thing, and the move+attack speed mods were simply added before the cardio system. This will be a big downgrade for the mutation, but it might be more representative of actual bird bones.
