### ISSUE TITLE
Keep legacy content as part of an option or mod

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72103]
### Is your feature request related to a problem? Please describe.

My 0.G playthrough is now filled with nether chewed grounds because things that i really enjoyed like the valhallists and the railway stations got removed, as well as the option for not having skill rust, etc.

### Solution you would like.

Either replace those nether chewed ground tiles with something more appealing, like keeping the old tiles, or have an option to keep the legacy content in some shape or form like through a mod or an option.

### Describe alternatives you have considered.

I know those features got removed because either they needed to be reworked or were causing problems, but i imagine there are less debilitating options of dealing with them than just transforming them into "deleted" grounds. What will happen to that primitive camp when it gets reintroduced in 0.I? maybe by keeping them as is they could get updated more easily?

### Additional context

At least give the players the agency.

**Comment by RenechCDDA** [comment]
No, content is removed when it is not fit for the game. Keeping it around means maintaining it, which defeats the entire purpose and means that the game is saddled with an ever-increasing amount of debt to support completely useless, unwanted things.

If you want these, feel free to maintain them yourself. Nothing is stopping you.

**Comment by Qrox** [comment]
We could add migration code to turn removed overmap tiles to similar tiles like what is done for items though.

**Comment by RenechCDDA** [comment]
The local terrain should still be intact, this is really just a case of overmap cosmetics. There are no reasonable migrations for something like `valhallist_camp_1b` (made-up example), and it would again mean more maintenance.
