### ISSUE TITLE
Crash in imgui (maybe around keyboard layout switching?)

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#72102]
### Describe the bug

I think this might be happening around when I switch keyboard layouts?

```
Assertion failed: ((io.KeysDown[n] == false || IsKeyDown((ImGuiKey)n)) && "Backend needs to either only use io.AddKeyEvent(), either only fill legacy io.KeysDown[] + io.KeyMap[]. Not both!"), function UpdateKeyboardInputs, file imgui.cpp, line 8422.
```

### Attach save file

N/A

### Steps to reproduce

Haven't been able to reliably repro yet.

### Expected behavior

No random crashing in imgui, especially when imgui is not enabled 😅 

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3; Build: 23D56; 
- Game Version: 0.G-7695-g60757df3a8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by nornagon** [comment]
Unfortunately my build didn't have symbols in it, but `UpdateKeyboardInputs` is only called from one place (in `ImGui::NewFrame`), and `ImGui::NewFrame` is only called in one place (ignoring imtui), via `ui_adaptor::redraw_invalidated`. So that's at least the top few frames. If I get a complete stack trace I'll attach it here.

**Comment by nornagon** [comment]
(also, the assert is behind `#ifndef IMGUI_DISABLE_OBSOLETE_KEYIO`, which sounds maybe like we could build with that defined?)

**Comment by nornagon** [comment]
ohh, this might be something to do with having both imgui and imtui built. It looks like imtui uses the legacy keyio system, but the SDL backend uses the new one. This assert might crop up if we're somehow feeding keypresses into both imtui and imgui?

**Comment by katemonster33** [comment]
Yeah maybe this is imtui-related

**Comment by katemonster33** [comment]
Sorry, I just noticed you're on a tiled build... ImTui should not be compiled in. There is no way that I'm aware that both ImTui and SDL backend could be running at the same time. 
Have you found a path to reproduce it? What keyboard layouts do you use?

**Comment by nornagon** [comment]
Here's a symbolicated stack trace:
```
Assertion failed: ((io.KeysDown[n] == false || IsKeyDown((ImGuiKey)n)) && "Backend needs to either only use io.AddKeyEvent(), either only fill legacy io.KeysDown[] + io.KeyMap[]. Not both!"), function UpdateKeyboardInputs, file imgui.cpp, line 8422.
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.G-7695-g60757df3a8-dirty
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

    0   cataclysm-tiles                     0x0000000104c57c98 debug_write_backtrace(std::__1::basic_ostream<char, std::__1::char_traits<char>>&) + 72
    1   cataclysm-tiles                     0x0000000104c17c00 log_crash(char const*, char const*) + 440
    2   cataclysm-tiles                     0x0000000105de39b8 signal_handler(int) (.cold.1) + 48
    3   cataclysm-tiles                     0x0000000104c1793c crash_terminate_handler() + 0
    4   libsystem_platform.dylib            0x00000001839b1a24 _sigtramp + 56
    5   libsystem_pthread.dylib             0x0000000183981cc0 pthread_kill + 288
    6   libsystem_c.dylib                   0x000000018388da40 abort + 180
    7   libsystem_c.dylib                   0x000000018388cd30 err + 0
    8   cataclysm-tiles                     0x0000000105df7dd8 ImGui::NewFrame() (.cold.30) + 0
    9   cataclysm-tiles                     0x0000000105bb2af8 ImGui::NewFrame() + 13140
    10  cataclysm-tiles                     0x0000000105c6fef8 ui_adaptor::redraw_invalidated() + 100
    11  cataclysm-tiles                     0x000000010520c064 loading_ui::show() + 32
    12  cataclysm-tiles                     0x0000000104e48754 game::load(save_t const&) + 1056
    13  cataclysm-tiles                     0x0000000105288320 main_menu::load_game(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, save_t const&) + 240
    14  cataclysm-tiles                     0x0000000105289180 main_menu::load_character_tab(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 1472
    15  cataclysm-tiles                     0x000000010528748c main_menu::opening_screen() + 4660
    16  cataclysm-tiles                     0x000000010527bf98 main + 4348
    17  dyld                                0x00000001836010e0 start + 2360
```

and I think I was able to repro this by pressing a key down, switching keyboard layouts (between QWERTY and Dvorak), then releasing the key. Though not especially consistently! This is the most reliably way I've found to trigger the crash though.
