### ISSUE TITLE
Error due to removed mission in diary

### ISSUE THREAD

**Issue by Water-Moon** [CleverRaven/Cataclysm-DDA#72107]
### Describe the bug

An error will occur if a dairy entry contains a mission that have since been **removed**. (Not completed, but rather removed - such as portal storm mission)

### Attach save file

N/A. Not save specific - reproducible in any save.

### Steps to reproduce

1. Cause a portal storm by running the eoc `EOC_CAUSE_EARLY_PORTAL_STORM` in debug menu.
2. There is now the mission of "Center of storm". 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/43123946/5333072d-7356-43da-bdac-92ddef978451)
3. Make a diary page. It will now indicate this as a new mission in the stats. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/43123946/7d164c2c-034b-4eee-9095-f081e95052f4)
4. Stop the portal storm by running the eoc `EOC_CANCEL_PORTAL_STORM`. Or wait it out.
5. Open your diary. Move to another entry, then move back to the entry created during portal storm. On loading the entry, it will throw an error, due to the mission being removed.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/43123946/08578cc5-e823-410d-ac23-3b1e6d9f8627)

*Note that this issue is more pronounced in mods where mission are constantly added and removed. For example, sky island mod, or any other mod containing significant use of `remove_active_mission` EOC effect. 
*It could affect the game play if one use diary for keeping notes while playing such mods, as it results in frequent error message.

### Expected behavior

An error does not occur. 
Preferably, the mission name and description is still kept in the diary entry.

### Screenshots

See *Steps to reproduce*

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: 9eaa5d4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

Edit: Also tested on 0.H branch [5d069f2](https://github.com/CleverRaven/Cataclysm-DDA/commit/5d069f2eaccd125d22b53617ba73ce7fab157a9f). The error also occurs there. In fact, the relevant functions (see below) have not been updated for a prolonged period, likely before 0.H was created.

### Additional context

There is only these two lines in the log related to this:
```
16:15:51.270 ERROR GAME : src/mission.cpp:94: requested mission with uid 6 does not exist
16:15:51.270 ERROR : src/mission.cpp:95 [static mission* mission::find(int, bool)] requested mission with uid 6 does not exist
```

Investigating the code indicates that the above methods are invoked from `diary::mission_changes`.

The full reason is due to the storage format. Diary stores IDs of the missions assigned to the player. When a page is loaded, functions will be invoked to obtain mission name from ID, (compare the difference between current page and previous page to determine the items to display). If a mission has since been removed, loading the mission for that ID will cause an error.

Investigating the [`diary::mission_changes`](https://github.com/CleverRaven/Cataclysm-DDA/blob/9eaa5d442581542cb536a8133b7e8252ac0faa69/src/diary.cpp#L124) reveals that infrastructure to handle a missing mission indeed exist, and is checked when the return of `mission::find` is null pointer. [`mission::find`](https://github.com/CleverRaven/Cataclysm-DDA/blob/9eaa5d442581542cb536a8133b7e8252ac0faa69/src/mission.cpp#L87`) also contains field `missing_ok` to gracefully handle the error. However, the field is not set by ``diary::mission_changes``, and [defaults to false](https://github.com/CleverRaven/Cataclysm-DDA/blob/9eaa5d442581542cb536a8133b7e8252ac0faa69/src/mission.h#L413), resulting in the error.

Purposed simple solution is to modify `diary::mission_changes`, adding `true` as the second parameter to `mission::find` calls [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/9eaa5d442581542cb536a8133b7e8252ac0faa69/src/diary.cpp#L137) and [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/9eaa5d442581542cb536a8133b7e8252ac0faa69/src/diary.cpp#L161), so an error will not be thrown if the mission does not exist.

If possible, a better solution is to allow still displaying the missions even if they are removed. However, this may require introducing new struct to store id, name and description of each mission, and modifying serialization to output such struct as JSON Objects. Migration from old storage format will also be necessary if such solution is implemented.

**Comment by Milopetilo** [comment]
/confirm (am I allowed to do that?)
Still happens in latest experimental - 0f9df4f
