### ISSUE TITLE
Px4 Storm magazines not functioning in Cx4

### ISSUE THREAD

**Issue by RadioAndrea** [CleverRaven/Cataclysm-DDA#72129]
### Describe the bug

The Px4 Storm pistol magazines should be compatible with the Cx4 Storm rifle, in addition to the M9 magazines it currently uses.

### Attach save file

N/A

### Steps to reproduce

1. Wield a Cx4 Storm with a Px4 magazine in inventory
2. Attempt to reload the Cx4 Storm
3. There is nothing to reload!

### Expected behavior

The Cx4 Storm is loaded with the Px4 magazine

### Versions and configuration

- OS: Linux
- Game Version: 669a9fc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
]

**Comment by TheShadowFerret** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/99621099/d059523a-22b2-4235-9661-30b39c0ef52e)

https://www.beretta.com/en-us/product/beretta-px4-magazine-9mm-20-rounds-unpackaged-C89166
You need a magwell adapter to do this IRL, not a bug.

**Comment by RadioAndrea** [comment]
In this case, perhaps there should be a second variant of the right made the uses **only** Px4 magazines!

**Comment by kevingranade** [comment]
As outlined,  feel free to add mag inserts or something but it's not a bug.
