### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#72125]
### Describe the bug

the game crashes periodically, in various situations, the problem seems to arise if you don’t save for a long time, or do a lot of moving objects and movements in one place

### Attach save file

None

### Steps to reproduce

None

### Expected behavior

I will continue to watch and post logs...

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: 8a1fa0e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14470249/crash.log)

**Comment by andrei8l** [comment]
#72116 should fix it
