### ISSUE TITLE
Error: Invalid enum string 'MOVECOST_FLATGROUND_MOD' for 'enum enchant_vals::mod' Version 7fab443 with Arcana and Magic mod

### ISSUE THREAD

**Issue by Alpacci** [CleverRaven/Cataclysm-DDA#72134]
### Describe the bug

When creating new character in world with Arcana and Magic mod, error occurs as mod files load. If continue or ignore error, will be taken back to the main menu.

### Attach save file

N/A

### Steps to reproduce

Add latest Arcana and Magic DDA mod to mod folder
Open game
Create new world and select Arcana and Magic mod
Create character in new world with Arcana and Magic DDA mod
Error shows

### Expected behavior

I expected there to be no issues

### Screenshots

![Bug](https://github.com/CleverRaven/Cataclysm-DDA/assets/162005274/928853ac-6d1e-43a0-9d5c-38a033d3211d)

### Versions and configuration

Version: cdda-windows-tiles-sounds-x64-msvc-2024-02-02-0710
OS: windows 10
Tiles
English
Arcana and Magic mod DDA version loaded

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14472076/debug.log)

**Comment by andrei8l** [comment]
/invalid
Your version is too old. `MOVECOST_FLATGROUND_MOD` was added in [this release](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-02-27-2243)
