### ISSUE TITLE
Failing Text Changes Analyzer build

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#72137]
### Describe the bug

**Text Changes Analyzer** build fails on "Generate translation template on test merge commit" step.
[Exception](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8129393503/job/22216453190?pr=71934#step:5:59) when parsing JSON data type "body_part" while Extracting strings from JSON files commited in #71896 (Limb_WIP mod).
`"type": "body_part"` JSON objects are missing [mandatory fields](https://github.com/CleverRaven/Cataclysm-DDA/blob/4f3b1cc51c9c917402f32070d0b96ca322341880/doc/JSON_INFO.md?plain=1#L1029).

### Attach save file

N/A

### Steps to reproduce

Exception on Text Changes Analyzer build.

### Expected behavior

Passed Text Changes Analyzer.

### Versions and configuration

N/A

**Comment by SurFlurer** [comment]
It seems to be the same issue as #72046.

**Comment by AMurkin** [comment]
You're right. Then it adds some details to the issue, and is linked now. Closing.
