### ISSUE TITLE
npctalk.cpp operation talk_effect_fun_t::func f_revert_location odd tinymap usage

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#72136]
### Describe the bug

This is not a bug report in the sense that there is any indication the code doesn't work.
However, the code seems to be doing more work than it ought to have to do:

- tinymap is loaded inside the loop, even though a single load would cover the complete area the code is concerned with.
- The loaded tinymap isn't used for any visible purpose.

### Attach save file

N/A. It's in the source code.

### Steps to reproduce

1. Examine the code of npctalk.cpp operation talk_effect_fun_t::func f_revert_location( const JsonObject &jo, std::string_view member ) at around line 3900.

### Expected behavior

The tinymap object tm isn't used after the map has been loaded. Instead, submaps are loaded from the MAPBUFFER. I cannot rule out the possibility that the code relies on some side effect of the destruction of the tinymap object, however, although there is also an invalidation of the map cache of the map (done 4 times, rather than once).

What I think the relevant part of the code should look like:
```
    return [target_var, dov_time_in_future, key]( dialogue & d ) {
        const tripoint_abs_ms abs_ms( get_tripoint_from_var( target_var, d ) );
        tripoint_abs_omt omt_pos = project_to<coords::omt>( abs_ms );
        time_point tif = calendar::turn + dov_time_in_future.evaluate( d ) + 1_seconds;
        // Timed events happen before the player turn and eocs are during so we add a second here to sync them up using the same variable
        // maptile is 4 submaps so queue up 4 submap reverts
        const tripoint_abs_sm revert_sm_base = project_to<coords::sm>(omt_pos);

        for( int x = 0; x < 2; x++ ) {
            for( int y = 0; y < 2; y++ ) {
                tripoint_abs_sm revert_sm = revert_sm_base + point(x, y);
                submap *sm = MAPBUFFER.lookup_submap( revert_sm );
                if( sm == nullptr ) {
                    sm = MAPBUFFER.lookup_submap( revert_sm );
                }
                get_timed_events().add( timed_event_type::REVERT_SUBMAP, tif, -1,
                                        project_to<coords::ms>( revert_sm ), 0, "",
                                        sm->get_revert_submap(), key.evaluate( d ) );
            }
        }

        get_map().invalidate_map_cache(omt_pos.z());
    };

```
What the code looks like originally:
```
    return [target_var, dov_time_in_future, key]( dialogue & d ) {
        const tripoint_abs_ms abs_ms( get_tripoint_from_var( target_var, d ) );
        tripoint_abs_omt omt_pos = project_to<coords::omt>( abs_ms );
        time_point tif = calendar::turn + dov_time_in_future.evaluate( d ) + 1_seconds;
        // Timed events happen before the player turn and eocs are during so we add a second here to sync them up using the same variable
        // maptile is 4 submaps so queue up 4 submap reverts
        for( int x = 0; x < 2; x++ ) {
            for( int y = 0; y < 2; y++ ) {
                tripoint_abs_sm revert_sm = project_to<coords::sm>( omt_pos );
                revert_sm += point( x, y );
                submap *sm = MAPBUFFER.lookup_submap( revert_sm );
                if( sm == nullptr ) {
                    tinymap tm;
                    tm.load( revert_sm, true );
                    sm = MAPBUFFER.lookup_submap( revert_sm );
                }
                get_timed_events().add( timed_event_type::REVERT_SUBMAP, tif, -1,
                                        project_to<coords::ms>( revert_sm ), 0, "",
                                        sm->get_revert_submap(), key.evaluate( d ) );
                get_map().invalidate_map_cache( omt_pos.z() );
            }
        }
    };

```
If the tinymap object serves a purpose by doing things on its destruction, I would expect it to do so even if created outside the loop as it covers the complete area iterated over.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.G-7795-g4f3b1cc51c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I'm trying to continue to transform the map code to use typed tripoints rather than untyped ones, and encountered this issue when trying to load tinymaps using tripoint_abs_omt instead of untyped versions of tripoint_abs_sm.
I think it's better to ask for advice separately rather than burying it into a PR later, especially since it doesn't seem to be easily tested.

**Comment by SurFlurer** [comment]
I'm not particularly familiar with map code, but according to the comments for `map::load`,

>  Load submaps into grid. This might create new submaps if the mapbuffer can not deliver the requested submap (as it does not exist on disc).

it does make sense that, when the map at `revert_sm` hasn't been created ( thus sm == nullptr ), calling `map::load` will create it and load it to the mapbuffer so that calling `MAPBUFFER.lookup_submap` again returns a valid pointer.

> even if created outside the loop as it covers the complete area iterated over. 

As the comment in the original code block goes, An overmap tile is consisted of 4 submaps. So I don't think a single tinymap can cover the complete area iterated over.

> // maptile is 4 submaps so queue up 4 submap reverts

**Comment by PatrikLundell** [comment]
Thanks for the comment! It absolutely makes sense.

An overmap tile is 2*2 submaps, and so is a tinymap, so they fit perfectly.

I'll go ahead and load the tinymap above the loop preemtively, which means there is no need to check for the submap within the loop.

**Comment by SurFlurer** [comment]
> An overmap tile is 2*2 submaps, and so is a tinymap, so they fit perfectly.
> I'll go ahead and load the tinymap above the loop preemtively, which means there is no need to check for the submap within the loop.

I think a tinymap is the same size as a submap. So I doubt loading the tinymap preemptively will work, as there's 4 different  submaps that needs to be loaded.
