### ISSUE TITLE
Add personality to chargen

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#72157]
### Is your feature request related to a problem? Please describe.

The player can give up control of their character to play another at the faction board. Doing this turns their PC into an NPC. But that NPC has no personality set.

### Solution you would like.

It would be nice if this NPC could have personality traits/scores like other NPCs can. I think the best way to do this would be to add them to the chargen menu, especially if they could be put somewhere apart from the other traits, maybe even on a different panel. There's a bunch of empty space on the stats panel, could that become like, "attributes"? 

I'm sure most people will make their guy a heroically brave altruist but we have a freeform system so that's fine.

This would also help the player understand what NPC personalities mean when they encounter them in the wild.

### Describe alternatives you have considered.

We could probably also use a personality editor in the debug menu. I know we have traits but IIRC the hidden scores are still separate, right?

**Comment by IdleSol** [comment]
Can we evaluate a player's actions? And assign personality traits based on the results. Something like, refuses a reward - altruistic, takes money - greedy.

**Comment by fairyarmadillo** [comment]
I doubt it. That would be an enormous undertaking for almost no benefit.

**Comment by AnotherSeawhite** [comment]
How about tying it with buffs&debuffs? ex. If the player with Coward personality is facing a massive threat, they'll have debuffs on intelligence or perception, implying the character is scared and want to flee.

**Comment by fairyarmadillo** [comment]
That really is well beyond what I'm suggesting here, which is a simple addition to the character creation menu.

**Comment by AnotherSeawhite** [comment]
~~sorry i brainstormed a bit too much~~
