### ISSUE TITLE
Planters disappear when crops in them mature

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#72158]
### Describe the bug

Planters disappear when the crops growing in them reach the stage "mature".

### Attach save file

N/A

### Steps to reproduce

1. Start a game in autumn or summer.
2. Find a greenhouse or a community garden.
3. Examine a tile with a harvesteble or a mature plant.
4. Harvest a plant.
5. Notice how there is no planter.

### Expected behavior

Expected planters to not be consumed when growing plants, they are quite big and expensive after all.

### Versions and configuration

Game version: dd1adff

**Comment by RenechCDDA** [comment]
Unable to confirm, please provide a safe for this issue.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/bda44395-cb59-43b1-a93b-195f0afbbe82)

**Comment by SSpook** [comment]
[debuggie-trimmed1.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14479748/debuggie-trimmed1.tar.gz)
[debuggie-trimmed2.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14479749/debuggie-trimmed2.tar.gz)
Here's 2 saves, before and after waiting 2 seasons at a greenhouse. There's planters with mature plants in the first one and harvestable plants without planters on the second one.

**Comment by RenechCDDA** [comment]
In the first save, the furniture type is `f_planter_mature` but in the second save the furniture type has changed to `f_plant_harvest` (a raw plant furniture! not a planter!). Most curious.
