### ISSUE TITLE
Imgui y/n query popup fails to display translated string on Windows

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#72162]
### Describe the bug

Imgui y/n query popup fails to display translated string on Windows.

### Attach save file

N/A

### Steps to reproduce

1. Change language setting to Chinese.
2. Restart the game.
3. Press 'q' to try to quit the game.
4. The y/n popup appears with an unrecognizable string.

### Expected behavior

I expect that translated string appears on the screen, instead of "????????"

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/fcd41362-3f31-417a-a86f-b187c73a9a36)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0.G-7807-g2ba772a1dd-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: 中文 (天朝)<color_dark_gray>（92.9%）</color> [zh_CN]
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth]
]

**Comment by ZeroInternalReflection** [comment]
I did some further testing on how the fonts get loaded in and the resource usage thereof.  In addition to the languages discussed above, this probably also impacts any language using Cyrillic characters, though that should be a relatively easy fix.

First, the good news:
The following patch seems to work to display everything (I cannot _read_ Chinese, Japanese, Korean, or any variety of Cyrillic, but there did not appear to be any symbols missing when looking through the keybinding screen)
```
diff --git a/src/sdl_font.cpp b/src/sdl_font.cpp
index 24652f80fdb..886725037ed 100644
--- a/src/sdl_font.cpp
+++ b/src/sdl_font.cpp
@@ -304,15 +304,21 @@ CachedTTFFont::CachedTTFFont(
 #if !defined(__ANDROID__)
     ImGuiIO &io = ImGui::GetIO();
     if( io.FontDefault == nullptr && typeface.find( "unifont" ) != std::string::npos ) {
-        static const std::array<ImWchar, 17> ranges = {
-            0x0020, 0x052F,
+        static const std::array<ImWchar, 29> ranges = {
+            0x0020, 0x052F, // Includes English, Latin, Greek & Coptic
             0x1D00, 0x1DFF,
-            0x2000, 0x20CF,
+            0x2000, 0x20CF, // General Punctuation
             0x2100, 0x214F,
             0x2190, 0x22FF,
             0x2500, 0x27BF,
+            0x3000, 0x30FF, // CJK Symbols and Punctuations, Hiragana, Katakana
+            0x3131, 0x3163, // Korean alphabets
+            0x31F0, 0x31FF, // Katakana Phonetic Extensions
+            0x4e00, 0x9FAF, // CJK Ideograms
+            0xAC00, 0xD7A3, // Korean characters
             0xC900, 0xC9FF,
-            //0x0020, 0xCFFF,
+            0xFF00, 0xFFEF, // Half-width characters
+            0xFFFD, 0xFFFD, // Invalid
             0
         };
         io.FontDefault = io.Fonts->AddFontFromFileTTF( typeface.c_str(), fontsize, nullptr, ranges.data() );

```

![ImGui_HW_SimplifiedChinese_Display](https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/e513d727-91ce-4668-849b-40228a539a85)

Now, the bad news:
Using hardware acceleration (in my case opengl), I did some checks on VRAM usage.  The current configuration uses ~15MB on the main menu, and ~150MB loaded into the evac centre using UltiCa.

Loading the full set of glyphs using the code above and setting the language to Chinese uses 150MB of VRAM in the main menu.  Whether that's merge-able isn't my call, but I'm betting it's at least debatable.

Interestingly, the VRAM only appears to be used once you start _using_ a batch of glyphs.  Loading the full set but keeping the language as English kept the usage to 19MB on the menu.  So there's probably not much point in trying to dynamically load only the glyphs of the current language.

The "[ChineseSimplifiedCommon](https://github.com/ocornut/imgui/blob/6b7358e9f36b7faa37ae40704aafc4341eb62020/imgui_draw.cpp#L3317)" range from ImGui seems promising, in that it used 35MB and I did not spot anything missing on the Keybindings screen (The screenshot above is actually from that test).  Of course, whether that collection is everything we need is a question for someone who can actually _read_ the language.  Unfortunately, that still leaves Japanese and Korean to manage, and I don't think there's a similar "Common usage" range established for them.

**Comment by Qrox** [comment]
Maybe we should try to implement the previous glyph caching logic in the ImGUI source.

> The "[ChineseSimplifiedCommon](https://github.com/ocornut/imgui/blob/6b7358e9f36b7faa37ae40704aafc4341eb62020/imgui_draw.cpp#L3317)" range from ImGui seems promising

That should work in most cases but we occasionally (but commonly enough) use characters outside that range, and people might want to enter rare characters into their diary or character name. For example the source refered by the link above (https://zh.wiktionary.org/zh-hans/Appendix:%E7%8E%B0%E4%BB%A3%E6%B1%89%E8%AF%AD%E5%B8%B8%E7%94%A8%E5%AD%97%E8%A1%A8) lists "嘎" as a character not in that list, however "嘎" is commonly used to describe sound such as a duck's quack.

**Comment by katemonster33** [comment]
I need to study up on ImGui glyph caching. If I understand properly, we could build a more dynamic system, where we react when an unknown glyph is typed or written into a widget, add the glyph range into the cache dynamically.

There would be caveats to this approach. You have to rebuild the font glyph cache when editing it, and so there would be slight but noticeable hangs whenever the user adds a glyph in a range that hadn't already been seen.

The only alternative would be for us to take every glyph that could ever be typed and add it into the font glyph cache. This has the  undesired effect of eating RAM like candy.

**Comment by Qrox** [comment]
> rebuild the font glyph cache

Maybe we can edit the ImGUI source to insert the new glyph instead of rebuilding the entire cache, like what is done in the game's SDL font loading code?
