### ISSUE TITLE
Taekwondo buffs are always working despite wielding something.

### ISSUE THREAD

**Issue by Lupinos** [CleverRaven/Cataclysm-DDA#72179]
### Describe the bug

![图片](https://github.com/CleverRaven/Cataclysm-DDA/assets/26404356/6bec34a0-c2aa-456f-a9a6-4820aee92774)
By its description, I think taekwondo buffs should not be available if you are wielding anything.
I check the code and find:
![图片](https://github.com/CleverRaven/Cataclysm-DDA/assets/26404356/7dc90dec-b94a-4d42-ae83-c6184b0bffe6)
Here, this piece of code make 'valid_melee' always true whether you wield anything or not. I guess 'valid_melee' is used to check if the weapon is feasible to use the techniques or buffs, 'force_unarmed' should not affect weapons check.
If I delete the "forced_unarmed || ", it seems that it works fine.

By the way, here might be a relevant bug: If I wield anything, for example a heavy sledge. select taekwondo.Then when I smash something, the damage is calculated by sledge but the stamina cost is calculated as unarmed. I think there might be a little problem in `Character::used_weapon()`.

Last question, if I believed I have fixed them, can I make a PR for them or should I ask anyone/make a confirmation first?

### Attach save file

N/A

### Steps to reproduce
About taekwondo buff:

1，create a random character, and choose taekwondo.
2，wield anything you find and choose taekwondo
3，inspect your status.

About stamina cost:
1，create a random character, and choose taekwondo.
2，spawn a heavy sledge, wield it, and choose taekwondo
3，smash something for several times.
4，see your stamina bar.

### Expected behavior

1，If character wield something, he/she should not get buffs from taekwondo.
2，If character wield something heavy and smash, he should cost more stamina, or the damage should be revised.

### Versions and configuration

2ba772a

**Comment by Zenefess** [comment]
In **data\json\martialarts.json**, in the `style_taekwondo` entry, the static buff `buff_taekwondo_static2` is missing the line `"strictly_unarmed": true,` after `"unarmed_allowed": true,`. Adding it in prevents `buff_taekwondo_static2` from taking effect, and prevents globally affecting usage of `valid_melee`.

Testing:
Loaded existing save. "Unhindered" appears. Pick up freezer. "Unhindered" disappears. Drop freezer and wait a turn. "Unhindered" reappears. Repeat process with rifle. Same result.

**Comment by Zenefess** [comment]
Further testing:
Loaded existing save and repeated above process with carving knife, then knuckle dusters. Same result as above.
Started new game and repeated above process with pocket knife. Same result as above.
