### ISSUE TITLE
AI technology for NPC conversation and interaction.

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72185]
### Is your feature request related to a problem? Please describe.

Immersion.

### Solution you would like.

Implement the chatbot ai technology into the npcs interaction menu, where their opinion, current status, current location, previous location, etc, determines how they respond to the player. Maybe even add some hooks to allow players to make the npcs do something through the conversation.

### Describe alternatives you have considered.

Not doing this.

### Additional context

We are approaching a new era of immersion in gaming thanks to the rapidly advancing ai technology, would only make sense for such an amazing survival sim like this one to feature some of it!

**Comment by RenechCDDA** [comment]
No. Besides the myriad of legal problems this would cause, the devs have repeatedly expressed that they are not interested.
