### ISSUE TITLE
[MoM] gateway power should have mutliple destinations 

### ISSUE THREAD

**Issue by M7mdKady14** [CleverRaven/Cataclysm-DDA#72184]
### Is your feature request related to a problem? Please describe.

The gateway spell is super cool but I think it will be cooler if you could attune yourself to multiple locations and then when you gateway, you choose which one of these locations you should go to.

### Solution you would like.

add a "max attuned locations" value to gateway with something like (1 + 1 for each 5 levels).
and when activating the gateway spell, you see a list containing the locations' name(set by the player) and coords and you choose one to teleport to.

**Comment by SariusSkelrets** [comment]
AFAIK it already works like that: set your locations, cast the spell, choose one, teleport to it

The only thing that isn't in game is a limit on attuned locations, currently you can attune to as many spots as you want

**Comment by Standing-Storm** [comment]
As SariusSkelrets says, that should be the default behavior. Is it not working for you?

**Comment by M7mdKady14** [comment]
Ah sorry my bad, I thought it didn't work like that since I assumed attuning to another location would delete the old one
