### ISSUE TITLE
Is it possible to choose armor thickness in game?

### ISSUE THREAD

**Issue by Lupinos** [CleverRaven/Cataclysm-DDA#72180]
### Is your feature request related to a problem? Please describe.

It might be a little simplistic and abrupt to just choose from “light/medium/heavy" types of plate armors.
And between thickness，weight/encumberance and feasible materials, there should be some degree of freedom to trade off in real world.

### Solution you would like.

I think it's a good idea to allow player to choose their favorite thickness of armors, let them weigh up the defense and encumbrance.

For example, there could be a minimum thickness and maximum thickness defined in json. And some other paired information like minimum weight/encumbrance/materials and maximum weight/encumbrance/materials defined in respective json files.. 

Weights、encumbrance、materials needed would be linearly(or any other possible curve) lerped by the chosen thickness.

If some of the paired values are not specified, then the value is fixed.

**Comment by PGR-14** [comment]
Encumbrance & Thickness are independent from eachother.
Besides, It's alright where it is, so it doesn't need much of a re-work

**Comment by kevingranade** [comment]
What you're suggesting is procedural or parametric stat generation for armors.
This is an incredibly complicated concept that I don't expect to provide any meaningful improvement to player experience.
You might be under the misapprehension that we already calculate all armor stats based on material and thickness, this is not the case, we calculate a few simple stats based on material and thickness, but there are also a large number of stats that are set manually for each armor item. For example a heavier armor might imply not just thicker armor pieces but a greater emphasis on protection over mobility, so a contributor making an armor might tune up the coverage of heavier armors at the cost of higher encumbrance.  Baking this kind of tradeoff into a parametric armor generator wouldn't just be complex and difficult, I wouldn't even know where to start.
