### ISSUE TITLE
Hardcore difficulty regions inspired by the movie "ANNIHILATION"

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72192]
### Is your feature request related to a problem? Please describe.

None.

### Solution you would like.

Just an ideia: The world could be bombarded by special meteors or various different portals could open up sporadically transforming a region around it into a more difficult location where there are natural traps and special types of mutated beasts and zombies. if near a city, the walls could slowly crumble or become overgrown. The location could spawn special types of zombie hordes that would track the player, incentivizing them to go in there and close the portal/destroy the object.

### Describe alternatives you have considered.

Not implementing this.

### Additional context

Idea came to mind upon watching the movie "ANNIHILATION" where there occurs an alien phenomenon called the Shimmer. It is also very similar to the events that happen on the lovecratian story "The Colour Out of Space", which is very on par with the game's lore, considering all the lovecraftian beasts already implemented.

**Comment by TheSaddestGoomba** [comment]
I like the idea of scaling difficulty upwards towards the center of a point of interest. Somehow tying this to monster evolution would be excellent.
