### ISSUE TITLE
Pressing `i` to ignore hangs for a bit, while loading a game

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#72203]
### Describe the bug

Whenever there's an error while loading the game and I press `i` to ignore it, it takes a while to show the loading screen again. It feels like the input wasn't registered, so I used to spam the key a few more times.

### Attach save file

Sure, this is my testing game, I am used to ignore a few errors on loading. Once there will be to many, I will make a new one,
[Turkey over fence-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14510238/Turkey.over.fence-trimmed.tar.gz)

### Steps to reproduce

1. Start loading a game
2. When error appears press `i` to ignore it
3. The debug menu stays for a bit.

Workaround:
Resize the screen - this forces redraw, so the loading menu is shown.
1. Start loading a game
2. When error appears press `i` to ignore it
3. resize the window
4. Loading menu instantly appears.

### Expected behavior

The moment I press ignore, the loading screen redraws again.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0.G-7808-gf0c1acc2ee-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Qrox** [comment]
I think it's just waiting for the next redraw? We can probably increase the response speed but that involves adding input event pumping calls to the individual pieces of loading code (or rewriting the code to run a different UI thread).
