### ISSUE TITLE
Anvil discussion

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#72208]
### Is your feature request related to a problem? Please describe.

the problem is the anvil formulation

it used to be like:
Level 1 of the anvil is used at the very beginning, it is mainly made from a large stone,
Skip level 2 (bronze anvil) it was stupid
Next, at the 3rd level of the anvil, at the 6th production level we melt 2 or 4 steel frames, we get the 3rd level of the anvil and forget about the anvils for the rest of the game with this character

now, in order to make a level 3 anvil, we first need a meter-long rail, then we need to cut it into a half-meter rail (by the way, this is only level 1 of the anvil), then we need:
Tools Required:
        1 tool with hammering of 3 or more.
        1 tool with chiseling of 3 or more.
        1 tool with grinding of 2 or more.
        drill press (20 charges)
        angle grinder (20 charges)
Components: 1 crude anvil (this is what is made from half-meter rails)

in general there are never any problems with a hammer everything else is much more difficult to make yourself (making steel chisel looks especially fun, it requires level 3 anvil ^^)

Of course, you will tell me “Make a bronze anvil, it gives the 3rd level of the anvil” yes, this is true, but it requires 90 bronze fragments to make, for which you need to find a book

in the end it turns out that there are unjustified difficulties everywhere: either find a steel chisel, or find a level 3 anvil, or find a book on bronze casting, I don’t know what’s easier at low drop rates...

By the way, a half-meter rail or a meter-long rail is still steel, cars weighing 20 tons or more travel on it, and at the joints there is still an impact that the rail can withstand quite well if the seams are not welded (before, by the way, they were not welded but twisted and there were a lot of joints). Why can't an anvil made from rails be level 3 at once?

### Solution you would like.

in general, the old recipe was quite plausible, I doubt that medieval blacksmiths found rails, sawed them with a grinder, then found a book on bronze casting and made a steel anvil, most likely they cast iron in the ground or in sand, and forged on the resulting piece of metal, an anvil after all mainly needed to set the shape and mix the layers of metal in the workpiece, and the workpiece is heated at the beginning so that it becomes soft and is already forged

a drilling machine and a grinder also don’t look appropriate, although a drill is probably still needed, but not a machine;
perhaps the grinder can be replaced by grinding (grinding stone or sandpaper) + a hacksaw for metal;
steel chisel I don’t understand what needs to be carved on an anvil

perhaps if you really want to make life more difficult for players, you should introduce more levels of anvils, different anvil materials, but this will add problems with adapting recipes for the level and anvil material

It’s difficult for me to offer something interesting for anvils and blacksmithing in general, perhaps other enthusiasts will offer something, now the process of making anvils looks ridiculous and unjustifiably complicated

**Comment by IdleSol** [comment]
The bronze anvil requires an angle grinder. And for the disk to it, you need an anvil 3.

https://cdda-guide.nornagon.net/item/anvil_bronze
https://cdda-guide.nornagon.net/item/grinder_blade

**Comment by osuphobia** [comment]
IMO, anvils are treated too seriously, while at the same time we are too dismissive of forges, as well as fuels.
It is somewhat reasonable of the change making it rougher to obtain a good anvil, but do we realy need a level 3 anvil to do almost all that blacksmithing works? 
In addition, the history of metal casting is way longer than forging, but in dda only a few casting recipes exist.
As for things like bronze Dao, which only need metal casting tools to be made IRL, needs anvil in dda. That's ridiculous.
Furthermore, for the fuels of forge, there are only two types of fuel, charcoal and coal, coke can't be found in dda, and that's not realistic at all.

Suggestions:

1. Make it easier for low-spec weapons to be made. Allows play to make a makeshift anvil with level 2 anvil, just like the counterweight, and lower the requirement of some recipes to level 2 anvil.
2. Lower or remove the requirement of anvil for bronze tools and weapons that should be made mainly by metal casting IRL. On the other hand, we should add grinding tool requirement in relevant recipes.
3. Change the method of forges. Fuels are not charged to forges, but consumed directly as componets. Coke should be introduced as a high-tier fuel and be required for hardened steel and tempered steel weapons.
4. Maybe using acetylene torch _forge_, rather than directly using acetylene torch,  is more reasonable in forging and casting.

See also:
https://calawton.com/iron-casting-history-part-1/
https://www.youtube.com/watch?v=RmLvWRjgOVs
https://www.youtube.com/watch?v=FHS0NXr1xbk

**Comment by osuphobia** [comment]
> The bronze anvil requires an angle grinder. And for the disk to it, you need an anvil 3.
> 
> https://cdda-guide.nornagon.net/item/anvil_bronze https://cdda-guide.nornagon.net/item/grinder_blade

You don't need an angle grinder to make a bronze anvil, while disassembling it needs.
It is the anvil and crude anvil that requires an angle grinder.

**Comment by IdleSol** [comment]
>You don't need an angle grinder to make a bronze anvil

You're right. It's my mistake.

**Comment by watcherPlayer** [comment]
some thoughts:
1. there shouldn't be a bronze anvil
1. link the anvil level to the volume of the metal part of the workpiece, this will make it easier to link recipes to the anvil level
1. enter a new parameter describing the quality of blacksmithing, for example, if you have an anvil and a forge and forging pins, this is one figure, if you change the type of forge or anvil or add more blacksmithing items, this is another figure
1. add fluxes (crushed glass, borax, powdered cast iron, etc.) and quenching (a container with water or oil, and so that it is consumed in the manufacture of items that require quenching), for the manufacture of various
1. add a compressor as a speed ignition equipment, let it increase the speed or quality of forging if it will increase the speed of forging
1. add a furnace for tempering metal, optional for some recipes, perhaps worth adding as a tool at the forge
1. anvils can be the following: 
    level1. cast iron, steel, anything connected with a rail, heavy-duty frame, hard plating, counterweight
    level2-3. cast iron anvil or steel anvil larger than level 1 anvil
    level4. unique heavy anvil (you can only find it)
    level5. forge hammer
1. then you need crucibles of different sizes and a blast furnace, but this will need to be thought about

**Comment by Zireael07** [comment]
> there shouldn't be a bronze anvil

Why not?

**Comment by watcherPlayer** [comment]
try to look for the use of bronze anvils, with the exception of breoks or figurines in the form of bronze anvils))), as people mastered the smelting of iron and its alloys, so all anvils began to make it, bronze anvils, if they were ever made, it was in the Bronze Age quite a long time ago... and in the game trying to collect bit by bit the ingredients for a bronze anvil is, to put it mildly, stupid, because a bunch of various scrap metal pours out of iron... there is simply more of it

**Comment by Zireael07** [comment]
The fact that the Bronze Age lasted thousands of years is proof that bronze anvils existed and were viable.

You're however right that it makes little sense for a survivor to make bronze anvil when there's so much iron around

**Comment by watcherPlayer** [comment]
no, not like that... let there be a place for a forge similar to a place for manufacturing or a place for firewood. You can place an anvil in this place, any

tools that can be attached to the forging station:
* metalworking chisel
* hotcut
* pair of flatjaw tongs
* polishing agents,
* swage and die set
* drift
* bucket with hardening liquid (metal)
* furnace for metal tempering
* hammer or sledgehammer (hammer as a hammer option can be installed by attaching the smallest anvil to the largest anvil and drive to work: steam engine, diesel engine, gasoline engine and electric motor, as well as anything as mechanisms for combining the anvils and drive, and yes, the hammer can only be placed on steel anvils, not on cast iron anvils and not on all others either) ; may be improvement option via shift + 8 ?...
* reinforced bed (to purely improve the quality of blacksmithing, and it would be strange if the hammer were placed on soft ground in the form of earth, sand or parquet), then cement and reinforcement would probably be needed, the reinforced bed cannot be removed, only destroyed; improvement option via shift + 8
* let the anvils be the following 100mm, 200mm, 300mm, 400mm, 500mm

consumables:
* sanding accessories other than files
* fuel for the operation of the hammer and/or furnace for tempering; if there is no hammer, fuel is not needed
* hardening liquid (water, oil, goo canister (for futurism)), each liquid gives some kind of bonus, here you need to think about what oil and water are used for (for example + 5-10% to some type of damage and + 5-10% to the fragility of the product, the tempering oven removes the penalty to fragility), and goo canister for regenerating weapons, for example 1hp of a weapon 1 time in 6 game hours, - to crushing damage and cutting + bonus to piercing damage, and the weapon cannot be repaired by any means another way, or stops the character's bleeding and is treated for it

**Comment by watcherPlayer** [comment]
let there still be room for the forge, well, it will be possible to assemble the next forges:
* coal forge
* electric forge
* gas forge
* open-hearth furnace for large smelting and processing

You can also attach some tools, for example:
* различные флюсы как для горнов так и для open-hearth furnace (пусть они статически расходуются при изговления по рецепты как заряды топлива)
* compressor, you need to think about it because in reality it is only needed for a coal forge (increasing the blacksmithing bonus in conjunction with a blacksmithing place) and maybe for an open-hearth furnace

anvils can only be made through an open hearth furnace, except for the smallest cast iron, it should probably be given the opportunity to make it through a crucible

for an open hearth furnace you will need a book (this is not a simple device)

so that you can use basic blacksmithing recipes for a steel anvil with a cast iron anvil, increase the level of blacksmithing convenience with the help of tools and at least slowly make them

**Comment by watcherPlayer** [comment]
yes, I completely forgot about casting molds, all casting molds are available for an open hearth furnace, only a small sand mold is available for a forge

**Comment by IdleSol** [comment]
I tried to make a scheme for obtaining tools for blacksmithing. There were several conditions, lack of ready-made tools, impossibility to find them (only creation) and lack of books.

Basically, it's not possible now. To make a level 3 hammer, you need a level 3 hammer. To create a furnace, you need a furnace. And to create a level 3 anvil, you need a level 3 anvil to create tools. And that's in addition to the recipes from the books alone.

This is a greatly simplified scheme. For clarity.
![Simple](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/514e9a6b-c8ad-4722-b3fa-85c5e9846f76)

And this is part of the scheme for obtaining a bronze anvil, except for the forge.
![Bronze anvil](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/91651067-0ca0-41e7-ae91-84028fd8440d)

There is no complete scheme with forges. There are too many tools that require even more tools that require first tools. Which makes this scheme difficult to understand.

**Comment by IdleSol** [comment]
Extras. There are a lot of weird recipes that call for a tool with a certain quality and the same tool by itself.

To give you an example:
https://cdda-guide.nornagon.net/item/tin_snips

It requires:
- 1 tool with grinding of 2 or more.
- metal fileset or bronze fileset

But the metal fileset already has level 2 grinding quality.

**Comment by IdleSol** [comment]
I made the mistake of forgetting about the rock forge. That's why I hid the last post.

Here are the new variants, for bronze and steel anvil.

![Bronze anvil](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/971e10b5-dc2f-4ae5-bfee-93c1f3903f58)
![Steel anvil](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/be55d2e9-6b4d-4f29-9102-91cfa1184878)

If for a bronze anvil, you only need to find a book with a recipe for bronze chunks. For the steel anvil, you need to find both books and tools.

P.S. Hopefully this time, I didn't make a mistake anywhere.
