### ISSUE TITLE
phone resolution

### ISSUE THREAD

**Issue by MIQted** [CleverRaven/Cataclysm-DDA#72223]
### Describe the bug

after setting the resolution (in my case 1280x720) there is a need to buy glasses because everything on the screen becomes very small, it is very difficult to see on the phone, everything looks like a rough ported build of the pc version to android. and the main problem is that reducing the resolution doesn't solve this issue by making the game bigger, it just shrinks and moves the game screen to the top left corner, leaving the empty black area of ​​the phone screen empty

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

regardless of the selected resolution in the game settings, the game screen should be placed completely on the entire display of the phone, that is, if you set the game resolution for example to 800x600 on a phone with a resolution of 1280x720, the game screen should stretch to the entire phone screen, increasing all the content

### Screenshots

![IMG_20240307_131537_499](https://github.com/CleverRaven/Cataclysm-DDA/assets/118636969/dbc92b07-a127-4a3c-998c-ceeeb8fc2cb1)

### Versions and configuration

Geotel Pace 2 Lite android 7.0
screen diagonal: 5
Resolution 1280x720
Cdda last experimental

**Comment by katemonster33** [comment]
Hi, can you verify this was working properly before the SDL update?

**Comment by MIQted** [comment]
sent the pictures to e-mail

**Comment by turco-ai** [comment]
Did you set it to full screen mode, change the font size, change the shortcut height (after making it so they don't overlay over the screen) and change the terminal height and width accordingly?

**Comment by MIQted** [comment]
unbelievable, it worked as before! after changing the font display settings, namely: increased size, height, width.
it's strange that it affects the screen resolution at all..

**Comment by MIQted** [comment]
thank you very much Turco-ai
And my apologies to Kate if i made her worried about the sdl update and happy women's day to you, inspiration to you and your team ❤
