### ISSUE TITLE
Vague Monster Shapes in the dark

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72239]
### Is your feature request related to a problem? Please describe.

None

### Solution you would like.

Monsters in very dark areas could be located but not discerned as they would appear as vague shapes (humanoid, Hulking, Robotic), and the range of visibility for these shapes could be dictated by the perception stat. This would essentially give players more agency while not altering the difficulty too heavily. Could give some good scares as you watch a vague shape turn out to be a fierce monstrocity.

### Describe alternatives you have considered.

Not doing this.

### Additional context

This would also balance the game towards making small and strong creatures more dangerous, as you could easily mistake a humanoid silhouette for a simple zombie when in reality it is a dangerous mutated variant. Big silhouettes would be less surprising as big things are already expected to be dangerous.

**Comment by andrewhr** [comment]
I would add, weakpoint proficiencies could be applied here too, given they are about "how well you know the monsters".

**Comment by Rimplestilt** [comment]
This is basically an idea I had a couple years ago from #59266

**Comment by RedMisao** [comment]
Related to #22687
