### ISSUE TITLE
Map refresh artifact when playing without tileset

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#72238]
### Describe the bug

I am playing on [a recent build](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-04-0136) without a tileset , with the default (Terminus) font. The map (not the overmap) seems not to refresh correctly on area where the terrain is not known or not remembered. 

Also, when I close a dialog, the dialog does not erease completely on those unknown zone.

Look at my screenshot, to the right of the orchard processing building, there is many vertical walls on the right that appear as I move toward the building.

### Attach save file

[Juncal-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14530325/Juncal-trimmed.tar.gz)

### Steps to reproduce

Just start a new game without tileset, move around , and look for artifact like mine

### Expected behavior

should be black or sepia (i think)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1076726/4e2b04a8-0424-4671-bde4-99dfea2afe7b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3155 (22H2)
- Game Version: dfab48d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Monsters [Only_Wildlife]
]

**Comment by pierredavidbelanger** [comment]
I cant reproduce the problem in a new world with a [more recent version](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-08-0523) .

**Comment by Uwuewsky** [comment]
> Game Version: dfab48d [64-bit]

This was fixed in [0092ef6](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-06-2243), #72127
