### ISSUE TITLE
vehicle boards with security cameras can be walked through when diagonal

### ISSUE THREAD

**Issue by enbyfiend** [CleverRaven/Cataclysm-DDA#72241]
### Describe the bug

vehicle boards with security cameras can be walked through when diagonal. it's only the diagonally-generated tile that is walk-through-able. 

### Attach save file

[Ferrisburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14533558/Ferrisburg-trimmed.tar.gz)

### Steps to reproduce

The save should spawn you next to the diagonal vehicle in question. just walk through the tiles with cameras.

### Expected behavior

the boards with cameras shouldn't be pathable like the other boards. 

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/133426720/904a689b-9f04-4bd8-a963-ce4421cd4a6d

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: c5225cf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by IdleSol** [comment]
Confirmed.
Started with version [2023-03-24-0154](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-03-24-0154) Most likely PR #64392

Additionally note. 0:11. The heavy board is copied twice. As far as I understand, this is also an error.


![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/601490e2-ba68-4e93-86e4-dc94d4aa66c3)
