### ISSUE TITLE
Regression--METABOLISM of 0 causes the game to hang.

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#72242]
### Describe the bug

Setting METABOLISM to zero (such as by enchantment with `{ "value": "METABOLISM", "multiply": -1.0 }`) causes the game to hang indefinitely on the turn after it's set. This was explicitly fixed in #69894, so there's been a regression since then. 

### Attach save file

[Hagerstown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14534044/Hagerstown-trimmed.tar.gz)

### Steps to reproduce

1) Cast the spell Stones' Fortitude, which reduces metabolism to zero at max level.
2) Attempt to move
3) Game hangs indefinitely

### Expected behavior

Metabolism of 0 is supported post- #69894

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 9f08089 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

**Comment by rty275** [comment]
This must be a relatively new regression, I was using Stone's Fortitude at max level successfully as recently as a month or less ago.

**Comment by Standing-Storm** [comment]
Are you on the most recent experimental? The message `A relic attempted to load invalid enchantment CARDIO_MULTIPLIER` makes me think your game is from before #72106 was merged.

**Comment by rty275** [comment]
I realized I wasn't moments after saying that, wanted to update and check before coming back here so I didn't have to edit again. Yeah, I can reproduce it so the bug occurred somewhere between build 2024-03-07-0457 and now. That's my bad for not getting up to date before testing.

**Comment by GuardianDll** [comment]
/confirmed
![image-123](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/eff7c171-3ae6-4276-b65f-469ab1a88f2a)

**Comment by rty275** [comment]
A bit more testing, it's something that happened between 2024-03-07-2013 and build 2024-03-07-2353, and while I don't have the coding expertise to actually diagnose where things went wrong, out of those three PRs in the changelog for that build, #72106 seems like the only thing that touched metabolism. I have no idea how to debug or diagnose from here, so I'll leave the rest of that to y'all, but I hope I helped a little in detecting which build caused the difference.
