### ISSUE TITLE
Sometimes limb health is displayed differently on bandaging and sidebar screens

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#72269]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53100513/a51cde9d-6205-453d-bed9-14f8a45d3acd)

### Attach save file

N/A

### Steps to reproduce

1. Get hurt exactly to the point it bugs out
2. Try to bandage

### Expected behavior

They should be the same

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53100513/1e3d790c-6416-4ebd-a6c5-2e824830b044)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: d660a13 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Milopetilo** [comment]
I didn't manage to reproduce this using a default character, also not when stepping from the debug 9000 health. It'd be handy if you could provide the save this happened with :)
