### ISSUE TITLE
Stray characters at end of floating point value 0.000000 in item::get_var   

### ISSUE THREAD

**Issue by SterixFoxe** [CleverRaven/Cataclysm-DDA#72266]
### Describe the bug

When loading the world, the following error message appears:

 DEBUG    : Stray characters at end of floating point value 0.000000 in item::get_var

 FUNCTION : get_var
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1863
 VERSION  : 311da93
If you ignore the error, after some time the game popup with this message

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            Stray characters at end of floating point value 0.000000 in item::get_var

 FUNCTION : get_var
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1863
 VERSION  : 311da93

and after some time crashes. If you move away from the base and throw the firearm out of your inventory, the error disappears. This error appears every turn, no matter if you skip a turn or move. 

### Attach save file

[Пасчер-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14546021/-trimmed.tar.gz)

### Steps to reproduce

1. Load save 
2. Get first 2 erors
3. after loading in world and skipping error messages by "SPACE" skip turn to get errors

### Expected behavior

This error does not occur in the experimental build 2023-03-04-0412. Also, if you move a sufficient distance away from the base, the error will still appear. By dropping SIG Pro from your inventory, the error will stop appearing until you pick up the weapon or approach to evac shelter.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 311da93 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by SterixFoxe** [comment]
I found items that cause this error. one pistol in the inventory and a shotgun in the hands of the NPC at the base. Solved

**Comment by cyberpunk2021** [comment]
Hi

I have the same issue, can you describe the method to solve it please ?

Best regards
