### ISSUE TITLE
Game crash when using auto-travel

### ISSUE THREAD

**Issue by RedBloodCat** [CleverRaven/Cataclysm-DDA#72270]
### Describe the bug

The game crashes when using auto-travel feature. This does not happen when you there walk manually

### Attach save file

[Travelling-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14547386/Travelling-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Autowalk to brigde -> Crashes

### Expected behavior

Not crashing

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/49415411/397172ea-3d86-48f1-aa8e-dee9c7092def)
Bridge in question

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 925f13b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14547391/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14547392/debug.log)

**Comment by Milopetilo** [comment]
I don't seem to be able to replicate this :/

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 925f13b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]
