### ISSUE TITLE
[Magiclysm] Megablast uses stamina instead of mana

### ISSUE THREAD

**Issue by Luiizz** [CleverRaven/Cataclysm-DDA#72280]
### Describe the bug

Megablast, a spell in Magiclysm, uses stamina as opposed to its actual mana cost of 8000.

### Attach save file

N/A

### Steps to reproduce

1 - Learn Magablast
2 - Cast it
3 - Mana stays the same but stamina go's down (not by a lot even)

### Expected behavior

Spells take mana not stamina

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: d660a13 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm]
]

### Additional context

The spell itself is also weird in a bunch of other ways, like, It takes so much mana that it might not be possible it can ever be cast at its real mana cost or the fact it's a difficulty 10 classless spell.

**Comment by rty275** [comment]
This is intentional. It's 8000 cost because your stamina is in much higher numbers than your mana total. If it cost 8000 mana, it would be unusable in all but the strangest of circumstances. To my understanding, it's a martial arts laser beam a la hadouken or somesuch.

**Comment by Maleclypse** [comment]
I don't think it's ever supposed to be cast at all.  When was it changed to stamina?

**Comment by rty275** [comment]
Oh was it actually supposed to be mana? That's wild, I assumed from the cost that it must have been intended to be stamina since it just wouldn't make sense otherwise. But if the point is that it isn't supposed to be castable, then that makes more sense.
