### ISSUE TITLE
Follower put into stasis after trying to read e-book with dead batteries

### ISSUE THREAD

**Issue by BlueDragonFire** [CleverRaven/Cataclysm-DDA#72289]
### Describe the bug

My follower was reading an e-book on a phone for applied science when their batteries ran out. The log on screen said something about the follower "fainting" and when trying to talk to them, I got a message about the follower being put into some kind of stasis because of its AI bugging out.

### Attach save file

N/A

### Steps to reproduce

1. Get a follower
2. Give them a phone or e-ink reader with low batteries and containing an e-book that takes a long time to read.
3. Ask them to read it
4. Assuming the batteries run out, they will continue to try reading it for several hundred turns before fainting

### Expected behavior

The follower should stop reading and say they are out of batteries

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.3; Release: 20.3; Codename: una; 
- Game Version: dd1adff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Skill Rust [perfect_memory]
]

**Comment by enbyfiend** [comment]
I've had this issue too.
