### ISSUE TITLE
Guns and Soundpacks

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#72286]
### Is your feature request related to a problem? Please describe.

There's a lot of guns in the game and most of them has the wrong sounds when fired/reloaded or completely silent, this kinda makes such guns have "less" cool factor (in my opinion), this includes mods that adds their own guns and ammo type, this change (if at all implemented), would make future guns added in the game to have a high chance of having the correct firing and reload sounds and not just silent if not the incorrect sound.

### Solution you would like.

Firing sounds to be tied to Ammo type.

Reloading sounds to be tied to Magazine type.

Muffling/loudening of firing sounds (if it exists) to be checked if the gun a certain type of muzzle mod or any other mod that changes said sounds.

### Additional context

This is just immersion stuff, so it changes from
"Woah, this gun looks cool!" Into "woah, this gun looks cool AND sounds cool!"

I mean, we have our own preferences, just to be kinda let down by them being utter silent when being fired and reloaded.

**Comment by Fris0uman** [comment]
Guns having wrong sound seems like a soundpack issue and not a game issue

**Comment by Kywi001** [comment]
Has any sound pack have been updated?

**Comment by Fris0uman** [comment]
[CC-Sounds](https://github.com/Fris0uman/CDDA-Soundpacks) is the only soundpack officialy associated with the game and it doesn't have sound for every gun

**Comment by Kywi001** [comment]
Oh cool, I was still using the one from forever ago. Thanks!
