### ISSUE TITLE
Sky Island not reviving on death

### ISSUE THREAD

**Issue by DarkyDonno** [CleverRaven/Cataclysm-DDA#72301]
### Describe the bug

When dying a second time you do not respawn.

### Steps to reproduce

1. Create a sky island character
2. Start an expedition
3. Suicide - respawn
4. Start a second expedition
5. Suicide - permadeath

### Expected behavior

Character should respawn on the island a second time

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 423bc10 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland]
]

**Comment by MrHrulgin** [comment]
Can you provide more detail regarding your death? I couldn't recreate the issue with the stated version and modlist, even when I died within a couple of minutes of teleporting down.

**Comment by DarkyDonno** [comment]
> Can you provide more detail regarding your death? I couldn't recreate the issue with the stated version and modlist, even when I died within a couple of minutes of teleporting down.

Did you try using the provided save? This issue seems to begin happening more often the longer the save file has been played. I've repeatedly loaded and tried changing different conditions of the death, but it seems to be random unless I'm missing something.

**Comment by MrHrulgin** [comment]
Testing it with your save, I could reproduce. When I chose to "watch the last few moments', the teleport back to the island did trigger, but it caused a segfault. It also did  I've attached the crashlog here.

Interestingly, it's not about your death. Using a homeward mote teleports me, but I then fall 6 stories to the ground and the game crashes to an identical segfault. Did you trim your map files or something else that might have changed your home location? Searching for "sky" or "island" on the overworld map gets no hits, so it may be that your home island doesn't exist anymore. It's definitively *not* that you're not being revived on death, though.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14553921/crash.log)

**Comment by DarkyDonno** [comment]
Odd.. No, I've done nothing out of the ordinary with the map.

Since this issue is not present until later in the save I wonder if it could be related to one of the island upgrades that have been crafted. It seems to start happening around the same time/progression (rank 1, medium expeditions, room construction 1-2).

I'll mess around with island upgrades this evening when I get home and see if I can find a consistent cause.

**Comment by DarkyDonno** [comment]
> Testing it with your save, I could reproduce. When I chose to "watch the last few moments', the teleport back to the island did trigger, but it caused a segfault. I've attached the crashlog here.
> 
> Interestingly, it's not about your death. Using a homeward mote teleports me, but I then fall 6 stories to the ground and the game crashes to an identical segfault. Did you trim your map files or something else that might have changed your home location? Searching for "sky" or "island" on the overworld map gets no hits, so it may be that your home island doesn't exist anymore. It's definitively _not_ that you're not being revived on death, though.
> 
> Edit: To cover all my bases, I debug killed all the enemies, waited half an hour, then used a mote, to the same effect.
> 
> [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14553921/crash.log)

Yes I suppose the debug trimmed save deleted the island... Homeward mote for me works fine and brings me to the island before dying. After enabling deathcam I also see it teleport me to the island, however there is no crash accompanying this. It waits until I stop it and then proceeds with the end of character messages.

I was unable to find a pattern to the permadeath after messing around with island upgrades.

Here is a link to a zipped untrimmed save: https://file.io/LKZJdLcL7If3
I couldn't share here as it is over 25MB.

**Comment by MrHrulgin** [comment]
Using your larger save file, I'm seeing exactly what you're seeing. And waiting 30 minutes, even right on the spot, does properly return your character to the island. No idea why it's causing the game over screen to step in too soon; I'll do some digging.

**Comment by DarkyDonno** [comment]
> Using your larger save file, I'm seeing exactly what you're seeing. And waiting 30 minutes, even right on the spot, does properly return your character to the island. No idea why it's causing the game over screen to step in too soon; I'll do some digging.

I created a new world with only the sky island mod, and made a default character. I started an expedition and promptly blew myself up which had me respawn on the island. I did it a second time and it was permadeath, exact same behavior as before.

**Comment by MrHrulgin** [comment]
Yeah, debug killing them does have them reappearing if you wait. It's curious, and might be worth a separate bug report, as my assumption is that it's unrelated.

**Comment by MrHrulgin** [comment]
Doing additional tests, if I kill myself repeatedly in subsequent runs, I get a game over. If I wait a few hours, between attempts I recover just fine. If I die repeatedly on the island from freezing to death, nothing goes wrong. If I start a mission, die, start another mission, die by drowning, and then die almost instantly on the island a second time by drowning, that game overs. Something about deaths in quick succession seems to be the problem, but it's not only that.

**Comment by DarkyDonno** [comment]
Been playing with that PR and have not had the issue on any of my characters since.
