### ISSUE TITLE
Add Snail Shell

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#72317]
### Is your feature request related to a problem? Please describe.

The main component of snail shells is calcium carbonate, which can be used to make quicklime. In addition, the products of freshwater snail slaughter in the game are shell meat and fat, which cannot be used to prepare snail-related dishes.

### Solution you would like.

Add snail shells, add snail shells to the slaughter products of freshwater snails (and other mutated snails), and add a formula for make quicklime with snail shells

**Comment by ADekema** [comment]
The mutant snail shells could have funny uses. They could possibly be used as canteens, bowls, large water containers, shelter, improvised backpacks. These uses would just be for fun in mainline but they could be actually useful in innawood.
