### ISSUE TITLE
Crutches Overhaul

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72313]
### Is your feature request related to a problem? Please describe.

Crutches are a bit weird. I realized many items could be used as crutches (but they don't) and some items can support your weight when they shouldn't. ~~ex) a plastic wizard cane~~
And for some reason, both cane and crutches function exactly the same. There's no reason to find or make crutches when you can just make a simple cane which is smaller and shorter.

### Solution you would like.

Two separate functions for cane and crutches.

- Canes for weight distribution. If your character is overburdened, or has injured leg(s), a cane should be able to lessen the speed debuff, or it could help the character with going across rough terrain.
- Crutches, in the other hand, shouldn't work the same as canes, but it should be able to help with injured or broken leg better than a cane.

+ a stick or a long stick could work as makeshift cane, and a plank could work as makeshift crutches.

### Describe alternatives you have considered.

Not doing it, maybe. I couldn't think of better alternatives.

### Additional context

MY LEG

**Comment by Inglonias** [comment]
While we're on the topic, I'm curious as to how crutches have a similar power level to baseball bats in terms of raw damage.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/2125926/b8574ce0-dafd-4906-bd3d-bd0b07c8d43b)

**Comment by RedMisao** [comment]
> While we're on the topic, I'm curious as to how crutches have a similar power level to baseball bats in terms of raw damage.

Melee damage is not standarized and has no reference.
