### ISSUE TITLE
Unrelated invalid JSON errors upon correcting an error and reloading a save

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#72316]
### Describe the bug

When working on a PR and I mess up, forget a field in the JSON or anything really that causes a fatal error and try loading a save again, there will be *many* errors where totally unrelated JSON becomes invalid.

```
 DEBUG    : (json-error)
Json error: data/json/artifact/artifact_item_types.json:225:19: <color_white><color_cyan>Invalid or misplaced field name "description" in JSON data</color>

    "copy-from": "robe",
    "name": { "str": "royal robe" },
<color_light_red>    "description": "An ornately decorated robe with an unfamiliar royal symbol on it.  The humanoid figure on the seal has two pairs of eyes.  It is the only one of its kind.\nIt may have unknown powers; try activating them."</color>
                 <color_cyan>▲▲▲</color>
  },
  {
</color>


 FUNCTION : void JsonObject::error_skipped_members(const std::vector<long unsigned int>&) const
 FILE     : src/flexbuffer_json.cpp
 LINE     : 347
 VERSION  : 84b2f37

 DEBUG    : (json-error)
Json error: data/json/artifact/artifact_item_types.json:223:17: <color_white><color_cyan>Invalid or misplaced field name "copy-from" in JSON data</color>

    "id": "art_robe",
    "type": "ARMOR",
<color_light_red>    "copy-from": "robe",</color>
               <color_cyan>▲▲▲</color>
    "name": { "str": "royal robe" },
    "description": "An ornately decorated robe with an unfamiliar royal symbol on it.  The humanoid figure on the seal has two pairs of eyes.  It is the only one of its kind.\nIt may have unknown powers; try activating them."
</color>


 FUNCTION : void JsonObject::error_skipped_members(const std::vector<long unsigned int>&) const
 FILE     : src/flexbuffer_json.cpp
 LINE     : 347
 VERSION  : 84b2f37
```

This repeats for basically all properties.

### Attach save file

n/a

### Steps to reproduce

Note that this is applicable to many other errors, but it is one way to trigger it.

1. Launch cataclysm-tiles.
2. Open your editor, go to data/json the game is using and intentionally cause a JSON error. In this case, I just went into `monster_special_attacks/spells.json` and removed the first {.
3. Save the file.
4. Load any save.
5. Get a fatal error, where the game does not continue loading and instead drops you back to the main menu.
6. Undo your change.
7. Load the save again.
8. You get these super weird invalid and unrelated JSON errors. Do note that it does not matter which fatal error you cause, it just needs to be fatal while loading.

### Expected behavior

It does not suddenly regard perfectly valid JSON as invalid. It is always the same file it complains about, too.

I was told on the devcord to ping @akrieger.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 84b2f37 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Maaaaybe related: #71495

**Comment by PatrikLundell** [comment]
I've seen that kind of thing as well. However, since the weird error reports have gone away when I've fixed my issues I haven't bothered reporting it.

**Comment by RedMisao** [comment]
While (extremely) annoying this is not critical as you can just `i`gnore them, but by doing so it hides any proper "invalid field" error. So you can edit and fix stuff, but as the proper "invalid field" errors won't show up, they may leak through if you don't exit and re-enter the game to check there are none.

(I also suffer from this, having posted in the PR you referenced. RenechCDDA commented there should be an issue for it somewhere, but I couldn't find it)
