### ISSUE TITLE
UPS-powered tools draw power from UPS that is turned off as long as it's in inventory and loaded with a battery

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#72320]
### Describe the bug

UPS-powered tools draw power from UPS that is turned off as long as it's in inventory and loaded with a battery

### Attach save file

[ups_test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14560149/ups_test-trimmed.tar.gz)

### Steps to reproduce

Activate UPS, activate UPS-powered tool (like phase immersion suit in the save), deactivate UPS. Observe UPS charge still going down.

### Expected behavior

I expect UPS that's turned off to not work.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 0f9df4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by DPavonis** [comment]
/confirm

Standalone UPSes that are (allegedly) off are treated like they're still on. I suspect this is a caching issue with the UPS's transforming not updating the relevant cache, but what that is and where, I can't figure out for the life of me.
