### ISSUE TITLE
Vehicle cooler not venting hot air to vehicle's muffler

### ISSUE THREAD

**Issue by chrsrns** [CleverRaven/Cataclysm-DDA#72323]
### Describe the bug

In an attempt to build a walk-in freezer, it seems that in this specific instance, the vehicle's cooler produces both hot air and cool air, even when it has a muffler.

### Attach save file

[Jacquet-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14561082/Jacquet-trimmed.tar.gz)

### Steps to reproduce

1. Create an airflow isolated room.
2. Create a vehicle construction.
3. Drag it to a door frame.
4. Complete the door construction with 'Build Door', with the vehicle inside it.
5. Add a frame inside the isolated room and another in the outside of the room.
6. Add a muffler in the outside frame.
7. Add a vehicle cooler in the inside frame.
8. Power the vehicle. I added a storage battery and jumper cable-d it to a wall wiring for power. 
9. Turn on the vehicle cooler.

### Expected behavior

I expected that the hot air would be exhausted from the muffler installed.

### Screenshots

![Screenshot from 2024-03-11 23-37-58](https://github.com/CleverRaven/Cataclysm-DDA/assets/43345572/b83e6eea-d74a-4393-81ee-440dd1733050)
![Screenshot from 2024-03-11 23-37-42](https://github.com/CleverRaven/Cataclysm-DDA/assets/43345572/e9cc22e9-73b7-4a5c-9397-335b3aebec26)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 84b2f37 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by SSpook** [comment]
Mufflers vent hot air at the next tile without a vehilce part behind the muffler, same spot where regular exhaust gases appear. Your freezer will work properly if you move the freezer to the front and move the vehicle so that the forward end is facing the room.
