### ISSUE TITLE
sunflower seeds have no calories

### ISSUE THREAD

**Issue by shadowsapex** [CleverRaven/Cataclysm-DDA#72335]
### Describe the bug

sunflower seeds crafted from a sunflower have no calories

also crafting fried seeds using them resulted in no calories

### Attach save file

n/a

### Steps to reproduce

spawn sunflower
craft sunflower seeds using it

### Expected behavior

it has the correct number of calories

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/53508415/8da4b38f-ca98-47d0-bf92-1f28e81fc34e)
spawned vs crafted sunflower seeds

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3155 (23H2)
- Game Version: 0f9df4f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Zyzarda** [comment]
This is caused by the sunflower seed json missing the NUTRIENT_OVERRIDE flag, I've already fixed it and am making a PR.
