### ISSUE TITLE
"Length of railroad track" is not 1 meter

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#72333]
### Describe the bug

The description of the "length of railroad track" states that it is "A heavy one-meter length..." amount of material, while its length stat is 50cm.

### Attach save file

N/A

### Steps to reproduce

 1. Acquire a "length of railroad track"
 2. (e)xamine it
 3. Length will not match the description of "one-meter"

### Expected behavior

The item to be one meter,

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: ef537eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/773fa35332a21db3cb7e6381b185814390356cd0/data/json/items/resources/metal.json#L1126-L1130

**Comment by DobriniaMerk** [comment]
Fixed along with the barter price, which also was same as the half length track.
