### ISSUE TITLE
Too much zombies in cities 

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#72339]
### Describe the bug

#69980 re-added pre generated hordes, but there is tons of zombies now in cities, and hordes works very bad. They will non-stop coming to you, making you to fight with all zombies in cities
Here is screenshots as example

<details>
  <summary>Screenshots</summary>
 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/d0870414-136d-4472-8beb-d862c938f022)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/92a0f080-6fa9-47fa-b77e-2b31bfacc29c)

</details>

There is 9 houses with 3-4 places for residents each. So in this city should be ~ 36 peoples. But here is more, than 100 zombies, 80 on the screenshot, but the screenshot dont take all of this little city
And you cant meet abandoned cities, so the version of coming bandits or peoples from other cities does not work

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14576168/test-trimmed.tar.gz)

### Steps to reproduce

Teleport to city and see tons of zombies

### Expected behavior

Dont have so unreasonable number of zombies

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 84b2f37 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90,7%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by KHeket** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/10662b4c-26bb-4711-b11f-e222b8d3202f)
I just killed all zombies, which I can find in this city, there is 104 zombies and 1 dog

**Comment by KHeket** [comment]
Another example - 7 houses and 138 zombies 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/2140d816-fc35-4cb0-a374-1ce9668a57ce)![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/800d66fa-195a-44fa-9f86-659a4c18f89b)

**Comment by KHeket** [comment]
@esotericist check pls, because this problem occurs only after #69980

**Comment by Maleclypse** [comment]
> @esotericist check pls, because this problem occurs only after #69980

eso is on break for the moment. Your issue is up and visible to the people who would act on it currently. Thanks!
