### ISSUE TITLE
About `relic_data` and items with pink colored names

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72337]
### Is your feature request related to a problem? Please describe.

#72304 and a PR from the past removed relic data from endless teapots & whiskey and many other magic items.

How about a flag or anything that gives or hides a 'pink colored' name? Some magic items could have it (such as storage rings), and some non-magic items that shouldn't be giving a magic item feel could hide it. (such as claw item that comes with claws mutation, or frontier cryosuit/mask in Aftershock)

### Solution you would like.

A flag that gives or hides pink color from item names.

### Describe alternatives you have considered.

Comments in #72304 mentioned that color tags could work with items, but I'm scared that it might cause confusion when it comes to localization or adding future content.

### Additional context

Why on Earth is my `claws` glowing pink

**Comment by John-Candlebury** [comment]
Theres a "MUNDANE" flag for this purpose, but its newer than most aftershock 'magic' items.

You can help out by going over the json and adding that flag where appropiate, if you have the chance.

**Comment by AnotherSeawhite** [comment]
> Theres a "MUNDANE" flag for this purpose, but its newer than most aftershock 'magic' items.
It does exist? :eyes:

> You can help out by going over the json and adding that flag where appropiate, if you have the chance.
I'll consider that after finishing draft PR I've opened.

**Comment by AnotherSeawhite** [comment]
> Theres a "MUNDANE" flag for this purpose, but its newer than most aftershock 'magic' items.
> 
> You can help out by going over the json and adding that flag where appropiate, if you have the chance.

It does exist? :eyes: I'll check it out after finishing the draft PR I've opened earlier.
