### ISSUE TITLE
Segfault when moving or picking up items

### ISSUE THREAD

**Issue by florissmit10** [CleverRaven/Cataclysm-DDA#72340]
### Describe the bug

After updating to the latest experimental my save game is crashing. It was working fine for a while, but after entering a city crashes started happening.
I can make a few moves until it happens, but then the game segfaults.

### Attach save file

[El Dorado Springs-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14577178/El.Dorado.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Open my save
2. Walk around and/or pick up items

### Expected behavior

No crash

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.2.1; Build: 23C71; 
- Game Version: 3ccc5fa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    No Hope [no_hope]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14577180/debug.log)
[segfault.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14577181/segfault.log)

**Comment by Brambor** [comment]
Last line of debug:
```

19:37:44.986 ERROR SDL : src/cata_tiles.cpp:759: The tileset you're using has no 'unknown' tile defined!
19:37:44.986 INFO : Loaded tileset: UltimateCataclysm
```

Maybe a quick workaround for you would be to use different tileset.

**Comment by florissmit10** [comment]
I tried a few, but they all crash

**Comment by SurFlurer** [comment]
/confirm.

Actual backtrace:

	cataclysm-tiles.exe!item::get_var(const std::string &) Line 1911	C++
 	cataclysm-tiles.exe!item::weight(bool, bool) Line 7050	C++
 	cataclysm-tiles.exe!npc::can_take_that(const item &) Line 3785	C++
 	cataclysm-tiles.exe!`anonymous namespace'::good_for_pickup(const item &, npc &, const tripoint &) Line 220	C++
 	cataclysm-tiles.exe!npc::pick_up_item() Line 3680	C++
 	cataclysm-tiles.exe!npc::execute_action(npc_action) Line 1664	C++
 	cataclysm-tiles.exe!npc::move() Line 1560	C++
 	cataclysm-tiles.exe!`anonymous namespace'::monmove() Line 322	C++
 	cataclysm-tiles.exe!do_turn() Line 620	C++\

It seems that an NPC tries to pick up a piece of glass shard, and the game fails to get the `weight` element of `item_var`. However it's strange that the compiler optimized `item_var` away so I cannot check what's in it.

**Comment by Brambor** [comment]
> However it's strange that the compiler optimized `item_var` away so I cannot check what's in it.

Compiler is always right, it wouldn't have worked anyway :D. I didn't investigate this at all thought.
