### ISSUE TITLE
Passions

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#72351]
### Is your feature request related to a problem? Please describe.

I was thinking of a change to skills to make them a bit less boring, & this may be the solution.

### Solution you would like.

If your character has a passion in a skill, then a few things will happen:
-Faster Learning & Reading speeds
-Slightly faster crafting times (If the skill is used in it)
-Morale Bonuses when doing it
-Morale Debuffs when not doing it
-Just overall better at it.
-Couple other benefits depending on what it is (Ex: Mechanics being able to repair twice or Health care being faster at autopsies or something.)

### Describe alternatives you have considered.

Not doing it

**Comment by I-am-Erk** [comment]
This is a cool idea, but this post lacks enough information to be useful as a suggestion, I'm afraid.

**Comment by PGR-14** [comment]
I'll try to flush it out more then.
