### ISSUE TITLE
[MoM] Enhanced Mobility aura penalizes encumbrance due to layering

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#72364]
### Describe the bug

Enhanced Mobility is supposed to reduced encumbrance penalties, per its description ("you can move more easily even in encumbering gear").

The aura item has negative encumbrance and `Coverage: Outer aura`; however, when the power is cast (and the item is created/added to inventory/worn), it gets put on the innermost clothing layer (possibly because "[t]his is integrated into the body"), causing layer conflicts (`wearing this outside your enhanced mobility is adding encumbrance to your torso` etc.) and instead penalizes encumbrance.

This can't be resolved manually (via armor sort interface) because the `enhanced mobility` aura item is considered integrated armor and cannot be moved above other clothing (`Can't move your integrated armor!`), nor can other clothes be moved below it (`Can't sort this under your integrated armor!`).

### Attach save file

[Test World Please Ignore1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14586377/Test.World.Please.Ignore1-trimmed.tar.gz)

### Steps to reproduce

1. Equip some kind of encumbering clothing (does not need clothing conflict) that is not in your personal aura/an aura around you e.g. `nomad bodymesh` or `mercenary body armor` or `load bearing vest with sling` (in fact, all three can be combined).
2. Observe encumbrance value in sort armor screen or player info screen.
3. Cast enhanced mobility.
4. Observe encumbrance value.

### Expected behavior

Enhanced mobility reduces encumbrance instead of increasing it.

Alternatively, power's description should be changed to reflect what it actually does.

### Screenshots

Character's encumbrance without enhanced mobility:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/3744055/97a4ced8-3208-4ed8-823f-95b138032c39)

Same character's encumbrance, with enhanced mobility:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/3744055/d106de42-1525-43f8-90b4-bd77f3f33e29)
(Note also the description of the `nomad bodymesh`: "Wearing this outside your enhanced mobility is adding encumbrance to your [...]".)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 96cca64 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

Just now observing this after updating to latest from ~3-7 days ago. Playing on what was originally an overpowered testing/debug character that I got over-invested in.

**Comment by Standing-Storm** [comment]
> Wearing this **outside** your enhanced mobility 

This is extremely weird because it's supposed to go PERSONAL -> SKINTIGHT -> NORMAL -> OUTER -> BELTED -> AURA.  I'm surprised it even allows you to try to wear something on the outside of an AURA effect.

But, I have another way to fix this (I think) that stops Enhanced Mobility from being an item, which is better anyway.
