### ISSUE TITLE
Armored zombie should have higher power armor drop rate.

### ISSUE THREAD

**Issue by yuganxia** [CleverRaven/Cataclysm-DDA#72363]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/31246176/14e7ca61-629e-418b-ab3c-19e5e22d5515)
Salvaged power armor drop rate is 20%, should be higher for realistic reason.

### Solution you would like.

power helmet might get lost in accident, but an unintelligence zombie can hardly remove a power suit by accident or by itself.

### Describe alternatives you have considered.

Make dorp rate of Salvaged power armor 80% maybe?

**Comment by PGR-14** [comment]
Yeah, around 80% is good, allows leeway for the possibility for it to be damaged beyond salvaging

**Comment by DoctorBoomstick** [comment]
To be honest, I don’t understand, logically, why the power armour suits are set to the salvaged items rather than military-ready, functioning armour. The zombies wearing them were explicitly soldiers, and I never understood why they’re walking around in, essentially, intentionally demilitarised equipment.

**Comment by PGR-14** [comment]
Yeah, I was thinking that too, the person who made it probably didn't know of those variants (Mainly because they're named different things) or didn't exist yet & no one bothered to fix it.

**Comment by ADekema** [comment]
Power armour that a zombie would be wearing would be exposed to the element and constant wear and tear from the zombie moving around. Combine this with the zombie inside rotting and mutating and the chances of a armor being even semi-functional are very slim. The only way I could see a survivor getting a functional power armor from a zombie is by repairing one or paying someone else (exodii) to repair it.

I do think that powerarmor should showup more frequently in military sites.

**Comment by yuganxia** [comment]
From a gameplay perspective, military-ready and functioning armour is the end game item, it just should not drop that easy?

May be we need a power armor story line.

**Comment by Kantonine** [comment]
well, there already are changes being done to the power armors anyways, id rather wait for that to finally go through before doing anything else related to exosuits

**Comment by yuganxia** [comment]
> well, there already are changes being done to the power armors anyways, id rather wait for that to finally go through before doing anything else related to exosuits

Indeed, things should be changed but not now.
