### ISSUE TITLE
Npcs in general are way too static!

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72372]
### Is your feature request related to a problem? Please describe.

I just completed a mission where i shot down 3 bandits on an open field and they literally did not react aside from throwing the occasional aluminum can.

### Solution you would like.

Npcs need to move more, idle around a position, panic whenever being shot at, search to break line of sight, heal eachother, and run you down if needed!

**Comment by Fris0uman** [comment]
this is not an actionnable request, "make NPCs better" is too broad
