### ISSUE TITLE
From 0.G stable to latest experimental, every character loses their "mutation" hair. Everyone is Bald.

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72391]
### Describe the bug

All characters lost their hair "mutation" and now they are bald. something to do with the refactor of how hair works maybe?

### Attach save file

N/A

### Steps to reproduce

1. make a player with hair in 0.G
2. Update the game to latest experimental.
3. Alopecia ensues.

### Expected behavior

I expected that every npc kept their hair.

### Versions and configuration

- Windows 10
- English
- "dda", "no_npc_food", "personal_portal_storms", "no_fungal_growth", "package_bionic_professions", "mindovermatter", "railroads".

**Comment by RedMisao** [comment]
The hair json styling was changed at some point past 0.G, before they were individual mutations for each hair style and color iirc. They were changed into hairstyles containing hair colors (as variants).
Maybe the obsoletion process didn't or can't visually "port" the old appearances to the new ones, if this is what you mean by refactor.

**Comment by harakka** [comment]
> or can't visually "port" the old appearances to the new ones

Not breaking hair from stable was a requirement for that PR to be accepted, so this definitely should be working.

**Comment by ZhilkinSerg** [comment]
Is it true for all tilesets in your game version? It is possible that only some tilesets are affected - see https://github.com/I-am-Erk/CDDA-Tilesets/issues/2237

**Comment by anoobindisguise** [comment]
> > or can't visually "port" the old appearances to the new ones
> 
> Not breaking hair from stable was a requirement for that PR to be accepted, so this definitely should be working.

All of the classic hairstyles no longer exist, creating an error on game load followed by everyone being bald. Only thr "new style" hair muts are in the game now.

**Comment by MNG-cataclysm** [comment]
This is not good. I guess migrating the mutations could fix this? I'll experiment today.

**Comment by anoobindisguise** [comment]
Yeah tilesets are looking for the name of the mutation, so it's probably important to just keep these legacy mutations in a separate file and make them not be choosable. It doesn't do much harm, even with a migration people may have to manually edit 3rd party tilesets.

**Comment by harakka** [comment]
I guess it was this that broke it? #70017

**Comment by harakka** [comment]
/confirm
Tested with 0.G-> 2dbf12c, reproduces on both Ultica and MSX+
