### ISSUE TITLE
Furnitures/Terrains with `ALARMED` flag does not Sound the Alarm when Hit

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#72405]
### Describe the bug

I noticed that vending machine (and potentially the other furnitures/terrains with ALARMED flag) does not actually blares out their alarm when being hit.

### Attach save file

N/A

### Steps to reproduce

1. get into a world
2. find/debug in vending machine
3. (s)mash it open
4. no alarm

### Expected behavior

it blaring its alarm when being hit.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: c4dec49 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff]
]

### Additional context

Relevant discord convo regarding the issue
https://discord.com/channels/598523535169945603/598529174302490644/1218196735214485606

**Comment by GuardianDll** [comment]
it was removed by accident in 66872, to fix it someone just need to revert this piece of code https://github.com/CleverRaven/Cataclysm-DDA/pull/66872/files#diff-742a716324b97c7b673cb41a50625f5583e55761b4cd8bacaaadf2b2480d0050L3845-L3857

Probably not entire thing, just part of it

```c++
    if( has_flag( ter_furn_flag::TFLAG_ALARMED, p ) ) {
        sounds::sound( p, 40, sounds::sound_t::alarm, _( "an alarm go off!" ),
                       false, "environment", "alarm" );
    }
```
