### ISSUE TITLE
Can't use Caps lock and Esc swap under Wayland in latest experimental builds.

### ISSUE THREAD

**Issue by lsadls** [CleverRaven/Cataclysm-DDA#72401]
### Describe the bug

Currently Caps lock and Esc swap not work in latest experimental build.
But it did work in 0.G and version 2023-12-05 when I played it back in 2023-12.

Press Caps lock does send Escape to system which I checked in wev.

### Attach save file

N/A

### Steps to reproduce

1. Enable caps:swapescape in Sway
2. Settings -> Options -> Press Caps lock won't work.
3. Disable caps:swapescape in Sway
4. Settings -> Options -> Press Esc and it works.

### Expected behavior

The Caps lock and Esc swap should work like in 0.G.

### Versions and configuration

OS: Arch linux
DE: Sway
LANG: English

**Comment by ZhilkinSerg** [comment]
Is it working in 0.G right now on same Wayland version on same machine?

**Comment by ZhilkinSerg** [comment]
Related SDL issue - https://github.com/libsdl-org/SDL/issues/6256

**Comment by lsadls** [comment]
> Is it working in 0.G right now on same Wayland version on same machine?
Yes.
Btw key code mode has same result.

> Related SDL issue - [libsdl-org/SDL#6256](https://github.com/libsdl-org/SDL/issues/6256)

Weird, on some sdl2 games(supertuxkart) the caps:swapescape is working, but on other sdl2 games(tome4, warzone2100), Caps lock will don nothing and Esc will trigger both Caps lock and Esc.

**Comment by ZhilkinSerg** [comment]
That's because this is SDL related issue and whether the bug is reproducible depends on SDL version used to build a game.

**Comment by pwalsh0** [comment]
Have been trying out fancy new kde6 and hdr etc. But this bug makes CDDA unplayable so back to X11 we go :)

**Comment by lsadls** [comment]
This bug is caused by the SDL lib shipped with CDDA.
After delete libSDL2-2.0.so.0 in the game root dir, CDDA will use system sdl2 lib and this bug is fixed!

**Comment by lsadls** [comment]
@pwalsh0 ^
