### ISSUE TITLE
PR summary labeler seems to be malfunctioning

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#72419]
### Describe the bug

Some PR are incorrectly labeled as `Info / User Interface`, `Enhancement / Feature` and `Code: Infrastructure / Style / Static Analysis`.

See #72417, #72416, and #72411.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

PR are labeled correctly.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/107d6815-9a14-4208-8781-886049ab4474)

### Versions and configuration

The latest commits' SHA is 773fa35332a21db3cb7e6381b185814390356cd0.

**Comment by Vaskritaya** [comment]
Could this be caused by the examples added by #72379 ? see https://github.com/CleverRaven/Cataclysm-DDA/blob/0bb40773a90f740852bd3e90165a90998fb87798/.github/pull_request_template.md?plain=1#L21-L26
