### ISSUE TITLE
Android Bughunting

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72420]
A lot of bugs appeared since SDL got updated. This bug report lists not all but most of them.
I'll also write possible workarounds on 'Additional context'.

### Describe the bug

1. **(RESOLVED)** Canvas does not scale properly

This is(was) probably the most problematic bug. When you launch the game, there's a small probability that the canvas will refuse to rescale at all.

2. Broken IME and composition (Is it happening only in Android?)

When you type CJK characters (haven't tested in Chinese and Japanese), the game inputs the letters in a completely broken way.

3. Sprites transparency is weird

This is a duplicate of #72213, but I think it's worth mentioning, and it's pretty straightforward. 
The sprites are more opaque, as if there are two sprites overlapping on top.
This does not happen on builds with older SDL versions (needs confirmation).
![무제417_20240307080300](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/c4cbfd9f-ad1f-481e-980b-46b6d30f04d7)

### Steps to reproduce

2. Broken IME and composition

This one is pretty easy to reproduce.
When you're typing Korean, you type consonants and vowels to complete a letter. This used to work. (wasn't perfect but it worked)

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/bf5fa319-b0a7-429f-baa4-6cc61419ef1c

But with new SDL versions, the game inputs... whatever this is.
The system that helps you to complete a letter, is completely broken, and it'll spit everything out. (I couldn't think of a better explanation)

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/10b99b82-948a-4bca-9dc7-77a5bcf6c6c5

3. Shown above.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 14; Incremental: G991NKSS4FXAD; 
- Game Version: c4dec49 [64-bit]
- Graphics Version: Tiles

### Additional context

For issue 2, use a keybind that swaps the game's language to English so that you can search for items and use filters, etc.

For issue 3, using software rendering solves the issue, but that would be horrible, isn't it?

If there are other bugs or workarounds that I'm not aware of, please write them in comments. It would help a lot.

**Comment by Srcwya** [comment]
I noticed my shortcut buttons only pop up after i interacted with a menu that uses them. 

That didnt happen for you?

**Comment by AnotherSeawhite** [comment]
I can't tell if it happened to me. I have fairly less bugs than other people for some reason.
Would be appreciated if you post a recording.

**Comment by Srcwya** [comment]
> I can't tell if it happened to me. I have fairly less bugs than other people for some unknown reason.
> Would be appreciated if you post a recording.

https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/602140d6-8325-4179-b064-66b13b6b61ea

**Comment by Srcwya** [comment]
Shortcuts only appeared once i interacted with that menu

**Comment by katemonster33** [comment]
I installed previous versions of the game before the SDL update and found that you couldn't input non English characters at all, regarding the second issue.

We have issues already for the main issue reported here, I don't see the need for having yet another issue for this.

**Comment by AnotherSeawhite** [comment]
> We have issues already for the main issue reported here, I don't see the need for having yet another issue for this.

You're right, but I've still decided to make an issue of this to organize reproductions and workarounds.

**Comment by AnotherSeawhite** [comment]
And regarding the non-English keyboard, this is how it should work.
Tested in 0.G stable.

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/ad32b495-4732-4e45-ad8e-c73e0097c11e

**Comment by AnotherSeawhite** [comment]
Perhaps we could find a hint in #63672?

**Comment by katemonster33** [comment]
> And regarding the non-English keyboard, this is how it should work.
> Tested in 0.G stable.
> 
> https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/ad32b495-4732-4e45-ad8e-c73e0097c11e
> 
> 

![Screenshot_20240319-175029.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/24497894/2b45825b-c251-4754-8d07-05ae5c2d85c6)

This is what I see on 0.G when I open the standard android keyboard and select Korean input. Keyboard keys do not change

**Comment by AnotherSeawhite** [comment]
Ohhh you meant that? Now that's concerning.

**Comment by AnotherSeawhite** [comment]
You're using Pixel, right? It's probably using Gboard as default keyboard. Can you record a video about it?
