### ISSUE TITLE
COMPILING-MSYS missing a step

### ISSUE THREAD

**Issue by pierredavidbelanger** [CleverRaven/Cataclysm-DDA#72426]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-MSYS.md#cloning-and-compilation

the make command does not find the g++ executable, we need to add `/ucrt64/bin` to the `PATH`. It work if we set it just before the make command like that: `PATH="/ucrt64/bin:$PATH" make ...` 

### Attach save file

n/a

### Steps to reproduce

follow the howto, line by line, it fails

### Expected behavior

one should expect it to work without extra step

### Versions and configuration

latest git clone

**Comment by ZhilkinSerg** [comment]
Path variable updates were removed in https://github.com/CleverRaven/Cataclysm-DDA/pull/71089

**Comment by pierredavidbelanger** [comment]
ill close my own issue, as [pointed out here](https://github.com/CleverRaven/Cataclysm-DDA/pull/72427#discussion_r1527218170) `ucrt64' is not the only env and may be the wrong choice on some installation.
