### ISSUE TITLE
"NO_BREATHE" monster flag does not apply to effects from regular smoke

### ISSUE THREAD

**Issue by TheSaddestGoomba** [CleverRaven/Cataclysm-DDA#72439]
### Describe the bug

The "NO_BREATHE" flag makes creatures immune to the effects of tear gas, sleep gas and others, but not the effects 'smoke_inhalation' and 'smoke_irritation'.
Even the Talon UGVs are affected.

### Attach save file

N/A

### Steps to reproduce

Make some smoke, debug spawn a monster with "NO_BREATHE" into the cloud.

### Expected behavior

That monsters with the flag would be unaffected similarly to other gas effects.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 0bb4077 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
Hmmm
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/6b948ab1-f3fd-497e-a906-1c3a581703eb)

**Comment by RenechCDDA** [comment]
Looks like a simple fix, the smoke fields simply needs to have `has_fume` set to true. This makes NO_BREATHE monsters immune to it.
