### ISSUE TITLE
USMC F.R.O.G Gear as Military Clothing Fire Resistant Alternatives

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#72430]
### Is your feature request related to a problem? Please describe.

With the addition of the USMC into cdda, it makes sense to represent their uniforms and gear more closely, instead of just.... zombie soldiers in blue. Theres also a lack of some basic nomex equipment, filling the gap between heavy turncoat uniforms, Kevlar firesuits, and very unassuming nomex undergarments. The addition of Fire Resistant Organizational Gear (F.R.O.G) fits

### Solution you would like.

Add Nomex only/ maybe Nomex+Synthetic Fabric Blend
Combat Shirt variant + New Mercenary Body Armor Variant
Pants and Survivor pants variant
T-shirt and Long sleeve shirt.
nomex balaclava
maybe gloves?

### Describe alternatives you have considered.

*shrug*

**Comment by Kantonine** [comment]
Also almost forgot to mention
The Military Flightsuit is very meh, as it is rn, its not all that useable for anything except being a 110% breathability normal layer jumpsuit, is there any upsides to it that arent immediately notable? (besides it being great nomex scrap)

**Comment by tenmillimaster** [comment]
Which IRL item would you consider for a body armor variant? I went looking for the bill of materials for the USMC gen3 plate carrier [https://sam.gov/api/prod/opps/v3/opportunities/resources/files/faeeb286cc6cb73c0eee3723fa382c0e/download?&status=archived&token=](here), and there's some amount of fire retardant nylon, but it does not appear to be much. I would not consider it equivalent to nomex. I'm not aware of any FROG body armor item, either.

**Comment by Kantonine** [comment]
> Which IRL item would you consider for a body armor variant? I went looking for the bill of materials for the USMC gen3 plate carrier [here](https://sam.gov/api/prod/opps/v3/opportunities/resources/files/faeeb286cc6cb73c0eee3723fa382c0e/download?&status=archived&token=), and there's some amount of fire retardant nylon, but it does not appear to be much. I would not consider it equivalent to nomex. I'm not aware of any FROG body armor item, either.

Well, to keep this in line with the regular Mercenary Body Armor (lsurvivor_armor) it would essentially be the combat shirt with the kevlar vest stitched on overtop, maybe it would just be the F.R.O.G. shirt, the kevlar vest stitched on top, and then sandwiched between another covering layer of Nomex?
