### ISSUE TITLE
golfer item spawn on roof does not properly put vodka in the bottle

### ISSUE THREAD

**Issue by robinthedragon** [CleverRaven/Cataclysm-DDA#72443]
### Describe the bug

i encountered golf-related items on an apartment tower roof, including a glass bottle and vodka
but the vodka isn't inside the bottle. it's on the ground next to the bottle

### Attach save file

[Wainwright-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14626426/Wainwright-trimmed.tar.gz)

### Steps to reproduce

1. check roofs
2. find golf bag, score card, etc
3. also find empty glass bottle and a puddle of vodka on the same tile

### Expected behavior

i expect the vodka to be in the bottle

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92946919/7e810f8b-f31c-4856-a465-21f3f6de4eea)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 0bb4077 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]

i've also deleted data/json/monsters/fungal.json from my game files. but i really doubt that's causing the issue

**Comment by RenechCDDA** [comment]
Curstwist had a lot of experience even at that point, and it would take a significant level of misunderstanding to misapply this in mapgen.

Thank you for the report, but it does seem intentional.
