### ISSUE TITLE
Randomly generated corpse of child is not considered as human corpse

### ISSUE THREAD

**Issue by Paramachina** [CleverRaven/Cataclysm-DDA#72444]
### Describe the bug

Randomly generated corpse of child is not considered as human corpse.

### Attach save file

N/A

### Steps to reproduce

1. spawn child corpse, try butchering it. 

### Expected behavior

I expected that human corpse, not zombie one.

### Screenshots

![스크린샷 2024-03-17 155821](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/24f8f90a-bd8f-4900-9767-bd1636b8367b)
![스크린샷 2024-03-17 160241](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/837dd0ec-7046-4be0-a47f-2b1a5e3004b2)
![스크린샷 2024-03-17 161104](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/2527a0a2-9138-49e6-9ae8-5b11abbc0e7c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3235 (23H2)
- Game Version: 4fdf92b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
/confirm Fixing the butchering yields took two seconds but the dissection harvest field doesn't allow overriding and copy froms the zombie child, I'll look into a C++ fix
