### ISSUE TITLE
Adding ways to heat food in batch

### ISSUE THREAD

**Issue by yuganxia** [CleverRaven/Cataclysm-DDA#72477]
### Is your feature request related to a problem? Please describe.

Cooking tools that use electricity, such as electric stoves, can only heat one portion of food at a time with the heat food function.
When it comes to 20 portions of food that need to be heated or defrosted, the process of performing 20 heating actions can become very painful.

### Solution you would like.

If you can use an electric stove to heat a pot that holds food, a container of this type that has a cooking function (or is made of metal), put the item need to be heated into the pot, and heat pot up, could be better.
To make this happen：
1. Adding holsters to the electric stove，and put pot on it to heat.
2. When use stove, make some of the pot selective.

**Comment by Cenness** [comment]
Washing interface would be ideal for this - [a]pply something that you can heat food with, ui shows multiselect list of heatable items

**Comment by yuganxia** [comment]
Heat_item in iuse.cpp is still using character.assign_activity().
heat item action is not in activity_actor_definitions.h
Might should make it a standard activity first.
