### ISSUE TITLE
Game loglessly crashes when my CBM power goes over ~40%

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#72474]
### Describe the bug

When my power goes too high via jumper cable or gasoline fuel cell or anything, it just instantly crashes the game. It's weird as heck

### Attach save file

[Southwood Acres-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14630159/Southwood.Acres-trimmed.tar.gz)

### Steps to reproduce

1. Enable gas fuel cell, full and ready in linked save
2. Wait a bit
3. Crash

### Expected behavior

It no crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 6f5392e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
Unable to reproduce on 9c3b7d1bf9389395cf010e432f315ea6233cab4c (MSVC compiled locally)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/ac975583-f79d-41bb-af41-13fa972f2d11)

**Comment by carlarctg** [comment]
{
    "type": "mutation",
    "id": "CANT_WAIT_FOR_FIX",
    "name": { "str": "Impatient" },
    "points": 1,
    "description": "You want to experience all the game, the most recent version, but can't tolerate the bugs it may bring with.",
    "enchantments": [ { "values": [ { "value": "FATIGUE_REGEN", "multiply": 1 } ] } ]
  },
  
  I have this big funny. That this causes a crash somehow is baffling.

**Comment by carlarctg** [comment]
Update, I've updated to master, without the above funny, and the bug is still happening. Worse, it seems to be occurring randomly on some 'slow' actions such as crafting, waiting, deconstructing, and such.

**Comment by Postalover** [comment]
I have a similar issue related to CBMs that started happening around the time the fatigue regen issue arised. The difference is, in my case, it CTDs on most CBMs activation/deactivation (turning on/off cable charger, oil/ethanol generators, hydraulic muscles, blood filter, etc.). Doesn't seem to crash on blood filter, finger lighter, electromagnetic unit CBMs activation from the limited poking around I did.
I don't know if it's worth mentioning, but when it just started happening, it used to crash once in a while on certain CBMs, but after updating a few builds, including the latest one, it crashes all the time. For instance, a few days ago, I played around with subaquatic navigation system CBM and it worked fine, no crashes on activation/deactivation. Playing 2024-03-18-0013, however, using this CBM crashes the game as well.
Oh, and I have butchered my modlist to include MoM and SpeedyDex mid-playthrough, so... yeah.
If anyone can point poor silly me to where I need to attach any files, if needed, I'd appreciate it greatly.

**Comment by carlarctg** [comment]
That would  that the issue is somewhere in CBM power gain/loss specifically

**Comment by carlarctg** [comment]
It just crashed from me trying to turn my optical dampers on.

**Comment by RenechCDDA** [comment]
@carlarctg You've got compiling set up, right? Get a stack trace for this. Load your save in the compiled build, wait until it crashes. While it hangs in VS, open the call stack, copy-paste here.

**Comment by RenechCDDA** [comment]
Narrowing it down:

It's something within the "Graphs & Meters" part of your sidebar.

**Comment by Postalover** [comment]
Can confirm, switching from 'ZenFS thick' sidebar to even 'ZenFS numbar', enables me to toggle bionics reliably with no crashes. Switching back to thick version with bionics enabled, however, crashes the game instantly.
