### ISSUE TITLE
ImGui windows don't render when screen is small (too short)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#72470]
### Describe the bug

When you (click / press key) to open a window in the main menu, it looks like nothing happened, just as if the input broke, since you cannot see the selection moving and sound pinging. When you resize the game window, the ImGui window shows up.

The keybinding and popup windows both fail to render.

### Attach save file

N/A

### Steps to reproduce

1. Launch game
2. Set screen ~width~ height to very small (actually 1000px is around the braking point)
3. Open keybindings menu
4. Nothing shows
5. Resize game window
6. ImGui window shows, (but needs resizing to update every time)

### Expected behavior

Windows always render even with the smallest size CDDA supports.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/a8c2bb03-a8c4-44dc-8ca0-8928995ff144)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 0.G-8021-g0bb40773a9-dirty [64-bit] - actually, it is clean master 0bb40773a9
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I don't know what is the version doing. I am recompiling on master, stashing everything, editing files to bump their edit date and editing them back so that VS recompiles it.
Rebuilding the whole project.
Still the "version" is garbage.

This report should be better, but I am gonna go to sleep now.

**Comment by Brambor** [comment]
This seems to be the limiting size (still works)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/cbffe131-b6b4-4e09-9c74-82af0984cb44)

This doesn't work anymore (cannot scroll):
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/3fd93980-eaf4-4fca-89b0-61420f08178d)

**Comment by NetSysFire** [comment]
CC @katemonster33

**Comment by ZeroInternalReflection** [comment]
I did a bit of testing on this one.  A couple of observations:
 - This is specifically a Tiles issue.  Curses seems to work fine all the way down to 80x24.
 - On my setup, the window will show up even at small sizes, _but_ it will be broken at the same size of ~1000px
 - Even when broken, input is still clearly being registered.  I can click the 'x' in the top right and the screen goes away.  Similarly, if you click on buttons/the scrollbar/use text controls, the screen will not _display_ updates, but will implement whatever you input (observe how things change when resizing the window forces a display update):

https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/91cd95a5-9d70-4ed8-a812-955d868206c1

(I also checked that the behaviour was the same prior to #72353)

**Comment by ZeroInternalReflection** [comment]
A bit more testing, unfortunately still inconclusive.  This _feels_ like an issue where the ui_adaptor is made too big for the window and fails to draw (see, e.g. #52688), but I don't really have any evidence to back that up, and can't find where it might be going wrong.

To back up my previous assertion that this is Tiles only, here's an example of the keybindings screen showing up in Curses at 80x24:
https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/d605b796-72d3-4192-98fb-aacf6b75db78

To see if the window is being sized correctly I added a bunch of size checks to demo_ui::draw_controls() .  You can see that at a height of 976 pixels, the screen works.  At 975 pixels, it breaks.  However, SDL, ImGui, and the numbers being given to the underlying ui_adaptor all seem to make sense for a screen height of 975 pixels.
https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/35740121-6bf6-4c1a-88d4-092223772614

One note is that on Curses, demo_ui _only_ shows the ImGui demo screen.  This screen that I populated with information for testing does not show up in Curses.  Is that relevant?  Maybe?  Have I figured out why?  No.
I had a notion that the Tiles build was somehow making a ui_adaptor that the Curses version didn't and that's what was breaking, but every configuration I tried had the same number of ui_adaptors in the Keybinding screen and the ImGui demo screen.

**Comment by Brambor** [comment]
I just noticed that in-game keybindings don't work either, nor a new screen I made (when the height is too small).

I wrongly assumed they did work.

**Comment by katemonster33** [comment]
best i can tell, something is going wrong internal to imgui. below a certain window size, imgui simply stops rendering. input gets handled silently, but it's like the SDL backend just kicks the bucket. resizing the window forces a single draw operation to happen, otherwise you get nothing.

**Comment by katemonster33** [comment]
Spent a few more minutes looking at it, this actually is a CDDA problem, sorry. Because the actual ImGui drawing code was moved into ui_manager::redraw_invalidated, when redraw calls happen too far from calls to refresh_display, then the ImGui window is not actually updated on the screen - this seems to happen when the window is small. We need to either fix the way rendering is done on SDL, or add a hack to force refresh_display to be called every time ui_manager::redraw_invalidated is called.
