### ISSUE TITLE
Mod loading does not automatically load in the correct order to account for dependencies

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#72483]
### Describe the bug

When loading a mod that has dependencies, some of which also have dependencies, the dependencies are not automatically accounted for in the auto-sorted mod order. I learned this when working on a personal project, which can be found [here](https://github.com/Standing-Storm/innawood-an-age-undreamt-of) (links in that project to the dependencies

### Attach save file

N/A, demonstrated on world creation

### Steps to reproduce

1) Install relevant mods
2) Activate `Innawood: In an Age Undreamt Of` in the mod list
3) Xedra Evolved Innawoods will be loaded before Innawood, despite having Innawood as a dependency. 

### Expected behavior

Mods are automatically sorted so dependencies are accounted for.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/4ae5ffd4-0ba9-486b-9293-615c44c265eb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 9733666 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    Megafauna [megafauna],
    Innawood [innawood],
    Xedra Evolved Innawoods [xedra_evolved_innawoods],
    Innawood Hostile Villages and Color Locations [feral_villages_innawood],
    <color_green>Innawood</color>: An <color_cyan>Age Undreamt Of</color> [innawood_age_undreamt],
    Bombastic Perks [bombastic_perks],
    <color_green>My CDDA personal tweaks</color> [CDDA_personal_tweaks]
]

### Additional context

This bug only occurs if I only specify a mod that has dependencies without also specifying those dependencies. If I explicitly specify the entire tree of necessary mods, they are loaded in the correct order.

**Comment by Standing-Storm** [comment]
Since "If I explicitly specify the entire tree of necessary mods, they are loaded in the correct order" fixes everything, I'm not sure this is actually a bug or not.

**Comment by ZhilkinSerg** [comment]
At least you have a workaround
