### ISSUE TITLE
Larger turbine weighs less than smaller one

### ISSUE THREAD

**Issue by Modzer0** [CleverRaven/Cataclysm-DDA#72489]
### Describe the bug

27L 1350 HP gas turbine engine weighs 2500lbs
38L 1900 HP gas turbine engine weighs 881.81lbs

### Attach save file

N/A

### Steps to reproduce

Shows up in vehicle construction when selecting turbines.

### Expected behavior

I expect the smaller turbine to weigh less than the larger one.

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.2.1; Build: 23C71; 
- Game Version: dd1adff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by SurFlurer** [comment]
I remember that the weight data directly come from their irl counterpart. For example the small turbine is modeled after AGT-1500, which weighs around 2500 pounds.

**Comment by Modzer0** [comment]
The AGT1500 is a tank turbine. A light helicopter like the MD500 uses a 450-shp Rolls-Royce 250-C20R that weighs 173lbs

**Comment by oosyrag** [comment]
Misunderstanding regarding the expected characteristics between a tank turbine engine and aircraft turbine engines.
