### ISSUE TITLE
[MoM] Some welding recipes missing Incandescent lance as tool

### ISSUE THREAD

**Issue by Dancheek** [CleverRaven/Cataclysm-DDA#72480]
### Describe the bug

The Incandescent lance description says it can be used for welding, but there are some recipes requiring welding tools except incandescent lance

### Attach save file

N/A

### Steps to reproduce

1. Increase fabrication skill to 4
2. Search for electric forge recipe
3. It has arc welder as tool but not incandescent lance

### Expected behavior

Incandescent lance should be able to use as tool in all recipes that use default arc welder

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.4046 (21H2)
- Game Version: dd1adff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Mythical Martial Arts [MMA],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks]
]

**Comment by Standing-Storm** [comment]
I just PRed #72481 to fix this generally, but it won't fix electric forge specifically because that recipe [specifically defines the tools it needs](https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-03-18-1108/data/json/recipes/recipe_others.json#L1182-L1227) rather than using a requirement set like `welding_standard`. The electric forge recipe will have to be fixed.

**Comment by Dancheek** [comment]
> I just PRed #72481 to fix this generally, but it won't fix electric forge specifically because that recipe [specifically defines the tools it needs](https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2024-03-18-1108/data/json/recipes/recipe_others.json#L1182-L1227) rather than using a requirement set like `welding_standard`. The electric forge recipe itself will have to be fixed.

I think such hardcoded pack of tools in recipes could be replaced with new requirement sets, with just welding kits/soldering irons, but its more like general game improvement rather then just mod support
BTW, if lance shares some function with acytelene torch such as cutting metals and welding, could it also be used as forge in smithing recipes?

**Comment by Standing-Storm** [comment]
The PR I linked adds it to the requirements list for repairing, so after that's merged it should be able to be used in repairs.

**Comment by Dancheek** [comment]
Im talking about Item repairing through the `use_action`, its the way you repair most of metal items, not with repair recipes
