### ISSUE TITLE
Game crashes when interacting with the evac shelter console

### ISSUE THREAD

**Issue by b2arrival** [CleverRaven/Cataclysm-DDA#72500]
### Describe the bug

Game crashes when interacting with the evac shelter console

### Attach save file

[Kosmos-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14655373/Kosmos-trimmed.tar.gz)

### Steps to reproduce

use e to interact with the console

### Expected behavior

The game doesn`t crash

### Screenshots

![IMG_20240319_140313](https://github.com/CleverRaven/Cataclysm-DDA/assets/110062544/dbe039b8-cea0-4de1-aabf-6abf006e2db3)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>(edit :arch linux)
- Game Version: 9733666 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14655472/crash.log)

**Comment by Procyonae** [comment]
Nothing related to the console seems to have been changed lately so I'm pretty confused as to what would be causing this

**Comment by Icantthinkofanameforthis** [comment]
tried the save and cant replicate crash 
if the crashes are consistent then the only difference i can see is my OS

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 9733666 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NancokPS2** [comment]
Is this consistent, i've had the game crash during the calculation of new mission locations, which the console does.  
The game will basically freeze while it does the math so the OS may think it stopped responding.

**Comment by RenechCDDA** [comment]
Looks to be related to #70338 and by extension, an issue with your distribution's locale settings.
