### ISSUE TITLE
Backup generator disassembly, volume and weight are incorrect.

### ISSUE THREAD

**Issue by turco-ai** [CleverRaven/Cataclysm-DDA#72506]
### Describe the bug

The backup generator gives the incorrect components when disassembling, additionally it's weight and volume do not match the components used to craft it.

### Attach save file

N/A

### Steps to reproduce

1. Acquire backup generator recipe.
2. Observe.

### Expected behavior

That the recipe, volume and weight match.

### Screenshots

![Screenshot_2024-03-19-21-55-43-586_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/114369581/f34e9603-91ac-4f82-bd06-aa3d58022681)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 22031116BG; Release: 13; Incremental: V14.0.5.0.TGLMIXM; 
- Game Version: b9c4092 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
The disassembly recipe was missed when the smaller diesel engines were added, and its recipe changed.

https://github.com/CleverRaven/Cataclysm-DDA/blob/8d5e2e578f0632d19f2936d5cb6a460c1a7e9287/data/json/recipes/recipe_deconstruction.json#L7707

**Comment by RenechCDDA** [comment]
Resolved by #72624
