### ISSUE TITLE
Massive Slowdown at Steel Mill during Night Time

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#72508]
### Describe the bug

Once night time hit my game suddenly halted to a crawl in the specific area im at, if you move away from the area or change the time of day to daytime then the slowdown vanishes.

### Attach save file

[NewEarth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14662091/NewEarth-trimmed.tar.gz)

### Steps to reproduce

1. Walk around the steel mill where my character is

### Expected behavior

I expect it to not slowdown at nighttime at a steel mill

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 0bb4077 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Removes Fungus and Ants [myf_ant_fungal_removal]
]

### Additional context

Removes Fungus and Ants is my mod, doesnt touch anything but overworld map tiles involving Ants and Fungus. There was a zombie necromancer nearby but I killed it so I dont think its that. Other than that, I dont know whats goin on.

**Comment by Myfharad** [comment]
Figured something out. The slowdown cleared when I changed the weather to "Clear" when Mist, Fog or Rain weather the game slows to an absolute crawl in the area.

**Comment by Qrox** [comment]
Could it be related to #65205? What happens if you set the 3d field of vision (in the debug option tab I think) to 0 during mist, fog, or rain?

**Comment by SurFlurer** [comment]
Sounds like #72147 but the slowdown in shadowcasting is direction-specific in this case.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/22912139/909c3890-e7ad-42db-9a85-87a38b4be8be)

The two most prominent directions are:

```
 ..@
 ..
 .
```
and 
```
  .
 ..
@..
```
