### ISSUE TITLE
Did something happen with the releases?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72512]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-03-20-0451

Look at the list of PRs. Weren't they already merged?

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

**Comment by AnotherSeawhite** [comment]
#72509 
Something got borked and spammed changelogs that was in previous stable release.

**Comment by Fris0uman** [comment]
Yes ther was (is) an issue comparing releases to the 0.G instead of the previous one, #72509 should fix it
