### ISSUE TITLE
simplify npc menu,faction menu, and menu that you ask the npc what needs to be done at the camp, plus basecamp storage:drink option in zone manager, more freedom in npc and free from npc microing

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#72527]
### Is your feature request related to a problem? Please describe.

     -simplify npc menu,faction menu, and menu that you ask the npc what needs to be done at the camp: 
there no need to have too many menu for things that are related to each other, should just make one menu have all of them

      -plus basecamp storage:drink option in zone manager:
 the npc just refuse to drink after eating: 
 
      -more freedom in npc and free from npc microing :
  easier to equip them ( after reaching certain trust), the ability for them to automatically thraw or cook food when hungry or attack when doing job( which they did not attack them back)

### Solution you would like.

     -simplify npc menu,faction menu, and menu that you ask the npc what needs to be done at the camp: a menu where you can also save settings for:
   
   +commands for combat, miscellaneous rules, pickup rule, so that you don't have to re doing it again and again, and when starting a new save.
   +the faction menu: the will show the current follower in that faction which you could talk to and you have the menu which appear when you select the option what needs to be done at the camp when you ask your npc
   
       more freedom in npc and free from npc microing :
 in the same menu, having loadout save for npc loadout

**Comment by Brambor** [comment]
Consider using lists, like this
 - item 1
 - item 2

Or this, if things are getting fixed
- [ ] unsolved
- [x] solved

**Comment by Brambor** [comment]
> pickup rule, so that you don't have to re doing it again and again,  and when starting a new save.

~Isn't there a global pickup rule? Aren't you making rules for a character instead of global rules?~ Wait, you are talking about NPCs. Maybe a template could be made... it needs thinking.

**Comment by Brambor** [comment]
> attack when doing job( which they did not attack them back)

I don't understand that.

**Comment by Brambor** [comment]
> -plus basecamp storage:drink option in zone manager:

Is this completely unrelated to the rest? Is it a bug report? Btw. isn't it caused by the NPC being too full to drink?

**Comment by Brambor** [comment]
There is so much in this issue that it is hard to read since it isn't focused on a single problem or the problems aren't explored very deeply.

And if there will be any discussion, it cannot be managed, since it would be about 5 topics at the same time in the same thread.

I would recommend splitting it up and making it more detailed. If you offer a direct solution and show that it is better, somebody might pick it up.

**Comment by Brambor** [comment]
> there no need to have too many menu for things that are related to each other, should just make one menu have all of them

I haven't played the game for a while. If you posted screenshots and showed how the menus are similar, then I could understand. Describe why is it a problem that there are too many menus. Mock up a menu (make a picture, a list or some other understandable representation) that you would prefer and describe why would it be better. That would greatly increase the chance for somebody to pick this up. Now, if anyone picks this up, they have to figure all that out including what you meant exactly.

**Comment by blablase** [comment]
> > attack when doing job( which they did not attack them back)
> 
> I don't understand that.

well they were chopping down the tree while the zombie just attack them without them (the npc) fighting back) (they're holding the godamn axe) they didn't even care, only after i tell them to stop

**Comment by blablase** [comment]
> > -plus basecamp storage:drink option in zone manager:
> 
> Is this completely unrelated to the rest? Is it a bug report? Btw. isn't it caused by the NPC being too full to drink?

yeah i kinda lazy to write more stuff

**Comment by blablase** [comment]
> I hope you read this since this issue is your only one! Don't get discouraged!

thanks

**Comment by blablase** [comment]
> > -plus basecamp storage:drink option in zone manager:
> 
> Is this completely unrelated to the rest? Is it a bug report? Btw. isn't it caused by the NPC being too full to drink?

well i would not say that because after i traded them a gallon that contain 15 waters for free, they started to drink, after they just ate

**Comment by blablase** [comment]
> Consider using lists, like this
> 
> * item 1
> * item 2
> 
> Or this, if things are getting fixed
> 
> * [ ]  unsolved
> * [x]  solved

alright

**Comment by Brambor** [comment]
> > > -plus basecamp storage:drink option in zone manager:
> > 
> > 
> > Is this completely unrelated to the rest? Is it a bug report? Btw. isn't it caused by the NPC being too full to drink?
> 
> yeah i kinda lazy to write more stuff

Try to reproduce it in a save that a programmer can load and look at the code to figure out what is happening. Then, it is likely to get attention. Like this, it is a complete shot in the dark.

**Comment by blablase** [comment]
> > there no need to have too many menu for things that are related to each other, should just make one menu have all of them
> 
> I haven't played the game for a while. If you posted screenshots and showed how the menus are similar, then I could understand. Describe why is it a problem that there are too many menus. Mock up a menu (make a picture, a list or some other understandable representation) that you would prefer and describe why would it be better. That would greatly increase the chance for somebody to pick this up. Now, if anyone picks this up, they have to figure all that out including what you meant exactly.

okay the problem with the menu is when you ask them
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/9f122e37-ffa2-4e40-a213-0ffb4fb95594)

then went to another chat let talk about camp 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/3244a91b-f13a-4b23-b728-60d96c7016ae)

then to show me what needs to be done at the camp

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/3d29d4c9-0dc0-4f43-8d0d-2c090572359c)
then you get to this
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/8075d90f-1c68-4fbc-887b-eb787f2603ab)

require alot of clicking

then you need to check something you need to go through all of that again
or when you donate the food into that window then have to go through all that again just to tell your npc to do something related to the camp

**Comment by blablase** [comment]
maybe they should move commands for combat, miscellaneous rules, the help/ tutorial into the faction menu 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/c3ccb22e-caff-498c-baf8-b75a46c4a40e)

the commands for combat, miscellaneous rules should have stuff like who should be affected by this, so you can make like alot of those rule loadout and name them, so for different situtation and area, when you want them to guard and look for the noise surrounding your base or when you go into the city and there like alot of zombie making noise everywhere and don't want them to go investigate the noise and get gang on

oh and i also want this menu to be on faction menu so it easier to access right away when you choose this outpost for example 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/e43ff3cc-a0ea-4e54-8d21-f78db40290c1)
and it will show 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/11203d09-fde1-4bc1-91e4-9d54ac32226a)

**Comment by blablase** [comment]
maybe change the name into faction and npc management

**Comment by Brambor** [comment]
Thanks! These are much better, I can follow what you are saying. If I didn't have so little time I would jump on this one right away:

> oh and i also want this menu to be on faction menu so it easier to access right away when you choose this outpost for example ![image](https://private-user-images.githubusercontent.com/63102395/316237050-e43ff3cc-a0ea-4e54-8d21-f78db40290c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExOTI1MTgsIm5iZiI6MTcxMTE5MjIxOCwicGF0aCI6Ii82MzEwMjM5NS8zMTYyMzcwNTAtZTQzZmYzY2MtYTBlYS00ZTU0LThkMjEtZjc4ZGI0MDI5MGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDExMTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYWRiNmRlZTYxYTQ5YTcwZWNmMThjM2NjZDdlYTcyNTFkNjZlNzY1ZDJmZDdjMDM2MjA4YzIwNjExNzRjYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YgGIqvK0CXrO7mG14a75DfDTNIjom0y7OYEC3BDuN7U) and it will show ![image](https://private-user-images.githubusercontent.com/63102395/316237027-11203d09-fde1-4bc1-91e4-9d54ac32226a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExOTI1MTgsIm5iZiI6MTcxMTE5MjIxOCwicGF0aCI6Ii82MzEwMjM5NS8zMTYyMzcwMjctMTEyMDNkMDktZmRlMS00YmMxLTkxZTQtOWQ1NGFjMzIyMjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDExMTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZjNjM2EwNzAxMTA1YTAxZTEzMzllNjQ3MWY1OTIzNDkwNTM1NjE2OGJhZTkyMmI0MDBiM2MxNDc4NjY4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L-7J7FRKny4nKz74v6S8JEU7-awxH80WLUrRheXa138)

**Comment by Brambor** [comment]
#65609 Added some commands to Chatting with npc `C` menu

**Comment by Brambor** [comment]
I couldn't find an NPC menu/chat rework. I think I saw it somewhere...

Anyway: We cannot just move things around. A graph of talk topics should be created and assessed on what talk topics can be moved where. Otherwise, the changes can be detrimental.

This should include all topics including those not normally visible, so the finished graph should be looked at with the underlying code in mind.

**Comment by blablase** [comment]
> I couldn't find an NPC menu/chat rework. I think I saw it somewhere...
> 
> Anyway: We cannot just move things around. A graph of talk topics should be created and assessed on what talk topics can be moved where. Otherwise, the changes can be detrimental.
> 
> This should include all topics including those not normally visible, so the finished graph should be looked at with the underlying code in mind.

if this was about the help and tutorial then could the already viewed content be sent into the the npc menu, and either using the same name or using the npc (help/tutorial) but the latter option would cause confusion because of the changing in name, they might not know it was the same one.

commands for combat, miscellaneous rules are repeating things that are same for every npc, i just want them be in the npc menu for better management, because then you could save your commands for combat, miscellaneous rules loadout, and dictate which npc should take those loadout

i kinda want to move these around to lessen the words bombardment coming from npc, the (help/tutorial) one does sound reasonable to stay there, but it kinda lessening the load too
