### ISSUE TITLE
Another Mass Typo Issue

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#72520]
### Is your feature request related to a problem? Please describe.

I find a lot of typos and inconsistencies while translating, and write a lot of them down in issues or PR, this is one of those typo reporting issues.

### Solution you would like.

Today's list is:

MoM's description of the spell [Ψ]Mood Stabilization (C) has a double period at the end.

MoM's Banish Illness EOC option descriptions for the Banish Illness Vitakinetic spell has inconsistent spelling and probably should have periods added to the following descriptions:
- Attempt to cure your kaluptic psychosis -> Attempt to cure your kaluptic psychosis.
- Attempt to cure your mood swings -> Attempt to cure your mood swings.
- Attempt to cure your weakening sickness -> Attempt to cure your weakening sickness.

The description for the faction base upgrade "faction_base_modular_furniture1_west" probably needs "book cases" fused into "bookcases":
- We could use some storage containers.  Let's build some book cases to in the western alcove. -> We could use some storage containers.  Let's build some bookcases to in the western alcove.

.32 ACP JHP, reloaded's description has a double period:
- Jacketed .32 ACP ammunition with a 71gr hollow point bullet, intended for use in self-defense..  This one has been hand-reloaded by a survivor or perhaps a pre-Cataclysm hobbyist, leading to slightly inferior performance compared to factory-produced ammo.

The Metamorphosis description of the Chiropteran Mutation line has a !. that should be changed to a ! :
- Every sound is a painful screech in your ears.  It's all too much!.

Radioactive Leak CBM (the item version of the broken CBM) has a missing "has" in its description (description feels a bit clunky to me too):
- A broken CBM that been leaking radiation into its user.  The danger seems to have been sealed off during the removal process, but you definitely shouldn't put it back. -> A broken CBM that **has** been leaking radiation into its user.  The danger seems to have been sealed off during the removal process, but you definitely shouldn't put it back.

XE's vampire fang attack lacks exclamation marks (most attack messages have exclamation marks):
- You sink your fangs into [target] -> You sink your fangs into [target]!
- [NPC] sinks their fangs into [target] -> [NPC] sinks their fangs into [target]!

Additionally, the mainline new Bat mutant bite martial technique for the Critical Vampire Bite technique also lacks an exclamation mark:
- You sink your fangs deep into [target] -> You sink your fangs deep into [target]!

The conditional name for cartridge necklaces using 45 Colt or 454 has revolver misspelt:
- rivolver-cartridge necklaces -> revolver-cartridge necklaces

Hanging Limbs' attack messages could use looking at, the NPC version is obviously wrong but I'm almost certain something's wrong with the player targeting one but can't pinpoint what:
- [void spider?] hanging limbs try to bite your [bodypart] , but fails to penetrate their armor! -> [void spider?]'s hanging limbs try to bite [NPC]'s [bodypart], but fails to penetrate their armor!
- [void spider?] hanging limbs try to bite your [bodypart], but fails to penetrate your armor! -> [void spider?]'s hanging limbs try to bite your [bodypart], but fails to penetrate your armor!

Aftershock's MarSec. 4 has a typo in its firing mode:
- semi-autoi -> semi-auto

Two spiritual book variant titles with double dipping "the"s in their plurals:
- copies of the The Mithraic Inscriptions -> copies of the Mithraic Inscriptions
- copies of the The Orphic Gold Tablets -> copies of the Orphic Gold Tablets

Gun Store Survivor dialogue has a misspelt maybe:
- I'm sorry to hear that.  Mabye we should change the subject. -> I'm sorry to hear that.  Maybe we should change the subject.

XE's Fortified Armor mutation's description needs an end period:
- You embody the tales of ancient knights, increasing the strength of armor you wear by 40% -> You embody the tales of ancient knights, increasing the strength of armor you wear by 40%.

Dinomod's shady zombies need end periods to their description, this concerns:
- shady gallimimus
- shady struthiomimus
- shady ornithomimus
- nighstalker gallimimus
- nighstalker struthiomimus
- nighstalker ornithomimus
- nighstalker thescelosaurus

### Describe alternatives you have considered.

- Fix em' myself
- Not making lists
- Waiting until I found even more
- Doing this earlier

**Comment by Uwuewsky** [comment]
I'll throw in a few of mine
speaking of necklaces, ordinance-cartridge -> ordnance-cartridge (as it is written in the ID)
https://github.com/CleverRaven/Cataclysm-DDA/blob/b314742194a8d1e0c207c91f35b8bbb1f7ecd1a1/data/json/items/armor/jewelry.json#L4315
must be capitalized
https://github.com/CleverRaven/Cataclysm-DDA/blob/b314742194a8d1e0c207c91f35b8bbb1f7ecd1a1/data/json/items/armor/jewelry.json#L4076
extra underscore
https://github.com/CleverRaven/Cataclysm-DDA/blob/b314742194a8d1e0c207c91f35b8bbb1f7ecd1a1/data/mods/Aftershock/items/armor.json#L468
