### ISSUE TITLE
While building "dig out pit and remove anything remaining" you have a chance to fall into a pit

### ISSUE THREAD

**Issue by Krieger1999** [CleverRaven/Cataclysm-DDA#72526]
### Describe the bug

While building "dig out pit and remove anything remaining" you have a chance to fall into a pit. The finished completly diged out pits also disappears after you saved and load in again and turn into earth.

### Attach save file

[Death2-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14693853/Death2-trimmed.tar.gz)

### Steps to reproduce

-Try building "dig out pit and remove anything remaining" from the construction menu for a pit and wait until you randomly fall into it.
-Try to finish the construction
-Save the game and load in again
-See that your hole has disapeared and turned into earth.

### Expected behavior

Not falling into a pit while construction and not having the finished holes disappear after loading in again and turned into earth.

### Screenshots

![grafik](https://github.com/CleverRaven/Cataclysm-DDA/assets/133584226/42728dc5-af4e-497c-8cea-fc13e7d510ae)

### Versions and configuration

Windows 10
Experimentall build: 2024-03-11-0458
Mods: Xedra evolved

**Comment by oosyrag** [comment]
can confirm irl, when digging man sized pits it is possible to fall in and hurt yourself :[
