### ISSUE TITLE
To standardize the dispersion of guns and bullets

### ISSUE THREAD

**Issue by wwkk222208** [CleverRaven/Cataclysm-DDA#72523]
### Is your feature request related to a problem? Please describe.

At present, the dispersion of bullets and guns of different calibers in the game seems to follow multiple sets of standards, some based on realism, and some based on balance. For example, the dispersion of the marksman rifle M110A1 when using 7.62×51mm M80 is 120+15=135 (in reality, its accuracy is 1.5MOA). The dispersion of the TAC-50, which once set the record for the longest sniping distance, when using ".50 BMG Match" is surprisingly as high as 50+100=150. In addition, perhaps for the sake of balance, the game's numerical setting is exceptionally strict on the dispersion of 5.56×45mm caliber. Therefore, the current dispersion of firearms and ammunition does not match the reality, and a relatively unified standard needs to be formulated.

### Solution you would like.

Correlating the dispersion of firearms in real-life data with that in the game, my suggestion is 1MOA = 100 dispersion (gun + ammo). The ratio is considered to be the maximum compatibility with the current game's dispersion setting. The dispersion range of assault rifles in the current game is about 210 to 330, that of precision marksman rifles is around 150, and that of sniper rifles is less than 100 (excluding the unfortunate .50BMG), which coincides with the real-life values: assault rifle (2MOA to 4MOA), marksman rifle (1.5MOA), and sniper rifle (<1MOA). The dispersion of the gun is determined by using high-precision competition or sniper bullets, and the dispersion of the bullet is determined by subtracting the dispersion of the gun when the gun uses regular rifle or machine gun bullets.

### Describe alternatives you have considered.

There is another option: To determine the corresponding ratio based on the game's setting that one grid is equal to 12 meters. However, this option would make all guns extremely accurate.

### Additional context

In the data of real firearms, the testing conditions and calculation methods of the gun's dispersion data are not the same, so it is not possible to fill in completely accurate data based on them, but it will still be better than the current chaotic standards in the game.

**Comment by kevingranade** [comment]
Concretely, here's what needs to happen:
Pick several guns to use as examples,  I recommend the most common guns available in different categories like pistol, assault rifle, hunting rifle, shotgun, pistol calibre carbine, plus some outliers like the most and least accurate firearms available.

Using those example guns,  set up in-game scenarios that demonstrate max effective range, e.g. "so-and-so doc says the m4 has a max effective range of X, which means with perfect aim we expect a 95% hit rate against a human sized target at that range".

Using code similar to tests/ranged_balance_test.cpp, implement that scenario,  while adjusting for in- game range compression.

Adjust the example gun stats to the proposed dispersion,  this can either be something like "MoA/100" or "max effective range" in distance,  where we have a definition of exactly what that means to the game.

Tweak the ranged code until those tests pass,  then start the process of migrating all guns over to whatever the new system implies.

**Comment by wwkk222208** [comment]
Thank you for your suggestion. It seems to take a long time to complete, but I think it's worth it.
