### ISSUE TITLE
[Sky Islands Mod] Cavernous Soul components too rare

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#72531]
### Describe the bug

"Cavernous Soul" currently requires a lot of items, which is fine for most of the required components except for 2: 

- Heavy Duty Pipes (4x)
- set of heavy duty pipe fittings (4x)

These are next to impossible to find, given the only place you can actually  get them from is at hospitals that have a certain machine, that needs taking down then disassembling. The other plausible locations are low % chance at default item spawn rate and I have never seen any at any other place. Elsewise it's impossible to get them, given how rarely hospitals seem to spawn / how the random nature of the trips makes it impossible to find one. 

### Attach save file

N/A

### Steps to reproduce

Not really a bug. 

### Expected behavior

I would expect the recipe to not use nigh-impossible-to-get items that only show up at one place if the map gen feels generous.  (read "Additional Context")

### Versions and configuration

Linux build of the latest experimental branch as of the time of this post.

dda
Sky Islands mod

### Additional context

This problem is made worse by the fact these "heavy duty" items are not craftable (and are probably new additions to the game too). The player cannot find them at home improvement stores or any other place that would make sense to see them at all. The player is limited to arbitrary low % locations which makes no sense. 

Suggestion would be to make the requirements be "X **OR** Y". E.g.:

4 Heavy Duty Pipes **OR** 16 Pipes
4 sets of heavy duty pipe fittings **OR** 16/32 Sets of Pipe Fittings.

**Comment by AcidAntOnAMinefield** [comment]
> Not a problem with a mod, but with vanilla not using and spawning said heavy duty pipes. Solution is to add more places where it can spawn or tweak some disassembly recipes to spawn such pipes

Yep, very much aware of this. My suggestion was for the recipe to be tweaked while the items are still so rare/limited in terms of spawning.

**Comment by gnneo** [comment]
I've completed this base upgrade before. It's one of the more difficult ones for sure.
I disagree that it is too rare: 3x3 hospitals are not particularly rare and these are guaranteed to spawn inside one.

**Comment by oosyrag** [comment]
Perhaps high gauge pipe terrain could be disassembled to get heavy duty pipes and fittings.
