### ISSUE TITLE
Creating rags using wood (Bugs for cutting items)

### ISSUE THREAD

**Issue by TerribLeo** [CleverRaven/Cataclysm-DDA#7254]
I just find it interesting :) to cut items with 2 material tags.

When I make a bindle using 1 heavy stick and 4 rags, I can cut the bindle and get "back" 12 rags and therefore converting the stick into 8 rags...
(bindle has a size of 12 and two material tags which are cotton and wood)

I wonder if we can improve the material tag a little bit. For example, we can add a hidden size value for each material tag (cotton:4, wood:8) so that we can get some rags and some skewers after cutting the item.
##

**Comment by mugling** [comment]
Still present?
