### ISSUE TITLE
mercenary ghosts should not drop loots

### ISSUE THREAD

**Issue by Paramachina** [CleverRaven/Cataclysm-DDA#72545]
### Is your feature request related to a problem? Please describe.

In Physics lab, mercenary ghosts keep spawning until you kill mercenary officer.
It means you can farm mercenary ghosts for MRE, gears or so.

### Solution you would like.

Make mercenary ghost drop no loots.

### Additional context

![스크린샷 2024-03-22 133907](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/1c6fedf0-4bd0-40d6-a12f-8d6e76889de0)
![스크린샷 2024-03-22 133850](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/12c36b37-6d00-46ab-a5cc-6582653b945a)

Took 20 minutes in game, i was just holding tab button. Pretty efficient way to get food imo

**Comment by John-Candlebury** [comment]
Oh this is a regresion, they used to banish as spell summons normally do.
