### ISSUE TITLE
Cargo Pants Aren't Autolearned

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#72547]
### Describe the bug

Cargo pants aren't autolearned, while cargo shorts are. Seems like either both should be autolearned, or neither should be. Not sure if this is intentional, but it doesn't seem like it is.

### Attach save file

N/A

### Steps to reproduce

1. Debug tailoring to max
2. Cargo shorts are autolearned, cargo pants aren't

### Expected behavior

That either cargo shorts and pants are autolearned, or neither are.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1889 (21H2)
- Game Version: ab5b4c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by PGR-14** [comment]
I think there's 2 cargo shorts recipes, one being making them from scratch, while the other is just cutting a pair of cargo pants to length. If you're talking about the from scratch one, It makes sense that your char would be able to make pants too.

**Comment by ERRORCODE509** [comment]
Yeah, referring to the from scratch one in this case.

**Comment by PGR-14** [comment]
You can make a pull request, just go to the cargo shorts recipe, copy it, put the time to complete & material cost higher & replace the name & result w/ cargo pants

**Comment by ERRORCODE509** [comment]
Fair enough, I'll do that later today then.
