### ISSUE TITLE
crash when stepping into vehicle

### ISSUE THREAD

**Issue by marilynias** [CleverRaven/Cataclysm-DDA#72559]
### Describe the bug

when stepping inside vehicle (and some other cases) the game crashes. its always 
```c++ 
/src/catacharset.cpp:

353: cata_assert( sz != static_cast<size_t>( -1 ) );
```

I have tried different game versions and compiling it myself, it's always the same.

### Attach save file

[Valley Green-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14726160/Valley.Green-trimmed.tar.gz)

### Steps to reproduce

Im unable to reproduce on other PC's so its prob something on my PC, but anyways:
1: step in vehicle
2: crash

### Expected behavior

nothing

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 9733666 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14726309/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14726310/debug.log)

**Comment by Qrox** [comment]
Looks like the same problem as #68558. You could probably try https://github.com/CleverRaven/Cataclysm-DDA/issues/68558#issuecomment-1752051767 and see if it fixes your crash.

**Comment by marilynias** [comment]
Thank you, you are a life-saver
