### ISSUE TITLE
[imgui] Can't navigate list in keybindings UI with the keyboard

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#72598]
### Describe the bug

There is no way to navigate the list of keybindings without a mouse

### Attach save file

N/A

### Steps to reproduce

1. Open keybindings UI
2. Press Up, Down, Page Up, Page Down
3. Nothing happens

### Expected behavior

List navigates up and down like in the old UI

### Screenshots

N/A

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-03-24-0121 cf9267f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

N/A

**Comment by katemonster33** [comment]
this is a problem of widget focus, we need to fool imgui into focusing the scrollable view whenever the user presses a navigation key and put focus back onto the filter box when the user presses an alphanumeric key.

**Comment by Brambor** [comment]
You can use TAB to switch focus. It is merely a workaround thought.
