### ISSUE TITLE
[imgui] Can't switch between popup buttons with vimkeys

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#72599]
### Describe the bug

Only the arrow keys work in a popup. vim keys `h` and `l`, as well as `y` and `n` (etc..) don't work even though they are bound.

### Attach save file

N/A

### Steps to reproduce

1. Wait 6 hours
2. Press 5 to stop. There should be a confirmation popup
3. Press h, l, y, and n
4. Nothing happens

### Expected behavior

Bound navigation keys work like in the old UI

### Screenshots

N/A

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-03-24-0121 cf9267f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

N/A

**Comment by katemonster33** [comment]
we will need some way to have ImGui respect CDDA key bindings. Right now navigation keys are hard-coded in the ImGui backends. What we could do is override ImGui's input system completely, this would be no simple task.

**Comment by Brambor** [comment]
> Wait 6 hours

You got me worried there. I was thinking what kinda joke you are pulling or if it compiles for you that long. Only then I realized it is in-game wait action.
