### ISSUE TITLE
Can't reload misc repair kit

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#72603]
### Describe the bug

If you debug in duct tape it works, but if you've got a cardboard roll of it, then it doesn't reload.

### Attach save file

n/a

### Steps to reproduce

get misc repair kit, unload, find duct tape (In roll), & try to reload

### Expected behavior

To reload even when in the roll

### Versions and configuration

Windows 11, Latest experimental

**Comment by oosyrag** [comment]
Duplicate of #71090, thanks for your confirmation!

**Comment by PGR-14** [comment]
Thank you!
