### ISSUE TITLE
World building additions. 

### ISSUE THREAD

**Issue by RanikOrtega** [CleverRaven/Cataclysm-DDA#72614]
### Is your feature request related to a problem? Please describe.

This is a checklist to help sort several "world building" fluff additions that I wanted to make.

### Solution you would like.
**World Fluff**
- [x] Home Pictures Part 1 - Build out framework for home pictures and populate with snippets.
- [ ] Home Pictures Part 2 - Edit Picture spawns to more or better locations, add more snippets.
- [ ] Home Pictures Part 3 - Extend Picture spawns to office environments. Add more snippets. 
- [ ] Location Lore Part 1 - Notes, documents or emails at categories of location that load from snippets. Office Notes, Store Notes, Restaurant Notes.
- [ ] Location Lore Part 2 - Notes, documents or emails at categories of location that load from snippets. EX: Hospital Notes,  Evacuation center notes, FEMA camp notes. 
- [ ] Plants Part 1 - Potted outdoor plants may be a decorative item that could be looted and kept for small morale bonuses.
- [ ] Plants Part 2 - Personality trait "Plant Person" that gets more morale out of plants and leads to Plant mutation tree.
--------------------------------------------------------
**Water Locations**
- [x] Water Locations Part 1 - Flooded Basements for homes or other locations. Keep to a low % chance of spawning variant.
- [ ] Water Locations Part 2 - More flooded Basements for homes or other locations.   Keep to a low % chance of spawning variant.
- [ ] Water Locations Part 3 - Loading Docks locations with nested shipping containers, chance of boats and chance of loot in water / underwater.
- [ ] Water Locations Part 4 - Ship wrecks, underwater wreckage or lost cargo. 
- [ ] Sunken Ship scenario - Start in a tiny air pocket of a sunken ship. Swim to safety (Hopefully) 
--------------------------------------------------------
**Sewer Additions**
- [x] Sewer Additions Part 1 - Extra side rooms for Sewers and small homeless camps.
- [ ] Sewer Additions Part 2 - More wildlife in sewers having tunneled out part of the sewers to make nests.
--------------------------------------------------------
**National Park**
- [ ] National Park Part 1 - 5x5 or larger globally unique park location. Upgraded version of the current "Big" parks. Currently a Zoo is bigger than a State Park. So the national park should be massive if possible. 
- [ ] National Park Part 2 - Possibly add 1-2 NPC's to National park.
--------------------------------------------------------
**Unique Skyscraper**
- [ ] Unique Tower location Part 1 - Initial setup and spawn
- [ ] Unique Tower location Part 2 - Setup Boss / Elite encounter at penthouse "bunker". Zombie / Feral versions of ViP and security team.
- [ ] Unique Tower location Part 3 - Quest or breadcrumb setup to location. 
--------------------------------------------------------
**Hardware Store**
- [ ] Hardware Superstore - Home depot sized hardware store. Rarer and bigger than normal but heavily looted and zombie populated. 
--------------------------------------------------------
**Lodge Community**
 Lodge Community - A small community of initially 3 people.  They are remnants of a prepper militia group where the handful of members that did survive the cataclysm retreated to a large but dilapidated lodge in the woods. They have lost most of their members in the cataclysm and are currently lacking manpower, especially tech competent users to access high tech systems. Quests involve High Value Targets such as Unique Skyscraper, military bunkers, warehouses and prepper houses of "their former members". Lodge evolves from run down to fortified and add new members.  Perhaps even contact the old guard.
- [ ] Lodge Location Part 1 - Create lodge and first NPCs. One Main NPC / trader and handful of other guard NPC's.
- [ ] Lodge Location Part 2 - Initial quest to try to rescue their salvage team from a locked down location. Additional 3 NPC's spawn after quest completion.  
- [ ] Lodge Location Part 3 - Handful of bread crumb quests to low value prepper or military locations.
- [ ] Lodge Location Part 4 - Warehouse raid. Salvage team raided an arms warehouse and found half of the inventory missing with no signs of recent entry. During their raid they left some stock behind and you are free to loot if you use computer skills to track what happened to the warehouse inventory. Bread crumbs to Unique Skyscraper location
- [ ] Lodge Location Part 5 - Leads to bread-crumb only unique location. 
--------------------------------------------------------
**Traps and devices**
- [ ] Trap additions - Razor Tripwire, noisemaker tripwire, scrap-metal traps and more improvised anti-zombie traps etc etc
--------------------------------------------------------
**Achievements + Meta progression**
- [x] Achievement Additions - Achievements for Broken bone X amount of times. Read a book X amount of times. Any other Globally unique locations or important locations I may have missed or are new. LIXA for example.  
- [ ] Achievement for reading more Lore Snippets to "Inform yourself" of events around the cataclysm happening.  Requires functionality to record number of snippets read.
- [ ] Progression via achievement mod. Once you get X statistic your character gains a beneficial trait. Take 1000 damage -> Get trait that increases your HP or gives armor. Requires functionality change to call EOC on achievement. 

Current Achievement ideas not implemented yet: Number of times books read, number of times bones broken, damage taken, damage dealt

### Additional context

Feel free to list any additional achievement ideas that do not exist yet or any comments or suggestions related to the topics above.

**Comment by PGR-14** [comment]
Maybe the park ranger profession could be connected to an achievement from the national park.

**Comment by RanikOrtega** [comment]
> Maybe the park ranger profession could be connected to an achievement from the national park.

That makes a lot of sense. Great idea :)

**Comment by PatrikLundell** [comment]
Since this is a "note to self" post it might not be that important, but if you want to have discussions in a somewhat organized fashion I'd suggest splitting it up into parts centering on common themes.
- "Fluff", photos, possibly plants as well.
- Water stuff
- Sewers
- National park
- HW superstore
- Faction
- Achievements

**Comment by RanikOrtega** [comment]
Curse you github bot!
