### ISSUE TITLE
Bridges are not generating properly.

### ISSUE THREAD

**Issue by turco-ai** [CleverRaven/Cataclysm-DDA#72616]
### Describe the bug

I'm not sure how to describe it other than that bridge ain't normal.

### Attach save file

[Stull-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14747513/Stull-trimmed.tar.gz)

### Steps to reproduce

1. Find any bridge
2. Approach the other end 

### Expected behavior

The bridge should bridge.

### Screenshots

![Screenshot_2024-03-25-14-34-31-970_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/114369581/9b2a280b-52a7-456c-ad4a-c611b33788ff)
![Screenshot_2024-03-25-14-34-44-735_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/114369581/89e89977-5275-48c2-9b8e-ab9c863c9e6a)
![Screenshot_2024-03-25-14-34-56-580_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/114369581/7a335640-5a12-472c-9168-d1988304cd18)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 22031116BG; Release: 13; Incremental: V14.0.5.0.TGLMIXM; 
- Game Version: cdda-experimental-2024-03-25-1531 7511d69 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by miu135** [comment]
I can confirm this is still happening in 0.H
