### ISSUE TITLE
Hey budy

### ISSUE THREAD

**Issue by realmanbroyder** [CleverRaven/Cataclysm-DDA#72611]
### Describe the bug

If you INSERT an item from another NPC directly into your backpack, without picking it up first (open the inventory, go to the backpack, press "insert" and place the items, the theft message will not appear, and the npc won't get mad at you (android, version 0.G

### Attach save file

open the backpack, press insert, take the items from the npc without the theft message appearing 

### Steps to reproduce

1: open the back pack
2:select "insert"
3: insert the itens of npc in your bag

### Expected behavior

the theft message should appear even if you insert it directly into the bag 

### Screenshots

![Screenshot_20240325_102844_Cataclysm DDA](https://github.com/CleverRaven/Cataclysm-DDA/assets/164886043/beb41661-3eb9-4e5a-b6c7-224d1d04a838)

### Versions and configuration

0.G 

### Additional context

If you take the item out of the bag in front of the NPC, he will get angry

**Comment by RenechCDDA** [comment]
The bug is subtly different on experimental: While it IS stealing, the issue is that you are not WARNED that it is stealing. The stealing still occurs, and you are set as the new owner.
