### ISSUE TITLE
Regenerating zombie and miracle lurker rebalance

### ISSUE THREAD

**Issue by LucioMagno** [CleverRaven/Cataclysm-DDA#72622]
### Is your feature request related to a problem? Please describe.

Regen. zombies and miracle lurkers both regen health much faster than other zombies. Yet they take way too long to get back up.

### Solution you would like.

Have them come back up 5 to 10 minutes after being downed to make them more of a threat that needs to be assessed rapidly.

### Describe alternatives you have considered.

Having them come back up after 1 minute would be a bit insane, maybe reserve this behaviour for a future evolution of these zombies?

**Comment by Daved27hundred** [comment]
As the person who made the regenerating zombies I LOVE this idea. I could make them turn into a separate monster, a pile of goop that can't move around which needs to be killed or else the thing rises again. Kinda like those weird fleshy enemies from TBOI.
