### ISSUE TITLE
The new "drying_rate" test is flaky

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#72631]
### Describe the bug

#72406 introduced a new test case. This test appears to occasionally randomly fail.
Here are several examples where it failed:
- https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8431687780/job/23089522544?pr=72594
- https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8431687764/job/23089516680?pr=72594
- https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8430984481/job/23087686666?pr=72629
- https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8429776423/job/23085121555
- https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/8430994395/job/23087712960?pr=72626

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

We should:
- Either fix the bug (if the failing test indicates a bug)
- Or fix the test to not fail randomly
- Or remove/disable the test

### Versions and configuration

N/A

### Additional context

Ping @Venera3

**Comment by Venera3** [comment]
Noticed, I'll put up a fix later today.
