### ISSUE TITLE
mutiple crafting recipe selection for npc and player, status of showing what is missing for npc to initiate it task,  showing reason why the npc completing the task so quickly, or why the npc is going somewhere then stop and keep standing there doing nothing after assigning to work at this camp

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#72632]
### Is your feature request related to a problem? Please describe.

1. mutiple crafting recipe selection for npc and player: painstakingly have to go out and go in the crafting menu multiple time to let the npc craft multiple items that you want it to craft.

2. status of showing what is missing for npc to initiate it task : the log just show that the npc is missing some item but i don't what is it missing, this should also show what item is suitable for that job or what item qualities is suitable for that job.

3. showing reason why the npc completing the task so quickly: the npc would just say the task is complete after you assigning it task.

4.   why the npc is going somewhere then stop and keep standing there doing nothing after assigning to work at this camp: 

### Solution you would like.

- [ ]  the ability to select multiple crafting recipe with batch and having all the information like total hour total calories and other information stuff

- [ ] showing what the npc need to initiate the task , this should also show what item is suitable for that job or what item qualities is suitable for that job.

- [ ]  the npc tell you why the task been complete so quickly and what are the problem

- [ ]  showing faction work status to each npc relating to their job priorities and what are they currently doing, what are they missing to do that, and something along those line
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/30c6060b-777f-48ed-95a8-da4abffda4e0)

**Comment by anothersimulacrum** [comment]
These sound like 4 separate issues. You should make a separate issue for each one.

**Comment by blablase** [comment]
> These sound like 4 separate issues. You should make a separate issue for each one.

okay then :~
