### ISSUE TITLE
Map Generation is kinda.... Bugged?

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#72630]
### Describe the bug

Seems like most massive PoI have been squished near spawn points, in like 1 to 2 chunks near one after another, meanwhile cities and other stuffs are getting farther and farther than one another the farther you are from spawn point, to the point that, the whole chunk is nothing but forests, some trails here and there and very rarely, an actual city despite having 4 default city spacing, meanwhile, Labs, Mil Outposts, Mil Heli pads and other small PoIs are spawning in the middle of a forest far from a road access.

### Attach save file

N/A

### Steps to reproduce

1. Create a new map
2. Create a new character
3. Debug in everything to see surroundings
4. Teleport 1 chunk at a time in a single directions or around the spawn point
5. Teleport farther and farther

### Expected behavior

Huge chunk of forest covering 90% of a map chunk shouldnt be happening and cities should still be spawning here and there instead of a 5% chance of it spawning, PoIs should have road access and all

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: 8fc7e97 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

https://github.com/CleverRaven/Cataclysm-DDA/assets/95905384/66a4cdbd-f673-4ea4-8626-b27fdffbb145

**Comment by Kywi001** [comment]
Renech told me that it was normal, and if I wanna modify it, Im gonna have to make a personal mod for the game balance

**Comment by Procyonae** [comment]
The lacking road access on low urbanity/high forestity overmaps is what should be a fixable bug if you want to reopen specifically for that but ye the rest was intentionally added in #69912
