### ISSUE TITLE
Ferals don't climb over fences

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#72649]
### Describe the bug

Should they climb over fences? They climb ladders no problem - why not hop the fence? 

Please find save attached. There is no other path so the feral is trapped. It seems they should climb the fence or break the window to attack the player. 

### Attach save file
[West Milwaukee-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14796397/West.Milwaukee-trimmed.tar.gz)

### Steps to reproduce

Load save, observe nearby feral.

### Expected behavior

Feral should hop the fence or break the window to get at the player.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/19167795/7dbac0e6-023b-48f9-9bfd-f071a5f1570d)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-03-27-0151 08a7eee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks]
]

**Comment by PGR-14** [comment]
They probably should, but they don't have that ability, currently the feral is deciding to whack the fence with a pipe.
