### ISSUE TITLE
Melee weapon attack move cost algorithm based on simple physical modeling.

### ISSUE THREAD

**Issue by wwkk222208** [CleverRaven/Cataclysm-DDA#72648]
### Is your feature request related to a problem? Please describe.

In the current game, using a dagger or simply fighting with bare hands is the inevitable last choice for players who specialize in melee weapon. Their attack speed is very fast and they only consume very little stamina. Commonly seen professional cold weapons in the real world, such as long swords and war hammers, have become a worse choice because of their long attack intervals and the consumption of a lot of stamina.
I reviewed the relevant code and found that the reason for this phenomenon is that the melee weapon attack move cost algorithm is not based on a physical model. Therefore, I hope to improve it.

### Solution you would like.
Physical modeling of stab weapon is based on the following assumptions. 
1.The force F applied by the character arm and weapon is conserved. 
2.The character's attack is regarded as move arm and weapon to a specific distance s.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92137695/aad33ba0-ca10-4601-b30f-ff611500b3f9)

Physical modeling of cut and stun  weapon is based on the following assumptions. 
1.The character's arm and weapon are treated as a rigid body as a whole. L0 is the distance between the hand and the rotation center.
2.The weapon is a homogeneous stick with a density of ρ and the cross-sectional area S is negligible. Its length is L.
3.The character holds the bottom of the weapon.
4.The moment of force τ applied by the character to the rigid body is conserved. 
5.The character's attack is regarded as rotating the rigid body to a specific angle θ.
6.The weaponis perpendicular to the line connecting the hand and the rotation center.
The calculation process is as follows. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92137695/8380e5d1-79f0-4b5b-a45b-c65de244b169)

α is angular acceleration. I is rotary inertia. c1 and c2 are constants to be determined. c0 is the base attack move.

Now consider the extreme case, first when the "balance" is extreme.
The weapon is not a homogeneous stick any more, it becomes a ponit at the position of hand.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92137695/dda01873-ce0c-40fc-a77b-dcf35bd2e319)
Then consider the case when the "unbalance" is extreme
The weapon becomes a point at the other end.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92137695/664fee57-52b3-499e-855b-d7213688815b)

Therefore, how unbalanced a weapon is can be quantified. 

It is necessary to adjust the coefficient that the mass needs to be multiplied by according to the label of the weapon category.
### Describe alternatives you have considered.

Actually, the above assumptions are difficult to meet in real scenarios, so this model cannot fully and truly reflect the attack process, but it can determine that the attack duration is related to the **0.5th power of the weight** of the weapon rather than the first power in the current game. Perhaps these effects can be summarized by a general attack speed correction factor, but I am not sure whether it is necessary to introduce it.

### Additional context

To develop test procedures to ascertain the effect of this modification on the game's balance.

**Comment by Zireael07** [comment]
Why open only to close immediately as not planned?

**Comment by wwkk222208** [comment]
LOL...I found some errors in the previous calculation formula, so I temporarily closed it. But it's back now.

**Comment by Zireael07** [comment]
The only thing such "temporary" closing does is make noise in people's feeds. Not an advisable thing to do

**Comment by wwkk222208** [comment]
I feel sorry about that.

**Comment by I-am-Erk** [comment]
Don't worry too much about it. I'd suggest just setting it to draft until you're ready for merge with something this big

**Comment by LyranRenegade** [comment]
curious to see some simplified math of this

**Comment by Zireael07** [comment]
Woops I'm guilty of thinking it's a PR, too :P

**Comment by I-am-Erk** [comment]
So, if I'm understanding your math correctly, this looks excellent but has some drawbacks we should consider, primarily with swinging weapons. AFAICT the stab algo looks fine
1. I believe you're using item length to presume the overall length of the lever arm. A lot of the time that will work, eg. a sword, but a lot of the time it doesn't at all, eg a quarterstaff.
2. many cut/blunt weapons in game are not exclusively used to swing, they may also stab. A sword or quarterstaff is a good example here.

This doesn't invalidate your work. It just means we should have some ways to adapt it, and I would suggest we use the json data in to-hit for that. We have two stats I'd like to visit: `balance` and `surface`.
- I suggest that you use these formulae to calculate the *slowest attack time* for a weapon, and then have the balance and surface modify that down. That's because we're going to use balance and surface to make assumptions about things like choking up on the handle to shorten the lever arm.
- There should probably be a minimum attack time as well, maybe 50% of the calculated? You'd need to look into what numbers you're getting to make a sanity check here, I'm just throwing out random guesses.
- Your ability to shorten attack time should be based on appropriate skill. Less skilled people are more likely to be making big wide strokes, more skilled people can adjust their position and swing to make quicker attacks without sacrificing anything.
- BALANCE should straight up just increase attack speed when it is better: we are making the assumption that a better balanced weapon has a grip somewhere inside its length. I'd suggest that CLUMSY balance should use the base calculated speed, and that speed cannot be adjusted by weapon skill. UNEVEN balance uses the base calculated speed, but each level of weapon skill and melee skill reduces the time to swing by 0.5%. NEUTRAL balance reduces the base calculated time by 10%, and an additional 1% for each level of weapon and melee skill. GOOD balance reduces the base calculated time by 15%, and an additional 1% for each level of weapon and melee skill.
- SURFACE may be really useful to us here, because it carries some info on how a weapon is swung. Regardless of damage type, if surface is listed as "POINT" we should use the first calculation as per stabbing weapons. If surface is listed as "LINE", use the second calculation for swinging weapons. *if it is listed as "ANY"* though, we get a cool new development. Good example is the quarterstaff which can be swung *or* thrust. This use case should cover a lot of our weapons with a widely variable grip, and should help a lot to mitigate the edge cases where your number is going to be high because it assumes the player is swinging their quarterstaff from one end. I am not quite sure how to resolve this and am open to suggestions. my first thought is that for weapons using ANY surface, we set their base attack time to be the average between the thrust and swing time equations. However another option would be to have the attack speed start closer to the SWING calculation and trend closer to the THRUST equation as the player skill increases (with balance bonuses added after).

**Comment by I-am-Erk** [comment]
Separate thought, but your point about length becoming a purely negative attribute is a good one. We may want to consider ways of boosting length by representing its ability to make attacks while keeping away from the enemy. If you're on discord, ping me.

**Comment by wwkk222208** [comment]
I really appreciate your suggestion. I feel very honored to be able to study this issue with you.

> I believe you're using item length to presume the overall length of the lever arm. A lot of the time that will work, eg. a sword, but a lot of the time it doesn't at all, eg a quarterstaff.
> many cut/blunt weapons in game are not exclusively used to swing, they may also stab. A sword or quarterstaff is a good example here.
You're correct, my modeling here is closest to weapons similar to swords, and doesn't give much consideration to other types of weapons. Its greatest significance is to reflect to what extent the length and weight affect the attack time. If we model the attack method of long stick weapons, we will get formulas with similar forms but different coefficients.

> I suggest that you use these formulae to calculate the slowest attack time for a weapon, and then have the balance and surface modify that down. That's because we're going to use balance and surface to make assumptions about things like choking up on the handle to shorten the lever arm.

> There should probably be a minimum attack time as well, maybe 50% of the calculated?[2](https://github.com/CleverRaven/Cataclysm-DDA/issues/72648#user-content-fn-2-893f181ab031e221635d082e22f5f403) You'd need to look into what numbers you're getting to make a sanity check here, I'm just throwing out random guesses.

I have to admit that I think for weapons with specific attack methods, this formula determines the upper limit of the attack interval rather than the lower limit. Because when the weapon mass is 0, the formula calculates the base attack interval. Is it possible to attack faster with a held weapon than with bare hands? Of course it is possible, such as by swinging a long sword by rotating the wrist. But this actually changes the attack method, and from a practical point of view, the power of the wrist cannot compare with the power of the entire upper limb. The power of the weapon when using this special technique should be lower than normal. Yes, we now have Rapid Strike to simulate this technique.

> Your ability to shorten attack time should be based on appropriate skill. Less skilled people are more likely to be making big wide strokes, more skilled people can adjust their position and swing to make quicker attacks without sacrificing anything.

Very good suggestion, but for the reasons mentioned earlier in the text, I prefer that the skill level can be increased to reduce the penalty rather than to increase the speed.

> BALANCE should straight up just increase attack speed when it is better: we are making the assumption that a better balanced weapon has a grip somewhere inside its length. I'd suggest that CLUMSY balance should use the base calculated speed, and that speed cannot be adjusted by weapon skill. UNEVEN[3](https://github.com/CleverRaven/Cataclysm-DDA/issues/72648#user-content-fn-3-893f181ab031e221635d082e22f5f403) balance uses the base calculated speed, but each level of weapon skill and melee skill reduces the time to swing by 0.5%. NEUTRAL balance reduces the base calculated time by 10%, and an additional 1% for each level of weapon and melee skill. GOOD balance reduces the base calculated time by 15%, and an additional 1% for each level of weapon and melee skill.

In fact, the balance of a weapon can be roughly quantified. For example, an extremely balanced weapon can be considered to have its center of gravity near the handgrip position. Whether the handgrip position is at the end point or the middle point of the weapon represents two extremes respectively. When the hand is at the end point and the center of gravity is also at this point, the weapon is abstracted as a particle, at which time the influence of length disappears, and the formula degenerates into the form of the stab formula, and the moment of inertia is the smallest. When the hand is at the middle point, the influence of length on the moment of inertia reaches the maximum, but it is still smaller than the moment of inertia when the hand holds the end point of a homogeneous and slender weapon. When considering the extreme unbalance of the weapon, the hand holds one end of the weapon, but the mass of the weapon is concentrated at the other end (such as a hammer with a very heavy head), then its moment of inertia is directly determined by the distance from the center of gravity to the center of rotation. Therefore, when measuring balance, only one controllable and meaningful factor needs to be introduced. Of course, this factor can also be linked to the extent to which skills can affect the use of weapons. It's cool. But I am considering that it may need more testing due to the potential problem of numerical inflation.

> SURFACE may be really useful to us here, because it carries some info on how a weapon is swung. Regardless of damage type, if surface is listed as "POINT" we should use the first calculation as per stabbing weapons. If surface is listed as "LINE", use the second calculation for swinging weapons. if it is listed as "ANY"[4](https://github.com/CleverRaven/Cataclysm-DDA/issues/72648#user-content-fn-4-893f181ab031e221635d082e22f5f403) though, we get a cool new development. Good example is the quarterstaff which can be swung or thrust. This use case should cover a lot of our weapons with a widely variable grip, and should help a lot to mitigate the edge cases where your number is going to be high because it assumes the player is swinging their quarterstaff from one end. I am not quite sure how to resolve this and am open to suggestions. my first thought is that for weapons using ANY surface, we set their base attack time to be the average between the thrust and swing time equations. However another option would be to have the attack speed start closer to the SWING calculation and trend closer to the THRUST equation as the character skill increases (with balance bonuses added after).

Allowing a weapon to have both slashing and piercing functions at the same time is really cool. I really hope to add this feature to the next round of consideration.

> Edit to add, it occurs to me that if I'm following the math right, we might be able to use the "stab" calculated time as the fastest possible attack? I am not completely sure I'm correct on this but I think I am.

Not really. For these two models, they have different assumptions. The former assumes that the character provides a constant force, while the latter assumes that the character provides a constant torque. Although in some ideal cases, the latter formula will degenerate into the same form as the former, their coefficients are still different. Of course, since the stroke of the stabbing weapon is usually shorter, stabbing should be the fastest, which can be achieved by adjusting the parameters.

**Comment by wwkk222208** [comment]
I didn't use Discord before, but I would like to start an account.

**Comment by wwkk222208** [comment]
A term was missing in the previous formula, and now it has been corrected.

**Comment by wwkk222208** [comment]
Let's  consider the long stick-like weapons, such as the quarterstaff. If I didn't misunderstand, the quickest attack method of the quarterstaff is to hold one hand at the quarter to one-third of the weapon, and the other hand holds the end point. The former remains motionless, and the latter moves to drive the weapon to rotate for attack. Therefore, the modeling assumption is as follows.
1.The character's arm and weapon are treated as rigid bodies
2.The weapon is a homogeneous stick with a density of ρ and the cross-sectional area S is negligible. Its length is L.
3.The center of rotation is located at one-third of the weapon. 
4.The moment of force τ applied by the character to the rigid body is conserved.
5.The character's attack is regarded as rotating the rigid body to a specific angle θ.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92137695/679df102-1a6c-4f48-91af-04aee3563b28)

**Comment by wwkk222208** [comment]
If we consider a two-handed sword or axe, then we only need to double the moment of inertia and the rotational inertia of the arm on the basis of the one-handed sword model, and the result is as follows.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/92137695/b14e38f9-7276-4f8a-b3d4-38e013428fa1)

**Comment by wwkk222208** [comment]
Combined with the "Balance" factor, the above model should be applicable to classic weapons such as one-handed sword, one-handed axe / hammer, two-handed sword, two-handed axe / hammer, long stick, lance, dagger, etc.
