### ISSUE TITLE
Keyboard input problems on linux when using Wayland

### ISSUE THREAD

**Issue by pwalsh0** [CleverRaven/Cataclysm-DDA#72657]
### Describe the bug

For some reason keyboard inputs are broken when I use Wayland. If I switch back to X11 everything is fine. 

It looks like there is some confusion between KEY_UP and KEY_DOWN events, and the way this is interpreted by SDL. The problem persists both using the libSDL.so that comes with the game (auto-installed via catapult) - or by using the system version of libSDL (ie manually delete the games version). 

Is the problem with Wayland itself, or with SDL?

### Attach save file

N/A

### Steps to reproduce

Try to navigate the menu using arrow keys, or other simple operation. Try up/down in a simple list - this makes the KEY_UP/DOWN confusion evident. 

### Expected behavior

Keyboard input should work as with X11

### Versions and configuration

OS: Linux
        OS Version:
    Game Version: cdda-experimental-2024-03-27-0151 https://github.com/CleverRaven/Cataclysm-DDA/commit/08a7eee6413e86e9d69db3e27dcb535e87436d74 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks]
    ]

**Comment by pwalsh0** [comment]
Using latest arch with gnome/kde and wayland. Get same problem with both kde or gnome - the problem seems to only happen when using wayland.

**Comment by pwalsh0** [comment]
After some experimentation it seems this is some intermittent startup problem. Alt-tabbing out and back seems to fix it.

**Comment by ZhilkinSerg** [comment]
That's probably better to be reported in SDL or Wayland repo to get fixed. I am pretty sure that is not an issue unique to CDDA.

**Comment by pwalsh0** [comment]
@lsadls do you also experience this issue? The game is unplayable with wayland for me still.

My above comment about alt-tab fixing it was wrong - or at least I cannot replicate the fix.
