### ISSUE TITLE
Moving from Transifex to Crowdin

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72651]
### Is your feature request related to a problem? Please describe.

Transifex, which is used for localization in the game, is starting to feel like a huge pain for localization. Here's why:

1. Slow Performance

Transifex falls behind a lot when it comes to performance. When you fill the search tab, refresh, or do whatever makes the strings load, it takes seconds to load the strings, regardless of the device's performance. (Tested in my Galaxy S21 phone and a high-end PC with fast internet, still needs confirmation from others)

2. Unfriendly, Bad UX

The video below shows what I have to deal with everyday. Imagine that combined with 'seconds long loading'. At least the loading was short because there weren't much strings.

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/597350e1-363d-43a6-95b3-82bc483d1465

On top of that, Transifex doesn't really support ubiquitous search 'filter'.

- Searching for multiple texts like `text:katana, text:mild`, `text:katana,mild` or `text:"katana,mild"` doesn't work. It'll only look for the word 'katana' or 'katana,mild' as whole.
- `-text` doesn't work. You need a separate field that is named 'text_not_contains', which means you can't filter out specific developer notes in particular, since it doesn't have a `not_contains` variant.

Here are the other issues:
- Even the smallest change in the source string will un-translate the string, like swapping a letter to uppercase or adding a comma. What's worse is that some strings un-translate for no reason!
- Translation Memory keeps yelling at me over completely unrelated strings just because it matches a few words, and it would refuse to find something that is actually needed.
- There isn't even a feature that allows you to check strings that has been changed, other than sorting in `Source String Updated`, which isn't even perfect because it ignores search filter.

### Solution you would like.

Swapping from Transifex to Crowdin.

### Describe alternatives you have considered.

Pleading for Transifex employees to fix their stuffs.

### Additional context

Pros:
- Better UX. Crowdin allows you to see the location of files and raw files, which is very convenient when it comes to translating stuffs that needs context. Transifex, on the other hand, requires you to search for `occurrence` (file location), which is definitely slower than Crowdin's method.
(Left is Crowdin, Right is Transifex)
![무제427_20240327211048](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/08aa3140-888e-40b3-a1c2-7194279cd847)

- Officially supported in many devices, including phone. Crowdin even has it's own mobile app! And from what I've heard, Transifex *used* to have a client version, but it's nowhere to be seen now.

- Verified useful and being used by big companies, like Mojang's Minecraft and Valve's Counter-Strike 2 & Team Fortress 2, etc.

Cons:
- Transifex and Crowdin isn't compatible, so the entirety of translation memory or history wouldn't be accessible.
- Would require a lot of work setting up.
- Since Free version of Crowdin (maybe) wouldn't be able to hold all the stuffs CDDA has, it might require subscriptions. Depending on infrastructure that costs money in a volunteer project is very problematic. *by harakka*

**Comment by Uwuewsky** [comment]
I agree about performance, interface and search/filter. And on top of that weird behavior, like removing “extra” spaces from the pasted text. Some older issue mentioned that transifex forces the wrong number of plural forms.

The big con of crowdin is that when loading from a .po file, new translations appear as options for the current translation without replacing them. I had to manually set them to a higher priority. Maybe I missed a checkbox somewhere, but I'm not sure.

**Comment by sadenar** [comment]
I don't think it would impact me personally overly much, but in my mind the loss of translation history would be a large drawback that would disproportionally hit the localization with a significant amount translated (40>,<70%) but not much people starting with effectively blank slates or 95-99% finished translation project that are basically only keeping up with new PR additions.

**Comment by CansecoGPC** [comment]
What about Weblate as an alternative? It's open source and can be self hosted.
If hosting is a problem, projects like Fedora offer hosting for open source projects too.

**Comment by Cenness** [comment]
> Crowdin is free for open-source projects, so feel free to submit the [Open-source project setup request form](https://crowdin.com/page/open-source-project-setup-request) 🙂

>Before submitting this form, please ensure that your project meets the following criteria:
...
> You do not have any commercial products related to the open-source project you are requesting a license for.

cdda has non-free steam version. No idea if it counts as a commercial product.

**Comment by andrii-bodnar** [comment]
> > Crowdin is free for open-source projects, so feel free to submit the [Open-source project setup request form](https://crowdin.com/page/open-source-project-setup-request) 🙂
> 
> > Before submitting this form, please ensure that your project meets the following criteria:
> > ...
> > You do not have any commercial products related to the open-source project you are requesting a license for.
> 
> cdda has non-free steam version. No idea if it counts as a commercial product.

Just discussed this with the team and can confirm that we can approve the open-source license for the CDDA project
