### ISSUE TITLE
Missing a lot of shortcuts.

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#72667]
### Describe the bug

On screens like the inventory and the grab item screens lots of shortcuts are missing

### Attach save file

N/A

### Steps to reproduce

Open game.
Load into save
Open inventory
Shortcuts missing

### Expected behavior

Older versions had the missing shortcuts

### Screenshots

![Screenshot_20240328-003307~2](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/2cc5c25a-3ffe-4b08-a185-ea4bb69d8ef1)

### Versions and configuration

Android, version:09526ad

### Additional context

Did not check other screens. My bad.

**Comment by Srcwya** [comment]
![Screenshot_20240330-231443~2.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/936e7a69-010d-4309-8473-a0a47d5e53d4)

![Screenshot_20240330-231450~2.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/9acce4f9-552c-45f4-851b-62171439db13)

![Screenshot_20240330-231455~2.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/5e773dfd-286a-4533-8897-cf1874ea4929)

**Comment by Srcwya** [comment]
Some menus with this issue

**Comment by Srcwya** [comment]
Some menus with this issue

**Comment by tmqCypher** [comment]
I can confirm this. Haven't done any thorough testing, but it seems to happen most often when starting a new run
