### ISSUE TITLE
Bronze recipe missing

### ISSUE THREAD

**Issue by erikmac1** [CleverRaven/Cataclysm-DDA#72668]
### Describe the bug

The main bronze recipe is missing so you can't advance in crafting. 

### Attach save file

N/A

### Steps to reproduce

go to latest Experimental version reach level two fabrication and look for bronze

### Expected behavior

That the recipe for bronze would show up

### Versions and configuration

Windows 10 version ccc0118 (tiles0 Build 2024-03-1742. Using default mods.

**Comment by Karol1223** [comment]
Not a bug. Bronze is locked behind a book recipe unless you're playing Innawoods. This is working as intended.

**Comment by Karol1223** [comment]
Not a bug. Bronze is locked behind a book recipe unless you're playing Innawoods. This is working as intended.

/invalid

**Comment by RenechCDDA** [comment]
As above.

**Comment by erikmac1** [comment]
> Not a bug. Bronze is locked behind a book recipe unless you're playing Innawoods. This is working as intended.
> 
> /invalid

Thank you. This is not mentioned in any online repository
