### ISSUE TITLE
Add a button to add missing required components into auto pickup manager automatically in craft menu

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#72688]
### Is your feature request related to a problem? Please describe.

I find it challenging to locate the required materials among a multitude of items when attempting to craft something without having the necessary raw materials on hand.

### Solution you would like.

I think it would be beneficial to add a button within the crafting menu that automatically picks up the corresponding materials, and allows specifying the required quantity

**Comment by Zireael07** [comment]
Please change the title to describe the contents of the issue

**Comment by IoIqq** [comment]
> Please change the title to describe the contents of the issue

I apologize, I am not particularly familiar with the format for submitting an issue. Is this correct?

**Comment by Brambor** [comment]
I don't understand. What is your setup? Usually, players have a base and all the items in reach (~5-tile radius). Is it not sufficient?

Anyway, the way I understand it, it could be a cool QoL feature expanding my idea (todo: add issue number when created)

**Comment by IoIqq** [comment]
> I don't understand. What is your setup? Usually, players have a base and all the items in reach (~5-tile radius). Is it not sufficient?
> 
> Or do you have the items at hand, but you want to travel somewhere before crafting?
> 
> Anyway, the way I understand it, it could be a cool QoL feature expanding my idea #72697.

I mean, when we need to craft a specific item, we have to go out to search for the corresponding raw materials. This can often be quite challenging because each spawn location contains a multitude of different items.Or sometimes they're right beneath our feet, yet we remain unaware.

**Comment by IoIqq** [comment]
> I don't understand. What is your setup? Usually, players have a base and all the items in reach (~5-tile radius). Is it not sufficient?
> 
> Or do you have the items at hand, but you want to travel somewhere before crafting?
> 
> Anyway, the way I understand it, it could be a cool QoL feature expanding my idea #72697.

I'm not referring to items within the base, but those outside of it. And I believe the auto pickup feature should have a quantity setting, to determine how many such items we need.
