### ISSUE TITLE
NPC didn't use available mattress to sleep

### ISSUE THREAD

**Issue by wormingdead** [CleverRaven/Cataclysm-DDA#72682]
### Describe the bug

After collecting and hauling two mattresses to the starting evac-shelter, I went to sleep in the dark, expecting my follower NPC to use the other mattress. However, on waking up, I saw that the NPC was sleeping on the brazier on the other side of the building.

### Attach save file

[Broadlands-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14796344/Broadlands-trimmed.tar.gz)

Save is a few in-game hours after waking up/seeing the NPC wake up.

### Steps to reproduce

1. Have the NPC following you.
2. Sleep on one of the two mattresses.
3. Wake up and see the NPC is sleeping, but not on the other mattress.

### Expected behavior

Expected the NPC to sleep on the nearby mattress.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5608858/1a46e0f8-22a8-4d2a-b401-258cdaa70c55)

### Versions and configuration

GAME REPORT:
- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 94b74cf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

Potentially this is an invalid bug-report because the world was created with the `no_npc_food` mod, which was later removed from `mods.json`. `no_npc_food` works by setting a single bool, so I figured either removing the mod would work, or nothing would change and the npc wouldn't sleep/eat. However, my understanding is that mod removal remains unsupported.

**Comment by PGR-14** [comment]
Can confirm, had a run where my npc decided to sleep on the table directly adjacent to the bed.
