### ISSUE TITLE
Experimental Linux version doesn't start because of missing dependencies

### ISSUE THREAD

**Issue by CansecoGPC** [CleverRaven/Cataclysm-DDA#72685]
### Describe the bug

When i try to run any experimental version of Linux on a fresh installed distro like Manjaro it doesn't start.

Trying to run from terminal gives an error about missing libs.

Doing ldd cataclysm-tiles reveals the following libs as not found:

libSDL2_mixer-2.0.so.0
libSDL2_ttf-2.0.so.0
libSDL2_image-2.0.so.0

And maybe others that depend on them like:

libopus.so.0
libopusfile.so.0

### Attach save file

N/A

### Steps to reproduce

Download any Linux version
Try to run on generic distro (Ubuntu, KDE Neon, Manjaro, etc)
It doesn't start

### Expected behavior

It should start.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 23.1.3; Codename: Vulcan; 
- Game Version: cdda-experimental-2024-03-29-0523 cba18c3 [64-bit]
- Graphics Version: Tiles
- Game Language: Idioma del sistema []
- Mods loaded: [
    Futuros Días Oscuros [dda],
    Necesidades PNJ Desactivadas [no_npc_food],
    Las Tormentas de Portal ignoran a los PNJs [personal_portal_storms],
    Ralentización del Crecimiento Fúngico [no_fungal_growth]
]

**Comment by harakka** [comment]
We don't compile the libs in statically, you need to install the sdl2 dependencies from  your distro's package management.

**Comment by CansecoGPC** [comment]
These libs are shared not static or else they would be included in the binary.
There's libSDL2-2.0.so.0 included already with the Linux versions but as i said it's missing more dependencies.
These should be included and not expect the user to know what needs to be installed without warning.
Or worse, inmutable distros like SteamOS were installing things from repos would be removed after the next update of the system.
