### ISSUE TITLE
Add a new type of dog (Lizard Dog)

### ISSUE THREAD

**Issue by theFeu** [CleverRaven/Cataclysm-DDA#72696]
### Is your feature request related to a problem? Please describe.

I played around with some generative AI to get a nice picture of my lizard mutant, and it gave me the gift of this little guy: 
![lizarddoggo](https://github.com/CleverRaven/Cataclysm-DDA/assets/22217062/1231ce95-0911-4221-bcfe-67be64f490bc)

Now I was wondering, if I could implement the lizard dog. Maybe as a spawn in the science lab - or just out in the wild.

The question is, would that be conform with the lore?

### Solution you would like.

I would love this little guy to be an adoptable dog that spawns in science labs.

### Describe alternatives you have considered.

Alternativly also as a random rare spawn out in the wild, like the other _different_ dogs.

**Comment by Procyonae** [comment]
What do you mean by lizard dog that's just a lizard

**Comment by theFeu** [comment]
I mean, yes, that's not wrong.  
But what if it behaves like a dog?

**Comment by kevingranade** [comment]
No thanks.
