### ISSUE TITLE
 Clean Water Batch Savings

### ISSUE THREAD

**Issue by Montimorency** [CleverRaven/Cataclysm-DDA#72706]
### Is your feature request related to a problem? Please describe.

It's always ground my gears that boiling water is so onerous in the game.

### Solution you would like.

Yes, functionally water as a drinking source was - thankfully - trivialized by allowing autoboil on a fire source (small containers of water, such as camping tins, should boil on their own just being adjacent to open fire sources, or even embers, but let's say that's already sufficiently simulated within the area of one tile). Water purification is also trivial with the common furniture object and a modest power supply. So the recipe has minimal intrinsic effect on gameplay. 

But it's not just a problem for pedantry's sake for the water boiling time to be wrong. Clean (boiling) water batch time can be the limiting factor for some recipes that take it as a component, where the water is actually supposed to be boiling rather than just purified. It's not common. Teas and soups arguably enjoy too-low batch savings, and black coffee should not take 10 minutes for the first unit, but they are not limited by the game's clean water batch savings at the moment (20/1 vs. 50-75/1 or 80/4). I actually couldn't find a clear example of any recipes using boiling water that are apparently limited by the craft times of "clean water", despite examining the majority of recipes with clean water as a component. But in principle, at least some recipes could (should?) be so limited, making a correction of the basic component's values non-frivolous.

For example, we could be linking the batch time of quicker dependent recipes, such as tea or coffee, to the batch boiling time of water. Improving the realism of batch boiling would thus be a necessary step.  

[Here ](https://www.plotwatt.com/best-way-boil-water/)is a quick and dirty source on water boiling times, and a chart based on eyeballing the bar graph. 

![BoilingWaterTime](https://github.com/CleverRaven/Cataclysm-DDA/assets/151707610/526af99b-eec8-41e2-a7b2-36fe53b7560d)
![Water Boil](https://github.com/CleverRaven/Cataclysm-DDA/assets/151707610/265eea30-9be8-4387-b7d9-4e8f59063e61)

To be sure, the nature of reality is that these times will vary widely based on energy source, the environment and type of container. A keg is a more efficient boiling chamber in time and energy than a tin can. Boiling a gallon in a keg is more efficient than boiling a cup in it. A covered pot boils faster than an open pot. An induction stove exchanges energy more efficiently than a gas stove. It's not worthwhile to try to quantify the energy output of an open fire and and compare that to the outputs of any number of electric tools in the game; an open fire itself can vary widely in energy output based on fuel material and quantity. It's not worthwhile to compare the thermal conductivity of a copper pot and an aluminum pot, and so on. 

So an abstract baseline is alwayss necessary.

But even for a single abstract value, I believe anyone can discern from personal experience alone that 5 minutes with 20%>1 are obscenely-low values, and cast an unwarranted shadow over the 99% of the game where the player isn't relying on tin cans or hobo stoves to cook.

I recommend reducing the recipe's time for the first cup to 4 minutes from 5, and thereafter applying a 50%>1 batch savings as a **low-stress compromise.** I would prefer larger reductions, but the suggested compromise is something that hardly requires deliberation.

That's 10 minutes for 4 cups (1 L), compared to 17 currently. 

### Describe alternatives you have considered.

Water is life.

### Additional context

Address any correlation with the autoboil process.

**Comment by GuardianDll** [comment]
At first, boiling is very linear process - if you boil twice as much water with the same amount of energy, you spend twice as much time. 
At second, we can't make granular boiling recipes that are aware of how much energy you spend, without making 50+ different recipes to boil water - ideally we need interchangeable recipes steps for this

**Comment by Montimorency** [comment]
We have to follow the empirical evidence. 5 minutes is a long time to boil the first cup, and 4 minutes is a long time to boil subsequent cups in the same system. A part of the reason why it is incomplete that "if you boil twice as much water with the same amount of energy, you spend twice as much time" is that adding more water takes advantage of more spare surface area in the heating chamber or whatever is being used. To be emphatic, **we know this to be the case**. The particular case of perfectly efficient energy transfer of a given amount of energy directly into a given amount of water is when we would find time as a constant function of water volume. If one doesn't like the source I offered, it's an easy thing to test for oneself. 

There is no doubt that, regardless of a lack of granularity in the recipe, the current times are much too high. The compromise was offered because a new crafting mechanic that would distinctly accommodate every possible heating vessel size and composition against every possible energy source is a lot of complexity on the backend for seemingly very little profit in gameplay terms. 

Isn't it better to moderately lower two values in a recipe and be done with it? To be clear, the new times would make game boiling no more efficient than microwave boiling in the embedded graph.

**Comment by GuardianDll** [comment]
\> the current times are much too high
Just the smallest from all the tools we model 

> New crafting mechanic that would distinctly accommodate every possible heating vessel size and composition against every possible energy source is a lot of complexity on the backend for seemingly very little profit in gameplay terms

No, it doesn't add a lot of complexity, it's just no one made it in a good way: read #62635 and following feature requests of how it should be implemented
We don't want to spend any more time and energy on dirty hacks, because they do not help

**Comment by Montimorency** [comment]
> No, it doesn't add a lot of complexity

Accurately modeling and distinguishing all energy sources against all vessels or containers in their physical characteristics with respect to all cooking (what you're getting at has implications for more than just water boiling) is a very complex undertaking, but the dev team should certainly follow through with it if they have a plan. It sounds like it will be a while. 

In the meantime, why would shrinking the "clean water" craft time from 5 at 20%>1 to 4 at 50%>1 be objectionable? I am not aware of modellable tools other than a small can over a small flame that would approximate the current times. We know it's wrong in real life, so what's the justification for the game model? The game model should be changed, as it has been countless times in other domains.
