### ISSUE TITLE
Companion with reach weapon

### ISSUE THREAD

**Issue by Darigar** [CleverRaven/Cataclysm-DDA#72709]
### Describe the bug

The companion is able to reach 2 tiles diagonally with Halberd, Naginata (and surely others weapons with reach.

### Attach save file

[test1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14810654/test1-trimmed.tar.gz)

### Steps to reproduce

1. equip companion with reach weapon.
2. let something come at him diagonally (3 diagonal tiles).
3. if he is strong enough, the target dies on after reaching the second tile. 

### Expected behavior

weapon reach expected to be the same as for the character.

### Screenshots

![Screenshot 2024-03-30 085026](https://github.com/CleverRaven/Cataclysm-DDA/assets/66732182/f523b2c4-fabc-406a-9284-c865ae01071d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3296 (23H2)
- Game Version: 2a21f9f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by SurFlurer** [comment]
See #65266
