### ISSUE TITLE
Start up errors

### ISSUE THREAD

**Issue by Glorbian** [CleverRaven/Cataclysm-DDA#72701]
### Describe the bug

 DEBUG    : installing reaper_advanced would make invalid vehicle: The installed heavy-duty frame already occupies the 'structure' location.

 FUNCTION : int vehicle::install_part(const point&, vehicle_part&&)
 FILE     : src/vehicle.cpp
 LINE     : 1467
 VERSION  : cdda-experimental-2024-03-29-1553 1e95d1e
 DEBUG    : installing reaper_advanced would make invalid vehicle: The installed heavy-duty frame already occupies the 'structure' location.

 FUNCTION : int vehicle::install_part(const point&, vehicle_part&&)
 FILE     : src/vehicle.cpp
 LINE     : 1467
 VERSION  : cdda-experimental-2024-03-29-1553 1e95d1e
 DEBUG    : installing plow would make invalid vehicle: The installed heavy-duty frame already occupies the 'structure' location.

 FUNCTION : int vehicle::install_part(const point&, vehicle_part&&)
 FILE     : src/vehicle.cpp
 LINE     : 1467
 VERSION  : cdda-experimental-2024-03-29-1553 1e95d1e
 DEBUG    : init_vehicles: 'Survivor Tractor' part 'plow'(33) can't be installed to -1,0

 FUNCTION : void vehicles::finalize_prototypes()
 FILE     : src/veh_type.cpp
 LINE     : 1591
 VERSION  : cdda-experimental-2024-03-29-1553 1e95d1e
 DEBUG    : warnings for type cowboy_hat_surv:
problem with pocket: invalid ammotype shotpaper

 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 2491
 VERSION  : cdda-experimental-2024-03-29-1553 1e95d1e

### Attach save file

Dog my save is 1 gb if you want it i'll give it.

### Steps to reproduce

Try to load the game using the almost all default mods
Error Messages
Game still loads but im sad :(

### Expected behavior

I expect it to load without errors, but I lack the skills to fix it myself :(

### Versions and configuration

Most recent I think.

**Comment by RenechCDDA** [comment]
Please fill out the versions and configuration listing as it instructs you. Use the debug menu to generate game report.
