### ISSUE TITLE
Running out of fuel with a Power Armor Generator Frame causes a segmentation fault.

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#72710]
### Describe the bug

If the Power Armor Generator Frame item runs out of fuel while the attached Combat Exoskeleton is active, the game immediately crashes with a segmentation fault.

### Attach save file

[MagicEvoAdvancedHardcore-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14810670/MagicEvoAdvancedHardcore-trimmed.tar.gz)

### Steps to reproduce

1. Load the save file. When you load into the game, you will be at 5/10000 remaining Diesel in your Power Armor Generator Frame, and only your Environmental Combat Helmet is engaged. Since this item appears to have trivial fuel usage, it won't immediately drain your generator fuel.
2. Take any number of arbitrary actions, provided the Power Armor Generator Frame is not emptied by them. Note that the game is stable under these circumstances.
3. Press "a", "Left Arrow", "Left Arrow", and then "Enter" to engage your Combat Exoskeleton. You will have five or fewer turns of remaining fuel when it is engaged.
4. Take any arbitrary actions that add up to 500 moves or more, such as walking five spaces in any direction. The game will reliably crash with a segfault as soon as fuel runs out.

### Expected behavior

I expect for the pieces connected to the frame to disengage and refuse to turn back on until fuel is provided, and for the game to not crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: cdda-experimental-2024-03-21-0047 2c345a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14810740/crash.log)

**Comment by NetSysFire** [comment]
Do not close bug reports for random drama that happened. This is considered quite unproductive.

**Comment by jake1203n** [comment]
I'm sorry, but I am not interested in being productive. I have decided that I not longer wish to participate in the communities surrounding Cataclysm or its development. Please do not re-open my bug reports or further reprimand me. My personal contributions here are done. You are welcome to copy the text and make a new issue that doesn't involve me, but leave me out of it.
