### ISSUE TITLE
NPC somehow managed to turn disassembly progress negative.

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#72715]
### Describe the bug

I assigned an NPC to disassemble 100 lumps of steel via a zone and a C menu. Everything was fine at first - the progress was slowly increasing, but then somehow the item became **minus** 21474% complete.

### Attach save file

[main-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14811589/main-trimmed.tar.gz)

### Steps to reproduce

I don't know if this is reproducible. Possibly connected: NPC sleeping, me sleeping, reality bubble load/unload

### Expected behavior

Disassembly progress should not become negative

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/52621858/7c89e9d9-8065-49e8-8936-63c67f0b23f1)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: f0eb92d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by PatrikLundell** [comment]
Duplicate of #72250 (and the stale-bot killed #69554).

**Comment by hexagonrecursion** [comment]
Opps. Thanks!
