### ISSUE TITLE
Power Armor Generator Frames cannot be refueled from tanks attached to vehicles

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#72713]
### Describe the bug

I am attempting to create infrastructure to provide fuel for a combat exoskeleton that I can carry on my vehicle. To effect this, I have attached a 60L tank to a motorcycle and filled it with diesel fuel, with the intent of using it as a fueling depot for my power armor generator frame. 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/a8b7fc79-c53a-45e9-ae05-3924d13920e5)

However, while the tank is attached to the vehicle, I am not allowed to use it to refill my power armor generator frame in any way. Attempting to (r)eload the frame gives this error message.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/5f36fba2-7958-4965-96ed-120534094a23)

Attempting to (e)xamine the vehicle and then (s)iphon the gas into the power armor generator frame with a rubber hose in my inventory results in this message, if I try to Pour it into a Container. 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/23a3fc0c-104a-4403-83a3-a87238cbbb2a)

If I try to "Fill Available Tank", it just says: "Never mind."

However, if I fully detach the 60L tank from the vehicle, then (r)eload the power armor generator frame, I am able to reload my power armor generator frame without issue. Likewise, if I have a Steel Jerrycan, I can (e)xamine the vehicle, then (s)iphon the fuel into the jerrycan, *then* I can {r)eload the power armor generator frame with it. 

### Attach save file

[MagicEvoAdvancedHardcore-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14810921/MagicEvoAdvancedHardcore-trimmed.tar.gz)

### Steps to reproduce

1. Press 'r' and select your power armor generator frame to reload it from the adjacent 60L tank.
2. Note that the attempt fails.
3. Press 'e', "Left Arrow", "e" to examine the vehicle. Press "s" to siphon gas from it.
4. Note that the only valid container is your steel jerrycan. If you throw (y) the container away from you, you will have no valid container.
5. Siphon the gas into the steel jerrycan. Notice that you are allowed to do so.
6. (r)eload your power armor generator frame again. Note that you are allowed to refill it from the steel jerrycan.
7. Reload the game. Use your adjustable wrench to remove the 60L tank from the motorcycle to your left. You may have to kill some zombies. 
8. (r)eload your generator frame. Note that you are able to refill it directly from the 60l tank now without the need for an intermediary container, now that it isn't attached to a vehicle.

### Expected behavior

I expect to be able to fill my power armor generator frame from a container that is attached to a vehicle, if not natively, then certainly if I have a rubber hose in my inventory.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: cdda-experimental-2024-03-21-0047 2c345a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by jake1203n** [comment]
Please copy the text and create a new issue if you'd like this issue to be re-raised. I do not want to be involved in any way.
