### ISSUE TITLE
Select multiple containers for one-click emptying

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#72721]
### Is your feature request related to a problem? Please describe.

When I encounter numerous bullet boxes at the police station, I am forced to repeatedly use the 'Empty' ('U') key to take out ammo.

### Solution you would like.

When using the 'U' key to select container emptying, it is possible to choose to empty an entire category of items by pressing the 't' key

**Comment by Maleclypse** [comment]
Also desired would be a 'gather all like this'.  So if I've hauled all the loot in a room into a couple of tiles I'd like to be able to select one item and pull every copy of it  in reach into my inventory or tile I'm standing on.  Similar to sorting but without an npc.

**Comment by IoIqq** [comment]
> Also desired would be a 'gather all like this'.  So if I've hauled all the loot in a room into a couple of tiles I'd like to be able to select one item and pull every copy of it  in reach into my inventory or tile I'm standing on.  Similar to sorting but for one item specifically.

yeah，it cool

**Comment by IoIqq** [comment]
it important

**Comment by IoIqq** [comment]
> Also desired would be a 'gather all like this'. So if I've hauled all the loot in a room into a couple of tiles I'd like to be able to select one item and pull every copy of it in reach into my inventory or tile I'm standing on. Similar to sorting but for one item specifically.

are there anyone work in this issue？
