### ISSUE TITLE
Ability to blacklist/whitelist crafting recipes and crafting recipe categories

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#72736]
### Is your feature request related to a problem? Please describe.

It would be neat to have the ability to blacklist/whitelist certain recipes and/or recipe categories. I imagine it would be useful for total conversion mods. For example, in a wild west-era total conversion mod that changes the setting to be of that era, i would like to hide crafting recipes that is rather anachronistic for it to appear.

### Solution you would like.

add the ability to blacklist/whitelist certain recipes and/or recipe categories. 

### Describe alternatives you have considered.

not doing so

**Comment by Standing-Storm** [comment]
I'm tinkering with a sword and sorcery metamod (requires Xedra Evolved, Megafauna, and Innawood) I'd like to eventually get into the repo, and something like this would be very useful for that.
