### ISSUE TITLE
``monsters`` GitHub label doesn't get applied when monsters are being touched directly

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#72746]
### Describe the bug

As in the title - the label doesn't get automatically assigned when monster JSON is being touched. It does get applied occasionally for other things, though, such as editing monster factions.

### Attach save file

N/A

### Steps to reproduce

1. Look at any PR that touches only monster JSON files
2. No label
3. Cry

### Expected behavior

Touching monster JSON directly should apply the ``monsters`` label to the PR

### Versions and configuration

N/A

### Additional context

My attempts at solving this in #71933 brought no results

**Comment by Procyonae** [comment]
"Look at any PR that touches only monster JSON files" You got any example ones? '^^ I can't find any

**Comment by Karol1223** [comment]
> "Look at any PR that touches only monster JSON files" You got any example ones? '^^ I can't find any

#72700 #72534 #71752 #71741
