### ISSUE TITLE
caring npc and more reliable npc

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#72750]
### Is your feature request related to a problem? Please describe.

i want and npc that can do whatever a normal character can do to help itself or npc when in trouble

### Solution you would like.

 cooking assignment  that is automatically cook, thawed food when hungry or when have cooking scheduled with an amount of batch , ability to command them to bandage you as very poor and poor bandage don't heal much, automatically check on the sick one or the unconsciousness one either feed them or tell them to wake up to eat, bandage them and return to normal work schedule

**Comment by hexagonrecursion** [comment]
This is a gigantic request. Too big for one issue. It is easy to say "i want and npc that can do whatever a normal character can do to help itself or npc when in trouble", but this involves designing, implementing and testing a ton of new mechanics, user interface features and AI. I would recommend separating this into a number of issues each **detailing** a **specific** proposal - this makes it easier for people interested in making **specific** improvements to discuss them.

Regarding automatic cooking when hungry: at the moment the recommended workaround is the "disable NPC needs" mod - it is **enabled by default** for a reason.
