### ISSUE TITLE
[Imgui] Regression - Imgui popups do not cycle

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#72769]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/699e4c6f-4cb3-44d6-974a-e5fdff2b5c8b)
Nice buttons here, i surely can press `left` and jump right to "ignore" as previous interface allowed us, right? (no, i can't)

### Attach save file

N/A

### Steps to reproduce

Teleport in the center of the city, try to eat (or do anything that can be interrupted by the game for safety reasons), get a popup, try to cycle it

### Expected behavior

being able to jump to the rightmost button by pressing "left"

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Work in Progress Limb Stuff [limb_wip],
    Mind Over Matter [mindovermatter]
]

**Comment by hexagonrecursion** [comment]
/confirmed right/left navigate popup buttons, but **do not** wrap around

- OS: Linux
    - OS Version: <unknown>
- Game Version: f0eb92d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    bug [bug]
]

**Comment by katemonster33** [comment]
darn. i missed this in my most recent PR to fix the button selection using left/right keys. this will be a very small PR, ill combine it with the fix for #72770
