### ISSUE TITLE
Allow the player to switch character without a delay

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#72767]
### Is your feature request related to a problem? Please describe.

#65732 appears to conflate two concepts: _the character controlled by the player_ and _the leader of the faction_. Because of this conflation #65732 limits how often the player is allowed to swap characters to 90+ days.

Here is the dilemma:
* On the one hand when interacting with your own NPC followers, the character controlled by the player **does** appear to be the leader because the player tells everyone else what to do through them.
* On the other hand for the purposes of 99.8% of the rest of the game the character controlled by the player is **definitely not the leader** - if I am switching control to another character it is likely because I am about to do something risky and do not want to risk my best crafter. What leader would do the most dangerous job when having the option of delegating it?

### Solution you would like.

I want to be able to switch the character I control much more frequently than 90+ days. I want to be able to switch to my scavenger whenever I am about to head out for some action and I want to be able to switch back to my crafter whenever I want to craft something. I do not want to wait an arbitrary amount of time - not even 1 in-game day (waiting takes real life time too especially if I want my character to do something productive instead of wasting X in-game days doing nothing). I do not want to be forced to scavenge with my crafter (too valuable, few combat skills) or craft with my scavenger (few crafting skills and proficiencies). I do not want to role-play this swap as a change of faction leadership.

### Describe alternatives you have considered.

**Edit 2:** theoretically we could designate one member of the player's faction as the leader and only allow the player to give commands to his followers when they are controlling the leader, but I do not see what this would accomplish other than making the system that is already clunky and inconvenient even more so.

**Edit 3:** commentary on edit 2: if the player has _zero_ ability give orders to followers unless controlling the leader, this would cause many issues. For example: if the player wants to take a team of scavengers into town, the faction leader has to be the chief scavenger, but if the player _also_ wants to craft with NPC helpers (e.g. use NPC strength to install or remove heavy vehicle parts), then the leader _also_ has to be the chief crafter.

### Additional context

**Edit**: as far as I am concerned the character I control isn't telling my "followers" what to do - she is merely the character I am currently playing as. I - the player - control every member of the faction - sometimes directly, sometimes less directly (by giving them tasks).

**Comment by kevingranade** [comment]
Everything about this is intentional, the use case of swapping between characters based on your current task is explicitly a playstyle we do not want to encourage as it greatly erodes any tradeoffs present in your particular character's build, and it leads to treating NPCs as disposable as you illustrate with "if I am switching control to another character it is likely because I am about to do something risky and do not want to risk my best crafter. What leader would do the most dangerous job when having the option of delegating it?".

To answer the question, because the leader doesn't have the ability to compel their followers to embark on suicide missions, but is free to do so themselves.

**Comment by I-am-Erk** [comment]
Honestly, I think the biggest issue with it is just that it encourages way too much NPC micromanaging which is kinda unfun. As I noted in a previous issue, there's no reason we need to keep it to 90 days, but at-will will cause negative play consequences
