### ISSUE TITLE
Infrastructure support for terrain transformation due to destroyed ceilings.

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#72765]
### Is your feature request related to a problem? Please describe.

#72758 illustrates one case where a ceiling is destroyed, but "repair" mechanisms later undoes the damage by restoring the "missing" roof. Other cases are the collapsed office tower, weirdness when monsters bash up basements to temporarily open holes in the ground.
I believe these issues stem from the destruction of the "roof" level without removal of the SUPPORTS_ROOF flag of the terrain below (which prompts the "repair").

### Solution you would like.

Change of the JSON format for terrain whereby a "turns_into_when_ceiling_lost" field should indicate the terrain to transform into when something smashes up the tile or the tile above such that the ceiling (and the "roof" above) is destroyed. It would be preferable if this field was made mandatory if the "SUPPORTS_ROOF" flag is present.

### Describe alternatives you have considered.

An alternative would be the introduction of the new field and the removal of the "SUPPORTS_ROOF" flag, as the flag would be a redundant indication of the same thing.

Turning everything into t_dirt if their ceilings are smashed... That's essentially the (extremely unsatisfying) code only solution.

Moving the ceiling properties from the tile it's the top of to a property of the tile the roof above belongs to.

Having two different transformations, one for "graceful" destruction of the ceiling (such as construction removal of the roof above), and one "destructive" transformation for when both the ceiling and the tile itself gets bashed up by the damage. That's probably overkill.

### Additional context

Note that this change would involve a fair bit of work, as there's probably a need to define a lot of new ceiling less versions of existing tiles. Also note that mods are going to have to update their data in a similar fashion.

Also note that you should probably check (nuclear) explosions to see that they do the right thing when blasting open terrain below, once the support is present.

Another side effect of the introduction of a lot of ceiling less terrain is that there probably will be construction recipes for them, and the ceiling supporting version may well end up as the second stage in a construction process that creates the ceiling less version first (like log walls first go through a half log wall stage). Whether that's a problem or an advantage is probably a matter of taste.

Edit:
It seems the entry I'm looking for sort of exists in the form of the "bash" element "ter_set_bashed_from_above".
This is defined for "t_soil" and "t_rock" and looks like it's intended for various forms of digging rather than actual destruction from above. It seems the "bash" segment is associated with the "MINEABLE" flag.
In many cases the "ter_set" element of "bash" has the value of "t_null", which I would guess means it's supposed to be replaced by some kind of regional setting element.

**Comment by Procyonae** [comment]
Replacing the SUPPORTS_ROOF flag with metadata would be ideal so there's no need to have duped terrain definitions. In the terrain definition you could provide a default true or false and then mapgen could override it. The issue is there's no current support for saving terrain metadata so it would require changing the .map save format.

**Comment by PatrikLundell** [comment]
Well, the roof "metadata" already exists in the form of the presence of a roof, provided the code that adds roofs actually does so when adding the supporting terrain (using the current logic: future logic would instead imply the existence of a ceiling from the presence of a roof), rather than buried within the map::load call chain.

**Comment by Procyonae** [comment]
> rather than buried within the map::load call chain

https://github.com/CleverRaven/Cataclysm-DDA/blob/d2b51fdc645cf1a49bab6c06c06533737c7fd605/src/map.cpp#L7803-L7822

https://github.com/CleverRaven/Cataclysm-DDA/blob/d2b51fdc645cf1a49bab6c06c06533737c7fd605/src/map.cpp#L8243-L8253

https://github.com/CleverRaven/Cataclysm-DDA/blob/d2b51fdc645cf1a49bab6c06c06533737c7fd605/src/map.h#L1951-L1954

**Comment by PatrikLundell** [comment]
I've tried to call add_roofs in various ways without going via map::load, but all my attempts so far have blown up because the code considers the grid vector to have a size of 0.
