### ISSUE TITLE
Capoeira (And probably other kicking styles) brutalize footwear

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#72779]
### Describe the bug

Capoeira seems to damage anything worn on your feet sometimes, might be other kick styles too. Maybe its because the shoes are used as a weapon? But there are no shoes with 'will withstand punishment of combat' flag, and 'withstand a lot of abuse' flag does jack... or does it?

### Attach save file

N/A

### Steps to reproduce

1. Obtain MA with kicks
2. Kick stuff
3. Break your shoes
4. Cry because you have to keep repairing or replacing shoes

### Expected behavior

I expected the 'withstand a lot of abuse' flag to prevent the damage but it does not. Maybe it makes damage less frequent though, im not sure.

### Screenshots

![cataclysm-tiles_OHKD9kzMdK](https://github.com/CleverRaven/Cataclysm-DDA/assets/22750535/a2568085-2ffd-4111-b4b7-d6966afa3570)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3296 (23H2)
- Game Version: d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    My Sweet Cataclysm [my_sweet_cataclysm],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Classless magiclysm [Noclassmagic],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
This is working as intended. You use your footwear as a weapon, it's gonna going to get damaged. Testing gives around 1000 hits to break the combat boots, which is plenty. 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/5d03c330-98b9-4d75-8528-9b722693f52d)
