### ISSUE TITLE
Item repair use action rework

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72774]
### Is your feature request related to a problem? Please describe.

Looking at misc repair kit issues made me wonder if "grab ammo directly out of inventory" instead of the old reloading mechanic could work.

### Solution you would like.

Instead of having to load tailor's kit with thread, or misc repair kit with duct tape, etc, the player could use ammo directly out of their inventory, similar to how we can use washing kit without having to reload the kit with soap.

### Describe alternatives you have considered.

Suffer.

### Additional context

These are photoshopped concepts of how those would look/work.
![무제442_20240402012919](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/aa306965-298b-48b8-9cd4-be858c031866)
![무제438_20240402011422](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/1bffeb13-e8bf-44ab-94fe-148a1de2c821)

**Comment by IdleSol** [comment]
Additionally, I suggest increasing the radius for the repair system. So that it would not be necessary to stand closely.
