### ISSUE TITLE
what the feck?!

### ISSUE THREAD

**Issue by Casteele72** [CleverRaven/Cataclysm-DDA#72772]
### Describe the bug

I have read the compiling guide but it is clearly written for someone already familiar with compiling CDDA and does not need the guide. rewrite the guide as if you have never compiled even a hello world program ...
 notably, I am trying to compile on Debian, which does not seem to accept building a SDL+SOUND+FULL FRIGGIN' GUI (I.E. TILES BUILD), BUT WON'T BUILD ANYTHING LESS THEN  A FULL FRIGGING GUI AND SOUND VERSION! Trying to figure out how to build a NON-GUI NON-SOUND VERSION IS I KICK IN THE GROIN!  after being sliced open and left for dead!
Notable. if i do not "make ... TILES=1", compilation fails because it is not yet linked. huh? wait, what!? it cannot be linked yet, i have to compiled it so there's nothing that can be linked! so now what do I do?
also strongly consider a GUI make option instead og relying only on tiles, so there will be TILES+GUI VS NON-TILES+NON-GUI builds, and so on.

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Screenshots

n/a

### Versions and configuration

n/a

### Additional context

n/a

**Comment by RenechCDDA** [comment]
Rant post, not a bug.

**Comment by Casteele72** [comment]
NOT A RANT SO MUCH AS A REAL PROBLEM WHERE I CANNOT FIND A SOLUTION OR
RESOLUTION. WHAT ELSE DO YOU RECOMMEND I DO?
--
C. Mitchell
***@***.*** ***@***.***>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by andrei8l** [comment]
Try to improve your bug reports first. Some advice from quick google:
https://marker.io/blog/how-to-write-bug-report
https://linuxsilo.net/docs/smart-questions_en.html
If you can follow even a quarter of that, you'll likely get better responses
