### ISSUE TITLE
Error on selecting a bayonet

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72785]
### Describe the bug

Currently if you attempt to wield a bayonet you get an error message about a missing bottle suppressor mod definition.

### Attach save file

n/a

### Steps to reproduce

1. Spawn a bayonet (USCM, army, national guard) 
2. attempt to wield
3. observe error

### Expected behavior

there should be no error message

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56016372/34c4e15c-5ae7-4ff8-a6e9-6ee2d728f213)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by IdleSol** [comment]
In #72060, the soda bottle silencer has been removed.
https://cdda-guide.nornagon.net/item/bottle_suppressor?v=cdda-experimental-2024-03-18-1108

For knives that can be mounted as a bayonet on a weapon. This suppressor is listed in the blacklist:

https://github.com/CleverRaven/Cataclysm-DDA/blob/d2b51fdc645cf1a49bab6c06c06533737c7fd605/data/json/items/melee/swords_and_blades.json#L360
```
...
      "blacklist_mod": [
...
        "bottle_suppressor",
...
```
And also removed: `"id": "riv_suppressor",` But I don't see it on the blacklist, so it shouldn't cause a problem.
