### ISSUE TITLE
[MoM] Metabolic Hyperefficiency causes major lag spikes with higher intelligence

### ISSUE THREAD

**Issue by MoonlightKitty26** [CleverRaven/Cataclysm-DDA#72781]
### Describe the bug

At about 20 intelligence, actions like moving/eating/waiting start to lag noticeably, and the higher intelligence you have the nastier the lagging becomes. Because using the power also makes you too weary for 'stop concentration' and toggling the power off, the only way to turn it off is to fall asleep, which depending on how tired you are, can take forever due to the lagging. 

### Attach save file

[Everest-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14829096/Everest-trimmed.tar.gz)

### Steps to reproduce

1. Walk around, wait, eat/drink, etc. to understand game performance before power toggle
2. Toggle the "Metabolic Hyperefficiency" power (should be in favorites menu)
3. Repeat step 1's actions

### Expected behavior

I expected the lagging to not exist.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No Bionic Slots [no_cbm_slots],
    Mind Over Matter [mindovermatter],
    Mind Over Matter: <color_magenta>Remove Random Delay Before Learning New Powers</color> [mom_no_power_learn_delay],
    Mind Over Matter: <color_magenta>Remove Concentration Limit</color> [mom_infinite_concentration],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Mind Over Matter: <color_magenta>No Negative Nether Attunement Effects</color> [mom_no_negative_nether_attunement],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extended Freeform [Extended_freeform],
    Japanese Folklore [Jap_folklore]
]

**Comment by RenechCDDA** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/74aae7ef-ea37-4365-ae4b-025b36b02c53)

(First set of ingame hours: Your save, 2 intelligence. Second set: Your save, 25 intelligence.)

Unable to reproduce with in-repo mods

- OS: Windows
    - OS Version: Windows 10 (22H2)
- Game Version: 0.G-8389-g1b170f1cae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Standing-Storm** [comment]
#72773 should at least cause high levels of weariness to turn off your powers.

**Comment by Standing-Storm** [comment]
Well, I loaded up the save using in-repo mods and activated Metabolic Hyperefficiency. One step immediately dropped me to Extremely Weary, and:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/406978a4-bc78-444e-bf4c-4d832db6cf5a)

Also, the character was freezing to death for some reason.
- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 4808268 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    No name () [],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    No name () [],
    No name () [],
    No name () [],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No name () [],
    Mind Over Matter [mindovermatter],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    No name () [],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No name () [],
    No name () []
]

**Comment by RenechCDDA** [comment]
> Well, I loaded up the save using in-repo mods and activated Metabolic Hyperefficiency. One step immediately dropped me to Extremely Weary, and:

I updated to 4aef74851d802b60590642d14e09e0021ad58c1c which includes your new PR mentioned above and I'm still not able to reproduce on MSVC (have not tried other versions).

https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/d2dfba68-4d5e-4ef9-a54d-c48e3f670720

**Comment by RenechCDDA** [comment]
PEBKAC: Triage(me) forgot to follow the reproduction steps.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/df221bcd-6517-4771-9ef9-178708709b4c)

**Comment by Standing-Storm** [comment]
Out of curiosity, I loaded up the save again, debugged in Stones' Fortitude (an Earthshaper spell from Magiclysm that reduces your metabolism, among other things), and got this:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/f7144aa7-4c40-44e2-8b80-8c8d97879c40)

So, just extra-confirming the above.

**Comment by GuardianDll** [comment]
Probable reason: same as #72255; while the zero metabolism do not hang the game anymore, values close to zero still can cause a lot of slowdown due the loop Ren posted before.
Nota bene: should check what happens when enchantment falls below zero

**Comment by jake1203n** [comment]
Bumping this issue. I experienced this bug and being an 18 Int Snail Mutant with a Recycler CBM was enough to completely break my game/save file. I had to edit out the Recycler CBM to continue playing. It's bad. 

(Thanks to the discord server for helping me troubleshoot and esp @GuardianDll )

**Comment by RenechCDDA** [comment]
```diff --git a/src/consumption.cpp b/src/consumption.cpp
index 2796a2039f..70a9341a4c 100644
--- a/src/consumption.cpp
+++ b/src/consumption.cpp
@@ -715,7 +715,9 @@ float Character::metabolic_rate_base() const
 {
     static const std::string hunger_rate_string( "PLAYER_HUNGER_RATE" );
     float hunger_rate = get_option< float >( hunger_rate_string );
-    return enchantment_cache->modify_value( enchant_vals::mod::METABOLISM, hunger_rate );
+    const float final_hunger_rate = enchantment_cache->modify_value( enchant_vals::mod::METABOLISM,
+                                    hunger_rate );
+    return std::clamp( final_hunger_rate, 0.0f, float_max );
 }
 
 // TODO: Make this less chaotic to let NPC retroactive catch up work here
```

The basic issue is that Character::metabolic_rate_base() comes back negative so Character::weariness_level() gets stuck in the while loop constantly incrementing the `amount` higher and higher (because `threshold` is negative due to negative bmr) until it overflows to negative
