### ISSUE TITLE
Condoms should come in wrappers

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#72799]
### Describe the bug

Zombies frequently spawn with a lone condom in their inventory. For obscure reasons, the game often tries to sort a bunch of their inventory into it. Not only does this make no sense, it tends to generate error messages. Spawning condoms in sealed wrappers instead would prevent this issue.

### Attach save file

N/A

### Steps to reproduce

Kill zombies, look at their condoms full of stuff

### Expected behavior

Condoms should come in sealed wrappers, like they do in real life. This should not be the case for condoms found in the sewers, trash, etc.

Condoms in retail locations should also be boxed up, similar to how tampons are done.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: dd1adff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RedMisao** [comment]
This could be a very simple yet elegant and realistic solution for #71661

**Comment by fairyarmadillo** [comment]
I will add, and maybe this is a non sequitor, a condom is not really a good container for anything irl. Latex degrades rapidly when exposed to sunlight or many different common substances and they're very very thin so they tear easily.

Condoms generally come packed in lubricant made of glycerin and water, which seems like it would ruin pills and maybe damage electronics. Armed forces have anecdotally used them in places like Vietnam to keep mud out of gun barrels, but I am not at all sure it makes sense to be eating handfuls of granola out of one and then reusing it to hold hot coffee or keep a phone dry while wading through a river.

At the very least, it'd be a one-time thing. I can't imagine tying one closed and then untying it without tearing it.

**Comment by Brambor** [comment]
#73313 seals the condoms as requested.
