### ISSUE TITLE
endless generation of towels

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#72796]
### Describe the bug

towels are generated after using a car repair shop in the tile that has a towel hanger installed

### Attach save file

[DarkMagenta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14842888/DarkMagenta-trimmed.tar.gz)

### Steps to reproduce

1. load save
2. examine tile 1 rigth 1 up
3. get 1 towel
4. repeat step 2-3 several times

### Expected behavior

the towel should definitely not come out
maybe you should remove the towel hanger or go through an additional check and do nothing

### Screenshots

![Снимок экрана от 2024-04-02 22-36-43](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/22fb3e8e-ff16-4cc7-9f9e-1751d8f10817)

transport configuration if you do not use saving
![Снимок экрана от 2024-04-02 22-40-48](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/f212d7d9-7b85-4880-b9a1-0b8ab749b0e8)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: cdda-experimental-2024-04-02-0446 4aef748 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by Procyonae** [comment]
Don't panic!

**Comment by harakka** [comment]
Caused by #72570. Dunno how but apparently vp.avail_part_with_feature( "VEH_TOOLS" ) on towel_hanger returns something I didn't expect. If someone wants to figure out why and improve the check it's at https://github.com/harakka/Cataclysm-DDA/blob/master/src/vehicle_use.cpp#L2305
