### ISSUE TITLE
City Size restrictions for map specials

### ISSUE THREAD

**Issue by RanikOrtega** [CleverRaven/Cataclysm-DDA#72795]
### Is your feature request related to a problem? Please describe.

Currently map locations and specials can spawn at any size of city which leads to locations such as stadiums spawning even in tiny towns. 

### Solution you would like.

Map specials should have City size "ranges" that they can spawn in. This could keep small, medium and large city specials generating in their respective city size ranges. You wouldn't expect to see a hunting lodge in the middle of a metropolis nor would you expect to see a skyscraper next to a gas station in a one stop light town. 

EX: 
Stadium: Required City Size = 6-10
Apartment Building :  Required City Size = 5-10
Skyscraper :  Required City Size = 7-10
Hunting Lodge : Required City Size = 1-3
Diner : Required City Size = 1-10

### Describe alternatives you have considered.

Alternatively if a simpler method is wanted. Locations should have a Restriction or Qualifier to limit to city size "X or above"  

EX: 
Stadium: Required City Size = 6
Apartment Building :  Required City Size = 5
Skyscraper :  Required City Size = 7
Hunting Lodge : Required City Size = 1
Diner : Required City Size = 1

### Additional context
If realism and simulation is desired we may need to consider a more in depth system for certain map locations size ranges. You would expect to see Houses in a size 10 city. But at that point there should be more apartments or high density housing.
Perhaps it could be two different values: "Possible Range" and "Preferred Range".  With a configurable chance to "check again" and replace the special with something else if it's in the possible range but not the preferred range EX:

House:
Possible Range 1-10
Preferred Range 1-6
Chance to replace 50%

Apartment Building:
Possible Range 4-10
Preferred Range 5-10
Chance to replace 25%

**Comment by Procyonae** [comment]
`city_sizes` already exists for non city specials and allowing it to be used with city specials will be a big improvement and shouldn't difficult so I think that's worth doing first.

I like your suggested zones alot, we do already have zones to some extent with them split into houses, shops and parks but I've not really checked out the logic they use as to how realistic it is and how easily it can be expanded.

The outskirts/centre thing is probably doable as additional logic for that, the city places buildings as it places roads out from its centre but it knows its "size" from the start so you could probably split the "size" into thirds or something, which would have the nice side affect of a city spawning near a river/ocean to count the bank/shore still as centre.

It also might be nice if the outskirts didn't try to jam the buildings as tight to make them feel more like outskirts.

**Comment by RanikOrtega** [comment]
> Would it make more sense to have the availability be based on "local" density such that skyscrapers appear only in the central parts of large cities, while hunting lodges only appear at the very edge of a city (with a town only consisting of outskirts)? No more single houses at the center of a metropolis, but lots of them in the outskirts. My thought here is that you might be able to get more of a gradient from outskirts to center than you get with the current jumble. Obviously, it would require more logic to determine where city density zones are, but I think it might be worth it in the end.
> 
> It would differ from the suggestion in that it would say city zone rather than city size.
> 
> A side issue would be if there could be actual zones in cities (and possibly other environments), such as e.g. industrial or harbor ones that would have their own assortments of "stuff". Red light districts for strip clubs and sex shops (presumably with low end apartment buildings)?

I think `size_range` is the bare minimum for functionality that can help achieve a lot of the above changes. But then we'd need other issues for extra tags. 

City centers being the downtown high density area, rural outskirts and industrial zones are all great ideas but slightly out of this scope. 

I'd say we'd need two issues after this one.  One for "tags" attached to specials to determine what zone they should show up in and another for actually totally revamping the city generation.

So on city creation it would then go. "How big am I? what buildings can I even place? Then it would place the "City center" tagged buildings in the middle, even if that is only an apartment building or town hall for small cities vs apartment towers and skyscrapers for big cities. Then the city generation would go outward and go by zones or rings.

**Comment by Procyonae** [comment]
So after reading the code the existing "zones" thing only discriminates based on distance from the city centre using some normal distributions and so isn't easily expandable to actual zones but can definitely be used for skyscraper -> small buildings the further out you go with minimal changes.
