### ISSUE TITLE
Character died in sleep to their head being cold.

### ISSUE THREAD

**Issue by NafenX** [CleverRaven/Cataclysm-DDA#72798]
### Describe the bug

I'm playing an Innawood character for the first time and after waiting a very long time for my character to sleep (slow laptop) I came back to the game only to see that they had been slowly dying because their head was freezing.

I was sleeping next to a Pine lean-to on the pile of leaves, while wearing a blindfold. I don't know if any of these parts are relevant at all but I would expect to be warned/woken up if I was literally dying to cold. I dunno.

### Attach save file

Unfortunately I saved before sleeping and can't cancel the sleep, can't hit ESC etc.

### Steps to reproduce

1. Sleep
2. Wait for sleep to kill the character
3. Be killed with no warning or interruption/chance to save the character from death

### Expected behavior

I would expect a warning or interruption like what usually happens if you are doing an action and something potentially dangerous appears or makes noise. Or perhaps just wake up the character if they take damage/pain over a certain threshold?

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/28961736/3d1a30af-162d-409a-b8a0-9e49b2db2cfb)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/28961736/fd6ccae2-b900-4bd0-918c-c4b659f4dcd6)

### Versions and configuration

Game Version: cdda-experimental-2024-04-02-0446 4aef748 [64-bit]

**Comment by fairyarmadillo** [comment]
Not totally sure, but I believe this happens because of some code that causes injured limbs to be colder than they ought to be. The game doesn't properly adjust its shivering/wakeup code for this, and so you take damage even though you're supposed to wake up before you freeze to death.

The code that makes injured parts colder does a lot of nonsensical things, like making you take cold damage even when temperatures are fairly mild. It is an artifact of older design before the game had blood loss and stuff, and probably ought to be removed.

**Comment by AcidAntOnAMinefield** [comment]
I noticed something related to this, in that nowadays, sleeping doesn't regulate your temperature anymore as it used to. My characters keep getting "chilly" while sleeping, despite having 3 or 4 blankets, pillows and plushies in bed, whether they're fully healed or not. Unsure when this got changed (if ever, if so, why).

**Comment by NafenX** [comment]
This is one of the few situations where I would actually allow myself to save scum so if anybody knows a way I could edit my save so that my character would wake up instantly I'd appreciate it. This is also probably the last time I will choose "Save and Sleep" instead of just autosaving before doing the sleep :sweat_smile: When I load back into the character, they're already sleeping and I can't seem to find a way to cancel it.

But yeah I had noticed weirdness with sleeping and cold before, especially when watching series on YouTube, but I'd never witnessed somebody just dying in their sleep to it before!

**Comment by Kywi001** [comment]
> This is one of the few situations where I would actually allow myself to save scum so if anybody knows a way I could edit my save so that my character would wake up instantly I'd appreciate it. This is also probably the last time I will choose "Save and Sleep" instead of just autosaving before doing the sleep 😅 When I load back into the character, they're already sleeping and I can't seem to find a way to cancel it.

Go to your save file and go find this
head": { "id": "head", "hp_cur":
Change the hp_cur value to the same value of you hp max value

**Comment by NafenX** [comment]
> 
> Go to your save file and go find this head": { "id": "head", "hp_cur": Change the hp_cur value to the same value of you hp max value
> 
> This wont wake you up but you should not die


~~I keep looking in my files for the game and can't quite figure out which of all of these files is the save for my character.~~

I'm also wondering if this change will work, since in the autosave my character does have full health on their head and it's only because of the cold while sleeping that they start to lose health? hp_cur and hp_max are both 60 in the save, so I feel like I would need something else to jolt the character awake somehow. 

Pre-EDIT: I managed to make the character wake up immediately on loading the save by setting "fatigue" to 0 👍
