### ISSUE TITLE
Would it be possible to sort the list of Construction tasks in a way similar to Crafting?

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#7279]
I really like how the list of Construction possibilities continues to expand. One consequence of this, though is it has gotten hard to navigate the list. I would love to see a Construction screen like the crafting screen, with sub categories that can be navigated and help to sort out the options. It would also be awesome if the tasks that can be done float to the top like the available recipes do in Crafting.

**Comment by illi-kun** [comment]
Separate tabs (categories) were introduced in #8646, so this issue can be closed.
