### ISSUE TITLE
Could not convert string `<var>` to double - EoC regression

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#72806]
### Describe the bug

The EoC framework checking for elapsed time  since the last limb progress event leads to a new error message.
Specifically the snippet `{ "math": [ "time_since('limb_progress_timer', 'unit':'days') >= 1" ] }`

### Attach save file

N / A

### Steps to reproduce

1. Load a world with WIP Limb Stuff
2. Add 1200 Mutagen / Insect Primer
3. Mutate the Changing Eyes trait 
4. Add three hours of sleep (the trait fires every 2h)
5. Behold errorage

### Expected behavior

Things that worked to keep working.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/72006894/31e67db8-543b-4c59-a5e2-821f8de0bbfe)

### Versions and configuration

Windows, commit `f243a091b81eb6f41ef410630e337b36a9448ddb`, compiled using VS

### Additional context

The variable is set using EOC_LIMB_CHANGING_SETUP and when read to message reads `5,21295e+06` and doesn't shift with passage, so the writing is broken as well.

**Comment by GuardianDll** [comment]
Shouldn't you use` { "math": [ "time_since(limb_progress_timer) >= time('1 d')" ] }`

**Comment by Venera3** [comment]
Both are found in the codebase, and the former worked with no error before.

**Comment by andrei8l** [comment]
This is not an issue. GuardianDll is correct. You're trying to use a string as a number. It no worky that way

**Comment by andrei8l** [comment]
> The variable is set using EOC_LIMB_CHANGING_SETUP and when read to message reads 5,21295e+06 and doesn't shift with passage, so the writing is broken as well.

This is unrelated. It's an issue with variables saved in different locales. See, for example, #71635

**Comment by Venera3** [comment]
> This is not an issue. GuardianDll is correct. You're trying to use a string as a number. It no worky that way


| time_since(`v`)<br/>time_since('cataclysm')<br/>time_since('midnight')    |  ✅   |   ❌  | N/A<br/>(global)  | Convenience function that returns a numeric value (in turns) for the time period since time point stored in variable.<br/><br/>Special values:<br/>`cataclysm` - return time since start of cataclysm<br/>`midnight` - return time since midnight<br/>`noon` - when the ingame clock reads 12:00<br/><br/>Optional kwargs:<br/> `unit`: specify return unit. Assumes `turns` if unspecified or empty.<br/><br/>Returns -1 if the argument is an undefined variable<br/><br/>Example:<br/>`{ "math": [ "time_since(u_timer_caravan_RandEnc)", ">", "time('1 h')" ] }`<br/>`{ "math": [ "time_since('cataclysm', 'unit':'years') > 1" ] }`

Per the documentation, and again, this has worked before without errors. I can move stuff over to the other syntax, but this sort of silent breakage is the main problem with moving functional stuff out of code and into EoC logic.

**Comment by GuardianDll** [comment]
\> this has worked before without errors
It shouldn't have to work in the first place, non variable being read as variable was a bug, not feature, and changing it was a step to make it consistent - values in `''` are special values, where values without `''` are variables.

**Comment by andrei8l** [comment]
/invalid

The documentation you linked says the argument needs to be either a variable, or one of the special strings. You can think of it as an overload.

> I can move stuff over to the other syntax, but this sort of silent breakage is the main problem with moving functional stuff out of code and into EoC logic.

The functionality has not changed at all, you just seem to be confused about string (quoted) vs variable (not quoted). It's the same as in C so I would expect a C++ dev to get it.

To prove that it has not changed, load up [this release](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-01-24-0635) (the first one to include `tince_since()` and try this EOC:

```JSON
  {
    "type": "effect_on_condition",
    "id": "EOC_TEST_TIME_SINCE",
    "//": "Five progression dream steps steps",
    "effect": [ { "math": [ "_blorg", "=", "time_since('limb_progress_timer', 'unit':'days')" ] } ]
  },
```
It will show an error in that version just like in master.

**Comment by Venera3** [comment]
Again, I'm using a cookiecutter EOC logic that *worked* in #71387 and now both throws an error and doesn't increment the counter on current. "Fixing stuff for consistency" is fine, but do move in-repo stuff over instead of relying on it eventually breaking.
