### ISSUE TITLE
Hunting Lodge causes error when opening map

### ISSUE THREAD

**Issue by ashGlaw** [CleverRaven/Cataclysm-DDA#72814]
### Describe the bug

I receive a slowdown and an error message when I open the map near, or scroll the map over to hunting lodges from XE. I get error messages. I can keep playing, but the slowdown is extremely annoying

### Attach save file

[Fall City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14854904/Fall.City-trimmed.tar.gz)

### Steps to reproduce

Load the save and open the map. If it doesn't trigger, try moving up a z-level. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/58862150/331b44ae-54dc-4cca-afff-9d6f1c22bd3b)

### Expected behavior

I expected that the map would open without freezes or error messages, like it does when there's no hunting lodges around

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/58862150/d24d9596-cb19-45f0-9649-56cb511c6fff)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cdda-experimental-2024-03-31-0500 d2b51fdc64 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks]
]

**Comment by RenechCDDA** [comment]
Just like #71772 I am still unable to reproduce this.

**Comment by PatrikLundell** [comment]
Failed to reproduce it on my Windows installation.

**Comment by IdleSol** [comment]
Got a bunch of error messages when loading (stage: loading the save, it seems to be on the 2nd step and penultimate or last). In the game itself, there are no errors. (Open maps, go down z levels and open a map).
```
- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-04-0557 55f012c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks]
]
```


```
 DEBUG    : invalid overmap terrain id "dirt_road_3way_east"
 DEBUG    : invalid overmap terrain id "dirt_road_south"

 FUNCTION : int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&, bool) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 513
 VERSION  : cdda-experimental-2024-04-04-0557 55f012c
```

```
 DEBUG    : invalid effect_on_condition id "picked_rosebuds_fall"
 DEBUG    : invalid effect_on_condition id "godco_place_herb_garden"
 DEBUG    : invalid effect_on_condition id "godco_place_wall"
 DEBUG    : invalid effect_on_condition id "godco_place_warehouse"
 DEBUG    : invalid effect_on_condition id "godco_place_coop"
 DEBUG    : invalid effect_on_condition id "leaves2_fall_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_fall_timer_plant"
 DEBUG    : invalid effect_on_condition id "leaves2_winter_timer"
 DEBUG    : invalid effect_on_condition id "flowers_winter_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_spring_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_summer_timer"
 DEBUG    : invalid effect_on_condition id "leaves2_spring_summer_timer"
 DEBUG    : invalid effect_on_condition id "flowers_spring_summer_fall_timer"
 DEBUG    : invalid effect_on_condition id "leaves3_spring_summer_timer"
 DEBUG    : invalid effect_on_condition id "leaves_spring_summer_fall_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_winter_timer"
 DEBUG    : invalid effect_on_condition id "leaves3_fall_timer"
 DEBUG    : invalid effect_on_condition id "rosebuds_fall_timer_elfa"
 DEBUG    : invalid effect_on_condition id "leaves3_winter_timer"
 DEBUG    : invalid effect_on_condition id "leaves_winter_timer"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = effect_on_condition]
 FILE     : src/generic_factory.h
 LINE     : 482
 VERSION  : cdda-experimental-2024-04-04-0557 55f012c
```

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14864281/debug.log)

**Comment by IdleSol** [comment]
On this save:

``` DEBUG    : invalid overmap terrain id "524291"

 FUNCTION : const T& generic_factory<T>::obj(const int_id<T>&) const [with T = oter_t]
 FILE     : src/generic_factory.h
 LINE     : 467
 VERSION  : cdda-experimental-2024-04-04-0557 55f012c
```
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14864462/debug.log)

**Comment by IdleSol** [comment]
The reason is in the selected overmap tileset (MSXotto+).

**Steps to reproduce**
1. Default options, world and character
2. Find the hunting lodge and go to it
3. Open the map and press `PageUp`: level z = +1
4. No errors
5. Change the tileset: `Options` /  `Graphics` / `Tileset Options` / `Choose overmap tileset` = `MSXotto+`
6. Repeat step 3
7. Get an error

Or just look at the picture: no tile
![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/b11f174f-3603-4881-95b4-d5b46a3a9514)
