### ISSUE TITLE
PREVENT_DEATH based EOC doesn't work

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#72827]
### Describe the bug

I'm using a respawn mod that uses PREVENT_DEATH eoc type to respawn me, it doesn't work when falling to my death.

### Attach save file

[Reach the ocean-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14864397/Reach.the.ocean-trimmed.tar.gz)

### Steps to reproduce

load save and then jump down the broken skylight frame. See that the EOC doesn't trigger and you normally die.

### Expected behavior

I shouldn't die.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77662682/ca355196-cf34-4c35-ba68-9ff2d5551e4b)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 23.1.3; Codename: Vulcan; 
- Game Version: cdda-experimental-2024-03-31-0500 d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    <color_green>Respawn</color> [respawn],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Bionic Slots [cbm_slots],
    waterprof [skyisland_waterproof_containers],
    NPC Recruitment Options [recruitment_options]
]

### Additional context

mods (including the respawn mod) in the save:  [savemods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14864363/savemods.zip)

**Comment by RenechCDDA** [comment]
#72358

You need to use the `u_prevent_death` effect.
