### ISSUE TITLE
Imgui: erratic size changes of activity progess popup

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#72822]
### Describe the bug

The imgui activity progress popup changes size all the time, leaving visible artifacts in the background when it gets smaller.

### Attach save file

n/a

### Steps to reproduce

1. Turn on imgui
2. Start a longer activity (crafting, sleeping...)
3. Watch the popup change size

### Expected behavior

Don't change size at all, or at least keep it somewhat in check like the old ui does.

### Screenshots

![progress](https://github.com/CleverRaven/Cataclysm-DDA/assets/38702195/042c0777-0a3f-4687-91a1-4579b0300551)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 8b4c779 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by katemonster33** [comment]
Darn, caused by #72797 for sure, thought we could auto size the popup every frame and be done with it... Maybe there is an auto size option to only grow the popup. Otherwise we can make the popup only auto size its height

**Comment by mqrause** [comment]
There was some of that already going on before #72797, but just for the height, I think. I just put off reporting it for too long.

And it's actually not just crafting progress, it's affecting all activities. I guess the ideal solution would be to calculate a size at the beginning and then stick to that until the activity is finished/interrupted. But limiting it to growing only is an option, too. Although in the gif there's a moment of it becoming pretty big for no apparent reason.
