### ISSUE TITLE
Nodachi is not a valid Niten Ichi-Ryu weapon

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#72831]
### Describe the bug

It should be, niten_style doesnt include greatswords and the nodachi is one.
Easy to fix but I haven't figured out how to do prs yet so maybe somebody else wants to fix that.

### Attach save file

n/a

### Steps to reproduce

wield a nodachi with the niten ichi-ryu melee skill

### Expected behavior

yes

### Versions and configuration

win 7
e442936 (tiles)

**Comment by RenechCDDA** [comment]
Why should it be? The nodachi is a very heavy two-handed weapon, Niten requires a Katana or similar hand-and-a-half blade.

**Comment by pwalsh0** [comment]
[Niten Ichi-Ryu means 2-sword style - ](https://en.wikipedia.org/wiki/Niten_Ichi-ry%C5%AB)

**Comment by LyranRenegade** [comment]
hah, the more you know

**Comment by LyranRenegade** [comment]
my bad
