### ISSUE TITLE
(Aftershock) Wraitheon Regulator missing gun

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#72846]
### Describe the bug

Wraitheon Regulator is using the m4_carbine gun that was changed into modular_m4_carbine

### Attach save file

N/A

### Steps to reproduce

1. Spawn Wraitheon Regulator
2. Wait

### Expected behavior

It should be able to fire a weapon

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Lenovo; Model: Lenovo L58041; Release: 8.1.0; Incremental: 3.9.166_200309; 
- Game Version: cdda-experimental-2024-03-29-0523 cba18c3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Aftershock [aftershock],
    Modded Map Gen [MMG],
    Xedra Evolved [xedra_evolved],
    Armored Cosplay [armored_cosplay]
]

**Comment by Maleclypse** [comment]
Someone will need to jsonize the `MULTI_ROBOT` special attack which is currently hardcoded.

**Comment by Night-Pryanik** [comment]
Fixed by #75347.
