### ISSUE TITLE
ImGui Demo Screen. Center alignment of the window

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72844]
### Describe the bug

If you use a non-standard window size, you can get one like this:

![test 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/e0ae60de-6a71-43bc-8ee3-0d4729be804a)

### Attach save file

N/A

### Steps to reproduce

1. Default options
2. Enable ImGui
3. Settings / Options / Graphics / Graphical display options / fullscreen = no
4. Save changes, close the game and load again
5. Change the size of the window, to an arbitrary size
6. Settings / ImGui Demo Screen
7. Check the position relative to the window borders

### Expected behavior

N/A

### Versions and configuration

cdda-windows-tiles-x64-2024-04-05-0445

### Additional context

@katemonster33

**Comment by katemonster33** [comment]
yeah the code to show the Demo UI exists within the ImGui sources and has a hard-coded screen position. We could probably rewrite it to center itself. Or maybe just to fill the entire screen (would probably be best for small screens and Android)

**Comment by alef** [comment]
@katemonster33 done something similar to your suggestion in #75905
