### ISSUE TITLE
Pain. Incorrect display of characteristic penalty.

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72854]
### Describe the bug

In the character window (`@`), in the effects section (`c`), the penalties to characteristics depending on pain are incorrectly specified.

Most likely they just forgot about them when they introduced the changes #72687.

The gif shows the characteristics at 20, 30, and 60 pain.

### Attach save file

N/A

### Steps to reproduce

Create a character and set the pain value. Then compare the real characteristics with the specified penalties.

### Expected behavior

N/A

### Screenshots

![pain](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/7e2b87c4-b900-4c28-b19d-8e2f9a151514)

### Versions and configuration

cdda-windows-tiles-x64-2024-04-05-0445

**Comment by GuardianDll** [comment]
/confirmed, tho in the world i don't understand why it happens, since effect reads exactly same function that was edited

**Comment by IdleSol** [comment]
Maybe I'm going to say something stupid, but maybe it's about different types? float vs int

```
float penalty_mod = pain * 0.01f;
```
penalty_mod = float
```
ret.intelligence = enchantment_cache ...
```
ret.perception = float
```
ret.perception = std::max( ret.perception, 0 );
```
0 = int

**Comment by osuphobia** [comment]
I found out why this bug occurs.
When calling `Character::get_pain_penalty` in `Character::disp_info`, we are not calculating the displayed penalty with the stats _before_ penalties applied, but with the numbers _after_ the penalties applied.
So, with 50 pain and `intelligence 4 (8)`, `ppen.intelligence` is not `8*50*0.01 = 4`, but `4*50*0.01 = 2`.

Also, despite the doc and comment saying `// Also not make character has 0 stats`, the stats of character can still get lower than 1, I'll fix this also.
You can see that, with 100 pain, you got `intelligence 0 (8)`, and `ppen.intelligence` is now `0*100*0.01 = 0`.
