### ISSUE TITLE
Car quarter panels do not block light or line of sight

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#72860]
### Describe the bug

So I installed curtains on all the windows of my SUV yet light still gets in through the quarter panels as seen in the picture.

I tested it out on an armored car I spawned in and it does work correctly as soon as I close all the curtains it becomes completely dark. The heavy-duty board has an opaque tag on it where as the basic quarter panel does not, maybe that is the reason quarter panels don't block light or line of sight.

### Attach save file

[Kraemer.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14892223/Kraemer.zip)

### Steps to reproduce

Boot up the provided save or just spawn a vehicle in your game, add curtains, and then close them.

### Expected behavior

I would expect the quarter panels to block out the light and line of sight. Maybe they only block line of sight if you aren't in the driver seat so we don't have to put wing mirrors on every vehicle to be able to see what is beside us. 

### Screenshots

![Curtains Open](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/b0004c2b-d0a7-4ec1-a34f-3ea63b09a045)
![Curtains closed](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/2c09345a-c29a-455c-a99c-de9d24dcce07)
![Armored Car](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/169f4893-9c89-43b3-adf7-e7d193ecf072)

### Versions and configuration

cdda-windows-tiles-sounds-x64-msvc-2024-04-05-1254

**Comment by RenechCDDA** [comment]
They're not supposed to? From the description:
`A half-height metal wall. Keeps zombies outside the vehicle but allows people to see over it.`

**Comment by Fox-Ball** [comment]
> They're not supposed to? From the description: `A half-height metal wall. Keeps zombies outside the vehicle but allows people to see over it.`

Weird when I talked to Guardian he said that they were not suppose to be able to be seen through/let light in. Either way the quarter panel can't be vaulted/climbed over and it supports a vehicle roof on top of it. It is a solid object it makes no sense to be able to actively see through/let light through. It's not like it is a truck bed where you can sit in and see over it, at least not with the SUV. Maybe some sort of actual vehicle panel needs to be added, really when I think quarter panel I think of the piece above the tire, like a fender.

**Comment by fairyarmadillo** [comment]
Quarter panels are not full walls, they're like the hood of a car. Boards are full walls, like the side of a windowless van. Quarter panels can't be vaulted over because there isn't code in place to make vehicles climbable, because vehicle tiles are very weird in the code.

**Comment by Fox-Ball** [comment]
So basically that confirms what I said, some vehicles shouldn't be comprised of all quarter panels. You're better at explaining things than me. Any part that isn't a door/window that seperates the interior and exterior should be a board instead since that is a full wall and it blocks line of sight and light from getting through.

**Comment by fairyarmadillo** [comment]
Only if the car is taller than a person. A sedan or coupe should definitely be all quarter panels since you can see over those cars while standing up. An SUV should probably only have them in the front, with boards in the back.

**Comment by toweroglass** [comment]
quarter panels are necessary. otherwise you wouldn't be able to see over your dash.
