### ISSUE TITLE
Allow very tall characters to climb over split rail fences

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#72869]
### Is your feature request related to a problem? Please describe.

I was a little surprised when I found out very tall characters can't climb over split rail fences. Being fairly tall myself, I do not have difficulty climbing over/hopping small fences. Split rail fences are especially climbable due to the gaps between the planks. 

### Solution you would like.

I would like very tall characters to be able to climb over split rail fences. Initially, I thought a high move cost would be reasonable, but I think it should require a climbing prompt because it could be difficult to climb with your hands full or a heavy bag. 

### Describe alternatives you have considered.

Alternatively, split rail fences could be climbable for all characters. [Cedar fence direct](https://cedarfencedirect.com/blog/2021/06/03/have-your-split-rail-fence-and-your-privacy-too/) says split rail fences are typically 3ft tall, which is "an easy fence to climb over or squeeze through for most people". 

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/86f841ee-87de-4f33-b355-a7ebc239923c)
Figure 1. A wooden split rail fence.

**Comment by fairyarmadillo** [comment]
Everyone should be able to climb these.

**Comment by PatrikLundell** [comment]
If a giant isn't large enough to simply step over the fence, the only problem I see is the risk of being too heavy to climb it without is crumbling, and then it would be a matter of weight rather than height as such.
So yes, everyone should be able to get past those.
