### ISSUE TITLE
Couldn't create character for new world

### ISSUE THREAD

**Issue by Alzuule** [CleverRaven/Cataclysm-DDA#72865]
### Describe the bug

Created a new world and when I tried to initiate creating a character for it, I got an error message and was sent back to main menu.

### Attach save file

[worldoptions.json](https://github.com/CleverRaven/Cataclysm-DDA/files/14893382/worldoptions.json)
[mods.json](https://github.com/CleverRaven/Cataclysm-DDA/files/14893383/mods.json)

### Steps to reproduce

1. Create world ( as attached world )
2. Attempt to begin creating a character, or loading a character preset

### Expected behavior

Expected to be sent to the character creation screen and be able to create a character, which is what usually happens.

### Versions and configuration

OS: Windows
        OS Version: 10.0.22631.3296 (23H2)
    Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/28aa11c45e956a5f44a4215e06f1d41214f4ba7e [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Megafauna [megafauna],
    Tamable Wildlife [Tamable_Wildlife]
    ]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14893386/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14893387/debug.log)

**Comment by Maleclypse** [comment]
@I-am-Erk I’m away from computer until late tonight but the debug shows Fatigue errors

**Comment by Alzuule** [comment]
> @I-am-Erk I’m away from computer until late tonight but the debug shows Fatigue errors

Don't know what that means, is it a known issue or something triggered by a mistake on my end?

**Comment by I-am-Erk** [comment]
I thikn some of these mods are out-of-repo? You'd have to do a find-and-replace for FATIGUE in all caps and replace it with SLEEPINESS

**Comment by Alzuule** [comment]
Ahh okay, that makes sense. I'll have to see which ones are causing it.

**Comment by Maleclypse** [comment]
@I-am-Erk all of those are in repo mods.  I've checked individually with create a world pulled up.  Which suggests we've got a test coverage failure around some of our in repo mods potentially.

**Comment by Alzuule** [comment]
I uninstalled what I had and reinstalled with the current Experimental build this morning, and it seems to be the Megafauna mod thats at fault.

**Comment by I-am-Erk** [comment]
Oh, possibly something using Fatigue could have been merged while the sleepiness change was awaiting merge itself
