### ISSUE TITLE
Failed to place Liam's Cabin

### ISSUE THREAD

**Issue by Alzuule** [CleverRaven/Cataclysm-DDA#72864]
### Describe the bug

Started a new character on a world with Magiclysm and MoM, and upon finalizing the character I was told it failed to find a valid location for Liam's Cabin ( Scenario ). Upon using the Retry option, it successfully placed the cabin. 

Full mod list:   Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Megafauna [megafauna],
    Tamable Wildlife [Tamable_Wildlife]

### Attach save file

N/A

### Steps to reproduce

1. enable the mods listed in Description
2. Make a character ( I used Awakening Psion Profession ) choosing the Friends to the End scenario
3. Finalize

### Expected behavior

Placing the Cabin without issue.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3296 (23H2)
- Game Version: 28aa11c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Megafauna [megafauna],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PGR-14** [comment]
Nothing wrong here
