### ISSUE TITLE
Loot zones attached to vehicle cargo tiles disabling automatically

### ISSUE THREAD

**Issue by Delliejonut** [CleverRaven/Cataclysm-DDA#72870]
### Describe the bug

Sorting using Personal Unsorted zone into Default loot zone attached to vehicle cargo tile fails. Sorts one single item then all vehicle loot zones attached to the vehicle become disabled. Re-enabling vehicle loot zones does not fix.

### Attach save file

[TonkaLand-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14894763/TonkaLand-trimmed.tar.gz)

### Steps to reproduce

1. Make default loot zone attached to vehicle.
2. Make personal unsorted loot zone.
3. Attempt to sort using personal loot zones only.
4. Open Zone Manager, re-enable vehicle loot zones.
5. Repeat.

### Expected behavior

The objects I'm attempting to sort are vehicle parts, but it is repeatable with objects of any size or weight. Objects fit into the trunk space and I am able to carry them. It should work the same as any other loot sorting.

### Versions and configuration

2024-03-21-0047
I have deleted fungal creatures.
My mods-
![Active mods](https://github.com/CleverRaven/Cataclysm-DDA/assets/16458939/e08d7a1d-1ee5-487e-a3cf-fcd4653d354d)

**Comment by EternalLaughter** [comment]
Cannot reproduce.
All personal zones:
Car trunk - Loot Default
Pavement - Loot Unsorted

Shift-O Zone manager to sort personal zones only and all items on the pavement is moved to the trunk as expected.
![Screenshot from 2024-04-12 23-09-14](https://github.com/CleverRaven/Cataclysm-DDA/assets/50793323/249201dd-2fcd-4cd9-b7d9-3ac1b1f52b2b)

**Comment by DaimonTrilogy** [comment]
> Cannot reproduce. All personal zones: Car trunk - Loot Default Pavement - Loot Unsorted
> 
> Shift-O Zone manager to sort personal zones only and all items on the pavement is moved to the trunk as expected. ![Screenshot from 2024-04-12 23-09-14](https://private-user-images.githubusercontent.com/50793323/322138116-249201dd-2fcd-4cd9-b7d9-3ac1b1f52b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NjA1MjgsIm5iZiI6MTcxMjk2MDIyOCwicGF0aCI6Ii81MDc5MzMyMy8zMjIxMzgxMTYtMjQ5MjAxZGQtMmZjZC00Y2Q5LWI3ZDktM2FjMWIxZjUyYjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIyMTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MTI4YjY0ZTkwNzFlZWMzZTkwOTc4YzEzN2VkNTY2ZThhZGNjYzk0ZjEzZDNlYTUxMzYyODlhYTJmM2RkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ww7CWvAmVuY_wvuhIGy8JECG8fT2uU8QpQPZ8HaCFZM)

I have the very same issue.
You need to have a vehicle loot zone and a personal loot zone.
The vehicle loot zone disables when you have both zones and activate "sort personal zones only".

In the picture you only have personal loot zones, not vehicle loot zones.

**Comment by DaimonTrilogy** [comment]
Here are 3 pictures for easier understanding:
![cataclysm-tiles_cNd8pIUNwL](https://github.com/CleverRaven/Cataclysm-DDA/assets/69793827/a278e65e-d84d-47a3-afef-3109c846c10e)
![cataclysm-tiles_VVauU2ZeUw](https://github.com/CleverRaven/Cataclysm-DDA/assets/69793827/524c8b0b-dfc4-49b3-85f9-7066e3f15638)
![cataclysm-tiles_xgZO1OeZir](https://github.com/CleverRaven/Cataclysm-DDA/assets/69793827/3ac0dc3b-8a06-4e03-82fa-8856a4280984)

**Comment by EternalLaughter** [comment]
I'm sorry but i'm not sure what's going on from the pictures way too many zones.
As for the text you say "You need to have a vehicle loot zone and a personal loot zone."

So new test:
Car Trunk - Bound to cargo as Static Zone
Pavement under the character - Personal Loot Unsorted

Shift-O And sort out my loot (all zones) works and moves the loot to the trunk, since you are combing two zone types, personal and static this would be to my understanding the correct choice. Zones are unchanged\enabled after sort.

Shift-O And sort out my loot (Static) does nothing as i would expect, since the personal zone isn't counted, so no items to move into. Zones are unchanged\enabled after sort.

Now the last one...

Shift-O and sort out my loot (Personal) is very strange. It shouldn't work was my belief, as there's no other zone rule for it to interact with, as the loot in the car is static and bound not personan, but it actually moves one item to the trunk of the static zone, and then claims the job is done.
In addition it then disables the Personal Zone on the pavement for me, not the Static vehicle cargo, as you had as an issue with.

So there is something not quite right here, but would need better eyes to look at this.

**Comment by Delliejonut** [comment]
> Shift-O and sort out my loot (Personal) is very strange. It shouldn't work was my belief, as there's no other zone rule for it to interact with, as the loot in the car is static and bound not personan, but it actually moves one item to the trunk of the static zone, and then claims the job is done. In addition it then disables the Personal Zone on the pavement for me, not the Static vehicle cargo, as you had as an issue with.
> 
> So there is something not quite right here, but would need better eyes to look at this.

This is exactly what I was experiencing, and why I made the ticket. Thank you for attempting to replicate!

**Comment by DaimonTrilogy** [comment]
> I'm sorry but i'm not sure what's going on from the pictures way too many zones. As for the text you say "You need to have a vehicle loot zone and a personal loot zone."
> 
> So new test: Car Trunk - Bound to cargo as Static Zone Pavement under the character - Personal Loot Unsorted
> 
> Shift-O And sort out my loot (all zones) works and moves the loot to the trunk, since you are combing two zone types, personal and static this would be to my understanding the correct choice. Zones are unchanged\enabled after sort.
> 
> Shift-O And sort out my loot (Static) does nothing as i would expect, since the personal zone isn't counted, so no items to move into. Zones are unchanged\enabled after sort.
> 
> Now the last one...
> 
> Shift-O and sort out my loot (Personal) is very strange. It shouldn't work was my belief, as there's no other zone rule for it to interact with, as the loot in the car is static and bound not personan, but it actually moves one item to the trunk of the static zone, and then claims the job is done. In addition it then disables the Personal Zone on the pavement for me, not the Static vehicle cargo, as you had as an issue with.
> 
> So there is something not quite right here, but would need better eyes to look at this.

So it seems to have multiple issues, not just the one we had.
Very interesting.
