### ISSUE TITLE
Error "invalid effect type id pkill1" using aspirin

### ISSUE THREAD

**Issue by Talonus12** [CleverRaven/Cataclysm-DDA#72880]
### Describe the bug

 DEBUG    : invalid effect type id pkill1

 FUNCTION : const T& string_id<T>::obj() const [with T = effect_type]
 FILE     : src/effect.cpp
 LINE     : 106
 VERSION  : cdda-experimental-2024-04-07-0406 73f46a9

Followed by the following on spacebar press:

 DEBUG    : Invalid effect, ID: pkill1

 FUNCTION : void Creature::add_effect(const effect_source&, const efftype_id&, const time_duration&, bodypart_id, bool, int, bool, bool)
 FILE     : src/creature.cpp
 LINE     : 1535
 VERSION  : cdda-experimental-2024-04-07-0406 73f46a9

### Attach save file

[Horseshoe Bend-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14896088/Horseshoe.Bend-trimmed.tar.gz)

### Steps to reproduce

1. Shift E to enter Consume menu
2. Navigate to Aspirin
3. Enter to consume Aspirin

No other context required, seems to occur at all times in all locations, when in pain.

### Expected behavior

Expected to consume aspirin without error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: cdda-experimental-2024-04-07-0406 73f46a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mining Mod [Mining_Mod],
    Original Drug Names [OG_Drugs],
    Bombastic Perks [bombastic_perks]
]

### Additional context

-----------------------------------------
17:06:12.795 : Starting log.
17:06:12.795 INFO : Cataclysm DDA version cdda-experimental-2024-04-07-0406 73f46a9
17:06:12.795 INFO : [main] C locale set to C
17:06:12.795 INFO : [main] C++ locale set to C
17:06:12.795 INFO : SDL version used during compile is 2.26.2
17:06:12.795 INFO : SDL version used during linking and in runtime is 2.26.2
17:06:13.216 INFO : SDL render devices: direct3d, direct3d11, direct3d12, opengl, opengles2, software
17:06:13.217 WARNING : opendir [./cache] failed with "No such file or directory".
17:06:13.219 INFO : [options] C locale set to C
17:06:13.219 INFO : [options] C++ locale set to C
17:06:13.220 INFO : Setting language to: 'en'
17:06:13.220 INFO : [i18n] Scanning core translations from lang/mo/
17:06:13.246 WARNING : opendir [data/cache] failed with "No such file or directory".
17:06:13.309 INFO : Active renderer: 2/direct3d12
17:06:13.805 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
17:06:14.211 INFO : Setting language to: 'en'
17:06:38.138 INFO : Loaded tileset: UltimateCataclysm
17:06:38.138 INFO : Loaded tileset: UltimateCataclysm
17:06:59.549 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff77b7d827e[cataclysm-tiles.exe+0x28827e]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x14028827e),
    0x14028827e    src/debug.cpp:1139    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff77b7d91a7[cataclysm-tiles.exe+0x2891a7]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x211@0x1402891a7),
    0x1402891a7    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/time.h:246    time
    0x1402891a7    src/debug.cpp:1467    DebugLog(DebugLevel, DebugClass)
  #2
    (dbghelp: @0x7ff77b7da167[cataclysm-tiles.exe+0x28a167]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ac@0x14028a167),
    0x14028a167    src/debug.cpp:515    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  #3
    (dbghelp: @0x7ff77c5e9c03[cataclysm-tiles.exe+0x1099c03]), 
    (libbacktrace: void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)+0x83@0x141099c03),
    0x141099c03    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/basic_string.h:795    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    0x141099c03    src/debug.h:78    void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)
  #4
    (dbghelp: @0x7ff77b846573[cataclysm-tiles.exe+0x2f6573]), 
    (libbacktrace: string_id<effect_type>::obj() const+0x87@0x1402f6573),
    0x1402f6573    src/effect.cpp:107    string_id<effect_type>::obj() const
  #5
    (dbghelp: @0x7ff77b6b2395[cataclysm-tiles.exe+0x162395]), 
    (libbacktrace: Character::is_immune_effect(string_id<effect_type> const&) const+0x141@0x140162395),
    0x140162395    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_iterator.h:1073    __normal_iterator
    0x140162395    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_iterator.h:1073    __gnu_cxx::__normal_iterator<string_id<json_flag> const*, std::vector<string_id<json_flag>, std::allocator<string_id<json_flag> > > >::__normal_iterator(string_id<json_flag> const* const&)
    0x140162395    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/stl_vector.h:960    std::vector<string_id<json_flag>, std::allocator<string_id<json_flag> > >::cend() const
    0x140162395    src/flat_set.h:87    cata::flat_set<string_id<json_flag>, cata::transparent_less_than, std::vector<string_id<json_flag>, std::allocator<string_id<json_flag> > > >::end() const
    0x140162395    src/character.cpp:5877    Character::is_immune_effect(string_id<effect_type> const&) const
  #6
    (dbghelp: @0x7ff77b7c1807[cataclysm-tiles.exe+0x271807]), 
    (libbacktrace: Creature::add_effect(effect_source const&, string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)+0x67@0x140271807),
    0x140271807    src/creature.cpp:1523    Creature::add_effect(effect_source const&, string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)
  #7
    (dbghelp: @0x7ff77c8783bf[cataclysm-tiles.exe+0x13283bf]), 
    (libbacktrace: Creature::add_effect(string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)+0x7f@0x1413283bf),
    0x1413283bf    src/creature.h:607    Creature::add_effect(string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)
  #8
    (dbghelp: @0x7ff77bb15801[cataclysm-tiles.exe+0x5c5801]), 
    (libbacktrace: consume_drug_iuse::use(Character*, item&, tripoint const&) const+0x46d@0x1405c5801),
    0x1405c5801    src/iuse_actor.cpp:780    consume_drug_iuse::use(Character*, item&, tripoint const&) const
  #9
    (dbghelp: @0x7ff77baae496[cataclysm-tiles.exe+0x55e496]), 
    (libbacktrace: itype::invoke(Character*, item&, tripoint const&) const+0xdc@0x14055e496),
    0x14055e496    src/itype.cpp:203    itype::invoke(Character*, item&, tripoint const&) const
  #10
    (dbghelp: @0x7ff77b783dc6[cataclysm-tiles.exe+0x233dc6]), 
    (libbacktrace: Character::consume(item&, bool)+0x7d6@0x140233dc6),
    0x140233dc6    src/consumption.cpp:1811    consume_med
    0x140233dc6    src/consumption.cpp:1863    Character::consume(item&, bool)
  #11
    (dbghelp: @0x7ff77b7861c5[cataclysm-tiles.exe+0x2361c5]), 
    (libbacktrace: Character::consume(item_location, bool)+0x75@0x1402361c5),
    0x1402361c5    src/consumption.cpp:1883    Character::consume(item_location, bool)
  #12
    (dbghelp: @0x7ff77b582f00[cataclysm-tiles.exe+0x32f00]), 
    (libbacktrace: consume_activity_actor::finish(player_activity&, Character&)+0xde@0x140032f00),
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr_base.h:1524    ~__shared_ptr
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr_base.h:1524    std::__shared_ptr<item_location::impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr.h:175    ~shared_ptr
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr.h:175    std::shared_ptr<item_location::impl>::~shared_ptr()
    0x140032f00    src/item_location.h:28    ~item_location
    0x140032f00    src/item_location.h:28    item_location::~item_location()
    0x140032f00    src/activity_actor.cpp:3169    consume_activity_actor::finish(player_activity&, Character&)
  #13
    (dbghelp: @0x7ff77beea183[cataclysm-tiles.exe+0x99a183]), 
    (libbacktrace: player_activity::do_turn(Character&)+0x977@0x14099a183),
    0x14099a183    src/player_activity.cpp:383    player_activity::do_turn(Character&)
  #14
    (dbghelp: @0x7ff77b82eaf4[cataclysm-tiles.exe+0x2deaf4]), 
    (libbacktrace: do_turn()+0x46d@0x1402deaf4),
    0x1402deaf4    src/do_turn.cpp:494    do_turn()
  #15
    (dbghelp: @0x7ff77cd93ab1[cataclysm-tiles.exe+0x1843ab1]), 
    (libbacktrace: main+0x24b8@0x141843ab1),
    0x141843ab1    src/main.cpp:868    main
  #16
    (dbghelp: @0x7ff77b5513ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: __tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #17
    (dbghelp: @0x7ff77b5514c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #18
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff84fb47344[KERNEL32.DLL+0x17344]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #19
    (dbghelp: RtlUserThreadStart+0x21@0x7ff8501226b1[ntdll.dll+0x526b1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/effect.cpp:106 [const T& string_id<T>::obj() const [with T = effect_type]] invalid effect type id pkill1
17:11:51.958 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff77b7d827e[cataclysm-tiles.exe+0x28827e]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0xa8@0x14028827e),
    0x14028827e    src/debug.cpp:1139    debug_write_backtrace(std::ostream&)
  #1
    (dbghelp: @0x7ff77b7d91a7[cataclysm-tiles.exe+0x2891a7]), 
    (libbacktrace: DebugLog(DebugLevel, DebugClass)+0x211@0x1402891a7),
    0x1402891a7    /opt/mxe/usr/x86_64-w64-mingw32.static.gcc12/include/time.h:246    time
    0x1402891a7    src/debug.cpp:1467    DebugLog(DebugLevel, DebugClass)
  #2
    (dbghelp: @0x7ff77b7da167[cataclysm-tiles.exe+0x28a167]), 
    (libbacktrace: realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1ac@0x14028a167),
    0x14028a167    src/debug.cpp:515    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  #3
    (dbghelp: @0x7ff77c5e9c03[cataclysm-tiles.exe+0x1099c03]), 
    (libbacktrace: void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)+0x83@0x141099c03),
    0x141099c03    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/basic_string.h:795    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    0x141099c03    src/debug.h:78    void realDebugmsg<char const*>(char const*, char const*, char const*, char const*, char const*&&)
  #4
    (dbghelp: @0x7ff77b7c18c7[cataclysm-tiles.exe+0x2718c7]), 
    (libbacktrace: Creature::add_effect(effect_source const&, string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)+0x127@0x1402718c7),
    0x1402718c7    src/creature.cpp:1536    Creature::add_effect(effect_source const&, string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)
  #5
    (dbghelp: @0x7ff77c8783bf[cataclysm-tiles.exe+0x13283bf]), 
    (libbacktrace: Creature::add_effect(string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)+0x7f@0x1413283bf),
    0x1413283bf    src/creature.h:607    Creature::add_effect(string_id<effect_type> const&, time_duration const&, int_id<body_part_type>, bool, int, bool, bool)
  #6
    (dbghelp: @0x7ff77bb15801[cataclysm-tiles.exe+0x5c5801]), 
    (libbacktrace: consume_drug_iuse::use(Character*, item&, tripoint const&) const+0x46d@0x1405c5801),
    0x1405c5801    src/iuse_actor.cpp:780    consume_drug_iuse::use(Character*, item&, tripoint const&) const
  #7
    (dbghelp: @0x7ff77baae496[cataclysm-tiles.exe+0x55e496]), 
    (libbacktrace: itype::invoke(Character*, item&, tripoint const&) const+0xdc@0x14055e496),
    0x14055e496    src/itype.cpp:203    itype::invoke(Character*, item&, tripoint const&) const
  #8
    (dbghelp: @0x7ff77b783dc6[cataclysm-tiles.exe+0x233dc6]), 
    (libbacktrace: Character::consume(item&, bool)+0x7d6@0x140233dc6),
    0x140233dc6    src/consumption.cpp:1811    consume_med
    0x140233dc6    src/consumption.cpp:1863    Character::consume(item&, bool)
  #9
    (dbghelp: @0x7ff77b7861c5[cataclysm-tiles.exe+0x2361c5]), 
    (libbacktrace: Character::consume(item_location, bool)+0x75@0x1402361c5),
    0x1402361c5    src/consumption.cpp:1883    Character::consume(item_location, bool)
  #10
    (dbghelp: @0x7ff77b582f00[cataclysm-tiles.exe+0x32f00]), 
    (libbacktrace: consume_activity_actor::finish(player_activity&, Character&)+0xde@0x140032f00),
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr_base.h:1524    ~__shared_ptr
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr_base.h:1524    std::__shared_ptr<item_location::impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr.h:175    ~shared_ptr
    0x140032f00    /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.gcc12/12.2.0/include/c++/bits/shared_ptr.h:175    std::shared_ptr<item_location::impl>::~shared_ptr()
    0x140032f00    src/item_location.h:28    ~item_location
    0x140032f00    src/item_location.h:28    item_location::~item_location()
    0x140032f00    src/activity_actor.cpp:3169    consume_activity_actor::finish(player_activity&, Character&)
  #11
    (dbghelp: @0x7ff77beea183[cataclysm-tiles.exe+0x99a183]), 
    (libbacktrace: player_activity::do_turn(Character&)+0x977@0x14099a183),
    0x14099a183    src/player_activity.cpp:383    player_activity::do_turn(Character&)
  #12
    (dbghelp: @0x7ff77b82eaf4[cataclysm-tiles.exe+0x2deaf4]), 
    (libbacktrace: do_turn()+0x46d@0x1402deaf4),
    0x1402deaf4    src/do_turn.cpp:494    do_turn()
  #13
    (dbghelp: @0x7ff77cd93ab1[cataclysm-tiles.exe+0x1843ab1]), 
    (libbacktrace: main+0x24b8@0x141843ab1),
    0x141843ab1    src/main.cpp:868    main
  #14
    (dbghelp: @0x7ff77b5513ae[cataclysm-tiles.exe+0x13ae]), 
    (libbacktrace: __tmainCRTStartup+0x22e@0x1400013ae),
    0x1400013ae    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup
  #15
    (dbghelp: @0x7ff77b5514c6[cataclysm-tiles.exe+0x14c6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014c6),
    0x1400014c6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc12/gcc-12.2.0.build_/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup
  #16
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff84fb47344[KERNEL32.DLL+0x17344]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #17
    (dbghelp: RtlUserThreadStart+0x21@0x7ff8501226b1[ntdll.dll+0x526b1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/creature.cpp:1535 [void Creature::add_effect(const effect_source&, const efftype_id&, const time_duration&, bodypart_id, bool, int, bool, bool)] Invalid effect, ID: pkill1
17:12:22.883 : Log shutdown.
-----------------------------------------

**Comment by ZhilkinSerg** [comment]
Issue with a third-party OG_Drugs mod.

**Comment by RenechCDDA** [comment]
Doubly confirming what ZhilkinSerg said above. I checked that mod's distribution, it is indeed a problem with them.

We do not, and cannot, support third party mods. If you have an issue with one, contact the mod's author.
