### ISSUE TITLE
[MoM] Pain limits ignore painkiller effects

### ISSUE THREAD

**Issue by MelacholicMimic** [CleverRaven/Cataclysm-DDA#72882]
### Describe the bug

The pain thresholds introduced by #72737 check against your total pain, not the pain you're currently feeling.

### Attach save file

N/A

### Steps to reproduce

1. Set pain to 50
2. Eat 2 Codein
3. Wait 15 mins
4. Try to cast power

### Expected behavior

Check against pain the PC is actually experiencing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 9fc88ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter]
]

**Comment by GuardianDll** [comment]
There is no such thing as "total pain vs pain you're currently feeling", it is the same thing.
Painkillers start to work after digestion, 30 minutes after consuming

**Comment by MelacholicMimic** [comment]
Then the UI is effectively lying to the player. The basic effect of the PR is you can't use power if pain is over 40. I so far had 3 separate occasions where the sidebar was telling me I had 0 to 10 (=minimal) pain, yet powers were inaccessible due to pain apparently >=40. Whatever the cause, it doesn't feel like that's what should be happening.

**Comment by Standing-Storm** [comment]
Hmm

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/2eb3d46c-6a55-48c4-8429-4d64aa1ef6cd)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/485a3ec7-94c9-449d-a26c-7c004be0c60c)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/1dbdb8a8-806b-4eef-bbb5-7718c9702f07)

There's definitely something going on. I used u_pain() to get the pain from the character, but in the screenshot, the character has Mild Pain (below the threshold, they should be fine to use their powers) but u_pain() is returning a value where they can't

Another odd thing:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/330f2bc2-6843-4775-b4ce-943c562fd900)

This is with the Spacebar UI. The pain says mild pain, as expected, but the separators are light red, which the code reads should only apply when `"condition": { "and": [ { "math": [ "u_pain()", ">=", "40" ] }, { "math": [ "u_pain()", "<", "60" ] } ] }`  Mild pain is between 10 and 20, but the separators don't reflect that. 

So something is going on.

`get_perceived_pain()` and `get_pain()` are separate. Does u_pain() only return the results from `get_pain()`, not `get_perceived_pain()`?

**Comment by GuardianDll** [comment]
u_pain return pain_cur(), which is indeed return only get_pain()

**Comment by GuardianDll** [comment]
i recommend you to make vanilla math function for this, and use it in MoM
