### ISSUE TITLE
tree and flower on the same tile, tree not displayed

### ISSUE THREAD

**Issue by bateau-de-coal** [CleverRaven/Cataclysm-DDA#72897]
### Describe the bug

A tree and a flower spawn on the same tile, but only the flower is displayed, leading to traffic accident.

### Attach save file

[Hackberry-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14901031/Hackberry-trimmed.tar.gz)

### Steps to reproduce

accident took place at 0, -1'144, 0'137

### Expected behavior

either tree and flower not occupying the same tile, or both objects clearly visible to the player in some way

### Versions and configuration

os: ubuntu
build type: linux-curses-x64
build number: 2024-04-06-0205
language: german
mods: default

**Comment by PatrikLundell** [comment]
I've seen them displayed on the same tile in the past, so this is probably either a new problem or something related to the tile set used.

The save, however, is rather useless, as it's apparently nowhere near the location, as I assume it didn't happen in the cave where the save is performed.
To be useful to any but the most dedicated investigator the save ought to be beside the offending tile so it's easy for people to find it.

**Comment by Procyonae** [comment]
Idk how to even interpret the coords you've given

**Comment by bateau-de-coal** [comment]
It is over map coordinate.

**Comment by bateau-de-coal** [comment]
close this because now tree blocks sight and you'll notice it when you see that a flower unusually blocks the vision
