### ISSUE TITLE
Remove reloading of misc repair, sew, tailor kits and needles and use new-old comfortable and realistic mechanic

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#72899]
### Is your feature request related to a problem? Please describe.

That lots of bug reports because of inability of reloading misc repair kits after duct tape was put into cardboard roll
And also in the future threads will be also fixed because its unrealistic, that you can split 1 long thread (100+ thread item) into lots of little piece of thread, and after make again long thread and reload with it any tailor instrument, so there will be in the future problem with tailor instruments
#72751 GuardianDll and few more contributors tried to fix this, but it is very hard, and, as for me - unrealistic, that you can reload misc repair kit (like and needles)
And this mechanic will also make problems in future for another or new instruments

### Solution you would like.

Make tools like tailor instruments or misc repair kit use nearby thread/sinews/duct tape like it already is when you are crafting something, so we already have the good mechanic

As for now, you should:
1) r - open menu to choose, what you want to reload
2) enter - choose tailor instrument or misc repair kit
3) enter - choose, which duct tape or what kind of thread material to use
And you should repeat it lots of time, when your instrument run out of charges

What I am suggesting
1) a - open menu to activate instruments
2) enter -  choose tailor instrument
3) enter - choose new added line in pop up menu "Thread type". 
By default it will be set to "any" or "thread", to prevent loosing Kevlar threads
So, if you don't want to choose specific type of thread, you can just skip all of this steps and start repairing, or you can choose specific king of thread, like thread, sinew, Kevlar thread, yarn, any(to use any nearby thread) and something else and while repairing you will automatically use nearby chosen type of thread with no need of manual reloading 

For misc repair kit you dont need to do this, because it will automatically use nearby duct take, and you don't need to manualy reload and choose from lots of duct tapes

So this will make much less keypresses in total and became super realistic

You can also add pocket to tailor, sew and misc repair kit, to store inside threads/duct tape

### Describe alternatives you have considered.

Leave all as it is or waste lot of time to try to fix this bugs, and wait for bugs for tailor instruments and needles in future

**Comment by AnotherSeawhite** [comment]
I've made a similar suggestion that has concept images in #72774. I think these could work for this suggestion.

![무제438_20240402011422.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/4a621646-5140-4516-afa8-07e5713299a5)

![무제442_20240402012919.png](https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/bb1e0871-a97f-4dbc-8020-da455ef3fed9)

**Comment by KHeket** [comment]
> I've made a similar suggestion that has concept images in #72774 a week ago. I think these could work for this suggestion.

Yeah, that what I was talking about. It doesn't matter for me, where this option will be, but good idea to place it repair window
But I think, its better not to choose directly nearby item, but to choose type of used item and make kits and needles automatically use it
Because in your case will be situation, when you choose "cardboard roll > 183 duct tape", then you will come to another place and   should to choose manually again new cardboard roll, if I understand your idea right, and I think there is no need for mist repair kit to choose cardboard rolls, just use by default rolls with lesser chargers, but it can be realized via my "any" idea. For misc repair kit by default will be "any", so it will use rolls with lesser charges, but you can manually choose specific cardboard roll if needed, but I don't think, its necessary

**Comment by Maddremor** [comment]
Perhaps outside the scope of the issue, but I would generally audit the use of "ammo" charges for anything that isn't literal ammunition, electricity, or a liquid. The charcoal cooker comes to mind.

**Comment by KHeket** [comment]
Will be solved in #72899

**Comment by GuardianDll** [comment]
Wrong issue number?

**Comment by KHeket** [comment]
> Wrong issue number?

Yep, edited
