### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#72908]
### Describe the bug

The master code I downloaded a few hours ago is broken.
My save crashes directly on load, after chugging through the garbage reports resulting from crappy migration (hair color, bionic trickle feed, the junk reward ruger_redhawk gun given by the old guard, some 9b building that's no longer supported, etc.).
A bug report save I was trying to use for testing (which has worked previously) crashes when the PC moves closer to the bug report target site where a companion is working. First there's a bug report about some disatisfaction bionc that's not supported, then some vitrification stuff that has an illegal value, followed by a crash.

### Attach save file

N/A. My compressed saves are too large. The #72758 one is the bug report save referenced.

### Steps to reproduce

1. Load a save and have it crash (CTD) either directly or after a short while.

### Expected behavior

Not crashing...

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 0.G-8678-g0095b3047e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]
"Dirty" because I was trying to test a bug fix. However, my code has all been commented out.

**Comment by PatrikLundell** [comment]
Still broken...
- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 0.G-8696-ge37e4719a6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

Error reports before the crash which may or may not be related.
 DEBUG    : invalid bionic id "asocial_dissatisfied"

 FUNCTION : obj
 FILE     : C:\Cataclysm-DDA\src\generic_factory.h
 LINE     : 482
 VERSION  : 0.G-8696-ge37e4719a6

This definitely looks like something is corrupted. I believe the value was " 9  y  " yesterday.
 DEBUG    : failed to convert variable "npctalk_var_vitri_vitrified" with value "i��b�" to a number

 FUNCTION : eval
 FILE     : C:\Cataclysm-DDA\src\math_parser.cpp
 LINE     : 241
 VERSION  : 0.G-8696-ge37e4719a6

**Comment by ZhilkinSerg** [comment]
Have you tried to clear `\data\cache` folder?

**Comment by PatrikLundell** [comment]
I just tried moving it into "New Folder" (in case it's somehow needed), tried to load my main save, and it still crashes on load (that's not the bug report save above). The cache was repopulated.
I also tried the bug report save and it still crashes (although the vitrified stuff string was approximately "i     " this time).

**Comment by PatrikLundell** [comment]
@ZhilkinSerg's question prompted me to try to get rid of other "cached" info by rebuilding from scratch, and that did work. Thanks!
