### ISSUE TITLE
[Self assigned] "CITY_UNIQUE" flag

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#72904]
### Is your feature request related to a problem? Please describe.

UNIQUE currently makes it so only 1 of that special can appear per overmap (not to be confused with GLOBALLY_UNIQUE). Currently no city specials use this flag but with #72815 adding the ability to limit special spawns in cities based on city size it would make sense to increase their weights so their relative occurrences doesn't drop, however currently that would lead to multiple of the same type appearing in a single city which doesn't make sense for some of them.

### Solution you would like.

For cities it would make more sense for this to limit specials to 1 per city.

### Describe alternatives you have considered.

Using a separate flag for this functionality but UNIQUE is currently unutilised by city specials.
Waiting on someone to figure out limiting special placement based on already placed specials so you can prevent same function buildings spawning near each other where sensible even when there are multiple similar specials (as well as more realistic placement in general)

**Comment by PatrikLundell** [comment]
I prefer the usage of keywords that actually say what they do rather that provide some vague hint. Thus, I'd suggest the unspecified "UNIQUE" should be faced out and replaced with ones that actually say what they do (like e.g. "OVERMAP_UNIQUE"). In your case I'd suggest "CITY_UNIQUE" or "ONLY_ONE_IN_CITY".
Having the same keyword mean different things depending on context is bound to result in confusion (especially if there's nothing to indicate what the context is).

**Comment by RanikOrtega** [comment]
> I prefer the usage of keywords that actually say what they do rather that provide some vague hint. Thus, I'd suggest the unspecified "UNIQUE" should be faced out and replaced with ones that actually say what they do (like e.g. "OVERMAP_UNIQUE"). In your case I'd suggest "CITY_UNIQUE" or "ONLY_ONE_IN_CITY". Having the same keyword mean different things depending on context is bound to result in confusion (especially if there's nothing to indicate what the context is).

Since we already have GLOBALLY_UNIQUE. It makes sense to include CITY_UNIQUE and OVERMAP_UNIQUE to cover all bases. One per city, one per overmap and one per world.
