### ISSUE TITLE
In Game Lore for Firearm/Ammo Availability

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#72903]
### Is your feature request related to a problem? Please describe.

It would appear that quite a lot of recent changes (e.g. https://github.com/CleverRaven/Cataclysm-DDA/pull/72813) were focused on removal of firearms/ammo that are not available in the (real world) USA. However, given that in-game world is not a carbon-copy of our reality (AFAIK, China has not invaded USA yet and is not ruled by an Emperor), IMO it is unwise to apply all reasons from our world indiscriminately. I agree that there shal be rules on what to include in the game and what not.

Quick study of the related [GUN_NAMING_AND_INCLUSION.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GUN_NAMING_AND_INCLUSION.md) document  refers to real life gun dealings sites (GunBroker, GunsAmerica, Rock Island Auctionhouse, etc). However, these sites must deal with real-life trade embargoes, import restrictions and current (geo)political situation. So, usage of these sites as a metric for "Rarity Threshold" imprints real-world into in-game world.

1) For example, it is safe to assume that there is no shortage of the "AK rifle" worldwide, and while in real world importing these weapons in the US is heavily restricted, that might not be the case for the in-game world.

2) Another example: as we know, in-game China invaded US and even declared "victory" shortly prior to game start, so it is safe to assume a number of Chinese firearms was "imported" into US and found its way into "aftermarket" as war trophies.

3) Lastly, while it is reasonable to use online dealings sites for legal firearms, we must also take into consideration **illegal** activities. You might not find a fully automatic rifle in a gun shop, but finding a rifle "upgraded" to full auto (or imported as parts and re-assembled) in some gun enthusiast's basement is sort of expected. Some people (like Brandon Herrera) do even have a license for gun manufacturing.

### Solution you would like.

My proposal is:
1) In addition to "Civilian Firearms" and "Military and Police Firearms" categories introduce the "Illegal/Custom Firearms". This new category shall not spawn in gun shops and shall be reserved for hidden weapon stash locations (LMOE shelters, mansion secret rooms, gun enthusiast's basements and so on).
2) Weapons in the "Illegal/Custom Firearms" category shall be far less restricted. For inclusion into this category one shall use the "If there is a will, there is a way" approach. Basically, assume that if a gun is produced in quantities somewhere in the world, it can be brought into in-game world one way or the other.

### Describe alternatives you have considered.

Alternatively, we shall work more on the in-game lore and expand our world description. What countries and alliances exist, what were relations between them prior to the Cataclysm. Ideally, game world shall not mimic our world (because IMO, we are having enough of "our world" in real life to observe the same in-game). Some weapons long-obsolete in real life may be still in production and quite popular in-game (due some ongoing conflict or financial situation).

This would require much more work, but can result in far more believable and unique game world.

**Comment by ZhilkinSerg** [comment]
> I agree that there shal be rules on what to include in the game and what not.

There are two criteria - see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GUN_NAMING_AND_INCLUSION.md#inclusion-criteria

**Comment by Alm999** [comment]
> There are two criteria
Yep. "Rarity Threshold"  and "Difference Threshold".
The problem (IMO) is that "Rarity Threshold" is too strict and both 1) does not take into account black-market and hand-made (Luty) firearms, and 2) imprints real-world restrictions onto fictional in-game world.

This basically limits us to street-legal current-age real-world USA firearms.

**Comment by GuardianDll** [comment]
Rarity Threshold takes into account black-market weapon perfectly, because crime dealers do not really use rare, imported weapon, with rare ammunition, they use completely opposite - the most popular weapon, the most accessible one, the most basic one.
And no one produce hand made firearms in any valuable amount, because it's hard, require complicated and expensive tools, legally prohibited, and cost more than buying any another gun

\> This basically limits us to street-legal current-age real-world USA firearms.

Yeah, that's kinda the point - representing the actual US firearm market, not wacky call-of-duty set of weapons

**Comment by tenmillimaster** [comment]
I agree that there should be some consideration given to illegal firearms, but it is not going to be things like lutys or the 6p67 Kord. It'll be things like Glock switches, coat hanger lightning links, and 3d printed lightning links.

**Comment by kevingranade** [comment]
This is all very much intentional. We are aiming at matching the current reality as well as we can and not making arbitrary adjustments.
