### ISSUE TITLE
Sparring

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#72914]
### Is your feature request related to a problem? Please describe.

A lot of the combat practice actions are freebies that just feel like a waste of time. Specifically the 0-1 and to a lesser extent the 1-3 melee/dodge/weapon ones. You find a stick and spend 5 minutes waving it around and now you're reasonably good at fighting with it?

It basically becomes a simple chore at game start that's so easy that it obviates taking the skills at chargen, and may as well be given to the player for free. The only time the 0-1 skill gap ever really matters is when the game starts you adjacent to a zombie.

### Solution you would like.

Make these low-skill training activities require an NPC partner and quite a bit more time. Waving a stick around in a field by yourself is not teaching you how to fight. Walking through the process with a partner and trying out practice swings, defensive techniques, etc. is.

This would have the added benefit of letting certain crafts require one or more NPCs. Some tasks are not reasonable for one person to do alone (the unending anvil argument comes to mind) but could be done by multiple people.

### Describe alternatives you have considered.

This could also be done as an NPC activity via the dialog menu, and it might be interesting to sometimes accidentally take or deal a hit during these sessions. This could incentivize players to find or make things like cardboard swords or training armor.

For players who don't want a companion NPC, maybe the mercenary in the refugee center (or Cranberry at the Hub, or both) could train basic combat skills for a price.

### Additional context

The more complex training activities that require dummies and stuff are fine IMO, both because constructing those dummies is a meaningful task and because people train that way in real life. The dry-firing practice action is also probably fine, as a gun is a complex and dangerous piece of technology that many people are not personally familiar with. Taking a few minutes to sort out how the magazine release, the slide, the safety, and the sights work would be of tangible benefit to someone who had never touched a gun in their life. The same can't be said of a stick.

**Comment by IdleSol** [comment]
I don't see any problem in getting a level 1 quickly.

> Beginning hobbyist level: 1-2 (You've done this enough that you understand how to do basic things, know the tools that are used, and follow the language.)

**Comment by kevingranade** [comment]
This is working as intended.  Times are abbreviated as with all intended skill leveling times, but the lack of external requirements is very much what we want. 

0 in particular is 'literally never threw a punch/ swing a weapon in anger' and remedying that is intended to be easy.

I could see a *better* sparring related practice, particularly at lvls 1-3.
