### ISSUE TITLE
possibly unintentional: "Recycler" bionic causes you to to weary half as fast

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72921]
### Is your feature request related to a problem? Please describe.

Currently if you install the Recycler bionic, you get weary half as quickly, with no detriment to your recovery. This is due to its METABOLISM enchantment. It's not clear if it should work this way given it's merely reclaiming fluids and nutrients and not somehow sustaining their muscles past the point of soreness.

### Solution you would like.

It probably shouldn't halve weariness, but I figured I'd pose the issue here to see what others think.

### Describe alternatives you have considered.

Give it a power requirement also? Since currently it's a freebie but given its function it's not unreasonable it needs power too.

**Comment by GuardianDll** [comment]
related issue: #72781, and PR #72255
