### ISSUE TITLE
vehicle display

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#72928]
### Is your feature request related to a problem? Please describe.

<img width="228" alt="90e238b8193a7d2b9aaa0a85121dadf1" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/24226340/38fa3ebb-fde0-4d42-a10c-452d3c4d7f52">

### Solution you would like.

vehicle display normal

### Describe alternatives you have considered.

vehicle display

### Additional context

vehicle display

**Comment by Brambor** [comment]
I don't get it.

**Comment by PatrikLundell** [comment]
Yes, as indicated by the previous comment, you have failed to point out WHAT you think is wrong, and just hope others can read your mind to figure out what you think is wrong.

The image doesn't give any details of what the vehicle is supposed to be and look like.
You've created a suggestion without suggesting anything (apart from that visuals should be as you wish them to be), when you might have wanted to write a bug report (in which case you should provide the mandatory version, mod, etc. info that would help people track down the issue).

It could, however, be that you're confused by the intended but somewhat odd way the game adds pseudo tiles to vehicles at an angle to deal with various issues resulting from trying to display a (typically) rectangular vehicle at an angle.
Note that the game is tile based, so it's not possible to display a vehicle at an angle with pixel resolution. The tile is the resolution available.
