### ISSUE TITLE
[MoM] Nether Attunement not working

### ISSUE THREAD

**Issue by Sofistico** [CleverRaven/Cataclysm-DDA#72934]
### Describe the bug

The debug window returns this error when i use a psionic: 
invalid effect_on_condition id "EOC_RAISE_NETHER_ATTUNEMENT"

Latest experimental

### Attach save file

[Balfour-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14922715/Balfour-trimmed.tar.gz)

### Steps to reproduce

1. Load the save
2. Try to cast any psionic
3. Note that even after extensive channeling, no nether attunement is raised.

### Expected behavior

The nether attunement should be there.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.2965 (20H2)
- Game Version: cdda-experimental-2024-04-09-1421 2c47a81 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills],
    Extra Mutated Scenarios [extra_mut_scens],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bombastic Perks [bombastic_perks],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter]
]

**Comment by Sofistico** [comment]
Weird... Actually it seems to be working now, i just got it to raise the nether attunement... I will let the issue stand just for someone else to confirm that it's working as intended

**Comment by Standing-Storm** [comment]
I think this was caused by a problem in one PR that was then solved in another. The latter PR was just merged not that long ago, so I believe that should fix the problem (I just tested it and didn't get the error)

**Comment by Sofistico** [comment]
So it's probably just some experimental weirdness then! Good to know and thank you storm
