### ISSUE TITLE
"Fructose Intolerance" doesn't cover many forms of fructose

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72953]
### Is your feature request related to a problem? Please describe.

Currently Fructose Intolerance (FI) only bans the consumption of fruit. But most vegetables contain fructose. Also, many junk foods contain corn syrup, itself a form of fructose. Honey has fructose. Etc.

### Solution you would like.

It's tough to say what the proper solution is. The "fruit matter" property could be assigned to many veggies and junk foods but that would be somewhat clumsy. Fructose could be made a vitamin and assigned to various foods and FI could cause you issues with those, although that would cause it to work differently from the other "allergen" traits and create a bit of inconsistency.

### Describe alternatives you have considered.

Idk, remove the trait?

**Comment by RenechCDDA** [comment]
>It's tough to say what the proper solution is.

Allergens as vitamins!

**Comment by fairyarmadillo** [comment]
It should probably just be called "fruit allergy" or something.
