### ISSUE TITLE
Set default for where a weapon is stored when you holster/sheath it

### ISSUE THREAD

**Issue by ryeookin** [CleverRaven/Cataclysm-DDA#72950]
### Is your feature request related to a problem? Please describe.

When I stop wielding my fire axe it always defaults to my general inventory rather then my preferred holster. I asked in discord if a different default could be set and Guardian said "nope" and suggested I submit this for a feature request.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/85190400/72900a6c-55cc-43d9-9527-47aa5855300d)

### Solution you would like.

It would be nice if one could set a preferred default when they stop wielding their weapon.

### Describe alternatives you have considered.

The work around in the mean time is just remembering to manually select the correct holster each time is 'sheathed'.

**Comment by MelacholicMimic** [comment]
Now that I think about it, how does "store in inventory" even work? If your pockets are set up appropriately, your weapon will end up in the sheath regardless, it just takes 9 times as long for seemingly no reason?

**Comment by DragonWizard23** [comment]
> Now that I think about it, how does "store in inventory" even work? If your pockets are set up appropriately, your weapon will end up in the sheath regardless, it just takes 9 times as long for seemingly no reason?

I've wondered this too. Like, is the timing inaccurate and it actually takes the same amount of time despite the readout or is something else going on?

**Comment by MelacholicMimic** [comment]
I did test it, using the default option does indeed take 2 seconds. If I had to guess, it just creates a magic number from volume/weight regardless where the item goes.  This might still be pre pockets tech.

**Comment by EternalLaughter** [comment]
> I did test it, using the default option does indeed take 2 seconds. If I had to guess, it just creates a magic number from volume/weight regardless where the item goes. This might still be pre pockets tech.

Yeah there's something funky going on there time wise when using the default 200 move send to inventory.
Location wise it seems to respect priorities and rules on pockets as you'd hope when you use this for either backpack or belt, but the time spend is 200 moves no matter the pocket's actual move cost.

**Comment by oosyrag** [comment]
There are quite a few strange move cost inconsistencies in the game, but that's a separate issue. 

(https://github.com/CleverRaven/Cataclysm-DDA/issues/65062)
