### ISSUE TITLE
map::collapse_check SINGLE_SUPPORT code broken

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#72960]
### Describe the bug

The code dealing with SINGLE_SUPPORT in map::collapse makes no sense.
The code checks the same static value in two loops and then resets the counter to 0 each time.
As far as I can tell, this is equivalent to returning 0 from the function if the SINGLE_SUPPORT flag is set, which is then fed into a one_in() call that always returns true, i.e. collapse. That's probably not intended.

### Attach save file

N/A, it's source code.

### Steps to reproduce

1. Examine the code in map::collapse_check (in map.cpp)

### Expected behavior

I don't know what the behavior should be, but I would expect a guaranteed collapse if there's no support directly under the tile, and probably some chance for a collapse when support exists (based on the normal case not having a case where there is always a collapse chance). What's in surrounding tiles and surrounding tiles below shouldn't matter for this case.
I also don't think SINGLE_SUPPORT tiles should provide support for anything around them (the current code doesn't do that).

I'd expect the code to factor out the SINGLE_SUPPORT case to before the loops and return one of the two results from there.

Note that it's possible it should always be a guaranteed collapse regardless of support below, given that a roof supported only by a wall below is guaranteed to collapse (5-5 support points, when you need a value > 1 to provide a chance for not collapsing). That would obviously simplify the code further.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-8762-ga573b71648 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

I looked at the code in an attempt to understand what the SINGLE_SUPPORT flag actually means, because there is no documentation for the flag.

I believe the meaning of SINGLE_SUPPORT is intended to be that the tile can accept support only from directly below, and this is what the expected behavior section reflects.

I do find it odd that there's nothing that guarantees there won't be a collapse (and I don't know what a collapse at OVERMAP_DEPTH should look like, although it's probably ignored). That is out of the scope of this report, though.

I think @fairyarmadillo may have some insight into this (sorry if that's not the case).

**Comment by fairyarmadillo** [comment]
> I believe the meaning of SINGLE_SUPPORT is intended to be that the tile can accept support only from directly below, and this is what the expected behavior section reflects.

This is the case. It is for treetops, to prevent a situation where a tree is cut down but its top remains floating in midair because there were adjacent tops from other trees.

**Comment by fairyarmadillo** [comment]
So now that I'm more awake, I am recalling that partly the purpose of single_support is to bypass the one_in check in order to cause the roof (a treetop in this case) to always fall when its support goes.

**Comment by PatrikLundell** [comment]
Well, the PR should achieve that (as well as cause it to fall if hit directly while the tree is still standing to mimic the behavior of a roof on a single wall). The separate flag allows tree tops to ignore neighbor support and to not provide any, so that part is good. It's only the actual implementation of this function that was weird (but still working).
