### ISSUE TITLE
Garage doors duplicate, and I keep getting wet in garages.

### ISSUE THREAD

**Issue by Ava-PLSK** [CleverRaven/Cataclysm-DDA#72965]
### Describe the bug

Whenever I tried to open a garage door using the indoor winch, it failed for a few attempts before finally opening. The issue is that the garage door then proceeded to duplicate across the tiles above it. 

During a rain storm, I also would get wet, despite being inside a garage. The rain textures would load through those tiles, but nowhere else in the house.

### Attach save file

[Massachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14949273/Massachusetts-trimmed.tar.gz)

### Steps to reproduce

Enter garage
Try to open garage door from the inside winch.

**For the rain glitch just spawn a rain storm and wait inside the garage.**

### Expected behavior

I expected the garage door to open by pulling the inside winch, since it normally opens it.

I would assume the garage has a ceiling to keep out the rain.

### Screenshots

![20240411_110913](https://github.com/CleverRaven/Cataclysm-DDA/assets/166742015/47cac5ce-0806-40a7-a0fe-0bad384e8ff7)
![20240411_110922](https://github.com/CleverRaven/Cataclysm-DDA/assets/166742015/f69e2b4e-f0cb-423e-8add-1f13fe85466b)
![20240411_110927](https://github.com/CleverRaven/Cataclysm-DDA/assets/166742015/1d934720-e7d8-4026-b235-6b3694ec32bc)

### Versions and configuration

Windows 11, April 10th experimental build, Chibi Altica tiles, English is the in-game language, and I'm using portal storms ignore npcs, slowdown fungal growth, disable npc needs, the CDDA base pack, and the Massachusetts mod.

**Comment by oosyrag** [comment]
I don't suppose you've seen this happen in other/all garages? Or isolated to this particular house?

**Comment by PatrikLundell** [comment]
Failure of winches to work occasionally has been present for years, so it's not a new issue. The old bug reports are probably long since killed off by the stale-bot, though.

**Comment by Ava-PLSK** [comment]
> I don't suppose you've seen this happen in other/all garages? Or isolated to this particular house?

I've tested it just now, the rain only seems to go through one house in Egremont. Not sure why.
![20240412_133601](https://github.com/CleverRaven/Cataclysm-DDA/assets/166742015/d663fe5e-ce1a-44aa-9077-0abdea609d9d)
![20240412_133608](https://github.com/CleverRaven/Cataclysm-DDA/assets/166742015/4168ca14-69c9-49c6-bbff-96abb56fe73f)

**Comment by Ava-PLSK** [comment]
I'm not sure what I did, but either the duplicate garage doors disappeared, or I unintentionally fixed that issue.
