### ISSUE TITLE
problem with widget in game

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#72968]
### Describe the bug

button widgets do not have the usual shape

### Attach save file

None

### Steps to reproduce

None

### Expected behavior

should everything be in the same style?

### Screenshots

normal style
![Снимок экрана от 2024-04-11 22-19-32](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/49990592-acf4-4226-abb6-8dd1a9c41e98)

wrong style
![Снимок экрана от 2024-04-11 22-19-51](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/82f6d6ec-16bb-4bcd-9e94-c08d8a833dd7)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: cdda-experimental-2024-04-11-1603 9819962 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by katemonster33** [comment]
perfectly normal, see #72937

**Comment by kevingranade** [comment]
In other words, yes they will eventually be all styled the same way once all the windows are migrated.
