### ISSUE TITLE
Default selection for imGui.

### ISSUE THREAD

**Issue by Vane79** [CleverRaven/Cataclysm-DDA#72961]
### Is your feature request related to a problem? Please describe.

Default selection for imGui windows is set to "yes" which is totally wrong according to my muscle memory. As in, before, to change any setting you had to change the setting, press escape, move selection left, press enter. Now it's wrong.

### Solution you would like.

So, please either make it the way it was, or add the ability to change the default selection ourselves.

### Additional context

Cataclysm-DDA experimental build 2024-04-11-0340

**Comment by esotericist** [comment]
"my muscle memory is impacted" on its own is not an adequate call for change. if there are some dialogs that logically should be defaulting to no for safety that suddenly aren't, that could warrant attention.

please be more specific, "some things have changed" isn't actionable.

**Comment by Vane79** [comment]
The swap to ImGui in itself changed, as far as I can tell, all the dialogue windows from default "no" to "yes".

Clothes "swap side" used to be default "no", now - "yes"
Auto traven on the overmap - used to be "no", now - "yes"
Disassembly menu, butchery, etc. From the obvious point, now, everything requires one less button stroke, (as in, you don't have to press "left" on every confirmation dialogue) but, in actuality, it requires double the button strokes just because one has to double-take every dialogue menu because of how things were.

**Comment by katemonster33** [comment]
looks like the new popup doesnt respect calls to set the default choice. popup.cpp , query_popup::cursor needs to be modified to notify the UI to set the selected button to be the value of 'cur'

**Comment by mabmoro** [comment]
Just saw a potential issue with this, the 'abandon character' dialog also defaults to 'yes'. I just accidentally thick-fingered my keyboard when playing and nearly killed a successful character off, so it might be worthwhile at least for that dialog, to make the default 'no'.
