### ISSUE TITLE
Remove player character's prior knowledge of battery charge

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#72972]
### Is your feature request related to a problem? Please describe.

I had the realization that it is a little odd that the player character can instantly determine the charge of a battery. After testing a battery, it makes sense for the player to know the charge (self-discharge of modern batteries is very low), but prior knowledge is uncanny. 

### Solution you would like.

Instead of behaving like this, it should not be apparent what the charge of a loose battery is without testing it. This could be done in a couple of ways:
- Testing the battery voltage using a multimeter or voltmeter. While I was considering whether this should be an automatic action or manually initiated by the player, I thought of a compromise: when testing for voltage, a menu could pop up letting the player select which items to test the voltage of. 
- Placing the battery in a charger. Most modern battery chargers display cell voltage. 
- Putting the battery in a device. Most modern power tools, flashlights, cameras and personal electronics indicate charge level. 

### Describe alternatives you have considered.

I considered that the batteries in-game may be like the "press-for-charge-level" batteries in real-life, but those aren't as widespread as batteries without this feature.

**Comment by Uwuewsky** [comment]
I think the idea of hiding the battery charge was rejected in #71390

**Comment by PGR-14** [comment]
Also, batteries bounce higher the more charge there is, so it's pretty easy to grab a battery you know is fully charged, bouncing it, & then bouncing the other to tell how much charge is in it.

**Comment by DragonWizard23** [comment]
@PGR-14 and @mlgproftw Thanks for your input! I was not aware of either of those methods of testing charge. Do those work for all batteries or only specific ones (e.g. AA/AAA and 9V)? 

After some further thought, this suggestion should probably only apply to light and ultra light batteries, as medium and larger cells could have built in charge indicators. 

I absolutely agree with you that we don't want to make the gameplay more annoying/tedious. Instead of knowing the exact charge, perhaps we could implement a system where the player knows approximately how charged the batteries are. This could be done in a similar way as how the player can roughly tell when food is going to expire, but not exactly. 

This could be done with 5 groups, such as fully charged, mostly charged, partly charged, barely charged, and uncharged. With a high-capacity light battery, this tells the player how charged the battery is within 60 units. 

This would still provide the player with valuable information about the charge of the battery, and players who want to know the exact charge could put the battery in a device or charger. As a secondary benefit, this could pave the way for batteries of similar charge to stack in inventory, making it easier for the player to separate batteries by charge.

**Comment by PGR-14** [comment]
Mine usually works on those A batteries (AA, AAA), & anything like a cylinder, at least I think so.

Also, medium batteries are tool batteries, like this: 
https://m.media-amazon.com/images/I/51kXccXAnuL._AC_UF894,1000_QL80_.jpg 
Which usually have a charge indicator (Laptops also have charge indicator, I.E. on the Bottom Right of your screen)

Heavy batteries are the same type of thing, just bigger.

**Comment by PGR-14** [comment]
Also, the 60 units should change depending on the battery, ultralight ones shouldn't be off or on 60 units.

Also Also, if we implement this, we should also add in an item to check a battery's charge

**Comment by DragonWizard23** [comment]
> Also, the 60 units should change depending on the battery, ultralight ones shouldn't be off or on 60 units.

I agree. I was trying to use the high-capacity light battery as an example to demonstrate the maximum difference a player would typically encounter (ignoring plutonium batteries). With an ultra-light battery (50kJ), the 5 groups would be 0-10, 10-20, 20-30, 30-40, 40-50. :)

> Also Also, if we implement this, we should also add in an item to check a battery's charge

Yes, that sounds like a good idea. I think those are a fairly common household item.

**Comment by DragonWizard23** [comment]
After feedback, I no longer think it makes sense to hide the battery charge information from the player. It was brought to my attention that light batteries can be tested by hand, and larger batteries often have charge indicators. This leaves the ultra-light battery as the only remaining one, but I do not think we should change it alone, for the sake of consistency. 

It is still a little odd that we can tell the *exact* charge of batteries, but the gameplay benefits outweigh the verisimilitude. As a closing thought, grouping batteries of similar charge (of the same type) might remove some visual clutter from menus.
