### ISSUE TITLE
Solar Thermal Energy

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#72977]
### Is your feature request related to a problem? Please describe.

We have solar panels, but we could have the ancestor of solar panels: Solar thermal panels.
The way how it works is self-explanatory. The panels collect heat from the sun, and the heat goes to the water tank, which has a motor (turbine?) inside. The heat vaporizes water into steam, generating power by turning the motor.
Additionally, the player could make those as substitutions for photovoltaic kind of solar panels.

...Or, the player could make use of sunlight directly, like a solar cooker.

### Solution you would like.

Adding various ways to make use of solar thermal energy.

**Comment by oosyrag** [comment]
Someone was looking into a fruit drying rack a few days ago, passive item transformation by sun drying fruit. Pretty cool although it probably wouldn't be viable most of the time in NE climate.

Homemade solar steam generators would be inefficient to the point of not working I think. 
https://www.youtube.com/watch?v=Yy20z0y2tok gets a whole peak of 2.5 watts for a few seconds after building pressure for who knows how long. Designing a sealed water reclamation/cooling loop system that manages usable pressures to get power out would be decidedly nontrivial as well.
