### ISSUE TITLE
ImGui. The buttons don't fit in the window.

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72986]
### Describe the bug

Perhaps the problem is that the text is too long.
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/09434bf9-dff7-4073-a127-eab50f78fe0f)
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/5de74465-5f65-416a-8e55-22899592a84d)

1. You are standing in smoke. Stop producing items
2. A danger (zombies) has been detected. Stop moving items

These same messages are in English:
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/73cae61b-f67c-480a-bf2c-9cefc3cba73b)
![4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/da70d631-e826-4f9a-a27a-76b11ce431cf)

The problem is that the "yes" button doesn't fit in the window. There is only part of the "no" button, open manager and ignore.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Normal window display

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-11-2208 0bcda8a [64-bit]
- Graphics Version: Tiles
- Game Language: Russian [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

@katemonster33

**Comment by katemonster33** [comment]
probably part of the code calculates the total size needed for the right-aligned buttons based on the untranslated value. also please stop pinging me in every imgui-post you make

**Comment by katemonster33** [comment]
Right, and for the question mark question, when I wrote #72579, I had to make some artificial adjustments to the x/y coordinates when drawing to the screen from an imgui call. I'm still not sure why this needed to be done. It's possible that the adjustment I made to get CJK characters to look ok doesn't work for Cyrillic. Yes it's a separate issue, you can make an issue if you want, but I don't know how easy it will be to fix
