### ISSUE TITLE
ImGui. Keybindings. Doesn't work."Add local keybinding." 

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72980]
### Describe the bug

When controlling from the keyboard, you cannot assign a key. Doesn't work `shift` + `=`.

If you use a mouse, it's fine.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

cdda-windows-tiles-x64-2024-04-11-2208

### Additional context
Numpad `+`.  It doesn't work either.

@katemonster33

**Comment by oosyrag** [comment]
Confirmed in Android too. + doesn't do anything in the key binding screen.

**Comment by IdleSol** [comment]
Before creating a separate topic, I would like to clarify. Is it possible to change the appearance of imGui windows? Bring it to the same style as the other windows.

**Comment by katemonster33** [comment]
ImGui style may change in the future and become more configurable, but it is going to look different, that is just the way things will be for the future.
