### ISSUE TITLE
Receiving "trying to learn negative without direct" error in proficiency gain EoC

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#72982]
### Describe the bug

In Mind Over Matter, gain of concentration proficiencies is handled almost entirely through EoC: [](https://github.com/CleverRaven/Cataclysm-DDA/blob/0bcda8aaecdb07427e4b6c4d847ac4aef8a4978d/data/mods/MindOverMatter/effectoncondition/eoc_on_power_use_events.json#L604). However, currently I receive the following error message when the Master Concentration proficiency sub-EoC is called: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/331c84ab-5a3c-4654-9238-12f2e8e64672)

### Attach save file

[Colony-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14962461/Colony-trimmed.tar.gz)

### Steps to reproduce

1) Wait six hours
2) Error message occurs at some point.

### Expected behavior

No errors

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 9819962 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

Beginner and Expert concentration gain EoCs generate no errors.

**Comment by anothersimulacrum** [comment]
This is due to FP math.

KISS solution (and probably the most robust):

`< -1` instead of 0, but do nothing when it's negative. FP math should be correct within that magnitude, it'll obscure few errors, and not cause problems when errors occur.

https://github.com/CleverRaven/Cataclysm-DDA/blob/0bcda8aaecdb07427e4b6c4d847ac4aef8a4978d/src/math_parser_diag.cpp#L1230
