### ISSUE TITLE
Tried to set charges for item yeast that could not have them!

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#72984]
### Describe the bug

The error occurs when viewing the sealed yeast culture recipe.

```
 DEBUG    : Tried to set charges for item yeast that could not have them!

 FUNCTION : item::item(const itype*, time_point, int)
 FILE     : src/item.cpp
 LINE     : 318
 VERSION  : cdda-experimental-2024-04-11-2208 0bcda8a
```

### Attach save file

N/A

### Steps to reproduce

1. Open the craft menu
2. Find the `sealed yeast culture` recipe (food handling 2)
3. Get an error

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-11-2208 0bcda8a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
/Confirmed

Followed description and the error occurred. Not quite sure exactly when the code is from (not sure which branch it was compiled from), but it's from the last few weeks.

**Comment by RenechCDDA** [comment]
So what this caught was actually a display error in iuse_transform::info.

https://github.com/CleverRaven/Cataclysm-DDA/blob/34f99c8306ed1e7ba03f7d0be0dd0821c1701bf7/src/iuse_actor.cpp#L436
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/49f798cc-a520-4136-b1ba-65591d94abb8)

Note that even if we set the charges of the dummy item it won't display as `yeast (50)`, because yeast cannot have charges. Thankfully, the actual transformation works properly and correctly spawns 50 yeast.

iuse_transform::info needs to be updated to account for the actual amount of resulting items.

**Comment by IdleSol** [comment]
яйцо воробья = sparrow egg

``` DEBUG    : Tried to set charges for item яйцо воробья (свежее) that could not have them!

 FUNCTION : item::item(const itype*, time_point, int)
 FILE     : src/item.cpp
 LINE     : 318
 VERSION  : cdda-experimental-2024-04-16-1009 73b6cf7
```

**Comment by PatrikLundell** [comment]
Failed to replicate @IdleSol's terse case (no description of how to replicate it).
- Spawned 2 sparrow eggs and looked at them in various ways, with no error.
- Spawned clean water and an everburning torch (is this a vanilla item? Don't care, I just want a heat source).
- Boiled eggs, again with no error.

**Comment by IdleSol** [comment]
кусок заражённого мяса = chunk of tainted meat
```
DEBUG    : Tried to set charges for item кусок заражённого мяса (свежее) that could not have them!

 FUNCTION : item::item(const itype*, time_point, int)
 FILE     : src/item.cpp
 LINE     : 318
 VERSION  : cdda-experimental-2024-04-16-1009 73b6cf7
```

@PatrikLundell 
78th day of spring. I'm just trying to get to town. And I'm getting error messages. Eggs, butchery refuse, chunk of meat.

**Comment by IdleSol** [comment]
Try this save.
[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15026578/-trimmed.tar.gz)

1. Start driving your car straight down the road.
2. In two three moves later an error message pops up.

I got it again in 2 out of 2 tries.

**Comment by PatrikLundell** [comment]
I was able to repeat it in @IdleSol's save, following instructions.
I think this might be a separate issue from the bug report one. In this case the debugger indicates gibbing a monster results in chuncks with a quantity that is interpreted as charges.
mondeath.cpp operation scatter_chunks has this line: `const item chunk( chunk_name, calendar::turn, pile_size )`, where pile_size is charges.
The code would have to have two loops, where the outer loop iterates over chunk_amt, and the inner loop would loop over pile_size for each location you'd want a pile (and the chunk item probably not filling in any quantity (default -1), although 1 probably works).

**Comment by PatrikLundell** [comment]
I've made a PR for @IdleSol's gibbed monster case. However, there's a need for a separate bug report for each case encountered, as it's probably a case of multiple different places where charge removal wasn't performed properly (possibly because some charge generation method, like the direct item creation with charges, wasn't omitted from being investigated). Each bug report would need its own save and reproduction instructions.

**Comment by IdleSol** [comment]
But they have one thing in common, it all has to do with the function of change over time. The yeast must mature, the eggs must hatch, and the waste must disappear or spoil. I'm inclined to go to waste. Because I've had food spoil at my base, but no error message.

In fact, it's swapping one item for another when the timer expires.

I couldn't get stable reproduction in the new world.

**Comment by PatrikLundell** [comment]
You assume that's the cause (it wasn't in the gibbing case). I'm not saying it isn't, just that we shouldn't assume it's the same. Also, even if it may be the same mechanism, that doesn't necessarily mean it's the same code being responsible. If it's a matter of JSON definitions it's probably the same error in a number of different definitions.
