### ISSUE TITLE
faction camp food and hunting bug

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#72981]
### Describe the bug

hunting large animal, npc wielding axe perception 9, markshipman 3, being on the mission for 2 days, farther away or near npc return point, give no corpse.
asking npc to craft food in faction camp menu, being far away from the npc on the map there is no food no food, being near the npc return point there food.

### Attach save file

[fucking new world-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14961278/fucking.new.world-trimmed.tar.gz)

### Steps to reproduce

hunting large animal, npc wielding axe perception 9, markshipman 3, farther away or near npc return point, no corpse.
asking npc to craft food in faction camp menu, being far away from the npc on the map no food, being near the npc return point there food.

### Expected behavior

working properly

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3296 (22H2)
- Game Version: 9fc88ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    TropiCataclysm [tropicata],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
Your description is confusingly jumbled, and the steps to reproduction copy of it is rather useless.
However, if I've decoded it correctly, you claim that hunting and food crafting doesn't return any products, possibly that you may or may not have had the companion further away and/or closer to the PC when giving the order.

First, however, I should point out that at some time in the last ½ year or so the return product placement was changed from beneath the feet of the companion to some fixed location in the camp. I have no idea how the determination of that location is done, and whether it's tied to zones or anything else under the player's control.
I have no idea why the change was made, and only know about it because I was similarly confused when the products (in my case logs) suddenly ceased to show up under the companion's feet.

So, I'd suggest you look around in the camp (the camp tile only, i.e. not expansions, and only the Z level the camp is placed on) to see if you can find the "missing" products.

In my opinion the change was for the worse, and I think it would be better if a Return Product zone was introduced allowing the player to specify where returned products should be placed (bonus points if this zone could have parameters so you could have different products placed at different places, such as corpses on the butchering rack and logs at the same place at the wood zone). Default if no zone was defined would probably be the current mystery location.

**Comment by RenechCDDA** [comment]
I also am not understanding your description, here.

**Comment by blablase** [comment]
> I also am not understanding your description, here.

npc return point only means, the return of the npc when the you recall them

**Comment by blablase** [comment]
> Your description is confusingly jumbled, and the steps to reproduction copy of it is rather useless. However, if I've decoded it correctly, you claim that hunting and food crafting doesn't return any products, possibly that you may or may not have had the companion further away and/or closer to the PC when giving the order.
> 
> First, however, I should point out that at some time in the last ½ year or so the return product placement was changed from beneath the feet of the companion to some fixed location in the camp. I have no idea how the determination of that location is done, and whether it's tied to zones or anything else under the player's control. I have no idea why the change was made, and only know about it because I was similarly confused when the products (in my case logs) suddenly ceased to show up under the companion's feet.
> 
> So, I'd suggest you look around in the camp (the camp tile only, i.e. not expansions, and only the Z level the camp is placed on) to see if you can find the "missing" products.
> 
> In my opinion the change was for the worse, and I think it would be better if a Return Product zone was introduced allowing the player to specify where returned products should be placed (bonus points if this zone could have parameters so you could have different products placed at different places, such as corpses on the butchering rack and logs at the same place at the wood zone). Default if no zone was defined would probably be the current mystery location.

npc return point only means, the return of the npc when the you recall them

**Comment by blablase** [comment]
> Your description is confusingly jumbled, and the steps to reproduction copy of it is rather useless. However, if I've decoded it correctly, you claim that hunting and food crafting doesn't return any products, possibly that you may or may not have had the companion further away and/or closer to the PC when giving the order.
> 
> First, however, I should point out that at some time in the last ½ year or so the return product placement was changed from beneath the feet of the companion to some fixed location in the camp. I have no idea how the determination of that location is done, and whether it's tied to zones or anything else under the player's control. I have no idea why the change was made, and only know about it because I was similarly confused when the products (in my case logs) suddenly ceased to show up under the companion's feet.
> 
> So, I'd suggest you look around in the camp (the camp tile only, i.e. not expansions, and only the Z level the camp is placed on) to see if you can find the "missing" products.
> 
> In my opinion the change was for the worse, and I think it would be better if a Return Product zone was introduced allowing the player to specify where returned products should be placed (bonus points if this zone could have parameters so you could have different products placed at different places, such as corpses on the butchering rack and logs at the same place at the wood zone). Default if no zone was defined would probably be the current mystery location.

so basically when you near the npc return point and recall them, they do have the stuff that you asked them to craft appear on the ground.


when you're further away from that return point and ask them to return, they give nothing.

i also use distributes food in faction menu, and the 2nd one give no calories

**Comment by blablase** [comment]
> Your description is confusingly jumbled, and the steps to reproduction copy of it is rather useless. However, if I've decoded it correctly, you claim that hunting and food crafting doesn't return any products, possibly that you may or may not have had the companion further away and/or closer to the PC when giving the order.
> 
> First, however, I should point out that at some time in the last ½ year or so the return product placement was changed from beneath the feet of the companion to some fixed location in the camp. I have no idea how the determination of that location is done, and whether it's tied to zones or anything else under the player's control. I have no idea why the change was made, and only know about it because I was similarly confused when the products (in my case logs) suddenly ceased to show up under the companion's feet.
> 
> So, I'd suggest you look around in the camp (the camp tile only, i.e. not expansions, and only the Z level the camp is placed on) to see if you can find the "missing" products.
> 
> In my opinion the change was for the worse, and I think it would be better if a Return Product zone was introduced allowing the player to specify where returned products should be placed (bonus points if this zone could have parameters so you could have different products placed at different places, such as corpses on the butchering rack and logs at the same place at the wood zone). Default if no zone was defined would probably be the current mystery location.

me and my friend have this problem of no corpse being around the area, maybe they should drop somewhere in the zone, or keep the corpse in the inventory but i prefer the first option

**Comment by blablase** [comment]
> I also am not understanding your description, here.

npc return point only means, the return point of the npc when the you recall them

**Comment by PatrikLundell** [comment]
- Tested sending off a companion to hunt large game. Two corpses were dropped off at what I assume is the dropoff point.
- Moved away to the neighboring tile and teleported back to the bulletin board (while the companion was on the neighboring tile) and sent him off to hunt. Again corpses appeared at the same point.

**Comment by blablase** [comment]
> * Tested sending off a companion to hunt large game. Two corpses were dropped off at what I assume is the dropoff point.
> * Moved away to the neighboring tile and teleported back to the bulletin board (while the companion was on the neighboring tile) and sent him off to hunt. Again corpses appeared at the same point.

what about the asking him to craft jerky, last time i send him and recall him he didn't drop any bacon when i far away, even i use the bullet tin to distrube food, base camp food zone cover the whole house

**Comment by blablase** [comment]
> * Tested sending off a companion to hunt large game. Two corpses were dropped off at what I assume is the dropoff point.
> * Moved away to the neighboring tile and teleported back to the bulletin board (while the companion was on the neighboring tile) and sent him off to hunt. Again corpses appeared at the same point.

also did you set start point because i didn't, and when i near the npc drop point they did not have any corpse

**Comment by blablase** [comment]
i should take the screenshot
 of those step

**Comment by PatrikLundell** [comment]
No, I haven't tried crafting.

The camp food zone is irrelevant to where stuff is dropped. It's used for you to drop stuff on it to then be sent to the calorie store. Mine are typically singe tile zones next to the bulletin board.

I don't know what you mean by "set start point". I have covered the base with a storage zone, because you're prompted to create one when you first interact with the bulletin board. The only other zone I have in that camp is a camp food one (also prompted, as well as needed to provide calories for camp tasks).

**Comment by blablase** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/50eae928-6c2b-4e14-aff5-608665a8135a)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/8c0a4384-444c-4c37-b86f-b42e45f1af48)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/635d058e-03c7-42b6-bf67-1d86dfb2ecbb)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/076a2da3-bf77-470d-9e54-1847796d50b9)

**Comment by blablase** [comment]
> * Tested sending off a companion to hunt large game. Two corpses were dropped off at what I assume is the dropoff point.
> * Moved away to the neighboring tile and teleported back to the bulletin board (while the companion was on the neighboring tile) and sent him off to hunt. Again corpses appeared at the same point.

is the drop off point is like the spawn point when they return that they just drop them off their feet ?

**Comment by blablase** [comment]
i am using experimental

**Comment by blablase** [comment]
i did use both debug time change and waiting time and they both don't give me corpse

**Comment by blablase** [comment]
well actually they do drop off these corpse the same place where they also dropped the crafted food like last time but last time they spawned at that location, and only work when i near that spawn point, when i too far away and return the same place have no food in it, i was like somewhere 10 map title away,


![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/89435a9b-2d33-4786-aaa3-c64b3daf0e5b)

**Comment by blablase** [comment]
> No, I haven't tried crafting.
> 
> The camp food zone is irrelevant to where stuff is dropped. It's used for you to drop stuff on it to then be sent to the calorie store. Mine are typically singe tile zones next to the bulletin board.
> 
> I don't know what you mean by "set start point". I have covered the base with a storage zone, because you're prompted to create one when you first interact with the bulletin board. The only other zone I have in that camp is a camp food one (also prompted, as well as needed to provide calories for camp tasks).

no what i meant is use the food camp storage zone for the distributing food action

**Comment by PatrikLundell** [comment]
I loaded your save, hacked your companion to get 10 in all skills, sent him out to hunt, and he brought back a corpse dropped in the middle of the house (beside a human corpse).

I don't understand what you mean by being far away. You can only bring your companion back when interacting with the bulletin board, which is in the same overmap tile as the drop spot.

It's bad practice to try to cram multiple issues into the same bug report, because it's hard to keep track of things, and fixing one bug won't close the bug report.
I debug spawned 1000 pemmican, dropped them in the camp food zone, distributed them, and the stored content went up accordingly.
If you craft something and it doesn't add calories when dumped into the calorie store, first check that the food actually has calories in them. There have been cases in the past where food ended up with 0 calories due to bugs in the recipes.

**Comment by blablase** [comment]
> I loaded your save, hacked your companion to get 10 in all skills, sent him out to hunt, and he brought back a corpse dropped in the middle of the house (beside a human corpse).
> 
> I don't understand what you mean by being far away. You can only bring your companion back when interacting with the bulletin board, which is in the same overmap tile as the drop spot.
> 
> It's bad practice to try to cram multiple issues into the same bug report, because it's hard to keep track of things, and fixing one bug won't close the bug report. I debug spawned 1000 pemmican, dropped them in the camp food zone, distributed them, and the stored content went up accordingly. If you craft something and it doesn't add calories when dumped into the calorie store, first check that the food actually has calories in them. There have been cases in the past where food ended up with 0 calories due to bugs in the recipes.

i meant sending your companion to crafting not distributing, the distributing is only to test if those jerky is in the area, last time i done that it said 0 calories

**Comment by blablase** [comment]
> I loaded your save, hacked your companion to get 10 in all skills, sent him out to hunt, and he brought back a corpse dropped in the middle of the house (beside a human corpse).
> 
> I don't understand what you mean by being far away. You can only bring your companion back when interacting with the bulletin board, which is in the same overmap tile as the drop spot.
> 
> It's bad practice to try to cram multiple issues into the same bug report, because it's hard to keep track of things, and fixing one bug won't close the bug report. I debug spawned 1000 pemmican, dropped them in the camp food zone, distributed them, and the stored content went up accordingly. If you craft something and it doesn't add calories when dumped into the calorie store, first check that the food actually has calories in them. There have been cases in the past where food ended up with 0 calories due to bugs in the recipes.

maybe i just gonna give up in this problem

**Comment by blablase** [comment]
> GAH! Try to at least say that then!
> 
> Tried to spawn stuff needed to make meat jerky, set your companion to craft it, and it showed up at the drop location when the companion was recalled. I checked that it did contain calories and that the calories store increased when they were added.
> 
> So far I've failed to repeat any of your failures with your save.
> 
> * Hunting works
> * Crafting works
> * Adding stuff to the calorie store works.

and no i did not talking about adding calories to the camp did not bug, only those other 2 faction function did not work the calories is just to test if the jerky is there or not

**Comment by PatrikLundell** [comment]
After having guessed what you might mean with your half sentences leaving out most of the information I finally guessed that you might mean "Using a two-way radio to remotely call a companion who's conducting an activity and ask them to finish the activity does not result in any product being returned. There is nothing to be found when the PC returns to the camp."

That does indeed seem to fail for meat jerky production.
I only tried it with the PC outside of the reality bubble. If it also fails when a radio is used inside of the reality bubble (i.e. the PC is at the camp when calling) that should be mentioned by the report (some of what you typed might indicate that can be the case, or maybe not, it's hard to tell).

Please rewrite the report so it's legible (stating exactly what isn't working, including all relevant details) and an actual description of how to reproduce it (step by step list of exactly what needs to be done, including all relevant details so someone can actually repeat the steps).

It wouldn't hurt if English was used, rather than SMSish (i.e. using upper case letters where relevant, as well as punctuation).

**Comment by blablase** [comment]
> After having guessed what you might mean with your half sentences leaving out most of the information I finally guessed that you might mean "Using a two-way radio to remotely call a companion who's conducting an activity and ask them to finish the activity does not result in any product being returned. There is nothing to be found when the PC returns to the camp."
> 
> That does indeed seem to fail for meat jerky production. I only tried it with the PC outside of the reality bubble. If it also fails when a radio is used inside of the reality bubble (i.e. the PC is at the camp when calling) that should be mentioned by the report (some of what you typed might indicate that can be the case, or maybe not, it's hard to tell).
> 
> Please rewrite the report so it's legible (stating exactly what isn't working, including all relevant details) and an actual description of how to reproduce it (step by step list of exactly what needs to be done, including all relevant details so someone can actually repeat the steps).
> 
> It wouldn't hurt if English was used, rather than SMSish (i.e. using upper case letters where relevant, as well as punctuation).

no i am lazy as hell, and using these term as simple and quick as possible

**Comment by blablase** [comment]
> After having guessed what you might mean with your half sentences leaving out most of the information I finally guessed that you might mean "Using a two-way radio to remotely call a companion who's conducting an activity and ask them to finish the activity does not result in any product being returned. There is nothing to be found when the PC returns to the camp."
> 
> That does indeed seem to fail for meat jerky production. I only tried it with the PC outside of the reality bubble. If it also fails when a radio is used inside of the reality bubble (i.e. the PC is at the camp when calling) that should be mentioned by the report (some of what you typed might indicate that can be the case, or maybe not, it's hard to tell).
> 
> Please rewrite the report so it's legible (stating exactly what isn't working, including all relevant details) and an actual description of how to reproduce it (step by step list of exactly what needs to be done, including all relevant details so someone can actually repeat the steps).
> 
> It wouldn't hurt if English was used, rather than SMSish (i.e. using upper case letters where relevant, as well as punctuation).

https://www.youtube.com/watch?v=iaAoBH5rY78 this is my friend record

**Comment by blablase** [comment]
> After having guessed what you might mean with your half sentences leaving out most of the information I finally guessed that you might mean "Using a two-way radio to remotely call a companion who's conducting an activity and ask them to finish the activity does not result in any product being returned. There is nothing to be found when the PC returns to the camp."
> 
> That does indeed seem to fail for meat jerky production. I only tried it with the PC outside of the reality bubble. If it also fails when a radio is used inside of the reality bubble (i.e. the PC is at the camp when calling) that should be mentioned by the report (some of what you typed might indicate that can be the case, or maybe not, it's hard to tell).
> 
> Please rewrite the report so it's legible (stating exactly what isn't working, including all relevant details) and an actual description of how to reproduce it (step by step list of exactly what needs to be done, including all relevant details so someone can actually repeat the steps).
> 
> It wouldn't hurt if English was used, rather than SMSish (i.e. using upper case letters where relevant, as well as punctuation).

might gonna be like few more days because i am tired as hell
