### ISSUE TITLE
water purification tablet purify way more water than inteded

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#72991]
### Describe the bug

one water purification tablet purifies 60l of water in the metal tank for me

### Attach save file

[fucking.new.world-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14965258/fucking.new.world-trimmed.tar.gz)

### Steps to reproduce

one water purfication tablet, one 60l of water in a 60l metal tank

### Expected behavior

not cleaning that much water and only clean 250ml like it said

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3296 (22H2)
- Game Version: 9fc88ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    TropiCataclysm [tropicata],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Michael1993** [comment]
Duplicate.

See:
#69041
#67551
#71818
#71971
