### ISSUE TITLE
dev builds / windows / SDL /  full screen

### ISSUE THREAD

**Issue by mgrant24601** [CleverRaven/Cataclysm-DDA#7300]
First, a few notes in preface:

First, everything works normally on the stable version. I've tried a few of the different available dev builds currently posted, including the most and least recent currently up on http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/ (1363 - 1379). 

I've been trying (without success) to capture screenshots of the issue. Since I am able to take screenshots on the stable version I have to assume that the issue preventing me from taking screenshots is related. If this can't be reproduced by anyone else, I'll take pictures of the monitor with my phone if need be, but I don't want to spend any more time on this if someone who can diagnose the problem can reproduce it. 

There are two issues which I'm not 100% sure are related, but I'm going to describe them both here because are both only applicable in fullscreen mode. 

Issue 1: The last drawn frame is getting mixed in each time a new frame is drawn. This happens in the game and on the menus. I haven't been able to figure out exactly what's happening, because there are some things that aren't duplicated (for example, sprites don't trail or duplicate). The behavior does feel consistent but I've never done enough graphics programming to have more than intuitive feeling that there is some sort of consistent behavior. 

Alt-tabbing can also cause artifacts (although not usually much) from the GUI to be included. 

Issue 2: In full screen mode changing terminal width does not affect screen resolution selected when the game is run at full screen (it fills to the current resolution). I tend towards assuming that this may be unrelated but with graphics issues I would prefer not assume. 

Here are a couple of things that might help. 

![dxdiag](https://cloud.githubusercontent.com/assets/7013810/2749431/91753d76-c801-11e3-81d5-8fe8179ae40b.png)
![windows](https://cloud.githubusercontent.com/assets/7013810/2749432/917612dc-c801-11e3-82d5-b1910529d377.png)

Let me know if there's anything else I can do. I've tried to think of anything that might be useful without spending too much time on something that might be obvious to someone more familiar with graphics programming, but I'm willing to spend some more time on it if it can't be easily diagnosed.
##

**Comment by OzoneH3** [comment]
Related issue #6928
