### ISSUE TITLE
Crash with overlays

### ISSUE THREAD

**Issue by The-Silent-One** [CleverRaven/Cataclysm-DDA#73003]
### Describe the bug

The game freezes then crashes when talking to NPC or entering a vehicule. I run on experimental branch and had this issue on the last 1 month (ish) releases.I believe the issue is related to overlays and my graphics setup. 

I have linux opensuse tumbleweed, and UHD Graphics 630 & GeForce GTX 1050 Ti. 
Currently using prime to set the default mode to offload on boot, but the problem still persists when running with nvidia gpu (prime-run command)

### Attach save file

The crash.log + debug.log files:
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14968132/crash.zip)

Game save:
[Escape from Rossburg-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15069170/Escape.from.Rossburg-trimmed.tar.gz)

### Steps to reproduce

1. Talk to an NPC or Enter vehicule

### Expected behavior

Operate vehicules or return a handled error

### Versions and configuration

- OS : openSUSE Tumbleweed
- version: 20240409
- Game version: cdda-experimental-2024-04-12-2052 36578d7
- Graphics version: Tiles

**Comment by The-Silent-One** [comment]
any updates on this issue? it's still persistent

**Comment by NetSysFire** [comment]
You have not attached a save, only the log files. Try attaching your save because reproducing can be hard without a save in some cases.
Prepare the save so when someone loads your save to try and reproduce it, they only need to walk some steps in a single direction or so.

**Comment by The-Silent-One** [comment]
Update: I have attached my save file, even tho I believe this it's setup relevant and not attached to my current save, but alas.

**Comment by NetSysFire** [comment]
Can not reproduce. I loaded your save and went onto the tandem bike, no crash. There is no NPC anywhere I can see and spawning one in and speaking with them does not cause any crash.

**Comment by The-Silent-One** [comment]
> Can not reproduce. I loaded your save and went onto the tandem bike, no crash. There is no NPC anywhere I can see and spawning one in and speaking with them does not cause any crash.

Thus proving my point that it's setup related not save related.

**Comment by NetSysFire** [comment]
There should be debugging symbols in our official builds. Run the game in gdb and do a full backtrace and share the trace.

**Comment by The-Silent-One** [comment]
I run the game (titles version) in gdb, when I enter a vehicule the game freezes (not crashes) and the only message I find in console is this:

```
cataclysm-tiles: src/catacharset.cpp:350: std::wstring utf8_to_wstr(const string&): Assertion `sz != static_cast<size_t>( -1 )' failed.
```

**Comment by NetSysFire** [comment]
You must thread apply all bt full

**Comment by The-Silent-One** [comment]
No difference
```
[New Thread 0x7ffff60006c0 (LWP 6899)]
[New Thread 0x7fffeb6006c0 (LWP 6921)]
[New Thread 0x7fffeac006c0 (LWP 6922)]
[New Thread 0x7fffea2006c0 (LWP 6923)]
[New Thread 0x7fffe98006c0 (LWP 6924)]
[Thread 0x7fffe98006c0 (LWP 6924) exited]
[Thread 0x7fffea2006c0 (LWP 6923) exited]
[New Thread 0x7fffea2006c0 (LWP 6926)]
[New Thread 0x7fffe98006c0 (LWP 6927)]
[New Thread 0x7fffe2e006c0 (LWP 6928)]
[New Thread 0x7ffff52c56c0 (LWP 6929)]
[New Thread 0x7fffe24006c0 (LWP 6930)]
cataclysm-tiles: src/catacharset.cpp:350: std::wstring utf8_to_wstr(const string&): Assertion `sz != static_cast<size_t>( -1 )' failed.
```

**Comment by katemonster33** [comment]
> > Can not reproduce. I loaded your save and went onto the tandem bike, no crash. There is no NPC anywhere I can see and spawning one in and speaking with them does not cause any crash.
> 
> Thus proving my point that it's setup related not save related.

Can you zip up your config directory and send that too? If it's setup related that could help others reproduce

**Comment by TheCYPER** [comment]
This problem 
`cataclysm-tiles: src/catacharset.cpp:350: std::wstring utf8_to_wstr(const string&): Assertion sz != static_cast<size_t>( -1 )' failed.`
Appears to me and some other guys to an it seems to be related to [Locale settings](https://wiki.archlinux.org/title/Locale)
https://github.com/CleverRaven/Cataclysm-DDA/issues/72500
https://github.com/CleverRaven/Cataclysm-DDA/issues/68558

**Comment by The-Silent-One** [comment]
> This problem `cataclysm-tiles: src/catacharset.cpp:350: std::wstring utf8_to_wstr(const string&): Assertion sz != static_cast<size_t>( -1 )' failed.` Appears to me and some other guys to an it seems to be related to [Locale settings](https://wiki.archlinux.org/title/Locale) #72500 #68558

After pointing this out, I figured out that there was something that keeps overwriting my locale settings and setting
`LC_TIME="en_IO.UTF-8"` which breaks everything.
I couldn't find the source so I brute forced it by greping everything in my home directory with 
```
find . -type f -print0 | xargs -0 grep LC_TIME= 2>/dev/null
```

Found the culprit, which this file `~/.config/plasma-localerc` and deleting it fixed everything.
Thanks @TheCYPER for the lead. I'm leaving this message incase someone encountered the same problem as me.

**Comment by TheCYPER** [comment]
```
mac@PercydeMacBook-Air ~> locale
LANG="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_ALL=
```
This is my current locale setting on my mac and I'm still having this problem I mention. 
I know is assertion fail related to locale setting since I see many guys having the same issue.
However, after I see 350 in catacharset.cpp
```c
std::wstring utf8_to_wstr( const std::string &str )
{
#if defined(_WIN32)
    int sz = MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, nullptr, 0 ) + 1;
    std::wstring wstr( sz, '\0' );
    MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, wstr.data(), sz );
    strip_trailing_nulls( wstr );
    return wstr;
#else
    std::size_t sz = std::mbstowcs( nullptr, str.c_str(), 0 );     # Using mbstowcs to get sz
    cata_assert( sz != static_cast<size_t>( -1 ) );                    # this one, line 350
    std::wstring wstr( sz + 1, '\0' );
    [[maybe_unused]] const size_t converted = std::mbstowcs( wstr.data(), str.c_str(), sz );
    cata_assert( converted == sz );
    strip_trailing_nulls( wstr );
    return wstr;
#endif
}
```
This should be a problem with `mbstowcs` function returning a -1, which is a problem with C's function
Thus, 
* How is this related to my own locale setting
* How could I change my settings to make things work on my osx, since many command is not avalible on osx and my main language is chinese
