### ISSUE TITLE
ImGui doesn't respect font settings

### ISSUE THREAD

**Issue by DSeyka** [CleverRaven/Cataclysm-DDA#73019]
### Describe the bug

If you change your font settings via data/config/fonts.json, ImGui still uses what I assume is the default Terminus.ttf font.

My fonts.json file:
`{
    "typeface": [
        "data/font/FantasqueSansMono-Bold.ttf",
        "data/font/Terminus.ttf",
        "data/font/unifont.ttf"
    ],
    "map_typeface": [
        "data/font/Terminus.ttf",
        "data/font/unifont.ttf"
    ],
    "overmap_typeface": [
        "data/font/Terminus.ttf",
        "data/font/unifont.ttf"
    ]
}`

### Attach save file

Will provide one if needed, but I'm pretty sure it's unnecessary in this case.

### Steps to reproduce

1. Change your typeface font in data/config/fonts.json
2. Launch the game, make sure old UI uses the defined font
3. Open keybindings screen, note that default font is used instead of defined one

### Expected behavior

I expected MyGui to use the typeface font defined in data/config/fonts.json

### Screenshots

Comparison between old and new UI windows:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/66876732/1aa94068-fa23-4ad1-8049-2df0095fad19)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/66876732/c0d15662-a8f7-410a-a99d-53d58c302364)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: cdda-experimental-2024-04-14-0520 ddc82e2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14969893/debug.log)
No crash, but here's my debug.log file just in case.

**Comment by alef** [comment]
Problems lays [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_imgui.cpp#L264) where calling `ensure_unifont_loaded()` make sure the *only* `unifont.ttf` is used by ImGui
