### ISSUE TITLE
Shotgun speedloader doesn't work

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#73018]
### Describe the bug

The current shotgun speedloader doesn't work, the purpose of a speedloader is supposed to be to be able to quickly load a weapon at once, but as it currently stands, the speedloader itself can be loaded at once, but the weapon can't be loaded at once using the speedloader.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Allows shotgun to be loaded at once by using a speedloader.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-04-04-0825 15b95a2 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    减缓真菌增殖 [no_fungal_growth]
]

**Comment by Uwuewsky** [comment]
Dont you need to install speedloader chute gunmod first?

`A metal ramp that is installed near a shotgun's feeding port to index speedloader tubes.`

**Comment by Rocket-F-1024** [comment]
> Dont you need to install speedloader chute gunmod first?
> 
> `A metal ramp that is installed near a shotgun's feeding port to index speedloader tubes.`

I have test it and it doesn't work.

**Comment by oosyrag** [comment]
Shotgun speedloaders have never worked iirc, despite many attempts to address it. See #52595.

I think other speedloaders have had fixes applied but shotguns may still be broken.

**Comment by Rocket-F-1024** [comment]
> Shotgun speedloaders have never worked iirc, despite many attempts to address it. See #52595.
> 
> I think other speedloaders have had fixes applied but shotguns may still be broken.

I think this is essentially a problem due to the way shotgun loading is implemented, something I mentioned in another 
 issuehttps://github.com/CleverRaven/Cataclysm-DDA/issues/73012.

**Comment by osuphobia** [comment]
Managed to fix it.

Gun/magazine needs to have allowed_speedloaders defined in pocket_data to use speedloader.
For example, this is the pocket_data of .22 caliber revolver:
```
    "pocket_data": [
      {
        "pocket_type": "MAGAZINE",
        "rigid": true,
        "ammo_restriction": { "22": 8 },
        "allowed_speedloaders": [ "22_speedloader8" ]
      }
    ],
```
For the shotguns, they don't have it defined, and are expected to get the ability by installing speedloader chute gunmod.
However, speedloader chute has magazine_adaptor defined, but it doesn't change anything for guns with pocket_type MAGAZINE.
Instead, we need to use pocket_mods to alters the original pockets of the weapon.
```
    "pocket_mods": [
      {
        "pocket_type": "MAGAZINE",
        "rigid": true,
        "ammo_restriction": { "shot": 8 },
        "allowed_speedloaders": [ "shot_speedloader6", "shot_speedloader8" ]
      }
    ],
```
Removed magazine_adaptor from speedloader chute and defined pocket_mods as above, then it works as expected.
<img width="912" alt="12524536" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/f43d04da-f63f-40fd-8a88-36efe704529e">
<img width="213" alt="65165" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/288ac38f-ceab-4530-ae4d-559906719a2a">

**Comment by osuphobia** [comment]
Well, it did not totally fixed this issue.
Firstly, we need to modify activity_actor.cpp so that we can get the right msg when reloading shotguns with speedloader.
Secondly, since the pocket_data is changed, if the gun is loaded, ammos in it will be deleted.
