### ISSUE TITLE
Sky_island is unable to bring back all items within a room.

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#73013]
### Is your feature request related to a problem? Please describe.

I have already set in the difficulty options to bring back items from the entire room by paying fragments, but when I was preparing to return to the island, I couldn’t do it. I had enough fragments on me, but the obelisk still prompted me with ‘selfonly’ and I couldn’t bring back my items correctly.

### Solution you would like.

fix this bug?Or maybe I’m doing it wrong, could you please correct me?

**Comment by IoIqq** [comment]
Even when I hold the fragments needed for payment in my hand, it still prompts me with ‘selfonly’

**Comment by Standing-Storm** [comment]
When you say fragments, do you mean warp shards? There's a specific item you need to craft with them that enables the "bring everything home" behavior, you don't do it with just raw warp shards

**Comment by RenechCDDA** [comment]
In the future please use the bug report template if you're reporting a bug.

**Comment by IoIqq** [comment]
> When you say fragments, do you mean warp shards? There's a specific item you need to craft with them that enables the "bring everything home" behavior, you don't do it with just raw warp shards

yes,I 'm mean warp shards,After selecting the difficulty, do I need to craft an item in order to bring back all the items in the room?

**Comment by IoIqq** [comment]
> In the future please use the bug report template if you're reporting a bug.

ok,I will,sorry
