### ISSUE TITLE
Anvil has no Anvil Quality

### ISSUE THREAD

**Issue by davidwgoodall** [CleverRaven/Cataclysm-DDA#73010]
### Describe the bug

Just found an anvil in a gun store & could not use it, on (E)xamining it has not Anvil Quality?
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/166970338/a0cbb78b-a47b-4cb2-a6c0-83a0104a568b)

### Attach save file

[Southgate-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14969407/Southgate-trimmed.tar.gz)

### Steps to reproduce

Try & craft an item (heavy Sledge hammer) that requires Anvil level 3
Or examine Anvil, no Anvil Quality/Level is shown

### Expected behavior

I expect to be able to use the anvil as an anvil

### Versions and configuration

OS: Win 10
Version: cdda-windows-tiles-sounds-x64-2024-03-30-2128
Mods 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/166970338/f140bda8-2c6e-4725-990f-70aa25240f3e)

**Comment by gettingusedto** [comment]
Anvils these days must be placed down through the construction menu as a furniture.

**Comment by davidwgoodall** [comment]
Ah, thanks, might be worth adding that to the description Anvil quality 3 (must be placed to use)?

**Comment by davidwgoodall** [comment]
Closing

**Comment by RenechCDDA** [comment]
> Ah, thanks, might be worth adding that to the description Anvil quality 3 (must be placed to use)?

"Once installed, it can be used in most metalworking fabrication recipes."
