### ISSUE TITLE
Sky_island.After returning, the non-reset of the map results in performance strain.

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#73014]
### Is your feature request related to a problem? Please describe.

After multiple landings, I realized that I might repeatedly touch down at the same location. Due to the brief duration spent in each such area, every landing effectively uncovers a fresh chunk of the world, thereby incrementally increasing the computational load on my game.

### Solution you would like.

Is there a way to delete the map on the ground every time I return to the sky island?

**Comment by IoIqq** [comment]
Is the sky_island still updating?

**Comment by Procyonae** [comment]
Adding sky island to the title would help it get noticed by the appropriate peeps.
There's no current infrastructure to improve that, ideally someone will pickup #66454 which with alot of work would allow for a solution to this. Sky Island's main dev isn't active atm but that's not to say it's not being updated.
