### ISSUE TITLE
Android add option for "Force fullscreen" in options

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#73017]
### Is your feature request related to a problem? Please describe.

The toggle for "Force fullscreen" is not available without clearing data cache or reinstalling the game.

### Solution you would like.

Add the option for "Force fullscreen" to Android settings.

### Additional context

Force fullscreen is the only prompted setting on first install that can't be changed in game afterwards. The others, which include "Trap Back button", "Use native Android UI menus", and "Software rendering" all have entries in options.

**Comment by AdityaMH** [comment]
No want wanted this
