### ISSUE TITLE
Android "Trap Back Button" option is nonfunctional

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#73016]
### Describe the bug

Setting "Trap Back button" to false does not do anything. 

### Attach save file

N/A

### Steps to reproduce

Set "Trap Back button" to false. Restart. Hit back button, keyboard comes up and app does not close.

### Expected behavior

Back should back out of the app as described in the setting description.

(Or better yet trapped as the "ESC" key to cancel, but that's another issue)

### Versions and configuration

OS: Android
OS Version: Manufacturer: OnePlus; Model: HD1900; Release: 12; Incremental: Q.202303230244;
Game Version: cdda-experimental-2024-04-07-0018 84dae0b [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
  Dark Days Ahead [dda],
  Disable NPC Needs [no_npc_food],
  Portal Storms Ignore NPCs [personal_portal_storms],
  Slowdown Fungal Growth [no_fungal_growth]

**Comment by ZhilkinSerg** [comment]
> Back should back out of the app as described in the setting description.

Setting description actually does not say what would happen if setting is set to `false` and only implies what happens: "If true, the back button will NOT back out of the app and will be passed to the application as SDL_SCANCODE_AC_BACK"

When the button is not trapped by SDL the behavior is not controlled by the CDDA anymore. That option was added as some devices had back-out-of-the-app behavior on Back press.

**Comment by oosyrag** [comment]
Hmmm... I would still expect it to back out of the app though. It seems strange that the keyboard comes up anyway? That's not normal behavior for a back button.

**Comment by katemonster33** [comment]
I believe when we say we are "trapping" the back button, it means that Android will not process the back button press at the system level, only CDDA processes it.
