### ISSUE TITLE
ImGui UI presentation

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#73015]
### Is your feature request related to a problem? Please describe.

ImGui elements are not visually consistent with the rest of the game. 
![oldkeybinds](https://github.com/CleverRaven/Cataclysm-DDA/assets/26992604/7335ef84-3de3-48ad-8d04-1556fb5d8894)
![imguikeybinds](https://github.com/CleverRaven/Cataclysm-DDA/assets/26992604/14cc69d7-70e5-4209-a7a2-c05f593a89e5)
![olddialog](https://github.com/CleverRaven/Cataclysm-DDA/assets/26992604/0da17401-95ae-47f8-b6e0-ff5631d90f4d)
![imguidialog](https://github.com/CleverRaven/Cataclysm-DDA/assets/26992604/bb6fd263-f6c0-4de7-a2fd-8af987bdab75)

### Solution you would like.

- Window title - Remove background color, center text, highlight text color
- Remove/hide "X" to close window
- Remove background color color local GUI controls, highlight hotkey color
- Remove filter textinput background color
- Remove border or change to grey for scrollable area border
- Change scrollbar color to blue
- Remove button background color and outline color for yes/no dialog. Add background color on hover/active.

### Describe alternatives you have considered.

Underline the textinput field if possible, which would be more like how filters are displayed elsewhere. Or change background to darkgrey so it does not clash.

Leave the "X" to close window for mouse support. I don't think it fits with the aesthetic of the game though.

For the yes/no dialog buttons, I think leaving the border and removing the background for active/hover might look nice too.

### Additional context

Also just noticed the characters are not sharp. Is there some sort of anti aliasing or scaling going on that could be disabled? They're pretty crisp in the yes/no dialog though....

**Comment by RenechCDDA** [comment]
Any visual differences will be resolved as the old UI is replaced wholesale with imGUI.

**Comment by DSeyka** [comment]
Just to make sure, will it be possible to use custom fonts with imGui? Right now it doesn't seem to respect any font settings. Or should there be a separate issue for that?

**Comment by oosyrag** [comment]
Make a separate issue.
