### ISSUE TITLE
ImGui - ImTui support on tiled builds

### ISSUE THREAD

**Issue by katemonster33** [CleverRaven/Cataclysm-DDA#73011]
### Is your feature request related to a problem? Please describe.

Right now, ImGui drawing logic is split into two very different implementations, SDL and ImTui. In order to test ImTui we need to load up a curses build on Linux and we are running low on devs willing/able to do this.

### Solution you would like.

Rework ImTui to hook it into CDDA's existing curses-SDL bridge logic. This would solve two issues for us, one being that we could appease users who want the UI to look similar to how it did, and two, we could test ImTui without needing people to build curses on Linux. 

This would be an option under the options menu, something like "ImGui backend - SDL/ImTui"

### Describe alternatives you have considered.

Resurrect the Windows pdcurses-based non-tiled build. I have no idea if ImTui even works with pdcurses.

**Comment by Qrox** [comment]
The curses version can be built with ImTUI and ncurses using MSYS2 on Windows, although I'm not sure if it works anymore with ImGUI added.

**Comment by katemonster33** [comment]
> Which build are you refering to? The MSYS2 build I mentioned above and the obsolete wincurse port both use the ncurses API. In fact the ImTUI source code seems to be using pdcurses.

 I was talking about wincurse, I thought it used pdcurses, maybe not
