### ISSUE TITLE
Bullet loading improvement

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#73012]
### Is your feature request related to a problem? Please describe.

It doesn't make sense that when you're loading rounds into a magazine, if it's interrupted, then the magazine will go back to the way it was before it was loaded. After all, you're only interrupted from the loading process, the rounds don't spontaneously return from the magazine.
The current speedloader doesn't work, the purpose of a speedloader is supposed to be to be able to quickly load a weapon at once, but as it currently stands, the speedloader itself can be loaded at once, but the weapon can't be loaded at once using the speedloader.
And shotguns and revolvers can only be loaded one round at a time at the moment, but magazines, which are also loaded one round at a time, can be loaded all at once.

### Solution you would like.

Allows weapons to be loaded at once using a speedloader.
Make it so that all guns and magazines can choose to have only one round loaded or all loaded when loading.
If interrupted while loading, determine how many rounds were loaded in total based on the time of the interruption, rather than going back to the state before loading.

**Comment by RenechCDDA** [comment]
>The current speedloader for shotguns also doesn't work
>...
>Get the shotgun's speedloader back to normal and functioning.

Please make separate issues for separate issues, do not lump them together. The ability for people to find bug reports inside suggestions is basically nil.

**Comment by Rocket-F-1024** [comment]
> > The current speedloader for shotguns also doesn't work
> > ...
> > Get the shotgun's speedloader back to normal and functioning.
> 
> Please make separate issues for separate issues, do not lump them together. The ability for people to find bug reports inside suggestions is basically nil.

I just looked into the speedloader again and realized that the problem is not just caused by a bug, but by the way the feature is implemented itself. (The revolver's speedloader also has problems, but that's not due to a bug but to the way it's implemented.) I think it's better to solve the problem all together.

**Comment by Rocket-F-1024** [comment]
> > The current speedloader for shotguns also doesn't work
> > ...
> > Get the shotgun's speedloader back to normal and functioning.
> 
> Please make separate issues for separate issues, do not lump them together. The ability for people to find bug reports inside suggestions is basically nil.

OK, I've split its bug content and opened a new issue.
https://github.com/CleverRaven/Cataclysm-DDA/issues/73018
