### ISSUE TITLE
rendering vehicles while on z-level >1 causes errors

### ISSUE THREAD

**Issue by mischief** [CleverRaven/Cataclysm-DDA#73029]
### Describe the bug

when a vehicle is nearby and the character goes up a z level, some errors are produced:

```
15:58:44.908 ERROR : src/vehicle_display.cpp:64 [vpart_display vehicle::get_display_of_tile(const point&, bool, bool, bool, bool) const] no display part at mount (-5, 3)
```

reproducing this once with an ambulance produces ~50 errors.

### Attach save file

N/A

### Steps to reproduce

go to a radio tower with an ambulance nearby, and go up the tower one level

or drive up a bridge.

### Expected behavior

no errors.

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/1487996/32fdd267-6829-4548-b059-c94454564cc5

### Versions and configuration

gentoo, xterm, with cdda-experimental-2024-04-14-2000, built with `make -j32 LOCALIZE=0 DYNAMIC_LINKING=1 ASTYLE=0 LINTJSON=0 TESTS=0 HEADERPOPULARITY=1 RELEASE=1`

### Additional context

on my system any error like this is extremely noticable, because addr2line is invoked for a backtrace and it creates a very noticable delay in the game (~4-8 seconds), but i suppose that's fixable by turning off backtraces.

```
 An error has occurred!  Written below is the error report:
 -----------------------------------------------------------
 DEBUG    : no display part at mount (-2, -1)

 FUNCTION : vpart_display vehicle::get_display_of_tile(const point&, bool, bool, bool, bool) const
 FILE     : src/vehicle_display.cpp
 LINE     : 64
 VERSION  : cdda-experimental-2024-04-14-2000 27164690b2
 -----------------------------------------------------------
 See ./config/debug.log for a full stack backtrace
 Press space bar to continue the game.
 Press I (or i) to also ignore this particular message in the future.
```

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14972507/debug.log)

**Comment by NetSysFire** [comment]
Can reproduce. So far on curses only.
