### ISSUE TITLE
Keyboard on android always pops up with text capitalized, android shortcut bar also gets blacked out. 

### ISSUE THREAD

**Issue by prestushood** [CleverRaven/Cataclysm-DDA#73039]
### Describe the bug

1. Whenever bringing up the keyboard while playing on Android, it always capitalizes the first letter, a behaviour you would expect in a chat app like discord or whatsapp. This messes up muscular memory and add 2 extra strokes for Android players whenever they need to type a unbinded shortcut. Also whenever using a seach function, you need to press backspace multiple times so keystrokes can work. 

2. Whenever opening CDDA through Android, shortcut bars are blanked after a save is loaded (or created). You can work around that by repeately pressing back button or any key to restore it, but its annoying and messes up with shortcut order. 

### Attach save file

N/A

### Steps to reproduce

1. Just press Android Back button to bring up the keyboard and it will come with first letter capitalized
![Screenshot_2024-04-14-11-54-36-495_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/45672754/7500423e-1691-436c-a710-cfc2a40649f9)

2. Just load any save on most recent experimental version and the shortcut bar should appear blanked. 
![Screenshot_2024-04-14-11-54-20-795_com cleverraven cataclysmdda experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/45672754/9f721b30-31e3-4107-8f4d-06d19fa94126)

### Expected behavior

Screenshots are from 0.G

1. Keyboard is supposed to open uncapitalized 
![Screenshot_2024-04-14-12-06-58-696_com cleverraven cataclysmdda](https://github.com/CleverRaven/Cataclysm-DDA/assets/45672754/9abb1176-04c8-443e-a86a-cf92744f8a9e)

2. Shortcut bar is supposed to load shortcuts normally after loading a save
![Screenshot_2024-04-14-12-06-51-835_com cleverraven cataclysmdda](https://github.com/CleverRaven/Cataclysm-DDA/assets/45672754/5a7c2f11-c382-41cb-9e09-dd912b049a02)

### Versions and configuration

OS: Android 12 / MIUI 13.0.3 Stable
Game version: cdda-android-x64-2024-04-14-0749.apk
Graphics Version: Tiles
Game Language: English [en]

**Comment by prestushood** [comment]
Forgot to add but the keyboard im using on Android is Microsoft SwiftKey. I think its important because i heard people using other keyboards like Hacker Keyboard not being able to reproduce it

**Comment by ZhilkinSerg** [comment]
This might be keyboard app setting and/or something related to different SDL versions used.

**Comment by prestushood** [comment]
Cant be the keyboard app if the issue only popped up once i upgraded my experimental from 0.H candidate to the 2024-04-14-0749 version. Also, from the screenshots, you can see it working as intended in older versions
