### ISSUE TITLE
Out of Breath sounds do not play when you reach low stamina

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#73038]
### Describe the bug

Out of Breath sounds do not play when you reach the treshholds for fatigue low\med\high.
This has been happening with the latest couple of experimental builds.

### Attach save file

[Minden-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14974693/Minden-trimmed.tar.gz)

### Steps to reproduce

Install a build with sound enabled.
I used cdda-linux-tiles-sounds-x64-2024-04-15-0051.
I also tested a wine run of cdda-windows-tiles-sounds-x64-2024-04-15-0051.zip with same issue.

Check the soundpack is CC-Sounds, or soundpack with fatigue sounds.
I also experienced the same issue with Otopack.

Make a character\load a save - have him run and notice there are no sound that starts playing when you reach fatigue tresholds.

The latest experimental i can personally confirm had out of breath sounds playing on low stamina is:
cdda-linux-tiles-sounds-x64-2024-04-02-0446
This build still plays these sounds as expected.

### Expected behavior

I would have expected the sound to play when the stamina reaches low enough treshholds.

### Versions and configuration

- OS: Linux
    - OS Version: Fedora 39
- Game Version: cdda-experimental-2024-04-15-0051 065774f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I cannot say if the issue starts right after cdda-linux-tiles-sounds-x64-2024-04-02-0446 or not.
There may be other sounds also not playing, but in that case i don't notice it enough.

**Comment by anoobindisguise** [comment]
Do you have ambient sounds on?

**Comment by EternalLaughter** [comment]
> Do you have ambient sounds on?

Yepp.

**Comment by EternalLaughter** [comment]
So since no one has commented on this, i'm assuming this is a strange my config issue, and for everyone else these sound plays fine?

**Comment by Metalsoul212** [comment]
I have noticed this too, however I've only recently picked the game back up a couple days ago. Using @ soundpack and I have zero indication of low stamina.

**Comment by Xenbiotic** [comment]
I'm also having this same problem.
![gtr565y6](https://github.com/CleverRaven/Cataclysm-DDA/assets/67262624/bcb48359-2717-4dd6-acb7-8870c18a0b08)

**Comment by NetSysFire** [comment]
Do you know which exact build has broken this behavior? That will likely speed up the fix enormously.

**Comment by EternalLaughter** [comment]
> Do you know which exact build has broken this behavior? That will likely speed up the fix enormously.

Well as mentioned, the latest confirmed build i know of it working is:
cdda-linux-tiles-sounds-x64-2024-04-02-0446
I checked the builds i've played, and it's also failing on
cdda-linux-tiles-sounds-x64-2024-04-11-1603

reading the changelogs, and testing the builds likely, it seems the issue starts with:
cdda-linux-tiles-sounds-x64-2024-04-05-0221

My 10 cents would be on #72708
