### ISSUE TITLE
No cattail jelly in bag after quest.

### ISSUE THREAD

**Issue by DonOfSandiego** [CleverRaven/Cataclysm-DDA#73046]
### Describe the bug

When completing the mission to pick cattails and learn the cattail jelly recipe, the quest-giver attempts to give you a zipper bag full of cattail jelly, but the container is too small to contain it, so the game throws an error.

After the mission, your only reward is an empty zipper bag (and the recipe to make cattail jelly).

### Attach save file

N/A

### Steps to reproduce

1.) Evacuee start

2.) Keep making saves until you get the mission to pick 80 cattails from your starting companion

3.) Complete the mission

### Expected behavior

You expect to receive some portion of the cattail jelly in the zipper bag, instead of an empty one.

### Versions and configuration

- OS: Windows 10
- Version: d6ec466

### Additional context

 DEBUG    : tried to put an item (cattail_jelly) count (13) in a container (bag_zipper) that cannot contain it: pocket unacceptable because item too big

 FUNCTION : put_in
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1512
 VERSION  : d6ec466

**Comment by RenechCDDA** [comment]
Known issue, this is fixed on experimental. Thanks for the report, but there's nothing more to do here. Look forward to having the quest work properly in 0.H (when it releases) or experimental if you choose to play it.
