### ISSUE TITLE
imgui does not clean up the screen when the game crashes

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#73049]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59517351/afbb6921-cdee-4bc4-a149-9fe5beb3c63e)

### Attach save file

n/a

### Steps to reproduce

1. Start any game in curses.
2. Make the game crash via any means, but just try doing so with the deliberate crash in the debug menu

### Expected behavior

It does not do that.

Again confirmed because someone told me about this bug without reporting it for themselves and it turns out I can reproduce.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a;
- Game Version: cdda-experimental-2024-04-14-2000 2716469 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by katemonster33** [comment]
there's only so much we can do to reset the state of the terminal on a crash. I will add a line in crash.cpp to turn off mouse pointer events as part of #73164 but even then I can't guarantee the results.
