### ISSUE TITLE
The imgui popup windows are slower than "old" windows

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#73052]
### Describe the bug

The imgui windows are considerably slower than the normal popup windows

### Attach save file

[Highcliff.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14985986/Highcliff.zip)

### Steps to reproduce

1. Start the game
2. Load the save
3. Make a popup window appear (like trying to cancel an auto travel or trying to "B"utcher an item. I recommend the auto-travel since its what i showed to the vid.)

### Expected behavior

For this lag? delay?? Framerate??? Issue to not be happening

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/a70fc165-e805-4f79-816c-5a366b9394cc

You can see how long it takes for my actions to register

### Versions and configuration

Android, didnt touch anything related to imgur

### Additional context

Not sure if maybe its my phone, but the imgur windows are CERTAINLY slower than the normal windows for me

**Comment by Srcwya** [comment]
Small correction: the butcher menu uses the old type of popup window, so it runs normally.
But "butchering" clothes opens the new imgur menu, which has that issue.

Heres a video showing how much faster the normal window is https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/5928081a-8535-4c3c-a020-c89f6ad629b2

**Comment by nornagon** [comment]
I'm seeing this on macOS too:

https://github.com/CleverRaven/Cataclysm-DDA/assets/172800/92611f59-bc06-440b-a56e-96483c60fa1b

around 0:05, I see:
frame n: "S" key is pressed
frame n+5: "S" appears in input
frame n+8: list view changes

and similarly for pressing "o" shortly after that. (I count n+4 for "o" to appear, n+8 again for the list view to change.)

comparing to input lag in the "V" screen, at 0:11:
frame n: Down arrow pressed
frame n+3: view is updated 

this is at a locally built version from 9137309fc, macOS Sonoma 14.3, on an M3 Max MacBook Pro

**Comment by Srcwya** [comment]
So like i also discovered this


https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/c56bd048-9898-459c-af13-4c82e04f3897
Yeah.. i cant even describe this

**Comment by AnotherSeawhite** [comment]
I've found out that the performance issue on mobile is (probably) related to touchscreen stuff. Using a keyboard and/or mouse didn't make any delay. https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/0b38b021-b793-44f3-97a1-58d7a2ed1b71

**Comment by katemonster33** [comment]
please retest on latest experimental, #73180 may have fixed this. https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-04-22-1537

**Comment by Srcwya** [comment]
> please retest on latest experimental, #73180 may have fixed this. https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-04-22-1537

https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/068bc289-6a8a-44a6-8a79-6dab4bbfb002

Just updated, same save

**Comment by NetSysFire** [comment]
>please retest on latest experimental, https://github.com/CleverRaven/Cataclysm-DDA/pull/73180 may have fixed this.

It is much, much better now, at least for text entry. I just tested the current experimental and the one before that to compare.

I also think the imgui window updates faster now since you could see it redrawing. You still can but it is not that obvious now. Closing as fixed.

**Comment by AnotherSeawhite** [comment]
I've tested, and the issue with ImGui hampering the performance in Android is still there.

**Comment by NetSysFire** [comment]
This might be a different issue specific to android. I recommend creating a separate issue since you said so yourself its probably touchscreen stuff.
