### ISSUE TITLE
imGUI: regression in not being able to switch options with capital letters

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#73058]
### Describe the bug

Previously, when closing the game you could press ``Y`` to switch to ``Yes`` and ``N`` to switch to ``No``. This is no longer possible.

### Attach save file

[Vanilla-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14995324/Vanilla-trimmed.tar.gz)

### Steps to reproduce

1. Try to ``S``ave and Quit
2. Press ``Y`` to try and switch the chosen option to ``Yes``
3. Fail
4. Use arrow keys like a madman

### Expected behavior

I don't expect regressions. I mean, I do, but I'd like to see it fixed anyway.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/f57bef70-e67e-4848-9162-7e3112afc2d2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 0.G-8844-g14fd9eaaf9-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Karol1223** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/046a3037-384e-4bdc-8d32-56747a87e356)
Using terminals like this one appears to be impossible entirely. Not sure why, given these don't use imGUI...

**Comment by esotericist** [comment]
to elaborate a little on this, in settings/interface/accessibility, there's a setting:
"force capital/modified letters in prompts":
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1569754/545351e6-a36d-4721-8414-bea248ef522a)

if a choice is being made to drop this functionality, it should be explicit, and we shouldn't have a setting present that claims that functionality.

(i personally would like to keep it, though)

**Comment by Brambor** [comment]
I understand this to be solved by #73420

**Comment by Karol1223** [comment]
It is not done. The PR was done due to a misunderstanding between what this issue highlights and solves an entirely unrelated bug.

**Comment by katemonster33** [comment]
since @esotericist 's view of the issue was wrong then I no longer believe this is confirmed. I tried a fresh experimental build from today and compared it to 0.G. On either build I:
1) Load game
2) Hit escape
3) Hit 'S' (shift + s)
4) Hit 'Y' (shift + y)

and verify that I am sent back to the main menu. I am using the config you posted. Can't reproduce.

**Comment by Karol1223** [comment]
I tried it on the newest experimental as well when confirming the PR didn't fix it and it still happens to me.

Going through the steps does nothing. Only using arrow keys after pressing shift+Y actually closes it. (And I mean pressing the arrow keys without using Enter, this is weird)

**Comment by Brambor** [comment]
> Apparently that's invalid? If so, nevermind.

I marked it as invalid since it is not a master problem. It is a problem after applying some changes.

**Comment by Karol1223** [comment]
This is getting progressively weirder and weirder. I just made a new save and... this bug no longer occurs? But it did occur on my old save on the same exact version yesterday...

**Comment by Brambor** [comment]
Could something be saved through `uistate.h`? Wild guess, probably not. Try looking at the save files.

**Comment by Karol1223** [comment]
> Could something be saved through `uistate.h`? You could try looking at the save files.
> 
> Very wild guess, probably not.

I tested it on that same savefile that wasn't working and... now it's working? I didn't update the game inbetween. As far as I can see nothing changed except me turning on NumPad? But after turning NumPad back off it was working still.

I guess the issue is resolved? No idea how, though...
