### ISSUE TITLE
imtui does not update when repairing vehicle

### ISSUE THREAD

**Issue by mischief** [CleverRaven/Cataclysm-DDA#73054]
### Describe the bug

when trying to repair a vehicle, the part selection ui does not update the selected part.

### Attach save file

[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14988019/save.tar.gz)

### Steps to reproduce

try to repair the seatbelt in the save while using git HEAD/cdda-experimental-2024-04-14-2000 with curses UI

### Expected behavior

UI updates while selecting part

### Versions and configuration

gentoo/cdda-experimental-2024-04-14-2000/curses ui

**Comment by mischief** [comment]
cc @katemonster33

**Comment by katemonster33** [comment]
Can you retest? #73426 may have fixed this.

**Comment by mischief** [comment]
yup, i believe this is fixed.
