### ISSUE TITLE
ImGui windows. Using different fonts in one sentence

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73061]
### Describe the bug

While still in the process of creating report #72986, I noticed a strange behavior of exclamation (`!`) and question (`?`) marks.

Now, I have additional comments. Therefore, I am putting it in a separate topic. 

**1. As it was on the old interface (?). Version 2024-04-04-0557. ImGui = false**

- Russian
![test1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/66d8fffa-c9de-48fe-acf4-6c04e0ed45bc)

- English
![test2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/92b83851-68ee-4ce0-ade8-0a95e641a015)

Notice. The entire phrase is in the same style (same font). And it is on one line (one level).

**2. New interface. ImGui = true. English.**

- Version 2024-04-11-2208 
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/73cae61b-f67c-480a-bf2c-9cefc3cba73b)
![4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/da70d631-e826-4f9a-a27a-76b11ce431cf)

Pay attention to the question mark at the end of the sentence. He is clearly a half a line higher.

- Version 024-04-16-1009
![t1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/669c855c-7f7e-42be-909a-83f0e5cbb67f)

Maybe it's just me, but in this version, the font of the text and the question mark are different.

**3. New interface. ImGui = true. Russian.**

- Version 2024-04-11-2208
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/2989df19-8eb8-405a-89c7-b72dac480609)
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/23ca5bc4-8e77-4b76-accf-8237152724d1)

*For context. First screenshot: You stand in thin smoke. Second: stop moving items.  Problems with buttons are indicated in #72986*

Notice that the question mark is at the same level as the text. But now there is a problem with the exclamation mark. In the second screenshot, instead of the `-` sign you got `_`.

- Version 024-04-16-1009
![t2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/353c405f-ca08-430f-b9bf-b38aedeaf8ce)

Notice. Two different fonts are used. The first font is for the entire message. The second one is for the number of threads to be received: 50. And also 50 is half a line lower than the word `нитки` (threads).

UPD. I didn't pay attention right away. There's also a problem with brackets. They are obviously lower than they should be.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

I want the messages, as well as the game as a whole, to use a consistent style.

### Versions and configuration

cdda-windows-tiles-x64-2024-04-16-1009

### Additional context

Additional information https://github.com/CleverRaven/Cataclysm-DDA/issues/72986#issuecomment-2054201658

>Right, and for the question mark question, when I wrote https://github.com/CleverRaven/Cataclysm-DDA/pull/72579, I had to make some artificial adjustments to the x/y coordinates when drawing to the screen from an imgui call. I'm still not sure why this needed to be done. It's possible that the adjustment I made to get CJK characters to look ok doesn't work for Cyrillic. Yes it's a separate issue, you can make an issue if you want, but I don't know how easy it will be to fix

**Comment by NetSysFire** [comment]
Can confirm.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59517351/aa3f59d0-5821-41b9-b944-a46fa6786154)

Maaaybe also related to #73120
