### ISSUE TITLE
Tile spawning error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73074]
### Describe the bug

bungalow22_north
Asphalt in bathroom and room with washing machines

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15011653/-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/08b06d9c-ee5d-4e30-aacb-12616e319993)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-16-1009 73b6cf7 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90.3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
bungalow22.json specifies '_' for a number of bathroom tiles, and those are from the standard_domestic_landscaping_palette palette. I think those are supposed to be "~", as there doesn't seem to be any furniture or items associated with that character, and it seems these are supposed to be open floor (with nothing on top of it).
