### ISSUE TITLE
Certain food items in containers are unevenly spoiled

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#73071]
### Describe the bug

Related to #67603.

Although individual grocery items like veggies and fruits can and should vary in spoilage, certain items should not.

- Fruit jams and other jarred items
- Eggs in an egg carton, unless we assume that blob psychosis made the previous homeowner go mad and refill their used egg cartons with fresh eggs
- Butter in paper wrappers
- Cheese in plastic bags
- Bread in plastic bags
- Toast-ems in cardboard boxes
- Salad in plastic tupperwares

...And more.

### Attach save file

N/A

### Steps to reproduce

1. Go to a residential food spawn e.g. a kitchen refrigerator.
2. Observe that there are unevenly spoiled jam in a jar.

### Expected behavior

I expect that a stick of butter in a wrapper is more-or-less uniform in spoilage.

### Screenshots

![Screenshot_2024-04-17-21-16-24-248_com cleverraven cataclysmdda experimental-edit](https://github.com/CleverRaven/Cataclysm-DDA/assets/27952407/d501b472-24dd-476f-9ede-a2702904ecde)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 23046RP50C; Release: 14; Incremental: V816.0.4.0.UMYCNXM; 
- Game Version: cdda-experimental-2024-04-16-1009 73b6cf7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by RenechCDDA** [comment]
In what way does this differ from the linked issue?
