### ISSUE TITLE
ImGui save option

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#73070]
### Is your feature request related to a problem? Please describe.

New ImGui add lots of options to customize your interface, and in future, I think, there will be more comfortable options
There is ImGui Demo Screen option in main menu, where you can change your interface, but after close/open game - they set to default

### Solution you would like.

1) Make ImGui settings be available during the game too, not only from main menu
2) Make this options to be saved

Make it similar to side bar options, where you can choose lots of different type of sidebar and make its widgets be move to be comfortable to you
Available customization for you own preferences is better, than make only one unchangeable style which is good by opinion of one or few people

**Comment by ZhilkinSerg** [comment]
Saving and loading settings is already supported:

`ImGui::LoadIniSettingsFromDisk`
`ImGui::SaveIniSettingsToDisk`

We just need to call this code from somewhere.

**Comment by katemonster33** [comment]
> Saving and loading settings is already supported:
> 
> `ImGui::LoadIniSettingsFromDisk`
> `ImGui::SaveIniSettingsToDisk`
> 
> We just need to call this code from somewhere.

We turned off the imgui ini. I think we would prefer to wrap any imgui-related settings into our options json
