### ISSUE TITLE
Custom start date is not saved with character template

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#73072]
### Describe the bug

If you define a custom Cataclysm start date or Game start date, this value will not be saved if you save the character as a template or use the "last character" template.

### Attach save file

N/A

### Steps to reproduce

1. During character creation, change the start date.
2. Save the character as a template.
3. Exit character creator and load the template. Start date is not saved.
4. Change the start date again, and generate the character.
5. Kill the character.
6. Use the "Last character" template. Start date is not saved.

### Expected behavior

Custom start date should be saved.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 23046RP50C; Release: 14; Incremental: V816.0.4.0.UMYCNXM; 
- Game Version: cdda-experimental-2024-04-16-1009 73b6cf7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by XygenSS** [comment]
> That's because start date is not an attribute of a character

So is the issue invalid? What is the "correct" way of saving a custom start date for a scenario?

**Comment by ZhilkinSerg** [comment]
Scenarios themselves contain start date, e.g.:

```
    "start_of_cataclysm": { "hour": 0, "day": 61, "season": "spring", "year": 1 },
    "start_of_game": { "hour": 8, "day": 1, "season": "summer", "year": 2 },
```

**Comment by XygenSS** [comment]
And if you wanted to modify or set one for yourself, you are expected to mod in a custom scenario, or edit the date every time?

disappointing but I think I can understand.

**Comment by ZhilkinSerg** [comment]
> And if you wanted to modify or set one for yourself, you are expected to mod in a custom scenario, or edit the date every time?
> 
> disappointing but I think I can understand.

Yes, if you want to modify something - you create a mod, so you will have a scenario with all the necessary attributes.

Also there is a place for "Quick start with last settings used" option - it just should not be a character template (because it should not only character, but all other things as well - world settings, scenario, character selections, etc).
