### ISSUE TITLE
Can't create a character

### ISSUE THREAD

**Issue by Sandboxvoid** [CleverRaven/Cataclysm-DDA#73075]
### Describe the bug

If I go to create a  character on a world it just doesn't let me, I also can't see where to change mods

### Attach save file

N/A

### Steps to reproduce

Clicking create character

### Expected behavior

The game would let me create character???

### Screenshots

 DEBUG    : Error: Json error: data/json/furniture.json:30:18: Expected a string, got a 1

    "color": "brown",
    "move_cost_mod": 6,
    "max_volume":
                 ^
                  3000,
    "required_str": -1,
    "flags": [

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466
![cataclysm-tiles Screenshot 2024 04 17 - 15 10 29 96](https://github.com/CleverRaven/Cataclysm-DDA/assets/32523294/2255f983-7509-49bf-b399-b029655021fb)

Every time I go to create a custom character this pops up

I've only played this game once on an older version but now I've installed (what I think) is the latest version it doesn't work.

### Versions and configuration

Windows 10 Game version: d6ec466

**Comment by RenechCDDA** [comment]
Stale bot appears to be having issues closing this one so I'll close for it.

Please feel free to comment here/open a new issue if the issue persists after a clean install.
