### ISSUE TITLE
buff chainsaw, maybe or maybe not nerf axe, and bring more chainsaw type and maybe sharpen table to sharpen the axe and maybe other weapon too

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#73085]
### Is your feature request related to a problem? Please describe.

because it look like you can tear down tree with a few less than 6 minute, and maybe or maybe not nerf axe cutting because it look like it can be more than 14 minutes depending on the thickness, 

### Solution you would like.

chainsaw should cut faster or less than 6 minutes depend on the thickness, so too the axe, bring more chainsaw type medium power chainsaw, high power chainsaw and maybe sharpen table to sharpen the axe and maybe other weapon too

### Additional context

https://youtu.be/ZBxGO1bSi94?si=6DUXloJwCeSma-W3&t=127 content contains chainsaw, and axe

https://www.facebook.com/watch/?v=1485822605276863 content contains only chainsaw on hickory wood

https://youtu.be/bmOtKZ9tRL4?si=2sMjczuAPUT1Y8dq&t=507 world strongest chainsaw

**Comment by PGR-14** [comment]
A: Weapon mods aren't typically allowed, as they're kind of weird to work w/
B: They're unwieldy & hard to use. Think of using it on different materials, they're built for cutting trees, not people & Eldrich abominations. Axes on the other hand, while made for chopping trees, it's still an extremely effective weapon to use.

**Comment by PGR-14** [comment]
Oh wait, sorry, you're talking about cutting wood & stuff, I haven't really worked w/ that stuff but I think it's alright, especially w/ the axe.

**Comment by blablase** [comment]
> Oh wait, sorry, you're talking about cutting wood & stuff, I haven't really worked w/ that stuff but I think it's alright, especially w/ the axe.

okey
