### ISSUE TITLE
Have an option to name monsters ourselves.

### ISSUE THREAD

**Issue by Vane79** [CleverRaven/Cataclysm-DDA#73089]
### Is your feature request related to a problem? Please describe.

When the newly-created survivor sees a zombie for the first time, it doesn't know what's happening, right? Player character sees a person, maybe slightly warped by the blob, and that person moves jerkingly and abnormally. Maybe, there are snarling teeth or empty eye sockets. And that's it. How does the character realistically know that that's a zombie? Tough zombie, zombie brute or hulk or whatever. 

### Solution you would like.

Imagine you walk into town, and the compass marks things the character sees for the first time in your character's life. You are given the monsters' brief description and are prompted for a basic nickname for said monster. That would make the game more personal, in my opinion. 
This system could also be paired with taking photos, because one tends to notice more minute details when one looks at the photos in their calm/safe car/camp instead of the fray, fighting for their life. Thus, descriptions for photos could be more, erm, *descriptive*, (based on photo quality), than up-close in the fight. 
This could also be tied to the amount of monsters killed, probably.

I'm envisioning this feature as a completely optional one, since it changes the way the game is played drastically.

### Describe alternatives you have considered.

Not implementing this idea at all, since it's fun and functional as-is.

**Comment by PGR-14** [comment]
I really love this idea, but there are a few things:

1: Zombies are already part of general culture, so those should get a pass
2: It'd be harder to talk about a single creature if they've all got special names
3: Some other creatures already have names either through culture (Like aforementioned zombies) or through the news outlets (Like the Ferals)
4: For different zombies, it'd be somewhat easy to distinguish between them, (I.E. Tough zombie being noticeable fit) but I believe that this could add in "Hidden" zombies, the blob taking the form of a regular zombie, but then realizing that it's actually way different on the inside (Like tons of bone growth under the skin making it look like it's a regular tough zombie, but actually a skeletal zombie)


There's a pretty easy fix for this though:
Put it in as a mod, for RP purposes of course.

**Comment by ZhilkinSerg** [comment]
> How does the character realistically know that that's a zombie?

Different things have different names and that's it - character calls a thing with some name, another thing with a different name, etc. It does not matter which specific names are used (zombie, shamblers, ghouls, undead, blobsters, walking dead, rottens, whatever), but if you will use a mod that renames things that would only give you headache and confusion when talking about the game with other players.

**Comment by Zireael07** [comment]
>  confusion when talking about the game with other players.

That's a good point.

**Comment by IdleSol** [comment]
`Monster_name` = `name`+`player_name`

`name` = This is the name from the json file
`player_name` = ??? (by default)

The `player_name` column can be filled in by the player. With or without character limit.

Option to hide or show name in monsters name.

P.S. My imagination is only enough for zombie 1, zombie 2... zombie 130.
