### ISSUE TITLE
Salt Recipes. A more complicated recipe is less useful than a simple recipe.

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73086]
### Describe the bug

There are two recipes for producing salt from salt water:
- https://github.com/CleverRaven/Cataclysm-DDA/blob/73b6cf73b988b5f1289863e4f507bff8f5b2afdb/data/json/recipes/recipe_food.json#L89
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/dbaf1ac1-a626-4277-9cb1-c5d33e067be6)

- https://github.com/CleverRaven/Cataclysm-DDA/blob/73b6cf73b988b5f1289863e4f507bff8f5b2afdb/data/json/recipes/recipe_food.json#L105
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/f83339b8-e6fb-4905-b0a3-b7f0c5146012)

The first recipe calls for a fire + pot. It makes 10 salts out of 1 salt water.
The second recipe requires the same as the first + distiller. And from 5 salt water makes 50 salt.

It's easy to see that we end up with the same amount of salt. But the first recipe requires only 40 minutes (or 1 hour and 27 minutes x5). The second recipe takes 3 hours and 40 minutes (3:20 if the proficiency is learned).

Here is a comparison of the time it takes to make 150 units of salt from 15 units of salt water.
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/4924b577-474f-4262-a852-651c2b215108)
![4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/011ae183-ea5d-4d47-8ea9-8cf163683ce0)

The first recipe manages in less than three hours. The second, over six hours. The difference is about twice as much.

In fact, the second recipe will never apply. It is useless.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

I don't know which of these two recipes corresponds to the real state of affairs.

From a player's point of view, I would prefer the second recipe to win at mass production. That is, increase the bonus to 95%.

### Versions and configuration

cdda-windows-tiles-x64-2024-04-16-1009

**Comment by RenechCDDA** [comment]
Not a bug. Distillation is much more involved than just boiling all the water away.

>I don't know which of these two recipes corresponds to the real state of affairs.
>
>From a player's point of view, I would prefer the second recipe to win at mass production. That is, increase the bonus to 95%.

They both do. You also can't make salt out of nothing. Boiling away the clean water from salt water and capturing it is still going to leave you with the same amount of salt as not capturing the clean water. There's only so much salt in there.

**Comment by IdleSol** [comment]
I was talking about the mass production bonus. Instead of 80% on crafting over 4, increase the bonus to 95.
`"batch_time_factors": [ 80, 4 ],` --> `"batch_time_factors": [ 95, 4 ],`

Then the crafting rate will equal somewhere around 50 units of salt water. But the amount of salt would be the same.
