### ISSUE TITLE
Is the volume of the sleeping bags too small?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73099]
### Describe the bug

There are three sleeping bags in the game:
- sleeping bag https://cdda-guide.nornagon.net/item/sleeping_bag
- fur sleeping bag https://cdda-guide.nornagon.net/item/sleeping_bag_fur
- improvised sleeping bag

This is about the first two. Their volumes in rolled and unfolded state (copy-from) are 1 and 2 liters.

I'm not sure what exactly this bag represents in the game. And what served as its prototype.

Perhaps it's just a 3 millimeter thick cloth or a 5 millimeter thick fur. But even so, based on dimensions: 2.0m x 0.8m x 0.003m * 2 * 1000 = 9.6 liters. 

If you look at the warmth: 80 and 100. I don't think cotton alone can provide it. With fur, I don't know. So the volume would be even more.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

And while I really like carrying it in my pocket. I suggest we increase the volume:
- rolled sleeping bag : ~20..25L
- sleeping bag: ~30L
- rolled fur sleeping bag & fur sleeping bag: ~ 10..15L

Additionally, I would reconsider its length. I assume that it rolls up into a roll, and its width is at least 50...80 centimeters. But maybe there are models that can be folded in half and then rolled? I don't know, I've never used one.

### Versions and configuration

cdda-windows-tiles-x64-2024-04-16-1009

### Additional context

And I also suggest adding something synthetic with smaller dimensions when folded. Perhaps based on the emergency blankets from the shelter? Warm, comfortable and takes up little space. At 7-8 levels of tailoring.

**Comment by PatrikLundell** [comment]
Sleeping bags typically consist of thin fabric with something insulating caught in pockets between these fabrics, with warm ones often using down for insulation. Sleeping bags can be rolled up in a fairly small volume, and yes, you can fold them before rolling them up for a thicker but narrower roll. Note that most of the volume comes from air caught in the insulating material, and this air is pressed out when you roll it up.
It also depends on the kind of sleeping bag: is it one intended to use to sleep over indoors, or one intended to be usable in a tent when it's -20 degrees Celsius outside?

A fur bag would be a log heavier and thicker than a modern sleeping bag.

If the emergency blankets are the very thin silvery things I think of they'd be rather bad as sleeping bags, as they'd probably tear and won't allow moisture through (yes, not letting rain in is good, but not letting sweat and exhaled moisture out is bad. It's would probably be similar to sleeping in a plastic garbage bag, but warmer.

**Comment by natsirt721** [comment]
I keep my modern-ish synthetic cold-weather sleeping bag in a stuff sack that is 18" L x 10" D, which works out to about 25 L. Its not the original bag (which IIRC was quite a bit smaller) but I think 20 L for the rolled bag is a good starting place, and probably no lower than 15 L for a high-end bag. 

I feel like fur should take up more space, not less. Even if you do need less of it, the backing isn't going to fold as nicely as a synthetic fabric will.
