### ISSUE TITLE
 The man from the lighthouse quest doesn't work

### ISSUE THREAD

**Issue by GeneralyaGargozul** [CleverRaven/Cataclysm-DDA#73092]
### Describe the bug

quest number two to clear the lighthouse does not give up no matter what, they even tried to dismember all the corpses, but this did not lead to any result.

### Attach save file

[Девол-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15020146/-trimmed.tar.gz)

### Steps to reproduce

take a quest, do a quest, try to pass it.? idk

### Expected behavior

I expect that after I complete the conditions of the quest...I will pass it...unbelievable.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: bafd955 [64-bit]
- Graphics Version: Tiles [Tileset UltiCa]
- Game Language: Системный язык [Russian]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    Перевод сложных диалогов [translate_dialogue],
    Характеристики за убийства [stats_through_kills]
]

**Comment by PGR-14** [comment]
Just so you know you can go into debug mode-player-player-you-edit missions then select the mission you want to get into the next phase of & do it.
