### ISSUE TITLE
How high is the railroad track terrain in the game？no vehicle should be able to pass the railroad track terrain。

### ISSUE THREAD

**Issue by guo87995585** [CleverRaven/Cataclysm-DDA#73094]
### Is your feature request related to a problem? Please describe.

In the current game, no wheel can pass through railroad tracks，Whether this railroad is in the wilderness or at the intersection with the road

### Solution you would like.

In reality, except for cars with very low chassis and very small wheels, they should be able to pass through, or at least railway terrain that allows cars to pass through should be added in cities

**Comment by ZhilkinSerg** [comment]
> In reality, except for cars with very low chassis and very small wheels, they should be able to pass through, or at least railway terrain that allows cars to pass through should be added in cities

Nope, in reality most of cars can't cross railroad tracks in the wild
