### ISSUE TITLE
Heating up beyond 57° C doesn't cause you to vomit to death, you just die of heat stroke.

### ISSUE THREAD

**Issue by SomeGuyIGues** [CleverRaven/Cataclysm-DDA#73102]
### Describe the bug

Within blob/master/src/weather.h, it is described that the "maximum heat cannot pass 57 C, otherwise the player will vomit to death." This is not true, you just die of heat stroke, like a normal person.

### Attach save file

N/A

### Steps to reproduce

1. Spawn traitless, 8-8-8-8 character.
2. Strip naked and equip a diver's watch.
3. Drink rehydration drinks and eat any food (I chose cheese fries) until the player is full and turgid.
4. Debug force temperature to 60° C.
5. You can check your body temperature at any time to see that in fact you are dying of heat stroke.
6. Die of heat stroke in an hour.

### Expected behavior

Everything seems normal, perhaps the player should have vomited more considering how greasy the fries were and how unpalatable rehydration drinks are. Otherwise the main issue is that text within weather.h should be more accurate, warning that the player will die from heat stroke instead of spewing their guts out. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3296 (23H2)
- Game Version: ef202a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex]
]

### Additional context

The C header file in question: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/weather.h

**Comment by I-am-Erk** [comment]
The text is probably from before we added hydration and heat stroke. Feel free to change it. We could add vomiting as an effect from late stage heat stroke too.
