### ISSUE TITLE
Сrude anvil. Incorrect material. Disassemble gives the wrong materials

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73101]
### Describe the bug

A crude anvil is made from a piece of railroad track.

The rail is medium carbon steel and is disassembled into lumps of medium carbon steel.
![rail](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/b8dabb3d-2891-411e-a9f7-d078a537eab7)

But the crafted anvil becomes steel. And disassembles into lumps of steel. This is a mistake.
![anvil](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/615c117e-d162-4095-856d-33e910f02c35)

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

cdda-windows-tiles-x64-2024-04-16-1009

### Additional context

Yes, another anvil problem.

**Comment by natsirt721** [comment]
It looks like this is the only recipe for the crude anvil, so the fix should be as simple as changing the material and decraft recipe.
