### ISSUE TITLE
Tried to set charges for item chunk of tainted meat (fresh) that could not have them!

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73105]
### Describe the bug

```
En: DEBUG    : Tried to set charges for item chunk of tainted meat (fresh) that could not have them!
Ru: DEBUG    : Tried to set charges for item кусок заражённого мяса (свежее) that could not have them!

 FUNCTION : item::item(const itype*, time_point, int)
 FILE     : src/item.cpp
 LINE     : 318
 VERSION  : cdda-experimental-2024-04-16-1009 73b6cf7
```

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15026578/-trimmed.tar.gz)

### Steps to reproduce

1. Load the save
2. Take 2-3-4 steps on the road
3. Get an error

Object spawn location: underground lab. Directly below the character.

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-16-1009 73b6cf7 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90.3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

### Additional context

Probably related to these issues #72984
see post https://github.com/CleverRaven/Cataclysm-DDA/issues/72984#issuecomment-2064170122

**Comment by PatrikLundell** [comment]
This issue is fixed by #73104.
