### ISSUE TITLE
[Magiclysm] *Weapon* of Judgement and Mage Blade summoned weapons from the Crusader/Technomancer classes have no length.

### ISSUE THREAD

**Issue by jake1203n** [CleverRaven/Cataclysm-DDA#73112]
### Describe the bug

Summoned melee weapons from the Crusader/Technomancer classes in Magiclysm have no length. 

A normal weapon: 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/de52c11c-f637-4117-be88-bca14739419e)

A summoned Magiclysm weapon:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/4a2dce48-8c4e-44c1-85c5-4a2ff7ee17bf)

This allows for ridiculous occurrences, such as storing a greatsword inside of a milk jug: 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/5c196a4c-8b38-483b-b96d-d1ae7e6d7a4e)

It probably also impacts their To-Hit bonus, since weapon length correlates to this.

### Attach save file

[MagicEvoAdvancedHardcore-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15029867/MagicEvoAdvancedHardcore-trimmed.tar.gz)

### Steps to reproduce

1. Just open your inventory. The greatsword is already inside the milkjug. How?!

### Expected behavior

I would expect that a greatsword would only fit inside the items listed in its description - a large scabbard, or a rifle case of some kind.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-03-21-0047 2c345a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by GuardianDll** [comment]
Length is calculated automatically for all items, if it's not defined; UI just doesn't show it
The reason you can put sword in a bottle is because Concentrated Mana is a soft material
