### ISSUE TITLE
Tried to set charges for item ... egg (fresh) that could not have them!

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73119]
### Describe the bug

```
En:  DEBUG    : Tried to set charges for item sparrow egg (fresh) that could not have them!
Ru:  DEBUG    : Tried to set charges for item яйцо воробья (свежее) that could not have them!

 FUNCTION : item::item(const itype*, time_point, int)
 FILE     : src/item.cpp
 LINE     : 319
 VERSION  : cdda-experimental-2024-04-19-0435 d30757e
```

Similar errors occur with other eggs. I have encountered sparrow, crow, water vole, and turkey eggs.

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15039354/-trimmed.tar.gz)

### Steps to reproduce

1. Load the save
2. Continue automatic route movement (`g`). Note landmark `!` on the map
3. Get several error messages (1 to 3, probably depends on egg generation).

I got messages in 3 attempts out of 3.

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-19-0435 d30757e [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

### Additional context

Probably related to these issues https://github.com/CleverRaven/Cataclysm-DDA/issues/72984

**Comment by PatrikLundell** [comment]
Thanks for taking the time to produce bug reports reproducing these issues.
It is indeed a case of a call to create a stack of items, in this case I think it's the laying of eggs (operation called try_reproduce).

It looks like it should be a quick issue to fix, so I'll get right to it.
