### ISSUE TITLE
house_22. Tile spawning error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73124]
### Describe the bug

house_22. Sidewalk tiles in the bathroom
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/5fac4eda-1c74-4c52-b35d-ae447e44b911)

### Attach save file

[trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15041405/trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-19-0435 d30757e [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90,3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
'-' seems to be the tile used, while it probably should be '~' (house22.json, nested mapgen house_22_normal).
Note that the bug report instance is rotate 180 degrees, so the bathroom is to the NE in the file.
