### ISSUE TITLE
House_rv. Tile spawning error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73126]
### Describe the bug

House_rv. It's impossible to open or close the window.
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/bd3b4fc9-190d-41d3-9df6-f304afe2c462)

UPD. <s>I decided to check the other windows and doors. The door next to where the character is standing does not open.</s> It's not a bug
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/2e7640b2-af50-4ac0-8496-24178a49c313)
The character tries to open with a hammer. And when using lock picks, it says there is no lock.
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/12a8beb9-d1db-41fe-b929-508d49051647)

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15041875/-trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-19-0435 d30757e [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90.3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
Not a bug. You need a better tool for this task, such as a crowbar (only tested the front door). The message is intended to indicate that your tool is inadequate for the task.

**Comment by IdleSol** [comment]
But I have lock picks. Which say there is no lock. And I'm standing inside where any door should open from.

**Comment by IdleSol** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/9137309fc64504f707135a1f7e703b762756b191/data/json/furniture_and_terrain/terrain-doors.json#L353-L356

The question of why I can't open it from inside the house is still relevant. But maybe I should put it in a separate topic?

**Comment by PatrikLundell** [comment]
The answer is that this is how these doors are defined to be, and I believe that's intentional.
However, you can write a suggestion arguing for these doors to be changed. I have no idea if anyone would take you up on it, though.

**Comment by GuardianDll** [comment]
you very much can, it's just it lack of use action that suggest it, you need to activate your prying tool to pry it
to fix it, #65552 is required

**Comment by IdleSol** [comment]
I disagree with closing the topic. The first problem was with the window. It still won't open. Or doesn't close. I also can't interact with the curtains.

Depends on whether it is generated as open or closed.

In the construction menu, it doesn't fit the action to board up the window.
