### ISSUE TITLE
Sort by / differentiate 'almost craftable' recipes in crafting menu

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#73135]
### Is your feature request related to a problem? Please describe.

The crafting menu currently differentiates between recipes that you can and cannot currently craft at any given time by pulling craftable recipes to the top and coloring them differently. For those that you cannot craft, there is no differentiation between recipes where you are missing a single tool or material and those where you have none - they are all presented as equally uncraftable. As someone who frequently looks through the crafting menu for inspiration, it would be nice to see which recipes I was close to being able to make without having to read through every single one.

### Solution you would like.

A third level of differentiation between 'can craft' and 'cannot craft', that being 'can almost craft'. Recipes that are missing a single tool or a single material would be colored uniquely and placed between the 'can' and 'cannot' blocks in the crafting menu. An intermediate weight gray would be a nice default color (if one is available). The intent is to draw attention more complex recipes that are close the being workable, so recipes that have fewer than 2 or 3 tools or materials might be ineligible for this status to avoid cluttering - yes I know I can almost make a rock in a sock, its just a rock and a sock!

I think this would be extremely useful for cooking food, as it would let the player easily see if there are ingredients that they should keep an eye out for (or go get from the pantry) for making some of the more complex dishes.

For simplicity, this would count each tool or material input as a single missing item, rather than counting stacks. e.g. if my recipe needs 10 planks, having 3 and having 9 are both considered one missing item. 

For complexity, the total quantity of materials and tools could be summed and a percentage of available tools and materials calculated and compared to a threshold (say, 80%) to determine 'almost'ness. 

Edit: See #72697 for (some) related discussion regarding 'plausible crafting'

### Describe alternatives you have considered.

Instead of coloring the recipes, allowing the recipes to be sorted by missing item count would allow for the same information to be gleaned. I considered proposing enhancements to the filtering functionality, but the idea is to call out recipes while browsing, rather than require explicit filtering. 

Edit: The inverse of this would be 'if only I had a...' mode, which would let the player enter a set of tools/qualities/materials and show what recipes they currently can't craft, but could if they had those items. Not sure how this would work out from a gameplay perspective.

**Comment by Brambor** [comment]
> Edit: The inverse of this would be 'if only I had a...' mode, which would let the player enter a set of tools/qualities/materials and show what recipes they currently can't craft, but could if they had those items. Not sure how this would work out from a gameplay perspective.

That is a use case of the linked #72697. You could make a list of items you think you can obtain and feed it to the crafting menu. It is not direct consequence of said issue.
