### ISSUE TITLE
incorporeal characters can still open doors

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#73138]
### Describe the bug

Since they can't touch or affect nearly anything else, this seems like an oversight. 

### Attach save file

[Fords Prairie-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15046033/Fords.Prairie-trimmed.tar.gz)

### Steps to reproduce

1) Load save. You will begin under the effects of the Animist spell Spirit-Walking as an easy way to provide the incorporeal effect.
2) Attempt to get the object from the trash can to the south and be told that you don't have the substance to affect anything.
3) Attempt to attack the zombie to the west and be told that you don't have the substance to affect anything.
4) Attempt to open the door to the east, which immediately opens. 

### Expected behavior

You also lack the substance to affect doors. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 5aaf8fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Magiclysm [magiclysm]
]

**Comment by GuardianDll** [comment]
sound like a simple "if you have effect X, print a message, and don't" c++ change in `static void open()`
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/handle_action.cpp#L576

**Comment by Standing-Storm** [comment]
I tried my hand at it, and while you can't open the door with the o key, you can still move into it and auto-open it. I'm not sure how to stop that part.
