### ISSUE TITLE
More information for players

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73145]
### Is your feature request related to a problem? Please describe.

The game is slowly evolving and many new mechanics are being introduced. Or old mechanics are being changed. Some of these changes are quite obvious, others are not.

I suggest adding more information for players. This information should reveal some gameplay aspects. It's probably easier to show with examples.

1. We have different places to sleep on. Floor, chair, couch and bed. They have a comfort parameter. But how does the player know about it? I had to go into the game files and compare them to find out. And now I know that a couch is more comfortable than a chair. But I have no idea what exactly that gives. Just speculation.
2. Proficiencies for melee skills have been added to the game. What do they do? Why, the player has to meddle with the file to find out that they reduce stamina costs. And by how much?
3. What is the difference between blue colored water and red colored water? Why did my water go from red to blue and then back to red? And it's all in the same container. Is this a bug? Is it a feature?
4. Or how many limbs does a character have? Is it possible to get an elbow wound? And if we can, why do we heal the whole arm? Or a little more fun, are the eyes part of the head? Does 100% head coverage protect the eyes?
5. How many players know that a container of water can be thrown into a fire to get clean water? And what else can be prepared in this way? And how can you guess about it if there is a crafting menu. It says everything you can make is listed here.

### Solution you would like.

Ideally, revise all the mechanics and add the necessary explanations. But I doubt anyone will do that.

So I suggest we go with the simpler option. Adding new mechanics should include adding the appropriate explanations:

1. In the item description. If it applies to certain types of items. Example comfort for furniture. More specifically its level.
2. In the help, if it is something more general or requires detailed explanations. Same comfort, but with disclosure of how it affects the character. (And the ability to move from an item with a "comfort" parameter to the appropriate section of the help, would be a nice feature)
3. only in the help, unless these mechanics should be obvious to the player.
4. Any other options to understand these mechanics: dialogs, notes ... prophetic dreams.

Most importantly, ask yourself if your mechanics can be understood without reading code or game files.

### Additional context

Informing the player of a change in help?

**Comment by ZhilkinSerg** [comment]
Title says metagame, but you are actually talking about in-game information. Some features might be missing (intentionally or not) player faced details or how things work. What can be done with this for features is reviewing pull requests and providing your feedback with suggestions.

**Comment by IdleSol** [comment]
Could be a translation problem. Google says «Metagame information is information obtained by out-of-game means». Or maybe I'm misunderstanding the term. Changed the title of the topic.

**Comment by Zireael07** [comment]
@IdleSol That's exactly what Zhilkin means, this information is in-game so it wouldn't be meta

**Comment by kevingranade** [comment]
This issue is far too vague and covers too many topics.
Too little information is when the player can't make a decision,  if you know a bed is better than a chair,  that's enough information.
Also something covering many issues like this is simply invalid,  one topic at a time.

**Comment by IdleSol** [comment]
@kevingranade I may have misspoken. But this is more about adding a rule. If you are introducing new mechanics, then add explanations for the player.

But it's up to you. There's a problem and it's growing.
