### ISSUE TITLE
Water Faucet Duplication

### ISSUE THREAD

**Issue by AcornSlayer** [CleverRaven/Cataclysm-DDA#73158]
### Describe the bug

I uninstalled a water faucet of my mounted kitchen which was attached to a water tank(not on the same tile). I reinstalled the water faucet on to mounted workshop which was on a the tile right next to it and then it would still work but then the message "The water faucet is not longer compatible with mounted workshop and pops out then adds a water faucet to my inventory.

### Attach save file

![Screenshot 2024-04-20 221101](https://github.com/CleverRaven/Cataclysm-DDA/assets/167660715/f6fdca73-bd48-4ba9-9c20-016a4f24e2cb)

### Steps to reproduce

1. Install a water faucet on a mounted kitchen, but make sure a water tank is attached to the same vehicle.
2. Reinstall the faucet on to another tile where it can be mounted and then drink from it.

### Expected behavior

I expected my character to drink water and not have faucets appear in their inventory. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3447 (22H2)
- Game Version: cdda-experimental-2024-04-18-1441 5aaf8fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food]
]

**Comment by Karol1223** [comment]
@harakka you were asking if those errors occur to more items

**Comment by harakka** [comment]
/confirm
Thanks, yup same issue as #72796
