### ISSUE TITLE
Huge performance drop in Android with ImGui

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#73150]
### Describe the bug

The game's performance significantly drops when navigating ImGui with a touchscreen, but not with a mouse or keyboard.

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/0b38b021-b793-44f3-97a1-58d7a2ed1b71

### Attach save file

N/A

### Steps to reproduce

Make an ImGui window open.

### Expected behavior

I didn't expect ImGui to be this heavy in performance.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 14; Incremental: G991NKSS4FXAD; 
- Game Version: cdda-experimental-2024-04-19-2301 449edb2 [64-bit]
- Graphics Version: Tiles
- Game Language: 한국어 <color_dark_gray>(56.9%)</color> [ko]

**Comment by ZhilkinSerg** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/73052

**Comment by AnotherSeawhite** [comment]
@ZhilkinSerg Can you reopen this? The issue is still there.

**Comment by AnotherSeawhite** [comment]
Closing as it got resolved by unknown reason.
