### ISSUE TITLE
Game crashes when scrolling through the list of items

### ISSUE THREAD

**Issue by mini-bomba** [CleverRaven/Cataclysm-DDA#73155]
### Describe the bug

The game crashes when attempting to focus on an item that is "in the corner of vision" (around 50 tiles away from player) in the list all items view (default keybind `V`)

The crash log and the crash triggering on items near the limit of vision makes it seem like this is an index out of bounds error.

### Attach save file

[Fishing Creek-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15049748/Fishing.Creek-trimmed.tar.gz)

### Steps to reproduce

1. Open attached save
2. Open the "List all items around the player" menu (`V`) and switch to items
3. Scroll down the list of items in view
4. Game crashes when attempting to focus on "trail guide" 50 tiles away from the player

### Expected behavior

No crash occurs, view is focused on the selected item

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-04-20-1851 f32b285b21 [64-bit] (note: self-compiled)
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15049760/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15049761/debug.log)

**Comment by PatrikLundell** [comment]
Failed to repeat the issue. I can scroll over all items in the list just fine. Thus, it might be related to the OS or tileset (I'm too lazy to change from the default).

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-8937-g0a3e18c004 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]
