### ISSUE TITLE
Domestic animals. A spiral of hate. Discussion

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73167]
### Is your feature request related to a problem? Please describe.

**Situation 1**

The player drives up to any place where there are several groups of domestic animals (dogs, pigs, cows and so on). After that a fight starts. Some pets, attack the others. The result is <s>a bunch of dead bodies </s>a lot of wasted meat.

**Situation 2**

This situation is similar to the first one. But there is an enemy among a group of animals. A cockroach, a wasp, a zombie, and the like. After the enemy dies, the survivors start attacking each other. But not the player. 

Example from the game: arrived at the ranch. A cockroach attacked the dogs, which killed it. After that they attacked the cows and horses. I killed these dogs, but one of them ran away and attacked a second group of dogs. And then it was back to square one.

**Situation 3**

Enclosed barns where pets are kept. You open it up and there's a fight. Usually pigs versus cows/sheep or horses.

### Solution you would like.

From my point of view, this behavior is not quite correct. But I'm not sure, so I'd like to hear your thoughts. Is this a bug or is this behavior normal.

**Comment by DragonWizard23** [comment]
I've experienced a similar case where if you get ants to start fighting zombies, they will be aggressive towards you afterwards, even if they weren't angry earlier. My guess is that the anger/aggression of animals is not species dependent: i.e. once a creature gets angry, it's angry at everything/everyone. 
It would be nice if you could calm down aggressive animals, but I think there is a fair argument to keep the current behavior.
