### ISSUE TITLE
Massive Slowdown just moving items from one tile to another

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#73171]
### Describe the bug

As per the title suggests: 

Moving items from 1 tile to another is laggy af. 

It really doesn't matter where you do it, as long as you do it. I did it in a new game, I did it with a test world in supposed better circumstances (no labs underneath, no enemies, nearby or within the reality bubble, etc). And it's the same problem.

### Attach save file

N/A

### Steps to reproduce

1. Start a new world.
2. start a new character, doesn't matter what stats/traits they have.
3. debug spawn a vehicle with decent storage capacity (Low End Cube van works);
4. Get a lot of spare parts, food, medicine, etc in one tile by spawning several boxes of cookies, butter, bacon, cheese, aspirine, ibuprofen, gauze, bandages, antiseptic bottles, and about 200 or 300 leather patches, cotton patches, synthetic patches, etc. Stuff like this.)
5. Try to move them from tile A to Tile B. Notice how the game takes its sweet time.
6. Wonder what happened recently that made this become a thing.

### Expected behavior

I would expect to not spent a 1:1 "In-Game Time" to "Real Life Time" ratio moving inventory. 

### Screenshots

[sweet_lag.mkv.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15051996/sweet_lag.mkv.tar.gz)

Enjoy the video. 

### Versions and configuration

Latest Experimental. 

dda
fungal slow down
no npc needs
magiclysm
stats through skills
stats through kills
speedydex
bombastic perks

### Additional context

There's a video added to this (sorry for zipping it).

Yes, this happens while on top of a lab, but I have to mention the lab is fully cleared.

This has also been happening for at least 2 weeks at the very least, that I have noticed. In another save, I had a character inside an evac shelter with no NPCs, and moving Splintered Wood and planks was having the same effect, when it 100% should not be happening. Unsure what could be causing all these performance issues. And no, my hardware hasn't been changed nor is damaged.

**Comment by GuardianDll** [comment]
Well, first, from your video it seems you moving item one by one, each time pressing enter. Do not do it, instead use keybinds to move entire stack or everything on the tile, check `?` keybinds for this menu
Second, moving spare items one by one is pretty long task, so you'd be better to store your patches in boxes, bags or another containers, to speed it up
/invalid

**Comment by AcidAntOnAMinefield** [comment]
> Well, first, from your video it seems you moving item one by one, each time pressing enter. Do not do it, instead use keybinds to move entire stack or everything on the tile, check `?` keybinds for this menu Second, moving spare items one by one is pretty long task, so you'd be better to store your patches in boxes, bags or another containers, to speed it up /invalid

No. That is the result after pressing "M" to move the entire stack, because I do not want to move **all** the items. 

If you actually watch the video, you will see there is a part where the UI occasionally bugs but the correct items keep being moved.

**Comment by GuardianDll** [comment]
oh, it \*was\* the moving the entire stack

lack of the save file attached make it impossible to debug it for myself

**Comment by Brambor** [comment]
The vid in mp4:

https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/a41ce444-d060-4bf5-8b61-6703fbae910e

**Comment by Brambor** [comment]
I tried to reproduce it, my results are:
- Moving from tile to tile is equally as fast as moving tile to vehicle or vehicle to vehicle.
- Moving 4096 items did take ~10 seconds. OP reported 138 items in ~20 seconds. which is about 60 times slower.
- My case: time is refreshed every five minutes. OP: time is refreshed between every item (I think this is the culprit for slowdown.

vid:

https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/f35dd457-e18a-499c-8118-1ec37e6ed7b2

save: [TEST hint good.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/15062604/TEST.hint.good.zip)


Conclusion: OP's save needed for reproduction.

**Comment by IdleSol** [comment]
I'm not sure if this is the present case. 

1. Create 4096 leather patches
2. Summon 49 ants (i=3)
3. Start moving the patches from one tile to another
4. Keep moving the patches until it gets dark.
5. Watch the behavior of the timer in the upper left corner of the manager

I have by 2pm, it's starting to stray from 5 minute segments to shorter segments. It's hard to estimate, but something like 5-10 seconds per real second. Then it goes back to 5 minute segments again. Closer to evening, virtually no (or no) 5 minute segments. When night falls (no visibility), the timer goes back to 5 minutes.

**Comment by GuardianDll** [comment]
you still didn't post the trimmed save, as bugreport suggested
