### ISSUE TITLE
It is necessary to reduce the time taken to fill the smoking rack

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73175]
### Is your feature request related to a problem? Please describe.

To put something on the smoking rack, you need to spend 1 second per item. And to get food out of it, you need to spend 1 second per item.

It has a capacity of 20 liters. Or 80 chunks of meat. Or 240 kernels of corn.

### Solution you would like.

I want interaction time to be based on the volume of food, not the amount of food.

I suggest the following times:
- 6 seconds per liter of food (120 seconds per 20 liters), to put the food on the rack
- 2 seconds per liter (40 seconds per 20 liters), to remove the food from the rack for smoking.

The calculations are as follows. 1 liter of meat = 4 pieces of meat = 4 seconds

When you put the food on the rack, you need time to distribute it evenly. And when you take it off, you may be less careful.

### Describe alternatives you have considered.

Alternatively, reduce the time spent per item from 1000 ticks to ~250 ticks.
Or make the interaction time constant, regardless of the volume or amount of food.

### Additional context

In-game tests give the following time: 249 seconds to put or take down 240 kernels of corn. And maybe it should be a bug report?

**Comment by kevingranade** [comment]
You have not made an argument for why this change should happen,  only that you want it.

At first glance this outcome of it taking longer to load the smoking track when using tiny items is reasonable.
