### ISSUE TITLE
JSON faction camp construction usage of place_npcs blows up

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#73190]
### Describe the bug

While testing Z level camp construction I encountered the unrelated bug of the game crashing (CTD) when loading the game with the following JSON section:
  {
    "type": "mapgen",
    "update_mapgen_id": "fbml_2_coop_construction",
    "method": "json",
    "object": {
      "place_nested": [
        { "chunks": [ "fbml_2_coop_construction" ], "x": 13, "y": 0 },
        { "chunks": [ "fbml_2_coop_roof_construction" ], "x": 13, "y": 0, "z": 1 }
      ],
      "place_npcs": [ { "class": "farmer", "x": 14, "y": 1 } ]
    }
  },
added to faction camp livestock expansion 2 (might be a load order issue).

The offending part is "place_npcs" as it doesn't crash (and the construction is generated when invoked) without it.
The "farmer" was found in some existing JSON (searching for usage of the construct), but it also blows up on exodii_material and some apartment survivor.

The usage doesn't make sense in a player faction camp, but might if you want to spawn NPCs together with an expanding site.

### Attach save file

N/A. The crash is caused by introduced JSON.

### Steps to reproduce

1. Modify some JSON construction by introducing the place_npcs section in it.
2. Start the game and load a save.
3. CTD.

### Expected behavior

Working JSON construct...

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-8943-g7982fb416e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
This is the code of #73176 as it currently stands.

### Additional context

The debugger points at this line in effect_on_condition.cpp:
    `for( const effect_on_condition_id &eoc_id : get_scenario()->eoc() ) {`
where it catches an access violation (0x270).

**Comment by Procyonae** [comment]
It looks like "NC_FARMER" is the "farmer" class though I've barely touched NPCs
