### ISSUE TITLE
Way to find the Church retreat

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73193]
### Is your feature request related to a problem? Please describe.

There's ways to find most factions, but not an easy way to find the church retreat

### Solution you would like.

A flyer or a bulletin board to find it in rural churches (Similar to the Exodii sign)

### Describe alternatives you have considered.

Some type of map? Or maybe some religious guy in the refugee center.

**Comment by Nebnis** [comment]
I have been playing this game for years and i never found one

**Comment by PGR-14** [comment]
We could do something like this: 

`  {
    "type": "furniture",
    "id": "f_exodii_signpost",
    "name": "pictographic signpost",
    "looks_like": "f_sign",
    "description": "This simple scrap metal sign has a series of pictographs on it depicting what seems to be a trade interaction.  There is a crude but understandable map beneath it.  You should take a closer look.",
    "symbol": "!",
    "color": "red",
    "move_cost_mod": 1,
    "coverage": 35,
    "required_str": -1,
    "flags": [ "TRANSPARENT", "FLAMMABLE_ASH", "ORGANIC", "MOUNTABLE", "SIGN" ],
    "deconstruct": { "items": [ { "item": "sheet_metal_small", "count": 2 }, { "item": "nail", "charges": [ 2, 5 ] } ] },
    "bash": {
      "str_min": 6,
      "str_max": 40,
      "sound": "smash!",
      "sound_fail": "whump.",
      "items": [ { "item": "sheet_metal_small", "count": [ 1, 2 ] }, { "item": "nail", "charges": [ 2, 4 ] } ]
    },
    "examine_action": {
      "type": "effect_on_condition",
      "effect_on_conditions": [
        {
          "id": "EOC_EXODII_SIGNPOST_FALSE",
          "condition": { "u_has_mission": "directions_exodii_signpost" },
          "effect": [
            {
              "u_message": "You study the signpost.  It shows a similar set of directions to the ones you already have.  You cross-reference them and don't learn anything new.",
              "popup": true
            }
          ]
        },
        {
          "id": "EOC_EXODII_SIGNPOST",
          "condition": { "not": { "u_has_mission": "directions_exodii_signpost" } },
          "effect": [
            {
              "u_message": "You study the signpost.  It shows simply-drawn pictograms of a pair of hands holding out an object, and another pair taking the object and offering a pouch in return.  Beneath the pictures there's a crude but understandable map with arrows pointing to what looks like some kind of castle.  You do your best to relate those to landmarks you know about, and mark the likely location on your map.",
              "popup": true
            },
            { "assign_mission": "directions_exodii_signpost" }
          ]
        }
      ]
    }
  },`

Instead, just replace the mission (& make a new one for the church retreat), change the text, & change the sign tile to the bulletin board one

**Comment by MNG-cataclysm** [comment]
I suppose that I could add a globally unique church that has some clues leading to the retreat, this would have been what the NECC used pre-Cataclysm. I think that the teamster can also point you to the church retreat via random hints.

**Comment by PGR-14** [comment]
That could also lead to some problems, how about making it so that there's a very rare chance for that bulletin board to replace those found in churches? Or, as an alternative to this, a very rare spawn in churches; a map that leads you to it (Uses a similar thing to the refugee center where it also reveals the area around the roads)

**Comment by Nebnis** [comment]
> I suppose that I could add a globally unique church that has some clues leading to the retreat, this would have been what the NECC used pre-Cataclysm. I think that the teamster can also point you to the church retreat via random hints.

Wouldn't random npc also point out they found this church? Could also be a reward for doing stuff for them.
