### ISSUE TITLE
Item display_fridge is not base item of any appliance!

### ISSUE THREAD

**Issue by Sofistico** [CleverRaven/Cataclysm-DDA#73194]
### Describe the bug

 DEBUG    : item display_fridge is not base item of any appliance!

 FUNCTION : vpart_id vpart_appliance_from_item(const itype_id&)
 FILE     : src/veh_appliance.cpp
 LINE     : 53
 VERSION  : cdda-experimental-2024-04-22-0601 6797b1d

### Attach save file

N/A

### Steps to reproduce

1. Open debug menu
2. Search for fridge
3. Try to look at the display fridge
4. The bug will be there

### Expected behavior

It's expected that the appliance would be the display fridge

### Screenshots

When you look at what it deploys:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59299346/f70d7437-7bcb-436e-a615-09d0c3de6940)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.2965 (20H2)
- Game Version: cdda-experimental-2024-04-22-0601 6797b1d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills],
    Extra Mutated Scenarios [extra_mut_scens],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bombastic Perks [bombastic_perks],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter]
]

**Comment by GuardianDll** [comment]
oops

**Comment by Brambor** [comment]
Can confirm. I actually wanted to report that yesterday, but forgot.
We all seem to be spawning fridges.

Note missing step "spawn item" between 1 and 2.
