### ISSUE TITLE
The beggars at the refugee center eat all the smoked meat

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73192]
### Describe the bug

I have 100 pieces of smoked meat. After talking to one of the beggars (any beggar) and offering to take some food, I was left without meat.

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15063755/-trimmed.tar.gz)

### Steps to reproduce

1. Load the save
2. Check your inventory: 100 pieces of meat
3. Talk to the beggars and give them something to eat
4. Check inventory: 0 pieces of meat

### Expected behavior

Beggars are too greedy

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-21-0738 0a3e18c [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90.0%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
I believe I've seen that in the past. If I recall correctly I made sure to only carry a single food item of the type when offering it to a beggar (dropping the rest and picking them up afterwards).

**Comment by RenechCDDA** [comment]
This seems to have been introduced by #72759. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/709ea9f83d73ce1dc115a7014071d591d42a80ae/src/npctalk.cpp#L4080

I believe this line should just be `seller_has`, which returns the correct amount to hand over (1) as opposed to everything you're carrying (100).

**Comment by RenechCDDA** [comment]
Adding it to the triage list for 0.H since it was introduced by one of the PRs closing an issue for it.
