### ISSUE TITLE
zone unload leaves auto whitelist container settings

### ISSUE THREAD

**Issue by Killa3999** [CleverRaven/Cataclysm-DDA#73216]
### Describe the bug

Using zone unload zones to unload automatic whitelist containers doesn't remove the automatic whitelist

### Attach save file

N/A

### Steps to reproduce

1. Get some auto whitelisted containers eg. pill bottles of different types of pills
2. Unload said containers with an unload zone

### Expected behavior

Said containers have their container settings cleared, so as to remove ui clutter when containers of the same type are mass unloaded using zone manager

### Screenshots

![image_2024-04-23_120842650](https://github.com/CleverRaven/Cataclysm-DDA/assets/16639078/70901437-7d52-4281-89c8-fd182d3aa72e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 1143055 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    Xedra Evolved [xedra_evolved],
    Culinary Days Ahead [culinary_days_ahead],
    World on Fire [World_on_fire],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm Revamp and Additions [magicrevamp],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Bionic Slots [no_cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrei8l** [comment]
/confirmed `item::on_contents_changed()` is not called consistently when contents are removed. It can probably be called at a lower level, from `visitable`, instead of ad-hoc all over the place.
