### ISSUE TITLE
ImGui: The window after creating a minimized save archive is too small

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73219]
### Describe the bug

While creating #73218, I spotted a second bug! When making a save archive, the window wasn't tall enough for the file path to be displayed on the second line. 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15083689/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

1. Go to the debug menu
2. Select "Info"
3. Create a minimized save archive
4. The pop-up afterwards isn't the right size. 

### Expected behavior

I expected the minimized save archive saving window would be tall enough to include the file location of the save archive. 

### Screenshots

![Screenshot (385)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/10f6b717-da98-4c35-a9bd-7ae271079f04)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause a crash.

**Comment by DragonWizard23** [comment]
Update: Upon further inspection, it looks like the window that should display the file path of the save archive is stacked on top of another window. Namely, the window that says creating a save archive may take a while.

**Comment by NetSysFire** [comment]
Can not reproduce. You are using a 3 week old experimental and there have been imgui fixes in the meantime. Please update and retest.

**Comment by katemonster33** [comment]
Should be fixed by #72936

**Comment by NetSysFire** [comment]
Closing as potential duplicate then.

**Comment by DragonWizard23** [comment]
You are both correct! I updated my version and the issue disappeared. I will be more diligent with my background searching of issues moving forwards.
