### ISSUE TITLE
ImGui Window Size Issue

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73218]
### Describe the bug

The window when using medical items is a little mis-sized. It isn't quite tall enough for the "Press 5 to interrupt" and it is significantly wider that the text. I also noticed this issue when sleeping, where "Press 5 to interrupt" was a little cut off. 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15083667/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

Use a medical item and look at the window at the top of the screen. Alternatively, make the character sleep and look at the window at the top of the screen. 

### Expected behavior

I expected that the window would be large enough to hold all of the text, but not much larger than that. 

### Screenshots

![Screenshot (384)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/d84ae21b-a4c9-46ec-8d77-527bf3483033)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: d2b51fd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause a crash.

**Comment by katemonster33** [comment]
Should be fixed by #72936

**Comment by NetSysFire** [comment]
Another duplicate.

**Comment by DragonWizard23** [comment]
Yep, I made these issues at the same time. I've since updated to the latest version and have not been able to reproduce the issue. :)
