### ISSUE TITLE
The performance of the autosave function is quite slow. Is it possible to handle it in a separate thread?

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#73228]
### Is your feature request related to a problem? Please describe.

The performance of the autosave function is quite slow. Is it possible to handle it in a separate thread?

### Solution you would like.

The performance of the autosave function is quite slow. Is it possible to handle it in a separate thread?

**Comment by kevingranade** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#Performance
