### ISSUE TITLE
Is there any editor or method that can export the construction of my camp into a nested map?

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#73226]
### Is your feature request related to a problem? Please describe.

Is there any editor or method that can export the construction of my camp into a nested map?

### Solution you would like.

Is there any editor or method that can export the construction of my camp into a nested map?

**Comment by kevingranade** [comment]
The save files are raw json as are the nested mapgen files, you might be able to sort something out but there is no tooling that has been written specifically for that.
