### ISSUE TITLE
Half Worms Multiply Upon Their Death

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#73246]
### Describe the bug

Due to recent changes it would appear that now if an "oversized half worm" is killed it will split into two "oversized half worms". This is due to this monster having the same "On Death" function as its predecessor "oversized worm" (via "copy-from" field).

So now each time this monster is killed it basically resurrects and adds another instance of itself.

### Attach save file

[Skyforest-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15100197/Skyforest-trimmed.tar.gz)

### Steps to reproduce

1. Find an "oversized half worm".
2. Kill it.
3. Observe that now there are two  "oversized half worms".

### Expected behavior

These enemies shall be the "line terminators" for the "splitting" enemy line and do not have the ability to multiply.

### Screenshots

![worms01](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/cf177cf9-8feb-492c-8f95-a448ce9f8905)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-04-24-1626 97bec17 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

There may be other issues with incorrect usage of the "copy-from" field in "splitting" enemy types (e.g. slimes).

**Comment by Karol1223** [comment]
Me? Causing a bug via copy-from? Haha I would never...

So yeah I forgot to override their death effect fields. Oopsies. I'll fix that tomorrow.

Also shame on you for hurting them when they're no longer aggressive. The worms will remember this.
