### ISSUE TITLE
Android ImGui cannot be navigated

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#73260]
### Describe the bug

#73180 was introduced as a fix for delay issue on macOS, and hopefully for Android too, but not only the delay issue wasn't resolved (see #73150), it's also impossible to navigate ImGui now.

### Attach save file

N/A

### Steps to reproduce

1. Try to navigate ImGui
2. Observe it isn't possible

### Expected behavior

I expected ImGui to be navigatable with touchscreen.

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/b04fb58f-c800-4ca1-87f3-3dcd8da843d0

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 14; Incremental: G991NKSU4FXD3; 
- Game Version: cdda-experimental-2024-04-24-0616 4551df2 [64-bit]
- Graphics Version: Tiles

### Additional context

Enabling InputTrickleEventQueue fixes this issue, but it isn't possible without third-party apps' help or a keyboard.

https://github.com/CleverRaven/Cataclysm-DDA/assets/52661206/9db5ef3f-00db-4ced-a006-899ade3988c8

**Comment by katemonster33** [comment]
confirmed on latest CI experimental, not sure why i didn't see the error on my local branch experimental
