### ISSUE TITLE
Mound of dirt. Some creatures are immune to fire

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73267]
### Describe the bug

I set fire to the dermatik nest. And waited for it to burn down. I was very surprised when I went in and saw living creatures.

![pict1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/e3a9eeb2-8635-4d0f-ac44-2cc27da2f921)

While the nest was still burning, dermatids were appearing near the nest. But I thought they were coming down from a higher level. Now I think they were flying out of the burning nest. And they were intact.

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15119056/-trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

I hope that fire remains a universal response to the threats of a post-cataclysmic world.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-23-1301 9251ce4 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90.0%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by Venera3** [comment]
Dermatiks avoid fire, and monsters are only damaged by fire on their tile (not heat).
