### ISSUE TITLE
that the items can be separated 

### ISSUE THREAD

**Issue by joaquin-good** [CleverRaven/Cataclysm-DDA#73280]
### Is your feature request related to a problem? Please describe.

I saw that in the game the items accumulate and that causes more space to be taken up in the inventory  

### Solution you would like.

I would like it to be possible to put a key shortcut or something that allows me to decide whether to make 1 or 2 of an item, since there are 2. 

### Describe alternatives you have considered.

Use the + or - key to decide how much to grab or . to grab everything from that specific item.

**Comment by DragonWizard23** [comment]
Are you referring to [b]atch crafting, like this screenshot? You can access this by pressing "b" from the crafting page for the item you wish to craft multiple copies of. 
![Screenshot (393)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/db181498-ea10-40a3-a8ba-bf6a3bfa73b4)

Alternatively, are you referring to picking up a partial stack of items? You can do this by typing the number of items you wish to pick up before hitting the arrow key. 
![Screenshot (394)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/adc6965e-fd6a-45b5-9638-a28a7d1dfd1e)
