### ISSUE TITLE
Duplicate Proficiencies >100%

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73288]
### Describe the bug

I've encountered an odd bug where my character has a couple duplicated proficiencies, with >100% completion. This occurred when updating from an older experimental (~4/2/24) to a recent version (~4/24/24). Likely related to #72861. 
I've tried using debug mode to add the overtrained proficiencies and then removing them, but to no avail. 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15125139/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

Unfortunately, I'm not sure how this happened, other than that it happened when I updated my experimental version. 

### Expected behavior

I did not expect to see duplicate proficiencies, or proficiencies with over 100% completion. 

### Screenshots

![Screenshot (392)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/b6c2b744-0214-4f28-81cd-647d4550eb7a)
Figure 1. The duplicate proficiencies with more than 100% completion (also causing them to spill into the next row). 

![Screenshot (383)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/b9e1acf9-941d-4631-ac07-22f5b69d5d35)
Figure 2. The character's proficiencies before update versions. 

![Screenshot (389)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/f1673414-8a0e-4790-8d48-ac68d975d5c5)
Figure 3. The character's proficiencies stay weird despite debug mode. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 4551df2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause the game to crash. I'm using ImGui, but I don't think that's relevant.

**Comment by Sofistico** [comment]
In regards to this, i also have the same problem!
This was caused after #72693 with the same character from before the update.
Character with the same error:

 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/59299346/ab241706-4959-4a6b-9ca3-0a4b3816f053)

**Comment by RenechCDDA** [comment]
Looks like the game loaded that you had >100% proficiency training, gave you the proficiency, but doesn't know to erase your 'training record'. So it lists both.
