### ISSUE TITLE
If you start out on a office_tower_open_air_corner_roof (added in as a starting location) it can spawn the player at the open air (I assume) leading to starting dead on your first turn

### ISSUE THREAD

**Issue by Hellcommander** [CleverRaven/Cataclysm-DDA#73294]
### Describe the bug

If you start out on a office_tower_open_air_corner_roof (added in as a starting location) it can spawn the player at the open air (I assume) leading to starting dead on your first turn.

### Attach save file

[Grit for Spider-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15130157/Grit.for.Spider-trimmed.tar.gz)

### Steps to reproduce

1. Create a mod that lets you start at office_tower_open_air_corner_roof (by making a starting location file that adds it to possible starting locations and adding to a scenerio's possible start locations). 2. Select it as start location. 3. Warning pops up about not being able to find a safe location for character. 4. After skipping that prompt it might spawn character yelling and dead on first turn on the ground level (likely spawned in open air) and surviving for 0 mins. 5. As a bonus the last few moments of life have you being swapped by the undead infinitely rather then recording the fall that killed you.

### Expected behavior

Spawning somewhere on of the roof rather then into a instant death spawn on ground floor.

### Screenshots

![cataclysm-tiles_Pthslq8uCT](https://github.com/CleverRaven/Cataclysm-DDA/assets/2304030/7ceead63-81e5-4594-b755-2df4a9d7eed8)
![cataclysm-tiles_Jfj3cOUjCW](https://github.com/CleverRaven/Cataclysm-DDA/assets/2304030/c6a39580-6011-44f8-ab36-77b585d512d1)

### Versions and configuration

OS: Windows 11 Pro - Game version: Cataclysm-DDA expermental build 2024-4-26-0553 Graphics version: Tiles Ingame language:English Mods loaded:  "dda",
  "Tamable_Wildlife",
  "package_bionic_professions",
  "betterArachnids",
  "magiclysm",
  "xedra_evolved",
  "Pix's Shit",
  "extra_mut_scens",
  "demon_spider_a",
  "translate_dialogue",
  "alt_map_key",
  "no_fungal_growth",
  "better_bowcraft",
  "Medieval_Mod_Reborn",
  "WHALEYHAIR_UDP",
  "Mining_Mod",
  "sarcophagi_access",
  "culinary_days_ahead",
  "Carlos_Mod_River_Pool",
  "hand",
  "jackledead_armory",
  "light_weariness",
  "recruitment_options",
  "Nonperishable_Overhaul",
  "more_survivor_notes",
  "blazemod",
  "mutant_npcs_new",
  "CBM_Arms",
  "personal_portal_storms",
  "growable-pots",
  "cool_mod",
  "minimod_unpersoned",
  "No_Acid_Zombies",
  "water_towers",
  "hydroponics",
  "dual_class_mages_for_magiclysm",
  "cbm_slots",
  "stop_webs_from_hiding_items",
  "wings_allow_soft_gear",
  "MST_Extra",
  "PSY_magi_spells",
  "arendeth_extra_limbs_allow_soft_gear",
  "more_profession_chooses_extra_mut_scens",
  "new_start_locations_for_extra_mutation_scen",
  "Jap_folklore"

### Additional context

requires a mod that allows player to spawn at this location seems to happen 100% of all tries on making character start there if need a test mod for it https://github.com/Hellcommander/new_start_locations_for_extra_mutation_scen combined with version of mod here https://github.com/Hellcommander/Cataclysm-DDA/tree/master/data/mods/extra_mut_scen(since I have added scenarios that prior mod edits via patch) use any scenarios included from mod (which all start with Mutant) select science lab tower roof

**Comment by Procyonae** [comment]
This is a dumb problem that can happen if a start has any open air, in this case though the omt has no suitable tile for you to be placed on as the only non open air tile is a gutter drop.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/23cfe483-cabd-45a3-beab-034e8cf4aa28)

This can be hackily fixed for omts with suitable spots to spawn by adding zones but the C++ should really just not consider tiles where you'd fall to begin with, ideally also rerolling the omt (with a retry x time fail to avoid getting stuck if no omt has suitable terrain) if there's nowhere suitable at all in an omt

**Comment by Hellcommander** [comment]
thanks I'll remove that as a option
