### ISSUE TITLE
Making phosphorus from bone meal

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#73298]
### Is your feature request related to a problem? Please describe.

Bone meal contain a lot of calcium phosphate, and according to what I've searched on the internet, there are two main ways to extract the phosphorus from the calcium phosphate:
In the first method, calcium phosphate, sand, and charcoal are mixed and heated, and the products include calcium silicate, phosphorus, and carbon monoxide.
In the second method, calcium phosphate and sulfuric acid are mixed and heated, and the products include calcium sulfate, carbon monoxide, water and phosphorus.
However, all of the phosphorus produced by the above methods is white phosphorus, while only red phosphorus is currently available in the CDDA, and in order to convert white phosphorus to red phosphorus, it needs to be heated in air-isolated conditions.
But white phosphorus itself has some uses, we can use it to make smoke bombs and incendiary bombs.

### Solution you would like.

Add item:
White phosphorus
Add Recipe:
Use bone meal to make white phosphorus
Use white phosphorus to make red phosphorus
Use white phosphorus to make smoke bombs and incendiaries

**Comment by ADekema** [comment]
Most of the phosperous in corpse ash comes from bones. You can get a far more concentrated and cleaner source of phosperous with bone ash than corpse ash. Bone ash also has more uses such as being used in commercial fertilizers.

**Comment by Rocket-F-1024** [comment]
> Most of the phosperous in corpse ash comes from bones. You can get a far more concentrated and cleaner source of phosperous with bone ash than corpse ash. Bone ash also has more uses such as being used in commercial fertilizers.

You're right, I just check and found I wrote the wrong item

**Comment by Rocket-F-1024** [comment]
> Most of the phosperous in corpse ash comes from bones. You can get a far more concentrated and cleaner source of phosperous with bone ash than corpse ash. Bone ash also has more uses such as being used in commercial fertilizers.

But doesn‘t the main component of the corpse ashes is also bone ash? All the organic material has been burned out.

**Comment by ADekema** [comment]
> But doesn‘t the main component of the corpse ashes is also bone ash? All the organic material has been burned out. 

True but not everything of the non bone parts burns away so you still end up with more conteminantes. Especially as a survivor is unlikely to burn a body as thoroughly or hot as a normal cremation does. Most likely a survivor is simply gonna burn a body on a pile of wood and take the mixed corpse/wood ash as fertilizer. There is also the fact that you still need to burn away all the non-bone bits which takes more fuel, time and effort. 

So if you want to get a relatively pure mix that is similar to cremation ash to get phosporus from you would either need to specifically burn bones or make a specialized body burning setup where bodies are burned without the ash mixing with other things.

**Comment by Rocket-F-1024** [comment]
> > But doesn‘t the main component of the corpse ashes is also bone ash? All the organic material has been burned out.
> 
> True but not everything of the non bone parts burns away so you still end up with more conteminantes. Especially as a survivor is unlikely to burn a body as thoroughly or hot as a normal cremation does. Most likely a survivor is simply gonna burn a body on a pile of wood and take the mixed corpse/wood ash as fertilizer. There is also the fact that you still need to burn away all the non-bone bits which takes more fuel, time and effort.
> 
> So if you want to get a relatively pure mix that is similar to cremation ash to get phosporus from you would either need to specifically burn bones or make a specialized body burning setup where bodies are burned without the ash mixing with other things.

Maybe we can add incinerators, which can not only burn bodies to ashes, but also throw anything we don't want in there, burning the combustible material in it and keeping the non-combustible material.

**Comment by Rocket-F-1024** [comment]
Completed by the following PRs (https://github.com/CleverRaven/Cataclysm-DDA/pull/74759 , https://github.com/CleverRaven/Cataclysm-DDA/pull/74722 , https://github.com/CleverRaven/Cataclysm-DDA/pull/74599 )
