### ISSUE TITLE
Give Quills to Beast

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#73306]
### Is your feature request related to a problem? Please describe.

The Spines and Quills mutations have been sitting unused in the json files for a long time. They used to be hidden there as a thing that you could get if you got untyped mutations, but those haven't been a thing for a very long time.

### Solution you would like.

Give them to Beast. Porcupines are mammals, it stands to reason that Beast, which is sort of a general mammal thing, could become spiny. They haven't been updated for a bit, so they'd need to be added to the CANCELS list for the No Extras mutation, which would make them properly purifiable. They should probably have Sleek Fur (beast's final fur type) as a prereq as well.

### Describe alternatives you have considered.

Assault Barbs is a cool mutation, but it's really old and I don't think it's up to modern standards. It still works if you debug it in, but there's no such thing as an animal that shoots quills several yards away IRL.

I don't think Chimera should get them, as they're a uniform thing currently and chimera isn't uniformly covered in fur, let alone specialized quills.

**Comment by PGR-14** [comment]
Perhaps Chimera too? Some stories have them shooting out quills.

**Comment by fairyarmadillo** [comment]
> Perhaps Chimera too? Some stories have them shooting out quills.

I specifically said chimera _shouldn't_ get it. Chimeras aren't covered in fur so it doesn't make sense that they'd have keratin spines growing out of their skin. They aren't even uniformly covered in skin.

Every time someone suggests something for beast, people say "oh chimera too." That is bad for both lines, they need to be different.

**Comment by PGR-14** [comment]
Oh, sorry, didn't read that last part.
