### ISSUE TITLE
Several mutations can't be purified?

### ISSUE THREAD

**Issue by carlarctg** [CleverRaven/Cataclysm-DDA#73302]
### Describe the bug

Purifier was changed at some point to work via adding an invisible mutation that deletes incompatible mutations. However, there's a lot of overlooked mutations that can't be removed, due to this. 

The ones I have on my character RN are that I've noticed seem impossible or hard to purify are:

- Beak (Body flag used by Purified mutation) (Removed by Debug on attached savefile)
- Reflex Photopore (Body flag used by Purified mutation)
- Sapiovore (Body flag used by Purified mutation)
- Heat Dependency (Body flag used by Purified mutation)
- Predator (Body flag, but NOT purified by Human Mind)
- Quills/Assault Barbs (No type, no body flag, unpurifiable)

While researching this I came across body flags and how they work. In theory, this should fix the issue, as Beak and Human Mouth are TEETH flagged, but in practice, with Purifier and Catalyst in my system (and nothing else), I kept getting the churning message with nothing updating. Perhaps this was just the purifier adding an invisible human mutation, but I don't know. Something's iffy.

This also means that the HHG 'Purifiable' stat is inaccurate, as purifiable status is also based on there being an override Human mutation now, though that's not really something issues here are for. 

### Attach save file

[Bendersville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15132617/Bendersville-trimmed.tar.gz)

### Steps to reproduce

1. Mutate heavily.
2. Inject tons of purifier.
3. See how some mutations fail to be purified no matter what.

### Expected behavior

While perhaps not ALL mutations should be purifiable, there are some that clearly should and can't.

As an aside, Radioactivity's 3 tiers can't be purified. Unsure if intentional.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 08a7eee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by fairyarmadillo** [comment]
Human Metabolism should probably cancel Predator and Heat-Dependent.
No Extras should cancel Reflex Photophore, Quills, and Assault Barbs.
Human mouth should cancel Beak.
I am pretty sure Human Mind cancels Sapiovore (is its removal being blocked by another empathy trait you started with? That's a bug if so but it might be relevant to the issue), however I'm not sure this mutation ought to be purifiable, as it's an endstage post-threshold mutation that represents a drastic change in the brain structure of the mutant.

As an aside, it's not currently possible to get the Spines, Quills, or Assault Barbs mutations. I think Assault Barbs probably isn't up to modern standards as it allows you to fire quills several yards in a way that no animal is able to do IRL, but the other two would fit right in with Beast IMO. Porcupines are mammals and it seems to be sort of a general mammal thing.
