### ISSUE TITLE
Bugged Dialogue in the Church Retreat

### ISSUE THREAD

**Issue by halfelftwink** [CleverRaven/Cataclysm-DDA#73314]
### Describe the bug

I'm asking this character about his dad, but he's telling me about his mom instead.

### Attach save file

[Omori-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15137170/Omori-trimmed.tar.gz)

### Steps to reproduce

1. Go to the Church Retreat
2. Find the guard on the second floor of the church
3. Ask him to talk about himself
4. Ask him about his family
5. Ask him to talk about his dad

### Expected behavior

I expected to hear about his dad because that's what I asked him about.

### Screenshots

![Screenshot 2024-04-27 172812](https://github.com/CleverRaven/Cataclysm-DDA/assets/166699532/a9c492fe-67b9-4fa0-abab-79c28af8246f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 27b977e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/1b82e689f3d83b529784e32a3c1a0438e55dfc13/data/json/npcs/godco/members/foodguard.json#L198-L199

https://github.com/CleverRaven/Cataclysm-DDA/blob/1b82e689f3d83b529784e32a3c1a0438e55dfc13/data/json/npcs/godco/members/foodguard.json#L211-L212

TALK_GODCO_guard_food_father is the unreachable intended topic, nothing goes it.
