### ISSUE TITLE
[MoM] Burst of speed lets you walk on water

### ISSUE THREAD

**Issue by adamkad1** [CleverRaven/Cataclysm-DDA#73310]
### Describe the bug

Using burst of speed lets you walk on water. You don't swim, because things that could get wet when diving dont.

### Attach save file

N/A, can be easily reproduced.

### Steps to reproduce

1. Aquire burst of speed
2. Find water
3. Use burst of speed targeting water
4. Walking on water

### Expected behavior

Well as stated in here https://physics.stackexchange.com/questions/34597/how-fast-would-someone-have-to-run-to-run-over-water, unless burst of speed lets you run at 20-30 m/s its probably not right

### Screenshots

![cataclysm-tiles_PGaQBfkNf4](https://github.com/CleverRaven/Cataclysm-DDA/assets/22750535/d6e09433-950c-43ad-889c-dbef0f3cf106)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: cdda-experimental-2024-04-26-2043 682d4fb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

Side note: Waiting while standing on water does not make you sink. You have to move to sink.
Also, burst will bring you out of water should you be diving or have sunk.

**Comment by Icantthinkofanameforthis** [comment]
it does say "You move faster than the eye can see." XD

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/1a91701e-684e-4479-b75a-30fc7c1f79cb)

**Comment by Standing-Storm** [comment]
Hmm. This seems like something the Dash effect should not let you do. I can at least have it check whether you’re in water and not let you use it from water (then you could dash across short distances of water but not run across an entire river)

**Comment by emixa-d** [comment]
My survivor, with the mutations "Road Runner"+ "Hollow Bones" + "Padded Feet" 
and with the concentration power "Extended Stride" (int: 18, metaphysics: 10, level: 27) (with Nether Attunement 1) + "Momentum Alteration" (level: 21), has a move cost of 1 when running.

Assuming 1 tile = 1 meter, that's 100 m/s. Even if we leave some margin to tile size, that's much more than 30 m/s.

As such ...

>Well as stated in here https://physics.stackexchange.com/questions/34597/how-fast-would-someone-have-to-run-to-run-over-water, unless burst of speed lets you run at 20-30 m/s its probably not right

This is, in some cases, actually right even when not using "Burst of speed". I now tried running over water(*), and the survivor is getting soaked -- there might be a bug/missing feature here. Or maybe raw speed is insufficient, I'd need to read the paper mentioned in the link.

(*) on water the survivor has move cost 1 too

**Comment by adamkad1** [comment]
> My survivor, with the mutations "Road Runner"+ "Hollow Bones" + "Padded Feet" and with the concentration power "Extended Stride" (int: 18, metaphysics: 10, level: 27) (with Nether Attunement 1) + "Momentum Alteration" (level: 21), has a move cost of 1 when running.
> 
> Assuming 1 tile = 1 meter, that's 100 m/s. Even if we leave some margin to tile size, that's much more than 30 m/s.
> 
> As such ...
> 
> > Well as stated in here https://physics.stackexchange.com/questions/34597/how-fast-would-someone-have-to-run-to-run-over-water, unless burst of speed lets you run at 20-30 m/s its probably not right
> 
> This is, in some cases, actually right even when not using "Burst of speed". I now tried running over water(*), and the survivor is getting soaked -- there might be a bug/missing feature here. Or maybe raw speed is insufficient, I'd need to read the paper mentioned in the link.
> 
> (*) on water the survivor has move cost 1 too

I think its because dashes are considered teleports so they dont trigger walk stuff (Since if you walk onto a water tile from a water tile you either sink or start swimming)

**Comment by GuardianDll** [comment]
while the dash effect still not working properly (specifically, it does not pass the time properly after dash, which should cause you being in water), burst of speed spell itself does not have this problem now
closing it as resolved by #73395
