### ISSUE TITLE
Enemy become passenger in vehicle when rammed or passed slowly

### ISSUE THREAD

**Issue by Zenithir** [CleverRaven/Cataclysm-DDA#73334]
### Describe the bug

While using my car as a weapon, backing into a milspec turret, it popped into my passenger seat upon ramming. Additionally later while driving ~8 MPH by zombies they opened the passenger door and climbed into the passenger seat. Apparently buckled in as I couldn't get them launched out. There seems to be some issue with Every entity wanting to get into a car seat and getting its benefits.

### Attach save file

I'm dead, so not sure i can get that, if possible after death please reach out or comment here.

### Steps to reproduce

1. get in car
2. ram something with car a few times

### Expected behavior

I expected them and the car to take damage not be carjacked.

### Versions and configuration

-version d6ec466

**Comment by cosmo-naut** [comment]
Hey thanks for posting this issue! Could you please rephrase the title to be more descriptive? If somebody else encounters the same bug they will likely try to search for something like "monster appear inside vehicle" and may not realise this issue is describing that problem.

**Comment by Zenithir** [comment]
Is that good?

**Comment by cosmo-naut** [comment]
I think that's much more descriptive, cheers
