### ISSUE TITLE
make faction realistic scaling and/or give us the ability to be able to assign use time bubble to the npc, some stuff don't tick when the npc move far away and it somewhat frustrating 

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#73330]
### Is your feature request related to a problem? Please describe.

when you ask the npc at base to craft or wanting to some corpse to froze in the freezer but they did not get ticked because you were far away , or sending companion on a faction mission but they are some what wounded before being sent and expect them at the end of the day heal their wound

sending npc on a mission that give you too little wood but cost too much food  , like it took you 14 min to chop down a tree to trunk and 4 min to chop the trunk in to log, and it took me 2 hour for 2 tree and get like 13 logs and 13 long stick , but i only test with myself the npc could take more time,  or idk if it calculate it correctly it tell me it take 3 days but when i send the npc it said the npc will be done in 24 hours , but still one days would not just give me only 19 logs, and it only cost somewhere 200 calories to take down a tree and somewhere 200 calories to take down the trunk. so it should cost less than 19-20k calories for 1 days for me. 20k is like 30 tree being chopped all up that would be like 100 log and 100 long stick or somewhat.

plus enable the ability to bring car into place because no npc could bring 19 logs in one trip one weight like 30kg and half of forest of that type have more than just 19 log ,enable option to send team to reduce time to cut them down and transporting food water and fuel and also the option to bring in with you the chain saw to also reduce cutting time.

a place where fire take place and you would want it to burn to clear the path

and some food gathering mission depending on the season for the fruit harvesting and animal information at that location what type of animal would determine the dangerous level

some scout mission to determine the area dangerous level

### Solution you would like.

said above

**Comment by kevingranade** [comment]
Invalid omnibus issue, it's also unclear what is being asked for in several aspects.
