### ISSUE TITLE
Rubik's dialogue line "I'm here to talk about a job." is broken - typo in JSON

### ISSUE THREAD

**Issue by Bulaleks** [CleverRaven/Cataclysm-DDA#73340]
### Describe the bug

Rubik's dialogue line "I'm here to talk about a job." is broken after merging [#73221](https://github.com/CleverRaven/Cataclysm-DDA/pull/73221#issue-2259976782) and produces an error.

In [data/json/npcs/exodii/exodii_merchant_talk.json](https://github.com/I-am-Erk/Cataclysm-DDA/blob/2c39ec308e993457dab1d07e75cda95527ad0d7b/data/json/npcs/exodii/exodii_merchant_talk.json) "topic" on lines 39 and line 156 is defined as "TALK_EXODII_MERCHANT_TalkJob", while "id" on the line 356 is defined as "TALK_EXODII_MERCHANT_TalkJobs".

### Attach save file

N/A

### Steps to reproduce

1. Talk to Rubik
2. select the line "I'm here to talk about a job."
3. Get an error

### Expected behavior

Lines 39, 156 in "topic" and 356 in "id" should state the same value: either "TALK_EXODII_MERCHANT_TalkJob" or "TALK_EXODII_MERCHANT_TalkJobs"

### Screenshots

![RubikBug](https://github.com/CleverRaven/Cataclysm-DDA/assets/15330166/d7b0812b-e298-494a-9268-4cbd30a625f6)
Error after selecting the line.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0e4a71b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    Bombastic Perks [bombastic_perks],
    Bionic Slots [cbm_slots]
]

**Comment by MushroomW** [comment]
got the same error
