### ISSUE TITLE
Four horse cart is slower than a two horse cart

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#73341]
### Describe the bug

If a wagon is modified with two additional yokes at the front and four horses are attached, the resulting vehicle is considerably slower to accelerate than the default two-yoke variant despite having twice as much pulling power.

### Attach save file

n/a

### Steps to reproduce

1. Spawn Wagon (uncovered)
2. Hitch up with 2 horses
3. Drive it, observe acceleration
4. Attach two more 8" yoke & harness, one in front of each existing one
5. Hitch up with 2 more horses (total 4)
6. Try to drive it
7. Observe worse acceleration than in step 3

### Expected behavior

Doubling my horsepower shouldn't reduce my acceleration.

### Versions and configuration

latest experimental

### Additional context

I'm guessing that the weight of the horses is contributing to the overall weight of the vehicle, but the vehicle code assumes that all that weight is being supported by the spindly little wheels of the cart. A quick fix would be to subtract the mass of all harnessed vehicles when determining how much weight there is on the wheels.

**Comment by Consoleable** [comment]
perhaps yokes should count as wheels? this might better enable/model chariots and simple wagons?
