### ISSUE TITLE
Arithmetical error crash

### ISSUE THREAD

**Issue by MintyUwU** [CleverRaven/Cataclysm-DDA#73355]
### Describe the bug

values like strength etc. go below zero when bleeding out, causing the game to crash.

### Attach save file

N/A, game crashes when it happens, also it's easy to reproduce.

### Steps to reproduce

1. Spawn a hostile turret to inflict heavy wounds on player
2. move to safety and watch stats go down when bleeding out
3. once it reaches 0 after few turns game crashes

### Expected behavior

I expected the stats to not lower below 0

### Versions and configuration

OS: Windows 10
Game Version: latest experimental
Graphics Version: Titles
Ingame Language: English
Mods Loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, blazemod, secronom(happens even without this mod)

### Additional context

[mods.json](https://github.com/CleverRaven/Cataclysm-DDA/files/15142148/mods.json)
[worldoptions.json](https://github.com/CleverRaven/Cataclysm-DDA/files/15142149/worldoptions.json)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15142151/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15142152/debug.log)

**Comment by mqrause** [comment]
It crashes when weight capacity reaches 0, because the carry weight widget tries to turn it into percent, causing division by 0.

https://github.com/CleverRaven/Cataclysm-DDA/blob/58f64c0c7f8c9a9f0024d69b35a286ef8b949b70/src/display.cpp#L989

That's what the crash log pointed at. I didn't check if there are more places that divide by weight capacity.

**Comment by MintyUwU** [comment]
what can i do to workaround this?

**Comment by MintyUwU** [comment]
actually i did workaround by deleting that completly and it fixed the problem.

**Comment by mqrause** [comment]
Easiest workaround should be to not have a carry weight widget in the sidebar.

Still very easy actual fix (but C++) would be to return a special string if weight_capacity is 0.
