### ISSUE TITLE
The game code assumes the map goes up to Z=10, but you can't actually go higher than Z=9

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#73353]
### Describe the bug

You can't actually access what should be the top level of the map.

### Attach save file

[8.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15141504/8.test-trimmed.tar.gz)

Note that this is actually a test case provided by @IdleSol.

### Steps to reproduce

1. Building scaffolding on the top of a wind turbine (Z=9) works, because the check that the level above is free is successful (current level < OVERMAP_HEIGHT).
2. However, once constructed you can't go up, you can't look up, and the debug tool to modify the map won't allow you to access Z=10 either (I didn't try to do these things before construction, but assume they don't work then either).

### Expected behavior

If the game is supposed to only reach OVERMAP_HEIGHT - 1 the code should consistently check for that. So far all checks I've encountered have been for OVERMAP_HEIGHT.

What's probably needed is a review of all usages of OVERMAP_HEIGHT (and probably OVERMAP_DEPTH as well) to ensure they all check against the same limit.

Given that the code I've seen consistently have checked against OVERMAP_HEIGHT, I suspect it might be a case of the UI having a faulty restriction. That's supported by the fact that the code didn't blow up or produce a debug report when scaffolding was constructed at Z=10.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9116-gf4014754b9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Qrox** [comment]
The game used to crash when the character or the view moves to z=10. I don't remember why but I think it had something to do with the game not creating submaps at z=10. #71306 changed a few checks to avoid the aforementioned crash, and I think any check against `OVERMAP_HEIGHT` should be updated to treat `OVERMAP_HEIGHT - 1` as the maximum possible z level.

**Comment by PatrikLundell** [comment]
Is there a similar issue with OVERMAP_DEPTH, or should it remain?
