### ISSUE TITLE
Can't consume hypnotic drugs.

### ISSUE THREAD

**Issue by Void-Seeker** [CleverRaven/Cataclysm-DDA#73361]
### Describe the bug

When character tries to consume any hypnotic drug (I tried zolpidem and poppy drug), the message appears in the log, but no effect is applied to the character, and drug itself is not consumed.

### Attach save file

[Квойн-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15143324/-trimmed.tar.gz)

### Steps to reproduce

1. Obtain zolpidem or poppy drug (There are plenty in the west bedroom in attached save file).
2. Try to consume it
3. Check effects and drug amount remaining.

### Expected behavior

Drug is consumed, sleepy effect applied.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.535 (1909)
- Game Version: 99b4944 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(89,2%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    иконки видит-игрока, бег, приседание, кровотечение для retrodays [sees_player_retro],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Скорость от ловкости [speedydex]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15143344/debug.log)

**Comment by cosmo-naut** [comment]
I experienced a similar bug with sleeping pills.
When they were on a shelf next to me, consuming them with 'E' gave me the message but no effect, nor did the count diminish.
When I wielded the pill, pressing 'A' consumed the pill correctly and applied the effect.
