### ISSUE TITLE
Bandits do not bleed to death in no hope

### ISSUE THREAD

**Issue by KaleProgram** [CleverRaven/Cataclysm-DDA#73364]
### Describe the bug

In a very recent build experimental, maybe 2 days old, I found that bandits spawned with the no hope mod were not bleeding in any way. Even after some 10 shots in their torso and heavy arterial bleeding present there seemed to be no blood loss. In the console it did say the bandits were losing blood but nothing evident from what I could see. 

### Attach save file

[Little mercy per que-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15143845/Little.mercy.per.que-trimmed.tar.gz)

### Steps to reproduce

1.seems to work with any gun, but a raider is shot in the torso
2. raider seems to bleed but no damage is done to torso, notice torso hitpoints is still 56.

### Expected behavior

1.From the locational area that the raider is wounded should be continual damaged until they have bled out or patched themselves up.

### Screenshots

N/A gameplay makes it self-evident

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15143852/debug.log)

### Additional context

It seems the bug might extend to raiders as a whole.

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/1b82e689f3d83b529784e32a3c1a0438e55dfc13/src/character.cpp#L8593-L8597

So I technically 'caused' this, it's not no hope related.

**Comment by KaleProgram** [comment]
Oh is the bleeding related to NPC needs being turned off?
