### ISSUE TITLE
Tutorial text window cuts off text

### ISSUE THREAD

**Issue by dennmar** [CleverRaven/Cataclysm-DDA#73367]
### Describe the bug

The text window that pops up in the tutorial can cut off the last character in a line of text.

### Attach save file

N/A

### Steps to reproduce

1. Select Tutorial Game at the title screen. The game will be done loading after player information is displayed on the right hand side (ex: L ARM and Sound).
2. After loading into the game, press the right arrow key (→).
3. Text will pop up at the top center of the screen that displays “clos” on the second to last line.

### Expected behavior

The text window should be large enough to display all characters. In the example given to reproduce the bug, the second to last line should display “close” instead of “clos”.

### Screenshots

![TutorialCutoffText](https://github.com/CleverRaven/Cataclysm-DDA/assets/24706928/cee406da-d663-4322-9309-cbb0d20d96a9)
![TutorialCutoffTextFull](https://github.com/CleverRaven/Cataclysm-DDA/assets/24706928/618385c4-ea14-4c03-b3f3-4a381af8920a)

### Versions and configuration

OS: Ubuntu 20.04 (with WSL and Windows 11)
Game Version: a60d305954
Graphics Version: Terminal
In-game Language: English

### Additional context

Sometimes, the text window will be large enough for all lines of text, but there are multiple instances within the tutorial where a line of text was cut off by one character. This bug can be observed with varying window sizes.

**Comment by GuardianDll** [comment]
Confirmed
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/75820ff8-5f80-4650-8e52-d7812385707d)

**Comment by katemonster33** [comment]
Loaded the latest master, and while I could not reproduce the OP's exact issue (text was not cutoff), @GuardianDll 's issue is present. This is what the linked PR aims to fix.
