### ISSUE TITLE
Make "damaged" medieval weapons be able to be "fixed" 

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73362]
### Is your feature request related to a problem? Please describe.

There are three variants of medieval weapons that can be found, Replica, Bad, & Good. The replicas should stay the same, but I think we should change the Bad versions. 

### Solution you would like.

Pawn shops spawn damaged versions of weapons (Like the battle axe whose head is loose & stuff), & I believe that a reasonable skilled survivor could probably repair them to a good condition. Turns the Bad variants into the Good variant.

Would probably require:
-Skills
Weapon 2-3 (Depending on weapon)
Fabrication 3-5 (Depending on weapon)

-Tools
Tool with Grinding 2
Tool with Filing 2
Tool with Awl 2
Tool with Welding 1

-Materials
3 Leather patches
Superglue
Nail ?
Welding rod/wire/brazing rod (Dunno how many)

Learned:
-Automatically at min level
-New book? Something like "Renovating weapons & armor"

### Describe alternatives you have considered.

Not doing it.

**Comment by portajohn** [comment]
I do like the idea, as is. The bad version is simply described as an actual weapon, bit poorly made or the like. Perhaps having the recipes for the bad -> good version be locked behind the valid book, or just a reasonably high fabrication level (1 less than the normal crafting recipe)

Book wise, if you can learn the n0rmal crafting recipe from a suitable book (ie, historic weaponsmith), maybe add a "repair X weapon,", following the design for crafting as a repair guideline

This is just me spitballing, but I like the idea

**Comment by cosmo-naut** [comment]
As you outlined, there were typically 3 versions of medieval weapons, but I think you might have a different mental model to the intended purpose of those versions. I will also point towards the future direction medieval weapons are moving in.

[The replica](https://cdda-guide.nornagon.net/item/broadsword_fake) is obviously the replica, it is a super cheap knockoff and someone who doesn't know anything about swords could probably tell that it's not the real thing upon a visual inspection.

[The good one](https://cdda-guide.nornagon.net/item/broadsword) is the real one it. It is, for all intents and purposes, a high quality weapon that will perform it's job as intended.

[The bad one](https://cdda-guide.nornagon.net/item/broadsword_inferior) however isn't just a damaged variant of the good one. It is also a replica, but of a higher quality. The material is listed as 'budget steel' and it would likely perform similar to a sword made of scrap in a machine shop. A weapon like this can't be fixed into a better weapon short of melting the entire thing down and starting again, which would defeat the point.

In fact to illustrate this point further, now we have [multiple](https://cdda-guide.nornagon.net/item/qt_broadsword) [variants](https://cdda-guide.nornagon.net/item/ch_broadsword)  [of](https://cdda-guide.nornagon.net/item/lc_broadsword) [the](https://cdda-guide.nornagon.net/item/hc_broadsword) [good](https://cdda-guide.nornagon.net/item/mc_broadsword) version replacing the previous [generic good version](https://cdda-guide.nornagon.net/item/broadsword) that are differentiated by the type of steel they are made of. The generic versions are no longer found in the game.

**Comment by natsirt721** [comment]
The replica broadsword (as so linked) is also listed as being made from aluminum, whereas the good one(s) is/are made from higher carbon steels. Its not just that the non-good ones don't have an edge on them or are poorly crafted, its that the material they're made from prevents them from being any good. Now if you could forge budget steel into a more quality grade that would be one thing, but typically that kind of iron-working is done before or during the shaping of the blade, not after. Basically you'd be better off disassembling the budget sword, turning the material into better steel, and remaking it.

**Comment by PGR-14** [comment]
Wasn't aware of this, nevermind then.
