### ISSUE TITLE
Crash when resetting keybinding

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#73382]
### Describe the bug

game crashes when, after assigning a global keybind, trying to reset that keybind through mouse supported menu

### Attach save file

n/a

### Steps to reproduce

bind PAN UP in item examine to 8 on numpad then try to reset it in the mouse-supported menu latest experimental

### Expected behavior

game does not crash

### Screenshots

![dsafjsdhsjhsrjs](https://github.com/CleverRaven/Cataclysm-DDA/assets/6004660/c30b0d6e-5746-4c67-b788-a65f3f23a144)

### Versions and configuration

latest experimental

**Comment by RenechCDDA** [comment]
Please attach the minimized save archive as it specifically requires you to do. I am unable to reproduce the crash.

**Comment by Headjack** [comment]
[Iago-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15165836/Iago-trimmed.tar.gz)

Here you are.

the original is lost but I recreated it here. To do that I went to inventory with i, looked at a clothing item (long sleeved shirt) with Enter, hit ?, clicked Add Global Keybinding, clicked Pan Up, hit 8 on the numpad, repeated that process for Pan Down but with 2 on numpad, then clicked the x-out on the window, hit yes to save, then went back to that window, clicked Reset Keybinding, clicked Pan Up, then it reproduces.

**Comment by Brambor** [comment]
> (Secondarily, what button are you supposed to hit to scroll the item description down in such a situation to see more information about the item in that panel? < > and [ ] dont work and it doesnt seem like any of these keybinds do it either, incidentally... its neither pan up nor pan down)

It is different for different menus. I recommend opening the keybinding menu `?`, going through it and trying it all. This is a general solution to your problem. I encounter it from time to time. It is `PageUp` or `PageDown` in this case.

**Comment by ZhilkinSerg** [comment]
![image](https://github.com/user-attachments/assets/1b07c316-08d9-49dc-8dfa-a1a75cd41bcd)

**Comment by Brambor** [comment]
Thanks @ZhilkinSerg I will look into it further. I hope you haven't already!
