### ISSUE TITLE
Advanced Nomad Suit - Pocket Setting not saved on activation

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#73387]
### Describe the bug

When you put any rules, priorities or white\black list  on the suit pockets, and then activate it, the rule is deleted.
Doing the same on the activated suit, and then deactivating it also makes the rules vanish.

### Attach save file

N/A

### Steps to reproduce

Spawn suit, have some bionic power to use it, set some pocket rules for it, and activate it.
Check the pocket rules and observe that any rules, or priority you had set it gone.

### Expected behavior

I expect the pocket settings to be saved between activations.

### Versions and configuration

- OS: Linux
    - OS Version: <Fedora 40>
- Game Version: cdda-experimental-2024-04-28-0239 ed85b64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by IdleSol** [comment]
I confirm. cdda-windows-tiles-x64-2024-05-10-2227

#71780

**Comment by Amnestasia** [comment]
Another confirm. Any wearable item with two separate states will not carry over their respective pocket settings, and will remain reset upon returning to their original state.

**Comment by Procyonae** [comment]
Closing as a duplicate issue in favour of #71780
