### ISSUE TITLE
Top part of keybindings menu isn't shown on first open

### ISSUE THREAD

**Issue by dennmar** [CleverRaven/Cataclysm-DDA#73392]
### Describe the bug

On the first time opening the keybindings menu, the top part of the keybindings menu is not shown immediately.

### Attach save file

N/A

### Steps to reproduce

1. Navigate to Settings at the title screen using the right arrow key (→).
2. Press the down arrow key (↓) to highlight Keybindings.
3. Press the enter key to open the keybindings window (for the first time this session).
4. The keybindings window opens with the topmost line beginning as “Toggle language to English…”

### Expected behavior

The keybindings menu should display the top part of the window including the lines starting with “KEYBINDINGS”, “Unbound keys”, “Keybinding active only on this screen”, “Keybinding active globally”, and “* User customized” along with the keys and text for how to remove keybindings, add local keybindings, add global keybindings, reset keybindings, filter, and reset filter.

### Screenshots

Keybindings menu on first open (in this session) before any further input:
![PartialKeybindingsMenu](https://github.com/CleverRaven/Cataclysm-DDA/assets/24706928/4e74acd0-980f-4680-9bb2-2e460688cd59)

The expected full keybindings menu for comparison:
![FullKeybindingsMenu](https://github.com/CleverRaven/Cataclysm-DDA/assets/24706928/d15b74b7-4c09-4b0b-8775-d33fb2216a25)

### Versions and configuration

OS: Ubuntu 20.04 (with WSL and Windows 11)
Game Version: a60d305954
Graphics Version: Terminal
In-game Language: English

### Additional context

This bug can occur when opening the keybindings menu on the title screen or loaded into a world. Pressing a key like the down arrow key (↓) after first opening the keybindings menu will cause the full menu (including the top part) to display. Also, opening the keybindings menu a second time will open the full keybindings menu which includes the top part.

**Comment by katemonster33** [comment]
this one is confirmed too. not exactly certain why our logic isn't working that's supposed to perform a second redraw to draw the missing portions of the screen
