### ISSUE TITLE
Ferals with swords and chainsaws!

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#73397]
### Is your feature request related to a problem? Please describe.

What it says in the title. I'd like to see crazies running around with more than just pipes and axes. Besides, I'm pretty sure if some feral got hold of a machete or chainsaw, they'd try to use it, for better or worse.

### Solution you would like.

Savage Swordsman: "This feral seems to have gotten hold of a sword-like implement, and are now on the prowl for anything not already zombified."
Ripper: "A feral wielding some sort of power tool, sputtering along as their blackened eyes look for anything to mow down in the vicinity."

**Comment by SariusSkelrets** [comment]
For the sword: if you put them in places where swords can be found, then they might work

For the chainsaw: an unpowered chainsaw is an awkward club. A powered chainsaw is really impractical as a weapon (with flaws such as the blade [getting stopped by clothes](https://youtu.be/COlgpvb7ggY?t=229)) with a limited fuel and in this case an operator that either won't refuel it or won't ever stop using it against all targets (same reasonning for the gun ferals not firing them. The required ressource would be constantly used against everything not a feral or a zombie)

So the chainsaw will likely not fit but the sword feral could be added assuming the proper environnment (the same way the rapier-wielding ferals are exclusive to a certain mansion). It just need to be some place where you can expect someone to walk around with a real sword or something similar

**Comment by portajohn** [comment]
Are you on either cdda discord? Development or community?

**Comment by JeveGreen** [comment]
> For the sword: if you put them in places where swords can be found, then they might work

When I say "swords" I don't necessarily mean combat-oriented blades. It could also include stuff like machetes, sickles or repurposed lawnmover blades. Granted it COULD involve some lunatic who was a sword collector or just grabbed a wall hanger-blade from a mall, but the likeliness of that would have to be programmed by someone else, so...

> For the chainsaw: an unpowered chainsaw is an awkward club. A powered chainsaw is really impractical as a weapon (with flaws such as the blade [getting stopped by clothes](https://youtu.be/COlgpvb7ggY?t=229)) with a limited fuel and in this case an operator that either won't refuel it or won't ever stop using it against all targets (same reasonning for the gun ferals not firing them. The required ressource would be constantly used against everything not a feral or a zombie)

You're probably right, as these are among my usual "drunk idea, trademarked," but I can still imagine some tools, at least very early on, would be capable of taking an arm off of a careless survivor. And not all power tools are powered by gas either! There are cordless drills and angle grinders out there which can cause a lot of harm if used (in-)appropriately.

**Comment by JeveGreen** [comment]
> Are you on either cdda discord? Development or community?

I'm not, and probably never will be. I'm horrible at the social thing, probably below the 1-mark....
Either way, I don't care much for talking, so it's probably for the best...

**Comment by PGR-14** [comment]
The machete one's a good idea, it should spawn w/ three variants.
1. Actual machete
2. Makeshift Machete
3. Kukuri

First two make sense, but the third is there for flavor & the fact you can find it in basements.

**Comment by KaleProgram** [comment]
Any kind of katana or longsword wielding feral would likely have to be tied in to their respective followers. So for the longsword feral it could be some kind of renaissance festival where they might spawn at the bastion fort, and for a katana feral that could be a rare spawn at a mall or shrine (hopefully I got that right). As for common blades like previously mentioned that could spawn just about anywhere.

**Comment by portajohn** [comment]
I will add a comment here: I've made a mod that adds a large variety of ferals, though it's meant to be a full conversion from zombie apocalypse to feral apocalypse
