### ISSUE TITLE
Power Tool proficiencies

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#73393]
### Is your feature request related to a problem? Please describe.

Crazy as some some people, and this game gets, I imagine some people would develop a touch for how to use power tools in combat; not just chainsaws, but probably a lot of chainsaws.

### Solution you would like.

I imagine the various tiers would look something like:
Familiarity: The machine in your hands is awkward, but powerful. Treat it carefully.
Proficiency: If making minced meat was your job, you'd be good at it.
Mastery: Kar En Tuk!

### Describe alternatives you have considered.

Frankly, outside of crafting, power tools are fairly underutilized. I'm not asking for Dead Rising-sorts of madness, but there ought to be some sort of way to make mincemeat out zombies with your electric contraptions, right?

### Additional context

For anyone not in the know, Kar En Tuk is a reference from Doom Eternal. It's Argent for "Rip and Tear."

**Comment by cosmo-naut** [comment]
If I saw 'power tools proficiency' listed in-game, my automatic assumption is that it would be crafting related, and not combat related.

Personally, I don't think power tools are realistically a viable long-term weapon. Perhaps a solution in the middle would be to have a single tier "Powered tool combat" proficiency.

Alternatively, I recall there are officially supported mods that have more power tool options. I seem to remember there was a chainsaw lajatang in crazy cataclysm? This is going back a few years though, I'm not sure where that project is currently. The point is, this may be more suitable to one of the 'crazy' mod packs that have are a bit more open about these types of weapons and their suitability in the Cataclysm.

**Comment by JeveGreen** [comment]
> The point is, this may be more suitable to one of the 'crazy' mod packs that have are a bit more open about these types of weapons and their suitability in the Cataclysm.

I agree! I'm just suggesting this in my usual, drunken state! I just wanna see crazy people do crazy shit! XD
