### ISSUE TITLE
Cannot fully close keybindings menu in title screen

### ISSUE THREAD

**Issue by dennmar** [CleverRaven/Cataclysm-DDA#73391]
### Describe the bug

Parts of the keybindings menu in the title screen are still displayed after closing the keybindings menu.

### Attach save file

N/A

### Steps to reproduce

1. Navigate to Settings at the title screen using the right arrow key (→).
2. Press the down arrow key (↓) to highlight Keybindings.
3. Press the enter key to open the keybindings menu.
4. Press the escape key (ESC) to close the keybindings menu.
5. Portions of the keybindings menu are still displayed after closing the keybindings menu. 

### Expected behavior

The keybindings menu should be fully cleared from the display after closing the keybindings menu in the title screen.

### Screenshots

![TitleScreenLeftoverKeybindingsWindow](https://github.com/CleverRaven/Cataclysm-DDA/assets/24706928/b72ff59b-a48c-4800-a0b6-bfe6815388fb)

### Versions and configuration

OS: Ubuntu 20.04 (with WSL and Windows 11)
Game Version: a60d305954
Graphics Version: Terminal
In-game Language: English

### Additional context

The leftover portions of the keybindings menu persist even when performing other actions afterward in the title screen like opening the Help window and looking at the Credits information. However, the leftover portions are cleared when opening and then closing another window like the Help window or the Options window.

**Comment by katemonster33** [comment]
Confirmed. I will try my best to have this fixed as part of #73164
