### ISSUE TITLE
Raise faction reputation through other factions

### ISSUE THREAD

**Issue by KaleProgram** [CleverRaven/Cataclysm-DDA#73404]
### Is your feature request related to a problem? Please describe.

So while clearing out the backrooms in the refugee center I got a little carried away and may have shot one of the guards (whoops). Well I manage to escape and it gets me thinking about the beggars in the lobby, if I take care of them can I prove to the refugee center that I am not the crazy gun wielding psychopath they seem to think I am?

### Solution you would like.

The ability to raise reputation slightly with other factions when completing quests for connected factions. Say I complete a quest for the HUB 01 faction it could slightly raise the reputation of the refugee camp as word gets around and vice versa. The amount it would raise the reputation of related factions would be based on how out and about the faction you completed the quest for is. So since HUB 01 mostly works through mercenaries it would only raise by a slight amount in other factions. But say I were to take care of the beggars in the refugee center it would have a great impact on how the refugee center would see the me. It could even be expanded to causing opposing factions to lower in reputation by a very similar system.

### Describe alternatives you have considered.

The doctor in the refugee center still seems neutral and if connected to the refugee center can be a vessel of which to raise reputation through quests. That or I just forget about the refugee center and take my trading elsewhere.

### Additional context

It'd also be cool to send NPCs to go and represent your faction or do trading for you so that if you may or may have not shot someone in the leg they can go and explain it away. It would be a good way to take advantage of their social skill which seems to have a very limited application right now.

**Comment by PGR-14** [comment]
I think that it should mainly be for the Commune, Refugee center, Old guard, & Beggars together (Only small bonuses though).

**Comment by KaleProgram** [comment]
> I think that it should mainly be for the Commune, Refugee center, Old guard, & Beggars together (Only small bonuses though).

Yes I agree, since there isn't really a major "bad" faction right now, any reputation gained or loss would not have a significant impact on the bandits since they really wouldn't care. Of course I wonder if we'll get a faction like that in the future, almost like a fallout villain with a weird post-apocalyptic vision of society.
