### ISSUE TITLE
Ditch unnecessary tinymap usages

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#73407]
### Is your feature request related to a problem? Please describe.

I've come across some examples where `tinymap` usages seem to be redundant. If verified, the code can be simplified.
However, that only holds if it actually is redundant...

The cases I'm looking at are in `construct::done_digormine_stair` and `construct::done_mine_upstair` in construction.cpp where the code first loads the current map and then creates and loads a tinymap for the Z level below/above and uses the tinymap for access to the stair tile below/above the digging tile (which is accessed via map).

As far as I can tell you can just use the map variable to get the the tile below/above as well and save on the tinymap. Have I missed something that causes that to work differently?
A possibility is that whoever wrote the code carried over the logic from mapgen, where you only have access to tinymap, and thus have to use one tinymap for each Z level.

### Solution you would like.

Just go the straight forward route and use the general map to access both Z levels.

### Additional context

There might be other places too, but these are the ones I saw before deciding to write this issue.

**Comment by Procyonae** [comment]
> A possibility is that whoever wrote the code carried over the logic from mapgen, where you only have access to tinymap, and thus have to use one tinymap for each Z level.

I wouldn't be surprised if you're right there
