### ISSUE TITLE
win10 Codeblocks fatal error: flatbuffers-dev/flexbuffers.h: No such file or directory|

### ISSUE THREAD

**Issue by DayMD** [CleverRaven/Cataclysm-DDA#73416]
### Describe the bug

Using a fresh clean download of 0.G from github, there are no flatbuffer or flexbuffers included in the source, this is also noticable when viewing the source and header files in github itself. It is unclear if this is an issue with the files uploaded or as the end user I have to do something else.

### Attach save file

N/A

### Steps to reproduce

Viewing the source code files on git hub shows no flex buffer.
Downloading the 0.G repository and unzipping also has files missing

### Expected behavior

I would expect to just be able to download the source, open it in codeblocks and let it compile. Or at least it being clear that there is an extra step I need to do.

### Versions and configuration

Windows 10
0.G source code as uploaded to github.
Codeblocks 17.12

**Comment by harakka** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/tree/0.G/src/third-party/flatbuffers

No clue how you should configure codeblocks to find them, it isn't a supported build tool, but there's probably a setting for include paths somewhere. The makefile is the official way to build DDA.
