### ISSUE TITLE
Filter debug menu

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73427]
### Is your feature request related to a problem? Please describe.

Looking at the debug_menu.cpp, there are all the debug options. Maybe it would be easier to first find what you are looking for in an editor and only then in the game, since it is all laid out there and you can filter there. So maybe make a huge multi-column debug in the game, or...

_pic: searching for weather_
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/93cef2a0-6cfc-4083-974d-f7f97b55b91d)

### Solution you would like.

Make the filter in the debug menu which would filter through all the debug options (in your language).
It could be useful. Like when you ctrl+f in a text editor.
Something like filter in the keybindings menu.
Maybe implemented as a new option in `debug > filter` which pops up a popup with a pre-selected filter field

Mockup:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/79e10cf4-3003-4ca6-a203-95d6c5541bce)

**Comment by Qrox** [comment]
You can press `/` in the menu to search, if that's what you mean.

**Comment by Brambor** [comment]
I didn't know!

Still opening the debug menu and searching for "EOC" will not find anything, but there is "Activate EOC" under Debug menu > Game...

This is what I meant.

**Comment by Qrox** [comment]
Yeah, `uilist` only searches for the entry text, not anything behind the entry. Maybe we can make a new UI with expandable entries like the options menu.
