### ISSUE TITLE
[Magiclysm] Forge of Wonders has performance and QoL issues

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#73434]
### Describe the bug

Couldn't think of a title to mention both things but that's what a description is for. There seem to be a few issues that have been lingering since the last time I used Magiclysm (quite sometime ago). And I am surprised some of these things haven't been thought of and/or addressed given the shop/trading overhaul the game's had in the meantime.

**PERFORMANCE**
It is slow to do anything. Reading? Bad. Hauling? Bad. Walking? Bad. Existing? Bad. This is probably the same issue as with other POIs that have variable lighting (instead of being either fully lit or fully dark), too many items on display or too many monsters nearby. 
Probably reducing the number of these monsters would be nice, or just have them spawn if the player "misbehaves" would do wonders too. Otherwise, all they do is wander about aimlessly or literally target everything that isn't the PC (fish, bugs, wildlife, you name it).

**QoL issues**
It gets increasingly annoying having to stop every 10 seconds because the PC sees a Forge Born or a Forge Worker or a Lizardfolk thing. Can they just NOT trigger the safe mode if they are not hostile towards the player?
Another thing is the player can *also* easily walk into them and immediately get wrecked - which is where the safemode would help like it helps with pets and docile lifeforms. 
Another thing that could be added is a dialogue line with each trader that lets the player know when the next restock will happen. Maybe some misc/radiant missions for the player to earn some currency too, especially given the forgemaster is an absolute rip-off, given a lot of prices were nerfed, Hub01 spawns much less and a lot of the ways to "make money" are severely limited. 

### Attach save file

N/A

### Steps to reproduce

1. Create World with Magiclysm
2. Visit the forge of wonders.
3. Disable Safemode because otherwise you can't move among non-hostile creatures.
4. Spawn about 20 books or something and drop them on the floor. (or just spawn like 50 or 60 which is what you'd end up having after raiding a Wizard's tower and a library or two); 
5. Haul them for a bit and see how slow it actually is
6. Try to avoid the "friendly enemies" because you can't use safemode. 
7. Trade first with the Forgemaster - notice how ridiculous the prices are.
8. Trade with the Librarian. Notice how the prices are much more reasonable, despite still being high. 
9. Notice that both traders have no more dialogue options, so if you want to know when their stock refreshes, you're out of luck. 

### Expected behavior

I would expect some of the QoL features added to the basegame to have made their way into the overhaul mods too, especially things like those mentioned. 

### Versions and configuration

Linux - 5d07beb

Mods:
dda
magiclysm
bombastic_perks

**Comment by Maleclypse** [comment]
Reason #1 why you should always include a save game file.  I went to test your performance statements.  
```
It is slow to do anything. Reading? Bad. Hauling? Bad. Walking? Bad. Existing? Bad. This is probably the same issue as with other POIs that have variable lighting (instead of being either fully lit or fully dark), too many items on display or too many monsters nearby.
Probably reducing the number of these monsters would be nice, or just have them spawn if the player "misbehaves" would do wonders too. Otherwise, all they do is wander about aimlessly or literally target everything that isn't the PC (fish, bugs, wildlife, you name it).
```
1. Reading.  Basically the same as any high NPC area. Not specifically a Forge of Wonder's problem.
2. Walking had zero slowdowns.
3. Hauling. It was slow when I had to make multiple button pushes to clear the distraction update each haul but once I opened the distraction manager and disabled hostile spotted it no longer had any slowdown on hauling.

If you had included a save file someone could use a profiler and see if there is something weird happening in your save or something is actually slowing down the game.  Variable lighting and monster movement are not going to be issues with the Forge. If they are issues they need to be solved at the code level not the mapgen level.
