### ISSUE TITLE
[Magiclysm] - Asking Seer to reveal an Orc Village leads to a Goblin Outpost with the mission "Visit the Orcs"

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#73433]
### Describe the bug

As title says. 

Talking to the seer, it sends the player to a Goblin Outpost (Green "G") instead of a place where Orcs would be. I saw no Orcs there, but killed many a Warg and many a Goblins. 

### Attach save file

N/A

### Steps to reproduce

1. Start a World with Magiclysm
2. Visit Forge of Wanders
3. Talk to Seer
4. Ask for Orcs. 
5. Get Goblins instead.
6. Wonder why "orcs = Goblins". 

### Expected behavior

I would expect to get Orcs. 

### Versions and configuration

Version: Linux 5d07beb

mods:

dda
magiclysm
bombastic_perks

**Comment by Standing-Storm** [comment]
This is a result of #71758 -- I didn't realize there was Forge of Wonders dialogue that needed to be updated.

**Comment by AcidAntOnAMinefield** [comment]
> This is a result of #71758 -- I didn't realize there was Forge of Wonders dialogue that needed to be updated.

Huh. 

Tbh quite disappointing to learn that Orcs are just mutated Goblins - imo that makes no sense, as they are different species entirely.
