### ISSUE TITLE
Water purification

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#73436]
### Is your feature request related to a problem? Please describe.

There were discussions about water purification. To summarize:

1. The water purification tablet `use_action` will purify any amount of water. Might be a side effect of the removal of charges.
2. Water purification tablet are listed as an option in the clean water recipe, but even if you have them, they don't show up as usable in the recipe. That's because charge is removed from the tablet, thus it needs to be listed as component.
3. Time needed for water purification is too short. Time needed is 9 second per unit of water in the clean water recipe, and nearly no time with `use_action` of water purification tablet or water purifier.

https://github.com/CleverRaven/Cataclysm-DDA/pull/71971 try to (partly) fix the issue, but is too complex IMO. Though using `delayed_transform` to get clean water is a good approach.

https://github.com/CleverRaven/Cataclysm-DDA/pull/72252 is to add murky water, make regular water safer, and add a new type of water filter. But the recipe that uses the new slow-sand water filter needs 15 minute per 10 units of murky water, that's not realistic, should also use `delayed_transform` here.

### Solution you would like.

Remove `iuse::water_purifier` and `use_action: WATER_PURIFIER`.
For the water purifier furniture/vehicle_part (https://www.netsolwater.com/products-list.php), use it like a washing machine. Fill it with water, open it and wait for a while to get clean water.
For the "portable" water purifier, it should be something like this https://www.amazon.co.jp/-/en/GreeShow-GS-2801-Portable-Purifier-Disasters/dp/B0B27RM1N7. Recipe with a craft time of several minutes would be fine to simulate the behavior of using it.
For the water purification tablet and charcoal/sand filter, first use them to make "murky_water_purifying/water_purifying", then use `delayed_transform` to get water/clean water.

### Describe alternatives you have considered.

Something like https://github.com/CleverRaven/Cataclysm-DDA/pull/71971, while further adjustment is still needed to achieve better simulation of reality.

### Additional context

IRL, water purifier needs its filter to be exchanged. I have no idea whether we should introduce this to dda or not, and how to do it properly.
Also considering adding ultrapure water in the future, and make it needed in recipes of mutagen etc.

**Comment by natsirt721** [comment]
> Remove `iuse::water_purifier`...

I am all for this. IMO any iuse actions that turns items into other items (looking at you, wood axe) should be removed and replaced with the equivalent crafting recipes. Any features lost in that transition should serve as incentive to improve the crafting infrastructure where those features can be adopted globally.

**Comment by osuphobia** [comment]
> > Remove `iuse::water_purifier`...
> 
> I am all for this. IMO any iuse actions that turns items into other items (looking at you, wood axe) should be removed and replaced with the equivalent crafting recipes. Any features lost in that transition should serve as incentive to improve the crafting infrastructure where those features can be adopted globally.

Found out that there are items in some mods(Magiclysm etc) that use this iuse function, so deleting it now might be premature.
Give in a little, the use of this function needs to be limited to magic items, not a water purifier exists IRL.
