### ISSUE TITLE
RE: Faraday chainmail suit - Cannot pad eyes.

### ISSUE THREAD

**Issue by DonOfSandiego** [CleverRaven/Cataclysm-DDA#73446]
### Describe the bug

The faraday chainmail suit makes every single part of your body uncomfortable. Therefore, you must wear padding on every part of your body. Unfortunately for anyone who decided to go through the arduous process of crafting the suit, there is one part of the body that apparently cannot be padded: the eyes.

### Attach save file

N/A

### Steps to reproduce

1.) Wear arming pants, socks, gambeson, gambeson hood, gloves.
2.) Wear any choice of the following: safety glasses, sunglasses, snow goggles, gas mask, etc.
3.) Wear the faraday chainmail suit.
4.) Observe that no matter what you're wearing on your eyes, they are uncomfortable.

### Expected behavior

I expect that safety glasses, snow goggles, or especially gas masks, when worn underneath the faraday suit, will prevent the suit from rubbing against your eyes and making them uncomfortable.

### Versions and configuration

OS: Windows 10
Version: d6ec466

**Comment by AcidAntOnAMinefield** [comment]
It's funny to see this, but this was already addressed after #64207 was published, with #64235 . 

Which was merged just a few days after the build you are using was released.

**Comment by I-am-Erk** [comment]
please let me know if this issue happens to be persistent in a newer version and I will reopen.
