### ISSUE TITLE
Transparent pockets? (Items in pockets visible from afar?)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73445]
Continuing discussion opened in #73400 about transparent pockets.

**Comment by Brambor** [comment]
> I don't recall how much of my recommendation on that first pr ever got implemented.

> We need to track:
> 
>     * have you looked in this container before? Then show the contents.  If not,
> 
>     * Is this container transparent? Then show the contents. If not,
> 
>     * Is this container sealed? Then we should check if there's some kind of label and display that. If not,
> 
>     * Don't show the contents and display "contents hidden" in `V`.

From that list only transparency got implemented. Everything else is still hidden.

> Is this making it so that you can identify the contents of a backpack from across the room using V, because it's not sealed? If so, I'm very much not in favour of that

I agree with that. The question is if you can tell what's inside a pocket when it's not within reach to actually check the contents.
And on top of that, a change like that should be its own PR, it's kinda off topic for this one. Your implementation should simply work with whatever the known contents give you. Fixing/improving the things you get from that is a different thing.

_Originally posted by @mqrause in https://github.com/CleverRaven/Cataclysm-DDA/issues/73400#issuecomment-2088702010_

**Comment by Brambor** [comment]
Looking back, a reason why I was so quick to change `transparent()` is the doc comment, which contradicts implementation.
```cpp
// open pockets are always considered transparent
bool transparent() const;
```

**Comment by Brambor** [comment]
@mqrause and @I-am-Erk, lets continue the discussion here.

**Comment by mqrause** [comment]
An "open" pocket is something like a bucket. Meaning there's nothing holding the contents inside it besides gravity. Originally it was only used for "this container spills its contents if you try to put it into another container", but it got extended to "you can see the contents from a distance". It is explicitly not the opposite of "sealed". Although I'm not sure anymore how an open pocket could be sealed and why I added that check. But I assume there was a reason.

**Comment by Brambor** [comment]
Give me a sec, I am writing the same thing, sorry to call (ping) you before I had this done :(

**Comment by mqrause** [comment]
Yeah, the comments can definitely be improved. I'm not sure what using `_sealed` would achieve, though? It seems that would just enable weird edge cases where `_sealed` is `true` for whatever reason despite the pocket not actually being sealable.

**Comment by Brambor** [comment]
If the container isn't sealable, the `transparent()` returns false. But it should return true, since it is not `_sealed`.

> Yeah, the comments can definitely be improved. I'm not sure what using `_sealed` would achieve, though? It seems that would just enable weird edge cases where `_sealed` is `true` for whatever reason despite the pocket not actually being sealable.

**Comment by Brambor** [comment]
Closely related:

https://github.com/CleverRaven/Cataclysm-DDA/blob/53a0a73092aff1de989b0951e9c1d5eba6d62359/src/item_contents.h#L121-L123

My understanding of the comment differs from what I understand the method does, The method `all_known_contents` returns only top level (not nested) items,

So the comment should be changed and the function should be named `all_top_known_contents` to be consistent with surrounding functions. Or the implementation should change, to call pockets recursively:
https://github.com/CleverRaven/Cataclysm-DDA/blob/53a0a73092aff1de989b0951e9c1d5eba6d62359/src/item_contents.cpp#L1737-L1742

**Comment by mqrause** [comment]
> If the container isn't sealable, the `transparent()` returns false. But it should return true since it is not `_sealed`. Currently, if a bucket isn't sealable (which I would expect), it is considered not transparent, which is weird.

I think you're misreading that. If it's not sealable it's not sealed. So an unsealable bucket is transparent. Unless you can show me it's broken ingame.

> Closely related:
>
> My understanding of the comment differs from what I understand the method does, The method `all_known_contents` returns only top level (not nested) items,
> 
> So the comment should be changed and the function should be named `all_top_known_contents` to be consistent with surrounding functions.

That's correct and I agree. It's used in recursive contexts, so the implementation works as intended and I wouldn't change it, unless you want to do more/different stuff with it.

**Comment by Brambor** [comment]
Pockets that aren't transparent should also not leak their weight. A person cannot see that across the room.

**Comment by Brambor** [comment]
I am letting go for now. But it is a problem that nobody really knows how it should be right now. It is not easy to figure out and it is not trivial to program.
