### ISSUE TITLE
Saw the handle of wood axes a bit, with a saw

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#73454]
### Is your feature request related to a problem? Please describe.

Nope. Not tied to a problem, Its just been bugging my mind a lot lately and i just really want an answer.

### Solution you would like.

Why cant we saw the handle of the wood axe down? I wanna know if theres a different answer than just "because hatchet exists"

### Describe alternatives you have considered.

Literally just find a hatchet.

### Additional context

Im sorry but im just genuinely curious, why no:
![Screenshot_20240502-010121](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/c7a2d52d-cc89-4a8c-8f73-a79578a9b8f2)

**Comment by Srcwya** [comment]
Im genuinely super curious. Im sorry.

**Comment by SomeGuyIGues** [comment]
lmao, this is great.

Surprisingly, there's no hand axe tool in the game, which is what a shortened wood axe would probably be. Hatchets have the hammering quality, which implies it has a hammerhead tool opposite the blade-side. 

Someone could actually make a PR out of this, implementing a hand axe, a recipe for it via blacksmithing or cutting a wood axe short if someone can find a source for the typical blade size if they match roughly. So far I see no issue with cutting the handle short, albeit it might be slightly more awkward compared to an actual hand axe. 

If there is a difference between the blade sizes, the recipe could still be possible if a tool of metal sawing quality is also used to cut down the blade to a more appropriate size.

**Comment by Aerin-of-the-Toast** [comment]
> lmao, this is great.
> 
> Surprisingly, there's no hand axe tool in the game, which is what a shortened wood axe would probably be. Hatchets have the hammering quality, which implies it has a hammerhead tool opposite the blade-side.

It doesn't, actually. A hatchet has hammering 2, and hammering 2 only means "you could drive nails into wood with this without much difficulty" more or less. It doesn't have a proper hammer-shaped hammer tool, it's just that you can hammer nails with the back or the flat of the hatchet pretty easily.

**Comment by SomeGuyIGues** [comment]
> It doesn't, actually. A hatchet has hammering 2, and hammering 2 only means "you could drive nails into wood with this without much difficulty" more or less. It doesn't have a proper hammer-shaped hammer tool, it's just that you can hammer nails with the back or the flat of the hatchet pretty easily.

![20th_Century_Hatchet](https://github.com/CleverRaven/Cataclysm-DDA/assets/154325171/6afc26e6-a272-4d7d-9e42-0571aa5cca9b)

**Comment by Aerin-of-the-Toast** [comment]
That is *an* example of *a* hatchet but it is not every hatchet ever. The item is generic enough that it includes hatchets that don't have the hammer head, which still would be fit for hammering 2.

**Comment by IdleSol** [comment]
What for? There's an hatchet in the game https://cdda-guide.nornagon.net/item/hatchet

If you saw off part of the handle, the axe becomes less comfortable. For the game, this is at least a reduction in the quality of cutting trees from 3 to 2 or 1.

**Comment by PGR-14** [comment]
Let's say all hatchets are the one w/ the blunt end, for simplicity.

For the hand axes, there should be 3 types:
- Regular (Manufactured as a hand axe)
- Hand Wood Axe (Sawed wood axe)
- Hand Fire Axe (Sawed fire axe, removes bar pocket)

**Comment by fairyarmadillo** [comment]
The wood ace has a bigger head and stouter handle than a hand axe. Sawing its handle down would just ruin it.

There is a hand axe in the game, it's the hatchet.

**Comment by natsirt721** [comment]
> The wood axe has a bigger head and stouter handle than a hand axe. Sawing its handle down would just ruin it. Axes designed for one handed use have slimmer handles and much smaller heads.

This. Not only would the balance be way off, but you'd also lose the palm swell at the base of the handle, which would make it even more difficult to control. It would probably be straight-up worse than a purpose-built hatchet, the only upside being portability.

As for the hammering, although most hatchets do have a poll (the hammer-y bit opposite the blade) that could serve as a hammer, they are not made for driving nails. Driving tent stakes and some light 'bonking' work, but definitely no substitute for a proper hammer. The poll on my hatchet is slightly rounded, which I can only imagine would make driving nails pretty frustrating. Some types of hatchets (e.g. a roofing hatchet) do have a proper hammerhead on them, but these are the exception to the trend. Hammering 2 is the proper quality - adequate but not ideal.

**Comment by Srcwya** [comment]
Ah, i see

**Comment by kevingranade** [comment]
Issues are not here for asking random questions about the game, we use multiple sites for discussion that you can find at https://cataclysmdda.org/ that are perfect for this kind of thing.
Meanwhile we are completely overloaded with issues, currently at 1,900 open, please don't add to this.
