### ISSUE TITLE
[MoM] Perfected Motion + Extended Stride can make you move impossibly fast

### ISSUE THREAD

**Issue by Cress67** [CleverRaven/Cataclysm-DDA#73471]
### Describe the bug

With sufficiently high intelligence, and a sufficiently high level in Perfected Motion and Extended Stride, combining them both together can make your movement cost negative. This lets you move an arbitrary number of tiles per turn, as time will not progress so Perfected Motion will never tick down and the buffs will continue forever. Time only advances when you intentionally pause or do something other than move, which can allow Perfected Motion to finally tick down and end. 
For my own character, 14 Intelligence and 20 in Perfected Motion and Extended Stride was sufficient, with 0 nether attunement.

### Attach save file

[Piedra Gorda-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15197216/Piedra.Gorda-trimmed.tar.gz)

### Steps to reproduce

1. Make a fresh world with Mind Over Matter installed. 
2. Make a fresh character, either starting with 14 Int or debugging it in at the next step.
3. Debug their Spell Levels for Extended Stride and Perfected Motion to 20.
4. Cast the spells until they succeed once each.
5. Note that you now have an Enchantment applying -105% to your Move Cost, and that your Move Cost value is now negative.
6. Move around and see that time does not advance, even when moving across difficult terrain like benches and such.

Otherwise, just load up the save and move around. The effects are already present, although I did reset Stamina to full to see if that'd change anything (it did not).

### Expected behavior

I expected to be inhumanly fast, not impossibly fast.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

### Additional context

You can achieve similar results with Momentum Alteration instead of Extended Stride, if your levels in Perfected Motion and Momentum Alteration are high enough. I just threw my test character's Int to 20, the level in both powers to 30, and set his Metaphysics to 10 to be able to gain Noetic Resilience's power buff to hit the intended hardcap on Move Cost Reduction on both, which still pushes over 100% and lets you move infinitely fast.  It's just much easier to do legitimately with Extended Stride+Perfected Motion.

**Comment by Standing-Storm** [comment]
They're both multiplicative powers, so theoretically there should be no way for move cost to flip over into negatives. This is not the first time multiplicative stacking has reduced something below zero, though.
