### ISSUE TITLE
Apex Predator not preventing focus loss

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#73484]
### Describe the bug

Apex Predator (PRED4), according to its json flag note, is supposed to prevent focus loss from training combat skills. This is not the case.

### Attach save file

N/A

### Steps to reproduce

Make a character with the Apex Predator mutation. Attack something. Focus goes down.

### Expected behavior

Focus should not decrease.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-03-0220 abe3f76 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This is a 5-stage post-threshold mutation that significantly reduces your ability to learn other things, so it's pretty important that it gives the stated bonus.

**Comment by RenechCDDA** [comment]
Unable to reproduce. Please provide a save for this issue.

**Comment by fairyarmadillo** [comment]
Going to close this until I can triple check and confirm what I was seeing with a save.
