### ISSUE TITLE
npc keep throwing weapon i don't know if this related to new update or not

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#73480]
### Describe the bug

npc throwing stuff like base bat aluminum baseball bat, knife, pr 24 baton, baton, bayonet, some pistol sometime, idk if the pistol one been fixed

### Attach save file

[fucking new world-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15202747/fucking.new.world-trimmed.tar.gz)

### Steps to reproduce

giving npc either trade or ask them to use those said weapon, i also have throwing grenade (off) to those npc

### Expected behavior

they do not use any of those weapon as a throwing object

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/63102395/d385fc58-c5bb-42cb-9029-40367aa8871c)
### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3447 (22H2)
- Game Version: cdda-experimental-2024-04-23-0405 7f16ac8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    TropiCataclysm [tropicata],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills]
]

**Comment by RenechCDDA** [comment]
The provided save is just some random farm building with no enemies in sight. Please provide a save where the issues actually occurs.

**Comment by blablase** [comment]
> The provided save is just some random farm building with no enemies in sight. Please provide a save where the issues actually occurs.

welp gonna wait next time
