### ISSUE TITLE
What happened to the water? Map generation error?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73489]
### Describe the bug

That's the river on the left. An earthen river.

![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/d22682ce-f9f1-40af-b2f3-a462a9c8d8cd)

Oh, look at the new pools. I hear the mud baths are quite popular.

![test 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/47f58bf5-b9c8-4600-b491-54efe61bc0aa)

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205595/test-trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Screenshots
![test 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/82b3acd1-a067-4737-9a22-ca834a558017)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-03-1808 0a74bb4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
It's my fault... Sorry!

I screwed up when introducing support for empty space. That caused the roof adding magic to consider deep water to be empty space suitable for a "roof" for the ground beneath it (and that "roof" is dirt).

The good thing is that it's been fixed and accepted into master, but the bad thing is that the damage caused won't be undone. Thus any new deep water features will be generated correctly, while the destroyed ones will remain destroyed.

**Comment by NetSysFire** [comment]
Couldnt you fix this with the debug menu by regenerating the affected overmap tiles?

**Comment by PatrikLundell** [comment]
Well, yes, it should be possible to do a few hack things, all with their own drawbacks:
- Delete the affected files from the save, causing the game to regenerate the overmap tile. This causes a new version of it to be generated, so any stuff stored on it is lost, cleared monsters are replaced, and the layout will be different.
- Do the same thing via the debug menu by replacing the overmap tile. This has the same drawbacks as the above, as it's really doing the same thing through a different path.
- Manually restore each incorrect dirt tile with deep water one tile at a time via the debug menu. It's potentially a lot of work, but has the advantage of not affecting anything apart from those specific tiles.

**Comment by IdleSol** [comment]
I must have misunderstood you. But this is a brand new save created in this version of the game. This world was created to find generation errors in house tiles.

So all new worlds created in future versions will have this.

**Comment by NetSysFire** [comment]
It is fixed in master. Update and the worlds will no longer generate like this.

Closing as fixed.
