### ISSUE TITLE
It's possible to install a training dummy without diggable groud

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73483]
### Describe the bug

The description of the training dummy mentions that it needs to be embedded in the ground in order to be used. This is done using a construction recipe, which requires a tool of digging 2. However, it doesn't matter where you build it, whether it's on concrete or dirt. 

### Attach save file

N/A

### Steps to reproduce

1. Get a training dummy
2. Use `*` to install the training dummy on a surface that doesn't make sense, such as a road or sidewalk. 
3. Ta-da! You've replicated this bug. 

### Expected behavior

I expected that the dummy would have to be installed on a diggable surface, such as dirt or gravel. It should not be able to stand on concrete because it will not have enough support (though perhaps adding sandbags to a similar construction would make sense). 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/91d80fb9-e6db-403f-86a9-45e5295a71c0)
The training dummy installed on a sidewalk. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 4551df2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

The bug does not cause the game to crash.

**Comment by Consoleable** [comment]
I can confirm this issue, an alternate recipe for installing on other surfaces is desired. really, a weighted stand should suffice.
