### ISSUE TITLE
Tile spawning error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73490]
### Describe the bug

Mostly incorrect tile placement. Some points may be debatable.

1. house_detatched5_north. Should be linoleum, just like the rest of the tiles.
![pict 1 house_detatched5_north](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/5ea8f16d-a3a6-4812-a585-c55e7e635d3c)

2. bungalow23_west. Reverse situation. Linoleum is located here, but there should be a regular floor: `floor`.
![pict 2 bungalow23_west](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/56e63b39-ee29-4c06-99a9-f0fcecda3aaa)

3. house_34_west. Under the flowerpot, there should be a `floor`. With the pantry, it's a moot point. There is linoleum located there. I think it should be the same floor as the rest of the house.
![pict 3 house_34_west](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/90a7a6e7-33ce-4bc8-9397-9dd81c60e8c2)

4. house_38_west. Under the flowerpot, there should be a `floor`.
![pict 4 house_38_west](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/3e71fef2-3460-44c1-88f4-86c67b2cee0f)

5. gambling_hall_south. We need linoleum.
![pict 5 gambling_hall_south](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/da250a27-fcc5-4839-8445-7e52fcd85a33)

6. urban_10_1_south. A piece of pavement in the house and pantry.
![pict 6 urban_10_1_south](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/c25886fc-a31c-431d-b096-56a794e8a1e8)

### Attach save file

[1.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205894/1.test-trimmed.tar.gz)
[2.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205895/2.test-trimmed.tar.gz)
[3.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205896/3.test-trimmed.tar.gz)
[4.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205897/4.test-trimmed.tar.gz)
[5.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205898/5.test-trimmed.tar.gz)
[6.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15205899/6.test-trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-03-1808 0a74bb4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by IdleSol** [comment]
7. hous_wooded_north. Linoleum must be placed under the bathtub.
![pict 7 hous_wooded_north](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/3feee859-a1e0-4b82-9cb1-ada6c30e5538)

8. s_restaurant_coffee_east. Linoleum is missing again.
![pict 8 s_restaurant_coffee_east](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/77d46952-a12d-49a1-b1c4-984b5e4cd27f)

9. house_porch_basement_south. And here we forgot about the carpet.
![pict 9 house_porch_basement_south](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/4b075fed-75ca-4f08-b15b-9ffdbbf2e5cc)

10. house_37_east. Apparently flower pots don't like regular floors.
![pict 10 house_37_east](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/cea8a18d-6942-45cd-b3e6-7133f9046d55)

11. basement. Just a basement? No numbers or specifics. There's `concrete` under the boxes instead of a `floor`.
![pict 11 basement](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/17622075-c3e7-4972-918d-9132114879c1)

**Comment by IdleSol** [comment]
I have two questions:

1. Is there an easy way to get all the buildings on one map, without repeats? Something like creating a test world.

2. Those who are engaged in creating new maps. Are you comfortable working with such a system? I mean, how in one section you have to specify: terrain, furniture, items and the rest? Wouldn't it be easier to divide them into at least two sections? One for the building itself, where only structures would be included, and the other for the rest? Perhaps with monster spawning separated into a third section?

**Comment by PatrikLundell** [comment]
1. There is debug support where you can specify what an overmap should contain, so you could presumably specify them one beside the other from the list the overmap editing tool provides you with. It's obviously tedious if you want to get the lot, but doable. Beyond that I'd assume it would be possible to add code that does that, although the problem is for the code to "know" what to place and what to skip (just going through all of them probably creates a rather odd mix of housing and terrain). You also have the issue of things that are larger than a single tile.
2. I'm not making new maps, but separating things into layers brings another issue with it: namely alignment. As soon as you decide to shift a part of the structure you'll have to go to the other layers and shift them accordingly.

**Comment by casswedson** [comment]
/confirmed /good-first-issue

the hardest part is finding the mapgen ids with errors so this is pretty straightforward

**Comment by NukeShot58** [comment]
is it fine if i try fixing this one?
