### ISSUE TITLE
Replace the old UI method for displaying various information in the right-side window of the game with a new implementation using imgui.

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#73497]
### Is your feature request related to a problem? Please describe.

no
Replace the old UI method for displaying various information in the right-side window of the game with a new implementation using imgui.

### Solution you would like.

Replace the old UI method for displaying various information in the right-side window of the game with a new implementation using imgui.

**Comment by RenechCDDA** [comment]
* #55503

It's a huge project, and it'll be done *when it's done*.

We don't really need issues which ask us to work on what we're already working on, or to do the migrations we plan to already do. I'm going to close this issue.
