### ISSUE TITLE
[Interface] Add an option to consume beverages immediately after crafting

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73496]
### Is your feature request related to a problem? Please describe.

Occasionally, I run into an issue when I prepare too many beverage servings at once, and I don't have the capacity to store all of them. Instead of being able to drink the extra directly, I have to pour it onto the ground. 

### Solution you would like.

I would like an option to consume beverages immediately after crafting them, in addition to the options of pouring into a container or pouring onto the ground. 

### Describe alternatives you have considered.

It probably shouldn't be possible to make more beverages at once than you have liquid capacity for. How would you contain the beverages while making them? As an example, how could you make 1 L of coffee at once using a container that only holds 0.5 L?

### Additional context

Here is a screenshot of the menu I'm referring to. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/f39ecb78-80fd-4954-84fd-76db2e94331e)

**Comment by PGR-14** [comment]
I'm guessing you're drinking it out of the pot?

**Comment by Void-Seeker** [comment]
A long time ago there used to be exactly that option.
