### ISSUE TITLE
Feedback on new exoskeletons mk1-3

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73491]
### Is your feature request related to a problem? Please describe.

I had an older model of the exoskeleton looted from a TCL prior to updating to an experimental version that had the new models.
I like the overall direction of the changes, however, a few things still annoy me that I think can be improved.
First, the save -> update process, the rig itself became a mk2. Only the helmet into medium helmet armor, I did not get any of the torso, arm or leg armor pieces.  I ended up debugging them into the game because I felt cheated.
The diesel frame piece disappeared, not a big deal I never used it. However, maybe convert the diesel frame piece into one of the other armor types on the update?
the hauling frame also disappeared, also not a big deal since the new version can actually hold stuff. Again, maybe convert the hauling frame into one of the other missing plate armors?

The WATCH property only exists on the (on) version? This seems like a bug or an oversight. Why would it not exist on both the on and off versions when a simple unpowered watch can already do this?  It would also be great if it could show the temperature like a diver's watch does as well.

I'm very glad my character can now wear close-to-skin items underneath the exoskeleton, the naked requirement of the old one felt very silly. It will drive up the desire to find cut-resistant sleeves, cut-resistant balaclavas, leather corsets/chest wraps (there is no close-to-skin cut-resistant torso clothing like a concealable stab vest?), etc,  just to get a little extra protection. (if you can handle the heat build-up) 
I have not tried doing the chain mail reinforcement yet to the armor pieces, but it looks promising.

Two-way radio is nice except only when it is turned on? That makes it not so nice. Can it be available when off and still use a battery charge? Or should two-way radio be removed and just add a pocket to insert one with its own battery into the helmet like was done with the flashlight?   (A helmet flashlight pocket is nice, why isn't a radio helmet pocket standard on most helmets, or a radio earpiece model of two-way radio in existence? If there is I haven't found one.)

Adding stuff as MOLLE attachments is a good idea in general, though adding them to the torso plate and not to the suit directly seems odd, it makes the UI nesting more tedious.  Also, it seems like the encumbrance starts jumping up a lot with not very many items added.   I don't know if this was intentional or not, but it made me start looking at alternate leg/arm/foot/wrist places for strappable storage just to keep things off my torso when using the exoskeleton, this is even with the encumbrance drop when the thing is on. Looking forward to seeing how the survivor harness and distributed rigging work with the exoskeleton to alleviate this once I craft them.

I have not fought anything tougher than an Antlered Horror in the new exo suit yet because I already clear out many area around my base in the game. I dont have much feedback on combat, the armor is good, the antlered horror at least did nothing, though so did I until I realized I had forgotten to turn it on.  

The thing I miss the most about the old suit - the rifle pocket.  I'd really like to see this return in some form. I miss it because I like using a spear in a spear strap for melee and a slung rifle for ranged or bigger threats. Having the overlapping rifle sling and spear strap mess with encumbrance though is annoying so I really liked the rifle pocket freeing that up.

Is there a way to log a warning to the user when the remaining battery power drops below a certain level?

Spare Battery pocket?   

### Solution you would like.

Described above already.

### Describe alternatives you have considered.

Described above already.

**Comment by fairyarmadillo** [comment]
It probably only shows the time when it's on because the display is digital, like on your phone.

**Comment by O1OOO1O** [comment]
[Kinetic](https://en.wikipedia.org/wiki/Automatic_quartz) 'no battery' watches have been a thing for decades now.

Digital watches also last at least 2 years for the really cheap ones, 6 years for better and high-quality ones can last up to 20 years. This is a long enough time frame to be practically forever in this game to not worry about it.
 https://www.weidewatch.com/article/detail/how-long-does-a-digital-watch-battery-last.html

**Comment by fairyarmadillo** [comment]
But it isn't a watch, it's an exoskeleton. My phone doesn't have a clock display that works when it's off.

Just because it's technically possible doesn't mean it should exist. It'd be handy if all cars came with pemmican and m240 turrets, but they don't.

**Comment by ADekema** [comment]
Maybe the exoskeleton should have a effect where it ignores the encumbrance of other gear when turned on. The rational would be that the the armor becease it is effectively carring itself would also be carrying anything strapped to it.

**Comment by Kywi001** [comment]
I've not really used these new exoskeleton yet, but a few things that I know,

Normally, youre not supposed to wear anything aside from the exoskeleton and a few underlayers, its just that, we tend to wear a lot more than how theyre supposedly designed,

As for the "it's not showing time" or "its an expensive piece of equipment", its using a digital display like the VR headsets, so no wonder they dont show time when its not powered on, I mean, yeah, "digital clock" exists, but these exoskeletons arent designed like that,

I mean, these things are not something youre supposed to wear permanently, that's just a cdda thing.

**Comment by Zireael07** [comment]
*waves hand* I have used a real world (medical) exoskeleton and I can tell you that 

1) you are supposed to dress lightiy but normal, not just underlayers (so no jackets but everyday things like sweaters - and all associated underthings - are more than fine)
2) those *do* have a display when turned on - my therapist can then read lots of data from it so it's def more than a watch - but its power consumption is negligible compared to what the exoskeleton itself draws

**Comment by Kasgigz** [comment]
Another thing to note : Since the helmets were removed and parts like arm, legs, torso and head armor have been added as attachments, no helmet shows up on the characters for all tilesets that otherwise would. It's probably just in need of a tile update but since i've seen nobody talk about it i'll just mention it here. Not sure if it's worth opening an issue.
