### ISSUE TITLE
Molotov Cocktail creates raging fire instead of small fire

### ISSUE THREAD

**Issue by AnotherSeawhite** [CleverRaven/Cataclysm-DDA#73495]
### Describe the bug

Self explanatory title.

### Attach save file

N/A

### Steps to reproduce

1. Make a Molotov Cocktail
2. Light it up, throw it onto the ground
3. Open a gateway to hell

### Expected behavior

I expected Molotov Cocktail to make small fire instead of a gateway to hell.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G991N; Release: 14; Incremental: G991NKSU4FXD3; 
- Game Version: cdda-experimental-2024-04-24-0616 4551df2 [64-bit]
- Graphics Version: Tiles
- Game Language: 한국어 <color_dark_gray>(58.7%)</color> [ko]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ADekema** [comment]
I don't see the problem. From riot fotage I have seen a molotove can generate quite the big fire and definetly shouldn't generate a small fire. If they did generate only a small fire they would be next to useless as a offensive weapon which they are intended to be.

**Comment by AnotherSeawhite** [comment]
The issue is that raging fire is really, really big, so big that it kills a zombie in a second.

**Comment by Void-Seeker** [comment]
Historically, Molotovs were invented as low-tech anti-tank weapon. They were meant to set armored vehicle engines and interiors on fire on direct hit, when burning liquid is pulled into the grates and vents.
