### ISSUE TITLE
You can't scroll down the shortcuts' page in new UI (Mobile)

### ISSUE THREAD

**Issue by Elshad19** [CleverRaven/Cataclysm-DDA#73499]
### Describe the bug

I've posted this to reddit, so I figured I'd post it here too.

1) Basically, in mobile version, you can't switch inventories during a trade, because you have to press a button (Tab) which doesn't exist on digital keyboard. However the said button exists in game's options settings as a contextualized shortcut. This leads to the main problem:

2) I can't seem to scroll down the help page where you can customize shortcuts. I pressed all button, but there is no way to scroll. Swiping down doesn't work as well. Pressing "+" enables me to modify the shortcuts, but I need to see the whole list.

### Attach save file

N/A

### Steps to reproduce

1. Find a neutral NPC willing to trade. 
2. Go to the trade page.
3. You can't switch between your and NPC's inventories as tab doesn't exist on mobile.
4. Go to help section by pressing "?".
5. You can't scroll down in new UI using any buttons.

### Expected behavior

1) Tab should exist as a contextualized shortcut at the bottom during a trade as it does in settings panel. 

2) You should be able to scroll down the help page in UI by using contextualized shortcuts or touch/swipe. 

### Screenshots

![Screenshot_2024-05-04-09-14-04-325_com.cleverraven.cataclysmdda.experimental.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/87479123/3dad8fa8-3b4a-414e-a330-39e5d53bb8ea)

Note: pressing > doesn't switch inventories.

![Screenshot_2024-05-04-08-38-55-058_com.cleverraven.cataclysmdda.experimental.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/87479123/64c8e98f-eeb0-41e1-9c6c-4deaa0bfd6c3)

![Screenshot_2024-05-04-08-38-52-679_com.cleverraven.cataclysmdda.experimental.jpg](https://github.com/CleverRaven/Cataclysm-DDA/assets/87479123/ece43a50-e7c8-46c7-a9a9-21f4d15bc473)

### Versions and configuration

- Android 10 / Ram 4 GB
- Game version: 7dd8b1b (the latest as of now on 04.05.2024)

### Additional context

N/A

**Comment by db48x** [comment]
Thanks for the bug report, but it looks like you have reported three different bugs at once. Could you edit this one so that it contains information about only one bug, and file the other two individually as well?

**Comment by Elshad19** [comment]
> Thanks for the bug report, but it looks like you have reported three different bugs at once. Could you edit this one so that it contains information about only one bug, and file the other two individually as well?

I read somewhere that there are a lot of issues currently, so I thought it would be best to post three small issues in one post, so it doesn't clutter. 

I am not a contributer, so are you sure that is the best idea?

**Comment by db48x** [comment]
Yes, I am quite sure that it is the best idea. There is no such thing as clutter, but putting multiple problems in the same bug report makes it much more difficult to track completion, defeating the purpose of having bug reports in the first place.

**Comment by Elshad19** [comment]
This bug is fixed as I can scroll within the help menu. Therefore I closed the issue as completed.
