### ISSUE TITLE
`You could use it to craft` for `giant wooden screw` returns many unrelated recipes

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73507]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/19ae5e1c-171c-429e-9777-71e1ba575eb8)

### Attach save file

[Game-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15210119/Game-trimmed.tar.gz)

### Steps to reproduce

1. Open crafting menu `&`
2. Search for `giant wooden screw`
3. Look at the unrelated recipes under "you could use it to craft"

### Expected behavior

It should list only things where this is a component, right?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9265-g45fc0547f7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9265-g45fc0547f7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Did I break it? I touched this thing somewhat recently in regards to NPCs...

**Comment by osuphobia** [comment]
...isn't these listed recipes use the byproduct splintered wood as a component?

**Comment by Karol1223** [comment]
> ...isn't these listed recipes use the byproduct splintered wood as a component?

It is. This part of the UI is for splintered wood, not the screw

**Comment by Brambor** [comment]
Thank you very much! I sometimes get confused by this UI. But that is on me. I specifically approved it :D.
