### ISSUE TITLE
Hunted Forever relentless hulk becomes the Flash

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#73516]
### Describe the bug

In the Hunted Forever scenario, the relentless hulk has a buff that increases Bash, Stab, and Cut armor by 1 and speed by 1% per time it's killed. 

However, when testing something else and manually setting the `Nemesis_iteration` to 25, the hulk seems to become many times faster, not simply 25% faster.

### Attach save file

[Hebbronville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15211468/Hebbronville-trimmed.tar.gz)

### Steps to reproduce

1) Load up game. The hulk is 6 squares away.
2) Using debug menu, check global variables and see that `Nemesis_iteration` is 25.
3) Wait one turn
4) The hulk instantly crosses the 6 meters and hits you dozens of times, killing you. 

### Expected behavior

The hulk becomes faster, but Speed  119 (base 95 * 1.25), not so fast as to be totally unstoppable.

### Screenshots

Ouch:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/e00068de-7d02-4d98-92c2-effeb8956f5c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-04-1558 64321d6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I originally thought this was some error I made when making the Mindhunter scenario, but it persists in the base game.

**Comment by RenechCDDA** [comment]
How terribly interesting. All right, I guess I have to do some work to figure out what's going on here.
