### ISSUE TITLE
[MoM] Faster power learning 

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#73519]
### Is your feature request related to a problem? Please describe.

So much pain to wait until you can learn necessary power, especially when you have more than 2 psionic classes

### Solution you would like.

Some scaling for speed of learning powers from Int or maybe sum of levels in psionic class powers

### Describe alternatives you have considered.

Alternatively, ability to choose priority what class powers are learning (if you complete needed conditions) 

### Additional context

@Standing-Storm

**Comment by Standing-Storm** [comment]
Scaling with intelligence is reasonable and looks like it should be possible

**Comment by Cupidatis** [comment]
Also thinking about proficiencies but don't know if it make sense.

**Comment by Consoleable** [comment]
The rate of learning insight proficiencies is absolutely geologic compared to actually learning and training powers within a given specialty. 
Afaik, it takes 170 hours of meditation to become proficient in telekinetic insight, at a good pace. 
Are the insight proficiencies really good enought to warrant being so slow to learn? Getting exp from meditating on powers is already not great. And the dust cost for doing contempations on higher ranked powers means spamming the powers is several orders of magnitude faster and cheaper. But reducing the exp gained by casting powers would make learning powers even more tedious. 
I really like this mod, and spamming powers at high focus is a great way to learn them, but i think learning powers as a whole could be tuned up. 

I think the insight skills could be dropped down to about 30ish hours of contemplation on average and id like to see contemplation be a bit more optimal for learning powers personally.

**Comment by Standing-Storm** [comment]
> Are the insight proficiencies really good enought to warrant being so slow to learn?

Probably not. My perspective is somewhat skewed because I like a game pace that most people would consider glacial (I play with 0.5% of normal healing speed and 1/3 skill and proficiency gain, for example), which is why I originally set them so high, but you're right that they don't currently do enough to be worth that much of an investment.

**Comment by Cupidatis** [comment]
Are contemplation proficiencies work for accelerating powers researching or just for unlocking with meditation or both? I thinked it's working for meditation and my offering  was to make this work for both. @Standing-Storm

**Comment by Standing-Storm** [comment]
Currently just the latter. I already have some work done on implementing them to work for accelerating power learning EoCs

**Comment by Consoleable** [comment]
> > Are the insight proficiencies really good enought to warrant being so slow to learn?
> 
> Probably not. My perspective is somewhat skewed because I like a game pace that most people would consider glacial (I play with 0.5% of normal healing speed and 1/3 skill and proficiency gain, for example), which is why I originally set them so high, but you're right that they don't currently do enough to be worth that much of an investment.

I appreciate this, i do the same on some games and innawoods. I wonder if it's possible to unify the learning speeds to a consistently vanilla-esque rate and then tie it to a global modifier for the mod? I tend to take imperceptible healer and brawler and it would be cool to be able to contemplate powers to learn them while i heal.

**Comment by Standing-Storm** [comment]
> I appreciate this, i do the same on some games and innawoods. I wonder if it's possible to unify the learning speeds to a consistently vanilla-esque rate and then tie it to a global modifier for the mod? I tend to take imperceptible healer and brawler and it would be cool to be able to contemplate powers to learn them while i heal.

That's what I'm doing right now--I'm setting things up as variables that are initiated by EoC and then processed by Jmath statements, so it'll be very easy to mod them yourself without having to change 200 different EoCs directly.

Right now I'm leaving the base speed as-is but it should get much faster with some practice (you'll become eligible for insight 5% faster per point of Metaphysics above 5 and 3% faster per point of intelligence above 10, for example, and having the insight procifiencies will make the EoCs for that path come up 20% faster).
