### ISSUE TITLE
[Interface] Hide "attempt to hack this safe" pop-up when player doesn't have a hacking tool

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73515]
### Is your feature request related to a problem? Please describe.

It is a little silly that you can press `e` on an electronically locked gun safe without a hacking tool and it doesn't automatically tell the player: "You don't have a hacking tool with enough charges!"

### Solution you would like.

Instead, I propose hiding this pop-up when the character doesn't have a hacking tool, or better yet, a hacking tool with enough charges. The confirmation makes sense when the player has met the requirements to be able to hack the safe, but it shouldn't appear when the player doesn't meet the requirements. 

### Additional context

Here is the pop-up that I'm referring to: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/acbe2481-4823-4f30-b1a0-011afd312dce)

**Comment by PatrikLundell** [comment]
I disagree slightly.

I'm not too keen on the 'e' interaction only doing anything at all if you happen to have the tool it requires available, as this means you can easily get the impression that something can't be interacted with, when in reality you don't happen to carry the correct tool.
I'd rather have a feedback saying you don't have a a suitable tool, or that your tool doesn't have enough charges (without a popup requiring acknowledgement).
That has the disadvantage that you may have to select what to interact with when there are some things in range you don't have the tools for.

**Comment by DragonWizard23** [comment]
Hey PatrikLundell, thanks for the reply!
> I'm not too keen on the 'e' interaction only doing anything at all if you happen to have the tool it requires available, as this means you can easily get the impression that something can't be interacted with, when in reality you don't happen to carry the correct tool. 

I think we are in agreement. I don't think I was very clear, but I do want the player to be able to `e`xamine the safe regardless of _whether or not the player has a hacking tool with enough charges_. I'm thinking along the same line as how the player can `e`xamine a locked door or gate without picking/prying tools. (Those create log messages instead of pop-ups.)

> I'd rather have a feedback saying you don't have a a suitable tool, or that your tool doesn't have enough charges (without a popup requiring acknowledgement). That has the disadvantage that you may have to select what to interact with when there are some things in range you don't have the tools for.

Yep, this is what I had in mind. When the character `e`xamines a safe without a hacking tool with enough charges, there should still be the log message: "You don't have a hacking tool with enough charges!" However, I'm suggesting that we remove the confirmation pop-up, because it isn't necessary. If the player doesn't have the requirements to hack the safe, the pop-up will always end with the same result (not attempting to hack the safe). By removing the pop-up but keeping the log message, the behavior will be consistent with other locked things (gates, doors, etc).
