### ISSUE TITLE
Zombies attack spore clouds

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73521]
### Describe the bug

Zombies attack spore clouds, which cannot be harmed. It's a little silly that they try to attack what would just look like a cloud of dust. 

### Attach save file

N/A

### Steps to reproduce

Get some zombies and bring them towards a fungaloid. When the fungaloid makes spores, the zombies will attempt to attack the spores. 

### Expected behavior

I did not expect zombies to try to attack spore clouds. I realize that they currently use monster code, but it makes about as much sense as zombies trying to attack a cloud of smoke or tear gas. 

### Screenshots

Here is a log screenshot of the behavior. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/bcea875b-3516-40d8-a2de-457cd4bd3540)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: fa7e258 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause a crash.

**Comment by ADekema** [comment]
Given how stupid zombies are supposed to be attacking a spore cloud might actually be fine.

**Comment by DragonWizard23** [comment]
Hi ADekema, thanks for your input! 

I thought about this, but I don't think that a cloud of spores would be visible enough for a zombie to consider it to be something that can be attacked. Re-reading the spore cloud description: `A mass of spores the size of a balled fist, wafting around in the air.` I think this can be interpreted as _each spore_ is the size of a balled fist, or _the whole cloud of spores_ is the size of a balled fist. 

Our zombies, while dumb, don't attack similar effects (smoke, tear gas, toxic gas, etc). _Maybe we could model the spore clouds as a gas instead of as monsters..._

**Comment by toweroglass** [comment]
i think you have a point. they also don't attack frogs, birds and other small animals these days. so regardless of their intelligence the spores shouldn't be a target for them.
