### ISSUE TITLE
Heating up food as a queue menu

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#73531]
### Is your feature request related to a problem? Please describe.

Freezing food is great for making it last, but heating up a lot of individual food items at once is super tedious. Items that should stack dont due to slight differences in their perishable time (like hard cheese) so you have to heat up each slice as a separate request to a hotplate/etc.

### Solution you would like.

Instead of the heating up food menu selecting a single item, allow for the selection of multiple items simultaneously, like the drop menu or most other menus in game, and then heat up the food sequentially. based on alphabetic order or lowest work time or whatever. 

### Describe alternatives you have considered.

heating up food as recipes but that seems horrible

**Comment by yuganxia** [comment]
#72514
It is almost done and will merged soon.

**Comment by GuardianDll** [comment]
resolved by #72514
