### ISSUE TITLE
Segfaults when outside, may be solar panel related? Sky island related?

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#73530]
### Describe the bug

inconsistent segfaults when going outside, may be related to solar panels or sky island or mapgen?
It seems to be failing to draw something. 

### Attach save file

[Bonsai-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15214396/Bonsai-trimmed.tar.gz)

### Steps to reproduce

Difficult to reproduce, but noticed some patterns, they work inconsistently but tend to happen more after longer periods of playing the game
1. >spend time doing random shit in base
>. try to go outside
>segfault
>reload
>go outside
>no segfault

2. >go outside during day
>no segfault
>press e near solar panels
>open solar panel menu
>hit esc
>segfault

3. > go inside base
> walk around
>go back outside
>segfault

### Expected behavior

no segfault

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 014e815 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Mind Over Matter [mindovermatter],
    Sky Island [skyisland],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15214377/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15214378/debug.log)

**Comment by GuardianDll** [comment]
I've had this error a lot, i could not reproduce it properly, and it was almost completely gone when i changed my build from MSVC to other

**Comment by RenechCDDA** [comment]
I got it to reproduce when loading the save the second time, it happened *during loading*. Interestingly, it's trying to draw... z+14?

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/53cc3dc9-82f0-429e-bd0f-91218ea2a0b6)

That's way out of bounds.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/c6165119-cd6a-44d0-8442-b93591475d22)

But it should be z+7? What is going on here?

**Comment by RenechCDDA** [comment]
This should probably prevent the crash in the future, but the circumstances to trigger it aren't clear to me. I wasn't able to get it to crash more than the one time (with or without this patch).

```diff --git a/src/cata_tiles.cpp b/src/cata_tiles.cpp
index 0eaa347af9..c640f23c79 100644
--- a/src/cata_tiles.cpp
+++ b/src/cata_tiles.cpp
@@ -4049,6 +4049,9 @@ bool cata_tiles::draw_critter_above( const tripoint &p, lit_level ll, int &heigh
     // Search for a creature above
     while( pcritter == nullptr && !here.dont_draw_lower_floor( scan_p ) &&
            scan_p.z - you.pos().z <= fov_3d_z_range ) {
+        if( scan_p.z >= OVERMAP_HEIGHT ) {
+            break;
+        }
         pcritter = get_creature_tracker().creature_at( scan_p, true );
         scan_p.z++;
     }
```
