### ISSUE TITLE
Unloading action does not work properly for gases

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#73546]
### Describe the bug

When unloading a container with gases in it using auto mode, the whole bulk of gases is treated as an item, if you don't have a container that is big enough to hold all of the charges, not a single charge will be added to your pockets.
Unloading using manual mode works better, but still not perfect and will cause a bug.

### Attach save file

N/A

### Steps to reproduce

1. Wield an extra large gastank full of biogases, and put a small gastank in your backpack.
2. Try to unload the large tank using manual mode, see the small tank only be partly filled.
3. Try again, and the debugmsg popped up.
4. Try to unload the large tank using auto mode, get informed that there is no enough room in your inventory, and lost all the gases.

### Expected behavior

Be able to unload gases properly

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/a6e56d0e-e1d2-47a7-85f9-a15f88dfb3e6

https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/9ff05223-6729-4bac-9bd9-cf7bf029f1af

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: eefe407 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

https://github.com/CleverRaven/Cataclysm-DDA/issues/73543
We may need something like the liquid_handler but for gases.

**Comment by PatrikLundell** [comment]
What happens if you use the container fill interface instead?

This is for a potential work around, not suggested as a solution (and if that doesn't work properly either, we've got another issue that needs fixing as well).

**Comment by osuphobia** [comment]
What do you mean by "the container fill interface", the reload item interface?
The biogas tanks are not watertight, and have pocket type CONTAINER, with item_restriction defined.
I meant to make it only airtight, so you can't see it in the reload interface.
Anyway, even if you add watertight to the tank, you are still not able to reload it with gas.
If you also change the pocket type to magazine and define ammo_restriction, both reload and unload action works fine, but now you can't gather biogas from the digester.
And, if you only change part of the parameters, a display error will occur.
![20240506display_error](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/d7840706-f4d7-4d6a-89c1-80b78962307a)
