### ISSUE TITLE
Experimental builds on the website

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73562]
### Describe the bug

It hasn't been updated for ~4 days, while merges have been happening.

### Attach save file

N/A

### Steps to reproduce

Go to the website, releases, experimental, none since the 3rd

### Expected behavior

Merged builds shown

### Versions and configuration

- Google

**Comment by NetSysFire** [comment]
The last deployment of the website, as seen in https://github.com/CleverRaven/Cataclysm-DDA/deployments, was 5 days ago. No idea why it stopped deploying though.

**Comment by PGR-14** [comment]
It's happened before (Don't know when, but it was a while ago)

**Comment by PGR-14** [comment]
This doesn't seem to have fixed it.
