### ISSUE TITLE
Add a bit to the grakens

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73567]
### Is your feature request related to a problem? Please describe.

Well, they don't really have much going for them. They seem pretty interesting, & only really get killed by zombies or Mi-Gos.

### Solution you would like.

Add two things:

Make them actually ok at combat (Maybe an Eldrich weapon? Arm blade? They could get some type of small shapeshifting power)
Add something similar to the Panicked Person or the Futile Fighter, where you can "Talk" to them.

Some ideas include:
-Hand signaling & motions
-Something useful
-Friendly Grackens?
-Trading (Not through the usual interface) (Probably not)

**Comment by TheSaddestGoomba** [comment]
Just my 2 cents but I don't think they should gain any weaponry. I really like that they are sort of the "nether civilian" and I do love your ideas for developing that aspect further.

Maybe a separate variant would be good for the combat ideas? That way you could even have some of those versions defending the more passive ones.

**Comment by Consoleable** [comment]
I like it when games have more than just "friend" or "foe" in them. Grackens are a sign that there might be other eldritch beings around, or potentially scientist corpses. I think them being passive is cool. not everything needs to fall on one side of the friend or foe dichotomy. Especially in the PA aspect of CDDA, having a number of things which are not trying to kill you is nice, but adding too many friendlies takes away from the PA aspect of it. Watching a nether entity get chased and killed is part of the niche for them and I think thats good. Not for them, but good. I dont think players should try to use them to kill zombies, and the fact that they inevitably die means as a distraction they are on a timer. I don't think they really need to be made stronger or into an ally like a trader or something. 

However, a quest involving them might be interesting and add a little more depth to them and might be a good way to get a little bit of lore about the netherial aspects of the lore. Maybe a special device to have a one time conversation with one, or a device to capture one so a faction can study one or something.

**Comment by Jan-Blasiak** [comment]
I really would love to keep grackens friendly, ever since I've first launched the game years ago those little helpless goofs were there with me.

**Comment by PGR-14** [comment]
> Just my 2 cents but I don't think they should gain any weaponry. I really like that they are sort of the "nether civilian" and I do love your ideas for developing that aspect further.
> 
> Maybe a separate variant would be good for the combat ideas? That way you could even have some of those versions defending the more passive ones.

Ok, maybe 2 versions? One w/ some type of nether arm blade, & one w/ some type of bow?



> I like it when games have more than just "friend" or "foe" in them. Grackens are a sign that there might be other eldritch beings around, or potentially scientist corpses. I think them being passive is cool. not everything needs to fall on one side of the friend or foe dichotomy. Especially in the PA aspect of CDDA, having a number of things which are not trying to kill you is nice, but adding too many friendlies takes away from the PA aspect of it. Watching a nether entity get chased and killed is part of the niche for them and I think thats good. Not for them, but good. I dont think players should try to use them to kill zombies, and the fact that they inevitably die means as a distraction they are on a timer. I don't think they really need to be made stronger or into an ally like a trader or something.
> 
> However, a quest involving them might be interesting and add a little more depth to them and might be a good way to get a little bit of lore about the netherial aspects of the lore. Maybe a special device to have a one time conversation with one, or a device to capture one so a faction can study one or something.

Maybe the great Library w/ some type person w/ void fascination or something? Maybe, over time, they get to communicating w/ it?

**Comment by TheSaddestGoomba** [comment]
Oh, I meant two types as in keep the existing one as is and add a new combat capable version.
Two combat capable variants seems fine to me. We've got melee and ranged weaponry and they are reflections of our reality, right?
I'm mostly advocating for a "yes, and..." design approach, adding new rather than altering what's already there. I think a lot of people like the helpless grackens and it'd be a shame to lose them.

**Comment by PGR-14** [comment]
> Oh, I meant two types as in keep the existing one as is and add a new combat capable version. Two combat capable variants seems fine to me. We've got melee and ranged weaponry and they are reflections of our reality, right? I'm mostly advocating for a "yes, and..." design approach, adding new rather than altering what's already there. I think a lot of people like the helpless grackens and it'd be a shame to lose them.

Ok, that's a good Idea, I was gonna keep the original & add the two new ones either way. But what about the quest? The great library doesn't have much of a plan, much less outline.

**Comment by TheSaddestGoomba** [comment]
Yeah, the great library is entirely apocryphal in my experience. I like what I've heard in related conversations but don't recall seeing any specific issue or PR for it. I have no idea the actual direction or authors.

**Comment by PGR-14** [comment]
Why don't we start one?
