### ISSUE TITLE
Filter quality by level

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73584]
### Is your feature request related to a problem? Please describe.

I would like to search here for recipes that need anvil quality exactly one:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/06b18cd3-268f-42b2-be98-d34e9cf3c24a)

### Solution you would like.

Some syntax to support it, like `?1` or something in the game. Could also support ranges, but this is not necessary, as I can OR.

This would work in:
1. `&` Crafting menu > `f`ilter
2. `/` AIM > `f`ilter
3. `V`iew Item list > `f`ilter
4. etc.

**Comment by marex333** [comment]
I would say it would be usefull for zone manager for custom zone. Imagine you want a tile to have cooking utensils. It's easy, you set: q:cooking. Then you find out that cooking quality have plenty of things. From frying pan to sheet metal or sheet armor. To get rid of that we could either set exect quality level or by using operators.
