### ISSUE TITLE
Monster special attack cooldowns should be allowed to use math

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#73587]
### Is your feature request related to a problem? Please describe.

Working on the Mindhunter scenario for the modified Relentless Hulk and I wanted to modify the power cooldowns so they got shorter and shorter the more times you killed the hulk. Unfortunately this is impossible.

### Solution you would like.

Allow monster special attack cooldowns to accept math. 

### Describe alternatives you have considered.

I guess it's technically possible by copying each special attack a dozen times, each of which has a different cooldown and a condition like `"Nemesis_iteration" <= 8 and >= 5` or something, but that seems ill-advised.

**Comment by GuardianDll** [comment]
@Ramza13 i recall you are interested in such cases
