### ISSUE TITLE
ImGui: QueryYN doesn't highlight selected option

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73583]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/780fe86a-d012-4870-9c2e-3b1a644ed319)

Pressing left selects yes, and pressing right selects no. But there is no graphical difference whatsoever.

### Attach save file

N/A

### Steps to reproduce

1. Open the Keybindings menu, change something, then close OR save "Save and Quit" from a game OR press ESC on launch OR etc.
2. Yes No query pops up
3. press left and enter
4. check that the YES was selected (keybinding is changed / game is saved and quit)
5. press right and enter
6. check that the NO was selected (the popup is cancelled)

### Expected behavior

It used to highlight, no? Even after ImGui was implemented. Anyway, highlight the selected option.

### Versions and configuration

This **happens only** after merging the new ImGui provided by @ katemonster33 in https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 . 

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9302-g8a974a2373 [64-bit] master was 89988655dc
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Not pinging katemonster33, I heard they don't like it.

**Comment by katemonster33** [comment]
That's odd. Did this start recently for you? I will try and reproduce this when I get a minute

**Comment by Brambor** [comment]
> That's odd. Did this start recently for you? I will try and reproduce this when I get a minute

Cannot say when it started. It's something I have to actively observe to notice.

**Comment by katemonster33** [comment]
![Screenshot_20240508_215002-1](https://github.com/CleverRaven/Cataclysm-DDA/assets/24497894/569182bf-4015-4a1b-b0d7-0b406e6cb0ee)
tried it on bleeding-edge latest experimental. can not reproduce

**Comment by Brambor** [comment]
Ok, will try tomorrow too. Thanks for your service!

**Comment by PatrikLundell** [comment]
It could be that it's an issue with a particular (set of) instance, so I'd suggest to @Brambor to test the same thing that was done for the image in the report. If it remains, explain which instance it it (i.e. what you did to bring it up).
It would also be useful to try the quit popup @katemonster33 tried, in case it's something tied to the platform used.

**Comment by Brambor** [comment]
I see. I have been playing with https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 merged. My bad. Sorry to drag you into this.
When I throw it out, the selection works as expected.

Are there any fixes I have reverted by using it @katemonster33? If it is very little time, could you update it, pretty please?

**Comment by katemonster33** [comment]
@Brambor so is this problem new? Or was that branch always like that? It could be a regression in ImGui.

**Comment by Brambor** [comment]
I think it wasn't always like that. I will try when I have time. Since I hate bugs / love to eradicate them, maybe I will make time soon. Maybe now.

**Comment by Brambor** [comment]
I did find out that it worked on https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 but it doesn't work, that is merged into / rebased onto e37e4719. I didn't bisect any further... yet.

**Comment by Brambor** [comment]
I found it @katemonster33.
The culprit is e746932688 from
 - #72619
 after which merging https://github.com/katemonster33/Cataclysm-DDA/tree/imgui_v1.90.4 will break the highlight.
 
 If merging the new ImGui before that, that is 67f2fb9a3f and earlier, the highlight works.
 
 Note to self: be smarter about bisecting later.

**Comment by Brambor** [comment]
Removing the invalid label. I am new to the meaning of labels and how people interpret them.
