### ISSUE TITLE
Give Forge of Wonder a Translocator Gate

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#73598]
### Is your feature request related to a problem? Please describe.

Once the [PR#73578](https://github.com/CleverRaven/Cataclysm-DDA/pull/73578) merge the Forge of Wonder will become globally unique, make it hard to do return shopping. For such wealthy and powerful organization I think it is reasonable having a Translocator Gate outside helping powerful individual ease the traveling.

### Solution you would like.

I suggest adding a Translocator Gate outside of main building for customers who access Translocate Self spell doing a quick trip for shopping. How they return to where they from isn't Forge's concern.

### Describe alternatives you have considered.

Don't do it, making shopping trip a pain in the arse.

**Comment by Maleclypse** [comment]
Fully support this idea.

**Comment by Procyonae** [comment]
It'd need some new C++ to add a translocator to known_teleporters via EoC but that doesn't look difficult, I'll look into it once it merges.
Would you need to examine the gate or talk to someone about it or should just entering the forge be enough?

**Comment by Naadn** [comment]
> It'd need some new C++ to add a translocator to known_teleporters via EoC but that doesn't look difficult, I'll look into it once it merges. Would you need to examine the gate or talk to someone about it or should just entering the forge be enough? (or something more involved like locking it behind a purchase or something that comes with the spell or even a limited/one use version that can't fail if that's possible)

I remember when you "e" the gate it will popup a window window telling you to naming the gate and remember it. I think able to find the forge is enough, lock it behind a fee will reduce the willing to use it of potential customers.

**Comment by Standing-Storm** [comment]
> (or something more involved like locking it behind a purchase or something that comes with the spell or even a limited/one use version that can't fail if that's possible)

Single-use translocators seems like something that would exist in the Magiclysm world anyway, and it would make sense for the Forge to sell them to people.
