### ISSUE TITLE
Magiclysm: Cat's Grace should list Ogre's Strength in it's remove_effects code [low priority]

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#73593]
### Describe the bug
Update:
The spells themselves seem to recognize if a buff is up and not apply the new buff while the old one is active
The remove_effects code seems to be a failsafe in case something unexpected happens like if both get applied in the same tick or something else applies the effect without pre-checking if the other buffs are there.

Since in practice it's hard to actually cause this to happen it's a low priority issue atm.

---

In magiclysm there's 4 enhancement spells, one for each attribute
Their active effects are supposed to be mutually exclusive

in data/mods/Magiclysm/effects/effects.json
under Cat's Grace: removes effects (line 281)
eagles_sight is listed twice and ogres_strength is missing

I'm at work so I can't actually test but it looks like if you cast Ogre's Strength first then cast Cat's Grace you could mistakenly have both buffs active

If Cat's Grace does indeed remove Ogre's Strength then that line (281 in magiclysm/effects/effects.json) should still be updated to correctly list the removed buffs, in case it's used elsewhere

### Attach save file

N/A

### Steps to reproduce

make a character in magiclysm
give yourself both Ogre's Strength and Cat's Grace
cast Ogre's Strength
cast Cat's Grace
Verify you have both buffs active

### Expected behavior

Cats Grace should remove Ogre's Strength

### Versions and configuration

current (I was browsing the current source code on the website)

**Comment by Icantthinkofanameforthis** [comment]
seems when you have cats grace then activate ogres strength they will both be on for a second then cats grace deactivates itself and im currently having a look to see if this happens with any of the others but so far apart from that instance they dont activate if you got one of the others up

**Comment by Xpyder** [comment]
Did you try the other way around? Ogre's strength then Cat's Grace?  The order is important in this instance

**Comment by Icantthinkofanameforthis** [comment]
yup cats grace just doesnt give the buff when used if ogres strength is up

**Comment by Xpyder** [comment]
Thank you for testing.  I guess the remove effects are just a backup then in case a glitch happens?

I would say that line should still be updated but if the buffs aren't actually stacking then that's a low priority housekeeping issue.  I'll see if I have time to make a PR tonight when I get home but it sounds like this is more of a superfluous issue

**Comment by Icantthinkofanameforthis** [comment]
note that i got fox's cunning at max lvl which is why its not getting exp

cat's grace
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/094238ea-e711-485e-a0a0-e7d338ead204)

eagle's sight 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/96bc59d6-02c0-4e61-b7e2-147d9df7c222)

ogre's strength
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/e59467b5-d8a5-45f6-a2b0-259fe1a29089)

fox's cunning
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/18b57dd4-0740-4178-ad7d-759e24bf31ea)

**Comment by Xpyder** [comment]
well that's interesting, it looks like the effects block each other except when you cast Cat's Grace then Ogre's Strength (in which case the strength overwrites the dex buff)
