### ISSUE TITLE
misc repair kit requires bow saw or wood saw, but bow saw is bigger than the kit, has higher tree cut quality and isn't returned on dissasembly. 

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73608]
### Describe the bug

When you craft a misc repair kit you can use either a bow saw or a wood saw to do so.
A bow saw is 34 inches in length, a wood saw is 18 inches, and the misc repair kit is 18 inches. The wood saw has tree cut quality of 1, the bow saw has 2, kit has 1. Disassembly of the kit gives back just wood saw.
For this to make sense we have to assume the player cut the bow saw in half before making the kit and tossed the rest. Its a down grade either way.

### Attach save file

NA

### Steps to reproduce

Examine bow saw, wood saw, and misc repair kit.

### Expected behavior

Only have the wood saw available as the required component.
Maybe have some recipe to convert a bow saw into a wood saw and scrap metal with a hack saw? (seems like a waste of a bow saw to me though, but perhaps if one is desperate enough, a drawback is that it does make a hacksaw now needed.)

### Versions and configuration

Windows 11
build 9514a3f

**Comment by Karol1223** [comment]
How do you determine that disassembling it does not return the bow saw?

It is a reversible recipe. It will return the specific components used to craft it.

**Comment by Brambor** [comment]
`tailors_kit` is also composed of components that have smaller weight and size, I think.

**Comment by TheMurderUnicorn** [comment]
It does in fact give the components that it's crafted from 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41651793/b398720a-c01a-4354-a02d-155f3cf56a4d)
It does not inherit volume or qualities and that is not something I know how to do.  Expanding it's length would nearly double its size, if someone wants to do that they can, I don't want to do that.  But this did show me that I can add the bronze wood saw to the list of components, so... I'll change that?  That's... something? Right?

**Comment by O1OOO1O** [comment]
Sorry about the disassembly misread, I probably disassembled the wrong kit. It was the length mismatch that stuck out to me more.  My general opinion is to just drop the bow saw as a possible craft component choice (And add in your bronze wood saw instead)

**Comment by TheMurderUnicorn** [comment]
Bronze saw as a component was already merged, if someone wants to do more that's up to them, I probably won't follow up in any way.
