### ISSUE TITLE
No such parameter "variant_palette"

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73601]
### Describe the bug

Trying to build a house (`house_rv`) through the debug menu
```
 DEBUG    : No such parameter "variant_palette"

 FUNCTION : Result mapgendata::get_arg(const std::string&) const [with Result = string_id<mapgen_palette>; std::string = std::__cxx11::basic_string<char>]
 FILE     : src/mapgendata.h
 LINE     : 244
 VERSION  : cdda-experimental-2024-05-09-0820 fa8ae46
```

Looked at other house variants (`house_34`), similar problem.

### Attach save file

n/a

### Steps to reproduce

1. Create a new world
2. Edit map via debug menu
3. Spawn house_rv

### Expected behavior

n/a

### Screenshots

![pict 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/ec575c68-039d-4cb5-80e8-30cd4622cbe8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-09-0820 fa8ae46 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

But in the cities, everything is fine. Including with house_rv. What is the difference between spawning houses in a city and spawning through the debug menu?

**Comment by PatrikLundell** [comment]
When I tried to spawn an overmap thing I first got something similar to what you got. I found a different command which seemed to work properly.
't' place overmap terrain seems to place only the basics and for a single level.
's' place overmap special seems to place what I actually wanted.
To the left: the house_rv special, while to the right you have the terrain (with the missing palette message).
![Screenshot (340)](https://github.com/CleverRaven/Cataclysm-DDA/assets/22739822/bb7b604d-85b3-44cf-af05-f87a0a4a359d)

**Comment by IdleSol** [comment]
You created the house through global map modification. Overmap editor.

For simplicity: debug menu = `F1`.
`F1`-`m`-`O`-`s` 
`F1`-`m`-`O`-`t` This causes an error

And I created through map modification. Map editor - overmap/mapgen
`F1`-`m`-`M`-`o` This causes an error

**Comment by IdleSol** [comment]
dda-windows-with-graphics-x64-2024-12-10-1201 The error is reproduced.

But this is the debug menu. So I'm closing the topic.
