### ISSUE TITLE
No Hope needs a maintainer

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#73629]
### Is your feature request related to a problem? Please describe.

No Hope mod is one of the most popular and complicated mods in mainline and is without an active maintainer per #73268 . A maintainer is required for it to escape obsoletion per https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/IN_REPO_MODS.md

### Solution you would like.

A volunteer to add their name as maintainer to https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/No_Hope/modinfo.json and do the work

### Describe alternatives you have considered.

Obsolete the mod until a maintainer volunteers

### Additional context

Thanks to @Procyonae for the detective work on this and to @Night-Pryanik for creating a fun mod that so many care about

**Comment by I-am-Erk** [comment]
This is one I'd fight pretty hard to not obsolete. It serves a very valued gameplay role and night may come back.
