### ISSUE TITLE
Electric blankets have "When full" encumbrance of 800035

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#73626]
### Describe the bug

Electric blankets' description shows a "When full" encumbrance of 800035.

### Attach save file

N/A

### Steps to reproduce

1. Spawn electric blanket
2. Read the encumbrance value

### Expected behavior

Reported encumbrance value should be reasonable.

### Screenshots

![Screenshot (2085)](https://github.com/CleverRaven/Cataclysm-DDA/assets/38295275/cc9236a4-74ed-48ec-b745-de185ad59f59)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-10-0814 10a7e40 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by EternalLaughter** [comment]
Confirmed, reported "when full" value is shown as crazy high value, both with and without battery inserted, on or off.
When worn, the actual encumbrance is as expected (35)
