### ISSUE TITLE
Debug: Spawn Item menu crashes when resized (big to small)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73639]
### Describe the bug

Spawn Item menu crashes when resized (big to small)

### Attach save file

N/A

### Steps to reproduce

1. debug menu
2. spawning
3. spawn an item
4. make the screen big (if not already)
5. make the screen small
6. observe crash

For me, it is 100% reliable.

### Expected behavior

No crash.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9409-g1252fcee16 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I expect this to not be reproducible everywhere. Note my system etc.

Debug log (contains nothing interesting):

<details>

```
-----------------------------------------
02:54:57.311 : Starting log.
02:54:57.311 INFO : Cataclysm DDA version 0.G-9409-g1252fcee16
02:54:57.311 INFO : [main] C locale set to English_United Kingdom.utf8
02:54:57.311 INFO : [main] C++ locale set to 
02:54:57.311 INFO : SDL version used during compile is 2.26.4
02:54:57.311 INFO : SDL version used during linking and in runtime is 2.26.4
02:54:57.353 INFO : SDL render devices: direct3d, direct3d11, opengl, opengles2, software
02:54:57.388 INFO : [options] C locale set to en_US.UTF-8
02:54:57.388 INFO : [options] C++ locale set to en_US.UTF-8
02:54:57.388 INFO : Setting language to: 'en'
02:54:57.388 INFO : [i18n] Scanning core translations from lang/mo/
02:54:57.518 INFO : Active renderer: 1/direct3d11
02:54:58.045 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
02:54:58.086 INFO : Setting language to: 'en'
02:55:17.956 INFO : Loaded tileset: UltimateCataclysm
02:55:18.175 ERROR SDL : C:\GitHub\Cataclysm-DDA\src\cata_tiles.cpp:761: The tileset you're using has no 'unknown' tile defined!
02:55:18.176 INFO : Loaded tileset: UltimateCataclysm
02:55:44.623 ERROR : C:\GitHub\Cataclysm-DDA\src\item_contents.cpp:758 [combine] error: item duct_tape cannot fit into any pocket while loading: pocket with type (MAGAZINE) not found
```

</details>

**Comment by mqrause** [comment]
/confirmed

Crashes in `wish_item_callback::refresh` somewhere.

**Comment by Brambor** [comment]
- I can no longer reproduce it. I assume it was fixed when the menu migrated to ImGui (it is a uilist) in #74341.
