### ISSUE TITLE
crossbow to shoot  can make good look？

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#73648]
### Is your feature request related to a problem? Please describe.

no problem，Currently, when using the crossbow to shoot, it displays a white bullet-like trajectory (similar to a gun). However, I'd like to simulate the trajectory of an arrow and create a parabolic effect. In our game, we're shooting arrows, but they still appear as bullet-like light points. When the enemy is killed, there's an arrow on the ground. I hope that when the arrow is shot out, it would actually look like an arrow, and preferably have a parabolic or similar trajectory.

### Solution you would like.

Currently, when using the crossbow to shoot, it displays a white bullet-like trajectory (similar to a gun). However, I'd like to simulate the trajectory of an arrow and create a parabolic effect. In our game, we're shooting arrows, but they still appear as bullet-like light points. When the enemy is killed, there's an arrow on the ground. I hope that when the arrow is shot out, it would actually look like an arrow, and preferably have a parabolic or similar trajectory.

**Comment by PatrikLundell** [comment]
The game uses a very compressed scale, so everything is done at a short range. There isn't much of an arc to an arrow over the rather short range the game bow have (unless it's a toy bow useless for survival activities, but those aren't present in the game). Also, the game doesn't really have a 3D presentation (there are some tilesets that provide some illusion of it in some aspects, but the game doesn't support arcs).
