### ISSUE TITLE
ImGui: Scrolling through the list of missions is still problematic. (Mobile)

### ISSUE THREAD

**Issue by Elshad19** [CleverRaven/Cataclysm-DDA#73664]
### Describe the bug

Edit: this is a dublicate post. The problem was initially reported in #73606 

Edit 2: The problem still persists as of d78e605ededb7b83db032a7fd2061b711fd1a93f

https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-05-11-0903

I apologize if I don't make any sense or make mistakes since English is my second language. 

Basically, the latest experimental build implemented the new UI to mission selection. However there is a problem with it. While scrolling, it skips a mission and jumps to the other mission. There is no way to select the mission in middle. Check the video below for visual demonstration.

### Attach save file

N/A

### Steps to reproduce

1) Have more than 3 missions at the same time,
2) Press "M" to view your missions,
3) Scroll to reproduce the problem.

### Expected behavior

While I support scrolling quickly through the mission list, I think there should be an additional option to manually select one mission at a time instead of jumping over each other when scrolling. 

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/87479123/292e06ad-8c85-45e0-a066-c72a34581d1d

Pay attention to the names of the missions.

### Versions and configuration

Version: ef430d2
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-05-11-0139

Platform: Android (10.0) & 4Gb Ram.

### Additional context

N/A

**Comment by NetSysFire** [comment]
Closing as duplicate.

**Comment by Elshad19** [comment]
> Closing as duplicate.

I understand the reason behind the closing, I was wondering if you could reopen it considering the old issue was kind of vague and 2 days old. I reproduced the problem on the latest experimental + provided video evidence as a demonstration.

**Comment by NetSysFire** [comment]
Then provide your information in the other issue
