### ISSUE TITLE
Isherwoods Farms don't prevent spawning random map extras on it's overmap tiles.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#73662]
### Describe the bug

I've been walking around Isherwoods when suddenly as I approached Jack and Claire's house for the first time I saw a soldier zombie jump out of the window. As I walked inside I saw everything covered in acid, dead Jack and dying Claire, and a few different soldier zombies making an absolute mess out of everything.

### Attach save file

N/A, random encounter I immediately save scummed because it was bullshit.

Didn't repeat when approached again.

### Steps to reproduce

Random encounter on Isherwood Farms

### Expected behavior

NOT spawning a squad of zombie soldiers inside the Isherwoods house.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-04-19-2301 449edb2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by PGR-14** [comment]
Can confirm, had craters & alien plants spawn in there

**Comment by DSeyka** [comment]
This seems to be already on the tracker: https://github.com/CleverRaven/Cataclysm-DDA/issues/73493

**Comment by RenechCDDA** [comment]
Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.
