### ISSUE TITLE
Running (Gallop) with a horse is not faster then walk (trot)

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#73666]
### Describe the bug

Mounting a horse i see i move forward at a pace of 42(W) at a trot.
Changing my speed to run (gallop) the movement cost goes red, but it is still 42(R) per tile.

### Attach save file

N/A

### Steps to reproduce

Create a character that can mount and ride a horse.
Mount the horse and notice the movecost is the same at walk\trot as run\gallop.

### Expected behavior

I would have expected much less movecost at running\gallop speed.

### Screenshots

Walking\Trot speed:
![Screenshot from 2024-05-11 15-15-01](https://github.com/CleverRaven/Cataclysm-DDA/assets/50793323/750d098d-7759-4ccd-a827-4c119dd4b4ca)
Running\Gallop speed:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50793323/69a92165-4af8-4612-98ee-504f6eeb29e1)

### Versions and configuration

- OS: Linux
    - OS Version: <Redhat 40>
- Game Version: cdda-experimental-2024-05-09-0434 88e09a5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by PGR-14** [comment]
Quick (Irrelevant) question, why are you holding a horse stick?

**Comment by Icantthinkofanameforthis** [comment]
tileset

**Comment by Icantthinkofanameforthis** [comment]
anyways ya seems speed doesnt change based on the run, walk, crouch and prone thing even though the text suggests it does

also when i checked it out the horses speed was 50 instead of 42 like i tried moving on the road but still 50 and the mods are the same so maybe something in the os or game version changed it or something different in options? 

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/46d0f33a-90b5-4f4e-95b3-47b388772f4b)


- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: d78e605 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

**Comment by EternalLaughter** [comment]
Huh, not sure why it's 42 tbh, i rechecked now with a 100% clean world and config and it was 50 now.
Still, the issue is the same as you say, no speed difference between the modes.

**Comment by IdleSol** [comment]
1. This is not speed, but the number of action points remaining in the current turn. (Or something like that, it's better to ask the people in charge of the code.) Here's how it looks with a different sidebar view.

![test](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/65e731d8-d888-42b3-a2e4-082a0b058a47)

2. I suspect what is happening is switching the movement mode for the character, not the horse. The character is running or crawling on the horse. And the horse itself, continues to move in stride.
