### ISSUE TITLE
Website still isn't working

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73676]
### Describe the bug

Builds have been merged, & they don't show up.

### Attach save file

#73586 tried to fix this, but seemed not to.

### Steps to reproduce

N/A

### Expected behavior

Showing up

### Versions and configuration

N/A

**Comment by EternalLaughter** [comment]
Yepp, still missing updates.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/50793323/1e98f6d4-a950-4cb8-af77-47ae83f8cf72)

**Comment by PGR-14** [comment]
Should we notify Kevin? I think he's in charge of merging builds on the website.

**Comment by TealcOneill** [comment]
The newest version is now showing up correctly for me.
