### ISSUE TITLE
Construction menu. Fix the window size

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73675]
### Is your feature request related to a problem? Please describe.

Recently, there was a merger of this PR. [Graphical construction preview](https://github.com/CleverRaven/Cataclysm-DDA/pull/73455)

>The construction menu is now placed at the bottom left/right of the screen to make the main UI and side bar visible when possible. 

Which fixed its position at the bottom of the screen. This is what it looks like in the game:
![pict 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/83ebad5b-d6ee-4f38-987d-2cc5da252622)
![pict 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/be3b76e9-bd2d-4237-8fd9-c2985b5968f9)

Of course it's not a problem. But it looks weird.

### Solution you would like.

I suggest limiting the window height to 50% of the game window. And remove the dependence on whether or not inaccessible recipes are hidden. Thus, it will always occupy the same space.

### Describe alternatives you have considered.

Not to do anything as it is not a problem.

### Additional context

Also need feedback from players using smartphones. Perhaps this solution will cause problems for them.

@Qrox I apologize for the pinging. Just to keep you up to date as the author of the fix. And point out that previews don't work for practice target and firewood source.

**Comment by Qrox** [comment]
Just to be clear, the height was changing with the content even before #73455; I only moved the window to the bottom so the terrain around the player can be previewed. I think it's fine to fix the height if people find the dynamic height problematic; simply changing the code here should do it:

https://github.com/CleverRaven/Cataclysm-DDA/blob/795be741e48abc41256e0bf4a06b1b6f6442e27e/src/construction.cpp#L739-L746

> previews don't work for practice target and firewood source

Probably has something to do with post specials? Their preview was not implemented in that PR.
