### ISSUE TITLE
Hub 01 Modular Recon Headgear prevents inserting helmet plating with bionic power conversion mod

### ISSUE THREAD

**Issue by nmarrock4** [CleverRaven/Cataclysm-DDA#73671]
### Describe the bug

The Hub 01 Modular Recon Headgear is a parent item that accepts different armor plating via pocket system. Modifying the Modular Recon Headgear item with the bionic power conversion mod prevents insertion of any armored helmet covers. This problem is not present with other battery mods (heavy/medium/light).

The error states: "Could not put Hub 01 kinetic helmet into Hub 01 modular recon headgear+1, destination can't be reloaded."

### Attach save file

N/A

### Steps to reproduce

1. Obtain Hub 01 modular recon headgear
2. insert and remove helmet plating as normal (e.g. Hub 01 kinetic helmet)
3. add bionic power conversion mod to the modular recon headgear
4. remove the helmet plating and attempt to reinsert.

### Expected behavior

The helmet plating should be able to be added no matter the power mod.

### Versions and configuration

OS: Windows 11 (23H2)
Game Version: cdda-experimental-2024-05-11-0903 d78e605 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Slowdown Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions]
Bionic Slots [cbm_slots]
]

**Comment by EternalLaughter** [comment]
Can confirm.
If you don't have a plate in it when modding it with bionic power mod, you can't insert one.
If you had one in it before the mod, and remove it, you cannot reinsert another one.
