### ISSUE TITLE
A horse autopsy provides a sample of cattle

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73679]
### Describe the bug

<s>A horse doesn't have horns, right? Right???</s> Not all jokes are understandable in translation. Does a horse belong to cattle?

https://github.com/CleverRaven/Cataclysm-DDA/blob/d78e605ededb7b83db032a7fd2061b711fd1a93f/data/json/monsters/mammal.json#L2340

https://cdda-guide.nornagon.net/monster/mon_horse

### Attach save file

n/a

### Steps to reproduce

Look in the json file 

### Expected behavior

Either a horse sample or no sample.

### Versions and configuration

master

### Additional context

Fun fact. In Russian, it is a sample of a bull falling off a horse.

**Comment by Karol1223** [comment]
Nothing weird here. Cattle is our generic herbivore mammal mutation. If anything it's weird llamas, goats, and sheep don't give cattle samples.

**Comment by IdleSol** [comment]
Wikipedia:
>Cattle (Bos taurus) are large, [domesticated](https://en.wikipedia.org/wiki/Domestication), [bovid](https://en.wikipedia.org/wiki/Bovidae) [ungulates](https://en.wikipedia.org/wiki/Ungulates) widely kept as [livestock](https://en.wikipedia.org/wiki/Livestock). They are prominent modern members of the subfamily [Bovinae](https://en.wikipedia.org/wiki/Bovinae) and the most widespread species of the genus [Bos](https://en.wikipedia.org/wiki/Bos). Mature female cattle are called cows and mature male cattle are [bulls](https://en.wikipedia.org/wiki/Bull). Young female cattle are called heifers, young male cattle are [oxen](https://en.wikipedia.org/wiki/Oxen) or bullocks, and castrated male cattle are known as steers.

**Comment by Karol1223** [comment]
> Wikipedia:
> 
> > Cattle (Bos taurus) are large, [domesticated](https://en.wikipedia.org/wiki/Domestication), [bovid](https://en.wikipedia.org/wiki/Bovidae) [ungulates](https://en.wikipedia.org/wiki/Ungulates) widely kept as [livestock](https://en.wikipedia.org/wiki/Livestock). They are prominent modern members of the subfamily [Bovinae](https://en.wikipedia.org/wiki/Bovinae) and the most widespread species of the genus [Bos](https://en.wikipedia.org/wiki/Bos). Mature female cattle are called cows and mature male cattle are [bulls](https://en.wikipedia.org/wiki/Bull). Young female cattle are called heifers, young male cattle are [oxen](https://en.wikipedia.org/wiki/Oxen) or bullocks, and castrated male cattle are known as steers.

How does this matter? We're not going by taxonomy. Our "Cattle" is a generic ungulate.

**Comment by fairyarmadillo** [comment]
> > Wikipedia:
> > > Cattle (Bos taurus) are large, [domesticated](https://en.wikipedia.org/wiki/Domestication), [bovid](https://en.wikipedia.org/wiki/Bovidae) [ungulates](https://en.wikipedia.org/wiki/Ungulates) widely kept as [livestock](https://en.wikipedia.org/wiki/Livestock). They are prominent modern members of the subfamily [Bovinae](https://en.wikipedia.org/wiki/Bovinae) and the most widespread species of the genus [Bos](https://en.wikipedia.org/wiki/Bos). Mature female cattle are called cows and mature male cattle are [bulls](https://en.wikipedia.org/wiki/Bull). Young female cattle are called heifers, young male cattle are [oxen](https://en.wikipedia.org/wiki/Oxen) or bullocks, and castrated male cattle are known as steers.
> 
> How does this matter? We're not going by taxonomy. Our "Cattle" is a generic ungulate.
> 
> Centipedes give insect samples. Eels give _slime_ samples. We don't care about taxonomy for this purpose.

Eels should definitely be giving fish and not slime. An eel is a fish and a slime is an alien.

Cattle is all ungulates though, so horses dropping cattle samples seems fine to me.

**Comment by Karol1223** [comment]
>Eels should definitely be giving fish and not slime. An eel is a fish and a slime is an alien - IMO nothing from earth prime should be giving slime samples.

I solved that months ago. They give both.

**Comment by IdleSol** [comment]
The dolphins and whales say hello.
