### ISSUE TITLE
Gun damage calculations incorrect on wield menu

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73680]
### Describe the bug

The damage value listed for several guns is incorrect on the wield menu. Specifically, the weapon damage plus the ammo damage doesn't add up. 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15284126/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

1. Get some guns with ammo. 
2. Put them nearby and press `w`. 
3. Check if the damage calculations are correct. 

### Expected behavior

I expected that the equations would have the same value on both sides of the equation. 

### Screenshots

The highlighted weapon and the six weapons above it have incorrect equations. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/be8253f3-e8f5-4b75-ae57-0b3ce2c4027a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: fa7e258 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This bug does not cause the game to crash.

**Comment by EternalLaughter** [comment]
Can confirm.
While the left side of the equation seems correct for the gun and ammo type loaded,  the result after the = is not.
