### ISSUE TITLE
Most places spawn empty of items on world generation

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#73692]
### Describe the bug

When a new world is generated, nothing spawns in any of the containers. Cabinets, lockers, trash cans, etc. Items occasionally appear as part of map specials (instruments in basement music rooms, for example), but otherwise buildings are barren.

### Attach save file

[Moab-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15284740/Moab-trimmed.tar.gz)

### Steps to reproduce

1. Make a new world with default settings.
2. Start a new character. Any will do.
3. Check the building you spawned in for loot.
4. Check the map for loot.
5. Keep looking.

### Expected behavior

I didn't use any settings that would decrease the amount of loot in the world, so I assumed kitchen cupboards would have things in them, as would other containers.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: cdda-experimental-2024-05-11-2327 59351db [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Consoleable** [comment]
I'm also seeing this. It's freaky

**Comment by IdleSol** [comment]
The problems started with version [2024-05-11-2102 ](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-05-11-2102)

It's probably "Hope for No Hope" #73268 @Procyonae I apologize for bothering you if you're not involved.

**Comment by Procyonae** [comment]
I'm just encouraging peeps to pick up the mod by breaking vanilla, idk what the big problem is /j

**Comment by GuardianDll** [comment]
fixed by #73699
