### ISSUE TITLE
Mechanical Ergometer recipe is needlessly difficult

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#73722]
### Describe the bug

The construction recipe for a mechanical Ergometer requires a "small wheel" which is probably way harder than it should be. If I understood correctly this is the id wheel_small, which is only findable on a small handful of vehicles and in certain itemgroups. It is notably not craftable. This makes the recipe very hard despite seemingly only needing something rolly for what I assume is a pulley.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Mechanical Ergometer should be buildable with nearly any reasonably sized wheel. I don't see why it wouldn't work with anything larger than a caster and smaller than an 18-wheeler wheel. Or just allow small wheel to be craftable.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-05-07-0245 9514a3f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This recipe might need an entire audit. I haven't looked too closely but a lot of recipes might need an audit, especially regarding wheels. I could maybe do this with some guidance. Also, what is a "small wheel"? Like, how big is it?

**Comment by PGR-14** [comment]
We should probably replace it w/ a bicycle or offroad bicycle wheel.
