### ISSUE TITLE
Crash log not generated after abrupt termination

### ISSUE THREAD

**Issue by jtmusky** [CleverRaven/Cataclysm-DDA#73721]
### Describe the bug

crash.log file is either missing or not generated after abrupt termination. 

### Attach save file

N/A

### Steps to reproduce

1. Create a new custom character
2. pick world
3. use default pool type
4. tab to "scenario"
Crashes at this point

navigate to ~/Library/Application Support/Cataclysm/config
crash.log file is missing

### Expected behavior

Expect a crash.log file 

### Versions and configuration

OSX 14.4.1
game version osx-curses: [0.H Release Candidate, Build 8985D54](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-0.H-2024-05-12-1749)

**Comment by jtmusky** [comment]
Terminal shows:
`LIBC++ABI: Terminating due to uncaught exception of type IO::INVALIDENUMSTRING: INVALID ENUM STRING 'CHARACTER_ATTEMPT_TO_FALL_ASLEEP' FOR 'EVENT_TYPE'`

**Comment by jtmusky** [comment]
> unfamiliar with macos but try `ls -ltrh` in your home directory. in some rare cases the game will mangle the crash.log location and create files that have corrupted names.

no dice... no crash log hidden OR garbled anywhere

**Comment by NetSysFire** [comment]
Where is your complete terminal output I asked for?

**Comment by jtmusky** [comment]
@NetSysFire 
Please see the attached terminal screenshot of both the file listing and crash

<img width="1222" alt="image" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/23535616/4bcf7787-9db6-4732-b33c-c3f0949298e6">

![Screenshot of iTerm2 at May 12, 2024 at 20_31_10 (Duplicate)](https://github.com/CleverRaven/Cataclysm-DDA/assets/23535616/eb3f7de2-87af-48ea-a5b2-d360020ec6b8)

**Comment by perryprog** [comment]
I'm not able to reproduce on curses, macOS, with the same version you're using when building from source. Are you using a precompiled binary, or are you building from source? If the latter, could you share the build flags you're using? Otherwise, where are you getting the binary?

**Comment by jtmusky** [comment]
Precompiled binary. I have a link to the binary in the initial post

> I'm not able to reproduce on curses, macOS, with the same version you're using when building from source. Are you using a precompiled binary, or are you building from source? If the latter, could you share the build flags you're using? Otherwise, where are you getting the binary? It looks like your debug.log is also being updated. After the crash happens, can you paste the tail end of the log, starting from the very last bit that looks something like:
> 
> ```
> -----------------------------------------
> 10:56:36.160 : Starting log.
> ```

**Comment by perryprog** [comment]
That comes as a .app, but I see you're running it in the terminal. Are you running the .sh (`Contents/MacOS/Cataclysm.sh`) within the bundle, or the actual binary (`Contents/Resources/cataclysm`)?

**Comment by jtmusky** [comment]
I have a file called `playcat` located in my `~/bin`

```sh
#!/usr/local/bin/bash
cd '/Applications/Cataclysm.app/Contents/Resources' && ./cataclysm; exit
```

**Comment by perryprog** [comment]
Interesting; running it in that manner I don't see the same crash as you (I do see some errors which I thick are just forward-compatibility errors with some of my memorial files that I'm able to ignore just fine), but when I force a crash I do see crash.log not being updated despite this being the case when run as a self-compiled binary. I'll look into that tomorrow, though I'm not sure I have a good idea on what's causing your issue...

I don't think it should make a difference, but from a fresh download of that .app, could you try running in the Resources directory `./cataclysm --datadir data/`?

**Comment by jtmusky** [comment]
No difference running it directly. The exact same [crash style as before](https://github.com/CleverRaven/Cataclysm-DDA/issues/73721#issuecomment-2106352786). However, I did pull the "a" crash report from the console app. Maybe some clues there...  
[catcrash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15314961/catcrash.log)

> I don't think it should make a difference, but from a fresh download of that .app, could you try running in the Resources directory `./cataclysm --datadir data/`?

**Comment by jtmusky** [comment]
Ugh, I renamed my `Application Support/Cataclysm` folder to force the creation of a new one. No crash. So maybe something from there. Granted, been using "Experimental" for a while, so maybe that is the main culprit.

**Comment by perryprog** [comment]
Ah, good! This wouldbe a forwards compatibility issue, then—I suspect the culprit is one of your memorial files or one of your .sav files. If you go to your (bad) Application Support folder and run `grep -rl character_attempt_to_fall_asleep .` this will tell you what files are the issue. You can either remove those, switch back to experimental, or try to surgery out the bad part of those files by replacing the part that'll look like this (albeit with no newlines):
```json
"character_attempt_to_fall_asleep": {
  "event_counts": [
    [
      {
        "character": [
          "character_id",
          "1"
        ]
      },
      {
        "count": 2,
        "first": 5212800,
        "last": 5220001
      }
    ]
  ]
},
```
with nothing.

**Comment by jtmusky** [comment]
@perryprog Yep, that was it. Removed 3 files in the memorial folder and ran just fine.

Not sure if this issue needs to be closed, as the crash still didn't generate a `crash.log` But at least we discovered the underlying reason for the crash.¯\\\_(ツ)\_/¯

**Comment by jtmusky** [comment]
If it is any help, this was the memorial files that was causing the crash.

[Anastacia Branham-2024-02-04-11-10-54.json](https://github.com/CleverRaven/Cataclysm-DDA/files/15315357/Anastacia.Branham-2024-02-04-11-10-54.json)
[Anastacia Branham-2024-02-04-11-10-54.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/15315358/Anastacia.Branham-2024-02-04-11-10-54.txt)

**Comment by perryprog** [comment]
Yeah, I'd leave it open. I'm able to reproduce via the distributed binary but not from anything compiled from source (yet), but I'm still poking around.

**Comment by perryprog** [comment]
Yeah, no real clue and I'm only seeing it in this precompiled version (I haven't tested other precompiled versions). The only reason this seems to be happening is there's a segfault happening... somewhere (presumably near or during crash handling), and I can't tell where without debug symbols. That ended up preventing the crash.log from being written (hence the lack of message saying it generated one).

**Comment by jtmusky** [comment]
I'm at my capacity at this point as software engineering isn't my trade... if there is anything I can do to help, let me know. good luck
