### ISSUE TITLE
"Low Profile" scenario can start in town, despite description saying you left town

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#73733]
### Describe the bug

The "Low Profile" scenario can start you in a motel in town.

### Attach save file

[Heart Butte-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15288913/Heart.Butte-trimmed.tar.gz)

### Steps to reproduce

1. Create a character with the "Low Profile" start scenario
2. Sometimes, the starting location will be in a motel in town.

### Expected behavior

Either the description should be altered to match the starting locations, or the possible starting locations shouldn't include any inside a town.

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3; Build: 23D56; 
- Game Version: cdda-experimental-2024-05-12-1705 39e2afa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by TealcOneill** [comment]
/Confirm
This could be a good first issue. Either change the relevant spawn to only trailer parks or figure out what motels can spawn in cities and remove that from the scenario starting locations.

Some but not all relevant files for anyone wanting to take this on.
data/json/start_locations.json
data/json/scenarios.json
