### ISSUE TITLE
Item spawns not working right.

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#73731]
### Describe the bug

I'm not entirely sure about the extent of the problem but it seems like when I go to new areas now items don't get spawned on the ground or in furniture leading to a bunch of houses and stores that are empty save for the regularly spawned monsters. Interestingly enough the lockbox from a quest I needed did spawn in but everything else in the town seems to be gone.

### Attach save file

[Fort Wingate-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15288299/Fort.Wingate-trimmed.tar.gz)

### Steps to reproduce

I really don't know how this is happening or how to replicate.

### Expected behavior

Normal item spawn frequency

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-12-2300 fe9e803 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

I'm not sure how prevailant the problem is, I think it's new places spawned after an update that happened either early yesterday or the day before.

**Comment by NetSysFire** [comment]
already fixed by #73699

**Comment by Mister-Cultist** [comment]
> already fixed by #73699

Oh thank the Lord, I was getting paranoid about ruining my save I was making so much progress on.
