### ISSUE TITLE
Using the structural imager makes you learn an invalid spell that causes a segfault when cast.

### ISSUE THREAD

**Issue by AmeNyaa** [CleverRaven/Cataclysm-DDA#73749]
### Describe the bug

When I used the structural imager on the lastest experimental version, I stumbled upon this bug. While it's not really making the game unplayable, it's filling my spell list with junk that crashes the game. I tried to edit it out with the debug menu, but it also causes a segmentation fault.
I tested it on my save as well as on a brand new save.

### Attach save file

[Pandora-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15297462/Pandora-trimmed.tar.gz)

### Steps to reproduce

1. Spawn a Structural Imager
2. Reload it with a battery
3. Use the Imager

### Expected behavior

I kinda wish it didn't do that

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47608547/b368c95e-15c4-4b25-8642-c89f588bd6b0)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47608547/549efd6c-afd0-4b75-bbb3-40b47e7d143b)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47608547/92e091c6-a0f2-4043-9f07-d883ef3236e0)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47608547/9090c085-e1b1-4bb0-9af2-c8492231ec1f)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47608547/51e67934-efe4-423d-b102-1e43a5cfd521)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/47608547/9f36836d-d23f-41ce-a946-859d6115e3bb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-13-0447 81ede3c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15297720/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15297721/debug.log)

**Comment by Amnestasia** [comment]
Dealt with this before, forgot to make a bug report so thankfully someone else brought it up.

Its not a Magiclysm issue, its from Aftershock

Following the aforementioned steps leads to the same result.

Doing so again without Magiclysm also led to the same results, further showing it being an Aftershock issue. 

/confirm

**Comment by Cupidatis** [comment]
Using wands from magiclysm also make this bug.

**Comment by RenechCDDA** [comment]
Structural imager is in fact, Aftershock content not Magiclysm. Bit of a mistake on the tags there.

This was introduced by #73325. It should check if the spell is known/exists before trying to get it.

 known_magic::get_spell is also returning a reference to a spell that might not exist. Wow, that is also scary!
