### ISSUE TITLE
No extra soundpack is available in the game files for the mobile version.

### ISSUE THREAD

**Issue by Elshad19** [CleverRaven/Cataclysm-DDA#73748]
### Is your feature request related to a problem? Please describe.

Basically, you have to take extra steps to download the soundpack from the internet, manually extract them and move them to the correct folder within the game files. This is frustrating to do on mobile.

### Solution you would like.

Other than basic, at least Otopack should be available within the game files without an extra download. 

### Describe alternatives you have considered.

I know this is a far-fetched idea, but maybe put a download button within the game, so the game itself will take care of installing the soundpack. 

### Additional context

N/A

**Comment by ZhilkinSerg** [comment]
> Other than basic, at least Otopack should be available within the game files without an extra download.

No, it should not. This is a third party pack which is no bundled within the game.

**Comment by Elshad19** [comment]
The Otopack is the most popular which is the reason I wrote it first. Maybe another soundpack? Any other possible solutions? 

Unfortunately, it is not as easy as in PC version where you can download it straight from the launcher (as far as I know)

**Comment by harakka** [comment]
Otopack also contains copyright violating material so that's very fundamentally a no go. Including cc-sounds would double the apk size.
