### ISSUE TITLE
Messages for effects on other creatures is hardcoded

### ISSUE THREAD

**Issue by Hresvelgr401** [CleverRaven/Cataclysm-DDA#73746]
### Is your feature request related to a problem? Please describe.

I noticed that when a creature is downed a message is played when it attempts to stand. I tried to replicated this for a status effect I made but found that this was hardcoded rather then modifiable through .json

### Solution you would like.

If this text could be modified or added to effects using JSON files it would add more options for modding

**Comment by Brambor** [comment]
You can try to find the message. Dehardcoding might be less work if the person doing it is given the precise location of the text. And you can make sure the message isn't crazy complicated to construct.

**Comment by Hresvelgr401** [comment]
The message is found here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/monster.cpp#L2261
