### ISSUE TITLE
[MoM] NPC Muggers can steal your psionic pseudo-items

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#73753]
### Describe the bug

NPC muggers can steal psionic items such as the Lifting Field

### Attach save file

[Bonsai-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15300509/Bonsai-trimmed.tar.gz)

### Steps to reproduce

Havea lifting field, get mugged, have it stolen

### Expected behavior

Muggers should not be able to take the Lifting field or other psionically generated pseudo items

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/107653330/a4af4a54-21d4-44a5-a8ba-4ee7914aecfb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: dd42dbb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Mind Over Matter [mindovermatter],
    Sky Island [skyisland],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Standing-Storm** [comment]
Lifting field has the `INTEGRATED` flag, so it seems like that's being overlooked when considering what muggers can steal.

**Comment by RenechCDDA** [comment]
Needs a fix similar to #61098 if confirmed
