### ISSUE TITLE
Can NPCs be added with the function of driving vehicles on their own?

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#73759]
### Is your feature request related to a problem? Please describe.

no
Can NPCs be added with the function of driving vehicles on their own?

### Solution you would like.

Can NPCs be added with the function of driving vehicles on their own?

**Comment by fairyarmadillo** [comment]
I don't see why you couldn't get an NPC to autodrive if the player was also in the car.

For driving without the player, they would probably need a new system for calculating overland travel time and fuel cost and then basically teleporting to the destination. Maybe with a check for no monsters in the immediate area.

It would be super cool if you could radio for backup and have your buddy drive out to your location.

**Comment by PGR-14** [comment]
We already have the autodrive feature, & a calculation for how long fuel should last (in the vehicle building), could we not combine these for outside the reality bubble?
