### ISSUE TITLE
[Magiclysm] The "Night Vision color overlay" option does not disable the green backlight for the "dark sight" spell.

### ISSUE THREAD

**Issue by L1keThat** [CleverRaven/Cataclysm-DDA#73757]
### Describe the bug

To be honest, the green color not only hurts the eyes, it is quite strange that, playing for a magician, he sees everything in the dark green. After all, these are not bionics or night vision goggles.

But first of all it hurts the eyes, yeah. 

### Attach save file

[Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15301774/Test-trimmed.tar.gz)

### Steps to reproduce

- It is enough to study the Dark sigh spell
- Change the option in the settings, and look at the result.

If I understand everything correctly, there should be no green backlight.

### Expected behavior

It would be great if this green backlight didn't exist. Or at least it could be turned off.

### Screenshots

![sdh4545hhg](https://github.com/CleverRaven/Cataclysm-DDA/assets/169724547/a00f7ce2-328a-40a4-8842-434ee52ea6d5)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: aa7dd5c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded:
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]

**Comment by Standing-Storm** [comment]
Now that it's possible to to have variable night vision, this spell should probably be switched over to that, which will 1) remove the green overlay and 2) make your night vision better the better you know the spell.

**Comment by fairyarmadillo** [comment]
If different overlays are possible, a gray one might work here, especially at low levels. Classic D&D darkvision is grayscale based on the fact that rod cells in our eyes are good at seeing in poor light, but do not see color very well.
