### ISSUE TITLE
NPCs need to be able to eat/drink and walk at the same time.

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73768]
### Is your feature request related to a problem? Please describe.

I am always frustrated when...    I hand my NPC packmules a bunch of food to carry because I ran out of room and then I continue along my way, only some of them follow me, and I fail to notice that two of them are refusing to move because they are too busy stuffing their faces with the food items I wanted them to hold.  Everyone has to wait and the gluttons won't walk the distance of an overland map tile to get into the car because they repeatedly devour food.  This despite having No NPC needs mod. If the trek is more distant and I failed to notice the idiots had not left with the rest of the group, then we'll end up too far away for the idiots to know how to find us when they are finally done shoveling handfuls of cherries into their piehole. I then had to walk all the way back to wherever they decided to stop for tea and crumpets and escort them back to wherever we were going.

I'd eventually like to see _not_ requiring the No NPC mods, but I had to turn it back on because of the micromanagement. Admittedly this might be part of the problem I was facing (post-game start mod enabling), but I'm not so sure. However, if NPC needs were to ever function problem in a non-micromanaged manner by adding in smarter NPC food management logic,  we will also desperately need for them to be capable of walking and eating at the same time to avoid this particular hang-up.

### Solution you would like.

NPCs should be able to walk and eat at the same time.

### Describe alternatives you have considered.

Food and drink consumption units are multiplied so smaller bites and sips can be made and logic used to interleave sip/bite, walks some steps, sip/bite, etc. (with respectively divided up calories/quench numbers) rather than doing a high time cost consumption action or avoid allowing multiple high time cost consumptions actions to occur back to back.

Have new command/chat options  "tell everyone to take a meal/water break" then force that action to take place among NPCs capable of doing so.

**Comment by kevingranade** [comment]
At a guess, the NPCs were hungry when you enabled the no NPC needs mod, and now they're stuck in that state.
If so this is a great example of "we don't support changing mods during a game" as you guessed.

That aside though, if you hand a bunch of hungry people food, they're gonna eat it, though in practice it shouldn't take long at all before they're sated enough to start walking again instead of eating.

**Comment by O1OOO1O** [comment]
The NPCs that did this behavior had not joined me and I may have not even existed in the game yet at time I re-enabled the mod. I add in the mod early on within the first few in-game weeks, and these NPCs were ones I picked on a couple months in. At least one was from an evac center I had previously visited and had no NPCs present at the time of the first visit. (which is why I think they didn't exist). 

Regardless of the above, I'm still of the opinion that NPCs ought to be capable of the simple task of eating/drinking and walking at the same time.

**Comment by RenechCDDA** [comment]
This capability would have to be added to the player as well.

**Comment by O1OOO1O** [comment]
Adding it to the player too would be a good thing.

**Comment by TheSaddestGoomba** [comment]
Isn't this how smokeables are handled? I believe smokeables are comestibles too.

**Comment by fairyarmadillo** [comment]
In the past I have noticed situations where NPCs are spawned into the game severely underweight, even with NPC needs disabled. In these circumstances they will eat whatever they can get hold of.

I am not sure if this is an issue caused by updating my game while playing the same save (and thus a non issue) or if it's an ongoing problem. It may warrant further investigation.

**Comment by IdleSol** [comment]
Confirmed. Several times I've taken NPCs into followers who were exhausted. Despite me playing with a mod that disables their needs. Something like 25k calories or so. But I thought it was such a feature of their appearance or a flaw in the NPC modifications.

Is it necessary to track such cases and make reports?
