### ISSUE TITLE
NPCs refused to do any construction work.

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73765]
### Describe the bug

NPCs following you or assigned to a faction camp refuse to do any construction work. (or other jobs, but focusing on construction) 

### Attach save file

[Althea-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15308733/Althea-trimmed.tar.gz)

### Steps to reproduce

Load save.  Tell Gia Baird to do construction as their current activity. The save only has a single tile zone with a blueprint for chopping tree stumps/trunks into planks, which is directly west of the character. Gia is wielding a Hatchet. There are plenty of calories in Base Camp stocks. (150k+)  There any many NPCs assigned to the camp, all of them only have construction as their only job.
Gia Baird (and others) will say they have completed the task, but they never did anything at all.

### Expected behavior

I expect them to actually do the task and provide feedback as to what task they completed rather than "completed the task" If they cannot complete the task I expect feedback that states the explicit reason why they could not complete the task in the form of a useful, user-friendly, descriptive phrase. Ex:  "Gia Baird cannot [chop tree trunk into planks] because [it is too dark to see.]"
(it's not dark in the save, just an example)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2861 (23H2)
- Game Version: cdda-experimental-2024-05-07-0245 9514a3f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    No Hope [no_hope],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Disable NPC Needs [no_npc_food]
]

**Comment by O1OOO1O** [comment]
Thanks, I did not know that required a survival level 2.  I still say the bug is valid for 2 different reasons.
#1 I do have other NPCs assigned to the camp that have survival 2+ and they did not come out and try to chop anything. (base camp job assignments, not direct request)
#2 I need feedback that says Gia failed to [chop tree trunk into planks] because [lack needed survival skills].  instead of just "Completed the task". (which was an outright lie)
#3 If as you say they stop working on it because I move and the log disappears... that's also bad. The player character is going to be moving around.

**Comment by Icantthinkofanameforthis** [comment]
for the first thing there is a craft: wooden plank job at the bottom of the list but needs least 1 log in a basecamp: storage zone

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/cccdecdf-dcfa-464e-a4d1-fe35adc8121e)

**Comment by Icantthinkofanameforthis** [comment]
for the 2nd the task is [constructing blueprints] and its plural so they will do one then move to the next one they can do and once they cant find any they can do they pull a "Completed the task" so if theres no constructions they can do the task is complete so maybe it could have a conditional message saying they couldnt find a construction blueprint they could do if nothing was found

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/d4464510-e9de-4e75-8a05-ffae834de8ca)

**Comment by PatrikLundell** [comment]
I agree it would be useful to get feedback on why companions "complete" tasks.

However, it complicated due to how the code is constructed, with tasks split up into lots of little parts that sort of interact in non intuitive ways, using functions that just return whether something can be done or not, not why, and you can't place feedback within these operations because it sometimes just is a check that results in the next thing being tried, and sometimes resulting in the "completion" of the task (and, again, the code handling the "completion" doesn't have access to information of what the now deleted task was).
