### ISSUE TITLE
Construction menu needs option to choose NPC character to perform the task.

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73776]
### Is your feature request related to a problem? Please describe.

Just like in the crafting menu which lets you choose the crafter, the construction menu should also let you choose the builder. the list of available NPCs should be filtered by which ones meet the minimum skill requirements.  

### Solution you would like.

Add to the bottom of the construction screen UI the choice to choose the builder.

### Additional context
Add:
Press [c] to choose builder to construction screen.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/baed179a-e85e-4191-b48b-6180004bda8b)
Bottom of Crafting Screen (as reference example):
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/14aae469-51dc-4343-a119-a39b82a1e423)

**Comment by PatrikLundell** [comment]
No.

The way base camp construction works is that you select the job to perform and THEN you select the companion(s) to perform the task. Note that you can select multiple companions to get the job done faster.

Sure you could have some additional area listing the companions capable of performing the highlighted task, but that would take up more screen area, which I guess phone users might have an issue with.

**Comment by RenechCDDA** [comment]
Ehhh Patrik I believe this suggestion is for regular construction, not camp-related.

**Comment by O1OOO1O** [comment]
Yes, this is in regard to regular construction, not through the camp menu.

**Comment by natsirt721** [comment]
I haven't tried this in a bit, but the way I did this was to create a construction zone using the zone manager, then have the NPC work on the construction zone. No idea if that still works or not - this was two years ago or so.
