### ISSUE TITLE
Skunks will spray the player through barriers.

### ISSUE THREAD

**Issue by aapocalypseAArisen** [CleverRaven/Cataclysm-DDA#73786]
### Describe the bug

While behind the barrier of a car with no holes or entryways a skunk approached. From the outside of the vehicle it sprayed me.

### Attach save file

N/A

### Steps to reproduce

Used debug mode and loaded a new world. I then searched for a car with no damage that would allow for entry or access by the skunk. Spawned a skunk. I let it approach the car where it was still able to spray me despite having no access to my location.

### Expected behavior

For the skunk spray to be unable to penetrate barriers such as the exterior of a car.

### Screenshots

N/A

### Versions and configuration

Build 2024-05-13-1913

Only added mod is stats through kills.

### Additional context

None

**Comment by TheMurderUnicorn** [comment]
Hmm.  If this is happening I'm not sure how to fix it, I assumed barriers would block the spell.  The spell system was hard for me to understand, I don't know what I might have done wrong, I might need someone other than me to look at this, I'm sorry.

**Comment by NyarlathotepZERO** [comment]
Can confirm that skunks will still (most annoyingly) spray through closed windows/walls to great effect, as long as the player is visible. This is happening in experimental [2025-01-27-1239]

This issue should remain open.
