### ISSUE TITLE
Can't start a new game since #73750

### ISSUE THREAD

**Issue by ama0** [CleverRaven/Cataclysm-DDA#73787]
### Describe the bug

It is possible to generate a new world, but not possible to create a new character since https://github.com/CleverRaven/Cataclysm-DDA/pull/73750

### Attach save file

[Chiniak-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15313133/Chiniak-trimmed.tar.gz)

### Steps to reproduce

1. Have version with https://github.com/CleverRaven/Cataclysm-DDA/pull/73750 merged
2. Create World
3. Create new character
4. Crash with error message (see additional context)

Steps to fix:
1. Revert to version prior to https://github.com/CleverRaven/Cataclysm-DDA/pull/73750 (I reverted to 2ac99ba29c)
2. build
3. Create world
4. Create new character
5. Play game

### Expected behavior

Can create new character and start a new game

### Versions and configuration

 - OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux trixie/sid; Release: n/a; Codename: trixie; 
- Game Version: cdda-experimental-2024-05-14-1152 2ac99ba29c-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

```
 DEBUG    : Error: Json error: home/ama0/Projekte/Temp/cdda/share/cataclysm-dda/json/construction/appliances.json:4:10: <color_white><color_cyan>Duplicate construction id</color>

  {
    "type": "construction",
<color_light_red>    "id": "ap_box_battery_charger",</color>
        <color_cyan>▲▲▲</color>
    "group": "place_ap_box_battery_charger",
    "category": "APPLIANCE",
</color>


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 1051
 VERSION  : cdda-experimental-2024-05-14-1902 c7d88dcbe8-dirty
```

**Comment by Procyonae** [comment]
Latest build works fine locally for me, looking at your filepath you're not exactly using a traditional install so however you updated probably didn't remove construction.json

**Comment by ama0** [comment]
> Latest build works fine locally for me, looking at your filepath you're not exactly using a traditional install so however you updated probably didn't remove construction.json

You are right. It was actually removing the old construction.json that fixed it for me. Thx

**Comment by RenechCDDA** [comment]
I would also recommend a completely fresh install. Even if that resolved the visible issue, whatever caused your previous one may have left other surprises which are not immediately apparent.
