### ISSUE TITLE
Leather does not burn?

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7380]
I piled up huge heap of generic clothes in my fireplace. Following a night of raging fire, morning revealed survivors: items made of silver and items made of leather. I tried a few times again, but leather did not seem impressed at all.

Maybe silver items are supposed to survive fire, but leather? Probably should be somewhat resistant, but not immune. 

This, again, returns us to the issue of overwhelming amount of generic crap from zombies. It's useless, pollutes the area and, I imagine, is not very good for save file. Would be nice if we had a proper way of disposing of it. Turned out burning doesn't work that well (rain makes it even worse). Easiest way would probably be to use acid. Bionic that allows you to create acid puddle for low cost?

**Comment by mugling** [comment]
Is this still true after the recent changes to materials?
