### ISSUE TITLE
Snow-Cones

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73809]
### Is your feature request related to a problem? Please describe.

Seems like a fun idea

### Solution you would like.

Add in an appliance for a snow machine. Recipe goes as follows: 
Tools: Snow Machine
Materials: Clean water (2 units) & [Syrups & sugary drinks (I.E. Maple syrup or cola)]

**Comment by TheMurderUnicorn** [comment]
For the record I am working on this, just have to iron out some kinks and do a bunch of tedious naming convention legwork 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41651793/27fae66e-b0ca-4a57-8308-95195776b5a8)
I hope to be done soon but soon is relative.
