### ISSUE TITLE
Game Crash when using Coffeemaker attached to mounted kitchen to heat up liquid food

### ISSUE THREAD

**Issue by Brroleg** [CleverRaven/Cataclysm-DDA#73803]
### Describe the bug

It crashes only when coffeemaker attached to mounted kitchen. If you attach it to dashboard it works normally 

### Attach save file

N/A

### Steps to reproduce

1. Get a car with mounted kitchen 
2. Get a coffeemaker and attach it to the mounted kitchen
3. Exam mounted kitchen, select use coffeemaker and try to heat up liquid food using it

### Expected behavior

Game expected to not crash when coffeemaker attached to mounted kitchen is used to heat up liquid food

### Screenshots

![176415](https://github.com/CleverRaven/Cataclysm-DDA/assets/67473828/ecace5ac-3ae7-48b6-9b0a-99ddf39478a5)

### Versions and configuration

Experimental build 2024-05-15-0120

**Comment by Holli-Git** [comment]
/confirm 
Does seem to be a repeat of #73657 though
