### ISSUE TITLE
Magiclysm and Pain - Healing the wound should heal the pain

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#73806]
### Is your feature request related to a problem? Please describe.

So i recently got into Magiclysm again, and i notice that when i get hurt and heal with cure wounds, it does not affect the pain from the wounds. Even when healed to full.

### Solution you would like.

I would expect that when my wounds are healed, the pain caused by them is also removed.

### Describe alternatives you have considered.

I'm not a doctor, so i guess there could be reasons for the pain lingering after the wounds\reason for it is gone, but i would at least expect it to be greatly diminished.

**Comment by PGR-14** [comment]
IRL, w/ bandages, it would make sense that you'll be in pain. But w/ cure wounds, you aren't applying protection/absorbent material, you're mending the wound & growing flesh, so I'd expect for your nerve cells to calm down.

**Comment by rty275** [comment]
The problem is that I don't think there's a perfect model of how much damage equals how much pain (though I could be wrong about that) so deciding how much pain each Cure Wounds restored would be somewhat arbitrary. I can also see an argument for phantom pain lingering beyond the direct healing of the wounds, nerves do weird things sometimes.

**Comment by EternalLaughter** [comment]
> The problem is that I don't think there's a perfect model of how much damage equals how much pain (though I could be wrong about that) so deciding how much pain each Cure Wounds restored would be somewhat arbitrary. I can also see an argument for phantom pain lingering beyond the direct healing of the wounds, nerves do weird things sometimes.

If there's no perfect model, i'll be fine with "just" a decent one :) 
As stated i don't know how nerves would react to magical healing, but i would expect a large reduction in any lingering pain signals somehow still getting sent.
