### ISSUE TITLE
"interacting with the vehicle" dialog stays visible after action is complete

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#73810]
### Describe the bug

When removing a swappable storage battery from an electric street sweeper, the "interacting" IMGUI dialog stays visible after the action is done. The dialog does disappear when exiting the vehicle screen.

### Attach save file

N/A

### Steps to reproduce

1. Spawn an electric street sweeper
2. (e)xamine it, find the battery
3. rem(o)ve the battery

### Expected behavior

The "interacting" dialog should appear, then disappear.

### Screenshots

<img width="781" alt="Screenshot 2024-05-15 at 10 48 54" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/172800/afab467e-60d9-45e3-bee7-aa9692478412">

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3; Build: 23D56; 
- Game Version: cdda-experimental-2024-05-12-1705 39e2afa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by tinukedaya** [comment]
Happened to me while repairing (removing and installing) broken oars on a Canoe.

**Comment by PGR-14** [comment]
That's not just IMGUI, I think that's happened before it.
