### ISSUE TITLE
LIXA: Teleporting Deaths

### ISSUE THREAD

**Issue by ShnitzelX2** [CleverRaven/Cataclysm-DDA#73813]
### Describe the bug

Playing in a build (off of master) from about a week ago, upon defeating the "unfolded impossibility" in the LIXA unfolded space, my character (Chris Isherwood) was instantly killed. 
```
  Final Messages:
  3:16:32 PM Good hit!
  3:16:32 PM You hit the unfolded impossibility for 52 damage.
  3:16:32 PM You shoot your M4 carbine+6.  Blam!
  3:16:32 PM You hear thump!
  3:16:33 PM You shoot your M4 carbine+6.  Blam! x 2
  3:16:33 PM Grazing hit.
  3:16:33 PM You hit the unfolded impossibility for 4 damage.
  3:16:33 PM You hear thump!
  3:16:34 PM You shoot your M4 carbine+6.  Blam!
  3:16:34 PM Good hit!
  3:16:34 PM You hit the unfolded impossibility for 37 damage.
  3:16:34 PM You shoot your M4 carbine+6.  Blam!
  3:16:34 PM Good hit!
  3:16:34 PM You hit the unfolded impossibility for 44 damage.
  3:16:35 PM You shoot your M4 carbine+6.  Blam!
  3:16:35 PM Good hit!
  3:16:35 PM You hit the unfolded impossibility for 46 damage.
  3:16:35 PM The unfolded impossibility dies!
  3:16:35 PM There is a soft sound, like a champagne cork popping in an empty concert hall.  The world is as it was again.  The LIXA device still hums quietly as it finishes powering down.
  3:16:35 PM Your torso is no longer disinfected!
...
| Year 1, Summer, day 17 3:16:35 PM | LIXA device floor | Died
```

To clarify, there were no messages about damage, all body parts went from mostly-full to zero health, and my character appeared to teleport to the correct location. This LIXA was facing **east**.

To be safe, I downloaded the latest experimental release. I spawned LIXA facing **south** in a new world. I saw the main laser pipe emitting congealed light -- that didn't happen my first time through LIXA -- and monsters weren't spawning in the unfolded space after a while, so I had to spawn in an unfolded impossibility to kill it and successfully exited the space. I tried this multiple times and encountered no issues.

Then I spawned LIXA facing **east** in another new world and it appears my character (Clay Foxtail) was teleported to the wrong Z-level while just traveling through the unfolded space (_without_ fighting the unfolded impossibility):
```
Final Messages:
  9:12:32 AM Moving onto this photonic conduit is slow!
  9:12:33 AM Moving off of this photonic conduit is slow!
  9:12:37 AM Moving onto this photonic conduit is slow!
  9:12:38 AM Moving off of this photonic conduit is slow!
  9:12:42 AM Moving onto this photonic conduit is slow!
  9:12:43 AM Moving off of this photonic conduit is slow!
  9:12:47 AM Moving onto this photonic conduit is slow!
  9:12:47 AM You fell down a ledge!
  9:12:47 AM You fall down 10 stories!
  9:12:47 AM You're staggered off-balance.
  9:12:47 AM You've been badly wounded.  It might be better to rest for a while and let someone else scavenge.  (Changing characters is now available at any camp board.)
  9:12:47 AM You are no longer able to wield your M4 carbine+1 (<color_c_light_green>24/30</color> 5.56 NATO M855) and drop it!
  9:12:47 AM Your M4 carbine+1 tumbles to the pavement.
  9:12:47 AM You're staggered off-balance.
  9:12:47 AM You're stunned!
  9:12:47 AM You are slammed against the pavement for 753 damage.
  9:12:47 AM You're knocked to the floor!
  9:12:47 AM You see here 1 M4 carbine+1 (<color_c_light_green>24/30</color> 5.56 NATO M855).
  9:12:47 AM You walk for a long while.
  9:12:47 AM You see here 1 M4 carbine+1 (<color_c_light_green>24/30</color> 5.56 NATO M855).
```

### Attach save file

My characters were killed, so there's no save files to recover; the issue doesn't seem to consistently occur anyways.
[Chris Isherwood-2024-05-14-21-55-25.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/15326821/Chris.Isherwood-2024-05-14-21-55-25.txt)
[Clay Foxtail-2024-05-15-15-32-56.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/15326824/Clay.Foxtail-2024-05-15-15-32-56.txt)

### Steps to reproduce

Enter the unfolded space in LIXA and defeat the unfolded impossibility. Reproducibility seems inconsistent.

### Expected behavior

Escaping the unfolded space and not being teleported into the sky, respectively.

### Versions and configuration

(Chris Isherwood)
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9226-g0a74bb4ba2-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

(Clay Foxtail)
- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-15-0120 731bdaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ShnitzelX2** [comment]
Somebody else encountered this bug here: https://www.reddit.com/r/cataclysmdda/comments/1csptfd/lixa_lab_finale_glitched/

**Comment by ShnitzelX2** [comment]
I reproduced the bug consistently in this save: 
[Bouse-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15372624/Bouse-trimmed.tar.gz)

To trigger the bad teleport:
1. Walk east.
2. Kill the eigenspectres that show up (doesn't matter how).
3. Continue east.
4. Die upon reaching the "end" of the section with the eigenspectres.

**Comment by davidwgoodall** [comment]
Same issue, fortunately/unfortunately auto saved kicked in about 10 moves before the teleport death. It seemed like a bug so I crashed out, trapped now, until this can be fixed
