### ISSUE TITLE
easily transport garbage dug out from underground to the ground?

### ISSUE THREAD

**Issue by jcy1001** [CleverRaven/Cataclysm-DDA#73829]
### Is your feature request related to a problem? Please describe.

Is there a component similar to a conveyor belt, or could such an item be added to the game, to easily transport garbage dug out from underground to the ground?

### Solution you would like.

Is there a component similar to a conveyor belt, or could such an item be added to the game, to easily transport garbage dug out from underground to the ground?

**Comment by Brambor** [comment]
I recommend Discord for such questions: https://discord.com/channels/598523535169945603/642349261320880128 (I hope this link works).

Have you tried hauling `\`?

**Comment by jcy1001** [comment]
yes this is haul by man，I mean we add  a component similar to a conveyor belt to easily transport garbage dug out from underground to the ground

**Comment by Maddremor** [comment]
A conveyor belt is outside the scope of what the player can reasonable set up. You are better off using a mix of hauling and sorting zones.

**Comment by MoonlitRiverlight** [comment]
You could make a railway and have a robot-controlled vehicle do the rounds, with a scoop, but it wouldn't solve unloading. Tidying the area with an npc could unload.
But any of these would hit your processing speed a lot.

**Comment by kevingranade** [comment]
I don't think setting up a conveyor belt is *completely* outside the capabilities of the player, but what I really question here is if there is a use case that is feasible for the player that requires one.
The same applies for e.g. a minecart and track. It's even more feasible than a conveyor belt,  but digging a mine is not really a feasible thing to do in the first place.
I think the solution that meets the player needs is more of a feature where you can move items from one zone to another to eliminate micromanagement.

**Comment by Brambor** [comment]
> but digging a mine is not really a feasible thing to do in the first place.

Isn't it? With a couple of NPCs, it takes 1_hour/nuber_of_npcs per tile. I got 3 NPCs mining to get copper. But I figured copper probably cannot be mined (mined over 300 tiles). So I got into the copper tube buissness of disassembling large machines in 20 mins.
