### ISSUE TITLE
Shouldn't dissassembling a standing mirror with a glass cutter give me several hand mirrors instead of glass sheets?

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73826]
### Is your feature request related to a problem? Please describe.

Shouldn't disassembling a standing mirror with a glass cutter give me several hand mirrors instead of glass sheets? I am after all carefully cutting the mirror into precise squares not breaking it into pieces. Where does the silvered backing go otherwise?

### Solution you would like.

A disassembled standing mirror ought to give multiple hand mirrors (based on 2 glass sheets worth) and the scrap aluminum it normally provides instead of glass sheets. (the game only has two sizes of mirrors)

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/82064797/80ec322b-0c18-41d4-acb2-d270b0ce4efd)

**Comment by Karol1223** [comment]
A hand mirror is worth 3 shards, not a full sheet. And they're not just a piece of glass - it's an item that's just a handheld mirror, as the name implies.

This would need some new item along the line of mirror glass pieces.

**Comment by O1OOO1O** [comment]
That's why I said 'multiple' hand mirrors but didn't specify the amount that can be determined by volume equivalency or something as appropriate.   I'm not opposed to new alternate mirror sizes, but what else would they be used for in a game? Hand mirrors right now are an obvious meta-interpretation when you can use one for a smallish shaving kit and for a wing mirror on a Semi truck.  The goal of this request was just an extra thing to source hand mirrors from.  

Other possible mirror usages:
Periscopes, solar concentrators, safely peeking around corners (though the peek function already does this), reflecting sunlight/light to permit more lighting in otherwise darkened interior rooms.  Visual bait for zombies.  Components for devices related to optics and lasers.
