### ISSUE TITLE
Instead of just showing floats/doesn't float for a vehicle, show how much weight it can float vs how much the vehicle currently weighs.

### ISSUE THREAD

**Issue by ryeookin** [CleverRaven/Cataclysm-DDA#73857]
### Is your feature request related to a problem? Please describe.

Since its hard to determine exactly where the edge is for how many boat hulls you need before you sink with just the 'sinks/floats" notifier in the vehicle screen I end up just putting boat hulls in every square of my vehicles since its unclear where the sink edge is.

### Solution you would like.

It would be nice if instead of "floats/sinks" in the vehicle screen we saw something like "can float x amount of weight/your vehicle currently weighs x" or something similar so we had a better guide how close to the edge we are buoyancy wise. 

Bonus: if possible if the buoyancy value weight number is greater then the vehicle weight number then make the text green (or perhaps yellow if its very close a net buoyant positive value), else make the text red (something like that).

Thanks for your time!

**Comment by TealcOneill** [comment]
I do think this would be a good idea. 
As a note through, the draft/clearance indicator does allow you to gauge this in an okay manner. 
Draft is how much of the boat is under water and thus relates to the drag of the boat while the clearance is how much of the hull is above the water. If the clearance remains positive then the boat will float. 👍

**Comment by TealcOneill** [comment]
I apologize, my first sentence could have been clearer.
I am for this change. It's something that would be absolutely beneficial for players. I approve of this idea. 👍 

I added the other stuff for you and other players who might see this issue in order that our current system is better understood until this change is added. 

I also agree with it not being a good indicator, but at that it's a better indicator than just sinks/floats.

**Comment by ryeookin** [comment]
Hmm, after rereading things, if you didn't edit your post from May 17th, then this is on me and I read what you said wrong. If that's the case then my apologies. In any case it appears we're on the same side of things. Also thanks for the extra info regarding draft and clearance. :)
