### ISSUE TITLE
Allow ``rot_spawn`` to define a monster ID directly instead of needing a monstergroup

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#73858]
### Is your feature request related to a problem? Please describe.

``rot_spawn`` only takes monstergroups. This is evil, because it means for every egg-laying animal that we allow to reproduce we need a custom monstergroup with just one entry for the baby version. This is annoying as hell.

### Solution you would like.

Allow ``rot_spawn`` to take monster IDs directly to cut out the middle man

### Additional context

It's important to note that it should still be allowed to take monstergroups as well, since some of our eggs do rely on that. I am asking for a new possibility, not to replace the existing one with another.

**Comment by NetSysFire** [comment]
I wonder if this might be easy enough for me to slap good first issue on this.
