### ISSUE TITLE
I see dead people

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73886]
### Describe the bug

Well, I was walkin' around minding my business in the refugee center when I noticed that the hunter was dead. I've seen this prior to this bug report, but I just thought it was a side effect of some of my mods. Recently I trimmed my mod folder, & the issue continues (Most of my mods are minor additions & item mods). This doesn't just include NPCs who disappear & reappear, it can also include NPCs like the Old Guard Rep. However, I haven't seen it happen w/ the other factions, but it may just be from the large sample size of the refugee center.

### Attach save file

[Coffee-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15355177/Coffee-trimmed.tar.gz)

### Steps to reproduce

1. Go to refugee center (It works whether you travel to it, or if you spawn in it (Safe place))
2. Look around, see if anyone's dead
3. If not, unload the area (The bandit cabin nearby should be enough) & repeat step 2. If it is, despair.

### Expected behavior

Not seeing dead people

### Screenshots

![Pheevos Gregory _2024-05-17T13-38-13](https://github.com/CleverRaven/Cataclysm-DDA/assets/142340122/06531106-8041-4f1f-8008-e3e14862668d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: cdda-experimental-2024-05-16-1442 9cb81a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Tankmod: Revived [Tankmod_Revived],
    Blazemod - Vehicle Additions Pack [blazemod],
    Ships From Oa Additional Buildings [Ships],
    Bionic Professions [package_bionic_professions],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Dorf Life [Dorf_Life],
    Morlock Village [morlock_village],
    Extra Mutated Scenarios [extra_mut_scens],
    New start locations for Extra Mutated Scenarios [new_start_locations_for_extra_mutation_scen],
    Mythical Martial Arts [MMA],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More Survivor Notes [more_survivor_notes],
    More Professions can start in Extra Mutated Scenarios [more_profession_chooses_extra_mut_scens],
    Mind Over Matter [mindovermatter],
    Mind Over Matter: <color_magenta>Remove Random Delay Before Gaining Power Insight</color> [mom_no_power_path_check_learn_delay],
    Mind Over Matter: <color_magenta>Remove Rolling Delay in Each Path for Checking Learning Prerequisites</color> [mom_no_power_learn_delay],
    Mind Over Matter: <color_magenta>Remove Concentration Limit</color> [mom_infinite_concentration],
    Mind Over Matter: <color_magenta>Remove Calorie Cost from Psionics</color> [mom_no_calorie_cost],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    Mind Over Matter: <color_magenta>Double Limit Before Pain Disables Powers</color> [mom_raise_pain_disables_psi_limit],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Hands [hand],
    Dream of Flight [dream_of_flight],
    Custom Portal Storm Size [custom_size_ps],
    Custom Frequencey For Portal Storms [custom_freq_ps],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Bionic Traits [bionic_traits],
    Alternative Map Key [alt_map_key],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Targeted Mutagens [targetedmutagens],
    Frontier Mods Core [frontier_core],
    Loadout [loadout],
    Gunsmith [gunsmith],
    Culinary Days Ahead [culinary_days_ahead],
    Jackledead Armory [jackledead_armory],
    Xedra Evolved [xedra_evolved],
    Make bows great again [bow_opness],
    Better Arachnids [betterArachnids],
    Aftershock [aftershock],
    <color_light_red>Secronom</color> [secronom],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Additional backgrounds [Arendeth_Additional_backgrounds],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    No Bionic Slots [no_cbm_slots],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by osuphobia** [comment]
@NetSysFire Could this be relevant to #73352 ?

**Comment by NetSysFire** [comment]
As far as I know this test is failing because of vehicle shenanigans and there are no vehicles here

**Comment by osuphobia** [comment]
> As far as I know this test is failing because of vehicle shenanigans and there are no vehicles here

I'm not sure, I thought it was caused by the very tall trait that made the NPC unable to stay in the car, but when I tested it locally, the NPC seems to be normal sized.

NPC(s) died during(?) or before the CHECK is very suspicious.

**Comment by PGR-14** [comment]
Maybe it could be from malnourishment? I've seen many NPCs that have barely any meat on their bones & have severe malnourishment for little to no reason. IDK if they can die from this though. Even so, this should be fixed by Disable NPC Needs.

**Comment by RenechCDDA** [comment]
It shouldn't be currently possible for them to die from malnutrition/lack of water even if you had enabled NPC needs. You still have NPC needs disabled.

**Comment by harakka** [comment]
> shouldn't be doing anything like this (That I know of)

Shouldn't doesn't mean they don't, people include weird things. No-one knows what's in there, that's kind of the problem, unless you've specifically audited all the json.

**Comment by PGR-14** [comment]
> > shouldn't be doing anything like this (That I know of)
> 
> Shouldn't doesn't mean they don't, people include weird things. No-one knows what's in there, that's kind of the problem, unless you've specifically audited all the json.

Alright, I'll look into it.

**Comment by PGR-14** [comment]
Did a few runs normally, nothing (Might have been unlucky however, more tests needed). Tried a couple of times w/ magiclysm (mainly 'cause it affects NPCs quite a bit) & it worked
![TESTMAN _2024-05-20T17-50-00](https://github.com/CleverRaven/Cataclysm-DDA/assets/142340122/c859ebd7-d9bf-4309-8542-1f4e0053524b)
Here, you can see that the broker has died. So it may or may not be a problem w/ magiclysm

**Comment by PGR-14** [comment]
Will try w/out magiclysm to see if I can reproduce it.

**Comment by PGR-14** [comment]
Tried several times, nothing. Seems to be a magiclysm issue.

**Comment by harakka** [comment]
Can you provide the save where it happened to you with Magiclysm? Helps with investigating

**Comment by PGR-14** [comment]
Got it.
![TESTMANN _2024-05-21T10-58-30](https://github.com/CleverRaven/Cataclysm-DDA/assets/142340122/a9fe2f54-3bad-48be-811f-325c05dddbf8)
Mandeep is dead.
[  TEST-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15391641/TEST-trimmed.tar.gz)
Here's the save.

**Comment by PGR-14** [comment]
Has there been any work on fixing this?

**Comment by PGR-14** [comment]
Sorry, was just a bit concerned. I'll wait.

**Comment by RenechCDDA** [comment]
This should be doubly no longer possible with the addition of NPC camps. I wasn't able to reproduce it in the first place. Are you still encountering the issue?

**Comment by PGR-14** [comment]
No actually, seems to be fixed.
