### ISSUE TITLE
Dr. Prado doesn't always spawn w/ EMP grenades for the prototype robot Hub01 quest

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#73894]
### Describe the bug

Neither the EMP grenades, nor any of the armor the Intercom dialog mentions after the fact appeared on any corpse that was near the location of the robot. There was in fact no corpse near the robot.  I deduced that from the blood stains and a zombie corpse (that I didn't kill) nearby, that the corpse must have risen as a zombie and then went to a prior save and verified that this can happen by re-triggering the quest.

### Attach save file

[Althea - Copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15360182/Althea.-.Copy-trimmed.tar.gz)

### Steps to reproduce

Trigger the Prototype robot quest from Hub01 and go to the quest site. (don't need to kill the robot just long-range teleport to the quest location and evaluate the condition of the scientist corpse that spawns there.  This does not always repro, I had to reload multiple times and go through multiple checks.
If the body spawns as a corpse and stays a corpse, the EMP grenades and other items have always been present so far. If this occurs reload and re-trigger the quest and check again.
If the body rises as a zombie and gets killed immediately by the robot, often getting knocked several tiles away) the labcoat w/ EMP grenades _sometimes_ does not appear, and other Hub01 identifying gear may not appear or get added to the zombie's inventory/equipped items.   

This might be getting caused by the No Hope mod which reduces items?

### Expected behavior

Either the corpse does not rise as a zombie for quest dialog consistency, or if it does rise, all equipment intended to help aid in the completion of the quest remains intact and lootable from the zombie corpse.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2861 (23H2)
- Game Version: cdda-experimental-2024-05-16-2203 554b537 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    No Hope [no_hope],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Disable NPC Needs [no_npc_food]
]

**Comment by PGR-14** [comment]
It's no hope, it sometimes just forces important things to spawn, there should be a flag for No hope to spawn certain things

**Comment by IdleSol** [comment]
#71528 
This is a problem with the “Item Spawn Scaling Factor” setting and how the relevant things react with it.
