### ISSUE TITLE
Allow the player to turn off/disallow certain Martial arts techniques like headbutts and kicks.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#73890]
### Is your feature request related to a problem? Please describe.

When using brawling or even force unarmed the character can randomly decide to headbutt or kick that one plant monstrosity like a WWE fighter rather than gore it with his mutant/cyborg claws. This has made martial arts become underpowered recently, more so than it already was. It stands to reason that someone who knows how to throw some punches can choose to use its mostly deadly techniques for the appropriate situations rather than roleplay john scena.

### Solution you would like.

Would be nice if we could disallow certain body parts/techniques from being used since the damage is tied to what kind of armor you using or mutations. If I'm a rat mutant with gnarly claws i want to shred my opponents with them.

**Comment by Venera3** [comment]
The solution that's going to happen is restructuring the attack logic and allowing skill-dependent choosing of the best attack to attempt.

Per-tech toggles just lead to clicky micro and leaves everything playerside, which is not really how combat should work.
