### ISSUE TITLE
Autodriving across bridge causes crash

### ISSUE THREAD

**Issue by bateau-de-coal** [CleverRaven/Cataclysm-DDA#73893]
### Describe the bug

Autodriving across a bridge causes crash.

### Attach save file

[Hackberry-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15359998/Hackberry-trimmed.tar.gz)

### Steps to reproduce

Autodrive to west across the bridge

### Expected behavior

no crash

### Versions and configuration

os: ubuntu
build type: linux-curses-x64
version: cdda-experimental-2024-05-13-1656 3a16ecf
language: german
mods: default

### Additional context

driving manually across the bridge doesn't cause crash

**Comment by MoonlitRiverlight** [comment]
Had this happen to me this week too.
