### ISSUE TITLE
Weak stomach/nausea/vomitous trait keeps looping itself into upgrading and downgrading.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#73907]
### Describe the bug

If you take mutagen catalyst and rat mutagen and get basically every mutation at some point, you will loop between the weak stomach/nausea/vomitous traitline.

### Attach save file

[Ridge Ratta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15366096/Ridge.Ratta-trimmed.tar.gz)

### Steps to reproduce

1.Take tons of rat mutagen
2. Wait to get mutations
3. Watch weak stomach loops back between nauseous and vomitous

### Expected behavior

I assume it isn't supposed to be upgrading and downgrading itself

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-13-1412 dd42dbb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Lives - Extended [extra_lives_extended],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

**Comment by Kamejeir** [comment]
Poison Resistant is the prereq for Intestinal Fortitude and stays there, so what this bug report... reports is that Weak Stomach, Nausea and Vomitous are wasting vitamins flip-flopping. I'm looking into it.
