### ISSUE TITLE
Make static portals dynamic

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#73903]
### Is your feature request related to a problem? Please describe.

There's no way I'm aware of to remove static portals, they just endlessly spawn nether stuff.
It's weird imo that the portal is stable, it's gamey that stuff infinitely pours through them and it's annoying that they're a permanent feature if you want to setup near one.

### Solution you would like.

Make portals appear and dissappear.
Personally how I see appearing working is having a reoccurrence EoC with a random timer have a very low chance to spawn a portal, and then spawning the creatures with similar random timer reoccurance EoCs and making the portal collapse after a random number have spawned. You'd still be able to find map extra portals so it doesn't seem fully player centric but they'd collapse in the same fashion.
Some thought would need to be put into where these can spawn as they'd likely need to avoid basecamps, NPCs and faction bases as well as not spawn too close to the player. They may also want to be prevented while the player is sleeping to avoid bs like flaming eyes staring at you for 8hrs. To begin with just spawning them in (non-special) fields+forest is probably reasonable.

### Additional context

I'll attack this myself eventually if noone else does but if someone wants to do it sooner you're more than welcome

**Comment by IdleSol** [comment]
Do they have a connection to the portal storm? From a lore perspective.

From a player perspective, I would like to be able to close these portals. An item or vehicle that can close a portal. Or stabilize it and connect it to another stable portal.

**Comment by Nebnis** [comment]
There is an item that can close them but it is really hard and dangerous to get and one time use only, Maybe it could be a hub 01 reward at some point

I fully agree for the portal to collapse eventually after a set amount of enemies. Difficulty aside, infinite spawning portals also tanks the game performance severely and make it extremely painful exploring their areas. There could be weak or strong portals, spawning from 1~3 to 3~5 enemies

**Comment by IdleSol** [comment]
We can add a charge value for each portal. Make the charge level random or within certain limits. 

As a second value, add a decrease in charge per turn or time. When the charge reaches a value less than zero, the portal closes.

For each of the monsters, set the cost in charges. If a monster spawns, the portal charge is reduced.

Portal storms, can add charge to the portal. Labs add a field that generates this charge and tie it to a “switch” in the basement. Once the switch is turned off and the charge is depleted, the place becomes portal-free.

Items: special grenades (in the name of democracy). When exploding in a portal, wastes its charge.
Vehicles. Build a special transport (3x3, with an empty space in the center) and drain the charge from the portal, replenishing the batteries. Or spend the batteries' charge to reduce the portal's charge. Depends on the implementation.
