### ISSUE TITLE
`Oversized trapdoor spider` doesn't fight in a vehicle

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73913]
### Describe the bug

This spider would kill me, I went into a vehicle, and it followed me. It still follows me, but it doesn't attack me. Is that normal?
I drove with it for like 5 minutes

The spider just rides along, and fights only when I leave the vehicle.

I cannot hit it, it says "wait for a bit" for ~100ms and then no time passes.

I could even bandage wounds without it disturbing me.

### Attach save file

[Min Max it-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15366800/Min.Max.it-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. pass time (spider doesn't fight)
3. Try to hit it (nothing happens)
4. Try leaving car (spider will attack)

### Expected behavior

Spider fights me and kills me.

### Screenshots

The spider just rides along, fights only when I leave the vehicle.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/db819268-53c3-4741-b47a-3c28a436fed4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9614-gf522d7df2d-dirty [64-bit] master was f522d7df2d
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by fairyarmadillo** [comment]
#48296 Related or duplicate, I think, and not a new problem. I thought this was fixed though.

**Comment by Brambor** [comment]
Thanks, I couldn't find it before. I would close this as duplicate, but I am not 100% sure if the `oversized trapdoor spider` is a "graboid". Also, that issue talks about NPC breaking, but this is talks about the inability of any fighting between PC and the spider. So I would leave this open. If somebody else feels different, close it as a duplicate. 

A good fix will _likely_ close both these issues.

**Comment by toweroglass** [comment]
the plug arachnid, but he chill
