### ISSUE TITLE
supernatural abilties menu creating hotkey for spell that doesnt exist leading to excessive error repetition

### ISSUE THREAD

**Issue by cddaplaya** [CleverRaven/Cataclysm-DDA#73922]
### Describe the bug

Not sure how but supernatural ability menu has created a spell at the top of the menu which if used crashes the game and since showing up causes an excessive error repetition detected whenever doing any activity that passes time.

### Attach save file

[Pennsauken-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15369130/Pennsauken-trimmed.tar.gz)

### Steps to reproduce

1. Open up supernatural abilities menu and cast 1st spell to crash game
2. Reload save and attempt to pass time resulting in excessive error repetition detected

### Expected behavior

Unsure how spell got into menu in 1st place but would like to not have the error pop up every time I pass time

### Screenshots

![cdda1](https://github.com/CleverRaven/Cataclysm-DDA/assets/170238849/a95c47f0-c6d3-4631-85b9-1e25d4a67ec9)
![cdda2](https://github.com/CleverRaven/Cataclysm-DDA/assets/170238849/338e5326-8417-4d97-b4aa-d8c66f5c4e3b)
![cdda3](https://github.com/CleverRaven/Cataclysm-DDA/assets/170238849/fffc1012-fe6a-4317-adf8-0cabeb54f2e9)

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15369149/debug.log)

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15369151/crash.log)

**Comment by PGR-14** [comment]
Did you use any items that cast spells? Like the structural imager or wands?

**Comment by cddaplaya** [comment]
No, ive picked up a couple wands but hadnt used :(

**Comment by PGR-14** [comment]
Did you drink any potions then? This seems related to https://github.com/CleverRaven/Cataclysm-DDA/pull/73800 especially w/ the UI bugs (No Description, No Name) & the error reports.

**Comment by cddaplaya** [comment]
Does seem the same, i hadnt drunk any potions either, i vaguely remember it starting when i opened up either the supernatural or bionic powers menu and hit a hotkey that didnt have a corresponding power giving me an error saying something along the lines of no spell reference for that hotkey, then next time i opened supernatural tab there was the blank spell but ive tried to replicate that and nothing happens

**Comment by PGR-14** [comment]
There's a fix in the works: https://github.com/CleverRaven/Cataclysm-DDA/pull/73800 Hopefully this helps.

**Comment by cddaplaya** [comment]
> There's a fix in the works: #73800 Hopefully this helps.

Updated game hopefully it prevents it from happening again, the existing spell/errors are still present however so I'm wondering if it possible for me to delete the "spell" somehow, am new to commenting on here so guessing this might not be the right place to ask

**Comment by PGR-14** [comment]
It's alright. If you go into debug mode, then you can delete it (Debug - Player - Spells), but I've heard reports of it crashing your game.

**Comment by cddaplaya** [comment]
Yup, trying to enter debug > player > spells crashes it everytime, do you know if there is a file I can edit manually?

**Comment by PGR-14** [comment]
Not sure, you could look into your saves & edit from there, but that has a large chance of breaking it.

**Comment by cddaplaya** [comment]
my issues are all fixed now with latest update <3<3 absolute legends!!
