### ISSUE TITLE
Remaining 0.H backports

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#73923]
### Is your feature request related to a problem? Please describe.

So I'm pretty much done with the labelled backports, there's 3 labelled backport candidates left without backport PRs.
#72703: #70359 heavily messed with relevant code and if I only port the bits of it I deem necessary I'm concerned I'll break stuff, at the same time osuphobia has pointed out that that PR causes regression so porting it back into order to port a bugfix seems a bit backwards. #70359 in its entirety does backport and compile fine tho if that's preferred. Edit: Just backporting #70359 in its entirety
#70721: This PR has bad migration, needs extra handling for incorrect recipes and should be enabled by default for existing saves updating to it which we don't have infra for afaik. #71387 also causes problems bc it changes all the prosthetic ids to make the migration not break the mod but my concern is not backporting any of this will cause migration issues for 0.I if the mod is remerged into vanilla before then. Edit: Decided not to backport
#71823: I'm waiting until after all other backports to do this one bc it has lots of conflicts and would be easier just to replicate the PR instead.

This isn't to say that's all the remaining backports, I'm going to look through the blockers to check all relevant PRs are being backported (Edit: found 20 blocker solver PRs that weren't labelled for some reason), as well as the pinned stable issue (Edit: backporting the only mentioned PR) and the two dev discord channels for any relevant PRs that have been missed for labelling. I also need to do the substantial MoM backports #73842.

### Solution you would like.

I need solutions to the above two problems backport candidates from senior devs.
If there's any PRs anyone thinks should be being backported that haven't been please comment them here. Notably I've backported very few mod PRs and am quite happy to, EoC/math/shim updates since the 0.H split mean just backporting the current versions of mods to 0.H isn't doable for the most part.
#70661 has a section on what is sensible to be considered for backporting, with any PRs *merged* after the split on  January 4th 8pm not making it.

### Describe alternatives you have considered.

Just unlabelling the problem candidates and pretending they don't exist and that I'm done

### Additional context

**Comment by RenechCDDA** [comment]
70721 shouldn't need extra save handling, since the limb stuff was only present in the experimental void between 0.G and 0.H.

**Comment by Procyonae** [comment]
Just because we only require stable -> stable compatibility doesn't mean we should go out of the way to break exp -> stable compatibility

**Comment by Hyperseeker** [comment]
Would it be possible to backport changes to magazine sizes, from the PRs mentioned in #70784?

According to the guideline:
> **Fixes/adjustments to existing content should be audited carefully.** <..> Balance changes, such as adjusting item weights or spawn chances etc, is more likely to be fine as long as it's well vetted.

I'm not positive on what "well vetted" means in this context, but both @ANickelN and I have done a lot of work making sure the changes are as accurate as possible.

There's also #73451, which is a fix on the magazine-size PRs, but it adjusts the name of a magazine, which makes it a translation-string change.

**Comment by inogenous** [comment]
> If there's any PRs anyone thinks should be being backported that haven't been please comment them here.

Maybe #70780 even though it does not have the backport tag? Thanks.

**Comment by Procyonae** [comment]
> Maybe #70780 even though it does not have the backport tag? Thanks.

I'm explicitly asking for things that haven't been tagged ye

**Comment by Venera3** [comment]
Re: prosthetic handling the way the current system is set up is not expandable and will need a thorough redesign from the ground up, meaning whenever stumping makes it back into vanilla they will be entirely different. 

Don't lose too much sleep thinking about compatibility for them.

**Comment by Standing-Storm** [comment]
I realized that the MoM backports for Vitakinesis rely on a flag introduced in #70648 that just barely didn't make the 0.H cutoff (the `BLEEDSLOW` and `BLEEDSLOW2` flags), so I'd like to recommend that one for backporting.

**Comment by SkuliAdams** [comment]
#73313 should probably be backported, as it fixes issue #71661 which seems to exist in the latest 0.H candidate.

**Comment by Procyonae** [comment]
Closing bc none of this is remotely relevant anymore and 0.H is pretty much done
