### ISSUE TITLE
Batch-crafting should not receive penalty for cumbersome crafting when single craft doesn`t have the penalty.

### ISSUE THREAD

**Issue by Void-Seeker** [CleverRaven/Cataclysm-DDA#73936]
### Is your feature request related to a problem? Please describe.

Let's say, we are crafting planks from logs using table saw. When we schedule single craft, it finishes fast and without penalties. But if we batch 20 crafts, crafting speed goes to nothing, and we have messages `The in progress plank is too large and/or heavy to work on comfortably. You are working slowly.` That really makes a little sense, as batch crafting in this case is supposed to craft items in series, and if single craft is fine, why batch gets the penalty?

### Solution you would like.

Batch-crafting should not receive penalty for cumbersome crafting when single craft doesn`t have the penalty.

### Describe alternatives you have considered.

I can just spam "Recraft last recipe" key, I suppose...

**Comment by PatrikLundell** [comment]
Well, there are different flavors of batch crafting. While plank crafting is sequential, several other kinds just result in more ingredients being used (many kinds of food production, for example: make more soup in a single go).

**Comment by natsirt721** [comment]
There's already a batch crafting speed bonus - that should be able to account for 'many serial' vs 'batch parallelizable'. What is the rationale behind the 'craft too big' speed penalty??

**Comment by PatrikLundell** [comment]
I don't think there's been a decision to make large batches bulky, but rather a result of the bulky item code not having any code to treat batches differently from single crafts.

I don't think the calculation of bulky item is static, but rather depending on a bunch of factors, such as whether you're trying to handle the craft in your hands or on a surface of various qualities, and might also include character strength. Note that these are guesses, as I haven't looked at the code.
