### ISSUE TITLE
Be able to talk to monsters that are capable of talking.

### ISSUE THREAD

**Issue by Nuc-621** [CleverRaven/Cataclysm-DDA#73938]
### Is your feature request related to a problem? Please describe.

After playing experimental, I found an interesting feature where you could talk to monster-types humans (gawky guardian, panicked person, etc.), and i would like this mechanic to be applied to other monsters that also have human speech.

### Solution you would like.

Be able to talk to monsters with speech like: experimental mutant, cunning feral, etc, but the most of the convos are like the one's with the non-npc humans.

**Comment by PGR-14** [comment]
Well, maybe not the cunning feral, as most ferals are incapable of speech (See lore docs) (But then again they're outdated & I think talking ferals would be cool (Also, by talking, not like conversations, more like unnerving laugher, words, & phrases)), but I'd like for more talkative monsters, even if they can't explicitly talk (I.E. hand motions). Perhaps you can convince Overconfident Officers & Futile Fighters to calm down a bit.

**Comment by Standing-Storm** [comment]
I've thought about letting you read ferals' minds in Mind Over Matter for flavor reasons, but one disadvantage of this that stops me from doing it, and might also be a disadvantage here, is that if you open the chat window to give orders to NPCs, you would have to scroll through 

> feral human
> feral human
> feral human
> feral human
> feral human
> feral human
> feral human
> feral human

...etc to select your NPCs if any ferals or other talkable monsters are nearby.

**Comment by PGR-14** [comment]
It usually isn't too much of a problem (At least in my experience) 'cause it's usually sorted by proximity.

**Comment by ADekema** [comment]
Some ferals are clearly more intelligent than others. Some cunning feral might be capable of speech. There is also the mad scientist, feral cop and feral officer that are described as muttering so they should be capable of speech. Crazed survivalist and mad militia might also be a good choice as they still have enough common sence to run away from you when harmed so a survivor with enough speech skill pointing a gun at them might convince them too turn the other way.
