### ISSUE TITLE
Charging outlet/one-way power transfer device.

### ISSUE THREAD

**Issue by Void-Seeker** [CleverRaven/Cataclysm-DDA#73943]
### Is your feature request related to a problem? Please describe.

Let's say, I have a base with power generation capabilities and power storage (lots of solar panel arrays/wind turbines/RTGs), and an electric vehicle. If i just connect them with a power cord, battery charge is going to be equally distributed, which means electric vehicle can only be fully charged when base batteries are fully charged. Otherwise, it can even drain power from vehicle batteries to charge base batteries. But what if i need vehicle to be fully charged even when my base is not at the full capacity?

### Solution you would like.

Some kind of construction or device that allows vehicle charging and/or one-way power transfer to another section of the base. Like charging outlet, that allows cable connection that will only allow one-way power transfer. Or new kind of cable with similar functions.

**Comment by IdleSol** [comment]
I solved this problem by building a second vehicle to stand and charge the batteries.

The second solution, was to build a transport on the base, consisting of battery boxes and large batteries (or very large if you use them). Solar panels, wind turbines, and base consumers were connected to it. It held an average of 90+% charge. When I needed to, I just swapped the batteries around.

I think I'll be corrected, but as far as I understand it, electricity is directionless right now. So it's impossible to create a device that will transfer power in one direction.

Translated with DeepL.com (free version)

**Comment by PatrikLundell** [comment]
Recharging boxes are uni directional and can hold a number of storage batteries (that take a long time to recharge), so a workaround using existing functionality is to build a lot of these boxes and swap batteries on your vehicles.
It seems that's the way the C:DDA timeline evolved, rather than the charging station one the real world uses.

However, charging stations would definitely be useful.

**Comment by harakka** [comment]
> It seems that's the way the C:DDA timeline evolved, rather than the charging station one the real world uses.

No, it's just the way people implemented gameplay systems.

**Comment by Brambor** [comment]
This could be cool. It would allow to prioritize power.

For example, have a little grid with fridge and battery. This grid would be recharged by the main grid.

This is implemented in Astroneer, these chargers are called extenders there:
https://www.reddit.com/r/Astroneer/comments/o4xghm/extenders_splitters_and_directional_power/

**Comment by natsirt721** [comment]
This would effectively be a voltage regulator; that is, a component that produces a constant output voltage regardless of the input voltage, and modulates output power via current. Set the voltage high enough to charge the battery and you're golden - the output voltage is high enough that some current is always flowing to it regardless of the upstream voltage. These circuits are ubiquitous for applications where charging a battery is required, but the input power (current * voltage) varies over a known range. However, AFAIK the modern (can't say 'current' hah!) implementation of the electrical grid doesn't allow for such nuance, and the solution might be quite a bit trickier than expected.
