### ISSUE TITLE
Change nested recipes colour to something readable

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73949]
### Describe the bug

I just custom-changed it to this:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/9a520be5-3712-40b8-8e1b-8c465aa0afe7)

From the current default which is this:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/b99eeab5-944d-4143-95df-809e8784c309)
The above is super hard to read for me. I literally have to lean in to the monitor to like 20 cm. Sometimes I just give up and hope the text isn't important.

### Attach save file

N/A

### Steps to reproduce

1. Make sure you have the default colour in main menu > settings > colors
1. Open crafting menu

### Expected behavior

Text is readable by default without changing to custom colours.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9614-gf522d7df2d-dirty [64-bit] - master was 39e2afa80d
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment]
Related: #62501

**Comment by Brambor** [comment]
You are right, that is the same. Closing as duplicate.
