### ISSUE TITLE
[Sky Island] Crafting Alpha Secure Container on second character of same preset and name in world don't give container

### ISSUE THREAD

**Issue by Klamener** [CleverRaven/Cataclysm-DDA#73959]
### Describe the bug

When crafting Alpha Secure Container on a second character in the world (first one took mission for alpha secure container but was deleted after that), created from the same preset and with same name as first one, with only start date changed, game throws errors and double-completes mission, but gives nothing to second character.

### Attach save file

[Mackenzie-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15377431/Mackenzie-trimmed.tar.gz)

### Steps to reproduce

1.Load a save
2.Try crafting Alpha Secure Container

### Expected behavior

It should give me an Alpha Secure Container, attached to my body

### Screenshots

![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/167684677/9f3418e0-b4a6-4ddf-905d-0a581d1dec6c)
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/167684677/9c0d6db7-6020-4097-917e-8be6715f3d32)
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/167684677/69d5e341-a4fd-4b00-b2f3-6bf7bdf32028)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19042.1348 (20H2)
- Game Version: b9293eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    <color_light_green>Cataclysm++</color> [Cata++],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Armored Wheel Offroad [armored_wheel_offroad],
    Healthy Foods [healthy_foods],
    Mind Over Matter [mindovermatter],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Culinary Days Ahead [culinary_days_ahead],
    Pixel's Various Fuckery [Pix's Shit],
    World on Fire [World_on_fire],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/DinoMod Patchmod [Arcana_Dinomod_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Magiclysm Revamp and Additions [magicrevamp],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Magyclism Simplified [magyclism_simplified],
    Blazemod - Vehicle Additions Pack [blazemod],
    Crazy Cataclysm [crazy_cataclysm],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Sky Island [skyisland]
]

**Comment by Klamener** [comment]
After testing on save with minimal mods, turned out that creating a character, taking all missions, creating a second charater from same preset as first and crafting a container is enough to reproduce.

[Test World1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15377744/Test.World1-trimmed.tar.gz)

**Comment by Standing-Storm** [comment]
This is because the variables tracking your progress are all global variables, not character-specific, so when a second character in the same world checks the variable it's set to the "complete" state.
