### ISSUE TITLE
Butchery crash

### ISSUE THREAD

**Issue by 5ENP4I** [CleverRaven/Cataclysm-DDA#73978]
### Describe the bug

butchering 2nd corpse crashes the game. Corpses were obtained via hunting option in faction camp

### Attach save file

[OChallangeVanilla-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15380902/OChallangeVanilla-trimmed.tar.gz)

### Steps to reproduce

1. butcher one corpse placed on the table (full butchery).
2. butcher the second corpse near in the same way (here must appear a crash window)

### Expected behavior

I expect the second corpse to be butchered in a similar way as the first one.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: 140db31 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/15380989/crash.zip)

**Comment by ehughsbaird** [comment]
Result of https://github.com/CleverRaven/Cataclysm-DDA/pull/73610

On line 480 in activity_handlers (butcher_do_turn), it assumes that item location is valid, which is not a guarantee (the finish function says so).
A check needs to be added to ensure that is true.

**Comment by 5ENP4I** [comment]
Yes, that's helped, thanks a lot

**Comment by Brambor** [comment]
Note: Despite the fact that a workaround exists, this still is a valid issue. The game mustn't crash.

Opening it doesn't do anything really, but I wanna use my power ;)
