### ISSUE TITLE
Folding solar panel throws error on deployment and duplicates* on disassembly.

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73976]
### Describe the bug

Deploy `folding solar panel` get this:
```
 DEBUG    : new base 'folding_solar_panel' doesn't match part type 'ap_folding_solar_panel', this is a bug

 FUNCTION : set_base
 FILE     : C:\GitHub\Cataclysm-DDA\src\vehicle_part.cpp
 LINE     : 106
 VERSION  : 0.G-9614-gf522d7df2d-dirty
```

Take it down, you get these:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/448a6308-1a63-4e8c-bf91-d59b813a2c9c)

Place them down. The `folding solar panel` throws an error again and the cycle repeats.

The other thing is a bonus solar panel, that works as expected, except that it has an internal battery of 1kJ and it is spawned by taking down the deployed folding solar panel.

### Attach save file

[Paradise-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15379015/Paradise-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save.
2. The rest is in the bug description.

### Expected behavior

No duplication.

No errors on deployment.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9614-gf522d7df2d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I bet this is reported already and I just couldn't find it.

**Comment by Void-Seeker** [comment]
Can confirm, happened for me too.

**Comment by TheMurderUnicorn** [comment]
Yeah, I tested this when you (or whoever) brought it up on discord, I was able to duplicate it but couldn't figure out how to fix it with my limited knowledge.

**Comment by Brambor** [comment]
Agreed.

Yay! The Immersion break is fixed!
