### ISSUE TITLE
[Magiclysm] The "Bleed" spell does not provide exp for "Stats Through Kills"

### ISSUE THREAD

**Issue by L1keThat** [CleverRaven/Cataclysm-DDA#73977]
### Describe the bug

No additional description is required, it seems to me.

### Attach save file

[Test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15379908/Test-trimmed.tar.gz)

### Steps to reproduce

1. Learn the bleed spell (Animist)
2. Kill the enemy with it.
3. Not to gain experience.

### Expected behavior

If you kill an enemy with ordinary bleeding, experience is given.
I would like to be able to gain experience for Stats Through Kills by bleeding from the "bleed" spell.

### Screenshots

![fsaff43](https://github.com/CleverRaven/Cataclysm-DDA/assets/169724547/a2734117-3ef4-44ad-8935-6dbbbf656298)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: b9293eb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded:
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]

**Comment by RenechCDDA** [comment]
Likely dupe of #71408
