### ISSUE TITLE
Load error on skin tone assignment to NPC

### ISSUE THREAD

**Issue by kirkpham** [CleverRaven/Cataclysm-DDA#74012]
### Describe the bug

 DEBUG    : invalid trait id "SKIN_ROSE"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mutation_branch]
 FILE     : src/generic_factory.h
 LINE     : 482
 VERSION  : cdda-experimental-2024-05-21-1724 8e6eac5

The game soft crashes when I load the Lisa or Jesse Isherwood NPC for the first time in the Isherwood farm. Doesn't appear to be skippable with spacebar, but can be ignored with "I".

### Attach save file

[Provo Catalcysm-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15408485/Provo.Catalcysm-trimmed.tar.gz)

### Steps to reproduce

Take a few steps to the left in the game file to trigger proximity loading of offending NPC.

### Expected behavior

NPC should load with skin tone - my amateur guess is it's a variable mismatch (maybe skin tone naming convention changed?) as these are hardcoded NPCs from what I gathered; if she can't load with rose skin, possibly default to something else.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-22-0335 5b4b49b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by TealcOneill** [comment]
/Confirm
- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-25-0134 22d851b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
