### ISSUE TITLE
under barrel grenade launcher in generic guns mod not working properly

### ISSUE THREAD

**Issue by IndignantBastard** [CleverRaven/Cataclysm-DDA#74016]
### Describe the bug

launcher firing before finishing aiming and not getting farther than 3 squares.

### Attach save file

[try again_copy_copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15410750/try.again_copy_copy-trimmed.tar.gz)

### Steps to reproduce

1. load launcher 
2. fire launcher
3. die

### Expected behavior

the launcher fires and lands at least at mid distance between me and the target do to having lvl 2 in launchers.

### Screenshots

![Screenshot 2024-05-22 221037](https://github.com/CleverRaven/Cataclysm-DDA/assets/170587714/7a824a17-64a4-42ee-bf67-3846bfab5ec2)
![Screenshot 2024-05-22 221013](https://github.com/CleverRaven/Cataclysm-DDA/assets/170587714/a792cd1a-7a05-4113-923e-743a64177b0d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: 0.G Stable STEAM [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Generic Guns [generic_guns],
    Megafauna [megafauna],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]

**Comment by harakka** [comment]
Can you try reproducing this with latest experimental?

**Comment by IndignantBastard** [comment]
> Can you try reproducing this with latest experimental?

reproduced in experimental and set up save for testing.

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15418258/test-trimmed.tar.gz)
