### ISSUE TITLE
Belts and suspender/vest compatability, and other musings

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#74026]
### Is your feature request related to a problem? Please describe.

While looking at the belt occupying items, its always bugged me that suspenders don't have a reasonable use to them, save for the holster suspenders. They don't have Fancy, nor are they used in conjunction with other items. This leaves 3 items in the crafting menu that really have no basic use.

### Solution you would like.

Suspenders should be used as a way to lessen the encumberance for belts carrying items and containers, most likely as a seperate item of [specific kind of belt here] and suspenders, to mimic the way suspenders add a additional point of contact with your body, distributing the load partially off your hips, and onto your shoulders! This would add a reason to craft a pair of suspenders for use, especially for some of the more higher encumbering options (such as the police belt and the longsword scabbard, and the molle and standard leather belts!

_And to fully complete the psuedo Vietnam era USGI / Naked Snake larp but we wont dwell on that _

### Describe alternatives you have considered.

this could arguably be applied when a proper weight distribution mechanic comes into cdda, but this should do for now. Other Notes:

1. Perhaps the molle belt should use diff suspenders than (or even have a additional version) the regular belts, maybe with additional functionality for waist/butt packs? or even be able to be coupled up with the standalone preconfigured tac vest (i see a belt loop all across the bottom of it, indicating it could be worn together as a single piece, so idk maybe it should be less belt with vest and more vest with belt)? I think regular leather belts (western gunbelt, leather belt, tool belt, and longsword scabbard)

2. Maybe this could also be coupled alongside a update to belts regarding containers with BELT_CLIP? I find it kinda silly that basic pouches cant be clipped onto or otherwise tied onto a belt.... because reasons? 

3. I dont know how the coverage for this could be handled either, i think that suspenders shouldn't really conflict with a vest, but im not really experienced with this. Any relevant experience and advice is _much_ appreciated!

### Additional context

![snake_big_boss_mgs3_render_by_hexeno_d2fm0zj-fullview](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/e999b157-c204-4c06-9e1f-54482beb6975)

![usmc-black-combat-vest-with-belt](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/4e997d06-1341-4c3c-883b-42c6b3c6e5ed)
(Notice the belt running through the bottom, though idk if it would be able to be used to its fullest extent for stuff like batons/maces/whatever belt_clip weapons you have)

**Comment by Hyperseeker** [comment]
One way to handle suspenders would be to allow them to be worn "inside" the belt, with a -1 encumbrance value. I'm not positive whether than would work, but apparently, items with negative encumbrance reduce it when "worn", whatever that really means.

I'm not aware of MOLLE pouches being worn on non-PALS belts. It seems reasonable that they could be, but you have to consider that MOLLE straps on pouches would probably be too loose for non-sectioned belts, and thus would make the pouches rattle and move around, increasing their encumbrance. PALS webbing mitigates this by strictly regimenting its slots in a way that makes pouches sit as tightly as possible within the slots they occupy.

The prototype for the tac vest does indeed have a set of belt loops for a belt to be worn in, to a point where I'd initially assumed that the belt is part of the vest while modelling it for [Armory](https://github.com/FrontierMods/Armory). However, it is not integral to the vest, and the vest is generally sold without it. Mechanically, those loops probably act in the same way as belt straps do for leg-strapped holsters and such: as anchoring support.

In-game, this doesn't mean much. If we could change something about one item if another item is worn with it, that would be swell, but that's not the case right now. Leg-strapped holsters *could* reduce their encumbrance when worn with a waist belt the can strap to, but only in theory. The same would apply to this vest.

What Snake is wearing in that image looks to me like the harness pilots wear in the US Air Force:

![US Air Force pilot wearing a full set of equipment](https://www.salimbeti.com/aviation/images/equip/completousaf.jpg)

Notice a lack of belt, and an array of different torso equipment (as well as a different way for the harness to wrap around the torso before concluding at the crotch).

Beyond that, I would say that a lot more items could be worn on belts. Belt pouches issued to the police are but one example: pouches for magazines, handcuffs, Narcan, air horns (for mall security), collapsible batons... — as well as PR-24-style baton rings and rings for flashlights. Then you have belt-mounted holsters and sheaths, and that's a world of its own. Those should all probably be included or adapted for use with belts and suspenders.

**Comment by fairyarmadillo** [comment]
There are already harnesses and rigging in the game which do what you are describing. A pair of suspenders to hold up your dress slacks are not going to have any effect on the Hanzo steel you've strapped to your belt.

**Comment by Kantonine** [comment]
> There are already harnesses and rigging in the game which do what you are describing. A pair of suspenders to hold up your dress slacks are not going to have any effect on the Hanzo steel you've strapped to your belt.

Fair point! The scabbard was a bit more of a reach with this one, as so much of the encumberance is just from how intrusive to daily living scabbards are, and can be reasonably disallowed.

> I'm not aware of MOLLE pouches being worn on non-PALS belts. It seems reasonable that they could be, but you have to consider that MOLLE straps on pouches would probably be too loose for non-sectioned belts, and thus would make the pouches rattle and move around, increasing their encumbrance. 

Thats a very true statement, maybe this should be a feature relegated to leather PALS pouches along with slightly more encumberance than molle attachment? Keeps the proper pouches in their top dog position, and gives another reason to make up leather versions of existing pouches.

> What Snake is wearing in that image looks to me like the harness pilots wear in the US Air Force:

Another fair point actually, realized after the fact thats not really applicable, as thats a STABO rig, not the actual alice suspenders made for the belt. when it comes to molle compatible suspenders, i _do_ see:

![unnamed](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/616fcc97-c86a-4c32-b445-7c76a2c3a4ac)
very barebones suspenders.

and

![s-l1200](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/b22d5d0e-40e0-4867-97ca-2e8b2dda1b1c)
more bulky h-harness designs

**Comment by Kantonine** [comment]
> So, the answer to "Maybe this is how we make leather pouches meaningfully useful?" is "We should probably add belt-mounted pouches, instead". Leather MOLLE pouches sounds like a survivalist take on modern modular tactical gear. Which is to say: a valid approach in a survival situation, but odds are, you'll probably find enough of them lying around before you find yourself having to resort to hand-crafting your own.

Great point! it is definitely an oddity, especially when stuff like the shoulder holster and the western gun belt got axed off of the PALS accesory list (I still cry over it) but other leather pouches havent been touched. If at the very least, I might have a go through, and possibly make the leather pouches you can make belt attachable.

> The question is: will you be able to find this IRL? And if not, but you're aware of the idea, would this be something you'd be making as a means to your own survival?

I'd say you could find them at any milsurp store, and some people do swear by it as a alternative (Possible hipster paramilitary zombie wearing suspenders+ belt instead of a plate carrier) As for hand crafting, it would definitely fit into the realm of also being able to make the load bearing vests from scratch (though, this might change, how many people in their average playthrough spend the unironic days neccesary to make a lbv if it isnt for a challenge run)

> To reiterate: I don't think MOLLE is the way to go for this. I think your best bet would be implementing belt pouches and allowing suspenders (or at least suspenders that can hold some weight) to "take in" these pouches. This would require more research to determine whether that's an effective way to carry stuff, but between that and something as fancy as "MOLLE-compatible suspenders", my choice is clear. 

Thanks for the input!

> (Even though I recognize how freakin' cool the idea sounds.)

Lol you get the memo

![b51f4502b713847d997f369167e5cb47c3343b14926bd6f2443b9a04541e082b_1](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/d0c94993-a741-4410-a050-40b36a36e6f4)
