### ISSUE TITLE
Dynamic Faction Epilogues

### ISSUE THREAD

**Issue by GalacticApple** [CleverRaven/Cataclysm-DDA#74032]
### Is your feature request related to a problem? Please describe.

Right now, it seems like the endings for the factions are solely determined by the faction's "power". I think it makes sense that for a number of these, the success (or failure) of other factions should lead to them having a unique epilogue snippet(s). 

### Solution you would like.

I think the main factions this could impact are Hub-01, the Tacoma Commune and the Old Guard. Right now, the best ending for them is for when they have 150 power. However, these come off as more "middling" than "good", so I'll refer to them as "neutral" below.

---
Old Guard: 
The "neutral" ending for the Old Guard has them forced to consolidate their resources to a few large bases with the remains of the rest being handed off to the "few" remaining survivors. If the Hub-01 gets their "dynamic good" ending (below) and the Tacoma Commune doesn't get their "bad" ending (so instead the settlement survives and grows), then the Old Guard would get its own "dynamic good" ending. Helping the smaller factions to get their better endings could also factor into this new ending. 

Example good ending: "The steadfastness of individual survivors after the Cataclysm impressed the tattered remains of the once glorious union.  Spurred on by numerous strategic successes, a number of operations to re-secure facilities succeeded thanks to the support of various surviving communities. While some remained cautious of submitting themselves to the Old Guard's authority, nostalgia for the old world and the promise of security from the new rallied many more to their flag. In the coming decades, the Old Guard were able to reconnect much of New England and beyond, their dreams for the future buoyed by the memory of the past." 

---
Hub-01: 
The "neutral" ending you can currently get for Hub-01 is a few years of prosperity before a lack of advanced resources and personnel eventually leads to the collapse of Melchior and the site in general. However, the Exodii form connections to many other communities and become a haven of industry in their good end, while the Great Library becomes a haven for knowledge and learning in theirs. So, the idea could be that if you get the "best" endings for both the Exodii *and* the Great Library, Hub-01 is able to develop the connections needed to maintain itself and expand for years to come.  

Example good ending: "Melchior's enlightened leadership, backed-up with the muscle of numerous mercenary survivors, allowed Hub-01 to flourish on its' own for a time. However, while the staff of Hub-01 preferred to ignore the people of the region, the looming shortages of advanced resources and personnel forced them to begin opening up to their neighbors for help. Fortunately, the knowledge and resources they were able to source from the Exodii, and the influx of fresh recruits from organizations like the Great Library, ensured that the Hub would continue to thrive for the foreseeable future. While the researchers of the Hub would restrain themselves (or be restrained by Melchior) from engaging in the worst excesses of XEDRA, they continued to explore new ways to survive, and perhaps one day even overcome, the horrors besieging the Earth. Bionics and mutagens, reality anchors and molecular printing, the future was truly in their hands."

An additional snippet can be inserted after the above in the event that the Old Guard gets their "dynamic good" ending. As an example: "While still technically being employees (or property, in Melchior's case) of the federal government, the staff of Hub-01 were initially very reluctant to have anything to do with the Old Guard. However, the connections and resources of the Old Guard gave them significant leverage in negotiations between the two factions. After much debate, Hub-01 would eventually vote to rejoin the government in exchange for its' support of the Hub's research, as well as for the legal recognition of Melchior as a fully sentient citizen."

---
Tacoma Commune: 
In their "neutral" ending, the Commune survives and grows, but remains loyal to the Free Merchants and is dependent on the labor of desperate and overworked survivors. If, however, the Free Merchants were to collapse (so, they get their "bad" ending), the laborers of the Commune might overthrow the remaining Free Merchants, turning the settlement into a proper "commune."

Example good ending: "Through the years, the commune would continue to rapidly grow despite constant external threats. In a surprising twist then, the greatest threat would turn out to be an internal one. The collapse of the Free Merchant traders plunged the Commune's leadership into a period of significant infighting, and seeing an opportunity, the survivors of the Commune quickly moved to oust them. Afterwards, the settlement was re-organized under a democratically elected council and the resources of Tacoma were distributed by need and popular vote. The Commune would soon earn a reputation as a place where the struggles of the wasteland were shared, and where the horrors of the world were faced together."

Additional snippets can be inserted after this if the Old Guard get their "dynamic good" ending, and depending on whether the Free Merchants remain in charge or not.

If the Free Merchants remain in charge: "When the Old Guard came for their support, the Commune's leadership was happy to accept, though not without conditions. Lucrative contracts and the exclusive rights to inter-settlement trade routes made the Free Merchants virtual merchant royalty overnight. While many survivors would grumble, none could deny that wherever the Old Guard went, the Free Merchants would bring their prosperity with them, for a price of course."

If the Free Merchants are overthrown: "When the Old Guard came for their support, the citizens of the Commune were extremely resistant to surrendering their autonomy to this "new" power. However, the Old Guard, desperate to find footholds in the region, proved more amicable to their demands than they expected. In exchange for representation in the Provisional Congress on Nantucket island, and the Old Guard's support in organizing other settlements like Tacoma in their territory, the Tacoma Commune would surprise many by voting to join the new union. When asked for a comment on the vote, the First Speaker of the Tacoma Council simply said, "out of many, one." "

---
I think another faction that could have a new epilogue snippet in the event of an Old Guard "dynamic good" ending is the Isherwood's Farm. Perhaps there could be variations depending on who controls Tacoma.

If the Free Merchant's are in charge: "After they shot an Old Guard envoy to the farm, a bounty was placed on the Isherwood family. With the Isherwoods forced from their home, the farm was quickly purchased by the Free Merchants and converted into a very profitable plantation." 

If the Free Merchant's were overthrown: "After they shot an Old Guard envoy to the farm, a bounty was placed on the Isherwood family. After the father pleaded guilty to killing the man, the remaining Isherwoods were allowed to return to their farm, albeit with planners from Tacoma looking to oversee future settlements at the site."

---
Last thing, but here's an ending where the Hell's Raiders collapse due to the Old Guard getting their "dynamic good" ending:

"With the survivors of the wasteland becoming more organized by the day, the Hell's Raiders found it more and more difficult to find easy prey to loot and pillage. Before long, the once feared raiders found themselves on the defensive as the resurgent Old Guard began to assault their outposts and dismantle their hierarchy of command. Those that weren't killed were forced to flee into the untamed west, the memory of their terror slowly fading like a bad dream."

**Comment by Maleclypse** [comment]
Fixed by #74126
