### ISSUE TITLE
Cramped space. Incorrect volume calculation?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#74068]
### Describe the bug

Standard character. Completely naked. Sits in a normal car and gets this effect.

It should not be like this. My assumption is that the calculation of character volume or free space is not done correctly.

### Attach save file

[Бивис-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15442114/-trimmed.tar.gz)

### Steps to reproduce

Create a character and get in the car.

### Expected behavior

Lack of effect, for a normal character on a normal car.

### Screenshots

![pict 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/fb68b92b-2f43-4b82-b942-712d4d0320a1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-25-0347 388ca6c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Additionally looked at how this effect would react to starvation. Set it to 15k cal (skeletal). The effect didn't go anywhere.

**Comment by IdleSol** [comment]
Some tests are.
1. Create a vehicle (1 frame). No effect
2. Add a seat or trunk. There is an effect.

**Comment by TealcOneill** [comment]
/Confirm
Seems like it was caused by #74046. Didn't have this issue in a couple day old version of the game.
- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-05-25-0134 22d851b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Maddremor** [comment]
I can personally confirm this is the case on a vanilla save, unremarkable character, on a build just a few hours old. This might be an issue of the messaging towards the player ("You barely fit in this tiny human vehicle" should never trigger for a regular person), the calculations of what the threshold for being cramped is, and finally what the cramped debuff should entail. Calling @RenechCDDA for this.

**Comment by IdleSol** [comment]
Small question. A aisle can store 100L of stuff. Is this a bug that needs to be reported, or should it be?

And yes, it is also considered a cramped space.

**Comment by Brroleg** [comment]
I tested every last experimental build. This bug appeared after version 2024-05-23-1642. On said version and before there is no such bug

**Comment by mischief** [comment]
i believe it's https://github.com/CleverRaven/Cataclysm-DDA/pull/74004 causing this.

**Comment by winsomniak** [comment]
Tiles which do not have storage capacity seem not to be affected by this bug.

For example, using a "flimsy wooden seat" does not result in the debuff and allows driving a vehicle without a debuff as a workaround.

**Comment by kainvastro** [comment]
test
