### ISSUE TITLE
The `CARGO_PASSABLE` flag is not present in the documentation

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#74069]
### Describe the bug

The `CARGO_PASSABLE` flag is not present in the documentation.

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

n/a

**Comment by TealcOneill** [comment]
/Confirm
Searched using githubs code search option and found it in use and where it's coded in but not in any of the doc files.
