### ISSUE TITLE
The generated vehicle does not come equipped with a swappable storage battery case.

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#74109]
### Is your feature request related to a problem? Please describe.

When I try to remove the 'swappable large storage battery' from other vehicles and install it in mine, it prompts me that I need a 'swappable storage battery case,' but such a component is not found on the original vehicles.

### Solution you would like.

Generate a swappable storage battery case upon vehicle spawn.

**Comment by irwiss** [comment]
you can install a "large storage battery" without it, the case is only needed if you want quickly swappable

**Comment by IoIqq** [comment]
> you can install a "large storage battery" without it, the case is only needed if you want quickly swappable

However, I have never encountered a swappable storage battery case in vehicle generation, which seems unreasonable. Many vehicles have multiple batteries, so there should be a probability of generating a swappable storage battery case.

**Comment by 5ENP4I** [comment]
@IoIqq the item you are looking for is "storage battery case" -> https://cdda-guide.nornagon.net/item/it_battery_mount

**Comment by irwiss** [comment]
It exists on several vehicles and it's craftable at fab 4 https://cdda-guide.nornagon.net/vehicle_part/storage_battery_mount

**Comment by IoIqq** [comment]
> 它存在于几辆车上，并且可以在 4 https://cdda-guide.nornagon.net/vehicle_part/storage_battery_mount

But I have never seen it in many electric-powered vehicles.

**Comment by 5ENP4I** [comment]
The vehicle detail and the item which is required to install that detail is often named different. Upon removing or placing car detail, you are informed which item you need to have/you get upon removing vehicle part.
