### ISSUE TITLE
Heating up with hotplate 

### ISSUE THREAD

**Issue by 5ENP4I** [CleverRaven/Cataclysm-DDA#74107]
### Describe the bug

While I try to heat up something (pemmican) with hotplate, connected to car, I am receiving segfault.

### Attach save file

[OChallangeVanilla-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15447274/OChallangeVanilla-trimmed.tar.gz)

### Steps to reproduce

1. Examine nearest car kitchen block.
2. Use hotplate to heat something up.
3. Chose pemmican from a freezer nearby. (Afaik someone did or asked for batch heat up, but i don't see the option. I had game updated so idk if its the problem)
4. here should appear segfault.

### Expected behavior

Expect the game to heat up one piece of pemmican (or if batch heat up was added, i could heat up more pemmican chunks at once) 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: b03cb4b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/15447303/crash.zip)

**Comment by 5ENP4I** [comment]
Maybe the same issue was described in #73657 two weeks earlier.

**Comment by GuardianDll** [comment]
Fixed by #74313
