### ISSUE TITLE
Character Point Pool Balance

### ISSUE THREAD

**Issue by Name1essLord** [CleverRaven/Cataclysm-DDA#74125]
### Is your feature request related to a problem? Please describe.

I decided to tell this because the character's points are not balanced so far, I ask you to balance them.

### Solution you would like.

I'm asking you to balance your character's points because this is a pretty important part for fair play in Cataclysm DDA, and they're still not balanced!!

**Comment by NetSysFire** [comment]
Duplicate of #70031. And lacks vital details.
