### ISSUE TITLE
 Deploying solar suitcase causes error

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#74130]
### Describe the bug

```
 DEBUG    : new base 'folding_solar_panel_v2' doesn't match part type 'ap_folding_solar_panel_v2', this is a bug

 FUNCTION : set_base
 FILE     : C:\Users\colli\Documents\GitHub\Cataclysm-DDA\src\vehicle_part.cpp
 LINE     : 106
 VERSION  : 0.G-9851-g9e58e8a2e4

```

### Attach save file

[Paden-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15450196/Paden-trimmed.tar.gz)

### Steps to reproduce

Spawn in solar suitcase and deploy it

### Expected behavior

deployment with no error message

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: 0.G-9851-g9e58e8a2e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip]
]

**Comment by osuphobia** [comment]
#73976 
#73796 
duplicate
