### ISSUE TITLE
[XEDRA Evolved] Tool Maker Trait causes Slowdown 

### ISSUE THREAD

**Issue by MoonlightKitty26** [CleverRaven/Cataclysm-DDA#74142]
### Describe the bug

Been dealing with major time passage slowdown even when underground and away from areas w/high spawns lately. While crafting, my Homullus character mutated the Tool Maker trait and the passage of time slowed down. 

### Attach save file

[Reagan-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15462250/Reagan-trimmed.tar.gz)

### Steps to reproduce

1. Perform any time passing activity (wait, sleep, craft, etc.) 
2. Debug mutate the "Tool Maker" trait
3. Repeat step 1

### Expected behavior

I didn't think a single trait would impact the passage of time. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 6a57dbd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No Bionic Slots [no_cbm_slots],
    Mind Over Matter [mindovermatter],
    Mind Over Matter: <color_magenta>Remove Random Delay Before Learning New Powers</color> [mom_no_power_learn_delay],
    Mind Over Matter: <color_magenta>Remove Concentration Limit</color> [mom_infinite_concentration],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Mind Over Matter: <color_magenta>No Negative Nether Attunement Effects</color> [mom_no_negative_nether_attunement],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    Mind Over Matter: <color_magenta>Remove Pain Disables Powers</color> [mom_remove_pain_disables_psi_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extended Freeform [Extended_freeform],
    Japanese Folklore [Jap_folklore],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch]
]

### Additional context

I suspect that this is similar to the slowdown that used to be caused when metabolism was multiplied, but as I'm not good with coding shenanigans I lack the know-how to look into this issue myself.

**Comment by GuardianDll** [comment]
This one uses flat CRAFTING_SPEED_MULTIPLIER enchantment, so it is probably different from the metabolism issues. Someone need to step with debugger, but i suspect it's either the game hang on recalculating your crafting speed, or the game hang on evaluating the condition for effect every second

**Comment by MoonlightKitty26** [comment]
> This one uses flat CRAFTING_SPEED_MULTIPLIER enchantment, so it is probably different from the metabolism issues. Someone need to step with debugger, but i suspect it's either the game hang on recalculating your crafting speed, or the game hang on evaluating the condition for effect every second

Fiddling with the code, I discovered that it was this line of code triggering the slowdown: 
"condition": { "test_eoc": "EOC_HOMULLUS_IN_CIVILIZATION_CHECKER_CONDITION" }

Cause seems to be the latter. I removed that code from the trait and the slowdown it caused seems to be gone.

**Comment by Standing-Storm** [comment]
Does it still cause slowdown if you change the distances in the various `u_near_om_location` conditions to 2?

**Comment by MoonlightKitty26** [comment]
> Does it still cause slowdown if you change the distances in the various `u_near_om_location` conditions to 2?

No, that seems to have fixed it. I'm not sure if there's still a performance hit or not, but if there is it's barely noticeable.

**Comment by MoonlightKitty26** [comment]
> Does it still cause slowdown if you change the distances in the various `u_near_om_location` conditions to 2?

No, it seems to have fixed the slowdown. I'm not sure if there still is a hit to performance or not, but after the changes and re-adding the condition EOC the slowdown seems to be gone. I'd need a way of seeing precise changes to processing time or something to know for sure.

**Comment by GuardianDll** [comment]
`Debug - info - timer` would count irl seconds between each hour, so you can activate it, and then start some time consuming process, like crafting or just waiting for 6 hours - it is a good measurement tool for stuff like this
For you, Storm, I'd consider to edit this EoC to be hooked to OM_MOVE, and updating a single variable, and then EOC_HOMULLUS_IN_CIVILIZATION_CHECKER_CONDITION would just check the variable - this would make the game evaluate you being close or far from the locations not once every X seconds, but once when characters crosses overmap border

**Comment by MoonlightKitty26** [comment]
> `Debug - info - timer` would count irl seconds between each hour, so you can activate it, and then start some time consuming process, like crafting or just waiting for 6 hours - it is a good measurement tool for stuff like this For you, Storm, I'd consider to edit this EoC to be hooked to OM_MOVE, and updating a single variable, and then EOC_HOMULLUS_IN_CIVILIZATION_CHECKER_CONDITION would just check the variable - this would make the game evaluate you being close or far from the locations not once every X seconds, but once when characters crosses overmap border

Thanks for the advice! Using the debug timer, I did see that there was still a performance hit of about 300 milliseconds with the "City Strider" trait (The "Tool Maker" trait line, the trait line that adds mana/biopower regen, and the City Strider trait each use the same EOC, though "City Strider" uses about half of the same code of said EOC). 

![Dwight Barnett _2024-05-29T16-39-30](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/de8e5435-63eb-4eb4-a34c-244739a6bbf1)
![Dwight Barnett _2024-05-29T16-40-53](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/faf5f2a1-3a33-4987-90ec-cc5551051337)
(If this uploaded properly, one screenshot is the passage of time without the traits that use the EOC and City Strider, and the other is with those traits)
