### ISSUE TITLE
`map_in_city` says you're not in a city when you very clearly are

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#74177]
### Describe the bug

When working on #74175, I noticed that `map_in_city` would repeatedly return false even when I was clearly inside the city limits.

### Attach save file

[Darfur-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15492179/Darfur-trimmed.tar.gz)

### Steps to reproduce

1) Place the following JSON somewhere where it loads:
`  {
    "type": "effect_on_condition",
    "id": "EOC_CONDITION_CHECK_HOMULLUS_IN_CIVILIZATION_ON_OMT_ENTER",
    "eoc_type": "EVENT",
    "required_event": "avatar_enters_omt",
    "condition": { "u_has_trait": "HOMULLUS" },
    "effect": [
      {
        "run_eocs": [
          {
            "id": "EOC_CONDITION_CHECK_HOMULLUS_IN_CIVILIZATION_ON_OMT_ENTER_2",
            "condition": {
              "or": [
                { "test_eoc": "EOC_CONDITION_HOMULLUS_NEAR_FACTION" },
                { "map_in_city": { "mutator": "loc_relative_u", "target": "(0,0,0)" } }
              ]
            },
            "effect": [ { "math": [ "u_homullus_is_in_civilization", "=", "1" ] }, { "u_message": "You are in a civilized OMT." } ],
            "false_effect": [ { "math": [ "u_homullus_is_in_civilization", "=", "0" ] }, { "u_message": "You are NOT in a civilized OMT." } ]
          }
        ]
      }
    ]
  }`

2) Load game. 

3) Run west. Check when you start receiving the "You are NOT in a civilized OMT" and compare it to the city area on the map.

### Expected behavior

`map_in_city` matches the city limits that are visible on your map.

### Screenshots

 `map_in_city` returned false for this location:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/aba05ab0-d05c-4202-8b48-4d9614aa5b49)

Once I moved north to here, it returned true:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/ee8c7f0a-6729-4773-9187-2a6259646065)

Similarly, over here on the edge of town returns true:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/799975f3-3588-4528-86ee-f1e356ed3269)

But this spot returns false:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/d1993054-4917-454c-95a9-58a5500e0825)

it's not until two OMTs to the east of that picture that it begins returning true.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-28-2212 bf808f6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by Procyonae** [comment]
If I get the time I'll make the new city check from #71822 it's own PR and hook up everything to that, other than maybe non 0 city distance bc idk if that would be performance efficient or not

**Comment by Procyonae** [comment]
If you're not on z0 how do you think it would be best to work?

**Comment by Standing-Storm** [comment]
> If you're not on z0 how do you think it would be best to work?

Hmm. I would count any distance up (I think skyscrapers go up to Z: 9), and down to -1 at least for basements and the sewers. A cylinder would be easier but you'd end up with circumstances where some labs were partially in a city and partially not--not sure if subterranean labs should count as in the city or not.

**Comment by Brambor** [comment]
I would argue against it, since you can run around the underground, not knowing there is a city above you.

On the other hand, if you are in a cellar in a building, you still are in a city... So leaking that information isn't that bad. But then maybe mark it as a city only from z=-1 (deepest cellar) up as a compromise.
