### ISSUE TITLE
Bud: The program may crush when the vector items_ is empty in file /src/options.cpp. (static analysis report)

### ISSUE THREAD

**Issue by megumin9** [CleverRaven/Cataclysm-DDA#74184]
### Describe the bug

In file  /src/options.cpp, line 1422. If the vector items_ is empty,  iter ,equal to std::next( items_.begin() ), is behind items_.end(). The for loop may go wrong. Is it need to add a check here?

https://github.com/CleverRaven/Cataclysm-DDA/blob/856ea9d50e858ba991fe574360ac989de0cffbfe/src/options.cpp#L1416-L1428

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

Our static analyzer checks commit 77ff212, but the same issue still exists in the latest version on the default branch.

**Comment by Brambor** [comment]
I have encountered and fixed this there:
 - #74343

Closing as solved

**Comment by Brambor** [comment]
Oh, I didn't close this as promised.
