### ISSUE TITLE
Light Amp Goggles - Overlay Stopped working experimental build 2024-05-26-1716

### ISSUE THREAD

**Issue by Meadevil** [CleverRaven/Cataclysm-DDA#74208]
### Describe the bug

Turning on my Light Amp Goggles in game, but noticed that it stopped showing the green overlay. Went back through the builds to find when it last worked properly.

Light Amp Goggles [Night vision overlay] Working:
Cataclysm-DDA experimental build 2024-05-26-1437

Light Amp Goggles [Night vision overlay] No longer Working:
Cataclysm-DDA experimental build 2024-05-26-1716

### Attach save file

[Kiryu.zip](https://github.com/user-attachments/files/15507200/Kiryu.zip)

### Steps to reproduce

Install - Cataclysm-DDA experimental build 2024-05-26-1437
Launch Cataclysm:DDA
Turn on Light Amp Goggles. 
Observe Green Night Vision Overlay.

Install - Cataclysm-DDA experimental build 2024-05-26-1716
Launch Cataclysm:DDA
Turn on Light Amp Goggles. 
Observe the absence of the expected Night Vision Overlay.

### Expected behavior

For the night vision overlay to activate as usual when turning on light amp goggles.

### Screenshots

![Screenshot_20240531_093753](https://github.com/CleverRaven/Cataclysm-DDA/assets/171302003/a3c8d579-ad48-48b7-abc6-4c86f5f6a475)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 19043
- Game Version: 261b61c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

None. Self-explanatory issue.

**Comment by PatrikLundell** [comment]
Have you waited a tick after turning the goggles on? There are issues with things taking a tick to take effect.

**Comment by Meadevil** [comment]
Yes, I waited pressing [.] to allow wait time for it to activate. As you can see from the screenshot, the night vision overlay comes on in 2024-05-26-1437, but no matter how long I wait in any build after that ... it doesn't. Thats why I reported it. But thank you for checking. :)

**Comment by Meadevil** [comment]
Switched to Tiles instead of ASCII, I can see that the LAGs are using the low light overlay. I will close this PR.

**Comment by b0bhat** [comment]
@GuardianDll Should the night vision enchantment use the overlay? I don't think the NIGHT_VIS enchantment is used for anything other items so a check can be added to `character::has_nv` to also consider the enchantment.

The range of the light amp goggles could probably be a bit higher too.

**Comment by GuardianDll** [comment]
I'd prefer some character flag, that would change the overlay color, so both default and green nv would be possible without touching the enchantment 
Might be worth even adding a flag for blue-ish overlay, to match the resent development in night vis technologies

**Comment by Meadevil** [comment]
@b0bhat @GuardianDll thank you for all the time and effort you've put in. I'm Looking forward to trying the new NV attachments when I find them and using my LAGs in the meantime once the fix is merged. Thanks again! :)
