### ISSUE TITLE
'Very Short' character suffers pain/injury from entering vehicle

### ISSUE THREAD

**Issue by MochaModifier** [CleverRaven/Cataclysm-DDA#74204]
### Describe the bug

If you select Very Short as a trait, entering vehicles such as a car seat leads to warning messages such as "You are squeezed uncomfortably into the cramped space." and "You barely fit in this tiny human vehicle".
Additionally, this inflicts pain as if the character was a gigantic in size chimera, rather than the ~122cm tall human they are.

### Attach save file

N/A, issue is trivial to reproduce

### Steps to reproduce

1. Make a character with Very Short
2. Enter a car seat or similar vehicle element

### Expected behavior

The character should have no issues with being in a vehicle other than the intended difficulty (i.e. starting a vehicle and driving it without a booster seat).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 3f3e30b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key]
]

**Comment by MochaModifier** [comment]
From the warning messages, it sounds like Very Short may be using flags from the Large mutations; not sure why it isn't using ones from Little instead unless there's some interplay with vehicle accommodations.

**Comment by rselias** [comment]
Not caused by the Very Short trait. All characters are affected.

Also reported [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/74068). PR to fix is [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/74162).
