### ISSUE TITLE
When NPC finishes crafting it says `You craft X from memory.` - `You` instead of NPCs name

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74242]
### Describe the bug

When NPC finishes crafting it says `You craft X from memory.` - `You` instead of NPCs name.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/2de1ce19-ca99-4bd9-871b-42bea6769a3d)

### Attach save file

N/A

### Steps to reproduce

1. Let NPC craft something.
2. Wait for them to finish.
3. Observe this in the log.

### Expected behavior

NPCs name instead of `You`

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9784-g96401952f5-dirty [64-bit] - master was 96401952f5
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by jasonmokk** [comment]
Hi, I'd like to work on this.

**Comment by Brambor** [comment]
I assume you know how. Go for it!
