### ISSUE TITLE
`error: item extension_cable cannot fit into any pocket while loading: pocket with type (CONTAINER) not found` & `extension_cable` duplicated

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74246]
### Describe the bug

After activating an `electric lantern` to turn it on, it throws the following error. When turning it off, the extension cable duplicates and the copy falls to the ground.

```
 DEBUG    : error: item extension_cable cannot fit into any pocket while loading: pocket with type (CONTAINER) not found

 FUNCTION : combine
 FILE     : C:\GitHub\Cataclysm-DDA\src\item_contents.cpp
 LINE     : 758
 VERSION  : 0.G-9784-g96401952f5-dirty
```

### Attach save file

[Winter Beach - Copy-trimmed.tar.gz](https://github.com/user-attachments/files/15523294/Winter.Beach.-.Copy-trimmed.tar.gz)

### Steps to reproduce

1. Load game
2. Open the `a`ctivate menu. 
3. Activate the lamp ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/07871506-0688-4b66-ac80-c4b6a18065d7)
5. Turn it on. ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/a12dd9c8-3dd9-46b8-889d-1ee8181d61d8)
6. Observe error.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/85c322a7-cff6-46fc-9648-6c1ada43c6ce)
7. Activate it again.
8. Observe in the log that the `extension cord` fell to the ground. ~It duplicated since the lamp is still extended.~ EDIT: the lamp didn't drop the `extension cord` afterwards (when disconnected), so it didn't duplicate. Still, one cord could be used for multiple things.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/1eaa5d14-063b-4d0d-b2bb-400208542735)
9. This happens when this menu opens 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/c32e5b4e-a3d3-4930-bf2d-2e700c0cf3a8)

### Expected behavior

No error.

No duplication.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9784-g96401952f5-dirty [64-bit] - master was 96401952f5
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Kamayana** [comment]
I was able to fix this. Working on the PR writeup now.
