### ISSUE TITLE
A character can wear a maximum of two rings.

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#74256]
### Is your feature request related to a problem? Please describe.

I purchased several rings from the forge, but discovered that I can only wear two at a time. This doesn't seem right; a character should have ten fingers and thus, logically, should be able to wear more than just two rings.
What makes CDDA appealing is its realism, and it shouldn't be compromised for the sake of balance due to some peculiar reasons.

### Solution you would like.

Increase the specific finger limitations to allow a maximum of 10 rings to be worn.

**Comment by Standing-Storm** [comment]
Two rings also dates back to Magiclysm's D&D inspirations. The original 1974 edition states:

> ...only one ring may be worn on each hand if the ring is to be operable by the wearer.

**Comment by Maleclypse** [comment]
> Two (magic) rings also dates back to Magiclysm's D&D inspirations. The original 1974 edition states:
> 
> > ...only one ring may be worn on each hand if the ring is to be operable by the wearer.

I wonder if people would be open to allowing multiple magic rings but applying resonance penalties as if you were carrying multiple dimensional artifacts. Or if that's just a noob trap.

**Comment by AsAoA801** [comment]
Feet! I think it's 20!

**Comment by IoIqq** [comment]
> Two (magic) rings also dates back to Magiclysm's D&D inspirations. The original 1974 edition states:两个（魔法）戒指也可以追溯到Magiclysm的D&D灵感。1974年的原始版本指出：
> 
> > ...only one ring may be worn on each hand if the ring is to be operable by the wearer....如果戒指可由佩戴者操作，则每只手上仅可佩戴一个戒指。

But it's not very real.

**Comment by IoIqq** [comment]
> Two (magic) rings also dates back to Magiclysm's D&D inspirations. The original 1974 edition states:
> 
> > ...only one ring may be worn on each hand if the ring is to be operable by the wearer.

but it not real

**Comment by Maleclypse** [comment]
This applies to magiclysm which is based on D&D rules loosely.  Until this is impacting another in repo mod it's unlikely to receive any kind of changes.
