### ISSUE TITLE
`oxyacetylene` (id)  and `acetylene` have the same name: `acetylene`

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74252]
### Describe the bug

Looking through the crafting menu there are two distinct items with the name `acetylene`. It is very confusing:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/1a6435ed-2882-4e12-bb97-46567c2f1ab8)

Looking through the code, there they are:

```
  {
    "id": "acetylene",
    "type": "COMESTIBLE",
    "name": { "str_sp": "acetylene" },
    "category": "chems",
    "description": "A flammable gas that explodes under pressure.  Combined with oxygen, acetylene makes a great welding gas.",
    "comestible_type": "INVALID",
    "weight": "40 g",
    "volume": "250 ml",
    "price": "12 USD",
    "price_postapoc": "2 USD 50 cent",
    "material": [ "hydrocarbons" ],
    "symbol": "=",
    "color": "red",
    "charges": 1,
    "stack_size": 100,
    "phase": "liquid",
    "explode_in_fire": true,
    "explosion": { "power": 20, "shrapnel": 0 },
    "flags": [ "NO_DROP", "IRREMOVABLE" ]
  },
```

```
  {
    "//": "roughly 35grams of acetylene per cubic foot at STP. Volume given is when compressed - B tank has 9.17 L tank and holds 40 cubic feet.",
    "id": "oxyacetylene",
    "type": "AMMO",
    "name": { "str_sp": "acetylene" },
    "description": "Pressurized, dangerous acetylene gas.  Can be used for welding or cutting with a torch.",
    "weight": "1 g",
    "volume": "250 ml",
    "price": "24 USD",
    "price_postapoc": "5 USD",
    "material": [ "hydrocarbons" ],
    "symbol": "=",
    "color": "red",
    "count": 35,
    "stack_size": 35,
    "ammo_type": "weldgas",
    "phase": "liquid",
    "effects": [ "COOKOFF" ],
    "explode_in_fire": true,
    "explosion": { "power": 20, "shrapnel": 0 },
    "flags": [ "NO_DROP", "IRREMOVABLE" ]
  },
```

### Attach save file

N/A

### Steps to reproduce

1. Learn all recipes
2. Search for `acetylene`
3. Observe that they are different items

OR look into the code.

### Expected behavior

I can distinguish different items in the game by their name.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-9784-g96401952f5-dirty [64-bit] - master was 96401952f5
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Kamayana** [comment]
It's strange that oxyacetylene is even a distinct item at all - in real life there are separate canisters for both the acetylene and oxygen, they don't get mixed together into one like the oxyacetylene recipe is implying.

**Comment by XygenSS** [comment]
> It's strange that oxyacetylene is even a distinct item at all - in real life there are separate canisters for both the acetylene and oxygen, they don't get mixed together into one like the oxyacetylene recipe is implying.

Probably because we don't have multimag yet

**Comment by Brambor** [comment]
It was renamed to the same name in
 - #60660

Locally I just renamed it back to `oxyacetylene` so that I know what is going on. Readability is more important than realism.
