### ISSUE TITLE
Aftershock exosuit modules are unusable

### ISSUE THREAD

**Issue by Falconinglasses** [CleverRaven/Cataclysm-DDA#74292]
### Describe the bug

Because every single exosuit storage pouch ISNT RIGID its impossible to use them as they fall out of exosuits right after filling the slot they are in. Basically useless. This bug have been around for a year by this point.

### Attach save file

N/A

### Steps to reproduce

Use the exosuit system

### Expected behavior

Expexted for giant exosuit backpack to fit inside exosuit and not fall off it.

### Versions and configuration

Anything.

**Comment by Icantthinkofanameforthis** [comment]
seems to work just fine
i picked the emergency evacuation scenario for aftershock then grabbed the card and went to the exosuit storage bay, grabbed an exosuit underlayer and picked the exosuit frame on the fire side and used 'Manage exosuit modules' to put the plastic plates in along with the exosuit structural imager module, a mounted lamp, exosuit small auxiliary battery and exosuit gasoline ice power supply then used the escape pod (the other types of modules usually there were on the not fire side but figured i wouldnt have enough time to get them and get out)
on the planet after using the heat cream to not freeze i tested out the structural imager, lamp and small load modules and they work

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/3dc4e455-c042-4cdf-9221-9eafbede5317)

**Comment by John-Candlebury** [comment]
Please add a save file and list the modules you are having trouble with so we can verify and fix the issue.
