### ISSUE TITLE
Crash when steadying up aim.

### ISSUE THREAD

**Issue by gitelitko** [CleverRaven/Cataclysm-DDA#74308]
### Describe the bug

When trying to steady the aim of a weapon onto a creature the game will crash. It works fine with no creature as a target. If you don't try to steady up your aim you can exit the firing menu as expected.

### Attach save file

[CASUALITY-trimmed.tar.gz](https://github.com/user-attachments/files/15545908/CASUALITY-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save.
2. Try to fire a weapon at nearby creature.
3. Press any of the keys that steady aim (or the keys that fire immediately at whichever aim level).

### Expected behavior

Expected aim level to increase.

### Versions and configuration

- OS: Windows 10 ( 22H2 , 19045.4412 )
- Game Version: 02d16e3 (64-bit)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [  dda, no_npc_food, personal_portal_storms, no_fungal_growth, package_bionic_professions, mindovermatter, magiclysm, xedra_evolved, bombastic_perks, extra_mut_scens, sees_player_hitbutton, sees_player_retro, translate_dialogue, speedydex, stats_through_kills, StatsThroughSkills, MMA, Tamable_Wildlife ]

### Additional context

[CASUALITY.zip](https://github.com/user-attachments/files/15546009/CASUALITY.zip)
[crash.log](https://github.com/user-attachments/files/15546032/crash.log)
[debug.log](https://github.com/user-attachments/files/15546033/debug.log)

**Comment by osuphobia** [comment]
Caused by #74287

**Comment by PatrikLundell** [comment]
Fixed by #74315.

**Comment by gitelitko** [comment]
Not sure if I'm supposed to close this or someone else will 😅

**Comment by PatrikLundell** [comment]
Closing it yourself saves work for the (unpaid) maintainers, which is nice, so I think your call is a good one.
