### ISSUE TITLE
Auto forage cattails

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74300]
### Is your feature request related to a problem? Please describe.

I want to get the cattails from the swamps faster (less clicks).

Just like auto-pickup, I wanted to set auto forage. I set it to everything. Cattails were not harvested.

### Solution you would like.

One of the auto forage does harvest cattail.

Or select an area and the character would harvest from it.

**Comment by casswedson** [comment]
works for me
![Screenshot_2024-06-03_18-14-28](https://github.com/CleverRaven/Cataclysm-DDA/assets/58050969/de219536-531d-4ac7-8c8c-2017d9a9d510)


- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 26960ee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter]
]

**Comment by RenechCDDA** [comment]
Has worked for me in the past as well, make sure you also **enabled auto-forage**.

Yes, you can set the auto-forage to everything, but auto-forage itself also needs to be turned on.

**Comment by Brambor** [comment]
Huh, that sounds like an interface problem. I will see if that is the case for me. And maybe even fix it.
