### ISSUE TITLE
New Item Duplication bug just dropped

### ISSUE THREAD

**Issue by SomeGuyIGues** [CleverRaven/Cataclysm-DDA#74307]
### Describe the bug

When dropping an item into a car door and attempting to wield it again, I will receive a "Tried removing item from object which did not contain it" error. This allows me to infinitely duplicate some items.

### Attach save file

[Points Pool World+STKs-trimmed.tar.gz](https://github.com/user-attachments/files/15545556/Points.Pool.World%2BSTKs-trimmed.tar.gz)

### Steps to reproduce

1. Open the backdoor south of the avatar.
2. Drop the quarterstaff on the South-West tile adjacent the avatar.
3. Wield the quarterstaff.
4. Repeat as many times as you want
5. New item duplication bug just dropped

### Expected behavior

No items are to be duplication out of nowhere.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: cdda-experimental-2024-06-04-0210 9ec3053 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Additional testing may be required. I have no idea what might be causing this or other ways to cause this bug.

**Comment by toweroglass** [comment]
I did this about a month ago with a full acetylene torch. I managed to dupe two torches. For some reason i couldn't repeat the issue over and over so i wasn't comfortable reporting it.

**Comment by RenechCDDA** [comment]
The part to the southwest is in fact a fake vehicle part. Nothing should ever be put in there, but by dropping it directly you can. That in itself should be properly guarded with a debugmsg.

**Comment by toweroglass** [comment]
upon rereading the issue, this wasn't the dupe bug i noticed. mine was from dropping a wielded item into a trunk that didn't have enough space.
