### ISSUE TITLE
Pig on pig violence.

### ISSUE THREAD

**Issue by x7GoSu** [CleverRaven/Cataclysm-DDA#74317]
### Describe the bug

Not sure if this is a bug an oversight or just intended behavior however I'll describe my situation. So I have tamed some pigs and put them in a fenced area the size around 10x10. They managed to reproduce which is great but here is the problem. My pigs are killing the piglets. I don't know 100% what is going on but I think because the piglets aren't friendly when the pigs move and piglets are in their way they hit them.

### Attach save file

N/A

### Steps to reproduce

1.Make char
2.Make small fence area
3.Spawn pig fodder make it friendly
4.Spawn piglet  around pig
5. watch piglets don't tame them
6. Watch piglets be killed.

### Expected behavior

Any farm animals spawned from a friendly to inherit the friendly tag? Not 100% sure that would fix it or 

### Screenshots

![pigdying](https://github.com/CleverRaven/Cataclysm-DDA/assets/20464973/b21fdc3f-59a8-4df1-bf8e-68932e3242bc)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 9f9ae41 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    BrassMaking [BrassMaking],
    Stats Through Kills [stats_through_kills],
    <color_light_green>Cataclysm++</color> [Cata++],
    The Walking Dead [The_Walking_Dead],
    Deadly Zombie Virus [deadly_bites]
]

### Additional context

In screenshot I provided @ the 3 second mark you can the it shows pig follows smells and steps on the piglet and kills it.

**Comment by fairyarmadillo** [comment]
IMO tamed animals should have tame babies. Yeah alright maybe it's weird that they're friendly if they don't know you, but the current system is such an abstraction that it would be better just to eliminate the issue that way.

**Comment by rselias** [comment]
The same thing happens with kittens attacking their tame parents if they're born in a small, closed room, since they feel cornered.

**Comment by Maleclypse** [comment]
I think this can be solved in json, I thought there was a field that causes tamed animals to breed tamed animals but I could be wrong.

**Comment by solzerid** [comment]
Ok I'm just starting to dig through the source for this game, so I don't know how all the different flags and variables fumction, but would changing the call to add_spawn within try_reproduce so it passes the parent's friendly value fix the issue?
