### ISSUE TITLE
Show NPC morale (some keys in @ menu don't work for NPCs)

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74314]
### Describe the bug

I don't know how to see NPCs morale. It affects crafting so it is important.

Pressing `m` in this NPC stat window doesn't show their morale:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/6282d30f-d7df-40d1-9a98-7dd1acb3b1fd)

### Attach save file

N/A

### Steps to reproduce

1. Have NPC in fraction.
2. Talk to them.
3. `c` -> `I would like to know more about your abilities.`
4. Observe: @ menu is opened, not for the player character but for the NPC character.
   - ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/1f4f73dc-37da-48b5-99fa-b7de409e4d19)
5. The menu does work as you would expect with the exception of the following. They do nothing observable:
   - ![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/06451dca-9e5b-4f39-8ca1-424ed517946e)
   - `y` -> `Customize base appearance and name`
   - `m` -> `View character's morale`
   - `@` -> `Open medical menu`
   - `W` -> `Change sprite for armor.` (Additionally, there shouldn't be the `.` at the end.)

6. Look in the player character menu (for your character) and check that all of these do work

### Expected behavior

Ideally, implement them for NPC.

Otherwise, hide the keybindings or make a popup("Not implemented for NPCs").

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-10024-g124adb8057-dirty [64-bit] - master was 02d16e39de
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PGR-14** [comment]
Can confirm, tried to see morale, didn't work.

**Comment by Brambor** [comment]
Add to this: changing the name would be very nice too. I have 3 NPCs and for God's sake cannot distinguish them by name. Adding title doesn't show up anywhere I can see.
