### ISSUE TITLE
It cannot be obtained by removing the small integrated heater from the car?

### ISSUE THREAD

**Issue by AsAoA801** [CleverRaven/Cataclysm-DDA#74368]
### Is your feature request related to a problem? Please describe.

When removing a small integrated heater from a vehicle, I only get a pipe. However, when removing a small integrated cooler, I get the whole cooler. Is this a bug or an intentional design choice?
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/130402344/017a4e00-0522-4aa6-a791-63d032a6f7c0)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/130402344/46df60ba-c2a2-4054-b6b4-fd8505bf8457)

### Solution you would like.

I prefer to get the small integrated heater because the other heating functions are difficult to implement
If it was intentional, I respect it

**Comment by Kamejeir** [comment]
small integrated heater: "Set of tubes, that move heat from the engine into the vehicle cabin, heating it up."

just a heat pipe

**Comment by GuardianDll** [comment]
As Kamejeir says, it is intentional
