### ISSUE TITLE
Artificial Night Generator shouldn't grant full invisibility

### ISSUE THREAD

**Issue by rselias** [CleverRaven/Cataclysm-DDA#74366]
### Is your feature request related to a problem? Please describe.

Apparently back before 0.G, the Artificial Night Generator CBM gained the invisibility effect in addition to its normal effect of generating shadows. It's exactly the same invisibility effect as the Cloaking System CBM, but for less than a third of the power cost.

This doesn't make any sense to me. It's supposed to make enemies have a harder time seeing you from a distance, unless they have good night vision, no? Instead, even enemies that can see perfectly in the dark are unable to see you, and you can't be detected at all unless bumped into.

The [PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/48151) that included the change made no mention of a deliberate functionality change. Maybe it was accidental?

### Solution you would like.

Revert the change, removing invisibility from the Artificial Night Generator.

### Describe alternatives you have considered.

Increase the cost to match the Cloaking System, or remove the CBM entirely as it's redundant.

**Comment by GuardianDll** [comment]
> The 48151 that included the change made no mention of a deliberate functionality change. Maybe it was accidental?

You can see it doesn't change anything, just changed the notation
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/fa003b95-76db-451d-8890-abfc115c1d60)
i agree it shouldn't give invisibility, i suspect it does it to not make monsters with high night vision completely ignore said field

**Comment by rselias** [comment]
You're right, looks like it's been full invisibility for a long time. If only github had a branch search filter - trying to trace its history is a pain.

Shouldn't monsters with high night vision ignore it, though? If an enemy sees in the dark, why would artificially generating darkness do anything meaningful?

I just tried it out with the invisibility removed, and it seems to behave exactly as I'd expect it to. Normal zombies can't see me from more than three tiles away, and shady zombies can see me just fine.

I'm guessing full invisibility was a workaround for some issue years ago that probably doesn't exist anymore.

**Comment by GuardianDll** [comment]
it was not the work of Kevin, it was initially added in #1724, then it was added in #40645, with invis effect
@Fris0uman do you happen to remember why there is an invis effect here?

**Comment by rselias** [comment]
Looks like the invisibility enchantment was added in #39563.

**Comment by GuardianDll** [comment]
There is no reason to remove it, there is plenty of magiclysm/MoM spells that do exactly this
I was lucky to play with them, so i know they work exactly as Rselias says
@rselias if you're interested, feel free to make a PR that removes enchantment

**Comment by GuardianDll** [comment]
Again, it does

**Comment by rselias** [comment]
From brief testing, the shadow generation alone works as you would expect it to. I plan to make a PR after I've tested it more thoroughly to make sure I'm not missing anything.
