### ISSUE TITLE
The campsite cannot properly recognize furniture for their functions.

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#74381]
### Is your feature request related to a problem? Please describe.

Crafting at the campsite is limited; it doesn't recognize furniture tools like the anvil, even with assigned storage.

### Solution you would like.

1.Incorporate furniture functions into the storage area inventory for NPC crafting use.

### Describe alternatives you have considered.

Enhance NPC pathfinding to utilize all items and their functions in a set area.

**Comment by Procyonae** [comment]
Why close?

**Comment by IoIqq** [comment]
> Why close?

Because when I re-entered the game, I found that the problem no longer occurred, and there was no way to submit the relevant data to help repair the bug, or should I open it again?

**Comment by IoIqq** [comment]
> Why close?

And I also found that if there wasn't enough material around to keep the NPC going, the game would Stuck and flash back
