### ISSUE TITLE
when need let npc crafti something,whether selecting "Continue Crafting" sometimes incorrectly opens the "Crafting Menu".

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#74387]
### Is your feature request related to a problem? Please describe.

When I need the NPC to resume crafting an unfinished item, the "Continue Crafting" window doesn't open correctly，Instead, the "Crafting Menu" pops up.

### Solution you would like.

Prioritize the interface that prompts whether to continue crafting.

**Comment by Brambor** [comment]
This is not very detailed. This is a bug, not a feature request. With a bug report, if you follow the steps, you will provide the details necessary.

**Comment by IoIqq** [comment]
> 这不是很详细。这是一个错误，而不是功能请求。对于错误报告，如果您按照步骤操作，您将提供必要的详细信息。
> 
> 具体来说，我想念：
> 
> 1. 复制步骤。
> 2. 保存文件。
> 3. 您正在运行的版本。

My native language is not English, and I'm concerned whether others will understand my bug report.

**Comment by IoIqq** [comment]
> This is not very detailed. This is a bug, not a feature request. With a bug report, if you follow the steps, you will provide the details necessary.
> 
> Specifically, I miss:
> 
> 1. The reproduction steps.
> 2. The save file.
> 3. The version you are running.

My native language is not English, and I'm concerned whether others will understand my bug report.

**Comment by Brambor** [comment]
> My native language is not English, and I'm concerned whether others will understand my bug report.


Make a bug report:

https://github.com/CleverRaven/Cataclysm-DDA/issues/new?assignees=&labels=%28S1+-+Need+confirmation%29&projects=&template=bug_report.yaml
