### ISSUE TITLE
Close Quarter bionic quirks

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7439]
First of all, the description says that it improves your hand-to-hand skills. Instead, it sets all your melee-related skills to 5, which can be an improvement or a drop, depending on the character.

Next, if you open character screen, you will see all your relevant skills in yellow, equaling 5. But if you move your pointer to the screen tab, they will start displaying your normal skill levels.

I am not sure, but it seems that these values really do override your skills in actual combat.

So, either the description should be changed to reflect that this will be an improvement only for beginners (making this bionic pointless, especially since it seems to be pretty rare and belongs to the military group, so dangerous to get), or the bionic should add to your skills instead of overriding them. Also, the display fixes.
##

**Comment by WizardOfOoo** [comment]
Line 572 and 1082 of player_display.cpp Seem to where the issue is.  When you tab over to the skills tab it Draws over the yellow buffed skills with blue text and the player's base fighting skills.

**Comment by WizardOfOoo** [comment]
Was this bug fixed?

**Comment by kevingranade** [comment]
Based on a quick look through the code, it looks like the next tab handler overwrites the values, so still open.
