### ISSUE TITLE
Extraction of iodine from kelp

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#74391]
### Is your feature request related to a problem? Please describe.

Kelp contains a lot of iodine, theoretically, every 20 grams of dry kelp contains 0.1 grams of iodine. And with the recent addition of kelp to the game, I thought it would be a good idea to include a way to extract iodine from kelp as well.
The extraction of iodine from kelp can probably be divided into the following steps:
(i) Enrichment of iodine-containing compounds, add the kelp to water and soak it, and take the upper layer of clear liquid.
(ii) Oxidize iodine compounds using hydrogen peroxide under acidic conditions (e.g., using hydrochloric acid) to obtain iodine monomers.
(iii) Extraction of iodine monomers in solution using an organic solvent with a low boiling point (e.g., ether).
(iv) Evaporation of the organic solvent at low temperature to obtain solid iodine monomers.
The actual iodine extracted using ether as extractant was calculated to be about 40-45% of the theoretical iodine content of dried kelp (taking into account extraction efficiency, evaporation losses, and product purity).

### Solution you would like.

Add a recipe for Iodine extraction from kelp

**Comment by Brambor** [comment]
Why not try doing it yourself? Or are you just asking for feedback?
