### ISSUE TITLE
List of Various Typos

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#74436]
### Is your feature request related to a problem? Please describe.

I find a lot of very minor wrong things while translating random stuff, and from time to time I make lists of them and what needs fixing for anybody willing to spend the time on it. This is one of those lists

### Solution you would like.

**VANILLA**

Stuffed clam being kept singular is a bit ridiculous, how big is that clam?
- [x] stuffed clam -> stuffed clams

Chicken parmesan is pluralized when it shouldn't be as an uncountable object, same as Hinanese chicken rice and tandoori chicken:
- [x] chicken parmesans -> chicken parmesan
- [x] Hinanese chicken rices -> Hinanese chicken rice
- [x] tandoori chickens -> tandoori chicken

The Walther PPK pistol is not pluralized when needed:
- [x] Walther PPK pistol -> Walther PPK pistols

Leadwork Pennsylvania rifles should be changed to the new, better method to distinguish between single or multiple copies of the same firearm:
- [x] Leadworks Pennsylvania 2068s -> Leadworks Pennsylvania 2068 rifles

The game refusal message of letting you sleep and drive needs an end period:
- [x] You can't sleep while controlling a vehicle -> You can't sleep while controlling a vehicle.

The dialogue exiting sentence for the recently added Militia merchant needs a period:
- [x] Time for me to leave -> Time for me to leave.

This sentence in Sonia Greene's dialogue (godco guitarist) has a duplicate comma:
- [x] Nothin' much, just sitting around and biding my time,, getting any work I can.  I might play something to cheer everyone up, if my guitar wasn't busted. -> Nothin' much, just sitting around and biding my time, getting any work I can.  I might play something to cheer everyone up, if my guitar wasn't busted.

Missing periods at the end of the descriptions of the black and white sheep plushies:

- [x] This loving and fluffy sheep plushie features soft, woolly fur in black, with cute floppy ears and somewhat careless, bored eyes -> This loving and fluffy sheep plushie features soft, woolly fur in black, with cute floppy ears and somewhat careless, bored eyes.
- [x] This loving and fluffy sheep plushie features soft, woolly fur in white, with cute floppy ears and expressive eyes -> This loving and fluffy sheep plushie features soft, woolly fur in white, with cute floppy ears and expressive eyes.

Minor typo on the plesiosaurus plushie description:
- [x] A blueish, soft and friendly plesiosaurus plushie with big floppy flippers, a long neck and a and cute, gentle expression. -> A blueish, soft and friendly plesiosaurus plushie with big floppy flippers, a long neck and a cute, gentle expression.

Sketches aren't pluralized:
- [x] sketch -> sketches

**MODS**

Death message of the Croplord 2SPL (an Aftershock robot) has a typo on "crashes":
- [x] The Croplord crahses into the ground. - The Croplord crashes into the ground

Aftershock's active neurotoxin grenades have a typo'd double period in their description:
- [x] A neurotoxic device that deploys thick swathes of toxic foam upon detonation..  It's currently active. -> A neurotoxic device that deploys thick swathes of toxic foam upon detonation.  It's currently active.

Aftershock's Multi-axis maneuvering thruster furniture has a typo:
- [x] Multi-axis manuevering thruster -> Multi-axis maneuvering thruster

The feed message for the flat-headed peccary piglet of Megafauna has a typo'd double period in it:
- [x] The [piglet] seems to like you!  It squeals happily as you pet it.. -> The [piglet] seems to like you!  It squeals happily as you pet it.

This dialogue response in Helen Tavrel's dialogue (one of the Magiclysm Forge NPCs) should have a period at the end:
- [x] May the seas be ever in your favor -> May the seas be ever in your favor.

The description of the enchantments Salamander and Salamonstrous from Xedra Evolved have a typo'd comma:
- [x] Your Fire Elemental abilities grant you good resistance to temperature conditions and heat damage.  Also your body emits streams of heat into anyone who attack you,. -> Your Fire Elemental abilities grant you good resistance to temperature conditions and heat damage.  Also your body emits streams of heat into anyone who attack you.

Mind over Matter's triffid riftcaller's special attack message when aimed at non player entities has a duplicated at in it:
- [x] [riftcaller] waves its fronds at at [target]. -> [riftcaller] waves its fronds at [target].

Sky Island's Proofs of Determination are incorrectly pluralized:
- [x] Proof of Determinations -> Proofs of Determination

Limb Mod's feathered right arm heading has a capitalized A where it shouldn't:
- [x] feathered right Arm -> feathered right arm

### Describe alternatives you have considered.

- Fix them myself
- Wait for more to show themselves
- Not writing so many lists

**Comment by Brambor** [comment]
I don't know what is your setup, but changing the original string is super easy. I search the project with my code editor (Sublime Text) for the sentence. There is usually about one result. Then I fix it and make a PR.

Sometimes there might not be a result. The string might not be exactly as presented, as some parts are created dynamicaly. Then searching parts of the string always gets me there.

**Comment by Brambor** [comment]
Also can you make it into checklist? I am gonna take care of the easy typos.
- [x] yes
- [ ] no

syntax:
```
- [x] yes
- [ ] no
```

**Comment by Brambor** [comment]
Please look at the two PRs and mark off the done things.
I did everything but pluralization, I believe.
  - #74458
  - #74460
