### ISSUE TITLE
crashed airliners should not have ferals

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#74447]
### Is your feature request related to a problem? Please describe.

currently an average crashed airliner has about twenty ferals. Based on the wreckage the impact of the plane was pretty darn violent (it tore itself to shreds and left a trailing line of cratered earth and scrap) so it seems pretty likely that everyone on board died.
IRL, your odds of surviving a plane crash are >90%, but that's due in part to the efforts of the pilots to salvage the situation (pick a suitable landing spot, not be potentially messed up by the blob / a portal storm) and pictures of plane crashes I see when looking at survival rate examples typically show a plane that is far less obliterated than the one in game. Also, IRL if you sustain a serious injury during a crash, you aren't probably about to get killed by the raised corpses of your fellow passengers, but rather will benefit from a robust EMT network and rescue effort.

### Solution you would like.

All spawns at the wreckage should be zombies, perhaps a large amount of them should be crippled in some way (crawling, brainless etc) to represent the sheer destruction of the crash.

### Describe alternatives you have considered.

Make the plane much less obliterated to represent a survivable landing.

**Comment by Procyonae** [comment]
> Make the plane much less obliterated to represent a survivable landing.

It'd be cool to have a second less obliterated version, the current version is pretty cool looking for what it is tho

**Comment by Mithrite** [comment]
> It'd be cool to have a second less obliterated version, the current version is pretty cool looking for what it is tho

preferably with real NPCs that may or may not be able to fight off the non-survivors.

> All spawns at the wreckage should be zombies, perhaps a large amount of them should be crippled in some way (crawling, brainless etc) to represent the sheer destruction of the crash.

I'm not sure how to damage the spawns, can you think of any other locations that add pre-damaged enemies? Editing the spawn groups should be relatively doable otherwise.
