### ISSUE TITLE
The same EoC in two separate mods without dependencies on each other causes a double definition error

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#74443]
### Describe the bug

When working on #74279, I copied over a few EoCs as-is since they had the same function in both mods and I figured that the latest-loaded would overwrite the previous mod, and they'd be the same anyway regardless of the load order.

That's not what happened--the game treated it as the same EoC occurring twice in the same source and caused an error.

### Attach save file

N/A, only appears on world load

### Steps to reproduce

1) Create a world with both MoM and Aftershock as mods
2) Attempt to create a character
3) Error appears

### Expected behavior

Elements from the latest-loaded mod overwrites those same elements in any previous mods if the id is the same.

### Screenshots

![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3634323334393236313332303838303132382f313234393833303831333435383130383534372f696d6167652e706e673f65783d36363638626232362669733d363636](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/f0121dc8-d32d-4fe0-aaa4-fa91734716a6)

Note that the source is "()"

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3593 (22H2)
- Game Version: cdda-experimental-2024-06-10-1421 b54b0ea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]

**Comment by meelock** [comment]
Confirmed on my end. Crashes out to main menu on character gen.
 DEBUG    : Error: EOC_TELEPATHIC_DAMAGE_PSYSHIELD_CHECK_2 (struct effect_on_condition) has two definitions from the same source ()!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1051
 VERSION  : 99ed329

**Comment by Procyonae** [comment]
All mods required CI is also flaky because of this wew
