### ISSUE TITLE
No hope mod compatibility bug with MoM and Magiclysm. 

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#74446]
### Describe the bug

There are no spawning such buildings like magic academy, wizard tower, magic shop, office from MoM, when I'm playing with mods: No Hope, Magiclysm and Mind over Matter

### Attach save file

[test-trimmed.tar.gz](https://github.com/user-attachments/files/15781279/test-trimmed.tar.gz)

### Steps to reproduce

1. Make new world with these mods
2. Debug exploring the map

### Expected behavior

All mod structures in game. 

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.3.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-06-05-0202 b8f906a [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(88.9%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/762a52ec-d995-4cd6-820c-cb12fbf258ab)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/22276cc7-c64a-41b7-b9e7-beb966336c36)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/bc816d9a-9359-48aa-9e7f-1f38caeaa790)

Can't repro on two day old exp

**Comment by Cupidatis** [comment]
Hm, tryed some more worlds. Also removed aftershock(I didn't see aftershock ruins from your screenshots). Never changed... 
I'll try to update and look if behavior change. 
@Procyonae

**Comment by Cupidatis** [comment]
Updated to version Cataclysm-DDA experimental build 2024-06-11-0319 . Never changed. 
Tryed with "no hope" mod and structures didn't spawn. Without "no hope" All structures are spawning

**Comment by Procyonae** [comment]
momoyawn in the devcord can replicate this too, strange

**Comment by Night-Pryanik** [comment]
Can't reproduce this on 0.G-11869. Created a world with No Hope, Magiclysm, and MoM. Started game, debug-revealed the map, found 3 wizard towers, magic shop, magic academy, 2 magic meadows. I'm not sure what "office from MoM" in particular @Cupidatis talked about, but I got an error regarding `dm_office_cubical_phavian` from MoM:
![изображение](https://github.com/user-attachments/assets/1338f3d7-6692-4f3d-b86a-080335498c4a)
But I suppose that's because it has something to do with defense mode mod, not with NH mod.

**Comment by Cupidatis** [comment]
Updated and tried
- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.4.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-09-05-0451 5d5ef55 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.4%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Магиклизм [magiclysm],
    Разум над материей [mindovermatter],
    Надежды нет [no_hope]
]
Still have this big @Night-Pryanik

**Comment by Night-Pryanik** [comment]
What world settings do you have? Default or non-default? Have you tried on default world settings?

Can you start in some mod-specific start location, like Magiclysm's Wizard's Secret Basement Study?

**Comment by Cupidatis** [comment]
> What world settings do you have? Default or non-default? Have you tried on default world settings?
> 
> Can you start in some mod-specific start location, like Magiclysm's Wizard's Secret Basement Study?

City settings are default 8 and 4. Zombies - 1.5 but I think it's didn't matter. 
Tried some starts: secret basement started at first try, island mage - 2 tries, shelter mage - didn't start with 5 tries. But academy and wizard towers didn't spawn.
