### ISSUE TITLE
Gun store ammo should be a superset of the guns they have

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#74456]
### Is your feature request related to a problem? Please describe.

I don't live in the US but I feel like if you sold someone a gun and then told them you don't stock ammo for it they'd be fairly pissed

### Solution you would like.

Make a parameter palette that the gunstores share that picks what kind of guns they stock and ensures they stock corresponding ammo

### Additional context

Making this bc I'm more likely to see it in my open issues than I am my 100+ PR todo list, if someone else wants to take a shot at it feel free tho

**Comment by GuardianDll** [comment]
That assumes gun shop stock only single type of gun / caliber?

**Comment by Procyonae** [comment]
No?

**Comment by GuardianDll** [comment]
I don't see how the game could do it then, even with code

**Comment by Procyonae** [comment]
With multiple parameters? This doesn't need C++

**Comment by GuardianDll** [comment]
i eeeh i miss how it would work
isn't parameters are mostly for terrain/furniture? and not for itemgroups?

**Comment by Procyonae** [comment]
Nope, a parameter can be any of these and be used in switches for anything not covered by that https://github.com/CleverRaven/Cataclysm-DDA/blob/ea11df850b4634379f032934ebbfd56d1c7d44c6/src/cata_variant.h#L36-L87

**Comment by PatrikLundell** [comment]
As far as I understand you'd need one parameter per gun type the store was to stock. You could also do it per gun group, so that you'd bunch a number of guns of the same caliber into a group with its corresponding ammo.

You could also achieve this by having one chunk per combination (and you could have parameters for the chunks), but that would mean it would have to be customized to the particular store layout.

**Comment by dominic-dimico** [comment]
I live in the US, and the South no less (basically gun country).  It is indeed logical that the store would have ammo stocked for its guns, but that is under normal circumstances.  Even still, I've been within earshot of the sales counter more than a couple of times and heard, "Sorry, we're out of that ammo right now. We're getting another shipment this week."  Some people go to gun stores just to buy ammunition.

Even if the store promises to stock ammo to match its guns, this guarantee may not hold post-cataclysm.  I'd expect most of the ammunition to be bought up by the time riots peak.  Also, you may not be the first living person to have been in that gun store post-cataclysm---someone could have come along to take the ammo, but not the matching guns, if they already had their own gun.

It's also possible for a store to have ammo but no guns to match, if the guns just happen to sell out faster than the ammo.

**Comment by Procyonae** [comment]
> As far as I understand you'd need one parameter per gun type the store was to stock. You could also do it per gun group, so that you'd bunch a number of guns of the same caliber into a group with its corresponding ammo.
>
>You could also achieve this by having one chunk per combination (and you could have parameters for the chunks), but that would mean it would have to be customized to the particular store layout.

I were planning one parameter per caliber with corresponding gun + ammo item groups ye

>I live in the US, and the South no less (basically gun country). It is indeed logical that the store would have ammo stocked for its guns, but that is under normal circumstances. Even still, I've been within earshot of the sales counter more than a couple of times and heard, "Sorry, we're out of that ammo right now. We're getting another shipment this week." Some people go to gun stores just to buy ammunition.
>
>Even if the store promises to stock ammo to match its guns, this guarantee may not hold post-cataclysm. I'd expect most of the ammunition to be bought up by the time riots peak. Also, you may not be the first living person to have been in that gun store post-cataclysm---someone could have come along to take the ammo, but not the matching guns, if they already had their own gun.
>
>It's also possible for a store to have ammo but no guns to match, if the guns just happen to sell out faster than the ammo.

That's totally fair, I had no intention of increasing the actual numbers of guns/ammo just what spawns but approaching cata you'd imagine that they'd both be stocking whatever they could and peeps would be buying up stuff like crazy so this probably wouldn't be worthwhile
