### ISSUE TITLE
Matches may not contain red phosphorus.

### ISSUE THREAD

**Issue by Rocket-F-1024** [CleverRaven/Cataclysm-DDA#74459]
### Describe the bug

This may not be considered a bug. Currently in the game red phosphorus can be made from matches, but iirc the match heads don't contain phosphorus, it's the red strip next to the matchbox that contains phosphorus. Or is there some kind of match that I don't know about?

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

**Comment by suchacomic** [comment]
Strike anywhere matches (survival matches) does have phosphor compounds on the tip of the match head and the rest is made up of potassium chloride , but as you said regular safety matches do not have any phosphor in the match-head only on the striker on the box. We could remove the regular match from the red phosphor recipe and the survival match, matchbox and matchbook to the components.
