### ISSUE TITLE
Mouse overmap navigation while using a isometric non-overmap tileset is borked

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#74455]
### Describe the bug

The fix to #59974 corrected rendering for the overmap when using an isometric non-overmap tileset but mouse movement still seems to think it's isometric or something else funky is going on

### Attach save file

N/A

### Steps to reproduce

1. Enable Ultica_iso
2. Try moving around the overmap with mouse

### Expected behavior

The map cursor to move where I click

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/fb33c4c5-1f10-4ed1-8f29-6d58e2748b66

### Versions and configuration

N/A

### Additional context

I wouldn't be surprised if this is a dupe issue bc it's not remotely new iirc but I can't see one

**Comment by Qrox** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/fedfb57fe4f6ab875f094cb249b1ac383d04c53b/src/sdltiles.cpp#L3974

Should probably check if the window is `g->w_overmap()` and use `false` instead of `g->is_tileset_isometric()`.
