### ISSUE TITLE
`invalid harvest_list id ""` when corpse rots away

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74466]
### Describe the bug

```
 DEBUG    : invalid harvest_list id ""

 FUNCTION : obj
 FILE     : C:\GitHub\Cataclysm-DDA\src\generic_factory.h
 LINE     : 482
 VERSION  : 0.G-10098-g9e287b8451-dirty

```

### Attach save file

N/A

### Steps to reproduce

1. Kill a zombie.
2. Smash it so it doesn't revive.
3. Advance time by a year.
4. Move a tile.
5. Observe: error appears.

### Expected behavior

No `debugmsg`.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 0.G-10098-g9e287b8451 [64-bit] - Master was 5d0da40857
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
I think this should be fixed as of #74428?

**Comment by Brambor** [comment]
I will look into it when it compiles on my machine.

**Comment by Brambor** [comment]
Yup, fixed.
