### ISSUE TITLE
Isherwood's Not connected to road

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74472]
### Describe the bug

Well, I decided to reveal the map at one point, & noticed that the Isherwood's didn't have a road. I've seen this before, just didn't get around to make it & overwrote the save.

### Attach save file

[Mostly Normal-trimmed.tar.gz](https://github.com/user-attachments/files/15796779/Mostly.Normal-trimmed.tar.gz)

### Steps to reproduce

Make world, reveal map, try until Isherwood's are roadless

### Expected behavior

For them to have a road

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: cdda-experimental-2024-06-06-2047 daea5c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Magiclysm [magiclysm],
    Tankmod: Revived [Tankmod_Revived],
    Dorf Life [Dorf_Life],
    Caches [P_Caches],
    Rummaging [Rummaging],
    Mythical Martial Arts [MMA],
    More Survivor Notes [more_survivor_notes],
    Mind Over Matter [mindovermatter],
    Mind Over Matter: <color_magenta>Remove Rolling Delay in Each Path for Checking Learning Prerequisites</color> [mom_no_power_learn_delay],
    Mind Over Matter: <color_magenta>Remove Concentration Limit</color> [mom_infinite_concentration],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Mind Over Matter: <color_magenta>Remove Pain Disables Powers</color> [mom_remove_pain_disables_psi_limit],
    Hands [hand],
    Bombastic Perks [bombastic_perks],
    Bionic Traits [bionic_traits],
    Alternative Map Key [alt_map_key],
    Targeted Mutagens [targetedmutagens],
    Pixel's Various Fuckery [Pix's Shit],
    Frontier Mods Core [frontier_core],
    Loadout [loadout],
    Jackledead Armory [jackledead_armory],
    Gunsmith [gunsmith],
    Culinary Days Ahead [culinary_days_ahead],
    Xedra Evolved [xedra_evolved],
    Smart Cases [hyd_smartcases],
    Make bows great again [bow_opness],
    Better Arachnids [betterArachnids],
    Aftershock [aftershock],
    <color_light_green>Cataclysm++</color> [Cata++],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Bionic Slots [no_cbm_slots],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Additional backgrounds [Arendeth_Additional_backgrounds],
    Crazy Cataclysm [crazy_cataclysm],
    Magiclysm Revamp and Additions [magicrevamp]
]

### Additional context

1: There is two, the one I'm standing it (The pump station) is part of the Isherwood's. The one to the South-West is spawned in ('cause of the pump station lab, I wanted to make sure it wasn't part of the Isherwood's)

**Comment by Procyonae** [comment]
This should be fixed by #74329 (that merged a day after your version '^^)

**Comment by PGR-14** [comment]
Oh, thanks dude.
