### ISSUE TITLE
Base camp missions - anvil not registering

### ISSUE THREAD

**Issue by TheVagrantKnight** [CleverRaven/Cataclysm-DDA#74483]
### Describe the bug

The normal anvil isn't registered for base camp missions in either deployed or undeployed forms. This makes any base camp mission that requires a tool with anvil 3 impossible to start.
----------------------

![afbeelding](https://github.com/CleverRaven/Cataclysm-DDA/assets/145038845/ce9fb1bf-3f64-4a55-bbee-f07b1b746bf3)
------------------
![afbeelding](https://github.com/CleverRaven/Cataclysm-DDA/assets/145038845/d9dd7ccb-1a22-46b2-a4da-d18d0362f4e6)

### Attach save file

[Metropolitan Westlands-trimmed.tar.gz](https://github.com/user-attachments/files/15803392/Metropolitan.Westlands-trimmed.tar.gz)

### Steps to reproduce

deployed anvil
1. load up the save file
2. the anvil is already deployed in the base camp storage zone
3. (optional) take down and place the anvil again if needed for testing
4. head to the mission board (basement in the save file)
5. search any base camp craft mission that has a craft in it that requires the anvil. I used the hatchet as an example
6. The anvil is not recognized as a tool with anvil 3 for the sake of the recipe
7. (verification) The deployed anvil works for personal crafts as can be seen when trying to craft a katana
-----------------
undeployed anvil
1. load up the save file
2. the anvil is already deployed in the base camp storage zone
3. take down the anvil and place in any tile of the storage zone. The tile the anvil was at should work for this.
4. head to the mission board (basement in the save file)
5. search any base camp craft mission that has a craft in it that requires the anvil. I used the hatchet as an example
6. The anvil is not recognized as a tool with anvil 3 for the sake of the recipe

### Expected behavior

Presumably the case in which the anvil is deployed, it is expected the anvil counts as a tool with the anvil 3 quality for the sake of the base camp mission. Whether or not the undeployed version should count, I'll leave up for dispute.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-06-05-1812 1a6014e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Alternative Map Key [alt_map_key]
]

**Comment by silvadomi** [comment]
Could not reproduce, when I open your savefile and go straight to the bulletin board in the basement it shows the hatchet as craftable. That's with cdda-experimental-2024-06-12-0454.

![anvil_check](https://github.com/CleverRaven/Cataclysm-DDA/assets/171120271/94c48d3a-2c54-4fee-a21a-e58570999318)

**Comment by silvadomi** [comment]
Of course an undeployed anvil should not allow the hatchet to be crafted, and that's what happens as I saw in another test.

**Comment by TheVagrantKnight** [comment]
tried testing it again and you're right, it does accept the anvil now as well as the deployed E-forge. I'm not sure what was going on at the time of the reporting then. Could have been some in memory fuckery that was preventing it from recognizing the anvil. 

I'll mark this as completed for now and will keep my eyes open should  this happen again.
