### ISSUE TITLE
Homemade napalm

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74488]
### Is your feature request related to a problem? Please describe.

Well, a kind of pseudo-napalm is really easy to make. I want that.

### Solution you would like.

Add a recipe for homemade napalm made w/ Gasoline & Styrofoam.

Source: https://www.youtube.com/shorts/hfkbQIaW-y8 
He uses acetone in the video, but if you use an accelerant (Like gasoline or diesel), it'll burn better.

**Comment by suchacomic** [comment]
Isn't [Gelled Gasoline](https://cdda-guide.nornagon.net/item/gelled_gasoline) the same thing you are describing.

**Comment by PGR-14** [comment]
Didn't see that.
