### ISSUE TITLE
Followers can be sent to hunt for mutagen samples

### ISSUE THREAD

**Issue by GalacticApple** [CleverRaven/Cataclysm-DDA#74496]
### Is your feature request related to a problem? Please describe.

It's relatively simple to get enough mutagen to push a handful (or two) of your followers across a specific mutagen threshold. However, if you want to mix and match mutagens to get a specific combo of traits across a number of followers (or if you want to mutate more people with rarer mutagens), suddenly things become much more difficult. Considering how fast save files can get if you do a lot of exploration, I think there should be a way to have a small, but reliable source of samples while also hunkering down in one area. 

### Solution you would like.

This feature would be similar to sending your followers out to hunt, though they would need good combat and medical skills (perhaps even a proficiency in anatomy?) on top of good survival skills. These missions would also be much more dangerous than normal hunting jobs, but perhaps being skilled enough can offset some of the risk. You can specify which category of samples you want (or you can send them out to collect a random mix of all-of-the-above) and how much they bring back could depend on the relative rarity of those samples. If you send them after insect samples, you might get more than you'll know what to do with (because big bugs are everywhere). Sending them after rarer sample types (like Slime or Ursine) will net you less since the sources for those are a lot scarcer. Certain sample types might be impossible to send your followers after (like ELF-A, Medical or Alpha) since these generally can't be found outside of lab locations. 

### Describe alternatives you have considered.

An alternative is that if you tell a follower with a high medical skill (or relevant proficiency) to go hunting, they can occasionally find samples while they're working. However, I think the samples you could get this way would have to be limited to the "mammal" sample categories.

**Comment by kevingranade** [comment]
I know this might come as a surprise, but gathering mutation samples and doing mad science on yourself and your followers is *not considered normal*.  It's arguably a bug that you're able to get your followers to mutate at all, and we're not further normalizing this by making it a routine follower task.  We could consider having different NPCs be pro- and con- mutation and unlock an activity like this for the (rare) pro-mutation NPCs, but in general it's a non-starter.
