### ISSUE TITLE
Error when MOM & Aftershock are used

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74509]
### Describe the bug

 DEBUG    : Error: EOC_TELEPATHIC_DAMAGE_PSYSHIELD_CHECK_2 (struct effect_on_condition) has two definitions from the same source ()!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1051
 VERSION  : 99ed329

### Attach save file

N/A

### Steps to reproduce

Make world, put Aftershock & MOM

### Expected behavior

them working

### Versions and configuration

Using cdda-windows-tiles-sounds-x64-msvc-2024-06-11-0319

**Comment by GuardianDll** [comment]
Thank your for your issue, but we already track it in #74443
