### ISSUE TITLE
Starting equipment items missing, but still available for certain interactions

### ISSUE THREAD

**Issue by EvanBalster** [CleverRaven/Cataclysm-DDA#74503]
### Describe the bug

When using my favorite character preset, several of my starting items (from profession and traits) are absent from my inventory.  However, in the case of an inhaler, the item was still present for purposes of fulfilling a quest.

### Attach save file

Occurs consistently with this template created in the latest experimental:
[Helen V11.zip](https://github.com/user-attachments/files/15815171/Helen.V11.zip)

### Steps to reproduce

Load the attached character template, or recreate it by selecting the same options for a custom character.

Notice the following items are absent:
- Handy Woman: multitool
- Handy Woman: nail gun, nails
- Asthmatic: Inhaler

If you happen to generate an NPC that gives the inhaler quest, you will be able to fulfill it depite not apparently possessing an inhaler.

### Expected behavior

I would expect the items to appear in my inventory as normal.

### Versions and configuration

- OS: Windows 11 64-bit
- Cataclysm-DDA experimental build 2024-06-12-1850
- English, tiles, sounds
- Only default mods

**Comment by harakka** [comment]
Can you check if this is still present on https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-06-13-0502 or later?

**Comment by EvanBalster** [comment]
> Can you check if this is still present on https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-06-13-0502 or later?

Indeed, the problem is fixed now.  I assume #74499 fixed the issue.

**Comment by EvanBalster** [comment]
Interestingly, the patch appears to restore the missing items on existing saves.  My character now has a multitool, nails, another inhaler, and a nail gun has dropped at her feet.
