### ISSUE TITLE
option to limit evolution

### ISSUE THREAD

**Issue by shadowonwhite** [CleverRaven/Cataclysm-DDA#74536]
### Is your feature request related to a problem? Please describe.

For custom games that cap player's power by removing bionic and mutagen and such, zombies will always overpower the player as evolution progresses indefinitely.

### Solution you would like.

add option to stop further evolution of zombies after a specified amount of time

**Comment by kevingranade** [comment]
Sounds like something for a mod to do. This is not something we would surface as an option.
