### ISSUE TITLE
Make enemies more affected by stun and stagger

### ISSUE THREAD

**Issue by shadowonwhite** [CleverRaven/Cataclysm-DDA#74539]
### Is your feature request related to a problem? Please describe.

Stun and stagger's limb mod only dampens player's dodge and not enemy's

### Solution you would like.

make everyone equally susceptible to the negative effects

**Comment by Venera3** [comment]
Stunned mosters skip their turn.
```type": "effect_type",
    "id": "staggered",
    "name": [ "Staggered" ],
    "//": "Mainly for monsters",
    "desc": [ "You've been knocked off-balance by an attack." ],
    "apply_message": "You're staggered off-balance.",
    "max_duration": "5 s",
    "base_mods": { "speed_mod": [ -20 ] },
    "removes_effects": [ "grabbing", "grabbing_2", "grabbing_3" ],
    "rating": "bad",
    "show_in_info": true
```
Staggered monsters lose -20 speed and lose grabs.
Both are more sever than the player's equivalent effects.
