### ISSUE TITLE
Lockpick crafting uses lockpicking proficiency, but doesn't improve it

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#74532]
### Describe the bug

I've created a number of emergency - > improvised lockpicks, but see the Lockpicking proficiency doesn't improve.

### Attach save file

N/A, it should be a JSON issue.

### Steps to reproduce

1. Start with a (reasonably) fresh character.
2. Get the equipment to make emergency lockpicks as well as improvised lockpicks (conveniently, these have different names between recipes and the crafting UI).
3. Note your lockpicking proficiency progress.
4. Craft an emergency lockpick.
5. Craft an improvised lockpick from the emergency one.
6. Note that you haven't progressed your lockpicking proficiency.

### Expected behavior

I expected crafting using a proficiency should actually advance it. If that is not intended to be the case at all times, the UI should clearly distinguish between proficiencies that are advanced from those that aren't.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: 0.G-10201-gcb44970a12-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

The lockpick recipes both have "learning_time_multiplier" set to 0, and anything multiplied by zero becomes zero. That may well be the cause. If you don't actually want to change the rate the appropriate multiplier (as opposed to modifier) is 1.

I cannot say whether this also blocks the improvement of the trap/devices skill, as it's reported by the UI that it's too high to be improved by the recipe. However, I think the skill did when crafting the first two lockpicks (which have since been consumed through usage).

I still need the lockpicks, so I haven't lost a few hours, but it would be a real bummer to spend a day crafting something to improve proficiencies only to find that you'd wasted both time and materials on crafting some junk you didn't have any use for while attempting to gain the proficiencies needed to craft something you actually want.

**Comment by Aerin-of-the-Toast** [comment]
I agree it could be better communicated but the behavior makes sense to me. 
You ideally want to know how to pick locks to even know what you need to make a usable lockpick, but making the lockpicks wouldn't make you better at picking locks.

**Comment by kevingranade** [comment]
As aerinn says,  this is inebriated.  There are quite a lot of activities that use a skill or proficiency as a prerequisite and doesn't strain said skill or proficiency.

**Comment by Zireael07** [comment]
@kevingranade Uh, spellcheck acted up? What's inebriated supposed to be here?

**Comment by PatrikLundell** [comment]
My main issue wasn't with the functionality, but rather that it's not communicated to the player whether the proficiency is trained or not, resulting in it being seemingly random (based on someone's subjective (but hopefully grounded) judgement of whether it should be or not).

Doesn't matter, since the issue now is dead until someone else brings the underlying issue up in the future.
