### ISSUE TITLE
Out-of-date release distribution for Gaiman (0.G)

### ISSUE THREAD

**Issue by gridbugsmasher** [CleverRaven/Cataclysm-DDA#74566]
### Describe the bug

Files distributed under 'Assets' on the release page for Gaiman (https://github.com/CleverRaven/Cataclysm-DDA/releases?q=Gaiman) are not in sync with the 0.G branch, they contain outdated builds missing patches that address issues such as for #63859. 

### Attach save file

N/A

### Steps to reproduce

Go to https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.G.

Under 'Assets', click on the hyperlink beginning with cdda-linux-curses.

Extract archive, find 'cataclysm-launcher' and execute it. Notice version string mismatch between #d6ec466 and the head commit of the 0.G branch, #3a1e046.

### Expected behavior

Patches merged into the 0.G branch are redistributed to end-users, within a reasonable timeframe.

### Versions and configuration

System: Linux 6.9.4-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
Game Version: d6ec466
Graphics Type: Curses (ncursesw5)
Mods loaded: None

### Additional context

This is my first issue for Cataclysm: Darks Days Ahead.

**Comment by RenechCDDA** [comment]
As far as I am aware, there will not be any more releases for 0.G and the assets page links to the correct versions. There were aborted plans for a 0.G-1 with backports, like with the 0.F releases, but for various reasons that did not come to be.

We are currently working towards the 0.H release, so I am very confident any new 0.G builds are not on the table. 

Thank you for your report, but there's nothing to be done here.
