### ISSUE TITLE
Problems w/ the website.

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74562]
### Describe the bug

Just like all the other times, it's stopped working again. Last update was the 11th, now it's the 15th & things have been merged since then. Last merge was the Military base roofs.

### Attach save file

N/A

### Steps to reproduce

Check experimentals on the website, despair.

### Expected behavior

Showing the merged builds.

### Versions and configuration

N/A

**Comment by NetSysFire** [comment]
Maaybe related to #74006. Also https://github.com/CleverRaven/Cataclysm-DDA/deployments/github-pages

**Comment by PGR-14** [comment]
Yeah, I've made 2 separate issues before this, it just keeps happening. #74006 is probably the root problem.

**Comment by NetSysFire** [comment]
Please link those related issues you made

**Comment by PGR-14** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/73676 https://github.com/CleverRaven/Cataclysm-DDA/issues/73562 https://github.com/CleverRaven/Cataclysm-DDA/issues/71194

**Comment by harakka** [comment]
Download from GitHub releases page. The website only updates for releases where all versions are built successfully, that is on purpose.

**Comment by harakka** [comment]
Scratch that it's just object creator failing to build again.
