### ISSUE TITLE
Begin enforcing the new ``to-hit`` syntax

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#74563]
### Is your feature request related to a problem? Please describe.

For a longer while now we've had the fancy new ``to-hit`` syntax all ready to go. It's awesome and 9/10 times easy to use. Except that almost no newly added items seem to use it.

### Solution you would like.

Do something similar to the known bad density list for old ``to-hit`` syntax - list all items using old syntax there, and throw an error if someone tries to add the old syntax to more items for any reason. Important to have this list ignore items without ``to-hit`` defined at all, so as to not force every single item to have the field defined - it's pointless for at least a solid half of our itempool that isn't meant to be used as weapons.

### Describe alternatives you have considered.

Enforce the need to have a ``to-hit`` defined for any items with melee damage defined as well. I think it's not a bad idea, since if it's got melee damage defined it's expected to be usable as a weapon, and as such should have these values defined.

### Additional context

@Procyonae you asked me to fill this as an issue

Enforcing this syntax would allow us to make wider use of the variables it defines, such as using the contact surface for weakpoints, length for disarming, or balance for potentially losing grip on your weapon. These are just examples, but there's been a nonzero amount of conversations on the devcord where using those variables came up as possibly being useful.

**Comment by TealcOneill** [comment]
Very cool. Glad to see it's gonna be used more.

**Comment by Procyonae** [comment]
Got the test working I'm just doing a second 1 off test to find all in repo melee weapons that don't have a to_hit (old or new inc inherited) defined bc while the default is supposed to be -2 it's actually 0 rn so they'll want defining at the same time.

**Comment by harakka** [comment]
Shouldn't we add that on c++ side so that we don't need json churn for things that absolutely don't need it

**Comment by Procyonae** [comment]
Shouldn't add what?

**Comment by harakka** [comment]
The value defaulting to -2.

**Comment by Procyonae** [comment]
Oh I am changing the C++ default, my point is that because it's currently defaulting to 0 there are melee weapons without a to_hit defined that are going to be heavily invisibly nerfed so I'm trying to make a test to detect them so I can manually add to_hit s to them at the same time
