### ISSUE TITLE
classic_zombies unintentionally removes all map extras

### ISSUE THREAD

**Issue by shadowonwhite** [CleverRaven/Cataclysm-DDA#74578]
### Describe the bug

  {
    "type": "region_overlay",
    "regions": [ "all" ],
    "overmap_feature_flag_settings": { "whitelist": [ "CLASSIC" ] }
  },

This seems to require map extras to have the tags too, which none does.

### Attach save file

N/A

### Steps to reproduce

1.Create world with classic_zombies enabled
2.Try to find a single map extra

### Expected behavior

do not check map extras for tags

### Versions and configuration

OS: Windows
OS Version: 10.0.19045.4529 (22H2)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/9568831da00cf20a3ec26a894d5fd08266b036c4 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth],
Translate Complex Dialogue [translate_dialogue],
sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
SpeedyDex [speedydex],
Stats Through Skills [StatsThroughSkills],
Bionic Slots [cbm_slots]

### Additional context
Deleting the aforementioned line and reloading the save fixes the problem.

**Comment by Procyonae** [comment]
I'd like the whitelist/blacklist flags to be split by type/subtype too but adding the flags where appropriate makes sense in this case, it can either be done in vanilla like it currently does or in the mod itself like I did here when adding a whitelist to Backrooms. (Which personally I feel should be the norm)
https://github.com/CleverRaven/Cataclysm-DDA/blob/ae7671af947fdfdb1a2172f49186ba96bcc215aa/data/mods/Backrooms/map_extras.json#L24-L29
