### ISSUE TITLE
Cloned repo lacks launcher file and now experimental and Gaiman launcher show up as blank file icon.

### ISSUE THREAD

**Issue by TealcOneill** [CleverRaven/Cataclysm-DDA#74575]
### Describe the bug

When I updated my clone of master about a week ago I found that their was no launcher icon in the folder anymore. There is a cataclysm-launcher file but it's tiny and has a broken file image.
I figured some bug had broken it and it would be fixed in a day or two. 
Next day I came back and updated so I could check and still no launcher file. 
Then I decided to download the latest experimental and just make my changes there. I can launch it just fine but on my taskbar it shows up as the same blank file icon as the cloned version.
Today I decided to update once more and still have the same issue, and it persists after recloning the repo entirely.

### Attach save file

N/A

### Steps to reproduce

I doubt this is replicable. I even asked people in discord if they were having this kind of issue and no one spoke up.
My guess is that something on my machine is borked and messing with it but I have no clue how to go about fixing it.

### Expected behavior

That the clone comes with a working launcher and that other applications don't have a broken icon.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45678006/831a437e-9f9e-484c-bead-b5f2ef9ca078)
![brokenicon](https://github.com/CleverRaven/Cataclysm-DDA/assets/45678006/c6a650a8-a373-4dfd-8be5-d97952c3bfbb)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45678006/6244ddb0-af48-4d29-8b3f-f13883d8cccc)

### Versions and configuration

Windows 10

**Comment by ZhilkinSerg** [comment]
Screenshot actually shows icon in the top left corner of the CDDA app window and in the CDDA shortcut on desktop (meaning app icon is included in app resources), so I believe there is something wrong in your OS. Most possibly icon cache in explorer is broken and you will need to rebuild it deleting icon cache from `%localappdata%\Microsoft\Windows\Explorer`.

See some relevant links:

https://answers.microsoft.com/en-us/windows/forum/all/app-icons-not-showing-in-taskbar-notepad/591c6aff-3cc6-4a3d-bcb2-d2f958b35c21

https://techcommunity.microsoft.com/t5/windows-11/no-app-thumbnail-on-taskbar/m-p/3592807

https://www.howtogeek.com/fix-hidden-taskbar-icons-windows-11/

**Comment by TealcOneill** [comment]
I do agree it's an issue with my OS.
I cleared deleted this and made sure it was fully deleted then restarted my computer.
Both issues are still happening.
Thanks for the help Zhilkin!

**Comment by harakka** [comment]
It looks like you're on Windows. The cataclysm-launcher is a red herring, it's a Linux shell script to launch the game _on Linux_. It has nothing to do whether the binary gets an icon on Windows or not.

**Comment by kevingranade** [comment]
I wish you luck,  but this issue tracker is very much not here to provide tech support,  it's quite clear this is not actually a dda project issue,  so I'm closing it.

**Comment by TealcOneill** [comment]
Well, thanks for taking a look guys.
