### ISSUE TITLE
problem with quest HUB01 "contract: ligth retrieval"

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#74573]
### Describe the bug

I tried to complete this quest many times, but I was never able to complete it

I cleared the entire building, cleared the basement, in the room with the nanofabricator there are actually several nanofabricator templates (always different), I took them to HUB01, but not one of them counts as a quest item (if anything, my drop settings are 0.1)

maybe the quest is working fine, it seems to me that maybe the problem is any mod

quest item "photonic circuitry template"

### Attach save file

none

### Steps to reproduce

try to complete this quest with drop setting 0.1 and my world settings

### Expected behavior

help?

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: cdda-experimental-2024-06-15-0455 d5efb05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by IdleSol** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/71528#issuecomment-1949935532

**Comment by watcherPlayer** [comment]
how can you change the size of the drop in a ready-made world? This is written down during creation... do I need to edit some text file? Which ?

**Comment by watcherPlayer** [comment]
completed this quest with drop 1.1 several more times; in the room with the nanofabricator there is a quest item in the box; its name is in the screenshots

before end
![Снимок экрана от 2024-06-16 11-44-52](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/8450c0d4-3864-4003-b927-f695c8848f2c)
after end
![Снимок экрана от 2024-06-16 11-45-59](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/10dccf61-06ca-4865-9bc0-8f79bf367f50)

**Comment by watcherPlayer** [comment]
In the end, I still don’t understand, what is the solution for those who play low drop? switch to 1.00 when completing a quest?

**Comment by Zireael07** [comment]
Most quests do not work well with very low drop settings since they are written assuming 1.00

**Comment by watcherPlayer** [comment]
I played at first with a chance of 1.0, but it’s not interesting, each mod looks like a Christmas tree when killed, there’s no point in remembering the terrain for mining and you don’t need to remember where you can find this or that building material (because there are very few of them), right away the source code of the game becomes interesting to search for this or that ingredient in mods (https://cdda-guide.nornagon.net/ works only for the version without mods)

**Comment by IdleSol** [comment]
>how can you change the size of the drop in a ready-made world? This is written down during creation... do I need to edit some text file? Which ?

1. Load the save
2. `Esc` - `2` (options)
3. `current world` - `game world options` - `Item Spawn Scaling Factor`
4. Set the correct value

Only places visited by a character exist in the game. If a character has not been somewhere, that place does not exist. It is loaded when the character goes there. And it is at the moment of loading that its contents are determined: items, events, monsters. After that, it is stored in memory (?) until the game is saved. When saving, it is written to the save file.

So you can change this parameter as you go along. And get "poor" and "rich" locations.

I'm not sure exactly. The given radius is 60 tiles from the character.

As applied to this quest. When you take the quest, the game creates a wooden box in the basement of the tower and focuses on the current coefficient value. If it is 0, only the box will appear. And if it is 1, then the box and its contents. And if it is set to 10, the contents will increase 10 times.

After taking the quest, you can set the coefficient to 0.1. And then going to the tower you will continue to play in a poor world.

In the end, I still don’t understand, what is the solution for those who play low drop? switch to 1.00 when completing a quest?

You can modify the files locally as the link says: https://github.com/CleverRaven/Cataclysm-DDA/issues/71528#issuecomment-1949935532
Or play with the odds. Or reach the location, find the box. And create the necessary items, through the debug menu.

**Comment by IdleSol** [comment]
>completed this quest with drop 1.1 several more times (fatal, segmentation fail, etc...); in the room with the nanofabricator there is a quest item in the box; its name is in the screenshots

![pict 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/0e727368-a477-41d5-8e46-daa44fdbb1ab)
![pict 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/5b9aec3d-b43e-43c2-b990-05620f46e317)

This is what it should be at a value of 1.0.

**Comment by watcherPlayer** [comment]
yes, that's right, I already tried to describe it above

**Comment by watcherPlayer** [comment]
yes, I understood about the loot coefficient, so I don’t take this quest while saving, I already wrote about loot above, I’ll wait until they make a drop then...

**Comment by PatrikLundell** [comment]
The mission chunk places the item with:
`"items": { "T": { "item": "nano_templates", "chance": 100 } },`.
What happens if the optional "chance" parameter is removed? Does the value default to 100 or does it mean mandatory spawn? It would seem to be the latter, but MAPGEN.md doesn't really say.
If that's the case, just removing the chance parameter ought to guarantee the spawn (and, if so, all mission generated loot spawns ought to be updated).
If it defaults to 100, what would a value of 10000000 do? If the code multiplies the chance AFTER doing a 1 in X calculation it won't do anything, but if the code multiplies X with the chance to do the 1 in X calculation it would virtually guarantee the spawn. Again, MAPGEN.md doesn't provide any insight.

**Comment by watcherPlayer** [comment]
Why do you need "mapgen" at all if it doesn't say anything?!

**Comment by PatrikLundell** [comment]
If @watcherPlayer refers to MAPGEN.md, the documentation contains a fair bit of useful info, but it falls short in this particular regard. Of course, you're free to update it to cover this as well, if you're able to.

**Comment by watcherPlayer** [comment]
I'm sorry if I offended you, but this is a sore topic in a large staff of programmers, some comply and fill out, others do nothing, and here is the same problem...

**Comment by PatrikLundell** [comment]
There is no staff of programmers. This is an unpaid volunteer project.
If you've ever written documentation you'd know it's not easy to balance between repeating the same basic stuff over and over on the one hand, and skipping "obvious" info that might not be obvious to the beginners on the other. In this document the same info is repeated over and over because it's repeated in sections using the same basic building blocks, so you can get to the section you're interested in to get the info, but on the other hand you can't put all the details everywhere. The document can probably be improved by someone both capable of writing good documentation and also knowledgeable about the stuff in it.

I'm not offended, but I'm annoyed by the rapid inference of "something isn't documented properly" to "the documentation is completely useless".

**Comment by watcherPlayer** [comment]
ok

**Comment by Night-Pryanik** [comment]
> Does the value default to 100 or does it mean mandatory spawn?

Both, as value of 100 is a guaranteed spawn.

**Comment by PatrikLundell** [comment]
100 is only a guaranteed spawn if the spawn rate isn't reduced (unless there's some special code that excludes the value 100 from being subjected to the spawn rate multiplier). Issues with reduced spawn rate removing "guaranteed" spawns is the whole issue with this report.

**Comment by IdleSol** [comment]
The main problem, is the lack of the `MISSION_ITEM` flag on items
- https://github.com/CleverRaven/Cataclysm-DDA/issues/71528#issuecomment-1949935532

**Comment by Night-Pryanik** [comment]
Anyway, this issue is fixed by #76751.

**Comment by PatrikLundell** [comment]
@IdleSol :
Not really. The flag can only be used for items uniquely intended for a mission. There's also a need for guaranteeing the presence of mission target items at target locations even if it's a mundane item (like Alonzo's "special pants".).

**Comment by IdleSol** [comment]
These are those items. They even have a separate entry. They're not standardized templates.
