### ISSUE TITLE
"Sneaking"; Or, Acting Like a Zombie

### ISSUE THREAD

**Issue by dominic-dimico** [CleverRaven/Cataclysm-DDA#74582]
### Is your feature request related to a problem? Please describe.

I like the existing sneak mechanics, using cover and peek to move around stealthily.  But then it got me thinking.  How exactly is it that I attract the attention of zombies from far away in broad daylight?  The only plausible explanation is that they have the same visual recognition capabilities they did before as humans: _they recognize me by sight_ as a human.  They're too far away to smell me, too far away to hear me; and supposing they had some sort of blob-enabled psychic power or additional sense, wouldn't they have been tracking me with that already?  It seems logical that if I were to dress up as a zombie (with make-up and tattered clothes) and stagger by them far away enough from them not to catch my scent, that I should be able to move through to the extent of my _social_ skill, which covers acting.

### Solution you would like.

Let "stagger" be a new move option.  It lets you initiate your zombie act, moving as if you were walking like a zombie (i.e. you have the same cover, but move at the speed of a zombie).  You pull it off better the farther away you are, the higher your social skill, and the more you dress like a zombie (filthy or tattered clothes).  Scent gives you away.  The character could develop a proficiency in Zombie Mannerisms to boost their efforts, by watching zombies move around a lot in the absence of combat.  The risk of being discovered while wearing filthy, tattered clothes is balanced against the scouting benefits of skulking around as a zombie.

### Describe alternatives you have considered.

I really think the existing sneak mechanics (crouching, hiding behind furniture) are both fun and faithful to reality and I wouldn't change them one bit.  

There may be alternatives for accomplishing something like sneaking in this way, but hear me out on why acting would be a good way to handle it.  The game is very STEM focused, meaning you're rewarded for gathering scientific and technical knowledge.  Art is devalued somewhat, relatively speaking; the arts relegated to hobbies that boost morale.  But many players are artists, and everyone likes representation.  We even have an in-game example of why the art of acting in particular should not be underestimated: a capable actor (looking at you, Mi-Go) can even outfox a scientist (you, the player)!

It would be interesting to make acting its own thing, and it would provide another use for the _social_ skill.

### Additional context

In real life, I probably would experiment with this approach before ever engaging in battle with a zombie, if I had the option.

**Comment by PGR-14** [comment]
It seems great, but perhaps we could either replace Zombie mannerisms w/ Zombie biology, have Z Bio as a supplement to it, or do it as you said

**Comment by kevingranade** [comment]
Nope, this is a very movie logic solution and I'm not interested in it being in the game.
