### ISSUE TITLE
Arrows/Bolts are Extremely Brittle and Have Very Low Chance of Recovery

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#74655]
### Describe the bug

Due to some recent changes to game mechanic (some speculate due to this: https://github.com/CleverRaven/Cataclysm-DDA/pull/73931 but I lack the skills needed to tell heads from tails in the code) reclaimable projectiles (arrows/bolts) are extremely unlikely to survive a shot, which leads to bows/crossbows being unusable.

### Attach save file

[Addie-trimmed.tar.gz](https://github.com/user-attachments/files/15888757/Addie-trimmed.tar.gz)

### Steps to reproduce

Here is a test.
1) A character has the weakest bow in the game (survival bow) so arrow breaking another arrow is extremely unlikely and 20 wooden broadhead arrows (one of the sturdiest types of arrows, having a "decent" chance of remaining intact)
![fl001](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/506906ea-824f-426e-9799-f3a43862da03)
2) First, let's try shooting an imaginary target (as far as I can understand, the practice target is not material and an arrow actually can not collide with it).
![fl002](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/dd0f3003-f6e8-41b0-b158-c86431f3f54d)
3)After 20 shots only 3 arrows remained!
![fl003](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/c9ec143d-377a-4d09-abc7-fc86aa367b2c)
4) Now, with another 20 arrows let's try a "living" target…
![fl004](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/fc36d950-bc13-4b5a-8aa3-3a03f94be6c8)
5) One dummy "dead" and another one "wounded" (alas, could not get an arrow to embed into them) the result is marginally better. Only 5 arrows remain.
![fl005](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/35a22620-775f-4d08-a541-a151b3404228)

### Expected behavior

I expect arrows to be as sturdy as they were before the changes: roughly 18-19 wooden broadhead arrows remaining intact out of 20 shot.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-06-18-0730 d3ae4fd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
/Confirmed

I have noted the very low survivability of arrows as well. The weird thing is that when I started (a week or so ago) starting carbon fiber arrows usually survived the impact, as the wooden broadheads I found also survived with a reasonable frequency (about the same as in earlier sessions), but then I started to shoot enemies at point blank, resulting in critical hits, and they (the arrows, not the enemies) started to disappear on impact most of the time. I'm very occasionally able to recover a second tier arrow (crude-> makeshift?), but currently I'm expecting them all to be lost on impact, so they have to count. Half the day fighting, and the other half making new arrows.

**Comment by kevingranade** [comment]
Yes it looks like #73931 is the culprit, this is the pertinent change.
```
- !one_in( n.value() );
+ x_in_y( ammo->recovery_chance, 100 );
```
which is a lot easier to understand, but the chance values needs updating.
The "worst" recovery chance previously was "2", which means 2 - 1 / 2, i.e. 50%, now "recovery_chance: 2" means 2%, which is clearly much worse.
