### ISSUE TITLE
Add tags "problem in work" and "problem without owner"

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#74653]
### Is your feature request related to a problem? Please describe.

A small problem is bothering me. I'm creating posts describing a bug. For some reason, I personally can't fix them. But only I know about it. How can I show other people that they can take on the task of fixing these bugs?

Or how can I show that I am already working on this bug? That someone else isn't doing the same work I'm doing? And just ask me if I need help and with what?

### Solution you would like.

I propose to add two new tags:

1. "Problem without owner" or any other variant (my English is very bad). Set automatically when creating a bug report message. Or automatically with the addition of a confirmation tag (S2).

This will add convenience as you can sort topics by label. If you are looking for problems that no one is working on.

2. "Problem in work." (Maybe there's a translation problem here. A label to indicate that someone has taken on the task of fixing the problem or implementing the idea). It can be set by anyone (if possible). This tag automatically overrides the "problem without owner" tag. And since you have to create a post to set this tag, you can see at a glance who has taken care of the problem.

It can also be used in posts with suggestions for new ideas. And showing suggestions that someone is working on.

### Describe alternatives you have considered.

To write in every post, "I'm not working on this proposal."

### Additional context

I'm not working on this proposal

**Comment by GuardianDll** [comment]
For p1, any issue is considered to have lack a person assigned, unless said assigned person write in comment "I'm gonna bite it" or assign the bug using github functionality (besides, there is a lot of issues, that are assigned, but author never fixed them)
For p2, see p1

**Comment by Qrox** [comment]
> unless said assigned person write in comment "I'm gonna bite it"

That sounds like where a command to assign oneself could come in handy. It will also make searching for unassigned issues easier.

> besides, there is a lot of issues, that are assigned, but author never fixed them

Perhaps if the assignee does not update the issue for a long time, their assignment should be automatically removed.

**Comment by anothersimulacrum** [comment]
> A small problem is bothering me. I'm creating posts describing a bug. For some reason, I personally can't fix them. But only I know about it. How can I show other people that they can take on the task of fixing these bugs?

This is implicit in an issue. If you can fix it, you make a PR.

> Or how can I show that I am already working on this bug? That someone else isn't doing the same work I'm doing? And just ask me if I need help and with what?

A comment works, as does a draft PR.
