### ISSUE TITLE
Add way for EoCs to interact with item battery power

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#74657]
### Is your feature request related to a problem? Please describe.

MoM has an electrokinetic power called Electron Overflow. What it is supposed to do is that you can passively charge all devices on your person slowly, and in order to do this mechanically I had to make it a piece of integrated armor with a UPS. This has two problems:

1. It can only charge UPS-compatible devices, when it should be able to charge any device with a rechargeable electrical battery.
2. You can plug a cable into the abstract psionic power because I had to make it a physical device in your inventory for the effect to work, and thus recharge your car, your bionic power, or anything else you can plug the other end of the cable into.

Also, UPS is currently on thin ice, so it'd be nice to have another way to accomplish the same goal. 

### Solution you would like.

Some way to check item battery charge and manipulate it through EoCs, maybe through an EoC effect designed to run after a yet-to-be-added `u_run_inv_eocs` parameter.

### Describe alternatives you have considered.

Making it a pseudo_item UPS was the other alternative

**Comment by zachary-kaelan** [comment]
There are `val` [variables](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#list-of-character-and-item-aspects) for `power`, `power_percentage`, and `power_max`, the first two of which are assignable. It says "bionic power", but `u_run_inv_eocs` returns the items as "NPCs", and I'm assuming it's interpreted as the battery charge of the item, but I could be wrong.

**Comment by zachary-kaelan** [comment]
> There are `val` [variables](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md#list-of-character-and-item-aspects) for `power`, `power_percentage`, and `power_max`, the first two of which are assignable. It says "bionic power", but `u_run_inv_eocs` returns the items as "NPCs", and I'm assuming it's interpreted as the battery charge of the item, but I could be wrong.

I went and double checked and I was wrong.

**Comment by emixa-d** [comment]
> You can plug a cable into the abstract psionic power because I had to make it a
> physical device in your inventory for the effect to work, and thus recharge your car,
> your bionic power, or anything else you can plug the other end of the cable into.

I thought that was intentional, like, the psion is interacting with the charging port of electric car or bionic power, acting as an electrical battery constructed by thought, but instead of a chemical battery it's a psionic battery (lasting as long as concentration lasts).

I didn't know this works on cars and bionics too -- I thought this (hypothetically) not working is the reason why the "recharge power grid" is a separate thing from "Electron Overflow".
