### ISSUE TITLE
Claws vs Retractable Claws

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7465]
Is -3 visibility and -1 ugliness with completely identical everything else really worth making another trait? Retractable claws sound like a big improvement over common ones. May I suggest either upgrading retractable claws (more damage?) to represent that your claws can be bigger and deadlier without getting in the way if you can retract them, or to nerf basic claws and add encumrance or no-gloves penalty?

**Comment by Soyweiser** [comment]
Think this issues can be closed now with the mutation categories, and claws now changing into retractable claws
