### ISSUE TITLE
problem with blankets

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#74685]
### Describe the bug

quite recently there was a quest in the game to "Find 25 blankets", at some point something happened to the blankets and they began to be called differently (I collected blankets for the quest and now they are called “floral blanket”)

the blanket recipe disappeared from the recipe menu (shift + 7), and the “floral blanket” recipe did not appear, how can I complete this quest now? 

### Attach save file

none

### Steps to reproduce

none

### Expected behavior

Help?

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: cdda-experimental-2024-06-15-0455 d5efb05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by GuardianDll** [comment]
They just got a variants, quest do not care would it be floral, cartoon or geometric blanket

**Comment by watcherPlayer** [comment]
thank you for the clarification
