### ISSUE TITLE
it is impossible to make 50 lime mortars

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#74684]
### Describe the bug

When making 50 lime mortars on a workbench, the recipe disappears

### Attach save file

[DarkMagenta-trimmed.tar.gz](https://github.com/user-attachments/files/15911342/DarkMagenta-trimmed.tar.gz)
everything is ready to produce 50 units

### Steps to reproduce

try making 50 lime mortars

### Expected behavior

Help?

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: cdda-experimental-2024-06-15-0455 d5efb05 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries]
]

**Comment by watcherPlayer** [comment]
It seems to me that rarely anyone looks into “stale”, so it’s good that this topic comes up again

**Comment by NetSysFire** [comment]
There are simply very few triagers. All of us are volunteers, too. You can help by reproducing issues you care about and reporting the results in the comments.

**Comment by Maleclypse** [comment]
Closing this one as confirmation of the linked issue this is duplicating.  Moving it from things targeted by stalebot to confirmed bug.  This is why it's better to confirm a stale issue and remove it from stalebot targeting than keep recreating it.
