### ISSUE TITLE
Road segments generating sideways

### ISSUE THREAD

**Issue by gry997** [CleverRaven/Cataclysm-DDA#74698]
### Describe the bug

Road segments really do be spawning sideways (incl. bridge segments)

### Attach save file

[Trona-trimmed.tar.gz](https://github.com/user-attachments/files/15921343/Trona-trimmed.tar.gz)

### Steps to reproduce

It do be generating sideways though

### Expected behavior

Str8 road 

### Screenshots

![cddaroadbug](https://github.com/CleverRaven/Cataclysm-DDA/assets/173421338/7fc2c26c-6b78-4aa1-8421-94ebaf091337)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: c0fa700 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
Closing as duplicate. As the duplicated issue has been resolved, you should update to the version with the fix when the build is available for your system.
