### ISSUE TITLE
Unable to generate a valid starting location : Townhouse[sloc_retirement_community]

### ISSUE THREAD

**Issue by DaveChini** [CleverRaven/Cataclysm-DDA#74694]
### Describe the bug

`Unable to generate a valid starting location Retirement Community - Townhouse [sloc_retirement_community] in a radius of 3 overmaps, please report this failure.`

Generated new world and random start, got this during world build phase.

### Attach save file

N/A

### Steps to reproduce

Generated new world and random start, got this during world build phase. Starting location is Retirement Community - Townhouse

### Expected behavior

Game starts, retried a couple of times and couldnt get it to work.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65976856/2be12fe3-fceb-415a-befa-3d267e3a7abb)

### Versions and configuration

GameVersion: c0fa700

**Comment by LyranRenegade** [comment]
what city-size u used?

**Comment by Night-Pryanik** [comment]
Duplicate of #35376.
