### ISSUE TITLE
Map extras spawning on previously visited tiles, and monster spawns higher than usual

### ISSUE THREAD

**Issue by thomasmackrell** [CleverRaven/Cataclysm-DDA#74697]
### Describe the bug

I'm not sure if it's a bug as much as it is just a new feature, but I was asked to submit a report so I'm doing so. 

I'm getting map extras spawning on tiles that I have had pass through my reality bubble already, which I don't believe has happened before. In the save file I'm submitting, some web spinning spiders have spawned on a swamp tile a few spaces south of the evac shelter spawn at Level 0, -1'61, 1'43. I've also got a couple of ponds spawning in swamp tiles one tile Northwest and another pond spawning a tile north of that pond. -1'53 1'39 also spawned a mass grave in the Isherwood farms, in front of the outbuilding that Luke Isherwood resides in. 

Monster spawning also seems to be occurring more frequently than usual as well-I ran into a thing and a polyp southwest of the evac shelter spawn. 

### Attach save file

[Whately-trimmed.tar.gz](https://github.com/user-attachments/files/15920785/Whately-trimmed.tar.gz)

### Steps to reproduce

The map extra spawning should reproduce if the time ingame advances.

### Expected behavior

I expected for the game world not to spawn any extras after I visited them. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3737 (22H2)
- Game Version: cdda-experimental-2024-06-19-1857 e4840ea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
@PatrikLundell i ping you because it's not the first time i get this report, and i highly suspect it to be related to #74169

**Comment by PatrikLundell** [comment]
/confirmed

I've seen a pond in the save that wasn't on the overmap before and didn't appear when I reloaded the save.

I'll try to address it.
