### ISSUE TITLE
Game freeze when it saves

### ISSUE THREAD

**Issue by TemplarPraisingTheSun** [CleverRaven/Cataclysm-DDA#74708]
### Describe the bug

i had the freeze on save problem ever since i first played on steam, usually it would save fine for about 30 minutes before freezing in the middle of a save.

 I was told that CDDA on steam wasnt up to date and i gone to pick the github 0.G stable and made a folder on my desktop for the game, both had the same problem. Then i tried the stable candite again on a desktop folder, same problem again. In a last desperate attempt i made a new folder inside my PC user folder to put the game in and activated autosave with an interval of 10 minutes, i had no problems at all when saving for 9 hours, then i saved and quitted to make a backup save just in case. Then i re oppened CDDA and the very first autosave froze.

### Attach save file

[New England Save Before.zip](https://github.com/user-attachments/files/15932720/New.England.Save.Before.zip)

[New England.zip](https://github.com/user-attachments/files/15932696/New.England.zip)

### Steps to reproduce

simply load in the New England Save before and save the game in whichever way, it is supposed to freeze. the New England save is likely corrupted as it is only partially saved since it froze and i had to manually stop the game but it should also freeze when saving

### Expected behavior

I expected the game to not freeze since it seemed to be fine for a whole 9 hours

### Versions and configuration

Windows 11

**Comment by RenechCDDA** [comment]
Save issues like this are essentially always a permissions issue. Don't put cdda in any directory protected by your filesystem (e.g. C:\Users). Put it somewhere neutral like C:\Games\.

I have no issues loading or re-saving either of the provided save on experimental beb71d9.
