### ISSUE TITLE
Black Tea should be caffeinated

### ISSUE THREAD

**Issue by MochaModifier** [CleverRaven/Cataclysm-DDA#74717]
### Is your feature request related to a problem? Please describe.

When I am roleplaying a caffeine fiend; black tea should be a viable option to satisfy that craving in place of energy drinks or coffee (whether because of scarcity, circumstance or preference).
Currently, black tea doesn't seem to satisfy caffeine withdrawals; and it's drinks don't list caffeine as a nutritional value.

### Solution you would like.

I would like Black tea to have half as much caffeine as coffee per serving. 
Black tea, which the game describes in game as being 'Camellia sinensis', is an actual shrub species which produces a caffeinated tea. 
The USDA lists Camellia sinensis as having 47mg of caffeine per 8 fl oz; which is roughly half as much as coffee.

### Describe alternatives you have considered.

None, this is a request to add missing caffeine to black tea's nutritional value. If a tea is decaffeinated, it should be denoted as such. 

### Additional context

Decaff black tea (Camellia sinensis) would not occur naturally, if farming tea becomes an option; decaff coffees and teas are the product of chemical processing.
Plants produce caffeine as a deterrent against pests and herbivores.

**Comment by anoobindisguise** [comment]
It actually does reduce sleepiness and give you stimulants, so all that's missing is the caffeine addiction potential.
