### ISSUE TITLE
Unary "-" operation for typed relative coordinates missing

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#74721]
### Is your feature request related to a problem? Please describe.

When trying to typify coordinates, I ran into the problem that there is no unary "-" operation for typed relative coordinates. Thus, converting
`    tripoint dp_veh = -u.grab_point;`
into
`    tripoint_rel_ms dp_veh = -u.grab_point;`
when grab_point is converted into tripoint_rel_ms doesn't work (it can be worked around, but that's not reasonable, given how many locations are likely to be affected).

### Solution you would like.

The availability of a unary "-" operation for relative (tri)points ('relative' implies they're also typed).

### Describe alternatives you have considered.

I tried to do it myself by copying and adjusting the "-=" operator in coordinates.h, but that blew up substantially with messages of "'r': identifier not found" in coordinates.h from every existing usage of the binary "-" operator.

### Additional context

It appears there's a need for more competence in template wrangling to pull this off than just the "copy what's present and tweak a little" to get the compiler to understand that the binary and unary operations aren't the same thing and their profiles are different for that exact reason.

Of course, it might also be the case that the template functionality is too promiscuous to make this possible, and that might be why the unary operator wasn't provided when the rest of the operators were set up.

**Comment by RenechCDDA** [comment]
>I tried to do it myself by copying and adjusting the "-=" operator in coordinates.h, but that blew up substantially with messages of "'r': identifier not found" in coordinates.h from every existing usage of the binary "-" operator.

You got this on a branch? I might be able to put something together.

**Comment by PatrikLundell** [comment]
No, but I tried to quickly recreate it, although it's not quite the same, but still failing:
I entered this into coordinates.h:
```template<typename Point, origin relative, scale Scale>
constexpr inline coord_point<Point, origin::relative, Scale>& operator-(coord_point<Point, origin::relative, Scale>
    & me )
{
    me.raw() = -me.raw();
    return me;
}
```that compiles. However, trying to use it by adding:
```
    tripoint_rel_ms alpha = { 1, 2, 3 };
    tripoint_rel_ms beta = -alpha;
```
to a "random" location such as  the top of mapgen.cpp operation add_spawn causes the editor to think it's OK, but the compiler to reject it with "
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2675	unary '-': 'tripoint_rel_ms' does not define this operator or a conversion to a type acceptable to the predefined operator	Cataclysm-lib-vcpkg-static	C:\Cataclysm-DDA\src\mapgen.cpp	6807" and
"Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2088	built-in operator '-' cannot be applied to an operand of type 'tripoint_rel_ms'	Cataclysm-lib-vcpkg-static	C:\Cataclysm-DDA\src\mapgen.cpp	6807"
where 6807 is the line on which beta is defined.
