### ISSUE TITLE
Stop removing guns that could fit at the Gun Show, and fix existing guns and the months long bugs where interchangeable barrels on rifles aren't spawning on them at Gun Stores.

### ISSUE THREAD

**Issue by KrunkySmokin** [CleverRaven/Cataclysm-DDA#74720]
> > > Maybe fix existing guns and the months long bugs where interchangeable barrels on certain rifles aren't spawning there instead of removing guns, guns that could fit in at a gun show. Gun shows where _collectors_ bring their guns to show off and trade. Having a gun show and having that "it has to be prominent enough in New England" rule for gun inclusion makes no sense.
> > 
> > 
> > We can both fix the bugs and remove the guns at the same time. I already explained how guns can be rare and still meet the requirements for inclusion, justifying their presence at a gun show.
> 
> None of what you've said above explains how they can also meet the requirements for inclusion of a gun if rare because by virtue of them _being rare_, they're being removed from the game by you. There is a completely viable place they could be found instead.

As mentioned above completed PRs are not the place to be discussing this.  If you ignore requests to change the venue of a conversation again in the future it could result in removal of your ability to comment on this repo.

_Originally posted by @Maleclypse in https://github.com/CleverRaven/Cataclysm-DDA/issues/74636#issuecomment-2183588582_
            Instead of getting angry at me and telling me to redirect conversation when no one directed it at me or told me before and threaten to remove my ability to comment on a repository, fix the gun bugs your supported Pull Requests create that fester and sit around for months instead of removing guns where a perfectly viable spawn for them exists.

**Comment by GuardianDll** [comment]
I can't understand your message, can you please rewrite it?

**Comment by Maleclypse** [comment]
> ```
>           > > > Maybe fix existing guns and the months long bugs where interchangeable barrels on certain rifles aren't spawning there instead of removing guns, guns that could fit in at a gun show. Gun shows where _collectors_ bring their guns to show off and trade. Having a gun show and having that "it has to be prominent enough in New England" rule for gun inclusion makes no sense.
> ```
> 
> > > We can both fix the bugs and remove the guns at the same time. I already explained how guns can be rare and still meet the requirements for inclusion, justifying their presence at a gun show.
> > 
> > 
> > None of what you've said above explains how they can also meet the requirements for inclusion of a gun if rare because by virtue of them _being rare_, they're being removed from the game by you. There is a completely viable place they could be found instead.
> 
> As mentioned above completed PRs are not the place to be discussing this. If you ignore requests to change the venue of a conversation again in the future it could result in removal of your ability to comment on this repo.
> 
> _Originally posted by @Maleclypse in [#74636 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/pull/74636#issuecomment-2183588582)_ Instead of getting angry at me and telling me to redirect conversation when no one directed it at me or told me before and threaten to remove my ability to comment on a repository, fix the gun bugs your supported Pull Requests create that fester and sit around for months instead of removing guns where a perfectly viable spawn for them exists.


Not angry, just letting you know that you need to read the comments directed at you.
https://github.com/CleverRaven/Cataclysm-DDA/pull/74636#issuecomment-2182955186

**Comment by RenechCDDA** [comment]
Omnibus complaint issue which is also unreadable. This is not productive, so I am going to close it and lock it further participation.

But, *just for your sake*, to address some points.

> Stop removing guns that could fit at the gun show

No. The gun show is not a dumping ground for random things. The idea that we should shove random stuff into it is disrespectful to the people that added that content and detracts from the game's setting. 

There is one existing 'unique' gun that can spawn there **as part of a quest**. Generally speaking, rare guns that are not commonly found in New England can exist as part of such content, e.g. the existing kord quest. This is not blanket permission to add random things and have an empty quest for "find the checklist of rare guns I wanted to add!".

>and fix existing guns and the months long bugs where interchangeable barrels on rifles aren't spawning on them at Gun Stores.

Nobody has any idea what you're talking about, but if you've found a bug please open a bug report or add to existing ones. Bugs get fixed as we are able to do so, you are welcome to help.
