### ISSUE TITLE
Crash when deconstructing brazier

### ISSUE THREAD

**Issue by axus** [CleverRaven/Cataclysm-DDA#74775]
### Describe the bug

Deconstructing a brazier causes a full crash in experimentals.  Constructing is OK and I've deconstructed other things.
Tried turning off sound and tilesets.
Tried on different games.

versions:
cdda-experimental-2024-06-22-1628 a88ea32
June 24, 7da20bc

### Attach save file

[debug.log](https://github.com/user-attachments/files/15965597/debug.log)

### Steps to reproduce

Go to a brazier.
Deconstruct furniture and select brazier.
It crashes.

### Expected behavior

Not crashing.

### Versions and configuration

OS:  Windows 11
English
Tilesets on or off
Sounds on or off

**Comment by PatrikLundell** [comment]
/Confirmed

Using a master downloaded and compiled earlier today.
