### ISSUE TITLE
Moving in an inactive exoskeleton is less exerting than moving in powered medium or light exoskeletons

### ISSUE THREAD

**Issue by Regilith** [CleverRaven/Cataclysm-DDA#74785]
### Describe the bug

`MOVEMENT_EXERTION_MODIFIER` values seem to be incorrect for the new Exoskeletons. The powered light and medium exoskeletons (mk3 & mk2 respectively) are more exerting to move in than them being inactive. Only the powered heavy exoskeleton (first generation / least advanced) is less exerting. Numbers below.

Gameplay wise, this means that it's more efficient to turn the suit _off_ when moving to conserve your calories, when using the mk2 or mk3 suits.

### Attach save file

N/A

### Steps to reproduce

1. Create a new default character
2. Spawn in combat exoskeleton mk1, mk2, mk3, and heavy batteries
3. Reload, activate, and wear each.
4. Observe as all mk2 powered, mk3 powered, and inactive all are 'Brisk' Activity level, only mk1 powered is 'Moderate'
5. Edit the `MOVEMENT_EXERTION_MODIFIER` values for any suit in `data/json/enchantments.json`, then test again. Setting it to 2.0 causes Activity level to massively increase, and 0.1 only 'Light', so bigger number = more exertion.

### Expected behavior

I would expect that powering all the exoskeletons would make them _less_ exerting to move about in it, not more.

Intuitively, powering the exoskeleton should cause it to be less exerting, and more advanced / later generation / lighter suits should be less exerting.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 24.0.2; Codename: Wynsdey; 
- Game Version: cdda-experimental-2024-06-25-1641 50f8ab2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

`"combat_exoskeleton_inactive" > [ { "value": "MOVEMENT_EXERTION_MODIFIER", "multiply": 0.5 }`

`"combat_exoskeleton_heavy_active" > [ { "value": "MOVEMENT_EXERTION_MODIFIER", "multiply": 0.4 }`

`"combat_exoskeleton_medium_active" > [ { "value": "MOVEMENT_EXERTION_MODIFIER", "multiply": 0.6 }`

`"combat_exoskeleton_light_active" > [ { "value": "MOVEMENT_EXERTION_MODIFIER", "multiply": 0.8 }`

Powered heavy suit is least exerting, then inactive suit, then powered medium suit, then powered light suit.

**Comment by BalthazarArgall** [comment]
Don't hesitate to ping me next time you find something wrong with something I'm responsible for. I'm very active and always happy to fix my stuff.

**Comment by Regilith** [comment]
Will do!
