### ISSUE TITLE
Mobile terminal issue (again)

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#74809]
### Describe the bug

The terminal window on non fullscreen is not showing up correctly

### Attach save file

N/A

### Steps to reproduce

Open the game with NO force fullscreen and the window should appear small on the top left

### Expected behavior

Window shows up correctly

### Screenshots

![Screenshot_20240627-125625](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/b0ab8ea7-e8b0-4b6e-97e4-17fdddc3f641)

### Versions and configuration

Android. Game version: 0.H release candidate 2024-06-27-1418

### Additional context

This happened before. Maybe the same issue can have the same fix?

**Comment by Srcwya** [comment]
#72499 fixed this a while ago, maybe the same issue?

**Comment by Srcwya** [comment]
Fixed on the latest experiemental!

**Comment by jfitie** [comment]
But not in the latest 0.H release candidate.
