### ISSUE TITLE
(World Building) Only 1 TOTAL CONVERSION mod can be choose when creating new world

### ISSUE THREAD

**Issue by TheWallOnFire** [CleverRaven/Cataclysm-DDA#74820]
### Is your feature request related to a problem? Please describe.

It is not a bug but we still need this to limit the player's choice. 2 or more may result the game.

### Solution you would like.

Can only choose 1 TOTAL CONVERSION mod

**Comment by Srcwya** [comment]
This seems pretty unneeded?

**Comment by TheWallOnFire** [comment]
That's what I was thinking too until I put 3 of them together. Of course the game crashes. But only when I try to load the world this bug. So we need a way to control the number of mods added to our world when the number of mods extends.

**Comment by Srcwya** [comment]
> That's what I was thinking too until I put 3 of them together. Of course the game crashes. But only when I try to load the world this bug. So we need a way to control the number of mods added to our world when the number of mods extends.

Then just.. give a warning message that too many TCMs may break the world!

This just seems unnecessary in my opinion. What if one day there is a TCM that can be played with another TCM?
That would be like not mixing 2 substances because they taste bad when mixed, ignoring every other that may be created or exist already.

Besides theres nobody complaining that they cant play two total conversions in the same world, so why change that?

**Comment by TheWallOnFire** [comment]
> > That's what I was thinking too until I put 3 of them together. Of course the game crashes. But only when I try to load the world this bug. So we need a way to control the number of mods added to our world when the number of mods extends.
> 
> Then just.. give a warning message that too many TCMs may break the world!
> 
> This just seems unnecessary in my opinion. What if one day there is a TCM that can be played with another TCM? That would be like not mixing 2 substances because they taste bad when mixed, ignoring every other that may be created or exist already.
> 
> Besides theres nobody complaining that they cant play 2 (or more) total conversions in the same world, so why change that?

That will work too, I hope so. So my problem is not understanding how to add mod to the world. Let's make a tutorial about making world and choosing mod INGAME then, like "press F1 for more information". Thank you for your reply my liege!!

**Comment by ZhilkinSerg** [comment]
It is up to mod creators to provide mod information - whether they are compatible with other mods or not.
