### ISSUE TITLE
Holding my breath

### ISSUE THREAD

**Issue by nigromancer** [CleverRaven/Cataclysm-DDA#74826]
### Is your feature request related to a problem? Please describe.

The PC must be the dumbest mouth-breather because when faced with smoke, noxious gasses or various chemical sprays - they are incapable of closing their mouth and holding their breath. Irl, most children I know are capable of this basic technique. You know, just like when they go swimming and hold their breath underwater. 

### Solution you would like.

Just as I can toggle at will through prone, crouch, walk and run - I would also like for my PC to be able to hold their breath using the same mechanics as when they are swimming underwater.  It could even be added to the same action list... If their breath/stamina runs out then they'll be forced to take a deep breath of whatever surrounds them. Like when underwater... Could be deadly, could be risky fun! 

### Describe alternatives you have considered.

I lack the programming skills but even I could create a magicalysm spell that achieves the same thing but it seems a ridiculous solution given how basic an ability this is. I hold my breath quite regularly when I swim or sprint, and it's been useful for avoiding smoke and unpleasant fumes. In fact, I'm going to hold my breath right now until some wonderful person implements this excellent feature. Here I go... 3... 2... 1....... :)

### Additional context
I do realise that some chemicals affect us via our eyes as well (c.f. tear gas) but keeping one's mouth shut and running does help. Maybe we could also shut our eyes too? Ooh, can we have that too? ;)

**Comment by fairyarmadillo** [comment]
See #66291 and the comments for why this isn't implemented and isn't likely to be any time soon.

**Comment by GuardianDll** [comment]
But #66291 mentions when smoke effect would br divided in two, one responding for eye irritation and another for lungs, it would be within possibility to implement it as automatic action, "if you try to step on the smoke field, you can either stop yourself, or hold your breath and move forward, and get only eye irritation"
Do i read it differently?

**Comment by fairyarmadillo** [comment]
It is very unlikely that someone would want to purposefully inhale smoke, so adding a toggle, option, query, or other UI thing to determine that behavior is probably unnecessary complexity. The thing to do IMO would probably be to make it so you don't get the lungful of smoke effect until you've been in the smoke for a couple of seconds, maybe depending on stamina. That way it's automatic.

That is sort of modeled already via effect intensity and duration stacking up as you stay in the smoke longer, so I don't see a huge need for it, and there are plenty of counterarguments in the linked PR.
