### ISSUE TITLE
Website is broken... Again.

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74836]
### Describe the bug

Stopped giving out releases on the 29th, https://github.com/CleverRaven/Cataclysm-DDA/issues/74562#event-13194640973 https://github.com/CleverRaven/Cataclysm-DDA/issues/73562 https://github.com/CleverRaven/Cataclysm-DDA/issues/71194 are relevant issues, & https://github.com/CleverRaven/Cataclysm-DDA/issues/74006 is the solution.

### Attach save file

N/A

### Steps to reproduce

Go to experimentals on the website

### Expected behavior

For the newest build to be displayed

### Versions and configuration

N/A

**Comment by harakka** [comment]
It isn't broken. Like I already tried to explain to you previously, experimental releases on the website only get updated when all builds in the release succeed. This is on purpose. Currently Android builds are failing.

If you want to get the actual latest release, and not latest _complete_ release, get it from Github releases.

**Comment by PGR-14** [comment]
Oh shit sorry, misunderstood. I didn't mean to inconvenience you.
