### ISSUE TITLE
[Innawoods] mi-go scout tower creates road 

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#74847]
### Describe the bug

Playing on Innawoods, i have noticed after juggling new world a few times, that it tends to spawn a Road, of which one end leads to nowhere and the other end is always a Mi-go Scout tower that is connected by 1 rural road for some reason. the Innawoods readme clearly states to have disabled Road generation. this also causes vehicle to appear on the roads and also generates bridges if necessary. 

### Attach save file

[Hidden Valley-trimmed.tar.gz](https://github.com/user-attachments/files/16044673/Hidden.Valley-trimmed.tar.gz)

### Steps to reproduce

1.Create a World, go with city generation 0 and whatever with the other options
2.Start basic Scenario (In cave)
3.debug reveal the map. if it doesnt appear on the first time, keep revealing more maps beyond the borders, it will show up.

### Expected behavior

Not Spawn roads and bridges as it says in the Innawoods Readme

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-06-28-0827 0dabb58 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Even outside of Innawoods: 
I dont think Mi-go would care if their towers are connected by roads, since they dont seem to have wheeled vehicles that would make use of existing infrastructure

**Comment by MNG-cataclysm** [comment]
I think I know what this is, it's a special scout tower that's used in a mission for the Isherwoods. I believe that I can fix this very quickly.
