### ISSUE TITLE
No linux-tiles experimental builds since 06-27-2024

### ISSUE THREAD

**Issue by Void-Seeker** [CleverRaven/Cataclysm-DDA#74858]
### Describe the bug

No linux-tiles experimental builds since 06-27-2024

### Attach save file

N/A

### Steps to reproduce

1. Try to download recent experimental build for linux with tiles.

### Expected behavior

Build should be present.

### Versions and configuration

N/A

**Comment by Void-Seeker** [comment]
Yeah, of course it's June. Sorry for a typo.

**Comment by andrei8l** [comment]
/confirmed
Include order changed for some reason so the SDL library we need isn't pick up anymore. Maybe this can fix it

```diff
diff --git a/Makefile b/Makefile
index 0dd15eb9fb..fbcaff729b 100644
--- a/Makefile
+++ b/Makefile
@@ -778,7 +778,8 @@ ifeq ($(TILES), 1)
       endif
     endif
   else ifneq ($(NATIVE),emscripten)
-    CXXFLAGS += $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_image SDL2_ttf)
+    CXXFLAGS += $(shell $(PKG_CONFIG) --cflags sdl2)
+    CXXFLAGS += $(shell $(PKG_CONFIG) --cflags SDL2_image SDL2_ttf)
 
     ifeq ($(STATIC), 1)
       LDFLAGS += $(shell $(PKG_CONFIG) sdl2 --static --libs)
```

**Comment by Cupidatis** [comment]
Same with Android builds, #74841 didn't help.

**Comment by harakka** [comment]
Tested andrei8l's proposed solution, didn't work. I looked into this for a bit but couldn't figure out what has changed to break this. First I thought it was related to ubuntu-latest build image moving to a new release but we specifically use 20.4 for the release build, so not that either.

**Comment by andrei8l** [comment]
It worked for me [here](https://github.com/andrei8l/Cataclysm-DDA/actions/runs/9820613519/job/27115403350); it just needed [a bit more work](https://github.com/andrei8l/Cataclysm-DDA/commit/76a777a70b408c86ee7bf29bed8b22220c394e39). If that's too invasive, you can try overwriting the system SDL lib with the one we want

<details>
<summary>Untested</summary>

```diff
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
index 3d00a0b20c..fe19417959 100644
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -219,17 +219,16 @@ jobs:
         if: runner.os == 'Linux' && matrix.mxe == 'none' && matrix.android == 'none' && !matrix.wasm
         run: |
           sudo apt-get update
-          sudo apt-get install libsdl2-dev
+          sudo apt-get install libsdl2-dev libncursesw5-dev libsdl2-ttf-dev libsdl2-image-dev \
+            libsdl2-mixer-dev libpulse-dev ccache gettext parallel
           git clone https://github.com/libsdl-org/SDL.git --branch release-2.0.20 --depth 1
           cd SDL
           mkdir build
           cd build
-          ../configure
+          ../configure --prefix=/usr
           make -j$((`nproc`+0))
           sudo make install
           cp ../LICENSE.txt ${{ github.workspace }}/LICENSE-SDL.txt
-          sudo apt-get install libncursesw5-dev libsdl2-ttf-dev libsdl2-image-dev \
-            libsdl2-mixer-dev libpulse-dev ccache gettext parallel
       - name: Install Emscripten (WebAssembly)
         if: matrix.wasm
         uses: mymindstorm/setup-emsdk@v13
```


</details>

**Comment by ingles98** [comment]
Does anyone have a fork with working Linux x64 builds?

**Comment by NetSysFire** [comment]
If builds are broken again, you can always compile it yourself, although it takes quite a long time (which I experienced just yesterday). Even if you are not on Arch, you have working build instructions with this PKGBUILD: https://aur.archlinux.org/packages/cataclysm-dda-git
