### ISSUE TITLE
Items do not fit into pockets when item length = pocket max length

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#74862]
### Describe the bug

In the insert menu, items with length that should match the pocket's max length are shown as not acceptable by pocket/holster.

### Attach save file

N/A

### Steps to reproduce

1. Obtain a survivor belt and a pillbox (most of survival belt pockets are max length 5 in., pillbox is length 5 in.).
2. Try to insert the pillbox into the belt.
3. Fail.

### Expected behavior

The max length listed for the pocket should be the max length of an item that can fit. Not the length after which the item stops fitting.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-07-01-0638 4f065b5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I expect the issue is with length check using < instead of <= . Or there are some shenanigans with converting from normal units of measurement to FREEDOM units of measurement.

**Comment by natsirt721** [comment]
Its a rounding error. Change your units to metric and check again. The pillbox is 15cm but the utility belt only has 13cm pockets.

**Comment by DalenTalas** [comment]
Closing as "not an issue, will not fix".
