### ISSUE TITLE
The weather is broken (especially winter)

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#74886]
### Describe the bug

Some of weather condition are never appear on the overmap:
- flurries
- snow storm

Other weather condition appear when they aren't possible:
- drizzle with temperature below 0C

### Attach save file

N/A
you can recreate it easily

### Steps to reproduce

1. Spawn yourself a pair of binoculars
2. Debug mutate night vision
3. Skim through the whole year day by day and watch the sky

### Expected behavior

No liquid precipitation when temperature below 0C:
- Snow storm instead of rain storm in winter
- Flurries instead of light drizzle
- Snowing instead of drizzle/rain

### Screenshots

In the middle of the winter (45 day of winter) and midnight temperature is -20C
But it is... drizzle?
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6676374/44065b68-97fc-4ee4-952e-b3dc73bfd7d9)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6676374/6b2bc0de-8fdc-4d76-8649-509b7f751d93)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-06-28-1704 d18e0a0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ZhilkinSerg** [comment]
There is just no temperature condition for a drizzle - https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/weather_type.json

**Comment by ZhilkinSerg** [comment]
Required weather for flurries is flurries itself, which sounds wrong.

**Comment by ZhilkinSerg** [comment]
Required weathers for snowstorm are thunder and lightning, which also sounds odd.

**Comment by vetall812** [comment]
@Ramza13 , could you please take a look?

**Comment by Void-Seeker** [comment]
Drizzle can kinda happen with the surface temperature slightly below zero, which result in ice crust accumulating on all surfaces. That doesn't happen when temperature is -14 °C, of course.
