### ISSUE TITLE
Macro function to "Normalize items"

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#74892]
### Is your feature request related to a problem? Please describe.

This is what an "average" pile of clutter looks like after some "light looting":
![Screenshot_2024-07-04-20-20-55-776_com cleverraven cataclysmdda experimental-edit](https://github.com/CleverRaven/Cataclysm-DDA/assets/27952407/6d56d14c-8ac6-4f85-9b02-c7451d225e07)

Ever since #66260 and #71884 was implemented several containers spawning as loot are automatically assigned a pocket whitelist. The result is multple of the same containers not stacking due to having different pocket settings. If you're trying to do anything with your trash containers you run into massive organization issues because there is no way to "normalize" multiple items into its default state or bulk-reset pocket settings. Pages and pages of individual small plastic bags and pill bottles are extremely annoying to deal with

### Solution you would like.

Some kind of macro function to normalize items in bulk, removing special pocket settings and any other unique identifiers (names, favorites, etc...) to reset them into a default stackable state; This could be a zone, a UI menu, or even integrated into the "unload everything" zone function.

### Describe alternatives you have considered.

Alternatively a setting in the options menu to disable #66260 would also suffice.

**Comment by RenechCDDA** [comment]
This is actually just a symptom of #73216
