### ISSUE TITLE
Failed to read from "..." Expected a string, got null

### ISSUE THREAD

**Issue by meelock** [CleverRaven/Cataclysm-DDA#74925]
### Describe the bug

Occasionally my game gets a strange form of corruption where a map fails to load and gets regenerated with a different variant, destroying everything there. This has happened twice in two different games.
The massive log is below.

### Attach save file

[!Rifle-trimmed.tar.gz](https://github.com/user-attachments/files/16114477/Rifle-trimmed.tar.gz)

### Steps to reproduce

1. Load game
2. Try to gateway using ] -> N to Home
3. Home is corrupted.

### Expected behavior

I would expect a proper loading of my home location.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: f45ceda [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Dorf Life [Dorf_Life],
    Tankmod: Revived [Tankmod_Revived],
    Blazemod - Vehicle Additions Pack [blazemod],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Translate Complex Dialogue [translate_dialogue],
    Railroads [railroads],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks]
]

### Additional context

[Corruption.txt](https://github.com/user-attachments/files/16114484/Corruption.txt)

**Comment by meelock** [comment]
May be a variant of https://github.com/CleverRaven/Cataclysm-DDA/issues/71859

**Comment by Fosheze** [comment]
/confirmed

I have been getting this error repeatedly. My game info is below. I'll see if I can replicate it with no mods in use later.

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-07-04-1645 bf080d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Fosheze** [comment]
I just verified it with only DDA loaded.
Steps to reproduce:
1. Find and approach a bridge minefield. (it works with best with this map extra but I have seen it with other extras as well)
2. Travel several overmap tiles away so the minefield unloads. (I just debug teleported around for a bit)
3. Re-approach the initial bridge minefield on foot. (teleporting may trigger the error too but I didn't try it)
4. Observe error mentioned above and the map extra being partially changed to a different one.
5. If the map extra didn't change and no error was encountered then try repeating the above steps.

**Comment by meelock** [comment]
Secondary message that occurs after the first:
DEBUG    : submap (1266,-106,-1) was already loaded

 FUNCTION : deserialize
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapbuffer.cpp
 LINE     : 329
 VERSION  : bf080d9

**Comment by Dragmire2** [comment]
I have also been getting this repeatedly in the last two days, across different saves. Usually at my base.

<img width="1920" alt="Untitled1" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/104854343/465539bc-3c01-41c2-beb3-b085c384daad">
<img width="619" alt="Untitled2" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/104854343/4725b28b-d331-4a59-887a-d1915ba1feb4">

**Comment by meelock** [comment]
Closed via https://github.com/CleverRaven/Cataclysm-DDA/commit/973f6a9b57d456fb97e9070391940ffeb762de66
