### ISSUE TITLE
Save game fails to load areas with constructed firewood source

### ISSUE THREAD

**Issue by Zynnq** [CleverRaven/Cataclysm-DDA#74926]
### Describe the bug

Loading a save produces errors when there is a user constructed tr_firewood_source. Ignoring the error results in affected map parts regenerating.

### Attach save file

[Cobbtown-trimmed.tar.gz](https://github.com/user-attachments/files/16114491/Cobbtown-trimmed.tar.gz)

### Steps to reproduce

Issue does not seem to be mod related (reproducible with base "Dark Days Ahead [dda]" mod only)

1. Create World.
2. Create Survivor, Evac shelter start.
3. Construct a firewood source or practice target.
4. Save & Quit.
5. Load the save.

### Expected behavior

Game loads in the state it was saved in without errors.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: b8aa71b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Here's the message where the game complains about a null when loading:

[Error Message.txt](https://github.com/user-attachments/files/16114512/Error.Message.txt)

**Comment by meelock** [comment]
Correct, I also set up a firewood spot. Hopefully this gets fixed soon. Thanks!

**Comment by meelock** [comment]
This is probably a side effect of: https://github.com/CleverRaven/Cataclysm-DDA/pull/74876

**Comment by meelock** [comment]
@PatrikLundell I think this might be because of your PR.

**Comment by PatrikLundell** [comment]
/Confirmed

I can see it happening and I can reproduce it, but I currently see no connection to my PR. However, I'm continuing to try to see what's happening.

**Comment by Fosheze** [comment]
If this bug is being caused by traps then #74925 is likely a duplicate. I had noticed the error could be triggered by minefields there and the original poster there had said they set up a firewood source which was likely causing it.
