### ISSUE TITLE
Allow EoCs to check for nearby fields instead of only checking if the player is in a field

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#74944]
### Is your feature request related to a problem? Please describe.

Currently, the only EoC function related to fields checks if the player is right in one

It's very inflexible and there's many potential uses for checking nearby fields such as creating an unhardcoded fear of a field, making a monster buff themselves against a nearby field, or allowing the use of a field the player cannot stand in as part of a crafting recipe

### Solution you would like.

A way to check for nearby fields through EoCs, both for distance from player and field type

### Describe alternatives you have considered.

Hardcoding these effects can be done, but granting more power to EoCs is always a good thing

**Comment by Standing-Storm** [comment]
This would fix a lot of the way Xedra Evolved Salamanders work as well (checking if a fire is nearby).

**Comment by SariusSkelrets** [comment]
Yeah, currently they need to stand right in the fire or heat field for that or else they have to constantly check the temperature to ensure it's hot enough for power gain and other EoCs
