### ISSUE TITLE
[Perks] Can eat despite compressed eating window thanks to other calorie boosters

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#74974]
### Describe the bug

Using things that increase the calories gained from eating allows to gain calories despite having an effect preventing calorie gain

### Attach save file

[TEST PERK-trimmed.tar.gz](https://github.com/user-attachments/files/16169500/TEST.PERK-trimmed.tar.gz)

### Steps to reproduce

1. Debug in the compressed eating window perk and set time at 8:00 AM
2. See that anything you eat got zero calories
3. Install the expanded digestive system CBM
4. See how you can gain calories despite CEW saying that you won't gain any

If using the save:
1. Look at the inventory. See that protein rations are zero-calorie
2. Activate the CBM to install it. See that protein rations grant calories now

### Expected behavior

Not being able to gain calories due to the effect being intended to prevent calorie gain

### Screenshots

![Compressed](https://github.com/CleverRaven/Cataclysm-DDA/assets/68650913/223293f3-a658-44a1-a064-6b4cb0373145)
![Compressed Expanded](https://github.com/CleverRaven/Cataclysm-DDA/assets/68650913/a76e7327-3b3b-446a-a6aa-f53ab3ce3ddb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3737 (23H2)
- Game Version: cdda-experimental-2024-06-11-0319 99ed329 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]

**Comment by GuardianDll** [comment]
It's either a simple fix of making enchantment `-10` instead of `-1` or similarly simple fix of doing the same, but also adding handling for enchantment value lesser than -1 in code. If you check how the game behave when perk has multiplier of -10, then i could push a fix

**Comment by SariusSkelrets** [comment]
I tried making the values -10 and it makes the values negative. I get -3600 calories per ration without the CBM and -3400 with it

**Comment by Standing-Storm** [comment]
I figured it would go below zero, hence the original -1. I would be nice if there were some way to say “no, multiply this by zero after all other calculations” to prevent things like this.
