### ISSUE TITLE
Mutations provided by enchantment silently fail to provide all of their traits

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#74994]
### Describe the bug

Testing something that involved one mutation granting other mutations through enchantment, and the result was that while the mutations were granted and showed up in the @ panel, most of their traits were not.

### Attach save file

[Haswell-trimmed.tar.gz](https://github.com/user-attachments/files/16196953/Haswell-trimmed.tar.gz)

### Steps to reproduce

1) Put the following JSON somewhere in your game so it loads.
```
{
    "type": "mutation",
    "id": "THE_TESTING_MUTATION",
    "name": { "str": "The Container Mutation" },
    "points": 99,
    "description": "You have extra mutations available to you.  Theoretically.",
    "valid": false,
    "starting_trait": false,
    "purifiable": false,
    "enchantments": [
      {
        "condition": "ALWAYS",
        "mutations": [ "FANGS", "BIRD_EYE" ]
      }
]}
```

2) Check the @ panel and see that you have the Fangs and Avian Eyes mutations
3) Check your inventory. You do not have the integrated fangs item that the Fangs mutation should provide.
4) Check your stats. Your perception is 8 and does not gain the +4 that Avian Eyes should provide. 

### Expected behavior

Mutations that show up in your @ panel provide their full benefits (and drawbacks). 

### Screenshots

![image](https://github.com/user-attachments/assets/7133e4c8-2362-4a48-ad33-e056181fa70b)
![image](https://github.com/user-attachments/assets/73948089-d948-4883-bf4e-eb917e2e5d17)
![image](https://github.com/user-attachments/assets/cceb76bf-16cd-43eb-8e1e-e8235bd1401d)

The tilesets read the mutations at least:
![image](https://github.com/user-attachments/assets/da8091c8-1d70-41d3-875c-d14f4e9861fb)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3737 (22H2)
- Game Version: cdda-experimental-2024-07-11-0546 e418d44 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by GuardianDll** [comment]
related: #64118

**Comment by osuphobia** [comment]
I'm trying to fix this, and found:
https://github.com/CleverRaven/Cataclysm-DDA/blob/45999cb2dbaf9f695cbe87b16273304db590ee17/data/mods/Magiclysm/mutations/magical.json#L29
74984 is a typo, right? Then can you point out which part of the enchantment should be deleted, only the one beneath the enchantment mutations?
