### ISSUE TITLE
M110A1 seems too long

### ISSUE THREAD

**Issue by GusMorphism** [CleverRaven/Cataclysm-DDA#75001]
### Is your feature request related to a problem? Please describe.

When examining the length of the HK417 based M110A1, it seemed a little longer than expected.

### Solution you would like.

- Change Longest_side to 899 mm (reported on the Wikipedia page that matches the other physical dimensions)

- Change volume to 3500ml (scaled volume by the same % change in length, couldn't find a formula for gun volume in /doc, assumed it's some kind of modified rectangular prism setup) 

### Describe alternatives you have considered.

- Leave the length as it is. (If my research is incorrect or I am mistaken.)

- Change the length but not the volume, or the volume to something more appropriate. (In case the assumptions I made on gun volume calculation are incorrect.)

- Change the physical dimensions and name to match the M110A2, based on the SR-25 design revamp. (A different gun apparently, but seems like closer to the current length.)

### Additional context

Trying to learn how to contribute here, don't really know how to do a pull request yet, but am hoping to figure out how to do that after this and make a PR that closes this myself, if it is a reasonable change. If I messed up and put this in the wrong place or with the wrong designation I apologize.

Mock-up Change
...
    "volume": "3500 ml",
    "longest_side": "899 mm",
...

Research
[M110A1 wikipedia](https://en.wikipedia.org/wiki/M110A1_rifle#cite_note-peo_smdr_designation-2)
[M110 SASS/M110A2 wikkipedia](https://en.wikipedia.org/wiki/M110_Semi-Automatic_Sniper_System)
[Useful Youtube Video Section](https://youtu.be/JB7LeSwhc28?t=902)
[Unverified Useful Reddit comment](https://www.reddit.com/r/kac/comments/15nf9al/comment/k16ubuj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by kevingranade** [comment]
This is a naming collision, our M110A1 is the M110A1 SDMR and you're quoting stats for the M110A1 CASS. Note the name string "HK417 marksman's rifle".
The pertinent block from wikipedia is "1,019 mm (40.12 in) (M110A1 SDMR with suppressor)", but I believe there's an extra cm in there from measuring the longest diagonal instead of the length along the barrel.

**Comment by GusMorphism** [comment]
> This is a naming collision, our M110A1 is the M110A1 SDMR and you're quoting stats for the M110A1 CASS. Note the name string "HK417 marksman's rifle". The pertinent block from wikipedia is "1,019 mm (40.12 in) (M110A1 SDMR with suppressor)", but I believe there's an extra cm in there from measuring the longest diagonal instead of the length along the barrel.

Sorry, but I used the non-suppressor length because that is the length of the SDMR without the suppressor. In the video I linked with the commentary from the HK program director guy he says the SDMR is just the CASS but with a cheaper stock+optic and some bits of the total kit.

When adding in the suppressor mod on the gun the length is a little longer than 1,019 mm IIRC. I will revert my local game and check the exact length with the in game suppressor the report back for the exact value. But since it's a generic suppressor in game I wouldn't want to make any changes to the length at the moment and it's close enough.

**Comment by GusMorphism** [comment]
Checked in game with 1019 mm length as the base rifle. Currently over-size at 1206 mm.

With 899 mm base it's 1086 mm with the suppressor.

I'm going to go try and hunt in /doc/ to see if I can figure out the longest diagonal. Failing that I will play with ms paint or just and image and a ruler on my screen.

**Comment by GusMorphism** [comment]
Research change (Also edited above):

[Robert Reidsma Introduction](https://youtu.be/JB7LeSwhc28?t=671) - [Program Director, Defense at Heckler & Koch USA](https://www.zoominfo.com/p/Robbie-Reidsma/-1330240802)

[SDMR is CSASS but with cheaper scope and stock](https://youtu.be/JB7LeSwhc28?t=1489)

Will update this post with longest diagonal investigation results later. I think this many of my own comments is excessive at this point.

**Comment by kevingranade** [comment]
You're still making the same mistake,  899mm is not the length because the SDMR DOES have a supressor and DOES NOT have a collapsible stock.

**Comment by GusMorphism** [comment]
As per a conversation with kevingranade on discord,

abandoning this issue to move onto a PR, will likely link to this issue but no reason for it not to stay closed.
