### ISSUE TITLE
[MoM] Make contemplation train Metaphysics

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75011]
### Is your feature request related to a problem? Please describe.

Currently it appears that that the "meditating" activity that trains your specific powers doesn't train your Metaphysics skill, but the brief craft you do that triggers the training EOC does.

This creates an awkward, gamey incentive to start and cancel the meditation over and over to train the skill.

### Solution you would like.

Make the meditation activity give experience towards Metaphysics as well as the relevant power.

### Describe alternatives you have considered.

Remove the Metaphysics experiecne game from the initial craft. This would be a solution and make the actual Metaphysics practice recipes more valuable, but I'm not sure if it's even possible. These recipes really should fall under Metaphysics, and idk if you can disable xp gain fro mthe primary skill.

**Comment by Standing-Storm** [comment]
> Remove the Metaphysics experience game from the initial craft.

This should be possible by changing the 30s startup time to 1s, making it essentially uncancellable, which I'm going to do. But it should also provide some metaphysics XP.

**Comment by Terrorforge** [comment]
You don't cancel the startup time, you cancel the "meditating" afterwards so you can do the startup again, because that's the part that give Metaphysics xp. Cutting the time to 1 second doesn't prevent that, although it does make it prohibitively annoying.

Still, there's not really any reason to leave them at 30 seconds. Just creates a greater possibility of half-finished practice items cluttering up the place.

**Comment by Standing-Storm** [comment]
That makes me wonder if a craft can have a "0 seconds" time...
