### ISSUE TITLE
[Bombastic Perks] Bombastic Perks count towards mutation instability

### ISSUE THREAD

**Issue by gnneo** [CleverRaven/Cataclysm-DDA#75019]
### Describe the bug

When computing mutation instability, the perks from Bombastic Perks count towards the total mutation instability.

In mutation.cpp L182 it checks for the category to be nonempty. However, Bombastic Perks belong to the 'perks' category. 

### Attach save file

before taking perks
[Bombastic Only-trimmed.tar.gz](https://github.com/user-attachments/files/16228572/Bombastic.Only-trimmed.tar.gz)
after taking perks
[Bombastic Only-trimmed.tar.gz](https://github.com/user-attachments/files/16228578/Bombastic.Only-trimmed.tar.gz)

### Steps to reproduce

1. create a new player
2. add 5 bombastic perks levels
3. inject primer + catalyst

### Expected behavior

Expect the frequency of negative mutations to be independent of how many perks you have taken from Bombastic Perks.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.4 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cdda-experimental-2024-07-06-1626 76a777a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bombastic Perks [bombastic_perks]
]

**Comment by Cupidatis** [comment]
Also bombastic perks are purifable by mutagens...

**Comment by Maleclypse** [comment]
I think this line might work as a fix. 
```
if( mut.obj().points > -1 && !mut.obj().threshold && !mut.obj().category.empty() && !mut.obj().category.perks() &&
```
