### ISSUE TITLE
Game keeps crashing after loading and playing for a bit while entering a town

### ISSUE THREAD

**Issue by Hihahahalol** [CleverRaven/Cataclysm-DDA#75010]
### Describe the bug

Game keeps crashing starting the save file, seems to not crash if I move away northwards from the starting location

### Attach save file

[Magiclysm_copy-trimmed.tar.gz](https://github.com/user-attachments/files/16227035/Magiclysm_copy-trimmed.tar.gz)

### Steps to reproduce

I haven't pinned it down to what exactly causes the crash, but go into the city right south of the save start and fight the zombies and it tends to crash consistently

GuardianDll — Today at 15:50
Crash log says something about monster moving at some vehicle part or something like that. Yes, make a bugreport with save file

### Expected behavior

No crash

### Screenshots

![image](https://github.com/user-attachments/assets/e0370e30-5b19-4cf6-9601-c6e7f89c1ea9)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: cdda-experimental-2024-06-28-2200 54bd595 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16227517/crash.log)
[debug.log](https://github.com/user-attachments/files/16227518/debug.log)

**Comment by PatrikLundell** [comment]
/Confirmed

Call stack:
>	cataclysm-tiles.exe!game::achievements() Line 3385	C++
 	cataclysm-tiles.exe!vehicle::part_with_feature(int part, vpart_bitflags flag, bool unbroken, bool include_fake) Line 2763	C++
 	cataclysm-tiles.exe!vpart_position::obstacle_at_part() Line 2606	C++
 	cataclysm-tiles.exe!map::bash_rating_internal(int str, const furn_t & furniture, const ter_t & terrain, bool allow_floor, const vehicle * veh, int part) Line 3388	C++
 	cataclysm-tiles.exe!map::cost_to_pass(const coords::coord_point<tripoint,5,0,0> & cur, const coords::coord_point<tripoint,5,0,0> & p, const pathfinding_settings & settings, pf_special p_special) Line 307	C++
 	cataclysm-tiles.exe!map::route(const tripoint & f, const tripoint & t, const pathfinding_settings & settings, const std::function<bool __cdecl(tripoint const &)> & avoid) Line 467	C++
 	cataclysm-tiles.exe!map::route(const tripoint & f, const tripoint & t, const pathfinding_settings & settings, const std::function<bool __cdecl(tripoint const &)> & avoid) Line 384	C++
 	cataclysm-tiles.exe!monster::move() Line 1017	C++
 	cataclysm-tiles.exe!`anonymous namespace'::monmove() Line 317	C++
 	cataclysm-tiles.exe!do_turn() Line 658	C++
 	cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 873	C++

It seems something blows up when a monster bashes some vehicle. I have no idea where the achievement comes in, though.
