### ISSUE TITLE
Crash when zooming main view

### ISSUE THREAD

**Issue by gileri** [CleverRaven/Cataclysm-DDA#75039]
### Describe the bug

When zooming using z or Z, the game crashes when zoom "overflow" and go back to the biggest/smallest scale.

### Attach save file

[Spawn_no_crash-trimmed.tar.gz](https://github.com/user-attachments/files/16239964/Zoomies-trimmed.tar.gz)

[Moved_crash-trimmed.tar.gz](https://github.com/user-attachments/files/16239997/Spawn_crash-trimmed.tar.gz)

### Steps to reproduce

1. Load save `Spawn_no_crash-trimmed.tar.gz`
2. Zoom with z or Z until "overflow"
3. No crash
4. Load save `Moved_crash-trimmed.tar.gz` (I just walked NE a few tile from spawn since previous save)
5. Zoom (main view, not the map) with z or Z until "overflow"
6. Crash

### Expected behavior

No crash

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.I ( [64-bit] (f6ed398073c167af8472c4a81d96709022e8ec3b)
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/16240050/debug.log)

[crash.log](https://github.com/user-attachments/files/16240052/crash.log)

**Comment by PatrikLundell** [comment]
Failed to repeat with the crash save.

Thus, it might be an OS thing.

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 0.G-10776-gf6ed398073-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
"dirty" because it's the code for #75031, which shouldn't matter for this issue.

**Comment by gileri** [comment]
You're right @PatrikLundell. This is only triggered if `-D_GLIBCXX_ASSERTIONS` is in `CXXFLAGS`, which is the default on some distributions, including Archlinux.
