### ISSUE TITLE
"You are squeezed uncomfortably into the cramped space." on an empty tile

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#75035]
### Describe the bug

```
│          ┌ All the stuff you're carrying isn't making it any easier to move in here.
│          │ You are squeezed uncomfortably into the cramped space.                   
v  1  second It feels good having room to move again.                                 
```

### Attach save file

see below

### Steps to reproduce

* load the save
* follow the red trajectory

### Expected behavior

No such messages.

### Screenshots

![](https://tinystash.undef.im/il/5qQtAyRHvgNPBEGB7fF8UPXLM7r6n4SzbP4Qy8VM6oAKU3m8yNjVty9zc5MWL6rnFSCQfLa3t8T7xhTXm7aMpSMc.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-07-14-0652 38b05c284d-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by l29ah** [comment]
[2024.07.14.zip](https://github.com/user-attachments/files/16237200/2024.07.14.zip)

**Comment by anoobindisguise** [comment]
I'm having the same issue

**Comment by PGR-14** [comment]
Can confirm as well, I randomly had it for a turn
