### ISSUE TITLE
two upper receivers on a gun

### ISSUE THREAD

**Issue by cornlover62** [CleverRaven/Cataclysm-DDA#75064]
### Describe the bug

mk18 cqbr you start with at the beginning of aircraft carrier challenge has two upper receivers attached

### Attach save file

[Tatamy-trimmed.tar.gz](https://github.com/user-attachments/files/16266195/Tatamy-trimmed.tar.gz)

### Steps to reproduce

challenge - aircraft carrier
navy seal profession
check mk18

### Expected behavior

i expected the gun to have one upper receivers, i guess? :v

### Screenshots

![image](https://github.com/user-attachments/assets/de87dbfe-69b9-4d21-8867-4412272db83c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-07-03-1542 f581edd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

**Comment by casswedson** [comment]
/confimed

```sh
    "id": "m4_cqbr",
    "name": { "str": "Mk 18 CQBR carbine" },
    # varian of modular_m4 inherits the default mod
    "id": "modular_m4_carbine",
    "default_mods": [ "retool_ar15_223rem_medium" ],
  
    # after that this itemgroup that the navy seal profession uses applies another receiver on top
    "id": "m4_cqbr",
    "type": "item_group",
    "subtype": "collection",
    "entries": [
      {
        "item": "modular_m4_carbine",
        "variant": "m4_cqbr",
        "contents-item": [ "pistol_grip", "retool_ar15_223rem_short", "suppressor", "adjustable_stock" ]
      }
    ]
```

**Comment by casswedson** [comment]
ahem /confirmed
