### ISSUE TITLE
Performance drop in vehicle examination screen

### ISSUE THREAD

**Issue by MikasaTanikawa** [CleverRaven/Cataclysm-DDA#75085]
### Describe the bug

In https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-07-18-0452 navigation in vehicle screen has become very slow. It takes up to a second for me to move between frames.

### Attach save file

[Panacea-trimmed.tar.gz](https://github.com/user-attachments/files/16283649/Panacea-trimmed.tar.gz)

### Steps to reproduce

1. Examine any vehicle
2. Pan in any direction
3. Navigate to tile with controls and scroll through part descriptions with > < keys
Notice how slow is every step.
Compare performance with previous release: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-07-18-0220

### Expected behavior

Everything works as fast as in previous releases

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: db34351 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by likowski1** [comment]
i have the Same issue on my end. it seems to also effect the Multi-drop Menu as well

**Comment by JDdeen** [comment]
okay, i did the profiling thing on both the vehicle menu lag and multidrop menu lag, still dont know how to repro the vehicle menu lag, but i did repro the multidrop menu lag - i wielded(w) backup generator and lag started

vehicle menu lag
![image](https://github.com/user-attachments/assets/2c09820d-09c9-483b-85c2-c0fa1e0aa3d8)

multidrop menu lag
![image](https://github.com/user-attachments/assets/513f1f52-d733-4ba4-be69-3f320aaf722f)

both profiler reports in the attachment
[reports.zip](https://github.com/user-attachments/files/16310638/reports.zip)
