### ISSUE TITLE
[XEDRA Evolved] The Shadow singularity cannot spawn

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#75090]
### Describe the bug

When using XEDRA Evolved, the shadow singularity cannot spawn. It throws an error after the "you shiver as the night closes in" popup
The shadow spawns as expected in an unmodded game

### Attach save file

[Dot Lake-trimmed.tar.gz](https://github.com/user-attachments/files/16287084/Dot.Lake-trimmed.tar.gz)

### Steps to reproduce

1. Set time to night and at least a week after the cataclysm
2. stand in a field call the EOC_LIEUTENANT_SPAWN_SHADOW eoc until you get the shiver popup
3. See the error and the lack of shadow

### Expected behavior

I expect the shadow to spawn as it does in the unmodded game

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3737 (23H2)
- Game Version: cdda-experimental-2024-07-16-1658 bdc6ee9 [64-bit]
- Graphics Version: Tiles
- Game Language: Langue du système []
- Mods loaded: [
    Dark Days Ahead [dda],
    Désactiver les besoins des PNJ [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]

### Additional context

Here is the error 

DEBUG    : Interrupt query called in json without proper interrupt type.

 FUNCTION : talk_effect_fun::{anonymous}::f_message(const JsonObject&, std::string_view, std::string_view, bool)::<lambda(const dialogue&)>
 FILE     : src/npctalk.cpp
 LINE     : 4411
 VERSION  : cdda-experimental-2024-07-16-1658 bdc6ee9

**Comment by Maleclypse** [comment]
@SariusSkelrets did you fix this I thought I saw shadow quest still in the boann quests?

**Comment by SariusSkelrets** [comment]
It appears to be fixed. The shadow managed to spawn through the EOC

I noticed that the SHADOW_SPAWN EOC was overwritten by something that looked as if make for SHADOW_SPAWN_MESSAGE. I changed that EOC and apparently it fixed the issue

I'll close this issue for now. If the problem is encountered again, a new issue will be made
