### ISSUE TITLE
Dextrous mutation has no vitamin cost, don't believe it's possible to get via mutating

### ISSUE THREAD

**Issue by Regilith** [CleverRaven/Cataclysm-DDA#75097]
### Describe the bug

Dextrous does not have a vitamin cost, mechanic introduced in #74145

I've been trying to get it via mutating in my game, but either I have been incredibly unlucky (dozens of restarts from testing) or it is due to it not having a vitamin cost. I do see in that that PR that the default for mutations without a vitamin cost is 100, but even with having 100+ alpha primer and mutagen vitamin, and no other positive traits left to get in Alpha tree, it does not mutate.

### Attach save file

N/A

### Steps to reproduce

Can see issue in the Hitchikers Guide or in mutations.json

### Expected behavior

Would expect Dextrous to be attainable and have a vitamin cost.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: SteamOS; Description: SteamOS Holo; Release: rolling; Codename: Holo; 
- Game Version: cdda-experimental-2024-06-26-1623 06460ed [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland]
]

**Comment by Venera3** [comment]
Vitamin costs default to 150 if not defined (and don't influence trait eligibility in the first place).

You can enable Debug Mode by binding a key to it, activate it and select the `DF_MUTATION` debug filter to see the trait selection logic in the log if you want to check what prevents you from gaining it.

**Comment by Regilith** [comment]
It needed 150 vitamin
