### ISSUE TITLE
Clear outsert lens keep falling of the gas mask.

### ISSUE THREAD

**Issue by Loupkiller** [CleverRaven/Cataclysm-DDA#75094]
### Describe the bug

Clear outsert lens keep falling of the gas mask.
It has hapenned in 2 cases i was able to see
1. When i was walking around.
2. When it was in the pouch.
Message: Your * ++ clear outsert lens falls to the ground.

### Attach save file

[Skyland-trimmed.tar.gz](https://github.com/user-attachments/files/16289201/Skyland-trimmed.tar.gz)

### Steps to reproduce

1. Insert a "clear outsert lens" in a gas mask.
2. Walk around.
result: it falls off.

### Expected behavior

Without a reason it should not keep falling off.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-07-17-1500 ca314e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Consoleable** [comment]
I'm also having this issue

**Comment by MikasaTanikawa** [comment]
Clear outsert lens weights 55g: https://github.com/DoctorBoomstick/Cataclysm-DDA/blob/27ce568644fcc48c2cffc8f9669546dceab0bd20/data/json/items/armor/head_attachments.json#L943
But pocket in gas mask supports only 50g: https://github.com/DoctorBoomstick/Cataclysm-DDA/blob/27ce568644fcc48c2cffc8f9669546dceab0bd20/data/json/items/tool_armor.json#L2045

@DoctorBoomstick
