### ISSUE TITLE
NPC have vanished from a passenger seat (and other stuff) at save/load

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#75114]
### Describe the bug

He's gone, tho some of his aspects linger, like being able to `C`hat a little. The map is messed up too. Yes, i don't have free space problems on my cataclysm saves' partition, neither i received any funky errors before saving. Moving into the seat NPC has occupied shows `ERROR : src/map.cpp:1435 [void map::board_vehicle(const tripoint&, Character*)] map::board_vehicle: passenger (Elton Naylor) is already there`.

### Attach save file

[2024.07.14.zip](https://github.com/user-attachments/files/16318097/2024.07.14.zip)

### Steps to reproduce

* load the game
* `C`hat or move to the bottom right seat

### Expected behavior

No funky stuff.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: c05639c125-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by l29ah** [comment]
Replicated it on a new game on 613d67fe408a07b2060255f2a2eea8b3a84e15c5 about 10 minutes into gameplay.

**Comment by l29ah** [comment]
I wonder if it might be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/75012 e.g. some buffers aren't hitting the filesystem.

**Comment by PatrikLundell** [comment]
Confirmed.

The save does indeed seem to have been corrupted.

**Comment by l29ah** [comment]
Seems to be fixed as of 52d2b5f44bf9ee4b61e0d7a6284d8ba1238b7076: i load the "corrupted" saves just fine.
