### ISSUE TITLE
[MoM] Droning hum lingering (again)

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75110]
### Describe the bug

Killed a Blank, its "Droning Hum" field did not go away. Pretty sure it's supposed to.

This does not appear to be the same issue as #70107, as there were no walls between where the null died and where the hum persists. I was standing right next to it when I killed it, and the hum lingered on my position.

The hum remained for several minutes.

### Attach save file

My game won't let me create compressed saves right now.

I did back up this save so hopefully I'll be able to provide one if I can figure out how to unfuck it.

### Steps to reproduce

Unclear. Kill some nulls, I guess?

### Expected behavior

The hum is supposed to go away immediately when the null dies.

### Screenshots

![image](https://github.com/user-attachments/assets/68dc1a77-cf78-4828-a266-112ca7d0a832)
Droning hum here. This is where I was standing during the fight.

![image](https://github.com/user-attachments/assets/06fba7a6-d348-44c1-bca0-d2e53e114843)
Dead blank here.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 48419ad [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

@Standing-Storm it's happening again

**Comment by Standing-Storm** [comment]
It's a targeting issue problem. Easy fix
