### ISSUE TITLE
Repairing neoprene arm sleeves segfault

### ISSUE THREAD

**Issue by morikal** [CleverRaven/Cataclysm-DDA#75113]
### Describe the bug

When repairing my neoprene arm sleeves I get a reproducible segfault.
[crash.log](https://github.com/user-attachments/files/16318080/crash.log)

### Attach save file

[South Holland-trimmed.tar.gz](https://github.com/user-attachments/files/16318073/South.Holland-trimmed.tar.gz)

### Steps to reproduce

1. Move south 1 tile
2. (a)ctivate the tailor's kit
3. Select repair
4. Select the neoprene arm sleeves.
5. Select repeat until fully repaired
6. When first level of repairs completes, select cotton patch
7. Game segfaults while doing third level of repairs

I also tried repairing manually one step at a time. The crash is when it is the double green || and I succeed in repairing to ++.

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: cdda-experimental-2024-07-19-1649 006eac9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by l29ah** [comment]
I can confirm it. `fix` is `NULL` at `repair_item_actor::can_repair_target`.

**Comment by PatrikLundell** [comment]
/Confirmed
 The debugger claims "fix" looks like a normal pointer to an object in repair_item_actor::repair, but then that it's null in repair_item_actor::can_repair_target called by it, to then crash in
item::is_null when the null pointer is referenced.
Trying to set a breakpoint wasn't particularly useful, as it seems to be called every tick.
Looking at the item_locator before it morphs into null shows that it's an expired pointer with an idx of -1, so something, somewhere decided the item was lost, it seems. The code intended to handle lost item_locators doesn't seem to handle this case, though.
When I hacked in a handling of the sort of null case the game didn't crash, but the sleeve was missing, as was a whole bunch of stuff that was in the same tile.
Picking up the sleeve before the repair seems to works without crashing and without loss of other items.

**Comment by inogenous** [comment]
The NPC in the same room, "Lanora Maldonado" will start sorting items after a while. This makes the neoprene arm sleeves move some tiles to the west, which invalidates the `item_location`.
![snapshot9](https://github.com/user-attachments/assets/6fb04b4d-bd61-4491-ad50-aba4196bc94f)

**Comment by PatrikLundell** [comment]
Hm, if someone is sorting stuff it would explain why things went missing...
