### ISSUE TITLE
wyrd spider can push an entire car into you

### ISSUE THREAD

**Issue by deltanedas** [CleverRaven/Cataclysm-DDA#75115]
### Describe the bug

a car:
- that weighs ~1400kg
- with its handbrake up

was able to be shoved out of the way by a spider, and probably any other monster
coincidentally the spider crushed my character by pushing my car into me

additionally it can be shoved regardless of the wheel orientation, i originally had it happen back to front, and reproduced it again side to side.

wyrd spider specifically has a mass of 815kg, and the car is significantly heavier than it. handbrake specifically exists to prevent rolling so pushing with it up should not work, maybe having it get tipped over going side to side would make sense depending on how strong the spider is

### Attach save file

[Deepstep-trimmed.tar.gz](https://github.com/user-attachments/files/16318102/Deepstep-trimmed.tar.gz)

### Steps to reproduce

1. press a then h to turn on headlamp
2. let spider crush you

### Expected behavior

a spider should not be able to crush you with a 1.4T car thats pretty obvious

### Screenshots

![image](https://github.com/user-attachments/assets/7931ad37-afd6-4e83-8461-966cdbf0c178)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.0; Distributor ID: VoidLinux; Description: Void Linux; Release: rolling; Codename: void; 
- Game Version: cdda-experimental-2024-06-19-0447 551e1b5-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

version is dirty as i have a utf16 converting fix used locally, almost certainly has nothing to do with this behaviour

its relatively old though so maybe it was changed over the past few weeks

**Comment by Karol1223** [comment]
In comparison to other monsters, wyrd spider is actually one of the most reasonable to push vehicles. Hulks do it and weigh 200kg. The bigger picture is that a lot of our monsters have really really low weight compared to what they should have.

Having said that, I am not experienced with pushing cars, so I couldn't say how reasonable it is for any of those monsters to push vehicles. But it's not a bug, it's an intended behavior given to the spider by a flag, on purpose.

**Comment by harakka** [comment]
Handbrakes don't exist. You can push around cars, so can enemies, this is chonky sized enemy.

**Comment by deltanedas** [comment]
theres probably an issue for better handbrake/vehicle pushing interaction so closing this
