### ISSUE TITLE
Segfault when equipping thermal electric outfit while naked

### ISSUE THREAD

**Issue by morikal** [CleverRaven/Cataclysm-DDA#75111]
### Describe the bug

When naked, go to the + menu (armor/layer sorting) and navigate to the torso. Press 'E' to equip armor to this location, equip thermal electric outfit -> segfault.

Note that if I don't drop all my worn things first, there is no crash.
Further, even if I do drop all my things first, if I equip via the 'W'ear action there is no crash.

[crash.log](https://github.com/user-attachments/files/16317292/crash.log)

### Attach save file

[South Holland-trimmed.tar.gz](https://github.com/user-attachments/files/16317294/South.Holland-trimmed.tar.gz)

### Steps to reproduce

1. Drop all worn items.
2. Walk a few tiles north to where the pile with the thermal electric outfit is.
3. Press + to open armor layering UI
4. Navigate to torso section
5. Hit E to equip armor to this location
6. Select the thermal electric outfit

### Expected behavior

No crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: cdda-experimental-2024-07-19-1649 006eac9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by NoddingCrow** [comment]
Confirmed on cdda-experimental-2024-07-19-1400 b1cf8e3 [64-bit] from earlier in the day too; segfault occurs when equipping any worn item onto a naked character through the armor sort screen. 

No-location / cosmetic items crash the game too.

Integrated armor saves it from crashing, but pop-up "Can't put this on under your integrated armor!" seems to suggest it's attempting to place them "below" the integrated armor item and is being successfully caught.

**Comment by PatrikLundell** [comment]
Tried to fix this by checking if tmp_worn was empty and emplace the new item at both the back and the front of "worn" if it was, rather than to try to get the first element of an empty vector (and crash) . In both cases it doesn't crash, but I end up with two copies of the item worn, and it appears I get duplication when those are take off.

Giving up and handing over to someone who has some idea of how this thing is supposed to work.
