### ISSUE TITLE
`npctalk` error during player proficiency training

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#75139]
### Describe the bug

```
 DEBUG    : Invalid message type.

 FUNCTION : operator ()
 FILE     : Z:\alef\src\npctalk.cpp
 LINE     : 4364
 VERSION  : 0.H-6465-gecea7b5f0
```

Since I was playing under the debugger, I can see the missing [`type_string`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/npctalk.cpp#L4364) case is `"morale"`.

### Attach save file

N/A, but here the `debug.log`:
```
10:29:26.057 ERROR : (error message will follow backtrace)
  #0
    (dbghelp: debug_write_backtrace+0xc6@00007FF7A0F00416[cataclysm-tiles.exe+0x900416]), 
  #1
    (dbghelp: DebugLog+0x15e@00007FF7A0EFF26E[cataclysm-tiles.exe+0x8ff26e]), 
  #2
    (dbghelp: realDebugmsg+0x1ba@00007FF7A0F023EA[cataclysm-tiles.exe+0x9023ea]), 
  #3
    (dbghelp: <lambda_619a19adf6130e46aa3b076d96290a02>::operator()+0x6c0@00007FF7A1A35D20[cataclysm-tiles.exe+0x1435d20]), 
  #4
    (dbghelp: talk_effect_t::apply+0x222@00007FF7A1A45A12[cataclysm-tiles.exe+0x1445a12]), 
  #5
    (dbghelp: effect_on_condition::activate+0x37a@00007FF7A0FFBFDA[cataclysm-tiles.exe+0x9fbfda]), 
  #6
    (dbghelp: process_eocs+0x1a6@00007FF7A1001806[cataclysm-tiles.exe+0xa01806]), 
  #7
    (dbghelp: effect_on_conditions::process_effect_on_conditions+0x85@00007FF7A1001645[cataclysm-tiles.exe+0xa01645]), 
  #8
    (dbghelp: do_turn+0x1341@00007FF7A0FA8D31[cataclysm-tiles.exe+0x9a8d31]), 
  #9
    (dbghelp: WinMain+0xe65@00007FF7A0A5C025[cataclysm-tiles.exe+0x45c025]), 
  #10
    (dbghelp: __scrt_common_main_seh+0x106@00007FF7A237BEAE[cataclysm-tiles.exe+0x1d7beae]), 
  #11
    (dbghelp: BaseThreadInitThunk+0x14@00007FFBE2E37374[KERNEL32.DLL+0x17374]), 
  #12
    (dbghelp: RtlUserThreadStart+0x21@00007FFBE4B1CC91[ntdll.dll+0x4cc91]), 
Backtrace emission took 0 seconds.
(continued from above) ERROR : Z:\alef\src\npctalk.cpp:4364 [operator ()] Invalid message type.
```

### Steps to reproduce

Train some proficiencies. In this case was `markmanship (beginner)` but it happened with others.

### Expected behavior

Handle the `"morale"` case.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 0.H-6465-gecea7b5f0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
The "Steps to reproduce" entry is deficient.

I'm not sure what's supposed to happen given the lack of description of what's failing other than some referenced code, but given a reference to npctalk, reproduction probably requires an NPC or companion present. Maybe it requires said NPC to do something to trigger it (and thus be set up to behave in some fashion, like being idle, finish some job, coughing/wheezing, etc.). This is made worse by the omission of a save, which at least would have set things up, even if the details of the setup wasn't provided.

**Comment by alef** [comment]
There are no NPCs nearby.

**Comment by PatrikLundell** [comment]
Failed to reproduce.
Tried markmanship for a couple of hours and then bandaging for a couple of hours.

**Comment by alef** [comment]
The following save is *after* it happened, but while dissecting zombies so it is not related to proficiencies:
[Paradise-trimmed.tar.gz](https://github.com/user-attachments/files/16324732/Paradise-trimmed.tar.gz)

**Comment by alef** [comment]
Again some time later. This is the call stack from Visual Studio:
```
[External Code]
input_manager::get_input_event(keyboard_mode preferred_keyboard_mode) Line 3822
	at Z:\alef\src\sdltiles.cpp(3822)
debug_error_prompt(const char * filename, const char * line, const char * funcname, const char * text, bool force) Line 382
	at Z:\alef\src\debug.cpp(382)
realDebugmsg(const char * filename, const char * line, const char * funcname, const std::string & text) Line 558
	at Z:\alef\src\debug.cpp(558)
[Inline Frame] realDebugmsg(const char * const) Line 78
	at Z:\alef\src\debug.h(78)
talk_effect_fun::`anonymous-namespace'::f_message::__l2::<lambda>(const dialogue & d) Line 4364
	at Z:\alef\src\npctalk.cpp(4364)
[Inline Frame] std::_Func_class<...>::operator()(dialogue &) Line 869
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(869)
[Inline Frame] talk_effect_fun_t::operator()(dialogue &) Line 86
	at Z:\alef\src\dialogue_helpers.h(86)
talk_effect_t::apply(dialogue & d) Line 6449
	at Z:\alef\src\npctalk.cpp(6449)
effect_on_condition::activate(dialogue & d, bool require_callstack_check) Line 329
	at Z:\alef\src\effect_on_condition.cpp(329)
process_eocs(queued_eocs & eoc_queue, std::vector<...> & eoc_vector, dialogue & d) Line 248
	at Z:\alef\src\effect_on_condition.cpp(248)
effect_on_conditions::process_effect_on_conditions(Character & you) Line 278
	at Z:\alef\src\effect_on_condition.cpp(278)
do_turn() Line 677
	at Z:\alef\src\do_turn.cpp(677)
WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 873
	at Z:\alef\src\main.cpp(873)
[External Code]

```

**Comment by PatrikLundell** [comment]
I failed to reproduce it dissecting the remaining corpses in the pile.

However, if you can catch it in the debugger you ought to be able to also examine what the string that didn't match any of the expected ones was, as well as where in the call chain it was introduced, to locate its actual location.

You could also hack the debug message to actually print the offending string (that would be a reasonable improvement to the code base anyway).

**Comment by alef** [comment]
It seems the game want the *player* to say something in the log, but the `get_message_type` enum doesn't have a `m_morale` type of message. Some JSON file probably has this `"type"` field set to `"morale"`.

**Comment by PatrikLundell** [comment]
Based on the call stack, it's some EoC stuff, and thus probably almost impossible to track down without the actual text, as the text presumably would allow you to find a match in the JSON, where someone probably got something slightly wrong.

**Comment by alef** [comment]
> "The sunset always makes you a feel a little bit better."

Found it: https://github.com/CleverRaven/Cataclysm-DDA/blame/master/data/json/effects_on_condition/misc_effect_on_condition.json#L232 made by @BalthazarArgall

**Comment by BalthazarArgall** [comment]
What is the issue exactly?

> > "The sunset always makes you a feel a little bit better."
> 
> Found it: https://github.com/CleverRaven/Cataclysm-DDA/blame/master/data/json/effects_on_condition/misc_effect_on_condition.json#L232 made by @BalthazarArgall

What's the issue exactly?

**Comment by alef** [comment]
@BalthazarArgall There is no `"type": "morale"` for `"u_message"`.

**Comment by BalthazarArgall** [comment]
@Maleclypse It looks related to the last minute changes you made?
