### ISSUE TITLE
Crafting chainmail is very stupid

### ISSUE THREAD

**Issue by ShuCuoMao** [CleverRaven/Cataclysm-DDA#75140]
### Is your feature request related to a problem? Please describe.

You can craft chain links using wire,its material is cast iron.
But crafting chainmails only uses carbon chain,making normal one useless
In the end you have to make carbon steel before you can make chainmail.
you can see how stupid it is to make one chainmail:you have no chioce but to make steel wire and waste a lot of time
![image](https://github.com/user-attachments/assets/c6975723-ab8b-4c11-82c8-53e3d9f48e1b)

### Solution you would like.

Normal chain links should be able to make mild steel chainmail just like lamellar armor.And I personnally think chains should be more like lamellars and be cut into two kinds:wire->chain links->hardened steel chain link

**Comment by ShuCuoMao** [comment]
Also,carbon steel wires' only useage are to craft carbon steel chainmail,which is also a liability

**Comment by kevingranade** [comment]
If you can't show the slightest modicum of civility don't bother. Opening with "x is very stupid" is not ok.
