### ISSUE TITLE
Aftershock light exosuit frame gets damaged in combat

### ISSUE THREAD

**Issue by Menschlich1** [CleverRaven/Cataclysm-DDA#75163]
### Describe the bug

When the light exosuit frame from aftershock is powered on it is considered fragile and will break in combat.

### Attach save file

N/A

### Steps to reproduce

1. Wear light exosuit frame.
2. Equip exosuit auxillary battery.
3. Examine light exosuit frame. (Now considered fragile AND sturdy)
4. Get attacked.
5. Light exosuit frame takes damage and eventually breaks.

### Expected behavior

Exosuit should not get damaged/break.

### Versions and configuration

OS: Windows 10
Game Version: 99ed329
Graphics Version: Tiles
Language: English

Mods loaded:   "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "magiclysm",
  "bombastic_perks",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "aftershock"

**Comment by eturner** [comment]
I haven't used it yet, but I've noticed that it somehow has both 'sturdy' and 'fragile' for what it's worth. Scared to try it in my sky island run.
