### ISSUE TITLE
Cellphones always spawn with full charge

### ISSUE THREAD

**Issue by BarndoBoi** [CleverRaven/Cataclysm-DDA#75201]
### Describe the bug

When looting zombies you'll sometimes find cellphones on them, and those cellphones ALWAYS have a fully charged light battery (high capacity) inside of them.

### Attach save file

I'll attach my save when I next find a zombie with a cellphone on it and edit this issue to include it 👍 

### Steps to reproduce

Either generate some of the zombie's dropped itemgroups or look through some of the corpses and you'll notice that any time you find a zombie with a cellphone that the battery spawns with a full charge.

### Expected behavior

Cellphones should act like most of the other electronics and be generated with a random amount of remaining battery.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: cdda-experimental-2024-07-23-0822 302ed6e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I've noticed this on a save I've migrated across several weeks worth of experimental, but I'll attempt to reproduce it sometime tomorrow to confirm the bug in a fresh game in the latest experimental.

**Comment by Termineitor244** [comment]
I couldn't confirm this bug, while sometimes fully charged cellphones do drop from zombies, they also drop cellphones with low charge, in my own game I have one fully charged cellphone and 2 other ones low-charged, all of them dropped by zombies, I went and tested the item group with the debug menu and...
![imagen](https://github.com/user-attachments/assets/06896941-0890-4662-9fdc-6975557d95d5)
![imagen](https://github.com/user-attachments/assets/45c09949-61df-4c03-8a44-9359dea9f9df)

**Comment by Night-Pryanik** [comment]
Can't confirm it either on 0.G-12264. Closing until reconfirmed.
