### ISSUE TITLE
Small slimes are too big to be carried

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#75211]
### Describe the bug

Had a pet carrier & tried to capture a slime for my base (For slime globs), but couldn't, seems like they're the right size.

### Attach save file

N/A

### Steps to reproduce

Grab pet carrier, spawn friendly slime (so you are able to do it w/out check), despair

### Expected behavior

Slime in da carrier

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3737 (23H2)
- Game Version: cdda-experimental-2024-07-19-0455 48419ad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Tankmod: Revived [Tankmod_Revived],
    Blazemod - Vehicle Additions Pack [blazemod],
    Caches [P_Caches],
    Extra Mutated Scenarios [extra_mut_scens],
    New start locations for Extra Mutated Scenarios [new_start_locations_for_extra_mutation_scen],
    More Professions can start in Extra Mutated Scenarios [more_profession_chooses_extra_mut_scens],
    More Survivor Notes [more_survivor_notes],
    Mythical Martial Arts [MMA],
    Hands [hand],
    Custom Portal Storm Size [custom_size_ps],
    Custom Frequencey For Portal Storms [custom_freq_ps],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Bionic Traits [bionic_traits],
    Alternative Map Key [alt_map_key],
    Targeted Mutagens [targetedmutagens],
    Frontier Mods Core [frontier_core],
    Loadout [loadout],
    Gunsmith [gunsmith],
    Jackledead Armory [jackledead_armory],
    Culinary Days Ahead [culinary_days_ahead],
    Xedra Evolved [xedra_evolved],
    Power Armor Starts [power_armor_starts],
    Mind Over Matter [mindovermatter],
    Make bows great again [bow_opness],
    Gunslinger Professions [hyd_gunslinger],
    Bionic Professions [package_bionic_professions],
    Better Arachnids [betterArachnids],
    Aftershock [aftershock],
    <color_light_red>Secronom</color> [secronom],
    <color_light_green>Cataclysm++</color> [Cata++],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Bionic Slots [no_cbm_slots],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Additional backgrounds [Arendeth_Additional_backgrounds],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Readd Clothing Customization for TailorKits [TailorKits-Readd-Customization],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Mind Over Matter: <color_magenta>Double Limit Before Pain Disables Powers</color> [mom_raise_pain_disables_psi_limit],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    Massachusetts [MA]
]

**Comment by Karol1223** [comment]
What do you mean "seems like they're the right size"? They're human sized. They're not even remotely the right size.

**Comment by kevingranade** [comment]
As Karol points out, this is working as intended, you need a bigger carrier.

**Comment by PGR-14** [comment]
Oh, sorry, I though they were the size of a dog/cat (The small slimes look about that size in the tileset)

**Comment by Karol1223** [comment]
There is a communication issue.

In the title and comment you are saying "small slimes". "Small slime" is 30l in volume and should fit a pet carrier if memory serves me right.

In the PR description you're saying "slime". "Slime" is 65l in volume, the size of a human, and should definitely not fit inside a pet carrier.

**Comment by PGR-14** [comment]
Yeah, I thought the regular ones were intentional, sorry for the miscommunication.
