### ISSUE TITLE
[MoM] Concentration proficiency didn't train

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#75224]
### Describe the bug

The training of concentration proficiency didn't work when I was using biokinetic powers physical enhancement and overcome pain 

### Attach save file

[Кукуево-trimmed.tar.gz](https://github.com/user-attachments/files/16370571/-trimmed.tar.gz)

### Steps to reproduce

1. Make biokinetic character
2. Use powers or let them working

### Expected behavior

Proficiency would train. 

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.3.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-07-21-0150 a9e4235 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.6%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Магиклизм [magiclysm],
    Разум над материей [mindovermatter],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Aftershock [aftershock],
    Отключить потребности у НПС [no_npc_food],
    Медленный рост фунгалоидов [no_fungal_growth],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Мифические стили ближнего боя [MMA],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    Помпезные перки [bombastic_perks]
]

**Comment by Standing-Storm** [comment]
Figured it out. It's an incompatibility between Aftershock (which has its own version of MoM) and Mind Over Matter. Since AFS is loaded later, it's looking for AFS powers, which you don't have. 

Renaming the AFS EoCs should fix it.
