### ISSUE TITLE
[Aftershock] Voltaic cells didn't recharge

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#75225]
### Describe the bug

When i was trying to recharge voltaic cell at recharging station and battery charger it didn't work both appliances and vehicle, other batteries charged. 

### Attach save file

[Кукуево-trimmed.tar.gz](https://github.com/user-attachments/files/16370657/-trimmed.tar.gz)

### Steps to reproduce

1. Spawn some voltaic cells. 
2. Make recharging station with battery and enable it. 
3. Try to recharge voltaic cells. 

### Expected behavior

They should recharge. 

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.3.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-07-21-0150 a9e4235 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.6%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Магиклизм [magiclysm],
    Разум над материей [mindovermatter],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Aftershock [aftershock],
    Отключить потребности у НПС [no_npc_food],
    Медленный рост фунгалоидов [no_fungal_growth],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Мифические стили ближнего боя [MMA],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    Помпезные перки [bombastic_perks]
]

### Additional context

Edit: also chromoelectric cartridge can be put in but didn't work with Shikishma A-82 tactical laser @John-Candlebury

**Comment by John-Candlebury** [comment]
Voltaic cells arent meant to be trivially rechargeable like laser packs are.
 Couldn't reproduce the Tactical Laser no working with chromoelectric cartridges either.

**Comment by Cupidatis** [comment]
> Voltaic cells arent meant to be trivially rechargeable like laser packs are. Couldn't reproduce the Tactical Laser no working with chromoelectric cartridges either.

It's strange that voltaic cells didn't recharge but ok.
Tried chromoelectric cartridge at version 2024-09-28-2243. Worked.
Don't know who fixed it, but it didn't work at 2024-07-21-0150

**Comment by John-Candlebury** [comment]
Thanks for the report! 
Currently doing a round of bugfixing for aftershock so if you have noticed anything amiss now's the perfect time.
