### ISSUE TITLE
Option to lead a companion by the hand

### ISSUE THREAD

**Issue by Agnistel** [CleverRaven/Cataclysm-DDA#75245]
### Is your feature request related to a problem? Please describe.

Is it possible to make an option "lead a companion by the hand" similar to pets? During this option, the companion will not panic and will be on the tile next to you, which will allow you to safely pass near dangerous areas (fire, hordes, etc.).

### Solution you would like.

Do it

### Describe alternatives you have considered.

Don't do it

### Additional context

Enabling this option may slow down running and/or prevent the use of two-handed items

**Comment by Consoleable** [comment]
"What if we held hands while we walked into the swirling vortex"

**Comment by DSeyka** [comment]
Our NPCs should be carefully and methodically collecting data about the surrounding environment, measuring threat levels, current priorities, and their relationship to the player.
After which they should discard the above and walk into the nearest fire tile.

**Comment by DSeyka** [comment]
It should just be an NPC behavior option, "stay as close to me as you can no matter what".

**Comment by kevingranade** [comment]
We need to fix NPC behavior, not add goofy workarounds.
