### ISSUE TITLE
Loading Faction base camp spawns new npcs

### ISSUE THREAD

**Issue by The-Silent-One** [CleverRaven/Cataclysm-DDA#75258]
### Describe the bug

re- visiting a npc camp (the loggers in this example) spawns another copy of them.

### Attach save file

[Muscle Magic-trimmed.tar.gz](https://github.com/user-attachments/files/16395800/Muscle.Magic-trimmed.tar.gz)

### Steps to reproduce

1. visit a npc camp
2. walk a long distance
3. revisit the same camp

### Expected behavior

npcs should be not regenerated again.

### Screenshots

![image](https://github.com/user-attachments/assets/1aef2b05-278a-4ade-a7cb-d24d35cc0fc3)

### Versions and configuration

- Os : Opensuse tumbleweed Linux
- Game version : experimental build 2024-07-26-1716
- Graphics version: tiles

**Comment by PGR-14** [comment]
Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/issues/75256?

**Comment by The-Silent-One** [comment]
Update: it corrupted my save. here are the logs

[crash.log](https://github.com/user-attachments/files/16395942/crash.log)

[debug.log](https://github.com/user-attachments/files/16395943/debug.log)

is there any to fix my save?

**Comment by The-Silent-One** [comment]
> Possibly related to #75256?

I don't need to save and reload the game. Just move out of the reality bubble then load it back in. Same problem different methods to achieve it.

**Comment by IFailAtGaming** [comment]
> Update: it corrupted my save. here are the logs
> 
> [crash.log](https://github.com/user-attachments/files/16395942/crash.log)
> 
> [debug.log](https://github.com/user-attachments/files/16395943/debug.log)
> 
> is there any to fix my save?

Having experienced this bug recently after updating, try creating a new character in the same world, saving and quiting to title, then reloading your actual character, it seems to work for me for whatever reason, also avoid saving near areas with npcs, as those seem to cause the crash

**Comment by The-Silent-One** [comment]
> > Update: it corrupted my save. here are the logs
> > [crash.log](https://github.com/user-attachments/files/16395942/crash.log)
> > [debug.log](https://github.com/user-attachments/files/16395943/debug.log)
> > is there any to fix my save?
> 
> Having experienced this bug recently after updating, try creating a new character in the same world, saving and quiting to title, then reloading your actual character, it seems to work for me for whatever reason, also avoid saving near areas with npcs, as those seem to cause the crash

It worked! Thanks alot

**Comment by PatrikLundell** [comment]
I'd recommend against playing until #75270 has been merged, in order to not cause more damage to the save.
