### ISSUE TITLE
Calm down fleeing NPCs

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#75254]
### Is your feature request related to a problem? Please describe.

Whenever I go slime mutant or anything that makes me grotesque, new NPCs always try to flee from me.

### Solution you would like.

I'd love for there to be a way to calm down an NPC trying to flee from me, whether from intimidation or through a persuasion check. W/out a faction camp, it's basically impossible to befriend others.

**Comment by kevingranade** [comment]
This is an intended consequence of turning into a grotesque mutant, if you want to be social, don't do an anti-social character build.
