### ISSUE TITLE
(experimental) npc related segfault on load, duplicate npcs.

### ISSUE THREAD

**Issue by plumblossomfalling** [CleverRaven/Cataclysm-DDA#75265]
### Describe the bug

First time filing a report, forgive any inconsistencies or lack of clarity.

Two saves are involved here: my backup and current save. Not sure how to attach the current save file, as it is crash-on-load and I can't exaclty follow the instructions to send it if it's acting like that - so you'll be getting the backup.

Thankfully, the backup was made only minutes earlier, so don't worry about reproduction.

Not entirely sure what happened? certain NPC's have been... doubled? And saving and reloading near them causes a segfault on load. Saving and reloading one or two map tiles from the doppleganger npcs seems to be fine, but anywhere close is bad news.

tldr: I really don't know what's going on here, and I can only really describe it as magic at this point.

### Attach save file

[marshfield-trimmed.tar.gz](https://github.com/user-attachments/files/16397818/marshfield-trimmed.tar.gz)

### Steps to reproduce

1. enter kayak, and paddle north along the river to either Rubik or mr. Lapin (both are doubled, feel free to check both if you want).
2. exit kayak, and gawk at the pair of Rubiks staring you down.
3. why are there two Rubiks, and why are they outside the castle?
4. you can talk to them, they *seem* functional.
5. that's weird.
6. save and exit while gawking at them.
7. load and crash. (cursed by the dopplegangers!)

### Expected behavior

not to be cursed by the dopplegangers.

### Screenshots

these dorks
![Screenshot 2024-07-26 211005](https://github.com/user-attachments/assets/d7cb7439-101b-4b57-b9ac-85c094a3e871)

### Versions and configuration

- OS: Windows 11
- Game Version: Cataclysm DDA version 26da18e  (should be last week's experimental)
- Graphics version: Tiles, MSXotto+
- ingame language: English
- Mods Loaded: None (other than the vanilla preset cata always runs)

### Additional context

[logs.zip](https://github.com/user-attachments/files/16397888/logs.zip)

**Comment by PatrikLundell** [comment]
Confirmed regarding duplicate NPCs.
