### ISSUE TITLE
False(?) map notes

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75262]
### Describe the bug

The map keeps generating map notes of things that aren't there.

Or at least, only partially there. There's _something_ casting a shadow on the ground in this spot where the map says there's a wasp's nest:
![image](https://github.com/user-attachments/assets/b9b8d688-041e-45bd-b79d-42ce2df71238)

These notes seem to appear over time in areas I've already explored, but I don't know what triggers them.

### Attach save file

[New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16397323/New.Mind-trimmed.tar.gz)

### Steps to reproduce

Unsure when this happens. Possibly just over game time or when moving back and forth.

### Expected behavior

Map notes refer to real things.

### Screenshots

![image](https://github.com/user-attachments/assets/fe0d11de-28f0-4d5d-965e-58e558f27933)
There are not three ponds here. There is not even one pond. Based on how they normally spawn, I don't think it's even supposed to be possible for them to be this close together.

![image](https://github.com/user-attachments/assets/2794d2e4-c55b-4e1e-bbcd-7a80110ef796)
This portal note overwrote the derelict shed note for the shed that's actually here. There's no portal, but there IS some mycus nearby:
![image](https://github.com/user-attachments/assets/93ab6ed2-4b16-4cf6-a931-d84e183829a2)
No note here, though.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: c336181 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Possibly related to #75256?

**Comment by Terrorforge** [comment]
#75188 seems like the most recent change that might be messing with this

**Comment by l29ah** [comment]
I confirm, i got:
* scientist corpses only appeared as a map marker
* bugout bag only appeared as a map marker
* wasp nest only appeared as a map marker
