### ISSUE TITLE
Turrets shoot through walls

### ISSUE THREAD

**Issue by Agnistel** [CleverRaven/Cataclysm-DDA#75260]
### Describe the bug

Turrets shoot through walls

### Attach save file

N/A

### Steps to reproduce

1. Spawn ballistic glass wall
2. Spawn turret
3. Turret shoots at you (perhaps with reduced damage)

### Expected behavior

They don't shoot through walls

### Screenshots

![test1111](https://github.com/user-attachments/assets/4c9bd0aa-927f-474a-83e4-8aaeaba54f9f)

### Versions and configuration

Last experimental

**Comment by fairyarmadillo** [comment]
That's an intended and specifically coded feature, not a bug. The turret can see you, so it shoots at you. Ballistic glass doesn't shatter, but occasionally bullets and bullet fragments are able to poke holes in it.

**Comment by Agnistel** [comment]
> That's an intended and specifically coded feature, not a bug. The turret can see you, so it shoots at you. Ballistic glass doesn't shatter, but occasionally bullets and bullet fragments are able to poke holes in it.

Yes, but how far can the glass/bullet fragments fly and what damage can they cause? Now the glass reduces damage, but it's still bullet damage, with full attack range, bleeding wounds and torn clothing. A couple of turns and the turret kills you, just like you can kill an enemy through a wall with a shotgun/rifle. I'm no shooting expert, but Youtube shows that bulletproof glass stops a certain number of bullets completely before breaking, rather than letting them pass through. In any case, it's kind of unintuitive that you can get shot through ballistic glass

**Comment by harakka** [comment]
This is on purpose, our ballistic glass is meant to stop low power cartridges and lets higher power ones through with diminished energy. The exact end result depends on what's shooting at you.
