### ISSUE TITLE
PHOTOPHOBIA of Shadow lieutenant seems broken

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#75279]
### Describe the bug

Turning ON heavy duty flashlight near this fella seems to DOUBLE his speed, not halve it. Also, once he gets this effect, its seems to stay forever, or at least that was my observation.

### Attach save file

[Test-trimmed.tar.gz](https://github.com/user-attachments/files/16401068/Test-trimmed.tar.gz)

### Steps to reproduce

1. Fast character cannot catch PHOTOPHOBED shadow even while sprinting. If you have all mutations and bionics and drugs and rollerblades then you can barerly outrun him, but thats stammina intensive. Winning race aganist shadow thats not illuminated is way easier.

### Expected behavior

Light good. Darkness bad

### Versions and configuration

a24a4db (tiles)
Win10

### Additional context

In attached savefile i spawned one shadow, turned flashlight on, turned flashlight OFF, spawned second shadow. 
You can see that the one with photophobia is arround 2x times faster than one that wasnt scared. You can see that photophobia does not wear off

**Comment by SirPendrak** [comment]
After messing with debug a bit more I foud that it has exactly 300 speed when under effect of photophobia, and 200 speed under normal circumstances

**Comment by SariusSkelrets** [comment]
Looking at it, can you edit your json so the effect is like this:
```
  {
    "id": "photophobia",
    "type": "effect_type",
    "max_duration": "5 s",
    "name": [ "photophobia" ],
    "desc": [ "It burns!  Thankfully, this can't ever happen to you.  This is a bug if you have it." ],
    "rating": "bad",
    "show_intensity": false,
    "show_in_info": true,
    "enchantments": [
      {
        "condition": "ALWAYS",
        "values": [
          { "value": "SPEED", "multiply": -0.5 },
          { "value": "ARMOR_BASH", "add": 15 },
          { "value": "ARMOR_STAB", "add": 15 },
          { "value": "ARMOR_CUT", "add": 15 },
          { "value": "ARMOR_HEAT", "add": 15 },
          { "value": "ARMOR_COLD", "add": 15 },
          { "value": "ARMOR_ELEC", "add": 15 },
          { "value": "ARMOR_ACID", "add": 15 },
          { "value": "ARMOR_BULLET", "add": 50 }
        ]
      }
    ]
  },
```
and see if it fixes it? My guess is that the person that added it didn't knew that multiplying speed by higher than zero increases it, as does the quick trait (multiply speed by 0.1, resulting in a 10% speed increase)

**Comment by SirPendrak** [comment]
Currently we have:

> {

    "id": "photophobia",
    "type": "effect_type",
    "max_duration": "5 s",
    "name": [ "photophobia" ],
    "base_mods": { "speed_mod": [ -100 ] },
    "desc": [ "It burns!  Thankfully, this can't ever happen to you.  This is a bug if you have it." ],
    "rating": "bad",
    "show_intensity": false,
    "show_in_info": true,
    "//": "Enchantments don't actually work for monsters! If you find that shadow is suddenly very killable, they probably got hooked up!",
    "enchantments": [
      {
        "condition": "ALWAYS",
        "values": [
          { "value": "SPEED", "multiply": 0.5 },
          { "value": "ARMOR_BASH", "add": 15 },
          { "value": "ARMOR_STAB", "add": 15 },
          { "value": "ARMOR_CUT", "add": 15 },
          { "value": "ARMOR_HEAT", "add": 15 },
          { "value": "ARMOR_COLD", "add": 15 },
          { "value": "ARMOR_ELEC", "add": 15 },
          { "value": "ARMOR_ACID", "add": 15 },
          { "value": "ARMOR_BULLET", "add": 50 }
        ]
      }
    ]
  },
  
 The line "base_mods": { "speed_mod": [ -100 ] }, doesnt seem to work, making it higher or lower doesnt seem to do anything.
 Putting - in front of 0,5 makes it go half the speed in the dark.
 All the "value ARMOR add" actually make its armor weaker, in case of, for example, heat - its negative now and takes heavy damage even from weak laser pistol. 
 A shadow used to have some elemental armor that later got removed, so this extra weakness probably should be romoved from vanilla as well.
 Max duration: 5s seems to be broken, it stays photophobed forever
