### ISSUE TITLE
Debug tool to test monstergroup spawning

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#75272]
### Is your feature request related to a problem? Please describe.

We have a debug tool to test itemgroups. It would be very handy to do have one for monstergroups as well, to check if they function correctly when nested or used in mods, where they are extended by default.

### Solution you would like.

A ``Test monster group`` debug tool, that'd try to spawn 100 instances of a specific monstergroup and print the results, similar to the itemgroup test.

### Additional context

While we're at it, why the hell is ``Test item group`` in ``Info``, not ``Spawning``? There's not yet been a situation where I wasn't confused looking for that tool.

**Comment by RenechCDDA** [comment]
You can use population-based hordes.
