### ISSUE TITLE
Automatic POI Noting Going Rogue

### ISSUE THREAD

**Issue by likowski1** [CleverRaven/Cataclysm-DDA#75285]
### Describe the bug

for some reason the Automatic map noting appears to have gone haywire and is adding POI Notes to POI's that do not exist

### Attach save file

[Reardan-trimmed.tar.gz](https://github.com/user-attachments/files/16401821/Reardan-trimmed.tar.gz)

### Steps to reproduce

Unsure. although it might have something to do we Loading the save perhaps its generating the POI's in already explored area's. the Auto-Marker is Adding the notes before the Game tells the world generator that the POI Request is denied

### Expected behavior

not to have my world map look like a Conspiracy board of Map Notes

### Screenshots

![image](https://github.com/user-attachments/assets/d2985064-fb33-42ef-a350-1255ba5714c3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3737 (22H2)
- Game Version: 3135a6a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food]
]

**Comment by harakka** [comment]
Resolved by #75270
