### ISSUE TITLE
Applying bandages causes crash.

### ISSUE THREAD

**Issue by Escamado** [CleverRaven/Cataclysm-DDA#75309]
### Describe the bug

Might be related with the Innawoods mod
Using makeshift or boiled bandages crashes the game.

### Attach save file

[Sontag-trimmed.tar.gz](https://github.com/user-attachments/files/16407099/Sontag-trimmed.tar.gz)

### Steps to reproduce

Craft fibercloth.
Craft Makeshift Bandage.
Use the bandage.
Cry when game crashes.

### Expected behavior

Bandaged limb

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-07-28-2319 a334d3d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16407051/crash.log)
[debug.log](https://github.com/user-attachments/files/16407052/debug.log)

**Comment by inogenous** [comment]
In the savegame, the bandages are inside the clay canning pot, which is a spillable container. When using the bandage, the clay canning pot will spill its items, which will invalidate the `item_location`. This looks similar to #75156 .
