### ISSUE TITLE
[MoM] Change Electrical Discharge and Voltaic Strikes to be Concentration

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75301]
### Is your feature request related to a problem? Please describe.

The Electrokinetic's Electrical Discharge and Voltaic Strikes are decent little combat buffs, but their short duration makes them annoying to constantly reapply, and it's actually kind of a big Stamina investment to fire both of them off at the start of a battle.

### Solution you would like.

Make them both Concentration powers.

**Comment by Standing-Storm** [comment]
I thought this about Blazing Aura too when you put up that PR to remove the C from the name, and I was like "What, really? Isn't that concen...oh."

I think that dates before I had a concentration system in place. Now that there is one, there's an additional cost to keeping Blazing Aura/Voltaic Strikes/etc up (they take a slot that could be used by other buffs), so swapping them all over to Concentration is probably a good idea. I can put up a PR later today or tomorrow.

**Comment by Terrorforge** [comment]
I've had similar thoughts, but Blazing Aura feels better to use that way because it's pretty fucking deadly. Certainly could be Concentration, though.

And yeah, this makes them better at lower levels when they're basically the only damage options electrokinetics have, but gives them more opportunity cost for already powerful characters.

There's actually a whole load of powers that could probably be Concentration. Let me just blurt out a list of candidates and you can make your own decisions:
- Oxygen Absorption
- Hardened Skin (I'm a strong advocate for this one)
- Sealed System
- Neuro-acceleration
- Trick of the Light
- Thermogenesis (not sure if this even works tho)
- Slowfall

**Comment by emixa-d** [comment]
"Sealed System" is problematic for concentration power -- going by the description, you take a huge breath of air and use that as safe air source (as long as the effect lasts).  So, if the source runs out and you take a new breath while standing in acidic radioactive smoke, you would be in trouble.

(This is not actually implemented AFAICT.)

As such, there would need to be an indication to the player how long the breath is going to last, so they can take a small break in a safe area _before_ the air runs out.

**Comment by Terrorforge** [comment]
Implemented by #75313
