### ISSUE TITLE
Mirror estoc does not display when wielded by player in chibi ultica, though it does appear on enemy sprites

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#75317]
### Describe the bug

Mirror estoc does not display when wielded. weapon is from xedra mod

### Attach save file

[Petrichor-trimmed.tar.gz](https://github.com/user-attachments/files/16419090/Petrichor-trimmed.tar.gz)

### Steps to reproduce

get mirrored estoc
wield it
nographic

### Expected behavior

Expected overlay to show character wielding

### Screenshots

![image](https://github.com/user-attachments/assets/aea41cc3-4fc4-49df-87ce-488464464269)
![image](https://github.com/user-attachments/assets/5b778727-5f89-4f39-bef6-363a28cf77f8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: 6e69fb7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    Xedra Evolved [xedra_evolved]
]

### Additional context

overlay seems to work for enemies

**Comment by casswedson** [comment]
We don't have a sprite for the mirrored stock in msx to begin with so no there isn't an overlay for it
![Screenshot_2024-07-29_18-29-35](https://github.com/user-attachments/assets/930de1db-28a5-4977-be99-440bb072c817)

**Comment by Consoleable** [comment]
I guess I have misunderstood. What is: 
![image](https://github.com/user-attachments/assets/df4cbc66-b776-4faa-8712-90d73dbc17b5)
is this just for enemies?

**Comment by Consoleable** [comment]
> what that does is setting a sprite for an item when it's on the ground and an monster sprite; it works like that
> 
> also this issue should be moved to: https://github.com/I-am-Erk/CDDA-Tilesets/issues
> 
> this is fairly easy to patch, I recommend you try to fix it yourself - cause that would be far faster

I would genuinely really like to, i was trying to figure out how when i made this issue is there a tutorial for making items appear on the player sprite?
