### ISSUE TITLE
Make asthmatics use their least full inhaler

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75326]
### Is your feature request related to a problem? Please describe.

Characters with the "Asthmatic" trait will automatically use an inhaler when they have an asthma attack. However, they seem to prefer using the inhaler with the most charges remaining. Or maybe its some other metric, but they definitely don't do what would make sense, which is to finish one inhaler before starting in on the next.

It's not like it's a huge sacrifice to just throw out an inhaler with 11 charges remaining, but it is a bit annoying and tends to leave your inventory more cluttered than it needs to be.

### Solution you would like.

Make the character always use the inhaler with the least charges.

**Comment by PatrikLundell** [comment]
My guess is that they'd use the first usable inhaler found in the search, because that's what's easiest to implement while also being the fastest.
