### ISSUE TITLE
12 Miscellaneous Extremely Minor Issues

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#75327]
### Is your feature request related to a problem? Please describe.

I'm back with yet another report of random minor issues I find while translating the project to French, today I have 12 for anyone with the time and inclination to fix them.

### Solution you would like.

Megafauna's giant horses are capitalized for some reason:
- [x] Giant horses -> giant horses

Megafauna's American zebra has a double period at the end of its description:
- [x] A hooved grazing mammal with a brown-and-white striped coat.  . -> A hooved grazing mammal with a brown-and-white striped coat.

The description of Mind over Matter's Heightened Reflexes spell lacks a period in its first section:
- [x] You can improve your sensory acuity and the speed at which your brain processes sensory inputs -> You can improve your sensory acuity and the speed at which your brain processes sensory inputs.

Mind over Matter's message for the contemplation EoC refusal due to excessive exhaustion lacks an end period:
- [x] You are too exhausted to contemplate anything -> You are too exhausted to contemplate anything.

The description of Magiclysm's Scroll of Slowfall makes little sense since you know... you're not learning the spell, you're just using a single use scroll to get its effect:
- [x] Who's afraid of heights?  Not you, after you learn this spell. -> Who's afraid of heights?  Not you, after you use this scroll.

Magiclysm's mayapple potion fruit eating action message differs from every other single potion fruit (in comparison to handful potion fruits):
- [x] Eat the mayapple potion fruits. -> Eat the mayapple potion fruit.

One of Xedra Evolved's special monster attacks is badly written when a monster attacks a NPC:
- [x] [monster] bites and injects poison into your [NPC]! -> [monster] bites and injects poison into [NPC]!

Xedra Evolved's sparking sphere artifact shouldn't be capitalized:
- [x] Sparking spheres -> sparking spheres

Aftershock's Abnormal Augmentations starting scenario has unnecessary punctuation (no real need for a point behind corp):
- [x] You've already been modified mutagenically but now you were all ready for a bionic implant or three - the bill footed by the corp., of course -> You've already been modified mutagenically but now you were all ready for a bionic implant or three - the bill footed by the corp, of course

One Liam's dialogue lines has double end punctuation:
- [x] Thanks man, I'll keep that in mind.  We gotta do this though.  Any suggestions for how to do it safely?. -> Thanks man, I'll keep that in mind.  We gotta do this though.  Any suggestions for how to do it safely?

Liam's dialogue where you ask him his Cataclysm story doesn't capitalize Cataclysm, despite this being, from what I can see, the standard in NPC dialogue:
- [x] How did you make it through the cataclysm? -> How did you make it through the Cataclysm?

One of the Old Guard's epilogue messages has a double end period:
- [x] The steadfastness of individual survivors after the Cataclysm impressed the tattered remains of the once glorious union.  Spurred on by numerous strategic successes, a number of operations to re-secure facilities succeeded thanks to the support of various surviving communities.  While some remained cautious of submitting themselves to the Old Guard's authority, nostalgia for the old world and the promise of security from the new rallied many more to their flag..

### Describe alternatives you have considered.

- Looking for more
- Including fewer
- Not listing them
- Fixing them myself

**Comment by Standing-Storm** [comment]
> you're not learning the spell, you're just using a single use scroll to get its effect:

I should point out this is not actually true--scrolls in Magiclysm are studied to gain the spell, they aren't D&D-style single-use items.

**Comment by sadenar** [comment]
> > you're not learning the spell, you're just using a single use scroll to get its effect:
> 
> I should point out this is not actually true--scrolls in Magiclysm are studied to gain the spell, they aren't D&D-style single-use items.

My bad then, I assumed they were Pathfinder/DnD analogue single use things out of ignorance.

**Comment by merrygin** [comment]
Thanks for pointing out my typos in Megafauna! Fixed 'em right away, hope that's alright for you.
The reason giant horses are capitalized is that I'm German and sometimes that bleeds into my English spelling. :dancing_men:
