### ISSUE TITLE
batteries are more energy dense than plutonium

### ISSUE THREAD

**Issue by dynst** [CleverRaven/Cataclysm-DDA#75336]
### Is your feature request related to a problem? Please describe.

A `plut_cell` is

https://github.com/CleverRaven/Cataclysm-DDA/blob/0b942b331321bad62b7ae3879974a7cd7f5ed05e/data/json/items/ammo.json#L464-L466

A [`minireactor`](https://github.com/CleverRaven/Cataclysm-DDA/blob/0b942b331321bad62b7ae3879974a7cd7f5ed05e/data/mods/Aftershock/vehicles/part_items.json#L55) can hold 10,000 plutonium cells, and each consumed cell produces just 100 kJ of power (since for many years now, a 'unit of battery' = 1 kJ).

https://github.com/CleverRaven/Cataclysm-DDA/blob/0b942b331321bad62b7ae3879974a7cd7f5ed05e/data/mods/Aftershock/vehicles/vehicle_parts.json#L149-L150

100 kJ in 80 g gives an energy density of 1250 kJ/kg. Which seems kinda low for sci-fi plutonium super-science.

A `light_battery_cell` holds the same amount of energy, 100 kJ, but weighs less than a plutonium cell at only 30 g. It has an energy density of over 3300 kJ/kg.

https://github.com/CleverRaven/Cataclysm-DDA/blob/0b942b331321bad62b7ae3879974a7cd7f5ed05e/data/json/items/battery.json#L71-L72

A zinc-carbon `light_dry_cell` from #54287 stores 100 kJ in 20 g, making it even more energy-dense at 5000 kJ/kg.

### Solution you would like.

In real life, rechargeable lithium ion batteries usually have an energy density closer to [460 kJ/kg](https://web.archive.org/web/20090428060954/http://www.allaboutbatteries.com/Battery-Energy.html), so the batteries should probably either weigh more or hold less energy.

According to https://www.epectec.com/batteries/chemistry/ zinc-carbon batteries are 0.13 MJ/kg (130 kJ/kg).

### Additional context

Densities for vehicle batteries were already overhauled in #57193.

Battery density was increased back in #37146.

**Comment by masema** [comment]
Second problem. Plutonium has an energy density of .57 kJ/kg, so a single Plutonium cell should so each cell should produce, _at most_ 45 kJ

**Comment by dynst** [comment]
>  Plutonium has an energy density of .57 kJ/kg

Where'd you get that? In a fission reactor, plutonium-239 generates electricity at a rate of 31,000,000,000 kJ/kg ([31,000,000 MJ/kg](https://en.wikipedia.org/wiki/Energy_density)). And for game purposes, the plutonium cells are just energy-dense handwavium and not intended to be realistic IIUC, in which case a minireactor should probably generate more, not less energy from each cell.

**Comment by kevingranade** [comment]
The whole plutonium thing is a red herring, the issue is that batteries for handheld devices have way too high energy density.

**Comment by x-qq** [comment]
> In real life, rechargeable lithium ion batteries usually have an energy density closer to 460 kJ/kg, so the batteries should probably either weigh more or hold less energy.

According to https://www.researchgate.net/publication/328396021_Energy_Density_of_Cylindrical_Li-Ion_Cells_A_Comparison_of_Commercial_18650_to_the_21700_Cells lithium-ion cells have around 230 Wh/kg density, and according to https://www.cei.washington.edu/research/energy-storage/lithium-ion-battery/ up to 330 Wh/kg.

1 Wh/kg is 3.6 kJ/kg, so according to these sources real life densities are 828-1188 kJ/kg.

But that aside, does this issue have any negative effect on the gameplay?

**Comment by dynst** [comment]
>  according to https://www.cei.washington.edu/research/energy-storage/lithium-ion-battery/ up to 330 Wh/kg.

I said 'usually,' and 'closer to.' There's no contradiction here. Those high end, cutting-edge, experimental numbers, that haven't necessarily even been commercialized yet, and that are very carefully prefixed with the qualifier 'as high as,' are very, very far from the commonplace, hold-em-in-your-hands, rechargeable lithium ion batteries that we're actually talking about in this case.

And it was only a few months ago in May 2024 that that record-breaking '323 Wh/kg' number got reported in a press release. (For some reason, that University of Washington web page is quietly rounding up 323 to "as high as" 330 Wh/kg.)

> The P73 cell achieved 294 Wh/kg, the P79 cell 323 Wh/kg. This makes the P79 cell the new record holder and underlines the innovative strength of Farasis Energy.

**Comment by kevingranade** [comment]
Multiple sources are telling me real commercially available and lootable lithium batteries are available in the up to 800 kj/kg range and higher capacities are rare to nonexistent,  and even when present are going to be too specialized to do anything with.
Standalone batteries are in even worse shape and I'm looking at a bit over half that (500 kJ/kg) for these batteries, I'm also looking at differentiating between some other battery chemustries which is mostly bad news for those batteries,  except for premium disposable batteries that weigh in at about 1000 kJ / kg.

**Comment by x-qq** [comment]
May be of interest:
* 2023 Statista report on the topic (requires an account) https://www.statista.com/statistics/1422973/specific-energy-of-battery-energy-systems/
* Types of Lithium Ion batteries https://batteryuniversity.com/article/bu-205-types-of-lithium-ion
* State of the Art of Lithium-Ion Battery SOC Estimation for Electrical Vehicles (July 2018) https://www.researchgate.net/publication/326336142_State_of_the_Art_of_Lithium-Ion_Battery_SOC_Estimation_for_Electrical_Vehicles
