### ISSUE TITLE
Teleporting in battle bug. 

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#75367]
### Describe the bug

Sometime i was teleported in small radius when I'm fighting. It could kill me if i am on rooftops or else. 
It happens occasionally with message in log: "You feel yanked in a non-existent direction!" 

### Attach save file

[Кукуево-trimmed.tar (1).gz](https://github.com/user-attachments/files/16452738/-trimmed.tar.1.gz)

### Steps to reproduce

It happens occasionally but my save has a lot of this bugs. 

### Expected behavior

No random teleportation in battles. 

### Screenshots

![Screenshot_2024-08-01-13-41-54-237_com cleverraven cataclysmdda experimental](https://github.com/user-attachments/assets/c05bc204-e632-459e-a48a-d36d3e0c2abb)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.3.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-07-26-0048 8002d98 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.6%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Магиклизм [magiclysm],
    Разум над материей [mindovermatter],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Aftershock [aftershock],
    Отключить потребности у НПС [no_npc_food],
    Медленный рост фунгалоидов [no_fungal_growth],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Мифические стили ближнего боя [MMA],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    Помпезные перки [bombastic_perks]
]

**Comment by GuardianDll** [comment]
There is nothing in the repo that has this message. I suspect it is something from arcana mod

**Comment by Cupidatis** [comment]
> There is nothing in the repo that has this message. I suspect it is something from arcana mod

If so i puting this issue in Arcana github

**Comment by GuardianDll** [comment]
<https://github.com/chaosvolt/cdda-arcana-mod/blob/a6c2d862edfaedde5ac1c47221b3847a75cc8b0d/Arcana/items/armor.json#L308>
