### ISSUE TITLE
Error when grab-moving deployed solar suitcase.

### ISSUE THREAD

**Issue by Zaustie** [CleverRaven/Cataclysm-DDA#75366]
### Describe the bug

When moving a deployed solar suitcase using the grab mechanic the solar suitcase goes out of bounds and causes errors on every move.
(attached save file shows the game state after the suitcase was moved).

Delving into the map json shows that the solar suitcase vehicle gets a large negative number assigned to both x and y coordinate after trying to move it using the grab mechanic.

### Attach save file

[Struble-trimmed.tar.gz](https://github.com/user-attachments/files/16452588/Struble-trimmed.tar.gz)

### Steps to reproduce

1. make character and grant item 'solar suitcase'
2. deploy solar suitcase
3. Grab and move the deployed suitcase
4. error occurs and suitcase gets assigned an invalid map position.

### Expected behavior

Solar suitcase should not get disappear by having wrong coordinates assigned to it.

### Versions and configuration

OS: arch linux, self compiled with TILES=1, SOUND=1 and RELEASE=1
VERSION  : cdda-experimental-2024-07-31-0403 836a1ce5c1

### Additional context

 DEBUG    : Tried to access invalid map position at grid (-178956965,-178956965,0)

 FUNCTION : size_t map::get_nonant(const tripoint_rel_sm&) const
 FILE     : src/map.cpp
 LINE     : 10283
 VERSION  : cdda-experimental-2024-07-31-0403 836a1ce5c1

**Comment by PatrikLundell** [comment]
/Confirmed

Following the instructions I get an error message complaining that the base item doesn't match the deployed one. Only after that do I get the coordinate error message.
Grabbing the appliance causes it to disappear.
The same happens with the foldable panel.

Hacking iuse_actor.cpp operation deploy_appliance_actor::use to skip the last (optional) parameter causes the first error message to go away, while the one reported by this report remains. However, the appliance can now be dragged.
The reason for the first message is that the item itself is passed into the operation, while the parameter expected is the deployed version of it.
A guess is that you'd need to pass in the deployed fake item with correct coordinates to not get the coordinate error, but that has not been attempted.
