### ISSUE TITLE
World created after save&quit from the tutorial has a fixed 20C temperature everywhere

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#75375]
### Describe the bug

<s>Currently temperature in basements is the same as temperature outdoors, this is significantly detrimental for early game preservation of perishable food.</s>
EDIT: There is a fixed temperature of 20C everywhere in a world that was created after leaving the tutorial.

### Attach save file

An attached save has been provided in a comment.
https://github.com/CleverRaven/Cataclysm-DDA/issues/75375#issuecomment-2263980778

### Steps to reproduce

Detailed reproduce steps have been provided in a comment.
https://github.com/CleverRaven/Cataclysm-DDA/issues/75375#issuecomment-2265607643

### Expected behavior

<s>Temperature in basements should be significantly less than temperature outdoors</s>
Worlds should not have unintended effects on other worlds.

### Screenshots

https://i.imgur.com/g0PTW1n.png

### Versions and configuration

Game version: cdda-linux-tiles-x64-2024-07-24-1630

**Comment by GuardianDll** [comment]
Temperature in basement should always be 6 centigrade, not sure how did you make it 20

**Comment by x-qq** [comment]
The game is not modified in any way, world settings are all default.

**Comment by Void-Seeker** [comment]
Not confirming in my save, it is 6 °C for me. Maybe some floor/roof bugs?

**Comment by x-qq** [comment]
Attaching a save that reproduces an issue - a fresh character in a fresh world standing with a spawned thermometer in a shelter basement with 20C temperature.

![Untitled](https://github.com/user-attachments/assets/dea0363b-4cc0-4d49-aa7d-f4313ef6a9b4)


[Temperature-Test-World.zip](https://github.com/user-attachments/files/16461833/Temperature-Test-World.zip)

**Comment by PatrikLundell** [comment]
Confirmed in the save by examine the readout, teleport to a subway station and descend there too. Same temperature both above and below ground (still 20).

Failed to verify generally, as my own character's save still has the expected temperature of 6 degrees in the basement.

**Comment by x-qq** [comment]
I may have discovered a reliable way to reproduce this, from a clean state, here are the detailed steps:

1. Download the game release from github, in my case it's cdda-linux-tiles-x64-2024-07-24-1630.tar.gz file, and unpack it.
2. Launch the game.
3. From the main menu, press Tutorial Game.
4. ESC -> Save and quit -> confirm the warning about saving in tutorial -> confirm save and quit
5. From the main menu, go World -> Create World, finish without changing any settings.
6. From the main menu, go New Game -> Custom Charactrer, press TAB as many times as needed and confirm to finish.
7. In game, change interface options to show temperature in Celsius and in keybinding options add a keybinding for a debug menu.
8. Spawn a thermometer using a debug menu. Look at the temperature. Go to the shelter basement and look again. It shows 20C.

**Comment by PatrikLundell** [comment]
This would indicate there's some state not cleared out properly when quitting a world and creating another one. The tutorial probably disables a lot of functionality to ensure it behaves in a predictable manner, with weather and associated temperature changes probably among them.

**Comment by x-qq** [comment]
I have updated the title and description with newly discovered information.
