### ISSUE TITLE
Add Shillelagh (and loaded stick) to training weapon for Bashing(Intermediate)

### ISSUE THREAD

**Issue by Wittyson** [CleverRaven/Cataclysm-DDA#75383]
### Is your feature request related to a problem? Please describe.

When I spend the time training my carving skill & finding a good weapon, the Shillelagh draws me in due to its cheap recipe & effective DPS. However, due to it not being a training weapon, I need to craft a Bo/Ironshod quarterstaff to help train to level 4. 

### Solution you would like.

Adding it to the list of weapons used to train Bashing (Intermediate) so a weapon that takes 6 hours to craft doesn't require an additional 5 hours to train when crafting a Bo

**Comment by NetSysFire** [comment]
The shillelagh can already be used.

https://github.com/CleverRaven/Cataclysm-DDA/blob/09410b2578f51e5a0604f2a18e80ae1fd5ff3a66/data/json/recipes/practice/melee.json#L230-L236

https://github.com/CleverRaven/Cataclysm-DDA/blob/09410b2578f51e5a0604f2a18e80ae1fd5ff3a66/data/json/requirements/melee.json#L489-L496
