### ISSUE TITLE
Hotplate variants' power consumption values are contrary to descriptions

### ISSUE THREAD

**Issue by djefferd** [CleverRaven/Cataclysm-DDA#75391]
### Describe the bug

Hello,

Both the atomic coffeemaker and the induction hotplate claim to be more energy efficient in their descriptions. When I went to look in the JSON to put some numbers to those claims, I was baffled by what I found. Hotplate, atomic coffeemaker, and regular coffeemaker all have the same charge_rate value of 1KW. The Induction hotplate has a value of 1.5KW! The last one seems like the worst of the bunch, despite being a lab drop and claiming to be better. The atomic coffeemaker does not appear to differ from the regular coffeemaker.

Wondering if a larger value was counter-intuitively better, I ran a test by heating up the same kind of food item on a fully charged battery using a hotplate and an induction hotplate. The hotplate took 19W to heat the food, while the induction hotplate took 25W.

From the 0.H JSON: \data\json\items\tool\cooking.json:

    "name": { "str": "atomic coffeemaker" },
    "use_action": [ "HOTPLATE_ATOMIC", { "type": "link_up", "cable_length": 2, "charge_rate": "1 kW" } ],

    "name": { "str": "coffeemaker" },
    "use_action": [ "HOTPLATE", { "type": "link_up", "cable_length": 2, "charge_rate": "1 kW" } ],

    "name": { "str": "induction hotplate" },
    "use_action": [ "HOTPLATE", { "type": "link_up", "cable_length": 3, "charge_rate": "1500 W" } ],

I suggest changing the atomic coffeemaker and the induction hotplate charge_rate values to 750W to make them superior.

Cheers.

### Attach save file

N/A

### Steps to reproduce

Heat an identical food or beverage with the various appliances and see energy removed from the attached battery.

Also, read the JSON above.

### Expected behavior

Atomic Coffeemaker and Induction Hotplate should draw LESS power than their more common variants.

### Versions and configuration

0.H RC - 2024-07-26-2355

**Comment by RenechCDDA** [comment]
Charge_rate has nothing to do with [their efficiency](https://github.com/CleverRaven/Cataclysm-DDA/blob/0ca32b80f7d912ee78ad11316791eefb02c00ef6/data/json/requirements/cooking_tools.json#L3-L30).

From JSON_INFO.md:

```
  "charge_rate": "60 W",   // (optional) The charge rate of the plugged-in device's batteries in watts. Defaults to "0 W"
                           // A positive value will charge the device's chargeable batteries at the expense of the connected power grid
                           // A negative value will charge the connected electrical grid's batteries at the expense of the device's
                           // A value of 0 won't charge the device's batteries, but will still let the device operate off of the connected power grid
```
