### ISSUE TITLE
[Bombastic Perks] Flawless Memory Usability is tied to if you are in fullscreen or not

### ISSUE THREAD

**Issue by likowski1** [CleverRaven/Cataclysm-DDA#75406]
### Describe the bug

Flawless Memory is somehow Linked to Display setting

### Attach save file

[World of Lunancy-trimmed.tar.gz](https://github.com/user-attachments/files/16476225/World.of.Lunancy-trimmed.tar.gz)

### Steps to reproduce

1. Acqure the Flawless Memory perk from Bombastic Perks
2. Test in Windowed mode to find it work perfectly fine
3. switch your game to borderless and find that your Flawless memory is harder to use

### Expected behavior

i expect that Flawless memory to be usable at any time

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3737 (22H2)
- Game Version: 4ceb3da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Alternative Map Key [alt_map_key],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Disable NPC Needs [no_npc_food],
    Mythical Martial Arts [MMA]
]

### Additional context

i was trying to make a Gif to send into github to show what was going on my end and accidently discovered this

**Comment by SariusSkelrets** [comment]
Tried on the same version with the provided save. Couldn't reproduce
Took a bunch of selfies, played games, scanned books then read a scanned book (all from the [a]ctivate menu). The flawless memory was still usable after all that

Could you detail the precise steps more? It might be that a very precise set of steps is causing your issue

**Comment by likowski1** [comment]
here is a Video i turned into a GIF that details what i see on my end ![Flawed Memory](https://github.com/user-attachments/assets/4fb7daff-aa81-4510-8576-6bccf04e6dbe)

**Comment by SariusSkelrets** [comment]
Tried on the same version with the provided save both in and out of fullscreen. Still cannot reproduce

Took a bunch of selfies, read a scanned book, scanned another one then read it, opened a game and played it (all from the [a]ctivate menu). The flawless memory was still usable after all that
