### ISSUE TITLE
Animal Cooking Oil registers as a vegetable

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75421]
### Describe the bug

Animal cooking oil counts as a vegetable for allergy purposes.

This appears to be because animal oil (cooking_oil2) is mostly a copy-from of vegetable cooking oil (cooking_oil), and as such inherits the veggy_allergen vitamin. They're both in drink_other.json

### Attach save file

trivially reproducible

### Steps to reproduce

1. Take "Hates vegetables"
2. Look at animal cooking oil

### Expected behavior

animal products are not vegetables

### Screenshots

![image](https://github.com/user-attachments/assets/e2e13f5c-c575-46af-97b8-75ca9a71e9f6)
Will cause allergic reaction

![image](https://github.com/user-attachments/assets/57512d19-1b95-4718-a03a-bad60567eff0)
Character is not meat intolerant, but does hate vegetables

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 09410b2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    My personal mod [terror_mod]
]

### Additional context

And yes, this does matter for cooked foods. As of changing over to the vitamin system, meat fried in vegetable oil counts as a vegetable and vice versa. Which makes sense for actual allergies, but reads a bit strange for the "allergy" traits that are flavored as preferences.

**Comment by Karol1223** [comment]
This appears to be caused by the fact that ``vitamins`` field does not overwrite properly when used with ``copy-from``, instead the new ``vitamins`` field is added on top of the old one. This needs a C++ fix.
