### ISSUE TITLE
Time keeps advancing even though I take no action

### ISSUE THREAD

**Issue by goibnus** [CleverRaven/Cataclysm-DDA#75423]
### Describe the bug

In the newest release candidate, the clock runs forward even if I am not taking any action.  I tried unplugging both my keyboard and my mouse to check and make sure that no inerrant input was getting in.

### Attach save file

[Wanchese-trimmed.tar.gz](https://github.com/user-attachments/files/16482380/Wanchese-trimmed.tar.gz)

### Steps to reproduce

For me, just open the save.  I got the minimized save out of the archive to make sure that the issue is in the uploaded file.

### Expected behavior

Time should not advance if I'm standing in an open field and not doing any extended task (like crafting)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: c06f12d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Hyperseeker** [comment]
Is there any chance you have `Realtime turn progression` set to anything above `0.00` in the settings?

**Comment by goibnus** [comment]
...yes.  Turning that off resolves the issue.  Is that on by default, or did I press a key?  I've never seen that before and this is a fresh 0.H install for testing.

**Comment by GuardianDll** [comment]
You turned it on, this feature is old as rocks (and we suspected it doesn't even works)
Glad it got resolved fast

**Comment by goibnus** [comment]
To quote Isidor Isaac Rabi, “Who ordered _this_?”  :)
