### ISSUE TITLE
Game attempts to place followers underground

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75428]
### Describe the bug

Set up one of those "anywhere" bases in a hunting lodge, recruited a pair of NPCs and told them to go back there.

When I arrived back there myself, the game threw two "Failed to place NPC" errors. The error suggested it had tried to place them one Z-level below ground, and using debug to take control of them revealed that they were in fact stuck in the bedrock.

Apparently the game tried to place them in the lodge's basement, which is odd. I did not create the camp in the basement, and the bulleting board is above ground.

### Attach save file

[New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16483110/New.Mind-trimmed.tar.gz)

### Steps to reproduce

1. Create basecamp in hunting lodge
2. Tell NPC to go there from some distance again

### Expected behavior

NPCs spawn above ground, in places it is possible for them to be

### Screenshots
![image](https://github.com/user-attachments/assets/19b7b367-61af-473f-994e-d145e669a732)
Go here

![image](https://github.com/user-attachments/assets/6b0eab78-4be9-47de-af17-7b15618e45fb)
Location of base. Note bulleting board

![Screenshot 2024-08-03 23 47 35](https://github.com/user-attachments/assets/c22bc018-b2fa-4531-841b-ef65a1b53fcd)
The error

![image](https://github.com/user-attachments/assets/c40a5105-9cfb-463d-a6f5-8d52dcecef49)
Brigitte stuck in the bedrock

![image](https://github.com/user-attachments/assets/d2065937-3dd0-44eb-a7ef-010451bb91d7)
Von Barone too

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 09410b2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    My personal mod [terror_mod]
]

**Comment by Terrorforge** [comment]
I fixed the problem with my save archives and have now included a proper save archive in the OP.

**Comment by Terrorforge** [comment]
After dicking around with backups for testing purposes, I loaded a save close to the provided archive, and went back to just playing. I went back home and found Von Barone trapped underground as described.

I then went and did some crafting before bed, and while I was doing that Brigitte LaCroix arrived without incident. So either it's fine if you're actually there when the NPC shows up, or it's just inconsistent.

**Comment by Terrorforge** [comment]
... but when I load the save, they just get shunted underground again.

**Comment by Terrorforge** [comment]
Had to load a backup again, and this time when Brigitte shows up while I'm there, it doesn't place her properly. It throws the same error over and over:
![image](https://github.com/user-attachments/assets/caf5d6d6-7b70-44a5-9141-05dfb0be3a07)

![image](https://github.com/user-attachments/assets/8686c599-6cfb-4b34-bd57-eeeffeb29748)
Faction screen suggests she's above ground, some 15 map tiles to the east.

![image](https://github.com/user-attachments/assets/0f9d4caa-4dee-4a82-a5ab-a6be29941d9e)
And indeed I found her there.

**Comment by PatrikLundell** [comment]
Trying to reproduce.
- Some private mod missing.
- Report about excessive error repetition about "failed to convert variable "npctalk_var_nether_attunement_power_scaling" with value "0.75" to a number" when trying to walk to the base (as the bugger refuses to use the car). This seems to hang the game.

Trying again and teleporting back resulted in:
 DEBUG    : Failed to place NPC in a valid location near (83,65,-1)

 FUNCTION : place_on_map
 FILE     : C:\Cataclysm-DDA\src\npc.cpp
 LINE     : 1051
 VERSION  : 0.G-11130-g1fc1e9a0ea-dirty

Von Barone was indeed placed within the soil.

/Confirmed

**Comment by Terrorforge** [comment]
Whoops, forgot about the private mod. I was just dicking around with some difficulty settings that didnt turn out to matter, so it shouldn't change anything, but I'll remove it from my world to prevent future mishaps.

**Comment by PatrikLundell** [comment]
No longer needed, I've found the bug!
