### ISSUE TITLE
Phase immersion suit description is misleading

### ISSUE THREAD

**Issue by Void-Seeker** [CleverRaven/Cataclysm-DDA#75477]
### Describe the bug

Phase immersion suit description states that "it offers unparalleled environmental protection, both in this Earth and beyond", but 60 °C in the Mi-go tower is already too much for it to handle.

### Attach save file

N/A

### Steps to reproduce

1. Obtain Phase immersion suit.
2. Enter Mi-go building with the suit turn on.
3. Suffer.

### Expected behavior

Suit should do what it says it will do.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.2; Release: 21.2; Codename: victoria; 
- Game Version: cdda-experimental-2024-08-06-0149 3f860f1 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,4%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    иконки видит-игрока, бег, приседание, кровотечение для retrodays [sees_player_retro],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Скорость от ловкости [speedydex]
]

**Comment by x-qq** [comment]
Confirmed in cdda-linux-tiles-x64-2024-08-03-0533

![Untitled1](https://github.com/user-attachments/assets/b5e1e158-314d-4be4-bdbb-e39318cc62d9)


![Untitled2](https://github.com/user-attachments/assets/30c5ddac-9f24-4edf-88da-fd0a0394cc61)

**Comment by Sniper27IT** [comment]
As 11/11/24, the issue persists
[Evensville-trimmed.tar.gz](https://github.com/user-attachments/files/17706726/Evensville-trimmed.tar.gz)

**Comment by kevingranade** [comment]
There's only so much environmental protection can do to resist pervasive heat. If we get an insulation feature this would be a candidate,  but that still wouldn't do any more than buy you some time.
