### ISSUE TITLE
[MoM] Make Blazing Aura an AoE DoT

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75482]
### Is your feature request related to a problem? Please describe.

The descriptions for Blazing Aura suggest that it generates intense heat that burns everything close to the pyrokinetic, but that's not how it actually works. Instead, it sets up a basic enchant that adds fire damage to the player's attack, as well as a "thorns" effect that deals fire damage to enemies that attack the player. This is both unintuitive and contrary to the intended flavor.

### Solution you would like.

Change it to deal constant damage in a small AoE around the player. Something like 0.5xlevel to 1.5xlevel (+int, +attunement) heat damage every turn to adjacent enemies sounds right to me. Maybe as little as 0.5-1.0 so it doesn't get quite as stupid at higher attunement. If we're feeling frisky, perhaps allow the AoE to increase to two or even three tiles at the highest levels/attunement.

### Describe alternatives you have considered.

Canonize the current functionality and change the descriptions. I find this alternative difficult to justify in terms of flavor; what are you doing, exactly, that imbues your attacks with tremendous heat _and_ strikes out at your enemies when they strike at you? You could split it out into two separate powers or try to justify it as summoning an armor of fire or something, but in either case you're just turning it into something completelt different.

Also this current version kind of steps on Electrokinesis's toes, as that path already has two separate powers that imbue their attacks and defenses respectively with their element, and it's a little boring to just do "that, but fire". Arguably my proposal is similarly similar to Galvanic Aura, but I think there's enough difference between zapping one guy and sending out some sparks every few seconds in a wide area and consistently damaging everything in a very small area for them to feel like different abilities. Plus I think it would really speak to the identities of these two paths if they had versions of the same power where the Electrokinesis one is safe but unreliable whereas the Pyrokinesis one consistently destroys everything in its path whether you want it to or not.

### Additional context

I presume it's like this due to technical limitations, but the current implementation is the same as when MoM was first added to the repository and I'm pretty sure those limitations are no longer in place.

**Comment by Terrorforge** [comment]
Oh, whoof. I guess you could do less frequent pulses, but at what point does it actually become practical? I could imagine it still being decent if it did the same kind of damage I suggested at like 2 or 3 tiles but only every two or three turns.

But maybe I just adjust the descriptions instead. Something about how it's a very intense heat that clings closely to your body?

**Comment by Standing-Storm** [comment]
If only anyone else were affected by heat, this would be easy, because ideally things nearby would have a chance of combusting due to the heat (as you say), but just blasting out heat fields wouldn't do anything to anyone else, and damage-causing EoCs can't cause specific damage types that armor protects against, nor can they read the armor values of the target. 

> But maybe I just adjust the descriptions instead. Something about how it's a very intense heat that clings closely to your body?

For the moment, at least, that might be best. I can try some experimenting with it after I'm done switching things over to concentration.

**Comment by Standing-Storm** [comment]
Profiling.

Normal:

![Untitled](https://github.com/user-attachments/assets/18dbe8de-c572-42a1-aa61-17e35b544c60)

With that biomancer effect that uses an intermittent_casting: 

![Untitled](https://github.com/user-attachments/assets/4700362a-0a8f-4b15-bc0f-c1bd459e024f)

So literally over 100x slower.

**Comment by Terrorforge** [comment]
Implemented by #76648
