### ISSUE TITLE
Screaming should drain stamina

### ISSUE THREAD

**Issue by strategictraveler** [CleverRaven/Cataclysm-DDA#75490]
### Is your feature request related to a problem? Please describe.

Players should not be able to scream infinitely without any drawbacks.

### Solution you would like.

Screaming should drain your stamina by a set amount (probably negligible at full stamina) each time you scream. You would be unable to scream when winded, and also unable to talk/scream to NPCs until you regain your stamina.

E.g. if the player is in a dangerous situation and a friendly NPC is nearby but unaware of their presence, they should not be able to scream  for help if they're fully out of stamina.	

### Additional context

Players should get a message in the log when screaming while winded, e.g: "Your stamina is too low to be able to scream."

**Comment by ZhilkinSerg** [comment]
That does not make any sense
