### ISSUE TITLE
Flathub upload

### ISSUE THREAD

**Issue by grisha765** [CleverRaven/Cataclysm-DDA#75504]
### Is your feature request related to a problem? Please describe.

Hi, I created a manifest to submit the game to flathub so people can download it easily on linux using flatpak, needs approval from author/developer/upstream.
https://github.com/grisha765/flathub/tree/org.Cataclysm.DDA.Tiles

### Solution you would like.

approval from author/developer/upstream is required

### Describe alternatives you have considered.

Download tar.gz, unpack, install dependencies.

**Comment by grisha765** [comment]
> this one is just implementation?

yes, as i understood from that discussion, Kevin seems to agree.

**Comment by kevingranade** [comment]
Thank you,  I believe I understand what I need to do next and I'll follow up on it as soon as I have time.

**Comment by grisha765** [comment]
> Thank you, I believe I understand what I need to do next and I'll follow up on it as soon as I have time.

I'm trying to do this now, waiting for approval from the flathub people

**Comment by grisha765** [comment]
Successfully published https://flathub.org/apps/org.cataclysmdda.CataclysmDDA
