### ISSUE TITLE
Allow npc `anger`, `value`, `fear`, and `trust` values to be edited with remote EOCs.

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#75517]
### Is your feature request related to a problem? Please describe.

Recently, I have been experimenting with remotely editing an NPC's `anger`, `fear`, `value`, and `trust` values towards the player with EOC's. I have discovered that this is not possible, since these values require a `n_val` beta talker when used in `math`, which is entirely unsupported with EOCs.

### Solution you would like.

I would like to be able to edit these values remotely without requiring the player to talk to the NPC to set a beta talker. My envisioned solution would be to have these values register with `u_val`, and silently fail when run on the current player character. When run against an NPC, say using `u_run_npc_eocs` or a non-global EOC, then a function retrieves the ID of the player character and gets the values as it normally would. This would open up a lot of possibilities in the future for NPC stuff, such as automatic triggers or dynamic mood changes.

### Describe alternatives you have considered.

Not having this ability and relying on duplicate variables as a replacement. However, this is redundant and doesn't properly interface with some fringe functions. It's also weird to be able to check an NPC's opinion and see entirely different values pop up when compared to what they're telling you about or reacting to.

### Additional context

I'm currently working on NPC that would benefit from this ability, but I can use the workaround if need be.

**Comment by GuardianDll** [comment]
Do you mean something like `{ "math": [ "npc_val('anger')", "-=", "10" ] }` doesn't work?

**Comment by MNG-cataclysm** [comment]
> Do you mean something like `{ "math": [ "npc_val('anger')", "-=", "10" ] }` doesn't work?

No, it gives a "tried to use invalid beta talker" error when placed in recurring, non-global EOC.

**Comment by GuardianDll** [comment]
right, it seems it need to be ported to math, and be removed from the shim

**Comment by GuardianDll** [comment]
wait a second, so your only issue is that all this stuff require beta talker, and you can't manipulate on them from afar? in this case all you need is use `_set_talker` to store talker in some global variable, and then use `run_eoc_with` with `beta_talker` field, then EoC would run with that NPC from variable as talker
