### ISSUE TITLE
Desconstructing Improvised Shelter crashes game

### ISSUE THREAD

**Issue by MagikcapMarker** [CleverRaven/Cataclysm-DDA#75525]
### Describe the bug

as title says descontructing improv shelter crashes the game

### Attach save file

[Fort Walton Beach-trimmed.tar.gz](https://github.com/user-attachments/files/16549646/Fort.Walton.Beach-trimmed.tar.gz)

Shelter is right next to character

### Steps to reproduce

1. Build a improvised shelter (putting dry matter is optional)
2. Try to deconstruct shelter
3. Crash log

### Expected behavior

simply I expected to get some building matterials from it but it crashes the game!

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: a901bcc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16549672/crash.log)
crash log

**Comment by Karol1223** [comment]
They have ``EASY_DECONSTRUCT`` but no actual deconstruction results defined, that'll probably do it

**Comment by x-qq** [comment]
confirmed on cdda-linux-tiles-x64-2024-08-03-0533
