### ISSUE TITLE
Most human butchering products aren't considered cannibal food

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#75540]
### Describe the bug

Other than "chunk of human flesh", most of the products you get from butchering a human do not have the "Consumed human flesh" vitamin and thus don't register as cannibal foods, nor does anything produced with them as ingredients. A raw human liver turns into perfectly ordinary "cooked liver", for example. This also includes some recipes that are explicitly supposed to be cannibalistic, like human lard.

Curiously, "scrap of human flesh" _does_ have the vitamin, but processing it still tends to turn it into non-cannibal versions. Cooked scrap of meat has NUTRIENT_OVERRIDE so I guess that makes sense, but it also happens when turning it into jerky which doesn't, so idk what's up with that.

### Attach save file

[New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16561536/New.Mind-trimmed.tar.gz)

### Steps to reproduce

1. Butcher a human
2. Look at the pieces and note the lack of vitamin
3. Cook the pieces in various ways

### Expected behavior

Eating human is cannibalism, regardless of which part of the human you eat.

### Screenshots

![image](https://github.com/user-attachments/assets/fb41ba43-1d28-4030-8a95-822bcbe29261)
Raw human flesh. Note the presence of the "Consumed human flesh" vitamin and the warning that "This food contains human flesh."
![image](https://github.com/user-attachments/assets/47672da7-353d-4b8d-9f76-cfd9d03d043f)
Human flesh turned into jerky. Note that it still has the vitamin, still gives the text warning, and gains the special name "jerk jerky". This is as it shold be.

![image](https://github.com/user-attachments/assets/5109a1f7-2c25-4c2c-abff-e6062ce799ab)
Raw human liver. Note the lack of "Ate human meat" vitamin
![image](https://github.com/user-attachments/assets/286a70f8-0d94-4e1f-a25e-e9786a8a850e)
Cooked human liver. Still no vitamin and no warning

![image](https://github.com/user-attachments/assets/520d24e6-8730-498a-a3af-c179b74557b5)
Scrap of human flesh. Does have vitamin and warning.
![image](https://github.com/user-attachments/assets/1261aa5a-c63c-4fe7-9e35-97204dbeb3c6)
After turning into jerky. Note that it's totally normal "meat jerky" with no vitamin and no warning, not jerk jerky.

![image](https://github.com/user-attachments/assets/64bafa5a-6b55-4dca-a50f-7e0e0bef00fd)
Human lard is apparently not a cannibal food either, despite being called "human lard".

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 6ee8e16 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
I believe I've seen similar issues with zombie gibs, where some things were described as the normal (i.e. animal) version. I think it was gibs from one of the exploding versions (i.e. some kind of monster factory) rather than the result of a powerful external attack.

**Comment by Karol1223** [comment]
> Edit 2: .../json/harvest.json also needs an overhaul:
> 
>     * a lot of mutant critters seem to drop raw_leather, but raw_tainted_leather exists?
> 
>     * For some reason everything seem to have normal stomachs, i.e. no mutated ones.
> 
>     * mutant_mammal_small_fur has bone rather than tainted_bone
> 
>     * mutant_mammal_fur: bone
> 
>     * mutant_mammal_large_fur: bone
> 
>     * human_fur: bone
> 
>     * human_large_fur: bone
> 
>     * mutant_mammal_leather: bone
> 
>     * mutant_mammal_large_leather: bone
> 
>     * mutant_animal_noskin: bone
> 
>     * mutant_animal_large_noskin: bone
> 
>     * mutant_bird: bone
> 
>     * mutant_bird_flightless: bone
> 
>     * tusked_moose_with_skull: bone
> 
>     * dog_with_skull_fur_mutant: bone
> 
>     * raccoon_with_skull_mutant: bone
> 
>     * dog_triclopean_with_skull: only skull mutant?
> 
>     * spideer_with_skull: bone, raw_leather
> 
>     * cerbearus: bone

This just sounds like you're confusing mutants and zombies here. Mutants never dropped any tainted stuff, and they're not supposed to either. It would be a bug if they dropped tainted bones more than it is them dropping normal ones.

On top of that, the triclopean dog isn't a mutant either - it's altered by the nether, so it uses normal dog harvestlists on purpose.

**Comment by PatrikLundell** [comment]
Mutants drop a whole bunch of mutant stuff that's tainted, but not the bones (or the sinews, but there's only a single version of those, which is inedible anyway). Now, if mutant bones existed they ought to use those, but the next closest thing would be tainted, in my view. It's weird that everything in mutants is tainted except the bones (and thus their resultant products).

**Comment by Karol1223** [comment]
> Mutants drop a whole bunch of mutant stuff that's tainted, but not the bones (or the sinews, but there's only a single version of those, which is inedible anyway). Now, if mutant bones existed they ought to use those, but the next closest thing would be tainted, in my view. It's weird that everything in mutants is tainted except the bones (and thus their resultant products).

I don't disagree about them needing their own version of bones, but I do disagree about substituting them with tainted things. This is not something that needs an urgent bandaid fix. It can wait until it's done well.

**Comment by GuardianDll** [comment]
Can't reproduce:
butchered random NPC i debug spawned
![image](https://github.com/user-attachments/assets/31ec3bb4-6f0b-4256-b11f-61786d0019d9)
Butchered debug spawned feral axeman
![image](https://github.com/user-attachments/assets/02673ef6-dde6-470e-a434-63eead094fcb)

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 0.G-11377-g54be5797b6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Railroads [railroads]
]

**Comment by PatrikLundell** [comment]
@GuardianDll: I think you missed the point, as your screenshots don't address it, and I may be guilty of diverting attention away from it with my posts above. The (main) issue isn't that butchered humans aren't resulting in human parts, but that some of said parts aren't converting food made out of them into cannibal food, because they lack the "vitamin" that carries that information.

**Comment by GuardianDll** [comment]
Aha, i missed this fact, my bad

**Comment by RedMisao** [comment]
This issue is preventing the use of a hidden "human_product" vitamin, which would make tracking vampiric stuff much easier and straightforward.
