### ISSUE TITLE
Using set of clothes with backpack on crashes the game

### ISSUE THREAD

**Issue by ildifa** [CleverRaven/Cataclysm-DDA#75543]
### Describe the bug

Using the "set of clothes" object, while the character has a backpack on, crashes the game.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a new character
2. Debug spawn a backpack and a set of clothes
3. Wear the backpack
4. `a`ctivate the set of clothes
5. The game crashes

### Expected behavior

I expected the character to get naked and the game not to crash.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: openSUSE; Description: openSUSE Tumbleweed; Release: 20240801; Codename: n/a; 
- Game Version: cdda-experimental-2024-08-09-0203 61e0526 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[Archive.zip](https://github.com/user-attachments/files/16563744/Archive.zip)

**Comment by Psithief** [comment]
I just experienced this myself.

**Comment by catern** [comment]
See also https://github.com/CleverRaven/Cataclysm-DDA/issues/74237
