### ISSUE TITLE
Infolink CBM does not work

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#75545]
### Describe the bug

Infolink CBM's description suggests it should work as two-way radio, allowing communications with NPCs.
however, it does not work

### Attach save file

N/A

### Steps to reproduce

1. Make player with infolink CBM & NPC follower with two-way radio in inventory
2. Move outside of LoS from NPC, try to contact via radio
3. Observe "you do not have radio" message & unable to contact
4. Spawn two-way radio for yourself, observe you now able to contact NPC

### Expected behavior

Infolink CBM should allow radio communications, as described on the tin

### Screenshots

![infolink](https://github.com/user-attachments/assets/d41fa085-1bf5-44bf-804f-8bbc6c42db4d)
![no-radio](https://github.com/user-attachments/assets/ef283142-9eab-44f4-9dcd-dab8653412ce)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-08-05-1158 35e37f3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]
]

**Comment by Terrorforge** [comment]
Works just fine for me, and I'm on a version that's only ~six hours older than yours (2024-08-05-0511). Idk what exxactly @Maleclypse confirmed, but I guess the bug is inconsistent?

![image](https://github.com/user-attachments/assets/879baef7-551e-4f88-a885-16e9708991a5)
![image](https://github.com/user-attachments/assets/80b059b3-4824-4a23-8743-8ff5c5cf5b13)
No radio
![image](https://github.com/user-attachments/assets/aacee4b2-00a8-4c93-b925-c4c240912341)
Yes infolink

Here's my save and game report:

[New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16569033/New.Mind-trimmed.tar.gz)

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 6ee8e16 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills]
]

**Comment by Maleclypse** [comment]
> Works just fine for me, and I'm on a version that's only ~six hours older than yours (2024-08-05-0511). Idk what exactly @Maleclypse confirmed, but I guess the bug is inconsistent?
> 
> ![image](https://private-user-images.githubusercontent.com/5107449/356801165-879baef7-551e-4f88-a885-16e9708991a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk4NjgsIm5iZiI6MTcyMzI5OTU2OCwicGF0aCI6Ii81MTA3NDQ5LzM1NjgwMTE2NS04NzliYWVmNy01NTFlLTRmODgtYTg4NS0xNmU5NzA4OTkxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA2NGY0ODQ1ZDU3MjkyNzBiYTE1NjNmY2I5ODg5MzEwODVkNDU4ZjhiYWI1MjFhZjdiM2M3NGVjOTA1MzFjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wh3dD25dz1wRGaVKB09n_DPB2VqIpycMgjDoIx__e-U) ![image](https://private-user-images.githubusercontent.com/5107449/356801185-80b059b3-4824-4a23-8743-8ff5c5cf5b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk4NjgsIm5iZiI6MTcyMzI5OTU2OCwicGF0aCI6Ii81MTA3NDQ5LzM1NjgwMTE4NS04MGIwNTliMy00ODI0LTRhMjMtODc0My04ZmY1YzVjZjViMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFmYzM1NjhmMmQ5NDExZDE4NzZmYjU0OTdjMmNhYWFiNzM5YjA2Yjg3MzA2YzdhYjA4MDliNTE2ZGY5NmQ4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Naqf0U65xlNZ_KZPYldH-wpyWwJFjxL-2eEZ8qUUtHI) No radio ![image](https://private-user-images.githubusercontent.com/5107449/356801192-aacee4b2-00a8-4c93-b925-c4c240912341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk4NjgsIm5iZiI6MTcyMzI5OTU2OCwicGF0aCI6Ii81MTA3NDQ5LzM1NjgwMTE5Mi1hYWNlZTRiMi0wMGE4LTRjOTMtYjkyNS1jNGMyNDA5MTIzNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE0OWYyMTBhM2JiMWQxM2I5ZDVjZDA3ZjVhZmRmNzJlODFiZWQ3ZjcyMTkyZDkzM2EzZmNjZmJkM2FlOGJlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RNIxkFeX9VqPzUafxK1iaXvJuutvK_LBFys8lPGBU44) Yes infolink
> 
> Here's my save and game report:
> 
> [New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16569033/New.Mind-trimmed.tar.gz)
> 
> * OS: Windows
>   
>   * OS Version: 10.0.19045.4651 (22H2)
> * Game Version: 6ee8e16 [64-bit]
> * Graphics Version: Tiles
> * Game Language: English [en]
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Portal Storms Ignore NPCs [personal_portal_storms],
>   Slowdown Fungal Growth [no_fungal_growth],
>   Mind Over Matter [mindovermatter],
>   Bionic Slots [cbm_slots],
>   Stats Through Kills [stats_through_kills]
>   ]

I used my self compiled tester that I’d been testing a multiple months old PR on. But I thought I’d rebased recently. Quick check that you are on windows not Linux?  Unlikely to be compiler difference but I want to double check if that’s even a possibility.

**Comment by Antrocon** [comment]
just to add, changing infolink to togglable with
`    "toggled_pseudo_items": [ "two_way_radio" ],
    "flags": [ "BIONIC_TOGGLED", "USES_BIONIC_POWER" ]`
(similar to proposed fix by Maleclypse) 
fixes the issue for me

**Comment by Terrorforge** [comment]
> > Works just fine for me, and I'm on a version that's only ~six hours older than yours (2024-08-05-0511). Idk what exactly @Maleclypse confirmed, but I guess the bug is inconsistent?
> > ![image](https://private-user-images.githubusercontent.com/5107449/356801165-879baef7-551e-4f88-a885-16e9708991a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk4NjgsIm5iZiI6MTcyMzI5OTU2OCwicGF0aCI6Ii81MTA3NDQ5LzM1NjgwMTE2NS04NzliYWVmNy01NTFlLTRmODgtYTg4NS0xNmU5NzA4OTkxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA2NGY0ODQ1ZDU3MjkyNzBiYTE1NjNmY2I5ODg5MzEwODVkNDU4ZjhiYWI1MjFhZjdiM2M3NGVjOTA1MzFjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wh3dD25dz1wRGaVKB09n_DPB2VqIpycMgjDoIx__e-U) ![image](https://private-user-images.githubusercontent.com/5107449/356801185-80b059b3-4824-4a23-8743-8ff5c5cf5b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk4NjgsIm5iZiI6MTcyMzI5OTU2OCwicGF0aCI6Ii81MTA3NDQ5LzM1NjgwMTE4NS04MGIwNTliMy00ODI0LTRhMjMtODc0My04ZmY1YzVjZjViMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFmYzM1NjhmMmQ5NDExZDE4NzZmYjU0OTdjMmNhYWFiNzM5YjA2Yjg3MzA2YzdhYjA4MDliNTE2ZGY5NmQ4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Naqf0U65xlNZ_KZPYldH-wpyWwJFjxL-2eEZ8qUUtHI) No radio ![image](https://private-user-images.githubusercontent.com/5107449/356801192-aacee4b2-00a8-4c93-b925-c4c240912341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk4NjgsIm5iZiI6MTcyMzI5OTU2OCwicGF0aCI6Ii81MTA3NDQ5LzM1NjgwMTE5Mi1hYWNlZTRiMi0wMGE4LTRjOTMtYjkyNS1jNGMyNDA5MTIzNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTQxOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE0OWYyMTBhM2JiMWQxM2I5ZDVjZDA3ZjVhZmRmNzJlODFiZWQ3ZjcyMTkyZDkzM2EzZmNjZmJkM2FlOGJlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RNIxkFeX9VqPzUafxK1iaXvJuutvK_LBFys8lPGBU44) Yes infolink
> > Here's my save and game report:
> > [New Mind-trimmed.tar.gz](https://github.com/user-attachments/files/16569033/New.Mind-trimmed.tar.gz)
> > 
> > * OS: Windows
> >   
> >   * OS Version: 10.0.19045.4651 (22H2)
> > * Game Version: 6ee8e16 [64-bit]
> > * Graphics Version: Tiles
> > * Game Language: English [en]
> > * Mods loaded: [
> >   Dark Days Ahead [dda],
> >   Disable NPC Needs [no_npc_food],
> >   Portal Storms Ignore NPCs [personal_portal_storms],
> >   Slowdown Fungal Growth [no_fungal_growth],
> >   Mind Over Matter [mindovermatter],
> >   Bionic Slots [cbm_slots],
> >   Stats Through Kills [stats_through_kills]
> >   ]
> 
> I used my self compiled tester that I’d been testing a multiple months old PR on. But I thought I’d rebased recently. Quick check that you are on windows not Linux? Unlikely to be compiler difference but I want to double check if that’s even a possibility.

It's in the game report, but fwiw I have double-checked and I am definitely running this on Windows.

**Comment by Maleclypse** [comment]
Fix not needed in current experimental.  Worked fine when I updated on to the latest exp.
