### ISSUE TITLE
Cant use `Drug filler` / ` `m:drug filler``  as Pickup Rule in Auto Pickup Manager

### ISSUE THREAD

**Issue by EyangKodok** [CleverRaven/Cataclysm-DDA#75570]
### Describe the bug

Inside Auto pickup manager Pickup Rule `m:drug filler` in Test won't find items with Drug filler as material.

### Attach save file

[Batavialand-trimmed.tar.gz](https://github.com/user-attachments/files/16570339/Batavialand-trimmed.tar.gz)

### Steps to reproduce

1. In game press ESC to open Main Menu
2. Click Auto pickup manager
3. Press A to Add Pickup Rule
4. type `m:drug filler` and Enter
5. Make sure on I/E tab  `m:drug filler` is set to 'Include'
6. Highlight/select  `m:drug filler` and press T to run Test

### Expected behavior

Show items with `drug filler` as material to show up inside Test window

### Screenshots

![image](https://github.com/user-attachments/assets/9ed03b4c-0620-45af-bda8-070f2f422ad0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

this also happen to Search funtion.

**Comment by GuardianDll** [comment]
you try to find material, that was added 8 month ago, on 1.5 years old version
there is simply no such material
