### ISSUE TITLE
Maps do not override vague notions of what's on the overmap

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#75579]
### Describe the bug

When using a map to determine what is around you, the details on the map are not used if you can currently see what is around you. Your character instead ignores the map 

### Attach save file

[Apple-trimmed.tar.gz](https://github.com/user-attachments/files/16571243/Apple-trimmed.tar.gz)
This save file has a character at the top of a radio tower with everything you need to reproduce the bug.

### Steps to reproduce

1. Make a player, ideally with a pair of binoculars.
2. Climb a radio tower
3. If there's a map up there, use it after looking around with the binoculars.

### Expected behavior

I would expect that more specific information replaces the vagueness that my character can determine with dead reckoning.

### Screenshots

![image](https://github.com/user-attachments/assets/1497cbcd-ba05-41dc-80eb-74edabc923b8)

This image was taken with the attached save file. Highlighted tiles were revealed by the survivors map I just used. Everything in the vision circle remains vague and unknown. Note how roads are not visible.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: e5033d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Related to #75236 . Paging @ehughsbaird and @vetall812, as they worked in this area recently.

**Comment by Terrorforge** [comment]
I've also noticed this with other effects that reveal the map, such as science lab computers and mapping artifacts.

Those should definitely be able to update the map to geater detail as they typically represent eitger very accurate data or straight-up supernatural insight.

**Comment by vetall812** [comment]
Tested and can confirm only the road issue.
But view distance is increasing and I cant tell that it is bugged.

On the next screenshot you can see the view distance without binoculars:
Red marks is the distance to `outlines` changes to `vague`. Vague distance here is about 2 tiles more:
![base_view_ruler](https://github.com/user-attachments/assets/59fbb756-b718-4ae4-88cb-1293f8147eb2)

Next screenshot shows how roads appears on the unexplored area. You can see that there are no roads between red (`outlines`) and yellow (`vague`) marks:
![base+roads_rulers](https://github.com/user-attachments/assets/c39a24ac-90b6-4301-aa22-472810d8f56f)

Now I wear binoculars and my `vague` view distance increase drastically. (two yellow marks):
![vague_distance_increase](https://github.com/user-attachments/assets/5e75aeab-dcf9-4c46-ab34-89d6a942f2c4)

HOWEVER! If I use binoculars and THEN read the map roads wont appear in `vague` area:
![no_roads](https://github.com/user-attachments/assets/4c4e9f5d-26af-4fad-9829-580fa173f009)

**Comment by Inglonias** [comment]
To be specific, the desired behavior is that if you don't have perfect information on a tile already, activating a map that would reveal that tile should provide it, regardless of what its current revealed level is.

**Comment by kevingranade** [comment]
Rather, if a new source provides better information than what you already have it should improve it.

**Comment by SurFlurer** [comment]
Already fixed by #75641 ?

**Comment by Inglonias** [comment]
I'll take your word for it.
