### ISSUE TITLE
Isolation Protocol. The damage is too great

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#75589]
### Describe the bug

Note the screenshot. 2572 when using a pistol.
![pict](https://github.com/user-attachments/assets/97ac1c08-086b-44ae-8d78-36f0dce9ae12)

Also unreasonably high damage buff, continues to persist for a while. The second shot did 1460 damage.

Assumption. Strange interaction between **Hypocritу`s Oath** and firearms. It is assumed that after taking damage, the paramedic gets a buff to increase his damage (+50%).

With melee weapons, it seems to work that way. Or doesn't work at all, it's hard to say. But with ranged weapons (pistols were checked), it works differently.

### Attach save file

n/a

### Steps to reproduce

1. Create a world with this mod.
2. Default character. But the profession is paramedic
3. Increase pistol skill to 10 (this item is not important, just faster aim)
4. Create a pistol (I used M17)
5. Create or find a monster and wait for damage from it (this is the condition for triggering the buff)
6. Aim and shoot it
7. Pay attention to the damage

### Expected behavior

Canceling the buff for ranged weapons.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-08-11-0615 8d63411 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Isolation Protocol [Isolation_Protocol]
]

**Comment by GuardianDll** [comment]
`"values": [ { "value": "RANGED_DAMAGE", "multiply": 50 }, { "value": "RANGED_DAMAGE", "multiply": 50 } ]`
x100 damage, yeah checks out

**Comment by John-Candlebury** [comment]
Certainly one of the bugs of all time.

**Comment by John-Candlebury** [comment]
Fixed by: #75610
