### ISSUE TITLE
Russian credits. A few problems

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#75586]
### Describe the bug

![pict1](https://github.com/user-attachments/assets/b9652672-f1bf-4c5c-9f9c-b0164b196d13)

1. No space between words
2. Extra space

A minor point. Based on the English version. The author is Whales, and the leader is Kevin. In the Russian version it is not so clearly expressed. Perhaps it should be moved to a new line?

![pict2](https://github.com/user-attachments/assets/1f52c3d6-5365-45d1-9881-792c67c41eab)

3. No translation `and` (and in two other places). In my opinion, you can leave it untranslated or use a comma.
4. Text design failure? For the current version and version 0.F, gray text color is used (see the first picture). And for comments of earlier versions (E, D ...), white is used. In the English version, the design is the same everywhere (gray).

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

cdda-windows-tiles-x64-2024-08-11-0615

**Comment by Uwuewsky** [comment]
It will be fixed after the next routine translation update.

![credit1](https://github.com/user-attachments/assets/2a811736-bf4b-439c-a055-e27bb2a10891)
![credit2](https://github.com/user-attachments/assets/0ce479f3-d8e3-45cc-bb3f-e3d67c190d95)

**Comment by IdleSol** [comment]
cdda-windows-tiles-x64-2024-08-26-1250

It's all right.
