### ISSUE TITLE
Cooking oil is unobtainable

### ISSUE THREAD

**Issue by bird-ee** [CleverRaven/Cataclysm-DDA#75599]
### Describe the bug

Cooking oil is rarer than gold

### Attach save file

N/A

### Steps to reproduce

1. Spawn
2. Try to find cooking oil

### Expected behavior

1. Spawn
2. You find cooking oil in a normal house, because it is a normal household item

### Versions and configuration

N/A

**Comment by x-qq** [comment]
Cannot reproduce on cdda-linux-tiles-x64-2024-08-03-0533.

It's not in every house but it's certainly not unobtainable. After going through 10-15 kitchens you'll most likely have a lifetime supply of animal & vegetable cooking oil.

**Comment by sashakiller33** [comment]
I would recomendd to give save file with this bug to confirm

**Comment by bird-ee** [comment]
I searched two whole towns and didn't find any, then searched a few houses in a different town and found 800+ units

Maybe cooking oil should come in more common but smaller containers

**Comment by nhkun** [comment]
Hitchhiker's Guide to the Cataclysm says i have better chance finding cooking oil in strip club than in regular house. That's absurd.
