### ISSUE TITLE
Return superglue recipe

### ISSUE THREAD

**Issue by sashakiller33** [CleverRaven/Cataclysm-DDA#75594]
### Describe the bug

In https://github.com/CleverRaven/Cataclysm-DDA/pull/75492 Superglue creation were removed on basis that "nuh uh u can'b do that". This report trying to rectify it by saying that you can make strong enough glue in home that can be as strong as it.
https://www.youtube.com/watch?v=3RJ3WVUWIWk
https://www.youtube.com/watch?v=8g2REE6z9V8
It took me 5 minutes to find these videos. Original pull request uses an INDUSTRIAL way of creating superglue as a basis of that it can’t be done. and there are different and much inefficient ways to create superglues.

### Attach save file

N/A

### Steps to reproduce

1.Create word
2.Give yourself all recipes
3.See that superglue cannot be found

### Expected behavior

1. There is a way how to create a superglue in crafting menu

### Versions and configuration

N/A

### Additional context

I hope in future our creators and programmers will proof read and check more and don’t do such stupid mistakes.

**Comment by GuardianDll** [comment]
Youtube videos are not sufficient proof of anything in this project, full stop.
Both videos show how to make mold for casting, which is in no way the same thing as glue and especially superglue

**Comment by XygenSS** [comment]
Neither of those videos show how to make superglue, if you have to clamp it down for 2 hours for your glue to cure, it ain't superglue

**Comment by Holli-Git** [comment]
Superglue is a very specific chemical formula. A more productive version of this issue would be a feature request for more glues, instead of this poorly researched issue that throws shade on people for a misunderstanding.
