### ISSUE TITLE
urban_20_1. Tile spawning error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#75592]
### Describe the bug

![1](https://github.com/user-attachments/assets/4d7e0bcd-3bbc-49fb-a61e-45c534f5d55c)

1. Carpet under the table in the kitchen. But there is linoleum around the table
2. Wooden floor under the washing machine. There is linoleum around it

### Attach save file

[Хлопок-trimmed.tar.gz](https://github.com/user-attachments/files/16573561/-trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

cdda-windows-tiles-x64-2024-08-11-0615

**Comment by Milopetilo** [comment]
/confirm
I'll fix this once #77287 gets merged
