### ISSUE TITLE
Fetch quests bugged for Herrith, Vanessa and Alonso at refugee camp (Android O.G)

### ISSUE THREAD

**Issue by spacehimbo** [CleverRaven/Cataclysm-DDA#75605]
### Describe the bug

Cannot hand in cigarettes for Herrith, guard in the camp foyer, or hand in a makeshift haircut kit for Vanessa Toby, or hand in leather pants (or any leather bottoms) that were found in marked sex shop for Alonso. attempting to do speak to Herrith or Vanessa leads to going through to the same conversation with no acknowledgement of items in inventory. Attempting to talk to Alonso has an odd null message in the conversation. 

### Attach save file

[Moneta-trimmed.tar.gz](https://github.com/user-attachments/files/16576318/Moneta-trimmed.tar.gz)

### Steps to reproduce

1.  Find a route to the refugee centre
2. Talk to relevant npcs an accept their quests
3. Collect 100 cigarettes and try to hand them in to Herrith, either with all of them loose in your inventories,  all in one container,  or in cigarette packs.
4. Collect the materials to create a makeshift haircut kit and create it. Go speak to Vanessa.
5. Spend hours clearing out a town by burning buildings, using a poor gracken as bait for the town's populace, practice lockpicking so you can finally break into the sex store. Get a bull whip to complete your actual goal in life as a sub, then check every shelf for "special pants." Walk out in a leather collar and maid apron for good measure.
6. Return to Alonso with leather chaps, leather hot pants, a leather pants (poor fit). Those supposedly poor fitted leather pants are probably Alonso's because he has a magnum dong. The leather pants you are wearing were not found in said sex shop but robbed from a dead person's home, so are not his.
7. Alonso speaks to you in tongues,  not his usual type either. 

### Expected behavior

I just want to give people what they ask because I'm a people pleaser :( but really I just wanted to see if Vanessa could give me braids or something because I don't want to be bald anymore. And honestly I talked to Alonso just to get the location of the sex shop. 

### Screenshots

![Screenshot_20240812_102122_Cataclysm DDA](https://github.com/user-attachments/assets/7ff51f33-b0e8-41b9-8c28-cce843044311)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-X710; Release: 14; Incremental: X710XXS4BXG5; 
- Game Version: 0.G [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Alternative Map Key [alt_map_key]
]

### Additional context

[debug.log.zip](https://github.com/user-attachments/files/16576372/debug.log.zip)

Other contexts, I have manually installed things like sounds and an updated MSXOTTO tileset that didn't come with the android game. This is not my first game, I had died multiple times in different worlds because I was learning the game. In another save I started playing with the Safe scenario and it landed me in the refugee camp, which is how I first found out these characters. I'm not sure if playing a similar character over an over can bug out the game, since I accidentally overwritten a save  with a same named character. This save is not the Evacuee start but the Squatter start.

I did not attempt to take off my leather pants and tried to hand that in to Alonso, because those are MY pants and I was wearing them when I first met him. I have yet to find another pair that fits so I am NOT giving them to him. I also left my condoms at home, so I don't know if that has anything to do with it.

**Comment by GuardianDll** [comment]
Please reproduce the bug on current experimental or at least in 0.H stable candidate. 0.G is 1.5 years old
