### ISSUE TITLE
Fast Travel with Routes

### ISSUE THREAD

**Issue by ShnitzelX2** [CleverRaven/Cataclysm-DDA#75600]
### Is your feature request related to a problem? Please describe.

Autotravel (or W-g on the overmap) is an excellent feature to get from point A to point B in a vehicle or on foot. The problem: it's done turn by turn, and that can take several minutes of real time waiting and doing nothing. This is compounded by multiple points of interest being hundreds of OMTs apart that the player needs to go back and forth to multiple times, adding up to potentially hours of gameplay in a run that are ultimately spent tabbed out of the game waiting for autotravel to finish or get interrupted. 

In summary: autotravel is convenient, but not fast enough.

### Solution you would like.

I don't feel the need to change autotravel, and I also don't feel the need to adjust the overmap because points of interest should be far apart. So, I introduce Routes, allowing fast travel via timeskip/teleportation, and ideally reducing the number of times you must autotravel a safe path to just one.

**How it would work**
- You start an autotravel to a destination. Once you stop traveling (stop walking or turn off your vehicle's "engine"), reach your destination, or are interrupted by a hostile monster, a route is created. From anywhere on a route, you can instantly travel to any other OMT (we'll call them stops) along the route -- stops will always place you at the center of an entirely traversed OMT, similarly to how autotravel destinations work. Select a stop on the route, confirm a fuel and time expenditure for the given path if applicable, and you'll be teleported (along with your vehicle and any companions) to the destination one submap at a time, displayed exclusively on the map screen. Game time will progress and fuel will be consumed as appropriate.
- When routes intersect, they are merged automatically, creating a network of routes. Autotravel will determine which path between start and destination is fastest if there are multiple paths to take, along with which paths the vehicle can cross (e.g. over water or through a forest).
- Manually traveling can also create routes, but the same conditions apply as for autotravel

**Restrictions**
- You can't fast travel if hostile monsters are in view; encountering hostile monsters on an established route will split the route.
- You can't fast travel in the dark, nor can you map routes in the dark, even if you have sufficient lighting (for now). Fog is fine, but don't expect a permanent route.
- You can't fast travel in a portal storm.
- You can't fast travel while towing a vehicle (for now).
- You can't map routes manually while on foot. This is to avoid creating routes inside e.g. a nuclear plant; that's what #74433 is for.
- Routes must be at least 4 OMTs long (subject to change).

**Visual Example**
![route](https://github.com/user-attachments/assets/13afe945-9b29-475c-8f6e-717cf57472dd)
Where the red line is an already-mapped Route and the yellow points are Stops. The blue line represents part of the red route that was traversed on foot and can't be accessed with a vehicle.
So say you want to fast travel from the sewage plant to the refugee center. Drive your vehicle onto a route OMT (a stop works, but anywhere will do), hit the "cycle to next stop" key until you select the stop by the refugee center, and hit the key for "fast travel to destination". Confirm your path/fuel consumption/time spent, and you're there. Simple!

**Points of concern**
- hostile monsters that interrupt autotravel but won't actively or necessarily attack the player. Water striders in particular come to mind, black rats, skunks, etc. The "species" monster flag is a good start -- ZOMBIE, SPIDER, PLANT, BLOB, HORROR should always interrupt routing. From there, creatures with "aggression" > 10, or creatures with a faction that hates player/human?
- where vehicles and/or the player end up getting teleporting to in a submap, we don't want vehicles phasing into walls, creatures, vehicles, etc. Likely some kind of backwards check from the end of the route destination would be needed, with "your route was interrupted by a new obstacle" being a notification
- hordes and NPC random encounters, along with any other events occurring randomly in the future, need to be checked for while route stepping.
- muscle-powered vehicles and vehicles that produce power
- routes over water -- just because you crossed a route with one vehicle doesn't mean you can cross it with another. A vehicle must be capable of crossing all terrain between two stops on a given route.
- skill training; "vehicles" for time driven for now, add support for NPCs reading later
- vehicle speed setting?
- vehicle noise -- can trigger monsters

**Projected Workflow**
- [ ] extract vehicle fuel calculations
-calculate for distance in OMTs traveled
- [ ] define vehicle paths in a "route" class
-list of tripoint_abs_omt, which can optionally be defined as stops
-every route starts and ends with a stop by default
- [ ] changes to overmap UI
- routes appear dark on-screen, but light up when you're on them, allowing the following commands:
  - "fast travel to destination" (auto-creates stop if one does not already exist)
  - "next stop"/"previous stop" cycles along the route   
- "delete route"
- "delete stop here"
- "toggle blinking"
- "toggle routes"
- "list routes"
  - lists each route, along with each stop
  - delete route/stop
- [ ] route stepping
-moving the player one submap at a time towards the destination while checking for interruptions

### Additional context

- This would be a major feature, probably not for 0.H.
- This is a high-level design document for Routes; I have taken cursory looks at the relevant code but haven't written anything yet and don't plan to for a little while. I would like input for whether people like this and for anything I've overlooked.
- To reiterate, this doesn't replace autotravel, it builds off of it.
- Fast travel via timeskip was mentioned a few times in #70056, but I couldn't find much discussion on it anywhere else. Point me to discussions if you know of them.

**Comment by kevingranade** [comment]
Hard no,  the world state can and should change to invalidate these routes,  which is why it doesn't work as a teleport/timeskip in the first place. 

What can definitely happen is not drawing the map while in autotravel, using streamlined navigation heuristics, etc.
