### ISSUE TITLE
Too much materials required to initiate repairing

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7561]
Game often stops you from repairing/fitting/reinforcing an item of clothing, saying that you do not have enough material. But actually it consumes less. I had a situation when game required me to have 20 kevlar plates to fiddle with armor piece, then consuming about 5. One part of the code got updated without the other?

**Comment by Nandorianen** [comment]
Just curious, was this fixed or deemed working as intended?

**Comment by Coolthulhu** [comment]
Reworked, no longer applies.

New system always requires resources, but less of them.

**Comment by Nandorianen** [comment]
Nice. Thanks for the info.
