### ISSUE TITLE
Cats can climb ladders

### ISSUE THREAD

**Issue by failboat78** [CleverRaven/Cataclysm-DDA#75626]
### Describe the bug

As subject. There was similar bug before when Moose were climbing ladders - is it back?

### Attach save file

N/A trivial

### Steps to reproduce

Reproduce:
Start as Cat Lady in shelter (spawn with swarm of cats following you) and use ladder to roof for test.

### Expected behavior

Yes cats are very agile and could probably find other ways to climb up to the roof. 

But metal ladders?

Probably not a big deal - will try to find a Moose and test it's climbing ability a well.

### Screenshots

![image](https://github.com/user-attachments/assets/4fa38a75-b279-412e-a44e-578dae68fce6)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-08-12-1249 467f08f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter]
]

**Comment by kevingranade** [comment]
Cats can absolutely climb ladders, that's totally expected.

**Comment by failboat78** [comment]
Well my one cannot. Being able to jump quite high is not the same as climbing ladders.
