### ISSUE TITLE
Allow EoCs to spawn activated items

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#75627]
### Is your feature request related to a problem? Please describe.

Currently it is not possible to, through an EoC, spawn an item that is already active for the purpose of, for example, having it run another EoC after a set amount of time.

### Solution you would like.

Support for having EoCs spawn activated items

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_activatenpc_activate
