### ISSUE TITLE
Magiclysm spell casting menu doesn’t render color tags in the spell description

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75669]
### Describe the bug

Colors are shown correctly in all other parts of the menu; it is only the description that ignores them.

### Attach save file

n/a

### Steps to reproduce

Cast a spell using the Magiclysm mod.

### Expected behavior

Spell descriptions should not have visible color tags (things like “<color_yellow>” and the like). Those tags should be used to actually change the text color.

### Screenshots

![Screenshot 2024-08-14 at 10-50-23 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA](https://github.com/user-attachments/assets/7986acdd-a843-4ef3-bc8b-de5870e5798a)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Note that we cannot actually wrap text into paragraphs properly if it contains color tags. We are currently limited to either drawing a single line of colored text, or wrapping a paragraph, but we cannot do both at the same time. A short–term solution to this problem might simply be to strip the color tags and then render the description using wrapping but no color. At least then the text would be readable and the color tags would not be shown.

**Comment by eiennohito** [comment]
Also new implementation does not show non-mana requirements.
Haste was requiring mercury iirc
![New list](https://github.com/user-attachments/assets/903ef933-d770-48e8-b7e7-71e7782550a4)
Components required thing
![Old list](https://github.com/user-attachments/assets/56bf2334-6410-4db1-9171-ceaf71d07731)

**Comment by ThePotatomancer** [comment]
@eiennohito I separated your report to a new issue, will tackle it hopefully later today
