### ISSUE TITLE
The debug menu has a funny size

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75667]
### Describe the bug

The primary debug menu has a lot of text at the top that causes problems when the code tries to pick a correct size for the menu. Currently it overrides the default sizing and sets itself to half the width and height of the screen. This looks awkward on normal screens but not half so awkward as it would otherwise. It looks even worse on small screens.

### Attach save file

n/a

### Steps to reproduce

Open the debug menu, you can’t miss it.

### Expected behavior

I expect it to look so normal and ordinary that you don’t even notice it.

### Screenshots

![Screenshot 2024-08-14 at 10-38-56 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA](https://github.com/user-attachments/assets/a58b227f-6457-40e2-895a-90ebcfa0efd7)

Small window:
![Screenshot 2024-08-14 at 10-44-35 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA](https://github.com/user-attachments/assets/64a1b924-a114-47a1-bd44-3d5dd9529650)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ZhilkinSerg** [comment]
Removing `debug.desired_bounds = { -1.0, -1.0, 0.5, 0.5 };` makes it look okayish:

![image](https://github.com/user-attachments/assets/51686eaa-4d02-4e30-b2a6-7c8401fc747f)

**Comment by ZhilkinSerg** [comment]
Additionally removing flavor text makes it look nice:

![image](https://github.com/user-attachments/assets/d80ca854-74d7-4dc6-9e06-ee45b7087e3e)

**Comment by db48x** [comment]
Removing the override on the bounds is a simple enough patch. How does it look when the game window is small?

I don’t think we should remove the text; it does serve a purpose, and its removed automatically if you have a debug character. But maybe the first part, “Debug Functions”, should be a title instead. Then the text can be slightly shorter.

**Comment by ZhilkinSerg** [comment]
There is strange blue border appearing on third(?) key input, but it seems to affect all menus:

![image](https://github.com/user-attachments/assets/a53174ef-e7c7-48dd-a863-9590f70db067)

**Comment by db48x** [comment]
That’s known, not really that strange, happens when you wrap around from top to bottom or bottom to top, and is a separate issue.

**Comment by ZhilkinSerg** [comment]
![image](https://github.com/user-attachments/assets/6d7128b2-5dd0-4f8b-8a04-cdff3c91ec99)

![image](https://github.com/user-attachments/assets/8362d0ae-1701-48bd-84ca-9f3d39f3c0b8)

**Comment by db48x** [comment]
Looks ok there, but what about a tall narrow window like a phone in portrait mode? Like in the original post.

**Comment by CLIDragon** [comment]
For reference, this is what it used to look like on a normal sized screen:
![image](https://github.com/user-attachments/assets/97ddb83a-a7a7-42fe-85f0-57375ed2fe70)

And on a portrait mode screen:
![image](https://github.com/user-attachments/assets/dcfa1096-883c-4f13-86d6-a82543631b85)

Same dimensions, just locked larger I suspect.
