### ISSUE TITLE
Magiclysm spellcasting menu is missing its category selector

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75666]
### Describe the bug

This menu was the only one in the game to use a uilist with categories, and now the code to implement the category selector has been removed.

The best way to fix this may be to have a unique implementation just for this menu, rather than to complicate the uilist further.

### Attach save file

n/a

### Steps to reproduce

Cast a spell in the Magiclsym mod.

### Expected behavior

n/a

### Screenshots

![Screenshot 2024-08-14 at 10-33-46 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA](https://github.com/user-attachments/assets/24c94b83-5d9e-4a03-b832-691bcba1c793)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
Dumbing down the functionality of support tools because it might be convenient for a change of implementation shouldn't be the first course of action.
It may well be that whoever did this didn't think that functionality was used because the usage was hidden away in a mod.

**Comment by db48x** [comment]
It wasn’t done as the first course of action, it was done as a result of exhaustion.

**Comment by PatrikLundell** [comment]
Then it's even weirder. Knowingly break functionality for the time being because of being too tired to deal with it.

If it was known the functionality was used then the PR should have been kept on hold until a way to not break game functionality had been implemented.

**Comment by db48x** [comment]
Meh, the branch is called “experimental” for a reason. I presented the patch and accurately described the current state, including its known limitations. The developers committed it in spite of those limitations. If you don’t like it, take it up with them.
