### ISSUE TITLE
Filter input for ImGui uilist menus shows up behind the menu

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75676]
### Describe the bug

The user can still filter the menu, but the input box shows up behind the menu. On large menus it is invisible, on narrow ones it is merely obstructed.

### Attach save file

n/a

### Steps to reproduce

1. Open the main menu
2. Type ‘/’ to filter it

### Expected behavior

The input is a `string_input_popup` which has not yet been ported to ImGui.

### Screenshots

![Screenshot 2024-08-14 at 11-50-39 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA](https://github.com/user-attachments/assets/27b8c046-bc66-411c-b06c-95b251516984)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
/Confirmed

Actual confirmation made on #74341.
