### ISSUE TITLE
progress is not shown when loading a game

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75678]
### Describe the bug

Instead of showing a menu with each step of the loading process, the screen is just black. The progress menu is a `uilist`, but this doesn’t appear to be a problem with the `uilist` class itself. Instead it appears that ImGui windows are just not being rendered. Perhaps the `ui_adaptor` stack is in the wrong order; I haven’t done enough debugging yet to figure it out.

### Attach save file

n/a

### Steps to reproduce

Load a saved game

### Expected behavior

Some indication that the game is doing something, and hasn’t crashed.

### Screenshots

Not much point of a screenshot for this one, since the whole screen is black :)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
/Confirmed

Actual confirmation made on #74341.

**Comment by mqrause** [comment]
It looks like uilist is only drawn when `uilist::query` is called, since that's the only place that actually creates the `uilist_impl`. That never happens for the `loading_ui` and as a result it's not added to the `ui_stack`.
