### ISSUE TITLE
ImGui uilist menus render their footer text without color tags

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75673]
### Describe the bug

The footer text (which might actually be a description of the current menu item instead) is rarely used and needs to wrap, but it might also contain color tags. Currently that means the color tags are shown to the user.

### Attach save file

n/a

### Steps to reproduce

Craft something, or bandage your wounds.

### Expected behavior

For the short term I think I will have to remove the color tags before drawing the text, so that it can be wrapped. Eventually I or someone will write the code that correctly wraps text containing color, but until then the wrapping is more important than the color.

### Screenshots

![Screenshot 2024-08-14 at 11-04-33 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA](https://github.com/user-attachments/assets/ff291d4f-49fb-4e10-89c8-00d294f16912)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by db48x** [comment]
@HadeanLake, which crafting recipe did you select to get that particular menu? I keep getting a very similar but slightly different menu…

**Comment by HadeanLake** [comment]
High steel brigandine coat.
Also, I use slightly bigger font size, which may change how window looks

**Comment by db48x** [comment]
That’s really weird. My debug character can’t craft that, but he can craft the high steel brigandine coat with shoulder guards, which takes a previously crafted coat and shoulder guards and attaches them together.

Do you know any other recipes that need to use this menu?

**Comment by db48x** [comment]
Or I can just spawn the book the recipe is in, that works.

**Comment by HadeanLake** [comment]
Any recipe that needs multiple components with multiple options that your character has will produce it.

**Comment by db48x** [comment]
Ok, that menu is really funky. I’ll have to file a separate bug about the other problem it has, but fixing the footer text is easy.
