### ISSUE TITLE
Disassembling/butchering selection Imgui menu does not display time estimation

### ISSUE THREAD

**Issue by HadeanLake** [CleverRaven/Cataclysm-DDA#75680]
### Describe the bug

Disassembling/butchering selection Imgui menu does not display time to disassemble or butcher

### Attach save file

N/A

### Steps to reproduce

Drop some items on the ground and press butcher key (default "B")

### Expected behavior

The user should be able to see time estimation

### Screenshots

new imgui:
![disb](https://github.com/user-attachments/assets/3a2238c8-e1b2-4c8b-8765-e314474891a4)
before imgui:
![disg](https://github.com/user-attachments/assets/29be1615-7ad3-45fa-b196-05583d8232a9)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-08-14-0712 54be579 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by alef** [comment]
There is no `ImGui::TableNextColumn()` in [`uilist_impl::draw_controls()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/ui.cpp#L89) compared to how [`keybinding_ui::draw_controls()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/input_context.cpp#L780) does it. Hope it helps @db48x.

**Comment by db48x** [comment]
Heh, thanks. There is more missing than just that, though. I never actually implemented support for entries with the extra column, so it needs to set up a table, set up the columns, calculate appropriate widths, etc, etc.

And I am not entirely sure that I should keep that complexity in the `uilist`. There are other menus with columns, like the Eat menu, that essentially are a whole spreadsheet with many columns. Maybe there should be a `uilist_grid` class that implements it, and the butchery menu can be one of those instead.

**Comment by HadeanLake** [comment]
Redundant since issue #75813 now exists

**Comment by db48x** [comment]
Oops, I forgot that this one already existed!
