### ISSUE TITLE
Randomly crashing when attempting to use a bandage

### ISSUE THREAD

**Issue by Gaming-Doggy** [CleverRaven/Cataclysm-DDA#75689]
### Describe the bug

Sometimes when using a bandage, I will have a full crash. instead of a black screen error log, I get a new window that shows the error log, and then the game closes. 
This does not happen every time a bandage is applied either - there appears to be a random component.

![image](https://github.com/user-attachments/assets/b3c952e3-47b9-449e-aba3-25dfdd93fddd)

### Attach save file

[Keyesport-trimmed.tar.gz](https://github.com/user-attachments/files/16619719/Keyesport-trimmed.tar.gz)

### Steps to reproduce

Apply bandage. Sometimes the game crashes.
Possibly the game is getting confused by the ifak pouch attached to my gaudy light ballistic vest?

### Expected behavior

No crashes from applying bandage.

### Screenshots

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: c06f12d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16619707/crash.log)

[debug.log](https://github.com/user-attachments/files/16619713/debug.log)

**Comment by marilynias** [comment]
can you mark this as solved? Bot didnt seem to correctly close it.
