### ISSUE TITLE
incorrect vertical size of uilist menus

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75698]
### Describe the bug

Every line of text added above or below the menu items in a uilist menu causes the window to be a few pixels too short. This causes the end of the menu to be clipped. The more text there is, the more is clipped.

The uilist measures the text it is given to discover how large the menu should be. Is this some mismatch between how we (or our modified version of ImGui) measures text and how it renders it?

### Attach save file

n/a

### Steps to reproduce

Acquire multiple activatable objects (such as lamps, cigarettes, etc) and then use the sleep menu.

### Expected behavior

I expect the menu to be the right size! Crazy, I know.

### Screenshots

Two lines of text, slightly clipped at the bottom:

![Screenshot from 2024-08-03 08-19-43](https://github.com/user-attachments/assets/52ee633d-dfb9-4875-b769-d229f6917bb0)

Four lines, more clipping:

![Screenshot from 2024-08-03 08-24-58](https://github.com/user-attachments/assets/fec3effb-c19b-4b59-9f92-155ebc4030dc)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 809cfa67eb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by db48x** [comment]
@katemonster33, do you have any thoughts on this?

**Comment by qtquazar** [comment]
Can confirm this issue, and that it happens on many, many boxes. Especially noted on the bandaging menu that only the very top of the text for 'disinfection' status shows if the 'bandage' status text is also showing. 

Box is clearly not wrapping to the actual size of the needed text, and just cuts off wherever. Guessing #75673 broke several things and this was only partially fixed in #75684

**Comment by db48x** [comment]
The proficiency list is an interesting bug, but it isn’t drawn using ImGui. Do file that one separately.

The butchery menu is filed as #75813; thanks for reminding me about it.

**Comment by RenechCDDA** [comment]
Hm this is... closer? Something's strange. The area for `text` seems to be drawn about 1 pixel larger (in y) for every line it should have than the calculation provides for

```diff --git a/src/ui.cpp b/src/ui.cpp
index 9c4768909f..eaadebd435 100644
--- a/src/ui.cpp
+++ b/src/ui.cpp
@@ -633,7 +633,8 @@ void uilist::calc_data()
     ImVec2 text_size = {};
     if( !text.empty() ) {
         text_size = calc_size( text );
-        text_size.y += s.ItemSpacing.y * 2.0;
+        float expected_num_lines = text_size.y / ImGui::GetTextLineHeightWithSpacing();
+        text_size.y += ( s.ItemSpacing.y * 2.0 * expected_num_lines );
     }
 
     ImVec2 desc_size = {};
```

1 cigar:
![image](https://github.com/user-attachments/assets/d5cc1284-053d-43f4-823e-902ce04196f1)


6 cigars:
![image](https://github.com/user-attachments/assets/6c9260c5-d853-43b0-9f7d-d92ce454d349)


21 cigars:
![image](https://github.com/user-attachments/assets/c0ffbbd2-0401-4dcf-840e-224743284859)

**Comment by RenechCDDA** [comment]
Better patch where I don't double-count the spacing. No wonder it was screwy!

```diff --git a/src/ui.cpp b/src/ui.cpp
index 9c4768909f..9cc2ac9e69 100644
--- a/src/ui.cpp
+++ b/src/ui.cpp
@@ -633,7 +633,8 @@ void uilist::calc_data()
     ImVec2 text_size = {};
     if( !text.empty() ) {
         text_size = calc_size( text );
-        text_size.y += s.ItemSpacing.y * 2.0;
+        float expected_num_lines = text_size.y / ImGui::GetTextLineHeight();
+        text_size.y += ( s.ItemSpacing.y * expected_num_lines ) + ( s.ItemSpacing.y * 2.0 );
     }
 
     ImVec2 desc_size = {};
```

1 cigar:
![image](https://github.com/user-attachments/assets/15dec0a4-3c70-403a-84cc-1e5bb883ee2c)


6 cigars:
![image](https://github.com/user-attachments/assets/6b5ac210-e2b0-4b64-9831-30121da9ee97)


21 cigars:
![image](https://github.com/user-attachments/assets/3f65c328-df1e-4513-9ee3-8d5572b9bd13)


41 cigars:
![image](https://github.com/user-attachments/assets/06a08c6c-ce20-457a-ba9e-482498ca005e)
