### ISSUE TITLE
We should copy colors from the user’s color theme into ImGui’s theme

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75699]
### Is your feature request related to a problem? Please describe.

ImGui has it’s own theme from which it draws colors, but it isn’t linked in any way to the user’s preferred colors.

### Solution you would like.

When ImGui uses a color, let's say blue, we should pull the corresponding color from the user’s color theme.

### Describe alternatives you have considered.

One alternative is to let the user provide their own ImGui theme. However, this is much more complicated and is not really needed in the short term.

**Comment by sonphantrung** [comment]
Speaking of theming, there's also [this function](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_imgui.cpp#L258) for rendering fonts like in SDL/Text interface, yet I don't see it being used anywhere, so it uses the [default font](https://github.com/bluescan/proggyfonts/blob/master/ProggyOriginal/ProggyClean.ttf)
