### ISSUE TITLE
Too many TCL generated by freight badges?

### ISSUE THREAD

**Issue by akrieger** [CleverRaven/Cataclysm-DDA#75715]
### Describe the bug

I picked up more freight badges in the TCL I was raiding. I activated them, and got both 'you learn nothing new' and 'added new locations to map' messages. On the map there are a bunch of TCLs now.

### Attach save file

[2kumo4me.zip](https://github.com/user-attachments/files/16627233/2kumo4me.zip)

### Steps to reproduce

1. Find TCL
2. Pick up badges from lower levels.
3. Activate them?

### Expected behavior

I thought TCL is globally unique?

### Screenshots

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/40e85120-fdf1-4b3a-b7c0-10b08cfa87ad">

There's also two offscreen to the right.

### Versions and configuration

Some master build from the last couple weeks like `45f35ecb556eae10b78997257765a40795c2784f` but earlier.

**Comment by GuardianDll** [comment]
Just to specify, visitor's pass and transport freight employee badge do the same thing - reveal TCL 300 overmap tiles around
It's a mapgen gen issue, not badges issue

**Comment by x-qq** [comment]
I can confirm that this is happening but I'm not sure if it's a bug. Is TCL intended to be globally unique?

**Comment by akrieger** [comment]
For some reason I thought it was supposed to be. IDK though.
