### ISSUE TITLE
Butchery menu is laughably wide

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75726]
### Describe the bug

The uilist automatically calculates a size that is much too wide.

### Attach save file

n/a

### Steps to reproduce

Butcher a corpse.

### Expected behavior

A menu you can see.

### Screenshots

![Screenshot from 2024-08-15 14-00-51](https://github.com/user-attachments/assets/44cbcf58-272e-436c-8c70-d444d7fcff70)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 809cfa67eb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by DukePaulAtreid3s** [comment]
Confirmed, it has been happening to me as well

**Comment by db48x** [comment]
![Screenshot from 2024-08-15 19-05-40](https://github.com/user-attachments/assets/00e8915f-b9bf-4949-a339-5f4f7f37c4dc)

That’s nicer.

**Comment by Void-Seeker** [comment]
Same is with martial art selection menu.

**Comment by db48x** [comment]
@Void-Seeker: that’s already filed as #75674
