### ISSUE TITLE
Disinfection and bandaging not acting as it should

### ISSUE THREAD

**Issue by lethallama** [CleverRaven/Cataclysm-DDA#75736]
### Describe the bug

In the Consume screen, when I clicked on an alcohol wipe using my mouse, it just consumed it, cleaning a wound, I assume the most injured, and gave average disinfection.  If I used the keyboard, it would go to the correct screen and let me choose which wound to treat, offering poor disinfection, and then gave me average anyway.
The same happened with adhesive bandages, giving a poor bandaging, and when I go the the correct screen, it offers a very poor bandage.  I have not yet bandaged more than one slot, so I can't say what it will give if I use keyboard.

### Attach save file

[Eternal Pool-trimmed.tar.gz](https://github.com/user-attachments/files/16633608/Eternal.Pool-trimmed.tar.gz)

### Steps to reproduce

With an injured character, who has healthcare 3 and wound care proficiency, open the Consume screen, and click on an alcohol wipe, or click on an adhesive bandage.
Use the keyboard to go to the alcohol wipe or adhesive bandage, and check what it should have given.
Check the Character screen to see what it gave?

### Expected behavior

I expected clicking on the disinfectant/bandage to take me to the medical screen instead of just consuming it and using it on an injury without my input.  I also expected it to give me treatment in line with my skills and not dramatically more.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: c72f9ef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Tamable Wildlife [Tamable_Wildlife],
    DinoMod [DinoMod],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by lethallama** [comment]
After posting, I did verify that bandaging was giving poor benefit despite saying it would give very poor.

**Comment by Void-Seeker** [comment]
> bandaging was giving poor benefit despite saying it would give very poor

I think final result is scaled with medicine skill and has some random factor in it. The state you see before applying is just estimation derived mostly from the base quality of the item.

**Comment by lethallama** [comment]
Every heal I've done with this update has been max rolled, I think.  That doesn't sound right.  And it's not the amount that it's saying I should expect when putting the bandages on.

**Comment by l29ah** [comment]
/confirmed
The estimated healing efficacy is indeed off.

**Comment by failboat78** [comment]
Maybe this has side effect of messing up npc logic as well: https://github.com/CleverRaven/Cataclysm-DDA/issues/75688

The npc tries to disinfect same wound over and over again.

**Comment by sonphantrung** [comment]
Prob the fact that the Wound Care proficiency buffing healing (good -> very good, poor -> average, and so forth) which isn't calculated in the inv screen (just my guess)

**Comment by sonphantrung** [comment]
My char with 3 health care (No Wound Care):
![image](https://github.com/user-attachments/assets/c449a2bf-100c-404f-90d0-e9e42c79ce64)
With Wound Care:
![image](https://github.com/user-attachments/assets/d765ec1c-8605-42db-b396-66e399c4cc4b)

**Comment by sonphantrung** [comment]
I think I now know why the problem exists, after modifying the code so that it shows number:
- Bandages' bandaging quality with 3 health care + Wound Care is 8 (4 base value + 3 skills + 1 prof), a.k.a Good bandaging quality
- But then, when bandaging, the value is bumped up again (by 1), leading to a 9 (Very Good) in bandaging value.
