### ISSUE TITLE
[Xedra Evolved] "Call Oneiric Hammer" causes crash.

### ISSUE THREAD

**Issue by Testificater** [CleverRaven/Cataclysm-DDA#75730]
### Describe the bug

"Call Oneiric Hammer" Summoning the hammer does not cause a crash, but moving after the summon causes a crash. If you drop after summoning no crash but wielding it off of the ground does crash.

### Attach save file

[Magic Hunter-trimmed.tar.gz](https://github.com/user-attachments/files/16631079/Magic.Hunter-trimmed.tar.gz)

### Steps to reproduce

1. Use the spell to summon hammer into hands
2. Move

### Expected behavior

I would expect no crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 12bb7da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Hope [no_hope],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Mind Over Matter: <color_magenta>No Negative Nether Attunement Effects</color> [mom_no_negative_nether_attunement],
    Mind Over Matter: <color_magenta>Remove Concentration Limit</color> [mom_infinite_concentration],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16631093/crash.log)

**Comment by GuardianDll** [comment]
Should be fixed by #75642
