### ISSUE TITLE
ImGui: AIM examine panel wrong offset

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#75756]
### Describe the bug

See the screenshot.

### Attach save file

N/A

### Steps to reproduce

1. Open AIM `/`
2. `e`xamine a worn item in `>W<` slot
3. menu pane shows in wrong position

### Expected behavior

The pane should be attached to the examine report.

### Screenshots

![image](https://github.com/user-attachments/assets/85032ee6-1cf8-4802-9ff2-b30803ff5dd5)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 0b8d7ba74-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Related to #74341 .
Probably for @db48x

**Comment by db48x** [comment]
Nice. Looks like it’s calculating the position using the wrong font metrics. Thanks for filing it!

**Comment by db48x** [comment]
Incidentally, there is another window that is offset in a similar way. Can you go examine something that is attached to a power grid and see if that is offset correctly or not? If you don’t have a power grid handy, just look for a microwave or a standing lamp or something and examine it.

**Comment by alef** [comment]
![image](https://github.com/user-attachments/assets/c4d92e11-2428-451b-a36d-4c12d8c70860)

**Comment by db48x** [comment]
Yep, same problem.

**Comment by alef** [comment]
Both are fixed, thank you!

**Comment by db48x** [comment]
Are you sure this is fixed? I don’t see any code changes that would fix it…

**Comment by alef** [comment]
`911eeed47`
![image](https://github.com/user-attachments/assets/ecb13178-9d6d-470d-89ef-6c12be8dcc85)
![image](https://github.com/user-attachments/assets/87be5af7-b47b-47bb-a892-88934a4706ed)

**Comment by db48x** [comment]
Those have dramatically different fonts than before.

**Comment by alef** [comment]
Fonts are different because of #75920 and #75937

**Comment by db48x** [comment]
Oh, nice! Thanks for fixing that :)
