### ISSUE TITLE
Ergonomic grip mentions 'bow' in 'mod_targets' while none of the bows have 'grip' mod locations

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#75754]
### Describe the bug

Ergonomic grip mentions 'bow' in 'mod_targets' while none of the bows have 'grip' mod locations

### Attach save file

N/A

### Steps to reproduce

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/gunmod/grip.json#L39
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/ranged/archery.json

### Expected behavior

Not sure. Either some of the bows should have "grip" location (which makes sense for me), or "bow" should be removed from the "ergonomic grip" mod.

### Versions and configuration

current master... my local is 

build type: linux-tiles-sounds-x64
build number: 2024-08-12-0753
commit sha: 61cda3e73853a4fb7150333ab6e418e560fbfc59
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/61cda3e73853a4fb7150333ab6e418e560fbfc59

**Comment by SirPendrak** [comment]
As far as I am aware, handling modifier does nothing for bows anyway...
