### ISSUE TITLE
Lobster in the ocean

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#75761]
### Is your feature request related to a problem? Please describe.

We have lobster the creature in game file, we have lobster meat in recipes, and now we have ocean too. But lobster don't spawn in vanilla at all. Even by mod currently it only spawn in dino's zoo.

### Solution you would like.

Put `mon_fish_lobster` into ocean spawning group, let survivor able to eat fresh lobster right from the sea.

### Describe alternatives you have considered.

Don't

**Comment by DSeyka** [comment]
A zoidberg type monster seems like the next logical step then. :)

**Comment by Little-119** [comment]
> A zoidberg type monster seems like the next logical step then. :)

[and a variant it evolves into, with extra hard armor](https://www.youtube.com/watch?v=vz65vonktMA)

**Comment by TheLyca0n** [comment]
> > A zoidberg type monster seems like the next logical step then. :)
> 
> [and a variant it evolves into, with extra hard armor](https://www.youtube.com/watch?v=vz65vonktMA)

Isn't that literally what razorclaws are, I know it's a warcraft reference with the Xotto sprites but their screech attack gives bullet shrimp crossed with lobster rattle scream vibes

Also seconding them spawning giant crawfish are common enough on land and could use the same "looks like" tag in the json but crawfish annoyingly cannot be used in any of the recipes. A mutant crustacean meat would also be cool
