### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [CleverRaven/Cataclysm-DDA#75772]
### Is your feature request related to a problem? Please describe.

Unverified flatpaks do not show up in certain Linux distros by default (ex. Linux Mint), and are given warnings by others (ex. Elementary OS)

### Solution you would like.

By verifying the flatpak on Flathub it becomes available on all distros that restrict unverified apps and gives peace of mind to people who are skeptical. Here is a link to Flathub's official verification documentation https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by kevingranade** [comment]
Looks like I need to claim the app first,  I was expecting to end up in that state but it looks like #75504 ended up attaching it to a different account.

**Comment by GuardianDll** [comment]
since <https://github.com/flathub/flathub/issues/5513> was closed, i assume it means it was verified

**Comment by Roman19S** [comment]
Not quite yet. Taking ownership was just a prerequisite. Here is the documentation on getting verified https://docs.flathub.org/docs/for-app-authors/verification/ ![Screenshot_20240911-121013_Firefox_1](https://github.com/user-attachments/assets/f6fceb78-955c-48c4-8ea4-2d23cf85ff24)

**Comment by grisha765** [comment]
To complete the verification process, please make the following update to website:

Ensure that the URL https://cataclysmdda.org/.well-known/org.flathub.VerifiedApps.txt contains the following token:

```
2a29f88c-d751-445b-ac67-e56ffee1c359
```

Once this has been set up, i am will be able to proceed with the verification request.

![image](https://github.com/user-attachments/assets/bad136eb-0254-4cb4-8b1b-c58b14eaa151)

**Comment by kevingranade** [comment]
NOW we're verified, thanks for reminding me.
