### ISSUE TITLE
Unhardcode `water_source` to allow arbitrary liquid fields

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#75786]
### Is your feature request related to a problem? Please describe.

Right now only sewage, liquid cacao(?!), water and salt water have working liquid sources because they are hardcoded:

https://github.com/CleverRaven/Cataclysm-DDA/blob/711754cea17d523ac5b05e2b0882a39e297b3dea/src/map.cpp#L5772-L5795

### Solution you would like.

Rename `water_source` into `liquid_source`. Do mind the compatibility as some things do use `water_source` and must be adapted for the new thing. Make it an [examine actor](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EXAMINE.md#examine-actors) and allow an argument to specify the liquid item to be dispensed.
Also handle finite liquid sources appropriately.

**Comment by Standing-Storm** [comment]
This is what's stopping me from letting people take the black liquid from the MoM mag special pools
