### ISSUE TITLE
Autonote is does not delete notes generated by dropped favorited when picking them back up

### ISSUE THREAD

**Issue by Alithsko** [CleverRaven/Cataclysm-DDA#75785]
### Describe the bug

The autonotes currently have trouble deleting themselves when dropping a favorite item, this means if you use martial arts and drop your gun on the floor a lot the map will be rapidly flooded with junk notes

### Attach save file

[Chevy Chase Village-trimmed.tar.gz](https://github.com/user-attachments/files/16646735/Chevy.Chase.Village-trimmed.tar.gz)

### Steps to reproduce

Enable autonotes for dropped items, and simply drop and pick up your favorited item while wielding it such as a gun or bow

### Expected behavior

Autonotes for dropped items are intended to keep track of your items if you happen to drop them a lot or to not lose important things, by flooding the map with broken junk notes it makes is way more difficult to keep track of anything

### Screenshots

![image](https://github.com/user-attachments/assets/c8c99e12-007a-4187-abe6-8fe002232d18)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 6b4c4d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Generic Guns [generic_guns],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter]
]

**Comment by RenechCDDA** [comment]
They are not intended to delete themselves.

**Comment by Terrorforge** [comment]
That makes it more of a feature request than a bug report, but they absolutely _should_ delete themselves. If you can't reliably use this feature to find where you last left your backpack, I don't see much use for it at all.

**Comment by Alithsko** [comment]
Hmm, I genuinely thought it was a glitch, my bad, still though, would help so much
