### ISSUE TITLE
[0.H] weight doesn't decrease by item transfer with / advanced inventory panel

### ISSUE THREAD

**Issue by LarnellThePureDangerous** [CleverRaven/Cataclysm-DDA#75798]
### Describe the bug

when i put items in a container to somewhere else by using / advanced inventory panel, it didn't reduce my character's carrying weight. i normal inventory panel showed the carrying weight which didn't decrease, and my character was still affected by pre item transfer weight.

### Attach save file

N/A

### Steps to reproduce

1. wear a wearable container like backpack or hold a container like a cardboard box in hands
2. put something in the container
3. push / to go to advanced inventory panel
4. put something to somewhere from the container by the panel
5. finish advanced inventory panel, then push i to normal inventory panel
6. check the weight

### Expected behavior

just like weight displayed in advanced inventory menu, normal inventory weight display and general weight calcuration should change by each item transfer.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4037 (23H2)
- Game Version: 9883075 [64-bit]
- Graphics Version: Tiles
- Game Language: Japanese
- Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth],
]

### Additional context

1. actually, if you put too much in the container, your stamina will run out when you walk even if you put everything out of the container by advanced inventory panel. this means this is not just simple display issue but general weight calculation issue. actual ingame weight is, in this case, normal inventory one, it seems.
2. for example, if you put 1kg lump of steel*100 to a 1.06kg body bag in your hand (both normal and advanced inv shows 101.1kg), take every lump of steels out (adv inv shows 0kg about body bag, but both adv about entire character and normal still shows 101.1kg), then put 500g*1 to the container again, the weight calculation works again (both adv and normal inv shows 1.6kg). this means put in operation has weight recalculation but put out not.

**Comment by GuardianDll** [comment]
75560 is about multidrop, i honestly don't know does it affect AIM or not
If it's still an issue, it needs to get it's own issue

**Comment by LarnellThePureDangerous** [comment]
as far as i tested, 75798 is solved it seems. advanced inventory still has some problems (for example, can't put in a container even one piece if there's too much same "charge" count type items on a same place, like taking 1 cast iron chunk from 10000 of cast iron chunks on the floor) it seems, but about 75798, it's ok. during dropping items from adv inv, i can see displayed character's speed increasing.
