### ISSUE TITLE
segfault on save

### ISSUE THREAD

**Issue by amolofeev** [CleverRaven/Cataclysm-DDA#75792]
### Describe the bug

Hi there!

Autosave in lab loads with lots of errors and all tries to re-save got segfault

### Attach save file

[Sane4eG-trimmed.tar.gz](https://github.com/user-attachments/files/16647925/Sane4eG-trimmed.tar.gz)

### Steps to reproduce

load - quick save/save & quit

### Expected behavior

at least no errors on save

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 24.0.6; Codename: Wynsdey; 
- Game Version: cdda-experimental-2024-08-09-1521 9b2ac1a [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,4%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    иконка видит-игрока, HitButton_iso [sees_player_hitbutton],
    Перевод сложных диалогов [translate_dialogue],
    Скорость от ловкости [speedydex],
    Характеристики за убийства [stats_through_kills],
    Характеристики за навыки [StatsThroughSkills],
    Приручаемая живность [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
The segfault is a result of load failures:
- There's an error message stating "invalid use of nowhere item_location".
- The caller doesn't know a message is produced and proceeds to use the garbage position returned.
- That garbage position is then used when saving, which causes the save to blow up.
