### ISSUE TITLE
the new ImGui–based `uilist` implementation doesn’t support a second column

### ISSUE THREAD

**Issue by db48x** [CleverRaven/Cataclysm-DDA#75813]
### Describe the bug

The old `uilist` allowed the caller to specify both a label for each menu entry plus a second label to be drawn in a horizontally–aligned second column. The new `uilist` has the same interface and allows the caller to specify a second label, but I forgot to write the code that actually does anything with it.

### Attach save file

n/a

### Steps to reproduce

Butcher a corpse. As far as I know, this is the only menu in the game that uses this feature.

There is a menu that you occasionally get when crafting (and in certain other circumstances) that allows you to drop or store your wielded weapon. It puts the number of turns each option will take in a second “column”, but it is just faked by inserting spaces into the labels.

### Expected behavior

The butchery menu shows the time each option will take in the second column.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 809cfa67eb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

There is a little bit of doubt in my mind about whether I should implement this feature. It is not used very often, but leaving it out was technically a regression. However, consider the Consume Item menu. It’s very similar to a `uilist`, but has a completely separate implementation. but fundamentally it has only one difference from the `uilist`: it uses multiple columns. Eight of them, in fact. 

So maybe what I should do is have a separate menu implementation for more spreadsheet–like things. I could then make the butchery menu and the consume item menu both use it. And that unnamed drop–wielded–item menu.

Or maybe I should go whole hog, and just fold support for any number of columns into the `uilist` we already have.

**Comment by HadeanLake** [comment]
> As far as I know, this is the only menu in the game that uses this feature.

Vehicle select cosmetic variant had what I think is second column to the left of main column.
![vehg](https://github.com/user-attachments/assets/1e816b2a-42f0-4f51-946f-6d5268003ff2)

**Comment by db48x** [comment]
Perfect :P

![Screenshot from 2024-08-20 02-23-03](https://github.com/user-attachments/assets/cd0b3261-6599-4c46-a68d-9c1b66ffe3a3)

**Comment by db48x** [comment]
> Vehicle choose cosmetic variant menu had what I think is second column to the left of main column containing one char symbol. 

This is completely separate from the second column. Could you file it as its own bug report?

**Comment by HadeanLake** [comment]
filed as #75846

**Comment by ZhilkinSerg** [comment]
> > Vehicle choose cosmetic variant menu had what I think is second column to the left of main column containing one char symbol.
> 
> This is completely separate from the second column. Could you file it as its own bug report?

This is actually about zeroth (if we count from zero) column that should contain `extratxt` and there is no code to support it.
