### ISSUE TITLE
Speed loaders don't work

### ISSUE THREAD

**Issue by Holli-Git** [CleverRaven/Cataclysm-DDA#75814]
### Describe the bug

Speed loaders don't work, instead of loading the entire contents of the speedloader, it reloads 1 ammo

### Attach save file

N/A

### Steps to reproduce

1. Get an empty firearm/magazine with applicable speedloader
2. Reload firearm/magazine 
3. Notice it doesn't work

### Expected behavior

I expect that a speedloader rapidly reloads a firearm, and not one at a time

### Screenshots

![image](https://github.com/user-attachments/assets/d512b22f-c56e-4738-84f5-3e5a3490993e)
![image](https://github.com/user-attachments/assets/b862306a-32e7-4d80-948f-a23c19183b4d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: cdda-experimental-2024-08-18-1413 a1927ee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by mqrause** [comment]
I'm a little confused since there is a test reloading exactly that gun with exactly that speedloader (but different ammo).
