### ISSUE TITLE
Make Inhaler help with Smoke

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#7583]
As a [Bronchodilator](https://en.wikipedia.org/wiki/Bronchodilator), the inhaler should probably reduce or treat the smoke effect in addition to asthma attacks. [Smoke inhalation](https://en.wikipedia.org/wiki/Smoke_inhalation) is commonly treated with both Bronchodilators and oxygen apparently. Also, some other drugs common to the Cataclysm have been used as bronchodilators in the past before falling out of favor with those stick in the mud doctors. According to wikipedia,"Additionally some psychostimulant drugs that have an amphetamine like mode of action, such as amphetamine, methamphetamine, and cocaine, have bronchodilating effects and were used often for asthma due to the lack of effective β2-agonists for use as bronchodilator, but are now rarely, if ever, used medically for their bronchodilation effect." So perhaps those should help reduce the severity of smoke inhalation as well. 
##

**Comment by Night-Pryanik** [comment]
Closed by #20914.
