### ISSUE TITLE
Mobile terminal window small (again)

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#75838]
### Describe the bug

The mobile terminal when not using fullscreen mode is broken again

### Attach save file

N/A

### Steps to reproduce

Update mobile cdda. On  screen where you can activate fullscreen, do not. 

### Expected behavior

The terminal window to not be messed up like it has happened before

### Screenshots

![Screenshot_20240819-192904](https://github.com/user-attachments/assets/02bec064-8198-4d8e-8ad2-a9e661545bb4)

### Versions and configuration

![Screenshot_20240819-193255](https://github.com/user-attachments/assets/85b00857-f52f-4acd-b586-6a0674bf8903)

### Additional context

Maybe the same fix from before?

**Comment by MIQted** [comment]
changing font sizes usually helps me with this

**Comment by Srcwya** [comment]
> changing font sizes usually helps me with this

I know but this bug has happened before and has been fixed, also messing with my font size and then having to refix it after the bug was patched is a bummer.

Speaking of, is it okay to keep making new issues for already fixed in the past bugs like these?
