### ISSUE TITLE
Mild steel wire and legacy wire compatibility

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#75840]
### Is your feature request related to a problem? Please describe.

Ever since #72285 made fences drop `lc_wire` instead of `wire`, obtaining bulk amounts of `wire` for crafting anything but chainmail armor has become exceedingly difficult, even though (from what I've read) most commercial steel wire *is supposed to be* mild steel wire anyways. There is a need to either unify or migrate more instances of `wire` into `lc_wire` for parity.

### Solution you would like.

Note for myself after the discussion.
Bulk replace all `wire` to `lc_wire`.
Add migration of `wire` to `lc_wire`. (test this with a save before and after).

### Describe alternatives you have considered.

- Making an "any_wire" requirement group containing `wire` and `lc_wire`, making recipes use it and calling it a day

- Bulk overwriting all instances of `wire` to `lc_wire` and dealing with the consequences later

**Comment by GuardianDll** [comment]
I'd recommend to discuss it with Drew, but what I'd personally did is:
Add requirement group for all wire types
Replaced all recipes that require wire with this requirement
Replaced all instances of wire with mild steel wire
(optionally did the same thing with all steel chunks)

And left fixing places that supposed to have different grade of steel on later PRs, on one-to-one basis

**Comment by Drew4484** [comment]
Just documenting after our discussion on Discord, I support Guardian's proposed solution for as many `steel` to `lc_steel` groups you want to create.

**Comment by Bone-blood-moss** [comment]
Why don't we rename the Legacy wire. Scrap steel wire or junk/mixed steel wire.🤔 steel with a lot of Impurities.

**Comment by XygenSS** [comment]
> Why don't we rename the Legacy wire. Scrap steel wire or junk/mixed steel wire.🤔 steel with a lot of Impurities. Now That I think about it. We need a tear of steal that's right over but also below budget steel to To mark it as not bring just steel but has Different metals and Non metallics mixed in.

There's no reason to think that the wires are made of "junk" or "mixed steel," in almost all cases we're just cutting up wire fences and such. Almost all commercial steel wires are mild steel because it's cheap to manufacture. Pre-cataclysm sources are not junk, just salvaged. Big difference.

**Comment by Bone-blood-moss** [comment]
I'm fine with most mild steel replacing legacy steel. But with the replacement of legacy steel we need a steel for not pure steel. Budget steel is better for a wall hanging sword a display piece that won't survive at all cheap or not meant to combat. Then we have not pure steel that can survive combat but not for long. Steel with copper/aluminum or Other things mixed in.

**Comment by Drew4484** [comment]
I'd like to avoid adding any other types of steel **unless** there's a very specific use for it, especially when talking about alloy steels since those will almost certainly be unworkable by a survivor. This is why we don't have stainless steel even though many of the objects in game would be stainless. Consider if adding another type of steel offers a meaningfully distinct material. If the effective values are within a point of an already existing grade, I don't see any value in adding it.
