### ISSUE TITLE
Where have the Android releases gone ?

### ISSUE THREAD

**Issue by MIQted** [CleverRaven/Cataclysm-DDA#75843]
### Describe the bug

for 2 weeks there is no asset for android in the list of experimental dda releases

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

**Comment by MIQted** [comment]
> For some reason they fail to build, probably some compilator error, someone need to poke deeper

understood, thanks for the reply

**Comment by mqrause** [comment]
Got broken by #74341, seems like that was missing some android specific adjustments.

**Comment by MIQted** [comment]
> Got broken by #74341, seems like that was missing some android specific adjustments.

Understood, thanks

**Comment by Srcwya** [comment]
> Got broken by #74341, seems like that was missing some android specific adjustments.

I shouldve trust my gut to not update, i knew UI stuff would break mobile for some builds.

Too late now.
