### ISSUE TITLE
The game wont load (mobile)

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#75869]
### Describe the bug

The game will not start after picking a world

### Attach save file

N/A

### Steps to reproduce

1. Install update
2. Try opening a world
3. Wont load

### Expected behavior

Game load

### Screenshots

https://github.com/user-attachments/assets/6d0e09de-a010-4618-a1e9-7450f7f0ee49

### Versions and configuration

![Screenshot_20240822-003034](https://github.com/user-attachments/assets/6a67a496-7197-4d91-bc14-af3d7a6af222)

**Comment by Srcwya** [comment]
Yes, the video is 53 seconds of nothing

**Comment by XygenSS** [comment]
Please include your device information

**Comment by Srcwya** [comment]
> Please include your device information

My device is the moto g52

**Comment by mqrause** [comment]
See #75678, you might just have to wait longer?

**Comment by Srcwya** [comment]
> See #75678, you might just have to wait longer?

Damn, it kinda feels like forever when you dont have the loading screen
