### ISSUE TITLE
Transifex Administrator role is unmanaged and this makes improvements difficult

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#75889]
### Describe the bug

We regularly receive reports for bugs and issues with the Transifex project.  I have recently begun working with the Transifex team to attempt to resolve these issues.  They have informed me that @VlasovVitaly needs to transfer ownership of the project to someone currently active in the CleverRaven team.  Transifex said they reached out to you and received no response so I am assuming that you don't check your transifex messages so in addition to sending you a message there I am pinging you here on Github in hopes that will help us to reach you.  Thank you for all of your contributions to  this point and please help us one more time by giving administration rights to the Transifex project to the CleverRaven team. I hope this issue finds you healthy and well and that your future is bright.
Warmest regards,
Maleclypse

### Attach save file

N/A

### Steps to reproduce

Transifex

### Expected behavior

N/A

### Versions and configuration

Transifex

**Comment by VlasovVitaly** [comment]
Hello.
Please tell me what to do to transfer ownership?

**Comment by Maleclypse** [comment]
> Hello.
> 
> Please tell me what to do to transfer ownership?

I believe the transifex team has sent you a messsge you can reply to or these instructions can work. 

Or contact customer support and tell them you are transferring ownership of the project to mine or Kevin's email address.

**Comment by VlasovVitaly** [comment]
Guess i need only transifex user or email

**Comment by Maleclypse** [comment]
> Guess i need only transifex user or email

I've got the same username on Transifex as here

**Comment by VlasovVitaly** [comment]
Guess it's already done without me. Can you check this?

**Comment by VlasovVitaly** [comment]
> > Guess i need only transifex user or email
> 
> I've got the same username on Transifex as here

Strange... App can't find your nickname

**Comment by Maleclypse** [comment]
> > > Guess i need only transifex user or email
> > 
> > 
> > I've got the same username on Transifex as here
> 
> Strange... App can't find your nickname

![As a manager](https://github.com/user-attachments/assets/d9860eb5-20ee-4f86-be1b-fcfaa4c10bcc)


I show you as the owner still.  email address collinhsmith@gmail.com if you can look me up by email

**Comment by VlasovVitaly** [comment]
Sended

**Comment by Maleclypse** [comment]
> Sended

Got it! Thank you so much!

**Comment by VlasovVitaly** [comment]
Glad to help. Please don't remove me from manager's. I do nothing but sometimes my account can be used as last hope of restore membership.

**Comment by Maleclypse** [comment]
> Glad to help. Please don't remove me from manager's. I do nothing but sometimes my account can be used as last hope of restore ownership.

Absolutely will keep you on for it! Thank you again!

**Comment by Maleclypse** [comment]
@akrieger

**Comment by akrieger** [comment]
@VlasovVitaly are you a maintainer or owner of the project? We are looking to move to using fmtlib for string formatting, which uses `{}` fstring style placeholders, which transifex does not recognize by default for .po files. We need to add the appropriate regex in the global project settings which is not accessible to maintainers. Is it possible to transfer full ownership to an active dev? Thank you!

**Comment by VlasovVitaly** [comment]
Owner. Yes, i can transfer ownership if transifex allows that. To which user i need to transfer (it can be multiple)?

**Comment by Maleclypse** [comment]
> Owner. Yes, i can transfer ownership if transifex allows that. To which user i need to transfer (it can be multiple)?

Maleclypse and/or Kevingranade please if it can be.  I think there is also something called an adminstrator and if you can make multiple of those that's fantastic.

<img width="627" height="526" alt="Image" src="https://github.com/user-attachments/assets/aeaf65e1-fa8b-4733-add9-3e6f5ecc4669" />

**Comment by VlasovVitaly** [comment]
Sorry i am totally forgot about it. Added you and Kevin.
@kevingranade plz notice.

**Comment by Maleclypse** [comment]
> Sorry i am totally forgot about it. Added you and Kevin. [@kevingranade](https://github.com/kevingranade) plz notice.

Thank you!

**Comment by Maleclypse** [comment]
> Sorry i am totally forgot about it. Added you and Kevin. [@kevingranade](https://github.com/kevingranade) plz notice.

Got it working.  Thank you again!
