### ISSUE TITLE
Optional Ending to the Lore

### ISSUE THREAD

**Issue by GalacticApple** [CleverRaven/Cataclysm-DDA#75884]
### Is your feature request related to a problem? Please describe.

I think this has been discussed elsewhere, but I wanted to make a dedicated post for this here. As far as I'm aware, the current lore has it that the world will end in 100 years due to an environmental collapse. While I am fully aware that this is a cosmic horror game, from a story perspective I think it would be really beneficial for there to be at least *one* path where humanity/transhumanity figures out a way to survive on Earth. This doesn't mean humanity "beats" the blob, of course not. But it does mean that the end isn't the end. 

### Solution you would like.

Now for the main reason I'm writing this: to give my headcannon example of how the questing and broader plot could allow humanity to survive. You could do this any-number of ways, but this is mine. 

**In-Game:**

Currently, the "good" ending involves the player helping the Old Guard, Tacoma, Hub-01, Exodii and the Great Library. This results in a network of communities held together by the Old Guard that are able to survive by sharing resources and technology. To survive in the long-term though, humanity needs to do more; the end of the world is coming and the clock is ticking.

To begin towards the "best" ending, new quests would be given to the player after they help all these other factions. The first of these would be a series of quests where the player is asked by the Old Guard to mediate between the Hub and the Exodii. Since the player ostensibly is on good terms with both, and these factions would benefit a lot from working together, this would seem somewhat straightforward. 

After this you would have quests that amount to the player working for the Old Guard, Hub/Exodii and Tacoma to clear out facilities so they can be utilized again. The Old Guard might have the player take on military bases, Tacoma would have you clear out light industrial areas, lumber yards, mines, farms, etc. The Hub/Exodii might have you take on the labs to connect their reactors to the power grid and collect advanced technology. Maybe a penultimate quest would involve everyone coming together to clear out a nuclear power plant. 

After this, the factions would be in a "relatively" good place. They would have access to food and resources as well as the means to produce more of both. At least for now. However, with the threats ever-evolving and a future environmental calamity looming, more still needs to be done.

Perhaps one of the final quests would require you be a Cyborg or a Post-Threshold mutant. By now, the researchers at the Hub will have noticed the player's remarkable resilience in the face of the apocalypse. Their ability to survive the impossible again and again would suggest that something about them makes them uniquely suited to this nightmare of a world. If you're are a Cyborg or a Post-Thresh mutant, then they'll consider that to be the reason for your survival. Upon getting the quest, you'd simply be asked for a blood sample/cybernetic diagnostic scan and will be provided with the equipment to quickly return either. After that, you'd hear no more of this quest until the epilogue.

The main "final" quest(s) though would involve attempted to contact the Yrax for help. Let's say it would involve salvaging a damaged Yrax probe, connecting it to a network of re-connected MELCHIOR terminals (that the player will need to set up beforehand) and using it to "hack" the probe to send a message. It would take years for the message to reach the Yrax, and years more for them to send a response (assuming they bother too), so for now this would be the end of the player's role in the story. On to the epilogue!

**Epilogue:**
 
Continuing from the "good" ending, the survivor communities in New England are able to survive for decades. The Old Guard are even successful in connecting with other survivor groups across the country, though many remain out of reach of their main forces. 

If the player did the Cyborg/Mutant quest for the Hub, then it turns out they planned on using what made you, "you" to create a post-apocalyptic, super-soldier program. If you were a cyborg, then along with the Exodii the implants you used would slowly be manufactured in ever increasing numbers. If you were a mutant, then your blood sample would be used to create a new line of mutagens based on whatever list of mutations you had. These implants/mutagens would then be provided to volunteers who would serve as a kind of wasteland vanguard, responsible for taking on the various threats too dangerous for "normal" forces to handle. After a term of service, the cyborgs would have their implants removed and re-used, and the mutants could (optionally) be purified back into baseline humans. Due to logistical limitations, these vanguard soldiers wouldn't become widespread (for a long time at least), but they definitely gave humanity an edge. 

75 years after the apocalypse, humanity is on the cusp of oblivion. After several decades of expansion, civilization in North America is once again in full retreat. While the worst of the undead hordes have been culled through sheer attrition, the remaining anomalies and environmental decay are really taking their toll. However, at the 11th hour, the Yrax send their reply. They didn't expect humanity to still be here, but in exchange for very, very limited access to their technology, the Yrax would be allowed (not that they *really* need permission) to conduct experiments on Earth's anomalies/cosmic horrors and generally observe humanity's progress. The Yrax also provide a means to communicate with the Mi-go, as well as a sample of their (I'll call it) bioform technology used for food production. The bioform food is the real game-changer. These customizable fleshy-blobs can be used to produce nutritious meals indoors and at scale. Sure, the meals they make are mostly just variations of bland paste, but it's calories. After their introduction, most pre-Cataclysm staples become infrequent treats as agriculture moves fully indoors. 

Now able to communicate with the Mi-Go, the Old Guard makes separate deals with them, mostly along the lines of "you can stay here and do research, but no kidnapping and dissecting people. We'll share our knowledge with you if you share with us". 

These alien interactions enable humanity to survive for several more centuries. 

**_TIME-JUMP_** (but really you could end it here)

Some 300-400 years after the Cataclysm, the Earth is nominally under the jurisdiction of the Union of Nations. North America, Australia, North Africa and most islands are considered to be the planet's "safe" zones. Northern Europe, the British Isles, Siberia, Madagascar, South Africa, Chile and Argentina are mostly under humanity's control. Everywhere else is a deadzone. This means they're either still overrun by the undead/mutant horrors or were permanently scarred by Yrax testing.  

At a certain point, the Yrax simply up and left, though fortunately humanity was mostly self-sufficient by then. 

The Mi-Go also left suddenly; so suddenly in-fact that the Mi-Go still on Earth were stranded there. 

Eventually, a Yrax ship enters the system to evacuate a previously undetected observation station in orbit around the Moon. However, something goes wrong after the ship docks and the station is destroyed by an explosion. Fortunately, the ship itself is mostly undamaged as it was blown clear of the facility. In an effort that would've made Kennedy proud, a rudimentary space program is established to reach the abandoned ship. Upon arriving however, the first expedition to the ship discovers that the Yrax crew are undead, having somehow succumbed to the influence of the blob. After a second, better equipped expedition is sent to clear the ship out, a new program is launched to reverse engineer it's FTL systems. Together with the Exodii, what was gleaned from the Yrax, and the Mi-Go researchers still on Earth (who are probably eager to get home), a rudimentary FTL capable starship is produced somewhere around the 500 AC (After Cataclysm) mark. 

Unfortunately, all is not good in the galaxy. As the survivors of Earth begin to spread out, they discover that after the Mi-Go took blob-infected samples from Earth, they had inadvertently begun to spread it's influence to other civilizations they interacted with. In a stellar apocalypse that spanned centuries, the other civilizations of the galaxy attempted to save themselves by engaging in a near-total war of extermination against the Mi-Go. While successful in driving (most of) them from the galaxy, it did not stop the blob. Numerous wars, blob outbreaks, and failed attempts at self-preservation saw 99% of sentient life in the galaxy go extinct. By 500 AC, only a few holdouts remain on cut-off worlds and far-flung ships hiding in the void.

**Comment by kevingranade** [comment]
Everything about this is directly contrary to how the game operates, no we will not be moving in anything remotely resembling this direction.
