### ISSUE TITLE
Zone Manager. Zone description does not fit on the screen

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#75909]
### Describe the bug

Part of the window with the description of the zone to be added is not visible. See screenshot

![1](https://github.com/user-attachments/assets/d66b5187-7b19-4e23-a629-d8ff230b41c5)

### Attach save file

n/a

### Steps to reproduce

1. Open the zones manager `Y`
2. `a`dd a new zone

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-08-23-1745 80626e6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Before
![2](https://github.com/user-attachments/assets/ce71a574-868f-4592-9960-55a15563745f)

**Comment by 01ingsit1** [comment]
Same problem.

**Comment by DukePaulAtreid3s** [comment]
I have the opposite, my screen is stretching it so much I cannot see the name of the zone

**Comment by Comrade-Soupbeans** [comment]
having a similar though slightly different issue, the window as a whole is larger than my screen, mostly filled with blank space for some reason
![image](https://github.com/user-attachments/assets/8f451118-9e0b-43ad-b5e6-0941bfb3db74)
worth noting i play on a 1440p monitor so i should have no issue fitting the menu on screen

**Comment by Gramosa** [comment]
> having a similar though slightly different issue, the window as a whole is larger than my screen, mostly filled with blank space for some reason ![image](https://private-user-images.githubusercontent.com/26364270/363469853-8f451118-9e0b-43ad-b5e6-0941bfb3db74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDk4NzcsIm5iZiI6MTcyNTIwOTU3NywicGF0aCI6Ii8yNjM2NDI3MC8zNjM0Njk4NTMtOGY0NTExMTgtOWUwYi00M2FkLWI1ZTYtMDk0MWJmYjNkYjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE2NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMGY0OGI4MGMwNjIyNTM3NTNlZTgwODlhYjA4MWM3MjZhYjZjY2UxMDNlNGZiMzU5OGY1ZmJhYTgzYTg2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4WloC5UjGr_Cp2Ll2rPbDrUA3MYVUQNXjjv9cg_Qqog) worth noting i play on a 1440p monitor so i should have no issue fitting the menu on screen

I'm also facing this problem

**Comment by IdleSol** [comment]
it's okay

![1](https://github.com/user-attachments/assets/b8413c9e-d82e-4b6c-87e9-3328a8ca9370)
