### ISSUE TITLE
Radiation decontamination

### ISSUE THREAD

**Issue by Alithsko** [CleverRaven/Cataclysm-DDA#75928]
### Is your feature request related to a problem? Please describe.

Given that radioactivity is considered the worst of the negative mutations, it would help a lot if we were able to decontaminate radioactive areas

### Solution you would like.

We already have a chemical reaction we can use, manganese dioxide, potassium hydroxide and potassium chlorate in an electrolysis reaction to create potassium permanganate, which is used to clean areas of radiation in labs in addition to nitric acid, unfortunately it can be used to refine cocaine, meaning it's heavily restricted, but that may mean you can also find it in such places related to drug trade

**Comment by kevingranade** [comment]
Please be specific about what you mean, do you mean decontamination the player or irradiated areas?
potassium permanganate seems to be indicated for superficial skin contamination,  I'm not seeing it being recommended for other decontamination,  please share whatever sources you're relying on for this.

In a general sense, I don't see enabling generic,  "decontaminate an arbitrary area" as a feature,  and "the radioactive mutation is annoying so we should be able to do this" doesn't hold up,  don't be radioactive,  it's basically a death sentence.

**Comment by failboat78** [comment]
If it's an outdoor area then decontamination means more than that. Means removing all plants and even top X inches of the soil.

**Comment by Alithsko** [comment]
> Please be specific about what you mean, do you mean decontamination the player or irradiated areas? potassium permanganate seems to be indicated for superficial skin contamination, I'm not seeing it being recommended for other decontamination, please share whatever sources you're relying on for this.
> 
> In a general sense, I don't see enabling generic, "decontaminate an arbitrary area" as a feature, and "the radioactive mutation is annoying so we should, be able to do this" doesn't hold up, don't be radioactive, it's basically a death sentence.

The fact that radioactivity is a death sentence is what I specifically mean, I also know that this chemical only works on flatter artificial surfaces, and having this be on the expensive side would still force a drive to rid yourself of such a bad mutation or at the very least work on making a vehicle for a nomadic lifestyle which is a standard strategy, I just am suggesting any way to try to fight back but still have it's intense downside be very real, the other guy mentioned decontamination in a way that also involves intense labor or mechanics to build heavy machinery, which would fit the bill well too, I mean there's also radiation suits, but if you're using mutations you probably can't wear that, and if we were to update radioactivity anyway wearing a radiation suit might even trap it in which would be dangerous, there is radiogenic too but that mostly reduces the impact of your radiation, though still useful

**Comment by Alithsko** [comment]
Another idea is to add interrupt prompts when having radiation detection to let you know that things are getting contaminated around you so you can move a few steps in that field or abandoned building you're crafting in, it could make radiation cbms and radiophile that much more useful

**Comment by kevingranade** [comment]
Ok so your whole plan is specifically to continuously scrub your surroundings to decontaminate them while continuing to irradiate them.  Do you see the flaw in this plan?

Also I'm not sure you're following how these mitigations work, you can't just denature the radioactive particles, decontamination is just about capturing them in some medium, either a cleaning solution or by stripping off material, now you have "irradiated cleaning solution" or "irradiated soil" that you need to dispose of somewhere, and this would be something you'd need to do constantly.

The WHOLE POINT of the mutation is there's no meaningful mitigations, so no, I have no intention of bolting on a not actually meaningful system to try to mitigate it.  Either see if you can land on a mix of mutations that keeps it from killing you, or purify it away.

**Comment by Zireael07** [comment]
How about adding the above to Frequently Made Suggestions? I bet more players have thought of mitigations
