### ISSUE TITLE
The android build of `cdda-experimental-2024-08-25-0446` can't start

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#75935]
### Describe the bug

The android build in https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-08-25-0446 cannot run.

### Attach save file

N/A

### Steps to reproduce

1. Install the android build of https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-08-25-0446
2. run the android build
3. crash

### Expected behavior

It not crashing

### Versions and configuration

- OS: Android 13
- Game Version: 5237214

### Additional context

[crash.log](https://github.com/user-attachments/files/16739547/crash.log)
[debug.log](https://github.com/user-attachments/files/16739548/debug.log)

**Comment by harakka** [comment]
Likely the same issue as underlying #75818

**Comment by harakka** [comment]
This seems like a regression caused by #75920

**Comment by alef** [comment]
Try #75937 for invalid fonts. Not sure it is related to #75818 for the language selector.

**Comment by gettingusedto** [comment]
Updated my android build to the current experimental that has #75937, the game did infact stops crashing on game start.

**Comment by harakka** [comment]
Fixed by #75937
