### ISSUE TITLE
Binoculars should increase "detailed" vision range

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#75950]
### Is your feature request related to a problem? Please describe.

Recently introduced "detail" level map mechanics is unaffected by binoculars or similar vision-enhancing devices. Although binoculars increase overall reveal radius, they do not increase radius where "vague" information becomes "detailed".
Without any vision assistance, PC can ascertain details in 5 OM tiles range, with binoculars it remains the same.

### Solution you would like.

Vision-enhancing devices like binoculars & telescopes should increase radius of "detailed" map information reveal, as they are in fact magnify vision, that's their primary purpose

### Additional context

[Port Hadlock-trimmed.tar.gz](https://github.com/user-attachments/files/16741351/Port.Hadlock-trimmed.tar.gz)
save where it can be verified/reproduced

**Comment by ZhilkinSerg** [comment]
Binoculars (and some other things) should double your range:

https://github.com/CleverRaven/Cataclysm-DDA/blob/10d0f1c2ea3c9cd8b1e49f1aa6d17422e9481af4/src/character.cpp#L1327-L1350

Are you positive this does not work properly?
