### ISSUE TITLE
Menu black when entering via ESC

### ISSUE THREAD

**Issue by RobertBoettcherSF** [CleverRaven/Cataclysm-DDA#75967]
### Describe the bug

In game, press ESC, Menu container will come up but content will be black. You have to press up or down twice to see anything.

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 8185064 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Monsters [Only_Wildlife]
]

### Attach save file

[The Little Bonus Room-trimmed.tar.gz](https://github.com/user-attachments/files/16744765/The.Little.Bonus.Room-trimmed.tar.gz)

### Steps to reproduce

1. Load character.
2. In game press ESC to open Menu.
3. Cant see menu points cause all black.
![2024-08-26 (10)](https://github.com/user-attachments/assets/192956be-8833-4b33-889e-b1980db3c93e)
![2024-08-26 (12)](https://github.com/user-attachments/assets/c777e1e9-f144-4f3c-b532-8e79ee766677)

### Expected behavior

Visible menu's

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 8185064 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Monsters [Only_Wildlife]
]

**Comment by strategictraveler** [comment]
Can reproduce with different results:

1. Open debug menu, select spawn item, select item.
2. Go to different positions in the list.
3. When asked for the amount of item, press ESC three times and then look at the menu.

* 1st try with an engine
![1](https://github.com/user-attachments/assets/a44f6e19-c440-4c10-a81f-2d807f33653e)
![1](https://github.com/user-attachments/assets/0602ba43-f18f-417d-9f67-80bbb70c3717)

* 2nd try with an ammo can
![2](https://github.com/user-attachments/assets/f84569d1-6e8b-4731-9e99-658dc774f529)
![2](https://github.com/user-attachments/assets/6cd3acdd-7b80-426b-b9f3-d5c54373037a)

* 3rd try with 101 repairs
![3](https://github.com/user-attachments/assets/955bba2a-4039-4ad6-bedd-55c0901b236b)
![3](https://github.com/user-attachments/assets/efb66650-5662-49a2-963f-62adb5e98c9c)

- OS: Linux
    - OS Version: Fedora 40
- Game Version: cdda-experimental-2024-08-22-0621 15a5866 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment]
Could confirm during testing with a different issue. I am not entirely sure how to reliably reproduce it but it definitely exists.
