### ISSUE TITLE
Hair/Haircuts aren't working properly

### ISSUE THREAD

**Issue by bird-ee** [CleverRaven/Cataclysm-DDA#75989]
### Describe the bug

I couldn't seem to get the makeshift haircut kit to work UNTIL I used the debug menu to give myself a different haircut, and after that it would give me blonde hair only, no matter what my natural hair color was set to. I also noticed that by default the character was given every natural hair color for some reason.

### Attach save file

N/A

### Steps to reproduce

1. Hold makeshift haircut kit
2. [A] to cut your hair
3. Shaves you bald no matter what you choose

### Expected behavior

1. Hold makeshift haircut kit
2. [A] to cut your hair
3. Your hair is cut to the desired style

### Versions and configuration

W10, 6848495

**Comment by RenechCDDA** [comment]
Please include your compressed save file as the form instructs you, it attaches debugging information.

**Comment by Night-Pryanik** [comment]
Fixed by #76106.
