### ISSUE TITLE
`u_location_variable` only detects the first top left entity under the aoe

### ISSUE THREAD

**Issue by RedMisao** [CleverRaven/Cataclysm-DDA#75997]
### Describe the bug

The eoc effect `u_location_variable` can use to search for an entity's ("terrain" / "furniture" / "field" / "trap" / "monster" / "zone" / "npc") coordinates under the area where it's run. I tried to use it for a "detect X" kind of spell for non-monster entities, but it seems to return `true` after it finds the first target_id towards the top-left position.

### Attach save file

N/A

### Steps to reproduce

1. Add the following json somewhere
```json
  {
    "id": "utsuho_detectrad_furn_eoc_WIP",
    "type": "effect_on_condition",
    "effect": [
      { 
        "u_location_variable": { "global_val": "var_detectrad_furn_TEST_1" }, "furniture": "f_bench", "target_min_radius": 0, "target_max_radius": 32,
        "true_eocs": [
          {
            "id": "var_detectrad_furn_TEST_1_eoc",
            "effect": [ 
              { "u_set_field": "fd_clairvoyant", "radius": 0, "intensity": 1, "target_var": { "global_val": "var_detectrad_furn_TEST_1" } },
              { "message": "<global_val:var_detectrad_furn_TEST_1> AAA", "type": "mixed" }
            ]
          }
        ]
      },
      { 
        "u_location_variable": { "global_val": "var_detectrad_furn_TEST_2" }, "furniture": "f_bench", "target_min_radius": 0, "target_max_radius": 32,
        "true_eocs": [
          {
            "id": "var_detectrad_furn_TEST_2_eoc",
            "effect": [ 
              {
                "if": { "map_furniture_id": "f_bench", "loc": { "global_val": "var_detectrad_furn_TEST_2" } },
                "then": [
                  { "u_set_field": "fd_clairvoyant", "radius": 0, "intensity": 1, "target_var": { "global_val": "var_detectrad_furn_TEST_2" } },
                  { "message": "<global_val:var_detectrad_furn_TEST_2> BBB", "type": "mixed" }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
````

2. Create a new Evacuee at any of the refugee centers, so you have plenty of `f_bench` lying around
3. Run the EOC, only a single pair of coordinates will be printed (bench located top left)
4. Move that bench so another is located at the top-most left-most position
5. Run the EOC again, same thing for the bench that's top-most left-most

### Expected behavior

I expected to obtain the coordinates of all the benches under the aoe

### Screenshots

![1](https://github.com/user-attachments/assets/4b820ddc-64f3-4a06-a7f2-a895a1a0736c)

![2](https://github.com/user-attachments/assets/959b7f07-eafb-4902-aabd-8d79f14d99f4)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 5441d21 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I believe this is unintended behavior because anything relying on `u_location_variable` (or `npc_location_variable`) that runs on an aoe will be pointed towards the top left direction and only for a single entity. For spells it will shoot only once and always towards that direction, it cannot be using for counting the number of entities because it will stop after it detects the first one, and so on.

I also tested this with type_id monster and then placing two `mon_zombie_hazmat`, again only the coordinates of the first one are printed. I did not tested it with the other type_ids.

**Comment by PatrikLundell** [comment]
There are really two different use cases:
1. Find the first thingie matching the criteria and return that one (and the search behavior ought to be consistent and suitable for the usage: if you case which one you get you usually wants the closest one [best hit chance, shortest distance to walk to, etc.]).
2. Find all thingies matching the criteria and return all of them.

If you're attacking something, talking to it, or doing anything else that requires a single target you'd want the first behavior.
On the other hand, if you wanted to count the number of thingies or do something to all of them you'd need the second one.

You shouldn't have a case where you'd look for something and then fire a gun at all matches at the same time, for instance, whereas some kind of field effect would apply it to all matches.

**Comment by PatrikLundell** [comment]
I consider the return of a single match to be the proper function of this. If you want something that somehow returns all and affects all of them it should be a separate operation (named appropriately, of course).

Which match you want to return depends on the use case, so some kind of search criterion should probably be a parameter. Some alternatives:
- First one found (default, using whatever search algorithm the implementation happens to use).
- Closest one (where some hard coded logic would still return them in the same order with several at the same distance).
- Closest one beyond a given distance (if you want to send a fireball you probably don't want to catch yourself or your minions in the blast). If it was code (and not JSON) I would assume you'd pass a fitness function into the operation. With code you might be able to also require a given distance from your minions as well.

**Comment by RedMisao** [comment]
If this is the intended function, I will close the issue.
