### ISSUE TITLE
Zombies go down the stairs to the wrong place

### ISSUE THREAD

**Issue by Agnistel** [CleverRaven/Cataclysm-DDA#76020]
### Describe the bug

Zombies go down the stairs to the empty tile below them, instead of going down to the base of the stairs.

### Attach save file

N/A

### Steps to reproduce

1. Spawn/find a ladder whose top and base are on different tiles
2. Spawn zombies on top
3. They go down to the tile below them, not the stairs

### Expected behavior

They go down the stairs correctly

### Screenshots

![2](https://github.com/user-attachments/assets/167ef1a2-e77a-42b1-bcc3-88266287070e)
![1](https://github.com/user-attachments/assets/1770669e-bea9-43be-ba9f-954c0392176b)

### Versions and configuration

Windows 10
Last experimental
mods NoHope, CrazyCata, MMA, bionic_prof, extra_mut
Lab Escape Scenario
Science lab under Research facility map

**Comment by harakka** [comment]
Known issue with old labs and couple of other places with harcoded mapgen and stairs. Old labs are slated for removal and stairs being aligned will be a requirement, I don't think anyone is going to write code to try to fix this otherwise as it's kinda pointless.

**Comment by Agnistel** [comment]
> Known issue with old labs and couple of other places with harcoded mapgen and stairs. Old labs are slated for removal and stairs being aligned will be a requirement, I don't think anyone is going to write code to try to fix this otherwise as it's kinda pointless.

Ok, thanks for the explanation.
