### ISSUE TITLE
Trust-based NPC weapon assignment

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#76037]
### Is your feature request related to a problem? Please describe.

NPCs will often say stupid things like "No I will not wield that combat knife, my army helmet is better." They are also unable to understand complex ideas like "we are going to fight a bunch of slimes, a blade works better than a blunt weapon."

This can currently be worked around by simply taking everything away from them that their weapon analysis function could mistake for a better weapon, but that's quite annoying.

### Solution you would like.

NPCs have a trust score for the player character. Above a certain trust rating, you should simply be able to insist that the NPC wields whatever you are trying to get them to use.

The simplest way to do this would be to apply an invisible "wielding_ordered_weapon" effect to the NPC which would disable their usual weapon selection AI. The effect could also periodically fall off if the character was disarmed or otherwise lost their weapon, or if their engagement orders changed - for example if they were using a mace and got new orders to use ranged instead, and they had a gun on them.

### Describe alternatives you have considered.

I think just trust is enough, but you could also compare the characters' relative combat skills, intimidation factor, etc.

**Comment by GuardianDll** [comment]
both this issues should not be fixed by making player puppeting all the npcs they have, it should be fixed by making NPCs behave smarter

**Comment by fairyarmadillo** [comment]
I don't think that's possible. NPCs cannot think ahead or make plans like the player, and the player cannot communicate complex ideas to NPCs.

**Comment by RenechCDDA** [comment]
This is the completely wrong approach. As Guardian mentioned, it is not desirable that the player micromanage their followers.

>NPCs will often say stupid things like "No I will not wield that combat knife, my army helmet is better."

If you have an example of this, please open a bug report so it can be resolved. Otherwise, there's nothing to be done here.
