### ISSUE TITLE
[ImGui] relative paths in `fonts.json` and separated CDDA-userdata directory (by Kitten CDDA Launcher)

### ISSUE THREAD

**Issue by vetall812** [CleverRaven/Cataclysm-DDA#76057]
### Describe the bug

ImGui is unable to load font corretly if it is defined by relative path in `fonts.json` config file and the CDDA userdata is moved to another location by Kitten CDDA Launcher (for example).

### Attach save file

N/A

### Steps to reproduce

1. Unpack the game
2. Download Kitten CDDA Launcher
3. Move userdata to another location (lets name it %userdata%)
4. Define path to selected font as `/font/my_font.ttf`
5. Launch game. The game will load correct font, but ImGui doesn't.

### Expected behavior

I expect ImGui to load fonts correctly from `%userdata%/font/my_font.ttf`
It loads font if path is defined absoltely - for example `c:/cdda-userdata/font/my_font.ttf`

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4842 (22H2)
- Game Version: cdda-experimental-2024-08-30-1256 1ab5fb4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
We don't offer separated directories, this is something handled by your launcher. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/0c16bd0a437535886ece70ae2baab1025aa9b35c/src/path_info.cpp#L294-L297

[We cannot and do not provide support for the launchers.](https://github.com/CleverRaven/Cataclysm-DDA/wiki/FAQ-from-Discord#launchers-mod-packs-and-optional-content) You can try contacting the author of the launcher you are using or whatever troubleshooting they may have provided.

**Comment by vetall812** [comment]
@Fris0uman , any ideas why ImGui cannot get the correct font when the game itself can?
