### ISSUE TITLE
Integrated AR CBM should be like advanced AR glasses or better

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#76084]
For some reason they cannot play music, which is why I chose to install it yet I still have to carry around an MP3 so I can actively raise focus.

### Solution you would like.

Make it so it has all the functions of the advanced AR glasses, MP3 and smartphones all in one.

**Comment by Vgoloshivskiy** [comment]
pretty sure you need Integrated AR System CBM, Infolink more like a radio.

**Comment by Bone-blood-moss** [comment]
Mp3, 2 way radio and radio Sounds Better it works better with the AR system cbm. It also makes more useful and players more likely to go buy it more

**Comment by Torres84f** [comment]
> pretty sure you need Integrated AR System CBM, Infolink more like a radio.

my bad, brainfart... I meant the integrated AR system -_-

**Comment by kevingranade** [comment]
This rationale doesn't add up,  it's practically free to add audio to a pair of AR goggles, but if we're talking a implanted device an eye augment and a hearing augment are different things.

**Comment by Bone-blood-moss** [comment]
? How is it not planned we talking about infolink cbm adding more Functionality to it. It's already a 2 way radio We're talking about adding the ability of the normal radio to it.

**Comment by kevingranade** [comment]
Read the thread, they clarified they meant the AR CBM, which is literally just eye implants.
Issues around the infolink are seperate.
