### ISSUE TITLE
Monsters in No Hope and DinoMod have problems using ranged weapons

### ISSUE THREAD

**Issue by Agnistel** [CleverRaven/Cataclysm-DDA#76097]
### Describe the bug

The only weapons they use are machine guns. Monsters armed with a flamethrower or laser have no ammo. Bots with grenade launchers do not use it.

### Attach save file

N/A

### Steps to reproduce

1. Spawn tripod or tyruckusaurus, they don't have fuel for the flamethrower.
2. Spawn spinosaurus bio-op, it doesn't have energy for a laser.
3. Spawn a chicken walker or beagle tank, remove their machine gun ammo via the editor - they don't use grenades.

### Expected behavior

They have ammo and they use all available weapons.

### Screenshots

![111Безымянный](https://github.com/user-attachments/assets/bbf8c460-2c7b-4a67-9f6a-0afb3904bc7a)
![2222Безымянный](https://github.com/user-attachments/assets/6399e48e-733d-4449-af00-258ce2ab9fa3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: cdda-experimental-2024-09-01-0035 3b69d6f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    DinoMod [DinoMod]
]

**Comment by Agnistel** [comment]
It might be related to #75347

**Comment by LyleSY** [comment]
Confirmed DinoMod elements in testing with the two monsters provided. Since they share code I expect this hits No Hope in the same way

**Comment by LyleSY** [comment]
Tested to confirm other monsters with long range attack like Choppersaurus still work.

**Comment by LyleSY** [comment]
I also checked the Aftershock code changed at the same time and it looks good
