### ISSUE TITLE
Revert #75624 "Improve invlet management for Magiclysm spell list."

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#76098]
### Is your feature request related to a problem? Please describe.

This PR broke the whole spellcast menu that I can't even test spells in newest experiment build.

### Solution you would like.

Revert #75624

### Describe alternatives you have considered.

Let it remain broke until someday someone fix it.

**Comment by BaumgeistOne** [comment]
What exactly do you mean by "broke"? Is it the same as #76085?

**Comment by Naadn** [comment]
More like #76042, I choose to cast A but it cast B instead, and when I choose B it cast F and so on.

**Comment by Naadn** [comment]
> More like #76042, I choose to cast A but it cast B instead, and when I choose B it cast F and so on.

More like https://github.com/CleverRaven/Cataclysm-DDA/issues/76042, I choose to cast A but it cast B instead, and when I choose B it cast F and so on.

**Comment by Naadn** [comment]
> What exactly do you mean by "broke"? Is it the same as #76085?

More like https://github.com/CleverRaven/Cataclysm-DDA/issues/76042, I choose to cast A but it cast B instead, and when I choose B it cast F and so on.

**Comment by RenechCDDA** [comment]
This is not appropriate for a suggestion. Please put some further thought into your ideas before opening any further issues. In particular, calling for a revert is never a valid suggestion - at that point you're just trying to tell people what they should work on. That's not how we (or any FOSS) work.
