### ISSUE TITLE
curses/imtui: cursor is duplicated when searching in the keybinding menu

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#76129]
### Describe the bug

![image](https://github.com/user-attachments/assets/cfdaa753-a6f7-41f0-b069-8763e2584a37)

Note the second gray square. Which can also overlap stuff:

![image](https://github.com/user-attachments/assets/eed46112-a943-4cf0-9aff-1d1bce5e87b4)

### Attach save file

n/a

### Steps to reproduce

1. Use curses.
2. Enter any game.
3. Hit `?` to go into the key bindings.
4. Search anything.

### Expected behavior

The weird square doesnt happen.

CC @db48x. But its a low priority issue because it doesnt break really stuff.

### Versions and configuration

I'd paste the debug info here but I can't because the debug.log is not being generated.

This is cdda-linux-curses-x64-2024-09-01-1411.

**Comment by sparr** [comment]
#77001 describes a variation(?) of this(?) issue that very much breaks stuff.

**Comment by katemonster33** [comment]
looks like we will need to disable the drawing of the cursor on imtui to prevent this issue
