### ISSUE TITLE
Zone Imgui list using max terminal height acts weird if the mouse is at the bottom edge of the screen even while hidden

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76182]
### Describe the bug

When scrolling through the zone manager's 'add zone' menu to select a zone, using the arrow keys to scroll results in weird behavior if the mouse cursor is at the bottom of the screen. The imgui list also takes up the entire height of my window. My mouse option is 'HideKB' which hides the mouse on any keyboard input. i very rarely use my mouse in game, so this works for me. However, having the mouse cursor at the bottom edge of the screen results in the arrow key's selection of a menu item act very weird and buggy. Presumably, the mouse still affects what option is selected despite being hidden and off the selection area (the blue lined area when a selection box is focused with the imgui). 

There's also the issue of having the mouse cursor directly on the selection menu, even if it is hidden, I can put the mouse cursor over the window, then use arrow keys to go back and forth between 2 options, which is also a bit weird.

My terminal is 210 x 65. This may be relevant as the imgui information is also slightly cut off of the bottom of my screen.

### Attach save file

N/A all saves affected

### Steps to reproduce

1. Go into zone manager
2. Select A to add a zone
3. Move mouse cursor to bottom edge of screen
4. Use arrow keys to see very weird selection

### Expected behavior

If the mouse is hidden in the 'Mouse control options' -> 'Hide mouse cursor' using either 'Hide' or 'HideKB', the cursor should not have any affect on any window if it is currently hidden. if the user moves the mouse, then mouse-selection should re-activate.

### Screenshots

![image](https://github.com/user-attachments/assets/c77d4be7-0ca6-46e1-a007-c41db26e3240)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-01-0300 2d41010 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

If the list width could also be toned down and centered rather than be full screen, that would be nicer-looking.
#76128  (only putting this link here because its slightly relevant, and this is not a duplicate of it)
This issue deals with the mouse cursor interacting with imgui while hidden, not specifically for the screwed up window size or text cut off.

**Comment by IdleSol** [comment]
Update the game.
- #75909
- #76157

**Comment by CoroNaut** [comment]
all issues solved, mouse is ignored, window is centered, and within the monitor.
