### ISSUE TITLE
MoM: Broken spellcasting window

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76192]
### Describe the bug

There's some offset applied when I choose a spell to cast. It changes with amount of available spells (it was 1, now 2). 
For example, when I select Concentration Trance here
![image](https://github.com/user-attachments/assets/ee45767b-79f3-45cb-8b1d-abb2f1151095)
It starts casting Fountain of Flames
![image](https://github.com/user-attachments/assets/a102c2e9-5ce4-4f40-a173-6ff555b74ce1)

Same when I choose Stop Concentrating 
![image](https://github.com/user-attachments/assets/752e76a7-ae36-4ffd-8533-bd028c8046a0)
Triggers Phase
![image](https://github.com/user-attachments/assets/327cfc3d-17f6-4681-80d2-23d1f59ba4d3)

Doesn't matter whether I use LMB / Enter / hotkey.

### Attach save file

[Nairn-trimmed.tar.gz](https://github.com/user-attachments/files/16868485/Nairn-trimmed.tar.gz)

### Steps to reproduce

1. Open spellcasting menu
2. Choose any spell
3. Spell 2 rows before it starts casting

### Expected behavior

A correct spell is chosen from the menu

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-03-0707 c0f8c04 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by AntiquePass** [comment]
Same thing happening with android version. I don't know what the offset is, but I can't use phase anymore since it's casting other spells everytime and can't find which one is casting phase.

**Comment by ThePotatomancer** [comment]
this is duplicate of #76042 and I have a PR waiting for review that fixes it: #76137

**Comment by dev-dsp** [comment]
Works great in [2024-09-05-0451](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-09-05-0451), thanks a lot!
