### ISSUE TITLE
Can't turn on the vehicle engine from controls menu

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76209]
### Describe the bug

Can't turn on the vehicle engine from the controls menu
If you go to the tile with controls, then `^ e l`  - engine starts and you can walk around. Turning off the engine also works via the controls menu.

### Attach save file

[Nairn-trimmed.tar.gz](https://github.com/user-attachments/files/16887357/Nairn-trimmed.tar.gz)

### Steps to reproduce

1. Have a vehicle with controls and an engine installed
2. Examine controls tile
3. Select 'Turn on the engine' or press 's'
Nothing happens.

### Expected behavior

Engine can be turned on from the controls menu

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-03-0707 c0f8c04 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by HadeanLake** [comment]
this was broken by #75467
driving remotely also is broken by it
