### ISSUE TITLE
Some ideas for new challenges

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#76212]
### Is your feature request related to a problem? Please describe.

The basic idea, having something that requires constant recharging.

### Solution you would like.

1. Wedlock (film 1991)

Bomb collar. A piece of clothing in the form of a collar. Constantly consumes charge (i.e. it is initially on). When the charge expires, it deals damage (lethal(?)). Small assumption, it is possible to connect to a vehicle or electrical grid. Cable 1-2 meters.

The capacity of the built-in battery is based on 4 hours of operation. Naturally, it is not possible to remove it.

1a. A lighter version (?). Single character. The main problem is finding something to charge the collar from.
1b. Add a partner with a collar. Distance to him more than 10 tiles, explosion. Dead partner? Carry his corpse or dissect him and carry his collar or explode.

Recipe for level 7 devices, to disable the collar.

Additional complication, start in prison.

2. The Lost Cyborg
Backstory. By accident or misdirection, but you found yourself on earth much sooner than your comrades. Since your discovery and capture, you have been subjected to a great deal of experimentation. As a result, virtually all of your bionic enhancements have either been removed or damaged. Now, all that separates you from ceasing to function is the charge of a few batteries. Fortunately, you still have the option of recharging. If you can get out of your cell and find a power source.

Start as a character with bionics in a lab. The new item is a bionic brain/heart or something similar. *your personality is recorded in a permanently powered brain*. Cessation of power means death... or resetting all skills and abilities, provided you have followers. Who can restart you after some time.

Similar to the past, the number of batteries is calculated based on 4 hours of device operation.

The goal is to get out of the lab, get to Rubik's, where you can buy additional batteries and/or generators. Conditionally, the energy should be enough for 24 hours and any generator should appear.

Complication. Reducing the number of batteries. Taking damage every hour. And producing noise a few minutes (10-30) before shutting down. It's also insurance to wake up a sleeping character. 

3. Implanted bomb.

Something in between these two. A bionic that constantly draws energy and explodes if it runs out of energy. The difference is that Rubik can't extract it. Only autodoc and high complexity operation. Overall target 10 computers, electronics, medicine and devices.

The challenge is passed if the bomb is removed.

**Comment by PatrikLundell** [comment]
Utterly ridiculous, in my opinion. On the other hand, if it's not forced onto others either through game play or game maintenance of it, I don't really care.

None of it makes any logical sense or fit the existing lore, so it should probably have to be placed in some kind of mod if someone actually wants to implement it.

**Comment by RedMisao** [comment]
Second sounds somewhat similar to the broken cyborg start from the old lore, but updated and with a more engaging mechanic
Third definitely sounds like a challenge, although it brings the questions of "why can't Rubik remove it" and "why can you recharge it but not remove or deactivate it"

**Comment by Zireael07** [comment]
The second one seems like already existing broken cyborg.

Implanted/collar bomb is a common theme in cyberpunk

**Comment by failboat78** [comment]
Something similar to the bomb collar is already in the game - the FoodPerson mask. Just missing the explodey part when it runs out.
