### ISSUE TITLE
Game do not load

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#76223]
### Describe the bug

The game fails to open with next error message
![image](https://github.com/user-attachments/assets/504c46b5-7737-4dee-a1db-93b04a56ed68)
`Well apparently avif support isn't compiled in with our sdl deps by default so I think we're gonna have to (use regular formats)` - Harakka

### Attach save file

N/A

### Steps to reproduce

open the game at the most recent build

### Expected behavior

N/A

### Versions and configuration

Can't open the save file

### Additional context

Caused by #75998, so @db48x to the court! (that's a joke, you also know it, but i need to pin something to prevent army of issues)

**Comment by CoroNaut** [comment]
This better be one heck of a png lol.

**Comment by gitelitko** [comment]
> This better be one heck of a png lol.

https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/gfx/cdda.avif

**Comment by db48x** [comment]
You can view it directly of course, but it’s fairly understated. It’s clearly inspired by the ASCII art logo on the main menu. Ultimately I think someone should create some art specifically for the loading screen. Something exciting and bold. I‌ know my limitations though, so I‌ didn't try.
