### ISSUE TITLE
Can't pulp acid-filled corpses 

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76236]
### Describe the bug

Attempting to pulp a corpse of acid-filled creatures results in "The corpse moved before you could finish smashing it!".

### Attach save file

[Nairn-trimmed.tar.gz](https://github.com/user-attachments/files/16907975/Nairn-trimmed.tar.gz)

### Steps to reproduce

1. Kill an acid-filled creature
2. Try to pulp it

"The corpse moved before you could finish smashing it!"

### Expected behavior

Corpse is pulped thoroughly

### Screenshots

![image](https://github.com/user-attachments/assets/0c48edb0-21b7-4e38-9e37-550344ea7b0d)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-05-0451 5d5ef55 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by PatrikLundell** [comment]
/Confirmed

It can be noted that you typically want to dismember acid corpses (from the butchering menu, after moving the corpse away from the pool of acid using AIM), as you don't want to be splashed with acid (the exception is when you're wearing acid proof gear).
Regardless, you used to be able to smash them, and I know of no reason why you shouldn't still be able to do so.

Note that you're still able to smash a zombie cow corpse (spawned and debug killed a zombie cow to test it).
