### ISSUE TITLE
Problems calculating the length of an item

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#76239]
### Describe the bug

According to the documentation:
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a13be36d01648cbbaa206f79de5b58ed6ae62fc/doc/JSON_INFO.md?plain=1#L3433

My assumption: If this parameter is not specified, it is calculated automatically.

A light Kevlar jumpsuit will be used as a test prototype.
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a13be36d01648cbbaa206f79de5b58ed6ae62fc/data/json/items/armor/bespoke_armor/custom_bodysuits.json#L141

Unmodified jumpsuit:
![1](https://github.com/user-attachments/assets/a5578313-3a98-4000-a8ff-9b973a5123f8)

Pay attention. The length of the suit is not specified.

Let's change its volume to 500 liters. 
```
    "volume": "500 L",
```
![2](https://github.com/user-attachments/assets/1f89c7a4-8ccb-4bb7-9e4e-f548352545b3)

Now let's add a built-in battery:
```
      { "pocket_type": "MAGAZINE", "rigid": true, "ammo_restriction": { "battery": 64 } }
```
![3](https://github.com/user-attachments/assets/a71dfa9d-e568-458c-8232-af9efbc4d724)

And now the length of the object appears. 1 centimeter. But the cube root of 500 equals 79 centimeters.

1. Should the length for clothing/armor be displayed if it is not set in json?
2. Why does it show up unexpectedly?
3. And why is it equal to 1 centimeter?

### Attach save file

n/a

### Steps to reproduce

1. Make these changes.
2. Reload the game and see the result.

In the recipe menu, the length does not appear. Use the debug menu.

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-09-06-0627 1a13be3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

You don't have to change the volume. With any volume I got 1 centimeter.

**Comment by PatrikLundell** [comment]
The assumption of dimensions is a sphere, not a cube, when unspecified (at least that used to be the case). However, 1 cm is still wrong.

**Comment by kevingranade** [comment]
IIRC this is because it has the "soft" tag so it should never be "too long" to fit in a container because you can just squish it.
I'm not clear why you added the battery compartment, but that's also valid until you add a battery. Because a battery compartment isn't necessarily a full enclosure for a battery. It could just be a terminal where you attach your battery.

Does?
It still have a length of one centimeter if you actually install a sizable battery in it?

**Comment by RenechCDDA** [comment]
Yes this is just hiding the value when it's irrelevant, because the item is soft. Maximum length does not apply to it.

itype_battery(the free-floating electricity that you added) is not soft, so adding battery storage to it causes it to calculate the maximum length through the contained, non-soft battery.

**Comment by IdleSol** [comment]
I modified the battery compartment so that the suit uses a separate battery. If the suit is without a battery, the length is not specified. If the suit has a battery, the length of the battery is used.
```
    "ammo": "battery",
...
      {
        "pocket_type": "MAGAZINE_WELL",
        "rigid": true,
        "flag_restriction": [ "BATTERY_MEDIUM" ],
        "default_magazine": "medium_battery_cell"
      }
```
The costume has a medium battery with a length of 65 cm. "id": "medium_battery_cell",
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a13be36d01648cbbaa206f79de5b58ed6ae62fc/data/json/items/battery.json#L80

![4](https://github.com/user-attachments/assets/8540fcac-99a0-44a5-bcbd-3077fdeee2f7)
```
      {
        "pocket_type": "MAGAZINE_WELL",
        "rigid": true,
        "flag_restriction": [ "BATTERY_HEAVY" ],
        "default_magazine": "heavy_battery_cell"
      }
```
small tool battery
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a13be36d01648cbbaa206f79de5b58ed6ae62fc/data/json/items/battery.json#L102
![5](https://github.com/user-attachments/assets/3b59464e-693c-4e35-9ecb-2449458325df)




>I'm not clear why you added the battery compartment

The idea was to cross between a Kevlar jumpsuit and an advanced nomad suit. A climate-controlled suit, but powered by a UPS instead of bionics. As well as adding a 20-minute battery to the jumpsuit. So that you can remove the backpack from the UPS and keep the electronics running.

**Comment by IdleSol** [comment]
If the suit has a built-in battery, for some reason it counts as 1cm. Is that the minimum possible length? If this doesn't count as an error, I'll close the topic?

**Comment by kevingranade** [comment]
Aha I understand, this is just the situation you encountered while modding.

This in particular is working as expected:
> If the suit is without a battery, the length is not specified. If the suit has a battery, the length of the battery is used.

If you want it to act as if there is a rigid battery compartment,  you just need to add the longest dimension manually.

Yes 1cm is the smallest length for that measurement, as RenechCDDA says it's inheriting the length of the longest contained item,  but that's only 1cm.

**Comment by IdleSol** [comment]
Or add a rigid material (steel) to the material list. Then it will take the volume and calculate the length.
![7](https://github.com/user-attachments/assets/45a54bad-2b8a-42d7-9497-e451bf16d10a)

I'll close the thread since it's not a bug. Thanks for the replies.
