### ISSUE TITLE
New (?) problems with windows. Highlighting two items at the same time

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#76241]
### Describe the bug

Tested on a menu of spawning items and vehicles.

![pict 1](https://github.com/user-attachments/assets/dcba7aef-8e77-47cf-a215-5b28c978ddfd)

Beginning at 30 seconds.
https://github.com/user-attachments/assets/33d1bc98-2d66-4aff-b7e6-ebec2cb5dbeb

Additionally, at the end of the video, you can see the resizing of the windows. (the list window becomes narrower and the description window becomes wider)

### Attach save file

n/a

### Steps to reproduce

1. open the spawn menu
2. press `/`
3. type text (I used `kevlar j`)
4. do not press `enter`
5. use the `up` and `down` arrows on the keyboard (x a lot)
6. wait for the bug to appear
7. press `enter` and compare the highlighted lines to what spawn suggests
8. press `esc`
9. compare the size of the windows before and after

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-09-06-0627 1a13be3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CoroNaut** [comment]
I was suffering doing testing yesterday from this. i couldn't make heads or tails of what i was spawning, so i just accumulated a pile of crap i never wanted to spawn. XD

**Comment by Brambor** [comment]
This will be related to / caused by:
 - #76033

**Comment by l29ah** [comment]
/confirmed
also occurs on curses

**Comment by IdleSol** [comment]
The search bar has been changed. That's why it's not reproducing now.
