### ISSUE TITLE
missing mandatory JSON value does not throw an error

### ISSUE THREAD

**Issue by HadeanLake** [CleverRaven/Cataclysm-DDA#76246]
### Describe the bug

`to_ter` member is mandatory for terrain to furniture migration:
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a13be36d01648cbbaa206f79de5b58ed6ae62fc/src/savegame_json.cpp#L4582-L4587

but is missing from
https://github.com/CleverRaven/Cataclysm-DDA/blob/1a13be36d01648cbbaa206f79de5b58ed6ae62fc/data/json/obsoletion_and_migration_0.I/obsolete_furniture.json#L91-L95

And this does not cause an error.

### Attach save file

N/A

### Steps to reproduce

Start new game

### Expected behavior

There should be debug message or something when game loads `ter_furn_migrations`

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: d0b941b0-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by mqrause** [comment]
Looks like the issue is the `true` passed to mandatory. That causes it to ignore errors.

**Comment by HadeanLake** [comment]
Another instance of always assumed to be loaded json:
https://github.com/CleverRaven/Cataclysm-DDA/blob/e398be14514639f1e6aa512d8fd39c908b347eed/src/veh_type.cpp#L1729-L1735
No error if I remove this line:
https://github.com/CleverRaven/Cataclysm-DDA/blob/e398be14514639f1e6aa512d8fd39c908b347eed/data/json/obsoletion_and_migration_0.I/migrated_vehicleparts.json#L24
