### ISSUE TITLE
Have More Than 1 Loading Screen

### ISSUE THREAD

**Issue by Holli-Git** [CleverRaven/Cataclysm-DDA#76268]
### Is your feature request related to a problem? Please describe.

Having more than 1 loading screen would be nice, as it can showcase more art and styles.

### Solution you would like.

Having more than 1 loading screen, and randomly picking them on load.

**Comment by gettingusedto** [comment]
mod-specific loading screen would be nice, though im not sure how much of an ask that it.

**Comment by Srcwya** [comment]
YEAAAAAAAH!
