### ISSUE TITLE
Drive by wire controls are only accessible by removing them from solar car

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76293]
### Describe the bug

There is absolutely no way to obtain drive by wire controls other than taking it off the solar car, a very rare spawn.
[drive by wire controls hitchhikers guide](https://cdda-guide.nornagon.net/vehicle_part/drive_by_wire_controls)

### Attach save file

N/A

### Steps to reproduce

1. view drive by wire controls on hitchhikers guide
2. realize its only accessible via removing it from solar car

### Expected behavior

There should at least be a recipe for the drive by wire controls, and perhaps some spawns in some car-lovers garages or a race track or something.

### Screenshots

![image](https://github.com/user-attachments/assets/c7fa4b4e-e4a0-4345-bd97-aec83a9a6910)
![image](https://github.com/user-attachments/assets/36f68fc6-9f25-4ad2-8a1c-0631d70af906)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-07-0110 e398be1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Made this a bug report because it seems like an oversight rather than a feature to be added.

**Comment by osuphobia** [comment]
https://cdda-guide.nornagon.net/item/drive_by_wire_controls
Nope, there is a recipe for it.
