### ISSUE TITLE
Unable to store books with e-ink reader

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#76322]
### Describe the bug

There is no way to store books with my e-ink tablet.

### Attach save file

N/A

### Steps to reproduce

1. Activate e-ink reader
2. Store books option no longer available. 

### Expected behavior

I expect that the e-ink tablet is able to store books

### Screenshots

![image](https://github.com/user-attachments/assets/768375ba-cb28-4416-8627-3f38ca42f3e7)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: cachyos; Description: CachyOS; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-10-0532 43dd78a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Alternative Map Key [alt_map_key]
]

**Comment by GuardianDll** [comment]
E-ink readers do not have cameras, it is expected to not be able to scan books
