### ISSUE TITLE
map::process_fields_in_submap is probably bugged

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#76336]
### Describe the bug

The operation process_fields_in_submap defined in map.h is defined using an untyped tritype and is called from a single location in map_field.cpp, This call is made from map::process_fields, where the untyped tripoint is created from x, y, z, which are iterators over the submaps of the calling map, which implies the proper type should be tripoint_bub_sm.
However, the first thing done in map::process_fields_in_submap is to convert the untyped tripoint to be an OMT reference, and then cast it to tripoint_abs_omt, before being sent to overmap_buffer.ter to get the terrain of the overmap tile.
As far as I can see, a bubble submap coordinate cannot be converted into an OMT coordinate, as it's may not be OMT aligned. Instead of feeding "submap" to "sm_to_omt_copy" the code should feed it "abs_sub.raw() + submap" in order to actually convert an absolute submap location to the OMT conversion and ultimately to the "overmap_buffer.ter" call.

Edit:
It's even worse, as the operation also calls map::on_field_modified with the untyped parameter being fed with submap coordinates (in three places), while the other uses of that operation feeds it bubble coordinates and its implementation implies usage of bubble coordinates, which should cause the wrong location's caches to be marked as dirty.

### Attach save file

N/A. It's the source code referenced.

### Steps to reproduce

Examine the code as per the description.

### Expected behavior

I don't know what the overmap terrain id is used for, but it's probably not extremely important, given that serious issues aren't reported.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 0.G-12001-gab062c5e8b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
Only the game version is relevant. It's dirty because I'm working on typification, which is where I encountered this.

**Comment by SurFlurer** [comment]
> As far as I can see, a bubble submap coordinate cannot be converted into an OMT coordinate, as it's may not be OMT aligned.

I believe you are right. 

> It's even worse, as the operation also calls map::on_field_modified with the untyped parameter being fed with submap coordinates (in three places),

The point type is clearly wrong, but I guess the actual value is right since it tries to convert to a bub_ms coordinate by `map_tile.pos() + sm_offset, submap.z`?
