### ISSUE TITLE
Using toggle fast travel to travel to a destination you cannot reach puts the UI in a strange state

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76351]
### Describe the bug

If you try to fast travel to an area where you get the message "You cannot reach that destination", the map view stays up when it finishes its job. Then you get into a strange state where you can move your character around in the world, but the map screen is up.

While in this strange state, you could actually move your character far across many overmap tiles and the map updates like normal.

The only way I found to get out of this strange state is to re-open map view with its keybind, and then closing map view.

### Attach save file

[TESTINGTWO-trimmed.tar.gz](https://github.com/user-attachments/files/16960952/TESTINGTWO-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Enable 'toggle fast travel' on the map view
3. There is a note on a map tile just left of the character, fast travel to that point from map view
4. fast travel finishes, but because it cannot reach the destination, it stays in map mode despite giving control back to the character.

### Expected behavior

Map view should close when fast travel can't deliver you to your destination.

### Screenshots

![image](https://github.com/user-attachments/assets/2abf0fd7-794b-41d9-abcd-67f863032825)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-10-0339 c73e4c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ShnitzelX2** [comment]
Thanks, I'll fix this soon.
