### ISSUE TITLE
Linux binaries fail to compile in GitHub releases after #76266

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#76357]
### Describe the bug

Linux Binaries are not generating after #76266

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

I expect all standard binaries to generate after a code update.

Perhaps it would be a good idea for GitHub to run a test to see how many files are generated after a commit.

### Screenshots

![image](https://github.com/user-attachments/assets/b6fe2b59-9074-4ab4-b952-7560df2908ca)

### Versions and configuration

N/A

**Comment by harakka** [comment]
> Perhaps it would be a good idea for GitHub to run a test to see how many files are generated after a commit.

And to do what with that information?

**Comment by ZweiFedern** [comment]
There is a Problem at the Build - GCC 9, Curses, LTO -  get an Error, and so the Build for Linux (ubuntu) get cancelled.
The Later Builds for Linux were all cancelled. I have seen in the newest Build Progress, that there is an Error.
(Error: src/mtype.h:320:19: error: declaration of ‘baby_type mtype::baby_type’ changes meaning of ‘baby_type’ [-fpermissive])

**Comment by harakka** [comment]
Yes, #76363 is already up to fix this particular instance of a particular build breaking.

**Comment by redcrate** [comment]
> > Perhaps it would be a good idea for GitHub to run a test to see how many files are generated after a commit.
> 
> And to do what with that information? It is considered acceptable for experimental that a particular build breaks sometimes in experimental releases, if you want to find the last complete release it is linked on the game's website.

I am aware that in experimental that things don't always work. However, as part of the development process, the information could be used to notify the committer that their update isn't working properly and would just be another CI/CD check. The possibilities are endless...

**Comment by kevingranade** [comment]
If you have a proposal for a workable mechanism to close this feedback loop, feel free to recommend it,  but "notify people somehow" isn't a meaningful suggestion.
