### ISSUE TITLE
New loading screen does not display loading progress

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#76359]
### Describe the bug

![image](https://github.com/user-attachments/assets/1d5c49d0-0719-4024-b60f-4ee98e0c597f)

### Attach save file

N/A loading screen

### Steps to reproduce

Load game

### Expected behavior

This should be in the window and visible. (image made by replacing the loading screen image)

![loading progress](https://github.com/user-attachments/assets/fd8c6d03-cacd-4e12-b65f-9fec25048cb1)

### Versions and configuration

master dd272dd1852db13f7f4b11af861a06dccf6c8d34

**Comment by GuardianDll** [comment]
#76249
