### ISSUE TITLE
Repairing with portable soldering iron is frustrating and broken

### ISSUE THREAD

**Issue by TheLyca0n** [CleverRaven/Cataclysm-DDA#76364]
### Describe the bug

Essentially in the latest build tried to repair some elbow guards and a motorcycle helmet and it cost me 15 FULL DISPOSABLE BATTERIES with constant battery changes between every repair tick. Potentially bad luck due to low repair skill but reloaded a save and it still consumed half that amount. 

As a comparison that is enough AA batteries to power a pair of night vision goggles for 2 weeks used to have a soldering iron solder for 5 minutes and melt 3 pieces of plastic

### Attach save file

N/A

### Steps to reproduce

- Start game 
- Attempt to repair a semi/badly damaged item
- Count the batteries consumed
- See results

### Expected behavior

Potentially having the portable soldering iron use a 18650 battery (medium tool battery) would make this less frustrating and true to reality ?, I assume it's still using the old framework that has each tick of success dependent on between 30-50 charges while currently in the existing for some reason you can only put a single AA battery into most household objects that have disposable batteries. There are also butane powered irons like what my father used to use but that should probably be a side grade rather than a replacement

I can see that the soldering practice and other recipes are being adjusted to accommodate for their low capacity but this feels like a mistake as a hours worth of soldering would leave my lithium Ion powered iron nearly dead I doubt a AA of 15 charges or 12v powered one could get three hours. Its just added workload to recipe changes for little benefit

### Versions and configuration

Latest experimental

**Comment by failboat78** [comment]
Why is this unrealistic? Devices that use heat are quite power hungry. Other devices like modern electronics are very power efficient in comparison.

You can just plug the soldering iron in and not have to worry about batteries. Or install a mod to use larger ones.

**Comment by CoroNaut** [comment]
Portable soldering iron uses light batteries with 16 charge x 15 uses = 240 total battery used. If you were to upgrade to the heavy battery mod and put in a  'small tool battery', it would hold 259 charge, 

I would say that using a soldering iron to fix elbow guards and motorcycle helmet is quite challenging. I haven't done it myself, but repairing a plastic item with a soldering iron just sounds like trouble. This complicated task combined with the large power requirement kind of puts this in the right ball park in my opinion. Light batteries are extremely abundant anyways. Once you get a corded soldering iron, I'm sure you'll be immediately plugging it into your car with a battery of 3,000, and engine to recharge it.

**Comment by TheLyca0n** [comment]
> Why is this unrealistic? Devices that use heat are quite power hungry. Other devices like modern electronics are very power efficient in comparison.
> 
> You can just plug the soldering iron in and not have to worry about batteries. Or install a mod to use larger ones.
> 
> You mention Volts and Amps a lot but did not mention POWER. A small soldering iron could use 100W - which will drain an AA battery very quickly indeed. Post with some real figures if you want to prove your point.
> 
> 100W is a lot more than a laptop uses - imagine powering your laptop off an AA battery?

Portable soldering irons don't have wires in current experimental. Also how common are soldering irons that run off A SINGLE AA. This is just post hoc justifying breaking a items utility and expecting the player to deal with it

You are right though why would a player fucking bother with a useless item when the standard soldering iron can be plugged in beyond it's use in the firearm repair kit recipe.

**Comment by TheLyca0n** [comment]
> Portable soldering iron uses light batteries with 16 charge x 15 uses = 240 total battery used. If you were to upgrade to the heavy battery mod and put in a 'small tool battery', it would hold 259 charge,
> 
> I would say that using a soldering iron to fix elbow guards and motorcycle helmet is quite challenging. I haven't done it myself, but repairing a plastic item with a soldering iron just sounds like trouble. This complicated task combined with the large power requirement kind of puts this in the right ball park in my opinion. Light batteries are extremely abundant anyways. Once you get a corded soldering iron, I'm sure you'll be immediately plugging it into your car with a battery of 3,000, and engine to recharge it.

You just use it like a blend between soldering dependent on the plastic....I think idk tbh I only know the theory , reminder though in the skill practicing you can use a soldering iron for 3 hours for a total of 15 charges. Should it be returned to the original consumption rate ?.

Again just such a weird discussion about the "realism" of AAs in a portable soldering iron as I'm not even aware of where you could get them outside of DIY and aliexpress and even if I could don't know of any tradesman or hobbyist that would bother with them.

https://www.youtube.com/watch?app=desktop&v=4CGc1gs9PKA

A video on how quickly you can weld plastic btw, not entirely irrelevant but bit of a side tangent

**Comment by kevingranade** [comment]
The portable soldering iron accepts a medium battery as of #76517 which brings it in line with real examples of this kind of tool (4 AA).  *Alledgedly* this would yield an hour of operating time according to associated datasheets, I haven't tested if the in-game item matches, feel free to follow up on that if you like.
