### ISSUE TITLE
Mod: No Hope - Idea

### ISSUE THREAD

**Issue by ZweiFedern** [CleverRaven/Cataclysm-DDA#76378]
### Is your feature request related to a problem? Please describe.

i like the mod and the to parts of it, all defeated dead remain dead, and the drop raid is lower.
but i think, if there is a fallout - or what ever the lore of cdda is very big and we have many explations...
why in all vehicles the tank is empty and all batteries are unloaded.

### Solution you would like.

 i have the idea, that there is a little bit in it. like 1-5%.

or i have the idea if its possible to make a selection in the world creation, that handle the "drop rate"?
![Bildschirmfoto vom 2024-09-12 11-45-13](https://github.com/user-attachments/assets/85c76ed7-f198-459b-ba87-2ef31eb6845a)
we have the part  "item spawn scaling factor", maybe we get a sub part for petrol/gasoline

**Comment by GuardianDll** [comment]
Items in no hope are reduced via eoc, which include changes by category, including `{ "spawn_rate": 0.6, "id": "fuel" },`
