### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by ZweiFedern** [CleverRaven/Cataclysm-DDA#76391]
### Is your feature request related to a problem? Please describe.

I have the idea that the scenario "middle of nowhere" get an update.

### Solution you would like.

![Bildschirmfoto vom 2024-09-12 19-16-24](https://github.com/user-attachments/assets/9c60a9b3-85ad-44f4-aa10-54c17c40e92b)

you can not select the real staring point.
maybe its possible to set it to default and in the starting locations that is deposit?
scrap yard, sewage treatment, small power substation...

and i like the locates small dump, farm supply store, small scrap yard and and most the point junkyard.
maybe its possible to incorporate this as a selectable menu item

its idea to make it more varied.

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/2473620ec6fae3fff2cf0cd4d17780c421e8ef81/data/json/scenarios.json#L1343

https://github.com/CleverRaven/Cataclysm-DDA/blob/2473620ec6fae3fff2cf0cd4d17780c421e8ef81/data/json/start_locations.json#L808-L820

all you would need to do is split single `start_location` with six locations into six `start_location` with one loc each
Not sure is it really worth it tho, but go for it
