### ISSUE TITLE
Does nobody like MRE entrees?

### ISSUE THREAD

**Issue by failboat78** [CleverRaven/Cataclysm-DDA#76397]
### Describe the bug

Many of the MRE entrees seem to have negative joy stats. Are they really that bad? 

Maybe they are - I have never tried an American MRE. I did have a veggy taco recently IRL and it was ok!

The BBQ beef one has positive stats, but many of the others have negative. Is this just someones personal opinion or are these items universally loathed?

Heating them up doesn't seem to help either.

### Attach save file

N/A

### Steps to reproduce

Procure MRE
Examine stats

### Expected behavior

Not negative joy stat?

### Screenshots

![image](https://github.com/user-attachments/assets/a6e769e1-0707-4186-ace1-67ef2fcdb3a5)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-09-10-0532 43dd78a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    Mind Over Matter [mindovermatter]
]

**Comment by failboat78** [comment]
A filtered view

![image](https://github.com/user-attachments/assets/6a98de7d-d44d-4f39-855d-387007079337)

**Comment by Aimless-dude** [comment]
1) MRE meals are made to exacting standards to ensure a soldier gets all their important nutrients in these mres, alongside minimizing possibility of food poisoning, and maximizing shelf life. The focus on these things usually means the actual taste of the food suffers. If you watch any of the many MRE review videos out there, and looking up actual soldiers talking about the meals,  you'll probably run into a lot of people saying things like "It tastes close enough to [X]" when complimenting a dish.

2) Eating a food at it's 'proper temperature' (Like hot MRE meals or cold milkshakes) doesn't directly improve the mood bonus from the food. It instead gives a secondary joy buff that's separate to the food's joy.

**Comment by CoroNaut** [comment]
Getting the bare minimum amount of food while maximizing all the needed requirements of the human body. All heated with a chemical heater (FRH), this -3 star dish is sure to keep you on your toes and in the fight!

**Comment by failboat78** [comment]
The main courses seem pretty good in comparison - only the entrees seem to be disgusting tho!?

**Comment by fairyarmadillo** [comment]
I have tried some. They are about equivalent to average-quality canned food, and should generally be about as enjoyable.

**Comment by failboat78** [comment]
> I have tried some. They are about equivalent to average-quality canned food (chef boyardee, dinty moore, etc), and should generally be about as enjoyable.

We watched you eating one on youtube! You are well-qualified to perform this serious auditing task :)

(please more cdda videos!)

**Comment by kevingranade** [comment]
As others have indicated,  there is a Very Strong Consensus that MREs are not enjoyable food and eating them does not make you particularly happy.

**Comment by failboat78** [comment]
Kevin come on you didn't even read the thread. The MRE main courses all have positive joy, but the entrees have negative. This does not line up with what you just said.

**Comment by Aimless-dude** [comment]
An 'entree' is a main course. Did you mean the sides?

**Comment by Zireael07** [comment]
@Aimless-dude Thanks for asking the question, I was super confused what was meant

**Comment by failboat78** [comment]
> @Aimless-dude Thanks for asking the question, I was super confused what was meant

Wow - I was also confused by this. It seems Americans use the term in an exceptional fashion.

https://en.wikipedia.org/wiki/Entr%C3%A9e

However the game is set in the USA and using their rations - so the naming is correct. 

This is very amusing. So now it seems MREs have awesome sides but terrible mains? But the BBQ beef is amazing?

**Comment by CoroNaut** [comment]
A quick look at the mre.json file reveals that most of MRE entrees are a little lower than the MRE sides. The sides do looks generally a little better than the entrees IMO. Of course, not by much. 

mre_entree defaults to -1 fun
mre_side defaults to 2 fun

The sides were actually added like 5 years later after the entrees were already in the game. Sides including pizza, zapplejuice, chocolate pudding. Entrees just seem like a bunch of packets of dried out nutritious meals. Generally, I don't see an issue, this seems reasonable.

https://github.com/CleverRaven/Cataclysm-DDA/blob/1925be0d2b5f937ef42c52295d39522015a2c57a/data/json/items/comestibles/mre.json#L349

**Comment by fairyarmadillo** [comment]
At this point it's a solution in search of a problem, I don't think there's anything wrong with MREs. It's also best not to carry on discussions in closed issues as nobody is going to see them.
