### ISSUE TITLE
Properly hint text and improve font rendering.

### ISSUE THREAD

**Issue by CLIDragon** [CleverRaven/Cataclysm-DDA#76420]
### Is your feature request related to a problem? Please describe.

I think this screenshot makes the problem pretty clear. We are unable to detect the actual cap height of the text, leading to text being off centre. 
![image](https://github.com/user-attachments/assets/79a4c135-6db1-4abb-a97e-5354996efeaa)

Additionally, there is an extra 1px of space before and 3px of space after text (drawn in purple). This is the natural spacing embedded in the font, and it would be nice to remove it. 
![Screenshot 2024-09-14 175153](https://github.com/user-attachments/assets/165734c5-66dc-49a4-9a64-79d8f0b64547)

### Solution you would like.

Change the current font rendering stack so that we can support autodetecting the cap height for different fonts and adjusting as necessary See https://github.com/CleverRaven/Cataclysm-DDA/pull/76404#issuecomment-2350813614 for initial direction.

### Describe alternatives you have considered.

Hand adjusting text in all user-visible UIs. Unfortunately, this breaks if the user changes the font, the font size, the font height, the font width, the font rendering mode, etc. 

### Additional context

Naming this issue was hard. The scope is strange, and I feel like the current label isn't very clear about what the actual goal is. I certainly didn't start this with the goal of rewriting the font renderer, but I guess that's what I am doing now.

**Comment by db48x** [comment]
Luckily we don’t have to completely rewrite the whole renderer, we can just swap over to using Freetype. ImGui even [provides instructions](https://github.com/ocornut/imgui/tree/master/misc/freetype), we just have to get around to it.

See also #73728, and #73120.

**Comment by CLIDragon** [comment]
I tried following the provided link to include ImGui, but build fails with the following error:
```
ImGui-lib-vcpkg-static-Release-x64.lib(imgui_draw.obj) : error LNK2019: unresolved external symbol "struct ImFontBuilderIO const * __cdecl ImGuiFreeType::GetBuilderForFreeType(void)" (?GetBuilderForFreeType@ImGuiFreeType@@YAPEBUImFontBuilderIO@@XZ) referenced in function "public: bool __cdecl ImFontAtlas::Build(void)" (?Build@ImFontAtlas@@QEAA_NXZ)
```

Which is strange given that building imgui by itself succeeds.

**Comment by whirm** [comment]
Is this issue (not computing the right height) also causing the wrong vertical dimensions for pop-up windows, cropping content?

This is on Wayland (Sway) on 2024-09-12-1816 build.

![2024-09-15T08:22:48,887212788+02:00](https://github.com/user-attachments/assets/0d00f9be-ebba-4063-873a-c80228d4779d)
![2024-09-15T08:29:24,672152633+02:00](https://github.com/user-attachments/assets/008dff12-7be3-4074-b5a0-9be60182a1a1)

**Comment by db48x** [comment]
No, that was #75698

**Comment by db48x** [comment]
![Screenshot from 2024-09-18 10-27-55](https://github.com/user-attachments/assets/8e3da50d-676f-42b3-9693-7487d62f8fab)

Ignore the window on the left; that’s just for testing.

**Comment by db48x** [comment]
![Screenshot from 2024-09-18 10-37-09](https://github.com/user-attachments/assets/94e13166-ce80-459b-b56d-ae0060b74dc6)
