### ISSUE TITLE
Consuming water from a pond results as consuming a "null"

### ISSUE THREAD

**Issue by MH10295** [CleverRaven/Cataclysm-DDA#76425]
### Describe the bug

1. Consuming water from a source of water results in consuming a null. 

### Attach save file

[Vyartas-trimmed.tar.gz](https://github.com/user-attachments/files/17002215/Vyartas-trimmed.tar.gz)

### Steps to reproduce

1. Find a pond, river, or lake.
2. "e" to interact with water tile.
3. Select "consume it".

### Expected behavior

Expected water to be consumed.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G990U2; Release: 14; Incremental: G990U2SQS7FXA2; 
- Game Version: cdda-experimental-2024-09-14-0515 b8b5c5c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by GuardianDll** [comment]
![image](https://github.com/user-attachments/assets/6ad0f187-a0d6-4b98-95c0-aa43f67c86e5)

**Comment by BaumgeistOne** [comment]
Is this the same problem as in #76398 ?

**Comment by MH10295** [comment]
Probably, it seems you can consume fine from containers, it's just consuming from a tile or piece of furniture that doesn't work.
