### ISSUE TITLE
Tetanus does not show up in the character effects panel

### ISSUE THREAD

**Issue by WJohn** [CleverRaven/Cataclysm-DDA#7642]
Self explanatory, could not tell why I was spazzing out and ended up dying due to immense amounts of built up pain making me suck in combat. It should probably show up like the common cold or the flu or other problems in the character effects screen.

EDIT by Kevin: Suggested fix is occasional warning messages when you cut yourself warning about Tetanus.
##

**Comment by Night-Pryanik** [comment]
Various messages about muscle spasms and explicit explanation while using the blood analysis bionic - I think this should be closed.
