### ISSUE TITLE
Launch with fullscreen mode

### ISSUE THREAD

**Issue by I-dont-know-why** [CleverRaven/Cataclysm-DDA#76436]
### Is your feature request related to a problem? Please describe.

I found it hard to switch to fullscreen mode at the main menu.

### Solution you would like.

I think there should be an option to launch the game in fullcreen mode.

### Describe alternatives you have considered.

Add an option to launch the game in fullcreen mode.

**Comment by RenechCDDA** [comment]
Why did you find it difficult to switch to fullscreen mode?

**Comment by I-dont-know-why** [comment]
> Why did you find it difficult to switch to fullscreen mode?

I'm using version b35342f

**Comment by I-dont-know-why** [comment]
> Why did you find it difficult to switch to fullscreen mode?
 I add keybinding for toggle fullscreen mode, but it dont work when I press that key at the main menu.

**Comment by CoroNaut** [comment]
I use the "Windowed borderless" fullscreen option and scale my terminal width/height to my exact screen size. I'm not sure if this will work for you? This puts the game effectively in full screen mode.

**Comment by I-dont-know-why** [comment]
> I use the "Windowed borderless" fullscreen option and scale my terminal width/height to my exact screen size. I'm not sure if this will work for you? This puts the game effectively in full screen mode.

It does work.
I used "maximized" fullscreen option before and found it hard to toogle fullcreen mode at the main menu.

**Comment by I-dont-know-why** [comment]
My bad. I didn't see the fullscreen option in "Graphical Display Options".

I'm using the build 2024-09-14-1609 .I think this question reflects some new issues.
1. Keybind for toggle fullscreen mode don't work properly at the main menu.
2. The Chinese translation is misleading, "Graphical Display Options" is translated into"渲染调整" which means "Rendering Adjustments".

**Comment by I-dont-know-why** [comment]
I don't know what to do next. Should I close this issue and open new issue with the problems I found in my last comment?

**Comment by CoroNaut** [comment]
If your full screen issue is solved, then it is probably best to close this issue. If you want to create a new issue about a translation error, that would be best. That's how I would do it anyways.
