### ISSUE TITLE
Recent battery nerf broke electronics practice recipes (and possibly others)

### ISSUE THREAD

**Issue by CrazySwayze** [CleverRaven/Cataclysm-DDA#76446]
### Describe the bug

"Semiconductor Circuits" and "Integrated Circuits" (electronics practice recipes) require 50 and 100 multimeter charges to craft respectively. Because of the recent battery nerf, light batteries only hold 16 charges. Additionally, you cannot upgrade the multimeter battery to hold more than 16 charges. The only workaround to this issue is to collect 4/8 multimeters and 4/8 light batteries for each cycle of the practice recipe. I doubt this is intended balance.

I strongly suspect that there are a large number of other practice recipes that got messed up as well when batteries were nerfed.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![image](https://github.com/user-attachments/assets/99c3484c-323f-4a6f-a31a-4227eb86fc39)
![image](https://github.com/user-attachments/assets/8e24aa37-815b-4e05-9aa1-31e147021099)

### Versions and configuration

0221f6e

### Additional context

N/A

**Comment by CoroNaut** [comment]
The multi meter can be upgraded with battery mods, the device to be upgraded can't have a battery inside for you to be able to upgrade it. 

I would however say that multi meters are definitely not power hungry at all. To use 100 charge (7 light batteries) doesn't really make sense for one training session over the course of 1hr 8 minutes... you can generally use a multi meter on projects for months if not longer without needing to change batteries.

![image](https://github.com/user-attachments/assets/6804397f-f4dc-4d78-94c6-9cb2554ed3f4)
- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-12-1206 6341fd2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by CrazySwayze** [comment]
> The multi meter can be upgraded with battery mods, the device to be upgraded can't have a battery inside for you to be able to upgrade it.

Ahhhh, thank you. That fixes the issue I was having. 

Agreed, though, the balance on this is off. I'm guessing it probably hasn't been touched since the battery nerf.

**Comment by Maleclypse** [comment]
#76544 looks like this fixed it?
