### ISSUE TITLE
Strange light apparently from nowhere generated in world.

### ISSUE THREAD

**Issue by redcrate** [CleverRaven/Cataclysm-DDA#76445]
### Describe the bug

There is what appears to be a headlight of some kind generated inside a planter somehow. The other interesting thing about the light is the fact that it isn't visible all the time, like normal headlights are, but only when you're very close. 

### Attach save file

[Fompton-trimmed.tar.gz](https://github.com/user-attachments/files/17004322/Fompton-trimmed.tar.gz)

### Steps to reproduce

1. Load save, move character one tile to the west.
2.  Notice the strange light by the planter...

### Expected behavior

I expect there to be no strange lights appearing in the game, except for the strange lights that are supposed to be there.

### Screenshots

![Screenshot_2024-09-14_20-53-36-1-1](https://github.com/user-attachments/assets/8d94299e-d998-4dd3-b442-d0ded0332a6c)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: cachyos; Description: CachyOS; Release: rolling; Codename: n/a; 
- Game Version: c6ba9a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by CoroNaut** [comment]
The light only 'pops in' because the car with the headlights on is out of the reality bubble until you step left one tile.
![image](https://github.com/user-attachments/assets/f65932e1-9358-4698-bd13-daf790a4a283)

**Comment by redcrate** [comment]
> The light only 'pops in' because the car with the headlights on is out of the reality bubble until you step left one tile. !

Thanks! whoops...

**Comment by redcrate** [comment]
PEBKAC error
