### ISSUE TITLE
`Request review` always* fails

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#76440]
### Describe the bug

Request review either concludes that nobody is to be pinged and then successfully ends. Or it finds somebody to ping and then fails instead of requesting the review.

![image](https://github.com/user-attachments/assets/e7f274af-1869-49df-9407-00a8daecfb5e)

from:
 - #76433

### Attach save file

N/A

### Steps to reproduce

I am not sure. Make a PR with changes to a file somebody is subscribed to? Make it Qrox to be sure it fails.

### Expected behavior

I would either disable the test or fix it. Currently, it gives no value. It never requests a review which is the whole point.

### Versions and configuration

N/A

### Additional context

Search "request review" on Discord for more insight.

**Comment by Brambor** [comment]
- Requesting @ KorGgenT in #76617 didn't fail.

**Comment by RenechCDDA** [comment]
@Qrox Any chance you could lend us your wisdom?

Harakka seemed to think it was an API change and also identified that function so that's what I'm going with 🤷 

![image](https://github.com/user-attachments/assets/72308ded-1071-4e6b-a7cb-a7f78265031c)

**Comment by Qrox** [comment]
If it is failing inside `is_collaborator` and throwing an error, then my best guess is that the returned error status when a user is not a collaborator is somehow not 404, which will trigger [this line](https://github.com/Qrox/auto-request-review/blob/481e6cd2f5d57b6e914d81ca731211384a76798f/src/github.js#L118). I haven't tested though.

**Comment by Procyonae** [comment]
https://github.com/Qrox/auto-request-review/pull/1 should hopefully fix it (we'll need to update https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/workflows/request-review.yml#L23 to the new commit or just point to the branch too)
