### ISSUE TITLE
Bear trap "disappear" after trapped victim is killed. 

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#76454]
### Describe the bug

Related to https://github.com/CleverRaven/Cataclysm-DDA/pull/76312 ?

### Attach save file

[Zakhadia_BigCity-trimmed.tar.gz](https://github.com/user-attachments/files/17005593/Zakhadia_BigCity-trimmed.tar.gz)

### Steps to reproduce

Place beartrap, get something to stand  on beartrap, see text stating that it's stuck in trap, and kill said creature, but alas no return on trap.

### Expected behavior

To be able to retrieve the trap.

### Screenshots

![image](https://github.com/user-attachments/assets/f4d4e383-e061-4fdf-b2b4-8dbf5034c0e5)
![image](https://github.com/user-attachments/assets/1aa9bbc3-b470-4ca9-a745-548e9fadfc7b)
![image](https://github.com/user-attachments/assets/5a6f06d4-c604-4b0a-a44f-cd09d7f60b97)

### Versions and configuration

- OS: Windows
    - OS Version: 7
- Game Version: 1925be0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by MikasaTanikawa** [comment]
Also bear trap disappears if you throw item (like rock) and trigger it.

**Comment by Night-Pryanik** [comment]
That's strange. Tested right now. Set a trap. Lured zombie to the trap. The trap has correctly spawned under the zombie.
![изображение](https://github.com/user-attachments/assets/ea4e8d62-b4c1-441e-85d0-69cc390ad087)
