### ISSUE TITLE
Multiple Loading Screens On One Load

### ISSUE THREAD

**Issue by Holli-Git** [CleverRaven/Cataclysm-DDA#76468]
### Describe the bug

When you load into an existing character with a multiple loading screen mod, it can jump to a different loading screen when it goes from loading the world to the character.

### Attach save file

N/A

### Steps to reproduce

1. Have the mod active
2. Load into an existing world 
3. Notice how the screen can quickly change 

### Expected behavior

I expect it to have the same loading screen throughout

### Screenshots

![image](https://github.com/user-attachments/assets/0f08124b-0a69-4de7-960d-56c63afc1d2e)
![image](https://github.com/user-attachments/assets/ca237e6d-3063-4fe2-b2ec-cba739f929ee)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: cdda-experimental-2024-09-14-1609 b35342f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Loading Screens [loading_screens]
]

### Additional context

[loading_screens.zip](https://github.com/user-attachments/files/17007678/loading_screens.zip)
Here's the mod I used

**Comment by RenechCDDA** [comment]
I wasn't able to reproduce. I loaded multiple times just in case it was chancey, but nothing.

https://github.com/user-attachments/assets/7fe97c45-f8c1-4086-9399-302ae074bffb

**Comment by RenechCDDA** [comment]
Oops I found it by reviewing your message on discord - looks like there's still a stray gLUI reset when loading an **existing** character. Let me see what I can do about that.
