### ISSUE TITLE
Sky Island climate control upgrade broken

### ISSUE THREAD

**Issue by CrazySwayze** [CleverRaven/Cataclysm-DDA#76504]
### Describe the bug

The climate control upgrade for the bunker in the sky island mod doesn't set the interior temperature of the bunker to 70 deg f.

### Attach save file

N/A

### Steps to reproduce

1. Start a new sky islands game
2. Use debug to upgrade bunker with climate control

### Expected behavior

I expected that the temperature in the bunker would be 70 deg f after upgrading it with climate control per commit [e218158](https://github.com/CleverRaven/Cataclysm-DDA/commit/e2181589a94dbca92a590a966c7c2e7dcbe9462d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-17-1552 aae02aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks],
    Sky Island [skyisland]
]

**Comment by Standing-Storm** [comment]
Cannot reproduce:

![Untitled2](https://github.com/user-attachments/assets/71317f29-6b66-4aee-8f74-d7f34387dc13)
![Untitled3](https://github.com/user-attachments/assets/f41c1b57-33bb-4f31-b55a-fe8de6660422)

**Comment by CrazySwayze** [comment]
Thanks for checking - strange. I'll attempt to reproduce it on my own as well.

**Comment by CrazySwayze** [comment]
Ok, I was able to reproduce the bug. I made a copy of the game directory, made a new world with the same mods + load order, and then debugged through the first 20 quests to unlock tier 3 and gave myself the Lukewarm Sphere. It's still 21 deg in the bunker (started in winter this time).

In terms of stuff that could be causing the issue, I'm running MoM, Xedra, Bombastic Perks, and bumped Sky Island to the end of the load order. And am running 30 day seasons. That's everything funky about my setup.

What would you like me to attach/include to help? Sorry, I'm pretty new around here and not 100% sure what I'm doing yet

**Comment by Standing-Storm** [comment]
You say you gave yourself the sphere--did you debug in the item, or build the recipe?

**Comment by CrazySwayze** [comment]
> You say you gave yourself the sphere--did you debug in the item, or build the recipe?
> 

I just kept accepting each quest sequentially and then debug spawning the item to complete it (including the Lukewarm Sphere). I ranked up by accepting a mission and teleporting to the end 10x for each tier as well (idk if there's a quicker way to do this).

I have attached the save file. Thanks for offering to take a look!

[Medicine Lodge.zip](https://github.com/user-attachments/files/17047767/Medicine.Lodge.zip)

**Comment by CrazySwayze** [comment]
I just reproduced the bug again under different conditions! I started a new game yesterday (totally clean install of the experimental, no launcher this time) without Xedra Evolved and with the default mod load order. I used the debug process outlined above to catch myself up to where I was before, starting in spring of year 2. This save file starts right before I gave myself the Lukewarm Sphere (sorry about the world name, I didn't expect to encounter the bug again/share this world).

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-17-1552 aae02aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks]
]

[I apologize in advance for the name of this world.zip](https://github.com/user-attachments/files/17047988/I.apologize.in.advance.for.the.name.of.this.world.zip)

**Comment by CrazySwayze** [comment]
Removing Mind over Matter doesn't fix the bug. It's 35mb for some reason so I can't upload this particular save file but you get the idea.

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-17-1552 aae02aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks]
]

**Comment by CrazySwayze** [comment]
Removed No Hope as well - still encountering the issue. At this point it has to be Bombastic Perks or something about my game settings.

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-17-1552 aae02aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Bombastic Perks [bombastic_perks]
]

**Comment by CrazySwayze** [comment]
Ok, I removed Bombastic Perks - the game is vanilla now - and the issue is still going on. I'll attach the minimized save archive from my game (sorry about uploading the entire world folder earlier, still learning).

[No Bombastic Perks-trimmed.tar.gz](https://github.com/user-attachments/files/17049263/No.Bombastic.Perks-trimmed.tar.gz)

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-17-1552 aae02aa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland]
]

I'm gonna keep testing. You were able to get climate control working on experimental vanilla, right? Because at this point it looks like we're running very similar game copies and getting two different results.

**Comment by Standing-Storm** [comment]
> I'm gonna keep testing. You were able to get climate control working on experimental vanilla, right? Because at this point it looks like we're running very similar game copies and getting two different results.

Yeah--current experimental with Bombastic Perks, Mind Over Matter, and Xedra Evolved all running.

**Comment by CrazySwayze** [comment]
Alright now, this is just silly. I literally downloaded a fresh copy of the game from today, made a world, changed absolutely nothing aside from enabling Sky Islands, and I'm still getting the issue. I have no idea how you were able to get climate control to work because I have yet to get it working at all, with any mod.

Minimized archive attached: 
[Totally Vanilla-trimmed.tar.gz](https://github.com/user-attachments/files/17050061/Totally.Vanilla-trimmed.tar.gz)

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-18-0731 abbb6ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland]
]

**Comment by Standing-Storm** [comment]
Figured it out.

![Untitled3](https://github.com/user-attachments/assets/8961f8fd-60d8-418a-8914-5e8e558391c2)

My personal game (where I tested the trait) was updated from the original Sky Island mod because I've been playing it for months, so the bunker's overmap terrain is still open_air. I assumed this was true for new games, but as the screenshot shows, it isn't. So I just need to change the EoC to account for the new terrain. 

In the mutations.json file in the Sky Island folder, replace the `EOC_SKY_ISLAND_CLIMATE_CONTROL` with this:

`  {
    "type": "effect_on_condition",
    "id": "EOC_SKY_ISLAND_CLIMATE_CONTROL",
    "recurrence": [ "3 seconds", "3 seconds" ],
    "condition": {
      "and": [
        { "u_has_trait": "mut_skyisland_temperature_adaptation" },
        { "or": [ { "u_at_om_location": "open_air" }, { "u_near_om_location": "sky_island_subcore", "range": 1 } ] },
        { "math": [ "u_val('pos_z')", "==", "6" ] }
      ]
    },
    "deactivate_condition": { "not": { "u_has_trait": "mut_skyisland_temperature_adaptation" } },
    "effect": [ { "math": [ "weather('temperature')", "=", "from_fahrenheit( 70 )" ] } ]
  }`

It fixes the problem.
