### ISSUE TITLE
[MoM] Channelings learning math issue

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#76510]
### Describe the bug

You can't trigger eoc for learning both channelings with metaphysics 10 and intelligence higher than 20.
I think it's simple bug with math in eoc_learn_recipes.json
> "x_in_y_chance": { "x": 1, "y": { "math": [ "1000 - (u_skill('metaphysics') * 50) - (u_val('intelligence') * 25)" ] } }  in 1223 and 1254 rows.
   

### Attach save file

-

### Steps to reproduce

-

### Expected behavior

Math needs to be changed?

### Versions and configuration

-

### Additional context

Also found minibug with this learning eoc. If you triggered this multiple time and "time in future" was very different at them you can trigger eoc for learning channeling when it was learn.

**Comment by Standing-Storm** [comment]
The additional context sadly can’t be fixed (there’s no way to cancel queued EoCs), but it’s a simple fix for the EoC to set the minimum odds at 1 so they don’t go negative
