### ISSUE TITLE
Hair Grows Instantly / Balds Inappropriately

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#76534]
### Describe the bug

When you have natural hair growth turned on and cut your hair it grows back immediately.

### Attach save file

[New Magic-trimmed.tar.gz](https://github.com/user-attachments/files/17049350/New.Magic-trimmed.tar.gz)

### Steps to reproduce

1. Have character with natural hair growth
2. Cut hair shorter using any method (save has a makeshift haircut kit wielded)
3. Wait
4. Each turn you wait the hair grows through its phases until landing on bald

### Expected behavior

Hair grows over days and weeks, not seconds

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: abbb6ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Maybe related to #76170

**Comment by GuardianDll** [comment]
it related to the fact that numbers in EoC that handle hair grow are broken totally, result in negative time, and, therefore, are running every second
https://github.com/CleverRaven/Cataclysm-DDA/blob/abbb6ce0fe3b61c4c49c2d1fa168eaf9be3f5b90/data/json/effects_on_condition/npc_eocs/appearance_eocs.json#L10
