### ISSUE TITLE
.410 ammo will disappear if two different types are loaded into a Taurus Judge

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#76541]
### Describe the bug

If you have different types of .410 shells, say 000 shot and slug, load one type into the gun, and then try loading the second kind next, it will just disappear and the gun will remain unloaded. This error message appears:

` DEBUG    : tried to put an item (410shot_slug) count (1) in a container (taurus_judge) that cannot contain it: pocket unacceptable because holster already contains an item`

` FUNCTION : put_in`
` FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp`
` LINE     : 1803`
 `VERSION  : 6805e26`

This, as far as I know, this only happens to this weapon. Or any other revolver that takes .410. 

### Attach save file

[Brad-trimmed.tar.gz](https://github.com/user-attachments/files/17052526/Brad-trimmed.tar.gz)

### Steps to reproduce

1. load into attached save file.
2. Reload a shell into the judge. either type. You can load several as long as you leave a chamber open.
3. Reload the second type, the bug happens here.

### Expected behavior

Different ammo types should be able to sit inside a revolver. See attached images

### Screenshots

![image](https://github.com/user-attachments/assets/88f1b504-fd97-4068-b9e3-1b9a6b9a41dd)
![image](https://github.com/user-attachments/assets/12a73e3d-a09b-408b-82ce-b43966894bbf)
![image](https://github.com/user-attachments/assets/af680ef9-7217-47a8-9aae-4a9dcb6e4402)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.2274 (1909)
- Game Version: abbb6ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Daved27hundred** [comment]
> Why did you make this issue with my screenshot instead of your own?

Laziness...I've replaced them with my own now.

**Comment by Holli-Git** [comment]
Alright, just didn't feel comfortable confirming without that. Also, when I did it, I got an error, that may be helpful to include

**Comment by Daved27hundred** [comment]
ah i got it too
