### ISSUE TITLE
Can't reload HWP magazines with 5.56 clips

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76558]
### Describe the bug

HWP 40-round 5.56 magazines are absolutely fine with every 5.56 ammo, but I can't use 10-round clips to reload them

### Attach save file

N/A

### Steps to reproduce

1. Have an empty HWP 40-round 5.56 magazine
2. Have a 10-round 5.56 clip
3. r

### Expected behavior

Being able to reload these magazines

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-19-0617 e00a779 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by GuardianDll** [comment]
It supports only stanag magazines, and i don't know are 5.56 HWP should be compatible with stanag-type tools
Description probably need a bit of clarification, but it is pretty much intended
