### ISSUE TITLE
"Error: rm121aux (struct itype) has two definitions from the same source (dda)!" when trying to create a new character.

### ISSUE THREAD

**Issue by Seb-The-SamMarten** [CleverRaven/Cataclysm-DDA#76572]
### Describe the bug

When trying to create a custom character on the latest experimental (2024-09-20-1705) the game will throw this error;
 DEBUG    : Error: rm121aux (struct itype) has two definitions from the same source (dda)!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1062
 VERSION  : 03b8d34

Attempting to skip it returns to the menu, attempting to ignore it causes an infinite load screen.

### Attach save file

N/A

### Steps to reproduce

1. Create a world. (Mine had Magiclysm, Xaedra, and Mind over Matter chosen if that matters)
2. Create a custom character.
3. Error.

### Expected behavior

To go to the character creation menu.

### Versions and configuration

- Windows 10
- Version 03b8d34
- UltiCa tileset
- English (US)
-   "dda",  "no_npc_food",  "personal_portal_storms",  "no_fungal_growth",  "light_weariness",  "alt_map_key",  "bombastic_perks",  "translate_dialogue",  "no_cbm_slots",  "speedydex",  "StatsThroughSkills",  "magiclysm",  "mindovermatter", "xedra_evolved"

### Additional context

[save.zip](https://github.com/user-attachments/files/17081026/save.zip)
[crash + debug.zip](https://github.com/user-attachments/files/17081029/crash.%2B.debug.zip)

**Comment by Holli-Git** [comment]
Can you try replicating without 3rd party mods? Also follow the instructions for versions and config, its a lot easier to read

**Comment by RenechCDDA** [comment]
You have stray files in your installation, there is [only one definition.](https://github.com/CleverRaven/Cataclysm-DDA/blob/03b8d3484261ed7de7bf4f674ea628b0b0f32795/data/json/obsoletion_and_migration_0.I/gun.json#L995) (Readers will note that the second result is a variant, not an itype)

![image](https://github.com/user-attachments/assets/f8958122-c772-4084-8089-a05f236b9a56)


Don't install over old copies of the game, always install to a fresh empty folder.

**Comment by RenechCDDA** [comment]
> Can you try replicating without 3rd party mods? Also follow the instructions for versions and config, its a lot easier to read

Mods cannot cause this, the source of each item is tracked and it's reporting that there's two from DDA. There are not two from DDA, this is a user error.

**Comment by Seb-The-SamMarten** [comment]
Hm, never had an issue using the 'install over previous installation' option with Catapault but I will try doing a fresh install entirely.
