### ISSUE TITLE
Cave that has absurd levels of overpopulated spawns in the subterranean level with small rail and miner bot. 

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#76597]
### Describe the bug

I'm not sure what is going on here, so i can only take an educated guess is that the game didn't know what to populate the cave with so it just spawned everything.

I was originally just going down but couldn't get past the bear that was blocking the entrance (In order to use my artefact that reveals nearby terrain and was doing that in caves to see if i can find any secret labs nearby etc) was was being teleported several tiles away when i tried to push past due to Z level stairs not aligning up so it spawned me where the game thought i should, so i thought this was unusual and debug teleported downbelow and lo-and-behold a absolutely monstrous amount of spawns are suddenly here so i'm confused as to why.

### Attach save file

[Zakhadia_BigCity-trimmed.tar.gz](https://github.com/user-attachments/files/17086009/Zakhadia_BigCity-trimmed.tar.gz)

### Steps to reproduce

I guess check a spawn of various caves to see if this is a one off occurrence or the result of some recent change.

### Expected behavior

Not have every seemingly unique creature spawn type, spawn underground?

### Screenshots

![image](https://github.com/user-attachments/assets/44634687-0211-4c9f-b2ce-c0d535131b3e)
![image](https://github.com/user-attachments/assets/1bfcf7bc-e83c-4e23-a92c-9f4bcf7f978f)
![image](https://github.com/user-attachments/assets/ac49ccb9-bb0b-41f0-9c18-13072cd3af89)
![image](https://github.com/user-attachments/assets/dbd093f2-c9a9-466d-a9c1-e12e7abc711e)

### Versions and configuration

- OS: Windows
    - OS Version: 7
- Game Version: 2c596cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks]
]

**Comment by Procyonae** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/5f6f5e06a32ce82eac22e3ccebac27f1d1640c0f/data/json/mapgen/cave.json#L681-L710

It's spawning monsters with a 2% chance which sounds reasonable except that it's a 2% chance on 154 different " " tiles and when it succeeds it spawns a group with some very high pack size entries like the bats. I'm not quite sure why someone thought an average spawn of 19 bats was sensible in a game where a bat takes up a tile but that group and numbers is at least 11 years old, it's just only used in 2 maps now (and the other one spawns with really low density so it doesn't have this problem)

https://github.com/CleverRaven/Cataclysm-DDA/blob/5f6f5e06a32ce82eac22e3ccebac27f1d1640c0f/data/json/monstergroups/wilderness.json#L2-L17
