### ISSUE TITLE
Loudness multiplier of gunmods can't display correctly

### ISSUE THREAD

**Issue by HardcoreRanger** [CleverRaven/Cataclysm-DDA#76604]
### Describe the bug

Loudness multiplier of gunmods can't display correctly.
For now, it's just displayed a value equal to loudness modifier.

### Attach save file

[尤金.zip](https://github.com/user-attachments/files/17088553/default.zip)

### Steps to reproduce

1.Get any gunmod.
2.Examine its description.

### Expected behavior

If this item does not involve loudness multiplier, it should be displayed as x1 or simply not displayed.

### Screenshots

![无标题](https://github.com/user-attachments/assets/66df07eb-3e0f-49ce-932f-ce465f92a58d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: 0376347 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/744251b8383086f69695a4f6afb002d1168abbda/src/item.cpp#L3627
`!= 0` -> `!= 1.0`

**Comment by GuardianDll** [comment]
fixed by #76821
