### ISSUE TITLE
Mounting [M249 + select fire trigger] removes select fire trigger from M249

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76609]
### Describe the bug

Can't have semi-auto M249 in a vehicle; gun mod disappears on gun mount

### Attach save file

N/A

### Steps to reproduce

1. Grab an M249
2. Attach an M249 select fire trigger to it
3. Mount it to a vehicle
4. Try to switch fire mode - only [burst] is available
5. Umount it from a vehicle - it doesn't have [select fire trigger] anymore

### Expected behavior

Mods don't disappear

### Screenshots

![image](https://github.com/user-attachments/assets/7867e182-d1c9-478f-9360-4cae15248676)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-19-0617 e00a779 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by GuardianDll** [comment]
Turrets are not compatible with turrets, solving it is desired, but it is not related to select fire trigger directly

**Comment by dev-dsp** [comment]
Sorry? WDYM by 'Turrets are not compatible with turrets'?

**Comment by GuardianDll** [comment]
brainfart, my bad
