### ISSUE TITLE
Moving something in/out of container restores advanced invertory to default when "Open default advanced inventory layout" is enabled

### ISSUE THREAD

**Issue by fire1919ua** [CleverRaven/Cataclysm-DDA#76606]
### Describe the bug

Moving items out of container by advanced inventory sometimes restores default layout (exit from container).

### Attach save file

N/A

### Steps to reproduce

1. Setup [Open default advanced inventory layout = True] in the settings;
2. Assign key to the "Save default layout";
3. Save the default layout for the advancd inventory (e.g. [All] for the left window and [5] for the right);
4. Have a contianer near on the flor with few items (e.g. wallet with dollar bills);
5. Open advancd inventory;
6. Open the container [C] (e.g. wallet);
7. Move some items by pressing [Enter] or [m] or [M] (in the or from the container);
8. If issue is not reproduced repeat the step 7.

### Expected behavior

Advanced inventory layout restores only by re-opening advanced inventory OR by pressing assigned to the "Restore default layout" key.

### Versions and configuration

cdda-windows-tiles-sounds-x64-2024-09-22-0113
Open default advanced inventory layout - True
saved default advanced inventory

**Comment by alef** [comment]
Must be something related to #76490, maybe `do_return_entry()`

**Comment by alef** [comment]
Probably related to #76490 and #76610

**Comment by alef** [comment]
The reason for the random AIM UI reset is this call to [`kill_advanced_inv()`](https://github.com/CleverRaven/Cataclysm-DDA/blob/45a93aa5a6b5038a7f46258179eee0353c9be20a/src/do_turn.cpp#L536)

**Comment by alef** [comment]
@fire1919ua please check 2024-10-02-0553 or later.

**Comment by fire1919ua** [comment]
@alef checked on the cdda-windows-tiles-sounds-x64-2024-10-02-1516 - fixed.
Great job, thank you!
