### ISSUE TITLE
green light created by NV doesn't switch to regular when batteries die

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76608]
### Describe the bug

This happens at least with my UPS-modded enhanced NV goggles and Hub01 helmet, but I'm pretty sure I saw it with regular medium batteries.

### Attach save file

[Nairn-trimmed.tar.gz](https://github.com/user-attachments/files/17089349/Nairn-trimmed.tar.gz)

Save file is prepared - UPS is charged for 3/503, so just wait for a minute or two

### Steps to reproduce

1. Have a NV goggles / Hub01 helmet charged
2. Enable it
3. Wait until they are discharged
4. NV turns off, but fov is still green

### Expected behavior

NV visual effect turns off when NV apparatus does

### Screenshots

![image](https://github.com/user-attachments/assets/22ae4007-40c4-4c83-9213-09b2a1e7a5e5)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-19-0617 e00a779 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by dev-dsp** [comment]
Batteries run out. Then green light (not NV effect, just green light) stays ON until you turn on-off any NV device.

**Comment by Night-Pryanik** [comment]
I conducted some tests and found out that game for some reason thinks that character still wears _activated_ goggles even after batteries ran out and it converts the goggles into a deactivated version. I suppose this has something to do with pockets, since the bug didn't occur in my tests where I temporarily changed goggles to be wearable directly on the head, not on helmet as it is now.

**Comment by CoroNaut** [comment]
Also able to reproduce.
1. get NV goggles, tactical helmet, ups, ups conversion mod
2. Install UPS into NV goggles and turn on the UPS
3. Turn on NV goggles and notice the minimap and nearby area are now visible through night vision.
4. take battery out of the UPS
5. Notice your vision no longer benefits from the night vision distance, but is still green around you and on minimap

[NVTest-trimmed.tar.gz](https://github.com/user-attachments/files/17100168/NVTest-trimmed.tar.gz)

![image](https://github.com/user-attachments/assets/0c5d9285-70a7-4a57-84ac-565db958bb8c)
- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-09-21-1412 e66affb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
