### ISSUE TITLE
zombies magically disappear when killed on a certain terrain

### ISSUE THREAD

**Issue by Ruminator24** [CleverRaven/Cataclysm-DDA#76620]
### Describe the bug

When killing zombies, sometimes they have a tendency to... disappear on certain terrain. The half built simple metal wall for example. This is best seen on the crashed airliner, where if you kill a zombie on the metal wings, their corpse disappears, FOREVER. Even if you destroy the wing, you will never find the body.

### Attach save file

N/A

### Steps to reproduce

1. Go to a crashed airliner/spawn half built simple metal walls
2. Spawn/find zombies and kill them on said wall
3. watch them disappear.
4. destroy the wing to confirm that in fact they no longer exist.

### Expected behavior

I expect zombies to not be magicians.

### Screenshots

![zom3](https://github.com/user-attachments/assets/bb74a6c8-1bb9-41bb-ad30-aa800f0b7b1b)
![zom2](https://github.com/user-attachments/assets/2a6b77a2-d41b-4040-b126-5da6acf7652c)
![zom1](https://github.com/user-attachments/assets/16291f58-5a98-460a-8ea1-92862b90ae71)

### Versions and configuration

- Windows 10
- abbb6ce
- Tiles
- English
- No mods

### Additional context

Strangely, if you kill a zombie that is sitting on a wall next to some ground, they will not disappear and their body will flop onto the ground.

**Comment by CoroNaut** [comment]
Can confirm, I made pads 3x3 to 6x6 and filled the entire pad with 9 -> 36 zombies to fill the pad. I killed all of them and spread out the corpses to one corpse per tile for easier counting. There is definitely some zombies missing
3x3: 9
4x4: 15
5x5: 24
6x6: 32
[TESTINGTWO-trimmed.tar.gz](https://github.com/user-attachments/files/17091356/TESTINGTWO-trimmed.tar.gz)
![image](https://github.com/user-attachments/assets/e42ef23e-db1d-4957-ab36-c787d400be2d)

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-09-21-1412 e66affb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by osuphobia** [comment]
Probably due to `NOITEM`?

**Comment by mqrause** [comment]
Items spill only up to 2 tiles from the tile they're spawned on when it can't hold items for whatever reason. That's why on the 5x5 the center tile and on the 6x6 the center 2x2 square can't spawn corpses.
