### ISSUE TITLE
"gun shy" trait still prevents use of bows.

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#76651]
### Describe the bug

Despite being a trait designed to allow the player to use bows and not guns, it doesn't allow the player to use bows.

### Attach save file

N/A

### Steps to reproduce

1: choose the gun shy trait,
2: spawn in
3: spawn in a bow, with some arrows
4: try to shoot
5: you should get a message on the side of the screen that says 'your too gun shy to use this"

### Expected behavior

I expected to be able to shoot a bow.

### Screenshots

![Screenshot 2024-09-24 201452](https://github.com/user-attachments/assets/2352aa6a-a25f-40ab-8151-491812065ee5)

### Versions and configuration

Latest Experimental Build

### Additional context

Bow machine broke

**Comment by KeremBabaG** [comment]
Aww :(
Anyways I think the problem stems from the gunmode_checks_common in ranged.cpp, It only checks if you have the trait and not wheter or not the weapon is primitive, haven't tested but a similar problem should occur when using a mounted ballista
