### ISSUE TITLE
Smashing chain link fence on the roof leaves a hole

### ISSUE THREAD

**Issue by Syler1984** [CleverRaven/Cataclysm-DDA#76652]
### Describe the bug

If you fully smash chain link fence and, then, metal posts it will result in a hole in the roof instead of a roof tile. Interesting that it didn't use to be that way a few months ago. I remember that, because I used to smash gun store roof fences for wires to make lockpicks. Now you can breach gun stores by just destroying the fence on the roof.

![Screenshot_18](https://github.com/user-attachments/assets/390a0aa4-b741-4273-bdf2-c35c382c0901)

### Attach save file

[Test.zip](https://github.com/user-attachments/files/17122952/Test.zip)

### Steps to reproduce

1. Climb the roof with the fence (usually stores)
2. Smash the fence.
3. Smash remaining fence posts.

### Expected behavior

Smashing fence should result in some form of a walkable tile.

### Versions and configuration

experimental 2024-09-24-2221 78ebcd0

**Comment by osuphobia** [comment]
#76376

**Comment by TheShadowFerret** [comment]
/confirmed
But also a dupe
