### ISSUE TITLE
Cannot recharge Professional Camera

### ISSUE THREAD

**Issue by LowIncomeNeighborhood** [CleverRaven/Cataclysm-DDA#76662]
### Describe the bug

Can't recharge it. Doesn't matter what you drop it in: Recharger, Battery Charger, Charger Box. Nothing works. You cannot plug it into things. When it is dead out of battery, all that happens on use is "You need 5kw to activate this."

### Attach save file

[Albany-trimmed.tar.gz](https://github.com/user-attachments/files/17133805/Albany-trimmed.tar.gz)

### Steps to reproduce

1. Try to recharge camera.
2. Fail

### Expected behavior

I should be able to recharge it.

### Versions and configuration

Win 11
- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-22-0113 0376347 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PGR-14** [comment]
Confirmed, no way to plug it in & no battery slot.

**Comment by ISuckM8** [comment]
This actually happens with every camera in the game. It should now be fixed in #76762
