### ISSUE TITLE
Cannot receive the mutation Giant Pincer from Crustacean Primer

### ISSUE THREAD

**Issue by Sutton618** [CleverRaven/Cataclysm-DDA#76672]
### Describe the bug

No matter how long you wait, no matter how much Crustacean Primer you take, you will NEVER mutate Giant Pincer. You will get every other mutation in the tree and then the game will merely state "Your body tries to mutate, but it lacks a primer to do so and only contorts for a moment." Mutating Giant Pincer through the debug menu works fine. This was something I noticed in an earlier playthrough so made a test character to confirm this.

### Attach save file

[Worthington Springs-trimmed.tar.gz](https://github.com/user-attachments/files/17144651/Worthington.Springs-trimmed.tar.gz)

### Steps to reproduce

1. Make a player.
2. Mutate everything in the Crustacean tree except giant pincer
3. Take Crustacean Mutagenic Primer and Catalyst
4. After waiting, you will get messages in the log that your body tries to mutate, but lacks primer, even though it has primer and has a mutation it can still receive in that category (giant pincer).

### Expected behavior

I expect the Giant Pincer mutation to manifest, considering I don't have it and my body has both primer and catalyst.

### Screenshots

![bug report 2](https://github.com/user-attachments/assets/25c40d7e-8ee8-48ab-a79e-990f3b1ba2a1)
![bug report 3](https://github.com/user-attachments/assets/41408f6d-6fda-499f-98d6-c7137cb32d50)
![bug report 1](https://github.com/user-attachments/assets/e153db3d-39d5-46ac-baad-a2c792630932)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-09-24-1915 7ee3ce7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Kamejeir** [comment]
The "valid" field on CRUSTACEAN_CLAW appears to be set to false for some reason.

**Comment by Sutton618** [comment]
Huh, not a code guy so didn't realize it was that simple (and didn't know what "valid" was used for..). Removed that one line and immediately mutated the pincer upon re-loading in and waiting a few minutes. Thanks for looking into this! Guess I could make a PR but not totally sure what I'd be doing, surely its not as simple as removing that one line..

**Comment by Kamejeir** [comment]
#65310 The author claimed "I spent several hours making sure things spawned correctly and that you could correctly mutate through the crustacean branch." and assuming it is truthful (when nothing obvious has changed in the blame/code history), valid being set to false might've broken with whatever under-the-hood changes has happened to mutations since last year. That is like a sufficient amount to go on, claiming it is broken.
