### ISSUE TITLE
Can't Use Dog Food on Dogs

### ISSUE THREAD

**Issue by LowIncomeNeighborhood** [CleverRaven/Cataclysm-DDA#76688]
### Describe the bug

Whenever I use the "Feed to Animal" option on dog food, my guy eats it instead.

### Attach save file

[Kirkwood-trimmed.tar.gz](https://github.com/user-attachments/files/17165636/Kirkwood-trimmed.tar.gz)

### Steps to reproduce

1. Try to feed dog food to a dog
2. Eat it instead
3. Be depressed you ate dog food

### Expected behavior

I should feed the dog food to the animal

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-22-0113 0376347 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
Thank you for reporting it, but we already track this bug in #76414
Closing it as duplicate
