### ISSUE TITLE
Vehicle Anvils?

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#76685]
### Is your feature request related to a problem? Please describe.

We've got a forge, but not an anvil for vehicles.

### Solution you would like.

Simply add it in, & give it the appropriate level of anvil.

### Describe alternatives you have considered.

Give the item itself the quality?

**Comment by Fris0uman** [comment]
Not planned, anvil in vehicles don't really make sense, just put the anvil down on solid ground that doesn't have supsensions. See https://github.com/CleverRaven/Cataclysm-DDA/pull/74448 for a previous discussion of this.

**Comment by PGR-14** [comment]
Fair enough.
