### ISSUE TITLE
Help w/ modding?

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#76683]
### Is your feature request related to a problem? Please describe.

I'm trying to add in an exported vehicle, but it keeps giving me an error message.
![Screenshot 2024-09-27 074634](https://github.com/user-attachments/assets/ade3444b-ea7d-44bb-9dbf-f656d5de2eb9)
For reference, here's the code: 
{"id":"Surv_Cube","type":"vehicle","name":"Survivor Cube Van","blueprint":[
" ^^^^^ ",
" ┌─^─┐ ",
"o┌───┐o",
" '#o#' ",
" ┌─'─┐ ",
" │&=H│ ",
" │==&│ ",
" │===│ ",
"└+++┘"],
"parts":[{"x":-5,"y":-1,"parts":["frame#sw","board#sw","roof"]},
{"x":-5,"y":0,"parts":["frame#horizontal_rear","door_shutter","roof"]},
{"x":-5,"y":1,"parts":["frame#horizontal_rear","door_shutter","beeper","roof"]},
{"x":-5,"y":2,"parts":["frame#horizontal_rear","door_shutter","roof"]},
{"x":-5,"y":3,"parts":["frame#se","board#se","roof"]},
{"x":-4,"y":-1,"parts":["frame#vertical_left","wheel_mount_medium","wheel_wide","roof","stowboard#wheel_left"]},
{"x":-4,"y":0,"parts":["frame#cross","roof","reinforced_solar_panel_v2","spring_plate","cargo_space"]},
{"x":-4,"y":1,"parts":["frame#cross","roof","trunk_floor","afs_roof_external_tank","large_storage_battery"]},
{"x":-4,"y":2,"parts":["frame#cross","cargo_space","roof","reinforced_solar_panel_v2","spring_plate"]},
{"x":-4,"y":3,"parts":["frame#vertical_right","wheel_mount_medium","wheel_wide","roof","stowboard#wheel_right"]},{"x":-3,"y":-1,"parts":["frame#vertical_left","roof","stowboard#vertical_left"]},
{"x":-3,"y":0,"parts":["frame#cross","cargo_space","roof","reinforced_solar_panel_v2","spring_plate"]},
{"x":-3,"y":1,"parts":["frame#cross","roof","trunk_floor",{"part":"afs_roof_external_tank","fuel":"water_clean"},"large_storage_battery","atomic_lamp"]},
{"x":-3,"y":2,"parts":["frame#cross","roof","reinforced_solar_panel_v2","spring_plate","veh_forge"]},
{"x":-3,"y":3,"parts":["frame#vertical_right","roof","stowboard#vertical_right"]},
{"x":-2,"y":-1,"parts":["frame#vertical_left","board#vertical_left","roof"]},
{"x":-2,"y":0,"parts":["frame#cross","roof",{"part":"veh_tools_kitchen","tools":["press","cordless_drill","puller","metalworking_tongs","hotplate","pan","coffeemaker","tongs","soldering_iron"]},"reinforced_solar_panel_v2","towel_hanger","water_faucet","spring_plate"]},
{"x":-2,"y":1,"parts":["frame#cross","roof","trunk_floor",{"part":"afs_roof_external_tank","fuel":"gasoline"},"large_storage_battery"]},
{"x":-2,"y":2,"parts":["frame#cross","roof","minifridge","reinforced_solar_panel_v2","spring_plate"]},
{"x":-2,"y":3,"parts":["frame#vertical_right","board#vertical_right","roof"]},
{"x":-1,"y":-1,"parts":["frame#sw","board#nw",{"part":"tank","fuel":"gasoline"}]},
{"x":-1,"y":0,"parts":["frame#cross","board#horizontal_front"]},
{"x":-1,"y":1,"parts":["frame#cross","door","roof"]},
{"x":-1,"y":2,"parts":["frame#cross","board#horizontal_front"]},
{"x":-1,"y":3,"parts":["frame#se","board#ne",{"part":"tank","fuel":"gasoline"}]},
{"x":0,"y":-1,"parts":["frame#vertical_left","door#front_left"]},
{"x":0,"y":0,"parts":["frame#cross","seat#windshield_front","seatbelt","controls","integrated_heater_small","integrated_cooler","stereo","dashboard","vehicle_alarm","horn_car","roof"]},
{"x":0,"y":1,"parts":["frame#cross","box","roof"]},{"x":0,"y":2,"parts":["frame#cross","seat#windshield_front","seatbelt","roof","inboard_mirror"]},
{"x":0,"y":3,"parts":["frame#vertical_right","door#front_right"]},
{"x":1,"y":-2,"parts":["wing_mirror"]},
{"x":1,"y":-1,"parts":["frame#vertical_T_left","wheel_mount_medium_steerable","wheel_wide","windshield#wheel_left"]},
{"x":1,"y":0,"parts":["frame#horizontal_2","windshield#cover_left"]},
{"x":1,"y":1,"parts":["frame#horizontal_2","windshield#horizontal_front"]},
{"x":1,"y":2,"parts":["frame#horizontal_2","windshield#cover_right"]},
{"x":1,"y":3,"parts":["frame#vertical_T_right","windshield#wheel_right","wheel_mount_medium_steerable","wheel_wide"]},
{"x":1,"y":4,"parts":["wing_mirror#right"]},
{"x":2,"y":-1,"parts":["frame#nw","wide_headlight_reinforced","halfboard#nw"]},
{"x":2,"y":0,"parts":["frame#horizontal_front","halfboard#cover_left","headlight"]},
{"x":2,"y":1,"parts":["frame#cover","halfboard#cover","engine_v6","alternator_car","battery_car"]},
{"x":2,"y":2,"parts":["frame#horizontal_front","halfboard#cover_right","headlight"]},
{"x":2,"y":3,"parts":["frame#ne","halfboard#ne","wide_headlight_reinforced"]},
{"x":3,"y":-1,"parts":["ram_spiked"]},
{"x":3,"y":0,"parts":["ram_spiked"]},
{"x":3,"y":1,"parts":["ram_spiked"]},
{"x":3,"y":2,"parts":["ram_spiked"]},
{"x":3,"y":3,"parts":["ram_spiked"]}],
"items":[{"x":-3,"y":0,"chance":100,"items":["sm_extinguisher"]]}],"zones":[]
}

### Solution you would like.

Just some help figuring out what's wrong.

**Comment by Night-Pryanik** [comment]
It will be much easier to solve your problen if you attached the Json file here.

**Comment by PGR-14** [comment]
I attached it to another mod's Json, but here's the export file:
[CubeSurv.json](https://github.com/user-attachments/files/17163788/CubeSurv.json)

**Comment by ZhilkinSerg** [comment]
[trytousethisfile.json](https://github.com/user-attachments/files/17164299/trytousethisfile.json)

**Comment by ZhilkinSerg** [comment]
There is a stray `[` character in your json. If you have a savegame archive with original vehicle you have exported, someone can test if vehicle export function works properly. If it works properly then probably you have accidentally added stray `[` yourself.

**Comment by IdleSol** [comment]
If you get an error with the mirror. Change the order of the lines:

```
--      {"x":1,"y":-2,"parts":["wing_mirror"]},
    {"x":1,"y":-1,"parts":["frame#vertical_T_left","wheel_mount_medium_steerable","wheel_wide","windshield#wheel_left"]},
++      {"x":1,"y":-2,"parts":["wing_mirror"]},
```

**Comment by PGR-14** [comment]
Thanks y'all, it works.
