### ISSUE TITLE
Can't activate "durable plastic sack, cement" to get the recipe for mortar

### ISSUE THREAD

**Issue by tcld** [CleverRaven/Cataclysm-DDA#76706]
### Describe the bug

As far as I can see [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/75348/files), it should be possible to learn how to craft mortar by "activating" the sack it came in.
When doing so, however, nothing happens for me (no message at all).

### Attach save file

N/A

### Steps to reproduce

1. Make a player with a "durable plastic sack, cement".
2. [a]ctivate the item.
3. Nothing.

### Expected behavior

As far as I understand, the recipe for mortar should be learned from activating the sack.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cdda-experimental-2024-09-15-0411 9a984a1350 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Alternative Map Key [alt_map_key]
]

**Comment by tcld** [comment]
First: Thank you for taking such a quick look at this!

And sorry for reopening this, but I just tested it and I still get nothing after 'a'ctivating the cement bag. No log output at all, no recipe. There seems to be more wrong than just the check.
I am using the same save as before, but as far as I understand, a change like this should still have an effect, right?

**Comment by Maleclypse** [comment]
> First: Thank you for taking such a quick look at this!
> 
> And sorry for reopening this, but I just tested it and I still get nothing after 'a'ctivating the cement bag. No log output at all, no recipe. There seems to be more wrong than just the check. I am using the same save as before, but as far as I understand, a change like this should still have an effect, right?
> 
> EDIT: OK, adding a comment doesn't reopen the issue anyway.

Did you spawn in a new version of the bag as any saved bags prior to the change won't be affected by the

**Comment by tcld** [comment]
That indeed worked, thank you. It seems I don't understand the save data yet.
