### ISSUE TITLE
Cody Miller can't craft chainmail.

### ISSUE THREAD

**Issue by Zhurdon** [CleverRaven/Cataclysm-DDA#76710]
### Describe the bug

Cody miller is not able to craft a full set of chainmail. Cody can craft plate just fine. But it seems like for chainmail, at the step where measurements are taken, the only dialogue option is "forget it".

### Attach save file

[Hope-trimmed.tar.gz](https://github.com/user-attachments/files/17174523/Hope-trimmed.tar.gz)

### Steps to reproduce

1. Complete Cody's quest.
2.  Try to get measured for a set of chainmail.

### Expected behavior

Cody should be able to craft a set of tempered steel chainmail in 4 weeks.

### Screenshots

![image](https://github.com/user-attachments/assets/8e84c2cd-0312-4688-b76d-ae2ba76c5b31)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: 39eabf6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by XygenSS** [comment]
Did he used to craft you untyped `steel` chainmail?
