### ISSUE TITLE
Aluminum foil rolls appear unusable

### ISSUE THREAD

**Issue by EvanBalster** [CleverRaven/Cataclysm-DDA#76733]
### Describe the bug

Aluminum foil rolls appear in kitchen 'junk drawer' tiles in large numbers, each containing a single foil wrapper (this appears to be in error, as one foil roll should be able to contain dozens of wrappers).

It is not currently possible to unload or insert foil wrappers into the roll (compare to duct tape).  It is also impossible to disassemble foil wrappers or use them as containers.  Because they don't factor directly into any crafting recipes (eg, they must be deconstructed to make bronze) this makes them almost entirely unusable except as rudimentary cooking tools.

### Attach save file

N/A

### Steps to reproduce

1. Generate or collect an aluminum foil roll.
2. Attempt to remove the foil wrapper from the roll.
3. Attempt to disassemble the foil wrapper.

### Expected behavior

While it is potentially reasonable that players shouldn't necessarily be able to reload a foil roll, it should be possible to unload its contents for use or disassembly.  Rolls of foil should generate with many sheets, rather than as many rolls with only a single sheet.

### Versions and configuration

Windows 10, latest experimental as of today.

**Comment by GuardianDll** [comment]
how it was fixed for duct tape, do you happen to know? it should be applied to foil in this case

**Comment by EvanBalster** [comment]
I don't think duct tape was ever broken.  It is used directly as a crafting ingredient and as a type of charge, and those interactions can access the roll.  Duct tape cannot be disassembled or removed from its roll, and these functions don't appear to be implemented for that type of container.

If foil rolls contained aluminum foil instead of foil wrappers, the stuff would be usable for crafting and there would be no reason to disassemble or remove it.  You wouldn't be able to use the foil as a container but you can't do that now in any case.
