### ISSUE TITLE
Supernatural abilities menu, cutoff at the top

### ISSUE THREAD

**Issue by ryeookin** [CleverRaven/Cataclysm-DDA#76746]
### Describe the bug

My game was a few months old and I ended up updating it yesterday. After doing so when I open the "supernatural abilities" menu it shows my spells/abilities but cuts them off at the top.
How can one fix this?

Note: This issue wasn't present pre-update.
Thanks for your time.

### Attach save file

[Tombstone-trimmed.tar.gz](https://github.com/user-attachments/files/17196243/Tombstone-trimmed.tar.gz)

### Steps to reproduce

This happens every time I open my supernatural abilities menu. I've also tried closing/reopening CDDA but the issue still persists with my save.

### Expected behavior

It shouldn't cut off the top of that menu.

### Screenshots

![image](https://github.com/user-attachments/assets/d400891a-412d-4708-8d09-f9b4a2fae123)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4249 (23H2)
- Game Version: cdda-experimental-2024-09-29-0806 26de5a1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    Minimod: No Skill Rust [minimod_no_rust],
    Ryans no lieutenant mod [aRyanMod_blacklist_lieutenant]
]

**Comment by yamil-90** [comment]
can confirm, been having this problem since i upgraded to the 2024-09-18-0731 version. cant see the name of the spells and some tables are hidden by the window's border
![image](https://github.com/user-attachments/assets/61e7ca4a-1b24-40ad-ad85-145d972ba822)

**Comment by ryeookin** [comment]
Interesting.. so you're issue is with the right side of the window that doesn't contain all the writeup for the spell for you, where as my issue is with the left side of the window which cuts off the top (which for me blocks one spell that's just off the top of the screen and also doesn't thus show what list we're in such as 'favorites', 'technomancer', 'magus', etc). 

The specifics are different but we're both clearly having issues with formatting of this window and its text.🤔

**Comment by yamil-90** [comment]
i too have the same issue with the top of the window not being visible, cant really tell if im in the favorites, druid etc tab. also it seems like the size of the window depends of the amount of spells that are shown when you open it. for example if i dont have any favorite spells when i open the window it will show the "all" tab and the window will try to accommodate all the spell i know so it will be bigger, but will not resize if i change to the other tabs like druid or earthbender or whatever. but if i select a couple of spells as favorites close and reopen the window the favorite tab takes priority so it will be smaller as it only needs to show 2 or 3 spells. but when i cycle to the "all" tab the size of the window doesnt change. 
also the spell description when trying to study it gets cut off and i cant see my current level. maybe its hidden somewhere 
![image](https://github.com/user-attachments/assets/33c253b4-46ee-4aea-9cbc-457bdec0655c)

**Comment by MorphingE** [comment]
> Interesting.. so you're issue is with the right side of the window that doesn't contain all the writeup for the spell for you, where as my issue is with the left side of the window which cuts off the top (which for me blocks one spell that's just off the top of the screen and also doesn't thus show what list we're in such as 'favorites', 'technomancer', 'magus', etc).
> 
> The specifics are different but we're both clearly having issues with formatting of this window and its text.🤔

I have both issues, to a degree. It was fine until I had enough spells that it started to require scrolling. After that, it pretty much broke (the left side) so that the first 2 spells are out of view at the top. The right hand window is largely fine for me, but some spells don't wordwrap certain extra details. Might be an issue with the spell's description, but I haven't checked yet on that.
![Num2](https://github.com/user-attachments/assets/eaf7de30-9771-4778-b2cd-569b2fef238c)

**Comment by ryeookin** [comment]
@yamil-90 Ah I see, yeah we overlap there too.
@MorphingE 
Hmm, so maybe it is breaking because we have more then it can handle in its current iteration? I mean it should be able to handle so many spells, but seemingly isn't.

Also, yeah I am missing some characters on the right as well. Here's my section of 'return critters':
![image](https://github.com/user-attachments/assets/e5dc09f8-d41a-4ed3-ab15-5bd4e4c79e8f)

**Comment by db48x** [comment]
Let’s try to keep to one bug report per bug report, as it were. The text wrapping and formatting in the spell description is fixed by #76513, so we needn’t include it here. Likewise #75666 covers the missing category display. Note that you can still switch categories with the keyboard shortcuts, it just doesn’t show you which one you’re in.

Cutting off the top of the window is new to me, however, as it is intended to max out at the vertical height of your screen and then scroll if there are more menu entries than will fit. Do you get the same height problem if you use the Debug → Spawning → Spawn an item menu? It lists every possible item in the game, so it’s rather tall.

**Comment by ryeookin** [comment]
@db48x 
I tried that, here's what I'm seeing:
![image](https://github.com/user-attachments/assets/959958a6-0bb9-44ec-9ae8-dd367b24f5ac)
 Is that normal?

**Comment by ryeookin** [comment]
Note that is a copy/paste of my full screen.

**Comment by db48x** [comment]
Yes, that’s normal.

**Comment by ryeookin** [comment]
Alright, after you existing bug reports get merged I'll update and test it again. Here's hoping they fix this issue too.

**Comment by ryeookin** [comment]
I just tested it myself after updating and I wanted to confirm this fixed it on my end as well. Thanks for the fix! :D

**Comment by db48x** [comment]
You’re welcome! :)
