### ISSUE TITLE
0.H RC: steel ballistic plate disassembles into synthetic fabric patches

### ISSUE THREAD

**Issue by guijan** [CleverRaven/Cataclysm-DDA#76767]
### Describe the bug

Disassembling a `steel ballistic plate` yields `synthetic fabric patches`.

### Attach save file

[Mill Creek-trimmed.tar.gz](https://github.com/user-attachments/files/17217738/Mill.Creek-trimmed.tar.gz)

### Steps to reproduce

- Load my save
- Press B to butcher/disassemble
- Press 2 to cut up a steel ballistic plate

It'll disassemble into synthetic fabric patches.

### Expected behavior

It should disassemble into some kind of metal.

### Versions and configuration

- OS:
OpenBSD 7.5 amd64
- Game Version:
71dcd14592a4a03cec283cf06fac676ac1af96ca
- Ingame language:
English.
- Mods loaded:
The unchanged defaults.

**Comment by RenechCDDA** [comment]
You're actually salvaging (butchering) it, not disassembling it. Not trying to be a jerk, but these are different actions accessed through the same menu.

Anyway this just shouldn't be salvageable. The materials are correct, the ability to turn it into a pile of synthetic fabric is not. Issue is also present on experimental.
