### ISSUE TITLE
Probably a better description of the recycler?

### ISSUE THREAD

**Issue by Mahoyomu** [CleverRaven/Cataclysm-DDA#76769]
### Is your feature request related to a problem? Please describe.

The recycler has a description of `Useless now that there's no power.`, But imo that just don't make sense, for it will still be unuseable regardless of powered or not. It also can't be powered, probably nor can it be powered and work in the future, for it's original functionality is not accepted. To those afk for a while and come back to play, they can waste some time on powering it.

### Solution you would like.

Probably "It's struction is totally broken, rusted and surely only just a pile of crap now." or "You simply won't understand how it worked, for you know it can only be operated by a few specifically trained people before the apocalypse."

### Additional context

If accepted, probably I can start a pr to fix it, after all it's just some doc work.

**Comment by RenechCDDA** [comment]
Feel free to submit a PR to change the description. This doesn't really need any discussion, so I'm just closing the issue. (As you can see we have a *lot* of open issues, so we'd prefer not to keep open issues that don't need to be open)

I recommend something like "It could be useful if you were selling scrap metal in specifically dimensioned industrial volumes, but the economy's gone to hell with the planet."
