### ISSUE TITLE
The `description` of use_action `effect_on_conditions` is not used

### ISSUE THREAD

**Issue by RedMisao** [CleverRaven/Cataclysm-DDA#76771]
### Describe the bug

The contents of the `description` field from use_action `effect_on_conditions` is not displayed or is ignored, thus not used.

### Attach save file

N/A

### Steps to reproduce

1. Make a survivor
2. Debug yourself a `nre_recorder` and a `saline_bag_250`
3. (Also debug yourself a medium battery because the NRE recorder requires it for use)
4. Press `a`ctivate
5. Notice how the NRE recorder activation text is "Activate item", while the small saline infusion kit text is "Infuse saline"
6. Try to activate either. Any text that follows up isn't the contents of each item's `description` field

### Expected behavior

I'm... not sure how this should behave.

Digging through the json I found that `saline_bag_250` uses `menu_text` to display "Infuse saline", whereas `nre_recorder` lacks the field, so it uses the default text. If this is intended, then `description` is redundant, as the printed text comes from any `message` from running the EoCs anyways.

However, if `menu_text` is the workaround for the description not displaying, then there is no space for the relatively long description text in the `a`ctivation window.

### Screenshots

![1](https://github.com/user-attachments/assets/e98d5681-e92a-4ffb-9322-f7800b1ce9db)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 0e6e222 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by cknight828** [comment]
It is used in Item Info.
![use_action_description](https://github.com/user-attachments/assets/bd875836-8f2c-4869-911b-021430a0ec96)

**Comment by RedMisao** [comment]
Ok, it's not an issue then.
