### ISSUE TITLE
Capability to use item transform actions with itemgroup IDs

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#76785]
### Is your feature request related to a problem? Please describe.

I have recently tried to have an item transformation action for a mod that'd turn into one of multiple targets. This is currently unsupported, and may only be possible (even with Guardian's help we couldn't get it to work without errors) with EoCs.

### Solution you would like.

 It'd be handy to have the item transformation actions support itemgroup IDs directly to save me a headache.

### Describe alternatives you have considered.

Suffer in EoC limbo

**Comment by mqrause** [comment]
It's definitely possible without EOCs. Transform actions already have members like `variant_type` or `container` that mirror the same functionality in item group modifiers. So there's potential to simplify the json a bit as well. Just the `iuse_transform::do_transform` needs a bit of a refactor to allow generating arbitrary itemgroups from an item, and of course if you really want to simplify the json that needs to be changed to item group syntax as well (but could be done by a script).
