### ISSUE TITLE
Crashing if sheathing machete from hands when trying to drive

### ISSUE THREAD

**Issue by Ixchael** [CleverRaven/Cataclysm-DDA#76791]
### Describe the bug

Game crashing, when i choose sheath to empty hands for driving. Maybe beacuse hands have severe damage

### Attach save file

[Кан-trimmed.tar.gz](https://github.com/user-attachments/files/17238063/-trimmed.tar.gz)

### Steps to reproduce

1. try to drive car with machete in hands
2. you cant drive while holding a machete, store it to nylon scabbard
3. crash

### Expected behavior

I expect, that machete just goes into inventory and i will be able to drive

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-10-02-0858 744251b [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17238158/crash.log)
[debug.log](https://github.com/user-attachments/files/17238159/debug.log)

**Comment by Night-Pryanik** [comment]
I can't open your save (it says there's an error in the archive for some reason), so I tried to reproduce it on fresh character.

I spawned a car, a machete, and a nylon scabbard. I wore scabbard and wielded machete. I sat on the driver's seat and tried to take control of the vehicle. I successfully turned on the engine with machete in my hands. I got no errors and no crash.

**Comment by Ixchael** [comment]
The reason, i cant drive with machete is because both hand is damaged to "|....". I just installed fresh cdda, made a new world, gave myself machete, damaged both hands to |.... and now i dont have free hand to hold machete so game ask me to remove it. And then even when i agree to drop it on floor (or seat) it crashing

**Comment by RenechCDDA** [comment]
> I can't open your save (it says there's an error in the archive for some reason), so I tried to reproduce it on fresh character.

Are you using winrar or anything besides 7-zip? They don't play nice with non-latin filenames by default. The saves in this issue are all saved with Cyrillic filenames/contents.

Anyway I can confirm the crash, and I re-exported it with a Latin name for ease of use.

[Machete_Drive-trimmed.tar.gz](https://github.com/user-attachments/files/17256161/Machete_Drive-trimmed.tar.gz)
