### ISSUE TITLE
Outfit gender is not saved in characte template

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#76808]
### Describe the bug

When you load a character template outfit is always set to male

### Attach save file

N/A

### Steps to reproduce

Make a character
Set outfit to female
Save template
Load template
See outfit being set to male

### Expected behavior

Outfit should be set to female

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: 26de5a1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Wilderness [wilderness] (custom mod, basically innawoods lite)
]

**Comment by RenechCDDA** [comment]
I've never used character templates so I don't have any idea how they work, but this patch should probably fix it:

```diff --git a/src/newcharacter.cpp b/src/newcharacter.cpp
index 326bd71b3a..c17e21ae30 100644
--- a/src/newcharacter.cpp
+++ b/src/newcharacter.cpp
@@ -4907,6 +4907,7 @@ void avatar::save_template( const std::string &name, pool_type pool )
         if( !random_start_location ) {
             jsout.member( "start_location", start_location );
         }
+        jsout.member( "outfit_gender", outfit );
         jsout.end_object();
 
         serialize( jsout );
@@ -4939,6 +4940,8 @@ bool avatar::load_template( const std::string &template_name, pool_type &pool )
             random_start_location = jobj.get_bool( "random_start_location", true );
             const std::string jobj_start_location = jobj.get_string( "start_location", "" );
 
+            outfit = jobj.get_bool( "outfit_gender", true );
+
             // get_scenario()->allowed_start( loc.ident() ) is checked once scenario loads in avatar::load()
             for( const class start_location &loc : start_locations::get_all() ) {
                 if( loc.id.str() == jobj_start_location ) {

```
