### ISSUE TITLE
Glowsticks die instantly

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#76800]
### Describe the bug

Glowsticks die a turn after they're lit

### Attach save file

[Manator-trimmed.tar.gz](https://github.com/user-attachments/files/17249639/Manator-trimmed.tar.gz)

### Steps to reproduce

Get glowstick
activate glowstick
it dies

### Expected behavior

glowsticks should last longer than a second

### Screenshots

![image](https://github.com/user-attachments/assets/b267f000-dd7f-4db7-89f1-a643ba96bee5)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: f61d1cd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm]
]

**Comment by omni-Var** [comment]
Candles are also exhibiting this behavior
![image](https://github.com/user-attachments/assets/442266f1-1368-499c-8b75-f362588f6c1a)

**Comment by IdleSol** [comment]
If I understand correctly, that's the problem:
- #75912

**Comment by AirRice** [comment]
Flares also exhibit this.

**Comment by JeveGreen** [comment]
The clay oil lamp filled with crude lamp oil does this too.
Basically, anything that isn't powered by battery charges, like the smartphone or reading light, all seem to be bugged.

**Comment by newbie-forever** [comment]
![image](https://github.com/user-attachments/assets/d66d82bc-2454-4440-86e6-c7db4680bd04)
Seems it's caused by switching from ammo_remaining into energy_remaining when calculating the remaining charge, in which energy_remaining only supports battery charge and does not support wax.
