### ISSUE TITLE
Tileset (soundpack) bug on Android 14

### ISSUE THREAD

**Issue by Kezper** [CleverRaven/Cataclysm-DDA#76815]
### Describe the bug

I installed a soundpack tiliset in Cataclysm stable on my cell phone, but it didn't work and a strange screen appeared with several words and red numbers.

### Attach save file

 .

### Steps to reproduce

1- I downloaded a soundpack (Master.soundpack) 2- Extract 3- I placed the files in the "sound" folder 4- I opened Cataclysm and a strange screen appears with the characters 5- I went to the settings and tried to change the "basic" sound pack, but it didn't work.

### Expected behavior

The sound pack should work normally

### Screenshots

![IMG_20241004_154219623](https://github.com/user-attachments/assets/e1c76435-5455-4344-a28d-188fd4e3835e)

### Versions and configuration

Cataclysm dda stable
 
Version 0.G 

Android 14

Phone: Moto g84

### Additional context

I also tried installing the "Undeadpeople" graphic Teliset, but it didn't work.

**Comment by Fris0uman** [comment]
Very likely that you copied the wrong thing. We're not making this soundpack so nothing we can do about it

**Comment by Kezper** [comment]
> Very likely that you copied the wrong thing. We're not making this soundpack so nothing we can do about it

I did the same procedure on a cell phone with Android 10 (32 bits). It worked perfectly. I think that on 64-bit platforms or recent Android it is not possible to install Tilisets. I don't know.
