### ISSUE TITLE
Can't harvest chunk of poultry meat and cook any food need chunk of poultry meat

### ISSUE THREAD

**Issue by HardcoreRanger** [CleverRaven/Cataclysm-DDA#76832]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/pull/70934 add chunk of poultry meat and scrap of poultry meat. 
But there is no way to harvest 'chunk of poultry meat'.
https://cdda-guide.nornagon.net/item/poultry

### Attach save file

N/A

### Steps to reproduce

1.Find a chicken, a duck, a goose or any common edible poultry.
2.Kill and harvest.
3.Only get some scrap of poultry meat. It means we can't craft fried chicken by harvest chicken.
![image](https://github.com/user-attachments/assets/cbd524d8-d3ed-485d-838f-be5a378bb81a)

### Expected behavior

Harvest chunk of poultry meat from chicken and other poultry.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: 65aca7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    No Monsters [Only_Wildlife]
]

**Comment by Nebnis** [comment]
Looks like all of the birds are now considered tiny for harvest which makes harvesting the big poultry meat impossible, since it only comes from small or big. Seems like an easy fix.
