### ISSUE TITLE
crash on autosave during lockpick

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#76844]
### Describe the bug

Game crashes when autosaving while trying to pick a lock

### Attach save file

[Manator-trimmed.tar.gz](https://github.com/user-attachments/files/17267473/Manator-trimmed.tar.gz)

### Steps to reproduce

turn on autosave, set it to save during lcokpick, game crashes

seems to have happened twice in a row, normally dont report if random crash in experimental

### Expected behavior

nocrash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: 65aca7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17267471/crash.log)
[debug.log](https://github.com/user-attachments/files/17267472/debug.log)

**Comment by mqrause** [comment]
Appears to be the same as #76742, unrelated to the activity but instead caused by AIM uistate serialization.
