### ISSUE TITLE
junk_allergen. Wrong name?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#76854]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/65aca7f154933aa62002d95d3e178a0fe8619452/data/json/vitamin.json#L575-L579

@GuardianDll Is there a mistake in the name of the allergen?

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

master

**Comment by GuardianDll** [comment]
Yes
