### ISSUE TITLE
Add `breaks_on_damage` and `breaks_on_attacking` booleans to effect JSON definitions

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#76875]
### Is your feature request related to a problem? Please describe.

I have a variety of ideas for spells and powers with powerful effects balanced by them not being able to be used in combat. To pick one example, a Hypnotism power that prevents the target from acting, but any damage snaps them out of it. At the moment, doing this requires four separate EoCs (`character_melee_attacks_character`, `character_melee_attacks_monster`, `character_ranged_attacks_character`, and `character_ranged_attacks_monster` ) and still doesn't cover all possibilities--none of those EoCs cover damaging supernatural powers, and none of them cover monsters attacking the target with the effect.

### Solution you would like.

 `breaks_on_damage` and `breaks_on_attacking` booleans to effects. The first means taking any damage will immediately remove the effect, and the second means that the creature with the effect attacking anyone will break the effect. This would allow for a spell that mesmerizes a target without allowing you to just sic summoned monsters (or even trained dogs) on them while they passively let themselves be ripped apart, and make it easier to make various stealth or invisibility effects that prevent attacking anything.

### Describe alternatives you have considered.

Lots of EoCs. 

Alternately, a `"breaks_on"` field that takes an array of possibilities ( `"movement": true`, `"spellcasting": false`, `"attacking": true`, `"conversation": false` ) would be more compact.

**Comment by GuardianDll** [comment]
does adding `monster_takes_damage` event fullfil it?

**Comment by Standing-Storm** [comment]
It would solve the edge cases listed above and would work with the idea I had that inspired this suggestion (a Mesmerize Telepathic power that stuns the target but breaks if the target is attacked). It would also let me give feral magi the Mageshield spell and have feral Photokinetics use Trick of the Light. 

Do the _takes_damage events have the attacker as the beta talker?

**Comment by GuardianDll** [comment]
Yes, they can have one
