### ISSUE TITLE
Candles immediately run out of energy

### ISSUE THREAD

**Issue by BanditPizza** [CleverRaven/Cataclysm-DDA#76880]
### Describe the bug

Any candle that I light immediately runs out of charges, even if full, getting destroyed. From testing without mods and only with cdda core content the problem persists

### Attach save file

[Waltman-trimmed.tar.gz](https://github.com/user-attachments/files/17275550/Waltman-trimmed.tar.gz)

### Steps to reproduce

1. take candle
2. light candle

### Expected behavior

candle lights up and produces a small radius of light at the cost of charges per turn

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-10-07-0342 128e941 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Dark Days Ahead: Lua [dda-lua],
    Dark Days Ahead: Lua (Traits) [dda-lua-traits],
    Dark Days Ahead: Lua (Fun) [dda-lua-fun],
    Xedra Evolved [xedra_evolved],
    Dark Days Ahead: Lua (Items) [dda-lua-items]
]

**Comment by harakka** [comment]
As an aside, you know none of these do anything, right?

Dark Days Ahead: Lua [dda-lua],
Dark Days Ahead: Lua (Traits) [dda-lua-traits],
Dark Days Ahead: Lua (Fun) [dda-lua-fun],
Dark Days Ahead: Lua (Items) [dda-lua-items]

**Comment by Vindicatory** [comment]
+ same issue
