### ISSUE TITLE
With many content mods on, average melee damage stat column is bloated

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#76907]
### Describe the bug

Most damage types aren't applicable to a weapon and are bloating the tab

### Attach save file

N/A

### Steps to reproduce

1. make a world with many content mods
2. look at any weapon's 'average melee damage' tab

### Expected behavior

display only damage types that aren't 0

### Screenshots

![image](https://github.com/user-attachments/assets/28f37e30-e6b8-4135-98b3-7ddcc451acab)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 24.0.7; Codename: Wynsdey; 
- Game Version: cdda-experimental-2024-10-04-0532 5f6f5e0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    No Hope [no_hope],
    Xedra Evolved [xedra_evolved],
    Megafauna [megafauna],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex]
]

**Comment by harakka** [comment]
Easy repro save
[mods-trimmed.tar.gz](https://github.com/user-attachments/files/17304312/mods-trimmed.tar.gz)
