### ISSUE TITLE
Headlight beam is being blocked with no apparent cause, depends on vehicle orientation

### ISSUE THREAD

**Issue by ildifa** [CleverRaven/Cataclysm-DDA#76909]
### Describe the bug

One of the headlights of my modified humvee seems to be blocked by some invisible vehicle part, but only when the vehicle is pointing in some directions (e.g. West).
In most other orientations the light is not blocked.
Dismantling parts which might be in the path of the lightbeam doesn't seem to have an effect, so I couldn't identify the reason for this blockage.

### Attach save file

[Springville-trimmed.tar.gz](https://github.com/user-attachments/files/17299147/Springville-trimmed.tar.gz)

### Steps to reproduce

1. Rotate the vehicle around.
2. See that the light is partially blocked (but only for the left-hand headlight), when pointing W,  W-SW, and E-NE.

### Expected behavior

I expected that the light occlusion is independent of the vehicle rotation (or at least rotationally simmetrical).
I expected that the source of the occlusion would be clearly identifiable.

### Screenshots

Lightbeam is not blocked:
![Screenshot_20241008_224115](https://github.com/user-attachments/assets/cf2e1261-3630-43d2-861f-7adf8a81c9bc)

Lightbeam is blocked:
![Screenshot_20241008_224002](https://github.com/user-attachments/assets/84dbb023-7462-4a0e-a6c7-f4ca88ee4708)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: openSUSE; Description: openSUSE Tumbleweed; Release: 20240927; Codename: n/a; 
- Game Version: cdda-experimental-2024-08-09-0203 61e0526 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by SurFlurer** [comment]
How did you install your 3 reinforced headlights? More specifically, in which direction did you install them?

**Comment by Psithief** [comment]
I've also had this issue, with the same directions too.

**Comment by SurFlurer** [comment]
I think this line encounters some rounding error:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f18d1e3c4a2ee14570bef188c811706f224b7963/src/lightmap.cpp#L1428

std::floor never returns 11, jumping from 10 to 12.

Changing that line to `    switch( static_cast<int>( std::floor( ( oangle + 0.0001_degrees ) / 45_degrees ) ) % 8 ) {` fixes this, but is dirty.

**Comment by SurFlurer** [comment]
This minimal program outputs 10 when it should be 11:
```
#include <iostream>
 // copy-paste these DDA headers
#include "units.h" 
#include "math_defines.h"
#include "unit_fwd.h"

int main()
{
    units::angle oangle = 45_degrees;
    oangle = oangle * 11;
    std::cout << static_cast<int>( std::floor( oangle / 45_degrees ) ) << std::endl;
}
```

**Comment by ildifa** [comment]
> How did you install your 3 reinforced headlights? More specifically, in which direction did you install them?
> 
> Based on some testing, I think #49183 introduced this behaviour.

The problem happens both when the headlights are installed pointing at 45° from straight forward (installing, then pressing up and then left/right) and when they point ~27° (installing, then pressing up x2 and then left/right).
