### ISSUE TITLE
RM13 combat armor turns off mid combat

### ISSUE THREAD

**Issue by strawberryx3c** [CleverRaven/Cataclysm-DDA#76926]
### Describe the bug

The RM13 power armor shuts down after a few turns in combat citing insufficient power, despite being fully charged.
![image](https://github.com/user-attachments/assets/32369508-aac5-4dc9-9151-a65fc2cb863a)

### Attach save file

[Hampton Bays-trimmed.tar.gz](https://github.com/user-attachments/files/17308476/Hampton.Bays-trimmed.tar.gz)

### Steps to reproduce

1. Verify RM13 power armor is on.
2. Engage for a few turns against the menacing Zomborg
3. The armor turns off.

### Expected behavior

I expected that the armor would stay on while it was charged and not told to turn off. It didn't. :(

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-10-09-0748 2cccbde [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key]
]

**Comment by DPavonis** [comment]
/confirm

I've both run into this bug myself in the wild and have independently replicated it with the provided save, though in more controlled tests I've had difficulty reliably replicating it.
