### ISSUE TITLE
Cataclysm logo overlays the Custom Character screen.

### ISSUE THREAD

**Issue by FeepingCreature** [CleverRaven/Cataclysm-DDA#76934]
### Describe the bug

When creating a custom character, the "Cataclysm Dark Days Ahead" ASCII logo remains drawn, making the menu unreadable. This also happens in the tiled version.

### Attach save file

N/A

### Steps to reproduce

1. Enter the menu to create a custom character

### Expected behavior

The menu overlay should only draw in the main menu. 

### Versions and configuration

- Linux
- Git c57abffb63f02dc4aa5cd8654fe00f96a918aa44 (cdda-experimental-2024-10-09-2117)

### Additional context

Bisect points at https://github.com/CleverRaven/Cataclysm-DDA/commit/78a391732ca30e1898c866963775395ce27c8f7e

**Comment by IliaGolubenko** [comment]
Haven't played for a while and today after re-installing experimental can confirm the loading screen isn't gone on character creating sheet.
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/65232b2f-b935-4ac5-b484-885b085a6511">

**Comment by ERRORCODE509** [comment]
Same issue on 77d6189.

![image](https://github.com/user-attachments/assets/b9be4f90-c5db-40f1-800e-6e633987aa82)

**Comment by RenechCDDA** [comment]
Well this is awkward. Clearly caused by my PR, but let's take a look at what happened

**Comment by ERRORCODE509** [comment]
853937d seems to be the last version without this issue, if that helps

**Comment by RenechCDDA** [comment]
I've got a patch that should work, but it's kind of ugly. `cata_path` is ultimately just a string, so it's not like there's a huge memory concern from shoving it into a static, but ehhh maybe there's a better way?

https://github.com/CleverRaven/Cataclysm-DDA/compare/master...RenechCDDA:Cataclysm-DDA:more_loadscreen_troubleshoot

**Comment by ERRORCODE509** [comment]
Seems to be fixed for me at least on 11886ea.
