### ISSUE TITLE
Crash when using the set of clothes.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#76931]
### Describe the bug

Interacting with the set of clothes is crashing the game, i can't really pinpoint why but it looks like removing the military rucksack or some items stop it

### Attach save file

[Broadrat-trimmed.tar.gz](https://github.com/user-attachments/files/17317062/Broadrat-trimmed.tar.gz)

### Steps to reproduce

1.Once you load, interact with the set of clothes north of your location by the oven.
2.Game crashes.

### Expected behavior

I expect to not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-09-26-0701 39eabf6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Lives - Extended [extra_lives_extended],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

### Additional context

I often noticed that my entire armor isn't being transferred to the set of clothes.

**Comment by Standing-Storm** [comment]
It's the backpack: #75543

**Comment by Nebnis** [comment]
I will close it then
