### ISSUE TITLE
Soldering iron bootstrap impossible without solder charges

### ISSUE THREAD

**Issue by FeepingCreature** [CleverRaven/Cataclysm-DDA#76945]
### Is your feature request related to a problem? Please describe.

Trying to do lab start, I can craft a soldering iron, I have electronics 3, solder, batteries, but I cannot create a portable soldering iron because that needs 5 solder charges, and I cannot see any other way to get appliance power without solder charges.

This is unreasonable because I have batteries, wire and duct tape. Soldered connections are nice to have but not actually necessary to connect a battery to a tool.

### Solution you would like.

The easiest solution is to drop the soldering charge requirement for crafting the portable soldering iron.

### Describe alternatives you have considered.

Alternately, with a makeshift battery compartment that substitutes duct tape for solder, the soldering iron could plug into that.

**Comment by kevingranade** [comment]
Just having a craftable handheld soldering iron is a stretch, and bootstrapping it with arbitrary bits missing is not a must have.

**Comment by FeepingCreature** [comment]
Idk, I feel if you're gonna have it, having it stopped by being unable to scotch tape wires to a battery is just very silly.

Ah well.

**Comment by FeepingCreature** [comment]
I have been told that it would help if I provided a source for people being able to build a battery driven soldering iron without using solder. So here is a Youtube video of somebody doing it I guess? https://www.youtube.com/watch?v=N7jVqSQ4aoE Note that the battery slot is not attached with solder.

**Comment by kevingranade** [comment]
That switches the bottleneck to essentially the nichrome wire, make that harvestable from toasters or electric kettles or something and you've got something.
That's essentially what the glowplug item in the soldering iron recipe is there for, but it has that alternative of e_waste which is kinda nonsensical.

**Comment by IdleSol** [comment]
Can't we get by with a fire and a screwdriver? An awl or any iron that fits the size and shape?
