### ISSUE TITLE
Weary penalty doesn't apply to hauling, actually speed ​​it up

### ISSUE THREAD

**Issue by HardcoreRanger** [CleverRaven/Cataclysm-DDA#76944]
### Describe the bug

According to the effect description, weary should give speed penalty to activity. Activity level of Hauling items is moderate, so it should get penalty at high weary level. But actually weary will just make hauling  faster. "Very Weary" is 2x fast, "Extremely Weary" is 4x faster, and so on.
![image](https://github.com/user-attachments/assets/419ac8ea-f35f-4db0-b816-de00c261342c)

### Attach save file

N/A

### Steps to reproduce

1.Find many items that you need much time to hauling.
2.Hauling them, and record how much time you spend. For me, hauling some logs will spend 40 seconds across a tile.
3.Get weary.
4.Than find the higher weary level you have, the faster you are. For me, 20 seconds a tile for "Very Weary", 10 seconds a tile for "Extremely Weary".

### Expected behavior

The numerator and denominator should be interchanged? Or it shouldn't have any effect on hauling, just like how it does on normal movement?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: f18d1e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Sky Island [skyisland],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    DinoMod [DinoMod],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Bombastic Perks [bombastic_perks],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife],
    No Monsters [Only_Wildlife]
]

**Comment by Brambor** [comment]
I will make a PR.
