### ISSUE TITLE
[MoM] Stop Concentration and some concentration spells not working.

### ISSUE THREAD

**Issue by TheoryInfinity** [CleverRaven/Cataclysm-DDA#76958]
### Describe the bug

Stop concentrating doesn't end active powers. 

Some concentration powers, such as Enhanced mobility, no longer have any effect.

### Attach save file

[Dundee-trimmed.tar.gz](https://github.com/user-attachments/files/17337568/Dundee-trimmed.tar.gz)

### Steps to reproduce

1: Create a world with Mind over Mater running build 2024-10-09-1847 or later.
2: Choose an awakened background with a concentration power.
3: Start concentration on a power.
4: Attempt to end the power using Stop Concentrating.

### Expected behavior

Concentration powers end when you Stop Concentrating and all concentration powers have an effect.

### Screenshots

![Concentration_Screenshot](https://github.com/user-attachments/assets/b83a202b-1826-4a97-9caa-1bc5270db154)

### Versions and configuration

- Cataclysm-DDA experimental build 2024-10-09-1847 or later

**Comment by Standing-Storm** [comment]
Confirmed.

I did some brief testing and it looks like the `run_eocs` EoC effect is broken when attempting to run more than one EoC. Every part of the powers work when I individually run each EoC in order, but trying to use the powers (which chain various EoCs together to produce the effects) doesn't work.

For example, from above with Enhance Mobility. Channeling enhance mobility has the following main effects:

>  { "run_eocs": [ "EOC_POWER_MAINTENANCE_PLUS_ONE", "EOC_BIOKIN_ENHANCE_MOBILITY_SWITCHER" ] },
>       { "u_add_effect": "effect_biokin_enhance_mobility", "duration": "PERMANENT" },

The effect is added just fine, as visible in the screenshot above. But no mutation is added (which is what the `EOC_BIOKIN_ENHANCE_MOBILITY_SWITCHER` EoC does, as [visible here](https://github.com/CleverRaven/Cataclysm-DDA/blob/11886ea0ff57064e63e901c4d03afbb479fc7f3c/data/mods/MindOverMatter/powers/biokinesis_concentration_eocs.json#L356)): 

![Untitled2](https://github.com/user-attachments/assets/263ba16c-83ab-437f-bd35-332fc8a76671)

However, the first EoC above, `EOC_POWER_MAINTENANCE_PLUS_ONE`, does work, as you can see by the incrementing of the maintained powers counter: 

![Untitled2](https://github.com/user-attachments/assets/e7160131-e289-4467-8bdb-11b148614139)

And indeed, if I go into the JSON and switch the line to ` { "run_eocs": [ "EOC_BIOKIN_ENHANCE_MOBILITY_SWITCHER", "EOC_POWER_MAINTENANCE_PLUS_ONE" ] }`, now I get the hidden mutation and encumbrance is properly reduced:

![Untitled2](https://github.com/user-attachments/assets/c7c086de-9c88-453c-a83f-733514feaa9c)

...but when I check my maintained powers vitamin, it's zero.

This is why Stop Concentration isn't working--mechanically it just calls the cancellation EoCs for every single maintained power. The first power it checks is Overcome Pain, and indeed if I channel that and then stop concentrating, Overcome Pain goes away.
