### ISSUE TITLE
Exiting game with CTRL+C leaves console in mouse tracking mode

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#77011]
### Describe the bug

When playing in curses mode, I can press ctrl+c to get the "Really Quit?" prompt. If I select Yes then the game exits, putting me back in the terminal where I started the game. Now if I move my mouse or click the mouse buttons, I see escape codes filling the command line.

### Attach save file

N/A

### Steps to reproduce

1. Launch game
2. Ctrl+C
3. Y, enter
4. move mouse

### Expected behavior

No effect from moving the mouse.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: 94370789a7 [64-bit]
- Graphics Version: Curses
- Game Language: System language [] (edit: English)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This problem does not occur when exiting the game normally from the main menu.

**Comment by NetSysFire** [comment]
Might be a regression? #73049

I feel like this was reported in the past, too as it is very much a known issue, but I can not find a duplicate right now

**Comment by sparr** [comment]
I also get the "newlines without carriage returns" behavior on [very early] crashes currently, but on a black screen since I haven't made it to rendering anything yet. It's what stops me from getting good crash reports for #77001
