### ISSUE TITLE
Creating New Character Deletes Existing

### ISSUE THREAD

**Issue by ERRORCODE509** [CleverRaven/Cataclysm-DDA#77025]
### Describe the bug

Creating a second character on a world deletes the existing one.

### Attach save file

N/A

### Steps to reproduce

1. Make a character
2. Save and return to menu
3. Attempt to create second character on the same world
4. Save and return to menu
5. See that only the second character exists

### Expected behavior

The warning when creating a second character implies that doing so will cause issues, but says nothing about deleting the existing character on the world. If this is the intended behavior, the warning should be edited to reflect this.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: f85808d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Useful Helicopters [useful_helicopters],
    Innawood [innawood]
]

### Additional context

![image](https://github.com/user-attachments/assets/cfacd9d7-afbf-4217-9799-85b8064a9af2)

**Comment by ZhilkinSerg** [comment]
Do you use the same name for a new character as the existing one?

**Comment by ERRORCODE509** [comment]
Yeah, that's exactly what it was. Didn't even cross my mind. Apologies.

**Comment by ZhilkinSerg** [comment]
It might make sense to add a notification about existing character with the same name.
