### ISSUE TITLE
There is no way to craft firefly terrarium

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#77053]
### Is your feature request related to a problem? Please describe.

In game we have item as firefly terrarium, which you can also find in rabbit breeder npc house or in debug menu. In innawood we dont have free light source, except sun too
You cant also dismantle this terrarium 

### Solution you would like.

Make it possible to craft firefly terrarium by simple recipe
Aquarium + wooden pet carrier(firefly)/(other variation of pet container) + dirt(for plants as food for firefly. Terrarium - terra - ground) = fire fly terrarium + empty pet container
make it as simple and fragile furniture

**Comment by PatrikLundell** [comment]
I assumed it was a unique item crafted by this (not actually: he's spawned multiple times) unique individual, and thus not intended to be possible to reproduce.

**Comment by Karol1223** [comment]
The firefly terrarium is a WIP piece of content that's intended to be currently unobtainable.
