### ISSUE TITLE
[MoM/Aftershock] Synaptic blast learned in a moment

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#77068]
### Describe the bug

When you try to learn synaptic blast with both mods it's learning in a second. 
When you have only MoM there are no bugs.

### Attach save file

[sss-trimmed.tar.gz](https://github.com/user-attachments/files/17380733/sss-trimmed.tar.gz)

### Steps to reproduce

1. Make world with both mods
2. Make telepath and learn all recipes
3. Debug items for learning synaptic blast
4. Learn it

### Expected behavior

Synaptic blast learn like other powers

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.4.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-09-28-2243 de3f2b6 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.4%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Разум над материей [mindovermatter],
    Aftershock [aftershock],
    Отключить потребности у НПС [no_npc_food],
    Медленный рост фунгалоидов [no_fungal_growth],
    Портальные штормы игнорируют НПС [personal_portal_storms]
]

**Comment by Standing-Storm** [comment]
> Debug items for learning synaptic blast

There is no current infrastructure for learning new powers in Aftershock because the intended way to do it (finding alien devices) hasn't been implemented yet.
