### ISSUE TITLE
[XE] researching blood gifts as a tier 4 vampire shouldn't give tier 5 powers.

### ISSUE THREAD

**Issue by SariusSkelrets** [CleverRaven/Cataclysm-DDA#77076]
### Is your feature request related to a problem? Please describe.

While I was waiting to get enough storms to reach the fifth tier of vampirism, I passed the time by using the research blood gift recipe.

I then got Distillate the Inner Blood, which is a tier 5 power, as a tier 4 vampire.

I tested and it's possible to get all tier 5 powers that way without being a tier 5 vampire. The research EOC doesn't include a check for tier 5 so it can give said powers.

### Solution you would like.

Making tier 4 vampires unable to get tier 5 powers, so those who want the highest-tier vampiric powers will do the related quest and become tier 5 to get access to tier 5 powers.

Telling tier 4 vampires that they can't get such powers for now if they roll that high would also be a good idea.

**Comment by Standing-Storm** [comment]
When I wrote that EoC I wanted to let you get higher-tier powers sometimes if you're lucky, but also when I wrote it there were no level 5 powers (so rolling that high would just dump you down to 4 anyway). It'd be relatively simple to kick you down to level 4 or below if you're not tier 5.
