### ISSUE TITLE
Talking and Mom related bug

### ISSUE THREAD

**Issue by Lorindel** [CleverRaven/Cataclysm-DDA#77085]
### Describe the bug

Dunno, crash window in screenshots

### Attach save file

[Arcanum-trimmed.tar.gz](https://github.com/user-attachments/files/17391761/Arcanum-trimmed.tar.gz)

### Steps to reproduce

I started a game evac start, see alien grass everywere and couple veiled butterfly. And while scouting around get this crash window

### Expected behavior

Crash should not

### Screenshots

![изображение](https://github.com/user-attachments/assets/50effbd2-520b-4c28-8259-d77d3ea3cbc6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: cdda-experimental-2024-10-16-0438 8c9ca7a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Magiclysm [magiclysm],
    Mana Cores [manacores],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/17391825/debug.log)
[crash.log](https://github.com/user-attachments/files/17391832/crash.log)

**Comment by Standing-Storm** [comment]
I may have a solution to this but Sukkot starts tonight so it might be a few days until I can test it.

**Comment by Ichthysdekilt** [comment]
Can confirm, I'm seeing it as well. Possibly related to the MoM psi spell Spark Sight.

**Comment by Standing-Storm** [comment]
Cannot load the provided save due to out of repo mods that I don't have.

However, I went in and spawned an alien meadow and waited 24 hours in it with the fix. No errors.
