### ISSUE TITLE
Bad tag (parse_tags) error related to 'npctalk.cpp'

### ISSUE THREAD

**Issue by dik1337** [CleverRaven/Cataclysm-DDA#77080]
### Describe the bug

I'm receiving this error message (or a variation) when entering NPC dialogue screens that have a "goodbye" message option:

 DEBUG    : Bad tag.  '<lets_go>' (0 - 8)

 FUNCTION : parse_tags
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 2459
 VERSION  : b7cfa5d

The "goodbye" option message text is replaced with "????" It doesn't appear to be game breaking otherwise.

### Attach save file

[Groveland.zip](https://github.com/user-attachments/files/17388887/Groveland.zip)

### Steps to reproduce

1. Start existing player save (World - Groveland, only character).
2. Enter dialogue with the NPC follower (should be near player).
3. Navigate to message screen with "goodbye" option.

### Expected behavior

I expected this to not to occur.

### Screenshots

![cdda_npctalk_error1](https://github.com/user-attachments/assets/d93c0baa-904b-4d8d-a809-a5ade0ec31e0)
![cdda_npctalk_error2](https://github.com/user-attachments/assets/d36268f0-f98a-476a-87dd-ae94b24a8be7)

### Versions and configuration

OS: Windows 10
Game Version: b7cfa5d
Installed using Catapult launcher. 
Only stock mods installed.
Otopack soundpack installed.

### Additional context

[debug.log](https://github.com/user-attachments/files/17388945/debug.log)

**Comment by GuardianDll** [comment]
Resolved by #76102
