### ISSUE TITLE
Using `math` in the `relic_data` field causes an error

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77160]
### Describe the bug

```
 DEBUG    : (json-error)
Json error: data/mods/XXX/test.json:31:52: Invalid or misplaced field name "add" in JSON data

          "has": "WORN",
          "condition": "ALWAYS",
          "values": [ { "value": "STRENGTH", "add": { "math": [ "1 + 1" ] } } ]
                                                  ▲▲▲
        }
      ]



 FUNCTION : void JsonObject::error_skipped_members(const std::vector<long long unsigned int>&) const
 FILE     : src/flexbuffer_json.cpp
 LINE     : 347
 VERSION  : cdda-experimental-2024-10-18-0902 77e1ead
```

According to the documentation:

https://github.com/CleverRaven/Cataclysm-DDA/blob/ac689beccf2f0c60457ddfef5a6c62ebf1d633b8/doc/MAGIC.md?plain=1#L730-L740

It should be working.

Mod XXX content:
```
[
  {
    "id": "TEST_jumpsuit_1",
    "type": "ARMOR",
    "category": "armor",
    "name": { "str": "TEST jumpsuit 1" },
    "description": "test",
    "copy-from": "survivor_jumpsuit",
    "relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": "ALWAYS",
          "values": [ { "value": "STRENGTH", "add": 2 } ]
        }
      ]
    }
  },
  {
    "id": "TEST_jumpsuit_2",
    "type": "ARMOR",
    "category": "armor",
    "name": { "str": "TEST jumpsuit 2" },
    "description": "test",
    "copy-from": "survivor_jumpsuit",
    "relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": "ALWAYS",
          "values": [ { "value": "STRENGTH", "add": { "math": [ "1 + 1" ] } } ]
        }
      ]
    }
  }
]
```
TEST jumpsuit 1 all works. TEST jumpsuit 2 causes an error at the stage of loading the save.

### Attach save file

[test.json](https://github.com/user-attachments/files/17445177/test.json)

### Steps to reproduce

n/a

### Expected behavior

1. The possibility of using math
2. Or clarification of documentation if it cannot be used

### Versions and configuration

cdda-windows-tiles-x64-2024-10-18-0902

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-10-18-0902 77e1ead [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92.2%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    XXX [XXX]
]

### Additional context

How to set two conditions in the `condition` field: "ALWAYS" AND "u_hp(`torso` > 0)"
Cause:
```
  "condition": {
      "and": [ 
          "ALWAYS",
          { "math": [ "u_hp('torso')", ">", "0"] }
      ]
  },
```
it doesn't work.

**Comment by GuardianDll** [comment]
`relic_data` seems to not support math notation directly, move enchantment to it's own field, and use it like 
`"relic_data": { "passive_effects": [ { "id": "ench_armor_spirit" } ] },`

\> How to set two conditions in the condition field: "ALWAYS" AND "u_hp(torso > 0)"
If you already have second condition, it already implies it is not ALWAYS
`"condition": { "math": [ "u_hp('torso')", ">", "0"] },`

**Comment by IdleSol** [comment]
> seems to not support math notation directly, move enchantment to it's own field, and use it like

I disagree, unless you're talking about the `values` field. Because:

```
    "relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": { "math": [ "u_hp('torso')", ">", "50"] },
          "values": [ { "value": "STRENGTH", "add": 2 } ]
        }
      ]
    },
```
It works fine. But it doesn't work when the `math` is in the `add` field.

>If you have second condition, it already implies it is not ALWAYS

ALWAYS used for example only. Let it be ACTIVE.

**Comment by IdleSol** [comment]
>i am talking specifically about relic_data

Maybe I'm misunderstanding.

We have a field `relic_data`. There is a `condition` inside it, which can contain `math`. And there is `values`, which has `add` inside and cannot process `math`.

And we also have the option to use a different form of record where `id` is used instead of conditions and values.

But for a code handler, is there any difference between these options?

```
"relic_data": { "passive_effects": [ { "id": "some_ench" } ] }
```
`+`
```
  {
    "type": "enchantment",
    "id": "some_ench",
    "has": "WORN",
    "condition": "ACTIVE",
    "values": [ { "value": "STRENGTH", "add": { "math": [ "1 + 1" ] } } ]
  }
```
`=`
```
"relic_data": { "passive_effects": [ { "has": "WORN", "condition": "ACTIVE", "values": [ { "value": "STRENGTH", "add": { "math": [ "1 + 1" ] } } ] } ] }
```

But aren't these forms supposed to be equivalent by rule? (And processed by the same function?).

And we end up with them having different processing. If you use `"id": "some_ench"`. Everything works. But if you substitute it directly, it doesn't.
---
>"condition": { "and": [ "ACTIVE", { "math": [ "u_hp('torso')", ">", "0"] } ] },

It doesn't work. If you want to check it out, here's the code:
```
[
  {
    "id": "TEST_jumpsuit_off",
    "type": "TOOL_ARMOR",
    "category": "armor",
    "name": { "str": "TEST jumpsuit (off)" },
    "description": "test",
    "copy-from": "survivor_jumpsuit",
    "relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": { "and": [ "ACTIVE", { "math": [ "u_hp('torso')", ">", "0"] } ] },
          "values": [ { "value": "STRENGTH", "add": 2 } ]
        }
      ]
    },
    "use_action": {
      "type": "transform",
      "menu_text": "Turn on",
      "target": "TEST_jumpsuit_on",
      "active": true,
      "need_charges": 1,
      "need_charges_msg": "The charger's battery is empty.",
      "moves": 100
      },
    "pocket_data": [
      { "pocket_type": "MAGAZINE", "rigid": true, "ammo_restriction": { "battery": 64 } }
    ]
  },
  {
    "id": "TEST_jumpsuit_on",
    "type": "TOOL_ARMOR",
    "category": "armor",
    "name": { "str": "TEST jumpsuit (on)" },
    "copy-from": "TEST_jumpsuit_off",
    "revert_to": "TEST_jumpsuit_off",
    "power_draw": "36 W",
    "use_action": {
      "type": "transform",
      "ammo_scale": 0,
      "menu_text": "Turn off",
      "target": "TEST_jumpsuit_off",
      "moves": 100
    }
  }
]
```

**Comment by RedMisao** [comment]
If I may:
1. `relic_data` doesn't process `math` inside it. It may be an issue in itself, although GuardianDll has shown you the workaround (if it can be called that) of referencing a `"type": "enchantment"` object.
I'm phrasing it like this because there are other `X_data` fields (i.e. `ammo_data`, `fuel_data`, `spell_data`) that allow the use of `"type": "AAA"` data and values into `"type": "BBB"` objects. Their use is not 100% consistent and doesn't allow porting everything 1:1.
2. `ALWAYS`, `ACTIVE` and so on are hardcoded conditions. I don't think you can combine those. Regardless, your best bet is to apply two enchantments. One to the active object, and another (or none) to the inactive object. You can add several enchantments with different conditions each:
```json
    "enchantments": [ 
      { 
        "condition": "ALWAYS", 
        "values": [ 
          { "value": "ATTACK_SPEED", "multiply": 0.1 },
          { "value": "MOVE_COST", "multiply": -0.1 }
        ]
      },
      { 
        "condition": { "not": "u_has_weapon" },
        "values": [ 
          { "value": "ITEM_DAMAGE_BASH", "add": { "math": [ "( max( u_skill('unarmed') * 2, u_skill('melee') * 1.5 ) * 2/3 )" ] } }
        ] 
      },
      { 
        "condition": "u_has_weapon",
        "values": [ 
          { "value": "ITEM_DAMAGE_BASH", "add": { "math": [ "( max( u_skill('unarmed') * 2, u_skill('melee') * 1.5 ) * 1/6 )" ] } }
        ] 
      }
    ],
```

**Comment by IdleSol** [comment]
Thank you.
