### ISSUE TITLE
Problem with search bar in menu windows. Variant of "temporary" solution

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77186]
### Is your feature request related to a problem? Please describe.

![3](https://github.com/user-attachments/assets/cda8eaec-97ae-4b22-9c3d-4bbe887b7bcb)

It's hard to search for something when you can't see what you're typing. Add to this the ability to change the keyboard layout. This is especially true if the menu window occupies the whole or most part of the screen.

And this problem is more than 2 months old. I assume that there are some difficulties in solving it. That's why I would like to suggest that you consider a solution. Perhaps temporary or perhaps permanent, if you like it. (And if someone does this.)

### Solution you would like.

And I'll start with the screenshots:
![2](https://github.com/user-attachments/assets/0839bf8f-2734-4df6-a1d1-e5ed97e49acf)
![4](https://github.com/user-attachments/assets/f6b7db44-7820-44b3-a86b-b5942d979ca4)

Instead of calling a new window. Let's place it right along with the main window.

For "small" windows, it can be placed at the bottom. And for "large" windows, it can occupy part of the window.

*A little clarification. I don't know the correct terminology. To me, it's all windows. Perhaps the word frame is appropriate here?*

**Comment by Brambor** [comment]
I think the problems are that the search window relies on other windows that haven't been migrated to ImGui yet.

This issue is mentioned here:
 - #75661
 - #75676

**Comment by Brambor** [comment]
- Resolved by #75676.
 - The search is in the middle but I still call this complete rather than closed.
