### ISSUE TITLE
keffiyeh makes head colder

### ISSUE THREAD

**Issue by Bullk9ng** [CleverRaven/Cataclysm-DDA#77180]
### Describe the bug

When wearing a keffiyeh the head temperature actually drops.

### Attach save file

[Smiles-World-trimmed.tar.gz](https://github.com/user-attachments/files/17448056/Smiles-World-trimmed.tar.gz)

### Steps to reproduce

wear keffiyeh

### Expected behavior

Head temperature increase. Keffiyeh should have 5 warmth?

### Screenshots

![head-no-keffiyeh](https://github.com/user-attachments/assets/59e31b8d-8c6e-43d4-889a-cde88db766c4)
![head-with-keffiyeh](https://github.com/user-attachments/assets/eec976e5-5018-4cc3-ae63-63b211792bdb)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: e9f130b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Dacendeth** [comment]
the keefiyah is just preventing the emergency jackets hood effect from keeping you warm, so you see a loss in protection

**Comment by Bullk9ng** [comment]
aaaaahh! okay! thanks @Dacendeth!
