### ISSUE TITLE
Debug menu. Add ability to interact with radiation

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77190]
### Is your feature request related to a problem? Please describe.

This will increase convenience when debugging or testing anything related to radiation.

### Solution you would like.

1. Ability to check and change the radiation level of a character or NPC
2. Ability to change the radiation value for tiles
3. (Optional). Change the way radiation is displayed, for large values. Or possibility to see the value in a certain tile.
4. (Optional) Ability to check and change the value of radiation for items (optional, limit to items that the character holds in his hands)

**Comment by RenechCDDA** [comment]
When would you find this useful for testing?

**Comment by IdleSol** [comment]
Checking flags and their interactions. For example, three things with RAD_RESIST... the final radiation level is 40 more than one thing with RAD_RESIST. And I have no idea if this is due to some randomness, my measurement error and or a problem in the calculation. Because I'm forced to log out and back into the game, for checking.

Drug check. Set the level, check the output rate. Added a cure, checked again.

What's the radiation level here? (solved by maximizing proximity)
![1](https://github.com/user-attachments/assets/0fdde236-376f-4938-bb8c-41949f82deba)
