### ISSUE TITLE
Cant increase electronics in Innawood more than 2

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#77205]
### Describe the bug

Cant increase electronics in Innawood more than 2, all recipes with 2 or higher difficulty need soldering iron with charges. You cant craft car clay battery, because you need lvl 3 electronic for it
I also cant find dry batteries and reason, why they was removed. There is no dry batteries, after I debug learned all recipes or trying to find it via spawn item menu

### Attach save file

N/A

### Steps to reproduce

Create Innawood character, make all skills to 10, only electronic to 2, see, that you are locked at second level of this profession

### Expected behavior

Be able to learn electronic more than 2

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 74e77cc [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92,2%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood]
]

**Comment by Fris0uman** [comment]
I don't think it's a bug, see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/innawood/readme.md 
`The goal is to make it possible to get to at least around late medieval technology on your own.` doesn't really need electronic to get to medieval technologie

**Comment by KHeket** [comment]
> I don't think it's a bug, see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/innawood/readme.md `The goal is to make it possible to get to at least around late medieval technology on your own.` doesn't really need electronic to get to medieval technologie

But we have soldering iron special for innawood #77097
And we have clay car battery special for innawood too
And theoretically, because of skill rust boost I can lvl up electronics to 3 too, but it will consume lot of time
And previously there was dry batteries for innawood too

**Comment by Kantonine** [comment]
Honestly, that is a good point, especially about dry batteries (Maybe to have it needing a vehicle battery mod to fit? and instead of using the original Light -> Medium -> Heavy (or rather, hand tool battery), make it more like motorbike batteries? As for the technology bit, I *did* have a few ideas:

Allowing leather hoses to act as a alternative to rubber hoses for a fair amount of recipes (That doesnt need elasticity), so that masks, mounted kitchen and workshops, yadda yadda yadda

Possibly giving the gutskin parka a use in the skin_ppe grouping, as it would likely be good enough to block skin irritants,

Sunglasses Recipe (No transition, bifocal, reading, or corrective glasses.... maaaaaaaybe stylish glasses, for the stylish cavemen, women, and peasantry) 12th Century China had tinted glasses, that _did_ protect the eyes from the sun.

Actually, tbf these *could* be in mainline.

**Comment by kevingranade** [comment]
Random overreaches past the stated goal of the mod don't invalidate the stated goal.  If anything the solution is pruning those exceptions rather than ratcheting up the achievable technology in the rest of the mod.

**Comment by KHeket** [comment]
@Light-Wave can you check pls? because if lvl up electronic in Innawood more than 3 is forbidden by the goal of the mod, as Kevin said, so I dont understand the propose of adding clay car battery and #77097 pr, which you approved as a maintainer of Innawood, because in this pr clay car battery became craftable by heat, but still need electronic lvl 3, what is forbidden
I cant understand this logic, and also a reason for adding and then removing dry batteries?

**Comment by Light-Wave** [comment]
Right, the intention is for Electronics to be trainable higher than level 2 in Innawood. I think the readme was written before that was changed.
I'm not sure why dry batteries were removed, wasn't my doing.
@KHeket do you think changing the level requirement of clay batteries to 2 would solve this issue? If so I'll make a pull request implementing that change.

**Comment by KHeket** [comment]
> do you think changing the level requirement of clay batteries to 2 would solve this issue?

Yes, it will solve the issue, because you can craft all components of clay battery in Innawood. But may be in this case also add required lvl 3 or 4 of chemistry to its recipe? Because to understand, that lead and sulfuric acid can provide electricity because of chemical reaction - you need knowledge in chemistry

**Comment by Light-Wave** [comment]
All right, fixes in #77352 on their way. Thanks for alerting me to this issue. :thumbsup:
