### ISSUE TITLE
Raw butter has inconsistent calories when crafted

### ISSUE THREAD

**Issue by Sirbab** [CleverRaven/Cataclysm-DDA#77224]
### Describe the bug

When one looks at raw butter (the crafted variant) the calories are wildly inconsistent with commercial butter "butter", the code entry for raw_butter as well as online sources.
For reference, "butter" has 101 calories per unit, and "raw butter" in code has 110 (due to differences in milkfat I presume)
If one crafts raw butter with a churn, they get raw butter that has 24 calories per unit, and if one uses the shake recipe, they get raw butter that has 44 calories per unit.  
My suspicion is that this is down to how many charges are produced per craft attempt since calories in has to equal calories out in most recipes.
After discussion in discord with Maddremor, and some other contributors, I see several solutions that I'm going to pose.
1: Make crafted butter create the commercial variant.  This also entails removing or deprecating raw_butter, and either using nutrient_override or adjusting ratios to align the calorie density and total produced calories to align more similarly with the ~101 calories per 14g of butter.
2: Keep raw butter, but Change the ratio of input/output of heavy cream to raw butter on these to make them align at least similarly to the HHG/Code result for calories. Or again, using nutrient_override since the two methods of making it *probably* don't warrant the nutrient inheritance since you can only make it from raw milk, and the only difference is that you're shaking the cream as opposed to churning it as far as I can tell.  With this one, I would suggest renaming raw butter to homemade butter, as raw implies a processed or cooked variant, and also that raw also technically describes commercial butter too.

I am happy to enact either of these solutions, I just want to encourage some discussion on the preferred solution. 
As it stands, raw butter is usable in 88 recipes, while butter is used in 93, so I don't think there really warrants the distinction, but I concede I may be speaking out of ignorance which is part of why I'm making this issue.

### Attach save file

N/A, Trivial to reproduce/apparent in code

### Steps to reproduce

1: Look at hhg or debug mode entry for raw butter and butter.
2: Spawn some milk cream jars, and craft the two variants of raw butter, and observe the calories produced.

### Expected behavior

I expect that raw butter should be at least vaguely close to what the FDA defines as butter, being ~80% milkfat by mass.  This 24 calorie per 14g business makes me imagine watery butter, which makes me sad.

### Screenshots

![image](https://github.com/user-attachments/assets/f222954c-f0af-4379-964a-44ea7bc57f90)
![image](https://github.com/user-attachments/assets/1858a249-d310-4061-a44c-fc9c07e88bff)
![image](https://github.com/user-attachments/assets/ea50d9d4-eb0a-49b0-91f6-1b459affdd4d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: e9f130b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

Discord discussion can be found around the following message links
https://discord.com/channels/598523535169945603/598523535169945607/1297846786261778477
https://discord.com/channels/598523535169945603/598523535169945607/1297847155276386376
https://discord.com/channels/598523535169945603/598523535169945607/1297848298081878026

**Comment by IdleSol** [comment]
I've been down the whole raw butter-making chain. Starting with milking the cow.

```mermaid
graph TD

1(raw milk) -->|x12| 2(rising cream jar) -->|x1, +6h|3(milk cream jar) -->|x1|4(heavy cream x5 + buttermilk x7)
4 --> |x3 heavy cream|5(raw butter v1 x33 + buttermilk x3)
4 --> |x5 heavy cream|6(raw butter v2 x99) 
```



<table>
    <thead>
        <tr>
            <th>Step N</th>
            <th>Name of component</th>
            <th>Calories, kcal</th>
            <th>quantity</th>
            <th colspan="2">Total, kcal</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td align="center">1</td>
            <td align="center">raw milk</td>
            <td align="center">132</td>
            <td align="center">x12</td>
            <td align="center" colspan="2">1584</td>
        </tr>
        <tr>
            <td align="center">2</td>
            <td align="center">rising cream jar</td>
            <td align="center">-</td>
            <td align="center">-</td>
            <td align="center" colspan="2">-</td>
        </tr>
        <tr>
            <td align="center">3</td>
            <td align="center">milk cream jar</td>
            <td align="center">-</td>
            <td align="center">-</td>
            <td align="center" colspan="2">-</td>
        </tr>
        <tr>
            <td align="center" rowspan="2">4</td>
            <td align="center">heavy cream</td>
            <td align="center">490</td>
            <td align="center">x5</td>
            <td align="center">2450</td>
            <td align="center" rowspan="2">3577</td>
        </tr>
        <tr>
            <td align="center">buttermilk</td>
            <td align="center">161</td>
            <td align="center">x7</td>
            <td align="center">1127</td>
        </tr>
        <tr>
            <td align="center" rowspan="3">5a</td>
            <td align="center" colspan="5">heavy cream x3 = 1470</td>
        </tr>
        <tr>
            <td align="center">raw butter v1</td>
            <td align="center">44.5 (note1)</td>
            <td align="center">x33</td>
            <td align="center">1468.5</td>
            <td align="center" rowspan="2">1951.5</td>
        </tr>
        <tr>
            <td align="center">buttermilk</td>
            <td align="center">161</td>
            <td align="center">x3</td>
            <td align="center">483</td>
        </tr>
        <tr>
            <td align="center" rowspan="2">5b</td>
            <td align="center" colspan="5">heavy cream x5 = 2450</td>
        </tr>
        <tr>
            <td align="center">raw butter v2</td>
            <td align="center">24.7 (note 2)</td>
            <td align="center">x99</td>
            <td align="center" colspan="2">2445.3</td>
        </tr>
    </tbody>
</table>

Note 1. The value is calculated from the sum of component calories divided by 33. Or `1470 / 33 = 44.54(54)`
Note 2. The value is calculated from the sum of the component calories divided by 99. Or `2450 / 99 = 24.74(74)`

*Steps 1-4*. As you can see from milk, calorie 1584 kcal, we got products with total calories equal to 3577 kcal. I don't understand anything about this, so I don't know if this is possible.

*Step 5a*. The recipe does not take into account the calories of the additional products. Therefore, we end up with more calories than the original ingredients contain. I don't know how accurate this is.

*Step 5b*. This is the same if you don't account for rounding errors.

**Comment by IdleSol** [comment]
If we need the calorie content of the product to not exceed the calorie content of the ingredients, then:

<table>
    <thead>
        <tr>
            <th>Step N</th>
            <th>Name of component</th>
            <th>Calories, kcal</th>
            <th>quantity</th>
            <th colspan="2">Total, kcal</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td align="center">1</td>
            <td align="center">raw milk</td>
            <td align="center">132</td>
            <td align="center">x10</td>
            <td align="center" colspan="2">1320</td>
        </tr>
        <tr>
            <td align="center">2</td>
            <td align="center">rising cream jar</td>
            <td align="center">-</td>
            <td align="center">-</td>
            <td align="center" colspan="2">-</td>
        </tr>
        <tr>
            <td align="center">3</td>
            <td align="center">milk cream jar</td>
            <td align="center">-</td>
            <td align="center">-</td>
            <td align="center" colspan="2">-</td>
        </tr>
        <tr>
            <td align="center" rowspan="2">4</td>
            <td align="center">heavy cream</td>
            <td align="center">490</td>
            <td align="center">x2</td>
            <td align="center">980</td>
            <td align="center" rowspan="2">1302</td>
        </tr>
        <tr>
            <td align="center">buttermilk</td>
            <td align="center">161</td>
            <td align="center">x2</td>
            <td align="center">322</td>
        </tr>
        <tr>
            <td align="center" rowspan="3">5a</td>
            <td align="center" colspan="5">heavy cream x3 = 1470</td>
        </tr>
        <tr>
            <td align="center">raw butter v1</td>
            <td align="center">110 (note1)</td>
            <td align="center">x9</td>
            <td align="center">990</td>
            <td align="center" rowspan="2">1473</td>
        </tr>
        <tr>
            <td align="center">buttermilk</td>
            <td align="center">161</td>
            <td align="center">x3</td>
            <td align="center">483</td>
        </tr>
        <tr>
            <td align="center" rowspan="2">5b</td>
            <td align="center" colspan="5">heavy cream x5 = 2450</td>
        </tr>
        <tr>
            <td align="center">raw butter v2</td>
            <td align="center">110 (note 2)</td>
            <td align="center">x22</td>
            <td align="center" colspan="2">2420</td>
        </tr>
    </tbody>
</table>

But that's tinkering with the results. My quick internet search, says we have the wrong calorie values for milk, buttermilk and heavy cream.

**Comment by AudBobb** [comment]
>Steps 1-4. As you can see from milk, calorie 1584 kcal, we got products with total calories equal to 3577 kcal. I don't understand anything about this, so I don't know if this is possible.

kcal is a measure of energy, so unless an ingredient is being added in this step, the energy in the system should not increase.

**Comment by x-qq** [comment]
Changing the number of produced items in churn/non-churn raw butter recipes from 99/33 to something like 20/7 seems like a reasonable and easy fix.

**Comment by Sirbab** [comment]
I just realized the shake recipe (non churn) produces buttermilk at a constant 161 calories. So the math for preserving calories becomes this relationship: 3*490=(X*110)+161, or x=11.9.  If I change the butter produced from 33 charges to 12, that results in 12 charges of butter at 109 calories, and 161 calories in buttermilk. 

For the churn, If we keep the 5 cream jars input, and reduce the produced charges from 99 to 22, that maths out to 111 calories per unit, which I find acceptable.

Balance wise, this means you cannot craft as many things needing butter due to a reduced volume of outputs, but I think that's honestly fine.  The alternative becomes increasing the input number of milk cream jars which just becomes silly, needing 22.3 cream jars for 99 charges out output.

The next question becomes if we want or need raw butter still, or are we okay with merging raw butter and butter into one item.

**Comment by x-qq** [comment]
Store-bought butter is likely to contain various oils, emulsifiers, preservatives, etc so it makes sense that homemade would be a different (and better) product.

The recipes that can be crafted with butter but not with raw butter are:
```
chicken sandwich
escargot
lobster roll
PBJ toast
shillelagh
```
I can't think of any explanation as to why raw butter wouldn't be usable for these except an oversight.

Also, crafting homemade butter should probably also require salt.

**Comment by Xelat84** [comment]
> unless an ingredient is being added in this step, the energy in the system should not increase

Sorry for replying to closed issue. Just to clarify, actually that statement isn't correct in general case. For example, thermal processing of food does not create energy but can significantly increase its digestible caloric value by enhancing nutrient bioavailability. Several mechanisms contribute:
- **Cell wall breakdown** – Heat disrupts plant cell walls (composed of indigestible cellulose), releasing nutrients that would otherwise remain inaccessible.
- **Protein denaturation** – Unfolding of protein structures facilitates enzymatic digestion.
- **Starch gelatinization** – Heating causes starch granules to swell and partially break down, making them more susceptible to amylase digestion (e.g., potatoes, rice, cereals).
- **Reduction of anti-nutritional factors** – Thermal processing inactivates compounds that inhibit digestion, such as enzyme inhibitors in legumes.

But this does not applicable for fermenting process, like chain of butter production.
