### ISSUE TITLE
Segmentation fault when trying to exit out of Read menu.

### ISSUE THREAD

**Issue by gitelitko** [CleverRaven/Cataclysm-DDA#77223]
### Describe the bug

Pressing ESC to leave the Read menu (even with nothing to read) will crash the game. It does it in my current save with mods, and in a brand new world with no mods and a random character.

### Attach save file

N/A

### Steps to reproduce

Make a new world.
Make a character.
Press R to try reading something.
Press ESC to try and exit Read menu. (or exit out of the "there is nothing to read" popup)

### Expected behavior

Expected the menu to close and game to continue to run.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-21-0327 5762e89 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17458104/crash.log)

**Comment by PatrikLundell** [comment]
Failed to reproduce with my current save.

**Comment by Night-Pryanik** [comment]
Can confirm. This is most probably because of #77167.

**Comment by PatrikLundell** [comment]
/Confirmed

@Night-Pryanik: Aren't you on the list of people who are allowed to "officially" confirm bug reports? Not sure if it's permitted, but I did it based on your reply.

**Comment by Night-Pryanik** [comment]
I am. I just posted the confirmation, and rushed to fix the issue.
