### ISSUE TITLE
"Stealing" checks are too aggressive

### ISSUE THREAD

**Issue by Demivan** [CleverRaven/Cataclysm-DDA#77239]
### Describe the bug

You can no longer read signs at the exodii base.

You can no longer move creates and lockers at refugee center. This prevents completing the first merchant quest to kill zombies (Clear Back Bay).

### Attach save file

N/A

### Steps to reproduce

1. Try grabbing crates at the refugee center
2. This makes everyone hostile

1. Try activating signs at the exodii base to read them.
2. This triggers a warning too

### Expected behavior

Reading signs should be allowed.

Moving some crates and lockers at the refugee center should be allowed.

### Screenshots

![image](https://github.com/user-attachments/assets/c77b3fab-485c-48ec-a73c-2ded779da490)
![image](https://github.com/user-attachments/assets/771878a7-81d7-43f9-9479-e486a1fad58f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: 2357a3c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by AudBobb** [comment]
There was also a reddit post talking about pulping zombies at the Tacoma ranch making them angry

**Comment by RenechCDDA** [comment]
> You can no longer read signs at the exodii base.

Yes, that's a problem.

> You can no longer move creates and lockers at refugee center. This prevents completing the first merchant quest to kill zombies (Clear Back Bay).

Nope, they clear entrance for you.

**Comment by Demivan** [comment]
> Nope, they clear the entrance for you. You don't need to move any furniture at all.

Strange, I haven't seen that. How do you trigger it? Just accepting the quest does not do it.

**Comment by EvanBalster** [comment]
I did that quest a few days ago and was able to move the lockers out of the way with no warning or NPC hostility.  My character was too weak to grab/drag the crates easily.

I have encountered the following interactions flagged as stealing:

1.  Looting the body of the refugee center informant.  (Upon careful inspection, you're stealing from the biker faction and the refugee center people do not care)
2.  Looting the bodies of various other bandits who are in any case hostile to you.
3.  Attempting to read or digitize books in the refugee center.  (YMMV on whether this is truly an issue)
4.  Exodii signs as mentioned before.
5.  The door winch in the refugee center, after it is enabled by completing a quest and the player is welcomed to use it.

**Comment by Demivan** [comment]
> Attempting to read or digitize books in the refugee center. (YMMV on whether this is truly an issue)

This is working as intended: https://github.com/CleverRaven/Cataclysm-DDA/pull/65927#issuecomment-1577535295

**Comment by Demivan** [comment]
You cannot activate fences at a lumbermill to climb over them

**Comment by RenechCDDA** [comment]
> You cannot activate fences at a lumbermill to climb over them

100% working as intended. The only fence entrance was locked, that was just bad mapgen. That is being handled - #77371 / https://github.com/CleverRaven/Cataclysm-DDA/pull/77371/commits/7a420245c423a6438991efb13e371d2e24a17469

**Comment by failboat78** [comment]
You cannot smash corpses near npc bases like Tacoma or scrapper.

**Comment by RenechCDDA** [comment]
> > Nope, they clear the entrance for you. You don't need to move any furniture at all.
> 
> Strange, I haven't seen that. How do you trigger it? Just accepting the quest does not do it. I have always dismantled the baricade manually.

It was added in the same PR which introduced this mechanic.

It is possible you accepted the quest beforehand but did not complete it before updating to a version with these checks.

**Comment by RenechCDDA** [comment]
With #77371 and #77426 the only concern I have left for this issue is being unable to read the signs, or any other possible 'benign' examine action which we want to explicitly allow.

I'm open to suggestions on how to resolve this.

**Comment by Night-Pryanik** [comment]
Make explicit check for those "benign" iexamine actions?

**Comment by RenechCDDA** [comment]
> Make explicit check for those "benign" iexamine actions?

I would like to avoid hardcoding a list of allowed/disallowed actions, but that might have to be the approach.

It's troublesome to even attach it to the iexamine/iuse acto~~r, because at the time of check we don't even have information on *which* actor it is.~~ This might be solvable, but I'd have to look into it. It looks like `examine_actor` is protected, but we could have a function which returns whether the examine_actor is considered 'allowed' and set that value in json.

**Comment by osuphobia** [comment]
![2024-11-01 222134](https://github.com/user-attachments/assets/89d19a4a-c1d3-48b7-900f-27b344ab90bd)
Now I need to use Probability Travel CBM to enter the territory of Prisoners, otherwise they got mad and attack me.
Meanwhile, if I offend one prisoner and let him attacks me, then kill him, they feel nothing :)
![2024-11-01 223254](https://github.com/user-attachments/assets/32fdab95-1ca3-4207-88a6-1ae50f654c90)
Furthermore, if I climbed a tree and want to climb down, the relationship between me and the Prisoners will be challenged😀

**Comment by kevingranade** [comment]
I don't think this adresses your actor problem,  but probably we should have a method for "only examine,  don't interact with in any way" that doesn't trigger theft checks to make it distinct from other interactions that Prentiss involve acquiring or interacting with an object in a way that should trigger those checks.

**Comment by yamil-90** [comment]
just wanted to add that you also cant interact with the translocator at the forge of wonders in magiclysm
![image](https://github.com/user-attachments/assets/80eb8c2f-445d-40e1-be43-6c2ae48184d7)
