### ISSUE TITLE
Default name is new npc name and will always be that name

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#77235]
### Describe the bug

Believed to be related to https://github.com/CleverRaven/Cataclysm-DDA/pull/76935

For some reason it's picking from the default name as the only valid name, removing the default name fixes it, but any name you enter makes it so that only npc's spawn with that name

### Attach save file

[Jupiter Inlet Beach Colony-trimmed.tar.gz](https://github.com/user-attachments/files/17465951/Jupiter.Inlet.Beach.Colony-trimmed.tar.gz)

### Steps to reproduce

Set default name to something

Spawn a npc, 

Npc will have that name

remove default name

Npc will have random name

### Expected behavior

Not to have npc's all named after the default name

### Screenshots

![image](https://github.com/user-attachments/assets/498b6f3b-bf9e-4130-8cba-b1b6da0d1572)
![image](https://github.com/user-attachments/assets/add81db1-8960-4eff-8687-e204e3943372)
![image](https://github.com/user-attachments/assets/3e3bc11f-04c1-4ab5-b73f-8a9e013cb8ec)
![image](https://github.com/user-attachments/assets/842552b7-483a-4bda-bc32-f239b6822d23)
![image](https://github.com/user-attachments/assets/8f75e067-266c-43b1-840f-b73047c04ffe)
![image](https://github.com/user-attachments/assets/75f36a83-10b1-412f-9edf-d490be2377b3)
![image](https://github.com/user-attachments/assets/0b7d991d-5798-40bc-9d50-9c7b25aff7c6)
![image](https://github.com/user-attachments/assets/f69b81d7-6c57-42a7-a5d2-8a089e5bcccb)
![image](https://github.com/user-attachments/assets/2ad16bd6-34b2-4da4-bc7b-028c25eafb68)
![image](https://github.com/user-attachments/assets/6c015a63-4554-4a3e-9c05-c89b8c22ef8d)

### Versions and configuration

- OS: Windows
    - OS Version: 7
- Game Version: 2357a3c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Mind Over Matter [mindovermatter],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

https://discord.com/channels/598523535169945603/598523535169945607/1297995245820186715 was the discord discussion where it started.

**Comment by harakka** [comment]
Probably related to #76935, @ShnitzelX2 ping

**Comment by ShnitzelX2** [comment]
thanks, I'll take a look.
