### ISSUE TITLE
Pressing most keys on nothing to read prompt crashes the game

### ISSUE THREAD

**Issue by AdamBrezik** [CleverRaven/Cataclysm-DDA#77261]
### Describe the bug

Game crashes on prompt "nothing to read" if you press anything but exit

### Attach save file

[CleanTest01.zip](https://github.com/user-attachments/files/17481482/CleanTest01.zip)

### Steps to reproduce

1. Have nothing to read in your inventory and nearby 9 tiles.
2. Go to read menu.
3. Press anything that is not mapped as exit. Example: "?", "1", ","

### Expected behavior

Exit the prompt pressing any key.

### Screenshots

Game crash. Tested on a blank world without mods.
![image](https://github.com/user-attachments/assets/9400ffdd-7f0c-4a21-b0d3-3c1bd050ddbf)

### Versions and configuration

Windows 10 19045.5011, 5762e89 (tiles)

### Additional context

[crash.log](https://github.com/user-attachments/files/17481527/crash.log)
[debug.log](https://github.com/user-attachments/files/17481530/debug.log)

**Comment by PatrikLundell** [comment]
This has most likely been fixed by #77229 (which is newer than your version).
