### ISSUE TITLE
Color issue 2. Naming of the colors from COLOR.md

### ISSUE THREAD

**Issue by RedMisao** [CleverRaven/Cataclysm-DDA#77282]
### Describe the bug

I'm not sure if the names of the colors are how they're _intended to_ look, or the names are arbitrary and they look how they _should_.

Basically, it appears that colors have the _wrong names_.

The biggest offender is `pink`, which is definitely IRL magenta (#FF00FF). Even the rgb values say so (255,0,255 vs 254,0,254).
Directly related to this, ingame `magenta` is a shade of IRL purple (for reference, purple is this #800080 and it's different from violet, which looks like this #7F00FF).
Then, `light_red` is a kind of IRL pink.

The other offender is `cyan`, which is a kind of IRL light blue (teal), and `light_cyan` is actually how IRL cyan looks like (#00FFFF or (0,255,255 vs 0,240,255))

Finally, the grays, relatively minor compared to the previous two. There's `light_gray` and `dark_gray`, but not `gray`. In my opinion, `dark_gray` should be `gray` because there's a gap between that and `black`

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Again, I'm not sure if the colors are intended to look how they _currently do_, or they're intended to look how they're _named_.

### Screenshots

N/A, it can be seen in the [docs](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COLOR.md#possible-colors).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 7fc0414 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Night-Pryanik** [comment]
Naming of colors is such a deep pit.
![fuschsia](https://github.com/user-attachments/assets/15df6333-0484-4c13-8df2-68ab23d20124)

![IMG-20240913-WA0002](https://github.com/user-attachments/assets/ea849fe6-43c6-427b-8bb0-3c82843f7b1a)
(Лиловый is purple in Russian)

**Comment by Procyonae** [comment]
I think we just use the names that curses uses

**Comment by harakka** [comment]
Procyonae is correct, our colors and limitations on them stem from 16 color terminal where the program has zero control over what the colors actually are, it's up to terminal.

**Comment by ZhilkinSerg** [comment]
Actual RGB values are irrelevant - players can configure whatever they want in terminal settings and/or in SDL game builds (via color templates).

As for color ids: they were like that from the very beginning - https://github.com/Whales/Cataclysm/blob/69ffbb2953c1e92a9b24d5380dabe7f26066223e/color.h. There are `pink` instead of `light_magenta`,  `dark_gray` and whatnot. Not much to gain in changing these ids.
