### ISSUE TITLE
Color issue 1. No orange, no purple, no violet. More colors?

### ISSUE THREAD

**Issue by RedMisao** [CleverRaven/Cataclysm-DDA#77281]
### Is your feature request related to a problem? Please describe.

There's no orange, purple or violet colors [in the game](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COLOR.md).

For context, this is violet (#7F00FF), purple proper (#800080), light violet (#CF9FFF) and light purple (#CBC3E3)

### Solution you would like.

The presence of such colors.

### Describe alternatives you have considered.

Honestly, no alternatives to the lack of such colors. We've living without them for more than a decade.

Alternatives regarding missing colors in general: more colors, like gold/golden (average between yellow and IRL orange), tan/light brown (#c4884d in hex), for what I can recall on the spot.

### Additional context

Windows version, game version for when this issue was opened.
- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 7fc0414 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
Yeah the colours we have are pretty limiting and I appreciate it has to work with curses but surely their must be some way to support more than what we have

**Comment by ZhilkinSerg** [comment]
Long story short - that's not really feasible while there is curses version.
