### ISSUE TITLE
Debug menu. Force temperature. The expected and displayed number must be the same data type

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77296]
### Describe the bug

If you need to set the temperature, you can only use numbers. That is, the temperature has an integer value.

debug menu / `m`ap... / `T` Force temperature / `1` Set 
![1](https://github.com/user-attachments/assets/d52d377e-45e6-4b5b-8b75-c56766a769fb)
This is the window to enter the temperature. In the example I have set it to 10 degrees Celsius.

Now I want to change the temperature. I call the window again and get:
![2](https://github.com/user-attachments/assets/c35fb42a-d873-442c-97cb-c7c1f69c3f69)

Okay, I'm just pressing enter:
![3](https://github.com/user-attachments/assets/35f42be4-909d-4ed5-b20f-e43472cd033d)

So if I want to change the temperature, instead of entering a value, I have to edit the value entered last time. (In some cases, this is even good).

At the same time, the game outputs an integer number as a floating point number. And instead of changing 1-2 digits, I have to delete everything that the game output and then enter a new number.

This is not convenient. And annoying

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

The game should output the integer value, or at least accept it in the format it displays itself.

### Versions and configuration

- OS: <s>Windows</s> Arch linux + portproton
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-10-24-0244 19807c7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Maybe there's an additional problem. And there should be a period, not a comma. Maybe most people have that.

But my main language is Russian. And remembering the topic https://github.com/CleverRaven/Cataclysm-DDA/issues/71635#issuecomment-1935743602, maybe my system uses comma as a decimal separator. But I definitely didn't install it separately, so those are the default settings. Arch linux.

**Comment by PatrikLundell** [comment]
/Confirmed

The UI doesn't accept either comma or period as input (nothing happens when these keys are pressed: they're ignored), so either the input should be changed to take a floating point number, or the presented existing value should be displayed as an integer.

I believe the separator convention used is based on the language used, but cannot confirm it.

**Comment by IdleSol** [comment]
The fix didn't help. Only the message has changed:
![1](https://github.com/user-attachments/assets/1e7db4cf-3b0d-453c-866c-0967037e5dbc)

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: fc8e177 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
