### ISSUE TITLE
No Word Wrap on Item Info Menus

### ISSUE THREAD

**Issue by kween-kobold** [CleverRaven/Cataclysm-DDA#77298]
### Describe the bug

With the new update issue #76529 PR #76529 there is now no longer word wrapping on item info screens, perhaps other screens as well.

### Attach save file

[The Event Zone-trimmed.tar.gz](https://github.com/user-attachments/files/17509395/The.Event.Zone-trimmed.tar.gz)

### Steps to reproduce

1. Open game
2. press g to Pickup item menu
3. highlight item on list
4. press I to open Item Info screen

### Expected behavior

I expect the text to not be cut off and wrap around. 

### Screenshots

![2024-10-24 11_39_36-Cataclysm_ Dark Days Ahead - cdda-experimental-2024-10-24-1253 2d90bfe](https://github.com/user-attachments/assets/ee8ddb02-bbcf-4a3e-9df0-75aefeda347b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-24-1253 2d90bfe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Bombastic Perks [bombastic_perks],
    DinoMod [DinoMod]
]

**Comment by RenechCDDA** [comment]
☝️ Closing as duplicate.

Thank you for reporting this bug. We already have an issue # tracking this. To keep the reports organized (so we can fix them!) your issue will be closed, and a link provided to keep all conversation together.
