### ISSUE TITLE
Game is crashing way more often 

### ISSUE THREAD

**Issue by Iron-Thorn** [CleverRaven/Cataclysm-DDA#77308]
### Describe the bug

The game crashed out of nowhere, for no apparent reason.  This has never exactly _not_ happened, but now it's every fifteen minutes.  It seems to be universal across save files.
\

### Attach save file

[Green Hill-trimmed.tar.gz](https://github.com/user-attachments/files/17513065/Green.Hill-trimmed.tar.gz)

### Steps to reproduce

1. Start a game.
2. Wait briefly until the game crashes without warning.

### Expected behavior

I expected the game to not crash, at least not constantly, because games that crash constantly are difficult and unrewarding to play.

### Versions and configuration

Macbook Air, tiles version, Cuteclysm.  The October 20th experimental release of the game.  Same Preset Character every time.

### Additional context

There are no crash logs among the files, oddly enough.  I looked at the debug log, and I think this is the message before it crashes/quits.
_ERROR SDL : src/cata_tiles.cpp:769: The tileset you're using has no 'unknown' tile defined!_

[debug.log](https://github.com/user-attachments/files/17513376/debug.log)

Debug log is above.

**Comment by RenechCDDA** [comment]
When, exactly, are you seeing crashes? Gameplay? Loading? Saving? Main menu? You're going to have to give us some more information to work with here if there's not even a crash log. I would wager a guess you have "antivirus" software killing the process.

**Comment by Iron-Thorn** [comment]
Updating to a newer version fixed it.  Don't worry about it.
