### ISSUE TITLE
One frame menu delay when using recording software.

### ISSUE THREAD

**Issue by blahbleepew** [CleverRaven/Cataclysm-DDA#77301]
### Describe the bug

I'm submitting this issue on behalf of vormithrax without his knowledge (no association, no twitch/yt/discord) and thus cannot reproduce. During his streams his menus aren't showing up. From what I can see and intuit, each render is 1 frame behind on the recording. The recording doesn't detect the change when attached to a windowed screen and thus doesn't show the next frame. Clicking or using keyboard keys forces a rerender. A compatibility setting that forces a rerender every second (or sooner) should fix the issue for streamers.

### Attach save file

N/A

### Steps to reproduce

Not reproducible, can be seen in VODs. You can witness him talking about the current selection and see the frame off by one for each menu item (8:40, talks about tiny stomach, highlighted menu entry is topographagnosia. 8:50 slow healer but highlights slow learner)

https://youtu.be/qYuwFr1nyV8?si=SYl6KLEZsh-vvgBn&t=519

### Expected behavior

Explained above.

### Screenshots

Cannot be screenshotted due to it being a temporal bug. Requires video (posted above)

### Versions and configuration

N/A. Vormithrax would need to submit his information. He says it happens regardless of render configuration.

**Comment by RenechCDDA** [comment]
We can't support third party software or people's use of it. 

Also, I personally use OBS to record without any issues.

**Comment by blahbleepew** [comment]
> We can't support third party software or people's use of it.
> 
> Also, I personally use OBS to record without any issues.

You already do support third party software with the screen reader compatibility option. In the settings description it says "Targeted towards open-source screen reader 'orca' using curses for display".
