### ISSUE TITLE
battery values are messed up

### ISSUE THREAD

**Issue by Moistwaffleofluv** [CleverRaven/Cataclysm-DDA#77315]
### Describe the bug

the values on batteries are super low

### Attach save file

[Strauss-trimmed.tar.gz](https://github.com/user-attachments/files/17514810/Strauss-trimmed.tar.gz)

### Steps to reproduce

1. find anything battery operated 
2. see the values or way messed up

### Expected behavior

i expect to find normal values not like 52/16 battery capacity

### Screenshots

![Screenshot 2024-08-31 161649](https://github.com/user-attachments/assets/308c4db7-1da1-4e5b-8306-681220d109b1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: cdda-experimental-2024-10-24-2254 12b4e6c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by RenechCDDA** [comment]
Not a bug. #75361
