### ISSUE TITLE
Zombies are acting really weird.

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#77328]
### Describe the bug

They aren't attacking me at all, they just ignore me, I checked If I was invisible, & they can see me, but they completely ignore me. They do however, attack NPCs & animals. They sometimes come back on & attack, sometimes saving & re-loading it works, but most of the time it doesn't.

### Attach save file

[App-trimmed.tar.gz](https://github.com/user-attachments/files/17522916/App-trimmed.tar.gz)

### Steps to reproduce

No idea.

### Expected behavior

Zombies attack the player

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-10-25-0415 f633a1b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm [magiclysm],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Magiclysm Revamp and Additions [magicrevamp],
    Tankmod: Revived [Tankmod_Revived],
    Blazemod - Vehicle Additions Pack [blazemod],
    Extra Mutated Scenarios [extra_mut_scens],
    New start locations for Extra Mutated Scenarios [new_start_locations_for_extra_mutation_scen],
    More Professions can start in Extra Mutated Scenarios [more_profession_chooses_extra_mut_scens],
    More Survivor Notes [more_survivor_notes],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mind Over Matter [mindovermatter],
    Mind Over Matter: <color_magenta>Remove Pain Disables Powers</color> [mom_remove_pain_disables_psi_limit],
    Mind Over Matter: <color_magenta>Feral Psions Always Drop Crystals</color> [mom_feral_psions_always_crystals],
    Mind Over Matter: <color_magenta>Awakenings Are Always Successful</color> [mom_always_awaken],
    Martial Mastery [perk_melee_system],
    Hands [hand],
    Dream of Flight [dream_of_flight],
    Custom Portal Storm Size [custom_size_ps],
    Custom Frequencey For Portal Storms [custom_freq_ps],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Bionic Traits [bionic_traits],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Readd Clothing Customization for TailorKits [TailorKits-Readd-Customization],
    Pixel's Various Fuckery [Pix's Shit],
    Jackledead Armory [jackledead_armory],
    Culinary Days Ahead [culinary_days_ahead],
    Xedra Evolved [xedra_evolved],
    Make bows great again [bow_opness],
    Jackledead Armory: Creeps Goons Guns [jackledead_armory_expansion],
    Gunslinger Professions [hyd_gunslinger],
    Frontier Mods Core [frontier_core],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    <color_light_green>Cataclysm++</color> [Cata++],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Bionic Slots [no_cbm_slots],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Loadout [loadout],
    Additional backgrounds [Arendeth_Additional_backgrounds],
    <color_yellow>Project Moon World</color> [pm_world]
]

### Additional context

I have been teleporting a bunch, & I've used debug menu. Perhaps the real time turn progression? It's currently at 4.

**Comment by kevingranade** [comment]
Both the massive number of mods and the debug activities are very problematic.
If you do enough weird mod stuff and especially abuse debug you can break the game,  it is known.
