### ISSUE TITLE
fast report option from ingame

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#77322]
### Is your feature request related to a problem? Please describe.

there might be alot of people who are too lazy to report a little bug or any of all the bug that they experiencing, or suggestion that they might having, there might also be too much filling that they are needed to fill

### Solution you would like.

option for ingame bug report and filling that they require to fill like the description and auto filling for the version mod save file crash log, in game reply,...
that directly upload to github or other sources, then the reply will be sent to gmail or ingame

**Comment by GuardianDll** [comment]
Launcher is not part of a project, it's a third party tool
such request should go to launcher repo

**Comment by GuardianDll** [comment]
Okay, i read it with outdated title, my bad

**Comment by Holli-Git** [comment]
This would require CDDA to have internet connections and service, which is way outside practicality, especially for such a minor QoL feature very few would benefit from. The bug report already includes instructions on how to generate a bug report, I don't see how much more you can improve upon that.
