### ISSUE TITLE
clang is not getting detected properly, Makefile has general issues

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#77320]
### Is your feature request related to a problem? Please describe.

I needed to build with clang on Linux. I put this in my PKGBUILD, which works for 99% of projects:

```bash
export CC=clang
export CXX=clang++
```

But it errors out with:

```
clang++: clang++error: : unknown argument: '-flto-odr-type-merging'error:
unknown argument: '-flto-odr-type-merging'
```

Apparently you need to append `CLANG=1` but it should get detected automatically:

https://github.com/CleverRaven/Cataclysm-DDA/blob/f633a1b9a94b0d4fbcce0001d8bf689b0743da5c/Makefile#L249-L251

Yet I was told this is probably dead code.

### Solution you would like.

The whole Makefile needs a makeover. This is one issue of many. Another significant, glaring issue is that the Makefile *appends* flags, making it very hard to impossible to overwrite some flags without editing the file, which is bad practice. For example, due to arcane debugging reasons related to asan I had to change `-Os` to `-O3` and that was quite the ordeal.

There is quite possibly more dead code in there, as well as a lot of unneeded complexity.

**Comment by kevingranade** [comment]
Please don't use confusing suggested solutions like this. 

"The makefile should respect standard compiler externs" is a valid feature enhancement,  "rewrite the thing" isn't.

**Comment by NetSysFire** [comment]
Should I create an issue for every single flaw in that makefile? That is not viable. The Makefile needs someone to thoroughly look at it as that is something that has not happened for a long time it appears. Not rewriting, but cleaning it up.

**Comment by kevingranade** [comment]
Either break the *significant* points into issues or drop it.  *I think the makefile is bad and needs fixing* is not a valid issue.

For reference, none of the specific things you mention are a high priority.  Respecting environment variables is a nice to have,  overriding compile flags is a nice to have,  cleaning up dead code is a nice to have.

**Comment by NetSysFire** [comment]
>I think the makefile is bad and needs fixing is not a valid issue.

I don't *think* it is bad, it is actually bad. So bad the gcc folks even commented on its quality when I went to them for help with asan. That is *quite* something.

>"The makefile should respect standard compiler externs" is a valid feature enhancement,

>For reference, none of the specific things you mention are a high priority.

This has never been assigned a high priority. In fact the help wanted label even implicitely lowered it. This also does not invalidate this issue.

You know there are bundled issues like this one for a variety of topics. This format is not inherently invalid. When someone attempts fixing any of these described issues, it is possible, maybe even likely, the others will get fixed in the same pass, as the Makefile needs some attention in general. Thus, there is very little sense in splitting this up and I highly recommend just reopening.

If you really want to split them up, how about making a new kanban board/project for build related issues like these? That might make them easier to organize. I'd recommend you create this one or someone still needs to poke you about making the board public as these are invisible by default.
