### ISSUE TITLE
Menu too short

### ISSUE THREAD

**Issue by SniperofFire115** [CleverRaven/Cataclysm-DDA#77333]
### Describe the bug

In the description of almost any or all items when examining, parts of the description text and other item info menu text is cut off.

### Attach save file

N/A, Mods and save seem to have no bearing on the issue.

### Steps to reproduce

Open inventory (I) then examine any item with (E).

### Expected behavior

Text shouldn't be cut off, or window should be scrollable. (if possible)?

### Screenshots

![image](https://github.com/user-attachments/assets/97b981cb-8c06-4581-9dfc-31ab5ca9fc73)
![image](https://github.com/user-attachments/assets/9e6de4c4-628f-4d6e-abe2-7d68a4e26b02)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-25-1449 6ae4cb0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    <color_light_green>Cataclysm++</color> [Cata++],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Aftershock [aftershock]
]

### Additional context

I can't be certain but this didn't seem to be an issue with the builds a handful of updates back. The new UI or text menu (whatever it may be), seems to have been the cause of the text now being cutoff.

**Comment by NetSysFire** [comment]
Why is github-actions not closing issues anymore? Ugh.
