### ISSUE TITLE
Bow criticals are inconsistent

### ISSUE THREAD

**Issue by Egregorious** [CleverRaven/Cataclysm-DDA#77362]
### Describe the bug

Using either of the composite bows with 7 dex and 9 per, along with 10 marksmanship and 10 archery. I consistently manage to land criticals against child, boomer and dog zombie lines; yet I have never landed a critical hit on any other zombie type I've encountered. 

It seems as if something weird is happening with bow critical calculations, since I would have assumed landing crits on dogs and children should actually be harder than on regular zombies - them being dodgier and smaller targets.  

### Attach save file

[Supai-trimmed.tar.gz](https://github.com/user-attachments/files/17531770/Supai-trimmed.tar.gz)

### Steps to reproduce

1. Make character with 7 dex and 9 per, 10 marksmanship and 10 archery and give them a composite bow(light) with makeshift metal arrows.
2. Spawn in some child, boomer, dog, and regular zombies.
3. Shoot a bunch of arrows at each of the zombies.
4. Observe that critical hits only land against child, boomer and dog zombies. Never crit against regular zombies. 

### Expected behavior

The composite bow being capable of landing crits against regular zombies.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-26-0601 303ea65 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
Light composite bow has 6 base damage, makeshift metal arrows give you a 1.0x damage multiplier. This means you can only critical things with less than or equal to 6 * 10 (crit damage multiplier) = 60 maximum HP. All of the things you've mentioned critting have 60 or less HP. Sounds like it's working as intended.

**Comment by IdleSol** [comment]
@RenechCDDA I think you rushed to close the topic.

If I understood correctly (and a quick test confirmed it), it's about the lack of critical hits. Critical hits just don't happen. And as far as I remember, critical hit has nothing to do with the target's HP, i.e. it doesn't matter if it kills or not. It's a dice, right?

**Comment by IdleSol** [comment]
I was wrong. Although I don't understand why it was done that way:
https://github.com/CleverRaven/Cataclysm-DDA/blob/d5156114554a8a769e25c450a0b7b59eb7bf0d6a/src/creature.cpp#L1106-L1108

https://github.com/CleverRaven/Cataclysm-DDA/blob/d5156114554a8a769e25c450a0b7b59eb7bf0d6a/src/creature.cpp#L1113-L1115

For ranged weapon hits to be critical. A condition must be met: `ret.max_damage * crit_multiplier > get_hp_max( ret.bp_hit )`

Compare it to melee weapons:
https://github.com/CleverRaven/Cataclysm-DDA/blob/d5156114554a8a769e25c450a0b7b59eb7bf0d6a/src/melee.cpp#L1115

**Comment by Egregorious** [comment]
Oh, ranged crit chances being based on max hp of the target is not information I was able to find. Armour is always mentioned whenever it comes up but all that implies to me is that armour reductions are calculated before crit multipliers. 

What *is* the reasoning behind this? The only thing I can imagine is that it incentivises higher base damage weapons, but I would have imagined armour does that job anyway.
