### ISSUE TITLE
[General bug] Can't learn dissecting proficiencies from magiclism monsters and human's bodies that died before game start. 

### ISSUE THREAD

**Issue by Tiareth** [CleverRaven/Cataclysm-DDA#77361]
### Is your feature request related to a problem? Please describe.

As the title says, trying to dissect a corpse found in the field, as well as the bodies of monsters from the Magiclysm, will not teach you anything. The latter is especially unpleasant, because i feel that since the corpse does not teach anything, then the advantages associated with proficiency will not work when you fight wih said corpse when it was't corpse yet.

### Solution you would like.

Proficiencies should be learnable and the benefits of proficiencies must be applied when you fight.

### Describe alternatives you have considered.

none

**Comment by Milopetilo** [comment]
The magiclysm bodies not providing proficiencies is because they do not have any proficiencies tied to them yet (#70307). I'm unsure about the human bodies and can't test that right now.

**Comment by Tiareth** [comment]
> The magiclysm bodies not providing proficiencies is because they do not have any proficiencies tied to them yet (#70307).
Wow, almost a year ago and they still don't get the weak points and everything that comes with it? Unless It is necessary to create a new "magic beast" proficiencies or something similar, but copying an existing one shouldn't be too difficult.
