### ISSUE TITLE
Tutorial character is famished and underweight

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#77386]
### Describe the bug

![image](https://github.com/user-attachments/assets/41dbd177-3715-46e3-a198-47da1e75a773)

### Attach save file

n/a

### Steps to reproduce

1. Start tutorial.
2. Immediately be underweight.

### Expected behavior

Character has a normal weight.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-10-23-1516 99d27e5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by GuardianDll** [comment]
Should be fixed by #77294
