### ISSUE TITLE
Gravestone ascii art in default death screen looks screwed up 

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#77402]
### Describe the bug

What title says. According to @harakka it might have used a non-monospace font. I also dont know if this happens on the pc version cuz i dont own one.

### Attach save file

N/A

### Steps to reproduce

1. Go into a world
2. kill off the character
3. see the gravestone

### Expected behavior

Properly ascii gravestone.

### Screenshots

![Screenshot_20241028_143429](https://github.com/user-attachments/assets/d8d74013-bdc9-435b-b802-452221b3fdc5)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: ZTE; Model: ZTE 8050; Release: 13; Incremental: 20240523.205226; 
- Game Version: cdda-experimental-2024-10-28-0252 1fef5f3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    Xedra Evolved [xedra_evolved],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    GUT's Xedra Evolved Compendium [gut_xedra_compendium],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    horde tweaks [horde_tweaks],
    Funni Loading Screens [loading_screen_funni]
]

**Comment by harakka** [comment]
Confirmed, not an Android only problem

**Comment by NetSysFire** [comment]
There are other consequences to using a non-monospace font, too. E.g the Satiety gauge on food looking a little off. Potentially we can collect all the stuff broken by it here.

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
