### ISSUE TITLE
Unable to compile on MacOS

### ISSUE THREAD

**Issue by johannes-graner** [CleverRaven/Cataclysm-DDA#77410]
### Describe the bug

Both the automatic release process and myself compiling locally fails with the following error:
```
src/third-party/imgui/imgui_freetype.cpp:38:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
```
which clearly indicates that libraries are not included and linked properly.

### Attach save file

N/A

### Steps to reproduce

On MacOS, run e.g. `make RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 CLANG=0` and watch the compilation fail.

### Expected behavior

The compilation succeeds.

### Versions and configuration

OS: MacOS Sequoia 15.0

### Additional context

The following addition to `Makefile` made the compilation succeed:
```
@@ -765,6 +765,8 @@ ifeq ($(TILES), 1)
     LDFLAGS += $(shell $(PKG_CONFIG) --libs freetype2)
   endif
 
+  CXXFLAGS += $(shell $(PKG_CONFIG) --cflags freetype2)
+  LDFLAGS += $(shell $(PKG_CONFIG) --libs freetype2)
   DEFINES += -DTILES
 
   ifeq ($(TARGETSYSTEM),WINDOWS)
```
So the problem is likely that the `freetype2` library is not included properly for MacOS. It should probably be quite easy to fix for someone more familiar with the makefile than me.

**Comment by JonathanCLo** [comment]
i've had to use `freetype-config --cflag` and `--lib` respectively

**Comment by Ivan-Shestakov** [comment]
The solution from https://github.com/CleverRaven/Cataclysm-DDA/pull/77413 allowed me to complete the build. @johannes-graner thanks for the solution!
