### ISSUE TITLE
"Flatlander" portal storm enemy's attack doesn't function

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#77423]
### Describe the bug

[Exactly 1 year ago](https://github.com/CleverRaven/Cataclysm-DDA/pull/69818) I had a dream where I was playing CDDA and was being accosted by some new monster, so I turned that dream into a monster itself.

I've been informed today that ever since I added them It's attack spell is completely broken. It doesn't do anything. People've encountered this guy and just been confused as to what it does. I could've sworn that it worked when I tested it but that was a year ago.

### Attach save file

N/A

### Steps to reproduce

1. Spawn flatlander enemy. Alternatively spawn a portal storm and wait for the flatlander to spawn naturally.
2. Let it attempt and fail to attack you

### Expected behavior

It was written with a spell seen in the pr, the spell's supposed to work but doesn't.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.2274 (1909)
- Game Version: b7cfa5d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

### Additional context

If need be, I might just completely redo the flatlander enemy entirely. Having actually read the book I based it on this time.

**Comment by RedMisao** [comment]
Can confirm it doesn't cast the spell, lemme submit a PR with a fix
