### ISSUE TITLE
Narcoleptic Destroys even the best vehicles way too easy

### ISSUE THREAD

**Issue by Vgoloshivskiy** [CleverRaven/Cataclysm-DDA#77439]
### Describe the bug

If you drive deathmobile and fall victim to narcolepsy instead of vehicle slowly coming to a halt as you no longer press pedal or  when you hit something instead it continues to press out acceleration that you were on for 4 minutes managing to destroy good car by continiously ramming it into terrain etc.

### Attach save file

N/A

### Steps to reproduce

1.Create character with narcolepsy
2.Drive car in circle at relatively high-speed
3.Wait until narcolepsy hit
4.You continue to drive at high speed,if you crash you do it untill you wake up

### Expected behavior

Similar to **let go of controls**, slowly losing speed and when hit obstacle stop completely.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: f9790c2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by kevingranade** [comment]
There's a reason why people with serious narcolepsy avoid driving....

This is working as intended.

**Comment by Vgoloshivskiy** [comment]
> There's a reason why people with serious narcolepsy avoid driving....
> 
> This is working as intended.
Bummer, but I still don't belive that after crasing my sleeping character would be flooring gas pedal.

**Comment by Vgoloshivskiy** [comment]
Maybe at least some medicine to prevent falling asleep? like modafinil.

**Comment by zakhad** [comment]
How about if you had a npc with you that could check if the vehicle is moving and if the player avatar is asleep to shout/wake them up?
