### ISSUE TITLE
add stress stat

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#77450]
### Is your feature request related to a problem? Please describe.

it can make some actions and game progressions more relevant and would be another regulator for other kinds of activity that are not physical. There may be as well player characteristics that limit the frequency of kills based on the stress stat

### Solution you would like.

stress could work very much simmilar to the Lifestyle stat, also the presence of some items and life support buildings could reduce stress while things like rotten corpses would be detrimental and the presence of NPCs may boost positive effect while reducing the negatives, progression in the game may also help to stabilize stress changes

**Comment by ampersand55** [comment]
I like the ideas, but couldn't most of this be implemented using the morale stat?

**Comment by CoroNaut** [comment]
I can see the potential for "stress", "depression", "hyped", "religious fervor" (after reading a religious book for a religious character) or other mental boons or burdens. Would be nice to see a few new traits like "depressive personality", "hopeless", "energetic" or "deadened" (no morale penalties or boons) for it too. There could be drugs to regulate them, like anti-depressants, etc.

If we draw a comparison between this and the current system for how drugs affect the character, the current drug system is still a bit iffy at times even after years of tinkering with it. I'm kind of thinking it could be implemented with the drugs system though. Treating mental stuff as if it was just an effect from a drug. At the very least, adding a bunch of stuff to the morale stat would definitely be a basic solution. That affects focus and crafting, but perhaps extremely negative morale could affect combat stats in a sort of "its all hopeless" way.

**Comment by ampersand55** [comment]
Are you thinking something like a "stress bar" that's like the health bar but for mental health/sanity. 

I would absolutely like for the game to emphasize the cosmic horror/Cthulhu aspects more and this would very much fit into that.

**Comment by PGR-14** [comment]
A few more ideas:
-Anxiety: Kind of like languorous, but for stress (Or maybe a small mult?)
-Addictions cause stress: What it says on the tin, some addictions will give more or less (Caffeine & Cigarettes should be notable)
-Hallucinations?: Maybe.
-Lower morale (of course)
-Shaky: Higher levels should give the shaky hand effect.
-Beta Blockers: Basically makes you lose stress fast. (Could nullify the effects of Adrenaline or act as a blood thinner)
-Adrenaline?: We've got a mutation, but it seems to be an improvement to it, so if you've got high stress, you'll get a bunch of strength & speed, but completely useless afterwards.

**Comment by ADekema** [comment]
Mood is currently very limited both in what it does and what it doesn´t. It doesn´t affect the game to much unless it get´s extremely low and it isn´t affected by stuff that a normal modern person should be affected by (The WORLD just ended and everyone you know is dead, there are increasingly horrific monsters and you could be covered head to toa in zombie guts becease you chopped several dozen up with a sword)

the mood system definetly could be expanded and refined more.

**Comment by kevingranade** [comment]
Yes it could be expanded, but that's not adding a stress stat.

**Comment by ADekema** [comment]
I thank that if you want to reflect the effects of how horrific and discusting some things are than fear instead of terror would be a better thing to simulate. Think having a starting phobia´s that makes you afraid of gaint bugs. When you see one you get debuffs to simulate a detrimental flight or fight response and a big negative mood debuff.

**Comment by PGR-14** [comment]
> I thank that if you want to reflect the effects of how horrific and discusting some things are than fear instead of terror would be a better thing to simulate. Think having a starting phobia´s that makes you afraid of gaint bugs. When you see one you get debuffs to simulate a detrimental flight or fight response and a big negative mood debuff.

Oh, that's a perfect idea. Maybe also add some fears of mutations/doctors (CBMs & 1st Aid). I know we have those Mutagen/Mycus Aversion traits, but I think those are dilapidated by now.

**Comment by kevingranade** [comment]
This is wrapped up, the answer is no, I see no good argument for adding a stress stat.
