### ISSUE TITLE
"min_dot" and "max_dot" spell fields don't function when negative values

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#77470]
### Describe the bug

While working on #77113 I found that the spell I had set up to heal the player upon eating the sandwich didn't work - it's set to have a `dot_min` and `dot_max` value set to a negative integer, so that it would slowly heal the player instead of hurt them. This doesn't work, despite me looking it over, trying numerous fixes and consulting with some people. I was told to make this bug report.

### Attach save file

[Lola-trimmed.tar.gz](https://github.com/user-attachments/files/17581066/Lola-trimmed.tar.gz)
NOTE: this save needs to run on the version from #77113. 

### Steps to reproduce

1. take damage
2. debug spawn in the "cosmic dagwood" inventor item. This item has a spell on consumption which causes a `min_dot` and `max_dot` value with a value of -5 (it was set like this for testing purposes. I'll balance it after I've made it work.)
3. Consume the dagwood. examine your health and note that it doesn't heal.

### Expected behavior

a negative value for these fields should give negative damage, healing the player, so I've been told. It seems like they just do nothing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.2274 (1909)
- Game Version: b7cfa5d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by RedMisao** [comment]
I can confirm it's not the spell `cosmic_dagwood_regeneration`. I added the json to a file, debugged lvl 1 to a character, set ALL hp to 1, casted it a few times, and it's not healing. (**Note:** I did not try adding the whole json (food, recipe, etc.), just the spell endpoint).

Then, I set the values to positive to deal damage, and that's working as intended. Doing this requires adding `"damage_type": "pure"` to the spell json, else it throws a "unknown "" damage type" error.

I tried with another heal dot spell I've done in the past (third party mod) as reference, and that isn't working either.

**Comment by Daved27hundred** [comment]
> I can confirm it's not the spell `cosmic_dagwood_regeneration`. I added the json to a file, debugged lvl 1 to a character, set ALL hp to 1, casted it a few times, and it's not healing. (**Note:** I did not try adding the whole json (food, recipe, etc.), just the spell endpoint).
> 
> Then, I set the values to positive to deal damage, and that's working as intended. Doing this requires adding `"damage_type": "pure"` to the spell json, else it throws a "unknown "" damage type" error.
> 
> I tried with another heal dot spell I've done in the past (third party mod) as reference, and that isn't working either.

thank god, I was hesitant to make this issue report because I wasn't sure if it was a mistake on my end lmao.

**Comment by GuardianDll** [comment]
Oh yeah, after closer inspection it seems i, for some reason, added `if( sp.damage_dot( caster ) > 0 )` check, that simply ignores dots that have zero or negative dot damage
Also found a bug that made dots affect all bodyparts even without SPLIT_DAMAGE or PERCENTAGE_DAMAGE flag
