### ISSUE TITLE
Multiple scenarios incorrectly make you spawn on a road

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#77474]
### Describe the bug

![image](https://github.com/user-attachments/assets/ff8344c1-e0ac-461d-a92e-2d87ec435bce)

### Attach save file

n/a

### Steps to reproduce

1. Make a new character, select burning building scenario
2. ~~Get lucky and it picks the road out of 362 possible spawn locations~~ This always happens. Why?! Even if I specifically select a different building out of the location pool.

### Expected behavior

A road can not burn. Disallow spawning there.

This spawned me on `road_ew`, right here: 
![image](https://github.com/user-attachments/assets/462b7029-38bd-4d57-99a9-7d6278519a8a)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-10-31-0712 47225ca [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment]
@LyleSY I just confirmed that #77451 is the reason why multiple scenarios spawn on a road now. At least burning building and lone survivor are affected.

**Comment by LyleSY** [comment]
Interesting! I wonder if it's because road is the only option that has ZONE_START_POINT defined in mapgen, so it wins automagically?

**Comment by silvermistshade** [comment]
I'm getting it with the default (evac shelter) start too.
