### ISSUE TITLE
Crafting is getting slowed to a crawl(irl time) by character temperature message spam.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#77481]
### Describe the bug

Looks like the player body temperature message spam is slowing crafting and making it really painful to craft anything. My % increases every 4%, stops, then resume for another 4%. As soon i take my clothes off, crafting resume normal IRL speed and goes blazingly fast compared to before. Just to reiterate and make it clear, what is slowing down is the IRL time, not the game crafting time.

Going into interface options and limiting the "messages cooldown" to 1000 or something seems to "fix" this issue as well. So it probably has to do with message spam.

### Attach save file

[Broadrat-trimmed.tar.gz](https://github.com/user-attachments/files/17589054/Broadrat-trimmed.tar.gz)
Mod to load my save. Dump in the data folder.
[CDDA-Extra-Lives.zip](https://github.com/user-attachments/files/17589047/CDDA-Extra-Lives.zip)

### Steps to reproduce

1.Load save
2.Craft what's on the workbench in front of you or just make any craft 
3.Crafting is very slow
4.Take off all your clothes so you don't have body temperature warm spam
5.Crafting resume normal speed
6. Limit the "message cooldown" in the interface options to 1000
7. Put on all your clothes again and craft
8. Game is back to normal speed

### Expected behavior

I'm expecting temperature message spam to not lag the game so much.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-21-1656 888e34a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Lives - Extended [extra_lives_extended],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

**Comment by RenechCDDA** [comment]
Unable to reproduce on 9f98a020 / windows 10

Crafted for 30 IRL seconds with clothes on and 30 IRL seconds without clothes on. Neither seemed to 'pause' at any particular point or show performance issues. Profiling looks pretty normal and basically identical between the two.

With clothes on:

![image](https://github.com/user-attachments/assets/93a1326c-3ce8-48e4-b48a-146f88c9eb2d)

Without clothes on:

![image](https://github.com/user-attachments/assets/f7b32b78-04f1-4730-a28a-812a197d4037)

**Comment by RenechCDDA** [comment]
This save has definitely been edited(there is a duplicate entry in mods.json), that completely voids your warranty.

**Comment by IdleSol** [comment]
I have not been able to reproduce the error. The speed is about the same:
1. character as it is
2. naked character
3. naked character + limit on the number of lines: 1, 255, 10000 - no difference.

Trying to reproduce on a fresh version of the game with a new character and without your mod, also failed.
