### ISSUE TITLE
Some ImGUI prompts have small size which resets to normal size after mouse move

### ISSUE THREAD

**Issue by AdamBrezik** [CleverRaven/Cataclysm-DDA#77487]
### Describe the bug

Some ImGUI prompts like examine or smash open as very small in size (or invisible) and reset to normal size after mouse move (tested with mouse show and hideKB settings).

### Attach save file

Not connected to a save file. Previously only happened to me with a custom font (consolas bold), now it happens with the default, too.

### Steps to reproduce

1. Press s to smash or e to examine.
2. See there's no prompt.
3. Move the mouse.

### Expected behavior

The prompt is shown normally from the beginning.

### Screenshots

![image](https://github.com/user-attachments/assets/5037f957-74d1-445a-9aac-40fe759196f2)
![image](https://github.com/user-attachments/assets/138c3405-efae-48eb-9172-08a7751a4b39)

### Versions and configuration

OS: Windows 10 Pro 64-bit 22H2 19045.5011
Game Version: 47225ca (tiles)
Ingame Language: Английский

**Comment by IdleSol** [comment]
Confirmed. cdda-windows-tiles-x64-2024-11-01-0729

**Comment by NetSysFire** [comment]
I am pretty sure this is a direct consequence of #77297 - as such this is a duplicate.

**Comment by AdamBrezik** [comment]
The effect seems to be the same, but I'm not experiencing this on item info window.

**Comment by AdamBrezik** [comment]
From what I can understand, #77297 is fixed. My issue still exists. Perhaps it is directly connected to custom fonts as mentioned? Should it be a request instead?

**Comment by Night-Pryanik** [comment]
I use the default fonts, and have the same issue.

**Comment by db48x** [comment]
These are all `query_popup`s. @katemonster33, you wrote that code. Do you know what’s going wrong here?

**Comment by katemonster33** [comment]
@db48x with query_popup, what happens sometimes is that the popup is initialized with this pattern:

query_popup().title("title")

I'm probably getting the syntax wrong, I'm on my phone. Anyway, with this pattern, I observed at points that the popup would size itself based off no contents, then the title would be set, except the redraw wouldn't happen until input is sent. I swear we fixed this but I need to research a bit

**Comment by db48x** [comment]
Ah, I see. Yea, I had a similar problem with the uilists. I fixed it by adding a timeout to the input handler so that we would automatically refresh the window, allowing it to immediately use the cached size from last time around. I looked at the code and found some popups that don’t have a time out; adding one to these fixed them. But the one used by waiting or sleeping (or other activities that take time) already has a timeout, so I am not quite sure what is going on.

**Comment by db48x** [comment]
I discovered that `do_turn` is creating and leaking a popup every single time around the loop while you wait. Fixing that fixes that class of popup.

**Comment by IdleSol** [comment]
cdda-windows-with-graphics-x64-2024-11-17-0712
![1](https://github.com/user-attachments/assets/3e44f377-abf0-4e19-82ea-bfaf005a6f6d)

The screen before entering the game (i.e. after character creation, but before appearing in the world).

**Comment by NetSysFire** [comment]
I can confirm this happening.

**Comment by IdleSol** [comment]
Perhaps I imagined it. But when automatically save, some small window flashes too.

**Comment by AdamBrezik** [comment]
> Perhaps I imagined it. But when automatically save, some small window flashes too.

Correct!

**Comment by NetSysFire** [comment]
Related: #78012

**Comment by AdamBrezik** [comment]
I have a feeling the situation got a bit of a setback as of late.
