### ISSUE TITLE
Repeatable crash when interacting with an item

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#77500]
### Describe the bug

Some item in the pile directly north of the character causes a repeatable segfault when interacted with

### Attach save file

[Skyland - Copy-trimmed.tar.gz](https://github.com/user-attachments/files/17596552/Skyland.-.Copy-trimmed.tar.gz)

### Steps to reproduce

1) attempt to pick up, examine, autohaul, use the item look around menu with, or use AIM on the pile of items directly north of the PC.
2) segfault

### Expected behavior

No segfault.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: cdda-experimental-2024-10-31-2132 f348de9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Railroads [railroads],
    Bombastic Perks [bombastic_perks]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17596560/crash.log)
[debug.log](https://github.com/user-attachments/files/17596561/debug.log)

Mousing over the pile in debug map editor does not cause a segfault...unless you try to edit items, which does.

Using Telekinesis (the directed_push spell effect) does _not_ cause a segfault. Throwing the pile of objects into a debugged-in lava tile does successfully delete them all.

**Comment by RenechCDDA** [comment]
Right, looks like I forgot to check if the *component* is a comestible before calling its comestible values...

https://github.com/CleverRaven/Cataclysm-DDA/blob/1e022d2315ab046821ca9ef66775c2f3b8dd61ea/src/item.cpp#L8674-L8676
