### ISSUE TITLE
Incorrect u_teleport function (or documentation?)

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#77507]
### Describe the bug

The documentation for u_teleport says

> if impassable obstacle occur, the closest point would be picked instead

But this doesn't happen in practice, you end up somewhere randomly nearby instead.

### Attach save file

[Darfur-trimmed.tar.gz](https://github.com/user-attachments/files/17601116/Darfur-trimmed.tar.gz)

### Steps to reproduce

1) Cast the spell "Traverse the Wilds" and target the cherry tree to the south, which is impassible terrain.
2) You do not end up next to the cherry tree.

### Expected behavior

You end up next to the target of the teleport, as indicated in the documentation.

### Screenshots

Before:
![Untitled2](https://github.com/user-attachments/assets/1b3c66d6-869c-4007-9b28-e37929005a53)

After:
![Untitled2](https://github.com/user-attachments/assets/fc1fd983-2fdf-45a7-b603-2851b4253b5b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: cdda-experimental-2024-11-01-0729 1e022d2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

### Additional context

The EoC controlling the teleport is here: https://github.com/Standing-Storm/Cataclysm-DDA/blob/1e022d2315ab046821ca9ef66775c2f3b8dd61ea/data/mods/Xedra_Evolved/mutations/paraclesians/arvore_eocs.json#L247

**Comment by Procyonae** [comment]
Yeah it just picks a random valid point in radius 5 around the target and has done since forced teleporting was added, I'll make a PR changing it bc closest feels like much more desirable behaviour unless I'm missing somewhere that'll trigger abundant unwanted telefragging where multiple creatures are being teled to the same impassable tile in Sky Island or something
