### ISSUE TITLE
What even is "budget steel"? 

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#77506]
### Is your feature request related to a problem? Please describe.

For reference:

> Budget Steel
> 
> Budget Steel represents poorly made steel that contains impurities, rusts easily, fractures, and generally isn’t very useful. This should be used to represent things like a Genuine Katana From Nippon that was sold on craigslist for $50, or to represent things like armor that has been sitting in a mansion for two hundred years without maintenance.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/STEEL_CRAFTING.md#budget-steel

Some problems:

Fundamentally, "budget steel" is not a material, it's just a cost description of a material. The material cost is not what's expensive when you manufacture a sword or an armor, it's the shaping and processing of it, and sharpening/hardening/tempering for functional weapons. You can buy a high end high carbon steel (SAE 1085) for [around $500 per ton on alibaba](https://www.alibaba.com/showroom/aisi-1085-high-carbon-steel.html), which would make the material cost for a 1 kg high carbon steel sword 50 cent. Manufacturing a sword with some impure steel that easily fractures would be more expensive than to make one from a decent material. 

You can buy a [set of full tang 27" and 18" inch swords in anodized black 440 stainless steel for $11.98](https://www.swordnarmory.com/dual-full-tang-ninja-warrior-double-swords-with-strap/), and from what I can gather, almost all cosplay or display swords are made from 440 stainless steel, which is the same steel used for most consumer grade kitchen knives. 

Budget steel is also meant to represent "armor that has been sitting in a mansion for two hundred years without maintenance", but it makes little sense to describe this material as "budget steel" as antiques are generally more expensive than modern replicas. I believe such budget steel antiques would be better represented by weapons and armor made with mild steel with low durability to represent rust and fractures. 

Budget steel bladed weapons do about half the normal damage, in primarily bash damage, I assume that it's mean to represent a dull edge of a display weapon or unmaintained antique. But this logic can't explain why blunt impact weapons such as maces also do half the damage of their non-inferior counterparts. 

The third type of items using budget steel are scrap items such as scrap sword and scrap helmet used in low level crafting recipes from salvaged steel. Again the term "budget steel" doesn't apply to salvaged steel. The most common way to get large quantities of scrap metal is to smash car wrecks, and car chassis are generally made from high carbon steel. 

### Solution you would like.

Remove the budget steel material.

Replace antique budget steel weapons you find in museums, pawnshops and mansions with mild steel variants that are damaged. 

Replace bladed "mall ninja" weapons with something like "unsharpened display katana", possibly with reduced weight. Add some way to sharpen it into something close to real versions but without the `DURABLE_MELEE` flag. 

If there are any references to non-antique versions of non-bladed weapons and armor, I think we can safely remove them. Bladed weapons are the most common cosplay and mall ninja weapons by quite a margin.

Replace the material in scrap armor and scrap sword with generic steel, as that's what it is.

### Describe alternatives you have considered.

Make a "pre-modern carbon steel" to use in antiques instead of mild steel. I don't think that would be much different than mild steel to warrant a new material though.

**Comment by kevingranade** [comment]
What tangible issue does this fix? If the name fit is poor, which seems to be the main issue you have, propose a different name.

Fundamentally, this indicates that the material used was not fit for purpose and is not salvageable to make something better,  which is a reasonable niche.

I'm not going over it point by point,  but your arguments are riddled with contradictions,  it's cheaper to use decent steel but mall swords do not in fact use a decent steel for their purpose,  clearly you're missing something.

**Comment by ampersand55** [comment]
> What tangible issue does this fix? If the name fit is poor, which seems to be the main issue you have, propose a different name.

My main gripe is with the material itself, which is why I think should be removed. It's used to represent different steels that I would expect to have different properties. 

To give a concrete example, let's use the katana.

https://cdda-guide.nornagon.net/item/katana_inferior

The description reads:

> A rare sword from Japan.  While it's got the right edge and weight, the pommel feels like it'll just snap off, and the blade seems pretty worn.

Which would make it seem like a poorly maintained antique, but it's properties (i.e. damage) makes it function like a mall sword with its blade dulled.

bash 17 cut 8 = 23 damage  (real katana does 5 bash + 33 cut = 38 damage).

I don't see why we have 2 separate items representing antique katana, one inferior katana and a one regular katana, when we have the tools to convey a spectrum of katanas of varying degrees of use and rust damage represented by item durability.

If we use this method of representing antique katanas and other antiques, we don't need a material that "represents poorly made steel that contains impurities, rusts easily, fractures, and generally isn’t very useful" that's mostly used on mall swords made with modern 440 stainless steel. Mall swords can be represented with generic steel, me don't need the material "budget steel" at all. 

>  your arguments are riddled with contradictions, it's cheaper to use decent steel but mall swords do not in fact use a decent steel for their purpose, clearly you're missing something.

Either I'm misunderstanding you or you're misunderstanding me. Mall swords do it fact use a decent steel for their purpose, which is to look good. 440 stainless steel is easy to polish to a shine and doesn't need much maintenance.

**Comment by kevingranade** [comment]
> when we have the tools to convey a spectrum of katanas of varying degrees of use and rust damage represented by item durability.

We don't,  that doesn't work at all. Most prominently,  that's not damage you can easily repair, which is what your suggestion would allow.

You're still not bringing up anything that *actually impacts the game*, and when you do get specific about replacements they have bad side effects.
