### ISSUE TITLE
Segfault caused by hand rolled cigarette repeatable/reproducible

### ISSUE THREAD

**Issue by zakhad** [CleverRaven/Cataclysm-DDA#77530]
### Describe the bug

Can't use hand rolled cigarettes without segfaulting

### Attach save file

[Zakhadia_BigCity-trimmed.tar.gz](https://github.com/user-attachments/files/17607263/Zakhadia_BigCity-trimmed.tar.gz)

### Steps to reproduce

Load save, try  to use either of the 2 hand rolled cigarettes on the floor and it will crash 

### Expected behavior

To not crash

### Screenshots

![image](https://github.com/user-attachments/assets/d1979931-7b48-4e60-8c51-a47bda0bd9bb)

![image](https://github.com/user-attachments/assets/b7f46abe-bfc0-404e-9fd4-714d7b3143e2)

### Versions and configuration

- OS: Windows
    - OS Version: 7
- Game Version: 55335a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Night-Pryanik** [comment]
Can confirm.
Both cigarettes have strange `(cold)` suffix that doesn't go away despite my best efforts, e.g. simply waiting outside (it's summer) or lighting a fire next to the cigarettes.

**Comment by Night-Pryanik** [comment]
@andrei8l you're referring to this very issue.

**Comment by Night-Pryanik** [comment]
Closing as duplicate.
