### ISSUE TITLE
[MoM] Likely swapped min/max in _CHANNELING_FAILURE 

### ISSUE THREAD

**Issue by emixa-d** [CleverRaven/Cataclysm-DDA#77542]
### Describe the bug

In `EOC_PSIONICS_BIOKINETICS_CHANNELING_FAILURE`, there is the following line for determining whether a failure leads to an 'out of control' thingie:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3442f08c68aac11527e5c9d77e3f974cba8b0219/data/mods/MindOverMatter/effectoncondition/eoc_on_power_use_events.json#L145

I think this was meant to do 'max' instead of 'min'. For demonstration, suppose drain=0 and metaphysics=3. Then, the probability in function of the difficulty is:

https://www.wolframalpha.com/input?i=%28150%2F1000%29*min%280%2Cx%5E2-1-3%2F2%29+for+0%3Cx%3C10

Note that it is _negative_ (because the left term is always <=0) (this also holds for other values of metaphysics with drain=0)! So, as far as this test is concerned, psionics is 100% safe if you keep your drain at 0, even if you do a difficulty=10 power at 1 intelligence with zero metaphysics knowledge and zero power levels while drunk .

IIUC this isn't completely correct reasoning since the drain might have increased by other events, but still.

Now compare this to the formula with 'max' (I added a min(1,...) to keep the probability <=1):

https://www.wolframalpha.com/input?i=%28150%2F1000%29*max%280%2Cx%5E2-1-3%2F2%29+for+0%3Cx%3C10

I think this looks much more reasonable: at low difficulty/high metaphysics, the difficulty of the spell does not affect overload chance (but drain still affects things). At high difficulty/low metaphysics, it is guaranteed to have overload (conditional on the power having failed(*)). In between, it's ... in-between.

@Standing-Storm is this indeed a min/max issue, or is psionics actually this safe?

### Attach save file

N/A

### Steps to reproduce

I can try to test whether this occurs in-game, but this is more a question of 'what _should_ things be' I think. I'm not even playing the game lately, I'm doing this for lore reasons.

### Expected behavior

Replacing `min` by `max` produces risk curves that seem more reasonable to me (in particular it _increases_ risk).

### Versions and configuration

No configuration, I'm browsing code on GitHub (master branch, commit 3442f08c68aac11527e5c9d77e3f974cba8b0219).

### Additional context

For story reasons I'm investigating how much kW an psion (electrokinetic, or telekinetic with a dynamo, or photokinetic with a solar panel) can produce (I know I quoted the biokinetic code, but other schools do similar things), and quantifying the risks involved. This particular risk factor seemed a bit off to me

**Comment by Standing-Storm** [comment]
No, you're right. There were a few other spots I swapped min/max and this looks to be one of the remaining ones.
