### ISSUE TITLE
Translations for at least one language not pulling down

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#77579]
### Describe the bug

Someone recently started the Portuguese - Portugal translation project in Transifex.  They have been working long enough that it should be showing up in game given the timeline for when localization PRs have been created and merged.  So I went and looked and I can't find anything that makes a limit on what langauges get included in the downloads.   

### Attach save file

N/A

### Steps to reproduce

https://app.transifex.com/cataclysm-dda-translators/cataclysm-dda/dashboard/  

### Expected behavior

I'm not sure at what point a language folder is created in the game files.  

### Versions and configuration

Current experimentals

### Additional context

@BrettDong @Qrox I apologize for pinging you both but I'm not sure who else would have a better idea of whats going on here.

**Comment by themaster567** [comment]
The following languages are present in-game as of [2024-11-03-2221](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-11-03-2221)
English
Arabic
Czech
Danish
German
Greek
Spanish (Argentina)
Spanish (Spain)
French
Hungarian
Bahasa Indonesia
Icelandic
Italian
Japanese
Korean
Norwegian
Dutch
Polish
Portuguese (Brazil)
Russian
Serbian
Turkish
Ukranian
Chinese (Simplified)
Chinese (Traditional)

---------------

The following languages have strings in Transifex but have yet to be shipped in a release:
Portuguese (Portugal)
Swedish
Esperanto
Irish
Persian
Filipino

There are more languages in Transifex than these, but they lack any strings.
----------------

My speculation now is that translation below a certain threshold simply do not get shipped. This would answer the question, but it would be nice to know what that threshold is.

**Comment by themaster567** [comment]
Consolidating information from the Discord: the Portuguese (Portugal) translator posted a screenshot showing that there are no errors holding up their translation
![image](https://github.com/user-attachments/assets/52cd3953-9d7a-4aef-a069-4e144514ce39)
