### ISSUE TITLE
.303 5-round charger clip spawns loaded in gun stores

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#77580]
### Describe the bug

The .303 5-round charger clip incorrectly spawns loaded when found in the magazine loot set found in gunstores.

### Attach save file

N/A

### Steps to reproduce

1. Spawn a gunstore that has magazines in its loot.
2. Check magazines.  The .303 will be the only one loaded if it spawns.

### Expected behavior

All magazines in gun store magazine loot should be empty, baring exceptional circumstances where an employee was very careless.  In such a case though, it should be equally likely that any magazine is loaded or partially loaded.

### Screenshots

![image](https://github.com/user-attachments/assets/d83ff5d0-0cc5-480d-bb14-c13c461c7f1c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 3edfea1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by TheDarkMaster13** [comment]
On reflection, this item probably should not even be in the magazine tables.  It's a stripper clip and goes in the ammo category.

**Comment by Holli-Git** [comment]
/confirm 
![image](https://github.com/user-attachments/assets/e208c399-a153-4616-a6eb-cd49658058d9)
I'm looking into it right now
