### ISSUE TITLE
Steel things are really burdensome and UNNECESSARY

### ISSUE THREAD

**Issue by ShuCuoMao** [CleverRaven/Cataclysm-DDA#77609]
### Is your feature request related to a problem? Please describe.

Since those steel things appeared,they show nothing necessary.Steel things is not special and fun at all, e.g. weapons just increase a little bit damage,so as to armors.This set of thing just make items split into 3 resemble copies.All those steel things just force us to craft things like "high carbon steel" meaninglessly,and that will decrease our interest on what is really fun that forging weapons and armor.

### Solution you would like.

Delect all these steel things.After all,those steel solely works on weapons and armor,so it's not too late to do so.Or it could be even more burdensome if you want to keep it and promote this system into all items in game.

### Describe alternatives you have considered.

give back the normal recipe of forging with just "steel",you will see we really dont want to bother to craft those "high steel" piece of 
 ( ).

### Additional context

forging with different material is different in real world,but not so in cdda.We just wait for the same 99% bar.So it's really unnecessary to distinguish difference between mild steel and high steel.I can just imagine that I used high steel and quencing my sword,in 0.F3

**Comment by GuardianDll** [comment]
The idea is not having generic steel and three different types of graded steel, the idea is having three different types of graded steel full stop
Removing it is akin to removing different types of the same round because there is too many rounds
