### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by RangerFromBaja** [CleverRaven/Cataclysm-DDA#77602]
### Describe the bug

seems to be related to npc trying to avoid friendly fire, after I disabled the option in the npc rules it didn't crash

### Attach save file

[Miamisburg-trimmed.tar.gz](https://github.com/user-attachments/files/17635286/Miamisburg-trimmed.tar.gz)

### Steps to reproduce

1. turn off safe mode
2. hold tab until it crashes

### Expected behavior

not crash

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 19807c7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17635203/crash.log)
[debug.log](https://github.com/user-attachments/files/17635240/debug.log)

**Comment by PatrikLundell** [comment]
/Confirmed

Crashes in npcmove.cpp operation npc::wont_hit_friend due to access violation when trying to get dispersion from a ruger when the gun is out of ammo.
