### ISSUE TITLE
Use sewing kit > molotov cocktail

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#7761]
You can use a sewing kit to repair molotov cocktails, and damage them with low skill.
Amusing!
##

**Comment by OzoneH3** [comment]
Bug still present

**Comment by illi-kun** [comment]
Tested on the current experimental build - it still happens.

**Comment by Night-Pryanik** [comment]
We make rag sturdier by using tailor's kit, the bottle is intact. Don't think this is a bug (not a that big, at least).
