### ISSUE TITLE
EOC lacking beta talker may cause death of the PC

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#77629]
### Describe the bug

Several weeks ago, someone in the community asked me to find out why his avatar dies after a certain time.
It turns out that his save is corrupted, resulting in one invisible `MISSION_GET_INHALER` hides in the list.
After the deadline of the mission coming, the error below will popup.
```
 DEBUG    : Tried to use an invalid beta talker.  

 FUNCTION : actor
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 2593
 VERSION  : 93c608c
```
As there is no NPC bound with the mission, the `npc_die` EOC will be called on the alpha talker, killing your PC.

### Attach save file

[Cowarts-trimmed.tar.gz](https://github.com/user-attachments/files/17650372/Cowarts-trimmed.tar.gz)

### Steps to reproduce

The save in question was deleted, but we can use debug menu to reproduce it.
(Use the save above to skip step 1 and 2):

1. Play a new game with a start NPC.
2. Debug add a mission Find Inhaler/Find Antibiotics to the NPC, receive it and debug fail it, killing the NPC.
3. Debug fail the mission again, ignore the error, and found out your PC got killed.

### Expected behavior

Do not use alpha talker carelessly when beta talker is missing.

### Screenshots

![2024-11-07 005437](https://github.com/user-attachments/assets/a3481642-2cf0-4b71-b5db-496d6a6b27f0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 93c608c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
The debug menu's mission editor sets the avatar as the assigning character, the assigning character is killed when the mission is failed. This is not an issue with the mission, it is an issue with assigning missions through the debug menu.
