### ISSUE TITLE
SIGSEGV from [E]ating a joint or hand-rolled cigarette that you have crafted yourself

### ISSUE THREAD

**Issue by Maarifrah** [CleverRaven/Cataclysm-DDA#77631]
### Describe the bug

Repeatable segmentation fault from (Shift-e) eating within range of a hand-rolled cigarette or joint that you have crafted yourself.

### Attach save file

[Dahlgren-trimmed.tar.gz](https://github.com/user-attachments/files/17651823/Dahlgren-trimmed.tar.gz)

### Steps to reproduce

1. Create a character with the Punk Rock Dude profession (It starts with the necessary crafting materials already).
2. Craft either a joint or a hand-rolled cigarette. Either will work.
3. Shift-E to eat. So long as you are within eating range of the hand-rolled cigarette/joint that you've crafted, this will produce a segmentation fault and a crash to desktop.

### Expected behavior

I expected to eat a delicious joint and get delightfully marinated as a result.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 6b98896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[Crash & Debug Logs.zip](https://github.com/user-attachments/files/17651848/Crash.Debug.Logs.zip)

The crafting stage appears to be necessary to reproduce this issue, as spawning in a joint or hand-rolled cigarette through the debug menu didn't cause a crash. This issue may apply to items other than the two I've listed. I did test 'Boring Sandwich,' which didn't result in a segmentation fault, so I know that not all comestibles/crafted items produce this crash.

**Comment by RenechCDDA** [comment]
Resolved by #77551

If you encounter this issue on that version or newer let us know and it can get reopened, etc.
