### ISSUE TITLE
[Dino Mod] Tamed dinos from a nest spawn return to nest after tamed.

### ISSUE THREAD

**Issue by Cddasurvivor** [CleverRaven/Cataclysm-DDA#77653]
### Describe the bug

Any dino tamed at a nest will walk directly to the nest spawn

If you do not tie them they will break away from you and run back to the nest, leading by a rope doesn't matter they all run back to the nest spawn.

*Might need to make  a separate report but it also tends to makes the non tamed dinos hostile to the tamed ones at the nest.

### Attach save file

N/A

### Steps to reproduce

1)Tame a dino at a nest spawn.
2)Attempt to lead them by a rope and they ignore attempts to lead it and return to the nest.  Mount the dino and move away, dismount and it will instantly attempt to make a path back to the nest including breaking anything in it's way.

### Expected behavior

To act as a normal tamed animal and follow you or at least go neutral.

### Screenshots

n/a

### Versions and configuration

experimental 2024-11-07-0841

**Comment by RenechCDDA** [comment]
This can be reopened if you have a save.
