### ISSUE TITLE
Game Locks Up when asking NPC about nearby farm

### ISSUE THREAD

**Issue by ScionOfEris** [CleverRaven/Cataclysm-DDA#77666]
### Describe the bug

When talking to an NPC, the game locked up.  I think the NPC was going to give the directions to the Isherwood Farm, and the game couldn't handle something about it.

The only resolution to the lockup was a force quit.

### Attach save file

[Onamia-trimmed.tar.gz](https://github.com/user-attachments/files/17671064/Onamia-trimmed.tar.gz)

### Steps to reproduce

1) talk to NPC
2) choose Not Yet
3) choose Heard anything about the outside world
4) choose Anyone nearby I should meet
5) choose Seems like a deal to me

### Expected behavior

I'm not sure if it was supposed to assign a quest or was a simple map reveal, but in any case a lock up is not expected.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: 30ea495 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Hope [no_hope]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/17671073/debug.log)

**Comment by PatrikLundell** [comment]
Failed to reproduce. The next dialog section appears after a split second using the just downloaded and compiled master.

**Comment by RenechCDDA** [comment]
The version they report using is one of the 0.H candidates, it is possible the behavior is different there.

**Comment by ScionOfEris** [comment]
I realized I had forgotten to update the game.  I was using the .H stable candidate from 10/29.

I just updated to the 11/06 version, and the behavior is the same, it still locks up.

This is a Stable Candidate issue, not an experimental one.  I didn't see a way to tag it as such.

**Comment by ScionOfEris** [comment]
This was a Stable Candidate issue, not experimental.
However, I had forgotten to update the game.  This was a problem with the 10/29 build.

I just tried on the 11/06 build.  It lags a bit, but then works.

Sorry about that, closing this.

**Comment by NetSysFire** [comment]
Hang on, if this is an issue for the release candidate, this might be worthy of a backport as this is a common enough issue to encounter.

**Comment by NetSysFire** [comment]
Oh you meant its fixed in the stable release candidate and not experimental. If this is fixed in the latest release candidate, then this can remain closed.
