### ISSUE TITLE
SIGSEGV:segmentation fault on certain actions

### ISSUE THREAD

**Issue by thexcvjordanxcv** [CleverRaven/Cataclysm-DDA#77669]
### Describe the bug

When crafting, moving or dropping certain items the game will crash

### Attach save file

[Blackwood-trimmed.tar.gz](https://github.com/user-attachments/files/17674398/Blackwood-trimmed.tar.gz)

### Steps to reproduce

Hit consume keybind

### Expected behavior

Menu should pop up with list of edibles

### Versions and configuration

cdda-windows-tiles-sounds-x64-2024-11-03-2221

### Additional context

[debug.zip](https://github.com/user-attachments/files/17674463/debug.zip)

**Comment by thexcvjordanxcv** [comment]
Thanks for the link to post this bean!

**Comment by RenechCDDA** [comment]
Resolved by #77551

If you encounter this issue on that version or newer let us know and it can get reopened, etc.
