### ISSUE TITLE
documentation bug: chezzo links in Getting Started

### ISSUE THREAD

**Issue by SamGondra** [CleverRaven/Cataclysm-DDA#77670]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributors-Guide-Getting-Started includes several broken chezzo links

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

### Additional context
sorry if this very barebones

**Comment by RenechCDDA** [comment]
Killed 'em. Thanks for the heads up.
