### ISSUE TITLE
Hair dye sells for a comically high amount post-apocalypse.

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#77683]
### Describe the bug

Everyone knows hair dye is an absolute necessity in any post apocalyptic setting, but the hair dyes we have sell for 30 dollars. That's more than some guns and tools sell for. It's definitely silly.

### Attach save file

N/A

### Steps to reproduce

1. locate barbershop or spawn in hair dye. look at it's value.

### Expected behavior

I think hair dye should sell for 2-3 dollars at most.

### Screenshots

![image](https://github.com/user-attachments/assets/bbb47f83-56d9-46fd-8136-2e479620f76b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-11-03-2221 6b98896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
]

**Comment by Little-119** [comment]
Of course it's vital, how else are you going to maintain your post-apocalyptic spikey leather jacket-wearing neon hair dyed biker gang?
