### ISSUE TITLE
Expand u_forget capabilities

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#77689]
### Is your feature request related to a problem? Please describe.

I would like for u_forget_recipe to be expanded with a u_forget_recipe_category.  That way we could reduce line count when recipes have to vanish because a trait is removed.
"type": "recipe_category",
    "id": "CC_XEDRA",
    "recipe_subcategories": [
      "CSC_ALL",
      "CSC_XEDRA_RESEARCH",
      "CSC_XEDRA_WEAPONS",
      "CSC_XEDRA_ARMOR",
      "CSC_XEDRA_TOOLS",
      "CSC_XEDRA_ROBOTS",
      "CSC_XEDRA_MISC",
      "CSC_XEDRA_ALCHEMY",
      "CSC_XEDRA_GRACKEN",
      "CSC_XEDRA_ELEMENTAL"

### Solution you would like.

To remove a whole recipe subcategory in one go.  This would also benefit future changes to recipes not having to add individual recipes to the eoc's here. #77685

### Describe alternatives you have considered.

I dunno there are lots of people smarter than me

**Comment by Procyonae** [comment]
Would the same support for learn recipe be useful?

**Comment by Maleclypse** [comment]
> Would the same support for learn recipe be useful?

Yes I think it would be.
