### ISSUE TITLE
Linux builds are broken due to extra ;

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#77709]
### Describe the bug

See https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/11757640468/job/32755299670#step:18:63

### Attach save file

n/a

### Steps to reproduce

1. Try to find recent Linux builds
2. There are none
3. Check the actions
4. Fails because at least double semicolon

### Expected behavior

It builds.

### Versions and configuration

n/a

**Comment by GuardianDll** [comment]
Resolved by #77702
