### ISSUE TITLE
Small squeeze tube. Inaccuracy in description

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77710]
### Describe the bug

The description says 3 ml of glue, and the pocket volume is 4 ml.

https://github.com/CleverRaven/Cataclysm-DDA/blob/a05e593bf581eb76bc946fbabddc554f7e361e1c/data/json/items/containers/containers.json#L704

https://github.com/CleverRaven/Cataclysm-DDA/blob/a05e593bf581eb76bc946fbabddc554f7e361e1c/data/json/items/containers/containers.json#L715

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

Correspondence between the description and the internal volume 

### Versions and configuration

master

### Additional context

I don't know the volume of the actual tube.

**Comment by ninersheep** [comment]
Are you suggesting that packaging should take no space?

**Comment by IdleSol** [comment]
This is the volume of the pocket. Pack volume:
https://github.com/CleverRaven/Cataclysm-DDA/blob/a05e593bf581eb76bc946fbabddc554f7e361e1c/data/json/items/containers/containers.json#L707
