### ISSUE TITLE
Fire makes fungus spread faster

### ISSUE THREAD

**Issue by alef** [CleverRaven/Cataclysm-DDA#77743]
### Describe the bug

Fire makes the fungal bed to grow faster then the fire can burn it to ashes.

Under the debugger, it seems [this line](https://github.com/CleverRaven/Cataclysm-DDA/commit/826ab0d56100cf80f11a4f751aa1be8f7e7ba256#diff-6a88db17632ab81a842663959762bcea7cd0866fd63dfbbdfa2b8fddb72406a7R1117) added in #77605 causes lot of calls to `create_spores`.

### Attach save file

N/A

### Steps to reproduce

1. Make a new debug world, enter with a new debug player
2. Teleport to a fungal spot
3. Light fungal bed on fire
4. Wait 5 minutes

### Expected behavior

Fire to burn fungal bed without expanding it.

### Screenshots
One tile on fire:<br/>![start](https://github.com/user-attachments/assets/f013f269-6a44-4ab8-b655-a2dd345e6938)

After 30 minutes:<br/>![30m](https://github.com/user-attachments/assets/7f8fc5b0-75ca-401f-888a-d7afc7684798)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 66098b4c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Reported on Discord `#player-help` by `RjThePerson`

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/silly-bug-fungal-mutant-fire-consuming-my-world/29515/1

**Comment by latogato** [comment]
I mentioned on that forum link, but i mention here too, it seems to me, the fungal bed is not destroyed by the fire, there are wood ashes on the tiles on fire, but the fungal bed is still there.
