### ISSUE TITLE
stream has excessive garbage

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#77780]
### Describe the bug

i randomly went nearby a stream, and noticed a HUGE pile of items across the river, the pile of items seems related to the garbage item pool, i appreciate the idea of stuff being thrown into the river but this is too much?
![image](https://github.com/user-attachments/assets/8a973c36-fad4-4597-884e-d39522450683)
![image](https://github.com/user-attachments/assets/ace99131-5c87-4022-878b-53769183b335)

### Attach save file

[Talpa-trimmed.tar.gz](https://github.com/user-attachments/files/17712564/Talpa-trimmed.tar.gz)

another save file provided in the discord

[Canyon Lake-trimmed.tar.gz](https://github.com/user-attachments/files/17712661/Canyon.Lake-trimmed.tar.gz)

### Steps to reproduce

load save and just follow the stream, it's too much garbage!

### Expected behavior

a reasonable amount of garbage, maybe much more sparse, and clumped in some parts

### Versions and configuration

Windows 10 tiles english, 2024-11-12-0435
modlist:[
  "dda",
  "magiclysm",
  "no_npc_food",
  "no_fungal_growth",
  "Arthropod_Alliances",
  "Tamable_Wildlife",
  "stats_through_kills",
  "speedydex",
  "personal_portal_storms",
  "blazeindustries",
  "rub_reb",
  "translate_dialogue",
  "bombastic_perks",
  "No_Person"
]

**Comment by Maarifrah** [comment]
I experienced this in an innawoods playthrough earlier today.

**Comment by TheMurderUnicorn** [comment]
Taking a look at this, it seems like it might be as simple as lowering a couple itemgroups spawn chances that are much too high.  If I don't bump into anything more significant I'll take a shot at rebalancing this.
