### ISSUE TITLE
Debug menu. Reveal map. Where did the item go?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77807]
### Describe the bug

cdda-windows-tiles-x64-2024-11-01-0729
![pic 1](https://github.com/user-attachments/assets/7a96efa5-9f3d-4373-99f5-5ff32ecc3124)

cdda-windows-tiles-x64-2024-11-13-0609
![pic 2](https://github.com/user-attachments/assets/31bddc1a-4c4d-416b-bc6e-5171fc5c1926)

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

cdda-windows-tiles-x64-2024-11-13-0609

**Comment by Procyonae** [comment]
It's in the overmap editor which the map becomes if debug mode is enabled (for example if you use quick setup) as of #77339
