### ISSUE TITLE
[Xedra Evolved] Blocky pistol segmentation fault

### ISSUE THREAD

**Issue by Sofistico** [CleverRaven/Cataclysm-DDA#77809]
### Describe the bug

When i empty a magazine of the blocky pistol and try to go to the wield item menu, the game crashes.

### Attach save file

[Anandale-trimmed.tar.gz](https://github.com/user-attachments/files/17733027/Anandale-trimmed.tar.gz)

### Steps to reproduce

1. With the gun wielded, fire all ammo on the approaching zombies
2. After gun is empty, go to the wield item menu
3. Note the crash

### Expected behavior

No crash and able to unwield or wield any other item

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: cdda-experimental-2024-11-13-0827 f1fa949 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm],
    Mana Cores [manacores],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/17733048/debug.log)
[crash.log](https://github.com/user-attachments/files/17733049/crash.log)

**Comment by Sofistico** [comment]
Weirdly, it only happens when all ammo is shot rather than say being unloaded from the gun

**Comment by RenechCDDA** [comment]
I believe this was resolved with #77887

Please comment if you're still experiencing this issue on a version newer than that PR.
