### ISSUE TITLE
Fungal Blooms extremely annoying, possibly a trap for new players?

### ISSUE THREAD

**Issue by emomicrowave** [CleverRaven/Cataclysm-DDA#77802]
### Describe the bug

There are simply way to many fungaloids generating fungal beds all over the world. I started in a prison, and by the time I escaped, the whole prison was surrounded by fungal beds. After setting it on fire, and realizing I just made things worse (#77743), I debug teleported out of the prison. But every road has multiple fungal enemies. Long distance teleport allows you to see groups of enemies on a tile, and it made me realize how bad the situation is.

The way the situation is now, it requires the player to immediately engage every single fungal enemy they see immediately, otherwise you risk the whole area becoming uninhabitable. But engaging recklessly in combat on the first sight of an enemy isn't the intended way to play the game, I would think.

**EDIT:** It seems that I did not see a fungal tower close-by (thank you @IdleSol). This certainly explains the ridiculous amount of fungaloids I've been finding.

Maybe this issue can be closed, but on the other hand the infection radius feels too big, and I don't know where I would look for information about fungal enemies, and finally I wonder if it is possible to stop towers in range of the game starting point. (in my case the prison). 

### Attach save file

[Pronto-trimmed.tar.gz](https://github.com/user-attachments/files/17730234/Pronto-trimmed.tar.gz)

### Steps to reproduce

- Load the save
- Walk the road between Belmont and the evac shelter north-east from Belmost, and observe amount of fungaloids and fungal beds
- Debug -> Teleport -> Long range teleport
- Browse different spots on the map and notice how many groups of FUNGI enemies there are
  - e.g the road west of Belmont
  - the church west of Belmont

### Expected behavior

~1. There should be simply way fewer fungaloids spawning at all~
~2. Maybe they should be spawning at concrete places, not simply anywhere~
3. Reduce range of fungal blooms
4. Somehow inform players that there is a fungal bloom in the area
5. No fungal blooms spawning within 20 tiles of the game start

### Screenshots

![cdda_fungal_map](https://github.com/user-attachments/assets/9a0e2502-7270-41ac-8d00-97f9ade7cb76)

Legend: 
- Red marks a group of fungal monsters, detected by Debug -> teleport -> long range
- Pink is places I visited manually and observed fungals

Also I did not scan every single tile on the map, as it was getting tedious.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-11-10-0706 66098b4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter]
]

**Comment by IdleSol** [comment]
My personal opinion. The amount of mushrooms is not a mistake. That's their threat level.

Although I agree that players have two options:
1. Engage in combat immediately upon encounter and hope for a miracle.
2. Avoid the mushrooms until you're ready.

And that's annoying.

Again, my personal opinion, it would be better if they spread more slowly, but did not depend on the reality bubble. Then the player would not have the feeling that he is late: will he have time to kill or will everything around be covered in mushrooms. Instead, the player would be faced with the fact: this area is already contaminated. He no longer needs to rush. All he needs to decide is to look for another area or try to clear this one.

**Comment by emomicrowave** [comment]
Personally the idea that it's spreading at all, at however slow pace, would stress me out a lot.

But to address the options, I made the bug report because I felt that option 2 basically impossible right now. It's actually feels impossible to find a reality-bubble sized area on the map that is free of fungals.

**Comment by IdleSol** [comment]
<details><summary>Spoiler</summary>

![pic 1](https://github.com/user-attachments/assets/c8535f10-f864-48c6-80c8-a6619b36f714)
</details> 

There's a tower near the city. The infection radius is about 20 tiles. Provided they didn't get into the reality bubble.

**Comment by emomicrowave** [comment]
Thank you that certainly explains the ridiculous amount of fungals. I edited the post. While I recognize that this issue may be closed now, maybe it's still worth discussing fungaloid balance, how close blooms and towers can spawn to the game start, and how can players be better informed that there is a fungal tower nearby. For example I was stuck for a few in-game days in the prison and had no reason to look outside or look at the map. Finally going out was a nightmare.

**Comment by kevingranade** [comment]
You discovering that you need to evacuate an area is a completely intended outcome of the way that several different enemy types generate.
