### ISSUE TITLE
What's going on with the order in which font settings are loaded?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77803]
### Describe the bug

In thread #77756 I was advised to change `fonts.json` to fix the font. During the experiments, I got strange results.

So there are two files in the game:
- `data/fontdata.json`
- `config/fonts.json`

My understanding is as follows (possibly incorrect):
- `fontdata.json` - a file with default fonts, serves as a template for `fonts.json` when the game is first launched.
- `fonts.json` - font settings. This is the file the game uses when loading. If there is no entry in the file, it looks at `fontdata.json`

The experiments were conducted on a freshly downloaded version of the game: `cdda-windows-tiles-x64-2024-11-13-0609`

A world and a character will be created at the first launch. And we will look at the result using the example of a smartphone, in the part responsible for flags. Standard world, standard survivor, start in a shelter. After which the game is saved, and the save is used for subsequent tests. At the end of each test, the game client closes.

**TEST 1.** Unpacking the archive and first launch of the game

Contents of the `data/fontdata.json` file:
```
{
  "//1": "If more than one font is specified for a typeface the list is treated as a fallback order.",
  "//2": "unifont will always be used as a 'last resort' fallback even if not listed here.",
  "typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "gui_typeface": [
    "data/font/Roboto-Medium.ttf",
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "map_typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "overmap_typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ]
}
```
File `config/fonts.json` - missing

![pict 1](https://github.com/user-attachments/assets/784c525d-fcc6-46b6-950b-6f2aa2869b59)

**TEST 2.** Second loading of the game.

File data/fontdata.json unchanged
Contents of file config/fonts.json, created automatically during test 1:
```
{
  "typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
  "map_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
  "overmap_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ]
}
```
Note that the `gui_typeface` section is missing from `fonts.json`

The result is the same, which is logical in principle.
![pict 2](https://github.com/user-attachments/assets/8ce363d0-311b-4ef7-bd6d-920c696d2588)

**TEST 3.** Testing the assumption that `fontdata.json` serves as a template for `fonts.json`

Let's remove `fonts.json` and make changes to `fontdata.json`:
``` diff
{
  "typeface": [
--    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "gui_typeface": [
--    "data/font/Roboto-Medium.ttf",
--    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "map_typeface": [
--    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "overmap_typeface": [
--    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ]
}
```
![pict 3](https://github.com/user-attachments/assets/d4a94af6-88e4-4c34-ab06-05eb84f6d5ac)

Contents of `fonts.json` after exiting the game:
```
{
  "typeface": [ "data/font/unifont.ttf" ],
  "map_typeface": [ "data/font/unifont.ttf" ],
  "overmap_typeface": [ "data/font/unifont.ttf" ]
}
```
This means that the assumption is most likely correct.

**TEST 4.** Reload the game.
The `fonts.json` and `fontdata.json` files are unchanged after the 3rd test.

![pict 4](https://github.com/user-attachments/assets/28a33376-ad30-498e-adf8-e7452551cec4)

Suddenly the `Roboto-Medium.ttf` font appears. Where from?
For ease of comparison, 3 and 4 screenshots in gif animation:
![pict 3-4](https://github.com/user-attachments/assets/a6e6fc89-15e7-42c0-9ef3-9eed4dad8dcb)

Checking `fonts.json` and `fontdata.json` files after exiting the game. No changes.

And a comparison of screenshots 2 and 4, to compare the font used in the inventory window. To make sure that different fonts are used there.

![pict 2-4](https://github.com/user-attachments/assets/e8474676-d26f-4a7f-9a08-b2b8a6761c6c)

**TEST 5 and 6.** Repeat of tests 3 and 4, with `Terminus.ttf` font
Delete `fonts.json` and correct `fontdata.json`:
```diff
{
  "typeface": [
++   "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "gui_typeface": [
++    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "map_typeface": [
++   "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "overmap_typeface": [
++    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ]
}
```
In fact, this is the original version from which the `Roboto-Medium.ttf` font in the `gui_typeface` section has been removed.

The result repeats tests 3 and 4. That is, the font changes, but after re-entering, it again turns into Roboto-Medium.ttf.

`fonts.json` :
```
{
  "typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
  "map_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
  "overmap_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ]
}
```
The `Terminus.ttf` and `unifont.ttf` fonts are very similar, so here is a gif animation from screenshots 3, 5 and 6 of the tests:
![pict 3-5-6](https://github.com/user-attachments/assets/31eefc74-c73e-4391-8379-f867045d051d)

**TEST 7.** Add the `gui_typeface` section to the `fonts.json` file
The `fontdata.json` file without changes:
```diff
{
  "typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "gui_typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "map_typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "overmap_typeface": [
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ]
}
```
The fonts.json file:
```diff
{
  "typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
++  "gui_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
  "map_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
  "overmap_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ]
}
```
![pict 7](https://github.com/user-attachments/assets/01f41522-37bc-4116-9b8c-7c758b9bda18)

Completely repeats the result of test 5. But unlike it, it is saved after exiting the game and re-entering.

**TEST 8.** Additional test to confirm that `fonts.json` file takes precedence over `fontdata.json`
```diff
{
--  "typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
++  "typeface": [ "data/font/Roboto-Medium.ttf"],
--  "gui_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
++  "gui_typeface": [ "data/font/Roboto-Medium.ttf" ],
--  "map_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ],
++  "map_typeface": [ "data/font/Roboto-Medium.ttf" ],
--  "overmap_typeface": [ "data/font/Terminus.ttf", "data/font/unifont.ttf" ]
++  "overmap_typeface": [ "data/font/Roboto-Medium.ttf" ]
}
```
The `fontdata.json` file without changes.

![pict 8](https://github.com/user-attachments/assets/b15467d9-b64d-439b-af09-e71218c5e4e1)

### Attach save file

n/a

### Steps to reproduce

n/a

### Expected behavior

1. The `fonts.json` file should contain the `gui_typeface` section by default
2. The game should focus on the `fonts.json` file. If it does not exist, on `fontdata.json`. There should be no situations like in test 4. That is, the font should not be hardcoded somewhere in the game files.
3. Optional. Access to changing the font through the game menu, and not by editing the configuration file. (Provided that this state of affairs is not temporary, until the full transition to ImGui.)

### Versions and configuration

cdda-windows-tiles-x64-2024-11-13-0609

### Additional context

If you leave the `fonts.json` file empty, the game refuses to load without any messages.

**Comment by CLIDragon** [comment]
I appreciate the dedication to testing! From what I can see, there are two problems here:
1. gui_typeface isn't being auto-populated
2. Roboto is randomly appearing.

**Comment by IdleSol** [comment]
>Does that sound correct?

Yes

**Comment by ZhilkinSerg** [comment]
Try binary with this patch:

```PATCH
diff --git a/src/font_loader.cpp b/src/font_loader.cpp
index 47dea9618e..0fd02c1d72 100644
--- a/src/font_loader.cpp
+++ b/src/font_loader.cpp
@@ -28,9 +28,6 @@ void font_loader::load_throws( const cata_path &path )
         } else {
             config.read( "gui_typeface", gui_typeface );
         }
-        if( gui_typeface.empty() ) {
-            gui_typeface.emplace_back( PATH_INFO::fontdir() + "Roboto-Medium.ttf" );
-        }
         if( config.has_string( "map_typeface" ) ) {
             map_typeface.emplace_back( config.get_string( "map_typeface" ) );
         } else {
@@ -61,6 +58,7 @@ void font_loader::save( const cata_path &path ) const
             JsonOut json( stream, true ); // pretty-print
             json.start_object();
             json.member( "typeface", typeface );
+            json.member( "gui_typeface", gui_typeface );
             json.member( "map_typeface", map_typeface );
             json.member( "overmap_typeface", overmap_typeface );
             json.end_object();
```

[cataclysm-tiles-77803fixed.zip](https://github.com/user-attachments/files/17750329/cataclysm-tiles-77803fixed.zip)

**Comment by IdleSol** [comment]
cdda-windows-tiles-x64-2024-11-13-0609

1. This fixes the problem with `fonts.json` on a clean install.
2. If after unpacking the archive, transfer the old configuration (including `fonts.json`), the game will use `unifont.ttf`.
