### ISSUE TITLE
Well into game, and found some food that is marked as (fresh)

### ISSUE THREAD

**Issue by jeremyosborne** [CleverRaven/Cataclysm-DDA#7780]
See screen shot. Year one, day 13 of winter. Using build: 2960fdc2642cbabfbff670e1f9d919995c3e0d70

![screen shot 2014-05-29 at 7 57 18 pm](https://cloud.githubusercontent.com/assets/160639/3126613/5ec9dfac-e7a6-11e3-9764-b188c23d643a.png)

**Comment by mugling** [comment]
Fixed in `master`
