### ISSUE TITLE
style.yml corruption?

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#77819]
### Describe the bug

A couple of days ago I had a local corruption of my project environment, resulting in a re-downloading and setting up of it again. Somewhere in that process the github version of my "master" was also updated from the freshly downloaded "real" master.
Since then I've suffered from git spam about failed runs of various git things, with the worst one being "Run failed at startup: Stale issue handler - master (1692e4a)" failing about once per hour with the error

```
Invalid workflow file: .github/workflows/stale.yml#L31
The workflow is not valid. .github/workflows/stale.yml (Line: 31, Col: 26): Unexpected symbol: '""'. Located at position 73 within expression: contains(fromJson('["01", "02", "03", "04", "05", "06"]'), env.time) && "" || "<Suggestion / Discussion>"
```

I have no idea why this is being run, but apparently it has been for 400 pages of logs over the years, so it's probably intended for some reason. Examination of the file seems to indicate it looks the same as the "real" master version, including the pair of double quotes.

I think I've gotten rid of the other spam by killing them via the git web UI, but this can't be killed as it never runs for long enough to be killed (or they run seldomly enough not to have reappeared yet).

### Attach save file

N/A, it's a github issue.

### Steps to reproduce

I can't reproduce it since I don't know how it happens...

### Expected behavior

Github not wasting resources on running garbage runs over unused repos present only because they seem to be mandatory, even though they're not really used for anything and typically are badly out of date.

### Versions and configuration

N/A, it happens on the github server.

**Comment by kevingranade** [comment]
Do you want actions running on your local repo? If not you can go to settings -> actions -> general -> Actions Permissiobs and tick "Disable actions".

If so you can tick the last option "Allow PatrikLundell, and select non-PatrikLundell, actions and reusable workflows" and configure which ones run.
