### ISSUE TITLE
[0.H RC] crash (segvault) monster fusion?

### ISSUE THREAD

**Issue by SamGondra** [CleverRaven/Cataclysm-DDA#77844]
### Describe the bug

I am having a semi repeatable crash in the attached game,
seeing the log I assume that there is a devourer trying to eat something that it probably should not. (maybe the quest Zombie for the Horde master quest?)

### Attach save file

[Reform-trimmed.tar.gz](https://github.com/user-attachments/files/17748221/Reform-trimmed.tar.gz)

### Steps to reproduce

load the save and if you simply wait | around half an hour it seems to happen

### Expected behavior

no crashes?

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.3; Release: 21.3; Codename: virginia; 
- Game Version: a8ec133 [64-bit]
- Graphics Version: Tiles
- Game Language: English <color_dark_gray>(100.0%)</color> [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

### Additional context

[logs.tar.gz](https://github.com/user-attachments/files/17748388/logs.tar.gz)

**Comment by SamGondra** [comment]
I checked again with the trimmed save, and it crashed after using the wait command to wait for 30 minutes.

**Comment by mqrause** [comment]
I also can't reproduce it with this save. It's possible the crash simply doesn't happen on windows. There is fusion happening with a zombie master, but it completes without issues.

**Comment by esotericist** [comment]
downloaded most recent 0.H rc (2024-11-22-0429), loaded save, attempted to wait, reproduced error pretty close to instantly.

![image](https://github.com/user-attachments/assets/5990c3d2-339c-4953-aa7d-5b8a1692df9a)

[crash.log](https://github.com/user-attachments/files/17869157/crash.log)


- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 24.04.1 LTS; Release: 24.04; Codename: noble; 
- Game Version: 4c8fd24 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

**Comment by kevingranade** [comment]
Fixed, don't know why it didn't auto-close?
