### ISSUE TITLE
Autodrive ruins everything

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#77847]
### Describe the bug

I use autodrive fairly often, but recently it keeps smashing into stuff, almost decommissioning my vehicle.

### Attach save file

N/A, trivial

### Steps to reproduce

Get car (A large one, ~the size of a cube van)

### Expected behavior

Regular path & no dmg.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: cdda-experimental-2024-11-12-1726 b8a6d08 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    Mythical Martial Arts [MMA],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Holli-Git** [comment]
By any chance do you lack the drivers license proficiency?

**Comment by PGR-14** [comment]
Nope, I've got the driving proficiency, & an amendment to the problem, it seems to only happen at the destination, meaning it'll get there, then decide to immediately crash into a log or something.

**Comment by RenechCDDA** [comment]
It does stop at arrival.

The heck is RTP?

**Comment by PGR-14** [comment]
> It does stop at arrival.
> 
> The heck is RTP?

Real-Time-Progression, sorry.

**Comment by esotericist** [comment]
> NVM it's 'cause of RTP, I tab out when auto driving, & RTP keeps going. Maybe we should make autodrive stop at arrival?

autodrive intentionally doesn't automatically park at the destination because of the likelihood that when it stops you might need to keep driving (either to select another destination or to deal with navigating potentially hazardous or hostile circumstances).

since you're _supposed_ to be at the controls and take over from that point.
