### ISSUE TITLE
I keep falling down ledges and geting buried by debris. On roads. Wilderness. Anywhere.

### ISSUE THREAD

**Issue by AncientAylamo** [CleverRaven/Cataclysm-DDA#77840]
### Describe the bug

Randomly in completely empty areas I will fall down invisible ledges etc.
Latest Experimental. Mods or configuration does not seem to matter.

### Attach save file

[No Hope for Convicts-trimmed.tar.gz](https://github.com/user-attachments/files/17747994/No.Hope.for.Convicts-trimmed.tar.gz)

### Steps to reproduce

Any character. The one in the screenshot was a "Play Now" random character. 

### Expected behavior

To walk down a road without this happening.

### Screenshots

![InvisoLedge](https://github.com/user-attachments/assets/7dc0130f-01e3-440f-a545-f562628f2592)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 1692e4a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Hope [no_hope],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

Happens at random. When walking or fast traveling.

**Comment by harakka** [comment]
Already resolved by #77805, update your game.
