### ISSUE TITLE
Mining using a pickaxe always causes an error

### ISSUE THREAD

**Issue by osuphobia** [CleverRaven/Cataclysm-DDA#77865]
### Describe the bug

After #76820 , mining using a pickaxe always causes the debugmsg to be poped up.
![20241115120106](https://github.com/user-attachments/assets/3c14a873-881b-4738-81d8-cdf8fea4ab34)

### Attach save file

[Matlacha-trimmed.tar.gz](https://github.com/user-attachments/files/17768735/Matlacha-trimmed.tar.gz)

### Steps to reproduce

Load the save, `a`ctivate the pickaxe to dig the wall, see debugmsg pops up.

### Expected behavior

First check if the tool uses charge?
```diff
--- a/src/activity_handlers.cpp
+++ b/src/activity_handlers.cpp
@@ -1870,7 +1870,7 @@ void activity_handlers::pickaxe_finish( player_activity *act, Character *you )
     here.destroy( pos, true );
     if( !act->targets.empty() ) {
         item &it = *act->targets.front();
-        if( it.is_null() || it.charges <= 0 ) {
+        if( it.is_null() || ( it.count_by_charges() && it.charges <= 0 ) ) {
             debugmsg( "pickaxe expired during mining" );
             return;
         }
```

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: 36d1e0c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by NetSysFire** [comment]
Confirmed, this reliably happens.
