### ISSUE TITLE
Nunez weirdo vehicle teleports in on dirt floor construction

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#77877]
### Describe the bug

During testing I constructed a dirt floor, and during the construction a weird looking vehicle containing the Nunez couple teleported in on top of a fence.
As far as I understand, this bug is, firstly, supposed to be fixed so they teleport to the Tacoma farm rather than to the PC's location. Secondly, the teleport is supposed to happen as a result of development at the Refugee Center and the Tacoma farm, but the PC hasn't been able to reach the Refugee Center yet (30 or so tiles of city to fight through). The save is old enough to have multiple Tacoma farms.

### Attach save file

[Hawaiian Ocean View-trimmed.tar.gz](https://github.com/user-attachments/files/17774066/Hawaiian.Ocean.View-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.
2. Walk up the ramp and out into the open area south of the house.
3. Construct dirt floor (I assume other things may well trigger it as well, but this is what I know does it).
4. See a "vehicle" suddenly appear.

### Expected behavior

The Nunez shouldn't move until the conditions are set up, and they should move to their intended destination.

### Screenshots

![Screenshot (640)](https://github.com/user-attachments/assets/b87e14c7-13bc-4b22-955d-ba62f57d0b77)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 0.G-13932-gdca38e584e-dirty [64-bit] "Dirty" due to it being the code for #77873, but it happened before the code was changed as well.
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I call the Nunez vehicle "weird" because it seems every surface of it is mis-oriented.

**Comment by Procyonae** [comment]
Oops that's on me #77664
I made changed the recurrance EoC to not be a recurrance EoC so everyone with existing saves has the placement EoC queued >_>
