### ISSUE TITLE
[0.H-RC] Cannot wash / clean a MOLLE medium rucksack

### ISSUE THREAD

**Issue by emomicrowave** [CleverRaven/Cataclysm-DDA#77889]
### Describe the bug

A zombie (marine zombie I think) had dropped a filthy **MOLLE medium rucksack**. Wearing it gives morale penalties from filthy gear. Activating a washboard does not give the option to clean the MOLLE even if you have soap/detergent and water nearby.

Whether the backpack is full or empty makes no difference. Whether there are pockets attached or not makes no difference. Whether you're wearing the backpack or not, makes no difference.

### Attach save file

[West Marion-trimmed.tar.gz](https://github.com/user-attachments/files/17779021/West.Marion-trimmed.tar.gz)

### Steps to reproduce

1. Load save
2. Observe that there is water in the toilet and soap / detergent nearby
3. (a)ctivate washboard -> get message "nothing to clean"

### Expected behavior

Either zombies shouldn't drop MOLLE backpacks, or you should be able to clean the backpack correctly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: a8ec133 [64-bit] **(0.H RC from a few days ago)**
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm]
]

**Comment by Karol1223** [comment]
Have you attempted this with a washing kit, or just a washboard?

**Comment by xcdxbaxa9** [comment]
Tested on https://github.com/CleverRaven/Cataclysm-DDA/commit/a8ec13390295a1b44490ea9701a2be425efe553c, washing does indeed work. Washing board doesn't. Not sure if it should.

**Comment by Karol1223** [comment]
I am assuming this has something to do with the soft/hard item distinction based on material. MOLLE medium rucksack has both nylon, which makes it soft, and plastic, which makes it hard (I think?) - it might be that the only possible cleaning tool that can handle this is one that can clean both soft and hard items at the same time?

I don't know if that's a regression, frankly. I never even attempt to use anything but the washing kit.

**Comment by emomicrowave** [comment]
Thank you both for checking. I didn't know that a washing kit existed as an item. Maybe the in-game message or the washboard description should somehow allude to the soft/hard item distinction?

**Comment by xcdxbaxa9** [comment]
Washing board looks like can wash only soft items https://github.com/CleverRaven/Cataclysm-DDA/blob/a66386858663064b8533b42492133e9b5a8dec55/data/json/items/tool/toiletries.json#L263 while washing kit can wash all items https://github.com/CleverRaven/Cataclysm-DDA/blob/a66386858663064b8533b42492133e9b5a8dec55/data/json/items/tool/toiletries.json#L279

**Comment by emomicrowave** [comment]
Just tried, a scrubbing brush works. Thank you both for the debugging! Maybe I am just dense, but I couldn't infer that the washboard wouldn't work on the rucksack from its description or from the "nothing to clean" message.

**Comment by harakka** [comment]
This is not a bug, it's just how the hard/soft cleaning distinction works. If something has hard parts, it can't be cleaned with tool for washing soft items. The whole distinction is pointless in practice since washing kit is trivial to craft, but that's how it works.
