### ISSUE TITLE
Military base warehouse batteries are all empty and also outdated.

### ISSUE THREAD

**Issue by Aimless-dude** [CleverRaven/Cataclysm-DDA#77896]
### Describe the bug

The military base warehouse (where you spawn in the 'overrun' start) has a large amount of standard military equipment. One of these things is a large number of non rechargable batteries, presumably for use with the large number of Flashlights, heavy flash lights, and electric lanterns stored right next to it.  However, not only are all these batteries empty, they also don't fit in flashlights anymore! Every battery currently spawned in the warehouse is a light battery, and currently flashlights take medium batteries 

### Attach save file

N/A Trivially reproducable

### Steps to reproduce

1) Make a new world
2) Pick the 'surrounded' start.
3) Look for the shelf where the dozens of spent batteries sit.

### Expected behavior

I would expect a military base to not stock completely useless spent batteries for their soldiers.

### Screenshots

![image](https://github.com/user-attachments/assets/e5ac5a79-0c35-47d6-b328-0ed8bcdf80ff)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: f665b59 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

The military base loot has oodles of issues, and this is only one of them. I assume part of the issue is that (allaegedly) the military base doesn't use any loot tables, but instead directly drops the loot when generated.

**Comment by ampersand55** [comment]
I believe this is an issue for many, if not most, of the spawned non-contained batteries. Similar issue with #77831.
