### ISSUE TITLE
Can't use remote robot controls on helicopter

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#77913]
### Describe the bug

You can't use remote robot controls on helicopter as you can't change Z-level. 

You get a "You can't climb here" message when trying to go up, and SEGFAULT when trying to go down.

### Attach save file

N/A

### Steps to reproduce

1. Start game as helicopter pilot
1. Spawn a Helicopter
2. Uninstall seat and install robot controls
3. Spawn remote vehicle controller and light battery, load controller, activate and take control of helicopter.
4. Press `>` and get "You can't climb here" message
5. Press `<` and get SEGFAULT crash.

### Expected behavior

I expected it to work.

Not that remote controlling an actual helicopter would be realistic, but this would open up possibilities to create aerial drones and UAVs.

![image](https://github.com/user-attachments/assets/38a3b58e-1d3a-4ae8-90d6-2d4c9a9674bf)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.7515 (1607)
- Game Version: 0f2c155 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by kevingranade** [comment]
Invalid expected result.

**Comment by Night-Pryanik** [comment]
Still, if it's possible to install a robot controls into a helicopter and get a SEGFAULT when trying to make it descent, we should do something about it. Crash should be fixed in any case.
