### ISSUE TITLE
[Magiclysm] Druid's spell Sacrificial Regrowth not working as intended due to missing IGNORE_WALLS flag.

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#77957]
### Describe the bug

Since it does not ignore walls, it never works as intended, as it can not hit the tree terrain and thus does not transform the tile. It works fine to turn dead grass into grass, but this is kind of useless.
I know it is an old spell, and nobody uses it so it never get reported to be updated to the more recent changes and missing a lot of potential transformations. There is also the renew forest spell, which kinda does the same thing. For a rudimentary fix, a simple IGNORE_WALLS flag should do, I think. But the spell's effect codes still needs to be updated.

### Attach save file

N/A

### Steps to reproduce

1. Give and edit a character with Sacrificial Regrowth spell.
2. Change some terrain using Map Editor to find the relevant tree, in this case, t_tree_dead, t_tree_deadpine, t_tree_hickory_dead, t_tree_willow_harvested, t_tree_very_dead ( these are all the currently tree that is in the code, quite outdated, I think)
3. Cast Spell. Spell doesn't target the tree, as shown by the targeting cursor.

### Expected behavior

The spell is a simple revival spell for dead plants. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: cdda-experimental-2024-11-03-2221 6b98896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Standing-Storm** [comment]
> I know it is an old spell, and nobody uses it so it never get reported to be updated to the more recent changes and missing a lot of potential transformations.

What sort of transformations is it missing specifically? I added `t_tree_very_dead` a while ago, but I'm not sure what else is out there

**Comment by tranhuulong** [comment]
> > I know it is an old spell, and nobody uses it so it never get reported to be updated to the more recent changes and missing a lot of potential transformations.
> 
> What sort of transformations is it missing specifically? I added `t_tree_very_dead` a while ago, but I'm not sure what else is out there

Now that you said it, I might have overthink it. I just though about how many new trees there is and there maybe more dead tree variant that I do not know about. There is also the t_tree_willow_harvested that was included in the code. That mean there is also other tree such as almond, walnut... that have the harvested state. But that will need to be reviewed, since it make no sense that you can just use the spell to instantly renew the tree to harvest again ( unless I am mistaken on how the spell work).
