### ISSUE TITLE
[Experimental] advanced inventory menu UI issue

### ISSUE THREAD

**Issue by frostedclaws** [CleverRaven/Cataclysm-DDA#77967]
### Describe the bug

When dropping an item via the advanced inventory menu, it asks which direction you want to drop the item in.  It gives the menu listed in the picture and the orientation doesn't match the cardinal directions.  The item goes to the written texts location instead of the numbers location. the two don't match up with each other so you have to guess where your item will go.

i thought i may just rename them but its also tied to the code going to different spots than the number direction.

### Attach save file

n/a

### Steps to reproduce

open advanced inventory manager
make left pane viewing all items
make right pane viewing inventory
select an item from the right pane - personal inventory and pull up the drop item location menu
move it to a spot.

### Expected behavior

I expect that the numbers match the cardinal directions on a compass.  Being named 
(1 north west) (2 north) (3 north east)

(7 south west) (8 south) (9 south east)

### Screenshots

![image](https://github.com/user-attachments/assets/3dab54b2-08a0-4c66-848a-5dc143a2cd98)

### Versions and configuration

windows 10

**Comment by db48x** [comment]
Wow, that’s actually pretty hilarious.

**Comment by db48x** [comment]
some improvements:
![Screenshot from 2024-11-19 00-18-21](https://github.com/user-attachments/assets/3db9dc58-8090-40bb-ace8-3c96f2d791c2)


![Screenshot from 2024-11-19 00-15-46](https://github.com/user-attachments/assets/ae699399-9d77-4e9c-9a67-c7b930030b3e)

**Comment by frostedclaws** [comment]
awesome thanks for fixing it =]

**Comment by db48x** [comment]
You’re welcome :)
