### ISSUE TITLE
Removal of npctalk_var_ prefix results in multiple broken EoCs and variables

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#77980]
### Describe the bug

Tried updating to the latest version and got a message that I was loading Sky Island for the first time. I've been playing this Sky Island save for months, so that's obviously not true. Checking into it further, it looks like a problem with variable names that still have the npctalk_var_ prefix when the game is no longer checking that. 

### Attach save file

[Skyland - Copy (2)-trimmed.tar.gz](https://github.com/user-attachments/files/17808479/Skyland.-.Copy.2.-trimmed.tar.gz)

### Steps to reproduce

1) Load game on the latest version of the game (post #77515 )
2) Just before finishing, you'll get a popup saying that you're running an old version of Sky Island and need to update, presumably because npctalk_var_versionupdate is set to 1 but it's now looking for just versionupdate to be set to 1.
3) Go through the prompts. Pick anything.
4) You spawn in an advanced bunker, indicating that this is not a new game. 
5) Go underground and go west. See a rock wall where the existing room was destroyed by the upgrade EoC mapgen.
6) Go north. See the same thing.

The only reason I didn't suddenly spawn into solid rock is that my appliances prevented some of the mapgen from running.

### Expected behavior

Variables are automatically migrated to the new format on load. 

### Versions and configuration

Version save was taken from: 

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: cdda-experimental-2024-11-15-0512 0f2c155 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Sky Island [skyisland],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Railroads [railroads],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Bombastic Perks [bombastic_perks]
]

It does require Arcana, but I included the var_output files below for easy comparison. Scroll down to the bottom to see the variables Sky Island re-wrote.

### Additional context

I don't specifically know that #77515 is the reason, but I did notice when I checked the var_output files that it was full of npctalk_var_[WHATEVER] before and when I updated, the new version had a few [WHATEVER] mixed into the old npctalk_var_[WHATEVER].

[var_list_pre_output.txt](https://github.com/user-attachments/files/17808254/var_list_pre_output.txt)

[var_list_post_output.txt](https://github.com/user-attachments/files/17808503/var_list_post_output.txt)

**Comment by GuardianDll** [comment]
You can see from the PR that i migrated all possible vars. I forgot to include a screenshot of actually migrated global vars, but they should make a copy of variable, so it is intended you have npctalk_var_X and X mixed

The only possible explanation in my eyes is that for some reason variables are read before they are migrated, which is simply impossible for it would mean they are read before they are loaded
