### ISSUE TITLE
NPC become hostile when zombies break their building

### ISSUE THREAD

**Issue by ShuCuoMao** [CleverRaven/Cataclysm-DDA#77982]
### Describe the bug

zonbies break their fences,and when I go their home they become hostile

### Attach save file

(https://github.com/user-attachments/files/17810071/default.zip)

### Steps to reproduce

just go south to smith's home and she becomes hostile

### Expected behavior

smith becomes hostile

### Versions and configuration

windows 11 experience-11090812

**Comment by RenechCDDA** [comment]
They appear to be already hostile in the provided save.

![image](https://github.com/user-attachments/assets/18f81625-8b96-4e29-8f3d-79f7f78b88e1)

The faction starts with 10 `likes_u` (https://github.com/CleverRaven/Cataclysm-DDA/blob/909383b710625ac8c9578ae123f1603db2c1b7cd/data/json/npcs/factions.json#L458), 0 respects_u, and 0 trust.

Given the values I see in your save (-14/-24/-24), it appears you slept at their base 5 times, ignoring the warning each time. 

The message log provided in your save has at least 3 recorded messages of your character going to sleep immediately after speaking with Jay, with no indication that you left the area. 

Sleeping at most factions' territory is not permitted. The game gives you a popup query about this. Choosing to proceed will cause them to lose relation with you. Doing it repeatedly, as you appear to have done, will eventually result in them turning hostile.
