### ISSUE TITLE
Safe mode doesn't warn me

### ISSUE THREAD

**Issue by ShuCuoMao** [CleverRaven/Cataclysm-DDA#77991]
### Describe the bug

After I put wasp in blacklist,safety mode stops warning me any monster

### Attach save file
[safemode.json](https://github.com/user-attachments/files/17813071/safemode.json)

### Steps to reproduce

push ~ open white/blacklist,add *wasp to blacklist,T test oversized wasp is included and then opening safe mode becomes useless.After i delect all the settings it is still not work.

### Expected behavior

safe mode don't warn you if you see monsters

**Comment by IdleSol** [comment]
Attach file: config/safemode.json

**Comment by ShuCuoMao** [comment]
done

**Comment by ShuCuoMao** [comment]
> Attach file: config/safemode.json

done

**Comment by IdleSol** [comment]
Notice you have the rule set for hostile wasps. Change it to any

**Comment by ShuCuoMao** [comment]
> Notice you have the rule set for hostile wasps. Change it to any

I tried,the file is just a test,It's really easy to reproduce in I could say any version since I've been seeing this from 0.g.And back to your saying either way is not working, zombies is even not warned after my setting.

**Comment by IdleSol** [comment]
![1](https://github.com/user-attachments/assets/659e41d8-dd14-492e-9755-d6eb4f2c760a)

**Comment by ShuCuoMao** [comment]
well I see...I think It's the discription of distance that mislead me.It says 0 distance is max dist
![image](https://github.com/user-attachments/assets/2edb29c8-4e9a-4f56-b5a5-2396a5d6fe9c)

**Comment by ShuCuoMao** [comment]
I think it's a text mistake rather a coding one

**Comment by ShuCuoMao** [comment]
Wait,there's still one bug.Add *wasp to blacklist will prevent warning you normal zombies.
