### ISSUE TITLE
Merc coat goes to outer when MOLLE is attached.

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#78031]
### Describe the bug

Was runnin' 'round, grabbing stuff, when I realized I could put MOLLE stuff on my merc coat. But then, my encumbrance went from pink to red, & it was now conflicting w/ my wool cloak, was resolved when I took the MOLLE stuff off.

### Attach save file

N/A

### Steps to reproduce

Grab merc coat & outer clothing, put a MOLLE item on the coat, & look upon ye encumbrance & dispair.

### Expected behavior

To keep it's layer

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: cdda-experimental-2024-11-12-1726 b8a6d08 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    Mythical Martial Arts [MMA],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by DukePaulAtreid3s** [comment]
whenever MOLLE is added to something it automatically becomes part of the strapped layer, in addition to any others. So this is intended so far as this is a limitation of our clothing system.

**Comment by oosyrag** [comment]
Well no, since it was intended to do so it's not a bug. Molle attachments add their layer/encumbrance to whatever they are being attached to, they don't get overwritten/absorbed into it.
