### ISSUE TITLE
[Xedra Evolved] Stealing ruach from Dinos/Megafauna causes the game to crash.

### ISSUE THREAD

**Issue by Cddasurvivor** [CleverRaven/Cataclysm-DDA#78069]
### Describe the bug

If you attempt to steal ruach from a dino it causes a stacktrace crash saying bad function call.

![test _2024-11-21T20-52-27](https://github.com/user-attachments/assets/10026309-cd2c-4b46-893e-95553657a238)

### Attach save file

[Boogeraids-trimmed.tar.gz](https://github.com/user-attachments/files/17856186/Boogeraids-trimmed.tar.gz)

### Steps to reproduce

1)Make a Lilit character.
2)Cast Enervating Touch on a dinosaur.
3)Stack Trace Error.

### Expected behavior

The game shouldn't crash and you gain ruach.

### Screenshots

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: f0d2f50 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved],
    DinoMod [DinoMod]
]

### Additional context

Apparently dinosaurs have no soul.

**Comment by Cddasurvivor** [comment]
Noticed it crashes to when I try to steal ruach from anything using megafauna mod as well

**Comment by Standing-Storm** [comment]
/confirmed 

That's definitely odd.  The only failstate it should have is to do nothing.

**Comment by Standing-Storm** [comment]
Further testing--it happens on a normal animal as well, not just a dinosaur. Dinomod is not necessary to cause the crash.

Relevant part of the EoC is here: https://github.com/CleverRaven/Cataclysm-DDA/blob/d42cfd9adae589f98d6a4041b038f1caa62f94b4/data/mods/Xedra_Evolved/spells/lilin_spell_eocs.json#L108

**Comment by Standing-Storm** [comment]
Okay, went through each stage of the EoC

NPCs: works
Ferals/renfields/humans/changelings: works
Migo/triffids: crashes
Nether: crashes
Arvore/Ierde/etc/Vampire: crashes
Animal: Crashes
Insect/Spider: Crashes
Fallback at the end for anything else: crashes. Which is pretty odd because you can see I checked it three days ago and it worked then.

**Comment by Standing-Storm** [comment]
Further testing--if I delete everything in the EoC except the plant/migo condition and try to drain a plant, it works, so it's something about the way the if conditions are being handled.

**Comment by SariusSkelrets** [comment]
I tested and both test EOCs will cause a crash if the related mod isn't loaded.

With only XE, everything below humanlikes caused a crash.

With XE and magiclysm, only insects and below caused a crash.

With XE, magiclysm and dinomod, nothing caused a crash.

There's something not working with the test EOCs.
