### ISSUE TITLE
Game stops responding to numpad keys

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#78075]
### Describe the bug

In November, I started to notice that sometimes the game stops responding to pressing keys on the keyboard numpad. (2 or 3 times).

Today I walked away from the game for about 9 minutes. When I came back, the character was not responding to the numpad keys in any way.

I didn't quit the game or minimize the window. Presumably, the reason is a long idle time of the game (~10 minutes).

Exiting to the main menu and re-entering did not fix the problem.
Exiting the game (close the client) and re-entering fixed the problem.

While writing the report, the game was minimized. But the problem did not appear. I will try a longer delay on a new start.

### Attach save file

n/a

### Steps to reproduce

No idea

### Expected behavior

n/a

### Versions and configuration

- OS: <s>Windows</s> arch + portproton
    - OS Version: 10.0.19043 (21H1)
- Game Version: d42cfd9 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92,0%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

### Additional context

Maybe the problem is in the emulator.

**Comment by harakka** [comment]
> Maybe the problem is in the emulator.

What emulator?

**Comment by IdleSol** [comment]
PortProton-1.7.1

**Comment by Little-119** [comment]
Does the native Linux version not work on Arch?

**Comment by IdleSol** [comment]
In the repository: version 0.G.
AUR: cdda.experimental.2024.08.29

I don't know how to install directly. And it's easier to download for windows and run it in a couple of clicks.

**Comment by zakhad** [comment]
I've had this issue but i can't tell what is causing it but im on windows, not linux.  But mine happens after being alt tabbed or so i'm suspecting, i've only noticed this happen since having the new GUI on experimental last few weeks or month and a bit which further distances my case from his if he's using stable.

**Comment by Aimless-dude** [comment]
This also happens to me, alt tabbing, clicking off and on the tab, turning num lock on and off, none of it seems to work.

**Comment by IdleSol** [comment]
In my case, alt-tab doesn't cause the error. Everything works.

**Comment by NetSysFire** [comment]
Use the Linux version. I am using the arch version, it works flawlessly. Might be a wine bug, which you want to report upstream.

**Comment by dbedrenko** [comment]
I can reliably reproduce this.

OS: Arch Linux (X.org)
Release version: 0.H
Playing with Tiles

I run the game in borderless window.

Alt-tabbing away from the game then back into the game causes the bug. Clicking to another window and then back to the game doesn't cause the bug: it needs to be Alt-Tab.

Effects in the bugged state:

1. The number keys above the letters, as well as the numpad number keys do nothing in the game. Not even as text input in something like the keybinds menu that allows you to search keybinds by name. The game doesn't register these keys at all. 
2. In this state all other keys seem to work well, including punctuation keys, as well as `/` and `*` on the numpad.
3. Interestingly, holding shift and pressing the number row will enter `!`, `@`, `#`, etc.

The workaround is to press Alt once, and then the game becomes unbugged.
This bug doesn't occur if the "Use key code input mode" is set to "Key code", but this is a WIP option and it causes other problems, e.g. not being able to press a number on the inventory, get or drop screens to select the number of items to drop.

Can this be reopened please? I'm ready and willing to do any sort of debugging you want from me :)

**Comment by harakka** [comment]
Nothing is going to be done about this for 0.H any more at this point, if you can reproduce it for [0.I release candidates](https://github.com/CleverRaven/Cataclysm-DDA/releases?q=release+candidate&expanded=true) or experimental, please open a new issue about it.
