### ISSUE TITLE
Danger marker on overmap only works in the chunk where it's present

### ISSUE THREAD

**Issue by AideeAmei** [CleverRaven/Cataclysm-DDA#78078]
### Describe the bug

Using "Mark danger" action on the map allows the player to create a marker with rectangular area around it (dunno if this is changed when rectangular distances = false) and the player is prompted for the size of the area (diameter value).
This is all fine, but when you create a danger marker large enough, you start to see the circle is not so round.
It is caused by the marker only being respected by the chunk where it is present.

Someone tell the ants they shouldn't follow me to the neighboring chunk!

### Attach save file

N/A

### Steps to reproduce

1. Go to map
2. Mark danger
3. Enter diameter 20 near chunk edge

### Expected behavior

I expect the danger to stretch to other chunks. If there's something I don't know about chunks that would contradict this idea, I will welcome that information with an open heart.

### Versions and configuration

OS: Windows 10 Pro 64-bit 22H2 19045.5131
Game Version: b1266d1 (tiles)
build 2024-11-22-1510
Ingame Language: das Englisch

**Comment by inogenous** [comment]
Example screenshot:
![snapshot1](https://github.com/user-attachments/assets/c4355631-077f-492e-a2cb-748af13156d4)
![snapshot2](https://github.com/user-attachments/assets/cd81a94d-e324-4510-a89a-96dda46c97ba)

**Comment by AideeAmei** [comment]
@inogenous 

Thanks, I'm not great with screenshots. 😆

**Comment by AideeAmei** [comment]
Then this is a duplicate.
