### ISSUE TITLE
Crashing when trying to move

### ISSUE THREAD

**Issue by Rjtheperson** [CleverRaven/Cataclysm-DDA#78120]
### Describe the bug

After I load the game and try to move the game crashes.

### Attach save file

[Canyon Lake-trimmed.tar.gz](https://github.com/user-attachments/files/17894558/Canyon.Lake-trimmed.tar.gz)

### Steps to reproduce

1. Load Save
2. Try to move anywhere
3. Crash

### Expected behavior

I expect not to crash when trying to move. 

### Screenshots

https://github.com/user-attachments/assets/9972862c-38d3-4c0a-9ed1-43a835663c4e

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 14f7f1d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore N

PCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    Martial Mastery [perk_melee_system],
    Bombastic Perks [bombastic_perks],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills]
]

### Additional context
I can load the game, look at a bunch of menus and even debug teleport with no issues but if I take one step it just crashes.
[crash.log](https://github.com/user-attachments/files/17894563/crash.log)

**Comment by Standing-Storm** [comment]
/confirmed

Same as above--loaded game, tried waiting, immediate crash
