### ISSUE TITLE
Crash when npc's gun has a breakdown

### ISSUE THREAD

**Issue by ShuCuoMao** [CleverRaven/Cataclysm-DDA#78162]
### Describe the bug

When npc shoots zombies,after some shots the game crashes.I guess it's because the gun has breakdown according to information .

### Attach save file

[mor-trimmed.tar.gz](https://github.com/user-attachments/files/17913947/mor-trimmed.tar.gz)

### Steps to reproduce

Let npc shoot some zombies and soon it will crash.

### Expected behavior

The game crashes.Lower right shows their gun is lagged.

### Versions and configuration

-OS windows11
-game version 09f30df
-mod loaded:
  ["dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "Cata++",
  "ProjectKawaii",
  "MST_Extra",
  "Medieval_Mod_Reborn",
  "perk_melee_system",
  "Mining_Mod",
  "Nonperishable_Overhaul",
  "stats_through_kills",
  "Tamable_Wildlife",
  "cbm_slots",
  "speedydex",
  "VOICEROID_mod",
  "NPC_kiritan",
  "culinary_days_ahead"
-language:chinese(simplified)

### Additional context

[crash.log](https://github.com/user-attachments/files/17913910/crash.log)
[debug.log](https://github.com/user-attachments/files/17913911/debug.log)

**Comment by RenechCDDA** [comment]
Resolved with #77887

Please comment if you're still experiencing this issue on a version newer than that PR.
