### ISSUE TITLE
Appliance use menu is cut off with scroll bars, last menu item only half visible when scrolling down.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#78177]
### Describe the bug

Title.

### Attach save file

N/A

### Steps to reproduce

Place a solar panel or freezer in the construction menu `[*]` and examine it.

### Expected behavior

I expect all options to be legible. 

I would prefer if there weren't any scroll bars and the window resized to display all values.

### Screenshots

![image](https://github.com/user-attachments/assets/246b0025-1a00-4444-80e7-9a90cee226bd)

(this looks like I've made an error in cutting and pasting, but the menus looks like this in game)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.7515 (1607)
- Game Version: 4589bf8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by ZhilkinSerg** [comment]
```PATCH
diff --git a/src/veh_appliance.cpp b/src/veh_appliance.cpp
index 52a5daac78..bfde1af493 100644
--- a/src/veh_appliance.cpp
+++ b/src/veh_appliance.cpp
@@ -198,10 +198,11 @@ void veh_app_interact::init_ui_windows()
     ImVec2 text_metrics = { ImGui::CalcTextSize( "X" ).x, ImGui::GetTextLineHeight() };
     ImVec2 origin = text_metrics * ImVec2{ static_cast<float>( topleft.x ), static_cast<float>( topleft.y + win_height ) };
     ImVec2 size = text_metrics * ImVec2{ static_cast<float>( win_width ), static_cast<float>( height_input ) };
+    imenu.title = _( "Vehicle interaction menu" );
     imenu.desired_bounds = { origin.x,
                              origin.y,
-                             size.x,
-                             size.y + 4.0f * ( ImGui::GetStyle().FramePadding.y + ImGui::GetStyle().WindowBorderSize )
+                             -1.0,
+                             std::min<int>( static_cast<int>( imenu.entries.size() ) + 2, TERMY - 1 ) *ImGui::GetTextLineHeightWithSpacing()
                            };

     imenu.allow_cancel = true;

```

![image](https://github.com/user-attachments/assets/af594651-2d76-4aa9-8e6a-7b8acdb5b597)
