### ISSUE TITLE
Change large dry bag recipe from wanting 200 + 400 duct tape to 600

### ISSUE THREAD

**Issue by Icantthinkofanameforthis** [CleverRaven/Cataclysm-DDA#78188]
### Is your feature request related to a problem? Please describe.

was looking through recipes and noticed the large dry bag asking for the duct tape in 2 different amounts without an OR item along with them so figure possible alternatives may have been removed for one of them and the recipe left as is

### Solution you would like.

combine the 200 duct tape and 400 duct tape into 600 duct tape

### Describe alternatives you have considered.

have one of them offer the OR alternative like say super glue, bone glue or medical tape so like with with that example

> 200 duct tape OR 8 bone glue OR 80 superglue OR 400 medical tape
> 400 duct tape

### Additional context

![image](https://github.com/user-attachments/assets/ab3d6475-15a7-4e98-89e4-a2b8db6d8750)

edit - adding version stuff to show its a pretty recent one with no mods making it weird

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: ad13310 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
That's impossible, because it's not just "200 duct tape and 400 duct tape", but "200 duct tape as part of waterproofing_plastic_sheets, and 400 duct tape". It is generally desired to have better algorithm that would sum up such requirements, but it's a different suggestion altogether

**Comment by Icantthinkofanameforthis** [comment]
> because it's not just "200 duct tape and 400 duct tape"

![image](https://github.com/user-attachments/assets/df1d0cb7-7b10-4930-b944-6b2f12de9f25)
just to be clear how arnt these a total of 600 duct tape?

**Comment by GuardianDll** [comment]
![image](https://github.com/user-attachments/assets/ecb4824a-675c-442a-8f40-48106dfe5a98)
![image](https://github.com/user-attachments/assets/0e21b648-3304-483e-9029-c515029a7d4c)

400 + [5 * 40]
