### ISSUE TITLE
"Infected with the vampire disease" conflicts and doesn't conflict with becoming Dreamer/Eater of Dreams/Dreamsmith/Mad Genius?

### ISSUE THREAD

**Issue by Battlegear1734** [CleverRaven/Cataclysm-DDA#78181]
### Describe the bug

When obtaining the "Infected with the vampire disease" mutation before learning a Dreamer/Eater of Dreams/Dreamsmith/Mad Genius spell, the player can no longer obtain the class.

However, suppose the player learns a respective class's spell, such as the dreamer's "Stalker's Oculars" spell via Presence artifact, before obtaining the "Infected with the vampire disease" mutation. In that case, they can still learn all the spells and obtain all the benefits of the class.

### Attach save file

N/A

### Steps to reproduce

1. Create two identical save files with the same world mods (For clarity purposes, I will separate them as Save 1 & Save 2)
2. For Save 1, **LEARN ANY** dreamer/eater of dream/dreamsmith/mad genius spell, then get bitten by a vampire and wait until you obtain the "Infected with the vampire disease" mutation
3. Attempt to learn another dreamer/eater of dream/dreamsmith/mad genius spell for the class you chose that is unlearned
4. For Save 2, **DO NOT LEARN ANY** dreamer/eater of dream/dreamsmith/mad genius spell, get bitten by a vampire, and wait until you obtain the "Infected with the vampire disease" mutation
5. Attempt to learn another dreamer/eater of dream/dreamsmith/mad genius spell for the class you chose that is unlearned

### Expected behavior

According to the debug menu, the mutation "Infected with the vampire disease" should cancel the Dreamer/Eater of Dreams/Dreamsmith/Mad Genius class and most likely remove/disable all associated spells.

Ideally, either becoming a vampire and obtaining "Infected with the vampire disease" shouldn't conflict with the classes, or obtaining the dreamer/eater of dream/dreamsmith/mad genius class should make the player immune to "Infected with the vampire disease".

### Screenshots

<img width="794" alt="CDDA Dreamer_Debug_Info" src="https://github.com/user-attachments/assets/58e74dfa-80d4-4613-abf9-7ee58e63ffb6">
<img width="750" alt="CDDA IWTVD_Debug_Info" src="https://github.com/user-attachments/assets/0c9c7e4b-6319-4738-9e0c-03cb72f4bb22">

### Versions and configuration

OS: MacOS 14.6.1
Game Version: Experimental/Unsure (Maybe Fixed Already)
Game Language: English
Mods Loaded: Dark Days Ahead [dda], Xedra Evolved [xedra_evolved]

**Comment by Standing-Storm** [comment]
This is intended: #77685

...mostly. The problem is that if you have the trait for the class already, nothing can stop you from finding items in the world and learning new spells from those items, so it's only EoC-based spell learning that I was able to prevent. 

Vampire gets special treatment because it's acquired during the game (not just in character creation) and it's progressive and curable, so it's up to the player when they get infected whether they think their vampire powers are worth giving up dream magick. If not, they can take the cure. But not being able to freely mix and match them is intended.
