### ISSUE TITLE
ATM cash deposit to ecash does not change account balance but still removes money from inventory

### ISSUE THREAD

**Issue by kuutekitty** [CleverRaven/Cataclysm-DDA#78235]
### Describe the bug

The ATM cash deposit option does not work. After trying multiple times with different randomly picked up wallets, the money and coins were removed from the wallets (I've also tried single notes) but the actual cash does not change in my in game account.

### Attach save file

https://www.dropbox.com/scl/fi/psm4hj1un32vsbjbxwn8u/Nicholls-trimmed.tar.gz?rlkey=h5qtshsd0dlgh6v1wrzdh6obw&st=s3qoko3y&dl=0

### Steps to reproduce

(after loading the save file)
1.interact with the ATM terminal to try to deposit cash and turn it into eCash
2.The cash gets deposited, value of money in the account is completely unnefected

### Expected behavior

I expect that some amount of the cash that I deposited would be turned into eCash as that is what the menu says should happen

### Screenshots

![inventory](https://github.com/user-attachments/assets/34f63696-7ca1-4a16-b842-2f8728e540bd)
![ATM menu](https://github.com/user-attachments/assets/c3f8cb0c-f9de-4816-9e91-7824e15b90a8)
![Screenshot_1](https://github.com/user-attachments/assets/50e44c49-4fdb-424c-82a6-f73c60e2a39c)
![after depositing](https://github.com/user-attachments/assets/e3520ba0-c722-4477-9c9c-bce09b9eebb2)
![invetory after depositing](https://github.com/user-attachments/assets/df4ae50c-4287-45c7-8da6-9bbd703546ab)

### Versions and configuration

Os-Windows 10
Game version: build number: 2024-11-23-1857 commit sha: 78fd6e3af9fd75b2e6f0b1c603ce34c7ab222610
Graphics version:Tiles
In game language: English
Mods loaded: (in order) dda, no_npc_food, personal_portal_storms, no_fungal_growth, bombastic_perks, my_sweet_cataclysm, sees_player_retro, speedydex

### Additional context

The problem does cause a crash or appear in the message log in any way.

**Comment by Little-119** [comment]
Functional ATMs are getting removed anyway, aren't they?
Unless the bug is relevant to Aftershock

**Comment by kuutekitty** [comment]
seeing as they added a new feature, they didn't intend to remove ATMs yet, so it would be best for the game if the feature actually worked (no animosity for the people developing the game, I love it, that's why I reported a concrete repeatable bug I found)

**Comment by PatrikLundell** [comment]
If you look at the inventory screen shots you'll find that the amount on the first card has increased, which is what I would expect from the exchange option (the corresponding real world cash deposits deposit into accounts, but we also don't have cash cards to any extent). Thus I suspect this works as expected, but haven't tested it in the game.

It can also be mentioned that there's a game option to create a compressed save that can just be dragged and dropped into the corresponding section of the bug report form, so no external storage locations are needed. Can be worth keeping in mind for future reports.
