### ISSUE TITLE
Atomic Cell Phone can not read books [aftershock]

### ISSUE THREAD

**Issue by TheRagingAnimist** [CleverRaven/Cataclysm-DDA#78245]
### Describe the bug

You can not read books stored in atomic cell phone in recent experimentals. You can store them (and once stored, can't store them again, so it's clearly remembering what it has somewhere)

When you choose 'read stored books' you get the message 'you have nothing to read'

This may be related to this PR that was merged yesterday

https://github.com/CleverRaven/Cataclysm-DDA/pull/78184

In this PR, cell phones were 'nerfed' so that you could not read books if they had no charge. I am guessing the atomic smartphone has no charges and it's functions are set to just work and not require power, and that this change has unintentionally broken them

It could be a separate issue still, but I upgraded my experimentals yesterday after it was merged and ended up restarting cause I lost access to my books which I didn't keep physical copies of. I found out after that regular cell phones still work fine, so it's highly likely this linked PR causing the problem.

### Attach save file

N/A can be quickly reproduced with debug with aftershock enabled.

### Steps to reproduce

Get any book/manual

store in atomic smartphone(from aftershock)
store in regular smartphone that has power

attempt to read from both devices. the atomic device will fail.

### Expected behavior

the atomic smartphone should work and not require power.

### Versions and configuration

Win 10
Experimental 2025-11-29-0509

**Comment by Arcania88** [comment]
I am having exactly the same issue with the integrated AR system CBM

**Comment by SomeName42** [comment]
Thank you for commenting I'll try to fix it
