### ISSUE TITLE
.H stable map ui bug

### ISSUE THREAD

**Issue by mufasas111** [CleverRaven/Cataclysm-DDA#78259]
### Describe the bug

after opening the map, the messages line at the bottom right remains with the map ui/ art

### Attach save file

n/a

### Steps to reproduce

open map
closse map

### Expected behavior

all the ui/art of the map should be closed 

### Screenshots

![Screenshot_20241130-130617](https://github.com/user-attachments/assets/7d88141d-f044-4f3a-aec1-5956f2174b59)

### Versions and configuration

android
.H stable

**Comment by NetSysFire** [comment]
Looks to be a duplicate of #77325.
