### ISSUE TITLE
Access NPC inventory through Advanced Inventory Manager

### ISSUE THREAD

**Issue by svakob** [CleverRaven/Cataclysm-DDA#78308]
### Is your feature request related to a problem? Please describe.

Accessing the inventory requires a lot of clicking. It takes a lot of time.

### Solution you would like.

Add ability to access NPC inventory via Advanced Inventory Manager. Namely, equipped items and inventory.

**Comment by Brambor** [comment]
- Duplicate of #68034.
 - Note: Closed doesn't mean we don't want it!
