### ISSUE TITLE
Pits appears after smashing fences

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#78309]
### Describe the bug

If you smash chain linked fences or locked wire gate - the empty space pit is appear

### Attach save file

[1-trimmed.tar.gz](https://github.com/user-attachments/files/17983192/1-trimmed.tar.gz)

### Steps to reproduce

Smash chain linked fence or wire gate - see the pit appear

### Expected behavior

Dont have pits appears after smashing chain linked fences

### Screenshots

![image](https://github.com/user-attachments/assets/33e80418-2ea0-4434-9fa1-7eb8885d0967)
![image](https://github.com/user-attachments/assets/471d1cf3-bf2f-4225-9460-6f31b72eec6a)
![image](https://github.com/user-attachments/assets/8eaa734a-8178-45f9-82c6-494d1f97e06d)
![image](https://github.com/user-attachments/assets/470565c8-5a0e-4f2d-96d1-bd6cded9d952)
![image](https://github.com/user-attachments/assets/7b7b8d10-3866-4644-82d7-29d3a02ffb76)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 3173580 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92,2%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RedMisao** [comment]
Related to/duplicate of #76376 ?

**Comment by KHeket** [comment]
> Related to/duplicate of #76376 ?

Yeah, you are right. Thx
