### ISSUE TITLE
Mutant friendly skates

### ISSUE THREAD

**Issue by Alithsko** [CleverRaven/Cataclysm-DDA#78312]
### Is your feature request related to a problem? Please describe.

Being able to use the skater trait while having non-human feet using some tailoring will prevent mutants risking completely locking out of one of their core character features taken during game start

### Solution you would like.

On the lower end we have XL and XS skates, being a simple resize, and on the higher end with some fabrication and tailoring you might make a pair of survivor rollerskates, or perhaps survivor rollersandals if you want to attempt talon kicks with skates, if you happen to have very high dodge levels

### Describe alternatives you have considered.

A skater CBM might be considered

**Comment by Swootch** [comment]
Doesn't the skater trait already give bonuses to mutants who walk on 4 legs? You're not "completely" locking out, just need to know which mutation works with it.

**Comment by kevingranade** [comment]
We don't do silly things to make all character choices functional. If you mutate away from being able to use something your character originally focused on, just focus on something else.
