### ISSUE TITLE
"unable to generate valid starting location hospital/mall/cathedral" (several atempts)

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#78315]
### Describe the bug

trying to start in "large building" hospital/mall/cathedral all  results in error. I have tried resetting the world and trying again (for hospital) but it makes no difference. In case it is relevant city spacing is 6 and city size 3.

More andecoaly these buildings seem to have a very low chance of spawning in general, i can't remember seeing any of them in my last several runs?

### Attach save file

N/A issue is at game start.

### Steps to reproduce

Try to start the game in a hospital. specifically large building scenario hospital location in my case.

### Expected behavior

Game starting without an error.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4541 (23H2)
- Game Version: 723edad [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Bombastic Perks [bombastic_perks],
    Bionic Professions [package_bionic_professions]
]

**Comment by Procyonae** [comment]
Both hospitals, the cathedral and mall have a minimum city size, changing the world setting city size to 3 will prevent several buildings including these to spawn with any frequency, this is not a bug.
