### ISSUE TITLE
Bill is unrealistically cheap

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#78320]
### Describe the bug

It's $2.50, a machete on a stick should be worth more than that.

### Attach save file

N/A

### Steps to reproduce

Spawn a bill, & despair

### Expected behavior

A bit more, maybe 'round the price of a glaive?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: 3173580 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by kevingranade** [comment]
PR if you want to fix it.
