### ISSUE TITLE
Summoning weapons spawns them dropped

### ISSUE THREAD

**Issue by MorphingE** [CleverRaven/Cataclysm-DDA#78327]
### Describe the bug

When I summon a weapon via Xedra or Magiclysm, it is summoned on the ground by default. Should be summoned in hand.

### Attach save file

Attached the save files and my personal tweaks folder in case it is part of the problem.

[Kelly Lake.zip](https://github.com/user-attachments/files/18001430/Kelly.Lake.zip)
[PersonalTweaks.zip](https://github.com/user-attachments/files/18001432/PersonalTweaks.zip)

### Steps to reproduce

1. Log in
2. Cast Summon Dagger, Nature bow, w/e
3. Watch it summon onto the ground

### Expected behavior

Expected behavior is to summon into my hand

### Versions and configuration

Windows 10
CDDA Experimental Build: 2024-12-03-0845
![Screenshot 2024-12-03 181457](https://github.com/user-attachments/assets/69ff0e70-f0e4-4306-bd40-d9daee4e3175)

**Comment by RedMisao** [comment]
I cannot replicate this, either from the save (image), or by creating a fresh character in Magiclysm an summoning the bow (not shown), or in a third partymod that spawns a weapon (not shown).

Maybe it's a change between the versions? Mine is 2024-11-27-1335

![1](https://github.com/user-attachments/assets/28ab008a-b39b-4c3c-ac13-6881c7756581)

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: ad13310 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    Personal Tweaks for Gameplay [PersonalTweaks]
]

**Comment by MorphingE** [comment]
> ~I cannot replicate this, either from the save (image), or by creating a fresh character in Magiclysm an summoning the bow (not shown), or in a third partymod that spawns a weapon (not shown).~
> 
> ~Maybe it's a change between the versions? Mine is 2024-11-27-1335~
> 
> Yeah it's that, nvm.

I appreciate being double-checked. Never know if I am breaking stuff, sometimes.
