### ISSUE TITLE
[MoM + No Hope] No Hope prevents MoM map extras from spawning properly

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#78338]
### Describe the bug

Running MoM and No Hope together prevents the spawning of MoM's overmap extras, most notably the crystal clusters that are the primary source of matrix crystals. Sometimes you get a bit of pseudo-terrain in the shape of what the MoM extras look like, but often it seems to just fail silently.

I've also not been able to find any instances of office_cubical_phavian (tested by searching "office" on the map and looking for buildings with "Origin:'Mind Over Matter'", but I have confirmed the presence of both crystal outcroppings and the MoM version of the research facility.

All the missing things are found in MoM's regional_overlay.json, so presumably there's some issue with that. Debug spawning the extras seems to work just fine.

### Attach save file

[No Mind_TEST-trimmed.tar.gz](https://github.com/user-attachments/files/18009636/No.Mind_TEST-trimmed.tar.gz)

### Steps to reproduce

Start a game with MoM and No Hope and try to find any map specials.

### Expected behavior

Mods do not interfere with each other spawning map extras unless explicitly intended to.

### Screenshots

![image](https://github.com/user-attachments/assets/733a9b5d-0a33-4885-b5e5-e234351c767f)
Some pseudo-terrain that looks like it was meant to be an MoM map extra.

![image](https://github.com/user-attachments/assets/996a93c0-27bb-4287-9f9b-1c53a9bb2726)
The MoM Research Facility as it appears with No Hope active. Note the lack of any weird crystal clusters or alien flora intruding on the building. The whole thing looks like this.

![image](https://github.com/user-attachments/assets/31499033-a017-47a2-a053-c7c61921defe)
For comparison, a research facility in a game 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 04cb3d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    No Hope [no_hope]
]

**Comment by Terrorforge** [comment]
UPDATE: changing the load order of the mods so the MoM comes after No Hope appears to fix this issue. I'm not sure if it still constitutes a bug or not; this is the first time I've encountered load order issues in CDDA, and it's possible that MoM is now overwriting No Hope content instead.

**Comment by Procyonae** [comment]
Related PR #74446
I have a branch open changing No Hope to use a region overlay that should fix all this, I'll try to get it up tomorrow

**Comment by Terrorforge** [comment]
![image](https://github.com/user-attachments/assets/e0221769-39a4-4f50-b1fe-f27c8e8f2b9f)
Still getting some pseudo-terrain with MoM below No Hope in the load order.

[No Mind-trimmed.tar.gz](https://github.com/user-attachments/files/18028253/No.Mind-trimmed.tar.gz)

**Comment by Maddremor** [comment]
If there is no easy enough way to fix this, I should note that this can be "fixed" by declaring No Hope incompatible with MoM.

**Comment by Procyonae** [comment]
> If there is no easy enough way to fix this, I should note that this can be "fixed" by declaring No Hope incompatible with MoM.

We don't have a method to do that
