### ISSUE TITLE
tname_i18n_order test sets language to system language instead of English

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#78334]
### Describe the bug

```
13:47:15.744 INFO : Setting language to: 'ru'
13:47:15.745 INFO : [i18n] Scanning core translations from lang/mo/
13:47:15.837 INFO : Setting language to: 'de'
```

This causes all subsequent tests that compare translated strings to fail.

On top of that, even if I force the test to set the language to English, the `math_parser_parsing` test will generate failures if it is run after `tname_i18n_order`. It passes when run on its own.
```
tests\math_parser_test.cpp(97): FAILED:
  CHECK( testexp.eval( d ) == Approx( 2 ) )
with expansion:
  0.0 == Approx( 2.0 )

tests\math_parser_test.cpp(129): FAILED:
  CHECK( testexp.eval( d ) == Approx( 87139.7243098 ) )
with expansion:
  -394.0162907268 == Approx( 87139.7243098 )

tests\math_parser_test.cpp(135): FAILED:
  CHECK( std::isnan( testexp.eval( d ) ) )
with expansion:
  false
```

Also maybe bonus issue: `\data\mods\TEST_DATA\lang\mo\ru\LC_MESSAGES\TEST_DATA.mo` isn't compiled when building tests with Visual Studio. But I also didn't manage to run `compile_mo.sh` and instead just made MSYS2 compile languages for me, so it might just be a me issue. Compiling tests in MSYS2 does compile the file as expected.

### Attach save file

n/a

### Steps to reproduce

Run `.\Cataclysm-test-vcpkg-static-Release-x64.exe tname_i18n_order,math_parser_parsing,item_name_pluralization` for example on a system with a different system language than English? German in my case, which might be relevant for the math parser issue.

`.\Cataclysm-test-vcpkg-static-Release-x64.exe tname_i18n_order,math_parser_parsing,item_name_pluralization --order lex` on the other hand will pass.

### Expected behavior

Tests pass.

### Versions and configuration

3173580d8ac5662aec5add59b751301e7058e0bc

**Comment by PatrikLundell** [comment]
I've recently (a few days ago) seen the math_parser_test failures when trying to run tests locally. My system is only partially set to English (I think various conventions are set to the local ones, as well as the keyboard, while the language UI as such is set to English).

**Comment by mqrause** [comment]
Yeah, `set_language( "en" )` was what I tried, but then ran into the math parser issue, which led me to believe there's a bit more going on that I don't understand. My best guess is that it's still using swapped decimal and thousand separators, though I'm not sure why and at what point that'd swap. That could explain why `"-1 ^ 0.5"` is a number (0.5 read as 0 or maybe 5 instead), but I can't really explain why `"clamp( 1, 2, 3 )"` fails but `"max( 1, 2, 3, 4, 5, 6 )"` succeeds. I'll probably have to step through it to see what actually happens.

Not sure I can offer better reproduction steps. I tested on regular German Win 11, and the language switching from `tname_18n_order` is necessary to cause the failure, that's really all I have right now.

**Comment by mqrause** [comment]
![grafik](https://github.com/user-attachments/assets/9bf5c120-7760-4b8b-9ff1-41a3a98a785a)
This is parsing `clamp( 1, 2, 3 )`. Parsing "1" actually returns std::nullopt despite std::strtod successfully setting val to 1. Because of that in `math_exp::math_exp_impl::_parse` it fails `if( std::optional<double> val = get_number( token ); val )` and instead goes to the else case and does whatever. The same goes for `7.123` in the complex calculation (except it also gets parsed as just 7).

So yes, it's doing something funky with `.` and `,`. The reason it works for `max` is that the 6 is in last place and not followed by a `,`, so it gets parsed successfully and is also the expected largest number. I switched places with the 4 to test and as expected it failed and returned 4 as max.

Changing region settings in my system also fixes the errors, so you should probably be able to reproduce when you set decimal separator to `,` and thousand separator to `.`. Unless it really is a Windows issue.

**Comment by mqrause** [comment]
Yeah, that fixes number parsing. Decimal numbers are still cut off, though, because it's still using the wrong separators, so it's still failing calculations with decimal numbers.
