### ISSUE TITLE
cannot scroll the achievements, kills, and scores screen (on android)

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#78331]
### Describe the bug

I cant scroll down the achievements, kills, and scores screen that has the newly imgui-ed screen.

### Attach save file

N/A

### Steps to reproduce

1. Open a world
2. open the achievements, kills, and scores menu `) then v`
3. Try scrolling down.

### Expected behavior

I can scroll down said screen

### Screenshots

https://github.com/user-attachments/assets/0303072f-22a9-4d83-bddf-bd307817077d

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: ZTE; Model: ZTE 8050; Release: 13; Incremental: 20240523.205226; 
- Game Version: cdda-experimental-2024-12-03-0525 eba9c9f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Xedra Evolved [xedra_evolved],
    GUT's Xedra Evolved Compendium [gut_xedra_compendium],
    horde tweaks [horde_tweaks],
    Martial Mastery [perk_melee_system],
    Funni Loading Screens [loading_screen_funni],
    Bombastic Perks [bombastic_perks],
    Work in Progress Limb Stuff [limb_wip]
]

**Comment by ZhilkinSerg** [comment]
Is it working properly in keybindings menu?

**Comment by gettingusedto** [comment]
You mean if the keybindings menu scrolls? Yeah it does scrolls in the keybindings menu.

**Comment by ZhilkinSerg** [comment]
I can't build & test on Android locally right now, but I've made some changes that might help to fix scrolling issues in score menu, so you could test once it is merged.

**Comment by gettingusedto** [comment]
@ZhilkinSerg looks like after the pr, the scores screen can be scroll now.
