### ISSUE TITLE
Error with Kaluptic Psychosis

### ISSUE THREAD

**Issue by MorphingE** [CleverRaven/Cataclysm-DDA#78349]
### Describe the bug

Wielded items try to speak, error, and only say "???" on repeat if ignored.

### Attach save file

[Kelly Lake.zip](https://github.com/user-attachments/files/18015924/Kelly.Lake.zip)
[PersonalTweaks.zip](https://github.com/user-attachments/files/18015925/PersonalTweaks.zip)

Attached my save and tweaks folder for verification.

### Steps to reproduce

Have Kaluptic Psychosis
Wield item
Wait until it tries to speak.

### Expected behavior

Use one of the multitude of dialog options that occur when your wielded item talks to you

### Screenshots

Receive the following error message when wielding something.
![image](https://github.com/user-attachments/assets/7cc3cd84-d213-4eed-8776-15e2879cc520)

Results in the following spam:
![image](https://github.com/user-attachments/assets/c46424da-3620-4597-9283-146ab0771813)

### Versions and configuration

Windows 10
CDDA Experimental Build: 2024-12-04-2101
![image](https://github.com/user-attachments/assets/dac4f346-4159-4133-8cdd-06c48131503d)

**Comment by GuardianDll** [comment]
for some reason #74360 renamed `<schizo_weapon_talk_bleeding>` to `schizo_weapon_talk_bleeding`
Seems to be accidental mistake, reverting it back to `<schizo_weapon_talk_bleeding>` should fix the problem
