### ISSUE TITLE
Recycling center is made of tables.

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#78376]
### Describe the bug

I mean, just look at it:
![Pheevos 'Carcosa' Gregory _2024-12-06T09-19-05](https://github.com/user-attachments/assets/c5d7626e-7ae5-4fca-9c80-ad7144ba75e7)

### Attach save file

[MA-trimmed.tar.gz](https://github.com/user-attachments/files/18039296/MA-trimmed.tar.gz)

### Steps to reproduce

Spawn a recycling center, & despair.

### Expected behavior

No tables in the walls

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.2033 (24H2)
- Game Version: 3173580 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip],
    Translate Complex Dialogue [translate_dialogue],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Crazy Cataclysm [crazy_cataclysm],
    Bombastic Perks [bombastic_perks],
    Alternative Map Key [alt_map_key],
    Xedra Evolved [xedra_evolved],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Massachusetts [MA]
]

**Comment by Karol1223** [comment]
@Milopetilo that one of yours? I know you've been wrestling palettes for a while now lol

**Comment by Milopetilo** [comment]
Yeah it does look like it is, I'm not home for the next few days though so if someone else wants to fix this that'd be appreciated :)
