### ISSUE TITLE
Light industry building should have wall wiring

### ISSUE THREAD

**Issue by Coyote-Bongwater** [CleverRaven/Cataclysm-DDA#78407]
### Is your feature request related to a problem? Please describe.

Light Industry buildings are sufficiently popular as player bases that there is even a faction camp layout specifically for them, and they include a bunch of stationary equipment that needs to be wired into a power grid, but the Reveal Wall Wiring construction cannot be used on the building's walls, requiring any power grid to be placed 100% manually as though the building never had electricity.

### Solution you would like.

The walls of Light Industry should have wiring in them that can be revealed and used in order to set up a power grid.

**Comment by Procyonae** [comment]
Fixed by #78515 (Potentially only in future worlds, not sure how adding wiring to pre-existing walls works)
