### ISSUE TITLE
[XEDRA Evolved] Monstrous Badger is killing stonelings despite being in the same faction

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#78408]
### Describe the bug

For some reason, Ierde's monstrous badger seems to be beefing on stonelings and killing them. Now theres a bunch of dead stonelings in my altar cuz the badger kills them.

### Attach save file

N/A

### Steps to reproduce

1. Debug spawn in a monstrous badger and stoneling close to each other.
2. see the badger kills the stoneling for no reason

### Expected behavior

It shouldnt do that.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: ZTE; Model: ZTE 8050; Release: 13; Incremental: 20240523.205226; 
- Game Version: cdda-experimental-2024-12-07-0523 cfe9f6c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Xedra Evolved [xedra_evolved],
    GUT's Xedra Evolved Compendium [gut_xedra_compendium],
    horde tweaks [horde_tweaks],
    Martial Mastery [perk_melee_system],
    Funni Loading Screens [loading_screen_funni],
    Bombastic Perks [bombastic_perks],
    Work in Progress Limb Stuff [limb_wip]
]

### Additional context

There's also the case for the Homullus' animorphic figurine killing venus figurines, though i noticed it only happened on the animorphic figurine that comes with the player as their pet in the Paracleisan birth scenario

**Comment by Standing-Storm** [comment]
/confirmed. Not only that, stonelings are attacking each other.

![Untitled2](https://github.com/user-attachments/assets/950db550-808d-47ff-899a-ce349970c5c6)
