### ISSUE TITLE
Large storage batteries that are almost destroyed turn into medium storage batteries after removing from a vehicle

### ISSUE THREAD

**Issue by kuutekitty** [CleverRaven/Cataclysm-DDA#78410]
### Describe the bug

After removing a almost destroyed large storage battery from a vehicle, it transforms into a medium storage battery
### Attach save file

https://www.dropbox.com/scl/fi/2tsoojddfrx5vwf9wyx2k/Nicholls-trimmed.tar.gz?rlkey=jtvb5jxllmehc76p625qkbm5d&st=pqdeyx3w&dl=0

### Steps to reproduce

1.Load save file
2.Examine the vehicle tile right above the player
3.Remove the large storage battery battery
4.The transformed medium storage battery is now in the inventory

### Expected behavior

I expect that the battery would retain it's damage and would not morph into a different type of battery.

### Screenshots

![image](https://github.com/user-attachments/assets/535ca4ef-3579-4067-9d06-ac1d86260f8a)
![image](https://github.com/user-attachments/assets/49a787e6-f342-4755-990a-c9165350e622)
![image](https://github.com/user-attachments/assets/2e311d64-0863-40f3-a9aa-486372345adb)

### Versions and configuration

OS- Windows 10
Game version: 78fde3
Graphics version: tiles
In game language: English
Mods: Dark Days ahead; Disable npc needs; Portal storms ignore npcs; Slowdown fungal growth; Bombastic perks; My sweet cataclysm; sees-player, run, crouch, bleed icons; SpeedyDex

### Additional context

This may not happen to large storage batteries of all states (I have removed other large storage batteries which were not this damaged without my character resorting to alchemy)

**Comment by RenechCDDA** [comment]
Your large storage battery was not "almost destroyed", it just *was* destroyed (`XX` damage). Receiving components of the base item when removing the husk of a destroyed vehicle part is the intended behavior.
