### ISSUE TITLE
Make anvils craftable without using power tools and more manageble metalworking recipies

### ISSUE THREAD

**Issue by kuutekitty** [CleverRaven/Cataclysm-DDA#78422]
### Is your feature request related to a problem? Please describe.

It doesn't really make sense that the only way to make steel anvils is with power tools, there is no realism argument for it, steel anvils shouldn't be locked behind power tools, because this can heavily disrupt playthrough where you don't have a lot of access to power tools or can just wander around till you just find one.

### Solution you would like.

Add a crafting recipe for steel anvils that doesn't require power tools. The recipe can be the same, similar to or different to the one for bronze anvils. The recipe also should not require tools that can only be made with an anvil (besides bronze anvils, it would make sense for a bronze anvil to be a prerequisite to a steel anvil).

### Describe alternatives you have considered.

Heavily increasing the amount of recipes you can make with a bronze anvil (this would not solve the underlying problem but would reduce it at least).

### Additional context

I'm not calling for the current recipe to removed, just for another one, which requires no power tools (and hopefully no tools that require steel anvils in the first place) to be made.

**Comment by GuardianDll** [comment]
Having a recipe to hacksaw the anvil may be reasonable, with a price of you spending a week doing it
Overall most recipes with power tools, mainly angle grinder, make little sense, they speed up the task very not enough, my quick calculations shows most our recipes to cut metal stuff need to be recalculated, for they need to spend 50x times more energy and time they spend now

**Comment by kuutekitty** [comment]
A one week recipe would be grueling but better than no recipe, but no, hacksaws require steel anvils to craft, it would be best if the recipe to make a steel anvil does not require an item that can only be made with a steel anvil, not just for realisms sake, but so you aren't forced to go and look for one specific item before making the steel anvil because there's no craftable recipies for it that don't require steel anvils and can just make it without the steel anvil.

**Comment by kuutekitty** [comment]
> my quick calculations shows most our recipes to cut metal stuff need to be recalculated, for they need to spend 50x times more energy and time they spend now
I think that would honestly be going into borderline unfun territory for realisms sake and don't know if it would be a good road to go down on (depending on how long it would take), it would not add any extra challange as far as mid and end game is concerned, which is what these items are, so, it would simply add a very boring timer before the fun thing happens (I have the same gripe with some tailoring recipe I saw that takes a week to make, it's practically just telling you to go find the item, although I was lacking like 3/4 proficiencies so that's a much more understandable case)

**Comment by GuardianDll** [comment]
\> hacksaws require steel anvils to craft
to make tongs you need tongs. The way to obtain tongs is to loot them. The game do not need to have a way to craft all the thing out of sticks and stones

also i did not say we need to make recipes consume 50 times more resources and time, i say they need to be redone, in the way that do not require user to spend 50 times as much time as resourses while still being reasonable

**Comment by kuutekitty** [comment]
>to make tongs you need tongs. The way to obtain tongs is to loot them. The game do not need to have a way to craft all the thing out of sticks and stones

flatjaw tongs already have a casting recipe that doesn't require tongs, so you're wrong on that, and it would take very little effort to just copy the bronze anvil recipe over to the steel one, I wouldn't mind it if steel anvils were hard to get, but this isn't hard or complicated, I wouldn't even have that hard of a time doing one, (as long as I find out where rail tracks even spawn, I've never seen one and hhg does not help) but the larger problem is all the tools are very hard to get, or are completely up to luck, and you can't make them without having them in the first place, the chisel should also have a casting recipe, just like the tongs,
and could require something like a polishing stone, so it still wouldn't be easy, but give you a way that isn't just "find it or fuck you"

**Comment by kuutekitty** [comment]
people who play with no cities or very low city density could literally just never find an angle grinder and be completely locked out of making their own really good weapons

**Comment by Aimless-dude** [comment]
Piggybacking onto this to say even if you do manage to get yourself a battery powered saw, there's not enough juice in it for you to finish the action. And because sawing up some railroad tracks is an Activate action, progress resets when the battery runs out.

**Comment by kuutekitty** [comment]
you probably wanna create a bug report for that

**Comment by kevingranade** [comment]
The way forward here is for you to provide a recipe (it doesn't have to be the full job or have completely correct values but it needs to have the list of tools and materials) for the craft and sources that sort that that recipe would work.

Otherwise this is absolutely not happening,  we don't make easier versions of recipes based on gameplay concerns.

**Comment by kuutekitty** [comment]
I will try to, could you elaborate on the "sources that sort that that recipe would work" part? the most coding I've ever done or anything resembling the sort is stumbling my way through xml files in modded rimworld to change a few values because I wanted to, but I could maybe get a decent recipe for both the metalworking chisel and the steel anvil that would be more friendly to people with less access to technology

**Comment by Zireael07** [comment]
Yes Kevin means real-world sources here, not code source

**Comment by kuutekitty** [comment]
Thank you, will do, if I remember to, I'll post it here today or tomorrow, or later depending on how much research I find out I have to do.

**Comment by kuutekitty** [comment]
I think this would more or less be completely fine as a recipe for a metalworking chisel

Primary Skill
fabrication (3)
Proficiencies
Principles of Metalworking (1.5× time, 0.5 skill bonus)
Manual Tooling (2× time, 0.15 skill bonus)
Quenching & Tempering (1.5× time, 1 skill bonus)
Time to Complete
125 m
Activity Level
Moderate
Batch Time Savings
none
Tools Required
1 tool with anvil of 1 or more. (crude anvil should be enough as there is little hammering involved)
1 tool with hammering of 3 or more.
1 tool with grinding of 2 or more.
electric forge (60 charges) OR basecamp forge (60 charges) OR charcoal forge (60 charges) OR gas forge (60 charges) OR acetylene torch (60 charges)
metal tank (2 L)
water or clean water
pair of flatjaw tongs OR pair of flatjaw bronze tongs
Components
1 spring (from what I've seen springs are more commonly actually made from steel and not cast iron, especially for things like suspension systems, https://www.centuryspring.com/resources/types-of-spring-materials-and-their-applications)
Autolearn
fabrication (3)

Sources: Main source for recipe-https://www.instructables.com/HAND-FORGED-Cold-Chisel-From-a-Rusty-Old-Coil-Spri/
Info on spring materials: https://www.centuryspring.com/resources/types-of-spring-materials-and-their-applications

**Comment by kuutekitty** [comment]
The anvil recipe will most likely take much longer due to needing much more research and a lot less step by step guides because very few people will willingly make an anvil without power tools in this day and age (I'll most likely include the metalworking chisel in the recipe or a hotcut or something).

**Comment by DavidAGi** [comment]
> I think this would more or less be completely fine as a recipe for a metalworking chisel (besides the time, I forgot to edit that from the template I started)
> 
> Primary Skill fabrication (4/5) Proficiencies Principles of Metalworking (1.5× time, 0.5 skill bonus) Manual Tooling (2× time, 0.15 skill bonus) Quenching & Tempering (1.5× time, 1 skill bonus) Time to Complete 125 m Activity Level Moderate Batch Time Savings none Tools Required 1 tool with anvil of 1 or more. (crude anvil should be enough as there is little hammering involved) 1 tool with hammering of 3 or more. 1 tool with grinding of 2 or more. electric forge (60 charges) OR basecamp forge (60 charges) OR charcoal forge (60 charges) OR gas forge (60 charges) OR acetylene torch (60 charges) metal tank (2 L) water or clean water pair of flatjaw tongs OR pair of flatjaw bronze tongs Components 1 spring (from what I've seen springs are more commonly actually made from steel and not cast iron, especially for things like suspension systems, https://www.centuryspring.com/resources/types-of-spring-materials-and-their-applications) Autolearn fabrication (3)
> 
> Sources: Main source for recipe-https://www.instructables.com/HAND-FORGED-Cold-Chisel-From-a-Rusty-Old-Coil-Spri/ Info on spring materials: https://www.centuryspring.com/resources/types-of-spring-materials-and-their-applications



That source is meh and...
Your source indicates the use of a T3 anvil.
Your source indicates the use of a bellows or a "hairdryer" to add oxygen to the fire.
Your source indicates the use of a Forge hammer -> T4 hammer.
Your source lists the use of protective eyewear/respirator.
Your source only indicates that a file could be used.
Your source lists tongs; however, it does not mention the use of flat-jaw tongs but rather round stock tongs (Picture).

In addition to these points, this source (https://www.youtube.com/watch?v=qmQZHWHFa9Q) also indicates that a power tool is not necessary.

However, the book "New Edge of the Anvil: A Resource Book for the Blacksmith" states:

p. 33 f. It is indicated that spring steel is not tool steel; therefore, you would need high-carbon steel.
p. 31. Gas-fired forge furnaces are somewhat unsuitable for heat treating.
Source: https://books.google.de/books?hl=de&lr=&id=mecE6dX7HlIC&oi=fnd&pg=PR11&dq=metal+working+anvil&ots=4Ee3iOnkkq&sig=JAjvBQSMSmxyZa69JOXpWo-2UDo&redir_esc=y#v=onepage&q=metal%20working%20anvil&f=false

Additionally, the book The Beginner's Guide to Blacksmithing (https://www.google.de/books/edition/The_Beginner_s_Guide_to_Blacksmithing/zqR9EAAAQBAJ?hl=de&gbpv=1&dq=How+to+make+an+anvil&pg=PA18&printsec=frontcover) states:

p. 18. Early anvils were made out of cast iron, but modern anvils are made out of tool steel and must weigh at least 68 kg (150 pounds).
p. 23 f. Lists all types of tongs.
p. 21 f. indicates the necessity of a Hmmer set for smithing.
p. 30 f. Indicates that a coal forge also requires additional tools.

**Comment by kholat** [comment]
What does being niche have to do with existing?

In the medieval ages people did not have modern anvils yet they made swords. Enough swords to be killing each other all the time.

I do not understand how come the elite contributors have such bad logic about this.

**Comment by kuutekitty** [comment]
> That source is meh and... Your source indicates the use of a T3 anvil. Your source indicates the use of a bellows or a "hairdryer" to add oxygen to the fire. Your source indicates the use of a Forge hammer -> T4 hammer. Your source lists the use of protective eyewear/respirator. Your source only indicates that a file could be used. Your source lists tongs; however, it does not mention the use of flat-jaw tongs but rather round stock tongs (Picture).
> 
> In addition to these points, this source (https://www.youtube.com/watch?v=qmQZHWHFa9Q) also indicates that a power tool is not necessary.
> 
> However, the book "New Edge of the Anvil: A Resource Book for the Blacksmith" states:
> 
> p. 33 f. It is indicated that spring steel is not tool steel; therefore, you would need high-carbon steel. p. 31. Gas-fired forge furnaces are somewhat unsuitable for heat treating. Source: https://books.google.de/books?hl=de&lr=&id=mecE6dX7HlIC&oi=fnd&pg=PR11&dq=metal+working+anvil&ots=4Ee3iOnkkq&sig=JAjvBQSMSmxyZa69JOXpWo-2UDo&redir_esc=y#v=onepage&q=metal%20working%20anvil&f=false
> 
> Additionally, the book The Beginner's Guide to Blacksmithing (https://www.google.de/books/edition/The_Beginner_s_Guide_to_Blacksmithing/zqR9EAAAQBAJ?hl=de&gbpv=1&dq=How+to+make+an+anvil&pg=PA18&printsec=frontcover) states:
> 
> p. 18. Early anvils were made out of cast iron, but modern anvils are made out of tool steel and must weigh at least 68 kg (150 pounds). p. 23 f. Lists all types of tongs. p. 21 f. indicates the necessity of a Hammer set for smithing. p. 30 f. Indicates that a coal forge also requires additional tools.

I'll take this into account and put more research into it before making any new recipies, I greatly underestimated the amount of research this would take (not for the anvil, I realized I was way in over my head the second I started doing any research on it), I still think it would be a positive overall for the game if there were more anvil and recipies for anvil tools (tier four hammers do not exist in CDDA, maybe you were referring to the drop hammer, I'll re read my source and the things you've linked).

This is where most of the response ends, this last part is more of my thoughts and opinions, than anything else.

 (for the reasons I've talked about, this would also make fully medieval playthroughs/total conversions simpler and easier, and no I am not aware if any such mods exist as I do not know a good way to search for CDDA mods as, as you can likely tell, I'm new to the community (besides playing a lot and watching a few tutorials half a year/a year or more ago, I've never interacted with the actual community)), so I'll see if I *can* find plausible ones, even if they're very annoying to do, and most people would be better off just finding their own anvil or making one with an angle grinder. To anyone still reading, expect a new recipe this week, no promises when, but I'll either update this this week or have a new recipe, maybe, by the end of the week, help, thoughts on this, more sources, and anything else you'd like to share about it, I'll gladly listen. I have no expertise on the topic (the most I know is getting as far as wrought iron in Terrafirmagreg if that means anything to anyone here, I kind of gave up when I realized the hell that will be graphite) and will gladly accept any help.

**Comment by DavidAGi** [comment]
You are right there is no T4 hammer/hammerset, but someone could discuss introducing one. Together with new tohngs.

Personally, I like reading the comments and I respect your effort for the community very much.

Basically, you could discuss differentiating forging a little further. Currently T1 anvils are more or less a stone. T2 anvil are bronze and improvised steel Items. T3 is steel. Maybe you could differentiate between iron and steel and you could make complex and simple anvils with just a smooth surface or with the additional extras like the horn. These would then have the quality of complex anvils, for example. But it would probably not be possible without a lot of work and a table.  (<- my Hypothesis without sorces)  However, I think this process also began with the introduction of high carbon steel.

I have deliberately always spoken of “indicates”, I do not know many things and I do not know whether my sources are correct. 

Apart from that, the focus of the game should be on exploration and not on crafting. To a certain extent, it is deliberate not to be able to craft everything out of nothing. -> If this is not true, someone please correct me.

**Comment by IdleSol** [comment]
As an option, replace anvil quality with a set of qualities. That is, to go from an anvil of level 1...3 to an anvil with the quality of hardness, flat surface, horns, and what else they have there. But for this we need people who understand blacksmithing to explain what is used for what.

>People asking for easier anvils is pretty common, and I think one major reason is that people don't get how niche blacksmithing is. Just because it's a part of the CDDA meta at some point doesn't mean that it make sense to start forging swords instead of just using whatever you can loot, or cut things from sheet metal when nothing suitable is at hand.

An anvil is required for almost any tool. Need a tailor's kit? Look for an anvil. Want to build a house? Look for an anvil. Armor, weapons, your own vehicle... everything requires an anvil. And creating an anvil requires tools that are created on the anvil.

With the default settings, it's not too flashy. Most tools and weapons can be found. Reduce the amount of stuff, down to 10%. And you'll be happy to find a lighter.

Not that it's a problem. There are still traders you can buy tools from. But my personal opinion is that two ways are better than one.

P.S.
- #72208

**Comment by AideeAmei** [comment]
I consulted a professional and while not ideal, it is perfectly possible to craft steel tools using bronze anvil. It needs to be done in a peculiar way, avoiding heavy blows if possible and using a milder steel, but it is possible. I think the current in-game situation is neither well balanced nor makes sense. Make it hard, not impossible, is what I'm saying. It's dark days ahead, not no light ever again.

**Comment by kuutekitty** [comment]
Another not that important message relatively speaking, all of these points will be argued with sources when the time comes, now is not the time. (I mark these so devs don't waste time reading things not worth reading)

Also, just for clarification, I think it would be best if the majority of the playerbase would be best left off exploring to find these items, and will possibly be making these recipies in such a manner as to encourage that, this is about making it possible to make your own smithy if you *can't* find these things, not providing a better alternative, or one that's just as good (I may do this by making anvil recipies multi step, (for ones with no power tools), generally speaking be a pain in the ass, or simply not be worth it when guns are around or a wood axe is good enough ). Setting up a smithy by yourself should be a very hard thing to do, with not much reward in modern times (you could find much better gear in the time it takes to make a smithy), but completely indespensible in a medieval playthrough or playthroughs with no cities/very little city density, I'm kinda locked on also giving anvils two more qualities horned for horned anvils, and anvil with hardy hole for anvils with hardy holes (I plan on mostly leaving the current anvil system in place besides the recipies which would require these qualities, and making a bronze anvil a T2 anvil), and also introducing a forge hammer which will be used for all or almost all the black/redsmithing recipies (I might have to do anvil recipies first and try to figure this whole thing out, it is not going to be easy but I'll be doing my best to make a recipe tree that is linear (ish) and does not require finding things, to the best of my ability, I may make 2-3 recipies for some items (especially anvils, I'll most likely try to come up with 2 additional recipies to remove the power tool requirement), but plan to leave most recipies currently in the game alone and simply to add these new ones)

**Comment by kevingranade** [comment]
Closing as people are just using this for discussion now.  If you have sources outlining recipes that require fewer tools feel free to open an issue around that.
