### ISSUE TITLE
Swiss Army knife should have Level 1 awl quality

### ISSUE THREAD

**Issue by DexterBobo** [CleverRaven/Cataclysm-DDA#78434]
### Is your feature request related to a problem? Please describe.

Swiss Army knife does not have in-game awl quality even thought awls are a very common tool for them to contain in real life (even more common than a saw, which the current in-game Swiss Army knife already has). Awl quality is also relatively rare in-game - every awl helps!

### Solution you would like.

Add Level 1 awl tool quality to Swiss Army knife

### Additional context

Almost every version on this product listing page features an awl: https://www.victorinox.com/en-US/Products/Swiss-Army-Knives/Medium-Pocket-Knives/c/SAK_MediumPocketKnives/. 

![image](https://github.com/user-attachments/assets/965f82a5-e1a9-4ef3-8315-6fff601853b4)

In action!:
![image](https://github.com/user-attachments/assets/43e626c0-5767-4308-86e7-5a4381231d12)

**Comment by moxian** [comment]
I think this is a reasonable suggestion, and should be an easy [first PR](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) for whoever wants to tackle it!
