### ISSUE TITLE
fighting stances selection window stays on top of fighting details windows

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#78431]
### Describe the bug

When selecting the details of a fighting stance the selection window remains on top of the details window, making it impossible to read.

### Attach save file

[Treasure Island-trimmed.tar.gz](https://github.com/user-attachments/files/18054011/Treasure.Island-trimmed.tar.gz)

### Steps to reproduce

1. open fighting stance menu
2. select details
3. observe that the fighting stance menu window remains on top of the details window

### Expected behavior

details window should be on top

### Screenshots

no screen shot

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: 9bd8345 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Bombastic Perks [bombastic_perks],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

N/A

**Comment by AlexMooney** [comment]
- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.3; Release: 21.3; Codename: virginia; 
- Game Version: cdda-experimental-2024-12-08-1745 9bd83459-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

Confirmed.
![image](https://github.com/user-attachments/assets/e588e10d-0189-423d-9e0a-57caaebd5b73)

**Comment by TadhgEomonn** [comment]
Thank you.
