### ISSUE TITLE
Recipes Not Shown for Books with Many Recipes

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#78448]
### Describe the bug

For books that contain many recipes, there is no way to view those recipes after they are listed the first time you read them. You can look at the inventory, but the list of recipes it shows there is not comprehensive and there is no way to scroll to see the rest.
![Screenshot 2024-12-09 130338](https://github.com/user-attachments/assets/d2865380-df4d-4043-9466-0ca2d92bb420)

### Attach save file

[The Dark Forest-trimmed.tar.gz](https://github.com/user-attachments/files/18066920/The.Dark.Forest-trimmed.tar.gz)

### Steps to reproduce

1. Make a book with many recipes like Outdoor Survival Guide.
2. Notice you can't see all the recipes it contains in the inventory entry.

### Expected behavior

I expect for the entire list of recipes a book offers to be listed the same way "Can be stored in:" entry is exhaustive. This seems like the easiest solution as there is now a way to scroll up and down in inventory entries to see details.

### Screenshots

![Screenshot 2024-12-09 130338](https://github.com/user-attachments/assets/684221ad-dbc2-45e8-b5fd-2ce8b378cc79)

### Versions and configuration

-Windows 11
- 0.H Tiles and Sound Version

**Comment by RenechCDDA** [comment]
"and 30 more"
"and 23 more"
"and 12 more"

Not a bug.

**Comment by EricFedrowisch** [comment]
Ok. I'll move this to "request a feature" then...It may not be a "bug" but it is still poor design. There is NO way to see what recipes are in a book after you read it once. Is this really intentional? Why?
