### ISSUE TITLE
Cook one sparrow egg I'm starving over here

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#78459]
### Is your feature request related to a problem? Please describe.

some people only have a single sparrow egg and a luxury RV, and cannot cook and eat the egg

### Solution you would like.

allow one sparrow egg to be cooked in the boiled egg recipe

**Comment by Karol1223** [comment]
No, boiled egg item is specifically just enough boiled egg material to roughly equal in weight a boiled chicken egg. Changing this would break nutritional tests and generate mass, which is unacceptable.

Eat it raw. It's safe.

But if your only food is a single sparrow egg you have bigger problems to worry about.
