### ISSUE TITLE
SIGABRT:  Reading a scroll causes crash in spellbook_callback::refresh() -> ImGui:BeginChildEx

### ISSUE THREAD

**Issue by ghiknt** [CleverRaven/Cataclysm-DDA#78476]
### Describe the bug

Reading the the scroll in starting tower causes crash.  
- Tried with two different starts.  
- Appears to be regression between  "cdda-experimental-2024-11-26-0822 1ecb260" where it worked and "cdda-experimental-2024-12-10-1632 ff1d0cd"

### Attach save file

[Grapevine-trimmed.tar.gz](https://github.com/user-attachments/files/18085153/Grapevine-trimmed.tar.gz)

### Steps to reproduce

1. Activate (or Read) the "Scroll of Stormfist" in inventory

### Expected behavior

Bring up window showing scroll contents to allow learning if desired.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: cdda-experimental-2024-12-10-1632 ff1d0cd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[grapevine-crash-debug.zip](https://github.com/user-attachments/files/18085156/grapevine-crash-debug.zip)

**Comment by ghiknt** [comment]
Issue first appears in release https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-11-28-1212 which included change of...

- Upgrade ImGui version to 1.91.5 by @ZhilkinSerg in https://github.com/CleverRaven/Cataclysm-DDA/pull/78144

**Comment by ZhilkinSerg** [comment]
Doesn't crash for me on Windows MSVC build, so it could be Linux-specific (and because MSVC is less strict).

Crash is on the line 5955 of `imgui.cpp` which is:

```C++
IM_ASSERT((child_flags & ~ImGuiChildFlags_SupportedMask_) == 0 && "Illegal ImGuiChildFlags value. Did you pass ImGuiWindowFlags values instead of ImGuiChildFlags?");
```
Thus most probably following patch should help:

```DIFF
diff --git a/src/magic.cpp b/src/magic.cpp
index 96038ff396..a5e5915251 100644
--- a/src/magic.cpp
+++ b/src/magic.cpp
@@ -2529,7 +2529,7 @@ class spellcasting_callback : public uilist_callback
             ImGui::SameLine( 0.0, -1.0 );
             ImVec2 info_size = ImGui::GetContentRegionAvail();
             info_size.y -= ImGui::GetTextLineHeightWithSpacing();
-            if( ImGui::BeginChild( "spell info", info_size, false,
+            if( ImGui::BeginChild( "spell info", info_size, ImGuiChildFlags_None,
                                    ImGuiWindowFlags_AlwaysVerticalScrollbar ) ) {
                 if( menu->previewing >= 0 && static_cast<size_t>( menu->previewing ) < known_spells.size() ) {
                     display_spell_info( menu->previewing );
@@ -3194,7 +3194,7 @@ void spellbook_callback::refresh( uilist *menu )
 {
     ImGui::TableSetColumnIndex( 2 );
     ImVec2 info_size = ImGui::GetContentRegionAvail();
-    if( ImGui::BeginChild( "spellbook info", info_size, false,
+    if( ImGui::BeginChild( "spellbook info", info_size, ImGuiChildFlags_None,
                            ImGuiWindowFlags_AlwaysAutoResize ) ) {
         if( menu->selected >= 0 && static_cast<size_t>( menu->selected ) < spells.size() ) {
             draw_spellbook_info( spells[menu->selected] );

```

**Comment by ZhilkinSerg** [comment]
Please confirm whether it helped or not.

**Comment by Night-Pryanik** [comment]
I didn't get the crash on Windows either.

**Comment by ghiknt** [comment]
Unfortunately it still crashed for me the same way using cdda-experimental-2024-12-11-0835 653a131 [64-bit] on linux.

Since it is not happening on windows if needed I can re-setup my build environment and run debug code for you if you want.

- Attaching updated log / save files using current version.
    - [024-12-11-0835-Grapevine-trimmed.tar.gz](https://github.com/user-attachments/files/18098507/024-12-11-0835-Grapevine-trimmed.tar.gz)
    - [2024-12-11-0835-crash-debug.zip](https://github.com/user-attachments/files/18098514/2024-12-11-0835-crash-debug.zip)

**Comment by ghiknt** [comment]
Confirmed this fixed my issue.  Thank you.
