### ISSUE TITLE
Crash: SIGSEGV during monmove | ... | get_prev_dir

### ISSUE THREAD

**Issue by ghiknt** [CleverRaven/Cataclysm-DDA#78473]
### Describe the bug

Game Seg faults during boat movement presumably due to unseen underwater monster.

VERSION: cdda-experimental-2024-11-26-0822 1ecb260
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    0x614,a28,fd7,e3b    src/debug.cpp:979    bt_full
    0x614,a28,fd7,e3b    src/debug.cpp:1,244    debug_write_backtrace(std::ostream&)
    0x614,a28,fb0,ee2    src/crash.cpp:89    log_crash
    0x614,a28,fb1,22f    src/crash.cpp:146    signal_handler
    0x7df,43e,e5b,04f    [unknown src]:0    [unknown func]
    0x614,a29,9eb,967    src/simple_pathfinding.cpp:240    get_prev_dir
    0x614,a29,9eb,967    src/simple_pathfinding.cpp:459    pf::find_overmap_path(coords::coord_point_ob<tripoint, (coords::origin)1, (coords::scale)2> const&, coords::coord_point_ob<tripoint, (coords::origin)1, (coords::scale)2> const&, int, std::function<pf::omt_score (coords::coord_point_ob<tripoint, (coords::origin)1, (coords::scale)2>)> const&, std::function<void (unsigned long, unsigned long)> const&, std::optional<int> const&, bool)
    0x614,a29,86e,cd9    src/overmapbuffer.cpp:968    overmapbuffer::get_travel_path(coords::coord_point_ob<tripoint, (coords::origin)1, (coords::scale)2> const&, coords::coord_point_ob<tripoint, (coords::origin)1, (coords::scale)2> const&, overmap_path_params const&)
    0x614,a29,735,258    src/npcmove.cpp:4,898    npc::set_omt_destination()
    0x614,a29,735,752    src/npcmove.cpp:2,637    npc::long_term_goal_action()
    0x614,a29,74d,c3d    src/npcmove.cpp:1,537    npc::move()
    0x614,a29,03d,439    src/do_turn.cpp:363    monmove
    0x614,a29,03d,439    src/do_turn.cpp:657    do_turn()
    0x614,a28,abc,8ec    src/main.cpp:863    main
    0x7df,43e,e46,249    [unknown src]:0    [unknown func]
    0x7df,43e,e46,304    [unknown src]:0    [unknown func]
    0x614,a28,c1c,23d    [unknown src]:0    [unknown func]
    0xf,fff,fff,fff,fff,fff    [unknown src]:0    [unknown func]

### Attach save file

[Millington-trimmed.tar.gz](https://github.com/user-attachments/files/18083370/Millington-trimmed.tar.gz)

### Steps to reproduce

1. Pause (. or 5) x 7 times - Boat should move forward and then SIG Fault

### Expected behavior

Not Crash

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: cdda-experimental-2024-11-26-0822 1ecb260 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[crash-debug-logs.zip](https://github.com/user-attachments/files/18083525/crash-debug-logs.zip)

**Comment by RenechCDDA** [comment]
Should have been resolved by #78168

Please update to a version newer than that PR and see if the issue persists.

**Comment by ghiknt** [comment]
Confirmed already fixed in build...

- Game Version: cdda-experimental-2024-12-10-1632 ff1d0cd [64-bit]

Thank you
