### ISSUE TITLE
game-crashing mutation bug

### ISSUE THREAD

**Issue by Primordial-Kaos** [CleverRaven/Cataclysm-DDA#78481]
### Describe the bug

was exploring a lab with Xedras Evolved on, using the Paraclesian Birth start. ever since i used a few artifacts, the game will try to give me a random mutation and crash. 
here's the bug log:
 DEBUG    : Tried to use an invalid beta talker.  Callstack: EOC: EOC_random_mutate

 FUNCTION : const_actor
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 2605
 VERSION  : 7b67e86

### Attach save file

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: 52e00eb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Steps to reproduce

It happens at semi-random points, so waiting for a few hours seems to be the only reliable way to recreate it

### Expected behavior

I expected for the game to not hard crash at semi-random intervals

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: 52e00eb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[crash.zip](https://github.com/user-attachments/files/18087597/crash.zip)
[debug.zip](https://github.com/user-attachments/files/18087598/debug.zip)
[Hallstead save file.zip](https://github.com/user-attachments/files/18087620/Hallstead.save.file.zip)

**Comment by Procyonae** [comment]
Can repro on today's exp

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: e4af39e502-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

[debug.log](https://github.com/user-attachments/files/18100404/debug.log)
[crash.log](https://github.com/user-attachments/files/18100403/crash.log)

**Comment by Primordial-Kaos** [comment]
got it reproducible, wait in the same position/move abt 6 tiles and it happens
[crash (2).zip](https://github.com/user-attachments/files/18105415/crash.2.zip)
[debug (2).zip](https://github.com/user-attachments/files/18105416/debug.2.zip)
[Hallstead new file.zip](https://github.com/user-attachments/files/18105423/Hallstead.new.file.zip)

**Comment by Primordial-Kaos** [comment]
misread the previous comment and thought it said _can't_ sorry i'm dumb

**Comment by Etos7** [comment]
Same issue

**Comment by Procyonae** [comment]
Duplicate issue above has a save that might be more useful for testing

**Comment by Primordial-Kaos** [comment]
Had the exact same issue with another char. I’ll link the save tomorrow
