### ISSUE TITLE
View is slightly bugged when building/deconstructing

### ISSUE THREAD

**Issue by Vulp0d** [CleverRaven/Cataclysm-DDA#78489]
### Describe the bug

View moves several tiles down when building/deconstructing anything and stays there after building or canceling, requiring the player to center view manually, which shouldn't be the case.

### Attach save file

N/A

### Steps to reproduce

1. Create a new world and character.
2. Open build menu and choose e.g. Make crafting spot.
3. Build or cancel.
4. View the result.

### Expected behavior

View doesn't move several times down and/or centers itself automatically on the player after building/cancelling/

### Screenshots

![bug1](https://github.com/user-attachments/assets/79722eec-6271-4cd5-a096-f48ed485f9ef)
![bug2](https://github.com/user-attachments/assets/8ba8de10-9c81-4f72-a084-bc1f21535080)
![bug3](https://github.com/user-attachments/assets/7603fa44-f30b-44ed-a548-d9e670757445)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: cdda-experimental-2024-12-11-0835 653a131 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

N/A

**Comment by Procyonae** [comment]
Got borked sometime in the last ~5 days

**Comment by kwl01skz** [comment]
Old: Moved the camera up so that the character is not obscured by the menu. Returns the camera to its original position when the menu disappears.
Now: Moved the camera up to keep the character from being obscured by the menu.
