### ISSUE TITLE
Vehicle turret tests fail randomly

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#78539]
### Describe the bug

Vehicle turret tests fail randomly on PRs unrelated to the tested functionality, and, what's worse, does so in a non repeatable fashion.

### Attach save file

N/A, this is about the github tests failing randomly (attempting to reproduce it locally using the same seed failed, although that could potentially have been because some other tests failed due to local environment not having something preceding tests needed).

### Steps to reproduce

Trigger the test suite until the error sequence is encountered (one failure for every(?) possible turret mounted weapon.

### Expected behavior

No flaky tests.

### Versions and configuration

N/A. It's a github issue.

### Additional context

The failure is caused by an inability to spawn a test vehicle at the standard location, despite attempts by the test to clear everything out. Thus, the reason for the failure is unknown.

What's probably needed to locate the problem is some way to determine why the vehicle can't be spawned (unless someone can analytically identify something that isn't cleared properly). If it was possible to access the debug output from failed tests (and I haven't found a way to do so), it might be reasonable to add such an output to the vehicle spawning code on a failure, containing info specifying why the spawning failed.

If there's some state set on tests that can be picked up by error reports it might even be possible to only generate such a report on a test failure, and do so to the test log. If such a state is available, it might even be possible to do a bit of work to create the test report (such as scanning terrain, etc. to verify that it is actually the expected type).

**Comment by mqrause** [comment]
/confirmed

Example for a failure: https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/12311260870/job/34361182608?pr=78511#step:19:111

For the record, I tried a few local runs of the test suite with random seeds to reproduce it, but it simply never happened. Though I'm not sure if I just didn't try often enough (in the range of 10-20 times) or if it just does not happen on Windows/MSVC.

**Comment by Procyonae** [comment]
```
            vehicle *veh = here.add_vehicle( STATIC( vproto_id( "test_turret_rig" ) ),
                                             tripoint_bub_ms( 65, 65, here.get_abs_sub().z() ), 270_degrees, 0, 0, false );
            REQUIRE( veh );
            veh->unlock();
```
->
```
static const vproto_id vehicle_prototype_test_turret_rig( "test_turret_rig" );
...
     const tripoint_bub_ms veh_pos( 65, 65, 0 );
     ...
            vehicle *veh = here.add_vehicle( vehicle_prototype_test_turret_rig, veh_pos, 270_degrees, 0, 2, false, true );
            REQUIRE( veh );
```
Seems like a general improvement but I don't think the vehicle condition of 0 or the here.get_abs_sub().z() should be causing non 100% of the time problems and I couldn't repro it locally from testing just it so I imagine it's something more "sinister" from previous tests as you're suggesting, running the full suite locally to try to pin it down would take forever tho :c Is there any way to access the test save on a failed test run through CI artifacts?

**Comment by mqrause** [comment]
> I imagine it's something more "sinister" from previous tests as you're suggesting, running the full suite locally to try to pin it down would take forever tho

To be clear, I ran tests with `~[slow] ~[.],starting_items` as our CI does, which still takes a bit but far less than a full run. And I can't conclude anything about possible interference by another test.

**Comment by Procyonae** [comment]
Huh ye that didn't take as long to run as I remember, maybe I were having to run the slow tests last time
