### ISSUE TITLE
Arrows landing on locked display cases become locked inside them

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#78546]
### Describe the bug

Arrows landing on locked display cases become locked inside them

### Attach save file

N/A

### Steps to reproduce

1. Have a locked display case
2. Have a bow and an arrow
3. Fire the arrow with the bow to the locked display case
4. Try to 'g'rab the arrow - it's locked inside the display case

### Expected behavior

I expect the arrows to lie on top of the locked display case or around it, but not inside.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-12-09-0933 bb75c38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by Procyonae** [comment]
Don't worry you can just drag the display case to get your arrows back c; #78436 (related issue)

**Comment by dev-dsp** [comment]
🤯

**Comment by Night-Pryanik** [comment]
This is just another variation of #49312.
