### ISSUE TITLE
Inside of small lighthouse tower should be considered inside

### ISSUE THREAD

**Issue by ghiknt** [CleverRaven/Cataclysm-DDA#78553]
### Is your feature request related to a problem? Please describe.

While building a base in a small lighthouse I realized that the lighthouse tower is considered outside (rain starting falling on my bed).  Since the tower is fully enclosed with Stone Masonry Floors/Walls,  the top of the ladder is inside glass walls, and it is roofed I feel it should be considered inside space.

### Solution you would like.

Either change t_stone_masonry_floor to be an inside floor or replace the flooring of the lighthouse tower with one that is.

### Describe alternatives you have considered.

Remove some of the walls around the tower to create slits/openings to make it clear that it is exposed to the elements.

**Comment by WhaleYogurt** [comment]
I hope [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/78613) fixes that
