### ISSUE TITLE
Enable sleeping in the refugee center lobby

### ISSUE THREAD

**Issue by J4anis** [CleverRaven/Cataclysm-DDA#78571]
### Is your feature request related to a problem? Please describe.

If you try to sleep in the territory of the refugee center you will get the warning "You're in the territory of the Free Merchants, they probably won't appreciate your actions. Continue anyway?". I don't know how the ownership mechanic works, but i suggest an idea on how to solve this.

### Solution you would like.

I'm sure the refugee center wouldn't bother if you slept in the lobby, that's why this could be implemented.

The beggar faction could have their own territory in the lobby, that allows you to sleep there safely. However that new territory shares the other rules that the refugee center has. If the player then steals from the beggars, attacks them, angers them etc. the beggars would then attack or verbally stop the player if the relation is low enough. They would like the player to not cause them any trouble so they don't risk losing their refuge.

The lobby guards could be transferred to the beggar faction to make the consequences of causing trouble in the lobby more dangerous.

### Describe alternatives you have considered.

There is another open issue suggesting to enable sleeping in the parking lot (https://github.com/CleverRaven/Cataclysm-DDA/issues/78051) , which is a simpler solution than mine. If my suggestion is too hard to implement, sleeping on the parking lot would be the second-best solution.

**Comment by RenechCDDA** [comment]
Changing it would be a simple one-line change. Here's the problem:

It isn't really wanted.

I, mechanically, want to stop the player from sleeping in the refugee center. (Also any other occupied place, but the refugee center is by far the worst)

There are dozens of NPCs there. Sleeping at the refugee center will do nothing but worsen your experience by severely reducing the game's performance. There is a bit of conventional wisdom from game development that if you allow it, the players will optimize all the fun out of the game. It sounds silly, but it is extraordinarily true. If you were allowed to sleep in the center (despite there being no reason to!!) you would. And then you would waste many minutes or hours of your life just... watching the bar spin. That doesn't make the game any better. That makes the game worse. I don't want to make the game worse.



Now, let's talk about all the story reasons why you shouldn't be able to sleep there:

If you can get to the center then you can also walk to one of many many abandoned buildings or other shelters and sleep there. You can even sleep in the parking lot, the 'ownership zone' only applies while the camp in the central square is inside the reality bubble. This is akin to squatting, but they're not going to shoot you ingame or lore-wise to get you to stop sleeping inside the outer fence. So, again, why sleep in the center? It's just shooting yourself in the foot.

The beggars got there first. The VERY FIRST THING that smokes says to you is "We are full, you cannot stay here. End of discussion.". They were already overfilled to the point where the beggars relegated to the benches, and the *beggars* are already numerous and packing the lobby. There simply is not enough room for you.

There was a discussion on the development discord talking about how you might help them out a lot, by killing people (or zombies) for them, that sort of thing. And maybe they'd like you enough to give you a room. But the question again becomes: Why? Why of all the rewards would they want to give up some of their insufficient living space to let you stay there? And why would you want to do so? It just doesn't make any sense. Unless you've got a fetish for hot racking, the conditions in the refugee center are *objectively miserable*. People are only staying there cause it's the best choice they've got. You don't have that choice, and it would be far easier for you to find an empty building elsewhere. So why would you expend the most effort for the worst outcome? You just wouldn't.


> The beggar faction could have their own territory in the lobby

This is actually not possible without significant changes.

**Comment by J4anis** [comment]
When i play the scenario where i start in the center i usually slept 1-2 times there to prepare and train some skills. In rare cases i would sleep through a portal storm there for one night. After second thought, the usefulness of being to able to sleep there would be questionable. I agree with your explanation, enabling the player to sleep there might be more harmful than useful after all.
