### ISSUE TITLE
Pocket settings not visible

### ISSUE THREAD

**Issue by Retr0Cat** [CleverRaven/Cataclysm-DDA#78575]
### Describe the bug

Priority selection in the pocket settings shows up very dimly.

### Attach save file

[New Knoxville-trimmed.tar.gz](https://github.com/user-attachments/files/18137940/New.Knoxville-trimmed.tar.gz)

### Steps to reproduce

1. Open pocket settings for any item with pockets.
2. Select pocket priority on any pocket.

### Expected behavior

Menu should be on top of the UI.

### Screenshots

![cataclysm-tiles_NCKRwX2TBf](https://github.com/user-attachments/assets/eaf0a013-4fd3-4433-b714-2fa51831392f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: 1ecb260 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by RenechCDDA** [comment]
Already resolved by #77863. You're on an older version

**Comment by Brambor** [comment]
- Nitpick: This one was actually resolved by #78453.
