### ISSUE TITLE
Reproducible Seg Fault when turning on Heavy-Duty Flashlight

### ISSUE THREAD

**Issue by TRScheel** [CleverRaven/Cataclysm-DDA#78580]
### Describe the bug

I attached the flashlight to the car and turned it on. Immediately caused a seg fault. It is reproducible.

### Attach save file

[Twain Harte-trimmed.tar.gz](https://github.com/user-attachments/files/18138351/Twain.Harte-trimmed.tar.gz)

### Steps to reproduce

1. Load the attached save
2. Press `a` to use an item
3. Select the heavy-duty flashlight that is being wielded
4. Turn it on

### Expected behavior

It shouldn't seg fault

### Screenshots

![image](https://github.com/user-attachments/assets/b70118fe-4f89-4212-9a38-f999c82c3ea4)

![image](https://github.com/user-attachments/assets/b63333eb-978f-4752-b10d-bd1f0e2b6b6d)

![image](https://github.com/user-attachments/assets/aa736d5c-d82c-45f4-b3ca-a14c5ac09c51)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 2a8e243 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

[config.zip](https://github.com/user-attachments/files/18138371/config.zip)

**Comment by IdleSol** [comment]
Confirmed.
```
- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: 7acb286 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,7%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]
```

You need a flashlight **without a battery** to reproduce it. Plug it into the car (or a placed battery) and try to turn it on.

It might be important. If you remove the string:
https://github.com/CleverRaven/Cataclysm-DDA/blob/7acb286beeb4b07ee27ee0f45e9a9853dffa277f/data/json/items/tool/lighting.json#L648
Then turning on the flashlight does not cause a crash.

@TRScheel Alternative. Insert a battery into the flashlight, then it will turn on without error.

**Comment by marilynias** [comment]
hmm, the https://github.com/CleverRaven/Cataclysm-DDA/blob/32e2b3c33f14868930e1de2228c560110b6b1f1c/data/json/items/tool_armor.json#L3539
work the same way (with charges_per_use) and it doesn't crash. If im not missing anything, everything should be the same.
`0x5c0,360,682,c20    src/item.cpp:12,149    item::getlight_emit() const` 
seems like lighting requires battery charges.
