### ISSUE TITLE
Reduced item spawn from world setting also affect and reduced quest's items spawn, making completing quest impossible.

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#78585]
### Describe the bug

One of the quest from church retreat is "Get Gemma's 25 fertility supplements.". However, after getting to the quest location, I only found 11 pills. Since this fertility supplement is exclusively spawned through the quest, and there are no other sources to get it, you can't complete the quest.

### Attach save file

N/A.

### Steps to reproduce

1. Make world with reduced item spawn (Punish me more! difficulty).
2. Find a church retreat and Get quest from Gemma.
3. Go to the location and fetch the fertility supplement.
4. Realize you are scammed.

### Expected behavior

Spawned items should be enough to complete the quest.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: 651881e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

On a related issue. Other quests that involved fetching specific item suffer the same problem. I got like 5 weather log quests, and the 2 nearby radio station does only got 1 weather report. At least it still can found in other radio station, unlike exclusively spawned quest item.

**Comment by RenechCDDA** [comment]
Just needs the `MISSION_ITEM` flag.

**Comment by ZhilkinSerg** [comment]
> Just needs the `MISSION_ITEM` flag.

Should be probably automatically added in finalize step for all items that are mission targets.
