### ISSUE TITLE
Infrared is a bit broken right now.

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#78584]
### Describe the bug

The infrared goggles work, but textures are not showing up. On the other hand, the build-in infrared of the modular recon headgear does not work at all.

### Attach save file

[Palm Beach Shores-trimmed.tar.gz](https://github.com/user-attachments/files/18138798/Palm.Beach.Shores-trimmed.tar.gz)

### Steps to reproduce

1. Load save.
2. Test out both already equipped headgear.

### Expected behavior

Showing them nasty zombies in the dark.

### Screenshots
Infrared goggles:
![image](https://github.com/user-attachments/assets/b4ab8e27-611f-42ab-8385-aa3b3ab16304)
![image](https://github.com/user-attachments/assets/21a125b6-8a41-4e42-927f-f535e9ef4e36)

Modular recon headgear IR mode:
![image](https://github.com/user-attachments/assets/ac116bbe-53f8-4b01-93f2-210dbf46b569)
![image](https://github.com/user-attachments/assets/c19f174f-0a93-4153-9c43-d114757bd018)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: 651881e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Crazy Cataclysm [crazy_cataclysm],
    Martial Mastery [perk_melee_system],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by gettingusedto** [comment]
I think that's moreso in the tileset side of things, in which they need to modify the previous infrared sprite so it works with the new system.

**Comment by tranhuulong** [comment]
There is still the modular recon headgear's IR mode not working too. Probably an oversight, because normal light amp mode still work.

**Comment by IdleSol** [comment]
It's a tileset problem. A temporary solution, using the UltimateCataclysm tileset as an example:

/gfx/UltimateCataclysm/tile_config.json
```diff
        { "id": "infrared_creature", "fg": 13041 },
++        { "id": "infrared_creature_tiny", "fg": 13041 },
++        { "id": "infrared_creature_small", "fg": 13041 },
++        { "id": "infrared_creature_medium", "fg": 13041 },
++        { "id": "infrared_creature_large", "fg": 13041 },
++        { "id": "infrared_creature_huge", "fg": 13041 },
        {
```

But that doesn't apply to the HUB equipment. It just doesn't work. (If I remember correctly, you can't just add the `relic_data` of an IR variant. It is inherited in the transformation, so the empty `relic_data` from the main version is used)

The changes were made in: #77770

**Comment by GuardianDll** [comment]
see https://github.com/I-am-Erk/CDDA-Tilesets/pull/2588 for a proper way to change it tileset side

**Comment by IdleSol** [comment]
@GuardianDll What about the HUB helmet?

**Comment by GuardianDll** [comment]
hmm, odd, it already uses THERMAL_VISION_GOOD, not sure why it doesn't work
I'm surprised it was not hit with #78329 issue

**Comment by IdleSol** [comment]
>not sure why it doesn't work

>(If I remember correctly, you can't just add the `relic_data` of an IR variant. It is inherited in the transformation, so the empty relic_data from the main version is used)

**Comment by GuardianDll** [comment]
oh yeah there is some flickery with relic_data and inheritance, but i am not very familiar with it; one can try to replace THERMAL_VISION_GOOD with THERMAL_VISION_GOOD_PASSIVE, it works all the time, and doesn't require item being on, and it's okay since on revert item would be transformed into one without relic data

**Comment by IdleSol** [comment]
Something tells me it won't work either.
I haven't looked at the code. I can't read it at all. But when I was making my own armor, I experimented a little.

If we take an item and add a transformation to it. Then `relic_data` is inherited from the object that is created.

For example, consider the HUB 01 equipment.
- https://github.com/CleverRaven/Cataclysm-DDA/blob/1be27d733a706490c98284fe75f22309b8c75996/data/json/items/armor/robofac_armor.json#L273
- https://github.com/CleverRaven/Cataclysm-DDA/blob/1be27d733a706490c98284fe75f22309b8c75996/data/json/items/armor/robofac_armor.json#L362

The `relic_data` section is not defined for `robofac_head_rig`. And for `robofac_head_rig_ir`, it looks like this:
https://github.com/CleverRaven/Cataclysm-DDA/blob/1be27d733a706490c98284fe75f22309b8c75996/data/json/items/armor/robofac_armor.json#L368

What do we get? If we spawn `robofac_head_rig` and transform it to `robofac_head_rig_ir`. We get a `robofac_head_rig_ir` with an empty section. (I.e. the equipment will not work).

And if we spawn `robofac_head_rig_ir`, we will get `robofac_head_rig` with a section from IR version... We just need to activate the item (make IR - rig - NV - IR transformation). And here we will see an additional problem. There will be two effects for the NV version.

If you just replace one effect with another, it won't change anything. You need to define `relic_data` for `robofac_head_rig`. But the condition for triggering the effect is to make the subject `active` **AND** the subject is `robofac_head_rig_ir`.
