### ISSUE TITLE
conditions on enchantments applied to creatures silently fail with no message

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#78597]
### Describe the bug

Testing #78586 and the modifications to the slowing spells I applied did nothing. Further testing showed that enchants applied to monsters always evaluate conditions to `false`, even something that should always be true like `1 == 1` or `u_is_monster`

### Attach save file

N/A, requires modification (at the moment)

### Steps to reproduce

1) Put the following JSON in your game somewhere so it loads:

 {
    "type": "effect_type",
    "id": "effect_frozen_monster",
    "name": [ "Super Slow" ],
    "desc": [ "This monster is unbelievably slow!" ],
    "show_in_info": true,
    "enchantments": [
  {
        "condition": "u_is_monster",
        "values": [
          {
            "value": "SPEED",
            "add": -1000
          }
        ]
      }
   ]
  }

2) Using the debug menu, apply this effect to a monster
3) Monster's speed is not reduced.

### Expected behavior

Ideally, conditions work. In the meantime, an error message to appear.

### Screenshots

![Untitled2](https://github.com/user-attachments/assets/a8584c89-d10f-4d88-8f7a-9b01a41720dc)

![Untitled2](https://github.com/user-attachments/assets/4a83432b-c0b6-4c48-955e-4db277c97d0f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: 42c3aed [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

**Comment by GuardianDll** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/61f58dcb492523fa7cbd0264d1f0345bcd93fd74/src/magic_enchantment.cpp#L323-L324
