### ISSUE TITLE
various fences blocks fields from spreading

### ISSUE THREAD

**Issue by deltanedas** [CleverRaven/Cataclysm-DDA#78596]
### Describe the bug

chain link fences completely stop hot air from raging fires spreading, being regular temperature outside, then hot air 3 on the chain link fence tile

presumably you could make an oven out of this with a cross of chain link fences and a fire in the center

### Attach save file

just throw a molotov over a chain link fence, like in a military base
hot air will be trapped by the fence

### Steps to reproduce

1. find or spawn a chain link fence
2. light and throw a molotov over it
3. be completely safe from the fire

### Expected behavior

mostly air should have next to no insulation

### Screenshots

![02:46:25](https://github.com/user-attachments/assets/74d6dde5-09d1-4b74-9e57-18fe385c1824)

hot air 3 on the fence tile, nothing below it (on me) and i am at 17C

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.0; Distributor ID: VoidLinux; Description: Void Linux; Release: rolling; Codename: void; 
- Game Version: 91e1ec8fed-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

my build is a little outdated, could have been fixed recently

**Comment by WhaleYogurt** [comment]
Yeah just confirmed it. This one still works in both the old version you found it on and the latest sable. Looks like an issue with the JSON flags. I tried this with other terrain objects and it seems to be an issue with similar things like metal fences and the like. Consider changing the name of the issue to broaden it so that others know this issue is important

**Comment by deltanedas** [comment]
it may affect different fields like smoke and smell too so edited that as well

**Comment by WhaleYogurt** [comment]
Yeah but yeah distro works as intended for stuff like open screen doors but more testing should be done
