### ISSUE TITLE
Dynamic bomb craters.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#7860]
I've been thinking about how to make nice looking bomb craters like acidia's work in mapgen, and I think I have a good solution.
When we place a crater, instead of setting the affected tile to crater, we should:
load the affected and surrounding tiles in a map (as if the player had visited it), procedurally apply bomb effects, save the map, THEN mark the tiles as crater to make them visible on the overmap.
##

**Comment by Asmageddon** [comment]
What about a compromise between replace-tile-with-crater and simulation in form of a step after the main generation which just overlays rubble on top of stuff while randomly damaging items underneath?

**Comment by actual-nh** [comment]
Note #48137 - ideally, altered to allow for activating it before the player can potentially see it (unless I misunderstood the description in the PR). If something like this could set off a spell effect, it could also help out in Magiclysm - remnants of mages gone nutty (or, probably unsuccessfully, defending themselves against critters or other mages).

**Comment by I-am-Erk** [comment]
given that crater.json is now done procedurally I think this is just a matter of actually adding the JSON to mx_crater, which should be a very easy task. I will make this a blocker.

**Comment by Inglonias** [comment]
I'm confused as to what the expected result from this is. Is this issue just to JSONize the mx_crater extra?

**Comment by I-am-Erk** [comment]
Pretty much yes. The original issue was written long before that would have been possible, but we can resolve this issue by JSONizing the mx_crater extra and having it process like crater.json by just dropping a bunch of bombs on the map.
