### ISSUE TITLE
Bagpipes should be LOUD

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#78608]
### Is your feature request related to a problem? Please describe.

Found some bagpipes, & played 'em. Only a couple of zeds came 'round, at the outskirts of the city. These things are supposed to roll across the highlands.

### Solution you would like.

Increase the sound radius of bagpipes. If you're in a (mostly) quiet area, it should lay on a lot of dead ears.

**Comment by WhaleYogurt** [comment]
This what your looking for? https://github.com/WhaleYogurt/Cataclysm-DDA/blob/bagpipes-volume-change/data/json/items/tool/musical_instruments.json

**Comment by PGR-14** [comment]
Well, it's already being worked on then. It's completed, no? Just waiting for the merge, right?

**Comment by PGR-14** [comment]
Well, what's the scale? If 75 noise = 75 decibels, then it should be raised to 110 (from what I've read), put it equal to gasoline chainsaw maybe?

**Comment by WhaleYogurt** [comment]
I think the noise level has to do with how many tiles away the noise is heard so maybe you can try using that as a reference

**Comment by PGR-14** [comment]
Looking at the chainsaw, which is ~110 decibels, it only has a range of 12 tiles? If 1 tile = 1 meter, then that's ~40ft. That's reasonable, but the bagpipes have a bit of an echo effect. Looking at some forums here, it can reach quite a while [forums.bobdunsire.com](https://forums.bobdunsire.com/forum/general-discussion/beer-tent/74530-/page2) one person says (In a busy town, unlike ours) ~6 blocks, others say miles.

Side question, do some tiles block sound more than others? I'm pretty sure walls do, but I'm not sure if the game sees any difference between water & wood floors.

**Comment by WhaleYogurt** [comment]
First off that's weird that the chainsaw is so quiet and second I'm pretty sure that walls and stuff block and reflect sound but that's just my own guess from personal experience. I think that 50-75 should be plenty high enough to get your desired gameplay results so if your fine with it Ill probably just merge the fork and then you can close the issue

**Comment by PGR-14** [comment]
Alright, also side thing on the chainsaw, both the reg. & elect. ver. have the same noise.

**Comment by PGR-14** [comment]
Oops, didn't mean to do that.

**Comment by WhaleYogurt** [comment]
Just merged. Hope the changes help

**Comment by PGR-14** [comment]
Thanks man

**Comment by Night-Pryanik** [comment]
Closed by #78627.
