### ISSUE TITLE
bee fields can't merge.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#7862]
i added bee fields as a source of danger for the granade item to balance the unintended stat-roulette effect it had, but I don't want to include them anywhere 'serious' in the game because there was a technical issue I couldn't solve.
I couldn't figure out how to get bee fields to merge without having them move at different speeds based on which direction they were moving.
specifically, if a field merges with a field south and or east of it, the field it merges into will be processed again, and move in the same direction, but if the field moves north or west this doesn't happen.
##

**Comment by Leland** [comment]
@kevingranade this is one of the oldest issues on the repo - you want to keep it open?

**Comment by kevingranade** [comment]
Considering it's a still-present bug (about bugs), yes.

**Comment by kevingranade** [comment]
Removing in #64679
