### ISSUE TITLE
Tileset options > Use Tiles = 'False' Results in Lock-up

### ISSUE THREAD

**Issue by Meadevil** [CleverRaven/Cataclysm-DDA#78667]
### Describe the bug

This has been happening ever since Cataclysm-DDA experimental build 2024-12-17-0625.
Changing Tilest options > Use tiles: from 'True' to 'False' issues an error and also causes the game to freeze/lock-up when trying to load a world/overmap. If the setting is changed back to using tiles it works fine.

### Attach save file

N/A - this occurs with fresh install new game/new world

### Steps to reproduce

1) Fresh install (Build 12-19-2246)
 2) Start Cataclysm-Tiles.exe
 3) Settings > Options > Graphics > Tileset options > Use Tiles = 'False' and Save Changes [Y]
 
 Results:
 
 DEBUG    : Layering data: f_flagpole not a valid furniture/terrain object

 FUNCTION : load_layers
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\cata_tiles.cpp
 LINE     : 890
 VERSION  : 47fa616

Press [I] to ignore
 
4) New Game > Play Now (Default Scenario)
   Title Image & Loading/Finalizing/Verifying

 Results: Game Locks to a black screen (Waited for several minuets) - Must force close the non responding application 
 
 "Cataclysm: Dark Days Ahead - 47fa616" of cataclysm-tiles.exe is not responding. Do you want to terminate this application?""

 This has been happening ever since Cataclysm-DDA experimental build 2024-12-17-0625.

### Expected behavior

Expectation: Changing the Use Tiling option from 'true' to 'false' to work properly as it has in the past allowing you to toggle between Tiles and Ascii gameplay.

### Screenshots

![Screenshot_20241220_092430](https://github.com/user-attachments/assets/9d28a60f-231c-4f60-aece-5e0f59f1b2bc)

### Versions and configuration

OS: Win10
Game Version: 47fa616
Graphics Version: Tiles
Ingame Language: English (Default)

### Additional context

[config.zip](https://github.com/user-attachments/files/18204413/config.zip)

**Comment by PatrikLundell** [comment]
This looks like it's a duplicate of #78669, which was fixed by #78674, which was merged 8 hours ago (as of this writing).

**Comment by Meadevil** [comment]
Indeed, when I loaded the latest build it looks to be resolved.  I shall close the PR.
