### ISSUE TITLE
Ошибка при запуске игры

### ISSUE THREAD

**Issue by MikuFun1** [CleverRaven/Cataclysm-DDA#78690]
### Describe the bug

Когда запускаю игру то сразу же появляются ошибки.

### Attach save file

N\A

### Steps to reproduce

Запустить игру

### Expected behavior

Я ожидал что появится главное меню игры, но вместо этого куча ошибок, хотя их можно пропустить и на игру вроде бы они не влияют.

### Versions and configuration

Windows 11 
Версия: 0.E-10291-g5b3c6ce
Графика: Tile
Язык: Русский
Модов нету

### Additional context

[debug.log](https://github.com/user-attachments/files/18217615/debug.log)

**Comment by RenechCDDA** [comment]
Your reported version is 0.E, released sometime in 2020 or perhaps earlier.

That is three major versions ago. Support can no longer be provided for that release.

Please open a new issue if you encounter this on 0.H or newer.
