### ISSUE TITLE
So cold in No Hope

### ISSUE THREAD

**Issue by Cupidatis** [CleverRaven/Cataclysm-DDA#78719]
### Describe the bug

Go outside and you have -~1000  temperature

### Attach save file

[Троски-trimmed.tar.gz](https://github.com/user-attachments/files/18221231/-trimmed.tar.gz)

### Steps to reproduce

1. Start new game with no hope

### Expected behavior

Normal temperature.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: M2101K7BNY; Release: 13; Incremental: V14.0.4.0.TKLRUXM; 
- Game Version: cdda-experimental-2024-12-22-0410 248e058 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91.7%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Надежды нет [no_hope]
]

**Comment by Night-Pryanik** [comment]
I guess the reason is the same as in #78678.

**Comment by Cupidatis** [comment]
Maybe, but freesing in few seconds is much worse then juat bad weather @Night-Pryanik
