### ISSUE TITLE
Map Editor unable to scroll through terrain and furniture lists

### ISSUE THREAD

**Issue by QuillInkwell** [CleverRaven/Cataclysm-DDA#78725]
### Describe the bug

When opening the place terrain or furniture windows I am finding I am unable to scroll the windows. The mouse functionality does not appear to be working properly and I cannot scroll using the mousewheel on click on any options with the mouse. Which would be minor but I also can't really seem to scroll options using the arrow keys either. Instead the windows keeping jumping to different scroll points. I thought it might be the mouse and keyboard fighting for input but moving the mouse away from the window doesn't seem to solve it. If you reduce the total entries in the list by searching for a specific terrain, the arrow keys start working again. Although there is still no mouse support. (Which I think was implemented recently?

### Attach save file

N/A

### Steps to reproduce

Load a world
Open the Map Editor
Open the terrain or furniture editor
Attempt to use the arrow keys to navigate or move the mouse around the window
Observe that the window becomes neigh unusable as it begins jumping around the scroll area.

### Expected behavior

Using the arrow keys should scroll the terrain and furniture lists. And the window should not be constantly jumping to other points in the scroll selection.

### Screenshots

![GIF 12-22-2024 9-28-50 AM](https://github.com/user-attachments/assets/af6fd39e-5bea-4aa3-b8ed-d508c98209dc)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4602 (23H2)
- Game Version: 25aabc1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

**Comment by CoroNaut** [comment]
Similar issue #76215, don't know if its a duplicate

**Comment by QuillInkwell** [comment]
That does actually seem to be the same bug as what I am experiencing, I will go ahead and close this issue out. Sorry about that!
