### ISSUE TITLE
Effects from equipment are spammed

### ISSUE THREAD

**Issue by thaelina** [CleverRaven/Cataclysm-DDA#78735]
### Describe the bug

When wearing an _active_ [RM13 Combat Armor](https://cdda-guide.nornagon.net/item/rm13_armor_on) or [phase immersion suit (on)](https://cdda-guide.nornagon.net/item/phase_immersion_suit_on), the effects they apply get spammed constantly. 

### Attach save file

[Bug-trimmed.tar.gz](https://github.com/user-attachments/files/18224759/Bug-trimmed.tar.gz)

### Steps to reproduce

Spawn either piece of equipment
Equip then activate the equipment
Pass time then check `@`

### Expected behavior

Only a single effect should be applied to the player

### Screenshots

![image](https://github.com/user-attachments/assets/bafc8ec3-7120-4c82-95b1-e7d99f75c38e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 53cbd1e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This is definitely related to this commit 53cbd1e752ddc5aa4733b209155bb6fd0ec36c77
I checked by going to the previous commit and the problem does not exist

Saving and reloading the game will reset the effects applied to what it should be until time passes again

**Comment by MorphingE** [comment]
Can confirm that this occurs for Magic Armor and Magic Blade from Magiclysm, as well. Both items with effects.
![image](https://github.com/user-attachments/assets/0039994e-1099-49c0-ba6b-076b8449d1ba)

**Comment by osuphobia** [comment]
Oops, will check it later.

**Comment by osuphobia** [comment]
```diff
diff --git a/src/magic_enchantment.cpp b/src/magic_enchantment.cpp
index 46f1bd6a39..6560c89fde 100644
--- a/src/magic_enchantment.cpp
+++ b/src/magic_enchantment.cpp
@@ -1472,6 +1472,7 @@ void enchant_cache::clear()
     ench_effects.clear();
     mutations.clear();
     modified_bodyparts.clear();
+    details.clear();
 }
```
This should solve it.
I realy should not have replaced the `inv` stuff with `clear` function, it's like we had this code worked relying on _bugs_ 😵‍💫
