### ISSUE TITLE
Integrated armor provided by mutations remain even after the associated mutation disapears

### ISSUE THREAD

**Issue by Satellite-SLickers** [CleverRaven/Cataclysm-DDA#78761]
### Describe the bug

mutations that grant integrated armour do not remove said armor when they are removed, whether that is by upgrading to a higher level mutation, or vanishing via purifier

### Attach save file

[Saint Catherine-trimmed.tar.gz](https://github.com/user-attachments/files/18245136/Saint.Catherine-trimmed.tar.gz)

### Steps to reproduce

1. Create a default character in the default scenario in a default world
2. Via debug, grant your character any mutation that grants some form of integrated armor (i used Gnarled Claws in my testing)
3. Remove the mutation granting integrated armor,
4. the integrated armor should still be equipped to your character

### Expected behavior

removing a mutation should remove whatever effects it was granting a character, 

### Screenshots

screenshot showing multiple copies of both Claws, and its upgraded form Gnarled Claws
![image](https://github.com/user-attachments/assets/cdbfc1fc-7df6-4074-a982-c368056864d3)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.3; Release: 21.3; Codename: virginia; 
- Game Version: cdda-experimental-2024-12-25-0459 3f09bef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by osuphobia** [comment]
Ok it's my fault, let me see how to fix it😥

**Comment by osuphobia** [comment]
![2024-12-25 193625](https://github.com/user-attachments/assets/72de1048-9cb0-4113-ab47-852461a2bc4e)
Toggled the Gnarled Claws, seems good now.
