### ISSUE TITLE
Buying a map from Hub-01 pays you one coin instead of costing you one coin

### ISSUE THREAD

**Issue by Coyote-Bongwater** [CleverRaven/Cataclysm-DDA#78768]
### Describe the bug

Upon completing the quest 'Return to Sender' for Hub-01, you receive an option to purchase a map of the local area for 1 HGC.  If you select this option, you receive both the map and a Hub gold coin.

### Attach save file

N/A

### Steps to reproduce

1. Complete the quest 'Return to Sender' for Hub-01.
2. When speaking to the intercom, select the dialogue option to purchase a map of the surrounding area.
3. Note that you now have one more gold coin in your inventory than you previously did.

### Expected behavior

Purchasing the map should cost the amount of money the dialogue indicates it will.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5247 (22H2)
- Game Version: 78fd6e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by oosyrag** [comment]
Already fixed #77471
