### ISSUE TITLE
No longer possible to Alt-F4 out of tombstone screen

### ISSUE THREAD

**Issue by dead-letter-office** [CleverRaven/Cataclysm-DDA#78776]
### Describe the bug

When the player dies, a tombstone screen is shown with a text box for the player's last words. This popup is stopping Alt-F4 from closing the window. It's also impossible to close the window by clicking the title bar close button. The only way to close the game from this screen is to kill its process using the task manager.

### Attach save file

N/A

### Steps to reproduce

1. On Windows, start a new game.
2. Die.
3. Press Alt-F4.
4. Click the title bar close button.
5. The game remains running.

### Expected behavior

Pressing Alt-F4 or clicking the title bar close icon should exit the game.

### Versions and configuration

- OS: Windows

**Comment by RenechCDDA** [comment]
[We do not support savescumming.](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#fixing-savescumming-in-either-direction-no)

**Comment by dead-letter-office** [comment]
> [We do not support savescumming.](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/FREQUENTLY_MADE_SUGGESTIONS.md#fixing-savescumming-in-either-direction-no)

No, but there's no position on save scumming in either direction. This change is a change that prevents it, and an app refusing to close on Alt-F4 is clearly a bug.

**Comment by kasanryukin** [comment]
> No, but there's no position on save scumming in either direction. This change is a change that prevents it, and an app refusing to close on Alt-F4 is clearly a bug.

No, it's by design. Alt-F4 just sends a signal to the program requesting it to terminate. If the program doesn't want that feature to work, they don't add a handler. In the case of CDDA, it responds by sending a QUIT? query. Since you can't quit from the tombstone screen, ALT-F4 does nothing. That's by design because we do not support savescumming.  It is literally 5 key presses to get back to the main menu where you can quit normally.

**Comment by dead-letter-office** [comment]
> > No, but there's no position on save scumming in either direction. This change is a change that prevents it, and an app refusing to close on Alt-F4 is clearly a bug.
> 
> No, it's by design. Alt-F4 just sends a signal to the program requesting it to terminate. If the program doesn't want that feature to work, they don't add a handler. In the case of CDDA, it responds by sending a QUIT? query. Since you can't quit from the tombstone screen, ALT-F4 does nothing. That's by design because we do not support savescumming. It is literally 5 key presses to get back to the main menu where you can quit normally.

The answer in the FAQ is
`‘Fixing’ savescumming (in either direction): no.`

This is a fix in one direction by trying to prevent it. Unless it really is a bug?

**Comment by Alphyn-gunner** [comment]
Wo are "we" exactly? People should be free to play the game however they like. 
CDDA is not a traditional roguelike. It lacks a winning condition. It's just an open-ended sandbox game at this point. 
Maybe it's time to implement a more comprehensive game system.

**Comment by RenechCDDA** [comment]
> This is a fix in one direction by trying to prevent it. Unless it really is a bug?

It is not "trying to prevent it". Things may change which make it more difficult for you to savescum. We are not supporting savescumming, and that means we're not going out of our way to preserve your favorite way to do it, either. The PRs responsible for this change had absolutely nothing to do with savescumming.

> Wo are "we" exactly? People should be free to play the game however they like.

As stated repeatedly: Nothing prevents you from savescumming, and nothing will be done to help you savescum, either. If you don't like that... go play something else, I guess. It will not be changing. I guarantee it.

**Comment by dead-letter-office** [comment]
> > This is a fix in one direction by trying to prevent it. Unless it really is a bug?
> 
> It is not "trying to prevent it". Things may change which make it more difficult for you to savescum. We are not supporting savescumming, and that means we're not going out of our way to preserve your favorite way to do it, either. The PRs responsible for this change had absolutely nothing to do with savescumming.
> 
> > Wo are "we" exactly? People should be free to play the game however they like.
> 
> As stated repeatedly: Nothing prevents you from savescumming, and nothing will be done to help you savescum, either. If you don't like that... go play something else, I guess. It will not be changing. I guarantee it.

If the change was unintentional, then surely it's an unintentional change aka a bug?

**Comment by RenechCDDA** [comment]
It was an intentional change, and it had nothing to do with savescumming. To quote myself:

> Things may change which make it more difficult for you to savescum. We are not supporting savescumming, and that means we're not going out of our way to preserve your favorite way to do it, either. The PRs responsible for this change had absolutely nothing to do with savescumming.

**Comment by dead-letter-office** [comment]
I didn't actually bring it up in the context of savescumming, but because an application silently refusing a user request to close (either using Alt-F4 or with the close button) is so surprising and so unique I assumed it was and still see it as a bug.

**Comment by RenechCDDA** [comment]
Oh okay, no wonder so many random responses showed up so quickly.

The FMS entry is our stance and it's been there for a while. Hasn't changed, isn't changing, and absolutely nothing you can say is new. Believe me, in the 10+ years of development, everything you want to say has already been said, and what you see in the FMS was the winning argument.

Calling reddit to come waste my time does not earn you any brownie points. I am locking this, because further discussion is pointless.
