### ISSUE TITLE
Follower NPC's will wield integrated armour

### ISSUE THREAD

**Issue by Satellite-SLickers** [CleverRaven/Cataclysm-DDA#78780]
### Describe the bug

if a follower npc has integrated armour with combat stats, they will wield it as a weapon, breaking a lot of things in the process

### Attach save file

[Dandridge-trimmed.tar.gz](https://github.com/user-attachments/files/18256156/Dandridge-trimmed.tar.gz)

### Steps to reproduce

1) Make a player in a scenario that starts them with an NPC
2) Use the debug menu to grant the NPC a mutation that gives an integrated weapon armour (i used Fangs in my test)
3) Ask them to be your follower, increase their opinion values via debug so theyll accept if needed
4) Remove all of their weapons
5) Wait 5 minutes
6) they should now be wielding their integrated armour in their hands

### Expected behavior

I expected them to be unable to wield their integrated armor, and to keep it worn at all times. as the player is unable to do the same. and wielded integrated armor can be dropped/thrown/traded 

### Screenshots

![image](https://github.com/user-attachments/assets/4d1fbb1e-3ad0-42af-9d3c-275f528cee2e)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.3; Release: 21.3; Codename: virginia; 
- Game Version: cdda-experimental-2024-12-26-2300 1e44b42 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by osuphobia** [comment]
```diff
--- a/src/character.cpp
+++ b/src/character.cpp
@@ -7878,6 +7878,9 @@ void Character::did_hit( Creature &target )

 ret_val<void> Character::can_wield( const item &it ) const
 {
+    if( it.has_flag( flag_INTEGRATED ) ) {
+        return ret_val<void>::make_failure( _( "You can't wield a part of your body." ) );
+    }
     if( has_effect( effect_incorporeal ) ) {
         return ret_val<void>::make_failure( _( "You can't wield anything while incorporeal." ) );
     }
diff --git a/src/npc.cpp b/src/npc.cpp
index bd5c83598d..5eb74221c6 100644
--- a/src/npc.cpp
+++ b/src/npc.cpp
@@ -1514,6 +1514,10 @@ bool npc::wield( item &it )
         return true;
     }

+    if( !can_wield( it ).success() ) {
+        return false;
+    }
+
     item to_wield;
     if( has_item( it ) ) {
         to_wield = remove_item( it );
diff --git a/src/npc_attack.cpp b/src/npc_attack.cpp
index da87d0a854..111cd1c21f 100644
--- a/src/npc_attack.cpp
+++ b/src/npc_attack.cpp
@@ -231,7 +231,7 @@ npc_attack_rating npc_attack_spell::evaluate_tripoint(

 void npc_attack_melee::use( npc &source, const tripoint_bub_ms &location ) const
 {
-    if( !source.is_wielding( weapon ) ) {
+    if( !source.is_wielding( weapon ) && source.can_wield( weapon ).success() ) {
         if( !source.wield( weapon ) ) {
             debugmsg( "ERROR: npc tried to equip a weapon it couldn't wield" );
         }
```
This should work.
