### ISSUE TITLE
[Xedra] Unable to use questionable blood treatment

### ISSUE THREAD

**Issue by Sohex** [CleverRaven/Cataclysm-DDA#78823]
### Describe the bug

I'm unable to take the questionable blood treatment to treat vampirism. When trying to take the treatment this error appears:
 DEBUG    : Comestibles are not properly consumed via effect_on_conditions and effect_on_conditions should not be used on items of type comestible until/unless this is resolved.

 FUNCTION : use
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\iuse_actor.cpp
 LINE     : 5704
 VERSION  : 00ded91

### Attach save file

[Rome-trimmed.tar.gz](https://github.com/user-attachments/files/18267823/Rome-trimmed.tar.gz)

### Steps to reproduce

1. Get vamp'd (i.e. be bitten by a moroi/strigoi and contract vampirism)
2. Get a 'questionable blood treatment'
3. Try to take the treatment either by (a)ctivating it or (E)ating it.
4. Get the above error about EOCs on comestibles.

### Expected behavior

The treatment should be taken and reverse the onset of vampirism.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5247 (22H2)
- Game Version: 00ded91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Translate Complex Dialogue [translate_dialogue],
    Sky Island [skyisland],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
Should be fixed by #78805

**Comment by Sohex** [comment]
Right on, thank you!
