### ISSUE TITLE
NPCs do not respect item blacklists

### ISSUE THREAD

**Issue by Izicata** [CleverRaven/Cataclysm-DDA#7940]
If you're using the controversial items mod, they're still able to spawn with katanas, for example. I've also had one spawn with active flashbangs.
##

**Comment by BevapDin** [comment]
I'm pretty sure this was fixed by ec41db6d5e9572a76db82c6ab47638ca0533520d (removed katana from hard coded list of possible initial npc weapons). If it appears again, reopen this or make a new issue.
