### ISSUE TITLE
Allow turrets to have arbitrary guns attached.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#8082]
It should be fairly simple to let the player install an arbitrary gun in a turret instead of having separate definitions and recipes for each variety.  We might still want to have different levels of accuracy though,
##

**Comment by mugling** [comment]
We aren't that far of this as of the new gun, reloading and gunmod refactors

**Comment by merrygin** [comment]
There are still separate definitions&recipes for different guns that can be installed on a turret. 
![turrets](https://user-images.githubusercontent.com/64795375/180641986-05d19ac5-7283-41a1-9588-be6f82ec0be7.PNG)
