### ISSUE TITLE
Crash when attempting to burn down a black widow infested house

### ISSUE THREAD

**Issue by GroeneAppel** [CleverRaven/Cataclysm-DDA#8099]
As the title says. The game crashes when you light a house infested by black widows on fire. It seems to occur a few turns after the fire started. 
It occasionly displays an error window:

![ss 2014-06-30 at 05 56 16](https://cloud.githubusercontent.com/assets/8028344/3432016/152f106e-0070-11e4-81be-ea11f9d19e09.png)

Version: 5245ae1 (SDL)
OS: W7 64bit SP1

If any usseful, i've zipped the savegame and uploaded it here:
https://dl.dropboxusercontent.com/u/62200674/save.zip

**Comment by mugling** [comment]
This is approaching two years old and has not been subsequently reported. @stk2008 please re-open if you can reproduce in any recent version of `master`
