### ISSUE TITLE
Using pipe to smoke weed has no effect.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#8142]
Windows-curses build 1741

It consumes a unit of cannabis and says 'you smoke some weed' but it has no morale effect.

**Comment by Rivet-the-Zombie** [comment]
[This is still being reported as broken.](http://smf.cataclysmdda.com/index.php?topic=10016.msg229467#msg229467)

**Comment by DavidKeaton** [comment]
Things to fix:
- Blunts as big as soda cans
- pipage working to smokage and tokage
- bongs

**Comment by BevapDin** [comment]
There is a `ise::smokin_pipe` (0e2da9088e4547c56699f3ee6b4ed202f3bf4ee7) which seems to do what is required here, but it is only used when activating a crackpipe, tobacco pipe, and glass pipe, and it does not give morale bonus and its effects are hard coded and only work for cannabis and tobacco. That might be a point to start from.

That PR also removed the check for `apparatus` (which can be different smoking devices, see `player::amount_of` and should probably be a flog or a quality).

**Comment by Night-Pryanik** [comment]
Should be closed after #13477?

**Comment by illi-kun** [comment]
Yes, it can be closed safely. I don't remember exactly why I didn't request closing of this issue, that's probably because I wanted to simplify smoking code more, but that's unrelated to current issue anyway.

**Comment by illi-kun** [comment]
Usage of smoking pipes was broken about 20 days ago but this incident is not related with the current issue (which was fixed in #13477, as stated above).

I'll create a new bug report about the actual issue with apparatus (pseudo item).
