### ISSUE TITLE
Found a monomolecular blade on an npc, picked it up, unable to drop or unequip.

### ISSUE THREAD

**Issue by cosmodiusrex** [CleverRaven/Cataclysm-DDA#8171]
I killed an npc and found a monomolecular blade on his corpse. I picked it up figuring it was a regular sword but it was a cbm weapon. I was unable to unequip or drop it thereafter, and was unable to pick up additional items while holding it.

**Comment by Night-Pryanik** [comment]
Should be closed after #11385?
