### ISSUE TITLE
Vehicle repairs require silly components

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#8194]
Hey all I would like to make a suggestion about vehicles.
As it stands now to fit a wheel to a car you can do this with duct tape I mean come on really?.

I would opt for a more realistic component requirement.

So lets say to fit a wheel to a car

wrench
jack
replacement wheel

repair frame

wrench
welder
scrap metals

repair glass

duct tape
or a replacement screen

repair light

duct tape
wire
solder etc etc

repair alternator

duct tape
solder

I just cant grasp the idea how one can fix a frame of a car with duct tape nor fit a wheel with the stuff?.

I would be willing to write a really detailed list but no point if its not or cant be changed.

Thanks

EDIT

as for the boats that have been added I think duct tape and super glue for the inflatable boat would be ideal even if we can add some thing made of rubber sheet to stick over the top of the broken parts of the boat :)
##

**Comment by illi-kun** [comment]
We need to update / revise this issue since @mugling modify the related code.

**Comment by mugling** [comment]
> We need to update / revise this issue since @mugling modify the related code.

Yes, you can specify `install_requirements` and `repair_requirements`
