### ISSUE TITLE
volume adjustment

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#8215]
I want to redefine volume and how it is interpreted. 
By default human character is for example capable of carrying... 2 strawberries?!
My goal is to redefine Volume to be more precise ( like weight ) and be around 1K times scaled. For every item there could be defined better volume ranges. Also Json files need to be modified accordingly.

What do you think about it?

**Comment by nornagon** [comment]
This can probably be closed now that #16330 has landed :)
