### ISSUE TITLE
explosion damage is sooo wrong...

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#8217]
i think its simple - zombies can, but shouldn't survive some kinds of explosions - C4, grenades, grenade launchers and things like that. As far as i tested, most regular zeds can survive direct hit with grande launcher.
Moreover there should be something like flag or status indicator - "on fire" (if possible, for items and objects too) without it, using Molotov and fire-throwers is just week . Of course it should be balanced, like spray can fire-thrower shouldn't be able to burn neighborhood...

**Comment by mugling** [comment]
Known problem covered in a lot of other issues
