### ISSUE TITLE
(more) monster/player standardization

### ISSUE THREAD

**Issue by swwu** [CleverRaven/Cataclysm-DDA#8230]
Going to be going through the code and
* (finishing) porting all the diseases to use the creature effects framework rather than the player-specific disease framework
* (finishing) standardizing the use of `Creature::apply_damage` and `Creature::deal_damage` vs `Creature::hurt` in sources of non-combat damage.
* phasing out the use of diseases/`Creature::hurt` (except for shoes' temperature stuff, which AFAICT is bodypart-dependent and has to go in `player` or at least `Character`)

Feedback welcome.

**Comment by illi-kun** [comment]
This describes the general direction of code changes, and everybody knows that this direction is correct and desired. I see no reason for keeping this issue open - it describes the obvious thing.
Any comments / other opinions, anyone?

**Comment by Night-Pryanik** [comment]
Should be closed.
