### ISSUE TITLE
[z-level Mod] office tower generating badly

### ISSUE THREAD

**Issue by ranger22550** [CleverRaven/Cataclysm-DDA#8237]
like showers in solid rock behind the wall in the basement with the wall already missing in some parts
![capture](https://cloud.githubusercontent.com/assets/8114711/3574746/3b101b68-0b81-11e4-809c-a9c5813cdbbf.PNG)

sinks by the doors parking garage door console ![capture2](https://cloud.githubusercontent.com/assets/8114711/3574783/ba156652-0b81-11e4-8a6a-0ca15fd58560.PNG)

empty vending machines were lockers were on first floor normal towers 

Normal towers![capture3](https://cloud.githubusercontent.com/assets/8114711/3574846/804123d4-0b82-11e4-9ed9-8213db233aa0.PNG)
large towers![capture4](https://cloud.githubusercontent.com/assets/8114711/3574884/d05d3e34-0b82-11e4-9360-d1c19a921f9e.PNG)

apologize in advance if this is already known or the wrong place for it
but as pictured above the towers are generating with showers in the walls sinks beside the console and vending machines replacing all lockers on the other floors and they are all empty, actually the whole building is empty except for furniture theirs not loot no chairs
##

**Comment by Leland** [comment]
Closed by #8252
