### ISSUE TITLE
Somehow NPCs cloning items

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#8306]
Story goes: I was playing a tweaker and ran into the woods, began collapsing from withdrawal. While I'm at the 25 speed nadir, there's a commotion nearby. I check it out and theres a bunch of bloodsmears, wolf corpses, and combat knives. Like, seven combat knives, certainly more than you would expect an NPC to have. So, I suspect that somehow having combat while the player had no turns, possibly getting the knives pulled away, caused the item to duplicate. It's also possible they found a pile of junkies with several knives, collected them, and lost them normally, but no such pile was found. 

This is in 9062d15, but I don't see it mentioned in ensuing bug reports.

**Comment by mugling** [comment]
closed as unlikely to be reproducible
