### ISSUE TITLE
Alarm Function doesn't work as advertised.

### ISSUE THREAD

**Issue by erendor** [CleverRaven/Cataclysm-DDA#8330]
As title, the alarm function for clocks/watches/PDA/etc doesn't seem to work like it should - setting an alarm for 8 hours, for example, at 12am midnight, will cause the alarm to go off at 5am.

This is in version 1d2f15a or 0.A-1813, but it's been around for a while now.
##

**Comment by Dracace** [comment]
> Has it been fixed? I was unable to reproduce this.

+1

**Comment by AlecWhite** [comment]
I couldn't reproduce it with 0.C-22337-g54e8448fc8.

**Comment by Dracace** [comment]
v 6426

The alarm is working fine

**Comment by Leland** [comment]
Closing due to lack of confirmation. If any _can_ confirm this behavior, feel free to ping me here to reopen... or just create a new issue 😁
