### ISSUE TITLE
Worldgen with citysize 10+ results in really blocky forests

### ISSUE THREAD

**Issue by CErratum** [CleverRaven/Cataclysm-DDA#8342]
I've been experimenting with generating worlds with high citysize settings, and they all seem to have very long stretches of forest where one, or several sides are perfectly straight lines along overmap 'chunk' boundaries. This might be a bug in the worldgen. 
##

**Comment by kevingranade** [comment]
This is expected, if not desireable, behavor due to the way overmap chunks are generated independently.  This would require a rewrite of overmap generation to correct, and isn't serious enough to drive such a change.
