### ISSUE TITLE
Chaining explosives

### ISSUE THREAD

**Issue by Lap** [CleverRaven/Cataclysm-DDA#8428]
Explosives currently don't seem to set off most other explosives. While I can understand certain situations where blast force wouldn't set off another explosive I definitely think players expect explosions to chain.

Dropping a lit dynamite or c-4 pack onto a pile of similar explosives doesn't cause any of these explosives to detonate.Considering that we have the ability for ammo to "cookoff" and explode, as well as certain things to "explode_in_fire," it only makes sense that explosions should be able to set off most other explosives.

It would also be logical for explosives on the same tile to add to (or even multiply) the explosive power. So instead of having a truck full of dynamite simply give off a dynamite explosion 25 times it would give off a single explosion of much larger size. Enough conventional explosions can do the damage of a mininuke if you have enough.
##

**Comment by Xpyder** [comment]
Regarding detonating explosives there's 2 traits to consider (aside from explosive yield)

The Triggering method fis usually one or more of the following and depends on the type of explosive:
Heat (fire/spark)
Blast (detcap/primer)
Electricity

And the context in which it explodes, vs other types of discharge (mainly burning).  The context usually boils down to containment and pressure.  Some examples:
  - Diesel detonates if under pressure, but can detonate from the pressure (and heat generated by the pressure) without a separate ignition source.  In open air it just burns.
  - Gasoline only explodes if it's a gas, in a closed chamber, and is within the correct range of oxygen.  As a liquid in open air it just burns, and as a liquid in closed space it suffocates and goes out.
  - C4 detonates when exposed to electrical charge, even in open air.  It also detonates from a sufficiently strong blasting cap.  But it won't detonate from being burned or shot, or from a weak primer like those used in bullets

If we look to expand this later, ideally there would be a section where we can say which combinations are valid for triggering a detonation with heat and blast having low (fire/gunshot), high (another explosion), and extreme (specialized blasting cap) requirements

**Comment by Xpyder** [comment]
Also sorry for necroing this, I didn't see this was closed before I posted my comment

**Comment by Night-Pryanik** [comment]
Discussion is stalled for years, so closing for now.
