### ISSUE TITLE
Move special attacks to weighted targeting map.

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#8438]
With the (not so) recent changes to melee attacks to use a weighted map for choosing the body part that is being hit, I have noticed that special attacks, mainly bite from zeds, are still using the old random, 'bite all the things' , method of choosing a body part. A big reason for moving to the weighted map was because after a certain amount of melee skill, EVERYTHING was hitting the head.  I would like to propose that we centralize the body part targeting and then use it for all attacks, melee, special and ranged. Adding the ability to affect the weights (aiming when implemented, dodge, skill, etc) should be fairly simple.

Attacks like bite also do not take into account the target's melee abilities like block.
##

**Comment by Leland** [comment]
Looks like discussion's stalled on this suggestion, closing. Feel free to let me know if you want it reopened; or just create a new issue.
