### ISSUE TITLE
Wearable items can not be wear with power armor

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#8473]
Something like watches, biomonitor,  wearable flashes etc, if you are wearing a power armor, you can't wear these things, but if you wear these things first, you can wear a power armor then.
##

**Comment by Griffinhart** [comment]
While it makes no sense to wear a watch *inside* the power armor, it should be fine to wear a watch *outside* it, no?

I've also noticed something similar with other items - waist layer items (such as `scabbard`, `holster`, etc.) can't be worn when PA is equipped, but I don't see any logical reason to prevent a person from strapping things to the exterior to the power armor.

(I think - but haven't tested/checked - guns with straps also can't be worn while wearing PA.)

**Comment by Griffinhart** [comment]
1. Put on `heavy power armor`.
2. Put on `heavy survivor mask`. This works (makes sense; not wearing PA helmet).
3. Put on `heavy survivor helmet` This works (ditto).
4. Put on `diamond dental grill` .
5. `You can't wear || diamond dental grill with power armor!`

**Comment by kevingranade** [comment]
In principle there are a number of things we could whitelist for wear with
power armor. Not so sure of some of the examples, like watches and
scabbards.  Sure they would physically fit (with extension), but how are
you going to put them on while wearing power armor?

**Comment by l29ah** [comment]
It's fun i need to take off the power armor helmet before wearing my backpack; then i can put it back on.

**Comment by Night-Pryanik** [comment]
Wearing PA over watches is impossible, wearing watches over PA is impossible too.
Should be closed?
