### ISSUE TITLE
Weird Lighting Issues/Bugs with cars and houses.

### ISSUE THREAD

**Issue by erendor** [CleverRaven/Cataclysm-DDA#8495]
0.A-1885/0.A-1813
Not sure how this one works, but it's been around a while and can be reproduced from time to time.  Certain spots on vehicles, window frames, and other odd places will give you this 'light cone' look, even though no light sources exist in the places in question.  Contrast the two pictures, taken one step apart. (0.A-1813)
![lighting 1](https://cloud.githubusercontent.com/assets/4063549/3866478/698a4bd8-1fd3-11e4-9de5-5422a744f2ea.png)
![lighting 2](https://cloud.githubusercontent.com/assets/4063549/3866480/6cca0c8e-1fd3-11e4-87a8-d6b39ef52338.png)

As well as this, from 0.A-1885:

![weird lighting](https://cloud.githubusercontent.com/assets/4063549/3866487/a9f3aa5c-1fd3-11e4-81a8-1e3c8de473ab.png)
##

**Comment by Oskar636** [comment]
I'm pretty sure that the lighting system got reworked in some ways, and this bug isn't reproducable in the current experimental build 5864 windows 64bit console.

**Comment by illi-kun** [comment]
I'm not so sure I think I saw this after reworking. I want to investigate/check it deeper.

**Comment by kevingranade** [comment]
Pretty sure this was addressed with the latest (not at all recent now) lighting overhaul, feel free to reopen if you spot it in the wild.
