### ISSUE TITLE
Bicycle enhancements 0#0

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#85]
Some basic new features to round out bicycles.
Limit foot crank to operating when the player or a NPC is in the same square.
Derive foot crank power from player or NPC in same square.
Rebalance bicycle speed.

**Comment by sparr** [comment]
checking in. most of the requests at the top of this issue are done now, I think? Not the STR-based acceleration from later, though.

**Comment by KA101** [comment]
Meh, I'd hate to close Kevin's cute bicycle ASCII there.  D:
