### ISSUE TITLE
Bad texts in key-binding screen

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#8509]
Version: 7994c6db24b631be2071bf0e66ac0168b19dd78b
on ncurses

When using the key-binding screen, there are a lot of texts which are too long. They extend to the “column” where the keybindings are written.

Also, it seems that only some of the strings use the proper translation. Most of them simply ignore their translation.

Please fix this for the 0.B release, because I think this is actually pretty serious and makes C:DDA look bad.

**Comment by illi-kun** [comment]
Translation part of this issue was fixed in the PR mentioned above. Overlapping of keys by their descriptions is noted in #11918, so I see no reason for keeping this issue open.
