### ISSUE TITLE
Flickering in message log and keybinding menu (ncurses)

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#8510]
Hi!
In the ncurses version (7994c6db24b631be2071bf0e66ac0168b19dd78b), C:DDA flickers a lot in some cases when holding a key pressed if this key updates something on the console. Note that the flickering does not always affect the entire console.
“Flickering” means here that the console (or a part of it) goes black for a short time and then gets re-drawn.

Here are some instances where flickering happens:
- Keybinding menu: When I scroll this, I notice heavy flicker on each step. When I keep scrolling it is sometimes hard to read the text until I stop scrolling.
- When walking through the map, the message log in the sidebar flickers. The rest of the console is fine. Oddly, this is only the case when using the thin sidebar, the broad sidebar works fine.

I don’t know wheather there are other instances of flickering. If you know any, please post here.

I had _none_ of these flickering issues in 0.A.

If possible, please fix this before 0.B. I find this flickering highly irritating, especially in the game.
##

**Comment by Leland** [comment]
Closing - this is a very old issue. If you still run into this problem, please make a new one.
