### ISSUE TITLE
Battle text and view

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#8541]
The battle text animations like headshot, critical, grazing etc can overlap the character, but when they keep moving, they don't seem to redraw the @, just the ground underneath. Windows (SDL?) 1910 build from the dev

Also I swear I saw occasionally an "hp" moving to the right, but it is much faster than the other text, don't know if bug
##

**Comment by Leland** [comment]
I imagine that this is fixed with #24078

**Comment by kevingranade** [comment]
Many months without confirmation, please reopen if you encounter this again.
