### ISSUE TITLE
Can bind escape to commands

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#8553]
I discovered that my escape key had somehow been bound to "open map." No idea how that happened, and since I pass the same keybindings across versions, it could have happened ages ago. 

But, beside the point, you can currently bind escape to pretty much whatever you want. KA101 mentioned in IRC that escape probably ought to be reserved.
##

**Comment by Leland** [comment]
Considering how old and disused this issue is, I have a feeling that this is an issue that was present in old, imported saves. Closing.

For the second part of the issue (reserving <kbd>esc</kbd> key) see #12112
