### ISSUE TITLE
[AI?] Shockers appear to not use their special abilities through chain fances.

### ISSUE THREAD

**Issue by Greiger** [CleverRaven/Cataclysm-DDA#8611]
Possibly related to #5300 Shockers will also not zap through chain link fences.  It's not that the shocker's attack is blocked like the smoker's smoke but that they won't even attempt to shock someone on the other side of a chain link fence.

This may make public works a bit easier than intended because a player with even a basic ranged weapon can simply pick the shockers off one by one with no risk of retaliation.
![public works shockers](https://cloud.githubusercontent.com/assets/6796376/3945542/1a1534bc-2647-11e4-8e0f-8f58ba05a2eb.gif)
##

**Comment by Leland** [comment]
Siding with the faraday cage mentality on this – and besides, discussion's been stalled on this for about 3 years 🙃 Closing. Feel free to let me know if you want it reopened; or just create a new issue.
