### ISSUE TITLE
start_location.json not working properly

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#8649]
The start_location.json doc is not working properly. 
Some starts can work reliably, but need certain prerequisites;
So far I have noticed:
- LMOE Shelter starts work most of the time with small city sizes, from 8 upwards they bug out reliably.
- Underground starts seem to not work at all, at least from what I've tested, could be the same issue that prevents regular starts from time to time (meaning LMOE, Prison, hostpital, you name it)
- The "target" tag is not doing anything as someone (sorry, forgot the name) pointed out, and my testing came to the same conclusion

Of course this leads to the question why "house" and "shelter" starts work so reliably. I suppose it is because those two are pretty much in every world available. 
Yet I also had situations, where I couldn't start in a lab, even though during a different start in a mansion I had found a lab nearby.
So, if someone has the skills and the time to dive into the code I (and many others, I suppose) would be very happy.
##

**Comment by Leland** [comment]
Looks to be closed by https://github.com/CleverRaven/Cataclysm-DDA/pull/21212. Tested by spawning across 5 different world spawns in both Bottom of a Mine and Sheltered scenarios on various City Sizes running from 8 to 13. Encountered no issues.
