### ISSUE TITLE
Vehicle facing indicator does not draw in tiles mode

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#8655]
version a0e3b51 sdl 
I have vehicle facing enabled and tiles enabled, and I've set my terminal size to be about 1600 x 892 pixels + full screen (as close as I could get to 1600x900, which is my native resolution.)

In ascii mode, the direction indicator draws just fine as a white X, but if I turn tiles mode on, with any tileset I've tried, the X or whatever equivalent doesn't show up.

**Comment by DavidKeaton** [comment]
NV doesn't work *exactly* the same, but does expand LOS

**Comment by KA101** [comment]
Methinks you're talking about something else, DavidKeaton?

**Comment by sparr** [comment]
Fixing this will require updating game::draw_veh_dir_indicator() to draw a tile in tiles mode.

**Comment by Midaychi** [comment]
super bump. But yeah you'll also have to make IR and all the other detection modes draw a tile too.

**Comment by DavidKeaton** [comment]
For `game::draw_veh_dir_indicator()` in tiles mode, a superficial additive 'X' to the tile in question would suffice.

For NV/IR, however, is a bit more complicated, but not much. Iterate all tiles (cache will prob be nice), and simply do a nice src-add operation (similar to "latched" Mode X/Mode 13 operations in C/VGA I/O operations, if the bits are set accordingly, of course) to all the tiles the player can see with its appropriate color.

So, for example:

`#####`
`##x##`
`#xxx#`
`##x##`
`#####`

All `x` is tiles the player can see, all `#` are unseen.

[warning, pseudo-code ahead]
`for(auto &tile : tiles_player_can_see()) {`
`    rgba_t val = get_rgba(tile.x, tile.y);`
`    clamp_add(val.g, nv_modifier, 255);`
`    set_rgba(tile.x, tile.y, val);`
`}`
(nv being nightvision, mind you)

Anyway, enough rambling. hth.

**Comment by BevapDin** [comment]
Implemented by #13275
