### ISSUE TITLE
Gas grenades dissipate too fast to be of any use

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#8659]
Both tear gas and smoke grenades dissipate too soon to offer any concealment, smoke blocks sight only for about two turns (and also covers a very small area)  tear gas works for about 14. However, both prove insufficient for escaping angry tankbots (or zombies, or anything) coming your way.

I would suggest for they to work as a combination of a grenade/tool. That means that once the grenade ticks to 0, it will become active and continuously emit smoke for some 30 or so turns

**Comment by mugling** [comment]
Smoke grenades are fixed in master via a generic implementation which supports other fields
