### ISSUE TITLE
Mapgen Replacement Thought Dump

### ISSUE THREAD

**Issue by masecknotrealname** [CleverRaven/Cataclysm-DDA#8662]
# Map Generation Format
## Preface

The current map generation code is overrun with hard coded numbers. It is horrible. It used to be worse. Sometime ago, I added mapf to the codebase. My ultimate plan was to move these text based blueprints into files and have lua put together the files.

My ideas were quite extravegent. In fact, they were downright OCD. The only reason I started this project was because mapgen.cpp was messy and I was too compulsive to ignore it. The whole project made me fidgity so I gave up on it.

I still think the lua and files is a good idea. Whales seems to like the files and you guys seem to want to add lua. We might be able to get away with only having files so that should still be considered.
## What Can Be Improved With mapf

There were a few thing I meant to implement into mapf. Back in the day, items that were placed on funiture were done so in a hardcoded manner. There is still some hard coded item placement but most of it is gone. e.g. of this `place_items("office", 75, 4, 2, 6, 2, false, 0);`

Now we have a bunch of this.

``` C++
for (int i = 0; i <= 23; i++)
  for (int j = 0; j <= 23; j++)
    if (this->furn(i,j) == f_dresser)
      place_items("dresser", 70,  i,  j, i,  j, false, 0);
    else if...
      plac...
    else if... ... ...
```

Instead of this loop, you could bind the item generation data to the corresponding furniture tile characters. You will need to add stuff to the `format_data` structure and work through my undocumented code. Once you figure out what I wrote, it shouldn't be too hard.

This was not my original solution for item generation. What I originally was going to do was have formatted_set_\* return data including but not limited to geometric regions. `place_items` could then be run on that region. This would work by using say... `region_bind(string characters, string keys)` and then extracting the desired region using a key.
## Editor and File Format

(Note: I'm getting exausted at this point. This section isn't as complete as the on before)
[These](https://github.com/Whales/Cataclysm2/blob/23b934be2acda1de5d745c683eb2da5e65b8f9d5/data/mapgen/bank.map) are the files that Cataclysm2 currently uses for map generation. In my opinion, they are powerful enough to provide almost all of the fun features one might need from map generation. They can also be used by people who can't code.

There are problems. Most of those problems exist in our way too. It is hard to tell where objects from one floor are in relation to another floor. If you want a bunch of different item generation types, then you will need to add characters. The rng weights are in a foreign language.

What would be great is if we had an editor. We switch between levels with the press of a button. We could have seperate layers for items and terrain. We could have the rng data expanded into usable data. We could see the SDL tiles instead of weird characters.
### Lua

Label and mark locations on the map and have them accessable in lua. Awesome!!! I want to write more but I can't seem to.

---

I don't think I can coax much more out of myself right now.
##

**Comment by kevingranade** [comment]
So this is here, but it's not exactly reporting an issue, so closing.
