### ISSUE TITLE
Building Utility: list of needed work, ideas, and problems

### ISSUE THREAD

**Issue by wormingdead** [CleverRaven/Cataclysm-DDA#8693]
Hopefully, this will be a good place for discussing the Building Utility. Should this type of thing be on the forums?

Work Still Needed
----------------------
- [x] License, credit information placed in files:
 - I'm not sure how this project handles it. Is this unnecessary because of other files elsewhere?
- [x] Fix help formatting

Needs Critique & Discussion
-----------------------------------
- [ ] Second pass of documentation, comments:
 - I kinda wrote this in a vacuum, and I need to make sure others users/developers can understand it.
- [ ] Output file creation:
 - Currently dumb output file naming is adding the prefix "output_". The other extreme is to ask the user for each name which will basically double the length of the cli command. Which is worse?
- [ ] Template usefulness/usability feedback

Future
--------
- Template expansion:
 - Allow template to filter info based on contents of cell:
   - See `Examples/output_office_template.json`. It contains furniture and terrain symbols not used by individual cells.
- Actual tests:
 - This is in future because tests will by necessity nail down the template format.

Pull Requests
-----------------
- [x] #8689
- [x] #8701
- [x] #8711

Questions
------------
- Are there other inputs that work with this utility? That almost work?
- ~~Does this overlap in any way with the json audit tool?~~
 - https://github.com/CleverRaven/Cataclysm-DDA/issues/8693#issuecomment-53376130
- Does anyone use this? Am I wasting my time? (I don't mean to sound rude.)

Please let me know your thoughts. Thanks

**Comment by mugling** [comment]
This looks fairly stalled for now...
