### ISSUE TITLE
firearms balancing

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#8716]
So far firearms are working nicely but what about different approach. 
CDDA works on approach that ammunition is frequent but epic weak comparing to reality. Right now its easier to kill enemies with butterfly knife than with pistol. Guns means almost only disadvantages comparing to melee weapons. Ammo is limited, they are loud and you must be some kind of epic hero to earn headshot, and even then, most enemies will just don't care about you do and continue to eat your {insert what do you like here!}.

Why not to use damage model that allows to kill basic enemies with one round (even if its 9mm pistol, ok max two), however ammunition should be really scarce. Also differences between weapon types should be not on all enemies but only when encountering enemies that are really tough or actually wears medium or better armor. In that case all weapons can one-shot-kill weak opponents, but not every weapon can do sufficient (or any) damage to heavier targets.

Take following resources for comparison:

heavy ammo, similar to .308 sniper rifle, hollow point ammo: 
https://www.youtube.com/watch?v=S0BoPVkgVQ8
.22LR sports light rifle ammo:
https://www.youtube.com/watch?v=KyvaR5AMS3s

( i would also love to see shotgun reworked - buckshots should not be 1x50dmg but 10x5 and also displayed properly, (e.g. not like monolith projectile )

**Comment by illi-kun** [comment]
Mugling has some progress with rebalancing of firearms.
