### ISSUE TITLE
Question about overmap specials

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#8725]
Currently there is a selection of special things like science, military and drugdealer, that you can occasionally find.
1. Is it possible to create more of those using only the jsons?
   1.1 If not, which .cpp should I change?
   1.2 If yes, which jsons should I change?
2. Is it possible to add furniture or certain terrain to those places?

Thanks in advance.
##

**Comment by codemime** [comment]
Can be closed.
