### ISSUE TITLE
Gasoline madness

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#8777]
There are two issues 
1.Gasoline stored in leather containers won't make the volume of the container increase
2.For weapons using gasoline as ammo, you can just pour gasoline into it using Unload command. In this way it can be reloaded very quickly.
Combine these two features, you can burn everything that moves with just a spray can flamethrower, yeah
##

**Comment by BevapDin** [comment]
Rivet fixed the first item on the list, but what about the second?

> 2.For weapons using gasoline as ammo, you can just pour gasoline into it using Unload command. In this way it can be reloaded very quickly.

So unloading liquids into tools / guns should simply be removed? Is this consensus?

**Comment by Rivet-the-Zombie** [comment]
I like the current system. You can (r)eload such weapons normally, or use the (U)nload command the same way you do for *every other* liquid container. It's not necessary, just a matter of command consistency.

**Comment by kevingranade** [comment]
The only change needed IMO is making sure unload into tools/guns and reload
on tools/guns works the same, and ideally calls the same code to insure it
stays the same.

**Comment by KA101** [comment]
+1 for current system.  No need to overcomplicate the controls.
