### ISSUE TITLE
Car parts can hide other parts when 'e'xamining

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#8792]
On a single tile I have frame, water faucet, aisle and water tank. When 'e'xamining, only water faucet's options are available and water tank has to be filled from the car menu. This doesn't change if I remove both the aisle and the water faucet. Even when the tile contains only the tank and the frame, it has the tile of a frame and no option to fill it when 'e'xamining (goes immediately to car menu).
##

**Comment by mlangsdorf** [comment]
I think this has been fixed. Certainly vehicles tiles with multiple parts with different functions work or else controls and dashboards would be broken.
