### ISSUE TITLE
Debug message when approaching small electric substation

### ISSUE THREAD

**Issue by Zireael07** [CleverRaven/Cataclysm-DDA#8829]
Build eeb323f

Could not find monster with type 
(x2)

Resorted to debug spawning a zombie technician twice via debug menu (which works fine).
So my guess is something doesn't work with this spawn group, but a quick check verified no typos, so I don't know the exact reason.

**Comment by mugling** [comment]
Closed as unconfirmed. Please re-open if reproducible in any recent version
