### ISSUE TITLE
Attacking an NPC without seeing him will not make him hostile

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#8830]
Say, if you start at night, having some sort of ranged weapon, stand a tile away from the npc and shoot toward the tile the npc stands on, you can kill the npc without making him hostile.
Well, this can be explained in a way that cause it's at night so he can not see you either. But if you are invisible, attacking an npc while you can see him will enrage him.
##

**Comment by Night-Pryanik** [comment]
While working on #37664 I tested the case described in this issue and found it no longer valid. Firing at unseen NPC **will** make him hostile. So I guess this issue could be safely closed.
