### ISSUE TITLE
Robots does not seem to care about anything other than the player

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#8846]
No matter what happened they will only attack the player.If they are attacked by NPCs, friendly monsters like dogs or blobs, they just don't react. I've seen a tankbot killed by a friendly dog in about 12 hours.
Also, their special attack only seems to be available against the player. If you try to control a weaponed robot, it will never fire at your enemies, instead just trying to bash them

**Comment by illi-kun** [comment]
Was it fixed by #10986?

**Comment by Rivet-the-Zombie** [comment]
So it was!
