### ISSUE TITLE
Zombie icon used in place of "no tile" icon when using Hoder's tileset

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#8913]
When using Hoder's tileset the zombie icon is used for things that previously displayed the "no tile available" pink circle in 0.A. That tile still exists but it seems to be randomly used.
![cddahoderzombietile](https://cloud.githubusercontent.com/assets/8005217/4207027/48d72a22-3852-11e4-9fbe-c8cd67ca19b3.png)
Notice the bobcat shown as a zombie and the pink circles on generic trees in that screenshot. As far as I can tell this issue doesn't affect other tilesets.

**Comment by OzoneH3** [comment]
Fixed with ascii fallback.
