### ISSUE TITLE
You can wield two-handed weapons with fusion blaster arm

### ISSUE THREAD

**Issue by malakhim** [CleverRaven/Cataclysm-DDA#8915]
With fusion blaster arm installed:
1. Drop the 2-handed weapon (for me, it was a compound bow that the Hunter profession starts with)
2. Pick it up again
3. Voila, you're wielding a two handed weapon that you couldn't normally do if you use the inventory.

**Comment by Night-Pryanik** [comment]
Unconfirmed. Should be closed?
