### ISSUE TITLE
Freeze/infinite loop on disassembly

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#8927]
0.A-6535-g6c593ff
Linux 64

After a long battle with numerous zombies, I was trying to make room for all the loot, so I disassembled a file (hoping for paper which would be lower volume). There were a few zombies at the edge of my vision range (but unaware of me), so it gave the "are you sure?" dialogue. I hit yes.

Game thought about it for a long time (overnight), but nothing happened, no update to screen, etc.

Possible factors:
- Dynamic spawn with hordes, and I was within a small village (3-4 buildings)
- Zombies within sight

No save to check as when I killed the game and reloaded, it was 6+ game hours earlier, so autosave wasn't working either (I will log a separate issue for this if I can recreate it).
##

**Comment by illi-kun** [comment]
I see no obvious way to confirm this issue and I see no similar complains in the last two years, so I'm closing this issue. Please let me know of this issue is reproducible and I'll reopen it.
