### ISSUE TITLE
Occasional Monster Invisibility

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#8974]
Sometimes entities vanish for a round or two when things are going on, and I suspect it has something to do with the popup messages like Left Leg when someone is hurt, or the damage indicators like that. I noticed that when someone was running away from me, there was a screenmessage and it went over the tile they were in and then when it vanished they were invisible. Then, they came back the next round. It seems like the messages are fading into the tile beneath them, but not drawing entities in that tile.
##

**Comment by Leland** [comment]
2 year stall in discussion and this never saw verification. A lot has changed in the code over that time - if anyone encounters this, you'd probably be best off opening a new issue about it. Closing.
