### ISSUE TITLE
Mi-go are no Amigos. Maybe unbalanced?

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#8995]
Three of my last five characters have died from Mi-Go. They are very powerful, which is ok. I think that their speed may be too high, though. I wasn't able to lose one even though I was fleet-footed and taking adderall until my speed was 113. It basically spells my doom when I run into one at least early on because I have no option other than to fight since flight does no good. They also seem way more common than they were before. I see them most games in the cities. Before I used to only really see them in labs. I feel all of these factors together as making them a little unbalanced.

**Comment by kevingranade** [comment]
> forget I said anything
