### ISSUE TITLE
Crafting food doesn't show amount produced if more than one portion

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#9013]
For example, lard or meat jerky recipes: regardless of how many you craft, log will still say: `[L] - cracklins (hot)` and `[L] - meat jerky`. Lard has `1 cracklins (fresh) (4)` as byproduct, while meat jerky produces 3 portions per craft.
This interferes with batch crafting, because it will not show how many times you crafted something - 1,2 or 20, it won't show the number, whether multiplied by portions or not.

Suggested look: `[L] - [item] ([portions]) x [times crafted]`, i.e. `[L] - cracklins (fresh) (hot) (2) x 6`.

P.S. Portioned foods stack in containers as well, unlike non-portioned. Is there any way to select a number of items to pick up instead of picking up entire stack of them?
P.P.S. Please don't break stacking of portioned food in pickup menu while fixing this. Having things NOT stack is superbly annoying to navigate through.
P.P.P.S. Yes, there is number-pick. The number just isn't shown absolutely anywhere, same as with number-dropping.
##

**Comment by Leland** [comment]
Looks like discussion never took off with this one. Closing. Feel free to let me know if you want it reopened; or just create a new issue.
