### ISSUE TITLE
Add a flags field to oter_t and use it to eliminate enum hackery in overmap.cpp

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#902]
Due to the lack of metadata in the oter_t structure, code in overmap.cpp resorts to comparing enum ranges to determine properties of tiles, adding flags to this struct would clean up the code greatly.

**Comment by BevapDin** [comment]
Does 166fe2fb92ecfa4dd1dd49dbe8c9957eb69fa812 count as solution? It added flags as a bitset. If sou, this should be closed.

**Comment by i2amroy** [comment]
Yeah, closing.
