### ISSUE TITLE
2 issues with the tutorial - version 0.A SDL - Windows

### ISSUE THREAD

**Issue by Snipie** [CleverRaven/Cataclysm-DDA#9086]
1- The tutorial treats objects as symbols. Example: "That brown '+' next to you is a closed door."
2- I tried the tutorial for first time and it worked fine then I wanted to quit so I made the character commit suicide -I think the game exited by itself after that- then every time I choose tutorial, the game exit by itself. I fixed it by renaming the directory "/save/tutorial" to something else and the game created a new one.

**Comment by Soyweiser** [comment]
We should really update the tutorial for 0.D btw. If nobody has looked at it recently.

**Comment by mugling** [comment]
Discussion continues in #17984
