### ISSUE TITLE
Flaming Eye's wallbreacher

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#9139]
FE's burst of light doesn't do appreciable damage (in Survivor gear, anyway) but easily breaks any walls between eye and you, tending to bring houses down on your head.

**Comment by kevingranade** [comment]
Flaming eye wall destroying attack removed :D

**Comment by DavidKeaton** [comment]
so it doesn't rip up terrain anymore? :-(

**Comment by kevingranade** [comment]
Nope, if you want there to be a terrain-destroying monster that makes
sense, please add or propose it :)

**Comment by DavidKeaton** [comment]
fair enough!
