### ISSUE TITLE
'!' is used as a bionic designation, becomes inaccassable

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#9170]
in 'p' to use bionics, '!' is the key to toggle inspecting a bionic rather than using it. However, when you have a crap-ton of bionics and work through the normal alphabetic designations twice, you get one that gets designated '!', but you can never use or inspect it because that key always toggles inspect mode.

**Comment by illi-kun** [comment]
Closed as a duplicate of #10563 (which contains more useful info).
