### ISSUE TITLE
Policebots attack cuffed characters

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#9171]
Only riotbots respect cuffs. Even when they cuff a zap-immune cyborg who then proceeds to beat them up while cuffed.

Eyebots will keep taking pictures and spawning policebots. Policebots will keep using tazers and delivering beatings while telling the target to drop the "weapon". Policebots attacking unarmed characters is excusable (brawling can hit hard too), but beating up a cuffed character is just nasty and makes the entire option not to resist arrest more of a new player trap than an actual option.

The intended way of removing cuffs is cutting them up and that's why they're made of plastic and not steel, right?

**Comment by Rivet-the-Zombie** [comment]
Is it wrong that I want police-bots to occasionally shout 'STOP RESISTING' while they do this?
