### ISSUE TITLE
Zombie dancer won't become zombie hulk if zombie jackson is killed far away

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#9249]
If for some reason a zombie dancer is not in the same map with zombie jackson, even after the jackson is killed the dancer will still be a dancer and can (almost) never be killed

**Comment by sparr** [comment]
Maybe the fix for this is to change dancers to hulks when they aren't near jackson any more?

**Comment by kevingranade** [comment]
I very much do not want dancers changing to hulks unless we're absolutely
sure thriller is dead, they're supposed to be impossible-ish to kill but
mostly harmless™ until the thriller is killed.

**Comment by mugling** [comment]
Closed as unconfirmed. Most of this content was also shifted to a mod and is disabled by most players
