### ISSUE TITLE
Safe mode (filter what is safe and not)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#9285]
Hi all I was wondering would it be possible to assign what is safe and what is not?.

I mean if I enable safe mode and walk around all I get is warnings of dogs or things that are not really 100% threat so I disable the auto safe mode and move on but then forget to enable it and end up walking into some thing bad.

So can we say for example be able to assign what triggers a safe mode action?.
Or have it so it goes into safe mode and you can then say ignore forever this animal etc?.

Thanks :)

**Comment by mightyagrippa** [comment]
Is this any less hairy to work with after a year and change? It would be a real boon if you could tailor your safe mode triggers to your current level of capability.

In addition to the case where dogs and such interrupt your work, most characters hit a point where basic zombies are more of a difficult terrain than an actual hazard. Customizing the safe list would also be great when you outfit yourself against specific dangers. Once I've decided to wear fireboots and turnout trousers, for example, I don't care about getting a 50 tile warning about any of the acid zombies.
