### ISSUE TITLE
Request - Rearview mirror layout update + mirror on a stick

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#9376]
As in the title, I think at some point, it'd be a pretty good idea to add rearview mirrors to the existing vehicle layouts, especially since they work pretty well now.

 Maybe add hand mirrors to garages too, and/or change the recipe to use a 'rearview mirror' and have the rearview mirror be a minor fabrication and/or mechanics recipe with some duct tape and scrap metal.

As a bonus to the above, I guess you could then alternatively make a 'mirror on a stick' recipe. Wielding it could let you view from adjacent tile points of view without having to use X to pop out and risk exposing yourself.

As an abstraction of the above, you could use the same code to make a corner-shot kind of weapon of varying qualities; a horribly inaccurate one using a red dot mod and a mirror and a pistol + a makeshift cornershot mount, ranging to a high end UPS-powered version with electronic screen and a laser pistol.
##

**Comment by illi-kun** [comment]
Further discussion of alternative car mirrors can migrate to #11618, inboard mirrors were implemented in #11726, 'mirror on a stick' part of request is a negligible one.
