### ISSUE TITLE
Idea: a better battle rifle conversion

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#9428]
Instead of having the battle rifle conversion be a few changes to stats, actually have it change the available mod slots for a gun. (Or, alternatively, have something like a "tactical conversion kit".)

This is an M1 Garand: http://upload.wikimedia.org/wikipedia/commons/9/9e/M1_Garand_rifle_-_USA_-_30-06_-_Arm%C3%A9museum.jpg

This is an M1 Garand dropped into a Sage EBR stock (plus optic, bipod, and grip): http://www.thefirearmblog.com/blog/wp-content/uploads/2012/03/sag_ebr_stock-tfb.jpg

As you can imagine, one is significantly more amenable to tacticool modifications than the other, plus it makes certain weapons more distinguishable from others (e.g. M14 vs. M14 EBR-RI differ - last I looked - only by a little bit of damage and accuracy).

**Comment by mugling** [comment]
Much of this is already implemented apart from the conversion mods which were deprecated entirely
