### ISSUE TITLE
Dehydrated Fruit VS Fruit Leathers! Worse in every way or misunderstood??

### ISSUE THREAD

**Issue by Learner10** [CleverRaven/Cataclysm-DDA#9443]
It has just occurred to me that at some point, these things seemingly got unbalanced.
Why is it that Fruit Leathers (a cooking recipe set at a difficulty of 1), which stop the fruit from spoiling past creation... give three potions to eat for 1 fruit, plus the cost of a sweetener (which is a ratio of 3:1 for portion/fruit)... while the more difficult crafting recipe, which is Dehydrated Fruit (set at the difficulty level 2), which also needs more difficult to find tools... only gives 2 potions, but also REQUIRES 2 fruit to create in the first place (meaning it's a 1:1 ratio for portion/fruit)?

It's made worse when you consider a few things: to really get the best out of dehydrated fruit, it must be rehydrated, so to make the stats match a fruit leather, water must be consumed...

Maybe there's a reason behind this decision. I don't know! But just on the surface, it seems... very peculiar that the harder recipe gives less results (and therefore, pretty much never gets used at all)...

Here's the difference if we calculate what sort of return we get per fruit required by the crafting recipe. For dehydrated fruit... 1 fruit=16 nutrition, -2 quench & 2 enjoyability. That's per portion. Adding water leaves it at 18 nutrition, 1 quench, and 4 enjoyability.

But for a fruit leather... 1 fruit+ a sweetener= 54 nutrition & 9 enjoyability, all spread across 3 potions. That's a whopping 36 point difference...

So... clearly, something just doesn't seem right here.

**Comment by Night-Pryanik** [comment]
Should be closed after #9527?
