### ISSUE TITLE
World Generation - Input Conflict

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#9455]
Version: 0.A-7739-gd618eda.
1. New Game
2. Preset Character
3. Automated gas stations, Boats, Classic Roguelike Classes, DinoMod, Icecoon's Weapons Pack
4. Static npcs, Random npcs
5. On the CONFIRMATION page, attempt to randomize World Name with `?` - the Keybindings menu pops up instead.

Not sure if 3. and 4. are necessary, but that's what I did.
##

**Comment by illi-kun** [comment]
It seems that default keybinding for random name was changed from '?' to '*' more than two years ago so I don't think it's significant issue now.
