### ISSUE TITLE
Feature Request: Internal Lighting (Vehicles)

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#9475]
Why car's internal lighting is not implemented in the game yet? It's extremely useful stuff & I don't know why I missed this earlier (yeah, this idea may be visualized as a lightbulb appeared over my head but I would prefer bright lightbulbs over my protagonist's head, if you know what I mean).

NB: implementation of the request may break the game's balance.

**Comment by narc0tiq** [comment]
Oh, hey, I think we can close this -- implemented by #10715, a while back.
