### ISSUE TITLE
map i_at() accessors?

### ISSUE THREAD

**Issue by CIB** [CleverRaven/Cataclysm-DDA#9517]
Currently, `map::i_at()` returns a modifiable reference to the internal item list of the submap. This obviously has drawbacks.

I'd like to make `map::i_at()` return a const. For adding/removing items, this is fine. But for modifying items, this means extra code will be required in all code that does modifications, to first create a modifiable copy of the item, and then to replace the item in the submap with the modified copy.

@kevingranade @BevapDin thoughts?

**Comment by kevingranade** [comment]
Implemented this as an item_stack with specializations for map and vehicle inventories.
