### ISSUE TITLE
rebars

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#9565]
Where are the rebars now? in the old days you burn down a building and can get tons of them, but now burn down a building you will only get stones and nails. Since some recipes do require rebars, and there are not other ways to get rebars (like crafting) this means you can never make a jackhammer / coilgun unless you disassemble something.
##

**Comment by keyspace** [comment]
Rebar can be gotten from pavement (roads), and is present in `data/json/item_groups.json` for `hardware`, `hardware_bulk`, `mischw`.

OK to close?

**Comment by WizardOfOoo** [comment]
Rebar can be harvested by activating a pickaxe on roads now.
Since the original complaint was that there wasn't a good source of rebar, I think this is safe to close.
