### ISSUE TITLE
Vehicle interaction window: hotkeys and drawing

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#9572]
Two minor interface issues that are probably fixable from the same places:
- when changing the hotkey assigned to one of the vehicle interaction keys (e.g. `rem<o>ve`), the highlighted letter in the menu at the top remains the same, even though 'o' no longer performs that action. Correct behaviour should probably be to try to find a letter in the word "remove" that can be highlighted, or not highlight any letter at all (bonus points: show something like `remove [n]` -- but this may break on min-size displays. The menu in veh_interact is already close to the 80-column limit (in English/unlocalized)).
- when the keybindings screen is closed, the vehicle interaction window does not redraw and the player must close and reopen it.
##

**Comment by Leland** [comment]
Second note has an issue for it in #8514.
