### ISSUE TITLE
Some new json fields for gunmods

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#9604]
While reading this http://smf.cataclysmdda.com/index.php?topic=8039.0, it occurred to me there's a few things still missing from the new gunmod system.  Specifically, we have no way to account for mods that may reduce a gun's total weight or volume, due to their replacing parts of the existing gun.
We can't, for example, have a collapsing stock mod that makes a gun take up less space, as all mods currently just add their weight and volume to what they're attached to.  This also doesn't make much sense for internal mods like rebuild kits; they shouldn't make the gun take up more volume, but they shouldn't have zero volume when not attached to something either.

I propose we add some optional field for gun mods to allow people to specify how much the mod affects the weight and volume of what it's attached to, separate from the weight and volume of the gunmod itself.  For example, the collapsing stock would have weight and volume when it's sitting in your inventory, but when it's attached to something, that something will be LIGHTER and SMALLER than it was before, because you ADDED the collapsing stock and REMOVED the old stock.

This does bring up an issue of where the original parts go, but I think we can abstract them out just for reasons of gameplay and general maintenance of sanity for everyone concerned.

Does anyone want to try coding this?  I'm not very skilled at this stuff myself (not even sure if my git setup works anymore), but I don't think it should be too complex.

**Comment by mugling** [comment]
> We can't, for example, have a collapsing stock mod

Was added in #12300

> This also doesn't make much sense for internal mods like rebuild kits; they shouldn't make the gun take up more volume, but they shouldn't have zero volume when not attached to something either.

Was implemented by #15157 as `integral_volume`
