### ISSUE TITLE
Idea: hand crank generator

### ISSUE THREAD

**Issue by Darkyhard** [CleverRaven/Cataclysm-DDA#9642]
Just what the title says. It would allow to convert muscular force into electricity and recharge tools that have rechargeable battery pack installed. Something like this: http://tinyurl.com/o86bhcc

I think it would need 3 minutes to generate 1 charge for tools to use.

**Comment by sparr** [comment]
Reviving this thread... Isn't there a pedal powered generator for electric vehicles now? I thought I saw that in some patch notes.

**Comment by KA101** [comment]
Yes, there is.  I'm thinking this can be closed.
