### ISSUE TITLE
Performance issues in last builds

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#9643]
In the latest tiles builds (for a week or two) there is a severe decrease in performance. As of now there is a chopping and big latency between screen refreshes. It is confirmed for me both on laptop (I5 4200U x2.4Ghz, GTX740M); desktop (I7 3770K x4.2Ghz, GTX680) and my friend's desktop (Core2Duo x2.3GHz, AMD 3600).

**Comment by kevingranade** [comment]
Not an addressable issue, probably fixed with the item processing overhaul, but impossible to be sure since the report is so vague.
