### ISSUE TITLE
Make use of the MediSoft USB drive

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#9684]
The hackPRO usb drive has its control laptop, let's find a nifty use for the MediSoft counterpart.

I propose something along the lines of:
- laptop + medisoft + chemset + vacutainer = medical laptop
- can analyse your dna and with that make targeted mutagens, serums and purifiers
- you still need to first make/find a specific mutagen/serum/purifier; this only refines it
- for mutagens of specific 'line' (e.g. lizard) increase probability of actually getting a mutation from that line
- for serums increase not only line specificity but also the probability of getting a good mutation
- for purifiers increase the chance of getting rid of bad mutation(s) while leaving the good ones
- with end-game skill levels maybe even make stuff targeted for specific trait

Let the discussion commence!
##

**Comment by illi-kun** [comment]
Conclusion from #17158:
Laptop should be a universal device expandable with optional modules like control module for hacking robots, medical lab module for blood test, etc.

**Comment by Leland** [comment]
Discussion's been stalled on this one for about a year now. Closing. If anyone still has an interest in this, free to let me know here that you want it reopened; or just create a new issue.
