### ISSUE TITLE
Safe cracking never fails.

### ISSUE THREAD

**Issue by BevapDin** [CleverRaven/Cataclysm-DDA#9695]
`iexamine::safe` has a boolean `success` which controls whether the safe cracking was successful, but that variable starts with true and is *never* set to anything else. Therefor the non-success branch is never run and the safe is always opened.

I suggest to either removing the variable and the check completely, keeping the current behavior without useless code.

Or adding some kind of check (based on dexterity?).

The PR "No safecracking when deaf"  does not affect this.

**Comment by sparr** [comment]
in nethack, it's possible to be unable to pick a lock at all, in which case you have to resort to other ways to get the chest/door open. I'm thinking we might want some characters to be unable to crack a safe, and make them go find a torch or power tools. of course, that would mean implementing those alternate methods.

**Comment by karlnp** [comment]
@i2amroy had a blowtorch PR at one point but it seems to have fallen by the wayside.

**Comment by Soyweiser** [comment]
Ancient issue, while there is no failure for safes now still, the useless code mentioned has been removed. And there are now checks and requirements for normal safe cracking. (gunsafees are different).

See: http://www.wiki.cataclysmdda.com/index.php?title=Lockpicking

So think this could be closed now right?
