### ISSUE TITLE
Multi-coverage armor takes damage unusually quickly in damaging field/AOE/hulk smash attacks.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#9705]
Any single piece of clothing that covers a large area of the body suffers 'hits' against it many times over in these cases due to the attack striking multiple areas of the body at once; the more locations it covers, the worse the effect.

We need something in the clothing damage code to limit the number of damage checks per clothing article per damage event to one.

**Comment by Rivet-the-Zombie** [comment]
The hulks' new(ish) ability to smash you and send you flying has made this one really apparent. One good whack can outright destroy many forms of full-body armor even if it's reinforced.

**Comment by DavidKeaton** [comment]
This. I just fought a brute that kept putting reinforced armour to yellow on a single hit, to multiple items.

**Comment by Rivet-the-Zombie** [comment]
This one is so brutal that I kind of want to mark it as a blocker-issue.

**Comment by KA101** [comment]
Done.

**Comment by Rivet-the-Zombie** [comment]
Another example of this is spitter acid versus stuff like powered armor.

A player has reported on the forums that smashing a spitter's corpse splashed enough acid on their feet that their entire suit of reinforced Doubletech powered armor evaporated in a single turn.

**Comment by kevingranade** [comment]
Will do a little more testing, the hurtall function was still calling the old player::absorb() method instead of the player::absorb_hit() method, the calculation for armor taking damage had been changed.

**Comment by kevingranade** [comment]
I'm still on this BTW, just haven't had much time to work on it.
