### ISSUE TITLE
Assault on precinct Z - Professions unbalanced

### ISSUE THREAD

**Issue by Jiamil** [CleverRaven/Cataclysm-DDA#9804]
The cop costs 2 points, the detective 4.

Detective seems to be overpriced: Weapon is only slightly better, equipment is almost on par and on top the detective has a nicotine withdrawal (which is worth 1 point looking at the chainsmoker profession). Skills are also equal.

In need of a fix, maybe lesser cost for detective or better equip/skills?!
Speaking skills would be nice to have, mechanics 1 and a lockpick set, too.
##

**Comment by kevingranade** [comment]
Ancient points nitpick, closing.
