### ISSUE TITLE
Vehicle UI parts list overlap

### ISSUE THREAD

**Issue by malhawee** [CleverRaven/Cataclysm-DDA#9808]
At default terminal size, parts like 'upgraded reinforced solar panel' wrap around in the 'list of installed parts' menu when in horizontal vehicle UI mode. This also occurs in vertical mode but not quite as badly. A solution could be to make a new line if the length of the name is longer than the width of the window.
![screenshot - 031114 - 09 40 16](https://cloud.githubusercontent.com/assets/9424695/4877214/429c9124-62e1-11e4-9f0e-29dc01eec97a.png)

**Comment by mugling** [comment]
Display has since been rewritten. Please re-open if reproducible in any recent version of `master`

**Comment by illi-kun** [comment]
That's an actual issue for horizontal menu, take a look on a snapshot from current master:
![horizontal_menu](https://cloud.githubusercontent.com/assets/5421954/14589944/6aa41d06-04ff-11e6-82ab-bbafdf8f89cd.png)
