### ISSUE TITLE
Sledge hammer science lab bionic computer access tweak

### ISSUE THREAD

**Issue by hustergeyser** [CleverRaven/Cataclysm-DDA#9824]
In version 50cef5d in science labs you can use a sledge hammer to get into bionics by smashing the wall around it, ignoring the computer unlocks or reinforced glass.  I was thinking it might be better to implement a stronger wall unless it was intentional to allow the sledge hammer access option.
##

**Comment by Night-Pryanik** [comment]
Right now bionics have concrete walls around them, and they can't be damaged by sledgehammer. Also, ordinary walls now have strength 30. 
Should be closed?
