### ISSUE TITLE
Alt-tabbing from Windows SDL Fullscreen spams debug log until crash

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#9880]
Downloaded 0.A-2349, after expanding the terminal to fit a 1280x720 fullscreen resolution (160x45), alt tabbing away from the game produces one instance of this error message:
10:9:43.931 SDL : src/sdltiles.cpp:557: SDL_SetRenderTarget failed: Texture is not currently available

These other messages get generated at about 1.5 million total messages a minute.
10:9:43.932 SDL : src/cata_tiles.cpp:818: SDL_RenderCopyEx(bg) failed: SetTexture(): INVALIDCALL
10:9:43.932 SDL : src/cata_tiles.cpp:853: SDL_RenderCopyEx(fg) failed: SetTexture(): INVALIDCALL

Tabbing back into the game stops the message spam and produces one more instance of this message:
10:9:46.962 SDL : src/sdltiles.cpp:557: SDL_SetRenderTarget failed: Texture is not currently available

The game crashes after the debug log reaches about 400 MB, if the game is left tabbed out for a few minutes.

**Comment by mugling** [comment]
Unconfirmed in obsolete version. @DanmakuDan please reopen if this remains a problem for you in `master.
