### ISSUE TITLE
Redundant construction plans

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#9898]
I noticed some redundant construction plans. This is not really a serious bug or maybe this is not even a bug at all, but it clutters the description part of the construction menu and it could be simplified IMO.
- **Tape Up Window**: There is 3 times the exact same construction plan.
- **Reinforce Boarded Window**: Same plan repeated twice.
- **Armor Reinforced Window**: Same plan repeated twice.
- **Build Stone Wall**: Same plan repeated twice.
- **Realign Fence**: picket fence and chain link fence plans appear twice each.
- **Take Paint Off Wall**: Same plan repeated twice.
- **Paint Wall [some color]**: Same plan repeated twice.

(As of f94a402b102967ea3051ca3b042f84c0a9f4a6c1)
##

**Comment by OzoneH3** [comment]
The window naming has been taken care off.
