### ISSUE TITLE
For item recipes, merge skill_used into skills_required

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#9939]
It used to be that all recipes had a single primary skill requirement (still present as `skill_used` + `difficulty`) and a single optional secondary skill requirement. The secondary skill checks have since moved into a `skills_required` JSON array which explicitly supports listing multiple named skills and levels (e.g. as `"skills_required": [[ "survival", 1 ], [ "throw", 2 ]]` from the javelin recipe).

As the support now exists for an arbitrary number of skills being listed as `skills_required`, we should consider merging the "primary" skill into the list of skills required, which will make things easier for folks reading and writing recipes. This should **not** otherwise alter recipe behaviour or availability (handle with care).
##

**Comment by narc0tiq** [comment]
See also #11052.

**Comment by Asmageddon** [comment]
I have an unmaintained branch that changes some of this stuff, but I've dropped working on it because mental health issues. I've got JSON loading of a format similar to the one presented in #11052 mostly done.

**Comment by Leland** [comment]
Closing this due to years of stalled discussion.
