### ISSUE TITLE
Zombies too mobile in water

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#9950]
Zombies are just too capable of getting around underwater. Even zombie dogs, they aren't slowed down if you try to lead them through deep water or escape with swimming; they charge along the bottom unimpeded and are actually faster than an intentionally swimming human. Swimmer zeds are excusable in this regard, but for others they should be nearly as slow as going through deep pits, and probably visually hampered as well.
##

**Comment by kevingranade** [comment]
This seems like a very easy-to-apply move penalty for monster types that can move underwater without swimming.

**Comment by Headjack** [comment]
Bumping cause it happened again; can't escape regular zeds with swimming. Also, shockers and shocker brutes aren't really affected by being in water, so far as I can see. I don't know if it would hurt them or hurt people near them, though...
