### ISSUE TITLE
Constructing curtains uses whole stack of sheet.

### ISSUE THREAD

**Issue by RenegadeElement** [CleverRaven/Cataclysm-DDA#9961]
Installing curtains in a vehicle causes it to consume a whole stack of sheets, when if i drop my sheets far away and only pickup 1 I can install curtains as expected.

Issue damn windows are being sheet greedy. Making installing curtains possible but a pain.

Tested on 	cataclysmdda-0.A-2359.zip	I don't know the code for it sorry.

**Comment by mugling** [comment]
When tested is no longer present in `master`
