### ISSUE TITLE
Blankets(sheet, flag) coverage

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#9963]
i know you are worried for mutants, but it results in my feet and hands getting unnecessary warm, maybe we can make them activatable, removing coverage from parts that you choose?

**Comment by ArikVhedrovix** [comment]
As a unwilling subject in Lab Challenge, I was quite grateful to find a blanket for evening wear. =) Yay for not freezing to death until I can sew together something better! I did have to take it off to put on sneakers though which I think is maybe a bug.

**Comment by DavidKeaton** [comment]
Curious, is there a way to escape the lab?

**Comment by ArikVhedrovix** [comment]
Yup. I have escaped many times. Usually by using a teleporter. I think there may be other ways like finding/making explosives to rupture the outer walls of the ground floor entrance. I like to start this way because it gives a lot of points.

**Comment by DavidKeaton** [comment]
exactly why I love really bad day. ;-)
