### ISSUE TITLE
In Lab, Ants seem to spawn from nowhere

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#9969]
I was doing the lab challenge and ants just started to apparently spawn from nowhere. I saw two soldier ant appear two spaces away when they weren't there before. I had gone up stairs maybe 5 turns before. I am using Windows Experimental 96dcd9c.
##

**Comment by EditorRUS** [comment]
I've reported this bug a long time ago
http://smf.cataclysmdda.com/index.php?topic=9112.msg207263#msg207263

**Comment by kevingranade** [comment]
Now that I see this again, I realize what's happening.  Ants are still
using the dynamic spawn code, which just uses a point and a radius.  If the
lab area is inside that radius ants can spawn there.  A quick fix would be
to patch dynamic spawn to check the type of the map type, but I'd really
prefer to just rip it out and replace it.

**Comment by illi-kun** [comment]
I saw this bug previously but I have no idea if it's still an issue.

**Comment by Oskar636** [comment]
I think that ants cutting into labs should be considered a feature, the spawning algorythm though is a bug if it works like you say it does. Anyway I just want to link this issue to #14136 since it seems related.
