### ISSUE TITLE
Special Characters prevent Character Templates from Saving

### ISSUE THREAD

**Issue by EricFedrowisch** [CleverRaven/Cataclysm-DDA#9972]
When saving character templates, some special characters in the template name cause it to fail to save silently, others give an error message. So far I have tested:
Characters that cause silent failure to save:
$, :
Characters that fail and give error message "Failed to write template to ./templates/<Name>.template":
*
##

**Comment by Leland** [comment]
Regarding the slash, note that in #18721, someone actually ran into that exact issue with world naming.

>My world, on multiple characters, will no longer load because of an extra slash being inserted in the address (e.g. save//World Name/...).

**Comment by AMurkin** [comment]
Need same approach as with character save filenames:
> The savegame uses the base64-encoded player as base path.

See for example recent #20975

**Comment by OzoneH3** [comment]
This got fixed at some point.
